### ISSUE TITLE
#SP Desenvolvedor(a) Back-end PHP

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/vagas#1]
**Descrição**

A Slikland é um estúdio criativo de desenvolvimento. Nosso foco é produzir projetos criativos digitais voltados para a publicidade. 

Estamos à procura de um(a) Desenvolvedor(a) Back-end que tenha experiência em desenvolvimento de sistemas para projetos interativos dentro do mercado publicitário digital, que saiba utilizar o máximo de suas ferramentas para criar um projeto integrado fodástico. Aqui você vai pensar fora da caixinha e poder utilizar todo o seu conhecimento para agregar ao nosso time.

Se você se encaixa neste perfil, bora bater um papo com a gente!

**Requisitos**

- Experiência no mercado publicitário digital
- Sólidos conhecimentos em OOP
- Conhecimento avançado em PHP puro
- Conhecimento avançado em MySQL
- Conhecimento em banco de dados não relacionais
- Integração com APIs e SDKs externas (Facebook, Google, Twitter, etc.)
- Pensar em soluções além do stackoverflow
- Comprometimento e facilidade para trabalhar em equipe
- Bom humor

**Desejável**

- Conhecimento de desenvolvimento Front-end
- Conhecimento de outras linguagens de Back-end
- Conhecimento de outras linguagens além de web
- Noções de estruturação e configuração de servidores
- Integração com outras ferramentas em Server-side (FFmpeg, PhantomJS, OpenCV, etc.)
- Fazer um bom café

**Benefícios**

 Vale-transporte ou estacionamento
 Vale-refeição
 Flexibilidade de horário
 Férias remuneradas
 Bônus anual
 Caneca de café

https://trampos.co/oportunidades/132826

**Comment by Pedro-Souza** [comment]
@reginaldojunior em questão de Junior, continua os mesmo requisitos?

**Comment by reginaldojunior** [comment]
@Pedro-Souza a vaga não é minha, peguei no trampos.co para ir preenchendo aqui. 

Mas se quiser estou com uma aqui na @plugg-to tiver afim me manda currículo, meu e-mail é reginaldo.junior@plugg.to
