### ISSUE TITLE
 [São Paulo/SP] Desenvolvedor(a) PHP na Plugg.to

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/vagas#10]
### Tarefas:

    - Criação de integrações utilizando APIs em REST e/ou SOAP;
    - Criação de interfaces web;
    - Manutenção de aplicações de legadas;
    - Modelagem de banco de dados;
    - Criação de documentação.

### Local

Escritório a 5 min do metrô Barra Funda - SP.

### Benefícios

    - Vale-transporte
    - Vale-refeição
    - Horário Flexível com banco de horas

#### Obrigatórios:

    - PHP, Laravel
    - REST Service
    - JSON
    - XML
    - MySQL
    - Javascript

 #### Desejáveis:

    - Git
    - Linux Debian

### Diferenciais:

    - Projetos opensource
    - TDD
    - Design Patterns

### Contratação

CLT

### Nossa empresa

Plugg.to é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces.

Com isso é possível vender muito mais utilizando múltiplos canais de venda, mantendo porém estoques sincronizados, e recebimento e gerenciamento de pedidos em um único ponto.

Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

Sempre buscando a excelência, Plugg.To é mais um produto ThirdLevel notoriamente conhecida por sua primeira integração apenas entre MercadoLivre e o Magento que é utilizada por mais de 300 lojas em 4 países.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015
Como se candidatar

Por favor envie um email para reginaldo.junior@plugg.to com seu CV anexado - enviar no assunto: Desenvolvedor(a) PHP

**Comment by deyvisonrocha** [comment]
@reginaldojunior Python? Acho que clicou na label errada. hehehe

Olha, aceita remoto?

**Comment by reginaldojunior** [comment]
@deyvisonrocha é que temos uns projetos novos em python, mas não é obrigatório.

E não, só presencial por enquanto :)

**Comment by reginaldojunior** [comment]
Preenchida! ❤️
