### ISSUE TITLE
[Sorocaba/SP] Fullstack Developer na Goomer

### ISSUE THREAD

**Issue by rafalag** [backend-br/vagas#100]
## Descrição da vaga

A Goomer é uma start-up de Sorocaba que trabalha com tecnologias de auto atendimento para restaurantes. Temos 3 anos de vida e já ajudamos os restaurantes no atendimento de 6,5 milhões de pedidos. Temos a missão de melhorar a experiência de consumo dos restaurantes do Brasil.

A vaga é para desenvolvedor full stack com foco em PHP (Laravel), programação web (html, css e javascript) e Node.js

## Local

Sorocaba/SP

## Benefícios

- Vale Refeição
- Vale Transporte
- Cursos
- Horário flexível
- Stock Option (participação na empresa)

## Requisitos

**Obrigatórios:**
- PHP
- Javascript
- HTML e CSS

**Desejáveis:**
- Conhecimentos em Laravel
- Conhecimentos de Node.js

**Diferenciais:**
- AngularJS, Ractive.js ou Vue.js

## Contratação

- CLT
- Pode ser PJ (se preferir)

## Como se candidatar

Inscreva-se pelo link: https://goo.gl/forms/wsY6rjZ1re4IVGZY2

## Labels

- CLT
- Pleno
- Presencial (com possibilidade de home office em alguns dias da semana)

**Comment by josebispo** [comment]
Boa tarde @rafalag , que bacana essa vaga, remoto parcial, poderia explicar melhor?

**Comment by rafalag** [comment]
@josebispo preciso corrigir. A vaga é presencial, mas tem a liberdade de fazer uns home offices.

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
