### ISSUE TITLE
[Senior Backend Engineer with Ruby with English] - Início Remoto, mudança para Portugal necessária.

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#10009]
[Senior Backend Engineer with Ruby with English] - Início Remoto, mudança para Portugal necessária. 2K Euros a 3.5K Euros.  Mais de 8 anos de experiência.

Software Consulting founded with the mission to inspire the connection of technology with people, fostering the best of our professionals through our expertise in finding and attracting the best talent for the best projects.

What You’ll do: 

● A lot of Ruby, and increasingly a wide variety of programming languages: Java, Scala, Elixir, PHP and, most recently, Kotlin. We'll match you with the right technology team depending on your background and preferences. ● Prometheus and Grafana for metrics and alerting. ● Kafka and RabbitMQ as message queues, the former is now increasingly used for event-driven systems. ● Dierent databases for dierent needs: MySQL, Postgres, Cassandra, MongoDB, ElasticSearch. ● GraphQL (implemented in Scala & Sangria) for our mobile and web APIs. Experience and Skill Requirements You care about the craft of software development and strive to build testable, predictable and simple code; You want to tackle the engineering challenges that come with building systems at scale (highly available, low latency and high throughput); 

You are curious and interested in learning new languages and frameworks; You have a good sense of humour and keep calm in dicult situations; You value transparency, honesty, humility and helping your teammates grow.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
