### ISSUE TITLE
[100% Remote] Back-end Developer (Node) at @YellowIpe

### ISSUE THREAD

**Issue by YellowIpe** [backend-br/vagas#10005]
## Nossa empresa

YellowIpe is a technology consultant present in Brazil and Portugal with the mission of connecting the best talents to the best projects. We work with national and multinational companies in different sectors of activity that trust us and the differential of our professionals.

## Descrição da vaga

We are looking for a **Backend Node.js** Developer to join our team!

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- At least 3 years of experience in software development using NodeJS and its ecosystem
- Proficiency with JavaScript and Typescript
- Solid knowledge of HTTP, scaling and caching principles
- Ability to work well in a team, self-driven and eager to learn
- Creative thinking, analytical skills and attention to detail
- Fluent in English

**Diferenciais:**
- Knowledge in Docker/Kubernetes and Jenkins is a plus

## Contratação

PJ a combinar

## Como se candidatar

Please send an email to **recrutamento@yellowipe.io** with your CV attached - send in the subject: Back-end Developer (Node)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@yellowipe.io

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
