### ISSUE TITLE
[Remoto] Back-end Developer Sr  .NET @ Icon It

### ISSUE THREAD

**Issue by Thamme1** [backend-br/vagas#10008]
## Nossa empresa
A ICON Solutions é especialista em pessoas. Referência no mercado de recrutamento e seleção, profissionais altamente qualificados e no desenvolvimento de pessoas para todos os setores e níveis de mercado.

Temos valores como Respeito ao Ser Humano, Bom Relacionamento com Confiança, Simplicidade e Humildade 

## Descrição da vaga

Vaga para profissional Sênior com atuação estratégica dentro da Squad
Será o responsável por ajudar os demais membros do time com questões técnicas;
Contribuir para os que outros consigam entregar o melhor, tecnicamente;
Sugerir caminhos e sinalizar os erros.

## Local

Remoto 100%

## Requisitos

**Obrigatórios:**
- Experiência como Dev. Sênior ou lead

**Diferenciais:**
- Atuação como Tech Lead

## Contratação

PJ a combinar 

## Como se candidatar

Por favor envie um email para thamires.camacho@iconit.com.br com seu CV anexado - enviar no assunto: Dev Sr .NET e pretensão Taxa/hora.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
