### ISSUE TITLE
[Developer Senior  C#/C++ with English] - Remoto

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#10012]
[Developer Senior  C#/C++ with English] - Remoto - R$ 19 K PJ.

· Responsibilities:
o Receives a high level of technical definition and translates into language technique;
o Provide support on the product / system adoption;
o Develop software (except core codes), collecting information and verifying the viability of the implementation;
o Ability to evaluate the effort of the activities requested;
o Responsible to attend the tasks regarding the customer support;
o Record metrics for monthly reporting of team's performance.
o Work with other engineering functions from design to production to implement test procedures for systems and equipment.
o Document the procedures and recommendations for all phases of product tests.
o Creates documentation as needed.
Requirements
· Bachelor’s degree (Computer Sciences, Engineering, Physics or other with logical and analytical background);
· Experience of 2 years or more
· English skills;
· Knowledge:
o C#
o C++
o SDK Windows
o Multi thread
· Desirable
o HTML / Java Script
· Skills:
o Execute for results
o Lead change and innovation
o Teamwork
o Prompted pressure
o Availability to travel.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
