### ISSUE TITLE
[Remoto] .NET Developer na MB Labs Tecnologia

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#10014]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-net-remoto-165052159?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>MB Labs Tecnologia</strong> busca <strong><ins>.NET Developer</ins></strong> para compor seu time!</p>
<p>Nascemos em 2013 da junção de paixão por tecnologia e muita vontade de mudar o mundo! Somos uma software house especializada em desenvolvimento de sistemas e aplicações mobile, com sede em Campinas (SP).</p>
<p>Buscamos mudar o mundo por meio da tecnologia e nossas soluções já impactaram mais de 100.000.000 de pessoas mundo afora, tudo isso graças à nossa capacidade colaborativa e motivacional de empoderar pessoas e transformar negócios.</p>
<p>Somos uma empresa jovem e aliamos criatividade e descontração aos métodos mais modernos de desenvolvimento e gestão de projetos.</p>
<p>A MB Labs incentiva a diversidade e inclusão em nossa equipe, todas as candidaturas são avaliadas sem distinção de raça, gênero, orientação sexual, deficiência ou idade. Nosso objetivo é criar um ambiente de trabalho que dê o apoio que precisam para crescer e atingir seus objetivos.</p>

## MB Labs Tecnologia: 
 <p>Fundada em 2014 a MB Labs acumula a experiência de desenvolvimento de sistemas e aplicações. Em seus anos de empresa seu nome é consolidado na região através de sua atuação em grandes e estratégicos projetos de empresas e startups.</p>
<p>A MB Labs conta com sede própria em Campinas, são cerca de 600 metros quadrados de escritório onde se localiza o time de P&amp;D com aproximadamente 180 colaboradores, também possuindo representação nas cidade de Porto Alegre, São Paulo e Belo Horizonte.</p><a href='https://coodesh.com/empresas/mb-labs-tecnologia'>Veja mais no site</a>

 ## Habilidades: 
 - .NET 
- .NET Core 
- C# .NET Core 
- Microsoft SQL Server 
- Programação Orientada a Objetos (POO) 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Bons conhecimentos com WEB, .NET, ASP, .NET Core; 
-  Bons conhecimentos em C#; 
- Metodologias ágeis; 
- Bons conhecimentos .NET Core e .NET Framework; 
- Bons conhecimentos em POO; 
- Bons conhecimentos em SQL Server; 
- Controle de versão GIT.
## Diferenciais: 
 - Conhecimentos em Amazon AWS; 
- Conhecimentos em IIS e Windows Server; 
- Conhecimentos em Patterns de programação; 
- Conhecimentos em SCRUM e outras metodologias ágeis;
## Benefícios: 
 - Descanso remunerado após 12 meses de empresa; 
- Seguro de vida e contra acidentes; 
- Horário Flexível; 
- Avaliação PDI a cada 3 a 4 meses; 
- Vale Presente de R$ 120,00 no ifood  em seu aniversário; 
- Incentivo a certificações de tecnologia; 
- Acesso ilimitado ao MB Academy  (iniciativa interna); 
- Equipamento fornecido pela empresa.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [.NET Developer na MB Labs Tecnologia](https://coodesh.com/vagas/desenvolvedor-net-remoto-165052159?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
