### ISSUE TITLE
[Remoto] Backend Java Developer na Grupo Selpe

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#10015]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-sw-developer-java-165757563?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O <strong>Grupo Selpe</strong> está em busca de <strong><ins>Backend Developer Java Sênior </ins></strong> para compor seu time!</p>
<p>A pessoa desenvolvedora atuará global e ativamente em iniciativas que promovam uma transformação digital na empresa e em seus clientes, dando todo o suporte necessário para garantir o correto ciclo de vida dos produtos digitais que são de responsabilidade do Squad que participa.</p>
<p>Será um ambiente de equipe ágil de execução rápida e será capaz de desenvolver e testar soluções para novas funcionalidades, corrigir soluções de ritmo para novas funcionalidades e implementar soluções bem-sucedidas para novas funcionalidades. O software que você desenvolverá será destinado a serviços a serem implantados em uma arquitetura baseada no uso, como as mais recentes técnicas de desenvolvimento de software.</p>

## Grupo Selpe: 
 <p>Há 56 anos conectando pessoas e empresas aos seus propósitos.&nbsp;</p>
<p>Somos o elo entre profissionais e empresas, trabalhando com a atração, seleção consultoria e tecnologia em RH das mais diversas formas.&nbsp;</p><a href='https://coodesh.com/empresas/grupo-selpe'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Web Services 
- JSON 
- XML 
- GitHub 
- GitLab 
- Docker 
- Programação Orientada a Objetos (POO) 
- Inglês
## Local: 
 100% Remoto
## Requisitos: 
 - Microserviços; 
- POO; 
- Experiência com processo de desenvolvimento ágil; 
- Developing services using JAX-RS : Java RESTful Web services; 
- Depuração do código desenvolvido; 
- Inglês avançado ou Fluente; 
- Experiência sólida com Java; 
- Experiência com JSON.

## Benefícios: 
 - Vale Refeição; 
- Previdência Privada; 
- Seguro de Vida; 
- Plano de Saúde Coparticipativo; 
- PLR.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Java Developer na Grupo Selpe](https://coodesh.com/vagas/senior-sw-developer-java-165757563?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
