### ISSUE TITLE
[Remoto] Java Tech Lead na Builders!

### ISSUE THREAD

**Issue by RaissaBaltazar** [backend-br/vagas#10020]
**Conhece o Movimento Builders? 🤟**

Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios.

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar!

**Esse será seu desafio: 💻**

No papel de Tech Lead, a pessoa Builder terá experiência em trabalhar em equipes para fornecer soluções robustas e escaláveis para a automação de processos de negócios complexos. Deverá conduzir o processo de delivery para que os membros de sua equipe tenham um especialista confiável e esperam que você defina o ciclo de vida de desenvolvimento de software de ponta a ponta de acordo com as melhores práticas modernas.

**Para cumprir esse desafio, você precisa dominar:**
- Java 8+;
- Ferramentas de CI/CD como Jenkins, ArgoCD, Github Actions;
- Cloud;
- Spring;
- DDD;
- Microservices;
- REST;
- Design Patterns.

**Você será considerado(a) uma lenda se tiver também: 😯**
- Vivência em projetos de aplicativos ou produtos web de alta audiência;
- Conhecimento em desenvolvimento e entrega de software em Kubernetes.

**O que nós oferecemos?**
- Trabalho 100% remoto;
- Parceria com coworking em São Paulo;
- Webnars semanais para expandir ainda mais seu conhecimento;
- Fazer parte de uma comunidade de empreendedores de ponta;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado;
- Possibilidade de proft share de novos negócios;

**[O momento para se tornar Builder é agora! 🚀](https://bit.ly/3Sf7C13)**

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
