### ISSUE TITLE
[São Paulo] Engenheiro de Software- Back end @WCA Brasil

### ISSUE THREAD

**Issue by BiancaDuartePereira** [backend-br/vagas#10023]
## Contratação como terceiro da WCA para atuar na empresa Siemens

Somos pioneiros em avanços na área da saúde. Para todos. Em toda parte. 

## Descrição da vaga

Atuará com manutenção de infraestrutura analítica, processos de conjunto de dados usados para modelagem, aquisição de mineração e verificação, desenvolvimento, construção, manutenção e teste de arquiteturas como bancos de dados e sistemas de processamento de larga escala.

## Local

Atuação Remoto, com disponibilidade para viagens até a matriz em SP. 

## Requisitos

Superior em Ciência da Computação, Tecnologia da Informação, Engenharia da Computação ou correlatas.
Conhecimento em C#, C++, Java, Python, PHP.
Conhecimento de registos eletrônicos;				
Conhecimento em serviços baseados em nuvem;	

Inglês Avançado

## Benefícios

Ajuda home office, Seguro e Convênio médico

## Contratação

Terceiro como CLT

## Como se candidatar

selecionadora05@wcabrasil.com.br

### Nível

- Sênior

### Regime

- CLT

### Alocação

- Remoto
- Híbrido

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
