### ISSUE TITLE
[REMOTO] QA Backend (Javascript) @Invillia

### ISSUE THREAD

**Issue by HelenRenata** [backend-br/vagas#10024]
INVILLIA
Aproxime-se. A Invillia não promoveu as empresas como empresas únicas que fazem parte do mundo criativos, como empresas criativas e digitais.
Inovou a maneira como as pessoas apaixonadas por tecnologia, podem interagir de qualquer lugar, evoluir também do planeta que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. Como suas ideias. O seu potencial.

O tamanho do seu talento_

REQUISITOS
- Experiência anterior como QA +3 anos, como parte de uma equipe de desenvolvimento;
- Conhecimento sobre fundamentos de testes (Técnicas e Estratégias);
- Sólidos conhecimentos em diferentes tipos e níveis de testes;
- Experiência com ao menos uma linguagem de programação, preferência JavaScript
- Experiência com automação de testes WEB com Cypress ou outro framework JavaScript;
- Experiência com automação de testes API com Cypress ou outro framework JavaScript;
- Experiência com versionamento de código;
- Experiência com banco de dados (relacional e não-relacional);
- Facilidade com identificação da causa raiz de problemas;
- Experiência em trabalhar com times internacionais;
- Inglês Avançado.

DESEJÁVEL_
- Experiência com atuação QA Ágil;
- Experiência com integração dos testes automatizados em esteira CI/CD;
- Experiêmcia com Testes de Performance (K6 ou Jmeter).

DIFERENCIAL_
- Certificações na área de Qualidade de Software.

LOCAL
Totalmente Remoto para sempre

REGIME
CLT

COMO SE CANDIDATAR
Enviar o currículo atualizado para [[helen.santos@invillia.com]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
