### ISSUE TITLE
Lisboa ou Porto Front End Integer Consulting

### ISSUE THREAD

**Issue by Catia987** [backend-br/vagas#10034]
A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Front-end Developer(m/f), com fortes habilidades de comunicação e sentido de responsabilidade e de trabalho em equipa.

#Descrição da vaga

Este pode ser o desafio perfeito para ti se tens:

Bacharelado em Engenharia da Computação ou similar;

4 anos de conhecimentos em Javascript, ou React.Js, ou Angular;
Fluência em Inglês;
Localização: Lisboa ou Porto

Possibilidade de trabalho remoto numa fase inicial.

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para [catia.jorge@integer.pt](mailto:catia.jorge@integer.pt).

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN
Para saber mais como protegemos a sua privacidade, consulte a nossa Política em [www.integer.pt](http://www.integer.pt/)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
