### ISSUE TITLE
[REMOTO] Lead Software Engineer .NET  @DB1 Group

### ISSUE THREAD

**Issue by barbarameneghetti** [backend-br/vagas#10040]
## Nossa empresa
A DB1 Global Software é uma empresa do DB1 Group e é uma Software House especializada no desenvolvimento de software para grandes players do mercado. 
Na DGS, como chamamos aqui, trabalhamos com a transformação digital alinhada a uma entrega de valor aos nossos clientes. Temos o propósito de enfrentar desafios e resolver problemas, buscando nos aperfeiçoar cada vez mais. Aqui, entendemos que o profissional e pessoal andam juntos, por isso, cultura importa tanto quanto conhecimento técnico. 
Como fazemos isso? Formando squads exclusivas para nossos projetos, com equipes multidisciplinares, que imergem no segmento do nosso cliente e focam em realizar entregas pautadas em resultados e com padrão global de qualidade. Além disso, somos sempre movidos por uma cultura que desenvolve e valoriza pessoas! 

## Descrição da vaga

A pessoa Lead Engineer é uma referência técnica para o time de desenvolvimento do projeto. Auxilia o time para encontrar a melhor solução técnica e os ajuda a evoluir suas habilidades, retira impedimentos técnicos, assegura a utilização de boas práticas de programação e linguagem, aponta riscos e oportunidades de melhorias nos projetos.

## Local

Remoto

## Requisitos

**Obrigatórios:**   
- Experiência desenvolvendo em .NET e .NET Core;   
- Experiência com bancos relacionais e não-relacionais;   
- Conhecimento em microserviços;  
- Conhecimento em versionamento Git;  
- Conhecimento em Design Patterns, SOLID e Clean Code;   
- Experiência com metodologias ágeis. 

**Diferenciais:**   
- Inglês avançado para conversação; 
- Conhecimento em Docker, Kubernetes.  

## Benefícios

- Cartão de benefícios flexíveis (Alimentação, Mobilidade, Qualidade de Vida, entre outros);   
- Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;   
- Auxílio home office;   
- Horários flexíveis!;   
- Gympass (opcional);   
- Plano odontológico (opcional);   
- Seguro de Vida (opcional);   
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;   
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do Mestre dos Códigos.   
- Comitês para você participar e contribuir com as melhorias dos processos do Grupo DB1 ou contribuir com a comunidade: Núcleo de Diversidade, Equidade e Inclusão; Comitê de Boas Práticas de Gestão de Pessoas (CBPGP); Comitê técnico; Comitê de Responsabilidade e Desenvolvimento Socioambiental (CORDS); e Núcleo de Inovação.  

## Contratação

CLT ou PJ.

## Como se candidatar

- [Clique aqui para se candidatar na vaga](https://db1group.pinpointhq.com/jobs/64765?utm_medium=direct&utm_source=GitHub)   
Ou envie seu currículo para talentos@db1.com.br   

### Nível

- Especialista

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
