### ISSUE TITLE
[Remoto] Fullstack developer Java Senior @TecnologiaÚnica

### ISSUE THREAD

**Issue by danilafrazia** [backend-br/vagas#10063]
### **Tecnologia Única**

Venha fazer parte de uma empresa que acredita e aposta em novas ideias, com um time forte, e com propósito que já soma mais de 200 pessoas. Somos uma empresa de desenvolvimento de sistemas fundada em 2004. Nossas principais soluções são para o mercado segurador e de fidelização para diversos segmentos, desde o varejo até o agronegócio. Também mantemos um ecossistema de startups, nosso pilar de inovação. Parceira de grandes players de mercado de tecnologia, entre eles Microsoft e AWS, temos a missão de impactar a vida das pessoas provendo soluções disruptivas, investindo massivamente em nosso time, sempre perseguindo e incentivando processos criativos. 
Sentiu a energia única e se identificou com o nosso propósito? 
#VemSerUnico 

### **Descrição da vaga**

● Desenvolvimento do roadmap junto ao time de novas features; 
● Melhoria e ajustes de processos existentes 

 ### **Local**

100% Home Office OU São Paulo, SP. 

### **Requisitos**

**O que a gente precisa que você tenha:**
● Formação em Tecnologia; 
● Conhecimento em Metodologia Ágil Scrum/Kanban; 
● Java; 
● JBoss 

 **Seria ótimo se você tivesse:** 
● Inglês intermediário; 
● Oracle; 
● Spring Boot 
● Vue.js 
● CI/CD 
● Conhecimento em Cloud 
● Linux 
● Conhecimento em SPED Fiscal

 ### **Benefícios**

Auxilio Alimentação + Auxílio Saúde + Gympass + Apoio psicológico (Psicologia Viva) + Day Off Remunerado no Aniversário + Dias de Descanso Remunerado + Bônus para Certificação 

### **Contratação**

 PJ - 40h (semanais)

### **Como se candidatar**

Enviar currículo para: **dfrazia@tecnologiaunica.com.br** | Whats **(44) 99888-3694** | Telegram **@danilafrazia**
LinkedIn **/in/daniellelafrazia/**

### **Nível**

- Sênior

### **Regime**

- PJ

### **Alocação**

- Remoto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
