### ISSUE TITLE
[Lisboa ou Porto - Portugal] Oportunidades Internacionais TI @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#10069]
# Estás à procura de projetos internacionais na área de TI? Se o teu objetivo é ser bem-sucedido na Europa, temos novidades para ti!

## .Net Developer 

- +4 anos de experiência profissional em desenvolvimento .NET;

- Experiência com .NET Core;

- Experiência em testes TDD/BDD;

- Conhecimentos em Continuous Integration e Continuous Delivery (CI/CD);

- Conhecimentos em bases de dados SQL Server;

- Familiaridade com metodologias Agile;

- Inglês fluente (obrigatório).

## Java Developer

- +4 anos de experiência profissional em desenvolvimento Java;

- Experiência em Spring e Spring Boot;

- Experiência em testes TDD/BDD;

- Conhecimentos em Micro Serviços;

- Conhecimentos em bases de dados SQL Server ou Oracle;

- Familiaridade com metodologias Agile;

- Inglês fluente (obrigatório).

## DevOps 

- +5 anos de experiência como engenheiro DevOps;

- Conhecimento em pipelines Jenkins e ferramentas CI/CD;

- Conhecimentos em ferramentas de automação Terraform ou Ansible;

- Conhecimentos em Docker e Kubernetes; 

- Conhecimentos em Cloud (AWS ou Azure);

- Inglês fluente (obrigatório).

## Outsystems Developer

- Experiência na plataforma Outsystems 11;

- Experiência no desenvolvimento de extensões;

- Experiência em testes TDD/BDD;

- Experiência na base de dados SQL Server;

- Conhecimentos em desenvolvimento.Net;

- Inglês fluente (valorizado).

## Business Process Management (BPM)

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- Experiência com desenvolvimento ADF; 

- Experiência com bases de dados Oracle (preferencialmente 12c); 

- Conhecimentos em desenvolvimento Java;

- Conhecimentos de XML, de contratos XSD e transformações XPath, XSLT;

## Tester Automático

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional com testes automáticos;

- Experiência com ferramentas de automação (Selenium, Appium ou Calabash);

- Conhecimentos das Frameworks BDD (Behaviour Driven Development) como o Cucumber;

- Capacidade de realizar testes funcionais, além dos automáticos;

- Inglês fluente (obrigatório).

## iOS Developer

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional em desenvolvimento iOS;

- Experiência com Swift e/ou Objective-C;

- Experiência com Rest APIs;

- Conhecimentos das Frameworks iOS, como por exemplo, Foundation e UIKIT;

- Inglês fluente (obrigatório).

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as regras.
