### ISSUE TITLE
[São Paulo] Java + Python Dev PLENO // SÊNIOR na [Blueshift Brasil]

### ISSUE THREAD

**Issue by tortadelimao** [backend-br/vagas#1007]
Fala, pessoal, tudo certo?

Sou recrutador da Blueshift Brasil, empresa especializada em Big Data.

Estou buscando por um desenvolvedor Java + Python Pleno ou Sênior para participar de um projeto de precificação.

A princípio é um projeto de 3 meses - que pode ser prorrogado. Após a finalização desse projeto, se você quiser continuar sendo um Blue e tiver interesse em Big Data, vamos oferecer todo o treinamento necessário para que você comece a atuar nessa área e continue trabalhando conosco!

Se interessou? Tem algum colega para indicar? Mande um e-mail: bruno.machioni@blueshift.com.br

**Comment by THAYLLER** [comment]
somente presencial?

**Comment by tortadelimao** [comment]
Somente presencial.

E desculpe a demora, comecei a usar o Git esses tempos e estou aprendendo
ainda :p

Abraços.

Em qua, 24 de abr de 2019 às 16:18, Thayller Vilela Cintra <
notifications@github.com> escreveu:
