### ISSUE TITLE
[Remoto] Fullstack Developer Senior @TecnologiaÚnica

### ISSUE THREAD

**Issue by danilafrazia** [backend-br/vagas#10092]
### **Tecnologia Única**

Venha fazer parte de uma empresa que acredita e aposta em novas ideias, com um time forte, e com propósito que já soma mais de 200 pessoas. Somos uma empresa de desenvolvimento de sistemas fundada em 2004. Nossas principais soluções são para o mercado segurador e de fidelização para diversos segmentos, desde o varejo até o agronegócio. Também mantemos um ecossistema de startups, nosso pilar de inovação. Parceira de grandes players de mercado de tecnologia, entre eles Microsoft e AWS, temos a missão de impactar a vida das pessoas provendo soluções disruptivas, investindo massivamente em nosso time, sempre perseguindo e incentivando processos criativos. 
Sentiu a energia única e se identificou com o nosso propósito? 
#VemSerUnico 

## Descrição da vaga

🔹Desenvolvimento e manutenção de aplicações web;
🔹Desenvolvimento de funcionalidades no Front-End;
🔹Desenvolvimento de funcionalidades no Back-End;

## Local

100% Remoto OU Híbrido em São Paulo, você escolhe!

 ## Requisitos

Formação em Tecnologia;
🔹Conhecimento em metodologias ágeis (Scrum/Kanban);
🔹Experiência em .NET, C#, ASP.NET, APIS REST/JSON;
🔹02 + anos de experiência com plataforma Microsoft SQL;
🔹Conhecimento de Javascript, CSS, HTML para criação de Front-ends Web;
🔹Conhecimento em GIT/TFS

## Benefícios

Auxílios + Gympass + Apoio psicológico (Psicologia Viva) + Day Off Remunerado no Aniversário + Dias de Descanso Remunerado + Bônus para Certificação;

## Contratação

 PJ - 40h (semanais)

## Como se candidatar
https://www.linkedin.com/jobs/view/3312932575/?capColoOverride=true
OU enviar currículo para: **dfrazia@tecnologiaunica.com.br** | Whats **(44) 99888-3694** | Telegram **@danilafrazia**
LinkedIn **/in/daniellelafrazia/**

### Nível

🔹 Pleno
🔹 Sênior

### Regime

🔹 PJ

### Alocação

🔹 Remoto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
