### ISSUE TITLE
[Remoto] NodeJS Back-end developer @Multiledgers

### ISSUE THREAD

**Issue by nadinicarega-multiledgers** [backend-br/vagas#10094]
## Nossa empresa

A Multiledgers é uma startup brasileira líder no segmento de orquestração de nuvens públicas para deploy e gerenciamento de redes blockchain com altos níveis de segurança nos principais frameworks DLT do mercado. A Multiledgers atua na implantação da governança e no gerenciamento de redes Blockchain (Blockchain as a Service – BaaS), e no gerenciamento de infraestruturas de TI de redes públicas e privadas (Infraestrutura as a Service - IaaS) dessa forma, integra diferentes tipos de protocolos de redes e provedores de nuvens.

## Descrição da vaga

Estamos procurando um perfil de desenvolvedor back-end em NodeJS que possa trabalhar com um tipo específico de programação e entender muitas outras tecnologias envolvidas no desenvolvimento de back-end em NodeJS.

## Local

Contratação Remoto.

## Requisitos

Responsabilidades e atribuições:
- Desenvolver e gerenciar componentes de rede do lado do servidor.
- Gerenciar banco de dados centrais relacional e não relacional.
- Garantir a boa capacidade de resposta às solicitações do front-End .
- Desenvolver aplicações de alto desempenho.
- Desenvolver códigos testáveis, reutilizáveis e eficientes.
- Implementar protocolos de segurança eficazes.
- Executar testes de diagnóstico, reparar defeitos e fornecer suporte técnico.
- Gerenciar código fonte.
- Produzir documentação de código fonte.

Requisitos Técnicos:

- Proficiência em JavaScript.
- Conhecimento entre intermediário e avançado em NodeJS e frameworks compatíveis.
- Conhecimento sobre programação assíncrona e suas peculiaridades.
- Compreensão de linguagens de modelagem do lado do servidor (como Jade, EJS, etc.).
- Conhecimento básico de tecnologias front-end, como HTML5 e CCS3.
- Conhecimento preferencial em banco de dados postgres e mongo.
- Conhecer ferramentas de controle de versão, git entre outras.

Soft Skills:

- Agilidade e Flexibilidade.
- Trabalho em equipe.
- Habilidades de Comunicação.
- Organização

Diferencial:
- Certificações em NodeJS.
- Conhecimento de Typescript.
- Conhecimento de Blockchain.

## Benefícios

- O orçamento para a vaga chega até no máximo 12k (a depender do nível de senioridade). 
- Os colaboradores são constantemente avaliados e considerados pela política de associados.

## Contratação

O tipo de contratação é PJ.

## Como se candidatar

- Você pode se candidatar através do site: https://bit.ly/3Bo0qIk ou 
- Você pode enviar CV para o email: hr@multiledgers.com
- Voceê pode nos procurar no linkedin: https://bit.ly/3SdO3W9

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by fabricadesites-sc** [comment]
Me candidatei no site

**Comment by nadinicarega-multiledgers** [comment]
Edit 1: Recebemos muitos cvs pelo anuncio, estamos muito agradecidos pelo interesse na Multiledgers e estamos respondendo a todos por email (Por favor, conferir em spam).
Edit 2: A vaga foi preenchida.
