### ISSUE TITLE
[São Paulo / SP] Programador PHP na Web D7

### ISSUE THREAD

**Issue by sistemaweb** [backend-br/vagas#101]
# Descrição da vaga
Estamos em busca de desenvolvedor PHP, curioso e apaixonado por tecnologia, para trabalhar presencialmente em Sâo Paulo.

A vaga é temporária (de 03 a 06 meses) para desenvolvedor PHP (Laravel), programação web (html, css e javascript) e conhecimento / vivências com APi

# Local
Lapa - ZO - São Paulo / SP 

# Benefícios
- Vale Refeição 
- Vale Transporte
- Notebook
- Smartphone

# Requisitos

## Obrigatórios:

- PHP
- Javascript
- HTML e CSS
- APi restful
- Laravel

## Desejáveis:

- Conhecimentos em Java para Android
- Conhecimentos em Material Design

## Diferenciais:

- Sólida experiência em PHP
- Conhecimento em Criação e Consumo de Web Services (APIs RESTful, SOAP)

# Contratação
- PJ (pode ser MEI)
- Enviar currículo para contato@webd7.com

# Labels

- PJ
- Pleno
- Senior
- Presencial

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.

**Comment by sistemaweb** [comment]
pode manter fechada, obrigado!





*Att,**Adriano Nascimento*

2018-05-11 16:24 GMT-03:00 Reginaldo Junior <notifications@github.com>:
