### ISSUE TITLE
[REMOTO] Back-end developer - Internacional

### ISSUE THREAD

**Issue by tomas-itrecruiter** [backend-br/vagas#10104]
## Lead Blockchain Dev Sênior
Empresa do Texas que fornece produtos e serviços em tecnologia para viagens 

## Local
Remoto

## Requisitos
-Inglês avançado
-5 Anos de Experiência com .NET e C#
-Residir na América Latina

## Contratação
PJ

## Como se candidatar
Enviar CV em inglês + pretensão salarial (USD) até o dia 21/09/2022 por Whatsapp ou Telegram 81 988564321

## Labels
- .NET
- C#

### Nível
- Sênior
- Especialista

### Regime
- PJ
- 
### Alocação
- Remoto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
