### ISSUE TITLE
[REMOTO] Product Owner Sênior| DEAL TECHNOLOGIES

### ISSUE THREAD

**Issue by ThauanySilva7** [backend-br/vagas#10106]
**Sobre Nós**
Somos a Deal, estamos no mercado desde 2004 e somos referência em Inteligência de Dados e Transformação Digital, desde a estratégia até a execução (end-to-end).
Aqui, cada Dealmaker tem liberdade para:
• Ser quem é, numa cultura que valoriza as pessoas pela sua essência;
• Trabalhar de onde quiser, porque o Anywhere Office é uma realidade por aqui;
• Ser protagonista da sua carreira e escolher aonde quer chegar profissionalmente!

**Pré-requisitos:** 
•	Vivência no segmento de cartões e ter atuado na área de Produtos do segmento financeiro
•	Conhecimento da estrutura e fluxo de transações com cartão
•	Experiência com métodos ágeis
•	Propor e identificar melhorias e inovações, executar testes, e realizar o acompanhamento e gerenciamento do roadmap e indicadores de produtos
•	Experiência em gerir o ciclo de vida e jornada do cliente, régua de relacionamento e canais de atendimento
•	Identificar oportunidades de engajamento dos clientes, e mapeamento e execução de ações de vendas e marketing
•	Escrita de histórias e critérios de aceite 

**Local**
Remoto, trabalhe de qualquer lugar da galáxia. 

**O que oferecemos:**
• Benefícios personalizados
• Parceria com o SESC
• Capacitação e desenvolvimento pelo nosso Núcleo de Inovação Deal
• Programa de mobilidade interna (Deal Moving)
• E muito mais!

**Como se candidatar**
Por favor, envie um e-mail para [vemser@deal.com.br](mailto:vemser@deal.com.br)
Com seu CV anexado – enviar no assunto: Product Owner Sênior

**Labels**

Alocação
•	Remoto

Regime
•	CLT
 
Nível
•	Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as regras.
