### ISSUE TITLE
[São Paulo] Dev Phyton para time de Data Science - Serasa Consumidor - Regime CLT

### ISSUE THREAD

**Issue by mafabeni** [backend-br/vagas#1011]
Você quer trabalhar em um ambiente com tecnologia de ponta e uma equipe altamente capacitada para mudar a vida financeira do consumidor brasileiro? #vempraserasaconsumidor
Já somos uma das maiores empresas digitais do mercado financeiro e estamos desenvolvendo produtos e serviços que vão mudar a forma como o brasileiro se relaciona com o dinheiro.
Somos um time com brilhos nos olhos, multidisciplinar e com autonomia para propor ideias. Se você é apaixonado pelas transformações do mundo digital, não tem medo de assumir riscos e quer sentir-se “dono do negócio”, venha trabalhar com a gente!
Como Python Big Data Developer você desenvolverá produtos inteligentes que vão para o mercado com alta volumetria e larga escala.

O que buscamos?
•	Experiência com desenvolvimento Python na construção de data pipelines e web crawlers
•	Experiência em versionamento de código, arquitetura em micro serviços e testes de software
•	Perfil dinâmico que gosta de enfrentar desafios
•	Inglês técnico

O que pode diferenciar você?
Conhecimento em Spark, Scala ou Java. Atuação em fintechs no mercado financeiro. Experiência com arquitetura e desenvolvimento Cloud (AWS, Google Cloud). Experiência com algoritmos de machine learning.
Oferecemos:
•	Ambiente desafiador e high performance
•	Possibilidade de aprendizado e trabalhar com inovação
•	Pacote salarial atrativo + benefícios
•	PLR anual
•	Previdência privada

Entrar em contato: linkedin.com/in/leopoldo-bulgarelli-9825661

**Comment by gabrielangelo** [comment]
Aceita remoto ?

**Comment by mafabeni** [comment]
Infelizmente não 

Marcelo Fabeni

Em 22 de abr de 2019, à(s) 23:38, Gabriel <notifications@github.com> escreveu:
