### ISSUE TITLE
[São Paulo ou interior] [Desenvolvedor Back end Java Pleno SR] - Remoto

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#10119]
[Desenvolvedor Back end Java Pleno SR] - Remoto. CLT Pleno: R$ 8 mil a R$ 10 mil / Senior: R$ 11 mil a R$ 13 mil.  Eventualmente haverá reuniões de alinhamento na sede em São Paulo Interlagos. Precisa residir em São Paulo ou interior.

O que precisa?
Mínimo de 2 anos de experiência na área de desenvolvimento; Java (versão 8 para mais); Essencial: Springbot, redis,oracle, microserviços, junit.
Diferencial: Cloud (Azure/AWS), API gateway, pattern de resiliência.

Empresa
Atuar num Grande Banco, por uma consultoria internacional.

Benefícios
R$ 1.500,00 cartão Flex mensal.
Assistência Médica;
Seguro de vida;
Assistência Odontológica;
Academia
Seguro de vida.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
