### ISSUE TITLE
[Portugal] Developer @Integer Consulting Portugal

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#10138]
💥Integer Consulting Portugal 

A Integer Consulting é uma empresa portuguesa de consultoria em tecnologias de informação. Somos especialistas em serviços de IT outsourcing, software, projetos de nearshore e desenvolvimento à medida. Somos parceiros dos principais players tecnológicos a nível mundial e trabalhamos com empresas nacionais e multinacionais de diversos setores de atividade. A maioria dos projetos em que participamos são em Portugal, no Brasil e um pouco por toda a Europa. O que nos diferencia é o talento tecnológico e a experiência das pessoas que fazem parte da equipa e que integram os nossos projetos.

Estás à procura de um novo desafio internacional na área de TI? 😉 

📍 Senior .NET Developer (c/ inglês fluente)
📍 Java Developer (c/inglês fluente)
📍 ETL Developer c/ Oracle (c/ inglês fluente)
📍 Outystems Developer (inglês valorizado)
📍 Tester Automático (c/inglês valorizado)
📍 Oracle SOA Suite
📍 Oracle BPM

Se o teu objetivo é revolucionar a tua carreira em Portugal, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
