### ISSUE TITLE
[Joinville] Python Developer @ Neocredit

### ISSUE THREAD

**Issue by raissaime** [backend-br/vagas#10145]
## Nossa empresa

A Neocredit analisa informações de crédito e comportamento, internas, externas proporcionando uma análise personalizada. Permite a construção do perfil do cliente e a retroalimentação dos dados aumentando a assertividade das análises.

## Descrição da vaga

Vagas para Python Developer 🚀

## Local
🏢 Atuação Presencial ou remoto em Joinville e região.

## Requisitos
📌Domínio de Python;

📌Domínio de manipulação de dados (JSON e XML) em Python;

📌Conhecimento de APIs REST;

📌Conhecimento de SQS ou outra tipo de fila de mensageria;

📌Domínio de Banco de Dados Relacional (Se possível Postgres);

📌Com noções de Docker e AWS ou outra cloud pública.

## Benefícios

👉 30 dias de descanso remunerado a cada 12 meses trabalhado.

## Contratação

🤝 PJ ou Cooperativa.

## Remuneração
💰 Pode chegar até R$ 12.000 conforme senioridade.

## Como se candidatar

💬 Os currículos devem ser enviados para raissaime@outlook.com.

### Nível

- Júnior
- Pleno

### Regime

- PJ
- CLT

### Alocação

- Remoto
- Híbrido
- Presencial

**Comment by jjpaulo2** [comment]
Oi @raissaime. Entrei em contato com vc por e-mail 😁
