### ISSUE TITLE
[Lisboa/Portugal] Java Developer c/Cloud @IntegerConsulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#10167]
# Integer Consulting Portugal
A Integer Consulting é uma empresa portuguesa de consultoria em tecnologias de informação. Somos especialistas em serviços de IT outsourcing, software, projetos de nearshore e desenvolvimento à medida. Somos parceiros dos principais players tecnológicos a nível mundial e trabalhamos com empresas nacionais e multinacionais de diversos setores de atividade. A maioria dos projetos em que participamos são em Portugal, no Brasil e um pouco por toda a Europa. O que nos diferencia é o talento tecnológico e a experiência das pessoas que fazem parte da equipa e que integram os nossos projetos.

Estás à procura de novas oportunidades na área de IT? Temos novidades para ti!

## Este pode ser o desafio perfeito, se tiveres:
- Experiência em Micro Serviços; 
- Experiência em arquiteturas de processamento, tratamento e integração de dados;~
- Experiência em MongoDB e Azure MS SQL Server;
- Experiência em Cloud Azure (obrigatório);
- Conhecimentos em Kafka e Kubernetes;

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

Para saber mais como protegemos a tua privacidade, consulte a nossa Política em www.integerconsulting.pt

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
