### ISSUE TITLE
[Varginha] Fullstack CLT de PHP e Vue.js na Inter Telecom

### ISSUE THREAD

**Issue by viniciushsantana** [backend-br/vagas#1018]
## Descrição da Vaga

Atuará no desenvolvimento de ferramentas internas da empresa, similares a um ERP + CRM.

O candidato irá liderar o projeto e terá autonomia para moldá-lo, em sintonia com o restante da equipe e com os requisitos do projeto. Necessitamos que o código seja limpo, bem documentado e com boa cobertura de testes.

Apreciamos códigos leves, simples e com poucas dependências.

## Local

Sul de Minas Gerais – Região de Varginha. 

Temos auxílio de transporte da empresa para diversas cidades próximas (Machado, Alfenas, Elói Mendes, Três Corações, Três Pontas, etc.).

## Requisitos

* Forte experiência com desenvolvimento moderno de PHP;
* Capacidade de desenvolver interfaces com base nos requisitos dos projetos;
* Conhecimento em HTML5, CSS e JavaScript (ECMAScript 5+);
* Conhecimento em framework de construção de interfaces (Vue.js);
* Capacidade para desenvolver códigos testáveis e conhecimento para automação de testes unitários, funcionais e de integração;
* Experiência com trabalho em equipe com controle de versão (Git);

## Diferenciais

* Experiência prévia com Laravel, Docker e GitLab CI.

## Contratação

* CLT com remuneração inicial de até R$ 5.000,00;
* Possibilidade de trabalho remoto alternado com presencial;
* VA de R$ 300,00;
* Participação nos resultados;
* Almoço na empresa;
* Transporte da empresa para cidades próximas;
* Linha telefônica móvel ilimitada com voz e dados para uso pessoal.

## A Empresa

A Inter Telecom trabalha com serviços de telecomunicações com um modelo de negócios único no país e busca fomentar seu crescimento acelerado com o desenvolvimento de ferramentas próprias.

Utilizamos tecnologias modernas em um ambiente de autonomia, aprendizado e desafios.

## Como se candidatar

Interessados poderão entrar em contato pelo e-mail recrutamento.dev@intertelecom.net.br.

**Comment by fsrocha-dev** [comment]
Ainda está em aberto ?

**Comment by viniciushsantana** [comment]
A vaga ainda se encontra aberta.
