### ISSUE TITLE
[Alphaville/SP] Desenvolvedor Back-end

### ISSUE THREAD

**Issue by liviatadei** [backend-br/vagas#1019]
## Descrição da Vaga
- Atuar no desenvolvimento de hotsites promocionais.
- Promover melhorias nos sistemas existentes; 
- Apoiar no desenvolvimento de integrações entre sistemas através de tecnologias como: WebService e REST APIs.

## Local
Alphaville - São Paulo

## Requisitos
- Desenvolvimento PHP focado em Back-end
- Forte conhecimento em PHP ou Python
- MySQL, PostgreSQL
- Entendimento da arquitetura REST
- Experiencia com implementação / funcionamento de API
- Bom conhecimento Git

## Contratação
- Vale transporte ou estacionamento
- VR R$30,00/dia
- Salário entre R$6.000 e R$8.000 dependendo da experiência
- PJ
- Alocado em Alphaville

## A Empresa
A Átomo Comunicação iniciou suas atividades em 2002 e desde então vem construindo grandes cases para marcas líderes com resultados comprovados. Somos uma agência 360, que vem crescendo bastante a área de digital nos últimos anos.

## Como se candidatar
Interessados poderão entrar em contato pelo e-mail selecao@atomocom.com.br

**Comment by samuelfaj** [comment]
Seria possível trabalhar como PJ remoto?
