### ISSUE TITLE
Remoto/Hibrido/Presencial- Florianópolis-SC - Back-end developer - Deucrédito

### ISSUE THREAD

**Issue by jeavagas** [backend-br/vagas#10204]
## Deucrédito

**Sobre a empresa**

Somos uma empresa apaixonada por pessoas, pautamos sempre pela qualidade das nossas relações e pelo cuidado com cada membro do time. Estamos buscando uma pessoa para fazer parte deste time que vem crescendo a cada dia, tanto em número quanto em desenvolvimento.

Encorajamos e acreditamos no nosso time e prezamos por fazer junto. Se você é essa pessoa, que tem um senso de equipe e que procura por desenvolvimento constante, a DeuCrédito é para você! Venha fazer parte da fintech mais inovadora e líder no mercado de crédito consignado!

## Descrição da vaga

**O que esperamos ver em você:**

Raciocínio lógico e resolução de problemas;
Proatividade, analítico e autodidata;
Integridade e transparência;
Senso de equipe e cuidado com as pessoas.

## Local : Florianópolis-SC

Possibilidade de atuação: remoto, híbrido ou presencial.

## Requisitos

**O que esperamos que você tenha:**

_Estágio:_

Capacidade demonstrada de resolução de problemas e aprendizado rápido;
Noções de boas práticas de programação;
Conhecimento em Git;
Entendimento do funcionamento da web;
Entendimento básico de modelagem de dados (SQL);
Conhecimento de uma linguagem e um framework de backend, de preferência Python e Django/FastAPI/Flask respectivamente;
É desejável: experiência prévia de trabalho em organizações estudantis / volutariado / intercâmbio / ou similares;

_Junior:_

Experiência de trabalho com desenvolvimento web além dos requirements do estágio;

_Pleno:_

Base sólida em arquitetura de sistemas, banco de dados e APIs;
2+ anos de experiência com Python, Django e clean code;
2+ anos de experiência com HTML, CSS e Javascript;
Conhecimento de UX é um diferencial.

## Benefícios

Oferecemos oportunidade de crescimento interno, ações do nosso endomarketing como: Dia do doce, day off no aniversário, dia da fruta, premiação por tempo de casa, dia do sorvete e rodas de conversa focado na saúde mental. Nossa estrutura fornece refeitório, fliperama, ambiente para descanso e mercadinho interno e muito mais.

## Contratação

Tipo de contratação: Estágio ou PJ.

## Como se candidatar

Plataforma [sólides](https://fontesvagas.solides.jobs/vacancies/184607)
Plataforma [indeed](https://br.indeed.com/emprego/desenvolvedor-back-end-django-est%C3%A1gioj%C3%BAniorpleno-69c2eb0f6d44d02c)
Contato equipe de Recrutamnto e Seleção J&A: (48) 9164-0011 ou
E-mail: talentos@jeaholding.com.br

### Nível

- Estagiário
- Júnior
- Pleno

### Regime

- PJ
- Estágio

### Alocação

- Remoto
- Híbrido
- Presencial

**Comment by ZaikoXander** [comment]
Já me apliquei, aguardo a resposta! 😁

**Comment by Luisfelipeqt** [comment]
Já me apliquei a vaga de estágio, aguardo a resposta!
