### ISSUE TITLE
[Home Office] DevOps/SRE [Foco em Você]

### ISSUE THREAD

**Issue by kvilela** [backend-br/vagas#1020]
**Requisitos**
    SO Linux
    RESTful
    SQL e NoSQL
    Git
    Rest
    Integração e Entrega Contínua
    Testes Automatizados
    Infraestrutura
    Cloud (AWS / Google)
    Jenkins
    Kubernetes
    Docker

**Nós também amamos pessoas que conhecem:**
    Groovy / Java;
    Arquitetura de microsserviços (service discovery, gerenciamento de configuração, gerenciamento de logs, auto-scaling);

**CLT** - salário a combinar
 **Benefícios:**
     Plano de saúde;
     VR;
     VT;
     VA; 
     
Envie seu CV para karina.vilela@focoemvoce.com.br

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by kvilela** [comment]
Oi Guilherme, boa tarde!
Tudo bem?

Pleno e Sênior

Abs,

Karina Parise Vilela

Em qui, 25 de abr de 2019 21:22, Guilherme Oliveira <
notifications@github.com> escreveu:
