### ISSUE TITLE
[Remoto] Back-end developer Python - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#10201]
## Nexmuv
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Local

100% remoto 

## Requisitos

Experiência com desenvolvimento back-end Python (API Rest) - Experiência em alguma plataforma Cloud (AWS, Google, Azure, etc)
Experiência em React ; Javascript / TypeScript;  frameworks de UI (bootstrap, material, etc) consumo de APIs;  Docker 
Experiência com testes unitários. 

## Contratação

PJ.

## Como se candidatar

Enviar cv para o e-mail Helen.matos@nexmuv.com.br 

### Nível
- Pleno
- Sênior

### Regime
- PJ
 
### Alocação

- Remoto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
