### ISSUE TITLE
[REMOTO] Back-end Developer (Nodejs+Flutter) - DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [backend-br/vagas#10203]
## Nossa empresa

Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga
O QUE NOS MOVE:
Desafios! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente, uma Fintech com soluções inovadoras para o mercado de Gift Card.

O QUE ESPERAMOS QUE VOCÊ SAIBA:
Microsserviços altamente escaláveis escritos em TypeScript/NodeJS;
Aplicações de Front-end com Flutter;
Utilizando uma arquitetura funcional para Firebase/Google Functions;
Continuous Integration e Deployment (CI/CD) para Google e Firebase;
Estrutura de dados em Firestore.

## Local
DE ONDE VOCÊ VAI TRABALHAR?
No melhor lugar, onde você se sentir confortável!

## Requisitos
O QUE SERIA LEGAL SE VOCÊ SOUBESSE:
High throughput APIs para comunicação externa;
Monitoramento e logs via Stack Drive;
Ambiente Analítico separado via orquestração de eventos Segment;
BigData com Google BigQuery;
Trabalhar com sistemas distribuídos de grande escala;
Colaborar com a criação de sistemas funcionais (microfunctions);
Ter conhecimento de metodologias ágeis para o desenvolvimento.

## Benefícios
O QUE OFERECEMOS PARA VOCÊ?
Contrato PJ - Relação por LONGO prazo!
13ª Pagamento 
Recesso Remunerado;
Flexibilidade de horários.

## Como se candidatar

Envie seu currículo para vagas@dqrtech.com.br
Ou, acesse o Link: https://dqrtech.com.br/portfolio-items/desenvolvedor-a-fullstack-node-js-flutter/?portfolioCats=9%2C14

Você também pode nos chamar pelo WhatsApp: https://contate.me/51989678273
Contato: (51) 989678273

### Nível
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by gsabreudev** [comment]
vem ser @dqr.tech
