### ISSUE TITLE
[Hibrido / Brasília, Distrito Federal, Brasil] PHP Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#10214]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-php-211650546?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Engesoftware Tecnologia S.A.</strong> busca <strong><ins>PHP Developer</ins></strong> para compor seu time!</p>
<p>Somos a Engesoftware Tecnologia S.A. e estamos no mercado há mais de 25 anos. Trazendo transformação digital e soluções com sucesso! </p>
<p>Para isso, contamos com profissionais altamente especializados e qualificados, formando equipes multidisciplinares, de acordo com as características específicas de cada projeto. O trabalho em equipe permite que se combine a experiência, a técnica e a criatividade dos profissionais com uma permanente busca da inovação.</p>

## Engesoftware: 
 <p>Estamos no mercado há mais de 25 anos. Trazendo transformação digital e soluções com sucesso.</p>
<p>Para isso, contamos com profissionais altamente especializados e qualificados, formando equipes multidisciplinares, de acordo com as características específicas de cada projeto. O trabalho em equipe permite que se combine a experiência, a técnica e a criatividade dos profissionais com uma permanente busca da inovação.</p><a href='https://coodesh.com/empresas/engesoftware-tecnologia-sa'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- Agile 
- SCRUM 
- Kanban
## Local: 
 Brasília, Distrito Federal, Brasil
## Requisitos: 
 - Ensino Superior completo na área de TI; 
- Experiência sólida na área; 
- Experiência com Metodologias/Processos (Agile, Scrum, Kanban, etc); 
- Possuir certificações relacionadas (CSM, PMP, PSM, etc).

## Benefícios: 
 - Assistência médica; 
- Assistência odontológica; 
- Seguro de vida; 
- Vale alimentação; 
- Vale refeição; 
- Outros.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [PHP Developer na Engesoftware](https://coodesh.com/vagas/desenvolvedor-php-211650546?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by celorg** [comment]
Sou desenvolvedor no início de carreira, tive o primeiro contato com programação na faculdade, e criei uma paixão grande pela a área. Estou a procura de se tornar um desenvolvedor full-stack, aprendendo cada dia mais, minhas habilidades são: html, css, figma, wordpress, php e mySql. Meu próximo passo é aprender sobre Laravel e VueJS .

**Comment by blankapf** [comment]
Legal, Marcelo!
Na Coodesh temos diversas empresas parceiras, então para se candidatar a uma vaga, você precisa criar um perfil em nossa plataforma e se candidatar às oportunidades compatíveis. A criação do perfil é bem rapidinha :)
