### ISSUE TITLE
 Back-end developer EstrelaBet

### ISSUE THREAD

**Issue by RhEstrelaBet** [backend-br/vagas#10213]
Nossa Empresa: 

Somos uma empresa de apostas esportivas e entretenimento. Acreditamos nas pessoas e trabalhamos para impulsionar nosso negócio. Estamos à procura de um(a) Desenvolvedor Back-End para completar o nosso time de Estrelas! 🚀 
 
 Descrição da vaga: 

Participar ativamente na concepção da solução técnica para as necessidades de negócio junto ao time. Realização de code review, pair programming, mob programming, construção de soluções com integração contínua e contribuição com a documentação sistêmica.

Local de Trabalho: 
Homeoffice

Requisitos: 

Proficiência em ao menos uma linguagem (NodeJS, Go, PHP, etc);
Experiência com testes unitários e testes de integração;
Experiência com modelagem de dados em bancos relacionais e não relacionais;
Experiência em criação de APIs REST e/ou Webhooks;
Conhecimento em arquitetura de Software e microserviços;
Conhecimento de Gitflow;

Contratação: PJ 
Como se candidatar:  Candidata-se através do link https://estrelabet.solides.jobs/ ou se preferir pode nos enviar um e-mail rhestrelabet@gmail.com com o assunto " Desenvolvedor Back-End" com o link do Git 😉

Nível: 
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
