### ISSUE TITLE
[Faria Lima- São Paulo- SP] Analista Programador Java Pleno/Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1022]
BRQ Digital Solutions
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque. 

Analista Programador Java Pleno/Sênior
Estamos em busca de um profissional que tenha experiência com 
programação em Java,  EJB, JPA, SpringBoot, Rest, Oracle, MySQL.
Diferenciais: Redis, AWS e Docker.

Forma de contratação
CLT full, salário a combinar.

Benefícios
Vale refeição
Vale alimentação
Seguro de Vida
Previdência privada
Assistências médica e odonto

Horário comercial
Segunda a sexta das 9hs as 18hs.

Local: Faria Lima-SP- perto da estação de trem Cidade Jardim.

Interessou? Cvs para ryokota@brq.com

**Comment by JosephSousa** [comment]
A vaga ainda está aberta?
