### ISSUE TITLE
[Rio do Sul/SC] Back-End: Node JS na Riderize

### ISSUE THREAD

**Issue by fabriciosautner** [backend-br/vagas#10225]
## Nossa empresa

Somos uma plataforma esportiva para Ciclistas. Desenvolvemos todo o ecossistema através de experiências importantes para quem é ciclista. Estamos nos preparando para o lançamento mundial.

## Descrição da vaga

Participar do time de Bach-ends responsáveis por servir a plataforma (App e Desktop). E ser protagonista na primeira empresa brasileira com Gravador de Atividades (pedaladas) no próprio App.

Como será seu dia a dia:

- Participar de planejamento SCRUM junto com o time de desenvolvimento
- Implementar tecnologias modernas dentro de serviços de tecnologia
- Conhecer todo o ecossistema de um backend para aplicativo
- Entregar features usadas por milhares de pessoas todos os dias
- Evoluir na carreira de desenvolvedor trocando experiências com outros desenvolvedores
- Sentir a experiência de programar lado a lado com pessoas incríveis e divertidas

## Local

Escritório em Rio do Sul/Santa Catarina

## Requisitos

**Obrigatórios:**
- Conhecimentos em NodeJS
- Typescript

**Desejáveis:**
- GraphQL/Apollo
- Conhecimentos de Postgres

**Diferenciais:**
- Conhecimentos de Mapas
- Conhecimentos em REDIS
- Conhecimentos em Prisma
- Conhecimentos em AWS

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [pessoas@riderize.com](mailto:pessoas@riderize.com) com seu CV anexado - enviar no assunto: Vaga NodeJS

## Faixa Salarial

- Entre 2k e 6k inicial

### Nível

- Júnior
- Pleno

### Regime

- PJ

### Alocação

- Presencial

**Comment by alefks** [comment]
Sem possibilidade alguma de ser remoto? :(
