### ISSUE TITLE
[São Paulo] FullStack Developer Pleno na Taki Pagamentos (FINTECH)

### ISSUE THREAD

**Issue by takipagamentos** [backend-br/vagas#1023]
## Descrição da vaga

Chegou a hora de você trabalhar em uma Fintech com projetos disruptivos que estão mudando o comportamento do consumidor e empreendedores do Brasil. 
Trabalhamos com soluções de maquininhas de cartões, gateway on-line e soluções Open Bank.

Buscamos profissionais que queiram cair de cabeça na melhor experiência da vida deles com Startups FinTech.

## Requisitos
- Que tenha uma pegada mais back-end, mas com flexibilidade no front-end.
- Python (Django) 
- Node.js
- Arquitetura de Microserviços 
- Docker, Container, 
- HTML, Javascript e CSS. 
- Algum framework MVC Angular, React ou Vue. 

**Diferenciais**
- Já ter trabalhado com POS (Maquininha de cartões) ou C++. 
- Já ter trabalhado com migrações de Python para Node.js
- Kubernetes

## Local
Escritório próprio - São Paulo/ Zona Sul - Vila Olímpia (ao lado da estação).

## Benefícios
Ambiente descolado, equipe unida, com alto nível de senioridade, prontos para treina-lo e ajuda-lo a aumentar seus conhecimentos e torna-lo um ninja. 

- Ambiente sem dress code.
- Horário Flexível.
- Geladeira com cerveja.
- Contratação PJ + 30 dias de férias. 

**Gostou? Vem com a gente!** 

## Contratação
PJ a combinar

## Como se candidatar

Por favor envie um email para fabio.sarmento@taki.com.vc com seu CV anexado - enviar no assunto: Vaga FullStack Pleno

**Comment by brunooomelo** [comment]
aceita remoto?
