### ISSUE TITLE
[Remoto] Back-End Software Engineer Pl/Sr - TRACTIAN

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#10231]
## Nossa empresa

A Tractian está reinventando os sistemas industriais para que cada trabalhador da linha de frente possa realizar todo o seu potencial. Como o sistema operacional industrial, estamos construindo software e hardware em um só lugar, interrompendo instituições há muito enraizadas com produtos e experiências que atendem melhor às ambições de nossos clientes.

## Descrição da vaga

Como engenheiro de software de back-end, você será responsável por criar produtos e infraestrutura inovadores para a Tractian e nossos clientes. Acreditamos que os engenheiros devem acelerar os negócios por meio da tecnologia e colaborar entre várias equipes para conseguir isso. Você vai:

- Criar e manter nossas novas APIs em Node JS e Typescript
- Dê vida à infraestrutura que os gerentes de manutenção usam diariamente
- Crie um código limpo e orientado a testes focado em enfrentar novos desafios

## Local

Remoto

## Requisitos

- 3+ anos de exposição ao NodeJS e Typescript
- Mais de 2 anos trabalhando com bancos de dados SQL ou NoSQL
- Experiência com outras linguagens de programação backend (Go, C++, Python)
- Familiaridade com MongoDB

## Benefícios

- Salário competitivo e opções de ações
- R$ 800/mês para uso em diversos locais que aceitam bandeira Visa
- GymPass para não ficar sentado/trabalhando o dia todo
- Curso de inglês/espanhol 100% financiado
- 30 dias de férias anuais remuneradas
- Bolsa de estudos e cursos
- A cada 3 anos, ganhe uma viagem para qualquer lugar do mundo
- Dia de folga na semana do seu aniversário
- A partir de R$ 2.400/ano subsídio de trabalho remoto
- Apoio à saúde mental: cobrimos 40% do custo da sua terapia
- Plano de saúde com cobertura nacional e sem coparticipação.
- Seguro Odontológico: ajudamos você no tratamento odontológico para uma melhor qualidade de vida.
- Incentivo ao Esporte: R$ 300/mês extra se você praticar atividades

## Contratação

CLT

## Como se candidatar

Clique [aqui](https://remotar.com.br/job/1638/tractian/back-end-software-engineer-plsr?utm_source=github) para saber mais

OBS: a TRACTIAN é cliente da Remotar. Ao clicar no link acima você será redirecionado para nosso site, mas todo o processo seletivo ficará sob responsabilidade da TRACTIAN. 

### Nível

- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Remoto

**Comment by jjpaulo2** [comment]
Esta vaga ainda está aberta @tatidirienzo?
