### ISSUE TITLE
[Híbrido] Back-end developer - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#10247]
Nexmuv

Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Desenvolvedor Java 
Buscamos por um(a) profissional que busque crescimento junto ao negocio. Que AME tecnologia e se aventure em novos desafios. 

## Local

híbrido- Berrini - SP 

## Requisitos

Atuar com desenvolvimento Java; modelagem de banco de dados ; orientação a objeto; React ou angular; HTML; CSS; JavaScript 

## Contratação

PJ 

## Como se candidatar

Interessados, enviar CV para Helen.matos@nexmuv.com.br 

### Nível
- Pleno
- Sênior

### Regime
- PJ

### Alocação
- Híbrido

**Comment by gustavofreze** [comment]
Olá @HelenNexmuv. Você poderia, por gentileza, editar a vaga colocando quais os benefícios a empresa oferece?

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028)
