### ISSUE TITLE
[Uberlândia] - Desenvolvedor Backend Pleno/Senior

### ISSUE THREAD

**Issue by Valeriavnn** [backend-br/vagas#10265]
Empresa de tecnologia atuando na área do agronegócio (Agrotech), focada em coletar, processar e analisar dados do clima e soluções que envolvem inteligência artificial está em busca de uma pessoa desenvolvedora backend.

Para essa oportunidade conseguimos abordar perfis de diversas linguagens backend, como Java, Ruby on Rails, Python etc, mas que queiram fazer a migração para GoLang, que é a linguagem que será utilizada. Se conseguirmos perfis que já venham desta linguagem melhor ainda!

Essa pessoa será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades nos diversos serviços e aplicações que compõem backend.

**Requisitos e experiências exigidas:**

- Experiência com linguagem de programação focada no backend;
- Boa experiência em Linguagem SQL e banco de dados;
- Ferramentas de desenvolvimento e depuração de código;
- Testes unitários;
- Inglês intermediário;

**Desejável:**
- Experiência em ambientes Cloud (AWS ou GCP)
- Experiência com Docker;
- Experiência com CI / CD e Jenkins
- Conhecimento em Metodologias ágeis;
- Vivência com inteligência artificial;
- Conhecimentos de frontend: HTML + JavaScript + CSS;

**Local:**
Presencial em Uberlândia

**Contratação:**
PJ

**Como se candidatar**
Enviar currículo para recruiter.valeria@gmail.com

**Comment by gustavofreze** [comment]
Olá @Valeriavnn . Você poderia, por gentileza, editar a vaga colocando quais os benefícios a empresa oferece?

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
