### ISSUE TITLE
[Desenvolvedor Backend NodeJS Sênior] - Remoto - Hunter Hunter

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#10269]
[Desenvolvedor Backend NodeJS Sênior] - Remoto. PJ entre 15 mil a 20 mil negociável. Empresa Canadense. Inglês avançado.

Mandatório:

- Mais de 10 anos de desenvolvimento e 5 com NodeJS.
- Inglês avançado e para conversação.

Se tiver com https://strapi.io/ é um plus.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
