### ISSUE TITLE
[REMOTO] Java Solutions Architect na Builders

### ISSUE THREAD

**Issue by stefaniesoares** [backend-br/vagas#10275]
Como será seu dia-a-dia?
Seu papel será trazer novas perspectivas, estabelecendo parcerias com clientes, com equipe de desenvolvimento de negócios, engenharia e produtos para desenvolver arquiteturas escaláveis, flexíveis, lidando com os problemas dos clientes e acelerando a adoção de nossos serviços.

Para cumprir esse desafio, você precisa dominar: 
Apache Kafka
Java 8+
Jenkins
Clou
Spring
Microsserviços
Design Patterns
REST

Será um diferencial se você tiver também: 
Ansible (Red Hat)
Openshift
Kubernetes

O que nós oferecemos?
Atuação 100% remota;
Parceria com coworking em São Paulo;
Webnars semanais para expandir ainda mais seu conhecimento;
Participar de um processo único de geração de valor;
Contribuir na criação de métodos disruptivos;
Possibilidade de profit share de novos negócios.

Encaminhe seu currículo para: stefanie.soares@platformbuilders.io

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
