### ISSUE TITLE
[REMOTO] JAVA TECH LEAD - BUILDERS

### ISSUE THREAD

**Issue by stefaniesoares** [backend-br/vagas#10277]
Conhece o Movimento Builders?
Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios. 
Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar! 

Como será seu dia-a-dia?
No papel de Tech Lead, a pessoa Builder trabalhará em equipes para fornecer soluções robustas e escaláveis para a automação de processos de negócios complexos. Deverá conduzir o processo de delivery para que os membros de sua equipe tenham um especialista confiável e esperam que você defina o ciclo de vida de desenvolvimento de software de ponta a ponta de acordo com as melhores práticas modernas.

Para cumprir esse desafio, você precisa dominar: 
Java 8+;
Ferramentas de CI/CD como Jenkins, ArgoCD, Github Actions;
Cloud;
Spring;
Microservices;
REST;
Design Patterns;
Metodologia ágil.

Será um diferencial se você tiver também: 
Vivência em projetos de aplicativos ou produtos web de alta audiência;
Conhecimento em desenvolvimento e entrega de software em Kubernetes;

O que nós oferecemos?
Atuação 100% remota;
Parceria com coworking em São Paulo;
Webnars semanais para expandir ainda mais seu conhecimento;
Participar de um processo único de geração de valor;
Contribuir na criação de métodos disruptivos;
Possibilidade de profit share de novos negócios.

Encaminhe seu currículo para: stefanie.soares@platformbuilders.io

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
