### ISSUE TITLE
[Remoto] Senior Java developer - Builders

### ISSUE THREAD

**Issue by stefaniesoares** [backend-br/vagas#10276]
Como será seu dia-a-dia?
Como Java Developer você irá trabalhar em projetos de desenvolvimento de produtos digitais junto com grandes empresas, apoiado por uma equipe de tecnologia, designers e gestores. Buscamos pessoas desenvolvedoras apaixonadas pela linguagem Java, inconformadas por natureza e encantadas em gerar valor.

Para cumprir esse desafio, você precisa dominar: 
Java 8+
Springboot
Unit Test
JPA
GIT
Linux
DDD

Será um diferencial se você tiver também: 
Docker e Kubernetes
Cloud
Plataformas de CI/CD como Jenkins, ArgoCD, Github Actions
Maven
Arquitetura de Microsserviços
Rest
Design Patterns

O que nós oferecemos?
Atuação 100% remota;
Parceria com coworking em São Paulo;
Webnars semanais para expandir ainda mais seu conhecimento;
Participar de um processo único de geração de valor;
Contribuir na criação de métodos disruptivos;
Possibilidade de profit share de novos negócios.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
