### ISSUE TITLE
[Remoto]  - Desenvolvedor Backend - Land Tech

### ISSUE THREAD

**Issue by juulander** [backend-br/vagas#10289]
## Nossa empresa

A Land Tech é uma consultoria de recrutamento e seleção focada em tech e digital e está apoiando uma grande empresa de agro localizada em Ribeirão Preto.

## Local

Remoto. 

## Requisitos

Conhecimentos avançados em sistemas operacionais Windows e Linux
Lógica de programação
Linguagens de programação (Javascript, Python)
Experiência com banco de dados relacional e não relacional (MySQL / Postgresql / DynamoDB / MongoDB)
Estruturar servidor web
Metodologia de projetos ágeis
Metodologia serverless (AWS, Azure, Google)

## Contratação

CLT

## Como se candidatar

Enviar um e-mail com CV anexado para julia.saraiva@landtech.net.br ou entrar em contato via whatsapp no +55 11 94283-0912.

### Nível

- Sênior

### Alocação

- Remoto, mas nos primeiros 2 meses é necessário algumas idas a empresa (Ribeirão Preto) para integração.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
