### ISSUE TITLE
[Barueri] Desenvolvedor C# .NET JR - Home Office PJ na WTIME

### ISSUE THREAD

**Issue by AnieliFernanda** [backend-br/vagas#103]
Wtime Business Intelligence IT, contrata para atuar em cliente :

**Desenvolvedor C# .NET Junior**

Experiência em: Visual Studio .NET, REST,Database(SQL Server e PostGre)
Web API, WCF, WF, MVC, and ASP.NET, Angular JS, HTML5 e CSS, Message Queues(AWS SQS,
RabbitMQ, MSMQ).
Desejável Design patterns, NoSQL

**Local de trabalho Alphaville/ Jundiaí (1 vez na semana) e Home Office (4 dias na semana).**

Modalidade PJ
Interessados enviar currículo no e-mail anieli.fernanda@wtime.com.br

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
