### ISSUE TITLE
[São Paulo] Back-End Developer NodeJs / PHP na Vá de Táxi

### ISSUE THREAD

**Issue by franciscorangel** [backend-br/vagas#1030]
Fundado em 2013, o Vá de Táxi é um aplicativo de chamada de táxis, pioneiro no modelo de pagamento in-app. Em 2014 recebeu investimentos da Incube, primeira venture builder do Brasil. Em setembro de 2015 fez a fusão com o Taxijá da UOL e em maio de 2016 anunciou a segunda fusão em menos de um ano, desta vez com a WayTaxi, o aplicativo para chamada de táxi mais usado em Minas Gerais. Mais recentemente, o app foi escolhido pela Apple para ser o parceiro exclusivo de mobilidade para o lançamento do Apple Pay no Brasil.

**Local**
Escritório São Paulo - Higienópolis

**Benefícios**
Programa de benefícios da empresa
Cursos pagos pela empresa
Flexibilidade de horário
Frutas todas as sextas-feiras
Voucher para usar táxi todos os meses
Videogame para as horas livres depois do trabalho
A remuneração é avaliada individualmente por candidato, leva-se em consideração o perfil e experiência, tudo é sempre conversado e alinhado para que seja vantajoso para todos e condizente com o mercado. Nosso forma de contração é CLT ou PJ tudo é combinado.

**Atividades e Responsabilidades**
Desenvolvimento e manutenção de aplicações web; 
Aplica melhores práticas de documentação de código desenvolvido; 
Desenvolver e sustentar integrações; 
Realizar a manutenção e criação de novas funcionalidades; 
Aplicar melhores práticas de documentação de código desenvolvido; 
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;

**Requisitos:**
Experiência de pelo menos 2 anos com desenvolvimento PHP ou Nodejs;
Experiência de pelo menos 2 anos com algum framework de desenvolvimento WEB: Express, Yii, Laravel, etc;
Sólido conhecimento em desenvolvimento de REST APIs;
Conhecimento de HTML, CSS
Versionamento de Código: Git
Vivência com bancos de dados relacionais preferencialmente Mysql ou PostgreSQL;
Conhecimentos em bancos de dados não relacionais;
Desenvolver código limpo, de fácil compreensão e manutenção;
Interesse por novas tecnologias e padrões de arquitetura "fora da caixa";
Capacidade de trabalho com uma equipe multidisciplinar;
Ter capacidade de compreender como seu trabalho afeta a empresa como um todo, muito além do código;
Conhecer Linux: Saber gerenciar serviços, buscar informações em logs e compreendê-las;

**Diferenciais:**

Testes automatizados;
Conhecimento em Docker;
Conhecimento de estrutura de infraestrutura em AWS;
Agile methodologies (Scrum, Kanban);
Vivência em projetos ágeis
Experiência com Microsserviços;

**Caso você deseje se candidatar, por favor envie um email para vagas@vadetaxi.com.br com seu CV anexado - enviar no assunto: Vá de Táxi - NOME DA VAGA**

**Comment by RafaelGSS** [comment]
Olá!

Aceita remoto?

**Comment by samuelfaj** [comment]
Seria possível trabalhar como PJ remoto? Tenho bastante experiencia em nodejs e PHP, alem de microsserviços, aws e métodos ágeis.
