### ISSUE TITLE
[Remoto] Back-end developer (Ruby on Rails/Golang) - Globo

### ISSUE THREAD

**Issue by juulander** [backend-br/vagas#10313]
## Nossa empresa

O Grupo Globo é o maior conglomerado de mídia e comunicação de todo o país. Formado por diversas empresas das áreas de Jornalismo, Esporte e Entretenimento. Eles têm aproximadamente 15k colaboradores e o grupo atinge 99,6% da população brasileira e tem uma atuação ampla em todas as plataformas que se encontra.

## Local

Remoto.

## Requisitos

Obrigatórios:
- 3 anos de experiência com Ruby on Rails e Golang.
- Conhecimento em banco de dados não relacionais. 
- Conhecimento em testes unitários, de integração e de carga.

## Contratação

CLT.

## Benefícios
PLR
Vale Alimentação e Refeição
Assistência Médica e Odontológica
Seguro de Vida 
Previdência Privada

## Como se candidatar

Enviar um e-mail para julia.saraiva@landtech.net.br ou entrar em contato via whatsapp no +55 11 94283-0912.

### Nível

- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Remoto

**Comment by gustavofreze** [comment]
Olá @juulander. Você poderia por gentileza editar a sua publicação, e colocar os benefícios oferecidos para a vaga?

**Comment by juulander** [comment]
> Olá @juulander. Você poderia por gentileza editar a sua publicação, e colocar os benefícios oferecidos para a vaga?

Feito! :)
