### ISSUE TITLE
[Remoto] Back-end developer (Linguagem de programação C) - Triad Systems

### ISSUE THREAD

**Issue by Luiza3004** [backend-br/vagas#10329]
## Nossa empresa

Respiramos tecnologia.
A tradicional e a digital.
Transformamos exponencialmente os resultados de nossos clientes por meio de inovação e inteligência de dados.
Conheça a Triad: https://www.triadsystems.com.br/

## Descrição da vaga

Será responsável pelo desenvolvimento do software, avaliando a viabilidade do desenvolvimento do produto e propondo sugestões de implementação seguindo as boas práticas de codificação.

Desenvolver aplicações, conforme projetado pelo analista, usando as ferramentas disponibilizadas pela empresa;
Dar manutenção e suporte aos softwares desenvolvidos pela empresa;
Efetuar a correção dos erros identificados e reportados pelos Analistas de Testes e Testadores;
Garantir a integridade/qualidade do software desenvolvido;
Acompanhar e buscar melhoria dos sistemas que estão sendo desenvolvidos;
Garantir o controle de versão do sistema que está sendo desenvolvido usando a ferramenta disponibilizada pela empresa;
Documentar o software que está sendo desenvolvido;
Implementar softwares seguindo as boas práticas de desenvolvimento de código seguro;
Acompanhar homologações e desenvolver softwares nas dependências do cliente, se necessário.

## Local

Remoto

## Requisitos
Experiência com linguagem de programação C.
C Ansi
Socket
Linux/Windows
Microsoft Visual Studio
Git

Desejáveis
Android
WebSocket
Desenvolvimento de sistemas de Varejo
Ensino Superior completo ou em andamento em áreas de TI

Diferencial
Experiência em desenvolvimento de sistemas de Varejo (PDV).

## Contratação

PJ (Necessário ter empresa LTDA aberta)

## Benefícios

Sem benefícios (Contratação PJ)  

## Como se candidatar

Interessados no perfil da vaga, enviar currículo com pretensão salarial e título da vaga para luiza.longo@triadsystems.com.br

### Nível

- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by gustavofreze** [comment]
Olá @Luiza3004. Você poderia por gentileza editar a sua publicação, e colocar os benefícios oferecidos para a vaga?

**Comment by Luiza3004** [comment]
Bom dia @gustavofreze, tudo bem ?

Por ser uma vaga PJ não oferecemos nenhum tipo de benefício.

**Comment by gustavofreze** [comment]
Entendi. Mas, mantenha o padrão que a issue gera. Se não tem benefícios, especifique lá.
