### ISSUE TITLE
[Curitiba] FullStack Developer Pleno na Zimobi - Ruby/React

### ISSUE THREAD

**Issue by douglara** [backend-br/vagas#1033]
**Sobre nós**
Somos uma startup no mercado imobiliário, uma alternativa para a locação de imóveis sem mobiliaria mas com segurança e transparência.

**Descrição da vaga**

Manter e evoluir nossa aplicação que utiliza no back Ruby on Rails e de front React
Implementação de novas features e participar de todo o ciclo de desenvolvimento de produto

**Requisitos**

- TDD
- Docker
- React + Redux
- Rails
- TypeScript
- RESTful
- Redis

**Local**
Presencial em Curitiba no Centro Cívico.

**Como se candidatar**
Por favor envie um email para douglas@zimobi.com.br com seus dados, colocar no assunto: Vaga FullStack Pleno

Labels
Fullstack, PJ, Ruby on Rails, ReactJS, Presencial

**Comment by garaujodev** [comment]
Apenas presencial para esta vaga?

**Comment by douglara** [comment]
Oii @garaujodev sim, essa vaga é apenas presencial
Abss!
