### ISSUE TITLE
[100% REMOTO] Dev. Ruby on Rails e Bootstrap - Truppe!

### ISSUE THREAD

**Issue by Camila-Goms** [backend-br/vagas#10336]
**Sobre a empresa:**

A [Trupppe!](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 3 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital. 

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

**Descrição da vaga:**

Buscamos uma pessoa desenvolvedora com foco em Ruby on Rails e Bootstrap Sênior para atuar em um de nossos clientes! 

**Responsabilidades e Atribuições:**

• Desenvolvimento e manutenção de aplicações web;
• Realizar a manutenção e criação de novas funcionalidades;
• Desenvolvimento e manutenção de aplicações mobile;
• Aplicar melhores práticas de documentação de código desenvolvido;
• Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
• Desenvolver e sustentar integrações de sistemas.

**Nível**

SÊNIOR

**Local:**

100% Remoto.

**Requisitos:**

• Ruby on Rails;
• Bootstrap;
• Conhecimento em metodologias ágeis (Scrum/Kanban);
• Habilidades interpessoais de escrita e de comunicação verbal;
• Experiência com ferramentas de versionamento de código (GIT e outras);
• Experiência prévia em desenvolvimento nas linguagens mencionadas.

**Contratação**

PJ (tempo indeterminado) - Pretensão Salarial a combinar

**Como se candidatar**

Por favor, envie um email para *camila.gomes@truppe.team* com seu CV atualizado anexado, link do perfil do Linkedin (se utilizar) e pretensão salarial CLT no corpo do email.

Enviar no assunto: *Vaga Dev. Ruby on Rails - SR*

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).

**Comment by Camila-Goms** [comment]
O que não está de acordo? Estou buscando um dev backend Ruby on Rails, não entendi!

**Comment by gustavofreze** [comment]
_Vagas com informações fora do modelo de issues. O modelo é gerado automaticamente ao abrir uma nova issue._
