### ISSUE TITLE
[Lisboa ou Porto] Java Developer @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#10348]
## Estás à procura de projetos internacionais na área de TI? Se o teu objetivo é ser bem-sucedido na Europa, temos novidades para ti!

Requisitos:

- +4 anos de experiência profissional em desenvolvimento Java;
- Experiência em Spring e Spring Boot;
- Experiência em testes TDD/BDD;
- Conhecimentos em Micro Serviços;
- Familiaridade com metodologias Agile;
- Inglês fluente (obrigatório).

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).
