### ISSUE TITLE
[100% remoto] Devops Sênior @FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [backend-br/vagas#10363]
2 vagas em Sênior

Conhecimento em Devops com ambiente Cloud, muito focados em AWS.

Contratação
PJ

Benefícios
Horários flexíveis
Diferenciais
Ambiente descontraído

● 80hs em banco de horas, como descanso, após 1 ano de contrato
●  Possibilidade de bônus ate 2x o valor de prestação de serviços (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento pessoal
compra de livros, cursos, certificações e participação de eventos da área de tecnologia.

Nossa empresa

Dê uma olhada no nosso Site : http://www.fdte.org.br/
a Fundação é com foco em engenharia - ligada a Poli USP
o nosso escritório é um braço que é da Tecnologia

Como se candidatar
Por favor, envie um e mail para [vanessa.bruno@fdte.io](mailto:vanessa.bruno@fdte.io) - com seu CV anexado - enviar no assunto: Vaga Devops

Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois não está de acordo com as [regras](https://github.com/backend-br/vagas/issues/10028).

**Comment by VanessaBruno3** [comment]
Por favor, qual foi a parte que errei?
Para não fazer novamente

**Comment by gustavofreze** [comment]
@VanessaBruno3 _Vagas com informações fora do modelo de issues. O modelo é gerado automaticamente ao abrir uma nova issue._

Quando você abrir a issue, mantenha a estrutura que ela gera, e preencha todos os tópicos.
