### ISSUE TITLE
[Curitiba] Back-End Developer PL / SR na [commcepta]

### ISSUE THREAD

**Issue by suzane-machado** [backend-br/vagas#1037]
Consideramos trabalhar com tecnologia um grande desafio. A tecnologia está em constante mudança e nós também. Estamos buscando pessoas que amem o que fazem. 
Trabalhar em equipe também é importante, afinal troca de ideias é fundamental para projetos inovadores.

**// Qual o desafio que propomos?** 
- Enfrentar códigos "cabeludos" e transformar em códigos perfeitos 
- Não vai deixar escapar um ponto e vírgula além de manter o padrão de indentação 
- Ser minucioso com os detalhes 
- Compartilhar conhecimentos com a equipe 
- Estar sempre em busca de novos desafios e tecnologias

**// Processo Seletivo** 
- Envio de CV atualizado para análise. 
- Teste online específico e referente a atuação. 
- Entrevista presencial. 
- Definição da contratação.

**// Requisitos Obrigatórios** 
- Formação em Nível Superior em Ciência da Computação, Tecnologia da Informação ou Análise de Sistemas
- Fluência em PHP / SQL / Javascript e com ferramentas de versionamento de código (git); 
- Conhecimento com HTML5, CSS3 (Sass) e/ou frameworks de Front-End (AngularJS, Vue.js ou ReactJS) para integração; 
- Customização em WordPress; 
- Administração de Servidores Cloud

**// Diferenciais** 
- Ambiente MacOS 
- Conhecimento em Laravel 
- Desenvolvimento / Integrações API

**// Contração**
- CLT
- Vaga Presencial
- Vale Refeição 

**// Equipe**
- Café à vontade 
- Equipe talentosa e divertida 
- Sextas à partir das 17:00 tá liberado sua cerveja!

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by suzane-machado** [comment]
Pleno / Senior

**Comment by suzane-machado** [comment]
> Senioridade?

Pleno / Senior
