### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Pleno na Compart

### ISSUE THREAD

**Issue by maranesi** [backend-br/vagas#104]
## Descrição da vaga
Este profissional irá compor um time que será responsável por desenvolver os novos produtos da empresa, utilizando processos ágeis e focados em agregar valor ao cliente.

## Atividades
•    Atuar no desenvolvimento dos novos produtos da empresa.
•    Construir e manter um código eficiente. 
•    Promover melhorias de desempenho e qualidade de código.
•    Participar do processo criativo e auxiliar na construção das aplicações.
•    Acompanhamento de novas tecnologias (abertura a testar novas abordagens).
•    Trabalho em equipe, facilidade em se comunicar e debater sobre soluções buscando a melhor solução.

## Local
Rua Massacá, 418 - Alto de Pinheiros/SP - Brasil 

# Benefícios
•    VT, VR e VA;
•    Estacionamento.
•    Plano de Saúde, Odontológico e Seguro de Vida.
•    Day off.
•    Massagem 1 vez por semana.

## Requisitos
•    Formação superior na área de tecnologia.
•    Bons fundamentos em OO, PSR, SOLID, Design Patterns e CleanCode.
•    3 anos de experiência com PHP 5+.
•    Experiência em frameworks, preferível Symfony/Laravel
•    Controle de versão GIT.

**Diferenciais**:
•    MongoDB
•    Testes unitários
•    Docker
•    Conhecimento em framework JS (Vue, React ou Angular)
•    Noções de arquitetura escalável e microservices.

**Stack:**
•    PHP 7.1
•    Laravel 5.5
•    MongoDB
•    Redis, ElasticStack.

## Contratação
•    CLT Efetivo;

## Nossa empresa
A Compart é uma empresa especializada em trade marketing, merchandising e soluções de tecnologia da informação. Está no mercado desde 1995, proporcionando serviços de qualidade com tecnologias inovadoras no gerenciamento de equipes de campo, gerando as melhores soluções e resultados de sucesso no trade marketing. 

## Como se candidatar
Interessados enviar currículo com pretensão salarial para: bruno.maranesi@compart.com.br com o assunto "Compart | Vaga Desenvolvedor PHP [Full Stack]"

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
