### ISSUE TITLE
[Remoto] Back-end developer - Life Software Development 

### ISSUE THREAD

**Issue by mdiniz007** [backend-br/vagas#10429]
Life Software Development

## Descrição da vaga

Desenvolver infraestrutura de back-end de alto desempenho, escalável e disponível.
Contribuir e melhorar continuamente a arquitetura do nosso site, componentes de recursos, processo de desenvolvimento e ferramentas SDLC e design do sistema.
Traduzir requisitos de produtos e projetos técnicos em códigos robustos, bem projetados e com poucos defeitos.
Pesquise novas tecnologias ou metodologias que possam melhorar a arquitetura, a experiência do usuário ou o processo de desenvolvimento.
Participar de code review, manter a mente aberta em relação a feedback e compartilhando seus Conhecimentos com outros membros da equipe

## Local

remoto

## Requisitos

3+ anos de experiencia na área em Back End
2+ anos de experiencia em Ruby e Rails
Habilidade em trabalhar com várias equipes
Experiência com Kubernetes, Docker, APIs (REST e GrapgQL)
Ser familiarizado com a linguagem de programação OO e as ferramentas como PostgreSQL e Redis
inglês intermediário

## Benefícios

Salários a partir de 10 mil

## Contratação

CLT

## Como se candidatar

lifesoftwaredevelopment@gmail.com
telefone/whatsapp: (83) 99849-9750

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Remoto

**Comment by GefersonLopes** [comment]
enviado!
