### ISSUE TITLE
[engenheiro de dados/infra - PHP ] Back-end developer - Aquila Company

### ISSUE THREAD

**Issue by julliAquila** [backend-br/vagas#10428]
Precisamos de um engenheiro de dados/infra que nos ajude a encontrar a melhor solução para o nosso projeto:
Temos um site wordpress sustentado pela plataforma [kinsta](https://kinsta.com/) a função desse site é permitir uma pesquisa no nosso banco de dados, dentro do próprio wordpress, que atualmente tem 39.000 linhas. 

Neste cenário, queremos resolver 2 problemas:

1-	O kinsta disponibiliza apenas 260mb e por conta do tamanho do banco, estourou o limite e não roda mais a pesquisa, então queremos descobrir quais opções mais viáveis para mantermos esse bd que será crescente.

2-	Queremos que quando algum nome digitado na pesquisa ainda não conste no nosso bd que seja feita uma requisição real time em outros sites e se encontrado seja acrescentado ao nosso bd para pesquisas futuras. 
Estamos dispostos a trocar as ferramentas que já usamos e de construir novos caminhos se essa for a melhor maneira de fazer esse projeto funcionar. 
Esperamos d@ engenheir@ : uma consultoria a fim de construirmos juntos o melhor cenário, juntando ferramentas já existentes no mercado, de preferência,  mas também aceitamos construir uma parte ou outra. Temos uma equipe front end de 4 colaboradores internos que estarão disponíveis para a mão na massa.

### Nível
- Especialista

### Regime
- PJ
- Contrato
- Freelance

### Alocação
- Remoto

Entrar em contato via - jullia@aquilacompany.com

**Comment by julliAquila** [comment]
Interessados entrar em contato via : jullia@aquilacompany.com

**Comment by Cosmess** [comment]
Olá ! Creio que posso ajuda-los, meu contato (11) 95777-0643.
