### ISSUE TITLE
[Remoto] Back-end developer C# Sênior - Locus Custom Software

### ISSUE THREAD

**Issue by geysakarlagalvao** [backend-br/vagas#10438]
## Nossa empresa

A Locus Custom Software é uma empresa global que oferece serviços de desenvolvimento de software, design e soluções digitais. Trabalhamos para criar valor para os negócios dos nossos clientes através de tecnologias ágeis e inovadoras.
Acreditamos que nossos processos internos e nossas entregas geram valor! Nossa equipe se dedica a transformar ideias em grandes negócios de sucesso, utilizando tecnologias para ampliar resultados.

## Descrição da vaga

Desenvolvedor C# Sênior.

## Local

Remoto.

## Requisitos

Perfil:

Conhecimento e experiência em Docker, Mensageria, Micro serviços, metodologias ágeis, Scrum, C# 5 e 6, .Net Core 5 e 6, API Rest, RabbitMQ, NoSQL e Mongo DB.

## Benefícios

Informe os benefícios oferecidos pela empresa.

## Contratação

A contratação pode ser PJ ou CLT. 
Se for contratação CLT, os benefícios são: 
Plano de saúde e odontológico Bradesco e vale refeição ou alimentação no valor de R$700,00 (ambos sem desconto). 
Trabalhamos com pretensão salarial; 
São 40h semanais (8h diárias).

## Como se candidatar

Enviar currículo para o e-mail: vagas@locus.software.

### Nível

- Sênior

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by geysakarla** [comment]
Envie seu currículo para o e-mail: vagas@locus.software

**Comment by geysakarla** [comment]
Envie seu currículo para o e-mail: vagas@locus.software.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
