### ISSUE TITLE
[Remoto] Python Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#10437]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-python-pleno-100percent-remoto-174847023?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>ClearSale</strong> está em busca de <strong><ins>Python Developer</ins></strong> para compor seu time!</p>
<p>A Diretoria do TechLabs é a área de tecnologia da ClearSale que atua no mercado de onboarding digital voltado a identificação de fraudes e criação de processos seguros e com experiência sem atrito - frictionless.</p>
<p></p>
<p><strong>Responsabilidades: </strong></p>
<ul>
<li>Desenvolvimento de API's em Python;</li>
<li>Implementação de modelos criados de machine learning na área de visão computacional e processamento de documentos;</li>
<li>Experimentar novas tecnologias e formas de resolver problemas que questionem o status quo;</li>
<li>Atuação em análise e correção de incidentes em ambientes de produção;</li>
<li>Participação ativa nos chapters e ritos dos times e squads;</li>
<li>Discussões técnicas de melhoria de performance e novas tecnologias.</li>
</ul>
<p></p>
<p><strong>Vem com a gente se você é uma pessoa com:</strong></p>
<p>Habilidade de entender os problemas e procurar soluções;</p>
<p>Curiosidade e motivação para se manter atualizado com novas tecnologias de mercado e identificar se estas podem ser incorporadas à solução;</p>
<p>Relacional, interesse e motivação para se comunicar entre squads e clientes;</p>
<p>Interesse por trabalhar tanto em projetos estruturantes de longo prazo como em resolução de incidentes.</p>
<p></p>
<p>Local de Trabalho: Estamos de mudança para Barueri, mas adotamos o Remote First e você é livre para trabalhar de qualquer lugar!</p>

## ClearSale: 
 <p>A ClearSale (CLSA3) é referência em inteligência de dados com múltiplas soluções para prevenção a riscos em diferentes mercados, como e-commerce, mercado financeiro, vendas diretas, telecomunicações, entre outros. É a empresa que mais conhece o comportamento do consumidor digital brasileiro, o que a faz impulsionar negócios em todo o ecossistema da economia digital.</p>

<p>Por meio do seu time de especialistas, a ClearSale tem o propósito de gerar um efeito de rede de proteção no mercado digital, identificando padrões de ataques, protegendo os mais variados segmentos de negócio e promovendo impacto positivo, para garantir a melhor experiência ao usuário, com mínima fricção, do onboarding ao transacional.</p><a href='https://coodesh.com/empresas/clearsale'>Veja mais no site</a>

 ## Habilidades: 
 - Python 
- Web Services 
- Microsserviços
## Local: 
 100% Remoto
## Requisitos: 
 - Ensino superior completo nas áreas de computação ou conhecimento comprovado em experiências profissionais anteriores sólidas; 
- Conhecimento em Python; 
- Conhecimento em Web Services (Flask ou Django ou FastApi ou equivalentes); 
- Conhecimento em Microsserviços; 
- Conhecimento em monitoramento e alarmes de microsserviços; 
- Ter atuado com a utilização de metodologias ágeis; 
- Ter atuado com utilização de ambientes de Cloud (Azure ou AWS ou GCP); 
- Conhecimento em banco de dados de documentos (MongoDB ou CosmosDB ou DynamoDB ou equivalentes); 
- Conhecimento de Orientação a Objetos, Design Patterns e Arquitetura de Software.
## Diferenciais: 
 - Conhecimento e utilização de Kubernetes e Docker; 
- Utilização da plataforma Azure Devops e Cloud Azure; 
- Visão e planejamento estratégico com foco no negócio; 
- Conhecimento em programação funcional.
## Benefícios: 
 - PLR (Participação nos Lucros e Resultados); 
- Vale Refeição ou Vale Alimentação; 
- Auxílio Creche para crianças até 4 anos e 11 meses; 
- Seguro de Vida; 
- Gympass; 
- Sesc; 
- Cartão Multibenefícios Alelo – (com desconto na compra de diversos itens na rede credenciada, incluindo medicamentos em diversas redes de farmácias); 
- Assistência Médica e Odontológica Bradesco; 
- Atualmente estamos em home office, e a empresa fornece todos os equipamentos necessários; 
- Política Educacional para Graduação e Pós-graduação; 
- Programa eu Saudável (Acompanhamento de saúde e bem-estar); 
- Programa Primeiros Laços (Acompanhamento Gestacional); 
- Consultas médicas remotas; 
- Palestras de desenvolvimento pessoal e profissional.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Python Developer na ClearSale](https://coodesh.com/vagas/pessoa-desenvolvedora-python-pleno-100percent-remoto-174847023?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by jjpaulo2** [comment]
Olá @blankapf. Tentei submeter uma candidatura, mas o botão no site está desativo. A vaga ainda está disponível?

![image](https://user-images.githubusercontent.com/22819523/204157340-888b55a3-f360-4ed0-bff6-b914721e6388.png)
