### ISSUE TITLE
[São Paulo/SP] PHP Developer Pleno na Mypharma2Go

### ISSUE THREAD

**Issue by wbianchini** [backend-br/vagas#1044]
## [São Paulo/SP] PHP Developer Pleno na Mypharma2Go

Projeto escrito em PHP7.3 com laravel 5.7

## Local

Escritório, São Paulo/SP - Vila Olímpia

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR de R$ 25/dia
- VT com valor a combinar
- Seguro para computador

#### Diferenciais

- Espaço de coworking
- Happy hour uma vez por mês
- Autonomia

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- Experiencia com PHP orientado à objetos
- Conhecimentos em Laravel

**Desejáveis:**
- MySql
- Angular JS
- Código limpo

**Diferenciais:**
- .net C#

## Contratação

Cooperativa

## Como se candidatar

Por favor envie um email para kaio@mypharma2go.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- Cooperativa

### Experiência
- Pleno
- Sênior

**Comment by samuelfaj** [comment]
Seria possível trabalhar como PJ remoto?

**Comment by wbianchini** [comment]
> Seria possível trabalhar como PJ remoto?

Olá, td bem? Infelizmente a vaga atual seria apenas presencial mesmo.
