### ISSUE TITLE
[Remoto] Pessoa Analista de Segurança da Informação - AppSec na Tray

### ISSUE THREAD

**Issue by MoniquePaiva** [backend-br/vagas#10448]
Quem somos?

Somos a Tray, a plataforma de e-commerce da Locaweb Company que transforma vidas, experiências e negócios por meio da tecnologia. Com muito orgulho, somos reconhecidos desde 2019 como uma empresa GPTW e desde 2020 como um Lugar Incrível para Trabalhar pela FIA/FEEx. Isso é um indicador de que você veio ao lugar certo, não acha?

Dentre os nossos objetivos diários estão oferecer aos nossos colaboradores bem-estar; ambiente colaborativo, diverso e inclusivo; trabalho em equipe, paixão pelo que fazemos e a possibilidade de se desenvolverem, para entregarmos aos clientes da Tray a melhor experiência e os melhores resultados de venda em e-commerce. Nós respiramos, amamos e vivemos a tecnologia, e você?

RESPONSABILIDADES E ATRIBUIÇÕES
Como será seu dia a dia:

Implementar técnicas e procedimentos para desenvolvimento seguro e testes de segurança em aplicações e esteiras de entrega;
Atuar em conjunto com as equipes de Tecnologia na avaliação e desenvolvimento de novas soluções e controles de Segurança da Informação;
Atuar em todo fluxo de desenvolvimento (Desenvolvimento, Teste, Deploy e acompanhamento em produção), voltado ao Privacy by Design;
Implementar e executar ferramentas de SAST e DAST;
Planejar e ministrar treinamentos em Desenvolvimento Seguro;
Implementar segurança em CI/CD com a ferramenta Gitlab;
REQUISITOS E QUALIFICAÇÕES
E para tirar de letra, você precisa de:

Experiência em Segurança da Informação;
Sólidos conhecimentos sobre padrões, frameworks e boas práticas de Cibersegurança (por exemplo: OWASP);
Experiência em processos de gestão de vulnerabilidades, modelagem de ameaças, arquitetura segura e riscos cibernéticos;
Experiência na execução e implementação de ferramentas de SAST e DAST (por exemplo: OWASP ZAP, SQLMap, SonarQube, etc.);
Conhecimento em design patterns e técnicas de desenvolvimento seguro;
Conhecimentos em PHP, JavaScript, Banco de Dados, APIs Rest, GIT e Docker;
Boa capacidade de comunicação oral e escrita;

E se tiver isso também, melhor ainda:

Pós-graduação e/ou Certificações na área de Segurança da Informação, como por exemplo: ISO 27001 Foundation, CompTIA Security+, CISSP, etc;
Conhecimento em arquitetura de segurança/soluções em nuvens públicas e privadas;
Conhecimentos em Gestão de Projetos;
INFORMAÇÕES ADICIONAIS
Só quem é Tray tem:

Plano de Saúde Unimed 

Vale Refeição ou Vale Alimentação

Auxílio Creche

Programa de Participação de Lucros - PPR

Day Off no mês de aniversário

Seguro de Vida em Grupo e auxílio funeral

Plano Odontológico

Gympass

Licença maternidade de 6 meses e paternidade de 20 dias

Horário flexível

Parceria com o SESC e instituições educacionais

Programa Conexão Saúde

Para quem está no escritório:

Frutas da época todos os dias

Máquina de café, capuccino, suco de laranja e snacks

Estacionamento

Massagem

Mesas de jogos (pebolim, air game)

Onde estamos:

Ficamos em dois lugares incríveis e modernos aqui no Jardim Acapulco, bem pertinho das universidades:

Sede: Rua Alcides Lajes Magalhães, 130 - Marilia/SP

Traylab: Rua Rua José Joaquim de Oliveira, 305 - Marília/SP

### Nível
- Pleno

### Regime
- CLT

### Alocação
- Remoto

**Comment by filipesander** [comment]
Gostaria de me candidatar para vaga

**Comment by MoniquePaiva** [comment]
Olá, Boa tarde.
A vaga foi preenchida.

Abraço!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
