### ISSUE TITLE
[Híbrida/ Remoto ou Presencial - Florianópolis] Back-end developer - J&A Holding / Fontes Promotora 

### ISSUE THREAD

**Issue by jeavagas** [backend-br/vagas#10455]
## J&A Holding / Fontes Promotora

Não conhece a Fontes Promotora?

Nós somos a Maior do Mercado! Estamos pelo Brasil todo e contamos com mais de 30 filiais!

A Fontes Promotora faz parte da J&A Holding, que conta com 12 empresas em três ramos diferentes: financeiro, tecnologia e varejo!

Buscamos pessoas com muita vontade de crescimento e ambição!

Se esse também é o seu desejo, venha trabalhar em uma das empresas que mais cuida e engaja seus colaboradores.

Confira um pouquinho do nosso dia-a-dia pelo nosso perfil do instagram: https://www.instagram.com/fontespromotora/!.

## Descrição da vaga

Atuar na manutenção das APIs existentes, seja refatorando ou desenvolvendo evolutivas, para garantir o bom funcionamento das mesmas
Contribuir no desenvolvimento de novas APIs, sejam internas ou externas, como no caso de consumirmos APIs de parceiros
Saber comentar o código pensando que outras pessoas irão atuar em algum outro momento nesse seu desenvolvimento
Contribuir com a squad no qual estará inserido, seja codificando, seja estruturando um banco de dados, seja configurando algum serviço, etc, atividades que vão tirar você especificamente do código, mas vão contribuir para o seu crescimento, e consequentemente para as entregas da equipe como um todo

Principais tecnologias:

Javascript (TypeScript, Node.js, Express.js, NestJS ) e/ou Python (Django,Pandas,FastAPI, Flask)
Algum ORM, ex TypeORM, Prisma, Sequelize, SQLAlchemy, Django ORM
GIT (Github, Bitbucket, etc)
Docker (trabalhar com containers, Docker Compose, etc)
Bancos de dados relacionais (PostgreSQL, MySQL)

Outras tecnologias desejáveis (não obrigatórias):

Bancos de dados não relacionais como MongoDB
Testes automatizados, por exemplo usando Jest
Mensageria como RabbitMQ ou Kafka
Stack ELK (Elasticsearch, Logstash e Kibana)

## Local

Remoto, híbrido ou presencial em Florianópolis.

## Requisitos

Experiências desejáveis:

Escrever códigos limpos, sustentáveis e eficientes
Forte conhecimento em boas práticas de  desenvolvimento com design patterns e SOLID
Contribuir em todas as fases do ciclo de vida de desenvolvimento
Seguir as melhores práticas (desenvolvimento orientado a testes, integração contínua, refatoração e padrões de código)
Viver em um ambiente de mudanças e capacidade de aprendizagem
Impulsionar a adoção e integração contínua de novas tecnologias relevantes no desenvolvimento
Testar as aplicações para assegurar a capacidade de resposta e eficiência
Boas habilidades de  relacionamento interpessoal, visando o bom andamento da equipe
Práticas ágeis, Scrum ou Kanban

## Benefícios

Oferecemos oportunidade de crescimento interno, ações do nosso endomarketing como: Dia do doce, day off no aniversário, premiação por tempo de casa e rodas de conversa focado na saúde mental, palestras, cursos e muito mais.

## Contratação

 PJ

## Como se candidatar

Link da Sólides: https://fontesvagas.solides.jobs/vacancies/197752#vacancyDescription 
Link do Indeed: https://br.indeed.com/job/desenvolvedor-backend-pleno-ef843a3da7912676 
E-mail: [talentos@jeaholding.com.br](mailto:talentos@jeaholding.com.br) 
Via whatsapp: (48) 9164-0011

### Nível

- Pleno

### Regime

- PJ com contrato indeterminado

### Alocação

- Remoto
- Híbrido
- Presencial em Florianópolis-SC.

**Comment by Vitorrrocha** [comment]
Olá, programei o envio de um email com o meu curriculo para a vaga em questão.
