### ISSUE TITLE
[São Paulo] Back-end Developer (Laravel/PHP) no Hospital Israelita Albert Einstein

### ISSUE THREAD

**Issue by adhenrique** [backend-br/vagas#10452]
## HIAE - Ensino Einstein

Trago doces e presentes de Natal 🧑🏻‍🎄
Estamos em busca de um(a) desenvolvedor(a) Laravel/PHP para suportar, transformar e reestruturar uma das aplicações mais importantes aqui na área de Ensino do Einstein. Se você está disposto a trabalhar remoto 🗺️ , comendo pipoca 🍿 , absorvendo novos conhecimentos 💡 é só continuar lendo...

## Requisitos básicos:
- Laravel 6+ lover 🥰 (tem que AMAR mexmoooooo)
- Events
- IoC
- Parceria no momento do fogo 🔥 
- Analista de problemas (Não pode ficar com medo de pegar código legado 😋)
- Antenado(a). (Tem muitas tecnologias novas surgindo. Você poderia nos indicar uma?)
- Se vc souber responder qual a diferença entre os métodos **with()** e **load()**, já ganha um pirulito 🍭 

## Diferenciais (Como sair na frente...):
- PHP OOP 7+
- PHP Design patterns (Qual design pattern que vc mais utiliza no seu dia a dia?)
- Service/Repository pattern
- DDD
- TDD
- Docker (Chega daquela desculpinha: "na minha máquina funciona")
- 1 ano+ de experiência com desenvolvimento Laravel

Ufa... tirando tuuuuuudo isso, esperamos que vc seja uma pessoa bacana 😎. Só isso!

Agora, se tu se interessou, envie um e-mail para adenilton.ribeiro@einstein.edu.br com o assunto **Vaga Back-end**, respondendo a pergunta: Qual a ordem de precedência de uma Trait? _(essa é fácil bebê!)_

Ah, um detalhe **importante**: estamos atuando 100% remotos, mas se você conseguir visitar-nos, seria ainda mais incrível!

## Labels
- Remoto
- Pleno
- Senior
- PJ

**Comment by guligon90** [comment]
FYI: Existe um erro tipográfico em "Eistein". Deveria ser "Einstein".

**Comment by filipegarrett** [comment]
> FYI: Existe um erro tipográfico em "Eistein". Deveria ser "Einstein".

Na verdade é um erro ortográfico. Tipográfico seria algo referente ao typeface (tipo) nesses tempos digitais.

**Comment by adhenrique** [comment]
Opaaa, muito obrigado meus amigos. Acabei de corrigir ❤️

@guligon90 @filipegarrett

**Comment by guligon90** [comment]
> > FYI: Existe um erro tipográfico em "Eistein". Deveria ser "Einstein".
> 
> Na verdade é um erro ortográfico. Tipográfico seria algo referente ao typeface (tipo) nesses tempos digitais.

Obrigado pela correção ;)
