### ISSUE TITLE
[Remoto / Presencial - São Paulo] Junior/Pleno/Senior em Go / NodeJS / Ruby - Atomic Fund

### ISSUE THREAD

**Issue by herenow** [backend-br/vagas#10456]
## Nossa empresa

Operamos no mercado de crypto desde 2017. Somos uma empresa pequena, com poucos colaboradores. Nosso foco é em trading proprietário e market making para diversos clientes.

## Descrição da vaga

Vaga para full-time. Você irá trabalhar com um time pequeno, e todo o trabalho é backend. Também temos algumas interfaces em Javascript. O trabalho consiste em nos auxiliar em novas integrações com diversas bolsas de crypto e do mercado tradicional. Desenvolvimento e manutenção de estratégias existentes.

## Local

Vaga preferencialmente 100% Remota. Porém se morar em São Paulo, e preferir trabalhar conosco, no escritório, podemos analisar a possibilidade após alguns meses de estarmos trabalhando juntos.

## Requisitos

Interessante ter experiencia como uma das seguintes linguagens:
- Go
- Node
- Ruby

Interessante já ter trabalho com os seguintes stacks:
- Postgres
- RabbitMQ
- Websocket / REST
- Javascript
- AWS

## Benefícios

Compensação de R$ 8k ~ R$ 16k, a depender da experiência. 

## Contratação

PJ

## Como se candidatar

Envie um email para *leo@atomic.fund*, com o seu Github, CV (caso tenha) ou qualquer outro conteúdo que ache relevante.

## Labels

Go, NodeJS, Ruby, Remoto, PJ

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- PJ
- Freelance

### Alocação

- Remoto
- Híbrido
- Presencial

**Comment by herenow** [comment]
Vaga preenchida, obrigado a todos que se candidataram.

**Comment by herenow** [comment]
Vaga aberta novamente, para interessados em Go.

**Comment by victorbrugnolo** [comment]
Somente full-time?

**Comment by herenow** [comment]
@victorbrugnolo Caso esteja cursando algo, pode ser parte time.

**Comment by jeanlimadev** [comment]
Se abrir para Node ou qualquer outra stack javascript posta aqui por favor :)
