### ISSUE TITLE
[São Paulo/SP] Back-end PHP Developer Pleno na SupPay

### ISSUE THREAD

**Issue by MoovSystems** [backend-br/vagas#10466]
## Nossa empresa

A Sup#Pay é uma plataforma de pagamento B2B, spinoff da MinniS, startup acelerada pelo iDEXO/TOTVS, Edenred e Cielo e destaque em dois estudos da Liga Ventures. Estamos recebendo investimento, ganhando clientes e crescendo a equipe. Nosso propósito é ajudar o pequeno comerciante a ter uma relação mais justa com seus fornecedores. Nossa cultura é de entrega de resultados e não de cobrança de horários, presença física ou dresscode. Nosso site: https://suppay.com.br/ e no Linkedin: https://www.linkedin.com/company/suppay/

## Descrição da vaga

Estamos buscando um(a) desenvolvedor(a) PHP Backend Pleno para fazer parte do nosso time. Basicamente, utilizamos MySql (5.7) e PHP/Láravel. Por isso, buscamos alguém que tenha experiência e conhecimento nessas tecnologias. Estamos começando a formar a equipe, portanto, procuramos alguém disposto a crescer profissionalmente (e rápido) junto com a gente. A posição é híbrida porque acreditamos que ter alguns momentos juntos em equipe fortalece a nossa cultura.

## Local

Híbrido - Escritório, São Paulo/SP 

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- 2 anos de experiência com Láravel
- Experiencia com Banco de Dados MySql
- Experiência com Git

**Desejáveis:**
- Experiência com APIs
- Experiência com ERPs

**Diferenciais:**
- Experiência com Vue.Js
- Experiência com Docker
- Experiência com a Digital Ocean.

## Benefícios

- 2 horas de almoço
- Formato flexível: remoto e presencial
- Estrutura de coworking
- Desconto de 30% nos cursos na FIA em IA, Big Data, Analytics e todos os outros

## Contratação

PJ

## Como se candidatar

Por favor, envie um email para dev@suppay.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP Developer

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Híbrido

**Comment by MoovSystems** [comment]
Como estamos optando pelo modelo híbrido, damos preferência a devs de SP

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
