### ISSUE TITLE
HumanAZ Conectando Propósitos com Back-end developer - Firstbase 

### ISSUE THREAD

**Issue by devadrianoabner** [backend-br/vagas#10478]
## **HumanAZ :: Conectando Propósitos**

Performance-based Recruitment
https://www.humanaz.com.br/
https://www.linkedin.com/company/humanaz/

A HumanAZ é uma startup Performance-based
Recruitment é um produto analítico de recrutamento tech, dados e produtos. Humanizamos e facilitamos a conexão de propósitos entre #Techpeople e empresas, com assertividade e retenção! Absorvemos os desafios das empresas e conectamos as pessoas com seus propósitos de vida e carreira, usando dados, Machine Learning (IA) e metodologia. Alinhamos assertivamente cultura e desafios de negócios, atraindo propósitos e competências.

## Descrição da vaga

Firstbase empowers anyone to start a US business. Incorporate your company, set up banking, process payments, manage payroll, stay compliant, and more - 100% online, from a single dashboard. 
https://www.firstbase.io/
https://www.linkedin.com/company/firstbase-io/

**#Why being a Back-End Engineer @firstbase.io:**
As Back-end engineer, you play an important role in our small and nimble product team.
You will be expected to wear many hats and help make influential product decisions.
You lean toward the back-end, but consider yourself full-stack.
You will write plenty of code, but also oversee software projects.
You enjoy following good product development practices like reviewing, debugging, and testing code.
You should obsess over delivering the best customer experience to a global market of founders, ensuring simplicity and clarity.

**# @firstbase.io you will be challenged to:**
Build products & solving some of the startups’ hardest problems, with particular focus on:
Democratizing access to financial infrastructure
Automating tasks every founder faces when running a business
Making tools and resources more accessible to everyone, everywhere
Building integrated solutions for founders and removing friction
Delivering opportunities to traditionally overlooked founders and companies
Democratizing access to knowledge
Join us on a mission to increase the number of growing companies.

**# @firstbase.io you will be engaged to contribute for business development to:**
Rapidly scale the engineering org alongside product and design leaders in a high growth environment
Structure our engineering team to consistently ship high-quality work on time and on budget
Influence change and deliver sustainable technical and architectural decisions to improve efficiencies across our systems
Advocate for technical engineering excellence and guide career growth development for the engineering team
Be willing to jump in and help triage issues with the team as the need arises
Develop high-quality software design and architecture
Identify, prioritize and execute tasks in the software development life cycle
Develop tools and applications by producing clean, efficient code
Review and debug code
Collaborate with internal teams and vendors to fix and improve products
Work with product and design to define, shape, and plan deliverables
Make technical decisions following best practices
Identify and resolve technical risks to the product and business

**# @firstbase.io we are attracting competencies and experiencies as:**
Acting as back-end engineering while building products in high-growth startup
Hard-working and dedicated team player that needs little to no supervision, but enjoys working a team toward a common goal
Analytical mind with problem-solving aptitude
Self-motivated with an ability to work in the unknown
Ability to communicate technical topics to both technical and non-technical team members
Demonstrated collaboration with product managers, designers, other engineers to drive outcomes
Proficient in both oral and written English communication
Familiarity with PHP, Symfony, Vue, PostgreSQL, AWS, Redis, Vue Router, Vuex, Docker Compose, Docker, GitLab CI, Graylog, and/or Stripe is a plus

**# @firstbase.io is over stack:**
Our product is built using Golang, Python, Node.js, PHP, Symfony, Vue, PostgreSQL, and AWS. We also use Redis, Vue Router, Vuex, Docker Compose, Docker, GitLab CI, and Graylog, and some third-party API’s like Stripe. We use Slack, Clubhouse, Notion, Whimsical, Figma, and G Suite to collaborate and build together.
Mais Detalhes
 Comportamentos & Atitudes: Comprometimento, Responsabilidade, Dedicação, Agilidade, Adaptabilidade, Vulnerabilidade, Flexibilidade, Dinamicidade, Colaboração, Iniciativa, Autogestão, Pró-Atividade, Organização, Planejamento
Detalhes nos Benefícios:  PTO + birthday off We offer flexibility to allow people to relax and recharge whenever they need it. ● Build your ideal work setup We understand that how you work is extremely important, so we provide a stipend to set yourself up for success here at Firstbase. ● Health benefits Firstbase offers health insurance reimbursements to both US and international team members. ● Learning & development We provide a stipend together with resources to help people grow and develop in their careers. ● Amazing quarterly bonuses Every team member at Firstbase gets a bonus calculated based on personal KPIs and company growth.

## Local
Remoto

## Requisitos

- **Pensar a engenharia de software para a construção de produtos em arquitetura orientada a eventos com o objetivo de gerar escala e customizar a experiência ao usuário final (B2C)**
- Pensar o produto e seu desenvolvimento a partir da interação do negócio, produto, tecnologia e experiência do usuário
- Construir produtos com escalabilidade, performance, segurança e confiabilidade
- Inglês avançado: nível b2 - Abstrair regras de negócio reduzindo a complexidade tecnológica, para pensar e desenvolver o produto para o usuário
- Vivencia em empresas/startup globais/experiencias internacionais - Atuar na área de tecnologia em negócios multiculturais e dinâmicos, pensando e desenvolvendo produtos para usuários (B2C) que estão inseridos em ambientes multiculturais e dinâmicos
- Serviços financeiro - Entender de forma prática as regras de negócios e lógicas necessárias para o desenvolvimento de aplicações e sistema financeiros em negócios multiculturais e dinâmicos.
- Meios de pagamento - Pensar, desenvolver, implementar regras/negócio/produto/tecnologia(Regulação), integrar meios de pagamento em aplicações escaláveis
- Vivencia com sucesso/experiencia do usuário: B2C - Entender como construir produtos para usuários finais (B2C), a partir da experiência do próprio usuário (B2C) que estão inseridos em ambientes multiculturais e dinâmicos
- Automatizar rotinas e atividades relacionadas ao financeiro do negócio
- Conhecimento de outros frameworks nas stacks - Ser proativo e ter costume de buscar informações na comunidade dev para aprender e aplicar regras de negócios facilitadas para otimizar a performance através de outros frameworks e stacks
- Vivências e experiências construindo, consumindo e fazendo manutenção API’s REST
- Satisfação em ser programador
- Equilíbrio entre trabalho e pessoal - Entender a responsabilidade pelo negócio e como seu bem estar reflete na produtividade.
- Vivência e experiência com metodologia ágil e comunicação assíncrona
- É de extrema importância que o candidato tenha um bom conhecimento da indústria de startups
- Ter no mínimo 3 anos de vivência como dev 

Stack mandatória: Golang (ter vivências e experiências com a stack)

Bakc End stacks:
Python, Go, C, PostgreSQL, AWS

Comportamentais:

Abstração de problemas, tomada de decisão, pensamento analítico, proatividade, clean code, clareza, cooperação, senso crítico

## Contratação

 PJ 3-6K USD

## Como se candidatar

https://www.humanaz.com.br/jobs/

Linkedin dos nossos colaboradores: 
https://www.linkedin.com/in/adriano-abner-275736a7/

Canal de comunicação mais rápida:
81 99621-2554 (Adriano Abner HumanAZ)

### Nível

- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by devadrianoabner** [comment]
Fiquem a vontade para comentar e pedirem mais informações.

**Comment by Vitorrrocha** [comment]
> Fiquem a vontade para comentar e pedirem mais informações.

Olá Adriano tenho interesse na vaga te mandei uma solicitação de conexão no [linkedin](https://www.linkedin.com/in/vitorrrocha/)!

Da um olhada no meu [perfil](https://www.linkedin.com/in/vitorrrocha/) e vamos marcar uma conversa!

**Comment by devadrianoabner** [comment]
@Vitorrrocha Maravilha, já estou entrando em contato!
