### ISSUE TITLE
[São Paulo] Back-End Developer na Loggi 

### ISSUE THREAD

**Issue by brnvieira** [backend-br/vagas#105]
## Descrição da vaga

Não estamos procurando apenas um bom Dev, mas alguém responsável pelo crescimento de uma cultura técnica de excelência! Queremos alguém que possa nos ajudar a avançar para encantar nossos clientes e ser o melhor em logística urbana.

Fazendo uso da programação funcional sempre que possível, análise estática e sincronização declarativa de dados, estamos vendo um enorme ganho de produtividade e correção. 

Nossa Stack de BackEnd/DevOps inclui:
### 
# infra: Azure, AWS, Ansible, Docker, Nginx + UWsgi, HAProxy, Terraform, Kubernetes
# linguagens: Python, Go, Javascript
# frameworks: Django, Flask, Graphene, gRPC
# storage / queues: RabbitMQ, Kafka, Redshift, PostgreSQL, Redis, Influx, Prometheus
# tooling: Jenkins, Redash, Grafana, Flower
Nossa aplicação principal, o monolito gigante `loggi-web`, é feito em Python, com Django. 
Nossa API é em GraphQL (Graphene).

## Local

Escritório temporário na Vila Leopoldina (ao lado da estação).
Em alguns meses nos mudaremos para a LoggiTower, um prédio só nosso na Al. Santos, 2400.

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 510/mês
- Auxílio creche
- PLR (avaliação semestral)
- Vale de despesas de R$ 600/mês
- Atualização técnica em conferência ou curso

#### Diferenciais

- Horário flexível
- Monte a sua máquina como desejar
- Frigobar sempre cheio :P

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Python, Django, PostgreSQL.

**Desejáveis:**
- Go, Javascript
- ferramentas mencionadas da nossa stack

## Contratação

CLT

## Nossa empresa

A Loggi é uma plataforma de entregas expressas, que conecta você diretamente com um mensageiro. Basta utilizar o aplicativo em seu celular ou o site em seu computador, que rapidinho seu serviço será realizado! Não somos uma empresa de motoboys, somos uma ponte, que conecta os clientes que precisam de uma entrega rápida a um mensageiro disponível naquela região.

## Como se candidatar

Por favor candidate-se em nosso site: https://jobs.lever.co/loggi/2fd42aa8-3044-474d-b146-5230b449be9a

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno
- Sênior
- Python

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
