### ISSUE TITLE
[REMOTO] TECH LEAD Node.js/React.js- Invillia

### ISSUE THREAD

**Issue by maria-invillia** [backend-br/vagas#10509]
## Nossa empresa
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.

Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.

Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

## Descrição da vaga
Proporcionar entregas contínuas de alto valor e impacto, atuando ativamente na construção de produtos digitais; ser um profissional com perfil T (conhecimento profundo em [Node.JS](http://node.js/) e React, porém desejável abertura para conhecer outras áreas de conhecimento);

Mentoring/Coaching técnico do time de desenvolvimento;

Liderança Técnica;

Colaborar nas definições de arquitetura;

Acompanhar monitorações existentes, atuar na evolução destas e planejar ações para mitigar problemas futuros;

Auxiliar em momentos de crise dos sistemas, com foco na resolução dos problemas e no treinamento de outros membros da equipe para esse tipo de atendimento;

Interface técnica com as áreas de negócio e engenharia;

Entender o problema do cliente e propor soluções;

Ser participativo, dar opinião de forma construtiva;

Participar e conduzir reuniões técnicas do projeto;

Espírito de melhoria contínua (processo, produto, equipe e pessoal);

Disseminador de conhecimentos técnicos;

Estar em sintonia aos interesses dos projetos e empresa.

## Local
REMOTO

## Requisitos
Conhecimento Avançado em:

·        Linguagem (Typescript e Javascript)

·        Framework Web (Node, Express, Nest, etc)

·        Framework Front-end ([React.js](http://react.js/))

·        Arquitetura de Microserviços

·        SQL (Oracle)

·        NoSQL (MongoDB)

·        HTDB (Redis)

·        Mensageria (Kafka)

·        APIs (Restful, Swagger)

·        Testes Automatizados

·        CI/CD (Azure Pipelines, Azure Repos, Jfrog, Azure Registry)

·        Docker e Kubernetes

·        Qualidade and Secure (Sonarqube)

·        Cloud Computing (Azure, AWS ou GCP)

Tempo de experiência: +5 anos

Inglês: Avançado

## Como se candidatar
Envie um e-mail para selecao@invillia.com com o assunto "Vaga Tech Lead - GitHub"

### Nível
- Especialista

### Regime
- CLT + benefícios

### Alocação
- Remoto

**Comment by leandroluk** [comment]
Pena que pede inglês avançado
