### ISSUE TITLE
[Brusque - Santa Catarina] Back-End Developer na Hibrido

### ISSUE THREAD

**Issue by SamaraHeil** [backend-br/vagas#1051]
## Descrição da vaga

Autonomia e responsabilidade para liderar projetos de desenvolvimento de e-commerce;
Aprimorar projetos já desenvolvidos.

## Local

Presencial em Brusque - Santa Catarina

## Benefícios

Ambiente tranquilo e descontraído, com troca de ideias;
Horário Semi-Flexível (8 horas e meia de segunda à sexta);
Convênio FarmaSesi;
Plano de Saúde (Cooperativo);
Possibilidade de Home Office (á combinar);
Vale Alimentação;

## Requisitos

**Obrigatórios:**
Git;
MySQL;
HTML/CSS/JS;
PHP.

**Desejáveis:**
Conhecimento em Magento 1 e 2;

**Diferenciais:**
Composer;
Servidores Linux;
Inglês para leitura médio/avançado;

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A Híbrido, localizada na cidade de Brusque (SC), uma empresa certificada GPTW, trabalha com soluções para e-commerce. Na área de implementação de ecommerces, a Híbrido se destaca por ser **[Magento Professional](https://partners.magento.com/portal/details/partner/id/1761/back_url/aHR0cHM6Ly9wYXJ0bmVycy5tYWdlbnRvLmNvbS9wb3J0YWwvZGlyZWN0b3J5Lz9fdG9rZW49MndFZktkcks4c01WNTZGLWRiMjFXUjVvMlptWjhHcjImcGFydG5lcl9sb2NhdGlvbj1CUiZwYXJ0bmVyX3JlZ2lvbj1sYXRpbl9hbWVyaWNhJnBhcnRuZXJfdHlwZT0x)**, o que traz a segurança de uma das plataformas mais utilizadas no mundo para seus clientes. 

## Como se candidatar

Por favor envie um email para samara@hibrido.com.br com seu CV anexado 

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno
- Sênior

**Comment by donaukinder** [comment]
Qual a disponibilidade para remoto ?  Tenho interesse, vou enviar meu currículo
