### ISSUE TITLE
[REMOTO] .NET Back-end developer - DQR TECH 

### ISSUE THREAD

**Issue by carolinetech** [backend-br/vagas#10528]
## O QUE ESPERAMOS QUE VOCÊ SAIBA:

Experiência em projetos de desenvolvimento de software utilizando .NET Core
Experiência em serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS
Execução de testes unitários;
Metodologia ágil.

## DE ONDE VOCÊ VAI TRABALHAR?
No melhor lugar, onde você se sentir confortável atuação será remota e CLT com benefícios atrativos. 🤑

## O QUE SERIA LEGAL SE VOCÊ SOUBESSE:
Ter atuado no setor financeiro
Experiência em modelagem de dados em DDD;
Conhecimento em Arquitetura de Microsserviços;

## QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Liderança, habilidades de comunicação, boa didática, iniciativa.
## Como se candidatar

Informe os canais disponíveis para a aplicação na vaga.

### Nível
- Pleno
- Sênior

## Como se candidatar ? 
Link da oportunidade: https://lnkd.in/dj4nqVsG**

**Comment by gsabreudev** [comment]
Vem ser DQR!!! 🚀🚀🚀

**Comment by DaianeMFirmiano** [comment]
Ótima oportunidade!!!

**Comment by DaianeMFirmiano** [comment]
VEM pra DQR TECH!!
