### ISSUE TITLE
[Alocação REMOTO OU HÍBRIDO] Back-end developer [JAVA] - @dqrtech

### ISSUE THREAD

**Issue by gsabreudev** [backend-br/vagas#10530]
## Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Nosso site de vagas: https://dqrtech.com.br/pt-br/dqrcarreiras/

DE ONDE VOCÊ VAI TRABALHAR?
Você pode atuar de onde você preferir e caso você seja de SP, pode ir no cliente 2x ou 3x na semana!

O QUE NOS MOVE?
Tecnologia e vontade de evoluir! E é por isso que buscamos os melhores profissionais para atender ao nosso cliente da área financeira.

SUAS ATIVIDADES SERÃO?
Alguns dos projetos na área de seguros –

## O QUE ESPERAMOS QUE VOCÊ TENHA?
Java 11+;
Spring  Framework;
Arquitetura de Microsserviços;
AWS (SNS, SQS, API Gateway);
Mensageria.

## O QUE SERIA LEGAL SE VOCÊ TIVESSE?
Quarkus framework (programação reativa) e noção de arquitetura.

SOFT-KILLS ESPERADAS?
Comprometimento; Foco no cliente;
Perfil Proativo; perfil proativo, colaborativo, comunicação e autonomia.

O QUE OFERECEMOS PARA VOCÊ?
Vale Refeição/Alimentação (Cartão CAJU);
Assistência Médica e Odontológica sem coparticipação;
Seguro de Vida;
Auxílio-creche;
Aqui a sua indicação vale premiação;
No mês do seu aniversário você recebe mimos;
Material para você desempenhar as suas atividades;
Horário-flexível (conforme o cliente);
Contrato CLT (40 hrs semanais).

## VALORES da vaga: de 8k a 13k CLT + os benefícios!! (todos perfis são avaliados conforme skills técnicas e comportamentais para assim ser feito uma negociação)

Trabalhamos sempre transparência e agilidade na parte de valores! 🧡🖤🚀

**Comment by gsabreudev** [comment]
[https://dqrtech.com.br/pt-br/dqrcarreiras/](url)

**Comment by DaianeMFirmiano** [comment]
ÓTIMA oportunidade!!!

**Comment by kerol-barros** [comment]
#vempraDQRTech 🧡🖤
