### ISSUE TITLE
[Remoto] Developer Junior Back-end Javascript @ Port Louis

### ISSUE THREAD

**Issue by eduardonoronha** [backend-br/vagas#10533]
## Nossa empresa
A Port Louis possui soluções de RPA para tarefas de contabilidade e financeiras. O nosso stack é composto por um front de vue, e o back em node + net core, ambos rodando em AWS.

## Descrição da vaga
Procuramos um dev júnior para crescer junto com a empresa. A atuação inicial será na resolução de bugs e desenvolvimento de pequenos features.

## Local
Remoto ou São Paulo - Jardins.

## Requisitos
_Obrigatórios:_
- Conhecimento de javascript vanila
- Conhecimento de node e as bibliotecas mais comuns
- Vontade e disposição para aprender e se desenvolver

_Desejáveis:_
- Conhecimento de banco de dados mysql
- Conhecimento de ferramentas aws - lambda, s3, ...

## Benefícios
Salário compatível com a posição
VR

## Contratação
CLT

## Como se candidatar
Por favor envie um email para eduardo@portlouis.inf.br com seu CV anexado - enviar no assunto: Vaga BackEnd Javascript

## Labels
Alocação
Presencial
Remoto
Experiência
Júnior
Regime
CLT

**Comment by JNamasaki** [comment]
Essa posição é remota ou presencial? não ficou claro para mim

**Comment by eduardonoronha** [comment]
Remota

**Comment by Gabriel5748** [comment]
Quanto tempo dps de enviar o email devemos esperar até a resposta ?

**Comment by RobertoCabralCRCN** [comment]
CV enviado

**Comment by eduardonoronha** [comment]
Oi, Gabriel. O nosso prazo de resposta é de uma semana, mas neste processo
estamos com algumas dificuldades, poderá demorar até 4 semanas. Peço
desculpas pelo inconveniente.

Em sex., 13 de jan. de 2023 às 02:39, Gabriel5748 ***@***.***>
escreveu:

**Comment by LucasCavalei** [comment]
Currículo Enviado!

**Comment by guidani** [comment]
Enviado.

**Comment by felipe-sforcini** [comment]
Currículo enviado!

**Comment by HSfigueiredo** [comment]
Enviado!

**Comment by damaresss** [comment]
Currículo enviado!

**Comment by lorransantos** [comment]
CV Enviado!

**Comment by joao003** [comment]
Currículo enviado!

**Comment by racalixta** [comment]
Currículo enviado

**Comment by eneipereira** [comment]
CV enviado!

**Comment by lucasbarreto-dev** [comment]
Currículo enviado!

**Comment by gabrielbrasilmachado** [comment]
CV enviado!

**Comment by weillercarvalho** [comment]
CV encaminhado!

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by Rafaelrs21** [comment]
CV enviado

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by taciodev** [comment]
Acabei de enviar meu CV.

**Comment by Mateuslll** [comment]
CV enviado!

**Comment by ViniciusDuarte17** [comment]
CV enviado!

**Comment by jeandossantos** [comment]
CV enviado!

**Comment by Holiv** [comment]
Vaga de Dezembro. Será que essa vaga ainda está aberta?
Como tem sempre alguem comentando o Bot não a desativa, mas a pessoas responsável também não se pronuncia.

**Comment by YrllanBrandao** [comment]
ainda está disponível?

**Comment by eduardonoronha** [comment]
> ainda está disponível?

Não, a vaga foi preenchida. Estou encerrando o issue.

**Comment by eduardonoronha** [comment]
> Vaga de Dezembro. Será que essa vaga ainda está aberta? Como tem sempre alguem comentando o Bot não a desativa, mas a pessoas responsável também não se pronuncia.

Desculpa, não tinha visto a mensagem. Acabei de encerrar o issue.
