### ISSUE TITLE
[Remoto] NodeJS ou GoLang na Gallica

### ISSUE THREAD

**Issue by marciowinicius** [backend-br/vagas#1055]
Descrição da vaga
O profissional irá trabalhar diretamente na criação de um novo produto baseado em transações financeiras, sejam elas em moedas USD ou BRL ou EUR ou Crypto Moedas.

Com quem você irá trabalhar:
Irá fazer parte de uma equipe multidisciplinar, que dominam várias tecnologias e também gostam de bastantes desafios.

Em geral, os times aqui têm uma pessoa tech leader, que orienta e mentora as demais pessoas em questões técnicas; uma pessoa team leader, que é responsável por acompanhar entregas e direcionar o desenvolvimento de carreira das pessoas; e um(a) PM, que passa as demandas para desenvolvimento conforme a estratégia macro dos produtos. Todas essas pessoas têm background técnico!

Além disso, utilizamos métodos ágeis como Scrum, Kanban e XP. Somos adeptos a TDD (test-driven development).

Local
Remoto
Trabalhe de onde quiser

Requisitos
* NodeJS ou GoLang
* Banco de dados NoSQL e SQL
* Frameworks NodeJS(Adonis ou Express)
* Experiência em Blockchain
* API's Restfull
* Documentação
* Tests Unitários

Contratação
PJ a combinar

Como se candidatar
Email para vagas@gallica.io incluindo pretensão salarial e currículo com o assunto "Desenvolvedor Blockchain"

**Comment by jhefflg** [comment]
Gostei bastante da vaga, e converge bem com o que estudo e até projeto pessoal.
Sou um admirador de cripto moedas e estou estudando Blockchain usando a plataforma hyperledger a algumas semanas.

Envie email já.
