### ISSUE TITLE
[Remoto] Back-end Pleno (PHP e NodeJS) - Na Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [backend-br/vagas#10561]
## Nossa empresa

Somos um grupo focado em tecnologia e educação. Temos a missão de criar ferramentas inovadoras, afim de contribuir com o mercado de Dropshipping e educação!

## Descrição da vaga

-Criar aplicativos em versão Web;
-Prestar suporte e manutenção aos nossos produtos;
-Participar de Interações com todo time;

## Local

Home office (Remoto).

## Requisitos
Habituado(a) a trabalhar com micro-serviços e assincronicidade de chamadas. Integração e depuração de sistemas complexos.

- PHP;
-CodeIgniter;
-Laravel;
-NodeJS;
-Api's Rest;
-Mysql;
-Redis;
AWS S3;

## Benefícios

-Bônus de natal
-Bônus de férias
-Aula de idiomas
-Participação de lucros (PL)

## Contratação

Contratação PJ.

## Como se candidatar

Encaminhe um e-mail com título "Vaga Back ", contendo currículo e portfólio para o e-mail serena@empreender.com.br. 

### Nível

-Júnior 
- Pleno

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by serenarhempreender** [comment]
vaga ativa!

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by moisesfelix** [comment]
Enviado 🚀

**Comment by Mateuslll** [comment]
Enviado !

**Comment by damaresss** [comment]
cv enviado!
