### ISSUE TITLE
[Remoto] BackEnd .NET Core Júnior/Pleno na @ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [backend-br/vagas#10560]
> Vaga Remota 

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

100% Remoto - Full time horário comercial

## Requisitos

**Obrigatórios:**

Possuir experiência profissional em projetos com desenvolvimento .NET Core e Microservices. 
Conhecimento em ambiente Cloud e banco de dados.

## Atividades

Efetuar análise de incidentes e propondo soluções táticas para os mesmos;
Corrigir problemas relacionados à sistema de resseguro custom criado in-house pelo cliente. 

## Contratação

PJ (empresa aberta) ou CLT
6 meses, renováveis 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu CV anexado e pretensão salarial CLT ou PJ - enviar no assunto: Vaga .NET Core JR/PL

## Labels
Remoto
.NET Core
Microsservices
Cloud

## Regime
PJ
CLT

## Nível
Júnior/Pleno

**Comment by peulearning** [comment]
Enviado !

**Comment by ITeam-oportunidades** [comment]
Infelizmente a vaga foi cancelada.
