### ISSUE TITLE
[Porto Alegre - RS] Backend Developer na Superplayer & Co

### ISSUE THREAD

**Issue by robsondealmeida** [backend-br/vagas#1057]
## Descrição da vaga

Oi pessoal,

Estamos abrindo uma posição para Web/Backend Developer no Superplayer & Co. Buscamos alguém que seja apaixonado(a) por aprender, _codar_ e que goste de pensar no produto além das linhas de código.

Esta pessoa será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades nos diversos serviços, componentes e aplicações que compõem o backend e frontend dos nossos produtos. Vai trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. 🙂
<br/>

## Responsabilidades

- Pensar, contribuir no planejamento e desenvolver novas funcionalidades para as aplicações e serviços que compõem os produtos desenvolvidos pela Superplayer & Co.
- Utilizar as melhores práticas e tecnologias para escrever código em JavaScript (Node.js) ou C# (.NET).
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos em nossos produtos e cuidar para que eles nunca cheguem em ambiente de produção.
- Definir, junto com todo o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.
<br/>

## Requisitos

- Paixão em escrever código, principalmente para a plataforma Node.js.
- Formação ou cursando alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 é 0 e vai 1.
- Vivência com desenvolvimento de aplicações web.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- ♡ Git.
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.
<br/>

## Bônus (se você tiver, melhor, se não, tudo bem também)

- Vivência com mais de uma linguagem de programação (de preferência em diferentes plataformas).
- Gostar de resolver as coisas direto no Terminal.
- Conhecer ou ter vivência profissional com serviços de Cloud Computing como AWS, Google Cloud Platform ou Windows Azure.
- Experiência em escrever testes unitários, de integração e funcionais.
- Alguma vivência ou já ter "brincado" com Docker e/ou Kubernetes.
- Saber o que é Lean Startup e porque isso é importante mesmo sendo um desenvolvedor.
- Paixão por aprender e empreender.
- Tocar algum instrumento ou cantar como um rouxinol. 🐦
<br/>

## Local

Porto Alegre, RS
<br/>

## Como se candidatar

Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para jointheband@superplayer.co com o assunto Backend Developer.

## Labels
- CLT
- Javascript
- NodeJS
- GraphQL
- Electron
- MongoDB
- Elasticsearch
- Kubernetes
- Docker

**Comment by guilhermeoa07** [comment]
Vaga para Júnior? Entrevista pode ser remota?

**Comment by Rodd331** [comment]
Enviei meu curriculo..

**Comment by guilhermeoa07** [comment]
Ainda em aberto? processo seletivo pode ser remoto?

**Comment by Rodd331** [comment]
Ola Guilherme, ainda esta em aberto me envie seu curriculo porfavor, se atender os requisitos podemos fazer a entrevista remoto.

________________________________
De: Guilherme Oliveira <notifications@github.com>
Enviado: domingo, 19 de maio de 2019 19:00
Para: backend-br/vagas
Cc: Rodrigo; Comment
Assunto: Re: [backend-br/vagas] [Porto Alegre - RS] Backend Developer na Superplayer & Co (#1057)


Ainda em aberto? processo seletivo pode ser remoto?
