### ISSUE TITLE
[Remoto] Tech Manager na [Sanar]

### ISSUE THREAD

**Issue by isabelrlj** [backend-br/vagas#10586]
## Nossa empresa

Você será líder de um conjunto de squads multidisciplinares e trabalhará diretamente na construção de produtos voltados para os médicos ou estudantes de medicina, com o objetivo de empoderar os atuais e futuros médicos do Brasil.

Estamos em um momento importante de transformação nos nossos times de tecnologia, migrando para uma estrutura em que os times são donos ponta-a-ponta de domínios que impactam diferentes produtos que servem equipes internas e nossos usuários finais. 

Esse é um momento-chave onde vamos avaliar o que já foi construído até aqui, identificar pontos de melhoria e novas oportunidades e construir roadmaps para os próximos anos. 

Inovação, qualidade e escalabilidade são cruciais para o nosso crescimento e são o fio condutor da nossa estratégia enquanto equipe de engenharia. Estamos construindo uma base tecnológica que vai alavancar o crescimento acelerado da Sanar nos próximos anos.

Temos diversidade como um pilar da nossa cultura. Pessoas candidatas são consideradas para nossas vagas, sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência ou idade.

## Descrição da vaga

- Liderar pessoas desenvolvedoras que atuam diretamente em diferentes domínios utilizados pelos produtos da Sanar: pagamentos, identidade, compras e backoffice;
- Gerir, direcionar e mentorear pessoas de engenharia para que eles tenham um impacto positivo na organização além de crescimento em suas carreiras;
- Atuar ativamente com produto e design no planejamento e priorização garantindo aderência à estratégia de engenharia e alinhamento entre os diferentes squads;
- Guiar as decisões técnicas dos times, a partir de um profundo conhecimento das tecnologias e sistemas, garantindo diligência, pragmatismo e alinhamento com os objetivos estratégicos da empresa;
- Garantir que sua equipe esteja entregando com boa qualidade e consistência, dentro do time;
- Identificar oportunidades e desafios transversais aos diferentes times garantindo colaboração entre líderes e pessoas desenvolvedoras.
- Prover feedback contínuo e intencional para seus liderados, reconhecendo suas fortalezas e guiando a construção e execução de planos de desenvolvimento;
- Fazer as perguntas certas para conduzir as equipes para as melhores decisões considerando tradeoffs técnicos e de negócio;
- Atuar diretamente com as pessoas desenvolvedoras e seus pares de produto e design apoiando-os na priorização, removendo bloqueios e alinhando com stakeholders;
- Identificar pontos de melhoria em diferentes esferas (técnicas, priorização, execução, etc) e mobilizar liderados e pares para garantir a melhoria contínua da organização.

📶 Para entender o nível de senioridade da vaga (M1), pode ver as competências esperadas no [nosso frame de carreira.](https://www.sanarmed.com/carreiras/nossacarreira/)

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Possui experiência trabalhando em ambientes colaborativos entre Engenharia, Produto e Design
- Possui experiência liderando pessoas desenvolvedoras;
- Possui experiência com arquitetura e desenvolvimento em projetos de grande escala, idealmente também com experiência como desenvolvedora;
- Possui experiência contratando e desenvolvendo novas pessoas através de recrutamento, gestão de performance e planos de desenvolvimento;
- Tem conhecimento de negócio e capacidade de identificar, priorizar e direcionar os times de tecnologia na resolução de problemas de alto impacto;
- Possui foco em execução, viés para ação, e navega bem através de ambiguidades;
- Tem a capacidade de pensar e planejar tanto no curto quanto no longo prazo.

Observação importante: não é necessário conhecimento prévio em todas nossas ferramentas internas. Descrevemos o que é requisito da posição em “estamos buscando uma pessoa que…”.

**Diferencial:**
- Possuir experiência com a nossa stack (Node.js, React, React Native, Typescript, Styled Components, GraphQL)

## Benefícios

- VA de R$38,00/dia via cartão de crédito flexível (Caju)
- Auxilio Home-Office de R$300,00/mês  
- Plano de saúde Amil
- Plano odontológico Porto Seguro
- Gympass
- Zenklub - 4 sessões de 30min de terapia online por mês
- Licença Maternidade e Paternidade estendida;

**Diferenciais:**

- Equipamentos necessários para realizar o seu trabalho;
- Parcerias com descontos para seu desenvolvimento (Open English, FIAP e Escola Politécnica da USP);
- Parceria com linhas de crédito consignadas;
- Flexibilidade para trabalhar de onde você quiser;
- Quartas-feiras sem reuniões; 
- Short Friday - Nas sextas-feiras trabalhamos até às 16:30h;
- Folga no dia do seu aniversário.

## Contratação

CLT 

## Como se candidatar

Se inscreva através do link: [Tech Manager](https://sanar.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjM5MjUzNDB9?jobBoardSource=gupy_public_page)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada etapa.
E-mail para contato em caso de não haver resposta: isabel.jatoba@sanar.com

## Remuneração

14-16k

#### Categoria

- Engineer
- Tech Manager
- Backend
- Frontend

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Especialista
- Gestão

**Comment by danielsidev** [comment]
Me candidatei!
