### ISSUE TITLE
[São Paulo/SP] Pessoa Desenvolvedora Ruby 

### ISSUE THREAD

**Issue by Raffesmind** [backend-br/vagas#106]
## Descrição da vaga

Queremos duas pessoas para ajudar no desenvolvimento de nossa aplicação, uma de nível Junior ou Pleno e outra de nível Senior, para construir e melhorar nossas APIs :)

## Local

Rua Ministro Jesuino Cardoso 454 , São Paulo - Vila Olímpia
Parcial Remoto

## Benefícios

- Bônus ao ser contratado para customizar sua máquina da forma que preferir :)

#### Diferenciais

- Parcial remoto, fazemos cerimonias e outras reuniões ao vivo :)

#Jr / Pleno:
## Requisitos
- Experiência com kanban, scrum, lean, metodologias ágeis
- Controle de versão (Git, SVN e etc)
- TDD

**Desejáveis:**
- Já ter feito algo usando Elixir ou outra linguagem funcional
- Conhecimento em Graphql
- Já ter trabalhado com bancos relacionais e não relacionais

**Diferenciais:**
- projetos opensource;
- Ter aprendido e aplicado algo novo no último mês;
- Ser capaz de trabalhar de forma livre e autônoma

## Contratação
CLT

#Sênior:
## Requisitos
- Experiência com kanban, scrum, lean, metodologias ágeis
- Controle de versão (Git, SVN e etc)
- TDD
- Experiência com bancos relacionais e não relacionais

**Desejáveis:**
- Já ter feito algo usando Elixir ou outra linguagem funcional
- Conhecimento em Graphql

**Diferenciais:**
- projetos opensource;
- Ter aprendido e aplicado algo novo no último mês;
- Ser capaz de trabalhar de forma livre e autônoma

## Contratação
PJ

## Nossa empresa

 Yube quer revolucionar a forma que a pessoa é contratada nas empresas, oferecendo uma plataforma de facilidades para que o candidato faça o processo sem burocracias ou papeladas!

## Como se candidatar

Por favor envie um email para dev@yube.com.brcom seu CV ou Linkedin - enviar no assunto: Vaga Backend - [nível]
Caso tenha dúvidas, pode entrar em contato por email (rafael@yube.com.br), redes sociais, sinais de fumaça ou o que preferir :)

**Comment by reginaldojunior** [comment]
Vaga lindona :heart:

**Comment by Pedro-Souza** [comment]
@Raffesmind passa aí seu telegram/facebook ou twitter pra gente bater um papo?

**Comment by Raffesmind** [comment]
@Pedro-Souza no twitter ou telegram sou o @raffesmind também :) 
Pode me adicionar para conversar por lá

**Comment by umamaistempo** [comment]
Curiosidade: `Já ter feito algo usando Elixir ou outra linguagem funcional`

Voces estao utilizando Elixir em alguma parte do produto (ou com planos de utilizar) ?

**Comment by Raffesmind** [comment]
@mememori Estamos sim usando Elixir para montar as nossas APIs :)

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
