### ISSUE TITLE
[Curitiba - PR] Dev Node.js na Personaliza

### ISSUE THREAD

**Issue by matheus-rosin** [backend-br/vagas#1061]
## Descrição da vaga
Várias rotinas em Node.js.

## Local
Escritório, Curitiba - Juvevê

## Benefícios
A combinar

#### Obrigatórios:

- Node.js;
- MongoBD e Mongoose;
- GraphQL.

## Contratação
CLT.

## Nossa empresa
A Personaliza é uma empresa de marketing e tecnologia, e agora está entrando com mais força na área de aplicações - justamente por isso há essa vaga. Estamos nos movendo rápido e precisamos de gente para nos ajudar nisso.

## Como se candidatar
Por favor, envie um e-mail para matheus@personaliza.com.br com o que você achar interessante (mas mostrar alguma coisa favorece bastante). Enviar no assunto: Vaga Dev Back-end

**Comment by alessandroprudencio** [comment]
Ai que delicia cara .... Node js <3... aceita remoto?

**Comment by matheus-rosin** [comment]
@alessandroprudencio depende, cara... Manda e-mail que a gente vê 😄

**Comment by alessandroprudencio** [comment]
Cara estou louco para usar nodejs em projeto real, só ficar fazendo em casa
é chato...segue em anexo...


Em ter, 14 de mai de 2019 às 10:48, Matheus Rosin <notifications@github.com>
escreveu:

**Comment by matheus-rosin** [comment]
@alessandroprudencio não recebi nada aqui

**Comment by alessandroprudencio** [comment]
Ué,estranho vou reenviar...
segue em anexo....

>

**Comment by matheus-rosin** [comment]
@alessandroprudencio manda direto pelo e-mail, por gentileza

**Comment by guilhermeoa07** [comment]
Ainda em aberto? processo seletivo pode ser remoto?

**Comment by matheus-rosin** [comment]
@guilhermeoa07 opa, sim! manda e-mail lá que a gente conversa ;)

**Comment by guilhermeoa07** [comment]
Blz, enviado.

**Comment by AntLouiz** [comment]
Olá, a vaga ainda está em aberto? Tem a possibilidade do trabalho ser remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
