### ISSUE TITLE
[Remoto] Back-end developer SR - Synvia

### ISSUE THREAD

**Issue by jsantosrh** [backend-br/vagas#10623]
## Descrição da vaga

Nosso cliente é uma holding, atuante nos segmentos de saúde e tecnologia nas indústrias farmacêuticas e de diagnósticos. Com a visão voltada para inovação, investem continuamente em infraestrutura de alta tecnologia. São referência em estudos de equivalência e bioequivalência farmacêutica e em biologia molecular. Quer fazer parte desta história? Vem com a gente!

## Local

Remoto ou Híbrido - São Paulo

## Atividades

- Lidará com projetos de alta complexidade, passando por constantes validações e auditorias (ANVISA, FDA), tendo que seguir normas rígidas por conta do seguimento da saúde; 
- Ser responsável por um estagiário, acompanhá-lo, ensiná-lo e desenvolvê-lo.
- Entender a regra de negócios, segurança, banco de dados e integração de webservices e APIs;
- Estruturar, desenvolver e aplicar novas regras de negócio ao sistema;
- Controle de versão de código utilizando GIT;
- Realizar a manutenção e correção de bugs dos sistemas existentes, utilizando boas práticas de documentação de código;
- Atuar no desenvolvimento de novos projetos e propor novas tecnologias.

## Requisitos Obrigatórios

- Graduação completa em: Sistema de Informação, Ciência da computação, Análise de sistemas ou Engenharia da computação;
- Experiência sólida na área como Desenvolvedor;
- Experiência sólida nas linguagens de JavaScript, TypeScript utilizando frameworks  NodeJS e Express;

## Desejáveis

- Desejável conhecimento em frameworks de Front-End (Angular 7+ ou React);
- Desejável conhecimento em Nest.js;
- Autonomia e Liderança para trabalhar em equipe;
- Capacidade analítica e visão estratégia;
- Relacionamento interpessoal;
- Capacidade para resolver problemas.

## Benefícios

 - Plano de Saúde;
 - Plano Odontológico;
 - Seguro de Vida;
 - Convênio Farmácia;
 - VR,;
 - VT;
 - Estacionamento;
 - Day Off de Aniversário.
 - Parceria SESC

## Contratação

CLT ou PJ

## Como se candidatar

Envie um e-mail para ksouza@acelerarh.com.br com o seu currículo atualizado e coloque no assunto: Vaga Front-End SR 

### Nível
- Sênior

**Comment by Diegiwg** [comment]
Está com a label Estagiário, mas é uma vaga de Sênior.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
