### ISSUE TITLE
[Remoto] Back-end developer - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#10634]
## Desenvolvedor Java Jr/Pl

Ira atuar com desenvolvimento de novos sistemas e manutenção em sistemas já existentes. 

## Local
100% remoto 

## Requisitos
·        Java
·        Spring Framework
·       Mensageria
·        Testes integrados/unitários
·        API REST
·        Bancos de dados SQL e NoSQL
·        Metodologia ágil  
·        Experiência nas práticas de desenvolvimento de aplicações seguras, distribuídas e de alta disponibilidade.

## Contratação
PJ 

## Como se candidatar
Enviar CV atualizado para helen.matos@nexmuv.com.br 

### Nível
- Júnior
- Pleno

### Regime
- PJ

### Alocação
- Remoto

**Comment by PatrickFerreiraLima** [comment]
Enviado!

**Comment by brunodelucasbarbosa** [comment]
Email Não encontrado aqui

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
