### ISSUE TITLE
[Remoto][Pleno] Backend developer - Desosp

### ISSUE THREAD

**Issue by brenooliveira** [backend-br/vagas#10647]
Estamos buscando Desenvolvedor (a) Java Backend Pleno para se juntar à nossa equipe de desenvolvimento de software. O candidato precisará ter experiência sólida com Java, banco de dados e aplicações back-end em escalabilidade.

### Responsabilidades:

Desenvolvimento e manutenção de aplicações backend em Java;
Trabalhar em estreita colaboração com outros desenvolvedores e equipe de gerenciamento de projetos;
Participar da análise de requisitos e da concepção de soluções de software;
Implementar soluções de alta qualidade e escaláveis;
Documentar o código e os processos de desenvolvimento.

## Requisitos:

Experiência sólida com Java e aplicações backend;
Conhecimento de banco de dados relacionais e SQL;
Experiência com aplicações escaláveis e altamente disponíveis;
Conhecimento de metodologias ágeis de desenvolvimento de software;
Boa comunicação e habilidades de trabalho em equipe.

## Oferecemos:
Contratação PJ
Salário competitivo;
Ambiente de trabalho dinâmico e colaborativo;
Oportunidades de crescimento e desenvolvimento profissional.

Se você está procurando uma oportunidade emocionante em desenvolvimento de software, envie seu currículo para cv@trampodecasa.com.br ou acesse https://trampodecasa.com.br/vaga/2023-desosp-vaga-para-desenvolvedor-java-backend-pleno

**Comment by brunodelucasbarbosa** [comment]
Somente PJ?

**Comment by brunodelucasbarbosa** [comment]
Site não funciona e e-mail não encontrado
