### ISSUE TITLE
[Rio de Janeiro] Python API Senior [Órama]

### ISSUE THREAD

**Issue by ppaulojr** [backend-br/vagas#1064]
**Empresa**

A [Órama](http://www.orama.com.br) foi criada em 2011 por profissionais experientes do mercado financeiro, foi uma das pioneiras a oferecer investimento digital no Brasil. Além disso, foi premiada pela Amazon Web Services como uma das empresas mais inovadoras em serviços financeiros. 

Presente em todo o país, com uma estrutura 100% online, também está comprometida com a entrega do melhor serviço para que o brasileiro possa investir de forma consciente e transparente. 

**Vaga**

Estamos em busca de um desenvolvedor sênior Python que seja bastante proativo e focado no trabalho. Não acreditamos em pessoas trabalhando por muitas horas, mas sim em pessoas trabalhando focadas numa jornada máxima de 40 horas.

Estamos considerando a **possibilidade de trabalho remoto para a pessoa certa**.

**Requisitos**
- Python
- Algum framework (Django, Flesk, etc)
- Sólidos conhecimentos de REST API
- Capacidade de Compreensão de Problemas complexos.
- Capacidade de se adaptar rapidamente a um ambiente de produção.

**Metodologia de Trabalho**
- Agil
- Test Driven Development (TDD)
- Code Review
- 40 horas semanais – Trabalhe focado e trabalhe 40 horas.
- Possibilidade de trabalho remoto para a pessoa certa.
- Reuniões minimalistas

Envie e-mail com o subject [Python 2019 - Senior] para Pedro.junior@developers.orama.com.br

Comp extremamente competitiva.

**Comment by viniarck** [comment]
backendbr-vagas/all, ainda tem mais uma vaga aberta com estes mesmos requisitos que o ppaulojr descreveu. Continuamos procurando um(a) desenvolvedor(a) senior Pythonista para entrar no time.

**Comment by Mdslino** [comment]
Enviei o curriculo.
