### ISSUE TITLE
[100% REMOTO] Back-end developer - PERFECT FLIGHT 🛩️

### ISSUE THREAD

**Issue by pf-gente-gestao** [backend-br/vagas#10659]
## Nossa empresa

Nascemos da paixão pela agricultura e acreditamos que cada gota importa para alimentar melhor o mundo! Isso é o que nos move! 🛩️🌱

Somos a mais completa plataforma de gestão e rastreabilidade de pulverização, com atuação nacional e internacional. 
Iniciamos 2023 batendo o marco de 30 milhões de hectares monitorados, gerando um grande impacto sustentável para os produtores e para nosso planeta. O sistema Perfect Flight App gera relatórios simultâneos de análises de pulverizações, através dos arquivos LOG das aeronaves, com isso produtores e indústrias podem avaliar as pulverizações no aspecto Sustentável e de Performance.

Para conhecer mais sobre a nossa empresa, acesse:
LinkedIn: https://br.linkedin.com/company/perfect-flight
Site: https://perfectflight.com.br/
Instagram: https://www.instagram.com/perfectflightapp/

## Descrição da vaga

Estamos em busca de um Desenvolvedor Backend Sênior/Pleno para fazer parte do nosso time.
Você deverá ser alguém que goste de tirar as ideias do papel de maneira autônoma, e que se sinta confortável para trabalhar com nossa stack (Node.js, Typescript, GraphQl). 
Você deverá se orgulhar do seu código, mas tendo conhecimento suficiente para saber como gerenciar trade-offs de implementação. Você deverá ter mindset de produto - engenheiros desse time também farão parte de um time de produto.

## Local

Essa posição é 100% remota, mas você terá a opção de trabalhar em nosso escritório, se quiser (São João da Boa Vista - SP).

## Requisitos

**Como será o seu dia a dia?**
Estar a frente do desenvolvimento de funcionalidades do produto, do início ao fim, incluindo definição de escopo, arquitetura, desenvolvimento de código e envio do código à produção;
Trabalhar juntamente com outras pessoas do time de produto (PMs, Designers) para idealizar soluções para problemas dos clientes;
Se tornar um expert na área do seu produto e nossa stack;
Realizar melhorias para produtividade dos desenvolvedores através criação de processos / melhorias no código;
Trabalhar em times distribuídos.

**Competências e experiência necessárias:**
Experiência para concepção de produtos web complexos, nas linguagens ou frameworks que usamos: Node, Typescript, GraphQL, NestJS, RestFul, Microserviços;
Desejo de trabalhar de maneira autônoma;
Experiência em desenvolvimento para Cloud AWS (EC2, Lambda, DynamoDB, SQS, RDS, S3, ECS);
Empatia. Você se importa com seus colegas de trabalho e nossos clientes. Você consegue se colocar no lugar deles.

_Diferenciais (Bônus):_
Experiência com manipulação de mapas com Mapbox/Leaflet e GeoJSON;
Experiência com Postgis e Geoprocessamento;
Conhecimento em Python.

## Benefícios

Horário flexível;
Aulas de Inglês in Company

## Contratação

PJ

## Como se candidatar

Se este desafio é para você, envie seu currículo com o nome da vaga no assunto para: juliane.vitielli@perfectflightapp.com
Venha participar da revolução na gestão de pulverizações!

### Nível

- Pleno
- Sênior

### Alocação

- Remoto

**Comment by brunodelucasbarbosa** [comment]
Somente PJ?
