### ISSUE TITLE
[Remoto] - Fullstack Developer - @Ourofino

### ISSUE THREAD

**Issue by lauramarquesitrecruiter** [backend-br/vagas#10662]
### **Sobre a empresa**
A Ourofino é uma empresa de origem brasileira, com pouco mais de uma década de atuação no mercado de defensivos agrícolas. Com atuação focada em inovação no agronegócio. Hoje buscam reimaginar a agricultura brasileira, desenvolvendo tecnologias e soluções adaptadas às características da agricultura tropical. Se especializando nas características exclusivas em sua agricultura Brasileira, buscando alavancar o crescimento do agronegócio nacional.

### **Descrição da vaga**
Esse desenvolvedor vai ser responsável por gerenciar melhorias, fazer o desenvolvimento, a implantação e manutenção dos sistemas da empresa, visando aí atender os objetivos do grupo, garantindo a evolução dos sistemas. Também será responsável pelo auxílio no desenvolvimento de profissionais de nível júnior. O principal papel desse profissional será analisar, avaliar, desenvolver e corrigir sistemas de informações do grupo utilizando linguagens de programação e procedimentos adequados para implantação, tendo como objetivo principal a melhoria continua dos processos e otimização de recursos.

### **Nível**
Sênior (_em torno de 4 a 5 anos de experiência como Fullstack_)

### **Local**
Modelo 100% remoto

### **Requisitos**
-> Frontend: React ou JavaScript
-> Backend: Python
-> Cloud: AWS
-> Diferencial: ferramentas de geoprocessamento, como arcGIS

### **Benefícios**
Auxílio home office - R$ 100,00 mensal
PLR - até 2 salários
Vale alimentação
Vale refeição
Convênio médico
Convênio odontológico
Seguro de vida
Convênio farmácia
Previdência privada
Gympass
Universidade corporativa com cursos livres

### **Contratação**
Regime CLT

### **Como se candidatar** 
Encaminhar e-mail para [laura.marques@landtech.net.br](mailto:laura.marques@landtech.net.br) com seu CV anexado e assunto "Desenvolvedor Ourofino".

**Comment by eddyyxxyy** [comment]
Há vagas de nível Junior?

**Comment by lauramarquesitrecruiter** [comment]
> Há vagas de nível Junior?

Olá! No momento não estamos com nenhuma vaga aberta em nível Junior, mas se quiser, pode mandar o seu CV para o email que está no post e subimos na nossa base de dados para vaga futuras!

**Comment by manuncorrea** [comment]
Há vagas de nível Pleno?
