### ISSUE TITLE
[Remoto] Back-end developer PHP - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#10668]
## Desenvolvedor PHP 

Desenvolvimento de novos sistemas e manutenção em sistemas já existentes 

## Local

100% remoto

## Requisitos
Ter experiência com PHP (linguagem principal), Foco no backend; 
Ter conhecimento com filas rabbitmq ou SQS; banco de dados relacional; testes automatizados; 
Ferramentas de monitoramento (grafana, kibana); versionamento de código utilizando GIT;
Conhecimento com nodejs;

Diferencial : Conhecimentos de  docker, conteiners, kubernetes ; esteira CI/CD, AWS, linguagem funcional e desenvolvimento de serviços em nuvem.

## Contratação
PJ

## Como se candidatar
Enviar e-mail para Helen.matos@nexmuv.com.br

### Nível
- Estagiário
- Pleno
- Sênior

### Regime
- PJ

### Alocação
- Remoto

**Comment by cleiton-lima** [comment]
Olá, boa tarde. A vaga ainda está aberta?

**Comment by Junior-Shyko** [comment]
Também gostaria de saber.
