### ISSUE TITLE
[Remote] Back-end developer Python - Totvs

### ISSUE THREAD

**Issue by Felipepirova** [backend-br/vagas#10679]
## Nossa empresa

Que tal deixar a sua marca, com muita autonomia, em um ritmo acelerado, na maior empresa de tecnologia do Brasil?

Somos apaixonados(as) em apoiar e impulsionar o trabalho dos(as) TOTVERS, clientes e fornecedores. Aqui as áreas corporativas são parte indispensável para que mais de 40 mil empresas no Brasil e no mundo sejam transformadas pela tecnologia da TOTVS.

Se você quer aprender muito, em um ambiente dinâmico e com muita gente boa, vem pra TOTVS!

#ouseetransforme
#sejaTOTVER

## Descrição da vaga

- Compreender o funcionamento das soluções de Cloud que estejam relacionadas à suas atividades e projetos, através de análise de código e/ou documentações públicas ou privadas;
- Atuar diretamente com as demais equipes de Cloud na resolução de bugs que estejam relacionadas à suas atividades;
- Garantir e elevar a qualidade de suas entregas, por meio do desenvolvimento de testes (unitários, funcionais, integração);
- Acompanhar a evolução dos serviços das nuvens públicas, privadas, dos serviços de orquestração de contêineres, dos produtos TOTVS e das tecnologias envolvidas, por meio de eventos, palestras ou documentações;
- Compartilhar conhecimento com os demais membros do time, buscando a equalização de conhecimento e a evolução da equipe como um todo;
- Garantir a implementação de soluções técnicas com excelência, considerando custo x benefício e tempo, criando componentes "cloud- native" de acordo com técnicas modernas de desenvolvimento para nuvem;
- Definir tecnologias, metodologias de desenvolvimento e padrões de codificação através da criação de documentações e guias de desenvolvimento, multiplicando o conhecimento e engajando o time na proposta;
- Influenciar no roadmap dos produtos TOTVS e/ou dos serviços de TOTVS Cloud, baseado nas demandas internas dos deployments dos produtos, através de comunicações formais como especificações, propostas ou provas de conceito;
- Construir arquiteturas dos produtos para diversas plataformas suportadas pela TOTVS, usando ferramentas e técnicas de mercados para definição de arquitetura;
- Solucionar problemas decorrentes em ambientes produtivos de maneira eficiente, reduzindo o impacto para o cliente da maneira ágil;
- Pesquisar e propor novas soluções com profundidade, através de documentos, provas de conceito ou propostas;
- Ser referência técnica e pessoal (interna e externamente) na área de atuação e tecnologias envolvidas, participando de fóruns e encontros de discussão sobre os temas relacionados.

## Local

Remoto

## Requisitos

- Experiência com Python
- Experiência com banco de dados não relacional
- Desenvolvimento de software - nível Avançado;
- Conhecimento em bancos não relacionais e relacionais - nível Avançado;
- Arquitetura de software - nível Avançado;
- Nuvens públicas - nível Intermediário;
- Orquestração de contêineres - nível Intermediário;
- Ferramentas de automação e integração contínua - nível Avançado;
- Segurança de Infraestrutura e aplicações - nível Intermediário;
- Sistema operacional - nível Avançado;
- Redes e infraestrutura - nível Avançado;
- Linguagem de programação - nível Avançado em pelo menos uma;
- Desenvolvimento seguro - nível Avançado.

## Benefícios

Antes de mostrar nossos benefícios, deixa eu já te contar uma coisa: aqui as coisas acontecem em um ritmo acima da média.

A rotina em uma empresa de tecnologia é alucinante e o aprendizado é contínuo e diário. O melhor disso é que temos autonomia para colocar esse aprendizado em prática e buscar resultados.

E se errarmos? Voltamos e consertamos rápido, até criarmos aquilo que acreditamos ser parte da transformação de cada cliente.

Isso tudo acelera o nosso crescimento e nos torna a maior empresa de tecnologia do Brasil, ditando o ritmo do mercado nos mais diversos setores, fazendo tecnologia que transforma.

Dito isso, oferecemos:
- Universidade em Rede TOTVS, uma universidade Corporativa com conteúdos e certificações gratuitos para cada TOTVER;
- Programa +Saudáveis, que cuida de cada TOTVER com assessoria e ações voltadas para o bem estar em corpo, mente e finanças pessoais;
- Programa +Vantagens, a maior rede de descontos da América Latina, exclusivos para TOTVERS;
- Programa + Cuidado, programa de apoio pessoal para TOTVERS e familiares, com orientações em diversas especialidades como: psicologia, serviço social, pet consultoria...
- Einstein Conecta, benefício de orientação médica online pelos médicos do Hospital Israelita Albert Einstein, totalmente gratuito;
- Plano de saúde e odontológico;
- Vale refeição e / ou alimentação;
- Vale transporte e fretados em algumas estações do metrô;
- Licença maternidade e paternidade estendida;
- Espaço de lactário;
- Bicicletário;
- Vestiário;
- Seguro de vida;
- Auxílio creche;
- Previdência privada;
- Escritório que estimula a criatividade e produtividade com ambientes para lanches, salas de jogos, mesas de bilhar e poltronas para relaxar;
- Gympass.

IMPORTANTE: Os benefícios podem alterar conforme a unidade e/ou adquirida TOTVS.

Nós valorizamos a diversidade e inclusão, consideramos todos os candidatos para as nossas vagas, independente de cor, raça, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência, idade, etc.
## Contratação

Informe o tipo de contratação, CLT, PJ ou outra.

## Como se candidatar

Você pode encaminhar seu CV ou LINKEDIN para leonardo.pierrotti@totvs.com.br ou se candidatar diretamente na vaga https://www.linkedin.com/jobs/view/3457769135/

### Nível

- Especialista

### Regime

- CLT

### Alocação

- Remoto

**Comment by Diegiwg** [comment]
Nossa, muito interessante a vaga, infelizmente, necessita de conhecimento `avançado`, mas gostei muito.
