### ISSUE TITLE
[Hibrido / São Paulo, São Paulo, Brazil] Java Spring Boot Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#10686]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/java-spring-boot-developer-162722151?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Safeway</strong> está buscando <strong><ins>Java/Spring Boot Developer</ins></strong><strong> </strong>para compor seu time!</p>
<p>Imagine um futuro onde os processos são digitais, a tecnologia sendo sua aliada e simplificando sua vida. Pois bem, o futuro começou! Ousamos ser diferentes desde o nosso primeiro dia. Reinventando a forma de lidar com dinheiro, totalmente transparente. Aqui você é o protagonista, sem pegadinhas.</p>
<p>Somos uma gestora financeira que te permite receber e pagar de forma prática e segura. Desconstruímos complexidade, burocracias e aquele jeito antigo de lidar com dinheiro. Na SafeWay, você terá sua própria carteira e poderá fazer transferências para os sites credenciados de uma maneira simples e rápida!</p>
<p><strong><em>Bem-vindos a SafeWay!</em></strong></p>

## SafeWay: 
 <p>Imagine um futuro onde os processos são digitais, a tecnologia sendo sua aliada e simplificando sua vida. Pois bem, o futuro começou! Ousamos ser diferentes desde o nosso primeiro dia. Reinventando a forma de lidar com dinheiro, totalmente transparente. Aqui você é o protagonista, sem pegadinhas. Somos uma gestora financeira que te permite receber e pagar de forma prática e segura. Desconstruímos complexidade, burocracias e aquele jeito antigo de lidar com dinheiro.</p>
</p>

 ## Habilidades: 
 - Java 
- Spring Boot 
- PostgreSQL 
- Rest
## Local: 
 São Paulo, São Paulo, Brazil
## Requisitos: 
 - Experiência profissional na área de Programação e Tecnologia da Informação; 
- Ensino Superior completo ou cursando; 
- Programação Orientada a Objetos; 
- Importante conhecer as diferentes dimensões de tamanho dos mais diversos dispositivos tecnológicos; 
- Conhecimento em Java e no Framework Spring Boot; 
- Bancos de dados relacionais Postgres; 
- Arquitetura de sistema REST.
## Diferenciais: 
 - Conhecimento em OAuth, Kafka (ou algum serviço de mensageira) e Docker; 
- Conhecimento básico relacionado a soluções de meios de pagamento e serviços financeiros.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Java Spring Boot Developer na SafeWay](https://coodesh.com/vagas/java-spring-boot-developer-162722151?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Back-End

**Comment by micaelparadox** [comment]
Dale
