### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack

### ISSUE THREAD

**Issue by rafaortega69** [backend-br/vagas#107]
## Descrição da vaga

Agência busca novo integrante para sua equipe de desenvolvimento web.
Requisitos
- Conhecimento avançados em HTML / CSS / jQuery
- Conhecimento avançado em PHP
- Experiência com sistemas CMS
- Experiência com MAC
- Conhecimento em Bitbucket, Github... 

Desejável
- Experiência com framework Laravel e/ou similares

## Local

R. Padre Chico, 221, Cj 420, São Paulo - Pompéia

## Benefícios

- VR
- VT

#### Diferenciais

- 1h30 horas de almoço

## Contratação
CLT

## Nossa empresa

Agência digital com clientes no segmento de Incorporadoras e Construtoras.

## Como se candidatar

Por favor se candidatar através do link: https://trampos.co/oportunidades/137051?lc=d1up

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
