### ISSUE TITLE
Senior Java Developer - ProV International

### ISSUE THREAD

**Issue by RaissaBalttazar** [backend-br/vagas#10708]
Somos uma empresa Global de consultoria tecnológica premiada, especializada em estratégia de TI, implementação, gerenciamento e otimização! Estamos com uma posição aberta de Sênior Java Developer, e buscamos uma pessoa com ampla experiência na área de desenvolvimento.

Projeto para atuar em um cliente no setor financeiro. O cliente é uma fintech dinamarquesa, que fornece serviços para as principais instituições financeiras do mundo. O candidato selecionado se tornará um membro da squad de desenvolvimento full-stack atuando com integrações, desenvolvimento de novas funcionalidades para o cliente ou melhorias da plataforma e pipeline.

**Requisitos técnicos:**
● Kotlin, Java, Swift, Typescript e Javascript
● Git, Maven, Gradle, YARN, Spring Boot, Micronaut, Vue.js, React, Cypress, Appium, JUnit e Spock
● AWS, Docker, Kubernetes, GitHub Actions, Terraform, RabbitMQ, PostgreSQL, Kafka Job Description
● Forte experiência com JVM
● Conhecimento de APIs para iOS, Android
● Experiência com Spring Boot, Micronaut, SQL, Hibernate
● Noção de arquitetura e testes automatizados
● Graduação completa

**Imprescindível:**
● Vasta experiência de atuação com Java Backend
● Inglês fluente

● Espanhol desejável

**Venha fazer parte do time! Envie seu currículo com pretensão salarial para brazil.jobs@provintl.com**

**Comment by ghost** [comment]
Tem vaga pra WebDev Full Stack Jr?

**Comment by RaissaBalttazar** [comment]
> Tem vaga pra WebDev Full Stack Jr?

Nesse momento não temos 🙂
