### ISSUE TITLE
PHP e/ou JavaScript Back-end developer - EANP

### ISSUE THREAD

**Issue by milton-alvarenga** [backend-br/vagas#10701]
## Nossa empresa

Venha balancear crescimento na carreira com muito tempo livre.

Gostamos de trabalhar duro, mas ao mesmo tempo, ter um bom tempo livre para relaxar e ficar com as pessoas que amamos.
Para isto, mesmo trabalhando para clientes de diversos paises, costumamos ter nossos dias de feriados e folgas no padrão brasileiro.

E mais, costumamos emendar feriados de terça e quinta em todos os projetos que estão com entrega em dia. E costumamos sempre estar em dias em todos os projetos.

Além disto, tiramos férias no final/início de ano de modo a podermos aproveitar o máximo deste período incrível. Em geral 2 semanas no final de dezembro e 2 semanas no início de janeiro.

## Descrição da vaga

Atuamos na sustentação e criação de diversos projetos para diversos clientes em diversas áreas. 

O desenvolvedor terá a oportunidade de atuar em vários projetos diferentes de diversas empresas clientes, ao mesmo tempo que terá grandes oportunidades de crescimento de acordo com seu domínio e produtividade em atender as demandas existentes.

PHP ou Javascript são nossas ferramentas principais para atender as necessidades de nossos clientes. Domínio de SQL será o suficiente para se dar bem com todas as opções de bancos de dados que utilizamos

## Local

Remoto - Horário de atuação definido pelo desenvolvedor.

Temos clientes em vários timezones diferentes, mas o foco é timezone América.

## Requisitos

* Fulltime position
* Long term position. Entrar como pleno e pensar em saltar para senior I, II, II, especialista I, II... O céu é o limite
* PHP
* Bom ter um conhecimento de Laravel e Symfony, pois vários clientes usam, mas não é obrigatório para iniciar na vaga

## Benefícios

* Salário inicial 5kBRL
* Muitas oportunidades de crescimento
* Emendamos todos os feriados de terça e quinta. (quando os projetos estão em dia e seguimos os feriados de sp/sp)
* Costumamos estar sempre com os projetos em dia
* Vários projetos de vários clientes, o que gera muita oportunidade de aprendizado
* Atuamos em várias áreas, não só programação como infra e gestão de cloud. Caso goste, é uma oportunidade de aprender e adicionar experiência ao seu cv, e claro, mais promoção interna.
* Em programação, temos projetos em várias linguagens como PHP, JS, Python e Ruby. Caso queira aprender ou praticar outra linguagem, tem possibilidade de ser alocado em outros projetos para ganhar experiência, e claro, mais promoção interna.
* Se gosta realmente de programação, o trabalho costuma ser muito divertido com os desafios e projetos que temos

## Contratação

PJ ou Freela

## Como se candidatar
https://docs.google.com/forms/d/1d_Jzoy6CNYA1q4HQMDA9a1HKv7SJuWhtLan0m5NKbeI

### Nível
- Pleno

### Regime
- PJ
- Freelance

### Alocação

- Remoto

**Comment by dasilvactu** [comment]
5k PJ pra pleno? Não acha que está muito abaixo do mercado para uma posição full time?
