### ISSUE TITLE
[Remoto e Internacional] Programador Node.js Senior na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#10709]
## Sobre

O desenvolvedor terá a tarefa de comunicar o progresso do trabalho com os stakeholders internos e externos. O sistema exclusivo da empresa faz uso de avaliações que geram insights poderosos para ajudar professores e alunos de matemática a alcançarem seus objetivos. A organização conseguiu arrecadar mais de US$20 milhões durante sua rodada de investimentos da Série A. Esta é uma excelente oportunidade para programadores brasileiros conquistarem uma vaga remota e colaborarem com uma equipe talentosa, enquanto recebem em dólar. 

## Responsabilidades:

- Desenvolver o back-end de um aplicativo que combina educação e jogos
- Trabalhar com os desenvolvedores líderes para planejar, elaborar, implementar e construir um back-end em tempo real, escalável e responsivo
- Criar um microsserviço altamente escalável e disponível, que será usado por servidores internos e clientes
- Trabalhar com uma equipe Agile, altamente colaborativa e criativa

## Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- 3 anos de experiência relevante como desenvolvedor de software
- Ampla experiência com Node.js
- Experiência com C#, SQL e .NET será uma vantagem competitiva
- Fluência em inglês, verbal e escrito

## Benefícios: 

- Emprego de alto nível nos EUA
- Crescimento profissional
- Suporte ao desenvolvedor

## Como se candidatar

Clique [aqui](http://bit.ly/3KTzVRq) para acessar o site e se candidatar

### Nível

- Sênior
- Especialista

### Regime

- Contrato

### Alocação

- Remoto

**Comment by ghost** [comment]
Tem vaga para Web Dev Full Stack Jr?
