### ISSUE TITLE
[Hibrido/São Paulo - Vila Olímpia] Fullstack Developer - V.tal 

### ISSUE THREAD

**Issue by Thamme1** [backend-br/vagas#10718]
## Nossa empresa

Nós somos a V.tal, uma empresa que nasceu com o propósito de **viabilizar a conexão com o mundo digital transformando a vida das pessoas.** Trabalhamos para ajudar a incluir o Brasil no topo da lista dos países mais digitalizados do mundo, promovendo a inclusão digital, impulsionando novos negócios e estimulando o desenvolvimento regional.

E isso é possível porque já nascemos com a maior rede de fibra ótica do Brasil com cerca de 400 mil quilômetros e temos um time que faz acontecer. Somos uma rede neutra, compartilhada com operadoras, provedores e parceiros de todos os tamanhos e regiões. E isso nos enche de orgulho. Toda essa robustez nos permite oferecer abrangência e capilaridade para os nossos clientes irem mais longe, otimizando seus investimentos.

Somos conectados, ágeis e direcionados pelo excelente resultado. **Nosso ambiente de trabalho é leve porque é formado por pessoas que colaboram entre si, confiam umas nas outras e vibram por cada conquista. Aqui nós não damos desculpas, buscamos a solução**. É com essa equipe de alta performance que trabalhamos diariamente para incluir o Brasil no topo da lista dos países mais digitalizados do mundo, promovendo a inclusão digital, o desenvolvimento econômico e social das pessoas.

## Descrição da vaga

Ser responsável por desenvolver soluções que entreguem funcionalidades estáveis em produção.
Oportunidade de **desenvolver projetos do Zero** 

## Local

Híbrido - Vila Olímpia 

## Requisitos
Prover a construção/manutenção de código dentro das práticas de desenvolvimento, aderente ao portifólio de arquitetura e framework DEVOPS;
Recomendar abordagens técnicas e de negócios alternativas para viabilizar as entregas;
Atuar na avaliação de soluções visando entregas ágeis e incrementais de soluções escaláveis e tolerantes a falhas em conjunto com especialistas;
Auxiliar colegas na verificação da viabilidade e necessidade de utilização de novas tecnologias para desenvolvimento (front e back);
CI/CD (DEV/SEC/OPS), Cloud Computing (AWS, OpenStack, Azure, Digital Ocean, OpenShift, Kubernetes, Docker, Grafana, Jaeger, etc...), repositórios SVN/GIT e Nexus;
Arquiteturas de Integração de média e alta complexidade (REST, SOAP, Webservices, WADL, XSD, WSDL, APIs CRUD e Microserviços);
Conhecimento em Open API, Swagger, Arquitetura Java EE, [Node.js](http://node.js/), Springbot, Caching;
Conhecimento da plataforma Oracle Fusion Middleware com foco em Oracle Bpel e Oracle Service Bus;
Conhecimentos em SQL e bancos de dados relacionais (DDL, DML, transações, restrições de integridade, índices, etc.);

## Benefícios

Vale Alimentação e/ou Refeição
Vale Transporte
Assistência Médica
Assistência Odontológica
Seguro de Vida
Previdência Privada
Programa de participação nos resultados (PPR)
Auxílio Farmácia
Auxílio creche
Flexibilidade de horário

## Contratação
CLT

## Como se candidatar
Encaminhar currículo com Senioridade e Remuneração para thamires.camacho@vtal.com

### Nível

- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Híbrido

**Comment by joaov1ct0r** [comment]
enviado
