### ISSUE TITLE
[Remote] Mid-Level Software Engineer (GoLang desired) - IntruderLabs

### ISSUE THREAD

**Issue by rios0rios0** [backend-br/vagas#10729]
## Our Company

About IntruderLabs: IntruderLabs is a rapidly growing cybersecurity company that specializes in offensive security. We work with many clients to help them identify vulnerabilities in their systems and improve their security posture. Our team of experienced professionals is dedicated to providing high-quality services and products that help our clients stay secure in an ever-changing threat landscape. See more [here](https://www.linkedin.com/company/intruder-labs/).

## Job description

About the Role: As a mid-level Software Engineer at IntruderLabs, you will be responsible for developing cybersecurity products that help our clients stay secure. You will work closely with our team of experienced professionals to design and implement secure, scalable, and easy-to-maintain software solutions. You will also have the opportunity to work with cutting-edge technologies such as GoLang, OpenSearch, and AWS.

Key Responsibilities:

•	Develop software solutions using Clean Architecture, Hexagonal Architecture, Clean Code, DDD, TDD, Automated Testing and SOLID principles
•	Collaborate with other team members to identify and solve complex software engineering problems
•	Write clean, well-documented code that is easy to maintain
•	Work with cutting-edge technologies such as GoLang, OpenSearch, and AWS
•	Stay up-to-date with the latest trends and best practices in software engineering and cybersecurity

## Place

Remote.

## Requirements

•	Regular knowledge of Clean Architecture, Hexagonal Architecture, Clean Code, DDD, TDD, Automated Testing and SOLID
•	Experience with at least one programming language (e.g. GoLang, Python, Java)
•	Familiarity with software development tools (e.g. Git, JIRA)
•	Experience with databases (e.g. MySQL, PostgreSQL, MongoDB)
•	Understanding of security concepts and principles
•	Strong communication and interpersonal skills
•	Ability to work effectively in a team environment
•	Strong problem-solving and analytical skills
•	Ability to adapt to new technologies and learn quickly
•	Attention to detail and ability to produce high-quality work

## Desired Skills:
•	Experience with GoLang, OpenSearch, and AWS
•	Experience in Security related fields
•	Familiarity with Docker and Kubernetes

## Benefits

It's going to be combined.

## Hiring

It's going to be combined.

## How to apply

If you are looking for an exciting opportunity to work with cutting-edge technologies and help clients stay secure, then IntruderLabs is the right place for you. We offer a dynamic and collaborative work environment, competitive salary, and benefits package, as well as opportunities for career growth and development. Apply now and join our team of cybersecurity professionals who are dedicated to making the world a safer place.

Please, send an e-mail to: `frios at intruderlabs dot com dot br` with your Linkedin and GitHub links. Set the "Software Engineer Position" as the subject.

### Level

- Full

### Regimen

- CLT
- Contract

### Allocation

- Remote

**Comment by brunodelucasbarbosa** [comment]
Este e-mail não é encontrado.
