### ISSUE TITLE
[Home Office ou Presencial] Senior Back-end Developer (Node.JS) - BR5 Benefícios

### ISSUE THREAD

**Issue by limk10** [backend-br/vagas#10739]
## Nossa empresa

Somos uma empresa de Benefícios que desenvolve soluções em Saúde, Seguros e Finanças. Temos orgulho de ser a maior empresa de Benefícios do Brasil, somos premiados Top1 no segmento pelo oitavo ano consecutivo, queremos avançar ainda mais e você pode construir coisas grandiosas conosco🤖😎

Temos projetos incríveis você irá trabalhar com inovação, com uma grande variedade de tecnologias de ponta e não temos medo de experimentar.

## Descrição da vaga

Desenvolvimento e sustentação de sistemas.
Controle de versões de código-fonte de software.

## Local

Remoto, híbrido ou presencial.

## Requisitos

Experiência com Metodologias Ágeis.
Processo de build/deployment em Clouds.
Experiência com APIs/Gateways de pagamentos.
NodeJS
MongoDB
Mongoose
SOLID
PostgreSQL
Git/Github
Docker

## Benefícios

Possibilidade de contratação CLT ou PJ
VA/VR cartão de benefícios
Seguro de Vida
Plano de Saúde Nacional
Plano Odontológico
Plano de Proteção Familiar
Férias + 13° salário
Horários flexíveis
Day off no aniversário
No dress code

## Contratação

CLT ou PJ.

## Como se candidatar

https://www.linkedin.com/jobs/view/3520807445/

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ
- CLT
- Contrato
- Freelance

### Alocação

- Remoto
- Híbrido
- Presencial

**Comment by flavrance** [comment]
O link do linkedin não aceita mais candidaturas.
