### ISSUE TITLE
[REMOTO 100%] Back-end developer PHP com Laravel - FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [backend-br/vagas#10759]
Nossa empresa

Dê uma olhada no nosso Site: http://www.fdte.org.br/
a Fundação é com foco em engenharia - ligada a Poli-USP
o nosso escritório tem o foco em engenharia de software, com modelo de fabrica de software

Requisitos
• Mínimo de 5 anos com experiencia em desenvolvimento com foco em PHP 
Framework Laravel

**Inglês Avançado/fluente (mandatório)** 
Vaga 100% Remota

Contratação
PJ 

Vantagens
Horários com certa flexíveis
Ambiente descontraído

● 80hs em banco de horas, como descanso, após 1 ano de contrato
● Possibilidade de bônus ate 2x o valor de prestação de serviços (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento pessoal
compra de livros, cursos, certificações e participação de eventos da área de tecnologia. (mediante a comprovação )

Como se candidatar
Por favor, envie um e mail para [recrutamento@fdte.io](mailto:recrutamento@fdte.io) - com seu CV anexado - enviar no assunto: Vaga PHP com Laravel

Enviar seu Cv atualizado, Github - vai nos ajudar a conhecer melhor você e o seu trabalho

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by TilsonM17** [comment]
Se não fosse o inglês, eu enviava.
Meu inglês ainda é bem básico

**Comment by micaelparadox** [comment]
Sou fluente em inglês posso enviar talvez ?
