### ISSUE TITLE
[Alocação] Back-end developer - Devellop Labs

### ISSUE THREAD

**Issue by devellop-labs** [backend-br/vagas#10765]
## Nossa empresa

A Devellop Labs é uma empresa que conecta os melhores profissionais na área de tecnologia as melhores empresas do mercado.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento web.

## Descrição da vaga

A Devellop Labs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Back-End, com clientes e projetos. Essa experiência pode ser através de projetos frellas ou trabalho empresarial.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Requisitos

**Obrigatórios:**
- Ter conhecimento em alguma linguagem server side ( PHP, Java, Phyton, Js server side ) 
- Ter conhecimento em algum framework de desenvolvimento ( Laravel, Django, Express, Ruby on Rails, Asp .NET, Spring )
- Noções de Arquitetura / Infra-estrutura
- Desenvolvimento de APis
- Versionamento ( Git e afins )

**Desejáveis:**
- Cloud / Containerização
- Testes automatizados
- CI / CD
- Experiência em trabalhar com metodologia ágeis  ( Azure Devops )

## Contratação

PJ a combinar

## Como se candidatar

Pelo link: [https://devellop.com.br/trabalhe-conosco](https://devellop.com.br/trabalhe-conosco)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by arthur-j1** [comment]
Quanto tempo de resposta para a candidatura?
