### ISSUE TITLE
[Remoto] Back-end (PHP/Javascript) pleno/senior na Melhor Rango

### ISSUE THREAD

**Issue by julianchaos** [backend-br/vagas#1077]
### Descrição da vaga
O profissional irá trabalhar na manutenção e desenvolvimento de novas funcionalidades nas api's que alimentam o sistema Melhor Rango.
.
São duas api's escritas em PHP e um set de micro services em NodeJS (Express + Hydra). O db está em MySQL.
.
### Local
O trabalho é 100% remoto. Toda a comunicação é realizada pelo Slack e appear.in. Usamos Trello para organização das tarefas e Toggl para report de horas.
.
### Requisitos
- NodeJS
- PHP
- MySQL
- API's Rest
.
### Diferenciais
- Devops
.
### Para se candidatar
Envie um email para atendimento@melhorrango.com.br com seu CV anexado e forma de cobrança (por hora, escopo, projeto fechado ou valor mensal). 
- Informações como repositórios de projetos que participou ou quaisquer outras relevantes são bem vindas!

**Comment by brunooomelo** [comment]
Jr, Pleno ou Senior?

**Comment by julianchaos** [comment]
> Jr, Pleno ou Senior?

Esqueci desse detalhe! Obrigado @brunooomelo!

**Comment by samuelfaj** [comment]
E-mail enviado!

**Comment by julianchaos** [comment]
> E-mail enviado!

@samuelfaj, a vaga já está preenchida. Atualizei a issue como fechada. Me desculpe pelo tempo gasto.

Ao grupo, a vaga foi preenchida por aqui!
