### ISSUE TITLE
[REMOTO]  Node.Js Developer - Sênior @Augmenta IT

### ISSUE THREAD

**Issue by raissaime** [backend-br/vagas#10779]
## Nossa empresa

Somos a Augmenta, uma empresa de consultoria de TI especializada em desenvolvimento de software para fornecer soluções digitais para empresas de todos os setores. Com uma equipe de profissionais experientes e tecnologia de ponta, oferecemos serviços em estratégia e consultoria, tecnologia e operações. Nosso objetivo é ajudar nossos clientes a ficar à frente da concorrência e prosperar no cenário digital atual.
Temos unidades na Europa, Ásia e América do Sul.

## Descrição da vaga

Buscamos uma Pessoa Engenheira de Software para se juntar a nós no desenvolvimento de um projeto financeiro global para uma plataforma de negociação de títulos de renda fixa.

**Qual será a sua missão?**

- Será responsável por entregar software de alta qualidade;
- Efetuar contato com gerentes de produto e designers para entender os requisitos;
- Coordenar com arquitetos de software para criar uma arquitetura de software adequada;
- Escrever código de alta qualidade e desempenho;
- Trabalhar em conjunto com engenheiros de controle de qualidade para corrigir bugs de software;
- Colaborar com engenheiros de DevOps para publicar o código para produção.

## Local

Remoto - Você irá atuar dentro do fuso horário de NYC, pois será para um projeto em uma trading/banco sediada em Nova York.

## Requisitos

- Experiência em desenvolvimento de aplicações web;
- Experiência trabalhando com Node.js e JavaScript;
- Habilidades analíticas e de resolução de problemas superiores;
- Compreensão robusta de problemas de desempenho, complexidade computacional e otimização de código;
- Familiaridade com algoritmos de software e padrões de design populares;
- Amplo conhecimento de tecnologias web;
- Graduação ou Mestrado, preferencialmente em Ciência da Computação;

**Desejáveis:**

- Interesse em implementação de UX e UI design;
- Experiência com TypeScript;
- Experiência em desenvolvimento de software que usa microsserviços orientados a eventos de Arquitetura.
- 🌎Idioma: Inglês Avançado para conversação (haverá entrevista nesse idioma e seu contato diário será com equipe fora do Brasil).

## Benefícios

✔️Horário de trabalho flexível;
✔️Seguro médico privado;
✔️Orçamento atrativo para computadores e equipamentos de escritório para o seu trabalho.

## Contratação

Contratação PJ de 1 ano, podendo ser prorrogado por mais tempo.

## Range Salarial
Informar pretensão salarial em conversão USD >> O pagamento será realizado no moeda americana - Dólar US$

## Como se candidatar

Por favor envie um email para raissaime@outlook.com com seu **CV em INGLÊS anexado** - Enviar no assunto: Vaga : Fullstack @Augmenta

### Nível
- Sênior
- Especialista

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by bolodissenoura** [comment]
Sending the e-mail ! Thanks for share .
