### ISSUE TITLE
[100% REMOTE] FullStack Developer - Machinery Partner (USA)

### ISSUE THREAD

**Issue by danihenrique** [backend-br/vagas#10797]
## Machinery Partner

Machinery Partner, based in Boston, MA, aims to build one of the largest B2B marketplaces ever created.

Starting with industrial recycling, we are redefining how small and growing industrial businesses in America finance their expansion, buy and operate large pieces of complex equipment.

Machinery Partner brings the best of the tech ecosystem to one of few opportunities that haven't been altered by the digital world - industrial businesses that make America's goods utilize large, heavy, complex equipment to run and build their products.

Machinery Partner raised $4.5M in venture capital funding in the summer of 2021 and has eleven employees.

## Descrição da vaga

Machinery Partner’s technology efforts are focused on the following key activities: 

Sourcing and acquiring customers through the development of a best-in-class digital buying experience that creates trust with the customer.
Financing solutions to automate workflows and derive risk models in order to offer the best financial product for each customer.
Service and Support aided by building a talent network for independent mechanics to support our customers and spare parts sourcing solutions.
Operations optimization by automating processes with workflows that drive efficiency in running our business. 

In this role as a Full Stack Javascript engineer, you will be building out technology in some of these areas to support the rapid growth of Machinery Partner.  You’ll be part of a cross-functional team responsible for the full software development life cycle, from conception to deployment.  You will get to solve problems rapidly, architect solutions, decide on technologies and build winning products.  

A candidate for this role should be comfortable with both front-end and back-end coding languages, development frameworks, third-party libraries, and the use of no-code. You should also be a team player with a knack for visual design and creating value for users.

Machinery Partner’s product team values deep user empathy, speed, creativity, and delivering outcomes for the business.

## Local

100% Remote.

## Requisitos

- Proven experience as a Full Stack Developer or similar role
- Knowledge of multiple front-end languages and libraries (e.g. JavaScript, React, Figma)
- Knowledge of multiple back-end technologies (e.g. Node.js, Vercel, Postgres, ..)
- Excellent communication and teamwork skills
- Great attention to detail
- An analytical mind
- A proactive problem-solving approach

## Benefícios

- Competitive salary 
- Stock options (i.e. equity) in a fast-growth startup with tremendous upside
- 100% company-aid medical, dental, and vision plans - USA only
- HSA, FSA and 401(k) - USA only
- Fun, high-energy startup environment
- Flexible PTO
- Holidays per country of residence
- No time cards

## Contratação

Contract.

## Como se candidatar

Send an email to our Engineering Lead: daniel@machinerypartner.com.

### Subject: 

- [100% REMOTE] FullStack Developer - Machinery Partner.

### Content: 

- Your Linkedin Profile up to date. 
- Why did this vacancy catch your attention?

## Labels

Node.js,  Typescript, Javascript, Postgres, Remoto, Startup.

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- Contrato

### Alocação

- Remoto

**Comment by danihenrique** [comment]
If you

**Comment by victorbiasibetti** [comment]
The vacancy is close @danihenrique ?
