### ISSUE TITLE
[REMOTO] Back-end (PHP/Phyton) developer - Going2

### ISSUE THREAD

**Issue by gabrielabenite** [backend-br/vagas#10794]
## Nossa empresa
Nossa empresa
A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

Buscamos um desenvolvedor de back-end pleno para atuar como dentro de um contrato de prazo determinado em um projeto de um cliente (alocado), assim como em projetos da Going2.
Carga horária: full-time (09h às 18h)

## Local

100% remoto

## Requisitos

- Desenvolvedor Back-End Pleno
- Experiência sólida com desenvolvimento em PHP 
- Experiência com as frameworks do PHP, como Laravel, Symfony, CodeIgniter, CakePHP, entre outros
- Conhecimento  intermediário Python
- Experiência com Job Queues and Workers (em Laravel ou similar)
- Experiência com Docker
- Banco de dados SQL e conhecer linguagem sql
- Disponibilidade para início imediato

## Contratação

PJ

## Benefícios

- Convênio Médico Sul-América (sem custo para titular)
- Convênio Odontológico Sul-América (sem custo para titular)
- Gympass
- Convênio com plataforma de idiomas (Fluency Academy)
- Day-Off de aniversário
- 15 dias de descanso remunerado
- Plano de carreira

## Como se candidatar

Enviar currículo com disponibilidade de horas, início e valor da hora para o email: gabriela.benite@going2.com.br

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by devXela** [comment]
up?

Att,

Alex Rosa Santos Barbosa
Desenvolvedor

Em qua., 5 de abr. de 2023 às 12:34, Gabriela Benite <
***@***.***> escreveu:
