### ISSUE TITLE
[São Paulo] Back-end Developer no Carteira Online

### ISSUE THREAD

**Issue by paulopaquielli** [backend-br/vagas#108]
`[São Paulo] Developer no Carteira Online`
==================================================

## Descrição da vaga

Buscamos programadores para desenvolvimento de Web Crawlers.

## Local

Remoto ou Escritório, São Paulo - Faria Lima

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript
- Ajax
- Protocolo HTTP

**Desejáveis:**
- Conhecimentos em Web Scraping
- Conhecimentos em Frameworks MVC
- Conhecimentos em Go e Node JS

## Contratação

PJ. Remuneração a combinar.

## Nossa empresa

Somos uma startup de SP que desenvolve uma plataforma de consolidação de dados financeiros.

## Como se candidatar

Por favor envie um email para paulo@carteiraonline.com.br com seu CV anexado - enviar no assunto: Vaga Crawler

## Labels

- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total
- Crawler
- Web Scraping

**Comment by Pedro-Souza** [comment]
@PauloPaquielli os crawlers são feitos em js aí?

**Comment by brunover** [comment]
Paulo, enviei um email para "vagas@carteiraonline.com.br" e informou,
"endereço inexistente".

Vi no site que há um email "contato@carteiraonline.com", então encaminhei
para ele e para "vagas@...com" (sem o ".br"). Espero que não tenha problema
:)

Em 9 de mar de 2018 8:03 PM, "Pedro Souza" <notifications@github.com>
escreveu:

**Comment by paulopaquielli** [comment]
Olá @Pedro-Souza, fizemos o nosso primeiro crawler usando o puppeteer, mas não há impedimento em relação a linguagem, nesse caso foi necessário usar o browser, infelizmente algo como o requests não funcionou :(

**Comment by paulopaquielli** [comment]
Olá @brunover, obrigado pelo interesse, pode enviar para o meu e-mail paulo@carteiraonline.com.br.

**Comment by Pedro-Souza** [comment]
Entendi @PauloPaquielli, você tem telegram/twitter/facebook pra gente poder bater um papo melhor?

**Comment by paulopaquielli** [comment]
Oi @Pedro-Souza, pode me adicionar no telegram @paulo_prad.

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
