### ISSUE TITLE
[Remoto] Back-end developer - LevoAPP

### ISSUE THREAD

**Issue by WillianSugiyama** [backend-br/vagas#10808]
## Nossa empresa

A LEVO é uma empresa de Software as a Service (SaaS) e Banking as a Service (BaaS) para operadores logísticos e entregadores de delivery que movimenta mais de R$ 137 milhões em mais de 300 cidades brasileiras.

## Descrição da vaga

Atuar como Back-end Developer no desenvolvimento de novas plataformas com NodeJS.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com NodeJS
- 3 anos de experiência com AWS
- Experiência com Typescript
- Experiência com Lambdas
- 3 anos de experiência com Banco de dados Relacionais e/ou Não relacionais.
- Experiência com Filas

**Desejáveis:**
- Conhecimentos em NestJS
- Conhecimentos de Boas Práticas, Performance e Testes.
- Conhecimento em Clean Code, Clean Architecture, POO.
- Conhecimento em Testes Unitários
- Conhecimento com CI/CD

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para willian@levoapp.com.br com seu CV anexado - enviar no assunto: Vaga Back-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: willian@levoapp.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by Holiv** [comment]
A vaga é para Back-end e ta pedindo pra enviar **Front-end** no assunto do email.

**Comment by WillianSugiyama** [comment]
> A vaga é para Back-end e ta pedindo pra enviar **Front-end** no assunto do email.

Arrumado, obrigado pela correção !
