### ISSUE TITLE
[REMOTO] Back-end developer - iHOLD BANK

### ISSUE THREAD

**Issue by janainapnv** [backend-br/vagas#10836]
##  iHOLD BANK - VAGA Back-end PHP/Laravel Pleno

O iHold Bank é uma Fintech com a missão de fazer seu papel na disrupção do sistema financeiro. 

Pequenas, médias e grandes empresas são capacitadas pela infraestrutura financeira do iHold além de estar integrado ao Open Finance o que permite a conciliação de extratos de diversas instituição financeiras e auxilia no processo de análise de credito.

Com nossa plataforma, você tem acesso a soluções, que vão desde uma conta digital completa, emissão de Pix, transferência bancária (TED), emissão de boleto, emissão de cartão de crédito pré pago, multi-contas, conta escrow e outros recursos de forma modular.

## Descrição da vaga

Desenvolvedor(a) Back-end PHP/Laravel Pleno

Requisitos:
- Conhecimentos consolidados em PHP e Laravel;
- Experiência no desenvolvimento de APIs REST;
- MySQL
- Docker
- Git

Diferenciais:
- Testes automatizados
- Jenkins

## Como se candidatar
Envie seu currículo para rh@iholdbank.digital

### Nível

- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by Emersonovidio** [comment]
enviado

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.

**Comment by ionansantos** [comment]
enviado
