### ISSUE TITLE
[Campinas] Desenvolvedor FullStack (Junior) na WIDE SOFTWARE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1084]
### Sobre a empresa: Wide Software

A Wide é um time de especialistas no desenvolvimento de aplicações WEB. Criamos softwares inovadores com as tecnologias mais avançadas que existem no mercado. Entregamos soluções modernas, seguras, de alta qualidade que são chave para o sucesso dos nosso clientes.

A Wide Software continua crescendo e a busca por excelentes profissionais é contínua! Faça parte do nosso time. Seja um Wider!

### Procuramos pessoa que:

Que preze por desenvolvimento de software de qualidade.
Seja prestativo e comunicativo com a equipe.
Busque sempre se atualizar e goste de tecnologia como nós. Aqui adoramos aprender novas tecnologias.

### Você será responsável por:

Atuar no desenvolvimento de um sistema de Telemedicina com mais de 1.500 clientes ativos e em constante crescimento.

### Você precisa ter:

Experiência com PHP e framework Symfony;
Experiência em Linux;
Conhecimento em APIs REST;
Conhecimento em TDD;
Conhecimento em bancos de dados relacionais e não relacionais.

### Será um diferencial se tiver:

Conhecimento em design patterns e clean code;
Experiência em ambientes na nuvem (AWS);
Conhecimento em virtualização e containers (desejável Docker);
Conhecimento em desenvolvimento frontend.

### A Wide oferece:

Vale refeição;
Assistência médica e odontológica;
Gympass (Convênio com academias);
Ônibus fretado ou estacionamento.

### Labels:

Alocado
Junior

### Candidatar: http://bit.ly/widefull_github

**Comment by cassioklebio** [comment]
Com eu faço para enviar meu Curriculum Vitae.!!!
