### ISSUE TITLE
[Home Office] Dev Java - BDR Talentos Corporativos

### ISSUE THREAD

**Issue by anaclaudiac** [backend-br/vagas#10855]
Onde você vai trabalhar?
Em uma empresa que há 45 anos atua na construção civil no Estado de SC e tem expandido suas operações nos últimos 12 anos para o ramo de tecnologia e postos de combustível localizada em Florianópolis. 

Que perfil buscamos para o time?
Para participar do processo seletivo, você precisa ter:
Experiência com Desenvolvimento de Sistema em Java;
Conhecimento em Spring Boot;
Conhecimento em PostgreSQL;
Conhecimento em Linux;
Conhecimento em Angular;
Conhecimento em Docker;
Conhecimento em API’s.
E seria MUITO bacana se você tiver:
Graduação em Análise e Desenvolvimento de Sistemas;
Experiência com integração de hardware;
Modelos de IA e processamento de imagens.
(mas se não tiver, pode se cadastrar mesmo assim, tá?) 

Qual será o seu desafio? 
Atuar no desenvolvimento do software da empresa, modernizando tecnologias e mapeando melhorias e novas funcionalidades

O que você precisa saber sobre essa vaga?
A vaga é para atuar de forma 100% remota. Com carga horária de segunda a sexta-feira, das 08h às 12h e 13h30 às 18h.
A proposta salarial está entre R$3.500,00 e R$4.500,00  e a empresa também oferece os benefícios de Vale Alimentação (R$27,00/dia útil) + VT + Seguro de vida + Despesas de viagens quando necessário + Frutas para lanche + Ginástica Laboral + Convênio Telemedicina + Convênio Combustível + Incentivo ao Esporte. 
Além disso, a empresa é estável e possibilita grandes chances de desenvolvimento profissional.

LINK: https://www.empresabdr.com.br/vagas?id=002433 

Para mais informações acesse o link no destaque "Vagas Abertas"!

- Pleno
- CLT
- Remoto

**Comment by Franciscoflh** [comment]
Boa tarde, como faço pra me cadastrar na vaga?

**Comment by anaclaudiac** [comment]
> Boa tarde, como faço pra me cadastrar na vaga?

Olá! Atualizado com o link para cadastro :)

**Comment by Luisfelipeqt** [comment]
enviei meu CV, espero conseguir :D

**Comment by cpcrz7** [comment]
Vaga disponível ainda? Contratação somente CLT?
