### ISSUE TITLE
[Mogi das Cruzes/SP] Desenvolvedor(a) PHP na Resource IT

### ISSUE THREAD

**Issue by LeandroRenzi** [backend-br/vagas#1086]
## Descrição da vaga

Profissional para atuar em Squad (mesa estendida) com projeto de melhoria contínua com PHP no cliente do ramo de locação de automóveis e logística.

## Local
Mogi das Cruzes - SP (próximo a estação Brás Cubas)

## Benefícios

•	Plano de saúde Sulamérica Exato Apto 
•	Convênio Odontológico - Porto Seguro
•	Seguro de vida
•	VR de R$ 440,00
•	Auxílio creche
•	Convenio Farmácia

## Requisitos

**Obrigatórios:**

•    Experiência consolidada com desenvolvimento em PHP
•    GIT
•    Facilidade para trabalho em equipe

##Desejável
Láravel

## Como se candidatar

Por favor envie um email para leandro.renzi@resourceit.com com seu CV anexado - enviar no assunto: [VAGA PHP - MC] [Seu nome completo]

## Labels
- backend
- linguagem/PHP
- experiencia/sênior
- experiencia/pleno

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno/Sênior

**Comment by LeandroRenzi** [comment]
novas vagas abertas ;)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
