### ISSUE TITLE
Desenvolvedor PHP Sênior 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [backend-br/vagas#10898]
Desenvolvedor PHP Sênior

✴️Requisitos

- O candidato deve ter habilidades de comunicação eficazes para trabalhar em equipe e se comunicar com clientes e usuários
- É necessário ter um bom conhecimento de sistemas Web em Docker e contêineres
- Experiência com Laravel como framework é essencial
- O candidato deve ter conhecimento em PHP 8.1
- É necessário ter bons conhecimentos em bancos de dados, especialmente em Postgres
- Experiência em desenvolvimento de APIs RESTful é fundamental
- É um diferencial ter conhecimento em Filament
- É bem-vindo ter conhecimento em CI/CD e Terraform (AWS)
- Experiência em controle de erros, especialmente usando Centro, é valorizada. É importante deixar a estrutura e a documentação dos erros bem organizadas e escritas.

✴️Responsabilidades

- Suporte técnico para o time: mentoria, revisão de código e aprovação de códigos
- Refatoração de códigos
- Definição de arquitetura

💰PJ 13k
🏘️Remoto 

Faça sua inscrição no link abaixo 👇🏻ou chame através do WhatsApp (19) 97816-4262 
https://app.pipefy.com/public/form/1jbzjmR_

**Comment by BrunoMoreno** [comment]
Bom dia, o link de inscrição não funciona.

**Comment by Claudiaantunesdelima** [comment]
Favor enviar o currículo para WhatsApp 19 97816-4262

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
