### ISSUE TITLE
[Internacional e Remoto] Desenvolvedor(a) Java Back-end - Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#10894]
## Sobre

Uma empresa em rápido crescimento, que está utilizando soluções de ponta para transformar completamente a indústria da cadeia de suprimentos de produtos perecíveis, está procurando contratar um Desenvolvedor Java Back-end. O desenvolvedor será responsável por garantir a entrega pontual e de qualidade dos produtos, tanto em nível individual quanto de equipe. A empresa conecta agricultores e empresas, ajudando-as a localizar e comprar produtos frescos. Ela conseguiu arrecadar mais de US$362 milhões durante sua rodada de investimentos de Série D. Esta é uma ótima vaga de trabalho online para desenvolvedores brasileiros que desejam contribuir com iniciativas inovadoras em colaboração com uma equipe talentosa e internacional.

## Responsabilidades:

- Contribuir e assumir a responsabilidade sobre todas as etapas do ciclo de vida do desenvolvimento de software
- Elaborar, implementar e manter aplicativos e soluções baseadas em Java
- Colaborar com a equipe interna para entender os requisitos do usuário e definir objetivos comerciais
- Escrever código dinâmico, bem elaborado, testável e reutilizável
- Realizar análise de software, verificação de qualidade, testes e debugging

## Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- 5 anos de experiência relevante como desenvolvedor back-end
- Conhecimento avançado sobre Java
- Experiência com SpringBoot será um ótimo diferencial
- Excelentes habilidades de comunicação em inglês

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/41r9zKY) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

### Nível

- Sênior
- Especialista

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by Mardoqueu** [comment]
Olá! Como vai? Poderia me falar um pouco sobre como funciona o processo seletivo da Turing? Eu passei em todos os testes e ainda sim a aba de jobs ficou disposnivel apenas por um curto periodo de tempo. O suporte não deu feedback via email, e não tenho acesso a lista de jobs.

![image](https://github.com/backend-br/vagas/assets/11077068/e57e60ca-681f-4529-b89c-9ac1633a33da)
