### ISSUE TITLE
[Remoto / Maringá-PR] Desenvolvedor(a) Java (Todos os níveis) [DB1 Global Software]

### ISSUE THREAD

**Issue by nathaliabruno** [backend-br/vagas#1089]
## Descrição da vaga

Diversas vagas em vários projetos para Desenvolvedor(a) Java em todos os níveis.

Para entrar em um dos nossos times, você __não precisa dominar todas as tecnologias listadas__, apenas ter um bom conhecimento nos requisitos essenciais do Java.

## Local

Remoto ou alocado em Maringá - PR

### Cesta de benefícios personalizada, com opções como:
- Vale Alimentação
- Vale Refeição
- Plano de Saúde
- Plano odontológico
- Auxílio Creche
- Auxílio Educação

#### Diferenciais

- Horário Flexível
- Dress Code casual

## Requisitos

- Java 7, 8, 9 ou 10;
- Banco de Dados: SQL, MySQL ou Oracle;
- Frameworks: Spring/Springboot, JEE, JSON, jUnit/jBoss;
- API Restfull;
- Padrão de Arquitetura: MVC;
- Sonar;
- DevOps;
- Design Patterns;
- Orientação a objetos;
- Testes unitários e de integração;
- Metodologias ágeis.

**Desejáveis:**
- Conhecimentos em JHipster;
- Conhecimentos na Stack Netflix (Zuul, Eureka, Hystrix, etc.).

## Contratação

CLT

## Nossa empresa

A DB1 é um grupo de empresas, especializada em Fábrica de Software. Estamos há aproximadamente 19 anos no mercado, com atuação em todo o Brasil e em expansão internacional. Somos reconhecidos pelo Great Place To Work (GPTW) como uma das melhores empresas para se trabalhar no Brasil, com projetos diversos. Nossa sede principal fica localizada em Maringá/PR, temos um polo em Presidente Prudente/SP e estamos abrindo um novo polo em Campo Grande/MS. Para saber mais basta acessar [https://www.db1.com.br](https://www.db1.com.br/).

Buscamos pessoas talentosas que queiram fazer parte deste time de Feras, que são responsáveis e tem influência em tudo o que ocorre à sua volta, que investem no crescimento profissional e humano, que AMAM tecnologia e desafios, que são e promovem LUZ na vida de outras pessoas através do desenvolvimento de softwares de qualidade.  

## Como se candidatar

Acesse  [https://vagasdb1.recruiterbox.com/jobs/fk0j2nx?source=github](https://vagasdb1.recruiterbox.com/jobs/fk0j2nx?source=github)

## Labels

- Remoto
- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by luizfelipehh** [comment]
@nathaliabruno me candidatei para vaga de Trainee, porém não tive um retorno, será que a empresa recebeu meu cadastro? Consegue verificar a situação para mim? Obrigado.

**Comment by nathaliabruno** [comment]
Oi @luizfelipehh, tudo bem?? Falei com o RH e recebi o seguinte retorno: 
> Recebemos o CV, mas agora não estamos rodando processo seletivo pra Trainee. O seu CV ta no banco de dados, e caso surja uma nova rodada de processo seletivo pra trainee, nós entraremos em contato. 😄

**Comment by LuizFelipeUltra** [comment]
@nathaliabruno  Será que consigo me inscrever para uma vaga Junior?

**Comment by luizfelipehh** [comment]
@nathaliabruno será que consigo me candidatar para uma vaga Júnior?

**Comment by Wattam** [comment]
Ainda possuem vagas? O link para se candidatar não funciona

**Comment by jair-anderson-souza** [comment]
também tentei e o link não funciona

**Comment by JosephSousa** [comment]
A vaga ainda está aberta?

**Comment by nathaliabruno** [comment]
Não mais, pessoal. Desculpa não ter fechado aqui...
