### ISSUE TITLE
[REMOTO] Senior Back-End Developer - NodeJS

### ISSUE THREAD

**Issue by MalconMikami** [backend-br/vagas#109]
## Descrição da vaga
O profissional será responsável por desenvolvimento e manutenção da arquitetura em NojeJS. É esperado que a maior parte do trabalho (90%) ocorra em aplicações Back-End com possibilidade de alguma atuação também em Front End.

## Responsabilidades
Trabalhar no processo de construção de soluções de software Back-End, o que envolve desenho, planejamento, execução, manutenção e suporte;
Trazer soluções inteligentes e atuais, utilizando as melhores práticas de engenharia de software para garantir escalabilidade.
Ser pró-ativo;
Defender seu ponto de vista em relação a arquitetura proposta

## Local
Remoto ou Escritório na região de Barueri/Santana de Parnaíba

## Requisitos
3 anos de experiência com Node.js
Facilidade para ler e entender código fonte, independente da linguagem de programação (afinal, um bom desenvolvedor consegue se adaptar a diferentes tecnologias, né?);
Experiência com banco de dados relacionais;
Experiência no desenvolvimento de sistemas com arquitetura de serviços REST;
Experiência com controle de versão, preferencialmente Git e uso do GitHub;
Conhecimento em Sistema Operacional Linux.

## Diferenciais (ganhe pontos extra aqui)
Ter implementado algum sistema utilizando Docker e Kubernetes;
Ter trabalhado com arquiteturas orientadas a micro-serviços;
Gostar de criptomoedas

## Como se candidatar

Por favor envie um email para malconmikami@gmail.com.br com seu CV anexado - enviar no assunto: Vaga Arquiteto NodeJS

## Labels
- Imediato
- Freela
- PJ
- Remoto - Total
- Sênior

**Comment by ghost** [comment]
Vale 3 anos de experiência em javascript?

**Comment by MalconMikami** [comment]
Se atender os demais requisitos, sim.

2018-03-11 13:28 GMT-03:00 Jeferson Inacio Ferreira <
notifications@github.com>:

**Comment by ghost** [comment]
Eu tenho, eu só não tenho experiência profissional em node, só de estudos

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
