### ISSUE TITLE
[REMOTO] Dev. Back-End Pleno (Node.Js) - Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [backend-br/vagas#10903]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas;
- Analisar problemas e propor soluções;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Desenvolvimento e Testes;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Manutenção dos produtos e sistemas;
- Alinhamento com pares;
- Participar de comitês e grupos de acordo com suas especialidades;
- Cumprir entregas no prazo e com alta qualidade;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas.

**Requisitos**

- Criação de código legível para outros desenvolvedores;
- Habilidades de otimização de código para torná-lo mais eficiente;
- Capacidade de quebrar as tarefas em tarefas menores;
- Revisar o código em detalhes;
- Encontrar bugs e propor plano de ação para correção;
- Executar várias tarefas em vários projetos de forma simultânea;
- Domínio das principais linguagens da stack;
- Orientar os desenvolvedores juniores;
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos;
- Conhecimento sólido de Javascript (Node.JS), Express, NestJS, TypeORM, MySQL;
- Conhecimento de Arquitetura em Camadas;
- Conhecimento proficiente em Git;
- Desejável Ensino Superior Cursando ou Completo.

**Diferencias**

- CI/CD;
- Docker;
- Kubernetes;
- Conhecimentos em banco de dados não-relacionais, preferencialmente MongoDB.

**Benefícios** 

- Convênio Médico Sul-América (sem custo para titular);
- Convênio Odontológico Sul-América (sem custo para titular);
- Gympass;
- Convênio com plataforma de idiomas (Fluency Academy);
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

## Local

REMOTO.

## Contratação

PJ

## Como se candidatar

Por gentileza, se candidatar à vaga neste link: https://going2.solides.jobs/

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto
l

**Comment by brlga002** [comment]
Esta vaga não esta disponível no link https://going2.solides.jobs imagino que tenha sido encerrada.
