### ISSUE TITLE
Back-end developer - Houseasy

### ISSUE THREAD

**Issue by HouseasyRH** [backend-br/vagas#10914]
## Houseasy

A Houseasy é uma startup de tecnologia residencial, no segmento de IoT. Temos como missão atuar de maneira ampla e acelerada na geração de conforto à população em geral, otimizando tarefas, reduzindo custos e democratizando o acesso a automação para o lar. Realizando isso de forma simples, prática e eficaz. 

## Descrição da vaga

Desenvolvimento de novas funcionalidades e manutenção em sistemas já existentes em todas as nossas aplicações; 
Apoiar a equipe técnica do planejamento e arquitetura de novas soluções; 

## Localiza em Curitiba/PR

Remoto ou presencial.

## Requisitos Obrigatórios

Comprometimento com coding standards, documentação, testes e boas práticas; 
Prática com Git/Github e de de Versionamentos;  
Inglês técnico intermediário;  
Experiência com desenvolvimento Back-end com Javascript , C# e SQL Server;
 
## Diferenciais para o cargo

Conhecimento em Protocolo MQTT e Sistemas Embarcados; 
Conhecimento básico de DevOps como CI/CD, Infraestrutura de nuvem (GCP, AWS), automação, servidores e load balancers; 

## Benefícios

O que você vai encontrar na Houseasy: 
😬Um ambiente descontraído onde todos tem espaço para criar  
🍎 Frutas fresquinhas 
❤ Seguro de vida 
🏋🏻 Ginástica laboral 
💳 Cartão Caju benefícios 
🩺 Plano médico 
😬 Plano odontológico 
⏰ Horário Semi flexível 
🥳 Day Off no mês do aniversário 

## Contratação
CLT

## Como se candidatar

Para que possa conhecer mais a respeito da Houseasy e da energia do time #toeasy, segue abaixo link que traz como é o nosso dia a dia aqui, nossa cultura, valores e ações internas <a href="https://web.houseasy.net/trabalhe-conosco">aqui</a>. 

### Nível
- Pleno

**Comment by guligon90** [comment]
@HouseasyRH **THIMC**: O link para candidatura submetido não está funcionando (HTTP 404):
![image](https://github.com/backend-br/vagas/assets/35070513/8bf14fab-abe5-4b73-9f67-83e4f7e1c165)

Visitei a página da empresa e este link parece estar funcionando: https://web.houseasy.net/vaga-back-end-pl

**UPDATE**: Testei o formulário de submissão de candidatura no link supracitado, e a página não submete a requisição. Testei via Chrome e Firefox, com a minha VPN local desativada.

**Comment by HouseasyRH** [comment]
Link atualizado.
https://forms.office.com/pages/responsepage.aspx?id=iazo5AVPvUuSCwLZEpnU-HTOG9x2-k5DifZz5AKZyfxUMzFBUUFYRVEzSTM1MDEwTkpLQVY1NDFYSy4u
