### ISSUE TITLE
[100% Remote] Backend Developer (Python) at @SevenApps

### ISSUE THREAD

**Issue by rhSevenApps** [backend-br/vagas#10912]
Nessa posição, você poderá atuar em projetos de grandes empresas clientes nacionais e internacionais, e terá autonomia e liberdade para trabalhar 100% remoto, com flexibilidade de horário. Os seus desafios irão envolver o desenvolvimento back-end (Python); Você terá um time altamente capacitado para implementar essas soluções com você. Nós acreditamos que a Tecnologia tem o poder de transformar o mundo e melhorar a maneira como vivemos e enfrentamos os desafios. Se você também acredita nisso, vem fazer parte do nosso time!

**Requisitos**
Pelo menos **5 anos** de experiência em desenvolvimento Python
Forte compreensão dos frameworks Django e Wagtail
Experiência com sistemas de banco de dados como PostgreSQL
Experiência em projetar e implementar modelos de banco de dados usando ORM.
Proficiência em integrações de API da Web e design de API RESTful
Familiaridade com tecnologias de conteinerização, como Docker
Familiaridade com ferramentas de orquestração de contêineres, como Kubernetes ou Docker Swarm
Familiaridade com metodologias de desenvolvimento Git e Agile
Capacidade de escrever código limpo, eficiente e bem documentado.
Excelente resolução de problemas e habilidades analíticas
Capacidade de trabalhar de forma independente e como parte de uma equipe.
**Inglês avançado**

**Benefícios de trabalhar na SevenApps**
Contratação PJ (Faixa salarial: 3~3,5k dólares)
Revisão salarial periódica: revisão a cada 6 meses;
15 Dias Livre: descanso remunerado por 15 dias ao ano;
Horário Flexível: trabalhe no horário que se sentir mais produtivo
Imersão Internacional: cultura internacional com projetos fora do Brasil;
Bônus por indicação: nos ajude a trazer os melhores devs para nosso time

**Como se candidatar:**
Envie um e-mail para: [[rh@sevenapps.com.br](mailto:rh@sevenapps.com.br)]com o título "Vaga Back-End | Python"

**O código SevenApps**
Somos mais que uma empresa, somos um estilo de vida baseado na paixão em solucionar problemas usando design, usabilidade e tecnologia. Nosso propósito é unir os melhores profissionais do mercado em projetos nacionais e internacionais, com um crescimento de carreira e troca interna de alta velocidade. Nosso time aprende, evolui e compartilha.
Com um escritório administrativo em Belo Horizonte e uma sede nos EUA, já crescemos mais de 300% no último ano e ajudamos nossos clientes a crescerem mais de 120% com alocação dos nossos profissionais sênior e/ou desenvolvimento de aplicativos e softwares de alta performance.

Conheça mais o nosso código SevenApps: https://www.sevenapps.tech/

**Comment by Remato** [comment]
existem vagas para Front ou Mobile? por onde envio CV?

**Comment by rhSevenApps** [comment]
> existem vagas para Front ou Mobile? por onde envio CV?

Infelizmente no momento não temos, mas pode deixar seu currículo no nosso Banco de Talentos, enviando pro nosso e-mail: rh@sevenapps.com.br

**Comment by GuiHungaro** [comment]
Olá @rhSevenApps estão buscando apenas Sênior para Django? Pleno ou Júnior não?

**Comment by WhaleFcker** [comment]
Olá @rhSevenApps boa noite!
Espero que essa mensagem encontre vocês bem!

Estão procurando devs plenos para Django ou apenas Sêniors ?
