### ISSUE TITLE
[100% REMOTO] Desenvolvedor Backend ou Full-Stack Sênior - eCondos Sistemas

### ISSUE THREAD

**Issue by paivaric** [backend-br/vagas#10928]
## Nossa empresa

Somos uma startup 100% remota e trabalhamos bastante com IoT, comunicação em tempo real, aplicativos web, mobile e desktop.

## Descrição da vaga

Precisamos de um desenvolvedor backend ou full-stack. Trabalhamso com NodeJs, Angular, React, React Native, Ionic, Electron, Mongodb e outras tecnologias.

## Local

Remoto

## Requisitos

Mínimo de 5 anos de experiência em NodeJs.

## Contratação

PJ

## Como se candidatar

Para se candidatar e ver maiores detalhes sobre a vaga acesse: [https://econdos-sistemas.breezy.hr/p/38dd99039036-desenvolvedor-full-stack-pleno-ou-senior-remoto](https://econdos-sistemas.breezy.hr/p/38dd99039036-desenvolvedor-full-stack-pleno-ou-senior-remoto)

### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by HudsonAfonso** [comment]
po Queijo, "Angular, React, React Native, Ionic, Electron" se resume em Flutter...

**Comment by rafaprates** [comment]
Gostei bastante da vaga por trabalharem com IoT. Por curiosidade, vocês trabalham com alguma stack que contenha Java/Spring?

**Comment by paivaric** [comment]
> Gostei bastante da vaga por trabalharem com IoT. Por curiosidade, vocês trabalham com alguma stack que contenha Java/Spring?

Não usamos java nem spring.

**Comment by paivaric** [comment]
> po Queijo, "Angular, React, React Native, Ionic, Electron" se resume em Flutter...

até que faz sentido.
