### ISSUE TITLE
[Rio de Janeiro] Jr Developer na [Oslo Investe]

### ISSUE THREAD

**Issue by osloinveste** [backend-br/vagas#1092]
VAGA PARA JR. DEV NA OSLO INVESTE

Se você quer trabalhar com inovação, tecnologia e propósito, a Oslo é o lugar certo.

Somos uma plataforma de liberdade financeira. Nossa missão é ajudar as pessoas a juntar dinheiro e alcançar seus objetivos. Através de nosso aplicativo, possibilitaremos que os clientes invistam qualquer valor, de forma simples e automática, além de ter acesso a dicas e análises personalizadas para seu perfil financeiro. Combinando economia comportamental, micro investimento e tecnologia, tornaremos a relação de nossos usuários com o dinheiro mais próspera e equilibrada.

Estamos buscando pessoas que sejam estimuladas por desafios e pelo desejo de empoderar financeiramente a população.

Confira a vaga abaixo!

Contratação: PJ a combinar.

Se interessou? Envie seu CV para contato@osloinveste.com

![Desenvolvedor-Júnior_V2](https://user-images.githubusercontent.com/50716464/57880111-5008f280-77f4-11e9-8258-fd7e4b65e908.png)

**Comment by gabrielclima** [comment]
Galera, como podemos remover essa vaga? Eu acabei convertendo a conta pra organização e esqueci de fazer a remoção dessa vaga antes da troca. 

Poderiam me ajudar?

**Comment by PRElias** [comment]
É para aparecer para você um botão no canto inferior direito "Delete issue"

![image](https://user-images.githubusercontent.com/5929003/62804036-715f3f00-bac2-11e9-80d1-eac46b2f22c6.png)

**Comment by gabrielclima** [comment]
Sim, mas essa account que estou utilizando **gabrielclima** não foi a criadora da issue. Foi a account **osloinveste** que agora não é mais uma account e sim uma organização. 

Por isso que ela aparece ali em cima como **ghost**
![image](https://user-images.githubusercontent.com/8717587/62807366-91dfc700-bacb-11e9-94af-641e7eed0ede.png)
