### ISSUE TITLE
[REMOTO] Tech Lead Node.js na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [backend-br/vagas#10930]
**INVILLIA**
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

**REQUISITOS_**

·        Linguagem (Typescript e Javascript)
·        Framework Web (Node, Express, Nest, etc)
·        Framework Front-end (React.js)
·        Arquitetura de Microserviços
·        SQL (Oracle)
·        NoSQL (MongoDB)
·        HTDB (Redis)
·        Mensageria (Kafka)
·        APIs (Restful, Swagger)
·        Testes Automatizados
·        CI/CD (Azure Pipelines, Azure Repos, Jfrog, Azure Registry)
·        Docker e Kubernetes
·        Qualidade and Secure (SonarQube)
·        Cloud Computing (Azure, AWS ou GCP)
·        Inglês 

**RESPONSABILIDADES_**
Proporcionar entregas contínuas de alto valor e impacto, atuando ativamente na construção de produtos digitais; 
Mentoring/Coaching técnico do time de desenvolvimento;
Liderança Técnica;
Colaborar nas definições de arquitetura;
Acompanhar monitorações existentes, atuar na evolução destas e planejar ações para mitigar problemas futuros;
Auxiliar em momentos de crise dos sistemas, com foco na resolução dos problemas e no treinamento de outros membros da equipe para esse tipo de atendimento;
Interface técnica com as áreas de negócio e engenharia;
Entender o problema do cliente e propor soluções;
Ser participativo, dar opinião de forma construtiva;
Participar e conduzir reuniões técnicas do projeto;
Melhoria contínua (processo, produto, equipe e pessoal);
Disseminador de conhecimentos técnicos;
Estar em sintonia aos interesses dos projetos e empresa.

**LOCAL_**
Full remoto

**REGIME_**
CLT + benefícios

**COMO SE CANDIDATAR_**
Enviar o currículo atualizado para: [selecao@invillia.com](mailto:selecao@invillia.com)

**Comment by BrenoSantanaBruno** [comment]
https://drive.google.com/file/d/1h1KLGnn2MCP-PC4t8NmM9L-Q3L1Xb2qC/view?usp=sharing
