### ISSUE TITLE
[São Paulo/SP] BI na Resource IT

### ISSUE THREAD

**Issue by LeandroRenzi** [backend-br/vagas#1093]
## Empresa
 Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga
Trabalhar em equipe (scrum) utilizando as ferramentas de BI homologadas.

## Posição
Desenvolvedor Pleno/Sênior

## Tipo de contratação
 CLT

## Requisitos
- SSIS
- SSAS
- SQL

##Diferencial
- Tableau

## Benefícios
•	Plano de saúde Sulamérica Exato Apto com coparticipação
•	Convênio Odontológico - Porto Seguro
•	Seguro de vida
•	VR de R$ 440,00
•	Auxílio creche
•	Convenio Farmácia

## Contato
Por favor envie um email para leandro.renzi@resourceit.com com seu CV anexado - enviar no assunto: [VAGA BI] [Seu nome completo]

### Alocação:
- Presencial

## Local
Itaim Bibi - SP

##Labels
experiencia/pleno
experiência/sênior
experiência/junior

**Comment by LeandroRenzi** [comment]
novas vagas abertas para 2020 ;)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
