### ISSUE TITLE
[Internacional e Remoto] Vagas Backend com foco em Java (salário até U$D 128.000) na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#10947]
Pessoal, vim trazer aqui um compilado rápido de vagas internacionais e remotas na Turing, empresa de desenvolvimento de software americana que está contratando pesado aqui no Brasil.

[Desenvolvedor Back-end](https://remotar.com.br/job/15748/turing.com/desenvolvedor-back-end?utm_source=github)
Nível: Pleno e Senior 
- Ao menos 3 anos de experiência relevante como desenvolvedor back-end
- Experiência comprovável com Java, PostgreSQL, Kubernetes, Redis e AWS

[Desenvolvedor Java Back-end](https://remotar.com.br/job/15730/turing.com/desenvolvedor-java-back-end?utm_source=github)
Nivel: Senior 
- 5 anos de experiência relevante como desenvolvedor back-end
- Conhecimento avançado sobre Java

[Java Engineer](https://remotar.com.br/job/15904/turing.com/java-engineer?utm_source=github)
Nível: Senior 
- 5+ years experience in object-oriented languages
- Proficiency with OOAD principles and methodologies 

## Importante
- salário pode chegar em U$S 128.000 (claro que depende da vaga e nível de experiencia);
- eu infelizmente não sou responsável pelo processo seletivo, apenas ajudo a Turing com a divulgação;
- tem MUITAS vagas, então se vocês cumprem os  requisitos, não tenham medo de aplicar;
- **o sistema de recrutamento deles é  bem exigente: se você marcar que tem menos tempo de experiência do que o  exigido, sua candidatura não vai pra frente.** 

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by Luisfelipeqt** [comment]
existe alguma vaga para Desenvolvedor JR com 3 anos de experiencia? poderíamos conversar?

**Comment by tatidirienzo** [comment]
@Luisfelipeqt então, eu não sou responsável pelo recrutamento, estou apenas ajudando na divulgação. Mas [neste link](https://remotar.com.br/search/jobs?q=3%2B&c=13) aqui eu fiz uma busca por vagas em programação que pedem 3+ anos de experiência. E nas [vagas da Turing](https://remotar.com.br/company/88/turing.com), muitas pedem 3 anos também
