### ISSUE TITLE
[Remoto] Full Stack developer - IT Recruiter

### ISSUE THREAD

**Issue by jeanpereiraa** [backend-br/vagas#10948]
## Nossa empresa
Empresa portuguesa contrata para trabalho remoto no Brasil, como possibilidade de transferência para Portugal.

## Descrição da vaga
As responsabilidades:
- Desenvolver a arquitetura do site front-end.
- Projetar interações de usuários em páginas da Web.
- Desenvolver aplicativos de back-end para sites.
- Criar servidores e bancos de dados para funcionalidade.
- Garantir a otimização entre plataformas para telefones celulares.
- Garantir a capacidade de resposta dos aplicativos.
- Trabalhar com designers gráficos para recursos de web design.
- Acompanhamento de um projeto desde a concepção até o produto final.
- Projetar e desenvolver APIs.
- Atender às necessidades técnicas e dos consumidores.
- Manter-se a par dos desenvolvimentos em aplicativos da Web e linguagens de programação.

## Local

Remoto

## Requisitos

- Graduação em ciência da computação ou áreas relacionadas.
- Experiência mínima de 3 anos nesse cargo
- Sólidas habilidades organizacionais e de gerenciamento de projetos.
- Proficiência em linguagens front-end fundamentais, como HTML, CSS e JavaScript.
- Familiaridade com estruturas JavaScript, como Angular JS, React e Amber.
- Familiaridade com tecnologia de banco de dados, como MySQL, Oracle e MongoDB.
- Java com experiência em API.
- Java com experiência em Spring Boot
- Excelentes habilidades de comunicação verbal.
- Boa capacidade de resolução de problemas.
- Atenção aos detalhes.
- Inglês fluente obrigatório

Desejáveis
- Conhecimento em linguagens do lado do servidor, como Python, Ruby, PHP e .Net.

## Contratação

Modelo de contrato PJ

## Como se candidatar

Por favor envie um e-mail para jeanrecrutamentoit@gmail.com com seu CV anexado, CV em inglês - enviar no assunto: Vaga Full Stack 

### Nível

- Pleno/Sênior

**Comment by BrenoSantanaBruno** [comment]
Olá. Mandei agora e recebi uma mensagem dizendo que seu e-mail não existe.

**Comment by BrenoSantanaBruno** [comment]
[Breno Santana Bruno - English Resume.pdf](https://github.com/backend-br/vagas/files/11569930/Breno.Santana.Bruno.-.English.Resume.pdf)
