### ISSUE TITLE
[Breno Santana Bruno - English Resume.pdf](https://github.com/backend-br/vagas/files/11569930/Breno.Santana.Bruno.-.English.Resume.pdf)

### ISSUE THREAD

**Issue by jeanpereiraa** [backend-br/vagas#10949]
[Breno Santana Bruno - English Resume.pdf](https://github.com/backend-br/vagas/files/11569930/Breno.Santana.Bruno.-.English.Resume.pdf)

Oi Breno, já corrigi, ficou faltando uma letra no e-mail.
Está tudo certo agora

**Comment by LucienCorreia** [comment]
???

**Comment by gbtb16** [comment]
???

**Comment by itbrunoms** [comment]
???
