### ISSUE TITLE
[100% remoto] Back-end developer PHP - nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#10945]
## nexmuv

Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Desenvolvedor Fullstack (PHP)
Atuar com desenvolvimento de novos sistemas  e sustentação de sistemas já existentes. 

## Local

100% remoto.

## Requisitos
Ampla experiência com desenvolvimento em PHP;
-Experiência com GIT e Docker, Kubernetes;
-Experiência com Cloud AWS ou Azure;
-Experiência com React ou Angular; 
Informe os requisitos obrigatórios e desejáveis para a vaga.

## Contratação

PJ 

## Como se candidatar

Enviar cv para natalia.xavier@nexmuv.com.br

### Nível

- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by Emersonovidio** [comment]
enviado.
