### ISSUE TITLE
[Alocação] Back-end developer PHP Pleno - @Sambatech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#10966]
## Nossa empresa

A Samba está buscando uma **Pessoa Desenvolvedora PHP Pleno** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em **regime PJ e Campinas/SP**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Local
Remoto, Brasil.

## Requisitos

- Experiência prévia em desenvolvimento com linguagem PHP;
- Experiência com banco de dados (MySQL, SQL, Mongo DB);
- Experiência com desenvolvimento em Rest API;
- Experiência em Git (GitHub / GitLab);
- Vivência com metodologias ágeis (Scrum, XP, Kanban, Lean, Squad).

## Diferencial

- Dominar mais de uma linguagem de programação (JavaScript, Java, Node);
- Estar familiarizado com o framework Zend;
- Conhecimento do padrão MVC (Model View Controller);
- Conhecimento em AWS;
- Conhecimento em SaaS;
- Conhecimento em Docker;
- Ter atuado em mais de um dos ciclos do desenvolvimento (concepção, implementação, operação e manutenção).

## Contratação

PJ (clássico).

## Como se candidatar

Se inscreva pelo link: https://sambatech.compleo.com.br/Visualizar/154563

### Nível
- Pleno

### Regime
- PJ

### Alocação
- Presencial

**Comment by humbertocandido** [comment]
Bom dia, tarde e noite. Você poderia me responder se a vaga é presencial ou remota ?

**Comment by brlga002** [comment]
Enviado :)

**Comment by LeandroBarbosaBento** [comment]
Afinal, a vaga é presencial ou é remota?

**Comment by daiaoli** [comment]
Ei pessoal, vi que coloquei errado ali no local, mas seria presencial em Campinas/SP.
