### ISSUE TITLE
Nodejs developer - Softvaro

### ISSUE THREAD

**Issue by Rayy1004** [backend-br/vagas#10977]
## Descrição da vaga
Perfil consultivo, ou seja, que tenha visão crítica para avaliar se as demandas priorizadas pelo cliente contribuem para o resultado esperado. Que tenha o hábito de compartilhar suas ideias e experiências, além de analisar qual a solução mais eficaz para o problema a ser resolvido.
Comunicação clara e objetiva, que possui facilidade para tratar diretamente com públicos diversos (gerentes, coordenadores, analistas de negócio, times de desenvolvimento).
Sem restrição para se comunicar com pessoas no dia a dia, pois a rotina demanda interações com o cliente, pessoas de diversas áreas.
Perfil flexível para atuar em squads no modelo Build-Run (Projetos e Sustentação).
Perfil flexível para atuar em demandas / atividades desde sua concepção / análise, até a sua implantação no ambiente definido.
NÃO atuamos apenas como desenvolvedores, e sim somos Consultores, ou seja, suas atribuições não se resumem em apenas codificar! Além de atender as demandas da squad, o cliente preza por pessoas que discutem e tragam soluções para os problemas apresentados.
Comprometimento com as suas entregas.
Pode necessitar de atuações fora do horário para recuperar prazos de projetos e/ou acompanhar implantações em ambiente produtivo.

## Local - Brasil - Remoto

Informe se é remoto, híbrido ou presencial.

## Requisitos

Tecnologias Obrigatórias - NodeJS, APIs, HTML/CSS, JavaScript/Typescript, Bancos de dados relacionais (Oracle), Bancos de dados não relacionais (MongoDB), AWS e Docker
Tecnologias Desejadas:Node-RED, Python, Ferramentas de monitoramento (Kibana, Grafana e/ou AppDynamics)

## Benefícios

Programa de Meritocracia;
Day off de aniversário;
Trabalho 100% remoto;
Reembolso para cursos;
Bônus de indicação;

## Contratação

Contratação PJ.

## Como se candidatar

enviar email para raiany.fonseca@softvaro.com.br

### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by danieldfc** [comment]
Enviado

**Comment by YuriMont** [comment]
Enviado
