### ISSUE TITLE
[São Paulo/SP] Full Stack Developer na NIC.br

### ISSUE THREAD

**Issue by simetadmin** [backend-br/vagas#1097]
> Venha fazer parte da NIC.br onde construimos uma Internet para todos cada vez melhor. Na NIC.br você encontra um propósito e oportunidades para elevar sua carreira a um novo patamar.

### **A empresa**
**NIC.br** é uma empresa sem fins  lucrativos, que implementa as decisões do Comitê Gestor da Internet no Brasil (CGI.br) e trabalha pela melhoria da Internet Brasileira. Com sede em São Paulo, financiamento sólido e atuação em todo país, a empresa desempenha um papel crítico na evolução da Internet Brasileira. Acreditamos que a Internet é para todos e que ela terá uma importância cada vez maior em nossas vidas. Por isto o nosso trabalho é a favor de toda sociedade e de todo Brasil. Saiba mais sobre a empresa **NIC.br** e a sua missão em:

https://youtu.be/MGSzdKpZEWo
https://youtu.be/-0_A_BExNTQ
https://nic.br/atividades/

### **A vaga**
Na **NIC.br** você fará parte do nosso projeto de **Medição da Qualidade da Internet**. Como **Desenvolvedor Full Stack** você irá atuar no desenvolvimento de sistemas de software e terá participação em todo ciclo do desenvolvimento, incluindo concepção, arquitetura e implementação dos sistemas. No dia-a-dia você encontrará desafios como processamento em larga escala, sistemas distribuídos e arquiteturas baseadas em múltiplos paradigmas. Você irá trabalhar com uma equipe enxuta e experiente, incluindo especialistas em design, data science e sistemas embarcados. Você irá usar sua experiência de **Desenvolvedor Full Stack** tanto no desenvolvimento de sistemas backend, quanto de aplicações frontend e terá espaço para desenvolver um papel de liderança neste campo dentro da nossa equipe.

### **Benefícios e Informações**
- Contratação por CLT com salário competitivo em relação ao mercado
- Plano de saúde executivo premium
- Vale refeição integral
- Apoio para participação em congressos e treinamento profissional
- A vaga é presencial em região empresarial de São Paulo

### **Qualificação necessária**
- Pelo menos 4 anos de experiência com desenvolvimento de software
- Graduação em Engenharia, Ciência da Computação ou cursos afins
- Sólido conhecimento em fundamentos de ciência de computação (desenvolvimento de algoritmos, modelagem e análise de complexidade)
- Capacidade de trabalhar focado em problemas
- Experiência com liderança técnica, avaliação de tecnologias e de arquiteturas 
- Conhecimentos em redes, protocolo HTTP e programação web
- Experiência com micro-serviços e sistemas distribuídos
- Linux intermediário
- Inglês intermediário

### **Qualificação desejável**
- Desenvolvimento backend com Elixir, Golang, Java ou NodeJS
- Arquiteturas para sistemas intensivos em dados (big data)
- Banco de dados Postgres e sistema de fila Kafka
- Desenvolvimento frontend com React ou VueJS
- Gerência de estado client-side no navegador
- Projeto de APIs REST e GraphQL
- Experiência com metodologias ágeis de projeto
- Experiência em integração e entrega contínua (CI/CD)
- Conhecimento em boas práticas de desenvolvimento de software, ciclo de vida de produtos, code review, testes automatizados e gerência de ambientes
- Especialização, Mestrado ou Doutorado é um diferencial valorizado

**Comment by dgoscn** [comment]
quero

**Comment by dgoscn** [comment]
Ainda aberta?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
