### ISSUE TITLE
[REMOTO] Back-end developer - Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [backend-br/vagas#10985]
## Nossa empresa

Com 35 anos de história, somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial do sistema ArcGIS, desenvolvido pela Esri. A Esri é uma multinacional americana, com mais de 5.000 colaboradores ao redor do mundo.
Mais do que tecnologia entregamos soluções e geramos valor para mais de 4 mil clientes dos diversos segmentos de negócio e esferas de governo.

## Descrição da vaga

Analisar, planejar e executar desenvolvimento e/ou manutenção de soluções de GIS/TI nas fases de Design, Construção, Tecnologia, Requisitos, Teste, Infraestrutura, Configuração e Qualidade.

## Local

Remoto

## Requisitos

**Formação:**

- Superior Completo nas áreas de tecnologia, desenvolvimento ou afins;

**Habilidades e experiências:**

- Python;
- Javascript / Typescript;
- [ASP.NET.](http://asp.net./)
- Manipulação de banco de dados (Oracle, PostgreSQL, SQL Server);
- Conhecimento das ferramentas de controle de versão de código e de banco de dados.

**Diferencial:**

- Conhecimento GIS e do sistema ArcGIS;
- Arquitetura e design de Software;
- Noções de arquitetura de aplicações para ambiente Web, Desktop e Mobile.

## Benefícios

- Plano de Saúde; 
- Assistência Odontológica;
- Vale alimentação ou refeição;
- Valor integral do alimentação/refeição na férias;
- Cartão Alelo Multibenefícios;
- Vale transporte;
- Gympass;
- PLR;
- Seguro de Vida Individual - sem custos para o colaborador;
- Cooperativa de crédito;
- Flexibilidade de Horário de até 1 hora na sua jornada;
- Licença Paternidade estendida de 15 dias;
- Oportunidades de movimentação interna;
- Programa de Indicação;
- Day Off no aniversário + Vale Ifood;
- Day Off no aniversário do filhos (as) até 16 anos;
- Incentivo a cursos e idiomas: até 2h de estudo durante a semana;
- Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade.

## Contratação

CLT

## Como se candidatar

Quer saber mais da vaga? Acesse e faça seu cadastro: https://lnkd.in/dk5kScX7

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Remoto

**Comment by flakow** [comment]
Aplicado

**Comment by pedrosteinmuller** [comment]
Enviado!
