### ISSUE TITLE
[REMOTO] Back-end developer - Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [backend-br/vagas#10989]
## Nossa empresa

A Codex é uma organização que atende diversos segmentos do mercado, oferecendo soluções completas e especializadas em tecnologia, desenvolvimento de sistemas de informação, consultoria setorial e práticas de gestão corporativa.

## Descrição da vaga

- Realizar e orientar a equipe nas atividades de análise, desenvolvimento, manutenção, implantação, sustentação e documentação de software garantindo a qualidade das entregas;
- Desenvolvimento de sistemas;
- Gerar e gerenciar releases no GitHub;
- Apoiar o time de desenvolvimento júnior.

## Local

Remoto

## Requisitos

**Requisitos e qualificações:** 
- Ensino superior completo;
- Inglês intermediário.

**Habilidades Necessárias:**
- Experiência com duas ou mais das seguintes tecnologias: Kotlin, Java, Android, React, TypeScript e SQL;
- Análise crítica e capacidade em resolução de problemas.

**Habilidades Desejáveis:**
- Experiência com arquitetura de soluções;
- Liderança de times de desenvolvimento de software/produto;
- Conhecimento em [Node.Js](http://node.js/), React e outros frameworks de mercado;
- Experiência com integração continua e TDD;
- Experiência com modelagem e consumo de APIs REST.

## Benefícios

- Plano de Saúde; 
- Assistência Odontológica;
- Flexibilidade de Horário de até 1 hora na sua jornada;
- Oportunidades de movimentação interna;
- Programa de Indicação.

## Contratação

PJ

## Como se candidatar

Cadastre-se em: https://codexutilities.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjUwMjI0MTl9?jobBoardSource=gupy_public_page

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by NashiCodes** [comment]
Aplicado
