### ISSUE TITLE
[São Paulo] Back-end developer - Culttivo Tecnologia

### ISSUE THREAD

**Issue by CamilaCulttivo** [backend-br/vagas#10992]
## Nossa empresa

A Culttivo é uma plataforma digital que oferece aos produtores de café, crédito livre de burocracias desnecessárias, filas e pegadinhas. Nasceu da união de experientes profissionais do agronegócio com intuito de utilizar as mais sofisticadas ferramentas do mercado para atender a cadeia do café.  Simplificamos a vida "porteira a fora" e empoderamos o produtor rural, potencializando o foco no que é mais importante, a sua lavoura. 

## Descrição da vaga

-Implementar soluções em conjunto com outros profissionais;
- Desenvolver e evoluir microserviços e APIs em Node.js, utilizando bancos de dados como MSSQL Server  e MongoDB;
- Construir integrações com sistemas, serviços, parceiros e clientes;
- Implementar e implantar soluções utilizando recursos da nuvem Microsoft Azure.

## Local

Remoto

## Requisitos

- Experiencia de 1 ano com desenvolvimento em Node.js, banco de dados relacionais e Git;
- Conhecimento em React JS;
- Conhecimento em recursos de Microsoft Azure e desenvolvimento de APIs;
- Conhecimentos em mecanismos de fila;
- Conhecimento de metodologias ágeis e DevOps;
- Será um diferencial ter conhecimento em desenvolvimento assíncrono, bancos de dados NO-SQL, implantação de testes unitários e de integração.

## Benefícios flexíveis

- Vale Refeição
- Vale Alimentação
- Mobilidade
- Seguro Saúde
- Academia
- Ajuda de custo para home office

## Contratação

Cooperado

## Como se candidatar

Interessados encaminhar CV por e-mail para camila.candido@culttivo.com com o título Vaga Backend

## Labels
- Júnior

### Regime
- Contrato

### Alocação
- Remoto

**Comment by danieldfc** [comment]
Enviado

**Comment by heygon** [comment]
@CamilaCulttivo enviei o email! Obrigado pela oportunidade!

**Comment by YuriMont** [comment]
Enviado

**Comment by jotaviobueno** [comment]
Enviado

**Comment by lanziotti** [comment]
Enviado

**Comment by rafaelslopes1** [comment]
Enviado

**Comment by rzinak** [comment]
Enviado :)

**Comment by pedrosteinmuller** [comment]
Enviado!

**Comment by JoaolSoares** [comment]
Enviado ;)
