### ISSUE TITLE
[Remoto] Fullstack developer  Node.js and React - Datum

### ISSUE THREAD

**Issue by julianakraemer** [backend-br/vagas#10994]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo terceiro ano seguido. Nossa sede fica em Porto Alegre/RS e recentemente chegamos no Canadá

## Descrição da vaga

Responsabilidades e atribuições:
Buscamos Pessoa Desenvolvedora Fullstack, com foco em React.js e boa experiência em Node.js, para atuar na criação de novas features, manutenção das funcionalidades e correções de bugs do novo site de uma relevante empresa do segmento de varejo.
O profissional deve ser capaz de propor novas soluções que visem a melhoria e otimização dos sistemas web mantidos pela tribo.
Participação ativa nos ritos do modelo de trabalho, code-reviews, pair programmings e elaboração de documentações.
## Local

Trabalho remoto
## Requisitos

Mandatória experiência em desenvolvimento frontend na tecnologia React.js, configurações, padrões e boas práticas de desenvolvimento;
Sólida Experiência em Node.js;
Experiência com Design System é diferencial;
Sólida Experiência com testes para frontend, testes unitários e automatizados, biblioteca Jest;
Experiência com versionamento de código em Git. Gitflow e fluxo de desenvolvimento utilizando pipeline (esteira) CI/CD;
Desenvolvimento limpo, organizado, sempre aplicando boas práticas, conceitos de performance e segurança em primeito lugar;
Participar ativamente do processo de Code Review;
Vivência em metodologias ágeis e participação em seus ritos e dinâmicas, Scrum / Kanban;
Dedicação em tempo integral;
## Benefícios

Bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!
## Contratação

PJ R$71/HORA

## Como se candidatar

Envie um e-mail para: Juliana.kraemer@datum.inf.br
### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by danieldfc** [comment]
Enviado

**Comment by YuriMont** [comment]
Enviado
