### ISSUE TITLE
[São Paulo] Back-End Developer na DEVPARTNER

### ISSUE THREAD

**Issue by FabianaCarvalhal** [backend-br/vagas#110]
## Descrição da Empresa e da Vaga

A DevPartner é uma empresa de TI focada em soluções de Gestão de Relacionamento. Hoje nosso principal segmento é o automotivo, porém atendemos outros segmentos também.
Nossas soluções são moduladas para cada necessidade dos nossos clientes, portanto, não somos uma empresa de desenvolvimento de produtos.

Para os desenvolvimentos, utilizamos a plataforma .net, linguagem c# e banco de dados sql server, ambiente windows. Todos os novos desenvolvimentos estão direcionados em **MVC** e **WEBAPI**, utilizando interface em AngularJS.

De qualquer forma, temos projetos que damos manutenção em estrutura **.net webforms**.

**Como foco para esta vaga, necessitamos de um profissional com competência para atuar nos desenvolvimentos backend (WebForms, MVC, WEBAPI - C# e/ou VB.NET) para nossas soluções.**

Nossa missão é ENTREGAR RESULTADO, e portanto, nossos colaboradores são fundamentais para que possamos atingir nossa meta, tendo ativa participação nos projetos e no dia a dia da operação.

O departamento de TI tem os seguintes perfis:
- Designer/Front-End: profissionais com perfil de criação e programação de front-end. É responsabilidade deste perfil realizar a programação em AngularJS
- Desenvolvedor .net: profissionais com perfil de programação .net, com conhecimentos de banco de dados e de html/css/javascript para atuação quando projetos em estrutura MVC (Razor) e/ou webforms
- Banco de Dados: profissionais com perfil específicos de banco de dados para atuação em projetos determinados e/ou apoio em projetos que necessitem de procedimentos em banco de dados
- Suporte: Infraestrutura em geral

## Local
Estamos localizados na região do Campo Belo, perto do aeroporto de congonhas, em uma estrutura de casa, sede própria.
Por estarmos em uma casa, o ambiente é extremamente descontraído, não deixando de lado nosso profissionalismo.

## Benefícios
- VT
- VR de R$ 17,50/dia
- Auxílio de 50% do Plano de Saúde

#### Diferenciais
- cozinha: servimos café da manhã até às 09h00; além disso, você pode trazer sua comida (marmita) e almoçar na empresa (temos geladeira e microondas)
- sala de jogos
- café da tarde (20 minutos de pausa geral)

## Requisitos
**Obrigatórios:**
Experiência em projetos Web (MVC/WEBAPI/WEBFORMS). Irá atuar nos desenvolvimentos dos backends dos projetos web

## Contratação
Nosso regime de contratação é a CLT.

## Como se candidatar
Por favor envie um email para fabiana.carvalhal@devpartner.com.br com seu CV anexado - enviar no assunto: Vaga BACKEND

## Labels
- CLT
- PJ
- Pleno
- Sênior
- Alocado

**Comment by carloshenriqueribeiro** [comment]
**Requisito Obrigatório:**
resolver nosso desafio para backend:
https://goo.gl/DgjVrM

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.

**Comment by FabianaCarvalhal** [comment]
Vaga aberta ainda, Reginaldo.

Vc pode reabrir para mim?



[Fabiana_Carvalhal]

De: Reginaldo Junior [mailto:notifications@github.com]
Enviada em: sexta-feira, 11 de maio de 2018 16:25
Para: backend-br/vagas
Cc: Fabiana Carvalhal; Author
Assunto: Re: [backend-br/vagas] [São Paulo] Back-End Developer na DEVPARTNER (#110)


Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.

**Comment by FabianaCarvalhal** [comment]
Obrigada!

Sei que é só para vagas Backend e Frontend, mas estou com uma vaga para Banco de Dados, você teriam indicação de onde posso anunciar?

Obrigada,

[Fabiana_Carvalhal]

De: Reginaldo Junior [mailto:notifications@github.com]
Enviada em: terça-feira, 15 de maio de 2018 15:43
Para: backend-br/vagas
Cc: Fabiana Carvalhal; Author
Assunto: Re: [backend-br/vagas] [São Paulo] Back-End Developer na DEVPARTNER (#110)


Reopened #110<https://github.com/backend-br/vagas/issues/110>.

**Comment by reginaldojunior** [comment]
Ainda tem vagas?

**Comment by FabianaCarvalhal** [comment]
Sim, Reginaldo!

[Fabiana_Carvalhal]

De: Reginaldo Junior [mailto:notifications@github.com]
Enviada em: terça-feira, 12 de junho de 2018 10:53
Para: backend-br/vagas
Cc: Fabiana Carvalhal; Author
Assunto: Re: [backend-br/vagas] [São Paulo] Back-End Developer na DEVPARTNER (#110)


Ainda tem vagas?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
