### ISSUE TITLE
[Remoto] Full Stack developer - Mr. Turing

### ISSUE THREAD

**Issue by marcoaleixo** [backend-br/vagas#11003]
Vaga: Full Stack Developer (Python, Django, React)

A Mr. Turing, uma empresa inovadora focada em inteligência artificial e processamento de linguagem natural, está buscando um(a) desenvolvedor(a) Full Stack talentoso(a) para fortalecer nossa equipe e contribuir para o desenvolvimento de nossa plataforma SaaS, Alan. Nossa equipe trabalha de forma remota, e recentemente iniciamos a expansão da Mr. Turing em Toronto, Canadá.

**Responsabilidades:**

- Desenvolver e manter aplicações web usando Python, Django, React, JavaScript e TypeScript;
- Colaborar com a equipe de desenvolvimento para criar e otimizar funcionalidades, garantindo a qualidade e escalabilidade;
- Participar de todo o ciclo de vida do desenvolvimento, desde o planejamento até a implementação e manutenção;
- Integrar-se com outras APIs e serviços conforme necessário;
- Auxiliar na implementação de boas práticas de segurança e conformidade de dados;
- Trabalhar em equipe e se comunicar efetivamente com colegas e clientes internacionais.

**Requisitos:**

- Experiência prévia como Full Stack Developer ou função similar de no mínimo 3 anos;
- Domínio em Python, Django, React, JavaScript e TypeScript;
- Experiência com Git e controle de versão;
- Conhecimento em desenvolvimento responsivo e boas práticas de UX/UI;
- Experiência comprovada em integração de APIs e serviços de terceiros;
- Habilidade para trabalhar de forma independente e em equipe;

**Diferencial:**
- Proficiência em inglês, devido à nossa expansão para o Canadá e possível contato direto com clientes canadenses.

**Faixa salarial**: R$8.000,00

**Como se candidatar:**

Envie seu currículo para marco.aleixo@misterturing.com com o assunto "Full Stack Developer - Seu Nome". Estamos ansiosos para conhecer você e explorar como sua experiência e habilidades podem contribuir para o sucesso contínuo da Mr. Turing!

**Comment by ferreirase** [comment]
8 pau pra Full Stack e ser proficiente em inglês? Tá de sacanagem...

**Comment by marcoaleixo** [comment]
> 8 pau pra Full Stack e ser proficiente em inglês? Tá de sacanagem...

É, a ideia é pegar alguém com conhecimento em inglês, não estou citando nenhum tipo de requisito extremamente avançado como C1 ou C2. Valeu pelo feedback.

**Comment by guilherme90** [comment]
Amigão, se o cara sabe inglês, você acha mesmo que ele vai querer trabalhar aí sabendo que pode ganhar 2, 3x mais que isso? Para um inglês como B1/B2 já é o suficiente para trabalhar no exterior. 

Além disso, 8k está abaixo do mercado,

**Comment by rrgaya** [comment]
@marcoaleixo 
> É, a ideia é pegar alguém com conhecimento em inglês, não estou citando nenhum tipo de requisito extremamente avançado como C1 ou C2. Valeu pelo feedback.

mas proeficiência em inglês é C1 level man. Como o @guilherme90  falou esta bem fora da realidade do mercado.

**Comment by marcoaleixo** [comment]
Entendo o ponto dos senhores, mas meu objetivo aqui é contração e não alterar a minha vaga de acordo com o que vocês acham o correto.
Recebi ótimos currículos com vários níveis de inglês, ajustei as expectativas e é isso.
Obrigado.
