### ISSUE TITLE
[Remoto] PHP Symfony developer Sr- Datum TI

### ISSUE THREAD

**Issue by julianakraemer** [backend-br/vagas#11000]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo terceiro ano seguido. Nossa sede fica em Porto Alegre/RS e recentemente chegamos no Canadá

## Descrição da vaga

Desenvolver e customizar aplicações zelando pelo desempenho, estabilidade, escalabilidade, segurança, simplicidade e melhores práticas de programação;

Codificar aplicações previamente pesquisadas e documentadas pelos Analistas de Sistemas;

Organizar e documentar o código desenvolvido;

Negociar prazos de entrega de acordo com a sua capacidade de produção;

## Local

Remoto
## Requisitos

Conhecimento avançado em PHP;

Utilização de padrões de código PSR;

Conhecimento intermediário em Linux;

Conhecimento intermediário em linguagem SQL com preferência em banco de dados Oracle;

Conhecimento intermediário nos Frameworks Symfony ou Laravel (Preferencialmente Symfony);

Conhecimento intermediário em versionamento Git;

Conhecimento intermediário em JavaScript, jQuery, HTML, CSS;

Conhecimento intermediário no Framework Bootstrap;

Conhecimento na utilização de APIs REST e consumo de Webservices;

Inglês técnico intermediário;

Conhecimento sobre serviços síncronos e assíncronos;

Já ter trabalhado com desenvolvimento orientado a objetos;

Atenção para qualidade de código e design patterns;
## Benefícios

Bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!
## Contratação

PJ
## Como se candidatar

Envie um e-mail para: Juliana.kraemer@datum.inf.br

### Nível

- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Remoto

**Comment by devXela** [comment]
fechada?
up?

Att,

Alex Rosa Santos Barbosa
Desenvolvedor PHP

Em qui., 27 de jul. de 2023 às 21:58, github-actions[bot] <
***@***.***> escreveu:
