### ISSUE TITLE
[Híbrido em São Paulo/SP] Fullstack Developer (NodeJs/VueJs) na @DQR Tech 🧡🥷

### ISSUE THREAD

**Issue by kerol-barros** [backend-br/vagas#11010]
## Sobre a DQR TECH | Qualidade do começo ao fim 
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting. 

## Descrição da vaga
Estamos buscando pessoas desenvolvedoras pleno ou sênior para atuar em nosso cliente de setor financeiro - é o maior banco de Investimentos da América Latina!

## Local
Híbrido: 3x na Av. Faria Lima/SP e 2x home office.

## Requisitos
**Obrigatórios:**
Experiência em projetos de desenvolvimento de software utilizando NodeJS e VueJS; 
Banco de dados MongoDB; 
Serviços de mensageria (RabbitMQ/Kafka ou semelhante); 
Design Patterns GoF; 
Desenvolvimento de aplicações em nuvem AWS (Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS)

**Desejáveis:**
Execução de testes unitários; 
Metodologia ágil; 
Atuação com o mercado financeiro; 
Experiência em modelagem de dados em DDD; 
Conhecimento em Arquitetura de Microsserviços. 

## Benefícios
- Auxílio flexível para gastar como quiser (vale alimentação 🍔🛒);
- Assistência médica e odontológica gratuita para você (sem coparticipação ou mensalidade),
- Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
- Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;
- Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
- Seguro de vida em grupo;
- Aqui a sua indicação vale premiação de 1k;
- No mês do seu aniversário tem mimos;
- Notebook para o desempenho das atividades.

## Contratação
CLT

## Como se candidatar
Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: [kerolayne.barros@dqrtech.com.br](mailto:kerolayne.barros@dqrtech.com.br) - enviar CV anexo e no assunto colocar: Vaga - Fullstack Node/Vue

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 04 dias após cada processo.

### Nível
- Pleno
- Sênior
- Especialista

### Regime
- CLT

### Alocação
- Híbrido

### Período
- Full time

🧡🖤 Todas nossas vagas são destinadas a Pluralidade e Diversidade.

**Comment by gsabreudev** [comment]
🧡🖤 Vem fazer parte da DQR TECH!!

**Comment by carolinetech** [comment]
🧡🖤 Vem fazer parte da DQR TECH!!

**Comment by DaianeMFirmiano** [comment]
🧡🖤 Ótima oportunidade!!!   #VemPraDQRTECH

**Comment by danieldfc** [comment]
Enviado! 🧡🖤

**Comment by DaianeMFirmiano** [comment]
VAGA ATIVA!!
Venha bater um papo com nosso time!!

**Comment by guilherme90** [comment]
Vaga bem interessante! Modelo é realmente híbrido ou existe possibilidade 100% remoto?
