### ISSUE TITLE
[REMOTO] Back-end developer (Node) - KARHUB

### ISSUE THREAD

**Issue by marinanlima** [backend-br/vagas#11011]
## Nossa empresa

A KarHub nasceu em 2022 com uma forte paixão por tecnologia e com o propósito de tornar a compra online de Autopeças muito mais fácil e intuitiva. Para isso, criamos e unimos um time de Code, Design, Strategy, People e Ops em uma jornada que ocorre de forma ágil e colaborativa.
Na nossa cultura, valorizamos a transparência, espírito de dono e a meritocracia. Aprendemos muito com as nossas pessoas e incentivamos que todos os nossos times contribuam com o que tem de melhor para a nossa comunidade.

## Descrição da vaga

Como Dev Back End você fará parte de um dos nossos times que tem como principal responsabilidade criar um hub de integrações entre a KarHub e seus diversos parceiros, são integrações que irão nos ajudar a vender mais e também integrações para capturar informações(vendas e comportamento) que nos ajudarão a proporcionar uma experiência KarHub para os nossos clientes.
Trabalhar em conjunto com o time de Back-end, desenvolver e estruturar sistemas de inteligência e estruturação de dados;
Montar processos de primeira equipe interna da startup junto ao CTO.

## Local

Remoto

## Requisitos

Experiência prévia em NodeJS/Javascript/Typescript ou Golang;
Conhecimento de Micro Serviços;
Experiência com ferramentas de versionamento de código (GitHub);
Conhecimento em metodologias ágeis (Scrum/Kanban);
Conhecimento em ferramentas AWS e/ou GCP;
Habilidades interpessoais de escrita e de comunicação verbal;
Ser organizado(a), proativo(a) e analítico(a);
Gostar de aprender sempre!
Formação em Engenharia, Matemática, Estatística, Ciência da Computação ou Análise de Sistemas.

## Benefícios

Benefício Convênio Médico Alice e Stock Options.

## Contratação

PJ

## Como se candidatar
Enviar Linkedin e Github para marina@techrecruiterbrazil.app com título da vaga.

### Nível
- Pleno
- Sênior

### Regime
- PJ

### Alocação
- Remoto

**Comment by pedrosteinmuller** [comment]
Enviado!
