### ISSUE TITLE
[Internacional e Remoto] PHP/Laravel Developer na Turing.com (salário até U$D 150k / ano)

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#11023]
## About
A fast-growing company building a comprehensive platform that enables users to keep track of their accounting and financial management for business and personal life in one place is looking for a PHP/Laravel Developer. The selected candidate will be collaborating with cross-functional teams to deliver high-quality products. The company’s next-gen platform is built to cater to the needs of the self-employed, freelance, and gig-economy reliant. This is an exciting opportunity for developers who enjoy tackling challenging problems and building advanced products.  

## Job Responsibilities:

- Collaborate with designers, front-end engineers, and incredibly talented back-end engineers to create a world-class fintech application
- Participate in daily stand-up meetings and weekly knowledge sharing
- Experience writing tests, identifying and resolving issues in support of a release
- Continuously improve the codebase to improve stability and performance (error handling and knowing when to refactor)
- Provide training, mentoring, and assistance to other team members
- Believe that continuous learning is an essential component of being a modern developer

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 4+ years of experience working with PHP/Laravel and SQL
- 4+ years of experience with REST/RESTful APIs
- Must have in-depth knowledge of object-oriented PHP and Laravel frameworks
- In-depth experience with SQL schema design, SOLID principles, and REST API design 
- Must be creative and a problem solver
- Take charge of the entire feature development life cycle, from concept to delivery and post-launch support
- Use back-end integration services to help expand and maintain existing application services APIs
- In addition to writing test scripts, contribute to the manual QA testing to identify and report bugs to the engineering team
- Fluent in written and spoken English

## Candidatura
Para se candidatar, você deverá acessar a[ url da vaga](https://bit.ly/3NHZ1SO) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by LovelyDev829** [comment]
Nice posting, as a PHP/Laravel developer, what can I do now?

**Comment by tatidirienzo** [comment]
> Nice posting, as a PHP/Laravel developer, what can I do now?

just apply in [here](https://www.turing.com/remote-developer-jobs/j/php-laravel-developer-56007?s=ads_developers_remotarJobs&n=https://www.turing.com/remote-developer-jobs/j/php-laravel-developer-56007)

Good luck!

**Comment by LovelyDev829** [comment]
Thank you
