### ISSUE TITLE
[REMOTO] Sr Backend Developer Python c/ Inglês ou Espanhol - Invillia

### ISSUE THREAD

**Issue by maria-invillia** [backend-br/vagas#11045]
## Nossa empresa
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.

Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.

Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

## Responsabilidades e atribuições
O profissional será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.

Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.

Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).

Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

Ser entusiasta por novidades no mundo da tecnologia é algo crucial, portanto, é importante ser apaixonado pelo que faz.

## Local
Remoto

## Requisitos
Linguagens: Python 

Frameworks Web: Django 

Arquitetura/Padrões de Projetos: Microserviços 

Banco de Dados: Postgres (RDS) 

Mensageria: RabiitMQ 

Assíncrono: Celery Worker 

Cloud: experiência com AWS (EC2, RDS) 

CI/CD: Jenkins, Docker compose 

Idioma: Espanhol ou Inglês avançado

## Contratação
CLT

## Como se candidatar
Enviar um e-mail para selecao@invillia.com com o assunto "Vaga de Python Sr com Inglês/Espanhol" e com o corpo do e-mail contendo currículo, pretensão salarial e telefone para contato

### Nível
- Sênior

### Regime
- CLT

### Alocação
- Remoto

**Comment by BrunoMoreno** [comment]
Enviado
