### ISSUE TITLE
[100% REMOTE] Back-end developer Node.JS MID LEVEL Stagwell

### ISSUE THREAD

**Issue by mdc-partner** [backend-br/vagas#11056]
## 

a holding company that houses various marketing, public relations and other communications agencies. The company operates through a network of independent agencies, each with their own distinct specialties and brands. These agencies work together to provide integrated marketing and communications solutions to clients.

## Descrição da vaga

The professional will be responsible for providing technical solutions for new features and giving the necessary support to existing features, after all, not everything is flowers.

We also expect this person to help other team members with technical issues, not forgetting to provide the best solution for the business.

Something we value a lot is quality, this includes clean and readable code (clean code).

## Local

Full remote

## Requisitos

Responsibilities:
English is not a requirement. It is not necessary

experience working with Node, TS, and unit test
Develop codes following recommendations;
Perform bug fixes;
Focus on the quality of the codes;
Perform code review.

## Benefícios

training in English, among many others

## Contratação

Contractor.

## Como se candidatar

send your cv by telegram from Romanvicto
### Nível

- Estagiário
- Júnior
- Pleno

### Regime

- PJ
- CLT
- Contrato

### Alocação

- Remoto

**Comment by Cosmess** [comment]
Send !

**Comment by danieldfc** [comment]
Send!

**Comment by YuriMont** [comment]
Send

**Comment by tthiagopereira** [comment]
send

**Comment by dev-mariana** [comment]
sent!

**Comment by tthiagopereira** [comment]
Bom segue meu currículo

Em qua., 26 de jul. de 2023 às 12:00, Mariana Bastos <
***@***.***> escreveu:

**Comment by tthiagopereira** [comment]
send

**Comment by tthiagopereira** [comment]
send

**Comment by aandrelouis** [comment]
send

**Comment by JoaolSoares** [comment]
send!

**Comment by lucasccosta** [comment]
sent!

**Comment by tthiagopereira** [comment]
send

**Comment by RobsonMT** [comment]
send!

**Comment by Fecef** [comment]
sent

**Comment by araujodev** [comment]
Conversando com outros membros do grupo aparenta ser um golpe. Gostaria de saber quem avançou até qual etapa.

**Comment by jairokoning** [comment]
> Conversando com outros membros do grupo aparenta ser um golpe. Gostaria de saber quem avançou até qual etapa.

Pois é, tenho a mesma impressão. Fiz os testes tecnicos, enviei para o whats do Roman na quarta-feira (09/08/2023). Ele não responde as mensagens, excluiu o perfil dele no Linkedin. Muito estranho isso.

**Comment by jairokoning** [comment]
Alguem teve algum retorno da MDC Partner ou do Roman?

**Comment by MateusSousa00** [comment]
Não respondem mais, nem Jessie, nem Roman, nem Chris, ninguém. Me pergunto se a Stagwell sabe disso.

**Comment by jairokoning** [comment]
Isso eu vou descobrir se a empresa está ciente disso tudo. Vou coletar prints/evidências e procurar alguma forma de entrar em contato com a MDC ou a Stagwell.

**Comment by jairokoning** [comment]
É galera, realmente é golpe...

https://www.reclameaqui.com.br/empresa/programathor/

**Comment by Carlosajunior** [comment]
Mesma coisa aconteceu comigo, ofereceram a vaga, mandaram o contrato, pediram a invoice, mas nunca chegou o pagamento. Vocês tem algum grupo para contato?
