### ISSUE TITLE
[FULL REMOTE] C# / .NET Developer MID Level in Stagwell

### ISSUE THREAD

**Issue by mdc-partner** [backend-br/vagas#11055]
## 

a holding company that houses various marketing, public relations and other communications agencies. The company operates through a network of independent agencies, each with their own distinct specialties and brands. These agencies work together to provide integrated marketing and communications solutions to clients.

## Descrição da vaga

The professional will be responsible for providing technical solutions for new features and giving the necessary support to existing features, after all, not everything is flowers.

We also expect this person to help other team members with technical issues, not forgetting to provide the best solution for the business.

Something we value a lot is quality, this includes clean and readable code (clean code).

## Local

Full remote

## Requisitos

Responsibilities:
English is not a requirement. It is not necessary

experience working with C#, C++, and .NET

Develop codes following recommendations;
Perform bug fixes;
Focus on the quality of the codes;
Perform code review.

## Benefícios

training in English, among many others

## Contratação

Contractor.

## Como se candidatar

send your cv by telegram from Romanvicto
### Nível

- Estagiário
- Júnior
- Pleno

### Regime

- PJ
- CLT
- Contrato

### Alocação

- Remoto

**Comment by plo1991** [comment]
Ola,

Vaga esta em aberto ainda ?
