### ISSUE TITLE
[Remoto -  PJ] Full Stack Developer Pleno - Jusfy

### ISSUE THREAD

**Issue by guilhermepiza** [backend-br/vagas#11069]
## Nossa empresa
A [Jusfy](https://www.linkedin.com/company/jusfy/) está em busca de um Full Stack Developer Pleno para compor o time! Somos uma startup jurídica que busca constantemente soluções para facilitar a vida dos advogados e advogadas brasileiros. Atuamos na área de tecnologia, desenvolvendo produtos e ferramentas que auxiliam na produtividade diária dos nossos clientes.
Somos uma empresa jovem, mas muito promissora. Alcançamos resultados expressivos de crescimento nos últimos anos e sabemos que temos ainda muito mais para conquistar. Buscamos profissionais que queiram fazer parte dessa trajetória junto conosco!

## Descrição da vaga
Responsabilidades:
- Desenvolver novas funcionalidades utilizando ReactJS e APIs RESTful, utilizando Node.js e Express;
- Escrever códigos limpos, de alta qualidade e fácil manutenção seguindo as boas práticas de desenvolvimento;
- Realizar code reviews, ajudando outros desenvolvedores a melhorar a qualidade do código;
- Colaborar com a equipe de tecnologia (Engenharia, Produto e Design) para o sucesso dos projetos;
- Participar ativamente em discussões de arquitetura e tecnologias;
- Realizar code reviews, ajudando outros desenvolvedores a melhorar a qualidade do código;
- Garantir que a documentação do código e arquitetura esteja sempre atualizada;
- Corrigir bugs.

## Local
100% Remoto!

## Requisitos
Requisitos técnicos:
- Experiência com desenvolvimento de Backend e Frontend;
- Experiência em Typescript e API REST;
- Conhecimento em bancos de dados relacionais e não-relacionais;
- Orquestração de containers (Docker e docker-compose);
- Conhecimento em Styled Components e Context API;
- Experiência com controle de versão utilizando Git.

Desejável:
- Experiência com metodologias ágeis;
- Experiência em times de desenvolvimento de software ou empresas de tecnologia;
- Conhecimento em testes automatizados e ferramentas de integração contínua;
- Conhecimento de Design Patterns;
- Habilidade para trabalhar em equipe e boa comunicação;
- Boa habilidade de resolução de problemas e pensamento crítico.

## Benefícios
Oferecemos:
- 100% Remoto;
- Flexibilidade de horário;
- Ambiente de trabalho descontraído e inovador;
- Oportunidade de trabalhar em projetos desafiadores e com grande impacto.

## Contratação
PJ

## Como se candidatar
Candidaturas encerradas no momento

### Nível
- Pleno

### Regime
- PJ

### Alocação
- Remoto

**Comment by santyasm** [comment]
Enviado!

**Comment by rafaelfgyn** [comment]
Enviado!
