### ISSUE TITLE
[REMOTO] Back-end developer PHP - Tainacan

### ISSUE THREAD

**Issue by vnmedeiros** [backend-br/vagas#11068]
OPORTUNIDADE

Olá Pessoal, estou a procura de desenvolvedor WordPress pleno/senior para fazer parte de um projeto do IBRAM. A contratação é na forma de uma bolsa anual. Se você tiver interesse ou se conhecer alguém que possa estar interessado entre em contato.

Seguem os dados:

**Bolsa FAPESP TT-5**
**_Objeto geral: Desenvolvedor PHP+Wordpress: plugins e temas_**
Valor: R$ R$ 9.046,80
Dedicação exclusiva – 40h semanais. (não pode ter carteira assinada, mas pode ter MEI, PJ e trabalhos por fora, horário flexível)
Local: Brasília – DF, **modalidade presencial/remota.**
Início das atividades: a partir de agosto de 2023
Requisitos:
- Graduação em Graduado em Ciência da Computação, Engenharia da Computação, Sistemas de Informação, Análise e Desenvolvimento de Sistemas ou áreas afins;
- Mínimo de cinco anos de experiência em pesquisa ou experiência profissional após a graduação, ou com título de doutor, ambos em área relacionada ao Plano de Atividades proposto;
- Desejável conhecimento em programação PHP com especialização no CMS WordPress;
- Desejável conhecimento em Docker, Javascript (vue.js, angular, react).

enviar currículo para: **gabrielamelorocha2014@gmail.com**

### Nível
- Pleno
- Sênior
- Especialista

### Regime
- Bolsa

### Alocação
- Remoto
- Híbrido
- Presencial

![vaga](https://github.com/backend-br/vagas/assets/1179250/88a8a372-919e-43c3-8563-88382bf0afe5)

**Comment by devXela** [comment]
Essa vaga não é remota, favor ajustar.
