### ISSUE TITLE
[REMOTO] Full-stack developer - Stealth Startup

### ISSUE THREAD

**Issue by paivaric** [backend-br/vagas#11089]
## Nossa empresa

Somos uma Stealth Startup, focada em revolucionar a indústria com uma solução disruptiva em desenvolvimento. Estamos procurando um Engenheiro de Software talentoso e apaixonado para se juntar à nossa equipe no desenvolvimento do backend. Se você é alguém que adora desafios, tem um conhecimento em tecnologias web modernas e está pronto para deixar sua marca no mercado em um ambiente de startup dinâmico e colaborativo, esta é a oportunidade perfeita para você.

## Local

REMOTO

## Requisitos

Experiência comprovada no desenvolvimento de aplicativos backend usando TypeScript e Node.js.
Conhecimento em design de API e desenvolvimento utilizando frameworks modernos, como Nest.js.
Experiência em integração de bancos de dados relacionais, garantindo eficiência e segurança.
Familiaridade com práticas ágeis de desenvolvimento de software e colaboração em equipe.
Experiência ou familiaridade com serviços em nuvem, preferencialmente AWS, para implantação escalável e gerenciamento de infraestrutura.
Paixão por escrever código testável e de alta qualidade, com experiência em testes unitários e de integração.
Habilidades de resolução de problemas, pensamento crítico e capacidade de lidar com desafios técnicos complexos.
Excelentes habilidades de comunicação e colaboração em equipe.

## Benefícios

A oportunidade emocionante de fazer parte de uma Stealth Startup com um potencial transformador.
Ambiente de trabalho dinâmico e colaborativo, onde suas ideias e contribuições são valorizadas.
Espaço para crescimento profissional e aprendizado contínuo, com acesso a tecnologias de ponta.
Remuneração competitiva e possibilidade de Stock Options dependendo da performance.

## Contratação

PJ

## Como se candidatar

Acesse https://forms.gle/RzNk7Mop6uhoePa38.

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Remoto

**Comment by jhefflg** [comment]
Up!

**Comment by guilherme90** [comment]
Oferecem máquina para trabalhar?

**Comment by ricksonthompson** [comment]
Currículo enviado!✅
