### ISSUE TITLE
[Remoto] Back End Pleno (Elixir/Node.JS/React.JS) JUST TRAVEL 

### ISSUE THREAD

**Issue by Lusaniabarbosa** [backend-br/vagas#11095]
A JUST TRAVEL é uma TRAVEL TECH referência na distribuição de produtos turísticos de alta qualidade e excelência em atendimento ao cliente em qualquer lugar do mundo. Somos uma combinação de experiência da indústria do turismo, tecnologia e marketing digital. Estamos crescendo de forma exponencial e investindo na expansão do nosso time. Se você é uma pessoa proativa, organizada, flexível, gosta de trabalhar em equipe e sabe lidar bem com pressão, esta vaga pode ser para você!

**É importante destacar que o profissional realizará as seguintes atividades:**

- Desenvolver e manter serviços backend robustos e escaláveis utilizando Elixir
- Criar testes que garantam qualidade e confiabilidade ao desenvolvimento
- Ajudar o time de produto a digitalizar o turismo no mundo
- Colaborar na construção da arquitetura das soluções
- Construir soluções utilizando bancos de dados relacionais (SQL) e não relacionais (No-SQL)

**Segue algumas informações importantes:**

- Modelo de trabalho: Remoto ou Presencial em Salvador
- Modelo de contratação: PJ

**Requisitos/Qualificações:**

- Experiência sólida em desenvolvimento back-end utilizando programação funcional. Preferencialmente Elixir mas também Scala, Kotlin, Clojure, Erlang, NodeJS ou Python
- Familiaridade com metodologias ágeis
- Desenvolvimento e implementação de APIs REST e GraphQL
- Habilidade de aprender rapidamente, resolver diferentes tipos de problemas e se adaptar a mudanças constantes
- Conhecimento de boas práticas de desenvolvimento de software
- Algum contato com serviços AWS como EC2, Amplify, S3, Lambda

**Será um bônus se você se:**

- Possuir experiência liderando pequenas equipes
- Possuir experiência na construção de produtos
- Você residir em Salvador-BA

**Inscrições pelo link: https://x.gd/beuw1**

**Vem ser Justtravel!**

**Comment by matheuscamarques** [comment]
Estou aberto a oportunidade [linkdlin](https://www.linkedin.com/hp/matheuscamarques)
