### ISSUE TITLE
[São Paulo - SP] Desenvolvedor(a) Ruby on Rails na Pitzi

### ISSUE THREAD

**Issue by penelopevitoria** [backend-br/vagas#1114]
### **Sobre a Pitzi**

Somos uma empresa que cria experiências humanas. Sabemos que a vida é uma soma de experiências, e algumas são frustrantes, mas acreditamos que com carinho e velocidade podemos transformar frustrações em experiências admiráveis. 

No time de tecnologia nos esforçamos para unir tecnologia e empatia com base em dados. Nosso time é reconhecido por saber utilizar dados para escalar e agir rapidamente. Dados nos ajudam a automatizar processos mecânicos, ter mais velocidade e tornar a tecnologia mais humana.

### **Nossas práticas e princípios:**

- Procuramos sempre escrever código limpo (fácil de entender, modificar, estender e testar)

- Procuramos cuidar do código como um jardim, sempre tentando deixar melhor do que encontramos

- Fazemos Code review por Pull Requests (PR);
- Usamos boas práticas de engenharia + metodologias ágeis;
- Usamos o conceito de MVP em features. Colocamos no ar o mínimo para ser usado e validado;
- Estamos sempre abertos a receber críticas construtivas sobre o código;
- Buscamos a melhoria contínua em todos os processos.

### **Conhecimentos necessários**

- Ruby / Ruby on Rails
- JavaScript
- Testes Automatizados
- Algum Sistema de Banco de Dados Relacional
- Boa experiência com SQL
- Excelentes habilidades para escrita/comunicação
- Inglês técnico

### **Conhecimentos desejáveis**
Conhecimento de infraestrutura Cloud-Based (AWS)

### **O que oferecemos:**

- Ambiente de trabalho com muita autonomia
- Flexibilidade de horário
- Oportunidade é presencial em São Paulo, mas com flexibilidade de home office quando necessário

**### Tipo de contratação**

CLT

### **Tecnologias obrigatórias**

Ruby on Rails, Ruby

### **Benefícios**

Vale Refeição, Vale Alimentação e Vale Transporte, Convênio Médico e Odontológico, Salário competitivo;

### **Candidate-se:** 
http://bit.ly/30yMwj5

**Comment by garaujodev** [comment]
Por favor, deixe mais informações. É remoto, alocado? Onde?

**Comment by flaugabriel** [comment]
Como se candidatar ?

**Comment by penelopevitoria** [comment]
> Por favor, deixe mais informações. É remoto, alocado? Onde?

Pessoal, peço desculpas. Foi publicada sem querer quando estava sendo formatada. Agora está completa. Se faltar alguma info, por favor, me avisem!
