### ISSUE TITLE
[Remoto] Back-end developer (R$ 86K - 140K) - Milenio Capital

### ISSUE THREAD

**Issue by milenio-recruiter** [backend-br/vagas#11154]
## Nossa empresa

A Milenio é uma gestora de recursos focada na originação, estruturação, financiamento e gestão de produtos de crédito, com ênfase na redução da distância entre empresas e investidores. Nossa missão é unir o melhor do crédito com tecnologia. A empresa conta com um time de +40 colaboradores, sendo liderada por sócios com profundo conhecimento no mercado de crédito e tecnologia.

## Descrição da vaga

Estamos buscando por um(a) desenvolvedor(a) apaixonado(a) e motivado(a) para:
- Colaborar na construção de nossas APIs;
- Atuar com as tecnologias mais atuais do mercado;
- Realizar análises e manutenções em nossos sistemas existentes;
- Ficar por dentro das tendências e novidades do setor;
- Demonstrar uma insaciável vontade de aprender e evoluir.

## Local

Full remoto, ou em nossos escritórios em:
- São Paulo (Itaim Bibi);
- Rio de Janeiro (Leblon).

## Requisitos

Obrigatórios:
- Experiência com pelo menos uma linguagem de backend;
- Zelo pela qualidade do código;
- Familiaridade com git, padrões de projeto e design patterns;
- Conhecimento de banco de dados relacional e não-relacional;
- Competências em Docker;
- Autoaprendizado e desejo intenso de se aprimorar.

Desejáveis:
- Experiência em desenvolvimento Python com FastAPI;
- Experiência com MongoDB e SQL;
- Experiência com AWS.

## Benefícios

- Plano de saúde e odontológico Bradesco
- Vale Refeição de R$ 44,00/dia
- Vale Alimentação de R$ 600,00/mês

## Contratação

Regime CLT, com bônus semestral atrelado ao seu desempenho e ao da empresa. A remuneração anual é entre R$ 86k e R$ 140k, além dos benefícios.

## Como se candidatar

Interessados devem enviar o currículo por e-mail com o título “Vaga de Desenvolvedor” para selecao.dev@milenio.capital.

### Nível

- Júnior

### Regime

- CLT

### Alocação

- Remoto

**Comment by Daaaiii** [comment]
Currículo enviado :)

**Comment by MatheusLucas1** [comment]
Acabei de enviar meu curriculo!

**Comment by JohnPonciano** [comment]
Currículo enviado !

**Comment by oraffdev** [comment]
Currículo enviado!

**Comment by fabiohcnobre** [comment]
Currículo enviado

**Comment by jeffersongoncalves** [comment]
Currículo enviado

**Comment by daenerys98** [comment]
Currículo enviado!

**Comment by notOliveira** [comment]
Currículo enviado!

**Comment by RaphaelSchefflerF** [comment]
Currículo enviado!

**Comment by RaphaelSchefflerF** [comment]
Currículo enviado
