### ISSUE TITLE
OPORTUNIDADE REMOTA: BACK END PLENO (WEB) - GOING2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [backend-br/vagas#11161]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas
- Analisar problemas e propor soluções
- Especificar sistemas, processos e APIs
- Modelagem de dados
- Planejamento e estimativa de desenvolvimento
- Desenvolvimento e Testes 
- Versionamento organizado no Git
- Participar dos rituais do time (SCRUM)Manutenção dos produtos e sistemas
- Alinhamento com pares
- Cumprir entregas no prazo e com alta qualidade
- Pode trabalhar sozinho ou em equipe como um líder
- Pode configurar o ambiente de desenvolvimento sozinho
- Tem iniciativa e busca maneiras diferentes de resolver problemas
- Criação de novas funcionalidades 
- Manutenção de funcionalidades já existentes Aplicação de documentação Gerenciamento de prazos 
- Atualização de evolução de trabalho (Jira) 
- Participação de reuniões técnicas (Internamente/Stakeholder)

**Requisitos**

- Criação de código legível para outros desenvolvedores
- Habilidades de otimização de código para torná-lo mais eficiente
- Capacidade de quebrar as tarefas em tarefas menores;
- Revisar o código em detalhes
- Encontrar bugs e propor plano de ação para correção
- Executar várias tarefas em vários projetos de forma simultânea
- Orientar os desenvolvedores juniores
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
- Conhecimento sólido de Javascript (Node.JS), Express, NestJS, TypeORM, MySQL e Swagger;
- Conhecimento de Arquitetura em Camadas;
- Conhecimento proficiente em Git (Github, bitbucket);
- Conhecimentos básicos em Devops (GCP);
- CI/CD (DIFERENCIAL);
- Docker (DIFERENCIAL);
- Firebase (DIFERENCIAL);
- Kubernetes (DIFERENCIAL);
- Testes de unitários e integração (DIFERENCIAL);
- Conhecimentos em banco de dados não-relacionais, preferencialmente MongoDB (DIFERENCIAL).

**Benefícios**

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.

## Contratação

PJ 

## Como se candidatar

Por favor cadastrar através do link: https://going2.vagas.solides.com.br/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by ghost** [comment]
Olá, bom dia!
O link que disponibilizou só direciona para a plataforma, mas não para a vaga.
