### ISSUE TITLE
[Remoto] Backend Sênior - Food To Save

### ISSUE THREAD

**Issue by franriedo** [backend-br/vagas#11182]
## Sobre a Food To Save

Somos uma startup que nasceu do #inconformismo sobre o desperdício de alimentos no Brasil. Hoje, desperdiçamos 30% de toda a comida produzida, em torno de 15 milhões de toneladas de alimentos por ano, o que nos faz estar presente na lista dos 10 países que mais desperdiçam alimentos no mundo. 
Pensando nisso, juntamos propósito e tecnologia, e então, nasceu a Food To Save, com o sonho de revolucionar o desperdício de alimentos no Brasil e na América Latina, gerando uma reflexão sobre a forma como consumimos alimentos e repensando hábitos que contribuam para um futuro mais sustentável e humano. Criamos uma solução simples e funcional, que conecta os estabelecimentos aos #foodsavers, engajados em combater o desperdício de alimentos. E seu papel é fundamental para seguirmos juntos nessa causa tão urgente e necessária.

Venha fazer parte da #1 no Brasil contra o desperdício de alimentos.

Nossa #missão é eliminar o desperdício revolucionando a forma de consumir alimentos. E temos a #visão de ser O MOVIMENTO referência na luta contra o desperdício de alimentos, promovendo consumo consciente e sustentável.

## Descrição da vaga

- Criar e manter aplicações remotas;
- Analisar e corrigir problemas em ambiente de testes e produção;
- Autogerenciar suas próprias atividades e tarefas de acordo com os projetos do time;
- Se comunicar e participar ativamente das discussões e atividades do time;
- Capacidade de discutir em alto nível sobre diversos tipos de problemas do dia-a-dia e da equipe;
- Cuidar da monitoração das aplicações e criar ações para garantir a saúde da plataforma;
- Desenvolver e escalar o produto junto com o time de Engenharia;
- Participar de todo o fluxo do produto, desde a definição até o deploy e monitoramento;
- Auxiliar e sugerir melhorias

## Local

100% Remoto

## Requisitos

- Conhecimento em Java (opcional Golang, Rust, Javascript ou outra linguagem de programação);
- Conhecimento em boas práticas e padrões de projetos (SOLID, DRY, YAGNI, KISS);
- Conhecimento em aplicações Web, REST e micro-serviços;
- Conhecimento em testes automatizados (unitários e integração);
- Conhecimento em Docker (desejável Kubernetes);
- Conhecimento em cloud (AWS);
- Conhecimento em bancos de dados relacionais e não relacionais;
- Proatividade, bom relacionamento interpessoal e comunicação ativa;
- Conhecimento em Spring ou outros frameworks Web;
- Conhecimento de filas (SQS, Kafka, RabbitMQ);
- Desejável conhecimento em Maven ou Gradle.

## Benefícios

- Assistência Médica SulAmérica Nacional;
- Vale Refeição no cartão Cajú;
- No mês do seu aniversário tem crédito extra no cartão Cajú para ajudar na comemoração;
- Seguro de Vida da Prudential para seu conforto e de quem você ama;
- Auxílio Creche para crianças até 1 ano de idade;
- Convênio com SESC São Paulo;
- Gympass em parceria com a SulAmérica;
- Day off de aniversário;
- 100% Remoto.

## Contratação

Oferecemos CLT como principal estilo de contratação, mas podemos abrir exceção para quem opte por PJ.

## Como se candidatar

Enviar o link do LinkedIn para: rh@foodtosave.com **(Caso o perfil do LinkedIn não esteja completo com as descrições das atividades, pode ser enviado o currículo no lugar)**.

### Nível

- Pleno
- Sênior

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by franriedo** [comment]
29/09/23 -Vaga continua aberta. São 5 posições.

**Comment by franriedo** [comment]
18/10/23 Vaga continua ativa. Posições abertas 2/5.

**Comment by nelsonmfinda** [comment]
Olá @franriedo aceita candidatos de outro país(Angola)?

**Comment by franriedo** [comment]
Vaga encerrada 09/11/2023

**Comment by franriedo** [comment]
Vaga encerrada 09/11/2023
