### ISSUE TITLE
[Remoto] PHP e/ou JavaScript Back-end developer - EANP

### ISSUE THREAD

**Issue by milton-alvarenga** [backend-br/vagas#11194]
## Nossa empresa

Venha balancear crescimento na carreira com tempo livre focando em qualidade de vida.

Gostamos de trabalhar duro, focar em bater metas, mas ao mesmo tempo, ter um bom tempo livre para relaxar e ficar com as pessoas que amamos.
Para isto, mesmo trabalhando para clientes de diversos tamanhos e paises, costumamos ter nossos dias de feriados e folgas no padrão brasileiro.

E mais, costumamos emendar feriados de terça e quinta em todos os projetos que estão com entrega em dia. E costumamos sempre estar em dias em todos os projetos. E sim. Carnaval é feriado para nós também.

Além disto, tiramos férias no final/início de ano de modo a podermos aproveitar o máximo deste período incrível. Em geral 2 semanas no final de dezembro e 2 semanas no início de janeiro.

## Descrição da vaga

Atuamos na sustentação e criação de diversos projetos para diversos clientes em diversas áreas.

O desenvolvedor terá a oportunidade de atuar em vários projetos diferentes de diversas empresas clientes, ao mesmo tempo que terá grandes oportunidades de crescimento de acordo com seu domínio e produtividade em atender as demandas existentes.

PHP ou Javascript são nossas ferramentas principais para atender as necessidades de nossos clientes. Domínio de SQL será o suficiente para se dar bem com todas as opções de bancos de dados que utilizamos

## Local

Remoto - Horário de atuação definido pelo desenvolvedor.

Temos clientes em vários timezones diferentes, mas o foco é timezone América.

## Requisitos
* Fulltime position
* Long term position.
* PHP
* Bom ter um conhecimento de Laravel e Symfony, pois vários clientes usam, mas não é obrigatório para iniciar na vaga

## Benefícios
* Emendamos todos os feriados de terça e quinta. (quando os projetos estão em dia e seguimos os feriados de sp/sp)
* Costumamos estar sempre com os projetos em dia
* Vários projetos de vários clientes, o que gera muita oportunidade de aprendizado, crescimento, assim como estabilidade
* Atuamos em várias áreas, não só programação como infra e gestão de cloud. Caso goste, é uma oportunidade de aprender e adicionar experiência ao seu cv, e claro, mais promoção interna.
* Em programação, temos projetos em várias linguagens como PHP, JS, Python e Ruby. Caso queira aprender ou praticar outra linguagem, tem possibilidade de ser alocado em outros projetos para ganhar experiência e acumular stack, e claro, mais promoção interna.
* Se gosta realmente de programação, o trabalho costuma ser muito divertido com os desafios e projetos que temos

## Contratação

CLT, PJ ou Freela

## Como se candidatar

[Candidatar](https://docs.google.com/forms/d/e/1FAIpQLScsqtOyw6M8cokQMEmZkrc8Gsur_KvxTsZQz1Kmf4nA0k9UNw/viewform)

### Nível

- Júnior
- Pleno

### Regime

- PJ
- CLT
- Contrato
- Freelance

### Alocação

- Remoto

**Comment by GuilhermeSoares009** [comment]
Opa, me candidatei! 😁

**Comment by phvm** [comment]
Candidatura enviada!

**Comment by WillianDias-BDev** [comment]
Candidatura enviada! :)

**Comment by rms-diego** [comment]
Candidatura enviada!

**Comment by alvinscheibe** [comment]
🤙🏻

**Comment by Quelvinmp** [comment]
Candidatura Enviada!
