### ISSUE TITLE
[HÍBRIDO/REMOTO] Pessoa Engenheira de Software Senior (Back-End) - DORIS

### ISSUE THREAD

**Issue by rafaelcavalcante** [backend-br/vagas#11193]
Estamos em busca de uma pessoa com excelente comunicação, organização e bom relacionamento interpessoal. Buscamos alguém que consiga trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas e participando de decisões importantes de nossos produtos e tecnologias.

## Requisitos

- NodeJS
- Typescript
- APIs GraphQL e RESTful
- Microsserviços
- Plataformas de CI/CD (Codefresh e CircleCI)
- Experiência com testes unitários, testes de integração, testes end-to-end e TDD
- Amazon Web Services
- Conhecimento em Design Patterns e padrões SOLID
- Hexagonal, Onion e Clean Architecture
- Kanban
- Sistemas de filas (RabbitMQ, Kafka)
- Inglês de nível B1 ou superior*
- Boa comunicação

## Desejáveis

- Python
- NestJS
- Express ou Fastify
- Serverless
- Google Cloud Platform
- Scrum
- Experiência com arquitetura de software

## Diferenciais

- HTML e CSS
- React
- React Native ou Flutter
- CI/CD com Bitrise

## O que você vai encontrar aqui

- Cultura forte de testes
- Experiências com equipes adjacentes
- Compartilhamento de conhecimento
- Equipe comprometida em construir softwares de qualidade
- Plano de carreira construído com uma pessoa gestora
- Discussões para tomadas de decisão e rumos de projeto
- Code review e pair-programming

## Contratação

- Regime PJ
- Descanso remunerado
- Regime híbrido (Av. Faria Lima, São Paulo)

Entendemos que ao se aplicar para essa vaga você confirma a veracidade e entendimento das respostas preenchidos nos campos de perguntas e que cumpre os requisitos descritos no campo da vaga.
Carta de apresentação e referências serão muito bem recebidos durante o processo de recrutamento e colocarão você em uma posição de destaque.
 
*: O EFSET (efset.org) possui um teste gratuito para avaliar seu nível de inglês

## Quer se candidatar?

Se aplique via [Linkedin](https://www.linkedin.com/jobs/view/3728269989/) ou entre em contato com o _[Engineering Manager](https://www.linkedin.com/in/rafaelcavalcante/)_ ou o [_Tech Lead_](https://www.linkedin.com/in/vlctormartlns/) caso a vaga já esteja encerrada.

### Nível

- Sênior
- Especialista

### Regime

- PJ
- Contrato

### Alocação

- Híbrido

**Comment by ferreirase** [comment]
Acredito que as informações de remuneração e local do trabalho híbrido seriam relevantes pra quem está querendo aplicar.

**Comment by rafaelcavalcante** [comment]
> Acredito que as informações de remuneração e local do trabalho híbrido seriam relevantes pra quem está querendo aplicar.

Oi Anderson! Agradeço seu comentário. Já adicionei a região (Av. Faria Lima) e estou acertando os valores com o CTO. Você tem interesse na vaga?

**Comment by ferreirase** [comment]
> > Acredito que as informações de remuneração e local do trabalho híbrido seriam relevantes pra quem está querendo aplicar.
> 
> Oi Anderson! Agradeço seu comentário. Já adicionei a região (Av. Faria Lima) e estou acertando os valores com o CTO. Você tem interesse na vaga?

Tenho interesse sim, te aceitei lá no LinkedIn.

**Comment by rafaelcavalcante** [comment]
Ainda estamos no processo de seleção ✌️

**Comment by rafaelcavalcante** [comment]
Já estamos avaliando perfis mas ainda aceitando candidatos ;)
