### ISSUE TITLE
[Remote Work] Back-end developer - Korp

### ISSUE THREAD

**Issue by NovareRH** [backend-br/vagas#11191]
[Remote Work] Back-end C# e Angular developer - Korp

## Descrição da vaga
﻿﻿‍✔️ TAREFAS:
- Atuar no desenvolvimento de novas aplicações utilizando Golang e Angular;
- Criação/testes de componentes e telas em Angular;
- Desenvolvimento de serviços REST em Golang.

## Requisitos
Experiências e qualificações:
💻RESPONSABILIDADES:
- Sua experiência deve ser voltada a programação orientada a objeto;
- Experiência com banco de dados SQL;
- Ter bem desenvolvido a lógica de programação;
- Conhecimento em DDD e Micros serviços;
- Ter concluído ou estar cursando T.I ou áreas correlatas ao desenvolvimento de aplicações.

## Local
 Remoto

## Benefícios

Salário: Faixa de R$ 2.000 a R$ 4.000,00
- Auxílio Home Office;
- Vale alimentação ou refeição;
- Plano de Saúde e Odontológico.

## Contratação
 CLT ou PJ - com negociação no fechamento da proposta

## Como se candidatar: 
https://novarerh.selecty.com.br/vaga/122/vaga-para-desenvolvedor-a-web-fullstack-c-e-angular-jr

https://api.whatsapp.com/send?l=pt_BR&phone=5511946717642

### Nível
- Estagiário
- Júnior
- Pleno

### Regime
- PJ
- CLT

### Alocação
- Remoto

## Nosso Cliente:
A Korp é uma empresa especializada no desenvolvimento de sistemas ERP e CRM, ambos atendem as necessidades das indústrias e empresas de distribuição. O ViaSoft Korp ERP, desenvolvido por programadores em conjunto com engenheiros de produção, proporciona recursos sofisticados de análises e simulações em tempo real. Assim, as empresas conseguem romper limites com o poder da tecnologia.
Já o O Korp CRM chegou no mercado como uma força de vendas. O sistema de gestão comercial e relacionamento com o cliente auxilia os negócios a impulsionarem seus resultados.

**Comment by CarlosHenriqueRC** [comment]
É sério isto ?
******************************************
* Carlos Henrique Ramos Carvalho
* Analista de Sistemas Sênior
* MCP.Net, CSD
******************************************


Em qui., 28 de set. de 2023 às 12:24, Novare RH ***@***.***>
escreveu:
