### ISSUE TITLE
[Remoto] Back-end developer .net - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#11207]
## Nexmuv

Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Desenvolvedor .net 
- Ampla experiência com .Net, .Net Core, Entity Framework;
- Pelo menos 2 anos de experiência no desenvolvimento de Frontend utilizando REACTJS ou NEXTJS;
- Experiência em equipe SCRUM.
- Ter experiência sólida com testes unitários e mocks.
- Ter uma boa visão sobre infraestrutura de T.I
- Experiência com banco de dados sendo criação de tabelas (Modelo Relacional), procedures, functions, views e tunning.
Ter um conhecimento mínimo sobre banco de dados NOSQL (MongoDB, MariaDB e etc).
Inglês avançado

## Jundiaí 
Obs.: Atuação em modelo remoto, mas precisa ir a unidade da empresa apenas para a inclusão e retirada de equipamento. 

## Requisitos
Ampla experiência com .Net, .Net Core, Entity Framework;
- Experiência no desenvolvimento de Frontend utilizando REACTJS ou NEXTJS;
- Experiência em equipe SCRUM.
- Ter experiência sólida com testes unitários e mocks.

## Contratação

PJ 

## Como se candidatar

Enviar CV atualizado para natalia.xavier@nexmuv.com.br

### Nível

- Pleno
- Sênior
- 
### Regime

- PJ
- CLT
- Contrato
- Freelance

### Alocação

- Remoto

**Comment by rms-diego** [comment]
Enviado!
