### ISSUE TITLE
[REMOTO] Desenvolvedor Back-end PL - Solfácil

### ISSUE THREAD

**Issue by flaviareisf** [backend-br/vagas#11200]
**VAGA ENCERRADA EM 11/10.**

## Sobre a Solfácil:
**Empoderar as pessoas através do Sol,
Esse é o nosso propósito!**

Não somos um banco, não instalamos placas solares e nem somos apenas uma das maiores fintechs do Brasil. Somos um ecossistema líder em soluções para o mercado de energia solar. E também somos apaixonados por esse mercado e todas as suas possibilidades.

Todos os dias, buscamos dar autonomia para que cada um seja dono da sua própria energia, tornando cada vez maior o acesso a essa fonte de energia limpa, renovável e inesgotável.

Fazemos parte do mercado que cresce 150% ao ano. Um mercado que pode gerar uma economia imediata de até 95% na conta de luz. No último ano, o mercado de energia solar ajudou a recolher mais de 17 mil toneladas de CO2 que seriam lançados na atmosfera. O mesmo que 60 mil árvores fariam em 20 anos.

## Descrição da vaga
Atuar no processo de desenvolvimento de software;
Atuar em componentes com alta complexidade;
Atuar com autonomia;
Colabora com processos, métricas e artefatos que aumentam a efetividade operacional e governança do time e mitigar riscos ao colocar software em produção;
Participa de processos de definição de caminhos para minimizar riscos no processo de implantação nos ambientes;
Disseminar para o time as lições aprendidas em tratamentos de problemas;
Desejável: Buscar proativamente críticas construtivas sobre design/arquitetura técnica de membros da equipe e também de outras equipes;
Entendimento do escopo de novas features, conseguindo executar o trabalho com pouca supervisão.

## Requisitos
Experiência comprovada em desenvolvimento de aplicativos web usando Python;
Conhecimento de frameworks web Python, como FastApi;
Conhecimento em CI/CD, Postgresql, MongoDB e Kubernetes;
Conhecimento em back-end com bancos de dados e APIs RESTful;
Experiência em implementar testes de unidade e integração;
Habilidade em trabalhar em equipe e resolver problemas técnicos.

## Benefícios

- Cartão de benefícios Caju - para comer bem! Pode usar em restaurantes, mercados, padarias, etc., é só passar tudo no crédito;
- Plano de saúde e odonto Sulamérica - excelentes clínicas e hospitais;
- Plano de Educação - para você se desenvolver ainda mais;
- Plano de bem-estar VidaLink - subsídio para saúde mental e subsídio em medicamentos;
- Presente de aniversário no saldo livre do Caju;
- Convênio com Gympass;
- Auxílio Creche;
- Vale Transporte;
- No dress code, você pode se vestir como preferir!;
- Fácil acesso - estamos em Pinheiros (São Paulo/SP) ao lado da estação Faria Lima.

## Nível
- Pleno

## Local
Remoto 

## Como se candidatar
Acesse o link e se cadastre!
https://solfacil.gupy.io/jobs/5365739

## Contratação
Remoto - CLT

**Comment by jppradoleal** [comment]
As vagas já foram encerradas

**Comment by flaviareisf** [comment]
Olá @jppradoleal, foram encerradas hoje. Vou atualizar aqui. Obrigada!
