### ISSUE TITLE
[Remoto] Java Developer (Sênior) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11216]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedora-java-senior-home-office-131050650?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Nossa principal necessidade é que tenhamos profissionais com Skill em JAVA, SPRING BOOT, REST, DOCKER e KAFKA.</p>
<p>A Flexdoc é uma empresa sediada em Brasília/DF, com atuação nacional, focada no desenvolvimento de soluções inovadoras e no fornecimento de serviços técnicos especializados, direcionados para a automação de fluxos de negócios, processamento de dados, e gestão documental, atuando desde a instalação e implantação das tecnologias até produção, digitalização, extração, tramitação, controle e disponibilização da informação com tecnologias no estado-da-arte.</p>
<p></p>
## Flexdoc Tecnologia da Informação: 
 <p>A Flexdoc é uma empresa especializada em automação de processos, validação de dados e documentos, e sistemas de processamento de documentos por imagem, auxiliando os clientes a acelerar o crescimento através da implantação de fluxos inteligentes e gerenciáveis com alto grau de automação e confiabilidade nos dados, documentos e processos.</p>
<p>Com destaque dentro do crescente segmento de Regtechs, a Flexdoc se destaca por oferecer um cardápio modular de produtos e serviços que vão desde o fornecimento de APIs para extração de dados com tecnologia de ponta até o BPO completo incluindo a plataforma de automação de Onboarding e Backoffice digital, análise de fraude, infraestrutura e serviços, permitindo a redução de custos envolvidos nas esteiras digitais.</p><a href='https://coodesh.com/companies/flexdoc-tecnologia-da-informacao'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Spring Boot 
- Rest 
- Docker 
- Kafka
## Local: 
 100% Remoto
## Requisitos: 
 - Sólidos conhecimentos em desenvolvimento JAVA, SPRING BOOT 
- Desejável experiência em React ou Angular 
- Conhecer ferramentas de controle de versão de código (GitHub) 
- Ter atuado com linguagens de programação Web (desenvolvimento Full Stack) e criação de serviços / API 
- Conhecimento desejável com KAKFA E Docker 
- Profissional mínimo 3 anos de experiência, atuará com desenvolvimento de novos projetos e Manutenção

## Benefícios: 
 - VA/VR 
- Plano de Saúde 
- Convenio SESC 
- GYMPASS 
- Seguro de Vida
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Java Developer (Sênior) na Flexdoc Tecnologia da Informação](https://coodesh.com/jobs/desenvolvedora-java-senior-home-office-131050650?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by rms-diego** [comment]
Enviado
