### ISSUE TITLE
[Remoto] Desenvolvedor Pleno/Junior Java - Lacustre

### ISSUE THREAD

**Issue by tnscbv** [backend-br/vagas#11235]
## Nossa empresa

Lacustre is a software house specialized in software development that offers a wide range of services related to information technology. Lacustre plays a fundamental role in creating tailor-made technological solutions to meet the specific needs of its customers.

## Descrição da vaga

Desenvolvedor Pleno/Junior Java Remoto 100%

 DISPONIBILIDADE DE INICIO PRO DIA 1/11/23

Responsabilidades
- Desenvolver, manter aplicações e criar novas funcionalistas para aplicação web utilizando Java;
- Colaborar com membros da equipe para garantir a entrega de software de alta qualidade;
- Escrever código limpo, de fácil manutenção e eficiente;
- Auxiliar na manutenção do código e adição de novos serviços ao sistema.

Qualificações
- Proficiência na linguagem de programação Java, incluindo versões mais antigas;
- Conhecimentos com MySQL, Tomcat, Maven e Apache
- Experiência de nível Pleno/Sênior;
- Disponibilidade full-time
- Ótimas habilidades de comunicação, trabalho em equipe e análise & resolução de problemas;
- Bom nível de inglês, pelo menos para comunicação escrita;

. #remoto #java #angular #back #front #ingles
## Local

remoto.

## Requisitos

Informe os requisitos obrigatórios e desejáveis para a vaga.

## Contratação

PJ

## Como se candidatar

info@lacustre.tech

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by Weslin-0101** [comment]
Enviei o meu CV

**Comment by paulo-ssantos** [comment]
I am interested and available to start immediately, here is my LinkedIn: https://www.linkedin.com/in/paulo-ssantos/

**Comment by igorpereirag** [comment]
olá, tenho interesse nesta vaga  pois sou compatível ,aqui esta meu linkedln : https://www.linkedin.com/in/igor-pereira-13508822a/

**Comment by roderickli0626** [comment]
Hi
Thanks for your posting.
I'm a Java expert.
[Roderick_Li_Resume.pdf](https://github.com/backend-br/vagas/files/13324164/Roderick_Li_Resume.pdf)
https://github.com/roderickli0626
Please look at my resume and git link.
I want to work with you.
Hope your kind message.
Thanks.
[1.txt](https://github.com/backend-br/vagas/files/13324177/1.txt)

**Comment by vinigg2** [comment]
Essa vaga é fraude
