### ISSUE TITLE
[Híbrido - SP] Desenvolvedor Backend (Java/Camunda) - Triad Integration

### ISSUE THREAD

**Issue by Luiza3004** [backend-br/vagas#11279]
## Nossa empresa

Triad Integration

Nós somos a Triad Integration, empresa brasileira com mais de 25 anos de história. Potencializamos resultados por meio de um ecossistema de soluções e serviços de tecnologia e inteligência de dados que vão do tradicional ao digital.

Transformamos, otimizamos e suportamos o crescimento do negócio e da receita dos nossos clientes, entre eles, gigantes dos setores de Telecomunicações, Manufatura, Finanças, entre outros.

O grupo é composto pela i9Triad, focada em inovação e inteligência de dados, e pelo iTriad, Instituto de Pesquisa e Desenvolvimento responsável pela criação de projetos tecnológicos de P&D, Automação Industrial, Visão Computacional e Indústria 4.0. O Instituto é credenciado pelo Ministério da Ciência, Tecnologia, Inovações e Comunicações (MCTIC), por meio do Comitê das atividades de Pesquisa e Desenvolvimento na Amazônia (CAPDA) e da Coordenadoria de Assistência Técnica Integral (CATI).

## Descrição da vaga

Formação
Superior completo em Tecnologia da Informação, Engenharia da Computação ou áreas relacionadas.

Nível de experiência
Júnior – 1 vaga
Pleno – 2 vagas
Sênior – 3 vagas

Setor
TI/Telecom

## Local
Hibrido em SP (Vila Olímpia)
Estudamos a possibilidade de atuação home office

## Requisitos

Requisitos e Responsabilidades

Desenvolvimento de Microserviços:
– Projetar, desenvolver e manter microserviços escaláveis e eficientes

– Colaborar com arquitetos de software para garantir a integração adequada dos serviços.

Arquitetura Orientada a Eventos:
– Implementar e otimizar sistemas baseados em eventos para garantir alta disponibilidade e escalabilidade.

Infraestrutura Cloud:
– Trabalhar em estreita colaboração com as equipes de DevOps para implementar e manter soluções em ambientes de nuvem, preferencialmente AWS ou Azure.

Processos de Teste e Automação:
– Desenvolver e implementar estratégias abrangentes de teste.

BPMN e/ou Camunda:
– Utilizar expertise em BPMN e/ou Camunda para projetar e implementar processos de negócios eficientes e automatizados.

## Benefícios

Sem Benefícios

## Contratação

PJ

## Como se candidatar

Interessados no perfil da vaga, se inscrever pelo site ou enviar currículo com pretensão salarial e título da vaga para luiza.longo@triadintegration.com.br ou https://www.triadintegration.com.br/desenvolvedor-java-camunda/

### Nível

- Júnior
- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto
- Híbrido

**Comment by Mardoqueu** [comment]
se é híbrido não deveria ter a label Remoto

**Comment by Luiza3004** [comment]
Tenho vaga híbrida e remota

**Comment by Mardoqueu** [comment]
> Tenho vaga híbrida e remota

Show! Encaminhei o curriculo
