### ISSUE TITLE
[100% REMOTO] Node.js + Angular - Desenvolvimento Ninja

### ISSUE THREAD

**Issue by samuelfaj** [backend-br/vagas#11272]
Localização: 100% Remoto
Tipo de Contrato: R$ 10 a R$ 17 mil / mês - PJ

**Descrição da Empresa:**

Somos a Desenvolvimento Ninja, uma empresa jovem e dinâmica no ramo de desenvolvimento de softwares e soluções SaaS. Embora ainda pequenos, já estamos bem posicionados no mercado e em uma fase empolgante de crescimento e aprimoramento contínuo.
Aqui, você terá a liberdade e a confiança para inovar e aplicar as melhores práticas de programação. Valorizamos a autonomia e incentivamos nossos colaboradores a trazer novas ideias e soluções criativas para a mesa. Estamos sempre em busca de melhorar a qualidade do nosso trabalho e expandir nossos horizontes.

**Descrição da Vaga:**

Estamos em busca de um(a) Desenvolvedor(a) Full Stack talentoso(a) para se juntar à nossa equipe. Você trabalhará utilizando Node.js e Angular. Esta é uma excelente oportunidade para quem deseja crescer profissionalmente, enquanto trabalha em um ambiente ágil e colaborativo.

**Responsabilidades:**

Desenvolver e manter aplicações web de alto desempenho usando Node.js e Angular.
Colaborar com a equipe de suporte / diretoria para definir, projetar e entregar novas funcionalidades.
Garantir a qualidade do código e a robustez das aplicações através de testes e revisões de código.
Contribuir com ideias para novos recursos e melhorias, adotando uma abordagem proativa para resolver problemas.

**Qualificações Necessárias:**

- Domínio em Node.js: Procuramos alguém que seja craque em Node.js, capaz de construir e otimizar aplicações robustas e eficientes. Se você tem aquele conhecimento técnico avançado e prática comprovada, é exatamente o que precisamos.
- Expertise em Angular: Precisamos de um profissional com habilidades sólidas em Angular, capaz de criar interfaces dinâmicas e integrar com eficiência ao back-end. Se Angular é a sua praia e você sabe tudo sobre criar experiências de usuário incríveis, queremos você no nosso time.
- Experiência com MySQL: Essencial ter experiência com bancos de dados MySQL, entendendo como estruturar, consultar e otimizar dados. Se você sabe como tirar o melhor proveito do MySQL em ambientes de produção, isso será um grande diferencial.
Controle de Versão com Git: Proficiência no uso de sistemas de controle de versão, para colaboração em código e gerenciamento de versões.
- Gestão de tempo de produtiva
- Responsabilidade e habilidades de autogestão; 
- Vontade de aprender coisas novas todos os dias;
- Habilidade de relacionamento interpessoal para trabalho em equipe. 

**Diferenciais:**

- Familiaridade com práticas de DevOps e ferramentas de CI/CD.
- Experiência com frameworks adicionais como React ou Vue.js.
- Contribuições em projetos de código aberto.
- Conhecimento em tecnologias de contêineres, como Docker e Kubernetes.

**Oferecemos:**

Ambiente flexível e orientado a entregas.
Oportunidades de desenvolvimento profissional e crescimento.
Cultura inovadora e projetos desafiadores.

**Para se inscrever para a vaga preencha**: https://forms.gle/8yMfgAnzb3HsqwCi8

**Comment by alvinscheibe** [comment]
🤙🏻

**Comment by danieldfc** [comment]
enviado :+1:
