### ISSUE TITLE
[São Paulo/SP] Analista de Sistemas PHP

### ISSUE THREAD

**Issue by T2Tech-Jobs** [backend-br/vagas#1127]
Principais atividades

Desenvolver melhorias e projetos para áreas atendidas pelo squad, participar ativamente dos projetos e dinâmicas de técnicas ágeis.

Desejável

• PostgreSQL;
• PHP 7.2 avançado;
• API Rest;
• Nginx;
• DynamoDB;
• Symfony;
• Conhecimento em Métodos Ágeis.

Requisitos

• Experiência com projetos complexos em PHP.
• Ensino superior completo ou cursando.

A oportunidade é CLT + Benefícios.
Horário flexível.  

Se você gosta de ambiente dinâmico e possui um perfil determinado, movido a resultados, buscando sempre garantir uma entrega com autonomia e excelência, envie seu CV atualizado e pretensão salarial para rh@t2tech.com.br

**Comment by THAYLLER** [comment]
é vaga somente alocado? Em que cidade é?

**Comment by T2Tech-Jobs** [comment]
A vaga é CLT. A empresa fica em São Paulo/ SP, em Pinheiros.

**Comment by THAYLLER** [comment]
Entendi que pena a vaga é muito massa se eu tivesse condição de ir pra sp tentar a vaga ia se legal, vlw por responder

**Comment by T2Tech-Jobs** [comment]
@THAYLLER ah! que pena. Onde você reside? Nos envie seu CV mesmo assim! Nosso quadro de vagas atualiza semanalmente. Abs.

**Comment by THAYLLER** [comment]
Sou de Franca interior de SP na situação que me encontro não tenho financeiro para me mudar para uma cidade com um custo de vida tão alto, ate atendo as skills solicitadas na vaga, trabalho com php a mais de 4 anos
