### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby - Pleno ou Sênior

### ISSUE THREAD

**Issue by speedio-atlas** [backend-br/vagas#1128]
**Speedio** 
-Rua Pamplona, 1197 - Jardim Paulista, São Paulo - SP, 01405-001, Brazil

DESCRIÇÃO DA VAGA
Atividades e Responsabilidades
Liderar nosso time de desenvolvimento no aperfeiçoamento de bots, controle das nossas automatizações, melhoramento das nossas APIs.

Requisitos
-Não ter formação superior na área de computação É UM PLUS 
-Excelente relacionamento interpessoal 
-Capacidade de Liderança 
-Experiência em liderar time de desenvolvimento 
-Experiência e organização de versionamento e testes 
-Cargo Presencial no Jardim Paulista - 10min do metro TrianonMasp

Responda as perguntas seguintes no e-mail para 'recrutamento1@speediomail.com' :

1- Mora em SP Capital ?
2- Já trabalhou com Multithread e Multiprocess em ruby ?
3- Já trabalhou com quais sistemas de Filas: rabbit,kafka,sidekiq
4- Já trabalhou com Event Based code em vez de Thread based ?
5- Telefone de contato.
6- Email de contato.
7- Nome e idade.

Salário de R$8000,00.

http://speedio.com.br

**Comment by garaujodev** [comment]
Não pude deixar de notar o primeiro requisito, confesso que me deixou bastante surpreso deixar isso explícito(de uma forma boa, claramente). Infelizmente não me adequo a vaga atualmente, comecei com Ruby a pouco tempo, mas vocês teriam outras vagas em aberto?

**Comment by speedio-atlas** [comment]
> Não pude deixar de notar o primeiro requisito, confesso que me deixou bastante surpreso deixar isso explícito(de uma forma boa, claramente). Infelizmente não me adequo a vaga atualmente, comecei com Ruby a pouco tempo, mas vocês teriam outras vagas em aberto?

É uma pena. Se você quiser deixar seu currículo e email conosco, poderemos entrar em contato quando divulgarmos a vaga junior no próximo mês.

**Comment by garaujodev** [comment]
> > Não pude deixar de notar o primeiro requisito, confesso que me deixou bastante surpreso deixar isso explícito(de uma forma boa, claramente). Infelizmente não me adequo a vaga atualmente, comecei com Ruby a pouco tempo, mas vocês teriam outras vagas em aberto?
> 
> É uma pena. Se você quiser deixar seu currículo e email conosco, poderemos entrar em contato quando divulgarmos a vaga junior no próximo mês.

Será um grande prazer. Um grande abraço. Boa sorte com a contratação.
