### ISSUE TITLE
[Remoto] Backend developer (JAVA & NODE) - Datum TI 

### ISSUE THREAD

**Issue by julianakraemer** [backend-br/vagas#11281]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo terceiro ano seguido. Nossa sede fica em Porto Alegre/RS e recentemente chegamos no Canadá

## Descrição da vaga
Atuação com Desenvolvimento focado em BackEnd;

Profissional com autonomia, que foque em entrega e prazo, e peça demandas quando entregar antes;

Gerenciamento de tarefas por metodologias ágeis;

Comprometido com o projeto e o time;

Comunicativo, que goste de trabalhar em time;

Resolutivo;

Proativo e engajado;

Além de experiência técnica, pessoa com senso de responsabilidade, comunicativa, colaborativa e dedicada.

## Local
Remoto

## Requisitos

Experiência comprovada nas tecnologias:
Java;

Node;

Git (Git Flow);

Mongo;

Oracle,

TDD;

HTML 5;

Microsserviços..

Diferenciais:

Desejável experiência em React (Redux, Context e Hooks API);

Desejável Typescript;

Desejável CSS e pré-processadores;

Desejável Vanilla Javascript (ES5, 6, 7, Design Patterns).
## Benefícios

Bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o Open English que oferece 30% de desconto na mensalidade.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!

## Contratação

PJ ou cooperado.

## Como se candidatar

Envie um e-mail para: juliana.kraemer@datum.inf.br ou se inscreva diretamente no link: https://datum.gupy.io/jobs/6179083
### Nível

- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Remoto

**Comment by gvao** [comment]
Enviado

**Comment by smendes23** [comment]
Essa vaga ainda está disponivel?

**Comment by gvao** [comment]
Enviado e-mail com meu currículo.

**Comment by angelobms** [comment]
Currículo enviado! Aguardando retorno.
