### ISSUE TITLE
[REMOTO] PHP Developer Freelancer - The Sign Pack

### ISSUE THREAD

**Issue by RecruiterTSP** [backend-br/vagas#11286]
# Descrição da vaga

A 𝐓𝐡𝐞 𝐒𝐢𝐠𝐧 𝐏𝐚𝐜𝐤 está em busca de Developer PHP Freelancer para se juntar à nossa equipe.
Precisamos de devs freelas para resolver gargalos.
Projetos pequenos em PHP com Framework Laravel dividido em várias sessões. 
Projetos correspondem de R$1.000 a R$2.000 cada.
Quick work, quick cash.
Site de inscrição: https://www.thesignpack.com/jobapplication/

- Desenvolvimento de plataforma web
- Programação em PHP
- Experiência com Framework Laravel
- Conhecimento sólido em Banco de dados MySQL
- Familiaridade com metodologia Scrum
- Proficiência na linguagem PHP, utilizando o Framework Laravel e Banco de dados MySQL
- Uso do sistema Jira para gerenciamento de projetos
- Habilidade em VueJS para o desenvolvimento de interfaces interativas
- Conhecimento específico em Laravel, Eloquent ORM e Blade Engine
- Diferencial: Experiência ou conhecimento em Wordpress

## Local
100% Remoto

## Contratação
Freelance

## Experiência
- Pleno
- Sênior

## Inscreva-se
https://www.thesignpack.com/jobapplication/

**Comment by alvinscheibe** [comment]
👍🏻
