### ISSUE TITLE
[Rio de Janeiro]: À procura de desenvolvedorxs back-end

### ISSUE THREAD

**Issue by caueops** [backend-br/vagas#1129]
## Descrição da vaga

```javascript
Se você >>
    É uma pessoa, acima de tudo!
    É engajada por Qualidade de Software
    Ama codificar
    Curte a cultura de DevOps e Ownership
    Compartilha conhecimento
    Ama tecnologia
    Curte aprender, através de (treinamentos && cursos && eventos && livros)
    É receptiva à feedbacks contínuos
    Gosta de se adaptar à mudanças
    Ama inspirar a transformação positiva na vida das pessoas
>> Continue lendo...
```

O Personare tem um compromisso especial com a diversidade. Nossa equipe é composta por homens e mulheres que abraçam suas diferenças e buscam viver no dia a dia o propósito de inspirar transformação positiva na vida das pessoas. Que tal fazer parte do nosso time? Estamos de portas abertas para desenvolvedoras e desenvolvedores de todo o país!

Estamos começando a expandir os nossos times e precisamos de pessoas que realmente gostam de estar à frente do mercado, aquelas que curtem experimentar novas tecnologias e que estão sempre antenadas ao cenário atual do desenvolvimento de software. 

E se você se interessa em participar da migração de uma arquitetura monolítica para *Headless* utilizando **microsserviços** com o **Design Orientado a Domínio** (DDD) ou até mesmo participar da criação e do desenvolvimento de um novo produto, venha fazer parte do nosso time!

Hey, é contigo mesmo!!! Temos um ambiente de trabalho extremamente leve, divertido e com uma cultura que vai fazer você desafiar o seu próprio status-quo! Que tal experimentar estar neste ambiente e contribuir diariamente com a nossa missão???

A nossa missão é de **inspirar** a transformação positiva na vida das pessoas. ❤️ ❤️ ❤️ 

A maior parte de nossos produtos é construída em PHP e Node.js, mas estamos sempre em busca das ferramentas mais adequadas para resolver os problemas sem nos prendermos a uma tecnologia específica. Utilizamos bastante embasamento técnico e os resultados de nossas PoCs (provas de conceito) nos guiam para as tomadas de decisões.

Gerenciamos nossa infraestrutura através de IaC (Infrastructure as Code) e realizamos a implantação de todas as nossas aplicações na AWS. Durante o processo de migração do monolítico para **microsserviços** estamos focando bastante na qualidade do código construindo uma boa cobertura de testes, tendo um design emergente e um monitoramento da saúde das aplicações de forma ativa.

**Aqui você vai**:
- Colaborar diretamente com product owners, designers, developers e customers para identificar as melhores oportunidades para atender as necessidades de nossos queridos usuários e implementar as soluções.
- Colaborar ativamente no ciclo de melhoria contínua (vulgo Kaizen) para elevar o nível técnico de nossos serviços, microsserviços, ferramentas e produtos.
- Compartilhar o seu conhecimento através de revisões de código, palestras internas, treinamentos e até mesmo uma boa reunião.
- Se envolver na construção de um novo produto do começo ao fim, desde o MVP, design, implementação, deploy, monitoramento de KPIs até o ciclo de feedback.
- Participar de times multidisciplinares e contribuir com a evolução dos mesmos.
- Ajudar a migrar uma arquitetura monolítica para **microsserviços**.
- Programar :octocat:

## Local

Alocadx no escritório: Av. do Pepê, 700 - Barra da Tijuca, Rio de Janeiro - RJ, 22620-170

## Benefícios

- Vale Refeição ou Vale Alimentação (cê que escolhe) de R$30,00/dia útil.
- Participação nos Lucros (Anual).
- Seguro de vida.
- Plano de Saúde (Bradesco).
- Plano Odontológico (Bradesco).
- Licença maternidade e paternidade estendida.

#### Diferenciais

- Cultura de qualidade no fluxo de desenvolvimento (TDD, DDD, Pair Programming, Code Review).
- Treinamentos com especialistas internos e/ou externos.
- Material de suporte aos estudos, como por exemplo: cursos, livros, acesso à plataformas.
- Incentivo à participação de eventos.
- Ciclo de feedback contínuo através de avaliação 360º e 1:1 meetings.
- Sessões de meditação e mindfulness.
- Acesso às análises, cursos, jogos e serviços do Personare.
- Suco verde e frutas de manhã e à tarde.
- Cadeira de massagem.
- Convênio com restaurantes próximos.
- Flexibilidade de horário.

## Requisitos

**Obrigatórios:**
- PHP com um bom conhecimento de Programação Orientada a Objetos (POO).
- Ter experiência ou vontade de trabalhar com testes de unidade e integração.
- Conhecimento com banco de dados relacional (MySQL/PostgreSQL).
- Se importar com a qualidade do código que está fazendo.
- Ter conhecimento de padrões de projeto e saber aplicá-los na prática.
- Fluxo de desenvolvimento utilizando controle de versão (Git de preferência <3).
- Proatividade para resolver problemas e/ou impedimentos do dia a dia.
- Valorizar a agilidade.
- Experiência com setup/tunning do servidor de aplicação NGINX.

**Desejáveis:**
- Experiência com arquitetura de **microsserviços**.
- Ter o conhecimento de técnicas de **refatoração**.
- Conhecimento de operações básicas do Docker (run, stop, rm, kill, pull e push).
- Interesse pelas temáticas do Personare.

**Diferenciais:**
- Experiência com arquitetura *Headless*.
- Experiência com Domain Driven Design (DDD) <3 <3 <3 
- Ter o conhecimento do S.O.L.I.D e conseguir colocá-los em prática. 
- Praticar desenvolvimento guiado por testes (*Test Driven Development*)

## Contratação

CLT

## O Personare

<p align="center">
  <a href="https://www.personare.com.br/" target="_blank">
    <img src="https://user-images.githubusercontent.com/7065285/46258596-e249c980-c4a3-11e8-894c-14381df00fad.png" alt="Pesonare" width="70%">
  </a>
</p> 

O Personare é resultado do trabalho de jovens profissionais de diferentes especialidades, mas com uma mesma motivação: incentivar as pessoas a viverem suas vidas da melhor forma possível. Para isso, oferecemos conteúdos e serviços focados em qualidade de vida e autoconhecimento como: Astrologia, Tarot, Yoga, Meditação, Feng Shui e muitos outros.

Veja alguns bons motivos para se juntar a nós:

1. Inspiramos positivamente a vida de mais de um milhão e meio de pessoas que acessam o Personare todos os meses.

2. Aqui todos têm voz: prezamos que todas as opiniões e ideias sejam ouvidas. Até mesmo (e principalmente) as dos estagiários.

3. Nosso design e comunicação são feitos internamente. Você nunca vai ficar entediado trabalhando em uma empresa que é uma agência ao mesmo tempo.

4. Motivamos a amizade e a colaboração entre a equipe. Isso significa que todos têm boa vontade em explicar, ensinar, compartilhar tarefas e celebrar conquistas.

5. Agimos para que o bem-viver e o autoconhecimento não sejam um discurso somente. Praticamos o que pregamos: possuímos programas que incentivam que nossa equipe melhore sua própria qualidade de vida.

## Como se candidatar

Por favor me mande um sinal de fumaça através do email: queroserdev@personare.com.br com qualquer coisa (GitHub, Código, Projeto, se quiser marcar um café ou uma call)! \o/

## Labels

- Sênior
- Pleno
- CLT

**Comment by eduardojesusdev** [comment]
Enviei um e-mail para você!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
