### ISSUE TITLE
[Faria Lima/SP] Pessoa Desenvolvedora Software Especialista .NET CORE | DQR Tech

### ISSUE THREAD

**Issue by CarolCerqueira** [backend-br/vagas#11296]
**Sobre a DQR TECH | Qualidade do começo ao fim**

A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software.
Desde a concepção e desenvolvimento até a manutenção e sustentação.
Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

**O QUE NOS MOVE:**

Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

**SUAS ATIVIDADES SERÃO:**

- Definir e desenvolver novas soluções para a área de Commodities;
- Desenvolver melhorias e novas funcionalidades em sistemas já existentes;
- Manter um relacionamento próximo com as áreas de negócio;
- Interagir com a área de negócios para compreender problemas e modelar soluções;
- Garantir a alta disponibilidade e performance das plataformas;
- Desenvolvimento de software seguindo metodologias ágeis e utilizando as melhores práticas de orientação a objetos e de clean code.

**O QUE ESPERAMOS QUE VOCÊ SAIBA:**

- Formação superior em Engenharia de Software, Ciências da computação, Desenvolvimento de Sistemas ou áreas relacionadas;
- Conhecimento de programação orientada a objetos e design patterns;
- Conhecimento da linguagem C# – .NET Core, REST API, Dapper e Entity Framework;
- Conhecimento de bancos SQL;
- Conhecimento de computação na nuvem (AWS (S3; CloudFormation; SQS; SNS) / Azure);
- Conhecimento de Front-end – Angular;
- Código limpo, DDD, CI/CD, Git, DevOps, SOLID e metodologias ágeis;
- Habilidade analítica para identificar problemas e propor soluções;
- Habilidade de organização e gestão de tempo para cumprimento dos prazos estipulados;
- Experiência em Mensageria (Azure / AWS) e orquestração de serviços distribuídos;
- Vontade de aprender novas linguagens e tecnologias.
- Acreditamos em usar a melhor ferramenta para resolver cada problema e o aprendizado contínuo não deve ser um empecilho.

**O QUE SERIA LEGAL SE VOCÊ TIVESSE:**

- Atuação com o mercado financeiro;
- Experiência em modelagem de dados em DDD;
- Conhecimento em Arquitetura de Microsserviços.

**DE ONDE VOCÊ VAI TRABALHAR?**

- Presencial na região da Faria Lima – SP.

**O QUE OFERECEMOS PARA VOCÊ?**

- Auxílio alimentação da CAJU;
- Assistência médica e odontológica da Porto Seguro e Medservice gratuita para você (sem coparticipação ou mensalidade),
- Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
- Auxílio Educação Alura;
- Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;
- Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
- Seguro de vida;
- Aqui a sua indicação vale premiação de R$ 1.000,00;
- No mês do seu aniversário tem mimos;
- Notebook para o desempenho das atividades;
- Contrato CLT.

**Todas nossas vagas são destinadas a Pluralidade e Diversidade.**

**ENVIE SEU MATERIAL PARA: vagas@dqrtech.com.br**

![1703025434082](https://github.com/backend-br/vagas/assets/154989598/617121be-4bc1-4dc3-b140-c937f9ed474b)

**Comment by DaianeMFirmiano** [comment]
VEM pra DQR TECH!!!
