### ISSUE TITLE
[Híbrido/Remoto] Back-end developer - Ruby

### ISSUE THREAD

**Issue by 1nChurch** [backend-br/vagas#11305]
**Nossa empresa**
Olá, muito prazer, nós somos a inChurch!
A única plataforma no Brasil de desenvolvimento apps, sites, totens nativos para as igrejas.

**Key Responsabilities**

Resolução de erros do Backend;
Criação de testes unitários;
Participação no desenvolvimento de novas funcionalidades

**Requisitos**
Ter graduação / estar cursando Ciência da Computação, Sistemas de Informação ou áreas relacionadas.
Base (acadêmica) sólida de lógica de programação e algoritmos.
Experiência em desenvolvimento com a linguagem Ruby
Experiência em desenvolvimento com o framework Rails
Conhecimento de testes unitários
Uso de Git para versionamento de código

**Desejável conhecimento em Node.js**

**Local**
Remoto/Híbrido 

**Contratação**
PJ.

**Como se candidatar**

https://inchurch.vagas.solides.com.br/vaga/337752

**Labels**
Nível
Pleno

**Remuneração**
Pretensão salarial

**Comment by devXela** [comment]
Up?

Att,

Alex Rosa Santos Barbosa
Desenvolvedor


Em ter., 2 de jan. de 2024 às 15:34, 1nChurch ***@***.***>
escreveu:

**Comment by 1nChurch** [comment]
Alex, se identificou? Se inscreve no link https://inchurch.vagas.solides.com.br/vaga/337752

Boa Sorte!!!

**Comment by devXela** [comment]
A vaga é híbrida ou remota?
Caso seja híbrida não teria disponibilidade. Resido atualmente na Bahia

Att,

Alex Rosa Santos Barbosa
Desenvolvedor


Em ter., 2 de jan. de 2024 às 18:05, 1nChurch ***@***.***>
escreveu:

**Comment by 1nChurch** [comment]
Oi Alex, bom dia!

Híbrido para quem é do RJ e remoto para fora do RJ.

Abraço,

Em ter., 2 de jan. de 2024 às 18:08, Alex Rosa Santos Barbosa <
***@***.***> escreveu:

**Comment by devXela** [comment]
Bom dia!
Ótimo! Indo me candidatar.
Obrigado pela atenção.

Att,

Alex Rosa Santos Barbosa
Desenvolvedor


Em qua., 3 de jan. de 2024 às 08:34, 1nChurch ***@***.***>
escreveu:

**Comment by nelsonmfinda** [comment]
@1nChurch aceita candidato de outro país?

**Comment by eduardoksa** [comment]
Opa, tenho interesse, porém esse link não está funcionando. Como faço pra me candidatar a vaga?

**Comment by 1nChurch** [comment]
> Opa, tenho interesse, porém esse link não está funcionando. Como faço pra me candidatar a vaga?

Acabamos de preenchê-la.... mas não deixe de seguir a gente! Sempre estamos abrindo novas vagas.

**Comment by 1nChurch** [comment]
> Opa, tenho interesse, porém esse link não está funcionando. Como faço pra me candidatar a vaga?

Acabamos de preenchê-la.... mas não deixe de seguir a gente! Sempre estamos abrindo novas vagas.
