### ISSUE TITLE
[Remoto] Back-end Developer Sênior na Justiça 4.0 (PNUD/ONU e CNJ)

### ISSUE THREAD

**Issue by ericageo** [backend-br/vagas#11308]
## Sobre o programa

[Justiça 4.0](https://www.cnj.jus.br/tecnologia-da-informacao-e-comunicacao/justica-4-0/) é um dos maiores programas do mundo de transformação digital do Poder Judiciário. Iniciada em 2020, fruto de um acordo de cooperação firmado entre o Conselho Nacional de Justiça (CNJ) e o Programa das Nações Unidas para o Desenvolvimento (PNUD/ONU), a iniciativa visa desenvolver e aprimorar soluções tecnológicas para tornar os serviços oferecidos pela Justiça brasileira mais eficientes, eficazes e acessíveis à população, além de otimizar a gestão processual para magistrados, servidores, advogados e outros atores do sistema de Justiça. A iniciativa também dialoga com os Objetivos de Desenvolvimento Sustentável e com a Agenda 2030 da ONU.

**Este processo seletivo busca contratar 18 analistas – pessoas desenvolvedoras back-end, de nível sênior, para trabalhar remotamente, a partir de qualquer localidade do país.** **Inscrições abertas até 18/01/2024.**

## Descrição da vaga

- Modelar requisitos e artefatos utilizando diagramas da UML, bem como elaborar textos, relatórios, ofícios e outros documentos necessários ao desenvolvimento de artefatos de software ou à realização de outras atividades do projeto;
- Desenvolver artefatos de software necessários ao atendimento dos requisitos funcionais e não funcionais das soluções cujas entregas estão previstas no Eixo 1 do projeto;
- Empregar a linguagem de programação Java e o framework Spring Boot no desenvolvimento de artefatos de backend e desenvolver artefatos de testes automatizados;
- Subsidiar o(a) Gerente de Projeto e demais integrantes do time nas ações de planejamento e implementação do projeto, contribuindo para a definição e priorização do backlog do produto, do cronograma de projeto, dos backlogs de sprints e na realização de cerimônias e outros artefatos que venham a ser necessários; atuando nas atividades de implantação, monitoramento da execução e suporte técnico e das soluções desenvolvidas; 
- Desenvolver artefatos de software necessários ao atendimento dos requisitos funcionais e não funcionais das soluções cujas entregas estão previstas no Eixo 1 do projeto;
- Empregar a linguagem de programação Java e o framework Spring Boot no desenvolvimento de artefatos de backend; e apoiar o desenvolvimento de soluções estruturantes da Plataforma Digital do Poder Judiciário Nacional; bem como desenvolver soluções técnicas para suportar outros serviços a serem desenvolvidos no contexto do projeto; 
- Realizar outras tarefas, conforme demanda do supervisor designado;
- O titular desempenha outras funções dentro do seu perfil funcional que considere necessárias ao bom funcionamento do Gabinete e da Organização.

## Local

- 100% remoto

## Requisitos

**Obrigatórios:**

- Graduação universitária (Bacharelado) em Tecnologia da Informação, Ciência da Computação, Sistemas de Informação, Engenharia de Software, Análise de Sistemas, Engenharia da Computação, ou áreas relacionadas com mínimo de 2 anos de experiência com desenvolvimento de softwares ou de atuação profissional ou acadêmica na área de tecnologia da informação;
- Ou diploma universitário avançado (Mestrado ou equivalente) nas áreas de Tecnologia da Informação, Ciência da Computação, Sistemas de Informação, Engenharia de Software, Análise de Sistemas, Engenharia da Computação ou áreas afins.
- Habilidade de comunicação oral e escrita.

**Desejáveis:**

- Experiência no framework Spring Boot; 
- Experiência em outras linguagens de programação: Python ou JavaScript; 
- Experiência com o desenvolvimento de artefatos de backend, em especial APIs RESTful; 
- Experiência na construção de microsserviços;
- Experiência no desenvolvimento de soluções baseadas em containers; 
- Experiência em métodos ágeis;
- Experiência no uso de ferramentas de gestão de código fonte: Git, GitLab, GitHub e congêneres; 
- Experiência na utilização de ferramentas de gerência do ciclo de vida de projetos, como Jira, Bugzilla, Rubicon, e congêneres;  
- Experiência anterior no desenvolvimento de soluções para o Poder Judiciário também será considerada.

**Diferenciais:**

- Certificação na linguagem de programação Java;
- Proficiência em Inglês.

## Contratação

A modalidade de contratação é NPSA (National Personnel Services Agreement), que representa um instrumento próprio do PNUD utilizado internacionalmente para padronizar e viabilizar a admissão de profissionais especializados, por tempo determinado. Essa modalidade assegura benefícios como seguro saúde, seguro de vida e férias.

## Como se candidatar

O processo seletivo é realizado por meio da plataforma de Oportunidades do PNUD. [Inscrições até 18/01/2024: clique aqui para acessar a plataforma e o detalhamento completo desta oportunidade.](https://bit.ly/vaga-pnud-backend-sr)

### Nível

- Sênior
- Especialista

**Comment by victorbiasibetti** [comment]
no site diz que é Brasilia

**Comment by ericageo** [comment]
> no site diz que é Brasilia

Olá, Victor, obrigada pela mensagem. A indicação da localidade na plataforma do PNUD diz respeito ao escritório responsável pela vaga, mas, como indicado no título [Analista Desenvolvedor Backend Senior (Home Based)] e na própria descrição do anúncio, a posição é 100% remota.

**Comment by victorbiasibetti** [comment]
@ericageo as vagas de frontend no site estao abertas tb?

**Comment by ericageo** [comment]
> @ericageo as vagas de frontend no site estao abertas tb?

Sim! Além destas [18 vagas para back-end sênior](https://bit.ly/vaga-pnud-backend-sr), o programa Justiça 4.0 abriu [8 vagas para front-end sênior](https://bit.ly/vaga-pnud-frontend-sr) e [2 vagas para devops](https://bit.ly/cnj-devops-senior). Todas são remotas!

**Comment by everjava** [comment]
qual o valor dos honorários ?  nessa modalidade de contratação qtos % se paga de IR ?

**Comment by ericageo** [comment]
> qual o valor dos honorários ? nessa modalidade de contratação qtos % se paga de IR ?

Obrigado pela mensagem. Os detalhes da contratação e remuneração são apresentados ao candidato no decorrer do processo seletivo.

**Comment by ghost** [comment]
Como funciona esse processo ? preenchi aquele formulário do site mas nunca recebo nada sobre o processo. @ericageo

**Comment by ericageo** [comment]
> Como funciona esse processo ? preenchi aquele formulário do site mas nunca recebo nada sobre o processo. @ericageo

Após o término do período de inscrições, todas as candidaturas são avaliadas. Aquelas que apresentarem maior adequação são convocadas para a segunda etapa, de entrevista. A terceira e última fase do processo seletivo consiste na checagem das referências profissionais fornecidas. Todos os contatos são realizados através do e-mail cadastrado no início do processo.

**Comment by everjava** [comment]
esse contrato é prorrogado após o periodo de 6 meses definido no edital da vaga ?

**Comment by ericageo** [comment]
> esse contrato é prorrogado após o periodo de 6 meses definido no edital da vaga ?

Olá! Há possibilidade de continuidade do projeto e prorrogação do contrato, sim.
