### ISSUE TITLE
[Remoto] Software Engineering Manager I (Back End Python) - Loggi

### ISSUE THREAD

**Issue by Franciellidns** [backend-br/vagas#11306]
## Nossa empresa

**Vamos falar sobre a Loggi? 💙**
Somos uma empresa de tecnologia que está reinventando a logística e a forma de fazer entregas no Brasil. Queremos empoderar pessoas e transformar negócios com entregas de excelência. Movimentamos mais de 400 mil pacotes por dia com uma tecnologia de ponta a ponta, que aproxima todos os cantos do país.

Temos o propósito de que as entregas sejam acessíveis para todas as pessoas do Brasil. Esse é nosso desafio diário, por isso buscamos inovação em tudo que fazemos.

Por aqui, valorizamos diferentes formas de pensar, pois sabemos que só assim poderemos criar um futuro mais democrático para as pessoas.

**Nossa Cultura**
Nossa cultura é traduzida todos os dias pelos comportamentos de cada Logger e das experiências que construímos com os nossos clientes e sociedade.
Nossos valores são como um guia de como as pessoas devem se comportar diante das pequenas e grandes atitudes que são tomadas no nosso ambiente de trabalho todos os dias.

Contamos com quatro valores e 12 princípios. São eles:

Criamos o futuro

- Agimos com propósito

- Respiramos tecnologia

- Somos pessoas inconformadas

Entregamos soluções simples

- Partimos do cliente

- Entregamos com foco

- Buscamos eficiência operacional

Comunicamos abertamente

- Usamos dados com profundidade

- Respeitamos opiniões diferentes

- Somos responsáveis pelas nossas ações

Vivemos o diferente

- Contratamos com diversidade

- Nos conectamos pela empatia

- Somos pessoas curiosas

**Nosso time de Engenharia**
As equipes de Engenharia da Loggi são apaixonadas por desafios e buscam escalar um negócio transformador em um ambiente de constante aprendizado, tendo como compromisso a excelência para criar sistemas e otimizar processos, construindo assim uma plataforma de logística eficiente e inovadora. Nossos desafios são de alta complexidade, mesclando profissionais experientes e em início de carreira, em um ambiente fortalecido pelo aprendizado e compartilhamento de experiências.

Usamos tecnologia para resolver problemas de eficiência e operacionalização, além de produzirmos uma solução de coletas e entregas dinâmica e única. Temos também desafios em maximizar o sucesso de entrega e construir mecanismos de pagamento justos aos nossos entregadores.

Atualmente em back end usamos python/django; kotlin/micronaut; modelos de machine learning treinados com SKLearn e Keras/Tensorflow/Jax; aplicativos móveis híbridos e PWAs; algoritmos de otimização e nossas próprias soluções proprietárias. Também contamos com implantações de Istio/K8s no Azure e AWS. Para dados em geral, contamos com Looker, ELK e Grafana.

Junte-se a nós e faça parte da equipe que está democratizando a logística e conectando o Brasil, proporcionando uma experiência de entrega excepcional aos clientes.

## Descrição da vaga

Você irá arquitetar e desenvolver soluções escaláveis de alta qualidade, fazendo parte de squads multidisciplinares que buscam uma experiência incrível e eficiente para os usuários;
Como foco técnico de um time, contaremos com você no desenvolvimento de ideias e soluções que resolvam problemas complexos e consigam ótimos resultados para a equipe;
A equipe de engenharia da Loggi trabalha com uma ampla variedade de tecnologias e técnicas para resolver nossos desafios. Tentamos ver além dos padrões para desenvolver software de forma pragmática e eficiente;

## Local

Remoto 

## Requisitos

- Conhecimento e experiência prática em React Native e desenvolvimento nativo para Android e iOS.
- Habilidades em linguagens de programação específicas para mobile, como Java/Kotlin para Android e Swift/Objective-C para iOS.
- Fortes habilidades de comunicação, liderança e gestão de equipe.
- Familiaridade com metodologias ágeis.
- Autonomia, capacidade analítica, capacidade de resolução de problemas apoiada nas melhores práticas de codificação;
- Experiência trabalhando de forma colaborativa, com outros engenheiros, gerentes de produto e designers.

## Benefícios

- Vale refeição no cartão Flash;
- Vale Transfer no cartão Flash (apenas para trabalho presencial);
- Auxílio Home Office;
- Assistência Médica - Mensalidade custeada pela Loggi, com coparticipação em exames simples e consultas, inclusive para filhos de até 21 anos (se universitários, até 24);
- Plano Odontológico - 100% custeado pela Loggi, inclusive para filhos de até 21 anos (se universitários, até 24);
- Seguro de Vida pela SulAmérica Seguros;
- Auxílio creche para filhos com até 5 anos;
- Incentivo para desenvolvimento técnico anual;
- Gympass para desconto em academias;
- Parcerias Loggi: Zenclub, Edupass, Funcional Card;
- Loggi 4 free - 4 entregas grátis por mês;
- Empréstimo consignado (elegível após 3 meses de casa);
- Licença maternidade/paternidade de 6 meses para mães e 20 dias para pais;
- Elegibilidade para remuneração variável de curto e longo prazo.

## Contratação

CLT

## Como se candidatar

https://apply.workable.com/loggi/j/51314AA9A8/

### Nível

- Especialista
- Gerente

### Regime

- CLT

### Alocação

- Remoto

**Comment by ericjmachado** [comment]
A vaga descrita no link e para React Native @Franciellidns
