### ISSUE TITLE
[Indaial/SC] Desenvolvedor PHP na UNIASSELVI

### ISSUE THREAD

**Issue by emmerson** [backend-br/vagas#1130]
### **Sobre a UNIASSELVI**

Com 268 mil alunos em cursos de graduação e pós-graduação presenciais e a distância, a UNIASSELVI é a maior instituição privada de ensino superior de Santa Catarina e uma das maiores do Brasil. No momento, a UNIASSELVI está presente em todas as regiões do país, com mais de 400 polos EAD e 12 unidades próprias de ensino presencial.

### **Local**

Trabalho presencial na unidade de Indaial/SC.

### **Benefícios**

- Bolsa Educação
- Plano de Saúde
- Plano Odontológico
- Vale Alimentação ou Refeição
- Vale Transporte
- Convênio SESC
- Convênio Farmácias
- Seguro de Vida
- Biblioteca UNIASSELVI
- Descontos em produtos e serviços de diversos parceiros

### **Contratação**
CLT

### **Desafio**

- Desenvolvimento e manutenção de projetos WEB em PHP/Oracle/Node. 
- Propor soluções e desenvolver melhorias no atual sistema e futuras aplicações.

### **Principais atividades**

- Projetar sistemas e aplicações, através das informações fornecidas pela área interna, desenvolvendo o layout de telas e relatórios, definindo os critérios ergonômicos, de navegação com base no manual de identidade visual da empresa, interface de comunicação e interatividade, modelando a estrutura do banco de dados.
- Implementar e corrigir possíveis erros e não conformidade nos sistemas, apresentando soluções que atendam às necessidades indicadas pelos sistemas.
- Realizar testes e simulações em condições operacionais simuladas, aferindo os resultados, monitorando o desempenho e a performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessário.
- Monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessários.
- Efetuar a homologação do sistema e aplicação junto a clientes, treinando usuários, verificando resultados obtidos e avaliando objetivos e metas do projeto, a fim de garantir que esteja dentro do que foi previamente estabelecido.
- Realizar controle de versão do sistema, utilizando as ferramentas apropriadas para este fim.

### **Requisitos**

- PHP
- Banco de dados / SQL
- Git
- Html/CSS/JS

### **Diferencial**

- NodeJs
- Oracle
- PL/SQL
- Git Flow
- Laravel ou Symfony
- MongoDB
- PostgreSQL
- Ionic

### **Como se candidatar**
Enviar um e-mail para [emmerson.becker@uniasselvi.com.br](url) com seu currículo anexado, enviar no assunto: Vaga Desenvolvedor PHP.

### **Alocação**
Presencial
### **Regime**
CLT

**Comment by emmerson** [comment]
Gostou dessa vaga? Possui alguma dúvida? Deixe seu comentário.

**Comment by emmerson** [comment]
### **Sobre a UNIASSELVI**

Com 268 mil alunos em cursos de graduação e pós-graduação presenciais e a distância, a UNIASSELVI é a maior instituição privada de ensino superior de Santa Catarina e uma das maiores do Brasil. No momento, a UNIASSELVI está presente em todas as regiões do país, com mais de 400 polos EAD e 12 unidades próprias de ensino presencial.

### **Local**

Trabalho presencial na unidade de Indaial/SC.

### **Benefícios**

- Bolsa Educação
- Plano de Saúde
- Plano Odontológico
- Vale Alimentação ou Refeição
- Vale Transporte
- Convênio SESC
- Convênio Farmácias
- Seguro de Vida
- Biblioteca UNIASSELVI
- Descontos em produtos e serviços de diversos parceiros

### **Contratação**
CLT

### **Desafio**

- Desenvolvimento e manutenção de projetos WEB em PHP/Oracle/Node. 
- Propor soluções e desenvolver melhorias no atual sistema e futuras aplicações.

### **Principais atividades**

- Projetar sistemas e aplicações, através das informações fornecidas pela área interna, desenvolvendo o layout de telas e relatórios, definindo os critérios ergonômicos, de navegação com base no manual de identidade visual da empresa, interface de comunicação e interatividade, modelando a estrutura do banco de dados.
- Implementar e corrigir possíveis erros e não conformidade nos sistemas, apresentando soluções que atendam às necessidades indicadas pelos sistemas.
- Realizar testes e simulações em condições operacionais simuladas, aferindo os resultados, monitorando o desempenho e a performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessário.
- Monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessários.
- Efetuar a homologação do sistema e aplicação junto a clientes, treinando usuários, verificando resultados obtidos e avaliando objetivos e metas do projeto, a fim de garantir que esteja dentro do que foi previamente estabelecido.
- Realizar controle de versão do sistema, utilizando as ferramentas apropriadas para este fim.

### **Requisitos**

- PHP
- Banco de dados / SQL
- Git
- Html/CSS/JS

### **Diferencial**

- NodeJs
- Oracle
- PL/SQL
- Git Flow
- Laravel ou Symfony
- MongoDB
- PostgreSQL
- Ionic

### **Como se candidatar**
Enviar um e-mail para [emmerson.becker@uniasselvi.com.br](url) com seu currículo anexado, enviar no assunto: Vaga Desenvolvedor PHP.

### **Alocação**
Presencial
### **Regime**
CLT

**Comment by emmerson** [comment]
### **Sobre a UNIASSELVI**

Com 268 mil alunos em cursos de graduação e pós-graduação presenciais e a distância, a UNIASSELVI é a maior instituição privada de ensino superior de Santa Catarina e uma das maiores do Brasil. No momento, a UNIASSELVI está presente em todas as regiões do país, com mais de 400 polos EAD e 12 unidades próprias de ensino presencial.

### **Local**

Trabalho presencial na unidade de Indaial/SC.

### **Benefícios**

- Bolsa Educação
- Plano de Saúde
- Plano Odontológico
- Vale Alimentação ou Refeição
- Vale Transporte
- Convênio SESC
- Convênio Farmácias
- Seguro de Vida
- Biblioteca UNIASSELVI
- Descontos em produtos e serviços de diversos parceiros

### **Contratação**
CLT

### **Desafio**

- Desenvolvimento e manutenção de projetos WEB em PHP/Oracle/Node. 
- Propor soluções e desenvolver melhorias no atual sistema e futuras aplicações.

### **Principais atividades**

- Projetar sistemas e aplicações, através das informações fornecidas pela área interna, desenvolvendo o layout de telas e relatórios, definindo os critérios ergonômicos, de navegação com base no manual de identidade visual da empresa, interface de comunicação e interatividade, modelando a estrutura do banco de dados.
- Implementar e corrigir possíveis erros e não conformidade nos sistemas, apresentando soluções que atendam às necessidades indicadas pelos sistemas.
- Realizar testes e simulações em condições operacionais simuladas, aferindo os resultados, monitorando o desempenho e a performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessário.
- Monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas, oferecendo o suporte técnico quando necessários.
- Efetuar a homologação do sistema e aplicação junto a clientes, treinando usuários, verificando resultados obtidos e avaliando objetivos e metas do projeto, a fim de garantir que esteja dentro do que foi previamente estabelecido.
- Realizar controle de versão do sistema, utilizando as ferramentas apropriadas para este fim.

### **Requisitos**

- PHP
- Banco de dados / SQL
- Git
- Html/CSS/JS

### **Diferencial**

- NodeJs
- Oracle
- PL/SQL
- Git Flow
- Laravel ou Symfony
- MongoDB
- PostgreSQL
- Ionic

### **Como se candidatar**
Enviar um e-mail para [emmerson.becker@uniasselvi.com.br](url) com seu currículo anexado, enviar no assunto: Vaga Desenvolvedor PHP.

### **Alocação**
Presencial
### **Regime**
CLT

**Comment by roberto0arruda** [comment]
Boa noite, sou acadêmico finalista do curso de Análise e desenvolvimento de sistemas no polo de Manaus e gostaria de me candidatar a vaga.
Alguma objeção?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by emmerson** [comment]
Nenhuma. Por gentileza verifique o item como se candidatar, aguardo seu
currículo!

--

Emmerson Ribeiro Becker



Em sex, 14 de jun de 2019 às 23:58, Roberto Arruda <notifications@github.com>
escreveu:

**Comment by roberto0arruda** [comment]
@emmerson , obrigado, currículo enviado ;-)
