### ISSUE TITLE
[Hibrido / Maringá, Paraná, Brazil] PHP Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11312]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-php-110921351?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos buscando <strong>PHP Developer </strong>para compor nosso time!</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver novos sistemas</li>
<li>Resolver problemas de software</li>
<li>Escrever código de qualidade clara para software e aplicações e efetuar revisões de testes</li>
<li>Desenvolver, implementar e testar APIs</li>
<li>Contribuir para projetos de desenvolvimento de software</li>
<li>O candidato ideal será responsável criação de novos sistemas, manutenção e updates dos sistemas atuais.</li>
<li>O candidato será responsável pela equipe.</li>
<li>O candidato deverá identificar erros.</li>
<li>Também prestará apoio aos outros devs, resolvendo quaisquer problemas de software.</li>
</ul>
## LS Tech Solution ltda: 
 <p>A startup é uma empresa de desenvolvimento de sistemas, nossos clientes são internacionais e utilizam os nossos aplicativos para trabalhar.</p>
<p>A companhia tem apenas 2 anos e já estamos presentes em 4 países e com mais de 10 mil clientes.</p><a href='https://coodesh.com/companies/ls-tech-solution-ltda'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- API 
- Scraping 
- MySQL
## Local: 
 Maringá, Paraná, Brazil
## Requisitos: 
 - O candidato deverá ser especialista em PHP 
- Ter conhecimento em API's, Scraping de dados e mySQL.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [PHP Developer na LS Tech Solution ltda](https://coodesh.com/jobs/desenvolvedor-php-110921351?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Back-End

**Comment by heygon** [comment]
CV enviado!
