### ISSUE TITLE
[Remota] - Java Full Stack Developer - Artemis Corporation

### ISSUE THREAD

**Issue by mwseraphim0** [backend-br/vagas#11316]
## Nossa empresa

Na Artemis Corporation, somos especialistas na fusão de marketing digital e desenvolvimento de softwares. Com uma equipe de profissionais dedicados e apaixonados, oferecemos soluções inovadoras que aliam estratégias de marketing de ponta a tecnologias de software avançadas. Nossa missão é conectar marcas ao seu público-alvo de maneira significativa, usando as mais recentes ferramentas e abordagens digitais. Nós nos orgulhamos de transformar ideias em realidade, garantindo que nossos clientes alcancem resultados excepcionais e uma presença online notável.

## Descrição da vaga

Projeto em desenvolvimento utilizando Java, Spring Boot, Node, Mysql, Mongo e WebSocket seguindo o front com Angular como tecnologia principal.

## Local

Remoto

## Requisitos
Criação de microservices utilizando spring boot, Java 11+ e integração com WebSocket.
Desenvolver aplicativos da Web utilizando Angular 14+, CSS3, HTML5, Typescript.
Conhecimento de integração de API's Rest.

###Diferenciais:

Conhecimento em NodeJS

## Contratação

PJ ou outra.

## Como se candidatar

Envie o curriculo para michael@artemiscorporation.com.br com a pretensão salarial desejada

## Labels

JAVA, NODE, ANGULAR, SPRING

### Nível

- Júnior
- Pleno

### Regime

- PJ
- Freelance

### Alocação

- Remoto

**Comment by astriel-git** [comment]
Ainda está aberta essa vaga?

**Comment by mwseraphim0** [comment]
Sim ainda esta

**Comment by mwseraphim0** [comment]
> Ainda está aberta essa vaga?

Sim ainda esta
