### ISSUE TITLE
[Alocação] Back-end developer -Hepta Tecnologia 

### ISSUE THREAD

**Issue by GitMateusBruno** [backend-br/vagas#11310]
## Nossa empresa

Somos a Hepta tecnologia; empresa sediada em Brasília com 31 anos de atuação. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

 .NET (C#) OU React (JavaScript or TypeScript)

## Local

Remoto

## Requisitos

- Cinco (05) anos de experiência como DEV. (Necessário comprovar)

- Formação Superior completa em TI (Necessário comprovar)

- Certificação em: Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD)

Para o perfil Sênior desejável mais uma em: PSM I, II ou III. Ou CSM; Ou SMC; Ou ASM. (P/ atuar como Scrum Master)
Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.

- IMPORTANTE:
A Hepta presta serviço p/ instituições federais, as exigências que você leu sobre comprovação de experiência, formação superior em TI e certificação são exigências do edital e nós precisamos cumprir.

## Benefícios

- Plano de saúde
- Plano odontológico
- VR ou VA de R$ 21.59/Dia
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para [mateus.sousa@hepta.com.br](mailto:mateus.sousa@hepta.com.br) com seu CV anexado - enviar no assunto: Vaga GIT

### Nível

- Pleno
- Sênior

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by JIFerreira01** [comment]
Ta exigindo comprovacao, mas estao pagando quanto?

**Comment by GitMateusBruno** [comment]
@JIFerreira01 Podemos falar sobre isso no privado, o que acha? Manda um e-mail com seu CV.

**Comment by brenoassp** [comment]
Por favor, não use a tag PJ se a vaga é CLT, isso atrapalha a filtragem.

**Comment by GitMateusBruno** [comment]
Olá amigo, está com a TAG PJ porque conseguimos flexibilizar :)

Em seg., 15 de jan. de 2024 às 09:02, Breno Almeida <
***@***.***> escreveu:
