### ISSUE TITLE
[Remoto] RPA Python Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11325]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-rpa-python-144431381?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Desenvolvimento de automações de processos utilizando a linguagem Python. Entendimento de documentação com o passo a passo para desenvolvimento dos robôs.</p>
<p>Conversar com usuários chaves para entendimento do processo e homologação dos robôs desenvolvidos.</p>
<p>Documentação de código com as atividades desenvolvidas. Ser proativo na busca de soluções de problemas.</p>
## Zummit: 
 <p>Nascemos de gente e gente nos faz.</p>
<p>Gente nos sustenta e nos transforma!</p><a href='https://coodesh.com/companies/zummit'>Veja mais no site</a>

 ## Habilidades: 
 - Python 
- RPA 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Automation Anywhere
## Diferenciais: 
 - UiPath

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [RPA Python Developer na Zummit](https://coodesh.com/jobs/desenvolvedor-rpa-python-144431381?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by devXela** [comment]
Up?

Att,

Alex Rosa Santos Barbosa
Desenvolvedor


Em qui., 29 de fev. de 2024 às 21:56, github-actions[bot] <
***@***.***> escreveu:
