### ISSUE TITLE
[Alocação] Back-end NodeJs developer - 200DEV

### ISSUE THREAD

**Issue by 151209** [backend-br/vagas#11339]
## Nossa empresa

Somos uma consultoria de TI focada em Inovação e Transformação Digital, certificada como “Great Place to Work” atendemos clientes de todos os segmentos e temos parcerias relevantes com fabricantes como IBM, RedHat, Microsoft, Veritas e Pipefy, nosso foco é estabelecer uma parceria forte com o cliente e principalmente com nosso profissional e através de cursos e capacitações promover a carreira. Temos acompanhamento próximo com todos os profissionais. 

## Descrição da vaga

Backend NodeJs Sênior 

## Local
100% Remoto

## Requisitos

NodeJs
Javascript
TypeScript
Conhecimento em Cloud AWS ( RDS, DynamoDB, S3, Api Gateway, Secret Manager, Step Functions, Lambda, SQS, CloudWatch )
IaC
Git / GitFlow
CI e CD com Azure DevOps

## Benefícios

Fornecimento de máquina
Descanso remunerado 
Parceria com Convênio Médico 
Parceria com platarfoma de curso de Inglês 

## Contratação

PJ 

## Como se candidatar

paloma.oliveira@200dev.com

### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by tarciosillva** [comment]
Enviado!

**Comment by danieldfc** [comment]
Enviado

**Comment by rogerinn** [comment]
Enviado.
