### ISSUE TITLE
[REMOTO] WordPress Developer Senior

### ISSUE THREAD

**Issue by SebastianStifler** [backend-br/vagas#11330]
**Descrição da vaga**
Estamos em busca de um Desenvolvedor WordPress qualificado, com experiência comprovada em PHP, HTML5, CSS3, JavaScript, e conhecimento avançado em features e plugins de wordpress. É essencial ter habilidade na customização de temas e plugins, além de experiência com ferramentas de construção de páginas. Conhecimentos em MySQL, otimização de sites para alta performance, segurança web, e práticas de SEO são fundamentais. Apreciaremos experiência com Git, APIs RESTful para integração com outros serviços e sistemas, e um forte entendimento de acessibilidade na web e padrões web.

**Local**
Remoto

**Benefícios**
Salário competitivo
Oportunidades de desenvolvimento profissional em uma startup em crescimento rápido
Ambiente colaborativo e inovador de trabalho remoto
Horário flexível e liberdade de localização
Contrato PJ

**Contratação**
PJ

**Como se candidatar**
Por favor envie um email para [stiflerandballer@gmail.com](mailto:stiflerandballer@gmail.com) com seu CV anexado - enviar no assunto: WordPress Developer Senior

**Alocação**
Remoto

**Regime**
PJ

**Nível**
Sênior
Especialista

**Comment by miguel-henrique** [comment]
Olá, fiz o envio do currículo para o email informado, obg
