### ISSUE TITLE
[Remote] Senior Full-stack/Back-end Engineer - Node.js, TypeScript

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [backend-br/vagas#11338]
USD 7k / month
C1/C2
Node.js
TypeScript
Secondary: SQL
APIs
Minimum: 7 years

- Required:
    - Experience with Node.js and Typescript
    - Deep knowledge of SQL, database structures, HTTP, and API
    - Proficiency in writing clear and efficient SQL queries
    - Experience with B2B US startups
- Nice-to-haves
    - Experience with React.js and Python
    
    Make your registration
    
    https://www.linkedin.com/safety/go?url=http%3A%2F%2Fapp.onstrider.com%2Fr%2Fclaudiaantunes%3Fjob%3Dc2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItcmVhY3QuanMtbm9kZS5qcy10eXBlc2NyaXB0LXN0cmlkZXItZWIwMGY5ZjE%2FcmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM%3D&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-YzEzZTZmMDItZTQzMS00MGFlLTgyODktODJhYWJkNzgxYzlmXzAxMw%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging_conversation_detail%3B%2Bf29FITERRe4WBLH0f5ErQ%3D%3D

**Comment by marciosouzajunior** [comment]
Parece que o link não funciona: "Page not found".

**Comment by Claudiaantunesdelima** [comment]
Olá


app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItcmVhY3QuanMtbm9kZS5qcy10eXBlc2NyaXB0LXN0cmlkZXItZWIwMGY5ZjE/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=


________________________________
