### ISSUE TITLE
[Remote] Junior Engineer na Alternative Payments, inglês para conversação opcional

### ISSUE THREAD

**Issue by fernandobandeira** [backend-br/vagas#11343]
## Nossa empresa

Somos um payment processor, atuamos nos EUA, no ramo de pagamentos B2B, com o foco em transacoes online, transferencias bancarias, processamento de cartoes, financiamento, entre outras modalidades.

Time de produto totalmente Brasileiro com cerca de 14 pessoas, a empresa tem umas 26 pessoas no total.

Mais infos no nosso site: https://alternativepayments.io/

## Descrição da vaga

We're seeking a motivated and skilled junior engineer to join our team. This role presents an exciting opportunity to work on various projects, where you'll be expected to handle a majority of small tasks independently with minimal guidance. As a junior engineer, you'll have the chance to apply your existing experience and knowledge while gaining exposure to new technologies and practices. While no specific degree is required, candidates with relevant coursework or degrees are highly encouraged to apply.

## Local

100% Remoto

## Requisitos

- Some experience in software development, preferably in a professional or academic setting.
- Ability to handle small tasks independently with minimal guidance.
- Strong problem-solving skills and attention to detail.
- Familiarity with Golang and React/Next.js is a plus.
- Enthusiasm for learning and adapting to new technologies and practices.

### Responsabilidades

- Independently tackle small tasks and contribute to larger projects under the guidance of experienced team members.
- Collaborate with cross-functional teams to deliver high-quality software solutions.
- Participate in code reviews and provide constructive feedback to peers.
- Continuously expand your skill set and knowledge base through self-learning and participation in team activities.

## Contratação

PJ, remuneracao varia com a senioridade, no caso de um junior: $4.5k USD/month, intern $3k USD/month

## Como se candidatar

Pode se candidatar para esta e outras vagas na nossa pagina de carreiras: https://www.careers-page.com/alternative-payments
So vamos aceitar aplicacoes feitas em ingles

### Nível

- Estagiário
- Júnior

### Regime

- PJ

### Alocação

- Remoto

**Comment by tanukesensei** [comment]
Enviado!

**Comment by yurecouto** [comment]
Applied!

**Comment by knands42** [comment]
Applied! 👍🏼

**Comment by eng-gabrielscardoso** [comment]
Applied 😃

**Comment by Dnuns** [comment]
Applied

**Comment by DevdouglasGfs** [comment]
Applied! : )

**Comment by Icarus09** [comment]
Applied!

**Comment by valajr** [comment]
Applied! 👍

**Comment by velrino** [comment]
Applied!

**Comment by plinioSMoraes** [comment]
Applied!

**Comment by IamNatri** [comment]
Applied!

**Comment by padilhagodinho** [comment]
Applied

**Comment by Matheus-HMPaiva** [comment]
Applied.

**Comment by astriel-git** [comment]
Applied

**Comment by devCaiquedePaula** [comment]
Applied.

**Comment by jordanmaramos** [comment]
Applied!

**Comment by Gabrielm3** [comment]
Applied! 👍

**Comment by ItaloCovas** [comment]
Applied. Thanks for the opportunity :)
