### ISSUE TITLE
[Remote] Mid-Level Engineer na Alternative Payments, inglês para conversação opcional

### ISSUE THREAD

**Issue by fernandobandeira** [backend-br/vagas#11342]
## Nossa empresa

Somos um payment processor, atuamos nos EUA, no ramo de pagamentos B2B, com o foco em transacoes online, transferencias bancarias, processamento de cartoes, financiamento, entre outras modalidades.

Time de produto totalmente Brasileiro com cerca de 14 pessoas, a empresa tem umas 26 pessoas no total.

Mais infos no nosso site: https://alternativepayments.io/

## Descrição da vaga

We're looking for a skilled and experienced mid-level engineer to join our team. As a mid-level engineer, you'll play a key role in our projects, demonstrating the ability to work on any task independently while also providing guidance and support to junior team members. This position offers an excellent opportunity to leverage your expertise and take on challenging tasks, contributing to the success of our projects and the growth of our team.

## Local

100% Remoto

## Requisitos

- Several years of experience in software development, with a strong track record of delivering high-quality solutions.
- Proficiency in handling any task independently, with minimal guidance.
- Demonstrated expertise in Golang and React/Next.js, with the ability to learn new technologies quickly.
- Excellent problem-solving skills and attention to detail.
- Experience mentoring and providing guidance to junior team members.
- Strong communication and collaboration skills.
- Good English proficiency for reading, writing and listening.

### Responsabilidades

- Work on a wide range of tasks, from small fixes to complex feature development, with minimal supervision.
- Provide guidance and support to junior team members, helping them grow and develop their skills.
- Collaborate closely with cross-functional teams to deliver high-quality software solutions that meet business requirements.
- Participate in code reviews, providing feedback and guidance to peers to ensure code quality and maintainability.
- Stay updated on industry trends and best practices, continuously enhancing your skills and knowledge.

## Contratação

PJ, remuneracao varia com a senioridade, no caso de um pleno/mid-level: $6k USD/month, senior $7.5k USD/month

## Como se candidatar

Pode se candidatar para esta e outras vagas na nossa pagina de carreiras: https://www.careers-page.com/alternative-payments
So vamos aceitar aplicacoes feitas em ingles

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Remoto

**Comment by eng-gabrielscardoso** [comment]
Applied 😃
