### ISSUE TITLE
[Híbrido em São Paulo] Back-end developer Java (Pleno ou Sênior) na @DQR Tech

### ISSUE THREAD

**Issue by kerol-barros** [backend-br/vagas#11349]
## **Nossa Empresa**
**Sobre a DQR TECH | Qualidade do começo ao fim**

A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software. Desde a concepção e desenvolvimento até a manutenção e sustentação. Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

**O que nos move:**
Tecnologia & Pessoas! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

## **O seu desafio será:**
Atuar junto à equipe de Desenvolvimento;
Trabalhar com arquitetura orientada a microsserviços e modelo DevOps;
Expandir o pipeline de produtos;
Atuar nos projetos que consistem em aumentar e flexibilizar o negócio;
Monitoramento, performance e manutenção de sistemas em Java e Kotlin.

## **Local**
Híbrido na Faria Lima em SP (3x por semana).

## **Requisitos**
Java 8+
Kotlin
Arquitetura de Microserviços
Conceitos de Spring – Boot, Data, Security
Domínio dos conceitos – SOLID, Design Patterns
Rest – API
Conceitos de Mensageria – Kafka ou RabbitMQ
Ferramentas AWS – S3, Secrets Manager, CloudWatch e CloudFormation
Arquitetura Limpa – Clean Architecture
Ferramentas de Devops – Git, Jenkins, Kubernetes, Datadog, Kibana

## **Benefícios**
🍔 Vale Alimentação/Refeição no Caju, valor de 880,00 reais;
🏥 Plano de Saúde Porto Seguro sem mensalidade e sem coparticipação (metade da mensalidade paga somente para o dependente);
🦷 Plano Odontológico Porto Seguro sem mensalidade ou coparticipação;
🫶🏽 Terapia: parceria com Psicologia Viva;
👨🏻‍🎓 Benefício Educação onde você pode fazer os cursos da Alura ou da Faculdade Descomplica;
💊 Benefício Farmácia – Descontos de 20% a 70% na compra de medicamentos
🥳 Presente de aniversário (Fone Philips);
🚴‍♀️ Auxílio Esporte – Você pratica qualquer modalidade de esporte e te apoiamos;
👶🏼 Auxílio Creche
👨‍👩‍👧‍👦 Seguro de vida
💻 Equipamento de última geração
💰 Crédito consignado com taxas atrativas para te ajudar em uma emergência.

## **Contratação**
CLT

## **Como se candidatar**
Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: [kerolayne.barros@dqrtech.com.br](mailto:kerolayne.barros@dqrtech.com.br) - enviar CV anexo e no assunto colocar: Vaga - Backend Java

### **Nível**
- Pleno
- Sênior
- Especialista

### **Regime**
- CLT

### **Alocação**
- Híbrido

![Java](https://github.com/backend-br/vagas/assets/110194786/cde16857-fe22-4d0b-84d3-3d46538e8dd4)

**Comment by rogerinn** [comment]
Enviado.
