### ISSUE TITLE
[Remoto] Fullstack TypeScript Engineer @ Constructor 🇺🇸

### ISSUE THREAD

**Issue by pedro-lb** [backend-br/vagas#11345]
## Nossa empresa

[Constructor.io](https://constructor.io) powers product search and discovery for some of the largest retailers in the world. We serve billions of requests every week, and you’ve probably seen our results somewhere and used our product without knowing it. We differentiate ourselves by focusing on metrics over features, and reinventing search and discovery from the ground up as a machine learning challenge with the specific goal of improving metrics like revenue. We’re approximately doubling year over year despite the market slow down and have customers in every eCommerce vertical. We’re a passionate team of technologists who love solving problems and want to make our customers’ and coworkers’ lives better. We value empathy, openness, curiosity, continuous improvement, and are excited by metrics that matter. We believe that empowering everyone in a company to do what they think is best can lead to great things.

## Descrição da vaga

As a Javascript engineer on the Partnerships team, you’ll be working to develop streamlined integrations between Constructor and partner platforms. Your specific responsibilities will include:

- Writing and deploying code across the front and back-end, mainly in JavaScript / TypeScript
- Interfacing with engineering teams at partner companies to develop connecting integrations
- Working with data exposed via interfaces such as REST, GraphQL, FTP, etc.
- Supporting teammates with thorough and thoughtful code reviews
- Influencing the development of new features in our UI and SDK libraries
- Enforcing strong code stability through testing (unit tests, integration tests, etc.)
- Coordinating with other teams to prioritize partnership integrations needs

## Local

- Fully remote. Anywhere on 🌍.

## Requisitos

- **Fluent English**
- A minimum of two years of professional and/or academic experience in software engineering
- Excellent communication and interpersonal skills
- Located in or between GMT-3 and GMT+3 timezones
- Experience architecting efficient server-side applications
- Strong foundation and experience with server-side and client-side JavaScript / TypeScript
- Enjoys interacting with external stakeholders and solving new problems daily
- Able to pick up new technologies, languages and design patterns quickly and love learning them
- (Strong bonus) Experience with data processing pipelines and ETL processes
- (Bonus) Experience with front-end frameworks like React, Vue, Angular, etc.

## Benefícios

- 🏝️ Unlimited vacation time - we strongly encourage all of our employees take at least 3 weeks per year
- 💰 A competitive compensation package including stock options
- 🌎 Fully remote team - choose where you live
- 🛋️ Work from home stipend! We want you to have the resources you need to set up your home office
- 💻 Apple laptops provided for new employees
- 🧑‍🎓 Training and development budget for every employee, refreshed each year
- 👪 Maternity & Paternity leave for qualified employees
- 🧠 Work with smart people who will help you grow and make a meaningful impact

## Contratação

PJ.

## Como se candidatar

Submit your resume via Workable: [link here](https://apply.workable.com/constructor-1/j/95203BF7C1/).

### Nível

- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Remoto

**Comment by marciosouzajunior** [comment]
Applied!

**Comment by FeezyHendrix** [comment]
Applied!

**Comment by velrino** [comment]
Applied!

**Comment by rogerinn** [comment]
Applied
