### ISSUE TITLE
[Remoto] Senior Full Stack Developer na Freatz

### ISSUE THREAD

**Issue by robpaschoal** [backend-br/vagas#11353]
**Descrição da Vaga:**
Buscamos desenvolvedor full-stack sênior para a maior plataforma de Customer Experience focada em Food Service do Brasil

**Requisitos**
Profundo conhecimento em ferramentas de Frontend, Backend e DevOps
Vivência com sistema monolito, Cloud, Design Patterns, Clean Code, Clean Architecture, Sistema de Mensageria, Testes Unitários
Experiência com gestão ágil de projetos e de time (Scrum, Kanban)

**Conhecimentos desejados**
Frontend: React, Webpack
Backend: Django, Docker, Postgres
DevOps: Github Actions, GCP e AWS

**Responsabilidades**
Liderar o time de desenvolvimento, com a definição de features e tasks, assim como correção de código
Hands-on na criação de novos produtos para os diferentes stakeholders.
Definições da arquitetura do sistema.
Garantir o uso boas práticas de segurana e estabilidade na infraestrutura na nuvem

**Diferenciais**
Conhecimento em Ciência de Dados
Ferramentas: Pandas, Python
Responsabilidades: Criação de relatórios (pdf e google slides), criação de modelos, implementação de api para o dashboard

**Alocação:** Remoto
**Tipo de vaga:** Tempo Integral
**Enviar CV para:** roberto@freatz.com

**Comment by victorbiasibetti** [comment]
> **Descrição da Vaga:**
> 
> Buscamos desenvolvedor full-stack sênior para a maior plataforma de Customer Experience focada em Food Service do Brasil
> 
> 
> 
> **Requisitos**
> 
> Profundo conhecimento em ferramentas de Frontend, Backend e DevOps
> 
> Vivência com sistema monolito, Cloud, Design Patterns, Clean Code, Clean Architecture, Sistema de Mensageria, Testes Unitários
> 
> Experiência com gestão ágil de projetos e de time (Scrum, Kanban)
> 
> 
> 
> **Conhecimentos desejados**
> 
> Frontend: React, Webpack
> 
> Backend: Django, Docker, Postgres
> 
> DevOps: Github Actions, GCP e AWS
> 
> 
> 
> **Responsabilidades**
> 
> Liderar o time de desenvolvimento, com a definição de features e tasks, assim como correção de código
> 
> Hands-on na criação de novos produtos para os diferentes stakeholders.
> 
> Definições da arquitetura do sistema.
> 
> Garantir o uso boas práticas de segurana e estabilidade na infraestrutura na nuvem
> 
> 
> 
> **Diferenciais**
> 
> Conhecimento em Ciência de Dados
> 
> Ferramentas: Pandas, Python
> 
> Responsabilidades: Criação de relatórios (pdf e google slides), criação de modelos, implementação de api para o dashboard
> 
> 
> 
> **Alocação:** Remoto
> 
> **Tipo de vaga:** Tempo Integral
> 
> **Enviar CV para:** roberto@freatz.com

*Fullstack* e *profundo conhecimento* na mesma frase?
Ta serto isso?

**Comment by guilherme90** [comment]
Qual a faixa salarial?
