### ISSUE TITLE
[FULLY REMOTE] Java+Kotlin Developer at Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [backend-br/vagas#11357]
## About [Jobsity](https://www.jobsity.com/)💡
We’ve been around for about 10 years. We are a NY based staffing company that works with lots of different clients in the US, Canada and Europe.
Most of our developers, data engineers, and Quality Assurance engineers are located in Latin America, although we have a presence in more than 15 countries.
We have connected more than 400 people with international employment. We focus more on quality and long-term partnerships, between Jobsity, our candidates (you), and our clients. In fact, we only work with the top 3% of talents in LATAM.
As a member of the Jobsity Recruitment team, we are going to work to find you the right position depending on what is important to you.

## Requirements✔

🚘 Advanced English.
🚘 Extensive technical experience centered primarily on backend development.
🚘 Highly proficient in Java development.
🚘 At least 2 years of experience with Kotlin.
🚘 Experience with Microservices projects.
🚘 Hands-on experience working with various databases (DynamoDB, MySql, ElasticSearch) and data pipeline technologies.
🚘 General knowledge of AWS services like S3, SQS, Lambdas, etc..

## Modality
👨‍💻 Fully remote
PS: position available only for engineers located in LATAM 🗺

## Perks that Jobsity offers!💎

🔹15 business days of paid vacation yearly.
🔹3 extra off days per year.
🔹Paid local holidays.
🔹Unlimited PTOs.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Betterfly app (wellness).
🔹Bonuses for referrals and more!

## Type of contract📜

This is a full-time position as contractor🕘
....with USD payment 💰
....long-term relationship 🤝
...within an international team 👩‍💻 👨‍💻
...and working on international client projects! 🌎

## How to apply🤔

- Send an email to [angela.barboza@jobsity.com](mailto:angela.barboza@jobsity.com) with your CV/LinkedIn attached - Send in the subject: Sr. Java+Kotlin Developer - GitHub📧
- Send me a DM on [LinkedIn ](https://www.linkedin.com/in/angela-barboza/)💻

Whatever works best for you!👌

### Seniority
- Senior

**Comment by rogerinn** [comment]
Applied
