### ISSUE TITLE
[Remoto] Senior NodeJs Backend Engineer - Belvo

### ISSUE THREAD

**Issue by evandroguedes-belvo** [backend-br/vagas#11366]
## Nossa empresa

We are Belvo, an open finance API platform with the bold vision of democratizing access to financial services in Latin America. We enable any financial innovator to access and interpret financial data – as well as initiate payments from their end-users accounts. We’re turning the messy complexities of the Latin American financial ecosystem into a modern set of tools to access and interpret data and move money in a seamless and secure way.

We’re a highly-technical, passionate, and driven team. We are more than 130 people, our team currently represents 26 nationalities and we have offices in São Paulo, Mexico City, and Barcelona – while a large portion of us works remotely.

We are tackling a very stimulating problem: connecting fintech innovators with legacy financial infrastructure. We strive to go beyond the limits of what is possible today and to do so in an elegant and developer-first way.

Since starting our adventure in May 2019, we have raised $56m from the leading VC investors globally.

You can read more about our company [here](https://belvo.com/about/) and about our team and culture [here](https://belvo.com/careers/). Also, head to [our blog](https://belvo.com/blog/) for more news about what we’re building and [how we work](https://belvo.com/blog/category/working-belvo/).

## Descrição da vaga

Your opportunity:

Develop and maintain private and public facing APIs considering highly regulated environments in Latin America

Be customer-focused, and think as a user of our APIs. Proactively understand and tackle potential improvements and customer pain points.

Carefully manage API retro compatibility, document API changes, and implement deprecation plans

Build excellent documentation, SDKs, and client libraries. Continuously improve the “developer experience” of Belvo’s platform

Implement automated quality assurance and monitoring modules

Act in a collaborative team with growing challenges and fast development pace to deliver products to several countries

Our tech stack:

We’re building our platform using modern technologies, putting the focus on reliability and long-term maintainability

We primarily use NodeJS on the backend. We use battle-tested technologies such as NestJS

We use Javascript, React.js and Sass on the frontend. We are developing and leveraging our own design system and component library

We run our infrastructure on top of Amazon Web Services, leveraging managed services. We tend to favor the use of managed services wherever possible, in order to focus on our business problems

We observe and monitor our services using Datadog

We follow Continuous Integration and Continuous Delivery best practices

## Local

Remoto

## Requisitos

5+ years of experience as a Software Engineer

Degree in Computer Science or equivalent work experience

Strong experience designing and developing RESTful APIs

Professional experience with NodeJS

In-depth understanding of the async nature of NodeJS and how to get the most out of it

You appreciate good documentation, internal and external.

Detail-oriented developer, coding so others can read and work with your code

Willingness to solve challenging problems

Amazing if:

Fintech and SaaS experience

Past experience with NestJS and ReactJS

Payment products experience (PSE/Debito Automatico - Colombia, SPEI/Domiciliación - México)

Experience building large-scale platforms with a global reach

Knowledge of regulation implementation in Latam (IFPE - Mexico, Open Finance - Brazil)

Relevant programming knowledge in other languages such as Python, Go or Java

## Benefícios

🚀 Stock options (we are all owners and this is very important to us)

📈 Annual company bonus

🔆 Flexible working hours

🔝 Remote friendly

🐶 Pet friendly

🧘🏾‍♀️ Access to mental health service

👩🏻‍⚕️ Health Insurance

🎊 Paid time off on your birthday

🌎 Work from any office

💻 Renew your laptop every 3 years

🙋 Training Budget

😎 Team building events

🙀 Bank holidays swap inside the same month

🔋 Fitness/ wellness stipends

🚀 Yearly offsite

🍒 Fresh fruit every week, all-you-can-drink tea and coffee

🏝 1 week off on your 2-year anniversary

## Contratação

CLT

## Como se candidatar
https://jobs.ashbyhq.com/belvo?utm_source=omvGyKDLqj

### Nível
- Sênior

### Regime
- CLT

### Alocação
- Remoto

**Comment by BrunoMoreno** [comment]
Applied!

**Comment by rogerinn** [comment]
Applied.
