### ISSUE TITLE
[Contratação direta] Software Engineer Sr

### ISSUE THREAD

**Issue by Consultor-Vieira** [backend-br/vagas#11360]
## Nossa empresa
Uma Startup que atua diretamente com Varejo e Tecnologia, presente no mercado há 5 anos e que conta com mais de 300 profissionais que fazem a diferença. Escritório de 3 andares, cultura jovem, sinuca, fliperama..

## Descrição da vaga

- Participar do desenvolvimento de soluções Web e Mobile utilizando Node.JS;
- Trabalhar em colaboração com outros desenvolvedores para construir aplicações de alta qualidade;
- Implementar testes automatizados para garantir a qualidade do código;
- Analisar requisitos e elaborar soluções técnicas para os desafios propostos;
- Participar de reuniões de equipe para discutir e compartilhar ideias.

## Local

**Jornada de trabalho:** híbrido, 3x em por semana no escritório em Higienópolis - SP, por tempo indeterminado. 

## Requisitos

- +4 anos de vivência na área;
- Experiência com Node.JS;
- Experiência com TypeScript;
- Experiência com testes unitários, de integrações e outros;
- Essencial atuações com Clean Code e Clean Architecture;
- Conhecimento em banco de dados NoSQL (MongoDB, Redis, etc);
- Conhecimento em serviços de mensageria (RabbitMQ, Kafka, etc);
- Experiência com ferramentas de versionamento de código (Git, SVN, etc);
- Familiaridade com metodologias ágeis (Scrum, Kanban, etc);
- Habilidade para trabalhar com ambientes dinâmico.

## Benefícios

- Assistência Médica - Porto Seguro (Você e dependentes sem custos);
- Odontológica Porto (sem dependentes);
- VR de 40 por dia;
- Auxílio mobilidade;
- Seguro de vida;
- Terapia - Viva;
- TotalPass;
- 250,00 ao mês em nosso app;
- Licença maternidade e paternidade;
- Auxílio creche;
- Bônus de até 2 salários
- Avaliações de desempenho semestral e evoluções de carreira.

## Contratação

CLT ou PJ (**Salário de R$ 12 a 20k**).

## Como se candidatar

Whatsapp: 11 981357823
Linkedin: linkedin.com/in/consultor-vieira](https://www.linkedin.com/in/consultor-vieira
E-mail: consultor.vieira@outlook.com

### Nível

- Pleno
- Sênior
- Especialista

### Regime

- PJ
- CLT

### Alocação

- Híbrido
- Presencial

**Comment by rogerinn** [comment]
Chamei via wpp.
