### ISSUE TITLE
[Belo Horizonte - Presencial] .NET Back-end Developer Pleno - 7.5k a 11k PJ - Minds Digital 

### ISSUE THREAD

**Issue by Vitor-TI** [backend-br/vagas#11367]
## Nossa empresa

A Minds Digital é uma IDTech especializada em biometria de voz, por meio da nossa inteligência artificial conseguimos autenticar e identificar a sua voz. Com ela as pessoas se tornam únicas, exclusivas e insubstituíveis. Além dessa tecnologia inovadora, trabalhamos também como Outsourcing com a responsabilidade de ajudar desenvolver toda área de TI, com soluções em nuvem para o nosso cliente.

## Descrição da vaga

Como Back-end Developer, você irá atuar em nossa frente de Outsourcing, formado por um time de desenvolvimento que tem o objetivo de trazer soluções para um de nossos principais clientes que possui um sistema de empréstimos. O time atua no modelo presencial no Bairro Savassi em Belo Horizonte/MG no escritório do cliente, desenvolvendo uma relação próxima, colaborativa e de oportunidades de criação e resolução de problemas.

## Local

Atuação no modelo presencial no escritório do cliente no bairro da Savassi/Belo Horizonte.

## Requisitos

Obrigatórios:

.Net Core
Arquitetura Microsserviços
Mensageria (Kafka)
Conhecimento com Kubernetes e Docker
Clean Architecture, SOLID
Metodologias ágeis, Scrum e Kanban

Desejáveis:

Conhecimento com Angular
Inglês Avançado

## Benefícios

Horário Flexível

## Contratação

Proposta inicial entre R$ 7.500,00 e R$ 11.000,00 PJ (A proposta vai depender da experiência e conhecimentos demonstrados durante o processo seletivo. Desta forma, conseguiremos entender melhor como poderá ser sua contribuição aqui. Procure compartilhar o máximo de informações com a gente e, também, nos perguntar tudo o que for importante para você);

## Como se candidatar

Por favor faça o cadastro por este link: https://rh.minds.digital/jobs/detail/pleno-software-engineer-time-de-consultoria-28

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Presencial

### Linguagem 

-.Net Core

**Comment by rogerinn** [comment]
Aplicado.
