### ISSUE TITLE
[Remote] Senior Back-End Engineer - Node.js, Python (Jcal/Strider)

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [backend-br/vagas#11361]
USD 6k / month
Minimum: 5years
B2

- Focus on candidates that have experience with Spark, ETL pipelines, python, data lakes, etc.
- The candidate would be working with the client's data lake platform, building on top of the data platform that the Data Engineers have created.
- The candidate doesn't need to be a data engineer, but we should avoid candidates focused on full-stack development (front-end and web/SQL back-end).

https://app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLW5vZGUtcHl0aG9uLTg5MWUyZjZlP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

**Comment by oransje** [comment]
Hello, I have experience with backend in nodejs and ETL using python, but I don't have 5years experience. Is it possible to lighten this requirement?

**Comment by Claudiaantunesdelima** [comment]
Hi

unfortunately not
________________________________

**Comment by rogerinn** [comment]
Applied
