### ISSUE TITLE
[São Paulo] Backend Developer na [Avec Brasil]

### ISSUE THREAD

**Issue by 20072013** [backend-br/vagas#1136]
Descrição da vaga
Estamos em busca de um Desenvolvedor Backend que tenha uma visão de negócios para planejar novos produtos, melhorar os atuais e propor novas tecnologias e arquiteturas
Local
Escritório, São Paulo - Paulista
Diferenciais
Benefícios como Gympass, descontos em salões parceiros, descontos  em cabeleireiros, barbearia,...
Ambiente dinâmico e com crescimento exponencial;
Muitos desafios e aprendizados;
Cultura de feedback e 1:1;
No dress code;
Sala de “descompressão” com mesa de ping-pong (adoramos organizar campeonatos!) e puffs para dar aquela relaxada após o almoço ;)
...
...
Requisitos
Obrigatórios:
Experiência avançada em Node.js;
Arquitetura de microserviços;
Conhecimento em conceitos de design de APIs;
Visões de web como arquitetura, componentização e soluções para alta performance;
Metodologia Ágil / Scrum;
Experiência no desenvolvimento de TDD e testes unitários
Conhecimentos básicos em Docker;
 
 
 
Diferenciais:
RabbbitMQ, Kubernetes , NestJS e ElasticSearch( Desejável)
Contratação
PJ a combinar
Nossa empresa
Atualmente a Avec possui diversos produtos como um sistema de gestão (PHP/Laravel), um marketplace (React Native), aplicativos personalizados (Angular/Ionic), soluções de pagamento, entre outros. Estamos em busca de um Desenvolvedor Front End que tenha uma visão de negócios para planejar novos produtos, melhorar os atuais e propor novas tecnologias e arquiteturas
Como se candidatar
Por favor envie um email para jacqueline.mello@avecbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Backend.
Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: jacqueline.mello@avecbrasil.com.br

**Comment by brunooomelo** [comment]
Poderia arrumar a descrição. a vaga esta pra backend ou frontend?

>  Estamos em busca de um Desenvolvedor Front End que tenha uma visão de negócios para planejar novos produtos, melhorar os atuais e propor novas tecnologias e arquiteturas
