### ISSUE TITLE
[Remoto] Desenvolvedor Node.js Sênior

### ISSUE THREAD

**Issue by TherecruiterJu** [backend-br/vagas#11371]
Esta é uma vaga de uma empresa parceira ao qual presto consultoria, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Estamos em busca de Desenvolvedor  Node.js Sênior para compor o time!

Responsabilidades e atribuições

O que é necessário para participar desse processo seletivo?
Experiência na linguagem Node.js com express;
Design e documentação de API;
Conhecimento e uso adequado de requisitos de segurança em APIs;
Sólidos conhecimentos de Git;
Sólidos conhecimentos de bancos de dados não relacionais, Mongo DB;
Experiência em microsserviços e arquiteturas corporativas escaláveis;
Realização de testes unitários e integração com ferramentas como Mocha, Chai, etc.;
Sólidos conhecimentos de padrões de projeto.;
Aplicação dos princípios SOLID;
Projeto de testes de carga e E2E;
Experiência trabalhando com metodologias ágeis.

Desejáveis:

Integração de sistemas (Kafka, RabbitMQ, etc.);
Experiência em ferramentas CI/CD como Jenkins, Sonar, Docker/Openshift/Kubernetes;
Conhecimento em plataformas Cloud (GCP/AWS/Azure).

Local:
100% Remoto

Labels
Alocação
Remoto

Regime
CLT
PJ

Envio de CV para [techrecruiterju@gmail.com](mailto:techrecruiterju@gmail.com)

**Comment by rogerinn** [comment]
Enviado.
