### ISSUE TITLE
[VAGA PLENO REMOTO] - Incentive.me 🚀

### ISSUE THREAD

**Issue by NathanFirmo** [backend-br/vagas#11376]
## Nossa missão 🎯

Somos a [Incentive.me](https://incentive.me/) uma Startup que atua no varejo. Nosso objetivo é colocar todos os vendedores a um clique de todas as empresas e engajá-los através de campanhas de incentivo.

## O que valorizamos ⭐

Buscamos pessoas curiosas, proativas e que tenham senso de responsabilidade.

## Principais atividades 🧭

- Criação e manutenção de APIs REST;
- Criação de telas em nossa aplicação web com ReactJS;
- Monitoramento de aplicações no Kubernetes;

## Requisitos essenciais ✏️

- Inglês técnico (não precisa ser fluente);
- Sólido conhecimento em NodeJS, TypeScript, ReactJS;
- Experiência com de bancos relacionais como MySQL;
- Experiência com de bancos não relacionais como MongoDB;
- Noções de CI/CD;
- Experiência com cloud (Azure, AWS ou GCP);
- Experiência com Kubernetes;
- Experiência com testes automatizados;

## Diferenciais 💡

- Conhecimento de API Gateways e autenticação OAuth2;
- Noções de python ou golang;
- Noções de System Design e Arquitetura de Software;

## Contratação

CLT

## Como se candidatar

Interessados, enviar email para [curriculo@incentive.me](mailto:curriculo@incentive.me) com o assunto "Desenv. Pleno ".

### Nível

- Pleno

### Regime

- CLT

### Alocação

- Remoto

**Comment by Darkisda** [comment]
enviado!

**Comment by Cristuker** [comment]
Enviado!
