### ISSUE TITLE
[Híbrido-SP] Fullstack Developer NodeJs/VueJs na @DQRTech

### ISSUE THREAD

**Issue by kerol-barros** [backend-br/vagas#11379]
## **Nossa Empresa**
**Sobre a DQR TECH | Qualidade do começo ao fim**

A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software. Desde a concepção e desenvolvimento até a manutenção e sustentação. Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

**O que nos move:**
Tecnologia & Pessoas! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

## **Local**
Híbrido na Faria Lima em SP (3x por semana).

## **Requisitos**
Experiência em projetos de desenvolvimento de software utilizando NodeJS e VueJS;
Banco de dados MongoDB;
Serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF;
Desenvolvimento de aplicações em nuvem AWS (Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS);

**Diferencial**
Execução de testes unitários;
Metodologia ágil;
Atuação com o mercado financeiro;
Experiência em modelagem de dados em DDD;
Conhecimento em Arquitetura de Microsserviços;

## **Benefícios**
🍔 Vale Alimentação/Refeição no Caju, valor de 880,00 reais;
🏥 Plano de Saúde Porto Seguro sem mensalidade e sem coparticipação (metade da mensalidade paga somente para o dependente);
🦷 Plano Odontológico Porto Seguro sem mensalidade ou coparticipação;
🫶🏽 Terapia: parceria com Psicologia Viva;
👨🏻‍🎓 Benefício Educação onde você pode fazer os cursos da Alura ou da Faculdade Descomplica;
💊 Benefício Farmácia – Descontos de 20% a 70% na compra de medicamentos
🥳 Presente de aniversário (Fone Philips);
🚴‍♀️ Auxílio Esporte – Você pratica qualquer modalidade de esporte e te apoiamos;
👶🏼 Auxílio Creche
👨‍👩‍👧‍👦 Seguro de vida
💻 Equipamento de última geração
💰 Crédito consignado com taxas atrativas para te ajudar em uma emergência.

## **Contratação**
CLT

## **Como se candidatar**
Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: [kerolayne.barros@dqrtech.com.br](mailto:kerolayne.barros@dqrtech.com.br) - enviar CV anexo e no assunto colocar: Vaga - Fullstack NodeJs/VueJs

### **Nível**
- Pleno

### **Regime**
- CLT

### **Alocação**
- Híbrido

![NODE VUE](https://github.com/backend-br/vagas/assets/110194786/a80236ba-263e-4b80-b42f-826aa0e6e1a9)

**Comment by guilherme90** [comment]
Adorei a vaga, pena que é híbrido. :(

**Comment by br-jeff** [comment]
Enviei email, aguardo contato.
