### ISSUE TITLE
[Remoto] Developer Junior Back-end Javascript @ Port Louis

### ISSUE THREAD

**Issue by eduardonoronha** [backend-br/vagas#11388]
## Nossa empresa

A Port Louis possui soluções de RPA para tarefas jurídicas e financeiras. O nosso stack é composto por um front de vue, e o back em node + net core, ambos rodando em AWS.

## Descrição da vaga

Procuramos um dev júnior para crescer junto com a empresa. A atuação inicial será na resolução de bugs e desenvolvimento de pequenos features.

## Local

Remoto ou São Paulo - Jardins.

## Requisitos

Obrigatórios:

    Conhecimento de javascript vanila
    Conhecimento de node e as bibliotecas mais comuns
    Vontade e disposição para aprender e se desenvolver

Desejáveis:

    Conhecimento de banco de dados mysql
    Conhecimento de ferramentas aws - lambda, s3, ...

## Benefícios

Salário compatível com a posição
VR

## Contratação

CLT

## Como se candidatar

Por favor envie um email para [eduardo@portlouis.inf.br](mailto:eduardo@portlouis.inf.br) com seu CV anexado - enviar no assunto: Vaga BackEnd Javascript. Os currículos serão aceitos somente até o dia 22 de março.

## Labels

Alocação
Presencial
Remoto
Experiência
Júnior
Regime
CLT

### Nível

- Júnior

### Regime

- CLT

**Comment by Marcos-PauloR** [comment]
Boa Tarde, Candidatura Enviada!

**Comment by beterrabaA** [comment]
Enviado.

**Comment by gcaldasl** [comment]
Candidatura enviada.

**Comment by FelipeG-Almeida** [comment]
CV Enviado 🫡

**Comment by Pauloo2003** [comment]
Enviado

**Comment by matheudev** [comment]
Enviado.

**Comment by samuelbatista3rios** [comment]
Enviado. 👍🏿

**Comment by tarciosillva** [comment]
Enviado

**Comment by Josenilsonfariasx** [comment]
Enviado😉

**Comment by eduardonoronha** [comment]
Obrigado a todos, o prazo de envio se encerrou hoje.
