### ISSUE TITLE
[São Paulo] Back-End Developer na INTI

### ISSUE THREAD

**Issue by thiageek** [backend-br/vagas#1139]
Procuramos um(a) profissional apaixonado(a) pelo desafio de conectar pessoas e eventos por meio de uma plataforma revolucionária e totalmente transparente. Importante apresentar boa experiência em Node.js e gerenciamento de Cloud Hosts (AWS) Linux. Irá atuar no desenvolvimento de sistemas e integrações em parceria direta com o time de Front-end e demais competências.

## REQUISITOS

- Ter experiência de no mínimo 3 anos com Node.js (JavaScript);
- Saber informar aplicativos em Hostings (AWS);
- Conhecimento intermediário em Linux e configuração do servidor cloud / aplicação;
- Conhecimentos em Apache, NoSql (MongoDB), GIT.

## DIFERENCIAIS

- Experiência em sistemas eCommerce Conhecimento em Docker;
- Conhecimento em DEVOPS

## RESPONSABILIDADES

- Desenvolvimento backend em projetos;
- Ajustes, correções e melhorias em demandas pontuais;
- Contato e resolução direta com o cliente;
- Suporte a demandas internas de integração e automatização;
- Analisar e propor novas facilidades, demandas, projetos;
- Suporte e manutenção de Cloud Hosts (Linux)

## APLICAÇÃO

Envie currículo para thiago@byinti.com

**Comment by alessandroprudencio** [comment]
Sò presencial?

**Comment by thiageek** [comment]
> Sò presencial?

Por enquanto sim Alessandro. =)
