### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack na LECUPON

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1140]
### Sobre a empresa: LECUPON

A LeCupon é um aplicativo gratuito onde você tem desconto na hora em diversas lojas da sua cidade e online.

### Descrição: Ocupações do cargo

Será responsável pelo desenvolvimento back-end de APIs com foco em aplicações mobile, ira participar de reuniões semanais de alinhamento de tarefas.

Auxiliar a especificação de novas funcionalidades dos projetos. Analisar e propor soluções de arquitetura. Analisar a origem de problemas e propor soluções.

### Benefícios

Um ambiente extremamente descontraído, de hierarquia totalmente horizontal.

Uma cultura animal!

No dress code
Horario Flexivel

### Aptidões e qualidades

Para se juntar ao time é necessário que você seja fera em:

JavaScript,
Tenha noções de Ruby Ruby on Rails
Experiência no design de APIs RESTful
Banco de dados (MySQL, MariaDB ou Postgree)
Git

**Mas se você souber:**

Experiência com TDD e também de implementação de testes em projetos legados; Experiência em front-end
Deploy de aplicações em ambiente cloud (AWS)
Inglês para leitura

### Informações da empresa

LeCupon é um aplicativo gratuito onde você tem desconto na hora em diversas lojas da sua cidade e online.

Contamos com vários parceiros online e offline, estamos crescendo cada vez mais e em busca de uma pessoa desenvolvedora pra fazer parte deste time em crescimento gigantesco.

### Candidatar: http://bit.ly/lecupon_fullstack

**Comment by ericjmachado** [comment]
Remoto?

**Comment by megandavulpi** [comment]
> Remoto?

Presencial!
