### ISSUE TITLE
[Remoto] Backend Node.js Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11406]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/backend-nodejs-developer-183054832?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos uma startup inovadora que fornece soluções de software de atendimento por videochamadas para grandes clientes, incluindo bancos, seguradoras e redes de universidades.</p>
<p>Estamos à procura de um Desenvolvedor Back End. Node.js para se juntar à nossa equipe e construir conosco uma tecnologia inovadora ao lado de profissionais dedicados e um ambiente leve e desafiador.</p>
<p><strong>Você será responsável por:</strong></p>
<ul>
<li>Planejar soluções, desenvolver e supervisionar o código das aplicações;</li>
<li>Ter iniciativa na definição e proposição das melhores soluções para o produto;</li>
<li>Propor e contribuir com novos padrões de desenvolvimento;</li>
<li>Prezar pela qualidade do código desenvolvido e padrões definidos;</li>
<li>Realizar correção de bugs e ajustes necessários para o correto funcionamento e escalabilidade dos sistemas;</li>
<li>Compreender as regras de negócio, propor melhorias e implementá-las com boa qualidade técnica e confiabilidade;</li>
<li>Zelar por todo o processo de desenvolvimento definido pelo time e pela área;</li>
<li>Participar na análise e elaboração dos artefatos de arquitetura dos projetos;</li>
<li>Implementar, incentivar e supervisionar a ampliação dos testes funcionais;</li>
<li>Atuar na disseminação de conhecimento entre seus pares;</li>
<li>Realizar revisão de código e auxiliar na definição de critérios de aceitação;</li>
</ul>
<p></p>
## NuVidio: 
 <p>As videochamadas já vinham apresentando grande crescimento e massificação do uso há alguns anos. Agora com a pandemia e o isolamento social tudo se acelerou, conversar por vídeo deixou de ser uma atividade corporativa e se tornou “mainstream”.&nbsp;</p>
<p>Com o mesmo impulso, o e-commerce se expande como nunca e está tomando o mercado das vendas físicas. Além disso, as pessoas, cada vez mais sozinhas, passaram a valorizar mais as interações humanas.</p><a href='https://coodesh.com/companies/nuvidio'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- Typescript 
- Javascript 
- MongoDB 
- Rest API 
- WebSockets 
- AWS 
- NoSQL 
- GIT 
- Docker
## Local: 
 100% Remoto
## Requisitos: 
 - Proficiência em linguagem de programação Javascript (NodeJs/Typescript); 
- Experiência com banco de dados não relacional: MongoDB; 
- Experiência recente com Docker e Docker Compose; 
- Experiência com Git e Github; 
- Experiência com metodologias ágeis; 
- Experiência recente com integração e documentação de APIs; 
- Experiência com processamento assíncrono: jobs, filas, mensageria; 
- Conhecimento sólido de lógica de programação; 
- Conhecimento avançado sobre algoritmos e estruturas de dados; 
- Conhecimento de plataformas de computação distribuída: AWS; 
- Experiência com revisão de código; 
- Conhecimento boas práticas de desenvolvimento; 
- Conhecimento sólido de segurança web (programação defensiva); 
- Inglês técnico (leitura e escrita código e compreensão de documentações).
## Diferenciais: 
 - Conhecimento de padrões arquiteturais: MVC, Microservice etc.; 
- Experiência com AWS: S3, EC2, ECS etc.; 
- Experiência com automação de análise de código: SonarQube; 
- Experiência com ferramentas de gestão de desenvolvimento; 
- Experiência com ferramentas de monitoramento de software; 
- Experiência com banco de dados relacional; 
- Conhecimento de automação operacional: CI/CD, Infra as Code; 
- Experiência na criação de soluções escaláveis / serviços com grande concorrência;
## Benefícios: 
 - Participação ativa no desenvolvimento de soluções tecnológicas de ponta. 
- Ambiente de trabalho colaborativo e criativo, onde suas ideias e contribuições são valorizadas. 
- Possibilidade de crescimento junto com a startup 
- Totalmente home-office;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Node.js Developer na NuVidio](https://coodesh.com/jobs/backend-nodejs-developer-183054832?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Back-End

**Comment by Josenilsonfariasx** [comment]
candidatura feita 🙃
