### ISSUE TITLE
[Remote] Mid Back-end Developer - Scratch Financial (US)

### ISSUE THREAD

**Issue by lucas-barbosa** [backend-br/vagas#11403]
**TL-DR:**
A empresa que trabalho está com uma vaga aberta para Node.JS. A empresa é bastante organizada, muito flexível, pode trabalhar no seu próprio horário, tendo apenas uma reunião diária para acompanhamento do progresso. 
Não precisa ser fluente no inglês, precisa conseguir se comunicar.
Trabalho há 7 meses lá e tem sido minha melhor experiência de longe!

## Nossa empresa

Scratch Financial ("Scratchpay") is a financial technology startup based in Los Angeles, California. Our goal is to make difficult financial decisions simple and increase accessibility to fair, affordable, and transparent medical financing. Driven by our award-winning technology, Scratchpay has become the fastest growing financing provider in veterinary care, with our payment plans now offered in over 10,000 practices across the U.S. and Canada–ranging from dental offices to optometry clinics. We’re rapidly launching a new Point-of-Sale payment processing suite to help our providers create a better payments experience for their patients.

If putting compassion first, helping create groundbreaking products and continuously iterating & refining those products sound like you, then we encourage you to apply.

## Descrição da vaga

We’re looking for a [Node.js](http://node.js/) Developer to join the engineering team at Scratchpay. The ideal candidate will be well experienced in developing backend applications using [Node.js](http://node.js/) and different database systems, passionate for creating new and innovative products and solutions that meet the client’s needs. The ideal candidate will be someone that is innovative, adaptable to changing priorities, a system thinker, and able to learn new things while striving to deliver high quality code in collaboration with their team.

You will be responsible for designing and developing back end web applications, testing your solutions, and ensuring their ongoing responsiveness.

## Local

Remoto from **anywhere**!

## Requisitos

- At least 4 years of experience in backend or full-stack software development with [Node.js](http://node.js/) and JavaScript or TypeScript.
- Deep understanding of Object Oriented Programming and Test Driven Development, and other development patterns.
- Strong knowledge of both relational databases such as MySQL or PostgreSQL, and global scale distributed NoSQL databases such as FireStore.
- Experience with microservice based architectures.
- Experience and confidence developing high performance RESTful and GraphQL APIs and applications.
- Ability to switch between languages and frameworks as needed.
- Knowing what Agile and Scrum are.
- Nice to have: knowledge of C#, Python, Go, Google Cloud, CI/CD, Docker and Kubernetes.
- Nice to have: Experience in building payment solutions.
- Nice to have: Experience in the financial industry.

## Benefícios

$60,000 - $90,000 a year
- The base pay actually offered will take into account internal equity and also may vary depending on the candidate’s geographic region, job-related knowledge, skills, and experience, among other factors.
- In addition to a competitive base pay, employees in this role may be eligible for equity compensation.

## Contratação

Contractor

## Como se candidatar

https://jobs.lever.co/scratchfinancial/599b146e-6751-4ed9-b1dd-3eb53d52b14f?lever-via=ht8JnGs6pz&lever-social=job_site

### Nível

- Pleno
- Sênior

### Regime

- Contrato

### Alocação

- Remoto

**Comment by ejklock** [comment]
Me inscrevi se puder recomendar. Qualquer coisa envio no email o currículo. Grato

**Comment by Cristuker** [comment]
Apliquei! To na procura de vagas na gringa

**Comment by alvarosw** [comment]
apliquei! se tiver como, dá uma força aí pfv
