### ISSUE TITLE
[Remoto] BackEnd Developer Júnior na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11418]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-back-end-junior-175253174?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<ul>
<li>Executar as boas práticas de desenvolvimento de integrações entre sistemas;</li>
<li>Validar as novas funcionalidades das aplicações;</li>
<li>Realizar os testes de integração nas aplicações;</li>
<li>Manter os padrões de projetos existentes e sugerir melhorias.</li>
</ul>
<p></p>
## Digiage: 
 <p>Vamos dar um rolê pelo que a gente faz? 🚀</p>
<p>1. Inovação e Qualidade:&nbsp;</p><a href='https://coodesh.com/companies/digiage'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- API 
- AWS 
- Azure 
- GitLab 
- Microservices 
- Spring Boot 
- Metodologias ágeis 
- Jenkins 
- XML
## Local: 
 100% Remoto
## Requisitos: 
 - Superior completo em Ciência da Computação, Sistemas de Informação, TI e áreas afins; 
- Conhecimento em linguagem de desenvolvimento Java ou outra compatível com Java 8 ou superior; 
- Conhecimento em desenvolvimento de integrações com APIs SOAP, JSON, XML e REST; 
- Conhecimento de orquestradores (Docker/Kubernetes); 
- Experiência em implementação de Cloud Pública Azure e/ou AWS; 
- Experiência com repositórios de código (GitLab); 
- Conhecimento de ferramentas de CI/CD (Jenkins); 
- Experiência implementando builds automáticos e release pipelines; 
- Conhecimento e experiência de trabalho com metodologias ágeis; 
- Conhecimentos com Spring-boot / MicroServiços Rest;
## Diferenciais: 
 - Conhecimentos em ferramenta de API Gateway e API Management; 
- Conhecimentos com Ferramentas de mensagens: RabbitMQ e Kafka; 
- Conhecimento em Stack Web: JBOSS, NodeJS, Load Balancer (HA-PROXY ou similar); 
- Certificação AZure, AWS ou WSO2;

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [BackEnd Developer Júnior na Digiage](https://coodesh.com/jobs/desenvolvedor-back-end-junior-175253174?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by ocsoares** [comment]
CV Enviado !

**Comment by MateusLeviDev** [comment]
Opa, tenho interesse! Enviarei o cv
