### ISSUE TITLE
[REMOTO] Jr Node.JS developer - WeDoRemotely

### ISSUE THREAD

**Issue by glhrme** [backend-br/vagas#11413]
## Nossa empresa

A We Do Remotely é especializada em soluções sob demanda, com foco em fornecer produtos personalizados que atendem às necessidades exclusivas de cada cliente. Com uma abordagem inovadora e orientada para resultados, estamos transformando ideias em realidade digital.

## Descrição da vaga

Este é um cargo remoto por contrato para um Desenvolvedor Node Jr. Como Desenvolvedor Node Jr., você será responsável pelas tarefas diárias de desenvolvimento e manutenção de aplicações Node.js, colaborando com a equipe para solucionar e depurar problemas, e apoiando o desenvolvimento de novos recursos e aprimoramentos.

## Local

Remoto

## Requisitos

- Conhecimento em programação Node.js e JavaScript
- Conhecimento em APIs RESTful e serviços web
- Familiaridade com sistemas de banco de dados relacionais
- Capacidade de trabalhar de forma independente e remotamente
- Cursando Ciência da Computação ou área relacionada
- Conhecimento com sistemas de controle de versão (por exemplo, Git)

## Contratação

PJ, CLT ou Contrato

## Como se candidatar

Cv em fechado com assunto  Node JS - Nome

### Nível

- Estagiário
- Júnior

### Regime

- Contrato (estag)
-  PJ
- CLT

### Alocação

- Remoto

**Comment by Marcos-PauloR** [comment]
Candidatura enviada!

**Comment by David-Marcoss** [comment]
Candidatura enviada!

**Comment by Zattrus** [comment]
Candidatura enviada!

**Comment by JMustang** [comment]
Opa, é nois!

**Comment by yonathan-uchoa** [comment]
Candidatura enviada!

**Comment by glhrme** [comment]
Estou avaliando e respondendo as candidaturas.

Devido ter recebido vários e-mails, encerrei a vaga por aqui e irei seguir com os atuais candidatos.

**Comment by BambamRR** [comment]
OPa, a vaga já foi preenchida? Vou enviar meu CV
