### ISSUE TITLE
[Remoto] C# Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11436]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/dev-c-134409889?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos C# Developer que tenha bom entendimento financeiro, pois existe a necessidade de programação de fluxo financeiro&nbsp;</p>
## Urblot: 
 <p>Somos a 1ª plataforma de compra de terrenos do Brasil. Ajudamos nossos clientes a investir nos melhores empreendimentos imobiliários sem sair de casa.</p></p>

 ## Habilidades: 
 - Adobe XD 
- .NET Framework 
- .NET Core
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em AdobeXB, C# .Net Framework e .Net Core 
- Experiência na área financeira

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [C# Developer na Urblot](https://coodesh.com/jobs/dev-c-134409889?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by fabriciosenadev** [comment]
Esta vaga ainda está aberta?
