### ISSUE TITLE
[São Paulo] Desenvolvedor PHP FullStack no Beedoo

### ISSUE THREAD

**Issue by ptcmariano** [backend-br/vagas#1144]
# Sobre Beedoo
Construímos uma plataforma para tornar a comunicação e a capacitação de equipes de atendimento mais ágil, produtiva e eficiente. Acreditamos que quando você combina um propósito poderoso com grandes pessoas que são as melhores no que fazem, você obtém uma cultura diferente de qualquer outra. Para um novo mundo de trabalho, o Beedoo oferece uma nova maneira de aprender com conceitos de Social e Micro Learning, Gamification , Gestão analítica, base de conhecimento cognitiva e inteligência artificial.

## Principais atividades
Atuará na criação de novas features e manutenção do sistema além de trabalhar consultas no DB grandes e complexas para geração de relatórios, frontend (css/js) utilizando bootstrap/proprietário/Vuejs.

Experiência mínima de 2 anos em:

- PHP7+

- MySQL

- Modelagem de dados relacionais

- Javascript

- JQuery

- HTML

- CSS

- Codeigniter

- GIT

- Vue.js

Diferenciais:

- Vivência com alguma framework JS reativo (Preferencialmente Vue.js)

- Websocket

- NodeJS

- AWS

**Local de Trabalho: SÃO JOSÉ DOS CAMPOS-SP ou SÂO PAULO-SP**

**Fulltime**

**Startup Style**

**Homeoffice**

**PLR e Partnership**

**Valor: a combinar! Faça a inscrição e deixe sua expectativa.**

Inscrições pelo typeform (apenas 9 perguntas - de 3 minutos): https://daniellima14.typeform.com/to/rsLM4z

**Comment by ricardosaraiva** [comment]
Tem a possibilidade de ser 100% remoto
