### ISSUE TITLE
[Homeoffice] Back-end Engineer - Zest Platform

### ISSUE THREAD

**Issue by arancia-xdr** [backend-br/vagas#11459]
## Our Company

We are Zest! The platform is built on Top of OpenSearch Dashboards to make your SOC seamless.

## Description

We are in search of a proficient Software Engineer with a proven track record to become part of our dynamic team. The ideal candidate will take charge of designing, coding, testing, and managing software applications while upholding the utmost standards of quality, efficiency, and security.

**Key Responsibilities**

- Develop high-quality software by adhering to best practices like DDD, SOLID principles, Unit Testing, Clean Code, and Clean Architecture.
- Work collaboratively with the development team to design and deliver software solutions that fulfill customer requirements.
- Gain familiarity with containerization concepts, such as Kubernetes and Docker, as well as fundamental networking concepts.
- Author and sustain technical documentation, encompassing design specifications, user guides, and testing plans.
- Engage in code reviews to guarantee that the software conforms to the highest quality and performance standards.
- Establish and uphold CI/CD pipelines to facilitate swift and dependable software deployment.

## Place

Home office

### Hard skills:

- A minimum of one year of experience in software development.
- Strong proficiency in at least two programming languages, including Java, Python, GoLang, JavaScript, or Ruby on Rails.
- Knowledge and practical experience with ELK Stack/OpenSearch are required, along with relevant education and certifications.
- Experience with CI/CD tools, such as Azure DevOps.
- Excellent communication skills, with the ability to speak and write fluently in English.

**Differential:**
- OSS contributions

### Soft skills:
- You are more than happy passing in CodeReview analysis

## Benefits

International experience.
Negotiable.

## Hiring

You must have a CNPJ.

## Application Process

To apply, please email `techlead.zest at arancia dot ca` with your LinkedIn and GitHub profiles. Use "Backend Software Engineer Position" as your email subject.

## Feedback time

We will respond within two weeks following the initial contact. If you have not received a response, please resend your inquiry to the aforementioned email address.

## Labels
- Backend
- GoLang

#### Allocation
- Home office

#### Regimen
- PJ

#### Level
- Mid-level
- Junior

**Comment by erikbrito** [comment]
What the contact?

**Comment by krisfreedain** [comment]
hello - I'm the Community Manager for the OpenSearch Project 
This is interesting - does Zest have a website or location that provides further details on your product?

**Comment by arancia-xdr** [comment]
Closed, it was fulfilled already.

**Comment by arancia-xdr** [comment]
Hi guys. Reopening the opportunity, because we still need to fill the position.

**Comment by GugaDozero** [comment]
Hi, should I say something here or just send the linkedin/github profiles to techlead.zest@arancia.ca? Thanks!

**Comment by victorbiasibetti** [comment]
@arancia-zest the position is fill or not?
