### ISSUE TITLE
Back-end developer - Codeux

### ISSUE THREAD

**Issue by leandrocodeux** [backend-br/vagas#11451]
### Obrigatórios

- No mínimo 4 anos de experiência comprovada em desenvolvimento de sistemas para web, preferencialmente com a linguagem TypeScript, usando a estrutura do Node.js;
- Vivência, de no mínimo 2 anos, com a dinâmica de trabalho de desenvolvimento de software, colaborativo, seguindo algum método ágil, preferencialmente Scrum;
- Conhecimentos e vivência profissional, de no mínimo 3 anos, com padrões de publicação e administração de bases de código-fonte mediante a aplicação da ferramenta Git;
- Conhecimento e vivência profissional, de no mínimo 2 anos, em aspectos arquitetônicos de sistemas distribuídos, com ênfase na construção de microsserviços orientados à eventos, cujos dados são transmitidos via barramentos de mensageria como RabbitMQ ou NATS (preferencialmente NATS);
- Conhecimentos e vivência profissional, de no mínimo 3 anos, com modelagem e implementação de bancos de dados relacionais, preferencialmente utilizando como SGBD PostgreSQL;
- Conhecimentos e vivência profissional na aplicação de pelo menos uma das seguintes métricas de qualidade de software: 
    - Automatização de testes de software;
    - Redução de complexidade ciclomática;
    - Identificação de gargalos em tempo de execução via análise assintótica (***"Big O" Analysis*** - temporal e espacial);
    - ***Peer Review*** - contribuição na qualidade da produção de código pela equipe de desenvolvimento;

### Opcionais:

- Experiência (profissional ou em projetos pessoais), com técnicas de SSR (Server Side Rendering) em desenvolvimento de SPAs (Single Page Applications) em TypeScript, mediante a aplicação do framework Next.js.
- Experiência (profissional ou em projetos pessoais), em desenvolvimento de aplicativos para dispositivos móveis (Android) em TypeScript, mediante a aplicação do framework React Native.

### Nível

- Pleno
- Sênior
- Especialista

### Alocação
- Remoto

Envie seu currículo para: leandro@codeux.com.br ou (41) 9 9620-4513

**Comment by Cristuker** [comment]
Como aplica?

**Comment by leandrocodeux** [comment]
Envie seu currículo para: [leandro@codeux.com.br](mailto:leandro@codeux.com.br) ou (41) 9 9620-4513

**Comment by danieldfc** [comment]
Sended :+1:
