### ISSUE TITLE
[REMOTE] Back-end developer - Grupo Primo

### ISSUE THREAD

**Issue by gp-breno** [backend-br/vagas#11458]
Estamos em busca de um (a) Backend o para somar no time do Grupo Primo, buscamos alguém motivado a abraçar responsabilidades e que goste de trabalhar com autonomia, alguém que enfrente desafios junto com uma equipe determinada e disposta a fazer a diferença. Se você tem os requisitos descritos, vem ser um primo! 🍎

**Responsabilidades:**
 - Desenvolver e manter a lógica do servidor e APIs utilizando JavaScript;
 - Colaborar com a equipe de desenvolvimento para entender os requisitos do projeto;
 - Implementar práticas de segurança e otimização de desempenho no código backend;
 - Participar ativamente de discussões de design e revisões de código;
 - Integração de sistemas e serviços de terceiros;
 - Solucionar problemas e bugs de forma eficaz;
 - Conhecimento em contêineres, como Docker e Kubernetes.

**Requisitos:**
 - Experiência sólida em desenvolvimento de Backend utilizando JavaScript/TypeScript.
 - Conhecimento profundo de Node.js e frameworks associados.
 - Familiaridade com bancos de dados não-relacionais e relacionais.
 - Experiência em design e implementação de APIs RESTful.
 - Boa compreensão de práticas de segurança e desempenho no desenvolvimento de software.
 - Habilidade para trabalhar em equipe e se comunicar efetivamente.
 - Experiência em ambientes ágeis de desenvolvimento;
 - Conhecimento de frameworks como Express.js e Nest.js;
 - Conhecimento em AWS Lambda, SQS e SNS;
 - Práticas sólidas de teste de unidade.

**Diferenciais:**
 - Conhecimento em Python;
 - Experiência em integração contínua e entrega contínua (CI/CD);
 - Familiaridade com conceitos de microsserviços;
 - Conhecimento em práticas DevOps.

**INFORMAÇÕES ADICIONAIS**
🍔 Vale Refeição e Vale Alimentação disponível no Cartão flexível Swile
🚑 Plano de saúde Amil
🦷Plano odontológico Bradesco
🏃‍♂️Total Pass
⚠️ Seguro de vida
🚌 Vale Transporte
👧 Auxilio creche
📕Acesso as plataformas

Link para se candidatar https://www.linkedin.com/jobs/view/3909682036/

**Comment by AdsonBruno** [comment]
Candidatura enviada!

**Comment by diego2337** [comment]
Candidatura enviada
