### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack na CONDOFY

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1145]
### Sobre a empresa: Condofy

Somos a Administradora Digital de condomínios que utiliza a tecnologia e processos eficientes para reduzir custos, aumentar a transparência e entregar atendimento de excelência.

### Descrição: O que você irá fazer:

**Irá trabalhar na melhoria de um sistema de administração de condomínios.
Conhecimentos necessários:**

HTML;
CSS;
Alguns frameworks de JS;
Banco de Dados;
App público - IOS e/ou Android.

### Conhecimentos desejáveis:

SCSS;
LESS;
Angular 7;
Node.js;
Ionic;
Git.

### O que brilharia aos nossos olhos:

Vontade de compreender a visão do nosso negócio;
Contribuir com soluções e inovações no produto;
Habilidades de liderança para desenvolver o time (que futuramente irá criar);
Pessoa que coloque a mão na massa.

### Benefícios:

Trabalho 100% home office (inicialmente);
Possibilidade de se tornar um dos sócios e CTO do negócio.
Informações complementares:

### Candidatar: http://bit.ly/condofy

**Comment by AntonioMellies** [comment]
Período integral ?
