### ISSUE TITLE
[Alocação] Desenvolvedor Java Pleno

### ISSUE THREAD

**Issue by Franciane-Andrade** [backend-br/vagas#11466]
Estamos em busca de uma pessoa para atuar como Desenvolvedor Java Pleno.

## Descrição da vaga

• Experiência em programação Java
• Experiência em Framework de Teste
• Experiência em Microserviços
• Experiência em banco de dados
• Boas práticas de programação
• Experiência Modelagem de dados
• Experiência Padrões de programação
• Experiência em Containers
• Experiência em cloud
• Experiência em Spring Framework
• Desejavél conhecimento em Apigee
• Desejavél conhecimento em Oracle Service Bus(OSB)
• Desejável conhecimento em Service Oriented Object(SOA)
• Desejável conhecimento em Business Process Execution Language(Bpel)

## Local

Atuação Remota

## Contratação

Contratação CLT (Projeto de 6 meses)

## Como se candidatar

Envie seu CV para E-mail: franciane.andrade@3am-it.com.br

**Comment by HenriqueGSena** [comment]
Enviado !!
