### ISSUE TITLE
[Remoto] Junior (Java ou Python) Developer

### ISSUE THREAD

**Issue by henryzybs** [backend-br/vagas#11465]
## Descrição da vaga

Auxiliar no desenvolvimento e manutenção de aplicativos usando Java ou Python.
Escrever código limpo, eficiente e escalável.
Colaborar com outros membros da equipe para traduzir requisitos de negócios em soluções técnicas.
Participar de revisões de código e sessões de brainstorming.
Realizar testes de unidade e integração para garantir a qualidade do software.

## Local

 remoto

## Requisitos
NÃO É REQUISITO A FALA EM INGLÊS APENAS A ESCRITA NO MOMENTO.
Conhecimento básico em Java ou Python, dependendo da especialidade desejada.
Familiaridade com conceitos de programação orientada a objetos.
Capacidade de resolver problemas de forma criativa e eficiente.
Habilidade para trabalhar em equipe e se comunicar de forma clara e eficaz.
**Desejável:**

Experiência prévia em projetos acadêmicos, estágios ou desenvolvimento de projetos pessoais.
Conhecimento de frameworks relacionados à linguagem escolhida (por exemplo, Spring para Java ou Django para Python).
Familiaridade com bancos de dados relacionais ou NoSQL.
Interesse em aprender novas tecnologias e seguir as melhores práticas de desenvolvimento de software.

## Benefícios

Aulas de Inglês
Auxilio estudo

## Contratação

A combinar

### Nível

- Estagiário
- Júnior

### Regime

- PJ
- CLT
- Contrato
- Freelance

### Alocação

- Remoto

**Comment by NTN1789** [comment]
CV enviado

**Comment by RodrigoRamone7** [comment]
CV enviado

**Comment by felipegv-almeida** [comment]
Enviado ✅

**Comment by serghenr** [comment]
message by whatsapp

**Comment by gustavros** [comment]
GOLPE!

**Comment by teixeira-alexandre** [comment]
Golpe.

**Comment by jonathankarlinski** [comment]
GOLPE!!!
