### ISSUE TITLE
[Remoto] Fullstack Developer (maior enfoque em Back-end) - Fintech

### ISSUE THREAD

**Issue by MartinaCarvalho** [backend-br/vagas#11462]
## Nossa empresa

Somos uma fintech especializada em pagamentos através de infraestrutura tecnológica completa e segura.

## Descrição da vaga

- Participar ativamente em discussões e decisões de tecnologia;
- Desenvolver códigos estáveis e fáceis de manter, desenvolvendo soluções eficientes e escaláveis;
- Ser responsável pela sua entrega end-to-end, garantindo também a cobertura de testes automatizados;
- Contribuir com a cultura de desenvolvimento da engenharia, interagindo com outras pessoas desenvolvedoras, em busca de melhores soluções.

## Local

Remoto

## Requisitos

- Experiência com desenvolvimento de software (backend e/ou fullstack) e vivência com Go ou NodeJS, sendo diferencial ter alguma experiência com frontend;  
- Conhecimento e experiência em desenvolvimento e arquitetura de software, atuando com boas práticas, como design patterns, testes automatizados;
- Atuação prévia como Pessoa Engenheira de Software, com um papel hands on e abertura para atuar em problemas complexos;
- Vivência em ambientes ágeis;
- É um diferencial ter atuado com Cloud e ferramentas de observabilidade.

## Benefícios

Vale Alimentação flexível, Assistência médica e odontológica, Gympass, Seguro de Vida, Incentivo a estudo e idiomas, etc

## Contratação

CLT

## Como se candidatar

https://bit.ly/FullstackEngineerRemoto

### Nível

- Júnior
- Pleno

### Regime

- CLT

### Alocação

- Remoto

**Comment by smithereens1998** [comment]
Enviado

Meu Linkdlin: https://www.linkedin.com/in/tiago-vilela-15a548239/

**Comment by HenriqueGSena** [comment]
Enviado
