### ISSUE TITLE
[REMOTO] Dev PHP - DB1 Group

### ISSUE THREAD

**Issue by talentos-db1** [backend-br/vagas#11471]
## Nossa empresa

O DB1 Group é um grupo de empresas de tecnologia, nascido no interior do Paraná, com mais de 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado, por exemplo, produtos de E-commerce (ANYMARKET, KONCILI, PREDIZE), produtos de Fintech (Consignet, Mixtra e DUCZ), e sistemas de Transformação Digital (DB1 Global Software, DB1 Labs, Tinbot e MyKids).

## Descrição da vaga

Para essa oportunidade, você atuará focado em um projeto de desenvolvimento back end e aperfeiçoamento de uma solução para a área de pagamentos em grandes players.

## Local

Remoto.

## Requisitos

Para fazer parte dessa missão é importante:

- Responsabilidade com prazos e qualidade das entregas;
- Orientação para resultado;
- Organização e planejamento; 
- Resolução de problemas;
- Experiência prévia em desenvolvimento de software PHP;
- Conhecimento em boas práticas de programação como Clean Code, SOLID, Design Patterns, entre outras; 
- Conhecimento em testes automatizados;
- Inglês leitura/escrita avançado.

E será considerado um diferencial:

- Experiência e conhecimento sobre processamento de pagamentos; 
- Disponibilidade de atuação em Curitiba e região metropolitana (para eventuais visitas aos clientes e reuniões).

## Benefícios

- Cartão de benefícios flexíveis (Alimentação, Mobilidade, Qualidade de Vida, entre outras categorias);
- Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;
- Horários flexíveis;
- Gympass (opcional);
- Plano odontológico (opcional);
- Seguro de Vida (opcional);
- Auxílio home office*;
- Evolução de carreira: Plano de Desenvolvimento Individual (PDI), feedbacks constantes, Programa de Mentoria, Parceria com escolas para estudo de idiomas, eventos internos, subsídio para treinamentos, universidade corporativa e muito mais;
- Programas de recompensa: Next1 para indicação de novos colaboradores e bônus anual atrelado a metas;
- Comitês e projetos para você participar, contribuindo com a comunidade e com as melhorias dos processos do DB1 Group;
- Espaço para assumir desafios e se desenvolver.

## Contratação

CLT

## Como se candidatar

- [Clique aqui para se candidatar na vaga](https://db1group.pinpointhq.com/pt-BR/postings/04402993-f877-4943-b61e-47069deb274e)   

### Nível

- Pleno

### Regime

- CLT

### Alocação

- Remoto

**Comment by rdutraLogaroo** [comment]
olá o link da candidatura não está mais disponível. A vaga ainda está aberta?

**Comment by talentos-db1** [comment]
> olá o link da candidatura não está mais disponível. A vaga ainda está aberta?

Opa, atualizando aqui que a vaga foi fechada para candidaturas. Ainda estamos dando sequência com os perfis recebidos!
