### ISSUE TITLE
[Hibrido / São Paulo] Backend Developer (Sênior) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11488]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/programador-backend-senior-124116379?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Principais esponsabilidades:</p>
<ul>
<li>Projetar, desenvolver e implementar soluções de back-end robustas e escaláveis utilizando tecnologias .NET, como ASP.NET, C# e .NET Core.</li>
<li>Colaborar estreitamente com equipes multifuncionais para entender os requisitos do projeto e traduzi-los em soluções técnicas viáveis.</li>
<li>Realizar análises técnicas profundas, identificando possíveis pontos de melhoria e otimizando sistemas existentes para melhor desempenho e escalabilidade.</li>
<li>Participar do ciclo completo de vida do desenvolvimento de software, desde a fase de requisitos até a manutenção pós-produção.</li>
<li>Desenvolver e manter APIs RESTful, garantindo integração fluida com sistemas e serviços externos.</li>
<li>Implementar práticas de segurança de código e padrões de codificação para garantir a estabilidade e segurança das aplicações desenvolvidas.</li>
<li>Promover a adoção de melhores práticas de desenvolvimento, incluindo revisão de código e manutenção de documentação técnica.</li>
<li>Mentorear desenvolvedores juniores, ajudando a cultivar um ambiente de aprendizado e crescimento contínuo.</li>
</ul>
## TicketSports: 
 <p>Somos uma empresa de conexões. Unimos os melhores eventos esportivos aos atletas e apaixonados por experiências transformadoras.&nbsp;</p>
<p>Nossa plataforma cria valor, organiza dados, gera insights e resultados para organizadores de todos os cantos do país, com foco em personalização e atendimento consultivo.&nbsp;</p><a href='https://coodesh.com/companies/ticketsports'>Veja mais no site</a>

 ## Habilidades: 
 - .NET 
- .NET Core 
- Asp.Net 
- API 
- Microsoft SQL Server 
- NoSQL 
- CI/CD 
- GIT 
- Azure DevOps
## Local: 
 São Paulo
## Requisitos: 
 - Sólida e comprovada experiência em arquitetura e desenvolvimento de sistemas complexos, preferencialmente utilizando tecnologias .NET. 
- Expertise em Design de Sistemas: Proficiência avançada em design de sistemas, programação orientada a objetos (OOP) e aplicação de padrões de design de software em escala empresarial. 
- Mestria em Bancos de Dados: Experiência profunda com bancos de dados SQL e NoSQL, com capacidade comprovada de projetar, otimizar e gerenciar esquemas de banco de dados em ambientes de alta disponibilidade. 
- Experiência comprovada na liderança de projetos em ambientes cloud, especialmente com Azure Functions, e na implementação de melhores práticas e padrões. 
- Expertise em metodologias ágeis, com capacidade de orientar equipes e adaptar métodos conforme necessário (Scrum, Kanban, etc.). 
- Resolução Avançada de Problemas: Habilidade comprovada em solucionar desafios técnicos complexos e em orientar equipes durante a resolução de problemas. 
- Capacidade demonstrada de liderar e colaborar com equipes multidisciplinares em um ambiente dinâmico, orientando a tomada de decisões técnicas. 
- Fortes habilidades de comunicação, com experiência em apresentar soluções técnicas para stakeholders, equipes e gerência de forma clara, concisa e persuasiva. 
- Habilidade de orientar e monitorar desenvolvedores menos experientes, promovendo crescimento técnico dentro da equipe. 
- Capacidade de alinhar decisões técnicas com os objetivos estratégicos da organização, e de recomendar tecnologias ou abordagens futuras. 
- Proficiência comprovada em sistemas de controle de versão, em particular com o Git. Isso inclui compreensão avançada de branching, merging, rebasing e outras operações avançadas, bem como a capacidade de estabelecer e orientar melhores práticas para gerenciamento de código. 
- Experiência profunda em configurar, otimizar e gerenciar pipelines de integração e entrega contínua, garantindo implantações frequentes, estáveis e automáticas. Familiaridade com ferramentas líderes de CI/CD, como Jenkins, GitLab CI, Azure DevOps, entre outras, e capacidade de integrá-las ao fluxo de trabalho de desenvolvimento para maximizar a eficiência. 
- Experiência profunda com bancos de dados SQL e NoSQL 
- Habilidade de comunicar ideias e soluções técnicas de forma clara, tanto por escrito quanto verbalmente. 
- Capacidade de colaborar efetivamente com outras equipes e disciplinas (como designers e desenvolvedores front-end) para alcançar objetivos comuns. 
- Excelente habilidade para identificar e resolver problemas, buscando soluções inovadoras e eficazes. 
- Capacidade de se adaptar rapidamente às mudanças de tecnologia e requisitos de projeto. 
- Desejo de se manter atualizado com as últimas tendências e desenvolvimentos no campo do desenvolvimento back-end.
## Diferenciais: 
 - Experiência em ticketeria e/ou e-commerce 
- Ser corredor

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Developer (Sênior) na TicketSports](https://coodesh.com/jobs/programador-backend-senior-124116379?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Back-End

**Comment by velrino** [comment]
Hibrido e PJ (kit CLT camuflado) kkkkkkkk
