### ISSUE TITLE
[Remoto] Back-end developer .NET C# - Hepta Tecnologia

### ISSUE THREAD

**Issue by GitMateusBruno** [backend-br/vagas#11496]
## Nossa empresa

Somos a Hepta tecnologia; empresa sediada em Brasília com 33 anos de atuação. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

C# Avançado (REST, MVC, .NET 7 ou 8)
Metodologia Ágil

## Local

Remoto

## Requisitos

Necessário comprovação de experiência
Formação Superior completa em TI ou Pós graduação
Certificação em PSD ou CSD
Para o perfil Sênior desejável mais uma em: PSM I, II ou III. Ou CSM; Ou SMC; Ou ASM. (P/ atuar como Scrum Master)
*Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.*

## Benefícios

Salário + Plano de saúde com coparticipação parcialmente custeado pela empresa. Plano Odontológico. VA ou VR com valor fixado em convenção coletiva. Auxilio Home Office.

## Contratação

CLT ou PJ

## Como se candidatar

Enviar e-mail para mateus.sousa@hepta.com.br com o assunto "Vaga .NET"

### Nível

- Sênior

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by fabriciosenadev** [comment]
Seria pra atuar como dev e SM?

**Comment by GitMateusBruno** [comment]
Na verdade a atuação principal seria DEV. caso haja a necessidade sim.

Em dom., 19 de mai. de 2024 às 12:55, Fabricio Sena <
***@***.***> escreveu:
