### ISSUE TITLE
[Serra/ES] Anibal Henrique de Souza

### ISSUE THREAD

**Issue by ahsouza** [backend-br/vagas#115]
## Nome completo

ANIBAL HENRIQUE DE SOUZA

## Localidade

Serra/ES

## Apresentação

Sou Desenvolvedor Web Full-Stack Jr com formação em curso técnico profissionalizante com ênfase em Programação Web no Instituto Federal de Ciências e Tecnologias do ES.

## Outras Informações

Disposto a cumprir 8/h

## Especialidades

- JavaScript
- HTML
- CSS
- Node.js
- Angular.js
- Vue.js
- MySQL
- MongoDB

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/anibalhenriquesouza

## Site

https://ahscode.com.br

**Comment by kivervinicius** [comment]
@ahsouza repositório errado amigo.

**Comment by reginaldojunior** [comment]
Olá,

Este repositório é unicamente destinado a anuncio de vagas, estamos para abrir no estilo me-contrate da organização frontendbr.

Assim que abrimos aviso você.

**Comment by ahsouza** [comment]
Me desculpe, obrigado!

Em qua, 14 de mar de 2018 20:00, Reginaldo Junior <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Olá 

@ahsouza 

Abrimos nosso repositório com o objetivo de anunciar profissionais. Cria sua issue lá!

https://github.com/backend-br/me-contrata

Abs

**Comment by ahsouza** [comment]
Muito obrigado @reginaldojunior
