### ISSUE TITLE
[Remoto] Backend Node.js Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11501]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/backend-nodejs-developer-134446565?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos buscando <strong>Backend Node.js Developer </strong>para compor nosso time!</p>
<p>Somos um marketplace onde consumidores e marcas com propósitos semelhantes se encontram para fazer negócios. Se você acha que a tecnologia pode humanizar o varejo e deseja trabalhar com grandes marcas, temos uma vaga na nossa equipe de desenvolvimento.</p>
<p>Nosso manifesto é simples: aproximar marcas e consumidores.Vontade de encontrar o que se busca, mesmo ainda sem saber ao certo o que se quer. Afinal, quando temos acesso às informações certas sobre o que o outro quer, é muito mais fácil entregar o que se tem.</p>
<p>Queremos nos conectar com marcas que compartilham nossas crenças e desejos.</p>
<p>Nosso objetivo é criar uma conexão mais profunda entre as partes envolvidas, baseada em uma identificação mútua. Não nos apressamos, não nos deixamos levar pela pressão ou vaidade. Acreditamos que é necessário estar perto do que desejamos, do que falta e do que acreditamos.</p>
<p><strong>Responsabilidades e atribuições:</strong></p>
<ul>
<li>Desenvolver aplicações/micro-serviços</li>
<li>Propor as melhores soluções técnicas no processo de desenvolvimento</li>
<li>Garantir a escalabilidade e resiliência dos serviços</li>
<li>Conexão com líderes técnicos para acompanhamento de performance</li>
<li>Desenvolver a carreira de desenvolvedores de menor senioridade</li>
</ul>
## Likin.do Brasil: 
 <p>No Likin.do shopping, estamos comprometidos em liderar a transformação de comportamento no varejo online até 2030 atingindo 1% do share, unindo clientes e marcas com propósitos alinhados, cultivando um consumo que impulsiona mudanças positivas e duradouras, resultando em compras sustentáveis especialmente para grupos e franquias ou marcas que se equivalem através de uma curadoria. Nossa plataforma inovadora  é mais do que um espaço de compra: é um ponto de encontro onde marcas, instituições beneficentes  e clientes, unidos por propósitos, colaboram para um futuro mais sustentável.</p>
<p>Um shopping na palma da mão.</p><a href='https://coodesh.com/companies/likindo-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- Clean Architecture 
- GIT 
- Rest API 
- MySQL 
- ElasticSearch 
- AWS
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência na área de desenvolvimento 
- Graduação em áreas correlatas à Tecnologia 
- Ter experiência avançada com Node.JS (javascript/typescript); 
- Bancos de dados (MySQL/MongoDB); 
- Ter domínio de requisitos não funcionais como performance, escalabilidade, manutenibilidade e observabilidade; 
- Controle de versão (Git) 
- APIs REST 
- Elasticsearch (Stack ELK) 
- Testes unitários e de integração 
- Ferramentas Atlassian Jira/Bitbucket/Confluence 
- Amazon AWS
## Diferenciais: 
 - Residir na região Sul (Rio Grande do Sul, Santa Catarina ou Paraná) 
- Implementação de UI baseadas em protótipos (figma)
## Benefícios: 
 - 100% remoto 
- Paticipação nos lucros 
- 30 dias de férias remuneradas
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Node.js Developer na Likin.do Brasil](https://coodesh.com/jobs/backend-nodejs-developer-134446565?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by evertonbez** [comment]
Enviado, gostaria de participar, tenho todos os requisitos.
