### ISSUE TITLE
[Remoto] Back-end developer - Interaxa (Grupo Mutante) - [PL|SR]

### ISSUE THREAD

**Issue by jpventura** [backend-br/vagas#11511]
## Nossa empresa

[Interaxa (Grupo Mutante)](https://interaxa.com/) é a  maior integradora de soluções de atendimento do Brasil, e o primeiro BSP em WhatsApp da America Latina.

Animado com a construção integrações de ponta para capacitar milhões de empresas latino-americanas?  Junte-se à equipe!
 
A [Interaxa (Grupo Mutante)](https://interaxa.com/) já está contratando para o cargo de Desenvolvedor Backend!

## Descrição da vaga

Você fará parte do time de Tecnologia, que é a área responsável por desenvolver, monitorar, melhorar e criar soluções referentes aos nossos produtos e sistemas.

Como desenvolvedor, você fará parte do time por trás do time que garantirá a estrutura, eficácia e sucesso de todas as plataformas e produtos da [Interaxa (Grupo Mutante)](https://interaxa.com/).

Algumas das principais atividades dessa oportunidade são:

  - Detalhar junto ao time de Produtos as prioridades de desenvolvimento;
  - Desenvolvimento de novas funcionalidades;
  - Manutenção e evolução de sistemas existentes;
  - Garantir a qualidade de desenvolvimento;
  - Automação de testes;
  - Implantar as soluções desenvolvidas em ambiente produtivo.

## Local

 - Remoto
 
### Conhecimentos necessários

  - Mais de 4 anos de experiência em back-end
  - Criação de APIs RESTful
  - MVC padrão, MVP, MVVM, arquitetura limpa e derivados
  - Amazon EC2, Amazon S3, Amazon Lambda
  - Heroku, Amazon Beanstalk, Google App Engine
  - Teste de unidade Jasmine, Mocha ou Karma
  - Express.js, Django, Flask, Ruby on Rails, Sinatra ou Spring Boot

### Conhecimento desejável
  - MERN stack (Mongo, Express, React e Node.js)
  - Mais de 4 anos de experiência em backend Node.js
  - hapi.js, Koa.js ou Sails.js
  - GraphQL, Apollo, Prisma
  - Firebase Realtime Database e Firebase Analytics
  - Promessa, Async/Await ou RxJS

### Conhecimento especializado

  - React.js e Redux
  - Padrões avançados de componentes React
  - Renderização do lado do servidor com Next.js
  - Desenvolvimento React Native
  - Software Reliability Engineer
  - Kubernetes (EKS ou GKE)

## Contratação
  - PJ

## Como se candidatar

Agente um bate-papo conosco no [Calendly](https://calendly.com/jpventura-interaxa/30min) e LinkedIn, GitHub e portifólio.

### Nível

- Pleno
- Sênior

### Regime

- PJ
- Contrato

### Alocação

- Remoto
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by ferreirase** [comment]
Enviei CV. Posição bem alinhada comigo.

**Comment by jpventura** [comment]
Temporariamente encerramos a issue devido ao número de cadidatos.
