### ISSUE TITLE
[Remoto] Back-end Java developer Jr - Datum TI

### ISSUE THREAD

**Issue by julianakraemer** [backend-br/vagas#11512]
## Nossa empresa

Somos uma consultoria de tecnologia que, há 24 anos, desenvolve soluções digitais que promovem crescimento para pessoas e negócios.
Nossos clientes se veem desafiados a implementar projetos inovadores, enquanto exercem o papel de liderança, engajando pessoas em um mundo cada vez mais não-linear e complexo.
Por isso, contratamos e retemos profissionais de alta performance para entregar soluções digitais com a agilidade que o negócio precisa.
## Descrição da vaga

Oportunidade Remota nível Júnior/pleno!

Se você é um entusiasta da tecnologia em busca de uma oportunidade para contribuir sua carreira na área de TI, a Datum é o lugar perfeito para você!

Estamos em busca de talentos responsáveis, comprometidos e prontos para mergulhar em um ambiente dinâmico e solicitado.

Aqui você terá:

Acompanhamento especializado para auxiliar no desenvolvimento de soft skills;
Oportunidade de atuar em projetos de grandes empresas nacionais, nos mais diversos ramos;
Oportunidades de networking com profissionais experientes do setor de tecnologia.
## Local

Remoto
## Requisitos

Desejável que tenha conhecimento em 
Requisitos e qualificações: 

Java;

Git (Git Flow);

Mongo;

Oracle,

TDD;

HTML 5;

Microsserviços;

Diferenciais:

Desejável experiência em React (Redux, Context e Hooks API);

Desejável Typescript;

Desejável CSS e pré-processadores;

Desejável Vanilla Javascript (ES5, 6, 7, Design Patterns).
## Benefícios

INFORMAÇÕES ADICIONAIS
Nossos datunianos usufruem de benefícios e programas que atendem diversas áreas da vida.

Para sua saúde, oferecemos assistência médica e odontológica sem coparticipação em exames e consultas.
Seguro de vida
Quer mais bem estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Quando bater aquela fome, utilize nosso benefício de alimentação Caju para fazer compras em qualquer supermercado ou restaurante.
Quer viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Tem filhos? Temos ajuda creche.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Para deixar seu ambiente de trabalho com a sua cara, conte com o nosso auxílio home office.
Quer protagonista? Participe do Protagonistas, nosso jogo da vida real, e ganhe prêmios incríveis!
## Contratação

CLT

## Como se candidatar

Informe os canais disponíveis para a aplicação na vaga.

### Nível

- Estagiário
- Júnior

### Regime

- CLT

### Alocação

- Remoto

**Comment by alvaroaxsmith** [comment]
Qual canal de contato eu posso enviar meu currículo?

**Comment by NTN1789** [comment]
onde eu posso mandar o currículo ?

**Comment by ludson96** [comment]
Olá, @julianakraemer.

Acho que esqueceu de informar os canais disponíveis para a aplicação na vaga.

**Comment by Vitor-C-Souza** [comment]
Qual canal que tenho que me candidatar?

**Comment by AGioDio** [comment]
dionisio_pereira@outlook.com
(41) 99859-2384

**Comment by cyajuninho** [comment]
[cyajuninho@gmail.com](mailto:cyajuninho@gmail.com)
(18) 99124-2861

**Comment by salesbruno** [comment]
salesdasilvabruno@gmail.com 
(81) 98431-2039
Estagio

**Comment by Marcos-PauloR** [comment]
marcosp.rioss@gmail.com
(62)982650531
Junior

**Comment by Vitor-C-Souza** [comment]
vitor_souza97@hotmail.com
(13)996161719
Junior

**Comment by kevyncode** [comment]
kevinsilvar82@gmail.com
(87)99809-2391
Junior/Estágio

**Comment by gustavomgl** [comment]
gustavo.magc@gmail.com
(65)992883487

**Comment by kevyncode** [comment]
kevinsilvar82@gmail.com
(87)99809-2391
Junior/Estágio

**Comment by matheusaugusto98521** [comment]
matheusword555@gmail.com
(15) 99662-9300
júnior/estágio

**Comment by Kaminskifking** [comment]
vikaminski@hotmail.com
https://www.linkedin.com/in/vinicius-kaminski/
(11) 967172519
junior/estágio

**Comment by AriLopes** [comment]
Onde posso mandar meu currículo?

**Comment by LucasRafaelSouza** [comment]
lucasrafaelalvesd@gmail.com
(31) 99511-0090
júnior/estágio

**Comment by lucasAlcantara01** [comment]
lucas.alcantaravm@gmail.com
https://www.linkedin.com/in/lucas-alcantaravm/
(11)982964486
junior/estágio

**Comment by GabrielGomezzs** [comment]
gabrielgomess26ti@gmail.com
https://www.linkedin.com/in/gomezz26/
(13)991864504
junior

**Comment by yagobmoreira** [comment]
<yagomoreira@gmail.com>
[https://www.linkedin.com/in/yagobmoreira/](https://www.linkedin.com/in/yagobmoreira/)
Junior

**Comment by haimonvieira** [comment]
https://www.linkedin.com/in/haimonvieira/
Estou interessado para vaga de Júnior

**Comment by gugacosta99** [comment]
gug994@gmail.com
https://www.linkedin.com/in/gustavo-costa-824673143/
(81) 9 9646-6858
Interessado na oportunidade

**Comment by JoaoVitorMadeiro** [comment]
(85)9-9403-7237
joao.madeirodev@gmail.com
www.linkedin.com/in/joão-vitor-de-sousa-madeiro-338853294

**Comment by NTN1789** [comment]
alguém fecha essa vaga  está muito tempo inativa , e gente para de mandar seus números aqui pode correr risco de algo acontecer.
