### ISSUE TITLE
[São Paulo/SP] - Senior Backend Developer @ Arizona

### ISSUE THREAD

**Issue by raymonsanches** [backend-br/vagas#1152]
## Descrição da vaga

Sênior PHP Backend Developer na Arizona

Responsável pelo desenvolvimento e integração de vários projetos para organização e evolução de todos os processos de marketing. 
Trabalhar em conjunto com frontend e OPS para entrega da melhor solução e resolução do problema e tendo sempre em mente uma arquitetura escalável e manutenivel.

## Local

Rua Castro Verde, 98 - Jardim Caravelas - São Paulo/SP

## Nosso Time

Trabalhamos em um time focado em comunicação (síncrona e assíncrona) e estamos sempre experimentando metodologias e feramentas que nos permitam ser sempre mais produtivos e eficazes nas nossas entregas.

Acreditamos em uma cultura de responsabilidade com mais foco nas pessoas e menos nos processos.
Work-life balance.

## Nossa empresa

Arizona é lider do mercado de Crossmedia e atende grandes marcas. Veja mais em [https://www.arizonacrossmedia.com.br](https://www.arizonacrossmedia.com.br)

## Benefícios

- VR/VA/VT
- Convênio Médico
- Convênio Odontológico
- Horário flexível
- Gympass
- Parceria com SESC
- Seguro de Vida
- Auxílio creche

## Requisitos

- Experiência com PHP 5+ e 7+
- Experiência com Mysql 5.6+
- Solidos conhecimentos em arquitetura e padrões de desenvolvimento
- Experiência com integração entre sistemas
- Experiência com API REST
- Conhecimento em algum framework
- Composer
- GIT

## Desejável

- Docker
- Symfony
- Experiência com CD/CI
- Metodologia SCRUM
- Testes unitários

## Contratação

CLT

## Como se candidatar

Me manda um e-mail para ramon.sanches@arizona.global com seu perfil do Linkedin e "Vaga PHP" no título e bora trocar uma idéia ;)

**Comment by lucasmarques73** [comment]
@raymonsanches está buscando apenas sênior?
Sou um grande fã do DEVNAESTRADA e tenho vontade de trabalhar com você. Gosto muito do seu trabalho no podcast.
Mas ainda não estou neste nível de senioridade.

**Comment by raymonsanches** [comment]
opa mano, agradeço muito!
Po, manda seu cv assim mesmo cara, quem sabe ;)
