### ISSUE TITLE
[Remoto] Backend Java Developer (Júnior) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#11521]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/backend-java-developer-210417134?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.</p>
<p>Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.</p>
<p>Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial. O tamanho do seu talento.</p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES:</strong></p>
<ul>
<li>O profissional será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.</li>
<li>Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.</li>
<li>Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).</li>
<li>Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!</li>
</ul>
## Invillia: 
 <p>Certamente você já conheceu a Invillia, interagindo com os produtos e serviços digitais que a gente desenvolve_ Os nossos códigos e capacidade de inovar estão em revoluções de vários game-changers (techs que estão transformando seus segmentos com tecnologia). É nossa missão dar mais poder, agilidade e escala para essas empresas mudarem a vida de milhares de pessoas.</p>
<p>Alguns dos nossos clientes:  PagSeguro, Gympass, QuintoAndar, Fiagril, Dafiti, Via, ifood, movile pay, OLX, too seguros_</p><a href='https://coodesh.com/companies/invillia'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Spring 
- Kafka 
- AWS 
- GIT 
- NoSQL 
- SQL 
- Jenkins
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em desenvolvimento com Java; 
- Definição de Arquitetura exercendo o papel de Referência Técnica; 
- Experiência em desenvolvimento com Spring (Boot, Data, Cache, etc); 
- Conhecimentos em Java 8 (mínimo); 
- Conhecimento em Filas (Rabbit); 
- Conhecimento em Kafka; 
- Conhecimentos em AWS (SNS, SQS, S3); 
- Conhecimentos em Git e Git-Flow; 
- Experiência com bancos de dados SQL e NoSQL; 
- Desenvolvimento com foco em qualidade: testes unitários e Sonar(métricas); 
- Experiência em micro serviços e sistemas concorrentes; 
- Contínuos delivery (Jenkins);

## Benefícios: 
 - Inovamos lado-a-lado com #GameChangersGlobais 
- Cultura de trabalho distribuído #inStation 
- Metodologia exclusiva #GlobalGrowthFramework 
- Benefícios únicos entre as techs #InfinitePowers
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Java Developer (Júnior) na Invillia](https://coodesh.com/jobs/backend-java-developer-210417134?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by danielhe4rt** [comment]
Essa lista toda pra Junior? Doideira hein familia...

Salário é acima de 6k?
