### ISSUE TITLE
[Remoto] Desenvolvedor FullStack Sr (C, C++, Java)- Meta

### ISSUE THREAD

**Issue by rogiafarias** [backend-br/vagas#11548]
## Nossa empresa

**Por que construir sua carreira na Meta?**

Oferecemos autonomia, metas claras e um ambiente dinâmico e desafiador, onde os profissionais têm oportunidade de interagir com diferentes tecnologias, participar de todos os tipos de projetos, trazer novas ideias e trabalhar de qualquer lugar do Brasil e (por que não?) do mundo. Além disso, somos uma das melhores empresas para se trabalhar no Brasil segundo o Great Place to Work e uma das 10 empresas que mais crescem no país há 3 anos consecutivos, segundo o Anuário Informática Hoje.

Quais são nossos valores?

- Somos pessoas servindo pessoas

- Pensamos e agimos como donos

- Temos gana por performance

- Crescemos e aprendemos juntos

- Buscamos excelência e a simplicidade

- Temos inovação e criatividade no nosso DNA

Todas as pessoas são bem-vindas independentemente de sua condição, deficiência, etnia, crença religiosa, orientação sexual, aparência, idade ou afins. Queremos que você cresça conosco em um ambiente acolhedor e repleto de oportunidades.

Se identificou? Então, #VemSerMeta!

## Descrição da vaga

**O que procuramos?**

Atribuições principais: 

Definir as melhores práticas de desenvolvimento;

Programar, codificar e testar sistemas na linguagem, transitando entre projetos de desenvolvimento Front-End e Back-End;

Executar o desenvolvimento das funcionalidades complexas;

Propor evoluções tecnológicas nos sistemas.

Monitorar a execução das boas práticas de desenvolvimento de sistemas.

Validar o nível de testes existentes nos projetos;

Validar as novas funcionalidades das aplicações;

Monitorar o desempenho e desempenho dos sistemas das aplicações;

Propor evoluções tecnológicas nos sistemas;

Antecipar-se a oportunidades e problemas, ágil com rapidez e eficácia, desenvolvendo soluções de forma preventiva;

Auxiliar na orientação dos desenvolvedores mais novos e contribuir nas tomadas de decisão do projeto;

Executar a manutenção dos sistemas, fazendo possíveis alterações, atendendo às necessidades dos usuários;

Desenvolver trabalhos de montagem, depuração e testes de programas, executando serviços de manutenção nos programas já desenvolvidos.

## Local

100% Remoto

## Requisitos

Sólida experiência com desenvolvimento em: C; C++; Java; JavaEE 

Conhecimento e experiência com:  Qt, Windows

Experiência com Microservicos e Springboot. 

Linux: Sockets; Threads; Filas.

Banco de dados: PostgreSQL; Oracle.

Mensageria: Active MQ e Kafka

Conhecimento com: SOAP, REST, GIT, SVN, SCRUM, XP com sistemas complexos e Rede.    

**Diferenciais:**

 Experiência com MongoDB;

Conhecimento de hardware, IoT;

Protocolos de comunicação proprietarios; 

Inglês avançado. 

## Benefícios

VA/VR - Swile
Ajuda de Custo 
Seguro de vida
Plano Odontológico
Plano de Saúde
Total Pass
Vittude (Plataforma de Terapia Online)
Open English
English Club

## Contratação

CLT ou PJ

## Como se candidatar

[Se candidate aqui ;) .](https://meta.jobs.recrut.ai/vagas/job/OG8KBS)

### Nível

- Pleno
- Sênior

### Regime

- PJ
- CLT

### Alocação

- Remoto

**Comment by Marcos-PauloR** [comment]
Canditadura enviada :smiley:
