### ISSUE TITLE
[Alocação] Back-end developer - NomeDaEmpresa

### ISSUE THREAD

**Issue by Vitor-TI** [backend-br/vagas#11551]
## Nossa empresa

A Minds Digital é uma IDTech especializada em biometria de voz, por meio da nossa inteligência artificial conseguimos autenticar e identificar a sua voz. Com ela as pessoas se tornam únicas, exclusivas e insubstituíveis. Além dessa tecnologia inovadora, trabalhamos também como Outsourcing com a responsabilidade de ajudar desenvolver toda área de TI, com soluções em nuvem para o nosso cliente.

## Descrição da vaga

Como Back-end Developer, você irá atuar em nossa frente de Outsourcing, formado por um time de desenvolvimento que tem o objetivo de trazer soluções para um de nossos principais clientes que possui um sistema de empréstimos. O time atua no modelo presencial no Bairro Savassi em Belo Horizonte/MG no escritório do cliente, desenvolvendo uma relação próxima, colaborativa e de oportunidades de criação e resolução de problemas.

## Local

Atuação no modelo presencial no escritório do cliente no bairro da Savassi/Belo Horizonte.

## Requisitos

-.Net Core
-Arquitetura Microsserviços
-Mensageria (Kafka)
-Conhecimento com Kubernetes e Docker
-Clean Architecture, SOLID
-Metodologias ágeis, Scrum e Kanban

## Benefícios

Horário Flexível

## Contratação

Proposta inicial entre R$ 7.500,00 e R$ 11.000,00 PJ (A proposta vai depender da experiência e conhecimentos demonstrados durante o processo seletivo. Desta forma, conseguiremos entender melhor como poderá ser sua contribuição aqui. Procure compartilhar o máximo de informações com a gente e, também, nos perguntar tudo o que for importante para você);

## Como se candidatar

Por favor faça o cadastro por este link: https://rh.minds.digital/jobs/detail/pleno-software-engineer-time-de-consultoria-34

### Nível

- Júnior
- Pleno

### Regime

- PJ

### Alocação

- Presencial

**Comment by fabriciosenadev** [comment]
Seria possível candidatura de outro estado ou é imprescindível o presencial?

**Comment by gusholz** [comment]
link ta quebrado :(

**Comment by marcosh27** [comment]
é requisito essencial que seja presencial? sou de outro estado mas tô interessado na vaga... e o link tá quebrado

**Comment by Vitor-TI** [comment]
https://rh.minds.digital/jobs/detail/pleno-software-engineer-time-de-consultoria-34

Segue o link.

**Comment by marcosh27** [comment]
valeu

**Comment by marcosh27** [comment]
@Vitor-TI a vaga ainda tá disponível?
