### ISSUE TITLE
[Remote] Software Engineer (Back End) - Voxy Inc.

### ISSUE THREAD

**Issue by Lali-Voxy** [backend-br/vagas#11569]
## About Voxy

Voxy, founded in 2010, is a trailblazing language training platform tailored to meet the specific language needs of international organizations. With a mission to enhance productivity, foster collaboration, and unleash human potential, Voxy has established itself as a global leader in the field of corporate language education. With a robust foundation and an ever-evolving vision, Voxy has supported corporate clients across 150 countries by delivering live language coaching led by certified instructors and an expansive library of role-specific courses that bridge critical soft and technical skill gaps.

Today, Voxy's impact spans the globe, with dedicated teams operating across multiple regions, including the United States, Brazil, Chile, Mexico, Thailand, Malaysia, Spain, Italy, and Ireland. Originally focused on providing English language instruction, Voxy has evolved to offer an array of languages, including Portuguese, Spanish, Italian, German, and French, catering to a diverse range of learners.

We believe that learning a language should be fun, rewarding, and a gateway to the best experiences life has to offer. If you agree, we’d love to talk.

You can see more details about our values here (https://voxy.com/about/careers/)

## What You'll Be Doing

- Build a revamped content ingestion framework incorporating “AI”  to  power the activities our learners use to excel at language learning
- Create insightful customer reporting and build the big data pipelines that help power it
- Architect and document software solutions for our admin  facing team that integrate cleanly with our products and services
- Produce nicely-instrumented code that is testable and deployable without downtime
- Mentor other engineers in the ways of software engineering, including proposing standards that can be used across the engineering organization
- INNOVATE by incorporating AI, NLP, Machine Learning into multi learner/teacher activities that you help invent

## Brazil
Remote work

## What We’re Looking For:

- The person needs to reside in Brazil to be eligible for this role
- 5+ years of experience working as a software developer
- Python programming experience
- Curiosity and knowledge about technologies and architectural patterns of software engineering across the entire stack
- Pragmatism in understanding when to build a  solution that scales to 1 million users or works for 100 users
- Ability to design data models that reflect the Voxy business using advanced SQL/NoSQL/ORM’s

### What Would Be Nice To Have:

- Django Rest Framework and/or FastAPI
- B.S. or higher in computer science, science or engineering discipline or equivalent experience

## Benefits

- Competitive salary, bonus, and stock options 
- Great benefits: medical insurance, cell phone & wifi reimbursement, home office & wellness budget, team events
- Remote-friendly work policies
- Professional development budget
- HONE Membership - live training platform with programs designed for leaders, managers, and individual contributors(ICs) to develop skills to succeed in the workplace
- Language classes w/ Voxy & Fluentify
- Work with an awesome international team of super bright, creative, talented, and passionate individuals based around the world

## Contratação

Full-time; CLT.

## Como se candidatar

(https://jobs.lever.co/voxy/94da761a-5e32-409d-bbaf-c0e6c775b282?lever-origin=applied&lever-source%5B%5D=GitHub)

### Nível
- Sênior

### Regime
- CLT

### Alocação
- Remoto

**Comment by Lali-Voxy** [comment]
Ainda está aberta ;)) Qualquer coisa, estou à disposição!!

**Comment by guilherme90** [comment]
@Lali-Voxy gostei da vaga. Acabei de aplicar :)

**Comment by JMustang** [comment]
> Ainda está aberta ;)) Qualquer coisa, estou à disposição!!

Só tem vaga para Sênior?
