### ISSUE TITLE
[Alocação] Back-end developer (Node.js) Sênior - EXTRACTTA

### ISSUE THREAD

**Issue by isatelesmar** [backend-br/vagas#11566]
## Nossa empresa

Informe a descrição da empresa.

## Local

Remoto. 

## Requisitos

1. **Node.js**:
Proficiência em desenvolvimento backend usando Node.js.
Conhecimento de frameworks populares como Express.js, Koa.js ou Nest.js.
Capacidade de escrever código assíncrono utilizando Promises, Async/Await.
Experiência em desenvolvimento de APIs RESTful e GraphQL.
2. **AWS (Amazon Web Services)**:
Experiência com serviços da AWS como EC2, S3, RDS, Lambda, API Gateway, e IAM.
Conhecimento em deploy, configuração e monitoramento de aplicativos na nuvem AWS.
Habilidade em usar ferramentas de infraestrutura como código (IaC) como Terraform ou AWS
Experiência em configuração e gerenciamento de ambientes CI/CD usando serviços como AWS
3. **PostgreSQL**:
Experiência em design e gerenciamento de bancos de dados relacionais usando PostgreSQL.
Habilidade em escrever consultas SQL complexas, otimização de desempenho e tuning de banco de dados.
Conhecimento em índices, transações, e replicação de dados.
Capacidade de realizar backup e restore de bancos de dados, bem como gerenciamento de permissões e segurança.
4. **NoSQL**:
Familiaridade com bancos de dados NoSQL como MongoDB, Cassandra ou Redis.
Compreensão das vantagens e desvantagens de diferentes bancos de dados NoSQL e quando utilizá- los.
Habilidade em modelagem de dados para bancos de dados NoSQL.
Experiência em otimização de consultas e manutenção de bancos de dados NoSQL.

## Contratação

Forma de contratação: PJ

## Como se candidatar

Enviar CV para o e-mail: [isabele.martins@extractta.com.br](mailto:isabele.martins@extractta.com.br), com o assunto Desenvolvedor Backend.

### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto

**Comment by swlucas** [comment]
Enviado

**Comment by ejklock** [comment]
Enviei, recebi contato da recruiter, ela pediu CV novamente e pretensão salarial  e depois não respondeu mais nada 🤨
