### ISSUE TITLE
[REMOTO] Back-end developer - Opikode

### ISSUE THREAD

**Issue by cmaiarenata** [backend-br/vagas#11572]
## Nossa empresa

A Opikode é uma empresa de desenvolvimento de software que está construindo sua marca no mercado brasileiro, produzindo soluções de alto valor para os negócios de nossos clientes e parceiros.
Temos clientes em 22 estados, representando quase todo o território nacional, com um excelente nível de satisfação com a qualidade dos serviços prestados.
Nossa equipe é composta por especialistas, que criam soluções corporativas de enterprise-ready que proporcionam entregas rápidas de alto valor para as empresas, impulsionando o crescimento e o alcance de seus objetivos estratégicos mais rapidamente.

## Descrição da vaga

É necessário você ter conhecimento em:
- Experiência profissional com desenvolvimento de Portais Web em Java;
- Conhecimento em Ferramentas de controle de dependências Maven, Gradle, NPM, Gulp e cont
- Conhecimento na construção de OpenAPI/REST e serviços WS/SOAP
- Groovy scripting;
- Metodologias ágeis ( Scrum ou Kanban);

## Local

Remoto

## Requisitos

Diferencial:

- Conhecimento em plataforma de computação em nuvem (GCP, Azure, AWS); 
- Conhecimento em contêineres Docker;
- CI building pipelines tools like Jenkins, Nexus and Sonar;
- Certificação Liferay ou cursos Liferay Developer;
- Criação de Estruturas/Modelos/ADTs no Liferay DXP; 
- Administração de Sites, Páginas, Conteúdos e Listas no Liferay DXP;
- Administração de Usuários e Papéis no Liferay DXP;
- Desenvolvimento de Plugins (Themes, Portlets, Hooks, OSGI) no Liferay DXP; 
- Experiência com Talend ou outro software de ETL;
- Experiência com SOA e ESB;
- Conhecimento em E-Commerce;
- Experiência com Apache Freemarker.

## Benefícios

Horário flexível.
Salário compatível com o mercado.
Day-Off no dia do aniversário.

## Contratação

Regime PJ

## Como se candidatar

Enviar o currículo para renata.maia@opikode.com com o assunto "Vaga Desenvolvedor Back-end".

### Nível

- Júnior
- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by Mateuslll** [comment]
cv enviado!
