### ISSUE TITLE
[Rio de Janeiro] Desenvolver Python e Ruby [Estante Virtual]

### ISSUE THREAD

**Issue by ebertti** [backend-br/vagas#1158]
Descrições das vagas:

https://github.com/estantevirtual/vagas

## Sobre nós

A [Estante Virtual](https://estantevirtual.com.br) é o maior portal de compra e venda de livros usados
e seminovos do Brasil, reunindo mais de 16.5 milhões de livros dos melhores sebos e livreiros do país.

A empresa é líder absoluta no setor desde a sua fundação em 2005
e orgulha-se de oferecer ótimas condições de desenvolvimento criativo à sua equipe.  

O fluxo de clientes que a Estante Virtual recebe diariamente
é resultado direto da qualidade desse trabalho: são mais de 10 mil livros vendidos por dia
(top3 na internet brasileira), com um índice de satisfação superior a 97%.

Pensar qualidade, bibliodiversidade e preço é pensar Estante Virtual. Venha trabalhar conosco!

## Nossa Cultura

Comprometimento, qualidade e alegria são nosso DNA. Ambiente descontraído sem esquecer de nossas
entregas e qualidade. Conseguimos dominar a cultura do trabalho remoto e executamos com muita
assertividade os rituais do desenvolvimento ágil com Scrum.

## Vagas

Para ocupar nossas vagas buscamos pessoas interessadas em trabalhar com as mais novas tecnologias,
aprender novas técnicas e métodos de trabalho. Focando sempre em entregas com qualidade.

## Estágios:

Independentemente das vagas, é necessário apenas ter alguma experiência com linux, docker e git,
além de saber alguma linguagem de programação como Python, Javascript ou Ruby.

Buscamos pessoas interessadas em aprender e desenvolver seu conhecimento utilizando nossos desafios para alavancar sua experiência. Entenda a descrição das vagas como o que você aprenderá enquanto estiver estagiando conosco e não como pré-requisito para se candidatar.

### Backend

* O que usamos :

  **Ruby**, Rails, Perl, Git, Rabbitmq, Mysql, Postgres, Resque, Sidekiq, Redis, AWS, OpsWorks, Docker e algumas *"cositas más"*

* O que queremos usar alem do que já usamos:

  **Python**, Django, Lambda AWS, SNS, ECS com Fargate, Zappa, Node, Elasticsearch, Kubernets e algumas *"cositas más"*

* Conceitos que seguimos:

  DDD, TDD, Scrum, Microserviços, Serverless, Arquitetura Hexagonal.

* Níveis de experiência desejáveis:

  Sênior, Pleno, Junior e Estagiário

**Comment by ARJOM** [comment]
A vaga ainda está aberta?

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Como posso me candidatar?
Abraços,
Daniel Siqueira
http://danielsiqueira.net
