### ISSUE TITLE
[Remoto] Desenvolvedor PHP Pleno/Sênior - Tech Recruiter Brazil

### ISSUE THREAD

**Issue by marinanlima** [backend-br/vagas#11599]
## Nossa empresa

Somos uma consultoria de Recrutamento e Seleção especializado para contratações de profissionais de Tecnologia. Nosso cliente atua no mercado de transformação digital para área logística 

## Descrição da vaga
Este profissional será responsável por desenvolver e manter nossas aplicações web, garantindo alta performance, escalabilidade e segurança.

**Atividades:**

Desenvolver e manter aplicações web utilizando PHP e Laravel.
Criar e consumir APIs RESTful.
Garantir a qualidade do código através de boas práticas de desenvolvimento, testes e revisões de código.
Colaborar com as equipes de design e produto para criar interfaces de usuário eficientes e intuitivas.
Otimizar aplicações para máxima velocidade e escalabilidade.
Identificar e corrigir problemas e bugs em tempo hábil.
Participar ativamente do ciclo de vida do desenvolvimento de software, desde a concepção até a implantação e manutenção.

## Local
Remoto

## Requisitos
Experiência comprovada como desenvolvedor PHP, com forte conhecimento do framework Laravel.
Sólidos conhecimentos em criação e consumo de APIs RESTful.
Familiaridade com bancos de dados relacionais (MySQL, PostgreSQL) e não relacionais (MongoDB, Redis).
Experiência com controle de versão usando Git.
Conhecimento em práticas de DevOps e ferramentas de CI/CD.

**Diferenciais:**
Experiência com metodologias ágeis (Scrum, Kanban).
Conhecimento em TDD/BDD.
Experiência com serviços em nuvem (AWS, Azure, Google Cloud).
Participação ativa em comunidades de código aberto.

## Benefícios
Vale Refeição R$25 dia.

## Contratação
PJ

## Como se candidatar
Enviar CV ou Linkedin com contatos para larissa@techrecruiterbrazil.app

### Nível
- Pleno
- Sênior

### Regime
- PJ

### Alocação
- Remoto

**Comment by celsodavid** [comment]
Candidatura enviada!

**Comment by devjunioralves** [comment]
Candidatura enviada!
