### ISSUE TITLE
[Remoto | São Paulo] Desenvolvedor .net (Pleno/Sênior) - Contabilidade.com

### ISSUE THREAD

**Issue by augusto-ramos-ft** [backend-br/vagas#11598]
## Nossa empresa

A Contabilidade.com é a primeira rede inteligente de contabilidades especializadas em profissionais liberais, autônomos e empresas de serviço. Aqui, profissionais regularizam sua prestação de serviços com a segurança de um atendimento consultivo, eficaz e 100% humano, e os escritórios contábeis se associam para deixar de lado a operação e crescer com segmentação a partir do fundo de marketing da rede.

## Descrição da vaga

- Desenvolvedor .net (Pleno/Sênior).

## Local

- Remoto ou no escritório da empresa em São Paulo / SP.

## Requisitos

- Experiência com linguagem de programação C# e .Net Framework;
- Experiência com APIs REST ou Serviços REST;
- Experiência com Qualidade de Código (SOLID, Design Patterns, Cl);
- Experiência com Testes Unitários e Mensageria RabbitMQ;
- Experiência com Banco de dados (SQL Server / Postgre / MongoDB);
- Conhecimento em Programação Orientada a Objetos e Eventos;
- Conhecimento em Metodologias Ágeis (SCRUM / Kanban);

Diferenciais:

- Conhecimento com linguagem de programação Python;
- Conhecimento em Docker Containers;
- Conhecimento em Node;
- Conhecimento em React;
- Conhecimento em RPA e/ou Testes Automatizados;

## Benefícios

- Descanso anual remunerado;
- Horário flexível.

## Contratação

- PJ.

## Como se candidatar

- Encaminhar CV ou link do Linkedin para: [augusto.ramos@contabilidade.com](augusto.ramos@contabilidade.com)

### Nível

- Pleno
- Sênior

### Regime

- PJ

### Alocação

- Remoto
- Híbrido

**Comment by conqlima** [comment]
Oi @augusto-ramos-ft , o email parece não existir. Tentei enviar um email e não consegui.

**Comment by augusto-ramos-ft** [comment]
> Oi @augusto-ramos-ft , o email parece não existir. Tentei enviar um email e não consegui.

Opa @conqlima arrumado, obrigado por avisar.

**Comment by lucasmudile** [comment]
Olá @augusto-ramos-ft o email parece que não existe, tente e estou recebendo erro.

**Comment by augusto-ramos-ft** [comment]
> Olá @augusto-ramos-ft o email parece que não existe, tente e estou recebendo erro.

Opa @lucasmudile, estranho, tente novamente, se não conseguir pode mandar para o meu email mesmo (augusto.ramos@contabilidade.com).

**Comment by augusto-ramos-ft** [comment]
Vaga preenchida, obrigado a todos pela participação.
