### ISSUE TITLE
[São Paulo] Desenvolvedor Java Jr/Pl

### ISSUE THREAD

**Issue by engaugusto** [backend-br/vagas#116]
## Descrição da vaga

Se você é um desenvolvedor, que gosta de desafios e resolver problemas.
Gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade de aprendizagem, motivado, que seja organizado no código, nos testes e na vida. 

Seu desafio será ajudar a criar a melhor solução para o cliente de acordo com o que ele pedir, e isso nunca é tão simples :)

* Você trabalhará principalmente:
* Com Java Backend (MySql + Oracle + Java + Jax-ws) e no Front com (Html+CSS+Jquery).
* Uma parte do sistema é feita em Apache Camel.
* Uma parte do sistema é feita em middleware com IBM Message Broker.
* Também será necessário ter conhecimentos de  Webservices (SOAP) ou criação de API REST.
* Também será necessário ter conhecimentos de SQL (Insert,Update,Delete e Select).
* Ajustar códigos feitos em Java
* Realizar testes unitários
* Não tem problema você não saber alguma tecnologia acima, desde que tenha vontade de aprender e empenho !

## Local

Escritório, São Paulo - Paraíso

## Benefícios

- Salário compatível com mercado, regime PJ/CLT/Cooperado.

- Ambiente de Startup.

- Possuímos um programa de mentoria que irá te ajudar a desenvolver seu potencial. 

### Diferenciais

- Profissionais de alta capacidade do mercado
- Aprendizagem com certeza !
- Mentoria
- Ensinamentos de framework Ibm Message Broker
- Ensinamentos de DevOps.

## Requisitos

**Obrigatórios:**
- Java
- Spring
- SQL
- RESTful API
- Ajax
- SOAP
- Webservices

**Desejáveis:**
- Git
- IBM Message Broker
- Excel
- TDD / BDD /DDD
- Conhecimentos de ESB / SOA.
- Maven

**Diferenciais:**
- projetos opensource
- portfólio no github 

## Contratação

PJ a combinar / CLT / Cooperado

# Nossa empresa

![Image of EcommIt](https://github.com/ecomm-it/brand/blob/master/IT-small.png?raw=true)

A Ecomm-IT é uma empresa madura no mercado de consultoria de tecnologia da informação principalmente no segmento financeiro, atualmente estamos expandindo nossas operações para diversos setores.

##Como se candidatar

Por favor envie um email para vagas@ecommit.com.br com seu CV anexado / portfolio e sua pretensão salarial

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
