### ISSUE TITLE
[Remota] developer Java / Data Scientist - FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [backend-br/vagas#11601]
Estamos buscando um Cientista de Dados com especialização em Inteligência Artificial e IA Generativa para se juntar à nossa equipe.

- Experiência em ciência de dados e IA, com forte foco em aprendizado de máquina, aprendizado profundo e IA generativa
- Proficiência em Java.

*Nossa oportunidade é necessário ter o INGLÊS AVANÇADO ok! A avaliação mínima do inglês é de C1, validaremos em entrevista no processo seletivo.*

Vaga 100% home office
Contratação
PJ +

Vantagens
● 80hs em banco de horas, como descanso, após 1 ano de contrato
● Possibilidade de bônus ate 2x o valor de prestação de serviços (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento pessoal
compra de livros, cursos, certificações e participação de eventos da área de tecnologia.

Como se candidatar
Por favor, envie um e mail para [vanessa.bruno@fdte.io](mailto:vanessa.bruno@fdte.io) - com seu CV anexado - enviar no assunto: Vaga  Java / Data Scientist 

Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by HenriqueGSena** [comment]
Curriculo enviado
