### ISSUE TITLE
[Remoto] Back-end developer - Na Empreender para Desenvolvedor JavaScript Pleno. 

### ISSUE THREAD

**Issue by serenarhempreender** [backend-br/vagas#11608]
## Nossa empresa

Somos uma empresa de tecnologia engajada no mercado de Dropshipping nacional e internacional . Nossa paixão pelo empreendedorismo é o que nos motiva!

## Descrição da vaga

Estamos em busca de profissionais com experiência mínima de 02 anos, que já tenha realizado integrações complexas, preferencialmente com plataformas de E-commerce.  

## Local

Vaga 100% Remota (home office).

## Requisitos

Conhecimento e experiências necessárias para ocupar a vaga:

-JavaScript;
-Banco de dados SQL;
-AdonisJS;
-API Rest;
-Integração utilizando padrão OAuth 2.0.

## Benefícios

- Bônus de natal;
- Participação de Lucros;
- Bônus de aniversário;
- Participação no programa férias & Co;
- Férias coletivas no fim de ano;
- Aulas de espanhol.

## Contratação

Contratação PJ, contrato inicial de 03 meses. 

## Como se candidatar

Informe os canais disponíveis para a aplicação na vaga.

### Nível

- Pleno

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by HenriqueGSena** [comment]
Curriculo enviado

**Comment by dlucioyauh** [comment]
Currículo enviado.

**Comment by ChaarH** [comment]
Currículo enviado.
