### ISSUE TITLE
[Remoto]  Senior/Pleno Java-Angular Fullstack Developer - CI&T

### ISSUE THREAD

**Issue by AlexiaMarques** [backend-br/vagas#11613]
## Nossa empresa

Somos especialistas digitais e impactamos as marcas mais valiosas do mundo. Construímos produtos e soluções digitais focados nas necessidades dos nossos clientes. Como uma nativa digital, trazemos um histórico de 29 anos de aceleração do impacto nos negócios por meio de soluções digitais completas e escaláveis. Com uma presença global de mais de 6.000 pessoas em estratégia, pesquisa, ciência de dados, design e engenharia, desbloqueamos o crescimento de primeira linha, melhoramos a experiência do cliente e impulsionamos a eficiência operacional.

Importante:
Para as pessoas residentes na Região Metropolitana de Campinas*, a presença nos escritórios é obrigatória, tendo que cumprir um mínimo de dias ao mês, estipulado pela empresa e projeto. Converse com o nosso time de recrutamento para saber mais informações sobre política de frequência vigente.

CI&T é uma empresa que oferece oportunidades iguais. Celebramos e valorizamos a diversidade de identidades e experiências vividas de nossos CI&Ters. Estamos empenhados em construir, promover e manter uma empresa e cultura diversificada, inclusiva e equitativa focada em criar um amanhã melhor.

Na CI&T, reconhecemos que inovação e transformação só acontecem em ambientes de trabalho diversificados, inclusivos e seguros. Nossas equipes são mais impactantes quando pessoas de todas as formações e experiências colaboram para compartilhar, criar e ouvir ideias.
Antes de candidatar as nossas oportunidades, confira a [Política de Conflito de Interesse](https://s28.q4cdn.com/106679464/files/doc_downloads/governance/2023/09/conflict-of-interest-policy-sept-23-v-3-0-docx-1.pdf) em nosso site.

Incentivamos fortemente pessoas de comunidades diversas e sub-representadas a se candidatarem às nossas vagas.

*Cidades que compõe a Região Metropolitana de Campinas: Americana, Artur Nogueira, Campinas, Cosmópolis, Engenheiro Coelho, Holambra, Hortolândia, Indaiatuba, Itatiba, Jaguariúna. Monte Mor, Morungaba, Nova Odessa, Paulínia, Pedreira, Santa Bárbara d'Oeste, Santo, Antônio de Posse, Sumaré, Valinhos, Vinhedo.

## Descrição da vaga

Buscamos pessoas localizadas no Brasil para trabalhar como Fullstack Developer em Java e Angular Sênior/Pleno/Júnior e atuar em um projeto do ramo financeiro.

## Local

Remoto

Importante:
Para as pessoas residentes na Região Metropolitana de Campinas*, a presença nos escritórios é obrigatória, tendo que cumprir um mínimo de dias ao mês, estipulado pela empresa e projeto. Converse com o nosso time de recrutamento para saber mais informações sobre política de frequência vigente.

## Requisitos

Júnior:
Responsabilidades

Realizar o entendimento das necessidades técnicas
Atuar no desenvolvimento e evolução de uma solução escalável e de alta performance
Criar o principal canal de parcerias do cliente
Codificar e estruturar testes automatizados para garantia de qualidade dos entregáveis
Você precisa conhecer
Conhecimento em Java, Springboot, TypeScript e Angular 8+
Conhecimento em Angular
Conhecimento em desenvolvimento de Microsserviços
Conhecimento em testes unitários
Conhecimento em processos de CI/CD
Conhecimento em Docker / conteinerização de aplicações
Conhecimento em processo de SCM com Git

Ter prática com:

Desenvolvimento Frontend
Desenvolvimento Backend
Comunicação para garantir o alinhamento de todas as pessoas do time e do cliente
Entendimento adequado de demandas de negócio
Qualidade de código e boas práticas de programação

Pleno/Sênior
Responsabilidades:

Realizar o entendimento das necessidades técnicas, participando de inceptions e refinamentos;
Atuar no desenvolvimento e evolução de uma solução escalável e de alta performance;
Criar o principal canal de parcerias do cliente.
Requisitos para este desafio:

Desenvolvimento backend em Java 8 e 21;
Desenvolvimento frontend;
Testes automatizados;
Cloud Azure;
Frameworks: Springboot, Angular 8+, Nodejs;
Microsserviços;
Familiaridade com processos de CI / CD;
Testes automatizados;
Conhecimento de padrão de projeto;
Conhecimento em Docker / conteinerização de aplicações;
Git;
Comunicação para garantir o alinhamento de todas as pessoas do time e do cliente;
Entendimento adequado de demandas de negócio, bem como refinamento técnico;
Qualidade de código e boas práticas de programação;
Criticar e buscar melhoria contínua;

Diferencias:

Excelentes habilidades de comunicação e capacidade de trabalhar em equipe;
Autonomia e Proatividade.

## Benefícios

Plano de saúde e odontológico;
Vale-alimentação e refeição;
Auxílio-creche;
Licença paternagem estendida;
Gympass
PLR;
Seguro de Vida;
Parceria com plataforma online de saúde mental;
CI&T University;
Clube de descontos;
Programa de Apoio: financeiro; orientação psicológica; nutricionista e mais;
Curso gestante e paternagem responsável;
Parceria com plataformas de cursos online;
Plataforma para aprendizagem de idiomas;
E muitos outros.
Mais detalhes sobre os nossos benefícios aqui: https://ciandt.com/br/pt-br/carreiras

## Contratação

CLT

## Como se candidatar

Enviar currículo atualizado, informando disponibilidade de início e pretensão salarial, considerando a contratação CLT, para mim via LinkedIn: https://www.linkedin.com/in/alexia-marques/
Estamos com mais de 1200 vagas para fechar até dezembro, a grande maioria delas são no escopo aqui apresentado, devido a esse grande volume não temos um tempo de resposta definido, mas pode estar acima do esperado, aguardem com paciência serem respondidos.

## Labels

Java
Spring
Angular
Fullstack
Scrum
Azure
Docker
Git
Testes

### Nível
- Júnior
- Pleno
- Sênior

### Regime
- CLT - segunda a sexta.

### Alocação
- Remoto
- Híbrido

**Comment by HenriqueGSena** [comment]
Curriculo enviado

**Comment by JMustang** [comment]
Curriculo enviado

**Comment by JoaoVitorMadeiro** [comment]
amei a vaga pena que eu sou so back end, mas mandei ela

**Comment by AlexiaMarques** [comment]
Vaga Júnior agora somente afirmativa para mulheres, obrigada a todos que se candidataram, podem ser considerados para oportunidades futuras!
