### ISSUE TITLE
[Híbrido] Backend Java Developer - Truppe!

### ISSUE THREAD

**Issue by Camila-Goms** [backend-br/vagas#11610]
## Nossa empresa

A [Truppe](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 4 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital.

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

## Descrição da vaga

Estamos buscando um Desenvolvedor Backend Java experiente para integrar nossa equipe inovadora na área de tecnologia da informação. Você terá a oportunidade de trabalhar com tecnologias avançadas, contribuindo para o desenvolvimento de soluções que impactam diretamente nossos produtos e serviços.

## Local

Híbrido em São Paulo -SP, Itaim Bibi (3x presenciais e 2x home office). **SEM POSSIBILIDADE DE REMOTO!**

## Responsabilidades

• Desenvolver e manter aplicações robustas utilizando Java 21+ e Spring.

• Implementar e gerenciar integrações com sistemas de mensageria como Kafka.

• Trabalhar com bancos de dados NoSQL e SQL, incluindo Redis, MongoDB e MySQL.

• Projetar e implementar APIs RESTful e microsserviços.

• Escrever testes automatizados para garantir a qualidade e a confiabilidade do código.

• Colaborar com equipes multifuncionais para definir e implementar soluções tecnológicas inovadoras.

• Documentar processos, arquiteturas e designs de software para referência futura e treinamento.

## Requisitos

• +3 anos de experiência com Java e sólida experiência em Java 21+ e Spring.

• Conhecimento em Kafka, Redis, MongoDB e MySQL.

• Experiência em desenvolvimento de APIs RESTful.

• Experiência com testes automatizados.

• Familiaridade com a infraestrutura AWS Cloud Stack.

• Forte compreensão de práticas modernas de desenvolvimento ágil, incluindo CI/CD.

• Excelentes habilidades de comunicação e capacidade de trabalhar eficazmente em equipes multidisciplinares.

• Formação acadêmica em Ciência da Computação, Engenharia de Software ou área relacionada.

## Benefícios

• Vale Refeição (R$ 858,65 /mensal);
• Vale Alimentação (R$ 663,48 /mensal);
• Assistência Média e Odontológica;
• Seguro de Vida em Grupo;
• Dia de folga de aniversário.

## Contratação

CLT a combinar.

## Como se candidatar

Envie um email para [camila.recruiter@outlook.com](mailto:camila.recruiter@outlook.com) ] com seu currículo atualizado, link do perfil do Linkedin (se tiver) e pretensão salarial CLT.

Enviar no assunto: Backend Java Developer.

### Nível

Pleno a Sênior.

**Comment by Mauricio-MdS** [comment]
Olá! O requisito menciona '3 anos de experiência sólida com Java 21+'. Entretanto o Java 21 foi lançado há menos de um ano.
