### ISSUE TITLE
[Remoto] Pessoa Analista de Desenvolvimento de Sistemas Pleno (Back-End) - Neoway/B3

### ISSUE THREAD

**Issue by ferlintec** [backend-br/vagas#11611]
## Nossa empresa

Entre para a história de construção do maior Hub de Dados e Analytics do Brasil.
Além de você contribuir diretamente neste objetivo, você estará se desenvolvendo constantemente, por meio de grandes desafios de negócio, junto a um time de alto impacto. Na [Neoway](https://www.neoway.com.br/), acreditamos em fazer as coisas de forma inovadora, colaborativa, responsável e com foco no cliente.

## Descrição da vaga

# Missão do cargo:

Como Pessoa Desenvolvedora de Software você fará parte do time de desenvolvimento da BU de Loss Prevention e será responsável por agregar conhecimento técnico ao time, sustentando, evoluindo ou construindo parte das soluções de nossa plataforma, garantindo a segurança, buscando soluções para situações do dia a dia, visando sempre o trabalho harmônico em equipe, a qualidade do código e da arquitetura em geral.

# Como será o seu dia a dia no time:

Trabalhar na concepção de soluções técnicas, na quebra de tarefas, planejamento e na execução das demandas;
Garantir a qualidade das entregas, participando e fomentando práticas de Code Review e desenvolvimento orientado a testes;
Manter, monitorar e garantir a eficiência dos serviços construídos e de responsabilidade do seu time;
Participar das dinâmicas de trabalho adotadas pelo time;
Trabalhar de forma colaborativa no processo de melhoria contínua do seu time;
Colaborar nas definições de arquitetura e escalabilidade dos nossos produtos.
Trabalhar com linguagens de programação de backend como Golang e NodeJS
Criar soluções com base em uma arquitetura distribuída e de microserviços
Criar soluções resilientes e que estejam dentro dos padrões altos de performance
Observar o desenvolvimento seguro e estar sempre por dentro de atualizações de segurança e critérios relevantes relacionados ao desenvolvimento seguro

# Responsabilidades e atribuições em sua jornada:

Idealizar e construir novas soluções (análise e desenvolvimento);
Conceber melhorias nas arquiteturas atuais e de novas soluções;
Suportar questões técnicas dos projetos, em suas diversas fases, propondo soluções, indagando caminhos. Sempre de forma crítica e construtiva;
Recomendar modificações e melhorias em processos, visando a eficiência das áreas;
Solucionar/encaminhar ou ainda escalar impedimentos técnicos apontados pelo time;
Contribuir com o crescimento técnico do time, efetuando treinamentos, aconselhamentos (mentoria) e supervisão de pessoas desenvolvedoras menos experientes, sempre que necessário;
Contribuir para a produção de padrões e documentação de melhores práticas para a sua equipe e garantir que o desenvolvimento atenda a esses padrões;
Apoiar em práticas de desenvolvimento ágil.

# Requisitos e qualificações para o cargo:

Compreensão de arquiteturas para processamento de grandes volumes de dados (repositórios, filas, microsserviços, etc);
Domínio de conceitos e boas práticas de desenvolvimento de software (da concepção à entrega, sustentação e operação, desenvolvimento orientado a testes, escrita e documentação de códigos, code review, etc);
Conhecimento intermediário ou avançado em linguagem para back-end:
Linguagens de programação (Go, NodeJS, SQL);
Banco de dados relacionais, não relacionais, colunares/AVRO e elásticos (PostgreSQL, MongoDB, etc);
Estrutura Cloud (GCP);
Pró-eficiência no desenvolvimento de:
API Rest;
Programação concorrente e escalável;
Conhecimento nos processos de versionamento e práticas CI/CD;
Experiência com práticas de Code Review e Feedback;
Experiência com desenvolvimento orientado a testes;
Apresentar boa comunicação, pois somos um time bastante pró ativo e com necessidade de articulação de ideias;
Encarar as mudanças como oportunidades e aprender com seus erros;
Facilidade em compartilhar conhecimento;
Promover nossa cultura e valores;
Saber como construir com outras pessoas e desfrutar do trabalho em equipe.

# Alguns diferenciais que estamos de olho. Mas não se preocupe caso não tenha, ajudamos você nessa parte:

Conhecimento dos conceitos de Big Data, Data Lake, Metadados com as perspectiva das boas práticas e requisitos de governança de dados;
Teoria e prática em qualidade de dados (Dimensões, Profiling, Data Quality Assessment);
Conhecimento avançado em Go;
Conhecimento de infraestrutura (Terraform, Ansible);
Conhecimento em schedulers (Crontab, Jenkins, Airflow, etc);
Conhecimento do ecossistema de containers (Docker, Kubernetes);
Conhecimento em serviços de mensageria (PubSub, SNS, Kafka).
Conhecimento de BigQuery, ElasticSearch

## Local

Remoto
A sede está localizada em Florianópolis, podendo ser híbrido.

## Requisitos

Informe os requisitos obrigatórios e desejáveis para a vaga.

## Benefícios

🍲 Vale Alimentação/Refeição;
🚘 Auxílio transporte;
🩺Plano de Assistência médica e odontológica;
👨‍👩‍👦 Licença Maternidade e paternidade estendida;
💳PPR (Programa de participação de resultados);
🏋️‍♀️Gympass - plataforma que te dá acesso a mais de 18 mil academias no Brasil. Nas academias conveniadas são oferecidas mais de 700 modalidades esportivas;
💛 Wellz - plataforma de saúde mental e bem estar, com terapia gratuita e muito mais;
🙆🏽Ginástica Laboral (presencial) 1x na semana;
🧘🏻Quick Massagem (presencial) 2x mês;
👶🏽Auxílio Creche;
🎈Day off no aniversário;
🚑 Seguro de Vida;
📚 Parcerias Educacionais com Faculdades e Escolas de Ensino.

## Contratação

CLT

## Como se candidatar

Acesse este [link](https://www.linkedin.com/jobs/view/3987539301/) para se candidatar.

### Nível

- Pleno

### Regime

- CLT

### Alocação

- Remoto

**Comment by evertonbez** [comment]
Enviado!
