### ISSUE TITLE
[São Paulo] Desenvolvedor Python/Django Sênior - Hunter Hunter

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#11623]
Desenvolvedor Python/Django Sênior

Vaga 100% Presencial SP - Ao lado da Estação Moema - Linha Lilás.

Entre R$ 8.000,00 a R$ 9.000,00 CLT.

Requisitos:
    • Mais de 4 anos de experiência como Desenvolvedor Python/Django;
    • Formação em Ciência da Computação, Sistemas da Informação, Análise e Desenvolvimento de Sistemas, Desenvolvimento de Jogos;
    • Domínio comprovado em desenvolvimento Python e Django;
    • Experiência com Banco de Dados (Relacionais e Não-Relacionais);
    • Boa comunicação oral e escrita;
    • Inglês técnico.

Responsabilidades:
       • Desenvolvimento e manutenção de sistemas;
    • Desenvolvimento com código limpo e usando ao máximo as features existentes no framework Django;
    • Criação e manutenção de HTML responsivos usados em templates do Django;
    • Desenvolvimento de Integração de sistemas com Rest API e Django Rest Framework;
    • Integração de ambientes multi-linguagem;
    • Entrega de código para homologação do time do QA previamente testado e validado entre o time.

Jornada de Trabalho: 09:00 às 18:00, segunda a sexta.

Principais Benefícios:
    • Jornada de Trabalho Flexível;
    • Seguro de Vida - 100% custo empresa;
    • Assistência Médica Bradesco - 100% custo empresa;
    • Assistência Odontológica Bradesco: (custo do colaborador).
    • VR Flex: R$990,00;
    • Auxílio creche - Filhos até 5 anos e 11 meses.

Salário CLT.

Somos uma empresa com atuação global especializada no desenvolvimento de software para jogos. Líder em nosso setor, trabalhamos com uma série de tecnologias e plataformas: software embarcado, máquinas físicas, web e mobile. Nossa missão é levar inovação e novas experiências aos jogadores.

Se tem interesse e os requisitos da oportunidade entre em contato pelo Linkedin abaixo, informando qual é a oportunidade:[https://www.linkedin.com/in/erickamarquesb/]

**Comment by JuanBindez** [comment]
> Desenvolvedor Python/Django Sênior
> 
> Vaga 100% Presencial SP - Ao lado da Estação Moema - Linha Lilás.
> 
> Entre R$ 8.000,00 a R$ 9.000,00 CLT.
> 
> Requisitos: • Mais de 4 anos de experiência como Desenvolvedor Python/Django; • Formação em Ciência da Computação, Sistemas da Informação, Análise e Desenvolvimento de Sistemas, Desenvolvimento de Jogos; • Domínio comprovado em desenvolvimento Python e Django; • Experiência com Banco de Dados (Relacionais e Não-Relacionais); • Boa comunicação oral e escrita; • Inglês técnico.
> 
> Responsabilidades: • Desenvolvimento e manutenção de sistemas; • Desenvolvimento com código limpo e usando ao máximo as features existentes no framework Django; • Criação e manutenção de HTML responsivos usados em templates do Django; • Desenvolvimento de Integração de sistemas com Rest API e Django Rest Framework; • Integração de ambientes multi-linguagem; • Entrega de código para homologação do time do QA previamente testado e validado entre o time.
> 
> Jornada de Trabalho: 09:00 às 18:00, segunda a sexta.
> 
> Principais Benefícios: • Jornada de Trabalho Flexível; • Seguro de Vida - 100% custo empresa; • Assistência Médica Bradesco - 100% custo empresa; • Assistência Odontológica Bradesco: (custo do colaborador). • VR Flex: R$990,00; • Auxílio creche - Filhos até 5 anos e 11 meses.
> 
> Salário CLT.
> 
> Somos uma empresa com atuação global especializada no desenvolvimento de software para jogos. Líder em nosso setor, trabalhamos com uma série de tecnologias e plataformas: software embarcado, máquinas físicas, web e mobile. Nossa missão é levar inovação e novas experiências aos jogadores.
> 
> Se tem interesse e os requisitos da oportunidade entre em contato pelo Linkedin abaixo, informando qual é a oportunidade:[https://www.linkedin.com/in/erickamarquesb/]

Gostei da vaga e do jeito de divulgar.

**Comment by JuanBindez** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrário, a fecharemos automaticamente em 02 dias.

melhor fechar hoje
