### ISSUE TITLE
[São Paulo] Backend Ruby on Rails Developer [Petlove]

### ISSUE THREAD

**Issue by DayaneVeronez** [backend-br/vagas#1163]
## Descrição da vaga

Buscamos pessoas apaixonadas e talentosas, que nos ajudem a concretizar novas ideias e contribuam para o desenvolvimento da nossa plataforma de produtos digitais.
Estamos crescendo a todo vapor e criando novos produtos, sempre com a meta de fazer os pets mais felizes e saudáveis. Se você é um(a) profissional analítico(a), com experiência em desenvolvimento back-end e forte background em Ruby on Rails, temos a oportunidade perfeita para você.

**Como Backend Developer os seus desafios serão:**

- Trabalhar em equipe multidisciplinar, usando metodologia ágil para criação e evolução de produtos;
- Escrever código limpo, reutilizável e de fácil manutenção;
- Ajudar a definir e manter padrões de design e arquitetura dos sistemas;
- Deployment, code review, documentação e monitoramento dos sistemas;
- Apoiar na integração entre sistemas dentro e fora da equipe;
- Levantamento de requisitos, pesquisa e provas de conceito;
- Tomar decisões técnicas quando for preciso, envolvendo e alinhando equipe, clientes e stakeholders;
- Atuar como mentor, colaborando com o aprendizado dos desenvolvedores jr.

## Local

Escritório - [São Paulo - Berrini](https://goo.gl/maps/HarDqbMRWCL2)

## Benefícios

- Assistência médica e odontológica 100% custeada pela empresa; 
- Vale Refeição (podendo dividir com Vale Alimentação; 
- Crédito para Snacks; - Bicicletário no prédio; 
- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim; 
- Day-off de aniversário; 
- Ambiente descontraído e dinâmico; 
- Parcerias com descontos; 
- Desconto em produtos no site; 
- PLR - Atrelado a metas; 
- E claro, Pet Friendly, pets são muito bem vindos no escritório!! 

![Petlove Image](https://www.petlove.com.br/static/uploads/images/petcool.png)

## Requisitos

**O que esperamos de você:**

- Ruby / Rails;
- Webservices / REST;
- GIT;
- Banco de Dados (Postgres ou MySQL);
- Cloud (AWS ou Google Cloud);
- TDD / BDD;
- Processamento e Batch / Mensageria;
- Linux;
- JavaScript;
- OOP e Design Patterns;
- Docker;
- NoSQL;
- Redis ou Memcached;
- Serverless.

**Diferenciais:**

- Kubernetes
- Elastic Search
- Elixir
- JavaScript
- NodeJS
- VueJS, React ou Angular 2+
- Machine Learning
- Big Data
- Python
- ShellScript
- Golang

## Contratação

CLT

## Nossa empresa

A Petlove é o maior petshop online do Brasil. Nascemos em 1999 com a proposta pioneira de vender produtos pet pela internet e, hoje, são 20 anos entregando alegria na casa de milhares de famílias.

## Como se candidatar

Por favor, cadastre-se em nossa página de carreiras: https://petlove.gupy.io ou envie um e-mail para vagasti@petlove.com.br com seu CV anexado - enviar no assunto: Vaga Backend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: dayane.cruz@petlove.com.br

## Labels

- CLT
- Pleno
- Sênior
- Presencial

### Conquistas e Premiações

[Melhores Apps 2017 na Apple Store](https://www.petlove.com.br/dicas/aplicativo-petlove-e-eleito-como-um-dos-melhores-ano-pela-app-store)

Primeiro pet shop Diamante Ebit

[Loja mais querida Ebit 2017](https://www.ebit.com.br/premio-ebit/2017)

[Loja mais querida Ebit 2018](https://www.ebit.com.br/premio-ebit/2018)

[RA1000 no Reclame Aqui](https://www.reclameaqui.com.br/empresa/petlove-petsupermarket/)

[Case de site mobile - Google 2018](https://www.youtube.com/watch?v=PsgW-0M67TQ&feature=youtu.be&t=17m17s)

**Comment by emaiax** [comment]
Sou assinante da PetLove e adoraria trabalhar aí, só pelo bom trabalho que fazem! <3

**Comment by DayaneVeronez** [comment]
Manda o seu currículo para gente!!
