### ISSUE TITLE
[Portugal] Back-end developer - Node @YellowIpe

### ISSUE THREAD

**Issue by YellowIpe** [backend-br/vagas#11645]
## Nossa empresa

Temos a missão de inspirar a conexão da tecnologia com as pessoas, fomentamos o melhor de nossos profissionais através de nossa expertise em encontrar e atrair os melhores talentos para os melhores projetos. O Foco nas Pessoas, Colaboração e Comprometimento são os pilares que nos guiam nessa trajetória.  

## Descrição da vaga

A YellowIpe está recrutando um Desenvolvedor Back End Sênior - Node  para integração direta em uma projeto internacional.

## Local

Remoto com necessidade de mudança para Portugal em 6-12meses.
Patrocinio integral de visto.

## Requisitos

- Pelo menos 6 anos de experiência com desenvolvimento web back-end usando NodeJS com TypeScript ou JavaScript;
- Conhecimento em bancos de dados relacionais/SQL: preferencialmente PostgreSQL, mas SQL Server ou Oracle são aceitáveis;
- Experiência com testes automatizados;
- Preferência por Linux e domínio da linha de comando;
- Fluência em inglês, tanto falado quanto escrito;
- Autonomia e mentalidade voltada para resolução de problemas;
- Mente analítica, boa em antecipar problemas potenciais;
- Investigador de causas-raiz de problemas técnicos – não tem medo de ir até o fundo da questão!
- Compreensão abrangente do ciclo de vida de uma aplicação e das melhores práticas de suporte.

## Contratação

 CLT ou PJ 

## Como se candidatar

Por favor envie um email para recrutamento@yellowipe.io com seu CV anexado - enviar no assunto: Vaga FrontEnd React

### Nível

- Sênior
- Especialista

### Regime

- PJ
- CLT

### Alocação

- Remoto
- Híbrido
- Presencial

**Comment by evertonbez** [comment]
Enviado!
