### ISSUE TITLE
[São Pauo][Alocado][Python] Desenvolvedor Python Pleno ou Senior

### ISSUE THREAD

**Issue by victtorvpb** [backend-br/vagas#1165]
# Como se candidatar

Enviar email com curriculo para rh@skyone.solutions com cópia para victor.braga@skyone.solutions

# Sobre nós

Com um ambiente jovem e inovador, a startup referência em Cloud Computing com inteligência, busca valorizar seus profissionais, auxiliando na realização dos seus sonhos e no cumprimento de suas metas pessoais e profissionais. Em 2018, a [Sky.One](https://skyone.solutions/) foi reconhecida pela autoridade global Great Place to Work (GPTW) como um ótimo lugar para trabalhar. Além de figurar entre as top 25 startups do LinkedIn, que identificou os lugares mais desejados por profissionais brasileiros.

# Descrição da Vaga

Você encontrará um time especializado em Python (Django e Flask), AWS, trabalhando com Scrum e terá a oportunidade de desempenhar um papel chave na construção de uma startup que está em crescimento acelerado, além de desenvolver software inovador no segmento de Cloud com tecnologia de ponta.

**Requisitos Obrigatórios:**

- Python
- Framework Django ou Flask
- PostgreSql
- GIT

**Diferenciais:**

- Plataforma AWS ou GCP
- AngularJs
- Docker
- ElasticSearch
- Logstash
- Ansible
- Jenkins
- React
- Redis
- RabbitMq
- Testes unitários e de integração
- Sqlalchemy
- Framework Nameko

**Pré-requisitos:**

- Experiência comprovada na função
- Superior Completo na área

# Observações

Não aceita remoto, somente presencial.

# Labels

- CLT
- Python
- Alocado
- Pleno
- SÊnior

**Comment by xspager** [comment]
Essa vaga ainda está aberta?

**Comment by victtorvpb** [comment]
@xspager esta aberta ainda
