### ISSUE TITLE
[São Paulo] Full-Stack Golang/React Developer na Estratégia Concursos

### ISSUE THREAD

**Issue by gustavohenrique** [backend-br/vagas#1166]
A Estratégia Concursos está há 8 anos no mercado e agora está montando um time interno para criar novos produtos voltados para a área de educação e concurso público. Nossa cultura de trabalho é baseada na entrega de valor e nosso processo focado na melhoria contínua. Não temos ainda processos bem definidos. Nós mudamos as coisas no início de cada Sprint de acordo com o feedback discutido nas retrospectivas. Não gostamos de burocracia e somos focados nas soluções e não nos problemas. Estamos com um desafio bem interessante de lançar novos produtos para mais de 5 milhões de clientes.

### Perfil que procuramos

- Pessoas que apresentem soluções e não reclamações. "Não gostou? Então qual a sua sugestão para melhorar?".
- Quem realmente tem paixão por tecnologia, gosta de aprender, discutir e compartilhar conhecimento.
- Aqueles que conseguem focar no simples, e não trazer complexidade ao sistema.
- Quem gosta de meter a mão na massa, vai lá e faz, sem mimimi.

### Conhecimentos técnicos

- Buscamos pessoas que gostem e conheçam Go. Se souber Javascript também, melhor ainda.
- Gostamos de profissionais Full-stack, não para trabalhar o dobro, é que algumas vezes é necessário trabalhar com Front-end e o Back-end para entregar uma User Story.
- Conhecimento em ferramentas de infra-estrutura ágil/DevOps e familiaridade com os principais serviços da AWS é desejável.
- Cultura de testes automatizados.

### Tecnologias que utilizamos

- GitHub
- Go
- React
- Kubernetes
- AWS

### O que oferecemos

- Cultura de desenvolvimento baseada em metodologias ágeis.
- Ótimo ambiente para quem curte tecnologia e quiser aprender e praticar.
- Flexibilidade de horário.
- Macbook Pro novo com 16GB + monitor externo.
- Livros e mais livros para quem quer estudar.
- Salário acima de mercado.

A vaga é presencial para o bairro do Brooklin, próximo a estação de trem Berrini, na cidade de São Paulo/SP.

Nosso processo possui apenas 2 passos:

- Análise do desafio: https://github.com/estrategiaconcursos/desafio-desenvolvimento
- Batepapo entre o candidato e o time.

Quem estiver interessado, basta entregar o desafio junto com o currículo em PDF (ou perfil do Linkedin) para talentos@estrategiaconcursos.com.br.

**Comment by gustavohenrique** [comment]
Labels: `golang`, `react`, `aws`, `devops`, `kubernetes`

**Comment by brunooomelo** [comment]
qual nivel? Jr, Pleno, Senior?
