### ISSUE TITLE
[Remoto] Back-end developer (R$ 80K - 225K) - Milenio Capital

### ISSUE THREAD

**Issue by milenio-recruiter** [backend-br/vagas#11688]
## Nossa empresa

A Milenio é uma gestora de recursos focada na originação, estruturação, financiamento e gestão de produtos de crédito, com ênfase na redução da distância entre empresas e investidores. Nossa missão é unir o melhor do crédito com tecnologia. A empresa conta com um time de +50 colaboradores, sendo liderada por sócios com profundo conhecimento no mercado de crédito e tecnologia.

## Descrição da vaga

Estamos buscando por um(a) desenvolvedor(a) apaixonado(a) e motivado(a) para:
- Colaborar na construção de nossas APIs;
- Atuar com as tecnologias mais atuais do mercado;
- Realizar análises e manutenções em nossos sistemas existentes;
- Ficar por dentro das tendências e novidades do setor;
- Demonstrar uma insaciável vontade de aprender e evoluir.

## Local

Full remoto, ou em nossos escritórios em:
- São Paulo (Itaim Bibi);
- Rio de Janeiro (Ipanema).

## Requisitos

Obrigatórios:
- Experiência com pelo menos uma linguagem de backend;
- Zelo pela qualidade do código;
- Familiaridade com git, padrões de projeto e design patterns;
- Conhecimento de banco de dados relacional e não-relacional;
- Autoaprendizado e desejo intenso de se aprimorar.

Desejáveis:
- Experiência em desenvolvimento Python com FastAPI;
- Experiência com MongoDB e SQL;
- Experiência com AWS.

## Benefícios

- Plano de saúde e odontológico Bradesco
- Vale Refeição de R$ 1.034,00/mês
- Vale Alimentação de R$ 636,00/mês

## Contratação

Regime CLT, com bônus semestral atrelado ao seu desempenho e ao da empresa. A remuneração anual é entre R$ 80K - 162K para juniors e entre R$ 110K - 225K para plenos, além dos benefícios.

## Como se candidatar

Interessados devem enviar o currículo por e-mail com o título “Vaga de Desenvolvedor” para selecao.dev@milenio.capital.

### Nível

- Júnior
- Pleno

### Regime

- CLT

### Alocação

- Remoto

**Comment by pedromelocf** [comment]
Currículo enviado.

**Comment by VitorGreff** [comment]
Currículo enviado

**Comment by lucianowribeiro** [comment]
Currículo enviado

**Comment by RafaelCamilloJorge** [comment]
Currículo enviado.

**Comment by robsonluissagaz** [comment]
Enviei meu currículo para o E-mail mencionado.

Segue o link para mais detalhes profissionais.
https://robsonluissagaz.github.io/

Desde já agradeço a oportunidade.

**Comment by staubjoao** [comment]
Currículo enviado

**Comment by tarffie** [comment]
Currículo enviado!

**Comment by Italoomoura** [comment]
Currículo enviado!

**Comment by JoaoFerrareis02** [comment]
CURRÍCULO ENVIADO!!!

**Comment by JoaoVitorMadeiro** [comment]
Curriculo enviado

**Comment by dlucioyauh** [comment]
Currículo enviado.

**Comment by Kuroshi7** [comment]
Currículo enviado

**Comment by EdmilsonMedeiros** [comment]
Currículo enviado.
