### ISSUE TITLE
[Alocação] Desenvolvedor Sênior - DataEX

### ISSUE THREAD

**Issue by leticia-blanco** [backend-br/vagas#11687]
**Sobre a empresa:**
A DataEX é uma empresa especializada em dados e parceira Microsoft e AWS, com mais de 10 anos de atuação no mercado.
 
A vaga que temos aberta seria para alocação em um dos nossos clientes.
 
**Requisitos:**
• **Linguagens:** Python, C#
• **Ferramentas**: Bash
• **Bancos de Dados:** SQL lite
• **API REST:** Desenvolvimento e consumo de APIs
• **Versionamento:** Git
• **Cloud**: Azure
• **Protocolo de comunicação:** MQTT (Message Queuing Telemetry Transport)
• **Configurações de Rede:** Familiaridade com roteamento, configuração de VLANs, balanceamento de carga, failover, firewall e VPNs (como OpenVPN, IPsec, WireGuard)
 
**Desejável:**
• **Conhecimento de Modems LTE:** Entendimento sobre o funcionamento de modems LTE (RUTX12 possui dual LTE) e a configuração de failover e load balancing entre eles.
• **IoT:** Se o script envolve conectividade IoT, é importante entender como os dispositivos IoT se conectam ao roteador e interagem com ele.
 
**Atividades:**
• Coletar dados da control unit dos trens através de modems LTE (RUTX12 possui dual LTE) e a configuração de failover e load balancing;
• Transmitir os dados coletados para a nuvem.  
 
**OBS.: Disponibilidade de atuação presencial. A empresa é localizada em Osasco - SP.**

**Modelo de contratação:**

**PJ** - O modelo do contrato é PJ e o prazo inicial é de 02 meses. Todavia, há possibilidade de prorrogação do contrato. 

**Como se candidatar?**

Envie seu CV para: leticia.blanco@dataex.com.br

OU 

Acesse o link e se inscreva: https://dataex.vagas.solides.com.br/vaga/486409

**Nível:**
-Sênior

**Regime:**
-PJ - contrato de 02 meses com possibilidade de prorrogação por parte do cliente

**Alocação:**
-Modelo de Outsourcing - presencial em Osasco, SP

**Comment by guligon90** [comment]
Olá @leticia-blanco existem alguns problemas na descrição dos requisitos da posição:

1. Existe um erro tipográfico em "Phyton". Escreve-se "Python".

2. Bash não é uma linguagem, e sim um interpretador de comandos em ambiente Unix (GNU/Linux). Estaria mais adequado incluir ele em uma categoria de "Ferramentas" por exemplo.

**Comment by leticia-blanco** [comment]
Olá @guligon90 

Muito obrigada pelos apontamentos. As alterações foram feitas.
