### ISSUE TITLE
[Remoto] Back-end developer @ Uplexis

### ISSUE THREAD

**Issue by raissaime** [backend-br/vagas#11697]
## Nossa empresa

A upLexis é uma empresa de tecnologia pioneira em mineração de dados, especializada no mercado de compliance. Nossa plataforma, upMiner, é amplamente utilizada por empresas para coletar informações em tempo real, agilizando processos de análise de risco. Com uma missão centrada na ética e transparência, buscamos fornecer inteligência e insights para decisões mais assertivas, contribuindo para a redução de fraudes e corrupção. Há 20 anos no mercado, a upLexis cresce de forma sustentável, focada na excelência, inovação, e na satisfação dos clientes, sempre com responsabilidade social.

## Descrição da vaga
Desenvolvedor Back-End Pleno/Sênior
Tempo mínimo de experiência - 3 anos
Budget da vaga: até R$ 9.5K

## Responsabilidades
- Implementar e construir soluções web colaborando estritamente com equipes multi-disciplinares;                
- Entregar soluções alinhadas com as melhores práticas do mercado, otimizando e refinando aplicações legadas, garantindo desempenho, escalabilidade e segurança;            
- Implementar testes para garantir a manutenabilidade da solução;                
- Criar e manter as documentações da solução;               
- Apoiar a evolução continua e propagar as boas práticas da stack de desenvolvimento.

## Local

Remoto 🌎 

## Requisitos

- Stack Web : 
-  HTML + CSS + JS
- PHP - Laravel        
- DB Relacional - MySQL, Postgres, Oracle
- DB NoSQL - Aurora, Mongoo, MariaDB
- Boas Práticas de Codificação - SOLID, Clean Code, Design Patterns      

## Indispensável
O candidato deverá dispor de tempo integral de trabalho em horário comercial, no horário de São Paulo, e pode residir em qualquer região do país, pois o trabalho deve ser executado remotamente, sem a necessidade de presença física na empresa. As reuniões síncronas de equipe são feitas diariamente pelo GMeet da empresa.

O candidato deve possuir seu próprio equipamento e conexão Internet, e deverá acessar os recursos da empresa através de uma VM (máquina virtual) Linux (Ubuntu), padronizada para toda a empresa.

## Benefícios

- Assistência médica - sem desconto do funcionário;
- Vale refeição no valor de R$ 880,00;

## Contratação

CLT

## Como se candidatar

Enviar currículo com o assunto: Desenvolvedor Backend e pretensão salarial para: raissaime@outlook.com

### Nível
- Pleno

### Regime
- CLT

### Alocação

- Remoto

**Comment by phoenix0022** [comment]
I am interested, and already sent hi via Linkedin.
