### ISSUE TITLE
[São Paulo] Desenvolvedor IBM Message Broker - Alocação Projeto

### ISSUE THREAD

**Issue by engaugusto** [backend-br/vagas#117]
## Descrição da vaga

Se você é um desenvolvedor, que gosta de desafios e resolver problemas.
Gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade de aprendizagem, motivado, que seja organizado no código, nos testes e na vida. 

Seu desafio será ajudar a criar a melhor solução para o cliente de acordo com o que ele pedir, e isso nunca é tão simples :)

* Você trabalhará principalmente:
* Com IBM Message Broker (Plataforma ESB da IBM).
* Com SQL 
* Versionando os fontes no GIT
* Realizar testes e evidências

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Salário compatível com mercado, regime PJ/CLT/Cooperado.

- Ambiente de Startup.

- Possuímos um programa de mentoria que irá te ajudar a desenvolver seu potencial. 

### Diferenciais

- Profissionais de alta capacidade do mercado
- Aprendizagem com certeza !
- Mentoria

## Requisitos

**Obrigatórios:**
- Java
- ESQL
- SQL
- IBM Message Broker
- Excel
- XML

**Desejáveis:**
- Git
- Maven
- Conhecimentos de ETL.

**Diferenciais:**
- projetos opensource
- portfólio no github 

## Contratação

PJ a combinar / CLT / Cooperado

# Nossa empresa

![Image of EcommIt](https://github.com/ecomm-it/brand/blob/master/IT-small.png?raw=true)

A Ecomm-IT é uma empresa madura no mercado de consultoria de tecnologia da informação principalmente no segmento financeiro, atualmente estamos expandindo nossas operações para diversos setores.

##Como se candidatar

Por favor envie um email para vagas@ecommit.com.br com seu CV anexado / portfolio e sua pretensão salarial

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
