### ISSUE TITLE
[Remoto] Back-end developer Senior - Culttivo Tecnologia

### ISSUE THREAD

**Issue by Culttivoagro** [backend-br/vagas#11703]
**Nossa empresa**
A Culttivo é uma plataforma digital que oferece aos produtores de café, crédito livre de burocracias desnecessárias, filas e pegadinhas. Nasceu da união de experientes profissionais do agronegócio com intuito de utilizar as mais sofisticadas ferramentas do mercado para atender a cadeia do café. Simplificamos a vida "porteira a fora" e empoderamos o produtor rural, potencializando o foco no que é mais importante, a sua lavoura.

**Descrição da vaga**

Implementar soluções em conjunto com outros profissionais;
Domínio do Node.js, frameworks como Express, Sails, etc., JWT e PostgreSQL ou MSSQL 
Server, Microsoft Azure, GIT e desenvolvimento de APIs RESTful.
Conhecimento em MongoDB ou outro banco de dados não relacional, Kubernetes e bibliotecas de log.
Experiência com uso de recursos Microsoft Azure em soluções, sendo capaz de identificar prós e contras de diferentes arquiteturas.
Conhecimento de metodologias ágeis e DevOps.

Será um diferencial ter conhecimento em React, PHP, implementação de testes unitários e de integração e experiência com dispositivos de fila e arquiteturas baseadas em eventos.

Superior Completo em Tecnologia da Informação, Banco de Dados, Engenharia da Computação ou áreas correlatas.  

**Local**
Remoto

**Benefícios flexíveis**
Vale Refeição
Vale Alimentação
Mobilidade
Seguro Saúde
Academia
Ajuda de custo para home office

**Contratação**
Cooperado

**Como se candidatar**
Interessados encaminhar CV por e-mail para camilla.nicolino@culttivo.com

**Comment by guilherme90** [comment]
@Culttivoagro vocês costumam retornar e-mail? Enviei minha candidatura e não tive nenhum retorno.
