### ISSUE TITLE
[Remoto] FullStack PHP Sênior - ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [backend-br/vagas#11702]
> Atendimento remoto

## ITeam

Vinte anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

Remoto (Full time em horário comercial)
Início imediato

## Requisitos
 
Linguagens de Programação: PHP, Python, Java, Shell Scripting e C#.
Bancos de Dados: PostgreSQL, MySQL, Supabase, Firebird, Firebase e MongoDB.
Frameworks e Bibliotecas: React.js, React Native, Node, Next.js, Nest, Laravel, Codeigniter, Angular, Vue.js, Redux, 
Express, Bootstrap e jQuery.
Ferramentas: VSCode, Eclipse, Delphi, Git, GitHub, TortoiseGit, APIs, APIs RESTful, XSS (Cross-Site Scripting), JWT 
(JSON Web Tokens) e OAuth

## Contratação

3 meses

## Como se candidatar

Por favor, envie um e-mail para erika.santos@iteam.inf.br com seu currículo anexado e pretensão de taxa/hora PJ - enviar no assunto: 10668 - PHP

## Labels

PHP
Remoto

## Regime
PJ 

## Nível
Sênior

**Comment by maxhertel** [comment]
enviei meu curriculo
