### ISSUE TITLE
[Remoto] Back-end developer - Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [backend-br/vagas#11709]
## Nexmuv

A NEXMUV viabiliza a jornada digital de médias e grandes empresas. Aportamos nosso expertise de inovação, construção de produtos digitais, criação de startups e desenvolvimento de software para evoluir processos e gerar impacto positivo nos negócios e na experiência de consumo.

## Desenvolvedor Java - Sustentação 

Perfil para apoiar na operação do dia a dia na análise e entendimento de chamados e desenvolvimento de Sprint, garantindo a estabilidade e performance dos serviços disponibilizados.
Desenvolvedor Java com experiência em análise e desenvolvimento de aplicações, focado em microservices e integração com APIs. Conhecimento em SQL Server e conceitos de mensageria (AWS), além de habilidades em Git e metodologias ágeis. Apaixonado por aprender e crescer em um ambiente colaborativo, sempre em busca de soluções inovadoras.

## Local

100% remoto 

## Requisitos

Requisitos Técnicos:
• Desenvolvimento Java (versões mais recentes):
o Habilidade em analisar possíveis erros em aplicações Java e atuar no desenvolvimento/ajuste, com foco em depuração de problemas e identificação de causas de falhas na execução dos serviços
• Mensageria (SNS e SQS (Monitoramento e DLQ)):
o Experiência no monitoramento de filas SNS e SQS da AWS, além de conhecimento em busca e análise de mensagens em filas DLQ (Dead Letter Queue) para identificar e resolver falhas no processamento de mensagens.
• Cache Redis (Funcionamento):
o Compreensão básica do funcionamento do Redis como sistema de cache. Entendimento de seu papel em otimizar a performance e reduzir a carga no banco de dados, sem necessidade de implementação direta
• SQL (Consultas):
o Conhecimento em consultas SQL. O candidato deverá ser capaz de escrever queries eficientes, fazer análise de dados e realizar troubleshooting em bancos de dados relacionais, como PostgreSQL
Responsabilidades:
• Monitorar serviços e aplicações em Java.
• Analisar logs, identificar erros em aplicações Java e realizar as correções necessárias.
• Monitorar serviços AWS, com foco em filas SNS e SQS, incluindo DLQ.
• Realizar consultas em bancos de dados para análises e troubleshooting.
• Analisar e monitorar dashboards
## Contratação

PJ

## Como se candidatar

Enviar cv atualizado com pretensão salarial para Helen.matos@nexmuv.com

### Nível

- Júnior
- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by RafaelCamilloJorge** [comment]
Currículo Enviado.

**Comment by Italoomoura** [comment]
Enviado!

**Comment by Nicker2** [comment]
CV ENVIADO

**Comment by JoaoFerrareis02** [comment]
Enviado CV, mas fui bloqueado.
