### ISSUE TITLE
[FREELANCER] Back-end developer - BSH Norte

### ISSUE THREAD

**Issue by dinizezio** [backend-br/vagas#11728]
BSH Norte

Empresa de varejo no segmento de soluções em ferramentas elétricas.

Integração de API da Open Ai com alguma ferramenta capaz de retornar imagens, vídeos ou descrições

Nós estamos desenvolvendo uma solução em busca de produtos na nossa loja. Hoje, temos um grande problema em procurar por um item, dado que trabalhamos com dezenas de milhares de itens. Usamos a inteligência Chat GPT e criamos um agente de IA para ser um tipo de consultor de códigos e preço de itens. Ou seja: me forneça o código da parafusadeira Bosch 12V, e ele me retorna o código. Isso agilizou muito nosso atendimento, mas queríamos, por exemplo, fazer o agente GPT retornar não só a descrição do item, mas o produto com foto e outras coisas. Não sabemos como fazer isso, mas sabemos que precisaríamos de APIs e bibliotecas que fizessem esse trabalho. Portanto, quero marcar uma hora com um desenvolvedor para discutir sobre isso e orçar um projeto.

Manaus

100% remoto, serviço prestado da sua casa

Conhecimentos em APIs, Python e Java

Interessados chamar no WhatsApp (92) 98549-2294

- Contrato
- Freelance

**Comment by emairink** [comment]
@dinizezio  Tenho um sistema parecido. Entrei em contato.

**Comment by WESLEYx7** [comment]
Eu já trabalhei com o gemini utilizando node.

Em sex., 20 de dez. de 2024, 22:09, github-actions[bot] <
***@***.***> escreveu:
