### ISSUE TITLE
Back-end developer - Servidor Privado Metin2

### ISSUE THREAD

**Issue by somewhere-lost** [backend-br/vagas#11737]
Backend dev para freelance.

Estamos buscando um profissional para a customização de sistemas já existentes em um servidor de jogo. O trabalho envolve ajustes como balanceamento, modificações específicas e alterações em sistemas já implementados, sem a necessidade de criar novas mecânicas complexas.

**Requisitos obrigatórios:**
- Banco de dados MySQL: essencial para gerenciar operações do servidor.
- Linguagens Python e Lua: fundamentais para a personalização e ajustes no projeto.
- Conhecimento básico em C++: não será o foco, mas será útil ocasionalmente.

**Requisitos desejáveis:**
- Familiaridade com o jogo ou servidores semelhantes (não é obrigatório, mas é um diferencial).

**Benefícios:**
- Flexibilidade de horários.
- Trabalho remoto.

**Contratação:**
Contrato Freelancer.

Interessados, por favor, enviem sua proposta com detalhes sobre suas experiências e habilidades para [seu e-mail ou canal de contato].

**Remuneração:**
R$4.000 pelo freelance

Contato: saraxavv2004@gmail.com

**Comment by jorgelucas-rm** [comment]
Boa noite, você esqueceu de colocar o seu contato!

**Comment by somewhere-lost** [comment]
> Boa noite, você esqueceu de colocar o seu contato!

Obrigado, coloquei!
