### ISSUE TITLE
[REMOTO] Back-end developer - Projeto django-allauth - Servidor Privado

### ISSUE THREAD

**Issue by alansgonzaga** [backend-br/vagas#11764]
## Descrição da vaga

Estou procurando um desenvolvedor backend Django com experiência no pacote django-allauth para desenvolver um pequeno servidor de autenticação com regras de negócio de merge de contas de mesma propriedade, e trabalhando com logins SSO.

## Local

100% Remoto

## Requisitos

- Banco de dados PostgreSQL
- Django
- Pacote django-allauth

## Contratação

Contrato Freelancer.

Interessados, por favor, enviem sua proposta com detalhes sobre suas experiências e habilidades.

## Remuneração:
R$1.500 pelo freelance

Contato: [alan.s.gonzaga.eb@gmail.com](mailto:alan.s.gonzaga.eb@gmail.com)

### Nível

- Júnior
- Pleno

### Regime

- Freelance

### Alocação

- Remoto

**Comment by thiagochirana** [comment]
Poderia detalhar a task, o que de fato você precisa e como espera que o usuário se comporte para usar o software? Até para ter mais informações sobre e assim chegar em um acordo. Grato! ;)

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work with you.
I look forward your reply.
