### ISSUE TITLE
[São Paulo] Back-End Developer na EVNTS

### ISSUE THREAD

**Issue by evnts-dev** [backend-br/vagas#1177]
## Descrição da vaga

Profissional com experiência em desenvolvimento node Js. Atuará com desenvolvimento de novos projetos, camada de integração, serviços, arquitetura de sistemas, infraestrutura e banco da dados.

## Local

WeWork Paulista (em frente à estação de metrô Trianon - MASP) 
Endereço: Avenida Paulista, 1374

## Benefícios

- Vale-alimentação
- Vale-refeição
- Vale-transporte

#### Diferenciais

- Flexibilidade de horários e possibilidade de trabalho remoto 
- Ambiente informal e descontraído

## Requisitos

**Obrigatórios:**
- Habilidade analítica e realização de trabalho em equipe
- Experiência com Javascript (com orientação a objetos)
- Experiência com NodeJS
- Conhecimento em consumo de API's RESTful
- Conhecimento em banco de dados Mongodb/MySQL

**Desejáveis:**
- Arquitetura
- Padrão de projetos
- Gestão/cursos de metodologia ágil (SCRUM, XP entre outros)

## Contratação

CLT/PJ (a combinar)

## Nossa empresa

A Evnts é a empresa líder no mercado brasileiro em reserva de hotéis para grandes eventos. Entre milhares de parceiros trabalhamos com Rock in Rio, Lollapalooza, HSM, Salão do Automóvel, TDC, QCon e muitos outros. E é claro, visitamos e nos divertimos em alguns deles também :) 
Com 03 anos de mercado, conquistamos +70% do market share de eventos de médio e grande porte no Brasil. Estamos a procura de profissionais para nos ajudar a dar os próximos grandes passos no segmento, como internacionalização e a criação de um novo produto. Esse produto consiste em mudar a forma como o mercado se comporta em relação a eventos corporativos. Estamos revolucionando a maneira como as empresas organizam seus eventos, viagens e reuniões e precisamos de você para nos ajudar nesta jornada!  

## Como se candidatar

Por favor envie um email para vagas@evnts.com.br com seu CV anexado - enviar no assunto: Vaga Back-Ent Developer - [SEU NOME]

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto

**Comment by guilhermeoa07** [comment]
Vaga para Junior não?
