### ISSUE TITLE
[Barcelona, Espanha] Back-End Developer na SafeBoda

### ISSUE THREAD

**Issue by raphaklaus** [backend-br/vagas#1179]
# Sobre a empresa
SafeBoda é uma empresa que está revolucionando o mercado leste Africano de mobilidade. Realmente um trabalho incrível, dá uma olhada: https://safeboda.com/ug/

---

Bom, depois dessa pequena introdução... A empresa que trabalho aqui em Barcelona tá precisando escalar rapidamente e precisa de ótimos devs em várias áreas (Tech stack é Elixir, Kotlin, JavaScript, PHP, etc), então... Se você tem experiência em uma dessas áreas, bora! :) 

* Sponsorship de visto :+1:
* 35k ~ 50k EUR/ano
* Pacote de realocação
* Alocado (não rola remoto)
* Horário flexivel, equipe incrível!
* Possibilidade de viajar (ou morar, se vocêo quiser!) pra África para conhecer a sede da empresa
* Trabalhar na cidade mais foda da Europa :eyes:
* Escritório à poucos metros da praia :sunglasses: 

Mais informações aqui: https://www.linkedin.com/feed/update/activity:6531509359162200064/

Labels:
- Senior
- Elixir/Phoenix
- Visa Sponsorship
- Full Time
- Inglês fluente
- Alocado

**Comment by pdrgds** [comment]
Precisa de cover letter?

**Comment by raphaklaus** [comment]
@pdrgds Não, mas se tiver acho que é um plus. :)

**Comment by johninvictus** [comment]
Am Kenyan, and am passionate about elixir,  would be glad get an opportunity to work with you guys.

NB: I interview but was not choosen.

**Comment by alxbbarbosa** [comment]
Se tiver inglês intermediário tem chance? Na verdade saí do pré-avançado para o avançado mas...

**Comment by raphaklaus** [comment]
> Se tiver inglês intermediário tem chance? Na verdade saí do pré-avançado para o avançado mas...

Opa, ideal é avançado ou fluente.

**Comment by johninvictus** [comment]
Are positions in Kenya still open @raphaklaus
