### ISSUE TITLE
SÃO PAULO Desenvolvedor(a) Java [Via Varejo]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1181]
Requisitos:

Java 8								
Design Patterns								
Spring boot								
Docker, Linux								
GIT								
Experiência com integração entre camadas, definição de contratos de serviço.								
Junit Test.								
Experiência atuando em times ágeis.

Contratação PJ

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Java

**Comment by MarcosCarneiro** [comment]
tem disponibilidade para remoto?

**Comment by aline-navarro** [comment]
Essa vaga não tem, só presencial mesmo.
