### ISSUE TITLE
[Florianópolis, São Paulo e Joinville] Software Engineer - Senior na Resultados Digitais

### ISSUE THREAD

**Issue by MartinaCarvalho** [backend-br/vagas#119]
## Descrição da vaga

Vem construir algo incrível com a @RD

Faça parte de um time World Class!
Estamos em crescimento acelerado e precisamos de profissionais brilhantes para compor nosso time de especialistas!

Conheça nosso [Culture Code](http://resultadosdigitais.com.br/blog/culture-code-rd/) e um pouco mais de como trabalhamos no nosso [blog](http://shipit.resultadosdigitais.com.br). ;)

## Quem Buscamos?

Profissionais com Sólida experiência com desenvolvimento de Software e Conhecimento em Arquitetura de sistemas, estrutura de dados, redes, algoritmos. Além disso, vivência em estruturas de desenvolvimento/produtos complexas e que tenha participado de projetos desafiadores na carreira.
 
Você é o profissional que procuramos? #vemjunto

Nosso ambiente - Tecnologia:
- Desenvolvemos especialmente em Ruby (Rails e Sinatra), mas temos sistemas e componentes em Go, Elixir e Java, no front usamos Ember e React. 
- Utilizamos métodos ágeis (XP, Scrum, Kanban) e tudo está nas nuvens. 
- Utilizamos pesadamente infraestruturas como Heroku, Amazon e Azure, Sendgrid para email, além de Postgresql, MongoDB e Redis. 
- No desenvolvimento, utilizamos Github, Code Climate para análise estática e Circle CI para integração contínua, realizamos deploy 10x ao dias e fazemos isto via chat!

## Local

Florianópolis - Santa Catariana - Brasil 
Joinville - Santa Catarina - Brasil
São Paulo - São Paulo - Brasil

## Benefícios

- Vale-transporte
- Vale-alimentação
- Plano de saúde
- Plano Odontológico
- Gympass

#### Diferenciais

- Parcerias com descontos em academia, salão de beleza, lojas, etc.
- No dress code
- Cozinha com lanches para os RDoers (pão de queijo, salada de frutas, etc.)
- Aprendizado acelerado com grandes nomes do mercado em inbound marketing e vendas
- Curso e certificações da RD
- Seminários semanais para aprendizado
- Cultura de feedback e desenvolvimento
- Ambiente com autonomia
- Complexidade Tecnológica
- Desafios Diários

## Requisitos

- Experiência em linguagens como Ruby, Python, Go, Elixir, entre outras;
- Conhecimento de operação e volume de dados
- Postgres e NoSQL;
- Javascript e JQuery;
- AWS.

## Contratação

CLT a combinar

## Nossa empresa

A *Resultados Digitais* é a empresa do *RD Station*, uma plataforma SaaS focada em inbound marketing e automação de marketing. 

## Como se candidatar

Basta enviar seu currículo para talent.martina@gmail.com ou acessar este link e cadatrar seu CV: https://jobs.lever.co/resultadosdigitais/229a771a-9f04-45e2-a220-ccbaab121fb4

## Labels

- Alocado
- CLT
- Sênior

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
