### ISSUE TITLE
[São Paulo/SP] Summer Job em Tech (Back/Front) no Banco Safra

### ISSUE THREAD

**Issue by Fernandaruffo** [backend-br/vagas#1190]
O 4o maior banco privado do Brasil está com **4 oportunidades** para estágio de férias em SP.

O desafio é criar e desenvolver nosso novo site do Banco de Investimentos do zero. O Banco está passando por uma transformação digital e temos muuuuuuito a avançar ainda!

Para quem curte desafio, gosta de mudar (DE VERDADE) as coisas, esse é seu lugar.

Precisa ter conhecimento de **CSM** (lumis ou wordpress), **HTML,** web responsivo e se souber **C#** ou **Angular** já é um super plus! Conhecimentos previos em **SEO** também são um diferencial!

Bolsa R$2500
VT + VR
9h as 16h (1h de almoço) (tem flexibilidade de horário)

Período: 07/Julho até 02/Agosto (possibilidade de efetivação).

**Mandar currículo para ribeiro.fernanda@safra.com.br**

**Comment by Fernandaruffo** [comment]
Local: São Paulo | SP.

**Comment by kassiacatarine** [comment]
Tem a possibilidade de ser remoto?

**Comment by cimerio** [comment]
Não, só presencial, obrigado!

Atenciosamente,



[image: Descrição: cid:image001.jpg@01CDED2A.000CA350]

*Tarcizio Alexandre*

*Account Manager*

Tel. +5511 4063-7745

Cel. +5511 96901-9606

Skype: tarcizio.alexandre

Alphaville | Barueri | SP

*Atender bem não é diferencial, é uma obrigação!*



Em qua, 12 de jun de 2019 às 00:10, Akira <notifications@github.com>
escreveu:

**Comment by caioteixeira10** [comment]
Olá , tudo bem ? Gostaria de saber se o programa de Summer Job vai estar disponível no ano de 2020 ?
