### ISSUE TITLE
[Jundiaí] Backend Developer at WTIME

### ISSUE THREAD

**Issue by AnieliFernanda** [backend-br/vagas#120]
# # **Backend** Developer - Pleno

**Local:**
Jundiaí-SP

**Experiência** **em:**
Dashboards em MicroStrategy;
ETL, Integration Service (SSIS); 
Reporting Services (SSRS);
OBIEE, Migração de base de dados, BI;
Datawarehouse;
Modelagem de Banco de Dados;
SQL Server.
 
Vivência em modelo de negócios de Saúde / concessionárias de serviços públicos
Conhecimento de metodologias Ágeis (scrum) e formais (PMBok)

**Diferencial** 
Inglês intermediário (fluente é um diferencial)

**Modalidade** **de** **contratação:**
PJ - à combinar

**Projeto** 
Projeto pontual para atuar no cliente em Jundiaí, podendo prorrogar para um projeto maior em Alphaville, na nossa Fábrica de Software.
Negociando com o cliente para ser home office.

**Nossa** **empresa:**
A Wtime Business Intelligence It, uma consultoria que oferece serviços em tecnologia da informação.
www.wtime.com.br

**Como** **se** **candidatar**
Favor enviar um e-mail para anieli.fernanda@wtime.com.br com seu CV anexado - enviar no assunto: Vaga Backend Pleno.

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
