### ISSUE TITLE
[São Paulo] Desenvolvedor Python na Promo de Bolso

### ISSUE THREAD

**Issue by evertoncastro** [backend-br/vagas#1201]
[Desenvolvedor Python Promo de Bolso.pdf](https://github.com/backend-br/vagas/files/3269752/Desenvolvedor.Python.Promo.de.Bolso.pdf)

### Procuramos programadores que amam e sejam realmente bons no que fazem, encontrando soluções para os mais variados problemas técnicos
---

#### Sobre a vaga:
- Presencial
- Cidade - São Paulo
- Nível - Pleno (Se atualmente atua como júnior mas esta transbordando conhecimento e força de vontade não deixe de se candidatar)
- Faixa salarial entre R$ 5.000 e R$ 7.000 (PJ)
- Oportunidades reais de crescimento na carreira

#### Quais skills esperamos de você:
- Além do planejamento em equipe, auto-gestão das próprias atividades, saber lidar com dificuldades técnicas e identificar oportunidades de melhoria
- Automatização de processos evitando executar tarefas repetidas de forma manual
- Seguir boas práticas das linguagens e ferramentas utilizadas
- Pró atividade e interesse em entender e aprender as regras de negócio para propor soluções e agregar valor aos projetos e produtos
- Inglês intermediário/avançado para entender e criar documentações e se comunicar
- Experiência mínima de 2 anos com desenvolvimento WEB

#### Conhecimentos técnicos:
- Experiência com integração de aplicações WEB e APIs
- Criação de APIs REST
- Conhecimento da linguagem Python (NodeJs é um diferencial)
- Conhecimento em frameworks como Flask e Django
- Utilização de TDD 
- Ferramentas para automatização de tarefas
- Banco de dados relacionais. Criação de relatórios utilizando recursos como união de tabelas e agrupamentos
- Soluções em Cloud como Google Cloud ou Amazon

#### Responsabilidades:
- Criar, lançar, acompanhar e manter soluções de software
- Participar das decisões de tecnologia
- Soluções para garantir a melhor experiência para o usuário 

#### O que os as pessoas + gostam na Promo:
- O clima, o aprendizado de diversas tecnologias e o desafio diário
- A possibilidade de ser sócio e o reconhecimento financeiro a cada projeto/etapa
- Transparência em processos e decisões da empresa
- É pertinho do metrô Fradique, em um espaço muito legal!

#### Contato:
- Email: rh@promodebolso.com.br
- Site: https://promodebolso.site
- Telefone: 11 3455-7547

#### Labels
- Presencial
- Pleno
- Júnior
- PJ
- Python
- São Paulo

**Comment by marcospedro97** [comment]
A vaga ainda está aberta?

**Comment by evertoncastro** [comment]
Sim marcos
Vou fazer um update amanhã

Obrigado

**Comment by evertoncastro** [comment]
Pessoal, essa vaga ainda está aberta. Case se interessarem podem enviar um CV para rh@promodebolso.com.br
