### ISSUE TITLE
[REMOTO] Dev Backend Ruby [Impulso]

### ISSUE THREAD

**Issue by ThaysdaCosta** [backend-br/vagas#1205]

**Comment by ghost** [comment]
?

**Comment by ThaysdaCosta** [comment]
Buscamos **Dev Backend Ruby on Rails** que curta atuar em equipes colaborativas.

Se você adora desafios e tem **experiência prática** em **Rails, banco de dados MySQL, Aws, Semaphore CI, Sidekiq e repositório GIT**, não pode perder esta oportunidade!

Será **muito interessante** se já tiver **vivência em times ágeis**.

Nível: **Sênior**
Modelo: **Remoto**
Carga horária: **Full Time**, em horário comercial
Início: **Imediato**
Remuneração: **até R$90/h** (~R$14.400/mês). :moneybag: A própria pessoa define quanto julga ser adequado receber.

:smiley: **Sobre nós:** Somos uma **comunidade** com milhares de profissionais de TI **que integra diversas iniciativas, produtos e serviços** para a **colaboração mútua** e **desenvolvimento** pessoal e profissional de seus integrantes.
**Já somos mais de 10 mil pessoas!** :heart_eyes:

**Tem interesse e disponibilidade imediata?** Acesse o link https://impulser.me/thays-impulso, entre para a comunidade e me chame diretamente por lá (logo após registrar-se, você receberá por email as credenciais para acessar o nosso chat). Lá na comunidade, eu sou @thays. É só chamar! :wink:

Aguardo vocês! :rocket:

**Comment by nelsonmfinda** [comment]
Gosto de desafios :nerd_face: infelizmente não sou sênior.

**Comment by 0-9194** [comment]
Essa vaga ainda está em aberto? 😄
