### ISSUE TITLE
[São Paulo - SP] Pessoa desenvolvedora Backend Ruby - todos os níveis - na [Autoseg]

### ISSUE THREAD

**Issue by Rachc** [backend-br/vagas#1209]
# Perfil da vaga
Estamos buscando pessoas que almejam crescimento pessoal e profissional, junto à empresa. Seguimos uma cultura ágil: gostamos de fazer pair programming, testes, code reviews e troca de conhecimentos.

# Diferenciais da nossa empresa
- Participação em comunidades de TI 
- Somos abertos a novas tecnologias e plataformas.
- Gostamos de inovação e pensamos em soluções com o time e o projeto;
- Hack morning/evening (Tech talks)
- Open Source Day 
- Ambiente agradável e sem dress code (venha como se sentir à vontade ;D)

# Sobre a vaga 
Seu dia-a-dia consistirá na manutenção dos nossos sistemas, implementação em novos clientes e desenvolvimento de novas funcionalidades em Ruby on Rails.

# Níveis:
júnior, pleno ou sênior 

# Forma de contratação e benefícios
* CLT
* Vale transporte
* Vale refeição
* Plano médico e Odontológico

# Local
Próximo do metrô republica

# Como se candidatar
~se candidata aqui (:~
(o link ta temporariamente offline, então você pode mandar seu curriculo pro e-mail do nosso tech lead: bruno.volcov @ autoseg.com )
(se quiserem dar um salve por aqui, a gente da aquele apoio moral :D)

PS: Não vendemos seguro de carros :P

**Comment by ghost** [comment]
me indica pra essa vaga mano, to a procura de trampo

**Comment by guilhermeoa07** [comment]
É necessário experiência para Júnior também?

**Comment by Rachc** [comment]
Se a pessoa se desenrolar no código, é limpeza (:
A gente espera que ela tenha uma boa base de lógica, e já saiba um pouco de ruby/rails

**Comment by flaugabriel** [comment]
@Rachc  não existe nem uma oportunidade de HomeOffice ?  :/

**Comment by Rachc** [comment]
@flaugabriel  Depois de um tempo na empresa, você até consegue ficar remoto em alguns dias da semana, ou até negociar um remoto full time, mas precisamos do dev no escritório nos primeiros meses dele conosco

**Comment by Rachc** [comment]
@rx0n7 Manda o curriculo que eu indico (: Como eu consigo te identificar quando você mandar curriculo?

**Comment by ricardovsilva** [comment]
@Rachc o link está direcionando para a busca do trampos. Pode revisa-lo pfv?

**Comment by Rachc** [comment]
@ricardovsilva O link ficou fora do ar. Até ele voltar, deixei meu e-mail pra mandarem curriculo
Assim que voltar, eu conserto
(o texto do trampos é o mesmo que ta ai)

Obrigada por avisar!

**Comment by Rachc** [comment]
Só pra deixar avisado que a vaga ainda está aberta (:

**Comment by davialmeida** [comment]
Não sou de São Paulo, a empresa ajudaria na alocação caso eu tivesse o perfil para a vaga?

**Comment by Rachc** [comment]
Olá David. Vou perguntar aqui
mas manda o curriculo pra gente (:

**Comment by abrandao** [comment]
Estou enviando! Boa sorte na busca.
