### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na STUDIO VISUAL

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1212]
### Sobre a empresa: Studio Visual

Somos uma agência com foco em soluções digitais para empresas de pequeno, médio e grande porte. Estamos no mercado há mais de 15 anos, somando grande experiência em tecnologia e inovação, sempre com foco no usuário final.

### Descrição: O que você irá fazer?

Desenvolvimento de aplicações WEB, utilizando as melhores práticas do mercado, com foco na qualidade da entrega.

### Requisitos:

PHP;
JavaScript;
HTML;
CSS;
Bootstrap;
jQuery.
Conhecimento em WordPress, Laravel e Angular é considerado um diferencial para esta vaga.

### Aptidões e qualidades

Buscamos profissionais que tenham sangue nos olhos para fazer as coisas acontecerem.

### Informações complementares

Estamos localizados na Zona Leste de São Paulo, bem próximos ao metrô carrão.

### Candidatar: http://bit.ly/studio_visual

**Comment by ricardosaraiva** [comment]
Boa noite tem possibilidade de trabalho remoto este vaga?
