### ISSUE TITLE
[São Paulo] Desenvolvedor Node.Js na 5A Attiva 

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#1213]
Olá, estamos com oportuniddae para Desenvolvedor Node.Js. 

### Descrição: O que você irá fazer?
Desenvolvimento de aplicações WEB, atuar com desenvolvimento na linguagem Node.Js 
Projeto inovador de e-learning, será responsável pelo desenvolvimento do zero do projeto.

### Requisitos:
Experiência com desenvolvimento Back End WEB.
Node.js/Express, Mongo, React.

**Desejavel:** 
AWS, Docker, Heroku Python, Vuejs. 
e-learning

**Localidade:** Vila Mariana 
**Contratação:** PJ 

**Candidatar:** elisangela@5aattiva.com.br

**Comment by AntLouiz** [comment]
Vocês aceitam remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
