### ISSUE TITLE
Desenvolvedor (a) Bakcend na Encripta!! - [Moema - São Paulo]

### ISSUE THREAD

**Issue by thaishbrasil** [backend-br/vagas#1218]
enviar cv: vagas@encripta.com.br
Ou fale comigo>> https://www.linkedin.com/in/fernandesthais/

As tecnologias continuam mudando, os  modelos de negócio também e, o nosso sistema Back-end precisa estar sempre com as mais Modernas tecnologias construídas de forma a se adaptar facilmente aos usuários de Filmes e Séries de entretenimento.

Estamos diariamente desenvolvendo desta forma uma alta escalabilidade. Este é um dos conceitos mais importante de Back aqui na Encripta. 

É preciso pensar em quão flexível é a estrutura de uma aplicação para acomodar novos códigos, mais tráfego e dados.

Se você ama tecnologia de verdade, gosta de analisar grande volume de dados e extrair deles insights de melhorias de uma moderna Plataforma....E claro, tem que pensar fora da caixa, ter senso crítico, sem medo de buscar os melhores resultados. 

Ah! Só não pode dar Spoiler das séries preferidas ;)

Demorou, envia teu currículo pra gente!!

**Com o que você vai trabalhar**
Atuar no desenvolvimento e manutenção do back da plataforma de streaming com gestão de banco, servidores e criação de serviços.
Desenvolvimento de processos inovadores de encoding e encriptação de filmes e séries.
Integração com plataforma de parceiros, meios de pagamentos etc.
Desenvolver aplicativos para Smart TV e STB (set-top box).
Desenvolver aplicativos para console de jogos como Xbox e PlayStation.

**Atividades**
Colaborar com equipe de trabalho trazendo criação de soluções inovadoras e de Performance
Desenvolver novos componentes
Construir APIs e serviços de backend
Contribuir em decisões de arquitetura do projeto;
Criar ferramentas para medir e otimizar a performance dos nossos serviços;
Integrar serviços terceiros, como gateways de pagamento e ferramentas de e-mail marketing.
Priorizar e tratar bugs e exceções reportados em produção;

**Requisitos para se candidatar**
Conhecimentos em MVC e WebAPI.
Ser atualizado sobre as mais recentes ferramentas de framework e criação de bibliotecas;
Conhecimentos em Software Design Patterns
Conhecimentos de Windows Azure
Conhecimentos avançados em Banco de Dados SQL Server

![streaming](https://user-images.githubusercontent.com/47364879/59443036-b112ee80-8dd1-11e9-988b-ad761d17f968.png)

**Comment by izaguerreiro** [comment]
Qual a stack e requisitos da vaga?

**Comment by thaishbrasil** [comment]
@izaguerreiro segue na descrição da vaga ;)

**Comment by cbarauna** [comment]
Está sem os labels é alocado ou remoto?

**Comment by thaishbrasil** [comment]
> Está sem os labels é alocado ou remoto?


@cba
