### ISSUE TITLE
[São Paulo] Desenvolvedor de Software no Moip

### ISSUE THREAD

**Issue by evandromoip** [backend-br/vagas#122]
**Sobre o Moip**
O Moip é a empresa de pagamentos mais inovadora do Brasil. Ajudamos todos os meses mais de 100k empreendedores e PMEs a receberem pagamentos online (e offline). Acreditamos que a inovação e o empreendedorismo devam ser o motor de crescimento do país e por isso estamos redefinindo a forma com que pequenos negócios lidam com a sua vida financeira.

**Sobre nosso time de Produtos & Engenharia**
Somos um time multidisciplinar que busca por meio de tecnologia e design resolver problemas reais de nossos clientes. Trabalhamos com o conceito de times autônomos que possuem missões próprias (alinhadas a estratégia do Moip) e cuidam de todo o ciclo de desenvolvimento de produtos. Desde a concepção, à implementação e operação dos sistemas. Este é o nosso jeito de emular pequenas start-ups dentro do Moip, tornando a equipe dona do produto e 100% responsável pelo sucesso das nossas soluções. Comemoramos (com cevada) nossas conquistas todas as sextas-feiras. Dividimos nosso conhecimento com as já consagradas tech-talks semanais de um dos membros do time. Isso tudo, alinhado com muita responsabilidade e vontade de ajudar os clientes, ajudar a comunidade opensource e ser ajudado.

**Quais tecnologias utilizamos?**
O Moip hoje possui uma arquitetura baseada em (Micro-)Serviços e nos últimos anos temos enfrentados diferentes tipos de problemas:

- Separação de responsabilidades em uma arquitetura baseada em Serviços
- Uso de diferentes linguagens de programação (Java, Ruby, NodeJS, Go, JavaScript, CoffeeScript)
- Criação de bibliotecas para dispositivos móveis (Android, iOS)
- Comunicação assíncrona utilizando filas (RabbitMQ, ActiveMQ)
- TDD, BDD, Testes de Integração, Integração Contínua
- Monitoramentos e métricas das aplicações
- Integração com sistemas terceiros (Adquirentes, Anti Fraude, Bancos, etc)
- Criação de uma API Restful com conceitos de HATEOAS
- Entrega Contínua
- Relatórios rápidos e customizados para nossos clientes, utilizando ElasticSearch
- Uso de diferentes bancos de dados SQL/NoSQL (Mysql, MongoDB, Redis, etc.)
- Manutenção de sistemas novos e legados
- Automação de provisionamento de servidores em Cloud (AWS)
- Sistemas de alta disponibilidade

Um bom Github será um grande diferencial.

**REQUIREMENTS**
- Conhecimento / experiência em alguma linguagem de programação orientada a objetos (Java, Ruby, Python, NodeJS)
- Noções em APIs Restful
- Noções em MVC
- Noções HTML / CSS / JavaScript
- Inglês
- Estudando / Formado em alguma área de tecnologia

**Benefícios**
- Assistência Médica e Odontológica
- VT com desconto de apenas 2%.
- Flex Car (combustível).
- Seguro de Vida Itaú.
- Frutas.
- Auxilio Incentivo a Idiomas.
- Convênio com Academia.
- Convênio Sesc.

**Como se candidatar?**
Acesse esse [link](https://moip.workable.com/jobs/96455) e participe do processo seletivo.

**Labels**
- CLT
- Junior
- Pleno
- Senior
- Java
- Ruby
- NodeJS
- JavaScript

**Comment by reginaldojunior** [comment]
Ainda tem vagas?

**Comment by evandromoip** [comment]
Oi @reginaldojunior, ainda temos as vagas abertas!
Candidaturas nesse link: https://moip.workable.com/jobs/96455
