### ISSUE TITLE
Desenvolvedor Node.JS(PL)

### ISSUE THREAD

**Issue by larissaaguiar** [backend-br/vagas#1223]
Atividades: 
Trabalhar com o time de desenvolvimento para novas
features nos nossos sistemas;
Codificar e automatizar testes garantindo a qualidade de
seu trabalho;
Projetar, arquitetar soluções (back-end e front-end) e dar
manutenção nos sistemas já existentes;
Sugerir melhorias no processo de desenvolvimento;
Ter a proatividade em compartilhar seus conhecimentos,
contribuindo com o desenvolvimento profissional da
equipe;
Auxiliar com demais atividades da área.

Requisitos:
Superior completo em qualquer área;
Experiência de 2 anos em desenvolvimento;
Domínio com JavaScript;
Conhecimento de Node.JS;
Inglês Intermediário;
Disponibilidade para atuar 40h semanais.

Não é obrigatório mas será um diferencial se possuir:
Conhecimento de Chatbots;
Angular 6 / Ionic Framework;
Java com Play Framework;
Conhecimento (prático e/ou teórico) do mercado
hoteleiro;
Experiência em Startup.

Quem não quer trabalhar e nem perceber que está trabalhando? É assim na Ask pois temos o ambiente todo pensado em nossos colaboradores. Na Asksuite o cafezinho é liberado, os horários são flexíveis, temos uma localização privilegiada e o melhor: NO DRESS CODE. Buscamos um colaborador que tenha foco em resultados, inovação, vontade de crescer e aprender!

A Asksuite é líder no mercado, buscamos proporcionar as melhores experiências para os viajantes em seu momento de repouso então oferecemos aos nossos clientes atendimento online 24 horas! Temos parcerias incríveis, ficou curioso? Dá uma olhadinha em nosso site: www.asksuite.com

As características da vaga estão dentro do seu perfil e interesse? Encaminhe seu currículo para: larissa.aguiar504@gmail.com

**Comment by JonatanPotrikus** [comment]
É possivel trabalhar de forma Remota ? Ou deve ser em alguma cidade especifica ?
