### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor(a) PHP Junior na Agência Kaizen

### ISSUE THREAD

**Issue by b0bd3v** [backend-br/vagas#1224]
### O que nós buscamos
Desenvolvimento e manutenção de sites, gerenciamento de conteúdos dos sites gerenciados pela a Agência Kaizen.

Setor de desenvolvimento em crescimento tomando rumo para desenvolvimento de apps web e mobile. Oportunidade para aprendizado.

### Principais responsabilidades.
- Conhecimentos em PHP, Javascript, HTML/CSS e Banco de dados MySQL.
- Ajustes e inserções de conteúdos nas plataformas

### Conhecimentos Diferenciais
- Laravel
- Wordpress
- Drupal
- jQuery
- Bootstrap

### Benefícios
CLT 1.500 + VT + VA/VR 22,00/dia 
Bom ambiente de trabalho. 

https://www.instagram.com/digitalkaizen/
https://www.facebook.com/KaizenMarketingDigital/
https://www.agenciakaizen.com.br/

100% presencial Porto Alegre

Envie e-mail para naimara@agenciakaizen.com.br

**Comment by b0bd3v** [comment]
A título de informação. Ainda temos vagas na empresa.

**Comment by brunoreisnascimento** [comment]
Apenas presencial ou pode ser remoto?

**Comment by b0bd3v** [comment]
@brunoreisnascimento 
Desculpe a demora. Apenas presencial. 
Se tiver mais alguma dúvida, pelo e-mail conseguimos responder mais rápido. 
Abraços
