### ISSUE TITLE
[Curitiba] Back-End Developer no Grupo Inlog

### ISSUE THREAD

**Issue by joaoguibune** [backend-br/vagas#123]
### C# DEVELOPER
> Buscamos um desenvolvedor que goste de novos desafios usando as linguagens/frameworks em C#, .Net e WebApi.
O profissional irá atuar com metodologias ágeis e equipes autogerenciáveis.

__Necessário:__
- Conhecimento em desenvolvimento com C#
- Boa lógica de programação e algoritmos
- Padrões de projetos
- Boas práticas de desenvolvimento.  

__Diferenciais:__
- Noções de front-end
- Pró atividade.

__O que oferecemos?__
- CLT, VT, VR, Plano de saúde e odontológico
- Salário a combinar
- Empresa com ambiente descontraído
- Escritório bem no centro de Curitiba
- Frutas e snacks o dia todo
- Parcerias de desconto para graduação e pós-graduação
- Seguro de vida em grupo

__Quem somos?__  
Somos um grupo que tem a inovação como um dos nossos valores essenciais, sendo o primeiro e o maior no país a oferecer soluções completas ao mercado de controle, otimização e automação de empresas com operações de campo, nas áreas de coleta de resíduos e transporte coletivo.

__Tem o perfil que procuramos?__   
Realize um de nossos testes em https://github.com/weareinlog/CSharpTest  
E venha fazer parte do nosso time #beINLOG

**Comment by dgoangelo** [comment]
possibilidade de ser remoto?

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
