### ISSUE TITLE
[VAGA][ROR][SP] B2B Stack - Ruby on Rails Full Stack Developer - SP (PJ)

### ISSUE THREAD

**Issue by ticianafig** [backend-br/vagas#1236]
Para quem tem a ambição de ser protagonista das transformações de um produto líder de mercado.

**B2B Stack - Ruby on Rails Full Stack Developer - SP (PJ)** >> [http://bit.ly/b2bs-fs-github](url)

Transite entre as linguagens de código e a linguagem dos negócios e cresça em uma startup com o pé no acelerador. Trabalhando na B2B Stack, você fará parte de um time em crescimento, onde você será um(a) grande protagonista das transformações do produto. Nossa cultura é de transparência (estamos todos no mesmo barco), colaboração (gente boa unida faz a diferença), ambição (miramos alto) e hard work. Você estará em um ambiente informal (de startup), ao lado do fundador, com liberdade pra trazer ideias e testar coisas novas. Ser Full Stack Developer na B2BStack é estar disposto a crescer e a assumir grandes responsabilidades. No médio prazo, já pensou em ser um sócio CTO da empresa – liderando equipes de tecnologia, e unindo a visão técnica à visão de negócios da empresa?

Para ter acesso a **mais vagas de tech** entre no nosso grupo do WhatsApp: [http://bit.ly/grupo-tech-intera-2](url)

Conhece alguém com perfil para a vaga? **Indique e ganhe até R$500 reais** se ela for contratada >> [https://vagas.byintera.com/seja-um-hunter/](url)

**Comment by ghost** [comment]
links tudo quebrado brow
