### ISSUE TITLE
[São Paulo] Desenvolvedor Fullstack Java + Vue.js na iBlue Consulting

### ISSUE THREAD

**Issue by cahfigueiredo** [backend-br/vagas#1239]
Somos uma consultoria de TI com sede no Rio de Janeiro. Nosso foco é oferecer soluções digitais de ponta a ponta!
Buscamos Desenvolvedor Fullstack com experiência sólida em Java e Vue para atuar no nosso time de São Paulo!

Os requisitos da vaga são:
Conhecimentos em Java e AWS;
Experiencia com Vue.js e Vuex;
Experiência com SPA;
Domínio em HTML, CSS e Java Script;
Metodologias CSS (BEM, Atomic, OOCSS);
Pré-processadores CSS (Sass, PostCSS, Less, ...);
Entender como o Browser funciona;
Conhecer HTTP, HTTP/2 e APIs Rest;
Testes automatizados (Jest, Jasmine, Selenium);
Saber utilizar Git;
Criação de código limpo, legível, cross-browser e cross-device;
SEO;
Performance;
Desejáveis:
Acessibilidade;
ES6 / ES7;
Webpack;
Design pattern em javascript;

Local: São Paulo
Inicio: Imediato

Interessados enviar CV atuallizado para rhrio@iblueconsulting.com.br

**Comment by AntLouiz** [comment]
Vocês aceitam remoto?

**Comment by cahfigueiredo** [comment]
Olá, Luiz! Tudo bem?

Agradeço o seu interesse em fazer parte do nosso time, mas no momento não temos oportunidades para trabalhar remoto.

Att,


[Logo iBlue, Digital e gil]<http://www.iblueconsulting.com.br/>

Camila Figueiredo

Recursos Humanos

tel.: (21) 98867-2496<tel:+5521988672496> | (21) 3554-7278<tel:+552135547278>

email: cfigueiredo@iblueconsulting.com.br<mailto:cfigueiredo@iblueconsulting.com.br>

Av. Rio Branco 181, sala 3101. Rio de Janeiro

iblueconsulting.com.br<http://www.iblueconsulting.com.br/>


________________________________
De: Luiz Rodrigo <notifications@github.com>
Enviado: sábado, 12 de outubro de 2019 10:23
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Camila Figueiredo <cfigueiredo@iblueconsulting.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [São Paulo] Desenvolvedor Fullstack Java + Vue.js na iBlue Consulting (#1239)


Vocês aceitam remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
