### ISSUE TITLE
[São Paulo|Campinas] Desenvolvedor(a) Back-end na [Geofusion]

### ISSUE THREAD

**Issue by arturgaleno** [backend-br/vagas#124]
## Desenvolvedor(a) Back-end (São Paulo ou Campinas)

**Sobre a Geofusion:**

A Geofusion é para você, que tem paixão pela segunda-feira e se levanta todos os dias com vontade de fazer a diferença. Você que acredita na força das relações ganha-ganha e consegue enxergar que o melhor resultado é o bom pra todos. Se você não se contenta com um trabalho medíocre e busca o fator UAU, se você é capaz de sair da mesmice com uma atitude inovadora, junte-se a nós!

Somos uma empresa de Inteligência Geográfica de Mercado que nasceu para revolucionar a forma como as empresas tomam decisões de alto impacto. Nossas soluções SaaS trabalham com milhões de informações de forma muito rápida e escalável, para que o cliente tenha uma resposta precisa, no menor tempo possível.

Temos times com grandes desafios interagindo em um ambiente leve e descontraído, que proporciona liberdade para agir e decidir. E nossas pessoas também participam de projetos que promovem o empreendedorismo social e a diversidade dentro da empresa.

Você trabalha por um propósito e não apenas para pagar as contas?

Então venha para a Geofusion!

**Requisitos necessários:**

Formação superior em Ciência da Computação, Engenharia de Computação, Análise de Sistemas, Sistemas de Informação ou área relacionada
Domínio da plataforma Java
Experiência com desenvolvimento Web
Experiência com RESTful
Conhecimento sólido em Design Patterns e Clean Code
Conhecimento da arquitetura de microserviços
Experiência com ferramentas de Integração e Entrega Contínua
Experiência com ferramentas de versionamento de código, preferencialmente Git
Vivência e conhecimento em cultura de desenvolvimento ágil, bem como metodologias associadas (i.e. Kanban, Scrum)

**Requisitos desejáveis:**

Conhecimento em Spring e Java EE
Experiência com Docker e Kubernetes
Conhecimento em outras tecnologias de programação: Python, Node.js e/ou PHP
Vivência com banco de dados NoSQL (Solr, MongoDB, etc.)
Conhecimento em tecnologias Open Source
Conhecimento em GIS

**Responsabilidades:**

Desenvolver e evoluir tecnicamente os produtos da Geofusion
Prezar pela qualidade do código e da entrega
Buscar tecnologias e ferramentas para resolver os desafios do dia a dia
Implementar soluções eficazes e de alto desempenho
Opinar e ajudar a melhorar a qualidade dos produtos e processo de desenvolvimento.

Vaga disponível para: São Paulo ou Campinas. 

**Link para inscrição: https://goo.gl/fHK29u** 

Labels: Pleno, CLT

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
