### ISSUE TITLE
[Brasília, São Paulo] Desenvolvedor Backend, Android e Designer UX/UI

### ISSUE THREAD

**Issue by kimberlyplima** [backend-br/vagas#1245]
![WhatsApp Image 2019-06-21 at 16 42 12](https://user-images.githubusercontent.com/22302027/59948354-29b72200-9446-11e9-8b1e-a95219fe8c3a.jpeg)

Quer entrar em um time de apaixonados por tecnologia? Acesse: https://lnkd.in/etjQdkD

**Comment by jhefflg** [comment]
Há vaga para front-end ou fullstack javascript em SP? Achei muito interessante a empresa.
