### ISSUE TITLE
[Canoas / RS] Desenvolvedor FullStack React Native - Parceria HunterCo

### ISSUE THREAD

**Issue by joaofidelix** [backend-br/vagas#1246]
## Descrição da vaga

Desenvolvimento de aplicativos Mobile com React Native

## Local

Escritório - Canoas - RS

## Benefícios

- Plano de saúde subsidiado
- Plano odontológico subsidiado
- Seguro de vida
- Ajuda de custo (diária)
- Bônus anual

## Requisitos

**Obrigatórios:**
- Mínimo de 1 ano de experiência com desenvolvimento React Native

**Desejáveis:**
- Conhecer o processo de publicação em lojas de aplicativos (Apple e Android)
- Conhecer de Métodos Ágeis
- GitHub

**Diferenciais:**
- projetos opensource

## Contratação

PJ ou CLT (A combinar)

## Nossa empresa

A Kbase veio ao mundo para desenvolver o software que o seu negócio precisa. Fazemos isso de forma personalizada, seja qual for o desafio que a sua empresa enfrenta.

Nós fazemos o software que você não encontrou no mercado e trazemos soluções para problemas que só a sua empresa enfrenta em tecnologia.

Software é a nossa paixão!

A Kbase sente-se responsável pelo desempenho competitivo de seus clientes. Temos uma equipe especializada, focada na otimização de processos, aumento de produtividade e mais rentabilidade para os negócios.

## Como se candidatar

Por favor candidate-se no nosso site: https://vagas.hunterco.com.br/job/5d0a94d6ee67a70011acfa5e

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by jorginhodev** [comment]
a vaga está em aberto ainda?

**Comment by joaofidelix** [comment]
@jorginhodev Está sim. Você pode se candidatar por aqui: https://vagas.hunterco.com.br/job/5d0a94d6ee67a70011acfa5e
