### ISSUE TITLE
[São Paulo] Analisa Desenvolvedor .NET Senior / Pleno na TS Tech

### ISSUE THREAD

**Issue by trabalheaqui-tstech** [backend-br/vagas#125]
## Descrição da vaga
Empresa de tecnologia em integração de serviços e soluções de TI, localizada na Zona Sul de São Paulo.

## Responsabilidades
Atuar no desenvolvimento de novas funcionalidades para plataforma Web
Discutir e fomentar a implementação de novas funcionalidades
Em grupo, definir arquiteturas e contribuir com decisões técnicas
Testar novas ferramentas e frameworks com o objetivo de melhoria de resultado para o projeto
Participar na estimativa do time de desenvolvimento
Em grupo, se comprometer com metas, prazos e objetivos
Ouvir o cliente e sugerir diferentes opções de viabilidade

##  Tecnologias:
-  Angular 
- .NET 4.5
- Dot Net Core 2.0
- C# .NET
- Web API
- Javascript (Client/Server), Bootstrap, CSS
- MySQL;
- GIT
- REST

## Diferencial:
Node.JS
Bancos de dados Não Relacional

## Conhecimento desejável com:
Arquitetura escalável e distribuída
Docker

## Práticas:
Test Driven Development
Pair programming
Continuous Integration
Design Patterns

## Contratação
CLT ou PJ

## Salário
A combinar, de acordo com a experiência.

## Local
Av. das Nações Unidas, 18801, São Paulo, próximo a estação Santo Amaro de trem.

## Como se candidatar
Por favor se candidatar através do link: https://www.recrutasimples.com.br/vaga/analisa-desenvolvedor-net-senior-pleno/sao-paulo-sp/-L84BL_a1Nhe7kRle8HD
Ou enviar email com seu CV anexado para: trabalheaqui@tstech.com.br - enviar no assunto: Vaga Desenvolvedor .NET Senior / Pleno

### Labels
- Imediato
- CLT
- PJ
- .NET
- Angular
- Senior
- Pleno

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
