### ISSUE TITLE
[São Paulo/SP] Desenvolvedor C# na Resource IT

### ISSUE THREAD

**Issue by LeandroRenzi** [backend-br/vagas#1257]
## Empresa
 Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga
Desenvolvimento de melhorias e novas funcionalidades.

## Posição
DESENVOLVEDOR SÊNIOR 

## Tipo de contratação
 CLT

## Requisitos
•	Conhecimentos sólidos .NET, Linguagem C Sharp (Framework 4.5 ou superior), MVC (versão 4.0 ou superior) e Orientação a Objetos ;
•	JQuery, Ajax, JavaScript e HTML5; 
•	SQL;
•	Design Pattern 
•	Reaproveitamento de código;
•	WCF (Windows Communication Foundation);

##Diferenciais
•	Oracle (versão 11g);
•	Arquitetura SOA (Arquitetura Orientada à Serviços) ;
•	JSON – XML;
•	BootStrap;
•	Telerik - Enterprise Architect;
•	Sistemas Logísticos (TMS - Transportation Management System)

## Benefícios
•	Plano de saúde Sulamérica Exato Apto com cooparticipação
•	Convênio Odontológico - Porto Seguro
•	Seguro de vida
•	VR de R$ 440,00
•	Auxílio creche
•	Convenio Farmácia

## Contato
Por favor envie um email para leandro.renzi@resourceit.com com seu CV anexado - enviar no assunto: [VAGA C# - SP] [Seu nome completo]

### Alocação:
- Presencial

## Local
Avenida Paulista, em frente ao metrô Brigadeiro

##Labels
junior/pleno/senior
CLT
C#

**Comment by luicesar** [comment]
Não moro no estado de São Paulo, posso me candidatar a vaga ?

**Comment by streammus** [comment]
Olá, Luís
Tudo bem?

Sim, não tem problema.
Caso entre pro time, o job será em SP.

Forte abraço,
