### ISSUE TITLE
[Campinas - SP] DBA - Postgre SQL na PROSCORE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1259]
### Sobre a empresa: ProScore

A proScore com quase 20 anos de atuação no mercado de desenvolvimento de software e prestação de serviços de tecnologia da informação é uma empresa de soluções tecnológicas customizadas com excelência na estruturação e no gerenciamento de informações, para atender seus clientes nas mais diversas necessidades.

### Descrição: Quais os requisitos?

Experiência como DBA PostgreSQL, com sistemas operacionais Windows e Linux;
Possuir inglês técnico;
Experiência com configuração e administração de SGBD em ambiente Linux;
Domínio da linguagem SQL, PL/SQL
Experiência com tuning SQL
Conhecimento em Ambiente de Data Warehouse
Experiência no planejamento e execução de migrações entre banco de dados PostgreSQL e outros SGBDs
Experiência com virtualização de SGBDs
Gestão de Ambientes
Análise de Capacity e performance em ambiente Linux

### Diferenciais

Buscamos por profissionais que se sintam confortáveis em uma cultura de aprendizagem constante e inovação, que gostem de desafios e busque a melhoria contínua! Gostar de trabalhar de forma colaborativa é muito importante pra gente! Todo nosso time tem atuação dinâmica e participativa. É Importante saber trabalhar sobre pressão e ter autonomia de suas demandas e responsabilidade sobre suas entregas.

### Benefícios

Vale-transporte;
Vale-refeição;
Assistência Médica;
Convênio farmácia;
Seguro de vida em grupo;
Política para bolsa de estudos;
HomeOffice 1x/semana :)
DayOff no dia do aniversário;
Festas de confraternização;
Sala de descompressão;

### Você gostará de trabalhar aqui se

Se tiver sangue no olho para aprender cada vez mais e for motivado por desafios! Além disso saberá que aqui é o lugar ideal para você se gostar de ambientes descontraídos onde todos são proativos e dispostos a fazer acontecer. E claro, se você buscar crescimento, pode ter certeza, aqui é o seu lugar!

### Candidatar: http://bit.ly/proscore_dba

**Comment by luicesar** [comment]
Não tem vaga para nível sênior ?
