### ISSUE TITLE
[Belo Horizonte] CIENTISTA DE DADOS SR. na Grupo Selpe

### ISSUE THREAD

**Issue by lucasparisi** [backend-br/vagas#126]
**Descrição da Vaga**
Suportar um time multidisciplinar no processo de venda e consumo de produtos e serviços analíticos;
Atuar em projetos de machine learning fazendo Feature Engineering, construindo modelos de classificação ou regressão usando técnicas de aprendizado de máquina;
Explorar dados usando métodos atualizados;
Adicionar aos dados da empresa fontes de informação de terceiros quando necessário;
Processar, limpar e verificar a integridade dos dados utilizados para análise;
Fazer análises ad hoc e apresentar os resultados de forma clara;
Criar sistemas automatizados que usem inteligência analítica.

**Requisitos**
Domínio em R, Python (Numpy, Scipy), distribuições, teste de hipóteses, regressão linear, regressão logística, estatística multivariada e SQL.

Formação acadêmica
Superior Completo - Ciência da Computação

Candidate-se em http://recrutamentointeligente.click/data-scientist_SR

**Comment by lucasparisi** [comment]
@gucastiliao por favor, como adiciono tags? rs

**Comment by gustavocstl** [comment]
@lucasparisi opa!
me passa as tags que eu adiciono por aqui :)

**Comment by reginaldojunior** [comment]
@lucasparisi só os admin do repositório pode adicionar as tags.

Passa para gente que adicionamos ;)

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
