### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) TypeScript / NodeJS na Vizir

### ISSUE THREAD

**Issue by apantaliao** [backend-br/vagas#1262]
**Descrição da vaga**
Estamos com oportunidades para trabalhar com Node.js e TypeScript na Vizir.
Para conhecer mais sobre a vaga e [um pouco da Vizir](http://vizir.com.br/2017/04/26634697957-2/)

Quem tiver interessado, só preencher o seguinte [formulário](https://bit.ly/2uEH3Ze).

**Local**
Em nosso escritório no centro de SP, podendo alguns dias ser remoto. 

**Benefícios**

- Ticket refeição: R$ 30,00 por dia (R$ 630,00 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou aonde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

**Requisitos**
- Conhecimento de JavaScript, boa lógica e orientação a objetos
- Estar a fim de aprender
- Comprometido em entregar projetos com qualidade

**Requisitos Obrigatórios:**
- Curtir programar

**Contratação**
- CLT

**Como se candidatar**
Preencha o seguinte formulário: [https://bit.ly/2uEH3Ze](https://bit.ly/2uEH3Ze)

**Labels**
Presencial
CLT
Pleno
Senior

**Comment by jhefflg** [comment]
Olá @apantaliao, como está?

Adorei a vaga, enviei formulário.
Não moro atualmente em SP, mas estou em processo de mudança, no caso já conheço SP, morei por sete anos na capital. Gostaria de saber se o processo é 100% remoto ou tem etapas presenciais.

Att,
Jefferson de Lima

**Comment by apantaliao** [comment]
Opa @jeffersonlg , tudo bem? 
Legal! Obrigado pelo interesse! 

O processo pode ser remoto sim. O único ponto é que nestas vagas daremos preferência para pessoas que possam vir com alguma frequência ao escritório. 

Até mais e obrigado!

**Comment by jhefflg** [comment]
Tudo bem.

@apantaliao entendo, Envie de qualquer forma o currículo, Pois seria apenas o processo de seleção mesmo que precisaria ser remoto de resto consigo sem problemas atuar presencialmente.
