### ISSUE TITLE
|Lisboa, Portugal| Desenvolvedor Java na Aubay

### ISSUE THREAD

**Issue by silviapedrosa** [backend-br/vagas#1268]
Descrição da vaga
Projetos em vários setores de atividade, usando diversas tecnologias de Java entre outras.

Local
Portugal: Lisboa e Porto

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário
• Almoço grátis todas as sexta-feiras

Requisitos
Obrigatórios:
• Mais de 3 anos de experiência em desenvolvimento Java;
• Domínio da língua Inglesa (conversação e escrita).

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Envie o seu CV para spedrosa@aubay.com com o assunto Aubay: JAVAG.

Labels
Alocado
Pleno
Sênior
Vaga Internacional

**Comment by tiagocassio** [comment]
O que seria "Domínio da língua Inglesa"? Falar Inglês fluentemente? Existe alguma informação da remuneração anual que a empresa oferece?

**Comment by silviapedrosa** [comment]
Tiago,

Não é necessária fluência mas um bom nível de inglês que permita fazer uma entrevista em inglês com os nossos clientes.

Os melhores cumprimentos,
[Descrição: 721313813@16102008-18F2]  Sílvia Pedrosa
  Talent Recruiter

Edifício Duque d’Ávila,
Avenida Duque d’Ávila nº 46, 7ºC – 1050-083 Lisboa
Tel: +351 2<tel:%2B351%20211%20928%20417>11 928 417 - Mobile: +351 914 053 987
Fax: +351 211 928 230<tel:%2B351%20211%20928%20230>
Skype: smarinapedrosa_1

[cid:image002.png@01D1126F.FAEB9CF0]<http://www.aubay.com/>  [cid:image003.png@01D1126F.FAEB9CF0] <http://www.facebook.com/aubayportugal>   [cid:image004.png@01D1126F.FAEB9CF0] <https://twitter.com/groupeaubay>   [cid:image005.png@01D1126F.FAEB9CF0] <https://www.youtube.com/user/aubaytv>

Antes de imprimir, pense no ambiente!
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Tiago Cássio <notifications@github.com>
Enviada: 27 de junho de 2019 14:39
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Silvia PEDROSA <spedrosa@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] |Lisboa, Portugal| Desenvolvedor Java na Aubay (#1268)


O que seria "Domínio da língua Inglesa"? Falar Inglês fluentemente?
