### ISSUE TITLE
[São Paulo] Back-End Developer na Ambev

### ISSUE THREAD

**Issue by andre0799** [backend-br/vagas#127]
## Descrição da vaga

We are developing a global platform where customers from many countries will be waiting for their cold beers! You will work with people with multidisciplinary skills (PO, UX / UI, Developers and QAs) in order to deliver the best experience for our users.
You will join a team where everyone share a common interest in distributed backend systems, their scalability and continued development. If you are passionate about working with high scalable backend infrastructure, and are motivated to make an impact in creating a robust and scalable software - this is the opportunity for you

## Local

Escritório, São Paulo - Itaim Bibi

## Benefícios

- Vale Refeição
- Vale Transporte
- Assistência Médica
- Assistência Odontológica
- Seguro de Vida

## Requisitos

**Obrigatórios:**
- Python, node or equivalent programming language
- SQL / NoSQL databases (like PostgreSQL, Redis, ElasticSearch, DynamoDB…)
- Automated unit, functional, integration testing
- Infrastructure as code (like Docker, Ansible, AWS Cloudformation…)
- Amazon Web Services (like Lambda, API Gateway, SQS, etc.)
- B.S., M.S., or PhD. in Computer Science/Engineering or equivalent
- Continuous Integration/Continuous Deploy (like Travis, Jenkins...)
- Data modeling
- Design Patterns
- Git

## Contratação

CLT (Efetivo) - Salário de R$7000,00 a R$9000,00

## Nossa empresa

Empresa atua no ramo de bebidas ha mais de 20 anos, com foco em expandir o mercado levando boas experiência com as nossas marcas para os nosso clientes.

## Como se candidatar

Para se candidatar, acesse: [https://www.recrutasimples.com.br/vaga/-L7PRACr3S2OU0vmzjIK?referrer=githubBacktendVagas](https://www.recrutasimples.com.br/vaga/-L7PRACr3S2OU0vmzjIK?referrer=githubBackendVagas)

## Labels

- CLT

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
