### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack na ADIRETO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1273]
### Sobre a empresa: Adireto

A Adireto entrou no mercado do marketing digital e logo se especializou em compra de tráfego online, atingindo resultados milionários em pouco tempo de atividade no Brasil. Com metas agressivas de crescimento, busca fazer história e gerar grande impacto. Suas marcas alcançam literalmente milhões de pessoas todos os meses.

### Descrição: O que você irá fazer?

Desenvolver soluções web, garantindo a entrega do escopo no prazo acordado, com alta qualidade de entrega.
Contribuir nos projetos e propor as melhores práticas em desenvolvimento web.
Autonomia para tomada de decisões técnicas dos projetos, ainda que seja necessário seguir algum guideline em alguns casos.

### As habilidades necessárias:

Você irá trabalhar com o desenvolvimento MEAN:
JavaScript;
MongoDB;
Node.js;
Angular.js;
Express.js;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Entende que os prazos são importantes e leva isso a sério;
Gosta de trabalhar de onde estiver e lida muito bem com isso;

### Candidatar: http://bit.ly/adireto_fullstack

**Comment by grrlopes** [comment]
O sistema de cadastro est'a gerando timeout.
Teria outra maneira de cadastrar a vaga as email.

**Comment by jair-anderson-souza** [comment]
Também não consegui realizar a submissão.
