### ISSUE TITLE
[São Paulo] Back-End Developer na Hash

### ISSUE THREAD

**Issue by carolgdsouza** [backend-br/vagas#1286]
### Faça parte da evolução dos serviços financeiros brasileiros e ajude a construir as melhores estruturas e meios de pagamentos do mercado!
______________________________________________________________________________________________________
**Sobre a Hash**

> "Oferecemos uma plataforma em que qualquer empresa pode se tornar um próprio serviço de pagamento e oferecer isso à sua rede de clientes. Agora, nossos desafio é escalar esta plataforma para oferecer a melhor experiência de meios de pagamento do mercado e contribuir para democratizar o acesso ao ecossistema de serviços financeiros em todo Brasil.
>
> Vamos quebrar paradigmas juntos e, para que isso seja possível, estamos montando um time de alto nível técnico, responsável e autônomo."

**O que buscamos?**

> Pessoas apaixonadas por programação, com experiência na construção de produtos escaláveis e experiência técnica excepcional. Queremos pessoas que se conectem com nossos negócios e queiram construir algo que mude o Brasil!

**Diferenciais**

> - Ter experiência anterior trabalhando com Node.js, Mongodb, Postgres, Clojure, Golang
> - Tenha experiência com sistemas em um ambiente de produção e aplicativos de missão crítica.

**Benefícios**
> - Remuneração: entre R$8.000 e R$18.000 (a depender da senioridade)
> - Vale refeição
> - Vale transporte
> - Assistência médica
> - Assistência odontológica
> - GymPass
> - Escolha sua própria configuração de notebook
> - Remote friendly
> - Massagem no escritório

**Gostou da oportunidade? Candidate-se com a gente!**
> Através do link: https://vagas.byintera.com/hash/back-end-developer/

**Labels**
> - CLT
> - Presencial

**Comment by guilhermeoa07** [comment]
Qual a senioridade? O processo seletivo pode ser feito remotamente?

**Comment by carolgdsouza** [comment]
Olá, Guilherme! Tudo bem?

A Hash está procurando pessoas com experiência entre 3 a 5 anos na área,
mas está disposta a avaliar outras realidades também.

O processo é todo feito remotamente e bem dinâmico! Basta se inscrever no
link que as etapas serão enviadas por e-mail.

Fico à disposição caso tenha quaisquer dúvidas.

Em ter, 2 de jul de 2019 às 18:54, Guilherme Oliveira <
notifications@github.com> escreveu:
