### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Java Senior na Hive

### ISSUE THREAD

**Issue by diemoritat** [backend-br/vagas#129]
# Sobre a vaga
Dev Java Senior PJ alocado próximo ao Shopping Morumbi, SP.

# Requisitos 

**Básicos:**

- +7 anos de experiência
- Vivência em ambiente agile (Scrum)
- Arquitetura de softwares web
- Inglês avançado (conversação e escrita/leitura) - vai trabalhar diretamente com um time nos EUA

- Backend development:
  - Java + tecnologias envolvidas no deploy de soluções baseadas no CQ (maven)
  - Java EE
  - JSP
  - Desenvolvimento de REST APIs e servlets

- Outras tecnologias:
  - Apache Sling
  - CQ5 Framework / Adobe Day
  - BONUS - AEM 6.1, 6.2, 6.3
  - Linux e OS X

**Desejáveis:**

- BONUS - Alguma experiência com Adobe AEM
- Frontend development:
  -  Nível avançado em tecnologias de frontend (JavaScript, HTML, CSS, SASS)
  -  Webpack (1 e 2)
  -  Sightly
  -  BONUS - React

# Contratação
PJ

# Para se candidatar
Interessados podem mandar email pra nayara@hive.com.br ou ariel@hive.com.br com currículo atualizado :)

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
