### ISSUE TITLE
[São Paulo] Back-end Software Engineer no Mercado Livre

### ISSUE THREAD

**Issue by matheussita** [backend-br/vagas#1294]
### **Quer fazer parte de uma das principais empresas do setor de comércio eletrônico? Então dá uma olhada na descrição abaixo!**

No Mercado Livre estamos democratizando o comércio, o dinheiro e os pagamentos na América Latina.

A tecnologia é a essência do nosso produto. Nossas equipes de desenvolvimento, arquitetura, banco de dados, user experience e business intelligence cocriam e são responsáveis ​​pela plataforma líder de e-commerce da América Latina e um dos sites de maior tráfego em todo o mundo. Em uma indústria que é reinventada todos os dias, nossas equipes são reconhecidas por sua visão e liderança. De aplicativos móveis até machine learning, nossa inovação tem um foco claro: simplificar a vida da pessoa que usa nossos produtos.

**Temos um desafio para as pessoas que:**

- Vibram energia empreendedora: são movidas pela curiosidade, nunca desistem e estão focadas em superar seus próprios limites.
- Dão o máximo, porque adoram trabalhar com compromisso e dedicação.
- Encaram as mudanças como oportunidades e aprendem com seus erros.
- A excelência e a execução são primordiais na sua forma de fazer as coisas.
- Promovem o bom clima, alegria e diversão.
- Sabem como construir com outras pessoas e desfrutam trabalhando em equipe.

**Buscamos pessoas que:**

- Contam com experiência prévia com desenvolvimento Back End em ambientes de alto desempenho e escalabilidade.
- Tem experiência com tecnologias como Java, Go, Groovy, Golang, NodeJS, APIs REST, Git, New Relic, entre outras.
- Possuem experiência em bancos de dados relacionais e NoSQL, além de já ter atuado em ambientes de nuvem.

**​​​​​​​Imagine você empreendendo projetos desafiadores, dinâmicos e inovadores, e sendo responsável por:**

- Participar de todas as fases do design de produto de alto impacto, analisando os requisitos e propondo soluções que agreguem valor a área técnica e de negócios.
- Colaborar nas definições de arquitetura e escalabilidade dos nossos produtos.
- Garantir a qualidade do código.
- Identificar e propor melhores práticas para Back End, participando da definição do projeto, revisão do código, testes e manutenção.

**​​​​​​​Nós lhe propomos:**

- Ser parte de uma empresa com espírito empreendedor, na qual adoramos pensar grande e em longo prazo.
- Ser protagonista de seu desenvolvimento em um ambiente de oportunidades, aprendizagem, crescimento, expansão e projetos desafiadores.
- Compartilhar e aprender em equipe, com excelentes profissionais e especialistas.
- Um excelente clima de trabalho, com tudo o necessário para você viver uma grande experiência. :)

### **Diversidade**

No Mercado Livre, trabalhamos para promover uma cultura inclusiva, que busca a equidade e valoriza as diferentes perspectivas. Isso se traduz em Gênero, Religião, Pessoas com Deficiência, LGBTQ+, Raça, Etnia e diversidade de experiências. Trabalhamos todas nossas vagas com base nessa premissa.
 
### **Localização**

A Melicidade, como carinhosamente chamamos nosso humilde escritório de 33 mil metros quadrados, está localizada na região de Osasco, próximo à entrada da Rod. Pres. Castelo Branco, e possui as seguintes instalações:

- +100 salas de reunião.
- Auditório para 200 pessoas.
- Biblioteca e espaços de descanso (bem no meio do escritório).
- Estacionamento.
- Academia (Bio Ritmo).
- Restaurante com capacidade de 450 pessoas, contando com 4 tipos de gastronomia.
- Entretenimento: salão de jogos, manicure, massagista e nutricionista.
- Quadra de esportes.
- Redes de descanso no Jardim, e muito mais!

Veja abaixo algumas matérias sobre a Melicidade!

https://exame.abril.com.br/negocios/por-dentro-da-nova-cidade-do-mercado-livre/
https://www.startse.com/noticia/mercado/28886/conheca-o-gigantesco-escritorio-do-mercado-livre-melicidade

### **Forma de contratação**

A contratação é feita pelo Mercado Livre, em regime CLT.

### **Como se candidatar**

A candidatura pode ser feita facilmente pelo [site da Talenses](https://talenses.com/pt/oportunidades/2d2a06ed-736d-4bbc-8e20-7613ccb25d3b), ou envie seu CV/LinkedIn para o e-mail matheus.sita@talenses.com, com o assunto [Back-end Software Engineer @ Mercado Livre].

**Comment by luicesar** [comment]
Qual e-mail envio meu currículo ?

**Comment by matheussita** [comment]
> Qual e-mail envio meu currículo ?

Post atualizado com infos.!
