### ISSUE TITLE
[REMOTO ou São Paulo] - Desenvolvedor backend, qualquer nível de experiência

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#1297]
Olá, pessoal,

Estamos em busca de pessoas que tenham interesse em trabalhar (remotamente) na área de desenvolvimento da Simbiose, qualquer que seja sua linguagem e nível de conhecimento atual. Temos oportunidades para todos os níveis.

Para se candidatar, basta seguir os passos indicados no link abaixo:
https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

**Carga horária:**
Opções de 4 ou 6 horas diárias.

**Remuneração:**
De acordo com seu nível de conhecimento e maturidade (pessoal e profissional).

**Forma de contratação:**
CLT ou PJ

**Local de trabalho:**
Opções de trabalho remoto OU no escritório em São Paulo (Av. Dr. Chucri Zaidan, 1550).

**Benefícios:**
- Horário de trabalho realmente flexível
- Participação significativa nos lucros e sucesso da empresa, veja:
https://www.simbioseventures.com/sobre-a-simbiose/compartilhamento-de-sucesso

**Candidatar:**
Para se candidatar, basta seguir os passos indicados no link abaixo:
https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

**Comment by nelsonmfinda** [comment]
@gmenegatti Aceita candidato de fora?

**Comment by gmenegatti** [comment]
Olá, @nelsonmfinda, aceitamos sim.

**Comment by Henriquepb22** [comment]
bom dia, quantas vagas são? vou realizar os testes e enviar essa semana ainda

**Comment by gmenegatti** [comment]
Olá, @Henriquepb22, não temos um número máximo de vagas. Nesse momento buscamos pelo menos 7-10 pessoas.

**Comment by felipe5215** [comment]
Olá! Qualquer nivel de experiência inclui também nenhuma experiência(tech-related)?

O estudante curioso aqui pergunta porque não custa nada, não é mesmo?

**Comment by rodrigoms2004** [comment]
Olá!

Trabalho próximo a Berrini, tenho uma empresa e presto Consultoria em IoT (Internet of Things), gostaria de saber sobre trabalho remoto, entregando os jobs de acordo com a demanda, como faço hoje.

Monto sistemas de Backend em NodeJS com banco de dados MySQL, MS-SQL e MongoDB, além de usar RabbitMQ em um projeto recente. Outra coisa que tenho bastante demanda, relativamente simples de fazer mas muito funcional são os bots em Telegram. 

Ah muito legal o site de vocês, a proposta é interessante. Vocês desenvolvem bastante coisa em Data Warehouse pelo visto.

Abraço

**Comment by gmenegatti** [comment]
Olá, @felipe5215, infelizmente precisa ter alguma vivência com tecnologia. Apenas conteúdo teórico já basta, mas não saber nada sobre lógica ou programação infelizmente inviabiliza.

Olá, @rodrigoms2004, agradeço pela oferta, mas não trabalhamos com "freelancers". O nosso modelo de trabalho remoto é igual um trabalho normal, porém feito da sua casa e com certa flexibilidade de horários.

**Comment by gmenegatti** [comment]
Pessoal, acabei de enviar um email com o feedback para todos que se inscreveram e infelizmente não foram selecionados dessa vez.

Agradeço profundamente a participação de todos.

IMPORTANTE: O processo de seleção continua aberto e selecionando pessoas.

**Comment by rodrigoms2004** [comment]
@gmenegatti de qualquer forma obrigado pelo retorno!

**Comment by leopedroso45** [comment]
Olá @gmenegatti, vou efetuar a inscrição, espero que não seja tarde demais.

**Comment by gmenegatti** [comment]
Olá, @leopedroso45, obrigado. Fique tranquilo, esse processo de seleção não se encerra nunca.

**Comment by raphach7** [comment]
@gmenegatti, ainda estão contratando? Qual a flexibilidade do horário para trabalho remoto?

**Comment by leopedroso45** [comment]
Aproveitando que o @raphach7 reviveu essa Thread... Informo que fiz uma entrevista no dia 24 de Julho e até hoje não recebi feedback algum!

É importante esse feedback até para entender melhor o ponto onde o candidato "errou" (Em relação a cultura da empresa e etc).

**Comment by Henriquepb22** [comment]
Também gostaria de receber meu feedback. Fiz a entrevista dia 12 de agosto com uma pessoa da equipe e dia 16 de agosto com o Gabriel e ainda não recebi nenhum feedback. Gostaria de receber para saber o que preciso melhorar e onde errei, assim como o @leopedroso45 falou!

**Comment by fabiomirandaa** [comment]
É engraçado porque ele falou "esse processo de seleção não se encerra nunca", e pelo visto não se encerra mesmo.. Não dão nem a resposta pra não finalizar rs

**Comment by gmenegatti** [comment]
Olá, pessoal,

Peço sinceras desculpas pela demora no retorno. Estive ausente da empresa por 15 dias e, como sou eu quem conduz todo o processo de seleção, realmente algumas respostas não haviam sido enviadas.

Quem foi aprovado para as próximas fases já recebeu um email informando os próximos passos. Ainda não consegui enviar o email de agradecimento para quem não foi aprovado, mas farei isso ainda hoje.

O processo continua aberto e selecionando pessoas. Nos últimos 90 dias nós contratamos mais de 30 pessoas para a equipe.

Obrigado pela compreensão.

**Comment by messiasdias** [comment]
Olá, gostaria de saber se o anuncio ainda é válido.
Se sim me coloco à disposição.
Desde já, muito grato!
