### ISSUE TITLE
[FECHADA] Developer JavaScript na Instruct

### ISSUE THREAD

**Issue by iassia** [backend-br/vagas#1299]
Estamos buscando um(a) profissional que consiga trabalhar em um time multidisciplinar, que tenha bons conhecimentos em desenvolvimento utilizando JavaScript para tarefas de backend e ocasionalmente frontend.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

É fundamental saber aprender novas tecnologias e que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem-vindas e importantes.

Precisamos que você conheça JavaScript voltado para implementação de backend (Node.js) e ocasionalmente aplicação de bibliotecas ou frameworks frontend. Conhecimento e experiência em integrações diversas, APIs REST, banco de dados e testes unitários são fundamentais. Conhecimento da linguagem Python é um diferencial.

O trabalho poderá ser realizado totalmente remoto, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente.

**Benefícios**

- Regime de contratação CLT;
- Salário inicial entre R$ 3.500,00 e R$ 5.000,00;
- Plano de saúde e odontológico Bradesco Top Nacional Top para o titular e mais um dependente totalmente custeados pela empresa (dependentes adicionais podem ser incluídos com desconto em folha);
- Vale refeição de R$ 400,00;
- Vale alimentação de R$ 600,00;
- Seguro de vida corporativo custeado pela empresa;
- Verba semestral de R$ 1.250,00 garantida para investimento em treinamentos e educação;
- Bolsas de estudo custeadas pela empresa;
- Acesso aos treinamentos da empresa sem custos;

**Por que trabalhar na Instruct?**

- Ambiente de trabalho amigável, inclusivo e seguro;
- Resolvemos problemas desafiadores e em larga escala para nossos clientes;
- Trabalhar na empresa referência de mercado em infraestrutura como código no Brasil;
- Empresa premiada como "Melhor Parceira Mundial" da Puppet em 2016;
- Acesso gratuito aos treinamentos oficiais Puppet e GitLab ministrados pela Instruct;
- Incentivos para participação em eventos, cursos e palestras;
- Empresa fundamentada nos princípios DevOps, Infra as Code e Agile;
- Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
- Cultura blameless;
- Café de qualidade!

**O que esperamos de você?**

- Esperamos que nos ajude a melhorar a performance dos nossos clientes;
- Esperamos que você consiga se relacionar bem com o seu time de trabalho, que saiba fazer parte do time, respeitar o time, dividir e compartilhar responsabilidades, acertos e aprendizados;
- Esperamos que você possa ir além, propondo, criando, mudando, construindo, crescendo e evoluindo junto conosco;
- Queremos que você agregue valor ao nosso time e a nossa organização, e queremos que a nossa organização agregue valor a você;

**Conhecimentos técnicos**
Estes são os conhecimentos fundamentais para trabalhar conosco:

- Linguagem JavaScript ES5+;
- Banco de dados relacional/SQL;
- Node.js
- Integração de aplicações via APIs REST;
- Testes unitários;
- Uso de Git para versionamento de seu código;

**Diferenciais**
Não são obrigatórios, mas serão devidamente considerados:

- Vue.js ou outro framework ou biblioteca;
- Desenvolvimento backend, preferencialmente utilizando Python;
- Curso superior;

**Tecnologias e métodos**
Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:

- Fundamentos de modelos ágeis como Kanban e Scrum;
- Fundamentos do conceito testes unitários;
- Fundamentos do conceito testes de aceitação;
- Docker e containers;
- Jenkins/GitLab CI;
- Participação em projetos Open Source;

Se você acha que tem as características necessárias para participar de nossos projetos e de nosso time, entre em contato!

LOCAL: Remoto com encontros presenciais
HORÁRIO: 40 horas semanais

Enviar um e-mail com CV para jobs@instruct.com.br
com assunto "Desenvolvedor(a) JavaScript".

**Comment by samuelfaj** [comment]
E-mail enviado :D

**Comment by THAYLLER** [comment]
A oportunidade é incrivel será uma honra se eu participar do processo de seleção

**Comment by JonatanPotrikus** [comment]
Email enviado. Otima oportunidade e realmente a vaga que eu estava procurando. 😍

**Comment by RodrigoGuedelho** [comment]
Email Enviado. Grande oportunida.

**Comment by joninter** [comment]
E-mail enviado, grande oportunidade.

**Comment by THAYLLER** [comment]
Qual e o tempo de retorno?

**Comment by JonatanPotrikus** [comment]
@THAYLLER minha primeira etapa levou quase 24Hrs para resposta. Ja na segunda foi mais rapido. Levou umas 12 horas. Terceira etapa agora entrevista tecnica.

**Comment by THAYLLER** [comment]
@JonatanPotrikus então pra mim ate o momento nao teve nenhum retorno kkkk

**Comment by JonatanPotrikus** [comment]
@THAYLLER pensamento positivo irmão kkk. Muitos candidatos eu acho, deve levar um bom tempo esse processo.

**Comment by THAYLLER** [comment]
Sim @JonatanPotrikus  por isso que perguntei se tem um tempo de resposta pq e chato nao receber nenhum feedback

**Comment by iassia** [comment]
Vaga encerrada! Obrigado pelo envio e participação de todos!
