### ISSUE TITLE
Analista Desenvolvedor web - .NET

### ISSUE THREAD

**Issue by Pmirandaricardo** [backend-br/vagas#13]
Somos 1 grupo composto por 5 empresas que atuam no segmento de Tecnologia de trânsito, estamos presente em quase todos os estados do Brasil, temos 30 anos de mercado e, estamos crescendo agressivamente.
Buscamos profissionais curiosos, que gostem de propor ideias e novas tecnologias, para um de nossos projetos: 
Reconhecimento Facial e biometria,para a obtenção da CNH e processo de reciclagem da CNH.

Obrigatórios:
•	C#
•	ASP.Net MVC
•	Banco de dados relacional (SQL Server)
•	Domínio em arquitetura de APIs RESTFul;
•	Angular JS
•      WCF, ORM, Nhibernate, DDD
•	Experiência com Controle de Versão
•	Utilizar padrões e boas práticas para desenvolvimento
•	Experiência com desenvolvimento em C# em plataforma Web.

Local de trabalho: São Paulo/SP, próximo à estação São Judas.
Não há possibilidade de trabalho remoto.
Contratação CLT.
Início imediato.

Envie  seu currículo para: pmiranda@tecnowise.com.br
Grata :)

**Comment by reginaldojunior** [comment]
vaga preenchida? posso fechar a issue?

**Comment by Pmirandaricardo** [comment]
Olá, Reginaldo!

 

Por gentileza.

 

Abraços,



 

De: Reginaldo Junior [mailto:notifications@github.com] 
Enviada em: quarta-feira, 28 de fevereiro de 2018 16:24
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Pmirandaricardo <pmiranda@tecnowise.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] Analista Desenvolvedor web - .NET (#13)

 

vaga preenchida? posso fechar a issue?
