### ISSUE TITLE
[São Paulo] Back-End Developer na [Cel.Lep Ensino de Idiomas S.A]

### ISSUE THREAD

**Issue by rhcellep** [backend-br/vagas#130]
**Nossa empresa**
Cel.Lep é uma conceituada escola de inglês e espanhol que atua no segmento de idiomas há 50 anos tradicionalmente em São Paulo e algumas cidades do interior de SP, e em 2017 adquiriu a escola de programação MadCode que desenvolve suas atividades com os públicos teens e kids.

Acreditamos que um novo idioma é fundamental para abrir muitas portas na vida e que nos próximos anos aprender a programar será tão importante como é hoje o conhecimento de uma segunda língua.

**Descrição da vaga**
Atuação como Back End Developer no ramo Educacional.

**Local**
Morumbi - São Paulo.

**Requisitos**
GIT
PHP
LARAVEL 5.3
MySQL
Eloquent ORM
Autenticação JWT
CORS
API Restful

**Formação**
Ensino superior (cursando ou concluído) em uma das áreas abaixo:
- Sistema de Informação
- Gestão em Tecnologia da Informação
- Análise e Desenvolvimento de Sistemas
- Ciência da Computação
- Engenharia da Computação

**Contratação**
CLT, 40h semanais.

**Como se candidatar**
Enviar email para hana.chiarelli@cellep.com com CV anexo e assunto: Vaga Back End.

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
