### ISSUE TITLE
[Bauru -SP] Desenvolver Web [Arca Solutions]

### ISSUE THREAD

**Issue by joaoderoldo** [backend-br/vagas#1300]
Fala galera, tudo tranquilo ? a Arca Solutions esta com uma vaga para Dev. Web.

**Requisitos:**
 - Superior completo ou cursando em TI
 - Inglês avançado
 - PHP
 - MySQL
 - GIT

**Diferenciais:**
 - Framework Symfony
 - Elasticsearch

Para se candidatar acesse o link: https://bit.ly/2RX3nsg

**Comment by joaomsneto** [comment]
Olá,
Pode ser remoto?

**Comment by joaoskr** [comment]
> Olá,
> Pode ser remoto?

**Comment by joaoderoldo** [comment]
> Olá,
> Pode ser remoto?

Infelizmente para essa vaga não João.
Att.
