### ISSUE TITLE
[Rio de Janeiro] Estágio Back-End Ingresso.com

### ISSUE THREAD

**Issue by f2l2pe** [backend-br/vagas#1301]
Atribuições/Conhecimentos: o estagiário irá trabalhar no desenvolvimento de projetos em ambiente web na linguagem .NET com banco de dados MySQL, MongoDB e nuvem da AWS

Competências:
- Saber trabalhar em equipe;
- Focado;
- Procurando sempre se atualizar em tecnologias;
- Ser organizado;
- Dinamismo e proatividade;
- Aberto a críticas;
- Gostar de estudar;
- Gostar de desafios;

Requisitos:
- Escolaridade: cursando nível superior em faculdade de bacharelado em Informática, Ciências da computação ou afins;

Conhecimentos:
- Lógica de programação;
- Noções de orientação a objetos;

Carga Horária : 6h
Remuneração : R$ 1500,00 + VR + VT
Local : Centro

Caso você tenha o perfil acima e queira participar do processo seletivo ou conheça alguém, favor enviar currículo atualizado para rh@ingresso.com com o cargo no assunto do e-mail.

**Comment by Josemaralves** [comment]
Enviado ;)
