### ISSUE TITLE
[Belo Horizonte, MG] ESTAGIÁRIO PROGRAMAÇÃO na Grupo Selpe

### ISSUE THREAD

**Issue by lucasparisi** [backend-br/vagas#131]
![Grupo Selpe Logo](http://www.gruposelpe.com.br/img/grupo-selpe.svg)

### Local<h3>
Belo Horizonte

### Job<h3>
- Suporte aos usuários do sistema;
- Parametrizações no sistema;
- Programações conforme orientação do desenvolvedor;
- Elaborar tutoriais e vídeos para os usuários do sistema;
- Apoiar alterações do novo layout do sistema conforme orientações da consultoria.

### Padrões<h3>
- Técnico em Programação e curso Superior em andamento em Sistemas de Informação;
- Conhecimento em SQL | PHP | Java Script | Ajax | CSS | Html;
- Inglês intermediário.

### Formação<h3>
Técnico Completo e Superior Cursando - Sistemas de Informação (Análise de Sistemas)

### Contratação<h3>
Estágio

### O Grupo Selpe<h3>
O Grupo Selpe é uma consultoria de Recursos Humanos com mais de 50 anos de história e procuramos devs apaixonados por tecnologia (claro) e que tenham vontade de transformar a maneira que empresas e candidatos se conectam no mercado de Recursos Humanos.

### Como aplicar:<h3>
Inscreva no [link do Recrutamento Inteligente](https://www.recrutamentointeligente.com.br/vaga/R02472)

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
