### ISSUE TITLE
[Belo Horizonte] Java Developer na [Cast group]

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#1319]
Descrição da vaga
Projeto para instituição financeira desenvolvido em Java 8, AngularJS, JavaScript, Hibernate e Spring.
Local
Alocado em cliente – Bairro Santo Agostinho
Benefícios
•	Plano de médico e odontológico 
•	Seguro de vida
•	VR/VA
•	VT
•	Benefícios flexíveis
Diferenciais
•	Horário flexível
•	40 horas semanais
•	Plano de carreira
•	No dress code
Requisitos
Obrigatórios:
•	Experiência sólida em Java 
•	Experiência sólida em AngularJS  
•	Experiência sólida em JavaScript
•	Experiência sólida em Hibernate
•	Experiência sólida em Spring
Contratação
CLT a combinar 
Nossa empresa
Com 28 anos de mercado, a Cast group é uma empresa nacional de Tecnologia da Informação e automação com larga experiência em grandes projetos para as áreas privada e pública, que atua com consultoria e soluções de TI e TA.
Hoje, a Cast group é reconhecida por seus mais de 320 clientes, especialmente nas áreas de finanças, indústrias e serviços, como, Banco do Brasil, Cielo, Datasus, Vale, Cemig, Gerdau, EDP, Eletrobrás, Grupo Petrópolis, Atento, Renault, Randon, Bosh, Ipiranga Agroindustrial, DrogaRaia e Banco Central do Brasil.
Como se candidatar
Por favor, envie um email para recrutamentoeselecao@castgroup.com.br com seu CV anexado - enviar no assunto: Analista de Sistemas Java SR BH
Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo. E-mail para contato em caso de não haver resposta: recrutamentoeselecao@castgroup.com.br
Labels
•	Alocado
•	CLT
•	Sênior
•	Analista
•	Cast
•	BH
•	Java
•	Angular
![Java SR BH](https://user-images.githubusercontent.com/46196842/60908457-4f1f9a80-a252-11e9-9388-a6af39b5127d.jpg)

**Comment by ghost** [comment]
Ainda estamos com a oportunidade em aberto!

**Comment by FelipeAragao** [comment]
Aceita remoto?

**Comment by ghost** [comment]
Boa tarde!

Para esse projeto énecessária disponibilidade para alocação.



Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
