### ISSUE TITLE
[Campinas] Desenvolvedor Node na PJ BANK

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1320]
### Sobre a empresa: PJ Bank

PJBank é a conta digital e serviço de recebimentos e pagamentos que chegou para revolucionar a operação financeira de sua empresa. Saiba mais sobre a gente em https://pjbank.com.br

### Descrição:

Estamos à procura de Desenvolvedor Node, capaz de trazer soluções rápidas, com mindset enxuto, crítico e empreendedor, alguém que seja protagonista, questionador e ousado! Se identificou?

Continue lendo, então!

### Sobre a PJ Bank:

Nossa cultura é muito forte, somos adeptos a feedbacks instantâneos, diálogo aberto, participação, colaboração e propósito bem definido. Criamos um ambiente onde você pode trabalhar de forma flexível, construir relações saudáveis e desenvolver o melhor delas.

### Seu papel:

Procuramos devs, nos níveis pleno ou seniores, que tenham sólidos conhecimentos comprovados em Node Js, que tenham foco em resolver problemas e gerar valor ao negócio.

### Sua experiência:

Experiência comprovada com Node Js;
Experiência comprovada com banco MySQL e otimização de queries;
Experiência comprovada com API;
Experiência comprovada de testes unitários;
Experiência comprovada com cacheamento;
Base sólidas em orientação a objetos;
Experiência em validar performance de aplicação;
Gestão de logs;

### Experiências extra:

Experiência no desenvolvimento de chatbots ;
Experiência em Serverless AWS;
Experiência comprovada em projetos com altíssimo volume de transações.

### O que significa escolher a PJ Bank:

Modelo de gestão startup;
Times enxutos, auto-geridos com modelo similar ao squad do Spotify;
Ambiente colaborativo, pouca burocracia e pouca hierarquia;
Ambiente inclusivo e de aprendizado continuo;
Plataforma Alura para treinamento online;
Espaço próprio para eventos Superlógica Labs com execução, apoio e presença nos eventos na cidade;
280 títulos de livros em nossa biblioteca particular;
Lanchonete interna;
Mesa de ping-pong e video-Game;
Convenio com escola de idiomas Excellent Global(opcional).

### Algumas outras vantagens incluem:

Contratação CLT ou PJ
Plano de saúde
Plano odontológico
Refeição no local
Vale transporte

### Candidatar: http://bit.ly/pjbank_node

**Comment by tiago123456789** [comment]
E possível atuar **remotamente**?

**Comment by danielsidev** [comment]
Olá @megandavulpi ! Tudo bem?
Essa vaga pode ser remota? Sou do RJ! =)
Abraços!
http://danielsiqueira.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
