### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na DESCOMPLIQUE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1327]
### Sobre a empresa: Ddma Comunicação Eirelli

Somos uma empresa de tecnologia que atua no mercado há mais de 9 anos. Investimos em nossos serviços com objetivo de servir pequenas e médias empresas, trazendo tecnologia de ponta a um preço acessível. A chave do nosso trabalho é servir e reduzir custos de TI dentro do seu ambiente.

### Descrição: Ocupações do cargo

Este profissional será o principal responsável das ações de criação e manutenção dos projetor novos e já existentes.

Terá uma atuação de suma importância, onde estará presente desde o alinhamento com o cliente até a entrega do projeto.

### Benefícios

Regime de Contratação Flexivel, podendo optar por CLT ou PJ
Férias remuneradas para PJ
Uma cultura extremamente horizontal.
Material de ponta para trabalhar

### Aptidões e qualidades

Buscamos pessoas focadas em solução, que querem crescer aprender e executar da melhor forma. Utilizando as tecnologias de maior destaque do mercado.

### Para isso é preciso que você seja fera em:

PHP
Javascript; HTML; CSS
Ajax:Jquery.
Ter sistemas operacionais: Linux
Framework: Laravel
Bootstrap
Arquitetura de programação com MVC. 

### Vai ser um diferencial se você souber:

Manipulação de webservices/dados,
WEB-API,
Json requisições
CUrl .
React Native

### Candidatar: http://bit.ly/descomplique_fullstack

**Comment by jair-anderson-souza** [comment]
Remoto?
