### ISSUE TITLE
[São Paulo, São Carlos] Desenvolvedor Back-end Pleno/Senior [Diin]

### ISSUE THREAD

**Issue by brenooliveira** [backend-br/vagas#1337]
Quer ajudar milhares de pessoas a guardar dinheiro, junto com a inclusão no mundo de micro investimentos? Venha fazer parte do nosso time! 

**Onde estamos?**
Cubo Network ou Onovolab São Carlos

**Requisitos**
 - Conhecimento em alguma linguagem OO;
 - Testes automatizados (TDD/BDD);
 - Sólidos conhecimentos de protocolos de rede (HTTP/gRPC/TCP/UDP/IP);
 - Modelagem e consumo de APIs RESTful;
 - Containers (Docker);
 - Serviços AWS (Lambda, EC2, ECS, SQS);
 - Vivência em metodologias de desenvolvimento de software.

**Tecnologias**
 - Kotlin/Java, Python, NodeJS
 - SpringBoot / Netflix Stack
 - MySQL
 - Redis

**Desejáveis**
 - Conhecimento em linguagem funcional (Elixir, Scala, Haskell) 
 - Entrega Contínua (Gitlab CI, Jenkins, TravisCI, CircleCI, etc);
 - Conhecimento em arquitetura de micro-serviços;
 - Kubernetes;
 - Git / GitFlow

**Diferenciais** 
 - Um bom GitHub e contribuições Open-source;
 - ReactNative;
 - Ops Tools ;

**Contratação**
PJ

**Topa?**
Me mande um e-mail breno@diin.com.br com seu LinkedIn e GitHub.

**Comment by FelipeAragao** [comment]
Olá @brenooliveira,

Aceita remoto?

**Comment by brenooliveira** [comment]
@FelipeAragao ainda não temos 100% remoto
