### ISSUE TITLE
[Salvador] Senior Back-end Developer na Cubos

### ISSUE THREAD

**Issue by rafaassism** [backend-br/vagas#1345]
## Responsabilidades e atribuições da vaga:

- Participar ativamente nas etapas de ideação, planejamento e desenvolvimento dos produtos dos nossos clientes;
- Participar de discussão das tecnologias que serão utilizadas nos projetos;
- Criar endpoints de APIs que serão consumidas por desenvolvedores web, android e iOS. Seja amigo deles! :p
- Compreender as ferramentas que usa em um contexto DevOps, sendo capaz, em situações problemáticas, de desenvolver um raciocinio lógico consistente para investigar e resolver o problema;
- Disposição para ajudar e compartilhar conhecimento;
- Ser curioso e estar disposto a se arriscar em novas tecnologias.

## Nossa stack Backend:

- Typescript
- Node.js
- RethinkDB
- Postgres
- Docker
- Kubernetes
- Gitlab CI
- Local

### Obrigatórios:

- Experiência com arquitetura de banco de dados;
- Experiência com projetos de alta disponibilidade;
- Expertise em NodeJs e Javascript ES6+;
- Experiência com outras linguagens de programação (Go, PHP, Elixir, Clojure...);
- Experiência fazendo APIs;
- Experiência com Docker ou Kubernetes;
- Experiência com bancos de dados SQL e NoSQL.

### Diferenciais:

- Leitura na língua inglesa;
- Conhecimento em Typescript;
- Experiência com GraphQL;
- Apresentação de portfólio, Github ou similares;
- Experiência com CI.

## Contratação
CLT a combinar

## Benefícios
Plano de saúde;
Plano odontológico;
Vale alimentação ou refeição de R$ 26,00/dia;
Vale transporte.
Aulas semanais multidisciplinares;

## Sobre a Cubos
A Cubos existe para transformar a realidade ao seu redor. Temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia.

Nosso alicerce é a educação: somos um hub, absorvendo, compartilhando, produzindo conhecimento. Todo esse conteúdo se reflete nos nossos serviços e produtos, culminando em entregas incríveis, com foco na melhor experiência para o usuário. Vamos além do desenvolvimento. Por isso, não nos limitamos pelo padrão, assumimos riscos que nos dão a adrenalina necessária para alcançar resultados desafiadores. Todos os dias cuidamos das pessoas: aquelas que estão na Cubos; aquelas que são familiares e amigos; aquelas que são parceiros; aquelas que vemos no dia a dia; aquelas que nos tocam.

Oferecemos um ambiente colaborativo com bastante café, flexibilidade, pessoas incríveis dispostas a aprender e ensinar. Usamos tecnologia porque dá acessibilidade de conhecimento, porque simplifica o mundo, porque tecnologia é sinônimo de evolução, porque tecnologia é consequência da própria existência humana. Criamos tecnologia com significado.

Como se candidatar
Se inscreva na vaga através desse [link](https://cubos.gupy.io/jobs/59929?jobBoardSource=gupy_public_page).

**Comment by rafaassism** [comment]
Labels:
- Sênior
- NodeJs
- Typescript

**Comment by grrlopes** [comment]
E possivel atuar remotamente  ?

**Comment by rafaassism** [comment]
> E possivel atuar remotamente ?

Olá, Gabriel!
É possível para algumas vagas. Depende do projeto e do nível do candidato. Hoje temos vagas para projetos com essa possibilidade.
