### ISSUE TITLE
[REMOTO] Senior - Desenvolvedor FullStack (React+NodeJS) / TheChecker

### ISSUE THREAD

**Issue by danihenrique** [backend-br/vagas#1348]
[TheChecker](https://thechecker.co/)

**Descrição da empresa**

TheChecker is an accurate email verification system that brings quality results at affordable prices. We are the most cost-effective email verification service. Reduce email bounces, improve inbox deliverability and open rates, protect sender reputation, and more. Get the highest ROI on your email marketing campaigns.

We are trusted by thousands of professionals at the smartest companies from 135+ countries, such as WeWork, Accenture, Ebanx, Tereos, Rock Content, MJV, and many others.

We are the most cost-effective and most loved #1 email verifier GLOBALLY according to independent reviews (https://www.g2.com/categories/email-verification#highest_rated).

**Atividades e Responsabilidades**
Você ajudará no crescimento de uma startup global, que já tem usuários de mais de 130 países. Trabalhamos para dominar nosso nicho de validação de emails globalmente.

Acreditamos que um time de desenvolvedores e designers brasileiros pode construir ferramentas do nível das melhores do Vale do Silício. Pensamos grande e estamos fazendo acontecer. Se você quer fazer parte de uma empresa global e inovadora, junte-se a nós! ;)

- Especialista em React; 
- Realizar a manutenção e criação de novas funcionalidades; 
- Aplicar melhores práticas de documentação de código desenvolvido; 
- Desenvolver e sustentar integrações; 
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas; 
- Desenvolvimento de funcionalidades no Back-End (NodeJS); 

**Requisitos**
- Habilidades interpessoais de escrita e de comunicação verbal; 
- Experiência prévia nas linguagens informadas; 
- Experiência com ferramentas de versionamento de código (GIT,...); 
- Inglês Intermediário; 
- Conhecimento em metodologias ágeis (Scrum/Kanban); 
- Gostar de aprender: usamos o que for preciso para resolver nossos desafios e precisamos aprender rápido; 
- Ser analítico e detalhista: você vai ser dono das entregas, confiaremos nas suas decisões; 
- Se amarrar em construir um produto: aqui você não é fábrica de código, esperamos que você se envolva nas discussões e seja dono do projeto tanto quanto a gente;

**Salário: R$9.000,00 PJ**
Enviar email com perfil no **Linkedin**: daniel@thechecker.co

**Comment by robertohonda** [comment]
Alguma oportunidade para Desenvolvedor FullStack (React+NodeJS) pleno remoto?

**Comment by danihenrique** [comment]
Olá Roberto.
No momento temos uma oportunidade para alguém domine React, com conhecimentos sólidos o suficiente pra entregas contínuas com qualidade.
Se se encaixar no perfil, participe do processo.

Abs

**Comment by lcoalves** [comment]
Boa noite,

Encontrei uma vaga da TheChecker no Programathor e estou interessado. Podemos nos conhecer?
