### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP na Plugg.to

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/vagas#135]
### Tarefas:

    - Criação de integrações utilizando APIs em REST e/ou SOAP;
    - Criação de interfaces web;
    - Manutenção de aplicações de Laravel 4.2+;
    - Modelagem de banco de dados;
    - Criação de documentação.

### Local

Escritório a 5 min do metrô Barra Funda - SP.

### Benefícios

    - Vale-transporte
    - Vale-refeição
    - Horário Flexível com banco de horas
    - Convênio Médico

#### Obrigatórios:

    - PHP, Laravel
    - REST Service
    - JSON
    - XML
    - MySQL
    - Javascript

 #### Desejáveis:

    - Git
    - Linux Debian

### Diferenciais:

    - Projetos OpenSource
    - TDD
    - Design Patterns

### Contratação

CLT

### Nossa empresa

Plugg.to é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces.

Com isso é possível vender muito mais utilizando múltiplos canais de venda, mantendo porém estoques sincronizados, e recebimento e gerenciamento de pedidos em um único ponto.

Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

Sempre buscando a excelência, Plugg.To é mais um produto ThirdLevel notoriamente conhecida por sua primeira integração apenas entre MercadoLivre e o Magento que é utilizada por mais de 300 lojas em 4 países.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015
Como se candidatar

Por favor envie um email para reginaldo.junior@plugg.to com seu CV anexado e pretensão salarial - enviar no assunto: Desenvolvedor(a) PHP

**Comment by hilderjares** [comment]
possibilidade de 100% homeoffice ?

**Comment by reginaldojunior** [comment]
Não, somente presencial no momento!

**Comment by hilderjares** [comment]
blz então

**Comment by fsrocha-dev** [comment]
Entrevista pode ser via Skype ?

**Comment by danielhe4rt** [comment]
A vaga ainda está aberta?

**Comment by reginaldojunior** [comment]
Bom dia não, mas manda curriculo para deixamos anexado a base caso abra mais vagas.
