### ISSUE TITLE
[Belo Horizonte] SRE/DevOps Engineer na NUVEMSHOP

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1350]
### Sobre a empresa: Nuvemshop

Somos uma das principais startups de e-commerce na América Latina. Formamos uma equipe de mais de 150 pessoas, que trabalham de maneira integrada no Brasil, Argentina e México. Nosso propósito é potencializar histórias de sucesso por meio da nossa plataforma. 

Surgimos para que micro, pequenas, médias e grandes empresas criem sua própria loja virtual, de maneira autogerenciável e sem conhecimentos técnicos prévios. Em nossa cultura e em tudo o que construímos, valorizamos muito o compromisso, a transparência, executar com excelência e saber pensar grande e a longo prazo.

### Descrição: Ocupações do cargo

O objetivo principal do cargo é construir uma arquitetura de alta disponibilidade, que seja segura e otimizada, permitindo um alto desenvolvimento da nossa equipe.

Você trabalhará em conjunto com a equipe de desenvolvimento, com intuito de assegurar o uptime e disponibilidade da nossa plataforma, garantindo a resolução de problemas sempre que necessário.

### Desafios

● Infraestrutura cloud de alta disponibilidade utilizando recursos da AWS;
● Otimização de custos com provedores em nuvem;
● Manter e otimizar processos relacionados a monitoramento das aplicações e micro serviços;
● Manter e otimizar processos relacionados a fluxos de Continuous Integration e Continuous Deployment;
● Manter e otimizar réplica de ambientes de desenvolvimento e produção;
● Busca por excelência em alta disponibilidade, resiliência e recuperação de desastres.

### Necessário

● Experiência consolidada com AWS;
● Experiência consolidada com ambientes linux;
● Experiência com docker em ambientes produtivos;
● Conhecimento do comendo UNIX;
● Experiência com linguagens de script (bash, python, go, ruby ou similar).
● Experiência com infraestrutura como código (terraform, cloudformation, protosphere, etc...).
● Experiência com ferramentas de monitoramento (sensu, grafana, prometheus, new relic, etc...).
● Experiência com desenvolvimento de aplicações (nginx, php, java, python, ruby, go,etc...).

### Diferencial

● Experiência com orquestradores de containers (AWS ECS, Kubernetes).
● Experiência com alguma tecnologia de gerenciamento de configuração (Chef, Ansible...).

### Dinâmica de trabalho

Esperamos por um colaborador que cuide do seu tempo de maneira efetiva. Não deixe de pedir ajuda quando necessário, mas é importante que saiba fazer isso sem deixar outras tarefas de lado.

Cada dia conta muito aqui na Nuvemshop. Comprometer-se com o prazo é se comprometer a dar um passo adiante na construção do valor que buscamos para os nossos clientes. Esperamos que entenda isso e cumpra com seus objetivos.

Não somente trabalhamos em construir a infraestrutura, mas também em dar ferramentas para que nossa equipe de desenvolvimento possa desenvolver mais rapidamente. Quanto mais rápido a equipe desenvolve, mais rápido entregamos valor aos nossos clientes.

### Benefícios

● Ambiente de trabalho dinâmico, com equipes multidisciplinares que tomam suas próprias decisões para criar um grande impacto, dentro do ecossistema empreendedor na América Latina;
● Flexibilidade de horário;
● Possibilidade de mudança do local de trabalho de acordo com as demandas;
● Aulas de espanhol no escritório (somos uma empresa bilíngue);
● Plano de saúde e odontológico Bradesco;

### Seguro de vida;

● VT (ou VC);
● VR (ou VA);

### Candidatar: http://bit.ly/nuvemshop_devops

**Comment by jmateusousa** [comment]
Boa tarde, existe a possibilidade de trabalhar 100% remoto ?
