### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor(a) JAVA na Montreal

### ISSUE THREAD

**Issue by isabellimaselpe** [backend-br/vagas#136]
![Grupo Selpe Logo](http://www.gruposelpe.com.br/img/grupo-selpe.svg)

### Local<h3>
Belo Horizonte

### Job<h3>
- Desenvolver soluções de software utilizando a linguagem JAVA e JAVA EE;
- Realizar o desenvolvimento a partir dos artefatos especificação de casos de uso ou histórias de usuário;
- Implementar as soluções conforme de protótipos da especificação;
- Garantir a gestão da configuração para o código fonte desenvolvido;
- Implementar testes unitários.

### Padrões<h3>
- Conhecimento em JAVA e JAVA EE;

### Formação<h3>
- Formação concluída ou em andamento em curso superior em Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou áreas afins;

### Contratação<h3>
CLT

### O Grupo Selpe<h3>
O Grupo Selpe é uma consultoria de Recursos Humanos com mais de 50 anos de história e procuramos devs apaixonados por tecnologia (claro) e que tenham vontade de transformar a maneira que empresas e candidatos se conectam no mercado de Recursos Humanos.

### Como aplicar:<h3>
Inscreva no [link do Recrutamento Inteligente](https://www.recrutamentointeligente.com.br/vaga/R02434) ou por email: isabel.lima@gruposelpe.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
