### ISSUE TITLE
[Porto Alegre] - Back-End Developer na Linx

### ISSUE THREAD

**Issue by diegonogueirasantos** [backend-br/vagas#1367]
**Tá afim de trabalhar em uma empresa incrível, que além de valorizar o colaborador, está com tudo no mercado???**

**Então venha mover o varejo com a gente! Vem para LINX.**

O Desenvolvedor  será responsável pelas seguintes atividades:

- Analisar, controlar e acompanhar os diversos cenários do desenvolvimento.

- Apoiar o Analista no planejamento das implementações e correções do sistema, considerando, Contexto/Riscos/Estratégias/Alocações.

**Habilidades Técnicas Necessárias:**

- Conhecimento em lógica de programação, com experiencia no desenvolvimento de sistemas (Projeto principal em .Net Core);
- Conhecimento em testes unitários (UNIT);
- Conhecimento nos padrões SOAP, REST, XML, WSDL, XSD e JSON;
- Desejável conhecimento de metodologia ágil (Scrum)

**Habilidades desejadas**

- Angular
- WebAPI
- Selenium
- Sql Server
- Conhecimentos em DevOps

**Alguns benefícios**

- Assistência médica e odontológica;
- Vale refeição;
- Vale Alimentação;
- Seguro de vida;
- Plano de carreira;
- Horário flexível;

**Sobre a empresa**

A Linx é uma empresa brasileira especialista em tecnologia para o varejo. Líder no mercado de software de gestão, com 41,3% de market share do mercado varejista, conforme atesta o IDC. Toda a expertise da Linx na jornada de compra é transformada em insights fundamentais para atingir o que os varejistas mais esperam: fidelizar seus consumidores e atingir resultados concretos e relevantes. Com capital aberto desde 2013, a Linx possui cerca de 3 mil colaboradores distribuídos entre sua sede em São Paulo, 13 filiais pelo Brasil e 7 países da América Latina.

Favor candidate-se pelo e-mail **diego.dossantos@linx.com.br**

**Comment by luicesar** [comment]
Aceitam candidatos fora do estado de RS ?

**Comment by diegonogueirasantos** [comment]
> Aceitam candidatos fora do estado de RS ?

@luicesar no momento não estamos aceitam 100% remoto.
