### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor(a) Mobile Android na Montreal

### ISSUE THREAD

**Issue by isabellimaselpe** [backend-br/vagas#137]
![Grupo Selpe Logo](http://www.gruposelpe.com.br/img/grupo-selpe.svg)

### Local<h3>
Belo Horizonte

### Job<h3>
- Desenvolvimento de aplicativos móveis na linguagem JAVA utilizando Android Studio 3.0;
- Desenvolvimento de soluções para backend utilizando linguagem JAVA;
- Desenvolvimento de integrações entre soluções móveis e backend através de Web Services;

### Padrões<h3>
- Linguagem JAVA;
- Android Studio 3.0 ou superior
- Gradle 4.1

### Formação<h3>
- Formação concluída ou em andamento em curso superior em Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou áreas afins;

### Contratação<h3>
CLT

### O Grupo Selpe<h3>
O Grupo Selpe é uma consultoria de Recursos Humanos com mais de 50 anos de história e procuramos devs apaixonados por tecnologia (claro) e que tenham vontade de transformar a maneira que empresas e candidatos se conectam no mercado de Recursos Humanos.

### Como aplicar:<h3>
Inscreva no [link do Recrutamento Inteligente](https://www.recrutamentointeligente.com.br/vaga/R02435) ou por email: isabel.lima@gruposelpe.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
