### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Back end C# na iBlue Consulting

### ISSUE THREAD

**Issue by cahfigueiredo** [backend-br/vagas#1370]
Estamos contratando Desenvolvedor Backend no Rio de Janeiro!

Requisitos:

Experiência com desenvolvimento em C#

Salário + benefícios (plano de saúde, plano odontológico, vale transporte, vale refeição e totalpass)

Interessados enviar CV atualizado para rhrio@iblueconsulting.com.br

**Comment by MaikonTT** [comment]
Seria somente pra pessoas do RJ?
Qual o nível? Sou programador Junior em C#
