### ISSUE TITLE
[DEV BACK-END] [SP] [ PRESENCIAL] [CLT]

### ISSUE THREAD

**Issue by fredmelo1** [backend-br/vagas#1373]
[VAGA] Nosso desafio é grande, nosso crescimento é acelerado e buscamos os melhores profissionais para essa missão. Para fazer parte da melhor Edtech do país, é preciso estar aberto a oportunidades, ter olhar analítico, facilidade para resolução de problemas e muita vontade de crescer e fazer acontecer.

**Desenvolvedor(a) Back-End Pleno - São Paulo/Presencial (CLT)**

- NodeJs (JavaScript)
- Conteinerização
- Serviços Clouds
- Bancos de Dados

Inscreva-se >>http://bit.ly/32DcN14

**Comment by luicesar** [comment]
Aceitam candidatos fora do estado de SP ?

**Comment by fredmelo1** [comment]
Aceitamos sim!

**Comment by fredmelo1** [comment]
> Aceitam candidatos fora do estado de SP ?

Aceitamos sim! A vaga é presencial, porém a empresa está disposta a auxiliar na mudança

**Comment by luicesar** [comment]
Estou preenchendo o formulário.
Obrigado.
