### ISSUE TITLE
[SÃO LEOPOLDO - RS] Fullstack Developer na À Pampa

### ISSUE THREAD

**Issue by lsfrancisco** [backend-br/vagas#1385]
### A empresa
À Pampa é uma startup incubada na Unitec, no Tecnosinos, em São Leopoldo/RS. Nosso produto é uma rede social destinada a todas as vertentes da cultura gaúcha. Nosso objetivo, a curto prazo, é oferecer um espaço de compartilhamento de conhecimento sobre a tradição gaúcha e a lida no campo. 

### A vaga
Tu atuará no time de **Produto** da À Pampa, sendo responsável pela implementação de novas funcionalidades e manutenção das existentes. A oportunidade é de trabalho alocado, com a possibilidade de home office algumas vezes por semana.
Buscamos alguém que esteja sempre buscando **aprender** e seja **comprometimento com prazos**. A **curiosidade** constante (aquela vontade de sempre ir atrás dos porquês) é essencial. Somos uma equipe jovem, sempre promovendo a troca de conhecimento entre times para agregar valor ao trabalho de todos e crescermos juntos. 😃

### Responsabilidades:
- Escrever código limpo e legível em Javascript (Node.js), utilizando as melhores práticas;
- Resolver defeitos e problemas em nosso produto e zelar pela qualidade;
- Realizar a integração do código.

### Requisitos obrigatórios:
- Longa vivência em desenvolvimento de aplicações web;
- Já ter desenvolvido ao menos um PWA;
- Minimo de 2 anos de experiência em Node.js;
- Afinidade com AWS;
- Bancos de dados MySQL e MongoDB;
- Proficiência em Git;
- HTML5/CSS3.

### Requisitos desejáveis:
- Graduação completa ou em fase de conclusão em Ciências da Computação ou áreas afins;
- Experiência com Vue.js e Nuxt.js;
- Experiência com Typescript;
- Conhecimento sobre testes unitários.

### Diferenciais:
- Já ter trabalhado com métodos ágeis (especialmente Scrum);
- Já ter trabalhado em startup.

### Benefícios:
À combinar.

### Como se candidatar:
Envie um e-mail para contato@apampa.com.br com o assunto "Vaga Node.js"

**Comment by juwviegas** [comment]
Continuamos na busca!

**Comment by JonatanPotrikus** [comment]
Caso tivesse a opção de trabalhar remoto, ou alguns JOBS frella, teria muito interesse. Sou desenvolvedor Full Stack. 

Segue meu linkedin: https://www.linkedin.com/in/jonatan-potrikus/

**Comment by lsfrancisco** [comment]
> Caso tivesse a opção de trabalhar remoto, ou alguns JOBS frella, teria muito interesse. Sou desenvolvedor Full Stack.
> 
> Segue meu linkedin: https://www.linkedin.com/in/jonatan-potrikus/

Oi, Jonatan!

Agradecemos o interesse, mas no momento precisamos de alguém presencial mesmo.

Grato!
