### ISSUE TITLE
BRQ São Paulo busca Programador Fullstack (Angular/Node)

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#139]
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Programador Fullstack  (Angular/Node)

Grande banco localizado na Faria Lima busca profissional com experiência nas seguintes 
tecnologias:CSS,  HTML, Angular.js, SASS, GULP, npm e gerenciamento de dependências Node.js 
LinuxIntegração e Delivery Contínuos, Jenkins ou ferramentas similares Scrum (desejável)
Contratação CLT, salário a combinar mais benefícios como VR, VA, Assistência médica, odontológica, 
seguro de vida, entre outros.
Início imediato e prazo indeterminado.
Horário comercial.
Local: Faria Lima- próximo a Juscelino Kubitschek (SP)- vaga presencial.

Podem enviar o cv para Renata (ryokota@brq.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
