### ISSUE TITLE
[SÃO PAULO - SP]  GuiaBolso - Desenvolvedor Back End Pleno/Sênior

### ISSUE THREAD

**Issue by fredmelo1** [backend-br/vagas#1395]
A vaga em questão é para **Dev. BackEnd**, tanto **Pleno**, quanto **Sênior**! Falando um pouco sobre o que fazer, os devs ingressarão no **Guiabolso** serão alocados nos squads do time que recebe a denominação de CNP (crédito novos produtos) – que estão relacionados a produtos de crédito/empréstimo. O movimento atual é de inchar os squads em termos de equipe e depois quebrá-los conforme o panorama encontrado – e o principal foco do segundo semestre será aumentar a originação de empréstimo.

A tecnologia está sendo construída utilizando Java e Kotlin, mas principalmente utilizando microserviços – no entanto, sabemos que bons devs são feitos muito mais do que de mera sintaxe. Por isso, **_não estamos realmente presos a qual stack você usa_** – e sim se você emprega/ama/usa conceitos e práticas como Clean Architecture, Clean Code, Design Patterns e S.O.L.I.D.

**O link para inscrição da vaga é esse aqui - http://bit.ly/2ypyhjK**

**Comment by fredmelo1** [comment]
O Guiabolso é uma FinTech nasceu em 2012 pra ajudar os brasileiros a fazerem escolhas “dinheirísticas” mais espertas e, aos poucos, fortalecer uma comunidade que, unida, consegue jogar melhor esse jogo, forçando o sistema financeiro a melhorar suas práticas.

5,3 milhões de usuários (e contando):  só por meio de tecnologia robusta, escalável, segura e bem concebida é possível sustentar da melhor maneira essa demanda e este crescimento. Assim, quando se fala em tecnologia, o nosso desafio é diário, pois é por meio dela que vamos simplificar a relação do Brasileiro com o seu dinheiro.

Para isso, os Devs Back End de nossos squads, imersos em cultura ágil e que se responsabiliza de ponta a ponta pela engenharia de software, tem a missão de criar e manter microserviços, propor arquiteturas, abordagens e práticas para resolver problemas e entregar novas funcionalidades.

**Comment by fredmelo1** [comment]
![Slide4](https://user-images.githubusercontent.com/53058474/62077966-d04ec980-b221-11e9-9e50-7a8f5929f6e6.PNG)

**Comment by izaguerreiro** [comment]
Qual a stack que vocês usam?

**Comment by fredmelo1** [comment]
> Qual a stack que vocês usam?

Olá, Isa! Sobre a stack, a tecnologia a ser construída utiliza Java e Kotlin, mas principalmente utilizando microserviços – no entanto, não estamos realmente presos a qual stack você usa – e sim se você emprega/ama/usa conceitos e práticas como Clean Architecture, Clean Code, Design Patterns e S.O.L.I.D.
