### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor FullStack na ONAWA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1399]
### Sobre a empresa: Onawa

Propomos um novo jeito de ser, interagir e vender: Conectamos marcas e consumidores por meio de uma poderosa ferramenta mobile de vendas por relacionamento e estratégia customizada. Perfeito para potencializar as vendas de e-commerces, marketplaces, franquias, indústrias, prestadores de serviços e lojistas em geral.

### Descrição: O que você irá fazer

Ser referência técnica;
Ajudar a idealizar novos projetos;
Atuar no desenvolvimento fullstack com foco no back end.

### Você vai amar trabalhar aqui se estiver em busca de:

Ambiente sensacional;
Café o tempo todo #welovecoffee
Zero hierarquia, estamos caminhando para uma holocracia;
Cultura animal!
Gostar de trabalhar em equipe;
Ambiente de muito crescimento. Estamos crescendo 114% ao ano ;)

### Requisitos obrigatórios:

PHP;
Laravel;
JavaScript;
React;
Metodologias Ágeis.

### Vamos ficar muito felizes se você conhecer:

React Native.

### Informações complementares:

Contratação PJ;
Vaga presencial.

### Candidatar: http://bit.ly/onawa1_fullstack

**Comment by marcossouzadotdev** [comment]
Alguma chance de trocar PHP e Laravel por Python + Django?

**Comment by megandavulpi** [comment]
> Alguma chance de trocar PHP e Laravel por Python + Django?

Olá, @marcosroot ! Infelizmente esses requisitos são realmente obrigatório para o que a vaga exige =/

**Comment by karinegusmao** [comment]
Boa noite, não consigo me candidatar no link acima, apresenta erro 500 de servidor ao conectar com o Linkedin :(
