### ISSUE TITLE
[São Paulo] Backend Developer - Java ou Node na IBM

### ISSUE THREAD

**Issue by guto-gomes** [backend-br/vagas#14]
## Descrição da vaga

Projeto tempo indeterminado

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Muitossssss

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Backend

**Desejáveis:**
- Java ou Node

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para augusto.gomes@br.ibm.com seu CV anexado - enviar no assunto: Vaga Backend Java ou Node

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
