### ISSUE TITLE
BRQ São Paulo busca Programador NodeJS (Pleno ou Sênior)

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#140]
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Programador Node JS (Pleno ou Sênior)
Grande banco localizado no Itaim Bibi busca profissional com experiência em Node.js; Linux;
- Habilidade de implementar refactoring em códigos legados, deixando-os testáveis e mantendo seu funcionamento original;
- Conhecimento em conceitos de design de APIs;
- Experiência com Integração e Delivery Contínuos, Jenkins ou ferramentas similares;
- Experiência no desenvolvimento de testes unitários;
- Experiência com Scrum (desejável);
- Experiência com Tecnologias AWS;
Para início imediato e prazo indeterminado;
Contratação CLT, salário a combinar mais benefícios;
Horário comercial;
Local: Itaim Bibi (Zona Sul-SP). Vaga presencial no cliente.

Cvs para Renata (ryokota@brq.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
