### ISSUE TITLE
[Remoto] Full Stack Developer na bxblue 

### ISSUE THREAD

**Issue by nuk** [backend-br/vagas#1401]
## Descrição da vaga

Essa é uma vaga para integrar o time de desenvolvimento do produto na bxblue.com.br . É uma vaga remota, sem pre-requisitos ou preconceitos. O que buscamos são pessoas com pontos de vista diferentes, aptas a desenvolver soluções web e dispostas a resolver problemas em equipe. Interessados basta entrar em http://bit.ly/bxdev2019 e deixar seus dados.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Saber se comunicar em Inglês e Português
- Se sentir a vontade no desenvolvimento, manutenção e deploy de aplicações web
- Ter disponibilidade para trabalhar em período integral

**Não Precisa:**
- Morar perto da gente (somos remotos)
- Fazer parte de qualquer grupo (seja por idade, genética, geografia, escolha pessoal ou acaso do destino)
- Ser fluente na nossa Stack de Desenvolvimento

## Nossa empresa

A bxblue é uma fintech com a missão de ajudar as pessoas a terem acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Dentre eles a Y Combinator (Aceleradora responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch). Também tivemos a honra de sermos selecionados pelo Banco do Brasil para co-criarmos juntos a primeira API de Empréstimo do Brasil. Hoje estamos na lista das 100 Startups para ficar de olho em 2019.

## Como se candidatar

Interessados basta entrar em http://bit.ly/bxdev2019 e deixar seus dados.

**Comment by rogerapdev** [comment]
Qual a Stack de vocês?

**Comment by nuk** [comment]
Temos muita coisa, mas o core é RoR, React, Mongo e Heroku.

**Comment by halkliff** [comment]
Enviei @nuk! Estarei aguardando ansiosamente um feedback 😆
