### ISSUE TITLE
[São Paulo] Analista Desenvolvedor C# Pleno / Sênior [Air Liquide]

### ISSUE THREAD

**Issue by viniciuscmatheus** [backend-br/vagas#1405]
### Analista Desenvolvedor C# Pleno / Sênior

Estamos à procura de um analista desenvolvedor pleno / sênior para atuar em nosso departamento de Transformação Digital.

**Sobre o Trabalho**
Atuar desde o levantamento das demandas com nossos colaboradores internos, passando pela arquitetura e desenvolvimento das aplicações

**Requisitos do Candidato**

Obrigatórios:

- .net Core 2.x
- RESTful APIs
- Javascript
- SQL Server
- DDD
- Redis
- Conhecimento em captação de requisitos
- Scrum / KanBan
- Git
   
**Diferenciais**

- Angular
- Bancos NoSQL
- React
- TDD
- Rabbit MQ

**O que oferecemos:**

- Horário flexível
- R$ 28/dia (almoço)
    
**Regime da contratação**
- PJ (Horas abertas)
- Valor: A combinar

Enviar CV com pretensão salarial valor/hora para o e-mail vinicius.matheus-sc@airliquide.com

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?
