### ISSUE TITLE
[Remoto] Back-End Developer na AlphaSights 

### ISSUE THREAD

**Issue by jcfigueiredo** [backend-br/vagas#1407]
Olá,

Estamos em busca de pessoas que tenham interesse em trabalhar (remotamente) em desevolvimento back-end na [AlphaSights](https://www.alphasights.com)

**Local**
Remoto - New York, London

**Benefícios**
- Salários acima de **$20,000.00**
- Visitas aos nossos escritórios de NYC/London 4 vezes ao ano

**Diferenciais**
- Nada de trabalho fora de hora!
- Equipamento top de linha fornecido pela empresa
- [Cultura super legal](https://www.youtube.com/watch?v=QcSieDMulhM) e já adaptada para trabalho remoto com o Brasil

**Requisitos Obrigatórios**
- 6+ anos desenvolvendo Software
- Ser especialista em ao menos uma linguagem de programação
- Inglês técnico e conversacional

**Desejáveis**
- conhecimento de Java/Kotlin
- conhecimentos de Ruby

**Diferenciais**
- projetos opensource
- Agile, scrum, ou similar
- Pair Programming
- TDD, Pair Programming, XP (extreme programming), DDD
- conhecimentos desenvolvimento front-end

**Contratação**
PJ

**Como se candidatar**
Preencha o formulário aqui ([https://grnh.se/c037a82e1](https://grnh.se/c037a82e1)) e nosso time de recrutamento entrará em contato!

Temos várias vagas em aberto e **vagas especiais para Times**! Chame os amigos que queira trabalhar junto - front-end ou back-end também! 

**Labels**
- PJ
- Pleno
- Remoto
- Sênior

**Comment by jcfigueiredo** [comment]
Para mais visibilidade, o salário é de mais de R$20.000,00 ao mês.

**Comment by alessandroprudencio** [comment]
Ahhh eu soubesse conversar em inglês....

**Comment by rendmp** [comment]
Alguma possibilidade de previsão para estagiários/jr?

**Comment by THAYLLER** [comment]
eu tenho 5 anos e pouco de experiencia, sei java, e aprendendo kotlin, tenho ingles tecnico e ja mandei curriculo para vcs, sera que não rola uma converssa, penso que eu teria muito a agregar como colaborador de sua empresa

**Comment by THAYLLER** [comment]
e o link da vaga está com problema ao acessar aparece Sorry, but we can't find that page.

**Comment by onhernandes** [comment]
@jcfigueiredo o link está quebrado. Estou fechando a vaga.
