### ISSUE TITLE
BRQ São Paulo- Programador Java (Pleno ou Sênior)

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#141]
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Programador Java (Pleno ou Sênior)
Estamos em busca de profissionais com experiência em programação Java para grande Banco. Tecnologias: Java, EJB, JPA, Springboot, AWS, Git. 
Contratação CLT, salário a combinar mais benefícios como VR, VA, plano médico e odonto, seguro de vida, entre outros. 
Horário comercial. 
Local: Itaim Bibi- São Paulo. 

Cvs para Renata (ryokota@brq.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
