### ISSUE TITLE
[São Paulo] Desenvolvedor React Native pleno @ Hupper

### ISSUE THREAD

**Issue by raffaelmarfara** [backend-br/vagas#1410]
## Descrição da vaga

Estamos buscando um desenvolvedor pleno ou sênior para fazer parte do time de tecnologia da Hupper, trabalhando com o desenvolvimento e gestão de uma aplicação híbrida, desenvolvida com React Native e Firebase. Buscamos alguém com vontade de trabalhar, aprender, liderar e crescer junto com a empresa.

## Local

Vila Olimpia - São Paulo - SP

## Benefícios / Diferenciais

- Horário flexível
- ☕ Free coffe
- Stock-option anual

## Requisitos

- React Native
- Firebase
- Typescript

## Contratação

PJ a combinar

## Nossa empresa

A Hupper foi fundada com o objetivo de melhorar a saúde e bem-estar dos funcionários de grandes empresas, com uma plataforma de saúde gamificada que incentiva e premia a adoção de hábitos saudáveis dos colaboradores.

## Como se candidatar

Para se candidatar, enviar um e-mail com CV ou Linkedin e pretensão salarial para vagas@hupper.life com o assunto “GITHUB - DEVELOPER HUPPER"

## Labels

- Alocado
- PJ
- Pleno

**Comment by davialmeida** [comment]
Boa noite, teriam vaga para Dev Junior ou Freela?

**Comment by raffaelmarfara** [comment]
Boa noite Davi,

Qual sua experiência com firebase e react?

Abraços!

Em ter, 30 de jul de 2019 23:09, davialmeida <notifications@github.com>
escreveu:

**Comment by davialmeida** [comment]
@raffaelmarfara 
Com Firebase 4 meses, com React 6 meses, inclusive estou trabalhando em um freela de um app usando React.

**Comment by raffaelmarfara** [comment]
Legal!!

Só mais duas perguntas:

1) qual sua pretensão salarial?

2) está disposto a vir para SP?

Em qua, 31 de jul de 2019 12:09, davialmeida <notifications@github.com>
escreveu:
