### ISSUE TITLE
[São Paulo] Desenvolvedor de automação no Banco Safra [FECHADO]

### ISSUE THREAD

**Issue by AndreCecchi-Safra** [backend-br/vagas#1419]
### Vaga Desenvolvedor
**Empresa:** Banco Safra S/A
**Cargo:** Analista (CLT) Júnior/Pleno
**Local:** R. Bela Cintra 560, Consolação - São Paulo, São Paulo

### Atividades:

- Desenvolvimento de software de RPA (por ora em .NET, Selenium)
- Desenvolvimento de soluções para interface de usuário e visualização de dados.
- Interface com diversas áreas do banco, a fim de entender o funcionamento do negócio e propor soluções de RPA.
- Desenvolvimento de projetos segundo metodologia ágil.
- Pesquisa de tecnologias novas para RPA (UIPath, Cypress).

### Pré-requisitos:

- Experiência com linguagens de POO (C#, Java, Python, etc).
- Experiência com automação de processos (desejável)
- Desenvolvimento .NET (desejável)
- Conhecimento de front-end (desejável)
- Conhecimento de ferramentas de RPA (desejável)

### Benefícios:
A combinar.

### Início:
Setembro/2019

Enviar currículo para: **andre.cecchi@safra.com.br**

**Comment by olucasqueiroz** [comment]
Somente programadores de São Paulo?

**Comment by AndreCecchi-Safra** [comment]
Boa tarde, Lucas.

Sim. Não podemos montar equipes que trabalhem remotamente. Teria que 
trabalhar aqui no prédio do Safra.

Obrigado,
ANDRE GOMES CECCHI 
INF CONSIGNADO/VEICULOS
 
Av. Paulista, 2150 | São Paulo | CEP: 01310-300
andre.cecchi@safra.com.br

**Comment by RafaelFigueiredo** [comment]
Vocês tem interesse em contratar PJ? Faço parte de uma equipe especializada em RPA com mais de uma centena de processos em produção, o pessoal tem disponibilidade de ir a São Paulo e realizar o trabalho no próprio prédio da Safra, bem como dar manutenção ou iniciar projetos de pesquisa locais. Posso pedir para entrarem em contato por e-mail e apresentamos uma proposta?

**Comment by AndreCecchi-Safra** [comment]
Boa tarde, Rafael.

No momento estamos contratando apenas CLT para montarmos uma equipe 
própria. Contudo, pode me enviar a proposta que vou analisar !

Obrigado,

 
 
ANDRE GOMES CECCHI 
INF CONSIGNADO/VEICULOS
 
Av. Paulista, 2150 | São Paulo | CEP: 01310-300
andre.cecchi@safra.com.br




De:     Rafael Figueiredo <notifications@github.com>
Para:   backend-br/vagas <vagas@noreply.github.com>, 
Cc:     AndreCecchi-Safra <andre.cecchi@safra.com.br>, Author 
<author@noreply.github.com>
Data:   02/08/2019 21:25
Assunto:        Re: [backend-br/vagas] [São Paulo] Desenvolvedor de 
automação no Banco Safra (#1419)



Vocês tem interesse em contratar PJ? Faço parte de uma equipe 
especializada em RPA com mais de uma centena de processos em produção, o 
pessoal tem disponibilidade de ir a São Paulo e realizar o trabalho no 
próprio prédio da Safra, bem como dar manutenção ou iniciar projetos de 
pesquisas locais. Posso pedir para entrarem em contato por e-mail e 
apresentamos uma proposta?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Esta mensagem e seus anexos são destinados exclusivamente ao(s) seu(s) 
destinatário(s) e, podem conter informações confidenciais e/ou legalmente 
privilegiadas. A divulgação, distribuição, reprodução ou qualquer forma de 
uso não autorizado de tais informações são proibidas e podem ser ilegais, 
sujeitando-se o responsável às penalidades cabíveis. O remetente utiliza o 
correio eletrônico no exercício do seu trabalho ou em razão dele, eximindo 
as empresas integrantes do Grupo de qualquer responsabilidade por 
utilização indevida. Caso não seja o destinatário desta mensagem, 
solicitamos a gentileza de notificar o remetente e eliminá-la 
imediatamente.
