### ISSUE TITLE
[São Paulo] Software Engineer at [2Mundos)

### ISSUE THREAD

**Issue by bmanfredini** [backend-br/vagas#142]
Please send your CV to jobs@2mundos.net

This developer will be working with PHP and MySQL. The professional will work with the API team, creating new API endpoints and providing maintenance to the existing ones.

Day to day tasks also include creating database schemas, procedures, optimization, importing large amounts of data and data migration.

Essential job functions:

- Good communications skills in spoken english

- Ability to follow code standards is a must

- Php5 (raw php with no frameworks)

- Oop (classical oop, namespaces)

- Experience in json based apis

- Experience in object-relational mapping (orm)

- Database modelling (layout, indexes, foreign keys)

- Ability to write mysql stored procedures and functions

- Experience writing sql intensive scripts for stats/data warehousing purposes

- Proficiency in using git from the command line

- Ability to comment code as you go

Additional:

- Real-time infrastructure experience (meteor, socket.io, node.js)

- Front-end development using angularjs

Benefits:

- Relaxed environment and a dress down culture

- Flat organizational structure

- Next star wars launch will be day off

Labels:

-PJ
-Senior

Please send your CV to jobs@2mundos.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
