### ISSUE TITLE
[São Paulo] Back-End Developer na [T4W Tecnologia]

### ISSUE THREAD

**Issue by GeracaoTalento** [backend-br/vagas#1423]
Somos uma Consultoria de RH e estamos assessorando o nosso cliente nesta oportunidade.

Back-End Developer na T4W

Convidamos você à trabalhar em uma Empresa Global de Tecnologia com foco no Desenvolvimento de Sistemas para o mercado de Turismo.

Você será responsável pelo desenvolvimento de novas funcionalidades e manutenção da plataforma dos clientes nacionais e internacionais.

Requisitos necessários: 

- .NET.
- VB.Net e C#.
- Entity Framework, WCF, WebForms.
- Arquitetura cliente/servidor.
- Orientação à objetos.
- Javascript.
- XML.
- JSON.
- WebApis, SOAP e REST.
- MySQL. 

Metodologias: 

- Design Patterns, MVVM, MVC, OO.
- SCRUM.
- TFS.

Desejável:

- Asp.net Core 2.0.
- IIS e WebDeploy.
- Serviços do Windows.

Diferencial: 

- Ter trabalhado MongoDB.
- Conhecimento em UX e Usabilidade.
- Ter trabalhado no mercado de turismo.

Desejável : Formação Superior em Ciências da Computação, Sistemas da Informação ou área relacionada.

Contratação CLT + benefícios (VT, VR R$ 715,00 por mês, VA R$ 400,00 por mês, Plano Médico da Allianz). 

Local: Região da Vila Olímpia - SP (próximo à estação de trem).

Enviar o CV e pretensão salarial para o Marcelo no e-mail (marcelo@geracaotalento.com.br).

**Comment by luicesar** [comment]
Aceitam contratação do tipo PJ ?

**Comment by GeracaoTalento** [comment]
Olá, boa tarde! A vaga foi encerrada!
