### ISSUE TITLE
[Remoto] Desenvolvedor(a) TypeScript/NodeJS na Vizir (Pleno/Sênior)

### ISSUE THREAD

**Issue by FabricioFFC** [backend-br/vagas#1430]
## Descrição da vaga

Estamos com oportunidades para trabalhar com Node.js e TypeScript na Vizir.

Para conhecer mais sobre a vaga e um pouco da [Vizir](http://vizir.com.br/2017/04/26634697957-2/)

Quem tiver interesse, só preencher o seguinte form: https://recruiterflow.com/vizir/jobs/2

## Local

100% remoto, podendo também ser presencial (ficamos na cidade de São Paulo, no Edifício Itália)

## Benefícios

- Ticket refeição: R$ 31,50 por dia (R$ 661,50 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou aonde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

## Requisitos

- Conhecimento de JavaScript, boa lógica e orientação a objetos
- Estar a fim de aprender
- Comprometido em entregar projetos com qualidade

**Obrigatórios:**
- Curtir programar
- Ter no mínimo 1 ano de experiência com Node.js

**Desejáveis:**

- Experiência com práticas ágeis, AWS, Microservice e TypeScript
- Experiência anterior trabalhando remoto

## Contratação

CLT

## Como se candidatar

Preencha o seguinte formulário: https://recruiterflow.com/vizir/jobs/2

## Labels

- Remoto
- Presencial
- CLT
- Pleno
- Sênior

**Comment by evertonnppp** [comment]
eu estou interessador na vaga 21 992433897

**Comment by JonatanPotrikus** [comment]
Olá, @FabricioFFC ja respondi o formulario, mas não tive nenhum feedback via email, para saber se o formulario realmente foi submetido corretamente.

**Comment by halkliff** [comment]
@FabricioFFC Também estou no aguardo de um feedback

**Comment by THAYLLER** [comment]
E quanto ao salário da vaga?

**Comment by FabricioFFC** [comment]
> E quanto ao salário da vaga?

@THAYLLER, de acordo com o nível de senioridade da pessoa. Inclusive uma das perguntas do questionário é a pretensão, então é mais questão de negociação e vemos se está na realidade nossa para a vaga

**Comment by iagovholanda** [comment]
Fabrício e para quem já fez o processo ? Quando vai ser o retorno das respostas.

**Comment by FabricioFFC** [comment]
@iagovholanda tivemos um alto volume de candidatos, devemos conseguir dar o retorno em até duas semanas. Desculpa pela demora.
