### ISSUE TITLE
[Remoto] Backend Dev Golang [Impulso]

### ISSUE THREAD

**Issue by ThaysdaCosta** [backend-br/vagas#1431]
Buscamos Backend Devs que possuam boa experiência prática com GoLang, e que tenham algum conhecimento de Angular.

Atualmente, a stack é composta pela linguagem GoLang, banco de dados MySQL, front-end feito em Angular 1.2 (React no futuro), Bootstrap e a infra está no Google Cloud.

Nível: Pleno
Modelo: Remoto
Carga horária: Full Time, em horário comercial.
Início: Imediato
Remuneração: até R$70/h (~R$11.200/mês). 💰 A própria pessoa define quanto julga ser adequado receber.

Sobre nós: Somos uma comunidade com milhares de profissionais de TI que integra diversas iniciativas, produtos e serviços para a colaboração mútua e desenvolvimento pessoal e profissional de seus integrantes. Já somos 12.000 pessoas!

Tem interesse e disponibilidade imediata? Acesse o link https://impulser.me/thays-impulso, entre para a comunidade e me chame diretamente por lá (logo após registrar-se, você receberá por email as credenciais para acessar o nosso chat). Lá na comunidade, eu sou `@thays`. É só chamar!

Aguardo vocês!

**Comment by olucasqueiroz** [comment]
Boa noite, entrei em contato... mas ninguém respondeu.

Já encontraram alguém para a vaga?

**Comment by jonathanguilhermesouza** [comment]
Aceita pessoas sem experiência com GoLang?
