### ISSUE TITLE
[Portugal] .NET Developer

### ISSUE THREAD

**Issue by festaca** [backend-br/vagas#1432]
Descrição da vaga: Projectos em vários sectores de actividade, usando diversas tecnologias Microsoft.

Local
Portugal: Lisboa ou Porto

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Viagem de avião e alojamento inicial
• Outras

Diferenciais
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

Requisitos Obrigatórios:
• Experiência mínima de 4 anos em funções de desenvolvimento de software
• Experiência nas seguintes tecnologias: .NET, C#, VB.NET, MVC, Entity, REST, SOAP
• Nível de Inglês Avançado

Diferenciais:
• Conhecimentos em frameworks React ou Angular
• Experiência internacional

Contratação:
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

A nossa empresa:
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projectos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Por favor envie para fpiedade@aubay.com com seu CV em inglês anexado colocando no assunto 
Candidato_Internacional.NET

**Comment by LeoFC97** [comment]
Tem vaga pra estágio/junior? Tenho dupla cidadania portuguesa e gostaria de fazer intercambio de trabalho.

**Comment by festaca** [comment]
Olá Leonardo, infelizmente as vagas são apenas para pleno/sénior.
