### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor FullStack NodeJS / TypeScript (Seventh)

### ISSUE THREAD

**Issue by cunhaw** [backend-br/vagas#1436]
## Descrição da vaga

Atuação como Full Stack Developer no ramo de softwares para monitoramento de câmeras;

## Local

Escritório, Florianópolis

## Benefícios

- Plano de saúde 100% pago pela empresa
- Vale refeição/alimentação
- Vale transporte/Estacionamento
- Curso de idiomas
- Bolsa de estudos

#### Diferenciais

- Horário flexível (banco de horas)

## Requisitos

**Obrigatórios:**
- Full Stack Node.js/Typescript, Express, Angular 2/4/5 ou superior;
- Modelagem e programação de banco de dados NoSQL com MongoDB;
- Conhecer Padrões de Projetos utilizando Javascript/Typescript;
- Domínio de Html/CSS/Javascript

**Desejáveis:**
- Experiência com Docker, serviços da AWS e Heroku;
- Experiência com testes automatizados, testes de carga, técnicas de clean code.

## Contratação

CLT / 40 horas semanais

## Como se candidatar

Por favor envie um email para rh@seventh.com.br com seu CV anexado - enviar no assunto: Desenvolvedor FullStack NodeJS 

## Labels

- Alocado
- CLT
- Sênior
- NodeJS
- Typescript

**Comment by seventhltda** [comment]
A vaga continua aberta.

**Comment by danielsidev** [comment]
É possível trabalhar remotamente? Sou do RJ.
https://www.linkedin.com/in/danielsidev/

**Comment by seventhltda** [comment]
@danielsidev Oi Daniel, durante essa fase de pandemia sim.  Em 2021 voltamos ao presencial.

**Comment by danielsidev** [comment]
@seventhltda Vocês tem política de trabalho remoto ou estariam dispostos a manter um funcionário remoto após a pandemia? =)

**Comment by seventhltda** [comment]
@danielsidev Após a pandemia: Apenas presencial. Mas é em Floripa! =D
Vamos conversar?

**Comment by danielsidev** [comment]
@seventhltda Vamos.
