### ISSUE TITLE
[Curitiba, PR] Desenvolvedor PHP Senior

### ISSUE THREAD

**Issue by tifabio** [backend-br/vagas#1437]
**Entregas esperadas**
Elevar o padrão da área de desenvolvimento, com melhoria na qualidade do código e disseminar no time a cultura ágil.

**Necessário saber** 
PHP, JIRA, PYTHON, Metodologia Ágil.

R$ 6.000 clt + benefícios 

Enviar cv no recrutamento@grgit.com.br

**Comment by hexetia** [comment]
Vale remoto?

**Comment by tifabio** [comment]
> Vale remoto?

Maiores informações recrutamento@grgit.com.br
