### ISSUE TITLE
[Porto Alegre] Desenvolvedor C# .net core no [Grupo WL]

### ISSUE THREAD

**Issue by GrupoWL** [backend-br/vagas#1438]
### O Grupo WL está em busca de desenvolvedores juniores e plenos de C# .net core para integrar nosso time!

**Pré requisitos**

- Experiência com angular, C# e .net core.

**Atribuições**

- Desenvolver novas aplicações relacionadas às demandas do projeto.

Tem alguma dúvida sobre a oportunidade? Me manda inbox [https://www.linkedin.com/in/j%C3%BAlia-lantmann-ab37ab140/](url) 

![67826075_642415772927456_4359183929022873600_n](https://user-images.githubusercontent.com/53013854/62789948-6b586680-baa0-11e9-8557-d079a4c3eb3e.jpg)

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?
