### ISSUE TITLE
[Belo Horizonte] Back-End Developer

### ISSUE THREAD

**Issue by andre0799** [backend-br/vagas#144]
Empresa: Mercatório

A Mercatório é a (r)evolução do mercado de Direitos Creditórios e Precatórios! Atuamos baseados em 3 pilares:
- Informação: Facilitamos a consulta de informações sobre o processo judicial e as cessões de crédito realizadas.
- Simplificação: Através de algoritmos criados pela nossa equipe, simplificamos o processo de análise de documentos e de compra do Precatório.
- Conexão: Conectamos diretamente credores de Precatório e compradores. Além de disponibilizar uma plataforma personalizada para gestão de processos.

Bairro: Pampulha
Descrição:
Mercatório (mercatorio.com.br) is a upcoming Fintech born and raised in the San Pedro Valley. Our product is conquering more clients each day and we need your passion for tech to take it a step further. We are looking for a back-end developer with strong knowledge of Ruby (RoR), API's and Infrastructure. You'll be developing a product that aims to revolutionize a hole market!

Want to know about our stack?

- Back End: Ruby! We love GIT and TDD! <3
- Front End: Angular 4;

What will you do?

- Be concerned abou our clients needs and create productive conversations with the legal team about the product; 
- Take the lead on your tasks and do everything in your power to delivery it;
- Help us work a big load of features on the API and help us escalate our infrastructure;
- Learn and share as much as you can; 

What you will get?

 - FAIR compensation and will get to choose between a PJ Contract or CLT with VT + VR;

- FULLY flexible work hours;

- Work with a product that has complex and challenging  architecture. As the product grows so will you;

- Work with us to implement SCRUM and create a truly Agile environment;

- We take learning very serious, so... Udemy AND Allura account with ANY course available at company expense;

- Opportunity to grow fast with Marcatório. We're working to implement a vesting option strategy for our first employees in the near future;

- Generation Y friendly environment (Mistake are treated as learning opportunities. We value learning and knowledge sharing, experimentation atitude and your individuality. Informal dress code);

- BYOC (Bring your own computer!)

- Opportunity to shape the company's culture.

Requisitos:
* Mercatório is a pro diversity company, so if you identify yourself as as woman, black or LGBT person feel extremely encouraged to apply for the job. Currently 1/3 of our team if LGBT.

What you will need?

- Ownership;
- Degree (2y-5y courses) at the I.T field or proven equivalent experience;
- Minimum of 2 years of proven experience with Ruby, API and Infrastructure; 
- Knowledge in Angular 4 is a plus. TDD and Scrum are pure love therefore a plus;
- Domain over the Crawler technologies is a HUGE plus; 
- Experience and love for the Fintech industry is also a HUGE plus;
- Intermediary English is necessary for your learning process to go more smoothly;
- Experience getting your way around the documentation and the tasks without a lot of guidance; 
- Know how to bare a little bit of caos (It is our moment it will pass but you WILL need some resilience for now)

If you think you have what it takes, join our way of work!

Tipo de Contrato: CLT (Efetivo)
Salário: A combinar
Benefícios:
- Check out the description. :)

**Para se candidatar:** [https://www.recrutasimples.com.br/vaga/-L8PQmOWPDPc9kStDLdZ?referrer=githutbackend](https://www.recrutasimples.com.br/vaga/-L8PQmOWPDPc9kStDLdZ?referrer=githutbackend)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
