### ISSUE TITLE
[Rio de Janeiro] Back-End Developer [Fleekus LLC]

### ISSUE THREAD

**Issue by rm0r43s** [backend-br/vagas#1443]
Fala galera,
Somos uma startup com sede em Miami e estamos com 1 vaga de back-end aberta para o time Brasil 🙂.
Trabalhar na Barra da Tijuca - RJ, 8h/dia, inicialmente por 3 meses, podendo ser efetivado.
Caso tenha interesse envie seu CV para o e-mail careers@fleekus.com.

Fleekus is looking for a Back End Developer to help with maintaining and evolving the platform. You will work closely with team members from a variety of disciplines such as writers, UX, product management, and marketing (design) to build and evolve Fleekus and other team's tech stack. We also hope you will coach and mentor team members and volunteers who contribute to the Fleekus platform.

**Key Skills**

- Experience developing within the Node.js ecosystem
- Designing, building, and using web-based REST APIs
- PHP Intermediate Knowledge
- Knowledge of relational MySQL database and NoSQL MongoDB database
- Comfortable working with Git
- Have worked with agile project management such as Scrum / Agile / Kanban or similar development methodology

**Helpful Additional Skills**

- Knowledge in micro-services architecture
- Knowledge in Docker and Kubernets
- Knowledge in Laravel
- Knowledge in integration tests with supertest, jest or other
- Knowledge in Typescript

Location
Brazil, RJ, Rio de Janeiro, Barra da Tijuca

Employment Time
Fixed term and Contract as full time job (3 months)
Monday to Friday, 9am to 6pm

Payment
PJ/MEI - TBD

**Comment by rendmp** [comment]
Olá, acabei de enviar um email com o currículo mas parece que esse email não pode ser encontrado pelo gmail 

> 550 5.1.1 The email account carrers@fleekus.com that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.

**Comment by rm0r43s** [comment]
Obrigado por me avisar. O Correto é careers@fleekus.com.
