### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack Pleno na AUTOPAPO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1444]
### Sobre a empresa: AutoPapo

O jornalista e engenheiro Boris Feldman está à frente do autopapo.com.br – portal para quem gosta de carro e também precisa do automóvel no dia a dia. Nosso objetivo é ajudar as pessoas que desejam comprar, trocar, fazer a manutenção e entender melhor o funcionamento do próprio carro. A ideia é que o internauta tenha conhecimento básico e não seja mais enganado no posto de combustível, concessionária, loja de peça e oficina. A redação do AutoPapo, composta por experientes jornalistas e engenheiros, testa e compara os principais lançamentos da indústria automobilística. Além da análise técnica, damos dicas importantes para manutenção do seu carro e publicamos reportagens com aspectos do trânsito, comportamento, além das notícias quentes do mercado.

### Descrição: O que você irá fazer

Desenvolver novas soluções e dar manutenção em sistemas;

### Requisitos Obrigatórios:

HTML/CSS
JavaScript;
PHP;
Angular;
WordPress;
Banco de dados MySQL.

### Requisitos Desejáveis:

ASP.net Core C#
PHP Codelgniter;
SQL Server;
AWS;
Redis / Memcached;
Linux;
Docker;
Práticas e ferramentas em SEO.

### Você vai amar trabalhar aqui se:

For apaixonado por carros;
Estiver em busca de um ambiente de trabalho flexível;
Queira não só codificar mas entender do negócio :)

### Informações complementares:

Contratação tipo PJ;
Não é necessário estar todos os dias no escritório, mas ter disponibilidade sempre que necessário.
Nosso escritório está no localizado no alto da Raja, bairro Estoril em BH;
É necessário um notebook próprio para o trabalho.
Estamos com algumas instabilidades na nossa plataforma. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para **paula.lanza@vulpi.com.br**

### Candidatar: http://bit.ly/autopapo_fullstack

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?
