### ISSUE TITLE
[São Paulo/Capital] Desenvolvedor Pleno na Banco Alfa de Investimento S.A.

### ISSUE THREAD

**Issue by jeehand** [backend-br/vagas#1445]
Atuará com programação C#.

Pré-requisitos: 
 Superior cursando ou completo em cursos relacionadas à Tecnologia. 
Conhecimentos em: .Net (c# e vbnet), MVC, javascript, JQuery, SQL Server.
Desejável conhecimento em negócios financeiros, angular e desenvolvimento de scripts SQL.

O que nós oferecemos: 
Salario compatível com mercado + Assistência Odontológico + Assistência Médica + Vale Transporte + Vale Alimentação + Vale Refeição + outros.

Horário: De segunda a sexta das 09:00 às 18:30. 

Local de trabalho: Próximo à Avenida Paulista (Metrô Brigadeiro)

Envie um e-mail para jessica.andrade@bancoalfa.com.br contendo seu currículo atualizado com PRETENSÃO SALARIAL, colocando no campo assunto “Analista Programador C# - Back-End.

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?
