### ISSUE TITLE
[Hortolândia] Application Developer - Back End at IBM

### ISSUE THREAD

**Issue by Kelycsf** [backend-br/vagas#145]
Mandatório: **Java avançado**
Secundário: Linux, TWS, GIT, Python
Recurso proativo, comunicativo

**Inglês: Avançado**

Local
IBM Hortolândia

Benefícios
VR/VA
Vida Link
Assistência Medica e Odontológica
Fretado
PLR
Previdêcia Privada

Contratação

Nossa empresa
A IBM é uma multinacional americana e uma das maiores em Tecnologia no mundo.

Como se candidatar
Entrar no site da IBM [https://ibm.biz/Bdi26G] e se candidatar na vaga 136723BR

Labels
CLT
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
