### ISSUE TITLE
[Remoto] Desenvolvedor Python na Instruct

### ISSUE THREAD

**Issue by vmesel** [backend-br/vagas#1456]
Estamos buscando profissional que consiga trabalhar em um time multidisciplinar, que tenha sólidos conhecimentos de programação e bons fundamentos de sistemas operacionais e redes.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

Precisamos que você conheça muito bem Python em ambiente Linux.

Caso você tenha experiência com tecnologias de automação, gerencia de configuração, o paradigma de infraestrutura como código ou containers, estes serão diferenciais.

O trabalho poderá ser realizado totalmente remoto, dentro de horário comercial e seguindo o horário de Brasília, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

## Requisitos
Conhecimentos e experiências fundamentais:
- Linguagem Python;
- Banco de dados relacional/SQL;
- Django ou outro framework web;
- Integração de aplicações via APIs REST;
- Uso de Git para versionamento de seu código;
- Vagrant;
- Testes unitários;

Se inscreva em: [https://www.pyjobs.com.br/job/611/](https://www.pyjobs.com.br/job/611/)

**Comment by mciurcio** [comment]
@vmesel pode fechar essa por favor.
