### ISSUE TITLE
[São Paulo] Junior Back-End Developer na [Testfy]

### ISSUE THREAD

**Issue by caiocutrim** [backend-br/vagas#1465]
Olá pessoal, tudo bem? nós da **Testfy** estamos em busca de um dev junior em backend. Somos uma startup na área biotecnologia, então precisamos de uma pessoa muito engajada em querer aprender com nosso time de devs. A vaga não é remota.
Conhecimentos necessários:
- Javascript
- Nodejs
- Conhecer alguma ferramenta de DEBUG (Chrome Devtools, VsCode e etc)
- Express ou similares
- Posgresql ou similares
Desejáveis:
- Disciplina
- Vontade de querer aprender novas tecnologias
Para se candidatar, por favor manda cv para caio@testfy.com.br

**Comment by rendmp** [comment]
Como faço para me candidatar e ver a cidade da vaga?

**Comment by caiocutrim** [comment]
manda cv para caio@testfy.com.br

**Comment by iagovholanda** [comment]
So presencial ?

**Comment by caiocutrim** [comment]
Sim, só presencial @iagovholanda
