### ISSUE TITLE
[REMOTO] Back-End Laravel Developer na Imagination Media

### ISSUE THREAD

**Issue by edilsoncichon** [backend-br/vagas#1466]
## Descrição da vaga

Você irá atuar como um Back-End dev. numa stack composta por uma API GraphQL e algumas coisas em REST.
Opcionalmente, se você manjar de Vue ou React vai ser interessante para projetos futuros que temos, pois pretendemos utilizar o Laravel + Blade + Vue em casos que não precisem de uma API necessariamente.

Procuramos alguém que tenha disciplina, se comunique bem: tudo é conversado e decidido em grupo, damos feedbacks com frequência, avisamos com antecedência pausas durante o trabalho, etc. Tudo isso para que o trabalho remoto flua! :)
Acreditamos que se a pessoa tiver essas qualidades e vontade de aprender, os requisitos técnicos/não técnicos são os menos importantes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Boa experiência com OOP;
- PHP;
- MySQL;
- Modelagem de Dados;
- Laravel;
- Desenvolvimento de APIs;
- Inglês para leitura/escrita;

**Desejáveis:**
- Testes automatizados;
- Saiba documentar: nós costumamos documentar muita coisa por aqui;
- JS moderno;

**Diferenciais:**
- Inglês para conversação: será um grande diferencial e lhe ajudará crescer na empresa a médio/longo prazo.

## Contratação

PJ a combinar.

## Nossa empresa

A Imagination Media é uma empresa americana que desenvolve soluções para e-commerces. Com sede na Florida, EUA, porém, a maior parte do time é distribuída em diversos países, então o trabalho é realizado totalmente remoto.
Se ficou interessado em nossa empresa, veja mais em https://www.imaginationmedia.com.

## Como se candidatar

Para mais informações ou para se candidatar, envie um email para edilson@imaginationmedia.com, com o título ¨Back-End Laravel Junior/Pleno¨. Não precisa enviar aquele currículo padrão se não quiser, pode mandar seu LinkedIn, ou até mesmo descrever no email suas qualificações.

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Júnior
- Pleno

**Comment by BrunoMoreno** [comment]
Enviado!
