### ISSUE TITLE
[Santos/SP] Programador Web PHP Pleno na TimePix

### ISSUE THREAD

**Issue by danielGalvao** [backend-br/vagas#147]
Vaga para Programador Web PHP Pleno - programação de sites com CMS e manutenção dos projetos web da empresa.

Requisitos:
- PHP 
- MySQL 
- JavaScript, jQuery 
- Trabalhar em ambiente Windows ou Linux

Desejável
- Desenvolvimento de aplicativos Mobile (iOS e/ou Android)
- Conhecer Pyro CMS e Bootstrap
- Sugerir mudanças, pensar em progresso contínuo

> Enviar CV, pretensão salarial e portfólio (se tiver) para vaga@timepix.com.br

Labels:
Pleno
CLT
Alocado

**Comment by fsrocha-dev** [comment]
Entrevista pode ser via Skype ?

**Comment by danielGalvao** [comment]
@fsrocha-dev Cara, eu acredito que sim, manda um email e confirma...

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
