### ISSUE TITLE
[FLORIPA] Back-End Developer C#.NET  [Exact Sales]

### ISSUE THREAD

**Issue by bluiza** [backend-br/vagas#1472]
## Nossa empresa

Oferecemos soluções para vendas complexas B2B, com metodologia própria e Software inovador. Estamos em constante e acelerado crescimento, buscamos pessoas que estejam na mesma pegada. 

## Descrição da Vaga

Desenvolvimento do software Spotter.
Desenvolver SaaS com boas práticas e agregar conhecimento técnico ao time.
Contribuir com a equipe para melhoria de práticas de desenvolvimento do processo.

## Benefícios

-Pacote de benefícios de R$ 877,00 (você compõe como quiser entre: vale alimentação, vale refeição, vale transporte, vale combustível, plano odontológico ou plano de saúde)
-Estacionamento gratuito
-Local para descanso (sim, você pode tirar aquele cochilo :)
-Vídeo Game, sinuca, jogos de mesa, ping-pong
-No dress code
-Happy Hours
-Dia de folga no aniversário
- Outros.. 

## Requisitos

**Obrigatórios:**
-Graduação completa ou nas fases finais em tecnologia da informação, sistemas de informação ou áreas afins.
-Mínimo de 2 anos de experiência com C#, MVC, SQL Server, Entity Framework.

**Desejáveis:**
-Experiência com React e DDD
-Familiaridade com Node.js e com Microsoft Azure.

## Como se candidatar

Clique no link e comece: https://exactsales.gupy.io/jobs/65701

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?

**Comment by bluiza** [comment]
Para essa vaga somente presencial @jonathanguilhermesouza

**Comment by jonathanguilhermesouza** [comment]
@bluiza obrigado!
