### ISSUE TITLE
FRONT END PLENO 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#148]
A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra. Para trabalhar na Radar Profissional

Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Imprescindível experiência com JavaScript, AngularJS (Grunt ou Gulp) ou React (Webpack), CSS (SASS) Bootstrap ou Semantic;
•	Será considerado como diferencial, experiência com React Native, Controle de versão de software (GIT), modelo de testes unitários Junit, Karma, Jasmine ou Phantomjs e metodologias ágeis Scrum.

Responsabilidades: 

•	Desenvolvimento e implementação de funcionalidades para sites e apps.

Contratação: CLT + Benefícios 
Local: São Paulo/SP – Zona Sul 
Interessados: Enviar CV para analista@radarprofissional.com.br com sua pretensão Salarial.
Visite nosso site: www.radarprofissional.com.br 
Visite nossa página: https://www.facebook.com/radarprofissional.com.br/

**Comment by reginaldojunior** [comment]
Olá, vagas de frontend por favor cadastrar em: https://github.com/frontendbr/vagas

@frontendbr
