### ISSUE TITLE
[São José dos Campos] Full Stack Junior/Pleno/Sênior [Sistema Pallas]

### ISSUE THREAD

**Issue by hugofialho** [backend-br/vagas#1483]
### Descrição da vaga
Desenvolvemos um sistema de ponto de venda e gestão para melhorar a vida dos pequenos e médios negócios.
Utilizamos tecnologia para transformar o varejo em uma experiencia simples, rápida e inteligente.

www.sistemapallas.com.br

### Local
São José dos Campos - Jardim Alvorada

### Atribuições:
Contribuir em decisões de arquitetura sobre novas partes do projeto;
Aderir às melhores práticas no desenvolvimento de UI e UX;
Criação de novas funcionalidades em Single Page Applications;

### Necessário:
Ter experiência em desenvolvimento web de, no mínimo, 1 ano;
Proficiência em CSS e Javascript;
Framework ReactJS;
Uso de SDKs e APIs REST;
Versionamento de Código Git;
Desenvolvimento de Código com boas práticas e bem estruturado;

### Comportamentos que valorizamos:
Autodidata;
Focado em resultados;
Proativo;
Motivado por desafios;
Gosta de sempre aprender coisas Novas;

### Contratação:
PJ a combinar.

[Para se candidatar preencha este formulário](https://forms.gle/NUCR7VNxEtDWgCnH6)

**Comment by jonathanguilhermesouza** [comment]
Tem a possibilidade de trabalho home office?

**Comment by hugofialho** [comment]
@jonathanguilhermesouza no inicio não, depois de se familiarizar com o projeto é possível ter 2 ou 3 dias remoto.

**Comment by jonathanguilhermesouza** [comment]
@hugofialho interessante, podemos conversar! Sou de São José dos Campos...

**Comment by hugofialho** [comment]
@jonathanguilhermesouza Show de bola, preenche nosso formulário por favor https://docs.google.com/forms/d/e/1FAIpQLSfkI6rZjzrx3CQNMS0l3irORsOLAspwFrwkCMy33GTHBq6fAg/viewform

**Comment by jonathanguilhermesouza** [comment]
@hugofialho fechado! Vou preencher mais tarde, trabalho atualmente na Panasonic, tenho acesso limitado aqui, rs....

**Comment by jonathanguilhermesouza** [comment]
@hugofialho  se quiser posso te responder via email, não consigo abrir formulário do google aqui :(...

**Comment by jonathanguilhermesouza** [comment]
@hugofialho  conegui responder pelo celular, não deu para falar muito, rsrs... Bom, fico no aguardo de um feedback, quando pode dar?

**Comment by hugofialho** [comment]
@jonathanguilhermesouza pretendo analisar os currículos durante duas semanas, aí consigo dar um retorno

**Comment by jonathanguilhermesouza** [comment]
@hugofialho obrigado!
