### ISSUE TITLE
[São Paulo] Back End Developer na Hash

### ISSUE THREAD

**Issue by leonardocomodini** [backend-br/vagas#1486]
### Descrição

Estamos com oportunidades abertas para dev Back End aqui na [Hash](https://hash.com.br) :)

Para entender um pouquinho o que fazemos e como trabalhos acesse [esse link](https://github.com/hashlab/hiring)

Para se candidatar se cadastre no nosso [workable](https://hashlab.workable.com/jobs/764027)

### Local

Ficamos localizados na Av. Brigadeiro Faria Lima bem pertinho do metrô mas encorajamos fortemente o trabalho remoto!

### Requisitos

- Codar é sua paixão
- Possui experiência construindo algo de que você se orgulha
- Está aberto à aprender novas tecnologias de programação e ferramentas

Vamos gostar ainda mais de você se:
- Já trabalhou com Node.js, Mongodb, Postgres, Clojure, Golang

### Benefícios

- Pacote de remuneração competitivo
- Assistência médica e odontológica
- Vale Refeição R$ 27 por dia
- Flexibilidade para escolher sua máquina
- Horário realmente flexível
- Oportunidade de atuar em algo com grande impacto na sociedade
- Gympass
- Snacks e bebidas no office

**Comment by MarcoWorms** [comment]
Eu trabalho na Hash e aprovo hahahahaha

Qualquer coisa pergunta aí na thread que a gente responde!

**Comment by RafaelGSS** [comment]
Olá! A proficiência em inglês é obrigatória ?

**Comment by MarcoWorms** [comment]
@RafaelGSS Olha, eu não diria que existem habilidades obrigatórias mas ao meu entendimento o inglês é uma barreia forte para aprender a desenvolver principalmente se você for se aprofundar bastante em algum assunto dado que grande parte do material é em inglês.

O nosso processo seletivo busca analisar na parte técnica o quão amplo é o conhecimento do candidato em cima de pontos que ele decidiu para arquitetar o desafio. Isso não requer saber ler ou falar inglês, inclusive temos pessoas na empresa que não tem um inglês afiado, então eu não olharia esse fator como algo eliminatório mas acredito que ele é essencial pro seu desenvolvimento profissional.

Se tiver na dúvida ainda se aplica na vaga e conversa com a gente!

**Comment by JonatanPotrikus** [comment]
Ola boa tarde,

A vaga esta aberta para ser 100% remota ?

Grato desde já.

Obrigado.

**Comment by leopedroso45** [comment]
Me candidatei, gostei muito da empresa!

**Comment by MarcoWorms** [comment]
@JonatanPotrikus aceitamos 100% remoto sim, o processo é o mesmo a única coisa que muda é que ao longo das validações técnicas as pessoas que vão te avaliar terão em mente que elas trabalharão com você remoto e não presencial. Isso pode mudar a maneira com que quem te avalia vai olhar alguns assuntos nas entrevistas, por exemplo uma boa comunicação assíncrona vira um fator essencial em alguém que ficará remoto então as pessoas vão tentar explorar como você lida com isso. No geral o processo é o mesmo com as mesmas pessoas e dinâmicas :)

**Comment by leonardocomodini** [comment]
@leopedroso45 Show Léo! Te encaminhei um e-mail ;)

**Comment by JonatanPotrikus** [comment]
@MarcoWorms valeu pelo pronto atendimento.

E cara, que legal. Parabens pela empresa, parece que fazem coisas incríveis e com tecnologias de ponta.

Atualmente trabalho com NodeJS+MongoDb, Ionic e laravel+(sqlServer || postgres). E confesso que nunca tinha visto algo referente a gRpc. O desafio é bem interessante, tem uma data prevista para finalizar o mesmo ? Ou a vaga ficara em aberto ?

**Comment by MarcoWorms** [comment]
@JonatanPotrikus O desafio não tem prazo de entrega. Geralmente se você preferir a gente marca uma chamada inicial contigo pra te explicar nosso produto e o contexto do time de tecnologia e da codebase. Se achar legal ja fazer o desafio vc pode só entregar ele quando achar que está bom e começamos o processo com ele ja entregue, a vaga fica em aberto e não tem prazo de fechar :)

**Comment by JonatanPotrikus** [comment]
@MarcoWorms da hora.

Beleza, vamos ver então., Entro em contato para marcarmos essa chamada inicial e entender mais sobre os projetos e conhecer melhor do negócio. 

E quanto ao projeto no momento ta corrido de mais, mas vou tentar fazer o mesmo. Achei ele muito interessante o fato de microservices, e gRpc parece ser algo muito perfomático. Aproveitar tambem pra dar aquela consolidada nos estudos de Docker \O/

**Comment by davialmeida** [comment]
Boa noite, a vaga também se aplica a programador Junior?
Tenho já uma certa experiência no backend com PHP/Laravel, e atualmente estou fazendo o curso Go Stack Bootcamp da Rockseat(Atualmente já passei pelo módulo 'GoNode', e agora estou no de ReactJS. rsrs).

**Comment by jonathanguilhermesouza** [comment]
O tipo de contratação é PJ ou CLT?

**Comment by leonardocomodini** [comment]
@davialmeida Davi, a vaga é pra qualquer um mas sendo bem honesto hoje não possuímos um time que conseguiria dar todo o suporte e acompanhamento pra alguém que tá começando agora. De qualquer maneira a gente sempre utiliza o nosso teste como barra de avaliação, o que significa que a gente pode sim te avaliar como um profissional que vai se encaixar bem no nosso cenário atual mesmo que seja alguém em início de carreira :)

**Comment by leonardocomodini** [comment]
@jonathanguilhermesouza Oi Jonathan! Nosso modelo hoje é CLT.

**Comment by jonathanguilhermesouza** [comment]
@leonardocomodini obrigado!
