### ISSUE TITLE
[São Paulo] Desenvolvedor back-end Pleno / Sênior na Vizir

### ISSUE THREAD

**Issue by apantaliao** [backend-br/vagas#1489]
Olá, tudo bem? 

Seja muito bem-vindo(a) à nossa vaga! Antes de mais nada, vamos deixar algumas coisas claras: 

- Para se inscrever a vaga, acesse [nossa página da vaga](https://recruiterflow.com/vizir/jobs/1)
- A vaga é para pessoas com alguma experiência em programação. Por isso colocamos pleno / sênior. Mas dentro do nosso time, no dia-a-dia, não usamos muito esta terminologia. 
- A vaga é presencial, mas com horário flexível. Estamos no centro de SP, na República. 
- Temos vagas abertas em projetos mais back-end, JavaScript, TypeScript e Rails. Mas embora seja mais para o back-end, gostamos que a pessoa não tenha medo de HTML. Mais do que conhecimento específico em uma plataforma queremos que seja uma pessoa que goste de programar, de fazer testes unitários e de fazer software bem feito!
  
Benefícios
- Ticket refeição: R$ 31,50 por dia (R$ 661,50 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou para onde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

Requisitos
- Conhecer bem uma linguagem de programação, boa lógica e orientação a objetos.
- Estar a fim de aprender.
- Ser comprometido em entregar projetos com qualidade.
- Curtir programar.
 
Desejáveis:
- Ter experiência com práticas ágeis, AWS, Microsserviços. 

**Para se inscrever a vaga, acesse: [Nossa página da vaga](https://recruiterflow.com/vizir/jobs/1)**

**Comment by jonathanguilhermesouza** [comment]
Aceita home office?

**Comment by apantaliao** [comment]
Olá, para está vaga em específico não. Temos várias pessoas que trabalham
em home office, mas infelizmente para esta vaga não temos disponibilidade.

Nestas vagas presenciais, fazemos home office ocasionalmente (algo como uma
vez por semana).

Até mais

Em qua, 21 de ago de 2019 08:01, Jonathan Guilherme <
notifications@github.com> escreveu:

**Comment by jonathanguilhermesouza** [comment]
@apantaliao obrigado!
