### ISSUE TITLE
[Belo Horizonte] Back-End Developer PHP Pleno [Sapiens]

### ISSUE THREAD

**Issue by sapiensbh** [backend-br/vagas#149]
## Descrição da vaga

Participará do desenvolvimento de novos projetos, aplicações web, aplicações mobile, webservices e blockchain. 

## Local

    Belo Horizonte - (Bairro Santa Efigênia)
    Escritório (Presencial)

## Benefícios

    VT + VR
    1 hora de almoço
    40 horas semanais

## Requisitos

Obrigatórios:

    - Estar confortável para trabalhar com demandas e datas pré-definidas com metas de produtividade;
    - Ser proficiente com as ferramentas ágeis mais comuns;
    - Experiência de pelo menos 2 anos com desenvolvimento backend em PHP;
    - Ser proficiente com PHP, HTML & CSS;
    - Saber o essencial de JavaScript, para por exemplo, lidar com a exibição dos dados advindos do backend através de 'templates engines';
    - Ter como pontos fortes, ter plena posse de suas ideias e resolver problemas desafiadores;
    - Ter o desejo de trabalhar de forma colaborativa com uma equipe.
    - Experiência com Frameworks (Laravel, Angular, React , Vue e etc...)
    - Git (Command Line)
    - Inglês Técnico para leitura
    - Conhecimentos de pré-compiladores de CSS

## Diferenciais:

    - Wordpress
    - Desenvolvimento de Plugins
    - Desenvolvimento de Temas
    - Woocommerce

## Contratação

    PJ Entre R$1.800,00 à R$ 2.600,00 + Bônus de Produtividade

## Nossa empresa

Somos a Sapiens, estamos há 09 anos no mercado e esse ano estamos fazendo uma fusão com outras empresas e buscando expansão no mercado nacional e internacional. Aqui você terá possibilidade de trabalhar em diversos projetos no Brasil e no exterior.

## Como se candidatar

Por favor envie um email para rh@sapiensolutions.com.br com seu CV anexado - enviar no assunto: Vaga Back-End Desenvolvedor Junior/Pleno

**Comment by reginaldojunior** [comment]
Essa vaga está sendo fechada por estar fora dos padrões de salário aceitáveis para uma vaga deste nível.

Tente melhorar o salário ou reduzir a quantidade de skills e reabra a issue.
