### ISSUE TITLE
[São Paulo] Desenvolvedor Mobile no Itaú CEIC

### ISSUE THREAD

**Issue by velrino** [backend-br/vagas#1491]
![enter image description here](https://scontent.fcgh4-1.fna.fbcdn.net/v/t1.0-9/68480275_889462628098080_5821819420879618048_n.jpg?_nc_cat=101&_nc_eui2=AeGYHvOuyOsrsvjmb7ot_5DgDp2OOiRexxyeeeae02Fb70r-591N8wxsmDKsPB9uGmH8EX00Th7_ozyraDutct_rJZrh_gk9I5UCCIYPRWvEeg&_nc_oc=AQm6KwZIayGm4nZZ_RhlO8fG_Ff6cvGQ7_X7p_Nfju2Il94USD6t1FYojkO9mM_b5JXGhWaZdkP0f6p7Tw1dzZ3t&_nc_ht=scontent.fcgh4-1.fna&oh=4dce2c37a6f9230cb794202e370ba6f2&oe=5DD60B65)

**Principais atividades:**
•	Participar do Desenvolvimento e implementação de projetos de novos aplicativos e melhorias nos sistemas existentes, visando atender as necessidades dos clientes internos, externos e parceiros de negócios;
•	Aplicar metodologia e padrões corporativos no desenvolvimento e manutenção de sistemas, através da divulgação e validação dos produtos gerados pelos terceiros.

**Perfil técnico:**
•	Conhecimento/experiência em análise de sistemas;
•	Experiência em desenvolvimento mobile Android ou iOS;
•	Conhecimento em Metodologia Ágil SCRUM;
•	Elaboração e execução de casos de testes.

**Perfil pessoal:**
•	Paixão por desenvolvimento de sistemas;
•	Pró-atividade e postura de dono;
•	Capacidade analítica com foco em eficiência e resultados;
•	Comunicativo, responsável, colaborativo e inovador;
•	Planejamento e organização para trabalhar com entregas programadas;
•	Habilidade de comunicação verbal e escrita;
•	Facilidade para trabalhar em equipe e estabelecer parcerias.

**Contratação:** CLT

**Comment by couras** [comment]
Enviado do Yahoo Mail no Android 
 
  <div>Em ter, 20 20e ago 20e 2019 às 10:09, Velrino</div><div><notifications@github.com> escreveu:</div>   


Principais atividades:
• Participar do Desenvolvimento e implementação de projetos de novos aplicativos e melhorias nos sistemas existentes, visando atender as necessidades dos clientes internos, externos e parceiros de negócios;
• Aplicar metodologia e padrões corporativos no desenvolvimento e manutenção de sistemas, através da divulgação e validação dos produtos gerados pelos terceiros.

Perfil técnico:
• Conhecimento/experiência em análise de sistemas;
• Experiência em desenvolvimento mobile Android ou iOS;
• Conhecimento em Metodologia Ágil SCRUM;
• Elaboração e execução de casos de testes.

Perfil pessoal:
• Paixão por desenvolvimento de sistemas;
• Pró-atividade e postura de dono;
• Capacidade analítica com foco em eficiência e resultados;
• Comunicativo, responsável, colaborativo e inovador;
• Planejamento e organização para trabalhar com entregas programadas;
• Habilidade de comunicação verbal e escrita;
• Facilidade para trabalhar em equipe e estabelecer parcerias.

Contratação: CLT
