### ISSUE TITLE
Desenvolvedor Back End Onawa

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1498]
Propomos um novo jeito de ser, interagir e vender: Conectamos marcas e consumidores por meio de uma poderosa ferramenta mobile de vendas por relacionamento e estratégia customizada. Perfeito para potencializar as vendas de e-commerces, marketplaces, franquias, indústrias, prestadores de serviços e lojistas em geral.

Descrição:
Estamos com algumas instabilidades na nossa plataforma. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para paula.lanza@vulpi.com.br

O que você irá fazer:

Desenvolver novos projetos;
Dar manutenção e atualizar projetos já existentes.
Você vai amar trabalhar aqui se estiver em busca de:

Ambiente sensacional;
Café o tempo todo #welovecoffee
Zero hierarquia, estamos caminhando para uma holocracia;
Cultura animal!
Gostar de trabalhar em equipe;
Ambiente de muito crescimento. Estamos crescendo 114% ao ano ;)
Requisitos obrigatórios:

PHP;
Laravel.
Vamos ficar muito felizes se você conhecer:

Metodologias Ágeis;
Node.
Informações complementares:

Contratação PJ;
Vaga presencial.

**Comment by carvalholeo** [comment]
Oi, boa noite, tudo bem?

Vi que a vaga é presencial, mas não achei a cidade. Para onde seria?

Grato.

Em ter, 20 de ago de 2019 às 16:14, Megan da Vulpi <notifications@github.com>
escreveu:
