### ISSUE TITLE
[Goiânia] Junior Full Stack Developer - Ruby on Rails [Siedos] 

### ISSUE THREAD

**Issue by jcottobboni** [backend-br/vagas#1499]
## Descrição da vaga

Junior Full Stack Developer na Siedos
Estamos buscando uma pessoa com o perfil fullstack, mais voltada para o backend

## Local

SIEDOS Goiânia

## Benefícios

- Plano de saúde;
- Vale alimentação;
- Vale transporte;
- Seguro de vida;
- Banco de horas;
- Área de alimentação e lazer;

#### Diferenciais

- 2 horas de almoço;
- Sala de jogos;
- Transparência em processos e decisões da empresa;
- A equipe preza pela evolução continua dos integrantes, o aprendizado de diversas tecnologias e o desafio diário;

#### Como Junior Full Stack Developer você tera que:
- Criar, lançar, acompanhar e manter soluções de software;
- Além do planejamento em equipe, auto-gestão das próprias atividades, saber lidar com dificuldades técnicas e identificar oportunidades de melhoria;
- Seguir boas práticas das linguagens e ferramentas utilizadas;
- Proatividade e interesse em entender e aprender as regras de negócio para propor soluções e agregar valor aos projetos e produtos;

#### Bônus

- Experiência em setor público

## Requisitos

**Obrigatórios:**
- Ter conhecimento básico da linguagem Ruby e do framework Ruby on Rails;
- Conhecimentos em SQL;
- Noções de Git;
- Conhecimentos JavaScript;
- Conhecimentos HTML/HTML5;
- Conhecimentos CSS/SCSS;
- Familiaridade de metodologias ágeis;
- Familiaridade com conceitos de MVC

**Desejáveis:**
- Experiência com testes unitários, de integração e de interface utilizando RSpec (Rails) e TDD
- Linters (preferencialmente  Reek e/ou Rubocop)
- ORACLE
- PostgreSQL
- Scrum
- APIs REST
- Disponibilidade para viajar
- Conhecimento em bancos de dados em memória: Redis, Memcached

**Diferenciais:**
- Contribuições para comunidade (opensource, palestras, etc);
- Git Flow;
- Micro Serviços;
- ShellScript;

## Contratação

CLT

## Nossa empresa

Equipe dinâmica, com metodologias ágeis de desenvolvimento e boas possibilidades de progressão. Empresa consolidada, com mais de 20 anos de atuação e em constante expansão nacional. Foco em folha de pagamento e sistemas administrativos para setor público. Salário a combinar

## Como se candidatar

Currículo para contato@siedos.com.br, com assunto "Vaga - Junior Full Stack Developer"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao.carlos@siedos.com.br

## Labels

- Alocado
- CLT
- Junior

**Comment by tiago123456789** [comment]
A possibilidade de trabalhar remotamente?

**Comment by jcottobboni** [comment]
Olá @tiago123456789 , no momento somente alocado.

**Comment by jcottobboni** [comment]
A vaga continua em aberto

**Comment by jcottobboni** [comment]
Vagas ainda em aberto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
