### ISSUE TITLE
[Florianópolis / Remoto] Fullstack Developer no Bulldesk

### ISSUE THREAD

**Issue by LucasLeandro1204** [backend-br/vagas#15]
# Vaga Full-stack Developer no Bulldesk

É dev e quer participar de uma startup em pleno crescimento em um ambiente criativo e flexível? Se liga!

Desenvolvimento, otimização e manutenção de código (tanto front e back end), garantindo que os requisitos sejam atendidos.

### O que procuramos:

- Atitude e experiência em gerenciar e priorizar seu trabalho.
- Capacidade de fazer as coisas de forma eficiente, mantendo ao mesmo tempo a qualidade e trabalhando em um ritmo consistente.
- Opiniões fortes - Não tenha medo de colocar suas ideias e participar na discussão do produto com a equipe.
- Pró-ativo e autodidata - Procure, tente, erre, tente de novo, aprenda e faça.
- Vontade de sempre aprender mais
- Uma abordagem iterativa - Nós nos concentramos em aprender e melhorar nossos processos ao longo do tempo, com uma abordagem ágil.
- Foco no cliente - Você sempre deve estar pensando: "O que posso fazer para entregar valor aos nossos clientes?"

### Requisitos:

- HTML5: código semântico, limpo, organizado, com ou sem frameworks (foundation, bootstrap, etc.)
- CSS: escalável e modularizado, sass/compass, crossbrowser
- Javascript: NPM/Yarn, jQuery, frameworks Angular, React, ou VueJS
- PHP 7: OOP, PSRs, Composer, com boa experiência em Laravel ou Symfony
- SQL: relacionamentos, índices, migrations, experiência com ORMs
- Ambiente unix e familiaridade com console/terminal
- Controle de versão com git

A vaga aceita remoto, porém nosso escritório se localiza em Florianópolis, Kobrasol / Campinas.

### Bônus:
• Experiência com devOps, continuous integration / deployment

## Contato
Envie seus projetos, github etc junto com pretensão salarial para gabriel@bulldesk.com.br

Abraço =)

![image](https://user-images.githubusercontent.com/13268691/31290895-898ca796-aaa4-11e7-9394-ebef5b7ba78e.png)

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
