### ISSUE TITLE
[Goiânia] Pleno Full Stack Developer - Ruby on Rails [Siedos] 

### ISSUE THREAD

**Issue by jcottobboni** [backend-br/vagas#1500]
## Descrição da vaga

Pleno Full Stack Developer na Siedos
Estamos buscando uma pessoa com o perfil fullstack, mais voltada para o backend

## Local

SIEDOS Goiânia

## Benefícios

- Plano de saúde;
- Vale alimentação;
- Vale transporte;
- Seguro de vida;
- Banco de horas;
- Área de alimentação e lazer;

#### Diferenciais

- 2 horas de almoço;
- Sala de jogos;
- Transparência em processos e decisões da empresa;
- A equipe preza pela evolução continua dos integrantes, o aprendizado de diversas tecnologias e o desafio diário;

#### Como Pleno Full Stack Developer você tera que:
- Criar, lançar, acompanhar e manter soluções de software;
- Além do planejamento em equipe, auto-gestão das próprias atividades, saber lidar com dificuldades técnicas e identificar oportunidades de melhoria;
- Seguir boas práticas das linguagens e ferramentas utilizadas;
- Pró atividade e interesse em entender e aprender as regras de negócio para propor soluções e agregar valor aos projetos e produtos;
- Levantamento de requisitos, pesquisa e provas de conceito;
- Efetuar Code Review e ajudar no treinamento e auxilio dos desenvolvedores Juniors;
- Escrever Testes para as aplicações;
- Manter e evoluir os aplicativos após sua instalação, monitorar e configurar servidores de deploy localmente e na cloud.

#### Bônus

- Experiência em setor público

## Requisitos

**Obrigatórios:**
- Ter domínio de Ruby on Rails;
- O ideal seria + 3 anos de experiência em desenvolvimento;
- Ter Conhecimentos sólidos em SQL;
- Conhecimentos JavaScript;
- Conhecimentos HTML/HTML5;
- Conhecimentos CSS/SCSS;
- Experiência com Git/GitHub/GitLab;
- Experiência  com REST/JSON APIs;
- Linters (preferencialmente  Reek e/ou Rubocop);
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- Conhecimentos em Design Patterns;

**Desejáveis:**
- Experiência com CI
- Experiência com ORACLE
- Experiência com PostgreSQL
- Conhecimento sobre engines em Ruby on Rails
- Disponibilidade para viajar
- Conhecimento em bancos de dados em memória: Redis, Memcached

**Diferenciais:**
- Contribuições para comunidade (opensource, palestras, etc);
- Git Flow;
- Micro Serviços;
- ShellScript;

## Contratação

CLT

## Nossa empresa

Equipe dinâmica, com metodologias ágeis de desenvolvimento e boas possibilidades de progressão. Empresa consolidada, com mais de 20 anos de atuação e em constante expansão nacional. Foco em folha de pagamento e sistemas administrativos para setor público. Salário a combinar

## Como se candidatar

Currículo para contato@siedos.com.br, com assunto "Vaga - Pleno Full Stack Developer"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao.carlos@siedos.com.br

## Labels

- Alocado
- CLT
- Pleno

**Comment by jcottobboni** [comment]
a vaga continua em aberto

**Comment by jcottobboni** [comment]
Vagas ainda em aberto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
