### ISSUE TITLE
[Osasco] Backend [iProduce]

### ISSUE THREAD

**Issue by iproduce** [backend-br/vagas#1508]
Olá,

Tenho algumas vagas para programador backend com experiência em desenvolvimento de aplicativos, para a cidade de Osasco. A vaga é temporária (3 meses). É necessário estar alocado no escritório. 

Conhecimento avançado em: HTML5, CSS3, Javascript, React, Flutter, PHP, MySql e Adobe Photoshop.

Tem interesse ou conhece alguém que esteja precisando? Então manda o seu portifólio e CV para no e-mail: freela@iproduce.com.br

Boa sorte!

**Comment by alessandroprudencio** [comment]
aceita remoto  não ?

**Comment by iproduce** [comment]
Alessandro, não apenas alocado.
