### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby na 5A Attiva

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#151]
**Quem somos**
A 5A atua fortemente no mercado Corporativo de TI, com destaque em Terceirização de Profissionais de Desenvolvimento, Gestão de Projetos e Soluções em Sistemas. 

**Dados da Vaga**
O que você precisa? 
- Ser apaixonado por desenvolvimento e tecnologia; 
- Código limpo  
- Ter experiência com Ruby 
- Ter conhecimentos de desenvolvimento WEB (HTML, CSS, Javascript, jQuery, etc); 
- Ter conhecimentos de práticas de XP, TDD, pair programming, refactoring, continuous integration, etc; 

**Contratação**
PJ +  benefícios ( VR e Férias remunerada de 30 dias após 1 ano )

**Como se candidatar** 
Interessados, encaminhar CV atualizado com pretensão salarial para Helen.matos@5aattiva.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
