### ISSUE TITLE
[São Paulo] Desenvolvedor NodeJs Jr na [IBM]

### ISSUE THREAD

**Issue by Kelvin-Costa** [backend-br/vagas#1510]
## IBM
O mundo está em seu melhor momento, está proporcionando novas formas de modelos operacionais, modelos de empresa, industrias e resultados. Nós temos exponencialmente maior poder de atingir o nível máximo do nosso potencial durante nossa vida profissional do que qualquer um antes de nós.

Esta é nossa visão do futuro, nosso compromisso com seu crescimento. Este é você com o poder da IBM.

[https://www.ibm.com/ibm/br/pt/?lnk=fsi-saib-brpt](https://www.ibm.com/ibm/br/pt/?lnk=fsi-saib-brpt)

## Descrição da vaga
Desenvolvedor NodeJs - Interlagos

## Posição
Junior

## Tipo de contratação
CLT 

## Requisitos
1-2 anos em desenvolvimento Back End
6+ meses em NodeJs

## Benefícios
- Bonus PLR
- Bonus global da IBM GDP
- Previdência privada, Vale alimentação e refeição
- Plano de saude
- Plano odontológico e de medicamentos familiar
- Bônus de incentivo para treinamentos internos e externos

## Como aplicar
Envie email com o título Posição ##NodeJs IBM, CV e pretenção para o

## Contato
kbusolin@br.ibm.com

**Comment by GuiziBr** [comment]
Olá @Kelvin-Costa , ainda não tenho experiência de mercado com desenvolvimento, você sabe me dizer se eu poderia aplicar para a vaga?

Obrigado

**Comment by MarcosRibeiroJesus** [comment]
> Olá @Kelvin-Costa , ainda não tenho experiência de mercado com desenvolvimento, você sabe me dizer se eu poderia aplicar para a vaga?
> 
> Obrigado

Requisitos
1-2 anos em desenvolvimento Back End
6+ meses em NodeJs

**Comment by Kelvin-Costa** [comment]
@MarcosRibeiroJesus bom dia

Para a vaga informada é necessária experiencia solicitada

**Comment by danieldfc** [comment]
@Kelvin-Costa Boa tarde, não tenho experiência na área comprovada, mas estudo na Rocketseat - GoStack, desde junho que ando praticando imersivamente as Tecnologias Node.js, ReactJs e React Native, será que posso habilitar para uma das vagas sendo (Jr/Pleno/Sênior)?

**Comment by Kelvin-Costa** [comment]
@DanielDavidDev necessária experiencia comprovada

**Comment by davialmeida** [comment]
É aquela coisa, como vou ter experiência se vocês não dão a chance da pessoa ter experiência?

**Comment by SamuelSousa1984** [comment]
@davialmeida, Não é necessário estar trabalhando pra ganhar experiência. Contribua com projetos open-source, crie suas API's, crie um produto que pode ser utilizado (uma API que devolve uma série de dados), pense em coisas como autenticação, segurança e implemente nela. Com isso você já está ganhando experiência

**Comment by iagovholanda** [comment]
Disponibilidade para remoto ?

**Comment by deyvisonborges** [comment]
Tenho interesse. Dê uma olhada em meu perfil

**Comment by arthur-mts** [comment]
Tenho interesse!
Mandei meu currículo para o email
