### ISSUE TITLE
[São Paulo] Desenvolvedor NodeJs Pleno na [IBM]

### ISSUE THREAD

**Issue by Kelvin-Costa** [backend-br/vagas#1511]
## IBM
O mundo está em seu melhor momento, está proporcionando novas formas de modelos operacionais, modelos de empresa, industrias e resultados. Nós temos exponencialmente maior poder de atingir o nível máximo do nosso potencial durante nossa vida profissional do que qualquer um antes de nós.

Esta é nossa visão do futuro, nosso compromisso com seu crescimento. Este é você com o poder da IBM.

[https://www.ibm.com/ibm/br/pt/?lnk=fsi-saib-brpt](https://www.ibm.com/ibm/br/pt/?lnk=fsi-saib-brpt)

## Descrição da vaga
Desenvolvedor NodeJs - Interlagos

## Posição
Pleno

## Tipo de contratação
CLT 

## Requisitos

2-4 anos em desenvolvimento Back End
1+ anos em NodeJs

## Benefícios
- Bonus PLR
- Bonus global da IBM GDP
- Previdência privada, Vale alimentação e refeição
- Plano de saude
- Plano odontológico e de medicamentos familiar
- Bônus de incentivo para treinamentos internos e externos

## Como aplicar
Envie email com o título Posição ##NodeJs IBM, CV e pretenção para o

## Contato
kbusolin@br.ibm.com

**Comment by JonatanPotrikus** [comment]
Bom dia @Kelvin-Costa a vaga é somente presencial ?

Impossivel abrir alguma vaga remoto para NodeJs ?

**Comment by Kelvin-Costa** [comment]
@JonatanPotrikus bom dia
Apenas presencial

**Comment by JonatanPotrikus** [comment]
@Kelvin-Costa OK, obrigado.

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Se houver a possibilidade remota, tenho muito interesse! Sou do RJ!
Abraços!
http://danielsiqueira.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
