### ISSUE TITLE
[Campinas] Desenvolvedor Ruby no Venturus - Inovação & Tecnologia  (Ruby/Rails)

### ISSUE THREAD

**Issue by erikunha** [backend-br/vagas#1514]
# Venturus - Inovação & Tecnologia!

O Venturus Inovação & Tecnologia, fundado em 1995, é hoje um dos grandes institutos de Pesquisa, Desenvolvimento & Inovação do Brasil. Somos um instituto de inovação, localizado no Polo II de Alta Tecnologia de Campinas/SP, que atua com as maiores empresas de tecnologia do mundo nas áreas de mobile, manufacturing, segurança digital, água e energia, entre outros. 

Hoje temos 300 funcionários feras em desenvolvimento de software, hardware, sistemas e outras soluções tecnológicas inovadoras. Credenciado junto ao CATI – Comitê da Área de Tecnologia da Informação – do Ministério da Ciência e Tecnologia, estamos entre os principais institutos que estão aptos a receber os incentivos decorrentes da Lei de Informática, Lei do Bem e outros fundos setoriais. 

Estes recursos aplicados aqui no Venturus transformam Pesquisa, Desenvolvimento e Inovação em competitividade. O Venturus também se atenta ao bom ambiente de trabalho por isso, temos nos destacado no ranking do Great Place to Work® como uma das Melhores Empresas para Trabalhar em TI & Telecom e do Brasil. 

O que você acha de trabalhar em um ambiente jovem, dinâmico e cheio de desafios? E se somar a tudo isso um programa que promove a integração entre as pessoas e a qualidade de vida? Achou impossível reunir todas essas qualidades em uma empresa só? Então você ainda não conhece o Venturus! Venha fazer parte do nosso time!

![Venturus](https://e3ba6e8732e83984.cdn.gocache.net/uploads/image/file/880877/regular_76066a6221983aecc5f1dd9e24f30c9a.jpg)

# Sobre a Vaga

Esta oportunidade é para você que gosta de trabalhar na área de meios de pagamento - ou deseja ingressar - em um ambiente dinâmico com desenvolvimento de software em Ruby. Suas responsabilidades serão voltadas para desenvolvimento de projetos para terminais de pagamento em linguagem Ruby para um de nossos clientes que está em plena expansão.

## Local

Condomínio GlobalTech - Estrada Giuseppina Vianelli di Napolli, 1185 - Polo II de Alta Tecnologia, Campinas - SP, 13086-530

![Venturus Google Maps](https://i.imgur.com/Ibpg45Y.png)

## Benefícios
![Venturus benefits](https://i.imgur.com/sAtBRvF.png)

##  Requisitos

**Competências e experiência desejadas:**

- Superior em Ciência da Computação, Engenharia da Computação, Sistemas de Informação e áreas afins.

- Conhecimento avançado em desenvolvimento Ruby.

- Conhecimento em banco de dados

- Experiência com sistema de controle de versão Git

- Conhecimento em metodologias ágeis (ex. Scrum)

- Inglês avançado

**Diferenciais:**

- Conhecimentos na área de meios de pagamento: EMV, ISO8583/ISO20022, Biblioteca Compartilhada ABECS, etc.

Vagas também para pessoas com deficiência.

## Como se Candidatar

A contratação é CLT, manda um e-mail para [aline.frediani@venturus.org.br](mailto:aline.frediani@venturus.org.br) com suas informações (Currículo, GitHub, LinkedIn) dizendo que gostaria de aplicar para a vaga que você viu aqui.  
Entraremos em contato em poucos dias com mais informações!

**Comment by erikunha** [comment]
Ainda procurando.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
