### ISSUE TITLE
[Rio de Janeiro-RJ] Desenvolvedor FullStack na DOT.LIB

### ISSUE THREAD

**Issue by vlamirsanto** [backend-br/vagas#1516]
## Nossa empresa

A Dot.Lib distribui conteúdo online científico e acadêmico a centenas de instituições espalhadas pela América Latina. Temos como parceiras algumas das principais editoras científicas nacionais e internacionais. Além de prover conteúdo, criamos soluções que atendem às necessidades de nossos clientes e editoras.

## Descrição da vaga

Buscamos um profissional que seja apaixonado por desenvolvimento, inovação e novas tecnologias, para integrar nosso time em projetos baseados em NodeJS, PHP e React JS/Native.

## Local

Barra da Tijuca, RJ

A oportunidade é 100% presencial.

## Benefícios

- Salário compatível com o mercado.
- Vale transporte.
- Plano de saúde.
- Plano odontológico.
- Vale Refeição ou Vale Alimentação.

#### Diferenciais

- Equipe unida, divertida e apaixonada por hambúrgueres.
- Cafeteira sempre cheia :P
- O gerente às vezes paga o almoço.
- Emendas em feriados nacionais.

## Requisitos

**Obrigatórios:**

- Mínimo 1 ano de experiência em desenvolvimento de sites e sistemas em NodeJS e ReactJS.
- Conhecimentos em Docker.
- Controle de versões (GIT).
- Conhecimentos em Linux.
- TDD.

**Diferenciais:**

- Experiência em PHP com Laravel.

## Contratação

Regime: CLT

## Como se candidatar

Para se candidatar, basta acessar a url e realizar o teste para a vaga:
https://github.com/dotlib/teste-desenvolvedor-pleno

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/CLT

**Comment by LeoFC97** [comment]
Tem com ser parcial? Parte local e parte Remoto?

**Comment by vlamirsanto** [comment]
@LeoFC97 infelizmente não.

**Comment by pedroaspereira** [comment]
É imprescindível conhecimento em PHP?

**Comment by vlamirsanto** [comment]
> É imprescindível conhecimento em PHP?

PHP é um diferencial.

**Comment by pedroaspereira** [comment]
> > É imprescindível conhecimento em PHP?
> 
> PHP é um diferencial.

Como faço para me candidatar?

**Comment by vlamirsanto** [comment]
> > > É imprescindível conhecimento em PHP?
> > 
> > 
> > PHP é um diferencial.
> 
> Como faço para me candidatar?

Só acessar o link acima para ver as informações do teste.
