### ISSUE TITLE
[Maringá/PR] Desenvolvedor NodeJs Pleno na Devninjas

### ISSUE THREAD

**Issue by willhoffmann** [backend-br/vagas#1517]
# Descrição da vaga

Procuramos uma pessoa talentosa e com potencial - que seja apaixonada por criar experiências memoráveis aos clientes através de uma contínua entrega de valor. Tenha disposição para construir uma nova cultura dentro de uma startup e se tornar uma liderança. Buscamos paixão por aprender acima de conhecimento "consolidado".

# Local

Maringá/PR

# Benefícios

Vale Alimentação/Refeição
Vale Transporte
Plano  de Carreira
Dress Code Casual

# Diferenciais

* Oportunidade de crescimento rápido
* Confiança e liberdade
* Ambiente divertido, colaborativo e rápido
* Transparência em todas as decisões

# Requisitos

**Obrigatórios:**

* +1 ano de experiência em Node,js
* Saber escrever testes
* Conhecimento em Docker
* Domínio de bancos de dados relacionais (Postgres, MySQL, etc...) e familiaridade com noSQL databases (Redis, Elastic, etc...)
* Saber o momento certo de utilizar Design Patterns
* Conhecimentos de testes unitários, aceitação, mocks, etc
* Ter argumentos para defender suas decisões técnicas
* Conhecimento em conceitos de integração (Sync/Async, Pub/Sub);
* Aplicação de boas práticas de clean code e experiência com metodologia ágil;
* Capacidade de analisar um código já existente para dar sequência ao produto, concentrando-se na entrega e na refatoração, quando necessário;
* Facilidade para aprender novas tecnologias e conceitos;

**Desejáveis:**

Você vai se destacar se:

* Souber desenvolver com TDD, DDD
* Tiver liderado tecnicamente uma equipe
* Tiver trabalhado com integração de sistemas

# Contratação

CLT

# Nossa Startup

A Devninjas, startup brasileira de alto crescimento, é uma fábrica de software que oferece soluções inovadoras para o mercado tecnológico.

# Como se candidatar

Por favor envie um email para william.hoffmann@devninjas.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor NodeJs

Ou cadastre diretamente em nosso site: https://www.devninjas.com.br/carreira/vaga-desenvolvedor-nodejs

# Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 uma semana após cada processo.
E-mail para contato em caso de não haver resposta: mariana.ganassin@devninjas.com.br

# Labels

Presencial
experiência/Pleno
regime/CLT

**Comment by JonatanPotrikus** [comment]
@willhoffmann boa tarde.

Existe alguma vaga no Devninjas remoto ?

**Comment by willhoffmann** [comment]
@JonatanPotrikus
Boa tarde.

Atualmente estamos somente com vagas presencial.

**Comment by jgecen** [comment]
Me candidatei a uma vaga aí na devninjas, até hoje estou aguardando o feedback, acho que faz mais de dois meses
