### ISSUE TITLE
[Porto Alegre] C# Full Stack Developer na InterProcess

### ISSUE THREAD

**Issue by alexandrejunges** [backend-br/vagas#152]
## Descrição da Vaga
A InterProcess busca um(a) C# Full Stack Developer para se juntar à equipe e ajudar no desenvolvimento de soluções inovadoras para nossos clientes. 

Como um(a) Full Stack Developer você irá trabalhar com desenvolvimento desktop (Windows Forms/C#), web (Angular), e serviços, fazendo parte de um time multidisciplinar. 

#### Obrigatórios
- Ser apaixonado(a) por programação; 
- Experiência com desenvolvimento C#; 
- Conhecimento em banco de dados (usamos SQL Server); 
- Experiência com sistemas de controle de versão (usamos Git). 

#### Desejáveis
- Conhecimento em arquitetura de microserviços; 
- Conhecimento em testes de unidade; 
- Experiência com a plataforma Azure; 
- Conhecimento em Angular; 
- Experiência com métodos ágeis. 
 
## Benefícios 
- Vale Refeição ou Alimentação;
- Vale Transporte;
- Ginástica Laboral;
- Massoterapia;
- Plano de Saúde;
- Plano Odontológico;
- Auxílio para capacitação (eventos, livros e certificações).
 
## Contratação
- CLT (44h/semana) 

## Local
Tecnosinos, São Leopoldo, RS 
ou  
Boa Vista, Porto Alegre, RS  

## Quem Somos
A InterProcess é uma empresa de excelência em soluções para gerenciamento de informações no segmento da saúde. 
Com sede em Porto Alegre, atua nas áreas de consultoria, desenvolvimento, implantação e suporte de sistemas e serviços. 

## Faça Parte da Equipe
Envie-nos um e-mail com seu CV que nossa equipe entrará em contato com você. Estamos ansiosos para te conhecer. 
E-mail para contato: rh@interprocess.com.br 

## Labels
- CLT
- Alocado
- Pleno
- .NET

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
