### ISSUE TITLE
[Brasília - DF] Analista de Infraestrutura DevOps

### ISSUE THREAD

**Issue by wagnerjs** [backend-br/vagas#1521]
# Analista de Infraestrutura DevOps

## Descrição da vaga

- Definir arquitetura e implantação de infraestrutura de aplicações
- Desenvolver e dar manutenção aos processos de CI/CD
- Monitorar e garantir o funcionamento dos sistemas de produção e desenvolvimento
- Interagir e buscar por eficiência técnica e automação dos processos de trabalho

## Local

Brasília - DF

## Requisitos

- Experiência com Docker e Docker Swarm;
- Experiência em integração e deploy contínuo com Gitlab CI/CD
- Experiência em gerência de configuração com Chef
- Linguagem de programação Python ou Shell Script
- Conhecimento em Linux (Ubuntu Server)
- Balanceamento de carga com Nginx

## Diferencial

- Experiência com ferramentas de monitoramento de ambiente
- Configuração e manutenção da stack do Elasticsearch (ELK)

## O que oferecemos

- Horário flexível
- Remuneração competitiva
- Bônus por desempenho
- Ambiente inovador e de entretenimento
- Plano de Saúde e Dental
- Vale Alimentação/Refeição
- Convênio com instituição de idiomas, academia e o SESC

## Como se candidatar

Envie o seu currículo para o e-mail rhtalentos221@gmail.com no campo assunto informar: DEVOPS e informe pretensão salarial.

**Comment by jonathanguilhermesouza** [comment]
@wagnerjs Aceita home office?
