### ISSUE TITLE
[São Paulo] Backend Developer Pleno/Senior

### ISSUE THREAD

**Issue by brenooliveira** [backend-br/vagas#153]
##  Vaga Backend Developer Pleno/Senior ##

Estamos procurando desenvolvedores backend para nos ajudar a construir produto, desde a sua concepção  até a implementação. Procuramos desenvolvedores que utilizem a tecnologia como um meio e que entendam que cada tecnologia pode resolver um problema de uma melhor forma. 
Buscamos pessoas que entendem a necessidade de criar testes automatizados e quando criar os testes, apaixonados por métricas, que tenham o senso do dono com produto.

## O Negócio ##
Um produto digital no setor financeiro, com uma grande ambição e que está no começo do seu desenvolvimento.

## Onde estamos? ##
WeWork Faria Lima

## Requisitos ##
 - Ter autonomia, capacidade de autogestão e auto-organização do trabalho;
 - Conhecimento em alguma linguagem OO;
 - Testes automatizados (TDD/BDD);
 - Sólidos conhecimentos de protocolos de rede (HTTP/gRPC/TCP/UDP/IP);
 - Experiência com ferramentas de automação;
 - Modelagem e consumo de API's RESTful;
 - Entrega Contínua;
 - Containers (Docker);
 - Serviços AWS (Lambda, EC2, ECS, SQN, SNS);
 - Conhecimento em arquitetura de micro-serviços;
 - Vivência em metodologias de desenvolvimento de software.

## Tecnologias ##
 - Java, Elixir, NodeJs, Python ou Go
 - MySQL ou Postgres
 - MongoDB
 - RabbitMQ
 - Kafka
 - ElasticSearch
 - Docker

## Desejáveis ## 
 - Conhecimento em linguagem funcional (Elixir, Scala, Haskell) 
 - Ops Tools 
 - Kubernates
 - Jenkins, TravisCI, CircleCI, etc
 - ReactNative

## Diferenciais ##
 - Um bom GitHub e contribuições Open-source

## Contratação ##
PJ

## Topa? ##
Me mande um e-mail breno26@gmail.com com seu LinkedIn e GitHub.

## Labels ##
 - Backend
 - PJ
 - Senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
