### ISSUE TITLE
[Piracicaba] Back-End Python Developer na [Intelup]

### ISSUE THREAD

**Issue by lucasdu4rte** [backend-br/vagas#1531]
A intelup é uma empresa qualificada como uma das startups mais promissoras do Brasil (100 Open), e que tem contribuído com a indústria 4.0.

### Responsabilidades da Função
- Fazer parte do time de Devs, trabalhando na melhoria do produto e atualizando suas habilidades continuamente com o melhor do mercado: cursos, leitura, palestras e experiência.

- Manter nossas soluções usando as melhores práticas de mercado, teste automatizados, código limpo e bem escrito.

#### Requisitos
- API REST
- ORM
- Flask ou Django
- Docker

#### Bônus
- AWS
- Experiência com micro-serviços
- NoSQL
- Testes Automatizados
- CleanCode

Enviar currículo para **vagas@intelup.com.br**

**Comment by lucasdu4rte** [comment]
Por favor, envie currículo para vagas@intelup.com.br

**Comment by leonardo1909** [comment]
Aceita ramoto?

**Comment by lucasdu4rte** [comment]
A empresa tem preferência em presencial, por enquanto
