### ISSUE TITLE
[São Paulo] Desenvolvedor Backend Rails no Totalpass/Smart Fit

### ISSUE THREAD

**Issue by alessandrogurgel** [backend-br/vagas#1535]
**A Empresa**

O Totalpass faz parte do grupo Bio Ritmo/Smart Fit, a maior empresa no segmento fitness da América Latina e quarta maior do mundo. Estamos presentes no Brasil, México, Chile, Peru, Colômbia, República Dominicana e Equador. A rede possui mais de 500 unidades e mais de 1.8 milhão de alunos ativos. O grupo também detém marcas modernas de academias especializadas: Race Bootcamp, Torq Cycle e Nós.

O Totalpass é um benefício corporativo 100% digital que busca fornecer aos colaboradores das empresas clientes o acesso às melhores redes de academias do Brasil por um preço mais baixo que o praticado no mercado visando proporcionar uma maior qualidade de vida e uma vida mais ativa aos colaboradores. O Totalpass já atua no Brasil e no México e deve entrar em outros países latinos ainda esse ano.

O departamento de desenvolvimento de software é fundamental dentro do grupo pois enxerga-se na tecnologia uma grande oportunidade de simplificação de processos e maximização da eficiência de seus colaboradores.
Mantemos um ambiente descontraído, onde a opinião de todos refletem na tomada de decisão da equipe. Estamos abertos à novas tendências de mercado e tecnologias em nossa constante evolução.

**Sobre a vaga**

Precisamos de um desenvolvedor backend pleno/sênior para se juntar a nossa equipe em São Paulo com experiência em Rails/Postgres/Javascript.
O Totalpass tem um ambiente bem dinâmico e estamos em um momento de franco expansão.
Temos um time heterogêneo com desenvolvedores fullstack, backenders, 1 frontend, 1 designer e 1 analista de suporte. O time ajuda na análise de dados de negócios. Temos bastante contato com as áreas comerciais e somos fundamentais nas tomadas de decisões estratégicas. Temos aplicativos web PWA SPA, integramos com totem de academias, plataformas de acompanhamento nutricial, sistemas ERP e temos planos de ter desenvolvimento mobile num futuro próximo.

A vaga é exclusivamente presencial em nosso escritório localizado na Avenida Paulista (período integral, porém com horário flexível).

**Requisitos**
- Experiência com Ruby on Rails
- Conhecimentos sólidos de programação OOP, MVC
- Boas práticas de programação
- Conhecimentos de modularidade e padrões de projetos
- Experiência com testes unitários
- Experiência com Banco de Dados relacional;
- Experiência com Javascript/HTML (básico)
- Ter trabalhado em equipe
- Git
- Experiência em consumir APIs REST
- Ser responsável por estruturar os artefatos do projeto
- Ser responsável pela qualidade de cada entrega do produto
- Ser ético e lidar bem com colegas da equipe
- Saber receber e dar feedback sobre código ou comportamento
- Disposição em aprender novas tecnologias, discutir soluções  e conceitos para melhorar performance
- Gostar de Desafios. Queremos crescer muito num tempo curto!
**Diferenciais (Plus)**
- Experiência com testes de integração 
- Experiência com ferramentas de Business Intelligence
- Experiência com algum framework JS: React/React Native/VueJS/Angular
- Métodos Ágeis
- Saber falar em Espanhol e/ou Inglês

**Benefícios:**
- Acesso gratuito a todas as academias do grupo: Smart fit, Bio Ritmo e academias internacionais;
- Vale Refeição;
- Vale Alimentação;
- Note da empresa  a sua escolha entre Mac, Linux ou Windows (vai que)
- Bicicletário no prédio;
- Remuneração

**Salário:**
- A combinar dependendo da experiência (pleno ou sênior).

**Vamos conversar**
- Manda um email com CV para alessandro.gurgel@totalpass.com.br

**Labels**
- CLT
- Alocado
- Pleno
- Senior

**Comment by Gilbertojpargas94** [comment]
Greetings!. My name is Gilberto Perez and I'm a Full-Stack Web Application Developer, using the Ruby on Rails Framework. I would love to have the opportunity to discuss your project with you and get an agreement to define a contract.

I have several years of experience in Web Application Development and over two years using the Ruby on Rails framework, in addition to Bootstrap for the design. Much of my experience comes from working for projects such as YeahThem or DGGiros & Remesas, etc. Which are web applications with a responsive design. I'd be happy to provide you with links so that you can review them before making a hiring decision.

Thank you for your time and consideration.

Sincerely, Gilberto Perez.
