### ISSUE TITLE
[São Paulo] Back-End Developer Java no Grupo Netshoes

### ISSUE THREAD

**Issue by tonimota** [backend-br/vagas#1536]
## Descrição
Estamos a procura de um profissional que #rompapadrões, que tenha **#foco** no resultado e que tenha **#tesãoporfazer**  sempre o melhor! Tá afim? :-)
Então dê uma olhada no perfil abaixo e venha fazer parte de um dos maiores e-commerces da América Latina!  \o/

Aqui você vai:

- Realizar a arquitetura baseadas em micro serviços;
- Comunicar via mensageria (ActiveMQ, RabbitMQ, HornetMQ, Kafka);
- Realizar bases de dados SQL/NoSql (Oravle, SqlServer, MongoDB, Cassandra, Redis);
- Monitorar logs (Graylog;
- Realizar padrões REST para criação de serviços;
- Documentat APIS via biblioteca (swagger, spring-fox, spring-rest-docs e etc);
- Containers com Docker e gestão com Kubernetes
- Realizar metodologias de desenvolvimento TDD, BDD, Testes de Integração, Testes de Stress (Gatling, JMeter).

## Local
Ficamos localizados na Rua Vergueiro, 943, bem pertinho do metrô Vergueiro!

## Contratação
CLT Full

## Requisitos
Superior Completo;
Conhecimento em Java, preferencialmente em 8+.

## Desejavél
- Padrões REST para criação de serviços;
- Framework Spring-boot;
- Desenvolvimento com TDD;
- Ferramentas de controle de versionamento Git;
- Metodologias ágeis;
- Realizar bases de dados (SQL/NoSql (Oracle, SQLServer, MongoDB, Cassandra, Redis).

## Benefícios
- Vale Refeição :-)
- Vale Alimentação
- Assistência Médica: Notredame Intermédica.
- Assistência Odontológica: BBDental.
- Vale Transporte
- Day Off, descanso merecido no dia do seu aniversário \o/
- Horário Flexível! 
- Participação nos Lucros e Resultados;
- Desconto em Produtos;
- Previdência Privada;
- Parceria com Gympass, mexa-se!
- Parceria  com o Cartão Funcional;
- Parceria com Faculdades, você sendo protagonista do seu conhecimento!

E aí? Gostou?! Então que tal juntar-se ao nosso time?! ;-)
Envie um e-mail com link do Github e do seu Linkedin para **marcelo.paparelli@netshoes.com**

## Labels
CLT
Presencial
Júnior
Pleno
Sênior

**Comment by AndersonMarquess** [comment]
Show de bola! :smiley:
