### ISSUE TITLE
[Belo Horizonte - MG] Vaga de Backend Developer Pleno

### ISSUE THREAD

**Issue by halisonrsjr** [backend-br/vagas#1549]
Desenvolver software para plataforma Web, 
Programar em Laravel 5.6+
Conhecimento básicos em PHP 7.0 ,HTML 5 , CSS 3 e JS. 
Conhecimentos básicos de MySql e serviços REST API. 
Desejável: Inglês técnico (leitura e escrita).

**Comment by adrianogl** [comment]
Como candidatar?

**Comment by halisonrsjr** [comment]
Me manda seu curriculo em halison@falconbrazil.com.br
