### ISSUE TITLE
[Florianópolis] Desenvolvimento Back-End pleno em Grupo Neolife

### ISSUE THREAD

**Issue by GrupoNeolife** [backend-br/vagas#1551]
Cargo: Desenvolvimento Back-End Pleno
Carga horária: 8 horas diárias

O que esperamos de você:
- Capacidade de aprender coisas novas e de melhoria constante;
- Paixão por tecnologia e marketing;
- Espírito de colaboração para agregar a nossa equipe;
- Atenção em tudo o que você está desenvolvendo;
- Sugerir novas e melhores soluções em tudo que inicia;
- Disposição para trabalhar em um ambiente de ritmo acelerado;
- 2 anos de experiência com PHP 5+;
- Conhecimentos em Orientação a Objetos, MVC, APIs;
- Banco de dados relacionais (MySQL);
- Versionamento de código (GIT);
- HTML, CSS e Javascript;
- Conhecimentos básicos em Linux;
- Inglês técnico (leitura).

Diferenciais:
- Inglês Avançado;
- Experiência com Wordpress.

Onde irá nos auxiliar?
- Desenvolver código limpo, testável e de fácil manutenção;
- Contribuir com todo o processo de desenvolvimento de software;
- Implementar features novas e investigar problemas em produção;
- Contribuir nas discussões técnicas sobre os desafios encontrados.

Valorizamos nossos colaboradores e pensamos em nosso espaço para deixar a galera a vontade e ainda oferecemos:

Salário: a combinar
+ Vale transporte;
+ Seguro de vida;
+ Aulas de inglês com professor nativo (Após 30 dias de experiência);
+ Acesso a nossa Universidade Corporativa (Muitas capacitações!!);
+ Horários flexíveis;
+ Um ambiente descontraído (no dress code), com snacks, frutas fresquinhas, cafézinho e chá a vontade, almoço com a galera, vídeo-game e nossa biblioteca particular. 

Sobre nós:
O grupo Neolife é uma startup global de marketing direto com produtos próprios. Começamos a atuar em 2018 e já somos reconhecidos no mercado por grandes empresas, como a Monetizze. No entanto, mesmo com todo esse crescimento, nunca perdemos nosso foco: unir pessoas extraordinárias para revolucionar a forma de vender online.

Na Neolife, nós acreditamos que a fórmula do sucesso está na união de pessoas diferentes e talentosas em torno de um objetivo comum. Para nós, a vontade de aprender e se desenvolver é o mais importante, por isso somos um grupo de overachievers focados em resultados. Trabalhamos com compromisso, precisão e inovação e é através dessa essência que estamos crescendo de forma sólida e saudável. O resultado? Alcançamos as metas que um dia achávamos serem impossíveis e incentivamos cada novo overachiever a viver de suas paixões e a conquistar todos os seus sonhos.

Deu match? <3 Venha nos conhecer melhor: https://gruponeolife.com.br

Encaminhar currículo/portfólio para talentos@gruponeolife.com.br

##labels
PJ, Pleno, Alocar

**Comment by eusouomauricio** [comment]
Boa noite. Para qual e-mail devemos encaminhar currículo?
