### ISSUE TITLE
#VAGA [Banco Cora] [Eng. de Software Back-End Sênior] [SÃO PAULO]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#1556]
**A Cora está nascendo**, e precisa de você para construir um novo banco.

**É tudo do zero!** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em **5% ao ano**.

Não buscamos uma stack específica, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

**Comment by LucascrMota** [comment]
@AndreBorim , você pode disponibilizar o salário da vaga?
Também gostaria de saber se tem alguma linguagem de preferência, mesmo que não seja eliminatória!

**Comment by AndreBorim** [comment]
> @AndreBorim , você pode disponibilizar o salário da vaga?
> Também gostaria de saber se tem alguma linguagem de preferência, mesmo que não seja eliminatória!

Olá @LucascrMota,
Sobre o salário, a Cora está disposta a pagar até 13 mil reais + benefícios em um regime de contratação CLT. E sobre a linguagem de programação exigida, a Cora é bem aberta quanto a isso e não define uma única stack, mas tem preferência por linguagens orientadas a objetos. 

Espero ter ajudado!

Qualquer dúvida pode me chamar ;D

**Comment by iagobyintera** [comment]
É necessário residir em São Paulo para participar do processo?

**Comment by AndreBorim** [comment]
> É necessário residir em São Paulo para participar do processo?

Não é necessário, Iago. As etapas do processo serão todas online.

Espero ter ajudado!

Qualquer dúvida pode me chamar ;D

**Comment by halkliff** [comment]
Há a possibilidade de Home Office? Gostaria muito de participar e, quem sabe, me juntar ao time, mas não posso sair da minha cidade pois estou terminando uma graduação...

**Comment by AndreBorim** [comment]
> Há a possibilidade de Home Office? Gostaria muito de participar e, quem sabe, me juntar ao time, mas não posso sair da minha cidade pois estou terminando uma graduação...

Infelizmente não há esta possibilidade para esta vaga =\

Espero poder te ajudar em uma oportunidade futura!

Qualquer dúvida pode me chamar ;D

**Comment by ghost** [comment]
Pessoal, o processo seletivo para esta vaga ainda está aberto!

**Comment by AndreBorim** [comment]
Pessoal, a vaga ainda está aberta. Qualquer dúvida estou disposto à ajudar.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
