### ISSUE TITLE
[São Paulo] Desenvolvedor JAVA na Docket 

### ISSUE THREAD

**Issue by carolinaleaodocket** [backend-br/vagas#1570]
**Somos uma startup revolucionária.**

Nós desenvolvemos uma plataforma que proporciona uma experiência end-to-end (do começo ao fim) sobre busca, gestão e análise de documentos cartorários e forenses. Significa que criamos um sistema inovador que faz com que o processo de formalização de documentos, que sempre foi longo e lento, torne-se um processo ágil, integrado e produtivo.
Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que se enquadrem na nossa cultura. \o/

Estamos em busca de um Desenvolvedor Jr que seja apaixonado por desenvolvimento Java e que tenha ambição de crescer junto com a Docket. Precisamos que você tenha experiência de 1 ano na área e que queira aplicar sua arte no mundo real da programação. Você terá a oportunidade de mostrar tudo o que sabe e nós ajudaremos a transformar sua trajetória de carreira.

Acha que somos compatíveis? Venha e #junteseaotime. =)

 **Na Docket você irá:**
-Trabalhar no desenvolvimento (código/testes) com múltiplos projetos
-Criar estratégias para transformar requisitos de negócio, funcionais e não funcionais, em código modular e reutilizável;
-Responsável por aplicar as boas práticas de engenharia de software e padrões de projeto;
-Implementar e manter aplicações;
-Responsável pela manutenção de códigos/testes de sistemas;

**Você vai se encaixar bem se:**
-Possuir formação em Ciências da Computação, Sistemas de Informação ou áreas relacionadas à tecnologia da informação.
-Bons conhecimentos em Java, SQL, HTML, CSS e JavaScript
-Conhecimentos em framework como Spring ou Hibernate
-Ter experiência de no mínimo 1 ano em desenvolvimento Java

**Benefícios:**
- Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida
- Ambiente descontraído, criativo e oportunidade de crescimento acelerado. =)
- Local: Pinheiros (a 5 minutos da estação de metrô Pinheiros)
- Horário: 44 horas semanais

Se inscreva: https://docket.gupy.io/

**Comment by luccasdev** [comment]
A vaga ainda está disponível ?

**Comment by carolinaleaodocket** [comment]
Sim, a vaga ainda está disponivel =)

[image: Logo Docket]
Carolina Leão
Folks
11 2769-5007
docket.com.br
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=ee81dd11e2&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=c13dc2be69&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=09843fb6fb&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=330a4a5bf7&e=d9d1f070dd>
[image:
Youtube] <https://www.youtube.com/channel/UC2x4kEpt5tXEKg1RCaFLMUQ> [image:
Blog da Docket] <http://www.documentosjuridicos.com.br/>

Startup acelerada por:

4º Lugar no LinkedIn
Top Startups 2018

Selecionada para
o Ranking
[image: Logo do Google Developers Launchpad] [image: Logo do ScaleUp da
Endeavor] [image: Logo do LinkedIn Top Startups 2018] [image: Logo 100
Startups to Watch de 2019]


Em ter, 15 de out de 2019 às 12:02, Lucas Rodrigues <
notifications@github.com> escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
