### ISSUE TITLE
[São Paulo] .Net Senior na [Athos]

### ISSUE THREAD

**Issue by negaomor10** [backend-br/vagas#1574]
### Descrição da vaga

Procuramos pessoass apaixonadas com o propósito de revolucionar o design e a criação de software atuando como um Desenvolvedor .Net Senior para São Paulo-SP.

A Athos está em constante crescimento no mercado e gostaríamos de trazer novas pessoas para nosso time. Nós buscamos trabalhar com as tecnologias mais atuais do mercado e com metodologias ágeis.
Estamos buscando um profissional com um perfil proativo, comunicativo e detalhista, com menor necessidade de mentoria e menor supervisão no cumprimento das tarefas.

### Descrição do Cargo:
Ser parte de times de alta performance em projetos de grande porte;
Trabalhar em aplicações de negócios em multi-camadas e com design personalizado, que utilizam as mais recentes tecnologias para a construção de sistemas críticos e escaláveis;
Experiência na escolha e aplicação de boas práticas de software como Test Driven Development (TDD), integração e entrega contínua;
O candidato irá trabalhar com sistemas Web, Mobile e Desktop, visando as boas práticas de código.

Ser parte de um ambiente aberto e não hierárquico onde se espera que todos colaborem dentro do projeto e nas direções da organização.

### Requisitos
Experiência com desenvolvimento em C#;
Conhecimento de .NET Framework, .NET Standard e .NET Core;
Experiência com criação de APIs REST;
Experiência com Banco SQL Server, desejável MongoDb;
Conhecimento Entity Framework;
Conhecimento de Injeção de dependência;
Experiência com controle de versionamento Git ou similar.

### Diferenciais
Experiência com Metodologias Ágeis / Scrum;

### Benefícios:
Vale Refeição
Vale Transporte
Plano de Saúde
Seguro de Vida

### Nossos Diferenciais:
Horário Flexível
No Dress Code
Folga no dia do aniversário;
Festa em comemoração aos aniversariantes do mês;
Descontos em faculdades, cursos de inglês e espanhol;
As datas comemorativas sempre são lembradas com uma surpresa (dia das mães, dias dos pais, Páscoa, etc...);

### Local de trabalho:
Liberdade - São Paulo

### Horário de trabalho:
8h30 às 17h30

### Observações
Não aceita remoto, somente presencial.

CLT ou PJ

Interessados podem enviar curriculo para rh@athos.com.br

**Comment by jonathanguilhermesouza** [comment]
@negaomor10 há possibilidade de PJ?

**Comment by negaomor10** [comment]
Olá @jonathanguilhermesouza sim existe a possibilidade. Estamos contratando CLT e PJ.

**Comment by negaomor10** [comment]
Olá ainda estamos contratando.
