### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na DR. CANNABIS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1576]
### Sobre a empresa: Dr. Cannabis

Somos uma comunidade que acredita no direito à saúde como um direito primário. O tratamento com canabinoides pode mudar vidas e é legal no Brasil. Por isso informamos, acolhemos e conectamos pessoas interessadas no tratamento com cannabis medicinal.

### Descrição:

Estamos com algumas instabilidades. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para bruna.valerio@vulpi.com.br :)

### As habilidades necessárias:

Node.js;
APIs;

### O que brilharia os nossos olhos?

Sails.js;
SQL;
WordPress;
Experiência com plataformas de inbound marketing e CRM;

### Beneficios:

Férias remuneradas;
13º salário;
Horários flexíveis;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Gosta de ter autonomia e propor novas soluções;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Tem senso de urgência e foco na solução;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Quer mudar a sua carreira e embarcar em um projeto inovador e com muita expectativa de crescimento;

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/drcannabis_fullstack

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Essa vaga pode ser remota? Sou do RJ!
Abraços!
http://danielsiqueira.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
