### ISSUE TITLE
[São Paulo] Full-stack Developer na Escale

### ISSUE THREAD

**Issue by Renanmacedof** [backend-br/vagas#158]
**Buscamos alguém que:**

Sabe codar loucamente em uma linguagem específica, mas manja muito de lógica de programação e acredita que a linguagem é só uma ferramenta;

Sabe pensar toda a arquitetura de um sistema, desde sua infraestrutura, passando pela arquitetura do backend até a implementação no front;

Segue padrões de desenvolvimento já estabelecidos no mercado e sabe quando aplicar cada um para atender melhor a lógica do negócio;

Escreve código limpo, bonito e testável, mas não tem tempo ruim na hora de meter a mão naquele código feio que Mun-ha deixou aí quando decidiu largar a vida de DEV.

RESTful API oriented design / modular service oriented architecture

Infraestrutura (AWS)

**Você é importante para nós porque:**

Você vai ser primordial para alcançarmos o crescimento e impacto que queremos causar no mercado de marketing digital e vendas. Queremos transformar a maneira como o cliente adquiri produtos e serviços e sabemos que desenvolvedores fodas se traduz em produtos fodas.

**Suas atividades serão:**

Refatorar, otimizar e ampliar projetos em diferentes linguagens de programação como NodeJS, Scala, PHP, Golang e Python;

Criar novos projetos, decidindo pela melhor tecnologia para aquele problema;

Criar soluções e adequar existentes para que tenham alta disponibilidade;

Cobrir de testes unitários, funcionais e/ou de integração os cenários necessários;

Auxiliar nas discussões técnicas com PO e TechLead;

Participar das cerimônias do SCRUM.

**Seria bom ter conhecimentos em:**

Ambiente de desenvolvimento Node.js e Golang

Bancos de dados MySQL e MongoDB

RESTful API oriented design / modular service oriented architecture

Infraestrutura (AWS)

Browser-based single page applications: React, Angular, Backbone, Ember, Vu

Experiência em diversos projetos.

**Onde estamos?**

República, São Paulo/SP

**Contratação**

CLT

## Como se candidatar

Por favor envie um email para renan.macedo@escale.com.br com seu CV anexado.

## Labels

- CLT
- Pleno
- Sênior

**Comment by giovannicruz97** [comment]
Qual o contato para envio de currículo ?

**Comment by Renanmacedof** [comment]
Olá, tudo bem?

Pode enviar para renan.macedo@escale.com.br

Obrigado pelo toque! Vou atualizar

Em seg, 9 de abr de 2018 19:53, Giovanni Cruz <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
