### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Back End na Quero Educação

### ISSUE THREAD

**Issue by pebype** [backend-br/vagas#1585]
### Nosso time de Tech

Nosso time de tecnologia é pioneiro no uso de diversas stacks e nós os incentivamos a inovar, trabalhar com autonomia, colaboração e foco em metas ousadas. Aqui cada um lidera seu próprio caminho e  somos adeptos de metodologias ágeis unidas às melhores práticas de mercado para entregar grandes resultados.

Testes, automatizações e otimizações são constantes por aqui e investimos muito para promover a melhor experiência  de ponta a ponta. Queremos que a jornada seja tão boa quanto o resultado final.

No time de tecnologia da Quero temos profissionais de diversos níveis de experiência, que trabalham juntos, em um ambiente de crescimento acelerado, pelo nosso maior propósito: conectar milhões de alunos a instituições de ensino.

### Nossos desafios
Viemos para desburocratizar o acesso à educação. Somos uma plataforma online cujo propósito é simplificar a vida de alunos e instituições de ensino.
Facilitamos a vida de quem quer aprender, conectando-o a quem é especialista em ensinar.
Nosso desafio é grande, nosso crescimento é acelerado e  buscamos os melhores profissionais para essa missão. Para fazer parte da melhor Edtech do país, é preciso estar aberto a oportunidades, ter olhar analítico, facilidade para resolução de problemas e muita vontade de crescer e fazer acontecer.

### QUAIS SERÃO SUAS ATIVIDADES NO DIA A DIA?
- Construir apis e serviços back end utilizando NodeJS;
- Contribuir em decisões de arquitetura do projeto;
- Criar ferramentas para medir e otimizar a performance dos nossos serviços;
Automatizar tarefas repetitivas
- Integrar serviços third-party, como gateways de pagamento,ferramentas de email marketing e provedores na área de educação
- Priorizar e tratar bugs e exceções reportados em produção;
- Eventualmente realizar algumas adaptações e documentar APIs para outros back-ends com linguagens OO e funcionais (como Ruby e Elixir).

### QUAIS SÃO OS REQUISITOS PARA VOCÊ SE CANDIDATAR?
- Ter experiência com desenvolvimento web com ênfase em back end;
- Proficiência com Git
- Contato básico com Devops: Integração Contínua, Conteinerização (Docker) e Serviços Clouds
- Bancos de dados SQL, preferencialmente PostGres
- Sólidos conhecimentos de Estruturas de Dados e Algoritmos;
- Melhores Práticas de Desenvolvimento: BDD, Design Patterns, Clean Code, SOLID principles.
- Testes de Unidade, Funcionais e de Integração.

### EXPERIÊNCIA NESSAS ÁREAS SÃO RELEVANTES, MAS NÃO SÃO OBRIGATÓRIAS
- Typescript
- JIRA
- Framework NestJS
- React ou Vue.JS;
- NoSQL
- Conhecimento em frameworks web (Rails, Phoenix, Express);
- Microservices;
- Orquestramento de Containers (Kubernetes)
- Mensageria (Rabbit, Kafka, etc)
- Infra as a Code (Terraform)

### NOSSO SANTO VAI BATER SE VOCÊ (FOR):
- Apaixonado por desenvolvimento de software;
- Focado em Resultados;
- Proativo;
- Se identifica com Ambiente de Startup, de muito Trabalho e muita Diversão.
- Pensa fora da caixa e propõe soluções criativas;
- Motivado por Desafios;
- Team Player;
- Gosta de sempre Aprender Coisas Novas;
- Quer fazer parte de um Time World Class e de Alta Performance;
- Acredita em fazer as coisas com amor.

### O QUE NOSSOS COLABORADORES TÊM:
- Stock Options
- Bônus semestrais
- Plano de saúde e odontológico
- Vale-refeição
- Vale-transporte ou auxílio combustível
- No dress code
- Co-working Spaces com localização privilegiada com fácil acesso a transportes públicos, cozinha compartilhada, café da manhã toda segunda. Café, chá e snacks à vontade. Bicicletário, espaço pet friendly, happy hour uma vez por mês promovido pelo Spaces e roof top.

### Sobre a Quero
Somos uma plataforma que conecta alunos a instituições de ensino.
Utilizamos tecnologia para transformar o sistema educacional em uma experiência simples, rápida e inteligente.
Estamos construindo a maior empresa de tecnologia educacional do mundo  e procuramos pessoas que não tenham medo de assumir responsabilidades, confiem nas suas capacidades e pensem no coletivo para fazer essa construção acontecer!

### Nossa Cultura
Aqui, lideramos nosso caminho: sabemos que colocando a mão na massa, cresceremos cada vez mais.
Nosso time é apaixonado pelo que faz e obcecado por entregas.
E nós reconhecemos isso - pensamos em tudo para que o nosso todos tenham a melhor experiência possível e possam crescer na mesma velocidade que a gente.

Queremos deixar um legado e nada menos do que isso.

Quer construir algo grandioso?
Venha trabalhar com a gente!

Oportunidade: 
https://jobs.lever.co/quero.education/ce2a40f2-f7eb-440a-8faa-9413afd8f9ff?lever-via=4ybWfKlo3A

**Comment by httpspedrosilva** [comment]
teste
