### ISSUE TITLE
[Palmas] Dev Mobile - React Native [Siedos]

### ISSUE THREAD

**Issue by victoreduardo** [backend-br/vagas#1587]
## Descrição da vaga

Dev Mobile na Siedos
Estamos buscando uma pessoa com o perfil Dev Mobile, com conhecimento em React Native

## Local

SIEDOS Palmas
## Benefícios

- Plano de saúde;
- Vale alimentação;
- Vale transporte;
- Seguro de vida;
- Banco de horas;
- Área de alimentação e lazer;

#### Diferenciais

- 2 horas de almoço;
- Sala de jogos;
- Transparência em processos e decisões da empresa;
- A equipe preza pela evolução continua dos integrantes, o aprendizado de diversas tecnologias e o desafio diário;

#### Como Dev Mobiler você tera que:
- Criar, lançar, acompanhar e manter soluções de software;
- Além do planejamento em equipe, auto-gestão das próprias atividades, saber lidar com dificuldades técnicas e identificar oportunidades de melhoria;
- Seguir boas práticas das linguagens e ferramentas utilizadas;
- Proatividade e interesse em entender e aprender as regras de negócio para propor soluções e agregar valor aos projetos e produtos;

#### Bônus

- Experiência em setor público

## Requisitos

*Obrigatórios:*
- Ter conhecimento em React Native;
- Conhecimentos em SQL;
- Noções de Git;
- Firebase
- Typescript;
- Familiaridade de metodologias ágeis;
- Familiaridade com conceitos de MVC

*Desejáveis:*
- Experiência com testes unitários, de integração e de interface
- Linters (preferencialmente  Reek e/ou Rubocop)
- Scrum
- APIs REST
- Disponibilidade para viajar

*Diferenciais:*
- Contribuições para comunidade (opensource, palestras, etc);
- Git Flow;
- Micro Serviços;
- ShellScript;

## Contratação

CLT

## Nossa empresa

Equipe dinâmica, com metodologias ágeis de desenvolvimento e boas possibilidades de progressão. Empresa consolidada, com mais de 20 anos de atuação e em constante expansão nacional. Foco em folha de pagamento e sistemas administrativos para setor público. Salário a combinar

## Como se candidatar

Currículo para victor.eduardo@siedos.com.br, com assunto "Vaga - Dev Mobile"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.

## Labels

- Alocado
- CLT
- Junior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
