### ISSUE TITLE
[São Paulo] Back-End Developer na brainn.co

### ISSUE THREAD

**Issue by gustavohenrique** [backend-br/vagas#159]
## Descrição

A brainn.co é uma empresa de produtos digitais full-solution com sede em São Paulo. Estamos desenvolvendo produtos de diversos segmentos, de fantasy games à aplicações em blockchain, passando por edtech e produtos de segurança. Estamos crescendo rápido e com uma essência de aprendizado constante bem bacana em nossos times, e queremos recrutar pessoas interessadas em aprender, contribuir e entregar valor. Nosso formato de trabalho é:

- Trabalhamos com times multidisciplinares formados por profissionais de gestão de produto, analytics, design e engenharia.
- Nossos times são realmente ágeis: só trabalhamos com escopo aberto e isso quer dizer que nós trabalhamos em projetos onde podemos alterar o curso das coisas rapidamente, reagindo às mudanças do mercado e/ou dores dos usuários.
- Trabalhamos com novas ideias: nosso foco está justamente em materializar novos conceitos e, por isso, criamos os produtos do zero utilizando diversas tecnologias de acordo com o problema a ser resolvido.

Se tiver um tempinho e curiosidade, dá uma olhada no nosso [GitHub](https://github.com/brainn-co/guides).

Vamos bater um papo? É só você enviar um e-mail para hello@brainn.co comentando o interesse.

## Labels

- Elixir
- Javascript
- Ruby
- Python
- Golang
- Remoto

**Comment by nicolascb** [comment]
Seria legal dar um feedback pra galera que se dedicou e fez o desafio.

Fica a dica.

**Comment by gustavohenrique** [comment]
Olá @nicolascb , tudo bem?

Realmente, houve uma falha do nosso lado com relação à devolutiva no seu processo em função da sobrecarga de número de aplicações que tivemos.  Em média, levamos 3 dias na análise do resultado. Você já deve ter recebido contato da nossa equipe para resolvermos isso e darmos o feedback sobre o seu Challenge. É importante frisar que nós analisamos 100% dos testes que realizamos com os candidatos que selecionamos e sempre fornecemos uma análise dos pontos positivos e negativos do resultado.

Abraços e obrigado pelo seu feedback.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
