### ISSUE TITLE
[REMOTO] Desenvolvedor BackEnd Ruby on Rails na E-INSCRIÇÃO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1593]
### Sobre a empresa: E-inscrição

Somos uma empresa jovem e inovadora. Um dos nossos pilares é a auto-responsabilidade de cada um da equipe. Todos somos focados em prover serviços e experiências que encantam os clientes. 

Nosso propósito é prover soluções para organizadores realizarem eventos com excelência e simplicidade, garantindo a melhor experiência para seus participantes. Nossos clientes são, em sua maioria, instituições religiosas e é muito importante para nós que nossos colaboradores se sintam à vontade com esse universo e, além disso, que se identifiquem! Sabemos que o alinhamento de valores entre a empresa e o colaborador é essencial para a felicidade e propósito no trabalho. 

Não é incrível poder estar em um lugar onde seus valores pessoais são vividos dia a dia? Gostou da ideia? Vem trabalhar com a gente! Amamos Home-office, somos 100% remotos! A distância NÃO nos impede de sermos uma grande equipe, com cultura forte e nos proporciona uma excelente qualidade de vida :)

### Descrição: Qual será o seu papel

Trabalhar no roadmap das melhorias da nossa plataforma;
Correção de bugs;
Desenvolvimento de novas funcionalidades;

### Esperamos que você seja muito bom em:

Ruby;
Ruby on Rails;
SQL;
Conhecimento em microservices;

### Vamos ficar felizes se você conhecer:

HTML
CSS
React

### Você vai amar trabalhar aqui se:

Estiver em busca de trabalho 100% remoto;
Gostar de trabalhar em ambiente colaborativo, onde as pessoas se importam umas com as outras;
Gostar de estar em empresas com cultura forte e que vive diariamente sua missão;
Trabalhar como foco em resultados;
Se sentir confortável com a nossa ligação com o universo religioso (queremos que você seja feliz);

### Benefícios:

Descanso remunerado de 30 dias;
Viagem e estadia com tudo pago para um evento de tecnologia no Brasil. Valorizamos e incentivamos seu crescimento pessoal;
Pagamos excelentes cursos nas tecnologias que você vai usar no dia-dia. Perceba como queremos pessoas que querem de fato aprender e crescer!
Trabalhar com stack moderna e tecnologia de ponta;

### Informações Complementares:

Contratação tipo PJ;
Vaga 100% remota;
Estamos localizados no Rio de Janeiro - RJ;

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/e-inscrição_remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
