### ISSUE TITLE
[São Paulo - SP] FullStack Senior Java Developer na Jurema

### ISSUE THREAD

**Issue by malungo** [backend-br/vagas#1594]
## Descrição da vaga
O candidato ideal deve se interessar pela oportunidade de manter a versão atual do stack de uma startup de uma grande instituição com possibilidade de se envolver na migração para nodeJs.

## Local
Remoto ou Escritório, São Paulo - Vergueiro

### Obrigatórios
- Experiência prévia no framework Spring Boot;
- Conhecimentode tecnologias front-end (angularjs, HTML5, CSS3);
- Bons conhecimentos em modelagem relacional de dados;
- Controle de versão de código-fonte em Git (Gitflow);
- Familiaridade com ambiente Linux.
- Experiência com infra-estrutura AWS

### Desejáveis
- Capacidade de autogestão e aprendizado;
- 4 anos de experiência prévia em desenvolvimento para web.
- Experiência em desenvolvimento PHP
- Disponibilidade para trabalho fulltime em nosso escritório;

## Nossa empresa
Desde 2010, a Jurema busca criar soluções que tornem o dia a dia das pessoas mais simples ou divertido. Combinando design e desenvolvimento de software concebe produtos e serviços que rompem os limites entre a web e o mundo físico, ajudando junto com seus parceiros - empreendedores, empresas e agências - a criar o futuro da web.

## Como se candidatar
Por favor envie um email para jobs+java@jurema.la com seu CV anexado - enviar no assunto: Vaga FrontEnd Angular

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: ping@jurema.la

## Labels
- PJ
- Sr
- Remoto
- Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
