### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na KUMON

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1596]
### Sobre a empresa: Kumon

O Kumon é uma metodologia que visa incentivar na criança a autonomia nos estudos, buscando fortalecer o potencial de aprendizado de cada um. Por meio de um processo de aprendizagem planejado e individualizado, o aluno se torna confiante e capaz de enfrentar sozinho o desafio da conquista do conhecimento. Criado por um professor de matemática e pai, preocupado com o processo de aprendizagem do filho, o método Kumon estimula o aluno a gostar de aprender e a se sentir seguro.

### Descrição:

Estamos com algumas instabilidades. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para livia.vasconcelos@vulpi.com.br :)
Ocupações do cargo

- Projetar e desenvolver sistemas e páginas web responsivos;
- Manutenção em sistemas existentes;
- Gestão do ambiente Cloud (App Services, Storage, Azure Database);
- Criar manuais e conteúdos de suporte aos usuários;
- Preparar e realizar treinamentos com os demais colaboradores da empresa;
- Pesquisar sobre novas tecnologias que visam melhorar os serviços prestados;

### Benefícios

Aqui você encontrará, um ambiente que altamente colaborativo que preza pelo aprendizado de maneira continua. Um local que preza pela troca de conhecimento e por ideias inovadoras. Nós oferecemos:

Regime de contratação CLT;
Remuneração compatível com o mercado;
Vale Transporte;
Vale Refeição (R$24,00 - dia);
Vale Alimentação (R$136,50 - mês);
Plano Médico (SulAmérica);
Plano Odontológico (Odontoprev);
Seguro de Vida (Metlife);
PPLR semestral;
Subvenções de cursos de pós-graduação, idiomas, academia;
Material Didático do Kumon;
Plano de carreira;

### Aptidões e qualidades

Buscamos profissionais de sólida experiência, apaixonados por tecnologia. Que tenham experiência com:

- Experiência em desenvolvimento, análise e testes de sistemas / aplicações Web / Responsivo
- Experiência em UI/UX
-Visual Studio 2017 (ASP.net, C#, MVC)
- Experiência em plataformas GIT
- Experiência com servidores IIS, Apache e serviços Web
- Experiência em desenvolvimento com Nodejs, Javascript, HTML5, CSS
- Frameworks Web (Bootstrap, Angular, JQuery)
- Experiência de desenvolvimento e consumo de API's (XML, JSon)
- Banco de Dados SQL Server, MySQL (Queries, Views, Stored Procedures), NoSQL (MongoDB)
- Conhecimento em desenvolvimento mobile (Android Studio, Xcode)
- Conhecimento em ambiente Microsoft Azure (aplicações IaaS / PaaS)"

### Informações da empresa

O Kumon é uma multinacional japonesa e a maior rede de franquias no segmento de educação no Brasil. Em 2018, fomos eleitos a melhor Microfranquia pela PEGN e temos o selo de excelência em franchising da ABF.

O método Kumon maximiza a capacidade dos alunos, descobre qual é o ponto ideal de estudo para cada um e fornece aos mesmos, material didático eficaz. O método Kumon está agora disponível em 51 países e regiões ao redor do mundo.

Venha fazer parte de nossa equipe e contribua para o desenvolvimento de nossos alunos!

### Candidatar: Entre em contato com o recrutador da vaga via WhatsApp http://bit.ly/kumon_fullstack1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
