### ISSUE TITLE
[Eindhoven, NL] Backend Developer (JAVA) | Jumbo Supermarkets

### ISSUE THREAD

**Issue by ksvh88** [backend-br/vagas#1597]
**To shape the future of food experiences**

**[Jumbo Tech Campus](https://www.youtube.com/watch?reload=9&v=giDJeFEvanE): Where It All Happens**
environment with many technical challenges. Our e-commerce platform has to keep up with our ever growing customer base and that’s why we are looking for talented people. Are you a software craftsman who can write maintainable, clean and testable code, but can also contribute to the development of the team and of the product? Then this is your chance to join the Jumbo family!

Jumbo Supermarkten is the 2nd largest supermarket chain in the Netherlands. The company was founded over >100 years ago by a family. It's still private owned, but nowadays it's a company of >650 stores , >80000 employees and an IT department of >300 people. Our HQ is located in Veghel (close to Eindhoven). Last year Jumbo’s ecommerce turnover doubled. And our omnichannel focus has enabled customers to do their shopping both in shops as well as online. In our multidisciplinary, international and environment you will work on innovative products and services which we release more and more by continuous delivery. So you’ll be working today on a new food experience that our customers will be able to use tomorrow!

**Your job as an Java Backend Developer**
As a Backend Engineer (java) you will be part of a scrum team that is focused on a domain, such as Selling, Ordering, Collect and Pay, etc. Each team has all the skills required to implement a user story from A to Z. Your team consists of frontend and backend developers, a business analyst, a tester and a product owner. Together you will work in sprints of two weeks to deliver value to the product you are responsible for.

We give a lot of autonomy and responsibility to people. At our Jumbo Tech Campus, we want to write maintainable, clean code. We review each other’s code and learn from each other whenever we can. We continuously monitor our systems performance to keep up with our ever-growing customer base.

We strive to make online shopping for our customers better every day and you, as a Senior Backend Engineer, can add value in many ways: you create and improve features, the user experience, clean up technical debt, redesign/rewrite components, improve performance, contribute to the direction of the product, share knowledge.

Your main tasks as a Java Backend Developer

- You play an important role in re-architecting our platform from a monolithic architecture to a microservices architecture deployed in a Kubernetes cluster on Amazon Web Services (AWS);
- You write maintainable and clean code, covered with tests. Primarily in Java but if there is a good reason for it, also Kotlin, Scala or Node.js.
- You coach other team members and share knowledge, review each others code and learn from each other
- Together with the product owner and the business stakeholders, you help defining the most optimal process and technical solution for the epics the team has on the roadmap.

**Do you have the Jumbo DNA?**
We expect you to take ownership and responsibility for the product your domain/team owns. This means you and your team are responsible for the successes and failures of the product, and its your responsibility to make sure the product is stable and future proof. Is your product unavailable? You make sure it becomes available. What happened? You make sure the root cause is found and fixed. Can it scale and support future epics? You make sure you understand the requirements and that the architecture and codebase support those requirements.

You should contribute with ideas and actions to continuously improve the teams way of working.

You dont reason only from a technical perspective. When analysing a problem or epic, you consider the impact to our customers, to the business processes, you make sure the solutions proposed make sense from a cost-benefit perspective.

You are a craftsman with >6 years of experience in java development. You take pride in your work and you make sure what you deliver is of high quality. Your code is covered with (unit, integration, acceptance, stress) tests, follows best practices such as the SOLID principles, reports metrics and other data to our logging and monitoring tools, etc.

**Whats in it for you?**
Shaping the future of online food retail is a challenging job. We will offer you plenty of space to develop your own initiatives and lots of opportunities to grow, both personally and in your area of expertise. Also, you will be surrounded by talented people with whom you will exchange ideas, knowledge and memes with.

You’ll receive a competitive salary and great working conditions. But even more importantly, we:

- Value your ideas and code more than your dress code;
- Are a food retailer so of course you can have a delicious lunch in our food cafe and food market;
- Are a family company so we want you to become part of our Jumbo Tech Campus family;
- Will give you 30 days of holidays a year;
- Offer a working environment in which you can learn, grow and have lots of fun!
- Offer a complete relocation package for you and your family that includes visa sponsorship, flights to the Netherlands, shipping your belongings, housing and navigating the bureaucratic part of settling in a new country.

**Interested?**
Please apply via [the website](https://jumbowerkt.nl/vacatures/senior-backend-engineer) or send me an email: han.swinkels@jumbo.com

_See you soon in Silicon Veghel!!_

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
