### ISSUE TITLE
[São Paulo] Senior Software Engineer na Zul Digital

### ISSUE THREAD

**Issue by marciocamurati** [backend-br/vagas#16]
# **Quem somos?**
Zul é uma startup fundada em 2016 com a seguinte missão: usar tecnologia para melhorar a forma com que as pessoas interagem com o estacionamento dos seus veículos. Em apenas alguns meses de operação, registramos um crescimento expressivo, chegando a mais de 500.000 usuários únicos. Esse sucesso é o resultado de uma extensa pesquisa e muito trabalho: desde o início nossa plataforma foi desenhada para ser robusta e amigável, e estamos trabalhado em diversas inovações, adicionando novas funcionalidades que visam melhorar a vida dos nossos consumidores.

Nosso time está crescendo, e sempre buscamos pessoas talentosas. Hoje estamos com uma oportunidade para um desenvolvedor hábil, que busca desafios complexos e que goste de trabalhar com gente fora da curva. Essa pessoa ajudará no desenvolvimento de uma nova cadeia de funcionalidades, entregando mais valor aos nossos consumidores, além de trabalhar ativamente em diversos desafios, ajudando a criar o futuro dos aplicativos de estacionamento. 

Zul foi construído com as melhores e mais modernas tecnologias, e você será responsável por desenvolver e dar manutenção no core da nossa plataforma, além de construir novas aplicações web e mobile.

Gostou? Veja abaixo a lista de requisitos que buscamos:

# **Requisitos**
**Experiências desejáveis**
- RESTful API
- Arquitetura com microservices
- Processamento assincrono
- Proficiency in Java
- Banco de dados SQL e NoSQL
- Programação funcional como Scala e Kotlin
- Mensageria como RabbitMQ e Resque
- Infrastructure as code
- Automatização de testes unitários, testes funcionais e testes de integração

**Diferencias**
- Frameworks modemos como Vertx.io, Light4j e Spring Boot
- Arquitetura com APIs
- Integração continua
- AWS Services
- Conhecimento em outras linguagems como Python, Nodejs ou Ruby
- Desenvolvimento mobile iOS ou Android

# **Beneficios**
- Salário competitivo
- Ajuda de custo para conferências e cursos online

# **Como se candidatar**
Para fazer sua candidatura a vaga acesse a página https://zul.workable.com/jobs/583180 e preencha com seus dados.

Caso não se encaixe no perfil dessa vaga e tenha interesse em ver outras oportunidades acesse: https://zul.workable.com

**Comment by opchaves** [comment]
Oportunidade muito interessante. Apliquei para ela @marciocamurati

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?

**Comment by marciocamurati** [comment]
@reginaldojunior já contratamos mas seguimos em busca de mais profissionais com esse mesmo perfil para completar o time.

**Comment by reginaldojunior** [comment]
Vaga preenchida, posso fechar a issue?

**Comment by marciocamurati** [comment]
@reginaldojunior pode fechar. Obrigado!
