### ISSUE TITLE
[São Paulo] Analista Programador .Net na Deal

### ISSUE THREAD

**Issue by Leticiacoelho25** [backend-br/vagas#160]
Experiência .Net C# pleno com profundos conhecimentos em .Net Framework 4.0 ou 
SQL Server 2008/2012 e Oracle 10g e PL SQL,Entity Framework e/ou nHibernate 
Experiência em WCF e Asp.Net WebAPI 
Proecificiência em ADO.Net,ASP.NET MVC,XML,JSON,Web Services,HTML,Javascript,JQuery 
Experiência na utilização dos frameworks jQuery/Bootstrap/AngularJS 
Desenvolvimento multi-camadas(N Tiers)Experiência com aplicações distribuídas(WCF,COM+) 
Experiência com aplicações e/ou processos assíncronos Desenvolvimento de ETL e SSIS 
Sólida habilidade em OOP(Object Oriented Programming)e Design Patterns(MVVM, MVP, MVC) 
Conhecimentos com ASP 3.0, VB6(Opcional)Conhecimentos básicos em Sharepoint(Opcional) 

Duração 3 meses com alta possibilidade de renovação - Região do Itaim Bibi

Indicações ou informações: leticia.coelho@deal.com.br
CLT
Pleno
Sênior

**Comment by Mgescud** [comment]
Qual a forma de inscrição ?

Sent from my iPhone

On 10 Apr 2018, at 09:05, Leticiacoelho25 <notifications@github.com<mailto:notifications@github.com>> wrote:


Experiência .Net C# pleno com profundos conhecimentos em .Net Framework 4.0 ou
SQL Server 2008/2012 e Oracle 10g e PL SQL,Entity Framework e/ou nHibernate
Experiência em WCF e Asp.Net<http://Asp.Net> WebAPI
Proecificiência em ADO.Net<http://ADO.Net>,ASP.NET<http://ASP.NET> MVC,XML,JSON,Web Services,HTML,Javascript,JQuery
Experiência na utilização dos frameworks jQuery/Bootstrap/AngularJS
Desenvolvimento multi-camadas(N Tiers)Experiência com aplicações distribuídas(WCF,COM+)
Experiência com aplicações e/ou processos assíncronos Desenvolvimento de ETL e SSIS
Sólida habilidade em OOP(Object Oriented Programming)e Design Patterns(MVVM, MVP, MVC)
Conhecimentos com ASP 3.0, VB6(Opcional)Conhecimentos básicos em Sharepoint(Opcional)

Duração 3 meses com alta possibilidade de renovação - Região do Itaim Bibi
