### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack na SÓ MULTAS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1603]
### Sobre a empresa: Só Multas

A SÓ Multas é uma empresa séria, especializada em consultoria de direito de trânsito. Todos os nossos recursos são feitos dentro da lei, embasados na legislação de trânsito, direito administrativo e direito constitucional. 

Já atendemos milhares de condutores, com uma taxa média de sucesso muito alta. Nosso maior diferencial é que analisamos cada caso individualmente, o que proporciona a defesa adequada e a utilização dos argumentos jurídicos corretos.

### Descrição: Qual será o seu papel?

Ser referência técnica;
Contribuir com a evolução dos nossos projetos, desenvolvendo novas funcionalidade e dando manutenção no nosso produto.

### Esperamos que você tenha experiência com:

PHP;
Zend;
JavaScript;
jQuery;
HTML/CSS;
Wordpress;
MySQL.

### Você vai amar trabalhar aqui se:

Estiver em busca de um ambiente de trabalho leve com muita autonomia, horizontalidade e liberdade;
Estiver em busca de um ambiente de muito crescimento;

### Informações Complementares:

Contratação PJ
Vaga presencial;
Estamos localizados em Belo Horizonte, no Carlos Prates.
Pleno

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/só_multas

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
