### ISSUE TITLE
[São Paulo, SP] Desenvolvedor de automação no Banco Safra [FECHADO]

### ISSUE THREAD

**Issue by AndreCecchi-Safra** [backend-br/vagas#1604]
Empresa: Banco Safra S/A
Cargo: Analista (CLT) Júnior/Pleno
Local: R. Bela Cintra 560, Consolação - São Paulo, São Paulo

**Atividades:**
Desenvolvimento de software de RPA (por hora em .NET e usando tecnologias open source).
Desenvolvimento de soluções para interface de usuário e visualização de dados.
Liberdade para o desenvolvimento das soluções para os problemas de automação.
Interface com diversas áreas do banco, a fim de entender o funcionamento do negócio e propor soluções de RPA.
Desenvolvimento de projetos segundo metodologia ágil.
Pesquisa de tecnologias novas para RPA (UIPath, Cypress).

**Pré-requisitos:**
Experiência com linguagens de POO (C#, Java, Python, etc).
Experiência com automação de processos (desejável)
Desenvolvimento .NET (desejável)
Conhecimento de front-end (desejável)
Conhecimento de ferramentas de RPA (desejável)

**Benefícios:**
VA, VR, VT, PLR, salário a combinar.

**Início:**
Outubro/2019
1 vaga

Enviar currículo para: andre.cecchi@safra.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
