### ISSUE TITLE
[Curitiba] Desenvolvedor FullStack na IDEIA NO AR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1605]
### Sobre a empresa: Ideia no Ar

Nós somos especialistas em ajudar empresas e empresários a criar o seu próprio marketplace de serviços. Acreditamos que a economia compartilhada, e novos modelos de negócios escaláveis e exponenciais, como o marketplace, são o futuro do e-commerce. Por isso, auxiliamos empreendedores a facilitarem e intermediarem a conexão entre oferta e demanda de serviços na internet, para aumentar seu impacto e faturamento do negócio.

### Descrição: Qual será o seu papel?

Dar manutenção e propor melhorias na nossa plataforma;
Propor solução para nossos clientes;
Não só desenvolver, mas entender do negócio :)

### Esperamos que você tenha experiência com:

C#;
Programação orientada a objetos;
Boas práticas de programação.

### Vamos ficar felizes se você conhecer:

Asp.net: Nosso principal produto é em C# e Asp.net MVC. Se você tiver interesse em aprender essa tecnologia, vamos ficar bem felizes :)

### Você vai amar trabalhar aqui se:

Estiver em busca de um ambiente de trabalho dinâmico e de MUITO crescimento;
Tiver um perfil empreendedor;
Estiver sempre em busca de conhecimento;
Trabalhar como foco em resultados.

### Benefícios:

Vale Refeição;
Vale Transporte.

### Informações Complementares:

Contratação tipo CLT;
Vaga presencial;
Estamos localizados na região central de Curitiba.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/ideia_no_ar

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
