### ISSUE TITLE
[São Paulo, SP] Desenvolvedor .NET no Banco Safra [FECHADO]

### ISSUE THREAD

**Issue by AndreCecchi-Safra** [backend-br/vagas#1606]
Empresa: Banco Safra S/A
Cargo: Analista (CLT) Júnior/Pleno
Local: R. Bela Cintra 560, Consolação - São Paulo, São Paulo

**Atividades:**
Desenvolvimento de sistemas para a financeira do Banco Safra (empréstimo consignado e financiamento de veículos) usando .NET e frameworks Web (APIs, Web)
Desenvolvimento em base de dados Oracle (PL-SQL)

**Pré-requisitos:**
Experiência com .NET (C#)
Experiência com APIs
Experiência com frameworks Web (Angular, React, ASP.NET)
Experiência com base de dados Oracle/MongoDB

**Benefícios:**
VA, VR, VT, PLR, salário a combinar.

**Início:**
Outubro/2019

Enviar currículo para: andre.cecchi@safra.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
