### ISSUE TITLE
[São Paulo] Back End Java na Sinqia

### ISSUE THREAD

**Issue by phmontefusco** [backend-br/vagas#1607]
Descrição da vaga
A SINQIA busca um desenvolvedor back-end com experiência em Java 8 ou superior para fazer parte da nossa equipe de produtos.

Buscamos pessoas que estejam buscando evoluir na careira e com vontade de enfrentar grandes desafios.

Local de Trabalho
O trabalho é na própria Sinqia. Estamos na região da Paulista

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico
-previdência privada
-plano odontológico

Diferenciais
Horário Flexível
Configure sua máquina como desejar (Windows ou Linux)
Sala de jogos
Possibilidade de Home Office, após período de experiência. (4 x 1)
Experiência em desenvolvimento de API padrão Rest, padrões de projeto e orientação a objetos
Requisitos
Obrigatórios:

- JDK 1.8 ou superior
- Domínio da linguagem Java 1.8 e/ou superior 
- SqlServer e/ou Oracle 
- Spring Boot
- GIT Flow
- Maven
- Microserviço
- API Rest
- Database Oracle 11g
- JUnit, Mockito
- Testes unitários e de integração
- Ter trabalhado com metodologias ágeis

Desejáveis:
- Netflix OSS
- Docker
- NoSQL (MongoDB, Redis, Elasticsearch)
- Liquibase
- Nexus
- Sonarqube
- Ter trabalhdo com In-Memory Database

Requisitos
- Formação Acadêmica em Ciência da Computação, Análise de Sistemas ou Áreas Afins;
- Experiência profissional de 3 anos em desenvolvimento de software;
- Ser colaborativo e ter habilidade para trabalhar em equipe;
- Experiência em desenvolvimento WEB e em 3 camadas utilizando Java, padrões de projeto e orientação a objetos;

Diferenciais:
- Conhecimentos de performance de aplicações

Contratação
À combinar.

Nossa empresa
A Sinqia é uma empresa de software voltada para o mercado financeiro. Estamos nas maiores instituições financeiras do Pais.

Confira o video do youtuber Primo Rico, que fez aqui na Sinqia,
Primo Rico

Como se candidatar
Por favor envie um email para karina.carvalho@sinqia.com.br , paulo.silva@sinqia.com.br e ademar.junior@sinqia.com.br com seu CV anexado - enviar no assunto: Vaga Angular Sinqia.
Pode encaminhar o link atualizado do seu LinkedIn.

Processo de Seleção
Avaliação de Currículo
Entrevista via skype
Prova online
Entrevista final presencial

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Labels
Alocado
CLT
PJ
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
