### ISSUE TITLE
[Campinas - SP] Desenvolvedor BackEnd Sênior na DAITAN

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1611]
### Sobre a empresa: Daitan

Daitan's high-quality software development services significantly accelerates time-to-market for global technology companies. The company’s expert Agile teams deliver full lifecycle software product development, maintenance and quality assurance services across today’s leading technologies, including: cloud computing and virtualization; communications, collaboration, artificial intelligence, data science, and analytics. 

Founded in 2004, Daitan serves a global client base from multiple locations. The company’s USA headquarters is located near Silicon Valley in San Ramon, California. Its Canadian headquarters and engineering Center of Excellence is located in Victoria, Canada. The company’s South American headquarters, operations and engineering Center of Excellence is located in Campinas, São Paulo, Brazil.

### Descrição: Activities

Work in a dynamic team to provide solutions for Java Web applications;
Participate in the complete cycle of development from requirements gathering, development and testing;
Participate in technical discussions with international customer;
Code development;
Help to unblock the other team members.

### Required Skills:

English Fluency Written/Spoken;
Strong background on Java (Web Development, Spring);
Experience developing Restful APIs;
Experience with Relational and NoSQL databases;
Familiarity with Linux as development environment.

### Additional Skills:

Experience with JavaScript;
Experience with using Docker in production and development;
Experience with Continuous Integration;
Experience or familiarity with distributed systems and microservices architecture;
Experience designing High Availability/Scalable systems;
Experience in CI/CD build pipelines;
Experience working on an Agile team and knowledge of agile processes (Scrum, Kanban etc);
Experience with VOIP and SIP is a plus;
Experience with Message Brokers like RabbitMQ and SQS is a big plus.

### Benefits:

Medical care (Unimed);
Dental care (Uniodonto);
Food ticket (R$ 1143,05);
Social Security;
Bonus.

### Additional information:

We are located in a commercial condominium in Campinas;
Our clients are international, so communication in English is essential;
If you are not from Campinas, we offer additional for your mobility :)

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/daitan_backend

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
