### ISSUE TITLE
#VAGA [BANCO CORA] SOFTWARE ENGINEER BACK END PLENO E SENIOR [SÃO PAULO]

### ISSUE THREAD

**Issue by LucascrMota** [backend-br/vagas#1612]
**A Cora está nascendo** e precisa de você para construir um novo banco.

**É tudo do zero!** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.

Não buscamos uma stack específica, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

![Slide1 (1)](https://user-images.githubusercontent.com/52604216/64806523-b961fd80-d569-11e9-8760-a0f1f9abe107.PNG)

**Comment by Andredgb** [comment]
Legal, Lucas! Parece um desafio bem empolgante!

Só tenho algumas dúvidas:

1. Qual é a _stack_ da vaga?
2. Qual é a faixa salarial?
3. Como me inscrevo?

**Comment by LucascrMota** [comment]
> Legal, Lucas! Parece um desafio bem empolgante!
> 
> Só tenho algumas dúvidas:
> 
> 1. Qual é a _stack_ da vaga?
> 2. Qual é a faixa salarial?
> 3. Como me inscrevo?

Fala @Andredgb , tudo certo?
Obrigado pelas perguntas, vamos lá:
1. Não temos Stack específica, queremos pessoas boas e que queiram crescer junto com a gente.
2. A faixa salarial para o cargo de pleno fica entre R$6.500,00 e R$10.000,00! Já a de Sênior está entre R$12.000,00 e R$13.000,00!
3. Para se inscrever, basta acessar o link que eu botei no mensagem inicial (este aqui: http://bit.ly/2HvIJvb )

Se tiver mais alguma dúvida, pode falar comigo!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
