### ISSUE TITLE
[FORTALEZA] Back-end Developer na KONSTROI

### ISSUE THREAD

**Issue by lilianfelismino** [backend-br/vagas#1613]
## Descrição da vaga

API Rest em .Net Core

## Local

Escritório, Fortaleza - Cocó

## Benefícios

- Plano de saúde (50%)
- VR de R$ 27,00/dia
- VT

#### Diferenciais

- 2 horas de almoço

## Requisitos

**Obrigatórios:**
- DDD
- Net Core 2
- SQL Server

**Desejáveis:**
- Docker
- Cloud (AWS / Azure)
- CI

## Contratação

CLT a combinar

## Nossa empresa

www.konstroi.com

## Como se candidatar

Por favor envie um email para talentos@konstroi.com com seu CV anexado - enviar no assunto: Vaga Back-End

## Labels

- Alocado
- CLT
- Sênior
- DDD
- Net Core 2

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
