### ISSUE TITLE
[São Paulo-SP] Java Tech Lead - Projeto iti (Itaú)

### ISSUE THREAD

**Issue by nathaliaambrosio** [backend-br/vagas#1614]
![Jy3dP1BW_400x400](https://user-images.githubusercontent.com/44304957/64820265-664a7380-d586-11e9-8819-38257ebf02b8.jpg)

📍 **Local de trabalho:**
Jabaquara, São Paulo – SP.

▶ **Atividades**
O profissional atuará no projeto iti, que é uma plataforma que reinventa o jeito de pagar, receber, comprar e vender. com o aplicativo, você pode fazer transferências ou pagamentos em poucos segundos, usando o celular. (https://iti.itau/)

•	Atuar como techlead na RT de Banking, sendo um dos membros da tríade da squad;
•	Fazer desenho arquitetural de solução de produtos bancários de forma análoga;
•	Preparar aplicações do iti para migrar para AWS;
•	Garantir que o time esteja criando toda a arquitetura utilizando microsserviços;
•	Liderar tecnicamente a squad;

💼 **Conhecimento técnico:**
•	Obrigatória experiência/conhecimento em AWS 
•	Conhecimento de Docker e Kubernetes
•	Conhecimento de backend (Java com Spring)
•	Desejável conhecimento em Front-end (Android - Kotlin e/ou iOS - Swift)
•	Ter domínio sobre a metodologia ágil aplicada ao desenvolvimento de software
•	Diferencial Certificação AWS Architecting/Developing

✍ **Contratação**
- CLT / Salário a combinar. 

**Como se candidatar**
Por favor envie um e-mail para vinicius.vieira@beit.work com seu CV anexado - enviar no assunto: Vaga TECH LEAD

Seu currículo será avaliado e fazendo sentido, entraremos em contato.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.

**Comment by sebastianjnuwu** [comment]
Seria legal estagiar
