### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na LISTENX

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1615]
### Sobre a empresa: ListenX

Somos um serviço que ajuda empresas a usar a música e a comunicação para melhorar a experiência de compra, fidelizar e atrair novos clientes. Somos especialistas em Ambientação Musical, Music Branding, Marketing Sensorial, Musica para empresas e Tecnologia. Já estamos há 16 anos no mercado e atendemos mais de 6 mil marcas em todo o Brasil e America Latina, temos alguns clientes como: Rede Hering, Smart Fit, Mahogany, Scala, Lacoste, Hope, Bio Ritmo, Levi´s, etc.

### Descrição:

Estamos com algumas instabilidades. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para bruna.valerio@vulpi.com.br :)

### O que você irá fazer?

Temos uma equipe enxuta e trabalhamos com métodos agéis, aqui você terá autonomia e espaço para opinar nos projetos definidos e na forma como irá conduzir os seus prazos e a sua Sprint, claro que tentando sempre manter o ritmo de acordo com o restante da equipe.

### Você irá:

Criar novos projetos;
Trabalhar em produtos já existentes principalmente no Listen Play;
Atuar em demandas internas;

### As habilidades necessárias:

PHP 5;
HTML e CSS;
Frameworks PHP MVC (Yii, Laravel, Codeigniter);
JavaScript;
jQuery;
MySQL;
API Rest;

### O que brilharia os nossos olhos?

HTML5 e CSS3;
Node.js;
Angular.js;
Experiência com Versionadores de Código (Git e SVN);
PHP 7;
Doctrine;
Bootstrap;
API SOAP;

### Beneficios:

Além de um ambiente descontraído, uma equipe unida e dinâmica, aqui nos temos horários realmente flexíveis, políticas de Home office, nada de dress code e momentos para interagir com a galera :)

Vale Refeição (R$20,00/dia);
Vale Alimentação;
VT ou VC;
Convênio Médio, Vida e Odontológico - Porto Seguros;
Parcerias com Pós Graduação;
Inglês in company;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Gosta de autonomia e propor novas soluções;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;

### Conheça um pouco mais sobre nós:

ListenX - Site
Instagram
LinkedIn
Facebook

### Informações complementares:

A contratação é CLT;
Estamos localizados no bairro Ipiranga, Zona Sul de São Paulo - Metrô Sacomã;

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/listenx_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
