### ISSUE TITLE
[Belo Horizonte] Desenvolvedor BackEnd Pleno na LOCKEY

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1616]
### Sobre a empresa: Lockey

A Lockey é uma plataforma online para locação de imóveis residenciais que nasceu da necessidade de simplificar o aluguel do início ao fim, beneficiando proprietários e inquilinos cansados do modelo tradicional, cheio de burocracia. 

O aluguel com a Lockey é fácil e seguro; sem papeladas, sem fiadores e com total garantia de recebimento. Colaboramos com a revolução do mercado imobiliário e buscamos ser excelentes no que nos propomos fazer, testando novas tecnologias e novas formas de pensar, aprendendo algo novo todo dia e melhorando sempre.

### Descrição:

Procuramos alguém que atue no desenvolvimento no Backend, com aplicação de técnicas de usabilidade e melhoria na experiência dos usuários.

Requisitos: Conhecimento de métodos ágeis de desenvolvimento e integração contínua; Net Core, C# , API e MySQL.

Será um diferencial conhecimento em Vue.js, HTML, JavaScript, CSS, PHP e Bootstrap

### Você vai gostar de trabalhar aqui se:

Busca uma empresa que utiliza tecnologias de ponta e tem espaço para inovação
Quer trabalhar em uma equipe engajada e comprometida
São orientados pela metodologia Scrum
Procura uma empresa com grande potencial de crescimento
Pouca hierarquia e muita autonomia

### Benefícios:

Contratação CLT
Vale refeição de R$ 23,00/dia
Plano médico e odontológico
Oportunidade de crescimento
Open café e vídeo game

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/lockey_backend

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
