### ISSUE TITLE
[Casa Forte - Recife] Back-end developer na Guava

### ISSUE THREAD

**Issue by acmh** [backend-br/vagas#1617]
## Descrição da vaga

Se você é uma pessoa desenvolvedora de back-end que gosta de código bem escrito e bem testado, gosta de um ambiente de trabalho leve, repleto de colaboração (open source incluso!), discussões profundas (porém respeitosas), e, claro, memes, vem fazer parte da Guava! (-:

## Local

Escritório, Recife - Casa Forte

## Benefícios
- Plano de saúde SulAmérica (50%)
- Seguro de vida
- Auxílio alimentação (R$ 500/mês)

**Diferenciais**

- Custeio de viagem para até duas conferências por ano⁣⁣
- Open bar de bebidas e lanches
- Macbook Pro + Monitor 27” + teclado e mouse
## Requisitos

**Obrigatórios:**

- Proficiência em pelo menos uma tecnologia de back-end
- Experiência de pelo menos dois anos em desenvolvimento web
- Inglês intermediário⁣⁣

**Diferenciais:**

- Proficiência em arquitetura de software
- Ruby
- APIs (REST/GraphQL)
- Testes automatizados
- DevOps
- Tecnologias de front-end
- Curso superior na área de tecnologia
## Contratação

CLT com salário entre R$ 5,7k a 7,7k

## Nossa empresa

Somos um estúdio de software ousado, que nasceu com a missão de unir sistemas sólidos a interfaces fluidas. Nosso objetivo é resolver problemas reais através de software útil, cativante e de alta qualidade. Estamos há mais de oito anos no mercado e neste período construímos produtos que vão desde MVPs para startups até softwares de alta demanda. Com clientes no Brasil e nos EUA, já atuamos em áreas tão diversas como engenharia elétrica, saúde e até *e-commerce* de lingerie. Saiba mais sobre a Guava em https://guava.software/about.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo. E-mail para contato em caso de não haver resposta: hello@guava.software

## Como se candidatar

É só mandar seu currículo, portfólio, Github, LinkedIn e/ou o que mais você achar relevante para vagas@guava.software (vaga aberta até 23/09).

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- ⚖️ CLT
- 💰 5k-10k

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
