### ISSUE TITLE
[São Paulo] Senior Software Engineer (Node/Servless) na Kovi

### ISSUE THREAD

**Issue by Raffesmind** [backend-br/vagas#1619]
**About Kovi**

At Kovi, we challenge the inertia of the market to allow people to get around as efficiently and cheaply as possible. To do this, we use state-of-the-art technologies to provide access to more straightforward, cost-effective and secure solutions. With this vision is how we provide the best solutions to our drivers for changing mobility in the world.

As we embark on the next chapter of realizing this vision, we are looking for seasoned developers to join our team. Our tight-knit team is committed to develop user-focused, product-minded technologists who are straightforward to solve problems and high on performance. We value accountability and meritocracy and fully own our successes and failures. Most importantly, we believe that people do their best work when empowered. If you are on a journey to find a team that crafts intelligent, cutting edge solutions while having fun together, we are your destination.

**About this position**
As an Engineer, you will be responsible for using creative thinking & raw innovation to drive the future evolution of the entire Kovi Core system stack, from our Rental System to our Driver Behaviour algorithm. You’ll be working on software projects at different stages of maturity and mould them into compelling user-facing products creating impact on our users live.

Our ideal candidate is someone who lives and breathes distributed systems, has a strong background in JavaScript, is familiar with Serverless technologies and is exceptionally comfortable with APIs.

**You’ll be directly responsible for**
Designing and building best in class Serverless application APIs
Maintaining and nurturing a cohesive architecture on rapidly expanding and evolving projects
Implementing simple, extensible integration strategies with 3rd party technologies and services
To excel in this role, you MUST be able to be good at
Building incremental solutions that are backward compatible
Presenting complex ideas and approaches in simple communicable terms across engineering and management levels
Proposing solution alternatives, analyzing tradeoffs and making high impact product and engineering decisions
Balancing short-term execution with longer-term concerns such as extensibility
Rapidly Iterating on solutions and continuously delivering software with automated unit/integration tests
Collaborating to fellow engineers and embodying development best practices
Demonstrating flexibility and efficiency working with remote teams

**Requirements**
Minimum 5 years experience in developing and supporting distributed APIs
Awesome knowledge in programming fundamentals, high quality and performance.
Mastery in coding custom JavaScript solution using Node.js and modern ES2017
Expertise with cloud architectures based on public cloud services
Working knowledge of networking concepts, protocols and security (TCP/IP, UDP, HTTP, NTP, DNS, TLS etc)
Working knowledge of Continuous Integration and Continuous Deployment (CI/CD)
Working knowledge of Git and some working flow with Git (Git Flow, Gitlab flow)
Experience with serverless architecture (Lamba) and/or container architecture (Docker / Kubernetes)
Comfort with dynamic startup environments where change is constant and there is a need to be largely self-guided on complex problems
Comfort working with multiple programming languages in a polyglot environment
Attention to detail and a high degree of individual ownership
Exceptional written and verbal communication skills

**Language and Location**
We are a Portuguese speaking company. This is written in English because 1) we value diversity and thus welcome foreign candidates, and 2) if you are Brazilian you need to be fluent in English in order to learn the most from the rest of the world.

This position is for our São Paulo office, near Chacara Santo Antonio.

Important Our recruitment process starts at the application form! If you really wish be a part of our team, endeavor to do well at this stage of the process. We analyze all the candidates individually. Yes, we do read all applications and we’ll reply even to those who won't follow the process.

**Benefits**
Working here is cool AND you get the following:

**Competitive salary package.**
Meal allowance ("ticket refeição and/or ticket alimentação").
Transportation vouchers or Parking lot for your car
Fuel or public transportation allowance.
Health insurance
Life insurance
Free beer every Friday
Very fun, collaborative, and fast-paced work environment with a full of smart and ambitious people.

**To start the job application:**
https://kovi.breezy.hr/p/ebeec12b95de-senior-software-engineer-nodejs-serverless

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
