### ISSUE TITLE
#VAGA [BANCO CORA] SOFTWARE ENGINEER BACK END PLENO E SENIOR [SÃO PAULO]

### ISSUE THREAD

**Issue by Andredgb** [backend-br/vagas#1620]
A Cora está nascendo e precisa de você para construir um novo banco.

**É tudo do zero!** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.

Não buscamos uma stack específica, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

**Comment by fredmelo1** [comment]
Tem mais informações sobre salário e/ou beneficios?

**Comment by Andredgb** [comment]
Olá, Fred.
Os salários podem chegar à 13 mil para Seniores e 10 mil para pleno + benefícios. 
A contratação é CLT.

**Comment by fredmelo1** [comment]
qual região de SP?

**Comment by klisostom** [comment]
Essa vaga é show! Já me candidatei e aguardando o feedback da empresa.

**Comment by Andredgb** [comment]
> qual região de SP?

![image](https://user-images.githubusercontent.com/55258557/65074817-f3694000-d96b-11e9-9229-ab7ed9989010.png)

**Comment by luicesar** [comment]
Aceita negociar para o tipo de contrato PJ  ?

**Comment by Andredgb** [comment]
> Aceita negociar para o tipo de contrato PJ ?

Infelizmente a empresa não aceita este tipo de contrato =\

**Comment by 0-9194** [comment]
Existe a possibilidade de trabalho remoto?

**Comment by Andredgb** [comment]
> Existe a possibilidade de trabalho remoto?

Para esta oportunidade apenas é possível trabalhar de forma presencial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
