### ISSUE TITLE
[São Paulo] Python Developer Jr na MOL

### ISSUE THREAD

**Issue by renatodotdev** [backend-br/vagas#1622]
# Python Developer Jr.

A MOL é uma startup que busca quebrar o paradigma do sistema judiciário através da tecnologia. Estamos buscando um desenvolvedor para nos ajudar na parte de obtenção dos dados e automatização de fluxo complexos de tratamento de dados.

## Oportunidades:

- Trabalhar em um ambiente inovador e dinâmico;
- Reais possibilidades de crescimento internamente;
- Trabalhar em projetos Python bem estruturados;
- Aprender e trabalhar com tecnologias de importantes do mercado, como Apache Airflow, AWS Cloud, Serverless, Jupyter.

## Responsabilidades:

- Desenvolver fluxos de dados programados;
- Criar integrações com sistemas internos e externos;
- Otimizar projetos e fluxos de dados já existentes;

## Requisitos:

- Graduação completa ou em curso na área de exatas ou background em matemática;
- Bons conhecimentos em programação Python;
- Utilização de Git para versionamento de código;
- Manipulação de dados em SQL;

## Diferenciais:

- Bom entendimento de conceitos de programação como programação orientada a objetos, programação funcional, teste unitários;
- Conhecimento da AWS Cloud;
- Conhecimento em outras linguagens de programação;
- Ter resolvido problemas de dados utilizando programação;

Hoje estamos localizados na Vila Olímpia, no Cubo, o principal Hub de inovação da America Latina, e oferecemos, além do ambiente dinâmico e inovador, uma real oportunidade de crescimento, horário flexível e salário compatível com o mercado.

**Comment by PedroHamzehT** [comment]
Aonde eu posso aplicar / me candidatar?

**Comment by renatodotdev** [comment]
@PedroHamzehT pode mandar seus contatos para meu email, por favor: renato.romao@mediacaonline.com

**Comment by vmesel** [comment]
Já pensou em colocar esta vaga no [PyJobs](https://www.pyjobs.com.br)

**Comment by daviwesley** [comment]
aceita remoto?

**Comment by tsoaresclick** [comment]
Aceito, dependendo de como trabalha




Obter o Outlook para Android







On Mon, Sep 23, 2019 at 6:32 PM -0300, "Davi Wesley" <notifications@github.com> wrote:












aceita remoto?
