### ISSUE TITLE
[São Paulo] Nodejs Developer na PIXTER

### ISSUE THREAD

**Issue by RecruiterFMonteiro** [backend-br/vagas#1624]
## Descrição da vaga

Temos uma oportunidade de desenvolvedor, para integrar equipe de desenvolvimento Web,, onde você terá a oportunidade de trabalhar com Nodejs em um time de pessoas incríveis!

## Local

São Paulo - Presencial.

## Requisitos

**Obrigatórios:**

- Interesse em aprender novas tecnologias e compartilhar conhecimento;
- Gostar de trabalhar em equipe e ser comunicativo(a);
- Experiência no desenvolvimento de projetos em php e node.js ;
- Experiência com jquery / angularjs ;
- Desenvolvimento e consumo de api rest / soap ;
- Conhecimento em metodologia ágil – scrum / kanban ;
- Conhecimento em mysql, mongodb ou dynamodb ;
- Experiência em ferramentas para controle de versão (git) ;
- Conhecimento da ferramenta jira ;
- Capacidade de analisar escopos e demandas, também sugerir soluções.

**Desejáveis:**
- Incentivamos troca de conhecimento;
- Trabalho em equipe;

## Contratação

PJ - Salário a combinar.

## Nossa empresa

Somos uma boutique de software que tem em seu core desenvolvimento, inteligência e usabilidade.
Filtramos projetos que têm fit cultural com o que acreditamos e trabalhamos com poucos clientes.
Nos últimos três anos acumulamos cases de sucesso com empresas de grande porte.
Veja mais em: https://pixter.com.br/

## Como se candidatar

Por favor envie um email para fernanda.monteiro@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Back Nodejs

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
