### ISSUE TITLE
Senior JS developer (Remote)

### ISSUE THREAD

**Issue by aalvarezbluecoding** [backend-br/vagas#1625]
Who are we looking for

We are looking for a Senior JS developer to work with one of our clients. We need someone who is smart, can understand problems quickly, is enthusiastic and willing to actively participate in the improvement of our development processes.

Job Details

Remote (EST hours)

Full time (30 - 40 hours/week)

US$20 - US$25 per hour
Our Requirements

    100% English fluency.
    Strong experience with MEAN stack. (MongoDB, Express.js, Angular, and Node.js)
    Strong experience with AWS.
    Experience with JSON.
    Experience with Restful APIs.

Apply here or send the link to a colleague:   https://www.bluecoding.com/job/senior-js-developer13

**Comment by hperezbaranda** [comment]
How can I apply for these job?

**Comment by aalvarezbluecoding** [comment]
> 
> 
> How can I apply for these job?

Hi Hector, you can apply by clicking on the link on the post or send your CV to hr@bluecoding.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
