### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Full Stack para OSF GLOBAL SERVICES 

### ISSUE THREAD

**Issue by carolina-brand** [backend-br/vagas#1626]
## Descrição da vaga

Oportunidade Desenvolvedor(a) Full Stack em uma empresa global!

## Local

Escritório, São Paulo.

## Benefícios

Bradesco Saúde (pago 100% pela empresa)
Seguro de vida
VR de R$ 28,00/dia
Bônus Educação de R$150,00/mês
Bônus Esporte de R$40,00/mês
Programa de mentoring
Certificações pagas pela empresa
Plano de carreira bem delineado (avaliação de performance de 4 em 4 meses)

#### Diferenciais

Empresa global presente em mais de 19 países.

## Requisitos

Obrigatórios:

Sólida experiência com Java Web;
Experiência com Angular 2+.

## Contratação

CLT + Benefícios (citados acima)

## Nossa empresa

OSF Global Services is a trusted technology consultant and technology integrator enabling companies to succeed over the greatest challenges in the world’s rapidly changing business environment. With expertise in cloud and mobile application development, enterprise CRM solutions, leading ecommerce platforms and integrated content management solutions.

## Como se candidatar

Por favor envie um email para carolina.brand@osf-global.com com seu CV anexado - enviar no assunto: Vaga Full Stack

## Labels

Alocado
CLT
Pleno
Senior
Angular
Java
Full Stack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
