### ISSUE TITLE
[São Paulo-SP] iOS Mobile Developer - AMARO

### ISSUE THREAD

**Issue by nathaliaambrosio** [backend-br/vagas#1627]
## Empresa
AMARO is a digitally native fashion brand and technology company with the mission to empower humans to express their authentic self.

AMARO is looking for a talented iOS Mobile Developer to keep innovating and improving their iOS app, leveraging their e-commerce platform's JSON API. The ideal candidate has solid experience in iOS development.

This is a highly analytical role that requires a driven, self-reliant and generalist hacker.
Make sure to check out https://amaro.com to get a sense of what they are building at AMARO.

## Responsibilities

·        Create new features for AMARO's iOS app using the Swift programming language
·        Maintain existing features
·        Create software documentation
·        Review code written by other team members and suggest improvements
·        Pro-actively participate in the product roadmap working with the Product team
·        Plan and deploy new releases in production
·        Embrace Test-Driven Development (TDD)
·        Optimize App’s performance
·        Improve/maintain crash-free metric
·        Reduce total App footprint
·        Implement automated tests
·        Write unit tests and achieve high code coverage
·        Help improve App’s rating

## Qualifications

·        Professional or academic experience in software development
·        Knowledge in software engineering best practices and trends
·        Extensive knowledge in iOS app development, especially in Swift
·        Intermediate or Advanced level of English

**Personality:**

·        Highly analytical and focused
·        Passion for technology, e-commerce and startups
·        Entrepreneurial, driven and proactive
·        Excellent technical communication skills

We take hiring very seriously. Interviewing with us may include phone interviews, practical tests, on-site interviews and case study. Although we are unable to follow-up with each and every applicant, we do our best to run a thorough process for candidates with whom we identify a potential fit.

## Posição
Sênior

## Localização
Av. Paulista - São Paulo/SP

## Tipo de contratação
CLT

## Benefícios
AM, AO, VR, VA, Estacionamento, Auxílio farmácia, Gympass, descontos nos produtos Amaro, frutas 2x/semana, Yoga 1x/semana 

## Como aplicar
Envie seu currículo para nathalia.ambrosio@beit.work

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
