### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack na DR LAVA TUDO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1628]
### Sobre a empresa: Dr. Lava Tudo

"Plataforma tecnológica de prestação de serviço atuante em 140 cidades do Brasil, com unidades em Minas Gerais, São Paulo, Rio de Janeiro, Brasília, Recife e Goiânia. Vendemos conforto e bem estar aos nossos clientes através de Home Improvement, com a lavagem e impermeabilização de estofados e couros, limpeza de ar condicionado e itens diversos comuns em seguimento residencial e corporativo."

### Descrição

Ocupações do cargo
Gestão da equipe de desenvolvedores;
Introdução de melhores práticas de desenvolvimento ágil;
Aplicação de novas tecnologias e tendências na empresa;
Colocar a mão na massa e desenvolver junto com a equipe.

### Requisitos Necessários

Proficiência em C#;
Proficiência em Javascript;
Conhecimento em DevOps;
Conhecimento em Métodos Ágeis.

### Seria legal se

Experiência com BI;
Experiência com liderança técnica;
3+ anos de atuação no mercado.

### Benefícios

Vale alimentação ou vale refeição;
Vale transporte ou auxílio combustível;
Plano médico;
Plano odontológico;
Convênio com farmácia (desconto em produtos);
Ambiente jovem e descontraído;
Oportunidade de trabalhar com liderança de equipe.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/drlavatudo_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
