### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Sênior na CÂMBIO NUTS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1629]
### Sobre a empresa: Câmbio Nuts

A Câmbio Nuts é uma fintech do setor financeiro, que visa a troca do real por moeda estrangeira, de acordo com o melhor momento de compra no mercado financeiro. Criada em 2019, e alocada no WeWork SP, a Câmbio está em ritmo acelerado de crescimento e em busca de um desenvolvedor sênior, que curta muito desafios e esteja disposto a vestir a camisa do negócio. Se identificou? Então se cadastra aí :)

### Requisitos necessários:

Experiência com PHP;
Experiência com Javascript e React;
Experiência com MySQL;
Experiência com arquitetura de sistemas;
Conhecimento em AWS.

### Seria legal se:

Experiência Mobile;
Conhecimento em Python.

Estamos em um momento de desenvolvimento acelerado e buscamos por um profissional que ame desafios, esteja disposto a vestir a camisa do nosso negócio e queira crescer junto com a Câmbio! Aqui você terá a oportunidade de trabalhar com autonomia, ter participação ativa em tomada de decisões e pensar estrategicamente para o nosso crescimento. Curtiu? Então não perde tempo e vem pra Câmbio!

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/cambionuts_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
