### ISSUE TITLE
[São Paulo] Back-End Developer na RADAR PROFISSIONAL

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#163]
## Descrição da vaga

Desenvolvimento Back-End

## Local

São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- VR de R$ 17,50/dia
- Auxílio creche
- ...

#### Diferenciais

- Clima Amistoso;
- Desenvolvimento Profissional

## Requisitos

**Obrigatórios:**
- Experiência com análise de requisitos;
- Desenvolvimento e testes de aplicações JAVA;
- Experiência com APIs REST
- Bancos de dados no SQL (Cassandra, ElasticSearch etc)
- Experiência em Arquitetura de microserviços 

**Desejáveis:**

- Conhecer outras linguagens de programação;
- Conhecimento em GIT;
- Conhecimento em banco de dados SQL
- Conhecimento em sistema Linux

## Contratação

##CLT

## Como se candidatar

Por favor envie um email para recrutadora@radarprofissional.com.br com seu CV anexado - enviar no assunto: Vaga Back End

## Labels

- BackEnd
- CLT
- Back end Developer 
- Radar Profissional
- Senior
- Especialista

**Comment by vanilsonsantos** [comment]
possibilidade de trabalho remoto?

**Comment by RADARProfissional** [comment]
Infelizmente não. 

 

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Vanilson Magalhães Santos <notifications@github.com> 
Enviada em: quarta-feira, 9 de maio de 2018 10:24
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [São Paulo] Back-End Developer na RADAR PROFISSIONAL (#163)

 

possibilidade de trabalho remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
