### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na CONNECTION COMUNICAÇÃO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1630]
### Sobre a empresa: Connection Comunicação

Somos uma agência e nosso principal produto é um sistema de atendimento para empresas via mensageiro instantâneo. Apesar de estarmos neste mercado há cerca de 2 anos, já temos grandes clientes e uma grande perspectiva de clientes. Neste ano, crescemos mais de 100% e a expectativa para próximo ano é crescermos mais 300%. Nossa missão é fazer com que a informação de nosso cliente seja transmitida de maneira ágil e eficiente e é isso que entregamos. Para isso, temos uma equipe com profissionais competentes e dedicados a cumprir metas e conquistar desafios.

### Descrição: Quer saber o que você fará aqui conosco?

Aqui na Connection Comunicação você irá desenvolver, codificar e testar funcionalidades de nossa aplicação. Irá auxiliar nosso time de produto a entregar uma experiência sensacional para nossos clientes.

### Por que você deveria se juntar a nós?

Somos uma empresa que que tem crescido muito e será ótimo ter mais alguém com o desejo de crescer. Você terá um ambiente sensacional para trabalhar, estamos alocados em um Co-working onde você poderá trocar experiências e aprender com outras empresas no cotidiano. 

### Benefícios:

Vale transporte ou estacionamento
50% do plano de saúde Sul América (opcional)
Cozinha
Área de lazer com mesa de ping pong e bilhar, bicicletário.

Ou seja, nós temos tudo para você querer ficar conosco.

### E sabe o que você precisa saber?

Laravel PHP
Socket 
javascript 
Nodejs
Conhecimento de documentação
 
### Agora, seria show se você soubesse...

Bot 
Android
Java

### Pois assim você avança algumas casa na disputa.

E sabe como você conquista a gente?
Com proatividade, honestidade, comprometimento, boa vontade e flexibilidade. E você se sairá muito bem se engajar conosco, se adaptar e querer crescer.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/connection_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
