### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Back-End Jr na Ingresso.com

### ISSUE THREAD

**Issue by f2l2pe** [backend-br/vagas#1631]
O time de Back End. está uma vaga aberta para Desenvolvedor Jr !

Escopo da vaga:

- O candidato irá trabalhar no desenvolvimento de projetos em ambiente web na linguagem
.NET com banco de dados MySQL, MongoDB e nuvem da AWS
- Dar suporte a áreas para correção dos problemas apresentados
- Levantamentos Técnicos
- Plantões em forma de revezamento

Escolaridade:
- Ensino Superior formado ou cursando em Análise de Sistemas, Engenharia de Software ou
cursos afins;
- Inglês Internediário

Conhecimentos técnicos:
- Experiência em desenvolvimento .Net (C#)
- Orientação a Objetos 
- Javascript
- WebAPI
- GIT
- Banco de dados (MySQL)
- Testes

Conhecimentos desejáveis:
- MongoDB
- Nuvem AWS
- Jenkins
- Scrum
Habilidades Interpessoais:
- Saber trabalhar em equipe;
- Focado;
- Procurando sempre se atualizar em tecnologias e extremamente responsável quanto a metas
e prazos;
- Ser organizado;
- Dinamismo e proatividade;
- Aberto a críticas;
- Gostar de estudar;
- Gostar de desafios;

Beneficios:
- VT
- VR
- Previdencia privada
- Plano de Saúde e Odonto

Contratação CLT
Remuneração : R$ 3600,00

Caso você se encaixe no perfil anexo ou conheça alguém, favor enviar o currículo para rh@ingresso.com colocando no Assunto do email Desenvolvedor Back End Jr.

**Os emails que não tiverem no assunto o NOME COMPLETO da vaga serão descartados.**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
