### ISSUE TITLE
[São Paulo] Desenvolvedor Java na CONFITEC

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#1632]
Somos uma empresa de Tecnologia da Informação, especialista no mercado de Seguros e buscamos pessoas apaixonadas por tecnologia para fazer parte do nosso time interno. 

**Para fazer parte do time, você precisa conhecer:**
Java
Spring Framework, Spring boot
NHibernate
Banco de dados SQL

Design Patterns
C.I / C.D

**Você se destaca se:**
Tiver conhecimento em linguagem Python.
Conhecimento em Cloud (AWS).
Conhecimento em algum banco de dados não relacional (Mongo DB - Cassandra ou Dinamo DB).​

**_Contratação:_** CLT

**Local:** zona sul de SP- ao lado da estação Morumbi da CPTM/ Shopping Morumbi.

**Curiosidades:** além dos benefícios padrões (VT, VR, Assistência médica e odonto), oferecemos: PLR, acesso ao DevMedia, café da manhã toda sexta-feira, festa de aniversariantes do mês, ginástica laboral, campeonatos de poker e futebol, Day off no mês do seu aniversário e o Dress Code é livre. 

Se interessou? Envie cv com pretensão para curriculos@confitec.com.br

Boa sorte!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
