### ISSUE TITLE
[Remoto] Fullstack Developer na Trio

### ISSUE THREAD

**Issue by mgkaefer** [backend-br/vagas#1638]
### About the job
Trio is more than just a group of software engineers solving problems. We are people who believe in innovation, global responsibility, and fair business. We are passionate about overcoming challenges with software engineering, forward-thinking, cutting-edge technology, and creative ideas to produce amazing products.

We value intelligence, professionalism, and integrity among other values in our team members and are constantly looking for like-minded people to join Trio. We believe that we do more than allocating software engineers for our client's projects - we contribute towards technological progress and innovation by helping businesses achieve their goals for growth by providing users with bespoke software.

At Trio our greatest assets are our engineers! We value their knowledge and skillset- as we collaborate, we grow from one another! Join us to discover opportunities for career growth and a competitive software engineer salary.

We are looking for a Senior Python Engineer who is passionate about designing and creating wonderful software systems using Python and other backend technologies.

### Minimum qualifications
- 5+ years of software development experience
- Good knowledge of Docker, Flask and REST.
- Has experience working on a team and collaborating
- Fluent in English

### Responsibilities:
- Design and implement a microservice-based application using Python, Django, Flask and related frameworks, in AWS or Azure, Docker.
- Create a scalable, testable, documented application so that we can grow the product over time
- Work independently to deliver software on time
- 5+ years of software development experience
- 5+ years of experience in building and deploying web applications using the Python ecosystem like Django, Flask
- Experience in building applications in the cloud, AWS or Azure, using containers like Docker
- Experience building and consuming APIs to interact with front end SPA and other applications using REST or GraphQL
- Experience in working in an agile environment to quickly iterate and deliver features to users

### We are looking for an Engineer who:

- Passionate and proven in-depth experience in SOLID and Clean code principles
- A passion for Quality. You want to be part of the team to produce the highest quality software products.

### Benefits
- Work Wherever You Want
- Vacations and Paid Holidays

[More info](https://trio.dev/join/python-developer-remote)
[Apply to the job](https://trio.dev/application/python-developer-remote)

**Comment by vmesel** [comment]
Já pensou em colocar esta vaga no [PyJobs](https://www.pyjobs.com.br)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
