### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Fullstack no CrossX

### ISSUE THREAD

**Issue by rodrigopriolo** [backend-br/vagas#164]
## Experiência
Pleno

## Local

Escritório, Vila Mariana, São Paulo

## Requisitos

**Obrigatórios:**
- Conhecimentos sobre php oo (avançado)
- Frameworks php padrões de mercado (laravel(5.0+), yii2 etc.)
- Banco de dados sql (mysql e afins)
- Sistemas de versionamento de código (git)
- Conhecimentos em html, css e js
- Inglês técnico

**Desejáveis:**
- Conhecimentos de design patterns
- Conhecimentos sobre node.js, javascript oo, javascript funcional, tdd
- Conhecimentos sobre mongodb
- Conhecimentos em frameworks javascript (angular, react, vue)
- Automatização de deploy e integração continua
- Experiência com servidores aws
- Pré-processadores css (less, sass, stylus)
- Ferramentas de automação de tarefas (gulp ou grunt)
- Cultura ágil, lean e de entrega contínua

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup que tem um aplicativo e sistema para o ramo de CrossFit e estamos expandido para outras áreas.

## Como se candidatar

Por favor envie um email para trampos@smartside.com.br com seu CV anexado - enviar no assunto: Vaga Fullstack

## Labels

- Alocado
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
