### ISSUE TITLE
[São Paulo] Back-End Developer .net na RADAR PROFISSIONAL

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#1640]
Estamos a procura de profissional para atuar como desenvolvedor .net, com experiencia minima de 2 anos de atuação, em um projeto determinado.

##Local: 
Escritório - São Paulo, Vila Leopoldina.

##Benefícios:
Descanso remunerado semestral

##Requisitos:
•	Superior completo; 
•	Imprescindível experiência na função e com C#, .NET, ASP.NET MVC, ASP.NET WebAPI, Orientação Objeto (POO), LINQ e SQL Server;
•	Será considerado como diferencial, profissionais com experiência em EntityFramework, Code First/Migrations, Padrões de Projetos, SCRUM, Controle de Versão Visual Studio Online, TDD, ORACLE e Automatização de Testes.

##Como se candidatar:
Por gentileza encaminhar para o e-mail vagas@radarprofissional.com.br com CV atualizado - enviar no assunto: Desenvolvedor .NET.

##LABELS
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
