### ISSUE TITLE
#vaga [Engenheiro de Software] [Banco Digital Cora] [São Paulo]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#1641]
O Cora está nascendo, e precisa de você para construir um banco.

**_É tudo do zero._** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.

**Não buscamos uma stack específica**, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime **CLT**, para atuar de forma presencial no **WeWork**, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

**Comment by LucascrMota** [comment]
> O Cora está nascendo, e precisa de você para construir um banco.
> 
> **_É tudo do zero._** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.
> 
> **Não buscamos uma stack específica**, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.
> 
> A contratação será feita em regime **CLT**, para atuar de forma presencial no **WeWork**, em São Paulo. Para mais informações, acesse a página da vaga.
> 
> Página da vaga: http://bit.ly/2HvIJvb

@AndreBorim , você pode disponibilizar a faixa salarial da vaga? Também gostaria de saber em qual Wework fica a empresa!

**Comment by AndreBorim** [comment]
> > O Cora está nascendo, e precisa de você para construir um banco.
> > **_É tudo do zero._** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.
> > **Não buscamos uma stack específica**, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.
> > A contratação será feita em regime **CLT**, para atuar de forma presencial no **WeWork**, em São Paulo. Para mais informações, acesse a página da vaga.
> > Página da vaga: http://bit.ly/2HvIJvb
> 
> @AndreBorim , você pode disponibilizar a faixa salarial da vaga? Também gostaria de saber em qual Wework fica a empresa!

Boa noite! O salário pode chegar à 13k, para os seniores. E o trabalho é presencial no WeWork da Faria Lima.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
