### ISSUE TITLE
[Cascavel] Back-End Developer na [ ClickAgende]

### ISSUE THREAD

**Issue by tsoaresclick** [backend-br/vagas#1642]
Procuro desenvolvedor Back-End em node.js *PLENO* ou *SÊNIOR*
Para tralhar local

Tipo de contrato 
CLT
PJ

**Comment by gabrielrab** [comment]
Olá gostaria de me candidatar. Qual e-mail para contato? Caso queria mais informações entre em contato rabelogabriel72@gmail.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
