### ISSUE TITLE
[São Paulo] Desenvolvedor Python no Carteira Global

### ISSUE THREAD

**Issue by lucasbastianik** [backend-br/vagas#1645]
## Descrição da vaga

Estamos procurando um desenvolvedor Backend que também esteja em busca de transformar a forma com qual os brasileiros lidam com seus investimentos. Desenvolvedor este que participará de toda a criação do produto, podendo ajudar nas discussões e decisões que serão tomadas, assim como tendo a total liberdade para propor inovações e melhores formas de atender nossos clientes.

Nós temos um alto nível de exigência dado que somos uma Startup e estamos preparando todos para se tornarem futuros sócios e líderes do Carteira Global. Acreditamos que times menores com pessoas extremamente qualificadas é muito mais produtivo que times grande sem tanta qualificação.

Se esse é o tipo de propósito, cultura e ambiente que você está procurando, junte-se a nós.

Exemplos do dia a dia de um desenvolvedor Backend no Carteira Global:
- Participação de reuniões e cerimônias do time: retrospective, planning e daily's
- Interação com as Telas que são desenvolvidas pelo Frontend
- Desenvolvimento de novas funcionalidades e manutenção
- Troca de experiências e conhecimentos através de Design Reviews, Code Reviews, Pull Requests, discussões técnicas
- Participação da melhoria dos processos e fluxos de trabalhos

## Local

Acabamos de mudar para uma sala privativa em um coworking novinho (_padrão WeWork_) que fica 5 minutos da estação Brigadeiro de metrô.
Ambiente moderno que inspira transformação e inovação, proporcionando um ótimo local para trabalho e networking com outras startups, além de constantes eventos, encontros e meetups que acontecem.

## Benefícios

- Política de Stock Options (participação na empresa)

## Requisitos

**Obrigatórios:**
- Sólido conhecimento em Python
- Sólido conhecimento em APIs e requisições HTTPs
- Sólido conhecimento em versionamento de código utilizando Git e boas práticas
- Habilidades em se comunicar de forma clara em revisão de código de outras pessoas

**Diferenciais:**
- Experiência com Serverless
- Experiência com Peewee ou outros ORM’s
- Experiência com ElasticSearch
- Conhecimento em JavaScript

## Contratação

PJ a combinar

## Nossa empresa

O Carteira Global é uma plataforma de consolidação de carteira de investimentos multi instituição financeira. Nosso propósito é ajudar o brasileiro a investir melhor, mostrando as contas que ninguém faz e, assim, acabar com a concentração bancária. Prezamos muito pela qualidade de design, desde o fluxo até a interface, que, quando implementado, traduz a qualidade do desenvolvimento, desde o planejamento, passando pelo front-end e back-end até a infraestrutura.
Somos extremamente unidos e temos uma orientação bem forte para team-work, transparência e participação no desenvolvimento do produto.    

## Como se candidatar

Envie um e-mail para tech@carteiraglobal.com com o assunto [Backend] Desenvolvedor Python.

## Tempo médio de feedbacks

Nossos processos são rápidos, geralmente levamos menos de 1 semana para responder e gostamos de dar um feedback construtivo além de simplesmente falar se você foi aprovado ou não.

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Sênior

**Comment by vmesel** [comment]
Já pensou em colocar esta vaga no [PyJobs](https://www.pyjobs.com.br)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
