### ISSUE TITLE
[Florianópolis/Remoto] Desenvolvedor Full Stack na  Datarisk

### ISSUE THREAD

**Issue by gustavodgbernardo** [backend-br/vagas#1646]
# Sobre a empresa: Datarisk

A Datarisk é uma empresa focada em resolver problemas utilizando as mais modernas ferramentas de machine learning. Desenvolvemos produtos para análise de dados e imagens prevendo fraudes e inadimplências, otimizando cobranças e aumentando vendas. Tornando o processo de decisão dos nossos clientes mais rápido, ágil e simples.  
Se você gosta de desafios, grandes quantidades de dados, modelagem estatística, aprendizado de máquina e quer trabalhar com ótimas pessoas, você é bem-vindo!

# Descrição: Qual será o seu papel?

Suas principais responsabilidades serão criar, manter, implantar nossos algoritmos, dar manutenção e propor melhorias na nossa plataforma.

# Esperamos que você tenha experiência com: 

- Python 
- Git 
- AWS 
- Docker
- Boas práticas de programação.

# Vamos ficar felizes se você conhecer: 

- Scala
- Continuous Delivery
- Hadoop
- Hive
- Spark
- ML-derived languages (ocaml, haskell)
- Machine Learning

# Você vai amar trabalhar aqui se:

- gostar de ambiente de startup 
- crescimento acelerado
- Gostar de aprender
- Trabalhar como foco em resultados

# Benefícios

- Horário flexível 
- Trabalho remoto 

# Informações Complementares:

- Contratação tipo PJ;
- Vaga presencial/remoto;
- Estamos localizados no bairro Santa Mônica Florianópolis.

Se tiver interesse enviar cv para vagas.ti@datarisk.io

**Comment by vmesel** [comment]
Já pensou em colocar esta vaga no [PyJobs](https://www.pyjobs.com.br)

**Comment by pdrgds** [comment]
Ainda tá aberta?

**Comment by boechat107** [comment]
> Ainda tá aberta?

Yes!
A issue vai ficar aberta enquanto a vaga estiver aberta.
