### ISSUE TITLE
[São Paulo] Back-End Developer NodeJS AWS na fintalk.ai

### ISSUE THREAD

**Issue by Cristianasp** [backend-br/vagas#1647]
**Sobre a vaga**

**Local** 🌆
Zona Sul, São Paulo, SP

**Forma de Trabalho** 💻
Presencial e eventualmente remoto

**Regime de Contratação** 💰
PJ

**Atividades e Responsabilidades** 💪
• Concepção, desenvolvimento, manutenção e melhoria contínua de nossos diversos projetos
• Backend em NodeJS
• Integração com banco de dados não relacional (DynamoDB)
• Tudo rodando na AWS (serverless)

**O que buscamos nas pessoas** 😍
• Vontade de trabalhar numa startup onde criamos tudo juntos
• Boa atitude, maturidade e comprometimento
• Competência técnica em programação

**Requisitos obrigatórios** 👊
• Experiência comprovada em NodeJS 
• Conhecimento em banco de dados relacionais e não-relacionais (SQL, Mongo, DynamoDB)
• Conhecimento sólido em segurança de APIs (tokens, rotas)
• Experiência com frameworks e bibliotecas de NodeJS (Restify, Hapi, Promises)
• Experiência com desenvolvimento em ambiente de nuvem (AWS)

**O que oferecemos** 😁
• Oportunidade única de carreira
• Participação nas decisões e nos desenhos dos projetos
• Ambiente descontraído
• Possibilidade de crescimento profissional e financeiro, acompanhando o da empresa, inclusive com possibilidade de bônus e participação em equity

**Sobre a empresa**

Somos uma startup que usa os Instant Messengers para, através de VOZ, oferecer inúmeros serviços às PESSOAS. 👨‍👨‍👧‍👦

Tudo acontece através de voz e mensagens de texto via WhatsApp, Messenger, Telegram, in-app, in-web ou qualquer outro serviço interativo. 👍

Ou seja: ZERO APP, ZERO ESPAÇO NO CELULAR, ZERO USO DE DADOS, ZERO CURVA DE APRENDIZADO, ZERO CUSTO DE GESTÃO DE DOWNLOAD E ATUALIZAÇÃO. 😍

Criamos uma plataforma agnóstica que permite conectar inúmeros Instant Messengers usando voz, texto, vídeos, imagens etc., com inúmeras soluções de Machine Learning, Speech to Text, Text to Speech, e inúmeros gateways de comunicações e serviços, conectando sua empresa de forma rápida, simples, e robusta. Seus serviços aways-on. 💻

Mas não somos somente uma boa idéia, nosso negócio é EXECUÇÃO. Temos paixão por RESULTADOS fortes e importantes e temos track records de sucesso no mercado. 💪

E falamos português! Essas tecnologias existentes foram feitas para o inglês que tem uma estrutura mais diretiva, imperativa. No PORTUGUÊS o jogo é diferente 😉

**Como se candidatar**
Envie seu currículo para vagas@fintalk.ai 👏👏👏

**Comment by Cristianasp** [comment]
Vaga continua aberta!

**Comment by GuiziBr** [comment]
Boa tarde, estão com vagas pra Junior?

Obrigado

**Comment by Cristianasp** [comment]
Oi Ricardo! Por enquanto não mas se quiser manda seu curriculo para
vagas@fintalk.ai e a gente guarda aqui ;-)


Em qua, 9 de out de 2019 16:07, Ricardo Guizi <notifications@github.com>
escreveu:

**Comment by Cristianasp** [comment]
ping !

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
