### ISSUE TITLE
[Remoto] - Desenvolvedor Backend Pleno na [Upnid]

### ISSUE THREAD

**Issue by lucasupnid** [backend-br/vagas#165]
## **Experiência**
Pleno

## **Local**

Remoto com possibilidade de trabalhar na sede física também em São Paulo ou no Rio de Janeiro.

## **Requisitos**

- Experiência comprovada em React.
- Conhecimento em Javascript, HTML, CSS
- Testes automatizados
- Foco em qualidade de código
- Ter conhecimento em Node.JS

## **Você vai se encaixar se:**

- For uma pessoa disciplinada e comprometida.
- Você  gosta de sempre ser desafiado a aprender mais.
- Você abraça novos desafios e questiona o status quo
- Aprende rápido e se adapta facilmente a mudanças
- Você se dedica a criar um produto incrível em padrões internacionais
- Busca ter uma visão macro do projeto

## **Diferenciais:**

- Bonificação extra para alto desempenho 
- Incentivo a educação (cursos, livros, eventos, etc)
- Trabalho Remoto
- Horários flexíveis (você define a sua rotina)

## **Nossa empresa**

Somos um marketplace para venda de produtos físicos e digitais. Estamos a dois anos no mercado crescendo a cada mês. Temos Executivos de grandes empresas do ecommerce brasileiro como sócios
**Nosso site**: https://conheca.upnid.com/
**Nosso Facebook**: https://www.facebook.com/upnid/

## **Como se candidatar**

Por favor envie um email para lucas@upnid.com com seu CV anexado e seu perfil no Github - enviar com o seguinte assunto: "Vaga Desenvolvedor Backend Pleno"  

## **Labels**

Remoto
PJ/CLT
Pleno

**Comment by SergioDiniz** [comment]
ainda ta aberto? :)

**Comment by lucasupnid** [comment]
Sim, Sergio!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
