### ISSUE TITLE
[Taboão da Serra-SP] Desenvolvedores (as) Java Pleno e Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1654]
Descrição da vaga
Estamos em busca de profissionais com experiência em Java para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial em Taboão da Serra- Grande São Paulo. Oferecemos fretado gratuito a partir de 2 estações de metrô.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico
-fretado gratuito a partir de 2 estações de metrô de SP.

Requisitos
Java
IBM WebSphere Portal
Portlets

Contratação
CLT full pela BRQ.
Horário das 8hs as 17hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Java Taboão.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
