### ISSUE TITLE
[Morumbi-SP] Desenvolvedores (as) Java Pleno e Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1655]
Descrição da vaga
Estamos em busca de profissionais com experiência em Java para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial no cliente ao lado do Shopping Morumbi e estação de trem Morumbi- Com fácil ligação nas linhas de metrô.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
Java 7 (ou superior) 
REST

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Java Morumbi.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
