### ISSUE TITLE
Analista de Sistemas - Tecon Suape (Pernambuco)

### ISSUE THREAD

**Issue by lucasparisi** [backend-br/vagas#1658]
Link para inscrição: http://bit.ly/tecon_suape_R08726
Desenvolver, suportar e aprimorar os sistemas de informações implantados no **### Tecon Suape**, no Porto de Suape, empresa do grupo ICTSI (www.ictsi.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
