### ISSUE TITLE
[Piracicaba SP] Back-End Java Developer na [IDGeo]

### ISSUE THREAD

**Issue by javierIdgeo** [backend-br/vagas#1659]
labels: 3+ anos de exp, CLT/PJ ,Java Spring, Cloud

**Programador Java Back-end Pleno**
**IDGeo – Inteligência em Dados Geográficos,**
                   
A **IDGeo** – Inteligência em Dados Geográficos, empresa do segmento de geotecnologias aplicada à gestão e monitoramento agrícola, está buscando profissionais experientes na área de desenvolvimento de plataformas Web, com interesse em integrar equipe multidisciplinar, com o desafio de inovar os processos de controle e gestão da lavoura. Vaga para contratação imediata.
 
**A vaga.**
Precisamos de profissionais para trabalhar na nossa plataforma web de gestão de dados geográficos, implementada em JAVA, com integração a aplicações mobile (IONIC), 
Estes aplicativos são consultados por nossos clientes e precisam de integrações a diferentes bancos de dados e sistemas de gestão de dados geoespaciais.
 
**Atividades:**
Definir requisitos do sistema junto à equipe de produção (equipe multidisciplinar);
Coordenar desenvolvimento com equipe front-end;
Implementar e documentar modificações no back-end de uma aplicação Web.

**Pré-Requisito:**

- Conhecimento e fluência de Java (JSE/JEE) .
- Dominio de Spring Boot, Spring Security, Spring Cloud, Spring Data JPA.
- Ter conhecimentos de Maven ou Gradle.
- Experiência usando API REST e documentação de API.
- Conhecimentos sobre Arquitetura de microsserviços (Netflix OSS).
- Domínio de lógica, engenharia de software, boas práticas e padrões de arquitetura.
- experiência com bancos de dados sql.

**Diferenciais:**

- Docker 
- git    
- Protocolo OAuth2     
- NGINX     
- SSL     (OpenSSL)    
- Geoserver
- shellscript
- Linux/ubuntu
- Azure, gCloud, ws3, DO.

**Local**
Remoto ou Escritório em Piracicaba

**Faixa salarial**
 R$ 7000,00

**Como se candidatar**
Por favor envie um email para selecao_dev@idgeo.com.br com seu CV anexado em pdf - enviar no assunto: **Vaga Back-end**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
