### ISSUE TITLE
BRQ São Paulo - Analista Programador Java Sênior

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#166]
Analista Programador Java Sênior
Grande empresa localizada na Zona Oeste de SP busca profissional com experiência nas seguintes 
tecnologias: Java Web e StandAlone Eclipse, Java 1.6 e 1.7, Spring Versões até a 4.2(incluindo 
Security, MVC e LDAP) e Spring Boot , Hibernate, DAO, JSP, WebServices (SOAP e Rest), Oracle, 
IBM Infosphere Data Architect, Maven, Ant, Junit, JQuery, JavaScript e ScriptLets, GJson, Jackson, 
API´s para parser e  API Google Engine e Google Search. 
Integrações de sistemas, GIT, Jenkins, Nexus, Apache-tomcat-7.0.56, CouchBase, Oracle, Falcon, 
AFM em Linux. 
CLT, salário a combinar mais atrativo pacote de benefícios.
Horário comercial.
Local: Villa Lobos- entre a estações de trem C. Universitária e Villa Lobos.

Sobre a BRQ:
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Interessou? Envie seu cv para mim, no ryokota@brq.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
