### ISSUE TITLE
[SÃO PAULO] Back-End Developer na Hash (Fintech)

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#1660]
### **Back-End Developer na Hash (Fintech)**
Site da empresa: https://www.hash.com.br/

Pessoal, tudo bem? Me chamo Carol, trabalho na intera conectando talentos à oportunidades no mercado.
Atualmente estou em busca de **desenvolvedores(as) Back-End** para uma oportunidade na Hash, uma fintech que vem crescendo exponencialmente nos últimos 2 anos, com o objetivo de ajudar seus clientes a mapear, desenvolver e implementar soluções financeiras. A ideia é reduzir a burocracia para operações de subadquirência, melhorando processos e reduzindo custos de operação para empresas que são ou querem se tornar subadquirentes.

### Estamos a procura de desenvolvedores com **conhecimento profundo** em:
- Sistemas de alta disponibilidade ou clusterização
- Microsserviços
- Linguagens orientadas à objetos

### E vai ser muito legal se você:
- Usa Node.js, Mongodb, Postgres, Go ou Clojure
- Tem projetos ou participa da comunidade open source

**Modelo de contratação:** Efetivo CLT | 40h semanais
**Local de trabalho:** Av. Paulista, 2537, Bela Vista, SP.
**Faixa salarial:** entre R$8.000 e R$18.000, a depender da senioridade
**Benefícios e outras infos:** vale refeição, vale transporte, assistência médica e odontológica, gympass, escolha sua própria configuração de notebook e remote friendly.

### **Processo Seletivo**
Inscrição no link abaixo, chat bot e bate-papo via hangouts com a Intera. Em seguida, desafio técnico e entrevista com a equipe da Hash :)
https://bit.ly/2lpegaf

Caso tenham alguma dúvida, estou disponível para conversar sobre a vaga!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
