### ISSUE TITLE
[São Paulo] Back-End Engineer no [Itaú Unibanco]

### ISSUE THREAD

**Issue by thatacardoso** [backend-br/vagas#1661]
**Venha trabalhar no Itaú Unibanco!**

Queremos o caminho que ninguém usou, porque ele geralmente leva aonde ninguém foi. Queremos os inconformados, os inquietos, os indignados, apaixonados por tecnologia. Queremos os impacientes e os inventivos.  

Queremos aqueles com vontade de mudar o mundo visando o melhor para o cliente. Não queremos você apenas por achar que você tem a nossa cara. 

Queremos ter um pouco da sua também. Queremos você!

**Principais atividades:**

Aplicar os conhecimentos de Engenharia de Software nas demandas envolvendo sistemas e aplicações na comunidade de Cartões, especificamente em novo projeto "Cartão Branco".
Aferindo custos, simplicidade, elasticidade, escalabilidade, sustentabilidade e reuso da solução;
Trabalhar no desenvolvimento, desenho da solução a nível de arquitetura;
Atuar na disseminação de conhecimento e implantação da soluções utilizando tecnologias inovadoras para atender a nova plataforma digital de cartões.
 

**Perfil Técnico**

Experiência e vivência com desenvolvimento em Kotlin;
Experiência com AWS;
Experiência com desenvolvimento/integração de APIs RestFul Mensageria/eventos, broadcasting;
Conhecimento em bancos de dados relacionais (Aurora, MySQL, SQL Server) e noSQL (Casandra, MongoDB, Hadoop);
Continuous integration e continuous delivery, automação de deploy e testes;
Expertise em ambiente Git e Jira;
Experiência em Metodologias ágeis e práticas Lean.

Interessados enviar cv para thais.cardoso@beit.work ou se candidatar na oportunidade https://jobs.bigland.co/integrityconsulting/job/6009c039-fb75-482b-83d1-ae0bfde5b9fd?utm_source=hire&utm_medium=direct_share

![Imagem divulgação vagas Github (1)](https://user-images.githubusercontent.com/55853915/65718728-898f1b80-e07a-11e9-9929-d045e948cced.jpg)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
