### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack Pleno na ADIRETO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1664]
### Sobre a empresa: Adireto

A Adireto entrou no mercado do marketing digital e logo se especializou em compra de tráfego online, atingindo resultados milionários em pouco tempo de atividade no Brasil. Com metas agressivas de crescimento, busca fazer história e gerar grande impacto. Suas marcas alcançam literalmente milhões de pessoas todos os meses.

### O que você irá fazer?

Desenvolver soluções web, garantindo a entrega do escopo no prazo acordado, com alta qualidade de entrega.
Contribuir nos projetos e propor as melhores práticas em desenvolvimento web.
Autonomia para tomada de decisões técnicas dos projetos, ainda que seja necessário seguir algum guideline em alguns casos.

### As habilidades necessárias:

 Você irá trabalhar com o desenvolvimento MEAN:

JavaScript;
MongoDB;
Node.js;
Angular.js;
Express.js;
Também buscamos alguém que já tenha trabalhado com React.

### Labels:

Pleno
REMOTO

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/adireto_remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
