### ISSUE TITLE
[São Paulo] Developer FullStack na [OSBR]

### ISSUE THREAD

**Issue by VagasOSBR** [backend-br/vagas#1665]
Somos a OSBR - Optimus Serviços do Brasil, utilizamos as melhores e atuais tecnologias do mercado, transformamos seus dados em informações e insights para tomada de decisão, respeitando o momento e a cultura da empresa, visando a melhoria de desempenho na gestão de seu negócio, balizando a tomada de decisão através de indicadores. 
Otimizamos seu processo através de workflows, sistemas customizados, apps, sites e intranets.

Venha! Junte-se a nós!

**Desenvolvedor FullStack .Net**
 
**Imprescindível** 
Superior em Tecnologia da Informação ou Áreas Correlatas.
Experiência em arquitetura FullStack (Front e Back) 
Backend: .NET, MVC 5 
FrontEnd: HTML, CSS, Zurb, Angular, JavaScript 
SQL Server 
Modelagem de base de dados 
C# 
SQL Server 2008 e/ou superiores 

Idiomas: Inglês Técnico

**Diferencial** 
Metodologias ágeis (Scum e Kanban)
Conceitos de usabilidade

**Contratação:** PJ - Indeterminado 
**Incentivos:** Assistência Médica + Auxílio refeição + Férias
**Remuneração:** à combinar
**Local de Trabalho:** São Paulo – Av. Paulista / Morumbi

Interessados enviar cv, pretensão salarial e disponibilidade para vagas@osbr.com.br

**Labels**
🏢 Presencial
👴 Sênior
⚖️ PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
