### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack Pleno na PARA O ALTO E AVANTE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1666]
### Sobre a empresa: Para o Alto e Avante

Somos uma Escola de Marketing de Diferenciação, disponibilizamos cursos e treinamentos para auxiliar empresários a se desenvolverem e aprenderem a se diferenciar no mercado. Somos uma empresa inovadora, que procura pessoas que queiram crescer junto com a gente! Acreditamos que todas as pessoas tem superpoderes e queremos destacar o SEU superpoder! Juntos iremos longe!

### Descrição: Qual será o seu papel?

Manutenção e desenvolvimento das nossas plataformas;
Auxiliar na definição de novas tecnologias a serem utilizadas;
Esperamos que você seja muito bom em:

PHP;
HTML;
CSS;
Javascript;
Laravel 5.0+;
MySQL;
Conhecimento de API;
AWS;
Inglês técnico e intermediário

### Vamos ficar felizes se você conhecer:

Nodejs (É um grande diferencial, muito importante para nós);

### Você vai amar trabalhar aqui se:

Estiver em busca de um ambiente de trabalho flexível, home office, dinâmico e de MUITO crescimento;
Gostar de estar em lugares onde possa se desenvolver o tempo todo;
Estiver em busca de aprendizado e quiser criar coisas inovadoras;
Estiver em busca de uma empresa colaborativa, humana e que se preocupa com as pessoas;
Trabalhar como foco em resultados.

### Benefícios:

Férias remuneradas;
Financiamento de cursos (nós investimos em você!)
Acesso a todos os nossos cursos.

### Informações Complementares:

Remoto
Pleno

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/altoeavante_remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
