### ISSUE TITLE
[São Paulo] Desenvolvedor .NET na Lopes Imóveis

### ISSUE THREAD

**Issue by thatigonc** [backend-br/vagas#1667]
***Atividades***
- Criar aplicações web, sistemas e rotinas na plataforma .NET;  
- Realizar a manutenção e melhoria constante dessas aplicações;  
- Participar de maneira ativa na contínua melhoria do código e do produto;  
- Ser rápido na entrega, inovar e quebrar paradigmas;  
- Trabalhar juntamente com desenvolvedores Front-end para garantir os melhores visuais e funcionalidades;  
- Aprender e crescer junto com a nossa empresa;  
- Estar atualizado com tecnologia web e tendências digitais;  
- Otimizar aplicações para garantir escalabilidade, performance e robustez;  
- Garantir que plataformas funcionem bem em diferentes navegadores e dispositivos;  
- Deploy de aplicações utilizando Git e ferramenta de CI;

***Requisitos***  
- Inglês técnico;  
- Conhecimentos de HTML, CSS, JavaScript;  
- Experiência comprovada em C# .NET  
- Experiência com Entity Framework;  
- Git;  
- Jenkins ou outro ferramenta de CI  
- ASP.NET Core  
- MVC  
- Web API Rest  
- Forte experiência em SQL Server (T-SQL)

💼Contratação: PJ (seg a sexta)
💰 Faixa Salarial: R$7.000,00 a R$9.000,00 
Benefícios: 2 semanas de descanso remunerado

CV + pretensão: tatiane.goncalves@taking.com.br

**Comment by jonathanguilhermesouza** [comment]
@thatigonc há possibilidade de home office?

**Comment by thatigonc** [comment]
> @thatigonc há possibilidade de home office?

@jonathanguilhermesouza não há possibilidade de HO.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
