### ISSUE TITLE
Rio de janeiro - Desenvolvedor .Net Senior

### ISSUE THREAD

**Issue by robsongomesses** [backend-br/vagas#1668]
Criar aplicações web, sistemas e rotinas na plataforma .NET Core;
Realizar a manutenção  em aplicações em .NET Framework;
Participar de maneira ativa na contínua melhoria do código;
Ser rápido na entrega, inovar e quebrar paradigmas;
Trabalhar juntamente com desenvolvedores Front-end para garantir os melhores visuais e funcionalidades;
Estar atualizado com tecnologia web e tendências digitais;
Otimizar aplicações para garantir escalabilidade, performance e robustez;
Garantir que plataformas funcionem bem em diferentes navegadores e dispositivos;
Deploy de aplicações utilizando Git e ferramenta de CI;

Requisitos mínimos: C# , Net Core e Dapper 
banco de dados: MSSQL Server e PostgreSQL
Git e Gitlab Github
REST API e JSON
Arquitetura em nuvem, TDD ou testes unitários, DDD, saber escrever código limpo e legível, orientação a objeto, padrão MVC. 
Para tratar alguns legados: ASP.NET e Java. 

Conhecimentos desejados: Contêiner Docker, autodidatismo, habilidade de documentação e de desenho de interfaces, experiência no desenvolvimento de componentes reutilizáveis, ter sede de aprender e trocar conhecimento com a equipe, conhecimento em JavaScript.

Vaga para pleno e sênior
Remuneração de até R$ 7.500 CLT FULL
Email com a descrição da vaga para: robsongomes.ses@gmail.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
