### ISSUE TITLE
[Remoto ou Jaguariúna-SP] Desenvolvedor(a) Java | AB-Inbev (Ambev)

### ISSUE THREAD

**Issue by xandebianchi** [backend-br/vagas#1669]
# **Informações gerais da empresa**

### **A maior cervejaria do mundo** abriu no final de 2018 seu setor de _tecnologia_, o time chamado: _Beertech_.
Uma novidade, pois antes os aplicativos eram feitos por terceiros.

E agora está acontecendo a **Transformação Digital** da empresa, onde se constrói um aplicativo B2B para vendas dos seus produtos (cerveja, não alcoólicos, etc.), e ele funciona em todos os países que a empresa trabalha, pelo mundo todo. 

A **Anheuser-Busch InBev** (abreviada **AB InBev**), **líder no mercado mundial**, é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga **Interbrew** e da brasileira **Ambev**. Está sediada em Leuven, na Bélgica, e possui escritório em Nova York, e sedes em Jaguariúna-SP, Londres, Cidade do México, Johanesburgo, St. Louis, e outros locais. Conta com mais de duzentas marcas de bebidas, entre as quais se destacam Brahma, Skol, Antarctica, Budweiser, Corona, Stella Artois, Beck's, Leffe, Hoegaarden na Europa. 

### - **Há também a possibilidade de trabalhar remotamente, de acordo com cada caso.**

# **O que esperamos de você**

Como desenvolvedor(a) Java será responsável por conceber serviços e soluções para garantir que o software implantado seja escalável e confiável.

# **Sobre nós**

No Brasil possuímos uma unidade com mais de 200 fanáticos por cerveja, e também nossa célula de tecnologia, chamada BeerTech que é focada em prover serviços e soluções em escala global para todas as cervejarias do grupo.

# **Responsabilidades da posição**

- Trabalhe colaborativamente com várias equipes para projetar e fornecer soluções novas e inovadoras.
- Use sua experiência aproveitando as melhores ferramentas e tecnologias para refinar e aprimorar as práticas de desenvolvimento de software para sua equipe.
- Envolva-se em atividades de solução de problemas, exigindo o pensamento conceitual criando soluções.
- Utilize práticas para garantir a entrega de código de alta qualidade com baixas taxas de defeitos.

# **O que você precisa ter**

- Diploma de bacharel em sistemas da informação, engenharia/ciência da computação ou áreas relacionadas a Tecnologia da Informação, com experiência de trabalho.
- Fundamentos sólidos em design orientado a objeto, estruturas de dados, algoritmos, solução de problemas e análise de complexidade.
- Capacidade de solucionar problemas e identificar a causa raiz de problemas sob pressão de tempo.
- Capacidade de articular efetivamente desafios e soluções técnicas.
- Excelente comunicação interpessoal com fortes habilidades verbais / escritas em inglês (Nível B2 - Avançado).
- Habilidade demonstrada e paixão pela excelência operacional.
- Mentalidade focada no cliente, tendo orgulho em criar uma jornada informativa orientada por dados.

# **Desejável**

- Java 7 ou 8 SE;
- Spring Framework incluindo (Spring Boot, Spring Cloud, Spring MVC);
- Docker;
- DevOps do Azure;
- Git;
- Jenkins;
- SDLC ágil;
- NoSQL (MongoDB ou Cassandra);
- Experiência com Jira e com Kubernetes são uma vantagem.

# **Tipo de Contratação**

CLT

# **Como se aplicar**

Mande seu CV para:
alexandre.bianchi@ab-inbev.com 

**- Link de diversidade e inclusão:**
[Link de diversidade e inclusão](https://www.ab-inbev.com/careers/why-ab-inbev/diversity-and-inclusion.html)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
