### ISSUE TITLE
[São Paulo] Vaga Back-end (linguagem agnóstico) 

### ISSUE THREAD

**Issue by alanrochlin** [backend-br/vagas#167]
Mapeamento de profissionais para a empresa D3 (D3.do).
Oportunidades para diferentes senioridades e linguagens. 
Link com mais infos e apply: https://thegrid.workable.com/j/46CEC5721B

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
