### ISSUE TITLE
[São Paulo - SP] Desenvolvedor(a) Full Stack na Zup Innovation

### ISSUE THREAD

**Issue by pedroferreirazup** [backend-br/vagas#1670]
## Empresa
 A Zup desenvolve produtos digitais disruptivos que impactam a vida de milhares de usuários. Acreditamos em ambientes ágeis, autogerenciáveis e flexíveis. Por isso, contratamos somente os melhores profissionais. Crescemos mais de 30 vezes nos últimos cinco anos, já somos mais de 850 zuppers e estamos em seis cidades.

**Importante:** acreditamos que profissionais fora da curva estão em todos os lugares. Por isso, todas as nossas vagas são abertas a qualquer pessoa, independente de cor, gênero, orientação sexual, identidade de gênero e/ou pessoas com deficiências.

## Quem é você?

Uma pessoa que gosta de ser desafiada e quer fazer parte de projetos que estabelecem um novo curso para a história das maiores empresas do Brasil. Gosta de trabalhar com autonomia, sabe se adaptar a qualquer ambiente e nunca desiste. Aqui na Zup, também valorizamos profissionais que disseminem conhecimento e trabalhem bem em equipe.

## Descrição da vaga
- Possuir disponibilidade de atuação em projetos vários
- Possuir foco em disseminar o conhecimento
- Ser organizado tendo vistas o trabalho em equipe
- Ser atento a pequenos detalhes
- Facilidade de relacionamento

## O que você fará na Zup:

Irá atuar tato no desenvolvimento Front-End quanto no Back-End. Deve dominar escalabilidade, versionamento, padrões projeto e formas de armazenamento (não apenas bancos em transacionais). Levar em conta questões de qualidade, portabilidade e escalabilidade das aplicações.

Importante: Acreditamos que profissionais fora da curva estão em todos os lugares. Por isso, todas as nossas vagas são abertas a qualquer pessoa, independente de cor, gênero, orientação sexual, identidade de gênero e/ou deficiências.

## Requisitos

Conhecimentos de Front End:

- Experiência com desenvolvimento em HTML 5, CSS, JavaScript;
- Familiaridade com as novas especificações do EcmaScript;
- Conhecimentos em React
- Frameworks de interface (Bootstrap)
- Testes unitários

Conhecimentos de Back End:

- C#, .NET Core;
- Desenvolvimento de WebServices e Micro-serviços;
- Experiência com REST e Integração de API;
- Web API / RestFul / OData / GraphQL;
- APIs documentation (Swagger e/ou Spring REST docs)
- Banco de dados SQL Server;

Conhecimentos em metodologia de desenvolvimento:

- TDD / BDD;
- Testes unitários;
- Padrões de projeto - MVC, MVVM, Singleton, Factory, Adapter, Proxy, Decoration;
- Metodologia Ágil (Kanban / Scrum) (Confluence, Jira);
- Conhecimento em Task Runner: Webpack, Gulp ou Grunt (para automatizar processos);
- Experiência em GIT (Hub / Lab / Flow) e/ou TFS/ VSTS;
- Continuous Integration e Continuous Deployment utilizando
- GIT ou TFS/VSTS;
- Jenkins;
- Sonar;
- Docker;

## Como me destaco para esta vaga?

- Servidor de aplicações: IIS, Jboss, Apache, NGINX;
- PowerShell;
- EF 6 (Migrations / Code First) / NHibernate e FluentNHibernate;
- Localização/Globalização;
- Protocolos TCP/IP e UDP;
- SAS
- Pessoas que conheçam de Core bancário possuem destaque para esta vaga.

## Posição
Todos os níveis de senioridade 

## Tipo de contratação
CLT

## Benefícios

- Salário compatível com mercado
- Vale transporte
- Vale Refeição/Alimentação
- Seguro saúde
- Plano odontológico
- Gympass
- Auxílio Creche
- Seguro de vida
- Auxílio plano telefônico
- PLR
- Nossos escritórios também contam com frutas, lanches e happy hours ocasionalmente

## Como aplicar
envie seu currículo para o e-mail pedro.ferreira@zup.com.br com descrição [Vaga Full Stack - Zup]

## Outras Informações
Ajudamos com Auxilio Moradia
Possibilidades de moradia:  Uberlândia, São Paulo, Belo Horizonte.

## Labels
CLT
Todos níveis
Presencial

**Comment by jonathanguilhermesouza** [comment]
@pedroferreirazup há possibilidade de PJ?

**Comment by pedroferreirazup** [comment]
@jonathanguilhermesouza a zup trabalha apenas com CLT, nossas propostas são boas avaliamos essas condições do candidato

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
