### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack Pleno na CREDIHABITAR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1671]
### Sobre a empresa: CrediHabitar

A CrediHabitar é uma fintech que aumenta a velocidade e assertividade em processos de financiamento imobiliário junto a bancos parceiros. Buscamos simplificar a jornada de financiamento imobiliário por meio de tecnologia e foco na experiência do cliente, a exemplo do que vimos nos cartões de crédito e bancos digitais. Vem revolucionar esse mercado com a gente?!

### Descrição: Qual será o seu papel?

Manutenção e desenvolvimento do nosso sistema;
Auxiliar na definição de novas tecnologias a serem utilizadas;

### Esperamos que você seja muito bom em:

PHP (CodeIgniter);
HTML;
CSS;
Javascript;
MySQL;
WordPress;
Experiência com: Google Cloud, mas, se souber VPS/Azure/AWS, também é legal para nós :)
Vamos ficar felizes se você conhecer sobre tecnologias mobile.

### Você vai amar trabalhar aqui se:

Estiver em busca de crescimento e evolução;
Gostar de estar em lugares onde possa se desenvolver o tempo todo;
Quiser trabalhar em uma empresa disruptiva e aberta a novas ideias;
Gostar de impactar positivamente a vida das pessoas;

### Benefícios:

Férias remuneradas;
Vale Alimentação.

### Informações Complementares:

Contratação tipo PJ;
Estamos localizados na Savassi - Belo Horizonte, MG
Pleno 

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/credihabitar_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
