### ISSUE TITLE
[Belo Horizonte] Desenvolvedor BackEnd Júnior na CREDIHABITAR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1673]
### Sobre a empresa: CrediHabitar

A CrediHabitar é uma fintech que aumenta a velocidade e assertividade em processos de financiamento imobiliário junto a bancos parceiros. Buscamos simplificar a jornada de financiamento imobiliário por meio de tecnologia e foco na experiência do cliente, a exemplo do que vimos nos cartões de crédito e bancos digitais. Vem revolucionar esse mercado com a gente?!

### Descrição: Qual será o seu papel?

Manutenção e desenvolvimento do nosso sistema;
Auxiliar na definição de novas tecnologias a serem utilizadas;

### Esperamos que você seja muito bom em:

PHP;
CodeIgniter;
MySQL;
POO;
Conhecimento em Crawler;
Conhecimento em Infraestrutura;
RESTful;
Conhecimento em Google Cloud;

### Você vai amar trabalhar aqui se:

Estiver em busca de aprendizado, crescimento e evolução;
Gostar de estar em lugares onde possa se desenvolver o tempo todo;
Quiser trabalhar em uma empresa disruptiva e aberta a novas ideias;
Gostar de impactar positivamente a vida das pessoas;

### Benefícios:

Férias remuneradas;
Vale Alimentação.

### Informações Complementares:

PJ
Alocado
Júnior

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/credihabitar_backend

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
