### ISSUE TITLE
[Ribeirão Preto] Desenvolvedor(a) Full Stack PHP na Venda.la

### ISSUE THREAD

**Issue by vitorleonel** [backend-br/vagas#1674]
## A Empresa

A Venda.la é uma Startup que está revolucionando o varejo on-line e off-line.

Nós desenvolvemos soluções que conectam vendedores aos principais marketplaces, para que possam ter uma gestão centralizada.

Nosso maior diferencial é a automação de processos. Nosso principal objetivo é fazer nossos clientes venderem mais e nosso lema é "Gerencie melhor e venda mais".

Estamos em constante evolução e temos a mente aberta para novidades.

## Atividades e responsabilidades

- Desenvolvimento e manutenção de sistemas em Laravel e Cake;
- Criação e manutenção em APIs;
- Documentação de toda a codificação;
- Ajudar a encontrar soluções para problemas;
- Trabalhar em equipes multidisciplinares em um ambiente scrum.

## Requisitos

- PHP 7+;
- Laravel;
- MySQL;
- CSS;
- Javascript;
- GIT;
- API.

## O que nós oferecemos

- Plano de Saúde;
- Vale Transporte;
- Vale Refeição;
- Salário compatível com o mercado;
- Premiação por desempenho;
- Plano de participação dos resultados;
- Trabalhar com os melhores computadores da Apple;
- Ambiente jovem, descontraído, escritório confortável;
- Sem dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável;
- Relacionamento próximo aos fundadores e diretores da empresa, além de uma equipe fantástica que está revolucionando o varejo.

## Teste

Caso tenha interesse, candidate-se pelo Programathor: [https://programathor.com.br/jobs/7969-desenvolvedor-a-full-stack-php](https://programathor.com.br/jobs/7969-desenvolvedor-a-full-stack-php)

## Labels

- CTL
- Pleno
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
