### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Backend na [Gazeus Games]

### ISSUE THREAD

**Issue by paulamarcolino** [backend-br/vagas#1676]
**PRINCIPAIS RESPONSABILIDADES**

- Desenvolver web services e APIs;
- Implementar código reusável e bibliotecas;
- Implementar protocolos cliente servidor;
- Implementar soluções para armazenamento de dados;
- Identificar dificuldades, desafios, obstáculos que possam surgir durante a implementação do projeto;
- Integrar múltiplas fontes de dados;
- Migrar e transformar dados;
- Trabalhar com autenticação e autorização de usuários.
- Desenvolver novas plataformas de serviços;

**LOCAL DE TRABALHO**
Barra da Tijuca (Rio de Janeiro)
Shopping Downtown - próximo ao metrô Jardim Oceânico e BRT

**BENEFÍCIOS**

- Plano de Saúde e Odontológico Bradesco 100% subsidiado
- VR (33,66)
- VT
- Shiatsu
- Snacks oferecidos pela empresa
- Horário flexível
- Day off no dia do aniversário

**PRÉ-REQUISITOS**

- Formado ou cursando Engenharia de Computação, Ciência da Computação ou áreas relacionadas;
- Forte conhecimento e experiência em Java;
- Experiência sólida em trabalhar com métodos ágeis (preferencialmente SCRUM)
- Trabalhar de forma independente e pró-ativa como também em equipe;
- Saber se comunicar com eficiência entre diferentes áreas da empresa;
- Conhecimento de técnicas de segurança e proteção de dados
- Conhecimentos sólidos de estruturas de dados, algoritmos e arquitetura de sistemas.
- Capacidade de aprender rapidamente diferentes linguagens e tecnologias.
- Conhecimento em MySQL;
- Experiência em sistemas de controle de versão;
- Experiência implementando e usando web services.
- Inglês avançado.
- Foco em resultados;
- Habilidade para lidar com diversas demandas simultâneas
- Boa comunicação.

**SERÁ CONSIDERADO UM DIFERENCIAL**

- Conhecimento de Amazon Web Services (SQS, SNS, DynamoDB, etc);
- Conhecimento em Lua, NodeJS, Ruby, Phyton e outras linguagens de programação
- Conhecimento de Git;
- Curiosidade em pesquisar tecnologias de backend.

**CONTRATAÇÃO**
CLT

**SOBRE A GAZEUS**
Gazeus Games é uma produtora e desenvolvedora brasileira de jogos para celular e instant games para o Facebook. Entre nossos jogos, destaca-se o portal Jogatina que traz jogos clássicos como Dominó, Buraco, Tranca, Truco, Mahjong, etc.  Buscamos sempre criar jogos casuais e sociais que entretêm e criem laços entre os jogadores. Atualmente milhões de pessoas jogam e interagem entre si usando nossos jogos.  Caso tenha problemas com sua aplicação, entre em contato pelo: rh@gazeus.com

**COMO SE CANDIDATAR**
Através do nosso sistema interno. Acesse o link e cadastre seu currículo:
https://gazeus.bamboohr.com/jobs/view.php?id=6

**Comment by jonathangaldino** [comment]
Disponível ainda?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
