### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Back-End Pleno na Avec [2 vagas]

### ISSUE THREAD

**Issue by rferro** [backend-br/vagas#1678]
# Desenvolvedor(a) Back-End Pleno na Avec (2 vagas)

## :pencil: Sobre a vaga

Você gosta de trabalhar em equipe no desenvolvimento de projetos inovadores e desafiadores? Se você tem alguns anos de experiência no back-end e está querendo um novo desafio, esta vaga é o que você está procurando.

O que acha de impactar diretamente o mercado de beleza e bem-estar reinventando como a operação dos estabelecimentos é feita? E mais: ajudar as pessoas a progredirem em suas carreiras profissionais, tendo mais tempo para fazer o que realmente importa?

A experiência de pedir comida e táxi e até de alugar um imóvel já foram redefinidos e uma certeza nós temos: o próximo foguete é a vertical de beleza e bem-estar. Só aqui você trabalha atingindo o cliente de ponta a ponta: do consumidor que agenda um serviço pelo app até a operação de transferência bancária para o cartão Avec do profissional. **Sim, também somos FinTech!**

Entre várias atividades, você será peça chave no desenvolvimento do nosso novo produto baseado em uma arquitetura de microsserviços com uma stack de tecnologias e ferramentas de última geração. Clique [aqui](https://stackshare.io/avec) e conheça nossa stack atual.

No final das contas, seu trabalho é facilitar a vida dos clientes e dos membros do seu squad. O quanto de tempo se ganha de não ter que navegar em um back-end mal feito, não intuitivo e lento? Tempo que poderia ser gasto com família e amigos. Seja a pessoa a dar esse presente para eles!

#### O que é essencial?

- Boa atitude, maturidade e comprometimento
- Comprovada experiência com Node.js **(+ 3 anos)**
- Desenvolvimento de serviços de alta performance de back-end
- TDD, Testes Unitários, Funcionais e de Integração
- Métodos ágeis de desenvolvimento (Scrum / Kanban)
- Bancos de dados relacionais: (MySQL, PostgreSQL)
- Clean Code / Coding Standards
- Proficiência em Git

#### O que seria desejável?

- Typescript
- API Design
- GraphQL
- Sólidos conhecimentos de Estruturas de Dados e Algoritmos
- Conteinerização (Docker)
- Bancos de dados NoSQL (MongoDB, DynamoDB)
- Redis / Memcached
- Mensageria (RabbitMQ, Kafka, ActiveMQ)
- Continuous Integration e Continuous Deployment

#### O que te diferencia?

- Experiência com serviços da AWS (API Gateway, App Sync, Step Functions, etc)
- Serverless Framework
- Functional Programming
- Experiência em segurança de APIs

## :heart_eyes: Você vai amar trabalhar aqui se você (for):

- Proativo
- Apaixonado por desenvolvimento de software
- Pensa fora da caixa e propõe soluções criativas
- Se identifica com ambiente de startup, de muito trabalho e muita diversão
- Gosta de sempre aprender coisas novas

## :heavy_check_mark: Responsabilidades

- Construir apis e serviços back-end utilizando Node.js
- Contribuir em decisões de arquitetura do projeto
- Integrar serviços third-party
- Priorizar e resolver bugs reportados em produção
- Criar ferramentas e soluções para medir e otimizar a performance dos nossos serviços

## :black_nib: Contratação

- **8k** ~ **10k**
- PJ
- Presencial

## :tada: O que você vai encontrar por aqui:

- Ambiente descontraído
- Gympass para todo mundo
- Descontos em salões, barbearias e SPAs parceiros
- Descontos em produtos de beleza vendidos no AvecShop
- Ambiente dinâmico, meritocrático e com crescimento exponencial
- Muitos desafios e aprendizados
- Cultura de feedback e 1:1 com avaliações trimestrais sobre você, seu gestor e fit-cultural
- No dress code
- Sala de "descompressão" com mesa de ping-pong (adoramos organizar campeonatos!) e puffs para dar aquela relaxada após o almoço :wink:

## :thinking: Quem somos?

Somos a maior Fintech de beleza do Brasil. Nossa missão é fazer com que profissionais e gestores da beleza ganhem mais tempo e mais dinheiro e, para isso, temos uma plataforma completa com soluções que vão desde ferramentas de marketing, aplicativo de agendamento online, sistema de gestão com soluções integradas de pagamento até conta digital e cartão de crédito pré-pago.

Temos mais de 40 mil estabelecimentos que utilizam nossa solução, entre salões de beleza, barbearias, clínicas de estética e spas. Queremos descomplicar a vida de todos eles e, para isso, temos quatro valores muito importantes para nós:

#### Iniciativa

Nunca estamos satisfeitos. Buscamos evoluir sempre e queremos sempre mais. Um Avecker nunca deve esperar que as coisas cheguem no seu colo!

#### Senso de dono

É mais importante identificar os erros e corrigi-los do que apontar o dedo para quem errou. Aqui, ensinamos. Um Avecker deve trazer a responsabilidade para si e não passar a bola para o lado. Senso de urgência e atenção constantes são pré-requisitos, afinal dono não dorme no ponto!

#### Trabalho em equipe

Se quiser ir rápido vá sozinho, mas se quiser ir longe, vá acompanhado. Por aqui, remamos juntos e para o mesmo lado! Sabemos que o trabalho em equipe bem feito é mais importante que o talento individual.

#### Foco em resultado

O esforço deve ser reconhecido, mas apenas o resultado deve ser recompensado. Somos malucos por números! Toleramos bem os erros, desde que eles sejam consertados rápido. Teste, erre, conserte, faça de novo, melhore! 

## :round_pushpin: Local

Av. Paulista. Próximo ao metrô Consolação.

## :question: E aí, gostou?

Candidate-se agora!

É só entrar em contato pelo email `jacqueline.mello@avecbrasil.com.br`.

**Comment by RafaelGSS** [comment]
Trabalho e recomendo!

**Comment by rferro** [comment]
Atualizado com os valores. Temos 2 vagas!

**Comment by halkliff** [comment]
Estão aceitando aplicação para trabalho remoto?

**Comment by rferro** [comment]
@halkliff infelizmente no momento não.

**Comment by GuiziBr** [comment]
Tem vaga pra Jr ou alguma previsão?

**Comment by rferro** [comment]
@GuiziBr Desculpe a demora. No momento temos apenas pleno e senior, mas podemos conversar mesmo assim. Entre em contato pelo email da descricao da vaga. Abs

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
