### ISSUE TITLE
[São Paulo] Back-End Developer na Cognizant

### ISSUE THREAD

**Issue by gabisaalves** [backend-br/vagas#1679]
## Descrição da vaga

Olá,

Já ouviu falar sobre a Cognizant? Somos uma multinacional do ramo de tecnologia com sede nos Estados Unidos :)

Estamos com oportunidade para atuar em um de nossos clientes. Se você é apaixonado por desenvolvimento assim como nós, este desafio é para você!

## Local

Escritório, São Paulo - Próximo ao Centro

## Benefícios

- Convênio médico;
- Convênio odontológico;
- Seguro de vida;
- VR ou VA;
- Auxílio creche;
- Previdência privada.

## Requisitos

**Obrigatórios:**
- Ter domínio em EJB3.1, JPA2 Hibernate, Webservices SOAP/REST JAX-WS/JAX-RS, CDI, JUnit, Spring Batch, Java 7 e Java EE6);
- Ter participado de projetos utilizando modelos ágeis.

**Desejáveis:**
- Experiência em startup.

## Contratação

CLT Full

## Nossa empresa

Fazer mais e melhor, com agilidade, é o que a era digital nos impulsiona, ser apaixonado pelos nossos negócios determina como iremos fazer. Nossos clientes e as nossas pessoas sabem que sempre encontraremos o melhor caminho, mas que nossos valores essenciais jamais mudarão. A Cognizant é uma das líderes mundiais em serviços profissionais. Com sede nos EUA e presente em mais de 40 países, ocupamos a 195.ª colocação no ranking da Fortune 500 e estamos, consistentemente, listados entre as empresas mais admiradas do mundo. 

## Como se candidatar

Envie um email para gabriela.alves@cognizant.com com seu CV anexado - enviar no assunto: Vaga Back-End Developer

Esperamos por você! _#BeCognizant_

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
