### ISSUE TITLE
BRQ São Paulo- Desenvolvedor Node Sr

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#168]
Programador NodeJS Sênior
Experiência no uso de Node.js, Linux; APIs; Integração e Delivery Contínuos, Jenkins ou ferramentas similares; Tecnologias AWS; git e flows como git flow/gitlab flow.
Contratação CLT, salário a combinar mais benefícios.
Horário comercial.
Local: Faria Lima- próximo a Juscelino Kubistchek (Itaim Bibi-SP).

Sobre a BRQ:
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Interessou? Envie seu cv para mim (ryokota@brq.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
