### ISSUE TITLE
[SÃO PAULO/SP] - Engenheiro de Software Back-End na CORA

### ISSUE THREAD

**Issue by VitorChaves21** [backend-br/vagas#1680]
## Descrição da vaga

Para revolucionar a vida do microempreendedor a Cora está construindo um produto do zero, com os melhores padrões de arquitetura e design. Mobile first – esse é o conceito. O desafio inicial é montar um app de um banco digital, e posteriormente a estrutura Web.

A equipe de tecnologia hoje é composta por um time forte de Back-End e de Mobile. Estamos em busca de pessoas que possam contribuir ainda mais com o desenvolvimento do Back End. O momento técnico é de muita construção, estamos desenvolvendo o produto do zero e para isso o time está planejando a plataforma, definindo arquitetura e os padrões, enquanto finaliza o que é necessário para lançarmos .

O que está sendo desenhado e definido agora, impacta diretamente no nosso crescimento, por isso é necessário estudar, buscar as melhores soluções e alternativas, definir o plano com o time e na sequência executar. Por fim, é preciso ter bastante experiência, pensar no longo prazo e estar disposto a colocar a mão na massa.

Topa o desafio?

## Local

WeWork Faria Lima - São Paulo

## Benefícios

- Assistência médica e odontológica
- VR
- Vale Alimentação
- Gympass
- Netflix
- Spotify

#### Diferenciais da vaga

- Política de horário flexível
- Trabalhar com autonomia e testar novas tecnologias e metodologias
- Criar um Produto do zero sem restrições técnicas

## Requisitos

*Obrigatórios:*
- Conhecimento aprofundado em ao menos uma linguagem e framework voltados a objeto 
  (preferência de Java, Kotlin ou Go);
- Conhecimentos básicos em ferramentas de infraestrutura; 
- Padrões de arquitetura e Design Patterns;
- Clean Code e boas práticas de desenvolvimento de software.

## Contratação

Em regime CLT e presencial

## Nossa empresa

O Banco Cora é uma nova fintech que está surgindo com o objetivo de melhorar a vida do micro e pequeno empreendedor. O grande objetivo é que, até 2030, o trabalho da Cora possa aumentar o PIB do Brasil em 10% através do crescimento desses empreendedores

## Como se candidatar

Candidate-se através de http://bit.ly/2p0H6PX

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
Nossos processos são rápidos e eficientes para os candidatos

## Labels

- Alocado
- CLT
- Sênior
- Backend
- Fintech

**Comment by ghost** [comment]
Observação: o processo seletivo desta oportunidade ainda está aberto!

**Comment by dgoscn** [comment]
Estão contratando somente sênior?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
