### ISSUE TITLE
[SÃO PAULO][JUNIOR] Ruby On Rails Dev. Jr. na B2B Stack

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1681]
### Conhecimentos Técnicos
- Experiência com pelo menos 3 a 5 projetos com RoR
- Utilizar o Unix
- Entender pelo menos uma das boas práticas de programação como code review, clean code, etc.

### Benefícios e Contratação
- PJ e remuneração compatível ao mercado
- Flexibilidade de horário
- Crescimento e desenvolvimento acelerado
- Happy hours com o time

**LINK PARA INSCRIÇÃO: http://bit.ly/2mD2ABl**

### Um pouco da nossa história
A B2B Stack é a **startup líder em avaliações de softwares B2B** no Brasil. Nosso propósito é trazer transparência no mercado B2B, dando voz à opinião de usuários reais de softwares, e acelerando a transformação digital no trabalho de profissionais brasileiros.

Lançamos a plataforma em 2018 e  já **somos líderes no Brasil** em avaliações de softwares B2B, **reconhecidos em meios como EXAME, Veja, InfoMoney, e patrocinadores do SaaStock Latam (maior evento itinerante de SaaS mundial)**. Tem muito crescimento pela frente! 

### Sobre o desafio a ser enfrentado
Trabalhando na B2B Stack, você fará parte de um time em crescimento, onde **você será um(a) grande protagonista** das transformações do produto. Neste cenário você terá a **responsabilidade e autonomia de desenvolver novas aplicações para o produto**, assim como garantir o pleno funcionamento com a melhor performance.

**LINK PARA INSCRIÇÃO: http://bit.ly/2mD2ABl**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
