### ISSUE TITLE
[Belo Horizonte] Desenvolvedor BackEnd Estágio na uCONECTE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1683]
### Sobre a empresa: Uconecte

A uConecte é uma das primeiras Fintechs do Brasil. Há 14 anos revolucionamos a forma que as pessoas lidam com sua situação financeira buscando as melhores oportunidades para a necessidade de cada um. Desenvolvemos tecnologias que permitem que as pessoas e as instituições financeiras se relacionem de forma transparente, rápida e com comodidade.

### Descrição:

Cuidamos para que o ambiente de trabalho seja diferenciado, descontraído e empolgante. Queremos estimular a criatividade, onde todos contribuem e são reconhecidos pelo seu desempenho. Buscamos no candidato valores que agreguem à equipe, com participação no processo criativo e foco em melhorias na experiência das pessoas.

Se você tem esse perfil, venha fazer parte dessa equipe!

### Você vai ser responsável por:

Desenvolvimento e manutenção de aplicações web;
Desenvolvimento de funcionalidades no Back-End;
Trabalho em novos projetos;
Gerar melhorias aos projetos da empresa;
Otimizando de serviços e processos.

### Requisitos Necessários:

PHP;
Codeigniter;
JavaScript;
APIs utilizando REST e SOAP;
GIT;
MYSQL;

### Seria legal se:

Serviços Google cloud plataform;
Amazon AWS;
Python;

### Benefícios:

Vale alimentação ou vale refeição;
Vale transporte;
Plano odontológico;
Seguro de vida;
Sala de descanso
Videogame

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/uconecte_estágio

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
