### ISSUE TITLE
[São Paulo] Software Engineer na Loft

### ISSUE THREAD

**Issue by FernandaBernardo** [backend-br/vagas#1684]
## Descrição da vaga
Procuramos pessoas que são apaixonadas por desafios e pelo mundo de startup para fazer parte do nosso time.

Como Software Engineer você terá que criar, desenvolver e manter uma arquitetura baseada em microsserviços para criar toda uma experiência simply delight no nosso usuário, além de criar APIs inovadoras e escaláveis e trabalhar em squads que empoderam o nosso negócio através da tecnologia.

## Local
São Paulo (região do Jardins) com oportunidade de home office alguns dias da semana.

## Benefícios
- Plano de saúde
- Seguro de vida
- Vale Refeição
- Vale Transporte
- Gympass
- Auxílio creche

#### Diferenciais
Folga no dia do aniversário;
Incentivo à educação
Horário Flexível
Home Office (parcial)
Nosso escritório tem snacks, espaço para meditação, sala de amamentação, sala de descanso, manicure, barbeiro e um ambiente totalmente descontraído

## Requisitos
**Obrigatórios:**
Bom conhecimento em design patterns
Experiência em implementar APIs escaláveis
Experiência com microsserviços
Experiência com banco de dados relacionais e não relacionais
Bom conhecimento de serviços AWS

**Desejáveis:**
Uso de dados para a tomada de decisões
Criar soluções inovadoras para problemas complexos
Gostar de trabalhar em um ambiente que incentiva a autonomia
Ser proativo e gostar de trabalhar em equipe

## Contratação

CLT

## Nossa empresa

A Loft está reinventando o processo de compra e venda de imóveis no Brasil, utilizando tecnologia e dados para transformar processos frustrantes e burocráticos em experiências simples e prazerosas.

Somos movidos pelo enorme desafio de transformar um dos maiores e menos eficientes mercados, enquanto nos divertimos e impactamos positivamente nossos clientes, stakeholders e a sociedade. Se você é ambicioso/a, habilidoso/a, criativo/a e gosta de enfrentar problemas complexos, junte-se à nossa equipe.

A Loft foi fundada em 2018 em São Paulo e conta com o apoio de investidores globais de venture capital, incluindo a Andreessen Horowitz, a Thrive Capital e a Monashees.

## Como se candidatar
Se inscreva na nossa vaga: https://jobs.lever.co/loft/2e67ace2-92b2-4179-9a45-6910fb96f47b

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
