### ISSUE TITLE
[SÃO PAULO] Dev. Java Sr. (B2W)

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1685]
Empresa de grande porte, do ramo varejista online, estilo Google, situada na Vila Olímpia - SP
Contratação PJ

Requisitos:
 - Experiência em arquitetura de dados desenvolvendo modelagem de dados e aplicações para integração em plataformas distribuídas e relacionais;
- Conhecimentos avançados nas linguagens de programação Java, Spark e/ou Scala, SQL;
- Conhecimentos de Python;
- Experiência na Stack Spring (Spring Framework 4.0+, SpringBoot, Spring Data, Hibernate, etc);
- Experiência com git, ferramentas de build contínuo;
- Desenvolvimento de serviços REST;
- Domínio sólido de cloud computing;
- Experiência com integrações com filas (Rabbit, Active MQ, Kafka).

Desejável:
- Experiência com bancos NoSQL;
- Experiência com docker, mesos e marathon;
- Experiência com programação funcional (Clojure, Elixir);
- Exprirencia com ferramentas de monitoria (NewRelic, ELK);
- Conhecimento básico no ambiente Cloudera, AWS ou Google;
- Conhecimento em frameworks front-end (angular, react, javascript, etc.);
- PL/SQL;
- Experiência em processos de carga para ambiente distribuído - HDFS.    

Venha fazer parte desse time!

Interessados encaminhar CV para aline.navarro@keepsimple.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
