### ISSUE TITLE
[Centro, São Paulo/SP] Desenvolvedor.NET na Krooze

### ISSUE THREAD

**Issue by thatigonc** [backend-br/vagas#1686]
Estamos com oportunidade para atuar com backend.

***Conhecimentos/Experiência desejados:***

- .NET Framework 
- SQL
- Algum framework de Javascript (angular / vue / react)
- Mongo (diferencial)
- Ter trabalhado com integrações de API
Diferencial .NET Core

***Informações***

1 vaga júnior 
1 vaga pleno 
30 dias de descanso remunerado

***Processo seletivo***
Enviar CV + pretensão para: tatiane.goncalves@taking.com.br

💻Teste a ser realizado antes. 
💰 Faixa Salarial: R$5.000,00 a R$10.000,00.

**Comment by jonathanguilhermesouza** [comment]
@thatigonc  é PJ esse valor? Há possibilidade de home office?

**Comment by thatigonc** [comment]
> @thatigonc é PJ esse valor? Há possibilidade de home office?

@jonathanguilhermesouza Sim, contratação PJ. Não há possibilidade de HO, vaga presencial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
