### ISSUE TITLE
[SÃO PAULO] Dev. PL/SQL (B2W)

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1687]
Empresa de grande porte, do ramo varejista online, estilo Google, situada na Vila Olímpia - SP
Contratação PJ

Requisitos:
- Análise, especificação e desenvolvimento de functions, triggers, procedures e views em banco de dados Oracle (PL/SQL);
- Análise e desenvolvimento de sistemas em Oracle Forms (12c).

Desejável:
- Conhecimento em Oracle Forms;
- Desenvolvimento de Interfaces e WebServices;
- Experiência com ferramentas de versionamento – GIT; 
- Tunning e performance de query;
- Linguagem Java;

Venha fazer parte desse time!    

Interessados encaminhar CV para aline.navarro@keepsimple.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
