### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na BRAIN SYSTEM

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1690]
### Sobre a empresa: BRAIN SYSTEM TECNOLOGIA

A Brain System atua no mercado de soluções tecnológicas há 15 anos, com sólida experiência em implementações de projetos voltados à área de atendimento e fidelização de clientes. Apoiados por uma equipe motivada e de alto desempenho buscamos fornecer aos nossos clientes produtos e serviços únicos e de alta qualidade. 

Focados sempre na melhor solução de negócio, promovemos o aumento da produtividade, a otimização do negócio e a redução de custos. Mantemos o compromisso ético e o respeito ao ser humano, desenvolvendo individualmente e trabalhando em equipe. 

Os profissionais da Brain System não só atuam no desenvolvimento de sistemas, como também na interação com o cliente para identificação das necessidades do negócio, proporcionando mais discernimento e inteligência na solução apresentada.

### Descrição:

Na Brain System o desenvolvedor irá participar da equipe de desenvolvimento de software de CRM, na execução de diversos serviços, como manutenção das plataformas Brain CRM, resolução de bugs quando necessário, criação de novas funcionalidades e novos formulários com regras específicas do cliente. Também irá desenvolver integrações através de Web Services/APIs.

### O profissional deverá ter conhecimento e experiência em:

.NET;
Visual Studio;
Javascript;
Frameworks front-end (BootStrap, ExtJs, outros);
Banco de Dados relacional SQL Server (mas se você tiver conhecimento em Oracle ou IBM DB2 também será válido);

### Benefícios:

Vale Refeição;
Plano de Saúde Amil;
Ambiente de trabalho descontraído.

### Informações complementares:

A Brain System fica localizada no bairro Vila Hamburguesa, região do Alto de Pinheiros (em frente ao parque Vila Lobos, acesso muito próximo pela estação de trem Villa-Lobos-Jaguaré).

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/brain_system1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
