### ISSUE TITLE
[São Paulo] Full-Stack Developer na Bovcontrol

### ISSUE THREAD

**Issue by FernandaAbreu** [backend-br/vagas#1692]
## Descrição da vaga

Olá, nós somos a Bovcontrol.

E nós estamos revolucionando o agribusiness no mundo!!!

Somos a 3 startup mais inovadora, segundo a Startse.

O time de desenvolvimento da BovControl está procurando desenvolvedor(a) full-Stack apaixonado por desafios exponenciais.

## Local

Escritório, São Paulo - Berrini

## Benefícios

- Vale refeição
- Vale transporte
- Plano de saúde
- Ambiente descontraído e informal

## Requisitos

**Obrigatórios:**
- C# 
- Asp.net Core 
- PHP 
- node.js
- react 
- firebase 
- elasticsearch 
- MySQL
- mongoDB 
- Git 
- HTML5 
- CSS3 (SASS)
- Google Material Design
- Noções de programação funcional
- Single Page Application
- JavaScript (ECMAScript 6)
- Consumo de API REST
- Ambientação em Linux ou Mac
- Processos e métodos ágeis (SCRUM, Kanban)
- Controle de versão via Git
- React + Redux
- Padrões de arquitetura e Design Patterns;
- Clean Code e boas práticas de desenvolvimento de software.

**Diferenciais:**
-  Vue.js
- Webpack / Gulp
- Teste unitário.
-  CI / CD 
- Inglês
 
## Contratação

 a combinar

## Nossa empresa

Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis.
Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva.

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Como se candidatar

Por favor envie um email para vagas@bovcontrol.com com seu CV anexado - enviar no assunto: Vaga Full Stack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
