### ISSUE TITLE
[Morumbi-SÃO PAULO] Dev PHP Pleno na Just Digital! 

### ISSUE THREAD

**Issue by alicesrossi** [backend-br/vagas#1694]
Conhecimentos necessários:
Sólidos conhecimentos em PHP;
Modelagem básica de banco de dados;
GIT;
Criação e consumo de API;
Testes de software;
Laravel/Symfony em sua versão mais atual

Desejáveis:
Conhecimento em Angular, HTML e CSS;
Design Patterns;

Local de trabalho:
SP - São Paulo

Benefícios:
- Vale Refeição  
- Vale Transporte
- Assistência Médica e Odontológica
- Seguro de Vida em Grupo
- Parceria com a Gympass e outros convênios em estabelecimentos e instituições de ensino

**Será que você é nosso próximo(a) Juster?**

Se candidata aqui e vem bater um papo com a gente!
https://justdigitalbr.recruitee.com/o/dev-php-pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
