### ISSUE TITLE
[Piracicaba-SP] Desenvolvedor Fullstack / Backend [Geplant Tecnologia Florestal]

### ISSUE THREAD

**Issue by vrechi** [backend-br/vagas#1698]
## Descrição da Vaga

A Geplant busca Desenvolvedor Pleno/Sênior (de preferência Fullstack, ou um Backend com vontade de aprender e ampliar os horizontes).

**Requisitos Obrigatórios:**
Graduação completa na área de TI ou áreas correlatas
Cinco anos de experiência (após graduação) OR doutorado na área

**Desejável:**
Git | PostgreSQL | APIs RESTful | Cloud | Linux | Python | Javascript | Node.js | Frameworks frontend

**Como será seu dia a dia:**
- Pesquisar e implementar novas tecnologias e melhorias em nossa plataforma
- Aplicar e disseminar boas práticas de versionamento, desenvolvimento, testes, documentação, integrações, cloud, segurança e metodologias ágeis
- Apoiar e mentorar a equipe do projeto

## Local de trabalho
Piracicaba-SP
(Presencial, pelo menos a maior parte do tempo)

## Remuneração
R$ 7.370/mês

## Quem somos
Somos a **Geplant**, uma empresa de tecnologia para a área florestal e agro, com cultura de startup e ambiente que promove a inovação, aprendizado e desenvolvimento.
Estamos desenvolvendo uma solução de base tecnológica e científica para nosso setor, que integra fontes de Big Data e algoritmos de inteligência analítica e espacial para gerar insights e melhoria de processos.
Faça parte do nosso time!

## Contato
Envie seu currículo para: contato@geplant.com.br (com o assunto: Vaga TI)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
