### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Backend PHP- Grupo Padrão

### ISSUE THREAD

**Issue by GrupoPadrao** [backend-br/vagas#17]
EXPERIÊNCIAS E CONHECIMENTOS (OBRIGATÓRIO)

**CONHECIMENTO** EM:
- JSON
- HTML / CSS BOOTSTRAP
- BANCO DE DADOS MYSQL
- PHP 
- JAVASCRIPT JQUERY
- NODEJS
- GULP
- SEO E OTIMIZAÇÃO DE SITES.
-WORDPRESS
- SABER TRABALHAR COM LAYOUT RESPONSIVO
- NOÇÕES DE API’S: GOOGLE, FOURSQUARE, INSTAGRAM, ETC.
             -
**EXPERIÊNCIAS** DESEJADAS (DIFERENCIAL)

•	DESENVOLVIMENTO DE APP NATIVO.
•	CONHECIMENTO EM PLATAFORMA DE E-COMMERCE.
•	 JAVASCRIPT: ANGULAR, EMBER.JS, ETC).
•	NOÇÕES DE UX 

**HABILIDADES:** 

•	HABILIDADES PARA CRIAR UM CÓDIGO LEGÍVEL E DE FÁCIL MANUNTENÇÃO.
•	HABILIDADE PARA TRABALHAR EM EQUIPE.

**DESCRIÇÃO** DAS ATIVIDADES: 

•	DESENVOLVER SISTEMAS WEB.
•	DESENVOLVER PORTAIS.
•	ESTRUTURAÇÃO DE BANCO DE DADOS.
•	INTEGRAÇÃO COM API’S.
•	TESTAR PROJETOS CRIADOS.
•	DAR SUPORTE PARA TODAS AS ÁREAS DA EMPRESA NO QUE DIZ RESPEITO A DESENVOLVIMENTO DE FERRAMENTAS.
•	REALIZAR CODIFICAÇÃO DE INTERFACES PARA SITES RESPONSIVOS.

****Escritório no bairro do Pacaembu-SP/SP
40 horas semanais - flexibilidade de horário
CLT ou PJ

****Enviar currículo para curriculos@gpadrao.com.br com pretensão salarial.

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
