### ISSUE TITLE
DEV na inDecks

### ISSUE THREAD

**Issue by Ricardoaugustovt** [backend-br/vagas#170]
## Descrição da vaga
Atuar em projetos e aplicações utilizando ferramentas/frameworks com objetivo de realizar integrações com a plataforma Microsoft SharePoint Online e 2013 OnPremises.

## Local
Remoto ou Onsite (Piracicaba SP)

## Benefícios
(*) Estes estão ligados a benefícios da CLT, nós não damos nada.

#### Diferenciais
- Flexibilidade de horários
- Trabalho 80% remoto
- Linha de produtos em desenvolvimento
- Grandes oportunidades de crescimento

## Requisitos

**Obrigatórios:***
- 2 anos de experiência com SharePoint 
- Conhecimentos em C# e AngularJS

*Desejáveis:*
- Conhecimento das APIs e modelo de estrutura do SharePoint.
- Atuação no SharePoint Online

*Diferenciais:*
- Experiência com Gulp/Grunt, Bower, TFS Online

## Contratação
Pessoa Jurídica (PJ)

## Nossa empresa

A inDecks está no mercado de Consultoria para Softwares Corporativos há mais de 10 anos, atuamos no mercado desenvolvendo softwares customizados, atendendo contratos de suporte técnico e comercializando nossos próprios produtos. Com estas três frentes em pleno crescimento, temos a possibilidade de engajar adequadamente aos recursos contratados.
Focados em tecnologias Microsoft, buscamos inovações e conhecimento sempre. 

## Como se candidatar

Por favor envie um e-mail para contato@indecks.pro com seu CV anexado - enviar no assunto: Vaga DEV
Não esqueça de colocar sua pretensão salarial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
