### ISSUE TITLE
[REMOTO] - Última Semana - Desenvolvedor Backend & Engenheiro de Dados Sênior (Até US$ 5,000 mês)

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#1700]
Olá, pessoal, 

Nós já tínhamos aberto essa vaga anteriormente (issue #1609), mas infelizmente ainda não conseguimos encontrar um profissional realmente sênior para preencher a posição principal.

Nós já contratamos duas das três pessoas que prevíamos, mas essas duas não são sênior. Isso é, não tem longa experiência/vivência prática.

Precisamos de alguém com verdadeira **experiência prática** em sistemas distribuídos e que já tenha trabalhado em produção com sistemas de fila (Rabbit, Kafka, etc.), sistemas de processamento distribuído (Spark, Storm, etc.) e com bancos de dados NoSQL em clusters grandes (Cassandra, Aerospike, etc.).

**A data para início na empresa será no dia 15 de outubro e o profissional selecionado se reunirá com toda a equipe em Austin (Texas, US), com todas as despesas pagas pela empresa.**

## Segue novamente os detalhes da vaga:

Estamos recrutando 2 a 3 pessoas para trabalhar remotamente para uma empresa dos EUA. O profissional deve ter **acima de 10 anos de experiência** prática com programação de sistemas distribuídos, já tendo utilizado em produção tecnologias como: Cassandra, ElasticSearch, Kafka e Spark.

Para se candidatar, basta enviar uma mensagem para o email abaixo com o seu currículo (em inglês):
gabriel@simbioseventures.com

**Carga horária:**
44 horas semanais.

**Remuneração:**
- De US$3,000,00 (aprox. R$ 12.500,00) a US$5,000.00 (aprox. R$ 20.500,00) por mês.
- O pagamento sempre será feito em dólar, portanto o valor pode aumentar significativamente nos próximos anos.

**Forma de contratação:**
Prestação de Serviços (PJ)

**Local de trabalho:**
Trabalho exclusivamente remoto, mas com possibilidade de pagamento de um co-working para o profissional, caso ele não queira trabalhar de casa.

**Benefícios:**
- Notebook da empresa: MacBook Pro (15'', 8cores 2.4GHz, 32Gb, 2TB SSD, etc.)
- Possibilidade de pagamento de um co-working para o profissional, caso ele não queira trabalhar de casa.
- Horário de trabalho realmente flexível
- Estabilidade. Os próximos 10 anos estão assegurados sem pressão nas vendas, visto que o foco está no desenvolvimento do produto.
- Ter a possibilidade de trabalhar com grandes profissionais. Pessoas que tem criado várias empresas de tecnologia em diversas partes do mundo. Nossos sócios são ex-CXX da Rackspace. 
- Possibilidade de mudar para os EUA em 2 anos se o profissional demonstrar alto desempenho. 
- Viagens frequentes para Austin (temos 3 deliveries que deveriam ser feitos lá só nos próximos 11 meses)

**Candidatar:**
Para se candidatar, basta enviar uma mensagem para o email abaixo com o seu currículo (em inglês):
gabriel@simbioseventures.com

**Comment by walteraa** [comment]
@TheTonon take a look at that opportunity! :)

**Comment by THAYLLER** [comment]
Cara ja penso em pegar alguem disposto a aprender oferecer um salario menor e treinar?

**Comment by gmenegatti** [comment]
@thayller, isso é o que nós sempre fizemos e continuaremos fazendo na Simbiose Ventures, mas essa empresa dos EUA precisa de alguém pronto agora, eles não tem esse tempo pra esperar a pessoa se preparar/formar.

**Comment by THAYLLER** [comment]
Mas tipo no meu caso não tenho 10 anos de experiencia mas ate tenho conhecimento nas tecnologias que vcs pedem, oque me impossibilita ai e so os 10 anos de experiencia, eu tenho apenas 5 anos na area

**Comment by gmenegatti** [comment]
@THAYLLER, se você realmente tem conhecimento/experiência prática (em produção) com as tecnologias, sugiro que se candidate. Não custa nada.

**Comment by rof20004** [comment]
@gmenegatti Não tenho perfil para a vaga, mas sugiro que vocês façam um teste técnico bem apurado para descobrir se é senior ou não.

**Comment by maruen** [comment]
Opa, @gmenegatti, como tá? Alguma nova vaga que eu possa concorrer?

**Comment by gmenegatti** [comment]
Infelizmente não @maruen.

Te desejo sucesso.
