### ISSUE TITLE
[Rio de Janeiro] - Desenvolvedor Full Stack Jr

### ISSUE THREAD

**Issue by pkdesouza** [backend-br/vagas#1701]
**Cargo:** Desenvolvedor Full Stack Jr. 
**Empresa:** Ingresso.com
**Local:** Centro - Rio de Janeiro

**Missão da área:** Desenvolver manutenções corretivas e evolutivas nos diferentes sistemas da Ingresso.com com qualidade e aderência máximas às solicitações feitas, visando sempre superar as expectativas dos clientes finais, garantindo sempre robustez ao produto.

**Cenário:** A equipe de Desenvolvimento realiza manutenção nos mais diversos sistemas da Ingresso.com (Arena, Legado, site Legado, site novo e eventos), cada qual com sua tecnologia (Asp .Net Mvc / .Net Core / .Net Framework / SQL Server / MySql).  Como a quantidade de clientes e de sistemas é grande, o volume de versões é proporcional, bem como em número razoável também são as liberações de novas releases.

**Detalhamento:** 
    Desenvolver novas funcionalidades nas mais diversas tecnologias 
    Resolver não conformidades nas mais diversas tecnologias

 **Comportamental:**     
    Perfil altamente técnico, detalhista, perfeccionista, focado, alguma capacidade de comunicação, bom gerenciamento da rotina, bom raciocínio lógico, capacidade de trabalhar sobre pressão e com prazos definidos. 

**Técnico:** 
    Bons conhecimentos de Orientação a Objetos, Princípios e Padrões de Projeto 
    Conhecimento de ferramentas de controles de versão e atividades (Git e JIRA) 
    Conhecimento da linguagem Vb.Net     
    Conhecimento da linguagem C#     
    Conhecimento da linguagem JavaScript     
    Conhecimento da linguagem Html     
    Conhecimento da linguagem Ansi SQL e TSQL     
    Conhecimento de LINQ     
    Conhecimento do Framework Asp.Net Mvc     
    Conhecimento de .Net Core 

**Principais atividades:**    
     Acessar painel de tarefas priorizadas     
     Participar de reuniões de kickoff     
     Participar de reuniões periódicas de status de projeto     
     Baixar o código especificado na atividade do repositório 
     Criar testes unitários baseados na especificação     
     Efetuar os desenvolvimentos necessários     
     Enviar para a revisão de código     
     Subir o código para o repositório Lançar horas nas atividades para controle 
     Atuar nos problemas de Produção

Caso você se encaixe no perfil anexo ou conheça alguém, favor enviar o currículo para **rh@ingresso.com** colocando no Assunto do email o NOME COMPLETO da vaga.
Os emails que não tiverem no assunto o NOME COMPLETO da vaga serão descartados.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
