### ISSUE TITLE
Arquiteto de Desenvolvimento .NET C#

### ISSUE THREAD

**Issue by thaishbrasil** [backend-br/vagas#1704]
Enviar Cv para: thais.fernandes@looke.com.br

**Sobre o Looke**
Somos a mais completa plataforma de Streaming do mercado Brasileiro 
Trabalhamos com opções de assinatura, locação e compra de conteúdos em Vídeo.
Oferecendo filmes recém-saídos dos cinemas, clássicos, shows, documentários, séries exclusivas e os mais queridos conteúdos infantis, levando diversão para todos os targets.

Com o que você vai trabalhar: 
Atuar no desenvolvimento e manutenção do back das nossas plataformas de Streaming com gestão de banco, servidores e criação de serviços.
Desenvolvimento de processos inovadores de encoding e encriptação de filmes e séries.
Integração com plataforma de parceiros, meios de pagamentos etc.
Desenvolver aplicativos para Smart TV e STB (set-top box).
Desenvolver aplicativos para console de jogos como Xbox e PlayStation.

**Atividades**
Colaborar com equipe de trabalho trazendo criação de soluções inovadoras e de Performance
Desenvolver novos componentes
Construir APIs e serviços de backend
Contribuir em decisões de arquitetura do projeto;
Criar ferramentas para medir e otimizar a performance dos nossos serviços;
Integrar serviços terceiros, como gateways de pagamento e ferramentas de e-mail marketing.
Priorizar e tratar bugs e exceções reportados em produção;

**Requisitos para se candidatar**
Conhecimentos em MVC e WebAPI.
Ser atualizado sobre as mais recentes ferramentas de framework e criação de bibliotecas;
Conhecimentos em Software Design Patterns
Conhecimentos de Windows Azure
Conhecimentos avançados em Banco de Dados SQL Server

**Nossa Cultura**
Somos uma empresa jovem inspirada em tecnologias disruptivas. Oferecemos um ambiente de trabalho que incentiva a inovação e a produtividade, garantido liberdade com responsabilidade.
O Looke é uma Plataforma brasileira. Multiplataforma.
Temos aplicativos de iOS, Android, TV conectada, Playstation, PC, Safari, Apple TV, Android TV.
Tudo isso a gente faz aqui. A gente faz a plataforma inteira.
Fazemos toda a parte de Encriptação, Decriptação, Encoding de vídeo.
100% dessa tecnologia, é nacional, proprietária da empresa e, é feita toda aqui com a gente.
Você, se vir a ser contratado, virá para trabalhar numa área específica de Backend para atender essa e outras plataformas de Vídeo.
O Streaming de Vídeo é presente da distribuição de Vídeo por internet. O que a gente conhece hoje de distribuição linear de TV, aqueles canais que a gente contrata, isso vai acabar. 100% está se tornando internet. Está se tornando no mundo inteiro. Como a Netflix fez isso, a Amazon Prime, o próprio Itunes, o Google Play...
É com isso que a gente quer que você venha trabalhar.
Distribuição de Vídeo por internet.

**Alguns links na mídia sobre alguns aspectos do Looke**
www.looke.com.br

https://www.linkedin.com/posts/fernandesthais_c-vagas-streaming-activity-6586967773409230848-bNIW

https://complemento.veja.abril.com.br/entretenimento/servicos-streaming/
https://www.meioemensagem.com.br/home/midia/2019/07/15/com-ouro-verde-plataforma-looke-estreia-a-exibicao-de-novelas.html
https://www.linkedin.com/posts/fernandesthais_quer-ver-o-meu-conte%C3%BAdo-e-minhas-vagas-com-activity-6570356603252428800-kc2x

![desenvolvedores](https://user-images.githubusercontent.com/47364879/66335187-d4c5eb80-e910-11e9-9df5-a096ba0e4244.jpg)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
