### ISSUE TITLE
#VAGA [ Creditas ] [Eng. de Software Back-End Pleno] [SÃO PAULO]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#1706]
Para trazer inovação ao mercado de empréstimos, **nós apostamos em tecnologia**. É com ela que escalamos o negócio, otimizamos processos e melhoramos a experiência dos clientes. Nossa plataforma foi criada dentro de casa utilizando tecnologia open source, **seguindo a filosofia agile e suas práticas**. Mas nosso negócio mesmo são as pessoas: não abrimos mão do atendimento personalizado, prestando consultoria e oferecendo educação financeira para empoderar o cliente a tomar a melhor decisão.

**O que você precisa?**
_Experiência em desenvolvimento **Java**;
Habilidade em desenvolver e implementar **APIs**;_

**O que você vai fazer?**
_- Desenvolver garantindo funcionalidade, manutenibilidade e velocidade, além de garantir práticas de teste e qualidade;_
_- Garantir que todas as soluções técnicas estejam alinhadas a estratégia do negócio e entender **OKRs** e iniciativas relacionadas ao produto;_
_- Ajudar o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;_
_- Colaborar com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam vários times;_
_- Trabalhar em um ambiente colaborativo, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads._

**Quais são os benefícios?**
_Vale refeição
Vale transporte
Estacionamento/Fretado/Bicicletário
Assistência médica
Assistência odontológica
Seguro de vida
Auxílio educação/estudo e Aulas de Inglês in company
Licença-maternidade é de 6 meses e a licença-paternidade de 20 dias
GymPass_
_Salário **R$ 9.000,00** CLT_

**E o processo?**
_A inscrição é feita pelo site da Intera: http://bit.ly/2MnSM7b_

**Comment by VitorChaves21** [comment]
Achei legal. A vaga oferece auxílio mudança?

**Comment by AndreBorim** [comment]
@VitorChaves21, simm! A Creditas está disposta à auxiliar na mudança.

**Comment by 1pedro** [comment]
Olá, gostei muito da oportunidade. Você tem o endereço de trabalho?

**Comment by AndreBorim** [comment]
> Olá, gostei muito da oportunidade. Você tem o endereço de trabalho?

Simm!
Local de trabalho: Av. Engenheiro Luís Carlos Berrini, 105, 12º andar – Itaim Bibi, CEP 4571010, São Paulo – SP

**Comment by thales-assis** [comment]
Curti a oportunidade, já me candidatei!

**Comment by AndreBorim** [comment]
> Curti a oportunidade, já me candidatei!

Legal!! Qualquer dúvida pode me chamar :D

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
