### ISSUE TITLE
[Uberlândia - MG] Backend Junior Python - NetSupport

### ISSUE THREAD

**Issue by vmesel** [backend-br/vagas#1707]
Atributos da vaga:
Empresa: NetSupport
Faixa salarial: R$ 1.000,01 a R$ 3.000,00
Estado: Minas Gerais
Local da vaga: Uberlândia
Nível: Junior
Aceita Remoto?: Não
Descrição da vaga
A NetSupport é uma startup em estágio de scaleup que opera uma plataforma de Suporte Técnico de TI, que realiza atendimentos através de uma comunidade de Supporters (profissionais freelancers).

Ainda acha que essa vaga é a sua cara? Então venha fazer parte do nosso time!

O Profissional que integrará nosso time de desenvolvimento irá crescer junto com a gente e contribuir no nosso negócio com a sua formação acadêmica.

Requisitos
﻿Formação
* Curso superior na área de tecnologia da informação completo ou em andamento

Requisitos
* Linguagem Python framework Flask
* API REST
* Versionamento de código com git e github
* Banco de Dados SQL (PostgreSQL)

Desejável conhecimento em:
* Framework Vue.js
* HTML, CSS e JavaScript
* Conhecimento básico em Sistemas Operacionais (Linux)
* Desenvolvimento Agil Scrum.

[Se inscreva aqui](https://www.pyjobs.com.br/job/841/?utm-source=backendbr)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
