### ISSUE TITLE
[São Paulo, SP ou Remoto] Desenvolvedor backend Python [Somar Meteorologia]

### ISSUE THREAD

**Issue by jonathanabila** [backend-br/vagas#1708]
## Descrição da vaga
Estamos procurando por um(a) desenvolvedor(a) apaixonado por desafios e proativo para fazer parte do nosso time.

Como Desenvolvedor Backend você terá que criar, desenvolvedor e manter uma arquitetura de microsserviços, para clientes internos e externos - tendo todo o leque de serviços da AWS quando necessário.

### Local

No escritório situado na Vila Leopoldina - SP, remoto parcial ou completamente remoto - Temos amigos em todos os fusos do brasil :bowtie:

## Requisitos
**Mandatórios:**
- Pyhton.
- GIT.
- Ser proativo e gostar de trabalhar com equipes multidisciplinares.

**Desejáveis:**
- Vivência com Serverless.
- Conhecimentos de AWS ou GCP.
- Metodologias Lean/Agile.
- CleanCode.
- Conhecimento em design patterns.
- Experiência em microsserviços.
- Experiência com event drive architecture.
- Gostar de trabalhar em um ambiente que incentiva a inovação.

Lembre-se, você não precisa cumprir todos os desejáveis, eles são como metas que podem ser de curto prazo para você tomar um plano de desenvolvimento ou coisas que gostaríamos de encontrar no candidato, mas que não será critério de eliminação.

## Contratação
O formato de contrato é PJ e a remuneração varia de acordo com o perfil de conhecimento do desenvolvedor.
:moneybag: Faixa salarial: R$ 3.500,00 a R$ 8.000,00.

## Sobre a empresa
Junte-se a Somar Meteorologia, uma das principais empresas privadas do setor de meteorologia do país atuando desde 1995 em diversos segmentos.

## Como se candidatar
**Desafio técnico**

É de grande interesse que você consiga realizar nosso desafio técnico para que possamos ter uma breve noção técnica relacionada a boas práticas, testes, organização, solução do problema proposto e outros. É claro que a avaliação técnica é apenas uma parte dentre outras que serão avaliadas.

[https://github.com/somarmeteorologia/challenge/tree/master/backend](https://github.com/somarmeteorologia/challenge/tree/master/backend)

Vale lembrar que não há prazo para a entrega do desafio - o objetivo é que você consiga entregar um código de qualidade sem deixar de entregar com os seus comprometimentos atuais.

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ

**Comment by iasj** [comment]
O que significa o label `PJ`?

**Comment by THAYLLER** [comment]
Cara significa pessoa juridica ou seja ter cnpj

**Comment by iasj** [comment]
Valeu

**Comment by jonathanabila** [comment]
Só para adicionar um pouco sobre, se você faturar até 6750,00 na legislação atual pode abrir o CNPJ como um MEI e com isso pagar somente 54,90 como imposto, incluindo todas as contribuições obrigatórias de um profissional.

**Comment by gabrielponto** [comment]
Até quando vai o processo seletivo? Eu só posso começar a fazer o teste na próxima semana, então não sei se ainda há tempo.

**Comment by jonathanabila** [comment]
> Até quando vai o processo seletivo? Eu só posso começar a fazer o teste na próxima semana, então não sei se ainda há tempo.

@gabrielponto O desafio está aberto por tempo indeterminado, então pode ficar tranquilo para fazer quando puder.

**Comment by leonardo1909** [comment]
O desafio pode ser feito utilizando Django Rest?

**Comment by jonathanabila** [comment]
> O desafio pode ser feito utilizando Django Rest?

@leonardo1909 Pode sim!

**Comment by cr4zyd3v** [comment]
Ainda está valendo?

**Comment by jonathanabila** [comment]
@marciks Sim!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
