### ISSUE TITLE
[REMOTO] Desenvolvedor Fullstack Node.js na [Artyou.global]

### ISSUE THREAD

**Issue by felipelopes6** [backend-br/vagas#171]
Procuramos os melhores para construir o melhor software para quem trabalha com obras de arte, acervos documentais, acervos históricos e público.

## Requisitos

Obrigatórios

-  Experiência com Node
- Experiência em MongoDB
- Angular
- Linux
- Git
- Javascript ES6

Desejáveis:

- Hapi, Express
- MySQL
- Gerenciamento de equipe

## Informações sobre contratação

A vaga é remota e temporária e a contratação é por PJ.

## Como se candidatar

Envie o seu **currículo**, **Skype** e **GitHub** através deste [Link](https://help.artyou.global/hc/pt-br/requests/new)

## Informações Artyou.global
[Artyou.global](https://artyou.global/)

## Labels
- Remota
- PJ
- Temporária
- FullStack

**Comment by ghost** [comment]
Pode ser iniciante em NodeJS e MongoDB?

**Comment by kivervinicius** [comment]
Aceita horário diversificado? (jornada dupla)

**Comment by felipelopes6** [comment]
@Finacio Para essa vaga em especifico, estamos procurando alguém com uma certa experiencia. Porém você pode enviar o seu currículo, que iremos analisar e adicionar no nosso banco!

**Comment by felipelopes6** [comment]
@kivervinicius Olá, tudo bem? Para essa vaga não, mas estamos abertos para receber seu currículo para futuros contatos.
