### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) PHP Júnior/Pleno na [Novovarejo.com]

### ISSUE THREAD

**Issue by gpupo** [backend-br/vagas#1710]
## A Empresa
A Novovarejo.com é uma empresa especializada no desenvolvimento de
tecnologias e estudo de dados e comportamento para o varejo, que facilitem e
ajudem no relacionamento entre as marcas (produtos e serviços) e seus
consumidores identificando e promovendo soluções para o segmento
de Mobilidade.

Nosso foco principal é aliar tecnologia à experiência de compra, promovendo a
conveniência e certeza sobre a tomada de decisão de compra por parte dos
consumidores, para quem dedicaremos todo o nosso esforço.

Desta forma, acreditamos que promovemos o consumo de forma inteligente, e
consequentemente um capitalismo também consciente.

A empresa fica localizada no bairro Campina do Siqueira, próximo ao Park Shopping Barigui.

### Perfil profissional
Entendemos que a composição de um time é feita com múltiplos perfis que se complementam e a neurodiversidade é bem vinda.
Buscamos pessoas que se dedicaram e persistiram em aprender sobre o desenvolvimento Web, melhores práticas e a gama gigantesca de conhecimentos necessários para um desenvolvimento moderno de aplicativos. Também estamos abertos aos pioneiros do desenvolvimento que querem se reinventar e desejam trabalhar em projetos modernos. Se você é dedicado e ama programar, possivelmente deva falar conosco.

### Conhecimentos e Habilidades

* Domínio do desenvolvimento de aplicações com PHP.
* Familiaridade com banco de dados;
* Conhecimento basico da infraestrutura da web (aplicações, protocolo, servidores web);
* Capacidade de desenvolvimento básico com javascript;
* Experiência no uso de frameworks relevantes da linguagem;

#### Principais requisitos
* PHP (Versões 5.5 e 7);
* Banco de dados Mysql/MariaDb
* JavaScript;
* Git;
* HTML
* CSS

#### Habilidade/Experiência que serão consideradas como diferenciais
* NodeJS;
* Git Flow;
* Micro Serviços;
* Threads;
* Web Service arquitetura REST;
* Metologias ágeis;
* Sass
* Bootstrap

## Contratação e benefícios

* Contratação regime CLT;
* Plano de saúde;
* VT;
* VR ou VA;

Interessado? Envie seu currículo para [cto@novovarejo.com](mailto:cto@novovarejo.com), com o título desta vaga no assunto do e-mail, junto com sua pretensão salarial.

## Labels
* Alocado
* CLT
* Júnior
* Pleno
* PHP

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
