### ISSUE TITLE
[São Paulo, SP] Pessoa Desenvolvedora Node.js (Pleno/Senior) na MutantBR

### ISSUE THREAD

**Issue by wwwflorencio** [backend-br/vagas#1711]
## Sobre o projeto:
Manutenção de bots com interfaces de voz em uma equipe multidisciplinar com foco na experiência do usuário e humanização em suas mais diversas nuances, usando diversas tecnologias de NLP (Natural Language Processing) como suporte.

## Requisitos Técnicos:
* Proficiente em Node.js
* ES6+
* Experiência em Testes
* Experiência no design e construção de serviços da API REST
* Experiência em metodologias Ágeis
* Conhecimento em banco de dados não relacionais (Elastic Search, Redis)
* Familiaridade com TypeScript

## Diferencial:
* Experiência em TypeScript;
* Experiência em serviços em clouds (AWS, Azure ou Google Cloud)
* Ter participado da construção de Chatbots
* Experiência em outras linguagens (Java, Python, C#, Scala, etc.)

## Beneficios:
* Plano de Saúde
* VA/VR
* Auxílio Creche
* Gympass
* Plano Odontológico
* Care Pets
* Vale Transporte
* Seguro de Vida
* Massoterapia
* PLR de até um salário

Local de trabalho (Alocado): [Cidade Jardim SP](https://www.google.com/maps/place/Mutant+Hungria/@-23.5820301,-46.6920314,15z/data=!4m2!3m1!1s0x0:0xd79187b82267bf52?sa=X&ved=2ahUKEwi6npeJq4_lAhV5HrkGHQOnATUQ_BIwD3oECAgQCA)
Tipo de contratação: CLT
Horário de trabalho: 40h/semana flexível

# Como se candidatar
Envie um email para marcos.florencio@mutantbr.com com seu CV em anexo. 
Enviar no assunto: **VAGA Pessoa Desenvolvedora Node.js (Pleno/Senior)**

-------
[Mais sobre a MutantBR](https://mutantbr.com/)

**Comment by danielsidev** [comment]
Olá!
Essa vaga também é remoto ou só presencial?
Desde já, obrigado!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
