### ISSUE TITLE
[SANTA MARIA - RS]    Programador C#    [SYNTESIS]

### ISSUE THREAD

**Issue by RHLucasCL** [backend-br/vagas#1713]
### **PROGRAMADOR C#**

Quer assumir um desafio e desenvolver soluções inovadoras para o mercado? Já pensou em trabalhar em uma empresa que impacta a rotina de mais de um milhão de usuários? Então, #VemProTime

### **Requisitos**
- Formação concluída ou em andamento em Tecnologia da Informação.
- Conhecimento em lógica de programação e orientação a objeto.
- Não é necessária experiência em linguagem C#

### **Cadastre seu currículo na vaga PROGRAMADOR no link: https://bit.ly/31D2ys3**

Na Syntesis, você conta com salário compatível com o Mercado |
Mix de benefícios (Vale-Alimentação, Vale-Transporte, Plano de Saúde, Programa de Recompensa, Auxílio Educação) |
Capacitação contínua para apoiar as tarefas Operacionais.

![Programador](https://user-images.githubusercontent.com/55497074/66505125-11c0e800-eaa1-11e9-9f97-4947820b8a01.jpg)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
