### ISSUE TITLE
[Porto Alegre - RS] Devs Back-End - Node.JS Pleno / Sênior [4all Tecnologia] 

### ISSUE THREAD

**Issue by micheliane** [backend-br/vagas#1714]
**DESCRIÇÃO DA VAGA**
Essa oportunidade é para Fintech do Hub. São os meios de pagamento do hub. Fintech as a service, ou seja, criamos fintechs, pois os meios de pagamento estão mudando. Saiba mais acessando: http://somosphi.com

Aproveite para conhecer um pouquinho mais sobre como é a vibe da 4all clicando aqui 👉 www.instagram.com/pordentroda4all 😉

**RESPONSABILIDADES E ATRIBUIÇÕES**
Aqui no hub 4all nossos desenvolvedores back-end precisam ter no minimo esses conhecimentos:
Node.js (javascript);
Git (gitlab);
Rest/Http;
SQL (MySQL);
Além disso, nossos devs prezam muito:
Clean Code;
Principios SOLID.
Realizamos também testes em nossos códigos, então é muito interessante saber fazer :
Testes unitários e de integração.
Por aqui nós utilizamos os conceitos e tecnologias listadas abaixo, se você tiver esse conhecimento será ótimo, senão é uma ótima oportunidade para aprender com a gente:
Aws (Ec2, S3, Lambda Functions, RDS, Elasticache);
Containerização de Serviços com Docker;
Orquestração de Containers com kubernets;
Microserviços em diversas linguagens (javascript, typescript, java);
Continuous Integration e Continuous Deployment.

**REQUISITOS E QUALIFICAÇÕES**
Superior completo ou em andamento em Ciência da Computação, Engenharia da Computação, ou áreas afins.

**INFORMAÇÕES ADICIONAIS**
O que oferecemos?
Explore todo o potencial de oportunidades de desenvolvimento e práticas do hub 4all aqui pelo nosso bot: http://bit.ly/BillBot 🤖

Liberdade com responsabilidade
Um ambiente de trabalho descontraído com colegas dispostos a te ajudar e a compartilhar conhecimento
Possibilidade de crescimento e desenvolvimento
Home office
Acessos a cursos do Alura
Gympass
Plano de saúde e odontológico da Unimed
VR ou VA
VT
40h semanais
Happy mensal 😊

**MANIFESTO 🤗**
A 4all é feita por pessoas que fazem a diferença.
E proporciona crescimento profissional e pessoal para todos que estão aqui.
Um lugar com um entrosamento cada vez maior.
De experiências únicas em um ambiente enriquecedor e gratificante.
Espaço para muito aprendizado e valorização do coletivo.
Uma galera incrível e uma equipe unida.
Onde a energia positiva encontra o clima perfeito.
Com oportunidades de aprendizado todos os dias.
Temos a motivação para o novo.
Somos engajados com o futuro.
Nossos dias são uma constante evolução.
Estamos sempre em busca do melhor.
Com criatividade para mudar, pensar grande e inovar.

Onde se candidatar? https://4all.gupy.io/jobs/65993
Dúvidas: entre em contato com rh@4all.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
