### ISSUE TITLE
[Exclusivo Remoto] Dev Back-End - Node.JS Pleno/Sênior [4all Tecnologia] 

### ISSUE THREAD

**Issue by micheliane** [backend-br/vagas#1715]
**DESCRIÇÃO DA VAGA**
É inquieto, pensa fora da caixa, tem sede de aprender coisas novas, curte tecnologia e adora compartilhar conhecimento? Então a 4all é o lugar certo pra ti!
Para fazer parte do nosso time de desenvolvimento, estamos em busca de profissionais para atuar home office, de qualquer lugar desse mundão. 🌎

E quando preciso, poderá contar com a infraestrutura dos nossos escritórios localizados em:
Porto Alegre - TECNOPUC
Pelotas - Parque Tecnológico
São Paulo - Cubo
Conheça um pouquinho mais sobre o nosso Hub 👉 http://bit.ly/hub4allTecnologia e saiba o que rola diariamente por aqui através do bit.ly/4allitxs 💚

**RESPONSABILIDADES E ATRIBUIÇÕES**
Trabalhamos com métodos ágeis e você estará em constante contato com a sua equipe, que será composta por profissionais de produto, desenvolvimento, designers e de negócio.
É importante que você entenda que uma boa aplicação deve resolver problemas das vidas das pessoas sem deixar de ser simples e intuitivo.
Alguém que acredite que um código limpo e bem organizado com padrões de design bem aplicados fazem a diferença.
Além de uma excelente habilidade técnica, esperamos também que você esteja sempre ligado nas novas tecnologias!

**REQUISITOS E QUALIFICAÇÕES**
O trabalho remoto requer maturidade e disciplina.
Por isso fique ligad@ no que é preciso para atuar nesse modelo.
Você deve ter um ambiente apropriado para o trabalho, onde consiga concentrar-se
Uma boa internet para a constante comunicação com o time é essencial
Pontualidade, conforme a combinação com a equipe
Você deve combinar previamente uma possível ausência com a sua gestão e relembrar o time na véspera

**INFORMAÇÕES ADICIONAIS**
O que oferecemos?
Explore todo o potencial de oportunidades de desenvolvimento e práticas do hub 4all aqui pelo nosso bot: http://bit.ly/BillBot 🤖

Liberdade com responsabilidade
Um ambiente de trabalho descontraído com colegas dispostos a te ajudar e a compartilhar conhecimento
Possibilidade de crescimento e desenvolvimento
Acessos a cursos do Alura
Gympass
Plano de saúde e odontológico da Unimed
VR ou VA
40h semanais

Se cadastre aqui: https://4all.gupy.io/jobs/57089

**Comment by THAYLLER** [comment]
O Boot nao mostra as tecnologias que vcs trabalham

**Comment by micheliane** [comment]
Oi! Ao iniciar a conversa por lá há opção: **Conta pra gente: o que mais desperta a sua curiosidade?**
Em seguida há as alternativas: **Tecnologias que usamos** 
Abrirá um novo campo para você escolher qual tecnologia tem interesse :)

Ao se cadastrar na vaga "Trabalhe de Onde Quiser" há pergunta filtro das tecnologias. Também pode acessar nossa página e verificar os perfis de cada oportunidade: https://4all.gupy.io/

Qualquer dúvida, só chamar.

**Comment by micheliane** [comment]
> O Boot nao mostra as tecnologias que vcs trabalham

Oi! Ao iniciar a conversa por lá há opção: Conta pra gente: o que mais desperta a sua curiosidade?
Em seguida há as alternativas: Tecnologias que usamos
Abrirá um novo campo para você escolher qual tecnologia tem interesse :)

Ao se cadastrar na vaga "Trabalhe de Onde Quiser" há pergunta filtro das tecnologias. Também pode acessar nossa página e verificar os perfis de cada oportunidade: https://4all.gupy.io/

Qualquer dúvida, só chamar.

**Comment by THAYLLER** [comment]
Sim eu me candidatei a vaga, acho que seria um bom candidato para sua empresa, pois das linguagens listadas eu conhecia todas praticamente.
As vagas em aberto todas tem chance de ser remoto?

**Comment by micheliane** [comment]
@THAYLLER legal! Vou avaliar! Sim, todas nossas vagas tem possibilidade de ser remoto. 
Abraço,
Michelle

**Comment by wesleybruno** [comment]
Não sei se tive ou azar ou o Bot está bugado, somente a opção de Mobile está funcionando, não consigo ver as tecnologias de backend, ainda estão com vagas em aberto?

**Comment by micheliane** [comment]
Oi @wesleybruno tudo bem? o bot já está normalizado :) Obrigada pelo aviso!

**Comment by iagovholanda** [comment]
Quando é retornado alguma resposta, para aqueles que ja se cadastraram para vaga ?

**Comment by micheliane** [comment]
Oi @iagovholanda boa tarde! O seu cadastro está ok. Estamos analisando os cadastrados realizados, não se preocupe. Qualquer dúvida, fico à disposição.

**Comment by THAYLLER** [comment]
@micheliane terá algum feedback para os candidatos? ja tem tempo que me inscrevi e não houve nenhum feedback

**Comment by micheliane** [comment]
Oi @THAYLLER os currículos estão sendo avaliados! Em breve você receberá retorno!

**Comment by THAYLLER** [comment]
Entendi @micheliane agradeço por responder a dúvida e parabens pelo trabalho 90% das empresas somente postam a vaga e nem tem a delicadesa e responder aos candidatos
