### ISSUE TITLE
[Alphaville / Barueri] Desenvolvedor PHP Backend Sênior na Talentify

### ISSUE THREAD

**Issue by dreanmer** [backend-br/vagas#172]
## Detalhes da Vaga

Localização: **Barueri, SP**
Contratação: **CLT**
Remuneração **R$6.000,00 - R$8.000,00/mês** 

### Benefícios: 

- Plano de Saúde (Amil);
- VA R$200;
- VR R$26 / dia;
- VT, fretado, ou estacionamento;
- Seguro de Vida;
- Horário Flexível;

### Responsabilidades da vaga

- Entender e melhorar a arquitetura do sistema; 
- Escalar sistemas; 
- Realizar testes de carga, identificar gargalos e otimizar o desempenho de sistemas;
- Identificar, monitorar e corrigir bugs e exceptions;
- Desenvolver testes automatizados e garantir a qualidade do software;

Experiência em infraestrutura, testes, monitoramento e otimização; 

### Experiência Requerida:

- PHP OOP (avançado);
- Testes unitários (intermediário);
- Noções básicas em DDD e MVC;
- MYSQL (avançado)
- GIT (intermediário);

### Experiência Desejável:

- Php 7.1 (principalmente type hinting);
- Phalcon (framework);
- Codeception (testes);
- Queues;
- AWS;
- Integrações de serviços externos (SOAP, REST, BATCH/FTP)

## Sobre Talentify

Acreditamos que a combinação Marketing + Tecnologia + Pessoas é a base do R&S do Futuro! E que todas as partes envolvidas em um processo seletivo podem ter uma experiência inteligente, ágil e descomplicada.

## Sobre a Equipe

Somos uma equipe enxuta de 5 desenvolvedores (backend) sênior, além de um designer e um frontend. Gostamos de sempre discutir a melhor implementação de uma task e contamos com a opinião de todos, para se dar bem aqui tem que saber defender bem sua idéia, mas também ouvir o colega e sempre tirar o melhor das conversas. Em unanimidade usamos linux + phpstorm e docker como environment, mas vc estará livre para usar o ambiente que lhe melhor lhe convir.

Inscrição rápida por aqui: https://br.talentflux.com/desenvolvedor-php-senior-barueri-sp-talentify-2
**---> Não se preocupe, a gente vai ler o seu currículo! rsrs... <---**

Dúvidas? alexandre@talentifyhr.com

## Labels

- PHP
- Sênior
- CLT
- Presencial

**Comment by reginaldojunior** [comment]
Vaga lindona :heart:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 mesês.
