### ISSUE TITLE
[São Paulo - Paulista] Designer UX SÊNIOR [GSW Software]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1721]
### **Descrição da Vaga**

Atuar em grande projeto de inovação. Com aplicativos web e mobile.

### **Experiência**

- Experiência de mais de 5 anos com Design de sistemas.

- Web/mobile design e desenvolvimento Front-end
- Linguagens de marcação como HTML, XML, XHTML, linguagens de folhas de estilo (CSS, XSL)
- Softwares de criação (Photoshop, Illustrator, Adobe XD);
- Prototipação com axure, justinmind ou similar Bootstrap (telas responsivas).

**Desejável**
AngularJS,Android e iOS.

Inglês intermediário

### **Local**
São Paulo - Paulista

### **Contratação**
PJ

### **Sobre Empresa**
A GSW é uma empresa referência, no desenvolvimento de soluções em Tecnologia da Informação, oferece a seus clientes sistemas de TI que se traduzem em melhorias significativas para o dia a dia do negócio, principalmente no que se refere à redução de custos e ao aumento da produtividade. Clientes: SPC Brasil, Embraer, Ericsson, Panasonic etc..

### **Candidatar**

Por favor, envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vaga UX

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
