### ISSUE TITLE
[São José dos Campos] Arquiteto Java [GSW Software]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1722]
### **Descrição da Vaga**
Arquiteto Java, atuar em grande projeto, alocação em cliente.

### **Experiência**

- Arquitetura de dados 
- Java, Nodejs,
- Spring, SpringBoot, Hibernate, etc..;
- Git, ferramentas de build contínuo; REST; TDD.

### **Local**
São José dos Campos

**### Benefícios**
Á combinar

### **Contratação**
PJ ( Á combinar)

### **Sobre Empresa**
A GSW é uma empresa referência, no desenvolvimento de soluções em Tecnologia da Informação, oferece a seus clientes sistemas de TI que se traduzem em melhorias significativas para o dia a dia do negócio, principalmente no que se refere à redução de custos e ao aumento da produtividade. Clientes: SPC Brasil, Embraer, Ericsson, Panasonic etc..

### **Como se candidatar**

Por favor, envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vaga Arquiteto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
