### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack Senior na GREEN LEGIS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1723]
### Sobre a empresa: GreenLegis

Sistema para a gestão da conformidade legal e gestão empresarial – Sistema Greenlegis. Módulos: Conformidade Legal, Aspectos Ambientais, Perigos Ocupacionais, Gestão de Fornecedores, Gestão de Ocorrências, Gestão de Documentos. 

### Descrição: Qual será o seu papel?

Dar manutenção e propor melhorias na nossa plataforma;
Propor soluções;
Manter a infraestrutura nuvem do sistema
Ser referência técnica para nosso time.
Desenvolver novos módulos do sistema

### Esperamos que você tenha experiência com:

C#;
JavaScript;
React;
.net Core;
TypeScript;
Aws;
Infraestrutura .

### Você vai amar trabalhar aqui se:

Estiver em busca de um ambiente de trabalho de MUITO crescimento;
Estiver em busca de um ambiente de trabalho com clima leve e amigável;
Quiser construir uma carreira junto com a gente ;)

### Benefícios:

Vale Transporte;
Plano de Saúde;
Seguro de Vida;
Vale Refeição (R$25);
Estacionamento.

### Informações Complementares:

Vaga presencial;
Contratação CLT;
Atualmente estamos no Estoril mas até dezembro estaremos em um novo escritório no coração da Savassi ;)
Atenção:
Estamos passando por algumas instabilidades no momento em nossa plataforma.

### Entre em contato diretamente com o recrutador da vaga via WhatsApp: http://bit.ly/greenlegis_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
