### ISSUE TITLE
[São Paulo, SP] Software Engineer Back End Pleno na Creditas

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#1727]
Esta é uma oportunidade **presencial** e conta com **auxílio mudança** para candidatos que não são de São Paulo =)

### Faça parte da nave Creditas
A Creditas é uma das empresas que mais cresce no Brasil e que mais se empenha em manter um ambiente de trabalho diverso e livre de preconceitos. Por isso, a oportunidade é aberta à todos os profissionais, e se você é **mulher, LGBTQ+ e luta diariamente contra preconceitos dentro do mercado de trabalho**, queremos deixar bem claro que esse é o seu momento de trabalhar num espaço construído com respeito, acolhimento e vontade de crescer <3 Não hesite em participar do processo seletivo, nós sabemos do seu potencial!

### Seu dia-a-dia como Software Engineer Back End:
É uma vaga para nível **Pleno**, onde suas principais atribuições serão:
Desenvolver garantindo funcionalidade, manutenibilidade e velocidade, além de garantir práticas de teste e qualidade;
Garantir que todas as soluções técnicas estejam alinhadas a estratégia do negócio e entender OKRs e iniciativas relacionadas ao produto;
Entender o impacto das soluções que o time desenvolve no usuário final;
Ajudar o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;
Colaborar com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam vários times;
Trabalhar em um ambiente colaborativo, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads;

### É muito importante que você tenha:
Conhecimento profundo em desenvolvimento com Java;
Habilidade em desenvolver e implementar APIs;
Boas práticas de programação (TDD e DDD, por exemplo);
Arquitetura Clean

### E será um diferencial:
Ter atuado ou atuar com Kotlin;
PHP;

### Benefícios
Remuneração: R$9.000 reais
Vale Refeição
Vale Transporte
Estacionamento/Fretado/Bicicletário
Assistência médica
Assistência odontológica
Seguro de vida.
Auxílio educação/estudo, aulas de inglês in company, licença-maternidade de 6 meses e licença-paternidade de 20 dias
Gympass

### Processo seletivo:
Inscrição através do link abaixo;
MatchMaker da Intera;
Entrevista com a Intera;
Entrevista com a Creditas;
http://bit.ly/2AXbEop

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
