### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Pleno na DR CONSULTA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1728]
### Sobre a empresa: Dr. Consulta

Você sabia que o dr. consulta é uma rede de centros médicos sem mensalidade, sem fila e sem burocracia? Trabalhamos para ajudar pessoas de todas as classes sociais a terem acesso a excelentes profissionais da saúde. Somos referência neste modelo de negócio, em que os profissionais ficam disponíveis para a população até para o mesmo dia, com atendimentos, exames e procedimentos com preços justos e cuidado e empatia com os pacientes.

### Descrição

Para nós, pacientes e profissionais da saúde estão em primeiro lugar e, para isso, precisamos ser ótimos CUIDADORES! Além disso, temos garra, senso de urgência e outros valores que nos levam a ser obstinados por resultados, afinal, estamos em constante crescimento e até 2023 queremos proporcionar acesso à saúde para 10 milhões de pacientes únicos!

### Aptidões e conhecimentos necessários

PHP
JavaScript
MySQL
Facilidade em trabalhar com prazos e metas
Agilidade e autonomia

### Benefícios

Vale Alimentação de R$ 142,00 mês
Vale Refeição de R$ 20,00 dia
Gympass
Cartão de acesso à saúde

### E mais...

-Metodologia Scrum
-Regime de contratação CLT
- HH uma vez por mês
- Cervejas liberadas às sextas-feiras
- Mesa de ping-pong
- Talks a cada bimestre com profissionais referências do mercado
- Entre outras ações

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/drconsulta_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
