### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Pleno na STUDIO VISUAL

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1729]
### Sobre a empresa: Studio Visual

Somos uma agência com foco em soluções digitais para empresas de pequeno, médio e grande porte. Estamos no mercado há mais de 15 anos, somando grande experiência em tecnologia e inovação, sempre com foco no usuário final.

### Descrição: O que você irá fazer?

Desenvolvimento de aplicações WEB, utilizando as melhores práticas do mercado, com foco na qualidade da entrega.

### Requisitos:

PHP;
JavaScript;
HTML;
CSS;
Bootstrap;
jQuery.

### Será um diferencial se você conhecer:

Wordpress
Laravel
Angular
Docker
Ferramentas de versionamento de codigo.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/studiovisual_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
