### ISSUE TITLE
[SP - Barra Funda] Desenvolvedor(a) Python

### ISSUE THREAD

**Issue by VivianeCrisogano** [backend-br/vagas#173]
**## Oportunidade Desenvolvedor(a) Python - São Paulo**
**Sobre a shopper.com.br:**
Somos o supermercado 100% online que mais cresceu em 2017.
Recebemos um prêmio de R$ 1 milhão para desenvolver tecnologias que revolucionem a forma como as pessoas fazem compras.
Acreditamos que com trabalho duro, usando tecnologias e modelos de negócio inovadores, podemos transformar a sociedade e entregar mais tempo, energia e dinheiro às pessoas.
Levantamos da cama todos os dias com esse propósito em mente: criar soluções para que os brasileiros vivam vidas mais inteligentes. Nossa cafeína diária é a vontade de servir, e servir bem (muito bem!)
Estamos em uma fase de expansão e crescimento, e, para que isso aconteça, queremos gente do nosso lado que acredite na nossa missão e que tenha muuuita vontade de crescer e fazer um trabalho incrível!

**Descrição da vaga:**
Responsabilidades:
Desenvolver alterações/melhorias no site da shopper.com.br.
Local
Escritório - Avenida Marquês de São Vicente, 1619 - Barra Funda.

**Benefícios**

Ambiente de startup, informal, de muito aprendizado e de possibilidade de crescimento muito rápido, nosso trabalho é focado em meritocracia, então, só depende de você!
Requisitos:
- Conhecimentos em: JavaScript, GIT, HTML5, CSS3, Python
- Será considerado diferencial conhecimentos em Jungle, Linux, Unix, MySQL

**Contratação:**
PJ a combinar

**Como se candidatar:**
Por favor envie um email para vagas@shopper.com.br com seu CV em anexo - enviar no assunto: Desenvolvedor Python

**Comment by reginaldojunior** [comment]
teste

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
