### ISSUE TITLE
[Home Office] - Desenvolvedor NodeJs e React na WA Project

### ISSUE THREAD

**Issue by gustavowaproject** [backend-br/vagas#1730]
Descrição da empresa
Desenvolvemos aplicativos e softwares para empresas. Nossa foco é na entrega, você pode trabalhar de onde você quiser e o horário que você quiser, nosso próprio nome já diz WA (Work anywhere) Project.

Atividades e Responsabilidades
Desenvolvimento de projetos sob demanda para nossos clientes, utilizando tecnologias web e mobile. Implementação de novas features e manutenção.
Compartilhar conhecimento e estar disposto a ajudar o time.

Requisitos
Experiência com as tecnologias: NodeJs, React, React Native, Typescript, Docker, HTML, CSS, Rest, NPM/Yarn, banco de dados SQL e GIT.
Metodologias utilizadas: Scrum e KanBan.
Diferenciais: MongoDB, RxJs e Testes.
Capacidade analítica para resolução de problemas.
Comprometimento e ótima comunicação.

Candidatos, enviar currículo para vagas@waproject.com.br

**Comment by danielsidev** [comment]
Olá!
Essa vaga remota é CLT ou PJ?
Desde já, obrigado!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
