### ISSUE TITLE
[SÃO PAULO][ALOCADO] Skyone: Vaga Senior Python

### ISSUE THREAD

**Issue by Michelledonega** [backend-br/vagas#1732]
### Sobre a empresa: Sky One
Nossa empresa busca profissionais dinâmicos e comprometidos, pessoas conectadas e atualizadas que sejam capazes de planejar e executar inovação, pois tudo o que realizamos é por meio de gente. Gente de talento, que gosta de trabalhar em um ambiente de colaboração, descontraído e alta performance. Se você possui essas características, venha fazer parte do nosso time.
	
Oportunidade para trabalhar na Sky One, uma das 25 melhores Startups para se trabalhar eleita pela segunda vez consecutiva pelo Linkedin. 
 
### Principais atividades
•	Contribuir na escrita das estórias, dos critérios de aceite e dos  critérios de READY e DONE.
•	Qualificar as estórias e pontuar a quantidade de horas para desenvolvimento junto ao time.
•	Projetar e documentar planos de sprints e releases para a evolução das soluções.
•	Participar ativamente das reuniões diárias de andamento e de revisão de qualidade.
•	Planejar e executar deploys de releases.
•	Realizar treinamentos e workshops para o time.
•	Trabalhar com os conceitos de Git flow.

### Requisitos mandatórios:
•	Python, Django, Flask, Jinja,  JQuery
•	ElasticSearch, Kibana, Logstash
•	RabbitMQ
•	Celery
•	SQLAlchemy 
•	Alembic
•	PostgreSQL, Redis
•	Jira, Git
•	PyTest, Restful API
•	Linux

### Competências técnicas desejáveis (diferencial):
•	Docker, Kubernetes, ECS, EKS, Ansible, 
•	AWS

### Formação 
•	Superior em Desenvolvimento de redes, Tecnologia da Informação e correlatos
 
**Horário de trabalho:**
•	Segunda à sexta com horário flexível - Berrini – SP.
 
### Benefícios oferecidos: 
•	Vale refeição R$ 22,50 ao dia
•	VT
•	Convênio Saúde e Odonto Sulamérica
•	Auxílio Creche para filhos até 10 anos
•	Seguro de Vida
•	Auxílio idiomas até 50% com teto de R$ 250,00
•	Gympass  
•	Convênio com diversas universidades
 
### Fale direto com o recrutador da vaga via WhatsApp: 
 http://bit.ly/vaga-python-senior

## Label

- Python
- Sênior
- Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
