### ISSUE TITLE
 [SÃO PAULO][ALOCADO] Skyone: Vaga Junior Python

### ISSUE THREAD

**Issue by Stephani1996** [backend-br/vagas#1734]
### Sobre a empresa: Sky One
Nossa empresa busca profissionais dinâmicos e comprometidos, pessoas conectadas e atualizadas que sejam capazes de planejar e executar inovação, pois tudo o que realizamos é por meio de gente. Gente de talento, que gosta de trabalhar em um ambiente de colaboração, descontraído e alta performance. Se você possui essas características, venha fazer parte do nosso time.
            	
Oportunidade para trabalhar na Sky One, uma das 25 melhores Startups para se trabalhar eleita pela segunda vez consecutiva pelo Linkedin.
 
### Requisitos mandatórios:

Python, Django, Flask, ElasticSearch, Kibana, Logstash, RabbitMQ, Celery , SQLAlchemy, Alembic 
PostgreSQL, bancos NoSQ, Jinja, Jira, Git, JQuery, Scrum, Kamban, Nginx, Docker, Ansible, Kubernetes, AWS/Azure, ECS, EKS, GCP, PyTest, Restful API, Linux

### Formação
•         	Superior em Desenvolvimento de redes, Tecnologia da Informação e correlatos
 
**Horário de trabalho:**
•         	Segunda à sexta com horário comercial - Berrini – SP.
 
### Benefícios oferecidos:
•         	Vale refeição R$ 22,50 ao dia
•         	VT
•         	Convênio Saúde e Odonto Sulamérica
•         	Auxílio Creche para filhos até 10 anos
•         	Seguro de Vida
•         	Auxílio idiomas até 50% com teto de R$ 250,00
•         	Gympass 
•         	Convênio com diversas universidades
 
### Fale direto com o recrutador da vaga via WhatsApp:
https://api.whatsapp.com/send?phone=5511988445504&text=Ol%C3%A1%2C%20tenho%20interesse%20na%20vaga%20de%20Python%20Jr

Sentiu que a vaga não é pra você?! 🙁
Indique amigos, conhecidos ou colegas de trabalho para essa oportunidade através do canal acima. 
#Compartilhe 

## Label
 
- Python
- Alocado
- Junior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
