### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Ionic Júnior na CUBO 333

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1736]
### Sobre a empresa: Cubo 333

Cubo 333 é uma incubadora de projetos com foco em tecnologia da internet e desenvolvimento de sites, planos de marketing, aplicativos e redes sociais. O nosso símbolo é o cubo, que representa a estabilidade, a sabedoria e a transparência, que, não por coincidência, são os nossos objetivos diários e constantes.

### Descrição

Você tem vontade de fazer parte de algo grande? Já pensou em desenvolver junto com o time de um dos maiores projetos de passagens aéreas do país?

Então vem pra Cubo 333, idealizadora do projeto Passagens Imperdíveis! Estamos em busca de um Desenvolvedor Ionic Júnior para fazer parte do nosso time de desenvolvimento :)

### Desafios

Implementação de Aplicativo para Android e iOS utilizando Ionic;
Implementação de Rest API;
Implementação de Testes;
Implementação de Notificações/PUSH com AWS;
Publicação e Manutenção dos aplicativos nas Lojas AppStore, Play Store e Windows.

### Requisitos necessários

Vivência com Ionic;
Javascript, HTML, CSS;
JQuery;
Angular JS;
REST API.

### Seria legal se

Conhecimento em PHP;
Conhecimento em Java.

### Benefícios

Vale Alimentação (R$30,00 por dia);
Vale Transporte;
Plano Médico;
Plano Odontológico.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/cubo333_ionic

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
