### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby on Rails na TZ3 Tecnologia

### ISSUE THREAD

**Issue by dgilbertoni** [backend-br/vagas#1737]
### **2 VAGAS URGENTES** 

Desenvolvedor Ruby on Rails / PostgreSQL, para projeto de 3 a 6 meses com possibilidade de renovação.

Enviar CV c/ pretensão de valor/hora (PJ) para: **rh@tz3.com.br** 

Local de trabalho: São Paulo - Av. Paulista

Contratação imediata

--------------------------------

### **Requisitos**

- Formação em ensino superior ou técnico;
- Experiência prévia nas linguagens informadas;
- Inglês Intermediário;
- Experiência com ferramentas de versionamento de código (GIT,...);
- Conhecimento em metodologias ágeis (Scrum/Kanban);

---------------------------------

### **Descrição da empresa**

A **[TZ3 Tecnologia](https://tz3.com.br)** atua há uma década no mercado de desenvolvimento de projetos 100% customizados de software, período em que entregou centenas de sistemas, apps, websites e robôs de automação de processos aos seus clientes.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
