### ISSUE TITLE
Pessoa Desenvolvedora Backend 

### ISSUE THREAD

**Issue by uemuraharumi** [backend-br/vagas#1738]
**Quem somos?**

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA. Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time de Produto e Desenvolvimento, e para isso buscamos pessoas incríveis!

Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

 Porque o(a) Desenvolvedor(a) - Java Sênior é importante para nós? Como membro da equipe de Produto e Desenvolvimento, você será responsável pela elaboração de novas ferramentas, manutenção das ferramentas existentes e pela tomada de decisões relacionadas à arquitetura das aplicações e dos microsserviços que compõem o ecossistema da Sympla.

 **Seus desafios serão:**

- Contribuir com as decisões de arquitetura da nossa aplicação, buscando uma arquitetura flexível e moderna que acompanhe o crescimento constante;
- Ajudar a manter um “espírito” ágil;
- Ter orgulho de colocar em produção um código que é usado por milhões de pessoas Brasil afora. Para isso, qualidade deverá ser sua obsessão;
- Monitorar o desempenho dos serviços que compõem o ecossistema da Sympla, para identificar gargalos de desempenho e problemas de performance em geral, assegurando a continuidade das operações e a melhor experiência para o usuário;
- Ser responsável por especificações técnicas e documentação;
- Monitorar a evolução dos produtos no mercado;
- Consultas de banco de dados e correções de bugs;
- Implementação de novos recursos na plataforma.

 **Oferecemos:**

- Regime de contratação CLT;
- Salário compatível com o mercado, VT e VR;
- Plano de Saúde e Odontológico;
- No dress code (pode trabalhar de bermuda, camiseta, etc);
- Café, bebidas variadas e snacks;
- Horário flexível :)
- 40h semanais, de segunda a sexta.

 

  **O que buscamos?**

 Procuramos pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras. Além disso:

- Excelente conhecimento de pelo menos uma linguagem de programação de alto nível: em especial Java;
- Conhecimento de Sistemas Operacionais: Linux;
- Conhecimento em banco de dados: PostgreSQL ou similar;
- Capacidade de priorizar o seu próprio trabalho a partir das linhas gerais definidas pela equipe e de feedbacks recebidos dos usuários finais;
- Ser flexível, independente e responsável;
- Ser curioso, com muita vontade de experimentar e aprender coisas novas;
- Ter senso de organização, atenção a detalhes e foco;
- Must rock!

**Alguns diferenciais para a função:**

- Inglês e/ou espanhol intermediário;
- Vivência em aplicações que recebam quantidade massiva de acessos simultâneos;
- Ter conhecimento de Microserviços;
- Ter conhecimento no framework Spring.
-  Valorizamos trabalhar em um ambiente de pluralidade e de inclusão, por isso todas nossas vagas também são para profissionais com deficiência.

Se o seu perfil corresponde ao que acreditamos, venha fazer parte do nosso time!!!

**Link para se candidatar:** https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=4472612002
**Responsável:** https://www.linkedin.com/in/raquel-uemura-8b9834122/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
