### ISSUE TITLE
[São José dos Campos] Desenvolvedor .NET [GSW Software]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1739]
**Descrição da Oportunidade**
Atuar com desenvolvimento .NET, com grandes clientes e projetos.

**Experiência**

.Net Framework ;MVC 5
Banco de dados Oracle e SQL
Entity Framework ;Bootstrap
Dapper; Ninject; Razor
WebAPI; Web Services em REST e SOAP

**Benefícios**
Á combinar

**Cidade**
São José dos Campos

**Tipo de contratação**
PJ

Interessados, por favor, enviar pretensão e disponibilidade de início para: **mariana.bompean@gsw.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
