### ISSUE TITLE
[São Paulo] Full-Stack Developer na PROA Tecnologia Criativa

### ISSUE THREAD

**Issue by ulissesrsilva** [backend-br/vagas#174]
Olá! Nós somos a PROA Tecnologia Criativa e estamos buscando uma nova pessoa para embarcar em nosso navio!

### Procuramos alguém que...
- Não tem medo de desafios!!!
- Tem um perfil _maker_ e investigativo;
- Comprometido com resultados e prazos;
- Curte um ambiente de startup, descontraído (mas com muito trabalho para ser feito);
- Queira crescer junto com a empresa;
- Gosta de aprender e se arriscar;

### Manja de...
- C# e .NET ;
- Javascript e Node.JS;
- MongoDB e SQL Server;
- CSS3, HTML5;
- Git;
- Construção e consumo de web services e APIs;
- Utilização e configuração de serviços AWS;

### No nosso navio tem:
- Vale-transporte;
- Vale-refeição ou alimentação;
- Assistência médica e odontológica;
- Possibilidade de home-office 1x por semana;
- Incentivo a cursos e participação em eventos;
- Flexibilidade de horário;
- Ambiente descontraído
- #_PROAParty_, nossa festa mensal \o/
- _No dress code_ (pode trabalhar de bermuda, camiseta, vestido...)

### Sobre a embarcação:
A PROA Tecnologia nasceu para criar soluções inovadoras em desenvolvimento de aplicativos móveis, sistemas, integrações, robôs de atendimento, consultoria e pesquisa por meio de uma imersão na realidade de cada cliente. Cada projeto é encarado como um novo desafio e estruturado sob medida para atender e superar as expectativas de cada empresa. Acesse nosso site: www.proatecnologia.com.br

Para embarcar nos envie seu currículo (feat. pretensão salarial) para rh@proatecnologia.com.br

**Comment by reginaldojunior** [comment]
Issue closed by Bot because very time without interantion
