### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Pleno na PROMO DE BOLSO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1740]
### Sobre a empresa: Promo de Bolso

A Promo de Bolso é uma startup de tecnologia. Com diversas soluções e produtos, a empresa se destaca neste segmento e propicia um ambiente desafiador e cheio de oportunidades, impactando a vida de milhares de pessoas. Existimos para ajudar as pessoas a participarem de promoções com rapidez e segurança.

### Descrição:

Procuramos programadores que amam e sejam realmente bons no que fazem, encontrando soluções para os mais variados problemas técnicos.

### Conhecimentos técnicos:

Experiência com integração de aplicações WEB e APIs;
Experiência com banco de dados relacionais;
Experiência em ambiente WEB: HTML, CSS, etc;
Experiência com Python e JavaScript.

### No seu dia a dia você lidará com:

Impacto real na vida de centenas e milhares de pessoas;
Sistemas complexos e novas tecnologias e ambiente de alta produtividade;
Participar das decisões de tecnologia;
Oportunidades reais de crescimento na carreira.

### Quais skills esperamos de você:

Planejamento em equipe e auto-gestão;
Vontade de aprender novas tecnologias e linguagens;
Automatização de processos;
Pró atividade e interesse em entender e aprender as regras de negócio;
Inglês: leitura intermediária.

### O que os as pessoas + gostam na Promo:

O clima, o aprendizado de diversas tecnologias e o desafio diário;
Transparência em processos e decisões da empresa;
É pertinho do metrô, no bairro Pinheiros, em um espaço muito legal!

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/promodebolso_fullstack1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
