### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Backend na Leroy Merlin

### ISSUE THREAD

**Issue by ravanscafi** [backend-br/vagas#1741]
<div align="center">
    <a href="https://www.leroymerlin.com.br" title="Leroy Merlin">
        <img width=100 src="https://cdn.leroymerlin.com.br/assets/images/logo-leroy-merlin.svg" alt="Leroy Merlin"/>
    </a>
    <h1 align="center">Backend Developer</h1>
</div>

## Descrição da vaga
Estamos procurando novos integrantes para nossas squads aqui na Leroy Merlin Brasil!

Nosso time, o Boitatá, é responsável pelo Site/E-commerce/APP Android e iOS/Plataforma de Vendas das Lojas, além de outros projetos que estão surgindo e que você poderá ajudar a construir :smile:

Priorizamos qualidade e valor de negócio. Adotamos boas práticas em nossos times como TDD, Pair Programming, Code Review, Tech Talks, Priorização de Débitos Técnicos, entre outros, nos embasando em Metodologias Ágeis para o sucesso de nossos projetos e equipes. Estamos constantamente nos atualizando e buscando novas tecnologias que façam sentido para os nossos desafios. Estamos presentes em diversos eventos de tecnologia da área, algumas vezes levando nossos conhecimentos através de palestras e workshops.

Valorizamos e contribuímos para o _open source_, tendo vários projetos publicados na nossa organização: @leroy-merlin-br

Nossas stacks são basicamente `PHP 7+` com `Laravel 5+`, `MongoDB`, `Elasticsearch`, `Redis`, `SQS`, `Kafka`.
Utilizamos `Docker` e provisionamos nossa infraestrutura na `AWS` e `GCP`, utilizando boas práticas de `IaC`, seguindo a cultura DevOps.

## Local

**Presencial**, Interlagos - Zona Sul, São Paulo/SP

## Benefícios

- Prêmio de Participação nos Lucros e Resultados
- Plano de Saúde
- Plano Odontológico
- Vale Refeição/Refeição no Local
- Vale Transporte
- Cesta Básica após o período de experiência
- Cesta de Natal
- Seguro de Vida em Grupo
- Desconto na Compra de Produtos da Loja
- Empréstimo Consignado em Folha de Pagamento
- Kit Material Escolar para Filhos de 3 a 17 anos de idade
- Cartão Farmácia
- Gympass

## Requisitos

Estamos buscando devs que tenham os seguintes conhecimentos:
- `PHP 7+`
- `OOP`
- Pelo menos um dos frameworks MVC: `Laravel`, `Symfony`, `Rails`, `Zend`
- `Testes automatizados`*

\* Caso você não possua conhecimentos em testes automatizados, haverá oportunidade de demonstrar sua capacidade de aprendizado em nosso teste prático.

## Contratação

CLT - Presencial

## Nossa empresa

A [Leroy Merlin](https://www.leroymerlin.com.br/) é uma multinacional francesa presente em mais de 10 países, sendo uma das maiores redes de varejo do Brasil, líder no mercado da Construção, Decoração, Jardinagem e fazemos parte do Grupo Adeo, maior grupo francês no setor internacional de Bricolagem.

No Brasil temos 41 lojas e 10.000 colaboradores que são especialistas em tornar acessível os sonhos dos nossos clientes, oferecendo soluções para os diferentes momentos de compra do cliente e a maior variedade de produtos e serviços.

## Como se candidatar

Ficou interessado?
Candidate-se para a vaga [clicando aqui](https://jobs.kenoby.com/leroymerlin/job/back-end-developer/5d3afe53c9595d6bdfe77040).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
