### ISSUE TITLE
[Campinas]- Venturus Centro de Inovação - Desenvolvedor(a) .NET Pleno 

### ISSUE THREAD

**Issue by marinasantangelosilva** [backend-br/vagas#1743]
Venturus Centro de Inovação 

Há mais de 20 anos no mercado, somos líderes em tecnologia atuando em diversas áreas como telecomunicações, manufatura, automotivo, meios de pagamento, saúde, entre outros. Com relações autênticas, cocriamos a melhor solução para o seu problema. 
Valorização Humana. Apaixonados. Curiosos. Esses são alguns dos valores que todo Ventureiro deve ter. Somos diversos em tecnologia, ambientes e, principalmente, pessoas. Aqui nosso foco é na tecnologia, mas sempre lembrando que são as pessoas que estão por trás de toda a inovação. 

Quem estamos buscando?
Desenvolvedor com experiência em .NET Core e conhecimento UWP (Universal Windows Plataform)

Responsabilidades:
Você trabalhará em um projeto para uma empresa multinacional, criando uma aplicação que será embutida
no produto final do cliente, com possibilidade de se tornar um produto internacional.

Competências e experiência necessárias:

- Experiência em .NET Framework e/ou .NET Core
- Experiência com Universal Apps (UWP)
- Conhecimento de ferramentas de controle de versão (Git)
- Inglês intermediário

Diferenciais:
- Experiência em WPF (Windows Presentation Foundation)
- Experiência com metodologia de desenvolvimento ágil (Scrum)

Benefícios:
VALE REFEIÇÃO
VALE ALIMENTAÇÃO
ASSISTÊNCIA MÉDICA
ASSISTÊNCIA ODONTOLÓGICA
ÔNIBUS FRETADO
VALE TRANSPORTE – 6% de desconto salário base
ESTACIONAMENTO GRATUITO 
SEGURO DE VIDA
COOPERATIVA DE CRÉDITO
PREVIDÊNCIA PRIVADA
OUTROS: 
- Horário Flexível (entrada das 7h às 9h)
- Programa de Bolsa de Estudos: 
- Incentivo de Horas: São liberados 4 horas semanais para mestrados e doutorados (depois dos 3 meses de empresa) 
- Programa de Certificação Técnica
- Sesc 
- Home Office

Contato:
Marina.silva@venturus.org.br

https://jobs.kenoby.com/venturus/job/desenvolvedora-net-pleno/5d97a582632737013ba8a124

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
