### ISSUE TITLE
[BARUERI-SP] Senior Java Developer na JUST DIGITAL

### ISSUE THREAD

**Issue by alicesrossi** [backend-br/vagas#1744]
**Quem é a Just? Da uma olhada aqui:**

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível.
Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

**Requisitos**

Java, JPA, Hibernate, Oracle Weblogic,
JBOSS, filas JMS
Git e WebService
REST e SOAP
Integração Contínua (i.e Jenkins)
Orientação a objetos 
Design Patterns
Web Services

**Local de trabalho:**

Barueri - São Paulo

**Benefícios:**
- Vale Refeição
- Vale Transporte
- Horário Flexível
- 2 home office/semana
- Assistência Médica e Odontológica
- Seguro de Vida em Grupo
- Parceria com a Gympass e outros convênios em estabelecimentos e instituições de ensino

**Será que você é nosso próximo(a) Juster?
Se candidata aqui e vem bater um papo com a gente!**
https://justdigitalbr.recruitee.com/o/dev-java-senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
