### ISSUE TITLE
[São José dos Campos - SP] DESENVOLVEDOR JAVA [Gsw Software]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1746]
### **Descrição da Oportunidade**
Atuar diretamente em projetos Java do cliente, junto com a equipe GSW.

### **Experiência**

•Java e suas API's (Lambda, Collections, Generics, Streams, etc..)
•Oracle, Postgres, SQL Server
•Vivencia na utilização dos principais frameworks do mercado (Plataforma Spring, Hibernate, MVC, RabbitMQ, etc.. )
•Vivência no sistema operacional linux.
•Vivência com servidores de aplicação (Tomcat, JBoss, Jetty, etc.)

### **_Conhecimentos:_**
POO e Princípios SOLID
Bons conhecimentos em segurança de aplicações web, tanto na prevenção de ataques quanto na aplicação de politicas de segurança.

### **Cidade**
SÃO JOSÉ DOS CAMPOS

### **Contratação**
PJ

### **Benefícios**
Á combinar

### **_Nosso Time GSW_**

Somos referência, no desenvolvimento de soluções em Tecnologia da Informação, oferecendo aos nossos clientes, sistemas de TI que se traduzem em melhorias significativas para o dia a dia do negócio, principalmente no que se refere à redução de custos e ao aumento da produtividade. Clientes como: SPC Brasil, Embraer, Ericsson, Panasonic, 3M, etc..

**Venham fazer parte de nosso time!**

### **Como se candidatar**
Por favor, envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vagas Java

### **Labels**
:+1: Flexível
:office:  Presencial
:+1: Pleno
:+1:  Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
