### ISSUE TITLE
[Palhoça - SC] Desenvolvedor BackEnd na TOTAL VOICE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1747]
### Sobre a empresa: Total Voice

A API de comunicação TotalVoice permite aos desenvolvedores incluir comunicação por voz e texto diretamente em seu aplicativo. Funciona no modelo “pay as you go”, sem mensalidades ou custos surpresa. 

Diferente de uma infraestrutura tradicional, você não precisa de volume para ter um preço baixo. Ou seja, usando 1 minuto ou 1 SMS, você já está com uma ótima tarifa.

### Qual será o seu papel?

Desenvolver software de acordo com as definições da equipe;
Documentar as funcionalidades e evolução dos programas desenvolvidos;
Automatizar testes de software;
Automatizar serviços escaláveis na nuvem;
Contribuir, construir e manter códigos no Github;
Trabalhar com tecnologias OpenSource;
Criar soluções escaláveis na nuvem usando principalmente NodeJS ou PHP.
Atuar com excelência na construção de indicadores e informações para tomada de decisão;
Apoiar no suporte e atendimento dos chamados de cunho técnico a Plataforma de Sistemas Corporativo;
Apoiar a análise técnica de requisitos;

### Esperamos que você tenha:

Conhecimento avançado em HTTP e protocolos baseados em texto;
Conhecimentos em PHP ou NodeJS;
Conhecimentos em bancos de dados SQL e GIT e experiência em desenvolvimento de software web com qualidade;
Conhecimentos em Linux;

### Você vai amar trabalhar aqui se:

Estiver em busca de crescimento e evolução;
For importante para você estar em um lugar diverso, no dress code e com horário flexível;
Gostar de trabalhar em equipe;
Gostar de aprender novas tecnologias;
Gostar de testar e validar as coisas e que não tenha medo de errar;
Trabalhar orientado(a) a metas e resultados;

### Benefícios:

Pacote de benefícios: valor de R$770,que poderá ser distribuído, conforme preferência, em cartões de benefício (Alimentação/Refeição/Combustível/VT); 
A partir de novembro: plano de saúde Bradesco Saúde Privativo.

### Informações Complementares:

Contratação tipo CLT;
Estamos localizados na área central de Palhoça - SC
Palhoça é uma cidade tranquila, pertinho de praias paradisíacas como a praia de Guarda do Embaú. Além disso, estamos a 30 minutos de Florianópolis)

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/totalvoice_back

**Comment by tdias25** [comment]
aceita remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
