### ISSUE TITLE
[São Paulo] Desenvolvedor Java [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#1748]
Se você tem vivência com:
Java8, 
Spring boot;
SQL Server. 

Aceita contratação CLT. 
Considera trabalhar na zona sul de SP (bem ao lado da estação Morumbi da CPTM). 

Gosta de projetos desafiadores, mas, também quer trabalhar em um ambiente com Dress Code livre, sala de descompressão (com mesa de sinuca), campeonatos de pocker e futebol, DayOff no mês do seu aniversário e mais o pacote "padrão" de benefícios: VR, VT, Assistência médica e odonto e o PLR. 

Mande seu cv e pretensão salarial para: curriculos@confitec.com.br. =)

{Ah! a Confitec é uma empresa de Tecnologia especialista no ramo de Seguros}

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
