### ISSUE TITLE
[São Paulo - Pinheiros] Full Stack Rails na Worldpackers

### ISSUE THREAD

**Issue by joaomm** [backend-br/vagas#175]
**Pinheiros, São Paulo**

A Worldpackers torna possível experiências incríveis de viagem que cabem no bolso. Somos uma comunidade de mais de 1.000.000 de viajantes e anfitriões trocando habilidades por acomodação ao redor do mundo. Imagine mochilar pela América do Sul ajudando hostels com recepção ou social media, voluntariar pelo Sudeste Asiático em ONGs & projetos sociais ou aprender sobre sustentabilidade em ecovilas & projetos ecológicos.

Temos um time de tecnologia & design enxuto e bem experiente para tornar a parte técnica na “parte fácil” e nos focar em melhorar, testar & crescer nosso produto & negócio.

**Essa vaga é perfeita para você, se você tecnicamente:**

- Não pára de aprender
- Ama fazer muitos deploys por dia
- Pira quando vê uma enorme bateria de testes automatizados verdes
- Respira código limpo
- Quer fazer/saber de tudo um pouco (front, back, APIs,  infra, etc)
- Já trabalhou com desenvolvimento Ruby / Rails

**Também é perfeita para você, você pessoalmente:**

- É apaixonadx pela ideia de usar tecnologia para impactar a vida de milhões de pessoas ao redor do mundo
- Se sente motivadx em um ambiente de startup global em constante mudança, testes e novas oportunidades
- Trabalha com autonomia & responsabilidade, participando ativamente das decisões do produto
- Toma decisões baseadas em dados e feedback de usuários
- Tem um mindset de melhoria contínua, sempre desenvolvendo seus skills e entendimento do mercado & negócio
- Quer trabalhar com propósito com gente realmente boa!

**Como se aplicar?**

1. Escreva um email respondendo “Por que você que se juntar ao nosso time? Como pode nos ajudar?”.
2. Envie para tech@worldpackers.com com o título: “Software Engineer, Full Stack Rails”

**Labels**
Ruby on Rails, Ruby, CLT, Pleno, Junior

**Comment by rannyeribatista** [comment]
Olá, vocês só contratam CLT? A vaga pode ser remota ou apenas presencial?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
