### ISSUE TITLE
CURITIBA Back-End Developer na SEND4 TECNOLOGIA

### ISSUE THREAD

**Issue by laissend4** [backend-br/vagas#1750]
A Send4 é uma startup de tecnologia para o varejo, que utiliza a logística para e-commerces como meio de integrar o mundo online e offline. Nosso objetivo é facilitar as compras e devoluções dos compradores online brasileiros, conectando-os à lojas e estabelecimentos físicos próximos de suas casas e trabalhos que atuam como pontos de retirada para sua conveniência.

Somos cheios de energia, sem mimimi, casca grossa, focados na solução. Venha fazer parte da nossa missão, vamos juntos tornar o mundo cada vez mais conectado, cada dia mais Omni!

**Suas principais responsabilidades serão:**
Desenvolvimento Back End/Front End para aplicações responsivas e PWAs;
Pesquisar e se atualizar sobre como e quais tecnologias podem ajudar na transformação do mercado de logística;
Ter opiniões sobre o business e colaborar de forma construtiva para o sucesso de uma empresa emergente;
Ter proatividade para criar e propor novas soluções, não ficar só sentado esperando acontecer!

**O básico para esta vaga:**
Conhecimentos sólidos em PHP, uso de frameworks, boas práticas e design patterns;
Experiência com consumo e criação de WebServices/APIs, APIs REST;
Conhecimentos em modelagem de banco de dados relacional;
HTML5, Bootstrap;
Git, SQL;
Experiência e conhecimento avançado em ES6;
Conhecimentos sólidos em ReactJS;
Ter experiência com testes TDD, BDD.

**O que a gente adoraria ver (vale pontos extras!!!):**
Conhece e já trabalhou com python;
Já teve contato com testes automatizados;
Conhecimento em Postman, Test Complete, JTest, Docker;
Gosta de fazer testes e sabe da importância deles para entregas mais rápidas;
CSS3 / Sass / Less;
Experiência em APIs e plataformas escaláveis, micro serviços;
Experiência em plataformas de e-commerce (Magento, WooCommerce);
Conhecimentos em SCRUM;
Ter o foco na solução e não no problema;
Haver trabalhado em startup/empresa .com;
Ter sede por produtividade e aprendizado;
Experiência com alguma cloud como AWS, GCP ou Azure;
Experiências anteriores diferenciadas como voluntariado, ongs, aiesec, empresas juniores, projetos próprios/empreendimentos.

**Nossa stack, aqui você trabalhará com:**
Usamos google cloud platform com kubernetes, app engine, cloud functions etc;
Nosso backend usa principalmente PHP;
Os fronts usam JavaScript, ReactJS, Redux, Sass, Jest, React Testing Library;
Usamos MySQL, Redis, GCS;
Nosso pipeline de CI/CD usa Jenkins;
Usamos Slack para comunicação interna;
Organizamos nossas tarefas com o Youtrack.

Contratação CLT ou PJ;
Oportunidade de impactar o dia a dia de milhares de pessoas, aplicando tecnologia;
Terá a oportunidade de contribuir efetivamente para o crescimento de uma startup em fase de expansão e crescer junto!

Enviar currículo para rh@send4.com.br com o titulo - GitHub CURITIBA Back-End Developer na SEND4 TECNOLOGIA.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
