### ISSUE TITLE
[Curitiba/PR] Desenvolvedor Full-stack Pleno & Senior [MadeiraMadeira]

### ISSUE THREAD

**Issue by paregonta** [backend-br/vagas#1751]
Estamos buscando desenvolvedores para fazer parte do time do www.madeiramadeira.com.br.

**BENEFÍCIOS**
- Contratação CLT
- VA e VR
- Plano de Saúde e Dentário
- Gympass

**DESAFIOS**
- Criação e auxílio nas definições de arquitetura de sistema;
- Colaboração com os desenvolvimentos da área;
- Acompanhamento de projetos com o time de TI;     
- Realização de benchmarks voltados para backend.
- Interação com as pessoas responsáveis de outros projetos;
- Preocupado com escalabilidade e estabilidade;
- Suporte ao QA;
- Depuração e resolução de problemas em produção extremamente rápida e eficaz;

**SKILLS**
- PHP frameworkless
- MVC
- AWS
- SQL server
- NoSql (Firebase, Redis, MemCached, ElasticSearch)
- RESTful APIs
- Docker
- FrontEnd (Html, CSS, Jquery e JavaScript)

Daremos prioridade para quem mora em Curitiba e região metropolitana.

Interessado? Envie seu currículo e/ou link do seu Linkedin para allan.campos@madeiramadeira.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
