### ISSUE TITLE
[SÃO PAULO] Software Engineer na Liv Up

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#1752]
A **Liv Up** está à procura de **Software Engineers** para criar soluções escaláveis e sustentáveis na foodtech brasileira que vem crescendo exponencialmente!

**Seu dia-a-dia como Software Engineers na Liv Up:**
Criar e desenvolver soluções escaláveis, sustentáveis e orientadas ao negócio da Liv Up.
Construir serviços, aplicativos e APIs fáceis de entender com soluções baseadas em Node.js, React.js e React Native.
Tomar boas decisões de Engenharia de Software com autonomia, considerando variáveis técnicas e não-técnicas.
Questionar por que as coisas são feitas do jeito que são e fazer parte da construção de um time de alta perfomance e muita colaboração multidisciplinar.

**Precisamos muito de alguém que traga:**
Conhecimentos sólidos em desenvolvimento de software em react, node.js ou react native.
Vontade de encontrar soluções para os problemas que encontramos do campo até a mesa do cliente.
Experiência com tecnologias modernas e metodologias ágeis.

**Benefícios:**
Remuneração: R$10.000 reais
Vale-refeição e Vale alimentação 
Vale transporte
Assistência médica e assistência odontológica
GymPass
Happy Hour mensal
Incentivo a cursos e eventos
40% de desconto nos produtos Liv Up

**Local de Trabalho:**
Rua Butantã, 468, Pinheiros, São Paulo – SP

**Processo Seletivo:**
Inscrição e MatchMaker da Intera Talent Hacking (no link abaixo)
Bate-papo com a Intera
Entrevista cultural e técnica com a equipe Liv Up :)
Link: http://byintera.in/1b

**Surgindo qualquer dúvida, estou disponível para conversar mais sobre a oportunidade! =)**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
