### ISSUE TITLE
[Belo Horizonte] Desenvolvedor BackEnd na CM TECNOLOGIA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1754]
### Sobre a empresa: CM TECNOLOGIA

A CM TECNOLOGIA é uma empresa de TI especializada em softwares para o setor de atendimento, que auxiliam e somam na automatização, eficiência e resultados de empresas na área da saúde. Nossa proposta é diminuir o custo que nossos clientes tem com Call Center. Trazendo eficiência para nossos clientes e comodidade para seus pacientes.

### Descrição: O QUE BUSCAMOS

A CM está em busca de um(a) Desenvolvedor (A) Sênior que será responsável pelo desenvolvimento e manutenção dos produtos da CM, treinando os mais jovens e evoluindo junto ao time.

### QUAIS SERÃO SEUS DESAFIOS:

* Estimar as atividades de desenvolvimento juntamente com a sua equipe;
* Garantir a o desenvolvimento de sistemas dentro da estimativa com qualidade e padrões previamente definidos;

### BUSCAMOS ALGUÉM QUE TENHA:

. Experiência na função;
. Experiência com alguma das linguagens de programação: C# OU JAVA
. Conhecimento em Git;
. Conhecimento de Agile (Scrum);
. Conhecimento em banco de dados SQL e NoSQL;
. Conhecimento em API REST;
. Graduação completa nos cursos de TI ou Engenharia.

### MAS IREMOS AMAR TAMBÉM SE VOCÊ TIVER:

. Conhecimento em arquiteturas em NUVEM;
. Conhecimento em arquitetura de software;
. Programação Orientada a Objeto.

### OFERECEMOS:

. No dress code (pode trabalhar de chinelo, bermuda, pijama, etc);
. Horário flexível (40hs semanais);
. Sinuca, Ping Pong e Video Game (olha que massa!);
. Happy Hour com cerveja toda sexta (não pode faltar aquela festinha, né?)
. Plano de Saúde Bradesco e Odontológico;
. Vale Alimentação/Refeição;
. Vale Transporte;
. Convênio com Sesc
. Convênio com Farmácia

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/cmtecnologia_backend

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
