### ISSUE TITLE
[São José dos Campos] Desenvolvedor FullStack Node/React Sênior [GSW]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1755]
### **Desenvolvedor FullStack Node/React Sênior**

Experiência mínima com Desenvolvimento de 4 anos.

### **Experiência:**
React 16.8; JavaScript ES6
Redux
KOA(para Nodejs)
MongoDB;Mongoose
PostgreSQL

### **Descrição**
O desenvolvedor, será responsável pelo desenvolvimento e análise de novas funcionalidades do sistema, contato direto com cliente.
Deverá sentir-se apto para atuar de forma multifuncional ajudando a compreender as atividades técnicas.

### Projeto
Tempo indeterminado

### Cidade
São José dos Campos

### Contratação
PJ

### Como se candidatar
Interessados, por favor encaminhar cv, pretensão e disponibilidade para
mariana.bompean@gsw.com.br

Venham fazer parte de nosso time!!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
