### ISSUE TITLE
[SÃO PAULO] Dev. Java [AUTOPASS]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1756]
Contratação PJ
Local: Berrini - SP

Requisitos Técnicos: 
Java (1.8)
Spring boot
Oracle
Github
Jenkins
Metodologias ágeis 
JSP
Devops

Encaminhar CV para: aline.navarro@keepsimple.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
