### ISSUE TITLE
[SÃO PAULO] Dev. Java [CCEE]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1757]
Contratação: CLT
Local: Paulista - SP

Requisitos Imprescindíveis:
Experiência em JavaEE
Conhecimentos de banco de dados Oracle 
Struts ou Spring e Hibernate
Apache e Tomcat 
Experiência com pelo menos um dos servidores de aplicações
JBoss ou Websphere ou Weblogic 

Requisitos Desejáveis:
Conhecimentos básicos de infraestrutura
UML
XML 
ER/Studio 
Ajax, SOA 
Enterprise Architect

Encaminhar CV para: aline.navarro@keepsimple.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
