### ISSUE TITLE
[Porto Alegre, RS] PHP Backend Developer Júnior

### ISSUE THREAD

**Issue by gbtagliari** [backend-br/vagas#1759]
## Descrição da vaga
Procuramos pessoa desenvolvedora para estágio em desenvolvimento de WebServices REST, integração com banco de dados PostgreSQL/MySQL em usando o Framework Laravel no ambiente da Amazon (AWS).

## Local
Porto Alegre, bairro Petrópolis.

## Benefícios
VR de R$ 18,00/dia

### Diferenciais
- espaço de jogos
- horários flexíveis
- café SEMPRE disponível ☕️

### Obrigatórios:
- vontade de aprender!

### Desejáveis:

- arquitetura API RESTful
- modelagem de BD

### Diferenciais:

- experiência em PHP
- experiência na criação de API
- inglês

## Contratação

Estágio

## Nossa empresa

A AIORIA trabalha com o desenvolvimento de projetos utilizando a metodologia ágil aliada ao scrum em nossos sprints.

Gosta de desafios? Somos especialistas em tirar idéias do papel e entregamos o MVPs (aplicativo iOS, aplicativo Android, backoffice e WS) em duas semanas.

Ou seja, trabalhos numa semana com um aplicativo para marcação de consulta médica e, na outra, estamos trabalhando com uma fintech! 💪

## Como se candidatar

Por favor envie um email para contato@aioria.com.br com seu CV anexado - enviar no assunto: Vaga Estágio PHP

## Labels

- alocação/Presencial
- alocação/Flexível (Remoto parcial)
- experiência/Estágio
- experiência/Júnior
- regime/Estágio

**Comment by danielmadureira** [comment]
Vocês têm alguma vaga full-time?

**Comment by gbtagliari** [comment]
> Vocês tem alguma vaga full-time?

Fala, Daniel, tudo bem? 

Manda teu cv que o pessoal avalia a possibilidade!!

Boa sorte!

**Comment by burn-c** [comment]
Disponível remoto ?

**Comment by gbtagliari** [comment]
@burn-c cara, manda o teu CV que o pessoal aqui avalia!

**Comment by burn-c** [comment]
@gbtagliari valeus, enviado!

**Comment by lgfranco22** [comment]
Disponível remoto ?

**Comment by gbtagliari** [comment]
fechando a vaga, pessoal!
