### ISSUE TITLE
[Belo Horizonte] Arquiteto de Software na GRUPO ANIMA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1760]
### Sobre a empresa: Grupo Anima

A Ânima é formada por pessoas apaixonadas pelo que fazem. E que não têm medo de desafios. Superamos dificuldades. Fazemos as coisas sempre da melhor maneira. Somos fascinados pela magia da educação: acreditamos que só ela pode transformar vidas. E isso reforça a sensação de que estamos participando ativamente do desenvolvimento do nosso país.

### Descrição:

Estamos em busca de pessoas com disposição de transformar o país pela educação e que sejam apaixonadas por tecnologia. Para esta vaga a pessoa irá atuar no desenho, desenvolvimento, manutenção e evolução de aplicações distribuídas desenvolvidas em PHP, NodeJS, .NET (Full Framework e Core), dentre outras. Essas aplicações são executadas em uma nuvem privada e também em nuvem púbica (AWS). Temos desde aplicações legadas (monolitos) até microserviços sendo executadas em cluster Kubernetes.

### Necessário:

- Conhecimento e experiência avançado em .NET Full Framework e .NET Core;
- Conhecimento e experiência em SQL Server, Oracle, Redis, ElasticSearch, MongoDB,Cassandra e Google BigQuery;
- Conhecimento e experiência com testes de unidades, TDD (test driven development) e testes integrados (API e interface);
- Conhecimento e experiência em AWS;
- Conhecimento em sistemas distribuídos: utilização de sistemas de filas, consistência eventual, resolução de conflitos, etc;
- Experiência com integração contínua (CI) e entrega contínua (CD);
- Conhecimento e experiência em Docker e Kubernetes;
- Conhecimento e experiência nos sistemas operacionais Windows e Linux;
- Conhecimento e experiência em sistemas de mensageria (RabbitMQ, SNS, SQS, Kafka,etc);
- Conhecimento e utilização prévia das metodologias SCRUM e Kanban;
- Capacidade de conduzir entrevistas e reuniões;

### Conhecimentos desejáveis:

- PHP, NodeJS, Java e AWS Lambda;

### Benefícios oferecidos:

- Vale de Refeição;
- Vale Transporte;
- Estacionamento;
- Assistência médica (Unimed);
- Assistência odontológica;
- Seguro de vida;
- A partir de 6 meses de empresa: Bolsa de Estudos junto ao sindicato (SAAEMG) para escola infantil: de 20% a 40%;
- A partir de 3 meses de empresa: Bolsa de estudos (90% graduação, 50% pós-graduação), extensivo a dependentes legais.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/anima_arquiteto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
