### ISSUE TITLE
[Balneário Camboriú] Desenvolvedor FullStack na BROKERHUNTER

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1761]
### Sobre a empresa: BrokerHunter

A BronkerHunter é um hub imobiliário! Existimos para desenvolver recursos técnicos e humanos para promover a prosperidade das partes envolvidas em negociações imobiliárias. Temos em nosso portfólio produtos que abrangem formações e treinamentos, rede de negócios imobiliários, plataforma imobiliária, consultoria e acessória.

### Requisitos obrigatórios:

PHP;
POO
JavaScript (JQuery)
MySQL
HTML 5
CSS 3
GIT
Wordpress

### Vai brilhar nossos olhos se você conhecer:

Laravel
Codeigniter
Unix (servidor Linux e Nginx)
Segurança de dados
Metodologias ágeis

### Informações complementares:

Podemos estudar candidatura remota

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/brokerhunter_fullstack

**Comment by thallysrc** [comment]
esse link não está funcionando aqui, eu clico em enviar mensagem e acontece nada

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
