### ISSUE TITLE
[Lauro de Freitas - BA] Desenvolvedor FullStack na Sotero Tech

### ISSUE THREAD

**Issue by fxcosta** [backend-br/vagas#1762]
# Descrição da Vaga
A Sotero Tech está em busca de devs para contribuir na criação e manutenção dos nossos diversos sistemas e produtos.

Atuar em correções, melhorias nos projetos já existentes e novos projetos, com atenção especial na qualidade do código. Buscamos um profissional retado e que esteja disposto aprender e compartilhar conhecimento e experiência conosco, participando desde o processo de arquitetura, análise, evolução até a produção das nossas soluções.

Se você adora desafios, tem fome por aprendizado e gosta de ambientes descontraídos com foco em evolução constante, venha trabalhar conosco!

# Local de trabalho:
-Presencial em Lauro de Freitas - Bahia

# Benefícios
-Vale Alimentação
-Vale Transporte
-Salário à combinar

# Requisitos 
## Requisitos obrigatórios:
-Ensino superior cursando ou completo em sistema da informação e áreas afins;
-Conhecimento e experiência com PHP (Orientação a objetos, Design Patterns, SOLID);
-Experiência em algum framework PHP (Zend Framework, Laravel e/ou Symfony)
-Conhecimento em versionamento de projetos usando Git;

## Diferenciais:
-Experiência com desenvolvimento de APIs REST
-Conhecimento e experiência com JavaScript (ES6+ e ecossistema);
-Testes unitários

# Como se candidatar
Enviar CV, pretensão salarial e portfólio/Github (se tiver) para selecao@soterotech.com.br

# Labels
- PHP
- Presencial
- CLT
- Junior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
