### ISSUE TITLE
[Belo Horizonte] SRE - Site Reliability Engineer na Rock Content

### ISSUE THREAD

**Issue by adrianoresende** [backend-br/vagas#1763]
É desenvolvedor ou conhece um desenvolver que deseja trabalhar em uma Startup de alto crescimento ?

Para quem não sabe, a [Rock Content](https://rockcontent.com) lançou um produto novo a 6 meses, chamado [Rock Stage](https://stage.rockcontent.com).

Estamos crescendo super rápido **(30% mês a mês)** e estamos somente começando.

Acabamos de abrir duas vagas para nosso time de desenvolvimento:

1) SRE - Site Reliability Engineer
2) Desenvolvedor Backend de Node

Se você se encaixa em algumas das vagas tenho certeza que vai se interessar em saber que:
- A stack inclui: Kubernetes, Docker, NodeJS, React, Serverless e muita, mas muita coisa na AWS.
- Aqui na plataforma passam mais de 80.000.000 de requests por mês
- Você trabalhará com um time distribuído, internacional e profissionais com mais de 10 anos de experiência.

Mais informações sobre a vaga e requisitos:

Site Reliability Engineer - SRE:
https://jobs.lever.co/rockcontent/a10d32b7-a3ef-4b5e-9929-d1f832b0dbbd

Backend Developer - Node:
https://jobs.lever.co/rockcontent/79d9eb59-e2e6-43a5-96ed-b03f5799b07c

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
