### ISSUE TITLE
[Belo Horizonte] - Pessoa desenvolvedora fullstack na itexto

### ISSUE THREAD

**Issue by kico-itexto** [backend-br/vagas#1766]
Estamos ampliando nosso time de desenvolvimento em Belo Horizonte.

### Requisitos essenciais

* Residir em Belo Horizonte ou região
* Conhecimento mínimo de inglês (ao menos leitura e compreensão).
* Desejável: já ter realizado estágio na área de desenvolvimento e ter ao menos dois anos de experiência comprovada com as tecnologias essenciais citadas abaixo.
* Conhecimentos sólidos em ciências da computação (acredite, é nossa ferramenta mais usada).

#### Experiência nestas tecnologias:
* Spring Boot (com parte do stack, tal como Spring Data, Security, MVC).
* Angular

#### Diferenciais interessantes para o momento
Note que estas não são as tecnologias que mais usamos, mas que tem desempenhado um papel cada vez maior em nosso dia a dia, sendo assim não devem ser levadas como seu único diferencial para a vaga.

* Desenvolvimento no stack Java EE (JSF, CDI, JPA)
* Plataforma .net (desenvolvimento web, para lidar com aplicações legadas desenvolvidas em ASP.net (MVC e Web Forms))

### O que você poderá aprender conosco
As tecnologias citadas acima são necessárias para que a pessoa possa ser inserida imediatamente em alguns de nossos projetos. Entretanto não são as únicas tecnologias com as quais trabalhamos. Atuamos com uma gama bem mais ampla:

* Sólidos conhecimentos em arquitetura e engenharia de software nos mais variados mercados e tecnologias
* Groovy / Grails
* Java EE (JSF/CDI/JPA...)
* Node.js
* PHP (WordPress, frameworks de mercado como Laravel, CakePHP....)
* Frameworks front-end muito variados (Vue.js, Ionic, jQuery, React....)
* Diversos provedores de cloud (AWS, Google Cloud, Digital Ocean....)
* Tecnologias de integração diversas.
* Tecnologias para desenvolvimento mobile (híbrido).
* Plataforma .net

E outras tecnologias que surgem a partir da nossa interação com sistemas pré-existentes de nossos clientes.

Você poderá atuar nestas tecnologias. Quando for o momento a itexto irá lhe fornecer todo o suporte necessário para que possa aprendê-las em horário de trabalho.

Maiores detalhes sobre nossa cultura assim como o formulário de inscrição para a vaga podem ser consultados neste link: http://www.itexto.com.br/site/venha-trabalhar-e-crescer-conosco-2/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
