### ISSUE TITLE
[São Paulo] Pessoa Desenvolvedora (Python ou Node) na Gupy

### ISSUE THREAD

**Issue by rghossi** [backend-br/vagas#1767]
A Gupy é uma empresa de tecnologia que une um grupo de engenheiros de softwares apaixonados em gerar inovação para oferecer contratações mais ágeis, justas e encantadoras à sociedade. Somos movidos por grandes desafios e precisamos de pessoas que amem tecnologia, aprendizado constante, e que tenham muita gana para nos ajudarem a transformar a Gupy na melhor e maior empresa de Recrutamento Tech do Brasil.

Estamos crescendo muito rápido e criando a cada dia um produto ainda mais poderoso. O segredo disso? As pessoas incríveis que fazem parte conosco dessa construção contínua.

Estamos expandindo nossa arquitetura de serviços e queremos sua ajuda! Se você é a pessoa que sabe e/ou tem interesse em aprender:

- Desenvolver plataforma web usando Python, Django e Serverless;
- Manter infraestrutura de serviços e bancos de dados hospedados na AWS;
- Definir e manter monitoramento de todas aplicações.

**Como requisitos básicos, você deve ter:**

- Mínimo de 4 anos de experiência como desenvolvedor/desenvolvedora de software;
- Sólido conhecimento em Python
- Hábito de aplicar boas práticas de engenharia de software;
- Hábito de fazer testes (unidade / funcionais / integração) no dia a dia;
- Hábito de fazer refatoração no dia a dia;

**Você se destaca, se tiver:**

- Conhecimento básico de Infrastructure as code (Docker, Chef, Puppet, Ansible, Kubernetes)
AWS
- Bancos de dados relacionais (postgres) e não relacionais (redis ou similar)

**Link pra vaga Python:** https://tech-career.gupy.io/jobs/95685

**Link pra outras vagas:** https://tech-career.gupy.io

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
