### ISSUE TITLE
[Florianópolis - SC] Desenvolvedor FullStack na WAY2

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1768]
### Sobre a empresa: Way2

Way2 Tecnologia é uma empresa que desenvolve soluções de software voltadas ao Setor Elétrico Brasileiro. Somos referência nesse tema e líderes nos segmentos de Geração e Distribuição de Energia. 

Mais da metade de toda a energia gerada no Brasil é medida pela nossa plataforma. Além disso, estamos presentes em 70% das distribuidoras do país e ainda somos responsáveis pelo desenvolvimento e pela manutenção da maior plataforma de medição de faturamento do país. É importante mencionar que estamos entre as três melhores empresas para se trabalhar em SC. Tudo isso por quatro anos seguidos!

### Descrição: O que você fará?

O desafio é desenvolver melhorias e novos módulos para uma plataforma utilizada pelas principais geradoras e distribuidoras de energia do país. Pela característica dessa atividade, é interessante que o profissional tenha experiência em metodologia ágil (scrum) e code review, pois é muito importante que preze pela qualidade do software.

### Stack de tecnologias usadas:

Frontend: Vue / Knockout;
Backend: Asp.net MVC e Asp.net Core;
Banco de Dados: Oracle.

### Você vai gostar de trabalhar na Way2 se...

For uma pessoa engajada, que gosta de trabalhar bem em equipe e é colaborativo com os pares;
Tem capacidade de rápido aprendizado;
Tem bom nível de atenção;
É pessoa acessível e de boa convivência.

Recomendo você dar uma passadinha no site, no Instagram e no Linkedin pra entender um pouco mais sobre a cultura e como é trabalhar lá. 🤩

### E quais são os Benefícios que você terá direito???

Horário Flexível;
Vale-Transporte sem desconto;
Estacionamento gratuito (o custo de ~R$280 é pago pela Way2);
Vale-Refeição ou Vale-Alimentação (R$23,27 por dia) sem desconto;
Plano de Saúde Bradesco sem coparticipação e com possibilidade de reembolso para consultas em médicos não credenciados;
Plano Odontológico Uniodonto sem coparticipação;
Mil reais por ano para sua capacitação;
Ginástica Laboral três vezes por semana;
Frutas, café, leite e chá à vontade;
Sala de descompressão (fliperama, instrumentos musicais, mesa de poker, etc..);
**Após 6 meses de admitido poderá fazer home office full-time (obs: o início deverá ser presencial).**

### Resumimos o que você terá se for trabalhar na Way2:

Morar em Florianópolis;
Gestão moderna;
Expertise no setor elétrico;
Desenvolvimento profissional;
Preocupação com sua qualidade de vida;
Ambiente de trabalho incrível.
Acesse aqui e veja mais sobre nós!

**Nível de experiência:**
Pleno 

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/way2_fullstack2

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
