### ISSUE TITLE
[Pato Branco - PR] Programador Java na Viasoft

### ISSUE THREAD

**Issue by rhviasoft** [backend-br/vagas#1769]
Estamos contratando Programadores Java para atuar na cidade de Pato Branco - PR

Buscamos desenvolvedores que gostam de novos desafios e querem trabalhar com tecnologias de ponta.

Os selecionados para as vagas trabalharão com tecnologias e frameworks de programação como: Spring, Angular 6, ElasticSearch,  Selenium, Kibana, Logstach, SonarQube, dentre outras, além de práticas e ferramentas DevOps, como: Maven, Sonatype Nexus, Jenkins, Docker, Kubernetes, entre muitas outras.

**Requisitos Essenciais:**
- Ter experiência em Desenvolvimento Java e Javascript;
- Ter paixão por programação;
- Ser colaborativo e gostar de trabalhar em equipe.;
- Ser crítico em relação à qualidade de código.

**Requisitos Desejáveis:**
- Conhecer algumas tecnologias como: React, Angular, Spring, entre outras!
- Conhecer bancos dados: MySql e/ou Oracle.
- Conhecimento em metodologias ágeis (Scrum)

**Benefícios:**
Plano de Saúde, Plano Odontológico, Vale Alimentação e auxílios a graduação, especialização e cursos relacionados a área de atuação.

Interessados devem enviar email para alana.tamagno@viasoft.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
