### ISSUE TITLE
[São Paulo-SP]  Desenvolvedor Full Stack na Marmotex  - Presencial

### ISSUE THREAD

**Issue by FernandaAbreu** [backend-br/vagas#177]
## Descrição da vaga

O time de desenvolvimento da Marmotex está procurando por desenvolvedores "gente boa", apaixonados por desafios, comprometidos e proativos.
Que tenha paixão pelos nossos principais objetivos que é alimentar, deixar as marmotinhas felizes e uni-las através do almoço no trabalho. Afinal, a #AComidaNosUne.

### Local
Vila Olimpia 

## Formação e Conhecimento:

- Formação em Ciências da Computação, Engenharia da Computação e afins;
 
- Sólidos conhecimentos em programação orientada a objetos, padrões de projeto e engenharia de software;

- Conhecimentos em Node.js, Vue.js, Firebase, Elasticsearch, MySQL, MongoDB, Redis , Nginx e Git;

-  Conhecimento em Docker 

- Conhecimentos em infraestrutura de servidores  Linux;

- Desejável conhecimento em Kotlin ou java para Android ou Swift para IOS

- Pro atividade;

### Responsabilidades:
- Participar de todas as etapas de desenvolvimento do projeto, com foco no desenvolvimento e solução de problemas;

- Escrever códigos limpos e funcionais para aplicações web e/ou mobile;

- Utilizar linguagens de marcação como HTML para criar páginas amigáveis;

- Manter e aperfeiçoar sites;

- Definir e atender os requerimentos técnicos e de design das aplicações;

- Acompanhar novas tecnologias;

- Conseguir aprender novas ferramentas de trabalho de forma rápida e por conta própria;

- Opinar em decisões de arquitetura dos produtos;

- Como uma marmotinha você irá participar de:

- Ambiente descontraído;

- Uma equipe que usa tecnologia de ponta e disruptiva;

- Ambiente de startup;

- Code Review;

- Meetups internos  sobre tecnologias usadas na empresa.

## Contratação

Como se candidatar
Envie um email para fernanda@marmotex.com

**Comment by trickstival** [comment]
Bem legal essa vaga, me identifiquei com vários dos requisitos. Pena que é presencial
