### ISSUE TITLE
[São Paulo] Desenvolvedor Node.js na SANAR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1771]
### Sobre a empresa: Sanar

Somos uma editora comprometida em ajudar o estudante da área de Saúde a atingir todos os seus objetivos profissionais e acadêmicos. Dentro desta perspectiva, seguimos a filosofia editorial de conceber um livro para cada um desses objetivos. Para tanto, formamos um time composto por mais de 100 professores das principais Universidades do país que assinam a autoria das nossas obras. 

### Descrição:

A Sanar tem uma pegada de startup e está sempre em busca de profissionais que estejam antenados com as novas tecnologias, práticas ágeis e inovadoras, além de amar pessoas focadas em resultados.

Temos um ambiente bastante descontraído e gostoso de trabalhar 😎.

Dá uma olhada nesse vídeo com colaboradores da empresa nos contando como é trabalhar lá.

Mas vamos ao que interessa! 🎯

### Ocupações do cargo:

O profissional integrará uma equipe dividida por squads, atuando no desenvolvimento da plataforma digital da Sanar.

Para isso é importante ter conhecimento e experiência sólida com:

Node.js;
Banco de dados relacionais e não-relacionais (por exemplo: MySQL e MongoDB);
Ciclo de vida de serviço e APIs, desde a concepção e design, ao deploy e troubleshooting;
Testes unitários, de aceitação, mocks, integração e BDD;
CI ou CD e com source control tools como Gitlab, Github, etc.

### Diferenciais:

Frameworks Javascript como Angular, React, React Native e/ou Vue;
Data e/ou Video Streamming;
Docker;
Kubernetes;
Desenvolvimento de controllers e operators para Kubernetes;
Micro-serviços escalonáveis horizontalmente e aproveitando técnicas de programação funcional e arquitetura hexagonal.

### Local de trabalho:

Flexível: o profissional poderá trabalhar na cidade de SP, Salvador ou remotamente.

### Benefícios:

Vale transporte ou auxílio gasolina;
Vale Alimentação (R$ 22,00 dia);
Plano de Saúde Unimed;
Possibilidade de participação em eventos de tecnologia financiados pela Sanar.
✔️ Ah, estamos super interessados em receber candidatos de todo o país, inclusive os que moram em outros Estados e por isso oferecemos:

Auxílio Moradia de R$500,00 durante 6 meses (para candidatos que precisarem mudar de cidade e/ou ir para Salvador) (se você gostar de praia, sua vida tá feita hein!🌊 🌞).

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/sanar_remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
