### ISSUE TITLE
[São Bernardo do Campo - SP] Desenvolvedor BackEnd na HYPNOBOX

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1775]
### Sobre a empresa: Hypnobox

Na Hypnobox ajudamos imobiliárias e incorporadoras a transformarem leads em comissões, unindo nosso CRM com a Metodologia Uselink de geração de leads e o ChatBox, nosso robô de atendimento específico para o mercado imobiliário. Nos orgulhamos de ter como parceiros 98 das 100 melhores empresas do mercado, como MRV, Tegra, Helbor, Diálogo, Tecnisa, Gafisa, Trisul, Lopes, Brasil Brokers e várias outras. 

### Descrição: O que você irá fazer:

Atuar em soluções de software usando as melhores práticas;

### Você vai amar trabalhar aqui se:

Está em busca de um ambiente de trabalho com hierarquia horizontal;
Quer ser além de desenvolvedor um analista de negócios;
Seja uma pessoa dinâmica e com muita energia;
Quer se tornar um profissional de referência no mercado;
Está em busca de um ambiente de trabalho colaborativo e de muito crescimento;
Entende TI como um desafio gostoso;
Pensa fora da caixa!!

### Requisitos obrigatórios:

Node.JS
Mongo DB
Vue.JS

### Informações complementares:

Estamos localizados no centro de São Bernardo do Campo - SP;
Contratação PJ.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/hypnobox_backend1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
