### ISSUE TITLE
[Arujá/Guarulhos/Itaqua/Suzano/Mogi, SP] Ruby Developer na RH Software

### ISSUE THREAD

**Issue by marcosgugs** [backend-br/vagas#1776]
## Sobre a RH Software

Há 20 anos no mercado, com excelência em programas para gerenciamento de consultórios e clínicas, a RH Software possui hoje milhares de clientes no Brasil e no exterior.  
Trabalhamos para oferecer produtos excelentes com pós-venda excepcional.  

Saiba mais sobre a empresa no site http://www.rhsoftware.com.br

## Sobre a Vaga

Esperamos que você seja comprometido com a qualidade do seu trabalho. Que saiba trabalhar em equipe e esteja sempre interessado em aprender mais.
Você fará parte da equipe de desenvolvimento do [Dental Office](http://www.dentaloffice.com.br), melhor software de gestão de clínicas odontológicas do Brasil, de acordo com o Cloudia. ([Os 3 melhores softwares odontológicos para a gestão de clínicas e agendamentos](https://www.cloudia.com.br/melhores-softwares-odontologicos/))

## Esperamos que você domine:
- Ruby
- Rails
- MySQL
- Git
- HTML5, CSS3

## Sería incrível se você conhecesse:
- AngularJS
- React
- React Native

## Nível Mestre Jedi:
- Linux / AWS
- DevOps
- NodeJS
- Elixir
- ElasticSearch

## O que oferecemos:

- Salário competitivo
- Ambiente descontraído
- Passaporte para eventos
- Alimentação
- Transporte
- Convênio Médico
- PLR
- Bonificação por desempenho

Caso este seja o seu perfil, venha bater um papo com a gente aqui na RH Software. Estamos localizados em Arujá/SP, próximo a Guarulhos, Suzano, Mogi das Cruzes, etc. 
Envie seu currículo ou LinkedIn para o e-mail trabalheconosco@rhsoftware.com.br para agendar a visita.

## Labels
- Alocado
- CLT
- Pleno
- Senior
- Junior
- Ruby

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
