### ISSUE TITLE
[São José do Rio Preto - SP] Desenvolvedor FullStack na DIDÁCTICA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1779]
### Sobre a empresa: Didáctica

A Didáctica é formada por um time multidisciplinar apaixonado por aprender e promover o aprendizado, com experiências e conhecimentos variados nas áreas de educação, comunicação, design, tecnologia e principalmente no relacionamento com pessoas. 

Nossa visão é ser referência nacional no desenvolvimento de soluções criativas que visam não apenas a educação mas o aprendizado e a geração de resultados concretos para os alunos de nossos treinamentos e empresa que nos contratam.

### Descrição

A Didáctica está crescendo e nossa equipe de tecnologia precisa de uma pessoa incrive para nos acompanhar nos próximos passos de nossa expansão. Você é uma pessoa que está a fim de crescer junto busca desafios incriveis? Dê uma conferida nesta oportunidade:

### O que você irá fazer?

Ira participar do nosso time de desenvolvimento, atuando na manutenção dos projetos já existentes e também auxiliando a criação de novos projetos.

Ira fomentar discussão e elucidação de requisitos com o time de produto. Alem de propor estimativas de esforço para execução de tarefas de desenvolvimento e testes unitários; E definição arquitetural de micro-serviços, APIs REST e bancos de dados a serem utilizados;

### As habilidades necessárias

• Experiência com aplicações Web (HTML, CSS e Javascript)
• Experiência com Bancos de Dados não relacionais (MongoDB)
• Experiência com ferramentas de controle de versão (Git e Github)
• Clean Code
• Experiência com API Rest
• Inglês intermediário
• Experiência Ruby on Rails ou Python ou Java

### Desejável

Experiência Frameworks JS: NodeJS, Vue.js, React
Capacidade de comunicação oral e escrita em inglês

### Diferenciais

Experiência em Ambientes Virtuais de Aprendizagem (AVA) e Learning Management Systems (LMS)
Envolvimento no desenvolvimento de Mobile app
Conhecimento de DevOps na AWS ou Google Cloud
Experiência com TDD (Test Driven Development) / BDD (Behaviour Driven Development)
Experiência Rspec e capybara 
Experiência com Heroku\Surge
Experiência com Postman ou Insomnia
Noções de UX
Experiência com Docker

### Benefícios

Contratação PJ ou CLT
Vale transporte
Vale refeição
Plano de saúde e odontológico
Ambiente descontraído
No dress code
Universidade corporativa, workshops e cursos
Custeio de Cursos e Certificações - 50%
Cultura mesclada entre Startup e Enterprise

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/didactica_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
