### ISSUE TITLE
Analista Desenvolvedor .NET na Sirius Interativa

### ISSUE THREAD

**Issue by didicosta** [backend-br/vagas#178]
## Descrição da vaga

Procuramos Analista Desenvolvedor .NET acima da média para fazer parte do nosso time.

Você será parte atuante na construção de ambientes web de grande relevância.

## Local

Escritório, Rio de Janeiro - Barra da Tijuca

## Requisitos

**Esperamos que você possua:**
- Experiência mínima de 2 anos com meios digitais (sites, aplicativos, sistemas)
- Experiência mínima de 2 anos com C# .NET
- Experiência com construção e consumo de Web Services e APIs;
- Conhecimento de Web API
- Domínio de SQL;
- Domínio de SQL Server;
- Proeficiência com Stored Procedures no SQL Server
- Experiência com Web Forms / MVC;
- Código eficiente, escalável, acessível e reutilizável
- Facilidade para trabalhar em equipe e contribuir com seus pares
- Boa comunicação verbal e escrita

**Desejamos que você possua:**
- Conhecimentos de Vue.js
- Conhecimentos de HTML/CSS
- Conhecimento de Javascript
- Familiaridade com Javascript
- Familiaridade com controle de versão (preferencialmente Git)
- Inglês avançado

## Contratação

PJ

## Nossa empresa

www.sirius.com.br

## Como se candidatar

Por favor, envie um email para rh.ti@sirius.com.br com seu CV anexado - enviar no assunto: Vaga Analista Desenvolvedor .NET

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
