### ISSUE TITLE
[Maringá] Desenvolvedor PHP  [Precode Soluções em e-commerce]

### ISSUE THREAD

**Issue by PrecodeSolucoes** [backend-br/vagas#1780]
**Nossa empresa**

O nosso negócio é fazer e-commerce. A Precode foi criada à partir da necessidade de nossos clientes em entrar e permanecer no mercado de e-commerce de maneira diferenciada, entendemos que a qualidade no atendimento, respeito ao cliente aliado a um negócio estruturado e inovador é o foco principal para agregar resultados com alta performance.
Nossa equipe de especialistas trabalha no planejamento, implantação, treinamento e suporte de cada área com uma estrutura 100% própria, da programação à execução. Essa é a nossa essência e o nosso objetivo: oferecer tecnologia, infraestrutura e experiência para que o negócio do nosso cliente se desenvolva no e-commerce de forma segura, dinâmica e sustentável.

**Sobre essa vaga:**

**Atividades e Responsabilidades**

- Desenvolvimento e manutenção de aplicações web;
- Desenvolvimento e manutenção de aplicações mobile;
- Realizar a manutenção e criação de novas funcionalidades;
- Desenvolvimento de funcionalidades no Back-End;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Desenvolver e sustentar integrações;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Desenvolvimento de funcionalidades no Front-End;

**Requisitos**

- Formação em ensino superior ou técnico;
- Habilidades interpessoais de escrita e de comunicação verbal;
- Experiência prévia nas linguagens:
•	PHP Orientado Objeto 
•	Desenvolvimento PHP e PostgreSQL 
•	Desenvolvimento e integração de API Rest 
•	Soap
•	JQuery 
•	JavaScript

O que nós oferecemos:
 
PJ ou CLT
Salário: Até R$6.000
Plano de Saúde
Vale Transporte
Vale Alimentação

Contato: recrutamento@precode.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
