### ISSUE TITLE
[Belo Horizonte-Remoto] Back-End Node.js Developer no MelhorPlano

### ISSUE THREAD

**Issue by GuilhermeLLS** [backend-br/vagas#1784]
### **Sobre o MelhorPlano**
O Melhor Plano é uma solução que ajuda os consumidores a tomarem a melhor decisão na contratação de serviços. Nosso objetivo é ajudar milhões de pessoas a economizarem bilhões!
Atualmente, somos os líderes em comparação de telefonia no Brasil e já impactamos mais de 8 milhões de brasileiros a tomarem decisões mais informadas com planos de celular, banda-larga, fixo, tv e combos!

### **Sobre a Vaga**
Há muito software por trás da solução do melhorplano.net. Você trabalhará com o desenvolvimento de crawlers, buscando sempre oferecer uma informação precisa para os consumidores. Nosso stack consiste no uso de tecnologias como Node e React para proporcionar uma experiência de uso fácil e rápida.

**Algumas das atividades que você desenvolverá no dia-a-dia são:**

- Manutenção e desenvolvimento de crawlers em Typescript e Node
- Desenvolvimento backend em Typescript e Node
- Integração com APIs de parceiros
- Integração com outros sistemas de CMS, Google Sheets, Airtable, etc.
- Desenvolvimento de testes automáticos
- Desenvolvimento front-end em Typescript e React

**Para aplicar acesse: https://melhorplano.net/vagas/dev-backend e preencha o formulário**

### **Local de Trabalho e Benefícios**

- Salário CLT + auxílio alimentação e transporte(salário de acordo com a experiência, você pode informar sua expectativa salarial ao se candidatar para a vaga.)
- Flexibilidade de horário (Tempo integral);
- Trabalhe parte do tempo de onde quiser - seu computador e boa internet é o suficiente. Somos um time parcialmente remoto. Nos encontramos com frequência em nosso escritório em Belo Horizonte, mas não precisamos trabalhar todos os dias de lá;

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Essa vaga é 100% remoto?
Sou do RJ.
http://danielsiqueira.net

**Comment by GuilhermeLLS** [comment]
Olá@danielsidev , tudo bem e você?
100% remoto. Perdão pela demora.

**Comment by wesleybruno** [comment]
O link para se candidatar não está funcionando, ainda está disponivel?

**Comment by danielsidev** [comment]
Me candidatei!

**Comment by danielsidev** [comment]
> Olá@danielsidev , tudo bem e você?
> 100% remoto. Perdão pela demora.

Tudo ótimo!
Me candidatei!

**Comment by GuilhermeLLS** [comment]
> O link para se candidatar não está funcionando, ainda está disponivel?

@wesleybruno eu tentei aqui e está funcionando normalmente. 
Tente acessar o link do formulário(https://airtable.com/shrsOQpQvGhXbAkpC).

Se esse link do formulário der errado também, me avise por favor.

**Comment by wesleybruno** [comment]
@GuilhermeLLS consegui me candidatar pelo link, obrigado!
