### ISSUE TITLE
[Belo Horizonte]  Desenvolvedor BackEnd Júnior na WAYCARBON

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1786]
### Sobre a empresa: WayCarbon

A WayCarbon é referência em assessoria sobre mudança global do clima, gestão de ativos ambientais e no desenvolvimento de estratégias e negócios visando a ecoeficiência e a transição para uma economia de baixo carbono. Preservando a objetividade e a integridade do nosso trabalho, enfrentamos problemas complexos com coragem para propor soluções não convencionais que exploram as oportunidades de mercado.

### Descrição:

A WayCarbon está no mercado há 13 anos, é referência no que faz, e possui escritórios em Belo Horizonte, Rio de Janeiro e São Paulo.

A Way tem pegada de startup e vem crescendo em ritimo aceleado. Por isso valoriza práticas ágeis e inovadoras, além de amar pessoas focadas em resultados.

O ambiente de trabalho é bastante descontraído e agradável 😎.

Mas, vamos ao que interessa! 🎯

### Ocupações do cargo:

O profissional integrará uma equipe bastante diversa com capacidades complementares e times autogeridos.

### Para isso é importante ter conhecimento e experiência com:

Linguagens JavaScript (Node.js), Python e PHP;
Frameworks MVC;
Linux (CLI);
Engenharia de software, testes unitários, estrutura, desenvolvimento orientado a objetos;
Banco de dados MySQL, MongoDB;
Infraestrutura em container.

**Conhecimentos e experiências abaixo não são obrigatórios, mas são um grande diferencial:**

### Conhecimento em:

HTML, CSS;
Cake PHP;
Flask, Express;
RESTful APIs.

### Local de trabalho:

Savassi.

### Benefícios:

Vale transporte;
Vale alimentação (R$ 385,00 por mês);
Vale refeição (R$ 385,00 por mês);
Plano de Saúde Unimed;
Bônus mensal (até R$ 700,00 por mês);

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/waycarbon_junior

**Comment by mateus228leal** [comment]
Aceita candidatos de fora?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
