### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Backend Júnior no GORILA - gorila.com.br

### ISSUE THREAD

**Issue by ricalamino** [backend-br/vagas#1787]
<h2>Descrição da Vaga</h2>
- Desenvolvimento e manutenção do backend do aplicativo web e mobile Gorila;
- Desenvolvimento de micro-serviços modulares;
- Participação em decisões de desenho da arquitetura;
- Desenvolvimento em ambiente cloud;
- Participação em decisões de uso de novas tecnologias.

<h2>Local</h2>
Escritório em São Paulo - SP

<h2>Requisitos</h2>
- Recém-formado na área de Engenharia, Computação, Análise de Sistemas (ou atuando na área há pouco tempo com outra formação Superior);
- Conhecimento de uma ou mais linguagens de programação (Python, C, Java...);
- Inglês avançado.

<h2>Extras</h2>
- Experiência com banco de dados não-relacional (NoSQL); 
- Experiência com Docker, Kubernetes, Codeship, Jenkins. 
- Experiência com Cloud (AWS, Azure)

<h2>Contratação</h2>
CLT

<h2>Benefícios</h2>
VR, VA e Plano de Saúde

<h2>Sobre a empresa</h2>
O Gorila é um consolidador de investimentos para pessoa física e para profissionais de investimento. A solução conta com todos os principais produtos financeiros do mercado brasileiro, mostrando a rentabilidade e a distribuição dos ativos por tipo e classe de ativo.

O Gorila existe há 3 anos e já se consolidou como uma das principais ferramentas no setor, contando com colaboradores altamente preparados e com expertise na área financeira e de desenvolvimento em TI.

O ambiente na empresa é colaborativo, descontraído e oferecemos uma compensação acima dos valores médios do mercado. Valorizamos diversidade, flexibilidade e criatividade!

<h2>Contato</h2>
<a href="mailto:vagas@gorila.com.br">vagas@gorila.com.br</a>

**Comment by burn-c** [comment]
Disponibilidade para alguma vaga remota ?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
