### ISSUE TITLE
[Mooca, São Paulo - SP] Desenvolvedor(a) Back-End Pleno na Easytech Tecnologia LTDA

### ISSUE THREAD

**Issue by etnishiyama** [backend-br/vagas#1788]
## Nossa empresa

Somos uma empresa nacional, atuando há vinte anos no mercado, oferecendo souções complexas de hardware software.

Localizados no Bairro da Mooca, dispomos de uma excelente estrutura e buscamos identificar um(a) Desenvolvedor(a) Android Sênior, que atuará em nossa unidade em São Paulo, no Bairro da Mooca, de segunda a sexta-feira em horário comercial.

## Local

Alto da Mooca (Zona Leste), São Paulo - SP

## Descrição da vaga

·        Desenvolver e manter serviços de alta disponibilidade e grande volume de acessos.
·        Definir boas práticas e arquitetura do sistema.
·        Desenvolvimento de APIs RESTful.
·        Documentação utilizando Swagger.
·        Integração com Sistemas Embarcados utilizando protocolos.
·        Deploy e gerenciamento de containers e servidores na nuvem.
·        Desenvolver novas soluções de comunicação, escrever protocolos (visando segurança).

## Benefícios

·       Ambiente inclusivo e desafiador, com ferramentas e tecnologias de ponta.
·       Desenvolvimento contínuo (on the job e treinamentos).
·       Assistência Médica e Odontológica, Vale-Transporte, Vale-Refeição e Café da Manhã.
·       Remuneração condizente com a posição e flexibilidade de vínculo empregatício.

## Requisitos

Obrigatórios:
·        Formação: Cientista da Computação, Matemática, Física, Análise de Sistemas e afins.
·        Raciocínio lógico, que saiba resolver problemas sozinho.
·        Experiência e sólidos conhecimentos em projetos Backend, Dotnet Core e Micro serviços.
·        Conhecimento intermediário em Banco de Dados SQL.
·        Experiência com deploy de sistemas de alta disponibilidade.
·        Experiência com desenvolvimento de APIs RESTful e/ou Webservices.

Diferenciais:
·       Experiência com gerenciadores de fila (RabbitMQ).
·        Conhecimento em processos de segurança (criptografia, desenvolvimento de processos seguro de comunicação, etc.).
·        Experiência com configurações de build e CI/CD.
·        Conhecimentos de testes de unidade e git.
·        Conhecimentos de Linux, servidores e IOS.
·        Inglês avançado.

## Contratação

CLT ou PJ

## Como se candidatar

Por favor, envie um email para everton.nishiyama@easytech.com.br com seu CV anexado e/ou LinkedIn - enviar no assunto: [Vaga Backend] ...

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
