### ISSUE TITLE
[São Paulo] Java Back-end Developer at AMARO

### ISSUE THREAD

**Issue by vithoriaamaro** [backend-br/vagas#1789]
A AMARO  é uma empresa de tecnologia que veio para (r)evolucionar o mundo da moda através de tecnologia e criatividade. 

Buscamos um desenvolvedor Java Back-end para se juntar ao nosso dreamteam de Engenharia. 

Atividades: 

Desenvolver features e integração em Java Spring 

Trabalhamos com: Java, Spring, JVM, SQL, Ehcache

Necessário inglês avançado :) 

Ficamos na Av. Paulista e oferecemos contratação CLT + benefícios completos. 

Buscamos profissionais com perfil analítico, paixão por tecnologia, seja pro-ativo e empreendedor.

Para participar do nosso processo seletivo você pode enviar o seu CV/Linkedin para o meu e-mail vithoria.duarte@amaro.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
