### ISSUE TITLE
[São Paulo] Back-End developer no CEPID NeuroMat

### ISSUE THREAD

**Issue by carlosribas** [backend-br/vagas#179]
## Descrição da vaga

Buscamos uma pessoa para trabalhar com o desenvolvimento de software de suporte à pesquisa científica do CEPID NeuroMat.

## Local

Instituto de Matemática e Estatística da USP, Cidade Universitária, São Paulo.

#### Diferenciais

- Horário flexível
- Assistir aulas e palestras do IME-USP 

## Requisitos

**Obrigatórios:**
- Título de doutorado OU 5 anos de experiência após a graduação em qualquer área da TI (exigência da FAPESP - http://www.fapesp.br/3098).
- Experiência com desenvolvimento web

**Desejáveis:**
- Python/Django (principal linguagem/framework que utilizamos)
- Docker
- Git
- Bootstrap
- Linux

**Diferenciais:**
- projetos opensource

## Contratação

Bolsa TT5 da FAPESP no valor de R$ 7.174,40 (http://www.fapesp.br/3162), para uma dedicação de 40 horas semanais.

## Nosso projeto

O CEPID NeuroMat, financiado pela FAPESP e sediado na USP, tem como objetivo integrar modelagem matemática e computacional com pesquisa básica e aplicada na fronteira da neurociência.

## Como se candidatar

Por favor envie um email para vagas-ti@numec.prp.usp.br com seu CV anexado - enviar no assunto: Vaga Back-End

## Labels

- Alocado
- Pleno
- Sênior

**Comment by carlosribas** [comment]
Vaga ainda disponível!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
