### ISSUE TITLE
[Valinhos - SP] Especialista Node.js na KROTON

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1790]
### Sobre a empresa: Kroton

Somos a maior empresa de educação do mundo, com aproximadamente 1,9 milhão de estudantes, dos quais 290.000 estão no segmento de ensino fundamental em 213 campi e 726 postes, divididos em 22 marcas educacionais localizadas em todos os estados brasileiros. 

### Descrição: Quer fazer parte da nossa revolução tecnológica?

**A Kroton procura por um profissional que seja referência em desenvolvimento Node, e que tenha habilidades de:**

- Desenvolver soluções com foco em qualidade, disponibilidade seguindo práticas Ágeis e melhores padrões de Arquitetura;
- Participar de refinamentos técnicos procurando entender o objetivo da estória colaborando com questionamentos para entendimento do desafio técnico envolvido;
- Desenvolver aplicações sob ótica do TDD garantindo a qualidade de suas entregas.

### Conhecimento necessário:

- Vasta experiência na atuação como desenvolvedor NodeJS;
- Experiência em desenvolvimento assíncrono;
- Desenvolvimento com webservices (SOAP e REST);
- Conhecimento em modelos ágeis utilizando Scrum e Kanban.

### Iremos amar também se você souber:

- Experiência em desenvolvimento com framework Express.JS;
- Experiência com front-end SPA (Angular ou React js e/ou React Redux);
- Já ter atuado com desenvolvimento PHP.

### Benefícios:

Ambiente Informal, Assistência Médica, Assistência Odontológica, Auxílio Academia, Auxílio Educação, Horário Flexível, Participação nos Lucros, Seguro de Vida, Vale Alimentação, Vale Transporte

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/kroton_node

**Comment by danielsidev** [comment]
Boa tarde!
Essa vaga pode ser remota?
Tenho interesse, mas estou no RJ.
LinkedIn: https://www.linkedin.com/in/danielsidev/
Site: http://danielsiqueira.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
