### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FullStack na CONSULTE GEO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1792]
### Sobre a empresa: Consulte GEO

Visando atender o crescimento na área da construção civil nacional, surgiu em 2007, a Consulte GEO. Uma empresa de software de gestão de obras, cujo sistema se caracteriza pela integração das ações em todos os níveis e etapas, do planejamento à execução, garantindo assim, a qualidade dos serviços contratados, tornando a gestão de obras ágil, organizada e eficiente. 

Trabalhamos com as maiores construtoras do país, desenvolvendo ferramentas escaláveis e que tragam melhorias na qualidade da engenharia brasileira.

### Descrição:

O principal produto da empresa é um software chamado GEO, criado para auxiliar construtoras, gerenciadoras e empresas do ramo da construção civil a realizarem, efetivamente, um trabalho de gestão sobre as atividades de seus empreendimentos. O GEO possui 11 diferentes módulos, que funcionam 100% web e trabalham de forma integrada e customizada de acordo com a necessidade de cada cliente, focado sempre na melhoria de processos e resultados.

### O que você irá fazer:

Participar do desenvolvimento de um novo sistema para usinas de concreto;
Diagnosticar e resolver problemas;
Propor novas soluções e inovações.

### Conhecimentos necessários:

Proficiência na linguagem de programação C#;
Domínio do Framework ASP.NET;
Domínio da tecnologia Microsoft SQL Server;
Experiencia com ASP.NET Core ou MVC.

### O que brilharia aos nossos olhos:

Experiência com Asp.Net Core;
Experiência com Entity Framework;
Experiência com Bootstrap.

### Benefícios:

Vale Transporte;
Vale Alimentação (em dinheiro);
Plano de Saúde;
Bônus anual por desempenho;
Investimento em cursos de qualificação para o profissional;
Opção de contração PJ ou CLT.

### Você vai gostar de trabalhar aqui se:

Prezar pelo trabalho em equipe;
Ser pró ativo;
For propositivo e gostar de grandes desafios técnicos;
Estiver em busca de uma empresa que preze pelo seu conhecimento e crescimento profissional.

### Informações complementares:

Estamos em um escritório próximo à Praça da Savassi.
https://consultegeo.com.br/
Pleno/Senior

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/consultegeo_fullstack1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
