### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack na SENSEDATA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#1794]
### Sobre a empresa: SenseData

A SenseData é a primeira plataforma de Gestão de Customer Success da América Latina. O sistema SenseData conta com modernos algoritmos que utilizam técnicas avançadas de análise de grandes volumes de dados, gerando insights relevantes para que as empresas gerem ação certa, no cliente correto no momento mais adequado. 

A empresa fez parte da primeira turma de residentes do Google Campus São Paulo e é uma das 100 Startups to Watch 2018 segundo a Revista Pequenas Empresas Grandes Negócios e o jornal Valor Econômico.

### Descrição: O que você irá fazer?

Detecção e correção de bugs;
Desenvolver novas funcionalidades no produto;
Integração de dados do cliente;

### As habilidades necessárias:

Python;
React;
Conhecimentos gerais de SQL e NoSQL;
Teoria de computação, algoritmo e estrutura de dados;

### Benefícios:

Além de um ambiente colaborativo, com muita troca de experiências, happy hour, cerveja, biscoito, pizza e nada de dress code, aqui você terá:

Vale Transporte;
13º;
Bônus anual;
Férias remuneradas;
Auxilio educação no valor de até R$1.500,00 anual;
Auxilio na compra ou melhoria do seu próprio computador no valor de R$1.000,00;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Tem gosto por inovação com excelência e um ambiente de trabalho dinâmico e desafiador;
Formação na área de engenharia, computação e afins será muito bem vinda;

### Informações complementares:

A contratação é PJ;
Estamos localizados em Pinheiros - São Paulo;
Pleno

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/sensedata_fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
