### ISSUE TITLE
[São Paulo/Alphaville] Dev Java AWS na ESX

### ISSUE THREAD

**Issue by ESX-Administracao** [backend-br/vagas#18]
# Quem somos?
A ESX conta com um time de mais de 60 profissionais dedicados a resolverem problemas complexos de negócio e provocar a transformação digital através de Dev + DevOps.

Fomos o primeiro parceiro Gold em Devops do Mundo, temos um time formado por MVP's, palestrantes, difusores de conhecimento em comunidade, além de incentivarmos iniciativas de desenvolvimento interno (sejam empreitadas individuais ou formação através de certificações pagas pela empresa).

> **Disclaimer**: o que se fala a partir de agora pode parecer marketing puro, mas através de uma visita às redes sociais dos membros do nosso time pode-se checar a veracidade :)

Estamos localizados em Moema, há 3 quarteirões do Shopping Ibirapuera.
Contamos com um ambiente _open space_ cheio de mimos a nosso time, como PS4 Pro, Chopeira, Fliperama, Rock Band e o mais importante: muito café.

Nos preocupamos com a integração de novos membros para que logo tenham a sensação de um Time, e o modelo de bodyshop/alocação não é praticado. A cada 15 dias fazemos um lunch party onde os funcionários escolhem onde querem almoçar e a empresa arca com o almoço, além disso temos verbas mensais dedicadas para o time escolher onde quer investir na empresa (a chopeira veio daqui), além disso incentivamos as atividades de integração "não-institucionais" entre o time, como exemplo, nossos famosos happy hours de quinta-feira.

# Sobre a vaga
Estamos em busca de Devs Java de nível Pleno e Sênior, em regime de contratação PJ, com salários num range de 8.750 a 11.000.

Além disso, a empresa paga certificações a seus funcionários com base em certos critérios e condições (melhor explicado na entrevista).

Para essa vaga, o time trabalhará in loco, em Alphaville. É desejável que tenha disponibilidade para trabalhar em Moema caso haja realocação de projeto.

O início dos trabalhos desses profissionais segue a seguinte escala:
- Desejável: imediato
- Negociável: 15 dias após contato

Casos em que sejam necessários mais de 15 dias serão avaliados com atenção, mas serão despriorizados para **este** projeto.

### Dev Java Pleno AWS
- Java 8
- GIT + Git Flow
- jUnit / Mockito 
- Maven
- DynamoDB / MySQL
- JMS / MQTT
- REST
- VSTS (desejável)

### Dev Java Senior AWS
**- Requisitos anteriores +**
- Docker
- BDD / Cucumber
- Spring / Spring Boot / Spring Core / Spring Data / Spring Integration
- Redis
- HornetQ
- NodeJs
- AWS
- EC2
- AWS SDK for Java
- Compose
- SQS
- Topic SNS

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
