### ISSUE TITLE
[São Paulo/SP] Tech Lead PHP na Voxus

### ISSUE THREAD

**Issue by gustavomgregorio** [backend-br/vagas#180]
## Descrição da vaga

Estamos procurando um desenvolvedor senior com vontade de crescer e ajudar a Voxus a crescer mais rápido. 

A pessoa ficará responsável por um pequeno time de programadores, além de trabalhar diretamente com C-Level da empresa para coordenar e entregar tasks de desenvolvimento de maior nível de dificuldade.

Além disso, é um plus se a pessoa tiver vontade e quiser aprender a fazer data analysis para melhorar os algoritmos de segmentação e compra de mídia da Voxus.

## Conhecimentos e tecnologias

**Obrigatórios:**
- PHP5+ 
- CakePHP ou Zend Framework
- ElasticSearch
- MySQL 

**Diferenciais:**
- Experiência formal em gestão de time técnico
- Utilização de APIs da AWS
- Experiência com report direto para C-Level

## Local

Empresa localizada em São Paulo, a um quarteirão da Av. Paulista, próxima à estação Brigadeiro do metrô

## Benefícios

- VT
- VR
- Opcional de plano de saúde

## Sobre nós

A Voxus (www.voxus.com.br) é uma empresa de tecnologia focada no mercado de e-commerces. 

A tecnologia da Voxus entende padrões de consumo através da coleta, processamento e cruzamento de dados comportamentais, prevendo quem são as melhores pessoas para exibir os banners de seus clientes. 

A Voxus estima impactar R$500 milhões de receita para e-commerces em 2018. 

## Como se candidatar

Envie um email para gustavo@voxus.tv

## Labels

- CLT
- Presencial
- PHP

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
