### ISSUE TITLE
[São Paulo] Back-End Developer na iBlue consulting

### ISSUE THREAD

**Issue by ana-sene** [backend-br/vagas#1800]
## Descrição da vaga

Estamos buscando desenvolvedor Back-End para o nosso time na Vila Olímpia, SP, para atuar com Java e AWS.

## Local

São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Plano odontológico
- VR de R$ 25,31/dia
- VT
- TotalPass

#### Diferenciais

- Horário flexível
- Treinamentos com nossos parceiros

## Requisitos

- Experiência com Java, AWS, SPA, HTML, CSS, JavaScript, metodologias CSS (BEM, Atomic, OOCSS, ...)

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rhrio@iblueconsulting.com.br com seu CV anexado - enviar no assunto: Vaga Back-End - SP

## Labels

- Alocado
- CLT
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
