### ISSUE TITLE
#Vaga [Software Engineer Back End] São Paulo

### ISSUE THREAD

**Issue by barbosarrodrigo1** [backend-br/vagas#1801]
A Cora está nascendo, e precisa de você para construir um novo banco.

É tudo do zero! Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.

Não buscamos uma stack específica, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

**Comment by GuiziBr** [comment]
Ola @barbosarrodrigo1 , vi na descrição da vaga que o requisito é conhecimento aprofundado  em ao menos uma linguagem.

Vocês estão contratando Junior também?

Obrigado

**Comment by barbosarrodrigo1** [comment]
Oi, Ricardo!!
No momento não, mas se inscreva! Pois aí passaremos a ter  você no nosso
banco de dados para vagas posteriores!

Atenciosamente, Rodrigo

Em qui, 31 de out de 2019 às 14:27, Ricardo Guizi <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
