### ISSUE TITLE
[Campinas] Back-End Developer Java na [Venturus]

### ISSUE THREAD

**Issue by AlineFrediani** [backend-br/vagas#1802]
### Quer conhecer  a Venturus?
https://www.venturus.org.br/

**Quem estamos buscando?**

Buscamos desenvolvedores Java que gostem de desenvolvimento de serviços para serem utilizados por aplicativos, seguindo as melhores práticas de segurança, desempenho e manutenabilidade.

**Como será o seu dia a dia?**

Suas responsabilidades serão voltadas para a criação e documentação técnica de serviços em Java que serão utilizados por aplicativos Android e iOS. Projeto com Design Thinking e metodologia de desenvolvimento ágil.

**Competências e experiência necessárias:**

Formação: Ensino Superior Completo na área de TI ou correlacionadas;

Experiência em desenvolvimento Java; JSON e APIs.

Inglês: leitura/escrita avançado e conversação nível intermediário;

**Competências e experiência desejável:**

Conhecimento da ferramenta Jira, GitLab e DevOps com Jenkins.

### **Para se inscrever acesse o link abaixo**
https://jobs.kenoby.com/venturus/job/desenvolvedor-java-back-end-plsr/5db6f00d53eecc24c60ad60d

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
