### ISSUE TITLE
[São Paulo] Android Developer na Ciclic

### ISSUE THREAD

**Issue by ana-sene** [backend-br/vagas#1804]
## Descrição da vaga

Estamos buscando desenvolvedor Android para o nosso time na Vila Olímpia, SP, para atuar com Kotlin.

## Local

São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Plano odontológico (opcional)
- Seguro de vida
- VR 
- VA
- VT (opcional)
- GymPass
- Auxílio creche
- Auxílio Babá
- Plano de previdência (opcional)
- Bônus anual de até 3 salários.

#### Diferenciais

- Horário flexível
- Home office 1 vez por semana
- Day off no aniversário

## Requisitos

- Conhecimento em Kotlin / Java
- Conhecimento em programação orientada a objetos/ Clean Code / SOLID
- Experiência em trabalhos com dados remotos via REST e JSON.
- Experiência com Android SDK / Android Studio
- Git
- Material Design guidelines
- Ter publicado pelo menos 1 app na Google Play.
- Metodologias ágeis.
- Testes automatizados (JUnit, Espresso).

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rhrio@iblueconsulting.com.br com seu CV anexado - enviar no assunto: Vaga Android - SP

## Labels

- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
