### ISSUE TITLE
#VAGA [BANCO BTG PACTUAL] SOFTWARE ENGINEER BACK END PLENO [SÃO PAULO]

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1805]
##Sobre o BTG Pactual
Presente em 9 países, o **BTG Pactual é o maior banco de investimentos da América Latina**, com atuação nos mercados de Investment Banking, Corporate Lending, Sales & Trading, Wealth Management e Asset Management. 

Nosso time é responsável pelos sistemas de trade capture, risco de credito e portais de negociação online. Acreditamos muito em tecnologia e temos certeza que ela protagonizará os novos modelos de negócios do banco. 

Página da vaga: http://byintera.in/21

##Responsabilidades e desafios
- Promover a automatização e otimização de processos e análises;
- Relacionamento próximo com as áreas de negócio e outras equipes de IT do Grupo BTG Pactual;
- Desenvolver algoritmos e modelos estatísticos para alavancar as operações de credito;

##Conhecimento técnico
- 2 Anos de experiência com Java, Python ou .NET
- Ter feito integrações com AWS.
- Inglês avançado.

Página da vaga: http://byintera.in/21

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
