### ISSUE TITLE
[São Paulo] Back-end Developer na [Resource IT]

### ISSUE THREAD

**Issue by RoqueResourceIT** [backend-br/vagas#1807]
Oportunidade para back-end C# .NET Instituição Financeira, Digital. Empresa jovem, dinâmica, só reune os feras de cada tecnologia. e-mails roque.silva@resourceit.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
