### ISSUE TITLE
[Belo Horizonte] Laravel Developer na Ensinio

### ISSUE THREAD

**Issue by guiavila** [backend-br/vagas#1808]
## Descrição da vaga

A Ensinio permite criar seu próprio ambiente de Escola Online com ferramentas avançadas para construção e vendas de cursos online, produtos físicos e digitais. Uma plataforma completa para você ter sua própria escola online, sua própria comunidade e rede social interagindo com seus conteúdos e seu marketplace. Estamos aumentando o nosso time e você fará parte dessa expansão.

Procuramos desenvolvedores especialistas no framework Laravel (PHP) para integrar o time de desenvolvimento do Backend.

## Local

Escritório em Belo Horizonte - MG

## Requisitos

Experiência em Desenvolvimento Web
Conhecimento avançado de Laravel (fundamental)
Conhecimento do "Laravel Nova"
Vue.js (painel do Laravel Nova)

## Contratação

PJ a combinar

## Como se candidatar

Para entrar no time de desenvolvimento da Ensinio, envie seu CV para jobs@ensinio.com com pretensão salarial e seu perfil profissional. Nos conte mais sobre você e o motivo pelo qual você quer esta vaga. Envie sua mensagem com o assunto: "Job - Backend Laravel"

**Comment by guiavila** [comment]
Ainda há 3 vagas para preencher pessoal :)

**Comment by marciowinicius** [comment]
@guiavila se abrir pra remoto da um toque

**Comment by guiavila** [comment]
> @guiavila se abrir pra remoto da um toque

Márcio, manda o email lá para jobs@ensinio.com e a gente se fala :)
