### ISSUE TITLE
[ CAMPINAS/SP REMOTO ] BACK-END Developer na FLOW DIGITAL

### ISSUE THREAD

**Issue by marcofrasson** [backend-br/vagas#1809]
### DESCRIÇÃO DO JOB
O profissional fará parte de uma equipe multidisciplinar, onde todos participam de projetos dos clientes da casa, ajudando e resolvendo problemas, otimizando e melhorando os processos de desenvolvimento.

Carga horária: 4 horas diárias

### LOCAL / FORMATO

- Trabalho remoto

### REQUISITOS OBRIGATÓRIOS
- Atenção em tudo o que você está desenvolvendo;
- PRECISA Conhecer WordPress e WooCommerce muito bem (requisito para a vaga);
- Domínio das linguagens HTML, CSS, JavaScript e da biblioteca jQuery;
- 2 anos de experiência com PHP 5+;
- Conhecimentos em Orientação a Objetos, MVC, APIs;
- Conhecimento em Metodologias Ágeis;
- Banco de dados relacionais (MySQL);
- Versionamento de código (GIT);
- Conhecimentos básicos em Linux;
- Inglês técnico (leitura).

### DESEJÁVEIS:
- Já ter experiência no desenvolvimento de ecommerces;
- Ter agilidade e comprometimento com o resultado final;
- Ser organizado, responsável e capaz de trabalhar em equipe
- Empatia com os projetos e pró-atividade;
- Perfil analítico e detalhista;
- Ser heavy-user de novas tecnologias;
- Ser organizado, responsável e capaz de trabalhar em equipe;
- Vontade inextinguível de aprender;
- Ter a capacidade de aprimorar o último trabalho realizado;
- Sugerir novas e melhores soluções em tudo que inicia;

### CONTRATAÇÃO
- PJ, via contrato entre as partes.
- Carga horária: 4 horas diárias
- Valor/hora a iniciar de R$ 12,00 (dependendo do nível de xp)

### SOBRE A FLOW DIGITAL
Somos uma empresa que alia a tecnologia e criatividade para entregar projetos incríveis.

### COMO SE CANDIDATAR
Você pode mandar um e-mail para contato@goflow.digital com o título: **VAGA DEV FLOW** e nos mostrando se está apto em todos os pontos solicitados acima. Prezamos o seu tempo e o nosso, então por favor envie o contato se realmente tiver interesse.

### Labels

- PJ
- Pleno
- Remoto

**Comment by marcofrasson** [comment]
### DESCRIÇÃO DO JOB
O profissional fará parte de uma equipe multidisciplinar, onde todos participam de projetos dos clientes da casa, ajudando e resolvendo problemas, otimizando e melhorando os processos de desenvolvimento.

Carga horária: 4 horas diárias

### LOCAL / FORMATO

- Trabalho remoto

### REQUISITOS

**Obrigatórios:**

- Atenção em tudo o que você está desenvolvendo;
- PRECISA Conhecer WordPress e WooCommerce muito bem (requisito para a vaga);
- Domínio das linguagens HTML, CSS, JavaScript e da biblioteca jQuery;
- 2 anos de experiência com PHP 5+;
- Conhecimentos em Orientação a Objetos, MVC, APIs;
- Conhecimento em Metodologias Ágeis;
- Banco de dados relacionais (MySQL);
- Versionamento de código (GIT);
- Conhecimentos básicos em Linux;
- Inglês técnico (leitura).

**Desejáveis:**

- Já ter experiência no desenvolvimento de e-commerces;
- Ter agilidade e comprometimento com o resultado final;
- Ser organizado, responsável e capaz de trabalhar em equipe
- Empatia com os projetos e pró-atividade;
- Perfil analítico e detalhista;
- Ser heavy-user de novas tecnologias;
- Ser organizado, responsável e capaz de trabalhar em equipe;
- Vontade inextinguível de aprender;
- Ter a capacidade de aprimorar o último trabalho realizado;
- Sugerir novas e melhores soluções em tudo que inicia;
- 

**CONTRATAÇÃO**

- PJ, via contrato entre as partes.
- Carga horária: 4 horas diárias
- Valor/hora a iniciar de R$ 12,00

### SOBRE A FLOW DIGITAL
Somos uma empresa que alia a tecnologia e criatividade para entregar projetos incríveis.

### COMO SE CANDIDATAR
Você pode mandar um e-mail para contato@goflow.digital com o título: **VAGA DEV FLOW** e nos mostrando se está apto em todos os pontos solicitados acima. Prezamos o seu tempo e o nosso, então por favor envie o contato se realmente tiver interesse.

### Labels
PJ
Pleno
Remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
