### ISSUE TITLE
[São Paulo] Desenvolvedor Web at Wtime 

### ISSUE THREAD

**Issue by AnieliFernanda** [backend-br/vagas#181]
Wtime contrata para atuar em cliente: 

 > # #Desenvolvedor Web

Conhecimentos em (front-end e back-end):
C#, utilizando as tecnologias MVC e WCF.
CSS e Javascript 

 ## Local de trabalho:

Morumbi/SP
 
 ## Modalidade de contratação:

PJ 

### Projeto temporário de 2 meses, podendo ou não ser prorrogado. 

**Interessados enviar currículo com pretensão salarial para anieli.fernanda@wtime.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
