### ISSUE TITLE
[São Paulo] Back-End .NET [Grupo Anima]

### ISSUE THREAD

**Issue by Izabella-vulpi** [backend-br/vagas#1811]
👔 Vaga: Desenvolvedor .NET Sênior
💼 Senioridade: Senior
🏣 Empresa: Grupo Ânima
📍 Localização: São Paulo
👉 Candidatar: http://bit.ly/grupoanima_net
🦊 Quer receber outras vagas? É só acessar https://materiais.vulpi.com.br/enjoythecode

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
