### ISSUE TITLE
[São Paulo] Developer Avocate [TAKE]

### ISSUE THREAD

**Issue by Izabella-vulpi** [backend-br/vagas#1812]
👔 Vaga: Developer Advocate
💼 Senioridade: Pleno
🏣 Empresa: TAKE
📍 Localização: São Paulo/ Belo Horizonte
👉 Candidatar: http://bit.ly/take_advocate
🦊 Envie seu currículo direto para o recrutador: izabella.silva@vulpi.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
