### ISSUE TITLE
[São Paulo] Backend Engineer na Wildlife 

### ISSUE THREAD

**Issue by brunaduartesc** [backend-br/vagas#1814]
**About the company**
Wildlife Studios is one of the leading mobile game developers and publishers in the world. Since 2011, we have released more than 70 titles, reaching billions of people around the globe. We are proud of our origins, and while leveraging everything we've learned so far, we are pushing the gaming industry forward.

**About the Team**
The Backend Team at Wildlife is reinventing itself. It started providing services for the games' online features and has since evolved to provide a platform that leverages the best of our teams when creating, operating and distributing our games. 

We know that the work we do has a high impact on our company's success and in order to achieve that, we work with a broad technology stack and have a mindset of being fully responsible for our systems, from their conception to incident resolution and troubleshooting in production.

We own several services that, combined, serve more than 1 million requests per minute. We know this number will only grow and we're looking for engineers that can help with the challenges of developing backend systems that perform well at large scale.

**About the Role**
Wildlife is searching for software engineers to join our Backend team. We seek engineers with solid programming and systems design knowledge. Since we are always looking for new tools and technologies that better solve our problems, we value professionals that like to learn new things, are autonomous and proactive to bring and implement their ideas.

As a backend engineer, you'll work directly with several teams such as the games' teams, product, marketing, data science, and data engineering to develop world-class platforms that are used in our games' creation, operation, and distribution. Our main goal is to empower and enable each of those teams to do their work faster and better, making our games reach the next billion people. We'll need you to understand our systems flows, identify common demands from different teams, and work in close collaboration both within the team and with different parts of the organization to design secure, resilient systems with great usability and performance.

**More about you**
Empowering teams is key to scaling. We look for engineers that have a history of designing systems and services that enable others to do their best work. You have a keen eye for common features and demands and can build from different requirements and expectations to a common ground.

Metrics focused. We are metrics oriented and our systems have great impact on the performance of our games. You have an analytic mindset and focus on ensuring great visibility to your clients. You aim for top-level system design, guaranteeing the highest availability possible.
High scale and low-latency. You are excited about the challenges brought by high scale and low-latency requirements. You thrive when discussing the architecture and best practices of such systems and have great attention when developing its internals to ensure an efficient and easily maintainable code. 

**What you'll do**
Design, implement, deploy and maintain systems and platform products that will be used in the games' development, operation and distribution.
Identify common demands from clients, design and propose solutions that improve everything from their operation to the end-user experience.
Detect and fix problems in production environment.
Contribute to the best practices of development, reliability, and availability of our systems.
Handle great volumes of data in real-time systems.

**What you'll need**
Bachelor's degree in Computer Science, Computer Engineering or equivalent experience.
Excellent analytical, problem-solving and critical thinking skills.
Solid understanding of computer science concepts (data structures, networking, concurrency, memory management, algorithm analysis, etc).

**Plus**
Experience with Docker and Kubernetes.
Experience with Redis, MongoDB, DynamoDB, Postgres.
Experience solving problems and optimizing the performance of APIs.
Experience developing and maintaining systems with a high volume of requests.
Experience developing systems in the games industry.
Experience developing systems in the ad tech ecosystem.
Experience developing platform products.
3+ years of software development professional experience.

We welcome people from all backgrounds who seek the opportunity to help build the best gaming company, where everyone thrives.

Apply at:
https://boards.greenhouse.io/wildlifestudios/jobs/4447407002

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
