### ISSUE TITLE
[São Paulo] Backend Engineering Manager na Wildlife

### ISSUE THREAD

**Issue by brunaduartesc** [backend-br/vagas#1815]
**About the company**
Wildlife Studios is one of the leading mobile game developers and publishers in the world. Since 2011, we have released more than 70 titles, reaching billions of people around the globe. We are proud of our origins, and while leveraging everything we've learned so far, we are pushing the gaming industry forward

**About the Team**
The Backend Team at Wildlife is reinventing itself. It started providing services for the games' online features and has since evolved to provide a platform that leverages the best of our teams when creating, operating and distributing our games.

We know that the work we do has a high impact on our company's success and in order to achieve that, we work with a broad technology stack and have a mindset of being fully responsible for our systems, from their conception to incident resolution and troubleshooting in production. 

We own several services that, combined, serve more than 1 million requests per minute. We know this number will only grow and we're looking for engineers that can help with the challenges of developing backend systems that perform well at large scale.

**About the Role**
Wildlife is searching for an engineering manager to join our Backend team. On the technical side, you'll need to find bottlenecks and solve performance problems in distributed systems with ease. You'll also make decisions about bigger systems design themes, such as when to build sustainable, high-impact projects and when to ship things quickly and with quality. You'll play a fundamental role in making our games reach the next billion people by guiding and developing highly-skilled engineers and working closely with other managers and leaders to improve our processes and ensure we have a world-class engineering organization.

**More about you**
Team focused. You believe in influencing through developing relationships over-exercising authority. You always look for improving your team's health, for example, by balancing operational responsibilities with development.
Technically skilled. You have deep knowledge about systems design and have built a career focused on studying how to design, maintain and monitor highly scalable systems. You are happy when you contribute to planning and design discussions.
Having the best engineers is key to scaling. We look for leaders that thrive when hiring the best engineers and promoting their growth. You believe in providing continuous, thoughtful feedback and in recognizing the individual strengths and contributions of your team members.

**What you'll do**
On a daily basis:
Participate in and guide the development of systems focusing on your customer, whether they are players or other Wildlife employees
Guarantee the team engineers' happiness and productivity
Attract and retain talent 
On a weekly basis:
Conduct 1:1s with the engineers
Plan team activities and engineers' allocation
Report status to the director (what was delivered in the previous week and what will be delivered next)
On a quarterly basis:
Set the team's goals aligned with the company's OKRs

**What you'll need**
Bachelor's degree in Computer Science, Computer Engineering or equivalent experience.
Excellent analytical, problem-solving and critical thinking skills.
5+ years of software development professional experience.
Experience managing teams of at least 5 people.

**Plus**
Experience developing and maintaining systems with a high volume of requests.
8+ years of software development professional experience.
Experience managing teams with 10+ engineers and being responsible for creating a team from scratch.
Project management experience.
Experience developing systems in the games industry.
Experience developing systems in the ad tech ecosystem.
Experience developing platform products.
Business knowledge about advertising operations.
Business knowledge about the games industry.

We welcome people from all backgrounds who seek the opportunity to help build the best gaming company, where everyone thrives. 

Apply at:
https://boards.greenhouse.io/wildlifestudios/jobs/4462075002

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
