### ISSUE TITLE
[São José dos Campos] DESENVOLVEDOR JAVA [GSW SOFTWARE]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1818]
_**Atuar**_ em grande cliente em São José dos Campos!
Projeto com uma grande equipe atuando com micro serviços e manuais.

**Desenvolvedor** Java

**Experiência:**

•Java 8
•Javascript
•Spring-boot
•Microserviços
•Docker
•PostgreSQL
•NoSQL

**Desejáveis:**
Microserviços e Docker

**Contratação:**
PJ + Benefícios

**Cidade:** São José dos Campos
### **Interessados, por favor enviar cv, pretensão e disponibilidade de início para:
mariana.bompean@gsw.com.br**

**### _Venha fazer parte desta equipe!!_**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
