### ISSUE TITLE
 [São Paulo] Back-End Developer na [Mira Educação]

### ISSUE THREAD

**Issue by MiraEduc** [backend-br/vagas#182]
**Quem Somos:**

A Mira é uma Startup que busca solucionar uma questão básica em todo o mundo: educação. Desenvolvemos ferramentas com o objetivo de facilitar a vida de professores e gestores, envolvendo os responsáveis e garantindo uma melhora no processo educativo dos alunos de modo escalável e com baixo custo.

Somos uma empresa engajada por um propósito maior, fazer a diferença na educação pública do Brasil. Somos inconformados com o presente e queremos construir um futuro diferente.

Se você quer que seu trabalho cause impacto na sociedade e você sinta orgulho disso, seu lugar é aqui.

Queremos inspirar outras pessoas, contribuir positivamente para o futuro de nosso país. Para isso contamos com colaboradores engajados, apaixonados pela nossa causa e motivados pelo impacto social.  

**Um pouco sobre a nossa Cultura:**

- Somos orientados pela experiência de nosso usuário. O problema do nosso usuário é o nosso problema;
- Nosso foco é resultado, contamos com uma equipe altamente capaz e disposta para atingi-lo;
- Estamos sempre em busca de melhorias;
- Estimulamos o “pensar fora da caixa” e valorizamos as boas ideias; 
- Nossa equipe é colaborativa e prestativa;
- Valorizamos as singularidades e respeitamos as diferenças;
- Damos a todos autonomia e liberdade para colocar suas ideias em prática;
- Nossos Miranautas se sentem donos do projeto e realizados a cada entrega;
- Reconhecemos nossos erros, e mais do que isso, estamos sempre abertos a mudança. 
- Aqui tudo é compartilhado, nossos resultados, ideias, dúvidas, gostamos de ouvir a opinião de nosso time, independentemente da posição que ocupe. 

A área de backend da Mira trabalha com APIs Restful, cloud, microsserviços em um ambiente com cultura devops. 

**Como Desenvolvedor (a) Backend os seus maiores desafios serão:**

Estar disposto a aprender com enfoque na qualidade do código;
Trabalhar com testes unitários e queira aprender sobre o negócio;
Trabalho em equipe e contribuição para o crescimento mútuo do time;
Preocupação com o ecossistema de aplicações;
Foco no cliente, no usuário e na nossa missão;     

**O que esperamos de você:**

Experiência com a linguagem Java;
Experiência com APIs Restful;
Experiência com testes integrados e unitários;
Experiência com Cloud computing;
Experiência com a arquitetura de microserviços.  

**Desejável:**

 Contato com a linguagem Kotlin;
 Contato com o framework spring-boot;

 **Benefícios:**

Assistência Médica e Odontológica - 100% custeada pela empresa;
Vale Refeição;
Vale Alimentação ou Combustível;
Vale Cultura;
Gympass;
Auxílio Creche;
PLR – Atrelado a metas;
Desconto com escola de idiomas;
Quick Massage;
Flexíveis: Happy Hour toda sexta, Snacks à vontade, Sala de descanso, Vídeo game, Dresscode e ambiente informal;
Ótima localização, ao lado do metrô Santa Cruz; 

Interessados acessar nossa página de Carreiras e cadastrar o cv na vaga: 
https://jobs.kenoby.com/miraeducacao/job/desenvolvedora-backend-plenoa/5acf6a13e5b41b7832f83447

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
