### ISSUE TITLE
[São José dos Campos] Desenvolvedor Ruby on Rails - Junior [GSW]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1822]
### **Requisitos**
· Conhecimento de Ruby on Rails.
· Conhecimento de PostgreSQL.
· Valorizamos pessoas motivadas, que programem por gosto e que gostem de aprender novas linguagens.
**_O que você vai fazer?_**
· Programação Ruby on Rails: Nossa infraestrutura já consiste de 3 stacks Ruby on Rails, com testes e deploys automatizados.
· Revisar código dos outros desenvolvedores.
· Participar do desenho técnico e implementação de novas soluções.

**Benefícios**
· Horários de trabalho flexíveis.

**_Projeto_**
Tempo indeterminado

**· Contato:** 
Mande um email com seu currículo para mariana.bompean@gsw.com.br
 Links de github/gitlab são muito bem-vindos!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
