### ISSUE TITLE
[SÃO PAULO] Banco BTG Pactual - Software Engineer

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1823]
O maior banco de investimento da América Latina está crescendo ainda mais e precisa de você para fazer parte dessa mudança.

**É uma grande mudança!**  Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir os novos modelos de negócio do Banco. Tudo isso para fornecer a melhor performance dos nossos times dos sistemas de trade capture, risco de credito e portais de negociação online.

Atualmente nós trabalhamos com as linguagens Java, Python, .NET e C#. Estamos nos atualizando então integrações AWS e Metodologias Ageis também fazem parte do trabalho. Essas tecnologias com pessoas de propósito e dispostas é o que a crescer com nós é o que fará a diferença!

A contratação será feita em regime CLT alocado na sede do BTG na Faria Lima.

Página da vaga: http://byintera.in/21

**Comment by juliana-byte** [comment]
Ainda estão precisando? Estão abertos a pessoas de todo o Brasil?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
