### ISSUE TITLE
[São Paulo/Home] Bluelab - Desenvolvedor backend NodeJS

### ISSUE THREAD

**Issue by pblackman** [backend-br/vagas#1825]
**DESCRIÇÃO DA VAGA**

A Bluelab (www.bluelab.com.br) desenvolve bots de texto e voz capazes de interagir com usuários através de diálogos complexos.
Nosso foco é entregar para nossos clientes a melhor experiência de atendimento que a tecnologia pode proporcionar.
Para isso acontecer, desenvolvemos uma plataforma própria de processamento de linguagem natural que está em constante evolução.
Estamos buscando desenvolvedores backend para integrar o time que será responsável pela evolução da nossa plataforma, utilizando tecnologia de ponta e muita criatividade.

**LOCAL**
Escritório, São Paulo - Sumarezinho (Heitor Penteado)

**DIFERENCIAIS**

- Horários flexíveis
- Possibilidade de home-office em alguns dias da semana
- Ambiente de trabalho descontraído
- Evolução salarial acima do mercado

**REQUISITOS OBRIGATÓRIOS**

- Desenvolvedor pleno ou sênior NodeJS
- Inglês fluente
- Microserviços
- Vivencia em metodologias ágeis (Kanban, Scrum, etc.)
- Experiência em API's REST/SOAP
- MongoDB

**REQUISITOS DESEJÁVEIS**

- GraphQL
- Redis
- Conhecimento de ferramentas de CICD
- ELK Stack
- Conhecimento básico em React

**CONTRATAÇÂO**

- PJ a combinar

**COMO SE CANDIDATAR**
Enviar currículo com pretensão salarial para vagas@bluelab.com.br com o assunto **"DESENVOLVEDOR BACKEND"**

**Tags:**
🏢 Flexível
🏢 Presencial
👨 Pleno
👴 Sênior
⚖️ A-Combinar
⚖️ PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
