### ISSUE TITLE
[São José dos Campos] Desenvolvedor Ruby Júnior

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1827]
Projeto startup (Fintech) - _Obs: Desenvolvedor poderá possuir conhecimentos com Python , caso não possua com Ruby._

**Desenvolvedor Ruby on Rails -  São José dos Campos**

**_Requisitos_**
· Conhecimento de Ruby on Rails.
· Conhecimento de PostgreSQL.
· Valorizamos pessoas motivadas, que programem por gosto e que gostem de aprender novas linguagens.
**_O que você vai fazer?_**
· Programação Ruby on Rails: Nossa infraestrutura já consiste de 3 stacks Ruby on Rails, com testes e deploys automatizados.
· Revisar código dos outros desenvolvedores.
· Participar do desenho técnico e implementação de novas soluções.

**Benefícios:**
Á combinar (Horários flexíveis)

**Tipo de contratação**
PJ

**Projeto**
Tempo indeterminado

**Contato:** Mande um e-mail com seu currículo para mariana.bompean@gsw.com.br
Links de github/gitlab são muito bem-vindos!

**Comment by davi-dv** [comment]
@marianabompean aceita remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
