### ISSUE TITLE
[São Paulo] Analista Desenvolvedor .NET na 5A Attiva 

### ISSUE THREAD

**Issue by HeloisaMoraes** [backend-br/vagas#183]
`5A Attiva `
Somos uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação, especialmente na área de desenvolvimento de software.

`O que buscamos no perfil técnico:`
- Sólidos conhecimento .Net em asp.net e C# e com SQL Server;
- Bootstrap, MVC, Gerenciamentos ágeis;
- Postgresql (desejável).
Conhecimentos de soluções Amazon (AWS)
- Profundo conhecimento com análise.

`O que você irá fazer:`
Esse profissional irá atuar em projetos de multiplataformas .NET, PHP, Visual Fox Pro, PostGreSQL, SQL Server, RedShift, Watson (IBM), Amazon, Azure, entre outras novidades de mercado.
Atuando em projetos de segmentos financeiros.

`Contratatação`
PJ ou Cooperado 

`Local de Trabalho`
Paulista - Centro de SP 

`Interessados se candidatarem através do Link:` 
https://5a.selecty.com.br/vaga/1524/vaga-para-desenvolvedor-net-senior-paulista-em-sao-paulo-paulista-sp-brasil

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
