### ISSUE TITLE
[Barueri SP ou disponibilidade para mudança] - Desenvolvedor PHP

### ISSUE THREAD

**Issue by lucaspecheche** [backend-br/vagas#1830]
Localizada em Barueri (Alphaville SP), TradeUp Group é um empresa que visa promover o desenvolvimento profissional, seja você de SP ou de outro estado. Possuímos várias empresas filiadas e juntos construímos um ecossistema que vai de desenvolvimento até RH.

#### Trabalhamos com:
- Grandes operadoras de telefonias como CLARO e TIM;
- Redes de varejo como CEA e Riachuelo;
- Sistema próprio de pagamentos;
- Entre muitos outros projetos.

#### O que você irá fazer?
Desenvolver, testar e executar manutenções nos sistemas, fazendo eventuais correções e criando novos recursos.

#### O que buscamos em você?
- Proatividade;
- Colaboração e integração nas atividades da empresa;
- Capacidade de compreender e questionar requisitos;
- Menor necessidade de mentoria e supervisão no cumprimento das tarefas;
- Experiência como desenvolvedor PHP;
- Liberdade técnica (apresentar/aplicar novas tecnologias);
- Conhecimentos sobre API Rest;
- Desenvolvimento de testes automatizados;
- Padrões PSRs;
- Código Limpo.

#### Algumas tecnologias/ferramentas que trabalhamos:
- Framework Laravel;
- Instâncias e Serviços na AWS;
- CI/CD com Buddy Works e GitLab;
- Alguns serviços/containers em Docker;
- Testes automatizados com PHPUnit;
- Bancos de dados: MySQL, Postgres, MongoDB e ElasticSearch;
- Versionamento Git;

#### O que oferecemos?
- 3 Meses de experiência;
- Remuneração de R$ 2.500,00 à R$ 6.000,00 CLT;
- Jornada de trabalho de 44h semanais;
- Sodexo Refeição – Café da manhã e Almoço na empresa;
- Plano de Saúde e Odontológico após os 3 meses de experiência;
- Vale Transporte ou Vale Auto;
- Incentivo no desenvolvimento profissional com bolsa de estudos de 50% de subsídio + (descontos de 30% nas universidades parceiras);
- Transporte aéreo do seu estado;
- Ferramentas de trabalho (Notebook, Monitor, Teclado..);
- Apartamento próximo a empresa e contas (Água + Gás + Energia + Internet) pela empresa;

#### Como será o processo seletivo?
- Entrevista;
- Será aplicado um teste de conhecimento que consiste em desenvolver um pequeno projeto em Laravel;
- Correção e avaliação do teste;
- Seleção;
- Contratação.

Estou esperando seu currículo/dúvidas: lucas.lima@tradeupgroup.com

Gostou da vaga? Não tem o perfil? Compartilhe!

**Comment by saimonventura** [comment]
Recomendo!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
