### ISSUE TITLE
[Pirituba-SP] Analistas Desenvolvedores Java Pleno em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1831]
Descrição da vaga
Estamos em busca de profissionais com experiência em Java para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento. Profissionais de outras cidades/Estados que tenham disponibilidade de mudança serão muito bem vindos.

Local
Presencial  no bairro de Pirituba-SP. Estações próximas: Trem: Domingo de Morais  + 1 ônibus de 10 min| Metrô: Vila Madalena, + um ônibus cerca de 45 min.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
Java 8, JavaScript/Jquery, Angular JS e Spring.

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Pirituba.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
