### ISSUE TITLE
[São Paulo] Back-end Developer na T4W Tecnologia

### ISSUE THREAD

**Issue by GeracaoTalento** [backend-br/vagas#1834]
Empresa Global de Tecnologia com foco no mercado de Turismo, está contratando Desenvolvedor .NET (Backend), para atuar no desenvolvendo de novas funcionalidades e manutenção da plataforma.

(Obrigatórios): 

- .NET VB.Net e C#, Entity Framework, WCF, WebForms 
- Arquitetura de aplicações cliente/servidor e SOA
- XML
- JSON
- WebApis, SOAP e REST
- MySQL
- Team Foundation Server
 
(Metodologias): 

- Design Patterns, MVC, OO 
- Srcum 

(Desejável): 

- Ter utilizado ferramenta Fiddler e SoapUI
- Experiência com testes de stress

(Diferencial): 

- Ter trabalhado no mercado de turismo 

Contratação CLT + benefícios (VT, VR R$ 715,00 por mês, VA R$ 400,00 por mês, Plano Médico da Allianz). 

Local: Região da Vila Olímpia - SP (próximo à estação de trem).

Interessados ou indicações, favor enviar o CV com a pretensão salarial para o Marcelo no e-mail (marcelo@geracaotalento.com.br).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
