### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na StartSe

### ISSUE THREAD

**Issue by enieber** [backend-br/vagas#1835]
Pessoal, estamos com vagas para dev full stack com foco em js aqui na StartSe.

(Obrigatórios):
 - Conhecimento com nodejs.
 - Conhecimentos em js/html e css
 - Experiência com git
 - Conhecimentos do protocolo HTTP

Desejável
 - Conhecimentos de DevOps na AWS.
 - Conhecimento de PHP

para mais detalhes e se candidatar:

https://www.trampos.co/oportunidades/152897?lc=startse

**Comment by THAYLLER** [comment]
vaga somente presencial?

**Comment by enieber** [comment]
no momento sim

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
