### ISSUE TITLE
[Remoto ou Sorocaba - SP] Back-End Developer na Bitwise

### ISSUE THREAD

**Issue by mendesbarreto** [backend-br/vagas#1837]
## Descrição da vaga

Fala pessoal sou o [Douglas](https://github.com/mendesbarreto) atualmente sou o CTO da Bitwise e estou procurando pessoas capazes de produzir conteúdo Back-End para nossos projetos, no momento não procuro por conhecimento em tecnologias especificas como NodeJs, .NET ou Java , se você é desenvolvedor é Back e é fera em alguma tecnologia que está sendo utilizada na atualidade mande seu CV.

## Local

Remoto ou Escritório, Sorocaba - Campolim

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em alguma framework de desenvolvimento de backend como: 
 1. NodeJS
 1. .NET 
 1. Hybernete
 1. Closure
 1. ETc...
   
- JavaScript
- RESTful services ou GraphQL
- NPM ou yarn (para gerenciamente de pacotes/bibliotecas javascript)
- Repositórios: GIT (Hub/Lab/Flow);
- Saber criar testes unitários
- OOP ou Functional Programming
- AWS, Heroku ou Azure

**Desejáveis:**
- Banco de dados (relacional e/ou não relacional)
- ElasticSearch (como noções de performance);
- Desenvolvimento Ágil

**Diferenciais:**
- projetos opensource

## Contratação
- CLT
- PJ

## Nossa empresa

A Bitwise é uma comunidade dedicada e apaixonada por soluções tecnológicas e nosso objetivo é revolucionar o design e a criação de software. 

Nossa missão é ajudar nossos clientes a melhorar suas operações de mercado e desempenho com uma transição suave e rápido retorno do investimento, para alcançar estabilidade a longo prazo. Para isso, trabalhamos duro para capacitar nossas equipes e reforçar uma cultura com valores ágeis.

## Como se candidatar

Por favor envie um email para estevao@bitwise.ltda com seu CV anexado - enviar no assunto: Back-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
