### ISSUE TITLE
[SÃO PAULO] Back-End Developer na Cora - NOVA Startup Fintech

### ISSUE THREAD

**Issue by ViniciusRodrigues26** [backend-br/vagas#1838]
### Descrição da Vaga

A Cora está nascendo e precisa de você para construir um banco digital disruptivo e completo! 

É tudo do zero! Estamos escolhendo as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão impulsionar o crescimento de pequenas e médias empresas do nosso país. 

Não procuramos uma stack específica, buscamos pessoas de todo o Brasil com propósito e dispostas a crescer exponencialmente. Serão bem vindos conhecimentos em infraestrutura, clean code e boas práticas de programação.

É preciso ter bastante experiência e estar disposto a colocar a mão na massa. A perspectiva é que o(a) Back-End Developer cresça junto com a empresa, construa o time de experts e seja uma liderança no futuro.

### Local

WeWork Faria Lima - São Paulo

### Benefícios

Assistência Médica
Assistência Odontológica
VR
Vale Alimentação
Gympass
Netflix
Spotify

**Diferenciais**

- Remuneração competitiva
- Política de horário flexível
- Trabalhar com autonomia e testar novas tecnologias e metodologias
- Criar um Produto do zero sem restrições técnicas
- Ser parte de um time especialista extremamente motivado

### Requisitos

**Obrigatórios:**
- Nivel Sênior (5 a 7 anos de experiência como Back-End);

**Desejáveis:**
- Conhecimento aprofundado em ao menos uma linguagem e framework;
- Conhecimentos básicos em ferramentas de infraestrutura; 
- Padrões de arquitetura e Design Patterns;
- Clean Code e boas práticas de desenvolvimento de software.

**Diferenciais:**
- Ter participado de outros fintechs ou startups
- Domínio das linguagens e frameworks Java, Kotlin ou Go

### Contratação

Em regime CLT e presencial

### Empresa

O Banco Cora é uma nova fintech que está surgindo com o objetivo de melhorar a vida do micro e pequeno empreendedor. O grande objetivo é que, até 2030, o trabalho da Cora possa aumentar o PIB do Brasil em 10% através do crescimento desses empreendedores. 

A Cora foi fundada pelos criadores do Moip (vendido para o Wirecard por 160 milhões) e por trás dela está o grupo 3G Capital, investidora de marcas gigantes, como iFood, Ambev, Stone, Burguer King, Kraft Heinz e Lojas Americanas.

### Como se Candidatar

Candidate-se através de http://byintera.in/fintechcorabackend ou pode falar comigo através do linkedin https://www.linkedin.com/in/viníciusrodrigues/

### Tempo médio de Feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
Nossos processos são rápidos e eficientes para os candidatos

### Labels

- Alocado
- CLT
- Sênior

**Comment by luizadpassos** [comment]
Precisa residir em São Paulo?

Qual a carga horária?

**Comment by andre-reis93** [comment]
Alguma outra linguagem é aceita além de Java, Kotlin ou Go?

**Comment by ViniciusRodriguesIntera** [comment]
> Precisa residir em São Paulo?
> Qual a carga horária?

Sim, a vaga é presencial, sob o regime CLT. A carga horária é de 40h semanais, com política de flexibilidade de horários.

**Comment by ViniciusRodriguesIntera** [comment]
> Alguma outra linguagem é aceita além de Java, Kotlin ou Go?

Sim, também buscamos a linguagem C, mas as linguagens principais são essas três mesmo: Java, Kotlin e Go.

**Comment by mariamaron** [comment]
Qual seria a faixa remuneratória da vaga?

**Comment by ViniciusRodrigues26** [comment]
A remuneração será negociada durante o processo de seleção, dependendo do perfil do candidato, mas pode chegar aos R$13000 + benefícios no valor de $2000.

**Comment by pradocomp** [comment]
Poxa vocês não trabalham com tipos de contratos PJ?! CLT possui muitos descontos.
