### ISSUE TITLE
[Remoto] Desenvolvedor(a) Back-end Python Senior

### ISSUE THREAD

**Issue by viniarck** [backend-br/vagas#1839]
**Empresa**

A Órama foi criada em 2011 por profissionais experientes do mercado financeiro, foi uma das pioneiras a oferecer investimento digital no Brasil. Além disso, foi premiada pela Amazon Web Services como uma das empresas mais inovadoras em serviços financeiros. Presente em todo o país, com uma estrutura 100% online, também está comprometida com a entrega do melhor serviço para que o brasileiro possa investir de forma consciente e transparente.

**Requisitos**

- Python.
- REST APIs e conhecimento em Django, Flask ou Falcon.
- SQL e ORMs.
- Experiência com microserviços.
- Capacidade de se adaptar rapidamente a um ambiente de produção.
- Capacidade de compreensão de problemas complexos.

**Pontos extras para a sua aplicação caso tiver experiência com:**

- Desenvolvimento de software para o mercado financeiro.
- Familiaridade de utilizar soluçoes de cloud AWS/GCP e efetuar o deployment.
- Migração de Python 2 para Python 3.

**Metodologia de Trabalho**

- Agile.
- Code Review.
- 40 horas semanais – Trabalhe focado e trabalhe 40 horas.
- Reuniões minimalistas.

**Forma de contratação**

- CLT ou PJ conforme a preferência do candidato(a)

Envie e-mail com o subject [Python 2019/2 - Senior] para vinicius.arcanjo@orama.com.br

**Comment by gbbocchini** [comment]
Bom dia!

Há possibilidade de remoto para a vaga?

Obrigado!

**Comment by Mdslino** [comment]
> Bom dia!
> 
> Há possibilidade de remoto para a vaga?
> 
> Obrigado!

Sim, inclusive está no título da vaga.

**Comment by gbbocchini** [comment]
lol, desculpa! Enviarei!
