### ISSUE TITLE
[Brasília] Back-End na Startup [Jazida.com]

### ISSUE THREAD

**Issue by tvaamorim** [backend-br/vagas#184]
Vaga para Back-End Developer www.Jazida.com - Vencedor Startup Brasilia 2015.

Atua com plataforma de geoespacialização com API Google Maps no segmento de mineração/exploração mineral. Modelo SaaS e clientes do porte de Votorantim, Vale e Rio Tinto. 
Projeto validado por grandes empresas e em busca do próximo passo... crescimento da base de usuários pagantes. 

Seguem os skills desejados:  
* NodeJS: express, socket.io 
* Experiência com banco de dados
* Conhecimento básio de linux
* Experiência com desenvolvimento GIS
* Experiência prévia em Back-End

Escritório maneiro, horário flexível, ambiente sem formalidade, hierarquia plana, localizado na área central de BSB (colado na rodoviária/metro). 

Mande seu CV com pretensão salarial para o email vagas@jazida.com

labels: nodejs, pj, junior, pleno, presencial, JavaScript

**Comment by giovannicruz97** [comment]
Permite home-office ?

**Comment by tvaamorim** [comment]
@giovannicruz97 O default é Presencial, mas permitimos alguns dias de Home-office
você é de onde?

**Comment by giovannicruz97** [comment]
Eu sou de Taubaté, SP.
________________________________
De: Thiago Amorim <notifications@github.com>
Enviado: segunda-feira, 30 de abril de 2018 00:42
Para: backend-br/vagas
Cc: Giovanni Cruz; Mention
Assunto: Re: [backend-br/vagas] [Brasília] Back-End na Startup [Jazida.com] (#184)


@giovannicruz97<https://github.com/giovannicruz97> O default é Presencial, mas permitimos alguns dias de Home-office
você é de onde?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
