### ISSUE TITLE
[São Paulo - SP] Tech Lead na Estudar com Você

### ISSUE THREAD

**Issue by beatrizabreu27** [backend-br/vagas#1841]
## Tech Lead

Conhecimentos: RoR (2 anos de experiência), AWS, conhecimento em infraestrutura e front-end.

## Benefícios

-Salário: R$ 10.000 (negociável)
-(PJ | Presencial flexível | 44h semanais)
-Férias remuneradas
-Possibilidade de ganhar participação societária
-Aviso prévio

## Responsabilidades:

No Back-end:
Manter nosso sistema atual em boas condições 
Propor, analisar requisitos, implementar, testar e deployar novas soluções
Avaliar e corrigir bugs reportados pela equipe
Garantir que o sistema seja escalável e que esteja sempre disponível
Manter o sistema atualizado e corrigir vulnerabilidades de segurança e performance
Pesquisar, definir e seguir as melhores práticas de desenvolvimento e operação
Todo mundo é um pouquinho devops! Nós também cuidamos da nossa infra!

Quanto à gestão:
Gerenciar equipe de tecnologia
Garantir que estamos entregando resultados úteis e de forma saudável
Manter nosso ambiente de trabalho bom para os membros do time

## Requisitos:
Ter experiência como desenvolvedor(a) Back-End ou Full-Stack
Proficiência em Rails
Ter um padrão de qualidade elevado para tudo que faz
Capacidade de aprender coisas novas

## Labels

- Alocado
- PJ
- Pleno
- Flexível
- Sênior

## Incrições: http://byintera.in/48

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
