### ISSUE TITLE
[Faria Lima-SP] Programadores Back end Node.js Pleno e Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1842]
Descrição da vaga
Estamos em busca de profissionais com experiência com back end Node.js para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial na Av. Faria Lima- altura da estação de trem Cidade Jardim- São Paulo.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
Node.js, EcmaScript 6, Promisse, Async Await, REST, Oracle, git flow
Plus: Testes Unitários, Testes Integrados, containers, CI/CD, Jenkins.

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Node.js

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
