### ISSUE TITLE
[São Paulo, SP] Pessoa desenvolvedora Full-Stack na Orbia.ag

### ISSUE THREAD

**Issue by mathnogueira** [backend-br/vagas#1843]
## Sobre a Orbia

Somos uma empresa que já nasce como a líder digital do agronegócio brasileiro sendo a Joint Venture entre Bayer Crop Science (líder no mercado agrícola) e a Bravium (líder no mercado de tecnologias go-to market).
Com mais de 140 mil agricultores em nossa base de clientes, nossa meta é nos tornarmos líderes globais na transformação digital do agronegócio.
 
- Promover a transformação digital no agronegócio
- Criar a maior plataforma de comércio digital do agronegócio
- Promover uma nova forma do produtor rural negociar
- Ajudar a construir uma empresa que já nasce disruptiva
 
Aqui esperamos que cada colaborador haja como um empreendedor e que sua contribuição para o negócio seja pautada em entrega de valor e não só em responsabilidades cotidianas. Sua carreira é o seu negócio e aqui queremos fazer isso valer.

### Notícias sobre a Orbia

[Bayer lança o marketplace Orbia [StartAgro]](http://www.startagro.agr.br/bayer-lanca-o-marketplace-orbia-e-um-novo-programa-de-fidelidade/)

[Parceria entre Bayer e Bravium, Orbia, chega ao mercado em novembro [Revista Globo Rural]](https://revistagloborural.globo.com/Noticias/Empresas-e-Negocios/noticia/2019/10/parceria-entre-bayer-e-bravium-orbia-chega-ao-mercado-em-novembro.html)

[Bayer lança marketplace de insumos agriculas [Época Negócios]](https://epocanegocios.globo.com/Empresa/noticia/2019/10/bayer-lanca-marketplace-de-insumos-agricolas-e-programa-de-fidelidade-para-produtores.html)

## Benefícios
- Vale refeição de $34,00 por dia
- Plano de saúde e odontológico sem coparticipação
- Participação nos lucros
- Vale transporte sem desconto em folha
- Happy hour quinzenal
- Frutas todos os dias
- Horário flexível
- No dress code

## O que você vai fazer
- Desenvolver soluções para melhorar a forma que o produtor rural interage com o restante do mercado agro
- Trabalhar em conjunto com um time multidisciplinar para garantir a qualidade do produto
- Desenvolver testes automatizados para garantir o funcionamento da solução
- Participar na melhoria contínua do dia a dia da empresa

### Obrigatório
- Forte conhecimento em orientação a objetos
- Prezar por boas práticas em desenvolvimento de software
- Conhecimento em desenvolvimento de testes automatizados
- Conhecimento em banco de dados relacionais / não relacionais
- Conhecimentos em metodologias ágeis
- Experiência com ferramentas de controle de versão (Git)

### Para se destacar
- Gostar de estudar novas tecnologias
- Conhecimentos em AWS
- Conhecimentos em Infraestrutura como código (Terraform)
- Experiência com fluxos de CI/CD
- Vivência em code review
- Experiência com Spring Boot
- Conhecimento em desenvolvimento front-end (ES6, React, SCSS)
- Conhecimento em desenvolvimento móvel (React Native)

### A pessoa ideal deve

- Ser adaptável a mudanças
- Prezar pela qualidade do produto
- Contribuir com ~~piadas ruins~~ o clima descontraído da empresa

## Tecnologias utilizadas

Hoje, na Orbia, utlizamos as seguintes tecnologias:

- Kotlin
- Spring Boot
- React
- Terraform
- Amazon AWS
- Docker
- Java
- PostgreSQL
- Linux
- Git

## Local
Berrini, Região Sul de São Paulo

## Inscrições
Temos vagas para todos os níveis de senioridade. Para se inscrever, acesse o link https://orbia.abler.com.br/vagas/desenvolvedor-pleno-753943

*PS: Ignorar a URL do link. A vaga não é restrita ao nível pleno*

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
