### ISSUE TITLE
[CAMPINAS/SP REMOTO] FullStack Developer (PHP/WordPress) na CRIAH

### ISSUE THREAD

**Issue by scorsoni** [backend-br/vagas#1844]
## Local: ##
Trabalho Remoto  - [Campinas - São Paulo]

## Desejáveis: ##
- Já ter experiência no desenvolvimento de sites e ecommerces (WordPress/WooCommerce);
- Desenvolvimento e manutenção de aplicações web;
- Realizar a manutenção e criação de novas funcionalidades nos temas/plugins desenvolvidos;
- Ter agilidade e comprometimento com o resultado final;
- Empatia com os projetos e pró-atividade;
- Perfil analítico e detalhista;
- Desenvolvimento de funcionalidades no Front-End e Back-End;
- Sugerir novas e melhores soluções em tudo que inicia;
- Horário disponível para CALLS/Reuniões com a equipe.
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- Criação de plugins/tema do zero.
- Desenvolver e sustentar integrações;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Desenvolvimento e integração com APIs REST;
- Ter a capacidade de aprimorar o último trabalho realizado;

## Contratação: ##
PJ
Via Contrato
Por demanda

**Valor/hora: R$ 40,00 a R$ 60,00 (para manutenção em projetos já existentes de acordo com demanda)**

**Valor/hora para projetos fechados: a combinar**

## Como se candidatar: ##
Por favor envie um email para **william@criah.com.br** com seu **CV anexado + portfólio** - enviar no assunto: **FullStack Developer - Criah**

## Labels ##
PJ
Pleno
Remoto
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
