### ISSUE TITLE
[Home Office] Fullstack Developer na WA Project - Node, React e React Native

### ISSUE THREAD

**Issue by gustavowaproject** [backend-br/vagas#1845]
Estamos com algumas vagas em aberto para integrar ao nosso super time.

Descrição da empresa:
Desenvolvemos aplicativos e softwares para empresas. Nossa foco é na entrega.

Atividades e Responsabilidades:
- Desenvolvimento de projetos sob demanda para nossos clientes, utilizando tecnologias web e mobile. Implementação de novas features e manutenção.
- Compartilhar conhecimento e estar disposto a ajudar o time.

Requisitos:
- Experiência com as tecnologias: NodeJs, React, React Native, Typescript, Docker, HTML, CSS, Rest, NPM/Yarn, banco de dados SQL e GIT.

Metodologias utilizadas: 
Scrum e KanBan.

Diferenciais: 
- MongoDB, RxJs e Testes.
- Capacidade analítica para resolução de problemas.
- Comprometimento e ótima comunicação.

Para se candidatar, envie seu currículo para vagas@waproject.com.br

**Comment by danielsidev** [comment]
Boa noite!
Essa vaga é CLT ou PJ?
http://danielsiqueira.net

**Comment by gustavowaproject** [comment]
Boa noite;

A vaga é PJ.

Att.

Gustavo Fernandez
gustavo@waproject.com.br
(11) 2589-1237
(11) 98765-1111
https://waproject.com.br <https://www.waproject.com.br/>


Em 7 de novembro de 2019 às 22:13:05, Daniel Siqueira (
notifications@github.com) escreveu:

Boa noite!
Essa vaga é CLT ou PJ?
http://danielsiqueira.net

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/backend-br/vagas/issues/1845?email_source=notifications&email_token=AIKGSBQBIV7GDRYWL2LJWNDQSS4KBA5CNFSM4JJV7UZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDOMIIY#issuecomment-551339043>,
or unsubscribe

**Comment by danielsidev** [comment]
Ok. 
Estou buscando uma vaga CLT.
Obrigado!

**Comment by mateusmangueira** [comment]
Boa tarde,

Essa oportunidade de emprego aceita trabalho remoto?

[]s

Mateus Mangueira

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
