### ISSUE TITLE
[São Paulo] Back-End Developer [Particle41]

### ISSUE THREAD

**Issue by Izabella-vulpi** [backend-br/vagas#1846]
Hi everyone!

Particle41 is hiring!
They have a lot of opportunities for you!
If you love remote work, have a DevOps mindset and enjoy working in a diverse team, this job is for you!

Location : São Paulo
Job type: Full-time / Remote work
Full-stack Developer: https://lnkd.in/eppJMee
Front-End Developer: https://lnkd.in/efqAz4E
Back-End Developer: https://lnkd.in/ecQfNJE

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
