### ISSUE TITLE
[Zona Leste - SP] Arquiteto de Software e Soluções no Sesc

### ISSUE THREAD

**Issue by beatrizabreu27** [backend-br/vagas#1847]
## Conhecimentos: 
- modelagem e desenvolvimento de API;
- processos de DevOps (CI/CD);
- nuvem pública (Microsoft Azure), com certificação técnica em Microsoft Azure e/ou AWS (Solutions Architect);
- banco de dados relacional e não relacional (NoSQL);
- projetos de migração para nuvem pública e definição de arquiteturas modernas.
Além disso, experiência com liderança técnica de equipes ou desenvolvimento de soluções desacopladas utilizando novos frameworks de mercado e arquitetura baseada em microserviços e como arquiteto de soluções com foco em serviços e tecnologias em nuvem pública.

## Responsabilidades
- Documentar requisitos e definir desenho de arquitetura de sistemas para novas soluções ou documentar soluções existentes com o objetivo de criar um mapa de arquitetura corporativa.
- Definir arquiteturas modernas utilizando tecnologias de integração em ambientes de nuvem pública e novos modelos de desenvolvimento baseado em microserviços e de baixo nível de acoplamento, utilizando conceitos de API Management e arquitetura serverless.
- Fomentar, disseminar e/ou conceber práticas, modelos, padrões e princípios de arquitetura de Tecnologia da Informação e garantir alinhamento das soluções corporativas com o negócio.
- Monitorar o mercado para identificar tecnologias e parceiros de valor para o negócio, realizar e conduzir provas de conceito e testes para assegurar a viabilidade de adoção de novas tecnologias.
- Montar soluções desacopladas e que permitam reuso.
Apoiar o desenvolvimento de sistemas, contribuindo com documentos para embasar o trabalho interno e de terceiros, além de capacitar a equipe em novos padrões de arquitetura de software e de desenvolvimento de software seguro.

## Benefícios

Salário: R$12.500,00
Vale Transporte, 
Assistencia Médica
Seguro de Vida
Refeição subsidiada com refeitório no local
Plano de previdência privada
Cooperativa de crédito 
Reembolso de educação infantil para as funcionárias que possuam filhos(as) de 0(zero) a 06 anos de idade.

## Requisitos:
Graduação ou pós-graduação na área de exatas.

## Labels

- Alocado
- CLT
- Sênior

## Incrições: http://byintera.in/49

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
