### ISSUE TITLE
[SÃO PAULO] Dev. Python Sr [Lendico Brasil]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#1848]
Buscamos pessoas para integrar o time de desenvolvimento com boa visão de arquitetura de sistemas e construção de API's REST (atualmente microsserviços com python e flask) para nos ajudar a desenvolver a melhor e maior plataforma de empréstimos pessoais do país.

O que esperamos de quem se candidata:
Goste de programar, se preocupe com excelência técnica e boas práticas de programação;
Ser capaz de colaborar com o time quanto às melhores práticas de desenvolvimento web do mercado;
Ser responsável pelo desenvolvimento backend das novas funcionalidades do produto;
Visão sistêmica, você entende o que faz, porque faz e qual impacto seu trabalho tem no negócio;
Capacidade de trabalhar em equipe, em um ambiente colaborativo (pareamento, feedback rápido, melhoria contínua);
Familiaridade com as tecnologias WEB como: Python (framework Flask), Mysql, Git e testes automatizados.
Ser capaz de propor otimizações de performance;
Vivência em métodos ágeis de desenvolvimento.

Fintech em rápido crescimento, com um ambiente descontraído, flexível e diverso.

Alocado - PJ

Interessados encaminhar CV para aline.navarro@keepsimple.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
