### ISSUE TITLE
SysAdmin especialista em Automação para a RAAD Solutions

### ISSUE THREAD

**Issue by fabiolsrodrigues** [backend-br/vagas#185]
__Job description__
---
**_Administrador de Sistemas MS/Windows_** que possua excelentes conhecimentos em:  

Instalação, configuração de domínio, MS/Active Directory (configuração e gerência), Microsoft Hyper-V (instalação, configuração, gerência, criação/manutenção de VMs), MS/Exchange (instalação, configuração e gerência), Suporte a infraestrutura Azure, suporte a infraestrutura Amazon AWS (será um plus), domínio/conhecimentos em Linux/Unix será um plus.  
É fundamental ter fortes conhecimentos de Programação em Scripts (principalmente Powershell, Microsoft Windows Scripting Host (WSH) ) . Será um plus conhecimento em Python, PERL ou AutoIt

---
__OU__ 

---

**_Administrador de Sistemas Unix/Linux_** que possua excelentes conhecimentos em:  

Instalação, configuração ( com BIND é um plus); LDAP ou MS/Active Directory (configuração e gerência), VMWare ou Citrix Xenserver e/ou Microsoft Hyper-V (instalação, configuração, gerência, criação/manutenção de VMs), MS/Exchange (instalação, configuração e gerência), Suporte a infraestrutura Azure e/ou suporte a infraestrutura Amazon AWS será um plus, domínio/conhecimentos em Linux/Unix será um plus.  
É fundamental ter fortes conhecimentos de Programação em Scripts (principalmente Python, PERL, Ruby and Shells (Bash, Korn, SED/AWK, etc. ) conhecimento em Powershell será um plus 

---  
EM AMBOS OS CASOS SERÁ UM PLUS: 
  
Ter conhecimentos de Bancos de Dados (MySQL, MariaDB, MS/SQL Server, CassandraDB, etc), ter conhecimentos de JAVA e/ou C# e servidores de aplicação (Apache Tomcat, IBM Websphere, RedHat JBOSS, etc). 

**_CV_** to: contact@raad.solutions

Para maiores detalhes sobre a RAAD Solutions veja:
https://www.linkedin.com/company/raad-solutions-corporation/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
