### ISSUE TITLE
[Curitiba- PR] Programador .NET Pleno ou Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1850]
Descrição da vaga
Estamos em busca de profissionais com experiência com .NET para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial em Curitiba- PR- Cidade Industrial- profissionais de outras cidades/Estados que tenham disponibilidade de mudança serão bem vindos.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
C, #HTML, JavaScript, JQuery, Bootstrap, Visual Studio, Linux, PostgreSQL, ASPNET, .Net Core.

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga .NET Curitiba.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
