### ISSUE TITLE
[SÃO PAULO - PAULISTA] - DESENVOLVEDOR BACKEND  [GSW]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#1852]
**"Empresa de tecnologia da informação, engenharia e ciência de dados, atualmente focada em desenvolvimento de soluções para o mercado de crédito"**

_**Backend Developer**_

**Requisitos**
NodeJS (Express and asynchronous APIs);
Java and the most common frameworks (Spring and Spring Boot, Hibernate, Jersey, etc...)
Kafka, the topic concept and ability to create clients in NodeJS and Java;
AWS or other cloud platforms;
SQL (on Postgre) or on Hive;
JSON and REST integration;

**Inglês:**
Avançado

**Desejável:**
Lambda architecture;
Go;
Scala or Spark;

**Benefícios:**
Salário competitivo - PJ
Flexibilidade de horário
Cursos online

**_Como se candidatar_**
Por favor envie um email para mariana.bompean@gsw.com.br com seu CV anexado e pretensão

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
