### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Android na Guiabolso

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1853]
A Guiabolso está crescendo e precisa de você para construir novos produtos.

**É tudo do início!** Estamos desenvolvendo um **novo produto** e para isso buscamos a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para fornecer a melhor performance e experiência aos nossos clientes, reduzindo aproximadamente R$250 milhões em gastos dos usuários por ano.

Atualmente nós trabalhamos com Kotlin, bastante AWS e ferramentas de CI/CD. Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos faz crescer exponencialmente. Serão bem vindos também conhecimentos em Programação Reativa, Jenkins, Gradle, TDD,  e outras boas práticas de programação.

A contratação será feita em regime CLT com horário flexível e o trabalho de forma presencial. Estamos na Pinheiros, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://byintera.in/vemserguiabolso

##Labels
Pleno
Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
