### ISSUE TITLE
[Belo Horizonte - MG] Analista de Sistemas

### ISSUE THREAD

**Issue by recrutamentopris** [backend-br/vagas#1854]
NÓS ESTAMOS PROCURANDO PESSOAS QUE:
• Valorizam assumir responsabilidades e trabalhar com autonomia;
• Se preocupam com a qualidade das entregas;
• Se interessam por aprimorar processos/rotinas;
• Gostam de aprender e ensinar;
• Que possuam bons conhecimentos sobre:
  - Linguagem de programação C#;
  - .NET;
  - HTML, CSS, Javascript;
  - Arquitetura MVC;
  - Programação orientada a objeto;
  - Lógica de programação avançada;
  - Banco de dados SQL;

NO DIA A DIA VOCÊ SERÁ RESPONSÁVEL POR:
• Trabalhar com o desenvolvimento de sistemas web utilizando .NET/C#;
• Contato com clientes para validar a implantação de recursos e funcionalidades;
• Melhorar e automatizar processos e rotinas;
• Participar de círculos de decisão e estratégia.
Entre outros!

COISAS QUE VAMOS AMAR VER EM VOCÊ:
• Boa capacidade analítica e lógica;
• Atenção e organização no trabalho;
• Inglês intermediário;
• Bons conhecimentos sobre .NET Core.

BENEFÍCIOS:
• Horário flexível;
• Plano de saúde;
• Vale-alimentação e vale-refeição;
• Vale transporte;
• Plano de carreira;
• Curso de meditação subsidiado;
• Massagem na empresa;
• Mentoria e acompanhamento de carreira;
• Oportunidade de atuar em outras áreas;
• 10% do tempo semanal dedicado a aperfeiçoamento;
• No dress code.

Ficou interessado? Inscreva-se em <https://pris.com.br/recrutamento.php> até o dia 17/11!
Se tiver qualquer dúvida, é só mandar no nosso chat que também se encontra no endereço acima.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
