### ISSUE TITLE
[SÃO PAULO] Backend Developer JAVA/Go na Nuveo (Inteligência Artificial)

### ISSUE THREAD

**Issue by gizeledelboni** [backend-br/vagas#1856]

**Comment by gizeledelboni** [comment]
## Descrição da Vaga
​
Somos focados em desenvolver soluções de software para automação de processos e serviços usando Inteligência Artificial (Visão Computacional e Natural Language Processing) para empresas e organizações que trabalham conosco.
​
## Conhecimentos mais importantes
​
* Go ou interesse em aprender Go e conhecer linguagens correlatas (Java etc)
* Implementação de apps em REST, GraphQL ou gRPC
* Teste unitários (na sua forma mais simples)
* Ferramentas ou Serviços de Continuous Delivery como:
  * TravisCI
  * Jenkins
  * CircleCI
  * Drone.io ou similares
* Containers:
  * Docker
* Banco de dados:
  * PostgreSQL ← Preferencialmente
  * MariaDB
  * MySQL
  
## Conhecimentos desejáveis
* Comunicação Assíncrona com:
  * AMQP (RabbitMQ ou outros)
  * Google Pub/Sub
  * Kafka ou similares
* SOLID
* Orquestração com Kubernetes
* Test-Driven Development (TDD)
* Domain Driven Design (DDD)
* Trunk-Based Development (TBD)
* Google Cloud ou AWS
* Conceitos em Cloud-Native Application
* Trace Distribuído
* Monitoramento
  
## Cidades para contratação
* São Paulo - SP
​
## Tipo de contratação
* PJ
​
## Se interessou?
Mande email com seu CV atualizado para talentos@nuveo.ai

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
