### ISSUE TITLE
[SP/ São Paulo] - Fullstack Developer na Estudar com Você

### ISSUE THREAD

**Issue by VitorChaves21** [backend-br/vagas#1858]
## Descrição da vaga

Buscamos um(a) desenvolvedor(a) Full-Stack ou Back-End de nível Pleno ou Sênior para nos ajudar a criar produtos que vão encantar nossos clientes e nos ajudar a transformar a experiência de estudo de universitários.

A posição é de Tech Lead, mas o trabalho é mão na massa, desenvolvendo funcionalidades que vão gerar muito valor para nossos usuários! Além disso, você será responsável por todo o processo de desenvolvimento, desde a discussão de tasks até os testes e a entrega de novas soluções. Não menos importante é a função coordenar/orientar e ajudar a evoluir o time de tech, que hoje conta com um desenvolvedor full-stack junior.
## Local

Rua Tabapuã, no Itaim Bibi, em São Paulo – SP.

## Benefícios:
- Faixa salarial: entre R$8.000 e R$12.000,00/ Regime PJ de contratação
- Férias remuneradas
- Possibilidade de ganhar participação societária
- Aviso prévio

## Requisitos:
**Essencial:**
- Ter experiência como desenvolvedor(a) Back-End ou Full-Stack
- Proficiência em Rails
- Ter um padrão de qualidade elevado para tudo que faz
- Capacidade de aprender coisas novas

**No Back-end:**
- Manter nosso sistema atual em boas condições
- Propor, analisar requisitos, implementar, testar e deployar novas soluções
- Avaliar e corrigir bugs reportados pela equipe
- Garantir que o sistema seja escalável e que esteja sempre disponível
- Manter o sistema atualizado e corrigir vulnerabilidades de segurança e performance
- Pesquisar, definir e seguir as melhores práticas de desenvolvimento e operação
- Todo mundo é um pouquinho devops! Nós também cuidamos da nossa infra!

**Quanto à gestão:**
- Gerenciar equipe de tecnologia
- Garantir que estamos entregando resultados úteis e de forma saudável
- Manter nosso ambiente de trabalho bom para os membros do timecom usuário e com o Back-End.

## Contratação

- PJ | Presencial flexível | 44h semanais

## Nossa empresa

Hoje o estudo de milhões de universitários é estressante e ineficiente. Muitos desistem de seus cursos, reprovam as matérias e se frustram com a faculdade. Com conteúdos excepcionais e uma plataforma intuitiva, estamos comprometidos a tornar o estudo fácil e eficiente.

Hoje contamos com um time de 15 pessoas, atingimos 40 mil alunos e estamos inseridos em faculdades em que mais da metade dos alunos são clientes (Poli USP, Insper e FGV). 

Isso só é possível porque oferecemos um produto que nossos usuários realmente amam.

## Como se candidatar

- Candidate-se através de http://byintera.in/48

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
Nossos processos são rápidos e eficientes para os candidatos

## Labels

- Alocado
- PJ 
- Sênior/Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
