### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na Orbia - Marketplace da Bayer

### ISSUE THREAD

**Issue by fabio-leao-byintera** [backend-br/vagas#1859]
A Orbia está iniciando seus trabalhos e precisa de você para construir o maior marketplace do agrotech do Brasileiro!

É tudo do início! A Orbia é um marketplace da Bayer(essa mesma que você está pensando) e a Bravium (líder no mercado de tecnologias go-to market). Eles estão na fase inicial desse projeto que tem potencial de R$70 Bilhões. Só aqui no Brasil, a base de dados deles conta com 140 mil produtores, responsáveis por 65% das áreas plantadas do Brasil.

Buscamos um desenvolvedor Full Stack com experiências em Java ou .Net, desenvolvimento de testes automatizados, uso de banco de dados relacionais e não relacionais.

Além das tecnologias modernas em termos de performance e otimização do código, a Orbia é para quem não se acomoda e gosta de encarar desafios diários, quem busca empreender e iniciar esse projeto multinacional, colocando sua marca e deixando seu legado.

A contratação será feita em regime CLT com trabalho de forma presencial flexível. Estamos no Brooklin, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://byintera.in/orbiafullstackgit

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
