### ISSUE TITLE
[São Paulo] Analista Desenvolvedor .NET sr na VENTRON

### ISSUE THREAD

**Issue by FrancieleRosa** [backend-br/vagas#186]
Ventron
Somos uma consultoria, focada em alocação assistida e soluções de software.
Fazemos parte do Grupo Cadmus, com 20 anos no mercado de TI.

O que buscamos no perfil técnico:
Sólidos conhecimento.Net
C#
DDD
SOLID
Design patterns
API Rest
Oracle ou SQL
Git
Scrum

Desejável
Service Fabric
Mongo Db
VSTS / Octopus
Salesforce

Contratatação
CLT + Benefícios

Local de Trabalho
Avenida Faria Lima - Centro de SP
Alocação em Cliente

Interessados, favor enviar currículos para: franciele.rosa@ventron.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
