### ISSUE TITLE
[GOIÂNIA/GO || REMOTO] Desenvolvedor Pleno FullStack NodeJS/VueJS [iRancho]

### ISSUE THREAD

**Issue by marcelomf** [backend-br/vagas#1861]
```
$ curl -s -X GET "https://api-dev.irancho.com.br/api/vagas" | json | egrep -i -A 12 'pleno.+nodejs|nodejs.+pleno'
    "titulo": "Desenvolvedor Pleno FullStack NodeJS/VueJS",
    "emailContato": "marcelo[Em]irancho[Pontooo]com[Pontooo]br",
    "habilidades": [
      "Vivencia de pelo menos 2 anos com NodeJS, VueJS, MySQL e GIT",
      "Entendimento das alterações do ECMAScript 6, 7, 8, 9 e 10",
      "Entendimento de callbacks, promessas e async/await",
      "Conhecer padrões de projeto",
      "Conhecer RESTful(GET/POST/PUT/DELETE), STATUS CODE(2xx, 4xx, 5xx), swagger",
      "Desejável que conheça GraphQL e microserviços",
      "Desejável que se faça o desafio: https://github.com/iranchobr/desafio"
    ],
    "codigo": "DEVP1"
  },
# Saiba mais em: https://api-dev.irancho.com.br/api-docs
```

**Comment by kivervinicius** [comment]
Excelente criatividade!

**Comment by THAYLLER** [comment]
uma duvida para desenvolver o teste tem algum prazo?

**Comment by marcelomf** [comment]
Oi @THAYLLER não tem prazo e não é obrigatório, mas sim desejável. Obrigado pelo interesse!

**Comment by tiago123456789** [comment]
Para o desafio poderia usar React no lugar de Vue?

**Comment by gutorc92** [comment]
Seria possível substituir o teste por projetos pessoais?

**Comment by marcelomf** [comment]
@tiago123456789 o ideal seria vuejs pois é a tecnologia que utilizamos... mas pode fazer em react sim, com certeza iremos considerar! Obrigado pelo interesse.

@gutorc92 É possível sim, mas gostaríamos de ter acesso a códigos, obrigado!

**Comment by gutorc92** [comment]
@marcelomf como posso te mostrar esses projetos?

**Comment by marcelomf** [comment]
@gutorc92 me mande um email marcelo [Em] irancho [Pooonto] com [ponto] br, se puder compartilhar algum código, seria o ideal. Se não, podemos marcar uma call para semana que vem, obrigado pelo interesse! []s

**Comment by THAYLLER** [comment]
vaga ainda em aberto?

**Comment by marcelomf** [comment]
@THAYLLER sim meu caro, iremos encerrar esta semana, obrigado.

**Comment by marcelomf** [comment]
Processo seletivo encerrado, muito obrigado pela participação de todos!
[]s
