### ISSUE TITLE
[São Paulo] Desenvolvedor Java Jr. na Docket 

### ISSUE THREAD

**Issue by carolinaleaodocket** [backend-br/vagas#1862]
**Somos uma startup revolucionária.**
Nós desenvolvemos uma plataforma que proporciona uma experiência end-to-end (do começo ao fim) sobre busca, gestão e análise de documentos cartorários e forenses. Significa que criamos um sistema inovador que faz com que o processo de formalização de documentos, que sempre foi longo e lento, torne-se um processo ágil, integrado e produtivo.

Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que se enquadrem na nossa cultura. \o/

 Estamos em busca de um Desenvolvedor Jr que seja apaixonado por desenvolvimento Java e que tenha ambição de crescer junto com a Docket. Precisamos que você tenha experiência de 1 ano na área e que queira aplicar sua arte no mundo real da programação. Você terá a oportunidade de mostrar tudo o que sabe e nós ajudaremos a transformar sua trajetória de carreira.

Acha que somos compatíveis? Venha e #junteseaotime. =)

**RESPONSABILIDADES E ATRIBUIÇÕES**
Na Docket você irá:
-Trabalhar no desenvolvimento (código/testes) com múltiplos projetos
-Criar estratégias para transformar requisitos de negócio, funcionais e não funcionais, em código modular e reutilizável;
-Responsável por aplicar as boas práticas de engenharia de software e padrões de projeto;
-Implementar e manter aplicações;
-Responsável pela manutenção de códigos/testes de sistemas;

**REQUISITOS E QUALIFICAÇÕES**
 Você vai se encaixar bem se:
-Possuir formação em Ciências da Computação, Sistemas de Informação ou áreas relacionadas à tecnologia da informação.
-Bons conhecimentos em Java, SQL, HTML, CSS e JavaScript
-Conhecimentos em framework como Spring ou Hibernate
-Ter experiência de no mínimo 1 ano em desenvolvimento Java

**INFORMAÇÕES ADICIONAIS**
 Benefícios:
- Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida
- Ambiente descontraído, criativo e oportunidade de crescimento acelerado. =)
- Local: Pinheiros (ao lado da estação de metrô Pinheiros)
- Horário: 44 horas semanais

Se candidate através da nossa página de carreiras:
https://docket.gupy.io/jobs/75633?jobBoardSource=gupy_public_page

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
