### ISSUE TITLE
[São Paulo] Back-End Java Developer na PSM Company

### ISSUE THREAD

**Issue by fwfreitas** [backend-br/vagas#1863]
Venha fazer parte do nosso time!

Estamos em busca de um profissional apaixonado por tecnologia e que busca desenvolvimento profissional.

A oportunidade é bem bacana sendo para atuar no mercado de seguros na região do Vila Olímpia.

Então se você conhece de Java, Spring e banco de dados, tenho certeza que a oportunidade é para você.

Trabalhamos com CLT Full + benefícios.

Ficou interessado, entra em contato através do e-mail francisco.freitas@psmcompany.com.br.

Vamos conversar!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
