### ISSUE TITLE
[PR/Curitiba] Desenvolvedor NodeJs

### ISSUE THREAD

**Issue by AutomTech** [backend-br/vagas#1864]
• NodeJs 
• REST 
• MySQL 
• MongoDB 
• AWS 
• Docker 
• Git 
• Linux (terminal - commands and tools) 

Diferencial: 
• Serverless;
• Message Brokers (RabbitMQ/AWS SQS);

Desejável Backgroud de infra.

Contratação PJ. 

![NodeJs](https://user-images.githubusercontent.com/57018306/68605469-37b81e80-048b-11ea-801a-cd77683a2674.png)

Ficou interessado? 
Envie seu CV para trabalheconosco@automtech.com.br com o no assunto: Dev. NodeJs

**Comment by raloliver** [comment]
Aceita remoto?

**Comment by AutomTech** [comment]
Essa posição é contratação direta pelo cliente e há necessidade do presencial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
