### ISSUE TITLE
[São Paulo/SP] Desenvolvedor back-end junior

### ISSUE THREAD

**Issue by beatrizabreu27** [backend-br/vagas#1867]
## Desenvolvedor back-end

# Conhecimentos básicos:
- Ruby on Rails 
- Unix
- HTML
- Lógica de programação

# Diferenciais:
-  SQL 
-  HTML5
- em algum framework de javascript
- conhecer um pouco de AWS e Google cloud

## Responsabilidades

- Implementar as melhores práticas de código e design patterns, orientação a objetos e otimização de performance;
- Desenvolver usando a nossa infra-estrutura;
- Aplicar código limpo, testável e de fácil manutenção;
- Contribuir com o processo de desenvolvimento de software;
- Atualizar features em ambiente de homologação;
- Contribuir nas discussões técnicas sobre os desafios encontrados;
- Seguir padrão de qualidade garantindo consistência do código;
- Compartilhar conhecimentos com a empresa e a comunidade.

## Localização
São Paulo - Rua Estados Unidos 1570, Jardins, São Paulo (localização fixa no Distrito Co working)

## Salário
 R$3000,00 - PJ 

## Labels

- Alocado
- PJ
- Júnior

## Incrições: https://intera.talent-hacking.com/b2b-stack/desenvolvedor-back-end-ruby-on-rails/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
