### ISSUE TITLE
[Remoto] PHP/Laravel Pleno na Gallica

### ISSUE THREAD

**Issue by marciowinicius** [backend-br/vagas#1868]
**Descrição da vaga**
O profissional irá trabalhar diretamente na reformulação de um produto baseado em um que já temos pronto e está no mercado (Estamos chamando de v2). Basicamente é uma plataforma de gerenciamento de investimentos.

Com quem você irá trabalhar:
Irá fazer parte de uma equipe multidisciplinar, que dominam várias tecnologias e também gostam de bastantes desafios.

Em geral, os times aqui têm uma pessoa tech leader, que orienta e mentora as demais pessoas em questões técnicas; uma pessoa team leader, que é responsável por acompanhar entregas e direcionar o desenvolvimento de carreira das pessoas; e um(a) PM, que passa as demandas para desenvolvimento conforme a estratégia macro dos produtos. Todas essas pessoas têm background técnico!

Além disso, utilizamos métodos ágeis como Scrum, Kanban e XP. Somos adeptos a TDD (test-driven development).

**Local**
- Remoto (Trabalhe de onde quiser)

**Requisitos:**

PHP 7.1+;
Orientação a objetos;
Testes unitários;
API's rest;
Banco de dados Relacionais(MySQL,Postgres) e Não relacionais(MongoDB)
Integração com API's de terceiros;
Redis;
Docker;
DevOps;

**Contratação**
PJ a combinar

**Como se candidatar**
Email para vagas@gallica.io incluindo pretensão salarial e currículo com o assunto "Desenvolvedor PHP/Laravel Pleno"

**Comment by andreluizlunelli** [comment]
Essa vaga ainda está em aberto? @marciowinicius

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
