### ISSUE TITLE
[São Paulo] Software Engineer Elixir, Ruby, Go - SumUp

### ISSUE THREAD

**Issue by Fernanda239** [backend-br/vagas#1869]
## **Your impact at SumUp**

As part of our vision to become a truly global tech organization, we have started to build out local, autonomous, cross-functional squads that can take an aspect of our product and perfect it from concept to execution with full autonomously. **As a Software Engineer, you will be a part of one of our new squads in Brazil, which means that you will have the freedom to experiment with new things and apply your ideas in our products.**

### **Your role and responsibilities**

- Participate in API design and implementation for both internal APIs and those exposed to our third-party integrators.
- Provide thoughtful and comprehensive documentation and testing for your features before shipping them.
- Design, implement, and iteratively improve new services and systems.
- Collaborate with other Software, QA and DevOps engineers to ensure smooth deployment, continual operation and support for quality software.
- Coach and mentor other engineers to increase their abilities and productivity.
- Actively provide code review feedback to other software engineers, considering both style and implementation.
- Interact daily with our different areas bringing technical perspective for each new feature, but also taking account the business value added on it.

### **Requirements**

- Experience with at least one of the following languages: **Elixir/Erlang, Ruby, Javascript, Java/Scala, GoLang, Python**;
- Experience with Git;
- Experience with SQL (PostgreSQL);
- Solid OOP and Functional Programming skills;
- Solid debugging, optimisation and problem-solving skills;
- Self-motivated, proactive and engaged attitude towards projects;
- Experience with Agile Methodologies (Scrum or Kanban).

## **Get in on all the awesome at SumUp**

- Empowerment to do great things and the opportunity to leave your mark in a high-growth organization;
- An **amazing team and work environment**, that works with passion and purpose to achieve incredible results;
- **Quarterly performance evaluation**, where we give you tools to design and create your own career path;
- Nice **flexible working hours** - you make your own schedule and have the freedom to align with the team if you want to work from home;
- **Benefits:** transport voucher or parking space, meal voucher, Gympass, healthcare insurance (dental optional), life insurance;
- Convenient location in the heart of Pinheiros (São Paulo), close to the central station and main avenues;
- [**Amazing office**](https://officesnapshots.com/2019/01/18/sum-up-offices-sao-paulo/) with all the structure to do amazing work and to have fun (games, video games, ping pong table, slide, and foods. Lots of food!);
- Everyone has a voice: **weekly meetings with the whole company**. Transparency is key for us!

## **About SumUp**

**We believe in the everyday hero. Those who have the courage to follow their passion, those who have the strength and determination to realize their dreams.**

We are 1,400+ SumUpers in 12 offices around the globe **- 700+ in Brazil only** - and we are here to empower small merchants and help them thrive.

We believe that anyone should be able to start their own business. [We provide small businesses with powerful, easy-to-use card readers and awesome customer support](https://www.whow.com.br/startups/sumup-cresceu-14-000-ao-apostar-no-pequeno-empresario/), so merchants can run their business and engage with their customers. We do so with genuine care for our merchants and love for our products. By taking the hassle out of getting paid, we enable small business owners to focus on what they love to do.

_SumUp is an Equal Employment Opportunity employer that proudly pursues and hires a diverse workforce. SumUp does not make hiring or employment decisions on the basis of race, color, religion or religious belief, ethnic or national origin, nationality, sex, gender, gender identity, sexual orientation, disability, age or any other basis protected by applicable laws or prohibited by Company Policy. SumUp also strives for a healthy and safe workplace and strictly prohibits harassment of any kind._

### **How To Apply** 

Click here (**https://grnh.se/f5e309512**) and lets talk =)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
