### ISSUE TITLE
[São Paulo] Analista Desenvolvedor .NET na VENTRON

### ISSUE THREAD

**Issue by FrancieleRosa** [backend-br/vagas#187]
Ventron
Somos uma consultoria, focada em alocação assistida e soluções de software.
Fazemos parte do Grupo Cadmus, com 20 anos no mercado de TI.

O que buscamos no perfil técnico:
Requisitos:
DDD, TDD
Angular 1 e X
.NetCore
Entity Framework
Injeção de Dependência
NodeJS
Resful
Web Api
Bootstrap
Git
VSTS

Desejável:
Swagger
Pug
Azure
Docker

Contratatação
PJ por tempo indeterminado

Local de Trabalho
Barra Funda -  SP
Alocação em Cliente

Interessados, favor enviar currículos para: franciele.rosa@ventron.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
