### ISSUE TITLE
[RIO DE JANEIRO] DevOps/SysAdmin - MeuPatrocinio

### ISSUE THREAD

**Issue by Thais2019-mp** [backend-br/vagas#1870]
Venha fazer parte da maior rede social sugar do Brasil realizando  o sonho de todas as Sugar Babies e Sugar Daddies desse país com a melhor proposta que todos eles podem ter!! 
E para fazer acontecer, buscamos pessoas que acreditem no nosso propósito, que tenham paixão por desafios e estejam dispostas a fazer nossos usuários sorrir. Para assim somar à nossa equipe multidisciplinar de talentos incríveis que nos inspira todos os dias.

Título da vaga: **DevOps/SysAdmin**

Nossa missão é evoluir e melhorar a experiência de nossos usuários nas plataformas Web e Android. Dentro nossa gama de tecnologias, trabalhamos com:

- PHP
- Javascript/Typescript
- Docker
- Terraform
- Packer
- Jenkins
- NewRelic
- Grande stack na AWS
- Entre várias outras!!

Faixa salarial:
- Salário 8 á 13k
- Contratação: PJ

Você é?
- Pró-ativo, valorizamos sua vontade de fazer sempre o melhor;
- Joga bem em grupo;
- Flexível; Extremamente Organizado;
- Espirito "Hacker" (Move Fast and Break Things);
- Apaixonado pelo o que faz;

O que buscamos em você?
- Experiência na criação de arquitetura cloud na AWS (com 5+ anos experiência);
- Conhecimento em Plataformas como estrutra em AWS RDS , S3 , Cloudwatch, SNS, CloudFront, SQS, ECS, entre outros.
- Como todo bom SysAdmin, precisamos daquele mestre em Linux, que consegue se dar bem com qualquer distro!
- Uma pessoa carinhosa e atenciosa com Monitoramento, Logs, etc;
- Nossa API’s são servidas todas em Docker, então esperamos que seja um mago com containers;
- CI/CD usando Jenkins, toda nossa entrega e testes estáticos são automatizados, precisamos de alguém pra manter essa engrenagem funcionando e deixando-a mais bonita 
- Configuração de DNS e proxy utilizando o Cloudflare e Route53;
- Inglês intermediário para conversação e avançado para ler (entender) e escrever;
- Um pouco Software de Gerenciamento de Projetos JIRA.

O que aumentam as suas chances?
- Contribuições Open Source;
- Certificação AWS;
- Interesse por qualidade de código;
- Conhecimentos em MySQL e performance de queries;
- Conhecimentos com Redis, Elasticsearch;
- Conhecimentos com ferramentas de monitoramento como NewRelic e PMM ou outras;
- Metodologias ágeis (Scrum, Kanban);
- Experiencia com Microserviços;

 
Como iremos lhe agradar  
- Todos equipamentos necessários (Software & Hardware)  
-  Café infinito  ​ 
- Ar condicionado BOMBANDO!!   
- Dresscode: seja você!   
- Escritório divertido que estimula a criatividade e autonomia   
- Pacote salarial competitivo
 
No MeuPatrocinio acreditamos que é a sua diferença que nos conecta com milhares de Sugar Babies e Sugar Daddies todos os dias, e aqui você tem a liberdade de ser quem você é. Para nossas vagas não fazemos distinção de raça, nacionalidade, identidade de gênero, necessidades especiais e demais especificidades.

Achou que essa é essa a oportunidade que tem o match perfeito com você? Vem fazer parte da nossa equipe!

Entrar em contato: thais.guapyassu[@]ipmedia.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
