### ISSUE TITLE
[Recife] Vaga para Desenvolvedor Backend .NET na App7 Sistemas

### ISSUE THREAD

**Issue by elvislourenco** [backend-br/vagas#1871]
A App7 Sistemas está procurando pessoas talentosas, inovadoras, comprometidas, inteligentes e que queiram ajudar no desenvolvimento da nossa plataforma de esportes.

**Responsabilidades e atribuições esperadas:** 
• Manutenção e desenvolvimento de sistemas baseados em Asp.Net e .Net Core MVC;
• Implementação e testes em ambientes de Cloud; 
• Desenvolvimento de softwares na arquitetura REST Full e Asp.Net Forms. 

**Requisitos**:
• .NET Core e Frameowrk .Net (4+), linguagem c#; 
• MS SQL Server; 
• GitHub; 
• C#; 
• WCF (Windows Communication Foundation);
• Inglês é desejável
• Conhecimento de infra-estrutura em Cloud (GCP, AWS, Azure) desejável;
• Conhecimento em Docker e Kubernetes é desejável;

**Local:**
Recife – Boa Viagem (Av.Domingos Ferreira – Empres. Business Beach)

**Benefícios:**
- Vale transporte
- Vale refeição
- Ajuda de custo para cursos/worshops/treinamentos 

**Contratação:**
- PJ

**Enviar CV com pretensão salarial para elvis@app7sistemas.com**

**Comment by elvislourenco** [comment]
up!

**Comment by elvislourenco** [comment]
Bora minha gente do Recife!

**Comment by guibranco** [comment]
Boa tarde,

A falta de interesse provavelmente é pelo modelo de contratação e a baixa remuneração. Esse valor seria justo para um CLT Junior. Pense em melhorar essa proposta para receber candidatos realmente com conhecimento e interessados em mover o projeto para frente!
