### ISSUE TITLE
[SÃO PAULO] Software Engineer Back-End no banco digital Cora - NOVA Startup Fintech

### ISSUE THREAD

**Issue by ViniciusRodrigues26** [backend-br/vagas#1872]
A Cora está nascendo e precisa de você para construir um banco digital disruptivo e completo!

A empresa foi fundada pelos criadores do Moip (concorrente do PayPal, vendido para o Wirecard por 165 milhões) e por trás dela está a Stone e Jorge Paulo Lemann, do grupo 3G Capital, investidora de marcas gigantes, como iFood e Ambev.

É tudo do zero! A Cora está escolhendo as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Ela busca oferecer uma solução voltada para os micro e pequenos empreendedores do nosso país. O grande objetivo é que, até 2030, o trabalho da Cora possa aumentar o PIB do Brasil em 30% através do crescimento desses empreendedores!

Para isso, estão buscando profissionais fora da curva, de todo o Brasil, com propósito e dispostas a crescer exponencialmente! É preciso ter bastante experiência e estar disposto a colocar a mão na massa. Serão bem vindos conhecimentos em infraestrutura, clean code e boas práticas de programação! A perspectiva é que o(a) Back-End Developer cresça junto com a empresa, construa o time de experts e seja uma liderança no futuro!

A contratação possui remuneração competitiva, benefícios atrativos e será feita em regime CLT, para atuar de forma presencial em São Paulo, com autonomia, flexibilidade e sendo parte de um time extremamente motivado, com senso de donos e personalidade!

Para mais informações, acesse a página da vaga http://byintera.in/corabackend2019 ou pode falar diretamente comigo através do linkedin https://www.linkedin.com/in/viníciusrodrigues/ para entender melhor o desafio.

É uma oportunidade fantástica para quem quer construir algo gigante em pouco tempo e dar sua identidade à solução!

**Comment by mariamaron** [comment]
Onde fica a sede? Há possibilidade de trabalho remoto?

**Comment by andre-reis93** [comment]
Quais são as linguagens buscadas?

**Comment by ViniciusRodrigues26** [comment]
> Onde fica a sede? Há possibilidade de trabalho remoto?

Olá, Maria! Tudo bem? A sede fica na Rua Gomes de Carvalho, 1629 - Vila Olímpia, São Paulo. Na verdade, a Cora acabou de mudar para esse escritório novo, com capacidade para 100 colaboradores. Hoje eles tem por volta de 40 funcionários, mas a perspectiva é que até o final do ano esse número alcance 80. Em relação ao trabalho remoto, hoje ele não é possível. No momento estamos em busca de talentos para trabalhar presencialmente mesmo. Nessa primeira etapa é importante para a Cora esse contato mais direto, já que o processo é de construção coletiva. No entanto, há flexibilidade nos horários e a possibilidade de fazer home office durante a semana.

**Comment by ViniciusRodrigues26** [comment]
> Quais são as linguagens buscadas?

Olá, André! Tudo certinho, cara? Não buscamos nenhuma linguagem específica, o importante é ter conhecimento aprofundado em ao menos uma linguagem orienta a objeto (Java, C#, Ruby, Python, Kotlin, Golang, Smalltalk etc.)

**Comment by luizadpassos** [comment]
Quantos funcionários tem atualmente na equipe de desenvolvimento da Cora?

**Comment by cviniciusdr** [comment]
Seria legal incentivar os funcionários atuais para que eles avaliassem a empresa em alguma plataforma, como o Glassdoor. 
Assim as pessoas que estão buscando uma vaga saberiam se combinam com a cultura do lugar.

**Comment by ViniciusRodrigues26** [comment]
> Quantos funcionários tem atualmente na equipe de desenvolvimento da Cora?

Olá, Luiza! Tudo bem? Atualmente a equipe de desenvolvimento conta com 10 desenvolvedores no total (back/front/full stack) e a perspectiva é de contratação de, ao menos, mais 5 back-ends. Estamos montando uma equipe bem sênior de software engineers para começar a desenvolvedor a solução e lançar ela no início do próximo ano já em uma versão bem completa.

**Comment by ViniciusRodrigues26** [comment]
> Seria legal incentivar os funcionários atuais para que eles avaliassem a empresa em alguma plataforma, como o Glassdoor.
> Assim as pessoas que estão buscando uma vaga saberiam se combinam com a cultura do lugar.

Olá, Carlos Vinícius! Tudo certinho? Cara, obrigado pelo feedback! Pode deixar que passarei para a Cora. Muito obrigado! 

Caso tenha alguma dúvida sobre a oportunidade, fala comigo e te explico mais sobre a Cora!
