### ISSUE TITLE
[São Paulo] Back-End Developer na Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#1873]
Estamos a procura de profissional para atuar como Desenvovedor PHP Back End Sênior.

##Local:
Escritório - São Paulo, Real Parque.

##Benefícios:
VR 30,00
VT
AM
AO

##Requisitos:
Requisitos:
•	Superior completo em Ciências da Computação, TI ou áreas correlatas; 
•	Experiência com PHP 5, utilizando SYMFONY2 ou superior, desenvolvimento de Procedures views, banco SQL SERVER, controle de versão GIT, com criação de branchs e tags;
•	Vivência com Linux (Debian, Ubuntu), tecnologias BaaS e Armazenamento em Nuvem;
•	Será considerado como diferencial, o profissional com experiência no setor de Saúde, Privado ou Público, desenvolvimento de aplicativos móveis híbridos: Xamarin, Ionic, Phonegap ou Nativos: Android (Java ou Kotlin), IOS (Swift), arquitetura de software para desenvolvimento móvel, MQTT broker.
•	3 anos de experiência  para Sênior
•	Imprescindível  conhecimento em Symphony

##Como se candidatar:
Por gentileza encaminhar para o e-mail talento@radarprofissional.com.br com CV atualizado - enviar no assunto: Desenvolvedor PHP

##LABELS
CLT
PJ
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
