### ISSUE TITLE
[Curitiba - PR] Consultor MM, Pl/Sr [VAGA ENCERRADA]

### ISSUE THREAD

**Issue by AutomTech** [backend-br/vagas#1876]
**### Requisitos obrigatórios:**
- Disponibilidade para viagens 
- Experiência comprovada em projetos SAP GRC Inbound - Mensageria 
- Conhecimento em Processos de MM de entrada de Nota Fiscal:
  Configuração e Processo de entrada de mercadoria
  Configuração e Processo de entrada Nota Fiscal de Serviço
  Configuração e Processo de entrada de CTe
  Configuração de localização Brasil para entradas de Produtos, de diversos cenários específicos (compra com entrega futura, consignação, subcontratação, brindes, etc.)
 
**### Diferenciais:**
Conhecimento ABAP • Conhecimento ao menos teórico da mensageria Cloud da SAP • Conhecimento de SD/Mensageria Outbound • Experiência com definição (especificação) de soluções para entrada de Mercadoria e Serviço.

### **Enviar CV com pretensão salarial para trabalheconosco@automtech.com.br**

![MM](https://user-images.githubusercontent.com/57018306/68684051-95f60780-0546-11ea-8bf2-a5f3bdf937ee.png)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
