### ISSUE TITLE
[Campinas-SP] - Desenvolvedor(a) Java Back-End Pl - Venturus 

### ISSUE THREAD

**Issue by MarcelaBortolatto** [backend-br/vagas#1877]
## Sobre nós:

Desenvolvemos o futuro há mais de 20 anos, levando a transformação digital aos nossos clientes e parceiros por meio de soluções exclusivas em hardware e software.
Criamos o que você não encontra pronto.
Um lugar guiado pelo espírito curioso, inquieto, desbravador e corajoso, de profissionais apaixonados por desafios. Onde a tecnologia atua a serviço da inovação, criando do zero, soluções que transformam o negócio de empresas e claro o dia a dia das pessoas.
Criamos o que você não encontra pronto.

## Descrição da vaga

Quem estamos buscando?

Buscamos desenvolvedores Java que gostem de desenvolvimento de serviços para serem utilizados por aplicativos, seguindo as melhores práticas de segurança, desempenho e manutenabilidade.

Como será o seu dia a dia?

Suas responsabilidades serão voltadas para a criação e documentação técnica de serviços em Java que serão utilizados por aplicativos Android e iOS. Projeto com Design Thinking e metodologia de desenvolvimento ágil.

**Competências e experiência necessárias:**

Formação: Ensino Superior Completo na área de TI ou correlacionadas;

Experiência em desenvolvimento Java; JSON e APIs.

Inglês: leitura/escrita avançado e conversação nível intermediário;

Competências e experiência desejável:

Conhecimento da ferramenta Jira, GitLab e DevOps com Jenkins.

## Posição
Pleno

## Tipo de contratação
Presencial, CLT

## Benefícios
Convênio Médico e Odontológico
Seguro de Vida
Vale refeição e Alimentação
Horário de trabalho flexível
Home Office (1x na semana) 
Previdência Privada
Bolsa de estudos 
Liberação de horas para mestrado e doutorado
Reembolso em certificações técnicas
Entre outros...
Também contamos com um ambiente descontraído, sem dress code e sempre com atividades voltadas a qualidade de vida. 

## Como aplicar
Clique neste link para se inscrever: http://vnt.ai/99oxfo 

## Contato
Saiba mais sobre o Venturus acessando nosso site e acompanhando nossas redes sociais. 

https://www.venturus.org.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
