### ISSUE TITLE
[FLORIANOPOLIS] Dev. Python [SOFTPLAN]

### ISSUE THREAD

**Issue by sanmartim** [backend-br/vagas#1879]
Buscamos pessoas para integrar o time de desenvolvimento com boa visão de arquitetura de sistemas e construção de API's REST (atualmente microsserviços com python e flask).

O que esperamos de quem se candidata:
Goste de programar, se preocupe com excelência técnica e boas práticas de programação;
Ser capaz de colaborar com o time quanto às melhores práticas de desenvolvimento web do mercado;
Ser responsável pelo desenvolvimento backend das novas funcionalidades do produto;
Visão sistêmica, você entende o que faz, porque faz e qual impacto seu trabalho tem no negócio;
Capacidade de trabalhar em equipe, em um ambiente colaborativo (pareamento, feedback rápido, melhoria contínua);
Familiaridade com as tecnologias WEB como: Python (framework Flask), Postgres, Git e testes automatizados.
Ser capaz de propor otimizações de performance;
Vivência em métodos ágeis de desenvolvimento.

contato: michael.ferreira@softplan.com.br

**Comment by gbbocchini** [comment]
Olá, Bom dia!

Há possibilidade de trabalho remoto para a vaga?

Obrigado

**Comment by analuizasampaio** [comment]
Boa tarde, Michael!

Essa vaga é pra Jr, Pl ou Sr?
É CLT ou PJ?

muito obrigada.


Em qua., 13 de nov. de 2019 às 08:36, Michael San Martim <
notifications@github.com> escreveu:

**Comment by sanmartim** [comment]
CLT, temos vagas  Pl e Sr

**Comment by juliaguiar** [comment]
aceita remoto?

**Comment by leogregianin** [comment]
Dá uma dor no ❤️ quando escreve Python errado 😄

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
