### ISSUE TITLE
[São Paulo] Desenvolvedor Back-End PHP no clubegreens.com

### ISSUE THREAD

**Issue by willianwelbert** [backend-br/vagas#188]
Startup voltada para o e-commerce de produtos orgânicos e naturais
loja.clubegreens.com

Vaga **presencial**:
Estamos pertinho do metrô Santa Cruz na zona sul

- Para JUNIOR (não tenha receio de enviar seu CV, a gente quer te conhecer e gosta muito de ensinar) ; 
- PJ (com possibilidade de se tornar CLT)
- PHP; - CSS; - Javascript; - PWA; 

Diferenciais: Wordpress\WooCommerce; VTEX; PWA; React Native;

Ambiente descontraído e amigável :)

Tags: PJ, Junior, Pleno, Alocado

me manda seu CV em: willian@clubegreens.com

**Comment by DanicoSantos** [comment]
Enviado!

**Comment by hilderjares** [comment]
possibilidades de 100% homeoffice ?
