### ISSUE TITLE
[São Paulo] Pessoa Desenvolvedora FullStack na Orbia

### ISSUE THREAD

**Issue by carolgdsouza** [backend-br/vagas#1882]
### A Orbia está nascendo e precisa de você para se tornar a líder global na transformação digital do agronegócio!

**Joint Venture entre Bayer Crop Science (líder no mercado agrícola) e a Bravium (líder no mercado de tecnologias go-to market), a Orbia está apenas no início, mas já é a líder digital do agronegócio brasileiro, com uma base de mais de 140 mil agricultores.**

Para alcançar seus objetivos e continuar a (r)evolução do agronegócio, a Orbia trabalha com programação orientada a objetos, sempre prezando pelas boas práticas no desenvolvimento de software. O conhecimento em desenvolvimento de testes automatizados, banco de dados relacionais e não relacionais e em metodologias ágeis também é bem-vindo e diferencial!

A contratação será feita em regime CLT, presencial flexível no Brooklin, São Paulo. Para mais informações como remuneração, benefícios e o próprio formulário de inscrição, acesse a página da vaga: http://byintera.in/4x.

LABELS
Senior/Pleno
Fullstack
Java
.NET
CLT
Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
