### ISSUE TITLE
[Ribeirão Preto] Desenvolvedor(a) Java - Sênior no Beblue

### ISSUE THREAD

**Issue by Gabrielle1012** [backend-br/vagas#1887]
### Descrição da vaga

Buscamos um profissional que irá:

- Projetar e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;
- Participar e colaborar na arquitetura das soluções focando em requisitos não funcionais como disponibilidade, escalabilidade e performance;
- Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc.;
- Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes;
- Servir como líder de projeto ou líder técnico durante a decorrer de projetos;
- Apoiar desenvolvedores menos experientes a atingir seus objetivos respeitando sempre os requisitos de engenharia, arquitetura e de qualidade.

### Local

Ribeirão Preto/SP

### Benefícios

- Vale Refeição (CLT)
- Jornada de trabalho flexível

### Requisitos

- Programação Java e proficiência em mais duas linguagens de programação;
- Ecossistema Spring (Boot, Web, Cloud, Data, Security, etc.);
- Plataforma Docker (images, containers, swarm, compose, services);
- Integração Contínua e Entrega Contínua (Jenkins, Drone.io, CircleCI, etc.);
- Formação de Ensino Superior em Análise e Desenvolvimento de Sistemas ou equivalente.
- Experiência com princípios TDD, BDD e DDD.

**Diferenciais:**

- Experiência com AWS (EC2, ECS, RDS, ELB);
- Experiência com cultura Agile;
- Experiência com JPA2;
- Experiência com Banco de dados NoSQL;
- Experiência com Mensageria RabbitMQ ou similares (JMS, Kafka, etc.).

### Contratação

CLT ou PJ, a combinar.

### Nossa empresa

O Beblue é uma Fintech de pagamentos com carteira digital que tem como objetivo aumentar o poder de compra das pessoas através de recompensa em cashback. 💰 Atuamos no varejo físico em centenas de cidades brasileira.
Após a compra da maioria das ações pela Omni Banco & Financeira, estamos desenvolvendo 12 novos produtos financeiros (para os usuários do aplicativo e estabelecimentos comercias), gerando demandas bem interessantes para a nossa área de Tech. 💙

### Como se candidatar

https://jobs.kenoby.com/beblue/job/desenvolvedor-engenheiro-java-senior/5d6690df2f467b286da0bcdd

### Labels

🏢 Flexível
🏢 Presencial
👴 Sênior
⚖️ A-Combinar
⚖️ CLT
⚖️ PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
