### ISSUE TITLE
[Barueri/SP] Desenvolvedor Java Sr na [PLATFORM BUILDERS]

### ISSUE THREAD

**Issue by Ana300** [backend-br/vagas#1888]
Buscamos desenvolvedores apaixonados pela linguagem Java, inconformados por natureza e encantados em gerar valor. 

Na Builders você irá fazer parte de um time de empreendedores, onde buscamos inovação com disrupção de forma significativa, com qualidade e simplicidade - seja através do código ou através da melhoria contínua alinhada à performance. 

Tá afim de iniciar essa jornada com a gente, gerando transformação de forma impactante? Se liga nos detalhes abaixo:
**#SejaBuilder**

**Tecnologias que vão gerar valor nos projetos:**
Java 8
Sonar
JPA ou Mockito
Springboot
GIT
Linux
DDD

**O que te torna mito ou uma maga por aqui:**
Conhecimento em Kubernets
Jenkins
Maven
Docker
Microservices
REST
Design Patterns

**INFORMAÇÕES ADICIONAIS**
- Oportunidades reais de empreender e impactar
- Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
- Inovação e criação liberados
- Participar de um processo único de geração de valor
- Contribuir na criação de métodos disruptivos
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de atuação societária
- Prestador de Serviços (PJ)
- Horário flexível
- Férias remuneradas

**APAIXONADOS POR DESENVOLVER CULTURA, PESSOAS E NEGÓCIOS**
Por aqui você não será tratado como um funcionário. Nosso movimento é para pessoas disruptivas e empreendedoras, que querem diariamente desafiar seu próprio status quo, fazendo de sua liberdade e autonomia o oxigênio para a inovação e construção de resultados com alto impacto. Gere valor e tenha a oportunidade de construir o seu próprio legado.
Quer saber mais? #SóBora #GoBuilders #SejaBuilder

**Como se Candidatar**
https://sejabuilder.gupy.io/jobs/116538

**Labels**
Possibilidade de trabalho remoto
PJ
Flexível

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
