### ISSUE TITLE
[Munique - Alemanha] Back-End Developer na [Personio]

### ISSUE THREAD

**Issue by diegofaria** [backend-br/vagas#189]
## Description

- Experience with one of the PHP-based MVC frameworks, and SQL-based relational database design
- Strong OO design skills, ideally experience with development and support of complex B2B systems
- Experience with automated testing. Knowledge of when and what to test
- Interest in DevOps, not shy to reach out for terminal. You are willing to build software in a “You build it, you run it” manner. Ideally, experience with Docker and container orchestration solutions (Kubernetes)
- Proactive problem solver. You leave code and processes in a better shape than when you first encountered them
- Team player. You are passionate about working with talented teammates. Your heart beats for receiving and giving feedback, to grow both personally and as an engineer
- Interest and passion to learn and experiment with new technologies
- Strong written and spoken English
- Willing to relocate - position onsite-only in Munich

## Local

Munich - Germany.

## Benefits:

- Relocation support to Munich, Germany
- Market-proven, well-funded and fast growing company ($14.3M funding acquired to date)
- Direct impact on the daily work of tens of thousands of users
- Creative environment with talented and ambitious team members from more than 15 countries
- High-end hardware, noise-cancelling headphones
- 1.500 EUR of development budget per year for attending conferences, courses, buying books
- Regular team events, including office dinners, skiing trips, and parties
- Unu electric scooter of your choice as "company car" (see www.unumotors.com) or an additional payment for a yearly public transportation ticket
- 26 paid vacation days, and 2 days of home office per month
- Weekly German language courses
- Office in the heart of Munich (near Gärtnerplatz)

## Our company

Personio is a Market-proven, well-funded and fast growing company ($14.3M funding acquired to the date). Join our ambitious product and engineering team and take an active role in shaping the future of our product. You will be responsible for leveling up our UX by improving existing features as well as participating in the specification and implementation of new ones.
- Frontend development is driven by customer feedback
- Help us with the migration of existing application features to React.js

## Labels

- Relocation
- Germany

mail me: diego.faria@personio.de
or apply at our [career site](https://personio-jobs.personio.de/job/1551?language=en#).

**Comment by diegofaria** [comment]
We are still hiring for this job position :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
