### ISSUE TITLE
[Interlagos-SP] Desenvolvedor .NET Core Pleno/Sênior em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#1893]
Descrição da vaga
Estamos em busca de profissional com experiência em .NET Core para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento. 

Local
Presencial no cliente em Interlagos (São Paulo)- estação de trem Jurubatuba.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico
-previdência privada
-plano odontológico

Requisitos
Experiência com: 
o Arquitetura de microserviços
o .NET C# (4.6 e Core/Standard)
o TSQL (SQL Server)
o GIT

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga .NET Core.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
