### ISSUE TITLE
[Mogi das Cruzes/SP] Desenvolvedor RPA/JAVA Jr Pl | Yank! Solutions

### ISSUE THREAD

**Issue by oliviaaversa** [backend-br/vagas#1894]
ATIVIDADES:
-Atuar em cliente de grande porte (ramo de aluguel de carros);
-Desenvolvimento de software (automação) em Java;
-Especificação de Regras de Negócio junto ao cliente.

REQUISITOS:
-Formação em Análise de Sistemas, Ciência da Computação, Engenharia da Computação ou áreas correlatas;
-Inglês intermediário;
-Experiência de no mínimo 6 meses na área de desenvolvimento de software;
-Sólidos conceitos de Orientação a objetos;
-Conhecimento em integração com Banco de Dados (MySQL) e WebServices RESTful;
-Vivência com elaboração de documentação técnica;
-Facilidade na comunicação e contato direto com clientes.

DIFERENCIAIS:
-Experiência profissional em desenvolvimento na linguagem JAVA;
-Conhecimento em ferramentas ou conceitos de RPA;
-Conhecimento em testes automatizados.

HORÁRIO: Seg à Sex, das 9h às 18h ou das 8h às 17h.

TIPO DE CONTRATAÇÃO: PJ

SALÁRIO: à combinar

Interessados enviar CV para **oliviaaversa@yanksolutions.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
