### ISSUE TITLE
[São Bernardo do Campo/SP] Desenvolvedor RPA Jr | Yank! Solutions

### ISSUE THREAD

**Issue by oliviaaversa** [backend-br/vagas#1895]
ATIVIDADES:
-Desenvolvimento de automações (RPA) em Java e plataformas (UiPath);
-Levantamento de requisitos com cliente.

REQUISITOS:
-Experiência profissional na área de desenvolvimento de no mínimo 6 meses (qualquer linguagem);
-Disposição para aprender a trabalhar com tecnologias novas.

DIFERENCIAIS:
-Possuir experiência em UiPath ou qualquer outra ferramenta RPA.

HORÁRIO DE ATUAÇÃO: Horário comercial (08h às 17h ou 09h às 18h)

REGIME DE CONTRATAÇÃO: PJ

TEMPO DO PROJETO: Colaborador fixo, não é por projeto

LOCALIDADE (ATUAÇÃO): São Bernardo do Campo - SP

SALÁRIO: À combinar

Interessados enviar CV para **oliviaaversa@yanksolutions.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
