### ISSUE TITLE
[São Paulo/SP] Desenvolvedor ADVPL Sênior | DWC Consult

### ISSUE THREAD

**Issue by DWCConsult** [backend-br/vagas#1896]
Será responsável por desenvolvimentos em ADVPL para o ERP Protheus; Integrações via Web Service REST e desenvolvimentos de rotinas em MVC.
Atuará em empresa de software na metodologia ágil Scrum.

Requisitos:
- Conhecimento nível sênior em ADVPL;
- Conhecimento e experiência anterior com REST e MVC.

Local: Zona Norte, São Paulo.
Jornada Integral
Forma de contratação Pessoa Jurídica
Vaga para atuação sem prazo determinado.

Interessados encaminhar o currículo para o e-mail: rh@dwcconsult.com.br
Assunto: Dev. ADVPL

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
