### ISSUE TITLE
[Porto Alegre] PHP Developer na InventSys

### ISSUE THREAD

**Issue by cleberar** [backend-br/vagas#1898]
Estamos crescendo, e para construírmos uma base sustentável nesse crescimento, estamos contratando Programador PHP para fazer parte desta jornada.

Alguns requisitos são importantes para isso:

* Valorizar um ambiente saudável e bacana!
* Curtir a musiquinha do Pokémon que toca todas as tardes na escola ao lado da empresa
* Conhecimento do uso do git
* Programação em PHP7
* Domínio de Bancos de Dados MySQL

São diferenciais dignos de ganhar bolo e brigadeiro no aniversário (e um plus no fim do mês):

* NodeJS e JavaScript
* React e React Native
* Conhecimento de NoSql

**Contratação**

CLT ou PJ, a combinar.

Para se candidatar envie um e-mail para inventsys@inventsys.com.br com o assunto: Vaga Programador PHP

**Labels**

- Presencial
- PJ
- CLT
- Pleno

**Comment by juliaguiar** [comment]
Aceita remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
