### ISSUE TITLE
[Salvador] Desenvolvedor Back-End na VXCASE

### ISSUE THREAD

**Issue by cilas** [backend-br/vagas#1899]
## Descrição da vaga

- Auxiliar no desenvolvimento de novas funcionalidades e na manutenção do sistema (PHP)
- Participar do planejamento das sprints para ajudar a equipe a fazer entregas de qualidade.
- Auxiliar a equipe e o projeto no uso de boas práticas de programação.

## Local

 Escritório, Salvador-Ba

## Requisitos
- Ter conhecimento em PHP e/ou Javascript
- Ter trabalhado com algum framework frontend (Angular, React e afins)
- Conhecimentos básicos em Git/Gitflow
- Boa capacidade analítica para ajudar a resolver os problemas.

**Diferenciais:**
- Conhecimento e experiência em boas práticas de desenvolvimento de software, como TDD, código limpo e padrões de projeto
- Conhecimento básico em docker
- Conhecimento em Python
- Conhecimento no desenvolvimento e integração com APIs e arquitetura de aplicações Web

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para jamillysantana@vxcase.com.br com seu CV anexado - enviar no assunto: Vaga Back-End Vxcase

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by juliaguiar** [comment]
Aceita remoto?

**Comment by cilas** [comment]
Apenas presencial.

**Comment by Cleiton080** [comment]
Qual o endereço?

**Comment by cilas** [comment]
Fica na Avenida Luiz Eduardo.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
