### ISSUE TITLE
[Remoto ou RJ] Back-end NodeJs Developer na SmartTaylor.io

### ISSUE THREAD

**Issue by tregismoreira** [backend-br/vagas#190]
# Apresentação

Somos uma startup internacional — com base no Rio de Janeiro — com a missão de simplificar o uso de cripto moedas. Os primeiros produtos que estamos desenvolvendo são relacionados a trading de cripto moedas.

Estamos em busca de nerds programadores apaixonados por grandes desafios. Pessoas com sangue nos olhos e com vontade de gerar impacto no futuro do mercado financeiro mundial.

Para desenvolver os melhores produtos, nós precisamos da melhor equipe. Por isso nós só contratamos gente f***!

# Vaga

Programador back-end com profunda experiência em NodeJs.

Contratação PJ para trabalho full-time remoto ou presencial no Rio de Janeiro.

# Compensação

* Salário baseado em dólar com pagamento em Bitcoin ou Ethereum
* Programa bacana de perks (que evolui conforme a empresa cresce)
* Bonus em tokens (TAY - nossa própria cripto moeda)
* Ambiente super agradável no [WeWork Carioca](https://www.wework.com/buildings/carioca--rio-de-janeiro) (para quem vier trabalhar presencialmente)

# Requisitos

* Profunda experiência com NodeJs
* HTML5, CSS3
* Javascript (vanilla)
* ReactJs + Redux
* ES6 / Typescript
* GIT
* RESTful APIs
* Testes unitários e automatizados
* Firebase (Real-time database, Functions etc)
* Código limpo, bem escrito e organizado

# Desejável

* Experiência com outras languagens de programação como Python, Golang, Elixir etc
* Experiência com aplicações críticas e de alta disponibilidade
* Análise e otimização de algorítmos
* BI / Machine learning
* Serverless
* Micro-serviços
* Programação funcional
* Experiência com desenvolvimento front-end
* Projetos publicados no Github
* Conhecimento de Blockchain e cripto moedas
* Solidity (Ethereum)
* GraphQL

# Como se candidatar

Envie um email para jobs@smarttaylor.io incluindo seu LinkedIn, Github e um breve texto explicando o que te faz ser o melhor sentre seus amigos/colegas. Lembra que só contratamos gente f***? :)

# Labels

* Remoto
* Presencial
* Senior
* Pleno
* PJ

**Comment by sandrosimas** [comment]
Não sou PJ, mas me interessei pelo projeto. Existe alguma outra forma?

**Comment by tregismoreira** [comment]
@sandro-csimas abrir um MEI é bem simples hoje em dia ;)

**Comment by tregismoreira** [comment]
Também temos vagas para de front-end: https://github.com/frontendbr/vagas/issues/1004

**Comment by simaodev** [comment]
Tenho interesse na vaga, sou PJ moro em Blumenau/SC

**Comment by tregismoreira** [comment]
@horsgle mande um email pra gente ;)

**Comment by joaopandolfi** [comment]
Tenho interesse pela vaga, moro em Santo André/SP

**Comment by tregismoreira** [comment]
@joaopandolfi siga as instruções para aplicação na vaga ;)

**Comment by DavidVeloso** [comment]
@tregismoreira O Processo seletivo ainda esta aberto ? (:

**Comment by tregismoreira** [comment]
@DavidVeloso 2 vagas já foram preenchidas, mas ainda temos 1. Manda lá ;)

**Comment by vinyguedess** [comment]
Vaga aberta ainda ?

**Comment by tregismoreira** [comment]
@vinyguedess por enquanto não, mas vamos retomar em 2~3 meses. Manda os dados lá ;)

**Comment by reginaldojunior** [comment]
@tregismoreira vou fechar a vaga por enquanto então, dps vc reabre ok? Abs
