### ISSUE TITLE
[SÃO PAULO] Software Engineer Back-End no banco digital Cora - NOVA Startup Fintech

### ISSUE THREAD

**Issue by ViniciusRodrigues26** [backend-br/vagas#1900]
A Cora está nascendo e precisa de você para construir um banco digital disruptivo e completo!

A empresa foi fundada pelos criadores do Moip (concorrente do PayPal, vendido para o Wirecard por 165 milhões) e por trás dela está a Stone e Jorge Paulo Lemann, do grupo 3G Capital, investidora de marcas gigantes, como iFood e Ambev.

É tudo do zero! A Cora está escolhendo as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Ela busca oferecer uma solução voltada para os micro e pequenos empreendedores do nosso país. O grande objetivo é que, até 2030, o trabalho da Cora possa aumentar o PIB do Brasil em 30% através do crescimento desses empreendedores!

Para isso, estão buscando profissionais fora da curva, de todo o Brasil, com propósito e dispostas a crescer exponencialmente! É preciso ter bastante experiência e estar disposto a colocar a mão na massa. Serão bem vindos conhecimentos em infraestrutura, clean code e boas práticas de programação! A perspectiva é que o(a) Back-End Developer cresça junto com a empresa, construa o time de experts e seja uma liderança no futuro!

A contratação possui remuneração competitiva, benefícios atrativos e será feita em regime CLT, para atuar de forma presencial em São Paulo, com autonomia, flexibilidade e sendo parte de um time extremamente motivado, com senso de donos e personalidade!

Para mais informações, acesse a página da vaga http://byintera.in/desafioesbe ou pode falar diretamente comigo através do linkedin https://www.linkedin.com/in/viníciusrodrigues/ para entender melhor o desafio.

É uma oportunidade fantástica para quem quer construir algo gigante em pouco tempo e dar sua identidade à solução!

**Comment by luizadpassos** [comment]
Qual a carga horária?

**Comment by andre-reis93** [comment]
Quais as linguagens necessárias?
