### ISSUE TITLE
[São Paulo] Desenvolvedor Back-End na ProCTi

### ISSUE THREAD

**Issue by procoworking** [backend-br/vagas#1901]
Desenvolvimento de um novo sistema (PHP)

Requisitos:
Ter conhecimento em PHP e/ou Javascript
Ter trabalhado com algum framework frontend (Angular, React e afins)
Conhecimentos básicos em Git/Gitflow
Boa capacidade analítica para ajudar a resolver os problemas.

Contratação:
CLT ou PJ a combinar

Como se candidatar:
Por favor envie um email para rh@procti.com.br com seu CV anexado - enviar no assunto: Vaga Back-End

**Comment by rodrigofbm** [comment]
aceita remoto?

**Comment by juliaguiar** [comment]
aceita remoto?

**Comment by procoworking** [comment]
Julia, bom dia.

Sim. Me envie o currículo, por favor.

At.te,

*Augusto Póvoa*




[image: Logo] <https://www.procti.com.br/>

T: + 55 11 3522 4750

M: + 55 11 986 760 998

1471 Paulista Avenue, Sao Paulo, SP, Brazil

[image: Facebook icon] <https://www.facebook.com/ProcTiSolution/>  [image:
LinkedIn icon] <https://www.linkedin.com/company/procti-solution/>  [image:
Twitter icon] <https://twitter.com/procti_solution>  [image: Google Plus
icon] <https://plus.google.com/+ProctiBr>  [image: Instagram icon]
<https://www.instagram.com/procti/>






Em sex., 29 de nov. de 2019 às 11:48, Júlia Albuquerque <
notifications@github.com> escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
