### ISSUE TITLE
[São Paulo] Software Data Engineer at Inspetor

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1903]
A **Inspetor** está nascendo e precisa de você para construir a plataforma anti fraude da América Latina.

É **tudo do zero!** Estamos escolhendo a melhor infraestrutura e as melhores tecnologias para construir uma plataforma altamente disponível, escalável e consistente à longo prazo. Tudo isso para resolver a dor latente do mercado varejista onde estimasse uma perda de **R$500 Bilhões em fraudes** para os próximos 3 anos.

Atualmente nós utilizamos **Python, AWS e processamentos de dados open-source**.
Essas tecnologias mais atualizadas do mercado, em uma empresa fundada por dois **Engenheiros de Dados de Stanford** e **pessoas com propósito** é o que buscamos para crescer exponencialmente.

A contratação será feita em regime CLT, para atuar de forma presencial na Pinheiros, em São Paulo. Para mais informações, acesse a página da vaga: http://bit.ly/34hsJWQ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
