### ISSUE TITLE
[São Paulo/SP] Python Developer Pleno na Mutant

### ISSUE THREAD

**Issue by reinaldo-gomes** [backend-br/vagas#1904]
## Descrição da vaga

Se você gosta de desafios, não se acomoda com a rotina de uma única aplicação, tem um perfil protagonista em todas as etapas de criação e melhorias e tem interesse em desenvolver conhecimento em uma linguagem secundária de trabalho (PHP), temos uma oportunidade que combina com o seu perfil! 
 
Estamos montando um time de desenvolvimento para atender a demanda por criação de aplicações (principalmente de automatização de tarefas) que possam potencializar e revolucionar a forma de trabalho das equipes internas da empresa, e eventualmente criar soluções que sejam utilizadas também por nossos clientes externos. 

## Local

Escritório em São Paulo/SP - Jardim Europa

## Benefícios

- Plano de saúde
- VR/VA
- Vale transporte
- Demais benefícios CLT

### Diferenciais

- Sala de jogos/descanso
- Código de vestimenta liberal
- Happy Hour toda semana com cerveja liberada
- Home office parcial
- Horário flexível
- Ambiente inclusivo

## Requisitos

**Obrigatórios:**
- curso superior completo na área de tecnologia
- experiência com desenvolvimento backend em Python
- experiência com framework ORM (preferencialmente SQLAlchemy)
- experiência em testes de unidade e integração
- experiência com Git Version Control
- experiência com bases de dados relacionais (mysql)
- inglês: fluência em leitura de documentação e artigos

**Desejáveis:**
- capacidade analítica e senso crítico
- familiaridade com planos e casos de teste
- familiaridade com as culturas Agile e DevOps
- experiência com ferramentas de deploy automático
- familiaridade com linha de comando e ambiente Linux
- vontade e atitude para melhorar os processos utilizados
- iniciativa para identificar e sugerir a implementação de novos processos
- conhecimento em PHP

## Contratação

CLT a combinar

## Nossa empresa

A Mutant é uma empresa focada em experiência do cliente e plataformas digitais, e que está em pleno crescimento. Saiba mais em: https://mutantbr.com/sermutant/

## Como se candidatar

Envie um email para reinaldo.gomes@mutantbr.com, com CV e pretensão - enviar no assunto: Vaga PHP

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by gbbocchini** [comment]
Bom dia!

Há possibilidade de trabalho remoto?

Obrigado

**Comment by reinaldo-gomes** [comment]
Por enquanto não estamos admitindo em regime 100% remoto, mas contamos com 2 dias de home office para residentes em SP que possam comparecer no escritório ao menos 3 vezes por semana.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
