### ISSUE TITLE
[São Paulo/ SP] - Software Engineer na Creditas

### ISSUE THREAD

**Issue by VitorChaves21** [backend-br/vagas#1906]
## Nossa empresa

Para trazer inovação ao mercado de empréstimos, nós apostamos em tecnologia. É com ela que escalamos o negócio, otimizamos processos e melhoramos a experiência dos clientes. Nossa plataforma foi criada dentro de casa utilizando tecnologia open source, seguindo a filosofia agile e suas práticas. Mas nosso negócio mesmo são as pessoas: não abrimos mão do atendimento personalizado, prestando consultoria e oferecendo educação financeira para empoderar o cliente a tomar a melhor decisão.

Se você chegou até aqui, provavelmente é porque nunca se contentou com o chão. Sempre buscou voar e agora quer voar ainda mais alto. Quer ir para um próximo nível, evoluir, oxigenar, impactar, desafiar e desafiar-se.
Temos uma boa notícia para você: a nave **Creditas** está voando e está em busca de novos tripulantes.

## Local

Av. Engenheiro Luís Carlos Berrini, 105, 12º andar – Itaim Bibi, CEP 4571010, São Paulo – SP

## Benefícios

- Assistência médica e odontológica
- VR
- Vale Alimentação
- Gympass;
- Estacionamento/Fretado/Bicicletário;
- Seguro de vida;
- Auxílio educação/estudo e Aulas de Inglês in company;

## Requisitos

- Experiência em desenvolvimento Java;
- Habilidade em desenvolver e implementar APIs;

## Como será o seu dia a dia

- Desenvolver garantindo funcionalidade, manutenibilidade e velocidade, além de garantir práticas de teste e qualidade;
- Garantir que todas as soluções técnicas estejam alinhadas a estratégia do negócio e entender OKRs e iniciativas relacionadas ao produto;
- Entender o impacto das soluções que o time desenvolve no usuário final;
- Ajudar o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;
- Colaborar com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam vários times;
- Trabalhar em um ambiente colaborativo, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads.
 
## Contratação

Em regime CLT e presencial

## Como se candidatar

Candidate-se através de http://byintera.in/59

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
Nossos processos são rápidos e eficientes para os candidatos

## Labels

- Alocado
- CLT
- Sênior/pleno

**Comment by MoraesGil** [comment]
> Requisitos
> Experiência em desenvolvimento Java;
Seria javascript ou java pra web (JSP, Servlet, MVC, Spring MVC, JDBC e Hibernate.) ?
