### ISSUE TITLE
[Belo Horizonte/MG, São Paulo ou Campinas/SP] Arquiteto DevOps na Sympla

### ISSUE THREAD

**Issue by rh-sympla** [backend-br/vagas#1908]
## Quem somos?

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA. Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla, estamos escalando nosso time e para isso buscamos pessoas incríveis!   

Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

 ## Porque o(a) Arquiteto de DevOps é importante para nós? 
Como membro do time de Segurança e Risco, você deverá aplicar seus conhecimentos e experiências sobre DevOps para implementar as melhores práticas e promover a integração contínua dos projetos, monitoramento dos ambientes de desenvolvimento/homologação e produção.

 ## Seus desafios serão:

Mapear, conhecer e analisar os ambientes de desenvolvimento/homologação e produção da Sympla;
Trazer as melhores práticas e ferramentas para auxiliar na melhoria  da nossa infra, buscando manter um ambiente com alta performance, seguro e escalável, seguindo os melhores padrões de microsserviços praticados no mercado;
Criação de métricas e o monitoramento da infra de modo que a mesma esteja sempre estável e pronta para escalar quando haja a necessidade;
Aplicar novas tecnologias de DevOps;
Administrar/Gerenciar infra na stack da AWS;
Configuração/Integração com API’s e ferramentas de analytics;
Atuação com foco nos resultados de PenTesting, auxiliando no planejamento e execução, bem como atuação junto aos times de projetos prestando consultoria na construção dos planos de correção.
Desenvolver e executar treinamentos de conscientização e boas práticas de desenvolvimento seguro.
Identificar requisitos de segurança, juntamente dos times de desenvolvimento de aplicações e DevOps
 
## Oferecemos:

Ambiente criativo, inovador e estimulante;
Regime de contratação CLT;
Salário compatível com o mercado, VT e VR;
Plano de Saúde e Odontológico;
No dress code (pode trabalhar de bermuda, chinelo, etc);
Clima descontraído;
Café, bebidas variadas e snacks;
Horário flexível :)
40h semanais, de segunda a sexta.
 
## O que buscamos?

Procuramos pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras.

Além disso:

Superior em Ciências da Computação, Sistemas da Informação, Processamento de Dados ou áreas correlatas;
Ter um bom domínio de pelo menos uma das linguagens de script: Python / Ruby / Perl;
Domínio da stack AWS ou similares;
Experiência relevante com o desenvolvimento e integração de Software/Infraestrutura, permitindo dar suporte completo ao ciclo de vida das aplicações;
Domínio de shell scripting;
Conhecimento de metodologias ágeis;
Vivência com tecnologias de monitoramento de sistemas (Zabbix, Graphite, Nagios e similares, ELK), pois é fundamental a capacidade de coletar e analisar métricas da infraestrutura;
Conhecimento em linguagens de configuração: Chef / Puppet / CFEngine / Ansible / Terraform;
Domínio em tecnologias de conteinerização: Docker e Kubernetes;
Entendimento de análise, depuração e gerência de ambientes *nix based, com foco em desempenho e segurança;
Vivência em: Gitlab / Jenkins / Vagrant / Apache / Jira;
Domínio em arquitetura de ambientes voltados a microsserviços, com experiência na transição de ambientes monolíticos para ambientes de microsserviços;
Proatividade, capacidade de propor soluções de alto impacto para o nosso ambiente,  com uma visão inovadora de como solucionar problemas, além de buscar sempre estar atualizado na sua área.
Must rock!
 
## Alguns diferenciais para a função:

Conhecimento de cloud: Azure / IBM Cloud | Google Cloud;  
Domínio em Kubernetes ou outras tecnologias de conteinerização;
Vivência com Selenium / Kong / Sonar / ELK / Nginx;
Conhecimento em profile/hardening e otimização de servidores web;
Foco em desempenho; simplicidade e segurança;
Conhecimento em Java
 
Valorizamos trabalhar em um ambiente de pluralidade e de inclusão, por isso todas nossas vagas também são para profissionais com deficiência.

Se o seu perfil corresponde ao que acreditamos, venha fazer parte do nosso time!!!

## Como se candidatar
https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=4457294002

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
