### ISSUE TITLE
[REMOTO] Sênior FullStack (Ruby on Rails + jQuery | SASS | HTML)

### ISSUE THREAD

**Issue by marcus-campos** [backend-br/vagas#1909]
Buscamos profissionais nível Sênior, que dominem Ruby on Rails e tenham experiências em jQuery | SASS | HTML, usando o próprio Ruby on Rails.

### **Diferenciais:**

Conhecimentos em React, VueJS, arquitetura frontend, experiência em projetos de fintechs, softwares financeiros e em aplicações de grande porte.

É de extrema importância que o/a profissional tenha experiência com testes automatizados (Rspec), além de prezar sempre por código limpo e organização por parte do time.

### **Sobre o trabalho:**
Os perfis selecionados atuarão em diversos squads, que aplica daily meeting e semanalmente realizam reunião de métricas. Adotam como boas práticas na etapa de revisão dos trabalhos, quando abrem Pull Request. Esta avaliação não é apenas do código, mas também da solução e dos impactos possíveis.
Espera-se que esses/as profissionais tenham proatividade, facilidade na resolução de problemas e muita colaboração com o time!

Nível: Sênior
Modelo: Remoto
Carga horária: Full Time, em horário comercial

E aí? Ficou a fim de participar desse processo? Então é só [clicar aqui](https://app.impulso.network/opportunities/08e5c1a6-e11d-47d2-9bb0-39c0fee8122d/public?referral=ba2a7a99&)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
