### ISSUE TITLE
[Belo Horizonte] Full-Stack Developer

### ISSUE THREAD

**Issue by tracksale-talents** [backend-br/vagas#191]
**Suas principais atividades**

Ajudar na construção e manutenção da arquitetura da aplicação;
Implementar e evoluir funcionalidades na plataforma;
Participar ativamente de nossas reuniões de evolução do produto.

**Experiências**

Experiência com desenvolvimento Web, preferencialmente utilizando PHP (Yii Framework e/ou Laravel), frameworks de JavaScript e GoLang;

Experiência com banco de dados relacionais e não relacionais;

Conhecimento das melhores práticas de engenharia de software;

Facilidade para ler e entender código fonte, independente da linguagem de programação.

Experiência com micro-services e arquitetura modular

 

**Diferenciais**

Testes automatizados;

Conhecer os serviços oferecidos pelas principais plataformas de computação em nuvem, de preferência AWS.

 

**Benefícios**

CLT - Salário de R$ 1.800 a R$ 3.500 -- De acordo com experiência
Vale transporte e alimentação;
Plano odontológico com co-participação;

Plano de saúde com co-participação;

Sólidas oportunidades de crescimento profissional;
No dress code (venha trabalhar de t-shirt, bermuda, sandália, chinelo…);
Oportunidade de conviver e aprender com grandes nomes da Tecnologia e da Experiência de Cliente;
Celebre com a gente as vitórias de cada semana no happy hour de sexta;
Venha se divertir com nossas competições de beer pong, cambalhotas, dança, videogame e arminhas Nerf;
Quando você menos esperar, vai ter hamburguer, hot dog ou salada de frutas sendo preparados;

**Carga Horária**

40 horas semanais

**Horário de trabalho**

Flexível das 7h00 as 21h00

*Como se candidatar*

Se cadastre em tracksale.co/jobs, mande seu currículo e responda algumas perguntas que colocamos na página! 
 

**Local de trabalho**

Bairro Lourdes, Avenida do Contorno próximo a Av. Raja e  Av. Olegário Maciel

**Comment by tracksale2030** [comment]
-

**Comment by ghost** [comment]
site nao funfa com vivaldi?

**Comment by raulinoneto** [comment]
Existe a possibilidade de trabalhar remoto?

**Comment by tracksale-talents** [comment]
Por enquanto não... seria aqui na nossa sede mesmo!
<https://tracksale.co/> *Marcella Rodrigues | Human Resources Analyst *

*Mobile* +55 (31) 98783 8016 | *Financeiro:* (31) 2551-4141
*Vendas:* 0800 025-8972 | * Sucesso do Cliente:*(31) 3058-0303
*Skype:* cella.rodrigues
*Brasil* | SP | MG
*Argentina* | Buenos Aires


Em dom, 13 de mai de 2018 às 14:53, raulinoneto <notifications@github.com>
escreveu:

**Comment by fsrocha-dev** [comment]
Entrevista via Skype ? Sou da Bahia mas tenho disponibilidade para mudança.
