### ISSUE TITLE
[Remoto] Urgent > Back-end Developer NodeJS na JOYJET

### ISSUE THREAD

**Issue by PachecoRaphael** [backend-br/vagas#1910]
Hello,

Joyjet is looking for a back-end developer in Nodejs for one of our project already on the go. It´s a project to help people be more secure when going back home. But you may also help on other projects if you join us! We have a lot of different projects from e-commerce to interns app for businesses.

Typescript is essential to know here as the projects use it. 

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Local
Remoto

## Benefícios
Plano de saúde
Free course to study

## Requisitos obrigatórios:
- 3 years of experience as a back-end developer
- Nodejs
- Typescript
- HTML/CSS
- GIT

## Desejáveis:
Knowledge in Mongodb would be good
Knowledge in Nest js

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA BACK-END Node js

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Labels
PJ
Pleno
Remoto
Nodejs
Typescript

**Comment by droliv** [comment]
Bom dia, o email está retornando dizendo que o endereço de email não existe.

**Comment by PachecoRaphael** [comment]
> Bom dia, o email está retornando dizendo que o endereço de email não existe.

Updated thx !
