### ISSUE TITLE
[Remoto] Back-end Developer Python (Fast API or Flask API) na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [backend-br/vagas#1911]
Hello,

Joyjet is looking for a back-end developer in Nodejs for a new project coming next year. But you may also help on other projects if you join us! We have a lot of different projects from e-commerce to interns app for businesses.

We will be using frameworks based on Python. And Fast or Flask API for this project. 

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Local
Remoto

## Benefícios
Plano de saúde
Free course to study

## Requisitos obrigatórios:
- 3 years of experience as a back-end developer
- Python
- HTML/CSS
- GIT

## Desejáveis:
- Django Framework

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para job@joyjet.com com seu CV anexado - enviar no assunto: VAGA BACK-END Python

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Labels
PJ
Pleno
Remoto
Python

**Comment by sleonardoaugusto** [comment]
Está acusando que o email job@joyjet.com não existe ou não pode receber mensagens.

**Comment by supwr** [comment]
Ainda em aberto?
