### ISSUE TITLE
[SÃO PAULO] BACK-END DEVELOPER NA RADAR PROFISSIONAL

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#1912]
## Descrição da vaga

Estamos à procura de um profissional, para atuar como desenvolvedor PHP Sênior, em um projeto indeterminado. 

## Local

Escritório, Real Parque - Morumbi

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia
- Plano odontológico
- Vale Transporte

## Requisitos

**Obrigatórios:**
•	Superior completo em Ciências da Computação, TI ou áreas correlatas; 
•	Experiência com PHP 5, utilizando SYMFONY2 ou superior, desenvolvimento de Procedures views, banco SQL SERVER, controle de versão GIT, com criação de branchs e tags;
•	Vivência com Linux (Debian, Ubuntu), tecnologias BaaS e Armazenamento em Nuvem;
•	3 anos de experiência  para Sênior
•	Experiência com Symphony

**Diferenciais:**
•	Será considerado como diferencial, o profissional com experiência no setor de Saúde, Privado ou Público, desenvolvimento de aplicativos móveis híbridos: Xamarin, Ionic, Phonegap ou Nativos: Android (Java ou Kotlin), IOS (Swift), arquitetura de software para desenvolvimento móvel, MQTT broker.

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para talento@radarprofissional.com.br  com seu CV anexado - enviar no assunto: Vaga PHP Sênior 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: talento@radarprofissional.com.br

## Labels

- CLT
- PJ
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
