### ISSUE TITLE
[Ribeirão Preto/SP] Desenvolvedor Java - Pleno no Beblue

### ISSUE THREAD

**Issue by Gabrielle1012** [backend-br/vagas#1913]
## Descrição da vaga

Como Desenvolvedor Java Pleno, você será responsável por:

- Projetar e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;
- Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc;
- Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes.

## Local
Ribeirão Preto/SP

## Benefícios
- Vale Refeição (CLT)
- Jornada de trabalho flexível

## Requisitos
- Experiência com Programação Java;
- Experiência com o ecossistema Spring (Boot, Web, Data, etc.);
- Experiência com TDD;
- Formação de Ensino Superior em Análise e Desenvolvimento de Sistemas ou equivalente.

**Diferenciais:**
- Experiência com cultura Agile;
- Familiaridade com O.S. Linux/Unix;
- Experiência com JPA2;
- Familiaridade com AWS (EC2, ECS, RDS, ELB);
- Familiaridade com Mensageria RabbitMQ ou similares (JMS, Kafka, etc.)

## Contratação
CLT ou PJ, a combinar.

## Nossa empresa
O Beblue é uma Fintech de pagamentos com carteira digital que tem como objetivo aumentar o poder de compra das pessoas através de recompensa em cashback. 💰 Atuamos no varejo físico em centenas de cidades brasileira.
Após a compra da maioria das ações pela Omni Banco & Financeira, estamos desenvolvendo 12 novos produtos financeiros (para os usuários do aplicativo e estabelecimentos comercias), gerando demandas bem interessantes para a nossa área de Tech. 💙

## Como se candidatar
https://jobs.kenoby.com/beblue/job/desenvolvedor-engenheiro-java-senior/5d6690df2f467b286da0bcdd

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
