### ISSUE TITLE
[Rio de Janeiro] Back-End Developer Pleno [URB9][Close]

### ISSUE THREAD

**Issue by rafaelso86** [backend-br/vagas#1914]
## Descrição da vaga
Se você gosta da ideia de trabalhar em um ambiente criativo, participar da mirabolação de novos serviços e soluções e, de quebra, fazer parte de uma equipe multidisciplinar formada por gente bonita, elegante e sincera, então você achou seu lugar! Você trabalhará criando soluções web, como aplicativos, intranet e websites. Pra isso, a gente precisa que você:
   ####
## Local

Ficamos no centro da cidade do Rio de Janeiro.

## Requisitos
- Tenha mais de três anos de experiência como profissional;
- Saiba desenhar e manter bancos de dados;
- Trabalhe com APIs e integração entre plataformas;
- Tenha experiência com MySQL, PHP, Codeigniter, JavaScript;
- Saiba (e goste!) de trabalhar em equipe!

## Alguns diferenciais que fazem nosso olho brilhar:
- Inglês avançado;
- Experiência em projetos realizados por métodos ágeis;
- Experiência com projetos de estruturação de dados;

## Contratação
Aqui, a gente trabalha com contratação fixa, em CLT.

## Benefícios
- 13° salário;
- Férias remuneradas;
- Vale transporte;
- Vale refeição;
- Após o período de experiência, plano de saúde integral;
- Possibilidade de home office planejado.

## Como se candidatar
E aí, quer fazer parte da nossa equipe de desenvolvimento?

É só mandar seu CV, com DESENVOLVEDOR BACK-END no assunto, para leandro@urb9.com.br.

Estamos te esperando

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
