### ISSUE TITLE
[Porto Alegre - RS] Desenvolvedor(a) Back-end Node.js [Triider]

### ISSUE THREAD

**Issue by gregslag** [backend-br/vagas#1915]
# Sobre nós
O Triider é uma plataforma de serviços. É o app que te conecta aos melhores profissionais do mercado com a mesma praticidade de chamar um carro pelo celular. Nascemos de uma dificuldade que muitas pessoas enfrentam quando precisam contratar profissionais para serviços de manutenção como eletricistas, hidráulicos, pintores, diaristas e outros. Completamos 3 anos de operação em Porto Alegre e iniciamos a nossa expansão nacional em 2019. Já chegamos em Curitiba (PR), Belo Horizonte (MG) e Brasília (DF) e, nos próximos meses, iremos para São Paulo (SP). 
 
Procuramos desenvolvedor(a) que queira trabalhar em um ambiente inovador e diferenciado.
 
Somos apaixonados por usar os melhores métodos e ferramentas para construir os nossos produtos e trazer uma experiência fantástica para os nossos usuários.
 
# Responsabilidades
- Pensar constantemente em novas ideias e não ter medo de errar;
- Desenvolver os nossos sistemas sempre pensando em boas práticas de arquitetura de software, trazendo sugestões e experiências;
- Identificar e propor melhorias para os sistemas atuais para aumento de produtividade, escalabilidade, estabilidade e/ou controle;
- Prestar suporte técnico para que o nosso time interno tenha as melhores condições de atender os nossos clientes.
 
# Requisitos
- Fluente em Javascript (ES6+)
- Conhecimentos de Node.js;
- Conhecimento de API REST;
- Conhecimento de SQL (Banco de dados);
- Conhecimento em ferramentas de testes;
- Práticas de Devops para implementar rotinas de CI/CD;
- Conhecimentos de computação em núvem e distribuída;
- Conhecimentos de controle de versões (GIT);
- Conhecimento de metodologias ágeis;
- Esteja alinhado com as melhores práticas de desenvolvimento.
 
# Desejável
- Conhecimento de desenvolvimento de aplicativos móveis;
- Conhecimento de desenvolvimento WEB;

# Como se candidatar
Mande seu currículo para para mecontrata@triider.com

**Comment by danielsidev** [comment]
Olá @gregslag ! Tudo bem?
Essa vaga pode ser remota? Sou do RJ! =)
Abraços!
http://danielsiqueira.net

**Comment by gregslag** [comment]
Oi @danielsidev !
Essa vaga seria para atuar em Porto Alegre..
No momento não temos vagas remotas.
Abraço!

**Comment by maximilianocatarino** [comment]
@gregslag aceitam candidados de outros estados?
