### ISSUE TITLE
[REMOTO] Pleno/Sênior FullStack na [Agência Pipoca Digital]

### ISSUE THREAD

**Issue by klerio** [backend-br/vagas#1916]
Se você adora aprender, compartilhar conhecimento, trabalhar com os melhores profissionais e fazer a diferença no dia-a-dia, essa é a vaga ideal e você é a pessoa que nós procuramos.

Confira abaixo alguns critérios da vaga:

**Requisitos**

- HTML5
- CSS3 (Algum pré-processador)
- JavaScript
- PHP
- Laravel Framework
- Gulp ou Webpack
- Git
- Pré-processadores
- Adobe XD (para recortes de elementos)

**Diferenciais**
NodeJS, Vue.js, React ou AngularJS

**Informações**
- Contrato por PJ (MEI)
- Local: Remoto ou na Sede do Rio de Janeiro
- Nível Pleno ou Sênior.

Curtiu a vaga? [Clica aqui](https://docs.google.com/forms/d/e/1FAIpQLSccIWtGkmJJjdOoNCTJhjiBMpr_wVlOplQ5-Wti_QMja8sSiA/viewform) e venha fazer parte do processo seletivo.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
