### ISSUE TITLE
[Porto Alegre - RS] Analista DevOps [Triider]

### ISSUE THREAD

**Issue by gregslag** [backend-br/vagas#1917]
# Sobre nós
O Triider é uma plataforma de serviços. É o app que te conecta aos melhores profissionais do mercado com a mesma praticidade de chamar um carro pelo celular. Nascemos de uma dificuldade que muitas pessoas enfrentam quando precisam contratar profissionais para serviços de manutenção como eletricistas, hidráulicos, pintores, diaristas e outros. Completamos 3 anos de operação em Porto Alegre e iniciamos a nossa expansão nacional em 2019. Já chegamos em Curitiba (PR), Belo Horizonte (MG) e Brasília (DF) e, nos próximos meses, iremos para São Paulo (SP). 
 
Procuramos um talento de DevOps que queira trabalhar em um ambiente inovador e diferenciado.
 
Somos apaixonados por usar os melhores métodos e ferramentas para construir os nossos produtos e trazer uma experiência fantástica para os nossos usuários.
 
# Responsabilidades
- Pensar constantemente em novas ideias e não ter medo de errar;
- Manter a infraestrutura de cloud do Triider na AWS;
- Construir e manter as integrações CI/CD;
- Trazer boas práticas de arquitetura de software, trazendo sugestões e experiências;
- Identificar e propor melhorias para os sistemas atuais para aumento de produtividade, escalabilidade, estabilidade e/ou controle;

# Requisitos
- Amazon Web Services (AWS);
- Google Cloud Platform;
- Experiência com tecnologias de containers (Docker) e Orquestradores;
- Conhecimento de API REST;
- Conhecimentos de computação em nuvem e distribuída;
- Conhecimentos de controle de versões (GIT);
 
# Desejável
- Programação nas linguagens Node.js, Python;

# Como se candidatar
Mande seu currículo para para mecontrata@triider.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
