### ISSUE TITLE
[São Carlos - SP] Full-Stack Developer na Tokenlab

### ISSUE THREAD

**Issue by carlosasj** [backend-br/vagas#192]
![group copy 3](https://user-images.githubusercontent.com/4120311/39447033-dd83428a-4c96-11e8-99cb-beb31cf3b0f0.png)

**Perfil**
Ser proativo e participativo dando opinião de forma construtiva. Ter espírito de melhoria contínua, ser e respeitar o planejamento dos projetos, estar em sintonia dos interesses da empresa e projetos. Respeitar e seguir processos e políticas da empresa. Gostar de estar em um ambiente descontraído, com liberdade e com pessoas que buscam se desenvolver sempre e crescer em conjunto com o time.

**Pré-requisitos obrigatório**
Experiência com metodologias ágeis, lógica de programação.
Propor soluções e definições de arquitetura.
Conhecimentos e experiência nas linguagens e frameworks HTML, CSS, Bootstrap, Javascript, Angular (preferencialmente 2+), JQuery.
Conhecimentos e experiência com NodeJS ou Grails.
Conhecimento e experiência em Arquitetura MVC, webservices REST, GIT, Versionamento, Gerenciador de dependências e Deploy da aplicação.
Ter noções de UI/UX.

**Desejável conhecimento**
Inglês avançado.
Conhecimento em Material Design e Design responsivo.
Conhecimentos em desenvolvimento de testes automatizados.
Experiência com banco de dados.
Ter concluído curso superior de Tecnologia da Informação ou relacionado.

**Benefícios**
CLT - Salário a combinar
Vale transporte e refeição
Plano odontológico
Plano de saúde com co-participação
PLR
Incentivo a cursos e certificações

**Carga Horária**
40 horas semanais (presencial)
Horário flexível

**Como se candidatar**
Enviar currículo para recrutamento@tokenlab.com.br

**Local de trabalho**
Av. Comendador Alfredo Maffei, 1489
São Carlos - SP

labels: Angular, Angular2, AWS, CLT, Java, JavaScript, NodeJS, Presencial

**Comment by carlosasj** [comment]
A vaga permanece aberta :smiley:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
