### ISSUE TITLE
Desenvolvedor Ruby on Rails

### ISSUE THREAD

**Issue by Daniela1986** [backend-br/vagas#1920]
Busco seis profissionais para trabalharem com Ruby on Rails ou Clojure.
Empresa voltada a sistemas financeiros.
Interessados em saber mais detalhes: daniela.lamonica@potencialrh.com.br

**Comment by lucasfonsecads** [comment]
Qual o local da vaga?

**Comment by Daniela1986** [comment]
São Paulo, com flexibilidade em trabalhar home office

 

De: Lucas Miranda <notifications@github.com> 
Enviada em: quarta-feira, 4 de dezembro de 2019 11:57
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Daniela1986 <daniela.lamonica@potencialrh.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] Desenvolvedor Ruby on Rails (#1920)

 

Qual o local da vaga?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
