### ISSUE TITLE
[Rio de Janeiro] Vaga Estágio em Desenvolvimento Back-end [Fattoria]

### ISSUE THREAD

**Issue by CarolPimentel** [backend-br/vagas#1921]
Estágio em Back End

A Fattoria é uma empresa de tecnologia, com sólido conhecimento no mercado digital. Atuamos da criação da marca, planejamento da campanha de marketing digital até o desenvolvimento de um sistema escaláveis e aplicativos mobile.

Função: Auxílio no desenvolvimento back-end de Sistemas Web e Aplicativos Mobile.

Conhecimentos: JPA, Spring, Angular/React,  SQL e Banco de Dados NOSQL.
Diferenciais: Arquiteturas baseadas em Microserviços, Docker e ApisREST

Cursando a partir do 3º período de Ciências da Computação, Análises de Sistemas e afins.

Contrato através do CIEE, com seguro de vida.
Bolsa: R$1.250,00 
Carga horária: 6h/dia, de segunda a sexta
Benefícios: VR e VT.

Os interessados deverão encaminhar o currículo para rh@fattoriaweb.com.br com o assunto Eback

Boa sorte!

**Comment by davi-dv** [comment]
aceita remoto?

**Comment by CarolPimentel** [comment]
Olá, boa tarde. No momento não, precisa ser presencial.

Att.

Em qui., 2 de jan. de 2020 às 13:58, silvadavi <notifications@github.com>
escreveu:
