### ISSUE TITLE
[São Paulo] Backend Developer na FANATEE

### ISSUE THREAD

**Issue by laizeamon** [backend-br/vagas#1924]
Sobre a vaga
O time de desenvolvimento da Fanatee é responsável por planejar, escrever e manter o código de programação dos nossos jogos. Como membro desta equipe você vai trabalhar com programadores experientes, além de interagir com times de produto, design e BI.

 

Como Software Engineer, estas serão suas principais atividades:
Trabalhar na programação dos jogos, seja no desenvolvimento de protótipos, em novos jogos ou na manutenção dos jogos existentes;
Atuar na otimização e na solução de bugs nos jogos e sistemas relacionados;
Pesquisar soluções para problemas e desafios técnicos;
Interagir com os times de produto em reuniões de briefing e acompanhamento.
 
Requisitos
Bacharelado em Ciência da Computação (ou áreas relacionadas) ou experiência de trabalho equivalente;
4+ anos de experiência prévia em desenvolvimento de sistemas de backend;
Domínio pleno de duas ou mais linguagens de programação;
Sólidos conhecimentos em programação orientada a objetos, design patterns, programação assíncrona, multithread;
Profundo conhecimento/experiência com arquitetura de dados com preferencia pela tecnologia .NET;
Sólidos conhecimentos de Javascript, HTML e tecnologias web.
Experiência em DDD;
 

Não são requisitos, mas serão considerados diferenciais:
Conhecimentos de banco de dados não relacionais (ex:MongoDB) e conceitos de Big Data;
Familiaridade com a infra-estrutura da AWS;
Experiência com vuejs
Ser apaixonado por jogos.
 
O que oferecemos  
Remuneração competitiva.
VR + VT.
Assistência Médica e Odontológica.
Ambiente (e Dress Code) descontraído.
Uma sala para necessários momentos de descanso, cheia de snacks, frutas e bebidas
 

Sobre a Fanatee
Somos uma startup fundada em 2013 e, desde então, nos dedicamos para que as pessoas possam jogar games a qualquer hora e em qualquer lugar. Somos perfeccionistas, guiados por dados e nosso talento consiste em transformar ideias em business: não à toa temos títulos de sucesso em nossa história, incluindo os aplicativos Stop e CodyCross, que juntos contam com mais de 120 milhões de downloads feitos ao redor do mundo. 

O mundo digital nos permitiu realizar nosso sonho: passar o dia todo em volta de pessoas talentosas, criando produtos que levam diversão e conteúdo à muitas pessoas ao redor do mundo!

Se identificou com a nossa cultura e objetivo? Então se candidate e venha fazer parte do time Fanatee!

https://fanatee.com/#op-357410-software-engineer-fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
