### ISSUE TITLE
[São Paulo] Data Engineer at FANATEE

### ISSUE THREAD

**Issue by laizeamon** [backend-br/vagas#1925]
We are looking for an experienced Data Engineer who can help build data engineering solutions that process millions informations a day using AWS technologies. In this role, you will interact and work across multi-disciplinary teams: game design, art, engineering and user acquisition. 

**RESPONSIBILITIES:**

Work with large amounts of data; 

Build and improve the ETL using programming languages (preferably scala, java, c#) & Big Data tools/frameworks;
Improve monitoring and alerting capabilities to ensure data quality;
Build and expand our Data Warehouse & Data Lake;
Optimize the performance of data models;
Research and develop new methods, tools, and technologies;
Develop SQL queries to extract/organize data from different sources (Oracle, Data Warehouse, Hadoop, cloud applications) and make it available for data analysts.
 

**DESIRED SKILLS AND EXPERIENCE:**

+4 years of previous experience with Business Intelligence or Software Development;
Experience in analyzing large datasets, preferably in a Hadoop or Spark environment, and deploying production-ready systems at scale;
Experience with some or all of the following: machine learning, statistics, experimental design, data mining, predictive modeling, deep learning is a plus;
Strong programming experience, manipulating and analyzing data (Java and Python);
Demonstrable ability to work in a dynamic environment, and to meet changing deadlines and priorities on multiple simultaneous projects;
Comfortable manipulating, transforming, and analyzing complex, high-volume, high-dimensionality data from varying sources;
Strong written and oral communication skills;
Enjoy working in both individual and team settings;
Passionate, self-motivated and capable of self-direction;
Good team player.
Strong passion for gaming;
BS in Computer Science, Math, Statistics, Economics, or other technical field; advanced degrees strongly preferred;
Advanced English;
 
**WHAT WE OFFER**

Competitive remuneration.
VR + VT.
Health and Dental Insurance.
Casual environment and dress code.
A space for resting moments, full of snacks, fruits, and drinks. 

**ABOUT FANATEE**

Fanatee is a mobile gaming startup founded in 2013. Since then, our goal has been to enable people to play our games anytime, anywhere. We believe that quality is the key to success. 

Our creative processes are well planned and carefully detailed, and our talent lies in turning great ideas into great businesses: our games hit over 120M downloads worldwide.

Our dream allows us to do what we love the most: work with talented, passionate people and give them the opportunity to achieve goals as big as they can dream of.

If you want to share this ride with us and join a lightweight, fun and focused environment that breathes innovation and game culture, apply now!

https://fanatee.com/#op-348196-data-engineer

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
