### ISSUE TITLE
[SÃO PAULO] Desenvolvedor .Net na Confitec

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#1927]
A Confitec é uma empresa de Tecnologia da Informação especialista no ramo de Seguros e buscamos um novo Dev para fazer parte do nosso quadro interno. 

Requisitos necessários: 
.NET 4.5
C#
Entity Framework
Dapper
SQL Server
WebAPI
GIT

Você se destaca caso conheça:
AngularJS
Angular 7
IONIC 4
PWA
NPM/NVM

Contratação: CLT. 
Benefícios: Vale Refeição, Vale Transporte, Plano de Saúde, Plano Odontológico, Horário Flexível, Programa de custeio e incentivo a certificações, Day Off no mês do aniversário, Dress Code livre, sala de descompressão, campeonato de futebol e poker. 

Local: zona sul de SP (ao lado do Morumbi Shopping). 

Cv's com pretensão salarial (CLT) devem ser enviados para: juliana.leite@confitec.com.br.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
