### ISSUE TITLE
[SÃO PAULO] Engenheiro de Dados Júnior

### ISSUE THREAD

**Issue by fcjonas** [backend-br/vagas#1928]
Já imaginou trabalhar em uma das maiores companhias do mundo? Em um setor inovador e de extrema importância?
A AMBEV está buscando um DATA ENGINEER JUNIOR para crescer junto e ser um dos futuros líderes da área! Para isso, precisará encontrar insights capazes de transformar o modo de toda companhia operar.

### **Responsabilidades**

- Especificação técnica dos projetos de dados;
- Extração de dados dos sistemas origem
- Carga de dados na nuvem;
- Organização do Data Lake da Companhia;
- Melhoria contínua da plataforma de dados.

### **Buscamos um talento que domine**

- Conhecimento de ferramentas de transformação e processamento de dados (DataBricks, Hive, Data Factory, etc.);
- Familiaridade com ferramentas de CI/CD, versionamento de código, documentação, etc.;
- Conhecimento de bases de dados relacionais (MS SQL Server, PL/SQL), não relacionais (MongoDB, Cassandra, etc) e de ferramentas de Big Data (HDFS, Hadoop, ferramentas análogas, de mercado ou open source).

### **...e é muito importante que você tenha**

- Inglês avançado ou fluente;
- Ambição e grande vontade de crescer na carreira dentro da empresa;
- Pensamento analítico e grande vontade de analisar dados de forma avançada para mudar a forma como fazemos e vendemos nosso produto;
- Gostar de encontrar soluções novas e melhores para resolver problemas;
- Facilidade para aprender e curiosidade de um autodidata;
- Flexibilidade para se adaptar às mudanças de situações e prioridades;

A contratação será feita em regime CLT, para atuar de forma presencial na Avenida Presidente Juscelino Kubitschek, em São Paulo. Para mais informações, acesse a página da vaga: http://byintera.in/5h ou fale com nosso Hunter: https://www.linkedin.com/in/jfcornelio/.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
