### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Python (Editora Globo)

### ISSUE THREAD

**Issue by dlimasouza** [backend-br/vagas#1929]
**Descrição da vaga** 
Estamos reforçando o time de desenvolvimento da redação para criar ferramentas pra produção de conteúdo e produtos para sites da Editora Globo (jornal O GLOBO / jornal EXTRA / revista ÉPOCA). O trabalho é feito de forma integrada à redação, num time interdisciplinar voltado para infografia, visualização de dados, storytelling e inovação em jornalismo web. O time é pequeno e espera-se que o(a) desenvolvedor(a) tenha muita autonomia, com liberdade para influir de forma decisiva em muitos aspectos do trabalho. É crucial também um forte espírito colaborativo. 

**Requisitos obrigatórios** 

- Git  
- Python 
- Django 
- REST APIs 
- Bons conhecimentos sobre a AWS 
- PHP 
- Servidores web: Apache, Nginx 
- Linux 
- ferramentas de deploy automático  
- Experiência com bases de dados relacionais (mysql)  
- Inglês: facilidade em leitura de documentação e artigos 

**Habilidades desejáveis** 

- Capacidade analítica e senso crítico 
- Familiaridade com as culturas Agile e DevOps 
- Experiência com ferramentas de deploy automático 
- Familiaridade com linha de comando e ambiente Linux 
- Se interessar por jornalismo, dataviz e/ou storytelling com dados 

Experiência 
Pleno 

**Contratação** 
Regime CLT 
Local: Rio de Janeiro - Centro 

**Como se candidatar** 
Enviar e-mail com CV para daniel.lima@oglobo.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
