### ISSUE TITLE
[São Paulo] Back-End Developer na REDE (Grupo Itaú-Unibanco)

### ISSUE THREAD

**Issue by izabela-ugolini** [backend-br/vagas#193]
**## O que buscamos?**

ANALISTA de SISTEMAS PL

Experiência com desenvolvimento Java;
Imprescindível: Java, Shell script, sql procedure;
Banco de dados: Oracle, SQL, Sybase
Sistema Operacional: Unix
Diferencial: Conhecimento em C#, .Net, Asp

**## Local**

Escritório, 8h às 17h, Barueri - São Paulo

**## Benefícios**

Auxilio Refeição
Auxilio Alimentação
Auxilio Creche
Cesta Natal
Vale Transporte
Fretado
Plano Médico
Plano Odontológico
Farmácia
Academia
Previdência Privada
Seguro de Vida
Bolsa Auxilio após 12 meses
Entre outros.

**Obrigatórios:**

Desenvolvimento Java, Shell script, sql procedure;

**Desejáveis:**

Banco de dados: Oracle, SQL, Sybase
Sistema Operacional: Unix

**Diferenciais:**

Conhecimento em C#, .Net, Asp

**## Contratação**

CLT full

**## Nossa empresa**

A Rede é uma das companhias líderes no mercado nacional de meios de pagamento eletrônico, responsável pelo credenciamento, captura, transmissão, processamento e liquidação financeira de transações com cartões de crédito e débito.

Para oferecer serviços cada vez mais focados nas necessidades de seus clientes, a empresa evoluiu seu modelo de negócios para uma plataforma multisserviços que oferece soluções como: antecipação de recebíveis*, consulta de cheques* e disponibilização de terminais, além de captura e processamento de cartões de benefícios (voucher) e de lojas (private label).

Como se candidatar
Por favor envie um e-mail para izabela.ugolini@randstad.com.br com seu CV anexado - enviar no assunto: Vaga Back-End Developer REDE

**Labels**
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
