### ISSUE TITLE
[Remoto, Floripa] DevOps Engineer na Nash

### ISSUE THREAD

**Issue by lucianoengel** [backend-br/vagas#1930]
Nash é o único projeto de blockchain TOP100 mundial com co-fundadores brasileiros.
Website: https://nash.io/

Our goal at Nash is to make trading, holding, and interacting with cryptocurrencies accessible to everyone. We are looking for Platform engineers (remote) to assist with the deployment of our exchange matching engine, settlement layer, and APIs. You should be well versed in best practices for deploying, monitoring, and updating highly secure systems.

Requirements:

- Build infrastructure for the secure deployment and monitoring of our exchange services.
- Document your work thoroughly so that others can work with and build upon it.
- Engage in test-driven development practices.
- Work asynchronously with a fully remote team.

We are looking for:

- 2+ years managing cloud infrastructure in a prior role.
- 2+ years in a backend or frontend engineering role.
- Experience managing cloud provider services (e.g., AWS GCP) using Terraform.
- Experience deploying highly secure systems (such as financial software).
- Experience managing cloud provider services (e.g., AWS GCP).
- Extensive knowledge of Kubernetes, microservice deployments, and CI/CD (Gitlab)
- Experience with managing distributed systems in Elixir.

We prefer but don't require:

- 1+ years experience working with Elixir.
- Experience working in remote teams.
- A history of contributing to open source software.
- Experience working with OTP, Ecto, and Plug.
- Familiarity with Elixir typespecs.

Contrato PJ - R$ 20.000,00 - R$ 25.000,00

contact: luciano@nash.io

**Comment by alaxalves** [comment]
Is this still available?

**Comment by canesin** [comment]
@alaxalves yes, this position continues open.
