### ISSUE TITLE
[Diversos] Vaga Back-end na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [backend-br/vagas#1933]
## Descrição da Vaga

Estamos procurando desenvolvedores(as) de todos os níveis para exercer posição full-time e presencial.
Os projetos se dividem em times autogerenciáveis desenvolvendo para startups e grandes empresas brasileiras e estrangeiras. Você terá autonomia para decidir junto aos seus pares o melhor curso de ação em cada projeto e ter parte na decisão de quais tecnologias melhor se adaptam a cada necessidade.

### Local

Estamos presentes em 12 cidades pelo Brasil, estamos expandindo para a cidade de Florianópolis e procuramos pessoas para embarcar com nós nessa jornada e nos ajudar a crescer em mais uma cidade.

### Benefícios

- Plano de saúde e dental.
- Auxílio transporte.
- Vale-refeição ou alimentação de R$ 30,00/dia.
- Ambiente de trabalho descontraído.
- Acesso a cursos e portais de educação como Ruby Tapas
- Vale para aulas de inglês para aperfeiçoamento.
- Diferenciais
- Horário flexível.
- Oportunidade de trabalhar em projetos nacionais e internacionais.
- Flexibilidade para contribuir em projetos opensource.
- No dress code.

#### Obrigatórios:

Pelo menos 1 ano de experiência de desenvolvimento back-end em **Ruby** e **Ruby on Rails**
Interesse em aprimorar suas habilidades através da prática em diferentes projetos, incluindo projetos de clientes e open source.
Estar disposto a trabalhar em um ambiente de organização horizontal onde o "sim, senhor" não é aceito e as críticas proativas são sempre bem-vindas.

**Inglês avançado: temos clientes internacionais e a compreensão e conversação são fundamentais. Parte do processo seletivo é uma conversa para avaliarmos sua comunicação.**

#### Desejáveis:

- Experiência com Node.
- Experiência com desenvolvimento front-end (HTML, CSS, JavaScript).
- Contratação CLT. Salário a combinar.

### Nossa empresa
A Codeminer 42 é uma butique de software brasileira. Trabalhamos para startups e grandes empresas, temos diversos tipos de serviços que vão de ciclo de vida de desenvolvimento de projetos do zero a resgate de projetos.

Nossa especialidade é desenvolvimento web com Ruby on Rails e seu ecossistema satélite. Temos experiência em todos os tipos de produtos de tecnologia como e-commerces, e-learning, redes sociais, gerenciamento de conteúdo, automação de processos.

Nós começamos a operar em setembro de 2011 e já somos mais de 80 desenvolvedores em mais de 
12 cidades brasileiras.

Estamos à procura de desenvolvedores(as) dispostos a crescer e fazer a diferença.

### Como se candidatar
Por favor envie um email para become@codeminer42.com indicando a sua cidade de interesse com seu CV anexado. Site pessoal e Github são bem vindos.

PS: Temos vagas para Front-end também: 🔗[Vaga Front-end](https://github.com/frontendbr/vagas/issues/2699)

#### Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior
- Ruby
- Ruby on Rails
- Node

**Comment by JIFerreira** [comment]
Aceita remoto para Júnior?

**Comment by abnersajr** [comment]
@JIFerreira não é algo muito comum, pois acreditamos que é importante no começo da carreira estar próximo ao pessoal. Se você tem os requisitos e o **Inglês** principalmente, vamos nessa. Manda lá que nós avaliamos caso a caso 👍

**Comment by abnersajr** [comment]
Não @JIFerreira somente alocado.

**Comment by nicolauflima** [comment]
Vocês têm vaga para estagiário?

**Comment by abnersajr** [comment]
@nicolauflima dependendo da cidade sim, lembrando que é vaga alocada. Atente-se ao requisito do Inglês, ele é realmente importante.

**Comment by nicolauflima** [comment]
Onde posso me inscrever para a vaga de estagiário? Sou de Sorocaba. Tenho inglês, então não será um problema.

**Comment by nicolauflima** [comment]
Posso só enviar um email falando que é para a vaga de estágio?

**Comment by abnersajr** [comment]
Envie o e-mail para become@codeminer42.com com assunto `[CIDADE] Estágio Back-end`. Cidade substitua pela cidade que quer candidatar-se.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
