### ISSUE TITLE
[Fortaleza/CE] Desenvolvedor(a) Backend PHP/Laravel na PC4

### ISSUE THREAD

**Issue by ffpviana** [backend-br/vagas#1934]
## Sobre nós
Somos uma empresa apaixonada por inovação digital e estamos no mercado há mais de 15 anos atuando no desenvolvimento de sistemas, principalmente, no ramo do setor elétrico. Para conhecer mais sobre a gente, acesse: https://www.pc4.com.br

## A vaga
Nós estamos procurando pessoas para nos ajudar a desenvolver modernas interfaces web para nossos clientes e uso interno. Você focará nas atividades de back-end, desenvolvendo APIs e interagindo com a nossa equipe de desenvolvimento.

## Requisitos
- Conhecimento em Laravel 5.4+
- Especialista em PHP e suas tecnologias
- Experiência com API RESTful, Eloquent ORM e MySQL
- Foco na experiência do usuário.

## Nossas Especialidades
Seria ótimo se você tivesse alguma familiaridade com nossa tecnologia ou semelhantes

- Backend: PHP / Laravel
- Frontend: HTML, CSS/Sass, Bootstrap and Javascript
- Banco de dados: MySQL, MongoDB
- Cloud: AWS e Digital Ocean
- Ferramentas: Bitbucket, Jira, Zendesk, Slack

## Benefícios
Vale-Transporte, Vale-Alimentação e Plano de Saúde.

## Contratação
CLT ou PJ a combinar

## Como se candidatar
Participe do processo seletivo através do [link](https://forms.gle/FZvoWph1TeDVxMWcA): 

## Labels

- Presencial
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
