### ISSUE TITLE
[SP] Back End Sênior - iCasei

### ISSUE THREAD

**Issue by gustaum** [backend-br/vagas#1936]
## Local

Av. Chucri Zaidan 1550, 31º andar - São Paulo - CEP:04711-130 - Próximo ao Shopping Morumbi

## Benefícios

- Estacionamento;
- Seguro saúde (Omint);
- Ajuda de custo para cursos, livros e palestras (**Até R$500,00 mês**);
- Horário Flexivel;
- Excelente localização;
- Ambiente de trabalho sensacional (**http://bit.ly/escritorio-icasei**);
- Massagem todas as segundas e quartas;
- Frutas na mesa;
- Gympass;

## Requisitos

**Obrigatórios:**
- Ruby On Rails
- SQL Server
- MySQL
- MongoDB
- Docker
- Conhecimento em ferramentas GIT (Conhecimento do Terminal)

**Desejáveis:**
- Conhecimento de frameworks Js
- Experiencia com AWS e outros Cloud Services
- Experiência com serviços de mensageria
- Inglês (técnico)

## Contratação

PJ
**Faixa de Salário R$10.000,00 a R$14.000,00**

## Nossa empresa

iCasei Presentes e Intermediação de Negócios LTDA

## Como se candidatar

> Por favor preencher o formulário: **https://forms.gle/ZbMvnr8kcu2V8Zj59**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: backend@icasei.com.br

## Labels

- Alocado
- PJ
- Senio

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
