### ISSUE TITLE
[Fortaleza/CE] Estágio Programador PHP na PC4

### ISSUE THREAD

**Issue by ffpviana** [backend-br/vagas#1937]
## Sobre nós
Somos uma empresa apaixonada por inovação digital e estamos no mercado há mais de 15 anos atuando no desenvolvimento de sistemas, principalmente, no ramo do setor elétrico. Para conhecer mais sobre a gente, acesse: https://www.pc4.com.br

## A vaga
Você será responsável pelo desenvolvimento e suporte de soluções tecnológicas em sistemas que utilizam o framework Code Igniter, Zend Framework e Laravel. 

## Responsabilidades
- Corrigir eventuais bugs das nossas aplicações sempre com o auxílio do programador sênior.
- Identificar melhorias e correções nos sistemas dos nossos clientes. 
- Documentar toda e qualquer tipo de atualização do sistema;
- Monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas;
- Assegurar a manutenção e o controle das versões da aplicação.

## Requisitos
- Graduando em engenharia de software ou afins;
- Conceitos sobre lógica de programação;
- Noção de programação orientada a objetos;
-  Experiência em PHP e MySQL;
- Trabalho em equipe;
- Proativo;
- Apaixonado por desenvolvimento de sistemas e aplicativos;

## Nossas Especialidades
Seria ótimo se você tivesse alguma familiaridade com nossa tecnologia ou semelhantes

- Backend: PHP / Laravel
- Frontend: HTML, CSS/Sass, Bootstrap and Javascript
- Banco de dados: MySQL, MongoDB
- Cloud: AWS e Digital Ocean
- Ferramentas: Bitbucket, Jira, Zendesk, Slack

## Benefícios
Vale-Transporte e Vale-Alimentação.

## Salário
R$ 600,00

## Como se candidatar
Participe do processo seletivo através do [link](https://forms.gle/2AtZ3aPURszCBpk47): 

## Labels

- Presencial
- Estágio

**Comment by caiquesandrade** [comment]
Nuss, 600 pilas

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
