### ISSUE TITLE
[Vale do paraíba-SP/Remoto]Scrum Master

### ISSUE THREAD

**Issue by oliverthies** [backend-br/vagas#1938]
O que você irá fazer? 

Procuramos um Scrum Master para nos ajudar a organizar e metrificar as demandas dos times de desenvolvimento,  além disso deve ser o guardião dos princípios Ágeis dentro da empresa. 
O Scrum Master será responsável por acompanhar as demandas, ajudar o time bater metas e cumprir prazos removendo impedimentos além de atuar como facilitador. Irá participar de processos como Refinamento, Planning, Daily, Review.

Requisitos para a vaga: Conhecimentos em Inglês (desejável), Scrum, Kanban, negociação e liderança. Experiência com ambiente de desenvolvimento de software e suas tecnologias.

Vaga PJ entre R$6.5K
A princípio morar próximo a região do vale do paraíba - SP, poderá trabalhar remoto alguns dias da semana.

Contato em fullstack@climatempo.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
