### ISSUE TITLE
[São Paulo] Back-End Developer na Fliper

### ISSUE THREAD

**Issue by gbeletti** [backend-br/vagas#194]
# [São Paulo] Back-End Developer Presencial na Fliper

## Descrição da vaga
Procuramos back-end com experiência em linguagens de programação de servidores, apaixonado por buscar soluções de quebra-cabeças lógicos e que esteja afim de desenvolver algo inovador com um real propósito de impactar a vida das pessoas. Junte-se a um time muito engajado e que está sempre buscando aprender sobre coisas novas.

## Arquitetura do projeto

Aqui você terá a oportunidade de trabalhar com as seguintes tecnologias:

- Golang;
- Microsserviços;
- Google Cloud;
- Kubernetes;
- Node JS;
- GraphQL;
- MongoDB;
- RabbitMQ;
- Deploy automatizado (CI/CD);

## Local
Nossa startup fica na [We work - faria lima](https://www.wework.com/pt-BR/buildings/faria-lima--sao-paulo). Visite o site para você ver que animal o nosso ambiente.

## Requisitos
- Sólidos conhecimentos em mais de uma linguagem de programação de servidor;
- Conhecimentos em bancos de dados NoSQL;
- Conhecimentos em controle de versão com Git;
- Testes Unitários e de Integração;

## Diferenciais
- Ter trabalhado com metodologias ágeis;
- Golang;
- Kubernetes;
- Google Cloud;
- Noções de GraphQL;
- Conhecer AMQP, ter usado RabbitMQ, ou ter familiaridade com filas de mensagens.

## Perfil
Buscamos alguém pró-ativo e autogerenciável. Nossa cultura tem por base uma hierarquia horizontal onde entendemos que as entregas são responsabilidades do time como um todo e enxergamos que o trabalho colaborativo flui muito mais.

## Informações
- Salário: a combinar.
- Tipo de contratação: PJ.
- Horário Flexível.
- A vaga é presencial pois queremos você pertinho todos os dias ( :D )
- Jogos (pebolim, ping pong).
- Coworking com café liberado, comodidades, diversos eventos com comidinhas ( :D ) e cerveja das 12h às 19hs.

## Nossa Startup
Fliper é a plataforma que vai te ajudar de maneira fácil a investir bem o seu dinheiro. Simplificamos tudo! Da linguagem até as ações que você precisa fazer. 
Vamos traduzir o “financês” do mundo dos investimentos, e te dar ferramentas simples pra acompanhar o crescimento das suas economias! Totalmente independente de bancos ou corretoras estamos alinhados em te ajudar a investir cada vez melhor. Focados em tecnologia e em simplificar a vida das pessoas chegamos trazendo uma grande novidade, a consolidação da carteira de uma ou mais instituições financeiras de maneira automática. E esse é só o começo! Vamos revolucionar a forma que o mundo se relaciona com o dinheiro. Mostrando que pode ser muito mais fácil, rápido e divertido fazer o seu “pé-de-meia” crescer!

## Como se candidatar
Por favor envie um email para vagas@fliper.app com seu github e linkedin.
Enviar no assunto: Vaga back-end (Pleno|Sênior)

**Comment by gbeletti** [comment]
Por favor adicionar labels: Golang, PJ, Presencial, MongoDB

**Comment by smithaitufe** [comment]
Remote? I am in Nigeria

**Comment by gbeletti** [comment]
Sorry, It has to be here in São Paulo / BR

**Comment by smithaitufe** [comment]
Is there Visa sponsorship support for relocation?

**Comment by ghost** [comment]
Gostaria de informar que o email está com problemas. Volta com erro:

```
Hello your@email.com,

We're writing to let you know that the group you tried to contact (vagas) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/carteiraonline.com.br/bin/topic.py?topic=25838.

Thanks,

carteiraonline.com.br admins
```

**Comment by gbeletti** [comment]
Desculpa galera, a configuração do email foi corrigida, agora está funcionando normalmente.
