### ISSUE TITLE
[SP - Com Auxílio] Desenvolvedora Javascript na Liv Up

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1941]
A **Liv Up** está crescendo e precisa de você para construir novos produtos!

É tudo do início! Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para fornecer a melhor performance e experiência para os nossos **clientes em todo o Brasil**.  

Atualmente nós trabalhamos com **React.js, Node.js e React Native**. Essas tecnologias com pessoas com propósito e dispostas é o que nos faz crescer exponencialmente 40% ao ano!

A contratação é CLT e **custeamos toda a transição para SP** caso não seja daqui!

**Página da vaga:** http://byintera.in/vemserliv

**Comment by yureesantos** [comment]
Enviado! O feedback é dado em até quantos dias?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
