### ISSUE TITLE
[São Paulo] Tech Lead - Back End ou Fullstack [Estudar Com Você]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#1942]
**O que buscamos?**
_Buscamos um(a) desenvolvedor(a) Full-Stack ou Back-End de nível Pleno ou Sênior para nos ajudar a criar produtos que vão encantar nossos clientes e nos ajudar a transformar a experiência de estudo de universitários._
_A posição é de Tech Lead, mas o trabalho é mão na massa, desenvolvendo funcionalidades que vão gerar muito valor para nossos usuários!_ 

**Nossas Stacks**
Back-end: _Ruby + Rails, PostgreSQL e um pouquinho de NodeJs._
Front-end: _React, Sass, HTML 5, CSS 3, Bootstrap, Typescript e Webpack_
Infraestrutura: _AWS, Docker, Cloudflare, Gitlab e Gitlab CI_
Monitoramento: _New Relic, Sentry, Cloud Watch e Pager Duty_

**Benefícios**
Faixa salarial: _entre R$8.000 e R$12.000,00 (PJ | Presencial flexível | 44h semanais)_
_Férias remuneradas
Possibilidade de ganhar participação societária_

**PÁGINA DA VAGA:** http://byintera.in/5y

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
