### ISSUE TITLE
[Remote] Senior Software Engineer na Ubiminds (Java, Python, Node.js, SQL, MySQL, MongoDB)

### ISSUE THREAD

**Issue by Ubiminds** [backend-br/vagas#1943]
**Oportunidade para trabalhar remoto para uma empresa americana do ramo SaaS / Educação. Todo o trabalho será realizado em inglês.**

### About the job

_What you’ll do:_
- Build scalable APIs for our partners and customers to use;
- Build reliable, fault-tolerant API clients;
- Create user interfaces that help guide users through the process of managing their course information, grades, and assignments;
- Release new software every day;
- Troubleshoot problems our customers have;
- Work closely with our Product Management, Product Operations, Quality Engineering, and Design teams to help decide which features to build and how to build them.

### Where?
Our positions are 100% remote, working from Brazil with teams mainly based in the United States.

### Requirements
In order to succeed in this position, you will need:

Mandatory:
- Advanced/fluent English skills;
- Strong backend development skills;
- Strong experience with either Java, Python, NodeJS or PHP;
- Experience writing complex SQL queries;
- Be comfortable with either MySQL, MongoDB or Postgres;
- Experience with different unit testing frameworks.
- Experience with TDD is a plus.

### Hire
PJ or CLT

### Our Business
Remote teams, near collaboration. Ubiminds matches American companies and Brazilian software engineers. [Check out our blog ](http://blog.ubiminds.com/pt/emprego-dev/)for more.

### How to Apply
Here: https://ubiminds.com/senior-software-engineer/

Labels
- PJ
- CLT
- Remoto
- Pleno
- Sênior

**Comment by rkaraujo** [comment]
Hello,

I applied with the provided link, but the description was different from this message. It was related more with a frontend position.

**Comment by Ubiminds** [comment]
> Hello,
> 
> I applied with the provided link, but the description was different from this message. It was related more with a frontend position.

Thanks for letting us know! Fixed it: https://ubiminds.com/senior-software-engineer/
