### ISSUE TITLE
[Rio de Janeiro] Senior Full Stack Developer .NET no Tribunal de Contas do Estado do Rio de Janeiro

### ISSUE THREAD

**Issue by dacferreira** [backend-br/vagas#1945]
## Objetivo

Desenvolvedor de sistemas corporativos de baixa complexidade tecnológica (poucas otimizações necessárias), com poucos usuários e com diversas regras de negócio em constante evolução. Atualmente usamos a stack: dotNetCore com webAPI + Angular7, mas os candidatos não precisam necessariamente dominar essas tecnologias inicialmente. Basta conhecer profundamente os fundamentos do bom desenvolvimento de sistemas corporativos (SOLID, DDD, TDD, MVC, acoplamento e coesão) e estar disposto a aprender as tecnologias da nossa stack. 
 
 
Contratação: Imediata
 
Quantidade de vagas: 1 (uma)
 
Regime: CARGO COMISSIONADO

## Benefícios: 
 
Sálario Bruto: 9.547,68

- Auxílio refeição (sodexo): 1.064,80

- Auxílio locomoção: 314,60

- Auxílio saúde (reembolso): até 726,00

- Auxílio educação (reembolso para escola dos filhos): 1.174,00

- 13º salário

- 30 dias de férias

- 8h + 1h de almoço durante o horário comercial

- [ ] DESCONTOS (INSS e Imposto de Renda)

 
 
## Pré-requisitos
 

- Diploma de graduação em nível superior na área de TI (não aceitamos candidatos sem graduação comprovada)

- Conhecimento de boas práticas de desenvolvimento e padrões de projeto.

- Mínimo de 05 anos de experiência comprovadas na área de desenvolvimento de sistemas.

- Disposição para aprender e, eventualmente, dar manutenção em aplicações legadas em WebForms, FoxPro (similiar ao PL/SQL) e Vb.net.

 
## Experiência profissional desejável:
 

- Angular com Typescript;

- Desenvolvimento em C# e pelo menos mais 01 linguagens de programação;

- Desenvolvimento .NET (ASP.NET Core, MVC, ASP.NET WebAPI); 

- Desenvolvimento de aplicações WEB;

- Desenvolvimento utilizando Banco de Dados;
- ORMs (Entity Framework);

- Ferramentas de controle de versão (TFS / GIT); 

- Deploy em servidores de aplicação;

- Desenvolvimento utilizando Banco de Dados;

- Utilização de Injeção de dependência e inversão de controle; 

 
## Diferencial:
 

- Pós graduação

- Boa experiência com análise de requisitos

- Arquitetura de software 

- Padrões de projeto (ex.: SOLID, DDD, TDD)

- boas práticas 
 
 
## Seleção: 
 
Como forma de pré-seleção, o candidato deverá desenvolver um pequeno projeto de teste usando as tecnologias listadas em https://gist.github.com/fulvius/fd37f06445f92d35e44a371a6366d33c 
Os códigos da aplicação de teste podem ser desenvolvidos em .Net, Java, Python ou Php, contanto que aplique as boas práticas de desenvolvimento e arquitetura (SOLID, DDD, TDD). Porém a vaga é para desenvolvimento em .Net. 
NÃO SERÁ ACEITO CONTATO DE CANDIDATOS PARA ENTREVISTA SEM O DESENVOLVIMENTO DA APLICAÇÃO DE TESTE SUPRACITADA. 
Após análise do código, os candidatos serão chamados para entrevista técnica, questionando sobre o código enviado, e analisando o domínio das tecnologias empregadas, bem como avaliando os fundamentos e possíveis propostas de soluções para evolução do sistema apresentado. 
 
## Duvidas
Qualquer dúvida, enviar email para FulvioALS@tce.rj.gov.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
