### ISSUE TITLE
[Portugal] Senior Backend Software Engineer [Talkdesk]

### ISSUE THREAD

**Issue by leandrogs** [backend-br/vagas#1949]
Together at Talkdesk, we’re building a future of brilliant customer interactions. We have the cleverness, curiosity, and grit to make us a team of customer heroes: thinkers, achievers, and dreamers who believe that our world-class SaaS platform can influence a new kind of customer interaction.

Talkdesk started from a hackathon win in 2011 and has since become one of the fastest-growing companies in the world, a Gartner Magic Quadrant Visionary, and enabled billions of customer interactions using our platform. With $124.5 million in backing from DFJ, Salesforce Ventures, Storm Ventures, and Viking Global Investors and supported by the successes of our 1,800+ customers from IBM, Acxiom, Discovery Education, and Peloton, Talkdesk is disrupting a $40+ billion stagnant market.

We’re now looking for the new members of the Talkdesk family - those ambitious, driven, and collaborative individuals who thrive in a fast-paced environment and will push us to do even greater things together. If you would like to help us shape the future of Talkdesk, come along with us on our journey - your dream job is waiting!

 

**Responsibilities:**

- Work independently as well as in small teams to develop the best product on the market
- Implement a scalable, stable, and user-friendly product that can handle our current growth
- Collaborate with experienced software engineers in the design, development and maintenance stages of the Talkdesk product
- Collaborate with our support engineers and customer support representatives to understand our customers' needs, enhance Talkdesk usability and resolve technical issues
- Work well in a modern agile software engineering environment (with source code control, dev/stage/prod release cycle, extensive testing, and continuous deployment)
- Solve challenging technical problems and put your skills to the test every day; see an immediate impact of your work and value you created for customers

**Required Skills:**

- Software engineering background with experience in OO programming and TDD
- Top-notch programming skills, ability to produce quality code that is maintainable, efficient, reliable and secure
- Be fearless about learning new technologies and technical approaches to application development
- Good written and spoken English
- +5 years of experience 

**Nice to haves / Pluses:**

- Familiar with Kotlin or Elixir, Spring, unit and integration testing, Redis, RabbitMQ, and Postgres
- BS/MS Degree in Computer Science, Applied Math, or an engineering-related field
- Experience in Agile development methodology/Scrum

**Application**

Send resume to isabelle.veiga@talkdesk.com or apply in our [career page](https://www.talkdesk.com/careers)

Labels

- Senior
- Backend
- Fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
