### ISSUE TITLE
[São Paulo - SP] - Software Engineer Pleno na Creditas

### ISSUE THREAD

**Issue by VitorChaves21** [backend-br/vagas#1950]
**CREDITAS**

**A maior empresa de crédito online do Brasil** está crescendo ainda mais e precisa de você para fazer parte dessa transformação digital.

**Seja parte de um grande desafio!** Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir os novos modelos de negócio da nossa empresa. Tudo isso para fornecer a melhor performance aos nossos clientes!

Atualmente nós trabalhamos com **Java** e o **Kotlin** é um diferencial bacana. Estamos nos atualizando então **integrações API** fazem parte do nosso dia a dia. Essas tecnologias com pessoas de propósito e dispostas é o que a crescer junto com a gente é o que fará a diferença!

A contratação será feita em **regime CLT alocado na sede da Creditas na Itaim Bibi em São Paulo** 

Página da vaga: http://byintera.in/i

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
