### ISSUE TITLE
[SALVADOR - BA] DevOps Engineer na Wex Brasil

### ISSUE THREAD

**Issue by ronirhwyser2017** [backend-br/vagas#1951]
Index/Apresentação:  

Maior empresa de Meio de Pagamento Corporativos do mundo, procura por pessoas analíticas, ótima conhecimento e potencial para atuar como DevOps, atrelado a uma comunicação em inglês e vasta experiência, para atuar em soluções, suporte, projetos e paixão com desenvolvimento, infraestrutura, banco de dados focado em meios de pagamento, para influenciar, implantar, migrar complexos ambientes para nuvem, atuando em um novo centro de desenvolvimento de softwares (Fabrica de Software), reportando diretamente para USA e operando de Salvador-BA.

- Inglês Avançado necessário devido a report para USA;
- Experiência solida atuando com Azure Devops, Chef, Docker, terraform, AWS, Ansible, Jenkins e/ou Chef;

-DESCRIÇÃO DO CARGO
·Auxiliar as equipes de Desenvolvimento e Infraestrutura a evoluir para 100% de automação e introduzir ambientes ainda não automatizados a tal realidade;
·Projetar e criar ambientes AWS usando fluxos de trabalho automatizados (infra codada);
·Contribuir para o desenvolvimento e manutenção da arquitetura do aplicativo e garantir que todo o desenvolvimento esteja em conformidade com os padrões;
·Analisar, projetar, programar, depurar e modificar aprimoramentos de software e / ou novos produtos locais, em rede ou relacionados à Internet;
·Desenvolver planos de conversão e implementação de sistema;
·Recomendar alterações nos padrões de desenvolvimento, manutenção e sistema;
·Planejar, projetar, desenvolver e testar bibliotecas de scripts para automatizar os ambientes em nuvem;
·Trabalhar com equipes de arquitetura e líderes técnicos, traduzindo requisitos em projetos e fluxos de trabalho automatizados;

-O CANDIDATO
·Sólida experiência em desenvolvimento voltado para automação e construção de ambientes DevOps;
·Amplo conhecimento e experiência com a metodologia ágil (Design Thinking Diferencial);
·Trabalhar em um ambiente colaborativo e ágil para criar, implantar, configurar e manter;
·Experiência de trabalho com Azure Devops, AWS Cloud Formation, Terraform, Ansible, Chef, Jenkins e/ou Docker;
·Experiência em scripts em Python, Ruby, Perl ou Bash;
·Projetar e implementar ferramentas para implantação e monitoramento automatizados de vários ambientes;
·Solucionar problemas nas instâncias de desenvolvimento, teste e produção;
·Formação Superior completo em Sistemas de informação, Ciências da computação ou relacionado;
·Inglês avançado para conversação (reporte aos EUA);

COMPETÊNCIAS COMPORTAMENTAIS
·Capaz de trabalhar em ambiente de alto constante e rápida mudança; (Resiliência)
·Perfil relacional para colaborar de forma funcional com diferentes áreas e hierarquias; (Comunicação)
·Profissional que leva os projetos ao fechamento com um mínimo de orientação e supervisão (Ownership)
·Possuir fortes habilidades técnicas e solução de problemas; (Analítico)

-OFERTADO
Um crescimento dado por paixão pela inovação continuada e busca em um nível de serviços incomparável no segmento, atrelado a oportunidade de exposição e movimentação internacional.
Contratação CLT + Bônus + Assistência Medica e Odontológica + Seguro de Vida + VA/VR...

##Labels
-Pleno
-Sênior
-Backend
-DevOps
-Python
-Ansible
-Terraform
-AWS

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
