### ISSUE TITLE
[São Paulo - SP] Software Developer - Finance at Hash

### ISSUE THREAD

**Issue by femariotti** [backend-br/vagas#1952]
<h2><strong>Product and Technology</storng></h2>
<h3>We are constantly seeking people that want to change the way the payment market is structured today. We are building a new infrastructure that allows the entrance of new payment players on a R$1.4tri market dominated by a few companies for the past 15 years. We do this by offering a platform where any company can be their own payment service.

To build this infrastructure, we need to build an amazing and scalable product. We need the best developers. "Move fast and break things" doesn't really work for the type of system that we build. We tend to reduce technical debt and prioritize quality over a fast release.<h3>

<h2><strong>About the role</strong></h2>
<h3>Hash creates technologies that allows companies of any size to easily access the financial market and create amazing solutions with fewer costs & bureaucracy. We strive to deliver all the necessary infrastructure, so companies can raise the bar on payments and banking solutions. The Financial Infrastructure team is small, and focuses on building and maintaining a reliable set of core microservices that ensures everyone is paid correctly. More specifically, we are responsible for:
<strong>*Payments related products like dynamic fees, payment splits, etc.
*Banking related products, like our digital wallets, money transfers, etc.
*Ensuring accounting is done right.</strong>
Today, Hash is growing really really fast, and for us that means keeping everything running smoothly, simultaneously splitting a monolith and offering better solutions for our clients.</h3>

<h2><strong>What we are looking for</strong></h2>
Software Developers who care about the things they do, about the people they impact and that strive for well written software.

<h2><strong>Requirements</strong></h2>

<h2><strong>You may apply if you:</strong></h2>
<h3><strong>*Naturally empathize with people. You care about how our clients use (or “misuse”) our products. You are interested in having contact and helping other teams (like our Support team, with which we are constantly in contact, and other techs teams alike)
*Understand the need for transparency and clarity in your work-related interactions, and you voice your ideas and concerns when they come up. This is very important for us, as we believe transparency is the core of building trust and long-lasting relationships.
*Care about code quality and test coverage, and know how it impacts productivity and helps everyone on the team sleep at night. Our work relies heavily on financial calculations, so it’s critical for us to ensure everything is working as it should.
*Believe that products are more than code and you like being involved from start to finish. From research and ideation to final product delivery, Tech teams at Hash are involved every step of the way. Taking ownership over what you build means that, beyond code, you’ll do your best to see your work succeed and run smoothly</strong></h3>

<h2><strong>We might like you even better if you:</strong></h2>
<h3><strong>*Are familiar with concepts like Docker, CI/CD, Message Queues, RPC.
*Have familiarity with Node.js, TypeScript, or Go (don't worry, you can learn them here!)</strong></h3>

<h2><strong>Benefits</strong></h2>
<h3>Opportunity to build a product with high impact and scale on the market
Competitive compensation package

Health, dental and life insurance; Meal allowance (“vale refeição”);
Flexibility to choose your own custom setup (computer, monitors, tablet, etc.); 
Subsidy to sports practicing; 
*Subsidy for education purposes.</h3>

<strong>You can send an e-mail to felipe.mariotti@hash.com.br to apply
Cya =)</strong>

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
