### ISSUE TITLE
[São Paulo] Engenheiro de Dados Júnior na Ambev

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1953]
A **Ambev** está crescendo e precisa de você para **construir sua nova área.**

**É tudo do início!** Estamos desenvolvendo a área de dados e para isso buscamos a melhor arquitetura e as melhores tecnologias para construir uma infraestrutura sustentável, escalável e consistente à longo prazo. Tudo isso para fornecer a melhor performance e experiência aos nossos clientes, nos mantendo como **maior cervejaria do mundo!**

Atualmente nós trabalhamos com **Python** e **SQL** para o processo de **ETL**. Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos faz estar e nos mantermos no topo. Serão bem vindos também conhecimentos em BD não relacionais, Hadoop, Hive e CI/CD.

A contratação será feita em **regime CLT**  e o trabalho de forma presencial. Estamos na **Avenida Presidente Juscelino Kubitschek**, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://byintera.in/vemserambev

## Labels
Junior
Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
