### ISSUE TITLE
[São Paulo] Engenheiro(a) de Software no BTG Pactual

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1954]
O **BTG Pactual** precisa de você para construir um novo produto!

**Participe do início!**  Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir os **novos modelos de negócio** do Banco. Tudo isso para fornecer a melhor performance e experiência para nossos clientes em todo o mundo!

Atualmente nós trabalhamos com **C#, .NET e Java**. Estamos nos atualizando então integrações **AWS e Metodologias Ágeis** também fazem parte do trabalho. Essas tecnologias com pessoas de propósito e dispostas é o que nos faz ser o **maior banco de investimentos da América Latina**.

A contratação será feita em regime CLT e nós estamos na Faria Lima.

Página da vaga: http://byintera.in/21

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
