### ISSUE TITLE
[Fortaleza - CE] Desenvolvedor .NET Junior na Izysoft

### ISSUE THREAD

**Issue by barbarapxto** [backend-br/vagas#1955]
## Local

 Escritório/Presencial, Fortaleza - CE

## Benefícios

- Ticket alimentação;
- ticket refeição; 
- Auxílio transporte;
- Assistência médica.

## Requisitos

- Formação em andamento ou concluída em Análise e Desenvolvimento de Sistemas ou cursos da área de TI.
- Capacidade analítica;
- Autogerenciamento e foco/concentração;
- Senso de priorização/urgência;
- .NET Framework 3.5 ou superior;
- Visual Studio 2015 ou superior;
- ASP.NET, C# e/ou VB.NET;
- SQL Server;
- HTML e Javascript.

## Contratação

CLT Full

## Como se candidatar

Por favor, envie o currículo para o e-mail barbara@izysoft.com.br, com o Assunto "Vaga Desenvolvedor .NET Junior".

**Comment by daviholandas** [comment]
Vaga aberta ainda? 5 meses do anúncio...
