### ISSUE TITLE
[São Paulo - SP] Analista de Testes na Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#1956]
Estamos à procura de um profissional com perfil Junior para atuar como Analista de Testes em um projeto indeterminado. 

Presencial, Escritório - Real Parque, Morumbi. 

Requisitos: 
•	Superior completo ou cursando em TI; 
•	Experiência com a elaboração de casos de testes, conceito de teste e qualidade de software e conhecimento em ferramentas de bug tracker (Mantis ou Similares);
•	Conhecimento em ferramentas de ALM (JIRA, Testlink ou Similares).
•	Experiência de 1 ano 

Benefícios:
VR, VT, AM, AO e SV. 

Labels
CLT
JUNIOR
Presencial

Interessados enviar CV para: talento@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
