### ISSUE TITLE
[São Paulo] Data Engineer Senior na Pag!

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1957]
A **Pag!** está nascendo e precisa de você para **construir um novo banco**.

**É tudo do início!** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que dos nossos clientes, atualmente nós já **ultrapassamos a marca de 6 milhões** de pedidos de cartões!

Atualmente nós trabalhamos principalemente com **Python, Spark, e AWS**(mas conhecimentos de outros ambientes é bem vindo também). Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos faz crescer exponencialmente! Serão bem vindos também conhecimentos em **Docker, Batch e Streaming**.

Formas de contração, local e mais informações acessar a página - http://byintera.in/vemserpag

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
