### ISSUE TITLE
Front-End _ UX

### ISSUE THREAD

**Issue by Daniela1986** [backend-br/vagas#1958]
	Experiência em programação Front-End (React, HTML e CSS);
	Experiência em designer de interfaces para web e para aplicações mobile;
	Experiência com arquitetura da informação / designer de interação

Empresa no segmento financeiro:
Atuação em São Paulo
Interessados enviar CV para: daniela.lamonica@potencialrh.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
