### ISSUE TITLE
[São Paulo] Desenvolvedor back-end para projeto .NET Core

### ISSUE THREAD

**Issue by apantaliao** [backend-br/vagas#1959]
Olá, tudo bem? 

Seja muito bem-vindo(a) à nossa vaga! Antes de mais nada, vamos deixar algumas coisas claras: 

- A vaga é para pessoas com alguma experiência em programação. Por isso colocamos pleno / sênior. Mas dentro do nosso time, no dia-a-dia, não usamos muito esta terminologia. 
- A vaga é presencial, mas com horário flexível. Estamos no centro de SP, na República. 
- O projeto é mais back-end, com C#, .NET e .NET Core. Mas embora este projeto seja mais focado nestas tecnologias, conhecimentos  JavaScript, TypeScript, Rails são bem-vindos. Eles não são necessários para o projeto,  mas mais do que conhecimento específico em uma plataforma queremos que seja uma pessoa que goste de programar, de fazer testes unitários e de fazer software bem feito!
 
Para se inscrever, [acesse aqui](https://recruiterflow.com/vizir/jobs/7?source=BackEnd-BR).
 
**Benefícios**
Ticket refeição: R$ 31,50 por dia (R$ 661,50 por mês) pago em dinheiro;
Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou para onde quiser. Após dois anos, o notebook ficará para você;
Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
Plano odontológico Odontoprev;
Seguro de Vida no valor de R$ 60.000,00.

**Requisitos**
- Conhecer bem uma linguagem de programação, boa lógica e orientação a objetos.
- Estar a fim de aprender.
- Ser comprometido em entregar projetos com qualidade.
- Curtir programar.

Esta vaga é preferencialmente presencial.  Mas se por acaso for remoto, pode se candidatar nesta [vaga aqui](https://recruiterflow.com/vizir/jobs/2?source=BackEnd-BR).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
