### ISSUE TITLE
[Campinas] Back-End Developer na [Petra Group]

### ISSUE THREAD

**Issue by prisciladiasromeu** [backend-br/vagas#196]
Back- End Developer PL

Suas responsabilidades serão voltadas para desenvolvimento de aplicação web. Além disso, estará em contato com o cliente, que é multinacional.

Competências e Experiências necessárias:
- Superior Completo em Ciência da Computação, Sistemas de Informação, Engenharia da Computação, Engenharia Elétrica/Telecomunicações ou áreas afins  
- Experiência em desenvolvimento de componentes utilizando Spring (Data, Security, Boot), JSF (Primefaces/ IceFaces, etc) e Web services RESTful  
- Experiência em mapeamento objeto relacional com JPA (Hibernate) e banco de dados (MySQL)  
- Experiência com gerenciamento de dependências (Maven) 
​- Inglês intermediário/avançado​​ Diferenciais 
- Conhecimento em self testing code (JUnit) 
- Conhecimento de JavaScript, CSS, emberjs, angularjs 
- Conhecimento de ferramentas de controle de versão e configuração (git, svn) 
- Experiência com desenvolvimento ágil de software (Scrum)

Contratação CLT

Oportunidade para Campinas, São Paulo.

Mandar currículo para priscila.dias@petraexec.com.br com o assunto: Desenvolvedor Back-End Pleno

**Comment by vanilsonsantos** [comment]
Olá, possibilidade de trabalho remoto?

**Comment by prisciladiasromeu** [comment]
@vanilsonsantos apenas presencial, mas me encaminha seu currículo para futuras oportunidades.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
