### ISSUE TITLE
[CURITIBA] Back-end Developer na Celero

### ISSUE THREAD

**Issue by vinicoelho1074** [backend-br/vagas#1960]
Somos uma startup curitibana que quer revolucionar a maneira com que as pequenas e médias empresas fazem a gestão de suas finanças através da tecnologia! 
 
Estamos buscando **BACK-END DEVELOPER** para nosso time interno que irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma.
 
Aqui na Celero, você trabalhará com **Python** e **Django** no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e um método de trabalho ágil. Além disso, você terá muita liberdade para desenvolver e por isso procuramos alguém com perfil proativo e que goste de ter autonomia! :)
 
**O que esperamos de você?**
- Experiência anterior com Python 3 + Django;
- Conhecimentos com modelagem e consumo de API's REST;
- Experiência com Git para versionamento de código.
 
**O que te diferencia?** 
- Ter formação em Ciência da Computação ou equivalente;
- Ter experiência com Testes unitários;
- Modelagem de bancos de dados relacionais (preferencialmente PostgreSQL)
- Experiência anterior com NoSQL;
- Ter conhecimentos com AWS e/ou Google Cloud;
- Ser autodidata;
- Conhecer o ambiente de startups;
- Experiência na área de gestão financeira;
- Boas práticas de programação;
- Design Patterns;
- Ter experiências anteriores com microsserviços.
 
**O que utilizamos?** 
- Métodos ágeis (práticas de Scrum e Kanban);
- Python 3 + Django 2 + Django REST Framework;
- Git (Github);
- PostgreSQL;
- MongoDB;
- MonetDB;
- AWS;
- Google Cloud Platform.

Local de trabalho: Curitiba-PR

Se identificou? 💚 Candidate-se pelo link: abler.in/v5684

**Comment by BrunoMoreno** [comment]
A vaga é só presencial?

**Comment by marlonleite** [comment]
Aceita remoto?

**Comment by vinicoelho1074** [comment]
@marlonleite e @BrunoMoreno Bom dia! Essa vaga em específico somente presencial.

**Comment by cleberzavadniak** [comment]
Essa vaga já está fechada? O link do Abler dá na página inicial.
