### ISSUE TITLE
[Mogi das Cruzes/SP] Analista Desenvolvedor JAVA Jr/Pl

### ISSUE THREAD

**Issue by oliviaaversa** [backend-br/vagas#1961]
A Yank Solutions está com nova oportunidade!! Vem fazer parte de uma Great Place To Work!!

Analista Desenvolvedor JAVA Jr./Pl

Atividades:
-Atuar em cliente de grande porte (ramo de aluguel de carros);
-Desenvolvimento de software (automação) em Java;
-Especificação de Regras de Negócio junto ao cliente.

Requisitos:
-Formação em Análise de Sistemas, Ciência da Computação, Engenharia da Computação ou áreas correlatas;
-Inglês intermediário;
-Experiência em desenvolvimento de software;
-Sólidos conceitos de Orientação a objetos;
-Conhecimento em integração com Banco de Dados (MySQL) e WebServices RESTful;
-Vivência com elaboração de documentação técnica;
-Facilidade na comunicação e contato direto com clientes.

Diferenciais:
-Experiência profissional em desenvolvimento na linguagem JAVA;
-Conhecimento em ferramentas ou conceitos de RPA;
-Conhecimento em testes automatizados.

Localidade: Mogi das Cruzes/SP

Horário: Seg à Sex, das 9h às 18h ou das 8h às 17h.

Tipo de contratação: PJ

Salário: A combinar

Interessados enviar currículo em nosso site.
www.yanksolutions.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
