### ISSUE TITLE
[SP - São Paulo] Engenheiro(a) de Dados Senior no QuintoAndar

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1962]
Que tal o desafio de trabalhar no mais novo **unicórnio do Brasil**?

**Cresça com a gente!** Venha ser liderança de algo grande, estamos trabalhando com a melhor arquitetura e as melhores tecnologias para construir uma plataforma sempre mais sustentável, escalável e consistente à longo prazo. Tudo isso para entregar a melhor experiência para **nossos clientes em todo Brasil!**

Atualmente nós trabalhamos principalmente com **Python, Spark, e AWS**(mas conhecimentos de outros ambientes é bem vindo também). Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos fez **crescer exponencialmente!** Serão bem vindos também conhecimentos em Estruturação de Datawarehouse, Data marts e Data Lake, além de Batch e Streaming.

Formas de contração, local e mais informações acessar a página - http://byintera.in/vemserquinto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
