### ISSUE TITLE
[SÃO PAULO/SP] Devops na Cora

### ISSUE THREAD

**Issue by amandagasineo** [backend-br/vagas#1964]
Oportunidade para DEVOPS em Nova Startup Fintech

A Cora está nascendo para revolucionar e precisa dos melhores talentos Tech para construir um banco digital disruptivo e completo!

A empresa foi fundada pelos criadores da Moip (concorrente do PayPal, vendido para o Wirecard por 165 milhões) e por trás dela está o André Street, da Stone, e o Jorge Paulo Lemann, do grupo 3G Capital, investidora de marcas gigantes como iFood e Ambev. Além desse forte time de investidores, a Cora está estruturando um time de experts para enfrentar o desafio de criar a tecnologia do zero! A perspectiva é que o(a) Devops cresça exponencialmente junto com a empresa  e seja uma liderança no futuro!

Informações da Vaga:
• Local - São Paulo, SP
• Regime – CLT Efetivo, 40h semanais
• Horário – Flexivo (dia de home office durante a semana)
• Remuneração e Benefícios: Falar no privado

Link da Oportunidade: http://byintera.in/devopscorac

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
