### ISSUE TITLE
[SP - Com Auxílio] Senior Software Engineer at QuintoAndar

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#1965]
**Construir uma empresa do zero** é o algo que te motivaria?

**Lidere mudanças e produtos!** Venha ser liderança no unicórnio brasileiro, estamos trabalhando com a melhor arquitetura e as melhores tecnologias para construir uma plataforma cada vez mais sustentável, escalável e consistente à longo prazo. Tudo isso para entregar a melhor experiência para nossos clientes em todo Brasil!

Atualmente nós trabalhamos principalmente com **Python, Spark, e AWS(mas conhecimentos de outros ambientes é bem vindo também)**. Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos fez **crescer exponencialmente!** Serão bem vindos também conhecimentos em Repositórios de Dados , Ambientes Cloud e mais. 

A contratação será feita em regime CLT com horário flexível. Caso seja de outro estado ou cidade **custeamos a sua transição para São Paulo!**

Para mais informações e aplicar a vaga: http://byintera.in/vemserquinto

**Comment by danielsidev** [comment]
Olá @iagobyintera ! Tudo bem?
Sou do RJ. Essa vaga pode ser remota? =)
Abraços!
Daniel Siqueira
http://danielsiqueira.net

**Comment by iagobyintera** [comment]
@danielsidev Opa Daniel, ainda não há essa possibilidade mas caso você tenha disponibilidade e interesse em se mudar para SP, não precisa se preocupar com a parte financeira da mundaça :D

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
