### ISSUE TITLE
[São Paulo/ SP] - Senior Ruby on Rails Engineer na DogHero

### ISSUE THREAD

**Issue by VitorChaves21** [backend-br/vagas#1967]
**DOG HERO**

**Uma das mais promissoras Startups do Brasil**, que já recebeu mais de **R$18 milhões em aportes** está crescendo ainda mais e precisa de você para subir o nível do time técnico.

**Seja parte de um grande desafio!** Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir os novos modelos de negócio da nossa empresa. Tudo isso para fornecer a melhor performance aos nossos clientes!

Atualmente nós trabalhamos com **Ruby on Rails** em **aplicações de microserviços**. Estamos nos atualizando então **integrações RESTful APIs** fazem parte do nosso dia a dia. Dentro do nosso dia a dia, usamos muito **MySQL**  e buscamos pessoas que também tenham um forte conhecimento em **Teste (TDD e Teste Unitário)**.Essas tecnologias com pessoas de propósito e dispostas é o que a crescer junto com a gente é o que fará a diferença!

A contratação será feita em **regime CLT alocado na sede da DogHero em São Paulo** e a oportunidade oferece uma faixa entre **R$12.000 - R$15.000!**

Link de Inscrição: https://intera.talent-hacking.com/doghero/software-engineer-ruby/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
