### ISSUE TITLE
[São Paulo - SP] Back-End Developer na 1HELP

### ISSUE THREAD

**Issue by fredericocurti** [backend-br/vagas#1968]
## O que buscamos:
* Dev que busca novas tecnologias e melhorias constantes, inconformado com status quo.
* Ser um Dev que goste tanto de código quanto de pessoas.
* Capacidade de liderar e gerir times de engenharia.
* Experiência em desenvolvimento de Software e Frameworks (Javascript/Node.js, Python/Tornado, REST APIs).
* Experiência prévia com micro serviços.
* Conhecimento básico ou alguma interação prévia com AWS.
* Criar e aprimorar soluções escaláveis, bem documentadas e centradas no usuário.
* Participar das decisões estratégicas de tecnologia, como a escolha da stack, da arquitetura, infraestrutura e do modelo de banco de dados.

## Na 1HELP
* Oportunidade de estar em uma empresa desde seu início, aprendendo e construindo juntos um sonho. 
* Ingressar no time fundador da empresa.
* Você vai ter o desafio de mudar a vida de muitas pessoas, impactando diretamente a economia brasileira e criando um ecossistema e uma mudança positiva na vida das Helpers.
* Viver uma cultura que sempre tenta capacitar seus membros, tornando-os responsáveis pela sua carreira.
* Fazer parte de uma equipe horizontal e transparente, que não apenas valoriza suas ideias, mas também espera que você faça parte da construção da empresa com a gente.
* Ter autonomia na tomada de decisões.
* Trabalhar em um ambiente descontraído e horizontal.
* Participar da construção do negócio, impactando diretamente o sucesso da empresa.

## Local
* Essa posição é presencial para o nosso escritório em São Paulo na Vila Olímpia, mas somos super flexíveis com possibilidade de dividir presencial e home office.
* Ambiente divertido, informal e acelerado.

## Benefícios
* Possibilidade de stock options, tornado-se sócio do negócio.
* Crescer junto com a empresa - eventualmente montar seu próprio time, etc.
* Acesso aos melhores mentores do mercado, de todas as áreas.

## Diferenciais
* Participe da construção do negócio - somos uma empresa em rápido crescimento com grandes desafios pela frente. 
* Buscamos pessoas com alta qualidade de entrega e que ajudem na resolução dos problemas.
* Ambiente descontraído repleto de pessoas excepcionais.

## Requisitos Obrigatórios:
* Conhecimentos de Node.js e Python.
* Inglês intermediário/avançado.
* Habilidade para aprender novas ferramentas rapidamente e compartilhar o conhecimento com o time.
* Experiência com ambiente de produção, onde escalabilidade, performance e estabilidade são qualidades obrigatórias.

## Desejáveis:
*  Experiência com infra AWS
* Vontade de aprender sobre o negócio

## Diferenciais:
* Experiência com framework Tornado de Python
* Experiência com micro serviços
* Perfil empreendedor - histórico de proatividade na resolução de problemas.
* Capacidades de liderança

## Contratação
* PJ

## Nossa empresa
A 1HELP é a startup que está mudando a forma como a faxina é feita e vista pela sociedade e acabamos de finalizar nossa primeira captação. Nascemos com a mente voltada para dados e tecnologia, mas não ligamos em passar um bom pano no chão. As profissionais cadastradas na nossa plataforma (HELPERS) são as pessoas mais carinhosas, educadas e viciadas por limpeza que você irá conhecer. Deixamos as casas dos nossos clientes com cara de casa. Usamos o carinho humano das nossas HELPERs para entregar o melhor padrão de limpeza para cada cliente.
Somos uma equipe jovem, frita, que CHAMA a responsa e resolve! Mas precisamos de ajuda. Por isso, estamos em busca de talentos. Acreditamos na igualdade de oportunidades e queremos revolucionar a vida dessas profissionais! A gente se ajuda diariamente e a única coisa que não pode faltar é o alinhamento com nossos valores. Bora da 1HELP?

### Como se candidatar
Por favor envie um email para pessoas@da1help.com
* Currículo / Linkedin e Github
* Por que se interessou
* Opcional: algum projeto tecnicamente difícil que se orgulha de ter feito (Github ou uma breve descrição do desafio)

### Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo. 
Labels
* Alocado
* PJ
* Sênior

### Nosso site
**https://www.da1help.com/**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
