### ISSUE TITLE
[Barra da Tijuca - Rio de Janeiro] Dev Fullstack 

### ISSUE THREAD

**Issue by talitaclerc** [backend-br/vagas#1969]
## Descrição da vaga
**VOCÊ, Desenvolvedor FULLSTACK!** Se você é _COMPROMETIDO, CURIOSO, MOTIVADO_ e gosta de trabalhar em _EQUIPE_…

…**buscamos uma pessoa exatamente como você** para compôr o nosso _**SUPER time!**_

- Desenvolver novas funcionalidades para nossas plataformas de comunicação, inscrições em eventos, gestão financeira e de membros dentre outras;
-  Participar da construção da nova versão do painel de controle;
-  Fazer a manutenção da versão corrente do projeto ao longo da migração;
-  Desenvolver novos serviços na API;
-  Realizar a migração da API para uma arquitetura de micro-serviços.

## Local
Alocado na empresa na Barra da Tijuca - Rio de Janeiro

## Benefícios
-  Pretensão Salarial;
-  Auxílio-Transporte;
-  Assistência Médica;
-  Assistência Odontológica;
-  Vale Refeição;
-  Horário flexível;
-  Cultura interna de aprendizado constante;
-  Descontos em instituições parceiras.

#### Diferenciais
-  Horário flexível;
- Piscina de Bolinhas;
- Frutas diariamente 

## Requisitos

**Obrigatórios:**

-  Perfil autoditada;
-  Capacidade de escrever códigos limpos;
-  Experiência como DEV FullStack;
-  Desenvolvimento e integração com APIs REST;
- Aplicação de Unit testing e Integration Testing;
- Versionamento de projetos com Git.

**Desejáveis:**
- Experiência com Continuous Integration
- Experiência com Scrum para gestão de projetos

**Diferenciais:**
- Tecnologias de Container, como Docker e Kubernetes
- Experiência com infraestrutura AWS

## Contratação
CLT ou PJ 

## Nossa empresa
Somos _movidos por grandes desafios_ e precisamos de _pessoas que amem aprender constantemente_, que sonhem grande e que tenham muita vontade de transformar a inChurch na melhor e maior empresa global de Tecnologia e Inovação para o 3º setor.

Estamos aumentando o nosso time e tornando o nosso produto cada dia mais robusto, por isso estamos a procura de pessoas cheias de energia, que amem tecnologia, que sejam fascinadas por aprender coisas novas e que queiram fazer parte de algo **GRANDE**!

## Como se candidatar

Se tiver interesse, mande seu currículo para: rh@inchurch.com.br com o assunto DEV FULLSTACK

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@inchurch.com.br

## Labels

- Alocado
- CLT
- Júnior
- PJ
- Pleno
- Fullstack

**Comment by alannsiqueira** [comment]
Qual stack?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
