### ISSUE TITLE
[São Caetano do Sul - SP] - Estagiário(a) em Desenvolvimento Big Data na [BIGGY]

### ISSUE THREAD

**Issue by aprando** [backend-br/vagas#197]
A Biggy é uma empresa de Big Data e Inteligência Artificial focada em personalização e recomendação de e-commerce.  Estamos à procura de um(a) profissional com grande entusiasmo, vontade de aprender e crescer profissionalmente.

Utilizamos tecnologias open-source voltadas para Big Data e Machine Learning, como Hadoop, Spark e TensorFlow. Bancos de dados NoSQL como Redis, Mongo e HBase e frameworks/linguagens como Scala, Java e Javascript/Typescript (NodeJS). Para isso, vamos realizar treinamentos internos para capacitar o nosso futuro desenvolvedor(a) a trabalhar com essas tecnologias. =]

Quer aprender isso tudo? Então venha trabalhar conosco!​

# Requisitos
- Cursando ensino superior na área de TI (mínimo 3º semestre).
- Conhecimento em alguma dessas linguagens de programação: Python, Scala ou Java.
- Conhecimento em Unix.
- Excelente lógica de programação e OO.​

# Desejável
- Interesse em soluções open-source e machine learning.
- Conhecimento em NoSQL, como MongoDB e Redis.​

# Benefícios
 - Vale-transporte
 - Vale-refeição
 - Playstation 4 e Nintendo Switch com amendoim e cerveja ;)
 - Ambiente de trabalho descontraído e equipe colaborativa

# Outras Informações
 - Carga horária de 6 horas (9h às 16h).
 - Estamos localizados no Espaço Cerâmica, ao lado do Park Shopping São Caetano.

# Nossa Empresa
Personalizando e criando em tempo real uma loja para cada consumidor, a Biggy acompanha e interpreta ação do usuário - seja no e-commerce ou nas redes sociais - entregando a melhor experiência de compra possível e potencializando as vendas do e-commerce.

Somos especialistas “nascidos” em Big Data e com profunda experiência em comércio eletrônico, apaixonados por tecnologia e principalmente em como ela pode auxiliar empresas a entenderem cada vez melhor seus clientes.

# Como se candidatar
Envie seu cv atualizado para rh@biggy.com.br, com o título "Estagiário(a) em Desenvolvimento Big Data"

**Comment by aprando** [comment]
Por favor adicionar labels: Estagiário, Big Data, NoSQL, Redis, MongoDB, NodeJS

**Comment by joaopdto** [comment]
Somente no 3° semestre? Poxa, gostaria de enviar meu currículo mas estou no fim do 1°.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
