### ISSUE TITLE
[Remoto] Desenvolvedor backend Ruby on Rails

### ISSUE THREAD

**Issue by andersondias** [backend-br/vagas#1970]
# Descrição da vaga

Trabalha com desenvolvimento web? Temos duas vagas para nosso time de engenharia aqui no enjoei!

O trabalho será remoto e o contrato CLT + benefícios.

O que você vai encontrar aqui?
- Um baita desafio de escala e mais de 4 milhões de usuários impactados ;)
- Stack de desenvolvimento com múltiplas linguagens
- Time de desenvolvimento espalhado por todo o país

O que a gente procura? Ânimo, respeito, polidez e criatividade para descobrir formas novas de resolver problemas.

# Local

De onde você mora, do conforto de sua casa! Basta ter internet e computador ;)

# Requisitos

**O básico para a vaga**

- Experiência em desenvolvimento web com Ruby on Rails ou Go
- Fluência em GIT
- Conhecimento de bases de dados, especialmente PostgreSQL

**Diferenciais:**

- Experiência com AWS e Serverless
- Conhecimento de Elastic Search
- Experiência com desenvolvimento remoto
- Experiência com liderança de times técnicos

# Contratação

CLT + benefícios.

# Como se candidatar

Se tiver interesse, mande seu currículo para: vagas@enjoei.com.br com o assunto DEV BACKEND

# Labels

CLT
Pleno
Senior
RubyOnRails

**Comment by nelsonmfinda** [comment]
@andersondias aceita candidato de fora?

**Comment by davi-dv** [comment]
Opa, aceita junior ?

**Comment by andersondias** [comment]
As vagas que tínhamos foram preenchidas essa semana! Obrigado pela participação.
