### ISSUE TITLE
[São Paulo] Back-End Developer na [Brasil de Fato]

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#1971]
Atividades:

- Desenvolvimento do portal de notícias Brasil de Fato
- Desenvolvimento de sistemas internos
- Testes unitários e de integração
- Garantir qualidade de código
- Trabalhar em time ágil

Sobre você: 

Procuramos uma pessoa: 

- Proativa
- Que saiba trabalhar em equipe
- Com experiência em desenvolvimento backend, preferencialmente Ruby on Rails.

Para se destacar: 

- RESTful, React Native, Frontend, Devops, WordPress.

Nós oferecemos: 

- Remuneração compatível com o mercado de trabalho
- Contratação CLT
- Ambiente descontraído
- Oportunidade de aprendizado e crescimento

Localização:

- Estamos em São Paulo próximo à estação de metrô Barra Funda

Como se candidatar
Se tiver interesse, mande seu currículo para: vagas@brasildefato.com.br com o assunto DEV BACKEND

Labels
CLT
Pleno
Senior
RubyOnRails

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
