### ISSUE TITLE
[São Paulo] Software Developer at Kestraa

### ISSUE THREAD

**Issue by keuller** [backend-br/vagas#1972]
**Sobre a Kestraa**

Somos uma startup que visa criar a primeira plataforma B2B para o comércio exterior. 
Nosso principal desafio enquanto tecnologia é prover um caminho simples, ágil e adaptável para conectar todos os envolvidos nessa complexa cadeia de importação/exportação, a fim de criar um fluxo de negócio transparente e preditível. Estamos no momento de expansão do time, pois nossa proposta de valor foi totalmente aceita no mercado.

**Descrição: Ocupações do cargo**
Desenvolver/evoluir as funcionalidades na plataforma da Kestraa. Além de construir, testar, validar e entregar os pacotes, esperamos que nos ajudem a definir juntamente com os POs a melhor forma de entregar valor aos clientes.

**Local**
Vaga presencial em São Paulo, região de Pinheiros próximo a estação Fradique Coutinho.

**Benefícios**
- Assistência Médica SulAmérica - plano sem mensalidade, mas com co participação limitada a 20% do procedimento, limitado a R$ 50,00
- Assistência Odontológica SulAmérica - plano com mensalidade de R$ 3,68
- Escritório pet-friendly
- Estacionamento ou Vale Transporte
- Ginástica Laboral
- Jornada flexível
- Massagem para relaxar 1 vez ao mês
- Seguro de vida totalmente custeado pela empresa
- Snack e Bebidas
- Vale Refeição R$ 32,00 ao dia
- Vantagens e descontos com instituições de ensino, academias e restaurantes

**O profissional deve possuir:**
• Bom relacionamento com os membros da sua squad;
• Boa comunicação, saber pedir ajuda quando necessário ou mesmo avisar de possíveis problemas antecipamente;
• Trabalho em equipe, está em nosso DNA a colaboração;
• Conhecimento básico em metodologia ágeis;

**Qualificações Técnicas**
- Conhecimento em Java, NodeJS, Kotlin, SpringBoot, Golang ou similares
- Conhecimento em React, Redux (para frontend)
- Conhecimento em desenvolvimento de API
- Conhecimento em banco de dados Relaciona/Não Relacional
- Conhecimento em serviços de Cloud (opcional)

**Contratação**
CLT Presencial.

**Como se Candidatar**
Enviar e-mail para rh@kestraa.com com o assunto: VAGA DE DESENVOLVEDOR DE SOFTWARE

**Salário**
A negociar, pois depende da posição Pleno/Sênior, mas pagamos valor justo de mercado.

**Labels**
Software Developer
Pleno
Sênior
Presencial
CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
