### ISSUE TITLE
[Belo Horizonte] PHP Back-end Developer [DialHost]

### ISSUE THREAD

**Issue by flaviohcardoso** [backend-br/vagas#1973]
## Descrição da vaga

Buscamos uma pessoa criativa e animada para abraçar desafios e objetivos definidos pela equipe;
Valorizamos a busca constante pelo conhecimento na área ou em áreas adjacentes, bem como auxiliar outras com suas habilidades;
Precisamos de pessoas com senso de equipe e engajadas, com senso crítico para ajudar nossos projetos evoluírem de forma rápida e sustentável;

O que esperamos dos candidatos:

- Desenvolver código limpo, testável e de fácil manutenção, implementando as melhores práticas de código e design patterns, orientação a objetos e otimização de performance;
- Discutir e planejar sobre aprimoramentos das ferramentas da empresa, juntamente com a equipe de desenvolvimento;
- Ter habilidade para desenvolver uma aplicação baseada em API para integrações de diversos aplicativos;
- Aplicar melhores práticas de documentação de código desenvolvido;
 
## Local

Presencial - Belo Horizonte - California

## Benefícios
- Regime de contratação CLT ou PJ;
- Vale refeição (CLT);
- Vale transporte (CLT);
- Lanche na empresa
- Flexibilidade de horário;
- No dress code (pode trabalhar de bermuda, camiseta, etc, afinal o que importa é seu resultado!);
- Incentivo a eventos e certificações;

## Requisitos

**Obrigatórios:**
- PHP avançado;
- Laravel;
- Conhecimento em desenvolvimento de API em REST;
- Programação Orientada a Objetos;
- Git;
**Competências Desejáveis:**
- Inglês Intermediário;
- Noções de otimização de performance web;
- Saber se virar como Front-end;
- Otimização de código para SEO;

## Contratação
CLT ou PJ

## Como se candidatar
Se candidatar no site **https://www.dialhost.com.br/trabalhe-conosco/vaga/back-end-php-developer/**
Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.

**Comment by firstMain** [comment]
Aceita remoto ?

**Comment by flaviohcardoso** [comment]
@firstMain como descrito, realmente a vaga é somente para presencial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
