### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor(a) PHP na Oliveira Trust

### ISSUE THREAD

**Issue by davicervo** [backend-br/vagas#1975]
<p>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQIAOtqQ5is5vwbcEn0ZahZfMxz1QIeAYtFfnLdkCXu1sqAGbnX" width="300">
 </p>

## Nossa empresa
Referência na prestação de serviços para o mercado financeiro, a Oliveira Trust vem construindo a sua história de mais de 28 anos de trabalho dedicados ao mercado de capitais.

Prestando serviços para grandes empresas, bancos e fintechs, trabalhando para inovar e otimizar serviços do sistema financeiro.

## Descrição da vaga

**Desenvolvedor PHP (Jr/Pleno/Sênior)**

Buscamos profissional que deseja despertar o seu lado criativo e de revolucionar o mercado financeiro por meio do desenvolvimento de software com tecnologias de ponta.

## Local

Barra da Tijuca, RJ.

A oportunidade é presencial com horário flexível

## Benefícios

- Salário (CLT)
- Bônus de meta e PLR
- Plano de Saúde e Dental
- Vale Transporte ou Combustível
- Vale Alimentação
- Vale Refeição

#### Diferenciais

- Ambiente moderno e descontraído
- Equipe unida e divertida
- Dress code: o seu estilo
- Política educacional
- Cesta de frutas
- Café expresso e muita inovação

## Requisitos

**Obrigatórios:**

- PHP
- Conhecimento em Frameworks PHP
- MySQL
- Javascript
- Ser apaixonado por aprender e explorar novas tecnologias

**Diferenciais:**

- Python, Angular
- Conhecimento em Frameworks (Laravel, Slim, Lumen)
- MongoDB, SQL Server
- Experiência com AWS e/ou outros Cloud Services

## Contratação

Regime: CLT

## Como se candidatar

Para se candidatar, basta acessar a url e realizar o teste para a vaga:
[https://github.com/OliveiraTrust/desafio-desenvolvedor](https://github.com/OliveiraTrust/desafio-desenvolvedor/blob/master/vaga.md)

**Comment by davialmeida** [comment]
Bom dia, tudo bem?
Qual é o prazo para entrega?
Já pode se candidatar e em seguida fazer o teste ou fazer o teste e depois se candidatar a vaga?

**Comment by davicervo** [comment]
O prazo para entrega é conforme a sua necessidade para entregar o desafio proposto.
É necessário fazer o teste para a avaliação, quando enviar o pull request, mande com o seu nome completo e logo depois envie o seu currículo para o e-mail informado!
**Boa sorte!**

**Comment by raphaelbarbosaqwerty** [comment]
Vou reportar uma falha/vulnerabilidade/bug pelo email do desafio.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
