### ISSUE TITLE
[São Paulo/SP] DESENVOLVEDOR NODEJS

### ISSUE THREAD

**Issue by Milaapaiva** [backend-br/vagas#1981]
**PONTALTECH**
Que tal trabalhar em uma empresa jovem, em excelente fase de crescimento e cheia de soluções inovadoras?
Essa é a Pontaltech, uma empresa moderna que vai conectar você a uma carreira de sucesso.

**DESCRIÇÃO DA VAGA**
Atuar junto ao squad para desenvolver nossas funcionalidades e suportar processos existentes

**RESPONSABILIDADES E ATRIBUIÇÕES**
Desenvolvedor novas funcionalidades para plataforma de e-mail e Sms;
Suportar processos já existentes na plataforma;

**REQUISITOS E QUALIFICAÇÕES**
MongoDb;
Nodejs;
Mysql;
Scrum;
Padrão Rest.
Pró-atividade, criatividade, curiosidade, organização, pensar fora da caixa e facilidade de comunicação.
Capaz de trazer soluções para problemas propostos.
Querer trabalhar em equipe e ajudar o time.

**INFORMAÇÕES ADICIONAIS**
Porque trabalhar na Pontal?
Somos uma empresa de tecnologia jovem e dinâmica que conecta pessoas, empresas e tecnologia, promovendo experiências completas em comunicação digital.
Buscamos os melhores para fazer parte dessa história de sucesso! Vem fazer a diferença com a Pontal Tech!

**Nossos benefícios**
Vale refeição, vale transporte ou auxilio estacionamento, assistência médica e odontológica, inglês in company, convênio farmácia, convênio com diversas faculdades e cursos profissionalizantes, ambiente descontraído e divertidos eventos internos!

**Local de trabalho: Centro de SP**

Para se inscrever, enviar currículo para: Camila.paiva@pontaltech.com.br

Site: https://www.pontaltech.com.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
