### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Progress Sênior

### ISSUE THREAD

**Issue by DWCConsult** [backend-br/vagas#1982]
Desenvolvedor Progress Sênior

Desenvolvimentos de manutenções e customizações em Progress para o ERP Datasul.

Requisitos:
- Conhecimento sênior em Progress;
- Conhecimento nos templates Datasul.

Contrato PJ
Prazo indeterminado
Início em Janeiro/2020
Local: Alphaville, Barueri.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
