### ISSUE TITLE
Vaga Programador Júnior - Barueri

### ISSUE THREAD

**Issue by CarolPimentel** [backend-br/vagas#1983]
SOBRE NÓS
Somos uma empresa com sólido conhecimento no mercado digital. Atuamos da criação da marca, planejamento de campanha de marketing, outsourcing até o desenvolvimento de sistemas escaláveis e aplicativos mobile.   A vaga é para atuação em um de nossos clientes, em Alphaville-Barueri.  Segue a descrição da função para o cargo de Programador Júnior:

**Responsabilidades** • Elaborar indicadores • mineração de dados • Implantar automatizações através de programação em SQL e Python • criar painéis de controles gerenciais de área estratégica de negócios • Manipular e tratar dados, convertendo dados brutos em informações úteis para a tomada de decisão.
**Requisitos** • Bacharelado em Ciências da Computação, Análise de Sistemas, Estatística, Física ou áreas afins • 1 ano de experiência em programação •  Perfil analítico  •  Conhecimento intermediário em programação  em SQL, Python e Excel.

**Contrato** CLT padrão
Assistência médica e odontológica - Bradesco Saúde
VT/Vale Combustível/Fretado
Vale Refeição
Seguro de Vida em Grupo
 
Horário
Segunda a sexta, de 08:00 às 17:00h
  
Os interessados deverão encaminhar o currículo para rh@fattoriaweb.com.br com a pretensão salarial.

Para maiores informações www.fattoriaweb.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
