### ISSUE TITLE
[São Paulo/SP] Analista DevOps Cloud Pleno

### ISSUE THREAD

**Issue by kaiorocha** [backend-br/vagas#1984]
VAGA: Analista DevOps Cloud Pleno

Requisitos:
- Experiência com AWS.
- Conhecimento em sistemas operacionais Linux. Automação de rotinas com Shellscript.
- Ferramentas de monitoramento (Zabbix, Grafana)
- Ferramenta de DevOps (Jenkins, ELK, Sonar)
- SQL

Local: São Paulo/SP - Avenida Paulista 

Somos uma Fintech com um ambiente descolado, típico de startup e totalmente voltada a tecnologia e inovação.
O nosso foco é a **CONTA DIGITAL**.
Localizada no coração de São Paulo, Av Paulista próximo a estação brigadeiro do metro.
Nossa Metodologia de trabalho é Scrum e Agile.
Temos também possibilidade de home office. 

O que nós procuramos mais nos profissionais:
- Entender muito bem os requisitos
- Trabalhar no processo de construção de soluções, o que envolve projeto, requisitos, execução, manutenção e suporte;
- Trabalhar para melhorar as soluções existentes e na definição de novas soluções e serviços;
- Aprender e aplicar novas tecnologias para otimizar nossos processos e produtos;
- Proatividade e profissionalismo.

**Tem interese? Envie seu CV e pretensão salarial para rh@aquicard.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
