### ISSUE TITLE
[Remoto] - Angular / Node.js - PJ / Freelancer na Desenvolvimento Ninja

### ISSUE THREAD

**Issue by samuelfaj** [backend-br/vagas#1985]
# Desenvolvimento Ninja

Somos uma fábrica de softwares totalmente remota, com parceiros por todo o pais.

Estamos buscando desenvolvedores(as) para nos ajudar em nossos projetos!

--------

**Requisitos:**
- Adorar conhecer novas tecnologias e estar sempre buscando inovar
- Manjar de Node.js e Typescript
- Manjar de SQL (Mysql) e MongoDB (Opcional).
- Manjar de Angular 2+
- Saber usar o Git e fazer pull request.
- Saber usar o Express. (https://expressjs.com/pt-br/)
- Saber usar Sequelize ORM (https://sequelize.org/)
- Saber usar o Bootstrap (https://getbootstrap.com/)

--------

**Diferenciais:**
- Conhecer Ionic.
- Conhecer um pouquinho de PHP.
- Não usar Windows 😂

--------

**Benefícios:**
- Trabalhe totalmente remoto!
- Horários totalmente flexíveis.
- Não cobramos horário. A gente não acredita em horário fixo. Nós combinamos um prazo (tranquilo) para as tarefas e só cobramos esse prazo.

--------

**Se você conseguir entender esse código https://github.com/samuelfaj/durinn você é mais do que perfeito para a gente.**

**Consegue lidar com o código e se interessou pela vaga?** Envie um e-mail para comercial@desenvolvimento.ninja com o título "Quero ser Dev!" falando um pouco mais sobre você,  sua disponibilidade e a resposta para o teste abaixo:

## Teste
Envie junto ao e-mail o código de uma migration no Sequelize para a criação da seguinte tabela:
![Captura de Tela 2019-12-19 às 23 28 17](https://user-images.githubusercontent.com/12994414/71225390-429a7600-22b7-11ea-848c-3332cec695e6.png)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
