### ISSUE TITLE
[São Paulo/SP] PHP Developer Pleno na Eleven Financial Research

### ISSUE THREAD

**Issue by regular-alves** [backend-br/vagas#1986]
## Descrição da vaga
O desenvolvedor(a) irá atular na análise e desenvolvimento de novas funcionalidades com foco em performance, escalabilidade, segurança e qualidade, além de atuar na integração de sistemas internos e de parceiros através de webservices REST.
Está no nosso DNA e procuramos desenvolvedores(as) com interesse por novas tecnologias e padrões de arquitetura 'fora da caixa', com a capacidade de trabalho com uma equipe multidisciplinar e de compreender como seu trabalho afeta a empresa como um todo, muito além do código.
Prezamos por um  código limpo, de fácil compreensão e manutenção :)

## Local
Escritório, São Paulo - Berrini

## Benefícios
- Plano de saúde
- Assistencia odontológica
- VR de R$ 30/dia
- VT ou ajuda custo estacionamento

#### Diferenciais
- Massagem no escritório
- Gympass

## Requisitos

**Obrigatórios:**
 - Experiência com PHP
 - Sólidos conhecimentos em OOP
 - Conhecimento em banco de dados MySQL/MariaDB
 - Conhecimento em GIT
 - PHP (Laravel)

**Desejáveis:**
 - React.js
 - Arquitetura de microserviços
 - Metodologia Ágil (SCRUM)
 - Experiência com testes unitários e integrados
 - Integração de pagamentos e serviços diversos
 - Conhecimento em Docker

## Contratação
CLT (enviar pretensão)

## Nossa empresa
Eleven é a maior casa de análises econômicas e financeiras independentes do Brasil. Com foco na qualidade, disciplina e responsabilidade, temos como missão auxiliar investidores locais e estrangeiros a tomarem as melhores decisões de investimento. Produzimos soluções de investimentos com respeito ao patrimônio do cliente, considerando suas características pessoais e ajudando-os a tomar as melhores decisões na hora de investir. 
Entregamos relatórios e soluções aos nossos clientes por meio de análises diárias, com teses que são discutidas entre toda a equipe, unindo a visão macro e micro. Além disso, oferecemos atendimento personalizado e acesso aos analistas para os nossos clientes.

## Como se candidatar
Envie o seu currículo junto com sua pretensão salarial para o email [rh@elevenfinancial.com](mailto:rh@elevenfinancial.com), com o assunto  **Developer PHP + Node Pleno**

## Labels
- CLT
- Pleno
- PHP
- Node.js
- React.js
- Laravel

**Vaga permanece aberta:** _atualizado em 24/03/2020_

**Comment by tdias25** [comment]
aceita remoto?

**Comment by regular-alves** [comment]
@tdias25, infelizmente não.
