### ISSUE TITLE
[São Paulo/SP] PHP Developer Júnior na Eleven Financial Research

### ISSUE THREAD

**Issue by regular-alves** [backend-br/vagas#1987]
## Descrição da vaga
O desenvolvedor(a) irá atular na análise e desenvolvimento de novas funcionalidades e integração de sistemas internos e de parceiros através de webservices REST.
Está no nosso DNA e procuramos desenvolvedores(as) com interesse por novas tecnologias e padrões de arquitetura 'fora da caixa', com a capacidade de trabalho com uma equipe multidisciplinar.
Prezamos por um  código limpo, de fácil compreensão e manutenção :)

## Local
Escritório, São Paulo - Berrini

## Benefícios
- Plano de saúde
- Assistencia odontológica
- VR de R$ 30/dia
- VT ou ajuda custo estacionamento

#### Diferenciais
- Massagem no escritório
- Gympass

## Requisitos
**Obrigatórios:**
 - Experiência com PHP e Node.js (Javascript ES6+)
 - Conhecimentos em OOP
 - Conhecimento em banco de dados MySQL/MariaDB
 - Conhecimento em GIT
 - PHP (Laravel)

**Desejáveis:**
 - Integração de serviços diversos (REST)
 - Conhecimento em Docker

## Contratação
CLT (enviar pretensão)

## Nossa empresa
Eleven é a maior casa de análises econômicas e financeiras independentes do Brasil. Com foco na qualidade, disciplina e responsabilidade, temos como missão auxiliar investidores locais e estrangeiros a tomarem as melhores decisões de investimento. Produzimos soluções de investimentos com respeito ao patrimônio do cliente, considerando suas características pessoais e ajudando-os a tomar as melhores decisões na hora de investir. 
Entregamos relatórios e soluções aos nossos clientes por meio de análises diárias, com teses que são discutidas entre toda a equipe, unindo a visão macro e micro. Além disso, oferecemos atendimento personalizado e acesso aos analistas para os nossos clientes.

## Como se candidatar
Envie o seu currículo junto com sua pretensão salarial para o email [rh@elevenfinancial.com](mailto:rh@elevenfinancial.com), com o assunto  **Developer PHP + Node Júnior**

## Labels
- CLT
- Júnior
- PHP
- Node.js
- React.js
- Laravel

**Vaga permanece aberta:** _atualizado em 24/03/2020_

**Comment by klisostom** [comment]
Remoto?

**Comment by regular-alves** [comment]
@klisostom, infelizmente não.

**Comment by klisostom** [comment]
> @klisostom, infelizmente não.

Blz, obrigado!

**Comment by CahMoura** [comment]
Estou interessada na vaga, mas ainda está sendo presencial? Gostaria de saber se agora tem a possibilidade de ser remoto.

**Comment by regular-alves** [comment]
> Estou interessada na vaga, mas ainda está sendo presencial? Gostaria de saber se agora tem a possibilidade de ser remoto.

@CahMoura , no período de pandemia estamos trabalhando Full remoto, mas após este período voltaremos a trabalhar no escritório. Você é de SP?

**Comment by CahMoura** [comment]
Que bom saber. Sim sou do Interior de  São Paulo.

**Comment by regular-alves** [comment]
@CahMoura , caso consiga trabalhar em SP e tenha interesse, manda seu currículo :)
http://eleven.financial/vagas/programador-php-node-junior

**Comment by CahMoura** [comment]
Muito obrigada @regular-alves ☺👩🏼‍💻
