### ISSUE TITLE
Rio de Janeiro - Desenvolvimento Java Júnior 

### ISSUE THREAD

**Issue by CarolPimentel** [backend-br/vagas#1989]
SOBRE NÓS
Somos uma empresa com sólido conhecimento no mercado digital. Atuamos da criação da marca, planejamento de campanha de marketing, outsourcing até o desenvolvimento de sistemas escaláveis e aplicativos mobile.   
Para maiores informações www.fattoriaweb.com.br

O Desenvolvedor atuará em desenvolvimento Web e mobile:
 Desenvolvimento web utilizando os principais frameworks (Spring MVC, Spring
Boot...) • Utilização de tecnologias JEE e REST, integração com Webservices SOAP • Controles de
versionamento GIT • Modelagem de dados .
Requisitos •Formação concluída ou cursando em Ciência da Computação, Análise e Desenvolvimento de Sistemas e afins • Conhecimentos em Linux • Conhecimentos em Java •
Conhecimentos em AWS, Docker, Javascript e NOSQL serão diferenciais.
Desenvolvedor Centro – Rio de Janeiro

A empresa oferece contrato CLT padrão:
- Salário fixo
- Vale Transporte, Vale Refeição
- Plano de Saúde e odontológico Golden Cross
- Seguro de vida em grupo

Horário comercial de segunda a sexta de 09 às 18h
Currículos para rh@fattoriaweb.com.br

**Comment by arrudacaio** [comment]
Aceitam remoto?
