### ISSUE TITLE
[São Paulo - SP] Java Developer Pleno [Intelipost]

### ISSUE THREAD

**Issue by evinorecruiter** [backend-br/vagas#199]
## Como Java Developer Pleno, seus maiores desafios serão:
-Desenvolver integrações de APIs REST/SOAP/FTP com diversos parceiros do segmento de logística;
-Apoiar e opinar na definição da arquitetura do sistema atual e dos micro serviços;
-Conhecer o conceito de base de dados robustas;
-Participar de code-reviews com o time das implementações feitas;
-Inovar sempre, mantendo o padrão de qualidade e performance existente atualmente.

## Local:
Alocado no escritório na Vila Mariana, próximo à estação Ana Rosa

## Benefícios:
-VT (com desconto de 6%) ou estacionamento (50%)
-VR (R$484,00/mês - s/ desconto)
-AM (Amil)
-AO (MetLife)
-Seguro de Vida
-50% de auxílio para curso de inglês

## Requisitos
-Alguém que tenha trabalhado em uma arquitetura de sistemas de alta escala e tolerância;
-Profissional colaborativo para trabalhar juntamente com a equipe de tecnologia existente e também com a equipe de produtos viabilizando a implementação das especificações;
-Boa experiência com JAVA, preferencialmente com Tomcat, SPRING framework, Nexus, Maven, GIT, Jenkins;
-Experiência em desenvolvimento de aplicações que rodam em cloud amazon ;
-Vivência com ambiente de aplicações distribuídas em micro serviços;
-Ter trabalhado com aplicações web modernas e com APIs REST;
-Não ter medo de trabalhar com PostgreSQL e stored procedures.

## Contratação
CLT a combinar

## Nossa Empresa
A Intelipost é a plataforma líder no Brasil em gestão de fretes. Suas soluções integram, de forma inteligente, embarcadores (como e-commerce, varejo e indústria) e transportadoras, proporcionando uma visão completa das entregas.

Suas principais funcionalidades são: cálculo de frete, gestão de despacho, rastreamento de entregas, auditoria de faturas e reembolso dos Correios, além de ferramentas de business intelligence e serviços de consultoria em logística.

Os principais benefícios a seus clientes são redução de custos, visibilidade em tempo real de todas as entregas e ferramentas desenhadas para facilitar o crescimento do negócio.

Baseada em tecnologia cloud de altíssima confiabilidade e escalabilidade, a plataforma está integrada a 2000+ lojas, 350+ transportadoras e faz mais de 300 milhões de cálculos de fretes ao mês.

## Como se candidatar
Envie seu cv atualizado ou linkedin para valeria.souza@evino.com.br, com o título "Java Pleno - Intelipost"

**Comment by evinorecruiter** [comment]
Por favor, adicionar labels: CLT, alocado, Pleno, Java

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
