### ISSUE TITLE
[BRASÍLIA] Desenvolvedor Back - End

### ISSUE THREAD

**Issue by romulo2902** [backend-br/vagas#1991]
VAGA PRESENCIAL!!

CONHECIMENTO EM: 
- API 
- NODE JS 
- FIREBASE 
- MONGODB  
- ADONIS 
- BANCO MYSQL

BENEFÍCIOS:
- VALE TRANSPORTE
 - VALE ALIMENTAÇÃO 

ENVIAR PRETENÇÃO SALARIAL.
CURRÍCULOS PARA ROMULO@NOLU.IO

**Comment by lpaivareis** [comment]
Remoto?

**Comment by romulo2902** [comment]
Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
