### ISSUE TITLE
[BRASÍLIA] Desenvolvedor Front - End

### ISSUE THREAD

**Issue by romulo2902** [backend-br/vagas#1992]
VAGA PRESENCIAL!!

Requisitos Obrigatórios:
- Vue.js; 
- Vuex; 
- Nuxt; 
- Bootstrap; 
- Vuetify; 
- Versionamento de códigos, GIT

Benefícios: 
 - VALE TRANSPORTE
 - VALE ALIMENTAÇÃO 

ENVIAR PRETENSAO SALARIAL
ROMULO@NOLU.IO

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
