### ISSUE TITLE
[São Paulo] Desenvolvedor(a) back-end TypeScript

### ISSUE THREAD

**Issue by apantaliao** [backend-br/vagas#1993]
Olá, tudo bem? 

Seja muito bem-vindo(a) à nossa vaga! Antes de mais nada, gostamos de esclarecer alguns pontos: 

- Para se inscrever a vaga, acesse [nossa página da vaga](https://recruiterflow.com/vizir/jobs/8?source=BackendBR)
- A vaga é para pessoas com alguma experiência em programação. Por isso colocamos pleno / sênior. Mas dentro do nosso time, no dia-a-dia, não usamos muito esta terminologia. 
- A vaga é presencial, mas com horário flexível. Estamos no centro de SP, na República. A vaga pode aceitar remotos, mas aí daremos preferência para pessoas com mais experiência (senior). 
- Embora seja mais para o back-end, gostamos que a pessoa não tenha medo de HTML. Mais do que conhecimento específico em uma plataforma queremos que seja uma pessoa que goste de programar, de fazer testes unitários e de fazer software bem feito!
  
Benefícios
- Ticket refeição: R$ 31,50 por dia (R$ 661,50 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou para onde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

Requisitos
- Conhecer bem uma linguagem de programação, boa lógica e orientação a objetos.
- Estar a fim de aprender.
- Ser comprometido em entregar projetos com qualidade.
- Curtir programar.
 
Desejáveis:
- Ter experiência com práticas ágeis, AWS, Microsserviços. 

**Para se inscrever a vaga, acesse: [Nossa página da vaga](https://recruiterflow.com/vizir/jobs/8?source=BackendBR)**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
