### ISSUE TITLE
[Remoto/Irlanda] NodeJS Developer com possibilidade de sponsor

### ISSUE THREAD

**Issue by rxluz** [backend-br/vagas#1995]
## Descrição da vaga
Trabalhar com NodeJS, Express, AWS

## Local
Inicialmente remoto com possibilidade de sponsor

## Benefícios
- Prêmios todos os meses de acordo com a performance
- Trabalhar presencial o nosso escritório em Dublin de uma semana a 10 dias por ano

## Requisitos

**Obrigatórios:**
- 1+ ano de experiência com NodeJS, Express e MySQL
- 6 meses de experiencia com AWS
- Experiencia com ferramentas de testes como Mocha, Jest e Cypress
- Experiencia com ferramentas de CI/CD como CodeBuild, CicleCI, Travis etc.

**Desejáveis:**
- Conhecimentos em Typescript
- Conhecimentos em Mongo
- Conhecimentos em Lamba functions

**Diferenciais:**
- Projetos open-source
- Textos escritos no Medium/Blog/Dev.to
- Palestras
- Profile (e conteudo) no Github/NPM

## Contratação
PJ a combinar

## Nossa empresa
Loylap.com

## Como se candidatar
Por favor envie um email para ricardo@loylap.com com seu CV/Linkedin/GitHub - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardo@loylap.com

## Labels
- Internacional
- Pleno
- Remoto
- Sênior

**Comment by thiagoluiznunes** [comment]
Que vaga show. Se possível fazer o network para um futuro contato eu agredeceria pois agora não tenho a senioridade. Vou da follow no git.

**Comment by rxluz** [comment]
@thiagoluiznunes a vaga aceita Pleno também, da uma olhada nas labels

**Comment by aurelioolive** [comment]
Enviado ;D

**Comment by ViniciusVicco** [comment]
Que vaga maravilhosa, uma pena não ter nem um terço dos conhecimentos.

**Comment by oliveira-andre** [comment]
essa vaga é show demais! dei um mandei o currículo tomara que dê certo!

**Comment by lucaspiressimao** [comment]
Muito legal a vaga show!!!

**Comment by walkerdepaula** [comment]
Vaga show mesmo! Vou repassar pra galera 💪

**Comment by THAYLLER** [comment]
quanto tempo de retorno amigo?

**Comment by kivervinicius** [comment]
Infelizmente nunca responderam...

**Comment by aurelioolive** [comment]
> Infelizmente nunca responderam...

Nem pra dizer "não" :/

**Comment by adailsonm** [comment]
> > Infelizmente nunca responderam...
> 
> Nem pra dizer "não" :/

Até agora não responderam.

**Comment by rxluz** [comment]
Opa galera, tudo bom? Queriamos agradecer a todo mundo que participou do processo, foram mais de 200 aplicacoes entao ficou praticamente impossivel responder todo mundo, a vaga ja foi preenchida mas em breve abriremos um novo processo, boa sorte a todo mundo, quem quiser algumas dicas sobre como funciona o nosso processo seletivo e como se preparar para uma entrevista desse tipo esse desenvolvedor escreveu um artigo sobre como a experiencia dele nas nossas entrevistas: https://dev.to/ypedroo/what-i-ve-learned-from-blowing-my-first-remote-interview-4klg
