### ISSUE TITLE
[Recife] Desenvolvedor(a) back-end Java

### ISSUE THREAD

**Issue by euraulima** [backend-br/vagas#1996]
**A JUSTA:** 

A JUSTA Pagamentos é uma startup que foi criada em março de 2018 e suas sedes ficam em Alphaville e Recife. Com um time muito competente, a fintech está tendo um crescimento muito acelerado e já possui abrangência nacional. Mais do que uma maquininha de cartão, a JUSTA também é uma maquininha de crédito que já nasceu com o apoio de grandes empresas com a A5, a ADIQ (Banco BS2) e Rede (Banco Itaú), e com o passar do tempo vêm conquistando outros nomes relevantes no mercado de meios de pagamentos como Elo, MercadoPago, a fabricante de equipamentos Pax do Brasil e outros.

**Benefícios**

Plano de saúde e odontológico
VR de R$ 30,00/dia
VT

**Diferenciais:** 

Hierarquia horizontal
Frigobar sempre cheio de cerveja :P
Sala de jogos
Varanda com vista para o Mar
Sem nenhum dress code

**O seu dia será:** 

Atuar na manutenção de microservicos.
Participar da criação de novas features
Atuar na otimização de querys
Atuar na arquitetura da informação

**Esperamos que você:**

Tenha conhecimento em Java
Tenha conhecimento em banco de dados relacionais
Tenha conhecimento com frameworks Spring ou Play
Tenha conhecimento em containers/ orquestradores
Tenha conhecimento em testes unitários
Tenha conhecimento em metodologias ágeis (scrum)

**Como se candidatar:** 
Por favor envie um e-mail para raul.morais@justa.com.vc com seu CV e/ou perfil no LinkeIn. Enviar no assunto: Vaga Back-End Developer

Realizar nosso desafio back-end no link: https://github.com/justapagamentos/jst-job-challenges/tree/master/back-end

**#TamoJustos**

**Comment by Jerffesongoncalves** [comment]
Boa tarde, aceita remoto.

att
________________________________
De: euraulima <notifications@github.com>
Enviado: quinta-feira, 2 de janeiro de 2020 10:26
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [backend-br/vagas] [Recife] Desenvolvedor(a) back-end Java (#1996)


A JUSTA Pagamentos é uma startup que foi criada em março de 2018 e suas sedes ficam em Alphaville e Recife. Com um time muito competente, a fintech está tendo um crescimento muito acelerado e já possui abrangência nacional. Mais do que uma maquininha de cartão, a JUSTA também é uma maquininha de crédito que já nasceu com o apoio de grandes empresas com a A5, a ADIQ (Banco BS2) e Rede (Banco Itaú), e com o passar do tempo vêm conquistando outros nomes relevantes no mercado de meios de pagamentos como Elo, MercadoPago, a fabricante de equipamentos Pax do Brasil e outros.

O seu dia será:

Atuar na manutenção de microservicos.
Participar da criação de novas features
Atuar na otimização de querys
Atuar na arquitetura da informação

Esperamos que você:

Tenha conhecimento em Java
Tenha conhecimento em banco de dados relacionais
Tenha conhecimento com frameworks Spring ou Play
Tenha conhecimento em containers/ orquestradores
Tenha conhecimento em testes unitários
Tenha conhecimento em metodologias ágeis (scrum)

Benefícios

VR e VT
Plano de Saúde e Odontológico
Sem nenhum dress code

**Comment by matheusnascgomes** [comment]
Fala @Jerffesongoncalves, beleza? Infelizmente no momento estamos apenas contratando para vagas presenciais

**Comment by thiago-carrilho** [comment]
Aceita estágio?

**Comment by igor036** [comment]
O desafio ficara aberto até quando ?

**Comment by matheusnascgomes** [comment]
> Boa noite, aceita estágio?
@thiago-carrilho No momento não, mas fica de olho nas nossas redes sociais que em breve estaremos com vagas abertas para estágio

**Comment by matheusnascgomes** [comment]
> O desafio ficara aberto até quando ?

Fala @igor036 ! Não estamos com data limite estipulada, mas estamos com certa urgência na contratação

**Comment by igor036** [comment]
@matheusnascgomes vou fazer hoje a noite quando chegar em casa do trabalho, já enviei o curriculo, e eu tenho um repositorio no meu github usando Spring Boot, vi que vcs queriam, porém eu usei DTO e não MVC, mas já da pra vocês terem uma ideia do meu conhecimento, foi trabalho de faculdade então os testes tive que fazer os que o professor pediu, tem BDD e teste unitário segue o link: https://github.com/igor036/lab-engenharia-software

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
