### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Back-End Jr.

### ISSUE THREAD

**Issue by luizhenrique07** [backend-br/vagas#1997]
# Desenvolvedor(a) Back-End Jr.

## Sobre a empresa
A Comunikime é uma empresa brasileira de integração, especialista em soluções de tecnologia para Call center/telemarketing.

## Sobre a vaga
Irá atuar em desenvolvimento de produtos internos da empresa, principalmente em APIs e automatização de processos.

## Conhecimentos
- Node.js
- Javascript
- MongoDB
- SQL
- GIT
- C#/Java

## Diferenciais
- TDD
- Typescript
- Kafka

## Local
Av. Gen. Ataliba Leonel, 1223 - Santana, São Paulo - SP

## Contato
Para se candidatar, mande um e-mail para contato@comuniki.me

**Comment by AndersonMarquess** [comment]
Enviado.

**Comment by albfernandes** [comment]
aceita remoto?

**Comment by luizhenrique07** [comment]
> aceita remoto?

Não, apenas presencial.
