### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Java Junior na Docket 

### ISSUE THREAD

**Issue by carolinaleaodocket** [backend-br/vagas#1998]
**Somos uma startup revolucionária.**

Docket é uma startup de tecnologia que está reinventando a forma como as grandes empresas lidam com a obtenção de documentos e certidões.
Através do uso intensivo de tecnologia, dados e inteligência artificial tornamos o dia a dia de nossos clientes mais ágil, transparente e eficiente.

Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que estejam alinhados com a nossa cultura e nosso propósito. \o/

**Na Docket você irá:**
-Trabalhar no desenvolvimento (código/testes) com múltiplos projetos
-Criar estratégias para transformar requisitos de negócio, funcionais e não funcionais, em código modular e reutilizável;
-Responsável por aplicar as boas práticas de engenharia de software e padrões de projeto;
-Implementar e manter aplicações;
-Responsável pela manutenção de códigos/testes de sistemas;

 **Você vai se encaixar bem se:**
-Possuir formação em Ciências da Computação, Sistemas de Informação ou áreas relacionadas à tecnologia da informação.
-Bons conhecimentos em Java, SQL, HTML, CSS e JavaScript
-Conhecimentos em framework como Spring ou Hibernate
-Ter experiência de no mínimo 1 ano em desenvolvimento Java

**Vantagens:**
Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida + Improve Yourself;
Auxílio creche para crianças de até 1 ano
Baby Cash após nascimento dos filhos
Comidinhas uma vez por semana
 Ambiente descontraído, criativo e oportunidade de crescimento acelerado =)
Local: Pinheiros
Horário: 44 horas semanais.

Se candidate através da nossa página de carreiras: https://docket.gupy.io/jobs/138191?jobBoardSource=gupy_public_page

**Comment by hidelrios** [comment]
Aceita remoto?

Em qui., 2 de jan. de 2020 às 14:40, carolinaleaodocket <
notifications@github.com> escreveu:

**Comment by carolinaleaodocket** [comment]
Esta vaga seria apenas presencial, mas estamos bem próximo da estação Pinheiros em São Paulo!

**Comment by brunubarbosa** [comment]
empresa top, recomendo!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
