### ISSUE TITLE
#SP Desenvolvedor Full Stack Javascript

### ISSUE THREAD

**Issue by diegoteixeir4** [backend-br/vagas#2]
Somos uma plataforma inovadora de inteligência em mídia digital. Integramos todos os resultados de campanhas em um único lugar e em tempo real. Venha fazer parte do nosso time de desenvolvedores e de um dos projetos mais promissores do mercado digital.

http://keepi.media/

PJ. Remuneração à combinar. Próximo ao metrô Paulista.

### Requisitos

**Obrigatórios**

- Javascript / Node.js / Express
- MongoDB
- GIT
- Experiência em desenvolver e consumir APIs REST e SOAP
- Vue.js, Angular ou React
- HTML5, CSS
- Bash / Terminal / SSH

**Desejáveis**

- Experiência com desenvolvimento de dashboards
- Experiência com alguma outra linguagem (PHP, Python, Ruby etc.)

**Diferenciais**

- Cloud computing (AWS, Azure ou Digital Ocean)
- Apache / Nginx (configuração)

Envie e-mail para contato@keepi.media com currículo/portifólio e pretensão salarial. Favor colocar a descrição da vaga no assunto do e-mail.

**Comment by onhernandes** [comment]
Mandei um email :D

**Comment by victorhcosta** [comment]
Possibilidade de remoto?

**Comment by diegoteixeir4** [comment]
@victorhcosta essa vaga é somente presencial.

**Comment by onhernandes** [comment]
@diegoteixeir4 a vaga ainda está aberta?
