### ISSUE TITLE
[São Paulo] Desenvolvedor Back-end Senior [TOTVS - iDEXO]

### ISSUE THREAD

**Issue by TiagoCastanho** [backend-br/vagas#20]
A TOTVS lançou recentemente o iDEXO, um instituto com uma plataforma ABERTA de inovação, com foco em dar suporte e mentoria nas mais atuais estratégias de negócio e criar parcerias com os mais inovadores players. Tudo para que startups e empresas compartilhem seu conhecimento e construam as melhores soluções em tecnologia.

Estamos buscando Desenvolvedores Back-end de nível Senior com os seguintes skills:

-Python
-NodeJS
-Paradigma Funcional
-Machine Learning (Diferencial)
 
O local de trabalho é em São Paulo-SP (Bairro de Santana) e os principais benefícios são:

-Assistência Médica
-Assistência Odontológica
-Seguro de Vida
-Previdência Privada
-PLR
-VR,VT

Para aplicar-se a essas vagas, lançamos um desafio que você pode acessar por esse link: https://bitbucket.org/idexoteam/desafio-backend

Dúvidas: tiago.castanho@totvs.com.br

**Comment by reginaldojunior** [comment]
https://bitbucket.org/MarcelSanches/desafio-backend

Está dando 404

**Comment by TiagoCastanho** [comment]
Link corrigido!
Abs.

**Comment by mastermt** [comment]
link 404


Em ter, 24 de out de 2017 às 07:55, TiagoCastanho <notifications@github.com>
escreveu:

**Comment by TiagoCastanho** [comment]
Corrigimos o link:
https://bitbucket.org/account/user/idexoteam/projects/IDEXO


De: Pedro Tomaz Alves [mailto:notifications@github.com]
Enviada em: terça-feira, 24 de outubro de 2017 15:30
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: TIAGO CASTANHO <tiago.castanho@totvs.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [São Paulo] Desenvolvedor Back-end Senior [TOTVS - iDEXO] (#20)

link 404


Em ter, 24 de out de 2017 às 07:55, TiagoCastanho <notifications@github.com<mailto:notifications@github.com>>
escreveu:

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
