### ISSUE TITLE
[São Paulo] Full-Stack Engineer na ANBIMA

### ISSUE THREAD

**Issue by bruno-julian** [backend-br/vagas#200]
### Descrição da vaga

- Full-Stack Engineer nível Pleno

## Formação:

- 	Ensino superior completo em Analista de Sistemas, Ciência da Computação, Sistemas de Informação ou afins.

## Atividades Principais:

- 	Desenvolvimento full-stack de sistemas: Java, ReactJS, Docker.
- 	Analisar, entender demandas de negócio para propor e especificar soluções sistêmicas.
- 	Liderar e apoiar a execução de projetos dentro da metodologia ágil
- 	Realizar o levantamento de necessidades das áreas de negócio e tecnologia, criando e gerenciando o backlog e a fila de execução de épicos e estórias de usuário.
- 	Analisar tecnicamente a performance, qualidade de codificação, cobertura de testes e outros aspectos técnicos dos sistemas.
- 	Elaborar, especificar, desenvolver e rever modelos de dados.
- 	Acompanhar coordenar testes e homologações de sistemas.

## Conhecimentos Necessários:

- 	Experiência em desenvolvimento Java, RESTful APIs, SQL, GIT, Servidores de aplicação, Spring Framework, Sprint Boot, JSF, Javascript, ReactJS e Docker.
- 	Experiência de gestão de projetos ágil (Scrum e Kanban).
- 	Inglês avançado.

## Conhecimentos Desejáveis: 

- 	Mensageria (JMS), JBoss Application Server, Jenkins, Cloud Services (AWS, Google Cloud).
- 	Conhecimento de conceitos de gestão de produto (Product Owner).
- 	Vivência no mercado financeiro com experiência em atuação em projetos de desenvolvimento de sistemas.

## Forma de contratação

- 	CLT Full (salário a combinar) + benefícios acima do mercado
- Alocação presencial Pinheiros/São Paulo
- Caso haja interesse, enviar email com CV atualizado para: bruno.julian@anbima.com.br

**Comment by bruno-julian** [comment]
Por favor adicionar labels: CLT, Java, Javascript, Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
