### ISSUE TITLE
[SÃO PAULO/SP] Back-End Developer Pleno e Sênior no Guiabolso

### ISSUE THREAD

**Issue by andre-reis93** [backend-br/vagas#2006]
**Oportunidade para BACK-END DEVELOPER PLENO e SENIOR no Guiabolso**

A vida adulta chega na forma de um boleto, mas quem disse que precisamos lidar com isso sozinhos?

O Guiabolso nasceu em 2012 para ajudar os brasileiros a fazerem escolhas mais espertas e, aos poucos, fortalecer uma comunidade que, unida, consegue jogar melhor esse jogo, forçando o sistema financeiro a melhorar suas práticas! São 6 milhões de usuários e mais de R$200.000.000 economizados para essas pessoas!

Acreditamos que as melhores ideias surgem quando as pessoas estão trabalhando por um propósito maior. Trabalhar no Guiabolso é ter a oportunidade de lidar com grandes desafios, crescer bastante e fazer parte de uma startup jovem, dinâmica e que sempre coloca as pessoas em primeiro lugar! Aqui todo mundo tem liberdade para protagonizar projetos que impactam vidas!

**O que precisa saber para encarar o desafio:**

Java e/ou Kotlin;
Microserviços;
Clean Code;
S.O.L.I.D. ;
Experiencia com AWS

**Informações da Vaga:**

Regime CLT, presencial flexível, em São Paulo
Remuneração Competitiva
Seguro de Vida, Vale Refeição, Vale Alimentação, Vale Transporte, Assistência Médica, Assistência Odontológica, Gympass e muito mais 🙂.

Link da oportunidade: http://byintera.in/guiabolsobackenddev

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
