### ISSUE TITLE
[Manaus] Desenvolvedor back-end Sênior [Méliuz]

### ISSUE THREAD

**Issue by Folks-Meliuz** [backend-br/vagas#2008]
## Descrição da vaga
Nós do Méliuz temos grandes sonhos e desafios e sabemos que para chegarmos cada vez mais longe precisamos aumentar nossa grande família com uma pessoa desenvolvedora Back-End Sênior. Gostamos de novas tecnologias e não nos restringimos a apenas o que temos funcionando hoje. São milhares de operações por segundo com grandes picos sobre nossa stack atual que é código PHP (legado), Python, C++ e Node.js, rodando com banco de dados MySQL, PostgreSQL, Redis, BigQuery e Redshift, rodando em ambiente de nuvem híbrida (AWS e Google Cloud). Contamos com uma equipe de desenvolvimento altamente qualificada e interdisciplinar que sempre prefere soluções Open Source ou livres.

**Benefícios:**
Vale transporte;
Vale refeição ou alimentação;
Plano de saúde;
Plano odontológico;
GymPass;
Horário flexível;
Cashback online em dobro no Méliuz!

## Requisitos 
**E para isso você precisa ter:**
Ampla experiência com alguma linguagem de alto nível em ambiente web; 
Experiência com banco de dados relacionais (especialmente MySQL ou PostgreSQL);
Visão sistêmica de problemas e melhorias em nível arquitetural;
Experiência com aplicações cliente-servidor e APIs REST;
Experiência com testes automatizados;
Experiência com ferramentas de controle de versão, em especial Git;
 
**Os diferenciais são:**
Experiência em sistemas com um alto volume e/ou tráfego de dados;
Experiência com Python ou Node.js;
Experiência com microsserviços;
Experiência com Docker;
Experiência com serviços da AWS (S3, SNS/SQS, CloudWatch);
Experiência com metodologias ágeis (Scrum, Kanban);
Contribuição em projetos Open Source e/ou comunidades de software;

## Como se candidatar
Entre no nosso site e faça seu cadastro: https://jobs.lever.co/meliuz

## Nossa empresa
Somos a maior empresa de cashback do Brasil e buscamos desbloquear relações inteligentes de consumo!
Atuamos criando oportunidades para todo mundo ganhar mais! Por meio de um programa de cashback, que devolve dinheiro para milhões de consumidores brasileiros, o Méliuz promove a fidelização e a otimização dos investimentos de suas lojas parceiras.
Somos apaixonados por nossos clientes e acreditamos no consumo inteligente, onde todas as partes sempre ganham: as lojas, pois aumentam suas vendas e retêm os clientes; o Méliuz, que recebe por cada venda feita; e os consumidores, que são recompensados de verdade por suas compras.

## Labels
- CLT
- Sênior
- Manaus
- Presencial

**Comment by Folks-Meliuz** [comment]
Vaga ainda ABERTA

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
