### ISSUE TITLE
[São Paulo] Back-End Developer na Hash

### ISSUE THREAD

**Issue by luizadpassos** [backend-br/vagas#2009]
A Hash é uma startup que oferece serviços de pagamentos e banking, ofertando aos seus clientes vantagens comerciais, eliminando fricções de transações e oferecendo outros benefícios relacionados a sua operação principal.

A Hash conta com time de excelência formado por pessoas inspiradoras e que entendem o valor da colaboração. Autonomia e confiança estão no seu DNA.

O desafio consiste em construir sistemas robustos, escaláveis e confiáveis, utilizando micro serviços para transformar a maneira como o ecossistema financeiro brasileiro funciona!

Mais informações sobre a oportunidade e onde se cadastrar na oportunidade no link a seguir: https://byintera.in/6y

Qualquer dúvida, estou a disposição! :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
