### ISSUE TITLE
[Barueri - SP] Full Stack .NET no [Grupo Flamboyant]

### ISSUE THREAD

**Issue by livialdias** [backend-br/vagas#201]
## Descrição da vaga

Grupo focado no desenvolvimento de soluções em empregabilidade. Inicialmente o profissional atuará em projeto de novo aplicativo mobile e depois nos demais produtos digitais do grupo.

## Local

Escritório, Barueri - Alphaville Empresarial

## Requisitos

**Obrigatórios:**
- Conhecimento em linguagem de programação .NET, MVC5, ASP.CORE, Web API, REST
- Banco de dados MS SQL

**Desejáveis:**
- Atuação em equipes com metodologia SCRUM

## Contratação

PJ

## Nossa empresa

O Grupo Flamboyant trabalha em soluções para interligar profissionais e oportunidades.

## Como se candidatar

Por favor envie um email para livia.dias@supervagas.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
