### ISSUE TITLE
[Manaus] Especialista em Desenvolvimento Back-end- Infraestrutura [Méliuz]

### ISSUE THREAD

**Issue by Folks-Meliuz** [backend-br/vagas#2010]
## Descrição da vaga

 O que você vai fazer?

- Mapear os serviços a serem criados/separados da aplicação principal;
- Definir Domínios e Responsabilidades dos serviços criados;
- Aprimorar junto aos DBAs e DevOps a arquitetura de comunicação entre os serviços;
- Criar e manter os serviços com versionamento;
- Implementar junto com os DevOps um sistema de deploy zero downtime;
- Fornecer os dados necessários para monitoramento dos serviços;
- Implementar o código de forma tolerante a faltas e falhas;
- Cuidar da segurança no nível da aplicação;
- Definir e implementar testes;
- Otimizar performance das aplicações;
- Monitorar e corrigir erros nas aplicações;
- Apresentar soluções simples e saber priorizar as tarefas;
- Propor melhorias nas soluções existentes;
- Ter vontade de aprender coisas novas todos os dias; 
- Codificar, codificar e codificar; e
- Se divertir com o trabalho.

## Requisitos
Experiência em sistemas com um alto volume e/ou tráfego de dados;
Experiência com banco de dados relacionais (especialmente MySQL e/ou PostgreSQL);
Experiência com aplicações cliente-servidor e APIs REST;
Experiência em arquitetura de software (em especial microserviços);
Experiência em gerenciamento de filas;
Experiência em testes automatizados;
Habilidade em diversas linguagens (exemplos: PHP, Python, Ruby, Go, Erlang etc.);
Experiência com ferramentas de controle de versão, em especial Git;

## Diferenciais
Experiência com serviços da AWS (S3, SNS/SQS, CloudWatch);
Experiência com ferramentas de ticket/bug tracking (JIRA, GitHub Issue, Bugzilla, Mantis)
Experiência com metodologias ágeis (Scrum, Kanban);
Contribuição em projetos Open Source e/ou comunidades de software;
POSIX (UNIX/Linux), Shell Script.

## Como se candidatar
Entre no nosso site e faça seu cadastro: https://jobs.lever.co/meliuz

## Nossa empresa
Somos a maior empresa de cashback do Brasil e buscamos desbloquear relações inteligentes de consumo!
Atuamos criando oportunidades para todo mundo ganhar mais! Por meio de um programa de cashback, que devolve dinheiro para milhões de consumidores brasileiros, o Méliuz promove a fidelização e a otimização dos investimentos de suas lojas parceiras.
Somos apaixonados por nossos clientes e acreditamos no consumo inteligente, onde todas as partes sempre ganham: as lojas, pois aumentam suas vendas e retêm os clientes; o Méliuz, que recebe por cada venda feita; e os consumidores, que são recompensados de verdade por suas compras.

## Labels
CLT
Especialista
Presencial
Manaus
Sênior

**Comment by Folks-Meliuz** [comment]
Vaga ainda ABERTA

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
