### ISSUE TITLE
[Rio de Janeiro] PHP

### ISSUE THREAD

**Issue by defdobrasil** [backend-br/vagas#2011]
Experiência com PHP e React. Desejável conhecimento de Api Google Maps e Geolocalização.contato@defdobrasil.com

**Comment by jhonatanmsc** [comment]
Aceita remoto?

Em qua, 8 de jan de 2020 13:18, defdobrasil <notifications@github.com>
escreveu:

**Comment by defdobrasil** [comment]
Neste momento seria presencial, mas mantemos contato pois aparecem alguns
jobs extrsa, tem interesse?


www.defdobrasil.com


Em qua., 8 de jan. de 2020 às 13:41, Jhonatan Matheus <
notifications@github.com> escreveu:

**Comment by jhonatanmsc** [comment]
Claro!

Em qua, 8 de jan de 2020 13:43, defdobrasil <notifications@github.com>
escreveu:

**Comment by karinegusmao** [comment]
Sou de Niterói, tenho 19 anos de experiência em desenvolvimento. Enviei o meu perfil profissional para o e-mail contato@defdobrasil.com.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
