### ISSUE TITLE
[Criciúma/SC] Desenvolvedor WEB (PHP) na Exon Sistemas

### ISSUE THREAD

**Issue by lucassch** [backend-br/vagas#2012]
### Descrição da vaga

Procuramos profissionais para auxiliar no desenvolvimento e manutenção de nossos produtos, contribuindo desde o planejamento até a entrega em produção.

### Requisitos

Pensamento lógico/matemático
Experiência com banco de dados relacionais
Ter autonomia e ser autodidata
Vontade de aprender/compartilhar conhecimento com a equipe

### Diferenciais

Experiência trabalhando em sistemas PHP, melhor ainda se conhecer o framework Laravel
Javascript
Controle de versão Git
iReport
Experiência com Angular 2+ / Ionic Framework
Conhecimento em ERPs

### Remuneração/benefícios

Salário a combinar, de acordo com competências e experiência.
Plano odontológico
Plano de saúde 

### Como se candidatar
Enviar CV/Linkedin para rh@exonsistemas.com.br

**Comment by viniptds** [comment]
Aceita remoto?

**Comment by lucassch** [comment]
No momento apenas presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
