### ISSUE TITLE
[São Paulo] Desenvolvedor BackEnd NodeJS Junior/Pleno na Mudeii

### ISSUE THREAD

**Issue by feliperodalves** [backend-br/vagas#2013]
## Descrição da vaga

- Desenvolvimento de funcionalidades no Back-End;
- Realizar a manutenção e criação de novas funcionalidades;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;

## Local

Escritório, São Paulo - Moema

## Requisitos

**Obrigatórios:**
- NodeJS
- AdonisJS
- ORM e MySQL & MongoDB
- Controle de Versões (Git preferencialmente);
- Paixão por aprender e programar;

**Desejáveis:**
- Padrões de códigos e Linters (eslint / prettier)
- Testes automatizados;

**Diferenciais:**
- Inglês
- Python
- Infraestrutura Azure;
- Build & Deployment

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa de tecnologia resolvendo antigos problemas do mercado imobiliário de uma forma totalmente inovadora. Somos uma plataforma de serviços financeiros para o mercado imobiliário que reúne e facilita a vida de inquilinos, administradores e proprietários, desburocratizando o processo de locação de um imóvel residencial urbano.

A MUDEii nasce com a missão de facilitar a vida das pessoas resolvendo as dores de quem precisa alugar um imóvel. Agora basta o inquilino se cadastrar no App, ver o valor de locação aprovado e sair para buscar o imóvel que deseja (pode escolher qualquer imóvel anunciado em qualquer plataforma existente no mercado). Depois que escolher o imóvel, é só avisar ao Administrador ou ao Proprietário que irá pagar com a MUDEii e começar a se preocupar com a mudança.

## Como se candidatar

Por favor envie um email para rh@foii.com.br com seu CV anexado - enviar no assunto: Vaga React / React Native

## Labels

- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 3k-5k

**Comment by paulohrodrigues** [comment]
Gostei Muito dessa vaga, não existe nenhuma possibilidade de ser remoto?

**Comment by feliperodalves** [comment]
> x

Infelizmente hoje somente presencial

**Comment by feliperodalves** [comment]
> Gostei Muito dessa vaga, não existe nenhuma possibilidade de ser remoto?

@paulohrodrigues - Infelizmente hoje, somente presencial

**Comment by paulohrodrigues** [comment]
@feliperodalves Obrigado pela sua resposta :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
