### ISSUE TITLE
 [Barueri/SP] Desenvolvedor(a) Java na Platform Builders

### ISSUE THREAD

**Issue by Ana300** [backend-br/vagas#2014]
Buscamos desenvolvedores apaixonados pela linguagem Java, inconformados por natureza e encantados em gerar valor. 
Na Builders você irá fazer parte de um time de empreendedores, onde buscamos inovação com disrupção de forma significativa, com qualidade e simplicidade - seja através do código ou através da melhoria contínua alinhada à performance. 
Tá afim de iniciar essa jornada com a gente, gerando transformação de forma impactante? Se liga nos detalhes abaixo:
**#SejaBuilder**

**Tecnologias que vão gerar valor nos projetos:**
Java 8
Sonar
JPA ou Mockito
Springboot
GIT
Linux
DDD

**O que te aproxima de ser um (a) Builder:**
Conhecimento em Kubernets
Jenkins
Maven
Docker
Microservices
REST
Design Patterns

Local de Trabalho: Alphaville - Barueri/SP
Remuneração: A definir
Modalidade: PJ

**INFORMAÇÕES ADICIONAIS**
Oportunidades reais de empreender e impactar
Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
Inovação e criação liberados
Participar de um processo único de geração de valor
Contribuir na criação de métodos disruptivos
Colocar suas ideias no mercado, na prática! :)
Possibilidade de Profit share em novos Negócios
Prestador de Serviços (PJ)
Flexibilidade de horário

Curtiu? Faça sua inscrição por aqui - https://sejabuilder.gupy.io/jobs/139304

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
