### ISSUE TITLE
[Remoto] Desenvolvedor(a) .NET na Platform Builders

### ISSUE THREAD

**Issue by Ana300** [backend-br/vagas#2015]
Trabalhar na Builders é conceber, planejar e executar novas funcionalidades! Fazer parte de uma comunidade de empreendedores de software, com um ambiente diferente de tudo que você já vivenciou, onde cada pessoa é protagonista da sua história. Irá atuar com desenvolvimento na plataforma, produzindo e otimizando códigos para maior performance, escalabilidade e velocidade. Será responsável pela qualidade e funcionalidade das soluções implementadas. Está na hora de ficar eufórico com a chance de ser Desenvolvedor .NET
**#SejaBuilder**

**Tecnologias que vão gerar valor nos projetos:**
Domínio nas plataformas: .NET Core (C#) / Angular 6+
Conhecimentos em Banco de Dados: Mongo DB, SQL Server, Testes: XUnit, Moq, JMeter Versionamento: Git, Arquitetura/Padrões: 12-Factor, DDD, Design Patterns, Restful, Microservices, CI/CD (Jenkins/Openshift)

**O que te aproxima de ser um (a) Builder:**
Vivência anterior com o padrão arquitetural Pipes and Filters
Fluência em programação recursiva

Local de Trabalho: Remoto
Remuneração: A definir
Modalidade: PJ

**INFORMAÇÕES ADICIONAIS**
Oportunidades reais de empreender e impactar
Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
Inovação e criação liberados
Participar de um processo único de geração de valor
Contribuir na criação de métodos disruptivos
Colocar suas ideias no mercado, na prática! :)
Possibilidade de Profit share em novos Negócios
Prestador de Serviços (PJ)
Flexibilidade de horário

Curtiu? Faça sua inscrição por aqui - https://sejabuilder.gupy.io/jobs/123787

**Comment by felipehfreire** [comment]
ainda disponivel?
