### ISSUE TITLE
[FLORIANÓPOLIS - SC] PHP Back-End Developer na CompuFour

### ISSUE THREAD

**Issue by haroldcsbecker** [backend-br/vagas#2017]
### **Função**

Trabalhar junto da equipe na manutenção e implementação de novas funcionalidades/atualizações na API e no sistema da CompuFour. Assim como participar das decisões de tecnologia, dos eventos de inovação da empresa e das decisões em equipe.

### **Requisitos**

* Conhecimentos em PHP e Orientação a Objetos
* Conhecimentos em banco de dados (MySQL, PostgreSQL)
* Conhecimentos em Git
* Conhecimento com algum framework como Zend Framework 2, Laravel, Silex ou similar
* Inglês técnico ao menos para leitura
* Interesse em aprender novas tecnologias, linguagens de programação e ambientes de desenvolvimento
* Morar ou estar disposto a se mudar para Florianópolis

### **Requisitos adicionais**
* Experiência com containers (Docker)
* Experiência com Rest API
* Conhecimentos em ORM (entidades, relacionamentos, DQL). Como Doctrine 2, por exemplo
* Conhecimentos em testes unitários
* Conhecimento sobre Cloud Computing (IaaS, PaaS e SaaS)
* Experiência com DevOps

### **Perfil esperado**

* Senso crítico;
* Disciplina e organização é fundamental;
* Sedento por conhecimento;
* Traz críticas em relação a ferramentas utilizadas, com o objetivo de melhorar o desenvolvimento;
* Pesquisador nas horas vagas, trazendo novidades que podem ser realmente aplicadas nos projetos;
* Engajamento com a equipe, para crescimento sustentável de todos.

### **O que oferecemos**

* Contrato CLT com salário compatível com a experiência
* Vale Alimentação
* Contratação Imediata
* Oportunidade de trabalhar em um projeto com tecnologias inovadoras
* Incentivos para participar de eventos/cursos/treinamentos

### **Local**

Ambiente descontraído e inovador do **Impact Hub Coworking** que fica localizado no **Centro de Inovação ACATE**

Se você atende os requisitos acima mande um e-mail com seu currículo para:
rh@compufour.com.br 
Ou entre em contato pelo telefone: (49) 3442-0122  (Ramal 616)

**Comment by vitoraalmeida** [comment]
Olá, boa tarde. A vaga é destinada a um nível específico de experiência?

**Comment by haroldcsbecker** [comment]
Olá, boa tarde Vitor. 
A princípio a gente procura uma pessoa com mais experiencia, entretanto pessoas com uma noção geral boa e com vontade de aprender são sempre bem vindas

**Comment by josebispo** [comment]
@haroldcsbecker currículo enviado, abraço!
