### ISSUE TITLE
[BARUERI-SP] JAVA PLENO na JUST DIGITAL

### ISSUE THREAD

**Issue by alicesrossi** [backend-br/vagas#2019]
## Descrição da vaga
Quem é a Just? Da uma olhada aqui:
Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível.
Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

## Local

Barueri - SP

## Benefícios

- Vale Refeição
- Vale Transporte
- Assistência médica e Odontológica
- Seguro de vida
- Home offices

## Requisitos

**Obrigatórios:**
Java, JPA, Hibernate, Oracle Weblogic,
JBOSS, filas JMS
Git e WebService
REST e SOAP
Integração Contínua (i.e Jenkins)
Orientação a objetos 
Design Patterns

## Contratação

PJ a combinar 

## Como se candidatar

Por favor acesse o link e se cadastre! https://justdigitalbr.recruitee.com/o/dev-java-pleno-barueri-sao-paulo

## Labels

- Alocado
- CLT
- Pleno
- Barueri
- back end
- java
- jpa
- jboss
- hibernate

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
