### ISSUE TITLE
[São Paulo] Senior Software Engineer at Hash

### ISSUE THREAD

**Issue by femariotti** [backend-br/vagas#2023]
About Us

Any company that wants to offer payment and banking services faces numerous regulatory and technological barriers. Through Hash, any B2B company can offer its customers business advantages by eliminating transaction friction and offering other benefits related to their core operation. Our whitelabel and plug-and-play platform minimizes implementation time, reduces initial investment and operating costs by up to 95%.
We understand the value of collaboration and we strive for a healthy work environment. Flexible work hours, pet friendly office, yoga, massage, etc. are cool but they are simply a reflex of autonomy as a core value of our team.
 
 
 How we work

*We are not attached to a specific set of programming languages or architecture, we have several challenges and we are free to choose the best way to tackle each one of them, following state-of-the-art software development practices and choosing the best programming language and stack to solve what we need. Our focus is on delivering quality, our customers are fine with fewer features, but are not ok with broken features. Today we are building:
*Horizontally scalable microservices
*Data storage in MongoDB and Postgres
*Continuous Integration and Deployment into AWS, GCLOUD and Azure
*A highly modular front-end that integrates the design team in the development process
*You can check out our detailed core key-values explanation or contact us if you want to know more about how we work.

What we are looking for

*We are looking for people passionate for coding, with experience on building scalable products and exceptional technical background. Technology is the most important part of our business, so we need people who want to know more about our market, about how the payment ecosystem works and help us to change it. 
*As a software engineer you are expected to set the tone and pace of engineering at Hash, building the foundation for dozens of other systems in the future.
 
 
What is needed to be an engineer at Hash

*Uphold Hash's high engineering standards and bring consistency to the codebases, infrastructure, and processes.
*Own and manage all phases of the software development lifecycle (planning, design, implementation, deployment and support)
*Own problems end-to-end, thinking through everything: from system design, data modeling, scalability, operability and ongoing metrics.
*Collaborate effectively with product managers, designers, engineers and stakeholders on the projects
*Communicate technical ideas and set direction on projects with a focus on solving business challenges. We are extraordinarily candid with each other and very frank on discussing technical matters.
 
Benefits
High compensation package
Health and dental insurance
Meal allowance (“vale refeição”)
Flexibility to choose your own custom setup (computer, monitors, OS etc.)
Subsidy to sports practicing
Subsidy for self-development purposes

--

You can apply at https://boards.greenhouse.io/hash or by sending an e-mail to felipe.mariotti@hash.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
