### ISSUE TITLE
[São Paulo] - Senior Software Engineer Java at Intelipost

### ISSUE THREAD

**Issue by brunoosilva** [backend-br/vagas#2024]
## Intelipost

A Intelipost é uma startup brasileira de tecnologia que está revolucionando o setor logístico no país. Temos um sistema inovador responsável por gerenciar as operações de logística das principais plataformas de E-commerce e Marketplace do mercado.

Somos focados em oferecer sempre a melhor experiência aos nossos clientes e engajados em entregar soluções que modifiquem a forma com que eles pensam e fazem logística no seu dia-a-dia.

Estamos à procura de um novo **#INTELIPOSTER** com olhar crítico para criar novas funcionalidades e fazer a manutenção de sistemas com impacto direto no nosso negócio. Como parte do Time de Tech, você terá a liberdade e responsabilidade de nos auxiliar com a melhoria continua dos nossos processos.

Se você está em busca de desafios e tem prazer em ensinar e aprender, a gente quer te conhecer 😉

## Nossa Stack

Usamos várias tecnologias diferentes para a criação do nosso produto, como: Docker para a organização nosso sistema em micro serviços na AWS, Java 8, Spring, PostgreSQL, ELK, Redis, RabbitMQ e outros.

Temos um frontend para acesso dos clientes que foi desenvolvido em AngularJS, Vue.js, GraphQL, Node.JS e alguns mobile apps utilizando Ionic.

Ah! Você não precisa saber tudo isso agora, mas precisa demonstrar interesse em aprender! =)

## Requisitos

**Os seus desafios serão:**

- Desenvolver e manter nossos micros serviços, ajudando nas tomadas de decisões e entregas de resultados, focando em encantar o cliente;
- Contribuir com o desenvolvimento e arquitetura da plataforma Intelipost, preparando-a para o crescimento acelerado pelo qual a empresa vem passando;
- Construir uma base sólida para o desenvolvimento de novos produtos de forma ágil;
- Acompanhar a disponibilidade do nosso sistema, visando antecipar possíveis GAPs, aumentando assim, a confiabilidade da solução;
- Desenvolver sistemas escaláveis, sustentáveis​​e orientadas ao usuário.

**Esperamos que você:**

- Possua graduação completa em Tecnologia, Análise de Sistemas, Sistemas da Informação, Engenharia de Software ou cursos de áreas correlatas;
- Tenha experiência com desenvolvimento de aplicações WEB, utilizando linguagem de programação Java e as tecnologias citadas anteriormente;
- Conheça o básico de arquitetura de sistemas de alta escala e tolerância que rodem em ambiente AWS;
- Vivência com ambiente de aplicações distribuídas em micro serviços;
- Tenha interesse em trabalhar com PostgreSQL e stored procedures.

**Consideramos como diferencial:**

- Vivência com ambiente de aplicações distribuídas em micro serviços;
- Experiência com banco de dados NoSQL;
- Experiência com tecnologias de Streaming e Big Data.

## Local

Escritório, São Paulo - Avenida Paulista

## Benefícios

- Salário fixo compatível com mercado;
- PLR de até 2 salários ao ano;
- Vale refeição/alimentação de R$ 630,00 ao mês;
- Vale transporte integral;
- Assistência Médica sem desconto de co-participação;
- Assistência Odontológica;
- Seguro de Vida;
- Frutas no escritório;
- Programa de Parcerias Corporativas (Bem estar, educação, beber e comer e qualidade de vida);
- Ambiente no dress code;
- Autonomia e flexibilidade;
- Descontração, alegria e um ambiente de empresa que cresce exponencialmente;
- Time que joga junto e disposto a ajudar sempre!

## Contratação

CLT

## Nossa empresa

A Intelipost é uma startup brasileira de tecnologia que está revolucionando o setor logístico no país. Temos um sistema inovador responsável por gerenciar as operações de logística das principais plataformas de E-commerce e Marketplace do mercado.

Somos focados em oferecer sempre a melhor experiência aos nossos clientes e engajados em entregar soluções que modifiquem a forma com que eles pensam e fazem logística no seu dia-a-dia.

Estamos à procura de um novo **#INTELIPOSTER** com olhar analítico, que seja autodirigido e com forte background em JavaScript.

Como parte do Time de Tech você terá a oportunidade de participar de discussões técnicas junto a squad de Produtos, atuar no desenvolvimento de novos recursos e trabalhar na manutenção de aplicativos existentes.

Por aqui somos **#MovidosPorPerformance,** então se você gosta de trabalhar em um ambiente orientado a resultados, ama desafios, é ávido por aprender coisas novas e sente-se á vontade em compartilha-las com seus colegas, a gente quer te conhecer 😉

## Como se candidatar

Me envie um email com seu curriculum e link do LinkedIn no email: bruno.oliveira@intelipost.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruno.oliveira@intelipost.com.br

## Labels

- Alocado
- CLT
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
