### ISSUE TITLE
[SP - São Paulo] SRE-Site Reliability Engineer at Inspetor

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#2028]
A **Inspetor** está nascendo e precisa de você para construir a **maior plataforma anti fraude da América Latina.**

**É tudo do zero!** Estamos escolhendo a melhor infraestrutura e as melhores tecnologias para construir uma plataforma altamente disponível, escalável e consistente à longo prazo. Tudo isso para resolver a dor latente do mercado varejista onde estimasse uma perda de **R$130 Bilhões em fraudes para os próximos 3 anos.** Por isso, estão fortalecendo seu time de tecnologia de alta performance.

A oportunidade é para **Site Reliability Engineer** e estamos buscando pessoas com experiência em **AWS (Lambda), Python, Terraform e NoSQL**. Essas tecnologias mais atualizadas do mercado, em uma empresa fundada por dois Engenheiros de Dados de Stanford e **pessoas com propósito** é o que buscamos para crescer exponencialmente.

A contratação será feita em **regime CLT, além de vários benefícios para atuar de forma presencial na Pinheiros**, em São Paulo. Para mais informações, acesse a página da vaga: https://byintera.in/7k

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
