### ISSUE TITLE
[SÃO PAULO/SP] Back-End (NodeJS) Developer Pleno e Sênior na Bitfy

### ISSUE THREAD

**Issue by m4rtinsp** [backend-br/vagas#2029]
Oportunidade para BACK-END (NODEJS) DEVELOPER PLENO e SÊNIOR na Bitfy.

A Bitfy é a primeira carteira multi-uso de criptomoedas do Brasil, conheça mais em www.bitfy.app

Necessário sólida experiência em:

NodeJS;
MongoDB;
SQL Server (desejável);
Experiencia com AWS.

Detalhes da vaga:

Regime PJ, presencial, em Santo Amaro (próximo a estação) - São Paulo/SP
Remuneração compatível com o mercado

Curtiu? Entre em contato através do e-mail vagas@bitfy.app com "NODEJS" no título do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
