### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Back End [LuizaLabs]

### ISSUE THREAD

**Issue by andressamelo** [backend-br/vagas#203]
### Buscamos pessoas interessadas em oportunidades de pleno ou sênior que:

Sejam apaixonadas por inovação, construção de sistemas e aplicações de alta performance. Que estejam dispostas a fazer experimentações em larga escala e a utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

### Requisitos

- Você ama programar;
- Escreve código limpo, fácil de entender e pensando em sua manutenção;
- É capaz de trabalhar de forma autônoma;
- É capaz de trabalhar em um ambiente multidisciplinar de ritmo acelerado com um cenário competitivo (varejo) onde os dados fluem rapidamente e tudo está em constante mudança;
- Sabe como a Web e uma boa API funcionam;
- Tem fundamentos fortes em estrutura de dados e algoritmos;
- Possui experiência com Python;
- Frameworks web: Django, Flask, Tornado, Muffin, Aiohttp;
- Testes automatizados;
- AWS (EC2, SQS, DynamoDB, outros);
- É curioso(a) e gosta de pesquisar sobre inovação e tecnologia.

### Oferecemos

- Vale Transporte
- Vale Refeição
- Seguro de Vida
- Previdência Privada
- Bolsa Auxílio
- Assist. Odontológica
- Assist. Médica
- 13ª Bolsa Auxílio

### Sobre Nós
[Visitamos o LuizaLabs, o laboratório de inovação do Magazine Luiza](https://conteudo.startse.com.br/startups/taina/visitamos-o-luiza-labs-o-laboratorio-de-inovacao-do-magazine-luiza/)
[O que estamos fazendo](https://medium.com/luizalabs)

### 
[Mais detalhes e inscrição] https://www.99jobs.com/luizalabs/jobs/16144-pesquisa-e-desenvolvimento-desenvolvedor-a-back-end
### Ou envie cv para:
emori.souza@luizalabs.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
