### ISSUE TITLE
[Porto Alegre - Possibilidade de Remoto] Ruby Developer [VNDA]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#2030]
A VNDA está crescendo em um ritmo acelerado, e **precisa de você** para revolucionar o mercado de market places.

Aprimorar a tecnologia para varejo focada na experiência de marca em todos os pontos de contato com o consumidor é o foco da VNDA, que atende cerca de 250 clientes no Brasil através de uma estrutura em modelo SaaS com back-end principalmente em Ruby On Rails e tecnologia toda própria. O escopo principal é uma plataforma de ecommerce, com módulos de CRM, Logística, OMS, Local, Marketplace e outros.

E para este desafio precisamos Devs focados com vontade de crescer. Ter grande conhecimento em **Ruby** On Rails, APIs e PostgreSQL será essencial.

A contratação será feita em regime **PJ**, para atuar de forma remota ou presencial em Porto Alegre. A empresa está disposta a pagar R$ 12.000,00 mas está aberta para negociações de valores até R$ 15.000,00.

Conheça mais sobre a oportunidade: https://byintera.in/7m

**Comment by AlexSJ** [comment]
Me candidatei para Júnior, vi que a senioridade da vaga não é essa, mas caso precisam.

**Comment by AndreBorim** [comment]
> Me candidatei para Júnior, vi que a senioridade da vaga não é essa, mas caso precisam.

Legal, Alex!

**Comment by iagobyintera** [comment]
Onde fica a sede da empresa?

**Comment by renatafarano** [comment]
Qual o endereço da sede da empresa?

**Comment by AlexSJ** [comment]
@iagobyintera  e @renatafarano  são bots?

**Comment by AndreBorim** [comment]
A empresa fica em Porto Alegre, na Germano Petersen Junior, 508, Auxiliadora.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
