### ISSUE TITLE
[Uberlândia] JavaScript [Luizalabs]

### ISSUE THREAD

**Issue by evellyncastro** [backend-br/vagas#2031]
Nós temos a missão de digitalizar o Brasil.

Se você acredita neste propósito e gosta de desafios, queremos te conhecer!

Vem ser feliz!

Descrição das Atividades:
Atuar na codificação do sistema na tecnologia JavaScript conforme arquitetura e padrão de desenvolvimento definidos.

Requisitos:

Conhecimento em linguagem de programação;

Conhecimento de modelagem em banco relacional;

Conhecimento de modelagem de banco Não Relacional, preferência MongoDB;

Conhecimento da linguagem de programação JavaScript, de preferência na plataforma NodeJS;

Conhecimento em: JSON, Joi, ExpressJS, Axios, Mongoose, Swagger;

Conhecimento em testes unitários na plataforma NodeJS (mocha, chai, etc).

Formação Necessária:
Graduação em Ciência da Computação, Sistemas de Informação ou cursos afins.

**Comment by M-Silva-V** [comment]
Enviar o CV por onde?

**Comment by evellyncastro** [comment]
Ola bom dia,

Pode encaminhar por aqui por favor.
[image: magalu] <https://www.magazineluiza.com.br/>
*Evellyn Castro*
Talentos Humanos
34 3221 8813
Esta mensagem é direcionada apenas para os endereços constantes no
cabeçalho inicial. Se você não está listado nos endereços constantes no
cabeçalho, pedimos-lhe que desconsidere completamente o conteúdo dessa
mensagem e cuja cópia, encaminhamento e/ou execução das ações citadas estão
imediatamente anuladas e proibidas. Apesar do Magalu/Luizalabs tomar todas
as precauções razoáveis para assegurar que nenhum vírus esteja presente
nesse e-mail, a empresa não poderá aceitar a responsabilidade por quaisquer
perdas ou danos causados por esse e-mail ou por seus anexos.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
17/01/20
08:46:13

Em qui., 16 de jan. de 2020 às 16:08, Murillo Silva Vieira <
notifications@github.com> escreveu:

**Comment by kassiacatarine** [comment]
Por aonde que é para enviar o CV?

**Comment by abdalla** [comment]
Uia... contrata eu :)

Todos os requisitos em um unico projeto OSS meu: https://github.com/abdalla/node-auth

Pode ser remoto?

**Comment by alannsiqueira** [comment]
Aceita remoto?

**Comment by evellyncastro** [comment]
Ola bom dia,

Nossas oportunidades hoje são todas presenciais, ainda não trabalhamos em
regime remoto.

Dúvidas estou a disposição, ótima semana!
[image: magalu] <https://www.magazineluiza.com.br/>
*Evellyn Castro*
Talentos Humanos
34 3221 8813
Esta mensagem é direcionada apenas para os endereços constantes no
cabeçalho inicial. Se você não está listado nos endereços constantes no
cabeçalho, pedimos-lhe que desconsidere completamente o conteúdo dessa
mensagem e cuja cópia, encaminhamento e/ou execução das ações citadas estão
imediatamente anuladas e proibidas. Apesar do Magalu/Luizalabs tomar todas
as precauções razoáveis para assegurar que nenhum vírus esteja presente
nesse e-mail, a empresa não poderá aceitar a responsabilidade por quaisquer
perdas ou danos causados por esse e-mail ou por seus anexos.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/02/20
08:24:24

Em dom., 2 de fev. de 2020 às 21:58, Alan Siqueira <notifications@github.com>
escreveu:

**Comment by danieldfc** [comment]
Precisa ter a formação completa? Tenho conhecimentos nesses requisitos,
caso esteja disponível, e remoto, mando agora meu currículo.

https://github.com/danieldfc
Esse é meu repositório do github

**Comment by evellyncastro** [comment]
Ola bom dia,

Nossas oportunidades são todas presenciais, não trabalhamos com regime
remoto.

Segue o link do nosso site com os requisitos das vagas caso tenha
interesse  https://softbox.com.br/oportunidades/

Dúvidas estou à disposição, ótima semana!
[image: magalu] <https://www.magazineluiza.com.br/>
*Evellyn Castro*
Talentos Humanos
34 3221 8813
Esta mensagem é direcionada apenas para os endereços constantes no
cabeçalho inicial. Se você não está listado nos endereços constantes no
cabeçalho, pedimos-lhe que desconsidere completamente o conteúdo dessa
mensagem e cuja cópia, encaminhamento e/ou execução das ações citadas estão
imediatamente anuladas e proibidas. Apesar do Magalu/Luizalabs tomar todas
as precauções razoáveis para assegurar que nenhum vírus esteja presente
nesse e-mail, a empresa não poderá aceitar a responsabilidade por quaisquer
perdas ou danos causados por esse e-mail ou por seus anexos.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/02/20
09:28:06

Em seg., 3 de fev. de 2020 às 20:27, Daniel Felizardo <
notifications@github.com> escreveu:

> Precisa ter a formação completa? Tenho conhecimentos nesses requisitos,
> caso esteja disponível, e remoto, mando agora meu currículo.
>
> https://github.com/danieldfc
> Esse é meu repositório do github
>

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
