### ISSUE TITLE
[REMOTO] Desenvolvedor Backend/Full-stack Ruby on Rails

### ISSUE THREAD

**Issue by augustocsmartins** [backend-br/vagas#2032]
![Repassa](https://www.repassa.com.br/assets/logo-cb6efa31d43dd0c712b9765635fe7bdc.svg)

# Desenvolvedor Backend/Full-stack Ruby on Rails

## Especialidade
Backend/Full-stack

## Tempo de experiência
4-6 anos

## Tecnologias Essenciais
Ruby on Rails, Ruby

## Tecnologias desejáveis
Testes automatizados, Linux, Continuous Integration/Deployment(CI/CD), Azure, Microserviços

## Modalidade de trabalho
Remoto

## Palavras chave
ruby, rails, api, ecomerce

## Faixa Salarial (CLT)
6K a 8K

## Benefícios
Plano de saúde, Vale refeição

## Descrição
O Repassa é uma plataforma de compra e venda de roupas gentilmente usadas, que garante 100% de praticidade para quem vende e 100% de segurança para quem compra. Nosso propósito é dar mais ciclos de vida para as nossas roupas e gerar impacto ambiental e social positivos no processo. Estamos aqui para fazer o bem e buscamos profissionais talentosos, ambiciosos e que também tenham a ambição de fazer o bem através de seu trabalho. 

Nossos principais valores são: ser do bem em tudo o que fazemos, liberdade e responsabilidade, melhoria contínua (para a empresa e para as pessoas) e espírito empreendedor. Se você se identifica com nossos valores e quer fazer impulsionar o crescimento e a consolidação de uma Startup de impacto, o Repassa é o lugar certo para você.

O trabalho é remoto, mas nada impede você ir na sede em São Paulo/SP e passar o dia com o restante das equipe e ter mais contato com a cultura interna da empresa. O ambiente é leve e o horário de trabalho é flexível (mas você precisa pelo menos trabalhar 8 horas por dia). Além disso, você recebe de benefício o vale-refeição e Plano de Saúde.

Sobre a vaga de trabalho, estamos recriando a nova versão do Repassa e por isso o código fonte será reescrito utilizando boas práticas e metodologias de desenvolvimento. No inicio, você irá trabalhar em uma das equipes de reconstrução, mas terá contato com o código do site atual para entender o funcionamento. Para isso precisamos que você tenha bons conhecimentos em:

• Domínio da linguagem Ruby e experiência com o framework Rails;

• Experiência com modelagem de banco de dados, SQL e NoSQL;

• API’s GraphQL e REST (integrações de terceiros);

• Conhecimento em HTML, CSS e Javascript;

• Empregar as melhores práticas de desenvolvimento para entregar código limpo e de qualidade;

• Domínio de sistemas de controle de versão (git) e testes automátizados;

• Conhecimento em metodologias ágeis (Scrum/Kanban);

• Conhecimentos de TDD (Test Driven Development);

• Boa comunicação para trabalho em equipe remota;

• Mínimo de conhecimento em Linux;

Conta como grande diferencial, a vivência em comércio eletrônico, meios de pagamento ou conhecimento sobre marketplaces. 
Além disso, estar ligado em novas tecnologias utilizadas pelo mercado, bem como possuir conhecimento sobre frontend, React, Node, usabilidade UI/UX.

## Envie seu currículo para Augusto Cesar em “tec [arroba] repassa [ponto] com [ponto] br”

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
