### ISSUE TITLE
[São Paulo - Possibilidade de Remoto]  Senior Back-End Developer [INGRESSE]

### ISSUE THREAD

**Issue by renatafarano** [backend-br/vagas#2034]
A INGRESSE está crescendo em um ritmo acelerado, e **precisa de você** para revolucionar o mercado de ingressos online.

A sua missão vai muito além de facilitar a compra e venda de ingressos online. Para os seus usuários, querem atuar cada vez mais como a **plataforma de experiências off-line** de referência no Brasil. Festivais, shows, conferências, feiras, exposições, e-games, eventos universitários… qualquer que seja o evento, de qualidade e de interesse dos seus usuários, eles estarão lá!

Estão evoluindo a cada dia, usando de tecnologia, design e interação com seus clientes e usuários, para serem cada vez melhor no que fazem. E estão de portas abertas para quem quiser fazer parte dessa jornada.

Vivência com desenvolvimento de API’s e experiência avançada em Python são requisitos importantes para essa oportunidade.

A contratação será feita em regime CLT, para atuar de forma **remota ou presencial** em São Paulo. 

Conheça mais sobre a oportunidade: https://byintera.in/7n

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
