### ISSUE TITLE
[Curitiba / PR] .Net Developer Full Stack (P144TS) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2035]
## Description
Ei, Dev., temos uma oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!

O que você irá fazer por aqui:

Você irá trabalhar com a criação e manutenção de uma aplicação voltada para compras de seguro para caminhões. Inicialmente você atuará no frontend da aplicação, depois assumirá o backend com outros integrantes do projeto.

## Onde ficamos:

Curitiba, PR.

## Requirements
Experiência com React.Js, JavaScript, API, REST, .Net Core, MVC, Aplicações WEB.

## Benefits
Confira os nossos benefícios:

Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo
GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

## Canditar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by jonathanguilhermesouza** [comment]
@cezarsg CLT ? Apenas presencial?

**Comment by cezarsg** [comment]
Bom dia, isso mesmo!

Em qua, 22 de jan de 2020 08:21, Jonathan Guilherme <
notifications@github.com> escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
