### ISSUE TITLE
[Curitiba / PR] PHP Web Developer (I179AB) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2036]
## Description
We are a company from Paraná, we have more than 27 years of histories, among them CMMI level 3 and GPTW for the 8th year in a row! We work with Software Solutions. We have a very well-structured factory that serves national and international clients. Outsourcing, CINQ professionals who work in clients of different segments and sizes.

We work with the focus of building careers and transforming lives!

## Requirements
Activities:

Content Management;
Create and publish engaging content;
Optimize content according to SEO;
Responsible for helping formulate an effective, responsive design and turning it into a working theme. * Work closely with back-end developers and customers to ensure an effective, visually appealing, and intuitive implementation.

## Where:

Curitiba, PR.

## Workload:

40h/week,

## Skills and Qualifications:

Web Development: Html, JavaScript, CSS, JQuery
Language: PHP
Knowledge in content management frameworks
Database: MySQL

## Differentials:

Drupal Content Managment.

## Languages:

English - Advanced/Fluent.

## Benefits
Health Plan
Odontological Plan
Life Insurance
Pension Plan
Meal Ticket
Market Ticket
Educational Aid

## Candidatar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
