### ISSUE TITLE
[Curitiba / PR] Desenvolvedor PHP PL (I250AB) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2037]
## Description
Ei, Dev., temos uma oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!

## O que você irá fazer por aqui:

Startup norte americana que possui solução para atender o mercado de manutenção de dispositivos móveis, possuindo integração com assistências técnicas autorizadas, operadoras de telefonia, seguradoras, escolas e outras entidades.

## Atividades a serem executadas:

Desenvolvimento de software utilizando PHP e Framework Yii;

Auxiliar em definições de design e arquitetura;
Auxiliar na tradução da aplicação de inglês para português;
Implementar APIs Rest;
Correção de defeitos;
Testes unitários;
Atuar em time SCRUM com interface diária com clientes nos EUA;

## Onde ficamos:

Curitiba, PR.

## Requirements
PHP, Rest APIs
Inglês Avançado

## Conhecimentos Desejáveis:

Yii Framework

## Benefits
Confira os nossos benefícios:

Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo
GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

**Comment by romulo2735** [comment]
aceita remoto ?

**Comment by cezarsg** [comment]
Bom dia, não aceita.

Em qui., 16 de jan. de 2020 às 10:22, Romulo Sousa <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
