### ISSUE TITLE
[Curitiba / PR] Desenvolvedor .NET Core SR (P215WJ) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2038]
## Description
Ei, Dev .Net: temos uma super oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!

## Sobre o Projeto:

Profissional irá desenvolver/manutenir aplicativo ( feito em Angular 6 e .Net Core 2.2 ) para criação de mapas para ferrovias.
Irá atuar também em aplicativo que coleta dados de hardware e faz analise de viagens, gerando gráficos e estatísticas.
A maior parte dos nossos aplicativos são web api (container Docker) e rodam no Kubernetes na AWS, alguns deles são instalados direto na infra do cliente.
Irá trabalhar em um ambiente heterogêneo - Linux e Windows

## Onde ficamos:

Colombo, PR.

## Requirements
.Net Core (C#)
Entity Framework Core
Web Api
Git
Docker
SQL Server
Oracle
Postgres
Inglês intermediário

## Benefits
Confira os nossos benefícios:

Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo
GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

## Benefícios que só a CINQ oferece:

Aqui, nosso foco é construir carreiras e transformar rotinas, por isso, não enfatizamos apenas a tecnologia - prezamos o cuidado com nossos colaboradores, com o ambiente e com os projetos. Para isso, temos o nosso programa de desenvolvimento, o CINQ TECH, que existe para que seja possível incentivar o Time CINQ a melhorar cada vez mais. Investimos em treinamentos técnicos que ajudam também com as capacidades pessoais, tornando tanto o profissional quanto o projeto mais qualificado.

Isso é ser CINQ: trabalhar em um ambiente moderno, tecnológico, inovador e flexível - It’s beyond technology.

## Candidatar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
