### ISSUE TITLE
[Curitiba / PR] Desenvolvedor .NET Core Pleno (P177WJ) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2039]
## Description
Ei, Dev .Net: temos uma super oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!

## Sobre o Projeto:

Os referidos projetos têm como característica a modelagem ou arquitetura de software escaláveis
de alta disponibilidade e desempenho, modelagem e consumo de banco de dados relacional e
também baseados em documentos, codificação de programas com interface web,
desenvolvimento de webservices – considerando, inclusive, integrações com outros sistemas, e
desenvolvimento de indicadores e/ou relatórios.

## Onde ficamos:

Curitiba, PR.

## Requirements
O que estamos buscando:

• Desenvolvimento em C# - .Net Core 2 ou acima
• SQL Server / Oracle
• Docker
• Microsserviços
• Message Broker (ferramenta de mensageria, de preferência RabbitMQ)
• Versionamento de código (preferência com git)
• WebApi REST
• Windows Services / Linux Daemons

## Benefits
Confira os nossos benefícios:

Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo
GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

## Benefícios que só a CINQ oferece:

Aqui, nosso foco é construir carreiras e transformar rotinas, por isso, não enfatizamos apenas a tecnologia - prezamos o cuidado com nossos colaboradores, com o ambiente e com os projetos. Para isso, temos o nosso programa de desenvolvimento, o CINQ TECH, que existe para que seja possível incentivar o Time CINQ a melhorar cada vez mais. Investimos em treinamentos técnicos que ajudam também com as capacidades pessoais, tornando tanto o profissional quanto o projeto mais qualificado.

Isso é ser CINQ: trabalhar em um ambiente moderno, tecnológico, inovador e flexível - It’s beyond technology.

## Candidatar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
