### ISSUE TITLE
[Remoto] Python Junior na Instruct

### ISSUE THREAD

**Issue by iassia** [backend-br/vagas#2040]
Estamos buscando profissional que consiga trabalhar em um time multidisciplinar, que tenha sólidos conhecimentos de programação e bons fundamentos de sistemas operacionais e redes.

**Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.**

Precisamos que você conheça Python em ambiente Linux.

É fundamental que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem vindas.

O trabalho poderá ser realizado totalmente remoto, dentro de horário comercial e seguindo o horário de Brasília, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente dentro da faixa salarial inicial da empresa.

**Benefícios**

- Regime de contratação CLT;
- Salário inicial entre R$ 2.000,00 e R$ 3.000,00;
- Plano de saúde e odontológico Bradesco Top Nacional Top para o titular e seus dependentes;
- Vale refeição de R$ 400,00;
- Vale alimentação de R$ 600,00;
- Seguro de vida corporativo custeado pela empresa;
- Acesso aos treinamentos da empresa sem custos;
- Prêmio de participação nos resultados;
- Prêmio quando se completa aniversário de empresa;
- A empresa fornecerá um laptop com as seguintes configurações: Dell Inspiron 14 5480 (Core i7-8565U, RAM 16GB, GeForce MX150, HDD 1TB, SSD 128GB, Full HD);

**Por que trabalhar na Instruct?**

- Ambiente de trabalho amigável, inclusivo e seguro;
- Resolvemos problemas desafiadores e em larga escala para nossos clientes;
- Incentivos para participação em eventos, cursos e palestras;
- Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
- Cultura blameless;
- Café de qualidade!

**O que esperamos de você?**

- Esperamos que nos ajude a melhorar a performance dos nossos clientes;
- Esperamos que você consiga se relacionar bem com o seu time de trabalho, que saiba fazer parte do time, respeitar o time, dividir e compartilhar responsabilidades, acertos e aprendizados;
- Esperamos que você possa ir além, propondo, criando, mudando, construindo, crescendo e evoluindo junto conosco;
- Queremos que você agregue valor ao nosso time e a nossa organização, e queremos que a nossa organização agregue valor a você; 

**Tecnologias com as quais trabalhamos:**
Conhecimentos e experiências fundamentais:

- Linguagem Python 3 e bons conhecimentos sobre orientação a objeto;
- Fundamentos de banco de dados relacional/SQL;
- Fundamentos de sistemas operacionais e Linux;
- Comunicação via APIs REST;
- Uso de Git para versionamento de seu código; 

**Conhecimentos diferenciais:**

- Curso superior;
- Python Celery;
- Python asyncio;
- JavaScript e Node.js;
- Frameworks e bibliotecas de desenvolvimento frontend;
- Testes unitários;

**Tecnologias e métodos**
Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:

- Fundamentos de modelos ágeis como Kanban e Scrum;
- Fundamentos do conceito testes unitários;
- Fundamentos do conceito testes de aceitação;
- MySQL ou PostgreSQL;
- GitLab CI;
- Participação em projetos Open Source;

Local: Remoto com encontros presenciais
Horário: Comercial das 9h às 18h (40h semanais)

Enviar um e-mail com CV para jobs@instruct.com.br
com assunto "Desenvolvedor(a) Python Junior".

**Comment by marcossilvaxx** [comment]
Possibilidade de horário flexível?
