### ISSUE TITLE
[PR-Curitiba] Desenvolvedor(a) Back-End na Vega I.T.

### ISSUE THREAD

**Issue by heitorri** [backend-br/vagas#2044]
### Local
Curitiba - PR

### Benefícios
* Horário flexível;
* Café fresquinho à vontade;
* Barbecue + Happy Hour mensal;
* Quick Massage;
* Gympass;
* Beauty Day com barbearia e manicure;
* Inglês In Company;
* Auxílio para cursos e palestras;
* Plano de Saúde;
* Plano Odontológico;
* Refeição no local;
* Vale-transporte.

### Requisitos
* Desenvolvimento de APIs usando linguagens modernas usando Frameworks;
* Modelagem de dados relacional e não relacional (MySQL, PostgreSQL, MongoDB);
* Familiaridade com infraestrutura AWS, GCP ou Azure;
* Vivência em ambiente com integração e entrega contínua;
* Desing patterns, Clean Code, SOLID;
* TDD e BDD;
* Criação de ambientes usando containers.

### Diferenciais:
* Conhecimento em arquitetura de software;
* Familiaridade com o Agile;
* Experiência com teste unitário e depuração;
* Mecanismos de cache e filas;
* FaaS;
* Jenkins;
* GraphQL

### Contratação
CLT

### Como se candidatar
Enviar currículo para: rh@vegait.com.br com seu CV anexado - enviar no assunto: Vaga Back-End

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Essa vaga pode ser remota?
Sou do Rio de Janeiro. =)
http://danielsiqueira.net

**Comment by heitorri** [comment]
Oi Daniel, 

pode submeter seu CV no  rh@vegait.com.br com seu CV anexado e no assunto colocar Vaga Back-End, vamos analisar seu CV e caso se encaixe, entramos em contato.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
