### ISSUE TITLE
[Portugal] PHP FullStack Developer [Aubay]

### ISSUE THREAD

**Issue by festaca** [backend-br/vagas#2046]
### A nossa empresa:
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas, desenvolvemos projectos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### Descrição da vaga:
Projecto internacional para trabalhar em Portugal, em vários sectores de actividade, usando diversas tecnologias Microsoft.

### Local:
Portugal: Lisboa ou Porto

### Benefícios:
• Visto de trabalho/autorização de residência
• Apoio jurídico e legal durante todo o processo
• Contrato de trabalho
• Passagem do avião
• Ajuda em alojamento
• Projetos inovadores nacionais e internacionais
• Oportunidades de formação todas as semanas
• Café e lanche grátis
• Entre outros
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívios mensais
• Oferta de aniversário
• Projetos dinâmicos

### Requisitos Obrigatórios:
• Experiência mínima de 4 anos em funções de desenvolvimento de software
• Experiência em desenvolvimento PHP e frameworks Laravel, CodeIgniter, Symfony, Zend ou Phalcon
• Experiência em desenvolvimento Javascript
• Nível de Inglês Avançado (obrigatório)

### Diferenciais:
• Conhecimentos em frameworks React ou Angular 2+
• Experiência profissional com cloud pública
• Experiência internacional

### Como se candidatar?
Por favor envie para fpiedade@aubay.com com seu CV em inglês anexado colocando no assunto
Candidato_Internacional_PHP

**Comment by THAYLLER** [comment]
nao rola um home office?

**Comment by festaca** [comment]
@THAYLLER tal como indicado no anúncio a vaga é para trabalhar em portugal. obrigado pelo teu interesse!

**Comment by ismaelguimaraes** [comment]
Possibilidade pra Junior com bastante vontade de crescimento?
