### ISSUE TITLE
Coordenador de Desenvolvimento de Software

### ISSUE THREAD

**Issue by Folks-Meliuz** [backend-br/vagas#2048]
## Descrição da vaga

Estamos crescendo e para isso acontecer procuramos uma pessoa para gerir e coordenar o time de pessoas desenvolvedoras do Méliuz.
Esta pessoa terá contato com times multidisciplinares fora da curva, tanto na área de desenvolvimento de software, bem como em desenvolvimento de produto.
Aqui você fará parte de um time fora de série, que ama seus clientes e tem como desafio transformar o Méliuz na melhor empresa de e-commerce e relacionamento do Brasil!
Se você ficou interessado nas nossas ideias e adoraria conviver em um ambiente inovador, em que os seus resultados terão impacto direto no negócio, venha trabalhar conosco!
## Benefícios 
- Vale transporte;
- Vale refeição ou alimentação;
- Plano de saúde;
- Plano odontológico;
- GymPass;
- Horário flexível;
- Estacionamento no local;
- Cashback online em dobro no Méliuz!

## Requisitos

- Formação superior em Ciência da Computação, Tecnologia da Informação e/ou áreas correlatas.
- Atuação anterior em desenvolvimento de software;
- Ter atuado como líder técnico ou gestor de pessoas na área de desenvolvimento de software;
- Alto conhecimento em metodologias de desenvolvimento de software;
## Diferenciais
- Certificações: Desenvolvimento Ágil (Scrum, Kanban, Lean, e outros);

## Como se candidatar
Entre no nosso site e faça seu cadastro: https://jobs.lever.co/meliuz

## Nossa empresa
Somos a maior empresa de cashback do Brasil e buscamos desbloquear relações inteligentes de consumo!
Atuamos criando oportunidades para todo mundo ganhar mais! Por meio de um programa de cashback, que devolve dinheiro para milhões de consumidores brasileiros, o Méliuz promove a fidelização e a otimização dos investimentos de suas lojas parceiras.
Somos apaixonados por nossos clientes e acreditamos no consumo inteligente, onde todas as partes sempre ganham: as lojas, pois aumentam suas vendas e retêm os clientes; o Méliuz, que recebe por cada venda feita; e os consumidores, que são recompensados de verdade por suas compras.

## Labels

- CLT

- Presencial
- Coordenador

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
