### ISSUE TITLE
[São Paulo] Desenvolvedor Back End no Guiabolso

### ISSUE THREAD

**Issue by amandagasineo** [backend-br/vagas#2049]
O **GuiaBolso** está crescendo e precisa de você para construir um novo produto.

Acreditamos que as melhores ideias surgem quando as pessoas estão trabalhando por um **propósito maior**. Trabalhar no Guiabolso é ter a oportunidade de lidar com **grandes desafios**, **crescer** bastante e fazer parte de uma startup jovem, dinâmica e que sempre coloca as pessoas em primeiro lugar! Aqui todo mundo tem **liberdade** para protagonizar projetos que impactam vidas!

A nossa tecnologia está sendo construída utilizando **Java e Kotlin**, mas principalmente utilizando **Microserviços** – no entanto, sabemos que bons devs são feitos muito mais do que mera sintaxe. Por isso, não estamos realmente presos a qual stack você usa – e sim se você emprega/ama/usa conceitos e práticas como **Clean Architecture, Clean Code, Design Patterns, S.O.L.I.D**. Somos heavy users de **AWS** e é fundamental ter alguma familiaridade com ferramentas de **CI/CD**!

A contratação será feita em **regime CLT com horário flexível**! Estamos na WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

**Link da oportunidade**: https://byintera.in/beguiabolso
**Dúvidas**: https://linkedin.com/in/amanda-gasinêo-98b42b134

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
