### ISSUE TITLE
[Rio de Janeiro - RJ] Back-End Developer na TVManager

### ISSUE THREAD

**Issue by danielcozer** [backend-br/vagas#205]
## Descrição da vaga

Somos uma Startup especializada em inovações em mídia, desenhadas para atender o mercado televisivo e produtores de conteúdo audiovisual. Não importa sua formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma extremamente inovadora para o mercado !

Perfil desejado: 

• Back-end / full-stack
• Alocado / modelo híbrido 
• Junior / pleno 

## Local

Rio de Janeiro, Centro da cidade

## Requisitos

**Obrigatórios:**

• Fluência em Javascript 
• Desenvolvimento de sistemas: Node js. 
• Domínio do stack MEAN 
• Experiência com AngularJs; 
• Experiência de controle de versão de código-fonte (Git); 
• Acompanhar coordenar testes e homologações de sistemas. 
• Familiaridade com o git-flow.
• Ajudar a construir o software ao em vez de apenas codar requisitos! participar ativamente da concepção e construção da TVManager

**Desejáveis:**

• Experiência em Metodologias ágeis; 
• Testes Automatizados e integração contínua; 
• Experiência com Sistemas Web / SaaS

**Diferenciais:**

• Familiaridade com Docker; 
• Familiaridade com Sails framework 
• Familiaridade com micro-serviços;

## Contratação

A combinar

## Nossa empresa

• Maiores informações em: www.TVeStore.com 
• Vídeo explicativo da Solução: https://player.vimeo.com/video/250085951

## Como se candidatar

Por favor envie um email para **daniel@tvestore.com** com o seguinte título e informações:

• Assunto [VAGA] Desenvolvedor Back-end 
• Currículo ou Linkedin
• Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)

## Labels

- Alocado
- Remoto - Parcial
- Júnior
- Pleno
- JavaScript
- Sails. JS

**Comment by Murillofilho86** [comment]
São os mesmos requisitos pra junior e pleno?

**Comment by danielcozer** [comment]
Isso !

**Comment by guilhermeoa07** [comment]
Uai. Se são os mesmos requisitos. Qual a diferença entre Jr e pleno?

**Comment by danielcozer** [comment]
Olá Guilherme !

A diferença é a profundidade e nível de conhecimento do dev no stack que
utilizamos.

Sabemos que o Jr normalmente vai ter uma curva de aprendizado maior, mas
precisamos que ele conheça pelo básico dos requisitos. Enquanto o pleno
esperamos que já possua domínio das tecnologia utilizadas na plataforma

2018-05-14 23:04 GMT-03:00 Guilherme Oliveira <notifications@github.com>:
