### ISSUE TITLE
Desenvolvedor Web na SONDA [Campina Grande-PB]

### ISSUE THREAD

**Issue by jair-anderson-souza** [backend-br/vagas#2050]
Conhecimentos desejáveis

- Algoritmo e estrutura de dados;

- JSP;

- Struts;

- Hibernate;

- Eclipse.

- Complementar

- EJB;

- SCRUM;

- Banco de Dados relacional;

- Padrões de Projeto;

- TDD;

- Integração contínua;

- SVN/GIT.

LinkedIn: https://www.linkedin.com/jobs/view/1689708600/?alternateChannel=search

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
