### ISSUE TITLE
[Recife] VAGA DE ESTÁGIO DESENVOLVEDOR WEB .NET

### ISSUE THREAD

**Issue by elvislourenco** [backend-br/vagas#2051]
A App7 Sistemas está procurando novos talentos para se juntarem ao novo time de desenvolvimento situado no escritório em Recife/PE.  Se você gosta de programar e deseja ingressar no mercado de trabalho e desenvolver as habilidades necessárias para o sucesso de sua carreira, esta vaga é para você!

**Quais são os requisitos mínimos exigidos?**
 •	Estar cursando Superior em Análise e Desenvolvimento de Sistemas, Ciências da Computação ou demais cursos de tecnologia. 
 •	Conhecer a linguagem de programação C# com enfâse em Web
 •	Conhecer a estrutura Microsoft .NET Framework e/ou .NET Core 

**Se você tiver o conhecimentos abaixo é um diferencial:**
 •	T-SQL para SQL Server
 •	Arquitetura MVC
 •	Javascript

**Quais serão as atividades desenvolvidas?**
O estagiário irá atuar na construção e manutenção de Web Api's e futuramente, conforme sua curva de aprendizado, irá atuar e lidar com diversas tecnologias e frameworks do mercado, como Angular para aplicações web, React Native para aplicações Mobile e Docker para orquestração de aplicações. Alem de conhecer e dominar estrutura de banco de dados relacional, aplicações MVC e DevOps.

**Competências:**
•	Saber trabalhar em equipe;
•	Procurar sempre se atualizar em novas tecnologias;
•	Dinamismo e proatividade;
•	Gostar de estudar e novos desafios;

**Local, Carga horária e Expediente:**
Local: Boa Viagem, Recife, PE
 Carga Horária : 6h
 Expediente: Manhã – das 09h as 15h e Tarde – das 14h as 20h.
 *temos vagas para os 2 períodos que melhor encaixe no horário do seu curso.  

**Remuneração:**
Bolsa-auxílio : R$ 1.500,00 
Benefícios: Vale Transporte + Vale Refeição  

Caso você tenha o perfil acima e queira participar do processo seletivo ou conheça alguém, favor enviar currículo atualizado para elvis@app7sistemas.com com o cargo no assunto do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
