### ISSUE TITLE
[Niterói] Back-End Developer na [Internit]

### ISSUE THREAD

**Issue by Fredpeixoto** [backend-br/vagas#2052]
**VAGA DE ESTÁGIO PARA PROGRAMADOR PHP EM NITERÓI**

Que tal começar o ano trabalhando!

Saca de PHP e MySQL?

Estamos abrindo mais uma vaga de estágio na Internit, empresa localizada em Niterói que há 23 anos desenvolve sites, lojas virtuais, portais, aplicativos, intranets e outros sistemas web.

**REQUISITOS OBRIGATÓRIOS:**
Estar cursando faculdade em cursos da área de TI, cadastro do currículo em nosso site, conhecimento de PHP, MySQL, Java Script, Html5, Programação orientação a objeto e GIT;

**DIFERENCIAIS:**
Profissionais com experiência em Symfony3 ou +

**O QUE OFERECEMOS?**
Ótimo ambiente de trabalho somado à desafios constantes. Bolsa + Vale Transporte + Seguro contra acidentes pessoais + Bicicletário na empresa. Estamos situados em uma rua tranquila com facilidade de estacionamento.

**COMO SE CANDIDATAR?**

Acesse http://www.internit.com.br/curriculo e cadastre seu currículo.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
