### ISSUE TITLE
[São Paulo] SRE na Inspetor

### ISSUE THREAD

**Issue by fcjonas** [backend-br/vagas#2053]
**É tudo do zero!** A Inspetor está nascendo e precisa do melhor time para construir a plataforma anti fraude da América Latina. Para mais informações, acesse a página da vaga: https://byintera.in/7i 

**Criada por ex-alunos de Stanford e com passagens pela Palantir Technologies**, a missão do Inspetor é permitir que os e-commerces se concentrem no que fazem de melhor e criar soluções que o mercado precisa sem perder o sono (ou tempo e dinheiro) devido a ataques fraudulentos.

Nossa visão de produto depende principalmente da ingestão, processamento e análise de dados confiáveis e eficazes. Isso significa que precisamos de um sistema robusto e confiável. Para a posição de Site Reliability Engineer, estamos procurando talentos dispostos a se encarregar de projetar, construir e manter nossa arquitetura de sistema. Você fará parceria com o time de engenharia para garantir que todos os componentes de nosso sistema antifraude tenham alto desempenho, escalável, estável e seguro.

### **Requisitos Técnicos**

- Python
- AWS (Kinesis, RDS, ECS, API Gateway)
- Terraform, Serverless ou Packer
- NoSQL

### **Diferenciais**

- Bash
- Inglês fluente ou avançado

A contratação será feita em regime CLT, para atuar de forma presencial na Pinheiros, em São Paulo. Para mais informações, acesse a página da vaga: https://byintera.in/7i ou falando com nosso tech recruiter: https://www.linkedin.com/in/jfcornelio/.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
