### ISSUE TITLE
[Remoto] Fullstack Developer na Onyo

### ISSUE THREAD

**Issue by komyg** [backend-br/vagas#2054]
# Fullstack Developer na Onyo

A experiência de refeição fora do lar nunca mais será a mesma. É por isso que estamos à procura de um Desenvolvedor Full Stack para uma missão que ajudará a colocar nas mãos de nossos clientes o poder absoluto de escolher, o quê e quando comer independe. Você desenvolverá produtos incríveis, que irão transformar a vida dos nossos clientes e parceiros.

## Sobre nós:

Temos uma forte cultura moldada pelos nossos valores. Quer conhecer todos os 7 valores? 

Vamos conversar! Por enquanto vamos contar três 

- "Trabalhamos em equipe, valorizando todas as contribuições individuais".
- "Somos máquinas de aprender”
- "A melhor experiência do cliente é o que nos guia”

## Como trabalhamos:

- Damos um alto valor ao poder de escolha em todos os assuntos, desde o design do código até opções de vida, podendo também decidir de onde quer trabalhar.
- Trabalhamos remotamente.
- Amamos desafios e os encaramos de frente sem medo.
- Acreditamos que temos sempre o melhor time, e você pode ser parte disso.

## Assim que ingressar em nosso time, esperamos de você:

- Contribuir com a concepção do produto como um todo para entregar a melhor experiência para os nossos usuários.
- Contribuir na implementação de novas features do zero, bem como melhorar o código existente.
- Ser dono do produto e lutar para a sua melhoria e o seu sucesso.
- Escrever um código limpo, testável e de alta qualidade.
- Resolver débitos técnicos.

## O que estamos procurando nas suas habilidades:

- Experiência com desenvolvimento Python e frameworks web como Django.
- Experiência com Frameworks de SPAs como Angular ou React.
- Experiência com GraphQL, Docker e Kubernetes é um diferencial.
- Experiência com trabalho remoto é um diferencial.

Venha trabalhar conosco e torne-se parte de uma empresa em franco crescimento, onde você pode moldar o futuro de nossos processos de trabalho, nossa empresa e sua carreira.

## Link para Inscrição

Use este link para se inscrever no nosso processo seletivo: https://onyo.recruiterbox.com/jobs/fk03gra?source=backend-br.

**Comment by komyg** [comment]
As inscrições continuam abertas!

**Comment by THAYLLER** [comment]
temque ter experiencia em todas as tecnologias que foram setadas?

**Comment by komyg** [comment]
Oi @THAYLLER,

Não, o mínimo que estamos procurando é alguém que tenha experiência com algum framework web de Python (principalmente Django) e com algum framework de SPA, especialmente Angular ou React.

Porém experiência com as outras tecnologias citadas é um diferencial.

Obrigado,
Felipe

**Comment by THAYLLER** [comment]
Entendi agora uma pena que não trabalho com python
