### ISSUE TITLE
[GSW] Desenvolvedor Node.js Pleno [São José dos Campos]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#2059]
**Desenvolvedor Node.js Pleno**

Atuar com:
Nodejs; MongoDB;
javascript; PostgreSQL;
React

.Projeto voltado a inovações!
Cidade: São José dos Campos

E-mail para contato: mariana.bompean@gsw.com.br

**Labels**

- PJ + Benefícios
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
