### ISSUE TITLE
[Curitiba] Back-End Developer na Nuvem Mestra

### ISSUE THREAD

**Issue by diegosoek** [backend-br/vagas#206]
# VAGA: BACKEND PHP LARAVEL em Curitiba
Empresa: Nuvem Mestra
Local: Curitiba PR
Remoto: Não 
Contratação: PJ
## Horas
+ Reembolso de Alimentação
+ Reembolso de Transporte ou reembolso de km rodado e estacionamento. 
## Requisitos:
- PHP OO
- HTML
- JAVASCRIPT
- CSS
- MYSQL
- LARAVEL
- COMUNICAÇÃO
## Diferenciais:
- LINUX
- GIT
- NODE
- ANGULAR
## COMO SE CANDIDATAR
- Enviar currículo com pretensão: ds@mestra.org

**Comment by franciscooliver** [comment]
Em seg, 14 de mai de 2018 18:18, Diego José Soek <notifications@github.com>
escreveu:

**Comment by brunokunace** [comment]
"Remoto: não"  =(

**Comment by diegosoek** [comment]
@brunokunace Infelizmente o projeto está em um estado muito crítico. Por enquanto não conseguimos abrir remoto, mas num futuro breve quem sabe :)
