### ISSUE TITLE
[Belo Horizonte] PHP Developer na Symplicity Brasil

### ISSUE THREAD

**Issue by cecimeira** [backend-br/vagas#2060]
## Nossa empresa

A Symplicity é uma empresa de tecnologia dos EUA que possui o software líder mundial em sucesso para estudantes. Com duas décadas de experiência no espaço de Tecnologia Educacional, estamos presentes em mais de 1.000 universidades em todo o mundo.
A Symplicity adquiriu recentemente a Contratanet, a maior rede integrada de portais de carreira para Instituições de Ensino no Brasil, fortalecendo suas operações no país e está recrutando talentos para trabalhar em nosso escritório em Belo Horizonte.

## Local

Savassi, Belo Horizonte - MG

## Benefícios

- Plano de Saúde Allianz
- Plano Odonto Inpao
- Sodexo - VR ou VA
- VT
- 40 horas semanais com flexibilidade
- Snacks
- Ginástica Laboral
- Aulas de Inglês
- Experiência Global

## Requisitos

**Obrigatórios:**
• Experiência em tecnologias PHP;
• Conhecimento de design orientado a objetos e padrões de design de software;
• Confortável com a linha de comando do Unix / Linux;
• Conhecimento de controle de versão, como o GIT;
• Conversação em inglês para colaboração com nossas equipes baseadas nos EUA;
• Experiência com banco de dados MySQL.

**Diferenciais:**
• Ter trabalhado em empresa de Produtos de Software;
• Experiência de mercado no desenvolvimento de Web (preferencialmente backend)
• Experiência anterior em equipes de desenvolvimento de produtos em um ambiente Ágil;
• Conhecimento em JavaScript;
• Experiência com SSH e VIM.

## Contratação

CLT

## Como se candidatar

- Enviar um email para ccarvalho@symplicity.com com seu CV anexado e assunto: Vaga de PHP
- Acessar: https://facaparte.contratanet.com.br/vaga/visualizar.aspx?v=1629417

![logo](https://user-images.githubusercontent.com/60138630/72804646-9dfdb200-3c2f-11ea-8694-d42037f18211.png)

**Comment by romulo2735** [comment]
aceita remoto ?

**Comment by cecimeira** [comment]
Oi Rômulo, tudo bem?

Essa vaga é presencial, pois já atuamos de forma remota ao HQ nos Estados Unidos.

Atenciosamente,

Cecília Carvalho




________________________________
De: Romulo Sousa <notifications@github.com>
Enviado: quarta-feira, 22 de janeiro de 2020 10:17
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: cecimeira <ceci_meira@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [Belo Horizonte] PHP Developer na Symplicity Brasil (#2060)


aceita remoto ?

**Comment by romulo2735** [comment]
Entendi, obg!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
