### ISSUE TITLE
[Belo Horizonte] .Net Developer na Symplicity Brasil

### ISSUE THREAD

**Issue by cecimeira** [backend-br/vagas#2061]
## Nossa empresa

A Symplicity é uma empresa de tecnologia dos EUA que possui o software líder mundial em sucesso para estudantes. Com duas décadas de experiência no espaço de Tecnologia Educacional, estamos presentes em mais de 1.000 universidades em todo o mundo.
A Symplicity adquiriu recentemente a Contratanet, a maior rede integrada de portais de carreira para Instituições de Ensino no Brasil, fortalecendo suas operações no país e está recrutando talentos para trabalhar em nosso escritório em Belo Horizonte.

## Local

Savassi, Belo Horizonte - MG

## Benefícios

- Plano de Saúde Allianz
- Plano Odonto Inpao
- Sodexo - VR ou VA
- VT
- 40 horas semanais com flexibilidade
- Snacks
- Ginástica Laboral
- Aulas de Inglês
- Experiência Global

## Requisitos

**Obrigatórios:**
• Perfil full stack
• Formação superior concluída/ou em curso de Ciências da Computação, Sistemas de Informação, Engenharias ou área afim;
• Conhecimento em POO e padrões de design de software;
• Experiência em tecnologias .NET;

**Diferenciais:**
• Vivência em uma empresa de produtos de Software;
• Experiência de mercado no desenvolvimento de Web ou UI;
• Conhecimento de controle de versão, como o GIT;
• Experiência em equipes de desenvolvimento de produtos em um ambiente Ágil;
• Experiência com Bootstrap e JQuery;
• Bons conhecimentos em SOLID, DDD, testes unitários e automatizados.

## Como será o seu dia a dia?
Nossas equipes utilizam tecnologias modernas e incentivamos uma cultura de inovação. Também praticamos metodologias ágeis para permitir entregas frequentes, previsíveis e de qualidade para nossos clientes. Criamos, hospedamos e suportamos produtos de software, que são dimensionados para suportar nossa grande base de usuários e clientes.

Nossos desenvolvedores têm o perfil full stack, e utilizamos tecnologias como: ASP.NET Full e Core, C#, AngularJS, SQL Server, ElasticSearch, AWS.

## Contratação

CLT

## Como se candidatar

- Enviar um email para ccarvalho@symplicity.com com seu CV anexado e assunto: Vaga de .Net
- Acessar: https://facaparte.contratanet.com.br/vaga/visualizar.aspx?v=1769106

![logo](https://user-images.githubusercontent.com/60138630/72804646-9dfdb200-3c2f-11ea-8694-d42037f18211.png)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
