### ISSUE TITLE
[Curitiba/PR] Back-end Node.js Developer na Cado Tecnologia

### ISSUE THREAD

**Issue by tiagompalte** [backend-br/vagas#2071]
## Descrição da vaga

Este profissional irá auxiliar no desenvolvimento de novas APIs para execução em ambiente de cloud.

## Local

Escritório, Curitiba / PR - Parolin

## Requisitos

**Obrigatórios:**
- Micro-serviços em Node.js
- Typescript
- MongoDB
- GraphQL

**Desejáveis:**
- Framework Nest.js
- Gitlab
- CI/CD
- Kubernetes
- Docker
- Json
- JWT

## Contratação

PJ a combinar

## Nossa empresa

Cado Tecnologia: Uma empresa nova do ramo financeiro buscando sempre inovação e uma ótima experiência do usuário. Somos parceiros da Fábrica de Software Wise e sempre temos desafios diferentes para vencer.

## Como se candidatar

Por favor envie um email para willian.tanaka@cadovendas.com.br com seu CV anexado - enviar no assunto: Vaga Angular

Para mais detalhes acesse: [LinkedIn](https://www.linkedin.com/jobs/view/1704782738/)

## Labels

- Alocado
- Júnior
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
