### ISSUE TITLE
[São Paulo] Fullstack Software Engineer na [Pitágoras Ampli]

### ISSUE THREAD

**Issue by DayaneVeronez** [backend-br/vagas#2074]
## Descrição da vaga 

 No mundo ideal para o aluno, o ensino superior seria público, gratuito e de qualidade. Infelizmente, a realidade está distante do ideal e o sistema está cheio de distorções que impedem que a crescente demanda por ensino superior seja atendida de forma adequada. 
 Dessa forma, várias instituições privadas buscam apoiar esses alunos e oferecer soluções educacionais. Entre elas, o ensino a distância (EaD) tem relevância especial por alcançar aqueles que moram longe de faculdades ou não têm condições financeiras para pagar os preços mais altos. 
 Pensando nisso, estamos criando uma unidade de negócio que trará novos modelos de negócio para o EaD, de forma disruptiva e tecnológica, focada em crescimento, acesso e qualidade educacional. 

Estamos construindo um projeto do zero e para isso contamos com um time altamente capacitado e uma cultura diferenciada. O que você encontrará por aqui: 

- **Foco em resultado** como premissa. 
- Ambiente de autonomia e alto nível de **Responsabilização**. 
- **Transparência** em nossa governança e comunicação. 
- Todas as decisões são pensadas e baseadas com **Foco em nossos alunos**. 
- **Foco em custo** para ter um produto escalável que chegue aos mais distantes municípios do Brasil e seja acessível às pessoas mais carentes. 
- Respeito e valorização a **Diversidade**. 

Tudo isso aliado ao nosso **Propósito** de contribuir para um mundo no qual o ensino superior de qualidade se torne acessível para a maioria da população. Queremos usar efetivamente o EaD para apoiar o alcance dos projetos educacionais e profissionais dos nossos alunos.

Se você quer trabalhar com o objetivo de impactar genuinamente a educação brasileira, com a cultura e o desafio de uma startup, seu lugar é aqui. =)

O(A) **Software Engineer** precisa possuir uma visão crítica sobre as soluções técnicas e desenvolver novas soluções para escalar o negócio, garantir a eficiência operacional e melhorar a experiência dos nossos alunos, gerando ainda mais valor para o nosso negócio.

## Local

Vila Mariana - São Paulo

## Benefícios

• Ambiente que valoriza feedback e 1:1; 
• Flexibilidade de horário, homeoffice e dresscode informal; 
• Ambiente dinâmico e com possibilidade de crescimento; 
• GymPass como incentivo a qualidade de vida; 
• Vale Refeição, VT, Plano de Saúde, Plano Odontológico e Seguro de Vida; 
• Bolsa de estudo para Graduação e Pós-Graduação; 
• PRV atrelado a metas; 

## Requisitos
**O que esperamos de você:**

Esperamos que goste de desafios e de resolver problemas. Esperamos que tenha amor por aprender e que seja antenado em novas tecnologias além de estar sempre se atualizando.

O que realmente procuramos são pessoas com as seguintes características:
• Experiência com desenvolvimento orientado a objetos e boa capacidade de abstração;
• Princípios SOLID bem afiados;
• Preocupação com códigos limpos, lembre-se que codificamos para os outros lerem;
• Desenvolver algoritmos simples e eficientes;
• Cultura de testes é imprescindível;
• Ter trabalhado com micro serviços e com a clean architecture é um diferencial;
• Ter facilidade para trabalhar em equipe e gostar de compartilhar ideias;
• Não ter medo de errar e assumir seus erros;
• Ter amor por tecnologia, gostar de estudar e evoluir o conhecimento;
• Ter senso crítico e questionar quando achar pertinente;

## Nossa stack
**Hoje trabalhamos com:**

- Kotlin (Spring boot)
- Node.js (GraphQL)
- React
- Kotlin  (Android nativo)
- Swift (IOS nativo)
- Python

E sempre consideramos novas linguagens e frameworks.

## Suas principais atividades serão:

• Entender o processo de produto como um todo;
• Desenvolver a plataforma de acordo com o desenho de produto e UX;
• Garantir a qualidade e escalabilidade da plataforma;
• Entender o impacto das soluções que o time desenvolve no usuário final;
• Ajudar o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;

## Contratação

CLT

## Como se candidatar

Por favor envie um email para dayane.veronez@ampli.com.br com seu CV anexado - enviar no assunto: Vaga Software Engineer.
Segue também nossa página de carreiras para mais informações: https://jobs.kenoby.com/pitagorasampli

## Labels

- CLT
- Júnior
- Pleno
- Sênior

**Comment by viniptds** [comment]
Olá, aceitam remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
