### ISSUE TITLE
[Rio de Janeiro] Back-End Enginieer na [Ame Digital]

### ISSUE THREAD

**Issue by CamilaTavares** [backend-br/vagas#2075]
Oi, somos a **Ame**!

A fintech que vai ganhar seu coração! Uma plataforma financeira para simplificar e revolucionar a maneira como as pessoas se relacionam com o dinheiro.

Buscamos desenvolvedores(as) com experiência em aplicações baseadas em micro serviços e práticas de testes para criar, identificar e propor melhorias. Estamos crescendo exponencialmente e precisamos de pessoas que gostem do desafio de criar novas funcionalidades, de forma rápida e com melhoria contínua.

**Responsabilidades e atribuições**
Desenvolver, evoluir e manter sistemas de alta escalabilidade, disponibilidade e performance, resilientes e orientados a eventos;
Colaborar com ideias que possam melhorar nossos sistemas e a vida dos nossos usuários;
Estar disposto a aprender e a ensinar;
Cuidar da nossa plataforma como se fosse seu filho;
Estar sempre atento às oportunidades para melhorar o código e os nossos processos.

**Requisitos e qualificações**
Graduação em Ciência da Computação ou áreas relacionadas;
Linguagens: não temos uma preferida e estamos sempre dispostos a experimentar. Hoje temos códigos escritos, principalmente, em NodeJS, mas também em Java, Groovy, PHP, Go e Kotlin. Se você domina alguma dessas linguagens, já possui uma vantagem;
Experiência e/ou interesse na realização de testes automatizados e refatoração de código;  
Confortável com Ambiente Unix;
Conhecimento básico de versionamento com GIT;
Saber como funciona o protocolo HTTP e o padrão REST.

**Diferenciais**

**Conhecimento/Experiência**
Programação assíncrona ou relacionada a arquitetura orientada a eventos;
Confortável com soluções de containerization, como Docker, por exemplo;
Confortável, também, com desenvolvimento de front-end;
Experiência com metodologia ágil;
Experiência open-source em algum projeto relevante;
Facilidade com arquiteturas distribuídas;
Experiência com banco de dados NoSQL. MongoDB, por exemplo.
Busca contínua por melhorias no time em que trabalha, no fluxo de trabalho e em você mesmo;
 
**Mais sobre nós** 
Ambiente descontraído e no dress code
Ame Talks – conversa semanal sobre a estratégia e tudo o que está rolando na Ame.
Acesso a todo o time o tempo todo - trabalhamos juntos para ir mais longe, mais rápido.
Benefícios
Pacote de remuneração compatível
Benefícios (vale transporte, vale refeição, plano de saúde médico e odontológico)

**Local de Trabalho**
Saúde - Rio de Janeiro

**Link da vaga**
https://boards.greenhouse.io/amedigital/jobs/4463495002?t=27927b6d2

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
