### ISSUE TITLE
[Curitiba] Back-End Developer na [Bcredi]

### ISSUE THREAD

**Issue by julydemenjon** [backend-br/vagas#2078]
Olá, nós somos a **Bcredi**!

Uma fintech curitibana que oferece Crédito por Garantia de Imóvel de uma forma descomplicada. Isto é: taxas reduzidas, de prazo alongado, em um processo que diminui as burocracias.
 
Nossa grande missão é construirmos a maior plataforma whitelabel de crédito, e para que esse e demais objetivos sejam conquistados, precisamos dos melhores ao nosso lado :) 

Estamos procurando **desenvolvedoras e desenvolvedores** que queiram revolucionar o mercado de crédito no Brasil. Sua missão junto com a gente é fazer os brasileiros alavancarem seus negócios ou seus projetos de vida através de crédito com garantia de imóvel.

Você é apaixonado (a) por tecnologia, por pessoas, start-ups e gostaria trabalhar em uma fintech de alto crescimento? Você quer causar impacto na nossa sociedade e movimentar a nossa economia? Vem com a gente.

**Sua responsabilidades serão:**

- Desenvolver códigos fáceis de entender, de manter e de testar. Seu código vai se transformar em produtos digitais que devem ser rápidos e fáceis de usar pelos nossos usuários.
- Evoluir todo dia: estar disposto a aprender novas linguagens, novos frameworks e novos paradigmas de programação. Aqui a única constante é a mudança.
- Desenvolver aplicações que sejam seguras, de alta disponibilidade, rápidas, estáveis e escaláveis. Estamos crescendo rápido e precisamos garantir que estamos sempre entregando o melhor produto.
- Realizar code-reviews e criar testes automatizados garantindo a qualidade dos sistemas.
- Trabalhar em um ambiente de times multi-disciplinares e de autonomia com metodologias de desenvolvimento ágil.
- Colaborar e interagir com time de desenvolvimento, designers, pessoas de produto e negócio.

**Requisitos necessários:**

- Dominar pelo menos uma linguagens de programação. **Utilizamos Elixir e Ruby.** Você não precisa saber nenhuma das duas. Precisa só de vontade para aprender rapidamente!!!
- Conhecimento de clean code, design patterns, arquitetura de sistemas e estrutura de dados.
- Vivência com testes automatizados que ajudem os sistemas a continuarem flexíveis e adaptáveis.
- Dominar pelo menos um banco de dados relacional. Utilizamos PostgreSQL.
- Se virar bem com alguma ferramenta de versionamento de código (preferencialmente git).

**Além dos requisitos acima, são bem vindos:**

- Experiência em alguma linguagem funcional como Elixir, Clojure, Scala, etc.
- Conhecimento em containers como Kubernetes, Docker, Vagrant.
- Conhecimento em sistemas distribuídos e de alta disponibilidade.
- Conhecimento em cloud, especialmente serviços da Google Cloud ou AWS.
- Utilizar conceitos do GitHub como branching, issues, pull-requests, etc.

A contratação acontece em regime CLT aqui na sede da Bcredi em Curitiba :) 

Sobre nós: https://www.bcredi.com.br/
Dúvidas? https://www.linkedin.com/in/julydemenjondesouza/
Contato: july.souza@bcredi.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
