### ISSUE TITLE
[Santo André - SP] Programador PHP PL

### ISSUE THREAD

**Issue by edgarguep** [backend-br/vagas#208]
## Atribuíções

- Desenvolver novas funcionalidades de software
- Identificar e corrigir bugs reportados pelos clientes
- Contribuir com soluções e idéias
- Modelar arquitetura de banco de dados relacional

## Requisitos

- PHP OO
- Conhecimento em MVC
- Conhecimento em frameworks (Yii, Symfony, Laravel ou similar)
- MySQL e MariaDB
- Composer
- GIT
- JavaScript
- AngularJS
- Bootstrap
- Ser organizado e pró-ativo

## Desejável

- Python / Java
- Redis
- React
- Scrum

## Contratação + benefícios

- Modalidade PJ (MEI)
- Assistência Médica ou Odontológica
- Moradia de baixo custo ao lado do local de trabalho
- Ambiente descontraído com videogame, sinuca, tênis-de-mesa e festinhas

## Sobre a GUEP Technology
Uma empresa provedora de tecnologia especializada no desenvolvimento de soluções integradas e análise de informações (Big Data) que tem por objetivo alavancar a produtividade e eficiência dos serviços e produtos da cadeia logística, respeitando os princípios do desenvolvimento sustentável e proporcionando melhor custo benefício aos negócios de nossos clientes

## Como se candidatar
Encaminhe deu CV para trabalheconosco@guep.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
