### ISSUE TITLE
[Encerrado][Rio de Janeiro] Back-End Developer Júnior [URB9]

### ISSUE THREAD

**Issue by rafaelso86** [backend-br/vagas#2080]
## Descrição da vaga
Se você gosta da ideia de trabalhar em um ambiente criativo, participar do desenvolvimento de novos serviços e soluções e, de quebra, fazer parte de uma equipe multidisciplinar, então você achou seu lugar! Você trabalhará criando soluções web, como aplicativos, intranet e websites. Pra isso, a gente precisa que você:
   ####

## Requisitos
- Tenha no mínimo 2 anos de experiência como profissional;
- Saiba desenhar e manter bancos de dados;
- Trabalhe com APIs e integração entre plataformas;
- Tenha experiência com MySQL, PHP, JavaScript, HTML, CSS;
- Saiba (e goste!) de trabalhar em equipe!

## Alguns diferenciais que fazem nosso olho brilhar:
- Inglês intermediário;
- Conhecimento em métodos ágeis;
- Experiência com projetos de estruturação de dados;

## Contratação
Aqui, a gente trabalha com contratação fixa, em CLT.

## Benefícios
- 13° salário;
- Férias remuneradas;
- Vale transporte;
- Vale refeição;
- Após o período de experiência, plano de saúde integral;
- Possibilidade de home office planejado;
- Horário flexível; 

## Local
Ficamos no centro da cidade do Rio de Janeiro.

## Como se candidatar
E aí, quer fazer parte da nossa equipe de desenvolvimento?

É só mandar seu CV, com DESENVOLVEDOR BACK-END JÚNIOR no assunto, para leandro@urb9.com.br.

https://www.urb9.com.br

Estamos te esperando

**Comment by romulo2735** [comment]
Apenas desenvolvedores juniors?

**Comment by lucasperrotta** [comment]
Aceita remoto ou apenas presencial?
