### ISSUE TITLE
[São Paulo - Pinheiros] Desenvolvedor .Net Jr/Pleno - Mazzatech

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2081]
## Descrição da vaga
Profissional atuará no desenvolvimento e sustentação de sistemas próprios da empresa, voltados para controle de acessos.

## Local
Pinheiros - São Paulo
Atuação Presencial

## Benefícios
Contratação PJ

## Requisitos
Experiência na plataforma .Net com C# e VBnet, MVC.
Conhecimentos em orientação a objetos.
Javascript e Sql Server.

## Contratação
PJ

## Nossa empresa
Profissional atuará em empresa que trabalha com sistemas para controle de acessos.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e pretensão salarial.
Inserir no assunto: Vaga .NET JR ou PL (dependendo da sua pretensão e senioridade).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
