### ISSUE TITLE
[São Paulo] Back-End Developer (PHP) na [Zebra Deluxe]

### ISSUE THREAD

**Issue by zebradeluxe** [backend-br/vagas#2083]
**Sobre a vaga**
Estamos buscando um profissional com experiência principal em PHP para se somar ao time de desenvolvimento da Zebra. Aqui estamos com uma demanda de novos projetos desafiadores prestes a entrar e você terá a oportunidade de embarcar com a gente desde o começo, bem como participar de projetos já existentes.

**Requisitos**
* Experiência em PHP, MySQL, OO, MVC
* Modelagem de banco de dados
* Experiência com algum framework PHP (Laravel, CodeIgniter, Symfony, etc)
* Conhecimento em WordPress (criação de temas, ACF, CPT, etc)
* Conhecimentos de JavaScript/jQuery, HTML5, CSS3
* Git
* Inglês técnico (leitura e escrita)

**Gostaremos mais ainda se você tiver familiaridade com**
* Algum framework JS - React, Angular ou Vue
* REST APIs
* C#

**Onde estamos**
* Rua Harmonia, Vila Madalena - São Paulo - (próximo à estação Vila Madalena)

**O que oferecemos**
* Regime de contratação CLT / PJ
* Vale refeição / Vale alimentação
* Plano de saúde
* Plano odontológico (opcional)
* Horário flexível
* No dress-code
* Café à vontade
* FIFA na hora do almoço 🙂

Se interessou? Envie um e-mail para cinthia.bento@zebradeluxe.com com o assunto "Vaga Back-End Zebra" com o seu CV.

Labels: Pleno, Sênior, CLT, PJ, Presencial

**Comment by patrickbtimoteo** [comment]
Aceitam remoto?

**Comment by zebradeluxe** [comment]
> Aceitam remoto?

Infelizmente não. Apenas presencial, Patrick.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
