### ISSUE TITLE
[São Paulo] Back-End Developer (PHP) na [Deloitte]

### ISSUE THREAD

**Issue by diogom-42** [backend-br/vagas#2085]
## Descrição de Cargo

Título do Cargo: Desenvolvedor PHP Sênior

Local de Trabalho: Av. Chucri Zaidan, 1240 - Golden Tower – 9º andar

Reportará a: Gerência

Principais deveres e responsabilidades:

O profissional irá atuar no desenvolvimento de sites e CMS (Content Management System), em PHP juntamente com
WordPress, sendo executadas on cloud, consumindo backlog de melhorias, bem como a implementação de novas
funcionalidades na aplicação atual.
É esperado que o profissional possua maturidade, comprometimento, capacidade de gestão autônoma de tempo, muita
vontade de aprender e entregar resultado.

Formação, educação e exigências de experiência de trabalho:

```
•Graduação em Ciências da computação, Matemática, Sistema de Informação, Análise de Sistemas e áreas
correlatas;
•Experiência em desenvolvimento de aplicações com PHP;
•Frameworks JS: Vue.js, React, Angular, JavaScript frameworks, jQuery;
•HTML5 e CSS frameworks como Bootstrap ou Foundation
•Experiência em desenvolvimento e consumo de API RESTful / Protocolo HTTP;
•Sólidos conhecimentos em arquitetura e prática dos princípios Clean Code, Design Patterns e padrão PSR;
•Banco de dados SQL (MS SQL, mySQL, MongoDB);
•Metodologias ágeis (Scrum / Kanban);
•DevOps: CI/CD, Testes automatizados, fluxo de versionamento com GIT;
```
Desejável conhecimento em:
```
•Bancos NoSQL (MongoDB, Elasticsearch, Redis, etc);
•Cloud Amazon AWS;
•Conhecimentos de Containers (Docker, Kubernetes);
•Conhecimentos de TDD, DDD e/ou BDD;
•Jira para controle de Projetos Agile;
•Maven;
•Swagger;
•Ter construído produtos e aplicações do zero;
```
Competências comportamentais:

```
•Comprometimento;
•Organização;
•Gestão de tempo;
•Iniciativa;
•Trabalho em equipe.
```
Enviar os currículos para o seguinte e-mail: renatosilva@deloitte.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
