### ISSUE TITLE
[São Paulo] Developer (Angular) na [Deloitte]

### ISSUE THREAD

**Issue by diogom-42** [backend-br/vagas#2086]
## Descrição de Cargo

Título do Cargo: Desenvolvedor Angular Sênior

Principais deveres e responsabilidades:

O profissional irá atuar no desenvolvimento do frontend, em angular 7, para uma aplicação desenvolvida on cloud, consumindo backlog de melhorias, bem como a implementação de novas funcionalidades.
É esperado que o profissional possua maturidade, comprometimento e capacidade de gestão autônoma de tempo.

Requisitos:
• Desenvolvimento de aplicações frontend, utilizando linguagem Angular 2, 5, 6 ou 7;
• Desenvolvimento WEB (HTML, CSS, Javascript, JQuery, TypeScript);
• Conhecimento em arquitetura de microserviços;
• APIs REST, Webservices, e Json;
• Experiência em controle de versionamento com Git;
• Experiência com testes unitários;
• Bancos de dados MySQL, MongoDB e DinamoDB;
• Familiaridade com ambientes de Cloud Computing, preferencialmente AWS;
• API Gateway.
• Conhecimentos de metodologias ágeis (Scrum e KanBan);
• Desenvolvimento Web Responsivo;
• Jira para controle de Projetos Agile;
• Maven;
• CI/CD;
• Jenkis;
• Swagger.

Local de Trabalho: São Paulo – SP
Contratação: CLT
Interessados enviar CV por e-mail para jveiga@deloitte.com com o assunto [Oportunidade: Desenvolvedor Angular]

**Comment by ednilsonamaral** [comment]
Aceitam remoto?

**Comment by diogom-42** [comment]
Apenas presencial mesmo.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
