### ISSUE TITLE
[São Paulo] Full-Stack Developer na [Editora Globo]

### ISSUE THREAD

**Issue by guilhermevalor** [backend-br/vagas#2087]
A Editora Globo, empresa das Organizações Globo, busca um Desenvolvedor Full-Stack para atuar com o time de produtos digitais.

**Requisitos:**

- Domínio em Javascript e Python;
- Conhecimento em HTML5, CSS e React;
- Experiência no trabalho com conteinerização (Docker, Compose);
- Experiência em utilização de terminal (Linux);
- Vivência no uso de ferramentas de controle de versão como GIT.

**Diferenciais:**

- Estar habituado ao trabalho com metodologias ágeis (Scrum/Kanban);
- Experiência em Node;
- Experiência com PHP;
- Experiência com armazenamento de dados com Redis e MongoDB;
- Experiência com desenvolvimento para aplicações web com alto volume de acessos, fazendo utilização de soluções para melhoria de desempenho de backend e frontend;
- Ter projetos publicados no github.

Benefícios: CLT + Assist. Médica, VR, Seguro de Vida, dentre outros.

Localização: A Editora Globo está localizada em São Paulo/SP, no bairro do Itaim Bibi.

Enviar CV para guilherme.ocampos@valor.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
