### ISSUE TITLE
[São José dos Campos/SP] Dev Back-end Cuponomia

### ISSUE THREAD

**Issue by taichr** [backend-br/vagas#2088]
**Temos vagas para desenvolvedores Back-End, nível pleno/sênior! Buscamos novos talentos para acelerar nosso crescimento.
Junte-se ao nosso time!**

**Benefícios:**
• Convênio médico e odontológico;
• Seguro de vida;
• Vale refeição;
• Vale transporte;
• Horário flexivel.;
• Cashback em dobro.

**Requisitos desejáveis:**
• Linguagens orientadas a objetos (C#, Java, C++, etc);
• Experiência com banco de dados.

**Diferenciais:**
• Experiência com C#;
• Familiaridade com computação em nuvem (Amazon AWS);
• Experiência com desenvolvimento Web.

**Atividades desenvolvidas:**
• Utilizar diversas linguagens e tecnologias para o desenvolvimento de sistemas em diferentes plataformas, tais como Web, REST, Mobile, Browser extensions;
• Aplicar boas práticas de desenvolvimento como SOLID, DDD e TDD;
• Extrair e analisar informações do nosso banco de dados utilizando SQL, NoSQL e Big Data;
• Desenvolver algoritmos de machine learning para identificação de padrões e aprendizado do comportamento do usuário;
• Desenvolver aplicações escaláveis em nuvem utilizando Amazon Web Services.

**Sobre a empresa:**
O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons, cash back e ofertas das principais lojas online nacionais e internacionais. Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos, descontos especiais e cash back para nossos usuários.

Envie currículo para taiane@cuponomia.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
