### ISSUE TITLE
[São Paulo - Berrini] Desenvolvedor BackEnd (Java ou Ruby) - Creditas

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2089]
Descrição da vaga
Atuará no desenvolvimento de aplicações voltadas para uma das áreas do negócio da empresa, que esta em processo de criação.

Local
Berrini - São Paulo
Atuação Presencial (a empresa não tem politica de home office mas esta trabalhando nisto).

Benefícios
VR, VT, Assistencia Médica, Assistencia Odontologica, Gympass (pequeno desconto para os planos mais altos).

Requisitos
Experiência com Microservices.
Boas Práticas de Programação como DDD, Arquitetura, Design Patterns, TDD, Desenvolvimento em Cloud (AWS).
Necessário que a pessoa tenha experiencia com Java ou Ruby. Caso tenha experiência com Java, que tenha um pouco de conhecimento em Ruby.
Caso tenha experiência em Ruby, que tenha um pouco de conhecimento em Java.
Necessário disponibilidade para aprender Kotlin.

Contratação
CLT

Nossa empresa
Profissional será contratado direto pela Creditas, uma empresa financeira que vem crescendo bastante no mercado.

Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e pretensão salarial.
Inserir no assunto: Vaga Java Ruby

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
