### ISSUE TITLE
[Santo André - SP] Programador Mobile PL

### ISSUE THREAD

**Issue by edgarguep** [backend-br/vagas#209]
## Atribuíções

- Desenvolver novas funcionalidades de apps
- Identificar e corrigir bugs reportados pelos clientes
- Contribuir com soluções e idéias
- Modelar arquitetura de banco de dados relacional
- Integração REST API
- Integração API Maps

## Requisitos

- Java Android
- UI / UX Design
- Conhecimento em MVC
- MySQL e MariaDB
- Composer
- GIT
- JavaScript
- Ser organizado e pró-ativo

## Desejável

- Objective C / Swift
- Scrum

## Contratação + benefícios

- Modalidade PJ (MEI)
- Assistência Médica ou Odontológica
- Moradia de baixo custo ao lado do local de trabalho
- Ambiente descontraído com videogame, sinuca, tênis-de-mesa e festinhas

## Sobre a GUEP Technology
Uma empresa provedora de tecnologia especializada no desenvolvimento de soluções integradas e análise de informações (Big Data) que tem por objetivo alavancar a produtividade e eficiência dos serviços e produtos da cadeia logística, respeitando os princípios do desenvolvimento sustentável e proporcionando melhor custo benefício aos negócios de nossos clientes

## Como se candidatar
Encaminhe deu CV para trabalheconosco@guep.com.br

**Comment by guilhermeoa07** [comment]
Necessário experiência?

**Comment by edgarguep** [comment]
@guilhermeoa07 sim, é necessária experiência em desenvolvimento de apps nativos Android. Obrigado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
