### ISSUE TITLE
[São Paulo - Alphaville] Desenvolvedor Java Senior - Mazzatech

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2090]
Descrição da vaga
Atuará no desenvolvimento de aplicações para clientes do mercado financeiro.

Local
Alphaville - São Paulo

Benefícios
Contratação PJ

Requisitos
Spring (boot/batch/rest/security/MVC), arquitetura de microservices, JPA, Hibernate, RabbitMQ, DDD, SOLID, Unit Test, Conceito de teste de integração, SQL, MongoDB, conhecimentos em AWS (seria um plus), API Rest, clean code.
Conhecimento Kotlin assim como AWS é um diferencial já que estamos atuando em alguns projetos.

Contratação
PJ

Nossa empresa
Estamos apoiando empresa que atua com desenvolvimento de aplicações diversas para Fintechs.

Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e pretensão salarial.
Inserir no assunto: Java Fintech.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
