### ISSUE TITLE
[São Paulo - Granja Viana] Analista de DevOps - Cloudways

### ISSUE THREAD

**Issue by rafaelcanto** [backend-br/vagas#2091]
**Descrição da vaga**
Estamos ampliando nossa pequena equipe de consutoria :) Trata-se de uma nova posição para atuar em projetos de adoção de melhores práticas de nuvem, esteiras de desenvolvimento e ALM.

**Local**
Granja Viana - SP + Clientes em São Paulo - SP

**Contratação PJ**

**Requisitos técnicos**
-Conhecimentos sólidos de nuvem (qualquer provedor, Azure é um diferencial)
-Prática em desenvolvimento back-end (qualquer linguagem, irá ter contato com .NET Core e Java principalmente)
-Conhecimento em cloud design patterns
-Conhecimento de arquitetura distribuída, enterprise applications

**Outros requisitos**
-Boa postura, boa escrita, etc.
-Redes e infraestrutura de nuvem são diferenciais
-Segurança de nuvem é um diferencial
-Certificações são um diferencial

**Timeline**
Precisamos fechar essa posição no final de fevereiro/2020.

**Nossa empresa**
Nossa empresa atua no segmento corporativo em projetos de cloud. Rearquitetura, migrações, otimizações e 'advisory' no geral. Parceiro Microsoft e Google Cloud.

**Como se candidatar**
Por favor envie um email para rafael.canto@cloudways.com.br com seu CV anexo e pretensão salarial.
Inserir no assunto: Especialista DevOps.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
