### ISSUE TITLE
[São Paulo] Back-End Developer (WordPress) na MUFASA

### ISSUE THREAD

**Issue by danilowm** [backend-br/vagas#2093]
**VAGA PROGRAMADOR SÊNIOR (QUEM PUDER COMPARTILHE)**

A Mufasa está em busca de um programador PLENO OU SÊNIOR para a participar da equipe. Precisamos de alguém que ajude a desenvolver novos projetos, além de dar suporte aos cases que já existem. As principais funções são:

**Requisitos:**
- WordPress (criação de temas, ACF, CPT, etc)
- WooCommerce (PagSeguro, PayPal, Correios, Cupons, etc)
- JavaScript/jQuery, Layout Responsivo, Bootstrap
- Lógica de Programação
- GIT (versionamento de código)

**Informações:**
- Vaga PJ
- Segunda a sexta, das 10h às 19h
- Rua Harmonia, Vila Madalena - São Paulo (próximo à estação Vila Madalena)

**Sobre nós:**
- Contratação PJ
- Horário Flexível
- Café à vontade
- Copa para refeições
- Ambiente descontraído e amigável
- Pet Friendly 🐶

[mufasa.com.br](http://mufasa.com.br)

Mande seu currículo, portfólio ou GitHub e pretensão salarial para danilo@mufasa.com.br

labels: Wordpress, PJ, Presencial, Pleno, Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
