### ISSUE TITLE
[São Paulo] Desenvolvedor Full-Stack Java/react

### ISSUE THREAD

**Issue by esterpaganini** [backend-br/vagas#2096]
https://www.linkedin.com/jobs/cap/view/1684968261/?pathWildcard=1684968261&trk=mcm

Vagas@rebelbank.com.br 

**O que buscamos:**
Proatividade;
Perfil colaborativo, flexibilidade e capacidade de mobilização de pessoas;
Visão sistêmica e de riscos com foco em soluções;
Dinamismo, flexibilidade e habilidade de condução de múltiplas frentes;
Visão de tecnologia integrada ao negócio e ao cliente;
Maturidade para conduzir mudanças.
Visão de risco de negócio e senso de urgência;
Perfil autônomo, autogestão e independência na definição de prioridades e seu desenvolvimento.
**Descrição do cargo:**
Reunir requisitos e transformá-los em soluções funcionais;
Trabalhar em conjunto com outros desenvolvedores para criar e manter soluções robustas;
Padronização para criação de soluções multiplataforma;
Otimização de desempenho de aplicativos;
Manter-se atualizado sobre tendências e novas tecnologias;
**Principais responsabilidades:**
Escrever códigos compatíveis com padrões, incluindo teste/depuração em várias plataformas
Trabalhar com designers para traduzir conceitos visuais em websites funcionais
Projeta e implementa componentes do sistema
Colabora estreitamente com colegas de equipe para criar soluções inovadoras e orientadas para o desempenho
Traga-nos ideias de novas tecnologias que podem ser usadas para melhorar nossos sistemas
**Conhecimento técnico:**
Conhecimento de padrões de design de software
Ensino superior em ciência da computação, engenharia da computação ou experiência de trabalho equivalente
Foco em Back-end, Java com Docker, Spring boot e Cloud AWS.
**Benefícios:**
Vale Refeição – R$ 31,00 ao dia
Vale Transporte
Seguro Saúde Sul América – plano especial 100 – Para colaborador e dependente
Snacks, toda semana disponíveis na copa (incluindo cerveja, salgadinho, chocolate, suco entre outros).
Ambiente descontraído
Oportunidade de grande crescimento profissional
Confraternizações que a Rebel oferece (almoços em datas comemorativas; Happy Hour de integração, comemoração de acordo ccom a meta batida, campeonato de poker e de vídeo game, etc...)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
