### ISSUE TITLE
[Niterói | Remoto] Full-Stack Jr.  @Xekout

### ISSUE THREAD

**Issue by Gabrielmoraesp** [backend-br/vagas#2098]
## Descrição da vaga

A Xekout é uma plataforma voltada para lojas virtuais. Ajudamos nossos clientes a aumentarem a conversão de suas vendas.

## Responsabilidade:

O desenvolvedor deverá zelar pela manutenção da plataforma da Xekout e oferecer soluções adequadas ao crescimento da mesma respeitando o stack tecnológico da empresa bem como suas diretivas.

## Perfil da contratação:

Ser cordial com os colegas de trabalho
Ser pontual, compromissado com horários e entregas
Ser crítico quanto a qualidade das entregas

## Local

Remoto

## Contratação

PJ

## Requisitos Obrigatórios:

- VueJS
- JavaScript
- NodeJs
- AWS
- API REST

## Como se candidatar

Por favor, envie um e-mail para contato@xekout.me com seu CV anexado. 
Enviar no assunto: Full-Stack Jr.

## Labels
- Remoto
- Júnior
- PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
