### ISSUE TITLE
[São José dos Campos/SP] .NET FullStack developer Senior na Climatempo

### ISSUE THREAD

**Issue by oliverthies** [backend-br/vagas#2099]
**FullStack Senior Developer at Climatempo/StormGeo** 

Do you wake up in the night dreaming on creating the killer APP or beautiful user friendly Web pages? Do you visualize yourself working among smart, creative and innovative colleagues? 
Does your heart beat faster when hear words like Micro services, Docker, Kubernetes, REST, Xamarin, Javascript, Angular, CSS3, C#, ASP.Net MVC and similar buzz words? 
Are you drooling when looking at beautifully designed and fast web pages and architectures? 
If you feel you can identify yourself with this, get in touch as we have much in common and should get to know each other better! 
We are currently looking for an experienced DEVELOPER. Yes, developer with capital letters. A person who will be responsible for creating and maintaining Software in close collaboration with our developers located in Norway, Sweden, Lithuania and USA. 
For information about our products, please visit us at www.stormgeo.com 

Job Responsibilities: 
·       Develop, support and improve client-facing applications. 
·       Software design, coding, testing and integration.  

Desired Skills and Experience 
•	bachelor or Master in computer science, information technology or a related discipline. 
•	5+ years of development experience 
•	strong understanding in Object Oriented programming and design patterns 
•	experience with some of the following tools: .NET C#, HTML, JavaScript, CSS, ASP.NET MVC, ASP.NET WebApi, ASP.NET WebForms, Angular, React, JQuery, Xamarin, Microservices, REST API 
•	strong interest to work in team using agile and lean methods 
•	familiarity with databases like MySQL 
•	ability to learn existing systems 
•	knowledge of any GIS system is an advantage 
•	able to communicate well in English

We prefer that you 
•	have good sense of humor 
•	are independent and have an entrepreneurial spirit 
•	are solution oriented and innovative 
•	have ability to learn new technologies and frameworks 
•	have good written and spoken knowledge of English 
•	have ability to structure chaotic events and ideas 

For the right person we offer a competitive package, including good compensation and possibility to influence software design and process flow. Our Development team is a team of highly qualified professionals who will guaranteed excel your skills. Smart, creative and innovative are the keywords.

make contact: fullstack@climatempo.com.br

**Comment by ericastro** [comment]
I do not prepared to this opportunite but i would loved will work in climatempo, i live and study in Taubate, but i want go to live in sjc i want a opportunite to work and learned whit your team.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
