### ISSUE TITLE
[Joinville] Software Engineer - Back-End na Conta Azul

### ISSUE THREAD

**Issue by MartinaCarvalho** [backend-br/vagas#21]
## Descrição da vaga

As a software engineer at ContaAzul you will work with big challenges of scalability caused by huge quantity of datas and fast growth number of users, in an environment highly fun and collaborative. We need someone that has a passion in solving complex problems.

A professional with strong skills in data and algorithm structures, along with a technical fascination of how things work. A motivated software engineer willing to experience and risk, in order to make a difference within his area, who is not afraid of defending his ideas and accept changes, next to highly trained people and motivated to improve day by day.

RESPONSIBILITIES

Elegant system code that requires search, interactivity and curiosity;
Write automated test to ensure the quality of the developed solution;
Analyse and improve the efficiency, scalability and stability of systems resources.

## Local

Joinville / SC

## Benefícios

- Compatible salary, above the market average;
- Meal ticket;
- Financial Aid for extented education and graduate;
- Financial Aid for learning english;
- Affliliation with pharmacies;
- Full health plan and without a discount on your paycheck;
- Full dental plan and without a discount on your paycheck;
- Financial Aid for physical activities;
- Transportation Assistance.

#### Diferenciais

- A different work environment and innovative, with a culture that values people and the delivery of results;
- Autonomy and flexibility;
- Kitchen’s always stocked with unlimited snacks;
- A team that has our values in their DNA;
- Living in one of the best cities to live in Brazil;
- Access to books and other materials.

## Requisitos

**Obrigatórios:**
- BS in Computer Science, Information Systems, related fields or equivalent experience knowledge in Web development;
- Our stack is mainly in Java - It is desirable that you have solid experience in this stack or be willing to learn quickly;
- Solid knowledge in TDD, Clean Code and Design Patterns;
- Desirable knowledge of distributed Systems and high availability;
- Knowledge in other Web programming technologies: Ruby on Rails and Node.js;
- Desirable knowledge in Cloud, mainly AWS services;
- Desirable knowledge in Agile methodologies and good communication skills, essential for teamwork;
- Ability to communicate in english, both written and verbally.

## Contratação

CLT a combinar

## Nossa empresa

A ContaAzul é uma empresa de tecnologia sediada em Santa Catarina que nasceu em 2011 no Vale do Silício. Nosso propósito é impulsionar o sucesso das pequenas empresas brasileiras. Hoje fazemos isso através de um software na nuvem que ajuda milhares de pequenos empresários na gestão de seus negócios. 

## Como se candidatar

Ficou interessado na vaga? Cadastre-se em https://jobs.lever.co/contaazul/bf2f5ced-c635-4f49-850d-8d50b46f3dc6?=source=github
Dúvidas ou comentários, podem contatar Martina Carvalho no e-mail: recrutamento@contaazul.com

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
