### ISSUE TITLE
[São Paulo] Node.js Developer Sênior na 3,2,1 Beauty

### ISSUE THREAD

**Issue by CavalcanteLeo** [backend-br/vagas#2100]
### Sobre a empresa

A 3,2,1 Beauty oferece serviços de bem estar e beleza in company (manicures, quick massage, barbeiro, design de sobrancelhas, yoga entre outros).
Nosso objetivo é que ajudar a otimizar o dia a dia dos colaboradores e melhorar a qualidade de vida no trabalho.
Cada empresa tem o seu próprio site para o agendamento online.
Atendemos semanalmente gigantes do mundo das startups como WeWork, 99Taxis, Nubank e Regus e empresas nacionais e multinacionais como Suzano e Burger King.

### Descrição da vaga
Estamos buscando backend sênior para ajudar no desenvolvimento da nossa plataforma, facilitando ainda mais a vida dos nossos clientes e parceiros.

Para se candidatar a essa vaga, você deve ter uma grande experiência **comprovada** com node.js, banco de dados relacional e não relacional, arquitetura de código, além de conhecimentos em metodologias ágeis como scrum, nexus e kanban.
Ambiente descontraído, com liberdade de horários.

### Atividades e Responsabilidades

* Desenvolvimento de funcionalidades no Back-End em node.js;
* Criar arquitetura de microserviços
* Realizar a manutenção e criação de novas funcionalidades;
* Aplicar melhores práticas de documentação de código desenvolvido;
* Desenvolver e sustentar integrações;
* Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
* Integração com outros sistemas;
* Ser auto-gerenciável, aplicar diariamente o conceito scrum;
* Participar da sprint planing, review e retrospectiva, assim como as daily;
* Participar da concepção do produto (utilizando metodologia design thinking);
* Conseguir quebrar as tasks de uma sprint backlog em no máximo 1 dia de duração ou menos;
* Criar e configurar microserviços na AWS;

### Requisitos

**Linguagens/tecnologias/frameworks:**
* Javascript ES6
* Node (**mais de 4 anos de experiência**)
* CI/CD
* Typescript (Desejável)
* Go (Desejável)
* Express (Desejável)
* Hapi.js (Desejável)

**Banco de dados/Engines:**
* Mongo
* PostgreSQL
* Redis
* ElasticSearch (Desejável)
* GraphQL (Desejável)

**Infraestrutura:**
* AWS (EC2, Elastic beanstalk, Kubernets, Lambda, RDS, S3, SES, SQS, SNS, X-Ray, Route 53, Api Gateway, VPC)
* Docker

**Outros requisitos:**
* Microservices
* Firebase (Cloud Messaging, Remote Config)
* Código limpo e claro
* Testes automatizados (BDD TDD)
* Scrum e outras metodologias ágeis
* Vue.js (Desejável)

### Local
Av Faria Lima - SP

### Contratação
PJ ou CLT, ótimos salários

### Como se candidatar
Por favor envie um email para leonardo@321beauty.com.br com seu linkedin e breve descrições nos projetos mais desafiadores que você já trabalhou 
Enviar no assunto: Vaga node.js

### Labels
Alocado
Sênior
PJ ou CLT
Salário a combinar
Ninja

**Comment by yureesantos** [comment]
Somente sênior? Vaga muito boa. Se pleno estiver apto, vou enviar.

**Comment by CavalcanteLeo** [comment]
> Somente sênior? Vaga muito boa. Se pleno estiver apto, vou enviar.

Vai abrir também vaga para pleno, pode enviar o CV =)
Mas somente vamos contratar os Plenos após a contratação dos sêniores

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
