### ISSUE TITLE
[São Paulo] Senior Backend Developer na Airfox - Presencial

### ISSUE THREAD

**Issue by apantaliao** [backend-br/vagas#2101]
**Descrição da Vaga**

Um cliente da Vizir, a Airfox está buscando desenvolvedores para montar o seu time de engenharia em São Paulo.  Atualmente, o time de engenharia se localiza em Boston com suporte do time da Vizir aqui de São Paulo.  

Eles buscam pessoas que tenham conhecimentos avançados em ao menos uma linguagem (preferencialmente TypeScript ou JavaScript). Se você gosta muito de programar e é bom nisso, irá aprender rapidamente qualquer linguagem. É importante valorizar a qualidade de código e defende isto durante o desenvolvimento do trabalho.

**Local de trabalho**
São Paulo / SP, esta vaga não está aberta para trabalho remoto.  

**Candidatura e mais detalhes sobre a vaga**
Para mais detalhes sobre a vaga e candidatura, favor acessar este [link do LinkedIn](https://www.linkedin.com/jobs/view/1711806044).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
