### ISSUE TITLE
[Curitiba / PR] Desenvolvedor Java Fullstack SR (N341WJ) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [backend-br/vagas#2102]
## Descrição
Somos uma empresa paranaense, possuímos mais de 27 anos de histórias, dentre elas o CMMI nível 3 e somos GPTW pelo 9º ano seguido! Trabalhamos com soluções de Software, possuímos uma fábrica muito bem estruturada que atende clientes nacionais e internacionais. Outsourcing, profissionais CINQ que atuam em clientes de diversos segmentos e diferentes portes. Trabalhamos com o foco de construir carreiras e transformar vidas!

## Atividades:

O projeto envolve o desenvolvimento de sistemas de gestão de frotas e monitoramento de veículos e cargas, que faz o acompanhamento do consumo de combustível, velocidade, dirigibilidade, rotas e trajetos.

## Local:

Curitiba, PR.

## Carga Horária:

40h semanais

## Perfil Técnico Necessário:

AngularJS
Groove
Java J2EE
JavaScript
Html
CSS
Bootstrap
Arquitetura de Serviços RESTFull

## Benefícios
Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo

## Canditar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
