### ISSUE TITLE
[Remoto] -  Vue & Node.js - PJ - Pleno

### ISSUE THREAD

**Issue by Gabrielmoraesp** [backend-br/vagas#2106]
### Sobre a empresa
A Xekout é uma plataforma SaaS que ajuda lojas virtuais a aumentarem a conversão no checkout. 

### Descrição da vaga
Estamos buscando backend pleno para ajudar no desenvolvimento dos projetos da empresa. Atualmente temos 3 projetos. 

Para se candidatar a essa vaga, você deve ter uma grande experiência comprovada com node.js, banco de dados relacional e não relacional, arquitetura de código.

### Atividades e Responsabilidades
Desenvolvimento de funcionalidades no Back-End em node.js;
Realizar a manutenção e criação de novas funcionalidades;
Aplicar melhores práticas de documentação de código desenvolvido;
Desenvolver e sustentar integrações;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Integração com outros sistemas;
Ser auto-gerenciável, aplicar diariamente o conceito scrum;

**Requisitos**
Linguagens/tecnologias/frameworks:

Javascript ES6
**Node/Adonis (mais de 2 anos de experiência)**
CI/CD
Typescript (Desejável)
Express (Desejável)
Banco de dados/Engines:

Redis
ElasticSearch (Desejável)
GraphQL (Desejável)

**Infraestrutura:**

AWS (EC2, Elastic beanstalk, Lambda, RDS, S3, SES, SQS, SNS, Route 53, Api Gateway)
Docker

**Outros requisitos:**

Código limpo e claro
Testes automatizados (BDD TDD)
Scrum e outras metodologias ágeis
Vue.js

**Contratação**
PJ

### Como se candidatar
Por favor envie um email para contato@xekout.me com seu linkedin e pretenção salarial

Enviar no assunto: Vaga node.js

Labels
Pleno
PJ
Salário a combinar
Ninja

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
