### ISSUE TITLE
[São Paulo/SP] Dev PHP Pleno/Sênior na MT4

### ISSUE THREAD

**Issue by gustavoper** [backend-br/vagas#211]
## Descrição da vaga

A MT4 está a procura de profissionais nos níveis Pleno/Sênior (PHP) para fazer parte de seu time de devs. 

Estamos na região de Pinheiros, bem próximo a estação Fradique Coutinho e a Vila Madalena.

## Local

Presencial - São Paulo/SP (Região de Pinheiros)

## Benefícios

- Vale-transporte; 
- Vale-alimentação; 
- Gympass; 
- Plano de Saúde Bradesco.

#### Diferenciais

- Empresa em franco crescimento; 
- Ambiente descontraído;
- Flexibilidade de horário

## Requisitos

**Obrigatórios:**
- Experiência comprovada em PHP 5+ (Orientação a Objetos, Design Patterns);
- Conhecimentos em Linux; 
- Conhecimentos em Javascript/CSS;
- Superior completo (ou cursando) na área de TI;
- SVN/GIT básico;
- SQL/Oracle;
- Noções em Redes; 
- Saber trabalhar em equipe.

Todos os requisitos serão medidos através dos testes e entrevistas com os gestores.

**Desejáveis:**
- Conhecimento em Zend Framework ou outro Framework de mercado (Symfony, Laravel).

**Diferenciais:**
- Participar de projetos opensource e/ou eventos de comunidades;
- conhecimento em Python;
- capacidade rápida de aprendizado (será medida nos testes).

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

Há mais de dez anos a MT4 desenvolve produtos e soluções inovadoras para empresas em diversos segmentos, destacando-se o setor financeiro nas áreas de automação de processos, BackOffice, CRM e Gestão Inteligente de Infraestrutura de TI.

## Como se candidatar

Interessados enviar currículo **com pretensão salarial**  para vagas@mt4.com.br com assunto: programador PHP.

Currículos fora do perfil desejado serão excluídos.

## Labels

- CLT
- PJ
- Pleno
- Sênior
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.

**Comment by andrecointrade** [comment]
tenho interesse
