### ISSUE TITLE
[São Bernardo do Campo, SP] Desenvolvedor .Net na Domvs

### ISSUE THREAD

**Issue by thaisvilladal** [backend-br/vagas#2110]
Descrição da vaga
Atuação em projeto em .Net em um cliente do segmento de Logística e cadeia de suprimentos. 
Especializada em operações complexas e de alta criticidade para empresas de setores de alto valor agregado, oferecendo uma gama completa de serviços, com foco em logística de veículos e logística integrada. Considerada a maior operadora da América Latina voltada para o transporte de veículos. 

Local
Presencial - São Bernardo do Campo, SP

Requisitos

Obrigatórios:
Experiência em Programação C# .NET (Visual Studio 2019).
Facilidade de relacionamento para trabalhar junto às equipes SCRUM.

Conhecimento Técnico Desejável:
Programação VB (Visual Studio 2019).
Conhecimento em integrações WEBServices e API REST.

Contratação
PJ a combinar - horas fechadas
Contrato: 6 meses - com possibilidade de prorrogação ou efetivação pelo cliente.

Nossa empresa
A DOMVS é constituída de profissionais com larga experiência em gestão de empresas, onde efetivamente participam de decisões de negócios embasadas pela utilização estratégica da tecnologia da informação.
Estamos presentes no Brasil e também em Portugal.

Como se candidatar
Por favor envie um e-mail para consultoria_villadal@domvs.com.br com seu CV anexado - enviar no assunto: Vaga .Net SBC

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: consultoria_villadal@domvs.com.br

Labels
PJ
Pleno
Junior
Senior
Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
