### ISSUE TITLE
[Belo Horizonte] Back-End Developer na [CIMPI]

### ISSUE THREAD

**Issue by AdrianaCaixeta** [backend-br/vagas#2111]
A CIMPI é uma startup que está nascendo com uma ideia inovadora que vai revolucionar o mercado com sua plataforma inteligente.

A proposta está pronta, e estamos em busca da pessoa certa para conduzir o desenvolvimento do produto, estruturando o projeto do 0, usando primordialmente Python.

Não nos importamos com o tempo de experiência, o fundamental é a garra, determinação e vontade de aprender!

caixeta@scrumaceleradora.com
#vagatech #vagabh #oportunidade #python #django #linux #git #tecnologia #scrumaceleradora

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
