### ISSUE TITLE
[São Paulo] Desenvolvedor .NET na Flatbox

### ISSUE THREAD

**Issue by williamxsp** [backend-br/vagas#2112]
## Descrição da vaga

Procuramos backend para nosso time, irá trabalhar em sites, sistemas, aplicativos, desenvolvendo api e manutenção em diversos projetos. Pra quem está a fim de aprender e se desenvolver em todos os caminhos da tecnologia.
.

## Local

Escritório, São Paulo - Santo Amaro (ao lado da estação de trem e metrô)

## Benefícios

- Oportunidade Crescimento
- Plano de desenvolvimento individual
- Férias Coletivas

#### Diferenciais

- Horário flexível
- No dress code
- Ambiente
 Vídeo game
- Participação em outros projetos com ideias e sugestões

## Requisitos

**Obrigatórios:**
- C#
- Boa lógica
- Conhecimento do conceito de Orientação a Objetos
- Conhecimento do conceito de Herança
- Conhecimento do conceito de Implementação de Interface
- Conhecimento do conceito de Injeção de Dependência
- Conhecimento do conceito de MVC

**Desejáveis:**
- Asp.Net Core 2
- Javascript
- HTML
- CSS
- PL/SQL

## Contratação

PJ a combinar

## Nossa empresa

Somos inquietos e estamos em constante transformação, como o digital. Nascemos para unir artistas e técnicos, comunicadores e estrategistas, programadores e designers e liderá-los para transformar sonhos em resultado. Nosso trabalho é construir pontes que conectam Tecnologia, Marketing e Comunicação ao que entendemos ser o foco de tudo: Pessoas. Afinal, somos pessoas, criando com pessoas, para servir pessoas.
Prazer, somos Flatbox.

## Como se candidatar

Por favor envie um e-mail para william.martins@flatbox.ag com:
Assunto: Vaga Back
Seu CV anexado
Faça o teste: http://mrcoach.com.br/teste-perfil-comportamental-disc.php
Envio o print do resultado anexado ao email

## Labels

- Alocado
- Júnior
- Pleno
- C#
- .NET

**Comment by felipe-allmeida** [comment]
Oi William, já acharam alguem para a vaga?

**Comment by williamxsp** [comment]
Oi @felipe-allmeida,
Achamos! Esqueci de fechar a issue.
De qualquer forma, se quiser mandar assim mesmo a gente olha todos os currículos que chegam pra gente ;)
