### ISSUE TITLE
[São Paulo/SP] Desenvolvedor ADVPL Sênior na DWC Consult

### ISSUE THREAD

**Issue by DWCConsult** [backend-br/vagas#2113]
Oportunidade para Desenvolvedor ADVPL Sênior!

Requisitos:
- Conhecimento sênior em desenvolvimento ADVPL e integrações- Web Service REST e SOAP;
- Experiência com aplicação em MVC para ADVPL.

Local: Zona Norte.
Jornada Integral
Forma de contratação PJ
Prazo Indeterminado.

Sobre a DWC Consult
Somos uma empresa jovem, apaixonada por oferecer as melhores soluções tecnológicas para negócios. Desde 2014 somos Totvs Partners e realizamos consultoria de negócios e desenvolvimentos voltados aos ERPs Datasul e Protheus. 
Estamos em constante crescimento, no último ano tivemos um total de 110.000 horas de serviços prestados, além de aumentarmos cada vez mais nosso time.
Prezamos por serviços com qualidade, rapidez e contamos com um time de perfil proativo e em constante aprendizado, por isso investimos no desenvolvimento de quem está conosco.

Interessados encaminhar o currículo para o e-mail: rh@dwcconsult.com.br
Assunto: Desenvolvedor ADVPL

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
