### ISSUE TITLE
[São Paulo] Sênior .NET Developer - Agile Content

### ISSUE THREAD

**Issue by Diego451f** [backend-br/vagas#2116]
## **Sobre a Agile Content:**
 
Em uma época em que a maneira como as pessoas consomem conteúdo muda em um ritmo vertiginoso, a Agile Content prevê a criação de soluções de streaming que possibilitam e aprimoram essas experiências.

Com tecnologia de ponta, desenvolvemos nossa experiência em streaming de vídeo e áudio, desde a ingestão de conteúdo, soluções de processamento e gerenciamento até a experiência do usuário final com aplicativos para celular, TV e Xbox, e aproveitamos essa experiência para ajudar algumas das **maiores empresas de telecomunicações na Europa e na América Latina, incluindo Telefónica, NET / Claro e Globosat,** para modernizar a maneira como eles fornecem mídia para seus clientes e permitir que eles alcancem novos públicos.​

## **Requisitos:**

- Bons conhecimentos de C # ou Node.js com pelo menos 7 anos de experiência no desenvolvimento, envio e manutenção de aplicativos Web;
- Conhecimento de padrões de design de software;
- Habilidades de design orientado a objetos;
- Capaz de trabalhar de forma independente, colaborativa e gerar resultados;
- Ensino superior em ciência da computação, engenharia da computação ou experiência profissional equivalente;
- Diferenciais: Docker e .Net Core.

 
## **Como será o seu dia a dia:**

- Projetar e implementar componentes do sistema
- Colaborar estreitamente com os colegas de equipe para criar soluções inovadoras e orientadas para o desempenho
- Trazer ideias de novas tecnologias que podem ser usadas para melhorar nossos sistemas
- Ajude outros membros da equipe a desenvolver e melhorar

## **O que estamos buscando:**

Estamos procurando alguém que não seja apenas experiente em desenvolvimento de software, mas que também tenha um forte entendimento de boas práticas de programação, demonstre empolgação para aprender e que não tenha medo de enfrentar novos desafios trabalhando em soluções que envolvem computação em nuvem, streaming de mídia digital e Gerenciamento de direitos digitais.

 ## **Benefícios e outras informações:**

- Local de trabalho: Alexandre Dumas, São Paulo - SP
- Seguro de Saúde
- Seguro de Vida
- Seguro Odontológico
- Aulas de inglês e espanhol no trabalho
- Remuneração competitiva
- Bilhetes de refeições
- Plano de participação nos lucros pago duas vezes por ano

## **Como se Candidatar:**

Se Inscreva [nessa vaga](https://vagas.byintera.com/agile-content/senior-net-developer/?utm_source=github&utm_medium=issue&utm_content=tipo1&utm_campaign=geral&cr=growth)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
