### ISSUE TITLE
São Paulo - Arquiteto / Engenheiro de Cloud

### ISSUE THREAD

**Issue by Daniela1986** [backend-br/vagas#2118]
Ter trabalhado com Cloud (Google, Azure ou AWS).
Aplicação/ uso de ferramentas em projetos para clientes de grande porte -Financial Services, Telecom ou Consumer Business em arquitetura de Cloud e arquitetura de Analytics /BI.
Conhecimento em Inteligencia Artificial.
Desejável - passagens por consultoria e pré-vendas de projetos.
Interessados, enviar Cv e contatos para : daniela.lamonica@potencialrh.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
