### ISSUE TITLE
[Remoto] PHP Developer na Empreender

### ISSUE THREAD

**Issue by andreas-monday** [backend-br/vagas#2119]
## Descrição da vaga

Desenvolver ferramentas online usando PHP, HTML e Javascript. 
É desejável experiência com bibliotecas Codeigniter, Jquery, Bootstrap. 
Experiência com uso de webservice http request.

## Local

Remoto

**Desejáveis:**
- conhecimentos em Codeigniter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@empreender.com.br com seu CV anexado e pretensão salarial para PJ, 8h
Enviar no assunto: Vaga PHP

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by walteralleyz** [comment]
Vocês aceitam PJ MEI de informática?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
