### ISSUE TITLE
[São Paulo/SP] Estágio em Dev PHP na MT4 Networks

### ISSUE THREAD

**Issue by gustavoper** [backend-br/vagas#212]
## Descrição da vaga

A MT4, empresa de Tecnologia instalada na região de Pinheiros, São Paulo, está a procura de estudantes para programa de estágio em PHP.

## Local

Presencial - Região de Pinheiros/SP (Próximo ao metrô Fradique Coutinho)

## Benefícios

- Vale-alimentação;
- vale-transporte; 
- Gympass; 
- Seguro de vida.

#### Diferenciais

- Empresa em crescimento; 
- Alta % de efetivação de estagiários;
- Treinamento intensivo.

## Requisitos

**Obrigatórios:**
- Curso Superior (Bacharel ou Tecnólogo)  ou Técnico em qualquer área relacionada a Tecnologia.

**Desejáveis:**
- Conhecimento (Técnico ou acadêmico) em PHP.

**Diferenciais:**
- Projetos Open Source; 
- Participante de eventos em comunidade; 
- Capacidade rápida de aprendizado (mediremos nos testes).

## Contratação

Contrato de estágio com grandes chances de efetivação como CLT.

## Nossa empresa

A MT4 Networks surgiu em 2010 como uma divisão da empresa MT4 Tecnologia para atender a crescente demanda por soluções e serviços especializados de redes.

Há mais de dez anos a MT4 desenvolve produtos e soluções inovadoras para empresas em diversos segmentos, destacando-se o setor financeiro nas áreas de automação de processos, BackOffice, CRM e Gestão Inteligente de Infraestrutura de TI.

## Como se candidatar

Por favor envie um e-mail para vagas@mt4.com.br com seu CV anexado - enviar no assunto: Estágio programação PHP.

## Labels

- Estágio
- PHP
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
