### ISSUE TITLE
[SP - Campinas, Possibilidade Remoto] Software Engineer no iFood

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#2120]
A **maior FoodTech da América Latina**, líder em delivery online está buscando **você para crescer junto!**

**Impacte a vida de milhões!** Estamos desenvolvendo a **melhor arquitetura e as melhores tecnologias** para construir uma plataforma **mais sustentável, escalável e consistente** à longo prazo. Tudo isso para fornecer a **melhor performance e experiência** para os nossos clientes, entre **usuários e restaurantes presentes na América Latina!**

Atualmente nós trabalhamos com **Java e Kotlin, assim como AWS e ferramentas CI/CD**(Conhecimentos em outras linguagens ou cloud como GCP são bem-vindas também!). Essas tecnologias com **pessoas com propósito** e dispostas é o que nos faz **crescer exponencialmente!** Adorariámos também agregar conhecimentos em Boa práticas de programação, TDD e Infraestrutura como código .

A contratação será feita em **regime CLT com PLR, benefícios e horários flexiveis**(E auxlílio deslocamento para lugares com ao menos **200km de distância do escritório**). 
Nossa **sede fica em Campinas** e temos hubs de trabalho em: São Paulo, São Carlos, Osasco, Porto Alegre e Recife. Existe a opção de **trabalhar na sede do iFood em Campinas, nos hubs pelo Brasil e também remoto!**

**Inscreva-se e venha fazer impactar a vida de milhões usuários que fazem parte da sua rede também:** http://bit.ly/2Ots3Ii

Perfil para dúvidas: https://www.linkedin.com/in/iagotavaress/

**Comment by renatafarano** [comment]
Onde fica a sede em Campinas?

**Comment by ednilsonamaral** [comment]
Enviei a minha inscrição! 🤞

**Comment by iagobyintera** [comment]
> Onde fica a sede em Campinas?

Boa tarde Renata! Fica na Rua Jasmim, em Mansões Santo Antônio :)

**Comment by iagobyintera** [comment]
> Enviei a minha inscrição! 🤞

Boa Ednilson! Espero que dê tudo certo na jornada pelo processo e muitos cupons! Hahaha!

**Comment by luizadpassos** [comment]
Boa oportunidade!!
