### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor Ruby on Rails

### ISSUE THREAD

**Issue by PedroSeda** [backend-br/vagas#2122]
## Desenvolvedor, a Qconcursos te quer!
Tem de tudo um pouco! Quer trabalhar com um dos top 150 sites mais acessados do Brasil, fazer interface e experiência para sistemas de IA e algoritmos bizarros de busca? Aqui você pode!
Buscamos pessoas que amam desafios e que buscam aprender sempre! Independentemente da sua experiência. 
Se você se identifica com essa vaga, venha pra cá! Temos um ambiente totalmente diferenciado e estamos refazendo vários sistemas com foco máximo em uma experiência diferencial para o usuário.
Fazer isso pensando em 110 milhões de pageviews não é uma tarefa fácil e, na verdade, é bem desafiante. Por isso, buscamos pessoas apaixonadas por tecnologia para estarem a cada dia buscando novas soluções e, claro, implementando as propostas da nossa equipe de produto!
### Local
Escritório, Rio de Janeiro - Ao lado do metrô Presidente Vargas
### Benefícios
- Plano de saúde Bradesco Top Nacional
- VR ou VA de R$ 33/dia
- Auxílio creche
- Bolsa parcial para graduação/pós/especialização depois de 1 ano de empresa
- Vale transporte
- Plano dentário
- Shiatsu
- Floral 
### Diferenciais
- 2 horas de almoço
- Monte a sua máquina como desejar
- Ambiente de trabalho muito descontraído
- Sala de jogos / vídeo game/ biblioteca
- Horários flexíveis
- Ter milhões de pessoas acessando seu trabalho a um commit de distância
- Dia de pizza / bolo / salgadinhos
- Proximidade da equipe de produto com foco em experiência do usuário
- Plano de carreira
#### Tecnologias
- Ruby on Rails
- Sidekiq
- Banco de Dados Relacional
- Redis
#### Desejável
- Cloud (AWS)
- Elasticsearch
- Experiência com Metodologias Ágeis – Scrum ou Kanban
 
#### Diferenciais
- Projetos opensource
- Ser comunicativo
- Gostar de aprender/ensinar
- Construir códigos organizados que facilitam escala

### Contratação
CLT  - Temos planos de carreira
### Nossa empresa
Somos a maior plataforma online de resolução de questões de concursos e cursos, voltada para apoiar os estudantes a alcançarem a aprovação em concursos públicos e a evoluírem na sua vida profissional por meio da educação.
Fizemos 10 anos em janeiro, temos mais de 900 mil questões de provas anteriores cadastradas em nossa base e mais de 10 milhões de usuários. Somos uma das marcas mais conhecidas e lembradas do mercado e temos o aval de grandes instituições.
### Como se candidatar
Por favor, envie um email para selecao@qcx.com.br com seu CV/Linkedin/Carta de Apresentação - enviar no assunto: Vaga Desenvolvedor

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
