### ISSUE TITLE
[Curitiba] Back-End Developer na [Deal]

### ISSUE THREAD

**Issue by karlakristinasilva** [backend-br/vagas#2124]
Empresa focada em transformação Digital e Data, a Deal busca um profissional para atuar dentro do Delivery atendendo projetos de grandes players (Ex: Cinemark, Banco Rendimento, NetShoes, etc)

Perfil que buscamos:
[09:49, 06/02/2020] Karla: 
Desenvolvedor Sênior .Net
•	Habilidades Imprescindíveis:
o	Conhecimento avançados em .NET C#
o	Conhecimento avançados em .NET C#  Core
o	Conhecimento avançado em ASP.Net Web API (REST) (Micro serviços)
o	Conhecimento avançado em ORM (Entity Framework e Nhibernate)
o	Conhecimento avançados de SQL SERVER (TRANSACT SQL)

o	Conhecimento em DEVOPS e  metodologia ágil (SCRUM)  
o	Conhecimento em desenvolvimento cloud computing (containers docker, kubernetes, Azure, Mensageria (RabbitMQ) e Event sourcing)

Entre em contato via Whatsapp - Karla (41) 99524-1407 Email: karla.silva@deal.com.br ou Skype: karla.kristinasilva

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
