### ISSUE TITLE
[São Paulo/SP][Remoto] Full Stack Developer no Fotop

### ISSUE THREAD

**Issue by azizvc** [backend-br/vagas#2125]
## Nossa empresa

Startup nacional em uma missão global para se tornar a melhor (e mais humilde) plataforma para fotógrafos de eventos. Somos a empresa de fotografia oficial do Rally Dakar, Rally dos Sertões e da Arena Corinthians.

## Descrição da vaga

Desenvolvedor Full Stack para atuar diretamente no desenvolvimento e manutenção de nossa plataforma.

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em pelo menos uma dessas tecnologias: PHP ou NodeJS/React
- Banco de dados MySQL/Aurora
- HTML, CSS, Bootstrap e Javascript
- Git
- Serviços AWS
- Conhecimento básico de Linux

**Desejáveis:**
**Outros recursos que utilizamos**

- Trabalhando aqui você terá contato com:
- React Native
- Serverless (lambda)
- Redis
- APIs em REST
- Scrum
- OKRs

### Experiência
- Sênior (2 vagas)

#### Diferenciais

- Startup dinâmica
- Ambiente descontraído

## Contratação

- PJ

## Benefícios

- VR
- VT

### Alocação:
- Presencial
- Remoto

## Local

Escritório, São Paulo/SP - Perdizes

## Como se candidatar

Por favor envie um email para vaga-tec@fotop.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
