### ISSUE TITLE
[São Paulo] Desenvolvedor Back End na Radar Profisisonal

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#2127]
VAGAS: FRONT END PLENO e SÊNIOR

Escritório, Vila Olímpia, Zona Sul

Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência com desenvolvimento front-end: HTML, CSS e Javascript;
•	Vivência com React web, GIT, Material Design, Material-UI e Javascript Api Google Maps.

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.
Local: São Paulo/SP – Zona Sul - Vila Olímpia 
Interessados: Enviar CV para talento@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
