### ISSUE TITLE
[São Paulo]  Desenvolvedor(a) Back-end na Nox Bitcoin

### ISSUE THREAD

**Issue by trumae** [backend-br/vagas#2128]
### Vaga de Desenvolvedor(a) Back-end na Nox Bitcoin

Atuando desde julho de 2018, a Nox Bitcoin é especializada em negociações e robôs de criptomoedas. Se você desenvolve Back-end com mais de 5 ano(s) de experiência, sênior ou pleno, que tenha trabalhado em sistemas que precisam escalar rápido, gostaríamos de conhecer você!
Descrição da oportunidade

A Nox Bitcoin está procurando desenvolvedores que queiram trabalhar no mercado de criptomoedas, seja para trabalhar na plataforma de negociações de ativos, seja para trabalhar com algoritmos de trading.

Para dominar nossos desafios, você precisará de habilidades em:  
- C#
- .NET
- SQL-Server

#### Como será seu dia a dia

- Projetar e implementar produtos inovadores do mercado de criptomoedas atuando no desenvolvimento de novas features, manutenção preventiva e evolutiva, além de colaborar com críticas, ideias e ferramentas, com o objetivo de melhorar o desenvolvimento e entrega;
- Colaborar estreitamente com os colegas de equipe para criar soluções inovadoras e orientadas para o desempenho;
- Trazer ideias de novas tecnologias que podem ser utilizadas para melhorar nossos sistemas;
- Ajudar outros membros da equipe a desenvolver e melhorar, atuando como referência técnica, executando code reviews e prezando pela qualidade das entregas;
- Trabalhar de forma independente e colaborativa, gerando resultados;
Bela oportunidade para atuar numa equipe extremamente qualificada e cheia de gás. 🙂

#### Pré requisitos
- Excelente conhecimento no desenvolvimento de aplicações de alta performance e escalabilidade utilizando plataforma .NET (C#);
- Conhecimento em arquitetura orientada a eventos e software distribuído;
- Conhecimento em MS SQL Server, Redis, Service Bus, REST API.

#### Conhecimentos desejáveis
- JavaScript;
- Python;
- Docker;
- Mercado Financeiro.

– Talk is cheap, show me your code 😉
Não temos desafios, queremos ver seu Github! Mas claro, se você tiver um desafio pronto, pode nos enviar também.

– Você tem ou já teve bitcoin? 🙂

Se interessou? Envie seu currículo para vmaciel@noxbitcoin.com.br
Local de trabalho: Distrito Fintech, Pinheiros, São Paulo/SP
Tipo de contratação: PJ ou CLT
Benefícios: Bônus anual

Venha fazer parte do time!

https://www.noxbitcoin.com.br/desenvolvedor-back-end/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
