### ISSUE TITLE
[Sāo Paulo] Estágio de desenvolvimento Python

### ISSUE THREAD

**Issue by raphaguasta** [backend-br/vagas#2130]
# Estágio de desenvolvimento Python

## A empresa:
Com a proposta de ajudar os brasileiros a negociarem suas dívidas e a se manterem no azul sempre, a BLU365 oferece uma plataforma de negociação fácil, intuitiva e digital, para seus clientes ficarem no azul o ano todo.

## Requisitos:

- Conhecimentos em programação Python
- Conhecimento em queries de MongoDB ou SQL

## Aqui você vai trabalhar com:

- Ambiente Linux
- Cloud/AWS
- Docker

## O que esperamos de você:

- Preocupado com organizaçāo e qualidade do código
- Acompanhar as novidades e atualzaçōes, a tecnologia evolui rápido!
- Estudo e aprendizado constante
- Habilidade de evoluir por conta própria

## Onde estamos:
Estamos no Cubo Itaú, o maior centro de empreendedorismo tecnológico da América Latina!
Vila Olímpia - Sāo Paulo, SP

## Sobre a vaga:

- Vale Transporte 
- Vale Refeiçāo
- Férias
- Incentivo a cursos
- No Dress Code
- Horário flexível

## Aqui você também tem:

- Refeitório com microondas
- Pebolim, mesa de ping-pong, sinuca
- Chopp free a partir das 18:00hrs :)

## Cvs
Encaminhar cvs para: estagios@blu365.com.br

**Comment by jonathan-mothe** [comment]
Gostaria de saber se para essa posição é necessário estar cursando a faculdade?

**Comment by raphaguasta** [comment]
> Gostaria de saber se para essa posição é necessário estar cursando a faculdade?

Sim, para estágio precisa =/

**Comment by raphaguasta** [comment]
Fechamos a vaga. Obrigado a todos! 😄
