### ISSUE TITLE
[São Paulo] Java Developer na [ACORDO CERTO]

### ISSUE THREAD

**Issue by KarenV12** [backend-br/vagas#2131]
A empresa Acordo Certo está aumentando seu time e estamos buscando um Dev Java Sr.

Sobre a Acordo Certo: com o propósito de oferecer bem-estar financeiro e ajudar as pessoas a realizarem seus sonhos, a empresa Acordo Certo, que já viabilizou mais de 1,4 milhão de acordos somando mais de 555 milhões de reais desde 2016, está aumentando seu time. Já são mais de 5 milhões de clientes atendidos. Agora você pode fazer parte dessa história.

FORMA DE CONTRATAÇÃO:
• PJ
• Bônus Semestral de até 3 salários
• 15 dias de férias remuneradas

REQUISITOS NECESSÁRIOS:
• Faculdade ou mestrado em Ciência da Computação ou similar
• 4+ anos de experiência em desenvolvimento Java e J2EE com Spring
• Familiaridade com Linux
• Conhecimento de desenvolvimento em ferramentas tais como Java, XML, JSON, REST, Spring etc.
• Capacidade de desenvolver códigos, seguindo diretrizes de codificação pré estabelecidas.
• Serviço de excelência com inovação, criando oportunidades pensando a frente das demandas do negócio.

PRINCIPAIS RESPONSABILIDADES:
• Reunir e analisar requisitos dos donos dos produtos para desenvolvimento em Java
• Projetar e desenvolver sistemas altamente escalonáveis e tolerantes a falhas usando Java, J2EE e tecnologias de código aberto
• Entender e adaptar aos princípios de SOA utilizando REST

Manda seu CV para: karen@v12consulting.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
