### ISSUE TITLE
[São José dos Campos] Desenvolvedor C# na DMCard

### ISSUE THREAD

**Issue by MattVieira** [backend-br/vagas#2134]
**Desenvolvedor C# PLENO - [CLT]**

Sobre a DMCard

Somos uma administradora de cartões de crédito de loja que respira transformação desde 2002. Viabilizamos para redes de supermercados a possibilidade de oferecerem aos seus consumidores um cartão de crédito de marca própria que, além de aumentar as vendas, fideliza seus clientes.

Nascemos de uma pequena operação de cartões de fidelidade e hoje possuímos uma completa e integrada estrutura de administração e processamento de operações. Atuamos em diversas regiões do Brasil e já ultrapassamos a marca de 3 milhões de cartões emitidos para mais de 360 redes e 2.300 lojas.

Nossos clientes estão no centro de nossas decisões e desde 2013 ostentamos orgulhosamente o selo **RA1000***.

Requisitos:

- Conhecimento com C# (.NET 4.5 ou superior)
- SQL Server
- API Rest
- Git

Beneficios: 

- Plano médico ou Odontológico.
- Vale Refeição
- Bônus Anual

Envie seu currículo através do e-mail selecao@dmcard.com.br com o título: "Vaga Desenvolvimento."

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
