### ISSUE TITLE
[São José dos Campos/Remoto] Desenvolvedor FullStack .NET - Climatempo

### ISSUE THREAD

**Issue by oliverthies** [backend-br/vagas#2135]
**Desenvolvedor FullStack .NET para atuar em projeto internacional.**

Você acorda no meio da noite sonhando em criar um APP matador, um algoritmo super veloz ou belas páginas da Web? 
Você se visualiza trabalhando entre colegas inteligentes, criativos e inovadores?
Seu coração bate mais rápido quando ouve palavras como MicroServices, Docker, Kubernetes, REST, Xamarin, Javascript, Angular, CSS3, C #, ASP.Net MVC e buzzwords semelhantes?

Você fica babando ao olhar para arquiteturas e páginas da Web rápidas e com design bonito?
Se você se identificar com isso, entre em contato, pois temos muito em comum e devemos nos conhecer melhor!

No momento, estamos à procura de um desenvolvedor experiente. Sim, desenvolvedor com letras maiúsculas. Uma pessoa que será responsável por criar e manter Software em estreita colaboração com nossos desenvolvedores localizados na Noruega, Suécia, Lituânia e EUA.
Para informações sobre nossos produtos, visite-nos em www.stormgeo.com

**Responsabilidades do trabalho:**
· Desenvolver, dar suporte e aprimorar aplicativos voltados para o cliente.
· Projeto, codificação, teste e integração de software.

**Habilidades e experiência desejadas**
Bacharel ou mestre em ciência da computação, tecnologia da informação ou uma disciplina relacionada.
• 5+ anos de experiência em desenvolvimento
• forte entendimento em programação orientada a objetos e padrões de design
• experiência com algumas das seguintes ferramentas: .NET C #, HTML, JavaScript, CSS, ASP.NET MVC, ASP.NET WebApi, ASP.NET WebForms, Angular, React, JQuery, Xamarin, Microservices, REST API
• forte interesse em trabalhar em equipe usando métodos ágeis e enxutos
• familiaridade com bancos de dados como MySQL
• capacidade de aprender sistemas existentes
• conhecimento de qualquer sistema GIS é uma vantagem
• capaz de se comunicar bem em inglês ( Obrigatório )

**Diferenciais:**
• ter bom senso de humor
• ser independente e ter espírito empreendedor
• ser orientados para soluções e inovadores
• ter capacidade de aprender novas tecnologias e estruturas
• ter bons conhecimentos para escrever e falar em inglês
• ter capacidade de estruturar eventos e idéias em cenários caóticos

Se você for a pessoa certa, oferecemos um pacote competitivo, incluindo boa compensação e possibilidade de influenciar o design do software e o fluxo do processo. Nossa equipe de desenvolvimento é uma equipe de profissionais altamente qualificados que garantem um excelente desempenho.

Vaga para trabalho presencial com possibilidade de home office 

contato: fullstack@climatempo.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
