### ISSUE TITLE
Dev Full Stack WebApp

### ISSUE THREAD

**Issue by labpne** [backend-br/vagas#2136]
_A Petronect é um dos maiores marketplace do Brasil conectando fornecedores, compradores e instituições financeiras ao processo de compras.

Nossas soluções compreendem o desenvolvimento, desenho e gerência de Portais Eletrônicos e atividades relacionadas a processos de aquisição de materiais, serviços ou produtos até o pagamento a seus fornecedores.

Nossos Valores: Agilidade, Conformidade e Simplicidade, são direcionadores que transmitem o compromisso da Petronect em prover soluções de valor para os nossos clientes.

Petronect, a conexão segura entre Fornecedores e Compradores._

**Estamos em busca de um profissional que deseje trabalhar no processo criativo de novos produtos no laboratório de inovação da Petronect.

Temos um ambiente super descontraído e fortemente estruturado nas práticas ágeis e lean, atuando com foco em validação de hipóteses e busca de motores de tração através de métricas/indicadores de valor. 

O laboratório de inovação fica localizado dentro da PUC Rio como iniciativa da Petronect, para prover serviços de comércio eletrônico relacionados à aquisição de bens e serviços.

O profissional que estamos selecionando, precisa ter experiência em desenvolvimento Full Stack, Cloud preferencialmente AWS, flexibilidade do Stack de tecnologias buscando o que melhor atenda ou tenha domínio para geração das primeiras versões dos produtos.**

É desejável conhecimento em algumas opções de Stack para front e back, como por exemplo:

●     Kotlin
●     NodeJs
●     Python
●     Java (Spring Boot)
●     Angular
●     React
●     Bootstrap
●     AWS Lambda
●     Docker
●     Kubernetes
●     ECS
●     MongoDB
●     MySql

Se você é esse profissional, vem trabalhar com a gente!

Benefícios
Assistência médica
Assistência odontológica
Auxílio academia
Seguro de vida
Vale-refeição
Vale-transporte

**Comment by pedro-surf** [comment]
Aceita remoto? Falta o link para se candidatar.

**Comment by THAYLLER** [comment]
eu tenho essa mesma duvida a vaga é otima

**Comment by PascalBreno** [comment]
Estou na mesma dúvida sobre a vaga. Como se candidata?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
