### ISSUE TITLE
[SP - Campinas, Remoto] Engenheiro(a) de Software no iFood

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#2137]
A **maior FoodTech da América Latina**, líder em delivery online está buscando **você para crescer junto!**

**Impacte a vida de milhões!** Estamos desenvolvendo a **melhor arquitetura e as melhores tecnologias** para construir uma plataforma **mais sustentável, escalável e consistente** à longo prazo. Tudo isso para fornecer a **melhor performance e experiência** para os nossos clientes, entre **usuários e restaurantes presentes na América Latina!**

Atualmente nós trabalhamos com **Java e Kotlin, assim como AWS e ferramentas CI/CD**(Conhecimentos em outras linguagens ou cloud como GCP são bem-vindas também!). Essas tecnologias com **pessoas com propósito** e dispostas é o que nos faz **crescer exponencialmente!** Adorariámos também agregar conhecimentos em Boa práticas de programação, TDD e Infraestrutura como código .

A contratação será feita em **regime CLT com PLR, benefícios e horários flexiveis**(E auxlílio deslocamento para lugares com ao menos **200km de distância do escritório**). 
Nossa **sede fica em Campinas** e temos hubs de trabalho em: São Paulo, São Carlos, Osasco, Porto Alegre e Recife. Existe a opção de **trabalhar na sede do iFood em Campinas, nos hubs pelo Brasil e também remoto!**

**Inscreva-se e venha fazer impactar a vida de milhões usuários que fazem parte da sua rede também:** http://bit.ly/2Ots3Ii

Perfil para dúvidas: https://www.linkedin.com/in/iagotavaress/

**Comment by LeoFC97** [comment]
Apliquei!

**Comment by iagobyintera** [comment]
> Apliquei!

Boaaa Leo! Espero que dê tudo certo na jornada!

**Comment by jair-anderson-souza** [comment]
Submetido. Agora é esperar.

**Comment by rmomogi** [comment]
Também me candidatei

**Comment by iagobyintera** [comment]
> Submetido. Agora é esperar.

Opa, logo logo entraremos em contato!

**Comment by iagobyintera** [comment]
> Também me candidatei

Ótimo, que bom que seguiram essa jornada, aproveitem bastante ela e os cupons! Hahaha!!
