### ISSUE TITLE
[São Paulo ou Remoto] Desenvolvedor Back-end Elixir/Ruby no ReclameAqui

### ISSUE THREAD

**Issue by cleytonmessias** [backend-br/vagas#2138]
**Sobre a empresa** : 

O RA é o 815º site mais acessado do mundo! Veja aqui :) https://www.alexa.com/siteinfo/reclameaqui.com.br

Temos uma cultura técnica forte. Não estamos amarrados a linguagens e paradigmas, mas sim a soluções :)

**Descrição: Ocupações do cargo**

Desenvolvedor back-end com Elixir, porém temos várias aplicações em Ruby.

**Você deverá conhecer:**

- Conhecimento em Elixir/Phoenix;
- Ruby
- Ruby on Rails
- Docker
- Kubernetes
- Um pouco de VueJS e Ember
- Redis 
- Se manjar de ElasticSearch e Kafka, melhor ainda, mas não é obrigatório :)

**Se inscreva aqui:)**

Se inscreva nesse link:  https://forms.gle/ccsVLDvsQ7GeEw3A8

Teremos prazer em conversar tanto pra lhe conhecer melhor quanto para mostrar nossa cultura :)

**Comment by weslleycf** [comment]
Bom dia,


O formulario está com ecesso restrito.

Em seg., 10 de fev. de 2020 às 10:51, cleytonmessias <
notifications@github.com> escreveu:

**Comment by cleytonmessias** [comment]
@weslleycf Desculpe, agora está liberado :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
