### ISSUE TITLE
[SP - São Paulo] Engenheiro(a) de Software na Voxy

### ISSUE THREAD

**Issue by icaroseara** [backend-br/vagas#2139]
## Descrição da vaga
Se você é um engenheiro de software procurando usar seu talento para ensinar ao mundo inglês, então preste atenção na Voxy.  Os engenheiros de software da Voxy estão mudando a forma com que milhões de pessoas ao redor do mundo aprendem inglês por meio do uso de pesquisa científica combinada com tecnologia inovadora e patenteada. Estamos implementando atividades de aprendizado impulsionadas por pesquisas científicas juntamente com aulas ao vivo usando algoritmos avançados para construir uma experiência personalizada usando fontes de "conteúdo autênticas" de nomes que você conhece (Bloomberg, AP, Financial Times e muitos outros). O objetivo da Voxy é se tornar o primeira opção no mercado de ensino de inglês que é avaliado em $80 bilhões. Dessa forma, o nosso time de engenharia é crucial para alcançar esse objetivo.

## O que você vai fazer:
Construir um código bem instrumentado, testável e que possa ser feito deploy sem downtime
Desenvolver nosso pipeline de big data para usar feedback em tempo real para uma plataforma ideal para os estudantes
Projetar a melhor solução de software que seja agradável para se trabalhar, performática para nossos parceiros e evolua com nossos alunos
Escalar a aplicação da Voxy e projetar para nossos novos projetos de NLP e machine learning

## O que nós estamos procurando:
- Fluência em inglês
- 5+ anos de experiência relevante trabalhando como desenvolvedor de software
- Curiosidade e conhecimento sobre tecnologias e padrões de arquitetura de engenharia de software em toda a stack
- Pragmatismo no entendimento de quando construir uma solução que escala para 1 milhão de usuários ou que funciona para 100 usuários.
- Habilidade de construir modelos de dados que refletem o modelo de negócios da Voxy usando técnicas avançadas de SQL, NoSQL e ORMs
- Alinhamento com os valores do time de Engenharia da Voxy: Confiança, Compromissos de Equipe, Comunicação Aberta, Pragmatismo e 'Engenharia ajuda a fazer o design do produto'. 

## O que seria ótimo ter:
- Django/Django Rest Framework Django/DRF ou outros frameworks web como spring/rails
AWS e devops
- Bacharelado em Ciência da Computação ou alguma formação equivalente, ou uma experiência profissional equivalente

## Local
Escritório, São Paulo - WeWork Pinheiros

## Benefícios
- Salário competitivo e stock options
- Trabalhar diretamente com nosso time internacional de Nova York
- Plano de saúde, Auxílio transporte e Vale alimentação
- Reembolso de fatura de celular
- Desenvolvimento profissional continuo
- Reembolso para participação de conferencias e eventos tecnicos
- Aulas de idioma
- Eventos mensais com o time
- Lanches e bebidas ilimitadas e acesso a nossa geladeira com cerveja
- Excelente time de pessoas brilhantes, criativas, talentosas e apaixonadas pelo que fazem

## Contratação
CLT.

## Nossa empresa
Voxy é uma empresa com sede na cidade de Nova York que está mudando a forma com que o mundo aprende inglês. Nossa tecnologia de personalização proprietária e parcerias exclusivas com produtores líderes de conteúdo nos possibilita fornecer uma solução única para mais de 2,5 milhões de alunos de inglês em todo o mundo. Nosso aplicativo para celular e aplicação web torna possível para qualquer pessoa aprenda com o mundo ao seu redor, transformando experiências e conteúdo do dia-a-dia em atividades divertidas e semelhantes a jogos.

## Como se candidatar
[Aplique diretamente no link Software Engineer na Voxy.](https://grnh.se/92fc57c71)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
