### ISSUE TITLE
[Curitiba] Desenvolvedor FullStack Sr.

### ISSUE THREAD

**Issue by debonaleonardo** [backend-br/vagas#214]
DESCRIÇÃO DA VAGA

    Startup de tecnologia busca pessoas que têm grande potencial e vontade de fazer 
a diferença para causar grande impacto no mercado atual.
    Saiba mais sobre a Leads2b: www.leads2b.com
    Atualmente estamos buscandos profissionais FullStack Sr, com capacidade de auto
gerenciamento, foco, disciplina e responsabilidade.

LOCAL

Curitiba / PR

QUEM ESTAMOS BUSCANDO?

Aqui na Leads2b sempre buscamos o que há de mais inovador em termos de tecnologia
e infraestrutura, entre os requisitos que os candidatos devem possuir, estão:

Linguagens:
Vuejs 2
Node.js (GraphQL, Loopback, Express)
PHP
Python

Banco de dados:
MySQL
MongoDB
Google BigQuery

Versionamento:
Git

Será considerado um diferencial:

Docker
Rancher
Jenkins
AWS
Bitbucket
JIRA
npm
yarn
Angular
Ionic
Quasa

CONTRATAÇÃO

PJ

Por favor envie um email para leonardo@leads2b.com com seu CV anexado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
