### ISSUE TITLE
[São Paulo, Curitiba, Remoto] Desenvolvedor Python no [Olist]

### ISSUE THREAD

**Issue by cristianmedeiros** [backend-br/vagas#2140]
O olist esta crescendo e precisamos de você! Estamos aprendendo a viver esse novo momento e estamos contratando para nossos escritórios regionais ou posições remotas.

Os profissionais do olist podem contar com um ambiente onde a autonomia e a coragem são bastante estimuladas. Valorizamos novas ideias, criatividade, confiança, companheirismo e a diversidade. Aprendemos juntos e não abrimos mão das boas práticas de desenvolvimento de software. Procuramos programadores que gostem de aprender coisas novas e que amam o que fazem.

Somos um time com o propósito de empoderar o comércio. Se você se identifica com estes valores e gosta de criar soluções com impacto positivo e com foco nas pessoas que utilizam nosso serviço, você é mais que bem vindo.

Todas as nossas vagas também são abertas para PCD.

### Presencial
As vagas presenciais do olist são para trabalhar em um dos nossos escritórios em Curitiba ou São Paulo. Oferecemos ajuda de custo no caso de mudança de cidade e temos flexibilidade para fazer home office alguns dias da semana no time de desenvolvimento:
https://olist.gupy.io/jobs/118828?jobBoardSource=gupy_public_page

### Remoto
As vagas remotas do olist são para trabalhar de qualquer região do Brasil:
https://olist.gupy.io/jobs/98275?jobBoardSource=gupy_public_page

### O que você precisa saber
- Python 3 e Django;
- HTML5, CSS3 e Javascript básico;
- Testes automatizados e/ou TDD;
- Modelagem e consumo de API's REST;
- Modelagem de bancos de dados relacionais (preferencialmente PostgreSQL);
- Pair Programming, Testes unitários, Code review;
- GIT para versionamento de código;
- Metodologia Ágil (scrum).
- Ter autonomia, capacidade de autogestão e auto-organização do trabalho;
- Iniciativa e colaboração em equipe
- Flexibilidade
- Comunicação 

### O que torna vocês especial para nós
- Conhecimento em arquitetura orientada a eventos com o padrão Pub/Sub (preferencialmente AWS SNS e SQS);
- Ter trabalhado em projeto no setor de e-commerce;
- Conhecer ou ter trabalhado com Django REST Framework;
- Ter tido experiência em um ambiente de trabalho home office;
- Ter tido relacionamento direto com áreas de negócio;
- Inglês avançado.

### Benefícios
Já imaginou decidir o quanto você vai receber no seu vale-alimentação? No Olist isso é totalmente possível. Isso acontece porque disponibilizamos um pacote de benefícios flexíveis baseado em um sistema de pontuação. Com ele, você decide onde colocar seus pontos e monta a sua própria combinação de benefícios. Confira abaixo os benefícios que os olisters têm acesso:

- Vale-Alimentação
- Vale-Refeição 
- Vale-transporte
- Auxílio Mobilidade
- Estacionamento
- Plano de Saúde
- Plano Odontológico
- GymPass
- Incentivo aos estudos (cursos de extensão, graduação, especialização, pós-graduação e MBA)
- Magnetis

### Benefícios em nossos escritórios
- Frutas fresquinhas todos os dias
- Chá e café à vontade
- Vending machine com bebidas e diversos lanches 
- Happy hour mensal com comidas e bebidas liberadas
- Desconto em restaurantes, universidades, escolas de idiomas e outros estabelecimentos
- Programa de indicação de funcionários
- Biblioteca
- Mais de 20 cursos in company em temas diversos

### Vem com a gente!

O olist é a maior loja de departamentos dos marketplaces e a ferramenta de empoderamento de lojistas que mais cresce no Brasil. Nossas soluções impactam positivamente os resultados de milhares de empresas, desde pequenos negócios até grandes marcas do mercado.

Com a nossa tecnologia robusta, já agregamos valor à vida de mais de 9 mil lojistas que utilizam nossa plataforma de vendas todos os dias. Eles cadastram seus produtos para serem vendidos em nossa loja dentro dos principais sites varejistas do país.

Esse modelo de negócio vem sendo construído e aprimorado por mais de 300 profissionais determinados a revolucionar o comércio mundial.

Labels:
São Paulo
Curitiba
Remoto
Python
CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
