### ISSUE TITLE
[São Paulo, SP] Desenvolvedor BACKEND [JUNIOR|PLENO|SENIOR] | NETPOS SA

### ISSUE THREAD

**Issue by saboianeto** [backend-br/vagas#2141]
**### Empresa**
Nossa missão é entregar o app de vendas mais utilizado no país! Temos um monte de projetos na fila e novas funcionalidades não param de surgir. Pra isso, a gente precisa de um time incrível pra concluir tudo isso com excelência, qualidade e velocidade. 

Estamos em fase de expansão e crescimento e procuramos novos profissionais que gostem de desafios para fazer parte do nosso time!

**### Requisitos:**

Domínio de orientação a objeto, estrutura de dados e algorítimos.
Conhecimento em arquiteturas distribuídas, resilientes, escaláveis e de alta performance.
Experiência com as melhores práticas de qualidade de software. Ex: testes automatizados, segurança, monitoração e documentação técnica.
Ser comprometido e engajado, com atitude de dono sobre contexto do produto, mantendo o foco na entrega de valor.
Ser proativo, buscando soluções que agreguem ao dia a dia do time e da Cia.
 
### **Desejável:**
Bom conhecimento e experiência em Java (pelo menos 2 anos),
Amplo conhecimento em serviços RESTful para criação de endpoints,
Amplo conhecimento em criação e estruturação de APIs,
Experiência com uso de banco de dados SQL (MySQL),
Desejável experiência com Cloud Computing AWS (EC2, ELB, RDS, S3, API Gateway, Beanstalk e Lambda).

 **### Atividades:**

Criar soluções que tornem a vida dos nossos clientes mais simples e produtiva.
Avaliar impactos, riscos e estimar esforços.
Garantir qualidade das entregas.
Automatizar tudo que for possível.
Criar monitorações e acompanhar o ambiente de produção.
Interagir com diversas áreas da Cia.
Fazer mentoring com outros profissionais.
Compartilhar suas opiniões e ideias.

**### Posição**
Sênior.
PL.

### **Local**
São Paulo - SP - Zona Sul - Moema
Campinas - SP 

### **Tipo de contratação**
CLT

**### Benefícios**
• Plano de saúde
• Seguro de Vida
• Vale refeição/alimentação
• Vale Transporte
• Salario a combinar

### **Diferenciais**
• Ambiente de trabalho descontraído
• Trabalhamos com metodologias ágeis (Scrum)
• Estamos sempre em busca de inovação
• Não desenvolvemos apenas software, também desenvolvemos pessoas 

**### Como aplicar**
Contato
Dúvidas mande um e-mail para antonio.saboia@netpos.com.br (11)   ##99347-6267 Vaga IOS PL ou SR.
www.smartpos.net.br

**Comment by mayermatheus** [comment]
@saboianeto Aceita Remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
