### ISSUE TITLE
[SÃO PAULO] Lead Software Engineer na KENOBY

### ISSUE THREAD

**Issue by luizadpassos** [backend-br/vagas#2142]
A Kenoby é uma das startups que mais crescem no Brasil, sua proposta é oferecer às empresas uma solução que contribua para a contratação dos melhores profissionais. Isso se torna possível através de uma plataforma moderna e amigável que inclui todo o processo de recrutamento, se integrando com diversas ferramentas de mercado e fornecendo uma inteligência que sugere os candidatos mais compatíveis.

O desafio consiste em ser um(a) líder técnico para compor a equipe e colaborar no projeto, construção e manutenção dos serviços. O Lead Software Engineer será responsável pelas entregas de seu Squad, visando sempre melhorar os serviços, torná-los mais escaláveis, manuteníveis e confiáveis!

Vai ser bacana se você:
- Ter experiência em AWS (Ex: EC2, ELB, ECS, ASG, SQS, RDS, VPC);
- Ter experiência em CI/CD (Jenkins, Codeship, Codebuild, CircleCI);
- Conhecer bastante do uso do ElasticSearch e de Cache em sistemas Web;
- Já ter liderado outros Software Engineers na construção de um produto bem sucedido;
- Ter habilidade e preocupação com a excelência técnica e boas práticas de Arquitetura/Cloud;
- Ser mais apaixonado(a) por desenvolvimento de software do que por uma linguagem de programação em si.

O regime da oportunidade é CLT, e conta com Vale Transporte, Alimentação, Assistência Médica, Odontológica, e remuneração compatível com o mercado!

**Caso você não more em São Paulo** (SP), esta oportunidade dispõe de **auxílio mudança** para facilitar o seu deslocamento!!!

Mais informações sobre a oportunidade e onde se cadastrar na oportunidade no link a seguir: https://byintera.in/b2

Qualquer dúvida, estou a disposição! :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
