### ISSUE TITLE
[São Paulo] Full Stack Developer na Playax

### ISSUE THREAD

**Issue by flaviokr** [backend-br/vagas#2144]
Olá, somos da [**Playax**](https://www.playax.com) e estamos contratando pessoas desenvolvedoras fullstack!

## A PLAYAX

A Playax é uma empresa de **inteligência de dados** voltada para o mercado musical. Temos centenas de clientes de diferentes perfis: desde artistas independentes até grandes empresas como **Globo, Youtube, Universal Music, T4F, Warner Music**, entre outros.

Nosso objetivo é organizar e facilitar o acesso às informações sobre o mercado da música para criar ações bem informadas. Então, se você gosta de tecnologia, dados e música, vai se dar muito bem conosco 😉 

## NOSSA CULTURA

A Playax é uma empresa pequena - somos hoje em 10 pessoas e temos uma cultura bastante horizontal. Nosso time utiliza metodologias ágeis e nós adoramos pair-programming. Buscamos usar tecnologias modernas e temos muita abertura para experimentação. Gostamos de nos encontrar pessoalmente no escritório, mas há  possibilidade de trabalho remoto. Nosso horário é flexível e nosso escritório é pet-friendly 😃 

## TECNOLOGIAS

Aqui na Playax, usamos várias tecnologias, porém **o único pré-requisito para a vaga é conhecimento em Ruby on Rails.**

- Ruby on Rails
- SQL (MariaDB)
- Vue.js
- Docker
- Kubernetes
- Scala
- Audio Fingerprinting
- NoSQL (Solr, Redis, Aerospike, MongoDB)

Não se preocupe, você poderá aprender sobre todas essas tecnologias aqui. Adoramos compartilhar conhecimento e incentivar o crescimento de nossos colegas ✌️ 

## DETALHES

Nossa faixa salarial varia dependendo do nível de experiência e conhecimento do candidato. Estamos abertos a negociações.

- **Pleno:** a partir de  R$ 5.000,00
- **Sênior:** a partir de R$ 8.000,00

## TENHO INTERESSE 😁 

Você pode entrar em contato através do vagas@playax.com - vem bater um papo com a gente!

Se quiser conhecer um pouco mais sobre o nosso trabalho, pode conferir nossa palestra na **RubyConf** de 2019 sobre [Identificação Automática de Músicas](https://www.eventials.com/locaweb/flavio-kon-rosenfeld-guto-motta-audio-fingerprinting-identificacao-automatica-de-musicas).

### Labels
PJ
Presencial
Remoto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
