### ISSUE TITLE
[São Paulo] Desenvolvedor(a) back-end JR/PL/SR na [Juntos Somos +]

### ISSUE THREAD

**Issue by willianantunes** [backend-br/vagas#2146]
Somos a Juntos Somos Mais, o maior programa de fidelidade do varejo de material de construção e maior marketplace B2B do setor.

Fomos criados em 2018, por 3 gigantes do setor (Votorantim Cimentos, Gerdau e Tigre), com o propósito de fortalecer o varejo e transformar a vida dos profissionais que constroem sonhos. Estamos crescendo a passos largos, já são mais de 20 empresas e 250 mil membros no programa de fidelidade.

Nosso time é fissurado pelo sucesso do varejo.

## Descrição

Precisamos de alguém que vá além de códigos e entenda que desenvolvemos aplicações para pessoas usarem. Sendo assim, você estará livre para propor melhorias, novas ideias, compartilhar conhecimento e participar ativamente de todas as partes da concepção do produto 😁

Importante ter boa capacidade de comunicação e visão de negócio, você vai atuar em um time multidisciplinar.

## Localização

Estamos localizados na região da Vila Olimpia em São Paulo, bem próximo da estação de trem e do shopping.

## Responsabilidades

- Desenvolver aplicações para atender às necessidades do negócio;
- Manutenção e evolução dos produtos;
- Construir códigos com qualidade e testáveis;
- Estudar e implementar novas tecnologias;
- Foco no usuário.

## Skills

- Domínio de Python e atuação em projetos com Django;
- Modelagem de APIs: desenvolvimento e consumo (REST);
- Domínio de testes (unitário e integração);
- Experiência com bancos SQL e NoSQL;
- Experiência com Docker e Kubernetes;
- Ter atuado em times ágeis (Kanban, Scrum) e gostar de atuar com time multi-funcional.

## Desejáveis

- Cultura open source
- React Native e básico de Java/Kotlin e Swift
- C#

## Benefícios

- CLT
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Vale Refeição
- Vale-transporte ou subsídio estacionamento
- Bônus (Remuneração variável)
- Gympass – para sua saúde e bem-estar!
- Home office
- Equipamento de última geração (MacBook Pro)

## Ambiente

- Videogame e ping-pong 🎮
- Frutas e snacks todos os dias 🍓
- Dresscode liberado - seja você! 🧦

## Como se candidatar

1. Primeiramente faça nosso teste seguindo as instruções: https://github.com/juntossomosmais/code-challenge
2. Esperamos que você envie o desafio em até 10 dias, mas caso precise de mais prazo avise a gente 😊
3. Mande um e-mail p/ vagas-dev@juntossomosmais.com.br com o título: [Back-end Developer] Seu nome
4. Nesse email adicione tudo que considere relevante no seu perfil: GitHub, LinkedIn, projetos e etc...
5. Não esqueça de enviar o link do repositório com seu teste
6. Boa sorte 🙏

Quer ser protagonista da sua carreira e contribuir para um mundo melhor?

Junte-se, pois Juntos Somos +! 💕

**Comment by ghost** [comment]
A vaga ainda está aberta ? Só vi o anúncio agora, e tenho interesse. Fiz a pergunta pq vc citou "10 dias", mas a issue foi aberta há 15.

**Comment by willianantunes** [comment]
> A vaga ainda está aberta ? Só vi o anúncio agora, e tenho interesse. Fiz a pergunta pq vc citou "10 dias", mas a issue foi aberta há 15.

Oi, @lukelima! Sim, continua disponível. Veja todas as nossas vagas [aqui](https://juntossomosmais.gupy.io/).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
