### ISSUE TITLE
[Trabalho Remoto] Desenvolvedor Backend Node.JS Sênior na iClinic

### ISSUE THREAD

**Issue by fabianaiclinic** [backend-br/vagas#2149]
## Descrição da vaga

A iClinic está à procura de um desenvolvedor back-end (remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: obcecado por qualidade e desenvolvimento ágil. Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

## Local

Remoto 

## Benefícios

- Vale refeição/alimentação;
- Plano de saúde;
- Plano de Carreira;
- Plano de participação nos resultados (PPR);
- Bônus por indicação de outros profissionais para trabalhar na iClinic;
- No escritório: Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- No escritório: Sem dress code,  Trabalhe do jeito que achar confortável;
- No escritório: Café da manhã, frutas e o sagrado cafezinho ao longo do dia;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Incentivo financeiro para desenvolvimento técnico;

## Requisitos

- Experiência comprovada em Node + Express;
- Conhecimentos em metologias de testes: TDD, unitários, de integração, de carga e mocks;
- Conhecimentos em Docker e AWS;
- Domínio do Git e organização no histórico de commits;
- Legibilidade do código e Clean Code;
- Clareza de raciocínio e exposição da solução;
- Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, front-end, QA tester;
- Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
- Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
- Modelagem de bancos de dados: Relacional e NOSQL;
- Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;

## Contratação

CLT com benefícios

## Nossa empresa

A iClinic é uma das startups de tecnologia em saúde que mais cresce no Brasil.

Nossa missão é Descomplicar a saúde no Brasil.

E como fazemos isso hoje? 

Oferecendo o melhor software de gestão para clínicas e consultórios médicos.

Como atingir este objetivo?

Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento.

## Como se candidatar

Veja mais detalhes da vaga e faça sua candidatura: https://iclinic.gupy.io/jobs/141733

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ CLT

**Comment by guilhermeoa07** [comment]
Apenas sênior? Vaga para pleno?

**Comment by fabianaiclinic** [comment]
No momento buscamos um profissional Sênior, mas se você se interessou na oportunidade e talvez não seja o momento ainda, faça a candidatura! Assim ficaremos com você no radar para futuras oportunidades ;)

**Comment by acgfbr** [comment]
troca pra php que eu vou

**Comment by danielsidev** [comment]
Vou aplicar!
http://danielsiqueira.net
