### ISSUE TITLE
[São Paulo - SP] Engenheiro(a) de Software Sênior na [GetNinjas]

### ISSUE THREAD

**Issue by restarac** [backend-br/vagas#215]
# Sobre a GetNinjas

Somos a maior plataforma de contratação de serviços do Brasil, com mais de 350 mil profissionais cadastrados em mais de 200 tipos de serviço – desde eletricistas até professores de inglês.

 Desde 2011, auxiliamos profissionais autônomos e pequenas empresas a encontrarem novos clientes. Geramos mais de 2,5 milhões de pedidos de serviços ao ano para estes profissionais, que antes dependiam de indicações ou de canais de marketing tradicionais. Do outro lado, clientes encontram profissionais confiáveis em menos de 5 minutos – e comparam orçamentos para fechar com aquele que melhor atenda suas necessidades.

Somos uma startup de alto crescimento que já captou mais de R$ 47 milhões de investimento da Tiger Global, Monashees Capital e Kaszek Ventures – alguns dos mais reconhecidos fundos de venture capital. E contratamos apenas os melhores talentos; em todos os níveis, em todas as áreas.

_Mais informações: https://jobs.kenoby.com/getninjas_

# O desafio

Buscamos um NINJA proativo, inteligente, criativo, realizado, enérgico e comunicativo. Queremos alguém que saiba trabalhar em equipe e que queira fazer parte de algo grande! E claro, que ame tecnologia!

Nós valorizamos profissionais que não tenham medo de novos desafios ou novas tecnologias. Queremos alguém que não fique na zona de conforto.

**Exemplos de desafios que você provavelmente resolverá no dia a dia dentro do GetNinjas:**

- Construir e manter micro serviços em Ruby ou qualquer outra linguagem que resolva bem nosso problema
- Ajudar nosso time de infraestrutura a evoluir nosso processo de deploy, aumentar a resiliência e performance dos nossos sistemas
 - Melhorar e otimizar APIs
 - Medir e criar alarmes para os sistemas críticos do nosso negócio

# O que esperamos de você

### Culturalmente você terá um bom fit se:
-  Pensar de maneira simples em como resolver problemas, sempre mantendo a qualidade.
 - Resolver problemas que você encontre no meio do caminho. O problema do outro pode ser seu 
daqui algum tempo.
 - Entregar features que agreguem valor ao nosso negócio (diretamente: algo que impacte a vida de nossos clientes e profissionais; indiretamente: melhorando o dia a dia do time de tecnologia)
- Valorizamos muito pessoas que não se apegam apenas a uma tecnologia. Acreditamos que a diversidade de conhecimento faz com que a forma inicial que pensamos a solução de um problema possa ser melhorada.

### Experiências como Back-End que valorizamos:

-  Experiência com Ruby (mínimo 3 anos) ou alguma outra linguagem orientada a objetos
-  RESTful APIs / GraphQL
-  Mensageria (SQS ou Sidekiq)
-  Testes automatizados de unidade / funcional / integração
-  Infraestrutura como código (Docker, Chef, ECS, Terraform)
-  AWS
-  Banco de dados SQL (AWS Aurora) e NoSQL (Redis, DynamoDB, MongoDB)
-  WebFrameworks (Rails, Sinatra, Grape, Express) 

### Adicionais que seriam legais:

 - CSS / HTML5
 - Conhecimento Android / iOS
-  ElasticSearch

# O que oferecemos para você

- Grandes desafios e um time colaborativo, aberto a criar, discutir e inovar
- Ninjas engajados e uma cultura focada em resultados
- Plano de saúde
- Vale transporte ou estacionamento
- Vale Refeição ou Vale Alimentação
- Ambiente divertido e descontraído, com comida no escritório, pet friendly.
- Pacote de remuneração  competitivo com o mercado, incluindo oportunidade de conquistar
-  Stock Options.
- Escritório super bem localizado – você pode vir de bike, metrô, ônibus ou carro: Ficamos a 30 metros da estação Fradique Coutinho
-  GymPass

_Mais detalhes: https://jobs.kenoby.com/getninjas/job/engenheiroa-de-software-senior/5a9d871ad11ea5090f341c0b_

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
