### ISSUE TITLE
[Remoto] PHP Developer na 2SOW

### ISSUE THREAD

**Issue by lucasxciv** [backend-br/vagas#2151]
## Descrição da vaga

 - Trabalhar em APIs utilizando PHP 7, Rest e GraphQL;
 - Trabalhar no suporte de sistema legado com PHP e jQuery;
 - Escrever testes automatizados;
 - Aplicar boas práticas de codificação (SOLID) e de OOP;
 - Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
 - Participar do processo criativo e auxiliar na construção dos sistemas;
 - Colaborar na automatização de processos internos (CI e CD);
 - Nos deixar impressionados com sua capacidade criativa.
 
## Local

 - Remoto ou Escritório, Santa Barbara D'Oeste / SP;
 
## Horário de trabalho

 - Segunda a Quinta das 8h às 17:15 e Sexta das 8h às 16h;
 
## Benefícios

 - Vale alimentação;
 - Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente;
 - No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

## Requisitos

**Obrigatórios:**

 - Ter experiência relevante em PHP OOP;
 - Ter conhecimento em SOLID e boas práticas de programação;
 - Ter conhecimento em testes unitários usando PHPUnit;
 - Ter conhecimento em JavaScript.
 
**Diferenciais:**

 - Ter conhecimento dos conceitos do GraphQL;
 - Ter conhecimento em ferramentas de Frontend.

## Nível

 - Pleno
 - Junior

## Contratação

 - CLT

## Nossa empresa

Percepção, motivação e aprendizagem são os elementos propulsores do desenvolvimento da humanidade. Assim é com a 2SOW, uma empresa focada e motivada pelos desafios de novos projetos, novas tecnologias, geração e uso inteligente da informação a órgãos públicos.

## Como se candidatar

Por favor envie um email para tulio@cacdigital.com.br com o seu CV anexado 
Enviar no assunto: **Vaga Backend**

**Comment by victorvhs** [comment]
enviado

**Comment by JIFerreira** [comment]
> ## Descrição da vaga
> * Trabalhar em APIs utilizando PHP 7, Rest e GraphQL;
> * Trabalhar no suporte de sistema legado com PHP e jQuery;
> * Escrever testes automatizados;
> * Aplicar boas práticas de codificação (SOLID) e de OOP;
> * Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
> * Participar do processo criativo e auxiliar na construção dos sistemas;
> * Colaborar na automatização de processos internos (CI e CD);
> * Nos deixar impressionados com sua capacidade criativa.
> 
> ## Local
> * Remoto ou Escritório, Santa Barbara D'Oeste / SP;
> 
> ## Horário de trabalho
> * Segunda a Quinta das 8h às 17:15 e Sexta das 8h às 16h;
> 
> ## Benefícios
> * Vale alimentação;
> * Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente;
> * No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.
> 
> ## Requisitos
> **Obrigatórios:**
> 
> * Ter experiência relevante em PHP OOP;
> * Ter conhecimento em SOLID e boas práticas de programação;
> * Ter conhecimento em testes unitários usando PHPUnit;
> * Ter conhecimento em JavaScript.
> 
> **Diferenciais:**
> 
> * Ter conhecimento dos conceitos do GraphQL;
> * Ter conhecimento em ferramentas de Frontend.
> 
> ## Nível
> * Pleno
> * Junior
> 
> ## Contratação
> * CLT
> 
> ## Nossa empresa
> Percepção, motivação e aprendizagem são os elementos propulsores do desenvolvimento da humanidade. Assim é com a 2SOW, uma empresa focada e motivada pelos desafios de novos projetos, novas tecnologias, geração e uso inteligente da informação a órgãos públicos.
> 
> ## Como se candidatar
> Por favor envie um email para [tulio@cacdigital.com.br](mailto:tulio@cacdigital.com.br) com o seu CV anexado
> Enviar no assunto: **Vaga Backend**

Bom dia, tudo bem?
Eu atuei com PHP em 2016, e estou querendo voltar agora, poderia enviar para junior?

**Comment by nelsonmfinda** [comment]
Olá, aceita pessoa de fora?
