### ISSUE TITLE
[100% Remoto] DevOps no Catarse ### Inscrição em http://catar.se/devops

### ISSUE THREAD

**Issue by thiagocatarse** [backend-br/vagas#2153]
### Objetivo da vaga

- Trabalhar junto ao Time de Produto do Catarse, hoje composto por 1 Líder de Produto/Designer, 2 desenvolvedores Back-end e 1 Desenvolvedor Full-stack.

- Você será o DevOps do Catarse que, em última instância, será a pessoa no time responsável por garantir a estabilidade de nossa infra-estrutura, por implementar processos que gerem mais segurança para nossa aplicação e por gerar uma maior velocidade de desenvolvimento e entrega do nosso time de produto, por meio da implementação de automações.

- Hoje o nosso desenvolvedor back-end Sênior já cumpre esse papel, porém estamos em uma fase de expansão do negócio e, com os desafios que estamos enfrentando pela frente, precisamos de uma pessoa focada em DevOps, para que a gente possa escalar nossa aplicação e ganharmos mais velocidade no desenvolvimento de features e em processos de refatoração em curso.

### Quem é você

- Apaixonada(o) pelo o que o Catarse faz: ser parte do processo de construção de uma cultura de colaboração no Brasil através do financiamento coletivo de projetos criativos;

- É curioso(a) e gosta de ter problemas complexos no seu colo para serem resolvidos;

- Fica confortável em trabalhar de casa - somos uma empresa 100% remota;

- Fica confortável em trabalhar em um time enxuto: não temos recursos infinitos, não temos equipe enorme para resolver tudo. É preciso colocar a mão na massa;

- É organizada(o) e rígido(a) com a qualidade (e beleza!) do código escrito;

- Tem apreço por uma boa documentação do código;

- Tem paciência para, na medida do possível, traduzir problemas de programação para uma linguagem mais palatável para outros membros do time do Catarse (que não falam a língua dos devs!);

- Interessado(a) em aprender novas linguagens e se adaptar às mudanças (às vezes rápidas) no código do Catarse;

### Como será o seu dia a dia

- Você trabalhará diretamente com o time de produto, na implementação, melhoria e manutenção das ferramentas que monitoram, provisionam, configuram e fazem o deploy de nossa plataforma. Seu foco é garantir a agilidade, resiliência e robustez de nossos deployments;

- Criará soluções com as melhores práticas de automação e cloud computing, e repassará essas práticas para o restante do time de produto;

- Dará apoio e ensinará, quando necessário, o time de produto a trabalhar com infraestrutura como código;

- Irá garantir a disponibilidade dos ambientes, setup de novos ambientes, atualização de políticas da informações, ações de controle e redução de custo, testes e melhorias de segurança / infraestrutura;

### Conhecimentos desejáveis
Buscamos uma pessoa que seja apaixonada por desenvolvimento de software escalável de qualidade:

- Experiência profissional em CI, CD, Linux, Banco de Dados;
- Experiência profissional em Docker e seus orquestradores;
- Experiência profissional em AWS, ECS, EC2, S3... ;
- Experiência profissional em Git;
- Experiência profissional com Heroku;
- Experiência com APIs REST;
- Experiência com logging e documentação de código;

Seria desejável, mas não necessário ter:

- Vivência com trabalho remoto;
- Conhecimento em segurança da informação;
- Conhecimento em ElasticSearch;
- Experiência profissional com desenvolvimento de aplicações Ruby;
- Já ter apoiado projetos no Catarse é sempre um plus  🖤

### Local de trabalho
Não temos escritório físico. Então você trabalha de onde quiser!

### Benefícios
- **Trabalho remoto:** você trabalha de casa e tem flexibilidade para construir o seu horário com o time.
- **Carga horária reduzida:** full-time no Catarse é de 30 horas semanais.
- **Bem-estar:** Você pode usar até 3 horas de suas horas semanais para atividades pessoais de bem-estar (Natação? Corrida? Bicicleta? Surfe? O que mais te interessar!)
- **Férias:** Você vai ter 30 dias de férias/folgas remuneradas por ano e, além disso, dias de dispensa quando tiver questões médicas (para você e familiares), que não contam nesses dias de férias.

### Salário
- R$6.000,00 (full-time). Trabalho remoto. Pagamento via PJ
- Início em Abril/Maio de 2020.

**Comment by thiagocatarse** [comment]
Esqueci de informar que a inscrição para a vaga é em http://catar.se/devops

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
