### ISSUE TITLE
[Joinville] Back-end Developer na NG

### ISSUE THREAD

**Issue by vitorebatista** [backend-br/vagas#2154]
## Descrição da vaga
Buscamos um backend developer para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossas plataformas. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com Node.JS, Typescript, PostgreSQL, GraphQL e muito mais, no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. padrões de projeto, testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local
[Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC](https://goo.gl/maps/f5mLxtRkd892)

## Benefícios
- Vale transporte ou combustível / Vale alimentação ou refeição (sim, conforme legislação);
- Plano de saúde Bradesco;
- Plano odontológico;
- Seguro de vida;
- Bolsa de estudo para ensino superior conforme regras da empresa;
- Casa de praia para os colaboradores em Piçarras/SC.

## Diferenciais
- Ambiente extremamente propício à aprendizagem;
- Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
- Diferentes stacks para diferentes projetos;
- Mesa de sinuca para jogar nos intervalos e almoço;
- Almoço de 1 hora e meia;
- Café + bolachas/biscoitos + frutas todos os dias;
- Geladeira e microondas para esquentar seu almoço e lanches.

## Requisitos Obrigatórios:
- Conhecimento com Git para versionamento de código
- Linux user (você escolherá sua distro)
- Inglês técnico (👀 stackoverflow)
- Experiência com API's RESTful e/ou GraphQL
- Experiência com Docker
- Banco de dados relacional (PostgreSQL, etc.)
- Familiaridade com desenvolvimento ágil
- Conhecimento DevOps - CI (Integração Contínua) / CD (Entrega contínua).

## Desejáveis
- Experiência com AWS
- Ansible
- Terraform
- Github Actions
- Programação funcional (Ramda)

## Diferenciais:
- GitHub ativo com projetos open source;

## Contratação
CLT

## Nossa empresa
A [NG Informática](https://www.ngi.com.br) é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS). Também possuímos um sistema de gestão de alertas chamado [Rung](www.rung.com.br), este construído com Node.js. Atualmente estamos com muitas melhorias no [Keepfy](https://www.keepfy.com), sistema SAAS com a _stack_ descrita nesta vaga.

## O que usamos:
- GIT + Scrum + Kanban + TFS
- Node.js + Typescript
- TypeORM + PostgreSQL
- Graphql + Apollo
- RabbitMQ
- Jenkins
- Github + Github Actions
- Slack

## Como se candidatar
Por favor, envie um email para curriculo@ngi.com.br com seu CV anexado e link do Github com o assunto: Vaga Back-end Developer - Github/Backend-BR

## Labels
- CLT
- Presencial
- Node.js
- Typescript
- PostgreSQL
- Graphql

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Existe a possibilidade dessa vaga ser remota? Sou do Rio (RJ).
Abraços!
http://danielsiqueira.net

**Comment by vitorebatista** [comment]
olá @danielsidev, infelizmente para esta vaga não é possível remoto. Contudo, caso desejar morar em Joinville/SC, podemos lhe apoiar. :smiley:

**Comment by 14luisdias** [comment]
vocês estão contratando sempre?, porque acabei de comprar o curso da rocketseat, e queria tentar trabalhar por ai. 
https://www.linkedin.com/in/luis-antonio-14370a1a0/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
