### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Sênior Ruby on Rails [LOCAWEB]

### ISSUE THREAD

**Issue by BeatrizFrancaS** [backend-br/vagas#2156]
Oi, pessoal!

Sou Tech Recruiter e estou com posições em aberto para **Dev Sênior** e **Tech Lead** com foco em Ruby on Rails para a área de Produtos Digitais da **Locaweb** (São Paulo/SP).

O profissional estará em times multidisciplinares (Product Owner, UX, Marketing e SysAdmin) com mindset ágil, desenvolvendo soluções que encantem nossos clientes. Garantirá a qualidade e a manutenibilidade de todo código produzido por você e seus pares. Enfrentará desafios envolvendo diferentes linguagens e tecnologias.

Caso tenha interesse, encaminhe seu currículo para beatriz.franca@beit.work para mais detalhes.

Obrigada!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
