### ISSUE TITLE
Pessoa Desenvolvedora de Software Backend - (Jr, Pl e Sr) [Wirecard]

### ISSUE THREAD

**Issue by mmoura-wirecard** [backend-br/vagas#2157]
**Sobre nosso time de Produtos & Engenharia**

Somos um time multidisciplinar que busca por meio de tecnologia e design resolver problemas reais de nossos clientes. Trabalhamos com o conceito de times autônomos que possuem missões próprias (alinhadas a estratégia da Wirecard) e cuidam de todo o ciclo de desenvolvimento de produtos. Desde a concepção, à implementação e operação dos sistemas. Este é o nosso jeito de emular pequenas start-ups dentro da Wirecard, tornando a equipe dona do produto e 100% responsável pelo sucesso das nossas soluções. Comemoramos (com cevada) nossas conquistas todas as sextas-feiras. Dividimos nosso conhecimento com as já consagradas talks semanais de um dos membros do time. Isso tudo, alinhado com muita responsabilidade e vontade de ajudar os clientes, ajudar a comunidade opensource e ser ajudado.

Aqui na Wirecard a diversidade e a inclusão já começa pelo fato de sermos globais, o que faz com que os nossos funcionários não tenham um background homogêneo. Não fazemos distinção étnica, religiosa, de gênero, sexualidade ou qualquer outra questão. Respeitamos as pessoas como elas são e como querem ser. As diferenças são vistas como algo bom, que pode somar e gerar diferentes visões para o dia a dia na empresa.

**Requirements**
- Conhecimento / experiência em alguma linguagem de programação orientada a objetos (Java, Ruby, Python, NodeJS)
- Noções em APIs Restful
- Noções em MVC
- Noções HTML / CSS / JavaScript
- Inglês

**Quais tecnologias utilizamos?**

A Wirecard hoje possui uma arquitetura baseada em (Micro-)Serviços e nos últimos anos temos enfrentados diferentes tipos de problemas:

- Separação de responsabilidades em uma arquitetura baseada em Serviços
- Uso de diferentes linguagens de programação (Java, Ruby, NodeJS, Go, JavaScript, CoffeeScript)
- Criação de bibliotecas para dispositivos móveis (Android, iOS)
- Comunicação assíncrona utilizando filas (RabbitMQ, ActiveMQ)
- TDD, BDD, Testes de Integração, Integração Contínua
- Monitoramentos e métricas das aplicações
- Integração com sistemas terceiros (Adquirentes, Anti Fraude, Bancos, etc)
- Criação de uma API Restful com conceitos de HATEOAS
- Entrega Contínua
- Relatórios rápidos e customizados para nossos clientes, utilizando ElasticSearch
- Uso de diferentes bancos de dados SQL/NoSQL (Mysql, MongoDB, Redis, etc.)
- Manutenção de sistemas novos e legados
- Automação de provisionamento de servidores em Cloud (AWS)
- Sistemas de alta disponibilidade

**Benefits**
Assistência Médica e Odontológica
VT com desconto de apenas 2%.
VR R$ 27,00 Dia.
Flex Car (combustível).
Seguro de Vida Itaú.
Frutas.
Auxilio Incentivo a Idiomas.
Convênio Gympass
Convênio Sesc.
Localização de fácil acesso(Faria Lima)
Temos HackDay
Hotdesking
Home Office, uma vez por semana.
Empresa Solidária - licença maternidade/paternidade extendida

Você pode se inscrever através do link: https://apply.workable.com/wirecardbrasil/j/ECB4D16D00/

Ou nos chame no Whatsapp pra saber mais da vaga: (11) 99873-4910

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
