### ISSUE TITLE
[Belo Horizonte] Desenvolvedor(a) Back-End Python - Pleno

### ISSUE THREAD

**Issue by marciayoshimatsu** [backend-br/vagas#2158]
Para nós, software house vai além da definição tradicional. Colaboração, espírito jovem e excelência: esses são os pilares da nossa casa! 

A *nata.house* é uma software house especializada no desenvolvimento de produtos. Tornamos nossos os desafios de todos os clientes. Prezamos por construir um hub de desenvolvimento para nossos talentos e, por consequência, fortalecemos nossa cultura de qualidade de software.

Com forte crescimento nestes dois anos de existência, nos preocupamos em construir um time com pessoas talentosas, alinhadas à cultura e aos objetivos da empresa. Além disso, buscamos constantemente maneiras de engajar, motivar e desenvolver os colaboradores para que seu crescimento acompanhe o da *nata*.

**Você precisa ter:**

Experiência com Back-End em Python;  

Fascínio não só por desenvolver, mas também pela melhoria contínua e por práticas garantem a qualidade do seu código;

**Procuramos alguém que:**

- Apoie a resolução de problemas, tem proatividade e orientação para resultados,
- Têm interesse em fomentar um ambiente colaborativo para todos,
- Atua com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso,
- É capazes de se adaptar a ambientes ambíguos e de colaborar em situações difíceis;
- Busca sempre adquirir mais conhecimento,
- Aberto a novos pontos de vista e maneiras de pensar.

**Seria bom se você tivesse:**

- Noções de conceitos e ferramentas arquiteturais referentes ao ecossistema de aplicações back-end, além de uma análise crítica e pragmática para utilizá-las dependendo do contexto da solução;
- Interesse em atuar como referência técnica, transmita seu conhecimento para seus pares de maneira clara;
- É capaz de selecionar recursos de trabalho, tais como metodologias e ferramentas de desenvolvimento de sistemas, planejando etapas e ações de trabalho;
- Desejável conhecimento em Inglês.

**São algumas vantagens de ser um *nativo*:**

- Carga horária de 40 horas semanais, de segunda a sexta;
- Plano de saúde;
- Temos vale-refeição/alimentação Sodexo de R$ 22,05 por dia;
- Para a galera do busão, vale-transporte de acordo com a necessidade, ou, se preferir, auxílio combustível no valor de R$120, sem desconto em folha;
- Bônus anual, pois, afinal, crescemos juntos! Se a empresa tem lucro, o mérito é seu e parte do lucro também;
- Se você está se desenvolvendo e gerando resultado, por quê não receber proporcionalmente? Nada de ficar estagnado: temos plano de carreira bem definido
- Who run the world? You! Temos incentivo ao aprendizado de inglês;
- Segurança extra com o nosso Seguro de Vida.
- Lanche à vontade;
- Horário flexível;
- Um happy hour mensal pago pela empresa;
- Auxílio financeiro para cursos, eventos e capacitações;
- No dress code (be you!)

Se interessou? Para se candidatar, basta preencher o formulário (https://docs.google.com/forms/d/e/1FAIpQLSfIVW4pYpxOFDe3iBhKhUAI7pwmeQSPDdq_jXzS12iWHOVDWQ/viewform) e boa sorte! :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
