### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) de Backend na Junto Seguros

### ISSUE THREAD

**Issue by Caroline-2020** [backend-br/vagas#2162]
A Junto Seguros é uma seguradora digital referência de Seguro Garantia no Brasil!
Somos guiados pelos nossos valores:
Somos Seguros
Somos Simples
Somos Transformadores

E temos o propósito claro de Garantir negócios que movem o país!
Quer fazer parte do nosso time e ajudar a escrever a história no seguro garantia? Vem JUNTO

Confira nossa oportunidade: 
**Desenvolvedor de Backend**

**Principais atividades**
- Desenvolver e desenhar a lógica do negócio e os sistemas de Backend do produto;
- Trabalhar em proximidade com os desenvolvedores de frontend para desenhar e desenvolver APIs funcionais, completos com boa performance;
- Decifrar sistemas de software existentes das empresas e ser capaz de conectar a aplicação com as fontes de dados aplicáveis;
- Criar testes de unidade e de integração, e desenvolver ferramentas de automação para tarefas diárias;
- Desenvolver código eficiente, de alta qualidade e bem documentado;
- Questionar ideias e opiniões para evitar armadilhas e soluções ineficientes. 

**Requisitos**
- Experiência anterior como desenvolvedor de backend;
- Curiosidade em aprender sobre novas tecnologias e linguagens, como Python ou Ruby;
- Amplo conhecimento de programação orientada a objetos;
- Experiência significativa escrevendo e utilizando serviços de API RESTful e apps de grande escala para melhoria de performance;
- Entendimento de web services e de sistemas de software complexos;
- Experiência com sistemas de banco de dados relacionais e não relacionais, com conhecimento de SQL, MongoDB, etc.
- Habilidade de criar testes de unidade e de integração eficazes;
- Conhecimento em SOLID, Design Patterns e Microserviços. 
- Experiência em metodologia Ágil;

**O que a Junto oferece:**
- Horário semi flexível (40hs semanais - segunda à sexta)
- Ambiente de muito aprendizado e desafios
- Área de convivência
- Escritório bem localizado - ao lado da Rua 24 horas ;)
- Vale alimentação - com 13º Vale alimentação em dezembro :)
- Vale refeição
- Copa com café à vontade e Honest Market (quiosque de auto atendimento com bebidas e lanches)
- Programa de bem estar
- Plano de saúde SulAmérica
- Plano odontológico
- Plano de previdência privada
- Incentivo ao desenvolvimento
- Auxílio creche
- Vale transporte
- Seguro de vida
- Participação nos Resultados
- Desconto em restaurantes, universidades, escolas de idiomas e outros estabelecimentos.

**Interessados enviar currículo para o e mail a seguir com o título da vaga Backend: Junto Seguros - trabalheconosco@juntoseguros.com **

**Comment by andrebrito** [comment]
Aceita remoto?

**Comment by Caroline-2020** [comment]
Olá Andre,

Essa oportunidade seria para atuar interno, dentro da empresa.

Abs,

[cid:image004.jpg@01D5A133.4D0C1860]ZS

[cid:image002.png@01D5A133.4D0C1860]ZS

[cid:image005.png@01D5A133.4D0C1860]

ZS

Caroline Corrêa
Capital Humano

(41) 3208 - 9349
juntoseguros.com






Esta mensagem é confidencial. Se você não for o destinatário, você não poderá copiar, encaminhar, divulgar ou usar as informações nela contidas. Se você recebeu esta mensagem por engano, por favor, notifique o remetente imediatamente e apague ou destrua esta mensagem.
This message is confidential. If you are not the addressee, you may not copy, forward, disclose or use any part of it. If you have received this message in error, please, notify the sender immediately and delete or destroy this message.
De: Andre Brito Fonseca [mailto:notifications@github.com]
Enviada em: terça-feira, 18 de fevereiro de 2020 17:45
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Caroline Taiane Corrêa Mateus Stonoga <carolinetcms@juntoseguros.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [Curitiba, PR] Desenvolvedor(a) de Backend na Junto Seguros (#2162)


Aceita remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
