### ISSUE TITLE
[Florianopolis] Back-End Developer na Mission Brasil

### ISSUE THREAD

**Issue by paruckerr** [backend-br/vagas#2163]
## Descrição da vaga

Buscamos desenvolvedores(as) que curtam novos desafios, que busquem resolver problemas, entregar tarefas com qualidade, auto-gerenciamento e que tenham boa comunicação.

## Local

Escritório, Florianópolis - Agronômica.

#### Diferenciais

- Flexibilidade de horário;
- Excelente localização;

## Requisitos

**Obrigatórios:**
- NodeJS;
- Restful API oriented design / SOLID;
- Integração de Tests;
- Infra (Docker / Github Actions / CI/CD);
- AWS (Lambda Serverless, SNS, S3, RDS)
- Cloudflare (Workers)
- Criar Micro-serviços e abstrair funcionalidades para melhor performance da aplicação;
- Melhorar triagem de bugs e reports para produção;

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Mission Brasil estamos construindo algo disruptivo e inovador. Acabamos de receber investimento feed para iniciar uma nova jornada em busca do Series A, estamos super empolgados e gostaríamos que você fizesse parte desse grande desafio que temos pela frente.

## Como se candidatar

Por favor envie um email para eduardo.parucker@missionbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Back End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@missionbrasil.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
