### ISSUE TITLE
[São Paulo] Back-end Java Developer na [ITeam]

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#2164]
## Descrição da vaga

Desenvolvimento Back-end em Java.

## Local

São Paulo/SP - Berrini

## Duração de projeto

3 meses - Presencial e em horário comercial.

## Contratação

Á combinar

## Nossa empresa

A ITEAM está presente no mercado há mais de 15 anos. Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado - enviar no assunto: Vaga Java

#### Alocação
- Alocado no cliente

#### Regime

- Freela
- PJ

#### Nível

- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
