### ISSUE TITLE
[Porto Alegre] FULL STACK Developer na TRINCA

### ISSUE THREAD

**Issue by robertakoche** [backend-br/vagas#2166]
**Buscamos Full Stack Developer** com sólida experiência em projetos digitais (web e mobile). Procuramos alguém que seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

**Habilidades que você precisa ter:**

• Conhecimento sólido em Javascript e ReactJS;
• Experiência com desenvolvimento backend em Node.js;
• Conhecimentos em arquitetura e engenharia de software;
• Desejável experiência com arquitetura de microserviços.

**O que ofereceremos e como é trabalhar na Trinca:** https://trin.ca/procuramos-por-voce/

![Full Stack Node e React ](https://user-images.githubusercontent.com/38670812/74741471-9c79d680-523b-11ea-9bc3-9087e1ca3c8b.jpg)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
