### ISSUE TITLE
[São Paulo] Full Stack Java [ITeam]

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#2167]
## Requisitos
Front-end: Angular, JavaScript, HTML e CSS.
Web-services: REST, JSON e XML; 
Tecnologias e Frameworks: JEE, JSE, JPA, EJB, Hibernate, Spring, Spring Security, Spring Boot, Spring MVC, JSP; 
Server Faces, JUnit, iReport, Maven, JQuery; 
Ferramentas e IDE’s: Eclipse, Netbeans; 
Servidores de Aplicação: JBoss e Tomcat;

## Nível
Pleno 
Sênior

##  Local de trabalho
São Paulo/SP – Z/S

## Duração de projeto
 6 meses (Presencial e em horário comercial)

## Modelo de contratação
CLT 

## Nossa empresa
A ITEAM está presente no mercado há mais de 15 anos. Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado.

## Para participar do processo seletivo
Envie o currículo atualizado para: viviane.pereira@iteam.inf.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
