### ISSUE TITLE
[São Paulo] Back End Developer na Radar Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#2168]
Desenvolvedor PHP Pleno e Sênior

Requisitos:
•	Superior completo em Ciências da Computação, TI ou áreas correlatas; 
•	Experiência com PHP 5, utilizando Laravel, SYMFONY2 ou superior, desenvolvimento de Procedures views, banco SQL SERVER, controle de versão GIT, com criação de branchs e tags;
•	Vivência com Linux (Debian, Ubuntu), tecnologias BaaS e Armazenamento em Nuvem;
•	Será considerado como diferencial, o profissional com experiência no setor de Saúde, Privado ou Público, desenvolvimento de aplicativos móveis híbridos: Xamarin, Ionic, Phonegap ou Nativos: Android (Java ou Kotlin), IOS (Swift), arquitetura de software para desenvolvimento móvel, MQTT broker.

Benefícios: VR, VT, AM e AO - somente para opção CLT
Contratação: CLT ou PJ
Interessados: Enviar CV para talento@radarprofissional.com.br 
Local: Real Parque, Morumbi/SP

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
