### ISSUE TITLE
[SÃO PAULO] BACK-END DEVELOPER na Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#2169]
BACK END DEVELOPER SÊNIOR

Requisitos:  
•	Superior completo em Ciência da Computação, TI ou áreas relacionadas;
•	Experiência com programação orientada a objeto (modelagem, desenvolvimento e testes de aplicações JAVA);
•	Vivência com Spring Boot 2.x, JPA, Oracle, ferramentas de controle de código GIT, AWS, Redes e Ansible;
•	Experiência com aplicações utilizando Docker e com sistema Linux.
•	3 anos de experiência mínima 

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.
Local: São Paulo/SP – Zona Sul 
Interessados: Enviar CV para talento@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
