### ISSUE TITLE
[Remoto | Campinas/SP] Back-End Developer na NB8 Digital

### ISSUE THREAD

**Issue by rodrigohenrik** [backend-br/vagas#217]
## Descrição da vaga

# Desenvolvimento PHP utilizando WordPress e WooCommerce

## Local

* Totalmente remoto. (Bônus para Campinas/SP)

## Benefícios

* Flexibilidade de Horário / Home office

## Requisitos

* Obrigatórios:
   * HTML e CSS pleno
   * PHP com conhecimento em WordPress e WooCommerce

* Diferenciais:
   *  Conhecimentos em APIs
   *  Projetos opensource
   * desenvolvimento de plugins

## Contratação

* Freelancer PF
* PJ

## Nossa empresa

A NB8 é uma agência criativa digital, com foco na criação e desenvolvimento de portais de conteúdo e lojas virtuais com WordPress e WooCommerce.

## Como se candidatar

Por favor envie um email para **marco@nb8.digital com** seus conhecimentos, experiências, valor pretendido. Enviar no assunto: **Vaga WP**

## Labels

* Freelancer
* PJ
* Pleno
* Remoto - Total

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
