### ISSUE TITLE
[Metrô São Bento-SP] Programador .NET Core Pleno/Sênior em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#2170]
Programador .NET Core Pleno/Sênior 

Requisitos:
Desenvolvimento de sistemas em .NETCORE e CLOUD (AWS). Para participar de projetos para grande empresa.

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, vale alimentação, entre outros.

Local: São Paulo/SP – metrô São Bento.

Interessados: Enviar CV para ryokota@brq.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
