### ISSUE TITLE
[Catanduva] Back-End Developer na PERFORMA IT

### ISSUE THREAD

**Issue by TaliaCouto** [backend-br/vagas#2172]
## [Catanduva] Back-End Developer na PERFORMA IT
Estamos à procura de um desenvolvedor Back-End que seja apaixonado por novos desafios, com disposição de descobrir e aprender todos os dias; que contribua com o time; que atue com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso. 

## O que você vai fazer

Desenvolver a lógica server-side e a definição e a manutenção de bases de dados de aplicações Web garantindo alta performance de resposta às requests originadas no client-side.
Você também será responsável por integrar os elementos de front-end desenvolvido pelos seus colegas às regras da aplicação, por isso um conhecimento básico das tecnologias de front- end é um diferencial.

## Local
Escritório, Catanduva 

## Nós te oferecemos

- Jornada de Trabalho: 40h semanais
- Convênio Médico
- Vale Refeição
- Descanso Remunerado
- Bônus Anual 
- Horário flexível

## Aqui você...

- Vivenciará uma cultura de desenvolvimento, dinâmico, colaborativo, gestão horizontal e com um ótimo relacionamento entre colegas e clientes.
- Pode ser quem você é: piercing, tatoo, social ou despojado... tudo é super bem-vindo!
- Estará em um ambiente de trabalho descontraído e aconchegante - temos videogame e aquele momento para tomar um café e bater um papo.

## Suas principais responsabilidades

- Vivenciará uma cultura de desenvolvimento, dinâmico, colaborativo, gestão horizontal e com um ótimo relacionamento entre colegas e clientes.
- Pode ser quem você é: piercing, tatoo, social ou despojado... tudo é super bem-vindo!
- Estará em um ambiente de trabalho descontraído e aconchegante - temos videogame e aquele momento para tomar um café e bater um papo.

## Você precisa ter:

- Proficiente entendimento das ferramentas de versão de código, como Git
- Proficiência em desenvolvimento em tecnologias web server-side ASP.NET em C# (ASP.NET MVC Controllers / ASP.NET MVC Web API);
- Proficiência em linguagem de programação C#;
- Proficiência em banco de dados relacionais;
- Integração entre código de lógica de negócios e bases de dados;
- Capacidade de criação de estruturas de dados;
- Conhecimento em desenvolvimento de serviços Web WCF (REST e SOAP);
- Conhecimento em containers Docker

## Você vai se destacar se tiver:

- Desenvolvimento em ASP.NET Core 2/3 será considerado um diferencial
- Conhecimento em plataformas de Cloud (AWS/Azure/GCP)
- Conhecimento em Kubernetes
- Conhecimento em micro-serviços
- Familiaridade em Javascript/Typescript
- Conhecimento em ferramentas de teste automatizados (NUnit/XUnit)

## O que você pode aprender com a gente:

- Arquitetura de soluções
- Arquitetura serverless
- Elastic search
- Machine learning
- Big data

## Contratação
Cooperado a combinar

## Quem somos
A PerformaIT é uma empresa de tecnologia atenta as necessidades dos clientes e as novas tecnologias que surgem a todo momento. Acreditamos que nossos produtos e serviços devem ajudar nossos clientes a atingir uma meta, resolver um problema ou satisfazer uma necessidade.
Com uma busca incessante pela qualidade procuramos definir nossos processos de forma à atender aos principais modelos de mercado, porém sem perder a agilidade e a flexibilidade no atendimento as necessidades de nossos clientes. Nosso conhecimento, criatividade e estratégias diferenciadas são nossos pilares para o desenvolvimento de relações de longo prazo com todos nossos parceiros, colaboradores e clientes.

## ☺ Se identificou com a vaga?
Envie um e-mail para oportunidades@performait.com com seu CV anexado - Vaga Back-End Developer

#### Alocação
- Alocado
#### Regime
- Cooperativa

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
