### ISSUE TITLE
[São Paulo-SP] Back-End Developer na Ewally

### ISSUE THREAD

**Issue by hrsoul1221** [backend-br/vagas#2174]
A HRSoul foi criada visando atender as necessidades do mercado de TI, Telecom e Engenharia, suprindo a carência de consultorias com expertise na área, assim como inovar os processos de Recursos Humanos para os demais segmentos. Oferecemos oportunidades para consultores com os seguintes perfis:  

Desenvolvedores Back-End/Node.js
Níveis , Pleno e Sênior (4 vagas) – São Paulo/SP 
 
- Sólida experiência com Node.js, Metodologias Ágeis, Terminal, GIT, APIs;
- Desejáveis conhecimentos em Arquitetura de microsserviços e Serverless Nuvem, AWS, Bancos de Dados não-relacionais (DynamoDB), Bancos de Dados relacionais (MySQL), TDD;
- Imprescindível Nível de Inglês Intermediário;
- Graduação na área de TI;
-  Projeto por tempo indeterminado;
- Atuação na região da Avenida Paulista.

Os interessados deverão enviar o currículo atualizado informando pretensão salarial e disponibilidade para início, através do e-mail lpierrotti@hrsoul.com.br ou cadastre-se em nosso site hrsoul.com.br

Grato,

**Comment by hallss93** [comment]
possibilidade de remoto ou somente alocado?

**Comment by hrsoul1221** [comment]
Somente alocado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
