### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Pleno(a) Backend PHP / Node.js / React

### ISSUE THREAD

**Issue by sergiobr** [backend-br/vagas#2175]
Empresa: Vee Digital
Vaga: Desenvolvedor(a) Pleno(a) Backend PHP / Node.js / React
Tipo: CLT ou PJ
☛ Responsabilidades
⟹ Desenvolvimento e manutenção de aplicações web
⟹ Desenvolvimento e manutenção de aplicações mobile
⟹ Realizar a manutenção e criação de novas funcionalidades
⟹ Desenvolvimento de funcionalidades de backend web
⟹ Desenvolver e sustentar integrações
⟹ Estar atento(a) à novas tecnologias que podem ser usadas no desenvolvimento dos produtos da empresa, buscando e validando as inovações para aplicá-las em diferentes projetos e situações
⟹ Participar ativamente durante as fases de concepção de novos produtos e funcionalidades. Entendimento das regras de negócio, análise de requisitos, validação da viabilidade técnica e discussão com toda a equipe a fim de encontrar as mais efetivas soluções para cada situação
⟹ Colocar em prática as tecnologias e frameworks utilizados através da implementação de POCs e da participação na programação das funcionalidades
☛ Requisitos obrigatórios
⟹ Possuir ao menos 3 anos de experiência comprovada
⟹ Domínio sólido no desenvolvimento em linguagem PHP e o uso de frameworks Laravel e Lumen
⟹ Bom nível de entendimento no desenvolvimento React para Web
⟹ Bom domínio de modelagem e manipulação de bancos de dados Relacionais
⟹ Ferramentas de Integração/Entrega Contínua(CI/CD), Git, práticas de XP (SCRUM/Agile), testes TDD/BDD, OOP, Design Patterns, design de APIs e REST
⟹ Nível avançado de programação Javascript, HTML5 e CSS3
⟹ Domínio de inglês técnico para leitura
⟹ Disponibilidade de 8 horas diárias (dias úteis)
☛ Soft skills
⟹ Familiaridade com trabalho em equipe
⟹ Estar sempre aberto para evoluir profissionalmente, pesquisando, propondo e abraçando novas tecnologias que possam contribuir para a qualidade e eficiência de nossos produtos 
⟹ Comunicação tranquila e pacífica (todos aqui temos ótimas ideias e é necessário ouvir e respeitar cada uma delas)
☛ Desejável
⟹ Familiaridade com ambiente Linux e MacOS
⟹ Desenvolvimento de aplicações móveis (Android/iOS)
⟹ Experiência com meios de pagamento
☛ Diferenciais
⟹ Conhecimentos básicos de desenvolvimento JAVA EE
☛ O que oferecemos
⟹ VA / VR
⟹ Plano de Saúde
⟹ Total Pass (Academias)
⟹ Home office opcional 1x por semana
⟹ Rendimentos compatíveis com o mercado e a função

Enviar currículo ou Linkedin para contato@vee.digital com o assunto "DEVPLENO2020"

**Comment by viniciusrtf** [comment]
@sergiobr Para os candidatos seria interessante você informar o nome da empresa e como fazer para enviar o CV. Sucesso na seleção.

**Comment by sergiobr** [comment]
@viniciusrtf poxa eu me esqueci. muito obrigado.
Desculpe pessoal.
Dados da empresa e como se candidatar atualizados!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
