### ISSUE TITLE
[Rio de Janeiro] Backend Developer Pleno na Somos Educação

### ISSUE THREAD

**Issue by lucas-pitta** [backend-br/vagas#2176]
Olá!

Trabalhamos com o Plurall na Somos Educação. O Plurall é uma plataforma de ensino criada com o objetivo de simplificar e revolucionar a forma como as pessoas estudam e se relacionam com seus materiais escolares.

Estamos em busca de uma pessoa para assumir a posição de Desenvolvedor(a) Backend junior/pleno utilizando Ruby on Rails, o perfil que buscamos precisa ser pró-ativo e que busque sempre aprender e compartilhar coisas novas.

O time hoje se organiza em capítulos e squad, em um formato parecido como o implementado pelo spotify.

**Local**

- Escritório, Rio de Janeiro - Ao lado do metrô General Osório

**Forma de contratação**

- CLT

**Benefícios**

- Plano de Saúde Bradesco
- Plano Dental Odontoprev
- VR ou VA de R$ 25,31/dia
- VT
- Gympass
- Programa de remuneração variável
- Auxílio Creche (benefício exclusivo para colaboradoras)
- Possíbilidade de Home Office
- Ambiente descontraído e no dress code

**Requisitos**

- Ruby on Rails
- Sidekiq
- Redis
- Banco de dados Relacional
- Confortável com Ambiente Unix;

**Desejável**

- Experiência na realização de testes automatizados
- Elasticsearch
- Docker

**Responsábilidades e atribuições**

- Desenvolver e evoluir a plataforma do plurall.
- Colaborar com ideias que possam melhorar nossos sistemas e a vida dos nossos usuários;
- Estar disposto a aprender e a ensinar;
- Estar sempre atento às oportunidades para melhorar o código e os nossos processos.

**Um pouquinho mais sobre a gente**

https://www.linkedin.com/company/somoseducacao/
https://www.linkedin.com/company/plurall/
https://www.plurall.net/

**Link da Vaga**

https://somoseducacao.revelo.com.br/openings/desenvolvedor-ruby-99638476-6c2b-4b0f-b0b3-fb2b4e3ccaeb?application_source=shared

**Comment by andreealencar** [comment]
Aceita completamente remoto?

**Comment by lucas-pitta** [comment]
Infelizmente não @andreealencar :(

**Comment by lucas-pitta** [comment]
Ainda buscando alguem para essa posição

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
