### ISSUE TITLE
[SÃO PAULO] Backend Eng looking to become a DevOps Engineer [SumUp]

### ISSUE THREAD

**Issue by matheus-dias-sumup** [backend-br/vagas#2177]
If you are  a Senior Backend Dev looking to become a DevOps Engineer (SRE) check bellow.

We will give you all the training, career advice you need, and any other help you need to be a Devops Eng.

If yout have:
Good experience with Linux and some of its distributions;
Fluent English;
5+ years of experience with Software Engineering:
Backend programming languages;
Cloud computing;
Design Patterns;
Aplly here: https://grnh.se/2d2dd8b12

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
