### ISSUE TITLE
[Belo Horizonte] Back-end Developer na Queima Diária

### ISSUE THREAD

**Issue by JohnCosta56** [backend-br/vagas#2178]
## Descrição da vaga

Node Developer na Queima Diária. 

## Local

Escritório, Belo Horizonte - Buritis

## Benefícios

- Vale Refeição ou Alimentação;
- Vale Transporte;
- Plano de Saúde;
- Plano odontológico;
- Lanche diário;
- Frutas à disposição;
- Ajuda de custo para aulas de inglês (in company);
- Acesso a programas Queima Diária <3;
- Acesso ao clube de vantagens da plataforma;
- No dress code (pode trabalhar com a roupa que quiser);
- Ambiente descontraído e motivador;
- Confraternizações frequentes na empresa.

## Requisitos

**Obrigatórios:**
- Experiência e expertise em Javascript, especialmente em NodeJs;
- Conhecimento em AWS;

**Desejáveis:**
- Conhecimento nos frameworks: Express e Loopback;
- Conhecimento em PostgresSQL;
- Experiência na escolha e aplicação de boas práticas de software como Test Driven Development (TDD), integração e entrega contínua.

## Contratação

CLT

## Nossa empresa

Somos uma startup inovadora e com crescimento a todo vapor! Visamos ajudar as pessoas a se tornarem aquilo que desejam ser através de uma vida mais saudável, harmoniosa e cheia de autoestima. Para isto acontecer, temos a maior e mais inovadora plataforma online do Brasil dedicada à atividade física e ao bem-estar.

Nosso time é um mix de excelência, trabalho em equipe e muuuita paixão! Por isso, buscamos profissionais que não só entreguem resultado, mas que chamem a responsabilidade do negócio para si, que tenham sede de crescimento, que sejam gestores do próprio processo e com a capacidade de criar relações abertas através da transparência. Fez sentido para você? Então vem fazer parte!

## Como se candidatar

https://queimadiaria.recruiterbox.com/jobs/fk0jqa2/

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by tiago123456789** [comment]
Há possibilidade de remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
