### ISSUE TITLE
[Bauru-SP] Analista Desenvolvedor JAVA (RPA) na Yank Solutions

### ISSUE THREAD

**Issue by oliviaaversa** [backend-br/vagas#2179]
A Yank Solutions está com oportunidade para:

Analista Desenvolvedor JAVA

ATIVIDADES:
-Desenvolver automações (RPA) em Java;
-Elaborar documentações técnicas e funcionais;
-Integrar com WebServices SOAP/Restful;
-Homologar automações com cliente final.

REQUISITOS:
-Experiência com Desenvolvimento de Software;
-Ensino superior cursando;
-Disponibilidade para atuar em horário comercial;
-Disponibilidade para viagens.

LOCALIDADE: Bauru-SP

Cadastre seu currículo na aba “carreiras” em nosso site: https://www.yanksolutions.com.br/

Vaga também disponível para pessoas com deficiência. ♿

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
