### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na FGV DAPP

### ISSUE THREAD

**Issue by cmarqs** [backend-br/vagas#218]
### Descrição da Vaga
Atuar com a manutenção e desenvolvimento de APIs, serviços, web applications. Criar estrutura de banco de dados, otimizar consultas em queries utilizando boas práticas de uso de recursos.
Estamos procurando um profissional que tenha capacidade técnica e analítica, com capacidade de implementar boas práticas e sugerir melhorias, com espírito de equipe e aprendizado contínuo. 

*Necessário*
Linux (Ubuntu / CentOS) 
Git / GitFlow
Python Flask, SQLAlchemy, Migrations
Banco de Dados Postgre ou MySQL

*Desejável*
Noção de redes (NGINX/Haproxy/Firewall) 
Rotinas de backup
Documentação de sistemas

*Diferencial*
PHP (WordPress) HTML CSS Javascript

### Local
Escritório DAPP FGV, Rio de Janeiro - Botafogo

### Contratação
 - A combinar (PJ ou CLT)

### Benefícios
1 – Refeição no local (desconto de 0,15% do salário por dia de utilização);
2 – Cheque alimentação no valor de R$160,00 (concedido ao funcionário que percebe o salário de até R$5.307,87)
3 – Auxílio-Creche no valor de até R$641,00 (para empregados com filhos de até 7 anos);
4 – Auxílio Funeral (concedido no caso do falecimento do funcionário e de seus familiares – pais, cônjuge e filhos) – valor do reembolso de até R$2000,00;
5 – Auxílio Filho Excepcional no valor de R$1347,14 (concedido aos funcionários com filhos com necessidades especiais, comprovada com laudo médico);
6 – Bolsas de 100% em cursos do CADEMP (após 3 meses na empresa), em MBA (após 1 ano) e curso de inglês online (pelo período de 1 ano). As bolsas para os cursos do CADEMP e do MBA dependem da abertura do curso e da concessão de bolsa para aquele período.
7 – Acesso a livraria;
8 – Assistência Médica (Amil);
9 – Assistência Odontológica (Inpao);
10 – Vale Transporte;
11 – ASFGV;
12 – PREVI.
 
*Diferenciais*
 - Ambiente dinâmico e interdisciplinar e muito colaborativo, ideal pra quem quer desafios e se desenvolver.

###Quem somos
A DAPP produz análises de políticas públicas com uma equipe interdisciplinar e diversificada, de sólida formação em áreas como Sociologia, Ciência Política, Antropologia, Linguística, Economia, Administração Pública, Relações Internacionais, Estatística, Matemática, Filosofia e Comunicação Social, aliadas às áreas de Tecnologia da Informação e Design.

Desenvolvemos pesquisa social aplicada com o objetivo de promover a inovação para políticas públicas,
produzindo análises qualificadas e disponibilizando diversas ferramentas de visualização e análise de dados. Nossas metodologias de pesquisa reúnem métodos quantitativos e qualitativos em integração com a análise de redes sociais e interface com áreas de tecnologia e design.

### Como se candidatar
Por favor envie um e-mail para cleiton.marques@fgv.br com seu CV anexado, forma de contratação preferencial com pretensão salarial - enviar no assunto: Vaga Back-End.

### Labels
 - Alocado
 - CLT
 - PJ
 - Pleno
 - Senior

**Comment by cmarqs** [comment]
Ninguém? :(

**Comment by tiglinux** [comment]
euu :)

**Comment by reginaldojunior** [comment]
@cpmarx tá dificil arrumar dev brô. Os melhores já estão trabalhando, temos que ajudar esses que estão começando com bastante curso e conteudo para virarem devs em um futuro próximo.

**Comment by tiglinux** [comment]
euu :)

**Comment by cmarqs** [comment]
Fala aí @reginaldojunior vc tem razão cara... normalmente eu curto o cara desenvolver junto com a equipe, aqui é um lugar bom pra isso... mas nesse momento precisa ser um dev boladão já mesmo. Vou deixar só mais um tempo, qq coisa eu fecho semana q vem.

**Comment by cmarqs** [comment]
@tiglinux manda aí seu CV pra mim cara! Vlw

**Comment by cmarqs** [comment]
Atualizado com os benefícios

**Comment by cmarqs** [comment]
Processo de admissão em andamento. Obrigado pessoal!
