### ISSUE TITLE
[Trabalho Remoto] Desenvolvedor Backend Node.JS Sênior na Influu

### ISSUE THREAD

**Issue by influu** [backend-br/vagas#2181]
## Descrição da vaga
Estamos em busca de um desenvolvedor backend REMOTO para trabalhar em uma migração de um projeto APIrest em Laravel para NODEJS

## Local
Remoto ou Escritório, São Paulo

**Obrigatórios:**
- +2 anos de experiência com NodeJS
- GraphQL
- Nível avançado de programação Javascript

**Infraestrutura:**
AWS (EC2, Elastic Beanstalk, Lambda, RDS, S3, SES, SQS, SNS, Route 53, Api Gateway)
Docker

**Desejáveis:**
- TDD

## Contratação
PJ a combinar

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_Node20] + Nome_Sobrenome

## Labels
- PJ
- Pleno
- Remoto
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
