### ISSUE TITLE
[São Paulo-Alphaville] Desenvolvedor Java Senior - Mazzatech

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2185]
Sobre a empresa: 
Profissional será contratado pela Mazzatech para atuar alocado em uma empresa que desenvolve soluções para Fintechs.

Descrição: O que você irá fazer?
Integrará equipe de desenvolvimento de soluções web, baseadas em Java, para Fintechs.

As habilidades necessárias:
Spring (boot/batch/rest/security/MVC), arquitetura de microservices, JPA, Hibernate, RabbitMQ, DDD, SOLID, Unit Test, Conceito de teste de integração, SQL, MongoDB, API Rest, clean code.
Conhecimento Kotlin assim como AWS é um diferencial já que estamos atuando em alguns projetos.

Você gostará de trabalhar aqui se:
Gosta de um ambiente descontraído, de atuar com autonomia, em ambiente ágil.
A empresa tem salas de descompressão, com jogos.
A empresa também disponibiliza para os funcionários Café da Manhã, Almoço e Café da Tarde.

Interessados, encaminhar curriculo com pretensão salarial para taiane@mazza.tech.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
