### ISSUE TITLE
[Jaguariuna] Desenvolvedor BackEnd Sr - Maior projeto de SAP do Mundo - Mazzatech

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2186]
Sobre a empresa: 
Profissional será contratado pela Mazzatech para atuar alocado em uma multinacional do ramo de bebidas.

Descrição: O que você irá fazer?
Profissional integrará equipe de desenvolvimento, composta por especialistas em várias linguagens backend que participarão de projeto de cerca de 5 anos de duração, voltado para uma nova implantação da plataforma SAP na empresa. O projeto começará pelo Brasil e será implantado em todos os escritórios do mundo.

As habilidades necessárias:
Necessário grande experiência com desenvolvimento, em alguma linguagem para backend (Java, Python, Hana...).
Inglês avançado.
Interesse em atuar com plataforma SAP.

Você gostará de trabalhar aqui se:
Gosta de desafios, de atuar em projetos com grande complexidade e exposição.
Se deseja no futuro desenvolver carreira no exterior.
Se deseja atuar em empresa multinacional, porém com cara de startup.
Se é fã de cerveja =)

Interessados, encaminhar currículo com pretensão salarial para taiane@mazza.tech.

**Comment by rodrigocardosodev** [comment]
Aceita remoto?

**Comment by taianeuchoac** [comment]
Ola!

Não aceita infelizmente, apenas trabalho presencial.

Obrigada!


Taiane Uchoa
ANALISTA DE RH

taiane@mazza.tech <leoraposo@mazza.tech>
011 2532.2992 <http://mazza.tech/assinatura/2020/11%2025322992> / 97569.0652
skype: taiane.uchoa
[image: Site] <http://www.mazza.tech/>
[image: Localização] <http://www.mazza.tech/>


Em seg., 2 de mar. de 2020 às 11:46, Rodrigo Cardoso <
notifications@github.com> escreveu:

**Comment by maximilianocatarino** [comment]
@taianeuchoac aceitam candidatos de outros estados?

**Comment by taianeuchoac** [comment]
Ola!

Sim, aceitamos profissionais de outros estados. =)


Taiane Uchoa
ANALISTA DE RH

taiane@mazza.tech <leoraposo@mazza.tech>
011 2532.2992 <http://mazza.tech/assinatura/2020/11%2025322992> / 97569.0652
skype: taiane.uchoa
[image: Site] <http://www.mazza.tech/>
[image: Localização] <http://www.mazza.tech/>


Em qui., 2 de abr. de 2020 às 12:50, maximilianocatarino <
notifications@github.com> escreveu:
