### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Backend PHP Laravel na Ensinio

### ISSUE THREAD

**Issue by guiavila** [backend-br/vagas#2188]
Desenvolvedor Backend PHP Laravel na Ensinio (BH)

Obs 1: Trabalho presencial, mas será remoto temporariamente até maio ou junho de 2020.
Obs 2: Apenas desenvolvedores de nível "Pleno Avançado" ou superior. Não estamos contratando desenvolvedores júniors.

## Descrição da Vaga

Procuramos desenvolvedores especialistas no framework Laravel (PHP) para integrar o time de desenvolvimento do Backend da Ensinio. Nossa plataforma oferece soluções de ecommerce e recursos avançados de Cursos Online e ensinio à distância, para empresas e empreendedores dos mais diversos nichos. Nós oferecemos a plataforma perfeita para quem quer ensinar e vender online, e queremos ter você nesse time!

Procuramos pessoas competentes e pontos fora da curva que querem crescer junto com a Ensinio. Veja se você atende a esses 5 pontos:

1. Tenha experiência com Backend;
2. Tenha experiência com Laravel;
3. Goste de soluções online para Educação;
4. Goste de fazer parte de um time que cria produtos que revolucionam e quebram paradigmas;
5. É competente e está sempre estudando, aprendendo e se aperfeiçoando.

Se sim, vem com a gente. Nos preocupamos com o que você entrega e não como você se veste! Seja bem vindo à Ensinio :)

## Sobre a Ensinio

Pequena descrição sobre o que é a Ensinio:

A Ensinio é uma solução completa para quem precisa vender e ensinar online. Você vai ter sua  própria plataforma para vender produtos digitais e físicos, criar cursos e construir sua própria Escola  Online com um sistema EAD completo. A plataforma é inteiramente customizável e você vai ter uma rede social e comunidade de  usuários interagindo com seus conteúdos em uma plataforma gamificada, com centenas de recursos  avançados para garantir a melhor experiência de navegação, compra e aprendizado.

## Local

Escritório em Belo Horizonte - MG
Obs: Trabalho presencial, mas será remoto temporariamente até maio ou junho de 2020.

## Requisitos fundamentais

- Experiência em Desenvolvimento Web;
- Conhecimento avançado em PHP;
- Conhecimento avançado de Laravel;
- Conhecimento de Laravel Passaport;
- Experiência comprovada de trabalho com Laravel;
- Conhecimento de Vue.js (painel do "Laravel Nova" utiliza Vue.js).

## Seria fantástico se em seu background tivesse

- Conhecimento do "Laravel Nova";
- Conhecimento de Laravel Tenancy;
- Habilidade de escrever e falar em Inglês.

## Contratação

PJ a combinar

## Benefícios

- Você tem voz. Os fundadores ouvem todas as pessoas. Sua opinião será levada em consideração.
- Perspectiva de crescimento;
- Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
- Contato com novas tecnologias de mercado;
- Ingressos para Congressos/Convenções de Tecnologia e Programação;
- Férias anuais;
- Feriados;
- Flexibilidade de horários;
- Trabalhar remoto nas sextas feiras;
- Lanches na empresa;
- Cafés, bebidas e snacks.

## Como se candidatar

Seja bem vindo à Ensinio! Para entrar no time de desenvolvimento da Ensinio, envie seu CV para jobs@ensinio.com com pretensão salarial e seu perfil profissional. Nos conte mais detalhes sobre você e o motivo pelo qual você quer esta vaga. Nós queremos conhecer mais do seu background, das suas habilidades e das suas perspectivas futuras. Vamos construir um produto incrível juntos! Envie sua mensagem com o assunto: "Vaga - Backend Laravel" e vamos responder em até 5 dias úteis.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
