### ISSUE TITLE
[Porto Alegre] Dev Java - SOUTH SYSTEM

### ISSUE THREAD

**Issue by cmazoni** [backend-br/vagas#2189]
## Descrição da vaga

Oportunidade de atuação em um de nossos clientes do setor financeiro. Atuação com metodologias ágeis e tecnologias de ponta.

## Local

Presencial na Zona Norte de Porto Alegre.

## Benefícios

- Material Dell de ótima qualidade
- Ótima localização
- Acompanhamentos e feedbacks com os profissionais
- Cursos e treinamentos para impulsionar o seu desenvolvimento!

## Requisitos

Obrigatórios
- Desenvolvimento Java e capacidade de aprender outras linguagens de programação correntes do mercado;
- Programação concorrente / multi-threaded; 
- Familiaridade com automação de testes;
- Desenvolvimento de web services e APIs (JSON ou XML sobre HTTP);
- Banco de dados (tanto relacional quanto NoSQL);
- Infraestrutura AWS;
- Práticas ágeis (Scrum / XP / etc) e familiaridade com conceitos 'lean';
- Conhecimentos de criptografia;
- Conhecimentos de segurança da informação;
- Conhecimentos técnicos e de negócio de cartões de crédito e débito.

Diferenciais
- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação

PJ ou cooperado

## Nossa empresa

A SOUTH SYSTEM atua hoje principalmente no setor financeiro, desenvolvendo as melhores soluções para atender às demandas de seus clientes. Focamos muito no desenvolvimento de nossos profissionais, oferecendo cursos e treinamentos para impulsionar seu desenvolvimento!

## Como se candidatar

Envie um e-mail com o teu currículo para claudia.mazoni@southsystem.com.br com a vaga no assunto e vamos marcar um café!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
