### ISSUE TITLE
[Florianópolis - SC] PHP Back-End Developer na Compufácil

### ISSUE THREAD

**Issue by euclecio** [backend-br/vagas#219]
### Função
Trabalhar junto da equipe na manutenção e implementação de novas funcionalidades/atualizações na API e no sistema da Compufácil. Assim como participar das decisões de tecnologia, dos eventos de inovação da empresa e das decisões em equipe.

### Requisitos
- Conhecimentos em PHP e Orientação a Objetos
- Conhecimentos em banco de dados (MySQL, PostgreSQL)
- Conhecimentos em Git
- Conhecimento com algum framework como Zend Framework 2, Laravel, Silex ou similar
- Inglês técnico ao menos para leitura
- Interesse em aprender novas tecnologias, linguagens de programação e ambientes de desenvolvimento
- Morar ou estar disposto a se mudar para Florianópolis

### Requisitos adicionais

- Experiência com containers (Docker)
- Experiência com Rest API
- Conhecimentos em ORM (entidades, relacionamentos, DQL). Como Doctrine 2, por exemplo
- Conhecimentos em testes unitários
- Conhecimento sobre Cloud Computing (IaaS, PaaS e SaaS)
- Experiência com DevOps

### Perfil esperado

- Disciplina e organização é fundamental;
- Sedento por conhecimento;
- Traz críticas em relação a ferramentas utilizadas, com o objetivo de melhorar o desenvolvimento;
- Pesquisador nas horas vagas, trazendo novidades que podem ser realmente aplicadas nos projetos;
- Senso crítico;
- Engajamento com a equipe, para crescimento sustentável de todos.

### O que oferecemos
- Contrato CLT com salário compatível com a experiência
- Vale Alimentação
- Contratação Imediata
- Oportunidade de trabalhar em um projeto com tecnologias inovadoras
- Incentivos para participar de eventos/cursos/treinamentos

### Local
Ambiente descontraído e inovador do **Impact Hub Coworking** que fica localizado no **Centro de Inovação ACATE**

Se você atende os requisitos acima mande um e-mail com seu currículo e conta do Github para admin@compufacil.com.br

**Comment by guilhermeoa07** [comment]
Possibilidade de entrevista via Skype ou hangouts?

**Comment by fsrocha-dev** [comment]
Ainda está aberta a vaga ?

**Comment by euclecio** [comment]
@guilhermeoa07 @fsrocha-dev já foi preenchida, mandem currículo que é provável que abriremos outra vaga. A entrevista é de forma remota mesmo, hangouts ou appear.

**Comment by euclecio** [comment]
Preenchida
