### ISSUE TITLE
Vaga para Análise e Programação em Barueri -SP

### ISSUE THREAD

**Issue by CarolPimentel** [backend-br/vagas#2192]
Empresa de Tecnologia da Informação contrata Analista em Programação Júnior para Barueri -SP

Nível: Júnior
Função:
Acompanhar estudos quantitativos, converter dados em informação através de análises e painéis;
Automatizar processos para auxílio das análises e elaborações de indicadores gerenciais, planilhas e sistemas de custos para controle das demandas de áreas correlatas; 
Manipulação em bancos, através de extrações e tratamento das bases;
Desenvolver em SQL e VBA, manipulando para a geração de análises em BI.

Requisitos: 
Experiência em manipulação de banco de dados robusto;
Desenvolvimento de comandos, para extrações e conversão dos dados em informação;
Ter conhecimento intermediário em SQL Server, VBA e Power Bi. 
Conhecimentos em SAS e Python serão um diferencial. 

Ensino Superior em Análise de Sistemas, Sistemas de Informação, Engenharia da Computação,  Análise em Banco de Dados e afins.
Benefícios: Assistência Médica Bradesco Saúde, Assistência Odontológica Bradesco Saúde, Combustível/VT/Fretado, Vale Refeição, Seguro de Vida;
Regime de contratação: CLT (Efetivo)
Horário: De segunda a sexta, das 8:00 às 17:00.
Local: Barueri

Os interessados deverão encaminhar o currículo com a pretensão salarial para recursos3008@gmail.com

Boa sorte!

**Comment by rodrigocardosodev** [comment]
A vaga é remota?

**Comment by CarolPimentel** [comment]
Nao, é presencial.

Bom dia.

Att

Em seg, 2 de mar de 2020 11:44, Rodrigo Cardoso <notifications@github.com>
escreveu:
