### ISSUE TITLE
[São Paulo] Back-End Developer na Fhinck

### ISSUE THREAD

**Issue by michelzf** [backend-br/vagas#2193]
### Backend Archmage

O Backend Archmage deve realizar a manutenção e suporte de nossa infraestrutura utilizando todo o seu conhecimento de feitiços em nuvem. Em nosso ambiente trafega diariamente _1,2 bilhão_ de datapoints por dia, e nossas bases de dados armazenam terabytes de informação. 
Atualmente nosso ambiente está todo localizado na **GCP** (Google Cloud Platform), e utilizamos as tecnologias mais recentes para **big data**, como: Cloud Storage, Cloud Functions e Google BigQuery.
Além do desenvolvimento de novas funcionalidades para o backend (desenvolvido em NodeJS), o Archmage deverá trazer melhorias relacionadas a infraestrutura, rede e segurança do ambiente, então prepare toda a sua magia arcana para esse desafio. 

**Pré-requisitos:**
 - NodeJS (Experiência de 3 anos ou mais).
 - Plataformas em nuvem (experiência em GCP, Azure ou AWS).
 - Experiência com metodologias de desenvolvimento e tecnologias GIT.
 - PHP.
 - Banco de dados (Oracle,MySQL ou MongoDB).
 - Serverless.
 
**Conhecimentos complementares:**
 - Docker, Kubernetes.
 - Gerenciadores de fila (Kafka, RabbitMQ).
 - FaaS (Cloud Functions, Azure Functions e AWS Lambda).
 - Python.

**Outras informações:**
 - Tipo de contratação: PJ.
 - Endereço: Cubo Itaú - Alameda Vicente Pinzon, 54 - Vila Olímpia, São Paulo - SP, 04547-130 

**Um pouco sobre a Fhinck:**

Em 2019 a Fhinck foi escolhida pelas grandes empresas pelo segundo ano consecutivo a Melhor Startup de Produtividade do Brasil, eleita uma das 100 Startups to Watch pela Época, Valor e PEGN e no final do de ano foi eleita a melhor empresa de tecnologia pelos Centros de Serviços Compartilhados das maiores empresas do Brasil.

Somos **Data Maniacs**, usamos ciência de dados embarcada no nosso software que fica instalado nos computadores, para identificar automaticamente oportunidades de melhoria contínua de processos nas grandes empresas que entende comportamento de navegação e tempos e movimentos dos times e sugere onde padronizar, automatizar/robotizar e até mesmo eliminar atividades que não fazem sentido (pois existe uma forma melhor de fazer).

Somos poucos e bons, com apenas 18 profissionais absurdamente competentes e apaixonados pelo que fazem e principalmente com o que vamos alcançar, temos clientes em mais 10 países e crescendo organicamente (queremos atender o mundo todo com um super time de apenas 38 fhinckers), nossos clientes são de peso global de todas as indústrias como Coca-Cola, Unilever, Santander, Porto Seguro, DHL, Accenture, Deloitte, TOTVS, Kroton, Natura... E tudo isso sem nunca ter pego investimento de fundos de Venture Capital. A Fhinck cresceu incrivelmente em receita recorrente +500% nos últimos 12 meses e tudo isso sem ter um time de vendas, estamos localizados no maior ecossistema de Startups da América Latina CUBO em SP e temos como meta ser uma empresa orgulhosamente brasileira de alta tecnologia reconhecida no mundo todo pelas grandes empresas.

Ficou Interessado? Nos envie um email com o título **[São Paulo] Back-End Developer na Fhinck** e seu currículo para o email jobs_is_alive@fhinck.com e boa sorte.

_E que a força esteja com você!_

**Comment by maximilianocatarino** [comment]
Olá @michelzf, aceitam candidatos de outros estados?
