### ISSUE TITLE
[São José dos Campos] DESENVOLVEDOR ANDROID JÚNIOR [GSW]

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#2194]
**Descrição da vaga**
Conhecimentos obrigatórios: Java, orientação objeto.
Conhecimento desejado: Desenvolvimento mobile ANDROID

**Local**
São José dos Campos

**Contratação**
CLT + Benefícios

**Como se candidatar**
Por favor, envie um e-mail para mariana.bompean@gsw.com.br com seu CV anexado e pretensão salarial.
Enviar no assunto: Vaga Júnior Android

### **Venham fazer parte de nossa equipe!!**

**Comment by EderNorivalSouza** [comment]
Mariana, sou de Santo André se aceitar estágio, tenho conhecimentos em Java orientado a objetos, SQL server, me avise que envio meu CV.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
