### ISSUE TITLE
[SÃO PAULO] Desenvolvedor(a) Back-End no [TRUCKPAD]

### ISSUE THREAD

**Issue by Tech-TruckPad** [backend-br/vagas#2195]
![alt text](https://i.postimg.cc/fL81fz38/truckpad-revolu-o-da-log-stica-vagas-1.png
 "Candidate-se!")

# O TruckPad

Estamos revolucionando a logística através da tecnologia. 

Nosso propósito é facilitar a vida de embarcadores, transportadoras e principalmente de caminhoneiros, os principais responsáveis por movimentar a economia do país e ao mesmo tempo, o elo mais sensível do ecossistema logístico brasileiro.

![alt text](https://i.postimg.cc/wTQsWmtJ/vagastech3.gif
 "Amazing!")

 ## Buscamos pessoas com:

- Experiência em modelagem de dados e utilização de bancos de dados relacionais e NoSQL;
- Conhecimentos de estruturas de dados e algoritmos;
- Experiência no desenvolvimento de sistemas web na plataforma Linux;
- Conhecimento em REST, Git, MySQL, Redis, Memcached, HTML, CSS, Java etc;
- Experiência com APIs REST;
- Conhecimento de metodologias ágeis - SCRUM, Kanban, XP etc;
- Domínio do protocolo HTTP/HTTPS, headers CORS, HTTP status codes;
- Experiência com desenvolvimento colaborativo - submissão, revisão e aplicação de patches;
- Conhecimento em Phyton e MongoDB será considerado diferencial.

## No dia a dia você vai:

- Atuar com foco em desenvolvimento de bancos de dados;
- Fará parte da equipe de desenvolvedores back-end criando modelos, funcionalidades e interfaces de APIs;
- Focar no usuário e na melhoria contínua do código de maneira a desenvolver um produto com as melhores práticas de mercado; 
- Executar a manutenção de rotina fazendo eventuais correções necessárias com o objetivo de atender às necessidades dos usuários; 
- Desenvolver trabalhos de codificação, depuração e testes nas soluções a serem desenvolvidas; 
- Trabalhará de forma integrada com o time de front-end para buscar sempre as melhores soluções com foco no valor entregue aos usuários.

# No TruckPad você encontrará:

- Ambiente descontraído, grandes desafios, muita autonomia para realizar as tarefas, oportunidade de crescimento, feedbacks e 1:1's;
- Pessoas curiosas, objetivas, inteligentes, que sonham grande e são abertas ao novo;
- Valorização do aprendizado constante através da educação. Por isso, oferecemos o auxílio desenvolvimento para utilizar em cursos técnicos e de línguas, universidades, eventos, palestras e compra de livros;
- Um bom pacote de remuneração e benefícios com: Vale-refeição e/ou alimentação (R$33/dia); Vale transporte; Vestiário com chuveiro;  Plano de saúde; Plano odontológico; Seguro de vida; Licença maternidade e paternidade; Auxílio creche;
- Massagem semanal; Mesa com café, chá, snacks e frutas da estação (o dia todo);
- Cerveja após às 18h00 (Todos os dias);
- No Dress code (vista-se e venha trabalhar à vontade).

Essa vaga tem a sua cara e foi feita para você? **VemSerTruckPader  ;)**

# Candidate-se agora!

**- Pela página de Carreiras:** http://bit.ly/2Pw9IuD **(Upload em PDF disponível)**

# Labels

- **Regime:** CLT
- **Nível:** Pleno e Senior
- **Linguagens:**  SQL (focado em dados); MongoDB (diferencial);  Relacionado: PHP, Java, Ruby

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
