### ISSUE TITLE
Especialista em Java

### ISSUE THREAD

**Issue by Daniela1986** [backend-br/vagas#2196]
Empresa multinacional europeia, presente no Brasil desde 2016, atuando como prestadora de serviços financeiros e tecnológicos.  
Posição em aberto: Especialista JAVA BACK-END  
(A área de tecnologia trabalha com conceito de times autônomos que possuem missões próprias (alinhadas a estratégia da empresa) e cuidam de todo o ciclo de desenvolvimento dos produtos, desde a concepção, à implementação e operação dos sistemas.  
Time multidisciplinar: uso de diferentes linguagens de programação (Java, Ruby, NodeJS, Go, JavaScript, CoffeeScript). Perfil inovador, dinâmico, apaixonado por novas tecnologias e fora da caixa. Inglês no mínimo avançado é requisito obrigatório  
BACK END  
Linguagem Java Framework Spring (MVC, Boot, Data, Security, Cloud) Programação orientada a objetos, código limpo e padrões de projetos Desenvolvimento orientado a testes (TDD) Experiência com micro serviços e a respectivas boas práticas. Banco de Dados Postgr, MySQL, MongoDB, Redis Metodologias ágeis: Scrum e Kanban Controle de versão: TFS, GIT (Fork, GitFlow) Containers (Docker) Arquitetura baseada em (Micro) Serviços  
Diferenciais: Filas(RabbitMQ, ApacheMQ, Kafka) Framework Javascript Node.js Ambiente em nuvem AWS, Azure, Google Cloud Containers (Kubernetes) Elastic Search Integração contínua  
Descrição das atividades:  
Manutenção e desenvolvimento de novas funcionalidades e melhorias nos sistemas Documentação completa de sistemas Testes de performance, carga e utilização de sistemas de formas manual e automatizada  
Desenvolver modelo de dados necessários para o desenvolvimento de sistemas Separação de responsabilidades de uma arquitetura baseada em Servios Comunicação assíncrona utilizando filas (RabbitMQ, ActiveMQ) TDD, BDD, Testes de integração, Integração contínua  
Monitoramento com sistemas terceiros (adquirentes, antifraude, bancos, etc.) Criação de uma PI Restful com conceitos de HATEOS Entrega contínua  
Formação acadêmica na área de tecnologia e afins Encaminhar cv em INGLÊS e PORTUGUÊS, mencionando pretensão salarial.  
 
Local de trabalho: São Paulo, Capital. Região da Faria Lima 
Email: renata.99hunters@yahoo.com Celular / Whatsapp: (16) 98137.1730

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
