### ISSUE TITLE
[SÃO PAULO] Desenvolvedor(a) Full-Stack PL no [TRUCKPAD]

### ISSUE THREAD

**Issue by Tech-TruckPad** [backend-br/vagas#2197]
![alt text](https://i.postimg.cc/fL81fz38/truckpad-revolu-o-da-log-stica-vagas-1.png
 "Candidate-se!")

# O TruckPad

Estamos revolucionando a logística através da tecnologia. 

Nosso propósito é facilitar a vida de embarcadores, transportadoras e principalmente de caminhoneiros, os principais responsáveis por movimentar a economia do país e ao mesmo tempo, o elo mais sensível do ecossistema logístico brasileiro.

![alt text](https://i.postimg.cc/wTQsWmtJ/vagastech3.gif
 "Amazing!")

 ## Buscamos pessoas com:

- Experiência no desenvolvimento de sistemas web na plataforma Linux;
- Conhecimentos em java script, html e css e Reacty.js;
- Experiência com APIs REST;
- Conhecimentos de estruturas de dados e algoritmos;
- Conhecimentos em modelagem de dados e utilização de bancos de dados relacionais e NoSQL;
- Experiência com desenvolvimento colaborativo - submissão, revisão e aplicação de patches;
- Domínio do protocolo HTTP/HTTPS, headers CORS, HTTP status codes;
- Conhecimento em REST, Git, MySQL, Redis, Memcached, HTML, CSS, JavaScript, etc;
- Conhecimento de metodologias ágeis - SCRUM, Kanban, XP etc.

## No dia a dia você vai:

- Interação contínua com a equipe de UI/UX;
- Desenvolvimento de layouts responsivos (mobile first);
- Utilização de frameworks que sejam aderentes ao paradigma SPA, como ReactJS ou VueJS;
- Criação e manutenção de componentes visuais reutilizáveis;
- Criação e manutenção de testes automatizados;
- Integração com back-end baseado em APIs REST. 

# No TruckPad você encontrará:

- Ambiente descontraído, grandes desafios, muita autonomia para realizar as tarefas, oportunidade de crescimento, feedbacks e 1:1's;
- Pessoas curiosas, objetivas, inteligentes, que sonham grande e são abertas ao novo;
- Valorização do aprendizado constante através da educação. Por isso, oferecemos o auxílio desenvolvimento para utilizar em cursos técnicos e de línguas, universidades, eventos, palestras e compra de livros;
- Um bom pacote de remuneração e benefícios com: Vale-refeição e/ou alimentação (R$33/dia); Vale transporte; Vestiário com chuveiro;  Plano de saúde; Plano odontológico; Seguro de vida; Licença maternidade e paternidade; Auxílio creche;
- Massagem semanal; Mesa com café, chá, snacks e frutas da estação (o dia todo);
- Cerveja após às 18h00 (Todos os dias);
- No Dress code (vista-se e venha trabalhar à vontade).

Essa vaga tem a sua cara e foi feita para você? **VemSerTruckPader  ;)**

# Candidate-se agora!

**- Pela página de Carreiras:** http://bit.ly/2I46Dhj **(Upload em PDF disponível)**

# Labels

- **Regime:** CLT
- **Nível:** Pleno
- **Linguagens:**  Java Script, HTML, CSS, Reacty.js, PHP, Java e Ruby

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
