### ISSUE TITLE
[Remoto, Floripa, Joinville, ou São Paulo] Senior Software Engineer, International Team - Resultados Digitais

### ISSUE THREAD

**Issue by kaiofelipejs** [backend-br/vagas#2198]
## Descrição da vaga
Você fará parte do time responsável pela **construção de um produto global**, que vai ajudar milhares de clientes a crescerem seus negócios!
Você será uma das pessoas responsáveis pela definição de uma arquitetura de internacionalização (tudo que esteja relacionado a tradução e gloabalização) para podermos explorar outras regiões utilizando os idiomas inglês e espanhol. Isso inclui: melhorar a consistência de timezone, assim como possibilitar a configuração de formato de data e hora, números, moeda e tudo mais.

Hoje nós temos clientes em mais de 30 países e, por isso os projetos são bem desafiadores e vão exigir skills bem afiadas de arquitetura e desenvolvimento de software.
Trabalhamos principalmente com Ruby, Go e React.

Tem bastante coisa para fazer, mas se você curte desafios realmente grandes e com alto impacto na vida das pessoas, está no lugar certo!

#### Com quem você irá trabalhar:
Com um time de 6 - 8 pessoas, com conhecimento em globalização de produtos.
Em geral, os times aqui têm uma pessoa team leader, que é responsável por acompanhar entregas e direcionar o desenvolvimento de carreira das pessoas; uma pessoa PM, que ajuda a direcionar as demandas para desenvolvimento conforme a estratégia macro dos produtos e uma pessoa designer, que ajuda a entregar a melhor experiência para os nossos clientes.

Nós utilizamos métodos ágeis como Scrum, Kanban e XP. Somos adeptos a TDD e usamos Circle CI para integração contínua (com 95% de coverage!) tudo integrado via Slack. Todo PR passa por code review e também fazemos pair programming para compartilhar conhecimentos e melhores práticas. Se você quiser conhecer a nossa stack e saber tudo o que usamos, visite o [stackshare](https://stackshare.io/resultados-digitais/rd-station).

## Local

- São Paulo (Vila Olímpia)
- Florianópolis
- Joinville
- Remoto

## Benefícios
- Plano de Saúde - sem nenhum custo pra você e dependentes;
- Plano Odontológico; 
- VA ou VR (R$600,00 mensal)
- RDiscount - rede de descontos em diferentes lojas, cinemas e restaurantes;
- Gympass;
- Seguro de vida.

#### Diferenciais
- Home office;
- Cultura de feedback, desenvolvimento e mentoria;
- Fazer parte de uma das [Linkedin Top Companies](http://bit.ly/RDehtop) - uma das 25 empresas em que os brasileiros mais sonham em trabalhar;
- Aprender e trabalhar diariamente com profissionais referência no mercado;
- Cursos e certificações da RD University (nossa universidade corporativa) para você explorar.

## Requisitos

**Estamos buscando uma pessoa: **
- Com experiência em arquitetura de softwares web escaláveis, performáticos e de fácil manutenção;
- Com conhecimento em Ruby; 
- [Desejável] Experiência com Golang;
- [Diferencial] Experiência com internacionalização de produtos;
- [Diferencial] Já trabalha (ou ter trabalhado) com microserviços.

## Sobre a RD:
A RD nasceu no Brasil, em 2011, com o objetivo de ajudar empresas de todos os portes e segmentos a entender e a aproveitar os benefícios do marketing digital, conquistando resultados reais e efetivos para seus negócios.
- Já são mais de 15k clientes em mais de 30 países;
- Somos um dos principais cases de SaaS B2B no Brasil;
- Temos escritórios na América Latina e Europa;
- GPTW: são 4 anos consecutivos como uma das melhores empresas para se trabalhar no Brasil;
- Criamos o [RD Summit](https://rdsummit.com.br/), maior evento de Marketing Digital e Vendas da América Latina;
- Já somos +700 pessoas (RDoers)!
No nosso [Culture Code](https://resultadosdigitais.com.br/blog/culture-code-rd/) você pode checar os nossos valores e no [blog](https://medium.com/rd-shipit) como trabalhamos no dia a dia.

## Como se candidatar

Clique [aqui](https://grnh.se/790fc7712), preencha o form e bora conversar! :)

_Sabemos que é muito importante para você ter um retorno, mesmo não seguindo no processo, então, fique de olho no seu e-mail, iremos entrar em contato com você! Ah, o **processo seletivo é 100% remoto**, então não se preocupe com deslocamentos - a não ser que você queira conhecer nossos espaços_ :)

**Comment by cmargulhano** [comment]
Olá, como vai?
A posição pode ser 100% remota?

**Comment by kaiofelipejs** [comment]
Oi @cmargulhano! Tudo certo e ai? 
Tem essa possibilidade sim.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
