### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Full-Stack  Node.js na [Replikante]

### ISSUE THREAD

**Issue by rodrigobmoura** [backend-br/vagas#220]
## Nossa empresa

Somos uma startup em franco crescimento que provê soluções e serviços utilizando inteligência artificial para replicar e automatizar as interações humanas.

## Descrição da vaga

Estamos em busca de desenvolvedores fullstack talentosos e experientes, para nos ajudar no desenvolvimento de nossa plataforma web.
	
**Diferenciais:**

Provemos um ambiente estimulante, com as seguintes características:

•	Hierarquia mínima

•	Horários flexíveis

•	Opção de fazer home office

## Requisitos

**Obrigatórios:**

•	 JavaScript
•	 Node.js
•	 Vue.js
•	 HTML5
•	 CSS3
•	 RESTful APIs
•	 GIT
•	 SQL
•	 MySQL

**Desejáveis:**

•	PHP
•	Python
•	Shell/Bash
•	WebSockets
•	CI/CD
•	AWS

## Local

São Paulo - SP  (CENU - Berrini)

## Contratação

Salário:

•	A combinar.

Tipo de contratação:

•	CLT ou PJ.

## Como se candidatar

Os interessados devem enviar seu currículo, LinkedIn e GitHub, mais pretensão salarial para o e-mail: tecnico@replikante.com.br. 

## Labels

- CLT
- PJ
- Alocado
- Remoto - Parcial
- Pleno
- Senior

**Comment by simaodev** [comment]
Teria a possibilidade de ser 100% remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
