### ISSUE TITLE
Tech Lead Back ERP | AB-Inbev (Ambev)

### ISSUE THREAD

**Issue by xandebianchi** [backend-br/vagas#2201]
# **Informações gerais da empresa**

### **A maior cervejaria do mundo** abriu no final de 2018 seu setor de _tecnologia_, o time chamado: _Beertech_.
Uma novidade, pois antes os aplicativos eram feitos por terceiros.

E agora está acontecendo a **Transformação Digital** da empresa, onde se constrói um aplicativo B2B para vendas dos seus produtos (cerveja, não alcoólicos, etc.), e ele funciona em todos os países que a empresa trabalha, pelo mundo todo. 

A **Anheuser-Busch InBev** (abreviada **AB InBev**), **líder no mercado mundial**, é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga **Interbrew** e da brasileira **Ambev**. Está sediada em Leuven, na Bélgica, e possui escritório em Nova York, e sedes em Jaguariúna-SP, Londres, Cidade do México, Johanesburgo, St. Louis, e outros locais. Conta com mais de duzentas marcas de bebidas, entre as quais se destacam Brahma, Skol, Antarctica, Budweiser, Corona, Stella Artois, Beck's, Leffe, Hoegaarden na Europa. 

### - A sede da vaga atualmente é em Jaguariúna-SP-Brasil. Em um futuro próximo, estaremos em Campinas-SP.

 **Porém,** há outros locais que estão sendo incluídos como possibilidade de se trabalhar, como sul, etc, e será possível transições de local. 

# **Sobre o time**

Estamos repensando a maneira como a AB InBev faz negócios com seus clientes de varejo e criando experiências digitais para atendê-los. Você ingressará em uma nova organização digital da AB InBev que consiste em estratégia digital, produto, design, análise, operações e engenharia. Essa organização é responsável por criar os produtos e plataformas que transformam nossas operações de vendas tradicionais em todo o mundo.

# **About the Job**

The Tech Lead: ERP will be responsible for supporting both local business units and other vendors to integrate their ERP systems with our e-commerce platform and will also be the technical lead for all new expansions to other business units which include rolling out web and mobile apps for that business unit.

Main stakeholders will include Product Team, Engineering Leadership and Local BU’s.

You will:

- Be a leading voice in team discussions and decisions. Focus on the whole team’s productivity and strive to increase the impact of the team’s work product.
- Lead teams of engineers located globally, e.g. Brazil.
- Assume technical responsibility for new services and functionality, lookout for opportunities for platform improvement, and work with engineers to scale our production systems.
- Lead, coach, pair with and mentor engineers.
- Lead the team in defining architecture, technical requirements and solutions and drive projects through to completion.
- Mentor software engineers from diverse backgrounds to nurture a culture of ownership, learning, automation, re-use, and engineering efficiency through the use of software design patterns and industry best practices.
- Contribute to the adoption of software architecture and new technologies.
- Be a leader within your team and the organization.
- Identify and lead technical initiatives to build clean, robust, and performant applications
- Collaborate with cross-functional team members from Product, Design, Program Management in order to deliver against quarterly and annual roadmap objectives.
- Handle planning and breaking down large projects into milestones and identifying risks and dependencies.
- Break down tasks for other engineers and offer guidance to other engineers on the team when they are blocked.
- Engage in code reviews helping maintain our coding standards and improving our code quality.
- Achieve on-time delivery without compromising quality.

# **Desired/Required Qualifications**

- 8+ years of relevant experience including ERP integration (SAP).
- B.S. in Computer Science or Engineering or equivalent years of work experience.
- At least two years being a tech lead of a group of three or more software engineers.
- Good active listening skills, the ability to empathize with customers, stakeholders and other engineers.
- Experience working using Agile methodology in a fast-paced environment.
- Lead architecture meetings and technical discussions with the focus of reaching consensus and best practice solutions.
- At least three demonstrable experiences in leading the deployments of systems into production.
- Experience in a high-paced, high-growth environment working with deadlines and milestones.
- Comfortable with ambiguity; you enjoy figuring out what needs to be done.
- Senior-level with Java spring boot, no sql databases (MongoDB), event-driven architecture, message bus (RabbitMQ or equivalent) and can learn anything you don't already know to get the job done.
- Excellent time management skills.
- Experience with internationalization and localization.
- Have a solid understanding of clean software design principles.
- Experience mentoring engineers with the team-focused mentality for success.
- Experience with data modeling and at least one database engine (MongoDB).
- Experience with distributed systems, CI/CD (Azure DevOps / VSTS) tools, and containerizing applications (Kubernetes), Cloud Hosting (Azure).
- Proven experience in e-commerce development and integration.
- Work with developers and product owners to create and maintain test automation for our products.
- Work with development teams to understand test automation gaps and implement coverage.
- Have experience using monitoring and metrics to support KPIs and performance of APIs
- JVM, microservice, and experience w/ event-driven architecture.
- Experience with XP practices such as pair programming and Test Driven Development.

# **Sobre nós**

No Brasil possuímos uma unidade com mais de 200 fanáticos por cerveja, e também nossa célula de tecnologia, chamada BeerTech que é focada em prover serviços e soluções em escala global para todas as cervejarias do grupo.

# **Tipo de Contratação**

CLT

# **Como se aplicar**

Mande seu CV e Carta de Apresentação para o e-mail abaixo com o título "Vaga Tech Back ERP":
alexandre.bianchi@ab-inbev.com 

**- Link de diversidade e inclusão:**
[Link de diversidade e inclusão](https://www.ab-inbev.com/careers/why-ab-inbev/diversity-and-inclusion.html)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
