### ISSUE TITLE
[São Paulo] Desenvolvedor Nodejs na Venda Válida

### ISSUE THREAD

**Issue by victorgsouto** [backend-br/vagas#2203]
A Venda Válida está buscando um Desenvolvedor Pleno ou Senior em Nodejs para complementar o time.

### Pré-requisitos:
- NodeJS (Experiência de 3 anos ou mais).
- Nível avançado de programação Javascript
- Experiência com banco de dados NoSQL (MongoDB).
- Experiência com fila (RabbitMQ).
- Experiência com cache (Redis).
- Experiência com GIT.

### Outras informações:

- Presencial.
- Tipo de contratação: PJ.
- Endereço: Webforce - Av. República do Líbano, 331 - Vila Mariana São Paulo - SP, 04553-011

Para se candidatar, envie seu currículo para victor@vendavalida.com.br

**Comment by tiago123456789** [comment]
A entrevista poderia ser total via Skype ou outra ferramenta?

**Comment by victorgsouto** [comment]
Opa @tiago123456789, todo processo vai ser presencial

**Comment by yureesantos** [comment]
Enviado.

**Comment by tiago123456789** [comment]
Muito obrigado @victorgsouto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
