### ISSUE TITLE
Olá, aceitam remoto?

### ISSUE THREAD

**Issue by DayaneVeronez** [backend-br/vagas#2205]
Olá, tudo bem?
Desculpe pela demora.
A vaga é presencial, ficamos em São Paulo - Vila Mariana.

Olá, aceitam remoto?

_Originally posted by @viniptds in https://github.com/backend-br/vagas/issues/2074#issuecomment-578280727_

**Comment by AntonioMellies** [comment]
Ops, deu alguma coisa errado ai, foi aberto uma _**issue**_ só pra responder o amigo @viniptds

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
