### ISSUE TITLE
[Remoto] Desenvolvedor Backend na Onyo

### ISSUE THREAD

**Issue by komyg** [backend-br/vagas#2206]
# Desenvolvedor Backend na Onyo

A experiência de refeição fora do lar nunca mais será a mesma. É por isso que estamos à procura de um Desenvolvedor Backend para uma missão que ajudará a colocar nas mãos de nossos clientes o poder absoluto de escolher, o quê e quando comer independe. Você desenvolverá produtos incríveis, que irão transformar a vida dos nossos clientes e parceiros.

## Sobre nós:

Temos uma forte cultura moldada pelos nossos valores.

- "Trabalhamos em equipe, valorizando todas as contribuições individuais"
- "Somos máquinas de aprender”
- "A melhor experiência do cliente é o que nos guia”
- "Somos humildes e determinados"
- "Praticamos a transparência"
- "Agimos como donos"
- "Somos resilientes"

## Como trabalhamos:

Damos um alto valor ao poder de escolha em todos os assuntos, desde o design do código até opções de vida, podendo também decidir de onde quer trabalhar.

- Trabalhamos remotamente.
- Amamos desafios e os encaramos de frente sem medo.
- Acreditamos que temos sempre o melhor time, e você pode ser parte disso.

## Nossa arquitetura atual:

- Nosso projeto principal foi criado usando Django e Celery. Outros projetos usam GraphQL, Flask, Falcon e SQLAlchemy.
- Para banco de dados gostamos do Postgres (relacional) e do Redis (cache).
- Usamos docker constantemente.
- Usamos o Google Kubernetes Engine.

## Assim que ingressar em nosso time, esperamos de você:

- Contribua com a concepção do produto como um todo para entregar a melhor experiência.
- Contribua na implementação de novas features do zero, bem como melhorar o código existente, revisar Pull Requests e propor soluções técnicas.
- Interaja com os times de Mobile, Front End, Operações a Ativação para ajudar a criar a melhor plataforma de todos os tempos.
- Escreva código limpo e com testes automatizados.
- Resolva débitos técnicos.

## O que estamos procurando:

- Ser autodidata
- Saber se comunicar de forma clara e coerente
- Estar disposto a ajudar pessoas menos experientes
- Experiência com Python (2 e 3) e Django
- Experiência com desenvolvimento de APIs REST
- Conhecimento de SQL e Banco Relacional (Postgres)
- Preocupação com a qualidade do código
- Testes automatizados
- Conhecimento básico de Docker
- Conhecimento de Celery.

## São diferenciais:

- Experiência com trabalho remoto
- Conhecimento de bancos de dados não relacionais (Redis)
- Conhecimento dos conceitos de GraphQL e/ou tenha trabalhado com essa tecnologia
- Conhecimento sobre infraestrutura e Kubernetes
- Conhecimento de Docker além do básico
- Conhecimento com autenticação JWT
- Experiência algum framework de Frontend (Angular ou React)

## Candidatura

Para se candidatar a essa vaga preecha o formulário nesse link: https://onyo.recruiterbox.com/jobs/fk0qm8j?source=backendbr

**Comment by cleberzavadniak** [comment]
Essa vaga ainda está aberta?
Pergunto porque o link do recruiterbox.com está "quebrado".

**Comment by komyg** [comment]
Oi @cleberzavadniak,

Não, por enquanto congelamos as novas contratações na Onyo. Vou fechar esse issue.

Obrigado,
Felipe
