### ISSUE TITLE
[São Paulo] DESENVOLVEDOR BACK-END PLENO  [Infovagas]  

### ISSUE THREAD

**Issue by patyandreolli** [backend-br/vagas#2209]
**VAGA DESENVOLVEDOR BACK-END PLENO – SÃO PAULO**

•	Desenvolver e manter serviços de alta disponibilidade e grande volume de acessos.
•	Experiência conhecimentos em projetos Backend, Node.js, micro serviços e serverless.
•	Conhecimento intermediário em Banco de Dados SQL e NoSQL.
•	Experiência com deploy de sistemas de alta disponibilidade.
•	Experiência com desenvolvimento de APIs RESTful e/ou Webservices

Ambiente inclusivo e desafiador, com ferramentas e tecnologias de ponta.
Desenvolvimento contínuo (on the job e treinamentos).
**Contratação: CLT + Benefícios :Assistência Médica e Odontológica, Vale-Transporte, Vale-Refeição e Café da Manhã.
Local de Trabalho: Mooca – São Paulo** 

**Interessados enviar currículo para recrutamento@infovagas.com  indicando no assunto “Desenvolvedor Pleno-Mooca”**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
