### ISSUE TITLE
[Alphaville] Back End Java [ITeam]

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#2210]
## Descrição da vaga

Experiência em análise sistêmica; análise de requisitos funcionais e técnicos.
Conhecimento de metodologia ágil.
Java 8;
Java WEB Spring Boot;
Angular;
Node.JS;
Cloud Computer;
DevOps;
Docker.

## Local

Barueri/SP - Alphaville

## Duração de projeto

6 meses

## Requisitos

**Obrigatórios:**
Java 8;
Angular;

## Contratação

CLT

## Nossa empresa

A ITEAM está presente no mercado há mais de 15 anos. Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado - enviar no assunto: Back-end - Java

#### Alocação
- Alocado no cliente

#### Regime

- CLT

#### Nível

- Júnior
- Pleno
- Sênior

**Comment by guilhermecostalopes** [comment]
Trabalho remoto ?
