### ISSUE TITLE
[PR - Curitiba, Remoto] Desenvolvedor(a) Back End Sr. na Send4

### ISSUE THREAD

**Issue by fapell** [backend-br/vagas#2212]
_Trabalhe de onde estiver revolucionando a experiência de compra online._ 

**Por que você deveria vir trabalhar conosco?**
A Send4 é uma retailtech inovadora e reconhecida por diversos prêmios. Além disso, somos a mais nova integrante do Grupo CLSS, do qual fazem parte Compre&Confie, Lomadee e a gigante ClearSale (Great Place to Work).
Já passamos por uma aceleração no Vale do Silício, e estamos iniciando nossa expansão para a América Latina.  Somos cheios de energia, motivados a gerar impacto na vida de nossos usuários e apaixonados por transformar a experiência de consumo do Brasil e da América Latina.
Nosso time de tecnologia é responsável mas não tem medo de usar o que existe de mais moderno em termos de técnicas e ferramentas.
Algumas das ferramentas que usamos são Laravel, Node e React, possuímos cultura de DevOps e entregamos nosso software de maneira contínua usando Jenkins e Kubernetes. Além disso, exploramos todo o espectro de técnicas de codificação de programas, desde  a programação orientada a objetos até a programação funcional.

**Oferecemos:**

- Foco na qualidade de entrega não na sua formação ou título
- Horário flexível, autonomia, home-office e trabalho remoto
- Metodologia de desenvolvimento Ágil com fluxo e cerimônias maduras
- Ambiente informal, diverso e aberto para todos!
- ‘no dress code’ e localização incrível no centro de Curitiba
- Cozinha com lanches saudáveis liberados e outros benefícios
- Gestão com alto conhecimento estratégico e reconhecimento de mercado
- Time organizado em SQUADS com gestão por resultados e cultura de feedback
- Mentorias constantes com referências e incentivo para eventos e formações
- Nossos Pilares: Service Design, Data e Customer Experience
- Contratação CLT ou PJ

 

**O que esperamos de você**

Muita experiência em desenvolvimento de software. Vasto conhecimento sobre a utilização de ferramentas e como as coisas funcionam por debaixo dos panos. Sólida compreensão de ciência da computação, algoritmos, estruturas de dados, análise de complexidade, heurísticas de gerenciamento de concorrência e paralelismo, conhecimento em sistemas criptográficos.
Nós trabalhamos com o que há de mais moderno no front-end, usando técnicas de programação funcional para garantir que interações com o usuário sejam preditivas. Estamos sempre em busca da forma mais eficiente de resolver problemas no back-end. A arquitetura de sistemas é muito importante para nós e esperamos que você possa contribuir muito em nossos produtos.
Se você é uma pessoa inquieta, que não descansa até descobrir os mínimos detalhes sobre como uma ferramenta funciona, que se preocupa não só com a qualidade do produto, mas também com a qualidade do código, você é a pessoa certa para esta vaga!

**Não se candidate se você não for ou tiver:**

- Papo reto: Valoriza a objetividade. Falamos o que precisa ser falado.
- Casca grossa: Resiliente e motivado por desafios.
- Sempre inconformado: Não se contenta com a média.
- Focamos na solução: Coloque o peixe podre na mesa para resolver.
- Todos donos: construímos a nossa empresa ideal todos os dias. 
- Positividade e Simplicidade: Atitude e energia sem complicações.

 

_Nosso quartel general é em Curitiba, temos escritório em São Francisco (CA) e São Paulo, mas você pode trabalhar aí da sua cidade mesmo ;)_

Saiba mais sobre nós [http://bit.ly/send4news](http://bit.ly/send4news)
Quer fazer parte da revolução do varejo? Candidate-se aqui! [http://bit.ly/backdevs4](http://bit.ly/backdevs4)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
