### ISSUE TITLE
[São Caetano do Sul/SP] PHP Developer na Kymo

### ISSUE THREAD

**Issue by vitorbari** [backend-br/vagas#2213]
## Descrição da vaga

Desenvolvimento e manutenção de sistemas em PHP.

## Local

Escritório - São Caetano do Sul /SP

## Benefícios

- A combinar

#### Diferenciais

- Ambiente informal e acolhedor

## Requisitos

**Obrigatórios:**

Conhecimentos / Experiência: 
- PHP
- MySQL
- Bootstrap
- Git

**Desejáveis:**

- Laravel
- Experiência com ferramentas de envio de emails transacionais (ex Mailgun)
- Configuração servidores (Apache, Nginx, SGBD)

## Contratação

PJ a combinar

## Nossa empresa

[Kymo](http://kymo.it/) - Empresa prestadora de serviços de TI em franca expansão, há mais de 15 anos auxiliando seus clientes a atingir a eficiência que buscam e a tranquilidade que merecem.

## Como se candidatar

Por favor envie um email para: ana.ferreira@kymo.it com seu CV anexado e pretensão salarial (PJ) - enviar no assunto: Vaga PHP

**Comment by Neyelson** [comment]
Bom dia, enviei um e-mail. 👍

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
