### ISSUE TITLE
[Belo Horizonte - Remoto] Desenvolvedor de Software Pleno|Jr no Melhor Plano

### ISSUE THREAD

**Issue by GuilhermeLLS** [backend-br/vagas#2215]
### Sobre o MelhorPlano
O Melhor Plano é uma solução que ajuda os consumidores a tomarem a melhor decisão na contratação de serviços. Nosso objetivo é ajudar milhões de pessoas a economizarem bilhões!
Atualmente, somos os líderes em comparação de telefonia no Brasil e já impactamos mais de 8 milhões de brasileiros a tomarem decisões mais informadas com planos de celular, banda-larga, fixo, tv, combos e agora também na área financeira!

### Sobre o Candidato
Não é obrigatório ter um curso superior, porém, caso não tenha, observaremos mais a experiência que você já teve até aqui. Para esta vaga, o candidato já tem um par de anos de experiência profissional.

O desenvolvedor ideal para a vaga:

- Aplica bem os fundamentos de desenvolvimento de software como algorítmos e estrutura de dados
- Já consegue escrever um código limpo e modular
- Já teve experiência com trabalho em equipe na construção de projetos de softwares mais longos
- Se bem orientado por um arquiteto de sistemas, consegue contribuir significativamente em projetos complexos com vários desenvolvedores
- Comunica bem problemas e usa do conhecimento do time para construir soluções melhores
- É uma pessoa curiosa e está sempre experimentando novas tecnologias

Também é desejável, mas não **obrigatório**:

- Ter tido alguma experiência com Node.js ou React, mesmo que não tenha sido uma experiência profissional
- Conhecer bem o Typescript
- Conhecer bem o protocolo HTTP e APIs Rest
- Ter trabalhado em algum projeto de soluções Web para consumidores

### Sobre a Vaga
Tecnologia é fundamental para a construção do Melhor Plano. Para funcionar bem, temos que atender várias demandas de diferentes grupos:

- Para o consumidor: capturar preços de serviços em todo o Brasil! Conseguir mostrar dados de maneira simples e precisa, atendendo milhões de usuários com respostas instantâneas.
- Para o time: prover ferramentas para que outros times trabalhem e produzam o máximo de resultado!
- Para parceiros: conseguir acompanhar resultados e analisar dados com precisão.

Você trabalhará em uma ou mais partes do stack do Melhor Plano:

- Linguagem: Typescript
- Front-end React (Preact)
- Node
- MongoDB / MySQL / Google Big Query
- Infra-estrutura: AWS / Google Cloud 

**Para se candidatar a vaga, clique neste link:**  https://airtable.com/shrUwkrE60MiJ3Pj1

### Local de Trabalho e Benefícios

**Vale Refeição / Alimentação** - R$ 28,60 por dia - cerca de R$ 600 por mês (dependendo de quantos dias úteis temos no mês) - 25% do Plano de Saúde Bradesco - Reembolso transporte quando for trabalhar no escritório - Possibilidade de **stock options** após um ano de empresa

**Flexibilidade de horário (Tempo integral);**

No Melhor Plano, tanto horário como local de trabalho é flexível. A sede da empresa fica na Savassi, em Belo Horizonte, mas o contrato de trabalho é **remoto** e você pode trabalhar de onde preferir. Toda a gestão e comunicação é feita online.

**Remuneração** Contrato CLT - tempo integral. Salário baseado na experiência, por favor, indique sua pretensão salarial na aplicação.

Labels

Remoto
Pleno
Junior

**Comment by hallss93** [comment]
possibilidade de PJ?

**Comment by GuilhermeLLS** [comment]
> possibilidade de PJ?

apenas CLT @hallss93

**Comment by victorvhs** [comment]
Enviado!🤞🤞

**Comment by dersonsena** [comment]
@GuilhermeLLS submetido =)

**Comment by tiago123456789** [comment]
A vaga ainda está aberta?

**Comment by GuilhermeLLS** [comment]
> A vaga ainda está aberta?

@tiago123456789 estamos para começar um novo processo! Vou fechar essa issue e abrir uma outra em alguns dias.

**Comment by tiago123456789** [comment]
@GuilhermeLLS  obrigado.
