### ISSUE TITLE
[Rio de Janeiro - Vaga presencial] - Desenvolvedor(a) Full Stack .NET - Pleno

### ISSUE THREAD

**Issue by katiavidal** [backend-br/vagas#2216]
## Local

Vaga presencial no centro do Rio de Janeiro em frente a estação Carioca.

## Benefícios

Ambiente descontraído, dinâmico e com grandes oportunidades de crescimento.
Valorizamos muito o aprendizado. Oferecemos auxílio em cursos e certificações.
Datas comemorativas são dia de festa. Inclusive o seu aniversário!
Equilíbrio entre mente e corpo: Shiatsu semanal para relaxarmos.
Plano de Saúde Amil + Plano odontológico.
Vale-refeição (R$548,10/mês) e Vale alimentação (R$341,71/mês); Vale transporte.
Estamos trabalhando com pretensão salarial.

## Requisitos

NET 4.6 – 4.7 e .NET Core;
Programação orientada a objetos;
ASP.Net Web API;
Angular 6;
Typescript;
Design Patterns;
Ferramental NPM (Node Package Manager);
Bancos de dados MS SQL Server;
Conhecimentos avançados em HTML5 e CSS3 (Pré-processadores SASS / LESS);
Ferramentas de controle de versão (Git);
Métodos Ágeis;

Desejáveis

Conhecimento em Azure Functions;
Conhecimento em React;
Experiência em SOA e/ou Microserviços;
Experiência em ambiente Cloud;
Experiência em Test Driven Development (TDD).

## Contratação

CLT

## Nossa empresa

Iniciamos a nossa trajetória em 2008 com objetivo de proporcionar aos nossos clientes todo o apoio tecnológico necessário para o desenvolvimento de soluções digitais inovadoras e transformar a maneira de oferecer serviços e se relacionar com o seu público. 

Ao longo desses anos, construímos um sólido portifólio de soluções em plataformas Web, Desktop e aplicativos Mobile. Participamos também de competições internacionais, como o Hello World Open e recentemente criamos o projeto open source Realize.js.

Nosso site: www.workingminds.com.br

## Como se candidatar

Para conhecer mais detalhes sobre a nossa empresa e fazer o seu cadastro acesse o link:
https://jobs.kenoby.com/vagaswkm/job/desenvolvedora-full-stack-net-pleno/5dfa23b6b2264617c3bb2362

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
