### ISSUE TITLE
`[Brasilia] Especialista Domain Driven Design na Coopersystem`

### ISSUE THREAD

**Issue by vagasCoopersystem** [backend-br/vagas#2217]
`[Brasilia] Especialista Domain Driven Design na Coopersystem`
==================================================
-->

## Descrição da vaga

Projeto PCB em Banco do Brasil 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$32/dia
- Gestão participativa 

## Requisitos

**Obrigatórios:**
--Experiência em modelagem de software utilizando DDD (Domain Driven Design) 
-- Experiência de modelagem para microsserviços
-- Experiência em Metodologias Ágeis.

## Contratação

Contrato através de Cooperativa 

## Nossa empresa

Somos a maior Cooperativa de TI do Brasil. Há mais de 20 anos tiramos do papel idéias inovadoras e transformamos em sistemas que automatizam a rotina das empresas.

## Como se candidatar

Por favor envie um email para vagas@coopersystem.com.br com seu CV anexado - enviar no assunto: Especialista DDD

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após a finalização de cada processo.

#### Alocação
- Alocado

#### Regime
- Cooperativa

#### Nível
- Sênior
- Especialista

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
