### ISSUE TITLE
[Rio de Janeiro - Vaga presencial] -Desenvolvedor(a) Full Stack .NET - Júnior

### ISSUE THREAD

**Issue by katiavidal** [backend-br/vagas#2218]
# Local

Vaga presencial no centro do Rio de Janeiro em frente a estação Carioca.

## Benefícios

Ambiente descontraído, dinâmico e com grandes oportunidades de crescimento.
Valorizamos muito o aprendizado. Oferecemos auxílio em cursos e certificações.
Datas comemorativas são dia de festa. Inclusive o seu aniversário!
Equilíbrio entre mente e corpo: Shiatsu semanal para relaxarmos.
Plano de Saúde Amil + Plano odontológico.
Vale-refeição (R$548,10/mês) e Vale alimentação (R$341,71/mês); Vale transporte.

## Requisitos

NET 4.6 – 4.7 e .NET Core;
Programação orientada a objetos;
ASP.Net Web API;
Angular 6;
Bancos de dados MS SQL Server;
Conhecimentos em HTML5 e CSS3 (Pré-processadores SASS / LESS);
Ferramentas de controle de versão (Git);
Métodos Ágeis;

Diferenciais

Experiência com Typescript;
Aplicação de Design Patterns;
Ferramental NPM (Node Package Manager);
Conhecimento em Azure Functions;
Conhecimento em React;
Conhecimentos sobre arquitetura de Microserviços;
Experiência em ambiente Cloud;
Experiência em Test Driven Development (TDD).

## Contratação

CLT

## Nossa empresa

Iniciamos a nossa trajetória em 2008 com objetivo de proporcionar aos nossos clientes todo o apoio tecnológico necessário para o desenvolvimento de soluções digitais inovadoras e transformar a maneira de oferecer serviços e se relacionar com o seu público. 

Ao longo desses anos, construímos um sólido portifólio de soluções em plataformas Web, Desktop e aplicativos Mobile. Participamos também de competições internacionais, como o Hello World Open e recentemente criamos o projeto open source Realize.js.

Nosso site: www.workingminds.com.br

## Como se candidatar

Para conhecer um pouco mais da nossa empresa e fazer o seu cadastro, acesse o link:
https://jobs.kenoby.com/vagaswkm/job/desenvolvedora-full-stack-net-junior/5d79306b9747f07f41c4d950

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
