### ISSUE TITLE
[Porto Alegre] Dev Node - SOUTH SYSTEM

### ISSUE THREAD

**Issue by cmazoni** [backend-br/vagas#2219]
## Descrição da vaga

Oportunidade de atuação com Node em um de nossos clientes do setor financeiro, com tecnologias de ponta. 

## Local

Presencial em Porto Alegre.

## Benefícios

- Material Dell de ótima qualidade
- Disponibilização de cursos e treinamentos para impulsionar o desenvolvimento

## Requisitos

Obrigatórios
- Experiência com NodeJS

Desejáveis
- Experiência com React e/ou Angular

## Contratação

PJ ou cooperativado

## Nossa empresa

A SOUTH SYSTEM atua hoje principalmente no setor financeiro, desenvolvendo as melhores soluções para atender às demandas de seus clientes. Focamos muito no desenvolvimento de nossos profissionais, oferecendo cursos e treinamentos para impulsionar seu desenvolvimento!

## Como se candidatar

Envie um e-mail com o teu currículo para claudia.mazoni@southsystem.com.br com a vaga no assunto e vamos marcar um café!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
