### ISSUE TITLE
BRQ SP- Back End NodeJS Sênior

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#222]
Programador Node Sênior

Experiência no uso de Node.js, Linux; APIs; Integração e Delivery Contínuos, Jenkins ou ferramentas similares; Tecnologias AWS; git e flows como git flow/gitlab flow.
Contratação CLT, salário a combinar mais benefícios (VR, VA, assistências médica e odontológica, seguro de vida, previdência).
Vagas presenciais no cliente.
Horário comercial.
Local: Faria Lima- Bairro Itaim Bibi- SP.

Caso tenha interesse,  pode entrar em contato com a Renata (ryokota@brq.com).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
