### ISSUE TITLE
[São Paulo] Desenvolvedor Java Jr. - Docket 

### ISSUE THREAD

**Issue by carolinaleaodocket** [backend-br/vagas#2220]
**Somos uma startup revolucionária.**

Docket é uma startup de tecnologia que está reinventando a forma como as grandes empresas lidam com a obtenção de documentos e certidões. Através do uso intensivo de tecnologia, dados e inteligência artificial tornamos o dia a dia de nossos clientes mais ágil, transparente e eficiente.

Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que estejam alinhados com a nossa cultura e nosso propósito. \o/

**RESPONSABILIDADES E ATRIBUIÇÕES**
Na Docket você irá:
-Trabalhar no desenvolvimento (código/testes) com múltiplos projetos
-Criar estratégias para transformar requisitos de negócio, funcionais e não funcionais, em código modular e reutilizável;
-Responsável por aplicar as boas práticas de engenharia de software e padrões de projeto;
-Implementar e manter aplicações;
-Responsável pela manutenção de códigos/testes de sistemas;

**REQUISITOS E QUALIFICAÇÕES**
 Você vai se encaixar bem se:
-Possuir formação em Ciências da Computação, Sistemas de Informação ou áreas relacionadas à tecnologia da informação.
-Bons conhecimentos em Java, SQL, HTML, CSS e JavaScript
-Conhecimentos em framework como Spring ou Hibernate
-Ter experiência de no mínimo 1 ano em desenvolvimento Java

**INFORMAÇÕES ADICIONAIS**
Vantagens:
Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida + Improve Yourself;
Auxílio creche para crianças de até 1 ano
Baby Cash após nascimento dos filhos
Comidinhas uma vez por semana
 Ambiente descontraído, criativo e oportunidade de crescimento acelerado =)
Local: Pinheiros
Horário: 44 horas semanais.

Se candidate direto através da nossa página de carreiras: https://docket.gupy.io/jobs/138191?jobBoardSource=gupy_public_page

**Comment by Jerffesongoncalves** [comment]
Bom dia, aceita remoto?

Att.
________________________________
De: carolinaleaodocket <notifications@github.com>
Enviado: terça-feira, 3 de março de 2020 14:06
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [backend-br/vagas] [São Paulo] Desenvolvedor Java Jr. - Docket (#2220)


Somos uma startup revolucionária.

Docket é uma startup de tecnologia que está reinventando a forma como as grandes empresas lidam com a obtenção de documentos e certidões. Através do uso intensivo de tecnologia, dados e inteligência artificial tornamos o dia a dia de nossos clientes mais ágil, transparente e eficiente.

Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que estejam alinhados com a nossa cultura e nosso propósito. \o/

RESPONSABILIDADES E ATRIBUIÇÕES
Na Docket você irá:
-Trabalhar no desenvolvimento (código/testes) com múltiplos projetos
-Criar estratégias para transformar requisitos de negócio, funcionais e não funcionais, em código modular e reutilizável;
-Responsável por aplicar as boas práticas de engenharia de software e padrões de projeto;
-Implementar e manter aplicações;
-Responsável pela manutenção de códigos/testes de sistemas;

REQUISITOS E QUALIFICAÇÕES
Você vai se encaixar bem se:
-Possuir formação em Ciências da Computação, Sistemas de Informação ou áreas relacionadas à tecnologia da informação.
-Bons conhecimentos em Java, SQL, HTML, CSS e JavaScript
-Conhecimentos em framework como Spring ou Hibernate
-Ter experiência de no mínimo 1 ano em desenvolvimento Java

INFORMAÇÕES ADICIONAIS
Vantagens:
Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida + Improve Yourself;
Auxílio creche para crianças de até 1 ano
Baby Cash após nascimento dos filhos
Comidinhas uma vez por semana
Ambiente descontraído, criativo e oportunidade de crescimento acelerado =)
Local: Pinheiros
Horário: 44 horas semanais.

Se candidate direto através da nossa página de carreiras: https://docket.gupy.io/jobs/138191?jobBoardSource=gupy_public_page

**Comment by carolinaleaodocket** [comment]
Olá!

Esta vaga é presencial aqui no nosso escritório mesmo, nós estamos
localizados em Pinheiros, a menos de 5 minutos a pé do metrô =)

[image: Logo Docket]
Carolina Leão
Folks
11 2769-5007
docket.com.br
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=ee81dd11e2&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=c13dc2be69&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=09843fb6fb&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=330a4a5bf7&e=d9d1f070dd>
[image:
Youtube] <https://www.youtube.com/channel/UC2x4kEpt5tXEKg1RCaFLMUQ> [image:
Blog da Docket] <http://www.documentosjuridicos.com.br/>

Startup acelerada por:

4º Lugar no LinkedIn
Top Startups 2018

Selecionada para
o Ranking
[image: Logo do Google Developers Launchpad] [image: Logo do ScaleUp da
Endeavor] [image: Logo do LinkedIn Top Startups 2018] [image: Logo 100
Startups to Watch de 2019]


Em qua., 4 de mar. de 2020 às 08:26, Jerffeson <notifications@github.com>
escreveu:

**Comment by walterfjustino** [comment]
Boa noite Carolina!

Qual e-mail posso estar encaminhando meu currículo?

Att.Walter

**Comment by Jose-Robert** [comment]
Olá, poderia me enviar me passar algum email, não estou conseguindo acessar o link.

**Comment by carolinaleaodocket** [comment]
Olá José,

Segue o meu e-mail: carolina.leao@docket.com.br

[image: Logo Docket]
Carolina Leão
Folks
11 2769-5007
docket.com.br
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=ee81dd11e2&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=c13dc2be69&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=09843fb6fb&e=d9d1f070dd>
<https://docket.us18.list-manage.com/track/click?u=775956d9e553eca34e3e922c3&id=330a4a5bf7&e=d9d1f070dd>
[image:
Youtube] <https://www.youtube.com/channel/UC2x4kEpt5tXEKg1RCaFLMUQ> [image:
Blog da Docket] <http://www.documentosjuridicos.com.br/>

Startup acelerada por:

4º Lugar no LinkedIn
Top Startups 2018

Selecionada para
o Ranking
[image: Logo do Google Developers Launchpad] [image: Logo do ScaleUp da
Endeavor] [image: Logo do LinkedIn Top Startups 2018] [image: Logo 100
Startups to Watch de 2019]


Em ter., 10 de mar. de 2020 às 16:22, José Robert <notifications@github.com>
escreveu:

**Comment by guilhermecostalopes** [comment]
Trabalho remoto ?

**Comment by carolinaleaodocket** [comment]
Olá, a Carolina saiu da empresa. Como fazemos para manter a divulgação?
[image: Logo Docket] <https://docket.com.br/>

Laura Catalani
Folks
laura.catalani@docket.com.br
11 2619-7085
[image: Linkedin] <https://www.linkedin.com/company/docketbrasil/> [image:
Instagram] <https://www.instagram.com/docketbrasil> [image: Blog DOcket]
<https://blog.docket.com.br/> [image: YouTube]
<https://www.youtube.com/channel/UC2x4kEpt5tXEKg1RCaFLMUQ> [image: Facebook]
<https://www.facebook.com/docketbrasil/>

Startup acelerada por:

4º Lugar no LinkedIn
Top Startups 2018

Selecionada para
o Ranking
[image: Logo do Google Developers Launchpad] [image: Logo do ScaleUp da
Endeavor] [image: Logo do LinkedIn Top Startups 2018] [image: Logo 100
Startups to Watch de 2019]


Em qua., 24 de jun. de 2020 às 21:18, github-actions[bot] <
notifications@github.com> escreveu:
