### ISSUE TITLE
[São Paulo] Back End Developer - Ruby on Rails

### ISSUE THREAD

**Issue by CamilaQuerubin** [backend-br/vagas#2221]
## Descrição da vaga

Atuar como desenvolvedor nas squads de inovação do Grupo Bioritmo (Smartfit) na Avenida Paulista, com o objetivo de melhorar a jornada dos clientes do grupo.

## Local

Presencial - Avenida Paulista - SP

#### Diferenciais

- horário flexível 
- possibilidade de home office

## Requisitos

**Obrigatórios:**

- Ruby on Rails

**Desejáveis:**

- JavaScript
- Git
- React
- Node.js
- SQL/NoSQL
- Conhecimento em json
- Conhecimento em design responsivo, bootstrap.
- Testes Unitários.
- Documentação.
- Scrum e Kanban
- BDD
-

## Contratação

PJ (emissão NF)

## Empresa 

Somos uma empresa de inovação que atendem grandes clientes como a Smart Fit. 
ACE CORTEX (Corporate to Exponential): Com projetos de inovação corporativa, alavancamos, junto à liderança e aos colaboradores, grandes corporações ao futuro de seus novos mercados. Atendemos grandes empresas, como: BTG Pactual, EDP, BASF, Natura, Google e muitos outros.

Como empresa de investimentos em startups, entrega aos melhores empreendedores uma plataforma com capital, expertise e networking de alto nível. Já foram mais de 300 startups aceleradas, mais de 80 investidas e mais 150 mentores qualificados.

## Como se candidatar

Por favor envie um email para camila@goace.vc CV anexado - enviar no assunto: Vaga Front End

## Labels

- PJ
- Pleno 
- Senior
- Presencial

#### Alocação
- Alocado

#### Nível
- Junior
- Pleno
- Sênior

**Comment by maugravena** [comment]
Olá @CamilaQuerubin 

Essa vaga continua disponível?
