### ISSUE TITLE
[SAO PAULO] Desenvolvedor(a) Back end

### ISSUE THREAD

**Issue by alicesrossi** [backend-br/vagas#2223]
Estamos em busca de desenvolvedores apaixonados por construir produtos digitais de qualidade, que estejam atualizados com as melhores práticas e tecnologias, envolvidos e engajados com comunidades de software.

**Requisitos da vaga**
Conhecimento em PHP;
CMS: Drupal ou Wordpress;
Conhecimento prático do fluxo de versionamento com GIT;
Criação e consumo de API;
Ferramentas de Deploy Contínuo e Integração Contínua;

Morumbi - São Paulo

Contratação CLT

Benefícios:
VR
VT
Horário Flexível
Café da manhã toda sexta-feira
Frutas toda quarta-feira
8 Home Offices Mensais
Assistência Médica e Odontológica
Gympass
Parceria com SESC
Jogos
⠀⠀

Será que você é nosso próximo(a) Juster?

Se candidata aqui e vem bater um papo com a gente!
https://justdigitalbr.recruitee.com/o/dev-back-end-pleno-morumbi-sao-paulo

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
