### ISSUE TITLE
[São Paulo] Arquiteto de Infraestrutura na ACE Startups

### ISSUE THREAD

**Issue by tatianaschott** [backend-br/vagas#2224]
## Descrição da vaga
Atuar como Arquiteto de Infraestrutura em um projeto inovador para um grande cliente da ACE Startups.
## Local
Presencial - Barra Funda - SP
#### Diferenciais
- horário flexível
- possibilidade de home office
## Requisitos
**Obrigatórios:**

-  AWS

- Ruby on Rails

**Desejáveis:**
- Mudança de cultura
- Scrum e Kanban
## Contratação
PJ (emissão NF)
## Empresa
Somos uma empresa de inovação que atendem grandes clientes como a Smart Fit.
ACE CORTEX (Corporate to Exponential): Com projetos de inovação corporativa, alavancamos, junto à liderança e aos colaboradores, grandes corporações ao futuro de seus novos mercados. Atendemos grandes empresas, como: BTG Pactual, EDP, BASF, Natura, Google e muitos outros.
Como empresa de investimentos em startups, entrega aos melhores empreendedores uma plataforma com capital, expertise e networking de alto nível. Já foram mais de 300 startups aceleradas, mais de 80 investidas e mais 150 mentores qualificados.
## Como se candidatar
Por favor envie um email para camila@goace.vc CV anexado - enviar no assunto: Arquiteto Infraestrutura
## Labels
- PJ
- Pleno
- Senior
- Presencial
#### Alocação
- Alocado
#### Nível
- Junior
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
