### ISSUE TITLE
[Niterói / RJ - Vaga presencial] - Desenvolvedor(a) Full Stack Node

### ISSUE THREAD

**Issue by Gabrielmoraesp** [backend-br/vagas#2225]
Vaga para Full Stack - Niterói / RJ

# Desafio
Procuramos um desenvolvedor apaixonado por desafios, tecnologia e conhecimento.

Você será responsável por desenvolver páginas web incríveis, com integração a vários sistemas da nossa infraestrutura.

Também vamos cobrar que você seja gente fina e trabalhe bem em equipe =)

**O que não pode faltar?**
- NodeJS (Experiência de 2 anos ou mais).
- Nível avançado de programação Javascript
- Experiência com banco de dados SQL (Mysql)
- Conhecimento de ferramentas auxiliares de versionamento, gerenciador de dependências e automação (ex: git,npm,gulp);
- Forte conhecimento em Node Adonis e VueJs;
- Boas práticas de programação;
- Mindset de aprendizado contínuo;

**O que melhoram suas chances?**
Experiência com Frameworks (Laravel, Express);
Experiência com desenvolvimento back-end em Node Adonis(criação de Apis, integração Database, Rotinas) e PHP;
Cache (Redis).
Design de UI/UX

**Outras informações:**
Presencial.
9h às 18h.
Tipo de contratação: PJ.
Endereço: R. Gen. Andrade Neves, 9 - Centro, Niterói - RJ, 24210-000

Para se candidatar, envie seu currículo para contato@xekout.me

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
