### ISSUE TITLE
[São Paulo/SP] Software Engineer na [Red Ventures Brasil]

### ISSUE THREAD

**Issue by pstvalle** [backend-br/vagas#2228]
SOBRE A EMPRESA
Fundada em Charlotte (USA) em 2000, a Red Ventures é uma empresa de tecnologia e marketing digital voltada à otimização de todo o processo de aquisição de clientes. Com uma base tecnológica e analítica muito forte, assumimos todo o processo de marketing e otimização do funil digital de uma operação - desde a captação até à efetivação da transação. Além de líder global nesse tipo de parceria, a empresa conta com uma série de ativos próprios e nosso portfolio de companhias conta com empresas como The Points Guy, uSwitch, BankRate, iq, Capital Research, dentre outras.

SOBRE A VAGA
No time de Engenharia de Software da Red Ventures, você atuará ativamente em um ou mais times desenvolvendo APIs distribuídas, escaláveis e resilientes, modelando e mantendo bancos de dados estruturados e tomando decisões de infraestrutura na nuvem.  Além disso, você terá exposição a squads multidisciplinares com os quais trabalhará durante todo o desenvolvimento do projeto. Da mesma forma que você ganhará experiência com linguagens como Golang e Node.js, arquitetura cloud e visão de negócios,
esperamos que você atue em conformidade com as boas práticas e convenções.

O QUE BUSCAMOS
- Pessoas das áreas de Ciência da Computação, Sistemas de Informação ou áreas relacionadas que sejam proativas e apaixonadas pelo que fazem;
- Profissionais buscando sempre a otimização de suas aplicações;
- Inglês intermediário ou superior (às vezes você precisará se comunicar com times internacionais);
- Possibilidade de trabalhar em nosso escritório (não contratamos profissionais remotos).

POR QUE TRABALHAR CONOSCO
- Tenha o melhor de dois mundos! Trabalhe em um ambiente dinâmico de start-up com o suporte de uma empresa norte americana líder em tecnologia;
- Fique em contato com o que há de mais novo no mercado: trabalhe com infraestrutura cloud e utilize linguagens de programação no estado-da-arte;
- Trabalhe em uma empresa global de crescimento acelerado;
- Ambiente disruptivo e empreendedor com plano de carreira acelerado.

Candidate-se através do Link: https://careers.redventures.com/application/position/878727?gh_jid=878727&gh_jid=878727

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
