### ISSUE TITLE
[Rio de Janeiro] Analista de Desenvolvimento Jr./Pleno [BigData Corp]

### ISSUE THREAD

**Issue by terezamachado** [backend-br/vagas#2229]
Já Pensou em trabalhar com BigData?

### BigData Corp!#BarradaTijucaRJ 

A BigDataCorp, líder no mercado de Big Data no Brasil e na América Latina, está procurando desenvolvedores (Jr. e Pleno) para seu time de Captura. 
Esse time tem como principal objetivo encontrar novas fontes de dados e impulsionar a criação de novas bases e produtos. 
O clima é descontraído e com um time apaixonado pelo que faz.
Currículos: vagas@bigdatacorp.com.br
No campo Assunto: Posição - Analista de Desenvolvimento

**Aqui você vai encontrar:**

- Ambiente Descontraído;
- Boas vindas com integração nas áreas;
- Remuneração e benefícios compatíveis com o mercado.
- Plano de Saúde - Bradesco;
- Assistência Dental - Bradesco;
- Vale Refeição;
- Seguro de Vida em Grupo;
- Liberdade para se vestir como se sentir bem;

**Como é o nosso dia a dia?**

- Desenvolver e dar manutenção em APIs para uso em larga escala;
- Desenvolver robôs para captura de informações públicas na internet (bem como manutenção);
- Desenvolver modelos de processamento em batch para processamento de grandes arquivos;
- Desenvolver novas funcionalidades para as APIs já existentes;
- Modelagem de bancos de dados (SQL e NoSQL);
- Desenvolver alarmes para melhor controle dos sistemas.

**Pré-requisitos**

- Ensino superior completo em Ciência da Computação, Bacharelado em Informática, Engenharia da Computação, Analise de Sistemas, Sistemas de Informação ou áreas afins;
- Habilidades sólidas em programação usando pelo menos uma linguagem orientada a objetos (ex: C#, Java, Python ou similares);
- Entendimento de processos/práticas de engenharia de software;
- Conhecimento em testes;
- Capacidade analítica/raciocínio lógico (problem solving/algoritmo);

**Diferenciais**

- Experiência com utilização de bancos de dados relacionais e/ou não relacionais;
- Vivência com soluções de versionamento de código (GIT, SVN, etc);
- Experiência com desenvolvimento de APIs;
- Experiência com serviços de nuvem (AWS, Azure, Google Cloud, etc);
- Experiência com bancos SQL e NoSQL;
- Conhecimento de ferramentas de scraping;
- Conhecimento de infraestrutura de soluções e deploys automatizados;
- Inglês Intermediário
- Experiência com Gestão para a posição Pleno;

Link das vagas: [https://www.bigdatacorp.com.br/trabalhe-conosco](https://www.bigdatacorp.com.br/trabalhe-conosco)

**Comment by guilhermecostalopes** [comment]
Trabalho remoto ?

**Comment by terezamachado** [comment]
Olá Guilherme,

Em contingência ao COVID-19, hoje estamos trabalhando remoto.

Em particular a vaga divulgada no GIT HUB, é presencial para o Rio de
Janeiro.

Sucesso na sua busca,
Um abraço,
[image: Img]
Tereza Machado
Pessoas
*T * +55 21 3795-2308 | 99111-0243   |   *E *
tereza.machado@bigdatacorp.com.br
Sim, temos vagas!
<https://www.bigdatacorp.com.br>
<https://www.linkedin.com/company/bigdatacorp>
<https://www.facebook.com/bigdatacorp/>   <https://twitter.com/BigData_Corp>
   <https://www.instagram.com/bigdatacorp/>
<https://www.youtube.com/bigdatacorp>


Em qua., 18 de mar. de 2020 às 08:34, guilhermecostalopes <
notifications@github.com> escreveu:

**Comment by guilhermecostalopes** [comment]
Obrigado pelo retorno
