### ISSUE TITLE
BRQ SP- .NET Sr Developer

### ISSUE THREAD

**Issue by ReAnne123** [backend-br/vagas#223]
Analista Programador .NET Sênior

Estamos em busca de um profissional com experiência no segmento bancário e seguintes conhecimentos: VS2015 C#, ReactJS, CSS3, DevExpress, aplicações WEB SPA, HTML, XML, JavaScript, AngularJS, Bootstrap, WCF.
Desejável conhecimento do produto financeiro de câmbio, SWIFT, mensagens BACEN, CHANGE.
Contratação CLT, salário a combinar mais benefícios.
Vagas presenciais no cliente.
Horário comercial.
Local: Faria Lima (Bairro Itaim Bibi)- SP.

Cvs serão muito bem vindos pelo e-mail ryokota@brq.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
