### ISSUE TITLE
[São Paulo] Desenvolvedor Java -  ABS SOFTWARE

### ISSUE THREAD

**Issue by guilhermecerqueir4** [backend-br/vagas#2233]
Hey, você...
**Você mesmo, desenvolvedor Java, conhecimento em API e MVC com spring? Precisamos conversar !!**

Temos a oportunidade ideal para você, que tem vontade de fazer a diferença e atuar diretamente com inovação.

**Quem somos?**
Uma empresa de tecnologia voltada para o mercado financeiro, apaixonada por inovação, localizada na região do **Itaim Bibi, em São Paulo/SP**, focada na eficiência do controle de investimentos
com soluções integradas para bancos, corretoras, distribuidoras, gestoras de recursos e family offices.

**O que você pode esperar da gente?**
* Oportunidade de inovar
* Horário flexível
* Projetos desafiadores
* Ambiente propício para seu desenvolvimento profissional

**O que esperamos de você?**
* Espírito inovador
* Sede por conhecimento
* Vontade de fazer a diferença

**Para fazer parte do nosso time, temos apenas algumas condições:**
* Conhecimento em Spring (API e MVC)
* Banco de dados relacional (SQL Server e Postgre)

**Você é daqueles que gosta de sair na frente? É, eu imaginei... Segue então o que consideramos como diferenciais:**
* Familiaridade com serviços AWS
* Entendimento de APIs REST/RESTful
* Utilização da ferramenta spring boot
* Familiaridade com o Jira Software
* Experiência com git flow
* Conhecimento em Mercado Financeiro
* Facilidade para trabalhar em equipe

**Agora que estamos conversados, basta nos enviar um e-mail para vagas@absoftware.com.br com o assunto "Java dev" e com o seu CV. Nossas oportunidades vão de Júnior a Sênior.**

**Comment by guilhermecostalopes** [comment]
Trabalho remoto?

**Comment by guilhermecerqueir4** [comment]
> Trabalho remoto?

100% nao, mas a ideia é que seja implantando em breve.
