### ISSUE TITLE
[São Paulo] Android Software Engineer Senior - CORA

### ISSUE THREAD

**Issue by natalia-sborges** [backend-br/vagas#2234]
A Cora está nascendo, e precisa de você para construir um novo banco.

É tudo do zero! Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano
.
Procuramos um Android Software Engineer Sênior, com pelo menos 4 anos atuando na área e com conhecimento em Kotlin. Outras linguagens ou ter trabalhado em startups serão diferenciais
.
A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga: https://byintera.in/coraandroid

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
