### ISSUE TITLE
[São Paulo] Back-end Pleno Developer na VIX

### ISSUE THREAD

**Issue by reisraff** [backend-br/vagas#2237]
## Descrição.

Dominar python, php, node.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde/odonto
- VR
- ...

#### Diferenciais

- use softwares/ferramentas que desejar
- sala com bilhar
- ...

## Requisitos

**Obrigatórios:**
- Competência

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rafael.reis@vix.com com seu CV anexado - enviar no assunto: Vaga Backend Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
