### ISSUE TITLE
[São Paulo - Presencial] NodeJS Developer Pleno na WeJam

### ISSUE THREAD

**Issue by crispossa** [backend-br/vagas#2238]
Queremos mudar a educação usando a tecnologia. Desenvolvemos produtos voltados a educação unindo design, tecnologia e inovação. Vem fazer parte dessa mudança você também!

Precisamos de Programador Node PLENO para desenvolvimento de produtos voltados a educação online.

**Principais atividades:**

- Você será responsável pelo desenvolvimento do back-end de uma plataforma de educação online que vai revolucionar a maneira que as pessoas aprendem algo.
- Suas tarefas consistem em desenvolver APIs em NodeJS integradas a um banco de dados relacional.
- Você também será responsável por documentar o código desenvolvido e escrever os testes necessários para garantir a estabilidade da plataforma.
- Também deverá reportar o trabalho executado em reuniões semanais.
- Você terá a sua disposição 2 profissionais de SQL para tirar dúvidas e aprender muito sobre PostgreSQL e MySQL.

**Não pode faltar:**

- NodeJS
- Experiência com banco de dados SQL
- Javascript
- GIT
- Docker

**Como se candidatar:**

- Envie um e-mail para queroserdev@wejam.email com seu currículo ou link do Github.

**Comment by SEdilson** [comment]
Boa noite. Vocês aceitam candidatos de outros estados? Qual o nível esperado dessa vaga?
