### ISSUE TITLE
[São Paulo] Back End Developer Node.JS (Pleno ou Sênior) para Turbi

### ISSUE THREAD

**Issue by Almanake** [backend-br/vagas#224]
A Turbi é uma empresa de compartilhamento de veículos, focada em proporcionar uma experiência única para seus clientes, oferecendo uma frota de carros TOP.
Procuramos um desenvolvedor para ser o próximo integrante da Turbi.
Se você gosta de programar, aprender e compartilhar conhecimento esta é a oportunidade.

Necessário:
* NodeJS
* TDD
* MVC
* Desenvolvimento e consumo de API REST/SOAP
* Banco de dados relacional e não relacional
* Controle de versão (GIT)
* Arquitetura microservices
* Princípios SOLID

Diferencial:
* AngularJS, SASS, Grunt, Gulp
* SEO
* Desenvolvimento para Mobile (Android/iOS)
* Google Cloud Platform /Firebase
* Agile/Scrum
* Machine Learning, Big Data, IA
* Autenticação (JWT/OAuth)
* CD/CI
* Inglês

Local: PLUGCLXT - Rua Lisboa, 890 (Pinheiros)
Horário: Flexível
Contratação: PJ

Quem tiver interesse, favor enviar CV ou perfil do LinkedIn para vieira@talentu.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
