### ISSUE TITLE
[São Paulo / Butantã] [Presencial] Dev. Fullstack (PHP / Laravel / Angular 1.x)

### ISSUE THREAD

**Issue by pedrolucasD** [backend-br/vagas#2241]
**Quer trabalhar em uma empresa que está buscando pessoas motivadas que querem mostrar toda a sua capacidade?**

Estamos buscando Desenvolvedores(as) Fullstack com sólidos conhecimentos em HTML5, Javascript e PHP para projetar interfaces e entregar a melhor experiência para os usuários, com foco na a otimização do código e agilidade no desenvolvimento.

Temos um grande desafio na construção de um ERP sob demanda para um cliente específico.
Se você gosta de desafios e quer entrar nessa jornada, venha com a gente! ;)

**Requisitos**

- HTML5
- CSS3
- Javascript
- Angular 1.x (AngularJS)
- PHP
- MySQL
- Laravel
- React
- Docker
- Métodos Ágeis (Scrum ou XP)

**Desejável**

- ERP
- Nodejs
- Typescript

**Para se candidatar, envie seu currículo em PDF para contato@systemhope.com.br com o título [Dev. Fullstack].**

**Comment by duuh30** [comment]
Aceita remoto ?

**Comment by pedrolucasD** [comment]
> Aceita remoto ?

@duuh30 

Nós oferecemos 1 dia na semana para que você trabalhe de home office, porém os demais é necessário que esteja em nosso escritório.

A disposição.
