### ISSUE TITLE
[São Paulo] Fullstack .Net Sr. na VENTRON

### ISSUE THREAD

**Issue by Dani-Ventron** [backend-br/vagas#225]
Programador Fullstack

Requisitos:
• DDD; TDD
• Angular 1 e X
• .Net Core (pelo menos conhecimento)
• Entity Framework
• Injeção de Dependência
• NodeJS
• Restful
• WebApi
• Bootstrap
• GIT
• VSTS

Desejável: 
• Azure
• Swagger
• Docker
• Pug

Local: São Paulo - Barra Funda
Projeto de tempo indeterminado
Envio de currículo: daniele.silva@ventron.com.br

**Comment by wfsimao** [comment]
Boa tarde, há possibilidade de ser remoto?

**Comment by Dani-Ventron** [comment]
oi @wfsimao, infelizmente não.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
