### ISSUE TITLE
[São Paulo] Back End .Net na VENTRON

### ISSUE THREAD

**Issue by Dani-Ventron** [backend-br/vagas#226]
Buscamos profissionais para atuação em um cliente do segmento Seguros, localizado na Faria Lima

Requisitos das vagas:
o Desenvolvimento .Net
o Orientação a Objetos
o Service Fabric (preferível)
o Estrutura de dados
o Analise de Algoritmos
o Conhecimentos em Banco de Dados
o Experience com RESTful Services e APIs
o Testing e Debugging
o Git e Version Control Systems
o Cloud computing
o Design Patterns
Desejável experiência na área de seguros

Contratação CLT
Local: São Paulo - Faria Lima
Projeto de tempo indeterminado
Envio de currículo: daniele.silva@ventron.com.br

**Comment by reginaldojunior** [comment]
Por favor, informar linguagens e mais informações na vaga.

**Comment by Dani-Ventron** [comment]
@reginaldojunior  vaga alterada, obrigada!
