### ISSUE TITLE
Desenvolvedor Back-end Python Gras Tech

### ISSUE THREAD

**Issue by GazozaApp** [backend-br/vagas#2263]
**Descrição da vaga**

Dev Back-End Pleno/Sênior Python

**Local**

Escritório, São Paulo - Próximo a Av Paulista (Trianon-MASP)

**Requisitos**

- Experiência com Python - Django e/ou Flask
- Experiência em design e arquitetura de software;
- Experiência em Cloud Computing (AWS e/ou Google Cloud);
- Experiência em softwares containers (Docker e/ou Kubernetes Engine);
- Experiência em desenvolvimento de API´s e Microserviços; 
- WebCrawlers;
- Conhecimentos em sistemas de alta disponibilidade e escalabilidade;
- Conhecimento de Banco de Dados MongoDB;

**Diferenciais**:

- projetos com aplicação de IA

**Contratação**

-PJ

**Nossa empresa**

Somos uma startup em fase inicial, já com investidor. Estamos desenvolvendo uma solução em consulta de preços de combustíveis, bem como a qualidade do combustível no abastecimento.

**Como se candidatar**

Por favor envie um email para rodrigo.u@kombux.com com seu CV anexado - enviar no assunto: Vaga Back-End

**Tempo médio de feedbacks**

Costumamos enviar feedbacks em até 04 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@kombux.com

**Alocação**

- Alocado

**Regime**

- PJ

**Nível**

- Pleno

- Sênior

**Comment by dutraleonardo** [comment]
Olá, há possibilidade de trabalho remoto?

**Comment by marcus-campos** [comment]
Olá tem disponibilidade pra remoto?
