### ISSUE TITLE
[Florianópolis SC] Desenvolvedor(a) NodeJS na Anestech

### ISSUE THREAD

**Issue by jndeus** [backend-br/vagas#2268]
**Tá de saco cheio** de ficar fazendo cardápio ou batendo código sem proposito?
Sim, você que é Back-end provavelmente está desenvolvendo um cardápio de alguma coisa: música, carros, sapatos, medicamentos, investimentos ou comida mesmo.

Quer dar um sentido diferente às suas linhas de código, ter a chance de **salvar vidas** em risco e acordar para um desafio diferente fazendo parte de um time FODA?

Você acha que aguenta o rally em uma das mais premiadas startups de saúde do Brasil, e não desmaiaria ao entrar em um centro cirúrgico?

Já ouviu falar nos “Seals da Medicina”, os anestesiologistas?

**Ficou curioso com tudo isso?** Dá uma olhada na oportunidade abaixo.

Ah! E de quebra trabalhar em Floripa. Conhece a Ilha do Silício?

**Você deve ter as seguintes qualificações:**

- Experiência no desenvolvimento de soluções Back-end;
- Familiaridade com versionamento de código.

**Requisitos:**

- Boas práticas de desenvolvimento;
- Skills nas seguintes tecnologias:
  - NodeJS;
  - Docker;
  - Git;
  - MySQL.
 
**Diferencial**
- Experiência com infraestrutura AWS;
- Experiência com GitLab;
- Linux.

**Por que trabalhar na Anestech?**
- Desenvolvimento de liderança;
- Incentivo para participação em eventos e cursos;
- Trabalhe com inovação e novas tecnologias;
- Time diverso e multidisciplinar;
- Ambiente aonde todos tem voz;
- Chopp na faixa as sexta-feiras (e as vezes durante a semana também) :beers: :beers:
- No verão beach clubs para discutir idéias em um ambiente descontraído.

**Se tiver interesse o processo seguirá da seguinte forma:**
- Você envia seu CV para talentos@anestech.com.br
- Avaliaremos com nosso time;
- e após avaliação mandaremos um teste técnico simples, para filtrar;
- e por fim, entrevista!

**Comment by luancma** [comment]
Enviado.

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Essa vaga pode ser remota? Sou do RJ. =)
Abraços!
http://danielsiqueira.net

**Comment by jndeus** [comment]
> Olá! Tudo bem?
> Essa vaga pode ser remota? Sou do RJ. =)
> Abraços!
> http://danielsiqueira.net

Infelizmente não Daniel, precisamos de alguém presencial.

**Comment by edilson** [comment]
Boa noite. Vocês aceitam candidatos de outros estados? Qual é o nível esperado dessa vaga?

**Comment by guligon90** [comment]
Boa noite. Currículo enviado.

**Comment by vinicioslc** [comment]
Qual a área de atuação ? 
Que tipo de sistemas ele irá desenvolver ? 
Quais tarefas que serão da rotina do Developer/Research ?

**Comment by jonathangaldino** [comment]
A vaga ainda está de pé?
