### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na Pareto Group

### ISSUE THREAD

**Issue by joaovcarvalho** [backend-br/vagas#227]
## Descrição da vaga

Procuramos desenvolvedor Backend para trabalhar no nosso SaaS e desenvolver API's REST em Django e Python. Possuímos um time que pratica agilidade e sempre quer evoluir. Alguns dos problemas que você possivelmente irá resolver são:

- Criação de API’s de alta disponibilidade em Python com Django ou Flask e também utilizando Java e Spring.
- Criação de infraestrutura cloud e serveless com AWS Lambda ou Google Cloud App Engine.
- Integração com serviços existentes que agreguem valor a plataforma.
- Escalar serviços existente melhorando a arquitetura e desempenho.

Somos uma empresa pequena então você pode se desenvolver em toda a nossa stack e causar impacto que todo o produto. Além disso estamos abertos para novas tecnologias.

## Local

Escritório no Rio de Janeiro - Copacabana

## Benefícios

- VR de R$ 25/dia
- VT

#### Diferenciais

- Café sempre disponível
- Mesa de Ping Pong

## Requisitos

**Obrigatórios:**
- Conhecimento em Python, Java, C# ou outra linguagem de backend. 
- Desenvolvimento web com frameworks modernas como Django, Rails, Laravel ou Express
- Banco de dados MySQL

**Desejáveis:**
- Desenvolvimento de API’s HTTP Rest.
- Conhecimentos em Django e Python
- Django Rest Framework

**Diferenciais:**
- Serviços Cloud com AWS ou Google Cloud Platform

## Contratação

CLT a combinar

## Nossa empresa

Pareto é a startup de otimização de campanhas de marketing digital e de apoio à decisão. Trabalhamos para automatizar processo repetitivos, tomar decisões automáticas baseadas em dados, desenvolver algoritmos inteligente para atuar em um mercado dinâmico. Somos Premium Partner do Google atuando fortemente com Adwords. 

Desenvolvemos o Pareto Quantic, plataforma de automatização e inteligência aplicados ao mercado de marketing digital.

## Como se candidatar

Por favor envie um email para joao.carvalho@paretogroup.com.br com seu CV anexado - enviar no assunto: Vaga Backend

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
