### ISSUE TITLE
[Remoto] Desenvolvedor Backend/Fullstack Ruby on Rails

### ISSUE THREAD

**Issue by maikelfb** [backend-br/vagas#2270]
# Sobre a Ruptiva
Somos uma empresa de Santa Catarina que atua no desenvolvimento de projetos Android, iOS e Web.

Buscamos por profissionais que gostem de desenvolvimento de software e tecnologia em geral, que estejam atentos às novidades e em constante evolução, que tenham capacidade de inovar e propor soluções, bem como facilidade de trabalhar em grupo.

Em nosso ambiente de trabalho cultivamos bons laços de relacionamento e amizade - prezamos muito pela harmonia e bem-estar de nossa equipe.

> Essa posição é para atuação em um projeto de meios de pagamento.

## Nível
- Júnior
- Pleno

## Modalidade
Remota

## Tipo de contratação
PJ

## Remuneração
Á combinar (compatível com o mercado)

## Requisitos
- Experiência de desenvolvimento Back-end com Ruby on Rails;
- Experiência em construção de APIs;
- Compromisso com prazos e qualidade; 
- Capacidade de propor soluções aos desafios do dia a dia; 
- Capacidade de autodesenvolvimento; 
- Facilidade de aprendizado; 
- Planejar, organizar e reportar atividades;
- Experiência com Git;
- Inglês (leitura e escrita).

## Como se candidatar
Por favor, envie um email para maikel@ruptiva.com com seu CV anexado, pretensão salarial e demais informações.

## Labels
- Júnior
- Pleno
- Remoto
- PJ

**Comment by zzBrunoBrito** [comment]
Olá, é uma vaga para backend e outra para fullstack?

**Comment by maikelfb** [comment]
> Olá, é uma vaga para backend e outra para fullstack?

Olá Bruno, temos oportunidades para backend e/ou fullstack.

**Comment by hemershon** [comment]
Olá, essa vaga ainda está disponível?
