### ISSUE TITLE
[Valinhos/SP] Desenvolvedor NodeJs na Kroton

### ISSUE THREAD

**Issue by fcjonas** [backend-br/vagas#2285]
A **Kroton**, uma das maiores empresas do setor de educação do país, está passsando por um forte processo de transformação digital  e planeja ser o maior grupo de edtechs do Brasil. 

Pra isso, está construindo um time de tecnologia de alto nível e está buscando um(a) Desenvolvedor(a) NodeJs para fazer parte da equipe!

Impacte a vida de milhões! Estamos transformando histórias, vidas e o futuro! Aqui, tradição e liderança não são traduzidas em modelos antigos e 'zona de conforto'. Pelo contrário. Temos em nosso DNA a invação e o dinamismo de uma jovem startup!

Agimos pensando no sucesso do aluno. Temos paixão por educar. Valorizamos as pessoas. Somos responsáveis. Fazemos acontecer. Buscamos inovação. Geramos valor sustentável e juntos, podemos mais. Nós somos a Kroton!

Quer saber um pouco mais sobre as tecnologias utilizadas e como seguir em nosso processo? 

### Você será responsável por:

- Desenvolver soluções com foco em qualidade, disponibilidade seguindo práticas Ágeis e melhores padrões de Arquitetura;
- Planejar tasks nas práticas ágeis do SCRUM
- Trabalhar em uma equipe ágil voltada a entregas realizadas com atividades de alta colaboração e autonomia;
- Analisar e resolver incidentes com mindset de melhoria contínua procurando sempre assimilar “lessons learned” visando se aprimorar para construir soluções mais resilientes;
- Codificar novas features em um fluxo de “Code Review” de forma colaborativa com outros DEVs de maior senioridade responsáveis pela revisão do código.

### O que buscamos:

- Experiência em desenvolvimento assincrono;
- Experiência em desenvolvimento com framework Express.JS;
- Desenvolvimento com webservices (SOAP e REST)
- Conhecimento em modelos ágeis utilizando Scrum e Kanban.

**Dá uma olhada na página!**  https://byintera.in/fo
**Perfil para dúvidas:** https://www.linkedin.com/in/jfcornelio/

**Comment by edilson** [comment]
Boa noite. Vocês aceitam candidatos de outros estados? Qual é o nível esperado dessa vaga?

**Comment by fcjonas** [comment]
Sim!! Para essa oportunidade, buscamos profissionais de nível JÚNIOR.

**Comment by TeijiW** [comment]
Há a possibilidade de remoto?
