### ISSUE TITLE
[São Paulo - SP] Analista Sustentação na Approvata

### ISSUE THREAD

**Issue by kvilela** [backend-br/vagas#2289]
**• Local**
São Paulo - Faria Lima

**• Requisitos**
Conhecimento em banco de dados relacional e linguagem PL/SQL.
Boa comunicação escrita e verbal.
Bom relacionamento pessoal.
Conhecimento da ferramenta Splunk para análise de logs.
Conhecimento da ferramenta Jira para gestão de incidentes (acompanhamento de SLA, priorização, relatórios).
Banco de Dados Oracle e MySQL.
Conhecimento em pagamento digital e em dispositivos de pagamentos.

**• Contratação**
PJ com 2 home office na semana

Por favor envie um e-mail para karina.vilela@approvata.com.br com seu CV anexado - enviar no assunto: Vaga Analista Sustentação

**Labels**
PJ
Junior
Pleno

**Comment by ronilsonreis** [comment]
Ola a vaga se encontra aberta?
