### ISSUE TITLE
[São Paulo] Desenvolvedor Java - Pleno e Sênior na 5A Attiva 

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#229]
**Empresa**
A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação.

**Numero de vagas** 
2 Vagas de Pleno e 2 Vagas para Sênior 

**Atividade**
Desenvolvimento de novas aplicações desenvolvidas em Java 1.8 e springboot
Manutenção em aplicações ativas que utiliza Java 1.6 e 1.7 utilizando jboss e webspheare.
Grande parte das aplicações tem testes unitários.

**Perfil Técnico**
SpringBoot, java6, java8 , Jboss, Docker, AWS, NoSQL, AngularJs, Pre-processador SAS, Integração Continua (Jenkins)

**Localidade**
Alphaville ou Morumbi

**Contratação**
Consultor 5A - PJ valor Hora

Interessados, por favor, entrar em contato através do e-mail: Helen.matos@5aattiva.com.br

Indicações são bem vindas.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
