### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby on Rails [Mooven Consulting]

### ISSUE THREAD

**Issue by gabrielgsf31** [backend-br/vagas#23]
[VAGA] Desenvolvedor Ruby on Rails

Local: São Paulo, SP
Empresa: Mooven Consulting
Salário: A combinar
Tipo de Contrato: Prestador de Serviços (PJ)

Clique no link abaixo para se candidatar:
https://www.recrutasimples.com.br/vaga/-KxIjxiuS0C9M8aT7zbO/desenvolvedor-ruby-on-rails/são-paulo-sp?referrer=github

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
