### ISSUE TITLE
[SÃO PAULO] PHP DEVELOPER na JUST DIGITAL

### ISSUE THREAD

**Issue by alicesrossi** [backend-br/vagas#2301]
## Descrição da vaga

Projeto PHP com Symfony ou Laravel, em um dos grandes clientes da Just!

## Local

200m da estação Pinheiros - SP

## Benefícios

- Plano de saúde e odontologia
- Seguro de vida
- VR de R$ 594/mês
- Frutas no escritório
- Horário flexível
- Ambiente tranquilo

## Requisitos

**Obrigatórios:**
Conhecimento em PHP;
Framework: Laravel ou Symfony;
Versionamento com GIT;
Criação e consumo de API;
CMS: Drupal ou Wordpress;

## Contratação

CLT a combinar

## Nossa empresa

Queremos mostrar ao mundo que entregar resultado para hoje e amanhã pode ser mais simples do que se imagina, mais divertido do que se espera, e inesquecível para gerar laços e conexões duradouras entre pessoas.
Agora estamos em busca de desenvolvedores apaixonados por construir produtos digitais de qualidade, que estejam atualizados com as melhores práticas e tecnologias, envolvidos e engajados com comunidades de software.
Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

## Como se candidatar

Por favor se cadastre em https://justdigitalbr.recruitee.com/o/dev-back-end-pleno-1

**IMPORTANTE:** Ressaltamos que, por conta do novo COVID-19, todas os nossos processos estão sendo feitos remotamente, a fim de diminuir a curva de propagação do vírus. Obrigada! 

### Alocação:
- Presencial
- Flexível (Remoto parcial)
- Home offices

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by levicosta201** [comment]
Que vaagaa dahora me candidatei!!
