### ISSUE TITLE
[Remoto] Back-end Developer Python - Django (Flask API) na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [backend-br/vagas#2304]
Hello,

Joyjet is looking for a back-end developer in Python using Django. We have a lot of different projects from e-commerce to interns app for businesses.

We will be using frameworks based on Python. And Fast or Flask API.

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Local
Remoto

## Benefícios
Plano de saúde
Free course to study

## Requisitos obrigatórios:
- 3 years of experience as a back-end developer
- Python
- HTML/CSS
- GIT
- Django Framework

## Desejáveis:
- React Js

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA BACK-END Python

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/backend/

## Labels
PJ
Pleno
Remoto
Python
Django

**Comment by PachecoRaphael** [comment]
We received enough test to check for now, thanks for all candidates! We will review them asap to come back to you and if you still didn´t send it plz consider doing so by the end of this week maximum. Thanks

**Comment by rodrigocardosodev** [comment]
Hi @PachecoRaphael, how are you?

Well, I didn't understand about the above process, should I send the curriculum first and then take the test? Or take the test and then send the curriculum? Or all at the same time?

It sounds like a silly question, but I hope you will understand my doubt.

**Comment by PachecoRaphael** [comment]
> Hi @PachecoRaphael, how are you?
> 
> Well, I didn't understand about the above process, should I send the curriculum first and then take the test? Or take the test and then send the curriculum? Or all at the same time?
> 
> It sounds like a silly question, but I hope you will understand my doubt.

Hey Rodrigo, 

You can send me your CV so I can check it first and then if all good for me you can do the test. No problem, it´s better to ask ! There are no silly questions.
