### ISSUE TITLE
[Porto Alegre] Desenvolvedor (a) Java Pleno/Sênior na South System

### ISSUE THREAD

**Issue by AmandaElena** [backend-br/vagas#2306]
A SOUTH SYSTEM está em busca de um desenvolvedor Java que faça parte do nosso objetivo de impulsionar as pessoas para inovar o mundo. Para fazer parte do tempo, há algumas habilidades que valorizam muito, e não estamos falando apenas de tecnologia, que valorizamos profissionais que respeitem ou que sejam próximas e suas diferenças, que sejam leais e responsáveis ​​com entregas e com pessoas. A colaboração e o engajamento devem fazer parte do dia para que o resultado seja eficaz e ter a sede de aprendizado para trabalhar com inovação contínua.

**Nessa oportunidade, o profissional trabalhará com:**
- Desenvolvimento e manutenção de soluções corporativas;
- Compromisso com entrega e qualidade do código;
- Escrita e manutenção de testes unitários;
- Esclarecer dúvidas de colegas com menor antiguidade;
- Suporte e correção de bugs.
- Desenvolvimento de APIs RESTful e micro serviços com Springboot;
- Arquitetura de microserviços;
- Boas práticas de desenvolvimento;
- Metodologias ágeis;
- Java e Springboot
- JSON / REST;
- Banco de dados NoSQL (MongoDB) e banco de dados relacionais (Oracle);
- Mensageria com RabbitMQ;
- GIT;
- Padrões de design;
- OpenAPI / Swagger.

**Será um diferencial bacana:**
- Conhecimentos em SOAP;
- Conhecimento em Spring batch;
- Conhecimento em OpenShift;
- Conhecimento em MariaDB;
- Conhecimento em Graylog;
- Conhecimento em Bitbucket;
- Conhecimento em Jira;
- Conhecimento em Confluence;
- Conhecimento em Jenkins;
- Conhecimento em Artefato;
- Conhecimento em Postman.

**Modo de Contratação** 
- PJ 
- Cooperado 

**Localização**
- Presencial em Porto Alegre-RS

**Labels**
Presencial - Porto Alegre RS;
-PJ ou Cooperado;
- Arquitetura de microserviços;
-Java e Springboot;

**Comment by Jose-Robert** [comment]
Tem algum email para enviar o currículo?

**Comment by AmandaElena** [comment]
Opa claro!! Erro meu, desculpa haha
amanda.almeida@southsystem.com.br
