### ISSUE TITLE
Desenvolvedora BackEnd

### ISSUE THREAD

**Issue by natalia-sborges** [backend-br/vagas#2307]
A Cora está nascendo, e precisa de você para construir um novo banco.

É tudo do zero! Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano
.
Procuramos uma Engenheira de Software Back End, com pelo menos 4 anos atuando na área e com um bom conhecimento em linguagens especificas como Java, Kotlin e Go, e conhecimentos avançados em linguagens orientadas a objeto.
.
Para mais informações, acesse a página da vaga: https://byintera.in/gh

**Comment by f0ntana** [comment]
Somente para mulheres?
