### ISSUE TITLE
[São Paulo] Tech Lead Python (CTO) - Promo de Bolso 

### ISSUE THREAD

**Issue by Almanake** [backend-br/vagas#231]
## Descrição da vaga

A Promo de Bolso é uma startup de tecnologia em crescimento e que está buscando seu CTO (atualmente essa posição é realizada pelo fundador da empresa, que passará a se focar 100% na área Comercial).
Irá atuar com desenvolvimento em linguagem Python, ambiente Google (ex: Google Cloud), Banco de Dados SQL e NoSQL. 
Buscamos profissionais com espírito empreendedor e com vontade real de crescer junto com o negócio. 

## Local

Escritório, São Paulo - Pinheiros (Metrô Fradique Coutinho)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- Plano Odontológico
- VT

#### Diferenciais

- Possibilidade de stock options (irá crescer junto!)
- Oportunidade para atuar como CTO (não exigimos "experiência em carteira")
- ambiente descontraído e horário flexível

## Requisitos

**Obrigatórios:**
- Ter experiência em gestão de times (mesmo se for como liderança técnica)
- Ter visão de negócios e acreditar na nossa ideia
- Ter experiência com arquitetura de sistemas e infra SAAS

**Desejáveis:**
- conhecimentos em Python (é a nossa linguagem principal, porém, não estamos fechados a profissionais com expertise em outras linguagens)
- conhecimento em ambiente e infra Google (ex: Google Cloud)

**Diferenciais:**
- Ter atuado em startup ou empreendido previamente

## Contratação

Cooperado a combinar

## Nossa empresa

PROMO DE BOLSO É UMA STARTUP DE TECNOLOGIA COM UMA REGRA CLARA: COLOCAR EM CAMPO PROMOÇÕES CAMPEÃS!
A Promo de Bolso é especializada em portifólio de promoções, atuando com grandes marcas e produtos através de Hotsites, SMS e Apps. A empresa está em seu terceiro ano de atuação e crescendo! Atualmente o time é formado por 9 profissionais (4 deles de Tecnologia). 

## Como se candidatar

Quem tiver interesse, favor enviar CV ou perfil do LinkedIn para vieira@talentu.com.br

## Labels

- CTO
- Cooperado
- Sênior
- Python

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
