### ISSUE TITLE
[São Paulo] Dev. FullStack PHP

### ISSUE THREAD

**Issue by mattfreitas** [backend-br/vagas#2311]
Fala devs!

Tenho disponível 2 vagas para devs, uma **full-stack** e a outra **back-end**.

**Quem somos:**
Nós somos a Edulabzz, um laboratório de inovação educacional. Facilitamos e solucionamos problemas na área de educação fornecendo plataformas que estimulam o aprendizado a distância para instituições e empresas de todos os tamanhos. 

**Nossas tecnologias:**
- Laravel
- MariaDB (MySQL)
- HTML/CSS/JS (jQuery)

No futuro iremos migrar para uma biblioteca (React ou VueJS) e temos alguns projetinhos em Node (não é requisito pra essa vaga).

**Sobre o trampo:**

- Presencial (estamos na Rua Joaquim Floriano, 466)
- Nível Pleno ou Senior
- Salário de 4k a 8k, PJ.
- Estamos em home-office durante esse período do surto de corona-vírus.

Pra de candidatar é só enviar o email **com a sua pretensão salarial** e currículo para:
matheus.freitas@edulabzz.com.br

**Comment by MoraesGil** [comment]
https://www.linkedin.com/in/moraesgil/
