### ISSUE TITLE
Backend Developer Movile Group - iFood, Sympla, PlayKids, Wavy

### ISSUE THREAD

**Issue by MovileGente** [backend-br/vagas#232]
Como Desenvolvedor Backend, você fará parte de times focados no desenvolvimentos e manutenção de aplicações e sistemas com diferentes níveis de escalabilidade, sustentabilidade e tolerância a falhas.

Ao se increver nessa vaga, você será avaliado pelo time da Movile e, se atender aos requisitos necessários, ficará em destaque para os times de RH das 10 empresas do grupo.

**O que valorizamos no Grupo Movile?**

- Senso de dono: gostamos de pessoas que se apropriam dos projetos e fazem o melhor;
- Hands-on: porque colocar a mão na massa é essencial;
- Foco em resultado: pois é assim que impactamos verdadeiramente a vida das pessoas;
- Inovação: precisamos mudar o jeito que as coisas acontecem;
- Apaixonadas pelo que fazemos e pelos nossos sonhos.

**Responsabilidades e atribuições:**

- Compreender os problemas sistêmicos e ajudar na construção de soluções;
- Ser capaz de criar soluções pragmáticas de software, onde os recursos são rapidamente entregues sem sacrificar a qualidade do código;
- Ajudar no desenvolvimento de APIs RESTful internas e públicas;
- Apoiar o rastreamento de métricas do produto através do desenvolvimento de ferramentas ou condução integração com as existentes.

**Requisitos e qualificações:

Essenciais:**

- Experiência na construção de aplicações escaláveis, de alto desempenho e tolerantes a falhas;
- Experiência com arquiteturas de microserviços;
- Sólida experiência com Java;
- Experiência em construção e integração com APIs RESTful;
- Conhecimento em frameworks Java populares (Ex: Spring);
- Experiência com bancos de dados relacionais e não-relacionais (Ex: PostgreSQL, Cassandra, Redis);
- 

**Diferenciais:**

Conhecimento em tecnologias de cache.
Experiência com ferramentas de compilação em servidores Maven e CI, como Jenkins.

**Local**
Presencial. Local do escritório dependerá da empresa, mas estamos presentes em São Paulo, Campinas e Belo Horizonte.

**Benefícios**

- Plano de saúde
- Seguro de vida
- VR compatível com o local do escritório
- VT
- Férias
- Possibilidade de home office
- Investimento em capacitação
- E outros diversos que são específicos de algumas empresa do Grupo (ex: GymPass, Plano odontológico, vale cultura)

**Diferenciais**

- Horário flexível
- Ambiente amigável e descontraído
- Times talentosos
- Produtos e tecnologia de ponta
- Espaço para inovação e tentativas
- Oportunidade para desenvolvimento e crescimento profissional
- Snacks liberados no escritório
- Cerveja sempre à disposição
- Muito café (máquina e coador)

**Nossa empresa**
A Movile é líder em marketplaces móveis, e tem como grande sonho tornar a vida de 1 bilhão de pessoas melhor através de seus aplicativos. Atualmente trabalhamos com negócios e empresas em 4 pilares, que são: Food (iFood), Tickets (Sympla), Education & Care (PlayKids, SuperPlayer e Wavy) e Rapiddo (Marketplace, Payments e Entregas). Já estamos presentes no Brasil, Estados Unidos, França, México, Colômbia, Peru e Argentina, e somamos mais de 100 milhões de usuários ativos mensalmente. Com 1600 funcionários apaixonados pelo mesmo sonho, empoderados a construir novos negócios com potencial global e motivados a tomarem riscos.

A tecnologia é o nosso core, estamos formando times que criem e desenvolvam produtos incríveis para impactar e melhorar diretamente a vida das pessoas. Nossa stack é totalmente diversificada, contamos com tecnologias e linguagens diversas para termos a liberdade de sempre aplicar o que fizer mais sentido para determinado projetos. Gostamos de inovar, de aplicar ideias diferenciadas, de mudar produtos e de criar coisas realmente grandes e escaláveis.

**Como se candidatar**
Basta [clicar aqui](https://jobs.kenoby.com/movile/job/backend-developer-movile-group/5af21bb7c64da16838105392?utm_source=Linkedin) e preencher a inscrição.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
