### ISSUE TITLE
 [Porto Alegre] Node Developer SouthSystem

### ISSUE THREAD

**Issue by AlineLarruscaim** [backend-br/vagas#2324]
### Vaga para atuar em Porto Alegre

> Descrição da vaga:
A SOUTH SYSTEM está em busca de um(a) Desenvolvedor(a) Node que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

Conhecimentos:
Amplo conhecimento em NodeJS e frameworks.

Desejável:
Conhecimento em meios de pagamento;
Vivência em projetos do mercado financeiro.

> Contrato Cooperado ou PJ

> Nível da vaga: PLENO/SÊNIOR 

## Interessado encaminhar o currículo para: aline.larruscaim@southsystem.com.br

**Comment by GabrielLinss** [comment]
Aceita remoto ?
