### ISSUE TITLE
[REMOTO ou São Paulo] Back-end Developer (qualquer nível) na Simbiose Ventures

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#2331]
## O que buscamos
Desenvolvedores back-end com qualquer nível de experiência em programação (em qualquer linguagem). As vagas são para aqueles que ainda estão iniciando e também para os que já se consideram sênior. Se você já está trabalhando mas possui pelo menos 4 horas "livres" por dia (seg a sex), também poderá se candidatar para trabalhar "part-time" conosco.

**Não selecionaremos as pessoas com base no nível de conhecimento técnico**.

## Trabalho
Nosso trabalho é criar plataformas de gestão, processamento e armazenamento de dados em larga escala. Bilhões de requisições por dia. Nossos sistemas são criados para serem utilizados por outras empresas (pequenas, médias e grandes), visando analisarem seus dados e/ou criarem seus próprios produtos.
Nossos repositórios internos somam mais de 1 milhão de linhas de código, sendo 40% em Java, 50% Python, 5% C, 5% JavaScript. Temos CI implementado e seguimos ao máximo o modelo TDD.

## Remuneração
Nosso plano de remuneração varia de acordo com a quantidade de horas que você deseja trabalhar. 
O valor base é de R$ 1.200,00 por mês para quem trabalha apenas 4 horas por dia, podendo chegar até R$ 17.500,00 para quem trabalha (em média) 12 horas por dia.

## Empresa
Você consegue saber mais sobre a Simbiose acessando o [nosso site](https://www.simbioseventures.com) ou assistindo ao vídeo abaixo.

[![Equipe Simbiose](https://i.imgur.com/5gzqKDC.png)](https://www.youtube.com/watch?v=71Gdag1CnSU)

## Como se candidatar
Basta acessar o link abaixo e seguir os procedimentos indicados.

[Como fazer parte da Simbiose](https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose)

## Vagas
Temos mais de 20 vagas abertas para desenvolvedores back-end, front-end, testers e DevOps/SysAdmin.

Qualquer dúvida, estamos à inteira disposição.

Muito obrigado!

**Comment by leopedroso45** [comment]
Opa, tudo bem?
Então, em Maio de 2019 eu tive uma entrevista com vocês e não obtive feedback desde então (da pra entender que não consegui a vaga haha), a dúvida é: posso submeter novamente?

**Comment by gmenegatti** [comment]
Olá @leopedroso45 

Peço sinceras desculpas por você não ter obtido um feedback. Esse não é nosso procedimento padrão, muito menos a forma como tratamos as pessoas. Novamente, me desculpe.

Claro, pode se inscrever novamente. :-)

**Comment by GuilhermeLis** [comment]
Até quando o processo seletivo estará aberto?

**Comment by gmenegatti** [comment]
Olá, @GuilhermeLis, ainda não temos um prazo limite para término, mas acredito que ficará aberto até o fim de Abril.

**Comment by Claudio-code** [comment]
Já me candidatei

**Comment by felipebc11** [comment]
Bom dia, Gabriel. Tudo bem? Fiz a inscrição no dia 13, quanto tempo leva em média para obter feedback? @gmenegatti

**Comment by felipebc11** [comment]
@gmenegatti

**Comment by JosephSousa** [comment]
@gmenegatti me inscrevi a mais de uma semana, vocês fornecem feedback, mesmo após a inscrição na primeira etapa?

**Comment by Henriquepb22** [comment]
Faz 1 ano que espero meu feedback e olha que eu cheguei até a etapa final da seleção

**Comment by gmenegatti** [comment]
@felipebc11 @JosephSousa, já começamos a fase de entrevistas. Apenas entre hoje e amanhã estamos nos reunindo com mais de 40 pessoas e continuaremos na próxima semana. Felizmente foram mais de 250 pessoas inscritas até o momento, então a resposta vai demorar um pouco. Algumas pessoas já receberam nosso retorno "negativo" por conta do inglês e matemática.

@Henriquepb22, deve haver algum engano, pois no dia 16 de Agosto de 2019 nós conversamos por Hangouts e no dia 18 de Agosto (segunda-feira) eu enviei um email informando que infelizmente não seguiríamos em frente naquele momento.

**Comment by felipebc11** [comment]
Muito obrigado @gmenegatti

**Comment by Claudio-code** [comment]
Boa tarde to esperando ansiosamente a entrevista.

**Comment by FernandaNascimento26** [comment]
Passei hoje pela fase da entrevista e gostei das perguntas, estou cheia de expectativas positivas, aguardando o feedback :100:

**Comment by gmenegatti** [comment]
Nós também gostamos muito da conversa com você @FernandaNascimento26. Nos falamos em breve. :-)

**Comment by luizfeliperodrigues** [comment]
@gmenegatti ainda da tempo?? Agradeço, de qualquer forma.

**Comment by andremoriya** [comment]
> @gmenegatti ainda da tempo?? Agradeço, de qualquer forma.

Também gostaria de saber.

**Comment by gmenegatti** [comment]
Olá, @luizfeliperodrigues @andremoriya, tudo bem? Peço desculpas pela demora.

Preciso ser sincero e honesto com vocês: nós recebemos muito mais inscritos/candidatos to que temos capacidade de contratar nesse momento.

Foram mais de 300 pessoas e nós já conversamos com pelo menos 80, mas tem **muita** gente boa nesse grupo. É possível que façamos a maior contratação da nossa história.

Isso posto, é claro que vocês podem (e devem) se inscrever, pois assim que a Simbiose precisar contratar mais, olharemos primeiro para as pessoas que se inscreveram e ainda não foram "entrevistadas".

Muito obrigado pelo interesse e também pela compreensão.

Qualquer dúvida, meu email é: gabriel@simbioseventures.com

**Comment by gmenegatti** [comment]
Estou (felizmente) fechando essa vaga/issue por conta do volume de inscrições.

Todos que se inscreveram receberão um retorno até, no máximo, amanhã (sexta-feira).

**Comment by andremoriya** [comment]
Muito obrigado pelo retorno @gmenegatti
