### ISSUE TITLE
[São Paulo] Back-End Pleno/Sênior no LuizaLabs - Magazine Luiza

### ISSUE THREAD

**Issue by erikhenrique** [backend-br/vagas#234]
Procuramos pessoas apaixonadas por resolver problemas através da tecnologia encarando desafios com naturalidade e sem medo de experimentar e arriscar - mas com responsabilidade e motivação para inovar em um mercado dinâmico e em constante mudança.

Nossas equipes tem um perfil colaborativo, com pouca formalidade e hierarquia, e convivemos com pessoas inteligentes, simples e super competentes, que se apóiam, aprendem e também se divertem fazendo aquilo que acreditam.

Incentivamos experimentação e ganho de escala e autonomia com responsabilidade.

Buscamos pessoas que queiram fazer parte do nosso time no escritório de São Paulo e que sejam apaixonados por construir sistemas distribuídos e aplicações de alta performance; que estejam dispostos a fazer experimentações em larga escala e utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

## Requisitos

Nossos requisitos são que você tenha alguma experiência trabalhando com sistemas - pequenos ou grandes - e que você tenha domínio de pelo menos uma linguagem de programação, independente de qual seja ela - C#, Java, Python, GO, Clojure, Node, Scala, tanto faz, não temos preconceitos ou requisitos sobre alguma linguagem específica. Nós valorizamos pessoas capazes de aprender e evoluir, que sejam críticas em relação a qualidade e desempenho independentemente do seu background profissional. Queremos que você se junte a nossa equipe e faça parte da construção da nossa cultura.

## Local

Rua Maria Prestes Maia, 300, 6º andar - Vila Guilherme

**Ao lado do Metro Portuguesa - Tietê, linha Azul do Metro**

## Benefícios

- Vale Refeição
- Seguro de Vida
- Previdência Privada
- Bolsa Auxílio
- Assist. Odontológica
- Assist. Médica
- 13ª Bolsa Auxílio

# INSCREVA-SE

[![apply_button](https://user-images.githubusercontent.com/1441720/40622917-459dca86-627a-11e8-8206-331bdeaa5ecf.png)](https://www.99jobs.com/luizalabs/jobs/20380-desenvolvedor-backend-pleno-senior-tribo-marketplace)

**Comment by erikhenrique** [comment]
Vaga ainda está aberta :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
