### ISSUE TITLE
[SÃO PAULO] Desenvolvedor JAVA | Qintess

### ISSUE THREAD

**Issue by helenazandona** [backend-br/vagas#2344]
**Desenvolvedor JAVA** 

**Conheça a Qintess**

O Mundo é ágil e nos cobra agilidade!
Para vencer, a questão não é sobre atingir limites mas sim em se destacar em meio a padrões vigentes. Isto depende do quanto estamos dispostos a provocar as estruturas atuais para testar o novo, para inovar.

As organizações criam o futuro através da visão e da estratégia que perseguem, experimentando e se desafiando a criar novos patamares de valor para seus mercados. É isto que nos inspira.

Acreditamos que inovação é, antes de tudo, uma atitude. Decidir, surpreender, testar e implantar novas realidades e redefinir o futuro. Queremos criar ideias que transformem pessoas e, assim, impulsionar as pessoas a transformar o mundo.

**O que buscamos:**
Java +8
Sprint Boot
Metodologia Ágil
Sql Server ou Oracle
Fila (Rabbit MQ), 
TDD

**Enviar currículo; rosangela.rodrigues@qintess.com**

**Comment by walterfjustino** [comment]
Tem vaga de nível Júnior?

Att.Walter
