### ISSUE TITLE
[RIO DE JANEIRO]  Back-End Developer na Ame Digital

### ISSUE THREAD

**Issue by marcelleanselmo** [backend-br/vagas#2346]
Quer trabalhar na **Ame Digital** com a gente? Então se liga nessa vaga de **Desenvolvedor Back-End!**

**Não temos uma linguagem preferida** e estamos sempre dispostos a experimentar. Hoje temos códigos escritos, principalmente, em NodeJS, mas também em Java, Groovy, PHP, Go e Kotlin. 

Se você domina alguma dessas linguagens ou alguma outra linguagem de programação, corre e se inscreve no link abaixo:
https://grnh.se/42c472fb2us

Vem pra Ame! :)

**Comment by allbarbos** [comment]
Aceita remoto?
