### ISSUE TITLE
[Rio de Janeiro] - DESENVOLVEDOR(A) Python ou GO na Globo.com

### ISSUE THREAD

**Issue by moura** [backend-br/vagas#235]
Esta posição é para trabalhar no time de desenvolvimento que cuida da plataforma de cadastro de usuários. A plataforma trata de tudo relacionado a autenticação e autorização dos usuários da Globo.com.

As atribuições desse papel vão desde o discovery, design, arquitetura, implementação, deploy, testes automatizados e manutenção de sistemas, à discussões de produto e de qual é a melhor solução técnica. Você vai trabalhar, no seu dia-a-dia, com o desenvolvimento de APIs REST, ferramentas para melhoria do processo de desenvolvimento, sempre buscando a alta disponibilidade e escalabilidade. Atuando dentro de um time multi-disciplinar, junto com vários outros analistas desenvolvedores, a tendência é que você também execute outras tarefas além dessas, dependendo do momento de cada projeto.

Esta vaga é para o nosso escritório no Rio de Janeiro, Barra da Tijuca, porém submissões de todo o Brasil são aceitas. A globo.com entende as dificuldades de mudança de cidade, e nós oferecemos um pacote de benefícios especial para pessoas de fora do estado.

Somos uma empresa que reconhece a importância da igualdade de oportunidades. O respeito ao outro, a valorização da diversidade e a convicção de que todos dependem de todos são componentes essenciais da nossa identidade.
 
**Nosso stack de tecnologias:**

Temos sistemas escritos em Go, Python, Java e Scala. HTML5, CSS e Javascript também fazem parte do nosso dia-a-dia. Todo o nosso ambiente de desenvolvimento e produção é fundamentado em cima de tecnologias open-source, começando pelo SO, Linux. Os times têm autonomia para escolher as tecnologias que julgarem mais adequadas para resolver cada problema, então com certeza temos muito mais coisas envolvidas nessa equação.
 
**Perfil desejado:**
		
- Ser apaixonada(o) por desenvolvimento e tecnologia;
- Ter experiência profissional com Go e/ou Python;
- Ter experiência com MongoDB e também com bancos de dados relacionais;
- Ter facilidade de trabalhar dentro de times multi-disciplinares;
- Ter boa capacidade de abstração;
- Escrever código limpo e legível para pessoas;
- Conhecimentos de desenvolvimento Web (HTML, CSS, Javascript, Angular.JS, etc);
- Conhecimentos de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
- Conhecimentos de testes unitários, de aceitação, mocks, Selenium, etc; 

**Diferenciais:**

- Conhecimentos de automação de deploy e gestão de configuração;
- Experiência com métodos ágeis (Scrum, Kanban, Lean, etc);
- Experiência em mentoring/coaching de pares e team members menos experientes;

**Tipo de contratação:** CLT

Se você se encaixa total ou parcialmente nesse perfil, [entre em contato conosco](https://talentos.globo.com/#/oportunidades/globo-id-desenvolvedor-a-de-software-rio-de-janeiro/mp0hdmu).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
