### ISSUE TITLE
São Paulo - BACK END Pleno, Sênior e Especialista - RADAR Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#236]
Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência em análise de requisitos, modelagem, desenvolvimento e testes de aplicações Java;
•	Experiência no desenvolvimento de APIs REST e arquitetura de micro-serviços;
•	Conhecimento em SQL e bancos de dados relacionais e No-SQL (Cassandra, ElasticSearch); 
•	Experiência em tecnologias Spring Boot/Data/Cloud, JPA, Hibernate e metodologias ágeis; 
•	Conhecimento em ferramentas de controle de versão (Git) e em ferramentas de Integração Contínua e com Sistema Operacional Linux.

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.
Local: São Paulo/SP – Zona Sul 
Interessados: Enviar CV para cristiane@radarprofissional.com.br com sua pretensão Salarial.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
