### ISSUE TITLE
[Rio do Sul/SC] Back-End: Node JS na Riderize

### ISSUE THREAD

**Issue by fabriciosautner** [backend-br/vagas#2369]
## Nossa empresa

O Riderize é a concepção de um App para um nicho de mercado que é atendido por uma grande indústria nacional dona do projeto.

## Descrição da vaga

Desenvolver em Node JS para um App Mobile.

## Local

Escritório em Rio do Sul - Santa Catarina 

## Requisitos

**Obrigatórios:**
- Estar familiarizado com linguagens de programação 

**Desejáveis:**
- Estar familiarizado com Node JS (Stacks JS)

**Diferenciais:**
- Ter realizado o curso da Rocketseat

**Diferenciais:**
- Horário relativamente flexível, principalmente o almoço.
- Trabalhar com MacOS :D 
- Ambiente de trabalho moderno e descontraído
- Autonomia de desenvolvimento

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para fabricio.sautner@carrodemola.com.br com seu interesse para marcar uma Call de entrevista

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado Físicamente

#### Regime
- PJ

#### Nível
- Júnior em diante (vagas para ambos)

**Comment by tiago123456789** [comment]
Existe possibilidade de remoto?

**Comment by fabriciosautner** [comment]
Oi @tiago123456789 !

Queremos formar um time focado num só objetivo e portanto focamos nas vagas presenciais.

**Comment by guilhermeoa07** [comment]
Tem auxilio mudança?

**Comment by fabriciosautner** [comment]
Olá @guilhermeoa07 ,

Sim, mas não tem um valor definido, vai depender do caso a caso entendes?

**Comment by fabriciosautner** [comment]
Processo encerrado.
