### ISSUE TITLE
[Salvador] Back-end Developer na Cubos Tecnologia

### ISSUE THREAD

**Issue by beatriz407** [backend-br/vagas#2370]
## Nossa empresa

A Cubos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda.

## Descrição da vaga

- Participar ativamente nas etapas de ideação, planejamento e desenvolvimento dos produtos dos nossos clientes;
- Participar de discussão das tecnologias que serão utilizadas nos projetos;
- Criar endpoints de APIs que serão consumidas por desenvolvedores web, android e iOS. Seja amigo deles! :p
- Compreender as ferramentas que usa em um contexto DevOps, sendo capaz, em situações problemáticas, de desenvolver um raciocinio lógico consistente para investigar e resolver o problema;
- Disposição para ajudar e compartilhar conhecimento;
- Ser curioso e estar disposto a se arriscar em novas tecnologias.

### Nossa Stack Backend 

- Node.js
- Typescript
- GraphQL, 
- Redis, 
- Docker, 
- Kubernetes, 
- gRPC
- Postgres
- GitLab CI

## Local

Escritório, Salvador - Caminho das Árvores. Por conta do Coronavírus, o trabalho será remoto até que a situação seja normalizada.

## Requisitos

**Obrigatórios:**

- Experiência com Javascript;
- Conhecimento de web server (REST, RPC, graphQL);
- Saber debbugar o código;
- Dominar alguma linguagem;
- Conhecimento básico de Bash;

**Esperado:**

- Domínio de Javascript (NodeJs);
- Conhecimento de tipos de teste;
- Conhecimento de Design Patterns;
- Noção de CI/CD;
- Saber documentar;
- Saber tratar erros e falhas.

## Benefícios

- Vale refeição ou alimentação (R$ 26,00 por dia);
- Plano de saúde;
- Plano odontológico.

**Diferenciais:**

- Happy hour mensal;﻿
- Aulas semanais multidisciplinares.

## Contratação

CLT

## Como se candidatar

Se inscreva em: https://bit.ly/vempracubos

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 8 dias após cada processo.

#### Alocação
- Salvador

#### Regime
- CLT

#### Nível
- Júnior

**Comment by TeijiW** [comment]
Existe a possibilidade de remoto?

**Comment by droliv** [comment]
Estou recebendo esta mensagem de erro no formulário:

"You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. Learn More."

**Comment by edilson** [comment]
Aceita candidatura de pessoas de outros estados? Eu também tô tendo o mesmo erro da @droliv.

**Comment by beatriz407** [comment]
Foi corrigido, podem dar uma olhada ;)

> Estou recebendo esta mensagem de erro no formulário:
> 
> "You need permission
> This form can only be viewed by users in the owner's organization.
> 
> Try contacting the owner of the form if you think this is a mistake. Learn More."

**Comment by beatriz407** [comment]
> Existe a possibilidade de remoto?

Inicialmente o trabalho é remoto, mas quando as coisas forem normalizadas voltará a ser presencial e em Salvador.
