### ISSUE TITLE
[São Paulo-SP] SRE Jr e Pleno | Itaú-Unibanco

### ISSUE THREAD

**Issue by nathaliaambrosio** [backend-br/vagas#2371]
## Local de trabalho:
Mooca, São Paulo – SP.

## Empresa
Somos o maior conglomerado financeiro do Hemisfério Sul e no final do ano passado ficamos no décimo quarto lugar na lista de bancos do mundo de maior valor (por capitalização de mercado). Para acelerarmos nossa evolução, já embarcamos em uma jornada de **Site Reliability Engineering (SRE)**, inspirado nas práticas da Google, para garantir cada vez mais confiabilidade e alavancar a qualidade dos nossos produtos.

Quer fazer parte do time que define e implementa SRE para o banco? Quer impulsionar nossa transformação? Então não há um momento melhor para estar conosco!

Temos vagas de júnior e pleno.

## Principais atividades
No time temos 2 funções: **System Engineer e Software Engineer** (se tiver experiencia hibrida você também será muito bem-vindo!)

Software Engineer:
- Linguagens de programação
- Integração de Sistemas
- Design Patterns
- Tracing, Logs, Métricas
- Debugging

System Engineer:
- Sistemas operacionais
- Automação
- Arquitetura e performance de sistemas distribuídos

## Benefícios
•	Plano de saúde
•	Seguro de vida
•	VR, VA
•	Auxílio creche
•	Bolsa-auxílio
•	PLR
•	Diversas parcerias com descontos para universidades, produtos, serviços, etc.
Diferenciais
•	Dress code leve
•	Horário flexível (podemos combinar sempre que necessário)
•	Trabalhar em soluções que impactam milhões de pessoas ;)

## Contratação ✍ 

CLT / Salário a combinar.
Como se candidatar
Por favor envie um e-mail para laise.pikunas@beit.work com seu CV anexado - enviar no assunto: Vaga SRE

**Comment by edilson** [comment]
Aceita candidaturas de pessoas de outros estados?

**Comment by nathaliaambrosio** [comment]
Aceita sim!

**Comment by nathaliaambrosio** [comment]
Ainda possuímos uma vaga em aberto!
