### ISSUE TITLE
[São Paulo-SP] Java Developer SR | Sciensa

### ISSUE THREAD

**Issue by mari-recruiter** [backend-br/vagas#2380]
### Local de Trabalho
**Rua Augusta**, Jardins

### Empresa:
A Sciensa construiu um novo formato de trabalho, trazendo o time do cliente para trabalhar conjuntamente em seu Produto Digital, abrindo um espaço de Co-Working e agregando nosso time de engenheiros, transformando a cultura e modo de como pensam em Software. Somos uma Aceleradora do Mindset Digital, que está auxiliando uma série de companhias a se reinventarem, criando novas Stream Lines de negócios, expandindo exponencialmente suas oportunidades.

### Responsabilidades:
- Participar na ideação e construção de um produto digital com nosso cliente
- Entender no detalhe todo o escopo de suas atividades
- Realizar documentação mínima como diagramas de arquitetura, documentos de README etc
- Entregar software de qualidade

### Requisitos:

- Experiência profissional com Java 7/8
- Experiência profissional com SpringBoot
- Experiência profissional com Banco de Dados Mongo DB
- Experiência profissional com APIs (REST / SOAP)
- Experiência profissional com Hábito de escrever testes (Unitários, Integrados, Aceitação)
- Experiência profissional com GIT

### Contratação:
- PJ (valor/hora aberta)
- Ajuda de Custo
- 15 dias de férias remunerada após um ano
- Home Office

### Para se candidatar: 
https://vemprasciensa.gupy.io/jobs/237887

**Comment by andremoriya** [comment]
Olá boa tarde.
Só para informar que a URL não está redirecionamento para o site.

[Java Back-End Developer
](https://jobs.lever.co/sciensa/13a994b2-3f4f-47ab-b19e-a39b49bcb25f)

Adicionei o redirecionamento para o site.

**Comment by mari-recruiter** [comment]
```
Oi, André.
Peço desculpa pelo inconveniente, acho que agora deu certo.
```
