### ISSUE TITLE
[Florianópolis/SC | Remoto] Back-end JR na Reviewr

### ISSUE THREAD

**Issue by leonardorifeli** [backend-br/vagas#2381]
# Sobre a Reviewr

Cada vez mais pessoas estão utilizando as avaliações online (reviews) para decidir os serviços e produtos que vão adquirir. Com a Reviewr as empresas passam a controlar e utilizar essa inteligência à favor do próprio negócio, potencializando os resultados, melhorando a reputação online de forma rápida e eficiente, abrindo vantagem sobre os concorrentes e transformando os seus clientes em embaixadores da sua marca.

Somos uma empresa de base tecnológica, mais conhecida como uma “startup”. Nossa plataforma oferece a consolidação de todas as plataformas de Reviews e através dela somos capazes de aumentar o rendimento de qualquer negócio.

Temos apenas dois anos de operação e neste pouco tempo já conquistamos milestones importantíssimos! Já possuímos grandes clientes, ARR relevante, já recebemos rodada de investimentos da Darwin Startups (eleita melhor aceleradora do Brasil), estamos incubados no MIDITEC (5ª melhor incubadora do mundo) e seguimos como uma das startups mais quentes para se trabalhar em Florianópolis. Nossa sede fica no Rio Tavares, um dos bairros mais descolados de Floripa, numa casa super astral, perto de vários restaurantes bacanas e comércio local, onde alinhamos trabalho com qualidade de vida.

# Atividade da vaga

- Atuar no time de Basal (base do produto; resolução de bugs, demandas extras, etc);
- Desenvolver e manter código back-end de APIS;
- Desenvolver e manter código de crawlers e scrapings;
- Dar manutenção em features existentes;
- Auxiliar outros times (como CS) na scriptação de fluxos e automatizações.

# Requisitos

- Desenvolver e manter códigos: estáveis, confiáveis, elegantes e, não menos importante, fáceis de manter;
- Desenvolver soluções sempre pensando em eficiência, escalabilidade, disponibilidade, performance e estabilidade. Queremos garantir nosso crescimento super acelerado e um software escalável de maneira econômica (do more with less);
- Conhecimento básico em pelo menos uma linguagem de programação (preferencialmente javascript);
- Utilizamos principalmente Javascript. Ter facilidade para aprender rápido outras linguagens, nós ajudamos você;
- Experiência na resolução de bugs e chamados de clientes;
- Experiência em Suporte Técnico;
- Experiência com integrações, via APIs, crawlers e scrapings;
- Experiência em pelo menos um banco de dados relacional;
- Experiência com SQL;
- Ter comunicação rápida e assertiva, saber trabalhar com times multidisciplinares e enxutos em um ambiente dinâmico, com entregas rápidas, metodologias ágeis e inspirado no Vale do Silício. Trabalhamos com velocidade e autonomia no dia-a-dia e somos um time de alta - performance;
- Experiência com git;
- Lógica de programação e fluxos de negócio.

# Informações Gerais

- Local: Florianópolis - SC;
- Benefícios: Salário até 2.5k + bônus;
- Contratação / Regime: PJ;
- Alocação: Remoto;
- Mais informações / Candidatar-se: bit.ly/reviewr-jr-backend-developer.

P.S.: Mais dúvidas, contactar leonardo.rifeli@reviewr.me

**Comment by davi-dv** [comment]
bom dia,a vaga é remota ou presencial?

**Comment by leonardorifeli** [comment]
Opa! @davi-dv é remoto.

**Comment by andersonmag** [comment]
@leonardorifeli Essa vaga já foi preenchida?

**Comment by leonardorifeli** [comment]
Olá @andersonmag ainda não foi.
Se tu tiver interesse, responde o formulário e me dá um alô: bit.ly/reviewr-jr-backend-developer.
Tks.
