### ISSUE TITLE
[Rio De Janeiro-RJ] Programador Java JR | Softtek

### ISSUE THREAD

**Issue by renanrufino** [backend-br/vagas#2385]
**### Local de Trabalho**
Praia do Flamengo,200 - Flamengo

**### Empresa**

Fundada em 1982, a Softtek é uma fornecedora global de soluções orientadas a processos de TI. 
No momento, estamos buscando Profissionais com o perfil abaixo:

**### Plataforma WEB - Java JR**

**Conhecimentos básicos de:**
arquitetura web
servidor de aplicação
JAVA / HTML / CSS / Javascript
Eclipse
Spring Boot
Hibernate

**Perfil:**
Profissional com boa comunicação
Dinâmico

**Local de Atuação:** Rio de Janeiro - RJ
**Período:** Indeterminado
**Contratação:** CLT
**Oferecemos:** Salário Atrativo + Benefícios 
Maiores detalhes serão passados no momento da entrevista.

**CLT / Salário a combinar.**

Por favor envie um e-mail para renan.souza@softtek.com com seu CV anexado 
- enviar no assunto: Vaga JAVA JR

**Comment by mayararysia** [comment]
Há possibilidade de ser trabalho remoto?

**Comment by renanrufino** [comment]
> Há possibilidade de ser trabalho remoto?

tem sim!

**Comment by andersonmag** [comment]
Boa noite!! Essa vaga já foi preenchida?
