### ISSUE TITLE
[Berlim / Alemanha] Desenvolvedor Java Senior em [Choco]

### ISSUE THREAD

**Issue by yokomizor** [backend-br/vagas#239]
Postando uma vaga para Berlim, Alemanha. Dentro da empresa se fala inglês (e não alemão) e por isso a descrição está em inglês.

A descrição de empresa está um pouco vaga. Publicarei uma versão detalhada sobre a empresa em breve. Enquanto isso estou anexando alguns screenshots do app que consome essa API no final do post.

Segue descrição:

# Senior Java Engineer

**Berlin - Germany**

We are a young company that recently attracted one of the largest Seed-Financing
Rounds ever in Germany. We are working on a technology that has the potential to
enable millions of people globally and to reshape one of the oldest and largest
industries on the planet.

We are currently looking for skilled Java engineer interested in building APIs
from scratch. We are in a very exciting stage if you enjoy being close to
business and other non technical teams. We are a flat organization with minimal
hierarchy and therefore value self-managed professionals with a positive
attitude.

As team member, you would be responsible to deploy and benchmark your own code.
We also expect you to be fluent writing unit tests and actively participate in
code reviews and non technical discussions.

We are well-funded and offer fair compensation + equity for the right fit.

## Required skills:

* B.S or M.S in Computer Science, or equivalent experience
* Experience building REST APIs using Java
* Experience with AWS cloud computing

## Nice to have:

* Erlang / Elixir
* Experience with serverless infrastructure
* XMPP protocol
* GraphQL
* Non relational databases
* Experience with chatbots

## How to apply:

Email r@choco.app

![applescreenshotiphone1](https://user-images.githubusercontent.com/514767/40933553-204dbd32-6832-11e8-80ca-07cbbeeb6c3e.png)
![applescreenshotiphone2](https://user-images.githubusercontent.com/514767/40933554-2069ffe2-6832-11e8-8eee-36021578f7c5.png)
![applescreenshotiphone3](https://user-images.githubusercontent.com/514767/40933557-208e7dfe-6832-11e8-9bf5-7fff8b73173d.png)

**Comment by joaomarri** [comment]
Olá pessoal vi o anuncio dessa vaga para atuar com desenvolvimento Java, api e fiquei interessado ainda tem  vagas em aberto para essa empresa ?

**Comment by yokomizor** [comment]
@joaomarri, vaga est'a aberta. Envie curr'iculo para r@choco.app. Obrigado!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
