### ISSUE TITLE
[Porto Alegre - RS] Desenvolvedores(as) C# ou NodeJS na Fintech Warren

### ISSUE THREAD

**Issue by iagobyintera** [backend-br/vagas#2398]
**A Warren está mudando o mercado de investimentos do Brasil** e precisa de você para isso!

Estamos **crescendo como nunca**,  foi **em plena pandemia** que a empresa de nascida nos EUA em 2016 **atingiu seu primeiro R$ 1 bilhão** em recursos! Além disso estamos lançando o nosso novo produto o **Warren 3.0!**.

Temos **conexão com Fintechs do Silicon Valley**, então **bebemos da fonte em inovação tecnológica**,  estamos com o desafio de trabalhar com **grandes transações de dados bancários**, **arquiteturas de alta disponibilidade** e **escalabilidade de produtos** digitais.

Trabalhamos com **.NET para C#** e **desenvolvimentos de API para NodeJS**, buscamos **pessoas com propósito e dispostas a crescer exponencialmente** com a Warren. Serão bem vindos conhecimentos em arquiteturas, estruturas de dados e testes automatizados.

**Estamos te esperando. Topa o desafio?** 🙂 https://byintera.in/timewarren1

**Comment by TeijiW** [comment]
Tem possibilidade de remoto mesmo após o fim do distanciamento social?

**Comment by iagobyintera** [comment]
> Tem possibilidade de remoto mesmo após o fim do distanciamento social?

Opa @TeijiW , após o isolamento a oportunidade é preferencialmente presencial

**Comment by GabrielLinss** [comment]
Tem a possibilidade de ser remoto mesmo após a pandemia passar? Gostaria de me candidatar porém estou concluindo a faculdade.

**Comment by TeijiW** [comment]
> > Tem possibilidade de remoto mesmo após o fim do distanciamento social?
> 
> Opa @TeijiW , após o isolamento a oportunidade é preferencialmente presencial

Poxa que pena =c
Eu tenho os conhecimentos exigidos, mas só tenho a possibilidade de remoto
