### ISSUE TITLE
[SÃO JOSÉ/SC] Programador(a) PHP JR - People TI

### ISSUE THREAD

**Issue by peopleti** [backend-br/vagas#2399]
**A People TI busca profissional para atuar como Programador(a) Full Stack PHP (nível júnior) na empresa Canal Telecom Tecnologia em Campinas, São José - SC.**

Especializada em Tecnologia & Comunicação, a Canal Telecom Tecnologia tem compromisso com seus colaboradores e seus serviços!

**Atividades a serem desempenhadas:**
- Atuar com rotinas de desenvolvimento em PHP, Framework PHP, banco de dados relacional e serviços REST.
- Realizar correções e melhorias em sistemas web. 

**Conhecimentos:**
- PHP
- HTML/CSS
- Bootstrap
- JavaScript
- JQuery
- MySQL/PostgreSQL
- Apache
- Linux e Windows
- Aplicativos de softwares para desenvolvimento: Eclipse, Netbeans.

**Benefícios:**
- VT
- VR
- Plano de saúde
- Seguro de vida

Horário comercial: segunda à sexta-feira; Contratação CLT (salário a combinar).

**Envie seu currículo para cvbanco@peopleti.com.br ou inscreva-se em https://abler.in/v10449**

**Comment by lucasmoore2k** [comment]
Olá!
Possibilidade de trabalho remoto?

**Comment by peopleti** [comment]
Olá, Lucas!

A equipe está remota durante a quarentena, mas após esse período é preferencialmente presencial.

**Comment by caiquesandrade** [comment]
No site ta falando que tive participação encerrada.

**Comment by peopleti** [comment]
> No site ta falando que tive participação encerrada.

Olá, Caique! Iremos localizar sua candidatura para verificar.
