### ISSUE TITLE
[São Paulo] Desenvolvedor Magento [Mooven Consulting]

### ISSUE THREAD

**Issue by gabrielgsf31** [backend-br/vagas#24]
[VAGA] Desenvolvedor Magento

Local: São Paulo, SP
Salário: A combinar
Tipo de Contrato: Prestador de Serviços (PJ)

Clique no link abaixo para se candidatar:
https://www.recrutasimples.com.br/vaga/-KxDcCItfTt9DKAbjUs5/desenvolvedor-magento/são-paulo-sp?referrer=FB

#emprego #oportunidade #vaga #oportunidadedeemprego

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
