### ISSUE TITLE
[CENTRO / RJ] Desenvolvedor JAVA | J.M Confitec

### ISSUE THREAD

**Issue by DaiannaCs** [backend-br/vagas#2402]
### **Local de trabalho:**
Centro, Rio de Janeiro/RJ - (estamos próximo ao metrô Uruguaiana e VLT Candelária).

### **Empresa**
Somos especialistas em softwares voltados ao mercado segurador. Estamos ajudando a impulsionar a transformação no setor de seguros no Brasil. Estamos presentes em São Paulo e Rio de Janeiro, duas das principais capitais do país.
Você fará parte de um time de desenvolvedores extremamente qualificado fortemente orientado a resultados e que não tem medo de inovar.
Você será parte vital no desenvolvimento da nova plataforma de um de nossos principais clientes, trabalhando com boas práticas de desenvolvimento em um ambiente dinâmico que incentiva a autonomia e o aprendizado constante.
Estamos crescendo e precisamos de pessoas que amem tecnologia e que sejam fascinadas por aprender!

### **Responsabilidade e atribuição:**
Desenvolvimento de sistemas.

### **Requisitos:**
Experiência em desenvolvimento Java 8 com spring boot;
Familiaridade com APIs.
Noções de programação backend.

### **Seria fantástico se em seu background tivesse:**
Experiência em Cloud (Principalmente AWS, mas pode ser outra também);
Conhecimento em padrão de arquitetura como o DDD;
Conhecimento em mensageria, microsserviços e bancos não relacionais;

### **Benefícios**
• Plano de saúde.
• Plano odontológico;
• Vale Transporte;
• Vale-Refeição;
• Incentivo a cursos e certificações;
• PLR;
• Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
• Flexibilidade de horários;
• Café da manhã toda sexta-feira;
• Comemoração mensal dos aniversariantes;
• Sala de Descompressão;
• Grupo de corrida e caminhada;
• Campeonatos de futebol;
• Day off no mês do seu aniversário;

### **Contratação e como se candidatar** ✍
CLT - Salário: R$3.000,00 - R$8.500,00.
Por favor envie um e-mail para daianna.souza@confitec.com.br com seu CV anexado - enviar no assunto: Vaga Java – RJ e vamos responder em até 5 dias úteis 💙

**Comment by ArthurPinheiro** [comment]
@DaiannaCs A vaga é para todos os níveis de senioridade ?

**Comment by DaiannaCs** [comment]
> @ArthurPinheiro A vaga é para todos os níveis de senioridade ?

Isso mesmo Arthur, lembre-se que a atuação é no Centro do RJ.
