### ISSUE TITLE
[REMOTO / RJ] Desenvolvedor .NET na [CM Corp]

### ISSUE THREAD

**Issue by GlaucioOliveira** [backend-br/vagas#2404]
## DESCRIÇÃO DA VAGA
Missão: Desenvolver telas, relatórios, funcionalidades e regras de negócios na linguagem de programação C# de acordo com as especificações fornecidas.

## RESPONSABILIDADES E ATRIBUIÇÕES
Desenvolver software que entregue valor;
Apoiar desenvolvedores menos experientes nas suas entregas;
Entregar código testável com qualidade e no prazo acordado;
Ser capaz de entender o impacto de suas entregas na demanda;
Conseguir sinalizar problemas e impedimentos que impactam no prazo acordado;
Ser capaz de buscar soluções para as entregas;
Realizar entregas de forma autônoma;
Saber estimar o esforço e o custo para uma entrega de acordo com sua complexidade;
Entender o desenho da solução (arquitetura, modelagem, design de código) e conseguir materializar com código;
Promover adoção de boas práticas no time;
Identificar problemas na base de código existente e aplicar melhorias.

## REQUISITOS E QUALIFICAÇÕES

I. Certificações Microsoft;

II. Experiência Necessária:

De 2 a 4 anos (Desenvolvedor I), de 4 a 6 anos (Desenvolvedor II), maior que 6 anos (Desenvolvedor III) com desenvolvimento backend C# e banco de dados SQL Server ou Oracle;
Desenvolvimento de APIs, Padrão RESTful;
Com .NET Core;
Azure/AWS/Google Cloud;
DDD;
SOLID;
Design Patterns;
Desenvolvimento de software seguro;
Microservices;
Métodos ágeis (Scrum, Kanban, Safe, etc);
Ferramenta Team Foundation Server (TFS);
Ferramenta de Controle de Versão (GIT);
Desejável experiência com React ou Angular.

III. Desejável conhecimento em:

Sistema ERP;
RabbitMQ/Kafka;
Redis, Elastick Search;
Bancos não relacionais (Datastore, MongoDB e DynamoDB);
Ferramenta de desenvolvimento Visual Studio;
Teste de Software (TDD / BDD);
Boas práticas de performance de sistemas e de programação (Clean Code);
Desejável conhecimento em sistema ERP;
Teste de Software (TDD / BDD).
INFORMAÇÕES ADICIONAIS
Regime de contratação: CLT ou PJ

**Trabalho remoto: aceitamos candidatos de todo Brasil**

SEJA BEM-VINDO(A)!
Desde 1985 desenvolvemos soluções de Gestão Corporativa Integrada (ERP) para o segmento hoteleiro e desde 2005 também para o segmento previdenciário e de serviços.

Por meio de um corpo técnico altamente qualificado, a CMCorp tem a resposta às múltiplas demandas do mercado, fornecendo ERPs completos, parametrizáveis, modulares e abrangentes que incorporam o conhecimento do negócio dos clientes.

No atual cenário competitivo, trabalhamos continuamente para que nossos clientes recebam soluções e serviços que sejam:

Adequados para a capacidade funcional e flexíveis às necessidades específicas da empresa;
Implementados de forma rápida, simples e segura, com suporte em tempo real e de alto nível;
Tecnicamente evoluídos para se antecipar às novas necessidades e tendências do mercado;
Integração com outras aplicações legadas, com o apoio das tecnologias e metodologias mais modernas.

Agradecemos desde já seu interesse em fazer parte da CMCorp!

**Site da empresa**: https://www.cmcorp.com.br/

**Inscreva-se para a Vaga em**: https://cmcorp.gupy.io/jobs/201686

**Comment by Hernany** [comment]
Glaucio Oliveira,
Boa noite!

Certificação é obrigatória?
Aguardo breve retorno!

**Comment by GlaucioOliveira** [comment]
@Hernany , não sei dizer se eles vão considerar obrigatória ou não. Como estão precisando de desenvolvedores acho que nem devem considerar isso como algo necessário, enfim, tenta a sorte, rs.
