### ISSUE TITLE
Goiania - Programador PHP

### ISSUE THREAD

**Issue by lucenarenato** [backend-br/vagas#241]
Empresa: Federal Soluções Técnicas
Vaga: Programador PHP - Goiânia
Requisitos:
* Amplo conhecimento na linguagem;
* Boa lógica de programação e conhecimento de OO.
* Banco de dados PostgreSQL;
* Boas práticas de desenvolvimento;
Desejável:
* Framework Laravel
Salário:
* Negociável. Enviar pretensão salarial.
Interessados enviar e-mail para: suporte@federalst.com.br

**Comment by garaujodev** [comment]
Apenas alocado?

**Comment by lucenarenato** [comment]
sim, é presencial.

**Comment by guilhermeoa07** [comment]
Júnior, Pleno ou Sênior?

**Comment by lucenarenato** [comment]
Tanto faz, pode mandar e coloca a pretensão.
