### ISSUE TITLE
[São Paulo] Nodejs Developer na PIXTER 

### ISSUE THREAD

**Issue by RecruiterFMonteiro** [backend-br/vagas#2414]
**Descrição da vaga**
Temos uma oportunidade de desenvolvedor, para integrar equipe de desenvolvimento Web,, onde você terá a oportunidade de trabalhar com Nodejs em um time de pessoas incríveis!

**Local**
São Paulo - Presencial.

**Requisitos**
Obrigatórios:

Interesse em aprender novas tecnologias e compartilhar conhecimento;
Gostar de trabalhar em equipe e ser comunicativo(a);
Experiência no desenvolvimento de projetos em php e node.js ;
Experiência com jquery / angularjs ;
Desenvolvimento e consumo de api rest / soap ;
Conhecimento em metodologia ágil – scrum / kanban ;
Conhecimento em mysql, mongodb ou dynamodb ;
Experiência em ferramentas para controle de versão (git) ;
Conhecimento da ferramenta jira ;
Capacidade de analisar escopos e demandas, também sugerir soluções.

Desejáveis:

Incentivamos troca de conhecimento;
Trabalho em equipe;
Contratação
PJ - Salário a combinar.

**Nossa empresa**
Somos uma boutique de software que tem em seu core desenvolvimento, inteligência e usabilidade.
Filtramos projetos que têm fit cultural com o que acreditamos e trabalhamos com poucos clientes.
Nos últimos três anos acumulamos cases de sucesso com empresas de grande porte.
Veja mais em: https://pixter.com.br/

**Como se candidatar**
Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Back Nodejs

**Comment by TeijiW** [comment]
Existe alguma mínima possibilidade de ser remota? (Após a pandemia no caso)

**Comment by RecruiterFMonteiro** [comment]
Olá!
Tudo certo?
Infelizmente não, pelo menos ainda não é uma opção.
Seria remoto até a situação ser normalizada.


*Fernanda Monteiro*
People & Community Manager

*Pixter*
Tel: +55 (11) 3090-8500



Alameda Santos, 1978 - 6° andar - Jardim Paulista - São Paulo - SP | CEP.
01418-200




Confidencialidade: A informação contida nesta mensagem de e-mail, incluindo
quaisquer anexos, é confidencial e está reservada apenas à pessoa ou
entidade para a qual foi endereçada. Se você não é o destinatário ou a
pessoa responsável por encaminhar esta mensagem ao destinatário, você está,
por meio desta, notificado que não deverá rever, retransmitir, imprimir,
copiar, usar ou distribuir esta mensagem de e-mail ou quaisquer anexos.
Caso você tenha recebido esta mensagem por engano, por favor, contate o
remetente imediatamente e apague esta mensagem de seu computador ou de
qualquer outro banco de dados. Muito obrigado.





Em qui., 14 de mai. de 2020 às 19:04, Teiji <notifications@github.com>
escreveu:

**Comment by RecruiterFMonteiro** [comment]
Olá, está aberta. Temos mais de uma vaga.

Fernanda Monteiro
People & Culture Manager
Pixter Technologies

Website: https://www.pixtertechnologies.com/

São Paulo, Brazil
+55 11 30908500


<https://www.pixtertechnologies.com/>

work hard and be nice to people


Em qua., 5 de ago. de 2020 às 21:22, github-actions[bot] <
notifications@github.com> escreveu:
