### ISSUE TITLE
[São Paulo ou Campinas] Backend Developer (Java) - Pleno ou Sênior (iFood)

### ISSUE THREAD

**Issue by Almanake** [backend-br/vagas#242]
## Descrição da vaga

O iFood está contratando Desenvolvedores Java (perfis Pleno ou Sênior) para atuar em suas unidades em São Paulo (SP) e Campinas (SP). Todas as posições são presenciais. 
Valorizamos profissionais com bagagem prévia em alta escalabilidade (temos picos de consumo diário), disponibilidade (nosso serviço NÃO pode ficar fora do ar), que saiba lidar com autonomia e assumir responsabilidades (aqui você faz sua carreira mesmo!), que seja questionador e propositivo (não adianta só apontar o erro), que busque aprender novas tecnologias sempre (temos legados, sim, mas buscamos sempre a tecnologia mais atual) e que tenha visão permanente em automação de processos.

Temos desafios complexos nas áreas de E-commerce, Logística, Meios de Pagamentos e entre outros! Aqui não há espaço para se acomodar. Valorizamos quem tenham passado por empresas onde teve que lidar com desafios de escala e disponibilidade. Valorizamos também gente que tentou próprio negócio, passou por startups ou atuou em time enxutos onde tinha que lidar com diversas informações e ser multidisciplinar.

## Local

São Paulo (Villa Lobos) ou Campinas (próx. Shopping Pq. Dom Pedro)

## Benefícios

- Plano de saúde
- VT ou Estacionamento
- VR 
- Plano Odontológico
- PLR

#### Diferenciais

- frigobar sempre cheio :P
- sala de jogos
- ambiente descontraído e informal
- possibilidade REAL de projetos internacionais

## Requisitos

**Obrigatórios:**
- Java
- Spring 
- Microsserviços 
- filas assícronas / mensageria.
- Banco de Dados SQL e NoSQL 

**Desejáveis:**
- AWS 

**Diferenciais:**
- atuado em startups e/ou times multidisciplinares

## Contratação

CLT (Plano de Carreira)

## Nossa empresa

O iFood é a maior plataforma de pedidos de delivery (restaurantes) da América Latina. Atualmente recebe mais de 6 milhões de pedidos ao mês, tem mais de 5 milhões de usuários ativos e, além do Brasil, também está presente na Argentina, Colômbia e México. 

Contratação CLT, remuneração competitiva e plano de carreira que pode ser acelerado conforme o grau de autonomia e responsabilidade do profissional. A empresa já está atuando em outros países e segue um ritmo forte de expansão internacional.

## Como se candidatar

Por favor envie um email para vieira@talentu.com.br com seu CV anexado

## Labels

- CLT
- Pleno
- Sênior

**Comment by geanfelipe** [comment]
paid relocation?

**Comment by Almanake** [comment]
Gean, não entendi o termo "paid relocation".
Se for em questão a auxílio moradia (mudança de outros Estados), pelo menos a priori, não estamos trabalhando com a possibilidade.

**Comment by guilhermeoa07** [comment]
Vagas para Júnior ou trainee?

**Comment by Almanake** [comment]
Olá!
Guilherme é capaz que tenham, sim!
Eu sou um Consultor que está auxiliando o iFood nas posições acima.
De qualquer forma, pode encaminhar seu CV que reencaminho ao RH do iFood.

**Comment by joaopdto** [comment]
Opa, estou procurando estágio. Posso enviar o meu? (Vai que dá certo)

**Comment by Almanake** [comment]
Olá!
Pode enviar que eu encaminho!
Repito, não estou conduzindo vagas nesse perfil, mas, se tiver algo em aberto para Estágio, provavelmente eles entrarão em contato.

**Comment by guilhermeoa07** [comment]
Ok, Vou enviar mesmo assim, obrigado.

**Comment by AlbericoD** [comment]
Apenas Java ? Tipo, tudo é full java? 
A vaga é interessante, perto de casa

**Comment by Almanake** [comment]
Olá Alberico. Como linguagem Backend, de fato, a empresa trabalha essencialmente com Java.

**Comment by gabrielrps** [comment]
A vaga ainda está aberta?

@Almanake

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
