### ISSUE TITLE
[São Paulo - Butantã] Java Developer (Pleno ou Senior) - Raia Drogasil

### ISSUE THREAD

**Issue by taianeuchoac** [backend-br/vagas#2422]
Buscamos por Desenvolvedor Java, nível Pleno ou Senior, para atuar alocado na Raia Drogasil.

Responsabilidades
Atuará no desenvolvimento e sustentação de aplicações internas da empresa.
A empresa valoriza profissionais que se interessem em atuar de forma hibrida, com linguagens difernetes.

Requisitos
Imprescindível Experiência de cerca de 3 a 4 anos atuando com:
Java, Jsf, Jpa, J2ee, Prime Faces.
Metodologia agil;
Weblogic; 
Maven; 
git; 
rest; 

Desejável conhecimento em:
Spring; Javascript; Jquery; Angular; Testes unitários; TDD; Integração contínua; Scrum; xp; metologia ágil; OC4J; Prime Faces;

Local de Trabalho: Butantã (São Paulo).

Como se candidatar
Encaminhe seu currículo para o email taiane@mazza.tech.

**Comment by arthur-mts** [comment]
Possibilidade para trabalho remoto?

**Comment by taianeuchoac** [comment]
Ola!

O trabalho remoto esta sendo realizado apenas nesse momento de
distanciamento social.
Mas após a normalização, a atuação é no escritório da empresa.

Obrigada!


Taiane Uchoa
ANALISTA DE RH

taiane@mazza.tech <leoraposo@mazza.tech>
011 2532.2992 <http://mazza.tech/assinatura/2020/11%2025322992> / 97569.0652
skype: taiane.uchoa
[image: Site] <http://www.mazza.tech/>
[image: Localização] <http://www.mazza.tech/>


Em sex., 15 de mai. de 2020 às 21:25, Arthur Maurício <
notifications@github.com> escreveu:
