### ISSUE TITLE
[São Paulo] Back-end Developer na Aeroscan

### ISSUE THREAD

**Issue by Marcello09** [backend-br/vagas#2426]
## Aeroscan

A Aeroscan é uma startup de tecnologia especializada em aeronaves remotamente pilotadas (drones). A 2 anos a empresa iniciou o processo de expansão para o mercado de segurança e está desenvolvendo uma plataforma de operação de aeronaves automatizada para este mercado.

## Descrição da vaga

Vaga de desenvolvedor(a) backend para ampliação do projeto de servidores da Aeroscan. Um projeto desenvolvido em Python que estamos migrando para NodeJS e adicionando novas funcionalidades. Trabalhando com Socket.IO para comunicações em tempo real e express para demais comunicações.

## Local

Escritório localizado em Alphaville Industrial, Barueri.

## Requisitos

**Obrigatórios:**
- NodeJS
- Lingua inglesa

**Desejáveis**
- Socket.IO
- Redis
- MongoDB
- Interesse em se tornar Fullstack
- Java para desenvolvimento Android

**Diferenciais**
- Conhecimento de veículos autônomos
- Conhecimento de sistemas em tempo real

## Benefícios

- Auxílio transporte
- Auxílio alimentação

**Diferenciais**
- Horario flexível
- Cachorro no escritório
- Chance de participação da empresa (stock option)

## Contratação

PJ a combinar

## Como se candidatar

Envie um email para m.moreira@aeroscan.com.br com o assunto: Vaga Front-end [NOME]

## Tempo médio de respostas

Após o primeiro contato, damos a resposta em até 2 dias úteis. Caso não receba uma resposta dentro do prazo, por favor entrar em contato no número (31) 99631-1979 ou pelo whatsapp do mesmo numero.

#### Alocação
- Alocado

#### Regime
- Estágio
- PJ

#### Nível
- Júnior
- Pleno

**Comment by arthur-mts** [comment]
Tem possibilidade de remoto?

**Comment by Marcello09** [comment]
Infelizmente não estamos contratando remoto no momento
