### ISSUE TITLE
Adicionar e organizar links de outros repositórios no readme.md

### ISSUE THREAD

**Issue by guibranco** [backend-br/vagas#2430]
Separar os repositórios "irmãos" por área de atuação, tecnologia, localidade.
Adicionar links dos repositórios de .NET e Rust. 
Adicionar link do próprio repositório para padronizar o readme.md

**Comment by guibranco** [comment]
Boa tarde senhores, @alexandremjacques @Fragalli @gucastiliao

Poderiam verificar este issue e aprovar a PR #2431 por gentileza ?

**Comment by Fragalli** [comment]
@guibranco estou sem permissão para aprovar esse pr oO

Só aguardar... logo alguém com permissão aceita

**Comment by guibranco** [comment]
Sem problemas @Fragalli !

**Comment by guibranco** [comment]
Alguém poderia verificar e aprovar por favor ? 

@khaueviana @Kirmayrtomaz @lucassantos61 @mrprompt @SylvioMigliorucci

**Comment by mrprompt** [comment]
aprovado ;)
