### ISSUE TITLE
[ São Paulo ] Principal Engineer (Tech Leader) na Fintech [CREDITAS]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#2432]
Vamos direto ao ponto, o Principal Engineer é a pessoa que tem que entender a arquitetura do problema, desenvolver a melhor solução tendo profundidade nos conceitos da aplicação, conhecendo da arquitetura, e em quais contextos aplicamos **microservices** para uma arquitetura com melhor performance. 

Não se engane, o Principal Engineer está **mais próximo do gerenciamento do que do coding**, é a pessoa que será mentora em desafios e dúvidas mais complexas, as que são mais do dia-a-dia, são de responsabilidade dos Specialists, esses que serão o braço direito, esquerdo e corpo da equipe de Principal's - ou seja, o desafio maior é **traduzir o que a Creditas e a Trybe em desejam para o negócio**, em linhas de código limpas e organizadas.

### **Tudo pode ser visto aqui: https://byintera.in/oq**

**Comment by barbosafred** [comment]
A vaga é para CLT?

**Comment by AndreBorim** [comment]
> A vaga é para CLT?

Simm. A contratação é feita no modelo CLT.

Qualquer dúvida estou à disposição.

**Comment by barbosafred** [comment]
Obrigado!
