### ISSUE TITLE
[Florianópolis/Remoto] Machine Learning Engineer na Datarisk

### ISSUE THREAD

**Issue by gustavodgbernardo** [backend-br/vagas#2449]
# Sobre a empresa: Datarisk 

A Datarisk é uma empresa focada em resolver problemas utilizando as mais modernas ferramentas de machine learning. 
Desenvolvemos produtos para análise de dados e imagens prevendo fraudes e inadimplências, otimizando cobranças e aumentando vendas. 
Tornando o processo de decisão dos nossos clientes mais rápido, ágil e simples.

## Descrição: Qual será o seu papel? 

Suas principais responsabilidades serão criar, manter, implantar nossos algoritmos de ML, principalmente com foco em visão computacional.

## Esperamos que você tenha experiência com: 

- Conhecimentos em python
- conhecimentos em Machine Learning e/ou visão computacional
- Git
- Boas práticas de programação

## Vamos ficar felizes se você conhecer: 

- Se tiver mestrado ou doutorado nesta área
- Conhecimentos em Docker
- Conhecimentos em sistemas distribuídos

## Você vai amar trabalhar aqui se:
- Gostar de ambiente de startup
- Crescimento acelerado
- Gostar de aprender
- Trabalhar como foco em resultados

## Benefícios
- Horário flexível
- Trabalho remoto

## Informações Complementares:

- Contratação tipo PJ;
- Vaga presencial/remoto;
- Estamos localizados no bairro Santa Mônica Florianópolis.

Envie seu currículo para vagas.ti@datarisk.io

**Comment by WagnerPaulino** [comment]
Poderia informar a faixa salarial...?

**Comment by gustavodgbernardo** [comment]
Vaga Fechada
