### ISSUE TITLE
[Florianópolis/Remoto] Senior Software Engineer na Datarisk

### ISSUE THREAD

**Issue by gustavodgbernardo** [backend-br/vagas#2450]
# Sobre a empresa: Datarisk 
A Datarisk é uma empresa focada em resolver problemas utilizando as mais modernas ferramentas de machine learning. 
Desenvolvemos produtos para análise de dados e imagens prevendo fraudes e inadimplências, otimizando cobranças e aumentando vendas. 
Tornando o processo de decisão dos nossos clientes mais rápido, ágil e simples.

## Descrição: Qual será o seu papel? 
Suas principais responsabilidades serão criar, manter, implantar nosso sistema de maneira geral, podendo trabalhar desde com construção de algoritmos de Machine learning como arquitetura de sistema, entre outros.

## Esperamos que você tenha experiência com: 
- Familiaridade com múltiplas linguagens, incluindo Python e Javascript
- Desenvolvimento, manutenção e operação de sistemas
- Experiência com diferentes processos para deploy de aplicações
- Conhecimentos em Docker
- Git
- Boas práticas de programação

## Vamos ficar felizes se você conhecer: 
- Conhecimentos em linguagens funcionais
- Conhecimentos em AWS
- Conhecimentos em sistemas distribuídos (spark ou outros)

## Você vai amar trabalhar aqui se:
- Gostar de ambiente de startup
- Crescimento acelerado
- Gostar de aprender
- Trabalhar como foco em resultados

## Benefícios
- Horário flexível
- Trabalho remoto

## Informações Complementares:
- Contratação tipo PJ;
- Vaga presencial/remoto;
- Estamos localizados no bairro Santa Mônica Florianópolis.

Envie seu currículo para vagas.ti@datarisk.io

**Comment by pauloegk** [comment]
Faltou colocar o link ou e-mail para vaga. :)

**Comment by gustavodgbernardo** [comment]
Foi mal! verdade, vou arrumar

**Comment by Hernany** [comment]
Manda o link pois tenho interessse em me candidatar!

Hernany Santos
(31) 98606-5970



Em seg., 25 de mai. de 2020 às 17:15, Gustavo Bernardo <
notifications@github.com> escreveu:

**Comment by gustavodgbernardo** [comment]
@Hernany eu ja adicionei o email para enviar o cv! 
basta enviar para vagas.ti@datarisk.io

**Comment by Hernany** [comment]
Valeu! Vou enviar!

Hernany Santos
(31) 98606-5970



Em ter., 26 de mai. de 2020 às 08:03, Gustavo Bernardo <
notifications@github.com> escreveu:

**Comment by xspager** [comment]
@gustavodgbernardo, só pra reforçar. Mandei meu currículo para o email informado.

**Comment by gustavodgbernardo** [comment]
A vaga continua aberta sim. Ainda não fechamos.
