### ISSUE TITLE
[Belo Horizonte - Remoto] Software Developer no Melhor Plano

### ISSUE THREAD

**Issue by GuilhermeLLS** [backend-br/vagas#2452]
## Nossa empresa

O Melhor Plano ajuda consumidores a tomarem a melhor decisão na contratação de serviços. Nossa visão é ser a referência mais confiável para consumidores compararem e contratarem serviços básicos como telefonia, serviços bancários, seguros, etc. Ajudamos consumidores com:

- conteúdo informativo e transparente
- tecnologia de ponta para capturar preços em todo o país
- softwares para o consumidor comparar e encontrar planos com facilidade

## Descrição da vaga

Tecnologia é fundamental para a construção do Melhor Plano. Para funcionar bem, temos que atender várias demandas de diferentes grupos:

**Para o consumidor**: capturar preços de serviços em todo o Brasil! Conseguir mostrar dados de maneira simples e precisa, atendendo milhões de usuários com respostas instantâneas.
**Para o time**: prover ferramentas para que outros times trabalhem e produzam o máximo de resultado!
**Para parceiros**: conseguir acompanhar resultados e analisar dados com precisão.
Você trabalhará em uma ou mais partes do stack do Melhor Plano:

- Linguagem: Typescript
- Front-end React (Preact)
- Node
- MongoDB / MySQL / Google Big Query
- Infra-estrutura: AWS / Google Cloud

## Local

No Melhor Plano, tanto horário como local de trabalho é flexível. A sede da empresa fica na Savassi, em Belo Horizonte, mas o contrato de trabalho é remoto e você pode trabalhar de onde preferir. Toda a gestão e comunicação é feita de maneira online. 

## Requisitos

**Para a Vaga de estágio**
- Conhece os fundamentos de desenvolvimento de software, algoritmos e estrutura de dados
- Já trabalhou em pequenos projetos de software da faculdade ou pessoais 
- Consegue expressar bem problemas e discutir soluções
- É uma pessoa curiosa e está sempre buscando entender novos desafios

**Para Jr-Pleno**
- Aplica bem os fundamentos de desenvolvimento de software como algoritmos e estrutura de dados
- Já consegue escrever um código limpo e modular
- Já teve experiência com trabalho em equipe na construção de projetos de softwares mais longos
- Se bem orientado por um arquiteto de sistemas, consegue contribuir significativamente em projetos complexos com vários desenvolvedores
- Comunica bem problemas e usa do conhecimento do time para construir soluções melhores
- É uma pessoa curiosa e está sempre experimentando novas tecnologias

**Diferenciais:**
- Ter trabalhado em algum projeto de soluções Web para consumidores

## Benefícios

**Para a vaga de estágio**
- Carga horária: 30h semanais
- Auxílio alimentação R$ 200 / mês. 
- Reembolso e transporte nos dias que vier no escritório
- Remuneração: R$ 1100 / mês - oportunidade de aumento da bolsa a medida que ganhar mais domínio com o processo de desenvolvimento

**Para a vaga de Jr-Pleno**
 - Vale Refeição / Alimentação - R$ 28,60 por dia - cerca de R$ 600 por mês (dependendo de quantos dias úteis temos no mês)
- Plano de Saúde Bradesco
- Reembolso transporte quando for trabalhar no escritório
- Horário Flexível - Possibilidade de stock options após um ano de empresa
- Remuneração: **Contrato CLT** - tempo integral. Salário baseado na experiência, por favor, indique sua pretenção salarial na aplicação.

## Como se candidatar

Preencha esse [formulário](https://airtable.com/shrUwkrE60MiJ3Pj1), ou acesse https://melhorplano.net/vagas
#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Pleno

**Comment by tiago123456789** [comment]
@GuilhermeLLS eu tinha me cadastrado a alguns dias atrás, pois vi uma vaga do Melhor Plano no linkedin. Preciso me candidatar novamente?

**Comment by GuilhermeLLS** [comment]
> @GuilhermeLLS eu tinha me cadastrado a alguns dias atrás, pois vi uma vaga do Melhor Plano no linkedin. Preciso me candidatar novamente?

@tiago123456789 não precisa, te daremos um feedback em breve!

**Comment by MarcosWinicios** [comment]
A vaga para estágio também é remota? Eu moro no Goiás e tenho interesse.

**Comment by GuilhermeLLS** [comment]
@MarcosWinicios é remota também.

**Comment by RafaelEmery** [comment]
Não tenho experiência com Typescript e tenho pouca com ReactJS e Node, minha stack é em PHP (Laravel), isso possui um caráter eliminatório? Ou vocês também analisam outros conhecimentos e pode ser oferecido uma oportunidade de aprendizado e desenvolvimento nessas stacks?

**Comment by GuilhermeLLS** [comment]
> Não tenho experiência com Typescript e tenho pouca com ReactJS e Node, minha stack é em PHP (Laravel), isso possui um caráter eliminatório? Ou vocês também analisam outros conhecimentos e pode ser oferecido uma oportunidade de aprendizado e desenvolvimento nessas stacks?

@RafaelEmery ter experiência com React e Node não são requisitos obrigatórios das vagas. Levamos mais em conta a capacidade de desenvolvimento e desenvoltura do candidato nos testes técnicos.

**Comment by jefferson-dev** [comment]
Bom dia @GuilhermeLLS , eu preenchi o formulário, há alguma previsão de retorno? repassando os teste para serem feitos?

**Comment by GuilhermeLLS** [comment]
> Bom dia @GuilhermeLLS , eu preenchi o formulário, há alguma previsão de retorno? repassando os teste para serem feitos?

@jefferson-dev você receberá um email nos próximos dias com as instruções do processo seletivo.

**Comment by breno-alves** [comment]
> > Bom dia @GuilhermeLLS , eu preenchi o formulário, há alguma previsão de retorno? repassando os teste para serem feitos?
> 
> @jefferson-dev você receberá um email nos próximos dias com as instruções do processo seletivo.

@GuilhermeLLS me cadidatei a mais de uma semana e não recebi retorno. O retorno será feito para todo mundo nos próximos dias?

**Comment by gabrieldylanls** [comment]
@GuilhermeLLS Olá, me inscrevi para a vaga de estágio, alguma previsão de quando será o feedback?

**Comment by GuilhermeLLS** [comment]
@breno-alves @gabrieldylanls todos receberão suas respostas.
Estamos demorando um pouco, pois temos muitos currículos (muitos mesmo) para fazer triagem. Vocês devem imaginar que deve ser um processo complexo :))

**Comment by RafaelEmery** [comment]
> @breno-alves @gabrieldylanls todos receberão suas respostas.
> Estamos demorando um pouco, pois temos muitos currículos (muitos mesmo) para fazer triagem. Vocês devem imaginar que deve ser um processo complexo :))

Ainda não recebi nada, tem alguma previsão? Parece ser um processo bem complexo mesmo, inclusive haha
