### ISSUE TITLE
[ São Paulo ] Principal Engineer | Tech Leader [CREDITAS]

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#2459]
As pessoas que procuramos para essa oportunidade devem possuir uma **profundidade em conceitos**, por isso **independe a linguagem que esse profissional domina**. É importante uma boa noção de arquitetura, já que as decisões técnicas passarão por essa pessoa diariamente. 

No dia a dia codam pouco e a maior parte do tempo precisam participar de reuniões para decisão de tecnologias e estratégia dos projetos, realizar experimentos, estudar, pesquisar sobre tecnologias e comunicar-se frequentemente com a área de produtos e com as lideranças da área de tecnologia.

### **Tudo pode ser visto aqui: https://byintera.in/oq**

**Comment by acgfbr** [comment]
da uma olhada no teu email que te mandei uma dica sobre segurança la.
