### ISSUE TITLE
[Remoto] Desenvolvedor Full-Stack na GrowthTech

### ISSUE THREAD

**Issue by kennethgt** [backend-br/vagas#2461]
## Nossa empresa

A Growth Tech é uma startup fundada há 4 anos e que trabalha desenvolvendo projetos inovadores de tecnologia da informação. Dentre as suas principais áreas de atuação estão: Soluções em Blockchain para negócios, aplicativos e softwares customizados sob demanda.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Node.js
- Express.js
- React.js

**Desejáveis:**

- Blockchain

## Contratação

- PJ (R\$ 6.000,00)

## Desafio

Uma empresa deseja realizar um monitoramento de outros grupos empresariais em um site X para analisar seus posts. Sua tarefa é criar uma simples API que captura apenas os usuários (http://jsonplaceholder.typicode.com/users) os quais a empresa em que trabalham fazem parte de um grupo e exiba seus posts (http://jsonplaceholder.typicode.com/posts) unido do nome do funcionário e sua empresa. Além disso criar uma tela para facilitar a leitura desses posts.

- O backend obrigatoriamente precisa ser realizado com Express.js.
- O frontend obrigatoriamente precisa ser realizado com React.js.
- Apesar de bem simples, o projeto precisa estar pronto para produção.
- Sinta-se à vontade para adicionar mais features e criar uma UI maneira!

## Como se canditatar

Assim que finalizado preencher o [formulário](https://forms.gle/ajYAbSVtrAJGUsLXA) e aguardar, boa sorte!

**Comment by carvalhoviniciusluiz** [comment]
esse trecho não ficou claro `os quais a empresa em que trabalham fazem parte de um grupo` alguma dica se é pra agrupar usuário por empresa, pesquisar usuários da mesma empresas ou somente um texto cosmético ?

**Comment by JeanDuarte00** [comment]
Vinícius, acho que é para agrupar por empresa e mostrar as postagens de todos daquela determinada empresa.

**Comment by carvalhoviniciusluiz** [comment]
Cada usuário pertence a empresa especifica, as empresas não se repetem nesse caso, acho que agrupar por empresa não se aplica só acho mas blz.

![Captura de Tela 2020-05-27 às 18 20 20](https://user-images.githubusercontent.com/22005684/83073483-e6e2ce80-a046-11ea-9995-f5877bb4a99b.png)

**Comment by kennethgt** [comment]
Eae gente, tudo bem?
"a empresa em que trabalham fazem parte de um grupo" são as empresas que contém "Group" no nome :)

Qualquer dúvida pode enviar um email para kenneth@growthtech.com.br

**Comment by radaelilucca** [comment]
Enviado! 

Desde já agradeço a oportunidade. Aprendi bastante com esse teste! rs
