### ISSUE TITLE
[Santos] Desenvolvedor(a) Back-End na Spacemoon

### ISSUE THREAD

**Issue by gabrielcraveiro** [backend-br/vagas#2468]
## Sobre a empresa

A vaga é para uma aceleradora de startups, voce ira atuar em projetos dentro da nossa incubadora em um ambiente compartilhado que permite o 
aprendizado e crescimento profissional através da exposição de vários mercados dentro da area de TI. 

Nossas startups envolvem mercados diversos como educação, saúde, entretenimento e nutrição.

A empresa é localizada em **Santos,** tendo um ambiente com horários flexiveis, sala de descompressão e coworking proprio.

## Atividades e Responsabilidades

- Será um dos responsáveis pela qualidade do código e do produto.

- Responsável pelo back-end em PHP (sistema de api's PHP com front em vue.js) e desenvolvimento do banco de dados (SQL Server)

- Desenvolvimento e arquitetura de MVP para projeto de streaming privado.

- Implementação de sistema de pagamentos 

- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;

## Requisitos

- Experiência ampla em PHP / SQL Server;

- Conhecimento em criação de procedures;

- Experiência com ferramentas de versionamento de código (GIT);

- Conhecimento básico em frameworks de front-end;

## Diferenciais:

- Node

- Processsos/Ferramentas de Integração Contínua

- Docker

- AWS

- Vue/JS 

- Arquitetura de Software

## Alocação Contratação:

- Presencial (com flexibilidade de horários)
- PJ

## Experiência
- Pleno
- Senior

Ficou interessado? Envie o link de seu Linkedin ou CV para sidney.lazzarini@spacemoon.com.br

**Comment by bryan-alves** [comment]
Enviado 👍
