### ISSUE TITLE
[Barueri] ANALISTA PROGRAMADOR C# .NET PL/SR (Vagas PJ)

### ISSUE THREAD

**Issue by cimerio** [backend-br/vagas#247]
# **IVENTIS TECNOLOGIA**
Procuramos  **Analistas Programadores C# .NET** para atuar em nosso cliente do segmento de fidelidade por prazo indeterminado. Temos vagas para todos os perfis (Sustentação ou Desenvolvimento). O ambiente de trabalho é jovem, dinâmico com ótimas oportunidades para aprender e crescer. 

## **PARA CANDIDATAR-SE**
Envie seu CV e pretensão hora para o email: [recrutamento@iventis.com.br](mailto:recrutamento@iventis.com.br)
No assunto especifique: vaga .NET (senioridade) (dev ou sustentação) - Alphaville

## **LOCAL**
Alphaville - Barueri/SP

## **REQUISITOS**
.Net C#, Entity Framework, MVC, WebAPI, AngularJS, Redis, GIT
Scrum, Unit Test, SOAP, REST, Design Patterns

## **DESEJÁVEL:**
Angular [2,4,5,6], NodeJS, Mongo DB
Integração contínua, TDD

## **CONTRATAÇÃO**
PJ a combinar

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
