### ISSUE TITLE
[Colombo/PR] Programador(a) PHP Jr

### ISSUE THREAD

**Issue by mayronceccon** [backend-br/vagas#248]
Programador(a) PHP Jr

Cidade: Colombo/PR

Desenvolvimento de aplicações PHP, criação de novas funcionalidades e melhorias em sistemas existentes.

Necessário experiência em PHP estruturado e Orientando a Objetos, HTML5, CSS3, JavaScript, SQL e lógica de programação.
Conhecimento tácito em Frameworks PHP (Laravel, Slim) será um diferencial.

Atuar com Banco de dados Postgresql, Controle de versão GIT, Conhecimentos em Linux

Salário a combinar

Horário Comercial

Contratação CLT

Presencial

Interessados enviar CV para o e-mail sistemas@tecnorisk.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
