### ISSUE TITLE
[São Paulo] Back-end Developer NodeJS na [Beetech]

### ISSUE THREAD

**Issue by AlexKawaharada1981** [backend-br/vagas#2487]
Sobre a BeeTech 🌏

Nossa missão é possibilitar que as pessoas tenham uma vida global, com serviços financeiros que não são limitados a fronteiras. Acreditamos que todos devem ter a oportunidade de fazer o melhor uso do seu dinheiro, não importa onde estejam. Juntos, estamos criando um mundo sem fronteiras financeiras.

**O que você vai fazer aqui na BeeTech **

- Participar ativamente na arquitetura de soluções

- Participar de cerimônias ágeis

- Aprofundar nas regras de negócio, estruturar e modelar serviços

- Garantir coerência e coesão no desenvolvimento sobre requisitos funcionais e não-funcionais

- Ser responsável por desenvolver Spikes como referência técnica

- Provisionar documentação técnica

- Participar de plantões (on call)

- Promover melhorias de código

- Trazer novas ideias e soluções fora da caixa

- Entender e promover a adoção de padrões de desenvolvimento da BeeTech no time

- Participar de melhorias em processos (desenvolvimento, qualidade, agilidade e infraestrutura) dentro do time

**E o que você precisa ter/saber**

- Conhecimento avançado sobre testes (unidade, integração, funcionais, mocks, snapshoots, stubs, geração de casos / massas de dados, TDD, BDD)

- Cultura DevOps

- Agilidade (experiência com Scrum, Kanban e princípios ágeis)

- Design de APIs públicas

- Estruturas de Dados (Hashes, Filas, Árvores, Listas etc)

- Protocolos HTTP, TCP, UDP

- Programação pararela, concorrente e distribuída

- Programação funcional (escopos, closures e boas práticas)

- POO

- SOLID

- Design Patterns

- DDD / Clean Architecture

- Arquitetura em Camadas

- Orientação a Eventos

- Mensageria (message broker, event bus, filas)

- Bancos de Dados Relacionais / modelagem relacional (Postgre / Maria DB)

**E o que seria legal se você tivesse/soubesse** 

- NodeJS (ES6+)

- Bancos de Dados Orientados a Documentos (MongoDB)

- Bancos de Dados em Memória (Redis)

- AWS (ECS, EKS, ECR, RDS, EC2, S3, Serverless etc)

- Integrações CI/CD (Jenkins, Circle etc)

- Experiência com desenvolvimento de produto

- Análise e Design de Algoritmos

**Como é trabalhar na Bee 🐝**

Aqui na BeeTech somos como uma colmeia: trabalhamos juntos e ajudando uns aos outros, sempre focados em alcançar os melhores resultados. Nosso ambiente é acolhedor e a diversidade é respeitada. Aqui você pode meditar ou tirar um cochilo na hora no almoço, sabia?  Além disso, temos muitas ações que visam promover a integração de nosso time, olha só:

#IntegraBee: Um evento de integração que reúne todos da empresa, trazendo a história inspiradora de um dos Bees e seguido por comes e bebes (muitos bebes);

#De People pra Bee: Iniciativa mensal que traz temas sobre diversos assuntos que os próprios Bees pedem, como por exemplo  CNV, Oratória, e etc; Tudo isso para fortalecer ainda mais o time como um todo;

#Inside the hive: Evento mensal onde o nosso CEO compartilha os resultados da empresa e os desafios futuros da Hive. É o momento onde todos têm uma visão geral do que anda acontecendo em cada área.

Acreditamos que conhecimento é para ser compartilhado, por isso gostamos de abrir nossas portas para que a comunidade agregue com suas experiências através de Meetups e Tech Talks.

 Estamos na Faria Lima mas estamos também trabalhando remotamente mesmo voltando da quarentena

Como geralmente funciona o nosso processo seletivo 🔍

Inscrição

Entrevista com o RH

Entrevistas com o time/gestor 

Oferta 

**O que temos de benefícios? 💙💚**

Salário Competitivo 

Assistência Médica Allianz;

Vale Refeição ( R$ 30,00 / dia )

Vale Transporte;

 
Curtiu? Se candidate na nossa vaga e venha ser feliz! Caso você não se identifique com essa vaga, compartilhe com os seus amigos.

Link da Vaga
https://jobs.kenoby.com/beetech/job/sr-back-end-engineer/5ed64957656d4536376db7e1

Caso não consiga entrar no Link, pode mandar email para alex.kawaharada@beetech.global

 
#vemprabee  #remessaonline  #beeyourself

**Comment by drd-2rcl** [comment]
Só por curiosidade, o que são `Spikes` ?

**Comment by AlexKawaharada1981** [comment]
Oi Diogo,
Esse é o conceito de Spikes

What are Spikes in Agile?

A spike is a user story for which the team cannot estimate the effort
needed. In such a case, it is better to run time-boxed research,
exploration to learn about the issue or the possible solutions. As a result
of the spike, the team can break down the features into stories and
estimate them.

Em ter., 2 de jun. de 2020 às 14:14, Diogo R. Dias <notifications@github.com>
escreveu:

**Comment by drd-2rcl** [comment]
Legal, user story... acho incrível a capacidade que os agilistas (ou sei lá quem) tem de renomear conceitos bem fundamentados, sem a real necessidade de renomear. Enfim, só um desabafo =). Sorte nas contratações!

**Comment by AlexKawaharada1981** [comment]
Obrigado Diogo!

Em ter., 2 de jun. de 2020 às 17:11, Diogo R. Dias <notifications@github.com>
escreveu:

**Comment by guilhermeoa07** [comment]
Possibilidade de remoto pós quarentena?

**Comment by AlexKawaharada1981** [comment]
Sim Guilherme, após a quarentena vamos voltar remoto.

Em ter., 2 de jun. de 2020 às 21:27, Guilherme Oliveira <
notifications@github.com> escreveu:
