### ISSUE TITLE
[São José/SC] Programador(a) PHP - Canal Telecom Tecnologia

### ISSUE THREAD

**Issue by peopleti** [backend-br/vagas#2498]
A People TI busca profissional para atuar como Programador(a) PHP (júnior) na empresa Canal Telecom Tecnologia em São José/SC.

Especializada em Tecnologia da Informação & Comunicação, a Canal tem compromisso com seus colaboradores e seus serviços, oferecendo o que há de mais inovador para comunicações!

Atividades a serem desempenhadas:

Desenvolvimento em PHP, banco de dados relacional e serviços REST em soluções de voz sobre redes IP.
Realizar correções e melhorias em sistemas web. 
Requisitos:

PHP, HTML/CSS, Bootstrap, JavaScript, JQuery
MySQL/PostgreSQL
Linux e Windows
Apache, Eclipse, Netbeans
Conhecimentos desejáveis: Zend Framework, REST, Asterisk, Mobile e UX Design.

Benefícios:
VT
VR
Plano de saúde
Seguro de vida

Cadastre-se https://abler.in/v10449

**Comment by dvespasiano** [comment]
boa tarde, aceita remoto?

**Comment by peopleti** [comment]
> boa tarde, aceita remoto?

Olá! Agora durante a pandemia parte da empresa está remoto, mas a preferência será para presencial.
