### ISSUE TITLE
[São Paulo] Back-End Developer na [Talent Matching]

### ISSUE THREAD

**Issue by jeffersondev** [backend-br/vagas#25]
Fala Galera!

Trabalho numa das startups residentes do Cubo chamada Talent Matching.
Estamos contratando um Dev Back-End, é preciso conhecer Java (Spring) e gostar da parte de DevOps, pois também irá mexer na infra do sistema que está na Azure.

A vaga é para Pleno / Sênior, contratação CLT ou PJ (a combinar) e não aceita remoto.

Mais detalhes da vaga e como se candidatar:
https://cubo.network/jobs/89c05e80-bb46-11e7-b296-3b8bbbf8259d

Ou mandem um email para gustavo@talentmatching.com.br

Valeu!!!

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
