### ISSUE TITLE
[Campinas] Node.js Developer pleno ou sênior na [HDNIT]

### ISSUE THREAD

**Issue by marcelocpinheiro** [backend-br/vagas#2502]
Fala dev, tudo certo?

A HDN está crescendo e estamos estruturando nossas áreas de desenvolvimento. Nosso jeitão de startup está bem redondo, dinâmico e muito pronto para errar e aprender. 

Estamos buscando quem topa vir pra HDN por um propósito e aceitar o desafio na área de desenvolvimento, muito contato direto com os sócios. Aqui todos tem muita voz e oportunidades de crescimento (MUITA). 

A forma de contratação é por cooperativa + ajuda de custo, e o salário é a combinar.

**Requisitos obrigatórios**
Sólidas habilidades em Javascript - Nível Pleno/Senior;
Experiência com Typescript;
Experiência com Express;
Bom entendimento de git, bancos de dados (sql e nosql) e filas;
Conheça sobre construção, implantação e teste automatizados;
Conhecer conceitos de arquitetura e Design patterns;

**Nice to have**
Capacidade de realizar várias tarefas, ser uma pessoa organizada e detalhista;
Fortes habilidades no ambiente Unix / Linux;
Familiarizado com princípios ágeis;

**Como se candidatar**
Envie para marcelo.pinheiro@hdnti.com.br, seu perfil do LinkedIn completo ou CV e uma breve apresentação.
No assunto: Vaga Node.js

**Comment by danielkmx** [comment]
Tentei te enviar email e nao encontrou esse email, tenho interesse caso aceite remoto, meu email é danielbezerrakmx@gmail.com
