### ISSUE TITLE
[São Paulo] PHP Developer Sênior/Especialista PJ na D2P

### ISSUE THREAD

**Issue by SergioSCF** [backend-br/vagas#251]
## Descrição da vaga

Estamos procurando um desenvolvedor de nível Sênior/Especialista, que seja curioso e tenha muita vontade de aprender.

A pessoa trabalhará na arquitetura, desenvolvimento das aplicações, micro serviços, melhoria dos produtos e em novos projetos. Terá um papel importante no dia-a-dia de entrega de tarefas - especialmente as de complexidade média e alta.

## Local

Escritório, São Paulo - Av. Brigadeiro Faria Lima, 1903
(Mudança para a Vila Olímpia em Setembro)

## Requisitos

**Obrigatórios:**

- Fortes conhecimentos em PHP 5+ e Laravel
- Bancos relacionais (MySQL) e não relacionais
- APIs em REST
- MVC
- JQuery, Angular ou React
- Criação e manutenção de robôs (crawling)
- Serviços e APIs da AWS
- Linux (configuração de ambientes de desenvolvimento em Ubuntu)

**Desejáveis (não obrigatório):**
- ElasticSearch
- WebServices SOAP
- Conhecimento em outras linguagens de programação
- Conhecimentos em BigData e Machine Learning
- Docker

## Contratação

PJ

## Nossa empresa

A D2P é uma startup criada para importadores (B2B) utilizando tecnologia para reduzir os custos em suas importações. Somos um spin off de uma empresa de 25 anos no mercado de Comércio Exterior. Estamos em fase de pré-lançamento com alguns clientes no Brasil, mas nosso objetivo é ser uma plataforma global.

## Como se candidatar

Por favor envie um email para sergio.costa@i-d2p.com.br com seu CV anexado - enviar no assunto: Vaga PHP Sênior/Especialista

## Labels

- Alocado/presencial
- PJ
- Sênior
- Especialista

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
