### ISSUE TITLE
[HOME OFFICE] Desenvolvedor(a) Junior Full Stack .NET Core na Squadra Tecnologia

### ISSUE THREAD

**Issue by VictoriaBoaventura** [backend-br/vagas#2518]
## Descrição da vaga

Desenvolvimento de sistemas com .Net Core (c#)

## Local

Remoto ou Presencial (conforme preferencia do candidato e localidade)

## Benefícios

- Plano de saúde
- Plano odontológico
- VR
- Bolsa Certificação
- Acesso ao Alura, Udemy e PluralSigth
- Horário flexível

## Requisitos

**Obrigatórios:**

- Desenvolvimento de WebAPIs com c#
- Soluções de ORM (Entity Framework, NHibernate ou Dapper)
- SQL Server ou Oracle
- React e/ou Angular e/ou .Net MVC
- HTML5
- Java Script
- CSS
- GIT

## Contratação

CLT

## Como se candidatar

Para se inscrever envie seu currículo para victoria.boaventura@squadra.com.br - colocando no assunto: Desenvolvedor(a) Full Stack Jr

**Comment by figormartins** [comment]
A caixa de correio do destinatário está cheia e não pode aceitar mensagens no momento.

**Comment by VictoriaBoaventura** [comment]
> A caixa de correio do destinatário está cheia e não pode aceitar mensagens no momento.

Oi Igor, obrigada por sinalizar! recebemos seu currículo, essa mensagem chegou para você porque uma pessoa do grupo está com caixa cheia. de toda forma mudei na descrição da vaga!
