### ISSUE TITLE
[Campinas] Developer .Net na StarCorp

### ISSUE THREAD

**Issue by tmsouza** [backend-br/vagas#252]
## Descrição da vaga

Desenvolvimento de novas funcionalidades para a plataforma de e-commerce, incluindo integração de sistemas internos e de parceiros através de APIs REST/SOAP.

## Local

Escritório, Campinas - SP

## Requisitos

**Obrigatórios:**
- Experiência com .Net C#/MVC;
- Conhecimentos em programação orientada a objetos;
- Conhecimento em banco de dados SQL Server;
- Conhecimento em SVN ou GIT;

**Desejáveis:**
- Experiência em Entity Framework com ORM;
- Testes unitários.

## Contratação

PJ a combinar

## Nossa empresa

Somos especializados no desenvolvimento de sites, portais, intranets, extranets e APPs.

## Como se candidatar

Por favor envie um email para tiago.mendes@starcorp.tech com seu CV anexado - enviar no assunto: Vaga .Net

## Labels

- Alocado
- Júnior
- Pleno
- PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
