### ISSUE TITLE
[Brasília/DF] Desenvolvedor Java [Fóton Informática]

### ISSUE THREAD

**Issue by fotonti** [backend-br/vagas#2523]
### DESENVOLVEDOR JAVA I (PLENO)  BRASÍLIA (18 vagas)

O candidato ideal precisa ter:
- Graduação completa na área de TI
- Sólida experiência como Desenvolvedor Java
- Experiência e disponibilidade para atuar tanto em front-end quanto em back-end
- Front-End: AngularJs e/ou Angular 2+, Primefaces, HTML, CSS, JavaScript e Bootstrap
- Back-End: Java 8, JavaEE, Hibernate, EJB, Restful (JAX-RS), Soap (JAX-WS)
- Spring Boot 2 (Spring Data, Spring Batch)
- Banco de Dados: Postgres, SQL Server
- Jboss, Maven, Teste Unitário, JMS e Git
- Disponibilidade para aprender novas tecnologias
- Atuação em projetos com metodologia Ágil Scrum

**Desejável:** Oracle Certified Professional – Java SE Programmer (Versão 5 ou Superior)

**Modalidade de trabalho:** presencial, alocado no cliente.

**Nossos benefícios:** Plano de Saúde nacional, Plano Odontológico, Seguro de Vida, Vale Alimentação / Refeição, Programa de Incentivo à Educação, Programa de Incentivo a Certificações e Auxílio Creche (para as fotonianas).

A Fóton Informática é uma empresa de tecnologia especializada no mercado financeiro. Ajudamos a transformar o dia a dia dos bancos e da população brasileira, criando soluções que permitam uma maior aproximação das instituições bancárias a seus clientes (mobile banking, caixa eletrônico, agência, etc). Também atuamos como parceiros especializados no desenvolvimento e manutenção de produtos e serviços financeiros.

### Venha fazer parte do nosso time!
Envie-nos o seu currículo através do email rh@foton.la informando no campo assunto a vaga pretendida (Desenvolvedor Java - Brasília). 

Essa e outras vagas você pode conferir em http://www.foton.la/oportunidades

**Comment by bosofelipe** [comment]
olá apenas vaga presencial?

**Comment by fotonti** [comment]
Bom dia

Sim.

Em qua., 10 de jun. de 2020 às 17:07, Felipe Thiago Boso <
notifications@github.com> escreveu:
