### ISSUE TITLE
[São Paulo] Vaga: Data Engineer and Back-End Architect 

### ISSUE THREAD

**Issue by danielyluz** [backend-br/vagas#253]
•	Desenvolver e executar um Data Warehouse e uma solução ETL / ELT escalável e que serão utilizados por analistas de negócios e principais tomadores de decisão.
•	Conhecer de cor a estrutura de dados e tudo o que há para saber sobre os bancos de dados da empresa para fornecer suporte para usuários finais e desenvolvedores.
•	Certificar-se de que todos os processos, relatórios, KPIs e ETL / ELT estejam sendo executados corretamente e sem problemas em tempo real.
•	Ser a referência para consultar sobre banco de dados de grandes dimensões.
•	Apresentar capacidade de contribuir com otimizações de arquitetura de ETL, ELT, BI e o ciclo de vida de uma solução EDW.
•	Uma compreensão da integração de dados usando Python e conhecimento de bancos de dados MySQL e PostgreSQL e tecnologias e padrões associados.
•	Capacidade de obter dados de APIs RESTful.

Interessados enviar currículo para: daniely.santos@neoatlas.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
