### ISSUE TITLE
[São Paulo/SP] PHP Developer na PicPay

### ISSUE THREAD

**Issue by tcassiano** [backend-br/vagas#2533]
## Descrição da vaga

O PicPay quer mudar a maneira de como lidamos com o dinheiro, tanto pessoal quanto profissionalmente. Somos uma plataforma de pagamentos criada para quebrar barreiras e eliminar burocracias. Sendo assim, nós existimos para melhorar a vida das pessoas e só conseguimos fazer isso porque temos um time fantástico aqui dentro!

Contamos com uma equipe de mais de 1.200 PicPay Lovers - engenheiros, desenvolvedores, profissionais de marketing, designers, criadores, nerds loucos e mais um punhado de profissionais sonhadores que dedicam suas horas desafiando as regras de tempo x propósito.

Buscamos pessoas que sejam apaixonadas por construir aplicações distribuídas e de alta performance, escaláveis para milhões de novos usuários em todo o mundo e que suportem a melhor experiência de pagamentos. Somos um dos melhores lugares para se trabalhar no Brasil (pelo menos as nossas pessoas acham isso)!

Manda bem nos requisitos abaixo? Então essa vaga é pra você! (:

Junte-se ao lado verde da força!

## Local

Remoto, São Paulo/SP

## Benefícios

- Assistências médica (você e +1 dependente ficam por nossa conta!);
- Assistência odontológica;
- Seguro de vida;
- Vale Transporte e/ou Auxílio combustível;
- Vale Refeição e/ou Vale Alimentação;
- Vale Cultura;
- PicPay Acolhe - Programa que cuida da gente e dos nossos familiares, oferecendo apoio jurídico, social, psicológico e financeiro;
- PPR - Participação nos Resultados do PicPay;
- Horário flexível e possibilidade de home office.
#### Diferenciais

- Participar de projetos com times multidisciplinares e inovadores;
- Ter a oportunidade de ser o protagonista da sua vida;
- Vivenciar a realidade move fast de uma startup;
- Aprender e se reinventar a todo instante (ser sua melhor versão a cada novo desafio);
- Ter um ambiente inovador que proporciona crescimento e desenvolvimento constantes, com profissionais incríveis e visionários;
- Ter uma liderança inspiradora;
- Ser quem você é! Nós apoiamos a diversidade e não fazemos distinção de raça, religião, deficiência, gênero ou orientação sexual.

## Requisitos

**Obrigatórios:**
- PHP 7.*;
- Frameworks Laravel ou Lumen, com ênfase em aplicações RESTful;
- Armazenamento de dados em MySQL (ou outros bancos relacionais) ou MongoDB (ou outros bancos não relacionais);
- Ambiente de desenvolvimento com Docker;
- Atenção para qualidade de código e design patterns;
- Desenvolvimento orientado a testes;
- Versionamento de códigos utilizando Git.

**Diferenciais:**
- Metodologias ágeis;
- Design e desenvolvimento de micro serviços horizontalmente escaláveis;
- Jobs de alto desempenho e comunicação entre serviços utilizando soluções de fila como Beanstalk, RabbitMQ, Kafka, etc;
- Conhecimento dos riscos comuns de segurança (OWASP).

## Nossa empresa

Estamos crescendo rápido (a-ce-le-ra-dos). Nos últimos 2 anos, o PicPay conquistou milhões de usuários e para 2020, o ritmo será ainda mais elevado!E sabe por quê? Nós temos um time de pessoas fantásticas e que amam o que fazem. Somos #PicPayLovers.

O que nos move?

Queremos tornar pagamentos cada vez mais invisíveis, por meio de experiências mais simples e desburocratizadas.

## Como se candidatar

https://bit.ly/3feUqop

### Alocação:
- Remoto

### Contratação:
- Não informado

### Experiência
- Pleno

**Comment by joubertredrat** [comment]
@tcassiano Esta vaga é remoto permanente ou remoto por conta da pandemia?
