### ISSUE TITLE
[Remoto] Backend Developer na Gerencianet Pagamentos

### ISSUE THREAD

**Issue by tuliospuri** [backend-br/vagas#2535]
## Atividades principais

- Desenvolvimento de soluções no ramo de pagamentos;
- Integração de microsserviços com serviços internos e externos:
  - SFN – Sistema Financeiro Nacional;
  - CIP – Câmara Interbancária de Pagamentos.

## Requisitos

- Experiência com análise e desenvolvimento de sistemas;
- Capacidade de analisar problemas e propor soluções;

* JavaScript / TypeScript (Node.js);
* MySQL;
* Git;
* Restful com JSON;
* Testes automatizados (Mocha, Sinon).

## Diferencial

- Domain-driven design e SOLID;
- Event-driven architecture;
- Noções de AWS (SQS, SNS, S3, DynamoDB);
- MongoDB;
- Redis;
- Arquitetura de microsserviços.

## Desejável

- Shell Script, Linux, OAuth;
- Vagrant;
- Inglês técnico;
- Swagger (OpenAPI 3);
- PHP.

## Salário

- A partir de R$ 7.000,00 para Pleno;
- A partir de R$ 9.000,00 para Sênior;

## Local de Trabalho

Home Office

## Horário

- 40 horas semanais; 
- De segunda a sexta-feira;
- De 07:30 às 16:30.

## Experiência

- Pleno
- Sênior

## Benefícios

- Plano de Saúde e Odontológico para colaboradores e dependentes;
- Bolsa de estudos e bolsa de idiomas para colaboradores;
- Bolsa de estudos para dependentes de até 17 anos;
- Vale Alimentação no valor de R$ 750,00;
- Vale Refeição (R$30,00 por dia);
- Participação nos resultados;
- Licença maternidade e licença paternidade estendida;
- Vale Transporte;
- Ambiente de trabalho descontraído e propício para o aprendizado.

## Como se candidatar

https://gerencianet.com.br/trabalheconosco

### Labels

- AWS
- CLT
- Full Time
- Git
- Imediato
- MySQL
- NodeJS
- NoSQL
- Pleno
- Remoto
- Rest
- Senior
- Swagger
- Testes automatizados

**Comment by italorangel** [comment]
Oportunidade para encaixar um júnior no time?

**Comment by tuliospuri** [comment]
Oi @italorangel, nosso processo para júnior está parado no momento, mas não é definitivo. Continue acompanhando nossas vagas em https://gerencianet.com.br/trabalheconosco, quem sabe não voltamos a nos falar no futuro!? 🤜🏻🤛🏻

**Comment by tuliospuri** [comment]
UPDATE: Processo seletivo em execução. Ainda estamos recebendo candidatos.

**Comment by tuliospuri** [comment]
Issue fechada e reaberta devido ao autolabel.
