### ISSUE TITLE
[São Paulo] Backend Developer na [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#254]
- Desenvolvimento de API;
- Experiência com Node e Backend;
- Desenvolver melhorias e novas aplicações de sistema existente na empresa;
- Contratação CLT;
- Local de trabalho: Vila Olímpia - São Paulo, SP
- Para atuar de forma presencial.

Os interessados ou que possuem colegas para indicar, podem encaminhar o contato ou currículo ao e-mail: raquel.lourenco@roberthalf.com.br

**Comment by rbezerra** [comment]
apenas alocado ou aceitam remoto?

**Comment by RaquelTavaresL** [comment]
Olá Ramon, tudo bem?

Somente de forma presencial.

Fico à disposição!

Raquel Lourenço
Recruitment Specialist
T: + 55 11 3382 0195   C: +55 119 5402 8154   S: 89395
Connect with us: LinkedIn<http://www.linkedin.com/groups?home=&gid=1925884&trk=anet_ug_hm> | Facebook<https://www.facebook.com/roberthalfbrasil> | Twitter<https://twitter.com/RobertHalf_BR> | YouTube<http://www.youtube.com/roberthalfbr> | Blog<http://worklife.roberthalf.com.br/?utm_source=signature&utm_medium=email&utm_campaign=worklife>
Robert Half Av. Dr. Cardoso de Melo | 1184 | 11° andar | São Paulo | SP - 04548-004


[cid:image004.jpg@01D3D02E.E11B1D80]

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
