### ISSUE TITLE
[São Paulo] BACKEND SR Developer na [XP]

### ISSUE THREAD

**Issue by FrancieleMarcaDaRosa** [backend-br/vagas#255]
Se você é fera em design patterns, S.O.L.I.D, WCF, Json, Entity Framework, DDD e TDD, é você que procuramos!

Empresa do ramo de investimentos, região da Faria Lima - SP.

Modelo de contratação CLT + benefícios.

Currículos devem ser direcionados para franciele@imaginebeyond.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
