### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Ruby on Rails (API) na iMusics

### ISSUE THREAD

**Issue by monteirobrena** [backend-br/vagas#2566]
## Nossa empresa

Nosso propósito é revolucionar o universo da música oferecendo tudo o que músicos e selos precisam de uma forma justa.

Dizem que trabalhar com música é muito bom, e podemos afirmar que realmente é f… de bom! Parafraseando alguém famoso, aqui acreditamos que a vida sem música seria um erro.

Somos uma empresa sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência ou idade. Profissionais LGBTQI+ são super bem-vindos.

## Descrição da vaga

Estamos com vaga para pessoa desenvolvedora de software, mas pra trabalhar com a gente você precisa, primeiramente, se identificar com nossos valores e com nossos compromissos junto ao mercado. Somos feitos de pessoas acima da média que adoram trabalhar e serem desafiados, questionadores, que não têm medo das ideias criativas e desafiadoras e que vêem significado naquilo que fazemos e proporcionamos a nossos usuários.

Buscamos alguém com foco em desenvolvimento back-end e com conhecimento em Ruby on Rails para desenvolver integrações via API RESTful.

Procuramos alguém multitasking, que não tenha medo de perguntar e de dar opinião, e que saiba principalmente a hora de ouvir. Que tenha um pensamento crítico e que vá além do código para avaliar, opinar e nos ajudar a construir produtos e serviços úteis, funcionais e sensacionais.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5+ anos de experiência com Ruby on Rails
- Desenvolvimento de APIs
- Integração entre APIs

**Desejáveis:**
- Conhecimentos em testes

**Diferenciais:**
- Experiência com otimização
- Experiência em desenvolvimento de regras e validações de segurança

## Benefícios

- Home office
- Internet
- Ajuda para cursos de especialização
- Possibilidades de prêmios financeiros

## Contratação

PJ

## Como se candidatar

Envie um email para **code@imusics.com** contando um pouco da sua experiência como dev, o que você tem estudado e desenvolvido nos últimos anos, faixa salarial pretendida e seu currículo.

## Processo de seleção

 1. Análise curricular 
Verificamos se seu perfil está dentro do que buscamos.

2. Teste
Code! Code! Code!

3. Entrevista técnica
Vamos conversar sobre o código desenvolvido e conhecer melhor seu jeito de programar.

4. Entervista interpessoal
Bate-papo pra identificar aquele match de valores.

5. Proposta
Se tudo se encaixar a gente te envia uma proposta desafiadora.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: code@imusics.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by casssiahaluu** [comment]
Trabalho nesse time há um ano. Recomendo super!

**Comment by marcospedro97** [comment]
Tem vagas junior?

**Comment by monteirobrena** [comment]
> Tem vagas junior?

@marcospedro97 no momento não, infelizmente. Obrigada pelo interesse.
