### ISSUE TITLE
[Remoto] Desenvolvedor(a) Ruby @ LocalLabs

### ISSUE THREAD

**Issue by krsmurata** [backend-br/vagas#2573]
A LocaLabs é uma empresa americana com sede em Chicago, IL contando com times de desenvolvimento espalhados pelo mundo, mas temos preferência por contratar brasileiros.

É um ambiente com diversas tecnologias e entre elas podemos destacar: Go, Elixir, Vue.js, Docker, PostgreSQL/MySQL e ElasticSearch, porém temos como foco central o uso de Ruby (e Rails) nos projetos principais.

Estamos procurando programadores(as) já com experiência sólida em Ruby, mas agnóstico quanto à linguagem de programação, podendo explorar novas tecnologias quando fizer sentido e intercambiar entre os diversos projetos que temos.

 É necessário também entendimento profundo em boas práticas de performance (ie. slow SQL queries, cache strategies e escalabilidade) além de conhecimento em front-end, podendo fazer alterações em JS/CSS/HTML (e não o design em si) facilmente.

Faixa salarial: $ 2.000,00 à $ 3.000,00 (USD)
Local: Remoto
Contratação PJ

**Requisitos**

- inglês avançado: leitura e escrita
- experiência sólida com Ruby e Rails
- experiência ou desejo de aprender Go
- bem versado em Javascript, CSS e HTML
- saber lidar com mappings complexos, clustering e táticas de reindex no ElasticSearch
- consegue criar, manter e consumir APIs diversas
- otimização de aplicações que consomem APIs
- considera code reviews necessários
- não vive sem versionamento de código no Git

**Algo [+]**

- experiência com Elixir, Vue.js ou PostGIS (temos projetos em várias linguagens)
- faz o desjejum comendo micro-services no café da manhã
- já trabalhou com multi-tenant apps e sabe quais os desafios
- alguma experiência prévia com trabalho/estudo remoto 

**Benefícios**

- revisão de salário progressiva anual
- custeio de conferências/estudos/cursos

**Processo seleção**

- avaliação do CV e compatibilidade com a vaga
- teste online com prazo definido de acordo com a disponibilidade do candidato
- entrevista via Skype/Hangout em português

**Como se candidatar**

Para se candidatar basta enviar o CV no email kris.murata+jobs@locallabs.com, alguma apresentação breve, **pretensão salarial** e código (github, bitbucket, etc..).

**Nível**

Pleno e Senior

**Comment by krsmurata** [comment]
Atualizando para avisar que ainda estamos com vagas em aberto. 🚀

**Comment by krsmurata** [comment]
Ainda temos uma vaga em aberto. 🚀 ☕

**Comment by vandaimer** [comment]
@krsmurata Alguma outra oportunidade focada em Backend?

**Comment by guicattani** [comment]
@krsmurata mandei email mas não houve retorno, ainda tem vaga em aberto?
