### ISSUE TITLE
[Belo Horizonte/MG ou São Paulo/SP] Desenvolvedor Java | Avenue Code

### ISSUE THREAD

**Issue by TalentAcquisiton** [backend-br/vagas#258]
Descrição da vaga
•	Experiência com desenvolvimento em Java;
•	Forte conhecimento em padrões de projetos;
•	Experiência com conectividade de banco de dados em Java;
•	Experiência com ORM Java frameworks (Hibernate preferível);
•	Experiência com ferramentas de controle de código: Git (preferível), Svn…;
•	Experiência com ferramentas de automção de build: ant, maven, gradle…;
•	Experiência com TDD e testes de software: jUnit, TestNg, Mock frameworks …;
•	Experiência com implementação SOA em Java (SOAP, REST, JMS, JAX/RS, JAX/WS);
•	Experiência em ferramentas de QA para automação de testes (Ruby, Cucumber, Selenium Webdriver e Capybara);
•	Capacidade de escrever de forma clara API’s e documentação para outros desenvolvedores e analistas;
•	Inglês avançado.

Local
Belo Horizonte/MG ou São Paulo/SP - Alocado

Benefícios
VT + VR + Plano de Saúde + Plano Ondontológico + Aulas de Inglês + PLR + Bonus por Performance ...

Nossa empresa
A Avenue Code é a principal consultoria de software focada na entrega de soluções de desenvolvimento ponta a ponta para a transformação digital em todas as vertentes. Com sede em São Francisco e três escritórios adicionais (Nova Iorque, Belo Horizonte e São Paulo) a Avenue Code é uma empresa 100% financiada com capital privado, rentável, e apresenta uma sólida trajetória de crescimento desde o primeiro dia. Nós nos preocupamos profundamente com nossos clientes, nossos parceiros e nossos consultores. Preferimos a palavra "parceiro" a "fornecedor" e nossos investimentos nos relacionamentos profissionais são um reflexo dessa filosofia. Temos muito orgulho da nossa perspicácia técnica, da nossa capacidade colaborativa de resolução de problemas e do calor e profissionalismo dos nossos consultores.

Como se candidatar
Cnadidate-se através do link: https://www.avenuecode.com/careers/belo-horizonte-mg/desenvolvedor-a-java/
Ou envie seu currículo para pvalle@avenuecode.com com o assunto "JAVA DEV"

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
