### ISSUE TITLE
[Remoto/Bragança Paulista-SP] PHP Developer na NUVEMSHOP

### ISSUE THREAD

**Issue by LucascrMota** [backend-br/vagas#2585]
## Nossa empresa

Nuvemshop é o produto digital que +40.000 marcas na América Latina escolhe para potencializar seus negócios. É um ponto de gestão que vai além de uma loja online. Integra produtos, pagamentos e envios com diferentes canais de vendas como Facebook, Instagram, marketplaces e lojas físicas. 
Atualmente 1 venda é feita a cada 5 segundos nas lojas que utilizam o produto, que são visitadas por pelo menos 20% dos usuários de internet na América Latina.

Graças à sua tecnologia, Nuvemshop se adapta a cada tipo de negócio de formas diferentes: permitindo que o layout de cada loja seja único, dando a possibilidade de instalar aplicações e de integrar desenvolvimento à medida. Tudo isso com o acompanhamento de uma excelente equipe de atenção ao cliente.
## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Exemplo: Remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios e desejáveis:**
+4 anos de experiência na linguagem PHP e seu ecossistema. (obrigatório)
Sólidos conhecimentos em programação orientada a objetos.
Sólidos conhecimentos do protocolo HTTP.
Sólidos conhecimentos de HTML / CSS / JS.
Experiência em testes unitários (PHPUnit, Mockery).
Experiência com desenvolvimento e versionamento de APIs.
Experiência em Laravel, Symfony, Zend Framework ou similares.
Experiência no uso de bancos de dados relacionais como MySQL.
Conhecimento de ambientes Unix.
Leitura e compreensão de textos em inglês.

**Diferenciais:**
Experiência com metodologias ágeis.
Experiência em arquitetura baseada em microsserviços.
Conhecimento e experiência com React.
Conhecimento e experiência com Scala.
Conhecimento e experiência com Java.
Falar espanhol.

## Benefícios

Plano de Saúde e Odontológico Bradesco, com cobertura nacional;
Vale Transporte (ou Vale Combustível); 
Vale Refeição (ou Vale Alimentação);
Auxílio Creche;
Ajustes salariais semestrais por desempenho.
3 dias por ano para participar de conferências relacionadas ao desafio;
1 loja gratuita para uso do colaborador ou alguém próximo a você;
Aulas semanais de espanhol no escritório;
Horário flexível;
Seguro de vida.

## Contratação

CLT com salário de até R$10.500,00 a depender da experiência

## Como se candidatar

Nesse link: https://bit.ly/3fTMysG  você vai ter toda a explicação da oportunidade e a opção de se cadastrar!
Qualquer dúvida, pode entrar em contato com lucas.mota@byintera.com

## Tempo médio de feedbacks

Na Intera, mantemos o contato e enviamos feedback em até 2 dias úteis após cada etapa!
E-mail para contato em caso de não haver resposta: lucas.mota@byintera.com

#### Alocação
- Remoto pelo menos até o final do ano

#### Regime
- CLT

#### Nível
- Sênior

**Comment by tiago123456789** [comment]
A vaga está em aberto?
