### ISSUE TITLE
[RIO DE JANEIRO] Back End Developer na MJV Technology & Innovation

### ISSUE THREAD

**Issue by RHRJ** [backend-br/vagas#259]
A MJV é uma consultoria global dedicada a transformar negócios por meio da inovação e da tecnologia presente em 6 países e em busca de crescer sempre mais! 

Você pode ver mais sobre a nossa história aqui: https://vimeo.com/269521857/87217f2322

Atualmente, nós estamos com oportunidades Back End para atuar tanto em projetos quanto em contratações Full.

Requisitos:

- Conhecimento em NodeJS e experiência em Git e uso de CI/CD
- Experiência com desenvolvimento de APIs REST
- Experiência em MySQL.

Desejável: Experiência com serviços AWS (ou equivalentes Azure): API-Gateway, AWS Lambda, Simple Notification Service, S3, RDS, EC2, ECS; 
Experiência com desenvolvimento de microsserviços usando Docker

Contrato RPA, PJ ou CLT 

Local: Centro/RJ

Interessados enviar CV para rhrj@mjv.com.br

## Labels

- Alocado
- CLT
- Júnior 
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
