### ISSUE TITLE
[Remoto] Back-end Developer @Atados

### ISSUE THREAD

**Issue by vinpac** [backend-br/vagas#2590]
## Nossa empresa

Somos uma organização que mobiliza pessoas e empresas para o engajamento social. Hoje nosso maior projeto é nossa plataforma de voluntariado que conecta pessoas com projetos sociais. Além disso, oferecemos consultoria de responsabilidade social para empresas.

Atualmente estamos trabalhando em combate as consequências do COVID-19 com projetos de doação, voluntariado remoto ou presencial para emergências, doação de máscaras, cestas básicas e vários outros projetos que você pode encontrar no nosso site (atados.com.br). Algumas empresas que já trabalhamos: Samsung, Boticário, Coca-Cola, Carrefour, Via Varejo, Shell.

## Descrição da vaga

Nosso projeto é nossa plataforma de voluntariado (atados.com.br) que funciona em modelo SaaS. Hoje nós temos 10 clientes que utilizam nossa plataforma (empresas ou movimentos) para conectar ainda mais pessoas com projetos sociais.

O back-end é em Django, porém estamos caminhando para trabalhar mais com microsserviços. Nosso novo microsserviço para gerenciar notificações é escrito em Node JS e usa o Hasura para criar o banco e as disponibilizar uma interface GraphQL.

Periodicamente trabalhamos em projetos paralelos, como a nossa última plataforma Conectados Pelo Futuro. O back-end foi feito com Hasura e Node.js. O front-end com Next.js, React e Typescript.

https://www1.folha.uol.com.br/empreendedorsocial/2020/06/samsung-lanca-voluntariado-online-para-orientar-jovens-sobre-o-mercado-de-trabalho.shtml

Segue listado todas as tecnologias que usamos em back-end: django, django-rest-framework, celery, rabbitmq, redis, postgresql, elasticsearch, hasura, express, apollo-server.

## Local

Você tem total liberdade para trabalhar remoto (mesmo após a pandemia) ou trabalhar em uma de nossas casas em São Paulo (2 min a pé do Metrô Fradique Coutinho, em Pinheiros) ou Rio de Janeiro (a 4 min a pé do metrô Saens Peña, no bairro da Tijuca). Atualmente estamos trabalhando remotamente devido ao isolamento social.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com linguagens Back End
- 2 anos de experiência com Postgres ou MySQL

**Desejáveis:**
- Conhecimentos em Django ou Flask
- Conhecimento em Node.Js
- Conhecimento em Typescript

**Diferenciais:**
- Projetos open source
- Conhecimento em Hasura
- Já ter feito voluntariado

## Contratação

PJ 

## Como se candidatar

Envie um email para pacheco@atados.com.br com seu CV ou link do Github, site ou qualquer projeto que demonstre seu trabalho - enviar no assunto: Vaga Back End - <seu nome>

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by vinpac** [comment]
Atualizamos a vaga. Tivemos um imprevisto com um candidato que aceitou outra vaga de ultima hora :/

Mas sem caô, estamos buscando novamente! Mande seu perfil :D

**Comment by vmesel** [comment]
@vinpac podemos fechar a vaga aqui para podermos trabalhar via PyJobs?
