### ISSUE TITLE
[Curitiba] DevOps na [LeHype][PJ][Cloud][WebServer]

### ISSUE THREAD

**Issue by barbraeliza** [backend-br/vagas#26]
Tudo bem galera?

Tô precisando de um DevOps que de preferência esteja na região sudeste/sul para ser um parceiro PJ da LeHype.

O perfil dos sites são de 80% de sites com baixo fluxo de acesso, uma baixa porcentagem deles pode ter um fluxo maior, mas podemos investigar para saber exatamente o tamanho disso.

Hoje temos cerca de 5 clientes para iniciar nesse server, precisamos de uma solução que possa crescer sem a necessidade de migração para uma outra plataforma no futuro, nossa meta para 2018 é de 20 sites nesse ambiente.

Precisamos nos preocupar também com backups atualizados, ter um ambiente de testes para sites em desenvolvimento, sem que isso interfira no desempenho dos sites que já estão em live.

**Comment by soujhony** [comment]
Legal, manda mais detalhes do que você esta precisando para o meu email jhonystein[at]gmail.com

**Comment by reginaldojunior** [comment]
A vaga foi preenchida?
