### ISSUE TITLE
[Remoto/Vinhedo-SP] Desenvolvedor NodeJS @ AutoAvaliar

### ISSUE THREAD

**Issue by dias-joao** [backend-br/vagas#2604]
**DESENVOLVEDOR NODE JS**
REMOTO PARA TODO BRASIL E PARA BRASILEIROS VIVENDO NO EXTERIOR!

Somos uma empresa brasileira com presença em 6 países. Nossos escritórios no Brasil se dividem entre São Paulo, com a parte administrativa e comercial, e Vinhedo, com um prédio inteiro dedicado ao desenvolvimento e suporte de nossas soluções web e mobile.

Começamos em 2013, quando juntamos um time com muita experiência no mercado automotivo, com um time fera em tecnologia. Esse é um dos segredos de nosso sucesso: unimos a prática à teoria para criar soluções verdadeiramente valorosas para o mercado. O resultado? Revolucionamos o segmento automotivo!

A gente vai longe, mas não esquecemos os nossos valores, daquilo que nos define. Qualquer decisão, qualquer solução e qualquer colaborador, tem que estar de acordo com 4 valores essenciais: Transparência, Rentabilidade, Segurança e Eficiência

**Buscamos talentos que:**

Sonham alto, gostam de contribuir com as suas opiniões, não tenham medo de desafiar os padrões e que, acima de tudo estejam dispostos a contribuir com um negócio em constante inovação! 

A Auto Avaliar valoriza a diversidade e igualdade. Esperamos também receber muitas inscrições de candidatos com deficiência, refugiados e público LGBTQ+!

**Conhecimentos técnicos desejáveis:**

- RESTful APIs;
- JavaScript ES6;
- Express e Sequelize framework;
- Experiência com ferramentas como Babel e NPM;
- Banco de dados (Postgres, MYSQL, MongoDB);
- Controle de versão GIT;

Quer nos encantar? Se você não conhecer algumas das tecnologias abaixo, sem problemas, aqui você poderá aprender! 

- Google Cloud;
- Continuous Integration
- Micro Serviços;
- Mensageria;
- Trabalhos assíncronos em fila;
- Angular ou ReactJs;
- ES6;
- DDD;

 **O que oferecemos?**

-Imersão numa cultura de agilidade, respeito e inovação;
-Plano de desenvolvimento técnico e de carreira
-Ganhos compatíveis com o mercado e na modalidade PJ - pessoa jurídica.
-Assistência médica Amil;
-PLR - Participação nos Lucros e Resultados;
-Parceria com diversos estabelecimentos (escola de idioma/ cursos / academias / lojas e etc).

E no nosso Techcenter em Vinhedo, oferecemos ainda:

-Frutinhas frescas todos os dias (uma delícia)
-Área de descompressão
-Mesa de sinuca
-Vídeo game
-Muito café gostoso!

Clima animado, happy hours na empresa, churrasco, dia do hamburger, dia do doce, aniversariantes do mês (adoramos uma festa!)

Neste momento não estamos conseguindo aproveitar alguns dos pontos acima por conta do COVID, mas esperamos em breve retomar nosso convívio e normalidade!

Se identificou com essa oportunidade e com nossa cultura? Venha fazer parte desse time vencedor e acelere seu desenvolvimento!!

Gostou? Se candidate: [https://www.linkedin.com/jobs/view/1901161629/](url)

**Comment by cristianomg** [comment]
o link não está funcionando.

**Comment by williamisaque1** [comment]
copia o link e cola no browser :)

**Comment by dvdscripter** [comment]
A seleção já começou no anúncio

Em qui., 25 de jun. de 2020 às 20:45, williamisaque1 <
notifications@github.com> escreveu:

**Comment by THAYLLER** [comment]
vaga ainda aberta?
