### ISSUE TITLE
[MORUMBI/SP] Python Developer Pleno @Confitec

### ISSUE THREAD

**Issue by DaiannaCs** [backend-br/vagas#2608]
## Nossa empresa

Somos especialistas em softwares voltados ao mercado segurador. Estamos ajudando a impulsionar a transformação no setor de seguros no Brasil. Estamos presentes em São Paulo e Rio de Janeiro, duas das principais capitais do país.
Você fará parte de um time de desenvolvedores extremamente qualificado fortemente orientado a resultados e que não tem medo de inovar.
Você será parte vital no desenvolvimento da nova plataforma de um de nossos principais clientes, trabalhando com boas práticas de desenvolvimento em um ambiente dinâmico que incentiva a autonomia e o aprendizado constante.
Estamos crescendo e precisamos de pessoas que amem tecnologia e que sejam fascinadas por aprender!

## Local

Escritório, São Paulo - Morumbi

## Requisitos

**Obrigatórios:**

- Python
- Familiaridade com APIs.
- Frameworks: Flask ou Django.

**Seria fantástico se o seu background tivesse:**
- GIT.
- AWS.
- Conhecimento em metodologia ágil.
- Data Lake

## Benefícios

- Plano de saúde.
- Plano odontológico;
- Vale Transporte;
- Vale-Refeição;
- Auxílio-creche;
- PLR;

**Diferenciais:**
- Incentivo a cursos e certificações;
- Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
- Flexibilidade de horários;
- Café da manhã toda sexta-feira;
- Comemoração mensal dos aniversariantes;
- Sala de Descompressão;
- Campeonatos de futebol;
- Day off no mês do seu aniversário;

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para daianna.souza@confitec.com.br com seu CV anexado - enviar no assunto: Vaga Pyhton - SP

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: curriculos@confitec.com.br

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by gabrielangelo** [comment]
Bom dia, aceita remoto ?

**Comment by DaiannaCs** [comment]
> Bom dia, aceita remoto ?

Olá Gabriel, somente presencial.

**Comment by xspager** [comment]
Boa tarde Daianna, vocês tem escritório aqui no Rio?
Eu tenho disposição para me relocar mas queria saber se vocês tem escritório no Rio ou se no momento atual a vaga seria temporariamente remota.
