### ISSUE TITLE
[RIO DE JANEIRO] Developer  ASP Pleno [CTIS]

### ISSUE THREAD

**Issue by ernanijunior** [backend-br/vagas#261]
Oportunidade Rio de Janeiro (capital) -  Analista desenvolvedor ASP e PL-SQL
Profissional com graduação ou pós em TI 
Requisitos: 
- Mínimo de 4 anos de experiência em análise e desenvolvimento de sistemas.
- Proficiência no desenvolvimento de aplicações em linguagem ASP (Clássico).
- Domínio de Javascript
- Desenvolvimento básico em PL-SQL.

Diferencial: 
- Habilidade no relacionamento com usuários
- Conhecimento de mapeamento de processos e ferramentas de BPMN 
- Conhecimento em ferramentas GED
- Conhecimento de JAVA; e/ou PHP e/ou Delphi será um diferencial.
Enviar CV para: selecao.031016@gmail.com com o assunto: “Analista desenvolvedor ASP e PL-SQL Pleno”

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
