### ISSUE TITLE
[REMOTO] Back-end Developer na Gerencianet Pagamentos

### ISSUE THREAD

**Issue by tuliospuri** [backend-br/vagas#2610]
## Atividades principais

- Desenvolvimento de soluções no ramo de pagamentos;
- Integração de microsserviços com serviços internos e externos:
  - SFN – Sistema Financeiro Nacional;
  - CIP – Câmara Interbancária de Pagamentos.

## Requisitos

- Experiência com análise e desenvolvimento de sistemas;
- Capacidade de analisar problemas e propor soluções;

* JavaScript / TypeScript (Node.js);
* MySQL;
* Git;
* Restful com JSON;
* Testes automatizados (Mocha, Sinon).

## Diferencial

- Domain-driven design e SOLID;
- Event-driven architecture;
- Noções de AWS (SQS, SNS, S3, DynamoDB);
- MongoDB;
- Redis;
- Arquitetura de microsserviços.

## Desejável

- Shell Script, Linux, OAuth;
- Vagrant;
- Inglês técnico;
- Swagger (OpenAPI 3);
- PHP.

## Salário

- A partir de R$ 7.000,00 para Pleno;
- A partir de R$ 9.000,00 para Sênior;

## Local de Trabalho

Home Office

## Horário

- 40 horas semanais; 
- De segunda a sexta-feira;
- De 07:30 às 16:30.

## Experiência

- Pleno
- Sênior

## Benefícios

- Plano de Saúde e Odontológico para colaboradores e dependentes;
- Bolsa de estudos e bolsa de idiomas para colaboradores;
- Bolsa de estudos para dependentes de até 17 anos;
- Vale Alimentação no valor de R$ 750,00;
- Vale Refeição (R$30,00 por dia);
- Participação nos resultados;
- Licença maternidade e licença paternidade estendida;
- Vale Transporte;
- Ambiente de trabalho descontraído e propício para o aprendizado.

## Formação

Superior Completa em Sistemas de Informações, Ciência da Computação ou áreas similares;

## Como se candidatar

https://gerencianet.com.br/trabalheconosco

**Comment by Reginaldo1239** [comment]
me reprovaram antes de fazer o teste, manda o teste para min

**Comment by tiago123456789** [comment]
Bom dia @tuliospuri! Eu me inscrevi para a vaga mas não tive retorno. Vocês costumam dar feedback para os candidatos?

**Comment by rodsoa** [comment]
Então, passei pelo mesmo. Na real eles querem 'curriculo ímpar' mas não
prezam pelos conhecimentos que o candidato tem e que possa oferecer/provar.

Em sáb., 27 de jun. de 2020 às 04:43, Reginaldo Melo <
notifications@github.com> escreveu:

**Comment by Reginaldo1239** [comment]
era melhor enviar um teste

**Comment by tuliospuri** [comment]
> Bom dia @tuliospuri! Eu me inscrevi para a vaga mas não tive retorno. Vocês costumam dar feedback para os candidatos?

**Comment by rhgerencianet** [comment]
> Bom dia @tuliospuri! Eu me inscrevi para a vaga mas não tive retorno. Vocês costumam dar feedback para os candidatos?

Olá Tiago, boa tarde! Como vai?
Verificamos em nossa plataforma, e vimos que você enviou o currículo para o nosso banco de talentos, mas não se candidatou a uma vaga específica da Gerencianet. Por isso nossos recrutadores não haviam enviado a você um feedback sobre sua participação no processo.
Pedimos que, caso alguma das nossas vagas em aberto seja do seu interesse e você se encaixe nos requisitos, que se candidate em nossa página de carreiras, para que o recrutador possa avaliar seu currículo de lhe dar um feedback sobre as próximas etapas! 
Boa sorte e sucesso para você :)

**Comment by rhgerencianet** [comment]
> Bom dia @tuliospuri! Eu me inscrevi para a vaga mas não tive retorno. Vocês costumam dar feedback para os candidatos?



> Então, passei pelo mesmo. Na real eles querem 'curriculo ímpar' mas não
> prezam pelos conhecimentos que o candidato tem e que possa oferecer/provar.
> 
> Em sáb., 27 de jun. de 2020 às 04:43, Reginaldo Melo <
> notifications@github.com> escreveu:
> …

Olá Rodrigo, como vai?

Ao realizar a triagem do currículo, levamos em conta alguns quesitos e a experiência é um deles, sendo muito importante para nossas vagas de Desenvolvedor nível Pleno/Sênior. Porém avaliamos alguns outros requisitos e, para estas vagas, é necessária a formação superior completa, devido ao plano de cargos e salários que utilizamos na Gerencianet.

Caso você tenha interesse em vagas futuras na Gerencianet, fique a vontade para se candidatar em nossa plataforma!
Desejamos sucesso a você :)

**Comment by gadielkalleb** [comment]
me candidatei, assino o linkedin premium, nem tiveram o trabalho de entrar no meu linkedin, tudo bem tomei uma negativa, mas gostaria de pelo menos um feed back, pode ser por email mesmo. receber uma mesagem genérica é complicado.

**Comment by rhgerencianet** [comment]
> me candidatei, assino o linkedin premium, nem tiveram o trabalho de entrar no meu linkedin, tudo bem tomei uma negativa, mas gostaria de pelo menos um feed back, pode ser por email mesmo. receber uma mesagem genérica é complicado.

Boa tarde, Gabriel!
Utilizamos as informações enviadas pelos candidatos na plataforma da Gerencianet, como currículo e demais dados preenchidos no formulário de inscrição, para que possamos realizar a triagem de maneira assertiva, de acordo com os critérios da vaga em questão. Observamos que você não possui formação superior completa, e este é um dos requisitos para a vaga de Desenvolvedor Pleno/Sênior na Gerencianet, devido ao nosso atual plano de cargos e salários. Por isso optamos por não seguir com sua candidatura neste processo.

Mas fique a vontade para se candidatar a futuras vagas da Gerencianet!
Desejamos sucesso a você :)

**Comment by gadielkalleb** [comment]
> > me candidatei, assino o linkedin premium, nem tiveram o trabalho de entrar no meu linkedin, tudo bem tomei uma negativa, mas gostaria de pelo menos um feed back, pode ser por email mesmo. receber uma mesagem genérica é complicado.
> 
> Boa tarde, Gabriel!
> Utilizamos as informações enviadas pelos candidatos na plataforma da Gerencianet, como currículo e demais dados preenchidos no formulário de inscrição, para que possamos realizar a triagem de maneira assertiva, de acordo com os critérios da vaga em questão. Observamos que você não possui formação superior completa, e este é um dos requisitos para a vaga de Desenvolvedor Pleno/Sênior na Gerencianet, devido ao nosso atual plano de cargos e salários. Por isso optamos por não seguir com sua candidatura neste processo.
> 
> Mas fique a vontade para se candidatar a futuras vagas da Gerencianet!
> Desejamos sucesso a você :)

pedi um feed particular, mas é legal ver que a empresa difere/preconceito com pessoas com formação, já que vc deu o feedback aqui expondo isso, sou formado sim em matemática, fui professor do estado, mas entrei na área de programação por não suporta mais o oficio não dou a minima para meu diploma, oque me difere é meu conhecimento e não minha formação. 

mas obrigado boa sorte para vcs. :)

**Comment by reginaldojunior** [comment]
Pessoal, as empresas tem total liberdade para pedir requisitos como cursos ou graduações para determinadas vagas, apesar de não concordar com esse requisito a empresa tem essa liberdade.

Recomendo a @rhgerencianet centralizar comentários e feedbacks da candidatura no e-mail pessoal para não expor as pessoas.

Como essa vaga ficou cheio de informação e não ajudando outros possíveis candidatos, vou fechar. Caso o @tuliospuri quiser abrir outra vaga, fique a vontade e mencione em requisitos que a graduação é necessária.
