### ISSUE TITLE
[REMOTO] Sr. Blockchain Engineer (Elixir, Rust, Solidity) @ Nash.io

### ISSUE THREAD

**Issue by canesin** [backend-br/vagas#2611]
## [Nash](https://nash.io)

Nash é uma FinTech contruída na blockchain!
Estamos na fronteira tecnológica aplicada a finanças.
Temos uma corretora (bolsa) de criptomoedas e carteira digital, ambas não-custodiais!

Conheça nossa empresa https://nash.io/company/

## Descrição da vaga

Temos oportunidades para engenheiros sênior com perfil arrojado para trabalhar no nosso time de backend lidando diretamente com nossos protocolos na blockchain.

Procuramos alguém que gostaria de trabalhar no desenvolvimento de sistemas de alta confiabilidade e gosta de desafios ao lidar com a fronteira do conhecimento e do que é tecnicamente possível hoje.

## Local

100% remoto, flexibilidade de horário. Nosso time é global, com membros em todos continentes.

## Requisitos

**Obrigatórios:**
- Fluencia na lingua Inglesa (Inglês é a língua oficial da empresa)
- 1 ano de experiencia em Elixir
- 2 anos de experiencia com bancos de dados distribuidos ou blockchain
- Domínio de criptografia assimétrica
- Mestrado ou 3 anos de experiência em tópicos como: segurança, criptografia, redes

**Desejáveis:**
- Doutorado em área relacionada a vaga
- Experiência com desenvolvimento de criptografia

**Diferenciais:**
- Experiência com smart contracts
- Experiência no desenvolvimento de protocols de rede

## Salário

- De R$18,000 a R$22,000 dependendo da senioridade
- Ações preferenciais digitalizadas (vesting de 3 anos)

## Benefícios

- Reembolso de equipamentos para home-office
- Viagem internacional anual para team-building, anteriores: Ko Phi Phi, Vienna e Lisboa
- 45 dias de férias
- Licença paternidade e maternidade

**Diferenciais:**
- Oportunidade de open-source parte do seu trabalho
- Único projeto de blockchain TOP100 com fundadores brasileiros

## Contratação

PJ com contrato internacional (matriz européia), levando a significante redução de impostos

## Como se candidatar

Por favor envie um email para canesin@nash.io com seu CV anexado - ou [click aqui](https://jobs.lever.co/nash.io/ba95848b-67f7-4fab-ae65-abad5f9952f7)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior
- Especialista

**Comment by canesin** [comment]
Respondendo uma pergunta frequente: O dia-a-dia do nosso backend eng. é em Elixir, trabalhando na parte de settlement dos fundos e matching da bolsa. Porém é frequente a necessidade de implementar ou analisar protocolos de blockchain, então o conhecimento de criptografia e DBs distribuídos é um requerimento importante.

**Comment by canesin** [comment]
Também estamos procurando por React Frontend Engineers: https://github.com/react-brasil/vagas/issues/729

**Comment by vandaimer** [comment]
@canesin ainda aberta a vaga?

Estão considerando aceitar pessoas sem xp em Elixir? (Sabemos que com vivencia a pessoa aprender rápido, se ela já tem xp em desenvolvimento de software).
