### ISSUE TITLE
[REMOTO] Full Stack Developer @ Vagalume

### ISSUE THREAD

**Issue by lafraia** [backend-br/vagas#2613]
## Descrição da vaga

Estou buscando profissionais que possam fazer parte de uma equipe remota para vários projetos no site Vagalume. Já temos algumas tarefas bem interessantes prontas para iniciar o desenvolvimento, mas boa parte do trabalho neste início é refatoração, otimização e ganho de confiança (qualidade, prazo e tempo de execução).

O foco é encontrar pessoas **bem** proativas, experientes, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica. 💪

## Local

Totalmente REMOTO mínimo de 4h por dia

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP / MySQL / MongoDB / Javascript
- 3 anos de experiência com Amazon Web Services (AWS) - Não só S3, mas outros recursos como RDS, ECS
- 2 anos de experiência com Docker
- 1 ano de experiência com Terraform

**Desejáveis:**
- conhecimentos de SEO
- experiência anterior com trabalho remoto

## Contratação

PJ/MEI

## Nossa empresa

Você já deve ter buscado uma letra de música no Vagalume, chegou a hora de poder contribuir com o projeto ;-)

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack e responder as perguntas abaixo:

* Quanto tempo você tem disponível por semana?
* Qual é o melhor horário do dia que você tem a disponibilidade?
* Qual experiência anterior com trabalho remoto?
* O que você busca no seu desenvolvimento profissional?
* Qual sua experiência anterior com AWS? (Este é um dos pontos principais da vaga, é necessário experiência anterior)
* Qual sua experiência com (favor elaborar a resposta):
    * PHP
    * Terraform
    * MySQL ou MongoDB
    * Javascript
* Por que você acha que deve ser escolhido?
* Como é o seu ambiente de desenvolvimento? SO, conexão, ambiente calmo, etc?
* Qual é o valor por hora que você acha justo trabalharmos neste modelo?

Se achar interessante compartilhar outras informações, pode mandar.

## Labels

- Remoto - Total
- Freela
- PJ
- Pleno
- Sênior

**Comment by samuelfaj** [comment]
E-mail enviado :)
