### ISSUE TITLE
[Rio de Janeiro] Estágio de desenvolvimento de software na [BigData Corp.]

### ISSUE THREAD

**Issue by pamtabak** [backend-br/vagas#262]
Estamos com algumas vagas de estágio de desenvolvimento de software abertas na empresa que eu trabalho, a BigData Corp.

O estágio é para 4h/dia, no nosso escritório na Barra da Tijuca. A BigData Corp. está procurando talentos para a área de Software Development. Buscamos desenvolvedores comprometidos, curiosos, proativos e organizados. Não cobramos experiência prévia na área, apenas vontade de aprender, um bom background de programação e muita energia. OBS: Gostar de pizza e/ou café é um bônus, mas não é necessário.

Interessados, mandar o CV para awesome.job.is.awesome@bigdatacorp.com.br . Qualquer dúvida/pergunta, podem me mandar mensagem!

**Comment by marcoapcaldas** [comment]
Oi Pamela! Vi que a vaga é pra estágio alocado. Alguma possibilidade para ser remoto? Sou do Ceará?

**Comment by pamtabak** [comment]
@marcoapcaldas Ola Marco! Essa vaga de estágio infelizmente é presencial, no nosso escritório no Rio de Janeiro. Para esta vaga, achamos importante a troca de experiência com o restante da equipe, que está todo localizado aqui.
Qualquer outra dúvida, estou à disposição!

**Comment by glauberm** [comment]
Qual a remuneração?

**Comment by pamtabak** [comment]
@glauberm R$1500 de salário, mais benefícios.

**Comment by paulo-raoni** [comment]
Parece ser uma boa vaga eim. Vou arriscar vai que...^^

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
