### ISSUE TITLE
Desenvolvedor Back-End - Pontual e Remoto 

### ISSUE THREAD

**Issue by procti-solution** [backend-br/vagas#2625]
1.Ajustes em Sistema existente PHPMailer6 + XOAUTH2 do Google.

2.Desenvolvimento de um novo sistema (PHP)
Requisitos:
Experiência em Laravel 5;
Experiência  em MySQL;
Experiência  em Bootstrap;
Experiência  em jQuery;
Experiência em consumo de API;

Contratação:
PJ a combinar
Como se candidatar:
Por favor envie um email para rh@procti.com.br com seu CV anexado e com valor/hora - enviar no assunto: Vaga Back-End

**Comment by samuelfaj** [comment]
E-mail enviado :)
