### ISSUE TITLE
[Curitiba] Back-End Developer na [GoEpik] - Curitiba 

### ISSUE THREAD

**Issue by chriscurcio** [backend-br/vagas#263]
**Descrição da vaga**
Buscamos um Backend ligado em 220V para projetos em Startup em Curitiba cujo propósito é levar a Realidade Aumentada para o chão de fábrica das empresas brasileiras de forma rápida, autônoma e flexível.
O dinamismo e a autonomia são uma marca da empresa! 
Você estará inserido em um ambiente inovador e em contato com tecnologias como RV e RA e machine learning.

**As principais atividades:** 
 • Desenvolver algo inovador com um real propósito de impactar a vida das pessoas através de tecnologia.
 • Trabalhar no processo de construção de soluções de software backend, o que envolve desenho, planejamento, execução, manutenção e suporte;
 • Atuar de maneira proativa para garantir escalabilidade, integridade de dados, bom desempenho de aplicações e estruturação de APIs. 

**Requisitos**
As principais atividades serão:

 Desenvolvimento e implementação de funcionalidades para site e app.
Que perfil estamos buscando?

Perfil autônomo, "dono do negocio";
Comunicação clara e objetiva;
Querer estar em uma start up e crescer com ela;
Dinamismo

**Os pré-requisitos técnicos:** 
Trabalhado com serviços na Cloud 
NodeJS 
TypeScript  
REST API
GIT

**O que é um super diferencial?**
NoSQL 
Recursos AWS 
Serverless (grande diferencial)

**Comment by simaodev** [comment]
https://www.linkedin.com/in/williamfelipesimao

**Comment by adrissonGalvao** [comment]
Segue o curriculum

GitHub: https://github.com/adrissonGalvao/
Linkedin: https://www.linkedin.com/in/adrisson-galvao/


Em 20 de junho de 2018 13:26, Christina Curcio <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
