### ISSUE TITLE
[Remoto - Porto Alegre] Full Stack na Bonaparte

### ISSUE THREAD

**Issue by eduardomello** [backend-br/vagas#2634]
### Nossa empresa
A Bonaparte é uma empresa de comunicação com 10 anos de mercado e que já trabalho com cliente como Converse, Facebook, Coca-Cola, Heineken e outros. 

Somos parceiros estratégicos de nossos clientes e, sem seguir fórmulas prontas, unimos design, criatividade e tecnologia para criar ideias que buscam construir conexões relevantes entre marcas e pessoas.

Temos duas frentes muito fortes de serviço: comunicação publicitária e desenvolvimento digital. Na área de desenvolvimento digital trabalhamos com equipes integradas e preparadas para trabalho remoto. Atualmente temos experiência com projetos de larga escala, aplicando técnicas DevOps. Nos últimos anos temos focado muito em JavaScript como nosso principal linguagem trabalhando com frameworks como Angular e Vue no front-end e Node.JS no back-end. Em termos de infra, estamos trabalhando muito com Docker para gerenciamento dos serviços.

### Descrição da vaga
- Participar de uma equipe ágil de desenvolvimento digital, ajudando a traduzir objetivos de negócio em aplicações web e mobile de alta performance;
- Codificar interfaces digitais;
- Desenvolver REST APIs;

### Requisitos
- Experiência com Frameworks JS (preferência por Vue.JS);
- Experiência com Node.JS;

### Desejado
- Conhecimento em ferramentas CI/CD;
- Conhecimento com Docker;
- Conhecimento com Serverless (framework);

### Como se candidatar
Enviar CV e, se possível portfolio, para eduardo.mello@bonaparte.ag

### Labels
**Alocação**
- Remoto

**Regime**
- CLT
- PJ

**Nível**
- Júnior
- Pleno

**Comment by samuelfaj** [comment]
E-mail enviado.
