### ISSUE TITLE
[Brasilia] Back-end Developer @ CalcLab

### ISSUE THREAD

**Issue by anderson-cubo** [backend-br/vagas#2636]
## Nossa empresa
A CalcLab é uma startup no ramo de HealthTech que busca simplificar processos de diagnóstico e tratamentos, trazendo a tecnologia e inteligência de dados para dentro do contexto da saúde! Trabalhamos com novas tecnologias e queremos alguém que nos ajude a criar novas soluções. 

## Descrição da vaga

Estamos a procura de uma Pessoa Desenvolvedora Júnior / Pleno que trabalha com tecnologias como NodeJS, Javascript, RegEx e afins. Não buscamos nenhum item como obrigatoriedade, então sinta-se livre para preencher a sua candidatura caso tenha ainda algo a aprender nesse contexto :) 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- RegEx

**Desejáveis:**
- Serverless
- Lambda
- MongoDB

**Diferenciais:**
- Já ter feito extração de dados de arquivos PDF.

## Contratação

PJ a combinar

## Como se candidatar

Preencha o formulário do link: https://bit.ly/2ZuQ8Tx

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by jefferson-dev** [comment]
Boa tarde @anderson-cubo , preenchi o form mais não sei o pdf do currículo foi enviado por que o site carrega mais não exibe que há algo inserido, se estiver com problema posso enviar por e-mail se preferir.
