### ISSUE TITLE
[Home-office] NodeJS Developer @ Incentivar 

### ISSUE THREAD

**Issue by mylenasantos** [backend-br/vagas#2637]
**Nossa empresa**

A Incentivar é uma startup de marketing de incentivo, visando melhorar a performance dos colaboradores de nossos clientes a produzirem mais e melhor e com isso receberem premiações. Somos um SaaS de Incentivo trabalhando sempre com o que tem de mais atual na area de desenvolvimento e tecnologia.

**Descrição da vaga**

O profissional irá atuar junto ao time na criação de features e sustentação das plataformas existentes.

## **Local**

100% remoto

## **Requisitos:**

**Obrigatórios:**
• Experiência com NodeJS; 
• Experiência com APIs REST;
• Experiência com banco de dados mySQL; 
• Experiência com versionamento de código utilizando git; 
• Sólidos conhecimentos em javascript ES6+; 
• Sólidos conhecimentos do Protocolo HTTP e seus métodos; 
• Conhecimento de Docker; 
• Conhecimento de padrões e boas praticas de programação; 
• Desejável Conhecimento NoSQL; 
• Desejável Conhecimento Web Services SOAP. 

## **Benefícios**

- Férias de 30 dias remuneradas

## **Contratação**

PJ a combinar

## **Como se candidatar**

Por favor envie um email para alvaro@incentivar.io com seu CV anexado - enviar no assunto: Vaga NodeJS Pleno, se for Junior, mandar como Vaga NodeJS Junior

## **Tempo médio de feedbacks**
 Uma semana.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Junior

**Comment by samuelfaj** [comment]
E-mail enviado.

**Comment by mylenasantos** [comment]
As vagas já foram preenchidas pessoal, agradeço quem mandou o CV. 
Estou fechando esse issue.
