### ISSUE TITLE
[ São Paulo ou REMOTO ] Software Engineer Back-End @Kovi

### ISSUE THREAD

**Issue by AndreBorim** [backend-br/vagas#2641]
## Nossa empresa

A Kovi é uma startup de mobilidade movida pela paixão de mudar vidas. Diariamente, **quebramos barreiras por meio da tecnologia para melhorar a vida dos motoristas de aplicativo** oferecendo a melhor experiência de aluguel de carros.

Aqui queremos construir um ambiente onde os **funcionários se sentem donos do negócio**. Assim como o significado da nossa cor, rosa, nosso ambiente é acolhedor e de muita colaboração.

Aqui os diversos pontos de vista convergem para a missão de criar um mundo sem posses!

## Descrição da vaga

**Responsabilidades como Desenvolvedor(a) Node.JS Senior na Kovi:**

- Organizar o desenvolvimento de software de ciclo de vida completo;
- Preparar especificações e determinar a viabilidade operacional;
- Avaliar e implante ferramentas, processos e métricas de software;
- Fornecer suporte e consultoria sobre o uso de sistemas de software;
- Garantir a conformidade com os planos do projeto e os padrões do setor;
- Sólida experiência em arquitetura e design de sistemas;
- Paixão por criar novos produtos em ambiente rápido e orientado para equipe;
- Sede de conhecimento e melhoria contínua;

**Para este desafio, estamos buscando:**
- Experiência significativa no desenvolvimento de aplicativos da Web usando pelo menos uma estrutura da Web popular, **NodeJS, Typescript**;
- Excelente conhecimento de bancos de dados relacionais, tecnologias **SQL e NOSQL**;
- Boa experiência no design de aplicativos interativos e com **desenvolvimento orientado a testes**;
- Bons conhecimentos para desenvolver software em **NodeJS**, **Typescript**, **Elixir**, ou outras linguagens selecionadas;
- Experiência na documentação de requisitos e especificações Familiaridade com ferramentas de engenharia de software, metodologia de desenvolvimento de software e processos de lançamento;
- Base sólida em estruturas de dados, algoritmos, design de software, design de API e segurança;
- Sólido conhecimento da **AWS**
- Sólido conhecimento de **git**;

## Local

Remoto ou presencial em São Paulo - SP

## Requisitos

**Obrigatórios:**
- Conhecimento sênior em Node.js
- Sólidos conhecimento em baco de dados SQL e NoSQL
- Sólidos conhecimentos em git e AWS

**Desejáveis:**
- Conhecimento em arquitetura serverless;
- Conhecimento em mensageria e arquitetura orientada a eventos;

## Benefícios

- Happy hour com cerveja toda sexta;
- Vale-transporte, desconto no estacionamento ou vale-combustível. Você escolhe =)
- VR e/ou VA porque saco vazio não fica em pé;
- Frutinhas frescas toda quarta-feira;
- Movimente-se, temos Gympass;
- NO Dress Code. Seja você;
- Notebook corporativo;
- Plano de Saúde;
- Plano Odontológico para manter aquele sorrisão;
- Tem um assunto super bacana e acha que é válido passar adiante? temos nosso #KoviTalks
- Aniversariante do mês;

## Contratação

- A combinar

## Tempo médio de feedbacks

Processo ágil, que normalmente dura em torno de 20 dias.

#### Alocação
- Alocado
- Remoto

#### Nível
- Sênior

**Comment by guilhermeoa07** [comment]
Apenas sênior?

**Comment by AndreBorim** [comment]
Oi, Guilherme. Nesse momento sim!
