### ISSUE TITLE
{Rio de Janeiro} Desenvolvedor Salesforce na {MJV Technology & Innovation}

### ISSUE THREAD

**Issue by RHRJ** [backend-br/vagas#265]
A MJV é uma consultoria global dedicada a transformar negócios por meio da inovação e da tecnologia presente em 6 países e em busca de crescer sempre mais!

Você pode ver mais sobre a nossa história aqui: https://vimeo.com/269521857/87217f2322

Atualmente, nós estamos com oportunidades de Desenvolvedor Salesforce para atuar tanto em projetos quanto em contratações CLT.

Descrição:

Desenvolvimento de aplicativos e integrações do Salesforce com outros aplicativos de negócios vitais. Personalizar portais do Salesforce Community e recursos do Chatter. Implementar e testar novos recursos. Criar especificações técnicas sobre planos de teste. Utilização de ferramentas de desenvolvimento: Eclipse, HTML5, CSS, JavaScript, Angular, Cordova, JSON, XML, APEX e VisualForce, Componentes do Lightning.

Pré-requisitos: Experiência trabalhando com Apex e Lightning Components, conhecimento com tecnologias como Java, C# ou similar.

Formação: Ensino Superior completo em áreas de TI

Experiência:

Marketing cloud e frontend (javascript) 

Desenvolvimento Salesforce

Local: Centro/RJ e Barra da Tijuca

Interessados enviar CV para rhrj@mjv.com.br

Labels
Alocado
CLT
Pleno
Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
