### ISSUE TITLE
[Remoto] PHP/Laravel Developer na Devsquad 

### ISSUE THREAD

**Issue by philalves** [backend-br/vagas#2653]
[Remoto] PHP/Laravel Developer na Devsquad 

## Aqui você irá:

- Desenvolver código limpo, testável e de fácil manutenção.
- Contribuir com todo o processo de desenvolvimento de software.
- Implementar features novas e investigar problemas em produção.
- Contribuir nas discussões técnicas sobre os desafios encontrados.
- Participar do processo de code review, garantindo qualidade e consistência do código.

##  Procuramos por pessoas que:

- Sejam detalhistas e analíticas;
- Gostem de lidar com projetos grandes e desafiadores;
- Consigam trabalhar em equipe de forma colaborativa e em função de um objetivo comum;
- Busquem aprendizado constante;
- Naveguem bem entre back-end e front-end;
- Queiram  construir um ambiente de trabalho de respeito e apoio mútuo.

## Requisitos

- Experiência desenvolvendo aplicações complexas;
- Conhecimentos avançados em PHP 7 e Laravel;
- Conhecimentos avançados em HTML, CSS, JavaScript.
- Vue.js 2 ou framework similar (React, Angular);
- Git workflow
- Inglês Intermediário

## Nossa empresa

A DevSquad é uma startup com sede nos EUA, Especialista em Desenvolvimento de Software Products com equipes nearshore, contratamos desenvolvedores em toda a América Latina.

Trabalhando conosco, você vai criar produtos para o mercado americano e fazer parte de uma equipe de desenvolvedores de elite.

Aqui você vai trabalhar remoto de qualquer lugar do Brasil, terá um ambiente flexível, dinâmico, colaborativo e inteligente, em uma empresa que está crescendo muito rápido e com muita solidez! Se você é apaixonado por aprendizado constante, desafios, autonomia e velocidade, Quem sabe seu lugar não é aqui com a gente?!

## Como se candidatar

Por favor use a seguinte URL: [https://hire.withgoogle.com/public/jobs/devsquadcom/view/P_AAAAAACAAL4B9NHWs7C6Ll](https://hire.withgoogle.com/public/jobs/devsquadcom/view/P_AAAAAACAAL4B9NHWs7C6Ll)

### Contratação:
- PJ

**Comment by duuh30** [comment]
É obrigatório 160h mensais ou pode ser acordado as horas?
