### ISSUE TITLE
Criar label Remoto Durante Pandêmia.

### ISSUE THREAD

**Issue by peterramaldes** [backend-br/vagas#2659]
Sugiro criar uma label **Remoto durante pandemia.**

Semelhante o [frontendbr](https://github.com/frontendbr/vagas/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%A6%A0+Remoto+durante+pandemia%22). 

Isso fará que quem quiser vaga full remoto não tenha dificuldade.

**Comment by leandroribeiro** [comment]
+1 faz todo sentido!
