### ISSUE TITLE
[Belo Horizonte] Full-Stack Developer na 2x3

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#266]
## Descrição da vaga

- Desenvolver aplicações e soluções web utilizando Ruby e JavaScript.

## Local

Belo Horizonte/MG

## Benefícios

- Plano de Saúde e Odontológico.

- Lanche na empresa.

- No dress code (pode trabalhar de bermuda, chinelo, etc).

- Clima descontraído.

- Happy Hour mensal.

- Horário flexível :)

## Requisitos
- Superior completo em cursos relacionados à Tecnologia da Informação (Ciências da Computação e Sistemas de Informação).

- Experiência no desenvolvimento de aplicações web, inclusive API REST.

- Desenvolvimento web back-end em Ruby on Rails.

- Conhecimentos no desenvolvimento front-end.

## Contratação

PJ ou CLT R$3800 a R$6000

## Nossa empresa

Na 2X3 Inteligência Digital, utilizamos a tecnologia para suprir necessidades de pessoas e organizações, oferecendo consultoria personalizada em soluções web, mobile e em tecnologias emergentes. Acreditamos que o maior valor de um website, aplicativo ou sistema não está na tecnologia e nas ferramentas com as quais ele foi desenvolvido, mas sim na experiência proporcionada ao usuário. Se identificou com a nossa visão? Essa é a oportunidade de fazer parte da nossa equipe, estamos com vagas abertas!

## Como se candidatar

Via Vulpi pela url: [https://app.vulpi.com.br/2x3-intelig-ncia-digital/652
](https://app.vulpi.com.br/2x3-intelig-ncia-digital/652
)

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
