### ISSUE TITLE
[São Paulo] Full Stack Engineer @ INTI

### ISSUE THREAD

**Issue by thiageek** [backend-br/vagas#2668]
## Nossa empresa

Na INTI uma coisa é clara: O todo é maior do que a soma das partes.

Somos diferentes, buscamos escutar e entender as necessidades dos nossos clientes para encontrar a melhor solução de tecnologia, de maneira ágil, mas ainda assim com tempo suficiente para não apenas atender e, sim, surpreender.

A coragem é a atitude que nos define já que o que nos move diariamente é nossa sede de resolver problemas, desafiar o óbvio e inovar na experiência.

Em nome da transparência, fazemos tudo com alma e permanecemos resilientes mesmo competindo no meio de gigantes.

Nosso sucesso é medido pelo sucesso de nossos clientes e por isso construímos cada funcionalidade em conjunto, sob medida, sempre com flexibilidade para promover autonomia e gerar inteligência.

Um time de atitudes diferenciadas, inquietos, apaixonados, questionadores, e que não se contentam com mais do mesmo.

O nosso propósito? É pouco a pouco, dia após dia, repensar o consumo do entretenimento, inovar na jornada, promover relacionamentos e escrever mais um capítulo do amanhã, sem abrir mão de dar boas risadas enquanto isso.

No fim de cada dia é fácil dizer que o que nos orienta não é apenas fazer negócios, e sim, construir e fortalecer parcerias.

## Descrição da vaga

Estamos procurando um profissional para atuar de ponta a ponta, desde o acompanhamento de entrevistas com usuários e stakeholders até a concepção da interface, que seja capaz de traduzir necessidades em experiências consistentes e de valor.

É necessário também bastante organização, excelente comunicação, autonomia e proatividade.

## Local
Escritório, São Paulo - Moema (Remoto opcional enquanto durar a pandemia)

## Requisitos

**O que você vai fazer?**

- Desenvolvimento de novos sistemas, implantação, manutenção de sistemas e suas API's – REST e PHP;
- Nossa Stack é principalmente feita em PHP, porém possuímos sistemas em NodeJS (que está sendo utilizado cada vez mais aqui);
- Possuímos inúmeros bancos de dados mas os predominantes são mySQL e SQL. Assim, seria legal você saber sobre SQL / Big Data / NoSQL;
- Desenvolvimento web, com HTML, Javascript ou Typescript e CSS, interessado em frameworks de desenvolvimento de produtos como Angular, React e Vue.js.
- Se preocupa com evolução do produto e está de olho em ferramentas de métricas como Google Analytics, Firebase e Mixpanel e está a fim de propor e trazer novas tecnologias para provas de conceito, validação de hipóteses e construção de protótipos para validar ideias junto a clientes.
- Propor novas tecnologias e formas diferentes de programar, afinal nada é escrito na pedra 😉;
- Gostamos muito de DDD/ BDD / TDD / Clean Architecture, estes conceitos precisam estar claros para você pois irá colocá-los em prática aqui.

**O que você precisa ter?**
- Experiência UX/UI na criação de interfaces gráficas e fluxos de navegação em sistemas;
- Conhecimento avançado em Prototipação de média a alta fidelidade (Figma, Adobe XD , Protopie ou similar);
- Extrema organização e consistência e relação ao Design System estabelecido;
- Noções de HTML e CSS;
- Ter experiência em trabalhar com a metodologia Scrum;
- Trabalhar com desenvolvedores, analista de requisitos e tester.

## Benefícios

- Plano de saúde
- Plano odontológico
- Academia

**Diferenciais:**
- Café da manhã
- Geladeira sempre cheia
- Oculus Quest VR a disposição no escritório

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para thiago@byinti.com com seu CV anexado - enviar no assunto: Vaga Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by brunooomelo** [comment]
Enviado.
