### ISSUE TITLE
[Belo Horizonte] Desenvolvedor ASP.NET

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#267]
## Descrição da vaga

Colaborar no desenvolvimento e manutenção dos microserviços da plataforma, nas quais a maioria são desenvolvidos em .NET. Há funcionalidades e APIs que precisam ser mantidas consistentes. Participar de um processo vivo e ágil, codificando a solução entendida utilizando as melhores ferramentas disponíveis e participando no processo de teste e especificação de software junto com o time.

## Local

Belo Horizonte/MG

## Benefícios

- Vale transporte, alimentação.

- Apoio na participação de eventos das comunidades de desenvolvimento.

## Contratação

PJ ou CLT R$3000 a R$3500

## Nossa empresa

Oficina Conectada é uma solução completa de gestão empresarial e conteúdo técnico que atende mais de 80 mil oficinas mecânicas em todo o país.

## Como se candidatar

Via Vulpi pela url: [https://app.vulpi.com.br/oficina-conectada/684
](https://app.vulpi.com.br/oficina-conectada/684
)

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
