### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Back-end Pleno @ Méliuz

### ISSUE THREAD

**Issue by Folks-Meliuz** [backend-br/vagas#2677]
## Méliuz

Nós do Méliuz temos grandes sonhos e desafios e sabemos que para chegarmos cada vez mais longe precisamos aumentar nossa grande família com uma pessoa desenvolvedora Back-End Sênior. Temos produtos acessados por milhões de pessoas e muitos projetos para torná-los ainda mais interessante para nossos usuários e parceiros. Contamos com uma equipe de desenvolvimento altamente qualificada e interdisciplinar que sempre prefere soluções Open Source ou livres.
Gostamos de novas tecnologias e não nos restringimos a apenas o que temos funcionando hoje. São milhares de operações por segundo com grandes picos sobre nossa stack, que é feita em PHP, Python, C++ e Node.js, roda com bancos de dados MySQL, PostgreSQL, Redis, BigQuery e Redshift, e é hospedada em ambiente de nuvem híbrida (AWS e Google Cloud).

**Você será responsável por:**
Atuar no desenvolvimento e evolução dos produtos do Méliuz;
Desenvolver e evoluir aplicações como APIs REST, além de realizar integrações com APIs de terceiros e plataformas como AWS;
Projetar e implementar a persistência de dados das aplicações e garantir que o acesso seja seguro e eficiente;
Atuar junto com a liderança e engenheiros do time para evoluir e tornar os sistemas/produtos do Méliuz cada vez mais escaláveis;
Arquitetar soluções para problemas complexos e garantir que o código seja eficiente e de fácil manutenção.

**Local**
Remoto

**E precisamos que você tenha conhecimentos como:**
- Conhecimentos na linguagem de programação Python;
- Conhecimentos de algoritmos e estruturas de dados;
- Experiência trabalhando com banco de dados relacionais (especialmente MySQL ou PostgreSQL);
- Experiência desenvolvendo aplicações cliente-servidor e APIs REST;
- Experiência com testes automatizados e ambientes de CI/CD;
- Experiência com ferramentas de controle de versão, em especial Git

**Você vai se destacar se tiver:**
- Experiência projetando e implementando sistemas/softwares escaláveis/missão crítica;
- Experiência com banco de dados não relacionais - NoSQL;
- Experiência com Docker;
- Ter trabalhado em projetos como desenvolvedor FullStackT;
- Ter trabalhado com arquiteturas baseadas em microsserviços e monólitos;
- Experiência com ferramentas de monitoramento de sistemas críticos;
- Experiência com serviços da AWS;
- Experiência com metodologias ágeis (Scrum, Kanban);
- Experiência empregando conceitos DevOps em projetos em que trabalhou.

**Benefícios:**
- Vale transporte;
- Vale refeição ou alimentação de R$30,00 ao dia;
- Plano de saúde;
- Plano odontológico;
- Horário flexível;
- Premiação por atingimento de metas coletivas;
- Convênio com Sesc;
- Biblioteca interna;
- Cashback online em dobro;
- Licença Maternidade/Paternidade estendida;
- Auxílio Creche;
- Auxílio luto.

 **Contratação**
CLT

**Como se candidatar**
Acesse o link e se candidate: https://jobs.lever.co/meliuz

**Nível**
- Pleno

**Comment by Folks-Meliuz** [comment]
Vaga ainda aberta!

**Comment by arthurazs** [comment]
Apenas presencial?

**Comment by Folks-Meliuz** [comment]
> Apenas presencial?

Aceitamos remoto
