### ISSUE TITLE
[Remoto]  Developer Pleno e Sênior @Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [backend-br/vagas#2678]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga

_Cliente:_ empresa jovem voltada para o mercado financeiro (B2B). 
_Projeto:_ duração de 3 meses e de cunho estratégico muito alto para a empresa. O foco será desenvolvimento back em **Java Web**, além de Cloud e Microservices. Posteriormente, vão trabalhar com desenvolvimento fullstack em outros projetos.

🔈🔈 Após a finalização desse projeto, há grande possibilidade de internalização.

**Buscamos developers tanto pleno quanto sênior.** 

## Local

:house: Remoto

## Requisitos

**Obrigatório**
Experiência em desenvolvimento de sistemas em Java (J2EE, Spring e Hibernate/Jpa/Jdbc, Webservices)
Desenvolvimento de microsserviços e APIs (REST/JSON);    
Conhecimento: SQL e serviços REST / SOAP.    
Frameworks: J2EE7 e 8, JPA, EJB3, Hibernate, CDI, JSF1.X e 2.X, Primefaces, e Jasper.
Servidor de Aplicação: JBOSS, Spring     
Integração Contínua: Maven, Jenkins e Gradlew     
Experiência em arquitetura Cloud Native (AWS, Azure ou Google)     
Execução de System Tests/Suporte aos Testes Integrados e UAT;    
Experiência em metodologias ágeis     
Banco de Dados: SQL Server  

**Desejável**
HTML5, CSS e Javascript
Angular, Vue/Quasar
Banco de Dados: DB2
Ter atuado com ERP Protheus

## Benefícios

Vale refeição
Vale Transporte
Assistência Médica
Seguro de Vida

**Diferenciais:**

A empresa está em fase de expansão, assim há possibilidade de crescimento profissional. :+1: :+1:

## Contratação

CLT (8k a 12k)

## Como se candidatar

Por favor envie um email para _livia.mello@roberthalf.com.br_ com seu CV anexado ou encaminhe um whatsapp para _(11) 95402-8154_

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by andrebrito** [comment]
Bom dia!
Cogita a contratação de freelance ou alguma política de horas flexíveis?

**Comment by LiviaMaron** [comment]
Oi @andrebrito! 

Trabalhamos somente com CLT, infelizmente não consigo flexibilizar o regime de contratação.
