### ISSUE TITLE
[São Paulo] Back-End Developer na B2W Digital

### ISSUE THREAD

**Issue by AmandaTiberio** [backend-br/vagas#268]
Descrição da vaga:
Buscamos desenvolvedores Back End para atuar na criação de novos serviços e plataformas digitais. O Profissional trabalhará em um ambiente diversificado e dinâmico que utiliza diferentes ferramentas e linguagens de programação, atuando no desenvolvimento de aplicações escaláveis e de alta disponibilidade.

Requisitos:
Experiência em análise de requisitos;
Experiência em modelagem, desenvolvimento e testes de aplicações Java;
Conhecer outras linguagens de programação (Scala, Python e etc);
Experiência no desenvolvimento de APIs REST;
Experiência em tecnologias como: Spring Boot/Data/Cloud, JPA, Hibernate e etc;
Experiência em arquitetura de micro-serviços;
Experiência em metodologias ágeis de desenvolvimento (Scrum, Kanban);
Conhecimento em gerenciadores de dependência e build (Maven, Gradle e etc);
Conhecimento em Docker;
Conhecimento em ferramentas de controle de versão (Git);
Conhecimento em SQL e bancos de dados relacionais;
Conhecimento em bancos de dados No-SQL (Cassandra, ElasticSearch e etc);
Experiência em ferramentas de Integração Contínua;
Conhecimento em Sistema Operacional Linux.
Ter facilidade para trabalhar dentro de times multi-disciplinares;

Qualificações desejáveis:
Conhecimento em desenvolvimento Front End;
Conhecimento em análise de desempenho de APIs (Heap Dump, CPU Dump e etc);
Conhecimento em frameworks para programação reativa (Netty, Play, Akka e etc).
Experiência no desenvolvimento de serviços de meios de pagamento;

Local: Vila Olímpia 

Benefícios: VT + VR + Plano de Saúde + Plano Odontológico + Seguro de Vida + Desconto nas nossas marcas 

Como se candidatar: Mande seu currículo para **recrutamento.bitsp@b2wdigital.com**
Visite nossa página de carreiras: http://somos.b2wdigital.com/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
