### ISSUE TITLE
[Porto Alegre] Full Stack Node e React Sênior @Trinca

### ISSUE THREAD

**Issue by Gabrielarochay** [backend-br/vagas#2680]
Full Stack Node e React Sênior na Trinca
Buscamos Full Stack Developer SR com sólida experiência em projetos digitais (web e mobile). Procuramos alguém que seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

// Habilidades que você precisa ter:

• Conhecimento sólido em Javascript e ReactJS;
• Experiência com desenvolvimento backend em Node.js;
• Conhecimentos em arquitetura e engenharia de software;
• Desejável experiência com arquitetura de microserviços.

Ah, nós estamos Remoto até o dia 4 de janeiro :) Depois disso, é opcional trabalhar presencial ou remoto.

O que ofereceremos e como é trabalhar na Trinca: https://trin.ca/procuramos-por-voce/
![full stack](https://user-images.githubusercontent.com/66493175/87074577-727a7e00-c1f5-11ea-8175-ff74ab3faa06.JPG)

**Comment by reginaldojunior** [comment]
@Gabrielarochay por favor arruma o titulo da vaga
