### ISSUE TITLE
[RIO DE JANEIRO] - Analista desenvolvedor Java Pleno [CTIS] 

### ISSUE THREAD

**Issue by ernanijunior** [backend-br/vagas#269]
Oportunidade Rio de Janeiro (capital) - Analista desenvolvedor Java Pleno
Profissional com graduação ou pós em TI 
Requisitos:
- 4 anos de experiência em análise e desenvolvimento de sistemas utilizando Java 1.6 ou superior.
- Experiência com JSF, Primefaces, Hibernate, JPA, iReport, EJB, Webservices, Javascript, ferramentas de versionamento de arquivos e banco de dados Oracle e  PL-SQL.
Diferencial: 
- Domínio dos conceitos SOA, Webservices, WSO2.
- Conhecimento de mapeamento de processos e ferramentas de BPMN, ferramentas GED, ASP Clássico; e/ou PHP, e ou Delphi será um diferencial.
Enviar CV para: selecao.031016@gmail.com com o assunto: “Analista Java Pleno”

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
