### ISSUE TITLE
[Remoto] Back-end Developer Nodejs @Pixter

### ISSUE THREAD

**Issue by D440** [backend-br/vagas#2694]
A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

Buscamos Back-end Developer Nodejs, com boa experiência, excelente comunicação, relacionamento interpessoal e trabalho em equipe.

Requisitos:
-Interesse em aprender novas tecnologias e compartilhar conhecimento;
-Gostar de trabalhar em equipe e ser comunicativo(a);
-Experiência no desenvolvimento de projetos em php e node.js ;
-Experiência com jquery / angularjs ;
-Desenvolvimento e consumo de api rest / soap ;
-Conhecimento em metodologia ágil – scrum / kanban ;
-Conhecimento em mysql, mongodb ou dynamodb ;
-Experiência em ferramentas para controle de versão (git) ;
-Conhecimento da ferramenta jira ;
-Capacidade de analisar escopos e demandas, também sugerir soluções.

## Local
Remoto

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Regime

- PJ
Pleno ou Sênior

**Comment by samuelfaj** [comment]
E-mail enviado :)
