### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Fullstack Python [Evoé]

### ISSUE THREAD

**Issue by gabrielgsf31** [backend-br/vagas#27]
[VAGA] Desenvolvedor Fullstack Python

Local: Belo Horizonte, MG (Centro)
Empresa: Evoé
Salário: R$ 3000 - R$ 5000
Tipo de Contrato: Prestador de Serviços (PJ)
Benefícios:
- Vale Transporte
- Vale Refeição
- **Possibilidade de se tornar socio**

Clique no link abaixo para se candidatar:
https://www.recrutasimples.com.br/vaga/-KyMGJwclR3AflRjVM7W/desenvolvedor-fullstack-python/belo-horizonte-mg?referrer=FB

**Descrição**

A Evoé é uma plataforma completa de crowdfunding com o diferencial de hackear e desburocratizar o apoio a projetos aprovados por leis de incentivo a cultura.

Sim, queremos descentralizar o dinheiro do governo e fazer com que você possa escolher onde parte do seu imposto vai parar.

Estamos participando de um programa de aceleração (SEED MG) e está na hora de aumentar nossa equipe. 

Buscamos um desenvolvedor Python com experiência e apaixonado pelo que faz para entrar no nosso time.

Se você acha especial saber que o seu trabalho está ajudando várias projetos criativos a ganharem vida, então vem com a gente!

----------

**REQUISITOS**

Bom nível de conhecimento em Python
Banco de dados Mysql
Django
Conhecimento em front-end
JavaScript,HTML5 e CSS3
Inglês intermediário (suficiente para entender as documentações);

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
