### ISSUE TITLE
[São Paulo] Desenvolvedor NODE.JS Back-end @ Kovi

### ISSUE THREAD

**Issue by lucasbahiaa** [backend-br/vagas#2700]
**Descrição:** A Kovi é uma startup de mobilidade movida pela paixão de mudar vidas. Diariamente, quebramos barreiras por meio da tecnologia para melhorar a vida dos motoristas de aplicativo oferecendo a melhor experiência de aluguel de carros. Aqui queremos construir um ambiente onde os funcionários se sentem donos do negócio. Assim como o significado da nossa cor, rosa, nosso ambiente é acolhedor e de muita colaboração.

**Local:** São Paulo, porem existe possibilidade em ser remoto a depender do profissional e do perfil.

**Contratação:** CLT full pela Kovi.

Requisitos principais:  Bons conhecimentos para desenvolver software em NodeJS, Typescript, Elixir, ou outras linguagens selecionadas, Sólido conhecimento da AWS, Conhecimento de bancos de dados relacionais, tecnologias SQL e NOSQL.

Diferencial: Conhecimento em arquitetura serverless, Conhecimento em mensageria e arquitetura orientada a eventos.
Fazer o cadastro no seguinte site:  **http://byintera.in/ua**

Dúvidas: https://www.linkedin.com/in/jessica-santana-96b5141a8/

**Comment by lucasbahiaa** [comment]
^^

**Comment by italopenaforte** [comment]
Só pra sênior :sob:

**Comment by danielsidev** [comment]
Curti! Será sempre remoto ou só durante a pandemia? Sou do RJ.
Apliquei para a vaga, preenchendo o formulário!
https://www.linkedin.com/in/danielsidev/

**Comment by lucasbahiaa** [comment]
> Curti! Será sempre remoto ou só durante a pandemia? Sou do RJ.
> Apliquei para a vaga, preenchendo o formulário!
> https://www.linkedin.com/in/danielsidev/

Durante a pandemia apenas, mas há possibilidade de ser remoto caso o perfil seja bem alinhado com a vaga!
