### ISSUE TITLE
[Niterói / Rio de Janeiro][Remoto] Back-End Developer Ruby On Rails na Edools

### ISSUE THREAD

**Issue by williamsbelchior** [backend-br/vagas#271]
## Descrição da vaga

O Desenvolvedor Ruby on Rails chegará para nos ajudar com a missão de somar forças para a evolução constante do ensino online. Ele ou ela integrará nosso time de engenharia e será responsável pela manutenção e desenvolvimento de novas soluções usando tecnologias de ponta. Nosso time é ágil e extremamente focado em entregar o melhor produto para nossos amados clientes.

## Local

Remoto ou em nosso escritório em Santa Rosa – Niterói/RJ

## Benefícios

- Plano de saúde (apenas CLT)
- VR (apenas CLT)
- Salário compatível com a experiência

#### Diferenciais

- Ambiente descontraído
- Xbox para relaxar
- Frigobar sempre cheio
- Café sempre fresco e infinito
- Estar no olho do furacão do ecossistema de startups brasileiro
- Possibilidade de impactar e mudar a forma como as pessoas estudam online
- Participar de uma equipe de alto desempenho, gerando aprendizado contínuo

## Requisitos

**Obrigatórios:**

- Boa comunicação
- Espírito de equipe
- Boa experiência com desenvolvimento Web (Ruby on Rails)
- Bons conhecimentos de OO
- Bons conhecimentos de Ruby
- Bons conhecimentos de Banco de dados PostgreSQL
- Experiência com Git
- TDD (usamos RSpec e Minitest)
- HTML / CSS / JavaScript

**Desejáveis:**

- Experiência em desenvolvimento de API RESTful
- Experiência com o Rails Turbolinks
- Experiência com o Rails Liquid
- Experiência com o Redis
- Experiência com o Elasticsearch
- Experiência com o MongoDB

**Diferenciais:**
- Experiência com Amazon AWS (EC2, S3, RDS, CloudFront, CloudFormation etc)
- Experiência com algum framework JavaScript (Meteor ou AngulaJs)
- Ser atuante na comunidade Ruby on Rails
- Ser colaborador ativo com projetos open source
- Inglês intermediário
- Possuir espírito empreendedor

## Contratação

Contratação CLT ou PJ

## Nossa empresa

A Edools é uma empresa brasileira de tecnologia que tem como missão somar forças para a evolução constante do ensino online. Através do modelo SaaS (Software as a Service), a plataforma é a infraestrutura tecnológica para instituições ensinarem a distância e levarem a melhor experiência para seus alunos.

Atuando em quatro principais segmentos de mercado: Treinamento Corporativo, Preparatórios para Concursos, Cursos Livres e Universidades, e por meio dos modelos de trabalho: plataforma nativa e por projeto, a empresa é conhecida pela melhoria contínua da sua tecnologia para ensino online.

Conheça algumas empresas que usam a Edools como sua solução EAD http://edools.com/clientes

## Como se candidatar

Por favor se inscreva através de nosso site
https://www.edools.com/trabalhe-conosco/vagas/desenvolvedor-ruby-on-rails-2/

## Labels

- Alocado
- CLT
- Remoto
- PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
