### ISSUE TITLE
[São Paulo] Back-End .NET Sr Developer na BEYOND

### ISSUE THREAD

**Issue by FrancieleMarcaDaRosa** [backend-br/vagas#272]
Descrição da vaga
Vaga para atuar alocado em cliente, do ramo financeiro/investimentos.

Local
São Paulo - Faria Lima (Zona Sul)

Obrigatórios:
Design Patterns
DDD - TDD
API REST
SOLID - pelo menos uma camada

Contratação:

CLT FULL + benefícios

Como se candidatar
Por favor envie um email para franciele@imaginebeyond.com.br seu CV anexado - enviar no assunto: Vaga Back-EndSr

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
