### ISSUE TITLE
[Remoto] Back-end PHP/Node.js Developer @ VipCommerce

### ISSUE THREAD

**Issue by gabrielhws** [backend-br/vagas#2723]
## VipCommerce

A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.

## Habilidades
- PHP
- Javascript
- Node.js
- BDD

## Descrição da vaga

A VipCommerce é uma empresa especializada em e-grocery, especificamente e-commercepara supermercados, atacarejos e atacados. Atualmente é Líder no segmento na vertente white-label, integrada e homologada com os maiores ERP´s do segmento. 

Buscamos uma Pessoa Desenvolvedora Fullstack com maior foco em Back-end Node.js ou PHP. Profissional com perfil de destaque e que possa crescer de maneira acelerada juntamente com a VipCommerce.  

## Local

100% Remoto

## Requisitos

- +2 anos de experiência em posição semelhante
- Escreva código bem projetado, testável e eficiente
- Domínio de programação orientada a objetos usando linguagens como PHP, Typescript ou Javascript
- Essencial trabalhar em ambiente Linux
- Habituado em trabalhar com princípios SOLID e DDD
- Experiência em trabalhar com banco de dados relacionais (MySQL ou AWS Aurora)
- Conhecimentos em escrever REST APIs usando Node.js ou PHP Laravel
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup)
- Ser engajado com os ideias do negócio, abraçar as causas da empresa e frequentemente ser "confundido com o dono", pelo aspecto do pensamento comprometido.
- Ser habituado com metodologias ágeis
- Saber trabalhar em equipe, em times (participativo, paciente, mediador)
- Conhecimentos em escrever Unit Tests (Jest, Mocha ou PHP Unit)
- Conhecimentos em BDD

**Diferenciais:**

- Conhecimentos em desenvolvimento front-end usando Angular.js
- Conhecimentos básicos em Microservices
- Experiência em framework CAKE PHP
- Contato com cultura DevOps e CI/CD

## Benefícios

- PJ ou CLT
- Plano Saúde Unimed
- Boa flexibilidade de horários de trabalho
- Subsídio de cursos e eventos em determinadas periodicidades
- Vale alimentação

## Contratação

PJ ou CLT

## Como se candidatar

Candidatar-se em: [https://bit.ly/3jdUIij](https://bit.ly/3jdUIij)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada etapa do processo.
E-mail para contato em caso de não haver resposta: contato@coodesh.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by lpj145** [comment]
a plataforma de vocês esta dando erro pra se candidatar.
