### ISSUE TITLE
[São Paulo] Backend Developer na FGV

### ISSUE THREAD

**Issue by cmarqs** [backend-br/vagas#273]
### Descrição da Vaga
Projeto de 6 meses. Analisar, documentar e desenvolver API para integrar frontend de 3 sites que estão em operação utilizando Python/Flask. Participar de reuniões técnicas de coleta de requisitos para módulo de leitura de PDF utilizando OCR para captura dos dados e salvá-los em um banco para exibição em portal de consulta. Controlar o fluxo de coleta e processamento dos dados utilizando o AirFlow.

*Necessário*
Linux (Ubuntu) 
Git / GitFlow
AirFlow
Python Flask, SQLAlchemy, Migrations
Banco de Dados Postgre ou MySQL
Análise e documentação de sistemas

*Diferencial*
PHP (WordPress) HTML CSS Javascript

### Local
Vila Mariana - São Paulo

### Contratação
 - PJ - Informar valor hora

### Como se candidatar
Por favor envie um e-mail para cleiton.marques@fgv.br com seu CV anexado ou link com valor hora - enviar no assunto: Vaga Back-End.

### Labels
 - Remoto
 - PJ
 - Senior

**Comment by Dborah** [comment]
enviado!

**Comment by pabrrs** [comment]
Enviado 🙏

**Comment by cmarqs** [comment]
vlw pessoal!
