### ISSUE TITLE
[Remoto] Back-end Developer @ Eficaz Marketing e Tecnologia

### ISSUE THREAD

**Issue by MarianeVeiga** [backend-br/vagas#2734]
## Nossa empresa

Você que deseja atuar em uma empresa de tecnologia e marketing com forte expansão nos mercados de e-commerce saas e fábrica de software, agora é a hora!  Estamos com vagas para Desenvolvedor Web no modelo Home Office para todo o Brasil. 

## Descrição da vaga

Como desenvolvedor, o seu objetivo é oferecer uma experiência incrível ao usuário utilizando tecnologias inovadoras e de alta qualidade. 

## Local

100% Remoto

## Requisitos
• Desenvolvimento back-end em geral (PHP, Laravel, Wordpress)
• Desenvolvimento front-end em geral (HTML, CSS, Wordpress);
• Experiências em projetos com Javascript;
• Domínio de algum framework de Javascript (React, Vue.js ou Angular);
• Atuação em projetos com React.

**Desejáveis:**
• React-Native
• API

**Diferenciais:**
Carga horária Flexível:
 Entrada: 08:00 às 08:30, segunda a sexta-feira
 Saída: 18:00 às 18:30, segunda a quinta-feira
 Saída: 17:00 às 17:30, às sexta-feira

## Benefícios
• Ambiente de trabalho leve, descontraído e colaborativo
• Horário flexível
• Equipe jovem e muito unida
• Day Off de aniversário
• Vale-refeição*
• Convênio Médico*
• Parcerias com em algumas Faculdades*

## Contratação
PJ ou CLT a combinar

## Como se candidatar

Envie seu currículo para o e-mail: vagas@eficazconsultoria.net.br , com o nome da vaga de título.

#### Alocação
- 100% Home Office

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by thallysrc** [comment]
essa vaga não seria Full-stack inves de Back-end?

**Comment by MarianeVeiga** [comment]
Bom dia! Temos vagas para Back-end, Front-end e Full-stack.

**Comment by danielhe4rt** [comment]
Então, eu vejo que vocês estão procurando um Fullstack no caso. Eu gostaria de me candidatar, porém há o impedimento do Front-end.

Caso eu me candidate como back-end, eu teria que dar manutenção em front-end quando necessário?

**Comment by MarianeVeiga** [comment]
> Então, eu vejo que vocês estão procurando um Fullstack no caso. Eu gostaria de me candidatar, porém há o impedimento do Front-end.
> 
> Caso eu me candidate como back-end, eu teria que dar manutenção em front-end quando necessário?

Bom dia!

Agradeço o contato, mas fechamos todas as vagas.

Obrigada.
Mariane

**Comment by MarianeVeiga** [comment]
Bom dia a todos.
Agradeço muito a todos que enviaram currículo para nós e com muita satisfação, venho comunicar que as vagas já foram preenchidas.

Desejo sucesso a todos.

Att.
Mariane
Gente e Gestão - Eficaz Marketing e Tecnologia
