### ISSUE TITLE
[São Paulo] Back-End Java na [Foco em você]

### ISSUE THREAD

**Issue by kvilela** [backend-br/vagas#274]
Estamos com vagas para um cliente de soluções de pagamentos do Banco do Brasil, Bradesco e Cielo.
Gosta de desafios? Envie seu currículo para [contato@focoemvoce.com.br](url) 
Aceitamos Indicações

![backend java](https://user-images.githubusercontent.com/8458082/41879766-6bd2481a-78b1-11e8-92e4-83e61d379e4f.png)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
