### ISSUE TITLE
[São Paulo] Software Engineer at Dafiti Group

### ISSUE THREAD

**Issue by gabfssilva** [backend-br/vagas#275]
Dafiti is the biggest Latin America fashion e-commerce. We are supported by brands like Rocket and JP Morgan. We're currently over 40 engineers working to maintain and create new services to evolve our product. Our goal is to use our software to impact as many people as we can.

#### We expect you to:

- build highly concurrent microservices;
- design beautiful RESTful APIs;
- construct apps with functional programming principles and/or object oriented patterns;
- build low-latency, highly resilient apps using reactive programming principles;
- help us with our agile culture; 
- talk with our partners from other countries; and
- be nice.

#### You will be a good match if you:

- are a fast learner;
- have good knowledge in algorithm and data structures;
- already have worked with agile principles (Scrum, Kanban, Lean);
- enjoy challenges and debates;
- already use functional programming principles in your apps;
- are familiar with asynchronous messaging (with Kafka, RabbitMQ or alike);
- have solid knowledge in both SQL and NoSQL databases; and
- can communicate in English.

#### And it’d be nice if you:

- know Java 8, Kotlin, Scala or Clojure;
- know PHP (yes, for legacy systems);
- know RESTful;
- know Vertx.io, Akka, Spring Web Flux, ReactiveX or any reactive library;
- know Event Sourcing; and
- already have built a reactive app and launched it on production.

### Benefits

- CLT;
- meal ticket;
- profit sharing;
- discount for all Dafiti Group products;

### How to apply

Send an e-mail to gabriel.francisco@dafiti.com.br with the subject as "Vaga back-end" informing your Linkedin profile and your GitHub account (if you have one).

### Labels

- CLT
- Sênior
- Pleno
- Especialista
- Full time

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
