### ISSUE TITLE
[Remoto] Back-end Developer @ Plugg.to

### ISSUE THREAD

**Issue by fabriciovieira** [backend-br/vagas#2754]
## Nossa empresa

Plugg.To é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces. Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015 e desde então não para de crescer.

## Descrição da vaga

O Plugg.to está buscando mais um(a) profissional para compor nosso time de desenvolvedores. O(a) Developer vai participar da manutenção dos serviços existentes, bem como na construção de novas soluções para atender os clientes e parceiros. Nosso stack básico usa PHP Laravel, MySQL, jQuery e Vue.js. É imprescindível conhecimento no uso, manutenção e criação de APIs.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em PHP e Framework Laravel;
- Sólidos conhecimentos em MySQL;
- Sólidos conhecimentos em APIs RESTFul;
- Desenvolvimento front-end em geral (HTML, CSS, Javascript);
- Experiência significativa comprovada em desenvolvimento de aplicações web.

**Desejáveis:**
- Conhecimento de Vue.js;
- Conhecimentos em Kubernetes e Docker;
- Conhecimentos em Node.js;
- Conhecimentos em MongoDB.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para fabricio.vieira@plugg.to com seu CV anexado - enviar no assunto: Vaga BackEnd Developer

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by tiago123456789** [comment]
A vaga ainda está aberta?
