### ISSUE TITLE
[REMOTO] Estágio em Desenvolvimento Back-End na UPNID

### ISSUE THREAD

**Issue by vemproninho** [backend-br/vagas#2765]
**Nosso DNA**
Somos uma startup em crescimento acelerado, então você terá a oportunidade de aprender muito e crescer com o time. O ambiente é descontraído, mas somos muito responsáveis com nosso trabalho e comprometidos com a entrega - não fazemos trabalho meia boca.

Temos fome! Estamos em constante evolução, buscando sempre a melhor solução para os desafios que encontramos, o que significa que nem sempre temos todas as respostas. Por isso, capacidade de adaptação, ser um entusiasta de novas tecnologias e ter disponibilidade para aprender são características muito importantes para fazer parte desse squad. Moramos fora da zona de conforto, não sabemos tudo, mas aprendemos rápido.

**O que você precisa**
Para estagiar com a gente, você precisa estar cursando Ensino Superior, mas não exigimos nenhuma graduação ou certificado específico.

Em relação às tecnologias que a gente usa, você encontrará por aqui Golang, Protobuf, MongoDB, Redis, Git, Elasticsearch, Datadog, Istio e Terraform. Se ainda não teve contato com algumas delas, não entre em pânico! O que precisamos mesmo é que você tenha uma boa lógica de programação e muita vontade de aprender! É um diferencial conhecer design patterns e conceitos SOLID.

De maneira geral, a gente curte a galera que é estudiosa, analítica, metódica, organizada. E acreditamos que saber inglês também é importante para ter fluência nesse universo.

Estamos procurando um estagiário que vai nos ajudar a desenvolver a nossa área de Risco, e não apenas fazer ela funcionar. Ah, e a gente acredita que estágio é feito para que você aprenda e se desenvolva enquanto profissional, então conte com a gente na sua jornada, a gente ta aqui para compartilhar o que sabemos e te apoiar em vôos cada vez mais altos!

**Sobre o desafio**
Um dia típico de um estagiário desenvolvedor na Upnid inclui:

Acompanhar e estudar sobre Golang, API's, arquitetura cloud e microserviços.
Acompanhar e estudar sobre o mercado de pagamentos e vendas online, trazendo novas ideias para o projeto.
Colaboração remota via Slack, Jira, Notion e videoconferência.
Alinhar com o time o andamento dos projetos e a preparação para lançamento de novas funcionalidades.
Reunião com a equipe para definir soluções para os problemas que você identificou e priorizou.

**Sobre a vaga**
Nosso squad de Risco trabalha remoto, então você pode se candidatar de qualquer lugar do Brasil! :)

A gente oferece Bolsa Auxílio, Plano de Saúde (opcional), UpGym (treino com personal 3x por semana), Vale UpHouse (para você visitar o HQ quando for seguro novamente) e uma Cultura Colaborativa, de Liberdade e Autonomia.

Se identificou? Aguardamos ansiosos a sua candidatura!
https://upnid.breezy.hr/p/6e295b87083f-estagiario-de-desenvolvimento-back-end

#VemProNinho

**Comment by RafaelEmery** [comment]
Me inscrevi e gostei MUITO da vaga e empresa. Pode me dizer em quanto tempo dão um retorno?

**Comment by lucasferreiraos** [comment]
Olá! Quando clico no site diz que esta vaga não está mais aceitando candidatos.

**Comment by ViniciusOl1** [comment]
Disponível?

**Comment by lucasferreiraos** [comment]
> Disponível?

Sim, estou!

**Comment by ArieleM** [comment]
Olá! A vaga já foi encerrada?

**Comment by th3d3rkn3ss** [comment]
A vaga está aberta ainda? Tenho interesse.

**Comment by Luisnadachi** [comment]
Olá, a vaga ainda está aberta?

**Comment by Thomasnsa** [comment]
Opa! estou interessado na vaga, tenho desejo de aprender e já conheço um pouco de programação. Sei que posso contribuir e ajudar esse time!

**Comment by kakarinax** [comment]
Oi! Vi essa vaga no LinkedIn, já foi preenchida? 
Tenho noções de programação e gostei bastante da oportunidade de aprendizado dessas tecnologias 🤩

**Comment by vemproninho** [comment]
Oi pessoal, boa noite! A vaga já foi encerrada, por isso o link não está mais disponível.
