### ISSUE TITLE
[REMOTO] Fullstack Dev [Pleno] @Catarse

### ISSUE THREAD

**Issue by thiagocatarse** [backend-br/vagas#2773]
## A empresa
O Catarse é a primeira plataforma de financiamento coletivo para projetos criativos criada no Brasil e é hoje um dos principais canais para artistas, jornalistas, quadrinistas, autores, músicos e profissionais do mercado criativo independente tirarem seus projetos do papel. [Saiba mais sobre o Catarse aqui. ](https://crowdfunding.catarse.me/quem-somos)

## Objetivo da vaga

- Trabalhar junto ao Time de Produto do Catarse, hoje composto por 5 pessoas:
    - 1 Líder de
    Produto/Designer
    - 2 Desenvolvedores Back-end
    - 1 Desenvolvedor
    Full-stack
    - 1 Analista de Infra
- Você será a pessoa no Time de Produto que estará mais focada em melhorar a experiência dos usuários do Catarse, por meio da resolução de bugs e atividades operacionais e construção de features que tenham como objetivo não só resolver problemas frequentes da comunidade de usuários, como também facilitar o trabalho do time de suporte e administrativo do Catarse.
- No seu trabalho, você não só irá interagir com o time de produto, como também com o nosso time de Suporte, entendendo os problemas e resolvendo as demandas dos usuários trazidas pelo Suporte.

## Quem é você

- Apaixonada(o) pelo o que o Catarse faz: ser parte do processo de construção de uma
cultura de colaboração no Brasil através do financiamento coletivo de
projetos criativos;
- É curioso(a) e gosta de ter problemas complexos no seu colo para serem resolvidos;
- Fica confortável em trabalhar de casa - somos uma empresa 100% remota;
- Fica confortável em trabalhar em um time enxuto: não temos recursos
infinitos, não temos equipe enorme para resolver tudo. É preciso colocar a mão na massa;
- É organizada(o) e rígido(a) com a qualidade (e beleza!) do código escrito;
- Tem apreço por uma boa documentação do código;
- Tem paciência para traduzir problemas de programação para uma linguagem mais palatável para outros membros do time do Catarse (que não falam a língua dos devs)
- É comunicativo(a) e gosta de vestir o chapéu do cliente (ou seja, tem empatia para entender os problemas, sentir as dores de quem está sentindo o problema, e ajudar o time de suporte a explicar a nossa comunidade os problemas enfrentados)
- Interessado(a) em aprender novas linguagens e se adaptar às mudanças (às vezes rápidas) no código do Catarse;

## Como será o seu dia a dia

- Hoje o time de produto tem duas filas de atividades em paralelo bem distintas:
    - (1) Uma fila onde gerenciamos atividades e features que não estão relacionadas com o dia-a-dia operacional da plataforma, e tem como objetivo mover o produto para onde o negócio quer ir (aqui entram atividades como refatoração de código, novas features)
    - (2) Uma fila onde gerenciamos as atividades rotineiras da nossa operação e que em grande parte são geradas pelo Time de Suporte ao cliente do Catarse. São basicamente operações de rotina, investigação e resolução de bugs, além de construção de features e soluções para eliminar bugs recorrentes, procurando melhorar a experiência não só do nosso backoffice (Time de Suporte e Time Administrativo), como também da nossa comunidade de usuários (realizadores de projetos e apoiadores).
    - Seu dia a dia estará vinculado à essa segunda fila, e você estará em contato constante não só com o Time de Suporte, como também com o nosso desenvolvedor Sênior, que tem mais conhecimento da aplicação e irá te orientar em como investigar e resolver atividades rotineiras.
    - Nós não temos horário fixo, mas como você irá trabalhar em contato constante com o Time de Suporte, você deverá criar algumas janelas durante horário comercial para ficar atento(a) a qualquer pedido que possa aparecer e que eles precisem de sua ajuda.

## Conhecimentos desejáveis

Buscamos uma pessoa que seja apaixonada por desenvolvimento de software escalável de qualidade:

- Experiência com APIs REST
- Conhecimento de Javascript, Rails e PostgreSQL.
- Familiaridade com Git.
- Manter a qualidade e garantir a capacidade de resposta das nossas aplicações.
- Colaborar com o resto da equipe de desenvolvedores para projetar, fazer manutenção e lançar novas features.
- Colaborar com a equipe de Suporte (atendimento ao cliente) para entender os
problemas/bugs enfrentados pelos nossos usuários e resolvê-los com
presteza.
- Manter a integridade e a organização do código.
- Participar da construção de soluções através da análise do problema, de retirar
dúvidas técnicas sobre a viabilidade e dificuldade de implementar tal
solução.
- Saber se certificar que o
problema que está sendo resolvido em qualquer situação está claro,
trazer as dúvidas pertinentes, planejar adequadamente a execução antes
de escrever código, e garantir a entrega da solução com precisão.
- Corrigir bugs.
- Trabalhar com o restante do time de produto para converter projetos em aplicações.
- Inglês intermediário (leitura e escrita)
- Experiência com logging e documentação de código;
- Já ter apoiado projetos no Catarse é sempre um plus 🖤

## Local de trabalho

Não temos escritório físico. Então você trabalha de onde quiser (OBS: isso não é por causa da Covid-19. Nós já éramos 100% remoto bem antes da pandemia e seguiremos assim pra sempre)

## Benefícios

- **Trabalho remoto:** você trabalha de casa e tem flexibilidade para construir o seu horário com o time.
- **Carga horária reduzida:** full-time no Catarse é de 30 horas semanais.
- **Bem-estar:** Você pode usar até 3 horas de suas horas semanais para atividades
pessoais de bem-estar (Natação? Corrida? Bicicleta? O que mais te interessar!)
- **Férias:** Você vai ter 30 dias de férias/folgas remuneradas por ano e, além disso, dias de dispensa quando tiver questões médicas (para você e familiares), que não descontam nesses dias de férias.

## Salário

- R$4.500,00 (full-time). Trabalho remoto. Pagamento via PJ
- Início em Setembro/Outubro de 2020.

## Como aplicar para a vaga
Acesse [este link](https://catar.se/vaga_fullstack) e aplique por lá

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

#### Tecnologias
- Javascript
- Rails
- PostgreSQL

**Comment by Pauloparakleto** [comment]
@thiagocatarse, O link pode não funcionar por causa de um redirect. Esse é o mesmo link sem o redirect.
https://catarse.freshteam.com/jobs/CJVOIZkBHVxG/desenvolvedor-a-rails-backend-junior-100-remoto
