### ISSUE TITLE
[REMOTO] Back-end Rails Developer [Júnior] @Catarse

### ISSUE THREAD

**Issue by thiagocatarse** [backend-br/vagas#2774]
## A empresa
O Catarse é a primeira plataforma de financiamento coletivo para projetos criativos criada no Brasil e é hoje um dos principais canais para artistas, jornalistas, quadrinistas, autores, músicos e profissionais do mercado criativo independente tirarem seus projetos do papel. [Saiba mais sobre o Catarse aqui. ](https://crowdfunding.catarse.me/quem-somos)

## Objetivo da vaga

- Trabalhar junto ao Time de Produto do Catarse, hoje composto por 5 pessoas:
    - 1 Líder de
    Produto/Designer
    - 2 Desenvolvedores Back-end
    - 1 Desenvolvedor
    Full-stack
    - 1 Analista de Infra
- No momento estamos executando um projeto grande de refatoração de parte de nossa aplicação. Estamos saindo dos microserviços e voltando ao monolito. O seu objetivo de curto prazo será portanto de somar esforços nesse projeto, gerenciado por um dos nossos desenvolvedores back-end. Esse projeto é uma boa oportunidade para que você tenha contato com o núcleo da aplicação do Catarse, que é nossa máquina de pagamentos.
- Seu objetivo de médio e longo prazo é seguir nessa frente do Catarse de evoluir nossa aplicação (com foco em nossa máquina de pagamentos e todas as funcionalidades relacionadas a ela).

## Quem é você

- Apaixonada(o) pelo o que o Catarse faz: ser parte do processo de construção de uma
cultura de colaboração no Brasil através do financiamento coletivo de
projetos criativos;
- É curioso(a) e gosta de ter problemas complexos no seu colo para serem resolvidos;
- Fica confortável em trabalhar de casa - somos uma empresa 100% remota;
- Fica confortável em trabalhar em um time enxuto: não temos recursos
infinitos, não temos equipe enorme para resolver tudo. É preciso colocar a mão na massa;
- É organizada(o) e rígido(a) com a qualidade (e beleza!) do código escrito;
- Tem apreço por uma boa documentação do código;
- Interessado(a) em aprender novas linguagens e se adaptar às mudanças (às vezes rápidas) no código do Catarse;

## Como será o seu dia a dia

- Você trabalhará diretamente com o time de produto na construção e entrega de atividades relacionadas ao projeto de Refatoração da máquina de pagamentos.
- A definição das atividades e gestão do projeto é de responsabilidade do líder do projeto, mas você terá total liberdade para sugerir caminhos, soluções e abordagens no projeto.
- Nosso time tem somente uma reunião semanal onde todo o time se reúne, e onde falamos sobre o que estamos fazendo e sobre os próximos passos da semana.
- Eventualmente você irá trabalhar em atividades e correção de bugs que não estejam ligados a esse projeto, mas de um modo geral seu foco é na refatoração do Catarse.
- Não temos horário fixo e você vai poder organizar seu horário em função das suas necessidades pessoais e das necessidades do projeto (combinadas diretamente com o líder do projeto)

*OBS: Essa é uma visão geral no curto prazo, pois temos esse foco do projeto no momento.*

## Conhecimentos desejáveis

Buscamos uma pessoa que seja apaixonada por desenvolvimento de software escalável de qualidade:

- Experiência com APIs REST
- Conhecimento de Javascript, Rails e PostgreSQL.
- Familiaridade com Git.
- Manter a qualidade e garantir a capacidade de resposta das nossas aplicações.
- Colaborar com o resto da equipe de desenvolvedores para projetar, fazer manutenção e lançar novas features.
- Colaborar com a equipe de Suporte (atendimento ao cliente) para entender os
problemas/bugs enfrentados pelos nossos usuários e resolvê-los com
presteza.
- Manter a integridade e a organização do código.
- Participar da construção de soluções através da análise do problema, de retirar
dúvidas técnicas sobre a viabilidade e dificuldade de implementar tal
solução.
- Saber se certificar que o
problema que está sendo resolvido em qualquer situação está claro,
trazer as dúvidas pertinentes, planejar adequadamente a execução antes
de escrever código, e garantir a entrega da solução com precisão.
- Corrigir bugs.
- Trabalhar com o restante do time de produto para converter projetos em aplicações.
- Inglês intermediário (leitura e escrita)
- Já ter apoiado projetos no Catarse é sempre um plus 🖤

## Local de trabalho

Não temos escritório físico. Então você trabalha de onde quiser (OBS: isso não é por causa da Covid-19. Nós já éramos 100% remoto bem antes da pandemia e seguiremos assim pra sempre)

## Benefícios

- **Trabalho remoto:** você trabalha de casa e tem flexibilidade para construir o seu horário com o time.
- **Carga horária reduzida:** o full-time no Catarse é de 30 horas semanais.
- **Bem-estar:** Você pode usar até 3 horas de suas horas semanais para atividades
pessoais de bem-estar (Natação? Corrida? Bicicleta? O que mais te interessar!)
- **Férias:** Você vai ter 30 dias de
férias/folgas remuneradas por ano e, além disso, dias de dispensa quando tiver questões médicas (para você e familiares), que não descontam nesses dias de férias.

## Salário

- R$2.900,00 (full-time). Trabalho remoto. Pagamento via PJ
- Início em Setembro/Outubro de 2020.

## Como aplicar para a vaga
Acesse [este link](https://catar.se/vaga_rails) e aplique por lá

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

#### Tecnologias
- Javascript
- Rails
- PostgreSQL

**Comment by karineamorim** [comment]
Olá, acho que esse link não está funcionando, poderia mandar outro? adoraria poder me candidatar para a vaga.

**Comment by stephannv** [comment]
Oi @karineamorim , estranho, aqui funcionou, mas tenta por esse aqui, é o mesmo link só que sem o redirect:
https://catarse.freshteam.com/jobs/CJVOIZkBHVxG/desenvolvedor-a-rails-backend-junior-100-remoto
