### ISSUE TITLE
[São Paulo] Desenvolvedor(a) PHP na MinniS

### ISSUE THREAD

**Issue by SupPayFintech** [backend-br/vagas#278]
A MinniS, uma startup com uma solução para pequenos comerciantes, atualmente sendo acelerada pelo iDEXO da TOTVS, esta buscando Desenvolvedor(a) Fullstack, com comprometimento para participar de um projeto grande.

Skills:

Laravel (5.6)
API padrão REST
MySQL (5.7)
Docker
Nginx
Git
AWS (RDS, S3 e EC2)
Linux, preferência distro Ubuntu
Diferenciais:

Deeplink
Ser ativo na comunidade de tecnologia
GitHub
Manjar de integrações
Swagger
Oferecemos:

Salário R$ 4.000,00 CLT (se puder ser PJ por uns 6 meses, podemos conversar)
Vale Transporte
Vale Refeição
Regime de contratação:

CLT
Outros benefícios

Bônus ($$)
Espaço para palestrar ou acompanhar os meetups, palestras, mentorias e networking tanto da TOTVS quanto da Idexo. O segundo batch de startups na Idexo vai começar e o/a profissional vai aproveitar desde o começo o que a Idexo tem de melhor.
Trabalho alocado em São Paulo/SP (infelizmente não estamos aceitando remoto para esta posição): Totvs - Av. Braz Leme, 1000 - Santana

INÍCIO IMEDIATO!

Site: http://minnis.com.br/

Espaço de trabalho: https://www.idexo.com.br/

O que usamos de tecnologia? Tem no Medium! :D
https://medium.com/id…/dev-demoday-idexo-minnis-70c595939681

Não sabe o que é Deep Linking? O mestre John CalistroJohn Calistro, um dos mentores explica :D
https://medium.com/@…/o-que-%C3%A9-deep-linking-d0208d746874

JÁ FALAMOS QUE É PARA INÍCIO IMEDIATO?! :D

Aplicações com GitHub para o email: contato@minnis.com.br

Labels
PHP
API
Fullstack
CLT

**Comment by bryan-alves** [comment]
Qual seria o nível de desenvolvedor, Junior, Pleno ou Sênior... ?

**Comment by SupPayFintech** [comment]
Estamos buscando um pleno recente, ou seja, um júnior que subiu recentemente para pleno ou quer subir! ;-)

**Comment by bryan-alves** [comment]
@Moov8Systems Opa, muito legal. Se encaixo perfeitamente neste perfil, pois recentemente subi para pleno. Entrarei em contato!

**Comment by SupPayFintech** [comment]
Olá Bryan. Obrigado pela aplicação. Já respondemos o seu email. Um abraço
