### ISSUE TITLE
[Brasilia] Back-end Developer @ Money Cloud Tecnologia Ltda

### ISSUE THREAD

**Issue by Alopes-web** [backend-br/vagas#2787]
Descrição da vaga
Atender demandas dos sistemas já publicados no mercado, além de poder trabalhar em sistemas ainda em desenvolvimento. Desenvolver banckend em PHP e Laravel, consumindo APIs já existentes ou que serão desenvolvidas conforme necessidade. Experiência PHP/Laravel. Domínio MySQL. Conhecimentos mongoDB, RESTFull, Javascript/jQuery, HTML, CSS (bootstrap).

Local
Guara - Distrito Industrial - Brasília - DF

Desejáveis:

nível de inglês adequado para exercício das tarefas

Contratação:
PJ a combinar

 Nível
- Pleno
- Sênior

Currículos para: alopes@moneycloud.com.br

**Comment by KevenKlain** [comment]
Boa tarde, solicito uma chance para entrar.
