### ISSUE TITLE
[Porto Alegre] Back-End Developer na ilegra

### ISSUE THREAD

**Issue by ilegra-oportunidades** [backend-br/vagas#279]
**Quem somos:**
A ilegra é uma empresa global de TI e negócios que tem uma abordagem baseada em pensar antes e além do software e que ajuda seus clientes a inovar e a crescer.
 Somos movidos por desafios e buscamos pessoas que são apaixonadas pelo que fazem para compor o nosso time! Para trabalhar conosco precisa ter brilho no olho e muita vontade de fazer a diferença. Se você se identifica com o nosso jeito, junte-se ao time “Sou ilegra”.

**O que buscamos:** 
Desenvolvedor(a) Back End Java – RS
Área: Dev
Perfil: Pleno/Sênior

-Descrição: Desenvolvemos em Java aproveitando a grande quantidade de ferramentas open source existentes nessa plataforma. Trabalho em time e práticas de Engenharia de Software (eXtreme Programing) são os pilares do desenvolvimento na ilegra. Entregamos aplicações estáveis com vários níveis de testes, permitindo melhorias técnicas por refactoring. Agile Coaching, Pair programming, peer review, TDD, agile design, clean code e lean architecture são algumas das práticas que nos permitem passar mais tempo desenvolvendo novas funcionalidades do que corrigindo bugs. 

-Qualificações: Sólido conhecimento em Java. Desejável inglês técnico e interesse em diferentes tecnologias.

**Contratação**: 
CLT Full + benefícios

**Como se candidatar:**
Enviar currículo para curriculos@ilegra.com

**Labels:**
-Pleno
-Sênior
-CLT
-Alocado
-Java

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
