### ISSUE TITLE
[São Paulo/SP | Presencial] FullStack Developer @ Minery

### ISSUE THREAD

**Issue by betodoescher** [backend-br/vagas#2794]
## Nossa empresa

Marketplace de commodities minerais, com o principal propósito de mapear, validar, registrar e expor mineradoras de pequeno e médio porte.
Desafiamos um sistema de negociação desatualizado e ineficiente ao construir um ambiente 100% digital, simples e seguro que atende às necessidades do mercado de mineração, sem intermediários. Através da Minery empresas do mundo todo poderão ter acesso a minérios ofertados pelos fornecedores cadastrados em nosso banco de dados.

## Descrição da vaga

Buscamos por um perfil profissional com proatividade e comprometimento em entregar software com qualidade, contribuindo com conhecimentos e experiências para aumentar a qualidade técnica do próprio time. Atuará na construção do Front-end e Back-end utilizando Vue.js e Laravel.

## Aqui você irá

- Desenvolver código limpo, testável e de fácil manutenção
- Contribuir com todo o processo de desenvolvimento de software
- Implementar features novas e investigar problemas em produção
- Contribuir nas discussões técnicas sobre os desafios encontrados
- Participar do processo de code review, garantindo qualidade e consistência do código

## Procuramos por pessoas que

- Sejam detalhistas e analíticas
- Gostem de lidar com projetos grandes e desafiadores
- Consigam trabalhar em equipe de forma colaborativa e em função de um objetivo comum
- Busquem aprendizado constante
- Queiram construir um ambiente de trabalho de respeito e apoio mútuo

## Local

Escritório, São Paulo/SP - Zona Sul

## Requisitos

**Obrigatórios:**
- Experiência desenvolvendo aplicações complexas
- Conhecimentos avançados em PHP 7 e Laravel/Lumen
- Sólido conhecimento em API RESTful e JWT
- Conhecimentos avançados em HTML, CSS, JavaScript
- Vue.js 2 ou framework similar (React, Angular)
- Git
- Inglês técnico

**Diferenciais:**

- Vue.js 2 ou framework similar (React, Angular)
- Quasar Framework
- Github ou projetos pessoais de estudo
- Processos/Ferramentas de Integração Contínua
- Docker
- Plataformas em nuvem (experiência em GCP, Azure ou AWS)
- Projetos open-source

## Contratação

- CLT
- Salário R$ 7.500

## Como se candidatar

Por favor, envie um e-mail para klelber.doescher@census.inf.br com seu CV anexado. Enviar no assunto: Vaga FullStack Laravel/Vue-js

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by danielhe4rt** [comment]
Boa noite, gostaria de saber se o foco é back-end ou front-end nessa vaga.

Tenho um amplo conhecimento em Laravel/Lumen porém mal conheço Vue.js e gostaria de saber se é possível um teste para metrificar a vaga.

**Comment by betodoescher** [comment]
Oi DanielHe4rt recebi seu e-mail, vou te responder com mais detalhes.

**Comment by betodoescher** [comment]
Oi DanielHe4rt recebi seu e-mail, vou te responder com mais detalhes.
