### ISSUE TITLE
[São Paulo] Full Stack Developer Senior ou Pleno na LIZA

### ISSUE THREAD

**Issue by paolamunaro** [backend-br/vagas#280]
LIZA - PLATAFORMA DE CADASTRO QUE PERMITE A CONEXÃO ENTRE EMPRESAS, ALÉM DE GESTÃO E GOVERNANÇA DE INFORMAÇÕES E DOCUMENTOS.

Descrição da Vaga
Oportunidade profissional única para desenvolvedores que tenham realmente espírito empreendedor, e que queiram construir do zero um projeto inovador e disruptivo. Se você sonha grande, quer desafios e faz a diferença, junte-se a nós.

Desejável:
- Desenvolvimento de plataforma Web, APIs e Banco de Dados
- Sólidos conhecimentos em linguagem Phyton ou Java
- Conhecimento em JavaScript e frameworks (AngularJS, React e etc.)
- Banco de Dados (SQL, NoSQL, MySQL)
- GitHub ou similar

Diferencial:
- Conhecimento de AWS

**Comment by simaodev** [comment]
Boa noite.
Segue meu linkedin e site pessoal com alguns projetos executados.
https://www.linkedin.com/in/williamfelipesimao/
https://wfsimao.github.io/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
