### ISSUE TITLE
[REMOTO] BackEnd Developer Sênior/Pleno @ Plug

### ISSUE THREAD

**Issue by ElVilhena** [backend-br/vagas#2816]
### Empresa
A Plug é uma plataforma que visa simplificar e trazer mais transparência para o setor de pagamentos online. Somos um hub de pagamentos digitais que permite diversas conexões à provedores (gateways, subs e adquirentes) através de uma integração. Além de providenciar flexibilidade e redundância, o hub também facilitará o roteamento de transações para otimização de taxa de aprovação e custos. Somos apoiados por um grupo experiente de investidores anjos e acabamos de fazer um round de captação.

Estamos buscando desenvolvedores backend sêniors, experientes e dispostos a encarar esse desafio com vontade, comprometimento e conhecimento para construir essa empresa. Estamos em fase inicial de desenvolvimento, portanto precisamos de alguém interessado em contribuir na construção do nosso software usando as melhores práticas em relação a escalabilidade, qualidade, custo e usabilidade. Atualmente usamos Node.js, Elixir, Python, e Java, mas o importante é se adaptar rapidamente e ser inteligente. Além do conhecimento técnico é importante ter uma boa comunicação para debater as escolhas de tecnologia na construção da plataforma.

Nosso time está composto atualmente de um responsável pela arquitetura e dois desenvolvedores de backend sêniors. Essa posição tem perspectiva de progressão de carreira para perfis de gestão e especialistas.

### Requisitos:
Expertise em Backend
Experiência em quaisquer linguagens: Node.js, Elixir, Python, Java. O importante é se adaptar rapidamente e ser inteligente 
Experiência com desenvolvimento e consumo de API

### Desejável:
Experiência em integração com gateways de pagamento  
Interesse em aprender novas tecnologias e compartilhar conhecimento
Capacidade de analisar escopos e demandas, também sugerir soluções.
Experiência com delivery contínuo e metodologias ágeis
Experiência em tokenização
Inglês para leitura de manuais e artigos técnicos

### Contratação
Salário competitivo, possibilidade de participação (equity)
De preferência Rio de Janeiro ou São Paulo, mas pode ser remoto
PJ a combinar

### Como se candidatar
Por favor adicione no linkedin (https://www.linkedin.com/in/alexvilhena/) ou envie um email para t@plugpagamentos.com com seu CV anexado.

### Labels: 
Git Jira NodeJS Elixir Python Java Devops PJ Sênior Presencial Remoto Rest StartUp AWS Pagamentos

**Comment by ElVilhena** [comment]
@Renato66 @guibranco @reginaldojunior vcs poderiam me ajudar a adicionar / editar labels? Queria tirar o Java e adicionar Remoto Git NodeJS Elixir Python Devops Rest AWS Pagamentos. 
E como consigo adicionar um assignee pra editar também?
Obrigado!

**Comment by Renato66** [comment]
@ElVilhena acredito que o gui ou reginaldo irão fazer isso,
> como consigo adicionar um assignee pra editar também

não consegue rs
