### ISSUE TITLE
[São Paulo] Backend Developer Senior ou Jr na LIZA

### ISSUE THREAD

**Issue by paolamunaro** [backend-br/vagas#282]
LIZA - PLATAFORMA DE CADASTRO QUE PERMITE A CONEXÃO ENTRE EMPRESAS, ALÉM DE GESTÃO E GOVERNANÇA DE INFORMAÇÕES E DOCUMENTOS.

Descrição da Vaga
Oportunidade profissional única para desenvolvedores que tenham realmente espírito empreendedor, e que queiram construir do zero um projeto inovador e disruptivo. Se você sonha grande, quer desafios e faz a diferença, junte-se a nós.

- Construção de toda a arquitetura inicial do banco de dados
- Definir infra adequada para suportar a operação e monitorar a operação
- Verificar e implementar as melhores tecnologias de criptografia para garantir segurança e velocidade da plataforma
- Estabelecer durante desenvolvimento da plataforma a integração com outros sistemas ERP/CRM (APIs)

Desejável:
- Conhecimento em linguagens Phyton ou Java
- Banco de Dados (SQL, NoSQL, MySQL)
- GitHub ou similar

Diferencial:
- Conhecimento de AWS

Envie seu CV para: paola.munaro@lizaid.com

## Labels

- Alocado
- PJ
- Remoto - Parcial
- Sênior

**Comment by guilhermeoa07** [comment]
Legal, pra onde envia o CV?

**Comment by paolamunaro** [comment]
Olá! Envie seu CV para paola.munaro@lizaid.com

**Comment by pabrrs** [comment]
Enviado :pray:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
