### ISSUE TITLE
[Remoto|Full Home] NodeJS Back-end Developer @ Climatempo

### ISSUE THREAD

**Issue by oliverthies** [backend-br/vagas#2820]
Descrição da empresa
A Climatempo simboliza mais de 30 anos de experiência no acompanhamento e previsão das condições meteorológicas no Brasil e America Latina. Fundada em 1988.

Foi a primeira empresa privada a oferecer análises customizadas para diversos setores do mercado, boletins informativos para meios de comunicação, canal 24 horas nas principais operadoras de TVs por assinatura e posicionamento digital consolidado com website e aplicativos, que juntos somam 20 milhões de usuários mensalmente.

Atualmente, é a principal empresa de consultoria meteorológica do país e possui serviços especializados para atender mais de 22 segmentos da economia. A Climatempo Consultoria faz uso dos melhores modelos matemáticos de previsão do tempo utilizados no mundo, adaptados para o Brasil em alta resolução.

Atividades e Responsabilidades
- O contratado irá nos auxiliar a manter e desenvolver novas features através de implementações no Back-end de alguns produtos.
**Tecnologias**:
NodeJS
PHP 5 & 7
REST
Javascript
MongoDB
Python ( desejável )
SQL/NoSQL.

**Requisitos**
- Experiência com ferramentas de versionamento de código (GIT,...);
- Habilidades interpessoais de escrita e de comunicação verbal;
- Muita experiência com back-end de sistemas
-Facilidade em debugar e identificar problemas.
-Excelente raciocínio lógico
-Facilidade com algorítmos mais complexos
-Experiência em sistemas de alta carga de acessos ( milhares de requisições por segundo )
-Design Patterns;
-Testes Automatizados;

Enviar email para fullstack@climatempo.com.br com o assunto "Climatempo Back-end" e se possível a pretensão salarial na mensagem.

**Comment by danielsidev** [comment]
Oi @oliverthies ! Tudo bem?
CLT ou PJ?
https://www.linkedin.com/in/danielsidev/

**Comment by oliverthies** [comment]
Oi Daniel
PJ

Em sex, 7 de ago de 2020 17:19, Daniel Siqueira <notifications@github.com>
escreveu:
