### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na Spot

### ISSUE THREAD

**Issue by gitsejaspot** [backend-br/vagas#284]
## Descrição da vaga
O Clube de Vantagens Spot está a procura de desenvolvedor para contribuir na criação e manutenção de diversos sistemas que estão sendo criados para suportar o constante crescimento da empresa.

## Local
Escritório, Botafogo - RJ

## Benefícios
- Vale Transporte
- Vale Refeição
- Plano de Saúde

## Requisitos

**Obrigatórios:**
- NodeJS
- Javascript
- Banco de Dados / SQL
- GIT
- REST API's

**Desejáveis:**
- AngularJS
- Ionic 
- AWS
- Ferramenta de Automação

## Contratação
CLT

## Como se candidatar
Enviar pretensão salarial e currículo para o e-mail: vemprotime@sejaspot.com.br com ''Vaga Back-End'' no assunto.

## Labels
Alocado
CLT
Júnior
Senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
