### ISSUE TITLE
[Belo Horizonte-MG / Manaus-AM] Back-end Developer @ Méliuz

### ISSUE THREAD

**Issue by gabrielhws** [backend-br/vagas#2842]
## Descrição da vaga

Nós do Méliuz temos grandes sonhos e desafios e sabemos que para chegarmos cada vez mais longe precisamos aumentar nossa grande família com uma pessoa desenvolvedora Back-End Sênior. Temos produtos acessados por milhões de pessoas e muitos projetos para torná-los ainda mais interessante para nossos usuários e parceiros. Contamos com uma equipe de desenvolvimento altamente qualificada e interdisciplinar que sempre prefere soluções Open Source ou livres.

Gostamos de novas tecnologias e não nos restringimos a apenas o que temos funcionando hoje. São milhares de operações por segundo com grandes picos sobre nossa stack, que é feita em PHP, Python, C++ e Node.js, roda com bancos de dados MySQL, PostgreSQL, Redis, BigQuery e Redshift, e é hospedada em ambiente de nuvem híbrida (AWS e Google Cloud).

**Você será responsável por:**
- Atuar no desenvolvimento e evolução dos produtos do Méliuz;
- Desenvolver e evoluir aplicações como APIs REST, além de realizar integrações com APIs de terceiros e plataformas como AWS;
- Projetar e implementar a persistência de dados das aplicações e garantir que o acesso seja seguro e eficiente;
- Atuar junto com a liderança e engenheiros do time para evoluir e tornar os sistemas/produtos do Méliuz cada vez mais escaláveis;
- Arquitetar soluções para problemas complexos e garantir que o código seja eficiente e de fácil manutenção;
- Realizar mentoria junto aos engenheiros júnior e pleno do time para garantir que as melhores soluções estão sendo tomadas;

## Méliuz 

O Méliuz é uma empresa que desbloqueia relações inteligentes de consumo. Estamos em uma busca constante de melhorar a forma que nossos usuários fazem suas compras em nossas lojas parceiras, de maneira que todos saiam ganhando. Queremos que nossos parceiros continuem conosco para toda a vida e, para isso, estamos sempre levando inovações até eles. Tudo isso aliado ao nosso espírito empreendedor nos tornou na maior empresa de cashback do Brasil e tem nos proporcionado um crescimento consistente. 
## Local

- Escritório, Belo Horizonte-MG
- Escritório, Manaus-AM

## Requisitos

- Conhecimentos avançados em linguagens e tecnologias como Python e Node.js;
- Conhecimentos avançados de algoritmos e estruturas de dados;
- Experiência trabalhando com banco de dados relacionais;
- Experiência desenvolvendo aplicações cliente-servidor e APIs REST;
- Experiência com testes automatizados e ambientes de CI/CD;
- Experiência com ferramentas de controle de versão, em especial Git;

**Diferenciais:**

- Experiência projetando e implementando sistemas/softwares escaláveis/missão crítica
- Experiência com banco de dados não relacionais - NoSQL
- Experiência com Docker
- Ter trabalhado em projetos como desenvolvedor FullStack
- Ter trabalhado com arquiteturas baseadas em microsserviços e monolitos
- Experiência com ferramentas de monitoramento de sistemas críticos
- Experiência com serviços da AWS
- Experiência com metodologias ágeis (Scrum, Kanban)
- Experiência empregando conceitos DevOps nos projetos em que trabalhou

## Benefícios

- Vale transporte;
- Vale refeição ou alimentação;
- Plano de saúde;
- Plano odontológico;
- Horário flexível;
- Convênio com Sesc;
- Biblioteca interna;
- Possibilidade de premiação por atingimento de metas coletivas;
- Cashback online em dobro;
- Licença Maternidade/Paternidade estendida;
- Auxílio Creche;
- Auxílio luto;

## Contratação

CLT

## Como se candidatar

- Vaga em Belo Horizonte-MG, candidatar-se em: [https://bit.ly/2Y8vmJV](https://bit.ly/2Y8vmJV)
- Vaga em Manaus-AM, candidatar-se em: [https://bit.ly/2DRaHCP](https://bit.ly/2DRaHCP)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by MoacirSchmidt** [comment]
"pessoa desenvolvedora" é a expressao mais ridícula que o politicamente correto já inventou

**Comment by leopedroso45** [comment]
> "pessoa desenvolvedora" é a expressao mais ridícula que o politicamente correto já inventou

Não vejo problema com o termo não, só quero meu emprego mesmo...
