### ISSUE TITLE
[Ribeirão Preto - SP] Back-end Developer @ Venda.lá [ Presencial ]

### ISSUE THREAD

**Issue by JessicaBarrosNerus** [backend-br/vagas#2845]
**Nossa empresa**

A Venda.la é uma Startup que desenvolve soluções para conectar vendedores aos principais marketplaces, possibilitando uma gestão centralizada. Ela é um HUB que integra os principais marketplaces. Ajudando em todo o fluxo de trabalho do seller: gestão de produtos, pedidos, atendimento e pós vendas.Seu maior diferencial é a automação de processos tanto no varejo on-line e off-line.
A empresa fica em Ribeirão Preto no Centro e hoje é composta por 21 funcionários com 10 programadores.

**Descrição da vaga**
Desenvolvimento e manutenção de sistemas em Laravel e Cake.
Criação e manutenção em APIs.
Documentação de toda a codificação.
Ajudar a encontrar soluções para problemas.
Trabalhar em equipes multidisciplinares em um ambiente scrum.

**Local**
Escritório, Ribeirão Preto - SP

Requisitos
-- PHP 7+
-- Laravel
-- MySQL
-- CSS
-- JS
-- GIT
-- API

**Desejáveis:**

Experiência com API (Mercado Livre, B2W, Amazon, etc)

Conhecimento em NodeJS
Conhecimento em desenvolvimento de sistemas em uma arquitetura de Micro Serviços
Conhecimentos básicos da AWS
Conhecimento em Docker
Teste unitário

**Benefícios**
VA/VR
Plano de Participação dos Resultados;
Trabalhar com os melhores computadores da Apple;
Ambiente jovem, descontraído, escritório confortável;
No Dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável;
Relacionamento próximo aos fundadores e diretores da empresa, além de uma equipe fantástica que está revolucionando o varejo.
Contratação
CLT

**Como se candidatar**
Por favor envie um email para jessica.barros@nerus.com.br com seu CV anexado - enviar no assunto: Vaga PHP Venda.lá

Alocado
Regime
CLT
Nível
Júnior
Pleno

**Comment by danielhe4rt** [comment]
Muito interessante essa vaga de back-end que tem como requisito algo do Front-end como CSS. Será que vocês não estão atrás de um full-stack?

**Comment by JessicaBarrosNerus** [comment]
Daniel, bom dia! Tudo bem?

O foco da vaga é BACK END mesmo.
O Front é algo a mais, não necessariamente precisa ter muito conhecimento.
Só o básico do básico.

[image: Foto de JÉSSICA BARROS]

JÉSSICA BARROS

Analista | RH

31 99773-670431 3273-4415
[image: logo nerus] <http://www.nerus.com.br/>
 [image: icone nerus linkedin]
<https://www.linkedin.com/company/nerussoftware/?viewAsMember=true>  [image:
icone nerus facebook] <https://www.facebook.com/nerussoftware/>  [image:
icone nerus instagram]
<https://www.instagram.com/nerussoftware/?hl=pt-br>  [image:
icone nerus youtube]
<https://www.youtube.com/channel/UCoCJoPP-TL5F1h6sQAaiXWA>  [image: icone
nerus website] <https://www.nerus.com.br/>

Viva o Omnichannel!




Em qua., 19 de ago. de 2020 às 21:35, Daniel Reis <notifications@github.com>
escreveu:
