### ISSUE TITLE
[São Paulo] Backend Developer Pleno (Node / Go) na Kiddo

### ISSUE THREAD

**Issue by CavalcanteLeo** [backend-br/vagas#285]
<a href="https://www.kiddolabs.com">![Kiddo](https://scontent.fcgh9-1.fna.fbcdn.net/v/t1.0-9/17757081_797286173763932_6083681800043838499_n.png?_nc_cat=0&oh=cd75184979f8adb6286b40994b4f9b84&oe=5BAEF756)</a>

## Descrição da vaga

Desenvolvedor senior backend **Node** e **Go**.

Experiente em desenvolvimento de plataformas complexas, white labels, usando técnicas de TDD, XP, programação funcional e metodologias ágeis.
Comprovar experiência, exibir portfólio online e informar contatos de referência.

Se você é um entusiasta de novas tecnologias, gosta de aprender, ensinar e desenvolver produtos que estão no dia a dia da galera, então tem o perfil que queremos para o nosso time!

## Local
São Paulo, Jardins (próximo ao parque ibirapuera)

## Requisitos

* Mínimo de 3 anos de experiência com Node.js;
* Mínimo de 1 ano de experiência com Golang;
* Mínimo de 5 anos de experiência com desenvolvimento para web;
* Trabalho em equipe;

## Coisas que usamos
* Node (es6, es7), Go 
* Postgres, MongoDB, MySQL, GraphQL, Redis 
* SQS / RabbitMQ
* Elastic Search 
* Microserviços em REST APIs 
* Amazon AWS 
* Docker / Docker Compose
* CI / CD
* Testes automatizados

## Contratação
PJ

## Diferenciais

* Ambiente de trabalho descontraído
* Dress code informal (bermuda!)
* Video game
* Flexibilidade de Horário
* Trabalhamos com metodologias ágeis (Scrum)
* Estamos sempre em busca de inovação

## Como se candidatar
Envie um e-mail para vagas@kiddolabs.com com seu LinkedIn e link de portfólio, idealmente explicando sua contribuição nos principais projetos listados e informar contatos de referência. Enviar também pretensão salarial. 
Enviar no assunto: "Vaga backend"

## Labels
Presencial
PJ
Pleno
Senior
Node.js
Golang

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
