### ISSUE TITLE
[Porto Alegre] Back-End Developer na [Mutuus]

### ISSUE THREAD

**Issue by pietrobonfiglioli** [backend-br/vagas#286]
A Mutuus é uma plataforma com foco em proporcionar uma experiência de qualidade ao cliente e facilitar o mundo de seguros.

**Descrição da Vaga**
Oportunidade profissional única para desenvolvedores que tenham realmente espírito empreendedor, e que queiram construir do zero um projeto inovador e disruptivo. Se você sonha grande, quer desafios e faz a diferença, junte-se a nós.
- Tirar a ideia do papel construindo o MVP da solução
- Construção de toda a arquitetura inicial da plataforma
- Definir infra adequada para suportar a operação
-Verificar e implementar as melhores tecnologias de criptografia para garantir segurança e velocidade da plataforma
-Montagem de equipe de desenvolvimento

**Desejável**
- Desenvolvimento de plataforma Web, APIs e Banco de Dados
- Sólidos conhecimentos em linguagem Phyton ou Java
- Banco de Dados (SQL, NoSQL, MySQL)
- GitHub ou similar

​
**Diferencial**
Conhecimento de AWS

Envie seu CV para: vagas@mutuus.net

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
