### ISSUE TITLE
[São Paulo] Junior Node.JS Developer @Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [backend-br/vagas#2864]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga

Oportunidade de trabalhar em empresa de tecnologia líder de mercado.
Irá ingressar em squad (aprox. 9 pessoas) 

## Local

Vaga Remota durante a pandemia, depois irá atuar no escritório (Zona Norte).

## Tecnologias que você irá trabalhar

Node.Js
Banco Amazon DynamoDB 
Angular
API Rest / Webservices
SQS (Amazon Simple Queue Service)

## Requisitos

NodeJs (obrigatório)
Banco Amazon DynamoDB (opcional)
Angular (opcional)
API Rest / Webservices 
SQS (Amazon Simple Queue Service) - (opcional)

## Benefícios

- Seguro de vida
- Vale Refeição
- Vale Transporte

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para livia.mello@roberthalf.com.br com seu CV anexado - enviar no assunto: NodeJS Junior

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by gdois** [comment]
Boa noite! Quanto tempo de resposta mais ou menos?

**Comment by LiviaMaron** [comment]
Olá! Tempo de 1 semana
