### ISSUE TITLE
[São Paulo]  Engenheiro de Software | Red Ventures

### ISSUE THREAD

**Issue by elvisdetona** [backend-br/vagas#287]
## Descrição da vaga

Como Engenheiro de Software na Red Ventures, você participará de uma ou mais de nossas equipes, participando ativamente da escolha da arquitetura, tecnologia e estratégia de implementação.
Você ganhará experiência diária em idiomas como **Node.js** e **GoLang**, além de arquitetura em nuvem (Amazon AWS) e percepção de negócios.
Você será um profissional com um papel ativo e com completa liberdade para sugerir novas abordagens (esperamos isso de você!) 😉 

## O que você irá fazer

- Planejar, desenhar e construir soluções para algumas das maiores marcas do mundo.
- Trabalhar junto com desenvolvedores, designers e analistas diariamente.
- Colaborar com todo o time não só criando aplicativos simples e eficientes, mas também dando idéias e identificando melhorias nas soluções desenvolvidas.
- Capacidade de articular conceitos técnicos e soluções para partes interessadas não-técnicas.
- Criar e evangelizar padrões de código, bibliotecas e componentes para uso interno (incluindo facilitar code review, documentar padrões e exemplos de código e ajudar novos desenvolvedores a crescerem profissionalmente).

## Requisitos

- Candidatos das áreas de Engenharia de Computação, Ciências da Computação e áreas afins.
- Demonstrar compromisso para aprendizado e melhoria continua.
- Desenvolvedores confortáveis com atitude proativa e apaixonados pelo que fazem.
- Profissionais que buscam não apenas a otimização de suas aplicações, mas também a melhoria do funil de negócios.
- Se sentir confortável em se comunicar em inglês, já que irá trabalhar com desenvolvedores de todos os lugares do mundo.

## O que mais você precisa saber

- Plano de carreira estruturado com sessões de feedback recorrentes.
- Ambiente de trabalho informal, transparente e que preza pela colaboração e respeito às pessoas de diversas origens, escolhas e culturas.
- Incentivo educação: valor semestral pra você utilizar da maneira que quiser e buscar mais conhecimentos.
- Exposição direta ao time de engenharia global da Red Ventures em Charlotte
- Incentivo à prática de atividade física: organizamos caminhadas/corridas entre os times e também temos uma parceria com o Gympass
- Red Adventure - de tempos em tempos, reunimos todo o time da RV em uma atividade fora do escritório (já teve Kart, Arco e Flecha, Escape 60)
- Liberdade para ajudar a construir uma cultura de desenvolvimento cada vez melhor.
- Convênio de saúde acima do mercado.
- Bônus financeiro anual por performance.
- Morar no Brasil (**vaga somente presencial em São Paulo**).

## Sobre a Red Ventures

A Red Ventures é a maior plataforma habilitada para tecnologia do mundo para aumentar as vendas e otimizar o ciclo de vida completo do cliente. Possuímos todo o funil de marketing direto para nossos parceiros da marca Fortune 500 - desde a geração de demanda até o fechamento da venda. Nossa experiência abrange várias indústrias, incluindo serviços domésticos, energia, serviços financeiros, seguros e software.
Nossa cultura é baseada em liberdade, você será livre para executar, testar e aprender e você terá a responsabilidade de se auto gerenciar num ambiente colaborativo e ágil. 
Você terá a oportunidade de se desafiar e crescer. Você poderia pensar no melhor dos dois mundos: trabalhar em um ambiente de start-up dinâmico no Brasil e, ao mesmo tempo, ser apoiado por uma empresa de tecnologia global líder em um ambiente de carreira disruptivo, empreendedor e acelerado.

## Como se candidatar

Candidate-se: https://grnh.se/60d30e931

## Labels

CLT
Alocado
Jr
Pleno
Senior

**Comment by LeticiaLCavalcanti** [comment]
Olá,
Você indica que eu anexe o currículo no site em inglês ou pode ser em português?

**Comment by elvisdetona** [comment]
Olá @LeticiaLCavalcanti , pode ser português ou inglês, tanto faz :D

**Comment by LeticiaLCavalcanti** [comment]
Já enviei @elvisdetona, muito obrigada!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
