### ISSUE TITLE
[Remoto] Backend Developer @ Evolux Sistemas

### ISSUE THREAD

**Issue by Mazuh** [backend-br/vagas#2872]
## Nossa empresa

Na Evolux, criamos uma suite completa para Call Centers com operações críticas e experiência de cliente. Também temos projetos de Pesquisa e Desenvolvimento, para soluções inovadoras ao mercado. E ainda há o Outsourcing de desenvolvimento para integrarmos equipes estrangeiras em suas soluções de software.

A Evolux é certificada pelo [terceiro ano consecutivo como Great Place to Work](https://www.linkedin.com/posts/evoluxbr_deu-bom-evolux-%C3%A9-certificada-gptw-pelo-terceiro-activity-6669315160668151808-6b3L), obtendo a [posição 14 no ranking nacional e 1 no estadual](http://www.tribunadonorte.com.br/noticia/empresas-recebem-certificado-great-place-to-work/454297).

## Descrição da vaga

Vagas de diversos níveis para os times de backend com Python e qualquer framework. Usamos bastante TurboGears que é semelhante a Flask e também há projetos com Django. Caso a pessoa deseje, há espaço para aprender serviços com Elixir, Lua, C e frontend com React.

## Local

Totalmente remoto, embora nossa sede seja em [Natal (RN)](https://pt.wikipedia.org/wiki/Natal_(Rio_Grande_do_Norte)).

## Requisitos

**Obrigatórios:**
- Python (2.7 ou 3.X);
- Algum framework (como Django, Flask ou TurboGears);
- Gerenciamento de bancos relacionais (MySQL, MariaDB ou PostgreSQL);
- Git (ou Mercurial);
- Familiaridade com testes;
- Leitura e escrita em inglês;
- Boa comunicação técnica com sua equipe em português.

**Desejáveis:**
- Fluência geral em inglês;
- Manutenção de ambientes GNU/Linux;
- Participação em projetos open source; 
- Metodologia Ágil;
- Agendamento de tarefas assíncronas (com RabbitMQ e Celery);
- Bancos de cache (Redis);
- WebSockets;

**Diferenciais:**
- Participação em projetos free source;
- Experiência com trabalho remoto.

## Benefícios
- Plano de saúde;
- Vales alimentação/refeição;
- Vale cultura;
- Auxílio de trabalho remoto;
- Acesso (opcional) ao escritório no fim da quarentena (com vacinação grátis, video game, geladeira livre, barril de cerveja, cafeteira, snacks, etc);

## Contratação

Apenas CLT.

## Como se candidatar

Basta inscrever seu currículo aqui:
https://evolux.freshteam.com/jobs/B2hWwBIyoFPL/desenvolvedor-a-backend-pleno-ou-senior-remoto

Se for júnior, sinta-se à vontade para se inscrever também!

No link, você também irá encontrar valores de faixa salarial e benefícios.

## Tempo médio de feedbacks

Em até 1 mês, fazemos seleção de currículos.
Uma vez que o currículo esteja selecionado, após cada etapa do processo há o feedback em até 2 dias.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by marianafmedeiros** [comment]
@Mazuh Aceita júnior também? Sei que está descrito aqui na postagem, mas no link tem apenas definições para Pleno e Sênior? Moro em Natal oh hahaha

**Comment by Mazuh** [comment]
@marianafmedeiros, oi, tá postado certo mesmo. :smile: Apesar de estarmos focados em achar pessoas pleno/sênior, caso você se identifique como júnior pode se candidatar, sim, há espaço para isso!

**Comment by Mazuh** [comment]
Foi feita uma contratação (de pessoa júnior), mas a vaga continua aberta para mais. A preferência ainda maior para não-júniors agora, porque já fizemos isso nesse mesmo processo, mas a vaga continua aberta a todos os níveis.

**Comment by Trunkol** [comment]
A vaga ainda está aberta?

**Comment by Mazuh** [comment]
Yep.
