### ISSUE TITLE
[LISBOA] Back-end Developer @vinhosdeluxo

### ISSUE THREAD

**Issue by michelmelo** [backend-br/vagas#2884]
## Nossa empresa

Somos uma empresa voltada para a vendas de vinhos, e enoturismo em portugal.

## Descrição da vaga

Estamos buscando um desenvolvedor full-stack apaixonado por desafios exponenciais.

## Local

Exemplo: Remoto , Lisboa - Portugal

## Requisitos

**Obrigatórios:**
- Experiência de pelo menos 3 anos com desenvolvimento de backend, com PHP
- Ter desenvolvido e ter conhecimento como funciona uma API REST
- Vivência com bancos de dados relacionais preferencialmente Mysql
- Desenvolver código limpo, de fácil compreensão e manutenção;
- Interesse por novas tecnologias e padrões de arquitetura "fora da caixa";
- Capacidade de trabalho com uma equipe multidisciplinar;
- Ter capacidade de compreender como seu trabalho afeta a empresa como um todo, muito além do código;
- Ter conhecimento em linux.

**Desejáveis:**
- Conhecimentos em bancos de dados não relacionais como Mongodb e Redis
- Conhecimento em DevOps (Kubernetes e Docker)
- React.Js ou Vue.Js
- Laravel

## Como se candidatar

Por favor envie um email para wine@vinhosdeluxo.com com seu CV anexado - enviar no assunto: Back-end VinhosDeLuxo

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Vagmacker** [comment]
email wine@vinhosdeluxo.pt não encontrado.

**Comment by michelmelo** [comment]
@Vagmacker wine@vinhosdeluxo.com já corrigi no post.
