### ISSUE TITLE
[Salvador, BA] Analista Desenvolvedor Backend na @ConvergenceWorks

### ISSUE THREAD

**Issue by diegocoxta** [backend-br/vagas#29]
Você gosta de programação e de desenvolvimento de software?  Gosta de novas tecnologias e de desafios? Tem espírito de equipe e é comprometido? Você gostaria de colocar tudo isto em prática numa empresa?

**A Convergence Works** 
Somos a Convergence Works, somos a convergência entre os desafios das empresas e as ideias pra vencê-los. Desenvolvemos plataformas para o mundo digital, com foco em comunicação. Somos especialistas na criação de sites e aplicativos para plataformas de comunicação. Integramos sistema de gestão de conteúdo, aplicativo, disparo de email, solução para clube de assinantes, implantação de editoriais em múltiplas plataformas.
 
**Local**
Rua Rubens Guelli, 134 - Sala 309 - Itaigara, Salvador – BA

**Conhecimentos necessários:**
- PHP
- Javascript
- HTML
- SQL 
- Linux
- GIT
- MVC e outros padrões de projeto

**Desejáveis:**
Conhecimento em React

**Benefícios**
- Vale transporte
- Vale refeição
- Plano de Saúde
- Excelente ambiente de trabalho 
- Oportunidades de crescimento 
 
**Contratação**
CLT

**Essa vaga é pra você ? Venha fazer parte do nosso time!!!**
Envie seu currículo para vagas@convergenceworks.com.br com seu CV anexado e pretensão salarial,  enviar no assunto: Vaga Analista Desenvolvedor Backend

**Comment by marcosalberto** [comment]
@diegocosta a vaga já foi preenchida.
