### ISSUE TITLE
[Curitiba] Back-End Ruby on Rails Pleno [EADBOX]

### ISSUE THREAD

**Issue by RafaeleEADBOX** [backend-br/vagas#290]
**Sobre** a EADBOX:

 EADBOX é uma startup que cresceu 130% no último ano, e que está revolucionando o mercado da educação e treinamentos corporativos por meio de um software utilizado para criação e distribuição de cursos online. 

A empresa cresce rápido, milhares de novos alunos todos os meses, com mais de 800 clientes entre autores e grandes empresas como Ache, Totvs, Renault, WiseUp, Heineken. Num forte processo de crescimento no Brasil, México, Argentina e Colômbia.

Começamos 2018 com 108 pessoas e queremos acabar o ano com mais de 267 pessoas entusiasmadas e comprometidas com um propósito: ser uma grande empresa e transformar a eduacação global.

**Sobre a vaga:**

Procuramos um desenvolverdor Ruby on Rails Pleno;
Para atuar no regime CLT;
Em Curitiba ou remoto

**Requisitos:**
Ruby on Rails
MongoDB
Desenvolvimento com Testes
EleasticSearch
Redis
Docker

**Desejável:**
devOps (AWS, Google Cloud)
Linguagem funcional (Elixir e afins)
Microservices

**Benefícios e diferenciais:**
Vale Transporte
Vale Refeição
Plano de Saúde
Quitutes diários (não muito saudáveis) para combinar com café expresso (à vontade e do bom)
Ambiente dinâmico e inovador
Equipe comprometida e empolgada

Interessados podem se candidatar no [https://hipsters.jobs/job-preview/5197/] e dúvidas enviar para: rafaele.bastian@eadbox.com

**Comment by marceloperini** [comment]
O link ([https://hipsters.jobs/job-preview/5197/](https://hipsters.jobs/job-preview/5197/)) não existe. Posso mandar o currículo por e-mail?

**Comment by marceloperini** [comment]
Acredito que seja esse [link](https://hipsters.jobs/job/5105/desenvolvedor-ruby-on-rails-back-end-pleno/)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
