### ISSUE TITLE
[Alphaville, Barueri] Java Developer - E-volve

### ISSUE THREAD

**Issue by nathaliagoldenberg** [backend-br/vagas#292]
Buscamos os MELHORES profissionais do mercado de Tecnologia para fazer parte da empresa REFERÊNCIA em meios de pagamento, em Barueri.

Qual o desafio? Participar da construção do futuro da experiência de compra!

## Local

Escritório, Alphaville, Barueri/SP

#### Diferenciais

- Ambiente FUN
- Modelo Squads,Tribos, Chapters
- Tecnologias de ponta

## Requisitos

- Conhecimento sólido em desenvolvimento Java;
- Conhecimento sólido de SQL;
- Programação orientada a objetos;

## Contratação

CLT

## Como se candidatar

Por favor envie um email para contato@e-volve.in com seu CV anexado ou link do Linkedin - enviar no assunto: Fullstack Java 

## Labels

- CLT
- Júnior
- Pleno
- Sênior
- JAVA
- SQL
- OO

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
