### ISSUE TITLE
[Belo Horizonte] Back-end Developer - PHP @ Sympla

### ISSUE THREAD

**Issue by rh-sympla** [backend-br/vagas#2927]
## Quem somos?

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA.
Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time de Produto e Desenvolvimento e para isso buscamos pessoas incríveis!
Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

## Seus desafios serão:

- Contribuir com as decisões de arquitetura da nossa aplicação, buscando uma arquitetura flexível e moderna que acompanhe o crescimento constante;
- Ajudar a manter um “espírito” ágil;
- Ter orgulho de colocar em produção um código que é usado por milhões de pessoas Brasil afora. 
- Monitorar o desempenho dos serviços que compõem o ecossistema da Sympla, para identificar gargalos de desempenho e problemas de performance em geral, assegurando a continuidade das operações e a melhor experiência para o usuário.

## Oferecemos:

*Neste momento estamos atuando no Regime Home Office, por isso os benefícios que dizem respeito a estrutura física serão desfrutados quando retornamos ao nosso super escritório, mas considere:

- Ambiente criativo, inovador e estimulante;
- No dress code (Venha como se sentir melhor, fechou?);
- GymPass é um benefício corporativo de atividade física, nele você tem acesso a diversas modalidades de atividades em várias academias;
- Plano de Saúde Sulamérica com cobertura Nacional na modalidade apartamento;
- Plano Odontológico;
- O momento da cegonha chegou? Nossas licenças são estendidas! Maternidade 6 meses e paternidade 20 dias;
- Auxílio creche para crianças de até 4 anos e 12 meses para mamães e papais;
- Acesso gratuito ao MyAcademy, plataforma de e-learning com acesso a + 40.000 cursos dos mais variados temas e parceiros;
- Café expresso, bebidas variadas, frutas e snacks a qualquer hora do dia;
- Happy Hour que acontece uma vez ao mês em comemoração aos aniversariantes;
- 40h semanais(segunda à sexta, com escala em alguns finais de semanas e feriados).
- Folga de um dia no mês do aniversário, que é a nossa maneira de presentear o funcionário;

 ## Alguns diferenciais para a função:
Alguns diferenciais para a função:

- Conhecimento em sistemas distribuídos;
- Conhecimento em banco de dados relacional;
- Experiência em desenvolvimento de APIs Restful.
- Vivência em aplicações que recebam quantidade massiva de acessos simultâneos; 

Valorizamos trabalhar em um ambiente de pluralidade e de inclusão, por isso todas nossas vagas também são para profissionais com deficiência, mães solos, pessoas LGBTQIA+, negros (as), indígenas e outras pessoas de grupos vulnerabilizados.

Por isso, se você tem paixão por atender pessoas e se identificou com tudo que contamos acima, essa vaga pode ser sua :)

Faça sua inscrição no link: https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=4828641002

Vaga para atuar em Belo Horizonte.

**Comment by lailson-dev** [comment]
Qual o nível de conhecimento para a vaga?
