### ISSUE TITLE
[Remoto] Back-end Developer @CyberGamer (até R$8.000,00)

### ISSUE THREAD

**Issue by wchagas** [backend-br/vagas#2933]
## Atividades e Responsabilidades

- Realizar mentoria e/ou orientação de equipes para garantia da qualidade;
- Garantir a qualidade do código;
- Apoiar na definição das atividades (Planning);
- Setup de ambientes;
- Corrigir erros e defeitos.

## Requisitos

- Domínio em NodeJS e TypeScript;
- Banco de dados SQL/NoSQL;
- Microservices;
- Docker e Kubernetes;
- AWS;
- Mensageria (RabbitMQ);
- Experiência em design de API's RESTful;
- Boas práticas de reusabilidade e desenvolvimento orientado a componentização/modularização;
- Experiência com o processo de integração contínua (CI/CD);
- Padrões de projeto / design para back-end;
- Conhecimento comprovado na área (Github);
- Versionamento de código utilizando GIT;
- Métodos Ágeis;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para willy@cybergamer.com.br com seu CV anexado - enviar no assunto: Vaga Back-end sênior

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

## Atividades e Responsabilidades

- Desenvolvimento de API's;
- Aplicar testes automatizados;
- Compartilhar conhecimento com os membros da equipe;
- Apoiar na definição das atividades (Planning);

## Requisitos

- Conhecimentos em NodeJS, Express e TypeScript;
- Banco de dados SQL/NoSQL;
- Experiência em desenvolvimento de API's RESTful;
- Boas práticas de reusabilidade e desenvolvimento orientado a componentização/modularização;
- Experiência com o processo de integração contínua (CI/CD);
- Conhecimento comprovado na área (Github);
- Versionamento de código utilizando GIT;
- Métodos Ágeis;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para willy@cybergamer.com.br com seu CV anexado - enviar no assunto: Vaga Back-end Pleno

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

#### Salário
- R$ 8.000

**Comment by thiagoluiznunes** [comment]
Aceitar Part-time? Se sim, thiagoluiz.dev@gmail.com

**Comment by guibranco** [comment]
Aceita part-time ?

**Comment by wchagas** [comment]
E ai galera, nesse momento estamos precisando full-time.
