### ISSUE TITLE
[Remoto] Back-end Developer @CyberGamer (até R$6.000,00)

### ISSUE THREAD

**Issue by wchagas** [backend-br/vagas#2934]
## Atividades e Responsabilidades

- Desenvolvimento de API's;
- Aplicar testes automatizados;
- Compartilhar conhecimento com os membros da equipe;
- Apoiar na definição das atividades (Planning);

## Requisitos

- Conhecimentos em NodeJS, Express e TypeScript;
- Banco de dados SQL/NoSQL;
- Experiência em desenvolvimento de API's RESTful;
- Boas práticas de reusabilidade e desenvolvimento orientado a componentização/modularização;
- Experiência com o processo de integração contínua (CI/CD);
- Conhecimento comprovado na área (Github);
- Versionamento de código utilizando GIT;
- Métodos Ágeis;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para willy@cybergamer.com.br com seu CV anexado - enviar no assunto: Vaga Back-end Pleno

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

#### Salário
- R$ 6.000

**Comment by thiagoluiznunes** [comment]
Aceita Part-time?

**Comment by wchagas** [comment]
Nesse momento estamos precisando full-time.
