### ISSUE TITLE
Programador PHP Back End Pleno - Ribeirão Preto/SP

### ISSUE THREAD

**Issue by JessicaBarrosNerus** [backend-br/vagas#2943]
Sobre a empresa:
⠀
A Venda.la é uma Startup que está revolucionando o varejo on-line e off-line. Desenvolvemos soluções que conectam vendedores aos principais marketplaces, possibilitando uma gestão centralizada. Estamos em constante evolução e temos a mente aberta para novidades.
⠀
Nosso maior diferencial é a automação de processos. Com isso, nossos parceiros gerenciam melhor e vendem mais.
⠀
Atualmente estamos expandindo nossa equipe e estamos à procura de um Programar PHP Back-end Pleno.
⠀
O que vai fazer:
⠀
Desenvolvimento e manutenção de sistemas;
Criação e manutenção de APIs;
Documentação de toda a codificação;
Ajudará encontrar soluções para problemas;
Trabalhar em equipes multidisciplinares em um ambiente scrum.
⠀
O que esperamos de você:
⠀
Goste de estudar e aprender;
Consiga transpor objeções;
Seja organizado;
Se sinta desafiado com metas;
Goste de trabalhar em equipe;
Uma pessoa flexível e aberta à novidades.
⠀
O que precisa ter:
⠀
Conhecimento avançado em PHP 7+ e Laravel;
Conhecimento em Banco de dados MySQL;
Conhecimento em GIT;
Conhecimento em construção de API.
⠀
⠀
Desejável:
⠀
Experiência com API (Mercado Livre, B2W, Amazon, etc);
Conhecimento em NodeJS;
Conhecimento em desenvolvimento de sistemas em uma arquitetura de Micro Serviços;
Conhecimentos básicos da AWS;
Conhecimento em Docker.
⠀
Benefícios:
⠀
Salário compatível com o mercado;
Vale transporte;
Vale alimentação;
Premiação por desempenho;
Plano de Participação dos Resultados;
Trabalhar com os melhores computadores da Apple; Ambiente jovem, descontraído, escritório confortável;
⠀
Encaminhe o seu CV para o e-mail rh@nerus.com.br com o assunto "VAGA PROGRAMADOR BACK END"

**Comment by diegosimax** [comment]
Aceita candidatos no modelo remoto?

**Comment by JessicaBarrosNerus** [comment]
Olá Diego, tudo bem?

Estamos avaliando essa possibilidade.
Se tiver interesse me envie o seu curriculo e/ou linkedin atualizado,
por favor!



[image: Foto de JÉSSICA BARROS]

JÉSSICA BARROS

Analista | Recursos Humanos

31 99773-670431 3273-4415

Viva o Omnichannel!
[image: logo nerus] <http://www.nerus.com.br/>

www.nerus.com.br





Em qui., 27 de ago. de 2020 às 11:45, Diego Simas <notifications@github.com>
escreveu:

**Comment by diegosimax** [comment]
Segue meu LinkedIn Jéssica -> https://www.linkedin.com/in/diegosimax/
