### ISSUE TITLE
[Porto Alegre/RS] .NET Back-End Developer PL na A&M Yours RH

### ISSUE THREAD

**Issue by AeMLeticia** [backend-br/vagas#295]
Desenvolvedora de Soluções e Prestação de Serviços de Hardware e Software para clientes da esfera Pública e Privada.
Possuem produtos desde câmeras de identificação veicular em rodovias com software LPR próprio, Sistema de Gestão de Frotas e Logística 

Conhecer C# e .Net profundamente; 
Conhecer Bancos de Dados (SQL Server);
Conhecer Desenvolvimento Web Backend e Frontend;
Ter experiência com desenvolvimento de Sistemas Distribuídos;
Conhecer Javascript, CSS e HTML; 
Desejável conhecimento de Frameworks de Javascript como JQuery, Angular;
Ter sólidos conhecimentos em Orientação a Objeto;
Ter conhecimento em HTTP e protocolos relacionados como REST e SOAP.

Remuneração: 
R$4.000 à R$5.000

Benefícios padrão da empresa:
Benefícios 
- VT
- VR ou VA (R$ 380,00)
- Plano de saúde/dentário UNIMED para o funcionário e dependentes com participação.

Bairro Menino Deus - Porto Alegre/RS

Envie seu currículo para rh@aemyoursrh.com.br

**Comment by guilhermeoa07** [comment]
Qual a senioridade?

**Comment by AeMLeticia** [comment]
guilhermeoa07 - é de JR a PL

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
