### ISSUE TITLE
[Belo Horizonte-MG / Remoto] Back-end C# .NET Developer Jr @ Onegreen

### ISSUE THREAD

**Issue by gabrielhws** [backend-br/vagas#2953]
## Onegreen

O Onegreen é um software especializado para a gestão de todo o Processo de Licenciamento Ambiental.

O desenvolvimento do Onegreen iniciou em 2009 com a ajuda de grandes mineradoras, e desde então vem sendo atualizado com novas funcionalidades e já é utilizado por empresas dos mais diversos segmentos e portes.

Fácil e prático de usar, você pode acessá-lo em qualquer lugar com seu navegador favorito.

Com uma interface simples e versátil você não perderá o prazo de nenhuma condicionante e conseguirá manter todas as tarefas relativas as suas licenças em dia.

## Descrição da vaga

A OneGreen está buscando Pessoa desenvolvedora Fullstack com conhecimento em C# e .Net, para atuar na área de desenvolvimento de software WEB, utilizando metodologia ágil (Scrum).

Se você tem esses conhecimentos, capacidade de raciocínio lógico, criatividade, e sabe trabalhar com independência para criar em conjunto com a equipe de desenvolvimento e planejamento, então seu lugar é aqui!

## Local

- Remoto
- Belo Horizonte-MG

## Habilidades
- C#
- Javascript
- SQL Server
- MVC .NET
- Git

## Requisitos

- Necessário experiência com .NET, C# e .NET Core
- Capacidade criativa e independência para atuar em equipe
- Ser habituado com metodologias ágeis (Scrum)
- Capacidade de raciocínio lógico e criatividade
- Conhecimentos em front-end com vue.js é diferencial
- Habituado com Design Patterns
- Conhecimentos em HTML / CSS e Jquery

**Diferenciais:**

- Conhecimentos em CoffeeScript ou Typescript
- Conhecimentos em Bootstrap
- Noções de testes unitários para .NET
- Experiência com Mercurial (controle de versão)
- Inglês intermediário

## Benefícios

- Vale Alimentação ou Refeição
- PLR

## Contratação

CLT

## Como se candidatar

Candidatar-se em: [https://bit.ly/3hB5dLo](https://bit.ly/3hB5dLo)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.
E-mail para contato em caso de não haver resposta: contato@coodesh.com

#### Alocação

- Alocado
- Remoto

#### Regime

- CLT

#### Nível

- Júnior

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by moisesbueno** [comment]
O link para cadastro da vaga está com problema retornando Error 525
