### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor Mobile Híbrido (Cordova e iOnic) [A&M Yours RH]

### ISSUE THREAD

**Issue by AeMLeticia** [backend-br/vagas#296]
Empresa atua há 30 anos no mercado Brasileiro e Internacional. Oferecem soluções de negócios verticalizadas e serviços de tecnologia personalizados. 
**Especialistas em soluções de Vendas, Compras, Computação em Nuvem e Tecnologia. Possuem grande experiência no desenvolvimento de Soluções de Inteligência em projetos de KPI’s e Analytics.** 

Conhecimento mínimo
•	Cordova;
•	iOnic;
•	, Angular JS;
•	API REST;
•	Firebase;
•	Scrum;
•	Git;
•	HTML, CSS, JavaScript, jQuery, HTML5, bootstrap;
•	.Net framework 4.0 - Web Forms e MVC, C#, ASP.NET;
•	Desenvolvimento de Wireframes;
•	Criação de fluxo de trabalho;
•	Experiência na utilização de jQuery, modelo ClientObject e Arquitetura Orientada a Serviços;

Conhecimento desejável
•	Habilidade para escrever consultas SQL e T-SQL complexas, Stored Procedures, triggers e consultas SQL complexas;
•	ASP Clássico;
•	Programação para nuvem (AWS, Azure e Google);
•	Ferramenta de tratamento de Imagens (Photoshop e/ou Fireworks).
•	Habilidades de comunicação escrita e oral, e ser capaz de ler e escrever em Inglês;

Experiência
•	Mínimo de 2 anos na função

Salário
R$ 3.500,00 a R$4.000,00 CLT

benefícios: VT, VR ou VA de R$ 480,00 e plano de saúde Unimed **sem** desconto
Porto Alegre/RS - Higienópolis

**Envie seu currículo para rh@aemyoursrh.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
