### ISSUE TITLE
[São Paulo] Back-end Developer Pleno (Ruby e Elixir) @ Petlove

### ISSUE THREAD

**Issue by brubsland** [backend-br/vagas#2975]
> Vaga Remota durante a pandemia

## Nossa empresa

A Petlove é o maior petshop online e clube de assinaturas para pets do Brasil. Nascemos em 1999 a partir do sonho visionário de um médico veterinário que foi pioneiro em apostar na venda online de produtos pets em uma época em que a internet no país ainda era uma incerteza. Somos investidos pelos melhores fundos de venture capital do Brasil e estamos em ritmo de crescimento acelerado para continuarmos cumprindo nossa principal missão: ajudar pais e mães de pets a fazerem seus filhos peludos mais felizes e saudáveis. 

## Descrição da vaga

Aqui na Petlove, nós desenvolvemos e continuamos expandindo uma plataforma tecnológica própria. A stack é baseada em aplicações e micro serviços que utilizam tecnologias como Ruby on Rails, NodeJS e Elixir, Bancos de Dados MySql, Postgres e Elastic Search. Somos 100% Cloud e nossa infra é baseada em containers Docker e Kubernetes.

O time de tecnologia, que atualmente está em fase de crescimento acelerado, é formado por mais de 30 profissionais entre desenvolvedores Front-End, Back-End, Mobile, Fullstack, Devops e de Infraestrutura. Os petlovers do time de tecnologia estão alocados em squads diversos, o que permite maior foco e qualidade nas entregas, além da autonomia e liberdade de trabalho presentes em todas as áreas da empresa.

Curiosidades sobre o time: os desenvolvedores da Petlove são amantes de café e ping pong assumidos!

## Local

Remoto durante a pandemia. Após normalização, escritório Berrini/SP.

## Requisitos

Vivência nas seguintes tecnologias:

- VueJS ou React
- GIT
- Javascript (Vanilla)
- Gulp ou Webpack
- HTML 5
- CSS 3
- Sass/Less
- NodeJS
- APIs/REST
- Testes automatizados
- SEO

## Benefícios

- Assistência médica e odontológica 100% custeada pela empresa;
- Vale Refeição (podendo dividir com Vale Alimentação);
- Crédito para Snacks;
- Bicicletário no prédio;
- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim;
- Day-off de aniversário;
- Ambiente descontraído e dinâmico;
- Parcerias com descontos;
- Desconto em produtos no site;
- PLR - Atrelado a metas;
- Gympass;
- E claro, Pet Friendly, pets são muito bem vindos no escritório!!

## Contratação

CLT Efetivo 

## Como se candidatar

Os interessados devem se candidatar através do link: https://petlove.gupy.io/jobs/468021

#### Regime
- CLT

#### Nível
- Pleno

**Comment by Wilker** [comment]
O título fala em Ruby mas a descrição é pra front. O link leva a uma vaga para Rails, que parece correto.
