### ISSUE TITLE
[Palhoça] Senior Node.js Engineer

### ISSUE THREAD

**Issue by cazlu8** [backend-br/vagas#2991]
Vaga Nodejs Senior.
Pode ser remoto durante um periodo, se morar próximo a região, seria requisitado mudança para palhoça.
Salário em USD, acima da média BR.
Startup Americana na área de entretenimento e eventos.
Stack para vaga:
- Typescript
- AWS (Elastic BeanStalk EC2, SES, RDS etc)
- NestJS
- TypeORM
- Postgres
mais informações mandar um email : lucas@artio.events

**Comment by cazlu8** [comment]
vaga ainda aberta.

**Comment by btd1337** [comment]
![Captura de tela de 2020-12-09 02-44-42](https://user-images.githubusercontent.com/11943860/101590089-87d41e00-39c8-11eb-913b-4838e33c741e.png)
