### ISSUE TITLE
[REMOTO] Software Engineer Sênior ou Especialista na Movile Pay 

### ISSUE THREAD

**Issue by Luiza0412** [backend-br/vagas#2999]
## Nossa empresa

A Movile Pay está revolucionando o mercado de pagamentos online e você pode entrar nesse movimento!

Somos uma fintech do grupo Movile com o objetivo de trazer ao meio financeiro soluções descomplicadas, inovadoras, democráticas e surpreendentes, e nosso sonho é sermos a maior wallet do Brasil.

Em plena pandemia pudemos ter maior noção de quão importante é o nosso papel, e por isso nesse estamos focados em expandir o nosso time de tecnologia para atender a todas as nossas unidades espalhadas pelo país.

Topa esse desafio? 
https://byintera.in/10o

## Descrição da vaga

Trabalhamos principalmente com Java e Kotlin e muito focados em AWS, e buscamos pessoas com espírito empreendedor e dispostas a crescer exponencialmente com a Movile Pay. Serão bem-vindos conhecimentos avançados em Kafka.

## Local

Remoto

## Contratação

CLT

## Como se candidatar

https://byintera.in/10o

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by jonatanmurga** [comment]
FirebaseCustomRemoteModel remoteModel =
      new FirebaseCustomRemoteModel.Builder("your_model").build();
FirebaseModelDownloadConditions conditions = new FirebaseModelDownloadConditions.Builder()
        .requireWifi()
        .build();
FirebaseModelManager.getInstance().download(remoteModel, conditions)
        .addOnSuccessListener(new OnSuccessListener<Void>() {
            @Override
            public void onSuccess(Void v) {
              // Download complete. Depending on your app, you could enable
              // the ML feature, or switch from the local model to the remote
              // model, etc.
            }
        });
