### ISSUE TITLE
[São Paulo, SP] Analista de sistemas sênior ou especialista na Bionexo 

### ISSUE THREAD

**Issue by gabriellett** [backend-br/vagas#30]
## Sobre a Bionexo

A Bionexo é uma empresa de tecnologia que oferece soluções digitais para compras, vendas e gestão de processos na Saúde. A comunidade Bionexo conta com mais de 1.300 instituições de saúde (entre hospitais, operadoras, clínicas e Home Cares) bem como 10.000 fornecedores, gerando mais de R$ 7 bilhões de transações através de seu marketplace. Seus produtos digitais trazem eficiência e transparência a quase 50% dos leitos do país.

Fundada em 2000, é a maior referência na construção de soluções digitais em nuvem para saúde, contribuindo decisivamente para a profissionalização da cadeia de suprimentos no setor no Brasil e outros países nos quais atua: Argentina, Colômbia, México e Espanha.

Para saber um pouco mais sobre a tecnologia da Bionexo, pode acessar o nosso medium: https://medium.com/bionexo

## Sobre a vaga

O desafio da Tecnologia é desenvolver plataformas com o uso de ferramentas de ponta para que a Bionexo continue sendo conhecida pela sua capacidade de inovar a área de Saúde e, para isso, estamos sempre em busca de pessoas que queiram fazer a diferença.

Nossa stack inclui principalmente Ruby on Rails e Java, além de Javascript, React, Elixir, Python, Scala, Golang, PostgreSQL, Oracle, ElasticSearch, Docker e AWS.

## Principais responsabilidades do cargo:

- Desenvolver novas funcionalidades e atuar na resolução de bugs das aplicações da Bionexo.
- Trabalhar em colaboração com outros times.
- Trazer boas práticas e conhecimentos técnicos para o dia a dia de trabalho.
- Compreender as necessidades dos usuários para ajudar a melhorar a eficiência dos fluxos de trabalho.

## Cadastre-se nesta oportunidade se você:

- Identifica-se com os nossos valores.
- Possui experiência em papéis que incluem desenvolvimento backend e frontend.
- Já trabalhou no desenvolvimento de aplicações web.
- Possui experiência com algum banco de dados relacional, testes automatizados (unitários, de interface e integração) e é habituado em trabalhar com pull requests.
- Tem noções de segurança para desenvolver código seguro.
- Conhece metodologias Ágeis.
- Possui experiência em Ruby on Rails ou Java.

## Será um diferencial se você:

- Conhecer Javascript, HTML e CSS, e tenha conhecimento com Twitter Bootstrap.
- Ter trabalhado com ElasticSearch ou similares.
- Desenvolver utilizando processos assíncronos.

## Beneficios

- Salário competitivo
- Vale refeição
- Vale transporte
- Plano de saúde
- Seguro de vida
- Auxilio creche
- PPR

## Como se candidatar

Para se candidatar, basta enviar seu currículo e GitHub para Renato Guimarães rguimaraes@bionexo.com com o titulo `[Vaga Dev] <seu nome>`

## Links:

* http://beta.bionexo.com/br/
* https://medium.com/bionexo
* https://www.linkedin.com/company/88588/life/
* https://github.com/Bionexo

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?

**Comment by gabriellett** [comment]
@reginaldojunior a vaga ainda está aberta! Pode reabrir?

**Comment by reginaldojunior** [comment]
@gabriellett claro!

**Comment by reginaldojunior** [comment]
A vaga foi preenchida?

**Comment by gabriellett** [comment]
@reginaldojunior Foi sim, vou fechar!
