### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor DotNet Fullstack [RHTEC]

### ISSUE THREAD

**Issue by wmoreira** [backend-br/vagas#300]
PRINCIPAIS ATIVIDADES

    Entender o problema e implementar soluções para atender o negócio.
    Realizar codificação.
    Implementar e realizar testes de software.
    Prestar orientações técnicas relacionadas à sua área de atuação.
    Contribuir para as decisões de design e arquitetura.
    Garantir o cumprimento dos prazos e requisitos técnicos.

CONHECIMENTOS OBRIGATÓRIOS

    NET(C#), javascript, angularjs e webapi. Experiência em métodos ágeis.

FORMAÇÃO:

Mínimo: Ensino superior completo.

BENEFÍCIOS

    PPR
    Plano de saúde Bradesco
    Plano Odontológico Bradesco
    Vale refeição/alimentação
    Vale transporte
    EXCELENTE AMBIENTE DE TRABALHO!

LOCAL DE TRABALHO:

Bairro do Botafogo - Rio de Janeiro

FAÇA PARTE DA NOSSA EQUIPE!

Envie seu currículo para talentos@rhtec.com.br com o campo assunto: "CV para DotNet no RJ".

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
