### ISSUE TITLE
[Belo Horizonte - MG] Back-end Developer PHP @123Milhas

### ISSUE THREAD

**Issue by matheus-ac** [backend-br/vagas#3002]
> Vaga Remota durante a pandemia

## Nossa empresa

123 Milhas, Passagens aéreas com milhas

## Descrição da vaga

Procuramos um profissional capaz de trabalhar com diversos tipos de tecnologias e com experiência em aplicações web de alta performance e escaláveis para propor e discutir soluções para os desafios do nosso negócio.

## Local

Remota durante a pandemia/ Escritório, Belo Horizonte - Funcionários 

## Requisitos

**Obrigatórios:**
- Experiência em PHP e Laravel;
- Banco de dados MySQL;
- Controle de versão Git;
- Familiaridade com as PSRs
- Conhecimentos sólido no paradigma OO;

**Desejáveis:**
- Experiência na criação de soluções escaláveis / serviços com grande concorrência;
- Serviçõs AWS;
- NodeJs;
- Ambientes virtualizados (docker);
- Mensageiria / Sistemas de filas;
- Conhecimentos em design e arquitetura de software;
- Conhecimento das boas práticas da engenharia de software, ferramentas e processos;

## Benefícios

- Convênio saúde UNIMED;
- Cursos tecnológicos;
- Pagamento da prova para certificações relacionadas à área, sendo 90% reembolsado mediante aprovação;
- Pagamento de inscrições de eventos de TI, como: conferência DevOps Day, Front In, Minas Testing Conference(MTC), entre outros;
- Refeição R$ 22,00 ao dia;
- Incentivo de R$ 200 mensal (pode ser utilizado em educação)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagas@123milhas.com.br com seu CV anexado - enviar no assunto: Back-end Developer PHP

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by acgfbr** [comment]
Benefícios: 
Horas extras remuneradas;

ta de sacanagem né meu patrão? isto é algo B Á S I C O.

**Comment by matheus-ac** [comment]
> Benefícios:
> Horas extras remuneradas;
> 
> ta de sacanagem né meu patrão? isto é algo B Á S I C O.

Hahaha não sou patrão, estou apenas ajudando na divulgação da vaga.
Obrigado pelo seu feedback, Sucesso.
