### ISSUE TITLE
[São Paulo]Back-end Developer @Fliper

### ISSUE THREAD

**Issue by Aa-app** [backend-br/vagas#3006]
## Nossa empresa

Olá, somos a Fliper! Nascemos para transformar a relação das pessoas com suas finanças, oferecendo transparência e conectividade para que elas possam tomar decisões financeiras inteligentes e realizar seus sonhos.
Somos apaixonados por tecnologia, inovação e empreendedorismo. Movidos a grandes desafios, desenvolvemos uma plataforma para facilitar o controle financeiro e otimizar o tempo das pessoas. De forma totalmente automática, é possível consolidar todos os seus investimentos de Bancos e Corretoras em um único lugar!
A Fliper faz parte do Grupo XP Inc., uma das maiores instituições financeiras do Brasil.

## Descrição da vaga

Procuramos back-end com experiência em linguagens de programação de servidores, apaixonado por buscar soluções de quebra-cabeças lógicos e que esteja afim de desenvolver algo inovador com um real propósito de impactar a vida das pessoas. Junte-se a um time muito engajado e que está sempre buscando aprender!

## Requisitos

**Desejáveis:**

Conhecimento em Node.js
Conhecimento em microsserviços e gerenciamento de mensagens por fila (rabbitmq)
Conhecimento em banco de dados não-relacional (mongoDb)
Experiência/conhecimento com APIs (REST) e/ou ferramentas de web-crawling (puppeteer)
Conhecimento em Git (GitHub)

**Diferenciais:** 
Experiência/conhecimento em processos ágeis (scrum)
Experiência em ferramenta de computação na nuvem (GCP - Google Cloud Platform) e processos de integração contínua/deploy contínuo (CI/CD)
Conhecimento e/ou experiência em criptografia de dados, engenharia reversa, segurança e protocolos de rede (esse é descartável mas se tiver é um baita bônus)
Algum conhecimento em outra linguagem além de javascript, preferência por Go ou alguma orientada à objeto, como Java

## Benefícios

- Plano de saúde
- Vale Alimentação
- Vale Refeição
- Home Office 

#### Regime

- CLT ( Salário compatível com o mercado). 

#### Nível

- Pleno
- Sênior

## Local

Vaga Remota durante a pandemia. Escritório, São Paulo - Vila Olímpia. 

## Como se candidatar

Por favor envie um e-mail com pretensão salarial para aline.arruda@fliper.app com seu CV anexado e github.
Enviar no assunto: Vaga back-end (Pleno|Sênior)

**Comment by brunooomelo** [comment]
Enviado
