### ISSUE TITLE
[São Paulo] Back-end Developer @ Fliper

### ISSUE THREAD

**Issue by Aa-app** [backend-br/vagas#3008]
## Nossa empresa

Olá, somos a Fliper! Nascemos para transformar a relação das pessoas com suas finanças, oferecendo transparência e conectividade para que elas possam tomar decisões financeiras inteligentes e realizar seus sonhos.
Somos apaixonados por tecnologia, inovação e empreendedorismo. Movidos a grandes desafios, desenvolvemos uma plataforma para facilitar o controle financeiro e otimizar o tempo das pessoas. De forma totalmente automática, é possível consolidar todos os seus investimentos de Bancos e Corretoras em um único lugar!
A Fliper faz parte do Grupo XP Inc., uma das maiores instituições financeiras do Brasil.

## Descrição da vaga

Procuramos back-end com experiência em linguagens de programação de servidores, apaixonado por buscar soluções de quebra-cabeças lógicos e que esteja afim de desenvolver algo inovador com um real propósito de impactar a vida das pessoas. Junte-se a um time muito engajado e que está sempre buscando aprender sobre coisas novas.

## Local

Vaga Remota durante a pandemia. Escritório em São Paulo - Vila Olímpia.

## Requisitos

**Obrigatórios:**

Sólidos conhecimentos em mais de uma linguagem de programação
Arquitetura de microsserviços
Conhecimento de algum sistema de mensageria
Conhecimentos de Banco de dados
Conhecimentos de Git
Testes unitários e de integração

**Desejáveis:**
Ter trabalhado com metodologias ágeis
Golang
Kubernetes
Google Cloud
GraphQL
RabbitMQ
MongoDB

## Benefícios

- Plano de saúde
- Vale Alimentação
- Vale Refeição
- Home Office

## Como se candidatar

Por favor envie um email com pretensão salarial para aline.arruda@fliper.app com seu CV anexado e github.
Enviar no assunto: Vaga back-end (Pleno|Sênior).

#### Regime

CLT ( Salário compatível com o mercado).

#### Nível
- Sênior
- Pleno

**Comment by brunooomelo** [comment]
Enviado!

**Comment by Aa-app** [comment]
Aberta!



Em seg., 9 de nov. de 2020 às 21:24, github-actions[bot] <
notifications@github.com> escreveu:
