### ISSUE TITLE
[Home Office] NodeJS Back-end Developer @ INTERCASE

### ISSUE THREAD

**Issue by cesarcardoso-intercase** [backend-br/vagas#3017]
## Nossa empresa

Somos a Intercase, uma empresa com +10 anos no mercado de soluções em e-commerce, tendo cases em seu portfólio de grandes clientes como Walmart, Wine, Osklen, Natura, Vix Brasil, Ortobom, Dufry Shopping, entre outros.

## Descrição da vaga

Procuramos desenvolvedores especialistas no framework React.js (Javascript) para trabalhar nos Squads Remotos da INTERCASE. 

Precisamos montar dois Squads, com 1 Front-end ReactJS e 2 Back-ends NodeJS

Se você já trabalhou com QA neste ecossistema, você também é bem vindo :)

## Local

Squads Remotos, com pessoas de todo o Brasil

## Requisitos

**Obrigatórios:**
- React.JS e Node.JS
- Ter trabalhado em algum projeto em produção com essas tecnologias

## Contratação

PJ a combinar

## Como se candidatar

Basta enviar seu currículo para talentos@intercase.com.br - assunto: Squad React/NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: falecom@intercase.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by brunooomelo** [comment]
Enviado!
