### ISSUE TITLE
[Rio de Janeiro] Python Developer @ Altran

### ISSUE THREAD

**Issue by lais-rosalini** [backend-br/vagas#3021]
> Vaga Remota durante a pandemia

## Altran

Altran, líder europeu em Tecnologia e Inovação. Operações em +30 países e 50.000 colaboradores. 
ACT Consultoria em Tecnologia, licenciado da Altran Technologies com 11 escritórios + 1200 Colaboradores  (São Paulo - Rio de Janeiro - Distrito Federal - Minas Gerais - Paraná - Santa Catarina). No Brasil ajudamos nossos Clientes nos projetos de Tecnologia, Inovação, Engenharia e Transformação Digital.   

## Local

Escritório, Rio de Janeiro - Botafogo ou Remoto

## Requisitos

**Obrigatórios:**
-  Python
-  AWS

**Desejáveis:**
- conhecimentos em Net Core

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 20,80/dia
- VT ou Vale combustível

## Contratação

CLT

## Como se candidatar

Por favor envie um email para lais.penedo@altran.com.br com seu CV anexado - enviar no assunto: Vaga Python

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by rodrigocardosodev** [comment]
Ola @lais-rosalini tudo bem?

Se fores possivel, terias como descrever melhor a vaga?
