### ISSUE TITLE
[São Paulo] Back-end Developer - Pl/Sr @SmartMEI

### ISSUE THREAD

**Issue by Leticiaschadeck** [backend-br/vagas#3023]
## Nossa empresa

A SmartMEI é uma fintech, focada em ajudar empreendedores autônomos com a burocracia de empreender no Brasil. Temos diversos serviços de desburocratização e financeiros no nosso app. Estamos lançando agora uma marca nova com um produto novo, que será focado em pequenas e médias empresas que contratam PJ. Essa nova marca se chama Work e tem uma licença de SCD aprovada pelo Bacen, você pode conferir mais detalhes aqui: https://www.work.com.br/.
A vaga irá atuar no backend dos dois sistemas, com muita tecnologia nova!

## Descrição da vaga

Nossas aplicações de backend são escritas nas linguagens NodeJS, TypeScript e Go, os bancos de dados são: Firebase RealTime DB, MongoDB, PostgreSQL e FoundationDB. Alguns dos principais frameworks e libs que utilizamos: GraphQL, Apollo, Express e 99Design. Plataformas: AWS (Lambda, API Gateway, SQS, S3), Firebase, Google Cloud (Functions, Pub/Sub, Tasks). Valorizamos alguns conceitos de programação e design, como Restfull para disponibilizar APIs, Promise, Async/Await, design de Microservices e um bom código que possa ser entendido não apenas por máquinas, mas também pelos seus colegas desenvolvedores.

Como a vaga júnior, você terá oportunidade de aprender toda essa stack aí, e os requisitos da vaga são: Saber programar em alguma linguagem de programação, mais de um ano de experiência de trabalho em alguma empresa, bons conhecimentos de inglês técnico (leitura e escrita).

## Local

Remoto ou Escritório, São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- Experiência com alguma linguagem de programação
- Ao menos 1 ano de experiência em alguma empresa
- Bom conhecimento de inglês téncnico (leitura e escrita)
- Alinhamento cultural com o time e com nosso propósito

**Desejáveis:**
- Conhecimento na stack acima
- Cassagem por startup

## Benefícios

- Home office e horário flexível;
- Escritório open space: contato direto com os founders, líderes e demais áreas;
- Excelente localização: ficamos em Pinheiros e próximo a 2 estações do metrô;
- Pode vir de bike que incentivamos e disponibilizamos bicicletário;
- Ambiente descontraído: puffs para descanso, lanchinhos a vontade, ambiente para alimentação e no dress code!;
- Oportunidades de crescimento: reuniões mensais com os principais resultados da empresa e as oportunidades em aberto - apoiamos a evolução interna dos nossos workers;
- Incentivo para a educação: valorizamos o aprendizado e queremos que você esteja sempre se desenvolvendo, por isso, reembolsamos 50% de valores investidos em estudos;
- Treinamentos técnicos e contato com as tecnologias mais recentes do mercado;
- Queremos dar todo apoio em um dos momentos mais especiais da sua vida: licença-maternidade de 6 meses e licença-paterninade de 20 dias, válido também para os casos de adoção :);
- Sabemos que o dia do seu aniversário deve ser comemorado com as pessoas que você ama, por isso, no mês do seu nascimento, você pode escolher um day off.

## Contratação

PJ 

## Como se candidatar

Se aplicar [nesse link](https://smartmei.recruiterbox.com/jobs/fk03zp7)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@smartmei.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by lucaslamar** [comment]
eu não tenho um ano mas vale?

**Comment by brunooomelo** [comment]
Enviado!

**Comment by Leticiaschadeck** [comment]
A vaga foi alterada de Junior para Pleno ou Senior.
