### ISSUE TITLE
[Porto Alegre] Dev C# .NET Backend - Jr. na Husky Logística

### ISSUE THREAD

**Issue by josehusky** [backend-br/vagas#303]
## Descrição da vaga

Somos uma startup focada em otimizar o delivery de restaurantes. Recentemente fomos selecionados no Startup Brasil e estamos montando nosso time.

Tipo de vaga: Bolsista CNPq
Salário: R$3.500,00 /mês
Local: Porto Alegre/RS (Remoto - Parcial)

## Local

Coworking em Porto Alegre

## Requisitos

**Obrigatórios:**
- Linguagem C#.Net Framework 4.5
- Banco de dados: Mysql
- APIs REST utilizando C# 
- Residir em Porto Alegre ou Região Metropolitana.

**Desejáveis:**
- Conhecimento de sistemas de PDV
- Ter trabalhado em projetos de integração com serviços de spooler de impressão do Windows
- Windows Forms

## Contratação

Bolsista CNPq 

## Nossa empresa

Somos uma startup focada em otimizar o delivery de restaurantes. Utilizamos processos de geolocalização, integrações e roteirizações para automatizar o processo de delivery.

## Como se candidatar

Interessados enviar CV para c@gohusky.net

## Labels

- Jr.
- Remoto - Parcial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
