### ISSUE TITLE
[Freela] PHP Developer: WordPress + WooCommerce

### ISSUE THREAD

**Issue by hmaesta** [backend-br/vagas#305]
O trabalho consiste na criação de uma área para personalização de pedido por parte do usuário antes da compra. _Informações detalhadas serão enviadas por e-mail._

- **Plataforma:** WordPress + WooCommerce
- **Freelancer** / Remoto

## Requisitos

**Obrigatórios:**
- PHP 7
- Experiência com WordPress
- Experiência com WooCommerce
- Javascript básico (pode ser jQuery)

**Desejáveis:**
- Experiência com alguma biblioteca de manipulação de PDF

## Como se candidatar

Por favor envie um email para hmaesta+vww@gmail.com com seu CV
Assunto do e-mail: `Vaga WordPress WooCommerce`
_Enviar trabalhos desenvolvidos que estejam online conta mais do que dizer qual faculdade fez_

## Labels
- Freela
- Remoto - Total
- WordPress
- WooCommerce

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
