### ISSUE TITLE
|Portugal| Java Developer na Aubay

### ISSUE THREAD

**Issue by FernandaMorais** [backend-br/vagas#306]
# Descrição da vaga

Projetos diferenciados em vários setores de atividade utilizando tecnologia JAVA entre outras.

## Local

Portugal: Lisboa e Porto

## Benefícios

- Plano de saúde
- Visto de Trabalho para Portugal
- Outras

#### Diferenciais

- cultura organizacional gerida pelo nosso Hapiness Manager
- horário flexível
- almoço grátis todas as sexta-feiras
- frigobar sempre cheio 
- armário das bolachas sempre cheio
- eventos mensais com atividades diferenciadas

## Requisitos

**Obrigatórios:**
- Experiência no desenvolvimento de backend 
- Domínio da língua inglesa

**Diferenciais:**
- projetos internacionais que permitem contato com vários países.

## Contratação

Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

## Nossa empresa

A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

## Como se candidatar

Por favor envie um email para fmorais@aubay.com com seu CV anexado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
