### ISSUE TITLE
[Remoto] Ruby Developer @ Ferreri

### ISSUE THREAD

**Issue by marceloandrade-ferreri** [backend-br/vagas#3073]
## A VAGA

A [Ferreri](http://ferreri.co) está em busca de desenvolvedores back-end apaixonados por programação, curiosos que busquem novas tecnologias, gostem de experimentar, testar e que tenham potencial de evolução técnica aliado ao conjunto de experiências que possuem, sejam elas profissionais e/ou experimentais. Buscamos pessoas que tenham experiência com versionamento de código, integração contínua, testes integrados, e que saibam resolver problemas. Que sejam organizadas, saibam gerenciar seu tempo, perguntem, interajam e se comuniquem. É imprescíndivel que compreendam e se envolvam no processo de desenvolvimento web (modelagem, desenvolvimento e implantação).

### Responsabilidades

- Escrever códigos compatíveis com padrões, incluindo teste/depuração em várias plataformas
- Trabalhar com designers para traduzir conceitos visuais em websites funcionais, microsites, microserviços, etc

### Tecnologias e plataformas que usamos com mais frequência

- Ruby / Rails
- Javascript / NodeJS
- .NET / C#
- Python / Django
- Git
- Google Cloud / AWS / Cloud Azure
- Docker / Kubernetes

### Como trabalhamos

Liberdade, flexibilidade e trabalho remoto. Aqui, todo mundo tem as ideias ouvidas e a mesma responsabilidade pelo projeto. Como cada um tem autonomia e flexibilidade nas tarefas que recebe, é importante estar comprometido de coração e estar disposto a dar o seu melhor. Não há intensa cobrança, o que não significa que não esperam muito de você.

## REQUISITOS

- Tenha conhecimento especializado das melhores práticas de experiência do usuário e capacidade de implementar soluções com base em necessidades exclusivas de usuários específicos.
- Trabalhe em colaboração com equipes internas de desenvolvimento e design para garantir a integração perfeita com tecnologia de back-end e uma excelente experiência do usuário.
- Tenha atenção aos detalhes e capacidade de priorizar demandas concorrentes.
- Desenvoltura, boa comunicação e disposição para buscar informações e sanar dúvidas.
- Tenha como valores: independência, ownership e auto gerenciamento.
- Tenha experiência com versionamento de código, integração contínua e testes integrados.
- Tenha familiaridade com código, preferencialmente, mas não exclusivamente (com um ou mais): Ruby on Rails, Python,  JavaScript, Java, .NET, Go.
- Tenha experiência com banco de dados.

## BENEFÍCIOS

- Cartão de benefícios: cartão de crédito Visa com créditos mensais que podem ser utilizados para Refeição, Alimentação e Cultura
- Auxílio bem-estar: reembolso de 80% do valor da mensalidade de atividades que ajudem na saúde do corpo e da mente (esportes, academia, pilates, terapia/psicólogo, etc) 
- Trabalho remoto
- Horário de trabalho flexível
- Trabalhar com tecnologia de ponta
- Perspectiva de crescimento
- Autonomia nas decisões de acordo com sua experiência
- Ser ouvido sempre

## COMO SE CANDIDATAR

Por favor envie um e-mail com tudo que tiver de informação sobre você: currículo, LinkedIn, experiência, etc. Caso tenha algum projeto em algum repositório git e rodando em algum servidor, certifique-se de que o repositório esteja público e adicione no e-mail o link para o repositório e link do projeto rodando em produção. Envie também a pretensão salarial caso tenha uma em mente.

O e-mail deve ser enviado para vagas@ferreri.co com o assunto no seguinte formato: "Nome - Backend - Especialidade".
Exemplo: Jorge Silva - Backend - Ruby on Rails.

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior

**Comment by jonatanmurga** [comment]
> ## A VAGA
> 
> A [Ferreri](http://ferreri.co) está em busca de desenvolvedores back-end apaixonados por programação, curiosos que busquem novas tecnologias, gostem de experimentar, testar e que tenham potencial de evolução técnica aliado ao conjunto de experiências que possuem, sejam elas profissionais e/ou experimentais. Buscamos pessoas que tenham experiência com versionamento de código, integração contínua, testes integrados, e que saibam resolver problemas. Que sejam organizadas, saibam gerenciar seu tempo, perguntem, interajam e se comuniquem. É imprescíndivel que compreendam e se envolvam no processo de desenvolvimento web (modelagem, desenvolvimento e implantação).
> 
> ### Responsabilidades
> 
> - Escrever códigos compatíveis com padrões, incluindo teste/depuração em várias plataformas
> - Trabalhar com designers para traduzir conceitos visuais em websites funcionais, microsites, microserviços, etc
> 
> ### Tecnologias e plataformas que usamos com mais frequência
> 
> - Ruby / Rails
> - Javascript / NodeJS
> - .NET / C#
> - Python / Django
> - Git
> - Google Cloud / AWS / Cloud Azure
> - Docker / Kubernetes
> 
> ### Como trabalhamos
> 
> Liberdade, flexibilidade e trabalho remoto. Aqui, todo mundo tem as ideias ouvidas e a mesma responsabilidade pelo projeto. Como cada um tem autonomia e flexibilidade nas tarefas que recebe, é importante estar comprometido de coração e estar disposto a dar o seu melhor. Não há intensa cobrança, o que não significa que não esperam muito de você.
> 
> ## REQUISITOS
> 
> - Tenha conhecimento especializado das melhores práticas de experiência do usuário e capacidade de implementar soluções com base em necessidades exclusivas de usuários específicos.
> - Trabalhe em colaboração com equipes internas de desenvolvimento e design para garantir a integração perfeita com tecnologia de back-end e uma excelente experiência do usuário.
> - Tenha atenção aos detalhes e capacidade de priorizar demandas concorrentes.
> - Desenvoltura, boa comunicação e disposição para buscar informações e sanar dúvidas.
> - Tenha como valores: independência, ownership e auto gerenciamento.
> - Tenha experiência com versionamento de código, integração contínua e testes integrados.
> - Tenha familiaridade com código, preferencialmente, mas não exclusivamente (com um ou mais): Ruby on Rails, Python,  JavaScript, Java, .NET, Go.
> - Tenha experiência com banco de dados.
> 
> ## BENEFÍCIOS
> 
> - Cartão de benefícios: cartão de crédito Visa com créditos mensais que podem ser utilizados para Refeição, Alimentação e Cultura
> - Auxílio bem-estar: reembolso de 80% do valor da mensalidade de atividades que ajudem na saúde do corpo e da mente (esportes, academia, pilates, terapia/psicólogo, etc) 
> - Trabalho remoto
> - Horário de trabalho flexível
> - Trabalhar com tecnologia de ponta
> - Perspectiva de crescimento
> - Autonomia nas decisões de acordo com sua experiência
> - Ser ouvido sempre
> 
> ## COMO SE CANDIDATAR
> 
> Por favor envie um e-mail com tudo que tiver de informação sobre você: currículo, LinkedIn, experiência, etc. Caso tenha algum projeto em algum repositório git e rodando em algum servidor, certifique-se de que o repositório esteja público e adicione no e-mail o link para o repositório e link do projeto rodando em produção. Envie também a pretensão salarial caso tenha uma em mente.
> 
> O e-mail deve ser enviado para vagas@ferreri.co com o assunto no seguinte formato: "Nome - Backend - Especialidade".
> Exemplo: Jorge Silva - Backend - Ruby on Rails.
> 
> ## LABELS
> 
> #### Alocação
> - Remoto
> 
> #### Nível
> - Pleno
> - Sênior
