### ISSUE TITLE
[São Paulo - Vila Olímpia] .Net Developer  (Sênior e Junior)

### ISSUE THREAD

**Issue by Lilicaan** [backend-br/vagas#309]
*Descrição da vaga*
Se você é ávido por tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!

Na Dextra os desenvolvedores são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento de software, garantindo o sucesso da entrega para o cliente.

O que você precisa saber para ocupar esta vaga?
Programar.. Mas com paixão! Ser crítico em relação à qualidade de código;
Desenvolvimento em .Net Core e C# 
Conhecer AWS
Integração e entrega continua;
Ser colaborativo e  gostar de trabalhar em equipe!
Conhecimento em metodologias ágeis (Scrum)

Disponibilidade para atuar proximo Vila Olimpia em SP.

*Local*

São Paulo - Vila Olímpia

*Contratação*

CLT

*Nossa empresa*

A Dextra é um estúdio de inovação digital e de desenvolvimento de software ágil para clientes que buscam criar produtos disruptivos. Combinamos processos de inovação, design de UX, novas tecnologia e visão de negócios para criar software que reposicione os nossos clientes no mundo dos negócios digitais.

*Como se candidatar*

Envie  seu cv ou LinkedIn para recrutamento@dextra.com.br - enviar no assunto: .NetSP

**Comment by joaowick** [comment]
Bom dia! O endereço de e-mail está correto? Pois estou recebendo de volta dizendo que o e-mail está incorreto. :(

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
