### ISSUE TITLE
[Amsterdã - Holanda] Software Developer na Booking.com

### ISSUE THREAD

**Issue by henriquehsv** [backend-br/vagas#31]
## About Booking.com
At Booking.com we combine the best traits of a start-up with the resources of planet Earth’s #1 accommodation website. We are working towards building the ultimate travel experience, building and improving great products for both travelers and the accommodation partners

#### Booking.com is looking for self-starters who are great at solving real life problems.

We offer an international, diverse, fun, and dynamic environment. If scale and complexity excite you, Booking is the place to B!

## B.responsible

As a Software Developer, you are responsible for the development, performance, and scaling of our public website as well as internal systems. You will work independently and will also be responsible for making technical decisions within a team.

### Important aspects of the job include:

* Rapidly developing next-generation scalable, flexible, and high-performance systems.
* Solving issues with the site and internal systems, prioritizing based on customer impact
* Acting as an intermediary for problems, with both technical and non-technical audiences
* Testing; we run thousands of experiments running at one time. We built one of the most advanced A/B testing platforms in the industry.
* Most products are developed in Perl, but not all. Perl is very effective when it comes to rapid prototyping, which our product development teams do a lot of. It’s not necessary to know Perl before you start, but it helps. We are not just using the language, we influence the future of the language.
* Contributing to the growth of Booking.com through interviewing, on-boarding, or other recruitment efforts
## B.skilled

We are looking for driven Developers who enjoy solving problems, who initiate solutions and discussions and who believe that any challenge can be scaled with the right mindset and tools.

#### We have found that people who match the following requirements are the ones who fit us best:

* Minimum of 3 years software development experience; using 2 or more server side programming languages. Preferably Perl, Java, Python, Scala, C++ etc.
* Previous experience with distributed systems
* Hands on experience of developing in and contributing to open source data technologies, such as Hadoop
* Demonstrable experience with MySQL and PostgreSQL or similar relational databases
* Experience of working on products that impact a large customer base is an advantage
* Preferably a university degree in Mathematics or Software Engineering
* Excellent communication; written and spoken
## B.offered

* Headquarters located in one of the most dynamic cities in Europe: Amsterdam
* Performance-based company that offers 26 vacation days, career advancement, and lucrative compensation, including bonuses and stock potential
* Discount on Booking.com accommodations with the “Booking Deal” including other perks and benefits
* Company-sponsored family and social activities to help our employees become integrated with each other and Dutch culture
* Diverse and creative colleagues from every corner of the world
* Generous relocation package, ensuring a smooth transition to working and living in Amsterdam

To apply to this position submit your CV through this link: https://grnh.se/0b9410661

*P.S. Estou a disposição para tirar dúvidas sobre a vaga no Hangouts ou E-mail :)* (henriquehsv@gmail.com)

**Comment by reginaldojunior** [comment]
O que coloco como label?

**Comment by henriquehsv** [comment]
@reginaldojunior Boa pergunta! Não é CLT nem PJ. Vcs tem alguma diretivas pra vagas de fora do país? Talvez colar [exterior][visa sponsorship][full time][presencial]?

Quanto a tecnologia, usamos perl e java, mas saber as linguagens não é pré-requisito para a candidatura.

**Comment by reginaldojunior** [comment]
Não tinha até agora 😄 vou criar aqui.

**Comment by henriquehsv** [comment]
Galera, se alguém estiver por Amsterdã é quiser tomar um café, só falar comigo pelo Hangouts.

**Comment by henriquehsv** [comment]
Vaga fechada por enquanto

**Comment by henriquehsv** [comment]
Aceitando currículos novamente

**Comment by josebispo** [comment]
@henriquehsv é uma vaga ninja?, abre e fecha kkk

**Comment by henriquehsv** [comment]
@josebispo Pior que sim. Tava aberta quando olhei hoje de manhã, de tarde tinha fechado.
Acho que a galera do RH fecha pra processar os currículos, depois abre de novo.

**Comment by henriquehsv** [comment]
Tem que ficar de tocaia com o currículo e enviar assim que a vaga abrir :)

**Comment by josebispo** [comment]
@henriquehsv atualmente to tranquilão em um projeto bem bacana, mas tenho um amigo que participou do processo foi até a holanda, enfim legal sua iniciativa, grande abraço.

**Comment by henriquehsv** [comment]
Legal que teu amigo conseguiu dar um pulinho em Amsterdã! Se alguém mais for por lá é só falar que a gente sai pra tomar um café :)

**Comment by henriquehsv** [comment]
Vaga ninja de volta por tempo limitado. Garanta já sua aplicação enviando o currículo pelo link. 😄

**Comment by reginaldojunior** [comment]
A vaga ninja ainda está aberta?

**Comment by henriquehsv** [comment]
@reginaldojunior Fechada por enquanto, se abrir novamente eu reabro a issue :)

**Comment by henriquehsv** [comment]
Vaga reaberta 😄, reforço o convite pra me contactar por email ou Hangouts se tiverem alguma dúvida. Divulguem pros coleguinhas que quiserem tentar.

**Comment by henriquehsv** [comment]
Vaga fechada novamente, galera. Não deixem de divulgar que sempre aparecem mais vagas por aqui. =)
Boa sorte aos candidatos.

**Comment by henriquehsv** [comment]
Olá galera, ano novo, vaga nova!
Estamos contratando pra Amsterdã novamente. Nosso site de carreiras foi atualizado, e atualizei o link junto. Qualquer dúvida estou a disposição no hangouts.

**Comment by AndersonAltissimo** [comment]
@henriquehsv  dessa vez ficou um bom tempo aberta ... hahaha

**Comment by henriquehsv** [comment]
@AndersonAltissimo dessa vez sim :) Pior que acabei de achar ela aqui no site de novo 😄
Pessoal só mudou o link, vou atualizar na descrição.

Estamos com vagas abertas pra Android, iOS e Full Stack developers tb.

**Comment by henriquehsv** [comment]
Não estou mais trabalhando pela Booking e agora eles mudaram a forma de contratar para ser mais específico para cada departamento. Fechando essa issue por aqui, se alguém ainda se interessar em aplicar, podem ver as vagas mais atuais em: https://careers.booking.com/
