### ISSUE TITLE
[Porto Alegre ou Remoto] Django Developer @ DeepX

### ISSUE THREAD

**Issue by lbrancacio** [backend-br/vagas#3114]
> Vaga Remota durante a pandemia

## Feel like changing the world today? 

Estamos com vagas abertas para desenvolvedores aqui na [DeepX](http://deepx.it/) :D 

O seu e nosso maior desafio será, além de desenvolver e estar sempre trabalhando com as mais recentes tecnologias, entrar e se desenvolver no espírito da nossa cultura de conhecimento compartilhado, somos uma grande equipe! Auto-gerenciamento e colaboração são valores muito importantes pra gente.

Procuramos pessoas que tenham para si o drive para constante aprendizado, se sintam confortáveis em estar num ambiente em que "pior que errar é não tentar" e consigam se manter positivas frente aos desafios, buscando soluções e querendo sempre colocar em prática o que aprendem. 

## Descrição da vaga

Como Django developer, você vai atuar na nossa área de consultoria, onde prestamos serviço para clientes do mercado internacional. Ao se juntar ao time, você irá: 

- Ajudar a identificar e solucionar problemas desafiafores
- Desenvolver código de qualidade usando Python
- Auxiliar no desenvolvimento de arquitetura
- Contribuir com a criação da experiência de produtos
- Ter contato direto com clientes e participar de reuniões com membros da equipe e clientes

## Local

Exemplo: Remoto ou Escritório, Porto Alegre - Moinhos de Vento

## Requisitos

- Experiência prévia em desenvolvimento backend
- Conhecimento em Django, Python e/ou outras linguages de programação
- Experiência em arquitetura e implementação de web services utilizando REST/GraphQL
- Proficência em databases e desenvolvimento SQL
- Inglês intermediário ou avançado - somos uma empresa americana e lidamos diariamente com nossos colegas de continente.
- Querer fazer parte de uma cultura de compartilhamento, frequentemente temos meetups na empresa e encorajamos o compartilhamento de conhecimento.

**Diferenciais:**
- Experiência em negócios de e-commerce e Shopify

## Contratação

CLT ou PJ a combinar

## Como se candidatar

É só usar [esse link](https://jobs.lever.co/deepx/b9172874-12b7-497e-96f1-ff44de6836bf/apply)  😄 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Caso de não tiver resposta, mande um email para: careers@deepx.it

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by JrJuscelino** [comment]
Olá, acredito que o link para se candidatar está errado :)

**Comment by lbrancacio** [comment]
fixed! obrigada :)

**Comment by BrunoMoreno** [comment]
O link está quebrado ainda.

**Comment by lbrancacio** [comment]
> O link está quebrado ainda.

O link chegou a ser arrumado mas a vaga foi fechada.
