### ISSUE TITLE
[Remoto] PHP Back-end Developer @ DB1 Group

### ISSUE THREAD

**Issue by talentos-db1** [backend-br/vagas#3115]
## Nossa empresa
Somos um grupo de tecnologia com 19 anos de expertise em desenvolvimento de software voltado para soluções de grandes empresas. Estamos há 10 anos consecutivos dentre as melhores empresas para trabalhar, pelo GPTW.
Ser DB1 é pertencer a um grupo que transforma a vida das organizações e das pessoas por meio da tecnologia. Nossa cultura, conhecimento e habilidades nos movem para fazer entregas que ajudam as pessoas a terem um dia a dia melhor.
Fazer parte do DB1 Group é ser movido a desafios, afinal, são neles que as melhores oportunidades surgem.

## Descrição da vaga
Buscamos um(a) profissional apaixonado(a) por tecnologia, que desenvolva em backend com PHP7+ e busque entregar soluções de qualidade aplicando as melhores práticas de programação, tais como SOLID e GRASP. Essa vaga se destina a profissionais antenados, interessados em evolução contínua, sejam curiosos e acompanhem as melhores tendências em desenvolvimento.

## Local

Remoto ou Maringá-PR, Presidente Prudente-SP ou Campo Grande-MS

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento em PHP7+;
- Noções de Docker e Composer;
- Conhecimento básico em MySQL;
- Conhecimento em Orientação a Objetos;
- Conhecimento em Restful API;
- Conhecimento em boas práticas de programação (SOLID, GRAPS);
- Experiência com testes;
- Git básico a intermediário;
- Ser uma pessoa flexível e por dentro das novidades tecnológicas; 
- Grande capacidade de aprendizado para novas práticas, tecnologias, linguagens de programação e culturas de engenharia.

**Desejáveis:**
- Conhecimento em Hexagonal Architecture e Clean Architectural
- Experiência com code review

## Benefícios
- Plano de saúde
- VR e/ou VA
- Materiais de trabalho oferecidos pela empresa (computador, tela, teclado, mouse, fone de ouvido).

**Diferenciais:**

- Horários flexíveis;
- Desenvolvimento de Carreira (Plano de Desenvolvimento Individual, feedbacks, acompanhamentos)
- Frutas fresquinhas todo dia;
- Café e chá feitos pela Dona Rosa com carinho para toda a equipe;
- DB1 Snacks para um lanche da tarde;
- Diversos comitês para você participar de ações com impacto dentro e fora da DB1;

## Contratação

CLT

## Como se candidatar
Através do nosso site:
PHP Pleno: https://vagasdb1.recruiterbox.com/jobs/fk0qyoc?source=Github
PHP Senior: https://vagasdb1.recruiterbox.com/jobs/fk0qykv?source=Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 45 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Senior

**Comment by walteralleyz** [comment]
Olá, a vaga tem uma LABEL Junior, mas pede nível Pleno/Senior.

**Comment by talentos-db1** [comment]
Olá @walteralleyz , obrigada por nos informar! Estamos verificando como corrigir essa questão, mas a vaga de fato se destina para Pleno e Senior.
