### ISSUE TITLE
[Remoto] Back-end Developer (R$9.000,00) @ iCasei

### ISSUE THREAD

**Issue by gustaum** [backend-br/vagas#3124]
## Nossa empresa

O iCasei é o maior e melhor fornecedor de [sites e listas de casamento](https://www.icasei.com.br/site-de-casamento) na América Latina e hoje é líder no mercado. 

## Descrição da vaga

Estamos buscando uma pessoa que seja proativa e que tenha interesse em trabalhar em um ambiente de desenvolvimento de produtos, com autonomia e mudanças constantes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Ruby On Rails
- SQL Server
- MySQL
- MongoDB
- Docker / Kubernets
- Conhecimento em ferramentas GIT (Conhecimento do Terminal)

**Desejáveis:**
- Conhecimento de frameworks Js
- Experiencia com AWS e Google Cloud
- Experiência com serviços de mensageria

**Diferenciais:**
- Inglês (técnico)

## Benefícios

- A combinar

## Contratação

PJ a combinar

## Faixa Salarial
De R$7.000 a R$10.000

## Como se candidatar

Por favor preencher o formulário https://forms.gle/ZbMvnr8kcu2V8Zj59

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: backend@icasei.com.br

#### Alocação
- Alocado
- Remoto
- Homeoffice

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by brunooomelo** [comment]
Enviado.

**Comment by fabiosoaresv** [comment]
Ufa, foi difícil mas enviei! haha

**Comment by gustaum** [comment]
Qualquer dúvida é só nos mandar um e-mail: backend@icasei.com.br
