### ISSUE TITLE
[São Paulo - SP] BACKEND JAVA JUNIOR e PLENO - RADAR Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#313]
VAGAS: BACK END JUNIOR e PLENO

Requisitos:
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência em arquitetura de dados, modelagem de dados e aplicações para integração em plataformas distribuídas e relacionais;
•	Experiência com programação Java, PL/SQL e Stack Spring (Spring Framework 4.0+, SpringBoot, Spring Data, Hibernate);
•	Experiência com git, ferramentas de build contínuo, desenvolvimento REST e cloud computing;
•	Será considerado como diferencial, profissionais com experiência com bancos NoSQL, docker, mesos e marathon.

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.
Local: São Paulo/SP – Zona Sul 
Interessados: Enviar CV para vagas@radarprofissional.com.br 
Visite nosso site: www.radarprofissional.com.br 
LinkedIn: https://www.linkedin.com/company/10144586/ 
Visite nossa página: https://www.facebook.com/radarprofissional.com.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
