### ISSUE TITLE
[REMOTO] Back-End Developer na Upnid

### ISSUE THREAD

**Issue by vemproninho** [backend-br/vagas#3138]
**Nosso DNA**
Somos uma startup em crescimento acelerado, então você terá a oportunidade de aprender muito e crescer com o time. O ambiente é descontraído, mas somos muito responsáveis com nosso trabalho e comprometidos com a entrega - **não fazemos trabalho meia boca.**

**Temos fome**! Estamos em constante evolução, buscando sempre a melhor solução para os desafios que encontramos, o que significa que nem sempre temos todas as respostas. Por isso, capacidade de adaptação, ser um entusiasta de novas tecnologias e ter disponibilidade para aprender são características muito importantes para fazer parte desse squad. Moramos fora da zona de conforto, **não sabemos tudo, mas aprendemos rápido.**

**Tecnologias - O que você precisa saber?**
Seria bacana você já ter algum conhecimento prévio em:

- Go (essa é a nossa linguagem para desenvolvimento de back-end e hoje representa 95% da nossa base)
- Conhecimento de gRPC
- Banco de dados relacionais, como MySQL ou PostgreSQL
- MongoDB
- Protobuf

Mas se você ainda não teve a oportunidade de utilizar essas tecnologias, tudo bem! A experiência em algumas outras linguagens podem fazer sentido pra gente também. Por exemplo:

Ter mexido com uma linguagem compilada (mesmo não sendo Go), é um grande diferencial. Exemplos: Java, Erlang, Haskell, Rust, Swift, C, C++
Se já tiver trabalhado com linguagens tipadas, isso nos indica que você tem grandes chances de aprender Go numa velocidade muito rápida. Alguns exemplos de outras linguagens são: Java, Swift, PHP, TypeScript, Rust, C, C++.
Além disso, valorizar boas práticas de desenvolvimento é fundamental. Somos uma empresa de pagamentos e precisamos ser capazes de escalar o sistema de forma sustentável. Ainda pensando no nosso negócio, se você já trabalhou numa empresa que exija alta confiabilidade de sistemas, também é um ótimo sinal.

Para o momento que estamos, é importante encontrarmos uma pessoa que já entre jogando, por isso fica mais difícil se você estiver nos primeiros passos, procurando uma vaga de nível anterior a pleno. Veja bem, não existe nenhum demérito nisso! Nós temos grande alegria em desenvolver nosso time, mas nesse momento, não seríamos capazes de fazer isso da forma como deve ser para quem está começando (lembra que não fazemos trabalho meia boca?), então estamos procurando gente que já tenha pelo menos uns 2-3 anos de experiência, ok?

Ah, se você já passou pelo mercado de meios de pagamento online (bancos, adquirentes, sub-adquirentes, gateways, e-commerces, marketplaces, etc), só vem! Vai ser um grande diferencial você conhecer do nosso mundo. :)

Sobre a vaga
Nossos Devs trabalham remoto, então você pode se candidatar de qualquer lugar do Brasil! :)

Estamos considerando pretensão salarial e de benefícios, temos Plano de Saúde, Vale UpHouse (para você visitar o HQ) e uma Cultura Colaborativa, de Liberdade e Autonomia.

Se identificou? Aguardamos ansiosos a sua candidatura!
https://upnid.breezy.hr/p/fda48d14b0d1-desenvolvedor-back-end

#VemProNinho

Nível: de Pleno a Sênior.

**Comment by wiltonlcsj** [comment]
Que mal pergunte, mas qual a necessidade de RG e CPF numa candidatura de emprego? (sem trashtalk, só dúvida mesmo)

**Comment by ydlpizarro** [comment]
Porque tem o label estagiário se a vaga fala: "... fica mais difícil se você estiver nos primeiros passos, procurando uma vaga de nível anterior a pleno."

![Upnid](https://user-images.githubusercontent.com/43155168/94070481-ac0c5f80-fdc8-11ea-83d9-2f7d2b972c57.png)

**Comment by vemproninho** [comment]
Oi @ydlpizarro, tudo bem? Pois é! esse label entrou automaticamente e eu não consegui tirar por nada! Não fomos nós que inserimos :(

**Comment by vemproninho** [comment]
> Que mal pergunte, mas qual a necessidade de RG e CPF numa candidatura de emprego? (sem trashtalk, só dúvida mesmo)

Olá @wiltonlcsj , tudo bem? Precisamos fazer uma pesquisa de idoneidade para contratarmos você, por isso, antes de fazermos a proposta oficial, precisamos do seu CPF para tal pesquisa.

**Comment by ydlpizarro** [comment]
blz, vi que criaram outra vaga e agora deu certo . Boa
