### ISSUE TITLE
[São Paulo - SP] BACKEND Pleno e Sênior - RADAR Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#314]
VAGAS: BACK END PLENO e SÊNIOR

Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência com API Rest e linguagens Java, Javascript, Framework Spring-boot e CSS;
•	Experiência com fila e mensageria (Kafka, Storm, entre outros);
•	Vivência em banco de dados non relational (BD Cassandra e outros);
•	Experiência com aplicações utilizando Docker.

Contratação: CLT + VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.
Local: São Paulo/SP – Zona Sul 
Interessados: Enviar CV para vagas@radarprofissional.com.br 
Visite nosso site: www.radarprofissional.com.br 
LinkedIn: https://www.linkedin.com/company/10144586/ 
Visite nossa página: https://www.facebook.com/radarprofissional.com.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
