### ISSUE TITLE
[Remoto] NodeJS+TS+GraphQL na Influu

### ISSUE THREAD

**Issue by influu** [backend-br/vagas#3140]
## Descrição da vaga
Desenvolvimento de novos projetos e manutenções com NodeJS.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- 2 anos de experiência com desenvolvimento NodeJS
- Apollo GraphQL Server
- TypeScript

## Contratação
Freelancer

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV anexado - enviar no assunto: [Vaga TS+GraphQL] + Nome_Sobrenome

## Labels

- alocação/Flexível
- experiência/Pleno
- experiência/Sênior

**Comment by brunooomelo** [comment]
Enviado.
