### ISSUE TITLE
[REMOTO] Fullstack Developer Pleno Typescript @ Profitfy.me

### ISSUE THREAD

**Issue by profitfyme** [backend-br/vagas#3144]
## Nossa empresa

Somos uma startup de inovação & tecnologia fundada em
2016, visando solucionar problemas e automatizar processos
no mercado de e-commerce e digital.

## Descrição da vaga

A nossa empresa começará desenvolver uma solução de pagamentos para e-commerce.

Nós trabalhamos com novas tecnologias e por isso valorizamos os profissionais que são abertos a aprender novas coisas e não tem medo de sair de sua zona de conforto.

Horário: Full-time

- Desenvolvimento de projetos NodeJS + TypeScript com Clean Architecture;
- Desenvolvimento de telas a partir de layouts (feitos por nossos UI/UX designers) com React.
- Fazer testes integrados e unitários.

## Local

Remoto ou Escritório, São Paulo - Jardim São Paulo

## Requisitos

**Obrigatórios:**
- Experiência de desenvolvimento de projetos com Typescript e Clean Architecture;
- Experiência com React Hooks, Context.

**Desejáveis:**
- Conhecimento em AWS;
- Conhecimento em Docker;
- Conhecimento em CI/CD;

**Diferenciais:**
- Ter trabalhado com areas relacionadas e-commerce

## Contratação

PJ a combinar

## Como se candidatar

Link para se candidatar: https://forms.gle/Tb7qcWG4rHktc1GU9

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by thediegochen** [comment]
Opa, a vaga ainda estã aberta?
