### ISSUE TITLE
[São Paulo - SP] - DESENVOLVEDOR ASP.NET / C# JUNIOR e PLENO - RADAR Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#315]
VAGA: DESENVOLVEDOR ASP.NET / C# JUNIOR e PLENO

A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

Requisitos:  

•	Superior completo em Análise e Desenvolvimento de Sistemas, Ciência da Computação ou áreas afins;
•	Experiências anteriores com ASP.Net 4.5 ou superior, C# e desenvolvimento de Web Services; 
•	Desenvolvimento e Modelagem OO Puro(POCO)/ UML/ Modelagem de Domínios/Classes;
•	Vivência em HTML/ HTML Tag/ Json/ Jquery/ CSS (Avançado);
•	Experiência com Banco de dados SQL Server (criação de tabelas, views, functions e stored procedures);
•	Inglês intermediário;
•	Será considerado como diferencial, o profissional com conhecimentos em Telerik/Xamarin.

Contratação: PJ
Local: Região do ABC/SP
Interessados: Enviar CV para vagas@radarprofissional.com.br 
Visite nosso site: www.radarprofissional.com.br 
LinkedIn: https://www.linkedin.com/company/10144586/ 
Visite nossa página: https://www.facebook.com/radarprofissional.com.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
