### ISSUE TITLE
[BUENOS AIRES - ARGENTINA] Back-End Developer na [ROBERT HALF] 

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#316]
Desenvolvedor VB6 - Buenos Aires
•	Experiência com serviços de rotina de cálculos; 
•	Desenvolver macros em Excel;
•	Espanhol Fluente;
Tempo do projeto: 2 meses CLT
Hospedagem e alimentação é por conta da empresa.
Remuneração: 4.600,00 + Benefícios.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
