### ISSUE TITLE
[Remoto] Back-End Developer Node.js na ARK.io

### ISSUE THREAD

**Issue by luciorubeens** [backend-br/vagas#317]
## Descrição

A **Ark Ecosystem** é uma empresa com sede na França, que visa criar um ecossistema inteiro de correntes conectadas fornecendo ferramentas open-source e fáceis de utilizar para publicar sua própria blockchain. Estamos expandindo nossos projetos e procuramos por desenvolvedores com conhecimento em **criptografia**.

## Vaga

Nosso time busca profissionais back-end com experiência em Node.js, com disponibilidade full-time e não se espante ao ouvir termos como Byzantine Fault Tolerance, Máquina de estados finita (FSM), SHA-256, Criptografia de curva elíptica, Turing completa, Árvore de Merkle, Bloom filters, etc…

Dê uma olhada no nosso repositório: https://github.com/ArkEcosystem/core

## Requisitos

- Javascript ES6 (Node.js)
- PostgreSQL
- Criptografia (ECDSA)
- GIT
- Inglês (Básico)
- Testes unitários e automatizados
- Código limpo, bem escrito e organizado

## Diferenciais

- Experiência em outras linguagens de programação como Go, C ou C++
- Solidity (Ethereum)
- LevelDB
- Conhecimento em protocolos P2P

## Contratação

- Salário baseado em Euro com pagamento em Bitcoin, ARK ou combinação das duas. 
- Os recibos podem ser emitidos a partir de nossa empresa na França.
- Não nos importamos se você é autônomo, freelancer, contratado ou tem sua própria empresa.
- Salário é negociado caso a caso.

## Como se candidatar

Você pode enviar seu currículo ou portfolio, experiência e trabalho anterior para jobs@ark.io.

## Labels

- Remoto
- Node.js
- JavaScript

[Leia a descrição completa da vaga em Inglês](https://blog.ark.io/ark-team-is-expanding-looking-for-core-developers-9b88ed0c8ce8).

**Comment by Pedro-Souza** [comment]
Já fiz algumas contribuições para outros projetos da Ark. Acho a projeto muito bacana.
Sabe se tem alguma vaga para Angular, ou até mesmo python?

**Comment by Pompeu** [comment]
Que vaga bacana .. meu deus  NodeJS,  Golang, vou estudar Criptografia (ECDSA) que não conheço tentar um trabalho nessa empresa em um futuro próximo muito massa a vaga.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
