### ISSUE TITLE
ANALISTA DESENVOLVEDOR PLENO(FULL STACK)

### ISSUE THREAD

**Issue by JessicaBarrosNerus** [backend-br/vagas#3180]
Olá, somos a Nérus, uma empresa de tecnologia com DNA varejista, especializada em software de gestão de varejo e transformação do varejo físico em digital. Aqui você vai trabalhar em um ambiente descontraído, colaborativo, com liberdade para desenvolver suas habilidades e aprender Muito. Venha fazer parte deste time!

Saiba mais sobre a vaga:

ANALISTA DESENVOLVEDOR PLENO(FULL STACK)

O que vai fazer:

Sustentar a evolução dos nossos produtos:  Nérus Web, Web Desktop e APIs.

O que precisa ter:

1 ano de experiência com desenvolvimento nas linguagens JavaScript e PHP, APIs, NODE E REACT 
Bons conhecimentos de padrões de projetos, refatoração (melhoria de código) e testes.
Excelente lógica de programação.
MYSQL intermediário.
Linux básico
Experiência com GIT, ou alguma outra ferramenta de versionamento.
Conhecimento sobre: CSS, HTML, jQuery e API REST.

Será um diferencial:

Desenvolvimento de ERP WEB
Rotinas e processos ligados ao varejo;
Conhecimento em AngularJS, ReactJS;
Conhecimento em Apache Cordova ou Ionic.

Envie seu currículo para rh@nerus.com.br

#vagadevBH
#VagasTIBH
#VagasBH
#FullStack

**Comment by itsGabriel** [comment]
A vaga seria presencial?

**Comment by JessicaBarrosNerus** [comment]
Olá, boa tarde!
Estamos de home office no momento mas seria presencial sim.
Se houver interesse nos envie um currículo.



[image: Foto de JÉSSICA BARROS]

JÉSSICA BARROS

Analista | Recursos Humanos

31 99773-670431 3273-4415

Viva o Omnichannel!
[image: logo nerus] <http://www.nerus.com.br/>

www.nerus.com.br





Em seg., 28 de set. de 2020 às 16:58, Gabriel Marques <
notifications@github.com> escreveu:
