### ISSUE TITLE
[São Paulo] Backend Node na Ewally

### ISSUE THREAD

**Issue by kevenjesus** [backend-br/vagas#32]
## Descrição da vaga

Proposta para desenvolvedor Junior ou Pleno (node.js) para startup fintech, basicamente conta digital...
Ewally é uma das 10 empresas selecionadas entre 550 startups para participar do INOVABRA (2016).
Programa de inovação aberto, operado pelo Bradesco.

## Local
Presencial: Av.Angelica, 2529 (proximo metro paulista)

## Requisitos

- Analise de requisitos
- Javascript/ES6
- Mundo node (mongo, express, template engine)
- Terminal e Git
- Noções de infra

## Diferenciais

- TDD
- typescript

## Beneficios

- Vale transporte
- Vale refeição (R$ 20/dia)
- Chopp no local
- Espaço incrível com networking foda

## Salarios e tipos de contratação

- Junior: R$ 3.500 CLT ou R$ 4.500 PJ
- Pleno: R$ 4.500 CLT ou R$ 5.500 PJ

Interessados e prontos para voar me mandar github, linkedin, curriculo o que tiver para falecom@keven.com.br

**Comment by rafaelaccampos** [comment]
A vaga está aberta ainda?

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
