### ISSUE TITLE
[São Paulo/SP] Back End Developer na MJV Technology & Innovation

### ISSUE THREAD

**Issue by RHRJ** [backend-br/vagas#320]
MJV Technology & Innovation, consultoria dedicada a transformar negócios e solucionar desafios complexos para levar ao mercado soluções inovadoras em produtos e serviços, está busca de alguns Back - End para atuar em cliente no ramo financeiro!

A nossa matriz é carioca mas estamos presentes em São Paulo, Curitiba e em unidades internacionais nos EUA, França, Inglaterra, Itália e Portugal.

A MJV acredita que uma equipe colaborativa enriquece a qualidade do nosso trabalho e produz resultados transformadores.

### **Requisitos**:

- .NET (ASP.NET MVC, ASP.NET WebAPI, WCF)
- Ferramentas de controle de versão (TFS / GIT)
- DDD
- Banco de dados relacional (preferencialmente Oracle)
- ORMs (Entity Framework, Dapper)
- NodeJS
- Arquitetura em microserviços
- Banco de dados não relacional (Redis, MongoDB)
- Ferramenta de enfileiramento (preferencialmente RabbitMQ)

### **Diferencial:**

- Conhecimento no mercado financeiro

**Contrato:** CLT + benefícios padrões.

**Local de atuação:** Vila Olímpia - SP

_Interessou? Envie seu CV para marla.mello@mjv.com.br com o título "back end SP"_

### Labels

CLT
Alocado
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
