### ISSUE TITLE
[Remoto] Fullstack Developer @ GNAR

### ISSUE THREAD

**Issue by yuriploc** [backend-br/vagas#3229]
## Description

(Remote)

GNAR is a remote-first company that works mainly to improve heavy industries. You can learn more about our work by listening to [Code[ish] podcast](https://www.heroku.com/podcasts/codeish/88-monitoring-productivity-through-iot) or reading about some success stories on [Heroku](https://www.heroku.com/customers/gnar).

We're looking for a mid-level or senior Fullstack Engineer to be part of our team developing features and delivering improvements on both the backend and frontend of the project by proving simple yet performant interfaces and ensuring long term stability and scalability.

### What's my mission?
As a member of such a small team at GNAR (we’re just 6 people company-wide!), you’ll work closely with our product team in our biggest project.
We’re continuing to expand and build new features, to be implemented during the next 2 years, and we need someone with good experience to help us deliver them with quality. At the same time, we’ve been building this project for the past 2.5 years, and we have lots of opportunities to improve our stack.

### Who will I be working with?
You will be working closely with our engineers and our Head of Product.

### What do I need?
* React experience - you have front-end development experience using ES6. You have also worked with React and Redux.
* Node.js experience - you can use ORMs like Sequelize but also knows how to write raw SQL when needed.
* Excellent engineer - you understand and advocate for testing, analytics, observability and error tolerance.
* Product mindset - you can challenge product features, propose simpler implementation, and propose excellent technical decisions to improve user experience.

### What we work with

We believe everyone can learn on the job, that's why we won't require you to know everything.

* Nodejs (**required**)
* Koajs (bonus)
* Sequelize (bonus)
* Postgres (**required**)
* React (**required**)
* Redux (**required**)
* Redis (bonus)
* Kafka (bonus)

### Why join GNAR?
Work with talented & passionate people with diverse experiences and backgrounds (Physics, Psychology, Computer Science).
Feel your impact: GNAR is a small company, everything we do matters and your impact is critical.

### What do I get?
* :woman_technologist: 40h / week
* :dollar: US$24 to US$30 / h (based on experience)
* :beach_umbrella: 3 Weeks PTO (Paid Time Off)

### Interested? Send

* CV and/or Portfolio
* Cover letter
* :mailbox_with_mail: yuri@gnar.io with title: Fullstack Engineer
* visit us at [gnar.io](https://gnar.io)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

## Labels
* Remoto
* Exterior
* Inglês Fluente
* Pleno
* Sênior
* Nodejs
* PostgreSQL
* Full Time
* Full Stack

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by ealvarez968** [comment]
I'm interested, is this position still available

**Comment by ealvarez968** [comment]
I'm interested, is this position still available?

**Comment by yuriploc** [comment]
> I'm interested, is this position still available?

@ealvarez968 Yes, we'll keep it open until tomorrow.
