### ISSUE TITLE
[Lauro de Freitas - BA] Full-stack Developer na Sotero Tech

### ISSUE THREAD

**Issue by fxcosta** [backend-br/vagas#323]
# Descrição da Vaga
A Sotero Tech está em busca de um dev ou deva para contribuir na criação e manutenção dos diversos sistemas e soluções que são entregues a nossos clientes além dos nossos produtos.

Atuar em correções, melhorias nos projetos já existentes e novos projetos, com atenção especial na qualidade do código. Buscamos alguém que possa atuar como pessoa-chave para o início de novos projetos, participando desde o processo de arquitetura, análise, evolução até a produção.

Se você adora desafios, tem fome por aprendizado e gosta de ambientes descontraídos com foco em evolução constante, venha trabalhar conosco!

# Local de trabalho:
-Presencial em Lauro de Freitas - Bahia

# Benefícios
-Vale Alimentação
-Vale Transporte
-Salário à combinar

# Requisitos 
## Requisitos obrigatórios:
-Ensino superior cursando ou completo em sistema da informação e áreas afins;
-Sólidos conhecimentos em HTML e CSS utilizando boas práticas;
-Sólido conhecimento e experiência em PHP;
-Conhecimento e experiência com JavaScript (ES6+);
-Conhecimento em versionamento de projetos usando Git;;
-Conhecimento e experiência com banco de dados relacionais
-Clean code, orientação a objetos, SOLID;

## Diferenciais:
-Experiência e conhecimento com os frameworks PHP (Zend Framework, Laravel e/ou Symfony)
-Testes unitários
-CSS moderno com Flexbox e/ou Grid Layout
-Ferramentas do ecossistema JavaScript (React, Angular, npm, webpack, ESLint)

# Como se candidatar
Enviar CV, pretensão salarial e portfólio/Github (se tiver) para selecao@soterotech.com.br

# Labels
- PHP
- Javascript
- Presencial
- CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
