### ISSUE TITLE
[Blumenau - SC] Full-stack Developer na Senior Sistemas 

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#324]
### **Descrição da Vaga**
A empresa Senior Sistemas está em busca de um (a) dev para atuar no desenvolvimento de softwares de Gestão de Pessoas. 

Esse profissional será responsável por manter e evoluir implementações do produto HCM; Realizar revisão por pares dos artefatos de programação; interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes; Construir código com testes automatizados/unitários para garantir a qualidade. 

### **Local de trabalho**
Presencial em Blumenau (SC).

### **Benefícios** 
Vale   Transporte, Vale Alimentação/Refeição,  Auxílio Educação, Auxílio   Creche, Plano de Saúde, Plano Odontológico, Seguro de Vida, Programa de   Remuneração Variável (PLR), Plano de Previdência Complementar.

### **Requisitos**
Indispensável: Superior completo ou cursando Ciências da Computação, Sistemas da Informação ou áreas afins; Vivência em desenvolvimento de software; conhecimento em linguagem Java e em banco de dados PostgreSQL (Back-End); JavaScript, AngularJS, HTML5, CSS3, integrações com APIs REST (Front-End). 
Desejável: Vivência com desenvolvimento em ambiente Cloud; Vivência com Hibernate, JPA, Docker e vivência em desenvolvimento de sistemas para Gestão de Pessoas (RH - HCM).

### **Como se candidatar**
Se cadastrar no nosso site: www.senior.com.br/carreiras e se candidatar na vaga 3420.

### **Labels**

- Java
- Front End
- CLT
- Full
- Pleno
- Junior
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
