### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Java Pleno | Ciclic

### ISSUE THREAD

**Issue by aoliveiradias** [backend-br/vagas#325]
Você gosta de desafios? Tem mindset ágil ? Quer participar da criação de um produto novo e disruptivo? Quer evoluir com nosso time? Tem paciência com Padawans*?

Então, só vem!

Queremos um(a) Back End Pleno para fazer parte desse time e que venha com muita vontade de crescer e aprender!

Quais são os conhecimentos e competências desejáveis?

Conhecimento em Java, OOP e Docker.

Spring.

Testes e boas práticas de programação (TDD,BDD, SOLID e Design Patterns).

Experiência em metodologias ágeis (Scrum. Kanban, XP etc).

Gostar de compartilhar conhecimentos (olha o Padawan aí novamente!)

Boa capacidade em resoluções de problemas.

Atitude positiva e construtiva!

O que oferecemos?

-Salário compatível ao mercado + benefícios (Vale Alimentação, Vale Refeição, Plano de Saúde, Plano Odontológico, Previdência Privada, Bônus e Gympass)

Horário flexível e home office
Vem que essa oportunidade é única! Vem pra Ciclic!

Envie email para: aline@ciclic.com.br

**Comment by jorgelimafeitosa** [comment]
Olá Aline, tudo bem? Enviei meu currículo para o e-mail, espero que goste! :D

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
