### ISSUE TITLE
[São Paulo] Back-End Developer na McCANN Health 

### ISSUE THREAD

**Issue by tiagords** [backend-br/vagas#328]
## Descrição da vaga

Contratação PJ desenvolvedor(a) para vaga de Back-End.

## Local

Rua Loefgren 2527 
04040-033 - SP 
Vila Clementino  (Metro Santa Cruz)
São Paulo

## Benefícios

- VR

## Requisitos

**Obrigatórios:**
- PHP7 (Intermediário)
- MySQL
- Laravel
- Wordpress

**Desejáveis:**
- Conhecimentos em Git
- Conhecimentos em Angular ou Vue.js

**Diferenciais:**
- Joomla

## Contratação

PJ

## Como se candidatar

Por favor envie um email para alvaro.silva@mccannhealth.com.br e tiago.rodrigues@mccannhealth.com.br com seu CV em anexo e pretensão salarial.

## Labels

- Semi Presencial
- PJ
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
