### ISSUE TITLE
[REMOTO] Back-End Developer na Citar Tech

### ISSUE THREAD

**Issue by meneguite** [backend-br/vagas#329]
![Citar.tech](https://s3-sa-east-1.amazonaws.com/citar.tech/assets/developers/dev-citar-tech.png)

### O que nós buscamos
- Responsável por desenvolver, testar e documentar rotinas;
- Atuar em implementações, melhorias de performance e integrações;
- Desenvolver códigos bem estruturados utilizando boas práticas de programação;
- Realizar revisão por pares dos artefatos de programação;
- Interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes;
- Construir código com testes automatizados/unitários para garantir a qualidade.

## Local
Remoto

## Requisitos:
- NodeJs com Javascript ES6;
- Domínio de testes unitários/integração;
- MySQL;
- MongoDB ou DynamoDB;
- Rest APIs;
- Conhecimento básico em modelagem de banco de dados relacionais e não relacionais;
- Noções básicas de scrum e metodologias ágeis;
- Dominio do Git para versionamento de projetos;

## Diferenciais:
- PHP;
- Microservices;
- Experiência na utilização do docker;
- Experiência em tecnologias de IA ou machine learning;
- Linux;
- AWS;

## Contratação

CLT ou PJ preferencialmente PJ para candidatos fora de São Paulo.

## Como se candidatar

Por favor envie um email para rh.dev@grupocitar.com.br com seu CV anexado ou link do linkedin - enviar no assunto: Vaga Backend NodeJs

## Labels

- Remoto - Total
- CLT ou PJ
- Pleno
- Sênior

**Comment by wesleymreng7** [comment]
Enviado!

**Comment by hc3** [comment]
enviado.

**Comment by abelclopes** [comment]
enviado!

**Comment by indhio** [comment]
Enviado.

**Comment by meneguite** [comment]
Boa noite Srs.. venho agradecer a todos que se inscreveram em nosso processo seletivo. Tivemos acesso a ótimos desenvolvedores e conseguimos completar nossa equipe por hora. É bem provável que em um futuro próximo precisemos de novos devs.. mas por hora nosso processo seletivo está pausado.
