### ISSUE TITLE
[São Paulo] Backend developer na Carteira Online

### ISSUE THREAD

**Issue by kevenjesus** [backend-br/vagas#33]
## Descrição

Carteira online é ums startup fintech com um projeto FODEREIRO que consiste em educar seus usuarios financeiramente para melhor investir a grana no momento certo ou periodo certo, estão montando seu time agora (melhor fase de entrar em um projeto).

A principio tudo indica que o core será em golang, mas terá microservices em outras linguagens então linguagem nao deve ser um problema para o dev :) 

## Local
Presencial: R. Prof. Atílio Innocenti, 165 - Vila Nova Conceição (Wework faria lima)

## Pré-requisitos

- Lógica boa
- Analise de requisitos
- Terminal e git
- Noções de infra
- Banco de dados

## Diferenciais

- Experiência com várias linguagens

## Beneficios

- Vale transporte
- Vale Refeição
- Chopp no local

## Salário e tipos de contratação
Pleno: R$ 7.000 PJ negociavel (até mesmo os beneficos)

Devs hormonizados de tecnologia e que nao sejam preguiçosos, bracinho de jacaré me enviar um email com github, linkedin oque tiver para falecom@keven.com.br

**Comment by carloshenriqueribeiro** [comment]
@kevenjesus e-mail enviado! Abraço ;)

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
