### ISSUE TITLE
[Brasília - DF] Desenvolvedor(a) Ruby | PDVend

### ISSUE THREAD

**Issue by pdvend** [backend-br/vagas#330]
## Descrição da vaga

Procuramos um(a) profissional de desenvolvimento Ruby Pleno/Sênior para compor o time de produto Plug and Play. Nosso time é composto por pessoas proativas, auto-didatas e com um senso de dono acima da média, por isso procuramos um(a) desenvolvedor(a) que seja como a gente.

## Local

Escritório de Águas Claras (Brasília)/DF, que fica no Edifício e-Business na Av. Pau Brasil, Lote 6. 
Pertinho da Estação de Metrô de Águas Claras.

## Benefícios

- ambiente descontraído, competitivo e desafiador
- autonomia e liberdade
- programa de feedback e coachings
- férias remuneradas para PJ

## Requisitos

Obrigatórios
- 3+ anos de experiência com Ruby
- Ruby on Rails
- MongoDB
- Arquitetura REST
- Heroku e AWS
- Testes Unitários

Desejáveis
- Gostar de times pequenos com autogestão
- Autonomia e responsabilidade acima da média
- Gostar de desafios 
- Comunicar-se bem

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A PDVend é uma empresa de produtos para o varejo, focada em pequenas e médios negócios oferecendo para o mercado soluções simples e eficientes utilizando-se de tecnologias modernas. 

Seu principal produto é o PDVend Plug and Play que é um aplicativo mobile (Android), onde o cliente consegue realizar vendas, gerenciar estoque, emitir notas e fazer gestão de seu negócio.

Veja nosso Culture Code: https://drive.google.com/file/d/1ewy7qM-8znVTYVRmocfZgqaRzETN7320/view

## Como se candidatar

Interessados enviar CV para waldyr@pdvend.com.br
Site: https://www.pdvend.com.br/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
