### ISSUE TITLE
[Florianópolis] Estágio Full Stack Developer na Conexão Solar

### ISSUE THREAD

**Issue by dandeastrigi** [backend-br/vagas#3302]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa que tem como objetivo impulsionar o mercado de energia fotovoltaica no Brasil.

## Descrição da vaga

Você vai auxiliar no desenvolvimento de soluções web utilizando as tecnologias Angular, GoLang e MongoDB.

## Local

Remoto durante a pandemia, flexível após ou Escritório, [SC], [Florianópolis], [João Paulo]

## Requisitos

**Obrigatórios:**
Completar o desafio neste [link](https://github.com/Conexao-Solar/challenge-user-crud)

**Desejáveis:**
- conhecimentos GoLang
- conhecimentos em JavaScript
- conhecimentos em MongoDB

**Diferenciais:**
- projetos opensource

**Diferenciais:**
- trabalho remoto

## Contratação

Estágio

## Como se candidatar

Por favor envie um email para dande.astrigi@gmail com o link para o seu desafio - enviar no assunto: Vaga Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: dande.astrigi@gmail.com

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by lucascerci** [comment]
fullstack nivel jr? tem a ver isso produção?

**Comment by dandeastrigi** [comment]
> fullstack nivel jr? tem a ver isso produção?

Tem sim meu caro, a pessoa que preencher a vaga vai ter contato direto tanto com frontend quanto backend, além de utilizar protocolos comuns para desenvolvimento web, por se tratar de uma vaga para estágio classifiquei como jr, pois há possibilidade de efetivação após estágio.

**Comment by lucascerci** [comment]
Você está cobrando um teste para um estágio, não concordo com esse tipo de approach mas tudo bem, cada um sabe o que faz, né?

**Comment by dandeastrigi** [comment]
Por enquanto estamos encerrando o processo por aqui, obrigado a todos!
