### ISSUE TITLE
[São Paulo] Back-End Developer na Yapoli

### ISSUE THREAD

**Issue by Yapoli** [backend-br/vagas#331]
Programador PHP Senior

### Descrição da vaga

A Yapoli está em busca de um desenvolvedor PHP sênior presencial com foco em backend (criação e consumo de webservices / modelagem de dados / escalabilidade / segurança / processamento de imagens e vídeos).

### Local

Jardim Paulista (ao lado da estação de Metrô Oscar Freire da Linha Amarela).

### Requisitos

**Obrigatórios**

- PHP 7+ (Orientação a Objetos / Design Patterns)
- MVC
- NGinx
- AWS - EC2 / S3 / Lambda
- MySql 
- MongoDB
- Agile/Scrum
- Desenvolvimento de Web Services
- Git

**Diferenciais**

- AWS - Elastic Transcoder / Rekognition / Cloud Front
- Google Cloud - Vision / Translation / Speech / Video intelligence
- Conhecimento em Zend Framework ou outro Framework de mercado (Symfony, Laravel)
- TDD

### Contratação

PJ à combinar

### Nossa empresa

A Yapoli é uma empresa de tecnologia baseada em São Paulo com foco em gerenciamento, otimização e distribuição de assets digitais através de AI e machine learning.

### Como se candidatar

Interessados enviar currículo com pretensão salarial para adalberto@yapoli.com com assunto: #Programador PHP Sr#

Currículos fora do perfil desejado serão excluídos.

### Labels

- Senior
- PJ
- PHP
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
