### ISSUE TITLE
[Osasco] Back-end Developer @ Mercado Pago (Remoto durante o covid)

### ISSUE THREAD

**Issue by freddybrasileiro** [backend-br/vagas#3312]
> Vaga Remota durante a pandemia

## Mercado Pago

Empresa mais valiosa da América Latina. Eleita a oitava melhor empresa do mundo para se trabalhar.

## Descrição da vaga

Nosso objetivo em Checkout é criar soluções simples, escaláveis, tolerantes a falhas e mensuráveis, para suportar milhares de requests por minuto. Aspiramos ter um uptime de 99.9% e hoje estamos muito perto de alcançar.

Nosso Checkout Web é o que faz a junção entre o ecossistema do Mercado Pago e os usuários que querem comprar e vender utilizando Mercado Envios, Mercado Pontos e Mercado Créditos.

No momento, estamos trabalhando 100% remoto devido ao contexto do COVID-19. Mesmo assim, continuamos tendo apoio para enfrentar da melhor maneira nossos desafios pessoais e profissionais.

## Local

Osasco

## Requisitos

Procuramos um desenvolvedor com experiência sólida, autonomia, forte conhecimento técnico e com grande capacidade analítica para enfrentar os desafios que envolvem trabalhar em um projeto para milhões de usuários.

## Contratação

CLT, presencial (pós pandemia)

## Como se candidatar

Entra em contato comigo via LinkedIn [https://www.linkedin.com/in/freddybrasileiro/](https://www.linkedin.com/in/freddybrasileiro/)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by guilhermeoa07** [comment]
Possibilidade de ser remoto pós pandemia?
