### ISSUE TITLE
[São Paulo] Back-End Developer no Grupo KRS

### ISSUE THREAD

**Issue by lBrunol** [backend-br/vagas#333]
## Descrição da vaga

Tá a fim de criar e desenvolver para diversos nichos, é proativo, trabalha bem em equipe e quer entrar em contato com várias tecnologias?
Então mande o seu currículo para nós e venha bater um papo conosco.

## Atividades

Procuramos um desenvolvedor para atuar na resolução de bugs, implantação de novas features em projetos que já estão em produção e no desenvolvimento de novos projetos.

## Local

Rua Diamantina, 538 - Vila Maria, São Paulo - SP
**Importante: O candidato deve residir na grande São Paulo ou próximo.**

## Benefícios

- VT
- VR
- Projeto qualidade de vida
- Convênio médico e odontológico

## Requisitos

**Obrigatórios:**

- Programar em uma ou mais linguagens de servidor como PHP, Golang, Nodejs ou C#
- Conhecimento de algum banco de dados (MySQL ou PostgreSQL)
- Conhecimento de GIT
- Experiência com desenvolvimento >= 2 anos
- Vontade de aprender e capacidade para enfrentar desafios

**Desejáveis:**

- Conhecimento em RESTFul API
- Conhecimento em HTML, CSS, Javascript
- Conhecimento em ambiente Linux

## Dica!

- Pode nos enviar link do GitHub, Bitbucket, projetos (mesmo aquele básico, feito só para testar), LinkedIn, blog ou qualquer complemento, isso vale bastante na hora da avaliação.

## Contratação

Regime CLT.
Faixa salarial - R$2.000,00 a R$4.000,00.

## Nossa empresa

[http://www.grupokrs.com.br](http://www.grupokrs.com.br)

## Como se candidatar

Por favor envie um email para curriculos.ti@grupokrs.com.br com seu CV anexado e links de projetos, caso tenha - enviar no assunto: Vaga Back-end – Back-end Brasil.

## Labels
- CLT
- Alocado
- Júnior
- Pleno

**Comment by guilhermeoa07** [comment]
Experiência obrigatória para Júnior também?

**Comment by lBrunol** [comment]
Olá @guilhermeoa07 

A nossa é ideia é contratar alguém que já tenha experiência com desenvolvimento, não necessariamente um trabalho formal, contamos como experiência projetos ou freela, a ideia é alguém que esteja preparado para lidar com as demandas dos projetos de forma mais independente. Se você acha que se encaixa nestes parâmetros, envie seu currículo para análise.

Qualquer dúvida estou a disposição.
