### ISSUE TITLE
[São Paulo] Python Developer na Luizalabs

### ISSUE THREAD

**Issue by ogustavomeira** [backend-br/vagas#334]
### Descrição da Vaga
Nossa Empresa, (a carismática Magazine Luiza), é muito sólida, já tem 60 anos e presença nacional, mas cultiva um fit jovem e um gosto pelo jeitão das startups, que está tornando-a uma empresa digital com a tecnologia no board e na estratégia.
Procuramos pessoas para nos ajudarem a construir ferramentas que tornem o Magazine Luiza o marketplace mais rentável e simples de operar do mercado.

### Atividades
Fazendo parte da Tribo Canais Digitais do Luizalabs, você será responsável pela evolução e manutenção do Squad Checkout do Magazine Luiza que atende diversos canais de venda, com espaço para inovação, colaboração e aprendizado constante.

### Requisitos
- Python
- MySQL, SQL
- Modelagem de APIs: desenvolvimento e consumo (REST)
- AWS (EC2, SQS, RDS, outros)
- Testes Automatizados (unitário e integrado)
- Controle de versão de software (GIT)
- Documentação de código e serviços

### Local
Rua Maria Prestes Maia, 300 - Luizalabs / São Paulo-SP

### Benefícios

- Vale Transporte
- Vale Refeição
- Seguro de Vida
- Previdência Privada
- Assist. Odontológica
- Assist. Médica
- PLR

### Labels
CLT 
Pleno
Sênior
Python

### Inscreva-se em
Acesse ao link e aplique na vaga com seus dados! Nosso time de Recrutamento entrará em contato!
https://99jobs.com/luizalabs/jobs/15604-desenvolvedor-a-backend-python-senior

**Comment by joaopdto** [comment]
Sem vagas para Estágio?

**Comment by ogustavomeira** [comment]
Estamos apenas com vagas para Pleno e Sênior por enquanto :(

**Comment by joaopdto** [comment]
Ok, quem sabem em uma próxima, obrigado pela resposta.
