### ISSUE TITLE
[São Paulo] Desenvolvedor PHP na WeJam Digital

### ISSUE THREAD

**Issue by crispossa** [backend-br/vagas#335]
### Descrição
Vaga para desenvolvedor PHP para dar manutenção em projetos que estão ativos, desenvolver novas features e apoiar no desenvolvimento de novos projetos.
A maioria dos projetos é em PHP mas utilizamos também outras linguagens como Node e Python.

### Skills necessárias
- PHP 7+
- Laravel 5.1+
- MySQL intermediário (Procedures, Functions, Joins, Views)
- Noções dos principais Design Patterns
- Git
- Lógica aplicada a solução de problemas
- HTML Básico
- JS Básico

### Skills desejáveis
Pelo menos 1 delas é esperado que vc domine.
- NodeJS
- Python
- Crawling
- MongoDB ou outro banco de dados não relacional
- Graph DB (Neo4J ou ArangoDB)
- Excel (Macros e Fórmulas)
- DevOps
- PostgreSQL avançado

### Contratação
- Alocado
- PJ (Pode ser MEI)
- R$ 2 a 3k (dependendo do nível)
- Início imediato

### Benefícios
- 13º salário
- Férias remuneradas

### Como se candidatar?
Envie um e-mail para queroserdev@wejam.email com pretensão salarial, link para github e apresentação.

### Sobre a WeJam
Somos uma agência com DNA digital que desenvolve projetos de alta qualidade e com grande impacto em negócios, desde sites institucionais até plataformas de treinamento e gamification.

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.

Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.

Venha fazer parte da nossa equipe!

We Ad! We Rock! We Jam!

Tags: PJ, PHP, Presencial, Junior, Senior

**Comment by ghost** [comment]
kd email mah?

**Comment by crispossa** [comment]
@Rxon7 adicionei ao texto da vaga. queroserdev@wejam.email
