### ISSUE TITLE
[Espirito Santo/Remoto] .NET C# Developer @ Drivin Sistemas

### ISSUE THREAD

**Issue by pvictorlv** [backend-br/vagas#3360]
Oportunidade PJ em uma empresa nacional, atuando em diversos estados.

## Local

Alocação completamente remota.

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento web com Asp.Net core
- Conhecimento em EntityFramework ou outras ORMs

**Desejáveis:**
- Conhecimentos em JQuery
- Conhecimentos em MySQL

**Diferenciais:**
- Conhecimento de PHP ou Node

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para paulo@teorico.com.br com seu CV anexado - enviar no assunto: Vaga .Net

#### Nível
- Júnior
- Pleno

#### Período
- Full time
- Part time

**Comment by RobsonBrazJunior** [comment]
Currículo enviado.
