### ISSUE TITLE
[Ribeirão Preto] Back-End JAVA Sênior na [Beblue]

### ISSUE THREAD

**Issue by TatianeBeblue** [backend-br/vagas#337]
**Vaga - Desenvolvedor JAVA Sênior - Ribeirão Preto/SP**

Responsabilidades: Desenvolvedor responsável pela evolução da plataforma PDV da Beblue. Isso envolve: decisões arquiteturais evoluindo a plataforma em resiliência e escalabilidade, programação de funcionalidades, refatorações, correções de bugs, coaching e liderança técnica dos programadores Java da equipe.

**Requisitos (obrigatório):**
Java 8
Ecosistema Spring: Spring Boot, Actuator, Consul Discovery, Feign, Sleuth, Spring Cloud Stream Rabbit, JDBC, JPA, Hibernate, Web, Spring Cloud AWS Autoconfigure, Liquibase
PostgreSQL
Redis
RabbitMQ
Docker
Git
Experiência desenvolvendo microserviços Java em containers na infraestrutura AWS
Bons fundamentos computacionais

**Requisitos (nice to have):**
1.	Experiência com continuous deployment (Bitbucket Pipelines, Jenkins, …)
2.	Experiência com ferramentas de monitoria como Sentry e New Relic
3.	Experiência desenvolvendo coberturas de testes automatizados

**Interessados, por gentileza encaminhar cv para: tatiane.lima@beblue.com.br e mencione no assunto GIT - JAVA** 

**Sobre o Beblue:** O Beblue é uma fintech (junção de finance + technology) nacional de meios pagamentos que devolve parte do dinheiro gasto nos estabelecimentos credenciados em “dinheiro virtual” na conta do usuário.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
