### ISSUE TITLE
[BELO HORIZONTE MG ] Back-end Developer @RHTECH

### ISSUE THREAD

**Issue by ITSimara** [backend-br/vagas#3377]
==================================================
-->
VAGAS URGENTES - TODOS OS NÍVEIS

> Vaga Remota durante a pandemia - POS PANDEMIA MODELO HIBRIDO

## Nossa empresa

Somos uma Consultoria focada em uma revolução e estamos procurando loucos por Tech é você?

## Descrição da vaga

Projeto de expansão! C# .NET

## Local

Escritório fica em BH capital do pão de queijo!

## Requisitos

**Obrigatórios:**
Estamos montando nosso SQUAD e queremos perfis de todos os níveis.

**Desejáveis:**
Conhecimento em  Angular

**Diferenciais:**
Ser apaixonado(A) por desafios!

## Contratação

CLT

## Como se candidatar

Por favor envie um email para: recrutamento.rhtech@gmail.com

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by deyvisonborges** [comment]
Não possuo conhecimentos em Angular (mas posso aprender em rapidamente).
No momento posso contribuir com outras tecnologias no front, aceitam mesmo assim? ;)

**Comment by ITSimara** [comment]
@deeborges por favor me encaminhe o seu CV vamos avaliar com certeza obrigada pelo retorno! recrutamento.rhtech@gmail.com

**Comment by ITSimara** [comment]
VAGA FECHADA!
