### ISSUE TITLE
[São Paulo] Back-End Developer NodeJS Pleno [Loopix]

### ISSUE THREAD

**Issue by thiagoaires** [backend-br/vagas#339]
**Obrigatório:**

 Mínimo de 2 anos de experiência com Node.js
 Dominío Javascript/Es5/Es6

 Experiencia com:
 - Meios de pagamento
 - Express
 - Websocket
 - desenvolvimento de RestAPI
 - MySQL
 - Webpack
 - Autenticação (JWT/OAuth)

**Diferenciais:**

 - Teste unitário
 - base de dados não relacional
 - PHP

Horário flexível

enviar CV para vagas@loopix.com.br

Labels: 
Node.JS Pleno SP PJ Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
