### ISSUE TITLE
[São Paulo]  Desenvolvedor Back-end Sr. (.net,node) na Octadesk

### ISSUE THREAD

**Issue by houstondapaz** [backend-br/vagas#342]
O Octadesk é uma startup de atendimento que está crescendo muito nos últimos anos.
300% em 2017 e com a mesma meta para 2018!

E com isso precisamos de mais pessoas para dar conta de toda essa evolução.
Em dois anos mudamos nosso back-end de monólito .net framework com deploy no Azure, para muitos micro-serviços (muitos mesmo), em node e .net core, todos em docker no Kubernetes do GCloud.

Estamos sempre evoluindo o produto, buscando sempre a estratégia de API First, de serviços enxutos e simples.

Se for para falar tudo vou escrever uma bíblia aqui.
Se vc quer sempre ter uns desafios maneiros, ter a liberdade de buscar sempre a melhor maneira de implementar algo novo em um nível de entrega alta, cola com nois!

A gente paga bem e quando batemos a meta sempre tem um a mais, ano passado fomos para Disney (a empresa toda) e esse ano vamos para o Vale do Silício.

Entra em contato por aqui!
https://octadesk.revelo.com.br/openings/desenvolvedor-back-end-sr?locale=pt-BR

#pas

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
