### ISSUE TITLE
[São Carlos/SP] Backend Developer PHP na Arquivei

### ISSUE THREAD

**Issue by kkinderr** [backend-br/vagas#343]
**Arquivei**, a Brazilian startup, is looking for a Back End Engineer with great experience. Arquivei is an online platform that empowers companies with smart data from fiscal documents to fetch & analysis, offering process optimization through different company areas, customized reports, and Brazilian law compliance. Founded in São Carlos, the Brazilian capital of Technology, Arquivei uses the valuable data available in fiscal documents to deliver reliable information to its clients at low costs.

[Apply here](https://arquivei.applytojob.com/apply/fRTjQ2tIIU/Back-End-Engineer)

**Desired Skills and Experience**

**You:**

- Have a good grasp of the software architecture concepts
- Have extensive knowledge on web development
- Have knowledge about microservices architecture
- Have real-world experience designing and implementing algorithms to tackle a hard problem
- Know how to architect, develop and deploy the solution you're planning to use. 
- Are a team player, we foster a culture of collaboration and sharing​

**​​​​​​We provide:**

- Fun, laid-back environment in a fast-paced Startup.
- Contract as CLT
- Open-bar kitchen with coffee, fruits, coffee, candy and coffee. Breakfast at the office every day. Did we mention coffee?
- Feedback and brainstorming directly with the founders. No bureaucracy. No bullshit.
- Competitive compensation based on your experience.
- Choice of tools
 
**Our current stack:**

- High use of AWS infrastructure
- PostgreSQL for relational storage
- Redis in a variety of roles
- Apache serving main PHP App (using MVC Framework)
- And a bunch of other stuff, let's not spoil the surprise

[Apply here](https://arquivei.applytojob.com/apply/fRTjQ2tIIU/Back-End-Engineer)

Labels

- PHP
- Senior
- CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
