### ISSUE TITLE
(Portugal) - NodeJS Developer

### ISSUE THREAD

**Issue by FernandaMorais** [backend-br/vagas#344]
Projetos em diferentes sectores de atividade com recurso a ReactJS, React Native, JavaScript, Angular entre outras.
Projetos a ser desenvolvidos em Portugal e que permitem contato com outras localizações na Europa.

## Local

Portugal: Lisboa e Porto

## Benefícios

- Plano de saúde
- Apoio no processo de visto de trabalho
- Formação
- Outros benefícios em vigor na Aubay

#### Diferenciais

- Almoço grátis todas as sextas
- Armário das bolachas sempre cheio
- frigobar sempre cheio :P

## Requisitos

**Obrigatórios:**
- Experiência profissional com NodeJS
- Experiência com JAVA - preferencial 
- Fluência na língua Inglesa - falado e escrito

## Contratação

PJ a combinar
CLT após autorização de residência
Apoio nas questões legais

## Nossa empresa

A Aubay é uma multinacional Francesa a trabalhar em Portugal há mais de 10 anos.
Fiquei a saber mais em www.aubay.pt. 

## Como se candidatar

Por favor envie um email para fmorais@aubay.com com seu CV anexado - enviar no assunto: Front end na Aubay.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
