### ISSUE TITLE
[Curitiba] PHP Full Stack Sr na MadeiraMadeira

### ISSUE THREAD

**Issue by rafaelrac** [backend-br/vagas#348]
## Descrição da vaga

Adaptar-se rapidamente ao ambiente startup, trabalhar em um time de alta performance, disruptivo e qualificado, entregando o melhor em tecnologia e experiência do usuário.
Atitudes como Resiliência, Paixão pelo o que faz, Empreendedorismo, Colaboração, Senso de Dono do Negócio são importantes em nossa cultura de alta performance.

## Local

Escritório, Curitiba - PR - Centro

## Benefícios

- Vale Refeição;
- Vale Alimentação;
- Vale Transporte;
- Plano de Saúde;
- Plano Odontológico;

#### Diferenciais

- GymPass;
- Quitanda com frutas fresquinhas;
- Estacionamento para bikes;
- Desconto em restaurantes locais;
- Assistencia Psicológica, Jurídica e Financeira;
- Convênio com diversas universidades e parcerias com cursos;
- Local de descanso com videogame, pebolim e redes ;D E MUITO MAIS!

## Requisitos

**Obrigatórios:**

- Mínimo 6 anos como desenvolvedor em PHP, Bootstrap, JQuery/Javascript, MySQL e Rest API's.

**Desejáveis:**
- Habilidades com AWS, twig, Shell Scripting e laravel
- Inglês: intermediário/avançado.

## Contratação

CLT

## Nossa empresa

[https://www.madeiramadeira.com.br/sobre](https://www.madeiramadeira.com.br/sobre)

## Como se candidatar

[Candidate-se clicando aqui, é rápido](https://signup.kenoby.com/#/candidatos/me?position=5ae66854a207bc35fbefa8dc&tenant=5aabe058c740f7051814e3ee&jobsite=madeiramadeira&positionName=Desenvolvedor%20Full%20Stack%20Sr&applicantSource=&utm_source=)

## Labels
- PHP
- Full Stack
- Sr
- Senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
