### ISSUE TITLE
[São Paulo] NodeJS Developer [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#349]
**Descrição da vaga**
- Integrará uma equipe de desenvolvedores em projeto de migração de sistema de uma grande seguradora, participando de um projeto tecnologicamente inovador neste cenário!

**Local**
- No escritório de São Paulo - Zona Sul- próximo ao Morumbi Shopping.

**Benefícios**
- Assistência Médica
- Assistência odontológica
- VT
- VR de R$ 24,30/dia
- Auxílio creche
- PLR

**Diferenciais**
- Comitê de treinamentos
- Campeonatos (futebol, games, pocker)
- Café da manhã toda sexta-feira
- Ginástica laboral às quartas-feiras

**Requisitos Obrigatórios:**
- Ensino superior completo;
- Sólidos conhecimentos em Javascript e Node JS;
- Vivência com ferramentas de versionamento de código, preferencialmente Git;
- Conhecimento em Angular (JS ou 2+). 

**Diferenciais:**
- Conhecimento em ​design, UX e mobile. ​

**Contratação**
CLT Full

**Nossa empresa**
- A Confitec é uma empresa de TI especialista em atender o mercado de Seguros.

**Como se candidatar**
- Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga "NodeJS".
Envie também sua pretensão salarial (CLT).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
