### ISSUE TITLE
[São Paulo] Backend PHP na Ufirst digital

### ISSUE THREAD

**Issue by kevenjesus** [backend-br/vagas#35]
## Descrição da vaga
Startup voltada para o desenvolvimento e automação de estratégias de Marketing Digital de Performance, procura desenvolvedor php junior.

## Local
Presencial: Serra de Botucatu, 880 4° andar, Tatuapé/SP

## Necessário
Analise de requisitos
POO e MVC
Banco de dados
Noções de infra
Git

## Diferenciais
Laravel
Design pattern
Linha de comando

## Salarios e tipos de contratação
CLT: R$ 3.000
PJ: R$ 4.000
Ambos VT e VR

## Obs
CEO e CTO retardis total... zueira sem limites.

Interessados me enviar email falecom@keven.com.br

**Comment by praganavictor** [comment]
Tão perto da minha casa :heart: 
ja mandei email.

**Comment by lucassantos61** [comment]
Vaga ainda está aberta ?

**Comment by kevenjesus** [comment]
Opa Lucas ainda tem interesse?

**Comment by provivencia** [comment]
Ah se fosse remoto ...

**Comment by lucassantos61** [comment]
@kevenjesus  tenho sim , cara vou preparar meu curriculo e te mandar então

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
