### ISSUE TITLE
[São Paulo] Arquiteto de Sistemas .NET [LIZA] 

### ISSUE THREAD

**Issue by paolamunaro** [backend-br/vagas#350]
Arquiteto de Sistemas .NET (1)

Local de Trabalho: Pinheiros

Perfil
Profissional com perfil de liderança, que saiba interagir com os principais usuários do sistema, goste de trabalhar em ambiente colaborativo e descontraído, com foco nas entregas e no valor agregado.

Conhecimentos Obrigatórios

-Linguagem de programação
C#, MVC, AngularJS, NodeJS, HTML5, CSS3, SQL Server, MongoDB, AWS, Azure, TFS e GitHub

-Metodologia
Ter sólidos conhecimentos de SCRUM e KANBAN

-Conhecimentos Desejáveis
Tecnologias: ReactJS, .NET Core, Python, Cassandra, MemCached

Conhecimento de Squad e Design Thinking

**Comment by Kirmayrtomaz** [comment]
Essa vaga, precisa de mais detalhes?
foi colocado linguagens de programacao com varios outros temas. 

Conhecimento em cloud


AWS e AZURE

Conhecimento de git e Gitflow
Github

Conhecimentos em Banco de Dados relacionais
SQL Server


o que acha?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
