### ISSUE TITLE
[São Paulo] Analista Programador .NET Sr [LIZA] 

### ISSUE THREAD

**Issue by paolamunaro** [backend-br/vagas#351]
Analista Programador .NET Sr

Local de Trabalho: Pinheiros

Perfil
Possuir grande experiência em desenvolvimento web, que goste de trabalhar em ambiente colaborativo e descontraído, com foco nas entregas e no valor agregado.

Conhecimentos Obrigatórios

-Linguagem de programação
C#, MVC, AngularJS, NodeJS, HTML5, CSS3, SQL Server, MongoDB, AWS, Azure, TFS e GitHub

-Metodologia
Ter sólidos conhecimentos de SCRUM e KANBAN

-Conhecimentos Desejáveis
Tecnologias: ReactJS, .NET Core, Python, Cassandra, MemCached

Conhecimento de Squad e Design Thinking

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
