### ISSUE TITLE
[Rio de Janeiro] Back-End Developer Python (Pleno) @Atitude

### ISSUE THREAD

**Issue by EduFinxi** [backend-br/vagas#3519]
> Vaga Remota

## Nossa empresa

Somos uma empresa formada por um time de muita dedicação e atitude! Facilitamos a realização do sonho da casa própria, de forma ágil e eficiente, sem complicações nem dificuldades excessivas para a conquista do imóvel próprio. Servimos de ponte entre a construtora civil e o banco. Praticamos uma gestão profissional de forma a maximizar os resultados de nossos clientes na contratação de financiamento imobiliário e no trâmite de processos cartoriais. Para otimizar nossos processos, temos uma equipe de alta performance e utilizamos de recursos tecnológicos e inovadores.

## Descrição da vaga

Você será responsável por coordenar a equipe de desenvolvimento durante o processo de planejamento de um novo sistema e desenvolvimento do backend do mesmo.
Terá um papel de liderança, convivendo diretamente com os sócios do projeto para ajudar a elencar as prioridades e esclarecer os desafios técnicos que encontraremos no dia a dia e atuará como o principal desenvolvedor de backend do time.
Também como parte de seu papel de liderança, precisará coordenar o time como um Scrum Master do projeto para manter o processo de desenvolvimento rodando de forma sustentável, eficiente e eficaz.

## Local

Remoto. 

## Requisitos

**Obrigatórios:**
-Ter participado do início ao fim de pelo menos um projeto de desenvolvimento de software
-Domínio de Python e Django
-Conhecimento em design e arquitetura de software (Sistemas Web, Programação Orientada a Objetos, Clean Code, Design Patterns)
-Conhecimento de base de dados relacionais
-Conhecimentos de escrita e consumo de serviços (REST)

**Desejáveis:**
-Conhecimento de escrita de testes automatizados
-Experiência com Docker
-Experiência com AWS ou Google Cloud Platform
-Experiência com metodologias de desenvolvimento ágil

## Benefícios

**Diferenciais:**
Disponibilizamos equipamentos para o trabalho em Home Office

## Contratação

Contratação PJ
Pagamento mensal: R$ 7.000,00 a R$ 8.000,00

## Como se candidatar
https://comunidadefinxi.gupy.io/jobs/490167

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: eduardo.lazera.finxi@gmail.com

## Labels
Python, Django, Rest, Remoto, Docker

#### Nível
- Pleno

**Comment by xspager** [comment]
Essa vaga ainda está aberta?
