### ISSUE TITLE
[São Paulo] .Net Developer [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#352]
**Descrição da vaga**
- Fará parte da equipe de desenvolvedores de sistemas web e mobile voltados ao mercado de Seguros. 
*Será responsável por Pesquisa e Desenvolvimento de novas funcionalidades e tecnologias.

 **Local**
- No Escritório de São Paulo - ao lado do Morumbi Shopping.

**Benefícios**
- Assistência Médica
- Assistência Odonto
- VR de R$ 24,30/dia
- VT
- PLR
- Auxílio creche

**Diferenciais**
- Café da manhã toda sexta-feira
- Ginástica laboral às quartas
- Campeonatos (Pocker, Futebol, Games, etc)

**Requisitos Obrigatórios:**
- Ensino superior completo. 
- Vivência em .Net, WebAPI, DDD, NodeJS, Angular 2+, tecnologias Mobile (preferencialmente, Ionic). 
- Importante: entusiasta de estudos e aplicações de novas tecnologias. 

**Desejáveis:**
- Desejável conhecimento em React, MongoDB, entre outras tecnologias. 

**Contratação**
- CLT Full

**Nossa empresa**
- A Confitec é uma empresa de TI especializada no mercado de Seguros.

**Como se candidatar**
Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga P&D

Por favor, envie também sua pretensão salarial CLT.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
