### ISSUE TITLE
[Remoto] Back-end Developer Python@ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#3520]
## Descrição da vaga

Desenvolvimentos utilizando Python.

## Local

Local de trabalho: Remoto (Horário comercial)

## Requisitos

Experiência em desenvolvimento Python com foco em soluções e arquitetura de dados;
Experiência em banco de dados SQL ou NoSQL;
Inglês intermediário.
Experiência no desenvolvimento de soluções de big data em provedores de nuvem (Google, AWS ou Azur): Spark, Scala, Hadoop, Cassandra, MongoDB ou serviços ou tecnologias equivalentes.

## Contratação

4 a 5 meses
CLT ou PJ

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de salarial ou taxa/hora - enviar no assunto: Vaga no GITHUB - Python Remoto

## Labels

- 🏢 Horário comercial
- 🏢Remoto 
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ ou CLT

**Comment by xspager** [comment]
Essa vaga ainda está aberta?

**Comment by VivianeRHTI** [comment]
Vaga encerrada.
