### ISSUE TITLE
[Remoto] Back-end Laravel Developer nível pleno

### ISSUE THREAD

**Issue by DaviMenezes** [backend-br/vagas#3529]
## Descrição da vaga

Pleno em php, bons conhecimentos em Laravel, desenvolver apis. Terá acompanhamento e tarefas sobre demanda.
Horário comercial, sempre conectado comigo
Não tem segredo, precisa ter bons conhecimentos em php e Laravel 7 para implementações de apis

Demanda de +- 176 horas
Horário comercial

## Contratação

PJ - valor hora R$50

## Como se candidatar

Me encontre no telegram: [davimenezes](https://t.me/davimenezes)

**Comment by duuh30** [comment]
Existe algum outro meio de contato?

**Comment by rogerapras** [comment]
Atualmente tenho 4 horas/dia disponíveis ...Podemos conversar?
