### ISSUE TITLE
[São Paulo] .Net Developer Junior [Radar Profissional]

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#353]
Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Imprescindível experiência na função e com C#, .NET, ASP.NET MVC, ASP.NET WebAPI, Orientação Objeto (POO), LINQ e SQL Server;
•	Será considerado como diferencial, profissionais com experiência em EntityFramework, Code First/Migrations, Padrões de Projetos, SCRUM, Controle de Versão Visual Studio Online, TDD, ORACLE e Automatização de Testes.

Contratação: PJ
Local: São Paulo/SP 
Interessados: Enviar CV para vagas@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
