### ISSUE TITLE
[Remoto] Desenvolvedor(a) Java Pleno/Sênior @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [backend-br/vagas#3556]
## Sobre nós

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Local
Remoto

## Projeto
Implementar uma solução para sistemas industriais.

Responsabilidade: Atuar no desenvolvimento de solução construindo funcionalidades e componentes definidos com a equipe de desenvolvimento. Implementar serviços REST Java para front-end e integrações via API.

## Requisitos
Obrigatórios:

Formação: Superior na área de TI

- Conhecimentos em Java EE, EJB, REST, PL/SQL, JMS, e Orientação a Objetos

## Desejáveis:

Inglês intermediário, e conhecimentos em outras tecnologias não relacionadas são um diferencial.

## Benefícios
Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo.

## Contratação
Cooperativa

## Como se candidatar
Clique no link para se candidatar: https://bit.ly/2UGlcxZ

## Alocação
Remoto

## Regime
Cooperativa

## Nível
-Pleno
-Sênior

**Comment by everjava** [comment]
é microserviços ou monolítico ? jms é  rabbitmq ? é só backend ? é sistema novo(em desenv) ou é manutenção e novas features ?
