### ISSUE TITLE
[Belo Horizonte] Back-End Developer na [Zumpy]

### ISSUE THREAD

**Issue by orafaelreis** [backend-br/vagas#357]
### Descrição da vaga ###
Integrar a equipe de desenvolvedor Back end entregando uma API Rest para ser consumida internamente.

### Local ### 
Estamos alocados no [Orbi Conecta](http://orbi.co) - Bairro Lagoinha, BH - MG.

### Requisitos ### 
Conhecimentos em Java;
Vivência com ferramentas de versionamento de código, preferencialmente Git;

### Diferenciais ### 
Framework Spring
SQL, Webservice, REST  e noções de desenvolvimento Web.

### Nossa empresa ### 

A Zumpy é uma startup de TI que tem se destacado 

### Como se candidatar ### 

Envie um email para **andre@zumpy.com.br** com seu CV anexado (assunto: "Vaga Backend Java").

**Comment by guilhermeoa07** [comment]
Qual a senioridade? Entrevista pode ser feita remotamente?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
