### ISSUE TITLE
[REMOTO/ITÁLIA] Pleno/Senior Node.js Developer @ Hashtag.be

### ISSUE THREAD

**Issue by fjuriolli** [backend-br/vagas#3599]
## Descrição da vaga

Buscamos desenvolvedores com um perfil pleno/sênior para integrar o nosso time de desenvolvimento, e esperamos que você:
- Desenvolva código limpo, testável e de fácil manutenção.
- Contribua com todo o processo de desenvolvimento de software.
- Implemente features novas e investigar problemas em produção.
- Contribua nas discussões técnicas sobre os desafios encontrados.

## Local

100% remoto, empresa com base na Itália, horário flexível.

## Requisitos

**Obrigatórios:**
- Sólido conhecimento com bancos de dados relacionais.

**Desejável:**
- Experiência em desenvolvimento de software usando metodologias ágeis.
- Experiência em testes de software.
- Inglês para participar das nossas dailys.
- Experiência com Typescript.

**Diferencial:**
- Experiência com Ruby on Rails.

## Contratação

PJ inicial de €1800 (aproximadamente R$10.000 - R$11.500 líquido de acordo com a senioridade).
OBS: taxas de impostos brasileiras pagas pela própria empresa.

## Como se candidatar

Por favor envie um email para guilherme@hashtag.be e fernando@hashtag.be com o título "Vaga Node.js Senior" com seu CV e linkedin.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by MGustav0** [comment]
Antes de enviar um e-mail para vocês, tem algum desafio de código para implementar? Tenho conhecimento nos requisitos, mas não a experiência exigida, posso me candidatar?
