### ISSUE TITLE
[Campinas ou Belo Horizonte] Software Architect .Net na CI&T

### ISSUE THREAD

**Issue by gabrielmanara** [backend-br/vagas#360]
# Procuramos alguém que

- Tenha sólida experiência na definição e desenvolvimento de aplicações utilizando .NET Framework;
- Possua familiaridade com desenvolvimento de aplicações de grande porte;
- Apresente conhecimentos em implantação de aplicações em ambiente Microsoft, desde a configuração do ambiente até a instalação da aplicação;
- Possua experiência na análise de requisitos funcionais e não funcionais;

 # Você será responsável por

- Fazer análise de requisitos;
- Realizar design de soluções;
- Fazer planejamento e acompanhamento de implementação com o time.

# Você vai se destacar se

- Tiver facilidade de se adaptar a contextos diferentes;
- Tiver conhecimento em Oracle, Oracle FORMS, VB, ASP, Python e AWS.

# O que a CI&T oferece

- Plano de carreira estruturado;
- Vale alimentação e refeição;
- Seguro de vida e auxílio creche;
- Assistência médica e odontológica;
- Gympass;
- Descontos em estabelecimentos;
- Ônibus fretado, estacionamento ou transporte intermunicipal, dependendo da base de atuação;

Além disso, você pode contar com um ambiente descontraído e uma Academia de Great Coders com cursos online onde você poderá aprender ainda mais.

**Prezamos pela diversidade, liberdade, flexibilidade e autonomia!**

# Como se candidatar
Por favor envie um email para gmanara@ciandt.com com seu CV ou Linkedin - enviar no assunto: Software Architect .Net

# Labels
- Alocado
- CLT
- Pleno
- Sênior

**Comment by andreantunees** [comment]
CV enviado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
