### ISSUE TITLE
[Campinas ou Belo Horizonte] Software Architect PHP na CI&T

### ISSUE THREAD

**Issue by gabrielmanara** [backend-br/vagas#362]
# Procuramos alguém que

- Tenha experiência com PHP;
- Tenha inglês avançado;
- Goste de liderar e colocar a mão na massa quando necessário.

 # Você será responsável por

- Conduzir design técnico com o cliente;
- Liderar o time tecnicamente;
- Se comunicar de forma constante com o cliente e propor soluções;
- Codificar soluções complexas.

# Você vai se destacar se

- Tiver sólida experiência como Arquiteto de Softwares;
- Tiver conhecimento em Drupal 7, JavaScript, JQuery, HTML, CSS
- Tiver boa comunicação com time e envolvimento com o cliente para apresentar soluções.

# O que a CI&T oferece

- Plano de carreira estruturado;
- Vale alimentação e refeição;
- Seguro de vida e auxílio creche;
- Assistência médica e odontológica;
- Gympass;
- Descontos em estabelecimentos;
- Ônibus fretado, estacionamento ou transporte intermunicipal, dependendo da base de atuação;

Além disso, você pode contar com um ambiente descontraído e uma Academia de Great Coders com cursos online onde você poderá aprender ainda mais.

**Prezamos pela diversidade, liberdade, flexibilidade e autonomia!**

# Como se candidatar
Por favor envie um email para gmanara@ciandt.com com seu CV ou Linkedin - enviar no assunto: Software Architect PHP

# Labels
- Alocado
- CLT
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
