### ISSUE TITLE
[São Paulo] Especialista Back-End [Segmento: E-Commerce]

### ISSUE THREAD

**Issue by BrunoYY** [backend-br/vagas#365]
Boa noite pessoal, tudo bem?

Meu nome é Bruno e trabalho na FIND HR, uma consultoria de recrutamento focada 100% em vagas de tecnologia.

Estamos procurando por um Desenvolvedor Back-End para atuar em um dos maiores players de E-Commerce do Brasil.

Localização: São Paulo - SP , próximo ao Shopping Vila Olímpia
Modelo de contratação: CLT

**[Principais Responsabilidades]**

• Atuação no **time de buscas** com o foco em soluções inovadoras, escaláveis e de alta performance;
• Identificar gargalos e oportunidades de otimização nas aplicações;
• Buscar excelência no desenvolvimento através da utilização de padrões mais elevados de testes rigorosos manuais e automatizados;
• Acompanhar as soluções em produção e atuação em caso de problemas.

**[Perfil Técnico]**

• Bons conhecimentos de desenvolvimento de sistemas distribuídos, altamente escaláveis e de alta performance;
• Conhecimento nas linguagens de programação **Java, C++, Python**;
• Experiência com banco de dados relacional e não relacional (não relacional é desejável)
• Base analítica com viés de pesquisa
• Desejável experiência em sistemas de busca, tais como Solr e ElasticSearch
• Desejável conhecimento de infraestrutura
• Graduação em áreas de tecnologia (AdS, Ciências da Computação, Processamento de dados, etc); Mestrado será considerado diferencial.
• **3 anos de experiência com desenvolvimento.**

**[Contatos]**

Para mais informações sobre a vaga, segue meus contatos:
E-mail: byoshioka@findhr.com.br
Whatsapp: (11) 99813-1809

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
