### ISSUE TITLE
[Alphaville] Desenvolvedor Backend [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#366]
Atividades:
- Desenvolvimento de relatórios e analise de dados, utilizando VBA e SQL Server;
- Manutenção e Desenvolvimento de novas macros;
- Desejável experiência nos sistemas de SAS e área de Finanças.

Benefícios:
VR: 440,00/mês
AM e AO Care Plus Individual
Vale Transporte
Seguro de Vida 
* Sem descontos na folha do profissional.

Local de trabalho: Alphaville
Contratação CLT Full

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
