### ISSUE TITLE
[Campinas] Back-End Developer na Mix Fiscal

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#367]
## Descrição da vaga

- Desenvolver e manter os sistemas e ferramentas com consistência, segurança e performance;
- Fornecer estrutura (arquitetura e software) capaz de atender as necessidades das ferramentas e interfaces; 
- Gerenciar e publicar as versões dos sistemas nos servidores de testes e produção;
- Garantir o correto funcionamento lógico do sistema perante as regras de negócios.

## Local

Escritório, Campinas - SP.

## Benefícios

- Convênio médico Amil (70%);
- Refeição no Local;
- Transporte.

## Aptidões e qualidades

- Habilidade em Análise;
- Busca exatidão em seu trabalho;
- Se preocupa com a regularidade;
- Concentração;
- Visão sistêmica;
- Capacidade de Análise e Síntese.

## Contratação

CLT - Faixa salarial: R$4000.00 - R$5000.00

## Nossa empresa

A Mix Fiscal é uma empresa pioneira e inovadora em consultoria tributária para o varejo. Nossa tecnologia e métodos estão registrados em CopyRight mostrando exclusiva e influenciando no "eco-sistema" do mercado de consultoria em varejo.

- Vídeo institucional: https://www.youtube.com/watch?v=8js9RfJNtTw
- Site: www.mixfiscal.com.br

## Como se candidatar

Basta se cadastrar no link a seguir: http://bit.ly/2KSXbfr

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
