### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Python na Grupo Selpe

### ISSUE THREAD

**Issue by andre0799** [backend-br/vagas#37]
Desenvolvedor(a) Python que seja apaixonado(a) por tecnologia e, claro, tenha vontade de transformar a maneira que empresas e candidatos se conectam no mercado de Recursos Humanos.

Suas atividades serão:
Desenvolver soluções de captura de dados desestruturados e formar semântica para estruturá-los (no seu time vai ter frontend e backend)
Multiple fields de um currículo e de outros documentos serão seus desafios.

Habilidades desejáveis:
Flexibilidade cognitiva ou flexibilidade da estruturação, logo aumentar um nó em um cluster de banco de dados não pode ser problema para você;
Alta capacidade analítica e habilidade de resolução de problemas;
Alta capacidade de aprendizado e repasse de conhecimento;
Proatividade e dinamismo;
Capaz de tratar com autonomia as tomadas de decisões.

Workflow resumido do seu processo?
1- Question
2- Wrangle (Data preparation)
3- Explore
4- Draw Conclusions
5- Communicate (Blog post, Data visualization/Dashboard, etc)
Requisitos:
O que vamos amar ver em você:
- Conhecer Python e algum framework Web,
- Conhecimentos em HTML5, CSS3, Javascript e JQuery básico,
- SQL e NoSQL,
- AWS,
- Data Scraping será sua prática e modelo mental,
- Orientação para construir Dashboards,
- Orientação para Ciência dos Dados,
- Ser capaz de operar com banco de dados relacionais e não relacionais,
- Inglês,
- Trazer um pouco mais do mundo Py
Tipo de Contrato: CLT (Efetivo)
Salário: A combinar
Benefícios:
- Vale Transporte
- Vale Refeição
- Assistência Médica

PARA SE CANDIDATAR, ACESSE: https://www.recrutasimples.com.br/vaga/-L-D5yImjlaJSGag0ihC?referrer=githubbackend

**Comment by lucasparisi** [comment]
(Y)

**Comment by lucasparisi** [comment]
Top!
