### ISSUE TITLE
[São Paulo] Back-End Developer [RoadPass Payments]

### ISSUE THREAD

**Issue by fpcandido** [backend-br/vagas#370]
## Descrição da vaga

Projeto Conta Digital, Gateway, Cartões de Crédito e Pré-Pagos, C#, Azure, AWS, NOSQL, BigData, Arquitetura, Scrum, MicroServiços, Node, etc.

## Local

Escritório, São Paulo - Tatuapé

## Benefícios

- Plano de saúde
- Vale Transporte
- Seguro de vida
- VR de R$ 17,50/dia
- Auxílio creche
- Participação nos Lucros (PLR)

#### Diferenciais

- Ambiente descolado
- Copa para refeição no Local
- Frigobar sempre cheio :P
- Sala de descompressão (jogos)
- Cabines para telefonemas particulares
- Ambiente Industrial

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com C# 
- 2 anos de experiência com Microserviços
- Experiência com MicroServiços, Java, etc

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em Java
- conhecimentos em AWS, S3, Lambda, Dynamo, NOSQL, etc

**Diferenciais:**
- projetos opensource
- Amazon 
- Azure
- BigData
- Arquitetura

## Contratação

CLT a combinar

## Nossa empresa

Somos uma Startup de Conta Digital e Plataforma de Pagamentos, buscamos profissionais Jovens em espirito, para empreender conosco e para participar do desenvolvimento de tecnologias disruptivas para o mercado de pagamentos. Somos uma empresa com tecnologias também para IoT, M2M, Machine Learning e AI e oferecemos um ambiente muito bom com integração constante entre outras empresas do Grupo. 

## Como se candidatar

Por favor envie um email para daisyleite@roadpass.com.br com seu CV anexado - enviar no assunto: Vaga DEV-Back-End e seu telefone de contato, ou entre em contato pelo tefefone, 11 3938-6740.

## Labels

- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
