### ISSUE TITLE
[Santa Rita do Sapucaí - MG] Back-end Developer Junior @ Inatel

### ISSUE THREAD

**Issue by lpliao** [backend-br/vagas#3700]
O Inatel está recrutando profissionais para atuar em projetos de desenvolvimento de software, no ICC Software Aplicativo.

## Descrição da vaga

Preparar, configurar e disponibilizar ambientes de desenvolvimento e testes;
Configurar container para os projetos;
Desenvolver aplicativos desktop multiplataformas, webservices e aplicativos móveis;
Codificar bancos de dados relacionais e não relacionais;
Depurar códigos em diferentes ferramentas e dispositivos móveis;
Atuar em correções/ajustes da solução;
Revisar códigos desenvolvidos;
Realizar testes em ambiente de desenvolvimento;
Apoiar tecnicamente o time do projeto;
Elaborar documentação de projeto.

## Local

Santa Rita do Sapucaí - MG.

## Requisitos

**Obrigatórios:**
Ensino Superior Completo, preferencialmente em cursos de Computação, Sistemas de Informação ou Ciência da Computação;
Domínio de programação orientada a objetos;
Conhecimentos em: Controle de versão Git, Web RESTful, JSON e Node JS, Linguagem de programação Java, C#, Typescript, Kotlin, Dart e SQL, e com frameworks React, React native, AdminLTE.3.4, Desenvolvimento de aplicativos móveis, programação e depuração de código Android e iOS, Ferramentas de desenvolvimentos híbridos para aplicativos móveis, Plataforma Cloud AWS.

**Desejáveis:**
Experiência em projetos com equipes multidisciplinares,
Conhecimento em: AWS Amplify, AWS IoT, Bancos de dados relacional e não relacional, Ferramenta para integração/deploy contínuo, Servidor de mensageria, Testes automatizados, Metodologias ágeis (Scrum, XP, Kanban).

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagas@inatel.br com seu CV anexado - enviar no assunto: Vaga ESI SWA ou pelo link vagas.com.br/v2130979

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Regime
- CLT

#### Nível
- Júnior

**Comment by edu-tomasi** [comment]
Boa tarde @lpliao, acho que seria interessante você revisar a vaga postada.
Tanto no título da mesma como no rodapé da issue criada você informa que ela é de nível **Júnior**, porém no início da descrição você informa que estão na busca por um **Especialista**.
Alinhar as informações desta issue podem ajudar vocês à atingir o público correto.

**Comment by lpliao** [comment]
Olá Eduardo, obrigada pela dica! O mercado usa o termo Especialista para profissionais Expert, acima de sênior. Mas no Inatel, utilizamos a nomenclatura Especialista para profissionais graduados, que seria equivalente ao Analista ou até mesmo ao Programador ou Desenvolvedor, que algumas empresam usam.
