### ISSUE TITLE
[Contagem] Back-End Developer PHP na Infornet

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#371]
## Local

Escritório em Contagem - MG.

## Benefícios

- Vale Transporte ou Auxilio Combustível;
- Vale Refeição;
- Lanche na empresa;
- Plano de Saúde (coparticipativo - Unimed);
- Programa de Remuneração Variável (Participação nos Resultados de acordo com o desempenho).

## Aptidões e qualidades

- Proatividade;
- Trabalho em equipe;
- Atualização tecnológica;
- Organização.

## Informações complementares

- Residir em Contagem ou proximidades;
- Conhecimento em PHP, MYSQL, Laravel.

## Desejável

- Conhecimento em metodologias ágeis (scrum), Git, NodeJS.

## Contratação

CLT - Faixa salarial: R$1500.00 - R$2000.00

## Nossa empresa

Fundada em 2008, a Infornet desenvolve softwares e aplicações específicas para as necessidades do seu negócio. Nosso diferencial é desenhar soluções customizadas, de acordo com os requisitos do sistema e com a realidade de sua empresa. Como resultado, oferecemos uma experiência única em desenvolvimento de software web. Nossos profissionais acompanham todas as etapas do processo, desde o levantamento de requisitos à implantação final, passando por testes, acompanhamento e treinamento. Contamos com casos de sucesso e experiência acumulada em projetos para diversas empresas.

## Como se candidatar

Basta se cadastrar no link a seguir: http://bit.ly/2KTKyAO

## Labels

- Alocado
- CLT
- Júnior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
