### ISSUE TITLE
[Rio de Janeiro] Full Stack Developer @ MAG Seguros

### ISSUE THREAD

**Issue by UeidiRocha** [backend-br/vagas#3716]
> Vaga Remota durante a pandemia

## Nossa empresa

MAG Seguros
Presente em todo o Brasil com mais de mil funcionários e dois milhões de clientes, somos uma multinacional do Grupo Aegon com sede em Haia, na Holanda. Atuando em mais de 20 países, fazemos parte de um dos maiores grupos de seguros, previdência e investimentos financeiros do mundo e temos como propósito ajudar as pessoas a assumir a responsabilidade por seu futuro financeiro.
Se você está em busca de desafios profissionais e quer trabalhar em uma das melhores empresas do Brasil, reconhecida pela Great Place to Work, venha fazer parte do nosso time!

## Descrição da vaga

- Desenvolvimento e manutenção de aplicações web;
- Implementação de serviços em ambiente nuvem;
- Desenvolvimento Frontend;
- Desenvolvimento Backend;
- Realização de manutenção e criação de novas funcionalidades.

## Local

Rio de Janeiro, Centro - Brasil

## Requisitos

**Obrigatórios:**

- Formação superior completa em Sistemas da Informação, Ciência da Computação ou áreas correlatas;
- Experiência em desenvolvimento, manutenção e análise de sistemas e de negócio;
- Já ter atuado com metodologias ágeis;
- Vivência com .Net Framework 4.5 ou superior;
- Vivência com Angular 6 ou superior.

**Desejáveis:**
- Experiência com o padrão MVC; ASP.Net Web API; SOA e/ou Microserviços; e com ambiente cloud (Azure).

## Benefícios

- Vale-refeição
- Vale-alimentação
- Vale-transporte
- Plano de saúde
- Plano odontológico
- PLR
- Gympass

**Diferenciais:**

- Assistência funeral
- Previdência
- Auxílio Creche

## Contratação

CLT. 
Salário a combinar.

## Como se candidatar

Por favor envie um email para urocha@mag.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolver Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo. E-mail para contato em caso de não haver resposta: urocha@mag.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by FilipeAugustoVO** [comment]
Pergunta: Vocês tem vagas remotas para quem não mora no Rio de Janeiro?
