### ISSUE TITLE
[São Paulo] Python Fullstack Developer [TemBici]

### ISSUE THREAD

**Issue by vinyguedess** [backend-br/vagas#372]
## Local
Vila Mariana, São Paulo

## Atividades
Desenvolvimento web de software frontend, backend e software de baixo nível, elaborar junto com o time arquitetura de novos sistemas, desenvolvimento de novos recursos em sistemas em produção e escolher em conjunto os caminhos técnicos de novos projetos.

## Requisitos
- Conhecimento em Python e visões de web como arquitetura, componentização e soluções para alta performance, Angular, HTML 5, CSS, Bootstrap, refactoring em códigos legados, deixando-os testáveis e mantendo seu funcionamento original, conceitos de design de APIs, integração e Delivery Contínuos, Jenkins ou ferramentas similares.
- Desenvolvimento de testes unitários, APIs Restful;
- Volumetria: ferramental e análise;
- Metodologias ágeis (Scrum e XP).

## Como se candidatar
Envie um e-mail para raon.freitas@randstad.com.br com o assunto **Dev Python Fullstack** com curriculo em anexo e pretensão salarial.

## Diferenciais
- Node.js 
- e-commerce
- AWS
- Ruby on Rails (legado)

## Labels
- Alocado
- Angular2
- AWS
- Django
- PJ
- Python
- TDD
- Senior

**Comment by vinyguedess** [comment]
@rafaelrabaco

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
