### ISSUE TITLE
[Amsterdã - Holanda] Senior Backend Engineer at Weeronline (Node.js & Scala)

### ISSUE THREAD

**Issue by heloa-net** [backend-br/vagas#373]
## Descrição da vaga
For our high-traffic weather platform, we're looking for a Full-stack Developer with a focus on server-side development. Main technologies used are JavaScript (Node.js) for our new responsive web environment and Scala for backend processing of data, all running on a Google cloud stack.

Our in-house development team recently finished building a new web application platform from scratch, using React, Redux and Node.js as primary tools for improving the product experience for our multi-million audience. Of course, we use continuous integration and deployments in our Kubernetes managed platform.

For our back office we are rebuilding our stack, from legacy applications build in VB6 and PHP to Scala and NodeJS based applications.

You will be part of a solid and efficient development team to drive product and platform innovation. We have a strong need for technical cleverness and skills to create a roadmap that ensures not only improvements for consumers, but also helping us move to a consolidated architecture with clear set of technologies and integrations. You should be able to oversee, steer and participate in the development of the whole platform.

We are open for new technologies, encourage collaborative decisions and are pushing for multi-disciplinary scrum teams caring about the products we ship.

## Local
Office in Amsterdam, Netherlands

## Contratação
Visa sponsorship available. Salary range depending on experience.

## Diferenciais
**Our environment:**
• Big technical challenge and inspiring ambitions;
• Very personal company (around 90 colleagues), big brand and part of a listed company;
• International team;
• Extensive training opportunities, meet-ups; 
• A lot of freedom which comes with your responsibility;
• Office located at one of the hot spots in Amsterdam;
• At Zoover & Weeronline performance and fun comes together with lunch, table tennis, parties, teambuilding, fun activities, casual drinks, etc.

## Requisitos
**Who are you?**
You are curious, you want to continually improve yourself and you like to tackle new developments with both hands.

**Your background and skills:**
- You want to learn with and from your colleagues to become even better;
- You have at least multiple years of experience with both JavaScript, cross-browser development and server side application development, preferably but not necessarily in Scala;
- You have gained your development experience in a web environment and you are aware of the impact of your work on a large consumer audience;
- Proficient with Node.js and its current ecosystem;
- You have experience optimizing backend performance and determining loading bottlenecks;
- Experience with multiple of: React, NodeJS, Scala, Kubernetes, Lighthouse, Test frameworks;
- Knowledge of some of our legacy technologies we are replacing (like PHP / VB6) is nice as well;
- You are a strong communicator;
- Very good conversational skills in English.

**Your tasks/responsibilities:**
- Oversee the full application landscape, ensuring quality and maintainability;
- Implement new features and components in our Node.js and Scala based backend;
- Consistently care for very good test coverage and automation;
- Co-Own our backend architecture and keep documentation up to date;
- Drive continuous evolution of our backend architecture together with your team;
- Help design RESTful APIs that provide outstanding Developer Experience.

## Nossa empresa
Weeronline is the most complete weather platform in the Netherlands. With 20 to 30 million visitors on a monthly basis, we are proud to serve the most specific weather information for every location all over the world.

## Como se candidatar
Please send an e-mail to [closed] with your CV attached and "Senior Backend Engineer at Weeronline application" as subject.

## Labels
- Presencial
- Full Time
- Exterior
- Visa Sponsorship
- Sênior

**Comment by heloa-net** [comment]
Fala galera do back-end!
Eu trabalho na Zoover, que tem uma relação bem próxima com a Weeronline no dia-a-dia, nem sei bem como separar. Quem sabe se você vier pra cá trabalhar com a gente você entende e me explica. Eu chamo informalmente de "sister company".

Tentei dar uma melhorada nesse texto do RH mas a situação estava difícil então vou escrever um pouco pra ver se ajuda.

### Sobre "full-stack"

Aqui somos contratados como "full-stack" (um termo de que nunca fui muito fã, aliás eu me especializei em front-end e acredito que os mindsets são diferentes, mas né...).
O meu foco é front, acho que >95% do tempo eu trabalho com isso. Até me aventuraria mais no back-end mas minhas habilidades me limitam. E do modo que trabalhamos, isso funciona bem. No meu time, especificamente, somos 4 devs, dois focados em front, dois em back-end, e na maioria do tempo dividimos as tarefas de acordo com preferências e habilidades.

Enfatizo isso porque se você for um back-end dev excelente, não acho que está fora porque não é tão forte (ou nem mexe) em React! O foco dessa vaga é NodeJS e Scala.

Quem vai definir isso 100% são os devs da Weeronline (no dia-a-dia somos próximos mas tecnicamente mais distantes), então se você decidir aplicar vai ter essa conversa e ver se vale a pena pra você e pra eles (pra nós(?!)). Mas te incentivo a "vender o seu peixe" e meter as caras. Se você tem alergia à front-end e nunca tocaria se necessário, pode ser um contra. Se você está aberto (apesar de simpatizar comigo que "full-stack" é meio non-sense), quem sabe né?

Também falo isso porque quando eu apliquei, também fiquei com medo de não conseguir a vaga por não ser tão "full-stack" assim. No final das contas rolou e foi win-win! 🎉

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
