### ISSUE TITLE
[Amsterdã - Holanda] Back-end Software Engineer at Zoover (NodeJS)

### ISSUE THREAD

**Issue by heloa-net** [backend-br/vagas#375]
## Descrição da vaga
As a high-traffic, travel website targeted at the Dutch market, we're looking for a Full-stack JavaScript Developer with a focus on server-side JavaScript (Node.js). Our in-house development team recently finished building a new application platform from scratch, using React, Redux and Node.js as primary tools for improving the product experience for our multi-million audience. 
You will be part of a solid and efficient development team to drive product and platform innovation. We have a strong need for technical cleverness and skills to create a roadmap that ensures improvements for consumers, but also moving towards an architecture based on Elasticsearch, Node.js and React/Redux. We are open for new technologies, encourage collaborative decisions and are pushing for multi-disciplinary scrum teams caring about the products we ship.

## Local
Office in Amsterdam, Netherlands

## Contratação
Visa sponsorship available. Salary range depending on experience.

## Diferenciais
**Our environment:**
• Big technical challenge and inspiring ambitions;
• Very personal company (around 90 colleagues), big brand and part of a listed company;
• International team;
• Extensive training opportunities, meet-ups; 
• A lot of freedom which comes with your responsibility;
• Office located at one of the hot spots in Amsterdam;
• At Zoover & Weeronline performance and fun comes together with lunch, table tennis, parties, teambuilding, fun activities, casual drinks, etc.

## Requisitos
**Who are you?**
You are curious, you want to continually improve yourself and you like to tackle new developments with both hands.

**Your tasks/responsibilities:**
• Implement new features and components in our Node.js based backend.
• Consistently care for very good test coverage and automation
• Co-own our backend architecture and keep a minimal set of documentation up to date
• Drive continuous evolution of our backend architecture together with your team
• Help design RESTful APIs that provide outstanding Developer Experience

**Your background and skills:**
• You want to learn with and from your colleagues to become even better;
• You have at least 3 years of experience with JavaScript, cross-browser development;
• You have gained your development experience in a web environment and you are aware of the impact of your work on a large consumer audience;
• Proficient with Node.js and its current ecosystem
• You have experience optimizing backend performance and determining loading bottlenecks;
• You are a strong communicator;
• Very good conversational skills in English;

## Nossa empresa
Zoover is the largest hotel and travel rating portal in the Netherlands.
With 3.2 million ratings, 400,000 hotels and camp sites as well as 900,000 travel tips, the Zoover platform makes finding the perfect holiday a cinch for holidaymakers.

In our Amsterdam office, around 90 colleagues all work together to achieve this goal by providing inspiring content through our website, blog and other platforms, by developing a user-friendly website, apps for tablet and mobile, and offering a varied assortment of accommodations, reviews and customer service.

## Como se candidatar
Please send an e-mail to [closed] with your CV attached and "Back-end Software Engineer Zoover" as subject.

## Labels

- Presencial
- Full Time
- Exterior
- Visa Sponsorship
- Pleno
- Sênior

**Comment by heloa-net** [comment]
Eu trabalho nessa empresa atualmente e estou curtindo bastante. E morar na Holanda... ❤️

_Essa vaga é similar à outra que postei mas não é a mesma._
_Meu comentário abaixo foi baseado no que postei na outra vaga, com algumas modificações porque são empresas diferentes._

Tentei dar uma melhorada nesse texto do RH mas a situação estava difícil então vou escrever um pouco pra ver se ajuda.

### Sobre "full-stack"

Aqui somos contratados como "full-stack" (um termo de que nunca fui muito fã, aliás eu me especializei em front-end e acredito que os mindsets são diferentes, mas né...).
O meu foco é front, acho que >95% do tempo eu trabalho com isso. Até me aventuraria mais no back-end mas minhas habilidades me limitam. E do modo que trabalhamos, isso funciona bem. No meu time, especificamente, somos 4 devs, dois focados em front, dois em back-end e dividimos as tarefas de acordo com preferências e habilidades.

Enfatizo isso porque se você for um back-end dev excelente, não acho que está fora porque não é tão forte (ou nem mexe) em React!

Quem vai definir isso 100% serão as pessoas que vão te entrevistar, então se você decidir aplicar vai ter essa conversa e ver se vale a pena pra você e pra eles. Mas te incentivo a "vender o seu peixe" e meter as caras. Se você tem alergia à front-end e nunca tocaria se necessário, pode ser um contra. Se você está aberto (apesar de simpatizar comigo que "full-stack" é meio non-sense), quem sabe né?

Também falo isso porque quando eu apliquei, também fiquei com medo de não conseguir a vaga por não ser tão "full-stack" assim. No final das contas rolou e foi win-win! 🎉

**Comment by alessandroprudencio** [comment]
@heloameneses que legal parabéns...
