### ISSUE TITLE
[Remoto] Back-end Developer C# - JOYJET

### ISSUE THREAD

**Issue by PachecoRaphael** [backend-br/vagas#3756]
Hello,

Joyjet is looking for a back-end developer in C#. We have a lot of different projects from e-commerce to interns app for businesses.

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview-tests/src/master/backend/

## Local
Remoto

## Benefícios
- Plano de saúde
- Free course to study
- 30 days of holidays per year

## Requisitos obrigatórios:
- Proficient in C#, with a good knowledge of its ecosystems
- Proficient understanding of REST API
- Good understanding of SQL (write queries, tables, constraints, etc.)
- Proficient understanding of code versioning tools such as Git;
- Experience with .NET Core and EntityFramework Core

And

- HTML/CSS
- GIT

## Desejáveis:
- Microsoft SQL Server or Postgres.
- .NET testing frameworks such as nUnit, XUnit or MSTest
- Continuous integration
- Azure Cloud
- Dapper
- Experience with any DI framework in any language

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA BACK-END C#

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview-tests/src/master/

## Labels
PJ
Pleno
Remoto
C#

**Comment by edu-tomasi** [comment]
Hello @PachecoRaphael, that's a nice role.
But the link to the test is broken.

**Comment by PachecoRaphael** [comment]
We are still looking for 2 c# dev ! :D

**Comment by FilipeAugustoVO** [comment]
I'm interested, but the page with the test does not work. Not even Wayback
Machine has it.

**Comment by PachecoRaphael** [comment]
> I'm interested, but the page with the test does not work. Not even Wayback Machine has it.

You don´t succeed to access this link? https://bitbucket.org/lixao/tech-interview-tests/src/master/

**Comment by FilipeAugustoVO** [comment]
It works now, thank you
