### ISSUE TITLE
[Uberlândia] Java Developer na Performis

### ISSUE THREAD

**Issue by andrelsperes** [backend-br/vagas#377]
**Experiência Necessária**
- Experiência mínima de 4 anos em desenvolvimentos de sistemas de médio e grande porte na área de TI.

**Conhecimentos Específicos Essenciais:**
- Conhecimento de padrões de projeto e padrões de integração
- Java(e suas principais APIs), Spring (IOC, MVC, Scheduler, JDBC, BOOT), JQuery, Javascript, HTML e CSS
- Servidores de Aplicação Apache e Apache Tomcat;
- Bancos de Dados Microsoft SQL Server (Modelagem de dados e programação);
- Mecanismos e Tecnologias para integração de sistemas (SOAP, REST, Bancos de Dados).

**Como se candidatar**
Por favor envie um email para th@performis.com.br com seu CV 

**Labels**

- Alocado
- Pleno
- Sênior

**Comment by jorgelimafeitosa** [comment]
Olá, como faço para enviar meu currículo?

**Comment by andrelsperes** [comment]
Por favor envie um email para th@performis.com.br com seu CV
