### ISSUE TITLE
[Bauru] Programador PHP Senior - Backend @UP Outsourcing

### ISSUE THREAD

**Issue by giovanarezende** [backend-br/vagas#3772]
> Vaga Remota durante a pandemia

## Nossa empresa

UP Outsourcing é uma empresa localizada em Bauru, no interior de São Paulo, a 326 km da capital com uma média de 379.000 habitantes.

Nós oferecemos oportunidades para desenvolvedores Web, baseado em Princípios de Desenvolvimento Ágil. Também auxiliamos Startups com Protótipos usando os Princípios de Inovação para a necessidade do cliente.

## Descrição da vaga

Esta oportunidade visa a liderança técnica de um time de desenvolvimento distribuído remotamente onde a função principal desejada é a de coordenação de arquitetura do sistema e suporte constante para o time de desenvolvimento.

Responsabilidades:
- Dar suporte técnico para os membros do time
- Reportar diariamente o andamento das atividades
- Ser pró-ativo colaborando para a resolução de problemas do time, incluindo Pair-Programming se necessário
- Trabalhar respeitando os processos ágeis de desenvolvimento

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5 anos ou mais de experiência
- Inglês Intermediário / Avançado
- Experiência com Banco de Dados padrão SQL
- Experiência com Symfony ou Laravel
- Experiência com Yii
- Graduação na Área de Tecnologia
- Experiências com metodologias ágeis - Scrum ou Kanban

## Benefícios

- Modalidade PJ
- Aulas de Inglês avançado para Empresas
- 10 dias pagos de férias
- Horário flexível (respeitando eventuais reuniões com base no fuso da Europa)
- Home Office
- Escritório em Bauru / SP com estrutura de suporte completa
- PLR Mensal
- Cursos e Certificações
- Webinars e ajuda de profissional para Saúde Mental
- Folga em dias específicos previamente planejado

## Contratação

PJ 

## Como se candidatar

Envie seu currículo para:  rh@upoutsourcing.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by giovanarezende** [comment]
@ravanscafi @felipefialho esta vaga já foi fechada! Como faço para excluir?

**Comment by felipefialho** [comment]
@giovanarezende Aqui não é eu que cuido hahaha 😅
