### ISSUE TITLE
[Alphaville (Barueri/SP)] Desenvolvedores na [Quod]

### ISSUE THREAD

**Issue by glendaquod** [backend-br/vagas#378]
Você gostaria de trabalhar com desenvolvimento no mercado de informações de crédito? E, o mais legal, transformando-o de forma positiva?

Estamos montando nossa área de Tecnologia e buscamos Desenvolvedores **Fullstack** e/ou profissionais de **FrontEnd** e **BackEnd**!

Várias linguagens de programação são bem vindas neste momento. Priorizamos as tecnologias HTML5, CSS3, Bootstrap, frameworks javascript (como Angular, React e Vue) no Front e PHP e/ou Java no Back.

Caso seja um Desenvolvedor mobile swift, java, Ionic, PWA, etc, também queremos te ouvir.

Se você tem experiência em desenvolvimento (mobile e/ou web) e está a fim de fazer a diferença, venha conhecer mais sobre a gente!

Se você acha que faz sentido para sua carreira, entre em contato comigo!
glenda.dalmedico@quod.com.br

**Comment by guilhermeoa07** [comment]
Qual a senioridade?

**Comment by glendaquod** [comment]
Oi Guilherme!
Estamos construindo a equipe do zero e devemos ter pelo menos 8 pessoas na equipe em diferentes níveis.
Por isso preferimos não limitar a senioridade e a linguagem :)

**Comment by Bufige** [comment]
O trabalho é remoto?

**Comment by glendaquod** [comment]
Olá @Bufige o trabalho não é remoto.

**Comment by joaopdto** [comment]
Vagas para Estágio?

**Comment by glendaquod** [comment]
@joaopdto por enquanto somente CLT, mas manda seu material para a gente de qualquer forma, pois devemos ter vagas no futuro :)

**Comment by joaopdto** [comment]
Opa! Legal, vou mandar sim. Obrigado.

**Comment by aCidcOde** [comment]
Tenho interesse na parte de liderança e desenvolvimento de produto, sou de barueri e abaixo segue meu site para dar uma conferida no meu resumo.

http://www.kernelpanic.com.br/

boa sorte!
