### ISSUE TITLE
[São Paulo] Fullstack Developer [Confitec]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#380]
**Descrição da vaga**
Fará parte da equipe de desenvolvedores de sistemas voltados ao mercado de Seguros.

**Onde**
No Escritório de São Paulo - ao lado do Morumbi Shopping.

**Benefícios**
Assistência Médica
Assistência Odonto
VR de R$ 24,30/dia
VT
PLR
Auxílio creche

**Diferenciais**
Café da manhã toda sexta-feira
Ginástica laboral às quartas
Campeonatos (Pocker, Futebol, Games, etc)

**Requisitos Obrigatórios:**
Ensino superior completo.
Buscamos profissionais (níveis Júnior, Pleno e Sênior) com skill de desenvolvimento Back End em .Net, C#. 
Vivência com Angular (JS/2+).
Diferencial: criação/manutenção de API’s em NodeJS. 

**Desejáveis:**
Conhecimento em React (JS/Native). 

**Contratação**
CLT Full

**Nossa empresa**
A Confitec é uma empresa de TI especializada no mercado de Seguros.

**Como se candidatar**
Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga .Net/NodeJS

Por favor, envie também sua pretensão salarial CLT.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
