### ISSUE TITLE
[Teresópolis RJ ou Remoto] Backend Ruby on Rails

### ISSUE THREAD

**Issue by Cleysonlb** [backend-br/vagas#381]
![image](https://user-images.githubusercontent.com/7593949/44222451-e5d6fa80-a15a-11e8-8b5a-3b3c3f40458e.png)

## Descrição da vaga

Buscamos alguém que tenha interesse nas necessidades dos nossos clientes e que se identifique com o nosso negócio: ajudar profissionais do varejo de todo o Brasil a potencializar seus resultados.

## Local

Remoto ou Escritório, Teresópolis - RJ

## Benefícios

A combinar

#### Diferenciais

- Trabalhar em uma startup em constante crescimento
- Poder impactar positivamente no varejo Brasileiro por meio da tecnologia
- Vaga Remota

## Requisitos
 - Experiencia com desenvolvimento de aplicações em Ruby on Rails
 - Ter dominio em Ruby
 - Código limpo e bem estruturado
 - Testes Unitários

## Contratação

 Remoto sendo PJ
 Presencial sendo CLT
 Salário a combinar

## Nossa empresa

Assumimos, com muita vontade, a missão de criar uma plataforma que transforma o varejo físico brasileiro, aumentando a produtividade e potencializando os seus resultados.

Conquistamos a confiança de +100 marcas do Varejo nacional, como: Clube Melissa, Mr Cat, Chilli Beans, Santa Lolla, Outer Shoes, Pandora, Grupo Technos, The Body Shop, AD, Rommanel, Cellairis, Taco entre outras...

nosso site: https://indeva.com.br/

## Como se candidatar

Preencha o formulario neste link: https://goo.gl/hPEJer

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Sênior
- regime/A-Combinar
- regime/CLT
- regime/PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
