### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack PHP Pleno

### ISSUE THREAD

**Issue by DeniseHunterCo** [backend-br/vagas#3813]
##Nossa empresa
Trabalho em uma empresa de recrutamento humanizado que se chama HunterCo, possuímos várias vagas e consultores que acompanham os candidatos no recrutamento, auxiliando-o e dando feedback's.
##Descrição da vaga
Analisar e desenvolver funcionalidades do Roadmap tanto no Back-end como Front-end. Sugerir evoluções de metodologia de desenvolvimento e entrega de software. Promover a integração e disseminação de conhecimentos entre a equipe, através de práticas como programação em par e apresentações técnicas.
O salário dessa vaga é em torno de 6k (CLT ou PJ)
##Local
A vaga é full remoto, mas se for da região de São Paulo - Capital e quiser ir até o office, eventualmente, fique a vontade.
##Requisitos
Vivência com Front-end (SQL, Estrutura de Dados, JavaScript, CSS, HTML);
Vivência com Back-end (PHP);
Conhecimentos de Banco de Dados MySQL e SQL Server;
Conhecimentos gerais: GIT | WordPress.
##Benefícios
Horário flexível
Vale Alimentação (Presencial)
Auxilio academia
Day off
Vale presente aniversário
##Como se candidatar
Acessar o link: https://vagas.hunterco.com.br/job/5fd1673a591099001b80aefb?c=3301
E clicar em "QUERO PARTICIPAR"
Eiiii e se quiser se candidatar em outras vagas que achar interessante, pode ficar a vontade.
Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: denise.silva@parceirohunterco.com.br
##Labels
full stack, back end, front end, php

**Comment by NomiasSR** [comment]
Olá boa tarde, tenho interesse em participar do processo seletivo para a vaga. Segue em anexo cópia de meu cv para suas avaliação. Obrigado
[Uploading curriculum_paulo_saimon_enviar.pdf…]()
