### ISSUE TITLE
[Florianópolis SC] Remote Back-end Developer JR @HarmoDeveloper

### ISSUE THREAD

**Issue by leonardorifeli** [backend-br/vagas#3823]
# Sobre a Harmo (@HarmoDeveloper)

### QUEM SOMOS?
Ajudamos empresas a crescerem na economia do feedback 💜

Somos uma empresa que acredita no poder do feedback dos consumidores como a principal estratégia na construção de relações duradouras e rentáveis entre as marcas e seus clientes. Temos um propósito claro: Promover a qualidade de vida na sociedade através do incentivo à cultura do feedback.

Nossa missão é contribuir com a melhoria contínua na qualidade do atendimento nas empresas brasileiras, usando como principal insumo os feedbacks dos próprios clientes ao se relacionarem com as empresas.

Nós damos ouvidos aos nossos clientes, para que eles possam escutar os anseios dos seus clientes de forma cada vez mais legítima e estruturada, contribuindo na implementação de uma cultura “customer-centric” nas empresas.

Para cumprir com essa missão, oferecemos no mercado uma plataforma SaaS para gestão 360 de experiência do cliente. A nossa solução é a primeira e única do país a unir gestão pesquisas de satisfação (NPSⓇ, CES e CSAT) com gestão de reputação online (reviews públicos do Google Meu Negócio, Trip Advisor, Facebook, ifood, Yelp etc), cobrindo toda a jornada do cliente com as marcas.

Acreditamos que a chave do sucesso está em ouvir os anseios dos clientes em todos os pontos de contato com as empresas, transformando as avaliações, opiniões e críticas em ações que promovam melhores experiências, fortalecendo a confiança e satisfação dos clientes, tornando-os compradores fiéis e promotores da marca.

### NOSSO PROPÓSITO
Promover mais qualidade de vida na sociedade através do incentivo à cultura do feedback.

### NOSSA ESSÊNCIA
Somos uma startup que, acima de tudo, ama a pluralidade do nosso planeta, em todos os sentidos. Para nós nada é mais excitante e fascinante do que a diversidade de paisagens, culturas, gostos e opiniões.

A cultura interna da nossa organização não apenas promove essa diversidade como entende que a aceitação das diferenças é a melhor forma de desenvolver o nosso próprio negócio.

### NOSSOS VALORES

- O cliente do nosso cliente em primeiro lugar.
- Profissionalismo como mantra.
- Respeito às diferenças.
- Espírito inquieto e curioso.
- Vontade incansável de contribuir.

### PORQUÊ TRABALHAR NA HARMO

Porque estamos crescendo! Temos um compromisso com o sucesso e trabalhamos com muita dedicação para alcançar nossos objetivos. Tudo que conquistamos até agora serve como credencial.

Porque possuímos um time de pessoas altamente inteligentes e competentes. Sem dúvidas, você será estimulado a evoluir continuamente.

Porque possuímos uma rede de contatos muito poderosa, que poderá ajudá-lo em sua carreira e em seu crescimento profissional.

Não oferecemos luxo, mas aqui nos sentimos parte de um grupo de pessoas que, acima de tudo, respeita, valoriza e incentiva a diversidade de cada um.

Como todo time, nós também temos nossos problemas, então não espere encontrar uma “família de comercial de margarina”. Mas tenha a certeza de que encontrará um espaço aberto ao diálogo para sempre oferecer o melhor ambiente de trabalho e as melhores relações possíveis entre os seus profissionais.

Temos orgulho do time que somos, não apenas porque somos profissionais comprometidos com a nossa missão, mas, principalmente, porque criamos um ambiente que nos estimula a evoluir, onde todos estão sempre prontos para se ajudar mutuamente nas conquistas dos nossos objetivos.

Trabalhar com a gente não vai ser moleza! Temos metas ambiciosas, o dia-a-dia é puxado e você vai encarar grandes desafios. Mas se você se identificar como nosso propósito, missão e cultura, garantimos que será uma jornada estimulante e prazerosa, de muita evolução profissional e pessoal.

Porque acreditamos que, acima de tudo, o time é o nosso maior diferencial. Nosso objetivo é sempre contratar profissionais que elevem a nossa barra constantemente, pois entendemos que dessa forma seremos sempre motivados a evoluir constantemente, contribuindo na atração de profissionais cada vez mais capacitados. “A” players hire “A” players

Porque nos importamos demais com a nossa cultura, para que ela reflita nossa ética e valores. Procuramos sempre oferecer o melhor ambiente de trabalho e as melhores relações de trabalho possíveis!

Porque nosso produto efetivamente resolve uma DOR! E o mercado sempre compra produtos que realmente resolvem dores e entregam resultados mensuráveis.

# Descrição da vaga

Back-end Developer JR (PJ / remoto / full-time)

Desenvolvimento de Produto

A Harmo Feedback Intelligence está crescendo rápido e chegou a hora de reforçar o nosso time de engenharia e desenvolvimento de produto. Atualmente somos um time composto por três engenheiros seniores, sendo dois back-ends (incluindo nosso CTO, Leonardo Rifeli) e um back-end. Também contamos com o nosso CPO, Lucas Hansel, que trabalha em total sinergia com o time de engenharia.

Estamos em busca de um profissional experiente, que apresente, além das qualificações técnicas necessárias, três atributos principais:

Atitude - Você faz acontecer. É líder de você mesmo. Não fica sentado esperando, entende os problemas e segue na resolução. Algo não está bom? Melhora. Cria planos e entrega nos prazos.

Conhecimento - Quando você não tem conhecimento suficiente para o desafio, busca rapidamente. Tem perfil autodidata, sempre busca aprender mais e melhor. Quando tem um problema, busca conhecimento sobre como solucioná-lo de forma inteligente visando o melhor contexto possível. Gosta de ler e aprender.

Entusiasmo - Você tem enorme paixão pelo que faz e não lida apenas como job. Se comunica super bem e tem bom humor. Encara os desafios com entusiasmo e confiança. Se orgulha do que está fazendo. Trabalha em equipe de forma eficiente.

O nosso produto, que preferimos chamar de solução, impacta a vida de milhões de consumidores e dos nossos mais de 70 clientes, grandes empresas e marcas do Brasil.

Quer fazer parte da nossa jornada?

### Principais atividades

- Atuação na área basal do time de produto (time base);
- Atuação no desenvolvimento e manutenção de scripts;
- Atuação na automatização de fluxos e processos;
- Atuação em bugs;
- Manutenção de robôs de coletas de dados;
- E muito, muito JavaScript.

### Qualificações Técnicas

- Desenvolver códigos: estáveis, confiáveis, elegantes e, não menos importante, fáceis de manter;
- Desenvolver soluções sempre pensando em eficiência, escalabilidade, disponibilidade, performance e estabilidade. Queremos garantir nosso crescimento super acelerado e um software escalável de maneira econômica (do more with less);
- Conhecimento intermediário em Javascript;
- Conhecimento SQL;
- Vivência com pelo menos um banco de dados relacional;
- Conhecimento em arquitetura de software;
- Inglês básico (leitura e escrita);
- Ter comunicação rápida e assertiva, saber trabalhar com times multidisciplinares e enxutos em um ambiente dinâmico, com entregas rápidas, metodologias ágeis e inspirado no Vale do Silício. Trabalhamos com velocidade e autonomia no dia-a-dia e somos um time de alta performance.

### Conhecimentos desejáveis

- Ter formação em sistemas de informação, ciência/engenharia da computação ou cursos similares. Não é formado mas tem experiência e vontade? Se inscreve também;
- Conhecimento sobre web-scraping & crawlers;
- Experiência na resolução de bugs;
- Conhecimento em metodologias ágeis e excelente comunicação.
- Conhecimento em conceitos como Clean Code, Clean Architecture, 12 factors app, Design Patterns e SOLID;
- Conhecimento em Cloud, especialmente serviços da AWS;
- Utilizar conceitos do GitHub, branching, issues, pull-requests, etc.

### Remuneração e Benefícios

- Remuneração fixa compatível com o cargo, regime PJ;
- Após 12 meses, recesso remuneradas de 30 dias (caso saia antes dos 12 meses, perde o benefício);
- Auxílio Internet de R$ 150 por mês.

### Oferecemos para quem trabalha na Harmo

- Modelo home-office full-time até março de 2021, depois será reavaliado, mas manteremos flexibilidade com relação ao home-office, ainda mais com profissionais que não moram em Floripa;
- Day-off no aniversário;
- Fazer parte de um time de alto rendimento;
- Ambiente descontraído, mas super profissional;
- Desenvolvimento de carreira.

# Como Submeter-se?

https://harmo.enlizt.me/vagas/back-end_developer_jr-221220

**Comment by likannp** [comment]
Boa tarde, a vaga ainda está disponível?

**Comment by leonardorifeli** [comment]
Vaga encerrada.
