### ISSUE TITLE
[São Paulo] Desenvolvedor Java na PSM Company

### ISSUE THREAD

**Issue by fwfreitas** [backend-br/vagas#383]
Desenvolver Java
Busco Desenvolvedores Java, com forte atuação com Java2 EE, Html, JSP, JavaScript, JBOSS, banco de dados PL/SQL.
Região: Bela Vista
Contratação: CLT + Benefícios.
Tempo: Indeterminado.

Interessados encaminhar currículo com pretensão salarial para francisco.freitas@psmcompany.com.br

Em seu 10º ano de atuação, a PSM Company é referência de mercado nos serviços especializados de Recrutamento e Seleção, Terceirização de Mão de Obra e Gestão de Pessoas.

A nossa história de sucesso, esta baseada em nosso modelo de negócios que proporcionam assertividade e qualidade no processo seletivo, baixo Turn Over e isenção de riscos e passivos trabalhistas.

Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
