### ISSUE TITLE
[SP - Metrô Faria Lima] Node.js Backend Developer (PL/SR) | SmartMEI

### ISSUE THREAD

**Issue by jpventura** [backend-br/vagas#384]
![SmartMEI](https://www.konkero.com.br/revistawp/wp-content/uploads/2018/01/smartmei-e1517427668436.png)

[SmartMEI](https://www.smartmei.com.br/) is inspired by a dream: give all the infrastructure the entrepreneur needs to take care of his business in an easy, intuitive and cheap way, using his smartphone.

We provide a large range of financial services and accounting solutions for those completely ignored by traditional financial institutions and by the Government.

Taking bureaucracy out of the way, entrepreneurs can finally focus on their business and have a better chance of improving their lives and of those around them.

Excited about building a cutting edge fintech to empower millions of Brazilian microentrepreneurs? Join the team! The SmartMEI is now hiring for the **Backend Developer** position!

You'll reshape the core experience of thousands entrepreneurs who are using our solution on a daily basis.

## Job description

Refactor and later maintenance of the backend that powers the [SmartMEI app](https://play.google.com/store/apps/details?id=br.com.smartmei) using JavaScript, TypeScript, Python, Java, and Rails.

## Place

[Metrô Faria Lima, São Paulo - BR](https://goo.gl/maps/XT6gwrJc8ZG2)

## Benefits

- Work remotely or at the office
- Near subway station
- Bike parking place
- Relaxed place with snacks
- Happy-hour with board games
- Periodic tech presentations
- Opportunity to hands-on backend, frontend, chatbot as well

## Requirements

**Required knowledge**

- 2+ years of backend experience
- Creation of RESTful APIs
- Standard MVC, MVP, MVVM, Clean Architecture and derivatives
- Amazon EC2, Amazon S3, Amazon Lambda
- Heroku, Amazon Beanstalk, Google App Engine
- Jasmine, Mocha, or Karma unit test
- Express.js, Django, Flask, Ruby on Rails, Sinatra, or Spring Boot

**Desirable knowledge**
- 4+ years of **Node.js** backend experience
- hapi.js, Koa.js, or Sails.js
- GraphQL, Apollo, Prisma
- Firebase Realtime Database and Firebase Analytics
- Promise, Async/Await, or RxJS
- Firebase Queue, Amazon SQS, Automatic Kue, Apache Kafka, Google Pub/Sub, or Google Tasks

**Expert knowledge**

  - React.js and Redux
  - Advanced React components patterns
  - Server-side rendering with Next.js
  - React Native development
  - Native Android
  - Native iOS

## Hiring

PJ

## How to Apply

Please send an email to [dejavite@smartmei.com.br](mailto:dejavite@smartmei.com.br) with your attached resume (subject: **Backend Developer**).

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by andradefil** [comment]
Sent

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
