### ISSUE TITLE
[São Paulo, Aclimação] Back-end Developer @ Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [backend-br/vagas#3849]
## Nossa empresa
A Pasquali Solution é     uma consultoria com foco em Alocação de profissionais de TI reconhecida     pelo seu trabalho rápido e com excelência.     Estamos há mais de 18     anos no mercado e somos altamente especializada em Tecnologia da     Informação. 

## Descrição da vaga
Procuramos por um Desenvolvedor Back-end Sênior, com familiaridade em C#, VB.Net, Asp.Net, SQL para atuar de forma presencial em cliente nosso.

## Local
Aclimação, SP

## Requisitos

**Obrigatórios:**
•C#
•VB.NET 
•MVVM 
•SQL 
•LINQ 
•WPF 
•Entity Framework
•.Net
•Asp.net

## Contratação
•PJ, 
•Salário a combinar

## Como se candidatar

Por favor envie um email para **catarina.maragno@pasqualisolution.com.br**, ou chame no WhatsApp através do link: 
**https://cutt.ly/sg9jhCe** 

#### Alocação
•Vaga Presencial, atuar na Aclimação, SP
•PJ

#### Nível
•Sênior

**Comment by CarlosHenriqueRC** [comment]
Pena que seja presencial !


******************************************
*Carlos Henrique Ramos Carvalho
*Especialista em Tecnologia .Net
*MCP.Net
******************************************


Em qua., 6 de jan. de 2021 às 15:48, Recrutas <notifications@github.com>
escreveu:
