### ISSUE TITLE
[Blumenau - SC] FullStack Developer na Senior Sistemas

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#386]
Atribuições e Responsabilidades

Responsável por desenvolver, testar e documentar rotinas. Atuar em implementações, correções, melhorias de performance e integrações. Desenvolver códigos bem estruturados utilizando boas práticas de programação. Realizar revisão por pares dos artefatos de programação. Interagir com todo o time de forma construtiva na busca por resultados que agreguem valor aos clientes; Construir código com testes automatizados/unitários para garantir a qualidade.

Requisitos

Indispensável: Superior completo ou cursando em Ciências da Computação, Sistemas de Informação ou 
áreas afins. Vivência em linguagem Java, JavaScript, HTML, CSS, Angular e disponibilidade para aprender novas tecnologias.

Desejável: Conhecimento em outras linguagens de programação e vivência com desenvolvimento ágil.

Os interessados devem se candidatar em nosso site: http://www.senior.com.br/carreiras/; 

Benefícios: VA ou VR, VT, Plano de Saúde, Seguro de Vida, Plano Odontológico, PPLR, Previdência Privada, Auxílio Educação, Auxílio Creche, Convênio Farmácias, SESC, Ginástica Laboral, etc..

**Comment by andradefil** [comment]
Bom dia, remoto ou alocado?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
