### ISSUE TITLE
[Alemanha] Porsche oferece 2.052 vagas de trabalho em TI na Alemanha

### ISSUE THREAD

**Issue by alexandremjacques** [backend-br/vagas#387]
https://canaldointercambio.com/2018/08/porsche-oferece-2-052-vagas-de-trabalho-em-ti-na-alemanha/

**Comment by Kirmayrtomaz** [comment]
@alexandremjacques tem como descrever melhor as vagas?
na issue, ao meu ver isso é só uma noticia e nao se refere num proposito de apresentar uma oportunidade de trampo específica.

**Comment by alexandremjacques** [comment]
Kirmayr, não há como ser específico. São 2052 vagas com vários perfis.

Se esse tipo de oportunidade não é interessante, evitarei postar.

Abs.

Alexandre Jacques
11 95055.1377

**Comment by Kirmayrtomaz** [comment]
Não quero que me entenda mal, 
mas no meu ponto de vista é a mesma coisa que assistir o jornal e dizer que o brasil tem muita oportunidade. 
Se puder ajudar a gente com vagas mais específica, fica mais fácil pra pessoas que acessam o projeto, encontrar algo de interesse mais objetivo.

att.

**Comment by alexandremjacques** [comment]
Claro, sem problemas.

Serei mais específico nas próximas.

Abs.

Alexandre Jacques
11 95055.1377
