### ISSUE TITLE
Itajaí Back-end Developer @ DMX Logística

### ISSUE THREAD

**Issue by gabrielanatascha** [backend-br/vagas#3877]
VAGA 100% PRESENCIAL.

Requisitos: Lógica de programação, regras de negócio e visão analítica. 

Techs: PHP, HTML, SQL e CSS. 

Ferramentas: Laravel, VueJS, PostgreSQL.

Desejáveis: Git e MongoDB. 

A empresa oferece salário de R$ 5.000,00 em modelo PJ ou CLT. Estacionamento e refeitório no local, assistência médica. 

Interessados deverão encaminhar currículo para: escolhacertarh19@gmail.com com o título da vaga.

**Comment by Railton98** [comment]
Possibilidade de trabalho remoto?

**Comment by gabrielanatascha** [comment]
Oi Railton,

tudo bem?

Infelizmente não, 100% presencial.

Em sex., 8 de jan. de 2021 às 10:18, Railton Leal Rodrigues <
notifications@github.com> escreveu:
