### ISSUE TITLE
[São Paulo] Backend Developer na [MIRA EDUCAÇÃO]

### ISSUE THREAD

**Issue by MiraEduc** [backend-br/vagas#389]
O time de engenheiros de software backend é responsável pela arquitetura, desenvolvimento e manutenção dos micros serviços que dão suporte às aplicações mobile e web da Mira Educação. Nosso time de engenheiros de software se preocupam em utilizar as melhores tecnologias e metodologias de desenvolvimento para encontrar as melhores soluções possíveis para os problemas do dia a dia, além de sempre estarem estudando coisas novas e constantemente propondo sugestões de melhorias.

Estamos crescendo e precisamos aumentar o nosso time. Procuramos engenheiros de software apaixonados por tecnologia, que se identifiquem com os valores e missão da Mira Educação. Que não se limitem apenas em resolver o problema, mas também em encontrar a melhor solução dentre as demais.

**Como Sênior Software Engineer Backend os seus maiores desafios serão:**
- Desenhar, desenvolver e manter micro serviços que solucionem da forma mais eficaz, eficiente e segura as demandas vindas de produto e marketing;
- Auxiliar tecnicamente o time com o conhecimento e experiência;
- Ser agnóstico a linguagens e estar disposto a conhecer, estudar e aplicar novas linguagens e tecnologias.

**Oque esperamos de você:**
- Experiência com desenvolvimento de software;
- Conhecimento em algumas das linguagens e tecnologias de backend;
- Java / Kotlin com SpringBoot
- Python com Flask ou Django
- Preocupação constante com arquitetura e documentação;
- Implementar testes;
- Familiaridade com Git;
- Compartilhar conhecimentos, discutir soluções, trabalhar em equipe;
- Sempre ter um olhar crítico e propor melhorias na organização do código, estrutura e arquitetura quando achar necessário;
- Expor sua opinião, independente da opinião dos demais.

**Diferenciais:** 
- Interesse em diferentes linguagens e frameworks (Go, R, Ruby, Scala, Clojure, Groovy);
- Conhecimentos em plataformas cloud (AWS, GCP ou Azure)
- Docker, Kubernetes, EFK, CI & CD, Oauth2, Mensagerias

**Benefícios:**
- Assistência Médica e Odontológica - 100% custeada pela empresa;
- Vale Refeição;
- Vale Alimentação ou Combustível;
- Vale Cultura;
- Gympass;
- Auxílio Creche;
- PLR – Atrelado a metas;
- Desconto com escola de idiomas;
- Quick Massage;
- Flexíveis: Happy Hour toda sexta, Snacks à vontade, Sala de descanso, Vídeo game, Dresscode e ambiente informal;
- Ótima localização, ao lado do metrô Santa Cruz;

Interessados encaminhar e-mail com currículo para: rh@miraeducacao.com.br ou cadastrar em nossa página de carreiras: https://jobs.kenoby.com/miraeducacao/job/senior-software-engineer-backend/5b7d5336d2d0316995c25ae0

Labels:
- Sênior
- CLT
- São Paulo-SP
- Presencial

**Comment by joaopdto** [comment]
Bom dia,
Vagas para estágio?
