### ISSUE TITLE
[Pinhais / PR] Desenvolvedor PHP

### ISSUE THREAD

**Issue by gabrielak2** [backend-br/vagas#39]
K2 Partnering busca Desenvolvedor PHP para atuação em cliente. 

Necessário experiência com mais alguma linguagem de desenvolvimento: PHP, Node, Python, Ruby, Go Lang, Java, ou .Net.

Contratação CLT.
Interessados encaminhar cv para: gpedro@k2partnering.com

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
