### ISSUE TITLE
[Campinas] Developer Trainee Enforce [SHARE]

### ISSUE THREAD

**Issue by felipelima0808** [backend-br/vagas#390]
Programa de trainees Enforce para profissionais de tecnologia, acessem o site para mais informações:  ### traineesenforce.com.br

**Comment by Kirmayrtomaz** [comment]
vc pode colocar descricao da vaga? @felipelima0808 
e mais detalhes sobre essa oferta?
procura outras issues que tem referencia de como estamos mostando
