### ISSUE TITLE
[Uberlândia] Pessoa Desenvolvedora C-Sharp [Explend Soluções]

### ISSUE THREAD

**Issue by Dervanil** [backend-br/vagas#395]
**Suas responsabilidades são:**
- Desenvolvimento de aplicações em C#, responsáveis por integrar nossos sistemas locais com as aplicações em nuvem;
- Implementar APIs Rest para as aplicações em nuvem;
- Implementar testes unitários (TDD) e de integração.

**Como é?**
Temos um ambiente sem burocracias, com uma equipe pequena e focada em levar sucesso aos nossos clientes, seguindo nosso propósito: 'Soluções inteligentes para pessoas'.

**O que esperamos para esta vaga?**
Entrega de valor para a equipe e para empresa, pessoa com vontade de aprender e crescer, que esteja disposta a encarar os desafios junto com a equipe.

**Onde você atuará:**
Você será parte de uma equipe multifuncional, desenvolvendo nossos produtos em nuvem, tendo a oportunidade de crescer e contribuir conosco.

**Experiência relevantes:**
- Experiência em desenvolvimento C#;
- Programação orientada a objetos;
- Testes automatizados (TDD);
- Acesso a dados utilizando ferramentas de ORM;
- Banco de dados SQL e/ou NoSQL.

**Diferenciais:**
- Git;
- Experiência com práticas ágeis;
- Microsoft Azure, preferencialmente em PaaS;
- Windows Form;
- Microsoft SQL Server;
- Design Patterns, (SOLID, YAGNI, BDUF);
- Asp .Net MVC.

**Benefícios:**
- Ticket alimentação;
- Convênio médico;
- Convênio odontologico;
- Seguro de vida;
- Ajuda de custo.

**Remuneração:**
De acordo com a experiência profissional.

[Contato](https://www.recrutamento.explend.com.br/detalhe-da-vaga/pessoa-desenvolvedora-c-sharp)

**Comment by FelipeFSilva** [comment]
Permite remoto?

**Comment by Dervanil** [comment]
@FelipeFSilva Infelizmente no momento não.
