### ISSUE TITLE
[Remoto ou Presencial em São Paulo] Back-end Developer @ Smart Fit/Bio Ritmo

### ISSUE THREAD

**Issue by alessandrogurgel** [backend-br/vagas#3957]
## Nossa empresa

O Grupo Bio Ritmo detém as marcas **Smart Fit**, Bio Ritmo e as recém lançadas Totalpass, Nós, dentre outras, que juntas têm mais de 1000 unidades e milhões de alunos ativos no Brasil, México, Chile, Peru, Colômbia, Agentina e +15. O grupo é líder em seu segmento na América Latina e está entre os 5 maiores do mundo. Recentemente, o grupo também vem investindo em produtos digitais como Smart Nutri, Smart Fit Go e Queima Diária além das academias físicas.

Apesar de anos no mercado, a estrutura da empresa é bastante flexível e ágil. Temos acessos aos gestores e diretores de tecnologia, temos bastante autonamia, temos um ambiente bastante propício a inovação. Há bastante espaço para aprendizagem e crescimento decorrente de criação de novos produtos e sistemas, integração entre sistemas, aperfeiçoamento e otimização de infraestrutura, bem como manutenção de aplicações complexas e distribuídas para atender a maior rede de academias da América Latina. Há muitos desafios e muita vonta/disposição da empresa em atendê-los propiciando um ambiente dinâmico, ágil e com muita oportunidade de crescimento dentro do grupo. Além disso, o departamento de Desenvolvimento de software  se esforça para manter um ambiente descontraído, onde a opinião de todos reflete nas decisões da equipe.

## Descrição da vaga

Desenvolvedor Backend Ruby on Rails. Atualmente temos vagas para junior, pleno e sênior.

## Local

Remoto ou presencialmente em São Paulo. Nosso escritório em São Paulo está localizado na Avenida Paulista próximo a FIESP. Para os que trabalham pressencialmente, também temos política de 2 dias de home office por semana. Como atendemos projetos internacionais, aceitamos também candidatos latinos.

## Responsabilidades
- Garantir a implementação e implantação dos projetos solicitados;
- Arquitetar as soluções de projeto trazidas por nossos Product Owners ou identificadas pela própria equipe;
- Zelar pela qualidade do código desenvolvido e pela saúde dos sistemas implantados;
- Orientar desenvolvedores juniores.
- Para sêniores, estar apto a trabalhar com Devops.

**Requisitos**
- Já ter trabalho em equipes ágeis;
- Sólida experiência em Ruby on Rails para backend para vagas pleno e sênior (>= 2 anos);
- Conhecimentos em HTML, CSS e Javascript; (não obrigatório em alguns projetos)

**Diferenciais (Plus)**
- Espanhol e/ou Inglês; Em particular, temos uma vaga específica para atender demandas da operação do México
- Devops com AWS (OpsWorks, EC2, RDS, S3, Lambda, API Gateway, ELB) ou Google Cloud Plataform (backend)
- Docker (backend)
- Conhecimentos básicos de UI/UX (frontend)

## Benefícios
- Plano de saúde após um tempo na empresa e com coparticipação.
- Utilização de todas as academias e marcas do grupo
- Verba dedicada para cursos, livros, eventos e congressos

## Contratação

- Preferencialmente CLT mas  trabalhamos com PJ também.

## Como se candidatar

Por favor envie um email para santana.aline@bioritmo.com.br e alessandro.gurgel@smartfit.com com seu CV anexado - enviar no assunto: Vaga Backend Ruby on Rails

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20~25 dias após cada processo. Contudo, o processo em si, é bem simples e rápido.

#### Faixa Salarial
- 5~14K CLT

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by rhuancarlos** [comment]
Bom dia, tenho conhecimento a nível de Júnior por enquanto no ruby, consigo pleitear uma vaga para este nível de experiência ?
