### ISSUE TITLE
[São Paulo] Back-End PHP Developer na [PontoCode]

### ISSUE THREAD

**Issue by leoallvess** [backend-br/vagas#397]
Descrição
Procuramos um(a) Desenvolvedor PHP Pleno / Sênior com vontade de aprender e ensinar, disposto a vestir a camisa e crescer conosco. 
Estamos modelando nossos processos, então sua experiência será importante para nós.

#  Pleno / Sênior
# CLT ou PJ

Atribuições: 
- Ajudar no desenho, documentação e desenvolvimento de sistemas; 
- Manutenção em sistemas e sites;

Requisitos
- Experiência significativa com desenvolvimento em php 5+
- Experiência com laravel 5+
- Controle de versão com git
- Vagrant
- Mysql
- Comprometimento

Desejável
- Experiência em plataformas open source (wordpress e magento)
- Experiência em integrações com apis
- Aws
- Npm
- Estrutura de servidores e processos de deploy
- Proatividade para resolução de problemas

Por favor envie um email para leonardoalves@coldvector.com com seu CV anexado - enviar no assunto: Back-End PHP Developer

**Comment by hilderjares** [comment]
aceita 100% home office ?


Em ter, 28 de ago de 2018 às 11:10, leoallvess <notifications@github.com>
escreveu:

**Comment by leoallvess** [comment]
Para esta vaga não @hilderjares, precisa ser presencial aqui na Av. Paulista

**Comment by leoallvess** [comment]
up
