### ISSUE TITLE
[ Belo Horizonte ] Back End em Fintech [ Plano de Vida ]

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#398]
**Sobre a empresa:**

Nascemos da vontade de impactar vidas e transformar histórias financeiras.
 
A Plano de Vida® é uma metodologia inovadora que auxilia nossos clientes na conquista de sonhos e
projetos de vida, através de soluções personalizadas para cada propósito de vida.

**Ocupações do cargo**

Desenvolvedor backend em Fintech especialista em assessoria financeira pessoal. Profissional será responsável pela evolução da plataforma ruby on rails.

Perfil empreendedor, comprometido com a visão do negócio e com sede de liderança. Objetivo de médio prazo é se tornar sócio e desenvolver papel fundamental no relacionamento com futuros investidores. Habilidades de front end são desejáveis e contam muitos pontos.

Modelo de trabalho flexivel, bom senso em respeitar a criatividade para maximizar a produtividade do profissional. Oportunidade única de desenvolver uma solução inovadora para um problema tão comum aos brasileiros: como lidar com o próprio dinheiro.

**Benefícios**

Vale Refeição;
Vale Transporte;
Participar de hackatons, mentorias e eventos de tecnologia;
Participação nos lucros semestral;
Plano de sociedade na empresa;
Participação em programas de aceleração de startup

**Aptidões e qualidades**

Domínio linguagem Ruby ou PHP;
Framework Rubyonrails;
Conhecimentos em javascript, CSS e HTML;
Visão de negócio;
Muita vontade de crescer;
Espírito de liderança.

**Informações da empresa**

MUDE SUA FORMA DE LIDAR COM O DINHEIRO COM A PLANO DE VIDA!

Plataforma de planejamento financeiro pessoal para a conquista de projetos de vida através da otimização do orçamento, assessoria de investimentos e educação financeira. 

**Como se candidatar:**

Basta clicar no link a seguir: http://bit.ly/2NqqcBt

**Nível de experiência**

Pleno / Junior

**Comment by megandavulpi** [comment]
Como se candidatar:

Basta clicar no link a seguir: http://bit.ly/2NqqcBt

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by megandavulpi** [comment]
@guilhermeoa07 : Pleno / Junior
