### ISSUE TITLE
Backend Developer

### ISSUE THREAD

**Issue by Deboralopes2019** [backend-br/vagas#400]
Desenvolvedor Backend pleno e sênior com experiência em RUBY / RAILS,GIT / GITFLOW,REST,CLOUD
TDD / RESPEC,DEPLOY
Profissional será responsável por estruturação e atenção com a persistência dos dados, regras de negócio, segurança da informação, performance e etc.

CVs enviar para debora.lopes@drltalents.com.br

contratação pj mais benefícios

**Comment by reginaldojunior** [comment]
Falta informações.
