### ISSUE TITLE
Sao Paulo Backend Developer

### ISSUE THREAD

**Issue by Deboralopes2019** [backend-br/vagas#401]
Desenvolvedor Backend pleno e sênior para zona oeste, sp

Principais atividades
Profissional será responsável por estruturação e atenção com a persistência dos dados, regras de negócio, segurança da informação, performance e etc.

Requisitos

RUBY / RAILS
GIT / GITFLOW
REST
CLOUD
TDD / RESPEC
DEPLOY
 
Contratação PJ mais benefícios, local Barra Funda
 Cvs enviar para debora.lopes@drltalents.com.br

**Comment by paulogdm** [comment]
```
Angular 2+ Sênior
HTML – Sênior
CSS – Sênior
(...)
```
Você tem certeza que isso não é "Front" ou pelo menos "FullStack"?

**Comment by Deboralopes2019** [comment]
&nbsp;
&nbsp;

sim errei o perfil

vou corrigir

obrigada

Em Tue, 28 Aug 2018 20:28:19 +0000 (UTC), paulogdm  escreveu:
&nbsp;
Angular 2+ Sênior
HTML – Sênior
CSS – Sênior
(...)


Você tem certeza que isso não é "Front" ou pelo menos "FullStack"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/backend-br/vagas/issues/401#issuecomment-416729070",
"url": "https://github.com/backend-br/vagas/issues/401#issuecomment-416729070",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [backend-br/vagas] Sao Paulo Backend Developer (#401)",
"sections": [
{
"text": "",
"activityTitle": "**paulogdm**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@paulogdm",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"backend-br/vagas\",\n\"issueId\": 401,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"backend-br/vagas\",\n\"issueId\": 401\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/backend-br/vagas/issues/401#issuecomment-416729070"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 373335332\n}"
}
],
"themeColor": "26292E"
}
]
