### ISSUE TITLE
[SÃO PAULO] Desenvolvedor PHP Laravel Sênior @Digi

### ISSUE THREAD

**Issue by BarbaraOgoshi** [backend-br/vagas#4020]
Descrição da vaga

Desenvolvimentos de plataforma digitais para grandes clientes com foco em campanhas de incentivo. Buscamos um profissional para atuar em nosso time de Tecnologia no cargo de Desenvolvedor PHP Laravel (nível Senior).

Descrição da Vaga: Será responsável por desenvolvimentos de plataformas digitais com integração com front-end, time de GPs e Head de tecnologia.
Sólidos conhecimentos em: PHP Laravel

Requisitos Obrigatórios:
Organização, disciplina trabalho em equipe, pontualidade, planejamento, espírito de liderança, precisão em estimativas e entregas são essenciais para essa vaga.

Local
Remoto, São Paulo
Benefícios
Recesso Remunerado
Day-off aniversário
Zenklub

Como se candidatar
Por favor envie um e-mail para lorraine@grupodigi.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor PHP Laravel Senior.

Labels
🏢 Flexível
🏢 Remoto
👴 Sênior
⚖️ A-Combinar
⚖️ PJ
💰 10k-11k

**Comment by danielhe4rt** [comment]
Alô, seguinte: o que mais além de laravel é necessário saber? 

Ficou essa dúvida ai pois pra um sênior geralmente reflete muito mais conhecimento nas tecnologias que a empresa usa.

**Comment by BarbaraOgoshi** [comment]
Alô,

 

O entendimento no dia a dia dos projetos e saber lidar com pessoas e prazos é essencial.

Estou direcionando seu questionamento ao líder da área e ele te dará o retorno das especificações detalhadas com relação a tecnologia.

 

Agradeço a candidatura.

Att,

 

 



 

De: Daniel Reis <notifications@github.com> 
Enviada em: sexta-feira, 22 de janeiro de 2021 20:45
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: BarbaraOgoshi <barbara@grupodigi.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [SÃO PAULO] Desenvolvedor PHP Laravel Sênior @Digi (#4020)

 

Alô, seguinte: o que mais além de laravel é necessário saber?

Ficou essa dúvida ai pois pra um sênior geralmente reflete muito mais conhecimento nas tecnologias que a empresa usa.
