### ISSUE TITLE
[São Paulo / Remoto ]  Full Stack Developer (Foco Back-end) Java @ Vórtx

### ISSUE THREAD

**Issue by jhomarolo-vortx** [backend-br/vagas#4022]
## Nossa empresa

Somos um time de tecnologia com foco no cliente (interno e externo) e em inovação constante, sempre voltado para resultados de negócio e entregas.

Também somos agilistas, portanto XP/SCRUM/Kanban/Pair Programming fazem parte do nosso dia a dia. Inclusive trabalhamos em Squads.

## Descrição da vaga

 No momento possuímos algumas vagas para pessoas desenvolvedoras, as vagas para **TODOS** os níveis de experiência.

Desenvolver novas funcionalidades, módulos e serviços para os nossos sistemas.

Irá atuar em todas as fases de um processo de software, desde as análises e levantamento dos requisitos, passando pelo desenvolvimento e testes, e chegando até a implantação e entrega.

Atuará também nas atividades pós-entrega de acordo com as demandas, como monitoramento, sustentação e manutenção do sistema, análises de performance e stress das rotinas.

A Stack desta squad é principalmente feita em JAVA;

Gostamos muito de DDD/ BDD / TDD / Clean Architecture, estes conceitos precisam estar claros para você pois irá colocá-los em prática aqui.

Nosso site: https://vortx.com.br/
## Local

Remoto ou Escritório (estamos remoto durante a pandemia) , São Paulo - em frente ao metrô Pinheiros

## Requisitos

**Obrigatórios:**

· Conhecimento sólido em arquitetura web;
· Conhecimento sólido em linguagem Java;
· Sede por aprender coisas novas;
· Boa comunicação e gostar de trabalhar em equipe.

**Desejáveis:**
· React JS, Git, javascript e typescript.
· Oracle;
· AWS;
· Angular / React

**Diferenciais:**
- Linux.

## Benefícios

- Plano de saúde
- VR/VA de R$ 1.150 por mês
- Auxílio creche
- Bônus (PLR)
- Auxílio educação
- Oportunidade de compra de ações 

## Contratação

CLT Full

## Como se candidatar

Se cadastre pelo [Kenoby](https://jobs.kenoby.com/vortx/job/desenvolvedor-full-stack-java-vorasys/5f8ddc73a3879142efd0f8b8?utm_source=website)

## Tempo médio de feedbacks

Nosso processo é bem rápido e costumamos não ser burocráticos.
Costumamos enviar feedbacks em até 2 dias após cada processo. E o processo no total costuma levar de 1 a duas semanas.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by GeorgeHenriqueGH** [comment]
Tem como fazer pra mim?

**Comment by GeorgeHenriqueGH** [comment]
Eu to aprendendo Spring, Angular e uso Linux também sei MySQL

**Comment by jhomarolo-vortx** [comment]
Está em aberto
