### ISSUE TITLE
[São Paulo - SP] Net Developer na Giganti (Junior ou Estágio)

### ISSUE THREAD

**Issue by darrudanoo** [backend-br/vagas#404]
## Descrição da vaga

Procuramos backend para nosso time, irá trabalhar em sites, sistemas, aplicativos, desenvolvendo api e com manutenção em muita coisa. Pra quem está a fim de aprender e começar a carreira com a mão na massa!

## Local

Escritório, São Paulo - Santo Amaro _(ao lado da estação de trem e metrô)_

## Benefícios

- Oportunidade Crescimento
- Plano de desenvolvimento individual
- Ferias Coletivas

#### Diferenciais

- Horário flexivel
- No dress code
- Ambiente
- Vídeo game, café e sinuca
- Participação em outros projetos com ideias e sugestões

## Requisitos

**Obrigatórios:**
- C#
- Boa lógica
- Conhecimento do conceito de Orientação a Objetos
- Conhecimento do conceito de Herança
- Conhecimento do conceito de Implementação de Interface
- Conhecimento do conceito de Injeção de Dependência
- Conhecimento do conceito de MVC

**Desejáveis:**
- aspnet core 2
- Javascript
- HTML
- CSS
- PL/SQL

## Nossa empresa

A Giganti é uma empresa de inovação com grande foco em projetos de tecnologia e startups, temos um time multidisciplinar e apaixonado por fazer acontecer. Usamos diversas abordagens, metodologias, muita empatia e tecnologia pra entregar soluções que encantam nossos clientes!

## Como se candidatar

Por favor envie um e-mail para atendimento@giganti.com.br com:
- Assunto: Vaga Back Júnior
- Seu CV anexado 
- Faça o teste: http://mrcoach.com.br/teste-perfil-comportamental-disc.php
- Envio o print do resultado anexado ao email

## Labels
- C#
- Estágiario
- MVC
- Junior
- .Net

**Comment by X-X-Xavito** [comment]
Vaga ainda está em aberto?

**Comment by darrudanoo** [comment]
Sim!

> Vaga ainda está em aberto?

Sim!

**Comment by Doutrek** [comment]
Vaga aberta ainda ?

**Comment by walteralleyz** [comment]
Possui vaga Junior/Estágio para desenvolvedor NodeJS?

**Comment by hilderjares** [comment]
Aceita remoto ?
