### ISSUE TITLE
[Remoto] Backend Developer PHP/Node na XGrow

### ISSUE THREAD

**Issue by geekrootbr** [backend-br/vagas#4054]
**Descrição da vaga**
Somos uma empresa parte de um grupo de diversas startups, estamos procurando um desenvolvedor back end com conhecimentos profundos de Laravel e MySQL. Buscamos um profissional com visão de longo prazo de crescimento em conjunto com a empresa e colaboração com a equipe para o crescimento do projeto.

**Local**
Remoto ou Escritório, São Paulo ou Santos

Benefícios
Participação em resultados

**Requisitos**

**Obrigatórios:**

5+ anos Experiência com desenvolvimento PHP
4+ anos experiência com desenvolvimento em Laravel
Experiência com MySQL
RestAPI

**Desejáveis:**

Conhecimentos de React
Conhecimentos de NodeJS

Contratação
PJ a combinar

Nossa empresa
Somos um grupo de 20 startups nas mais diversas áreas de atuação no Brasil, Portugal e EUA. Procuramos profissionais para uma parceria de longo prazo no projeto que você entrou ou outro dentro de nosso grupo.

**Como se candidatar**
Por favor envie um email para rh@triadps.com com seu CV anexado - enviar no assunto: Vaga PHP Laravel

Labels
🏢 Flexível
🏢 Remoto
👨 Pleno/Senior
⚖️ A-Combinar
⚖️ PJ

**Comment by NomiasSR** [comment]
Tenho interesse em participar de sua equipe, segue em anexo cópia de meu cv para sua avaliação. Obrigado
[curriculum_paulo_saimon_enviar.pdf](https://github.com/backend-br/vagas/files/5983694/curriculum_paulo_saimon_enviar.pdf)
