### ISSUE TITLE
[Remota] Back-end Developer PHP Pleno/Senior @UP Outsourcing

### ISSUE THREAD

**Issue by giovanarezende** [backend-br/vagas#4067]
> Vaga Remota durante a pandemia

## Nossa empresa

A UP é uma empresa de OutSourcing, Consultoria e Startup, responsável pelo desenvolvimento de sistemas web. 

Fornecemos oportunidades para desenvolvedores Web baseado em Princípios de Desenvolvimento Ágil e também auxiliamos Startups em Protótipos usando Princípios de Inovação para a necessidade do cliente.

Se você é curioso(a), colaborativo(a) e busca por inovação, dinamismo e propósito, venha fazer parte do nosso time!

## Descrição da vaga

A UP Outsourcing está com uma oportunidade de Programador PHP Backend Pleno/Senior para atuar com a construção de recursos que envolvem tecnologias de back-end (servidores, banco de dados, modelagem e programação) para um cliente norte-americano da UP.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Inglês intermediário
- Experiência sólida com PHP 
- Experiência com Banco de Dados MySQL
- Conhecimentos em Javascript / jQuery
- Conhecimentos com API / REST / XML / SOAP

**Diferenciais:**
- Boa conversação no inglês
- Mais de 6 anos de experiência com PHP

## Benefícios

- Modalidade PJ
- Aulas de Inglês avançado para Empresas
- 10 dias pagos de férias
- Horário flexível (respeitando eventuais reuniões com base no fuso da Europa)
- Home Office
- Escritório em Bauru/SP com estrutura de suporte completa
- PLR Mensal
- Cursos e Certificações
- Webinars e ajuda de profissional para Saúde Mental
- Folga em dias específicos previamente planejado

## Contratação

PJ

## Como se candidatar

Se interessou? Corra e mande o seu currículo para rh@upoutsourcing.com

#### Alocação

- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by NomiasSR** [comment]
Tenho interesse pela vaga, segue em anexo meu cv. Obrigado
[curriculum_paulo_saimon_enviar.pdf](https://github.com/backend-br/vagas/files/5983687/curriculum_paulo_saimon_enviar.pdf)
