### ISSUE TITLE
[Arujá / SP] Ruby Back-End Developer na RH Software

### ISSUE THREAD

**Issue by felipelomba** [backend-br/vagas#41]
**Sobre a vaga**
Buscamos desenvolvedores apaixonados por tecnologia, que queiram crescer com a empresa e aumentar a qualidade de nossos produtos.
Temos um time em crescimento e nossa stack está em evolução. Valorizamos o desempenho e comprometimento de todos do time.

**Responsabilidades do candidato**
Desenvolva recursos robustos, escaláveis e seguros
Escreva um código limpo, sustentável e eficiente
Participe de todas as etapas do ciclo de vida do desenvolvimento
Implementar melhores práticas de desenvolvimento orientado a testes, integração contínua, SCRUM, refatoração e padrões de código, e assim por diante
Mantenha-se informado sobre as novas tecnologias relevantes e promova sua adoção e integração contínuas no design

**Requisitos para a vaga**
2 anos de experiência em desenvolvimento com Ruby
Habilidade de escrever código simples, limpo e eficiente
Excelente conhecimento de análise e design orientado a objeto
Conhecimentos desenvolviemento de aplicações api-only com Ruby on Rails

**Diferenciais**
Frameworks frontend (AngularJS/VueJS)
HTML/CSS/Javascript
Elixir/Phoenix
AWS

**Comment by pskoike** [comment]
Oi Felipe, a vaga ainda está aberta? Abs

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
