### ISSUE TITLE
[Santa Barbara D'Oeste] Full Stack Developer na Acruxx

### ISSUE THREAD

**Issue by tuliomachado-acruxx** [backend-br/vagas#414]
## Descrição da vaga

- Atuar em correções e melhorias do software utilizando PHP, Javascprit e Postgresql;
- Buscar novas ferramentas e técnicas para a melhoria continua de nossos sistemas 
- Participar do processo criativo e auxiliar na construção dos sistemas. 
- Nos deixar impressionados com sua capacidade criativa

## Local

Remoto ou Escritório, Santa Barbara D'Oeste

## Benefícios

- VA
- Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
- No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

#### Diferenciais

- Área de descanso
- Frutas no escritório
- Café expresso ou coado
- Chá
- Cachorro no ambiente de trabalho

## Requisitos

**Obrigatórios:**
- Bons conhecimentos PHP, Javascript e SQL;
- Boa experiência em HTML5/CSS e na construção de websites responsivos/adaptáveis para mobile

**Diferenciais:**
- Bons conhecimento em JavaScript/CSS frameworks

## Contratação
- CLT

## Nossa empresa

Percepção, motivação e aprendizagem são os elementos propulsores do desenvolvimento da humanidade.

Assim é com a Acruxx, uma empresa focada e motivada pelos desafios de novos projetos, novas tecnologias, geração e uso inteligente da informação a órgãos públicos.

## Como se candidatar

Por favor envie um email para tulio@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

**Comment by guilhermeoa07** [comment]
Qual senioridade?

**Comment by tuliomachado-acruxx** [comment]
Nenhuma específica, mas estamos dando preferência a quem tem mais de um ano de experiência com PHP.

**Comment by guilhermeoa07** [comment]
Ok. A entrevista pode ser remotamente? Tenho interesse mas só posso ir em caso de contratação

**Comment by tuliomachado-acruxx** [comment]
Caso o candidato passe no primeiro filtro do nosso processo de seleção, estaremos entrando em contato para entrevista (remotamente ou presencial) dependendo da localização do candidato.
