### ISSUE TITLE
[Vitória-ES/Remoto] Wordpress Developer na Parresia

### ISSUE THREAD

**Issue by philipedornelas** [backend-br/vagas#419]
## Descrição da vaga
Wordpress developer é responsável tanto pelo back-end quanto pelo desenvolvimento de front-end, incluindo criar temas e plugins específicos para os projetos.

Esperamos que você tenha um forte conhecimento das tendências mais recentes do setor e dos sistemas de gerenciamento de conteúdo.

## Local
Remoto ou Escritório, Vitória - ES

## Requisitos
**Obrigatórios:**

- Bom entendimento de tecnologias front-end, incluindo HTML5, CSS3, JavaScript, jQuery;
- Experiência na criação de interfaces de usuário para sites e / ou aplicativos da web;
- Experiência em criação e desenvolvimento de websites de design responsivo;
- Depuração como o Firebug, o inspetor do Chrome, etc.;
- Capacidade de entender as alterações do CSS e suas ramificações para garantir um estilo consistente em todas as plataformas e navegadores;
- Capacidade de converter layouts e wireframes abrangentes em páginas HTML de trabalho;
- Conhecimento de como interagir com APIs e formatos RESTful (JSON, XML);
- Compreensão proficiente das ferramentas de controle de versão de código(GIT);
- Forte compreensão do desenvolvimento de back-end do PHP;
- Conhecimento em modelagem de banco de dados e suas estruturas (SQL e NoSQL);
- Manter o código atualizado e documentado;
- Profile e Audits para melhoria de performances.

## Desejáveis:
- SEO;
- PWA;
- Gerenciamento de pacotes e Front-end developer tool.

## Principais responsabilidades
- Projetar e implementar novos recursos e funcionalidades em projetos novos e existentes;
- Estabelecer e criar a arquitetura do projeto;
- Garantir alto desempenho e disponibilidade, e gerenciar todos os aspectos técnicos do CMS;
- Ajudar a formular um design eficaz e responsivo e transformá-lo em um tema e plug-in funcionais;
- Integrar plataforma de testes;
- Garantir qualidade visual (front-end) para entregas finais.

## Diferenciais:
- Infraestrutura de servidor (AWS, Digital Ocean, etc);

## Contratação
- PJ a combinar

## Nossa empresa
A [Parresia](parresia.com) é uma agência especializada em atender instituições religiosas com oito anos de mercado, desenvolvendo soluções tecnológicas como sites, portais e aplicativos. 

## Como se candidatar
Por favor envie um email para daniela.gomes@parresia.com com seu CV anexado - enviar no assunto: Vaga Wordpress Developer

## Labels
- Alocado
- Remoto
- WordPress
- PJ

**Comment by philipedornelas** [comment]
Reabrindo a Vaga!

**Comment by thalisonwilker** [comment]
Enviado =)
