### ISSUE TITLE
[Rio de Janeiro] Python/Django Developer Pleno no GloboEsporte.com

### ISSUE THREAD

**Issue by rperiago** [backend-br/vagas#42]
O GloboEsporte.com está procurando uma pessoa para o nosso time de desenvolvedores na redação do Esporte da Globo. A posição faz parte dos nossos planos em fortalecer a equipe e potencializar o trabalho da maior redação de esportes da América Latina.

A pessoa trabalhará com a equipe criando ferramentas jornalísticas que ampliem a escala e autonomia dos jornalistas e desenvolvedores em criar conteúdo digital para um público digital. Também dará apoio a áreas de estratégia de crescimento, insights para redação, na formulação de sistemas que auxiliem o dia a dia da redação do GloboEsporte.com.

## Local
Barra da Tijuca - Rio de Janeiro

## Contratação
CLT + Benefícios

## Responsabilidades

- participar da definição e implementação de novas funcionalidades e/ou melhorias as que já existem
- usar observação e análise para recomendar melhorias gradativas a infraestrutura do time
- influenciar lideranças da nossa organização a tomar decisões baseadas nos dados produzidos para conseguir novas oportunidades de negócios
- ampliar a capacidade do time entender a efetividade do seu trabalho respeitando processos e modernizando gradativamente as tecnologias utilizadas
- documentar e comunicar descobertas e insights para membros os membros do time
- trabalhar em sintonia com a redação e outros desenvolvedores
- usar dados exploratórios para compreender profundamente como a redação interage com a produção do time
- agir rapidamente para a solução de problemas

## Requerido
- 3+ anos trabalhando com Python
- conhecimento em Django
- excelente competência analítica e conceitual
- capacidade de pensar estrategicamente e interpretar informações de consumo da redação
- boa capacidade de comunicação e apresentação - tanto escrita quanto verbal
- habilidade de trabalho em equipe, pois colaboração é parte crucial do nosso trabalho
- paixão por jornalismo, informação e esportes
- senso de humor

### Desejável

- Conhecimentos em React
- Experiência com JavaScript ES6
- DevOps

## Como se candidatar

Por favor envie um email para ricardo.periago@globoesporte.com com seu CV anexado e/ou url para LinkedIn, GitHub etc.  Enviar no assunto: Vaga Python/Django Developer Pleno

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
