### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na Brbid

### ISSUE THREAD

**Issue by guiljardim** [backend-br/vagas#422]
**Sobre a empresa:** 
A BRbid.com é um marketplace de leilões. Trabalhamos para desenvolver soluções inteligentes tanto em tecnologia quanto em serviços para esse setor.

Temos um compromisso com a leiloaria no Brasil. 

A Leiloaria é um modelo de comercialização muito tradicional. Existe ainda muitas possibilidades de inovação e barreiras a serem quebradas. Barreiras que o e-commerce já superou e vemos isso como uma oportunidade.

O leilão funciona muito bem em três cenários: 
quando você precisa de transparência;
quando você possui produtos com escassez (ex.: Arte, Jóias);
Ou quando você tem oportunidade.

Parte do nosso desafio é descobrir e criar mercados onde a leiloaria pode ser viável e tornar os negócios gerados dentro da nossa plataforma interessantes tanto para o comprador, quanto para o vendedor.

**Requisitos obrigatórios:**
Experiência mínima de 2 anos desenvolvendo em python e Django;
Experiência com desenvolvimento em ambiente linux;
Conhecimentos em administração de servidores web e automação de tarefas.

● Contratação CLT ou PJ, você escolhe ;D
● Nosso QG fica no Recreio dos Bandeirantes.

**Benefícios:**
- Vale Transporte ou Vale Combustível
- Vale Refeição ou Alimentação (22,00/por dia)
- Plano de saúde Amil

Nível de experiência:

Pleno

**Como se Candidatar:**
Por favor, envie um email para marcus@brbid.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a) Python/Django.

**Comment by xspager** [comment]
Olá Guilherme, mandei um email mais cedo pro Marcus mas ele ainda não respondeu. Abraço!
