### ISSUE TITLE
[São Paulo, Campinas, Sorocaba (SP) e Blumenau (SC)] Desenvolvedor C# [JUNIOR|PLENO|SENIOR] | HBSIS

### ISSUE THREAD

**Issue by DHO-HBSIS** [backend-br/vagas#424]
Tecnologia, desafios, conhecimento. Isso move sua carreira? Então traga esta energia para nosso time. 
Venha desenvolver produtos que tornam grandes empresas mais eficientes. Venha trabalhar na HBSIS, referência em soluções nas áreas de logística, vendas e outsourcing. Atuar com grandes clientes e projetos nacionais e internacionais.
Estamos com vagas para Analista Desenvolvedor de Sistemas. Você vai conviver em um ambiente sem dress code conhecendo, na prática, a Cultura Lean.

Encare novos desafios em um time que sabe jogar junto. Acelere seu sucesso profissional com a HBSIS.

Benefícios:
Vale refeição ou alimentação
Plano de saúde
Auxílio educação
Seguro de vida
Convênio odontológico
Universidade corporativa
Convênio creche/escola

Para se candidatar: https://hbsis.com.br/trabalhe-conosco/ ou e-mail:trabalheconosco@hbsis.com.br

**Comment by slucascosta** [comment]
Há a possibilidade de ser remoto?
