### ISSUE TITLE
[Remoto] Desenvolvedor(a) Fullstack Python /C# na Seventh 

### ISSUE THREAD

**Issue by valdeci** [backend-br/vagas#4247]
**Descrição da vaga**
Estamos em busca de Desenvolvedor(a) Fullstack com conhecimentos em Python e C# para fazer parte do nosso time que está em pleno crescimento.  Buscamos uma pessoa com perfil analítico e atenção aos detalhes, que tenha autonomia e seja proativo. 

**Requisitos**
- Python 2 e 3
- Pip
- SQLite Database
- RabbitMQ
- Rest API
- Webhooks
- Git

**Desejável**
- Conhecimento em AWS / Azure
- C# web

**Benefícios**
- Plano de Saúde 100% custeado pela empresa (dependentes tem coparticipação)
- Plano Odontológico 100% custeado pela empresa (para colaboradores e dependentes)
- Vale Alimentação e/ou Refeição
- Seguro de Vida 100% custeado pela empresa
- PLR
- Day off de Aniversário.
- Programas de descontos/diversos convênios

**Contratação**
CLT

**Nossa empresa**
A Seventh está em pleno crescimento e busca novos talentos para fortalecer o time em 2021.
Se você tem um perfil inovador, gosta de tecnologia e está disposto a vestir essa camisa #vemprotime

_Saiba mais:_
https://youtu.be/-bqN-EZj0cg
https://www.seventh.com.br/contato/trabalhe-conosco

**Como se candidatar**
Envie um email informando sua pretensão salarial para valdeci.pedroso@seventh.com.br com seu CV anexado e no assunto: Vaga Desenvolvedor (a) Python/ C# - Pleno

**Labels**
Python
C#
CLT
Pleno
Remoto

**Comment by thallysrc** [comment]
Essa label remoto ta correta? fui fazer uma entrevista com a seventh e eles falaram q não trabalham remoto, tem que se mudar pra florianopolis

**Comment by valdeci** [comment]
Thallys, essa foi uma vaga específica que estávamos trabalhando. E devido a isso era necessário o envio do email.

**Comment by valdeci** [comment]
Candidato contrato. Muito obrigado aqueles que se inscreveram.
