### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na [Platypus Brasil]

### ISSUE THREAD

**Issue by luannavaranda** [backend-br/vagas#426]
Desenvolvedor(a) Back-End PHP
    Estar confortável para trabalhar com demandas e datas pré-definidas com metas de produtividade;
    Pelo menos 1 ano de experiência na área, sobretudo em projetos ágeis;
    Ser proficiente com PHP, HTML, CSS, APIs RESTfull com MVC Architecture
    Experiência com Phalcon,  PostGreSQL e NoSQL
    Git (Bitbucket);

luanna.varanda@platypusbrasil.com.br

**Comment by grrlopes** [comment]
Essa oportunidade contempla, trabalho remoto ?

**Comment by luannavaranda** [comment]
Envia o seu currículo para o e-mail.
Marcamos uma conversa.
