### ISSUE TITLE
[Cidade] Back-end Developer @ Nome da Empresa

### ISSUE THREAD

**Issue by ContabilizeiVagas** [backend-br/vagas#4262]
## Nossa empresa
Com mais de 30 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

O **Squad Leads** integra o time de Produto & Tecnologia e é responsável pelo primeiro ponto de contato com nossos futuros clientes. A missão da área é garantir que a experiência dos usuários com a Contabilizei seja encantadora desde a primeira interação e, internamente, acelerar nosso crescimento no mercado nacional, oferecendo sempre as melhores soluções para nosso público alvo.

Acreditamos que a diversidade promove o crescimento sustentável. Na Contabilizei queremos que você seja a melhor versão de si, e as oportunidades são para todos. Valorizamos as diferenças, e estamos abertos a receber pessoas com quaisquer deficiências, gênero, etnia, orientação sexual e diferentes mindsets. Juntos, construímos a Contabilizei do nosso jeito.

**Ahhh e essa oportunidade permite trabalho remoto e você poderá trabalhar de onde você quiser, além disso, todas as nossas vagas são regime CLT.**

## Descrição da vaga
Um dia típico inclui:
- Analisar as exigências e especificações dos arquitetos do sistema, e contribuir com o desenho da solução (arquitetura, modelagem, design de código), atuando no desenvolvimento de sistemas que entreguem valor.
- Entregar com autonomia código testável com qualidade, estimando o esforço e o custo necessário para cumprir expectativas acordadas e comunicando necessidade de novos prazos .
- Implementar monitoramento das funcionalidades e rotinas de back-end, assegurando saúde das aplicações.
- Criar e manter aplicações back-end, integrando diversas interfaces a fim de otimizar o desempenho de sistemas atuais e entregando soluções com a melhor performance possível.
- Identificar problemas na base de código existente e aplicar melhorias.
- Pode apoiar no desenvolvimento técnico de profissionais com menos experiência, ajudando a desenvolver um time com nível adequado de qualificação.

## Local
- Presencial/Híbrido em Curitiba (após a pandemia ou 100% Remoto (qualquer região do país)

## Requisitos

**Obrigatórios:**

- Graduação completa ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Experiência com desenvolvimento back-end em Java, Node.js ou Kotlin;
- Experiência com banco de dados relacionais e não relacionais;
- Experiência com sistemas distribuídos;
- Experiência com Cloud (Google Cloud Plataform, AWS, Azure e entre outras);
- Experiência com Paradigmas de Programação (preferencialmente Estruturada, Orientação a Objeto e Funcional);
- Experiência com DevOps, Git, PR, Release, Deploy, CI e CD;
- Experiência com abordagens de qualidade;
- Metodologias ágeis (Scrum, Kanban, Lean).

## Benefícios

- **Nossos benefícios:**

Vale Refeição e/ou Alimentação;
Plano de Saúde;
Plano Odontológico;
GymPass;
Convênio Farmácia;
Seguro de vida;
Psicoterapia Online.

## Contratação

CLT

## Como se candidatar

Há dois canais para você realizar sua candidatura:
-Página de Carreiras: https://contabilizei.gupy.io/jobs/656154
-Candidatura simplificada pelo Linkedin: https://www.linkedin.com/jobs/view/2370102380/?capColoOverride=true

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo através das plataformas de cadastro.

#### Nível
- Pleno

**Comment by reginaldojunior** [comment]
Titulo da issue incorreto. @jessicaalorena
