### ISSUE TITLE
[Vila Olímpia] Desenvolvedor iOS [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#429]
Atividades: 

- Analise, programação e modelagem de dados orientada à objetos;
- Desenvolvimento de aplicações iOS;
- Programação em ambiente Web e PHP;
- Manutenção de sistemas, desenvolvimento de novos projetos e sustentação aos aplicativos já existentes.

Benefícios:
VR: 440,00/mês
AM e AO Care Plus Individual
Vale Transporte
Seguro de Vida

Sem descontos na folha do profissional.
Local de trabalho: Vila Olímpia
Contratação CLT Full

**Comment by Kirmayrtomaz** [comment]
O foco é em desenvimento Backend. 
Se o cargo for pra desenvolvedor IOS, nao faz sentido estar aqui.
