### ISSUE TITLE
[Valinhos SP/ Remoto] .NET CORE Developer @ Kroton

### ISSUE THREAD

**Issue by marianeors1** [backend-br/vagas#4315]
## Nossa empresa

A Kroton está passando por um forte processo de transformação cultural e digital e planeja ser o maior grupo de edtechs do Brasil. Para isso, está construindo um time de tecnologia de alto nível e está buscando pessoas que desenvolvam em .net core para fazer parte da equipe e impactar a vida de milhões!

## Descrição da vaga

Como integrante de um time de desenvolvimento, dentro de um time ágil, você terá desafios técnicos, participará ativamente dos ritos Scrum (Planning, Daily Meeting, Review e Retro), sendo responsável pelo planejamento e entrega de produtos que estão em evolução para novas arquiteturas.

## Local

 Remoto ou Escritório em Valinhos, SP

## Requisitos

Experiência nas tecnologias .NET Framework e .NET Core (C#), Oracle (PL/SQL nível desenvolvedor);
Experiência sólida como Desenvolvedor .Net;
Desenvolvimento com webservices (SOAP e REST);
Familiaridade com controle de versionamento TFS e ferramenta de desenvolvimento Visual Studio;
Conhecimento em modelos ágeis utilizando Scrum e Kanban;
Experiência com front-end SPA (Angular ou React js e/ou React Redux) e ASP.NET MVC.
## Benefícios

Participação nos lucros
Assistência Médica
Assistência Odontológica
Vale Refeição ou Vale Alimentação
Vale Transporte;
Seguro de Vida
Gympass
Desconto em Bolsa graduação/pós-graduação nas marcas Kroton
K-Vantagens: Clube de benefícios com descontos nos parceiros;
Be Youserlf - Aqui você pode se vestir para o trabalho do jeito que você se sentir melhor
Havaianas Friendly
Temos espaços de descompressão em todos escritórios corporativos para você ter aquele momento relax.

## Contratação

CLT

## Como se candidatar

Através do link: byintera.in/28k

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by bessajonathan** [comment]
Acho que a vaga está procurando uma equipe inteira de TI não? Vaga desproporcional

**Comment by marianeors1** [comment]
Boa noite Jonathan!
Os requisitos estavam errados! Eu atualizei a postagem com os requisitos certos! ☺️

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
