### ISSUE TITLE
[REMOTO] Back-End Developer na VoceAzul.com [PHP-LARAVEL-VUE]

### ISSUE THREAD

**Issue by tuliovargas** [backend-br/vagas#432]
## Descrição da vaga

Buscamos um desenvolvedor com solidos conhecimentos em PHP e grandes habilidades com os seguintes frameworks: 
LARAVEL 5+;
VUE2;

## Local
Remoto

**Desejáveis:**
- Experiência com Node

## Nossa empresa
Somos uma Fintech localizada em Uberlândia-MG e São Paulo-SP.

## Como se candidatar
Por favor envie um email para: **contato@voceazul.com.br**
**Em assunto:** Vaga LARAVEL - [Seu_Nome]

No conteúdo do e-mail responder as questões abaixo:

::.VueJS
- Quantos projetos e anos de experiência;
- Vue 2;
- Vue Router;
- Vuex e SPA(Single Page Application);
- Vue CLI;

::.Laravel
- Quanto tempo de experiência;
- Quais versões trabalhou;
- Detalhes sobre seus desenvolvimentos;

::.Valor Hora: _________

::.Quantas horas semanais disponíveis: ________

::.Portifólio ou link Git: 

::. WhatsApp:

## Labels

- Freela
- Pleno
- Sênior
- Remoto - Total

**Comment by Vagmacker** [comment]
Boa noite,

Mandei email
