### ISSUE TITLE
[Florianópolis/Remoto] Back-end Developer @Agriness

### ISSUE THREAD

**Issue by MonicaDirksen** [backend-br/vagas#4383]
> Vaga Remota durante a pandemia

## Nossa empresa

Aqui na Agriness temos o propósito de impulsionar a prosperidade no campo e fazemos isso através de soluções em tecnologia e na aplicação de uma metodologia de aceleração de produtividade pioneira no mundo, auxiliando o produtor a utilizar análises e conhecimentos para obter resultados de excelência em produtividade e, assim, aumentar a rentabilidade de seus negócios.

## Descrição da vaga

Estamos com uma nova oportunidade para Desenvolvedor(a) Backend Júnior no nosso Squad Entrecore. Atuando em um Squad você participará na implementação de soluções escaláveis que atendam aos critérios de qualidade da empresa e que entregam valor aos nossos clientes.

Sendo mais específico, o(a) Desenvolvedor(a) irá:

- Interagir com desenvolvedores e integrantes da sua Squad e de outros setores da empresa para definição e implementação das soluções planejadas;
- Implementar código seguindo os padrões de qualidade definidos pela área, através de uso de testes unitários e automatizados, processos de integração contínua e revisão de código, buscando disseminar boas práticas;
- Desenvolver soluções multicamadas em uma arquitetura de microservices, utilizando para isso tecnologias já adotadas pela empresa, neste caso PYTHON; e
- Prezar pela otimização de processos de forma a evitar atividades manuais e repetitivas.

## Local

Remoto ou Escritório, Florianópolis/SC

## Requisitos

**Obrigatórios:**

- Ensino superior em andamento nas áreas de tecnologia; e
- Conhecimento e/ou experiência com a linguagem Python.

**Diferenciais:**
- Conhecimentos em construções de APIs, usando padrões REST;
- Conhecimentos básicos de Docker e Cloud;
- Interesse em temas como: clean code, design patterns, message queuing, containers, continuous integrations e continuous delivery;
- Conhecimento no uso de testes unitários e automatizados; e
- Inglês intermediário.

## Benefícios
- Oportunidade de trabalhar em uma empresa que te desafia, motiva, incentiva e dá liberdade para questionar e contribuir com novas ideias;
- Muita oportunidade de desenvolvimento;
- Ginástica Laboral duas vezes por semana;
- Previdência Privada;
- Aulas de idiomas;
- Folga no dia do aniversário;
- Parcerias de descontos com convênios;
- Possibilidade de trabalho 100% pós pandemia; e
- Pacote de benefícios tradicionais: Auxílio home office, VR/VA, Plano de Saúde.

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para pertencer@agriness.com com seu CV anexado - enviar no assunto: Vaga Backend

#### Regime
- CLT

#### Nível
- Júnior

**Comment by steadylearner** [comment]
test
