### ISSUE TITLE
[Belo Horizonte] Senior Java Developer [Strider]

### ISSUE THREAD

**Issue by carlosgpn** [backend-br/vagas#44]
<div class="">
   <h2><strong>About us</strong></h2>
   <h2>Strider is an AgTech startup that uses cutting-edge technology to enable farms to produce higher yields, using fewer resources, and consequently increasing profit in a way that is sustainable.</h2>
   <p>We make producers see their operations from an angle they had never seen before. In just 3 ½ years of operation, we are the agriculture industry leaders in Brazil. We have over&nbsp;3 million&nbsp;acres being monitored in Brazil, Bolivia, Mexico, Australia, and the USA, growing 20% per month and generating real savings for our customers.</p>
   <p>Prepare to be part of a lean team (we are 60 people strong), who wants to revolutionize the way farms are managed, and help create the sustainable agriculture of the future.</p>
   <h2><strong>We are looking for people who</strong></h2>
   <ul>
      <li>Are passionate about development and are ready and willing to meddle with any development challenge that crosses their path.</li>
      <li>Have curiosity and have the willingness to learn… a lot, and fast!</li>
      <li>Experiment with new technologies while maintaining alignment with emerging and existing architectures.</li>
      <li>Develop effectively, quality source code that satisfies customer needs with an exceptional experience.</li>
      <li>Code, test and deliver iterative minimally viable product features towards target customer and business outcomes.</li>
      <li>Work within modern architectures and frameworks while experimenting with newer technologies and tools which better enable your teams.</li>
      <li>Solve problems together with experienced developers, product owners to truly satisfy customers.</li>
      <li>Do not mind eating pizza and drinking beer one Friday a month with the entire team :D</li>
   </ul>
   <h2><strong>Reasons to join</strong></h2>
   <ol>
      <li>Strider is backed by some of the finest VCs in Brazil: Monashees and Qualcomm, investors of 99Taxi, ContaAzul, and VivaReal. Stability in the long-run.</li>
      <li>Tech/product founders that value software quality and really understand technical debt. Zero tolerance for trash code.</li>
      <li>Strong (100% product based) revenue stream and a fast-growing business (20% month-over-month for the last 2 years). Strider is the leader in its market.</li>
      <li>Using really cool technology and managing a large user base spread in many countries.</li>
      <li>Zero-bullshit environment, no pointless meetings, straight communication, no clueless managers, office politics does not pay off.</li>
      <li>A team of high-skilled and committed engineers you can learn a lot from.</li>
      <li>Opportunity to influence the future direction of the products and systems used across the business and to move up in the organization.</li>
   </ol>
   <p>&nbsp;</p>
   <h1><span style="font-weight: 400;">Senior Java Developer&nbsp;</span></h1>
   <h2><strong>Responsibilities</strong></h2>
   <ul>
      <li style="font-weight: 400;">Develop expertise in the software that makes up the Strider platform.</li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Develop a complete understanding of customer context and use of our products.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Be able to develop skills in new technologies to meet product objectives.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Create architecture, algorithm and design solutions to meet roadmap requirements.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Lead a small team of developers and designers to fulfill the product missions, always applying the best practices of software engineering and continuous integration.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Provide planning, documentation, management, and coaching to keep the team aligned with the goals and culture of Strider.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Be in touch with emerging trends and technologies and apply them to activities and operations. </span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Communicate with other company teams to align missions and releases.</span></li>
   </ul>
   <h2><strong>Qualifications</strong></h2>
   <p><span style="font-weight: 400;">Minimum:</span>&nbsp;</p>
   <ul>
      <li style="font-weight: 400;">Proficiência em Inglês (clientes ativos nos US and Australia).</li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Extensive experience with software development.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Consolidated and hands-on experience with Java and related technologies (Eclipse, Spring MVC / REST, JPA, Hibernate, etc).</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Ability to communicate with staff and clients, leaving them confident that you understand the whole problem (English is required).</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Proficiency in TDD, SOA, REST, Design Patterns, MVC and Relational and NoSQL databases.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Proficiency with Front End development technologies (Javascript - ReactJS, Angular).</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Excellence in the ability to seek out and learn new technologies with a focus on problem-solving.</span></li>
   </ul>
   <p><span style="font-weight: 400;">Desirable:</span>&nbsp;</p>
   <ul>
      <li style="font-weight: 400;">Experience throughout the product development cycle, from design to testing and release.</li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Demonstrated experience in DevOps, with complex deliverables using more than one platform. </span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience with mobile application development.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Experience with the GIS stack as Anaconda, GDAL, OGR, GEOS.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Experience with Hardware Development.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Experience with Image Processing and&nbsp;Computer Vision.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;"> Experience with Information Retrieval.</span></li>
   </ul>
   <p><strong>&nbsp;Contract type: CLT</strong></p>
   <p>Access this link to apply: <a href="http://bit.ly/2lRmzIe" target="_blank">http://bit.ly/2lRmzIe</a></p>
</div>

**Comment by carlosgpn** [comment]
Labels: "Senior" "Fulltime" "Presencial" "CLT" "Java"

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
