### ISSUE TITLE
[REMOTO] FULL STACK @Mirante Tecnologia

### ISSUE THREAD

**Issue by Anarib2921** [backend-br/vagas#4432]
<Descrição da vaga
A Mirante busca novo integrante para sua equipe de desenvolvimento web.

Requisitos

Conhecimento avançados em HTML / CSS / HTML/ Javascript 
Conhecimento avançado em Java

Diferenciais:
horário flexível 
Contratação:

PJ

Como se candidatar
Por favor se candidatar através do e-mail ana.ribeiro@mirante.net.br

**Comment by NomiasSR** [comment]
é horário comercial ou pode ser pela parte da tarde?

**Comment by Anarib2921** [comment]
Comercial
