### ISSUE TITLE
[São Paulo] Back-end Developer @ Air Liquide Brasil | Digital Team

### ISSUE THREAD

**Issue by albdigitalteamdev** [backend-br/vagas#4437]
> Vaga Remota durante a pandemia
![](https://i.ibb.co/JFpd3f0/logo-AL.png)
## Air Liquide Brasil
A Air Liquide é uma empresa multi-nacional francesa líder mundial em gases, tecnologias e serviços para a Indústria e Saúde. Estamos com vagas para profissionais de TI com foco em desenvolvimento Back-end.
## 💼 Descrição da vaga
- Criará produtos (softwares web e mobile) internos para uso nacional e internacional
podendo impactar a vida de milhares de pessoas;
- Irá contribuir ativamente para a cultura do time com tendências de mercado e novas
metodologias;
- Participará na concepção e solução de problemas técnicos em projetos novos e o projetos
legados.
## 📌 Local
Remoto ou Escritório, SP, São Paulo, Brooklin
## 🎯 Requisitos
**Obrigatórios:**
- .NET Core e .NET Framework
- RESTful APIs
- SQL Server
- Entity Framework
- JavaScript
- Docker
- CI / CD
- Conhecimentos em testes automatizados
- Git
- Vivência em metodologias ágeis (Kanban, Scrum, etc.)
- Design Pattern

**Diferenciais:**
- AngularJS
- ReactJS
- React Native
- Azure DevOps
- Dapper
- Inglês

**Comportamental:**
- Autodidata
- Autogerenciável
- Esteja em atualização constante da tecnologia dominada e novas tecnologias
- Multiplicador
- Equilibrio para lidar com sistemas de alta criticidade

## ⭐️ Benefícios
- VR de R$ 30/dia
- Bônus anual mediante metas atingidas
## Contratação
PJ a combinar
## 🚀 Como se candidatar
Para saber mais sobre a vaga, [cliquei aqui](https://github.com/albdigitalteam/vagas/blob/master/backend.md).
Por favor envie também um email para bruno.schoola-sc@airliquide.com com seu CV anexado - enviar no assunto: Back-end Developer.
## ⏰ Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: paulo.monte-sc@airliquide.com
#### Alocação
- Alocado
- Remoto
#### Regime
- PJ
#### Nível
- Pleno
- Sênior
- Especialista

_**Na ALB as pessoas interessadas são bem vindas em todas as vagas, independentemente de gênero, orientação sexual, raça, etnia ou deficiência.**_

![](https://i.ibb.co/X4GV83K/Whats-App-Image-2020-09-29-at-10-01-09.jpg)
![](https://i.ibb.co/jyyTGxY/Whats-App-Image-2020-09-29-at-10-01-08.jpg)

**Comment by FilipeAugustoVO** [comment]
Vaga interessante.
Pergunta: Essa vaga é remota ou híbrida? Pois aqui ela aparece como remota,
mas no site é dito hibrida.
