### ISSUE TITLE
[Alphaville / Barueri] Desenvolvedor(a) PHP Backend/DevOps Sênior na Talentify

### ISSUE THREAD

**Issue by dreanmer** [backend-br/vagas#444]
## Detalhes da Vaga

Localização: **Barueri, SP**
Contratação: **CLT**
Remuneração **R$6.000,00 - R$8.000,00/mês**

### Benefícios:

- Plano de Saúde (Amil);
- VA R$200;
- VR R$26 / dia;
- VT, fretado, ou estacionamento;
- Seguro de Vida;
- Horário Flexível;

### Responsabilidades da vaga

- Entender e melhorar a arquitetura do sistema;
- Escalar sistemas;
- Realizar testes de carga, identificar gargalos e otimizar o desempenho de sistemas;
- Identificar, monitorar e corrigir bugs e exceptions;
- Desenvolver testes automatizados e garantir a qualidade do software;

Experiência em infraestrutura, testes, monitoramento e otimização;

### Experiência Requerida:

- PHP OOP (avançado);
- Testes unitários (intermediário);
- Noções básicas em DDD e MVC;
- MYSQL (avançado)
- GIT (intermediário);
- AWS (intermediário);
- OPS/CD/CI (avançado);

### Experiência Desejável:

- Php 7.1 (strict types);
- Phalcon (framework);
- Codeception (testes);
- Integrações de serviços externos (SOAP, REST, BATCH/FTP)
- Queues;

## Sobre Talentify

Acreditamos que a combinação Marketing + Tecnologia + Pessoas é a base do R&S do Futuro! E que todas as partes envolvidas em um processo seletivo podem ter uma experiência inteligente, ágil e descomplicada.

## Sobre a Equipe

Somos uma equipe enxuta de 6 desenvolvedores (backend) sênior, além de um designer e um frontend. Gostamos de sempre discutir a melhor implementação de uma task e contamos com a opinião de todos, para se dar bem aqui tem que saber defender bem sua idéia, mas também ouvir o colega e sempre tirar o melhor das conversas. Em unanimidade usamos linux + phpstorm e docker como environment, mas vc estará livre para usar o ambiente que lhe melhor lhe convir.

Inscrição rápida por aqui: https://goo.gl/atmNEd

Dúvidas? alexandre@talentifyhr.com

## Labels

- PHP
- Sênior
- DevOps
- CLT
- Presencial

**Comment by dreanmer** [comment]
update no link de inscrição, ainda estamos com a vaga aberta!

**Comment by andrecointrade** [comment]
tenho interesse mas somente CLT de 8k pra cima
