### ISSUE TITLE
[Cidade] Back-end Developer @ Nome da Empresa

### ISSUE THREAD

**Issue by geekrootbr** [backend-br/vagas#4450]
Somos uma holding com diversas startups de tecnologia, em fase de seed ou growth. Procuramos pessoas que curtem desafios, querem crescer junto com a empresa e buscam oportunidades futuras de participação.

Descrição da vaga
Você estará trabalhando no desenvolvimento de uma startup de gestão de seguros, para desenvolvimento da plataforma, para web e mobile. Procuramos pessoas com vontade de aprender, que desejem crescimento na carreira, que busquem uma visão de longo prazo na nossa empresa.

Local
REMOTO

Requisitos

**Obrigatórios:**

Forte experiência em NodeJS
Conhecimento de React;
Experiência com ferramentas de versionamento (GitHub);

**Desejáveis:**
conhecimento em Python
conhecimentos em MySQL
conhecimentos em MongoDB

Contratação
PJ a combinar

Como se candidatar
Por favor envie um email para rh@triadps.com com seu CV anexado - enviar no assunto: Vaga Nodejs

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Regime
PJ
Nível
Pleno
Sênior

**Comment by geekrootbr** [comment]
publicacao errada

**Comment by reginaldojunior** [comment]
A vaga está com o titulo incorreto, pode abrir outra pfv?
