### ISSUE TITLE
[SÃO PAULO VILA OLIMPIA] Front End JR

### ISSUE THREAD

**Issue by jureis** [backend-br/vagas#446]
FRONT JR
Esta pessoa sera um ‘braço do TI’ dentro do Marketing, a serviço de negócio - Somos o e-commerce da Renner.

- A rotina é programar banners e campanhas para o site na plataforma da Oracle (iremos ensinar a ferramenta)
- irá programar hotsites, landing pages especiais (desk e mobile) - são paginas simples, com efeitos básicos de carrossel, videos embedados, efeito de hover etc
- possíveis manutenções simples no site (cabeçalho, rodapé, alguma página especifica) é tudo front ou ferramenta oracle
- linguagens que precisa saber: HTML, CSS e JS

o importante é ser uma pessoa com muita vontade de aprender, interessado e comprometido - tem muitas chances de crescer conosco!

Segunda a sexta - 9 as 19h
CLT - VT + almoço em restaurante conveniado (come a vontade)
Plano de saúde só depois de 24 meses de registro
Local: Vila Olímpia - SP

interessados (realmente) enviar cv para:
j.reis@lojasrenner.com.br

**Comment by gomesals** [comment]
Oi @jureis, como a vaga é para front, talvez seja mais interessante postar aqui: https://github.com/frontendbr/vagas

**Comment by Kirmayrtomaz** [comment]
Isso é uma vaga de front. Nosso foco é backend
