### ISSUE TITLE
[Freela Remoto] Desenvolvimento de API (+ Vue)

### ISSUE THREAD

**Issue by hmaesta** [backend-br/vagas#448]
Busca-se desenvolvedor para criação de API e integração com [Vue.js](https://vuejs.org/).

Toda a interface do sistema já está feita em Vue – com rotas, elementos dinâmicos, etc, mas utilizando dados estáticos.   

É livre ao desenvolvedor escolher a linguagem e framework que quiser para criar a API. Será um sistema construído do zero então temos flexibilidade.

Apesar de ser uma vaga back-end, será necessário desenvolver todas as partes para a interface usar dados reais (como autenticação, upload de arquivos, etc). Por isso a necessidade de ter experiência com Vue.

## Obrigatório
- Javascript
- Experiência com Vue 2 _(ou React e Angular, leia abaixo)_
- Experiência com API REST ou GraphQL
- Inglês
- Git

## Desejável (mas nem tanto)
- Experiência com API do [PagSeguro](https://devs.pagseguro.uol.com.br/docs/)
- Experiência com API da AWS S3 (vamos usar [DigitalOcean Spaces](https://developers.digitalocean.com/documentation/spaces/), que usa a mesma API do S3)

### Sou desenvolvedor React/Angular, posso participar?
Sim. Caso queira, há possibilidade de migrar a interface para React (Angular não) – mas isso não é desejável pelo re-trabalho.
  
Porém, vale dar uma olhada na [documentação do Vue.js](https://vuejs.org/v2/guide/), ele é muito mais simples que outros frameworks, então provavelmente você dê conta.

## Candidatar
Para receber o briefing completo com todos os detalhes do que deverá ser desenvolvido e ver a interface:

| ✉️ |  Envie seu portfólio para hmaesta+vda@gmail.com |
|---|---------------|
|   | Assunto do e-mail: `Vaga desenvolvedor API`       |

Não precisa ser um portfólio online, basta enviar alguns links de coisas que você desenvolveu recentemente, contar algumas experiências, etc. 
CV é bem-vindo, mas de pouca importância. *Não mande somente CV, tem que enviar portfólio!*

💰 **Com o briefing em mãos você poderá passar um orçamento.**

## Labels
- Freela
- Remoto - Total

**Comment by ifragas** [comment]
Applied !
