### ISSUE TITLE
[Belo Horizonte] GIS Developer [Strider]

### ISSUE THREAD

**Issue by carlosgpn** [backend-br/vagas#45]
<div class="">
   <h2><span style="font-weight: 400;">About us</span></h2>
   <h2><span style="font-weight: 400;">Strider is an AgTech startup that uses cutting-edge technology to enable farms to produce higher yields, using fewer resources, and consequently increasing profit in a way that is sustainable.</span></h2>
   <p><span style="font-weight: 400;">We make producers see their operations from an angle they had never seen before. In just 3 ½ years of operation, we are the agriculture industry leaders in Brazil. We have over 3 million acres being monitored in Brazil, Bolivia, Mexico, Australia, and the USA, growing 20% per month and generating real savings for our customers.</span></p>
   <p><span style="font-weight: 400;">Prepare to be part of a lean team (we are 60 people strong), who wants to revolutionize the way farms are managed, and help create the sustainable agriculture of the future.</span></p>
   <h2><span style="font-weight: 400;">We are looking for people who</span></h2>
   <ul>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Are passionate about development and are ready and willing to meddle with any development challenge that crosses their path.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Have curiosity and have the willingness to learn… a lot, and fast!</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experiment with new technologies while maintaining alignment with emerging and existing architectures.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Develop effectively, quality source code that satisfies customer needs with an exceptional experience.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Code, test and deliver iterative minimally viable product features towards target customer and business outcomes.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Work within modern architectures and frameworks while experimenting with newer technologies and tools which better enable your teams.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Solve problems together with experienced developers, product owners to truly satisfy customers.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Do not mind eating pizza and drinking beer one Friday a month with the entire team :D</span></li>
   </ul>
   <h2><span style="font-weight: 400;">Reasons to join</span></h2>
   <ol>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Strider is backed by some of the finest VCs in Brazil: Monashees and Qualcomm, investors of 99Taxi, ContaAzul, and VivaReal. Stability in the long-run.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Tech/product founders that value software quality and really understand technical debt. Zero tolerance for trash code.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Strong (100% product based) revenue stream and a fast-growing business (20% month-over-month for the last 2 years). Strider is the leader in its market.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Using really cool technology and managing a large user base spread in many countries.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Zero-bullshit environment, no pointless meetings, straight communication, no clueless managers, office politics does not pay off.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">A team of high-skilled and committed engineers you can learn a lot from.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Opportunity to influence the future direction of the products and systems used across the business and to move up in the organization.</span></li>
   </ol>
   <p>&nbsp;</p>
   <h1><strong>GIS Developer</strong></h1>
   <h2><span style="font-weight: 400;">Responsibilities</span></h2>
   <ul>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Evaluate problems scientifically and&nbsp;create&nbsp;new approaches to complex solutions.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Implement client-side and server-side web applications, demonstrating great programming skills and a desire to stay technically up to date.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Develop expertise in the software that makes up the Strider platform.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Develop an understanding of the customer context and use of our products.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Be able to develop skills in new technologies to meet the objectives of the product.</span></li>
   </ul>
   <h2><span style="font-weight: 400;">Qualifications</span></h2>
   <p><span style="font-weight: 400;">Minimum: </span></p>
   <ul>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience with Python or C / C ++.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Proficiency with HTML5, CSS3 and JavaScript.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Proficiency in English (active clients in the US and Australia).</span></li>
   </ul>
   <p><span style="font-weight: 400;">Desirable:</span></p>
   <ul>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Superior course in areas related to Computer Science.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience with the GIS stack as Anaconda, GDAL, OGR, GEOS.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience in the implementation of computer vision and image processing techniques with the OpenCV framework.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Knowledge of Front End development technologies such as AngularJS or ReactJS.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience with relational database (with support for GIS, like MySQL Spatial, PostGIS) and NoSQL (MongoDB, Cassandra).</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Experience with scientific research.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Development of highly complex technical and scientific software.</span></li>
      <li style="font-weight: 400;"><span style="font-weight: 400;">Work experience with high impact products and teams.</span></li>
   </ul>
   <p><strong>Contract type: CLT</strong></p>
   <p>Access this link to apply: <a href="http://bit.ly/2DZX9Q3" target="_blank">http://bit.ly/2DZX9Q3</a></p>
</div>

**Comment by carlosgpn** [comment]
Labels: "Fulltime" "Presencial" "CLT" "Python"

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
