### ISSUE TITLE
[Lauro de Freitas - BA] Full-stack Developer Jr. na Sotero Tech

### ISSUE THREAD

**Issue by fxcosta** [backend-br/vagas#450]
# Descrição da Vaga
A Sotero Tech está em busca de um dev ou deva junior para contribuir na criação e manutenção dos nossos diversos sistemas e produtos.

Atuar em correções, melhorias nos projetos já existentes e novos projetos, com atenção especial na qualidade do código. Buscamos um profissional retado e que esteja disposto aprender e compartilhar conhecimento e experiência conosco, participando desde o processo de arquitetura, análise, evolução até a produção das nossas soluções.

Se você adora desafios, tem fome por aprendizado e gosta de ambientes descontraídos com foco em evolução constante, venha trabalhar conosco!

# Local de trabalho:
-Presencial em Lauro de Freitas - Bahia

# Benefícios
-Vale Alimentação
-Vale Transporte
-Salário à combinar

# Requisitos 
## Requisitos obrigatórios:
-Ensino superior cursando ou completo em sistema da informação e áreas afins;
-Conhecimento e experiência com PHP (Orientado a objetos, MVC, Design Patterns, SOLID);
-Conhecimentos em HTML5 e CSS3;
-Conhecimento em versionamento de projetos usando Git;

## Diferenciais:
-Experiência com os frameworks PHP (Zend Framework, Laravel e/ou Symfony)
-Conhecimento e experiência com JavaScript (ES6+ e ecossistema);
-Testes unitários

# Como se candidatar
Enviar CV, pretensão salarial e portfólio/Github (se tiver) para selecao@soterotech.com.br

# Labels
- PHP
- Presencial
- CLT
- Junior

**Comment by guilhermeoa07** [comment]
Vaga ainda disponível? Entrevista pode ser remota?

**Comment by fxcosta** [comment]
@guilhermeoa07 desculpe a falta de manutenção da issue. Não, a vaga não está mais aberta, por hora. Irei fechar a issue.

**Comment by guilhermeoa07** [comment]
Ok, obrigado
