### ISSUE TITLE
[Remoto] Back-end Developer ClubeFII

### ISSUE THREAD

**Issue by worais** [backend-br/vagas#4512]
Estamos com vaga aberta no Clube FII para integrar a equipe de TI e trabalhar muito próximo ao CEO. Gostaríamos de alguém com algum grau de familiaridade com o mercado de Fundos Imobiliários ou conhecimento básico do mercado financeiro, utilizamos a stack .NET, Azure, SQL Server, Javascript, Jquery, VB.Net, Aspx. Sua função será de executar tarefas no backend para elaboração de ferramentas e manutenção do site do Clube FII.

## Local
100% Remoto - Monte seu horário com muita flexibilidade

## Projeto:
Gostaríamos de alguém com familiaridade com Fundos Imobiliários e conhecimento do funcionamento básico do mercado financeiro, utilizamos a stack .NET, Azure, SQL Server...

## Como se candidatar:
Por favor envie um email para contato@clubefii.com.br com pretensão salarial e CV anexado - enviar no assunto: Vaga Backend Clube FII

## Labels
PJ
Pleno
Remoto
Sênior
Full Time

**Comment by FilipeAugustoVO** [comment]
Essa vaga ainda está disponivel?

**Comment by worais** [comment]
Sim, ainda está aberta :)
