### ISSUE TITLE
[São Paulo] Programador .Net Fullstack Sênior na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [backend-br/vagas#454]
Programador .Net Fullstack Sênior

Requisitos:
• DDD; TDD
• Angular 1 e X
• .Net Core (pelo menos conhecimento)
• Entity Framework
• Injeção de Dependência
• NodeJS
• Restful
• WebApi
• Bootstrap
• GIT
• VSTS

Desejável:
• Azure
• Swagger
• Docker
• Pug

Local: São Paulo - Barra Funda
Projeto de tempo indeterminado
Envio de currículo: daniele.silva@ventron.com.br

**Comment by MicaelPereira** [comment]
Essa vaga

**Comment by MicaelPereira** [comment]
Essa vaga pode ser remoto?

**Comment by Dani-Ventron** [comment]
Olá @MicaelPereira , infelizmente não. Somente presencial.
