### ISSUE TITLE
[Remoto - São Paulo] Scrum Master @ CBYK

### ISSUE THREAD

**Issue by ThaynaraTeodoro** [backend-br/vagas#4586]
**## Nossa empresa**
A CBYK foi criada para ser uma consultoria diferenciada, realmente entregando aos clientes uma tecnologia consultiva que agrega valor ao negócio. Nosso ideal é justamente o desafio que impede nosso cliente de atingir sua meta tecnológica com soluções relevantes, se tornar exemplo para o cenário atual de inovações, soluções e performance.

**##Local**
Remoto, Vila Congonhas – São Paulo

**## Requisitos**
- Domínio em metodologia Agile;
- Experiência com Azure ou Jira;
- Estruturar, acompanhar e gerenciar as cerimônias da metodologia;
- Domínio sobre Kanban;
- Experiência com processo e gestão de times;
- Transversalidade prática e funcional;
- Ter autoridade e autonomia sobre o processo;
- Multiplicar e disseminar a metodologia agile;
- Guiar o time em auto-organização;
- Remover impedimentos na squad, sabendo priorizar os recursos;
- Facilitar as entregas de atividades;
- Auxiliar o time com comunicações internas e externas;
- Acompanhar, organizar e estruturar métricas ágeis, de performance e organização do time;

**## Benefícios**
Férias Remuneradas + Gympass + Parceria com universidades.

**##Desejável:**
- Vivência em desenvolvimento de software;
- Certificação Scrum master;

**## Contratação**
PJ a combinar

**## Como se candidatar**
Por favor envie um email para vagas@cbyk.com.br com seu CV anexado - enviar no assunto: Vaga Scrum Master.

## Labels
🏢Remoto
👱🏽‍♂️Pleno
🧔🏽Sênior
⚖️ PJ

**Comment by diogobuique** [comment]
Olá, acredito que o e-mail esteja errado.

**Comment by ThaynaraTeodoro** [comment]
Ajustado, Muito obrigada 😉

Atenciosamente,
Thaynara Teodoro

[cid:8620a53d-2473-4358-b36e-2f9ff78997d7]

________________________________
De: Diogo Buíque ***@***.***>
Enviado: quinta-feira, 11 de março de 2021 14:52
Para: backend-br/vagas ***@***.***>
Cc: ThaynaraTeodoro ***@***.***>; Author ***@***.***>
Assunto: Re: [backend-br/vagas] [Remoto - São Paulo] Scrum Master @ CBYK (#4586)


Olá, acredito que o e-mail esteja errado.
