### ISSUE TITLE
[Porto Alegre] Analista Programador Xharbour | Clipper | ADVPL na Sygecom

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#459]
### Sobre a empresa: Sygecom Informática

É uma software house gaúcha, líder de mercado em fornecimento de sistema de gestão para empresas de reciclagem no Brasil inteiro. Há mais de 10 anos no mercado, agregando valor e automatizando o gerenciamento dessas empresas, criando soluções inovadoras e produtos que atendam as necessidades de nossos clientes, excedendo as expectativas.

### Descrição:

**Ocupações do cargo**

Principais funções são a análise e desenvolvimento de customizações, melhorias e correções para funcionalidades de nosso produto (software ERP desenvolvido internamente), com bases nas demandas recebidas; Criar e analisar novas customizações; Criar modelagem de banco de dados; Realizar testes nas ferramentas desenvolvidas e disponibilizar manual explicativo sobre como funciona. 

### Benefícios

Estamos sempre em busca de novas parcerias e benefícios para agregar valor a vida profissional e pessoal de nossos colaboradores e familiares.

Plano de saúde - Unimed Max (funcionários e dependentes até 18 anos);
Plano Odontológico - Uniodonto (funcionários e dependentes até 18 anos);
Vale-transporte;
Alimentação no local (café da manhã e almoço);
Convênio com Farmácia;
Auxílio Creche;
Plano de Carreiras;

### Aptidões e qualidades

De aptidões e qualidades buscamos um profissional dedicado, responsável, com força de vontade, raciocínio lógico, comprometido, com boa concentração, disciplinado, paciente, persistente, que trabalhe bem em equipe, que goste de aprender constantemente e que goste de trabalhar muito e goste muito de trabalhar.

### Informações da empresa

A Sygecom Informática é uma software house gaúcha, líder de mercado, em fornecimento de softwares para empresas do setor da reciclagem, sejam atuantes do mercado de aparas de papel e plástico, sucata de ferro e não ferroso, espalhadas pelo Brasil inteiro.

Nossa missão é continuar criando soluções inovadoras e produtos que atendam as necessidades de nossos clientes, excedendo as expectativas, agregando valor e automatizando os processos gerenciais.

Como visão, temos o intuito de sermos reconhecida como referência em software e automação no segmento da reciclagem.

Temos como principal meta o CRESCIMENTO, de nossa empresa, dobrando o número de clientes, o quadro de funcionários, tamanho e estrutura de nossa sede.

E para isso estamos em busca de novos colaboradores que estejam disposto a vestir a camiseta e assim contribuir para que nossa meta principal seja alcançada com sucesso.

Venha fazer parte do nosso TEAM!

### Informações complementares

Trabalhar de segunda a sexta-feira, das 08h30 as 18h00, com intervalo de 1h00.

### Labels

Pleno 
CLT
Alocado

# Link de cadastro da vaga: http://bit.ly/sygecom_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
