### ISSUE TITLE
[São Paulo] Analista de Requisitos Jr na Concil

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#460]
### Sobre a empresa: Concil

Somos uma fintech em constante crescimento e líder em conciliação de cartões do mercado!
 
Nosso time de Dev é o responsável por criar e garantir a melhor experiência em recebíveis e gestão financeira para milhares de empresas em todo o Brasil.
 
Aqui valorizamos a cultura de desenvolvimento ágil, autonomia com responsabilidade, você irá nos ajudar a criar/testar novas tecnologias, decidir sobre o produto, aprender e compartilhar seus conhecimentos.

### Descrição:

**Ocupações do cargo**

Você irá atuar no levantamento de requisitos e especificações funcionais de nossas aplicações, trabalhando em conjunto com nosso time de Produtos e desenvolvimento.

Sua missão inclui traduzir as necessidades de nossos clientes, elaborar a documentação do projeto e garantir que toda funcionalidade seja especificada seguindo as mais boas práticas de: Arquitetura, Experiência do Usuário, performance e usabilidade.

### Benefícios

Plano de saúde
Vale Refeição

### Aptidões e qualidades

Buscando sempre conhecimento
Pró-atividade
Trabalho em equipe

### Requisitos para esta vaga:

Ter atuado na gestão de projetos de tecnologia (sistemas, aplicações web, web services, aplicativos, integrações)
Experiência no relacionamento com o cliente
Facilidade em traduzir regras de negócio em requisitos técnicos para o time de desenvolvedores

### Diferencial:

Conhecimentos e técnicas em usabilidade e pesquisas com usuários.
Experiência com Scrum e metodologias de desenvolvimento ágil

### Labels:

Junior
Alocado
CLT

**Comment by Kirmayrtomaz** [comment]
Analista de requisitos nao é uma vaga backend
