### ISSUE TITLE
[São Paulo] Desenvolvedor Java na Concil

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#461]
### Sobre a empresa: Concil

Somos uma fintech em constante crescimento e líder em conciliação de cartões do mercado!
 
Nosso time de Dev é o responsável por criar e garantir a melhor experiência em recebíveis e gestão financeira para milhares de empresas em todo o Brasil.
 
Aqui valorizamos a cultura de desenvolvimento ágil, autonomia com responsabilidade, você irá nos ajudar a criar/testar novas tecnologias, decidir sobre o produto, aprender e compartilhar seus conhecimentos.

### Descrição: Ocupações do cargo

Você irá atuar na análise, desenvolvimento e implantação de nossas aplicações Java com banco de dados Oracle SQL, trabalhando em conjunto com nosso time de UX e backend.

Sua missão inclui garantir que todas as aplicações sejam projetadas utilizando as mais boas práticas de desenvolvimento, performance e usabilidade.

### Aptidões e qualidades

Se você se preocupa com código limpo, bem documentado e testável, baixa latência e alta disponibilidade para oferecer a melhor experiência para o usuário final, então, aqui você fará uma grande diferença!

**Além disso, o que consideramos requisitos para esta vaga:**

Experiência sólida em desenvolvimento JAVA
Spring (vivência prática)
Banco de dados Oracle SQL
Javascript e uso de bibliotecas MVC como Angular.js e ReactJS
Testes unitários
Boas práticas de programação

**Diferencial:**

Experiência em JSF, EJB e JPA
Hibernate
Padrões REST
Github e regras de versionamento de código
Experiência com Scrum e metodologias de desenvolvimento ágil
Gerenciadores de tarefas (Grunt, Gulp)
Conhecimento em outras linguagens de programação dinâmica (Python, Ruby, etc) e bancos não relacionais

### Labels

- CLT
- Alocado
- Pleno

### Link de cadastro da vaga: http://bit.ly/2OtyUiL

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
