### ISSUE TITLE
[São Paulo] Desenvolvedor Java Pleno na [RADAR PROFISSIONAL]

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#463]
Descrição da vaga
Estamos em busca de um novo integrante para equipe de desenvolvimento web.

Requisitos:

•	Superior completo ;
•	Experiência em arquitetura de dados, modelagem de dados e aplicações para integração em plataformas distribuídas e relacionais;
•	Experiência com programação Java, SQL e Stack Spring (Spring Framework 4.0+, SpringBoot, Spring Data, Hibernate);
•	Desejável experiência com git, ferramentas de build contínuo, desenvolvimento REST.
•	Será considerado como diferencial, profissionais com experiência com bancos NoSQL, docker, mesos e marathon.

Local
São Paulo - SP

Benefícios

VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.

Como se candidatar
Por favor se candidatar através do e-mail vagas@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
