### ISSUE TITLE
[São Paulo] Desenvolvedor .Net Júnior  [RADAR PROFISSIONAL]

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#465]
Descrição da vaga
Estamos em busca de um novo integrante para equipe de desenvolvimento web.

Requisitos:
•	Superior completo ou cursando o ultimo ano ;
•	Imprescindível experiência na função e com C#, .NET, ASP.NET MVC, ASP.NET WebAPI, Orientação Objeto (POO), LINQ e SQL Server;
•	Será considerado como diferencial, profissionais com experiência em EntityFramework, Code First/Migrations, Padrões de Projetos, SCRUM, Controle de Versão Visual Studio Online, TDD, ORACLE e Automatização de Testes.

Local:
Vila Leopoldina - SP

Benefícios:

Contratação PJ + 7 dias de férias remuneradas por semestre. 

Como se candidatar:
Por favor se candidatar através do e-mail vagas@radarprofissional.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
