### ISSUE TITLE
[Remoto] Desenv. API (+ Vue) na VoceAzul

### ISSUE THREAD

**Issue by tuliovargas** [backend-br/vagas#466]
## Descrição da vaga
Vaga Freelancer para desenvolvedor Backend PHP(Laravel) com profundos conhecimentos em Javascript. Utilizamos VueJs no FrontEnd, então as telas em HTML/CSS serão disponibilizadas, o trabalho do desenvolvedor será criar as API no Backend e no FrontEnd criar componetes com VueJS.

## Local
Remoto

## Aplicar para vaga
Enviar um email para: **[contato@voceazul.com.br]**

**Assunto:** `Vaga Laravel_Vue [SEU_NOME]`

**Informando os seguintes pontos abaixo:**

**::.VueJS**
- Quantos projetos e anos de experiência;
- Vue 2;
- Vue Router;
- Vuex e SPA(Single Page Application);
- Vue CLI;
- Redux;

**::.Laravel**
- Quanto tempo de experiência;
- Quais versões trabalhou;
- Detalhes sobre seus desenvolvimentos;

**::.Valor Hora**: _________

**::.Quantas horas semanais disponíveis:** ________

**::.Portifólio ou link Git:** 

**::. WhatsApp:**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
