### ISSUE TITLE
[100% Remoto] PHP + Python Developer na Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [backend-br/vagas#4674]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga
 
Atuar alocado 100% remoto em squad com foco no desenvolvimento e aprimoramento de produtos em um dos maiores e-commerce de móveis e artigos de decoração do país.

São 15 vagas e estão separadas por nível de senioridade:

-  3 vagas: Junior PHP Developer 
-  3 vagas: Pleno PHP e Python Developer 
-  6 vagas: Sênior PHP e Python Developer 
-  3 vagas: PHP e Python Specialist 

## Local

100% remoto até depois da pandemia.

## Requisitos para Seniores e Especialistas

Experiência de mercado com:
- Desenvolvimento Cloud – empresa 100% AWS, mas pode ser experiência com outras como GCP ou Azure
- Experiência com GIT, API REST, microsserviços, serverless, lambda, container (usam Fargate AWS) e estrutura de dados em memória (usam Redis)
- PHP 
- Python para processamentos em escala, alto volume de alterações na página web.
- Banco de dados – usam Aurora (Amazon RDS), experiência com SQLServer ou MySQL
- Golang - diferencial 

## Requisitos para Juniors

-  Ter trabalhado com desenvolvimento em PHP “puro”, sem frameworks

## Requisitos para Plenos

-  Ter trabalhado com PHP e Python;
-  Ter conhecimento com desenvolvimento em cloud

## Benefícios

- Assistência Médica (s/ dependente) e Odonto Executivo (s/ dependente)
- Seguro de Vida
- Vale Refeição (R$ 660,00)
- Vale Alimentação (R$ 150,00)

## Contratação

Contratado como CLT Robert Half e depois de alguns meses, há uma grande oportunidade de ser internalizado pelo cliente.

Salário com base de Curitiba/Paraná.

## Como se candidatar

Interessados deverão enviar o currículo para livia.mello@roberthalf.com.br ou se candidatar através do nosso site: https://www.roberthalf.com.br/vagas/tecnologia

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Junior
- Pleno
- Sênior
- Especialista

**Comment by fabricioevan** [comment]
Olá, tem alguma vaga de estágio disponível?

**Comment by LiviaMaron** [comment]
Olá!
Infelizmente não temos, mas fique a vontade de encaminhar seu currículo.
