### ISSUE TITLE
Desenvolvedor Java Senior e Pleno🎯Oportunidade São Paulo | 💯 homeoffice | ✍🏼CLT | PLR 🪁 | Previdência Privada | 🏃🏾‍♀️Gympass

### ISSUE THREAD

**Issue by gispsico** [backend-br/vagas#4678]
🎯Oportunidade São Paulo | 💯 homeoffice | ✍🏼CLT | PLR 🪁 | Previdência Privada | 🏃🏾‍♀️Gympass
🎯Desenvolvedor Java Senior e Pleno

📍Linguagem Java 8 e 11
📍Spring boot
📍Docker
📍Kubernet
📍Google plataform Cloud
📍CI/ CD

👌🏻Gostou da vaga certo? Que bom, agora só enviar seu currículo para gislainevieira.headhunter@gmail.com

**Comment by fabricioevan** [comment]
Olá, tem alguma vaga de estágio disponível?

**Comment by gispsico** [comment]
Ola Fabricio,

Ainda nao.

Obrigada,


*Gislaine Vieira*

*Talent Acquisition/Headhunter de Profissionais de Tecnologia e Inovação *

*Psicóloga CRP 06/130234 apaixonada pela Psicanálise *

*Personal & Professional Coach*



Em sex., 19 de mar. de 2021 às 13:06, fabricioevan ***@***.***>
escreveu:
