### ISSUE TITLE
Desenvolvedor Front End Sênior 🎯Oportunidade São Paulo | 💯 homeoffice | ✍🏼CLT | PLR 🪁 | Vale Refeição | Vale Alimentação | Previdência Privada | Seguro de Vida 🏃🏾‍♀️Gympass| React | Angular | View

### ISSUE THREAD

**Issue by gispsico** [backend-br/vagas#4679]
🎯Oportunidade São Paulo | 💯 homeoffice | ✍🏼CLT | PLR 🪁 | Vale Refeição | Vale Alimentação | Previdência Privada | Seguro de Vida 🏃🏾‍♀️Gympass

🚀Venha somar conosco e faça parte da empresa que investe na cultura de inovação e evolução contínua da melhor experiência do cliente.

🎯Desenvolvedor Front End Sênior

📌No dia a dia

📍Trabalhar em parceria com negocio, entendendo as necessidades do cliente;
📍Atuar como um membro da squad, participando de todas as cerimônias, com ownership e senso de pertencimento;
📍Contribuir com ideia e propor ao time, a melhor solução;
📍Garantir a qualidade e as melhores práticas de desenvolvimento;
📍Desenvolver aplicações seguras, resilientes e escaláveis;
Alinhar com arquitetura os melhores padrões.

📌Você precisa conhecer!

📍React
📍Angular
📍View
📍Google plataform Cloud
📍CI/ CD

👌🏻Gostou da vaga certo? Que bom, agora só enviar seu currículo para gislainevieira.headhunter@gmail.com

**Comment by fabricioevan** [comment]
Olá, tem alguma vaga de estágio disponível?
