### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Full-Stack .Net na Mereo

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#468]
### Sobre a empresa: Mereo

Somos uma HRTech bem jovem. Estamos localizados numa das áreas mais bacanas de BH, próximo da Savassi, com vários atrativos ao redor. Desenvolvemos uma plataforma para avaliação de gestores de empresas com base em suas entregas e em suas competências. Nossos clientes são empresas médio e grande porte (com certeza você conhece vários deles). Trabalhamos duro para construírmos a melhor plataforma HCM do mercado.

### Descrição: Ocupações do cargo

O profissional será responsável por programar, codificar e testar os projetos criados. Requisitos técnicos essenciais para a vaga são:

.Net  (MVC/WebApi);
C#;
Bootstrap;
Angular;
Javascript;
SQL-Server;
Git.

Conhecimento de Aspnet Boilerplate e outros frameworks Javascript não são requisitos obrigatórios, mas serão considerados diferenciais.

### Benefícios:

A contratação será com regime CLT, com os seguintes benefícios:

Vale-transporte;
Vale-refeição;
Plano de saúde unimed co-participativo;
Auxílio-educação (até R$ 350);
Plano de carreira
Remuneração variável anual.

### Aptidões e qualidades

É legal que o profissional tenha as seguintes aptidões e qualidades:

Paixão por tecnologia;
Gostar de trabalhar e apoiar em equipe;
Curioso sobre diversas áreas de conhecimento (inclusive idiomas);
Alta energia interna (e positiva, claro ;).

### Labels: 

- Pleno
- CLT
- Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
