### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack Sênior

### ISSUE THREAD

**Issue by marcosrs75** [backend-br/vagas#469]
Desenvolvedor full stack para LIDERAR um projeto de plataforma multilateral.

Familiaridade com arquitetura, experiência em construção e manutenção de API (rest/restful).

Estamos no MVP e buscamos um líder para avançar para as próximas fases.

Somos uma startup que está nascendo dentro de uma empresa madura, com 25 anos de experiência em atendimento ao varejo. Somos jovens, dinâmicos, motivados e estamos construindo um projeto inovador.

Altíssima possibilidade de crescimento e aprendizado. 

**Requisitos**
- Experiência com Ruby on Rails
- Sólida experiência de Programação Orientada a Objetos
- Infraestrutura AWS e noções de automação de provisionamento (Chef, Cloudformation)
- Experiência com ElasticSearch, Memcache ou Redis
- TDD e BDD
- Git
- Boa noção de frontend: HTML, CSS com Flexbox, JavaScript (ES6), React e Redux.

**Desejável**
- Conhecimento básico de Programação Funcional 
- Metodologias ágeis, e Feature Branch Workflow (com Github ou BitBucket)
- Experiência com banco de dados relacionais em grandes projetos (preferência PostgreSQL).
- DDD

https://goo.gl/forms/yoCSYmelahZLSXlg1

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
