### ISSUE TITLE
[Brasília, DF] Java Developer @ Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [backend-br/vagas#4692]
**Descrição da vaga**
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Java

**Local**
Home Office, pós pandemia presencial em Brasília, DF

**Requisitos obrigatórios:**
•	Java 8
•	Banco de dados (MS SQL Server)
•	Versionamento de código Git e SVN
•	Hibernete
•	Maven
•	CDI 
•	JSF
•	Javascript
•	SOAP
•	Rest
**Desejáveis:**
•	Criptografia 
•	Certificação digital

**Contratação**
PJ

**Nossa empresa**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.

•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Como se candidatar**

Envie seu currículo https://cutt.ly/GjcZYfq
Envie seu currículo: barbara.silva@pasqualisolution.com.br
Labels
•	Alocado
•	PJ
•	Sênior

**Comment by fabricioevan** [comment]
Olá, teria alguma vaga de estágio?
