### ISSUE TITLE
[São Paulo/ Remoto] Back-end PHP Developer Pleno @Maitha Tech

### ISSUE THREAD

**Issue by fft-maitha** [backend-br/vagas#4694]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa digital, com experiência em tecnologia e inspirada pela inovação. Atuamos na aceleração, transformação e ideação de novas soluções e times de alta performance.
Atuamos tanto na construção de times de tecnologia, quanto em frentes de negócio, na co-criação de produtos, levantamento de requisitos, resolução de problemas, entre outros.

## Descrição da vaga

Esse profissional irá atuar principalmente com PHP, Zend, Orientação a Objetos, Gerenciamento de pacotes (composer), Linux, Docker, Git e MySQL.

Os desafios são abrangentes, desde customizações dentro da plataforma,criação de ferramentas de marketing, entre outros. Busco pessoas flexíveis e que tragam soluções criativas. 

A empresa tem um fit cultural que proporciona uma atuação com autonomia, comprometimento, colaboração e flexibilidade e tem como valores a empatia, agilidade digital, e a evolução em conjunto.

## Local

Santana/ SP e / ou Remoto

## Requisitos

**Obrigatórios:**
- PHP
-  Zend
-  Orientação a Objetos
- Gerenciamento de pacotes (composer)
-  Linux
- Docker
- Git 
- MySQL

## Benefícios

- Benéficos para contratação CLT
- Plano de Saúde GNDI 300
- Vale transporte
- Cesta de Natal
-  Vale refeição (R$ 450,00)
- Vale Alimentação (R$150,00)
- Bonificação de um salário a cada 6 meses, se atingir 100% das metas
- Cursos Alura

## Contratação

PJ ou CLT + benefícios 

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/felipe-franzin-trajano/ ou envie um e-mail para felipe.trajano@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Back end  PHP 

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by fabricioevan** [comment]
Olá, teria alguma vaga de estágio?
