### ISSUE TITLE
[Vitória] Back-end Developer @Code n' App

### ISSUE THREAD

**Issue by LiliamGaviorno** [backend-br/vagas#4695]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa que busca inovar através de processos e ferramentas para entregar soluções em tecnologias que atendam as expectativas do mercado.

## Descrição da vaga

Procuramos profissionais com experiência em construção de interfaces de software web e  atuação em grandes projetos.

## Local

Remoto ou Escritório em Vitória - ES

## Requisitos

.Net
Delphi
SQL Server 

## Benefícios

Faixa salarial de R$3.800 a R$5.200, plano de saúde, plano odontológico, vale transporte, ticket refeição, Gympass.

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Se você é esse profissional, venha fazer parte da nossa equipe. Envie seu currículo, com o nome da vaga no título, para queroser@codenapp.com

#### Nível
- Pleno
- Sênior
- Especialista

![Vaga_Desenvolvedor_de_Sistemas_dotNet](https://user-images.githubusercontent.com/80852236/111790829-61642f80-88a1-11eb-880a-7b418aa12895.png)

**Comment by fabricioevan** [comment]
Olá, teria alguma vaga de estágio?
