### ISSUE TITLE
[Remoto] Back-end Developer @Trinca

### ISSUE THREAD

**Issue by Gabrielarochay** [backend-br/vagas#4696]
**Buscamos Back-end Developer (Pleno)**! Alguém versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

**// HABILIDADES QUE VOCÊ PRECISA TER**
• Experiência com desenvolvimento em .Net Core e SQL Server;
• Diferencial: conhecimento no Microsoft Azure

// Estamos trabalhando de forma distribuída/remoto  :+1:  
// Contratação: PJ

Curtiu? Encaminha teu currículo para **jobs@trin.ca** 

**Aqui tem informações sobre a nossa cultura:** https://www.trin.ca/cultura
**Sobre a vaga:** https://www.trin.ca/vagas?job=Back%20End%20Developer

![backend](https://user-images.githubusercontent.com/66493175/111794401-f1f03f00-88a4-11eb-8505-81a46b240626.PNG)

**Comment by fabricioevan** [comment]
Olá, teria alguma vaga de estágio?
