### ISSUE TITLE
[Uberlândia - MG] Profissional Desenvolvedor C# - Explend Sistemas

### ISSUE THREAD

**Issue by Dervanil** [backend-br/vagas#47]
Profissional Desenvolvedor C# - Pleno

![Profissional Desenvolvedor C#](https://user-images.githubusercontent.com/2516266/34835303-9278361c-f6db-11e7-9545-842f4655694a.jpg)

Contratação CLT

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?

**Comment by Dervanil** [comment]
Ainda não, mas pode deixar o Issue fechado, obrigado.
