### ISSUE TITLE
[Belo Horizonte] Back-End Developer na [Axxiom Soluções Tecnológicas]

### ISSUE THREAD

**Issue by rhaxxiom** [backend-br/vagas#472]
## Descrição da vaga
Desenvolvimento de Software em Java para sistema especializado de Engenharia Elétrica;
Leitura de especificação;
Modelagem e monitoramento da aplicação;
Definição de Arquitetura e desenhos de sistemas;
Desenvolvimento Front-end, Java Script, Bootstrap e back-end;
Java Spring MVC e Spring Data.

## Local
Belo Horizonte/MG

## Benefícios
- Vale Transporte
- Vale Alimentação/Refeição (R$ 29,00/dia)
- Plano de Saúde Médico/Odontológico Amil, 100% subsidiado pela Axxiom para o colaborador e seus dependentes diretos
- Seguro de Vida
- Horário semi-flexível (40 horas)
- Descontos em Instituições de Ensino

## Requisitos
Java;
Java script;
Java Spting MVG;
Bootstrap;
Hibernate;
Apache Camel.

## Contratação
CLT

## Nossa empresa
A Axxiom é uma empresa de Tecnologia e Inovação que se destaca não só por seu grau de maturidade, contando com profissionais de alta qualificação técnica, mas também pelo valor gerado aos clientes. 
Oferecemos soluções de vanguarda, associando Tecnologia da Informação e engenharia. Atuamos com integração, desenvolvimento e sustentação de sistemas técnicos, comerciais e de gestão, além de consultoria em otimização de processos e soluções em TI. 
Nossa equipe desenvolve projetos estimulantes e desafiadores, gerando um ambiente de aprendizagem e crescimento profissional. Faça você também parte deste time!

## Como se candidatar
Por favor envie um e-mail para axxiom.rh@axxiom.com.br com seu CV anexado - enviar no assunto: Vaga Java

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
