### ISSUE TITLE
[Campinas] Back-End Developer PHP na [StarCorp]

### ISSUE THREAD

**Issue by tmsouza** [backend-br/vagas#474]
# Procuramos alguém que
* Tenha experiência com PHP;
* Tenha inglês avançado;
* Goste de colocar a mão na massa;
* Conhecimento dos princípios SOLID e TDD;

# Você será responsável por
Desenvolver novas funcionalidades para plataforma de e-commerce (marketplace) internacional, incluindo integração de sistemas internos e de parceiros através de APIs REST/SOAP.

# Como se candidatar
Por favor envie um email para [tiago.mendes@starcorp.tech](mailto:tiago.mendes@starcorp.tech) com seu CV ou Linkedin - enviar no assunto: Developer PHP.

# Local
Campinas-SP.

# Labels
* Alocado
* PJ
* Pleno
* Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
