### ISSUE TITLE
[Remoto] Tech Lead .NET @DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [backend-br/vagas#4749]
## Nossa empresa

Somos um grupo de empresas de tecnologia nascido em Maringá, interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado: com produtos (ANYMARKET, CONSIGNET, EIVE) e também com serviços e projetos personalizados da nossa Fábrica de Software - DB1 Global Software. E estamos em expansão !!!🚀🚀🚀

Somos colaboradores distribuídos em todo o Brasil e na Argentina, com escritório em Maringá / PR, Campo Grande / MS e Presidente Prudente / SP e atuamos também de forma remota (home office) desde 2017. Estamos há 12 anos consecutivos entre as Melhores Empresas para Trabalhar, segundo o GPTW, com reconhecimento pela instituição em 2020 como empresa referência na prática de escutar o colaborador.

Somos movido por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos (as) aqui temos autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de equipe. DB1 é pra quem não quer ser mais um!

## Descrição da vaga

 Buscamos um (a) Tech Lead .NET para um dos nossos times. É uma oportunidade para atuar em projetos desafiadores para uma fintech especializada em abertura e movimentação de contas-correntes digitais e emissão de cartões de débito, crédito e pré-pago. 

## Local

Remoto ou Escritório, Maringá/PR

## Requisitos

**Obrigatórios:**
- C# avançado (saber trabalhar com recursos novos da linguagem, paralelismo, processamento multithread);
- .NET Full/Core;
- Conhecimento básico do funcionamento de CQRS e EventSourcing;
- DDD;
- Clean Code;
- Aplicação de design patterns;
- Fluência em testes unitários;
- API Rest;
- Ferramentas: Git, Sonar, Docker, RabbitMQ, SQL Server.

**Diferenciais:**
- Jenkins;
- GOCD;
- Rancher;
- AWS;
- Kafka;
- MongoDB;
- Entity Framework/Dapper;
- Kubernetes.

## Benefícios

- Vale alimentação e/ou vale refeição;
- Plano de Saúde e plano odontológico;
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
- Horários flexíveis!;
- Convênio com farmácia Droga Raia, com desconto para colaboradores;
- Pra celebrar seu aniversário, é possível sair um pouco mais cedo no dia para comemorar com quem quiser e organizar o que for necessário :)
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do nosso programa de gamificação Mestre dos Códigos.
- Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017. Além de viabilizar, nossos colaboradores que não são 100% Home Office, trabalhar de casa em algum dia da semana quando necessário.

## Contratação

CLT

## Como se candidatar

[Clique aqui para se inscrever na oportunidade](https://vagasdb1.recruiterbox.com/jobs/fk0u6pq?source=Github) , envie seus dados e nosso tempo de recrutamento e seleção entrará em contato.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by leandroribeiro** [comment]
A descrição da vaga está muito boa parabéns, mas o link para se candidatar pedindo todos os dados RG, CPF,, nome da mãe, nascimento..... Não entendi muito bem qual sentido de pedir tantos dados pessoais de um candidato, em tempo de vazamentos de dados acho até um risco, fica o feedback.

**Comment by alissongusmao** [comment]
> A descrição da vaga está muito boa parabéns, mas o link para se candidatar pedindo todos os dados RG, CPF,, nome da mãe, nascimento..... Não entendi muito bem qual sentido de pedir tantos dados pessoais de um candidato, em tempo de vazamentos de dados acho até um risco, fica o feedback.

Muito obrigado pelo feedback, Leandro. Estamos trabalhando nesses ajustes, acredito que o formulário não peça mais esses dados no ato da inscrição. Fique à vontade para me sinalizar caso encontre algum outro ponto de melhoria. Abraço.
