### ISSUE TITLE
Back-End Developer Node.js Start-Up

### ISSUE THREAD

**Issue by projectn3xt** [backend-br/vagas#475]
# Quem Somos #

Somos uma startup de crescimento acelerado que tem como objetivo oferecer soluções comerciais para pequenas empresas. 

# Quem estamos buscando? #

Somos um time ágil de desenvolvedores full stack que coloca a mão na massa. Estamos contratando uma (ou um) Desenvolvedora Backend que tenha sólida experiência com desenvolvimento em node.js para se juntar ao time no nosso escritório no Rio de Janeiro. Gostamos de quem quer sempre aprender mais e que busque fazer a diferença. Se você se encaixa neste perfil, venha crescer junto com a gente!

# Requisitos # 

- Javascript ES6 (Node.js)
- Banco de Dados ( MySQL e MongoDB )
- Criptografia 
- GIT
- Inglês (Básico)
- Testes unitários e automatizados
- Código limpo, bem escrito e organizado

# Labels # 

Javascript
Node.Js
React Native
MongoDB

**Comment by mksanti** [comment]
@projectn3xt qual o link ou email para aplicar a vaga ?

**Comment by projectn3xt** [comment]
Verdade esqueci é contato@n3xt.com.br

—
Marcelo de Mello Gomes
Sócio Diretor - N3XT TI LTDA ME
Em 20 de set de 2018 20:02 -0300, Michael Santillán <notifications@github.com> escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
