### ISSUE TITLE
[Porto Alegre] Back-end Developer @ Bonaparte

### ISSUE THREAD

**Issue by eduardomello** [backend-br/vagas#4769]
## Nossa empresa

A Bonaparte é uma agência que atua tanto no marketing digital quanto no desenvolvimento de soluções web. Há 10 anos no mercado, atuando em Porto Alegre, já colaboramos com marcas como Converse, Youcom, Coca-Cola, Facebook e Heineken.

## Descrição da vaga

Freela em projeto de desenvolvimento de API em Node.JS que será integrado em um projeto existente. Tempo estimado de trabalho em torno de 15 dias.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Node
- Experiência com express
- Experiência com TypeScript
- Experiência com APIs REST

**Desejáveis:**
- conhecimentos em Docker
- Conhecimentos com GitLab CI/CD

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para eduardo.mello@bonaparte.ag com seu CV anexado - enviar no assunto: Vaga NodeJS

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior

**Comment by rafaelfernandesbrgo** [comment]
Tenho interesse
