### ISSUE TITLE
[Campinas] Desenvolvedor Node JS na [Page Personnel]

### ISSUE THREAD

**Issue by asallum** [backend-br/vagas#477]
Sobre nosso cliente
Empresa de grande porte do segmento de tecnologia.

Descrição do cargo
Responsável pelos novos desenvolvimentos e correções de erros voltados para backend
Responsável pela interação do site com as demais aplicações
Responsável por updates do projeto aos demais envolvidos

O candidato
Formação em Análise de Sistemas, Ciência da Computação ou outros
Necessário Inglês Avançado/Fluente
Necessário experiência com desenvolvimento em Node JS
Diferencial conhecimento em AWS

Currículos enviar para Alexandre - com o ASSUNTO: Desenvolvedor Node JS
alexandresallum@pagepersonnel.com.br

Labels
Node JS
CLT

https://www.pagepersonnel.com.br/job-detail/desenvolvedor/ref/168199

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
