### ISSUE TITLE
[São Paulo] FullStack Developer .Net/Angular na [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#478]
A Confitec é uma empresa integradora de soluções de Sistemas de Informação, Consultoria de processos e Desenvolvimento de soluções de tecnologia, especializada em soluções de seguros. 

Principais Atividades: 
Integrará equipe de desenvolvimento de plataforma web e aplicativos mobile voltados ao mercado de Seguros. 

Pré Requisitos:
Ensino superior completo (ou cursando último semestre);
Vivência com AngularJS, .NET/.NetCore, C#, Visual Studio, GIT/TFS, Orientação a objetos, HTML/CSS/Bootstrap e SQL Server; 
Diferencial: conhecimentos em  IONIC, Angular 2+, Design Patterns, PWA​.

Local de Trabalho: 
Zona Sul de São Paulo – Próximo ao Morumbi Shopping e estação Morumbi da CPTM.

Contratação:
CLT Full + Benefícios (Vale refeição de R$24,30/dia, VT, Assistência médica e odontológica, PLR, Cursos e Treinamentos). 

Candidatura: Enviar CV com assunto “Analista Desenvolvedor .Net” e pretensão salarial para curriculos@confitec.com.br. 

Boa sorte!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
