### ISSUE TITLE
[Uberlândia - MG] Desenvolvedor Full Stack na KANTTUM

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#479]
### Sobre a empresa: Kanttum

Empresa de informática com foco em formação de professores.

### Descrição: Ocupações do cargo

O profissional será responsável por programar novas funcionalidades e manter o produto atual, o qual é dividido principalmente em um Backend (Ruby on Rails API) e Frontend (Vuejs). Além disso, também é necessário conhecimento de ferramentas como git, postman e serviços como Heroku, AWS S3, AWS Cloudfront.

### Benefícios

O regime de contratação será CLT, com isso, terá o seguinte benefício:

Vale Refeição.

### Aptidões e qualidades

O profissional deve possuir as seguintes aptidões e qualidades:

Comprometimento com as entregas;
Capacidade de aprender rápido;
Sentimento de dono;
Saber trabalhar em equipe.

### Informações complementares

É desejável mas não obrigatório a experiência prévia nas tecnologias utilizadas, sendo importante a capacidade de aprendizado do candidato e conhecimento prévio em tecnologias correlatas.

### Labels

CLT
Pleno
Alocado

### Link de cadastro da vaga: http://bit.ly/2OJMPBG

**Comment by megandavulpi** [comment]
Up!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
