### ISSUE TITLE
[Remoto] Back-End Developer Júnior/Pleno/Sênior na D3.do

### ISSUE THREAD

**Issue by heyvito** [backend-br/vagas#48]
Desenvolvedor Backend com experiência e apaixonado pelo que faz.

## Requisitos
- Tecnicamente excelente
- Curioso pelo universo digital
- Proativo
- Alguém que se compromete com qualidade e prazos
- Alguém que gosta de trabalhar em equipe
- Alguém que ama do que faz
- Alguém bacana :)

## Local
Remoto

## Benefícios
- Plano de Saúde Bradesco
- Auxílio Academia
- Horário Flexível

## Nossa empresa
A D3 é uma produtora que há 15 anos ajuda empresas a criarem produtos digitais usando software, hardware e design. Descubra mais sobre o que estamos fazendo no [nosso site](https://d3.do/), no [Vimeo](https://vimeo.com/196785380), ou em http://d3.do/d3_digital.pdf.

## Contratação
CLT - Salário à combinar

## Como se candidatar
Topa o desafio? [vem.d3.do](https://vem.d3.do)

**Comment by Pedro-Souza** [comment]
Enviado!

**Comment by reginaldojunior** [comment]
Tem linguagens especificas para eu colocar nos labels?

**Comment by HandersonSilva** [comment]
Enviado....

**Comment by heyvito** [comment]
Oi @reginaldojunior! 
Não impomos requisitos de tecnologia porque além de termos vagas em todos os níveis, não procuramos nenhum especialista em um framework ou tecnologia, mas sim alguém que possa nos ajudar com as demandas dos projetos que temos por aqui. Ao invés de apontar as tecnologias que usamos, preferimos conversar e conhecer melhor o candidato, o que nos permite identificar o perfil com mais facilidade. ✨

**Comment by reginaldojunior** [comment]
ótimo! vlw 👍

**Comment by pwener** [comment]
Olá, me inscrevi pra vaga de front, mas me interesso por essa também, preciso fazer algo?

**Comment by heyvito** [comment]
@pwener Oi Phelipe! Obrigado por se inscrever! 🙌 
Você não precisa tomar nenhuma ação quanto a isso: analisaremos seu perfil tanto para a vaga de back quanto para a de front, ok?
Boa sorte! :)

**Comment by pwener** [comment]
@victorgama ok, obrigado!

**Comment by julioxavierr** [comment]
Ainda dá tempo de participar?! Enviado! 😄

**Comment by heyvito** [comment]
Dá tempo sim, @julioxavierr! 🙌

**Comment by gadielkalleb** [comment]
Enviado.

**Comment by josebispo** [comment]
Aguardando a ligação =D

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
