### ISSUE TITLE
[Belo Horizonte] Desenvolvedor PHP na D'Acordo Mediações

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#480]
### Sobre a empresa: D'Acordo Mediações

A D’Acordo Mediações é uma empresa especializada na prevenção, gerenciamento e resolução de conflitos. 
Com foco em mediação, conciliação e negociação, desenvolvemos tecnologias inovadoras para evitar disputas judiciais e administrativas. 
Por meio de Terminais de Autoatendimento e de uma Plataforma web, conectamos empresas e clientes para solucionar conflitos.

### Descrição: Ocupações do cargo

O profissional será responsável por programar e ajudar na construção e manutenção da arquitetura da aplicação, junto a isso, ele irá implementar e evoluir funcionalidades na plataforma web da D'Acordo.

São requisitos para a vaga as seguintes linguagens e frameworks:

PHP;
JavaScript;
JQuery;
DSL.

### Benefícios

O regime de contratação será PJ, com isso, os benefícios estão incorporados na remuneração da vaga.

O profissional também terá flexibilidade de horário e possibilidade de trabalhar home-office quando possível.

### Aptidões e qualidades

As aptidões e qualidades que o profissional deve possuir são as seguintes:

Pró-atividade;
Capacidade de trabalhar em equipe;
Bom relacionamento interpessoal;
Responsabilidade;
Criatividade.

### Informações complementares

O profissional participará ativamente e terá voz ativa no desenvolvimento do projeto. Buscamos incentivar a evolução constante de nossos profissionais e fornecer feedbacks com frequência para aprimoramento.

### Labels

PJ
Alocado
Junior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
