### ISSUE TITLE
[São Paulo] Desenvolvedor ASP. NET Pleno na [RADAR PROFISSIONAL]

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#481]
Sobre nosso cliente
Empresa de grande porte do segmento de tecnologia.

Requisitos da vaga: 
•	- Experiência em desenvolvimento de aplicação web
•	- C#
•	- .net framework 4.7 / core 2
•	- Entity framework
•	- Experiência em desenvolvimento de aplicação web
•	- Asp.net core
•	- apis restful
•	- Asp.net mvc, utilizando a linguagem c#
•	- Experiência e conhecimentos amplos em entity framework, html, css (tableless), javascript, jquery e jquery mobile
•	- Design patterns
•	- Mongodb
•	- Angularjs

São Paulo - Paulista

Contratação : 
PJ

Benefícios : 
VR
VT
15 dias de férias remuneradas.

Currículos enviar para vagas@radarprofissional.com.br - com o ASSUNTO: Desenvolvedor ASP.NET

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
