### ISSUE TITLE
[Remoto] Desenvolvedor(a) Back-end Jr, D3.

### ISSUE THREAD

**Issue by Julianaricci** [backend-br/vagas#482]
O THE GRID está com uma nova vaga aberta:
Back-end  Jr| D3 | https://bit.ly/2OTzXZW

Estamos à procura de um(a) desenvolvedor(a) de Back-end Jr responsável por gerenciar o intercâmbio de dados entre o servidor e os usuários. Acreditamos na autogestão, mentalidade empreendedora e paixão para alcançar grandes novos desafios todos os dias.

Se curtir essa vaga ou tiver alguma indicação, é só entrar em contato com a gente.

Muito obrigada, 
Juliana Ricci
THE GRID

**Comment by gutocosta** [comment]
Aplicado!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
