### ISSUE TITLE
[Remoto] - Formação e Seleção Simbiose — Java & DB

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#483]
## Descrição da vaga

Este é um processo de seleção diferente, pois visa **formar pessoas** para trabalhar (remotamente) na área de desenvolvimento do banco de dados proprietário que suporta o SlicingDice, uma das iniciativas da Simbiose.

> Qualquer pessoa que tenha as atitudes e comportamentos que julgamos serem adequados para nossa cultura e que esteja disposta a estudar muito, conseguirá um trabalho na Simbiose dentro de 1 ou 2 meses.

Por favor, acesse esse link:
https://medium.com/@simbioseventure/forma%C3%A7%C3%A3o-e-sele%C3%A7%C3%A3o-simbiose-java-db-22e6b74e71a6

## Local

Remoto ou Escritório São Paulo - Chácara Santo Antônio.

## Benefícios

Veja aqui:
https://medium.com/@simbioseventure/forma%C3%A7%C3%A3o-e-sele%C3%A7%C3%A3o-simbiose-java-db-22e6b74e71a6

## Requisitos

Veja aqui:
https://medium.com/@simbioseventure/forma%C3%A7%C3%A3o-e-sele%C3%A7%C3%A3o-simbiose-java-db-22e6b74e71a6

## Contratação

CLT ou estágio, o que o profissional preferir.

## Nossa empresa

Veja aqui:
https://github.com/s1mbi0se/company/wiki/

## Como se candidatar

Por favor, leia o link abaixo e siga as instruções:

https://medium.com/@simbioseventure/forma%C3%A7%C3%A3o-e-sele%C3%A7%C3%A3o-simbiose-java-db-22e6b74e71a6

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
