### ISSUE TITLE
[Brasília -DF] .NET Back-end Developer [@ilia digital]

### ISSUE THREAD

**Issue by Barbaramrsan23** [backend-br/vagas#4847]
## Sobre nós

A ília é uma empresa que veio para facilitar. Somos especialistas em simplificar como interações entre pessoas, produtos e serviços por meio da tecnologia e do design.
Somos focados principalmente em três setores: serviços financeiros, mobilidade e seguros. Temos mais de 100 equipes dedicadas, sediadas no Brasil e na Espanha, que atendem clientes premium nas Américas e na Europa.
Construímos soluções centradas nas pessoas, buscando a melhor experiência de usuário possível. Afinal, só assim alcançaremos o nosso objetivo: tornar o mundo surpreendentemente mais simples.

## Por que trabalhar com a gente

Você terá a oportunidade de fazer um trabalho que impacta a vida das pessoas. É uma chance de resolver problemas reais, com diversos desafios que trazer crescimento para você e sua carreira.
Temos um ambiente amigável, solidário e aventureiro. Aqui todo mundo anda lado a lado. Errar, aprender e evoluir em conjunto é algo intrínseco da nossa cultura.
Gostamos de trabalhar com gente diferente. Aqui você irá conviver com pessoas de diversas origens, experiências, habilidades e perspectivas.
Na ília, todo mundo tem as mesmas oportunidades de crescer e compartilha um mesmo objetivo: tornar o mundo surpreendente mais simples.

## Local

Vaga 100% remota!

## Requisitos

**O que você precisa para fazer parte do nosso time?**

- Conhecimento de .NET e .NET core;
- Experiência com arquitetura DDD;
- Experiência com APIs RESTFul;
- Noções básicas de bancos de dados não relacionais: CosmosDB;
- Noções básicas de programação assíncrona;
- Inglês intermediário.

**O que pode te diferenciar?**

- Conhecimento de metodologias ágeis;
- Conhecimento de Azure, docker, kubernetes, Postman, Kafka e Service Fabric;
- Experiência com teste unitário;
- Experiência em C#;
- Desejável DevOps.

## Responsabilidades e atribuições:

Nossos projetos em específico, tem como principal desafio a grandeza e o contato com clientes nacionais e internacionais. Conta com um tempo altamente capacitado em desenvolvimento de aplicações web e mobile em diferentes plataformas, onde o objetivo é entregar para o usuário uma plataforma que faça a diferença na vida das pessoas em qualquer hora e local.

## Conheça nossos incentivos e benefícios:

- Contrato de Trabalho CLT - 40h semanais podendo ser realizado remoto de qualquer região do Brasil, ou em algum dos nossos escritórios em Brasília ou São Paulo. Sendo que neste momento de pandemia, a empresa encontra-se 100% remota;
- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição ou Alimentação;
- Programa de incentivo ao inglês com atividades de mentoria e prática com nosso Professor particular;
- Programa de premiação a indicação de outros profissionais;
- Alugamos seu notebook pessoal (valor mensal), mas se preferir disponibilizamos uma máquina da empresa pra você (benefício de livre escolha);
- Fóruns Técnicos;
- Grupos de Capítulo;
- Seu niver, seu bolo!
- Seguro de Vida.

## Você pode se inscrever a vaga em:
https://boards.greenhouse.io/ilia/jobs/4008829004

**Comment by FilipeAugustoVO** [comment]
Boa noite! Como faço para me inscrever na vaga? Não vejo nenhum link ou
e-mail apropriado para enviar meu curriculum.

**Comment by Barbaramrsan23** [comment]
Oi Filipe! Segue link para inscrição na vaga: https://boards.greenhouse.io/iliadigital/jobs/4006970004

**Comment by Barbaramrsan23** [comment]
Olá Filipe, boa tarde!
Segue o link de inscrição: https://boards.greenhouse.io/ilia/jobs/4008829004

**Comment by FilipeAugustoVO** [comment]
Obrigado, Bárbara!

**Comment by FilipeAugustoVO** [comment]
Barbara, não está conseguindo encontrar a página.

**Comment by Barbaramrsan23** [comment]
@FilipeAugustoVO , tivemos uma alteração na nossa página de carreira. Mas agora está ok! Segue novo link: https://boards.greenhouse.io/ilia/jobs/4008829004
