### ISSUE TITLE
[Curitiba] Back-end Developer no Grupo Inlog

### ISSUE THREAD

**Issue by andrecamilo** [backend-br/vagas#485]
**Descrição da vaga**
Buscamos um desenvolvedor que goste de novos desafios usando a linguagem C# com os frameworks .Net Core ou .Net Framework
O profissional irá atuar com metodologias ágeis, equipes autogerenciáveis e desenvolver ou dar manutenção em aplicações de alto desempenho.

**Necessário:**
Boa lógica de programação e algoritmos, além de padrões e boas práticas de desenvolvimento, performance em aplicações web.

**Desejável:**
C#, SQL, Docker.

**O que oferecemos?**
CLT, VT, VR, Plano de saúde e odontológico
Salário a combinar
Empresa com ambiente descontraído
Escritório bem no centro de Curitiba
Frutas e snacks o dia todo
Parcerias de desconto para graduação e pós-graduação
Seguro de vida em grupo
Quem somos?
Somos um grupo que tem a inovação como um dos nossos valores essenciais, sendo o primeiro e o maior no país a oferecer soluções completas ao mercado de controle, otimização e automação de empresas com operações de campo, nas áreas de coleta de resíduos e transporte coletivo.

**Tem o perfil que procuramos?**
Currículos para: beinlog@inlog.com.br
Realize um de nossos testes em [github.com/weareinlog](http://github.com/weareinlog)
e venha fazer parte do nosso time

#beINLOG

**Labels:**
CLT,
Alocado,
Júnior, Pleno ou Sênior (temos vagas para todos os níveis)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
