### ISSUE TITLE
[Joinville] Back-end Developer na NG 

### ISSUE THREAD

**Issue by vitorebatista** [backend-br/vagas#486]
## Descrição da vaga
Buscamos um **estágiário** Back-end Developer para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossas plataformas. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com Node.JS, Typescript, PostgreSQL e muito mais, no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. padrões de projeto, testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local
[Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC](https://goo.gl/maps/f5mLxtRkd892)

## Benefícios
- Vale transporte ou combustível / Vale alimentação ou refeição (sim, conforme legislação);
- Plano de saúde Bradesco;
- Plano odontológico;
- Seguro de vida;
- Bolsa de estudo para ensino superior conforme regras da empresa;
- Casa de praia para os colaboradores em Piçarras/SC.

**Diferenciais**
- Ambiente extremamente propício à aprendizagem;
- Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
- Diferentes stacks para diferentes projetos;
- Mesa de sinuca para jogar nos intervalos e almoço;
- Almoço de 1 hora e meia;
- Café + bolachas/biscoitos + frutas todos os dias;
- Geladeira e microondas para esquentar seu almoço e lanches.

## Requisitos

**Obrigatórios:**
- Cursando : Ciência da Computação, Sistema da Informação, Engenharia da Computação ou cursos relacionado a área de tecnologia
- Disponibilidade para estagiar 6 horas (30 horas semanais).
- Conhecimento com Git para versionamento de código;
- Linux user (você escolherá sua distro)
- Inglês técnico (:eyes: stackoverflow);

**Desejáveis**
- Banco de dados não relacional e/ou relacional (MongoDB, PostgreSQL, etc.);
- Experiência com API's RESTful e/ou GraphQL;
- Familiaridade com desenvolvimento ágil;

**Diferenciais:**
- GitHub ativo;
- Functional programming (Ramda);
- Testes unitários;
- Conhecimento DevOps - CI (Integração Contínua) / CD (Entrega contínua).

## Contratação

Estágio

## Nossa empresa
A [NG Informática](www.ngi.com.br) é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS). Também possuímos um sistema de gestão de alertas chamado [Rung](www.rung.com.br), este construído com Node.js. Agora estamos iniciando uma nova fase em um sistema SAAS e precisamos de você!

**O que usamos:**
- GIT + Scrum + Kanban + TFS
- Node.js + Typescript
- TypeORM + PostgreSQL
- RabbitMQ
- Jenkins
- Github
- Slack

## Como se candidatar

Por favor, envie um email para [curriculo@ngi.com.br](mailto:curriculo@ngi.com.br) com seu CV anexado e link do Github com o assunto: Vaga Back-end Developer - Github/Backend-BR

## Labels

- Estágio
- Presencial
- Node.js
- Typescript
- PostgreSQL

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
