### ISSUE TITLE
[São Paulo - SP] Desenvolvedor JavaScript Puro [Replikante]

### ISSUE THREAD

**Issue by rodrigobmoura** [backend-br/vagas#487]
## Nossa empresa

Somos uma companhia em franco crescimento que provê soluções e serviços utilizando inteligência artificial para replicar e automatizar as interações humanas.

## Descrição da vaga

Estamos em busca de um desenvolvedor JavaScript Senior. Buscamos alguém proficiente em JavaScript puro. No dia a dia, iremos utilizar muitas bibliotecas, porém, é importante que o candidato tenha conhecimento da linguagem em si, pois em alguns casos de uso, não utilizamos bibliotecas prontas e conceitos como: closures, IIF, first-class functions, stack execution, etc., são essenciais.

Não exigimos nada além de conhecimento em JavaScript. Qualquer outra habilidade será um diferencial.

A vaga é somente para candidatos que residam na cidade de São Paulo.
	
**Diferenciais:**

Provemos um ambiente estimulante, com as seguintes características:

•	Hierarquia mínima

•	Horários flexíveis

•	Opção de fazer home office

## Requisitos

**Obrigatórios:**

•	 JavaScript

**Desejáveis:**

Node.js
WebSockets

## Local

São Paulo - SP  (CENU - Berrini) - Zona Sul

## Contratação

Salário:

•	A combinar.

Tipo de contratação:

•	CLT ou PJ.

## Como se candidatar

Os interessados devem enviar seu currículo, LinkedIn e GitHub, mais pretensão salarial, para o e-mail: tecnico@replikante.com.br. 

## Labels

- CLT
- PJ
- Alocado
- Remoto - Parcial
- Senior

**Comment by rodrigobmoura** [comment]
A vaga segue em aberto.

**Comment by joeljuca** [comment]
A vaga parece interessante - mas uma vaga remota apenas para residentes em São Paulo? Tem certeza que a mesma é remota, @rodrigobmoura?

**Comment by rodrigobmoura** [comment]
> 
> 
> A vaga parece interessante - mas uma vaga remota apenas para residentes em São Paulo? Tem certeza que a mesma é remota, @rodrigobmoura?

Fazemos reuniões presenciais constantemente em nosso escritório e em clientes, que estão localizados majoritariamente em São Paulo. Tanto que a vaga está com a tag "Remoto - Parcial".
