### ISSUE TITLE
[Campinas] Back-End Developer | PERFORMA IT

### ISSUE THREAD

**Issue by talentreplacement** [backend-br/vagas#488]
Estamos buscando desenvolvedores Web Back-End responsáveis por desenvolver a lógica server-side e a definição e a manutenção de bases de dados de aplicações Web garantindo alta performance de resposta às requests originadas no client-side. 
Você também será responsável por integrar os elementos de front-end desenvolvido pelos seus colegas às regras da aplicação, por isso um conhecimento básico das tecnologias de front-end também é necessário. 

**Responsabilidades** 
•	Integração dos Elementos desenvolvidos pelos desenvolvedores front-end com a lógica de aplicação server-side; 
•	Desenvolvimento de serviços web e web api em C#; 
•	Implementar as camadas de segurança e proteção dos dados da aplicação; 
•	Desenhar e implementar as soluções de armazenamento de dados; 
•	Desenhar e implementar as soluções de validação de dados, tratamento de erros e log para as aplicações; 
•	Criar código e bibliotecas reutilizáveis para uso futuro; 
•	Otimizar a aplicação para maior velocidade e escalabilidade; 

**Requisitos e Qualificações** 
•	Proficiência em desenvolvimento em tecnologias web server-side ASP.NET em C# (ASP.NET MVC Controllers / ASP.NET MVC Web API); 
•	Proficiência em desenvolvimento de serviços Web WCF (REST e SOAP); 
•	Proficiência em linguagem de programação C#; 
•	Proficiência em banco de dados SQL Server; 
•	Bom entendimento de autenticação e autorização de usuário entre múltiplos sistemas, servidores e ambientes;
•	Integração entre código de lógica de negócios e bases de dados; 
•	Capacidade de criação de estruturas de dados capazes de suprir as necessidades da lógica de negócios a ser implementada; 
•	Conhecimentos em manutenção de sessão em aplicações Web (incluindo ambientes distribuídos); 
•	Conhecimentos básicos de infraestrutura de aplicações Web Microsoft (IIS Sites, Application Pools); 
•	Desenvolvimento em ASP.NET Core 2 será considerado um diferencial; 

**Interessados enviar cv com pretensão salarial para recrutamento@talentreplacement.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
