### ISSUE TITLE
[São Paulo] Back-End Developer Node.js na Valleweb

### ISSUE THREAD

**Issue by afonsopacifer** [backend-br/vagas#49]
## Descrição da vaga

Mais do que desenvolvedores tecnicamente perfeitos, estamos em busca de pessoas que verdadeiramente se divertem e são felizes aprendendo e compartilhando conhecimento ❤️ .

**Sua missão, caso deseje aceitá-la é:**

Trabalhar no time que irá criar do zero nossos novos produtos (em geral ERP).
Estar disposto a aprender muito.

Ser responsável por implementar a camada da aplicação que conecta ao banco e entrega APIs para o Front-End, isso através das mais novas tecnologias possíveis (ES[7/8/9])!

Entregar features/módulos sempre com qualidade máxima, por isso trabalhamos com tudo muito bem documentado, testado, performático, escalável e manutenível. Basicamente você terá sempre a responsabilidade de criar um projeto que será fácil e seguro para qualquer pessoa.

Trabalhar tanto em nosso produto interno (a nível de aplicação), quanto em diversos projetos Open Source que compõem nossos produtos.

## Requisitos

**Obs:** Temos vagas para Pleno e Sênior. (ai depende de quantos requisitos você atende e seu background)

**Técnicos**

- Sólidos conhecimentos em Javascript.
- Sólidos conhecimentos em MondoDB.
- Entender como o Node.js funciona por baixo dos panos. (Event Loop, etc...).
- Gostar de tests automatizados.
- Entender bem o funcionamento do HTTP.
- Criação de APIs REST.
- Controle de versão com GIT.

**Soft Skills**

- Vontade de aprender novas tecnologias e estar sempre animado com novidades.
- Trabalho em equipe, compartilhar conhecimento e não ter vergonha de admitir que não sabe algo.
- Gostar de Open Source <3.
- Ser ativo na comunidade, seja como participante, organizador ou palestrante.

## Desejável

**Técnico**

- Boas práticas em geral (Design Patterns, performance,  etc…). 
- Conhecimentos de Infra.
- SQL Server.
- Estratégias de cache.
- Redis.
- Integração e entrega contínua com Jenkins.
- Interesse por Blockchain.

**Soft Skills**

- Interesse em entrar para core teams de projetos open source grandes. (ou já fazer isso)
- Interesse em palestrar/organizar em eventos de tecnologia. (ou já fazer isso)

## Diferencial

- Interesse em aprender sobre Front-End.

## Local

Pinheiros, São Paulo - SP | Em frente ao Shopping El Dorado

Obs: A princípio apenas alocado.

## Contratação

CLT ou PJ com salário a combinar

## Benefícios

**Básico:**

- VR.
- VT.

**Sala dedicada apenas ao time, com:**

- TV grande com apple TV.
- Maquina de café instantâneo com refil a vontade.
- Puffs para programar relaxado.
- Bebedouro com água mineral dedicado.
- Frigobar dedicado.
- Microondas dedicado.
- E todo o resto que um escritório dev precisa ter.

**Apoiamos que você se desenvolva com:**

- Auxílio financeiro para participar de eventos.
- Compra de livros.
- Patrocínio para fazer cursos.
- Tech Talks internas.
- Seções de pair programing.
- Aulas particulares de inglês.
- Plano de carreira.

## Um pouco sobre nossa cultura

**Apoio a comunidade**

Temos interesse em participar da comunidade de desenvolvedores sediando meetups, 
patrocinando conferências ou ajudando no que for possível.

**Roupas no local de trabalho**

Apenas use.

**Horários**

O horário padrão da empresa é das 8h às 17h de segunda a sexta (40h semanais), mas você tem flexibilidade para a hora de chegada e saída, assim como possibilidade de sair mais cedo ou chegar mais tarde e compensar em outro dia.

Após as 18h você é convidado a se retirar e viver sua vida pessoal, se quiser pode ficar e trabalhar em projetos Open Source ou compensar horas de outro dia, mas não será cobrado para ficar até mais tarde como acontece na maioria dos lugares.

**Trabalho remoto**

Possibilidade de ficar remoto quando necessário e posteriormente podemos ter abertura para ficar dias fixos da semana como home office. 

## Como se candidatar

Envie um e-mail (com Linkedin, Github, Site, etc... ou seja, o que tiver de legal p mandar 😄 ) para **afonso.pacifer@vallesistemas.com.br** com o assunto **Vaga Back** e se quiser da um salve aqui na issue ❤️

**Comment by thiagoluiznunes** [comment]
Que vaga show!

**Comment by jonathas** [comment]
Parece ser ótima mesmo! Parabéns pela empresa :)

**Comment by reginaldojunior** [comment]
A vaga já foi preenchida?
