### ISSUE TITLE
[São Paulo] Vagas para backend .net core, modelos de contratações flexíveis!

### ISSUE THREAD

**Issue by berenguelaline** [backend-br/vagas#490]
Oi galera!
Tenho varias vagas em diversas linguagens,  .net,  java, fullstack e front end tembem! 
Flexibilidade, oportunidade de inovar e ambiente extremamente colaborativo : )
Enviem currículo para aline.berenguel@fullbar.com.br

**Comment by Vagmacker** [comment]
Remoto ?

**Comment by berenguelaline** [comment]
Depois de 6 meses sim!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by gabrielsimas** [comment]
Pena que é em SP.

**Comment by christianmsbrito** [comment]
Qual o nível de senioridade?

Em qua, 26 de set de 2018 12:47, Gabriel Simas <notifications@github.com>
escreveu:

**Comment by berenguelaline** [comment]
Tenho todos os níveis..manda seu cv

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Kirmayrtomaz** [comment]
@berenguelaline poderia por favor, criar as vagas separadas para cada vaga em especial. 
a ideia é ter uma descricao mais detalhada do que é a vaga. 
só dar uma olhada nas vagas que fica mais claro como fazer.
