### ISSUE TITLE
[Uberlândia] - Desenvolvedor JAVA Full Stack

### ISSUE THREAD

**Issue by andrelsperes** [backend-br/vagas#491]
**Desenvolvedor JAVA Full Stack**

**Experiência Necessária**

- Experiência mínima de 4 anos em desenvolvimentos de sistemas de médio e grande porte na área de TI.

**Conhecimentos Específicos Essenciais:**

- Conhecimento de padrões de projeto e padrões de integração

- Java(e suas principais APIs), Spring (IOC, MVC, Scheduler, JDBC, BOOT), JQuery, Javascript, HTML e CSS

- Servidores de Aplicação Apache e Apache Tomcat;

- Bancos de Dados Microsoft SQL Server (Modelagem de dados e programação);

- Mecanismos e Tecnologias para integração de sistemas (SOAP, REST, Bancos de Dados).

**Como se candidatar**
Por favor envie um email para andre@ezsolucoes.com.br com seu CV

**Local:**

Uberlândia - MG

[java]
[PJ]
[CLT]
[Alocado]
[Pleno]
[Sênior]

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
