### ISSUE TITLE
[São Paulo/SP] PHP Developer no Promobit

### ISSUE THREAD

**Issue by theogoulart** [backend-br/vagas#493]
## Descrição da vaga

Estamos buscando um desenvolvedor(a) PHP Junior para nos ajudar com desenvolvimento de nossos produtos. Preferencialmente que a pessoa saiba o básico de front end.

## Local

Escritório em São Paulo - Ibirapuera, ao lado do parque.

## Benefícios

- Bônus de desempenho anual
- Férias de 30 dias anual

#### Diferenciais

- Flexibilidade de horário
- Ambiente descontraído 
- Snacks e lanches
- Localizado ao lado do parque ibirapuera
- Eventos de lazer e técnicos bancados pela empresa todo mês (ex: PHP experience, rodízio de pizza, cinema, kart, etc)

## Requisitos

**Obrigatórios:**
- Controle de versão (Git)
- HTML5 e CSS3,
- Javascript puro e jQuery
- PHP com orientação a objetos
- MySql

**Desejáveis:**
- REST
- SCRUM
- Conhecimento em preprocessadores e automatizadores de tarefas (Ex.: Less, Sass, Gulp, Grunt, Webpack)

**Diferenciais:**
- Noções de boas práticas
- Noções de usabilidade web
- Noções de SEO e semântica
- Saber um framework PHP (Ex.: Respect, SLIM, ZEND, Laravel, etc...)
- Saber um framework javascript (Ex.: React, AngularJS, Knockout, Mustache

## Contratação

PJ a combinar

## Nossa empresa

O Promobit é uma startup que usa inteligência coletiva para encontrar as melhores ofertas do Brasil. Somos uma plataforma que empodera o consumidor, permitindo e incentivando a troca de conhecimento e informações dentro da comunidade.

Além disso, a plataforma oferece, através de aplicações próprias, uma equipe de curadores especializados em consumo. O intuito é garantir a segurança e a honestidade das informações trafegadas no site e se certificar de que são realmente promoções verdadeiras.

## Como se candidatar

Para se increver basta preencher o formulário em https://docs.google.com/forms/d/e/1FAIpQLSfZkjYFcsnLhjg7-eVJ-JCjaZAgyS0RaTPzp-BL1EWzIYAe0w/viewform

Enviaremos um email de confirmação o mais rápido possível!

## Labels

- Alocado
- Júnior
- PJ

**Comment by hilderjares** [comment]
aceita 100% home office ?

Em qui, 27 de set de 2018 às 13:05, Theo Goulart <notifications@github.com>
escreveu:

**Comment by theogoulart** [comment]
@hilderjares não, somente alocado

**Comment by theogoulart** [comment]
Processo seletivo encerrado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
