### ISSUE TITLE
Desenvolvedor Java Triad Systems – São Bernardo do Campo, SP

### ISSUE THREAD

**Issue by Sueli321** [backend-br/vagas#494]
Profissional atuará com programação e desenvolvimento Java.

Necessário conhecimento com:

J2EE6 e 7, JPA, JSP, EJB3, Hibernate, Spring, CDI, JUNIT, JSF1.X e 2.X, Richfaces, Primefaces, Jasper;

Servidor de Aplicação: Websphere (imprescindível), JBOSS;

Integração Contínua: Maven, Jenkins

Forma de contratação CLT efetivo + Assistência Médica(Porto Seguro), Vale refeição(R$396,00 ao mês), Vale Transporte(Desconto de 6%), Seguro de Vida, Cursos do Alura e desconto com universidades e pontos de lazer.

Jornada Segunda à Sexta em período integral

A exigência maior do cliente é de que o profissional tenha conhecimento com Websphere e domínio em desenvolvimento Java. Como haverá uma mudança de departamento o profissional ficará alocado no Cliente(SBC) até 03/2019 e após esta data atenderá o mesmo cliente, porém em nossa fábrica de Software na Vila Olímpia-SP.

Tipo de vaga: Efetivo/CLT
Interessados enviar CV com pretensão para: sueli.patricio@triadsystems.com.br

**Comment by MateusGabi** [comment]
Olá :smile: Por favor, siga o padrão.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
