### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Full-Stack na ASSOWEB

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#496]
### Sobre a empresa: Agência Assoweb

Somos uma agência de Comunicação e Marketing Digital orientados à Performance Criativa.
 
Nosso propósito:
"Gerar valor, transformação e impacto em pequenas, médias e grandes empresas, fazendo do meio digital uma grande fonte de aquisição de clientes. Sempre de maneira autêntica e respeitando nossos valores. "

### Descrição:

Estamos em busca de um(a) Desenvolvedor(a) web para trabalhar com o desenvolvimento de sites e lojas virtuais utilizando WordPress e WooCommerce.

### Benefícios

Vale Transporte
Vale Refeição
Cursos Allura

### Aptidões e qualidades

Conhecimentos em PHP e mysql
Bons conhecimentos de front-end (HTML5, CSS3/SASS, JavaScript e Bootstrap)
Bons conhecimentos em wordpress e woocommerce
Desenvolver temas e lojas completos utilizando Wordpress e Woocommerce
Noções básicas em plataformas de versionamento (git)

### Informações complementares:

A Agência Assoweb além de prezar por uma boa entrega aos clientes valoriza muito o seu time e todos aqueles que participam da empresa. Se você está buscando um ambiente com muito trabalho, aprendizado e gosta de se comunicar essa vaga é a ideal para você!

### Labels

- Alocado
- CLT
- Júnior

**Comment by hilderjares** [comment]
aceita 100% home office ?

Em sex, 28 de set de 2018 às 15:59, Megan da Vulpi <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
