### ISSUE TITLE
[São Paulo] Desenvolvedor Fullstack 

### ISSUE THREAD

**Issue by berenguelaline** [backend-br/vagas#497]
Nossos desafios hoje estão em garantir que cada indivíduo impactado por nós seja multiplicador dos valores que acreditamos, e através da tecnologia expandir nosso alcance.
Para alcançarmos esses objetivos, estamos a procura de Full Stack Developer Junior que tenha garra, fome de aprendizado e paixão por high tech assim como nós : ) 

Se você se considera fast learner, quer trabalhar com inovação, ambiente colaborativo e muitas risadas essa vaga é para você!

*Local*
- Escritório (com flexibilidade de horários) na Barra Funda, bem pertinho do metro. 

*Contratação*
- PJ;

*Benefícios*
- Almoço garantido, você não gasta nada : ) 
- Te damos um salário a mais, tipo 13° sabe?
- Sempre estamos participando de feiras, eventos e cursos, aqui você vai aprender, hehehe; 

*Requisitos obrigatórios*
- Flexibilidade para atuar em desenvolvimento back-end e front-end;
- Conhecimentos em .Net;
- Conhecimentos em HTML5 e CSS3;
- Conhecimentos de banco de dados; 

**Diferenciais**
- Conhecimentos em React/Redux;
- Conhecimentos em metodologias de teste
- Noções sobre Integração e Implantação Contínua;
- Noções sobre microserviços;
- Conhecimento na AWS e Azure

**Comment by paulomonteirodev** [comment]
qual o contato para envio do curriculo?

**Comment by berenguelaline** [comment]
aline.berenguel@fullbar.com.br
________________________________
De: paulomonteirodev <notifications@github.com>
Enviado: terça-feira, 2 de outubro de 2018 09:24
Para: backend-br/vagas
Cc: berenguelaline; Author
Assunto: Re: [backend-br/vagas] [São Paulo] Desenvolvedor Fullstack (#497)


qual o contato para envio do curriculo?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
