### ISSUE TITLE
[São Paulo] Back-End Developer Pleno - Superare

### ISSUE THREAD

**Issue by superarelucas** [backend-br/vagas#499]
## Descrição da vaga

Estamos buscando Back-End Developers para atuarem em conjunto com a equipe, trazendo melhores resultados para grandes clientes como Claro / NET / Embratel.

Desenvolvemos diversos projetos, desde simples *landing pages*, até todo um fluxo para bots conversacionais, dashboards e etc.

## Local

Rua Francisco de Morais, 209 - Chácara Sto. Antônio, São Paulo / SP

## Benefícios

- VT
- VR de R$ 20,00/dia

## Requisitos

**Obrigatórios:**
- Git
- Linux
- PHP/NGinx
- NodeJs
- Docker, Kubernetes, Microserviços 
- Gerenciamento e configuração de ambiente Cloud (GCP, AWS)
- MongoDB, MySQL, modelagem de Banco de dados
- Acesso a Apis RestFul
- Desenvolvimento de funcionalidades no Back-End
- Desenvolver e sustentar integrações
- Desenvolvimento e manutenção de aplicações web
- Realizar a manutenção e criação de novas funcionalidades
- Experiência prévia nas linguagens informadas
- Conhecimento em metodologias ágeis (Scrum/Kanban)

**Desejáveis:**
- Mínimo de 2 anos de experiência como Back-End Developer
- Formação em ensino superior ou técnico
- Habilidades interpessoais de escrita e de comunicação verbal

**Diferenciais:**
- Ter criado algum projeto utilizando Node + Express;
- Ter criado algum projeto utilizando Laravel / Lumen;
- Ter criado algum chatbot utilizando Dialogflow, LUIS ou Watson;
- Ter bibliotecas open-source ou publicadas via NPM / Composer.

## Contratação

**Modelo:** CLT
**Horário:** 9h30 às 18h30

## Nossa empresa

A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.

## Como se candidatar

Por favor envie um email para joao.romao@superare.co com seu CV anexado - enviar no assunto: [backendbr] Back-End Developer Pleno - Superare

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
