### ISSUE TITLE
Desenvolvedor .NET 

### ISSUE THREAD

**Issue by parisamorim** [backend-br/vagas#5]
A Global System é uma empresa de Tecnologia da Informação, especializada em Soluções de Software. Vagas de Projetos de Sistemas WEB, para a região de São Bernardo do Campo - SP.

Programador em programação WEB com MVC, C# e banco de dados SQL Server.

Local: São Bernardo do Campo – SP

Colocar no assunto: WEB

Interessados encaminhar currículos para: girlene.araujo@gsoftware.com.br

**Comment by reginaldojunior** [comment]
@parisamorim a vaga já foi preenchida sabe dizer?

**Comment by parisamorim** [comment]
Acho que já, @reginaldojunior!!! Mas encaminha o currículo!

**Comment by reginaldojunior** [comment]
Ok, é só pra saber, para fechar as que não estão mais abertas. Vou deixar mais um tempo ai. Obrigado!
