### ISSUE TITLE
[São Paulo] Back-End Developer Júnior - Superare

### ISSUE THREAD

**Issue by superarelucas** [backend-br/vagas#500]
## Descrição da vaga

Estamos buscando Back-End Developers para atuarem em conjunto com a equipe, trazendo melhores resultados para grandes clientes como Claro / NET / Embratel.

Desenvolvemos diversos projetos, desde simples *landing pages*, até todo um fluxo para bots conversacionais, dashboards e etc.

## Local

Rua Francisco de Morais, 209 - Chácara Sto. Antônio, São Paulo / SP

## Benefícios

- VT
- VR de R$ 20,00/dia

## Requisitos

**Obrigatórios:**
- Git
- PHP/NGinx
- Noções de ambiente Linux
- Noções de Node.js
- Noções de MongoDB, MySQL
- Acesso a Apis RestFul
- Desenvolvimento de funcionalidades no Back-End
- Desenvolver e sustentar integrações

**Desejáveis:**
- Mínimo de 1 ano de experiência como Back-End Developer
- Formação em ensino superior ou técnico
- Habilidades interpessoais de escrita e de comunicação verbal
- Experiência em metodologias ágeis (Scrum/Kanban)

**Diferenciais:**
- Ter projetos open-source publicados.

## Contratação

**Modelo:** CLT
**Horário:** 9h30 às 18h30

## Nossa empresa

A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.

## Como se candidatar

Por favor envie um email para joao.romao@superare.co com seu CV anexado - enviar no assunto: [backendbr] Back-End Developer Júnior - Superare

## Labels

- Alocado
- CLT
- Júnior

**Comment by guilhermeoa07** [comment]
A vaga é pra pleno ou Júnior?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
