### ISSUE TITLE
[São Paulo] Back-End Developer Júnior - D3

### ISSUE THREAD

**Issue by chr0nu5** [backend-br/vagas#502]
D3 is a digital product studio in Brazil since 2002. As a studio we build digital products for companies like Twitter, Fiat and Google. As a venture builder we've founded startups like Bloom, Zag and Aura. We believe in tech, design and poetry to reimagine products and service to a connected world.

### Work Format

- Informal work environment;
- Flexible work schedule/remote working;
- Compensation and benefits package in line with the market standard for this position.

### Who is up for the challenge in this position?

> We are looking for a Jr Back-end developer responsible for managing the interchange of data between the server and the users. We believe in self management, entrepreneurial mindset and creating passion to achieve big new challenges everyday.

### What we expect from you?

- Participate in the entire application lifecycle, focusing on coding and debugging;
- Write clean code to develop functional web applications;
- Troubleshoot and debug applications;
- Perform UI tests to optimize performance;
- Collaborate with Front-end developers to integrate user-facing elements with server side logic;
- Gather and address technical and design requirements;
- Build reusable code and libraries for future use;
- Liaise with developers, designers and system administrators to identify new features;
- Follow emerging technologies.

### Requirements

- Proven experience as a Back-end developer;
- Basic understanding of the entire web development process (design, development and deployment);
- Hands on experience with programming languages and frameworks;
- Working knowledge of CMS framework;
- Familiarity with front-end languages (e.g. HTML, JavaScript and CSS);
- Excellent analytical and time management skills;
- Teamwork skills with a problem-solving attitude.

[Our Work](https://d3.do)

You can send an email to [john@d3.do](mailto:john@d3.do) or join [here](https://vem.d3.do)

**Comment by MateusGabi** [comment]
Is it remote?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
