### ISSUE TITLE
[REMOTO] Full Stack Developer no VAGALUME

### ISSUE THREAD

**Issue by lafraia** [backend-br/vagas#504]
## Descrição da vaga

Estou buscando profissionais que possam fazer parte de uma equipe remota para vários projetos no Vagalume. Já temos alguns projetos bem interessantes prontos para iniciar o desenvolvimento. O foco é encontrar pessoas **bem** proativas, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica.

## Local

Totalmente REMOTO via Slack

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP / MySQL
- 3 anos de experiência com Javascript / jQuery (avançado)
- 3 anos de experiência com HTML5 e CSS3 (avançado)

**Desejáveis:**
- conhecimentos de SEO
- experiência anterior com trabalho remoto

## Contratação

PJ a combinar

## Nossa empresa

Você já deve ter buscado uma letra de música no Vagalume, chegou a hora de poder contribuir com o projeto ;-)

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

## Labels

- Remoto - Total
- Freela
- PJ
- Pleno
- Sênior

**Comment by fabiosilvaacs** [comment]
Bom dia, este freela é por quanto tempo? Obrigado

**Comment by lafraia** [comment]
@fabiosilvaacs Estou procurando pessoas confiáveis para trabalhar em vários projetos. ;-) Este específico de agora são dois meses, mas tenho vários outros projetos. Assim que encontrar as pessoas certas, teremos trabalhos constantes. É uma relação de confiança focado em projeto.

**Comment by rodineicosta** [comment]
Enviado!

**Comment by Tagliatti** [comment]
@lafraia é fulltime?

**Comment by lafraia** [comment]
@Tagliatti A vaga não é full time, estou buscando profissionais que possam contribuir com o projeto remotamente por tarefa (por hora)

**Comment by Gabrielmoraesp** [comment]
@lafraia a vaga ainda está em aberto?

**Comment by davidalves1** [comment]
A vaga ainda está aberta?

**Comment by preetender** [comment]
Se estiver em aberto, tenho interesse ..

Em dom, 10 de fev de 2019 14:37, David Alves de Souza <
notifications@github.com escreveu:

**Comment by abelclopes** [comment]
a oportunidade está aberta ainda?

**Comment by lafraia** [comment]
Caros, a vaga está disponível novamente #1070 😃
