### ISSUE TITLE
[São Paulo] Back end Developer.NET @BetterNow

### ISSUE THREAD

**Issue by sthefanieamarins** [backend-br/vagas#5043]
Descrição da vaga

Como Developer .NET você irá:

Realizar o Desenvolvimento de novas integrações entre sistemas;
Realizar o Desenvolvimento de novos aplicativos ou funcionalidades para aplicativos já existentes; 

Local de trabalho
100% Remoto

Requisitos da vaga

- Linguagens de programação: C#;
-Conhecimento em Orientação a objetos- Padrões de projeto (design patterns);
- Comunicação via API (Rest, Soap, Mensageria);
- Banco de dados SQL Server e/ou Oracle;

Benefícios da empresa
Plano de saúde e Odontológico 
VR/VA de R$ 550/mês
Auxílio creche 
Auxílio home office de R$100
Horário Flexível
PLR
Parcerias com faculdades e escolas de ingles

Ambiente de Trabalho incrível
Vários benefícios internos como auxilio home office sem descontos; plataforma de cursos de tecnologia, entre outros!
Plano de Carreira que funciona
A vaga paga entre 6.000,00 e 9.000,00 reais.

Sobre a empresa
A Better Now foi fundada no ano de 2015 por dois especialistas em qualidade de software, a organização surgiu com uma proposta diferente e inovadora para quem se preocupa de verdade com qualidade, agilidade e segurança da informação.

Desenvolveu um novo conceito de atendimento customizado na implementação de soluções na qualidade de softwares com uma consultoria próxima, metodologias flexíveis, processos descomplicados e transparentes, aplicando os testes necessários, agregando valor e fornecendo os resultados esperados pelos clientes.

Como se candidatar
Se te interessou me envie seu CV para o email: sthefanie.amarins@betternow.com.br que realizo a sua indicação ou Whatsapp: 11 98984 2323

CLT
Pleno
Sênior
Especialista
Remoto
Brasil

**Comment by CarlosHenriqueRC** [comment]
Na tag fala em Remoto, mas no assunto não diz nada, pode ser remoto ou não ?

******************************************
*Carlos Henrique Ramos Carvalho
*Especialista em Tecnologia .Net
*MCP.Net
******************************************


Em seg., 19 de abr. de 2021 às 18:42, sthefanieamarins <
***@***.***> escreveu:

**Comment by sthefanieamarins** [comment]
Sorry! Sou nova por aqui hehe! A vaga é 100% Home Office! :)

**Comment by sthefanieamarins** [comment]
> Na tag fala em Remoto, mas no assunto não diz nada, pode ser remoto ou não ? Sorry! A vaga é 100% Home Office hehe :)

****************************************** *Carlos Henrique Ramos Carvalho *Especialista em Tecnologia .Net *MCP.Net ****************************************** Em seg., 19 de abr. de 2021 às 18:42, sthefanieamarins < ***@***.***> escreveu:
> […](#)
