### ISSUE TITLE
|Portugal| NodeJS Developer na Aubay

### ISSUE THREAD

**Issue by silviapedrosa** [backend-br/vagas#505]
### **Descrição da vaga**
Projetos diferenciados em vários setores de atividade utilizando tecnologia NodeJS entre outras.

### **Local**
Portugal: Lisboa e Porto

### **Benefícios**
Plano de saúde
Visto de Trabalho para Portugal
Outras
Diferenciais
cultura organizacional gerida pelo nosso Hapiness Manager
horário flexível
almoço grátis todas as sexta-feiras
frigobar sempre cheio
armário das bolachas sempre cheio
eventos mensais com atividades diferenciadas

### **Requisitos**
**Obrigatórios:**
Experiência de pelo menos 2 anos com NodeJS
Domínio da língua inglesa

**Diferenciais:**
projetos internacionais que permitem contato com vários países.

### **Contratação**
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

### **Nossa empresa**
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### **Como se candidatar**
Por favor envie um email para fmorais@aubay.com com seu CV anexado colocando no assunto: Aubay: NodeJS Developer

**Comment by JCPBarbosa** [comment]
Qual seria o salário liquido?

**Comment by silviapedrosa** [comment]
Olá Jefferson,

A remuneração irá depender do tempo de experiencia. No entanto, esse tema será abordado e ajustado ao longo do processo de recrutamento.

Os melhores cumprimentos,
[Descrição: 721313813@16102008-18F2]  Sílvia Pedrosa
  International Talent Recruiter

Edifício Duque d’Ávila,
Avenida Duque d’Ávila nº 46, 7ºC – 1050-083 Lisboa
Tel: +351 2<tel:%2B351%20211%20928%20417>11 928 417 - Mobile: +351 914 053 987
Fax: +351 211 928 230<tel:%2B351%20211%20928%20230>
Skype: smarinapedrosa_1

[cid:image002.png@01D1126F.FAEB9CF0]<http://www.aubay.com/>  [cid:image003.png@01D1126F.FAEB9CF0] <http://www.facebook.com/aubayportugal>   [cid:image004.png@01D1126F.FAEB9CF0] <https://twitter.com/groupeaubay>   [cid:image005.png@01D1126F.FAEB9CF0] <https://www.youtube.com/user/aubaytv>

Antes de imprimir, pense no ambiente!
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Jefferson Barbosa <notifications@github.com>
Enviada: 3 de outubro de 2018 13:07
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Silvia PEDROSA <spedrosa@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] |Portugal| NodeJS Developer na Aubay (#505)


Qual seria o salário liquido?

**Comment by samuelfaj** [comment]
Apenas presencial ou pode ser remoto como PJ?

(Moro no Brasil)

**Comment by silviapedrosa** [comment]
Olá Samuel,

A oportunidade implica uma mudança para Portugal e é presencial.

Os melhores cumprimentos,
[Descrição: 721313813@16102008-18F2]  Sílvia Pedrosa
  International Talent Recruiter

Edifício Duque d’Ávila,
Avenida Duque d’Ávila nº 46, 7ºC – 1050-083 Lisboa
Tel: +351 2<tel:%2B351%20211%20928%20417>11 928 417 - Mobile: +351 914 053 987
Fax: +351 211 928 230<tel:%2B351%20211%20928%20230>
Skype: smarinapedrosa_1

[cid:image002.png@01D1126F.FAEB9CF0]<http://www.aubay.com/>  [cid:image003.png@01D1126F.FAEB9CF0] <http://www.facebook.com/aubayportugal>   [cid:image004.png@01D1126F.FAEB9CF0] <https://twitter.com/groupeaubay>   [cid:image005.png@01D1126F.FAEB9CF0] <https://www.youtube.com/user/aubaytv>

Antes de imprimir, pense no ambiente!
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Samuel Fajreldines <notifications@github.com>
Enviada: 16 de novembro de 2018 16:10
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Silvia PEDROSA <spedrosa@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] |Portugal| NodeJS Developer na Aubay (#505)


Apenas presencial ou pode ser remoto?

(Moro no Brasil)

**Comment by andreantunees** [comment]
CV enviado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
