### ISSUE TITLE
[São Paulo ou Remoto] Dev Ruby on Rails

### ISSUE THREAD

**Issue by vixandrade** [backend-br/vagas#508]
Procuramos profissional para atuar desenvolvimento de nossas soluções para Web! Nós moramos no **CUBO na Vila Olímpia em São Paulo**. Somos os criadores do Ahazou, assistente digital de conteúdo para negócios no setor de beleza. Já ajudamos mais de 30.000 usuários todo mês. Nossa cultura é baseada em oferecer valor ao cliente de maneira ágil e consistente. Então se você se anima com a ideia de impactar positivamente todos os dias a vida de 5 milhões de brasileiros, seu lugar é aqui com a gente.

**Área de atuação**
Desenvolvedor Full Stack

**Requisitos**
Experiência e conhecimento das melhores práticas de desenvolvimento Web - tanto back quanto front.

Nosso **STACK**: Ruby on Rails + MongoDB + Google Cloud Platform

Para se candidatar:
https://cubo.network/platform/jobs/2c1da960-b468-11e8-a010-85f49f96cf2f

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
