### ISSUE TITLE
[Remoto] Dev Ruby on Rails Freelance

### ISSUE THREAD

**Issue by vixandrade** [backend-br/vagas#509]
Procuramos profissional para atuar desenvolvimento de nossas soluções para Web! Nós moramos no CUBO na Vila Olímpia em São Paulo. Somos os criadores do Ahazou, assistente digital de conteúdo para negócios no setor de beleza. Já ajudamos mais de 30.000 usuários todo mês. Nossa cultura é baseada em oferecer valor ao cliente de maneira ágil e consistente. Então se você se anima com a ideia de impactar positivamente todos os dias a vida de 5 milhões de brasileiros, seu lugar é aqui com a gente.

Essa demanda é para um projeto novo, começando do zero. Nosso produto entrega conteúdo para as redes sociais dos micro empreendedores. Nós escalamos a entrega desses posts através dos aplicativos. A produção do conteúdo nós escalamos através do uso de designers externos que são remunerados por posts criados. Hoje o processo de cadastro desses designers, envio de briefings, upload dos posts prontos e aprovação das criações é feito todo manualmente - com planilhas no Drive, forms no TypeForm e comunicação via email.

Essa demanda de web que nós temos é para criar a ferramenta que vai auxiliar nesse processo: com um espaço para cadastro de novos designers, um espaço pra nossa equipe publicar os briefings e jobs e para os designers enviarem os posts prontos. Todo esse workflow da ferramenta é novo, a única integração que temos com o nosso sistema atual é  para cadastrar na nossa base os posts que forem aprovados.

Um detalhe importante é que esse desenvolvimento é mais crítico para desenrolar uma questão de processo interno que hoje é feito manualmente. Tenho certeza de que com o tempo eu vou precisar ajustar e mudar muitas coisas no projeto, então não estou preocupado com design ou pontos muito específicos porque é certeza que vai mudar tudo em algum momento nos próximos meses.

Stack: Ruby on Rails + MongoDB + Google Cloud Platform

Para se candidatar: se inscrever no link e mencionar interesse por job freelance.
https://cubo.network/platform/jobs/2c1da960-b468-11e8-a010-85f49f96cf2f/preview

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
