### ISSUE TITLE
[Rio de Janeiro] Backend Developer na B2W Digital

### ISSUE THREAD

**Issue by carlos-bomfim** [backend-br/vagas#51]
## **Descrição da vaga**

Você irá ajudar a criar a melhor experiência para os usuário dos maiores e-commerces da América Latina, como Americanas.com, Submarino e Shoptime.

Se você é um entusiasta de novas tecnologias, gosta de aprender, ensinar e desenvolver produtos que estão no dia a dia da galera, então tem o perfil que queremos para o nosso time!

## Local

BIT Mauá - Centro RJ
Rua Sacadura Cabral 130, Saúde, Rio de Janeiro.

## Benefícios

- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Vale Refeição ou Alimentação de R$ 24,30/dia
- Vale Transporte
- 10% de desconto nos sites da Americanas.com, Submarino e Shoptime

## Diferenciais

- Ambiente de trabalho descontraído
- Dress code informal (bermuda!)
- Sinuca e video games
- Flexibilidade de Horário
- Trabalhamos com metodologias ágeis (Scrum)
- Estamos sempre em busca de inovação
- Não desenvolvemos apenas software, também desenvolvemos pessoas :smile:

## Coisas que usamos:

- Java, Clojure, Go, Javascript, Python
- MongoDB, Riak, Datomic, DynamoDB
- Microserviços em REST APIs
- Amazon AWS
- CI / CD
- Testes automatizados

## Contratação

CLT - a combinar

## Nossa empresa

B2W INOVAÇÃO E TECNOLOGIA

Somos o BIT, a área de inovação e tecnologia da B2W. Desenvolvemos os sites da maior empresa de e-commerce da América Latina, além das plataformas Marketplace e Mobile.

A B2W Digital está crescendo rapidamente com aquisições de novas empresas e com projetos de alta escalabilidade e impacto. Trabalhamos com as tecnologias mais modernas em um ambiente diferenciado. Buscamos pessoas com pensamento inovador, movidas a desafios e antenadas com as novidades do mercado. 

## Como se candidatar

Por favor envie um email para alberto.piovesana@b2wdigital.com com seu CV anexado - enviar no assunto: Vaga Backend Developer

**Comment by raphaelfmarins** [comment]
Galera ainda estamos contratando. 👍

**Comment by reginaldojunior** [comment]
Ainda tem vagas?

**Comment by raphaelfmarins** [comment]
@reginaldojunior temos sim. Pode enviar também para raphael.marins@b2wdigital.com

**Comment by jovinho** [comment]
Up! 

Envia o email para: raphael.marins@b2wdigital.com, leonardo.maia@b2wdigital.com ou alberto.piovesana@b2wdigital.com

**Comment by reginaldojunior** [comment]
Ainda tem vagas?

**Comment by jovinho** [comment]
temos sim @reginaldojunior, envia seu curriculo para mim: leonardo.maia@b2wdigital.com

**Comment by jovinho** [comment]
UP! Temos vagas ainda galera!

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by jovinho** [comment]
Todos os níveis @guilhermeoa07

**Comment by Rafael955** [comment]
Mandei meu currículo.

**Comment by raphaelfmarins** [comment]
Up!

Enviar o email para: raphael.marins@b2wdigital.com, leonardo.maia@b2wdigital.com ou alberto.piovesana@b2wdigital.com

**Comment by MoreiraVinicius** [comment]
Enviei mas faltou eu receber os testes: [vinicius.ads.mec@gmail.com](url)

**Comment by xspager** [comment]
Olá, essa vaga ainda está aberta?

**Comment by leonardodavila** [comment]
Está sim Daniel.

Em qui, 4 de out de 2018 às 17:28, Daniel Lemos <notifications@github.com>
escreveu:

**Comment by jovinho** [comment]
Está sim @xspager ! Pode enviar o currículo :D

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
