### ISSUE TITLE
[São Paulo] Software Engineer ( DevOps ) [Creditas ]

### ISSUE THREAD

**Issue by alexkawaharada** [backend-br/vagas#510]
**Creditas**

Nosso propósito é garantir um crédito de qualidade que ajude os brasileiros a usarem seus bens como alavancas do seu progresso financeiro e pessoal. Combater as más dívidas e ajudar a realizar projetos de vida é o que nos dá orgulho e nos motiva a trabalhar. 

Para trazer inovação ao mercado de empréstimos, nós apostamos em tecnologia. É com ela que escalamos o negócio, otimizamos processos e melhoramos a experiência dos clientes. Nossa plataforma foi criada dentro de casa utilizando tecnologia open source, seguindo a filosofia agile e suas práticas. Mas nosso negócio mesmo são as pessoas: não abrimos mão do atendimento personalizado, prestando consultoria e oferecendo educação financeira para empoderar o cliente a tomar a melhor decisão.

Você acredita em aplicações altamente disponíveis, robustas e escaláveis? Entende a importância de desenvolver aplicações cloud native? Ser Software Engineer (DevOps) na Creditas é ajudar o time de Tecnologia a evoluir a arquitetura das nossas aplicações; conhecer, avaliar, desenvolver, implantar tecnologias confiáveis e disseminar a cultura DevOps.

Hoje, nós temos mais de 10 squads e pode ter certeza que você fará parte de uma equipe super estratégica, com muitos desafios, aprendizados diários e pessoas incríveis e motivadas!

**Como será o seu dia a dia**

Difundir e estimular uma cultura DevOps nos squads;
Promover a integração entre as equipes de desenvolvimento de software e infraestrutura;
Trabalhar na melhoria e agilidade de deployments;
Diagnosticar erros, monitorá-los e documentar para democratizar soluções;
Criar soluções com as melhores práticas e repassar para todos os Tripulantes dos squads.

**Os mandamentos de Software Engineer (DevOps)**

- Sólidos conhecimentos em Linux;
- Experiência com AWS e boas práticas (segurança, controle de custos). Conhecimento em redes é um diferencial;
- Experiência em programação de aplicações Web ou alguma linguagem de scripts (Shell, Ruby, Python). - Conhecimento em Go é um diferencial;
- Práticas de automação e ferramentas como Terraform, Ansible e Git;
- Familiaridade com microserviços;
- Experiência com ferramentas de CI (CircleCI, Jenkins);
- Experiência com containers (Docker) e seus orquestradores (ECS, Kubernetes).

**O que você vai encontrar na nossa tripulação**

- Ambiente que valoriza feedback e 1:1;
- Ambiente dinâmico e com crescimento exponencial;
- Background anterior também é importante, não vamos anular o que você já vivenciou. E compartilhando algumas curiosidades, apresento a Monique, responsável pela área de talentos e cientista física molecular e o Thomas da área de Analytics, formado em engenharia florestal;
- Jogamos para ganhar e queremos que nossa tripulação sempre inove e busque por novos conhecimentos, e para isso temos auxílio educação / estudo e Aulas de Inglês in company (sem descontos);
- GymPass - Além de proporcionar qualidade de vida, trabalhamos em time, conhecendo outras áreas e nos desafiamos constantemente, com nosso programa CreditasEndurance;
- Vale-Refeição; VT / Estacionamento / Fretado / Bicicletário; Plano de Saúde; Plano Odontológico; - Seguro de Vida.

Caso tenha interesse em trabalhar conosco.
Inscreva no:  https://jobs.kenoby.com/creditas/job/software-engineer-devops/5b2bfb758a615e03260efc1b

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
