### ISSUE TITLE
[Remoto] Back-end PHP Developer na Lastlink < by Coodesh />

### ISSUE THREAD

**Issue by gabrielhws** [backend-br/vagas#5105]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>A Lastlink está buscando <strong>Backend PHP Developer,</strong> para compor seu time!</p>
<p>O time de desenvolvimento é o coração do Lastlink. Por causa dele, conseguimos entregar aos nossos clientes uma ferramenta incrível para criação de comunidades e monetização de conteúdos digitais, utilizando o que há de mais inovador entre as tecnologias do mercado.&nbsp;</p>
<p>Venha fazer parte do nosso time!</p>
<p></p>

## Lastlink: 
 <h6><strong>LASTLINK</strong></h6>
<p><strong><em>CRIANDO CONEXÕES CONSCIENTES</em></strong></p>
<p>Conexão e proximidade é o que nos move.</p><a href='https://coodesh.com/empresas/lastlink'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- MySQL 
- PHP 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em desenvolvimento PHP 
- MySQL, HTML5, CSS3 
- Entenda os fundamentos das tecnologias 
- Experiência em Javascript sem frameworks 
- Experiência em layouts CSS responsivos sem utilizar bootstrap

## Benefícios: 
 - Salário compatível com o mercado e com a sua habilidade técnica 
- Vale refeição ou alimentação R$ 24,00 ao dia 
- Plano de saúde e odontológico - Sul América Nacional 
- PLR 
- Flexibilidade de horário 
- Trabalho remoto 
- No dress-code
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [PHP Developer na Lastlink](https://coodesh.com/vagas/backend-php-developer-131316?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Pleno
#### Categoria
Back-End

**Comment by raank** [comment]
Isso é fullstack.

Abraços.
