### ISSUE TITLE
[Remoto] Fullstack Developer Estágio/Júnior/Pleno/Sênior @ V360

### ISSUE THREAD

**Issue by marcello-telles** [backend-br/vagas#5127]
## Nossa empresa

Reduzir o impacto do custo Brasil nas empresas parece impossível, né? Pois esse é o nosso propósito! Nós usamos tecnologia para simplificar a burocracia brasileira e facilitar a vida dos nossos clientes.

Nossa plataforma revolucionou as áreas de ingresso fiscal em algumas das maiores empresas do Brasil. Em linhas gerais, temos uma plataforma SaaS que automatiza o recebimento de 1 milhão de documentos por ano, somando R$ 30bi em valor, e este é só o começo.

Somos uma startup do grupo Visagio, consultoria líder em desenvolvimento de pessoas no Brasil.

## Descrição da vaga

Nosso time de desenvolvimento cuida da evolução do produto, implantação da ferramenta em novos clientes e suporte à operação. Geralmente, precisamos ir além do desenvolvimento de código para evoluir o produto e resolver os problemas, contato próximo com os clientes e com os demais times internos costumam ser a chave para o sucesso.

Tecnicamente você vai trabalhar com todas as nossas tecnologias de back-end, banco de dados, front-end e metodologias ágeis. Temos um dos times técnicos mais conceituados do Brasil, com experiência de atuação nas maiores empresas do Brasil. Colaboração faz parte da nossa cultura, então vamos trabalhar lado a lado (na prática em home office 😅), e em pouco tempo você estará aprendendo, trocando experiências e ensinando.

Entendemos que você está no início da carreira e queremos te fornecer todo apoio e estrutura para você se desenvolver e crescer profissionalmente. Temos mais de 1.000 horas de treinamento e um programa de mentoria que te auxiliarão na sua caminhada.

 

Se você tem sentimento de dono e se interessa por trabalhar em um ambiente ágil, colaborativo, não-hierárquico, buscando uma carreira acelerada, vai adorar se juntar ao nosso time!

## Local

Remoto

### Estágio

**Obrigatórios:**
- Ter alguma experiência em linguagem de programação, não precisa ser expert, mas ao menos se sentir confortável em pelo menos uma das seguintes: Ruby, Python, C#, PHP, Java ou Javascript. Ah, é importante que nessas linguagens você conheça algum framework, como Rails, Django, Laravel, Angular ou Node;
- Também é legal que você esteja familiarizado tanto com back-end quanto com front-end, dado que a vaga é full-stack, vamos contar com sua ajuda na evolução do produto das classes mais escondidas à identidade visual da plataforma.

**Desejáveis:**
- conhecimento em Git/GitHub e/ou bancos de dados relacionais
- conhecimento em testes com Rspec/Minitest
- conhecimento em arquitetura MVC e REST

**Diferenciais:**
- contribuição em projetos open source
- projetos pessoais
- conhecimento em: Sidekiq, Redis, ElasticSearch e/ou infra AWS
- conhecimento de padrões de projeto (_design patterns_) e arquiteturas MVC e REST
- conhecimento em metodologias ágeis

### Júnior

**Obrigatórios:**
- Ter alguma experiência em linguagem de programação, não precisa ser expert, mas ao menos se sentir confortável em pelo menos uma das seguintes: Ruby, Python, C#, PHP, Java ou Javascript. Ah, é importante que nessas linguagens você conheça algum framework, como Rails, Django, Laravel, Angular ou Node;
- Também é legal que você esteja familiarizado tanto com back-end quanto com front-end, dado que a vaga é full-stack, vamos contar com sua ajuda na evolução do produto das classes mais escondidas à identidade visual da plataforma.

**Desejáveis:**
- experiência em Git/GitHub e/ou PostgreSQL
- conhecimento em testes com Rspec/Minitest
- conhecimento em otimização de queries SQL
- conhecimento de padrões de projeto (_design patterns_) e arquiteturas MVC e REST

**Diferenciais:**
- contribuição em projetos open source
- projetos pessoais
- experiência com: Sidekiq, Redis, ElasticSearch e/ou infra AWS

### Pleno

**Obrigatórios:**
- Ter ao menos 2 anos de experiência com linguagem de programação, de maneira que consiga se adaptar rápido às tecnologias utilizadas pelo time. De preferência que esta linguagem seja o Ruby, com a qual já trabalhamos, mas se sua experiência for em Python, C# ou PHP não tem problema. Ah, é importante que nessas linguagens você tenha trabalhado e conheça os framework, como Rails, Django, Laravel, Angular ou Node;
- Como esta vaga é para full-stack, precisaremos que você se vire bem no front-end e no back-end. Vamos contar com sua ajuda na evolução do produto das classes mais escondidas à identidade visual da plataforma;
- Você precisará também se desenvolver como referência técnica, capacitando os demais integrantes do time, experiências prévias com liderança técnica são muito bem vindas. Assim como o trabalho com metodologias ágeis, muito presentes no nosso dia a dia, esperamos que você tenha participado de times que trabalhassem com metodologias ágeis.

**Desejáveis:**
- experiência em Git/GitHub e/ou PostgreSQL
- experiência em testes com Rspec/Minitest
- conhecimento em otimização de queries SQL
- conhecimento de padrões de projeto (_design patterns_) e arquiteturas MVC e REST

**Diferenciais:**
- contribuição em projetos open source
- projetos pessoais
- experiência com: Sidekiq, Redis, ElasticSearch e/ou infra AWS

### Sênior

**Obrigatórios:**
- Ter ao menos 4 anos de experiência com linguagem de programação, onde boa parte tenha sido dedicada ao Ruby, em conjunto com o Rails. Aprendizado rápido é essencial para se adaptar às tecnologias utilizadas pelo time. Ah, ter boa experiência em outros frameworks pode contar muito para esta vaga: Django, Laravel, Angular ou Node
- Como esta vaga é para full-stack, precisaremos que você tenha bastante experiência tanto no front-end quanto no back-end. Você irá auxiliar na evolução do produto das classes mais escondidas à identidade visual da plataforma
- Você será uma referência técnica, capacitando os demais integrantes do time. É muito importante que você já tenha experiências prévias com gestão de projetos e liderança técnica. Assim como o trabalho com metodologias ágeis, muito presentes no nosso dia a dia, esperamos que você tenha bastante experiência e esteja acostumado com metodologias ágeis
- Ampla experiência com bancos de dados relacionais (principalmente o Postgres) também é fundamental

**Desejáveis:**
- experiência com liderança em projetos grandes e/ou complexos
- experiência em Git/GitHub e/ou PostgreSQL
- experiência em testes com Rspec/Minitest
- experiência com otimização de queries SQL
- conhecimento de padrões de projeto (_design patterns_) e arquiteturas MVC e REST

**Diferenciais:**
- contribuição em projetos open source
- projetos pessoais
- experiência com: Sidekiq, Redis, ElasticSearch e/ou infra AWS

### Estágio

- remuneração entre R$ 2.000,00 e R$ 2.500,00
- seguro de vida

### Júnior

- remuneração entre R$ 3.500,00 e R$ 4.500,00
- VR de R$ 35/dia
- plano de saúde Bradesco
- seguro de vida

### Pleno

- remuneração entre R$ 5.000,00 e R$ 6.000,00
- VR de R$ 35/dia
- plano de saúde Bradesco
- seguro de vida

### Sênior

- remuneração entre R$ 7.500,00 e R$ 8.500,00
- VR de R$ 35/dia
- plano de saúde Bradesco
- seguro de vida

**Diferenciais:**
- horário flexível
- mentoria e plano de carreira
- mais de 1000 horas de conteúdo disponíveis na UniVisagio, nossa universidade corporativa
- trabalho remoto, mas a empresa tem bases em RJ e SP

## Contratação

Estágio
CLT (júnior/pleno/sênior)

## Como se candidatar

E aí, curtiu? Para se inscrever basta acessar o site https://virtual360.io/carreiras/, acessar a vaga em que melhor se enquadra e nos enviar o seu currículo através do botão de candidatura ao final da página! ;)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Estágio
- CLT

#### Nível
- Estagiário
- Júnior
- Pleno
- Sênior

**Comment by AlexDoug33** [comment]
Bom dia, me chamo Alex estou buscando oportunidade como desenvolvedor estagio/júnior.

**Comment by marcello-telles** [comment]
Olá, Alex! Tudo bem? Obrigado pelo interesse!

Basta se inscrever na vaga correspondente no nosso [site](https://virtual360.io/carreiras/) que faremos a triagem por lá!

**Comment by marcello-telles** [comment]
> Bom dia, me chamo Alex estou buscando oportunidade como desenvolvedor estagio/júnior.

Olá, @AlexDoug33! Tudo bem? Obrigado pelo interesse!

Basta se inscrever na vaga correspondente no nosso [site](https://virtual360.io/carreiras/) que faremos a triagem por lá!

**Comment by r4iser** [comment]
Valorização de estagiários, bons pagamentos e requisitos justos. Uma lindeza.

**Comment by leandroribeiro** [comment]
Opa não vou me candidatar para vaga, mas só vim aqui deixar meu elogio pela clareza de informações ao divulgador!

**Comment by marcello-telles** [comment]
obrigado pelos feedbacks, @r4iser e @leandroribeiro! 😄

**Comment by Guilheeeerme** [comment]
Boa tarde,  vou me candidatar para a oportunidade desenvolvedor junior,  só estou aguardando a facul me enviar meu histórico.

**Comment by cauachagas** [comment]
Mais clareza nas informações das vagas ainda não vi. Sem contar que a empresa deixa claro que não faz leilão de salários, pagando um valor que respeita até estagiários. Muitas vagas de Júnior não pagam esse valor desta vaga de Estagiário.

**Comment by marcello-telles** [comment]
As vagas permanecem abertas por tempo indefinido! ;)

**Comment by abelsouzacosta** [comment]
Realmente, é uma descrição de vaga bastante clara. Além de ser uma ótima oportunidade

**Comment by alisonmateus** [comment]
Eu queria tentar está vaga de estágio, entretanto eu estudo por conta própria, será que consigo me candidatar?

**Comment by marcello-telles** [comment]
> Eu queria tentar está vaga de estágio, entretanto eu estudo por conta própria, será que consigo me candidatar?

fala, @alisonmateus! Tudo bem?

Para a vaga de estágio é necessário estar cursando alguma graduação, infelizmente... não por limitação da V360, mas por questões legais. Para CLT não exigimos graduação, mas como é a partir do nível júnior, é importante que você demonstre aptidão com programação e/ou Rails especificamente, como através de projetos voluntários, pessoais ou profissionais!

**Comment by teuspersi** [comment]
> Para a vaga de estágio é necessário estar cursando alguma graduação, infelizmente... não por limitação da V360, mas por questões legais. Para CLT não exigimos graduação, mas como é a partir do nível júnior, é importante que você demonstre aptidão com programação e/ou Rails especificamente, como através de projetos voluntários, pessoais ou profissionais!

Opa, @marcello-telles. Beleza? Sei que já falou que é necessário estar cursando graduação, mas quem faz cursos técnicos em institutos federais na área de tecnologia também podem ter uma chance? Já que o estágio supervisionado também é um componente curricular nesses cursos.

**Comment by marcello-telles** [comment]
Vaga permanece aberta indefinidamente!

https://somosv360.gupy.io/
