### ISSUE TITLE
[São Paulo) Senior Back-End Developer (Ali Crédito)

### ISSUE THREAD

**Issue by Paulogrupe** [backend-br/vagas#513]
Construir do zero todas as APIs, micro-serviços e serviços de integração entre sistemas que darão sustentação a todo o nosso parque de TI. Serão desafios de todos os tipos: arquitetura, performance, segurança, usabilidade, etc. 

Local - Escritório em São Paulo - Jd. Paulistano

Benefícios:
Vale Transporte ou Estacionamento; 
Vale refeição de R$ 24,50/dia útil;
Aparelho celular e linha telefônica corporativa
Laptop

Requisitos:
Sólida experiência com o desenvolvimento de APIs RESTFul utilizando as tecnologias Python e Flask;
Sólidos conhecimentos com o desenvolvimento de plataformas que se conectem com bancos de dados MySQL e MongoDB;
Construção de micro-serviços com utilização de serviços de mensageria;
Familiaridade com construção de plataformas seguras com utilização de protocolos HTTPs, tokens, etc.

Requisitos desejáveis:
 Familiaridade com utilização de Docker para ambientes de desenvolvimento e produção;
 Conhecimentos na gestão de ambientes em Amazon AWS;

Forma de contratação: CLT

Nossa empresa:
Ali Crédito foi criada para fazer que o cliente aproveite o crédito da melhor maneira: realizar um sonho ou quitar dívidas do passado, com o menor custo possível, sempre em linha com o momento da vida do cliente.

Labels:
Alocado
CLT
Senior

Como se candidatar:

Por favor envie um e-mail pg@individuals.io, com seu curriculum anexado - enviar no assunto: Vaga Back-end

**Comment by ghost** [comment]
Pode ser remoto?

**Comment by Paulogrupe** [comment]
Bom dia


Estamos dando preferência para locado, mas mesmo assim gostaria de analisar seu currriculum.


Grato


Paulo Grupe


________________________________
De: Antonio Cleverson dos Santos <notifications@github.com>
Enviado: quarta-feira, 3 de outubro de 2018 19:27
Para: backend-br/vagas
Cc: Paulogrupe; Author
Assunto: Re: [backend-br/vagas] [São Paulo) Senior Back-End Developer (Ali Crédito) (#513)


Pode ser remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
