### ISSUE TITLE
[Londrina-PR ou Remoto] Desenvolvedor(a) Back-end @ Lapaza

### ISSUE THREAD

**Issue by danielsanfr** [backend-br/vagas#5135]
## Lapaza Empreendimentos LTDA

Empresa responsável pelo desenvolvimento e manutenção do Sistema Integrado de Estacionamento Rotativo [Vago!](https://www.vagoonline.com.br), atuamos em várias cidades do sul e sudeste do Brasil. Contamos com sistemas web tanto para administração quanto para o uso dos usuários finais. Temos aplicativos Android e iOS desenvolvidos de forma nativa. E também temos parquímetros desenvolvidos com sistemas embarcados.

## Descrição da vaga

Será o responsável pelo desenvolvimento contínuo do back-end do nosso sistema, incluindo novas features, adaptações e correções de bugs.

## Local

Remoto ou Escritório (Fábrica) Londrina - Centro.

## Requisitos

**Obrigatórios:**

- 1+ anos de experiência com Node.js (express) ou Django;
- 1+ anos de experiência com MongoDB ou PostgreSQL;

**Desejáveis:**

- Experiência com testes;
- Javascript/Typescript;
- MyPy;
- Git (Git-flow);
- Bootstrap;
- JQuery;

**Diferenciais:**

- Boa experiência em manutenção de servidores Linux e utilizando containers Docker em ambiente AWS;
- Experiência com a AWS - Amazon Web Services (route53, elastic beanstalk, RDS, Elastic Cache, ECR, EC2);
- Conhecimento intermediário/avançado de docker e docker-compose;
- Conhecimento intermediário/avançado de Linux (server side);
- Experiência com shell script.

## Benefícios

- Plano de saúde;
- Vale refeição;

## Contratação

CLT ou PJ a combinar;

## Como se candidatar

Envie um e-mail para danielsan@vago.online com o título Vaga para Desenvolvedor Backend. Coloque links para Github e ou LinkedIn e também anexe seu currículo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: antonio@vago.online

#### Alocação

- Remoto

#### Regime

- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by danielsanfr** [comment]
Olá pessoal, gostaria de saber se alguém tem alguma sugestão de como tornar esse anuncio mais relevante?
Digo isso pois recebemos menos de 5 e-mails, nem pessoas júnior entraram em contato. Será que foi por causa dos 2+ anos de experiência?

**Comment by thaylorcs** [comment]
Daniel, acredito que seja muito provável que sim. Pelo que tenho observado aqui boa parte dos dev's são júnior

**Comment by danielsanfr** [comment]
Valeu pela resposta @thaylorcs . Se eu editar a issue vocês recebem alguma notificação (tipo num Slack) ou teria que fechar essa e criar outra?

**Comment by thaylorcs** [comment]
Isso eu não sei dizer, mas eu acabei de receber a notificação da sua última interação por email. Acredito que todos receberam também o seu questionamento.

**Comment by danielsanfr** [comment]
Ainda esta aberta.
