### ISSUE TITLE
[REMOTO] C++ Developer @ Simbiose Ventures

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#5139]
Olá,

Estamos buscando desenvolvedores C++ pleno e sênior, full-time (8 horas) e part-time (6 horas).

# Sobre a Simbiose
https://docs.simbioseventures.com/#/public/about

# Perfil das pessoas que buscamos
- Objetivo de vida relacionado a ajudar/desenvolver/evoluir pessoas.

- Alta predisposição à riscos.

- Alto desejo de evoluir comportamentalmente (já faz terapia ou tem predisposição a fazer).

- Alta flexibilidade (baixa resistência).

- Controle emocional (pensa mais racionalmente do que emocionalmente).

- Alto nível de organização (já usa agenda, anota e organiza seus gastos, etc).

- Alta predisposição em pedir ajuda para outras pessoas.

- A maioria dos membros da família e amigos apoiando fortemente o objetivo de vida da pessoa.

- Inglês fluente ou avançado (para leitura e escrita).

# Expectativas para o profissional de C/C++

- Conhecimento avançado em C/C++

- Conhecimento avançado em algoritmos

# Remuneração

Entre R$ 6.000,00 e R$ 18.000,00 dependendo do nível técnico e comportamental do profissional.

# Candidatura

Caso tenha interesse, por favor, pedimos gentilmente que você olhe o material acima e envie seu currículo e pretensão salarial no email abaixo.

fazerparte@simbioseventures.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by CarlosHenriqueRC** [comment]
Minha nossa senhora, é sério isto ?

-

*Alto desejo de evoluir comportamentalmente (já faz terapia ou tem
predisposição a fazer).*
-

*Alta flexibilidade (baixa resistência).*
-
*...*
- * A maioria dos membros da família e amigos apoiando fortemente o
objetivo de vida da pessoa. *


******************************************
*Carlos Henrique Ramos Carvalho
*Especialista em Tecnologia .Net
*MCP.Net
******************************************


Em ter., 27 de abr. de 2021 às 16:40, Gabriel Menegatti <
***@***.***> escreveu:
