### ISSUE TITLE
[São Paulo] Full Stack Node.js na [FCAMARA]

### ISSUE THREAD

**Issue by recarol13** [backend-br/vagas#516]
![LogoFcamara](http://blog.fcamara.com.br/wp-content/uploads/2016/02/Logotipo-Horizontal-FCamara-2015-e1455123821994.png)

## Descrição da vaga

Para você que gosta de desafios, estou buscando Desenvolvedor Node.js para atuar em um cliente focado em transformação digital na região da Avenida Paulista e Barra Funda.

## Local

Região da Avenida Paulista e Barra Funda.

## Requisitos
- NodeJs (ExpressJS)
- Ionic 2+	
- MongoDB
- React
- Experiência em AWS

## Desejáveis:
- Elastic Search

## Contratação
- PJ a combinar

## Nossa empresa
A FCamara Formação e Consultoria iniciou suas atividades em 2008 com o objetivo de servir com excelência as demandas de verificação de desempenho de aplicações e organização de times de desenvolvimento. Hoje, somos referência em transformação digital através de um método próprio, o High Performance Team, que ajuda empresas a desenvolver projetos e ideias de negócio de forma mais eficiente. Inovação, tecnologia e empreendedorismo fazem parte de quem somos. Queremos ser uma empresa útil e funcional. Útil porque possuímos serviços e produtos necessários. Funcional porque nossos serviços e produtos realmente solucionam e representam valor agregado ao Cliente.

Venha fazer parte do #SangueLaranja. Seja um de nossos clientes ou consultores. Aqui suas ideias tem valor!

## Como se candidatar
Interessados ou indicações, enviar CV para heloisa.moraes@fcamara.com.br

## Labels

- Alocado
- PJ
- Senior
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
