### ISSUE TITLE
[SÃO PAULO] Back-end PHP Developer JR

### ISSUE THREAD

**Issue by crispossa** [backend-br/vagas#518]
### Descrição da vaga
Você vai atuar na correção de bugs em sistemas que estão em produção e desenvolvimento de novas features de complexidade média. Você vai encontrar desafios que exigem soluções "fora da caixa" para entregar a melhor solução com alta qualidade e com alto nível de manutenção do código. Bom raciocínio lógico e rápida reação a imprevistos são essenciais.

Você vai ter a oportunidade de aprimorar seus conhecimentos e aprender coisas novas todos os dias. Entre suas funções são destaque:

- Desenvolver novos recursos em sistemas já em produção.
- Correção de bugs.
- Análise de código para evitar futuros bugs.
- Escrever testes de sistema para softwares legados.
- Participar da concepção de novos projetos do zero e auxiliar no desenvolvimento de recursos.
- Encontrar soluções criativas e simples para problemas complexos.

### Requisitos

- 1 ano de experiência comprovada com PHP
- Experiência com algum framework conhecido (Laravel/Symphony/CodeIgniter, etc...)
- Bom raciocínio lógico
- Experiência com GIT
- Conhecimentos em APIs REST
- Conseguir usar o Google/StackOverflow para encontrar soluções para problemas simples por conta própria

### Desejáveis

- Conhecimento em Python/Ruby On Rails
- Experiência com banco de dados MySQL/PostgreSQL
- Experiência com banco de dados não relacional

### Contratação
PJ a combinar

### Sobre a WeJam

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.
Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.
Desenvolvemos sistemas únicos e realmente desafiantes, além de campanhas publicitárias inteiras que impactam clientes finais em diversas mídias.
Venha fazer parte da nossa equipe!
We Ad! We Rock! We Jam!

### Localização

Rua Raposo Tavares, 116 - Jardim das Acácias - São Paulo

### Como se candidatar

Envie para o e-mail queroserdev@wejam.email as seguintes informações:

- Seu CV.
- Link do Github se tiver.
- Uma breve descritivo dos últimos projetos que vc participou e qual a sua participação.
- Os desafios que vc encontrou recentemente e como os resolveu.
- Sua pretensão salarial.

**Comment by hilderjares** [comment]
aceita home office ?

Em sex, 5 de out de 2018 às 15:20, Cristiano Possa <notifications@github.com>
escreveu:

**Comment by allanzi** [comment]
Enviado :+1:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
