### ISSUE TITLE
[Portugal] Java Developer na Aubay 

### ISSUE THREAD

**Issue by monicantunes** [backend-br/vagas#519]
Descrição da vaga
Projetos em vários setores de atividade, usando diversas tecnologias de Java entre outras.

Local
Portugal: Lisboa e Porto

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário
• Almoço grátis todas as sexta-feiras

Requisitos
Obrigatórios:
• Experiência em funções de desenvolvimento de projetos na área de Java;
• Domínio da língua Inglesa (conversação e escrita).

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Envie o seu CV para mantunessilvestre@aubay.com com o assunto Aubay: JAVA.

**Comment by MrS4w** [comment]
Qual o nível de experiência com Java?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
