### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby na Jüssi - The Business Agency

### ISSUE THREAD

**Issue by gabrielhsp** [backend-br/vagas#52]
Pessoal, estou repassando uma vaga que recebi por e-mail aqui da empresa em que trabalho. Segue as informações abaixo e o link pra se inscrever na vaga no final. Infelizmente não me passaram os benefícios e valores da remuneração. Coloquei os benefícios baseados no que eu e a maioria da galrea tem, mas vou ver se consigo levantar e qualquer coisa dou um update aqui na issue :)

# Descrição
Estamos buscando desenvolvedores back-end para fazer parte do time de desenvolvimento 
da Jussi e trabalhar nos novos projetos que foram fechados recentemente na Agência.

## Local de trabalho
Rua Bandeira Paulista, 530 - Itaim Bibi, São Paulo - SP

## Requisitos
- Experiência com desenvolvimento de software (ao menos com 1 linguagem web);
- Experiência com desenvolvimento Ruby on Rails (Rails 3, 4);
- Conhecimentos sólidos de Orientação à Objetos;
- Conhecimento de Elasticsearch
- Prezar por Clean Code e não ser acostumado a "janelas quebradas"
- Aplicação dos conceitos SOLID e DDD
- Ter conhecimento do REST API (consumo e desenvolvimento)
- Ter conhecimentos de alguma plataforma Unix (Linux ou Mac)
- Saber lidar com comandos SHELL
- Saber trabalhar com GIT é essencial

## Diferenciais
- Testes automatizados são um diferencial
- Desejável conhecimento de Sidekiq
- Desejável conhecimento de Redis
- Um diferencial é ter conhecimentos de HTML, CSS e JS (Coffeescript)
- Cultura de Code Review

## Benefícios
- Plano de Saúde (Sulamérica)
- Plano Odontológico
- Vale refeição ou alimentação de R$ 31,00/dia
- Vale transporte 

## Como se candidatar
Através do seguinte link: https://www.vagas.com.br/vagas/v1638280/desenvolvedor-ruby-on-rails

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
