### ISSUE TITLE
[São Paulo - SP] Desenvolvedor PHP [Replikante]

### ISSUE THREAD

**Issue by rodrigobmoura** [backend-br/vagas#522]
## Nossa empresa

Somos uma companhia em franco crescimento que provê soluções e serviços utilizando inteligência artificial para replicar e automatizar as interações humanas.

## Descrição da vaga

Estamos em busca de um desenvolvedor PHP Pleno ou Senior para trabalhar no desenvolvimento de parte do back-end de uma de nossas plataformas.

A vaga é somente para candidatos que residam na cidade de São Paulo.
	
**Diferenciais:**

Provemos um ambiente estimulante, com as seguintes características:

•	Hierarquia mínima

•	Horários flexíveis

•	Opção de fazer home office

## Requisitos

**Obrigatórios:**

•	 PHP

**Desejáveis:**

Laravel
HTML
CSS

## Local

São Paulo - SP  (CENU - Berrini) - Zona Sul

## Contratação

Salário:

•	A combinar.

Tipo de contratação:

•	CLT ou PJ.

## Como se candidatar

Os interessados devem enviar seu currículo, LinkedIn e GitHub, mais pretensão salarial, para o e-mail: tecnico@replikante.com.br. 

## Labels

- CLT
- PJ
- Alocado
- Remoto - Parcial
- Pleno
- Senior

**Comment by rodrigobmoura** [comment]
Conseguimos encontrar um desenvolvedor no perfil e preenchemos a vaga. Porém, devido a demanda de novos projetos, estamos abrindo duas novas vagas no mesmo perfil. 

Candidatos interessados por favor enviem seus currículos.

**Comment by llldc21** [comment]
Acabei de lhes enviar um currículo.

**Comment by rodrigobmoura** [comment]
Contratamos um novo desenvolvedor. Ainda resta (1) uma vaga. Estando dentro do perfil, a contratação é imediata. Por favor enviar currículo com pretensão salarial (somente candidatos de São Paulo SP).

**Comment by llldc21** [comment]
Segue anexo currículo.

Em Ter, 6 de nov de 2018 10:07, Rodrigo Moura <notifications@github.com
escreveu:

**Comment by lucasperrotta** [comment]
Há vaga restante?

**Comment by rodrigobmoura** [comment]
@lucasperrotta sim, pode enviar seu currículo para rmoura@replikante.com.br. Abs!
