### ISSUE TITLE
[Ribeirão Preto] Desenvolvedor Genexus @ Nestlé

### ISSUE THREAD

**Issue by estevamfab** [backend-br/vagas#5226]
> Vaga em caráter definitivo de Teletrabalho (work from home)

## Nossa empresa

Nestlé (Centro de serviços compartilhados)

## Descrição da vaga

Desenvolvedor GeneXus

## Local

Escritório fisico em Ribeirão Preto- SP, porém será uma vaga de teletrabalho

## Requisitos

**Obrigatórios:**
Experiência em projetos de softwares com a utilização da ferramenta case GENEXUS (Visual Basic, Java, .NET e PHP e SGBD padrão relacional SQL.
Experiência em serviços especializados de manutenção de sistemas de informação.
Ferramenta GENEXUS.

**Desejáveis:**
- Conhecimentos em PowerBI (PowerQuery, DAX, M)
- Conhecimento da ferramenta case GENEXUS (Visual Basic, Java, .NET e PHP).

**Diferenciais:**
- Conhecimentos PowerApps

## Benefícios

- Plano de saúde
- Plano odontológico
- Participação nos Lucros
- Seguro de vida
- VR
- VA
- Previdencia Privada
- Cooperativa de Crédito
- Ajuda medicamentos
- etc.

**Diferenciais:**
- Trabalho remoto
- 100% equipamentos fornecidos pela companhia (Notebook, headphones + auxilio financeiro)

## Como se candidatar

Por favor envie um email para estevam.souza@br.nestle.com com seu CV anexado - enviar no assunto: Vaga Genexus

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by FabioAlmeidaTI** [comment]
https://docs.google.com/document/d/1UYYC47vCJ2AKIQZ3T2AGiOtev5BKAXFhdaogzOPyAMk/edit

Em qua., 5 de mai. de 2021 às 12:30, estevamfab ***@***.***>
escreveu:
