### ISSUE TITLE
[Ribeirão Preto - SP] - Engenheiro de Dados Jr - ETL - BEBLUE

### ISSUE THREAD

**Issue by TatianeBeblue** [backend-br/vagas#523]
**Engenheiro de Dados Junior**

**O que você vai fazer:**
• Ajudar a equipe da Data Science a desenvolver produtos surpreendentes e desafiadores que levam a empresa aos seus objetivos;
• Implementar e manter os pipelines de ETL;
• Construir a infraestrutura necessária para testar e implantar ETLs e modelos de aprendizado de máquina usando o AWS;
• Identificar, projetar e implementar melhorias de processos internos: automatizar processos manuais, otimizar a entrega de dados, reprojetar a infraestrutura para maior escalabilidade, etc.

**Experiências e habilidades exigidas:**
• Experiência com Python;
• Experiência com SQL, além de trabalhar com bancos de dados relacionais;
• Experiência com algum banco de dados NoSQL, como o Amazon Redshift;
• Forte capacidade de organização;
• Atitude proativa e do jogador em equipe.

**Seria um plus as seguintes experiências e habilidades:**
• Linguagem de programação Scala;
• Spark, Kafka, Hadoop, etc;
• Ferramentas de gerenciamento de fluxo de trabalho: Airflow, Luigi, etc;
• Serviços em nuvem da AWS: EC2, SQS, EMR, RDS, Redshift, Data Pipeline;
• Sistemas de processamento de fluxo: Storm, Spark-Streaming, etc;
• Conhecimento prático de processamento de fluxo.

**Interessados,** encaminhar CV para: tatiane.lima@beblue.com.br - mencionar no assunto o título da vaga.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
