### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android no Ubook

### ISSUE THREAD

**Issue by fmontella** [backend-br/vagas#529]
O Ubook está a procura de um desenvolvedor Android que tenha vontade de fazer parte de uma empresa que está mudando o mundo com suas novas tecnologias. Esta oportunidade é para aqueles que possuem experiência no desenvolvimentos de aplicativos mobile para Android. 

<br>

**Abaixo estão algumas características que serão necessárias:** 

- Conhecimento pleno da plataforma Android e suas APIs

- Conhecimento pleno da linguagem Java

- Conhecimento pleno da IDE AndroidStudio

- Conhecimento sobre SQLite e JSON

- Conhecimento sobre Git

- Elaborar código limpo e com estrutura legível ( Clean Code )

<br>

**Será um diferencial quem também tiver estes conhecimentos:**

- Otimização de recursos em ambientes embarcados

- Estar atualizado com as tendências e novidades da plataforma para sugestão de melhorias

- Conhecer a linguagem PHP (para depurar problemas na integração caso necessário)

- Conhecer testes unitários

- Conhecer o banco MySQL para validar registros enviados do aplicativo para o backend

<br>

O Profissional precisa ser pontual, pró-ativo e saber trabalhar em equipe.

Atenção: A vaga é para trabalhar no Rio de Janeiro - Barra da Tijuca.

Interessados devem enviar o currículo para vagas.ti@ubook.com até o dia 30/11/2018.

Imprescindível mencionar no assunto o nome da vaga : Vaga Desenvolvedor Android

Equipe Ubook

**Comment by Kirmayrtomaz** [comment]
o foco dessa vaga é de mobile, 
melhor procurar o pessoal do gdg, que devem dar um suporte melhor pra essa vaga.
