### ISSUE TITLE
[Belo Horizonte - MG] Back-end Developer PL/SR (San Pedro Valley)

### ISSUE THREAD

**Issue by andre0799** [backend-br/vagas#53]
Empresa: ROBOS.im
Bairro: Savassi
Descrição:
ROBOS.im is San Pedro Valley based company with amazing investors whom is fastly becoming the most well known platform/solution for chatbots. And we need your skills, experience and passion for tech to take this a step further!

We are looking for a software developer with strong knowledge in back-end development and machine learning solutions.

What will you do?

- Work everyday to improve our amazing chatbot engine; 
- Dive deep in our microservices based architecture and solve complex problems;
- Have fun and make friends at the office.

What you will get?

 - Contract based (PJ). Less bureaucracy and more freedom for you with a fair compensation for you contributions; 

- FULLY flexible work hours & once a week home office;

- Work with a product that has complex and challenging  architecture based on Microservices. As the product learns and grown so will you;

- Work with SCRUM on a truly Agile environment;

- We take learning very serious, so... Udemy account with ANY course available at company expense;

- Opportunity to grow fast. ROBOS.im is working to implement a equity strategy for our first employees in the near future;

- Generation Y friendly environment (Total respect for your decisions, experiment and individuality. Informal dress code, constant feedback, learning as a priority, SUPER cool office and SUPER cool partys, all you can eat snacks);

- BYOD. If you do not like to carry you lap top around we offer a Starter Pack (Laptop with a i5 and 8G DDR3 running Ubuntu)

- Opportunity to shape the company's culture.

- Give it back to the community: ROBOS.im works towards making 70% of it's technologies open source
Requisitos:
We are looking for a developer passionate about tech and who has an eager to be part of something revolutionary. In order to be considered for this position you also must present:

- Ownership;
- Clean code and detail oriented documentation. We value quality;
- Degree (2y-5y courses) at the I.T field or proven equivalent experience;
- Minimum of 2 years of proven experience as a Back-end Developer;
- Demonstrated skill with Javascript, Microservices, MongoDB/PostgreSQL, Node.js e REST
- Advanced english skills is a must; 
- Knowledge of SaaS, Machine Learning, Natural Language Processing e Bots are a plus;
- Experience with SCRUM or other Agile methodologies is also a plus;
- If you know your way around the client-side of the force that is a huge bonus!

If you love new challenges, have passion about tech and has an eager to be part of something revolutionary, join our way of working, join us! We are ROBOS.im!
Tipo de Contrato: Prestador de Serviços (PJ)
Salário: de R$4000,00 a R$9000,00
Benefícios:
- Check out the description. :)

**Para se candidatar:** [https://www.recrutasimples.com.br/vaga/-L3GNwcMFi3I6EZKG1IZ?referrer=githutbackend](https://www.recrutasimples.com.br/vaga/-L3GNwcMFi3I6EZKG1IZ?referrer=githutbackend)

**Comment by thiagoluiznunes** [comment]
Nice job.

**Comment by andre0799** [comment]
Atualizamos o salário! ;)

**Comment by kivervinicius** [comment]
@andre0799  ainda não sou fluente em inglês, posso aplicar mesmo assim?

**Comment by andre0799** [comment]
Se conseguir entender o texto da vaga sem a ajuda de um tradutor acho que não problema @kivervinicius ;)
