### ISSUE TITLE
[Belo Horizonte] Estágio em Desenvolvimento back-end Java na Lett

### ISSUE THREAD

**Issue by vitorandrade-lett** [backend-br/vagas#531]
https://jobs.lett.digital/o/estagio-java

## Perfil que buscamos:
Quer se sentir como um hacker? Venha pra Lett ! ;D

Estamos em busca de alguém que se interesse pela arte de extrair informações da web e se interesse por engenharia reversa. Afinal seu objetivo será capturar dados de lugares onde existem barreiras para evitar a captura, sendo assim surgirão desafios dia a dia!

Assim como todos que trabalham no nosso time, buscamos alguém colaborativo, que goste de trabalhar em equipe e tenha foco em resultados.

Talento e conhecimento não são as únicas qualidades necessárias para embarcar nessa jornada. Se você se considera disposto a aprender novas habilidades e é pró-ativo, essa vaga é para você!

## Principais tarefas e responsabilidades
Você estará em contato direto com a área de captura de dados, participando do desenvolvimento de web scrapers, estando sempre ao lado de desenvolvedores da área que estarão dispostos a te ajudar e também com a equipe de suporte ao cliente que trará demandas relacionadas ao negócio.

## Na Lett você aprenderá sobre:
- Desenvolvimento de Web Scrapers
- Políticas de segurança
- Proxies e anonimização
- VPN
- Bypass de sistemas de proteção
- Algoritmos de otimização de captura
- Bancos SQL
- Bancos NoSQL
- Monitoramento de processos
- Atuar em automatização de tarefas
- Java

## Detalhes
- 30 horas semanais
- Bolsa de R$1.000,00
- VT de R$200,00

### Obrigatórios
- Curso superior em andamento em Ciência da Computação, Sistemas da Informação ou áreas relacionadas.
- Conhecimento em programação orientada a objetos
- Interesse em aprender

### Diferenciais
- Conhecimento do protocolo HTTP e de como a web funciona
- Java
- SQL
- NO-SQL
- Linux
- Conhecimento em técnicas de web scraping
- Inglês (técnico)

## Inscrição:
Inscreva-se pelo site https://jobs.lett.digital/o/estagio-java.

**Comment by tyronedamasceno** [comment]
Esse estágio pode ser remoto?

**Comment by X-X-Xavito** [comment]
Vaga ainda em aberto?

**Comment by vitorandrade-lett** [comment]
A vaga já foi preenchida, Kaique!
