### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Java Web na TTY2000

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#536]
### Sobre a empresa: TTY 2000

A TTY foi fundada em 1996, em Belo Horizonte (MG), motivada por solucionar todas as questões que envolviam o “Bug do Milênio”. Com o sucesso da entrega desse primeiro grande desafio, a empresa buscou alianças, se especializou e, a partir de então conquistou cada vez mais espaço no mercado de TI. 

A qualificação de sua equipe técnica e as certificações conquistadas ao longo do caminho fizeram a TTY ampliar sua visão de mercado e crescer, sem deixar de focar suas ações no que mais importa em uma organização: os resultados. Hoje é isso que faz da TTY uma empresa diferenciada no segmento de TI: o fato de os seus gestores e colaboradores serem comprometidos com os resultados de seus clientes. Afinal, somos uma empresa especializada em prover sempre as melhores soluções.

### Descrição: Ocupações do cargo

Desenvolver softwares sob medida
Programar, codificar e testar projetos criados
Manutenções em sistemas e apps já existentes

### Benefícios

Vale Refeição
Vale Transporte
Plano de Saúde (UNIMED – Unipart Flex Nacional Empresarial Apartamento, empresa paga 50%)

### Aptidões e qualidades

Trabalho em equipe
Pronto para desafios

### Conhecimentos sólidos:

Java Enterprise
Padrões EE, EJB, JPA, JSF
Angular4
Hibernate
Spring
Rest
Experiência com servidores javaee, como JBoss e Tomcat. 

### Informações complementares

A TTY 2000 é uma empresa de TI com 22 anos de mercado. Certificada MPS.BR nível C e parceira GOLG da Microsoft o nosso negócio propõem soluções adequadas em Tecnologia da Informação. Nossa missão é propor soluções adequadas às necessidades do Cliente, através de profissionais qualificados que nos tornam uma empresa próspera e reconhecida por seus Clientes, Parceiros e Colaboradores como uma excelente opção de relacionamento.

### Labels

Pleno/Senior
CLT
Alocado

### Candidatar: http://bit.ly/tty2000_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
