### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Full Stack na One Beleza

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#539]
### Sobre a empresa: One Beleza

A MMtools, proprietária do software de gestão “One.beleza & bem-estar”, está no mercado há mais de 20 anos e lançou esse novo sistema em Fev/2015. Essa solução é 100% nuvem e já portamos todos os nossos clientes do ambiente cliente-servidor.

### Descrição: Ocupações do cargo

Daremos início, muito em breve, ao desenvolvimento da versão 2.0 de nosso sistema de gestão “One.beleza & bem-estar”. Esse analista estará trabalhando diretamente com o nosso analista sênior para, após conhecer toda a regra de negócios, dar início ao novo projeto.

O grande desafio desse novo projeto é criar uma solução simples, rápida e inovadora. Além disso, as mais atuais técnicas de desenvolvimento serão adotadas, como Micro-serviços e Contêineres.

### Conhecimentos em Frontend:

Angular 2 ou superior (React é um diferencial)
Domínio sob padrões e gerenciamento de códigos Frontend (Bower, Gulp, Npm)
Domínio sob HTML, CSS e JavaScript

### Conhecimentos em Backend:

.Net Core
ASP.Net MVC
SQL Server
C#

### Diferenciais:

Experiência em arquitetura de Microserviços
Experiência no ambiente Azure

### Benefícios

Caso a contração seja como CLT, o profissional terá os seguintes benefícios:

Vale-transporte
Auxílio-alimentação: R$22,50/dia
Plano de saúde Unimed

Caso for contratação PJ, os benefícios serão incorporados na remuneração.

### Aptidões e qualidades

Nossa empresa administra e cuida das informações administrativas, financeiras e fiscais de centenas de clientes. Além disso, milhares de profissionais e dezenas de milhares de clientes finais consomem e dependem dessas informações. A cada dia que passa, a nossa responsabilidade tem aumentado com a entrada de novos clientes.

Portanto, o ocupante desse cargo deve, antes de qualquer coisa, ter consciência do nível de responsabilidade a que estará submetido.

Isso o obriga a, por mais simples que sejam as tarefas, testá-las e validá-las localmente antes de sua execução ou implementação.

Outra qualidade está relacionada à capacidade de resolução de problemas, onde uma tarefa é dada e o responsável deve saber fazer o projeto, análise e o desenvolvimento de toda a solução. Logicamente, dentro dos padrões de desenvolvimento exigidos.

Resumindo: a nossa empresa dá total liberdade ao analista para ele, após ser submetido a uma tarefa, entregar a solução pronta e validada.

### Labels

CLT
PJ
Pleno

### Candidatar: http://bit.ly/onebeleza_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
