### ISSUE TITLE
[Florianópolis] Desenvolvedor Delphi na [Visto Sistemas] 

### ISSUE THREAD

**Issue by peopleti** [backend-br/vagas#54]
# Atividades: 
Desenvolvimento e manutenção de sistemas em Delphi e PL/SQL. Levantar requisitos, estudar regra de negócios, mapear processos e realizar modelagem de dados. Apoiar tecnicamente a implantação de novos sistemas e processos. Desenvolvimento de relatórios e processos específicos.

# Buscamos pessoas com:
Boa experiência em linguagem de programação: Delphi, SQL, PL-SQL. Conceitos de controladores de versão de software. [SVN] Experiência em levantar requisitos, estudar regra de negócios, mapear processos e realizar modelagem de dados. Facilidade em trabalhar em grupo. Experiência com banco de dados SQL Server. Comunicação, Compromisso com Resultado, Orientação por metas e proatividade.

### Descritivo completo no site da consultoria: 
[PeopleTI](http://peopleti.com.br/job/11417/)

Nível Pleno
Linguagem Delphi
Localização em Florianópolis, **sem** possibilidade de Home Office.

**Comment by reginaldojunior** [comment]
Ainda tem vagas?

**Comment by peopleti** [comment]
Olá, Reginaldo.

 

Sim, o processo segue em aberto.
Atenciosamente.

 



 

 

 

De: Reginaldo Junior <notifications@github.com> 
Enviada em: segunda-feira, 16 de abril de 2018 15:16
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: PeopleTI <peopleti@peopleti.com.br>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [Florianópolis] Desenvolvedor Delphi na [Visto Sistemas] (#54)

 

Ainda tem vagas?
