### ISSUE TITLE
[São Paulo/SP - Vila Olimpia] Sr Backend Developer - Yellow 

### ISSUE THREAD

**Issue by AnaYellow** [backend-br/vagas#543]
**Backend Developer**

**About your job:**
_Our backend is the heart and the brain of Yellow. It’s responsible for tracking our bicycles, managing the ongoing and finished trips, executing payment transactions, planing our operations team’s activities, organizing and solving users problems, etc.
The systems are required to be fast, reliable and to support millions of bikes and users._

**Here you are going to be responsible for:**
- Develop and maintain our backend services
- Understand and foresee our system requirements
- Work closely with mobile developers to design service interfaces and improvements
- Guarantee high performance and high availability of all systems
- Build and maintain services to support our operational teams

**Double click in your routine:**
- Develop new features and fix bugs in our java-based code
- Work side-by-side with product team to design requirements
- Keep our source organized in our git repository
- Collaborate in building and enforcing the roadmap
- Manage and prioritize your tasks efficiently
- Collaborate with architecture and code design decisions

**Our requirements for this position are:**
- 4+ years experience in backend development
- Advanced Object Oriented skills
- Advanced Cloud Computing skills
- Dominance of RESTful concepts
- Hands on experience with development best practices (testing, code-review, etc)
- Strong sense of commitment and delivery focus

**AWS Cloud based development:**
- Beanstalk
- DynamoDB
- SQS
- SNS
- Route53
- ElasticSearch

**Perks**
- Startup environment
- Flexible working hours
- Work in a startup pre-launch phase
- Our Current Stack

**Apply To Position: https://yellow.breezy.hr/p/d2903446df9b-backend-developer**

**Comment by AnaYellow** [comment]
[https://yellow.breezy.hr/](url)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
