### ISSUE TITLE
[Vila Olímpia - São Paulo] Desenvolvedor Backend na [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#544]
Requisitos:
Experiência no Desenvolvimento de novas aplicações e manutenção de códigos utilizando NodeJS, MongoDB e AngularJS.  

Local de trabalho: Vila Olímpia - São Paulo - SP
Contratação CLT Full
Benefícios: VR 440,00, AM e AO Care Plus 100% e Individual, VT ou reembolso de despesas até 250,00 e Seguro de Vida (nenhum dos benefícios tem desconto em folha do profissional).
e-mail: saopaulorht@roberthalf.com.br

**Comment by llldc21** [comment]
Aonde posso enviar meu curriculo?

**Comment by RaquelTavaresL** [comment]
Olá, boa tarde. Pode direcionar ao e-mail: raquel.lourenco@roberthalf.com.br

**Comment by llldc21** [comment]
Obrigado, acabei de lhe enviar.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
