### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Full Stack na LicenTIa

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#545]
### Sobre a empresa: Licentia

O LicenTIa quer promover o desenvolvimento sustentável, trazendo tecnologia para simplificar o licenciamento ambiental sem perder o rigor e seriedade, criando experiências melhores para empresas, órgãos públicos e comunidades. Somos uma startup que nasceu há um ano e meio na WayCarbon, uma empresa da área de sustentabilidade e mudanças do clima, oferecendo serviços de base tecnológica para nossos clientes há 12 anos.

### Descrição: Ocupações do cargo

A missão inicial é trabalhar no desenvolvimento de solução de software para ambiente WEB, desde a análise do problema até a entrega da solução. Você também deverá contribuir para o desenvolvimento de um produto inovador e da validação de protótipos no mercado (sim, ouvir, discutir e construir um produto fantástico!). Além disso, contribuir no desenho da arquitetura da primeira versão de um sistema de gestão ambiental com base nas funcionalidades já em operação da versão beta.

Em nível back-end você deverá executar e implementar todas as funcionalidades desenhadas, e em nível front-end selecionar e ajustar sistema ao melhor template disponível.

### Benefícios

Você será o segundo desenvolvedor contratado por nós. Entrar neste time agora, apostando junto conosco, pode te levar a fazer parte do início de uma história incrível, em um papel fundamental e de liderança. Queremos crescer juntos. Fora este mundo de possibilidades, oferecemos um ambiente de trabalho motivador e divertido, além do benefício de trabalhar com as pessoas mais legais de BH ;) Ah! e temos um horário flexível.

### Aptidões e qualidades

Dinâmico, pró-ativo e em busca de desafios;
Organização;
Excelente comunicação;
Facilidade de aprendizado;
Ter pensamento rápido;
Ser divertido e gente boa;

### Informações complementares

Trabalhamos para impactar a sociedade positivamente, pautados pela inovação, pela valorização das pessoas, pela ética e fazendo a coisa certa. Nós somos nós mesmos no trabalho e cultivamos o melhor clima onde quer que estivermos, com nossos colegas, clientes e parceiros. Ideias são mais importantes que aparências, e princípios mais importantes que origem.

### Labels

Pleno
CLT
Alocado

### Candidatar: http://bit.ly/licentia_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
