### ISSUE TITLE
[Remoto] Analista Programador na Sygecom Informática

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#546]
### Sobre a empresa: Sygecom Informática

É uma software house gaúcha, líder de mercado em fornecimento de sistema de gestão para empresas de reciclagem no Brasil inteiro. Há mais de 10 anos no mercado, agregando valor e automatizando o gerenciamento dessas empresas, criando soluções inovadoras e produtos que atendam as necessidades de nossos clientes, excedendo as expectativas.

### Descrição: Ocupações do cargo

Principais funções são a análise e desenvolvimento de customizações, melhorias e correções para funcionalidades de nosso produto (software ERP desenvolvido internamente), com bases nas demandas recebidas; Criar e analisar novas customizações; Criar modelagem de banco de dados; Realizar testes nas ferramentas desenvolvidas e disponibilizar manual explicativo sobre como funciona. 

O profissional deve possuir conhecimento em alguma das seguintes linguagens:

Xharbour;
Xbase;
ADVPL;
Php Procedural;
HwGui;
Fivewin;
Clipper;
Visual Fox Pro.

### Benefícios

Estamos sempre em busca de novas parcerias e benefícios para agregar valor a vida profissional e pessoal de nossos colaboradores e familiares.

Plano de saúde - Unimed Max (funcionários e dependentes até 18 anos);
Plano Odontológico - Uniodonto (funcionários e dependentes até 18 anos);
Vale-transporte;
Alimentação no local (café da manhã e almoço);
Convênio com Farmácia;
Auxílio Creche;
Plano de Carreiras;
Ajuda com a conta de luz (20%) e conta de internet (100%).

### Aptidões e qualidades

De aptidões e qualidades buscamos um profissional dedicado, responsável, com força de vontade, raciocínio lógico, comprometido, com boa concentração, disciplinado, paciente, persistente, que trabalhe bem em equipe, que goste de aprender constantemente e que goste de trabalhar muito e goste muito de trabalhar.

### Informações complementares

O profissional pode trabalhar remotamente ou trabalhar presencialmente de segunda a sexta-feira, das 08h30 as 18h00, com intervalo de 1h00.

### Labels

Remoto ou Presencial
CLT
Junior

### Candidatar: http://bit.ly/sygecomremoto_github

**Comment by lucasperrotta** [comment]
O link diz que a vaga não está mais disponível.

**Comment by megandavulpi** [comment]
> O link diz que a vaga não está mais disponível.

Realmente, @lucasperrotta ... a vaga está pausada no momento =/

Mas você pode conferir outras vagas remotas aqui: https://vulpi.com.br/vagas-para-desenvolvedores/?remote=true

Abraços!
