### ISSUE TITLE
[Barueri] Desenvolvedor Node.js na Capgemini

### ISSUE THREAD

**Issue by Leticiacoelho25** [backend-br/vagas#548]
Profissional para atuar em projeto de arquitetura com os seguintes conhecimentos:

Conhecimentos :
- Experiência com desenvolvimento de aplicativos Mobile Híbrido;
- Sólidos conhecimentos em Node.js
- Solídos conhecimentos em HTML5 e CSS3
- Solídos conhecimentos em Javascript
- Apache Cordova

Conhecimentos desejados
- Android;
- Apple iOS;
- AWS;
- Angular;
- Experiência Desenvolvimento Java
- Experiência em aplicações para instituições financeiras

Diferenciais
- IBM Watson
- Integração com mídias sociais

Local de Trabalho: Barueri -SP (oferecemos auxilio fretado)

Contratação CLT
Benefícios:
VR ou VA
Assistência Médica
Assistência Odontológica
Seguro de Vida
Auxilio Fretado
Previdência Privada
Universidade Corporativa 

Interessados ou indicações: leticia.coelho@capgemini.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
