### ISSUE TITLE
[São Paulo] Programador PHP na Cheftime

### ISSUE THREAD

**Issue by Cheftime** [backend-br/vagas#549]
### Programador PHP

**Descrição da vaga**
A Cheftime, startup de tecnologia que vende assinaturas de kits gastrômicos, está em busca de desenvolvedor PHP, para atuar presencialmente em sua sede em São Paulo. Os profissionais serão responsáveis pelo desenvolvimento e manutenção de APIs REST (webservices) desenvolvidas utilizando Lumen (Laravel). E, também, atuarão na modelagem dos dados, armazenamento de arquivos (storage), segurança e escalabilidade.

**Site**
http://www.cheftime.com.br

**Referências**

- https://www1.folha.uol.com.br/mercado/2016/08/1804607-kits-para-cozinhar-em-casa-ganham-espaco-no-mercado.shtml
- https://cultura.estadao.com.br/blogs/direto-da-fonte/chef-express/
- http://g1.globo.com/jornal-da-globo/noticia/2016/09/lojas-estao-apostando-em-clubes-de-assinaturas-para-fidelizar-os-clientes.html
- https://dcomercio.com.br/categoria/vida-e-estilo/quer-impressionar-na-cozinha-ela-da-a-receita
- http://g1.globo.com/globo-news/conta-corrente/videos/v/empresas-ampliam-o-faturamento-com-a-mudanca-de-habito-do-consumidor/4211944/
- https://prazeresdamesa.uol.com.br/culinaria-pratica/

### Local
Bairro Caxingui, cidade de São Paulo.

### Requisitos Obrigatórios

- PHP 7+ (Orientação a Objetos / Design Patterns)
- Lumen / Laravel (5.6+)
- ORM (Eloquent)
- Desenvolvimento de APIs REST
- Filas e Jobs
- Migrations
- MySQL
- MVC
- Git
- Apache / NGinx
- Agile / Scrum

### Diferenciais

- TDD
- Rocketeer
- AWS - EC2 / ELB / S3 / RDS / Cloudfront / ElasticSearch

### Contratação
PJ à combinar

### Nossa empresa
A Cheftime é uma empresa de tecnologia que vende assinatura de kits gastronômicos, possibilitando a todos serem verdadeiros chefs na cozinha!

### Como se candidatar
Interessados enviar currículo com pretensão salarial para adalberto.generoso@cheftime.com.br com assunto: #Programador PHP#

**Currículos fora do perfil desejado serão desconsiderados.**

### Labels

- PJ
- PHP
- Presencial

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
