### ISSUE TITLE
[Florianópolis] Analista de Sistemas Java [Nexxera] 

### ISSUE THREAD

**Issue by peopleti** [backend-br/vagas#55]
## Principais atividades:
Analisar documento de requisitos;
Elaborar projeto de software;
Pesquisar e estudar tecnologias para o uso nos projetos;
Participar da definição das tecnologias que serão utilizadas no desenvolvimento do projeto;
Apoiar na criação da arquitetura integrada dos sistemas e soluções;
Apoiar na criação de protótipos de arquitetura;
Elaborar orçamento (estimativa de tempo) com base no documento de requisitos para realização das tarefas;
Definir versionamento das aplicações;
Dividir as tarefas da versão com a equipe;
Registrar informações sobre a evolução do sistema dentro do sistema de controle interno;
Documentar e participar dos processos de atualização de sistemas nos ambientes de homologação e produção;
Elaborar modelo de dados e desenvolver SQL’s (DDL, DML);
Analisar e promover a solução de problemas (corrigir bugs, quando necessário);
Codificar sistemas e aplicações de acordo com os padrões e metodologias estabelecidos;
Codificar e aplicar testes unitários e de integração de acordo com os padrões e metodologias estabelecidos;
Comentar/Documentar o código escrito;
Manter a documentação técnica dos sistemas atualizada;
Garantir a execução das diretrizes da qualidade de softwares;
Apoiar na liderança técnica da equipe;
Apoiar no desenvolvimento dos colaboradores mais juniores;
Apoiar no refinamento do negócio junto às demais equipes;
Apoiar às demais áreas nas questões referentes aos custos e a viabilidade econômica dos projetos;
Atingir as metas propostas para o setor;
Demais atividades pertinentes ao cargo.

## Requisitos:
JAVA, JavaScript, JPA/Hibernate, PLSQL, EJB, JSF, Git, Oracle.

### **Descritivo completo no** [site da PeopleTI](http://peopleti.com.br/job/11410/)

Nível Pleno
Linguagem Java
Localização em Florianópolis, **sem** possibilidade de Home Office.

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
