### ISSUE TITLE
[Manaus - AM] Coordenador de SCM na SIDIA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#550]
### Sobre a empresa: Sidia

Somos um instituto de P&D localizado em Manaus (AM), responsável por implementar soluções inovadoras para o mercado local e global por meio de atividades de pesquisa e desenvolvimento. Atuamos no desenvolvimento e qualidade de software embarcado para celulares, tablets, novas tecnologias vestíveis (wearables) e smart TVs, aplicativos para óculos de realidade virtual, realidade aumentada, inteligência artificial e criação de games de classe mundial.

### Descrição: Ocupações do cargo:

Coordenar o time de SCM que tem como objetivo, dar suporte aos times de desenvolvimento nas áreas de Integração e Controle de Versão de código e geração de Releases.

### Você deve conhecer:

Integração contínua e Controle de Versão de código com GIT e Perforce;
Gestão de Issues com Jira;
Automação de Build com Jenkins e QuickBuild;
Programação em scripts: Python, Shell e Groovy;
Conhecimento em ferramentas de DevOPs: Docker, Linux, Banco de Dados;
Java, C, C++.

### Aqui você terá:

Salário compatível com o mercado;
Vale refeição;
Vale alimentação;
Transporte;
Previdência privada;
Plano de saúde;
Seguro de vida;
Vale cultura;
Cartão combustível;
Auxílio educação;
Auxílio mudança;
Passagens aéreas;
Flyback;
Auxílio moradia.

### Gostamos de pessoas:

Comprometidas;
Pró-ativas;
Capazes de trabalhar sobre pressão;
Alta capacidade de liderança;
Saiba falar inglês.

### Labels

CLT
Master / Especialista
Gestão / Direção

### Candidatar: http://bit.ly/sidia_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
