### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor .Net Full Stack na One Green

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#551]
### Sobre a empresa: One Green

O onegreen é um software especializado para a gestão dos processos de licenciamento ambiental, condicionantes, programas ambientais e tarefas. Fácil e prático de usar, você pode acessá-lo em qualquer lugar com seu navegador favorito.

### Descrição: Ocupações do cargo

Atuar na área de desenvolvimento de software WEB, utilizando metodologia ágil (Scrum), com grande capacidade de raciocínio lógico, criativo, independente para trabalhar em conjunto com equipe de desenvolvimento e planejamento (total liberdade criativa).

### Benefícios

Vale Transporte;
Vale Refeição;
Ambiente descontraído;
Horarios flexíveis;
No dress code;

### Aptidões e qualidades

.NET;
C#;
Orientação a Objetos;
Web services;
JavaScript;
jQuery;
SQL Server/Oracle;
HTML;
Visual Studio;
Design Patterns;
CSS;
MVC;
Controle de versão;
Coffee Script;
Saber trabalhar em equipe;
Ser colaborativo;

### Informações da empresa

Somos uma pequena empresa procurando um desenvolvedor para crescer junto à empresa. Nosso software é voltado para a área de meio ambiente, e nos 2 últimos anos dobramos nossos clientes e faturamento. Precisamos de pessoas que estejam dispostas à participar desse crescimento junto à nós atuando diretamente no processo criativo e evolutivo do sistema.

Apesar de sermos pequenos já trabalhamos com grandes empresas como a Gerdau e o Sesc.

### Informações complementares

Trabalhamos sem pressão em ambiente amigável e descontraído. Precisamos de mais colaboradores para evoluir o sistema e criação de novos módulos.

### Labels

Pleno/Junior
Alocado
CLT

### Candidatar: http://bit.ly/onegreen_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
