### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Java OU C# - Jr e Pleno - ITAÚ

### ISSUE THREAD

**Issue by nathaliaambrosio** [backend-br/vagas#555]
**Conhecimentos Técnicos**

- Obrigatório conhecimento em Java e/ou C#;
- Obrigatório conhecimento em Teste Unitário e banco de dados relacionais;
- Desejável conhecimento em ambiente Cloud, microserviços, mensageria e bancos não relacionais;
- Possuir experiência com metodologia ágil;

**Perfil Comportamental** 

- Profissional que busca se atualizar, estudar novas tecnologias;
- Paixão por desenvolvimento de sistemas;
- Pró-atividade e Postura de Dono;
- Capacidade analítica com foco em eficiência e resultados;
- Comunicativo, responsável, colaborativo e inovador;
- Planejamento e organização para trabalhar com entregas programadas;
- Habilidade de comunicação verbal e escrita;
- Facilidade para trabalhar em equipe e estabelecer parcerias.

**Enviar currículo para thais.mourato@integritygroup.com.br**

**Comment by lucasperrotta** [comment]
Aberta ainda?

**Comment by nathaliaambrosio** [comment]
Sim!


*Nathalia Ambrosio <https://www.linkedin.com/in/nathaliaoa/>Consultora de
Recrutamento e Seleção*

Rua Aureliano Guimarães, 150 - cj. 523
CEP 05727-160  São Paulo, SP
Cel.: (11) 98772-6865 <+55%2011%98772-6865> Tel.: (11) 3042-5100
<+55%2011%203042-5100>  (Ramal 1020)
www.integrityconsulting.com.br





Em qua, 20 de mar de 2019 às 17:40, Lucas Perrotta Barbosa <
notifications@github.com> escreveu:

**Comment by luicesar** [comment]
Bom dia, sou programador .NET qual seria o salário para o perfil ?

**Comment by nathaliaambrosio** [comment]
Oi Cesar, não conseguimos falar o salário por aqui. Mas podemos te ligar para explicar sobre a posição e remuneração. Nos envie seu currículo para podemos entrar em contato!

**Comment by luicesar** [comment]
Tudo bem. Enviei o meu curriculum para o e-mail thais.mourato@integritygroup.com.br

**Comment by guibranco** [comment]
Enviei!

**Comment by rjcjunior** [comment]
Aberto ainda?

**Comment by nathaliaambrosio** [comment]
Olá,

Continuamos com muitas vagas abertas!

* Nathalia Ambrosio <https://www.linkedin.com/in/nathaliaoa/>*
 Recruitment Consultant - Ramal 1020 | +55 (11) 98772-6865
[image: Assinatura de email - Be IT azul marinho.jpg]
<https://www.linkedin.com/company/beitrecruitment/>
 Nos siga nas redes sociais e acompanhe nossas vagas e conteúdos de TI
  <https://www.facebook.com/beitrecruitment>
<https://www.linkedin.com/company/beitrecruitment>
<https://www.instagram.com/beitrecruitment/> *
<https://www.youtube.com/channel/UCT0crpnJsCbPVf3cmA5Qu1g?view_as=subscriber> *




Em sex., 17 de abr. de 2020 às 19:11, Ricardo Junior <
notifications@github.com> escreveu:
