### ISSUE TITLE
[Manaus - AM] Desenvolvedor de Testes na SIDIA (Samsung Instituto De Desenvolvimento e Informática da Amazônia)

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#558]
### Sobre a empresa: SIDIA ( Samsung Instituto De Desenvolvimento e Informática da Amazônia )

Somos um instituto de P&D localizado em Manaus (AM), responsável por implementar soluções inovadoras para o mercado local e global por meio de atividades de pesquisa e desenvolvimento. Atuamos no desenvolvimento e qualidade de software embarcado para celulares, tablets, novas tecnologias vestíveis (wearables) e smart TVs, aplicativos para óculos de realidade virtual, realidade aumentada, inteligência artificial e criação de games de classe mundial.

### Descrição - Ocupações do cargo:

Entender os conceitos de requisitos e documentação de projetos;
Levantar cenários e escrever Casos de Teste de acordo com requisitos, padrões e tecnologias;
Análise, investigação e revisão de defeitos encontrados;
Identificar que técnica de teste usar e como aplicá-la;
Atribuir os riscos relacionados com a área testada e propor possíveis soluções; 
Executar testes exploratórios utilizando Google Approval e preparar relatórios dessa execução.

### Você deve conhecer:

Planejamento/execução de teste em dispositivos móveis;
Planejamento de teste, execução de testes, relatórios de defeitos;
Automação de ferramentas;
Java, C, C++;
Linux e ferramentas Office (Excel, Word e Power Point). 
Certificação CTFL é um diferencial para a vaga.

### Aqui você terá:

Salário compatível com o mercado;
Vale refeição;
Vale alimentação;
Transporte;
Previdência privada;
Plano de saúde;
Seguro de vida;
Vale cultura;
Cartão combustível;
Auxílio educação;
Auxílio mudança;
Passagens aéreas;
Flyback;
Auxílio moradia.

### Gostamos de pessoas:

Comprometidas;
Pró-ativas;
Capazes de trabalhar sobre pressão;
Alta capacidade de liderança;
Saiba falar inglês.
Com disponibilidade para viagens de negócios nacionais / internacionais 

### Labels

CLT
Alocado
Pleno

### Candidatar: http://bit.ly/sidiadevteste_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
