### ISSUE TITLE
[Londrina-PR ou Remoto] Desenvolvedor backend pleno na Lapaza

### ISSUE THREAD

**Issue by danielsanfr** [backend-br/vagas#559]
## Sobre a empresa Lapaza Empreendimentos LTDA

Empresa responsável pelo desenvolvimento e manutenção de sistemas de estacionamento rotativo em várias cidades do Paraná e com pretenção de aumentar esse número ainda mais.

## Descrição da vaga

**Fullstack Developer:** Será o responsável pelo desenvolvimento contínuo do backend do nosso sistema, incluindo novas features, adaptações e correções de bugs.

## Requisitos obrigatórios:

* Experiência com **Python/Django** ou **Ruby on Rails** ou **Elixir/Phoenix** (2 anos ou mais);
* PostgreSQL
* MongoDB
* Git (Git-flow)
* Bootstrap
* Javascript/Typescript
* Jquery

## Diferenciais

* Boa experiência em manutenção de servidores Linux e utilizando containers Docker em ambiente AWS;
* Experiência com a AWS - Amazon Web Services (route53, elastic beanstalk, RDS, Elastic Cache, ECR, EC2);
* Conhecimento intermediário/avançado de docker e docker-compose;
* Conhecimento intermediário/avançado de Linux (server side);
* Experiência com shell script.

## Contratação

A combinar, podendo ser CLT ou PJ com férias e décimo terceiro salário. Os possíveis benéficios serão negociados a depender do tipo de contratação que desejar.

## Como se candidatar

Envie um e-mail para danielsan@lapaza.com.br com o título **Vaga para Desenvolvedor Backend**. Coloque sua pretensão salarial, links para Github e ou LinkedIn e também anexe seu currículo.

> **Labels:** AWS, Docker, Python/Django, Ruby on Rails, Elixir/Phoenix, CLT, PJ, Remoto, Pleno

**Comment by raloliver** [comment]
Sou frontend com experiência em javascript e especialista em angular 2+, moro em Curitiba. Posso enviar CV?

**Comment by jonataszanol** [comment]
Olá, meu nome é Jonatas Samuel

Tenho experiencia com Ruby on Rails, JavaScript, Jquery, Linux e Docker.

Linkedin <http://www.linkedin.com/in/jonatas-samuel-zanol-vieira-181164145>

Como faço para enviar o meu curriculum para participar do processo seletivo?

Desde já agradeço!

Em ter, 23 de out de 2018 às 15:07, Israel Oliveira <
notifications@github.com> escreveu:

**Comment by danielsanfr** [comment]
@raloliver e @jonataszanol vocês podem se candidatar conforme a última seção do anúncio da vaga (que atualizei agora a pouco).

> Envie um e-mail para danielsan@lapaza.com.br com o título **Vaga para Desenvolvedor Backend**. Coloque sua pretensão salarial, links para Github e ou LinkedIn e também anexe seu currículo.

**Comment by raloliver** [comment]
@danielsanfr enviado!

**Comment by danielsanfr** [comment]
Só avisando que ainda estamos aceitando curriculos.

**Comment by danilocandido** [comment]
enviado!

**Comment by danielsanfr** [comment]
Conseguimos algumas pessoas. Obrigado a todos que tiverem interesse. Assim que surgir um novo oportunidade os que não foram chamados iram ser os primeiros a ser contactados.
