### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack PHP Junior - On Now

### ISSUE THREAD

**Issue by kaiorocha** [backend-br/vagas#56]
**Descrição da vaga:**
Procuramos desenvolvedor(a) para trabalhar com projetos desenvolvidos em Magento e Laravel, para o desenvolvimento de novas funcionalidades conforme a demanda e regras de negócios, executar manutenções e melhorias nos projetos existentes, e realizar testes para garantir a qualidade e integridade dos projetos .

**Sólidos conhecimento em:**
PHP, MySQL, HTML, CSS, Angular, JQuery, WebServices.

**É um diferencial:**
- Conhecimento na plataforma vtex;
- Conhecimento de AWS;

**Local da vaga:**
R. Cubatão, 97 - Paraíso, São Paulo - SP

Contratação PJ a combinar
Possibilidade de trabalho remoto

Por favor envie um e-mail para jobs@onnow.com.br com seu CV em anexo e pretensão salarial.
Enviar no assunto: Vaga Desenvolvedor Full Stack PHP Junior.

**Comment by reginaldojunior** [comment]
Vaga preenchida?
