### ISSUE TITLE
[São Paulo] FullStack Developer na [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#560]
A Confitec é uma empresa de Tecnologia da Informação com 15 anos de trajetória e escritórios no Rio de Janeiro e em São Paulo, com grande bagagem de atuação no mercado de Seguros.

Temos oportunidades como Desenvolvedores Fullstack (Pleno e Sênior) para fazer parte do nosso time interno, em equipes voltadas à inovação tecnológica.

Buscamos profissionais com vivência em desenvolvimento .Net, WebAPI, Entity framework e front end com Javascript, Typescript, Angular (JS e/ou 2+).

Nossa contratação é CLT Full + benefícios e nosso escritório está localizado na zona sul de São Paulo (ao lado dos Shoppings Morumbi e Market Place e à 5 minutos da estação Morumbi da CPTM). 

Se interessou? Mande seu cv e pretensão salarial para curriculos@confitec.com.br.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
