### ISSUE TITLE
[Curitiba - PR] Backend Developer Java na Action Labs

### ISSUE THREAD

**Issue by fleite** [backend-br/vagas#561]
Precisamos de um ninja da programação back end no ambiente Java EE, para tornar realidade tudo que nossos clientes precisam, com estabilidade e escalabilidade. Nosso back end developer trabalhará na produção da infra estrutura de serviços REST para prover suporte a todo o tipo de interface (desktop, tablets, smartphones).

**Perfil Action Labs**
Nós trabalhamos com inovação. Isso significa que a solução final muitas vezes não é como imaginamos no começo. Você deve ter muita flexibilidade para trabalhar em projetos cujas necessidades são revistas ao longo do caminho e ter iniciativa para criar soluções inovadoras para problemas inesperados, sem perder o foco no objetivo final do projeto. Nossas equipes têm muita autonomia para trabalhar de forma independente, com interações assíncronas com outros colaboradores-chaves no projeto – inclusive clientes. Portanto é essencial que você tenha a capacidade de relacionar-se com equipes de diferentes departamentos e compreender os diferentes pontos de vista sobre o produto. E, finalmente, queremos gente com visão crítica do trabalho, que saiba defender suas ideias de forma coerente e fundamentada.

Se este é um lugar no qual você gostaria de trabalhar, vem pra cá.

**Suas principais atividades / responsabilidades serão:**
Produzir e otimizar códigos para maior performance, escalabilidade e velocidade;
Construir códigos e bibliotecas reutilizáveis para uso futuro;
Garantir a viabilidade técnica das funcionalidades previstas;
Ser responsável pela qualidade e funcionamento das soluções implementadas

**Formação:**
Ensino superior completo em Ciências da Computação, Sistemas de Informação ou semelhantes

**Estes conhecimentos são fundamentais:**
- Java EE (EJB 3.1, JPA, CDI, Spring, etc)
- JSON
- APIs REST Java (JAX-RS, Jackson/RESTEasy)
- Bancos de dados relacionais (MySQL/PostgreSQL)
- Servidores Java EE (Wildfly/TomEE/Glassfish/Spring Boot)
- JUnit
- Maven/Gradle
- Git
- Inglês intermediário

**Estes conhecimentos são desejáveis:**
- Bancos de dados NoSQL (MongoDB)
- Ambiente AWS
- Desenvolvimento .Net
- Ambiente Azure
- Ferramentas de integração e delivery contínuos (Codeship)
- Metodologias ágeis de desenvolvimento (Scrum/Kanban)
- Monitoramento de aplicações

**O que esperamos de você:**
- Iniciativa para criar soluções tendo em vista o objetivo final do projeto.
- Capacidade de analisar criticamente os projetos nos quais está envolvido e defender suas ideias de forma coerente e fundamentada;
- Autonomia para trabalhar de forma independente com interações assíncronas com o restante equipe;
- Flexibilidade para trabalhar em projetos cujas necessidades podem ser revistas ao longo de sua evolução;
- Capacidade de relacionar-se com equipes de diferentes departamentos e compreender os diferentes pontos de vista sobre o projeto.

**Benefícios que oferecemos:**
- Bônus anual de até um salário e meio
- Plano de Saúde
- Acesso ao aplicativo Ei, Doutor!, com um assistente pessoal de saúde para atendimento individualizado.
- Vale Refeição / Alimentação
- Vale Transporte
- Ajuda de Custo para Estudo, Treinamento e Aperfeiçoamento
- Conta no Spotify
- Acesso aos Benefícios de Amigos do Hospital Pequeno Príncipe, incluindo desconto em cursos, lojas e viagens

Entre em contato com currículo e pretensão salarial CLT por esta issue ou via email: contato@actionlabs.com.br

**Comment by raloliver** [comment]
A vaga de frontend ainda está aberta?

**Comment by fleite** [comment]
> A vaga de frontend ainda está aberta?

Olá, acabamos preenchendo aquela vaga em agosto mesmo.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
