### ISSUE TITLE
[Porto Alegre] Desenvolvedor Java na YieldStreet

### ISSUE THREAD

**Issue by mbrito-yieldstreet** [backend-br/vagas#562]
### A Empresa
A [YieldStreet](https://www.yieldstreet.com) é uma empresa de investimentos alternativos com sede em Nova York com uma equipe de desenvolvimento em Porto Alegre, RS. Estamos buscando desenvolvedores backend com experiência em Java.

### Nossa Tecnologia
Trabalhamos com um stack de tecnologia moderno, que conta com:

* Java 8 e 11
* Play Framework
* Akka
* Lagom
* Kafka

E muito mais. Acreditamos em escolher a ferramenta certa para cada trabalho, e nos benefícios de diversidade e criatividade tecnológica. Para esta vaga, o único requisito indispensável é uma experiência sólida em **Java** e a capacidade de s comunicar em **Inglês**.

### Modalidade de trabalho e contratação
O trabalho será exercido no escritório de Porto Alegre. Ficamos na Rua Gonçalo de Carvalho, numa sala pequena mas aconchegante e com um clima descontraído. Visitas para conhecer o escritório e a equipe são bem vindas.

A contratação é através de uma terceira, a [White Prompt](https://whiteprompt.com/). A WP tem também sede nos EUA, assim que o contrato é pago **em dólares**. Entre em contato para saber mais detalhes de como isso funciona.

### Envio de currículo
Interessados podem enviar curriculo para mbrito@yieldstreet.com e christian.kedidjian@whiteprompt.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
