### ISSUE TITLE
[PINHEIROS - São Paulo - SP] Desenvolvedor Magento Backend na [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [backend-br/vagas#563]
• Backend Magento, Layout Xml, Observers, EAV, Payment, Checkout, entre outras áreas essenciais do sistema;
• Magento Community 1.x
• Magento Enterprise 1.x.x
• PHP 5.0 +, JS, JS Frameworks (jQuery, Prototype).
• Banco de dados MySql 4.5 +; MongoDB
Contratação: CLT
Benefícios: VR: 440,00/Assistência Médica/ Odontológica Care Plus/ Vale Transporte e Seguro de Vida.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
