### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Back End na MONETIZZE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#566]
### Sobre a empresa: Monetizze

Criada em 2015, o Grupo Monetizze é uma empresa de tecnologia que tem como missão despertar o UAU dos nossos CLIENTES, por meio do que há de mais inovador no mercado. Nossa filosofia de trabalho é baseada nas grandes referências de tecnologia do mundo, buscando oferecer um ambiente agradável e livre. Acreditar e investir no bem estar dos nos nossos colaboradores é a nossa estratégia para alcançar os melhores resultados. Para garantir isso, proporcionamos um espaço de lazer sensacional, contendo sinuca, totó, cadeira de massagem e fliperama onde você poderá relaxar nos seus intervalos, além de lanches à vontade. Somos uma empresa dinâmica, com possibilidade de horários flexíveis, onde você terá proximidade com os seus líderes e diretoria para discussão de idéias. Em troca, esperamos de você, comprometimento com a excelência, foco em resultados, planejamento e organização, resiliência, otimismo e senso crítico e analítico. 

### Descrição: Ocupações do cargo

•	Programar, codificar e testar linguagens de programação, com base nos sistemas desenvolvidos.

•	Executar a manutenção dos sistemas, fazendo eventuais correções necessárias, visando atender às necessidades dos usuários.

•	Desenvolver os trabalhos de montagem, depuração e testes de programas, executando serviços de manutenção nos programas já desenvolvidos.

### Benefícios

Vale Alimentação;
Vale Refeição;
Vale Transporte ou Vale Combustível;
Plano de Saúde e Odontológico sem cooparticipação;
Seguro de Vida.

### Requisitos

Experiência de no mínimo 5 anos com PHP;
Conhecimento em tecnologias back-end;
Conhecimento avançado em Linguagem PHP orientado a Objeto. POO;
Conhecimento avançado em JavaScript;
MYSQL;
HTML;
CSS;
Git;
Sass;
Conhecimento em responsive design;
Escrever código limpo e semântico, seguindo padrões do W3C.

### Desejáveis:

Experiência de trabalho em metodologias ágeis (equipe Scrum);
Conhecimento AWS (Amazon).
Conhecimento em arquitetura de microservices

### Labels:

Pleno
CLT
Alocado

**Comment by silasvasconcelos** [comment]
É possível **remoto**?

**Comment by megandavulpi** [comment]
> É possível **remoto**?

Apenas presencial, @silasvasconcelos .

**Comment by silasvasconcelos** [comment]
Obrigado @megandavulpi

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
