### ISSUE TITLE
[Betim - MG] Desenvolvedor Full Stack na SyncSoftwares

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#567]
### Sobre a empresa: SyncSoftwares

A Sync Softwares está no mercado a mais de 8 anos. Possuímos um ERP que se chama WebGlass e atendemos exclusivamente indústrias de vidro e vidraçarias, em todo território nacional e hoje com mais de 150 clientes. Nossa missão é oferecer soluções com excelência para o setor vidreiro, primando pelo desenvolvimento de nossos clientes para que concretizem todo seu potencial. Nossa visão para os próximos três a cinco anos é dobrar a quantidade de colaboradores, triplicar a quantidade de clientes, termos produtos com tecnologia de ponta e termos concluído a nossa nova sede. Nossos valores são a colaboração, comprometimento, melhoria contínua, qualidade, responsabilidade e satisfação do cliente.

### Descrição:

**Você deverá saber:**

C#
JavaScript
Visual Basic .Net (WebApi)
MySql

### Seria bom se você soubesse:

Vue.js
Bootstrap
Entity Framework

### O que você vai ter conosco?

Além de oferecermos um ambiente descontraído que permitirá seu crescimento e evolução, você vai ter também:

Vale transporte ou auxílio combustível
Vale Refeição
Plano de saúde coparticipativo
Plano odontológico coparticipativo

### O que esperamos de você?

Esperamos que você seja comprometido, colaborativo, responsável e que busque sempre aperfeiçoar os seus conhecimentos a cada dia. Estamos em crescimento e queremos que você venha conosco. Para isso, é de extrema importância que você tenha grande empatia com nossos clientes e por fim, que nos auxilie a ter um produto de máxima qualidade.

### Labels:

CLT
Alocado
Pleno/Júnior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
