### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Web Full Stack na AVANÇO INFORMÁTICA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#568]
### Sobre a empresa: Avanço Informática

Avanço Informática é uma empresa especializada no desenvolvimento de software para varejo. Juntando-se a nós você fará parte de uma das melhores empresas para trabalhar segundo o GPTW! Aqui você terá um ambiente onde o clima de trabalho é muito bom e leve, em uma empresa que está crescendo. Nossa missão é facilitar o dia a dia dos varejistas e nossos valores - ética, respeito às pessoas, excelência na execução, responsabilidade individual, satisfação dos clientes e trabalho em equipe são vivenciados no nosso cotidiano.

### Descrição: Ocupações do cargo

Você deverá ter a capacidade de analisar, testar e comunicar. Deverá analisar sistemas e as manutenções corretivas e adaptativas. Deverá entender os recursos e requisitos para fornecer insights para o desenvolvimento dos produtos e manutenções dos mesmos. Deverá também realizar testes de funcionalidades das aplicações e compartilhar os mesmos com a equipe de Qualidade, focando sempre na melhoria e aperfeiçoamento dos produtos.

### Você deve conhecer:

Conhecimento de linguagem Javascript, CSS e TypeScript;
Frameworks e bibliotecas como Node.Js e AngularJS
PostgreSQL, MySQL e NoSQL com MongoDB

### É um diferencial você conhecer:

Material ou Responsive Design
Metodologias ágeis
REST, SOAP, Java, GIT e SQL
Serviços AWS

### Aqui você terá:

Vale Refeição
Vale transporte
Plano de saúde Unimed
Convênio Farmácia
Convênios com Faculdades, Academias, Escolas de Idiomas entre outros
Sala de descanso e um ótimo clima de trabalho!

### Gostamos de pessoas:

Criativas
Inovadoras
Focadas
Abertas ao crescimento
Ótimo relacionamento interpessoal

### Nossos valores: 

**Nossa missão é facilitar o dia-a-dia dos varejistas e nossos valores são:**

Ética
Respeito às pessoas
Excelência na execução
Responsabilidade individual
Satisfação dos clientes e
Trabalho em equipe são vivenciados

### Labels:

Alocado
Júnior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
