### ISSUE TITLE
[São Paulo] Desenvolvedor BackEnd Pleno/Sênior na EASYNVEST :)

### ISSUE THREAD

**Issue by MariliaLeocadio** [backend-br/vagas#57]
# **Descrição da vaga**
Buscamos profissionais que estejam a frente de seu tempo, flexíveis e ousados para compor nossos **Squads multidisciplinares** na área de TI.
Temos vagas de nível Pleno e Sênior.
Projeto em .NET Core / .NET / C#/ Princípios SOLID

**Local**
Av Dr Cardoso de Melo, 1608 - Vila Olímpia, SP

**Benefícios**
Plano de saúde Bradesco Nacional
Plano Odontológico
VR de R$ 31/dia
VA de R$410
Gympass
Auxílio creche

**Diferenciais**
Horários Flexíveis
Bermudas liberadas
Cultura Ágil
Divisão por Squads, rotativo por cada projeto.

**Requisitos**
Obrigatórios:
Experiência em novos desenvolvimentos, planejando a arquitetura do zero
Familiarizado com a cultura de testes
Diferenciais:
Experiência em Testes Unitários e .NET Core

**Contratação**
CLT

**Nossa empresa**
A Easynvest está se transformando constantemente há 49 anos. Somos a única corretora de valores brasileira no ranking CB Insights, eleita como uma das Fintechs mais inovadoras do mundo, e a atual Líder no Tesouro Direto.
Somos uma empresa aberta e inclusiva, caminhamos todos juntos, respeitando e aproveitando de todas as nossas muitas diferenças, para sermos a melhor opção para o cliente. Erramos rápido e aprendemos rápido. Cada um de nós é um verdadeiro empreendedor e desafia o status quo para sempre sermos autênticos.

**Como se candidatar**
Por favor envie um email para marilia.leocadio@easynvest.com.br com seu CV anexado - enviar no assunto: Vaga BackEnd GitHub

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
