### ISSUE TITLE
[GRAMADO] Desenvolvedor(a) Fullstack na KW Recursos Humanos

### ISSUE THREAD

**Issue by andremenezeswk** [backend-br/vagas#570]
## Descrição da vaga

- Participação em projetos de implementação e manutenção de sistemas
- Codificação e realização de testes
- Elaborar documentação e manuais de operação de sistemas

## Local

Escritório em Gramado/RS

## Benefícios

- Vale Alimentação de R$ 20,00 por dia útil
- Unimed
- Seguro de Vida
- Farmácia
- Ajuda Combustível

## Requisitos

- HTML
- CSS
- JavaScript
- AngularJS
- C# JSON
- Webservice 
- Banco de dados SQL Server

## Contratação

- CLT

## Nossa empresa

Empresa de Turismo localizada em Gramado

## Como se candidatar

Por favor envie um email para daiani.souza@wkrh.com.br com seu CV anexado. Ou pelo link https://www.wkrh.com.br/job/desenvolvedor-fullstack-a0f1i000004vur1uag/

## Labels

- CLT

**Comment by joaomsneto** [comment]
A entrevista pode ser feita de maneira remota? 

Estou em João Pessoa/PB

**Comment by andremenezeswk** [comment]
Olá @joaomsneto, pode sim. Tem como nos enviar o teu currículo? 

Pode encaminhar para daiani.souza@wkrh.com.br

Um abraço.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
