### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby on rails [Clicksign]

### ISSUE THREAD

**Issue by rodrigopaulo** [backend-br/vagas#571]
![vaga clicksign](https://user-images.githubusercontent.com/13781510/47853794-a36aa480-ddbe-11e8-895b-c40670497106.png)

Necessitamos de um desenvolvedor de aplicação Ruby on Rails para ocupar posição no time da Clicksign. Valorizamos o trabalho em equipe, proatividade e facilidade em comunicação verbal e escrita.

### **Sobre a empresa:**
A Clicksign é uma plataforma de assinatura eletrônica de documentos que vem ganhando rápido crescimento no mercado. Aqui você trabalhará em um ambiente em constante evolução de forma ágil e flexível, onde terá a oportunidade de se desenvolver e crescer junto com a empresa, sempre tendo contato direto com os fundadores e demais colaboradores.

### **Localização:**
- Estamos em São Paulo em frente à estação de metrô Faria Lima  
- Nossa equipe conta com membros fora do estado de São Paulo que trabalham remotamente
- Candidatos de São Paulo também podem trabalhar remotamente

### **Atividades:**
- Análise de viabilidade técnica dos projetos
- Desenvolvimento de projetos pontuais
- Abstração e construção de demandas comuns a vários projetos

### **Requisitos:**
- Ruby on Rails: 3 anos ou mais de experiência
- RESTFul
- Linux
- Git
- Português: comunicação e escrita
- Inglês: intermediário para leitura
- Full time job

### **Diferenciais:**
- Ferramentas de deploy: Ansible, Docker
- Frameworks client-side: Vue
- Processamento de PDF
- Amazon AWS

### **Remuneração:**
- Remuneração compatível com o mercado de trabalho
- Contratação PJ

Interessados na vaga, favor mandar o currículo para o email: **dev-jobs@clicksign.com**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
