### ISSUE TITLE
[São Paulo/SP] PHP Developers na Hypnobox

### ISSUE THREAD

**Issue by markgerald** [backend-br/vagas#572]
## Descrição da vaga

A Hypnobox precisa de PHP Developers para os projetos internos e de sustentação em andamento/novos.

## Local

Escritório, São Paulo - Pinheiros - Próximo ao Metrô Faria Lima (Bem próximo!)

## Benefícios

- À combinar

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5/7
- 2 anos de experiência com MySQL e/ou banco de dados não relacionais
- **Não ter mimimi com código legado** :slightly_smiling_face: 
- OOP (de verdade!)
- Symfony 2/3 e se puder, 4 (Ou outro framework de Mercado, como Zend ou Laravel)
- PSR2, Clean code
- Ótimo TeamPlay

**Desejáveis:**
- TDD, BDD
- Vivência com sistemas SAAS
- Docker

**Diferenciais:**
- DDD

## Contratação

CLT/PJ à combinar

## Nossa empresa

O Grupo Hypnobox tem um DNA jovem e vibrante. Nosso maior objetivo é fornecer soluções únicas de produtividade para as melhores empresas do mercado imobiliário. O grupo - como parceiro estratégico dos seus clientes - conecta as pessoas, constrói sucesso, cria realidades novas e transforma o mercado através novos jeitos de fazer acontecer.

## Como se candidatar

Por favor envie um email para mark.gerald@hypnobox.com.br com seu CV anexado - enviar no assunto: Vaga PHP Developer

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
