### ISSUE TITLE
[REMOTO] DevOps @ Simbiose

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#5722]
Olá, pessoal,

Por favor, alguém aqui tem interesse em migrar para a área de DevOps?

Temos vagas para duas pessoas em DevOps. Se a pessoa já tiver conhecimento prático com DevOps, excelente. Mas se não tiver, nós estamos dispostos a ensinar tudo o que for necessário, inclusive pagando por cursos e certificações. Já fizemos isso antes com muito sucesso.

Precisa ter inglês realmente avançado. Não adianta ser intermediário.

O trabalho é remoto com carga horária de 8 horas por dia, com flexibilidade na adequação dos horários para quem for estudante.

Quem tiver interesse, favor enviar CV ou o Linkedin para o endereço abaixo, incluindo a pretensão salarial inicial:

fazerparte@simbioseventures.com

Muito obrigado! 😀

Abs,
Gabriel

**Comment by wendelcampos** [comment]
Boa noite Gabriel, tudo bem ?

Tenho certeza que seria muito bom migrar para a área de DevOps, mas o real
desafio seria o inglês infelizmente no Brasil existe uma porcentagem mínima
de 9% dos brasileiros que realmente possuem o inglês avançado para o
fluente. Mas caso a empresa reconsidere o inglês para tecnico ou ter uma
chance de aprendizado no ingles ficarei feliz em participar do processo
seletivo.

Obrigado

Att

Wendel

Em seg, 24 de mai de 2021 21:24, Gabriel Menegatti ***@***.***>
escreveu:

**Comment by gmenegatti** [comment]
@wendelcampos, obrigado pelo seu interesse. Sugiro que se candidate.

Nós temos um teste de inglês logo no início do processo, portanto, se não der certo, você vai saber rápido.

O inglês é realmente importante, mas pode ter certeza que não é o fator determinante. :-)

PS: Sim, é uma pena que só 9% dos brasileiros falem inglês. Mas infelizmente os melhores materiais de treinamento do mundo e as próprias documentações dos serviços são em inglês. Já tentamos selecionar pessoas que tinham quase nada de inglês e sofremos muito na hora de ensinar.

**Comment by wendelcampos** [comment]
Gabriel obrigado pelo retorno.

Realmente o inglês é ferramenta muito importante, principalmente para
leitura de manuais técnicos e de participar de treinamentos, compartilho a
sua preocupação, inclusive na minha carreira já declinei algumas
oportunidades, devido a falta do inglês, mas acredito que para leitura
técnica tenho uma boa capacidade de entendimento e boa capacidade de
aprendizado.

Portanto, irei seguir a sua sugestão e vou participar do processo seletivo.

Obrigado pela atenção.

Atenciosamente.

Wendel.

Em seg., 24 de mai. de 2021 às 22:13, Gabriel Menegatti <
***@***.***> escreveu:

**Comment by gmenegatti** [comment]
Vagas preenchidas. :-)
