### ISSUE TITLE
[Home Office] Back-end Developer NodeJs na Qintess

### ISSUE THREAD

**Issue by rafroza** [backend-br/vagas#5728]
## EMPRESA
Com 30 anos no mercado, somos uma multinacional brasileira entre as maiores integradoras de TI do Brasil.
Valorização dos talentos, seriedade, compromisso no atendimento aos clientes, agilidade e qualidade nos projetos são algumas das premissas que nos diferenciam.
São mais de 2000 clientes – grandes empresas nacionais e globais – que nos reconhecem pela excelência e inovação, o que só é possível pelo trabalho de uma equipe altamente qualificada e engajada. Reunimos diferentes programas de qualidade de vida e oportunidades de carreira, além de ações para proporcionar um ambiente de trabalho motivador e colaborativo, com incentivo à diversidade e à inovação. Tudo isso, baseado nos princípios ESG – Environmental, Social and Governance (em português: Ambiental, Social e de Governança), uma prática global que tem ganhado força no mundo dos negócios e que é composta por três fatores centrais que atuam na medição da sustentabilidade e do impacto social de uma empresa.
Mais de 3.500 profissionais altamente capacitados compõem a nossa equipe em mais de 151 cidades no Brasil e na América Latina. Estamos na era da mudança permanente e, nesse cenário, trabalhamos para suportar as empresas à alcançarem um novo patamar de desempenho e alavancarem à transformação digital.
Somos uma fonte de geração de ideias, que trabalha de forma colaborativa, que transforma pessoas e estas transformam o jeito de fazer negócios.

Para mais informações, acesse: www.qintess.com
 

## DESCRIÇÃO DA VAGA
Pessoa Desenvolvedora NodeJS

 
## LOCAL
Home Office

## BENEFÍCIOS

•    Plano de saúde AMIL Apto
•    Convênio Odontológico - AMIL DENTAL
•    Seguro de vida
•    Vale refeição
•    Auxílio creche
•    Convenio Farmácia

## REQUISITOS
 
**Obrigatórios**
- Atuação no desenvolvimento do roadmap do CRM Spirit
- Sustentação do produto, fazendo análises de incidentes e correções
- Auxiliar nas definições de Discovery do produto
- Participação e acompanhamento do squad no dia a dia
- Forte atuação em Node.js
- Conhecimentos em nosql
- Conhecimentos de elastic search

**Diferenciais**

- Conhecimento das ferramentas AWS (dynamo, cógnito)
- Conhecimentos de Scrum

 

## Como se candidatar

Por favor envie um email para rafael.roza@qintess.com com seu CV anexado - enviar no assunto: [VAGA XX] [Seu nome completo]

### Contratação:
- CLT

**Comment by jairosl** [comment]
Qual nível técnico para a vaga ?
