### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Full Stack na CONSULTE GEO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#573]
### Sobre a empresa: Consulte GEO

Visando atender o crescimento na área da construção civil nacional, surgiu em 2007, a Consulte GEO. Uma empresa de software de gestão de obras, cujo sistema se caracteriza pela integração das ações em todos os níveis e etapas, do planejamento à execução, garantindo assim, a qualidade dos serviços contratados, tornando a gestão de obras ágil, organizada e eficiente. Trabalhamos com as maiores construtoras do país, desenvolvendo ferramentas escaláveis e que tragam melhorias na qualidade da engenharia brasileira.

### Descrição: Ocupações do cargo

Desenvolver um novo sistema;
Diagnosticar e resolver problemas no sistema já existente;
Participar e propor novas soluções e inovações;

### Benefícios

Vale Transporte;
Vale Alimentação;
Plano de Saúde;
PL;
Participar de uma equipe e empresa que prezam pelo seu conhecimento e crescimento e que esta disposta a te ajudar e proporcionar isso;

### Aptidões e qualidades

Aptidão para liderança;
Trabalho em equipe;
Versatilidade;
Pró-atividade;

### Conhecimentos:

Asp.Net Core
Angular 2
MVC
Bootstrap
SQL Server

### Diferenciais:

Cloud
Experiência em desenvolvimento Mobile

### Informações da empresa:

A nossa missão é ajudar no crescimento e na qualidade da engenharia brasileira, e executamos isso com muito amor. Somos uma equipe pequena mas trabalhamos com grandes empresas. Sempre procuramos trabalhar com as mais novas tecnologias do mercado, possuímos um ambiente leve e pessoas tratando como se fossemos uma família. Prezamos muito pelo crescimento dos nossos profissionais e contribuímos tanto para o crescimento profissional quanto para o pessoal.

### Labels:

Pleno/Senior
Alocado

### Candidatar: http://bit.ly/consultegeo_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
