### ISSUE TITLE
[Brasil] Back-end Developer @ OSF Digital

### ISSUE THREAD

**Issue by wendelkassio12** [backend-br/vagas#5737]
**Enviar CV para wendel.kassio@osf.digital**
Descrição do trabalho
• Desenvolver experiências dinâmicas e aprimoradas de comércio eletrônico na web
• Desenvolver aplicativos baseados na web específicos do cliente, integrações de sistemas e desenvolvimento de aplicativos personalizados
• Aplicar habilidades técnicas em ambientes de front e back-end

Requisitos
• Uma boa compreensão de 
• Experiência com Web Services
• Experiência no consumo de dados em tempo real de APIs (Rest, JSON)
• Experiência anterior em desenvolvimento back-end (PHP, ASP.NET, Java, etc.)
• Experiência em desenvolvimento web
• Experiência com programação orientada a objetos e padrões de design MVC
•  (intermediário, avançado ou fluente)

**Comment by FilipeAugustoVO** [comment]
Olá, boa noite. Acredito que faltam certas informações na vaga.
