### ISSUE TITLE
[São Paulo - SP] BackEnd Developer na Senior Solution

### ISSUE THREAD

**Issue by SeniorSolutionSA** [backend-br/vagas#576]
## Descrição da vaga

Projeto de inovação para serviços financeiro da Senior Solution S.A. em seu braço de inovação o Lab Torq, um laboratório de inovação dedicada a serviços financeiros. Trabalhando com desenvolvimento de componentes-chave em Java de acordo com um plano de projeto e com construção de protótipos e desenvolvimento de aplicações.
  
## Local

Escritório do Torq - São Paulo - Vila Mariana

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 17,50/dia
- Pacote de Unidades Flexíveis (UF), no qual o colaborador pode alocar uma valor extra de benefícios onde desejar, como em vale alimentação, vale combustível, vale estacionamento, previdência privada ou melhor os benefícios do pacote básico.

#### Diferenciais

- Ambiente de StartUp
- Empresa entra as pequenas/médias empresas que mais crescem no país
- Maior empresa de seu nicho de mercado no Brasil
- sala de jogos
- Ambiente de inovação

## Requisitos

**Requisitos Técnicos:**

- JDK 1.8 

- Domínio da linguagem Java 1.7 e/ou superior  

- SqlServer e/ou Oracle  

- Spring Boot 

- GIT Flow 

- Maven 

- Microserviço 

- API Rest 

- Database Oracle 11g 

- JUnit, Mockito 

- Testes unitários e de integração 

**Desejáveis:**
- Netflix OSS 

- Docker 

- NoSQL (MongoDB, Redis, Elasticsearch) 

- Liquibase 

- Nexus 

- Sonarqube 

- Ter trabalhado com metodologias ágeis 

- Ter trabalhdo com In-Memory Database 

## Contratação

CLT

## Nossa empresa

A Senior Solution é líder em softwares e serviços para o setor financeiro. Atendemos mais de 360 clientes de diversos segmentos: bancos, gestores de recursos, entidades de previdência, administradoras de consórcios, seguradoras e operadoras de saúde, entre outros. Além disso, somos uma equipe com mais de 800 colaboradores nas cidades de São Paulo, Belo Horizonte, Rio de Janeiro e Ribeirão Preto, e contamos com mais de 3.000 acionistas brasileiros e estrangeiros. 

Veja mais no site da empresa: www.seniorsolution.com.br 

## Como se candidatar

Por favor se inscreva na vaga através do seguinte link:  [https://goo.gl/qZdEu5](https://goo.gl/qZdEu5)

## Labels

- CLT
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
