### ISSUE TITLE
[LISBOA] BACKEND .NET C # DEVELOPER  @ PDMFC # REMOTO

### ISSUE THREAD

**Issue by nathiblp** [backend-br/vagas#5768]
# BACKEND .NET C # DEVELOPER (REMOTO – EMPRESA EM PORTUGAL – PROJETO DE 6 MESES)

# DESCRIÇÃO

Procuramos engenheiros que sejam apaixonados por programação e tenham grandes habilidades em .NET E em desenvolver aplicativos C # e lançar produtos de alta qualidade que alcancem os usuários finais em todo o globo.

# RESPONSABILIDADES

• Projetar, desenvolver, testar, implantar, manter e melhorar o software

• Desenvolver especificações técnicas de software com base nos requisitos do cliente

• Executar análise geral, design, implementação e teste de software, normalmente integrado em uma equipe de projeto

• Executar atividades de manutenção de software, incluindo a análise de problemas
relatados pelo suporte técnico ou cliente e fornecer feedback correspondente

• Desenvolvimento de aplicativos de usuário final

• Contribuir para o planejamento do projeto

# REQUISITOS

• Graduação obrigatória; BS / MS em Ciência da Computação ou Engenharia da Computação de preferência;

• Fortes habilidades de programação usando framework .Net e C #;

• Sólida base em programação orientada a objetos, estruturas de dados e algoritmos;

• Capacidades de modelagem e integração de banco de dados (ADO.NET, Entity Framework, etc);

• Experiência comprovada de trabalhar com serviços HTTP, XML, SOAP e trabalhar com dados remotos via REST e JSON;

• Sólidos conhecimentos em MS Visual Studio ou ferramentas IDE similares;

• Fluente em Inglês (escrito e falado);

# O QUE NÓS OFERECEMOS?

• Um ambiente de trabalho excelente e descontraído;

• Honestidade e comprometimento com os colaboradores;

• Foco em desenvolver suas habilidades e aumentar seus conhecimentos;

• A oportunidade de fazer parte de uma empresa de sucesso com mais de 10 anos de experiência em negócios móveis

# Contato

Interessados, enviar CV para nathalia.pires@pdmfc.com, pf.

**Comment by FilipeAugustoVO** [comment]
Uma vaga interessante... mas fora do padrão. Não vejo onde me inscrever,
por exemplo.

**Comment by nathiblp** [comment]
Olá Filipe,

Atualizei para o padrão.
