### ISSUE TITLE
[Belo Horizonte - MG] Cientista de Dados no BANCO INTER

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#579]
### Sobre a empresa: Banco Inter

O Banco Inter é o primeiro banco totalmente digital com ações listadas na B3 e o único a oferecer uma conta 100% gratuita. Com uma robusta plataforma de multisserviços, somos um banco prático e completo como os novos tempos exigem.

### Descrição: Ocupações do cargo

Será responsável por aplicar conceitos de modelagem matemática no dia a dia da empresa.

Necessário ter experiência com métodos de machine learning (classificação, clusterização, regressão, análise de sobrevivência)

### Benefícios

VA + VR
Plano de Saúde e odontológico Amil
PLR
Auxilio Creche para filhos até 5 anos e 10 meses de R$468;
VT
Seguro de Vida.

### Aptidões Técnicas e qualidades

Experiência com métodos de machine learning (classificação, clusterização, regressão, análise de sobrevivência)
Python, Java, ou Julia

### Buscamos Pessoas:

Ágeis, pro ativas, colaborativas, capazes de oferecer soluções e agregar ao time com boas práticas de mercado.

### Labels

Sênior
Alocado

### Candidatar: http://bit.ly/intercientista_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
