### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na PEBMED

### ISSUE THREAD

**Issue by pedrogemal** [backend-br/vagas#58]
**A empresa**

- A PEBMED é uma startup carioca focada em conteúdo médico! Com aplicativos e notícias, temos como propósito ajudar a melhorar a saúde brasileira.
- Nossa missão é prover segurança e confiabilidade através de conteúdos médicos para tomada de decisão profissional.
- 20+ colaboradores
- Ambiente amigável 
- Profissionais jovens, focados e de alto nível técnico

**Descrição da vaga**

Procurando por um trabalho que seja sua segunda casa? Venha fazer parte de uma Startup de tecnologia que quer melhorar a prática médica no Brasil!

**Oportunidade de:**

- Apresentar, utilizar e melhorar práticas de desenvolvimento ágil em uma startup consolidada do Rio de Janeiro;
- Contribuir e colaborar com a equipe e clientes durante todo o processo de desenvolvimento de software;
- Ser parte de um ambiente aberto e não hierárquico onde se espera que todos colaborem dentro do projeto e nas direções da organização.

**O que você vai fazer:**

- Participar no desenvolvimento da maior plataforma médica de tomada de decisãodo Brasil
- Evoluir nossas APIs atuais e construir APIs para terceiros
- O que usamos: Linux Ubuntu, Apache, MySQL, PHP (LAMP), Node.js, Nginx, No SQL (mongoDB)

**Local:**

- Na Rua Voluntários da Pátria, a 10 minutos da estação de metrô de Botafogo, no Rio de Janeiro.
- Horário das 09h às 18h, de segunda a sexta-feira (Presencial).

**Habilidades obrigatórias:**

- Pelo menos 5 anos de experiência na área, sobretudo em projetos ágeis;
- Desenvolvimento de código com organização, modularização e documentação (swagger);
- Capacidade de autogestão e aprendizado rápido;
- Vontade em inovar e melhorar a saúde do Brasil.

**Habilidades desejáveis:**

- Envolvimento com projetos open source/comunidade;
- Vivência em projetos utilizando metodologia ágil (Scrum) e experiência com uso do Jira;
- Experiência com GitFlow;
- Experiência com Laravel 5.5, ExpressJS e MongoDB.

**Habilidades diferenciais:**

- Noções de infraestrutura e arquitetura;
- Experiência prévia com AWS.

**Contratação:**

PJ com benefícios.

**Como se candidatar:**

Por favor envie um email para pedro@pebmed.com.br com seu CV anexado e sua pretensão salarial. Enviar como assunto: Vaga Backend.

> Seja você mesmo, todos os outros já existem. 

Tags: NodeJS PHP PJ Pleno/Senior Full Time Presencial

**Comment by pedrogemal** [comment]
Vaga permanece em aberto!

**Comment by pedrogemal** [comment]
Ainda em aberto!

**Comment by reginaldojunior** [comment]
Vaga preenchida, posso fechar a issue?
