### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na Mutual

### ISSUE THREAD

**Issue by brunosantanarj** [backend-br/vagas#580]
## Descrição da vaga

Como desenvolvedor back-end você vai ter a oportunidade de trabalhar com uma arquitetura de microserviços usando tecnologias como Node.js, Koa, Typescript, ElasticSearch, MongoDB. Inserido em uma equipe ágil,  comprometida com qualidade, eficiência na automatização de processos, robustez, escalabilidade e performance dos nossos sistemas.

Procuramos pessoas engajadas, apaixonadas por tecnologia e que, principalmente, acreditem em nosso propósito disruptivo!

## Local

Centro - Rio de Janeiro (pertinho de duas estações de metrô)

#### Diferenciais

Salário competitivo,
Remuneração variável,
Stock Options,
Home office 3~4 vezes na semana,,
Flexibilidade de horário,
Ambiente informal,
Possibilidade de crescimento,

## Requisitos

**Obrigatórios:**
- JavaScript/ES6+
- Node
- MongoDB

**Desejáveis:**
- TypeScript
- AWS
- Koa
- ElasticSearch

## Contratação

PJ a combinar

## Nossa empresa

A Mutual é uma Fintech que surgiu para revolucionar a forma de realizar investimentos e empréstimos no Brasil, utilizando tecnologia, simplificando a circulação de dinheiro entre pessoas, com maior rentabilidade ao investidor e juros menores ao tomador.

Aqui trabalhamos com tecnologia de vanguarda, em ambiente horizontal e colaborativo, com autonomia e foco nas entregas, sem burocracia e enrolação!

## Como se candidatar

Por favor envie um email para bruno.santana@mutual.club ou fabiana.mansur@mutual.club com seu CV anexado - enviar no assunto: Vaga Back-end Developer[Github]

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
