### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Java no BANCO INTER

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#581]
### Sobre a empresa: Banco Inter

O Banco Inter é o primeiro banco totalmente digital com ações listadas na B3 e o único a oferecer uma conta 100% gratuita. Com uma robusta plataforma de multisserviços, somos um banco prático e completo como os novos tempos exigem.

### Descrição: Ocupações do cargo

Atuar com desenvolvimento de software, com testes automatizados, integração de sistemas, criação e divisão de componentes reutilizáveis, organização de pacotes e padrões organizacionais. .

### Benefícios

VA + VR
Plano de Saúde e odontológico Amil
PLR
Auxilio Creche para filhos até 5 anos e 10 meses de R$468;
VT
Seguro de Vida.

### Aptidões Técnicas e qualidades

JAVA
Spring-boot
JPA
Design Patterns
Microservices (RESTful/like)
Integração Contínua
Jenkins
Git

### Buscamos Pessoas;

Ágeis, curiosas, pro ativas, colaborativas, responsáveis, tenham boas habilidades para comunicação e vontade de inovar.

### Labels:

Pleno
Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
