### ISSUE TITLE
[São Paulo]  Analista Programador VB6 na [RADAR PROFISSIONAL]

### ISSUE THREAD

**Issue by RADARProfissional** [backend-br/vagas#582]
Descrição da vaga:

Estamos procuramos por pessoas apaixonadas por tecnologia.

Local:
São Paulo/SP 

Diferenciais:

Ambiente informal,
Possibilidade de crescimento,

Requisitos:

Superior completo
•	Imprescindível experiência comprovada em Visual Basic 6.0, Banco de dados ORACLE ou SQL SERVER e CRYSTAL REPORTS; 
•	Experiência com programação, interação/contato com usuários (clientes), testes e documentação de sistemas;
•	Será considerado como diferencial, o profissional com conhecimento em .Net, C# e que tenha atuado com produtos de empresas desenvolvedoras de WMS ou ERP; 

Responsabilidades:

Irá fazer análise da atividade e documentação técnica, codificação/formatação/melhores práticas, teste técnico, acompanhamento técnico, apoio a área de suporte, atendimento ao cliente e irá informar a gestão sobre andamento das atividades de suas responsabilidades.

Contratação:
PJ a combinar

Como se candidatar:
Por favor envie um email para talento@radarprofissional.com.br com CV anexado - enviar no assunto: Vaga VB6

Labels
PJ
VB6

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
