### ISSUE TITLE
[Belo Horizonte- MG] Desenvolvedor Full Stack na CADOMA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#586]
### Sobre a empresa: Cadoma

Somos uma empresa do ramo da piscicultura. A nossa missão é automatizar a criação de peixes deixando-a mais tecnológica e viável. Para isso, prestamos consultoria e desenvolvemos produtos inéditos no mercado da aquicultura.

### Requisitos:

Experiência com JavaScript, Java, React e Spring;
Experiência com Linux;
Pró-atividade;
Sangue nos olhos;
Trabalho em equipe e liderança;
Cooperação.

### Diferenciais:

Conhecimento de infra (Web Service);
Cultura de Scrum Master.

### Oferecemos:

Salário compatível com o mercado;
Clima descontraído;
No dress code;
Fazer parte de uma equipe foda e com grande possibilidade de crescimento. :)

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Liderar o time de desenvolvimento.

### Labels:

Alocado
Pleno/Senior

### Candidatar: http://bit.ly/cadoma_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
