### ISSUE TITLE
[São Paulo] Back-End Developer no GetNinjas

### ISSUE THREAD

**Issue by eduardojmatos** [backend-br/vagas#587]
## Sobre o GetNinjas

Somos a maior plataforma de contratação de serviços do Brasil, com mais de 450 mil profissionais cadastrados em mais de 200 tipos de serviço – desde eletricistas até professores de inglês.

Desde 2011, auxiliamos profissionais autônomos e pequenas empresas a encontrarem novos clientes. Geramos mais de R$300 milhões em renda por ano para estes profissionais, que antes dependiam de indicações ou de canais de marketing tradicionais. Por outro lado, também ajudamos clientes em todo o Brasil a encontrarem profissionais confiáveis em menos de 5 minutos – e compararem orçamentos para fechar com aquele que melhor atenda suas necessidades.

Somos uma startup de alto crescimento, que já captou mais de R$ 47 milhões de investimento da Tiger Global, Monashees Capital e Kaszek Ventures – alguns dos mais reconhecidos fundos de venture capital.

## O que esperamos de você?

**Culturalmente você terá um bom fit se:**

- Pensar de maneira simples em como resolver problemas, sempre mantendo a qualidade;
- Resolver problemas que você encontre no meio do caminho. O problema do outro pode ser seu daqui algum tempo;
- Entregar features que agreguem valor ao nosso negócio (diretamente: algo que impacte a vida de nossos clientes e profissionais; indiretamente: melhorando o dia a dia do time de tecnologia);
- Valorizamos muito pessoas que não se apegam apenas a uma tecnologia. Acreditamos que a diversidade de conhecimento faz com que a forma inicial que pensamos a solução de um problema possa ser melhorada.

## Exemplos de desafios que você provavelmente resolverá no dia a dia dentro do GetNinjas:

- Construir e manter micro serviços em Ruby ou qualquer outra linguagem que resolva bem nosso problema;
- Ajudar nosso time de infraestrutura a evoluir nosso processo de deploy, aumentar a resiliência e performance dos nossos sistemas;
- Melhorar e otimizar APIs;
- Medir e criar alarmes para os sistemas críticos do nosso negócio.
- Mentorar outras pessoas do time. Nós evoluímos as pessoas do time e, como pessoa num nível Sênior, será seu dever ser alguém que mentora essas pessoas mais inexperientes.

## Experiências como back-end que valorizamos:

- Experiência com Ruby (mínimo 3 anos) ou alguma outra linguagem orientada a objetos;
- RESTful APIs / GraphQL;
- Mensageria (SQS ou Sidekiq);
- Testes automatizados de unidade / funcional / integração;
- Infraestrutura como código (Docker, Chef, ECS, Terraform);
- AWS;
- Banco de dados SQL (AWS Aurora) e NoSQL (Redis, DynamoDB, MongoDB);
- WebFrameworks (Rails, Sinatra, Grape, Express);

## Adicionais que seriam legais:

- CSS / HTML5
- Conhecimento Android / iOS
- ElasticSearch

## Benefícios

- Remuneração competitiva;
- Plano de saúde;
- Plano odontologico; 
- Vale-Transporte ou estacionamento;
- Vale-refeição;
- Gympass;
- Ambiente divertido e descontraído, com comida no escritório, pet friendly;
- Escritório super bem localizado – você pode vir de bike, metrô, ônibus ou carro: Ficamos a 30 metros da estação Fradique Coutinho;
- Possibilidade de um enorme impacto positivo na maneira como as pessoas usam a internet.

## Como se candidatar
https://jobs.kenoby.com/getninjas/job/engenheiroa-de-software-senior/5bc6197bd282bd6ce23a0811

## Labels

- Alocado
- Aws
- Docker
- Express
- GraphQL
- Pleno/Sênior
- Ruby
- Ruby on Rails
- Redis
- Rest

**Comment by ghost** [comment]
@eduardojmatos há alguma outra maneira de se candidatar? A plataforma não está enviando o meu formulário.

**Comment by eduardojmatos** [comment]
@brFelipe só pela plataforma. Não exibe nenhuma mensagem de erro ao enviar? Porque recebemos algumas aplicações já, parece tudo ok 🤔

**Comment by ghost** [comment]
@eduardojmatos após preencher todo o formulário e clicar no botão de envio não acontece nada. Tanto o formulário não parece ter sido enviado como nenhuma mensagem é apresentada para mim. Seja pela UI ou no console.
Eu tentei algumas vezes ontem a noite, e mesmo agora de manhã eu continuo não conseguindo enviar.

**Comment by eduardojmatos** [comment]
@brFelipe caramba, que bizarro :(

O único modo pra aplicar é por esse processo... Tenta usar algum browser diferente ou uma aba anônima

**Comment by eduardojmatos** [comment]
Fechando pra reabrir, menos focado em Ruby
