### ISSUE TITLE
[Remoto] Vagas para freelancer em Java no SlicingDice

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#588]
## Descrição da vaga

Estamos em busca de desenvolvedores Java com mais de 5 anos de experiência e que tenham interesse em prestar serviço freelancer (remoto) para nossa empresa (SlicingDice).

**Observações importantes:**
- O profissional precisa ter disponibilidade de pelo menos 2 a 3 horas por dia, todos os dias;
- As horas de trabalho freelancer precisam ser realizadas entre 8:00 AM e 22:00 (Brasília), pois as tarefas demandarão constante interação com nossa equipe, dada a complexidade do projeto/código;
- O nosso code coverage é acima de 90%, além de termos testes unitários e integrados rodando para cada commit no CircleCI.
- O código está muito bem documentado.
- Todas as pessoas passarão por um treinamento técnico completo antes de começar a codificar.

Por favor, caso tenha interesse, peço gentilmente que envie um email para java@slicingdice.com com seu CV ou LinkedIn e seu valor por hora para prestação de serviços.

Qualquer dúvida, estamos à inteira disposição.

## Local

Remoto ou Escritório São Paulo - Chácara Santo Antônio.

## Benefícios

Nenhum.

## Requisitos

Experiência com programação em Java há mais de 5 anos.

## Contratação

Prestação de serviço (PJ), trabalho freelancer.

## Nossa empresa

Veja aqui:
https://www.slicingdice.com

## Como se candidatar

Por favor, caso tenha interesse, peço gentilmente que envie um email para java@slicingdice.com com seu CV ou LinkedIn e seu valor por hora para prestação de serviços.

Qualquer dúvida, estamos à inteira disposição.

**Comment by soutothales** [comment]
Enviado!

**Comment by walteraa** [comment]
@vagasarrombadas

**Comment by gmenegatti** [comment]
É impressionante perceber a que ponto chegamos.

É um absurdo pensar que existem pessoas que, se não concordam com algo,
além de censurar o **direito** da outra pessoa falar, também não aceitam ou
concordam que outras pessoas possam pensar de maneira diferente. Em outras
palavras, se eu não gosto dessa vaga ou quero isso para minha vida, ninguém
pode gostar ou querer. Onde fica o livre-arbítrio?

Se o problema é "por quanto" você vai se vender, pode ter certeza que as
pessoas que estão conosco ganham e ganharão mais dinheiro do que você possa
imaginar, ainda mais por terem a chance de serem sócias/donas do negócio.
Já viu pessoas com apenas 22 anos ganhando participações que equivalem a
mais de R$ 1 milhão? Eu não acho que seja um mau negócio.

Jamais foi nosso desejo contentar a todos. Escolhemos contentar quem
compartilha dos mesmos desejos e objetivos que temos.

**Comment by walteraa** [comment]
Amigão, ter livre arbítrio não muda o fato de algo ser escroto.

Basta ler isso aqui: https://github.com/backend-br/vagas/issues/778

**Comment by gmenegatti** [comment]
Sem comentários adicionais. Acho que temos entendimentos diferentes sobre o
que significa respeito a opinião do outro e livre-arbítrio.

Eu respeito e entendo sua maneira de pensar, ela só é diferente da minha.

**Comment by overdadeiro** [comment]
@gmenegatti você respeita tanto a opinião e o modo de pensar alheio, que ao invés de responder de forma pensada como você fez agora, você respondeu com gracinha e ironia, acho que pelo menos o meu alerta de que você deveria pôr a mão na consciência e pensar surtiu algum efeito nessa sua manifestação aqui

Veja bem, eu particularmente não sou contra a sua proposta, como falei lá apenas queria expressar minha opinião e talvez servir de alerta pra outras pessoas

**Comment by LuizSimonard** [comment]
@gmenegatti 

Aqui uma critica construtiva pra evitar post estilo vagas arrombadas.

1. Ler lei trabalhista antiga e nova
2. Deixe claro o salario e benficios da vaga, não omita a informação, isso so passa a ideia que você ta tentando esconder enganar a pessoa
3.  **extrema** cobrança e pressão. - nunca fale isso voce so vai passar a ideia que voce vai tratar o funcionario como lixo.
4. * Topem 10 horas por dia (as vezes, até no fim de semana) pelos próximos 6 meses. voce oferece pj remoto com o limite de 8 as 22 horas, vo tira todo o tempo da pessoa para viver alem do trabalho. cara ninguem é robo, a pessoa precisa de dinheiro mas ainda sim precisa viver, é um absurdo ver isso.
5. voce escreve no trecho de contra partida de forma agressiva, se a pessoa lê o que tu disse encima e ver isso tudo que vc ta escrevendo agora a pessoa ja sabe que voce vai chingar ela se algo der errado, por pura interpretação.
6. voce so comenta **possibilidade** de participação é bem possivel de não receber pela forma que voce comenta as coisas a cima 

agora uma coisa pra ficar mais claro, voce perde tempo discutindo e reabrindo a vaga. tentando esconder o que voce disse antes isso so deixa claro o como voce não é do BEM e quanto voce quer passar a perna num PJ

**Comment by walteraa** [comment]
Colocação perfeita, @LuizSimonard!!!! 

Precisa nem de complemento. Hahaha

**Comment by onhernandes** [comment]
Vou deixar meu posicionamento aqui, como organizador do BackEndBrasil: o projeto em si é baseado na ideia de criar uma comunidade saudável. E isso implica diretamente com as vagas que oferecemos pra galera. 

Ano passado houve um caso bem parecido de uma vaga abusiva e fechamos.

Assim vamos fazer com vagas anunciadas, perguntas no fórum, issues e PRs abertos, o que for nocivo será fechado aqui. 

Nós queremos o melhor pra comunidade. Sempre foi assim e sempre vai ser assim.

Siga as dicas do @LuizSimonard caso queira anunciar uma vaga aqui novamente - e obrigado pelo comentário :heart:

**Comment by mariovalney** [comment]
> @vagasarrombadas

Achei que a galera do Vagas Arrombadas tinha GitHub rsrs

**Comment by xspager** [comment]
"Já viu pessoas com apenas 22 anos ganhando participações que *equivalem* a
mais de R$ 1 milhão?"
