### ISSUE TITLE
[São Caetano do Sul - SP] Desenvolvedor Pleno C#

### ISSUE THREAD

**Issue by kvilela** [backend-br/vagas#589]
**Local**
Escritório, São Caetano do Sul - SP

**Benefícios:**
– Assistência Médica Bradesco (Cobertura Nacional 100%)
– Assistência Odontológica Sulamérica (Cobertura Nacional 100%)
– Seguro de Vida
– Vale Transporte
– Vale Alimentação ou Refeição
– Lanches / Café da Manhã / Frutas
– Vale Presente no Aniversário, Casamento e Nascimento de Filho
– PINC – Programa de Indicação de Novos Colaboradores
– Comemoração em Datas Especiais
– Parcerias com Instituições de Ensino, Universidades, Cursos de Idiomas, Farmácias, Restaurantes entre outros estabelecimentos
– Desconto no Estacionamento Local
– No Dress Code

**Requisitos:**
Conhecimentos em aplicações client/server e arquiteturas corporativas, não só REST;
Conhecimento em desenvolvimento de   aplicações cloud native AWS (EC2, BeanStalk, SQS, SNS, Load Balancer, RDS,   Dynamo);
Experiência com um ou mais frameworks JS como: Angular, jQuery, React e/ou Node.js;
Experiência em desenvolver um software através de Continuous Delivery;  Expriência em TDD/BDD;
Experiência com aplicações de alto-desempenho
Conhecimentos em geradores de build (CMake, QMake, etc) e configuração

**Atividades:** 
•Desenhar e implementar arquiteturas micro-services 
•Desenvolver sistemas com visão orientada a automação de testes; 
•Diagnosticar e corrigir falhas/bugs no sistema 
•Aplicar práticas como code review e pair programming; 
•Desenvolver projetos/produtos utilizando metodologias ágeis; 
•Monitorar tendências e tecnologias para contribuir com a melhoria de processos relacionados ao desenvolvimento dos produtos da empresa

**Contratação**
CLT (contratação direta no cliente)

**Nossa empresa**
A **Foco em Você** empresa especializada em contratação de talentos de TI e Design Cultural para empresas que desejam aumentar os resultados de seus negócios, através de talentos, competências e habilidades, estamos auxiliando um Cliente na contratação de um Desenvolvedor Pleno Fullstack C#.
**Nosso Cliente**:  Empresa especializada em desenvolvimento de Software para gestão de hospitais, policlínicas, laboratórios e centros de diagnóstico por imagem.

**Como se candidatar**
Por favor envie um e-mail para karina.vilela@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Pleno Fullstack C# (github/C#)

Labels
Presencial
CLT
Pleno
PLR 
VT
VR
Horário Flexível

**Comment by X-X-Xavito** [comment]
Olá!

Queria saber se vocês também tem vaga para estágio.

Abs.

**Comment by kvilela** [comment]
@X-X-Xavito tudo bem? no momento não temos vagas de estágio, mas envia o seu CV, a todo momento surge vagas em nossos clientes.

**Comment by kvilela** [comment]
Vaga encerrada
