### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Django Pleno na VERT Capital

### ISSUE THREAD

**Issue by ggteixeira** [backend-br/vagas#590]
# ANALISTA PLENO [PRESENCIAL]

## DESENVOLVIMENTO DE SOFTWARE

Somos uma boutique do mercado de capitais prestadora de serviços financeiros para empresas e investidores. Nossa companhia preza pela cooperação, análise crítica, flexibilidade, comunicação e engajamento.

#### PERFIL

- Experiência em liderança de equipes de desenvolvedores, proatividade e cooperação
- Interesse em arquitetura e qualidade de software
- Cuidado com a manutenibilidade e testabilidade do código legado e novas funcionalidades
- Experiência com refatoração e conhecimentos avançados em Python, Django, JavaScript e PostgreSQL,  Heroku e outras ferramentas da cultura DevOps

#### DESCRIÇÃO DA VAGA

- Levantamento de especificações e modelagem da arquitetura de novas funcionalidades do sistema
- Refatoração e remodelagem de código legado, com foco na performance da aplicação
- Auxiliar na gestão da área, acompanhando as atividades da equipe e coordenando a resolução e validações dos problemas

#### SALÁRIO

- De R$ 5.000,00 a 7.500,00 + bônus de até R$ 70.000,00
- VR + VT
- Convênio médico
- Auxílio Educação

**Envie currículo para rh@vert-capital.com**

![analistapl_ti_branco_margem_verde_70](https://user-images.githubusercontent.com/24235344/48281198-fd154380-e43c-11e8-9271-db5bc89fadc0.jpg)

**Comment by silasvasconcelos** [comment]
Remoto?

**Comment by ggteixeira** [comment]
> Remoto?

Presencial.

**Comment by silasvasconcelos** [comment]
> > Remoto?
> 
> Presencial.

OK, obrigado.

**Comment by ggteixeira** [comment]
> > > Remoto?
> > 
> > 
> > Presencial.
> 
> OK, obrigado.

Imagina :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
