### ISSUE TITLE
Desenvolvedor PHP Backend/Full-Stack

### ISSUE THREAD

**Issue by nerdmonsterdigitalretail** [backend-br/vagas#5903]
### **Descrição da vaga**
A NerdMonster Digital Retail, empresa em crescimento acelerado e líder em seu segmento, está a procura de desenvolvedores apaixonados por desafios envolvendo programação e que está sempre atualizado com as evoluções das tecnologias do mercado.

Somos uma empresa em construção, então aqui o aprendizado é constante e você terá pista livre para criar e muitos (muitos mesmo!) desafios.

Nossas stacks são basicamente React, PHP 5.6+ com Laravel, Lumen e CodeIgniter 3+, Node.js, MySQL, MongoDB e Jquery.

Buscamos ativamente profissionais capazes, motivados a procura de novos desafios através da programação.

### **O que você vai fazer?**
Desenvolvimento de projetos com arquitetura de microserviços e API's;
Utilização e consumo de API Restful;
Implementação de novos recursos na aplicação;
Criação de algoritmos e implementação de regras de negócio;
Correção de eventuais bugs da aplicação em produção;
Integrações com plataformas de serviços.

**### Obrigatórios:**
> Ter a nossa cultura;
> Experiência com gestão de equipes;
> Analise de indicadores para tomada de decisão;
> Experiência com o Framework Laravel 5.6+
> Experiência com o Framework CodeIgniter 3+
> Experiência mínima de 4 anos atuando como desenvolvedor;
> Experiência com PHP >= 5.6 avançado (OOP, design patterns e boas práticas);
> Experiência com Node.js;
> Banco de dados MySQL/MongoDB;
> GIT e versionamento;
> Linux e Apache (pode ser básico);
> Habilidade de comunicação e de trabalho em time.

**### Desejáveis:**
> Experiência com AWS (S3, SQS, EC2) e deploy;
> Experiência com o Framework CodeIgniter 3+;
> Experiência com Docker.

**### Diferenciais:**
> Conhecimento em APIs Sociais (Facebook);
> Experiência com React;
> Conhecimentos em estatística;
> Conhecimento em APIs de Ads (Facebook Ads e/ou Google AdWords);
> Proatividade para resolução de problemas;
> Código limpo e organizado;
> Proatividade para resolução de problemas;
> Cultura Scrum;
> Ter trabalhado no desenvolvimento de sistemas web - experiências em outras startups seria um diferencial;
> Espírito de equipe.

### **Local**
Remoto/Híbrido

### **Como se candidatar**
Candidate-se através do link: https://www.linkedin.com/jobs/view/2564979481/

### **Labels**
PJ
Remoto
Híbrido
Júnior
Pleno
Sênior

**Comment by nickFelix** [comment]
Muito boa essa empresa!

**Comment by nickFelix** [comment]
Continuamos à procura
