### ISSUE TITLE
SÃO PAULO - DESENVOLVEDOR NODE - RESOURCE

### ISSUE THREAD

**Issue by POLLEZI** [backend-br/vagas#591]
Desenvolvedor Nodes / NET
## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países. 
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga
NODES ; C Sharp; Dot Net; Angular,

## Tipo de contratação
CLT – tempo indeterminado

## Benefícios
VR ( 440,00) , VT, Convenio Médico Amil Blue 400 apto – co-participação, Convenio Odontológico Porto Seguro, Auxilio Creche, Convenio Farmácia, Seguro de Vida

## Local
Interlagos - SP

## Como aplicar
Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Desenvolvedor Node

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
