### ISSUE TITLE
[Remoto ou São Paulo] Back-end Developer @ LinkApi Solutions

### ISSUE THREAD

**Issue by mateus4k** [backend-br/vagas#5920]
## Nossa empresa

LinkApi é a nova experiência para desenvolvedores e empresas em todo o mundo que visam sua transformação digital usando APIs e integrações. Nossa plataforma unifica os conceitos de Gerenciamento de API e iPaaS (plataforma de integração como serviço).

Tudo começou quando nosso CEO percebeu que inúmeras empresas tiveram experiências traumáticas em relação às integrações de sistemas e, por isso, muito do potencial para isso foi deixado para trás. Como profissional de tecnologia experiente, ele reuniu os melhores desenvolvedores que conhecia e eles desenvolveram o que é o LinkApi hoje. Pouco tempo depois, os primeiros clientes da LinkApi começaram a ver o quanto essa plataforma poderia impulsionar seus negócios, por isso foram feitos esforços para o crescimento da empresa e do produto. 

Estamos vivendo uma jornada incrível e crescendo em ritmo acelerado. A razão para isso é o nosso povo, e queremos que os melhores se juntem a nós em nossa missão. Estamos à procura de um indivíduo criativo, comprometido e apaixonado pela tecnologia . Se o nosso código de cultura se adequar às suas crenças, não hesite e faça parte da #kapifamily

## Descrição da vaga

Exemplo: Back-end NodeJs Junior ou Pleno

**Responsabilidades:**
- Desenhar e desenvolver APIs e Integrações utilizando as melhoras práticas de desenvolvimento
- Realizar reuniões com o cliente para entendimento de cenário, mapeamento de novas demandas, homologações e etc

## Local

Exemplo: Remoto ou Escritório, São Paulo

## Requisitos

**Obrigatórios:**
- Conhecimento de arquitetura e boas praticas de desenvolvimento de software
- Conhecimento avançado em JavaScript/NodeJS
- Conhecimento em banco de dados NoSQL e SQL
- Boa comunicação escrita e verbal
- Inglês Técnico

**Diferenciais:**
- Fluência em inglês

## Benefícios
- Vale Refeição Flash
- Vale Alimentação Flash
- Seguro de vida em grupo
- Plano de Saúde Amil
- Parceria com universidade e plataforma de educação
- Gympass
- English in Company
- Treinamentos soft e hard skills in house

## Contratação

CLT

## Como se candidatar

Se inscreva através do link: https://linkapisolutions.gupy.io/jobs/856922

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by MuriloFRL** [comment]
Se tiver algum outro meio de se candidatar ao processo seletivo gostaria de poder me inscrever, essa GUPY é muito mal vista no cenário, além de não dar feedback o algorítimo para seleção de candidatos é deplorável.

**Comment by RobsonCrLira** [comment]
Me candidatei para essa vaga há mais ou menos duas semanas e não passei da fase de teste de perfil e a Gupy não me libera para refazer o mesmo, dificil...

**Comment by mateus4k** [comment]
Obrigado pelo feedback sobre a Gupy, pessoal. No momento as candidaturas são apenas através deste link mas encaminhei o feedback de vocês para o time responsável.
