### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na [B2w Digital]

### ISSUE THREAD

**Issue by MalletJorge** [backend-br/vagas#593]
#We are Hiring 
- Let's Elevate 

Você irá ajudar a criar a melhor experiência para os usuário dos maiores e-commerces da América Latina, como Americanas.com, Submarino e Shoptime.

Se você é um entusiasta de novas tecnologias, gosta de aprender, ensinar e desenvolver produtos que estão no dia a dia da galera, então tem o perfil que queremos para o nosso time!

##Local
BIT Mauá - Centro RJ
Rua Sacadura Cabral 130, Saúde, Rio de Janeiro.

##Benefícios
Plano de Saúde
Plano Odontológico
Seguro de Vida
Vale Refeição ou Alimentação de R$ 24,30/dia
Vale Transporte
10% de desconto nos sites da Americanas.com, Submarino e Shoptime

##Diferenciais
Ambiente de trabalho descontraído
Dress code informal (bermuda!)
Sinuca e video games
Flexibilidade de Horário
Trabalhamos com metodologias ágeis (Scrum)
Estamos sempre em busca de inovação
Não desenvolvemos apenas software, também desenvolvemos pessoas smile

##Coisas que usamos:
Java, Clojure, Go, Javascript, Python
MongoDB, Riak, Datomic, DynamoDB
Microserviços em REST APIs
Amazon AWS
CI / CD
Testes automatizados

##Contratação
CLT - a combinar

##Nossa empresa
B2W INOVAÇÃO E TECNOLOGIA

Somos o BIT, a área de inovação e tecnologia da B2W. Desenvolvemos os sites da maior empresa de e-commerce da América Latina, além das plataformas Marketplace e Mobile.

A B2W Digital está crescendo rapidamente com aquisições de novas empresas e com projetos de alta escalabilidade e impacto. Trabalhamos com as tecnologias mais modernas em um ambiente diferenciado. Buscamos pessoas com pensamento inovador, movidas a desafios e antenadas com as novidades do mercado.

##Como se candidatar
Gostou? Para se cadastrar basta entrar no link  https://b2w.gupy.io/jobs/7956
- Dicas para cadastro
   - Importe o CV do linkedin (PDF) 
   - Detalhe o máximo possível as suas experiências

Boa sorte

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
