### ISSUE TITLE
[São José dos Campos - SP] Desenvolvedor Full Stack na Tony Veículos

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#594]
### Sobre a empresa: Tony Veiculos

Entre as 2 maiores lojas multimarcas do Brasil a Tony veículos sempre manteve uma visão inovadora no mercado. hoje acreditando na transformação digital para inovar e transformar a relação de compra e venda de veículos. Com 40 anos de experiencia no mercado e uma grande quantidade de conhecimentos podendo ser parametrizados para assim o escalonamento para atendimento nacional. projeto de expansão digital. Missão: Revolucionar a compra e venda de veículos no Brasil.

### Descrição: Ocupações do cargo

Trabalhar em equipe para desenvolver o sistema e criação de sites, inicial sera uma equipe de 2 pessoas com a demanda que temos teremos que crescer a equipe.

### O profissional deverá ter conhecimento nas seguintes linguagens:

HTML 5
CSS 3
JavaScript
jQuery
PHP
BootStrap
Será considerado diferencial o profissional que apresentar conhecimento em Python.

### Benefícios

Possibilidade de crescimento muito grande na empresa e oportunidade de sociedade!

### Aptidões e qualidades

O profissional deve ser proativo, autodidata, ativa e sempre ter a vontade de aprender cada vez mais.

### Informações complementares

Criar uma empresa de tecnologia focado em testes e melhorias dos nossos processos

### Labels:

Alocado
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
