### ISSUE TITLE
[São Paulo] Node/Python Developer na MagazineLuiza [LUIZALABS]

### ISSUE THREAD

**Issue by ogustavomeira** [backend-br/vagas#595]
### Descrição da Vaga
O Luizalabs é o laboratório de inovação e tecnologia do Magazine Luiza. Temos três pilares que são a base do nosso negócio: Gente, Inovação e Código. Somos apaixonados por tecnologia e nosso propósito é melhorar a experiência de compra do nosso cliente.

### Requisitos
- Node.js 
- Python 
- Java (JavaEE, Spring boot) 
- Design de APIs REST 
- TDD, DDD, BDD 
- NoSQL 
- Experiência com AWS, Google Cloud ou ambientes multi cloud 
- Integração e deploy contínuo 
- Micro serviços 

Diferenciais:
 - Go 
- Angular.js ou react
- Forte conceito SRE

### Local
Rua Maria Prestes Maia, 300 - Luizalabs / São Paulo-SP

### Benefícios

- Vale Transporte
- Vale Refeição
- Seguro de Vida
- Previdência Privada
- Assist. Odontológica
- Assist. Médica
- PLR

### Labels
CLT 
Pleno
Sênior
Python
NodeJS

### Inscreva-se em
Acesse ao link e aplique na vaga! Nosso time de Recrutamento entrará em contato!
https://www.99jobs.com/luizalabs/jobs/29601-desenvolvedor-a-pleno

Se preferir, envie email para stefanie.cavalcanti@magazineluiza.com.br com seu CV + Pretensão.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
