### ISSUE TITLE
[Remoto ou presencial] Senior Back-end Developer no iFood

### ISSUE THREAD

**Issue by glaydsonarantesp** [backend-br/vagas#5950]
## Nossa empresa

iFood is the biggest and fastest growing FoodTech company in Latin America, operating in Brazil and Colombia. We aim to make people live more convenient and joyful, by simplifying and disrupting the way they eat through applied technology.As a Software Engineer, you will design, code, test and operate microservices that runs iFood's core business logics. Furthermore, you will also help us building frameworks and tools for identifying performance bottlenecks (eg: Load testing, Chaos engineering), measuring, monitoring and optimizing our backend performance to ensure high availability, scalability and fault tolerance, directly impacting the life of millions of people, daily!

## Descrição da vaga

Design, code, test, operate and solve production problems on services running on the cloud (specially AWS);
Participate in product evolution prioritization, always looking to the best value gains to the business, basing your decisions on data;
Face and solve scalability, maintainability and reliability challenges;

## Local

- Remoto
- Presencial (Quando reabrir 🙏)
- Temos parceria com diversos coworkings espalhados pelo Brasil ;)

## Requisitos

**Obrigatórios:**
- Passionate about software development, Object Oriented and Functional programming;
- Automated Tests, Distributed Systems and Secure Development concepts;
- Relational and NoSQL databases, queries and data modeling experience;
- Knowledge on Linux, Infrastructure as Code, Networking, Docker, Kubernetes;
- Prior experience dealing with applications that supports millions of transactions per day, 24 hours a day, 7 days a week;
- Experience with asynchronous communication between services and concurrency challenges on distributed systems.

## Benefícios e Diferenciais:

Veja [em nosso site de Carreiras](https://carreiras.ifood.com.br/) todo o que o iFood tem a te oferecer :)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para glaydson.arantes@ifood.com.br com o link do seu LinkedIn - enviar no assunto: Vaga Back

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by fabianosanttana** [comment]
Faala Glaydson, massa demais esse repo de vocês para as vagas, iFood é uma das melhores mesmo. Só achei um pouco estranho a mistura dos idiomas na issue
