### ISSUE TITLE
[Remoto] Back-end Developer - Elixir/Phoenix @ Delivery Center

### ISSUE THREAD

**Issue by limakayo** [backend-br/vagas#5955]
## Nossa empresa

**Estamos revolucionando o varejo e você pode fazer parte disso** 🚀

Nosso propósito é transformar milhões de negócios e impactar vidas, construindo um ecossistema saudável.
Uma rede formada por nossos colaboradores, lojistas, marketplaces, entregadores, acionistas e shoppings.
Somos uma empresa GREAT PLACE TO WORK, ou seja, somos uma das Melhores Empresas pra se Trabalhar, isso é conquista do time de pessoas fantásticas que temos no D e que amam o que fazem.
Estamos mudando o mercado e construindo uma cultura incrível.
Esse é o nosso jeito, essa é a Nossa Vibe!

## Descrição da vaga

No Delivery Center você vai:

- Aprender muito todos os dias;
- Trabalhar com um time com experiência em desenvolvimento de produtos globais;
- Fazer parte de um projeto que transforma positivamente a vida das pessoas;
- Conviver com pessoas em um ambiente informal, em uma hierarquia horizontal e flexível.

Nosso pessoal de desenvolvimento tem um ambiente interativo. O time participa das nossas novas ideias, aprendizados e decisões do dia a dia. Nosso time é leve e bem humorado. Assumimos riscos com responsabilidade, crescemos rápido e confiamos que estamos fazendo o nosso melhor a cada entrega.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Conhecimento em Elixir/Phoenix para Backend; arquitetura REST, arquitetura de backend, avaliação e implementação de novas tecnologias, bancos de dados relacionais (PostgreSQL e/ou MySQL), testes (TDD, BDD);
- Conhecimento em linguagem funcional;
- Experiência com ferramentas de versionamento (github); 
- Experiência com metodologias ágeis;

**Diferenciais:**

- Kubernetes;
- Microservicos;
- Kafka / RabbitMQ;
- GraphQL.
- Vivência com Sidekiq, Redis e RSpec, ferramentas AWS / Google Cloud(Auto Scaling, Docker) e conhecimentos com NodeJS e JavaScript; 
- Integrações entre sistemas de marketplaces, e-commerces e varejo em geral;
- Experiências em empresas de tecnologia ou startups.

## Benefícios

- Assistência Médica
- Assistência Odontológica
- Programa de Participação nos Resultados (PPR)
- Seguro de Vida
- Vale Refeição/Vale Alimentação
- Vale Transporte
- Convênios e Parcerias com diversas instituições

## Contratação

CLT

## Como se candidatar

Por favor, candidate-se pelo Gupy: https://deliverycenter.gupy.io/jobs/627692?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dia após cada processo.
E-mail para contato em caso de não haver resposta: kayo@deliverycenter.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by nelsonmfinda** [comment]
Fala @limakayo, sou de Angola. Não tenho CNPJ ou carteira de trabalho, posso me candidatar?
