### ISSUE TITLE
[Rio de Janeiro]: Back-End Developer Pleno/Senior

### ISSUE THREAD

**Issue by caueops** [backend-br/vagas#596]
## Descrição da vaga

```javascript
Se você >>
    É uma pessoa, acima de tudo!
    É engajado(a) por Qualidade de Software
    Ama CODAR
    Curte a cultura de Ownership
    Compartilha conhecimento
    Ama CODAR
    Curte aprender, através de (treinamentos && cursos && eventos && livros)
    For receptivo(a) à feedbacks contínuos
    Ama CODAR
    Curte a cultura de DevOps
    Prefere metodologias ágeis
    Ama CODAR
>> Continue lendo...
```

Estamos começando a expandir os nossos times e precisamos de pessoas que realmente gostam de estar à frente do mercado, aquelas que curtem experimentar novas tecnologias e que estão sempre antenadas ao cenário atual do desenvolvimento back-end. A nossa missão é de criar equipes de ponta, que estejam engajadas em superar seus próprios desafios.

Um pouco das atribuições desse papel:
- Participar de times multidisciplinares
- Codificar
- Participar de discussões sobre a evolução do time
- Participar de discussões de produto
- Decisões de arquitetura
- Definições de workflow

E se você se interessa em participar da migração de uma arquitetura monolítica para *Headless* utilizando *microservices* com o Design Orientado a Domínio (DDD) ou até mesmo participar da criação e do desenvolvimento de um novo produto, venha fazer parte do nosso time \o/

## Local

Alocado no escritório: Shopping Downtown - Barra da Tijuca - Rio de Janeiro - RJ

## Benefícios

- Vale Refeição ou Vale Alimentação (cê que escolhe) de R$30,00/dia útil.
- Participação nos Lucros (Anual).
- Seguro de vida.
- Plano de Saúde (SulAmérica)
- Licença maternidade e paternidade estendida.
#### Diferenciais

- Cultura de Qualidade no workflow de desenvolvimento (TDD, DDD, Pair Programming, Code Review).
- Treinamentos com especialistas (internos ou externos).
- Material de suporte aos estudos (cursos, livros, etc).
- Incenvito à participação de eventos.
- Ciclo de feedback contínuo (Avaliação 360º, 1:1 meetings).
- Sessões de Meditação e Mindfulness.
- Acesso às análises, cursos, jogos e serviços do Personare.
- Suco verde e frutas de manhã e à tarde.
- Cadeira de massagem.
- Convênio com restaurantes próximos
- Flexibilidade de horário
- Disponibilização de um MacBook para o trabalho

## Requisitos

**Obrigatórios:**
- PHP com um bom conhecimento de Programação Orientada a Objetos (POO).
- Testes de unidade e integração.
- Conhecimento com banco de dados relacional (MySQL/PostgreSQL).
- Se importar com a qualidade do código que está fazendo.
- Ter conhecimento de padrões de projeto e saber aplicá-los na prática.
- Workflow de desenvolvimento utilizando controle de versão (Git de preferência <3).
- Proatividade para resolver problemas e/ou impedimentos do dia a dia.
- Valorizar a cultura de desenvolvimento Ágil.
- Experiência com setup/tunning do servidor de aplicação Nginx.

**Desejáveis:**
- Experiência com arquitetura de *Microservices*
- Ter o conhecimento de técnicas de *Refactoring*.
- Conhecimento de operações básicas no Docker (run, stop, rm, kill, pull e push).
- Interesse pelas temáticas do Personare.

**Diferenciais:**
- Experiência com arquitetura *Headless*.
- Experiência com Domain Driven Design (DDD) <3 <3 <3 
- Ter o conhecimento do S.O.L.I.D e conseguir colocá-los em prática. 
- Praticar desenvolvimento guiado por testes (*Test Driven Development*)

## Contratação

CLT

## O Personare

<p align="center">
  <a href="https://www.personare.com.br/" target="_blank">
    <img src="https://user-images.githubusercontent.com/7065285/46258596-e249c980-c4a3-11e8-894c-14381df00fad.png" alt="Pesonare" width="70%">
  </a>
</p> 

O Personare é resultado do trabalho de jovens profissionais de diferentes especialidades, mas com uma mesma motivação: incentivar as pessoas a viverem suas vidas da melhor forma possível. Para isso, oferecemos conteúdos e serviços focados em qualidade de vida e autoconhecimento como: Astrologia, Tarot, Yoga, Meditação, Feng Shui e muitos outros.

Veja alguns bons motivos para se juntar a nós:

1. Influenciamos positivamente a vida de mais de um milhão e meio de pessoas que acessam o Personare todos os meses.

2. Aqui todos têm voz: prezamos que todas as opiniões e ideias sejam ouvidas. Até mesmo (e principalmente) as dos estagiários.

3. Nosso design e comunicação são feitos internamente. Você nunca vai ficar entediado trabalhando em uma empresa que é uma agência ao mesmo tempo.

4. Motivamos a amizade e a colaboração entre a equipe. Isso significa que todos têm boa vontade em explicar, ensinar, compartilhar tarefas e celebrar conquistas.

5. Agimos para que o bem-viver e o autoconhecimento não sejam um discurso somente. Praticamos o que pregamos: possuímos programas que incentivam que nossa equipe melhore sua própria qualidade de vida.

## Como se candidatar

Por favor me mande um sinal de fumaça através do email: queroserdev@personare.com.br com qualquer coisa (GitHub, Código, Projeto, se quiser marcar um café ou uma call)! \o/

## Labels

- Alocado
- Remoto - Parcial
- Sênior
- Pleno
- CLT

**Comment by samuelfaj** [comment]
Olá pessoal, e-mail enviado!

\o/
