### ISSUE TITLE
[São Paulo] Analista Arquitetura/Gateway APIs no Torq (www.labtorq.com.br)

### ISSUE THREAD

**Issue by mbradaschia** [backend-br/vagas#597]
Estamos buscando um profissional para atuar ativamente no nosso projeto de gateway de APIs para o mercado. Buscamos uma pessoa com experiência comprovada no tema, potencial e vontade de crescer conosco!

Atividades:
* Apoiar o desenho e desenvolvimento da arquitetura de gateway de APIs, considerando requisitos técnicos e de negócios
* Realizar configurações técnicas do ambiente
* Apoiar o desenho de APIs de soluções a serem conectadas no gateway
* Analisar diferentes soluções internas e de mercado e identificar melhores maneiras de conectá-las ao gateway

Perfil:
* Experiência comprovada em projetos de gateway, arquitetura de sistema, considerando critérios de segurança, escalabilidade, custo, entre outros
* Experiência comprovada em desenvolvimento de APIs REST
* Conhecimento em Javascript, NodeJS, HTML 5, CSS
* Capacidade de compreender necessidades de negócios e encontrar caminhos técnicos para solucioná-las
* Pró-atividade
* Inglês mínimo intermediário

www.labtorq.com.br

**Comment by MarcosDias** [comment]
Olá Marcelo, existe a possibilidade de ser remoto?

**Comment by mbradaschia** [comment]
> Olá Marcelo, existe a possibilidade de ser remoto?

Oi @MarcosDias, blz? Infelizmente não... é um projeto intenso e tem muita coisa pra ser especificada em conjunto.

**Comment by MarcosDias** [comment]
Muito obrigado pelo retorno @mbradaschia .

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
