### ISSUE TITLE
[São Paulo] BackEnd Developer na KANAMOBI 

### ISSUE THREAD

**Issue by nathaliagoldenberg** [backend-br/vagas#599]
## Descrição da vaga

A KANAMOBI ajuda a construir empresas digitais! Venha fazer parte desse movimento!

![devs backend](https://user-images.githubusercontent.com/40583512/48499786-59eb7200-e820-11e8-9c0c-bb0f9d4902c2.png)

## Local

Escritório, São Paulo - BARRA FUNDA (próximo ao metrô)

## Benefícios

- Horário Flexível;
- 13º;
- 30 dias de férias remuneradas;
- Participação nos lucros c/ avaliação a cada 6 meses;
- 50% do convênio médico de escolha do funcionário.

#### Diferenciais

- Oportunidades de participar de decisões estratégicas da empresa;
- Trabalhar com pessoas extraordinárias;
- Ambiente de muito aprendizado;
- Horário Flexível;
- Contratação PJ + benefícios.

## Requisitos

**Desejáveis:**

- Experiência comprovada com pelo menos uma das seguintes linguagens: Ruby, JS (Node), Elixir ou Go.
- Experiência com pelo menos um dos seguintes bancos de dados: Oracle, PostgreSQL, MySQL.
- Experiência com times e práticas ágeis (Pair Programming, Code Review).
- Trabalhar com metodologias ágeis como SCRUM e KANBAN
- Experiência com AWS, Redis, NoSQL (MongoDB).
- Experiência com MicroServices, Dockers, Distribute Systems Patterns.
- Experiência com CICD(Jenkins, CircleCI).
- Prática de TDD usando testes unitários e E2E.

**Diferenciais:**

- Conhecimento de programação funcional.
- Conhecimento de Ruby on Rails ou Phoenix Framework
- Noção de arquitetura orientada a filas/eventos
- Conhecimentos de programação Orientada à Objetos 

## Contratação

PJ
-13º
-30 dias de férias remuneradas
-Participação nos lucros c/ avaliação a cada 6 meses.
-50% do convênio médico de escolha do funcionário.

## Nossa empresa

Fundada em 2009 a Kanamobi é referência em tecnologia criativa com foco em mobilidade.

"Os nossos maiores ativos são os kanamobers, pois trabalhamos em uma estrutura horizontal e colaborativa, atuando de forma simplificada, onde todos podem compartilhar e discutir quais os melhores caminhos para cada projeto.
Somos desbravadores, inquietos, curiosos e estamos sempre aplicando novas ideias, modelos de negócios e criando soluções inteligentes para o mercado."

http://g1.globo.com/economia/pme/pequenas-empresas-grandes-negocios/noticia/2017/10/intraempreendedorismo-abre-espaco-para-startups-dentro-das-empresas.html

## Como se candidatar

CVs ou Link do Linkedin e Github para denise@e-volve.in

## Labels

- Alocado
- PJ+Benefícios
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
