### ISSUE TITLE
[São Paulo] Back-End Developer (.Net Core & Angular) na [goLiza]

### ISSUE THREAD

**Issue by rodrigomherrera** [backend-br/vagas#600]
**Empresa: goLiza – Startup Fintech** 

https://www.linkedin.com/company/liza/
http://www.goliza.com.br/

**Vagas:** Programador(a) .Net Core & Angular (Senior e Pleno)

Startup no início da operação, com alto potencial de crescimento, ambiente colaborativo e descontraído, com uma equipe competente suportados por investidores e sócios robusto.

**Nosso Proposito:** Transformar a forma como as empresas se conectam eliminando ineficiência, fortalecendo segurança, promovendo mais negócios e adicionando mais tempo na vida das pessoas.

**Perfil Profissional:**  Esteja com vontade de fazer a diferença, criativo(a), colaborativo(a), resiliente, flexível, goste de desafios, respeitoso(a), foco em resultado, e por fim, que goste de celebrar!

**Conhecimentos Obrigatórios:**
 -Linguagem de programação: C#, MVC, AngularJS, NodeJS, HTML5, CSS3, SQL Server, MongoDB, AWS, Azure, TFS e GitHub 
-Metodologia: Ter sólidos conhecimentos de SCRUM e KANBAN 

**Conhecimentos Desejáveis** 
Tecnologias: ReactJS, .NET Core, Python, Cassandra, MemCached Conhecimento de Squad e Design Thinking 

**Local de Trabalho:** São Paulo Capital - Pinheiros 

**Se tiver interesse envie seu CV para akira@goliza.com.br, rodrigo@goliza.com.br**

**Comment by JCPBarbosa** [comment]
Com a forma da contratação?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
