### ISSUE TITLE
[São Paulo] Back-End Developer no Itaú

### ISSUE THREAD

**Issue by julianaschapiro** [backend-br/vagas#602]
![image](https://user-images.githubusercontent.com/45045074/48501157-aedcb780-e823-11e8-9746-a1ecddda1b9f.png)

**Sobre nosso cliente:**
Nosso cliente é o banco Itaú, a maior instituição bancária privada do Brasil

**Local de trabalho:**
São Paulo – SP

**Principais atividades:**
•	Participar do Desenvolvimento e implementação de projetos e melhorias nos sistemas existentes, visando atender as necessidades dos clientes internos, externos e parceiros de negócios;
•	Aplicar metodologia e padrões corporativos no desenvolvimento e manutenção de sistemas, através da divulgação e validação dos produtos gerados pelos terceiros.

**Perfil técnico:**
•	Conhecimento/experiência em análise de sistemas; 
•	Experiência em desenvolvimento em uma das tecnologias: .NET(C#) ou Java;
•	Experiência em desenvolvimento com SQL Server;
•	Conhecimento em Metodologia Ágil SCRUM;
•	Conhecimento em Modelagem de Sistemas com UML; 
•	Elaboração e execução de casos de testes.

**Perfil pessoal:**
•	Paixão por desenvolvimento de sistemas; 
•	Pró-atividade e postura de dono; 
•	Capacidade analítica com foco em eficiência e resultados; 
•	Comunicativo, responsável, colaborativo e inovador; 
•	Planejamento e organização para trabalhar com entregas programadas; 
•	Habilidade de comunicação verbal e escrita; 
•	Facilidade para trabalhar em equipe e estabelecer parcerias. 

**Contratação:** CLT

Encaminhar CV para **juliana.veiga@integritygroup.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
