### ISSUE TITLE
[São Paulo] Desenvolvedor Mobile no Itaú

### ISSUE THREAD

**Issue by julianaschapiro** [backend-br/vagas#603]
![image](https://user-images.githubusercontent.com/45045074/48503297-e00bb680-e828-11e8-9d7b-743bfa0729ae.png)

**Sobre nosso cliente:**
Nosso cliente é o Banco Itaú, a maior instituição bancária privada do Brasil

**Local de trabalho:**
São Paulo – SP

**Principais atividades:**
•	Participar do Desenvolvimento e implementação de projetos de novos aplicativos e melhorias nos sistemas existentes, visando atender as necessidades dos clientes internos, externos e parceiros de negócios;
•	Aplicar metodologia e padrões corporativos no desenvolvimento e manutenção de sistemas, através da divulgação e validação dos produtos gerados pelos terceiros.

**Perfil técnico:**
•	Conhecimento/experiência em análise de sistemas; 
•	Experiência em desenvolvimento mobile Android ou iOS;
•	Experiência em desenvolvimento com SQL Server;
•	Conhecimento em Metodologia Ágil SCRUM;
•	Elaboração e execução de casos de testes.

**Perfil pessoal:**
•	Paixão por desenvolvimento de sistemas; 
•	Pró-atividade e postura de dono; 
•	Capacidade analítica com foco em eficiência e resultados; 
•	Comunicativo, responsável, colaborativo e inovador; 
•	Planejamento e organização para trabalhar com entregas programadas; 
•	Habilidade de comunicação verbal e escrita; 
•	Facilidade para trabalhar em equipe e estabelecer parcerias. 

**Contratação:** CLT

Encaminhar CV para **juliana.veiga@integritygroup.com.br**

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
