### ISSUE TITLE
[São Paulo] Node.js Developer na Aliança Hospitalar

### ISSUE THREAD

**Issue by danielbdias** [backend-br/vagas#605]
**Descrição da Vaga**

A Aliança Hospitalar é uma startup com foco em ajudar hospitais a melhorarem o seu ciclo de receita utilizando Inteligência Artificial, Machine Learning e Big Data. Atendemos hospitais de médio e grande porte de referência em suas regiões.

Possuímos um ambiente descontraído, flexível, pet-friendly e com muitos snacks!
 
Nossos valores são: trabalho em equipe, ética, paixão, melhoria contínua, transparência e sentimento de dono. 

**Requisitos**

- Node.js
- Design de APIs REST
- TDD, DDD, BDD
- Bancos de Dados relacionais (Postgres)

**Diferenciais:**

- Experiência com AWS
- Integração e deploy contínuo
- GraphQL
- React
- Python

**Labels:**
- PJ
- Júnior
- Pleno
- NodeJS

**Local**

Vila Olímpia / São Paulo-SP

Para se candidatar a vaga, por favor, envie um e-mail para ddias@aliancahospitalar.com com o seu CV + Pretensão salarial.

**Comment by guilhermeoa07** [comment]
entrevista pode ser online?

**Comment by andersonmendesdev** [comment]
Enviado!
