### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na BM&K Laboratório de Imagem

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#608]
### Sobre a empresa: BM&K Laboratório de Imagem

A BM&K é uma empresa de telerradiologia e pós-processamento de imagem.
 Prestamos serviços de elaboração de laudos e pós-processamento de imagens à distância para as clínicas, em Ressonância Magnética e Tomografia Computadorizada.
 Com o objetivo de oferecer uma solução completa em processamento, análise e interpretação remota de imagens médicas para os exames que a clínica realiza, reunimos uma equipe de profissionais altamente capacitados.

### Descrição: Ocupações do cargo

Desenvolvimento de sistemas;
Organizar e controlar as demandas existentes;

### Você deverá conhecer:

JavaScript, React.js, Node.js, Express;
ES6;
HTML5, CSS3;
MySQL;
API Rest;
Controle de versionamento com Git;

### Diferenciais:

Redux;
Sequelize;
GraphQL;
ECMAScript;
Experiência com ferramentas comuns de desenvolvimento de front-end como yarn, npm, etc.

### Aptidões e qualidades

Trabalho em equipe;
Boa comunicação verbal e escrita;
Auto-gerenciável;
Dinâmico, pró-ativo e em busca de desafios;
Organização;
Ter pensamento rápido;
Inglês técnico;

### Como é a BM&K?

A BM&K é uma empresa que não tem sede física, nossos servidores estão hospedados em um datacenter e todos os colaboradores (médicos e funcionários) acessam remotamente. Você irá integrar um time que está em crescimento. Trabalhará na sede que fica em um coworking de SP em conjunto com um desenvolvedor que está no RJ.

### Nossa Missão:

Fornecer aos nossos clientes produtos e serviços de qualidade por meio de tecnologia, conhecimento e engajamento das pessoas.

### Labels: 

Pleno
Alocado

### Candidatar: http://bit.ly/laboratorio_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
