### ISSUE TITLE
[Remoto] Back-end Developer Junior @ Enext

### ISSUE THREAD

**Issue by rogerioalmeidaa** [backend-br/vagas#6084]
## Nossa empresa

A Enext é uma consultoria e agência digital, formada por um time super engajado que tem hoje aproximadamente 200 pessoas, extremamente competentes e focadas nas entregas com excelência para alcançar os melhores resultados para os nossos clientes. É esse comprometimento que nos torna referência nas melhores tecnologias do mercado de desenvolvimento de e-commerce como: Salesforce, Oracle, Magento e Vtex!

Temos como base a missão de ser referência no desenvolvimento do mercado digital, oferecendo oportunidades para os nossos colaboradores e entregando resultados excelentes para nossos clientes!

Você está em busca de desenvolvimento e quer aprender através de projetos DESAFIADORES? Aqui na Enext Consultoria, nós TRANSFORMAMOS as PESSOAS para o FUTURO! Vem crescer com a gente!

## Descrição da vaga

Como Back-End Junior, serão atividades comuns no seu dia a dia:

- APIs REST e SOAP;
- Desenvolvimento de web, server e serverless applications com NodeJS e Python;
- Desenvolver soluções para o e-commerce de forma geral, atuando diretamente no processo de transformação digital dos clientes
- Processos básicos de Devops, como: Configuração de Databases, Containers ou CI/CD
- Análise de documentações, levantamento de requisitos e especificações dos projetos
- Liberdade para criar soluções da forma mais eficiente e que atenda as necessidades do projeto
- Stack altamente dinâmica (Nos adaptamos ao mercado e aos clientes)
- Contato com grandes players do mercado de tecnologia como Amazon, Salesforce, Oracle, Google, Microsoft e muito mais

## Local

Remoto

## Requisitos

**Obrigatórios:**

- NodeJs ou Python
- Git
- MySQL, SQL Server ou MongoDB
- Rest APIs ou SOAP APIs
- Estrutura de Dados e Orientação a Objetos
- Busca constante aprendizado

**Desejáveis:**
- Conhecimento básico de redes, subredes e protocolos (HTTP, HTTPS, TCP, SSH, FTP)

**Diferenciais:**

- Experiência com algum dos provedores de Cloud Computing, sendo: Oracle Cloud Infrastructure, Amazon Web Services, Azure ou Google Cloud Platform
- Experiência anterior com desenvolvimento mobile
- Desenvolvimento com Linux
- Oracle Integration Cloud, Apache Kafka, RabbitMQ, Amazon SQS ou Amazon SNS
- Oracle Commerce Cloud, Vtex ou Magento
- Já ter desenvolvido integrações com Clearsale, Cybersource, Braspag, Mundipagg ou outros provedores de pagamento e análise de fraude.
- Java

## Benefícios

- Vale Refeição ou Vale Alimentação (você escolhe o que é melhor!);
- Seguro Saúde Porto Seguro Bronze: a empresa custeia 100% e não tem co-participação por utilização;
- Auxílio Home Office;
- Seguro Odontológico - Porto seguro (opcional);
- Horário Flexível;
- Parceria com universidades para descontos e vantagens exclusivas;
- Descontos e vantagens em academias, agências de turismo, clínicas de beleza e estética, escolas de idiomas, restaurantes e em diversos outros serviços e estabelecimentos;
- Acesso gratuito à plataforma Enext College (Programa de aperfeiçoamento e conhecimento disponível para todos os colaboradores Enext
- PAE (Programa de Apoio ao Empregado) de auxílio com questões jurídicas, sociais, administração financeira e psicológicas;
- Acesso gratuito à Plataforma ILearn (WPP) com cursos internos e vínculo com o Linkedin Learning, Interface com outras empresas do grupo e oportunidades internacionais.
- Auxílio para Certificações em plataformas parceiras (Salesforce, Vtex, Google, Amazon, MeLi, etc.).

## Contratação

CLT

## Como se candidatar

Por favor envie entre em contato conosco através do nosso portal de carreiras oficial: [[Remoto] Back-end Developer Junior](https://enext.solides.jobs/vacancies/86930)

## Labels
- AWS
- Azure
- GCP
- Oracle
- Vtex
- Occ
- Junior
- Ecommerce
- Node
- JavaScript
- Python
- Java
- Docker
- Rest
- SOAP
- API
- Git
- SQL
- CLT
- Remoto

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Junior

**Comment by rogerioalmeidaa** [comment]
Ainda estamos com a oportunidade em aberto, venham fazer parte do nosso time !

**Comment by abelsouzacosta** [comment]
É preciso ter experiência em ambas as tecnologias ou somente uma delas?

**Comment by rogerioalmeidaa** [comment]
> É preciso ter experiência em ambas as tecnologias ou somente uma delas?

Não precisa ter experiência com as duas, mas será um diferencial se tiver nas duas ou uma bagagem maior com NodeJs.

**Comment by abelsouzacosta** [comment]
> > É preciso ter experiência em ambas as tecnologias ou somente uma delas?
> 
> Não precisa ter experiência com as duas, mas será um diferencial se tiver nas duas ou uma bagagem maior com NodeJs.

Ao clicar no link há um aviso dizendo que a vaga foi encerrada pela empresa 😢 

![image](https://user-images.githubusercontent.com/30609244/129052823-bcda6cf4-b416-486e-9ef1-853324be5a36.png)

**Comment by rogerioalmeidaa** [comment]
> > > É preciso ter experiência em ambas as tecnologias ou somente uma delas?
> > 
> > 
> > Não precisa ter experiência com as duas, mas será um diferencial se tiver nas duas ou uma bagagem maior com NodeJs.
> 
> Ao clicar no link há um aviso dizendo que a vaga foi encerrada pela empresa 
> 
> ![image](https://user-images.githubusercontent.com/30609244/129052823-bcda6cf4-b416-486e-9ef1-853324be5a36.png)

Obrigado por avisar, vou entender o que aconteceu com nosso time de RH e já atualizo o link da vaga

**Comment by abelsouzacosta** [comment]
Eu que agradeço, quando corrigir o link gostaria de ser avisado, se for possível.

**Comment by rogerioalmeidaa** [comment]
> Eu que agradeço, quando corrigir o link gostaria de ser avisado, se for possível.

Atualizado !

**Comment by diegoamloiola** [comment]
![image](https://user-images.githubusercontent.com/72869745/137313075-f429453a-607d-41e6-90ab-de5e08e4d776.png)
 Já encerrou a vaga? Aqui tá aparecendo assim...

**Comment by hidelrios** [comment]
Essa vaga ainda se encontra disponível? Gostaria de me candidatar.
