### ISSUE TITLE
[Vitória-ES/Remoto Desenvolvedor Full Stack na King Invest]

### ISSUE THREAD

**Issue by philipedornelas** [backend-br/vagas#609]
**Sobre a empresa: King Invest**
Focamos em pessoas e processos para construir grandes negócios. Fomentamos um ambiente disruptivo onde compartilhamos recursos como conhecimento, tecnologia, infraestrutura, marketing e assessoria jurídica para acelerar o crescimento de nossas empresas.

**Requisitos:**
Experiência com JavaScript, Node.js;
Experiência com Linux;
Experiência com PHP;
Pró-atividade;
Trabalho em equipe e liderança;
Cooperação.

**Diferenciais:**
Conhecimento de infra (Web Service);
Experiência com Angular ou Vue.js;
Cultura de Scrum Master.

**Oferecemos:**
Salário compatível com o mercado;

**Seus desafios serão:**
Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;

Para se candidatar envie seu CV para philipe.dornelas@kinginvest.co

**Labels:**
Alocado
Remoto
Pleno/Senior

**Comment by diegoldnascimento** [comment]
@philipedornelas , te enviei um e-mail com minha candidatura! Abraços.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
