### ISSUE TITLE
[Santa Barbara D'Oeste] Backend PHP Developer na Acruxx

### ISSUE THREAD

**Issue by santoja** [backend-br/vagas#61]
**Descrição da vaga**
Criar APIs com PHP e GraphQl;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Participar do processo criativo e auxiliar na construção dos sistemas;

**Local**
Remoto ou Escritório, Santa Barbara D'Oeste

**Benefícios**
VA
Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

**Diferenciais**
Area de descanso
Frutas no escritório
Café expresso ou coado
Chá
Cachorro no ambiente de trabalho
Troca de experiencias com profissionais de outras equipes

**Requisitos**
**Obrigatórios:**

Experiência relevante em PHP OOP
Usar os conceitos SOLID.
Desenvolver utilizando boas praticas de programação

**Desejáveis:**
PHP 7.1 e mais novos
Ter trabalhado com nonSQL
Conhecer os conceitos de GraphQL

**Diferenciais:**
Contratação
CLT presencial ou remoto

Como se candidatar
Por favor envie um email para kaue@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by brunokunace** [comment]
Vaga ainda em aberto?  pode ser clt ou pj e presencial ou remoto??? 

Pode dar mais detalhes?

**Comment by Moov8Systems** [comment]
Bom dia Bruno.

Sim, a nossa vaga ainda esta em aberto, mas não é esta que você mandou.
É esta: https://github.com/backend-br/vagas/issues/146

Se interessar, aplique pelo email: contato@minnis.com.br

Um abraço

Em 27 de março de 2018 22:12, Bruno Henry <notifications@github.com>
escreveu:

**Comment by santoja** [comment]
@Moov8Systems @brunokunace  Wut?

**Comment by giovannicruz97** [comment]
A vaga ainda está em aberto ?

**Comment by brunokunace** [comment]
@Moov8Systems na verdade era essa vaga mesmo pois existe a opção de Remoto,  moro em MG,  talvez o custo de São Paulo capital pra morar fique elevado. 

Agradeço seu contato, se entendi errado,  peço que me corrija por favor.

Obrigado. 

(Esta vaga aqui ainda está em aberto @santoja?)

**Comment by Moov8Systems** [comment]
Desculpe Bruno. Estamos preferindo presencial. Muito obrigado pela atenção.

Em 28 de março de 2018 12:05, Bruno Henry <notifications@github.com>
escreveu:

**Comment by Moov8Systems** [comment]
Boa tarde Bruno.
Sim. Esta em aberto.
Aplicações para: contato@moovsystems.com.br
Obrigado

2018-03-28 11:42 GMT-03:00 Giovanni Cruz <notifications@github.com>:

**Comment by Moov8Systems** [comment]
Ola Kaue.
Aplicações para: contato@minnis.com.br
Obrigado

2018-03-28 11:39 GMT-03:00 Kaue Santoja <notifications@github.com>:

**Comment by santoja** [comment]
Sim pessoal, a vaga ainda esta em aberto. Acho que o @Moov8Systems  está um pouco confuso com o uso da ferramenta só =).

**Comment by SupPayFintech** [comment]
É verdade. Estamos confusos com a ferramenta. Isto porque estamos recebendo notificações sobre esta vaga no nosso email, mas a vaga não é nossa. Desculpem. ;-)

**Comment by santoja** [comment]
@Moov8Systems Possivelmente está como Inscrito na vaga. Ali no canto direto superior tem um "Notifications" e embaixo o botão "unsubscribe", já tira as notificações dessa e deixa só a de vocês =)

**Comment by reginaldojunior** [comment]
@santoja 

Vaga preenchida?

**Comment by santoja** [comment]
Ainda estamos no processo, mas já encerramos o recebimento de CVs, obrigado por fechar a vaga @reginaldojunior
