### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Full Stack na ENCONTRE SUA FRANQUIA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#613]
### Sobre a empresa: Encontre Sua Franquia

A Encontre sua Franquia é uma holding que concentra 6 marcas próprias. Ao todo são mais de 1000 operações por todo o Brasil, através de suas marcas, nas áreas de turismo, beleza e estética, corretora de seguros, alimentação, estética automotiva e entretenimento.

### Descrição: Ocupações do cargo

Desenvolvimento de sites, landing pages, sistemas de gestão, criação de formulários, plug-ins e módulos para sites, wordpress e magento; Integração e/ou criação de API’s e web services; Manuais (tutoriais) para sistemas e/ou integrações; Diagnosticar problemas (bugs); Reformulação de um sistema feito em PHP;

### Benefícios

vale alimentação
vale transporte ou vale combustível

### Aptidões e qualidades

Linha de comando linux
Amazon AWS
PHP Avançado
MVC
Laravel (Ou outro Framework)
HTML + CSS
Javascript

### Labels

Alocado
Pleno

### Candidatar: http://bit.ly/encontresuafranquia_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
