### ISSUE TITLE
[Belo Horizonte] Laravel Developer Junior na EasyGamer

### ISSUE THREAD

**Issue by victordeassis** [backend-br/vagas#615]
Fala pessoal! Sou o Victor da EasyGamer e estamos com uma vaga de desenvolvedor Júnior em Laravel/PHP

Antes, deixa eu falar um pouco sobre a EasyGamer, nós somos a primeira plataforma de compra e venda de PC gamer, videogames e acessórios do Brasil, somos uma Startup de Belo Horizonte e estamos no mercado há 1 ano, temos no ar hoje em dia o nosso MVP, dá uma olhada lá: www.easygamer.com.br

Nós estamos evoluindo nosso produto para ter novas funcionalidades, trazendo mais facilidades e segurança na plataforma, para isso nós migramos o produto para Laravel e precisamos de uma pessoa que seja capaz de pegar um código já feito em Laravel, que está bem comentado e estruturado e fazer modificações para atender novas necessidades. Precisamos também de uma pessoa que saiba de DevOps para poder configurar o ambiente nos nossos servidores, seja Amazon, Digital Ocean ou Google Cloud Platform.

O modelo de contrato inicial será como PJ pois acreditamos ser o melhor para começarmos o projeto. E iremos combinar o preço baseando nas necessidades do projeto. Temos oportunidade de Stock Option caso você seja foda!

Nós estamos localizados em um Co-working na Avenida Cristiano Machado, onde podemos trabalhar localmente, mas sendo super flexível para trabalhar remoto (se tudo fluir bem), e também em outros co-workings para mudar o ambiente.

Entre em contato com a gente mandando um email para contato@easygamer.com.br com seu GitHub e/ou projetos que já tenha feito.

**Comment by guilhermeoa07** [comment]
Opa, show de bola, entrevista pode ser remota?

**Comment by victordeassis** [comment]
> Opa, show de bola, entrevista pode ser remota?

Fala Guilherme, Pode sim! Me manda um email no contato@easygamer.com.br

**Comment by maxmonteiro** [comment]
Não consigo entrar em contato.
