### ISSUE TITLE
[Remoto] Back-end Developer ruby on rails @ Jaya tech

### ISSUE THREAD

**Issue by rennanoliveira** [backend-br/vagas#6169]
## Nossa empresa

A [Jaya](http://www.jaya.tech) tem 8 anos, home-office desde sempre. Uma empresa formada por devs, para devs.
Somos motivados por desenvolver tecnologia que impacte positivamente a vida das pessoas, tudo isso dentro de uma cultura que respeita e valoriza (de verdade) cada um aqui dentro. Só aceitamos clientes que se alinhem a nossos valores, não nos consideramos ‘mão de obra terceirizada’ em nossos clientes, e sim parte da equipe .

## Descrição da vaga
A vaga é para trabalhar com um cliente em NY na área de saúde ligado a aprovação de exames e entrega de resultados de covid. Desenvolvimento Rails backend em diversos sistemas, desde um monolito padrão a projetos menores. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com Ruby on Rails
- Inglês intermediário (as reuniões serão em inglês, oferecemos aulas de inglês caso precise de reforço)

**Diferenciais:**
- experiência com desafios de escala
- mysql ou postgres

## Benefícios

- VR ou VA de R$ 1,100/mês
- Plano de saúde Sulamérica Especial 100 ou Unimed (integral para o desenvolvedor e 50% de uma tabela para conjugue e filhos) isento de carências
- Plano odontológico Sulamérica
- Seguro de vida
- Auxílio creche
- Auxílio equipamento
- Aulas de inglês (Cambly)
- PLR

**Diferenciais:**
- Cultura forte
- Acompanhamento de carreira (1 on 1s constantes)
- Possibilidade de migrar de projetos/tecnologias

## Contratação

CLT.
Faixa salarial de R$6,500 a R$ 13,500, dependendo da senioridade.
Possibilidade para migrar para um salário em dolar ($4,500-$6000) em regime PJ após 1 ano de casa.

No momento sem vagas para juniors.

## Como se candidatar

Por favor envie um email para rennan@jaya.tech com seu CV anexado - enviar no assunto: [Processo seletivo] Vaga Rails

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: lucas@jaya.tech

#### Tecnologias
- ruby
- rails

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by rfsbarreto** [comment]
Já estive na jaya e recomendo fortemente, cultura bem boa hein!

**Comment by walteraa** [comment]
> Já estive na jaya e recomendo fortemente, cultura bem boa hein!

Só pra dar um RT, uma das melhores empresas que já trabalhei!!

**Comment by alextakitani** [comment]
Recomendo demais, empresa sensacional!
