### ISSUE TITLE
[Belo Horizonte - MG] Analista BI na D'ACORDO MEDIAÇÕES

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#618]
### Sobre a empresa: D'Acordo Mediações

A D’Acordo Mediações é uma empresa especializada na prevenção, gerenciamento e resolução de conflitos. 
Com foco em mediação, conciliação e negociação, desenvolvemos tecnologias inovadoras para evitar disputas judiciais e administrativas. 
Por meio de Terminais de Autoatendimento e de uma Plataforma web, conectamos empresas e clientes para solucionar conflitos.

### Descrição: Ocupações do cargo

Coleta e análise de dados;
Organização e tratamento da informação;
Implementar e evoluir funcionalidades na plataforma web da D'Acordo.

### Requisitos:

Excel Avançado;
MySQL;
ETL para Excel;
SQL;

### Desejável:

SQL Server;

### Benefícios:

Flexibilidade de horário;
Home Office.
Aptidões e qualidades
Pró-atividade;
Capacidade de trabalhar em equipe;
Bom relacionamento interpessoal;
Responsabilidade;
Criatividade.

### Informações complementares:

O profissional participará ativamente e terá voz ativa no desenvolvimento do projeto. Buscamos incentivar a evolução constante de nossos profissionais e fornecer feedbacks com frequência para aprimoramento.

### Labels:

Alocado
Pleno/Junior

### Candidatar: http://bit.ly/Dacordobi_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
