### ISSUE TITLE
[Belo Horizonte ou Remoto] Back-End Developer no Melhor Plano

### ISSUE THREAD

**Issue by felipembyrro** [backend-br/vagas#62]
## Sobre o Melhor Plano

Melhor Plano é uma solução que ajuda os consumidores a tomarem a melhor decisão na contratação de serviços. Nossa visão é ser a principal referência para consumidores encontrarem economias em sua conta, em diversos serviços. Para isso, precisamos de tecnologia de ponta, utilizando crawlers e inteligência artificial para comparar e monitorar as contas de nossos usuários. Queremos ser uma das referências de tecnologia no país!

Atualmente, somos os líderes em comparação de telefonia no Brasil e já ajudamos quase 2 milhões de brasileiros a economizar com planos de celular, banda-larga, fixo, tv e combos!

## Vaga Desenvolvedor Full Stack/Back-End

Buscamos um talento para compor o time de desenvolvimento do Melhor Plano. Candidato além de ser dinâmico, deverá ser pró-ativo, saber trabalhar em equipe.

O stack do Melhor Plano hoje é composto por:

- Front-end com React e AMP
- Node
- Typescript
- MongoDB

Tem interesse em trabalhar em uma startup em crescimento acelerado e que tem como objetivo ajudar milhões de pessoas a economizar?

## Desafios e responsabilidades
**Aqui são algumas coisas que você irá se envolver:**

- Desenvolvimento de páginas otimizadas para SEO e responsivas
- Desenvolvimento de páginas utilizando AMP, HTML e CSS
- Desenvolvimento de páginas em React
- Manutenção de crawlers em Typescript e Node
- Desenvolvimento de backend em Typescript e Node
- Integração com APIs de parceiros
- Integração Google Sheets e Google Docs utilizando Javascript
- Desenvolvimento de testes automáticos

## Sobre você
**Você tem o perfil ideal para a vaga se:**

- Experiência com Javascript / Typescript;
- Experiência com desenvolvimento Web responsivo;
- Comunica de forma clara;
- Capacidade de analisar números e tomar decisões com base em dados;
- Sabe inglês;
- Excelente capacidade organizacional e pró-atividade para trabalhar de forma independente. Autogestão é um característica do nosso time. You get things done without someone saying so.
- Foco em objetivos e resultados. Somos muito orientados a resultado, você e todo o time será cobrado por isso!;
- Gostar de aprender. Não sabemos fazer tudo, mas somos apaixonados por aprender a fazer algo novo.
- Gosta de fazer seu trabalho de forma eficiente. Precisamos criar processos e sistemas que nos permitam criar algo maior que nós mesmos.
- Acredita que mais importante do que suas credenciais acadêmicas é o que você faz bem e gosta de fazer.

## Bônus:

- Experiência com React
- Experiência com AMP

## Mais sobre o Melhor Plano
O comparador do Melhor Plano foi lançado em março de 2016 e desde lá tivemos um crescimento acelerado, chegando a impactar quase 2 milhões de pessoas com nosso site.

Fomos uma das startups selecionadas, dentre mais de 3000 empresas do mundo, para participar do programa de aceleração Startup Chile, em Santiago - Chile.

Participamos recentemente do [SEED](http://seed.mg.gov.br/), aceleradora com 40 startups de diferentes partes do Brasil e do Mundo. Oportunidade única de se envolver em uma comunidade incrível de startups. Recentemente fomos destaques em eventos internacionais de startups como o [SeedStars](https://www.seedstarsworld.com/summit/) e o [Startup Games](https://ioasys.com.br/startupgames/).

- Acreditamos que todo mundo poderia fazer mais do seu dinheiro se tomar uma decisão mais informada.
- Colocamos nossos usuários em primeiro lugar. Ajudamos nossos usuários de forma imparcial, mesmo que isso signifique não ganhar dinheiro.
- Acreditamos que a transparência é bom negócio. Ela ajuda os consumidores a tomarem decisões com mais segurança e, ao mesmo tempo, torna o fluxo de venda de nossos parceiros mais eficiente.

**Faça parte do time!**
Estamos em crescimento acelerado e precisamos de um bom time para entregar economia e tecnologia de ponta para nosso usuários.

## Benefícios

- Salário baseado na experiência (R$3.000 - R$7.000 - você pode preencher expectativa salarial na aplicação);
- Flexibilidade de horário;
- Trabalhe parte do tempo de onde quiser - seu computador e boa internet é o suficiente 😉; A única obrigação de estar presente fisicamente são as reuniões criativas, a maior parte do tempo de execução pode ser feito remoto, ou no nosso escritório (possibilidade de trabalho remoto). Mas isso não significa que deixamos de comunicar constantemente.
- Oportunidade de trabalhar diretamente com fundadores de uma startup que cresce rapidamente.

## Como aplicar: (melhorplano.net/vagas)

- [Acesse este link para aplicar](https://airtable.com/shrotro0R03iL8UU7)
- Preencha o formulário do link
- Aguarde que entraremos em contato. Daremos retorno mesmo para quem não passou para a próxima fase.
- A segunda fase será uma atividade prática de desenvolvimento para entender como você programa.
- A última fase será uma entrevista com o time do Melhor Plano. Parte da entrevista será técnica e outra parte de alinhamento cultural.

Boa sorte!

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by felipembyrro** [comment]
Olá Vinicius!

Aceitamos sim. Só colocar no último campo que tem interesse em ser remoto.

Abs

--
*Felipe Byrro*

*Whatsapp* +55 31 92000006
Linkedin <http://www.linkedin.com/pub/felipe-byrro/1a/924/623> | Facebook
<https://www.facebook.com/felipe.byrro>

ESTAMOS CONTRATANDO: https://melhorplano.net/vagas
<https://melhorplano.net/vagas>



2018-02-07 21:04 GMT-02:00 Vinicius Guedes <notifications@github.com>:

**Comment by reginaldojunior** [comment]
Vaga preenchida?
