### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Full Stack na BAGY

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#621]
### Sobre a empresa: Bagy

Plataforma de vendas online focada no varejo de moda para pequenos e médios lojistas que hoje vendem utilizando o Instagram. Fundada no início de 2017 e com lançamento da versão 1.0 em julho o Bagy hoje já conta com mais de 50 lojistas, está encubada na CDL de Belo Horizonte e busca nesse ano bater a meta de mais de 1000 lojas cadastradas.

### Descrição: Ocupações do cargo

O profissional irá desenvolver as aplicações client da solução de e-commerce do Bagy, incluindo as aplicações de gerenciamento interno, dos lojistas e as aplicações de venda (para compradores finais). Propor e desenvolver melhorias de interface e de estrutura do código, focado na experiência do usuário, bem como ajudar a equipe atual a evoluir as habilidades em desenvolvimento FrontEnd.

 **O profissional deverá possuir conhecimento nas seguintes linguagens e frameworks:**

TypeScript;
Angular;
Trinca desenvolvimento web (HTML, CSS e JavaScript);
Ionic.

### E será considerado como um diferencial o conhecimento com:

Ter feito ou saber mexer com APIs externas;
Será muito bom ele ter conhecimento ou estar disposto a conhecer C#;
React;
React Native.

### Benefícios

O profissional será contratado como PJ, com isso os benefícios estarão inclusos na remuneração. Porém, no Bagy você terá a oportunidade de trabalhar em um local em que possui horário flexível, com possibilidade de trabalho remoto eventual, ambiente descontraído e estimulante.

### Aptidões e qualidades

O profissional deve ser capaz de propor soluções que levem em consideração as características do negócio e a atual arquitetura da solução. Ter capacidade de compartilhar conhecimento e de trabalhar em um equipe enxuta e ágil. É fundamental ter experiência em desenvolvimento de aplicativos (híbridos ou nativos), e de Single Page Applications e de suas características únicas em relação ao desenvolvimento web tradicional.  

### Informações complementares

No Bagy temos uma política de oportunidades para todos, onde as pessoas de destaque têm a possibilidade de receber participação nos resultados e/ou societária. 

### Labels:

Alocado
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
