### ISSUE TITLE
[Belo Horizonte] Desenvolvedor(a) Back-End Pleno (Elixir, Go, Typescript) na DITO

### ISSUE THREAD

**Issue by mari-dito** [backend-br/vagas#623]
**Sobre a Dito:**

A Dito é uma empresa de tecnologia que nasceu em meio à atmosfera de inovação do San Pedro Valley, em Belo Horizonte. Nós desenvolvemos uma plataforma capaz de impactar milhares de usuários de forma segmentada, inteligente e multicanais.

No nosso time, todo mundo é FERA: pega e Faz, com foco e planejamento; age com Ética e transparência; se preocupa com o Resultado dos clientes (internos e externos); trabalha com Alegria e tem sede por Aprender.

Nós estamos localizados no coração da Savassi, em Belo Horizonte, e temos bases de apoio também em São Paulo e no Rio de Janeiro. Nossa equipe hoje conta com 50 FERAs que ajudam marcas como TIM, Ingresso.com, Chilli Beans, Araujo, Track&Field, Havaianas, Chico Rei, Farm e Zee.dog a livrarem o mundo do marketing genérico.

**Nosso time de Tecnologia:**

A Dito é uma empresa de Tecnologia em sua essência. Por isso, nossos Desenvolvedores são o coração do nosso time. Com experiências e níveis de senioridade diversos, nossa equipe de Desenvolvimento é responsável por garantir uma boa experiência de uso da nossa plataforma, promovendo melhorias no produto e desenvolvendo novas funcionalidades.

Nós acreditamos no trabalho em equipe, no compartilhamento de conhecimentos e no uso de boas práticas de engenharia de software para construir as melhores soluções para os nossos clientes.

**CIA:**

Como a Agência Central de Inteligência dos Estados Unidos, a nossa CIA é o squad responsável pela inteligência da plataforma, garantindo o desempenho e a resiliência necessários para escalarmos.

**Nossos desafios:**

- Garantir desempenho, resiliência e extensibilidade para implementação de novas funcionalidades;
- Desenvolver códigos e sistemas com qualidade e robustez;
- Aprender e nos adaptar rapidamente às mudanças de contexto e prioridade;
- Melhorar cada vez mais nossos processos, sem perder a essência ágil.

**Como trabalhamos:**

- Utilizamos várias linguagens (Javascript, Typescript, Elixir e Go);
- Pensamos de forma funcional nas nossas soluções;
- Gostamos de trabalhar com linguagens tipadas;
- Utilizamos MongoDB, DynamoDB e BigQuery para armazenamento de dados, além de ElasticSearch como servidor de buscas;
- Prezamos pelo planejamento minucioso, embasamento teórico e muito benchmarking para entregar as melhores soluções;
- Temos uma grande preocupação com testes automatizados, style guide e integração contínua;
- Todos os nossos sistemas são distribuídos;
- Escalamos horizontalmente nossos microsserviços, utilizando Docker/Kubernetes e arquitetura serverless;
- Temos alto throughput de dados e comunicação entre microsserviços utilizando AWS Kinesis.

Para integrar esse squad, nós estamos em busca de um(a) Desenvolvedor(a) Back-End que tenha grande interesse em aprender e se aprofundar em linguagens funcionais.

**O que oferecemos:**

- Salário: avaliaremos a pretensão salarial x expertise e background;
- Vale transporte;
- Vale­ refeição ou alimentação (R$20,60 por dia);
- Assistência médica (Unimed);
- Lanche na empresa;
- Horários flexíveis;
- Sem dress code por aqui :)
- Contato com novas tecnologias e tendências de mercado;
- Um ambiente incrível <3

Se você se encaixa nesse perfil e quer fazer parte de uma das 10 melhores empresas de TI para trabalhar no Brasil, de acordo com o Great Place to Work®, inscreva-se no link: [https://dito.recruiterbox.com/jobs/fk0j6ea/](https://dito.recruiterbox.com/jobs/fk0j6ea/)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
