### ISSUE TITLE
[Belo Horizonte] Data Scientist na DITO

### ISSUE THREAD

**Issue by mari-dito** [backend-br/vagas#624]
**Sobre a Dito:**

A Dito é uma empresa de tecnologia que nasceu em meio à atmosfera de inovação do San Pedro Valley, em Belo Horizonte. Nós desenvolvemos uma plataforma capaz de impactar milhares de usuários de forma segmentada, inteligente e multicanais.

No nosso time, todo mundo é FERA: pega e Faz, com foco e planejamento; age com Ética e transparência; se preocupa com o Resultado dos clientes (internos e externos); trabalha com Alegria e tem sede por Aprender.

Nós estamos localizados no coração da Savassi, em Belo Horizonte, e temos bases de apoio também em São Paulo e no Rio de Janeiro. Nossa equipe hoje conta com 50 FERAs que ajudam marcas como TIM, Ingresso.com, Chilli Beans, Araujo, Track&Field, Havaianas, Chico Rei, Farm e Zee.dog a livrarem o mundo do marketing genérico.

**Nosso time de Data Science:**

Na Dito nós capturamos todos os dados de compra e comportamento on/offline dos clientes dos maiores varejos do país. Com esses dados nós ajudamos nossos clientes a segmentar melhor suas ações de marketing e a disparar notificações em diversos canais: Email, SMS, Mobile e Browser Push. Atualmente nossa base possui mais de 50 milhões de pessoas e enviamos mais de 100 milhões de notificações por mês.

Nosso principal desafio é ajudar os clientes a obterem mais resultado, gerando incremento na receita através do aumento da taxa de recompra. Esse incremento chamamos de lift, e utilizamos metodologias do campo da estatística para comprovar e medir quanto a Dito contribui no resultado dos nossos clientes.

**Nossos desafios:**

- Desenvolver e aplicar metodologias estatísticas baseadas em grupo de controle, construção de plano amostral e cálculo de lift;
- Extrair insights a partir dos dados que ajudam os clientes a obterem melhores resultados com a Dito;
- Construir modelos de Machine Learning para segmentação de clientes e recomendação de produtos.

**Como trabalhamos:**

- Utilizamos o Google BigQuery como fronte principal de dados; 
- Contato direto com áreas estratégicas da Dito e dos clientes que buscam insights a partir dos dados;
- Utilizamos o Redash para gerar Dashboards que facilitam a visualização dos dados.

**Você se encaixará bem se:**

- Souber programar (R , Python, Ruby…);
- Tiver facilidade com Cloud Computing;
- Possuir conhecimento avançado em SQL;
- Possuir facilidade e experiência com conceitos de estatística;
- Estiver interessado em usar dados para gerar mais resultado para os clientes da Dito.

Para integrar nosso time, estamos em busca de um(a) Data Scientist que será referência para toda a equipe de Tecnologia.

**O que oferecemos:**

- Salário: avaliaremos a pretensão salarial x expertise e background;
- Vale transporte;
- Vale­ refeição ou alimentação (R$20,60 por dia);
- Assistência médica (Unimed);
- Lanche na empresa;
- Horários flexíveis;
- Sem dress code por aqui :)
- Contato com novas tecnologias e tendências de mercado;
- Um ambiente incrível <3

Se você se encaixa nesse perfil e quer fazer parte de das Melhores Empresas para se Trabalhar em Minas Gerais e uma das Melhores Empresas de TI para se Trabalhar no Brasil, de acordo com o Great Place to Work®, inscreva-se no link: [https://dito.recruiterbox.com/jobs/fk0jw45/](https://dito.recruiterbox.com/jobs/fk0jw45/)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
