### ISSUE TITLE
[Brasília] - Desenvolvedor FullStack NodeJS

### ISSUE THREAD

**Issue by fscardua** [backend-br/vagas#629]
Procuramos profissionais engajados, com conhecimentos em desenvolvimento de software e, acima de tudo, dispostos a enfrentar desafios e problemas.

Formação e experiência:
* Nível superior ou cursando na área de TI.
* Boa leitura em inglês.
* Experiência mínima de 1 ano atuando como desenvolvedor.

Habilidades que procuramos:
* JavaScript (muito), HTML5, CSS3.
* Frameworks de mercado como Vue, React ou Angular (preferencialmente Vue).
* Desenvolvimento e utilização e API REST.
* GIT (alguém consegue não usar hoje em dia?)
* Testes são bem-vindos.
* Bom raciocínio lógico.
* Inteligência emocional e disposição para resolver problemas.
* Os requisitos mudam, os códigos também, esteja disposto a mudanças.

Habilidades que são interessantes e serão consideradas caso o candidato possua:
* SCRUM
* Banco de dados NOSQL (MongoDB?)
* Banco de dados geográfico (PostGIS?)
* Outros bancos de dados relacionais e não relacionais
* Saber consumir um servidor geográfico (GeoServer, ArcGIS)
* Utilizar framework de maps (ESRI, Leaflet, Openlayers)

O que você irá fazer:
* Código, muito código :)
* Planejar e discutir soluções de implementação com a equipe.
* Estudar e aprender bastante sobre novas tecnologias (ensinar também)

A vaga é para trabalho presencial e em tempo integral, em Brasília.

O regime de contratação é PJ.
Bateu as metas? Também tem bônus:)

A contratação é imediata.

Interessado? Envie seu currículo para contato@notoriun.com.br

Tipo de vaga: Tempo Integral

**Comment by samuelfaj** [comment]
Olá, sei que na descrição consta como presencial.

Mas seria possível isso ser reconsiderado? Para remoto ou remoto-parcial?
Teria disponibilidade a fazer viagens mensais ou até mesmo semanais.

**Comment by fscardua** [comment]
Olá Samuel, mande seu currículo para contato@notoriun.com.br e vamos analisar. 
Para remoto teria que ser alguém já bem sintonizado com nossas tecnologias, quem sabe você se encaixa.

**Comment by simaodev** [comment]
Bom dia, a vaga esta em aberto ainda?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
