### ISSUE TITLE
[São Paulo] Backend Developer no Portal R7.com - Ruby on Rails

### ISSUE THREAD

**Issue by andersonrpinto** [backend-br/vagas#63]
## Descrição da vaga

O R7.com está em busca de desenvolvedor Backend com proficiência em Ruby, Rails e MongoDB. Nossa equipe é multidisciplinar, com projetos envolvendo integrações de múltiplas aplicacões nas mais diversas linguagens e tecnologias. 

O profissional que buscamos deve ser dinâmico, pro-ativo, responsável, e acima de tudo com atitude positiva e paixão pelo que faz. 

## Local

Nosso escritório fica na Barra Funda, dentro da Record TV, ao lado da estação de metrô "Barra Funda" (linha vermelha).

## Benefícios

- Vaga CLT-FULL
- Plano de saúde
- VR de R$ 21,50 /dia
- VA de 106,00 / mês
- HomeOffice

## Requisitos

* Praticidade com Ruby on Rails (Mínimo de 1 ano de experiência)
* Experiência em design de APIs e web services REST.
* Experiência na construção de aplicações WEB e produtos escaláveis
* Experiência com Banco de Dados tanto relacionais quanto não relacional (MongoDB, MySQL e PostgreSQL são pontos positivos)
* Experiência com aplicações NodeJS
* Experiência com serviços de fila e mensageria (Sidekiq, RabbitMQ)
* Preocupação com qualidade de código. Vivência com TDD ou BDD, testes funcionais e de performance.
* Conhecimento com Redis e Memcached serão diferenciais
* Experiência com GIT e ambientes onde a integração continua, automação de ambientes e releases é prioridade.

**Diferenciais:**
* Conhecimento e skill's em Frontend
* Virtualização de ambientes

## Contratação

- Vaga CLT-FULL

## Nossa empresa

[R7.com](https://www.r7.com)

## Como se candidatar

Por favor envie um email para apinto@rederecord.com.br com seu CV anexado e pretensão salarial para vaga CLT - **enviar no assunto: Oportunidade BackEnd**

**Comment by Pedro-Souza** [comment]
Ué, férias é um beneficio?

**Comment by reginaldojunior** [comment]
Vaga preenchida?
