### ISSUE TITLE
[São Paulo - SP] PHP Developer na Flatbox

### ISSUE THREAD

**Issue by darrudanoo** [backend-br/vagas#630]
## Descrição da vaga

Procuramos front end para nosso time, irá trabalhar em sites, sistemas e aplicativos.

## Local

Escritório, São Paulo - Santo Amaro _(ao lado da estação de trem e metrô)_

## Benefícios

- Oportunidade Crescimento
- Plano de desenvolvimento individual
- Ferias Coletivas

#### Diferenciais

- Horário flexivel
- No dress code
- Ambiente
- Participação em outros projetos com ideias e sugestões

## Requisitos

**Obrigatórios:**
- Javascript (jQuery/ES6/Ajax)
- HTML5/CSS3
- Boa lógica de programação
- OOP
- Sólidos conhecimentos em PHP
- Conhecimentos em MySQL
- Experiência com Controle de Versão (SVN ou GIT)

**Desejáveis:**
- AngularJS e  BackboneJS
- NPM, Bower e Composer
- Experiência com servidor Linux
- Experiência com IONIC e ES6
- Experiência com Design Responsivo 
- Curso superior em Tecnologia (Completo ou cursando) 

## Contratação

PJ

## Nossa empresa

A Flatbox é uma empresa de inovação com grande foco em projetos de tecnologia e startups, temos um time multidisciplinar e apaixonado por fazer acontecer. Usamos diversas abordagens, metodologias, muita empatia e tecnologia pra entregar soluções que encantam nossos clientes!

## Como se candidatar

Por favor envie um e-mail para atendimento@grupoflatbox.com.br com:
- Assunto: Vaga FrontEnd
- Seu CV anexado 
- Faça o teste: http://mrcoach.com.br/teste-perfil-comportamental-disc.php
- Envio o print do resultado anexado ao email

## Labels

- PJ
- Júnior
- Pleno
- Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
