### ISSUE TITLE
[Belo Horizonte-MG] Desenvolvedor Java Web Sênior [3MW]

### ISSUE THREAD

**Issue by DanielLCintra** [backend-br/vagas#631]
Desenvolvedor/Programador Java WEB – Sênior

Precisamos de 2 desenvolvedores com o perfil abaixo para atuar na operação de um cliente. Se você tem o perfil listado e mora em BH envie seu currículo que iremos analisar e agendar uma entrevista.

Atividades:

•    Desenvolvimento de software baseado em JAVA – Oracle;

•    Participação ativa no desenvolvimento de produto;

•    Garantia da qualidade do código e resultado final.

 

Requisitos:

•    Java Enterprise Edition (Java EE);

•    Spring;

•    JPA;

•    Hibernate;

•    SOAP/XML;

•    RESTful APIs;

•    JSON;

•    JavaScript/jQuery;

•    Ajax;

•    HTML;

•    CSS;

•    Bancos de Dados Oracle;

•    Apache TomCat.

Salário a combinar, trabalhamos com a pretensão salarial

Vaga CLT com benefÍcios (VR, VT, Plano de saúde (50 % do valor), Seguro de Vida.

O trabalho será alocado em um cliente, portanto para essa vaga não é possível trabalho remoto.

Interessados enviar currículo com pretensão salarial para daniel.cintra@3mw.com.br.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
