### ISSUE TITLE
[Florianópolis, São Paulo e Joinville] Senior Backend Developer na Resultados Digitais

### ISSUE THREAD

**Issue by kaiofelipejs** [backend-br/vagas#633]
Na tribo de OnGoing somos responsáveis por manter e evoluir a plataforma RD Station. Times multidisciplinares, responsável por diversas features e por criar componentes e estruturas cross áreas. Nosso foco é criar soluções que suportem até 10x o nosso tamanho atual e que sejam escaláveis até 100x! E aí, aceita o desafio?

Buscamos pessoas amantes de tecnologia e que estejam dispostas a contribuir e impactar a vida de mais de 12 mil clientes. Nosso foco é escalabilidade, e para isso precisamos de gente muito boa a fim de colocar a mão no código e fazer acontecer! Se você não conhece de marketing digital não tem problema, nós te ensinamos. ;)

Principais habilidades e conhecimentos:
- Resolver problemas e implementar soluções envolvendo múltiplos times e profissionais;
- Amar entregar software bem testado e bem desenhado;
- Sólido conhecimento nas linguagens Ruby, Go, NodeJS, Java ou Python
- Experiências com bancos de dados como: MySQL, PostgreSQL, MongoDB ou Redis;
- Conhecimento em IaaS (Infrastructure as a Service) como: AWS, Azure ou Google Cloud; 

Veja mais sobre nós aqui: http://tm-station.rds.land/engineering

Me envie um e-mail para agendarmos um bate papo: kaio.silva@resultadosdigitais.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
