### ISSUE TITLE
[Remoto] Back-end PHP Developer Junior @ Vesti

### ISSUE THREAD

**Issue by abomfim** [backend-br/vagas#6339]
## Nossa empresa
A Vesti é uma plataforma de e-commerce de atacado e varejo para fabricantes e marcas de moda!

## O que esperamos de você:
- Curiosidade e muita vontade de aprender
- Disciplina
- Conhecimento em PHP, GIT, Laravel e banco de dados
 
## Sobre a vaga:
- Modelo de contratação: PJ
- Local de trabalho: Remoto / Home office
- Horário de trabalho: Comercial / Semi-flexível
- Ritmo de trabalho: 30 horas semanais
 
## O que esperar da Vesti:
- Mentoria e feedbacks
- Ambiente informal e amigável
- Cultura ágil
- Trabalho remoto (sempre trabalhamos assim com ou sem pandemia)
- Trabalho com as tecnologias mais atuais do mercado como: AWS, Firebase, Flutter, Angular, Docker, Redis etc.
- Grandes desafios!

## Tem interesse pela oportunidade?
Envie seu currículo com o título da vaga no assunto para: rh@vesti.mobi

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by douglasz1** [comment]
aplicar?

**Comment by elandro18** [comment]
Opa tudo bem, acabei de enviar meu currículo, me oferecendo para vaga, tenham uma ótima semana
