### ISSUE TITLE
[Curitiba, PR] Desenvolvedor  C++ / QT

### ISSUE THREAD

**Issue by kvilela** [backend-br/vagas#634]
Local

Home Office, Curitiba - PR

Contratação
CLT

Benefícios:
Convênio médico Bradesco Saúde nacional
Convênio odontológico Sul América
 VR 17,50 dia 
 VT 
Seguro de vida 
PLR  

**Requisitos:**
•Metodologia Ágil (XP/Scrum/Kanban)
•GIT
•Experiência com C++ Moderno (11 ou superior)  
•Entendimento de toda a pilha de programação, linkagem, hardware, código binário, endereçamento de memória, etc…
•Experiência com templates, Generic Programming, e metaprogramação estática.
- Uso frequente de técnicas de programação funcional
- Conhecimentos de DOD (Data Oriented Design)
- Experiência com desenvolvimento de servidores
- Experiência com processamento de imagens é um diferencial
•Conhecimentos sólidos em geradores de build (CMake, QMake, etc) e configuração
- Experiência com Conan é um diferencial
• Conhecimento avançado de  desenvolvimento em Windows e/ou Linux.   
- Experiência com   desenvolvimento MacOS X é um diferencial
• Conhecimento profundo da STL e Boost 
-   Experiência com Qt é um diferencial

**Atividades:**
• Realizar análise técnica de demandas baseado no projeto de concepção do produto 
• Planejar e implementar os requisitos do software dentro dos padrões de qualidade da empresa 
• Conhecer, seguir a metodologia, critérios e processos de desenvolvimento de software vigentes 
• Elaborar e executar testes unitários e integrados para garantir a qualidade do produto, prevenindo futuras falhas/bugs  
• Realizar a gestão de configuração e monitoramento do ambiente de P&D, garantindo a integridade e segurança 
• Diagnosticar e corrigir falhas em produtos 
• Monitorar tendências e tecnologias para contribuir com a melhoria de processos relacionados ao desenvolvimento dos produtos da empresa 

**Nossa empresa**
Nosso cliente é uma das maiores desenvolvedoras brasileiras de soluções para gestão hospitalar, medicina diagnóstica e laboratorial, responsável pelos sistemas PACS, HIS, RIS e LIS.

**Como se candidatar**
Por favor envie um e-mail para karina.vilela@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga  Desenvolvedor  C++ / QT (github/ Desenvolvedor  C++ / QT)

Labels
Home Office
CLT
CONAN
C++
DOD
MacOS X

**Comment by ghost** [comment]
aberto ainda ?

**Comment by kvilela** [comment]
Oi Dione, bom dia!

Sim.

Karina Parise Vilela

Em qui, 2 de mai de 2019 23:44, Dione Carlos Sousa Ferreira <
notifications@github.com> escreveu:

**Comment by rethRed** [comment]
Eu fiquei curioso. Será que depois de *4 anos ainda estão precisando de um desenvolvedor qt?
