### ISSUE TITLE
[Centro RJ] Desenvolvedor PHP Júnior @Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [backend-br/vagas#6368]
Descrição:

O trabalho a ser realizado consiste no desenvolvimento de novas rotinas de software, bem como na sua manutenção. O(a) Desenvolvedor(a) deverá colocar em prática os projetos que o Analista lhe destinar e, pensando na melhoria constante do sistema, também deverá propor melhorias.

Por fim, o(a) desenvolvedor(a) realizará testes de software para garantir seu bom funcionamento. Para esta vaga não é necessária experiência comprovada, porem é importante que o profissional já tenha tido contato com desenvolvimento em projetos pessoais ou de terceiros. Espera-se que o profissional domine bem as linguagens PHP e JavaScript.

Requisitos:

Ser criativo e proativo
Ter bom conhecimento sobre boas práticas de desenvolvimento php e devops
Conhecimento em PHP | javascript | jquery | Banco de Dados
Programação OO e Estruturada
Ter disponibilidade para trabalhar no centro do Rio de Janeiro.

Desejável:

Curso superior na área de computação, cursando ou finalizado
Controle de versão git
Css e html
Boa concentração e relacionamento interpessoal
Proatividade

Benefícios:

VR
Ajuda financeira para cursos
Um ambiente de trabalho diferente e inovador com uma cultura que valoriza as pessoas e a entrega de resultados
Um time que tem os nossos valores em seu dna
Muitos desafios e aprendizados
Oportunidade de eventos e cursos que deixem você mais próximo dos melhores do mercado
Os melhores happy hours

CVs via rh@hagloo.com

**Comment by hugomaatheus** [comment]
onde posso me candidatar?

Em seg., 12 de jul. de 2021 às 13:06, GIOVANI POLETO DA SILVA <
***@***.***> escreveu:
