### ISSUE TITLE
[Rio de Janeiro] Back-End Developer Python Pleno/ Sênior na [B2W Digital]

### ISSUE THREAD

**Issue by MalletJorge** [backend-br/vagas#639]
### A Maior Plataforma Digital da América Latina esta contratando

A B2W tem a missão de manter e evoluir uma das plataformas mais complexas e robustas da internet. Uma enorme parcela de tudo que é vendido online no Brasil tem como vitrine os sites Americanas.com, Submarino, Shoptime e Sou Barato.
A Sieve, unidade de Negócio da B2W Digital, realiza um trabalho estratégico para o e-commerce, fornecendo soluções de análise e monitoramento para fabricantes, varejistas e sellers que atuam em marketplaces.

No Time de Crawling, temos a missão de manter e evoluir a captura de dados de milhões de páginas de produtos do e-commerce brasileiro! Esses dados são utilizados no desenvolvimento de soluções de inteligência de preços para nossos clientes, garantindo que eles sejam mais competitivos e tenham a possibilidade de oferecer o melhor preço para o consumidor final :)

No nosso dia-a-dia temos que lidar com números bem expressivos:

- Mais de 10 milhões de produtos monitorados diariamente
- Dezenas de milhares de páginas visitadas a todo minuto
- Mais de 3 mil sites monitorados
- Terabytes de dados sendo capturados todos os dias.

Somos os pioneiros e líderes de mercado em inteligência de preços. Para isso, criamos e operamos o mais robusto sistema de captura de dados do país! Por trás dele, está uma arquitetura state-of-the-art que combina os padrões e tecnologias mais modernas do mercado. São dezenas de aplicações diferentes rodando em um ambiente containerizado de alta-escalabilidade que funciona 24/7.

A plataforma da B2W foi criada para conectar pessoas, negócios, produtos e serviços. Temos diversos outros negócios que impulsionam uns aos outros, gerando uma enorme sinergia. E quem sai ganhando no final são os nossos clientes.

### Requisitos e qualificações: 
**Esperados:**

- Forte base em programação orientada a objeto
- Valoriza qualidade, código limpo, design patterns, estruturas de dados e boa documentação de código
- Aprende rápido e é movido a desafios
- Tem interesse em engenharia reversa
- Experiência na realização de testes automatizados e refatoração de código
- Graduação em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente
- Confortável com Ambiente Unix
- Está familiarizado com GIT
- Conhece o funcionamento do protocolo HTTP
- Você é um bom comunicador e é capaz de dialogar
- Lê e escreve em inglês. Você não precisa ser fluente, mas precisa estar apto a ler documentações, debater soluções em fóruns técnicos e escrever o código-fonte dos nossos sistemas.

**Diferenciais:**

- Experiência em Python
- Experiência em programação assíncrona ou relacionada a arquitetura orientada a eventos
- Experiência com arquiteturas distribuídas e sistemas de filas.
- Confortável com soluções de containerization, como Docker, por exemplo
- Busca contínua por melhorias no time em que trabalha, no fluxo de trabalho e em você mesmo
- Experiência com metodologia ágil
- Experiência open-source em algum projeto relevante
- Trabalhou em algum projeto utilizando tecnologias como: Rabbitmq, Elasticsearch, ES6, task schedulers, Redis 

### Como funciona o nosso processo seletivo?

﻿Nosso processo começa com uma triagem de currículos e experiências. Em seguida, enviamos um desafio técnico prático em Python para o candidato resolver no seu próprio prazo. O desafio é proposto para avaliarmos a capacidade do candidato em resolver um problema, sua linguagem de programação e habilidades técnicas. Acreditamos que encontrar boas pessoas é um trabalho tanto dos candidatos quanto dos recrutadores, por isso, sempre enviamos um Feedback completo com likes e dislikes. Após isso, você será convidado para uma entrevista comportamental remota com o time de recrutamento. Quando bem sucedido, nosso processo é finalizado com uma visita ao nosso escritório, onde o candidato conhece nosso time, faz perguntas, conversa sobre a execução do seu desafio e nos conta sobre a sua experiência.
 
### Curtiu?
_**Benefícios**_
- VR
- Plano de Saúde
- Plano Odontológico
- Trabalhar e aprender tecnologias novas
- VT
- Ambiente orientado para maximizar o bem estar do time

**Regime**
- CLT
- Alocado

_**let's Go! Let's Elevate!**_
https://b2w.gupy.io/jobs/21790

_Quer ficar sabendo de todas as nossas vagas?_
https://t.me/Vagastech

**Comment by MalletJorge** [comment]
Fala, galera 
Ainda estamos com vagas abertas!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
