### ISSUE TITLE
[São Paulo] Backend NodeJS Developer na Dailyltd

### ISSUE THREAD

**Issue by caioalonso** [backend-br/vagas#64]
## Sobre a Daily

Somos uma startup focada em aplicativos mobile por assinatura vendidos na app store (B2C). Somos
uma empresa jovem e pequena, mas temos milhares de assinantes em mais de 120 países.

Trabalhamos com um portfólio de produtos divertidos, desenvolvidos em ciclos curtos.

Oferecemos uma oportunidade única de carreira aos nossos profissionais:
- Responsabilidade, por conta da nossa equipe enxuta;
- Crescimento profissional e financeiro, acompanhando o nosso, inclusive com possibilidade de bônus e participação em equity;
- Experiência e aprendizado ricos, por conta do nosso portfólio diverso e ciclos curtos

## Responsabilidades
- Desenvolvimento do back-end para os apps da Daily, utilizando principalmente bancos Google Firebase/Firestore e Cloud Functions (Node.js)
- Outras ferramentas (por exemplo Rails/Postgres) podem ser usadas quando apropriado
- Desenvolvimento de ferramentas de analytics para uso interno

## Possibilidades de Progressão de Carreira Incluem:
- Continuar com foco em desenvolvimento, em posições mais seniores (especialista)
- Liderança técnica/CTO
- Gestão de produto (incluindo aspectos de usabilidade e mercado)

## Requisitos
- Vontade real de trabalhar numa startup em crescimento e atitude, maturidade e comprometimento necessários para isso
- Bom raciocínio lógico e competência em programação
- Boas práticas de testes automatizados e source code management
- Familiaridade com Node.js, Firebase, Cloud Firestore, bancos de dados não-relacionais, microservices, arquitetura serverless e serviços em nuvem (ex. AWS)
- Conhecimento de ferramentas de busca como Algolia e Elastic, desenvolvimento mobile, JavaScript client-side e outros frameworks além do Node, outros frameworks e linguagens back-end (e.g. Rails) e bancos de dados relacionais (e.g. SQL/Postgres) são bem-vindos.

## Como se Candidatar
Por favor envie um email para talent@dailyltd.com com CV, pretensão de salário e regime de contratação. Perfis de GitHub, LinkedIn, links para apps publicados e outros projetos interessantes são todos bem-vindos.

**Comment by reginaldojunior** [comment]
Vaga preenchida?
