### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Back End na MERCATÓRIO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#640]
### Sobre a empresa: Mercatório

A Mercatório é uma startup mineira fundada em 2016, que acredita que o mercado jurídico-financeiro precisa se tornar mais moderno e eficiente com a incorporação de novas tecnologias. Para fazer isso, mapeamos e analisamos processos judiciais de tribunais de todo o Brasil, fornecendo informações qualificadas e estruturadas para o mercado. Ajudamos, assim, pessoas e fundos de investimentos a tomarem decisões com maior agilidade e assertividade, gerando bons negócios para ambas as partes.

### Descrição: Ocupações do cargo

Manter e evoluir nossa API REST;
Propor melhorias ativamente e participar de todo o ciclo de desenvolvimento do produto;
Liderar conversas produtivas com a equipe jurídica sobre o produto;
Criar integrações com serviços externos, como Assertiva, SERASA Experian, Neoway, IBM Watson

### Benefícios:

Vale-transporte;
Vale-refeição;
Plano de saúde;
Horário flexível;
Você deverá conhecer
Ruby on Rails

### Diferenciais:

AWS
Postgre

### Gostamos de pessoas:

Pró-ativas;
Inovadoras;
Abertas ao crescimento;
Gostem de conhecimento;
Bom relacionamento interpessoal; 

### Informações complementares:

A Mercatório é a (r)evolução do mercado de Direitos Creditórios e Precatórios! Atuamos baseados em 3 pilares:

Informação: Facilitamos a consulta de informações sobre o processo judicial e as cessões de crédito realizadas.

Simplificação: Através de algoritmos criados pela nossa equipe, simplificamos o processo de análise de documentos e de compra do Precatório.

Conexão: Conectamos diretamente credores de Precatório e compradores, além de disponibilizar uma plataforma personalizada para gestão de processos.

Fintech, nascida e criada no San Pedro Valley. Nosso produto está conquistando mais clientes todos os dias e precisamos da sua paixão pela tecnologia para crescer de forma escalável.

### Labels: 

Alocado
Pleno/Júnior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
