### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Back End (Elixir, Go e Typescript) na DITO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#642]
### Sobre a empresa: Dito

A Dito é uma empresa de tecnologia que nasceu em meio à atmosfera de inovação do San Pedro Valley, em Belo Horizonte. Nós desenvolvemos uma plataforma capaz de impactar milhares de usuários de forma segmentada, inteligente e multicanais. No nosso time, todo mundo é FERA: pega e Faz, com foco e planejamento; age com Ética e transparência; se preocupa com o Resultado dos clientes (internos e externos); trabalha com Alegria e tem sede por Aprender. Nós estamos localizados no coração da Savassi, em Belo Horizonte, e temos bases de apoio também em São Paulo e no Rio de Janeiro. Nossa equipe hoje conta com 50 FERAs que ajudam marcas como TIM, Ingresso.com, Chilli Beans, Araujo, Track&Field, Havaianas, Chico Rei, Farm e Zee.dog a livrarem o mundo do marketing genérico.

### Descrição: Ocupações do cargo

Garantir desempenho, resiliência e extensibilidade para implementação de novas funcionalidades;
Desenvolver códigos e sistemas com qualidade e robustez;
Melhorar cada vez mais nossos processos, trazendo as melhores práticas e soluções.

### Aptidões e qualidades

Aptidão com linguagens funcionais;
Grande expertise em back-end;
Facilidade e disposição para mentorar tecnicamente desenvolvedores menos experientes;
Sede por aprendizado para se aprofundar e ser especialista na área;
Habilidade de adaptar-se rapidamente às mudanças de contexto e prioridade.

### Benefícios:

Vale transporte;
Vale refeição ou alimentação (R$20,60 por dia);
Assistência médica (Unimed);
Lanche na empresa;
Horários flexíveis;
Sem dress code por aqui;
Contato com novas tecnologias e tendências de mercado;
Um ambiente incrível :)

### Informações da empresa

A Dito é uma empresa de Tecnologia em sua essência. Por isso, nossos Desenvolvedores são o coração do nosso time. Com experiências e níveis de senioridade diversos, nossa equipe de Desenvolvimento é responsável por garantir uma boa experiência de uso da nossa plataforma, promovendo melhorias no produto e desenvolvendo novas funcionalidades.

Nós acreditamos no trabalho em equipe, no compartilhamento de conhecimentos e no uso de boas práticas de engenharia de software para construir as melhores soluções para os nossos clientes.

### Labels:

Alocado
Pleno/Senior

### Candidatar: http://bit.ly/dito_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
