### ISSUE TITLE
[São Paulo] Estágio em back-end Ruby on Rails no Blumpa

### ISSUE THREAD

**Issue by rfoel** [backend-br/vagas#644]
## Descrição da vaga
Jovem universitário com interesse e experiência (mesmo fora do mercado de trabalho) em desenvolvimento de aplicações web com Ruby, PostgreSQL, JavaScript, entre outras tecnologias web, para atuar no apoio à implementação de funcionalidades em um sistema de médio porte. Ágil, interessado, responsável, disponível e que busque superar aquilo que lhe é solicitado.

## Local
Rua Cláudio Soares , 72, Pinheiros - São Paulo, SP

### Desejável
- Ruby
- Ruby on Rails
- PostgreSQL
- REST APIs

## Contratação
Estágio
Bolsa a combinar

## Nossa empresa
Blumpa Tecnologia é uma startup com sede em São Paulo, em fase de expansão e que opera uma plataforma digital para contratação de serviços de limpeza pela internet, por meio de website ou aplicativos. O ambiente de trabalho é dinâmico e descontraído, com foco em inovação e desenvolvimento de soluções criativas que facilitem a vida de clientes e profissionais usuários do sistema. Prezamos códigos bem feitos, para serem lidos por máquinas e humanos, conforme as melhores práticas de desenvolvimento web. Venha fazer parte de um time que está revolucionando o modo de contratação de diaristas na maior cidade da América Latina!

## Como se candidatar
Envie um email para rafael@blumpa.com com seu CV anexado e links de projetos, GitHub, etc. 

## Labels
- Ruby
- Ruby on Rails
- Estágio
- Alocado

**Comment by soutothales** [comment]
Esse estágio teria a possibilidade de ser remoto para quem mora longe de SP?

**Comment by rfoel** [comment]
@soutothales infelizmente não. Apenas alocado.
