### ISSUE TITLE
[Remoto] Full Stack Engineer na Kenoby

### ISSUE THREAD

**Issue by alanssimoes** [backend-br/vagas#646]
### O que você precisa ter
- Experiência profissional em desenvolvimento de software;
- Experiência em (ou vontade de aprender) as linguagens da nossa stack: React.js, Node.js e Angular.js;
- Habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento;
- Experiência com escrita e manutenção de testes unitários;

### O que vamos amar se você tiver

- Conhecer bastante e/ou ter trabalhado com base de dados NoSQL (MongoDB), Sistemas de Filas e ElasticSearch;
- Conhecer bastante e/ou ter trabalhado com Frameworks HTTP (Express, Koa, etc);
- Conhecer bastante e/ou ter trabalhado com Frameworks Visuais (Bootstrap, Material Design,etc);
- Conhecer bastante e/ou ter trabalhado com HTML5, CSS3, SASS;
- Conhecer bastante e/ou ter trabalhado com AWS ou similares;

### Quem nós somos
Aqui na Kenoby nós estamos transformando a maneira como as empresas recrutam as pessoas no Brasil e no Mundo! Criamos um produto que tem como objetivo gerenciar o processo seletivo de ponta a ponta, automatizar o trabalho dos recrutadores e engajar os gestores no processo. 

Nossa missão é de colocar a pessoa certa na vaga certa, e nosso sonho de acabar com o viés na contratação, focando no potencial e qualificações das pessoas, e queremos sua ajuda para atingir esse grande objetivo!

Em 2018, triplicamos nossa equipe e fomos considerados a startup SAAS que mais cresceu no país e a projeção para os próximos anos é crescer ainda mais!

Trabalhamos em um ambiente extremamente descontraído e com bastante estímulo para inovação. Se você gosta de desafios, manja dos códigos, se preocupa com a qualidade do seu trabalho e está disposto a aprender muito, essa é sua vaga!

### Aqui você irá:
- Causar impacto na vida das pessoas, construíndo um produto focado em otimizar o recrutamento, removendo o preconceito na contratação;
- Colaborar ativamente e com autonomia no desenvolvimento e concepção de produtos disruptivos;
- Implementar telas incríveis desenvolvidas pelo nosso time de Design;
- Trabalhar em pequenos squads que utilizam metodologias ágeis para entregar valor constante aos stakeholders;
- Garantir a qualidade e ser dono do seu código;
- Aprender muito e compartilhar conhecimento;
- Ter a possibilidade de escolher trabalhar Home Office ou Presencialmente (no Cubo Itaú!);

Estamos focados em disruptar o mercado de Recrutamento e Seleção global e queremos as melhores pessoas conosco nesta jornada!!

Gostou do desafio?! Acha que você pode ser uma dessas pessoas?! Estamos ansiosos para sua candidatura!

Super importante: Para nós, não faz a menor diferença qual sua localização, idade, raça, cor, religião, identidade de gênero, orientação sexual ou formação. O que nos importa é o quanto seu perfil e princípios estão alinhados com nossos objetivos.

### Como se candidatar
Se inscreva na URL:
 https://jobs.kenoby.com/kenoby/job/full-stack-software-engineer/5c0058cee90cdb57f9d88870

### Labels
Remoto
PJ
Full time
Pleno/Senior

**Comment by rodineicosta** [comment]
Aplicado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
