### ISSUE TITLE
[São Paulo/SP] Backend Developer na Programmer's

### ISSUE THREAD

**Issue by ProgrammersRecrutamento** [backend-br/vagas#647]
Requisitos:

•	Experience on developing back-end systems 
•	WCF General Development 
•	Basic distributed communication w/ C# (HTTP, TCP, ports etc.) 
•	WebSocket 
•	Git 
•	Unit Tests development w/ C# 
•	Service Fabric 
•	REST Services Development 
•	Azure General Knowledge 
•	Container - Docker 
•	ServiceBus 
•	Theoretical Knowledge about Tests and its Concepts 
•	Experience on automated tests for back-end services 
•	ProtoBuf Serialization 

Enviar currículos para ana.fraga@programmers.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
