### ISSUE TITLE
[São Paulo] Sr Backend Engineer na 99

### ISSUE THREAD

**Issue by BrunoYY** [backend-br/vagas#648]
## Descrição da vaga

**About the job:** We are looking for people who are passionate about building robust, scalable, real-time and distributed systems.
We want people who have ownership and do not settle for anything that is not incredible!We deal with challenging situations on a daily basis and our job is to address them through data analysis, machine learning and technology applied on safety.
You will be part of a team which primary concern is about safety for passenger and drivers. We are working very hard to prevent robbery, discrimination, harassment and any kind of physical or psychological violence. 
You will be handling any bugs, provide workarounds, and escalate unresolved issues to the development team. 
Your work is key to the success of making transportation better to everyone. This position requires strong multi-disciplinar technical skills and result-driven approach.

## Local

Escritório, São Paulo - Berrini

## Benefícios

- Plano de saúde
- Seguro de vida
- VR/VA de R$ 30/dia
- VT
- GymPass
- Cerveja e bolo toda sexta :D

## Requisitos

**Obrigatórios:**
- Pelo menos 4 anos de experiência comprovada com desenvolvimento backend;
- Inglês intermediário;
- Experiência com Java e APIs Restful.

**Diferenciais:**
- Conhecimento de Scala;
- Experiência com arquitetura de sistemas;
- Experiência com frontend.

## Contratação

CLT

## Nossa empresa

**About the company:** In the street, at work, by Taxi or Pop, as a driver or passenger, we are the starting point for thousands of people every day and we also want to be part of their professional path. 99's mission is to revolutionize urban mobility and transform the life of people. We are a Brazilian startup founded in 2012 and five years later became the first Brazilian unicorn (startups that are valued at one billion dollars). Now, 99 is part of Didi Chuxing, the world's largest application-driven transport platform.

Diversity goes beyond ethnic, physical, sexual, sensory and gender differences! Our goal is to cultivate an inclusive environment by focusing on high performance and valuing diversity in our work environment. We respect and value the differences!
Come and be part of a diverse environment where your ideas and opinions will always be heard. Inclusion and diversity are in our recruitment principles! 

## Como se candidatar

Se candidate diretamente no nosso site!
https://carreiras.99app.com/jobdetail/?vagaid=742db50d-88b5-47e7-add5-894a0cbae81b

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruno.yoshioka@99app.com

## Labels

- CLT
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
