### ISSUE TITLE
[São Paulo] Back-End [ATG Consulting]

### ISSUE THREAD

**Issue by ATGConsulting** [backend-br/vagas#649]
Descrição de Responsabilidades:
- Responsável pelo Desenvolvimento de plataforma tecnológica Fin-x, incluindo a programação e arquitetura
- Interação com os sócios da Fin-x para o desenvolvimento de soluções Back-end e integração e suporte à equipe de desenvolvimento

Qualificações Gerais: 
- Nível Sênior, com mais de 4 anos experiência na atividade
- Conhecimento e experiencia em desenvolvimento Back-end
- Programação:  em .Net , Angular (desejável) ,  banco de dados SQL Server e Python (desejável)  
- Skill de arquitetura de sistemas e soluções em nuvem                                                      - Capacidade de trabalho em grupo e colaboração
- Facilidade de comunicação com equipe de desenvolvimento
- Conhecimento da área de saúde (desejável)
Local de trabalho: Vila Olímpia – São Paulo
Interessados, enviar currículo para o e-mail  vagas@atgconsulting.com.br com título: “Vaga Desenvolvedor de Back-end Sr”. 
Remuneração:  salário + participação acionária na empresa

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
