### ISSUE TITLE
[REMOTO] Desenvolvedor PHP Laravel + JS na SSX Digital

### ISSUE THREAD

**Issue by guireisbh** [backend-br/vagas#652]
Procuramos Profissionais Experientes, com conhecimentos em desenvolvimento de software e, acima de tudo, dispostos a enfrentar desafios e problemas.

**Formação e Experiência:**

Não é necessário curso superior.
Boa leitura em inglês.
Experiência mínima de 2 anos atuando como desenvolvedor.

**Habilidades:**

Muito PHP (Laravel de preferência)
JavaScript (muito), HTML5, CSS3.
Frameworks de mercado como Vue, React ou Angular (Angular 1, 2 e 4 de preferência).
Desenvolvimento e utilização e API REST.
GIT
Testes são bem-vindos.
Bom raciocínio lógico.
Inteligência emocional e disposição para resolver problemas.
Os requisitos mudam, os códigos também, esteja disposto a mudanças.

**Diferenciais:**

Experiência com Wordpress, Woocommerce, Magento, Desenvolvimento de Plugins.
Experiência com Azure e AWS.

**Atribuições:**

Planejar e discutir soluções de implementação com a equipe.
Estudar e aprender bastante sobre novas tecnologias
A vaga é para trabalho remoto. Mas é de 40h semanais. Dedicação Exclusiva.
O regime de contratação é PJ.
Bateu as metas? Temos bônus de produtividade

A contratação é imediata.

Interessado? Envie seu currículo para vagas@ssxdigital.com.br com a _remuneração desejada_.

Tipo de vaga: Tempo Integral

**Comment by ghost** [comment]
Ainda está disponível?
