### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Full Stack na PFG

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#653]
### Sobre a empresa: PFG

Somos uma empresa de gerenciamento de investimentos que utiliza big data para determinar e recomendar as melhores opções de compra. Nós alinhamos investimentos de acordo com o perfil e objetivo de cada cliente e gerencia os relatórios, faturamento, impostos além de centralizar vários canais de investimento em um só lugar.

### Requisitos:

Experiência com JavaScript, HTML e React, NodeJs;
Boa leitura em inglês;
Lógica de programação;
Habilidade com contas e cálculos;
Pró-atividade;
Sangue nos olhos;

### Oferecemos:

Salário compatível com o mercado;
Home office

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Informações complementares:

O profissional irá trabalhar em Home Office e quando necessário, ir ao escritório no bairro Liberdade em BH.

### Labels:

Alocado
CLT
Senior
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
