### ISSUE TITLE
[REMOTO] Back-end Developer JAVA - ioasys

### ISSUE THREAD

**Issue by KennVieira** [backend-br/vagas#6530]
## Descrição da vaga
Para a vaga de Pessoa Desenvolvedora Back-end Java, buscamos um profissional que saiba trabalhar em equipe para agregar valor nos projetos em que trabalha. Este profissional ficará responsável pelo desenvolvimento back-end (Java) de grandes empresas do mercado nacional e internacional.
## Local
100% Remoto! 
## Benefícios
Regime CLT ou PJ;
Liberdade para exercer suas habilidades em um ambiente
dinâmico e horizontal;
Jornada flexível;
Não temos dress code, mas respeitamos o do cliente;
PowerUp semanais;
Acesso à plataformas de cursos online;
Curso de Inglês (In Company);
Day Off – Birthday.
## Requisitos
Obrigatórios
Sólidos conhecimentos em programação JAVA;
Familiaridade com estruturas XML, incluindo XSD, DTD, etc;
Conhecimentos em funcionalidade geral de serviços da WEB (SOAP, REST, autenticação, etc);
Conhecimentos em conceitos básicos de rede;
Familiaridade com uma linguagem de programação (Java, TCL, etc...);
Conhecimento de banco de dados SQL;
Sólidas habilidades para solução de problemas.
 
Desejáveis
Atuação com desenvolvimento na plataforma.
## Contratação
PJ e CLT a combinar
## Nossa empresa
A ioasys é especialista em criar soluções únicas para empresas ousadas. Somos experts em trazer o melhor do universo digital para nossos clientes e a transformar a sociedade, a repensá-la e a evoluí-la. Ajudamos marcas a inovar através da transformação digital e seguindo os princípios de metodologia ágil e abordagem centrada ao usuário, modificando a realidade das pessoas com tecnologia e inovação de ponta a ponta. Não somos apenas pensadores, somos realizadores! Estamos projetando um mundo mais acessível, conectado e intuitivo, como deveria ser.
Buscamos um time diverso, livre de preconceitos e aberto a todos os tipos de raças, cores, corpos e crenças. Nosso propósito estampado em nossas camisetas atuais "De Pessoas. Para Pessoas." traduz a importância de um ambiente heterogêneo, repleto de vivências e impressões da sociedade e suas necessidades.
Propiciamos um ambiente inovador dedicado ao crescimento, com profissionais incríveis e de aprendizado constante em escritórios que estimulam a criatividade e produtividade. Além do nosso horário ser flexível (trabalhamos de segunda a sexta), acreditamos na oportunidade de estarmos todos criando uma empresa que desenvolve soluções que afetam positivamente a vida de milhões de pessoas em diversos segmentos. Você estará em uma equipe horizontal e transparente, que não apenas valoriza suas ideias, mas também espera que você faça parte da construção da empresa com a gente.
## Como se candidatar
Por favor envie um email para kennedyvieira@ioasys.com.br com seu CV anexado - enviar no assunto: Vaga Java ou se inscreva através do link https://ioasys.gupy.io/jobs/906361

**Comment by italosantana** [comment]
**Feito!**
