### ISSUE TITLE
[REMOTO] Desenvolvedor PHP + JS - Samuel Faj

### ISSUE THREAD

**Issue by samuelfaj** [backend-br/vagas#654]
Olá pessoal, tudo bem?

Meu nome é Samuel Fajreldines, eu tenho uma micro empresa em Porto Alegre - RS aonde presto serviço de desenvolvimento para alguns clientes e desenvolvo alguns projetos. Como venho pegando mais trabalhos, preciso de um programador fera para me ajudar e crescer comigo.

**Quem eu busco?** Um programador nivel pleno que esteja interessado em uma mentoria hardcore para subir de nível (ficaremos skype e whatsapp quando você precisar) ou um programador senior que esteja querendo pegar algumas tasks a mais.

**O que preciso saber?** É indispensável que você manje de PHP e Javascript e que saiba lidar com o GIT. No dia-a-dia você vai lidar com Code Igniter, Angular e um pouquinho de Node.JS. Quanto mais você souber, melhor. Mas se não for um expert em um framework ou outro, eu te ajudo. PS: Se você já tiver trabalhado com Ionic Framework seria incrível.

**Carga Horaria:** Apenas dias úteis e não tenho uma carga horária requerida. Tenho algumas tarefas para fazer no dia. Se você resolver em 2 ou 12 horas, beleza! Uma palavra P-R-O-D-U-T-I-V-I-D-A-D-E. Mas creio que, na média, um pleno levaria em torno de 6 - 8 horas diárias e um senior 4h para baixo.

**Remuneração:** À combinar, variando de acordo com as tecnologias que você manja e nivel de conhecimento.

**Me interessei!**
Se você se interessou por trabalhar de casa, no ambiente que quiser, quando quiser, me manda um e-mail falando um pouquinho melhor de você e das coisas que já fez: samuelfajreldines@gmail.com

PS: Sou bem aberto a negociações então se você só pode trabalhar de pijama de bolinhas, nos dias pares, manda no e-mail! Podemos ajustar a melhor rotina possível. Preciso de mão-de-obra, quando e como a gente vê!

**Comment by diegoldnascimento** [comment]
Enviado! Fico aguardando um feedback. :)

**Comment by lucasperrotta** [comment]
Aguardando feedback ;)
