### ISSUE TITLE
[São Paulo] Desenvolvedor de API Azure - São Paulo

### ISSUE THREAD

**Issue by ProgrammersRecrutamento** [backend-br/vagas#655]
1.	Especificação dos Serviços: Alocação de um analista de API Pleno com sólidos conhecimentos em implementação do ciclo de vida de APIs.

Desenvolvedor de API Azure
•	Plataforma do Azure API Management, 
•	ferramentas do Swagger 
•	Azure Web App,
•	Capacidade de executar atividades de implementação do Azure API Management, e seus ambientes de testes, produção, desenvolvimento, associado a capacidade de migração de serviços existentes, de acordo com as diretrizes e priorização do cliente. 
•	Serviço de API Gateway, quanto a definição e documentação do ciclo de vida de APIs. 

Modelo de contrato: CLT – PI – SP 
Cargo/Atividade: Desenvolvedor de API Azure

	Convênio Médico: Unimed Nacional 
	Convênio Odontológico: Porto Seguro 
	Vale Refeição 
	Vale Alimentação
	Auxílio Transporte 
	PPR 
	Seguro de vida em grupo. 
	Gympass
	Auxílio Creche
 
Local de trabalho:  São Paulo

Enviar currículo para: thais.silva@programmers.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
