### ISSUE TITLE
[Maceió/Remoto] Dev Django Pleno/Senior na Ilhasoft

### ISSUE THREAD

**Issue by yvesbastos** [backend-br/vagas#656]
### Conheça a Ilha:
A Ilhasoft ('Ilha', se quiser economizar teclas) nasceu em 2012 no Nordeste do Brasil. Estamos escrevendo uma história que é um próprio testamento do nosso foco insaciável em busca de desafios cada vez maiores. Isso se traduz nos produtos que desenvolvemos, nos clientes globais que conquistamos e na confiança diária que recebemos em todos nossos serviços e produtos.

Como qualquer um que tem sede de crescer e ser cada vez maior, estamos buscando os melhores profissionais. Aqui temos um ambicioso objetivo: causar impactos positivos e palpáveis com a certeza que nossos clientes são melhores - também - por nossa causa. 

### Onde atuamos:
Nosso foco é o mercado ICT global. Temos projetos desafiadores nas seguintes áreas:

- Atendimento automatizado de suporte e cobrança ao cliente
- Deep Learning
- Chatbots inteligentes e NLP
- Consolidação, integração e coleta global de dados
- Aplicativos móveis e integração com todo o stack acima

Mesmo durante período de crise nacional dos últimos anos, ganhamos diversos prêmios e continuamos a expandir nosso espaço físico, número de colaboradores e faturamento. Temos um ambiente descontraído, somos 100% adeptos à metodologias ágeis e um açaí na nossa mão tem um resultado certo: papos profundos sobre tecnologia, música, série e animes.

### A gente quer você no time para:

- Crescer conosco à medida que desbravamos novos projetos
- Ter orgulho do trabalho que desenvolve
- Melhorar a cada dia
- Ter a certeza de ter contribuído para problemas de nossos clientes após um dia de trabalho desafiador
- Ajudar todos seus colegas de trabalho a completar o check list acima

### Para esta vaga, nós precisamos:
Desenvolvedor Python com experiência avançada no framework Django: 

- 3 anos de experiência em Django
- Domínio completo de Git Flow
- Experiência prévia em escrever e manter testes unitários
- Desejo por boas práticas de desenvolvimento e excelência técnica
- Conhecimento em servidores linux

### Você estará um passo à frente se:

- 2 anos no mercado de trabalho
- Contribuições em projetos open source
- Ao menos um projeto próprio de código aberto
- 3 meses ou mais de experiência Scrum
- Fluência em Inglês

### Para ser um de nós, não faz diferença:
A sua raça, de onde você vem (remote work is very welcome 🎉), ideologia política, idade, orientação sexual ou identidade de gênero. Queremos um time diverso, competente, respeitoso e alinhado com nossos princípios. 

### O que fazer?
Se inscreve aqui: http://www.ilhasoft.com.br/vagas/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
