### ISSUE TITLE
[Portugal] Outsystems Developer na Aubay

### ISSUE THREAD

**Issue by festaca** [backend-br/vagas#657]
![f67c935c-0608-4329-90ff-c1c8db3531d5](https://user-images.githubusercontent.com/41423757/49512108-df44ce00-f884-11e8-962d-be97591eaad6.png)
### **A nossa empresa**
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### **Benefícios**
Plano de saúde
Visto de Trabalho para Portugal
Cultura organizacional gerida pelo nosso Hapiness Manager
Horário flexível
Almoço grátis todas as sexta-feiras
Frigobar e café grátis
Eventos mensais com atividades diferenciadas
Apoio financeiro em deslocação e alojamento

### **Descrição da vaga**
Projetos diferenciados em vários setores de atividade utilizando tecnologia Outsystems em projetos Web e/ou Mobile para projetos nacionais e internacionais

### **Requisitos Obrigatórios**
Experiência em desenvolvimento Outsystems (pelo menos 2 anos)
Conhecimentos em programação orientada a objetos (Java, .NET)
Domínio da língua inglesa

### **Diferenciais**
Projetos internacionais web ou mobile que permitem contato com vários países
Experiência em lifetime e/ou BPT

### **Como se candidatar**
Por favor envie um email para fpiedade@aubay.com com seu CV anexado.

#Labels 
Outsystems
Java
Inglês
Vaga Internacional

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
