### ISSUE TITLE
[REMOTO | Natal-RN | São Paulo-SP] Back-End na Credere

### ISSUE THREAD

**Issue by juuh42dias** [backend-br/vagas#658]
O Credere é uma ferramenta para ajudar concessionárias de veículos a vender mais e melhor. Presente hoje em 18 estados brasileiros, movimentando cerca de 18 mil propostas de financiamento por mês e com mais de 7 mil usuários ativos.

## A oportunidade

Nos últimos anos conseguimos com uma equipe bem pequena evoluir o produto e ganhar destaque no seguimento de financiamento para veículos duas rodas. Esse trabalho nos trouxe para uma nova fase, aumentar a equipe para contar com mais de um time a fim de evoluir o Credere em novas frentes como produto.

## O que oferecemos

- Oportunidade de fazer diferença no seu trabalho
- Trabalhar com novas tecnologias
- Ambiente amigável, transparente e informal
- Horário flexível
- Trabalho remoto
- Plano de saúde
- Plano odontológico
- Vale alimentação

## Requisitos da vaga

- Experiência com alguma linguagem de back-end moderna (C#, Javascript, Go, PHP, Python, Ruby, Elixir)
- Conhecimento sobre testes automatizados
- Boas práticas de arquitetura de aplicação e organização de código
- Experiência com algum banco de dados relacionais (Postgres, MySQL, MariaDB ou Oracle)
- Vivência em ambientes ágeis (deploy, git como controle de versão, code reviews, etc)
- Comprometimento e ownership em organizar o seu próprio tempo e entregas

## Diferenciais

- Integração contínua, deploy contínuo.
- Alguma ferramenta de conteinerização (Docker, Docker Swarm, Kubernetes ou semelhantes)
- Experiência com ferramentas de monitoramento
- Conhecimento de banco de dados não relacional
- Experiência com infra-estrutura na AWS ou similar

## O que esperamos

- Gente do bem
- Boa comunicação e saber construir relacionamentos
- Empatia
- Experiência prática
- Compromisso com qualidade nas entregas

Usamos frameworks para o dia-a-dia, mas valorizamos bastante o domínio de fundamentos e do conhecimento da base - esses são os pontos que nos chamam mais atenção. Se você não se sente confortável com algum dos pré-requisitos, entre em contato mesmo assim, nos comprometemos em fazer a análise do seu perfil baseado nas suas qualidades.

## Avaliação técnica

Gostariamos muito de ver algum código seu que se aproxime de como você trabalha no dia-a-dia, pode ser contribuição pra projetos open-source, algum projeto seu desenvolvido para aprender alguma tecnologia ou durante algum curso, até mesmo avaliações que você fez para outras vagas/empresas. Não nos importamos com a fonte desde que consigamos avaliar os requisitos acima mencionados de maneira satisfatória. Ainda assim, caso você não possua uma amostra de código qual pode compartilhar, temos um teste pronto, e podemos lhe enviar após o contato inicial.  

---

Se você tem interesse em trabalhar conosco, envie uma breve apresentação, seu currículo/portifólio para credev@meucredere.com.br e lhe responderemos o mais breve possível.

## Faixa Salarial
R$ 3.000,00 a R$ 5.500,00

## Contratação
CLT Full Time

**Comment by guilherme90** [comment]
Olá. Vaga interessante!

CLT ou PJ ?

**Comment by juuh42dias** [comment]
Olá @guilherme90 a vaga é CLT Full time :)

**Comment by guilherme90** [comment]
@juuh42dias Okay.

Enviei email =)
Obrigado.

**Comment by tyronedamasceno** [comment]
Olá, a vaga é remoto em Natal ou São Paulo? Tenho interesse!

**Comment by juuh42dias** [comment]
Olá @tyronedamasceno , a vaga é REMOTO, presencial em Natal (nossa sede) ou presencial em SP. Mas temos flexibilidade com políticas de home office nestas duas cidades.

**Comment by tyronedamasceno** [comment]
Ótimo! Enviei e-mail, moro em Natal.

**Comment by gerdon** [comment]
Enviei email.

**Comment by rodineicosta** [comment]
Enviado.

**Comment by oliveira-andre** [comment]
enviado!

**Comment by ghost** [comment]
Enviado!

**Comment by ghost** [comment]
Enviando ... <3

**Comment by oliveira-andre** [comment]
Eu confirmei pelo Github que está conectado com este e-mail, mas o e-mail
pelo qual te enviei meu currículo foi andreoliveirar2d2@gmail.com

Abraços.

**Comment by miqueiasff** [comment]
Enviado

**Comment by devhttps** [comment]
Boa tarde @juuh42dias ainda estão aceitando currículos?

**Comment by juuh42dias** [comment]
Olá @zennsocial estamos sim 😊

**Comment by marcoswca** [comment]
@juuh42dias Acabei de enviar.

**Comment by juuh42dias** [comment]
Pessoal, agradecemos bastante todas as submissões de vocês, mas no momento encerraremos a temporada de vagas em aberto :sweat_smile: 

Mas fiquem atentos que em breve poderemos reabrir.

Até mais e obrigada pelos peixes.

**Comment by gadielkalleb** [comment]
pessoal tomem cuidado pois eles demitiram um colega nosso de forma injusta, não posso passar os detalhes mas quem quiser se candidatar fica por sua conta em risco.
