### ISSUE TITLE
[Remoto] PHP/Wordpress Developer na Mobiplus

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [backend-br/vagas#6624]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-phpwordpress-193921283?origin=github&medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A MobiPlus está buscando <strong>PHP/Wordpress Developer</strong> em nível sênior para compor sua equipe.</p>
<p><strong>Nosso caminho passa por: </strong>Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p>
<p>Investidores e grandes empreendedores dizem que uma das coisas mais importantes nas startups é o TIME. Então nós decidimos começar pelo TIME.  Nascemos para mudar o status quo de como se criam empresas de sucesso!</p>
<p><strong>O que nosso time técnico domina</strong>: Android e iOS nativo, React Native, Flutter, React.js, Vue.js, Typescript, Angular, Node.js, Golang, Java, Firebase, AWS, Testes, Testes, Testes e o principal, desenvolvimento de produtos.</p>
<p>Fora tecnologia, acreditamos em: Agilidade, MVP, User Discovery, Product Discovery, Negócios de sucesso com vida saudável, Equipes de alta performance.</p>
<p></p>
<p>👋 <strong>Como Funciona / Processo:</strong></p>
<p>Candidate-se fornecendo as informações solicitadas;</p>
<p>Complete o seu perfil na plataforma;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>Responda ao scorecard;</p>
<p>Responda ao teste de mapeamento comportamental disponível na plataforma;</p>
<p>Fique atento(a) aos convites para entrevistas de fit ou entrevista técnica.</p>

## Mobiplus: 
 <p>A Mobiplus nasce em 2017 com uma ideia bem clara: prestar serviço de alta qualidade para viabilizar a montagem de um TIME de alta performance e, em um segundo momento, gerar resultados importantes para todos os envolvidos na empreitada, com produtização de serviços e desenvolvimento de produtos (SaaS).</p><p>Nosso caminho passa por: Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p><a href='https://coodesh.com/empresas/mobiplus'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- MySQL 
- PHP 
- Wordpress 
- GIT 
- CodeIgniter 
- Wordpress Headless
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em posição similar ou background atuando como Wordpress Developer 
- Experiência com PHP junto com outras bibliotecas comuns como CodeIgniter ou Laravel 
- Bons conhecimentos de front-end base: HTML5, CSS3, SASS, JavaScript e Bootstrap 
- Conhecimentos em versionamento usando git 
- Perfil analítico, crítico e com habilidades para resolver problemas 
- Habituado em projetar, construir e manter código eficiente, reutilizável e testável 
- Habituado com metodologias ágeis, scrum e lean startup 
- Experiência com banco de dados relacionais (MySQL) 
- Conhecimentos sólidos de programação orientada a objetos e design patterns
## Diferenciais: 
 - Bons conhecimentos ou engajado em aprender React/Vue/Flutter
## Benefícios: 
 - Trabalho 100% remoto 
- Ambiente descontraído, colaborativo e extremamente desafiador 
- Horário flexível (limitações de janela de horário dependendo do contexto/cliente) 
- Possibilidade de trabalhar com um time de capacidade acima da média 
- Possibilidade de trafegar entre diferentes tecnologias e stacks 
- Contratação PJ com benefícios similares à CLT (Incluímos os benefícios no valor do salário PJ) 
- Possibilidade real de acordar todos os dias para construir algo seu de verdade 
- Stock Options (médio prazo)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [PHP/Wordpress Developer na Mobiplus](https://coodesh.com/vagas/pessoa-desenvolvedora-phpwordpress-193921283?origin=github&medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Back-End

**Comment by ZeiadSamir** [comment]
I’m a beginner front end and I’m going to build a full responsive website for an engineering consultant but i have some questions if any one can help please 

1- Is this kind of websites needs a huge database and wordpress dashboard or that point not very important?
2- And if so , should i build the data base first or after i finish the website and host it ? 
 
* note : this website contains only one form in contact us category that's all .

I will accept any advice or any steps ♥️
