### ISSUE TITLE
[Remoto ou Presencial em São Paulo] Back-end Developer @ Olga Ri

### ISSUE THREAD

**Issue by tatidirienzo** [backend-br/vagas#6643]
Salário para esta posição: entre R$ 6.000 e R$ 7.000 (CLT)

## Nossa empresa

A Olga Ri é uma startup de alimentos que opera a partir de cloud kitchens entregando saladas para clientes residenciais e corporativos. Com tecnologia de ponta, excelência na operação e uma marca com propósito, estamos trabalhando para criar a próxima geração do foodservice no Brasil.

Enquanto empresa, nos comprometemos a montar times diversos, a valorizar as comunidades em que estamos inseridos, pensar a sustentabilidade de nossas ações e estimularmos uma vida leve.

Nosso escritório fica na Vila Olímpia, em São Paulo, e hoje contamos com 140+ funcionários, 40+ entregadores terceirizados e 4 unidades. Em 2019, recebemos nosso primeiro aporte de um dos maiores fundos de venture capital da América Latina – a Kaszek Ventures e seguimos em uma fase de rápido crescimento.

## Descrição da vaga

Estamos buscando uma pessoa para integrar nosso time de tech que será responsável por contribuir com a evolução do nosso back end, incluindo a manutenção dos sistemas existentes e o desenvolvimento de outros projetos da área. Se você tem interesse em trabalhar em uma empresa de rápido crescimento e com um time em formação, queremos te conhecer!

Tecnologias utilizadas: Java, AWS, GIT e Jira

## Local

100% remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
- Ter vivência com experiência prévia de 2+ anos em desenvolvimento back end.

**Desejáveis:**
- Conhecimento de frameworks ágeis (como scrum);
- Ser uma pessoa organizada e conseguir se comunicar de forma clara;
- Gostar de trabalhar em equipe de forma leve, harmônica e integrada.

## Benefícios

- Plano de saúde
- Vale alimentação

## Contratação

CLT

## Como se candidatar

1. Preencher o formulário [neste link](https://bit.ly/3CgaK4v)
2. Enviar CV para joao.esmanhoto@olgari.com.br
3. Se possível, informe também que você veio através de uma divulgação do Github publicada pela [Remotar](http://remotar.com.br/)

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by guligon90** [comment]
FYI: O link para a Remotar está quebrado.

**Comment by tatidirienzo** [comment]
> FYI: O link para a Remotar está quebrado.

ajustado. Obrigada!
