### ISSUE TITLE
[Campinas] Back-End .Net C# na [e.Mix]

### ISSUE THREAD

**Issue by dmosantos** [backend-br/vagas#665]
Vagas Programador(a) C# em Campinas para:
- Desenvolver novas aplicações 
- Respirar inovação
- Colaborar na manutenção e constante melhoria de aplicações atuais

Necessário:
- C#
- ASP.NET
- HTML5 e JavaScript

Empresa com 21 anos de mercado.
Contratação CLT.
Apenas presencial. Empresa localizada no centro de Campinas com fácil acesso.
Ambiente descontraído com equipe TOP.

Benefícios:
- Convênio Médico Individual
- Convênio Odontologico Individual
- Vale Refeição
- Vale Alimentação
- Seguro de Vida
- Café Manha
- Frutas
- Folga Aniversário
- Happy Hour (Integração da Equipe)
- Amigo Aniversário
- Datas Comemorativas
- Uniforme
- Incentivo a treinamentos, cursos e eventos

Interessados(as) enviar currículo para: diego.marques@emix.com.br com o assunto "Vaga C#"

**Comment by luicesar** [comment]
Bom dia, qual seria o salário para a vaga ?
