### ISSUE TITLE
[Campinas] Developer C# na [Programmer's] 

### ISSUE THREAD

**Issue by mariabruna** [backend-br/vagas#666]
A PROGRAMMER’S®, empresa presente no mercado de soluções de Tecnologia da Informação 
desde 1989, construindo uma relação de confiança e credibilidade com seus clientes nos diversos 
segmentos do mercado empresarial, contrata profissionais para atuarem como: Desenvolvedor C# para um projeto internacional. 
 
**Requisistos:** 
- Desenvolvimento em C# .NET; 
- Inglês fluente para conversação; 
- ASP.NET, MVC, ASP .NET Core; 
- .NET  Framework;
-  SQL Server. 
 
**Desejável:** 
- Conhecimentos  em Ruby On Rails;
- ReactJS, AngularJS;
- WPF, WCF, Web Api. 
 
Regime CLT + Benefícios. Interessados deverão encaminhar os currículos para recrutamento@programmers.com.br

**Comment by luicesar** [comment]
A vaga está aberta ?
