### ISSUE TITLE
[São Paulo/Remoto] Back-end Developer @Definancial Investimentos

### ISSUE THREAD

**Issue by ClauMeneses** [backend-br/vagas#6665]
> Vaga Remota 

## Definancial

Quem nunca penou para decidir onde investir? Queremos resolver isso, de um jeito divertido. 
Veja em que seus amigos estão investindo, busque informações, e tomem decisões juntos. 

## Descrição da vaga

**Construindo um time de desenvolvimento**

 

Queremos que todos tragam suas histórias e que consigamos construir a nossa juntos, assim como estamos construindo a nossa empresa, compartilhando experiências.

Queremos construir uma cultura Dev de parceira e que todos sintam que estão impactando o negócio, que seu código faça diferença na nação de investidores que ajudaremos mudar suas histórias.

 

Acreditamos que com um time diverso um produto igualmente diverso e que assim atingiremos nossos objetivos.

 

Aqui, você estará junto construindo a nossa equipe, nossa arquitetura, e com certeza adotando ótimas práticas de gestão de engenharia e de pessoas, venha fazer parte desta história que está apenas começando.

 

**O que te anima**

Trabalhar em uma empresa onde seu trabalho impacta diretamente no negócio e com isto, ajude a definir  boas práticas para desenvolver o produto inovador;

Implementação de APIs bem organizadas, testadas, escaláveis e que resolvam o problema do usuário;

Desenvolver em  Go ou Node.js ou Elixir e/ou outras linguagens;

Conectar-se com a área de produto para que desenvolvam com qualidade e alinhados;

Debater e sugerir soluções e arquiteturas.

 

**O que nos anima**

Uma boa experiência no desenvolvimento de software em Node.js e mais uma das seguintes linguagens de programação: Go, Elixir, Rust, Scala ou C++. Aqui estamos para trocarmos experiências então, se não tem tanta experiência em uma das outras linguagens, mas gosta de aprender, também queremos te conhecer.

Docker, arquitetura de micro-serviços e mensageiria.

Experiência em Cloud providers como AWS, GCP ou Azure.

Desenvolvimento e manutenção de sistema de alta-disponibilidade.

Tenha a cultura de escrever testes automatizados e preze por uma boa cobertura de testes;

Boas práticas e qualidade de código.

 

**O que nos anima ainda mais**

Desenvolvimento de API e serviços de alta-disponibilidade e baixa latência mesmo com volumes gigantescos de dados

SOLID e Clean Architecture

Monitoramento de aplicações e gestão de logs

Experiência com Kubernetes e Kafka

 

**Pensando em você preparamos o seguinte pacote de Benefícios**

Stock options, você será dono do negócio também!

Ambiente inovador e de construção

Trabalho remoto definitivo com opção de trabalhar em escritório (se disponível na sua região)

Plano de saúde SulAmérica

Vale refeição/alimentação - Caju Benefícios

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Curtiu? Envie um email para people@definancial.com.br com seu CV anexado - enviar no assunto: Vaga Backend ou https://carreiras.definancial.com.br/vagas-abertas-back-end 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: claudia.meneses@definancial.com.br

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by igorcesarcode** [comment]
Tem algum desafio para poder fazer para quem quiser tentar de júnior ? @ClauMeneses

**Comment by ClauMeneses** [comment]
> Tem algum desafio para poder fazer para quem quiser tentar de júnior ? @ClauMeneses

Olá, Igor! Temos sim, inclusive temos juniors muito bons aqui. Venha com a gente.
Abs
