### ISSUE TITLE
 [São Paulo] Front-End Developer na [Verx Consulting]

### ISSUE THREAD

**Issue by Deborag12** [backend-br/vagas#67]
Conhecimentos necessários:
HTML5, JS, CSS3, VUE.js, Sass, Mocha.
VUE.js por ser um framework novo pode ser complicado encontrar no mercado, porém caso tenha experiencia em AngularJS já ajudaria nessa transição.
contrato PJ , tempo indeterminado , oportunidade para São Paulo e grande SP.

**Comment by reginaldojunior** [comment]
Olá @Deborag12 

Obrigado por anunciar a vaga aqui, mas estamos deixando esta organização apenas para vagas backend. 

As vagas de frontend pode anunciar em https://github.com/frontendbr/vagas .

Obrigado pela compreensão. 

<3

**Comment by Deborag12** [comment]
Obrigada

Débora Lima

Em 8 de fev de 2018 10:37, "Reginaldo Junior" <notifications@github.com>
escreveu:
