### ISSUE TITLE
[Remoto] Back-end Developer @ follow55

### ISSUE THREAD

**Issue by felipemarcos** [backend-br/vagas#6708]
## Nossa empresa

Uma boutique de tecnologia, especialista na criação e desenvolvimento de projetos digitais. Somos independentes e estamos em uma incansável busca por inovação. Estamos em constante crescimento e buscamos 3 back-end developers para integrar no nosso time.

Procuramos pessoas comprometidas, autodidatas e, principalmente, que curtam qualidade de vida no trabalho.

## Local

Remoto. Nosso escritório fica em São Paulo, mas você pode trabalhar de qualquer do país.

## Requisitos

**Obrigatórios:**
- PHP
- Laravel
- MySQL
- Git
- Proatividade
- Raciocínio lógico e analítico
- Inglês técnico
- Gostar de inovação, estar por dentro de tendências
- Disposto a trabalhar com pessoas de perfis diferentes.

**Desejáveis:**
- Conhecimento em AWS;
- Domínio na implementação de APIs Rest;
- WordPress
- HTML / CSS
- JavaScript

## Benefícios

- Bônus $$$ por projeto

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para felipe@follow55.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Backend

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by romulo2735** [comment]
Full Time?
