### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Node.js

### ISSUE THREAD

**Issue by LucGranato** [backend-br/vagas#671]
Esta vaga é presencial para Curitiba-PR.
Faça parte de uma equipe que está em constante evolução, sempre buscando novas tecnologias para melhorar nosso produto e entregar valor para o nosso cliente.

**Comment by danielmanfred** [comment]
Como faço para me candidatar?

**Comment by LucGranato** [comment]
@danielmanfred achou um bug! hehehe

Segue o link: https://www.facebook.com/job_opening/749792982023905
Caso prefiram encaminhar por e-mail: contratacao@engaged.com.br

Abraço!
