### ISSUE TITLE
[Remoto] Fullstack na MasterOp

### ISSUE THREAD

**Issue by masteropsys** [backend-br/vagas#672]
# MasterOp - Contrata
A MasterOp é uma operadora de turismo que busca desenvolver soluções inovadoras para o seu mercado, parceiros e clientes.

Adoramos pessoas que buscam um conhecimento abrangente (full stack) e desafios.

### O que usamos?
- Python, Django, DRF << Foco da Vaga >>
- React << Foco da Vaga >>
- AWS (EC2, Cloudfront, S3, RDS, Elasticache, etc)
- Git
- Docker

### Onde ficamos?
Nossa equipe fica distrubída entre o Brasil e os Estados Unidos.

### Onde trabalharei?
Se você estiver alocado em Maceió, o nosso escritório será o local ideal para que você absorva knowhow deste mercado mas rápido.
Caso esteja em outro estado ou país, a vaga é aberta para trabalho remoto.

### O que buscamos?
Pessoas com disposição (!), curiosidade e certa bagagem (pleno ou senior). Sem apego à um tecnologia ou linguagem e que buscam um conhecimento amplo sobre a tecnologia e suas práticas (arquiteturas, patterns, testabilidade, algoritmos, DB, etc).

### Modelo de contratação
A princípio PJ, mas podemos conversar!

### Remuneração
A combinar, mas gostaríamos de ouvir sua pretensão salarial.

### Contato
Mande seu e-mail com CV para: masteropsistemas@masterop.com.br

### Labels
- Remoto
- Semipresencial
- PJ
- Fullstack
- Python
- AWS
- React
- Javascript
- Pleno
- Senior

**Comment by masteropsys** [comment]
A vaga continua disponível.

**Comment by vandemberg** [comment]
:dancer:
