### ISSUE TITLE
[Belo Horizonte/MG] PHP Developer na Solusoft

### ISSUE THREAD

**Issue by tucanowned** [backend-br/vagas#677]
## Descrição da vaga

Procuramos Profissionais Experientes, com conhecimentos em desenvolvimento em PHP, utilizando framework Codeigniter e dispostos a enfrentar desafios.

## Local

Escritório, Bairro Ouro Preto, Belo Horizonte/MG

## Formação e Experiência

Não é necessário curso superior.
Boa leitura em inglês.
Experiência mínima de 4 anos atuando como desenvolvedor.

## Habilidades

Muito PHP e JS
Conhecimento em Git
Codeigniter
Bom raciocínio lógico.
Inteligência emocional e disposição para resolver problemas.
Os requisitos mudam, os códigos também, esteja disposto a mudanças.

## Atribuições:
Planejar e discutir soluções de implementação com a equipe.
Estudar e aprender bastante sobre novas tecnologias

## Como se candidatar

Por favor envie um email para edson@elw.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Contratação:

- CLT

### Experiência: 

- Pleno
- Sênior
- Alocado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
