### ISSUE TITLE
[PORTO ALEGRE/RS] Desenvolvedor(a) PHP na WK Recursos Humanos

### ISSUE THREAD

**Issue by andremenezeswk** [backend-br/vagas#678]
## Local

Presencial em Porto Alegre/RS

## Requisitos

- HTML, CSS, Javascript, jQuery
- PHP / Laravel
- MySQL
- GIT
- Graduação completa ou cursando na área
- Experiência para atuar com autonomia

## Contratação

CLT

## Nossa empresa

Empresa de marketing digital.

## Como se candidatar

Por favor envie um email para daiani.souza@wkrh.com.br com seu CV anexado.
Ou pelo link https://www.wkrh.com.br/job/desenvolvedor-php-a0f1i000004vpi1uao/

## Labels

- Alocado
- CLT
- PHP
- HTML
- CSS
- Laravel
- Javascript
- jQuery
- MySQL
- GIT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
