### ISSUE TITLE
[São Paulo] Back-End Developer Java - Pl & SR  na [ Verx Cosulting]

### ISSUE THREAD

**Issue by Deborag12** [backend-br/vagas#68]
Conhecimentos Técnicos Específicos (certificações, habilitações, cursos, etc.) 
 Experiência em desenvolvimento API Restful (JAVA) 
 Experiência em desenvolvimento JAVA, utilizando Spring Security 
 Conhecimento e aplicação da framework Spring (spring mvc, spring webview e spring data). 
 Vivência em ambientes com gestão ágil empregando SCRUM / Lean 
 Vivência em ambientes de desenvolvimento ágil com “Continuos Integration / Continuos Deploy” 
 Excelentes skills de comunicação interpessoal, comunicação verbal e escrita
Contratações: pj - tempo indeterminado -  currículo: debora.lima@verx.com.br

**Comment by Deborag12** [comment]
Formação/ Experiência (tempo e indústria) 
- Formação em Sistemas de TI, Engenharia de Computação, ou Áreas Correlatas 
- Experiência em desenvolvimento Java 
- Certificação Java será valorizada

**Comment by reginaldojunior** [comment]
Vaga preenchida?
