### ISSUE TITLE
[Arujá/SP] Ruby Developer na RH Software

### ISSUE THREAD

**Issue by marcosgugs** [backend-br/vagas#680]
## Sobre a RH Software

Há 20 anos no mercado, com excelência em programas para gerenciamento de consultórios e clínicas, a RH Software possui hoje milhares de clientes no Brasil e no exterior.  
Trabalhamos para oferecer produtos excelentes com pós-venda excepcional.  

Saiba mais sobre a empresa no site http://www.rhsoftware.com.br

## Sobre a Vaga

Buscamos um profissional que seja comprometido com a qualidade do seu trabalho. Que saiba trabalhar em equipe e esteja sempre interessado em aprender mais.
O desenvolvedor fará parte da equipe de desenvolvimento do [Dental Office](http://www.dentaloffice.com.br), melhor software de gestão de clínicas odontológicas do Brasil, de acordo com o Cloudia. ([Os 3 melhores softwares odontológicos para a gestão de clínicas e agendamentos](https://www.cloudia.com.br/melhores-softwares-odontologicos/))

## Esperamos que você domine:
- Ruby
- Rails
- MySQL
- Git
- HTML5, CSS3

## Sería incrível se você conhecesse:
- AngularJS
- VueJS
- ElasticSearch

## Nível Mestre Jedi:
- Linux / AWS
- Docker / Kubernetes
- DevOps
- NodeJS
- Elixir

## O que oferecemos:

- Salário competitivo
- Ambiente descontraído
- Passaporte para eventos
- Alimentação
- Transporte
- Convênio Médico
- Participação nos lucros

Caso este seja o seu perfil, venha bater um papo com a gente aqui na RH Software. Estamos localizados em Arujá/SP, próximo a Guarulhos, Suzano, Mogi das Cruzes, etc. 
Envie seu currículo ou LinkedIn para o e-mail careers@rhsoftware.com.br para agendar a visita.

## Labels
- Alocado
- CLT
- Pleno
- Senior
- Junior

**Comment by TheanRogerio** [comment]
Enviei meu currículo para o e-mail informado, porém recebi a mensagem abaixo:

We're writing to let you know that the group you tried to contact (carrers) may not exist, or you may not have permission to post messages to the group.

**Comment by marcosgugs** [comment]
@TheanRogerio ola amigo, eu digitei errado. Ja corrigi o email. Tenta novamente com o email correro. Obrigado e me desculpe

**Comment by TheanRogerio** [comment]
Sem problema.
Pra mim continua aparecendo o email careers@rhsoftware.com.br. Qual o correto?

**Comment by marcosgugs** [comment]
@TheanRogerio é esse mesmo. careers@rhsoftware.com.br ou qualquer coisa envia tambem pra marcos.junior@rhsoftware.com.br que eu encaminho.

**Comment by TheanRogerio** [comment]
@marcosgugs enviei para os dois emails. Obrigado.

**Comment by jonataszanol** [comment]
Olá, esta vaga é somente presencial ou pode ser para trabalho remoto?

Em qui, 13 de dez de 2018 às 07:53, Thean Rogerio <notifications@github.com>
escreveu:

**Comment by marcosgugs** [comment]
@jonataszanol presencial apenas, infelizmente! Mas envie o currículo mesmo assim, pode ser que eles aceitem caso gostem!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
