### ISSUE TITLE
[Porto Alegre - Remoto] Back-end Developer @ NOFARO

### ISSUE THREAD

**Issue by luiza19000** [backend-br/vagas#6809]
## Nossa empresa
Sobre nós: a Nofaro

Inovadores, transparentes, simples, resilientes.

Somos um plano de saúde Pet para cachorros e gatos com contratação e acompanhamento online, a primeira plataforma digital no Brasil.  Oferecemos todo o carinho e proteção que o seu melhor amigo merece sem burocracia e surpresas na conta no final do mês.

## Descrição da vaga

**Propósito do cargo:** Desenvolvimento de sistemas em Laravel.

**Atividades do cargo:** 
- Desenvolver novas funcionalidades nas aplicações da empresa;
- Atuar no desenvolvimento de sistemas e tomada de decisão;
- Trabalhar na manutenção e sustentação do site e em integrações de APIs. (integração com sistemas externos, por exemplo integrações com o RD);
- Correção de BUGs (erros do sistemas) e otimização dos sistemas. 

## Local

Remoto ou em POA (Porto Alegre - Rio Grande do Sul)

## Requisitos

**Obrigatórios:**
- 2 anos + PHP
- 1 ano + Laravel

**Desejáveis:**
- MySQL, AWS, Vue.js

## **Benefícios**
- Plano de Carreira
- Plano de saúde PET

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@nofaro.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by YaakovDantas** [comment]
Vaga ainda aberta?
