### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor(a) PHP Sênior na WK Recursos Humanos

### ISSUE THREAD

**Issue by andremenezeswk** [backend-br/vagas#681]
## Descrição da vaga

Empresa de Supply Chain e Logística localizada em Porto Alegre.

## Local

Presencial

## Requisitos

**Obrigatórios:**
- Forte experiência PHP
- Desenvolvimento orientado a objetos
- Javascript
- SQL
- Modelagem relacional de banco de dados
- Análise de requisitos / Arquitetura de informação

**Diferenciais:**
- Oracle / PLSQL
- Logística e supply chain
- Java para web e desktop
- Sistemas ERP

## Contratação

CLT

## Como se candidatar

Por favor envie um email para marianna.braga@wkrh.com.br com seu CV anexado e o nome da vaga no assunto.
Ou através do link https://www.wkrh.com.br/job/analista-desenvolvedor-php-a0f1i000004vk6quaw/

## Labels

- Alocado
- CLT
- Sênior
- PHP
- Javascript
- SQL
- Banco de dados

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
