### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Full Stack na OPINION BOX

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#683]
### Sobre a empresa: OPINION BOX PESQUISAS SA

O Opinion Box é uma empresa que está revolucionando a pesquisa de mercado e opinião no país. 
 Somos uma startup que inova a cada momento. Somos ágeis, antenados, gostamos de trabalhar e nos sentimos felizes em mudar a vida de pessoas e empresas de diferentes segmentos e portes.

### Descrição: Ocupações do cargo

Estamos em busca de um Analista Desenvolvedor Pleno para contribuir com a democratização da pesquisa de mercado.Além de responsável por realizar a manutenção e o suporte nas plataformas do Opinion Box, você também participará na definição de novas soluções e será responsável em auxiliar o setor de operação nas configurações e lançamentos de pesquisas.

### Benefícios

Vale-refeição;
Vale-transporte;
Plano de saúde (50%);
Plano odontológico (50%);
Day off no seu aniversário;
1 emenda feriado a cada 6 meses de empresa;
Casual dress;
Licença paternidade de 14 dias;

### Aptidões e qualidades

Possuir excelente conhecimento técnico em JavaScript;
Conhecer a fundo Protocolo HTTP, DOM e HTML;
Experiência em framework javascript: React Js;
Experiência em Node.js e PHP;
Familiaridade com ambiente Linux (desenvolvimento e deploy);
Estar atualizado com as principais arquiteturas e boas práticas para desenvolvimento Web e Backend;
Preocupar com a abstração de código, quebrando grandes módulos em componentes reutilizáveis, prezar por código limpo e bem estruturado.
Possuir conhecimento na implantação de testes em Javascript: Testes unitários e testes de integração;

### Diferenciais

Experiência com modelo de micro serviços;
Experiência com Docker;

### Labels:

Alocado
Pleno

### Candidatar: http://bit.ly/opinionbox_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
