### ISSUE TITLE
[Rio de Janeiro - RJ] Back-End Developer na TVManager

### ISSUE THREAD

**Issue by danielcozer** [backend-br/vagas#685]
## Descrição da vaga

Somos uma Startup especializada em inovações em mídia, desenhadas para atender o mercado televisivo e produtores de conteúdo audiovisual. Não importa sua formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma extremamente inovadora para o mercado ! Conheça nossa plataforma: http://tvmanager.io/ 

Perfil desejado: Alocado - Estagiário / Junior e Pleno

## Local

Rio de Janeiro, Centro da cidade

## Requisitos

**Obrigatórios:**

• Fluência em Javascript 
• Desenvolvimento de sistemas: Node js. 
• Experiência com Mongo DB e Express
• Experiência de controle de versão de código-fonte (Git); 
• Familiaridade com o git-flow.
• Acompanhar coordenar testes e homologações de sistemas. 
• Ajudar a construir o software ao invés de apenas codar requisitos! participar ativamente da concepção e construção da TVManager

**Desejáveis e Diferenciais:**

• Experiência com Sistemas Web / SaaS
•  Familiaridade com Docker; 
• Experiência com testes Automatizados e integração contínua; 

## Contratação

A combinar

## Nossa empresa

• Maiores informações em: http://tvmanager.io/
• Vídeo explicativo da Solução: https://player.vimeo.com/video/250085951

## Como se candidatar

Por favor envie um email para **daniel@tvestore.com** com o seguinte título e informações:

• Assunto [VAGA] Desenvolvedor Back-end 
• Currículo ou Linkedin
• Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)

## Labels

- Alocado
- Júnior
- Pleno
- Node JS
- JavaScript

**Comment by raphaelanjos1** [comment]
Enviado! 😄

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
