### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedores Full Stack na MONSAT

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#686]
### Sobre a empresa: Monsat

A Monsat é uma empresa moderna e inovadora que atua no mercado de segurança, rastreamento e tecnologia com o principal objetivo de transformar sonhos em realidade.

### Descrição: Ocupações do cargo

O profissional desenvolverá um software para a Monsat e terá como responsabilidade a criação de toda codificação necessária, bem como também a criação do layout no front-end e toda retaguarda no back-end com banco de dados, além de integrações com outros sistemas e softwares através de "API" fornecida por fornecedores, parceiros e/ou até outros sistemas da própria Monsat. O desenvolvedor também terá que homologar hardwares com protocolos em Hexadecimal e/ou ASCII em estruturas UDP e/ou TCP fornecidas pelo próprio fabricante do hardware para que se comuniquem com o software que será desenvolvido.

### É obrigatório ter habilidade de desenvolver nas seguintes linguagens:

React Native;
Node JS;
Redux.

**Será como diferencial as seguintes tecnologias:**

MongoDb;
Aplicativo Android e IOS (individual).

### Benefícios

O profissional será contratado pelo regime CLT, com isso terá os seguintes benefícios:

Vale-transporte;
Vale-refeição.

### Aptidões e qualidades

Acreditamos que a vaga disponibilizada deve ser ocupada por quem deseja realmente construir um sonho conosco, e para isso, é essencial que o profissional esteja a procura de ideais e não apenas de um emprego. Por tanto, o mesmo deve ter compromisso, comprometimento, entender plenamente suas habilidade e limitações para que entendamos também qual será a velocidade do desenvolvimento, sinceridade, honestidade, lealdade, criatividade, habilidade de ajudar o próximo, participação em equipe pelo fato de envolver outros setores e principalmente entender que o Software é de propriedade da empresa e não uma idealização pessoal.

### Informações complementares

O desenvolvedor Full Stack deve ter habilidades para criação e aplicação do software da empresa em plataformas mobile como IOS, Android e Windos de forma "nativa" e/ou universal, desde que, não apresente erros. 

Tipo de contrato:
Emprego
Nível de experiência:
Pleno 
Formação:
Graduação completa Graduação incompleta 

### Labels:

CLT
Alocado
Pleno e Júnior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
