### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Back End [Zé Delivery]

### ISSUE THREAD

**Issue by CesarNobre** [backend-br/vagas#687]
### **Sobre o Zé**

Nosso produto Zé Delivery tem a missão de entregar bebida rápida, barata e gelada. Hoje trabalhamos com times multidisciplinares com diferentes skills e com OKR’s bem definidos. Buscamos sempre prover autonomia para que os nossos times possam experimentar, aprender e encontrar as melhores soluções para os nossos clientes.

Pessoas são os ativos maios valiosos da nossa empresa, o seu desenvolvimento profissional é levado a sério e para isso temos processos e incentivos financeiros para que você consiga atingir os seus objetivos.

O Zé delivery é um produto da Zx Ventures que é um grupo global de inovação e growth da AB InBev, líder mundial do mercado cervejeiro e uma das 5 maiores companhias de bens de consumo do mundo. Fundada em 2015, nosso objetivo é desenvolver novos produtos e negócios que atendam às necessidades emergentes do consumidor. Temos várias unidades de negócios globais que atuam em áreas que possuem relação com nosso principal negócio, a cerveja: artesanais, internacionais e especiais, eCommerce, homebrewing, experiência da marca, e exploration.

### **Como trabalhamos**

Somos preocupados com a qualidade do nosso produto, sempre buscamos as melhores práticas e metodologias para entregar novas features para nossos clientes. Temos uma stack moderna, hoje trabalhamos com Python, AWS (Serverless, RDS, SNS), Graphql, React, Apollo, e React Native. Caso ainda não conheça essas tecnologias não se preocupe, grande parte do nosso time não conhecia essa stack e aprendeu conosco. :slightly_smiling_face:

Não acreditamos em bala de prata e nem seguimos rigorosamente as metodologias ágeis, sempre tentamos balancear com a nossa realidade.

### **BENEFíCIOS**

* Bônus de 4.2 a 5.6 salários.
* 14 salário.
* Plano de saúde, VR e VT.
* Gympass.
* Incentivo financeiro para cursos e eventos.
* Happy hour com cerveja artesanal feita especialmente para o evento.

### Clique [aqui](https://zxventures.gupy.io/candidates/jobs/19837/apply) para se inscrever na vaga.

**Comment by SamuelAraujoSilva** [comment]
remoto?

**Comment by CesarNobre** [comment]
Presencial, estamos na vila olímpia. Mas nada impede de fazer home-office as vezes. :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
