### ISSUE TITLE
[São Paulo/Campinas] Desenvolvedor(a) Sênior Ruby on Rails (Elixir Desejável) na ReclameAqui/Trustvox

### ISSUE THREAD

**Issue by cleytonmessias** [backend-br/vagas#688]
## Sobre a empresa: RA Trustvox

A [Trustvox](https://site.trustvox.com.br/) vem promovendo sinceridade há 5 anos no mercado. Esse mês, a Trustvox foi adquirida pela Reclame Aqui e estamos aumentando nossa equipe.

O [Reclame Aqui](https://www.reclameaqui.com.br/) é o milésimo site mais acessado do mundo e a Trustvox está presente em boa parte do comércio eletrônico no Brasil. Desafios técnicos não vão faltar ;)

## Requisitos:

**Conhecimentos técnicos necessários:**

- git
- TDD/BDD (de preferência com ruby)
- ruby
- rails (4, 5)
- javascript, html, css
- mysql/mariadb
- docker

**Desejável:**

- ember.js
- vue.js
- elixir/phoenix
- kubernetes
- elasticsearch, logstash, kibana (ELK stack)

**plus:**

- testes com javascript
- desenvolvimento orientado a micro services (na prática)
- sass

## Contratação:

- PJ porém com plano de saúde :)

## Como se candidatar:

Se [inscreva nesse link](https://trustvox.typeform.com/to/dOMLAf).

(A vaga é para trabalhar presencialmente em São Paulo ou Campinas, porém, caso esteja em outra cidade, aplique pois também temos uma equipe remota).

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
