### ISSUE TITLE
[Fortaleza] Desenvolvedor Python/Django

### ISSUE THREAD

**Issue by tiagocborg** [backend-br/vagas#689]
Vaga para desenvolvedor Python/Django em Fortaleza:

-Experiência 3+ anos em desenvolvimento Django 
-Experiência com Django Rest Framework
-Vivencia em backends para servir dispositivos móveis
-Capacidade de se comunicar verbalmente em inglês é essencial.

Salário e benefícios a combinar.
Regime CLT, presencial

Enviar currículo para: career@oowlish.com

Mais sobre a empresa:
http://www.oowlish.com
https://lnkd.in/eaNJX22

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
