### ISSUE TITLE
[São Paulo] Back-End Developer Pleno na WEBD7

### ISSUE THREAD

**Issue by sistemaweb** [backend-br/vagas#690]
## Descrição da vaga

Trabalhamos no desenvolvimento de um ERP (e mais alguns projetos) para uma empresa privada

## Local

4 dias (por semana) Remoto e 1 dia (por semana) no Escritório, São Paulo - República

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP / Laravel
- 2 anos de experiência com JavaScript
- experiência com posPostgress

**Desejáveis:**
- conhecimentos em React
- conhecimentos em C#

**Diferenciais:**
- projetos opensource

## Contratação

R$ 3200,00 - PJ / MEI

## Nossa empresa

A Web D7 desenvolve sistemas, sites e lojas virtuais

## Como se candidatar

Por favor envie um email para contato@webd7.com com seu CV anexado - enviar no assunto: Vaga Dev Pleno

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
