### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na STUDIO VISUAL

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#691]
### Sobre a empresa: Studio Visual

Somos uma agência com foco em soluções digitais para empresas de pequeno, médio e grande porte. Estamos no mercado há mais de 15 anos, somando grande experiência em tecnologia e inovação, sempre com foco no usuário final.

### Descrição: Ocupações do cargo

Desenvolvimento de aplicações WEB, utilizando as melhores práticas do mercado, com foco na qualidade da entrega.

### Requisitos

PHP;
JavaScript;
HTML;
CSS;
Bootstrap;
jQuery.
Conhecimento em WordPress, Laravel e Angular é considerado um diferencial para esta vaga.

### Aptidões e qualidades

Buscamos profissionais que tenham sangue nos olhos para fazer as coisas acontecerem.

### Benefícios

15 dias Férias/ano remuneradas

### Informações complementares

Estamos localizados na Zona Leste de São Paulo, bem próximos ao metrô carrão.

### Labels

CLT
Alocado
Pleno

### Candidatar: http://bit.ly/studiovisual_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
