### ISSUE TITLE
[Porto Alegre, RS] Python/Django/API [SENIOR] | Cíngulo

### ISSUE THREAD

**Issue by micheltlutz** [backend-br/vagas#694]
# Python/Django/API Python no Cíngulo

*Se ainda não conhece o Cíngulo, [confere aqui](https://github.com/cingulo/vagas/blob/master/README.md)*.

Estamos procurando uma pessoa desenvolvedora Python Sênior para trabalhar com as seguintes tecnologias:

- Python 3
- Django 2+
- Django Rest Framework
- JWT
- Git / GitHub / GitFlow
- TravisCI
- AWS

O que podemos adiantar é que o ambiente é acolhedor, o time é divertido e estamos criando algo f * * *. Nesse documento tem uma seção ["No que estamos trabalhando"](https://github.com/cingulo/vagas/blob/master/README.md).

Detalhes sobre a vaga:

- CLT até 8.000 a depender do nível do candidato.
- VR
- Nossa semana tem 40h de segunda a sexta, sem turno no sábado. Mas não é só tranquilidade, somos responsáveis e entregamos o combinado.
- Presencial na Marques do Pombal em Porto Alegre.

Nesse momento estamos procurando alguém senior para assumir a API do Cíngulo, então se você começou a pouco com Python ou Django ou sabe muito pouco sobre as tecnologias descritas acima, por favor não envie currículo agora. Aguarde termos uma vaga que se encaixe no seu perfil.

# Se interessou?

Manda o currículo pra ricardo@cingulo.com e vem com a gente! Essa história vai ser épica e está recém começando.

**Comment by rserro** [comment]
Mais detalhes em https://github.com/cingulo/vagas

**Comment by BrunoMoreno** [comment]
Remoto é possível?

**Comment by micheltlutz** [comment]
@BrunoMoreno Infelizmente não.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
