### ISSUE TITLE
[Curitiba, PT] DevOps Analyst

### ISSUE THREAD

**Issue by debonaleonardo** [backend-br/vagas#697]
Sobre a empresa: Leads2b
Somos uma startup tecnológica com foco em soluções para o setor comercial das empresas, estamos em crescimento acelerado e procurando talentos para compor o nosso time.

Descrição: Ocupações do cargo
Principais atividades:
* Monitorar as nossas aplicações web, identificar problemas e estruturar planos de ação;
* Desenvolver e dar manutenção em scripts de automatização de infraestrutura utilizando Python/Shell/etc.;
* Pesquisa & Desenvolvimento de novas tecnologias de operação web;
* Ajudar a manter nossa cultura devops;
* Ajudar a manter nosso ambiente (Amazon Web Services, Docker, Rancher, Google BigQuery).

O que é indispensável para a vaga?
* Experiência com Linux, Redes, VPN, firewall, etc.;
* Gostar muito de programar;
* Experiência com Stack web (VueJS, PHP, Node.js);
* Vivência com bancos de dados (MySQL e MongoDB);
* Jenkins;
* Git (Bitbucket);
* Ter trabalhado com infra-estrutura para a Web (programador/operações/infra-estrutura/sysadmin/network admin/etc). 
Desejável:
* Security mindset, automatização de infraestrutura (Terraform, etc), experiência com GCP;
* Langs: PHP, Python, iOS, Android;
* DB: MySQL, MongoDB, BigQuery;
* AWS: OpsWorks, RDS, EC2, Route53, VPC, S3, CloudFront, CloudWatch, SQS, IAM, etc.
* GCP: Kubernetes, Rancher, Docker
* Monitoramento: NewRelic, CloudWatch.
* Segurança: hardening, IDS/IPS, FIM, WAF, etc.

Informações complementares
Estamos localizados no bairro Bigorrilho em Curitiba-PR

Salário
CLT OU PJ a combinar

Interessados devem enviar o CV para o email vagas@leads2b.com com o assunto: Vaga DevOps

Labels
CLT
PJ
ALOCADO
DevOps

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
