### ISSUE TITLE
[Porto Alegre, RS] Backend Developer na Superplayer

### ISSUE THREAD

**Issue by robsondealmeida** [backend-br/vagas#7]
O [Superplayer](https://www.superplayer.fm/) é um serviço de streaming de música com a missão de tornar cada momento da vida das pessoas mais especial através da trilha sonora perfeita. Hoje temos mais de 1,5 milhões de usuários e 4 milhões de downloads em nossos aplicativos para as plataformas iOS e Android. Fomos acelerados globalmente pelo Google e fazemos parte da Movile, a maior empresa de serviços móveis da América Latina (iFood, PlayKids, Apontador, entre outros).
<br/><br/>

## Descrição da vaga

Buscamos um Backend Developer capaz de arquitetar e desenvolver soluções simples e dinâmicas que sirvam como base para o desenvolvimento do Superplayer em diferentes plataformas. Alguém que seja apaixonado por aprender e codificar (em .NET, Node.js, Python, etc) e que goste de pensar no produto além das linhas de código.

Ela/ele será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades nos diversos serviços (micro-serviços), na API e em outros componentes e aplicações que compõem o Backend do Superplayer. Vai trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. :)
<br/>

## Responsabilidades

- Pensar, contribuir no planejamento e desenvolver novas funcionalidades para as aplicações e serviços que compõem o Backend do Superplayer.
- Utilizar as melhores práticas e tecnologias para escrever código em JavaScript (Node.js) ou C# (.NET).
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos em nossos produtos e cuidar para que eles nunca cheguem em ambiente de produção.
- Ajudar seus colegas nerds a resolver problemas complexos.
- Definir, junto com todo o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.
<br/>

## Requisitos

- Paixão em escrever código, principalmente para as plataformas .NET e Node.js.
- Graduado(a) ou graduando(a) em alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 não é 2.
- Vivência com desenvolvimento de aplicações web e/ou RESTful APIs.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- ♡ Git.
- Habilidade de desenvolver aplicações do seu início ao fim (desde New File/Project até deployment em prod).
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Se sentir confortável com arquiteturas de desenvolvimento/project, tais como, MVC, MVVM, MVQC (MV Qualquer Coisa).
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.
<br/>

## Bônus

- Vivência com mais de uma linguagem de programação (de preferência em diferentes plataformas).
- Gostar de resolver as coisas direto no Terminal.
- Conhecer ou ter vivência profissional com serviços de Cloud Computing como AWS, Google Cloud Platform ou Windows Azure.
- Experiência em escrever testes unitários, de integração e funcionais.
- Não ter medo de "sujar as mãos" escrevendo um script em `shell`.
- Saber o que é Lean Startup e porque isso é importante mesmo sendo um desenvolvedor.
- Paixão por aprender e empreender.
- Tocar algum instrumento ou ser um rouxinol.
<br/>

## Contratação

CLT, Presencial
<br/>

## Benefícios

Plano de saúde, VA/VR e FIFA, [Tower Fall](http://www.towerfall-game.com/) e [Overcooked](https://www.playstation.com/en-us/games/overcooked-ps4/)
<br/>

## Local

Porto Alegre, RS
<br/>

## Como se candidatar

Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para **jointheband@superplayer.fm** com o assunto **Backend Developer**.

**Comment by reginaldojunior** [comment]
@robsondealmeida a vaga já foi preenchida?

**Comment by robsondealmeida** [comment]
@reginaldojunior Esta foi. Mas temos uma segunda igualzinha aberta 😄 
Manda teu LinkedIn/CV para o e-mail jointheband@superplayer.fm com o assunto Backend Developer

**Comment by reginaldojunior** [comment]
Ainda tem vaga, mantenho a issue ou posso fechar?
