### ISSUE TITLE
São Paulo - Engenheiro de Software Sênior - Locaweb

### ISSUE THREAD

**Issue by kalourenco** [backend-br/vagas#70]
Na Locaweb, desenvolver vai muito além da tecnologia. Nosso propósito é ajudar empreendedores do Brasil inteiro a prosperarem. Somos movidos pela paixão! Viramos referência quando o assunto é internet, porque somos motivados pelo que fazemos: desenvolver.

Aqui você trabalha com outras pessoas que amam tecnologia tanto quanto você. Nosso sucesso vem da atração, desenvolvimento e reconhecimento de pessoas com essa paixão. Cada Locaweber contribui para tornar nosso negócio referência no mercado. Valorizamos nossa equipe e investimos muito para criar um ótimo ambiente de trabalho.

## // Desafios

Somos a casa da internet no Brasil: temos um dos maiores data centers da América Latina. Nossos serviços atendem milhões de usuários e nosso time de tecnologia trabalha muito para manter tudo isso funcionando. Aqui você vai:

- Ter a oportunidade de trabalhar com diversas linguagens (Ruby, Elixir, Go, Java, …) e poder escolher a melhor solução, de ponta a ponta, para os desafios que temos hoje.
- Trabalhar em sistemas compostos por diversos serviços e tecnologias
- Colaborar com UX, PO, Marketing e Sys-admins, desenvolvendo um fluxo de trabalho ágil e inovador para entregarmos cada vez mais valor ao nosso cliente.
- Aprender constantemente. Ensinar e ajudar os outros com estes novos conhecimentos.
- Contribuir para a comunidade open-source.

## // Must have

- Comprometimento com a qualidade e resultados.
- Prazer em trabalhar de forma colaborativa. (Já falei que nos ajudamos muito?)
- Experiência com Ruby, Rails, TDD, BDD e programação orientada a objetos.
- Olhar de cliente.
- Experiência com bancos relacionais

## // Será um plus

- Ter trabalhado com sistemas de larga escala.
- Experiência com CI/CD.
- Já ter utilizado Docker para desenvolvimento.

## // Benefícios

- Liberdade para decidir qual a melhor solução.
- Apoiamos suas talks.
- Horário de trabalho flexível.
- Flexibilidade para trabalhar de casa quando necessário.
- Participação nos lucros e resultados.
- Temos sala de relax, academia, restaurante e lanchonete.
- Um ótimo plano de saúde.

**Contratação** CLT
**Localização** Rua Itapaiuna, 2434 São Paulo SP (Zona Sul, Vila Andrade)

## // Contato

Enviar CV e/ou Linkedin para kassya.christina@locaweb.com.br

**Comment by reginaldojunior** [comment]
Vaga preenchida?
