### ISSUE TITLE
[Belo Horizonte/MG] Analista BI

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#700]
### Sobre a empresa: A3 Data

A3Data é uma nova empresa com foco em fornecer serviços de inteligência de negócios para nossos clientes. Além disso, já estamos desenvolvendo aplicações especiais com foco em segmentos diversos. Nossos profissionais são renomados no mercado brasileiro e com vasta experiência em projetos analíticos. 

Toda esta experiência nos proporciona uma visão holística das necessidades que devemos encapsular para levar até nossos parceiros um produto que apoia na descoberta do que nossos dados têm para nos dizer.

### Descrição: Quais são os requisitos básicos?

Conhecimento na ferramenta Power BI;
Experiência com ETL;
Experiência com SQL;
Experiência com criação de Dashboards;
Experiência em modelagem de banco de dados (relacional e dimensional);
Ensino superior completo em Tecnologia ou áreas afins;

### O que brilharia os nossos olhos?

Habilidades de programação em R e Python;
Conhecimento em Machine Learning;
Conhecimento em arquitetura Big Data;
Conhecimento em arquitetura de Data Lakes;

### Você gostará de trabalhar aqui se

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho e se comunica bem com pessoas do negócio;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
É apaixonado por dados e por empreendedorismo;
Tem autonomia para tomar decisões e é criativo para propor soluções;

### Beneficios

Vale Alimentação ou Refeição (21,35/dia);
Plano de Saúde Amil 100% em apartamento sem coparticipação (atendimento no Mater Dei);
Auxílio Odontológico;
Seguro de vida;
Vale Transporte;
Escritório próximo ao metrô :)
Horários flexíveis e atuação em home office;

### Um pouco mais sobre nós

Somos uma empresa de Big Data Analytics com atuação dinâmica e horizontal, consideramos que cada colaborador é responsável por entregas de qualidade e que deve ter autonomia e liberdade para trabalhar e propor novas ideias.

Valorizamos muito a proximidade com a academia e a busca por conhecimento. Temos um time enxuto e altamente qualificado! Participamos de projetos de diversas áreas para grandes empresas.

Adoramos a diversidade e valorizamos os nossos profissionais dando espaço para que eles cresçam conosco.

Temos um ambiente dinâmico e colaborativo.

### Labels

CLT
Pleno
Alocado

### Candidatar: http://bit.ly/a3_github

**Comment by vmesel** [comment]
@megandavulpi porque tu não posta essa vaga lá no PyJobs?

**Comment by megandavulpi** [comment]
> @megandavulpi porque tu não posta essa vaga lá no PyJobs?

Obrigado pela dica, @vmesel ! Vou postar lá também =)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
