### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor PHP Full Stack

### ISSUE THREAD

**Issue by jheliodoro** [backend-br/vagas#701]
**Sobre a empresa: Grupo Unicad**
De 2004 em diante começamos a navegar nos mares da tecnologia, trazendo Informações em tempo real via Webapp, alertas via SMS e um Aplicativo para informar situações críticas na cidade. Temos um time de programadores em expansão, com trabalhos por projeto e contínuos, dando manutenção e implementando novas funcionalidades nos sistemas já existentes e também criando novas aplicações para as informações que nossa equipe de monitoramento insere no sistema.

**Descrição da Vaga**
Colabore com projetos inovadores e desafiadores na área de segurança. Analisar, desenvolver, manter, corrigir e evoluir nossos sistemas e crescer com a gente. Sempre visando atender as necessidades dos usuários.

Você precisa ter experiência com desenvolvimento em Laravel nas últimas versões, domínio de orientação a objetos, conhecimentos de padrões de projeto, conhecimentos no desenvolvimento front-end (HTML + CSS + JavaScript). Diferenciais: API GoogleMaps, Docker, Integração contínua (CI) e SCRUM

**É obrigatório ter habilidade de desenvolver nas seguintes linguagens:**
PHP;
Angular

**Será um diferencial conhecer as seguintes tecnologias:**
Laravel;
Bootstrap;

Benefícios
O profissional será contratado pelo regime CLT, com isso terá os seguintes benefícios:

Vale-transporte;
Vale-refeição
Plano de Saúde

Como se inscrever na vaga?
Mande seu curriculo e um link para o desafio concluído no email rh@grupounicad.com.br

Link Desafio: https://drive.google.com/open?id=1HDD3fA4yRVFA2XZHa2UtVZmKpluqrxBT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
