### ISSUE TITLE
[Porto Alegre/Remoto] Back-end Developer Pleno/Sênior (.Net Core) @Trinca

### ISSUE THREAD

**Issue by Gabrielarochay** [backend-br/vagas#7019]
**VOCÊ NA TRINCA**
A Trinca é uma empresa de tecnologia e aqui trabalhamos de forma hibrida. Ou seja, mesmo após a pandemia você pode escolher se quer trabalhar de casa ou não. Construímos uma cultura que tem como base a colaboração e o bom relacionamento entre todos.
Valorizamos as pessoas, gostamos de celebrar e agradecer nossas conquistas — que são suas também. Aqui, não temos regras para inventar happy hour ou um web cafézinho durante o dia.

**Aqui, você encontrará:**

- Equilíbrio entre vida pessoal e profissional;
- Horário de trabalho flexível — entendemos que o home office tem seus desafios;
- Liberdade para ser quem você é — não se acanhe;
- Além de buscar uma evolução constante, contamos com um plano de carreira individualizado para você.

**SOBRE A VAGA**
Buscamos Back end Developer .Net Core! Alguém versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

**HABILIDADES QUE VOCÊ PRECISA TER**

- Experiência com desenvolvimento em .Net Core e SQL Server;
- Diferencial: conhecimento no Microsoft Azure

// Estamos trabalhando de forma distribuída/remoto 👍
// Contratação: PJ

![Back end](https://user-images.githubusercontent.com/66493175/133308958-52911f56-b7ab-42c8-87bf-b1aae46575fe.png)

**Comment by CarlosHenriqueRC** [comment]
A vaga é para pleno ou sênior ?
******************************************
* Carlos Henrique Ramos Carvalho
* Analista de Sistemas Sênior
* MCP.Net
******************************************


Em ter., 14 de set. de 2021 às 14:56, Gabriela Rocha <
***@***.***> escreveu:

**Comment by Gabrielarochay** [comment]
Oi @CarlosHenriqueRC é para Pleno/Sênior. 
Tenho 3 posições em aberto. Alguém entre essas senioridades é ótimo.
