### ISSUE TITLE
[Belo Horizonte/MG] Analista de Desenvolvimento de Software na UPFLOW

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#702]
### Sobre a empresa: upFlow.me

A upFlow é uma startup com aproximadamente três anos de mercado. Nossa missão é ajudar as empresas a explorarem melhor seu potencial de gestão, através da automação de processos de negócios. Nosso ambiente é dinâmico, descontraído e horizontal. Procuramos sempre trazer para nosso time pessoas com muita iniciativa, que gostam de trabalhar com autonomia e que tenham sentimento de "dono do negócio". Prezamos pelo compromisso e por pessoas que procuram sempre fazer o seu melhor. Não há dress code, nosso período de trabalho é de 40h semanais e os horários são flexíveis.

### Descrição: O que você irá fazer?

Desenvolver Front-end.
Realizar integrações entre sistemas (webservice, rest).
Criar consultas em Bancos de Dados.
As habilidades necessárias:

JavaScript;
HTML;
CSS

### Diferenciais

jQuery;
Bootstrap;
Conhecimento da plataforma Fluig.
Conhecimento em back end

### Benefícios

Vale Transporte;
Vale Alimentação
Plano de Saúde e Odontológico.

### Você gostará de trabalhar aqui se

Trabalhar com sangue nos olhos e com sentimento de propriedade da empresa;
Ser pró ativo e ter muita iniciativa;
Estiver em busca de crescimento profissional.

### Labels

Alocado
Pleno

### Candidatar: http://bit.ly/upflow_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
