### ISSUE TITLE
[São Paulo] Back-end Ruby @ TotalPass

### ISSUE THREAD

**Issue by Grazi110** [backend-br/vagas#7028]
> Vaga Remota 

## TotalPass

Uma empresa que oferece benefícios corporativos para o bem estar, proporcionando acesso à diversos serviços como academias, estúdios especializados em corrida, boxe, yoga, ciclismo, treinos funcionais coletivos e desenvolvimento muscular. Temos prazer em descomplicar a vida dos nossos clientes com as nossas soluções e fazemos isso de uma forma colaborativa, em um ambiente desafiador.
Estamos em expansão na América Latina e a área de tecnologia protagonizará grandes evoluções no negócio, diante dessa missão, valorizamos quem tem cabeça de dono, sonha grande e é apaixonado em aprender e ensinar.

## Descrição da vaga
Atuar em squads dentro de uma tribo multidisciplinar construindo uma plataforma escaláveis, resilientes e de alta disponibilidade;
Propor idéias junto com outros engenheiros para elevar a tecnologia e aplicar as melhores práticas de forma consistente;
Monitorar e avaliar o desempenho de seus entregáveis;
Monitorar e propor soluções de performance e melhor utilização de recursos; 
Aprender constantemente e ser flexível com mudanças;
Fornecer manutenção contínua e suporte em sistemas e plataformas existentes;
Participar na evolução do produto, buscando sempre o melhor valor agregado para o negócio, baseando suas decisões em dados;
Compartilhar conhecimentos e ajudar seus pares quando precisam;
Simplificar ideias complexas ou de difícil implementação.

## São Paulo

Remoto

## Requisitos
Linguagens orientadas a objeto, em destaque Ruby;
Proficiência em desenvolvimento orientado a testes e frameworks de testes automatizados;
Vivência no ciclo de vida de desenvolvimento de software;
Vivência com sistemas de CI/CD;
Vivência com Pair Programming (Aprender e compartilhar);
Vivência com princípios SOLID e padrões de projeto;
Inglês Técnico

**Desejáveis:**
- 6 anos de experiência com Ruby on Rails

## Benefícios

- Vale Transporte
- Vale Refeição
- Vale Alimentação
- Plano de Saúde Bradesco
- EduPass (Subsídio de até R$ 140,00/mês para cursos extracurriculares)
- Acesso grátis a mais de 2.000 academias, incluindo Smart Fit e BioRitmo
- ...

**Diferenciais:**
Somos uma empresa que apoia o modelo de trabalho remoto e estamos constantemente nos esforçando para criar o melhor time, independente de onde as pessoas estejam. Mas se você prefere trabalhar presencialmente, temos um escritório localizado na Av. Paulista - São Paulo/SP / Em frente ao metrô Trianon Masp.
- ...

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para glaciele.meirelles@totalpass.com.br com seu CV anexado - enviar no assunto: Vaga Ruby

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: glaciele.meirelles@totalpass.com.br

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by andresilvape** [comment]
Boa tarde. Em Ruby sou pleno considerando toda minha stack e
capacidade resolutiva de problemas e inovações.

https://www.linkedin.com/in/andré-amaro-b7603422/

Em qua., 15 de set. de 2021 às 16:48, Grazi110 ***@***.***>
escreveu:
