### ISSUE TITLE
(São Paulo) - Desenvolvedor Java

### ISSUE THREAD

**Issue by JulianaACS19** [backend-br/vagas#703]
Desenvolvedor JAVA Backend com experiência em WebServices, 
Banco de Dados ORACLE/SYBASE, Microserviços, Spring, 
JAX-WS, EJB, MAVEN, SQL, WEBSPHERE WAS/MQ 
Versionamento GIT e metodologia Agile. 
IDE Eclipse.
Desejável: Angular JS e Angular.

**projeto contempla perfis júnior, pleno e sênior

São Paulo  - Região sul - Morumbi

CLT - Projeto de 1 ano, com grande possibilidade de prorrogação.

**Comment by JulianaACS19** [comment]
Interessados: enviar cv para juliana.silva@assuranceit.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
