### ISSUE TITLE
[Remoto] Back-end Developer @ Let’s Delivery

### ISSUE THREAD

**Issue by mateuscardosodeveloper** [backend-br/vagas#7043]
## Sobre a Let’s Delivery

Somos uma consultoria de food delivery que conta com uma metodologia própria para prototipar
as soluções de plataforma, serviço, logística interna e treinamento que levarão cada restaurante
até seus objetivos. No centro de nossa operação contamos com estrategistas, consultores,
engenheiros e programadores que preparamos para produzir toda a inteligência e tecnologia que
facilitará a gestão do delivery de nossos clientes.

## Descrição da vaga

Buscamos um desenvolvedor Backend Júnior para se juntar ao time da Let’s Delivery.
Seu foco será desenvolvimento Backend com Python, FastAPI e AWS. Se você gosta de trabalhar
em ambientes desafiadores e dinâmicos, é proativo, busca crescer e se desenvolver, valoriza o
trabalho em equipe e a troca de experiências para evoluir seus conhecimentos e de seus parceiros
de trabalho, é flexível para entender demandas e veloz para entregar resultados, então essa vaga
é pra você. Na Let’s, somos apaixonados por tecnologia e buscamos constantemente inovação e
excelência técnica. Aqui, você terá a oportunidade de desenvolver código de qualidade do
conforto de sua casa.

## Local

Full Remoto

## Requisitos

**Obrigatórios:**
- Experiência em pelo menos uma framework de backend em Python (Django, Flask ou FastAPI)
- Conhecimento de Git
- Conhecimento de Linux

**Diferenciais:**
- Conhecimento em AWS (API Gateway, Lambda, Dynamodb, RDS, Code Commit) 

## Contratação

PJ a combinar

## Como se candidatar

Interessados na vaga de Pleno acessar o link do formulário [Click aqui.](https://docs.google.com/forms/d/1Be1XEGGl5X0896yp-QJYUSY1geeMhVaAC8zWHa01KZE/viewform?edit_requested=true)

Interessados na vaga de Junior acessar o link [Aqui.](https://docs.google.com/forms/d/e/1FAIpQLSeI1w04Jh7CcKW-0mcpJu0_uPH0O9ROzcYHuRIQn4gpTFBBCg/viewform)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by guhenriq** [comment]
Enviado!

**Comment by mateuscardosodeveloper** [comment]
Nice, boa sorte Gustavo!!!
