### ISSUE TITLE
[Rio de Janeiro] Analista Desenvolvedor Java Senior na [Vertigo]

### ISSUE THREAD

**Issue by RHVertigo** [backend-br/vagas#705]
Você trabalha bem em equipe, é diplomático, proativo e tem **superior completo** em ciência da computação/engenharia de sistemas (ou similar) e tem **mais de 5 anos de experiência** em desenvolvimento de sistemas e manutenção em JAVA/JEE?

 Se sim, venha trabalhar conosco! Temos **2 vagas** em aberto para o **Rio de Janeiro**!

• Conhecimentos em Ambiente Linux, Banco de Dados e Frameworks Springboot e SpringBatch, Spring JPA
• Experiência em ferramentas de controle de versão (SVN e GIT); em ambientes de Integração Contínua (JEKINS e MAVEN); com servidores de aplicação Jboss 5.X, Jboss 7.X e com AngularJS, JSON e Jquery

Oferecemos salário + benefícios (VT, VR, VA,PS, PO, SV) e convênio com o SESC.

Se você se enquadra no perfil, acesse https://lnkd.in/emvxppN e se cadastre.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
