### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Full Stack na BLACKBOOK

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#706]
### Sobre a empresa: Black Book

Fundada em 1999, a Blackbook Editora é responsável pela edição e publicação da série de manuais Blackbook.
 
Concebidos pelo doutor Reynaldo Gomes de Oliveira, nossos manuais são inspirados nas pequenas cadernetas pretas utilizadas por diversos médicos norte-americanos no início do século XX para compilar as anotações sobre doses de medicamentos, fluxogramas de condutas, fórmulas de cálculos, diagnósticos diferenciais e várias outras informações e referências essenciais para a prática da Medicina.
 
Assim nascem os Blackbooks: sem a pretensão de substituir o estudo em tratados e livros especializados, mas com o objetivo de ser um importante instrumento de consulta rápida em momentos críticos da prática médica. Prático e salvador.

### Descrição: Quais são os requisitos básicos?

JavaScript e Angular.js;
Python e Django;
NoSQL banco de dados em geral SQL;
HTML5 / CSS;
jQuery;
Scrum;

### O que brilharia os nossos olhos?

Integração com web Service, RESTFul e SOAP, domino SQlite;
TDD;
Material Design;
Ferramentas de configuração de Software (GIT);
Sketch;
Bugzulla, Jira - Ferramentas de gestão de bugs;
Perfil de liderança

### Você gostará de trabalhar aqui se

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho e se comunica bem com pessoas do negócio;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Quer ter a oportunidade de tomar a frente do projeto e idealiza-lo do zero; 
Tem autonomia para tomar decisões e é criativo para propor soluções;

### Labels

Alocado
Pleno

### Candidatar: http://bit.ly/blackbookfull_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
