### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP na Leroy Merlin

### ISSUE THREAD

**Issue by ravanscafi** [backend-br/vagas#71]
<p align="center">
    <br/>
    <a href="https://www.leroymerlin.com.br" title="Leroy Merlin">
        <img src="https://cdn.leroymerlin.com.br/assets/lizard/images/logo-leroy.svg" alt="Leroy Merlin"/>
    </a>
</p>

## Descrição da vaga
Estamos procurando novos integrantes para nossos times aqui na Leroy Merlin Brasil!

Crescemos de forma ordenada, sendo atualmente responsáveis pelo Site/E-commerce/Plataforma de Vendas das Lojas, além de outros projetos que estão surgindo e que você poderá ajudar a construir :smile:

Priorizamos qualidade e valor de negócio. Adotamos boas práticas de desenvolvimento como TDD, Pair Programming, Code Review, entre outros, nos embasando em Metodologias Ágeis para o sucesso de nossos projetos e equipes. Estamos constantamente nos atualizando e buscando novas tecnologias que façam sentido para os nossos desafios. 

Valorizamos e contribuímos para o _open source_, tendo vários projetos publicados em @leroy-merlin-br.

Nossas stacks são basicamente `PHP 7+` com `Laravel 5+`, `MongoDB`, `Elasticsearch`, `Redis`.
Utilizamos `Docker` e provisionamos nossa infraestrutura na `AWS`, utilizando boas práticas de `IaC`.

## Local

**Presencial**, Chácara Santo Antônio - Zona Sul, São Paulo/SP

## Benefícios

- PPLR e outras bonificações
- Assistência Médica
- Assistência Odontológica
- Vale Refeição
- Vale Transporte
- Cesta Básica
- Seguro de Vida
... entre outros.

## Requisitos

Estamos buscando devs que tenham os seguintes conhecimentos:
- `PHP 7+`
- `OOP`
- Pelo menos um dos frameworks MVC: `Laravel`, `Symfony`, `Rails`, `Zend`
- `Testes automatizados`*

\* Caso você não possua conhecimentos em testes automatizados, haverá oportunidade de demonstrar sua capacidade de aprendizado em nosso teste prático.

## Contratação

CLT - Presencial

## Nossa empresa

A [Leroy Merlin](https://www.leroymerlin.com.br/) é líder em Home Center no Brasil. Somos um dos maiores cases de e-commerce Laravel no Brasil e talvez até no mundo.
Trabalhamos em projetos de transformação digital, atuando como e-commerce para nossos Clientes e plataforma de venda para nossos Assessores das Lojas no Brasil. Além disso, possuímos outros projetos em fase de desenvolvimento.

## Como se candidatar

Ficou interessado? Envie um e-mail para `rscafi@leroymerlin.com.br` com o assunto _”[Vaga-backend]”_, informando seu GitHub/LinkedIn/Portfólio juntamente com seu CV e bora bater um papo, que explicamos mais e nos conhecemos! :wink:

**Comment by josebispo** [comment]
Que vaga maravilhosa, trabalhar com artesões fodas como o zizaco, pena que é presencial, desejo muito sucesso pro cara que preencher essa vaga.
**php artisan inspire** 
* Leroymerlin is hiring an artisan*

**Comment by reginaldojunior** [comment]
Vaga preenchida?

**Comment by ravanscafi** [comment]
não, vagas em aberto!
se puder reabrir, agradeço.

**Comment by reginaldojunior** [comment]
Reaberto :heart_eyes:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.

**Comment by carusogabriel** [comment]
Poderiam reabrir a vaga com o email de contato como `maarujo@leroymerlin.com.br`?
