### ISSUE TITLE
[Belo Horizonte] JAVA Developer na CAST GROUP

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#710]
## Descrição da vaga

Estamos buscando um(a) profissional que desenvolva em Java, com experiência consolidada com os frameworks Angular JS, Wicked, JavaScript, Hibernate e Spring. Além dos conhecimentos técnicos, buscamos uma pessoa que tenha facilidade e goste de trabalhar em equipe, que seja engajada e que dê tudo de si nos projetos. Você terá a oportunidade de atuar em um dos nossos clientes (um dos maiores bancos do Brasil). 

## Local

Alocado no cliente – área central de BH

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- VT 
- Pontos Good (valor disponível para conversão em benefícios, como vale combustível, VA, VR, reembolso para cursos, etc.)

#### Diferenciais

- horário flexível
- plano de carreira
- oportunidade de trabalhar com uma equipe massa e diversificada

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JAVA
- Experiência consolidada com os frameworks Angular JS, Wicked, JavaScript, Hibernate e Spring

**Desejáveis:**
- Facilidade em trabalho em equipe

## Contratação

CLT com salário a combinar.

## Nossa empresa

Com 28 anos de mercado, a Cast group é uma empresa nacional de Tecnologia da Informação e automação com larga experiência em grandes projetos para as áreas privada e pública, que atua com consultoria e soluções de TI e TA.

Hoje, a Cast group é reconhecida por seus mais de 320 clientes, especialmente nas áreas de finanças, indústrias e serviços, como, Banco do Brasil, Cielo, Datasus, Vale, Cemig, Gerdau, EDP, Eletrobrás, Grupo Petrópolis, Atento, Renault, Randon, Bosh, Ipiranga Agroindustrial, DrogaRaia e Banco Central do Brasil. 

## Como se candidatar

Por favor, envie um email para sabrina.fantoni@castgroup.com.br com seu CV anexado - enviar no assunto: JAVA Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: sabrina.fantoni@castgroup.com.br

## Labels

- Alocado
- CLT

**Comment by ghost** [comment]
Ainda estamos com a oportunidade disponível...

**Comment by Pompeu** [comment]
Cast Grupo empresa top que paga muito bem.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
