### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na NAMU

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#712]
### Sobre a empresa: Namu

O Namu Cursos é a primeira plataforma de cursos online pensada para uma vida mais equilibrada.

### Sobre o papel

Você irá ajudar a pensar, estruturar , modificar ou criar as plataformas que serão a base para alcançarmos a nossa missão de contribuir para a evolução individual e coletiva, através da geração e divulgação de conteúdos, serviços e produtos que inspirem uma vida mais equilibrada.

### O que você vai fazer

Trabalhar em estreita colaboração com nossa equipe de atendimento, marketing, designers e clientes para criar ferramentas que impulsionem o crescimento acelerado do Namu. 

Trabalhar nas soluções de front-end e back-end

### Requisitos

- Necessário experiência na área.
- Formação superior em áreas de tecnologia e desenvolvimento
- Experiência comprovada no desenvolvimento de soluções de alto desempenho e qualidade.
- Experiência em front-end (javascript , html, css).
- Experiência comprovada em back-end (php, banco de dados mysql, servidor linux)
- Conhecimento em desenvolvimento para wordpress

### Labels

PJ
Alocado
Pleno

### Candidatar: http://bit.ly/namu_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
