### ISSUE TITLE
[Florianópolis] Back-End Java Developer na Sábia Experience

### ISSUE THREAD

**Issue by xandyalexandrec** [backend-br/vagas#714]
## O que esperamos de você:

- Pró-atividade;
- Sempre buscar inovar e trazer novas tendências;
- Ter espírito de trabalho em equipe;

## Local

Sapiens Parque
Av. Luiz Boiteux Piazza, 1302 - Canasvieiras, Florianópolis - SC, 88056-000

## Benefícios

- Remuneração competitiva;
- Plano de saúde;
- Vale-Transporte;
- Vale-refeição;

#### Diferenciais

- Dress free;
- Ambiente descontraído;
- Mesa de Ping Pong;
- Empresa de Inovação na área de Educação;
- A 700m da praia;

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de Java 8 (Lambda e Streams);
- Spring(Sprint boot, Spring DATA);
- JPA;
- Hibernate;

**Desejáveis:**
- AspectJ
- Kotlin;
- JMS (Amazon SQS, ActiveMQ);
- Apache POI;
- Liquibase;
- MySQL;
- GIT;
- Jenkins;
- Sonar;

**Diferenciais:**
- Experiência com Google Cloud

## Contratação

CLT

## Nossa empresa

A Sábia Experience é uma empresa de inovação atuando como EdTech, especializada em educação imersiva usando storytelling e gamificação. além de realidade virtual e aumentada.

## Como se candidatar

Por favor envie um email para alexandre.custodio@sabia.com.br com seu CV anexado - enviar no assunto: [Vaga] Back-end Developer

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
