### ISSUE TITLE
[RibeirãoPreto] Back-End Developer na [6P Marketing e Propaganda]

### ISSUE THREAD

**Issue by agencia6p** [backend-br/vagas#716]
Oportunidade para Desenvolvedor Backend e Frontend com disponibilidade para início imediato.
Se você é um apaixonado por programação e se interessou pela vaga, envie seu CV para o e-mail trabalheconosco@6p.com.br com o título “Desenvolvedor Backend” ou  “Desenvolvedor Frontend”

Descritivo da atividade e qualificação:

Aplicação de técnicas avançadas de SEO;
Desenvolvimento de códigos CSS, JavaScript, PHP, MySQL, jQuery e Bootstrap;
Lógica de programação em bancos de dados;
Conhecimento em desenvolvimento de Front-end;
Desejável conhecimento em WordPress;
Noções de estruturação e configuração de servidores;
Desenvolvimento de códigos com pensamento em UX;
Objetividade: capacidade de solucionar desafios de forma simples e prática;
Boa capacidade de planejamento e organização;
Criatividade e sensibilidade artística para perceber as tendências estéticas e visuais da linguagem digital;
Raciocínio lógico e analítico.

Gostar de inovação, estar por dentro de tendências, trabalhar em equipe, aprender, ensinar e se virar.
Aplicar melhores soluções sempre com perspectiva de prazos e com foco na qualidade da entrega.
Saber lidar com diversos projetos simultâneos é um diferencial.

Exigências:
• Formação em Análise de Sistema, Ciência da Computação, Engenharia da Computação ou áreas relacionadas;
• Excelente comunicação verbal e escrita;
• Experiência mínima como programador de 3 anos.

**Comment by dodopok** [comment]
Enviei! Não sou formado, mas tenho mais de 7 anos de experiência.

**Comment by davidrtpereira** [comment]
Remoto?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
