### ISSUE TITLE
[Florianópolis] DevOps na Sábia Experience

### ISSUE THREAD

**Issue by xandyalexandrec** [backend-br/vagas#718]
## O que esperamos de você:

- Pró-atividade;
- Sempre buscar inovar e trazer novas tendências;
- Ter espírito de trabalho em equipe;

## Local

Sapiens Parque
Av. Luiz Boiteux Piazza, 1302 - Canasvieiras, Florianópolis - SC, 88056-000

## Benefícios

- Remuneração competitiva;
- Plano de saúde;
- Vale-Transporte;
- Vale-refeição;

#### Diferenciais

- Dress free;
- Ambiente descontraído;
- Mesa de Ping Pong;
- Empresa de Inovação na área de Educação;
- A 700m da praia;

## Requisitos

**Obrigatórios:**
- Docker Avançado
- Kubernetes Avançado
- Cloud (Google Cloud, Azure e AWS)
- SSL
- CD/CI (Jenkins)
- MySQL Server;
- Apache / Nginx;
- Linux (CentOs/Ubuntu/Fedora);
- Redes (Firewall/DNS/DHCP/Samba/VPN);
- Asterisk;
- AD/LDAP;

**Desejáveis:**
- Windows Server;
- Hardware;
- Weblogic;
- Mercurial/Git;

**Diferenciais:**
- Java
- ShellScript

## Contratação

CLT

## Nossa empresa

A Sábia Experience é uma empresa de inovação atuando como EdTech, especializada em educação imersiva usando storytelling e gamificação. além de realidade virtual e aumentada.

## Como se candidatar

Por favor envie um email para alexandre.custodio@sabia.com.br com seu CV anexado - enviar no assunto: [Vaga] DevOps

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
