### ISSUE TITLE
[100% home office] Desenvolvedor Front-end ReactJs @ Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [backend-br/vagas#7186]
Será o responsável por desenvolver novas funcionalidades de frontend para a aplicação, garantindo sempre uma aplicação estável e com uma boa qualidade de código e arquitetura.

Responsabilidades

●	Evolução: realizar desenvolvimento de novas funcionalidades do frontend visando sempre um código limpo e organizado
●	Manutenção: resolver e acompanhar incidentes no sistema
●	Refactore: sempre que necessário irá refatorar aprimorando e organizando a estrutura código
●	Usabilidade: implementar as funcionalidades visando sempre a melhor usabilidade para nossos clientes
●	Layout: responsável por criar novos layouts e aprovar junto ao solicitante para realizar a demanda
●	Deploy: acompanhar os deploys de novas releases, garantindo a qualidade da entrega e a validação do que estamos subindo em produção. Tentando também automatizar sempre o que for possível
●	Q&A: realizar testes end-to-end em todas implementações realizadas garantindo assim a qualidade da entrega
●	Infraestrutura: contribuir com o time de infraestrutura para qualquer configuração referente ao projeto, tentando automatizar sempre o que for possível.
●	Stack: ReactJS, ReactNative, Angular, Bootstrap, Material, Docker, Kubernetes e outras ferramentas que a empresa venha implementar

100% home office.

Modelo: PJ por tempo indeterminado. 

CVs via: rh@hagloo.com

**Comment by franciscofpll** [comment]
As issues aqui sao para desenvolvedores backend, acho que voce vai ter mais sorte em encontrar profissionais aqui: https://github.com/frontendbr/vagas/issues

**Comment by giovaniPoletohagloo** [comment]
Realmente postei no lugar errado, obrigado por avisar, Francisco. :)
