### ISSUE TITLE
[Remoto] [Internacional] Python Developer @ BHS

### ISSUE THREAD

**Issue by vvoa99** [backend-br/vagas#7189]
> Vaga 100% Remota

## Nossa empresa

Nós somos a BHS!

Reconhecida desde 2015 como uma das melhores empresas para se trabalhar, temos mais de 25 anos de experiência e oferecemos soluções modernas de TI.

## Descrição da vaga
Oportunidade para atuar de modo remoto em um cliente internacional, fazendo parte de uma das 3 melhores empresas para se trabalhar em Minas Gerais, em um ambiente diverso, inclusivo e colaborativo. Tendo boa remuneração, e desafios incríveis!!

## Requisitos

O que a gente espera de você?

Buscamos uma pessoa de fácil relacionamento, com boa comunicação, que seja curioso, goste de pensar fora da caixa e trabalhar em equipe. Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS.

Buscamos uma pessoa que possua experiências com:

- Python.

- Criação de APIs usando Flask / Django / FastAPI ou qualquer outra estrutura moderna.

- Construção de APIs escaláveis

- Google Cloud Platform

- Inglês avançado ou fluente

## Benefícios

- Plano de saúde Unimed;

- Assistência Odontológica

- Vale transporte ou auxílio no estacionamento.

- Vale Refeição, sem desconto

- Incentivo para Pós-Graduação, Especializações e MBA’s;

- Incentivo de certificações que você for aprovado;

- Incentivo a treinamentos;

- Incentivo ao curso de inglês

- Parcerias e convênios diversos

- Licença Maternidade/Paternidade estendida

- PLR

- Programas de conteúdo, como o Deu Match!, e uma rotina com aprendizado constante

## Contratação

CLT

## Como se candidatar

Só se inscrever no link: https://jobs.kenoby.com/bhs/job/python-developer/61434691968d0536b1f04e11?utm_source=website

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by vvoa99** [comment]
Não percam essa chance!!

**Comment by regyeduardo** [comment]
gostei dos requisitos, apesar de estar estudando fast api ainda nao possuo experiencia

**Comment by vvoa99** [comment]
@regyeduardo Vem conhecer a gente, podemos conversar e ver se faz sentindo para você!

**Comment by regyeduardo** [comment]
> gente

como eu entro em contato?

**Comment by regyeduardo** [comment]
> @regyeduardo Vem conhecer a gente, podemos conversar e ver se faz sentindo para você!

Como eu entro em contato?

**Comment by vvoa99** [comment]
> > @regyeduardo Vem conhecer a gente, podemos conversar e ver se faz sentindo para você!
> 
> Como eu entro em contato?

>Você pode se inscrever nesse link: https://jobs.kenoby.com/bhs/job/python-developer/61434691968d0536b1f04e11?utm_source=website
E entramos em contato com você!
