### ISSUE TITLE
[Remoto] PHP Pleno - Code Igniter na Divisio.com.br

### ISSUE THREAD

**Issue by luizeduard0** [backend-br/vagas#719]
#
## Descrição da vaga
Ingressar uma de nossas equipes e atuar no desenvolvimento de um projeto internacional. Trabalhamos com projetos muito interessantes.

## Local
Remoto

## Benefícios
- Férias remuneradas
- Bônus e gratificações por desempenho
- Disponibilizamos cursos para aprendizado/aperfeiçoamento
- Você pode utilizar parte do seu tempo para estudos
- Se você tiver alguma gap, nossos devs vão te ensinar e colaborar p/ sua carreira.

#### Diferenciais
- Chefia horizontal, todos tem voz na empresa.
- Te valorizamos pelo seu resultado e não pelo tempo trabalho. Há muito espaço p/ crescer
- Trabalhamos com as tecnologias mais atuais
- Horário flexível
- Você pode trabalhar de qualquer lugar que quiser

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em PHP (se você não for tiver experiência, nem se aplique p/ vaga)
- Code Igniter (conhecimento indispensável para o projeto que você vai trabalhar)
- Inglês avançado (É um projeto internacional, você vai precisar se comunicar por escrita e audio praticamente todos os dias)
- jQuery
- HTML/CSS

**Desejáveis:**
- Laravel

**Diferenciais:**
- Visão empreendedora

## Contratação
PJ a combinar

## Nossa empresa
Conhece mais sobre a gente no nosso [site](http://www.divisio.com.br).

## Como se candidatar
Por favor envie um email para ola@divisio.com.br com seu CV anexado - enviar no assunto: [VAGA BACKEND] SEU_NOME

OBS: Se você tiver um Github relevante, este pode dispensar a necessidade de teste. Caso contrário, exigimos passar pelo nosso processo seletivo.

## Tempo médio de feedbacks
Uma vez enviado todas as informações damos um retorno em até 5 dias úteis.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
