### ISSUE TITLE
[REMOTO] Back-end Developer Node @ Datamob

### ISSUE THREAD

**Issue by adrianilauffer** [backend-br/vagas#7219]
**Sobre a empresa:**
Eu estou trabalhando como parceira da empresa Datamob, é uma empresa que está há mais de 2 anos no mercado de tecnologia, fica localizada em Porto Alegre.

A empresa desenvolve uma solução de MDM, trabalham com clientes como Tim, Vivo, Oi, Claro, Claro América latina e com atuação também no México.

Buscam profissionais com brilho no olho e engajados para crescer junto com a empresa.

Eles têm um sistema WEB em Ruby on Rails e o APP em Android. Estamos com uma vaga de React para atuar na migração de linguagem do sistema.

O modelo de contratação é PJ ou Cooperado, com bonificação. E se você gosta de trabalhar home office, temos essa opção e se você é de Porto Alegre ou regiões pode optar por fazer home office híbrido.

**Descrição da oportunidade:**
- Deverá trabalhar com metodologias ágeis (Scrum/Kanban) dentro de um time multidisciplinar com foco na entrega de valor.
- É necessário ter conhecimento para entender o problema, pesquisar soluções, conduzir reuniões de validação técnica com o time.
- ﻿Conhecimento básico em frontend é um diferencial, assim como ser resiliente para trabalhar com diferentes tecnologias em caso de necessidade pontual ou para ajudar o time a remover impedimentos.  
- Ser entusiasta por novidades no mundo da tecnologia é algo crucial, portanto, é importante ser apaixonado pelo que faz.
- Fazer a migração da linguagem Ruby on Rails para Node.

**Requisitos técnicos:**

- NodeJS
- Next.js
- NestJS
- Typescript/Javascript
- PostgreSQL
- Docker

Nível:
- Pleno
- Sênior

**Comment by lucasnsborges** [comment]
Qual o e-mail para enviar o cv?
