### ISSUE TITLE
[SÃO PAULO] - PROGRAMADOR JAVA - RESOURCE

### ISSUE THREAD

**Issue by POLLEZI** [backend-br/vagas#722]
## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do 
Brasil e uma as empresas de TI que mais crescem no País. 

PROGRAMADOR JAVA

Perfil :
							
-        Atuação com arquitetura de sistemas (Rest, SOAP, Micro serviços)
-        Conhecimento de processo de integração continua
-        Conhecimento e atuação com metodologias ágeis (TDD, BDD, DDD e Scrum)
-        Conhecimento em desenvolvimento de portais e mobile
-        Experiência com modelagem e implementação de barramento de serviços
-        Linguagens: Java (6, 7 e 8), IIB (IBM Integration Bus)
-        Banco de Dados: Oracle ou Sybase
-        Servidor de Aplicação: JBOSS, Tomcat, WebSphere;
-        Frameworks de Backend: JPA (Hibernate), EJB e Spring;  .

•	Formação Necessária: Curso superior nas áreas de TI ou correlatadas

Local : Ed Rochaverá – Berrini /SP

Benefícios
VR, VT, Convenio Médico, Convenio Odontológico, Auxilio Creche, Convenio Farmácia, Seguro de Vida

Como aplicar:  Envie seu cv com pretensão salarial para adriana.pereira@resourceit.com ou indique um amigo!!!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
