### ISSUE TITLE
[Belo Horizonte] Analista de Sistemas na HBA Tecnologia

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#723]
### Sobre a empresa: HBA Tecnologia

Empresa do setor de eventos, feiras, congressos e eventos corporativos. Há 15 anos no mercado, atendendo a clientes de todo o território nacional.

### Descrição: Ocupações do cargo

Especificação conceitual/técnica, desenvolvimento de novas aplicações e sustentação de aplicações existentes, testes de software, documentação, etc.

### Benefícios

Plano de saúde;
Plano Odontológico;
Restaurante na empresa;
Vale transporte;

### Aptidões e qualidades

Sólidos conhecimentos em desenvolvimento e arquitetura de software para Web;
Utilizando tecnologias C#, ASP.NET Core, ASP.NET MVC, Docker, Java Script, API Rest, Microseviços, MySQL, SQL Server.
Experiência com o desenho de soluções utilizando serviços em nuvem como Amazon Web Services (AWS), Microsoft Azure, etc.;
Conhecimento em metodologia de desenvolvimento Ágil (Scrum), Azure Devops (VSTS), dentre outros.

### Labels:

Alocado
Senior
CLT

### Candidatar: http://bit.ly/hba_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
