### ISSUE TITLE
[Rio de Janeiro, RJ] Storm Group - Desenvolvedor Web Sênior

### ISSUE THREAD

**Issue by luanstorm** [backend-br/vagas#724]
### **Requisitos obrigatórios**

- Ter experiência sólida com desenvolvimento no front-end.
- Gostar de programar em todos os níveis do stack tecnológico.
- Ter experiência com bibliotecas e frameworks de front-end como React.
- Ter excelente conhecimento de linguagens de programação como Nodejs, Python, Ruby, etc
- Ter conhecimentos em design e arquitetura de software.
- Ter profunda preocupação com qualidade e performance.
- Compreender a importância e praticar versionamento de código.
- Escrever código limpo e legível para pessoas.
- Ter conhecimentos de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc).

### **Nossa empresa**
A Storm Group é uma prestadora de serviços e integradora de soluções completas em tecnologia, desde o desenvolvimento e manutenção de sistemas de alta performance até a criação de aplicativos web e mobile.

### **Como se candidatar**
Por favor envie um email para rh@stormsec.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Web Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
