### ISSUE TITLE
[Rio de Janeiro, RJ] Storm Group - Desenvolvedor Backend Sênior

### ISSUE THREAD

**Issue by luanstorm** [backend-br/vagas#725]
### **Principais responsabilidades:**
- Desenvolvimento de aplicações Back-End;
- Atuar na conceituação, desenvolvimento, deploy e debugging de sistemas.

### **Pré-requisitos:**
- Ter facilidade de trabalhar em times de desenvolvimento multi-disciplinares;
- Aderente à cultura de inovação e desenvolvimento;
- Experiência com metodologias de desenvolvimento, tais como Scrum, Agile e Lean Startup;
- Proficiência total em Python e MongoDB;
- Proficiência em desenvolvimento em containers;
- Proficiência em desenvolvimento orientado a testes e comportamento (TDD e BDD);

### **Desejável:**
- Desejável conhecimento em NodeJS, C++, Java, RabbitMQ;
- Desejável  conhecimento desenvolvimento FrontEnd Web (HTML5, CSS3 e Javascript); e
- Desejável experiência com cadeias de integração e entrega contínua (CI/CD);

### **Nossa empresa**
A Storm Group é uma prestadora de serviços e integradora de soluções completas em tecnologia, desde o desenvolvimento e manutenção de sistemas de alta performance até a criação de aplicativos web e mobile.

### **Como se candidatar**
Por favor envie um email para rh@stormsec.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Backend Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
