### ISSUE TITLE
[Florianópolis, São Paulo e Joinville] SRE / DevOps - Resultados Digitais

### ISSUE THREAD

**Issue by kaiofelipejs** [backend-br/vagas#727]
_Work together and create leverage!_

**Profissional que procuramos:**
Buscamos pessoas que querem enfrentar grandes desafios de escalabilidade, alta quantidade de dados e rápido crescimento de usuários. Nascemos na nuvem, temos um ambiente complexo e buscamos constantemente automatização operacional. Mantendo uma mentalidade IaaC (infra as a code), queremos consolidar a infra em cloud da RD fazendo o máximo possível para simplificar os ambientes. Temos iniciativas de monitoramento e otimização de deploy, com espaço para várias melhorias subsequentes mantendo uma personalidade Lean. Curtiu o desafio? Vem fazer parte do nosso timaço de especialistas!

**O que esperamos de você:**
- Forte conhecimento em configuração e gestão de infraestrutura em cloud (AWS, Azure, GCP, Heroku...)
- Ter trabalhado com sistemas de alta disponibilidade;
- Experiência com desenvolvimento (Python ou Go, seria o ideal);
- Saber lidar com ferramentas de gestão de configuração;
- Conhecimento em CI / CD (Travis, Jenkins, Circle CI);
- Experiência com versionamento Git;
- Conhecimento em sistemas operacionais modernos (Linux, Ubuntu, CoreOS);
- Inglês.

**Será considerado um diferencial para assumir este desafio:**
- Experiência com gestão de incidentes;
- Ter trabalhado com metodologias ágeis.

Nascemos com o objetivo de nos tornar a maior empresa de tecnologia em marketing digital e estamos indo rápido nessa direção. Já são mais de 13.000 clientes, +1.500 agências parceiras, +100 parceiros de integrações e muito aprendizado.
Por 4 anos consecutivos somos a melhor empresa para se trabalhar de Santa Catarina segundo a GPTW, e só conseguimos isso mantendo um ambiente agradável, em que nossos colegas curtam estar todos os dias. Provemos flexibilidade de horários, incentivo ao autodesenvolvimento e muita autonomia no dia a dia.

Nosso ambiente descontraído com várias áreas integradas contribui para que todos tenham voz e participem das decisões da empresa como um todo. Queremos escutar suas opiniões e, sempre que possível, colocá-las em prática. Para melhorar ainda mais esse ambiente, conduzimos e participamos de seminários, encontros, meetups. No nosso Culture Code está os nossos valores e no blog como estamos trabalhando, com eles você pode saber um pouco mais sobre nós.

**Localização da vaga:**
Florianópolis/SC - Brasil
Joinville/SC - Brasil
São Paulo/SC - Brasil

Para se candidatar acesse: bit.ly/rd_sre :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
