### ISSUE TITLE
[Rio de Janeiro ] Estágio em Back-end  @ Fattoria web 

### ISSUE THREAD

**Issue by CarolPimentel** [backend-br/vagas#7274]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa licalizada no Centro do Rio, com conhecimento sólido do mercado digital. Vamos da criação da marca, planejamento da campanha de marketing digital até o desenvolvimento de um sistema escaláveis e aplicativos mobile.

## Descrição da vaga

Auxiliar na implantação, adaptações e criações de módulos nos sistemas.

## Local

Remoto enqto durar a pandemia.

## Requisitos

**Obrigatórios**
- Cursando a partir do 3° período da faculdade de Engenharia de software, Analise de Sistemas e afins;
- conhecimentos em Java e frameworks Struts, Vraptor, noçoes em EJB, JBoss, JSP, controle de versionamento GIT e SVN, banco de dados Oracle.

**Desejáveis:**
Conhecimentos em Javascript e no ambiente de desenvolvimento (IDE) Eclipse.

**Diferenciais:**
 Prática com EJB e JPA.

## Benefícios
Bolsa auxílio e:
- Seguro de vida
- VR de R$26,00/dia
- VT ao retornar ao presencial

## Contratação

Contrato de Estágio. CIEE

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com seu CV anexado - enviar no assunto: Vaga EstagioBack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@fattoriaweb.com.br

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by grehgcl** [comment]
ainda esta disponivel?
