### ISSUE TITLE
[Florianópolis, São Paulo e Joinville] Backend Developer - Resultados Digitais

### ISSUE THREAD

**Issue by kaiofelipejs** [backend-br/vagas#728]
_Work together and create leverage!_

Na tribo de OnGoing somos responsáveis por manter e evoluir a plataforma RD Station Marketing. Somos times multidisciplinares, responsáveis por diversas features e por criar componentes e estruturas cross áreas. Nosso foco é criar soluções que suportem até 10x o nosso tamanho atual e que sejam escaláveis até 100x!

Buscamos pessoas amantes de tecnologia e que estejam dispostas a contribuir e impactar a vida de milhares de pessoas que utilizam nossos serviços. Nosso foco é escalar cada vez mais nossa plataforma e para isso precisamos de gente muito boa a fim de colocar a mão no código e fazer acontecer! Se você não conhece de marketing digital não tem problema, nós te ensinamos ;)

Utilizamos métodos ágeis (XP, Scrum, Kanban) e desenvolvemos especialmente em Ruby (Rails e Sinatra), mas temos sistemas e componentes em Go, Elixir e Java. No front usamos ES6+ além de possuirmos aplicações em EmberJS e ReactJS. Tudo está nas nuvens, nossa infra roda principalmente sobre Amazon, Google Cloud e Heroku. Usamos Sendgrid para envio de emails e Postgres, Mongo e Redis para banco de dados. Utilizamos GitHub, Code Climate para análise estática e Circle CI para integração contínua, tudo integrado (inclusive deploys) via Slack.

**Principais habilidades e conhecimentos para você assumir esse desafio:**
- Resolver problemas e implementar soluções envolvendo múltiplos times e profissionais;
- Amar entregar software bem testado e bem desenhado;
- Sólido conhecimento nas linguagens Ruby, Go, NodeJS, Java ou Python;
- Experiências com bancos de dados como: MySQL, PostgreSQL, MongoDB ou Redis;
- Conhecimento em IaaS como: AWS, Google Cloud ou Heroku.

Nascemos com o objetivo de nos tornar a maior empresa de tecnologia em marketing digital e estamos indo rápido nessa direção. Já são mais de 12.000 clientes, +1.500 agências parceiras, +100 parceiros de integrações e muito aprendizado.
Por 4 anos consecutivos somos a melhor empresa para se trabalhar de Santa Catarina segundo a GPTW, e só conseguimos isso mantendo um ambiente agradável, em que nossos colegas curtam estar todos os dias. Provemos flexibilidade de horários, incentivo ao autodesenvolvimento e muita autonomia no dia a dia.

Nosso ambiente descontraído com várias áreas integradas contribui para que todos tenham voz e participem das decisões da empresa como um todo. Queremos escutar suas opiniões e, sempre que possível, colocá-las em prática. Para melhorar ainda mais esse ambiente, conduzimos e participamos de seminários, encontros, meetups, temos um ambiente acolhedor com café da manhã, frutas à vontade, games (do dominó até PS4) e happy hours - caso você curta.
No nosso Culture Code está os nossos valores e no blog como estamos trabalhando, com eles você pode saber um pouco mais sobre nós.

**Localização das nossas vagas:**
Florianópolis/SC - Brasil
Joinville/SC - Brasil
São Paulo/SP - Brasil

Para se candidatar, acesse: bit.ly/rd_rdsm

**Comment by thallysrc** [comment]
linkn pra se candidatar esta quebrado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
