### ISSUE TITLE
[Ribeirão Preto, SP] Desenvolvedor Python na Crave

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [backend-br/vagas#729]
Vaga para desenvolvedor Python de todos os níveis.

A vaga é para trabalho presencial, contratação por PJ com direito a vários benefícios. 

Equipe focada em manter excelência técnica, independentemente do seu nível, tenho certeza que pode aprender muito e nos ensinar muito também. :)

Para mais informações, acessar o link abaixo ou entrar em contato comigo.

https://crave.workable.com/j/50FBB88DE0

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
