### ISSUE TITLE
[São Paulo] Python developer no CEPID NeuroMat (R$ 7.372,40)

### ISSUE THREAD

**Issue by carlosribas** [backend-br/vagas#732]
## Descrição da vaga

Buscamos uma pessoa para trabalhar com o desenvolvimento de software de suporte à pesquisa científica do CEPID NeuroMat.

## Local

Instituto de Matemática e Estatística da USP, Cidade Universitária, São Paulo.

#### Diferenciais

- Horário flexível
- Assistir aulas e palestras do IME-USP 

## Requisitos

**Obrigatórios:**
- Título de doutorado **OU** 5 anos de experiência após a graduação em qualquer área da TI (exigência da FAPESP - http://www.fapesp.br/3098).
- Python

**Desejáveis:**
- Django
- Docker
- Git
- Bootstrap
- HTML, CSS e JS
- Linux

**Diferenciais:**
- projetos opensource

## Contratação

Bolsa TT5 da FAPESP no valor de R$ 7.372,40 (http://www.fapesp.br/3162), para uma dedicação de 40 horas semanais.

## Nosso projeto

O CEPID NeuroMat, financiado pela FAPESP e sediado na USP, tem como objetivo integrar modelagem matemática e computacional com pesquisa básica e aplicada na fronteira da neurociência.

## Como se candidatar

Por favor envie um email para vagas-ti@numec.prp.usp.br com seu CV anexado - enviar no assunto: Vaga Back-End

## Labels

- Alocado
- Pleno
- Sênior

**Comment by carlosribas** [comment]
Vaga ainda disponível!

**Comment by carlosribas** [comment]
Vaga ainda disponível!

**Comment by izaguerreiro** [comment]
Como funciona a bolsa?

**Comment by carlosribas** [comment]
Oi @izaguerreiro 

É uma Bolsa de Treinamento Técnico da FAPESP. O período de vigência da bolsa é de no máximo 24 meses. O valor da bolsa TT-5 é de R$ 7.372,40 (não há desconto). Dê uma olhada neste link: http://www.fapesp.br/3098, ele mostra os níveis de bolsas TT. Para receber uma bolsa TT5 é preciso ter 5 anos de experiência com TI após a graduação OU ter feito doutorado.

Se ficou com alguma dúvida, por favor, me escreva.

**Comment by izaguerreiro** [comment]
Obrigada!
