### ISSUE TITLE
Sao Paulo - SP - Back-End Pleno- TruckPad

### ISSUE THREAD

**Issue by Babisoto** [backend-br/vagas#733]
# Informações importantes
Para que as vagas enviadas neste mural sejam categorizadas com as labels, as mesmas devem seguir as seguintes regras:
1. Todas as vagas enviadas neste mural devem estar de acordo com o Código De Conduta da nossa comunidade: https://github.com/androiddevbr/codigo-de-conduta. Vagas que violem este Código de Conduta serão automaticamente editadas e encerradas pela equipe de moderação.
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
4. As vagas enviadas neste mural serão automaticamente divulgadas no canal #job-alerts do Slack da nossa comunidade.
5. Remova este bloco inicial antes de divulgar a vaga.

## Descrição da vaga

Atuará na equipe de desenvolvimento focado em back-end, criando modelos, funcionalidades e interfaces de APIs;
Deverá focar no usuário e na melhoria contínua do código de maneira a desenvolver um produto com as melhores práticas de mercado;
Executar a manutenção fazendo eventuais correções necessárias, visando atender às necessidades dos usuários;
Desenvolver trabalhos de codificação, depuração e testes nas soluções a serem desenvolvidas;
Trabalhará juntamente com o time de front-end para buscar sempre as melhores soluções com foco no valor entregue aos usuários.

## Local
 Escritório São Paulo - Vila Olímpia

## Benefícios

Assistência médica;
Assistência odontológica;
Seguro de Vida em Grupo;
Vale-refeição;
Vale-transporte;
Reembolso para idiomas;
Auxílio creche;
Café da manhã e massagem;
Day Off de aniversário;
Programa de indicações internas;
Bicicletário e vestiári
- ...

## Requisitos

Ótimo relacionamento interpessoal; flexibilidade; resiliência; adaptabilidade;
Facilidade para trabalhar em equipe, utilizando SCRUM e code reviews;
Capacidade para entender o negócio e dar suporte para as equipes de arquitetura e produto na tomada de decisões;
Ser assertivo e orientado a resultados;
Construir código componentizável e reutilizável;
Otimizar as aplicações considerando performance e escalabilidade;
Conhecer frameworks JavaScript como Angular, ReactJS, Vue, Ember, Meteor ou outro é um ótimo diferencial.

## Contratação

CLT

## Nossa empresa

Entre para o time de talentos que está revolucionando o mundo da logística, dos transportes no Brasil e ajudando milhares de caminhoneiros  em todo o país. Venha fazer parte da startup que representará o Brasil na "Startup World Cup 2018”, a Copa do Mundo de Startups!

O TruckPad é o aplicativo de fretes com maior base de usuários do Brasil. Lançado em setembro de 2013, a partir da primeira startup nacional de tecnologia aplicada ao transporte rodoviário de cargas. O app já ultrapassou o marcante patamar de 500 mil instalações pelos motoristas de caminhão de todo o País.
## Como se candidatar

Por favor envie um email para barbara.soto@truckpad.com.br com seu CV anexado - enviar no assunto: Vaga Back-end

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
