### ISSUE TITLE
[Portugal] IOS/Android Mobile Developer

### ISSUE THREAD

**Issue by Margarida86** [backend-br/vagas#736]
Descrição da vaga:
Projectos em vários sectores de actividade, usando Tecnologias Mobile IOS/Android.

A nossa empresa:
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projectos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Local:

Portugal: Lisboa

Benefícios:
• Plano de saúde
• Visto de Trabalho para Portugal
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos Team Building
• Convívio mensal
• Oferta de aniversário
• Almoço grátis todas as sexta-feiras

Requisitos obrigatórios:
• Licenciatura ou Mestrado em Engenharia Informática ou similar;
• Mais de 2 anos de experiência em desenvolvimento Mobile;
• Bons conhecimentos de Swift/Android Studio;
• Domínio da língua Inglesa (conversação e escrita).

Contratação:
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Como se candidatar:
Envie o seu CV em Inglês para mtavares@aubay.com, com o assunto Mobile Developer.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
