### ISSUE TITLE
[São Paulo] Desenvolvedor Back End na PLOOMES

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#738]
### Sobre a empresa: PLOOMES

Somos uma empresa de tecnologia, cujo principal produto é uma ferramenta de vendas inovadora. Procuramos pessoas dispostas a crescer conosco e dividir o pote de ouro com muito trabalho duro. Será uma jornada de muito aprendizado e muitas recompensas. Estamos com espaço aberto para quem queira ser desafiado em uma posição em que o trabalho operacional deve ser realizado junto ao trabalho estratégico. Nossa missão é ser a referência número 1 em CRM para indústrias e distribuidoras do Brasil.

### Descrição: O que você irá fazer?

Desenvolvimento de API;
Documentação e testes automatizados;
Desenvolvimento de serviços complementares à API;
Desenvolvimento de automações para feature releases.

### As habilidades necessárias:

C#;
SQL Server.

### Diferenciais:

Conhecimento com git;
Conhecimento das ferramentas da Microsoft como SQL Server Management e Visual Studio.

### Benefícios:

Vale transporte;
Vale refeição de R$ 25/dia;
Plano de saúde Amil.

### Você gostará de trabalhar aqui se:

Trabalhar com sangue nos olhos;
Ser pró ativo e ter muita iniciativa;
For um bom líder;
Ser autodidata;
Buscar por possibilidade concreta de crescimento.

### Informações complementares:

O horário de trabalho é flexível;
Ambiente de trabalho descontraído;
No dress code;
Estamos localizados na região de Pinheiros;
Trabalhamos com metas e bônus trimestrais.

### Labels:

CLT
Alocado
Pleno/Junior

### Candidatar: http://bit.ly/ploomes_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
