### ISSUE TITLE
[São Paulo] Back-End Developer Java na 5A TALENTOS

### ISSUE THREAD

**Issue by gfreitas** [backend-br/vagas#74]
## Descrição da vaga
**ATIVIDADES:**
Atuará como desenvolvedor de equipes ágeis e lean, utilizando metodologia Scrum ou Kanban , com foco na constante evolução.
Participará de todas as fases do processo de engenharia de software, desde o entendimento de requisitos, passando por desenvolvimento e
testes, até a entrega em produção e resolução de eventuais problemas e defeitos.
Desenvolverá predominantemente na linguagem e na plataforma Java.
Avaliará, juntamente ao time, novas tecnologias e frameworks.
Participará ativamente de definições arquiteturais de software e de sistemas.
Elaborará documentação técnica, sendo ela textual ou diagramática, conforme a necessidade para o entendimento das funcionalidades
desenvolvidas.
Auxiliará na construção de conhecimento da equipe, fomentando e participando de discussões técnicas, pair programming e coding dojos, por
exemplo

## Local
Escritórios em São Paulo - (Pinheiros ou Centro)

## Benefícios
- Não Há.

## Diferenciais
- Horario Flexivel
- Video Games e etc

## Requisitos
**Obrigatórios:**
Desenvolvimento com Linguagem Java e frameworks de mercado para desenvolvimento de sistemas Web em toda Stack (frontend e backend).
Experiência no uso das tecnologias e dos padrões Java SE, Java EE, JMS, HTML, JavaScript, CSS e Spring (DI, MVC e Repositories).
Experiência no desenvolvimento de aplicações que atuam tanto como produtores quanto clientes de serviços RESTful ou SOAP.
Vivência em desenvolvimento de sistemas que rodam em Apache, Jetty e JBoss ou similares.
Conhecimento de automação de testes: testes unitários com JUnit, Mockito e Powermock (desejável), testes funcionais automatizados com
Selenium ou testes de integração com JUnit e HttpUnit.

**Desejáveis:**
Experiência em controle de versionamento com Git e SVN;
Sólidos conhecimentos em design patterns e paradigmas de programação, principalmente Orientação a Objetos e GoF.
Vivência com um ou mais métodos ágeis de desenvolvimento:
Conhecimentos em criar e fazer manutenção em componentes de arquitetura de microserviços.

**Diferenciais:**
- projetos de componentes de microserviços

## Contratação
PJ a combinar

## Nossa empresa
A 5A Talentos, atua no mercado de serviços de TI desde 2003 e estamos buscando pessoas com espirito inovador e que amam de tecnologia;

## Como se candidatar
Caso tenha interesse ou conhecidos para indicar, enviar e-mail com cv para g.freitas@5Atalentos.com.br com asunto: "[São Paulo] Back-End Developer Java na 5A TATENTOS"

## Labels
- PJ
- Alocado
- Júnior
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Vaga preenchida?

**Comment by gfreitas** [comment]
Oi Reginaldo,

Tivemos uma vaga fechada sim, muito obrigado.

Em seg, 23 de abr de 2018 14:37, Reginaldo Junior <notifications@github.com>
escreveu:
