### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Back-End .NET na Tstech

### ISSUE THREAD

**Issue by trabalheaqui-tstech** [backend-br/vagas#740]
#   Descrição da Empresa
Empresa de tecnologia em  integração de serviços e soluções de TI centrada no cliente, localizada na   Zona Sul de São Paulo.
 
# Atividades e Responsabilidades
- Atuar no desenvolvimento de novas funcionalidades para plataforma Web
- Discutir e fomentar a implementação de novas funcionalidades
- Em grupo, definir arquiteturas e contribuir com decisões técnicas
- Testar novas ferramentas e frameworks com o objetivo de melhoria de resultado para o projeto
- Participar na estimativa do time de desenvolvimento
- Em grupo, se comprometer com metas, prazos e objetivos

Atuar com desenvolvimento do Back-end no desenvolvimento de microserviços e APIs com testes automatizados, criação de componentes e bibliotecas próprias.
 
# Tecnologias:
- Angular 
- .NET 4.5
- Dot Net Core 2.0
- C# .NET
- Web API
- Javascript (Client/Server), Bootstrap, CSS
- MySQL;
- GIT
- REST
 
# Diferencial
- Node.JS
- Bancos de dados Não Relacional
 

# Conhecimento Desejável
- Arquitetura escalável e distribuída
- Docker

# Práticas
- Test Driven Development
- Pair programming
- Continuous Integration
- Design Patterns
 
# Contratação
- Valor à negociar, de acordo com a experiência e conhecimento.
- Início Imediato

# Local
Escritório localizado próximo a Estação de trem Santo Amaro.

# Como se candidatar
Achou essa oportunidade a sua cara? Então se candidata, estamos ansiosos para conhecer você!
https://hipsters.jobs/job/8563/analista-desenvolvedor-net-pleno/

## Labels
- .NET
- Alocado
- PJ
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
