### ISSUE TITLE
[São Paulo] Desenvolvedor Pleno/Sênior Ruby on Rails na One Choice Consulting

### ISSUE THREAD

**Issue by MatheusOneChoice** [backend-br/vagas#743]
Estamos procurando um Desenvolvedor Ruby on Rails (Pleno) 

Requisito:

3 anos de experiência com Ruby.

Diferencial:

Experiência com Java.

Local: Região da Vila Olímpia / Vila Nova conceição.

Regime de contratação: CLT + Benefícios.

Interessados por gentileza encaminhar o currículo para matheuspaiva@onechoice.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
