### ISSUE TITLE
[Lisboa-Portugal] Java Developer - Aubay

### ISSUE THREAD

**Issue by alexandregvale** [backend-br/vagas#744]
Job Description:
Projects in various sectors of activity, using various Java technologies, among others frameworks and IDE.

Our company:
Aubay is a company of French origin present in several countries in Europe.
As about 7000 people we develop projects in the most diverse technologies.
At the moment, we have several open positions for various positions.
Portugal: Lisbon and Porto

Benefits:
• Health plan;
• Work Visa for Portugal;
• Technical and behavioural training;
• Recruitment referral awards;
• Team Building Events;
• Monthly conviviality;
• Support for family reunification;
• Birthday offer;
• Free lunch every Friday.

Mandatory requirements:
• More than 3 years of Java development experience;
• Proficiency in English (conversation and writing).

Hiring:
Support in the whole process to obtain a work visa for Portugal, **paid flight** and another benefits, contact to know! 

How to apply:
Send your detailed CV to avale@aubay.com with the subject Aubay: JAVA_22

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.

**Comment by alexandregvale** [comment]
open
