### ISSUE TITLE
[São Paulo] Back-End Developer na [Matchbox Brasil]

### ISSUE THREAD

**Issue by daniloras** [backend-br/vagas#746]
### Sobre a Matchbox Brasil

A Matchbox nasceu para revolucionar a forma como empresas e jovens se conectam e se relacionam. 
Conheça: http://matchboxbrasil.com

## Habilidades

- PHP, Laravel/Lumen , SQL, Git

## O que nós buscamos: 

- Ajudar no desenho, documentação e desenvolvimento de sistemas
- Manutenção em sistemas legados
- Desenvolver e implementar novas funcionalidades
- Identificar e atuar na solução da performance do produto
- Colaborar com equipes de produto, front-end e arquitetura da informação para o desenvolvimento de novos projetos

## Principais responsabilidades

Obrigatórios:

- Experiência com desenvolvimento de produto
- Experiência com criação e consumo de API
- Experiências com bancos de dados MySQL
- Experiência com Git
- Desenvolvimento de automações para feature releases.
- Conhecimentos em otimização para performance
- Ferramentas para gestão de dependências
- Habilidade para documentação e testes automatizados;
- Habilidade de descobrir soluções performáticas para problemas complexos
- Habilidade de comunicação e de trabalho em time

## Desejáveis:

- Experiência com testes unitários
- Experiência com VueJS / ReactJS ou Angular 4
- Experiência com metodologias agéis

## Diferenciais:

- Noções de SEO
- Noções de UI e UX
- Noções de Front
- Noções de Javascript
- Noções de IaaS (AWS, Digital Ocean)

## Como se candidatar

Por favor envie um e-mail para produto@matchboxbrasil.com com seu CV / LinkedIn - com o assunto: Vaga Backend

## Labels

- Alocado
- CLT / PJ 
- Pleno

## Obrigado!

Agradecemos sua participação no teste. Boa sorte! :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
