### ISSUE TITLE
[São Paulo] Back-end Developer NodeJS na [Valle Sistemas]

### ISSUE THREAD

**Issue by LarissaAbreu** [backend-br/vagas#747]
## Descrição da vaga

Mais do que uma pessoa desenvolvedora que seja tecnicamente perfeita, estamos em busca de pessoas que verdadeiramente se divertem e são felizes aprendendo e compartilhando conhecimento ❤️ .

**Sua missão, caso deseje aceitá-la é:**

- Trabalhar no time que irá criar do zero nossos novos produtos (em geral ERP).
- Ser uma pessoa disposta a aprender muito.
- Ser responsável por implementar a camada da aplicação que conecta ao banco e entrega APIs para o Front-End, isso através das mais novas tecnologias possíveis (ES[7/8/9])!
- Entregar features/módulos sempre com qualidade máxima. Por isso trabalhamos com tudo muito bem documentado, testado, performático, escalável e manutenível... Basicamente você terá sempre a responsabilidade de criar um projeto que será fácil e seguro para qualquer pessoa.
- Trabalhar tanto em nosso produto interno (a nível de aplicação), quanto em diversos projetos Open Source que compõem nossos produtos.

## Requisitos

**Obs:** Temos vagas para Pleno e Sênior, sua colocação irá depender de quantos requisitos você atende e qual background você tem 😉

**Habilidades técnicas**

- Sólidos conhecimentos em Javascript.
- Sólidos conhecimentos em MongoDB.
- Entender como o Node.js funciona por baixo dos panos (event loop, etc...).
- Gostar de testes automatizados.
- Entender bem o funcionamento do HTTP.
- Criação de APIs REST.
- Controle de versão com GIT.

**Habilidades interpessoais**

- Vontade de aprender novas tecnologias e sempre se animar com as novidades.
- Saber trabalhar em equipe, compartilhar conhecimento e não ter vergonha de admitir que não sabe algo.
- Gostar de Open Source <3.
- Ser uma pessoa ativa na comunidade (seja como alguém que participa, organiza ou palestra).

## Desejável

**Habilidades técnicas**

- Boas práticas em geral (design patterns, performance,  etc…). 
- Conhecimentos de Infra.
- SQL Server.
- Estratégias de cache.
- Redis.
- Integração e entrega contínua com Jenkins.
- Interesse por Blockchain.

**Habilidades interpessoais**

- Interesse em entrar para core teams de projetos open source grandes (ou já fazer isso).
- Interesse em palestrar/organizar em eventos de tecnologia (ou já fazer isso).

## Diferencial

- Interesse em aprender sobre Front-End.

## Local

Pinheiros, São Paulo - SP | Em frente ao Shopping Eldorado

**Obs: A princípio apenas alocado.**

## Contratação

CLT ou PJ - salário compatível com o mercado

## Benefícios

**Básicos:**

- VR.
- VT.
- Convênio (caso queira).

**Sala dedicada apenas ao time com:**

- TV grande com chrome cast.
- Máquina de café instantâneo com refil à vontade.
- Máquina Dolce gusto (para quem não gosta muito de café).
- Puff's para programar relaxado.
- Livros legais para você poder ler no escritório ou levar pra casa.
- Frigobar.
- Microondas.
- E todo o resto que um escritório dev precisa ter.

**Apoiamos que você se desenvolva com:**

- Auxílio financeiro para participar de eventos.
- Compra de livros.
- Patrocínio para fazer cursos.
- Palestras técnicas internas.
- Seções de pair programing.
- Plano de carreira.

## Um pouco sobre nossa cultura

**Apoio à comunidade**

Temos interesse em participar da comunidade de desenvolvimento sediando meetups, 
patrocinando conferências ou ajudando no que for possível.

**Roupas no local de trabalho**

Apenas use.

**Horários**

Horário flexível, apenas sendo necessário estar presente em possíveis reuniões que serão avisadas com antecedência.

**Trabalho remoto**

Possibilidade de ficar remoto quando necessário e posteriormente podemos ter abertura para ficar dias fixos da semana como home office. 

## Como se candidatar

Envie um e-mail com o seu Github (ou o que você tiver de legal para mandar 😄 ) para **dev@vallesistemas.com.br** com o assunto **Vaga back-end Node** e, se quiser, dá um salve aqui na issue ❤️ 

## Labels
- Alocado
- Pleno
- Sênior
- PJ
- CLT

**Comment by guilhermeoa07** [comment]
Super curtir, pena que não tem vaga para Júnior :weary:

**Comment by lucasmonstrox** [comment]
Salveeee!!!
