### ISSUE TITLE
[Campinas - SP] C++ Mobile Security Developer

### ISSUE THREAD

**Issue by endrilcsilva** [backend-br/vagas#748]
## Sobre a Daitan:
A Daitan foi criada há 14 anos com o objetivo de atender ao mercado internacional de software. Acostumada a criar soluções escaláveis para Telecom (que era a expertise dos fundadores na época) e possuindo acesso a uma mão-de-obra muito qualificada no Brasil, a Daitan logo identificou oportunidade de trabalhar com startups, especialmente no Vale do Silício. Ao trabalhar com startups, a Daitan aprendeu a ser mais ágil - hoje as grandes empresas de telecom e de outros setores estão recorrendo à Daitan para ganhar essa agilidade, por exemplo com DevOps, que temos aplicado há vários anos lá no Vale. Tem sido muito interessante esse modelo de aprender de um lado e aplicar do outro.
Várias evidências indicam que esse modelo está funcionando bem. Estamos em um ritmo acelerado de crescimento há anos – só ano passado, contratamos cerca de 200 pessoas e estamos ampliando o ritmo de crescimento em 2018.
Hoje em dia os clientes já buscam a Daitan como um consultor especializado. Isso porque com mais de 500 projetos e mais de 300 tecnologias, tools e metodologias em uso somente nos projetos atuais (e que foram escolhidos porque atendiam melhor a necessidade de cada cliente, caso a caso), a empresa pode oferecer um conhecimento coletivo que poucas empresas que estão fazendo seus próprios produtos podem acumular. Trabalhar na Daitan é isso: atuar em projetos desafiadores, com tecnologia de ponta, com clientes internacionais, aprendendo sempre e ensinando sempre. E tudo isso em um ambiente altamente descontraído, acolhedor e divertido: reconhecido pelo Great Place to Work como uma das melhores empresas em TI no Brasil há diversos anos seguidos.
Você pode encontrar informações mais detalhadas no site www.daitan.com

### Activities
Work in a dynamic and very autonomous team to provide security solutions for mobile applications including:
- Implementing security policies that are injected in blackboxed mobile solutions;
- Following up on security updates and vulnerabilities and how they would affect the security policies;
- Implement secure data transport mechanisms between mobile solutions and corporative cloud servers;
- Implementing new security policies to match mobile OS evolution and necessities;
- Investigate security injection issues and implement fixes in the solution accordingly.

### Essential Skills
- Experience in software security techniques;
- Ethical Hacker skills;
- Experience with server technologies and cloud services;
- Strong network skills (tcp/ip, tunnels, SSL);
- Strong C/C++ skills;
- Strong Linux skills.

### Highly Desirable Skills
- Curious and investigative mindset;
- English for professional communication;
- Experience in Android or iOS operating systems;
- Experience in Java or Objective-C.

### Additional Skills
- Experience in agile projects;
- Experience in Javascript.

## Posição
São duas posições com o mesmo perfil, uma Júnior e uma Sênior.

## Tipo de contratação
CLT Full, presencial.

## Como aplicar
Envie e-mail para talent@daitan.com com o assunto: Vaga Github: C++ Mobile Security Developer

## Labels
- Campinas
- Júnior
- Sênior
- Presencial
- CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
