### ISSUE TITLE
[São Paulo - SP] Full Stack Developer @ Doutor Já

### ISSUE THREAD

**Issue by Lucianoonaicul** [backend-br/vagas#749]
## Descrição da vaga
Buscamos um programador para integrar nosso time de devs e colaborar diariamente na implementação de novas soluções e melhorias de nossos projetos que dão suporte a todas as nossas metas estratégicas. 

## Local
Brooklin, São Paulo - SP.

## Requisitos
- AWS Amazon
- Git
- MySQL
- Api REST
- Node.js
- Angular

## Contratação
PJ a combinar

## Nossa empresa
A [Doutor Já](https://www.doutorja.com.br) é uma startup (Health Tech) que tem como missão facilitar o acesso à saúde de qualidade a população através  de soluções inovadoras.

## Como se candidatar
Envie o currículo para "querotrabalhar@doutorja.com.br" com assunto "Full Stack Developer".

## Labels
- Alocado
- PJ
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
