### ISSUE TITLE
[São Paulo / Remoto] Full Stack NodeJS/Angular2+/TypeScript na N2B

### ISSUE THREAD

**Issue by samuelhei** [backend-br/vagas#75]
# Full Stack NodeJS/Angular2+/TypeScript

[N2B](https://n2bbrasil.com) é uma healthtech de destaque no mercado contratando profissional de alta performance, apaixonado por desafios.

## Obrigatórios:

- Javascript moderno (ES6).
- TypeScript 2+
- NodeJS.
- Angular2+ (Estamos usando o 5! YAY!)
- Conhecimentos em NoSQL
- Inglês básico (p/ escrita de commits/documentação)

## Diferenciais:

Projetos OpenSource, talks, artigos ou tutoriais publicados

## Desejáveis:

Utilizamos todas essas tecnologias, mesmo que não as domine podemos aprender juntos!

- IONIC (Especialmente IOS)
- Elasticsearch + Kibana.
- Firebase, Firestore, Google Cloud Functions.
- Git/Git Flow
- Mocha + Chai
- TDD/BDD/DDD
- AWS

## Para se candidatar:

Preencha o seguinte form e pronto! [https://goo.gl/wPZY6a](https://goo.gl/wPZY6a)

**Comment by onhernandes** [comment]
@samuelhei pode colocar no começo do título, entre colchetes, o estado de onde a vaga é? Tipo, [São Paulo] Full Stack NodeJS/Angular2+/TypeScript na N2B

Valeu :D

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
