### ISSUE TITLE
[REMOTO] Desenvolvedor Back End na UPNID

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#751]
### Sobre a empresa: Upnid

Nós somos a Upnid. Nós construímos ferramentas que facilitam o processo de vendas online. Nosso principal produto é o checkout, uma página de pagamento que permite, em menos de 5 minutos, que nossos clientes consigam vender através da internet. Nossa missão é simplificar a maneira como pequenos e médios empreendedores recebem pagamentos através da internet.

### Descrição: O que você irá fazer?

Você será responsável por desenvolver a integração via API e criar testes automatizados para garantir a confiabilidade dos novos recursos

### Nossos diferenciais:

Liberdade. Na Upnid você escolhe onde e quando trabalhar. Nosso time é remoto e você tem liberdade para escolher seus horários.
Desenvolvimento de novas habilidades. Oferecemos uma ajuda mensal de R$ 100,00 para compra de livros, cursos e qualquer tipo de material educativo. (Também investimos em cursos mais caros - iremos analisar a viabilidade primeiro.)
Alimentação e Transporte. Cuidamos de suas despesas de alimentação e transporte nos dias em que você optar por trabalhar do nosso escritório.
Crescimento. Você estará fazendo parte de um time jovem e dinâmico, em um projeto em pleno crescimento. Participará ativamente em decisões estratégicas.

### O que você precisa saber?

Bancos de dados MySQL e MongoDB
Conhecimento de API RestFull﻿
Experiência com testes automatizados
Conhecimento em JavaScript ou Node.Js

### Como você precisa ser?

Você não sabe tudo, mas aprende rápido. Você é faminto pelo novo, está constantemente estudando e se qualificando. Se tem um desafio que não sabe como resolver, você estuda e coloca em prática o que aprendeu.
Você não faz trabalho meia boca. Se você tem um desafio, você vai até o fim. Sempre se preocupando com a qualidade, sem deixar que isso atrapalhe no cumprimento dos prazos.
Você é curioso. Está sempre questionando e buscando maneiras de melhorar o seu trabalho.
Você é motivado e independente. Você toma iniciativa para garantir que tenha todos os recursos necessários para desempenhar bem o seu trabalho e é proativo em pedir ajuda quando necessário.

### Labels:

PJ
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
