### ISSUE TITLE
[Remoto] Back-end Developer na @Caju Benefícios

### ISSUE THREAD

**Issue by allangrds** [backend-br/vagas#7514]
## Nossa empresa

Somos uma empresa brasileira de tecnologia, que veio para facilitar a vida das empresas e funcionários, transformando a maneira como as pessoas enxergam benefícios corporativos em uma experiência única.

Começamos a nossa história em junho de 2019, e desde o início contamos com as pessoas mais talentosas e curiosas do mercado, para construir a Caju que tanto acreditamos.

## Sobre o desafio

Estamos divididos em squads, então para as novas pessoas que entrarão para a equipe estamos abertos à todos os níveis de senioridade: se está migrando e começando a carreira em tecnologia, aprendizado é o que não vai faltar! Se já tem experiência e quer fazer parte de um produto de alto impacto, aqui é o seu lugar!

São muito bem-vindas candidaturas de pessoas negras, mulheres, indígenas, LGBTQIA+, ou outros grupos minorizados. Inscreva-se e conheça mais sobre nosso time! 🧡

## Local

Remoto

### Soft skills

- Comprometimento em resolver as dores do cliente e pensar na experiência do usuário;
- Buscar aprender todo dia;
- Buscar soluções de forma autônoma para os problemas técnicos encontrados;
- Saber trabalhar em equipe;
- Assumir responsabilidade pelo código produzido.

### Conhecimentos técnicos que valorizamos

- Fundamentos de ciência de computação;
- Práticas de programação funcional (experiência com alguma linguagem funcional é um bônus - Scala, Clojure, Elixir, Haskell, etc);
- Experiência em desenvolvimento de sistemas web;
- Conhecimento de padrões de arquitetura;
- Experiência com testes;
- Experiência com desenvolvimento e consumo de APIs (GraphQL ou REST);
- Conhecimento dos diferentes tipos de bancos de dados e suas características;
- Experiência com mensageria assíncrona;
- Uso de ferramentas de controle de versão (Git).

## Benefícios

- Salário competitivo;
- Cartão Caju, com liberdade para usar seus benefícios como você quiser (Refeição, Alimentação, Mobilidade, Saúde, Cultura e Educação);
- Plano de Saúde;
- Anywhere office, para você trabalhar de onde quiser;
- Auxílio Home Office, para ajudar na adaptação;
- Zenklub, com consultas onlines com terapeutas e coaches para cuidar da sua saúde mental;
- Revelo Up, para investir nos seus estudos;
- Muitas possibilidade de crescimento - temos muito a crescer e esperamos fortemente que você nos ajude com isso!

## Como se candidatar

Se candidate pelo Gupy através do link https://caju.gupy.io/jobs/845688?jobBoardSource=gupy_public_page

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by jeovazero** [comment]
Essa pode pra Júnior mesmo?

**Comment by allangrds** [comment]
Pode sim @jeovazero
