### ISSUE TITLE
[São Paulo - SP] Node.js Developer

### ISSUE THREAD

**Issue by VizirAdmin** [backend-br/vagas#752]
## Descrição da vaga

Estamos com oportunidades para trabalhar com Node.js na [Vizir](http://vizir.com.br).

Para conhecer mais sobre a vaga e um pouco da Vizir (http://vizir.com.br/2017/04/26634697957-2/)

Quem tiver interessado, só preencher o seguinte form: https://bit.ly/2uEH3Ze

## Local

Na rua do Arouche n23 cj 61, em frente ao metrô República.

## Benefícios

- Ticket refeição: R$ 30,00 por dia (R$ 630,00 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou aonde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

## Requisitos

- Conhecimento de JavaScript, boa lógica e orientação a objetos
- Estar a fim de aprender
- Comprometido em entregar projetos com qualidade

**Obrigatórios:**
- Curtir programar
- Experiência com Node.js

**Desejáveis:**

- Experiência com práticas ágeis
- Experiência com AWS
- Experiência com microservices

## Contratação

CLT

## Como se candidatar

Preencha o seguinte formulário: https://bit.ly/2uEH3Ze

## Labels

- Presencial
- CLT
- Júnior
- Pleno

**Comment by guilhermeoa07** [comment]
entrevista pode ser online?

**Comment by VizirAdmin** [comment]
@guilhermeoa07 pode sim

**Comment by Assisneto** [comment]
não teria vaga para remoto? mesmo que perdendo alguns benefícios.

Em sáb, 26 de jan de 2019 às 10:50, Vizir <notifications@github.com>
escreveu:

**Comment by VizirAdmin** [comment]
@Assisneto para remoto estamos com outro processo seletivo rolando, mas pode mandar ainda https://github.com/backend-br/vagas/issues/707

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
