### ISSUE TITLE
[São Paulo] Java Developer na [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [backend-br/vagas#754]
O que esperamos de você?
Que faça análise e desenvolvimento de sistemas (foco em backend) utilizando Java (web). 
Tenha ensino superior completo em cursos de TI;
Vivência em programação com Java Web (J2EE); 
Conhecimento em Banco de Dados Oracle;
Desejável: atuação anterior com Banco de Dados NoSQL (MongoDB, Cassandra, DynamoDB) e desenvolvimento em linguagem Python;
Diferencial: conhecimento do mercado de Seguros. 

O que você vai encontrar aqui:
Muito trabalho e...
Local de fácil acesso via estação Morumbi da CPTM ou estação Brooklin do metrô (zona Sul de SP);
Contratação CLT Full;
Benefícios (Vale Refeição, Vale transporte, Assistências médica e odonto (sem desconto), PLR;
Day Off no seu aniversário, Casual Dress Code;
Campeonatos (futebol e Pocker, por exemplo);
Festas (café da manhã às sextas e comemoração de aniversariantes do mês); 
Comitê de treinamentos (login DevMedia).

Se identificou com a Confitec?
Então envie seu CV com assunto “Java” e pretensão salarial (CLT) para curriculos@confitec.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
