### ISSUE TITLE
[Remoto] Back-end Developer @ Devellop Labs

### ISSUE THREAD

**Issue by obrunoalbano** [backend-br/vagas#7545]
## Nossa empresa

A Devellop Labs é uma empresa que oferece outsourcing de T.I para empresas de desenvolvimento e agências digitais.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento web.

## Descrição da vaga

A Devellop Labs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Back-End, com clientes e projetos. Essa experiência pode ser através de projetos freelas ou trabalho empresarial.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Local

Exemplo: Remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
• Utilizar conceitos do GitHub, branching, issues, pull-requests, etc;
• Conhecimento em algumas destas linguagens, PHP, Node js, Python, Go, .NET, Ruby, Java;
• Experiência com algum banco de dados relacional (PostgreSQL, MySQL), ORM's, e bancos de dados não relacionais;
• Conhecimento em TDD, Clean Code e Design Patterns;

**Desejáveis:**
• Noções de Bash script;
• Noções de virtualização e containers (Docker);
• Conhecimento em aplicações orientadas a componentes;
• Experiência com serviços AWS (EC2, S3);
• Ser familiarizado com o terminal e aplicações em linha de comando.
• Conhecimento em Cloud, ferramentas de análise de código, automação, e integração contínua;
• Capacidade de criar Micro-serviços escalonáveis horizontalmente e arquitetura hexagonal.

## Benefícios

- Trabalhe conforme sua capacidade, ganhe por hora trabalhada!

## Contratação

PJ a combinar

## Como se candidatar

Pelo link: https://devellop.com.br/trabalhe-conosco ou envie um email para rh@devellop.com.br com seu CV anexado - enviar no assunto: Vaga Back-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by ribeirosaimon** [comment]
Queria muito!

**Comment by obrunoalbano** [comment]
aberta para novos devs
