### ISSUE TITLE
[São Paulo] Back-End Developer na F.biz

### ISSUE THREAD

**Issue by mcarneiro** [backend-br/vagas#755]
## Descrição da Vaga

Procuramos um(a) desenvolvedor(a) Back-end apaixonado(a) por pesquisa e tecnologia e seja capaz de transitar entre diversas tecnologias e linguagens de programação. Que enxergue o valor dos detalhes, independente do projeto.

Formamos um time multi-disciplinar composto por UX, Front e Back-end que acreditam no melhor que cada tecnologia tem a oferecer. Não só viabilizamos como buscamos ter papel ativo e decisivo na concepção criativa dos projetos.

A F.biz é uma agência com mais de 18 anos e DNA 100% digital. Trabalhamos com grandes clientes como Unilever, Jeep, Honda, Tok&Stok, Votorantim, Rico, Comgás, entre outras. **Todas as contratações são CLT com benefícios** de transporte, alimentação, refeição e um belo plano de saúde com cobertura odontológica. Temos plano de carreira de longo prazo e trabalhamos com processos flexíveis que nos ajudam a organizar o dia-a-dia com mais eficiência e colaboração. 

### Como diferenciamos o Pleno do Sênior? 
**Pleno:** É independente e tem capacidade de dividir e priorizar suas próprias tarefas. Tem conhecimento técnico suficiente para tocar todas as etapas de um projeto pequeno sozinho (ex.: landing pages, sites institucionais focados em conteúdo). Maturidade para priorizar, reportar problemas e pedir ajuda quando necessário.

**Sênior:** Conhecimento técnico avançado, solucionador(a) de problemas, com capacidade liderar um projeto médio ou grande com outros perfis do time (ex.: e-commerce, grandes portais, sites experimentais, etc.). Maturidade para dar suporte, estimar e garantir a qualidade de entrega do trabalho dos pares.

### Como funciona nosso processo de contratação?
**1ª etapa - Triagem:** Aplique para a vaga, preencha o formulário e aguarde nosso contato.
**2ª etapa - Avaliação:** Envio de análise técnica de um projeto que tenha criado e se orgulhado.
**3ª etapa - Entrevista:** Presencial ou Online;

Além dos conhecimentos técnicos e trabalhos, queremos saber *quem* é você pois acreditamos que cada nova pessoa adiciona algo único ao time.

Se você acha que tem o perfil para a vaga, venha tomar um café com a gente!

## Local
[Rua João Moura, 1144, Pinheiros, São Paulo](https://www.google.com/maps/place/F.biz/@-23.5558365,-46.6827259,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5758b35c5cdf:0x9a4c0668291f8bcb!8m2!3d-23.5558365!4d-46.6805372)

## Benefícios

* Plano de saúde.
* Plano odontológico.
* VR/VA.
* Auxílio Babá/Creche para pais e mães.

**Intangíveis:**
* Gympass.
* Sistema de convênios com restaurantes e serviços da região.
* Transfer Metrô - F.biz e F.biz - Metrô.
* Espaço dedicado para contratação de manicure e massagista.
* Prédio próprio, espaço amplo e arborizado com bastante área comum.

## Requisitos
* PHP (5.6 e 7) e .NET são as linguagens mais utilizadas em nossos projetos.
* Desenvolvimento de APIs;
* Modelagem e manutenção em Banco de Dados relacional;
* Controle de versão (GIT);
* Continuous Integration (Jenkins, TeamCity, Bitbucket Pipelines);
* Princípios SOLID;
* Docker;

### Diferenciais
* Iniciativa, criatividade, colaboração;
* Organização e comunicação ativa;
* Inglês (escrita e conversação);
* Experiência com Wordpress, Drupal e/ou Umbraco;
* Configuração de serviços Cloud (AWS, Google Cloud, etc.);
* Estar preparado(a) para trabalhar com qualquer tecnologia;
* Test-driven development (TDD);
* Automatização de processos;
* Projetos pessoais;
* Interesse por IOT;

## Como se candidatar
Para aplicar, [entre por esse link e preencha o formulário](https://jobs.kenoby.com/fbiz/job/desenvolvedora-back-end-pleno-senior/5c39e75c292ddf2fb1cc6499?utm_source=github).

## Labels
* Alocado
* CLT
* Pleno
* Sênior

**Comment by lucasperrotta** [comment]
Mal espero pela vaga de jr

**Comment by mcarneiro** [comment]
Acabei esquecendo de avisar que esta vaga foi fechada. Obrigado!
