### ISSUE TITLE
[SÃO PAULO] - DESENVOLVEDOR JAVA PLENO E SENIOR- RESOURCEIT

### ISSUE THREAD

**Issue by POLLEZI** [backend-br/vagas#757]
## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.  

## Descrição da vaga		
-        Atuação com arquitetura de sistemas (Rest, SOAP, Micro serviços)
-        Conhecimento de processo de integração continua
-        Conhecimento e atuação com metodologias ágeis (TDD, BDD, DDD e Scrum)
-        Conhecimento em desenvolvimento de portais e mobile
-        Experiência com modelagem e implementação de barramento de serviços
-        Linguagens: Java (6, 7 e 8), IIB (IBM Integration Bus)
-        Banco de Dados: Oracle ou Sybase
-        Servidor de Aplicação: JBOSS, Tomcat, WebSphere;
-        Frameworks de Backend: JPA (Hibernate), EJB e Spring;  .

## Posição
DESENVOLVEDOR JAVA PLENO E SENIOR

## Tipo de contratação
PRESENCIAL - CLT FULL

## Requisitos
•	Formação Necessária: Curso superior nas áreas de TI ou correlatadas

## Benefícios
VR, VT, Convenio Médico, Convenio Odontológico, Auxilio Creche, Convenio Farmácia, Seguro de Vida

## Como aplicar
 Envie seu cv com pretensão salarial para adriana.pereira@resourceit.com ou indique um amigo!!!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
