### ISSUE TITLE
[São Paulo] Engenheiro de Software na Red Ventures

### ISSUE THREAD

**Issue by rv-lmai** [backend-br/vagas#758]
## Descrição da Vaga
A **Red Ventures** é uma empresa de tecnologia e, por isso, os engenheiros de software são o nosso coração e o nosso cérebro: arquitetando a infraestrutura em cloud, modelando bancos de dados e desenvolvendo APIs e serviços, seu papel em nosso time será o de criar aplicações robustas, distribuídas, seguras e de grande escala. Imerso em um ambiente dinâmico e ágil, você se verá diante de grandes desafios como desbravar novas ferramentas e tecnologias, se adaptar rapidamente a um novo projeto e interagir em um time diverso e interdisciplinar.

## Perfil do Candidato
Queremos sempre inovar e, por isso, buscamos candidatos das áreas de Engenharia de Computação, Ciência da Computação ou áreas relacionadas que sejam pró-ativos, motivados, apaixonados pelo que fazem e que busquem constantemente adquirir novos conhecimentos e repassá-los aos seus colegas de trabalho. Acreditamos que candidatos com diversos skill sets podem contribuir ativamente para formar a cultura da empresa e proporcionar um ambiente cada vez melhor para se trabalhar e, por isso, valorizamos características como curiosidade, entusiasmo, espírito de equipe e sede de conhecimento, tudo isso unido ao desejo de dar o seu melhor e entregar o melhor trabalho possível.

## Requisitos
- Pertencer às areas de Engenharia de Computação, Ciência da Computação ou relacionadas
- Inglês nível intermediário (ou superior)
- Morar em São Paulo ou ter a possibilidade de se mudar **(não contratamos funcionários remotos)**

## Diferenciais
- Conhecimentos em Go (Golang)
- Prática com AWS, Google Cloud Platform, Azure, etc
- Experiência com testes unitários/integração ou TDD
- Experiência com modelagem de bancos de dados relacionais e SQL

## Sobre a Red Ventures
A Red Ventures é uma empresa focada em otimizar todo o funil de marketing de nossos parceiros - desde a geração de demanda até o fechamento da venda. Nossa experiência abrange várias indústrias, incluindo serviços financeiros e seguros. Nossa cultura é baseada em liberdade: você será livre para executar, testar, aprender e terá a responsabilidade de se auto gerenciar num ambiente colaborativo e ágil, se desafiando e crescendo dia a dia.

### E o que mais?
- Plano de carreira estruturado com sessões de feedback recorrentes
- Bônus financeiro anual por performance
- Plano de saúde e dentário
- Auxílio Uber mensal
- Ambiente de trabalho informal, transparente e que preza pela colaboração e respeito às pessoas de diversas origens, orientações e culturas
- Incentivo educação: valor semestral pra você utilizar em cursos, certificações, eventos etc.
- Incentivo à prática de atividade física: parceria com o Gympass e prática de esportes coletivos
- Red Adventure: de tempos em tempos, reunimos todo o time em uma atividade fora do escritório (kart, arco e flecha, Escape 60 

**LINK:** https://goo.gl/JhpwuL

**Labels**
- CLT
- Golang
- AWS
- Junior
- Pleno
- Senior

**Comment by brazica** [comment]
contato?

**Comment by rv-lmai** [comment]
> contato?

@brazica Opa, incluí o link ali na descrição. Foi mal.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
