### ISSUE TITLE
[São Paulo/SP] PHP Developer na PayGo

### ISSUE THREAD

**Issue by adrianolaselva** [backend-br/vagas#759]
## Desenvolvedor PHP Sênior

Você fará parte do time de Tecnologia, que é a área responsável por desenvolver, monitorar, melhorar e criar soluções referentes aos nossos produtos e sistemas.

Como Desenvolvedor PHP você trabalhará na área responsável pelo desenvolvimento e manutenção do softwares de gestão interna da empresa.

## Local

Escritório, São Paulo/SP - Rua Augusta

## Benefícios

- Vale Refeição
- Vale Alimentação
- Programa de Participação de Lucros
- Auxílio Transporte
- Seguro de Vida
- Assistência Médica
- Assistência Odontológica
- Parceria com Gympass
- Parceria CGP (Programa de Apoio ao Colaborador)

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com PHP >= 5.6
- PHPUnit
- PSR’s
- 12 fatores
- Versionamento Git
- Conhecimentos em Linux distribuições ubuntu e centos
- Docker
- Laravel (a partir da versão 5.4)
- Modelagem em banco de dados relacional
- Javascript, JQuery, bootstrap
- Serviços RESTFUL e SOAP para criação e integração
- Criação e gerenciamento de dependências via composer
- Design de API's REST

**Desejáveis:**
- Conhecimento e experiência em métodos ágeis, principalmente Scrum e Kanban
- Silex
- Codeigniter
- Zend framework
- Supervisor para controle de processos
- Conhecimento em banco de dados

**Diferenciais:**
- Stack ELK (Elasticsearch), kibana, logstash, filebit
- Conhecimento em serviços em cloud AWS S3, SQS, EC2
- Conhecimento em algum framework front-end
- Reactjs
- DevOps
- CI/CD
- Grafana
- Travis

## Contratação

- CLT

## Nossa empresa

Fazemos parte da C6 Participações, mesmo grupo do C6 Bank, e somos uma das principais empresas de captura de cartões do mercado brasileiro. Nossa plataforma de pagamentos pode atender qualquer tipo de negócio: das soluções mais simples às mais customizadas.

## Como se candidatar

Por favor envie um email para a.moreira@paygo.com.br com seu CV anexado - enviar no assunto: Vaga PHP Sênior

## Labels

- Alocado
- Presencial
- Sênior
- CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
