### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Back End na SCN BRASIL

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#760]
### Sobre a empresa: SCN Brasil

A SCN Distribuidor Autorizado Serasa Experian conta com sua rede com profissionais treinados e qualificados com experiência de mais de dez anos de serviços no segmento de análise de crédito, com qualidade e competência em seus serviços, oferecendo aos seus clientes informações precisas e atualizadas auxiliando assim todo processo de vendas e de tomadas de decisões de seus clientes.

### Descrição: Ocupações do cargo

Programar, codificar e testar projetos;
Identificar possíveis melhorias no sistema existente;
Acompanhar e monitorar o sistema;
Trabalhar em equipe e de forma proativa.

### Conhecimentos obrigatórios:

PHP;
Ferramentas de automatização
Diferenciais:
.NET
MySQL/PostgreSQL
Laravel
WebService
Conhecimentos de Front-End

### Benefícios:

Vale Transporte
Vale Refeição
Plano de Saúde

### Informações complementares

Contratação CLT;
Local: Bairro Carlos Prates. Belo Horizonte/Minas Gerais.

### Tipo de contrato:

Emprego

### Nível de experiência:

Pleno 

### Candidatar: http://bit.ly/scn_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
