### ISSUE TITLE
[Curitiba] Back-End Developer na [JUNO]

### ISSUE THREAD

**Issue by thamiramachado** [backend-br/vagas#761]
# Vagas para **Pleno** e **Sênior**

# **As responsabilidades do job são:**
• Desenvolvimento de telas de fácil entendimento e usabilidade do cliente;
• Otimizar fluxos, processos e rotinas;
• Raciocínio lógico e rapidez no teclado;
• Atenção a detalhes.

# **Se você é do tipo que:**
• Sonha Grande!
• É proativo e coopera de forma genuína;
• Acredita que só é possível alcançar o sucesso trabalhando duro;
• Tem ensino superior completo em áreas relacionadas a TI;
• Tem vasta experiência em projetos de linguagem Java;
• Já teve contato com metodologia TDD e/ou desenvolvimento de teste unitário e automatizado;
• Conhece JUNIT, Spring, Hibernate;
• Possui capacidade de planejamento, desenvolvimento, testes e em aprimorar grandes projetos;
• Sabe gerenciar seu tempo e prazos de entregas;
• Buscar sempre aprender coisas novas;
• Sabe se comunicar de forma assertiva.

# **Exigência técnica para o perfil pleno:**
**Java** = Avançado
**Spring** = Intermediário
**JUNIT** = Básico
**Hibernate** = Intermediário
**TDD** = Básico 

# **Exigência técnica para o perfil sênior:**
**Java** = Avançado
**Spring** = Avançado
**JUNIT** = Intermediário
**Hibernate** = Avançado
**TDD** = Básico

# **Você ganha pontos ~extras se:**
• Já tiver utilizado React;
• Conhecer ou já ter atuado com o mercado financeiro. 

#  **Modelo de contratação**:
• Celetista e presencial;
• Horário semi flexível - 40h semanais.

# **Benefícios**:
• VR (R$ 19,00/dia);
• Plano de Saúde Unimed;
• Plano Odontológico Bradesco;
• Clube Gazeta do Povo;
• Plano de Academia;
• Desconto FGV, Uninter, Aldeia, FAE;
• Escritório com frutas liberadas e pet friendly;
• Happy hour todo mês;

# **Candidaturas**:
Envie seu currículo para vagas@juno.com.br com o assunto Back-End + Nível

# **Saiba mais:**
• [O que é a Juno](https://juno.com.br)
• [Quem somos](https://juno.com.br/quem-somos.html)
• [Veja o que a galera acha de trabalhar aqui](https://www.lovemondays.com.br/trabalhar-na-juno/avaliacoes)
• [Leia o que a impressa já falou da gente](https://www.gazetadopovo.com.br/blogs/parana-sa/2019/01/16/04-pequenas-empresas-do-parana-estao-na-lista-das-mais-amadas-do-love-mondays/)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
