### ISSUE TITLE
[SÃO PAULO] Desenvolvedor Ruby on Rails [Zaitt]

### ISSUE THREAD

**Issue by RobertoPassos** [backend-br/vagas#762]
Área de atuação
Desenvolvedor Ruby on Rails

Principais Atividades
Você irá desenvolver projetos de manutenção e evolução de sistemas utilizando Ruby on Rails, utilizando metodologias ágeis. Também irá integrar e/ou adequar outros sistemas ou serviços. 

Requisitos
Domínio em Ruby, Ruby on Rails, Sidekiq
Bons conhecimentos em PostgreSQL 
Conhecimento em Redis
Conhecimento em REST API
Conhecimento em HTML, CSS, Jquery e Javascript

Skills desejados
Experiência com gateways de pagamento
Experiência em OneSignal/Firebase
Experiência com serviços AWS
Experiência com OpenCV

Localização
Itaim Bibi, São Paulo/SP

Contato
Roberto Passos Bonacossa Rocha
contato@zaitt.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
