### ISSUE TITLE
[Remoto] PHP Developer Pleno @DOTLIB

### ISSUE THREAD

**Issue by vlamirsanto** [backend-br/vagas#7631]
## Nossa empresa

A Dot.Lib distribui conteúdo online científico e acadêmico a centenas de instituições espalhadas pela América Latina. Temos como parceiras algumas das principais editoras científicas nacionais e internacionais. Além de prover conteúdo, criamos soluções que atendem às necessidades de nossos clientes e editoras.

## Descrição da vaga

Buscamos um profissional que seja apaixonado por desenvolvimento, inovação e novas tecnologias, para integrar nosso time em projetos baseados em NodeJS, PHP e React JS/Native.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Mínimo 1 ano de experiência em desenvolvimento de sites e sistemas em Laravel;
- Desenvolvimento de APIs RESTful;
- Conhecimentos em SQL e NoSQL;
- Conhecimentos em Docker;
- TDD
- Controle de versões (GIT).

**Desejáveis:**
- Conhecimentos em Node.JS
- Conhecimentos em Elasticsearch
- Conhecimentos em serviços AWS
- Experiência em metodologias ágeis (Scrum/Kanban)

## Benefícios

- Salário compatível com o mercado
- Plano de saúde
- Plano odontológico
- Vale Refeição ou Vale Alimentação
- Emendas em feriados nacionais
- Equipe unida, divertida e apaixonada por hambúrgueres
- Cursos online
- TECH DAY - Evento trimestral de palestras sobre tecnologia;
- Friday's Talk - Bate papo descontraído sobre tecnologia, apresentação de POCs de estudos, etc;

## Contratação

Regime: CLT
Salário inicial: R$ 5.500,00

## Como se candidatar

O processo contará com 4 fases:

- Seleção do candidato através do currículo e informações adicionais enviadas pelo formulário: https://forms.gle/YKMoZVMe28qgX7qH8.
- Resolução de teste técnico: https://github.com/dotlib/teste-desenvolvedor-php.
- Entrevista via call.
- Contratação.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by we2l** [comment]
Opa amigo, há somente vagas para pleno ou também há vagas para Jr?

**Comment by vlamirsanto** [comment]
@we2l Infelizmente não, somente para pleno.
