### ISSUE TITLE
[Remoto] Python Developer na Instruct

### ISSUE THREAD

**Issue by iassia** [backend-br/vagas#764]
Estamos buscando profissional que consiga trabalhar em um time multidisciplinar, que tenha sólidos conhecimentos de programação e bons fundamentos de sistemas operacionais e redes.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

Precisamos que você conheça muito bem Python em ambiente Linux.

É fundamental saber aprender novas tecnologias e que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem vindas.

Caso você tenha experiência com tecnologias de automação, gerencia de configuração, o paradigma de infraestrutura como código ou containers, estes serão diferenciais.

O trabalho poderá ser realizado totalmente remoto, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente.

**Benefícios**

- Regime de contratação CLT;
- Salário inicial entre R$ 3.500,00 e R$ 4.500,00;
- Plano de saúde e odontológico Bradesco Nacional Top para o titular e mais um dependente totalmente custeados pela empresa;
- Vale refeição de R$ 400,00;
- Vale alimentação de R$ 600,00;
- Seguro de vida corporativo custeado pela empresa;
- Verba semestral de R$ 1.250,00 garantida para investimento em treinamentos e educação;
- Bolsas de estudo custeadas pela empresa;
- Acesso aos treinamentos da empresa sem custos;

**Por que trabalhar na Instruct?**

- Ambiente de trabalho amigável, inclusivo e seguro;
- Resolvemos problemas desafiadores e em larga escala para nossos clientes;
- Trabalhar na empresa referência de mercado em infraestrutura como código no Brasil;
- Empresa premiada como "Melhor Parceira Mundial" da Puppet em 2016;
- Acesso gratuito aos treinamentos oficiais Puppet e GitLab ministrados pela Instruct;
- Incentivos para participação em eventos, cursos e palestras;
- Empresa fundamentada nos princípios DevOps, Infra as Code e Agile;
- Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
- Cultura blameless;
- Café de qualidade!

**Tecnologias com as quais trabalhamos:**

- Conhecimentos e experiências fundamentais:
- Linguagem Python;
- Banco de dados relacional/SQL;
- Django ou outro framework web;
- Integração de aplicações via APIs REST;
- Git;
- Vagrant;
- Testes unitários;
- Conhecimentos diferenciais:
- Curso superior;
- Participação em projetos Open Source;
- Python Celery;
- Python asyncio;
- Puppet;
- PowerShell;
- Infraestrutura como código;

**Tecnologias e métodos**
Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:

- Fundamentos de modelos ágeis como Kanban e Scrum;
- Fundamentos do conceito testes unitários;
- Fundamentos do conceito testes de aceitação;
- MySQL ou PostgreSQL;
- Docker e containers;
- Jenkins/GitLab CI;
- Participação em projetos Open Source;
- Mattermost/Trello;

Enviar um e-mail com CV para jobs@instruct.com.br
com assunto "Python Developer Pleno".

## Labels:
 - Remoto
 - Pleno
 - CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
