### ISSUE TITLE
[São Paulo] Desenvolvedor Android Sênior [Amancay]

### ISSUE THREAD

**Issue by parizotto123** [backend-br/vagas#766]
A Amancay, Consultoria em TI há mais de 25 anos no mercado, busca candidato para atuar em um de seus clientes, um Banco Digital, de acordo com perfil abaixo: 

Desenvolvedor Android Sr.

Requisitos: 	
Experiência com desenvolvimento mobile nativo Android em Kotlin e Java (legado).
Experiência no uso de Web Services.
Conhecimentos de UX. 
Design Patterns. 
Testes unitários. 
Git 
Conhecimentos de arquitetura como MVP e MVVM. 

Diferencial:
Experiência com desenvolvimento para smartwatch e extensões. 
Conhecimento em Integração Contínua. 
Links com código no github e ou apps publicadas. 

Principais Atividades:
O profissional será responsável pelo desenvolvimento e manutenção do app Android, a expectativa é que o profissional seja capaz de entregar um produto com qualidade e requintes avançados de UX.
Desenvolvimento de features do app. 
Desenvolvimento de testes unitários. 
Análise e solução de bugs. 
Seguir o estilo de código proposto pelo time mobile. 
Seguir as guidelines propostas pelo time de design. 
Revisar código via pull request. 
Compartilhar conhecimento com o resto do time e propor melhorias contínuas. 

Ferramentas utilizadas: 
Android Studio 
Bitbucket, Jira 
Git (client de livre escolha)

Local de Trabalho: Próximo ao shopping Eldorado.
Contratação: CLT

Interessados, enviem currículo para flavia.parizotto@amancay.com.br e no campo assunto colocar: Android Sr.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
