### ISSUE TITLE
[REMOTO] Node.js Developer na AJA TECNOLOGIA

### ISSUE THREAD

**Issue by ajatwecnologia** [backend-br/vagas#767]
## Descrição da vaga

Integração de ferramenta de coleta de dados API ZABBIX com interface de front-end que exibe dashboards e outras funcionalidades.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- 2 anos de experiência com desenvolvimento Node.js

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Oferecemos soluções para negócios do futuro. Somos uma startup de tecnologia e desenvolvimento de soluções digitais integradas para empresas das áreas de Telecomunicações e TI.

## Como se candidatar

https://www.linkedin.com/company/aja-tecnologia/
comercial@ajatecnologia.com.br

## Labels

- alocação/Flexível
- alocação/Remoto
- experiência/Pleno
- regime/Freela

**Comment by davidrtpereira** [comment]
E-mail enviado!

**Comment by ajatwecnologia** [comment]
Obrigado Pessoal..
Preenchemos a Vaga.
