### ISSUE TITLE
[Uberlândia/MG] Analista Desenvolvedor de Sistemas PHP

### ISSUE THREAD

**Issue by milagloria** [backend-br/vagas#768]
Descrição das atividades:
Atuar na codificação do sistema na tecnologia PHP conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Incompleto dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Experiência com a plataforma PHP e conhecimento em MySQL, HTML, CSS e Javascript.

Tipo de Contratação: CLT

Local: Softbox, Uberlândia/MG

Vaga: Presencial/Alocado

Nível de candiado: Em aberto

Candidatar:
[https://softbox.com.br/job/analista-desenvolvedor-de-sistemas-php/](url)

Labels:

- CLT
- Presencial/Alocado
- Em Aberto

**Comment by devLopez** [comment]
Currículo enviado

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
