### ISSUE TITLE
[Uberlândia/MG] Desenvolvedor Trainee Java

### ISSUE THREAD

**Issue by milagloria** [backend-br/vagas#769]
Descrição das atividades:
Atuar na codificação do sistema na tecnologia Java conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Incompleto dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Desejável experiência com a plataforma Java e conhecimento em Java EE e EJB.

Tipo de Contratação: CLT

Local: Softbox, Uberlândia/MG

Vaga: Presencial/Alocado

Nível de candiado: Em aberto

Candidatar:
[https://softbox.com.br/job/desenvolvedor-trainee-java/](url)

Labels:

- CLT
- Presencial/Alocado
- Em Aberto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
