### ISSUE TITLE
[São Carlos/SP] Analista Desenvolvedor de Sistemas Java

### ISSUE THREAD

**Issue by milagloria** [backend-br/vagas#770]
Descrição das atividades:
Atuar na codificação do sistema na tecnologia Java conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Completo dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Experiência com a plataforma Java 8 e 9 e conhecimento em Java EE e EJB.

Tipo de Contratação: CLT

Local: Softbox, São Carlos/SP

Vaga: Presencial/Alocado

Nível de candiado: Em aberto

Candidatar:
[https://softbox.com.br/job/analista-desenvolvedor-de-sistemas-java/](url)

Labels:

CLT
Presencial/Alocado
Em Aberto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
