### ISSUE TITLE
[São Carlos/SP] Analista Desenvolvedor de Sistemas Node.js

### ISSUE THREAD

**Issue by milagloria** [backend-br/vagas#771]
Descrição das atividades:
Atuar na codificação do sistema na tecnologia NodeJs conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Completo dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Proficiência em NodeJS, GIT, Javascript (ES5, ES) e Docker; Conhecimentos sólidos em Design Patterns; Automatização de builds/ tooling (NPM, Webpack); Experiência com testes automatizado e unitários; Conhecimentos práticos em banco de dados NoSQL e no ambiente AWS.

Tipo de Contratação: CLT

Local: Softbox, São Carlos /SP

Vaga: Presencial/Alocado

Nível de candiado: Em aberto

Candidatar:
[https://softbox.com.br/job/analista-desenvolvedor-de-sistemas-node-js-2/](url)

Labels:
- CLT
- Presencial/Alocado
- Em Aberto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
