### ISSUE TITLE
[Alphaville,SP] Analista Desenvolvedor(a) - Resource IT

### ISSUE THREAD

**Issue by natassiamuniz** [backend-br/vagas#773]
Descrição da empresa

Somos uma tech partner focada em entrega de transformação digital. 
Oferecemos soluções e serviços baseados na tecnologia digital, especializada em suportar nossos clientes a se tornarem mais eficientes, inovadores e competitivos. 
Com mais de 27 anos de experiência, possuímos um time de mais de 3 mil colaboradores altamente qualificados e especializados, atuando em projetos no Brasil, América Latina e Estados Unidos. 
Por que a Resource? 
-Equipe multidisciplinar com amplo entendimento do negócio e visão diferenciada. -Monitoramento diferenciado para obter a maior satisfação possível do cliente. -Imersão na indústria do cliente para identificar a dor do negócio e oportunidades. -Visão integrada da transformação digital, o que nos permite entender o melhor caminho a percorrer. -Abordagem focada no produto, usando práticas como Lean, Design Thinking e Agile Methods.
http://www.resourceit.com

Local
Alphaville-SP

Posição
Pleno e Sênior

Benefícios
Assistência médica
Assistência odontológica
VR 
Convênio com instituições de ensino
Auxílio Creche
Desconto em rede de Farmácias 
Treinamentos em nossa plataforma EAD

Obrigatórios

- Java 6
- JSP
- Servlet
- Serviços SOAP e REST
- Oracle PL/SQL
- Java 8
- Microserviço
- Docker
- myBats
- Git
- Jquery

DESEJÁVEIS
 
-  Spring MVC
- String Boot
- Spring Security
- Mule
- Jasper
- Birt
- iBats
- SVN
- Maven
- Webservices Axis 2
- JBoss 
- Tomcat
- JPA
- Spring boot
- Angular 6
- React Native

Contratação
CLT

Como se candidatar

Se você busca uma nova oportunidade ou tem alguém para indicar para fazer parte do nosso time, encaminhe seu currículo pra natassia.muniz@resourceit.com

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
