### ISSUE TITLE
[REMOTO] Developer Mobile Android Pleno @ Going2 Mobile

### ISSUE THREAD

**Issue by brusecco** [backend-br/vagas#7730]
<!--
==================================================
==================================================

## Nossa empresa

A Going2 Mobile - uma empresa de tecnologia da informação, focada em criar produtos que buscam facilitar a vida das pessoas e empresas, está com VAGAS ABERTAS PARA TRABALHO REMOTO 💻 

## Descrição da vaga

• O profissional irá integrar time de desenvolvimento utilizando metodologia ágil (time Scrum);
• Desenvolvimento das demandas priorizadas pelo cliente;
• Participação em reuniões definidas pelo framework Scrum;
• Realizar o desenvolvimento evolutivo de sistemas e serviços;
• Utilizar boas práticas de desenvolvimento;
• Definir soluções de forma propositiva, apresentar as suas recomendações e ideias;
• Documentação de serviços, componentes e elaboração de diagramas;
• Compreender problemas técnicos e desenvolver soluções Mobile Nativa focado em aplicações Android;
• Concepção, desenvolvimento, implantação e manutenção de aplicações Android;
• Realizar integrações com serviços de terceiros;
• Habilidade de aplicar os padrões de desenvolvimento Android nativo;
• Colaborar com os testes e feedbacks dos usuários do aplicativo

## Local

Remoto - Horário Comercial

## Requisitos

**Obrigatórios:**
• Experiência em desenvolvimento de sistemas Mobile
• Habilidade no desenvolvimento de apps em Kotlin

**Diferenciais:**
Será um diferencial se possuir experiência em React Native

## Contratação

PJ 

## Como se candidatar

Link para inscrição: https://app.pipefy.com/public/form/iohJOGAI

## Labels
🏢 Remoto
👨 Pleno
⚖️ A-Combinar
⚖️ PJ

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by ghost** [comment]
Cade a descrição :sweat_smile:

**Comment by brusecco** [comment]
> Cade a descrição 😅

Teoricamente deveria estar aparecendo mas acho que deu algum problema!
