### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Back End na DITO

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#774]
### Sobre a empresa: Dito

A Dito é uma empresa de tecnologia que nasceu em meio à atmosfera de inovação do San Pedro Valley, em Belo Horizonte. Nós desenvolvemos uma plataforma capaz de impactar milhares de usuários de forma segmentada, inteligente e multicanais. 

### Descrição: Como será o meu trabalho?

Você precisará garantir desempenho, resiliência e extensibilidade para implementação de novas funcionalidades. Seu foco deverá ser sempre na qualidade e robustez nos códigos, sempre buscando novos aprendizados. Um olhar para a melhora de processos e inovação nas práticas e soluções também precisará fazer parte do seu dia a dia!

### Quais aptidões e habilidades preciso ter?

Na Dito você irá se tornar referência em Sistemas Distribuídos. Criar uma API única, extensível, confiável, controlada, padronizada e protegida. Para isso o ideal seria que você tivesse :

Aptidão com linguagens funcionais;
Grande expertise em back-end;
Facilidade e disposição para mentorar tecnicamente desenvolvedores menos experientes;
Sede por aprendizado para se aprofundar e ser especialista na área;
Habilidade de adaptar-se rapidamente às mudanças de contexto e prioridade.

### O que a Dito Oferece?

Vale transporte;
Vale refeição ou alimentação (R$20,60 por dia);
Assistência médica (Unimed);
Lanche na empresa;
Horários flexíveis;
Sem dress code por aqui;
Contato com novas tecnologias e tendências de mercado;
Um ambiente incrível :)

### Labels:

Alocado
Senior

### Candidatar: http://bit.ly/dito_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
