### ISSUE TITLE
[Teixeira de Freitas] Back-End Developer na [Inovatto Sistemas]

### ISSUE THREAD

**Issue by Gildarth** [backend-br/vagas#776]
## Descrição da vaga
Estamos com vagas abertas no time de Desenvolvimento! Buscamos pessoas que tem grandes ideias e vontade de construir algo incrível.

Se você é um desenvolvedor Back-end acima da média ou conhece alguém, essa é a oportunidade!

## Local
Escritório Teixeira de Freitas - Extremo Sul da Bahia (Possibilidade ser via Remoto.)

## Requisitos
- PHP 7.1 
- Laravel 5.5
- PostgreSQL
- API REST
- Conhecimento com Git 
- Conhecimento Básico Ubuntu/Linux
- Conhecimento com Cloud Computing

## Contratação
A combinar

## Rendimentos
R$ 3.500,00 ao mês

## Nossa empresa
Somos uma Startup inovadora pronta para oferecer uma nova experiência ao mercado que mais cresce no mundo. Conectamos: Gente boa + Empatia + Novas ideias + Design + Tecnologia.

Para que possamos implementar soluções disruptivas e diferenciadas para simplificar e gerar valor na gestão do negócio de Beleza e Bem-estar utilizamos como base o Project Thinking, Gestão Visual, Agilidade, Neurociência Aplicada e PESSOAS!

Somos o novo, mas com experiência de gente grande, nasce em 2017 a inovatto sistemas, com o apoio e a experiência da consolidada ECosmetics International Salon presente no Brasil, além da América do Norte, Europa, África e Emirados Árabes e a HSB Hair School Business, premiada com o título de Melhor Escola do Mundo para Cabeleireiros no Hairworld Global Awards em Paris.

## Como se candidatar
Aplique-se pelo link e envie seu currículo para nós: http://www.inovattosistemas.com/carreira/ - Enviar no assunto: Vaga Desenvolvedor Back-end

**Comment by Gildarth** [comment]
Oportunidade em aberta!!

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by Gildarth** [comment]
Não buscamos pessoas por senioridade ou graduação e sim pessoas que possa gerar valor para o negocio.

**Comment by ronilygomes** [comment]
Tentei enviar o currículo pela plataforma, mas ocorreu um erro no envio.

[https://drive.google.com/open?id=1SSnwf14NPSGH1igHPywKWqztvCWvVBgG](url)

Poderia me indicar uma alternativa?

**Comment by Gildarth** [comment]
> 
> 
> Tentei enviar o currículo pela plataforma, mas ocorreu um erro no envio.
> 
> [https://drive.google.com/open?id=1SSnwf14NPSGH1igHPywKWqztvCWvVBgG](url)
> 
> Poderia me indicar uma alternativa?

**Comment by Gildarth** [comment]
Ronily Gomes favor enviar para carreira@inovattosistemas.com
