### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na BRAIN SYSTEM

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#777]
### Sobre a empresa: BRAIN SYSTEM TECNOLOGIA

A Brain System atua no mercado de soluções tecnológicas há 15 anos, com sólida experiência em implementações de projetos voltados à área de atendimento e fidelização de clientes.

Apoiados por uma equipe motivada e de alto desempenho buscamos fornecer aos nossos clientes produtos e serviços únicos e de alta qualidade. Focados sempre na melhor solução de negócio, promovemos o aumento da produtividade, a otimização do negócio e a redução de custos. Mantemos o compromisso ético e o respeito ao ser humano, desenvolvendo individualmente e trabalhando em equipe.

### Descrição: Ocupações do cargo

Participar da equipe de desenvolvimento de software de CRM, criando novas funcionalidades, novos formulários com regras específicas do cliente, desenvolver integrações através de Web Services/APIs. Dar manutenção das plataformas Brain CRM e resolução de bugs quando necessário.

### Benefícios:

Vale Alimentação;
Vale Refeição;
Plano de saúde Amil;
Ambiente de trabalho descontraído.

### Conhecimentos Técnicos:

Visual Studio,
.NET
C#
Javascript
Frameworks front-end (BootStrap, ExtJs, outros)
Bando de dados relacional SQL Server (mas se você tiver conhecimento em Oracle ou IBM DB2 também será valido)

### Competências comportamentais:

Proatividade;
Engajamento para resolver os problemas do dia a dia dos nossos clientes;
Ter fácil entendimento das demandas atribuídas;
Ser criativo;
Ser autodidata.

### Labels:

Alocado
CLT
Pleno

### Candidatar: http://bit.ly/brainsystem_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
