### ISSUE TITLE
[Remoto] Contratação imediata - Devs Python e Java

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#778]
Olá, pessoal,

Tudo bem com vocês?

Peço antecipadamente desculpas por ir direto ao ponto, mas estamos precisando muito de pessoas boas, que tenham garra/predisposição/ânimo para trabalhar **muitas horas por dia**.

Nossa empresa [1] está enfrentando um problema "bom". Estamos crescendo em um ritmo muito acelerado [2] e simplesmente não estamos dando conta de fazer tudo o que precisa ser feito.

Diante disso, buscamos desenvolvedores Python (e Java) de todos os níveis (junior, pleno, sênior) que:
- Saibam trabalhar sobre **extrema** cobrança e pressão. 
Temos pessoas que ajudam a nos manter organizados e garantir que não perdemos o controle da situação, mesmo com toda a necessidade de velocidade.

- Topem trabalhar mais que 10 horas por dia (as vezes, até no fim de semana) pelos próximos 6 meses. Sabemos que isso realmente não é saudável, mas é o que está acontecendo e não temos como mudar nesse momento. Agora é a nossa chance de fazer "bonito" e nós só teremos essa chance.

Contrapartida:
- Equipe técnica de alto nível. Todo mundo se ajuda, o tempo todo. Não temos "estrelinhas".

- Em apenas três meses trabalhando conosco seu nível técnico será significativamente superior ao que é hoje, mesmo que você já seja muito fera. Os desafios técnicos são realmente significativos [3].

- Remuneração e crescimento agressivo, diretamente proporcional a sua capacidade de aprendizado e produtividade, avaliado semanalmente.

- Completa possibilidade de receber participação acionária na empresa em um curto prazo. Basta ser "do bem" e realmente estar a fim de trabalhar arduamente.

- Trabalho remoto e com flexibildiade de horários. Apesar de trabalharmos mais de 10 horas por dia, não tem essa de "bater ponto".
 
[1] - https://www.slicingdice.com
[2] - https://exame.abril.com.br/negocios/dino/startup-brasileira-cria-banco-de-dados-do-zero-e-desafia-as-gigantes-do-setor/
[3] - https://www.youtube.com/watch?v=Z2zNMPLn9h0&list=PL7zIHzbMoN_Tg2eZbgVi-X3xLiGIgninn

Por favor, quem tiver interesse em saber mais, peço gentilmente que responda esse email com seu currículo e atual remuneração.

**Benefícios:**
Nenhum

**Conhecimentos Técnicos:**
Python (Avançado)
Java (Avançado)

**Competências comportamentais:**
- Ser "do bem"
- Ter garra/predisposição/ânimo para trabalhar **muitas horas por dia**.

**Labels:**
Remoto
CLT
Junior, Pleno, Sênior

**Candidatar:**
CV e remuneração atual para: gabriel@slicingdice.com

**Comment by LuizSimonard** [comment]
Poderia definir melhor o que é ser bom em sua visão?

**Comment by gmenegatti** [comment]
@LuizSimonard, respondendo de forma bem direta, para nós ser "do bem" é: não ser "escroto", não ser estrela, não ser arrogante.

**Comment by gabrielsimas** [comment]
Boa!
*Luis Gabriel Nascimento Simas*
*Software Craftsman*
Junte-se a mim Linkedin - Join me on Linkedin:
http://www.linkedin.com/in/gabrielsimas
*Perfil Google Acadêmico: *
http://scholar.google.com.br/citations?user=f5HEJPEAAAAJ
Portfólio de Desenvolvimento: https://github.com/gabrielsimas
Twitter: @gabnascimento

“*Se for difícil eu faço agora, se for impossível me dê 5 minutos para me
preparar*"
*A presente mensagem é estritamente confidencial e seu sigilo é protegido
por lei. Quaisquer informações **e/ou documentos nela contidos são
destinadas exclusivamente a seu(s) destinatário(s) acima identificado(s).
Caso*

*tenha sido recebida por equívoco, notificamos que a divulgação, retenção,
disseminação, distribuição ou cópia de seu **conteúdo é proibida.*





Em seg, 4 de fev de 2019 às 09:41, Gabriel Menegatti <
notifications@github.com> escreveu:

**Comment by overdadeiro** [comment]
Eu só espero que as pessoas do bem paguem **MUITO BEM** pra uma vaga que eles já dizem de cara que vão sugar não só seu tempo como sua saúde

**Comment by gmenegatti** [comment]
@overdadeiro, conta do Github criada há 1 hora só pra se dar ao trabalho de comentar? Ta sobrando tempo.

**Comment by overdadeiro** [comment]
não precisa ficar sentido, só quis expressar o que eu senti quando li a descrição dessa vaga, e servir talvez de alerta pra alguém

o que você tá propondo tem um preço **caríssimo**, infelizmente não são todos os profissionais que tem essa percepção do quanto vale o seu tempo, seu fim de semana, seu descanso, e principalmente, sua saúde, e eu só queria expor que minha esperança é que pelo menos essas pessoas estejam sendo **muito justamente** remuneradas por isso

serve de reflexão pra você também, bota a mão na consciência e pensa nisso ao invés de ficar ressentido porque ouviu uma verdade inconveniente

Ps: sim, tá sobrando tempo, graças a deus eu não trabalho num lugar que consome todo meu tempo e energia :)

**Comment by reginaldojunior** [comment]
Pessoal, essa vaga é horrível. Infelizmente pelo bem da comunidade não é aceito o tipo de vaga que consuma todo o tempo da pessoa. 

Como empresa você deve procurar mais funcionários para cobrir a demanda e não um para sugar sua vida.

Desculpe, esse tipo de vaga não é aceito no backendbrasil.

**Comment by gabrielsimas** [comment]
Se for pensat assim... nenhuma empresa...

Em Qua, 6 de fev de 2019 21:44, Reginaldo Junior <notifications@github.com
escreveu:

**Comment by walteraa** [comment]
Que escroto, pra valer a pena trabalhar nessas condições só se o valoe/hora for de R$ 90+...

**Comment by onhernandes** [comment]
@gabrielsimas, @gmenegatti 

Vou deixar meu posicionamento aqui, como organizador do BackEndBrasil: o projeto em si é baseado na ideia de criar uma comunidade saudável. E isso implica diretamente com as vagas que oferecemos pra galera.

Ano passado houve um caso bem parecido de uma vaga abusiva e fechamos.

Assim vamos fazer com vagas anunciadas, perguntas no fórum, issues e PRs abertos, o que for nocivo será fechado aqui.

Nós queremos o melhor pra comunidade. Sempre foi assim e sempre vai ser assim. 

Decidimos que a vaga que você publicou é inadequada e abusiva, por isso fechamos.

Se quiser pensar em anunciar uma vaga aqui, dá uma lida no comentário dessa pessoa aqui, que foi uma crítica à outra vaga e serve muito bem aqui: https://github.com/backend-br/vagas/issues/588#issuecomment-461405201

Abraços.

**Comment by jersobh** [comment]
Parei de ler no 
Benefícios: nenhum

**Comment by ttribeiro** [comment]
> @overdadeiro, conta do Github criada há 1 hora só pra se dar ao trabalho de comentar? Ta sobrando tempo.

Essa arrogância é não ser do bem!

**Comment by allanweber** [comment]
@gmenegatti, está sobrando tempo pro cara criar conta no github e comentar pq ele não está nesse trabalho escravo de vocês.

**Comment by Assisneto** [comment]
Rapaz, se vcs não gostaram da vaga tudo bem, pode ser que alguém queria
pela possibilidade de participações nos lucros. A vaga sendo arrombada ou
não, ficar tripudiando ja e demais.

Em sex, 8 de fev de 2019 15:23, ALlan Weber <notifications@github.com
escreveu:

**Comment by guilherme90** [comment]
Galera, já chega de escrotizar a parada. O mundo é livre! Eu tbm náo curti muita coisa ai, mas nego aproveita outros comentarios pra ajudar a bombardear a parada. Ja deu, né? 

E é o que nosso colega ai disse, talvez alguém queira por causa da participações dos lucros.

Abraços.

**Comment by Assisneto** [comment]
Dois amigos meus responderam a vaga, quiseram encarar o desafio, mesmo a
vaga sendo taxada de "arrombada". Cada um sabe oque quer.....

Em sex, 8 de fev de 2019 17:59, Guilherme Nogueira <notifications@github.com
escreveu:

**Comment by allanweber** [comment]
Realmente, tem gente que não tem amor próprio.

**Comment by Assisneto** [comment]
Ou tem gente que não tem medo de trabalhar duro em troca de uma boa
recompensa.

Em sáb, 9 de fev de 2019 10:09, ALlan Weber <notifications@github.com
escreveu:

**Comment by allanweber** [comment]
Ou tem gente que acha que se rebaixar por trabalhos que não respeitam o profissional é sinônimo de trabalho duro.
Não há discussão cara, a vaga é tão horrível que teve a issue fechada.

**Comment by lhlimaverde** [comment]
Parabéns, a vaga está famosa, já está até no Vagas Arrombadas...

**Comment by mauricioklein** [comment]
Cara acha que vai trabalhar 24h por dia e a empresa vai ser super brother de dar 20% dos shares e o cara vai sair nadando na grana.

Galera tá assistindo muito `Silicon Valley` 😂

**Comment by wellingtoncosta** [comment]
Caramba, véi. Vocês ainda tão fazendo caso dessa vaga? Meu Deus.

**Comment by ghost** [comment]
O salário a gente recebe de você mesmo ou prefere que agilizemos o processo e peguemos diretamente dos empréstimos datados dos bancos?
https://www.escavador.com/sobre/24134287/gabriel-menegatti

**Comment by gmenegatti** [comment]
Honestamente, estão perdendo o tempo de vocês. Absolutamente nada vai mudar na minha vida ou no dia a dia da empresa em decorrência dessas mensagens de ódio. Se eu não fosse imune a esse tipo de ataque, jamais seria honesto e direto em relação a nossa forma de pensar, pois essa não foi a primeira vez e não será a última que seremos agredidos e viraremos motivo de chacota. A propósito, apenas para ficar claro, cada um que mandou mensagem de ódio realmente não me ofendeu, pois eu entendo e respeito sua maneira de pensar e agir. Ela só é diferente da minha. Não precisamos todos pensarmos da mesma maneira.

Quem entende a mensagem que queremos passar e o que estamos tentando fazer, já enviou o CV, já foi ou está sendo entrevistado e será selecionado, alguns de vocês querendo ou não. Esses profissionais que buscamos também são imunes a opinião de meia dúzia ou de qualquer grupo de Facebook que vive para criticar. Aliás, sinceramente, todo esse rebuliço que alguns fazem só serve para nos ajudar, pois mais pessoas ficam sabendo sobre nossa forma "diferente" de pensar e diversas se interessam.

@Drezus, obrigado pela pesquisa a meu respeito. Você honestamente acha que eu tenho vergonha de ter "quebrado" no passado e de ainda ter dívidas? Acha que você me afeta colando isso aqui? Acha que escondo algo que pode ser facilmente buscado no Google? Quem convive comigo já sabe sobre meus desafios do passado e nem por isso deixa de trabalhar comigo. Aliás, fique à vontade para tentar encontrar alguém que trabalhou comigo e não foi devidamente pago.

Como já falei inúmeras vezes, a Simbiose não é o tipo de empresa para quem quer ser apenas funcionário. Isso não significa que ela é melhor ou pior, ela é simplesmente diferente. Tem inúmeros pontos positivos, assim como inúmeros outros negativos. Quer fazer diferente? Vai empreender e contrate como seu funcionário todas essas pessoas que aqui me atacaram, afinal vocês pensam parecido. Seja a mudança que você quer ver no mundo. :-)

**Comment by guilherme90** [comment]
@Drezus desculpa cara, mas você passou dos limites. Pesquisando a vida pessoal do cara agora? Até onde isso vai parar? O que você tem a ver com os problemas pessoais dele? Isso não é da sua conta meu parceiro.

Vá cuidar da sua vida e deixa o cara em paz! Essa issue já deu o que tinha que dar. Você foi estremamente infeliz agora e isso foi um ato de total desrespeito. Lembrando que aqui não é lugar de ficar discutindo essas coisas, Não faça com os outros o que não gostaria que fizesse com você!

Moderação, há como desativar comentários disso aqui? Tá virando muita bagunça e indo pro lado pessoal, o que não é bom.

**Comment by ghost** [comment]
"Seja a mudança que você quer ver no mundo"
Falou o filhinho de papai que abriu duas empresas com a herança gorda da família e quer vir falando de ser alguém "do bem" promovendo uma verdadeira escravidão moderna numa indústria inchada e competitiva com a de TI.

Você tem razão, cara. Pra gente do seu nível, eu não deveria nem perder meu tempo expondo o quão desonesto e medíocre você é. Afinal, é isso que tu quer mesmo, que as pessoas desperdicem o tempo precioso delas para seus objetivos pessoais e fúteis. Aí depois vem querer opinar de governo, falar de corrupção ou de "mamar nas tetas". Deplorável.

Dá vergonha de dividir a mesma indústria com ascos da humanidade como você e observar os coitados dos profissionais desorientados que se submetem a tamanha humilhação profissional pra simplesmente exercerem seu oficio e garantirem seu ganha-pão.

Não é questão de pensar diferente, qualquer um em sã consciência e com o mínimo de ética desenvolvida consegue dizer como você tá usando o poder do seu dinheiro pra tornar o seu próprio mercado, e com isso o "mundo" que você faz tanta questão de ver a gente mudando, um lugar muito mais sofrível e deplorável. De gente assim eu só tenho pena, mesmo, parceiro. E não tem dívida ou processo judicial que vá mudar sua forma babaca de agir, mas pelo menos todo mundo já fica duplamente alertado! :-)

**Comment by gabrielsimas** [comment]
@gmenegatti eu gostei muito da vaga e acho a empresa bem promissora! Eu só não me candidato porque estou frio com o Java, tenho 10 anos de java, mas não trabalho com ele há 5... então, estou bem frio mesmo, mas gostei muito do Projeto e da forma como a vaga foi disponibilizada!
Futuramente, posso até investir nessa empresa com algum aporte financeiro.

**Comment by onhernandes** [comment]
Ae galera, vi as mensagens agora de vocês. A vaga já ta fechada e já nos explicamos, fechando a conversação.

**Comment by wellingtoncosta** [comment]
Alguém pode bloquear os comentários dessa issue? Acho que já estão passando dos limites. @Drezus, cara para com isso que tá feio já. Você deveria ir cuidar da sua vida ao invés ficar aqui expondo a vida pessoal dos outros e tentando denegrir a todo custo a imagem do outro.

**Comment by gabrielsimas** [comment]
@Drezus Muito chato ler isso de um colega de profissão.
Cada um sabe onde dói o calo e não vai ser com violência que as coisas vão melhorar ou mudar!
@gmenegatti acho que isso aqui cabe um processor por Calúnia e difamação
