### ISSUE TITLE
[São Paulo] Back-End Developer Java na [5A Attiva]

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#779]
**Empresa**

A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação.

**Números de vagas**
2 Vagas de Junior e 2 Vagas de Pleno

**Oportunidade**
Desenvolvimento de novas aplicações desenvolvidas em Java 1.6 ou superior  
Desenvolver funcionalidades alinhadas com a área de negócio sempre buscando agregar valor para os diferentes públicos que se relacionam com a empresa.
Antes das habilidades técnicas, buscamos um profissional que queira crescer profissionalmente e fazer uma carreira de sucesso, sempre obtendo novos conceitos e aprendendo novas tecnologias. 

**Perfil Técnico**
Atuar com desenvolvimento Java 6 ou superior, JPA/Hibernate; Spring; EJB 3, JAX-RS (REST). HTML; CSS; Angular ou React.

**Localidade**
Zona sul de São Paulo 

**Contratação**
5A Attiva - PJ valor Hora

Interessados, por favor, entrar em contato através do e-mail: Helen.matos@5aattiva.com.br

Indicações são bem vindas.

**Comment by AndersonMarquess** [comment]
Olá, teria alguma vaga CLT?

**Comment by helenmatos** [comment]
Olá @AndersonMarquess , sim temos uma vaga para CLT

**Comment by AndersonMarquess** [comment]
Enviado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
