### ISSUE TITLE
[São Paulo] Back End Developer - Grupo Movile

### ISSUE THREAD

**Issue by onhernandes** [backend-br/vagas#78]
## DESCRIÇÃO DA VAGA

Como Desenvolvedor Backend, você fará parte de times focados no desenvolvimentos e manutenção de aplicações e sistemas com diferentes níveis de escalabilidade, sustentabilidade e tolerância a falhas.

O que valorizamos no Grupo Movile?
- Senso de dono, que se apropriam dos projetos e fazem o melhor;
- Hands-on, colocar a mão na massa é essencial;
- Foco em resultado, é assim que impactamos a vida das pessoas;
- Inovadoção, precisamos mudar o jeito que as coisas acontecem e são;
- Apaixonadas pelo que fazemos e pelo nosso sonhos.

## RESPONSABILIDADES E ATRIBUIÇÕES

- Compreender os problemas sistêmicos e ajudar na construção de soluções;
- Ser capaz de criar soluções pragmáticas de software, onde os recursos são rapidamente entregues sem sacrificar a qualidade do código;
- Ajudar no desenvolvimento de APIs RESTful internas e públicas;
- Apoiar o rastreamento de métricas do produto através do desenvolvimento de ferramentas ou condução integração com as existentes.

## REQUISITOS E QUALIFICAÇÕES

Essenciais:
- No mínimo 4 anos de experiência profissional;
- Experiência sólida na construção de aplicações escaláveis, de alto desempenho e tolerantes a falhas;
- Sólida experiência com Java;
- Experiência em construção e integração com APIs RESTful;
- Conhecimento em frameworks Java populares (Ex: Spring);
- Experiência com bancos de dados relacionais e não-relacionais (Ex: PostgreSQL, Cassandra, Redis);
- Experiência mínima de 4 anos.

Diferenciais:
- Conhecimento em tecnologias de cache.
- Experiência com ferramentas de compilação em servidores Maven e CI, como Jenkins;
- Experiência com arquiteturas de microserviços;

## INFORMAÇÕES ADICIONAIS

Oferecemos:
- Ambiente de crescimento profissional;
- Desafios e aprendizados constantes;
- Clima amigável e de muita troca;
- Tecnologias de ponta;
- Profissionais altamente capacitados.

## CONHEÇA O GRUPO MOVILE

A Movile é líder em marketplaces móveis, e tem como grande sonho tornar a vida de 1 bilhão de pessoas melhor através de seus aplicativos. Atualmente trabalhamos com negócios e empresas em 4 pilares, que são: Food (iFood), Tickets (Sympla), Education & Care (PlayKids, SuperPlayer e Wavy) e Rapiddo (Marketplace, Payments e Entregas). Já estamos presentes no Brasil, Estados Unidos, França, México, Colômbia, Peru e Argentina, e somamos mais de 100 milhões de usuários ativos mensalmente. Com 1600 funcionários apaixonados pelo mesmo sonho, empoderados a construir novos negócios com potencial global e motivados a tomarem riscos.

A tecnologia é o nosso core, estamos formando times que criem e desenvolvam produtos incríveis para impactar e melhorar diretamente a vida das pessoas. Nossa stack é totalmente diversificada, contamos com tecnologias e linguagens diversas para termos a liberdade de sempre aplicar o que fizer mais sentido para determinado projetos. Gostamos de inovar, de aplicar ideias diferenciadas, de mudar produtos e de criar coisas realmente grandes e escaláveis.

Mais info [aqui](https://movile.gupy.io/jobs/5823)

**Comment by reginaldojunior** [comment]
Vaga preenchida?
