### ISSUE TITLE
[Fortaleza] [PJ] Arquiteto Java Sr. na FÁBRICADS

### ISSUE THREAD

**Issue by FDSsucesso** [backend-br/vagas#780]
### **Sobre a empresa: FÁBRICADS**

Fundada em 2012, em São Paulo, por um grupo de empreendedores e consultores de
tecnologia com o principal objetivo de oferecer ao mercado uma solução diferenciada e de
alta qualidade em serviços de TI.
Com uma política agressiva de Alianças Estratégicas com os principais fornecedores de
tecnologia do mercado, a FabricaDS tem atendido às necessidades de seus clientes com
reconhecido sucesso.

### **Descrição: Ocupações do cargo**

Profissional irá desenvolver soluções com o uso das tecnologias Java de mercado, definir arquitetura de soluções, discutir requisitos com o cliente e alinhar estimativas com gerente de projetos.

### **Obrigatório:**
– Formação (ou em andamento) superior na área de TI;
– Mais de 5 anos de vivência com análise e desenvolvimento de aplicações JavaEE com plataforma JBoss;
– Bons conhecimentos com linguagem SQL;
– Sólidos conhecimento com tecnologias e frameworks: JMS, EJB, JPA, JSF, CDI, Spring Boot, Apache Camel, Apache Maven, Docker;
– Controle de versionamento com GIT e SVN;
– Gestão de configuração com Apache Maven;

### **Desejável:**
– Conhecimentos em Angular, AngularJS, React, Jenkins, Apache Cordova;
– Disponibilidade para viagens;

### **Labels:**
Alocado
PJ
Sênior

### **Candidatar:** Enviar currículo para daniela.silva@fabricads.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
