### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Back End (Raspagem de dados) na CM Tecnologia

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#786]
### Descrição: Quais serão suas atividades na CMTecnologia?

Aqui na CM estamos crescendo de forma sem igual. Nosso mercado é bastante promissor e temos diversas aplicações e soluções a oferecer para nossos clientes. Você fará parte de uma solução estratégica para o crescimento da CM. O projeto já está em desenvolvimento e sendo migrado para Node.js. Você entrará para nos auxiliar a evoluir essa solução, além de migrar a solução que hoje é desenvolvida em Python. Você encontrará uma equipe para te apoiar e dar suporte. O que acha?

### Requisitos que você precisa atender:

Experiência com Crawler a famosa Raspagem de dados;
Node.js;
Javascript;
Sede por conhecimento;
Ter maturidade em entregas e trabalho em equipe;
Facilidade de aprendizado.

### Diferenciais que vão contar pontos para você:

Conhecimento de Python;
Automação de testes;
Jquery;
Ter conhecimento sobre Scrum;
Querer estudar e aprender!
Experiência de desenvolvimento utilizando métodos ágeis (Scrum);
Conheça os conceitos e processos ágeis de startup;
Controle de versão usando Git.;
Formação em qualquer curso de TI;

### Oferecemos um tudo para você crescer:

Vale Alimentação ou Refeição;
Vale Transporte;
Plano de Saúde Bradesco;
Plano odontológico MetLife;
Convênio SESC;
Convênio Farmácia (Araújo);
Horário Flexível;
No dress code;
Sinuca;
Ping Pong;
Video Game;
Aulas de inglês in loco;
Happy Hour toda sexta com cerveja. S2

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Auxiliar na criação de uma equipe de alta performance.

### Labels:

Alocado
Pleno

Obs: A ênfase em Raspagem de dados vem da necessidade de criarmos a melhor solução para nossos clientes! Está disposto a embarcar conosco nessa?

### Candidatar: http://bit.ly/cmtecnologia_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
