### ISSUE TITLE
[REMOTO] Desenvolvedor Sênior Ruby na Replay Gaming

### ISSUE THREAD

**Issue by paulgould** [backend-br/vagas#789]
Replay Poker ([www.replaypoker.com](www.replaypoker.com)) is a free-to-play online poker site whose mission is to spread the joy of poker to the world in a fair, friendly and competitive environment, without the risk of losing your shirt. 

Our vision is to be the go-to place for passionate poker players to play great poker and improve their game. We will succeed by offering an exceptional poker game experience and never losing our players trust. We celebrate the world’s greatest card game, its rich history and tradition, and seek to inspire others to share in our passion. 

**Our core values** 

- We’re big on our company culture, and keen on hiring like-minded people. So it’s important you share our values: 
- We put the needs of our players and community first
- We act with humility and treat others with respect
- We voice our opinions, but we’re open to new ideas
- We believe in taking ownership of ourselves and our work
- We recognise time is precious and not to be wasted
- We strive for excellence, but we’re not perfectionists
- We value a positive and flexible work life 

**The role**

We are a small, but growing team, of highly technical and experienced developers, which means you’ll have a huge impact on the decisions and the work being done. We all work remotely, 100% of the time. We’re currently spread out across Europe and South America. 

You’ll be responsible for maintaining and creating new features on all of our systems. These include the poker game client/server, poker lobby and not-quite-so-exciting auxiliary services (scheduling etc). 

We have a huge array of interesting problems to solve such as hunting down and killing the (thankfully) occasional performance issue, adding new features to bring happiness to our players and operations team, taking old code which has seen better days and refactoring it into something new and shiny that we can all be proud of, and much more. You’ll own the product as much as any of us and take collective responsibility in maintaining and improving it over time. 

We look for smart and independent people who work best in a team where everyone pulls their weight and collaborates with each other. Proactivity is key so we can improve and expand our systems without micromanagement. You will be given some freedom and with that comes responsibility (insert Spider-Man quote here). 

We are not afraid of using new technologies when we have to, but know that sometimes boring technology is the best solution. Using the best tools for the job is taken seriously and we expect everyone to be flexible enough to learn and use them.

 **Our stack**

- Poker lobby: Rails 4, a single page application with Backbone.js
- Poker game server: written in Ruby
- Poker game client: Flash - ActionScript 2.0 (in maintenance mode) and a new React/JS client in progress
- Other technologies used: MySQL, Sidekiq, Redis, NodeJS, Go, Kubernetes and many more

**You will**

- Have expert knowledge of Ruby and its surrounding environment
- Have expert knowledge of SQL and databases.
- Have expert knowledge of Unix
- Have expert knowledge of HTML5 and modern CSS (Less/Sass)
- Have 5+ years of Ruby development experience
- Have experience using modern JavaScript on the web (with or without a framework).
- Have experience writing automated tests, be it BDD, TDD, etc
- Have a good understanding of HTTP and REST-ful APIs
- Be confident working with git, code review and pull requests
- Be eager to learn and able to express your thoughts, arguments, and ideas clearly and effectively
- Have excellent english language skills (fluent speaking)

 **Ideally you should**

- Have experience with React/Backbone
- Have experience with GraphQL
- Have experience with Docker and Kubernetes
- Have professional experience working remotely
- Have contributed to open source projects
- Enjoy playing poker! 

**What we offer**

- Plenty of autonomy for you to work the way you think you're most productive
- A flexible process with the focus on efficiency of working with minimal bureaucracy
- A mixture of fun and challenging projects working on a real-time game
- Competitive salary (negotiable and depending on experience/skills)

**Apply here**
https://replaygaming.bamboohr.co.uk/jobs/view.php?id=2

**Comment by walteraa** [comment]
Hey, @paulgould do you have any journeyman level in RoR role available? have no 5 years in Ruby, but I have about 2~3 years(including in opens-source project working with Lenovo USA Team and Red hat) and experience in the other tech(Docker and kubernetes included).

If yes, I would like to apply!! :D

**Comment by paulgould** [comment]
Yes, still worth going ahead, please add your salary expectation then we can take that into account when considering experience in Ruby. Obrigado @walteraa!

**Comment by walteraa** [comment]
Done @paulgould. Thank you very much for your attention!! :smile:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
