### ISSUE TITLE
[Remoto] Freelancer - Java Backend Developer @ Dataseed

### ISSUE THREAD

**Issue by alvarogomes** [backend-br/vagas#7894]
VAGA

Desenvolvedor Backend Java para fazer manutenção de backend/microserviços em Springboot.

- Freelance
- Período 2 semanas
- Inicio imediato
- com possibilidade de integrar o time para projetos nacionals e internacionais.
- Enviar github e valor/hora e Disponibilidade.

E-mail para se candidatar: alvaro.brito@dataseed.de

**Comment by muriloalvesdev** [comment]
Tenho interesse, enviei um e-mail pra ti.
