### ISSUE TITLE
[Campinas/SP] Backend / Full + NodeJS / ReactJS + NoSQL* c/ experiência na [Startup Tarvos]

### ISSUE THREAD

**Issue by ftsoares** [backend-br/vagas#790]
### Desenvolvedor Backend / Full Stack com experiência
**Inscreva-se em:** [http://bit.ly/tarvosbackend](url)

**Empresa:** Tarvos - Startup de tecnologia da área agrícola

**Local da Sede:** Cidade Universitária, Campinas, SP

**Regime de contratação:** Bolsista 
 
**Objetivos:** Atuar no desenvolvimento de uma plataforma de aplicação para a solução criada pela empresa

**Resumo de atividades:** Estruturação da aplicação: (maior prioridade) servidor, segurança, modelagem de dados, API layer, Action Layer e Interface do Usuário (menor prioridade)

**Requisitos:**

- Graduação na área de Tecnologia da Informação ou Computação
- Inglês Intermediário
- Banco de dados NoSQL (MongoDB), preferencialmente / SQL
- Javascript
- API REST
- Framework NodeJS / ReactJS
- Protocolo JSON
- Experiência mínima de dois anos (será um fator de classificação)
- Ter disponibilidade para trabalhar no escritório da empresa também (reuniões e followup)

**Desejável:**

- Python
- Ferramentas de Interface front-end
- Experiência em consumo e definição de API de Teste
- Possuir conhecimento em ambiente cloud AWS

**Contato:**

vagas@tarvos.ag

**Comment by ftsoares** [comment]
Olá desenvolvedores! Procuramos um profissional com **autonomia, energia e entusiasmo** para a criação de soluções, assim como nós! **"Work Smart, Not Hard"**, não só define nosso modelo de trabalho, mas também como trazemos as soluções para o mercado. Faça parte dessa jornada e tenha a oportunidade de **crescer junto!** 🚀

**Comment by ftsoares** [comment]
Ainda estamos recebendo os formulários e contatos! Inscreva-se e fale com a gente!

**Comment by brunooomelo** [comment]
Sou de Jundiai, aceita remoto?

**Comment by ftsoares** [comment]
> 
> 
> Sou de Jundiai, aceita remoto?
@brunooomelo É uma opção sim. Você já acessou o formulário? Faça a inscrição e a gente pode conversar. Desculpe a demora na resposta, acabei não prevendo as perguntas por aqui...

**Comment by ftsoares** [comment]
A vaga continua aberta!

**Comment by brunooomelo** [comment]
Enviado! @ftsoares

**Comment by ftsoares** [comment]
Continuamos a receber os formulários. Tem alguma dúvida? Entre em contato com a gente!

**Comment by ftsoares** [comment]
Vaga encerrada!
