### ISSUE TITLE
[Rio de Janeiro/RJ] PHP Developer Full Stack na Benfeitoria

### ISSUE THREAD

**Issue by andre-pdassis** [backend-br/vagas#791]
## Descrição da vaga

E se você pudesse fazer parte de uma equipe que trabalha por um **mundo mais criativo** e **colaborativo**, bolando soluções para novos desafios?!

Galera, estamos com uma vaga aberta para o posto de **Developer PHP Full Stack** na @Benfeitoria! Faça parte do time de desenvolvedores de uma das maiores plataformas de crowdfunding do Brasil!

O/a developer será responsável pela manutenção e desenvolvimento de funcionalidades da plataforma de financiamento coletivo da Benfeitoria, bem como por zelar pelo acompanhamento de tarefas demandadas por outras áreas da empresa que tangem a equipe de desenvolvimento.

## Local

Escritório, Rio de Janeiro/RJ - Botafogo (A partir de março estaremos no Centro)

## Benefícios

- VR de R$ 15/dia
- Férias remuneradas (1.3x)
- 13º salário
- Fundo financeiro para capacitações
- Fundo financeiro para cuidado coletivo

## Diferenciais

- Horário flexível
- 1 dia de home office após período de experiência
- Frigobar abastecido

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- 2 anos de experiência com Mysql
- PHP OOP
- HTML5/CSS3/SASS
- MVC
- Experiência com algum framework PHP
- JavaScript (Vanilla, JQuery)

**Desejáveis:**
- Gulp
- Git

**Diferenciais:**
- Perfil no Github
- Gitflow
- Composer
- Docker
- APIs RESTful
- VueJS e VueX
- Zend 2 / Laravel 5
- Linux & Terminal
- Cloud

## Nosso Stack

- PHP 5.6
- PHP 7.2.x
- NGINX
- Mysql
- Docker

## Contratação

PJ a combinar

## Nossa empresa

Somos uma plataforma de crowdfunding que tem por objetivo fomentar uma cultura mais humana, colaborativa e realizadora no Brasil. Conectamos pessoas interessadas a projetos interessantes por meio do Financiamento Coletivo Pontual, Recorrente e Matchfunding. 

Projetos de cultura, empreendedorismo, tecnologia, educação, design, meio ambiente, esporte e saúde são todos.... Benfeitoria!

## Como se candidatar

Por favor envie um email para dev@benfeitoria.com com seu CV anexado - enviar no assunto: Vaga PHP Developer Full Stack

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Júnior
- Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
