### ISSUE TITLE
[Rio de Janeiro/RJ] Programador Back-End Pleno e Sênior no Reserve

### ISSUE THREAD

**Issue by reservesystem** [backend-br/vagas#792]
<vaga>"Programador .NET Pleno e Sênior"</vaga>

"Local": "Barra da Tijuca, Rio de Janeiro"
<currículo>"cv.vaga@reserve.com.br"</currículo>

"Javascript" : "Dominio"
".NET" : "Dominio"
"REST API" : "Dominio"
"C#": "Dominio"
"AngularJS" : "Desejável"
"Angular" : "Desejável"
"VB.Net" : "Desejável"
"WebForms" : "Desejável"
"GIT" : "Desejável"
"Entity Framework" : "Desejável"
"Design Patterns" : "Diferencial"
"SOLID" : "Diferencial"
".NET CORE" "Diferencial"

<Benefícios>"Plano de Saúde" & "Plano Odontológico" & "Vale Refeição" & "Vale-Transporte" & "Auxílio Academia"</Benefícios>

<Requisitos>"Pro-ativo" & "Boa Comunicação" & "Comprometimento" & "Disponibilidade"</Requisitos>

<Equipe>"Código Limpo" & "Ambiente Colaborativo" & "Plataforma Web"</Equipe>

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
