### ISSUE TITLE
[São Paulo] Back-End Developer na [ame digital]

### ISSUE THREAD

**Issue by MalletJorge** [backend-br/vagas#795]
<p align="center">
  <img src="https://s3.amazonaws.com/gupy5/production/companies/203/career/316/images/mainImage.png" alt="B2W Digital" width="900px" />
  
</p>

Oi, somos a Ame!

Estamos buscando desenvolvedores com experiência em desenvolvimento de aplicações Java, baseadas em micro-serviços, e práticas de testes para criar, identificar e propor melhorias no nosso app - estamos crescendo exponencialmente, e precisamos de pessoas que gostem do desafio de criar novas funcionalidades, de forma rápida e com melhoria contínua.

É uma posição em que é preciso tomar decisões e antecipar as demandas, operando de forma autônoma, com base no conhecimento e experiências adquiridos ao longo da carreira. Apoia a formação dos demais devs - pode liderar pessoas e/ou projetos.

Tecnologia é o nosso core - trabalhamos em squads, com times multi-funcionais onde todos participam ativamente e são responsáveis pelas decisões e metas de negócio.

**RESPONSABILIDADES E ATRIBUIÇÕES**

Participar ativamente do time para desenvolver, evoluir e manter sistemas de alta escalabilidade, disponibilidade e performance, resilientes e orientados a eventos, atuando diretamente em:
modelagem e manutenção dos repositórios de dados (SQL/no-SQL)
criação e manutenção de serviços REST em JAVA com regras de negócio (CRUD)
Colaborar com ideias que possam melhorar nossos sistemas e a vida dos nossos usuários;
Estar disposto a aprender e a ensinar;
Cuidar da nossa plataforma como se fosse seu filho;
Estar sempre atento a oportunidades para melhorar o código e nossos processos.
REQUISITOS E QUALIFICAÇÕES

**Importante:**
Graduação em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
Forte base em programação orientada a objeto: modelagem, desenvolvimento e testes de aplicações Java;

**Experiência em:**
- Análise de requisitos técnicos e funcionais;
- Desenvolvimento de APIs REST e micro-serviços;
- Spring Boot/Data/Cloud, JPA, Hibernate;
- Ferramentas de controle de código GIT;
- Banco de dados relacionais;
- Desenvolvimento em docker.
- 

**Experiência ou conhecimento em:**
- Ambiente Linux;
- Gerenciador de dependências e build (Maven, Gradle, etc).
- Lê e escreve em inglês. Você não precisa ser fluente, mas precisa estar apto a ler documentações, debater soluções em fóruns técnicos e escrever o código-fonte dos nossos sistemas.
 

**Diferenciais:**
- Outras linguagens de programação (Kotlin, Scala, Python e etc);
- Ferramentas de Integração Contínua;
- Bancos de dados No-SQL (Cassandra, ElasticSearch e etc);
- Metodologias ágeis de desenvolvimento (Scrum, Kanban).

**INFORMAÇÕES ADICIONAIS**
﻿
Para atingirmos alta escalabilidade de forma rápida, estamos o tempo todo experimentando novas abordagens e ferramentas. Quando o assunto é sistema de alta disponibilidade e volume, somos pioneiros no uso de Microservices, Cloud Computing, Kotlin, Clojure, Datomic, Go e React Native. E quando não encontramos as ferramentas adequadas no mercado, desenvolvemos dentro de casa (Atlas, RestQL e Marvin são bons exemplos).

Somos apaixonados por tecnologia e gostamos de compartilhar isso com a comunidade. Por isso, participamos dos principais eventos de tecnologia do país como patrocinadores e palestrantes (QCon, Big Data Week, Campus Party e Velocity) Também promovemos Meetups no nosso auditório e trazemos palestrantes nacionais e internacionais. E mais recentemente, disponibilizamos o Marvin e o RestQL para o uso público.

Tudo isso dentro de um ambiente bacana!

**O que você vai ganhar?**
- Muuuito conhecimento; 
- Desafios diários; 
- Trabalhar em um ambiente dinâmico e divertido; 
- Remuneração e benefícios alinhados com o mercado.

**Curtiu?**
Venha Fazer parte do nosso time e nos ajudar a construir a Fintech mais amada do Brasil [https://amedigital.gupy.io/jobs/29134](url)

<p align="center">
  <img src="https://www.amedigital.com/img/logo-min.png" alt="B2W Digital" width="180px" />
  
</p>

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
