### ISSUE TITLE
[ATUAÇÃO REMOTA] Back-end Developer Python @ DQRTECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [backend-br/vagas#7957]
> Vaga 100% Remota.

## DQR TECH
SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

CONTRATAÇÃO: PJ
Atuação 100% remota. 

DESAFIO: 
Contratação direta em nosso cliente, atuante há mais de 15 anos no mercado nacional, com selo GPTW e expertise em Consultoria Ágil; 
Transformação Digital e Desenvolvimento Full Stack. 

## Local

Remoto.

## Requisitos

REQUISITOS:
Requisitos: Python 2.7|3.8
Banco de Dados (SQLite)
GIT
Metodologia Ágil Scrum.
Necessário possuir equipamento próprio (16GB RAM – recomendado 32GB)

## Benefícios

Contrato PJ
Indicar sua pretensão salarial, por gentileza!

## Contratação

PJ - salário a combinar.

## Como se candidatar

Por favor envie um email para vagas@dqrtech.com.br com seu CV anexado - enviar no assunto: Vaga Python

## Tempo médio de feedbacks
Somos ágeis no Feedback!

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gsabreudev** [comment]
Pode vim falar comigo e com a Dai pessoal! :D
Meu whats: https://lnkd.in/eNwNcVxq
