### ISSUE TITLE
[ATUAÇÃO REMOTA] Back-end Developer JAVA @ DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [backend-br/vagas#7958]
> Vaga Remota.

## Nossa empresa

SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

CONTRATAÇÃO: PJ - 40h (semanais)

DESAFIO: 
Atuar em uma Fintech de soluções tecnológicas para operações financeiras, presente em 9 países de 4 continentes e disponibilizando diversos serviços em grandes players do segmento financeiro. 

## Local

Remoto.

## Requisitos
REQUISITOS:
Desenvolvimento em Java / Node JS;
Conhecimento básico em Linux;
Execução de testes de unidade, funcionais e de integração;
Versionamento com Git;
Arquitetura de microsserviços;
Domínio de orientação a objetos;
Spring Boot e utilização de APIs RESTFull;
Banco de dados relacional Postgres SQL;

DESEJÁVEL:
Experiência em Meios de Pagamento;
Conhecimento de metodologias ágeis de desenvolvimento como Scrum, Kanban;    
Experiência com cartões de crédito/débito e sistemas de liquidação;
ISO 8583;  
Conhecimento dos conceitos de Cloud Computing e Amazon Web Services como: ECS, EC2, ECR, ELB, S3;    
Conhecimento dos conceitos de aplicações em cluster, Docker;
Conhecimento de sistemas de mensageria (Ex: ActiveMQ, RabbitMQ, Kafka, IBM MQ);

## Contratação

PJ - salário a combinar!

## Como se candidatar

Por favor envie um email para vagas@dqrtech.com.br com seu CV anexado - enviar no assunto: Vaga Backend Java

## Tempo médio de feedbacks
Somos ágeis quanto ao retorno!

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gsabreudev** [comment]
Pode vim falar comigo e com a Dai pessoal! :D 
Meu whats: https://lnkd.in/eNwNcVxq
