### ISSUE TITLE
[São Paulo] Back-End Java Developer na [Consultoria]

### ISSUE THREAD

**Issue by igormgomes** [backend-br/vagas#796]
### **Oportunidade**
Pessoal estamos com algumas vagas para desenvolvedores Back end Java, esse profissional ira atuar em uma frente responsável por desenvolvedor novos produtos usando uma stack bem legal, participando de todas as cerimônias do Scrum (Daily, Plainning, Poker, Retro) e a partir da ai vai participar de todo o ciclo de desenvolvimento, definição de api, arquitetura e etc.

Atualmente ja temos projetos rodando em produção com Spring boot e mais algumas coisas que eu comento abaixo, então estamos buscando desenvolvedores que conhecem:
*Spring boot, Data, Security.
* Conhecer e já ter tido experiencia com projetos em arquitetura de micro serviços 
* Ter o hábito de escrever testes unitários.
* Conhecer bem a parte de REST (Status code, Recursos, Verbos)
* Docker
* Banco de dados NoSQL (Mongo, Redis).
* Se importar com qualidade de código (Design patterns, SOLID).

Mais informações entrar em contato: igormgomes94@gmail.com

A vaga é presencial e estamos localizados na zona sul de São Paulo.

**Comment by AndersonMarquess** [comment]
Enviado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
