### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Web Full Stack na GO UP

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#798]
### Sobre a empresa: GoUp

A GoUp é um Holding de empresas que atuam com foco em inovação em diversos mercados.

### Descrição: Ocupações do cargo

Idealizar, desenvolver, sustentar e evoluir aplicações em sua totalidade levando em consideração as dependências tecnológicas e a experiencia do usuário.
Atuará em todas as camadas da pilha.
Contribuir nos projetos e propor as melhores práticas em desenvolvimento.
Desenvolver e testar aplicações Web em NodeJS.

### Benefícios

Ticket Refeição
Vale Transporte

### Aptidões e qualidades

Aptidão para liderança
Trabalhar em equipe
Organização
Auto-gestão

### Conhecimentos Essenciais

Experiência em Javascript / Node
Experiência em Controle de Versionamento (Git)
Experiência com banco de dados MongoDB e Firebase
Experiência com React, HTML e CSS
Experiência em ExpressJS
Experiência em AWS (Amazon Web Services)
Métodos de desenvolvimento ágeis
Inglês em nível intermediário.
Organização, excelente comunicação e relacionamento interpessoal. 
Sistema Operacional Linux.

### Labels

Alocado
Pleno

### Candidatar: http://bit.ly/goup_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
