### ISSUE TITLE
[SÃO PAULO] Analista Desenvolvedor C# [SMT]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#801]
Tipo de Contratação: CLT

Estamos procurando um desenvolvedor .NET para compor o nosso time de desenvolvimento que trabalha em soluções de meios de pagamento e serviços financeiros. O desenvolvedor participará do desenvolvimento de micro-serviços utilizando .NET Core hospedados em ambiente de nuvem utilizando o Azure.

Requisitos:
* Experiência de ao menos 2 anos com C#, ASP.NET MVC, WebAPI.
* Controle de versão com Git;
* Conhecimento em métodos ágeis de desenvolvimento

Diferenciais:
* Experiência com .NET Core 2 e Azure

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Analista Desenvolvedor C# / SMT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
