### ISSUE TITLE
[SÃO PAULO] Analista Desenvolvedor C# MSMQ [XP]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#802]
Tipo de Contratação: CLT

Requisitos:
* Frameworks 4.6
* Experiência em mercado financeiro, corretoras ou Bovespa.
* Experiência em arquitetura
* VSTS (Visual Studio Team Services)
* Plataforma: Service Fabric
* Mensageira
* MS (Microsoft Service)
* MS Service Bus
* MSMQ (Message Queuing)

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Analista Desenvolvedor C# MSMQ/ XP

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
