### ISSUE TITLE
[SÃO PAULO] Analista Desenvolvedor C# FIX [XP]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#803]
Tipo de Contratação: CLT

Requisitos:
* Frameworks 4.6
* Experiência em mercado financeiro, corretoras ou Bovespa
* Experiência em arquitetura
* FIX Protocol

Diferenciais:
Sistema de Mensageria (RabbitMq) 
Hibernate

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Analista Desenvolvedor C# FIX/ XP

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
