### ISSUE TITLE
[SÃO BERNARDO DO CAMPO - SP] Analista Desenvolvedor C# Allianz

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#804]
Tipo de Contratação: PJ

Requisitos:
C#;
MVC;
Asp. NET;
SQL Server. 

Obrigatório:
Inglês fluente.

Experiência em:
API's, Rest e autenticação Oauth2;
.Net com Windows Forms; 
Oracle. 

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Analista Desenvolvedor C#

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
