### ISSUE TITLE
 [Vila Olímpia/SP] Desenvolvedor Ruby Pleno e Sênior

### ISSUE THREAD

**Issue by mayksalles** [backend-br/vagas#805]
### Sobre a empresa: BIONEXO
Soluções digitais para gestão de processos em saúde

### Descrição: Ocupações do cargo
Desenvolver novas funcionalidades e atuar na resolução de bugs das aplicações.
Trabalhar em colaboração com outros times.
Trazer boas práticas e conhecimentos técnicos para o dia a dia de trabalho.
Compreender as necessidades dos usuários para ajudar a melhorar a eficiência dos fluxos de trabalho.
Possui experiência em papéis que incluem desenvolvimento backend e frontend.
Desenvolvimento de aplicações web.
Possui experiência com algum banco de dados relacional, testes automatizados (unitários, de interface e integração) e é habituado em trabalhar com pull requests.
Ter noções de segurança para desenvolver código seguro.
Conhecer metodologias Ágeis.
Possui experiência em Ruby on Rails 

### Labels
Alocado (PJ)
Pleno e Sênior

### Candidatar: http://rnstad.biz/s/w/55K8HV

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
