### ISSUE TITLE
[Vila Olímpia/São Paulo - SP] Vaga de Desenvolvedor Backend na [Clickbus]

### ISSUE THREAD

**Issue by danilopereira** [backend-br/vagas#806]
## Sobre a Clickbus
A ClickBus é a maior plataforma online de vendas de passagens rodoviárias no Brasil, líder em inovação do setor e está conectada a mais de 150 empresas de ônibus. São 5 anos de mercado e mais de 4 mil destinos oferecidos para que os viajantes pesquisem, comparem e comprem passagens de ônibus para todo o Brasil, com toda a facilidade e segurança que nosso site oferece. É por isso que contamos com um time diferenciado e buscamos novos ClickBusers para fazer parte desse busão em uma viagem incrível!

Está afim de embarcar nessa? Mostre a sua bagagem pra gente se aplicando para esta vaga! :)

## Você será responsável por
Projetar, desenvolver e implantar serviços de back-end com foco em alta disponibilidade, baixa latência e escalabilidade;
Colaborar com outros desenvolvedores e tornar-se um valioso membro de uma equipe autônoma e multifuncional;
Desenvolver nossa API, Workers e automatizações;
Integrar Gateways de pagamento;
Realizar pesquisa de novas tecnologias, entendendo a viabilidade de implementação.

## Requisitos
Experiência com Spring Framework (Boot, Security, Data, Test, etc.);
Experiência com Database (MySql, ElasticSearch, MongoDB);
Conhecimento em Container (Docker);
Experiência com Cache (Redis);
Conhecimento em Environment – AWS;
Experiência em TDD e BDD;

## Oferecemos
Ambiente de trabalho descontraído, com espírito de equipe e pessoas talentosas;
Autonomia para trabalhar, desenvolver e implementar ideias;
Vale refeição de R$30,00/dia;
Vale transporte;
Horário flexível;
Gympass;
Assistência médica / odontológica / Seguro de vida
Local de trabalho: Vila Olímpia

## Como se candidatar
Os interessados devem enviar o CV para recrutamento@clickbus.com.br com o assunto: "Desenvolvedor Backend"

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
