### ISSUE TITLE
[Porto Alegre] Analista Programador na SML Brasil

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#808]
### Sobre a empresa: SML Brasil

A SML fornece toda a metodologia e a tecnologia necessária para o cliente descobrir, simplificar e digitalizar seus processos de negócio, conectando a estratégia ao desempenho operacional. Com isso, ajudamos a organização a melhorar a colaboração e a comunicação, eliminando silos, papel, retrabalho, informalidade e erros. Existimos para tornar a vida dos nossos clientes mais simples e eficaz. Nossa missão é entregar soluções digitais que coloquem processos e informações para trabalhar a favor dos clientes.

### Descrição: Ocupações do cargo

Análise e/ou elaboração de viabilidade;
Criação de estruturas e rotinas para banco de dados;
Atividades de pesquisa e desenvolvimento com objetivos de adquirir novos conhecimentos, concepção de produto ou processos, bem como agregação de novas funcionalidades ou características ao produto ou processos, que implique em melhorias incrementais e efetivo ganho de qualidade;
Criação e manutenção de instaladores para ambiente servidor e cliente;
Preparação e realização de reuniões e entrevistas junto a clientes, compreendendo a elaboração de atas;
Elaboração de estimativas, identificação de riscos de projetos e revisão de seus artefatos;
Realização de treinamento e apresentação interna e externa para disseminação de conhecimento;
Elaboração, preparação e execução de testes de carga e performance.

### Benefícios

Vale Refeição: R$ 22,50/dia;
Vale Alimentação: R$ 200,00/mês;
Assistência Médica : SulAmérica Saúde (Plano Clássico pago 100% pago pela SML);
Vale Transporte;
Seguro de Vida;
Inglês In Company;
Assistência odontológica: Uniodonto.

### Requisitos mínimos

Metodologia ágil;
.NET;
C#;
Java Script;
SQL (MSSQL ou Oracle ou Postgresql);
GIT;
TDD;
API RESTful.

### Informações complementares

Possibilidade de home office em até 4 dias da semana e horário de trabalho flexível.

### Labels

Alocado/Remoto
Pleno
CLT

### Candidatar: http://bit.ly/sml_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
