### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Python na Onidata

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#81]
## Descrição da vaga

Desenvolver novas funcionalidades de um extenso RoadMap, trabalhamos com metodologias ágeis e procuramos ter cobertura 100% em testes unitários e utilizamos algumas ferramentas para garantir a qualidade do software.

Profissional que esteja habituado a trabalhar com code review e desenvolvimento de API Rest/Json

## Local

Rio de Janeiro

## Requisitos

**Obrigatórios:**

-Git
-Python 3
-Django
-PostgreSQL

## Contratação

CLT à combinar

## Nossa empresa

A Onidata é uma empresa sediada na cidade do Rio de Janeiro, com representantes na cidade de São Paulo, composta por uma equipe de profissionais especialistas, que atuam há mais de 20 anos no desenvolvimento de soluções em tecnologia da informação para o mercado financeiro.

Ficamos na Barra da Tijuca - Rio de Janeiro no shopping Cittá-América

## Como se candidatar

https://app.vulpi.com.br/onidata/582?invited_by=9433

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
