### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na [B2W DIGITAL]

### ISSUE THREAD

**Issue by MalletJorge** [backend-br/vagas#810]
<p align="center">
  <img src="https://s3.amazonaws.com/gupy5/production/companies/203/images/jobs/7694/20180424081802538_picture.png" alt="B2W Digital" width="900px" />
</p>

<H1> Vagas para Desenvolvedor Back-end </H1>
     <H2> Estamos buscando os melhores Devs para compor o nosso time </H2>
<p>
      Temos a missão de manter e evoluir uma das plataformas mais complexas e robustas da internet. 
      Uma enorme parcela de tudo que é vendido online no Brasil tem como vitrine os sites 
       Americanas.com, Submarino, Shoptime e Sou Barato. Os nossos números são absurdos, veja:
</p>
<ul>
   <li>180 page-views por segundo;
   <li>21 milhões de visitantes únicos por mês (ou 270 Maracanãs lotados);
   <li>1 milhão de produtos distintos sendo oferecidos nos sites;
   <li>14 buscas realizadas nos sites a cada segundo;
   <li>Terabytes de dados são gerados todos os dias.
</ul>

<H2>Requisitos desejáveis</H2>
   <ul>
<li>Forte base em programação orientada a objeto;
<li><strong>Linguagens, não temos uma preferida e estamos sempre dispostos a experimentar</strong>. Hoje temos código escrito em Java, Groovy, PHP, Go, NodeJS e Kotlin. Se você domina alguma dessas linguagens, já possui uma vantagem;
<li>Experiência na realização de testes automatizados e refatoração de código;
<li>Graduação em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
<li>Confortável com Ambiente Unix;
<li>Conhece o básico de versionamento com GIT;
<li>Sabe como funciona o protocolo HTTP e o padrão REST;
<li>Lê e escreve em inglês. Você não precisa ser fluente, mas precisa estar apto a ler documentações, <li>debater soluções em fóruns técnicos e escrever o código-fonte dos nossos sistemas.
</ul>

<H2>Vantagens de trabalhar na B2W Digital</H2>
<ul>
<li> Utilizar as melhores tecnologias do mercado
<li> Trabalhar com problemas complexos e de alta escalabilidade, e os melhores profissionais do mercado para te ajudar a solucioná-los
<li> Pertencer a um time multidisciplinar e apaixonado por tecnologia
<li> Conviver num ambiente descontraído 
<li> Bermuda liberada
<li> Convênio com as melhores faculdades do país
</ul>

<H2>Benefícios</H2>
<ul>
<li> Remuneração compatível com o mercado
<li> VR + VA
<li> Vale transporte
<li> Plano de Saúde + Odontológico
<li> Seguro de Vida
</ul>

<H2>Coisas legais que estamos fazendo</H2>
<ul>
<li>QCon - https://www.infoq.com/br/presentations/restql-orquestracao-de-microservices-com-rest-na-americanas
<li>Marvin - https://www.valor.com.br/empresas/5262243/b2w-digital-compartilha-sistema-de-inteligencia-artificial-na-web
<li>RestQL - http://restql.b2w.io/
<li>Big Data Week - http://sao-paulo.bigdataweek.com/session/marvin-platform-potencializando-equipes-de-machine-learning/
<li>Campus Party - https://campuse.ro/events/campus-party-brasil-2017/talk/submarino-cpbr10/
<li>Velocity - https://conferences.oreilly.com/velocity/vl-ca-2016/public/schedule/detail/51193
<li>Blog de tecnologia - https://medium.com/b2w-engineering
<li>Nossos Resultados Financeiros - https://ri.b2w.digital/
</ul>

<H2>Modalidade de contrato</H2>
<ul>
<li> CLT Integral
<li> Trabalho Alocado - Centro do Rio de Janeiro
</ul>

<h2>let's Go! Let's Elevate!</h2>
<p> Se inscreva no link:</p> https://b2w.gupy.io/jobs/22423

**Comment by vcpablo** [comment]
Olá, aceita remoto?

**Comment by MalletJorge** [comment]
@vcpablo, bom dia. 
Apenas alocado.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
