### ISSUE TITLE
[São Paulo | Vila Olímpia] Developer Back-End Node.JS [Askme | Marketing de Incentivo]

### ISSUE THREAD

**Issue by danielegcosta** [backend-br/vagas#811]
### Sobre a Askme:

Somos a primeira IncentiveTech da AmericaLatina. Somos a Askme, uma empresa de tecnologia especializada em marketing de incentivo.

Buscamos simplificar processos, desenvolver produtos e soluções únicas para o mercado, acompanhar resultados e métricas importantes para definir novas estratégias e chegamos até a personalizar campanhas de acordo com as necessidades dos clientes.

### Sobre a nossa Cultura e dia-a-dia:

Temos um clima descontraído e ambiente despojado em nosso escritório. Aqui, cultivamos a boa relação entre as pessoas, o conceito de trabalho em equipe e, apoiamos a diversidade nas mais amplas vertentes. Apoiamos o desenvolvimento de carreira de cada um de nossos funcionários. Damos ouvidos aos nossos colaboradores, abrimos espaço para que se sintam confortáveis e principalmente como parte importante para o nosso crescimento.

Para trabalhar na Askme é importante que você enxergue o seu valor, pois acreditamos que todo mundo pode mais. Para nós, reconhecer um talento é recompensar seu esforço. Ter brilho nos olhos é sonhar com vontade de realizar. Queremos chegar onde ninguém chegou. Nosso time está preparado para isso. Você está?

### O que você fará como Desenvolvedor Back-End NodeJS:
  
•	Desenvolver soluções escaláveis e de alta disponibilidade;
•	Atuação tanto na sustentação de sistemas como no desenvolvimento de novas features;
•	Foco em alta produtividade e flexibilidade, através de entregas iterativas e incrementais de valor de negócio;

### O que você precisa para ser o nosso DEV:
  
•	Ter experiência com programação em Javascript, NodeJS e ferramentas Open Source, além de APIs RESTfull;
•	Ter atuado com versionadores de código como BitBucket e github; 
•	Ter conhecimento de Bancos de dados: MYSQL, Postgres, MSSQL;
•	Possuir conhecimento também em Integrações com parceiros via consumo de API ou SOAP;
•	Ter experiência com metodologias ágeis: Scrum/Kanban.

### Será um super diferencial se você tiver:

•	Ter conhecimento de inteligência com micro serviços;
•	Saber trabalhar junto a plataforma: Kubernetes, Docker e utilização de containers;
•	Conhecer Redis e Bancos não relacionais.

### Contrato:
PJ - Alocado
 
### Um pouco mais de como é trabalhar com a gente:

Aqui nosso ambiente é super descontraído e informal, inclusive sem dress code. Sim, bermuda é bem-vinda;
Estamos em plena transformação de uma 100 % Agência de Marketing, para 50% MKT e 50% Tech;
Atuamos em Squads multidisciplinar, vivemos agilidade e somos apaixonados por inovação, tecnologia e criação; 

### Contato
Envie seu cv ou linkedin para o e-mail: rh@askme.com.br
Seria legal, se já mandasse com pretensão salarial como PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
