### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na DESCOLA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#813]
### Sobre a empresa: DESCOLA

Somos uma escola de inovação online. Entendemos os principais temas que estão mudando o mundo, organizamos em conteúdos práticos, rápidos, leves e inspiradores e levamos eles para as pessoas. O aluno pode fazer de onde quiser, quantas vezes quiser e no device que preferir. Nossa missão é que ao final do curso o aluno saia com uma nova habilidade desenvolvida para aplicar em sua vida ou no trabalho. Transformamos suas curiosidades em Habilidades.

### Descrição: Ocupações do cargo

Vamos reconstruir a Descola do zero. O desenvolvedor ajudará em todas as etapas do processo desde modelagem de banco de dados a arquitetura da aplicação e será responsável por escrever boa parte do novo código. 

### Benefícios

Cursos online da Descola;
Cursos presenciais da ECHOS;
Temos chope liberado todos os dias a partir das 18h e um ambiente de trabalho descolado e muito inovador;
A empresa está estruturando um modelo de stock options que será implementado em breve.
Horário de trabalho flexível. 

### Aptidões e qualidades

Somos uma empresa ultra informal, com sócios e colaboradores jovens em um ambiente dinâmico. Justamente por isso contamos com maturidade e responsabilidade, já que existe uma grande flexibilidade. Este tipo de maturidade não esta relacionado à idade, e sim a comprometimento.

### Labels

Alocado
PJ
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
