### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Node Js na NUCONT

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#814]
### Descrição: O que você irá fazer?

Participar do planejamento das atividades;
Desenvolver microservices em Node.JS;
Programar testes em dupla ou solo;

### ﻿As habilidades necessárias:

Node.js;
MongoDB;
Experiência com metodologias agéis;

### Beneficios:

Vale-transporte;
Vale-refeição;
Desconto em academia;
Treinamento funcional e squash no prédio da empresa;
Frutas a vontade todos os dias;
Cervejinha liberada nos happy hour de quinta e sexta-feira;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Tem sangue nos olhos e foco na missão;
Acredita que nada é impossível, ainda mais se for programando;
Horários flexíveis e um ambiente muito legal de se trabalhar! :)

### Labels

CLT
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
