### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Full Stack na SOLARVIEW

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#815]
### Sobre a empresa: SolarView

A SolarView existe para trazer economia as pessoas e empoderá-las para serem energeticamente independentes. E para tornar isso possível desenvolvemos uma plataforma para monitoramento e análise completa de Geração de Energia Distribuída. Agora, precisamos reforçar nosso time para conquistarmos o mundo! Contamos com você!

### Descrição: O que você irá fazer?

Trabalhar na construção de produtos web e mobile que entregam informação e economia para milhares de pessoas que produzem a sua energia elétrica, desde a análise dos problemas de negócio até o suporte em produção;
Gerenciar prioridades do produto, prazos e entregas;
Participar ativamente da seleção de tecnologias para os produtos.

### As habilidades necessárias

Experiência com programação em PHP;
Experiência com banco de dados MySQL;
Experiência com controle de versão Git;
Experiência com HTML, Javascript e CSS;
Participação efetiva em desenvolvimento de software PHP;
Graduação em Ciência da Computação ou cursos relacionados ou experiência prática equivalente;
Experiência com metodologias ágeis;

### Diferenciais

Experiência com o framework PHP Codeigniter;
Conhecimento e experiência com práticas de uma cultura DevOps;
Noções de manutenção e operação de servidor Linux para WEB;
Experiência em criação e uso de APIs (REST, JSON);
Experiência com integração de Gateways de pagamento em softwares PHP;

### Beneficios

Vale transporte;
Vale refeição;
Auxílio médico;

### Labels

CLT
Alocado
Pleno

### Candidatar: http://bit.ly/solarview_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
