### ISSUE TITLE
[São Paulo] [CLT] Analista de Infraestrutura Pl. na FábricaDS

### ISSUE THREAD

**Issue by FDSsucesso** [backend-br/vagas#816]
### **Sobre a empresa: FÁBRICADS**
Fundada em 2012, em São Paulo, por um grupo de empreendedores e consultores de
tecnologia com o principal objetivo de oferecer ao mercado uma solução diferenciada e de
alta qualidade em serviços de TI.
Com uma política agressiva de Alianças Estratégicas com os principais fornecedores de
tecnologia do mercado, a FabricaDS tem atendido às necessidades de seus clientes com
reconhecido sucesso.

### **Descrição: Ocupações do cargo**
Administração de Redhat, KVM
Administração Storages EMC, Netapp e SUN
Criação e administração de máquinas virtuais
Criação e administração de LUNs de storage, implementação de projetos, ongoing, gerência de ambientes UNIX de alta criticidade (mudanças, incidentes e problemas)
Planejamento de atividades, capacity e performance tunning
Migração de versões, de ambientes, análises e relatórios.

### **Obrigatório:**
- Experiência em ambientes Linux e Unix (Redhat Linux)
- Red Hat versões 5, 6 e 7
- CentOS
- Experiência com LDAP e IDM
- Docker
- Openshift ou Kubernetes ou Rancher
- Conhecimentos em redes TCP/IP
- Ansible ou Chef
- Conhecimento em ambientes Cloud
- Disponibilidade para atuar em escala aos finais de semana.

### **Desejável:**
- Soluções Red Hat: RHEV, CloudForms, Openstack e Openshift.
- Administração JBoss EAP 6 e 7
- Jenkins
- Git
- Satellite/Katello

### **Oferecemos:**
Vale transporte, vale refeição, assistência médica, seguro de vida e auxilio creche. 

### **Labels:**
Alocado
CLT
Pleno

### **Candidatar:** Enviar currículo para daniela.silva@fabricads.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
