### ISSUE TITLE
[Florianópolis/SC] Fullstack PHP Developer na Uapper Tecnologia

### ISSUE THREAD

**Issue by philipedornelas** [backend-br/vagas#817]
## Descrição da vaga

Desenvolver sistemas e aplicações, determinando interface gráfica, montagem da estrutura de banco de dados e codificação de programas; projetar, implantar e realizar manutenção de sistemas e aplicações; selecionar recursos de trabalho, tais como metodologias de desenvolvimento de sistemas, linguagem de programação e ferramentas de desenvolvimento.

## Local

Remoto ou Escritório, Florianópolis/SC

## Requisitos

**Obrigatórios:**
- Análise, arquitetura e desenvolvimento de Microservices e aplicações distribuídas.
- Conhecimentos em PHP, node.js
- Experiência em trabalhar com metodologia ágil (SCRUM / KANBAN).
- Experiência de trabalho de pelo menos 4 anos.

**Desejáveis:**
- Conhecimento em JavaScript, JQuery, Web, HTML5, CSS, Bootstrap, JSON
- Controle de versão no Github
- Criação de tarefas, sprints, requisitos, backlog

**Diferenciais:**
- Conhecimentos em Angular e VUE.js

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ricardo.gomes@uapper.me com seu CV anexado - enviar no assunto: Vaga PHP Fullstack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
