### ISSUE TITLE
[Remoto] [Jr, Pl, Sr] Backend Developer @ Uma nova startup

### ISSUE THREAD

**Issue by raphaelsampaio** [backend-br/vagas#8177]
## Nossa empresa

Somos uma proptech fundada em 2021 e investida por um dos maiores fundos de venture capital do Brasil.

## Descrição da vaga

Estamos contratando engenheiros de software com **qualquer senioridade** para as áreas de Frontend, Backend e
Ops (avise seus coleguinhas)

Nosso modelo de contratação é PJ, 100% remoto e nossa stack é composta por 
Vue.js + Python + MongoDB + AWS.

Além da possibilidade de trabalhar em casa, oferecemos um dia por mês -- além de fins de semana e feriados --
para que vc use da forma como quiser, seja descansando, trabalhando num projeto pessoal, 
resolvendo pendências da vida ou jogando um CS (me chama), dotinha ou lolzinho.

Nosso processo seletivo é composto por três etapas: entrevista inicial, case e entrevista final.

Suas tarefas aqui serão
  - planejar, desenvolver e documentar sistemas escritos em Python
  - fazer code reviews

## Local

Remoto (4ever, mas se quiser ir no escritório fique a vontade)

## Requisitos

**Obrigatórios:**
  - HTTP, REST
  - Python (flask, Django, etc)
  - Git
  - mongodb ou outro banco NoSQL

**Desejáveis:**
  - conhecimentos em CI/CD (usamos GitLab)
  - AWS

**Diferenciais:**
  - projetos opensource

## Benefícios

- Salário competitivo
- Plano de carreira estabelecido
- Trabalhe de casa

**Diferenciais:**

- A vida é muito curta pra não emendar feriados
- Um dia por mês, fora fins de semana e feriados, pra vc fazer o que quiser (menos trabalhar)
- Nos preocupamos com seu bem-estar (inclui sua saúde mental)

## Contratação

PJ

## Como se candidatar

Por favor envie um email para raphaelsampaio@gmail.com com seu CV anexado - enviar no assunto: Vaga Backend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: raphaelsampaio@gmail.com

## Labels
- Python
- mongodb

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by r-trevisan** [comment]
Enviado!
