### ISSUE TITLE
[Blumenau-SC] Back-End Magento Developer na Trezo

### ISSUE THREAD

**Issue by dougfani** [backend-br/vagas#818]
## Descrição da vaga

Oferecemos as melhores soluções em Magento unindo criatividade, inovação e agilidade.
Acreditamos que eficiência + diversão = resultado.
Se você também acredita nisso, venha falar conosco!

## Local

Remoto ou Escritório, Blumenau - Itoupava Norte 

## Benefícios

- Seguro de vida
- Plano de saúde
- Plano odonto
- Refeição na empresa
- Auxílio educação
- Desconto em nossos clientes
- Convênio com SESC
- Convênio com a UNIASSELVI (desconto de 10% na mensalidade)

#### Diferenciais

- Café fresquinho o dia todo/dolce gusto
- Equipamentos novos
- Mesa grande e confortável
- Inglês In Company
- Dress code livre
- Pet friendly
- Xbox
- Park Gastronomia do Shopping Europeu
- Acesso a blogs, youtube, spotify, etc liberados
- Ser #trezoteam (família, café, biscoito/bolacha, bolos, pipoca etc)

## Requisitos

**Obrigatórios:**
- Conhecimento em Magento (M1 e M2)
- Conhecimento em MySQL
- Conhecimento JavaScript (Ajax, jQuery, Knokout.js)
- Conhecimento avançado do uso do git (merge, rebase, stash, branch, tag, cherry¬pick)
- Consolidado conhecimento em: Orientação a objetos, Padrão MVC e Design Patterns
- Conhecimento de arquitetura de software, princípios SOLID e refatoração
- Conhece sobre o grupo de interoperabilidade entre frameworks (PHP-FIG) e suas recomendações (PSRs)
- Conhecimento em CSS (básico), HTML, SQL, Linux
- Gosta de estudar e aprender
- Conseguir analisar um problema, pensando nas necessidades a serem contempladas computacionalmente, trazendo soluções viáveis

**Diferenciais:**
- Conhecimentos avançados em algum framework MVC
- Conhecimento ou participação em projetos com desenvolvimento web sendo em PHP ou não

## Contratação

CLT ou PJ

## Nossa empresa

Fundada em 2009 com foco total em tecnologia e-commerce, contamos hoje com mais de 100 clientes/projetos em sua base.
Especializada em desenvolver e prestar suporte a lojas virtuais utilizando a plataforma Magento, tem entre os principais clientes a Grendene, HB, Porta dos Fundos, Marabraz, Evoke, Melissa, Rider, Ipanema, Óculos Shop, Pichau Informática, Muller Eletrodomésticos, Decanter, entre outros.
Estamos entre os 5 maiores empresas de tecnologia Magento, motivo este que nos torna partner Magento.

Somos certificados Great Place to Work e estamos classificados na 19ª posição do Love Mondays na categoria PME de TI no Brasil, como empresa mais amada pelos colaboradores.
Oferecemos as melhores soluções em Magento unindo criatividade, inovação e agilidade. Acreditamos que: eficiência + diversão = resultado.

## Como se candidatar

Candidate-se em: https://vagas.hunterco.com.br/job/5c5b38e7ed558b000fef96ae?r=rltd

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
