### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na ACCOUNTFY

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#819]
### Sobre a empresa: ACCOUNTFY

Fundada em 2017, a ACCOUNTFY é uma plataforma SaaS de soluções integradas e com foco nas atividades de controladoria e planejamento financeiro que oferece: automatização das demonstrações financeiras (DRE, FC e Balanço), construção e acompanhamento do orçamento e forecast, elaboração e padronização de relatórios e dashboards, e automatização do processo de consolidação contábil. 

A ACCOUNTFY é uma ferramenta inovadora para profissionais das áreas de FP&A e Controladoria, de fácil operacionalização e compreensão, que também pode ser utilizada para incrementar a prestação de serviços por parte de consultorias financeiras e escritórios de contabilidade, além de padronizar o reporte de investidas para fundos de Private Equity e Venture Capital. Somos uma startup sediada no Cubo em São Paulo e recém investida da Redpoint eVentures.

### Descrição: Ocupações do cargo

Desenvolvedor FullStack com espírito de equipe e autonomia para fazer parte da nossa equipe em São Paulo para desenvolver e manter aplicação web (front-end e back-end). 

### Requisitos

- Interfaces Web (HTML, CSS e Javascript); 

- Integração com Sistemas e Serviços em Nuvem por APIs; 

- Desenvolvimento de APIs RESTFull;

- Experiência com Desenvolvimento JAVA (spring);

- Experiência com Bancos de Dados Relacionais Preferencialmente Mysql ou PostgreSQL;

- Experiência com CI/CD;

- Conhecimento em Angular 

É um diferencial o profissional ter conhecimento em, NoSQL Ruby e Python.

### Aptidões e qualidades

Gostamos de pessoas que trabalham com foco em resultados e que buscam por grandes possibilidades de crescimento profissional.

### Labels

Alocado
PJ
Senior

### Candidatar: http://bit.ly/accountfy_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
