### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor C++ na Audaces

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#82]
## Descrição da vaga

As a modern C++ Developer you'll use cutting edge computer graphics technology to provide fashion stylists with the most fantastic tool they have ever seen: IDEA 4D
Audaces Idea 4D is a unique design tool based on a mix of digital sculping and physics simulation techniques aimed at fashion stylists. Its main function is to speed up fashion product's development by reducing the time invested on prototyping and increasing the communication efficiency among the team.

Now we are focused on developing innovative and easy-to-use design tools that fashion stylists would just love to use. 

Profissional que esteja habituado a trabalhar com code review e desenvolvimento de API Rest/Json

## Local

Florianópolis

## Requisitos

**Obrigatórios:**

-Research on computer graphics areas such as: Computer based animation, Digital sculpting and Real time rendering;
-Come up with new functionalities and build them;
-Deliver high quality code;
-Help in crucial project's design decisions;
-Take part in product's decision.
-Working in small teams, following the lean & agile principles.
 -In comfortable and silent rooms 
 -Making use of automated tests and continuous integration (Jenkins)
- Pushing code into production in short intervals.
- Making frequent contact with other areas of the company, what will provide you a global vision of our business.
-You gotta be self-taught
-You are an experienced Modern C++ developer
-You like math :)
-You are a passionate programmer
-You like making the difference
-You're able to solve problems using accepted best practices and principles
-Willing to live in Florianópolis, Santa Catarina, Brazil
-Plus: some experience with computer graphics!

## Contratação

CLT 4500 a 5500

## Nossa empresa

A Audaces é referência mundial em inovação tecnológica para moda, desenvolvendo desde sistemas inteligentes a equipamentos para automação dos processos de confecção do vestuário.

## Como se candidatar

https://app.vulpi.com.br/audaces-automa-o/575?invited_by=9433

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
