### ISSUE TITLE
[Belo Horizonte] Líder Técnico na ALLUGATOR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#820]
### Sobre a empresa: Allugator

O Allugator é uma plataforma de acesso. Por meio do nosso site e aplicativo nossos usuários podem alugar e receber em casa produtos como GoPro, barraca, caixa de som, PS4, entre várias outras coisas. Acreditamos que as pessoas não precisam comprar nada para ter acesso a tudo e que o acesso está para a compra assim como a eletricidade esteve para as velas ou o Uber para o Táxi. 

Os produtos fornecidos vêm dos nossos investidores parceiros, que, além de estimular o consumo inteligente e sustentável, têm na Allugator uma rentabilidade muito acima da média, com baixíssimo risco de prejuízo. Uma das 10 Startups do Ano em 2017 e 2018 segundo o Startup Awards (ABStartups).

### Descrição: O que você vai fazer aqui:

Seu trabalho será entender nossas principais necessidades e traduzir isso em desenhos de soluções para o time de engenharia, orientando nossos engenheiros de software no que for necessário para alcançar essas soluções. **Em mais detalhes, seu trabalho será:**

Desenhar e arquitetar soluções para os diversos setores da empresa;
Liderar o time de engenharia de software;
Definir, a partir das prioridades estabelecidas pelo time de estratégia, as ações a serem executadas no período e designar responsáveis;
Orientar os membros do time quando necessário, seja acerca de priorização, divisão de atividades ou de questões técnicas;
Garantir o bom funcionamento da infraestrutura e a qualidade do produto em geral.

### O que esperamos de você:

Metodologias de gestão ágil;
Vontade insaciável de aprender coisas novas;
Interesse pelo ecossistema de startups;
Sinergia total com a cultura da Allugator, afinal queremos que você se sinta em casa aqui desde o seu primeiro dia!

### Desejável

Experiência com JavaScript, Node e React;

### ﻿Informações complementares:

Possibilidade de stock options;
Alto potencial de rápido crescimento;
Horário flexível;
Free snacks;
Happy hour.

### Labels

PJ
Alocado
Senior

### Candidatar: http://bit.ly/allugator1_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
