### ISSUE TITLE
[São Paulo / SP] Desenvolvedor Backend na Web Jump

### ISSUE THREAD

**Issue by diegocpires** [backend-br/vagas#821]
A Webjump está com uma oportunidade em aberto para a posição de Desenvolvedor PHP.
Este profissional irá atuar no desenvolvimento e manutenção de lojas virtuais na plataforma Magento.
Fará instalação e manutenção de extensões, customizações, desenvolvimento de módulos e integrações de sistemas ajudando no planejamento, desenvolvimento e implementação da plataforma.

**O que esperamos de você:**
·         Experiência com PHP;
·         Experiência com JavaScript / jQuery;
·         Experiência com MySQL;
·         Comprometimento com prazos e metas;
·         Empenho em buscar soluções criativas.

**Quem somos:**
Uma empresa de tecnologia focada em desenvolvimento de soluções para e-commerce com dinamismo e um sonho grande.

**O que valorizamos:**
·         Pensar e agir como dono;
·         Organização para tomada decisões;
·         Trabalhar como um time;
·         Ter disciplina e foco;
·         Não ter medo de mudar de direção quando outro caminho levar mais longe;
·         Melhoria contínua;
·         Jamais ser complacente.

Se você atende aos requisitos divulgados, vem fazer parte da nossa história!!

Enviar email para diego.pires@webjump.com.br

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
