### ISSUE TITLE
[Belo Horizonte] Engenheiro de Software na ALLUGATOR

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#822]
### Sobre a empresa: Allugator

O Allugator é uma plataforma de acesso. Por meio do nosso site e aplicativo nossos usuários podem alugar e receber em casa produtos como GoPro, barraca, caixa de som, PS4, entre várias outras coisas. Acreditamos que as pessoas não precisam comprar nada para ter acesso a tudo e que o acesso está para a compra assim como a eletricidade esteve para as velas ou o Uber para o Táxi. 

Os produtos fornecidos vêm dos nossos investidores parceiros, que, além de estimular o consumo inteligente e sustentável, têm na Allugator uma rentabilidade muito acima da média, com baixíssimo risco de prejuízo. Uma das 10 Startups do Ano em 2017 e 2018 segundo o Startup Awards (ABStartups).

### Descrição: O que você vai fazer aqui

Desenvolver soluções para os diversos setores da empresa, integrando o time de engenharia e participando das sessões necessárias para a metodologia de gestão escolhida.

### O que esperamos de você

Experiência com TypeScript, JavaScript, Node e React;
Vontade insaciável de aprender coisas novas;
Interesse pelo ecossistema de startups;
Sinergia total com a cultura da Allugator, afinal queremos que você se sinta em casa aqui desde o seu primeiro dia!

### Informações complementares

Possibilidade de stock options;
Alto potencial de rápido crescimento;
Horário flexível;
Free snacks;
Happy hour.

### Labels

PJ
Alocado
Pleno/Junior

### Candidatar: http://bit.ly/allugator2_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
