### ISSUE TITLE
[Minas Gerais] Analista de Testes na SYNC SOFTWARES

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#823]
### Sobre a empresa: SyncSoftwares

A Sync Softwares está no mercado a mais de 8 anos. Possuímos um ERP que se chama WebGlass e atendemos exclusivamente indústrias de vidro e vidraçarias, em todo território nacional e hoje com mais de 150 clientes. Nossa missão é oferecer soluções com excelência para o setor vidreiro, primando pelo desenvolvimento de nossos clientes para que concretizem todo seu potencial. 

Nossa visão para os próximos três a cinco anos é dobrar a quantidade de colaboradores, triplicar a quantidade de clientes, termos produtos com tecnologia de ponta e termos concluído a nossa nova sede. Nossos valores são a colaboração, comprometimento, melhoria contínua, qualidade, responsabilidade e satisfação do cliente.

### Descrição: Ocupações do cargo

Aqui você será responsável por desenvolver e realizar os testes dos sistemas desenvolvidos pela equipe de analistas, realizando o levantamentos dos erros e direcionando para correção. Você também irá fazer as especificações, planejamento e execução de testes de toda a piramide (Testes unitários, componentes, integração, api e automatizados).

### Benefícios

Além de oferecermos um ambiente descontraído que permitirá seu crescimento e evolução, você vai ter também:

Vale transporte ou auxílio combustível
Vale Refeição
Plano de saúde coparticipativo
Plano odontológico coparticipativo

### Aptidões e qualidades

Boa capacidade de aprendizagem para absorver o conhecimento de negócios.
Perfil de liderança.
Boa capacidade de abstração.
Orientação ao negócio do cliente.
Proatividade.
Conhecimento dos conceitos de teste de software, unitário, integrado, funcional, caixa branca, caixa preta.

### O que esperamos de você?

Esperamos que você seja comprometido, colaborativo, responsável e que busque sempre aperfeiçoar os seus conhecimentos a cada dia. Estamos em crescimento e queremos que você venha conosco. Para isso, é de extrema importância que você tenha grande empatia com nossos clientes e por fim, que nos auxilie a ter um produto de máxima qualidade.

### Labels

CLT
Alocado
Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
