### ISSUE TITLE
[São Paulo] Desenvolvedor Pleno Ruby on Rails

### ISSUE THREAD

**Issue by ralugli** [backend-br/vagas#824]
**Sobre a CreditCorp:**

Somos uma empresa que utiliza tecnologia inovadora, bem como recursos de um Fundo de Investimento em Direitos Creditórios (FIDC), para facilitar a vida de quem necessita antecipar 
recursos por intermédio do desconto de duplicatas dos sacados parceiros.

Saiba mais em: http://www.creditcorp.com.br

VAGA PRESENCIAL
Estamos localizados em:  Av. Nove de Julho, 5143 - Conjunto 81 - Jardim Paulista - São Paulo

**Requerido:**
- Experiência de pelo menos 2 anos com Ruby on Rails
- Experiência com desenvolvimento de APIs REST
- Fluência com HTML, CSS e JavaScript
- Conhecimentos em bancos de dados relacionais
- Conhecimentos em Testes automatizados
- GIT flow

**Diferenciais:**
- Experiência com React Native/ Desenvolvimento mobile
- Conhecimentos em Docker
- Conhecimentos em VueJS

Enviar currículo com Pretenção Salarial / LinkedIn para rafael@creditcorp.com.br
Com o assunto: Vaga Fullstack Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
