### ISSUE TITLE
[Belo Horizonte] - Desenvolvedor na itexto

### ISSUE THREAD

**Issue by kico-itexto** [backend-br/vagas#825]
### Sobre nós

Nosso objetivo é ajudar outras empresas e indivíduos a desenvolver softwares com maior qualidade e eficiência, o que é feito através dos nossos serviços de consultoria, treinamentos e desenvolvimento. Somos referência nacional quando o assunto é Java, Groovy, Grails e Spring, o que não quer dizer que apenas trabalhemos com estas tecnologias. Dado que acreditamos no imenso valor do legado, da experiência prévia dos nossos clientes e da pesquisa, o contratado irá lidar com um stack bastante variado.

Estamos experimentando forte crescimento, razão pela qual provemos ao contratado experiência real de mercado pois nossos clientes atuam nas mais variadas áreas: e-commerce, financeira, gestão, saúde, educação, desenvolvimento de software, mineração, engenharia, entretenimento, startups e outras.

Há também alguns produtos nos quais estamos trabalhando neste momento, focados em desenvolvedores, e que já se encontram em produção (como o Grails Brasil, /dev/All, Spring Brasil, Javascript Brasil, Formação itexto e nossos Guias).

Nos conheça melhor acessando nosso site: https://www.itexto.com.br

### Quem estamos buscando

Esperamos que você já possua alguma experiência na implementação ou manutenção de sistemas computacionais.

A tecnologia mais importante para nós são seus conhecimentos de ciência da computação, o que envolve lógica de programação, algoritmos, boa compreensão de conceitos fundamentais como sistemas operacionais, bancos de dados (não necessariamente relacionais), paradigmas de programação (pelo menos procedural e orientação a objetos) e estruturas de dados. Não buscamos um especialista, mas sim um generalista que, como nós, ame programar e projetar soluções. Se não ama programar seu lugar não é aqui.

Apesar de buscarmos generalistas, neste momento é importante que você saiba o que estamos usando em nossos projetos: Spring, Grails, JSF/CDI/JPA e um pouco de Node.js. 

Naturalmente você não precisa conhecer todas estas tecnologias, mas o conhecimento de ao menos parte destas será considerado como importante diferencial neste momento.

O aspecto pessoal é levado em consideração e sem dúvidas é fator fundamental. Como nosso dia a dia envolve pesquisa constante e intensa, em nossa conversa inicial avaliaremos o modo como seu interesse pelas áreas da computação se manifestam. Já adiantamos: se você não gosta de ler e estudar, seu lugar não é aqui.

#### Diferenciais importantes

O conhecimento de alguma (não precisa ser todas) das tecnologias a seguir será considerado como diferencial em nosso processo de seleção:

* Spring Framework.
* Groovy e Grails.
* Java EE (JSF, CDI, JPA)
* Node.js

Apesar desta vaga ser voltada para o desenvolvimento backend, sempre há algum trabalho a ser realizado no frontend também. Sendo assim é interessante que você conheça algumas das tecnologias que usamos em nosso dia a dia:

* Angular
* Vue.js
* Padrões web
* Ionic
* Cordova

#### Formação mínima esperada
Sobre sua formação, esperamos que você se encaixe em um dos casos abaixo:

* Ter finalizado recentemente (ou estar finalizando no próximo semestre) o curso de Ciência da Computação ou áreas correlatas (Sistemas de Informação, Engenharia da Computação, etc).
* Ter acabado de concluir um curso técnico relacionado a Tecnologia da Informação.

#### Requisitos essenciais

* Já ter realizado estágio na área.
* Pelo menos dois anos de experiência comprovada na área de desenvolvimento de software.
* Ter boa capacidade de leitura em inglês.
* Conhecimentos técnicos acima mencionados (de acordo com seu perfil).
* Gostar de lidar com pessoas.
* Estar antenado com o que ocorre no mercado de desenvolvimento de software.
* **Residir em Belo Horizonte ou região**

#### O que você fará aqui

* Implementação de novas funcionalidades em sistemas computacionais.
* Evolução de sistemas legados.

Para se inscrever preencha o formulário que disponibilizamos neste link: https://www.itexto.com.br/site/trabalhe-conosco/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
