### ISSUE TITLE
[São Paulo] Pessoa Desenvolvedora Node na [Gupy]

### ISSUE THREAD

**Issue by jtlimo** [backend-br/vagas#826]
**SOBRE A GUPY**

Você também se incomoda com a forma como os processos seletivo ainda são feitos? Nesse momento tão importante da vida das pessoas, queremos que os recrutadores e candidatos sejam protagonistas de uma experiência simples, prazeirosa e realizadora. Ainda há muito o que fazer, mas é para isso que a Gupy nasceu em 2015!

Somos o principal software de recrutamento e seleção do Brasil e uma das startups de RH que mais cresce no país.

Nessa jornada, fomos acelerados pela Wayra em 2016, investidos pela Yellow Ventures e Canary em 2017 e residentes no Google Campus em 2017 e novamente em 2018. Formamos um time incrível que nos ajudou a alcançar centenas de empresas e mais de 1 milhão de candidatos em nossa plataforma.

E é esse time que nos faz crescer 20% todo mês. Aumentamos tanto de tamanho que já mudamos 6 vezes de escritório e somos mais de 50 Gupiers apaixonados. Apaixonados por transformar um mercado inteiro para melhor, aprendendo muito e se divertindo no caminho.

Somos a startup que incomoda empresas antigas e inspira concorrentes novos. E vamos continuar sendo a número 1.
O melhor disso tudo: transformar a vida das pessoas desburocratizando o recrutamento e desafiando o status quo incansavelmente por meio de nossa tecnologia e metodologia.

**DESCRIÇÃO DA VAGA**

Somos movidos por grandes desafios e precisamos de pessoas que amem aprender constantemente, que sonhem grande e que tenham muita gana para nos ajudar a transformar a GUPY na melhor e maior empresa de Recrutamento Tech do Brasil.

Estamos crescendo o time e tornando o nosso produto cada dia mais poderoso, por isso estamos à procura de pessoas cheias de gana, que amem tecnologia, que sejam fascinadas por aprender coisas novas e que queiram fazer parte de algo muito maior! Que tal fazer parte disso?

**Benefícios que só a Gupy te oferece**

Trabalhar e trocar conhecimentos diários com um time incrível, de uma cultura forte, que faz campeonatos de Just Dance nas sextas-feiras com ou sem cerveja (você escolhe);
Tomar #CaféDaManhãDeHotel uma vez por semana;
Trabalhar em uma startup que preza pelo trabalho em equipe, diversidade e acredita que a diferença é um dos maiores fermentos para nosso crescimento;
Ter contato com mentores internacionais, especialistas na sua área;
Criar um produto que brilha os olhos de clientes e usuários;
Fazer a diferença para as empresas e candidatos, através de inovação;
Ajudar a colocar a pessoa certa no lugar certo;
Aprender e sempre se divertir no processo!

**RESPONSABILIDADES E ATRIBUIÇÕES**

Como pessoa desenvolvedora você vai:

- Desenvolver APIs usando Node.js;
- Continuous Integration e Deployment na AWS e Kubernetes;
- Manipular dados usando PostgreSQL, Redis, Elastic Search e banco de dados de documentos;
- Definir arquitetura de aplicações e micro serviços.

**REQUISITOS E QUALIFICAÇÕES**

Como requisitos básicos, você deve ter:

- Mínimo de 4 anos de experiência com desenvolvimento de software;
- Sólido conhecimento em testes de unidade / funcionais / integração;
- Aplicar boas práticas de engenharia de software.

**Você se destaca, se tiver:**

- Conhecimento em Node.JS;
- Hábito de fazer unit tests no dia a dia;
- Hábito de fazer refatoração no dia a dia.

**INFORMAÇÕES ADICIONAIS**

E tem mais:

- Horário flexível;
- Vale alimentação;
- Plano de Saúde;

Para se inscrever na vaga acesse o link: https://vempra.gupy.io/jobs/26940

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
