### ISSUE TITLE
 [Belo Horizonte] Desenvolvedor Backend Laravel [DON ADVICE]

### ISSUE THREAD

**Issue by pmagalhaesa** [backend-br/vagas#827]
**Conhecimentos**
-Linguagem PHP 
-Framework Laravel (obrigatório)
-Criação de APIs REST
-Arquitetura MVC 
-Banco de Dados MYSQL
-Linguagem SQL 
-ORM

**Diferenciais**
-Experiência com normalização de banco de dados
-Composer 
-GIT  
-Javascript
-Vue.js
-Linux

**Aptidões e qualidades**
Comprometimento com prazos e metas
Vontade de aprender 
Proatividade
Trabalho em equipe

**Formação** 
Curso superior relacionado a Tecnologia da Informação (Ciência da Computação, Sistemas de Informação e afins) - concluído ou em andamento

**Horário**
De segunda a sexta, de 9 ás 18h 

**Local**
Belo Horizonte-MG

Se você atende aos requisitos, venha fazer parte da nossa equipe!!
Envie seu curriculo por email para  [paula@donadvice.com](mailto:paula@donadvice.com) com o assunto VAGA BACKEND

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
