### ISSUE TITLE
[São Paulo] Software Engineer na Xerpa

### ISSUE THREAD

**Issue by Leocardoso94** [backend-br/vagas#828]
## Descrição da vaga

Estamos em busca pessoas para trabalhar conosco aqui na Xerpa. Seu trabalho aqui vai ser atuar lado lado com designers e engenheirxs para construir um produto que impacta a vida de diversas pessoas.

Aqui na Xerpa nossos principais serviços são escritos em Elixir, mas não se preocupe **não é requisito saber Elixir é apenas um diferencial**, nossa busca é por pessoas que estão afim de aprender e ensinar durante o dia-a-dia.

## Local

Av. Brg. Faria Lima, 1912 - Jardim America, São Paulo - SP, 05402-600

## Benefícios

- Academia/Gympass
- Seguro de Vida
- Plano de Saúde
- VT/VR

## Requisitos

**Desejáveis:**
- Experiência no desenvolvimento de aplicações web. Aplicativos da web de médio a grande porte e multicamada.
- Conhecimento de bancos de dados relacionais e não relacionais e SQL.
- Conhecimento de design de API e sistemas backend distribuídos.
- Interesse em programação funcional.
- Você adora trabalhar em um ambiente em que você experimenta e interage constantemente.

**Diferenciais:**
- Experiência com Elixir é um bônus.

## Contratação

CLT a combinar

## Nossa empresa

E se você acordasse para trabalhar todos os dias sabendo que suas habilidades estão melhorando a vida de milhares de pessoas criando experiências de trabalho incríveis? Isto é ser Xerpa. Nós somos a transformação que o Brasil precisa, com muita tecnologia e propósito!

## Como se candidatar

Por favor envie um email para lsilva@xerpa.com.br e lsousa@xerpa.com.br com seu CV e/ou Linkedin - enviar no assunto: Vaga Back-End

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by AndersonMarquess** [comment]
Enviado.

**Comment by pabrrs** [comment]
Enviado :smile:

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
