### ISSUE TITLE
[Belo Horizonte] Desenvolvedor fullstack na Starline

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#83]
## Descrição da vaga

Não se preocupe se você não tiver experiência em Python. Acreditamos que o melhor desenvolvedor é aquele que sabe se adaptar de forma rápida as necessidades do mercado, e por isso, sabe desenvolver bem independente de linguagem.

Se você tiver o perfil, entre em contato com a gente.

## Local

Belo Horizonte

## Requisitos

**Obrigatórios:**

-Seja formado ou cursando Sistemas de Informação, Ciência da Computação, Engenharia de Software ou cursos afins
-Tenha forte conhecimento em lógica de programação
-Tenha conhecimento em alguma linguagem de desenvolvimento
-Seja entusiasmado em aprender sobre novas tecnologia

**Desejáveis:**

-Python e Django
-HTML5
-CSS
-Angular
-Agile (Pair Programming, XP, Scrum, Integração/Entrega Contínua)
-TDD
-Design Patterns
-REST
-Linux
-Docker
-S3 - AWS
-MySQL
-Conhecimento de inglês

## Contratação

CLT 3000 a 4000

## Detalhes da vaga:

-40 horas semanais
-Vale transporte
-Vale refeição
-Plano de saúde
-Plano odontológico
-Lanche na empresa
-Venha trabalhar de bermuda, chinelo, do jeito que quiser, inclusive na entrevista (se você tiver vontade ;) )
-Trabalho totalmente focado em Agile - Pouca burocracia e alto desempenho

## Nossa empresa

Nós somos líderes na América Latina em gestão de provas e seguimos firmes na missão de melhorar índices educacionais e contribuir para a melhoria da educação no Brasil. Nesta caminhada, já simplificamos a logística e aplicação de mais de cinco milhões de provas e atendemos a mais de 700 mil alunos. Em 2016, fomos reconhecidos pelo Global EdTech Awards como uma das três startups mais inovadoras em tecnologia educacional da América Latina!
 
 Mais do que a tecnologia de ponta e soluções criativas para diferentes instituições de ensino, nós contamos com um recurso valioso: uma equipe altamente qualificada, motivada e, principalmente, divertida. Interessado em fazer parte? Confira nossas vagas!

## Como se candidatar

https://app.vulpi.com.br/starline-tecnologia/574

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
