### ISSUE TITLE
[Goiânia] Ruby Developer na CAST GROUP

### ISSUE THREAD

**Issue by Pompeu** [backend-br/vagas#830]
## Descrição da vaga
Trabalhar com Ruby, Rails, Sinatra, SASS/CSS, Oracledb, PostgreSQL, AngularJS, Jquery e outros..

## Local
Alocado no cliente – Jardim Goias Goiânia

## Benefícios
* Plano de saúde
* Seguro de vida
* VR ou VA
* VT
* Pontos Good (valor disponível para conversão em benefícios, como vale combustível, VA, VR, reembolso para cursos, etc.)

#### Diferenciais
* horário flexível
* plano de carreira
* oportunidade de trabalhar com uma equipe massa e diversificada

## Requisitos
**Obrigatórios:**
*  5 (cinco) anos de experiencia em desenvolvimento de software; - Ferramentas de controle de versao GIT e SVN; - Padroes de comunicacao de aplicacoes distribuidas REST e SOAP; - Dados estruturados em XML ou JSON; - Atividades realizadas em projetos de desenvolvimento e manutencao de software com metodos ageis; - 03 (tres) anos de experiencia como programador de sistemas em tecnologia Ruby com SGBD PostgreSQL; - Implementacao de codigo back-end e front-end; - Modelagem e estruturacao de dados; - Conhecimento de tecnologias como Angular, Javascript, HTML e CSS, dados estruturados em XML ou JSON; - Conceitos de interfaces de usuario e User eXperience (Experiencia do Usuario).

**Desejáveis:**

* Facilidade em trabalho em equipe

## Contratação
CLT com salário a combinar.

## Nossa empresa
Com 28 anos de mercado, a Cast group é uma empresa nacional de Tecnologia da Informação e automação com larga experiência em grandes projetos para as áreas privada e pública, que atua com consultoria e soluções de TI e TA.

Hoje, a Cast group é reconhecida por seus mais de 320 clientes, especialmente nas áreas de finanças, indústrias e serviços, como, Banco do Brasil, Cielo, Datasus, Vale, Cemig, Gerdau, EDP, Eletrobrás, Grupo Petrópolis, Atento, Renault, Randon, Bosh, Ipiranga Agroindustrial, DrogaRaia e Banco Central do Brasil.

## Como se candidatar
Por favor, envie um email para [leandro.vteixeira@castgroup.com.br](mailto:leandro.vteixeira@castgroup.com.br) com seu CV anexado - enviar no assunto: Ruby Goiânia Developer

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: [leandro.vteixeira@castgroup.com.br](mailto:leandro.vteixeira@castgroup.com.br)

## Labels
* Alocado
* CLT

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
