### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Back-End na QUEIMA DIÁRIA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#831]
### Sobre a empresa: Queima Diária

Maior Startup de Home Fitness da América Latina!

### Descrição: Ocupações do cargo

Estamos em busca de um profissional curioso que queira ser e fazer a diferença no projeto. Os projetos já estão em operação, mas também desejamos que essa pessoa faça parte dos projetos em start. Buscamos profissionais que tenham um perfil focado e atual que saiba pensar fora da caixa e desenvolver projetos de maneira criativa e eficaz.

### Benefícios

- Vale Refeição ou alimentação; R$21,35/dia - Lanche Diário
- Vale Transporte; 
- Plano de Saúde;( Unimed Enfermaria) Descontando somente a coparticipação.
- Plano odontológico; Sem desconto algum 
- Politica de ensino de línguas (inglês) na própria empresa onde o profissional terá uma ajuda de custo de 50%.
- Acesso à plataforma
-Horário flexível (chegada até as 10h)
- No DressCode
- Flexibilidade do horário de almoço 1h até 2h

### Aptidões e qualidades

Precisa ser uma pessoa criativa, organizada e com foco em resultados. Um profissional que seja capaz de se reiventar, e propor novas ideias a todo momento.

De atitude e com vontade de crescer.

### Informações da empresa

A Queima Diária é uma Startup em constante crescimento, que desde o seu inicio em meados 2015 vem crescendo e ganhando cada vez mais espaço em seu mercado. Sua proposta é promover o bem estar das pessoas, criando um espaço de conhecimento e valorização da vida saudável e nutrição. Tudo isso através de uma plataforma interativa e intuitiva que fornece diferentes programas e treinos para públicos de diversos perfis. Uma empresa inovadora, busca profissionais inovadores, criativos e que pensem fora da caixa para compor sua equipe.

### Informações complementares

É fundamental que esta pessoa seja fera em JavaScript e Node.Js, mas também se tiver boas noções de stream video, meios de pagamento e act tv. Abertura para novas linguaguens e noções de devops e ows também é bem legal.

### Labels

Alocado
Master/Pleno/Junior

### Candidatar: http://bit.ly/queimaback_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
