### ISSUE TITLE
[Belo Horizonte] PHP Back-end Developer [DialHost]

### ISSUE THREAD

**Issue by flaviohcardoso** [backend-br/vagas#832]
## Descrição da vaga

Se você é um desenvolvedor faminto por desenvolver e otimizar produtos em um processo de ciclo contínuo e evolutivo, esta pode ser sua equipe.
Nós somos uma empresa que presa a evolução dos nossos produtos juntamente com um atendimento eficaz a todos os nossos clientes oferecendo soluções de datacenter que atendam suas necessidades de forma simples e transparente. Por isto estamos buscando um desenvolvedor que possua empatia e comprometimento para auxiliar nossos colaboradores e clientes discutindo e buscando as melhores opções para garantir uma experiência excepcional no atendimento ao cliente. 

Acreditamos que em nosso time, você não trabalhará sozinho e que um problema nunca é somente de um colaborador, ele é de todos da empresa.
 
O que esperamos dos candidatos:

- Ter boa comunicação e disponibilidade para discutir insitentemente melhorias aos nosso produtos.
- Paixão por trabalho em equipe ainda que seja com poucos colaboradores, pois levamos a sério a colaboração entre os nossos times.
- Leitura, escrita e fala corretas e objetivas.
- Ouvir é outra habilidade chave, pois os feedbacks dos clientes devem ser levados a sério e discutidos em equipe para melhorarem os nossos produtos.
- Ter habilidade para desenvolver uma aplicação baseada em API para integrações de diversos aplicativos.
 
## Local

Presencial - Belo Horizonte - California

## Benefícios
Não ter chefe :)
Uma equipe de alto nível, comprometidas e colaborativa.
Salário compatível com o mercado.
Plano de Saúde.
Vale Refeição.
Vale Transporte.
Lanche na empresa.
Ambiente agradável.
Horário Flexível.
Estilo próprio para trabalhar.

## Requisitos

**Obrigatórios:**
- PHP intermediario;
- Framework backend MVC (em especial Laravel Lumen);
- Conhecimento em desenvolvimento de API em REST;
- Experiência com utilização do Git;
- Desejável conhecimentos teóricos e práticos em Programação Orientada a Objetos;

## Contratação
CLT

## Como se candidatar
Se candidatar no site http://jobs.dialhost.com.br/o/php-backend-developer
Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
