### ISSUE TITLE
[Belo Horizonte] C# .NET - Back-End Developer na [Plan B Comunicação]

### ISSUE THREAD

**Issue by eliasdouglas** [backend-br/vagas#833]
# Descrição da vaga
Desenvolver projetos de tecnologia para web desde a concepção até o acompanhamento e evolução em produção. Programação, análise, performance e comunicação.

Utilizamos Ruby on Rails, ASP.NET MVC (C#) e PHP como principais plataformas de desenvolvimento, mas o time é incentivado a explorar e testar novas tecnologias para desenvolvimento, buscando mais agilidade, performance e diversão. :)

## Local
Presencial - Belo Horizonte - Santo Agostinho

## Requisitos
- Experiência em .Net
- Experiência com banco de dados MySql/MSSql
- Aplicar boas práticas de engenharia de software

## Desejável
- Conhecimento de processos ágeis (Scrum)
- Conhecimento em Ruby on Rails
- CSS/SASS
- DevOps e/ou ChatOps

## Contratação
CLT ou PJ (negociar)

# Como se candidatar
Envie seu currículo para rh@planb.com.br com o título _Dev Backend_

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
