### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Java na DATA BRIDGE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#834]
### Sobre a empresa: Data Bridge

A Data Bridge é uma fábrica de software que desenvolve nas seguintes tecnologias: - Java web com spring boot, hibernate e thymeleaf (jquery, bootstrap) - Ionic com Angular 2 - PHP com Laravel - Projetos Drupal (PHP)

### Descrição: O que você fará na Data Bridge?

Somos uma Fábrica de Software que tem projetos bem bacanas e interessantes. Aqui você nos auxiliará na manutenção dos sistemas existentes, criação de projetos e otimização do que já temos criado. Venha preparado para codificar e desenvolver soluções que irão mudar a vida de muita gente.

### Requisitos que você precisa atender:

Conhecimento em Java;
Spring (boot, security, etc);
Hibernate;
Thymeleaf (jquery, bootstrap);
Servidor Wildfly;
Bancos Oracle ou Postgres

### Diferenciais que vão contar pontos para você:

Ionic com Angular 2;
UML;
PHP;
Laravel;
Drupal

### Você terá benefícios como:

Estacionamento gratuito;
Lanche fornecido manhã e tarde;
Lanchonete;
Espaço de Co-Working na Pampulha;
No dress-code;
Flexibilidade de horário

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Auxiliar na criação de uma equipe de alta performance.

### Labels:

Alocado
Pleno/Senior

### Candidatar: http://bit.ly/databridge_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
