### ISSUE TITLE
[São Paulo, Vila Olímpia] Desenvolvedor(a) Full Stack Java Sênior na VEE DIGITAL S. A.

### ISSUE THREAD

**Issue by sergiobr** [backend-br/vagas#835]
Vaga: Desenvolvedor(a) Full Stack Java 
Tipo: CLT
Experiência: Sênior 

☛ Responsabilidades
⟹ Estar atento à novas tecnologias que podem ser usadas no desenvolvimento dos produtos VEE, buscando e validando as inovações para aplicá-las em diferentes projetos e situações.
⟹ Prover orientação técnica à equipe de desenvolvedores nas diferentes tecnologias utilizadas, avaliando e promovendo boas práticas de programação, cobertura de testes e automatização de entregas.
⟹ Participar ativamente durante as fases de concepção de novos produtos e funcionalidades. Entendimento das regras de negócio, análise de requisitos, validação da viabilidade técnica e discussão com toda a equipe a fim de encontrar as mais efetivas soluções para cada situação.
⟹ Colocar em prática as tecnologias e frameworks utilizados através da implementação de POCs e da participação na programação das funcionalidades.

## Local

Escritório São Paulo - Vila Olímpia
## Benefícios

⟹ Remuneração compatível com o mercado
⟹ Horário flexível;
⟹ Sem dresscode;
⟹ Ambiente descontraído;

☛ Requisitos obrigatórios
⟹ Ter em torno de 6 anos de experiência 
⟹ Desenvolvimento em Java EE 
⟹ Ferramentas de Integração/Entrega Contínua(CI/CD), Git, práticas de XP (SCRUM/Agile), testes TDD/BDD, Design Patterns, OO, design de APIs, REST e Micro serviços
⟹ Bancos de dados Relacional
⟹ Inglês avançado para leitura

☛ Soft skill: 
⟹ Excelente trabalho em equipe 
⟹ Desapego por tecnologias (“explain to me like I’m five years old”: procuramos uma pessoa que não seja apegada a qualquer linguagem de programação ou tecnologia, que esteja aberto a desenvolver conforme nossas necessidades). 
⟹ Comunicação tranquila e pacífica (todos aqui temos ótimas ideias e é necessário ouvir e respeitar cada uma delas).

☛ Nossa stack (Java)
⟹ Java EE
⟹ JSF (Java Server Faces)
⟹ JAX-RS
⟹ Hibernate
⟹ Spring
⟹ Spring boot
⟹ WildFly 10.x acima
⟹ MySQLdb

☛ Desejável
⟹ Familiaridade Amazon AWS
⟹ Experiência com meios de pagamento
⟹ Familiaridade com ambiente Linux

☛ Diferenciais
⟹ Desenvolvimento de aplicações móveis (Android/iOS)

## Contratação

CLT ou a combinar
## Nossa empresa

A Vee surgiu com o objetivo de romper o oligopólio do mercado de benefícios do Brasil: um sistema antiquado, burocrático, acomodado e amarrado aos grandes bancos, a configuração atual impede a criação de um produto flexível, ágil e menos custoso para empresas, colaboradores e estabelecimentos.
Em breve resumo, criamos uma plataforma de baixo custo, com transações p2p, extinguindo intermediários do processo de pagamento. Conseguimos assim resolver os principais downsides do sistema atual para todos os stakeholders (empresas, colaboradores e dos estabelecimentos), oferecendo baixíssimos custos, além de excelente user experience aliado a um produto altamente customizável, características notoriamente inexistentes no atual panorama desse segmento.
Em números, o mercado PAT movimenta cerca de R$85 bilhões por ano. Já o mercado de benefícios como um todo movimenta R$150 bilhões por ano. Com a reforma trabalhista, existem previsões que colocam esse mercado no patamar de R$450 bilhões dentro dos próximos 5 anos.

Que tal fazer parte dessa revolução?!

☛ Cultura da empresa:

⟹ Você terá muita liberdade para propor novas ideias, novas soluções;
⟹ Não temos apegos a hierarquias, a melhor ideia sempre vence;
⟹ Queremos desenvolvedores(as) que prezam pela qualidade do código.

☛ Onde ficamos
Vila Olímpia
Rua Funchal, 538 - 4º andar – sala 42/44
São Paulo

☛ Políticas de inclusão
Somos uma empresa jovem favorável a diversidade, queremos uma empresa diversa, pois somente, assim, criaremos uma experiência de pagamento que envolvam todas a perspectivas.

☛ Políticas de não discriminação
Qualquer intolerância por motivos raciais, religiosos ou preferência sexual não serão toleradas na Vee.

Oferecemos uma grande oportunidade de aprendizagem e crescimento profissional, em conjunto com a expansão da empresa e de fazer parte de um time inovador e eclético de desenvolvedores(as), ajudando a criar uma nova forma para realizar transações financeiras.
## Como se candidatar

Por favor preencha o formulário em https://goo.gl/forms/acVjzqn4EvwssQh83

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
