### ISSUE TITLE
[Campinas/SP] Back-End Developer Node.js na inGaia

### ISSUE THREAD

**Issue by stefanobaldo** [backend-br/vagas#836]
## Descrição da vaga
Estamos à procura de um Desenvolvedor Back-End com foco em Node.js para juntar-se à nossa equipe de TI. Você será inicialmente responsável pela manutenção e desenvolvimento back-end de novas funcionalidades, com foco em Node.js.

## Local
Av. José de Souza Campos, 1549 - Cambuí, Campinas - SP,

## Benefícios
* Plano de saúde
* Seguro de vida
* Vale Refeição
* Vale Transporte
* Mesa de Sinuca
* Lanches e festas de aniversário.
* Apoio Pass (Suporte Pessoal).

## Responsabilidades e atribuições:
* Participar do o ciclo de vida dos produtos, com foco em desenvolvimento back-end;
* Efetuar manutenções em códigos existentes, bem como desenvolver novas funcionalidades;
* Gerar códigos limpos através da utilização de boas práticas de desenvolvimento - Clean Code;
* Produzir códigos reutilizáveis, testáveis e eficientes;
* Testar, testar, testar.

## Requisitos
**Obrigatórios:**

* Proficiência em Javascript (Node.js, especificações mais recentes do ECMAScript)
* Microsserviços com Node.js
* REST APIs com NodeJS (Koa, Express.js)
* Caching (Redis)
* Git (branches, git flow)
* Banco de dados: Relacionais (MSSQL, MySQL, Postgres, etc) e NoSQL (MongoDB)
* Testes: Mocha, Chai, Sinon
* Libs: ESLint, Sequelize, Mongoose, Swagger
* Ferramentas: Npm, ESLint
* Docker

**Diferenciais:**

* Serverless com Node.js
* Filas, tópicos e comunicação assíncrona entre serviços (AWS SQS, Google Pub/Sub, RabbitMQ, etc)
* ElasticSearch
* GraphQL
* Experiência com metodologias ágeis (SCRUM, Kanban, Lean, etc)

## Contratação
CLT

## Nossa empresa
* **Somos a inGaia:**  A maior empresa de tecnologia do setor imobiliário, com uma plataforma de soluções completa para os profissionais deste mercado. Ajudamos mais de 3 milhões de proprietários, compradores e imobiliárias a fecharem negócios.
* **Nós nascemos para construir um novo mercado imobiliário:** Com soluções que geram mais valor e ajudam os corretores de imóveis a trabalharem de forma mais profissional e eficiente.
* **Nosso time:** Performances individuais são sempre valorizadas, mas não toleramos individualismo e falta de ética. Trabalhamos juntos e somos positivos em todas as nossas atitudes, o mi-mi-mi não faz parte da nossa cultura.

## Como se candidatar
Por favor envie um email para [stefano.baldo@ingaia.com.br](mailto:stefano.baldo@ingaia.com.br) com seu CV anexado. Enviar no assunto: Back-End Developer - GitHub

## Labels
* Alocado
* CLT
* Júnior
* Pleno
* Sênior
* Node.js

**Comment by pabrrs** [comment]
Enviado :smile:

**Comment by Assisneto** [comment]
Remoto?

Em seg, 18 de fev de 2019 00:04, Paulo Barros <notifications@github.com
escreveu:

**Comment by guilhermeoa07** [comment]
Todos os "Obrigatórios" também são validos para Júnior?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
