### ISSUE TITLE
[Campinas/SP] Tech Lead (Líder Técnico) de Back-End Node.js na inGaia

### ISSUE THREAD

**Issue by stefanobaldo** [backend-br/vagas#837]
## Descrição da vaga
Estamos à procura de um Líder Técnico de Back-End com foco em Node.js para juntar-se à nossa equipe de TI.
Você será responsável pela liderança e condução técnica de uma equipe de desenvolvedores back-end.

## Local
Av. José de Souza Campos, 1549 - Cambuí, Campinas - SP,

## Benefícios
* Plano de saúde
* Seguro de vida
* Vale Refeição
* Vale Transporte
* Mesa de Sinuca
* Lanches e festas de aniversário.
* Apoio Pass (Suporte Pessoal).

## Responsabilidades e atribuições:

* Participar do o ciclo de vida dos produtos, com foco em desenvolvimento back-end;
* Liderar e conduzir tecnicamente as equipes de back-end, com foco em Node.js;
* Definição de padrões de desenvolvimento;
* Guiar tecnicamente as equipes de back-end;
* Efetuar Code Review;
* Participação em eventos, criação de conteúdo, criação e manutenção de projetos open-source e outras atividades que aumentem a visibilidade do nosso time de engenharia;

## Requisitos

**Obrigatórios:**

* Forte Proficiência em Javascript (Node.js, especificações mais recentes do ECMAScript)
* Microsserviços com Node.js
* Serverless com Node.js
* REST APIs com NodeJS (Koa, Express.js)
* Caching (Redis)
* Git (branches, git flow)
* Banco de dados: Relacionais (MSSQL, MySQL, Postgres, etc) e NoSQL (MongoDB)
* Filas, tópicos e comunicação assíncrona entre serviços (AWS SQS, Google Pub/Sub, RabbitMQ, etc)
* Testes: Mocha, Chai, Sinon
* Libs: ESLint, Sequelize, Mongoose, Swagger
* Ferramentas: Npm, ESLint
* Docker
* Experiência com metodologias ágeis (SCRUM, Kanban, Lean, etc)

**Diferenciais:**

* ElasticSearch
* GraphQL

## Contratação

CLT

## Nossa empresa

* **Somos a inGaia:**  A maior empresa de tecnologia do setor imobiliário, com uma plataforma de soluções completa para os profissionais deste mercado. Ajudamos mais de 3 milhões de proprietários, compradores e imobiliárias a fecharem negócios.
* **Nós nascemos para construir um novo mercado imobiliário:** Com soluções que geram mais valor e ajudam os corretores de imóveis a trabalharem de forma mais profissional e eficiente.
* **Nosso time:** Performances individuais são sempre valorizadas, mas não toleramos individualismo e falta de ética. Trabalhamos juntos e somos positivos em todas as nossas atitudes, o mi-mi-mi não faz parte da nossa cultura.

## Como se candidatar

Por favor envie um email para [stefano.baldo@ingaia.com.br](mailto:stefano.baldo@ingaia.com.br) com seu CV anexado. Enviar no assunto: Tech Lead Back-End - GitHub

## Labels

* Alocado
* CLT
* Sênior
* Node.js

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
