### ISSUE TITLE
[São Paulo - SP] Analista Programador Pleno na Finanças 360°

### ISSUE THREAD

**Issue by luizsaouda** [backend-br/vagas#839]
## [São Paulo - SP] Analista Programador Pleno

Estamos procurando alguém proativo, com muita vontade de aprender, repassar conhecimentos e se desenvolver profissionalmente. 

### Características:
- Conhecimento em linguagem de programação orientada a objetos (preferencialmente C#)
- HTML, CSS e Javascript
- Ficaremos muito felizes se você conhecer MongoDB
- Ter experiência de pelo menos 2 anos com desenvolvimento de software web
- Se você já trabalhou no setor do varejo será considerado um diferencial

### Benefícios:
 - Vale-Refeição
 - Vale-Transporte
 - Plano de Saúde
 - Café ou Chopp (o que você preferir)
 - No Dress Code
 - Trabalhe em um ambiente único, dentro do [ecossistema de inovação do Bradesco](https://inovabra.com.br/subhomes/habitat/)

### Local de Trabalho:
 - Av. Angélica, 2529 - Bela Vista 
 - São Paulo - SP - 01227-200

### Sobre a empresa
Somos uma startup com um sistema web inovador para gestão financeira e conciliação de cartões com foco em pequenos e médios varejistas

Venha fazer parte da nossa equipe e nos ajude a transformar o mercado de gestão para esse público ;)

### Interessado? 
Envie seu currículo com pretensão salarial para o e-mail vagas-prog@financas360.com.br.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
