### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Back-end na Ioasys

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#84]
## Descrição da vaga

Desenvolvimento é o nosso carro chefe, mas proporcionar experiências incríveis desde o ínicio até o fim do nosso processo é nossa prioridade. Para que essa mágica aconteça, precisamos de integrantes com criatividade e energia inesgotável. Procuramos alguém dinâmico, com um alcance de visão que vai além (Big Picture), que saiba se comunicar e que seja apaixonado por tecnologia.

## Local

Belo Horizonte

## Requisitos

**Obrigatórios:**

-Sólido conhecimento em Ruby on Rails
-APIs REST
-Banco de dados MySQL – modelagem
-Melhores práticas de programação
-Controle de versão (Git) / Git-flow
-AWS Services (EC2, S3, RDS) – Desejável
-Scrum

## Contratação

CLT à combinar

## Nossa empresa

A ioasys é uma das principais desenvolvedoras de apps do Brasil. Esse sucesso se dá pelo time criativo incrível e pronto para surpreender o tempo todo. Entregamos o que há de melhor quando se trata de tecnologia, em qualquer tela e em qualquer lugar, para trazer um valor real para nossos parceiros (a palavra “cliente” não é muito usada por aqui, temos uma relação de troca mútua).

Trabalhando conosco você poderá desenvolver e exercer suas habilidades em um ambiente dinâmico e horizontal.

Somos ricos em diversidade: cada um de nós carrega um mundo de experiências e perspectivas e isso é a representação da nossa essência. Pensamos fora da caixa para trazer resultados fora da caixa.

## Como se candidatar

https://app.vulpi.com.br/ioasys/541

## Labels

- Alocado
- CLT
- Pleno
-Sênior

**Comment by reginaldojunior** [comment]
Ainda tem vagas?
