### ISSUE TITLE
[SÃO PAULO] Analista Desenvolvedor(a) Java Sr [CCEE]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#842]
Requisitos:
* Conhecimentos avançados em: JavaEE, REST, SpringBoot, Spring framework, Web / REST Services / MVC, micro serviços, maven, jenkins, Git, OO, Hibernate, JUNIT, Oracle 
* Checkstyle, findbugs, Websphere 9 
* Gestão de configuração de artefatos de software utilizando git e svn 

Diferenciais:
* Angular 2+, Bootstrap, Node.JS, HTML5, JS, CSS3 
* UML, Archimate 3, TOGAF, Enterprise Architect, Jira, Componentização, Ionic, Apache Cordova, Desenv. Mobile 

Tipo de contratação: PJ
Local: Paulista - SP

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Java Sr

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
