### ISSUE TITLE
[SÃO PAULO] Vaga Analista Desenvolvedor(a) Java [B2W]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#843]
Requisitos:
* Graduação em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
* Forte base em programação orientada a objeto: modelagem, desenvolvimento e testes de aplicações Java;
* Mínimo 3 anos de experiência.
* Análise de requisitos técnicos e funcionais;
* Desenvolvimento de APIs REST e micro-serviços;
* Spring Boot/Data/Cloud, JPA, Hibernate;
* Ferramentas de controle de código GIT;
* Banco de dados relacionais;
* Desenvolvimento em docker.
* Ambiente Linux;
* Gerenciador de dependências e build (Maven, Gradle, etc).
* Inglês intermediário: Ser apto a ler documentações, debater soluções em fóruns técnicos e escrever o código-fonte dos sistemas.

Diferenciais:
*  Outras linguagens de programação (Kotlin, Scala, Python e etc);
* Ferramentas de Integração Contínua;
* Bancos de dados No-SQL (Cassandra, ElasticSearch e etc);
* Metodologias ágeis de desenvolvimento (Scrum, Kanban);
* Programação reativa (Spring WebFlux).      

Tipo de contratação: CLT 
Local de trabalho: Vila Olímpia 

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga  Desenvolvedor Java B2W

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
