### ISSUE TITLE
[SÃO PAULO] Vaga Analista Desenvolvedor(a) FullStack Sr [TEMPO ASSIST]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#844]
Requisitos:
* Java Web, J2SE, J2EE, Hibernate, Maven, Spring, Struts, CSS, JQuery, HTML5, Oracle, Tomcat, Mobile Android e objective c, Bitbucket, Web Services (SOAP e Restfull)

Diferenciais:
* WSO2, Jenkins, React + Redux, Angular.

Tipo de contratação: PJ
Local de trabalho: Barueri

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga FullStack

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
