### ISSUE TITLE
[SÃO PAULO] Vaga Desenvolvedor(a) Genexus [UNIDAS]

### ISSUE THREAD

**Issue by aline-navarro** [backend-br/vagas#845]
Requisitos:
* Experiência em projetos de softwares com a utilização da ferramenta case GENEXUS (Visual Basic, Java, .NET e PHP e SGBD padrão relacional SQL.
* Experiência em serviços especializados de manutenção de sistemas de informação.
* Ferramenta GENEXUS.
* Conhecimento da ferramenta case GENEXUS (Visual Basic, Java, .NET e PHP).

Tipo de contratação: PJ
Local de trabalho: Bela Vista

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Genexus

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
