### ISSUE TITLE
[São Paulo] Engenheiro de Software na ESCALE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#846]
### Sobre a empresa: Escale

Nos especializamos em trazer leads qualificados e captar vendas onde as empresas estão com dificuldades, focando na geração de leads de altíssima qualidade e encantando clientes com nossa abordagem. O resultado é um cliente com um maior lifetime do que os dos outros canais.

### Descrição: Quais são as experiências valorizadas por nós?

Contribuições em projetos de código aberto;
Grande conhecimento de SQL, incluindo otimizações de desempenho;
Forte experiência em desenvolvimento web: HTTP, HTML, JavaScript, CSS;
Conhecimento prático da arquitetura de microsserviços;
Experiência na criação de APIs RESTful públicas;
Experiência de trabalho com o BigData;
Conhecimento aplicado de estruturas web modernas, como React and Angular;
Conhecimento prático de programação funcional;
Conhecimentos em Scala, Go e Java.

### O que brilharia os nossos olhos?

Publicações revisadas por pares em disciplinas relacionadas a software;
Bacharel ou Mestrado em Ciência da Computação, Engenharia de Software ou disciplina relacionada;
Conhecimentos em Scrum.

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho e curte trabalhar em um lugar informal e sem dress code;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Tem autonomia para tomar decisões e é criativo para propor soluções.

### Benefícios:

Vale Transporte;
Vale Refeição;
Seguro Saúde e Odontológico;
Parceria com o SESC;
Home Office 1x na semana;
Lanches da tarde na empresa 2x na semana.

### Labels:

Alocado
Pleno

### Candidatar: http://bit.ly/escale_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
