### ISSUE TITLE
[São Paulo] Desenvolvedor Java Sênior na 5A Attiva 

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#847]
**Empresa**
A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação.

**Numero de vagas**
3 Vagas para Sênior

**Atividade**
Desenvolvimento de novas aplicações desenvolvidas em Java 1.8 e Springboot
Manutenção em aplicações ativas que utiliza Java 1.6 e 1.7 utilizando jboss e webspheare.
Grande parte das aplicações tem testes unitários.

**Perfil Técnico**
Desenvolvimento em Java 6 e superior, Jboss, Docker, AWS, NoSQL, 
Conhecimento prático da arquitetura de micros serviços; Experiência na criação de APIs RESTful
Integração Continua (Jenkins)
Desejável Angular

**Localidade**
Pinheiros 

**Contratação**
Consultor 5A - PJ valor Hora

### Labels:
Alocado
Sênior 
PJ 

**Como se candidatar**
Interessados, por favor, entrar em contato através do e-mail: Helen.matos@5aattiva.com.br

**Comment by netoestacio** [comment]
@helenmatos vaga somente para senior? (questiono por curiosidade eu notei que esta destacado 3 vagas senior)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
