### ISSUE TITLE
[100% Remoto] Back-end Developer PHP/ Laravel @Arquivei

### ISSUE THREAD

**Issue by AnaCoberio** [backend-br/vagas#8487]
## Nossa empresa

A nossa jornada:

Ninguém olha para Notas Fiscais como a gente. Somos a maior plataforma de automação e gestão de documentos fiscais do Brasil. São mais de 200 pessoas trabalhando conosco, 12 mil clientes e mais de 90 mil empresas que têm seus documentos fiscais gerenciados pelo Arquivei. Desde o nosso início, projetamos e construímos soluções digitais para revolucionar o dia a dia das pessoas. Nos aventuramos em produtos e serviços cada vez mais desafiadores, expandimos nosso time, ampliamos nossa audiência, estreitamos os laços com empresas e sobretudo, com pessoas. 

Human First - Pessoas em primeiro lugar

Somos um time de pessoas que enxergam oportunidades, com liberdade para falar e respeito para ouvir. Valorizamos pessoas e criamos experiências com base em dados, resultados, autonomia e melhoria contínua, sempre com intenção positiva: essa é a  nossa cultura. Tudo isso para que, no final do dia, ajudemos ainda mais pessoas a enxergarem oportunidades também e desafiarem o senso comum, pois aqui, tudo é possível :)

Trabalhamos no modelo de Squads, times cross-funcionais que englobam engenharia, produto e negócios que possuem total autonomia. Todas as decisões são tomadas em conjunto e, assim, o andamento às ações previstas no projeto fluem e são entregues de maneira ágil. Para suportar e fazer o negócio rodar de maneira sustentável, temos o time de Backoffice que atua por meio dos times de People, RH, MKT e Financeiro.

Diversidade é aprendizado e inclusão é necessária na Arquivei

Para que todas as pessoas possuam liberdade e respeito para falar e ouvir e sintam em seu dia a dia as experiências positivas promovidas pela Arquivei, estamos em constante aprendizado, afinal, somos gamechangers! Isso é mais do que resolver uma dor em comum, queremos ser melhores sempre, queremos mudar o jogo seja qual for o jogo. E contamos com você para fazer a diferença e isso independe de sua crença, gênero, orientação sexual, cor de pele, deficiência, classe social ou o que for.

Mirando mais alto, indo mais longe:

1 - Ser referência global em gestão de dados de notas fiscais e focar sempre na desburocratização de processos manuais e trabalhosos.

2 - Desenvolver tecnologia a favor do simples e assim devolver tempo para o que realmente importa.

3 - Munir as empresas de todos os tamanhos com inteligência de mercado a partir dos próprios dados.

É para isso que estamos aqui, é nossa razão de existir. Isso é ser Arquivei.

 
Trabalhamos no modelo de Squads, times cross-funcionais que englobam engenharia, produto e negócios que possuem total autonomia. Todas as decisões são tomadas em conjunto e, assim, o andamento às ações previstas no projeto fluem e são entregues de maneira ágil.

## Descrição da vaga

- Atuar no desenvolvimento/manutenção de APIs;
- Definição e implementação de arquiteturas escaláveis;
- Possuir um amplo conhecimento em desenvolvimento Web;
- Garantir a qualidade das aplicações colocadas em produção;
- Ser também, em conjunto com todo time, responsável pela saúde das aplicações em produção;
- Trabalhar em equipe, promovendo uma cultura de colaboração e compartilhamento.

## Local

100% remoto 

## Requisitos

**Obrigatórios:**

- Experiência com entrega ágil;
- Experiência com mensageiras;
- Experiência no desenvolvimento de pipelines de CI/CD;
- Experiência com observabilidade
- Conhecimento sobre Arquitetura de micro serviços e event-driven;
- Conhecimento básico de Sistemas Distribuídos;
- Conhecimento básico de bancos não-relacionais;
- Conhecimento básico de containers e orquestração (Docker e Kubernetes);
- Acostumado(a) a versionar projetos com GIT em equipe.

**Diferenciais:**

- Desenvolvimento em Golang;
- Desenvolvimento em PHP;
- Experiência em Clean Architecture;
- Experiência com  ElasticSearch;
- Experiência com Kafka e Kafka Stream;
- Experiência com cultura DevOps;
- Gosta de sistemas Distribuídos;
- Gosta de construir soluções escaláveis;
- Já vivenciou problemas e trouxe soluções para ambientes de alta escalabilidade;
- Contato com ferramentas de automação “Infrastructure as Code” (ex: Terraform, Ansible);
- Contato com ferramentas de monitoramento (ex: Prometheus, Grafana);
- Experiência com kubernetes.

## Benefícios

- Saúde e Bem Estar: Plano de saúde e Odontológico Nacionais, Gympass, Desconto Farmácia, Aulas de Yoga e Ginástica Laboral
- Liberdade: Horário Flexível e Modelo Remote First de trabalho, ou seja, trabalho remoto como principal alternativa pra gente. Mas caso queira trabalhar durante alguns dias em nosso escritório que fica em São Carlos - SP, fique à vontade! É sempre bom mudar de ares, não é mesmo? :)
- Boa alimentação: Vale Refeição e/ou Alimentação no Flash
- Tempo com quem importa: Licença Parental estendida para todos casais, inclusive para adoções e casais homoafetivos, ajuda de custo nos 3 primeiros meses do bebê ou criança adotada.

**Nossa stack:**

PHP
Golang
Google Cloud
Google PubSub
Apache Kafka
Kafka Streams
ElasticSearch
BigTable
BigQuery
Avro
Kubernetes
Prometheus / Grafana
ELK

## Contratação

CLT 

## Como se candidatar

Se inscreva através do link: https://arquivei.applytojob.com/apply/buFomfzLuy ou então nos chame pelo Linkedin [Talent Ana Barroso](https://www.linkedin.com/in/ana-cl%C3%A1udia-cob%C3%A9rio-barroso-a1520636/) |  | [ Talent  Bruno Cintra](https://www.linkedin.com/in/brunorodrigocintra/) | [ Talent Luisa Albuquerque ](https://www.linkedin.com/in/luisadealbuquerque/) | [Talent Heitor Sanches ](https://www.linkedin.com/in/heitor-sanches-641761165/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Tech Lead

**Comment by CbVidal** [comment]
Muito TOP!!!!

**Comment by AnaCoberio** [comment]
Continuamos com vagas abertas💙💙
