### ISSUE TITLE
[ Alphaville] Desenvolvedor Dot Net - Pleno [ 5A Attiva] 

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#849]
# Descrição da Empresa
A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação.
 
# Atividades e Responsabilidades
* Atuar no desenvolvimento de novas funcionalidades para plataforma Web
* Discutir e fomentar a implementação de novas funcionalidades
* Participar na estimativa do time de desenvolvimento
* Em grupo, se comprometer com metas, prazos e objetivos

# Tecnologias:
Experiencia em desenvolvimento .Net C#, .Net Core, Entity Framework, MVC, WebAPI, AngularJS, Angular, Redis, GIT
Scrum, Unit Test, SOAP, REST, Design Patterns

# Conhecimento Desejável
Angular [2,4,5,6], NodeJS, Mongo DB
Integração contínua, TDD

# Contratação
* PJ - Valor à negociar

# Local
Alphaville 

# Como se candidatar
Achou essa oportunidade a sua cara? Então se candidata, estamos ansiosos para conhecer você!
E-mail: Helen.matos@5aattiva.com.br

## Labels
* Dot Net
* Alocado
* PJ
* Pleno

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
