### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Node.Js - 5A Attiva

### ISSUE THREAD

**Issue by helenmatos** [backend-br/vagas#850]
# Descrição da Empresa
A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação.
 
# Atividades e Responsabilidades
 Desenvolvimento e manutenção de aplicações web; Atuar com esteira de desenvolvimento.
Atuar com cultura DeVops; Teste automatizados; Integração continua
Aplica melhores práticas de documentação de código desenvolvido; Desenvolver e sustentar integrações; 
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;

# Perfil técnico 
Buscamos profissionais que tenha experiência em modelo Ágil, Arquitetura, já ter atuado em squads. 
Profissional com visão de um todo, senso de urgência e responsabilidade. 
Além das características pessoais, precisamos de profissionais que já tenha atuado com Desenvolvimento Node.JS; AWA;  Desenvolvimento de funcionalidades no Back-End;  Aplica melhores práticas de documentação de código desenvolvido; Desenvolver e sustentar integrações; 
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas. 

# Tecnologias:
* Node.Js
* AWS
* Scrum
* Testes
* Docker

# Diferencial
* JavaScript
* Angular / React ou Vue

# Contratação
* PJ via 5A - Valor à negociar

# Local
Escritório localizado próximo a Estação da estação Berrini

# Como se candidatar
Achou essa oportunidade a sua cara? Então se candidata, estamos ansiosos para conhecer você!
E-mail: Helen.matos@5aattiva.com.br 

## Labels
* Node.Js
* Alocado
* PJ
* Sênior

**Comment by gislainy** [comment]
@helenmatos aceita remoto?

**Comment by giovannicruz97** [comment]
Acredito que o email seja: Helen.matos@5aattiva.com.br

**Comment by helenmatos** [comment]
> @helenmatos aceita remoto?

@gislainy infelizmente não :(

**Comment by helenmatos** [comment]
> Acredito que o email seja: [Helen.matos@5aattiva.com.br](mailto:Helen.matos@5aattiva.com.br)

@giovannicruz97 isso mesmo :)  obrigada pela observação, já realizei a alteração.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
