### ISSUE TITLE
[Santa Barbara D'Oeste-SP ou Remoto] Desenvolvedor Full Stack na [Acruxx]

### ISSUE THREAD

**Issue by tuliomachado-acruxx** [backend-br/vagas#851]
## Descrição da vaga

- Criar sistemas / aplicativos front-end (React, Angular) e back-end (GraphQL/PHP);
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Participar do processo criativo e auxiliar na construção dos sistemas;
- Nos deixar impressionados com sua capacidade criativa.

## Local

Remoto ou Escritório, Santa Barbara D'Oeste - SP

## Benefícios

- VA
- Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
- No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

#### Diferenciais

- Área de descanso
- Café expresso ou coado
- Chá
- Cachorro no ambiente de trabalho

## Requisitos

**Desejáveis:**
- Experiência com front-end;
- Bons conhecimento em JavaScript/CSS frameworks (e.g. React, Angular, Semantic UI, etc);
- Conhecimentos em HTML5/CSS e na construção de websites responsivos/adaptáveis;
- Experiência com serviços RESTful API;
- Experiência com aplicações usando JavaScript, JSX, HTML, CSS;
- Ferramentas de front-end, como npm, Bower, Grunt, Gulp, etc;    
- Conhecimentos em PHP para desenvolvimento Back-end.

## Contratação
- CLT

## Nossa empresa

Percepção, motivação e aprendizagem são os elementos propulsores do desenvolvimento da humanidade.

Assim é com a Acruxx, uma empresa focada e motivada pelos desafios de novos projetos, novas tecnologias, geração e uso inteligente da informação a órgãos públicos.

## Como se candidatar

Por favor envie um email para tulio@cacdigital.com.br com seu CV anexado - enviar no assunto: "Vaga Full Stack 02/2019"

**Comment by alessandroprudencio** [comment]
tem algum teste??

**Comment by tuliomachado-acruxx** [comment]
@alessandroprudencio, caso passe no primeiro filtro do processo de seleção, sim, teremos testes práticos.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
