### ISSUE TITLE
São Paulo - Senior Backend Software Engineer - Casafy

### ISSUE THREAD

**Issue by ricardovsilva** [backend-br/vagas#853]
## About Us
We are a real-estate portal startup located in the São Paulo, Distrito AdTech Startup Hub.

We are technology lovers that are passionate about learning, development, real-estate market, science and processes.

We secured recently R$8 mio investment from Austrian and Estonian VC funds and have aggressive plans and interesting ideas how to disrupt LATAM real-estate market.
If you like challenges, thinking big and deliver kick-ass services, please take a look at our job position.

## What are we looking for? 
We are searching for backend software engineers who are passionate about what they do, have a wide spread knowledge about technologies, system architecture and are proficient in at least two development languages.
We have a system developed in Ruby and some microservices in Python, so proficiency in one of these languages is going to be benefit.

What do you need to apply to this job?

- 5+ years of experience developing web systems;
- System architecture knowledge;
- Frontend experience is desirable;
- Experience working with TDD methodologies in DDD systems;
- Master at least two programming languages - Ruby or Python are preferred;
- Experience working with SQL and NoSQL databases;
- Need to know how to work in Linux environment;
- English is a requirement, at least in conversational level since we work with people from other countries also;
- Love for learning.

## Place
Rua Estados Unidos, 1570 - Jardim América, São Paulo - SP

## Benefits
- Health and Dental Plan from Bradesco;
- Meal compensation - R$35,00/day;
- Competitive salary and bonus from company results;
- Informal environment and minimal bureaucracy;
- Your ideas is will have big impact on business result;
- Highend tools that match your talent.

## Hiring Type
CLT

## How to Apply
Please, send an email with subject [ricardo@casafy.com.br](mailto:ricardo@casafy.com.br) with your curriculum in attachment.

Labels:
- CLT
- Senior
- Ruby
- Python
- Startup

**Comment by thiagovsk** [comment]
@ricardovsilva só presencial?

**Comment by ricardovsilva** [comment]
@thiagovsk por enquanto sim

**Comment by ricardovsilva** [comment]
up!
