### ISSUE TITLE
[Brasil] Back-end Developer DotNet Core @ NTT DATA

### ISSUE THREAD

**Issue by msrmarcio** [backend-br/vagas#8534]
> Vaga Remota (Home Office - Diversas Regiões do Brasil)

## Nossa empresa

**NTT DATA LATAM**

A NTT DATA é a 6ª maior provedora de serviços de TI do mundo com sede em Tóquio, e conta com 140.000 profissionais, operando em mais de 65 países. A NTT DATA Europe & Latam é uma parceria entre a everis (com presença na Europa e América Latina) e a NTT DATA EMEA (com presença principalmente no Reino Unido, Itália, Alemanha e Romênia) para entregar transformação e inovação a clientes em toda a Europa e América Latina. América. Para nós, nosso trabalho diário não é apenas inovação tecnológica, é conectar pessoas para criar as melhores soluções para o dia a dia.

Tamanho da empresa
+ de 10.001 funcionários

## Descrição da vaga
**Desenvolvedor Asp.Net Core**

Conhecimento em:

- Orientação a Objetos
-  Asp.Net Core,
-  C#, 
-  HTML 
- CSS
- JAVASCRIPT
- jQuery, 
- SQL SERVER (query, Procedure, cursos e modelagem) 
•  Net Core 
• APIs Rest 
• ORMs (Dapper, EF)  
• Testes Unitários 
• GIT   

## Local

Local Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com DotNet, DotNet Core e C# com uso do Asp.Net
- 2 anos de experiência com Sql Server

**Desejáveis mas não obrigatório:**
- Padrões de Projetos
- C# Programação paralela com uso do Thread

**Diferenciais:**
- Conhecimento de Arquiteturas de Projetos

## Benefícios

- Cesta de Benefícios Flexíveis
- Plano de saúde
- Seguro de vida 
- Auxílio creche 
- Vale Refeição 
- Auxílio Creche   
- Plano Odontológico 
- GYMPASS 
- Vale Combustível  

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para msantrod@nttdata com seu CV anexado - enviar no assunto: Vaga DoteNet Core

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo. 

#### Alocação
- Alocado
- Remoto Home Office

#### Regime
- CLT 

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by FilipeAugustoVO** [comment]
Boa tarde, não estou conseguindo enviar um e-mail para o endereço listado,
aparentemente ele não existe.
