### ISSUE TITLE
[São Paulo] - Analista / Desenvolvedor Angular, Ionic e ASP.NET Core

### ISSUE THREAD

**Issue by gabbianiiii** [backend-br/vagas#854]
# Descrição da vaga
Busco profissionais nos mais diversos níveis para trabalhar um software house.

# Local
São Paulo

# Requisitos
- Angular
- Ionic
- ASP.NET Core

# Como se candidatar
Envie um e-mail para raphael.pacheco@outlook.com.br com o título - Analista SP [Seu Nível] juntamente com o seu currículo anexado.

**Comment by GlaucioOliveira** [comment]
aceita remoto?

**Comment by gabbianiiii** [comment]
Vaga já preenchida. Obrigado a todos que enviaram os currículos :)
