### ISSUE TITLE
[Ribeirão Preto] Desenvolvedor .Net C# - Pleno - [BEBLUE]

### ISSUE THREAD

**Issue by KevinMarcelOriginal** [backend-br/vagas#855]
A Beblue está procurando por profissionais inovadores e apaixonados por tecnologia para se juntar a nós e nos ajudar na incrível e desafiadora caminhada de inovação nas indústrias de pagamentos e recompensas no Brasil. Na Beblue você terá a oportunidade de aplicar os seus talentos e energia criativa para entregar soluções de alta performance em uma das mais promissoras e crescentes Startups do Brasil. Temos múltiplas áreas de especialização disponíveis como: 

Micro-serviços Java/Kotlin com Spring Boot/Cloud;

Micro-serviços C# .Net Core;

Mobile Android Java/Kotlin;

Mobile iOs Swift;

Web React e Redux;

DevOps Terraform e AWS;

Requisitos e Responsabilidades:

Como um desenvolvedor .NET C# Pleno você será responsável por:

Mindset empreendedor, ter postura de dono e ser responsável pela entrega dos projetos; 

Ser adaptável, aprender rápido, entender o contexto da "big picture", e conseguir aplicar abordagens “out of the box” para atingir seus objetivos;

Projetar e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;

Participar e colaborar na arquitetura das soluções focando em requisitos não funcionais como disponibilidade, escalabilidade e performance;

Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc;

Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes;

Servir como líder de projeto ou líder técnico durante o decorrer de projetos;

Apoiar desenvolvedores menos experientes a atingir seus objetivos respeitando sempre os requisitos de engenharia, arquitetura e de qualidade.

Educação e Experiência:

3+ anos de experiência com Programação .NET C#;

1+ anos de experiência com ciclo de desenvolvimento Agile;

Formação de ensino superior em Ciência da Computação ou equivalente;

Conhecimentos e Habilidades:

Excelente comunicação oral;

Habilidades de escrita clara e direta;

Inglês Técnico para Leitura e Escrita;

Experiência com cultura Agile;

Conhecimentos em SOLID e Design Patterns;

Conhecimentos em TDD, BDD e DDD;

Experiência com .NET Core;

Experiência com containers de injeção de dependência;

Experiência com ORM (entity framework, dapper, etc...);

Experiência com a plataforma Docker;

Experiência com AWS (EC2, ECS, RDS, ELB);

Experiência com Mensageria RabbitMQ ou similares;

Experiência com Integração Contínua e Entrega Contínua.

LINK PARA CANDIDATURA: https://jobs.kenoby.com/beblue/job/desenvolvedor-net-c-pleno-15-vagas/5c3c4d584887ee50d41e9e7a

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
