### ISSUE TITLE
[Belo Horizonte] Full-stack Java na itexto Consultoria

### ISSUE THREAD

**Issue by kico-itexto** [backend-br/vagas#857]
Estamos ampliando nossa equipe e buscando novos membros. Venha atuar em projetos realmente desafiadores e crescer consoco!

## Sobre nós

Nosso objetivo é ajudar outras empresas e indivíduos a desenvolver softwares com maior qualidade e eficiência, o que é feito através dos nossos serviços de consultoria, treinamentos e desenvolvimento. Somos referência nacional quando o assunto é Java, Groovy, Grails e Spring, o que não quer dizer que apenas trabalhemos com estas tecnologias. Dado que acreditamos no imenso valor do legado, da experiência prévia dos nossos clientes e da pesquisa, o contratado irá lidar com um stack bastante variado.

Estamos experimentando forte crescimento, razão pela qual provemos ao contratado experiência real de mercado pois nossos clientes atuam nas mais variadas áreas: e-commerce, financeira, gestão, saúde, educação, desenvolvimento de software, mineração, engenharia, entretenimento, startups e outras.

Há também alguns produtos nos quais estamos trabalhando neste momento, focados em desenvolvedores, e que já se encontram em produção (como o Grails Brasil, /dev/All, Spring Brasil, Javascript Brasil, Formação itexto e nossos Guias).

Você pode conhecer melhor nossos valores neste link: http://www.itexto.com.br/site/?page_id=17

## Quem estamos buscando

Esperamos que você já possua alguma experiência na implementação ou manutenção de sistemas computacionais.

A tecnologia mais importante para nós são seus conhecimentos de ciência da computação, o que envolve lógica de programação, algoritmos, boa compreensão de conceitos fundamentais como sistemas operacionais, bancos de dados (não necessariamente relacionais), paradigmas de programação (pelo menos procedural e orientação a objetos) e estruturas de dados. Não buscamos um especialista, mas sim um generalista que, como nós, ame programar e projetar soluções. Se não ama programar seu lugar não é aqui.

É fundamental salientar que você não trabalhará com apenas uma tecnologia, entretanto não é necessário ter profundo conhecimento em todas as que for usar: o essencial é que tenha jogo de cintura para que possa caminhar entre estas ferramentas (a especialização, se houver, surgirá de forma natural). **Serão fornecidos em horário comercial todos os meios necessários para que você possa aprender as tecnologias que estivermos usando ou desenvolvendo no momento.**

O aspecto pessoal é levado em consideração e sem dúvidas é fator fundamental. Como nosso dia a dia envolve pesquisa constante e intensa, em nossa conversa inicial avaliaremos o modo como seu interesse pelas áreas da computação se manifestam. Já adiantamos: se você não gosta de ler e estudar, seu lugar não é aqui.

## Diferenciais importantes

Estamos buscando um profissional com perfil fullstack, porém um pouco mais voltado para o desenvolvimento backend neste momento e com experiência na plataforma Java. Sendo assim o conhecimento de ao menos uma das tecnologias a seguir será considerado um importante diferencial:

* Spring Framework.
* Groovy e Grails.
* Java EE (JSF, CDI, JPA)
* Ter noções de desenvolvimento web/mobile com algum framework de mercado (Angular, Vue.js, Ionic, * Cordova e Padrões web).

Importante salientar que estas são as demandas momentâneas da itexto, sendo assim é fundamental ter em mente que no futuro você também poderá atuar com outros stacks, tais como Node.js, Python, PHP, .net ou outros.

## Formação mínima esperada
Sobre sua formação, esperamos que você se encaixe em um dos casos abaixo:

* Ter finalizado recentemente (ou estar finalizando no próximo semestre) o curso de Ciência da 
* Computação ou áreas correlatas (Sistemas de Informação, Engenharia da Computação, etc).
* Ter acabado de concluir um curso técnico relacionado a Tecnologia da Informação.
* Ter ao menos dois anos de experiência profissional nesta área.
* Já ter realizado estágio na área.

Dado que estamos em Belo Horizonte, **é essencial que você resida aqui ou na região. O trabalho é realizado fisicamente em nossa sede**.

## Requisitos essenciais

* Ter a formação acima mencionada.
* Ter boa capacidade de leitura em inglês.
* Conhecimentos técnicos acima mencionados.
* Gostar de lidar com pessoas.
* Estar antenado com o que ocorre no mercado de desenvolvimento de software.
* Residir em Belo Horizonte ou região

## O que você fará aqui

* Implementação de novas funcionalidades em sistemas computacionais.
* Evolução de sistemas legados.

## Benefícios

* Ticket refeição.
* Vale transporte.
* Participação nos lucros.
* Cartão Cultura.
* Plano de saúde.
* Auxílio academia.

## Como se inscrever
Basta nos falar mais sobre você preenchendo o formulário disponibilizado neste link: https://www.itexto.com.br/site/trabalhe-conosco/

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
