### ISSUE TITLE
[Botafogo, Rio de Janeiro] Desenvolvedor Java / Mobicare

### ISSUE THREAD

**Issue by MobiSelecao** [backend-br/vagas#858]
**Descrição:**
Codifique para Plataformas J2EE;
Proponha novas tecnologias e melhorias para os processos da empresa;
Entregue projetos para operações de acordo com as definições da empresa.

**Requisitos:**
Estudante ou Formado em: Ciências da computação, Análise e Desenvolvimento de Sistemas, Sistemas de Informações e /ou áreas correlatas;                                        
Conhecimentos em:
•	 JAVA;  
•	Ao menos um framework MVC (Spring MVC, VRaptor, Play, JSF);
•	Padrões de projeto
•	SQL (modelagem básica, consultas);
•	ORM (JPA, Hibernate); 
•	Ferramenta para build e gerenciamento de dependências (Maven, Gradle); 
•	Ferramentas de controle de versão (Git, Subversion); 
•	Básico de ambiente Linux (navegação em diretórios, tail, grep, less, more, curl);
•	Testes automatizados (JUnit, TEstNG, RestAssured, WebDriver, Mockito, EasyMock;) Virtualização de ambiente (Docker);
•	Integração contínua (Jenkins, GoCD);
•	NoSQL (MongoDB, Dynamo).

Vivência com:
•	Desenvolvimento e utilização de web-services REST e SOAP;                                                   
•	Servidor de aplicação Tomcat;
•	Desenvolvimento de sistemas de integração (Padrões de integração EIP, SOAP, JMS);     
•	Protocolos de rede (transporte e aplicação);                                         
•	Frameworks JavaScript (Angular, Meteor, BackboneJS, JQuery);
•	Spring Framework (Data, Integration, Security, Cloud, Actuator, Batch);
•	Plataformas Android e iOS; 
•	Ambiente Amazon AWS (Beanstalk, SES, SNS, etc;) 

**Local de Trabalho:**
Botafogo/RJ

**Benefícios:**
Horário Flexível 
Plano de saúde- Bradesco 
Plano Odontológico - Bradesco 
Vale-Transporte 
Vale-Refeição e / ou Alimentação (Flex) 
Curso de Inglês e / ou Espanhol (Dentro do Nosso Programa de curso de idiomas ministrado internamente) 
Bônus 
Política de Trabalho remoto (Home Escritório). 
Cursos e palestras para o desenvolvimento de carreira

**Como se candidatar:**
Entre em nossa página de carreira e faça sua inscrição na vaga de interesse: https://jobs.kenoby.com/mobicare

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
