### ISSUE TITLE
[REMOTO] Back-End Developer PLENO/SÊNIOR @ACCT Global 

### ISSUE THREAD

**Issue by Ednaratorres** [backend-br/vagas#8580]
## Nossa empresa

Somos a ACCT Consulting & Technology, atualmente possuímos projetos de implementação, operação e evolução de e-commerce em 19 países e desde 2020 certificados pelo Great Place To Work (GPTW) como uma das melhores empresas de TI para se trabalhar.

## Descrição da vaga

- Irá desenvolver um código de alta qualidade, garantindo a funcionalidade, usabilidade, manutenibilidade e performance, além do uso de práticas de teste e qualidade;
- Entender e avaliar o impacto das soluções que o time desenvolve nos nossos clientes e no usuário final;
- Irá trabalhar e ajudar a promover um ambiente colaborativo com um time de ponta, em que práticas de feedbacks e motivação para se desenvolver estão sempre presentes.

## Local

100% REMOTO 

## Requisitos

**Obrigatórios:**
- Experiência em nodejs
- Capacidade para escrever código consistente, eficiente, reutilizável e escalável;
- Capacidade crítica para atuar na revisão de códigos e apoiar na definição de processos do dia-a-dia do time;
- Preocupação com a excelência técnica e boas práticas de desenvolvimento 
- Preocupação com a experiência do cliente;
- Boas práticas e estratégias de versionamento com Git;
- Pragmatismo para resolução de problemas.

**Desejáveis:**
- Experiência com plataformas de e-commerce (VTEX, Magento, etc);
- Possuir familiaridade com metodologias ágeis.
- Tiver conhecimento com API's (REST, SOAP);

**Diferenciais:**
- Inglês e espanhol avançado ou fluente
- Participação ativa em comunidades de Tecnologia (palestras, meetups, eventos, tech talks, blogs) e projetos open source como forma de disseminar o conhecimento.

## Benefícios

- Política de home office;
- Benefício All remote, para montar seu espaço de trabalho em casa;
- Vale transporte;
- Vale alimentação e/ou vale refeição;
- PLR;
- Auxílio creche;
- Assistência médica e odontológica;
- Seguro de vida em grupo;
- Convênio com farmácias e academias;
- Benefício terapia (nesse momento de pandemia e isolamento social);
- Parceria com o SESC.

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para recrutamento@acct.global com seu CV anexado - enviar no assunto: Vaga NodeJS
Ou se candidate no nosso site https://jobs.kenoby.com/acct?utm_source=website

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Ednaratorres** [comment]
Vaga continua em aberto!

**Comment by raelnogpires** [comment]
Não sei se a vaga ainda está disponível, visto que é do dia 22/02, porém enviei meu currículo para o email indicado.
