### ISSUE TITLE
[Botafogo, Rio de Janeiro] Desenvolvedor Fullsatck (Backend e Frontend) / Mobicare

### ISSUE THREAD

**Issue by MobiSelecao** [backend-br/vagas#859]
**Descrição:**
Criar aplicativos da Web para fornecer dados inteligentes e oportunos para as equipes;
Entregar código de alta qualidade;
Colaborar com engenheiros de software, proprietários de produtos e analistas;
Comunicar-se com outras equipes e indivíduos para planejar, coordenar e solicitar feedback;
Se integrar como membro de uma equipe multifuncional autônoma.

**Requisitos:**
Estudante ou Formado em: Ciências da computação, Análise e Desenvolvimento de Sistemas, Sistemas de Informações e /ou áreas correlatas;                                        
Conhecimentos e experiência em:
•	Criação de aplicativos JavaScript / HTML / CSS ricos em dados e fáceis de usar;
•	Tendências atuais e emergentes da plataforma web;
•	Modernas técnicas de codificação, teste, depuração e automação de JavaScript;
•	Boas práticas de integração Rest  
•	Prover autenticações seguras e integradas com o backend de maneira segura

Importante:
•	Se preocupar com tecnologias da Web, explorando dados, experiência do usuário e design;
•	Ter insights sobre as trocas entre bibliotecas JavaScript front-end
•	Ter interesse sobre o funcionamento das plataformas backend e infraestrutura

**Local de Trabalho:**
Botafogo/RJ

**Benefícios:**
Horário Flexível 
Plano de saúde- Bradesco 
Plano Odontológico - Bradesco 
Vale-Transporte 
Vale-Refeição e / ou Alimentação (Flex) 
Curso de Inglês e / ou Espanhol (Dentro do Nosso Programa de curso de idiomas ministrado internamente) 
Bônus 
Política de Trabalho remoto (Home Escritório). 
Cursos e palestras para o desenvolvimento de carreira

**Como se candidatar:**
Entre em nossa página de carreira e faça sua inscrição na vaga de interesse: https://jobs.kenoby.com/mobicare

**Comment by alessandroprudencio** [comment]
tem que ser presencial ou 100% remoto?

**Comment by MobiSelecao** [comment]
Oi Alessandro,



O Nosso programa, à princípio, é 1vez na semana.



*Abs,*

*Fabiana Perrotta Bezerra*
DC Analyst
*fabiana.perrotta@mobicare.com.br <escarlet.suzan@mobicare.com.br>*
*+55 (21) 3032-5165*

*www.** mobicare.com.br <http://www.mobicare.com.br/>*

*https://jobs.kenoby.com/mobicarreira
<https://jobs.kenoby.com/mobicarreira>*



[image: http://www.mobicare.com.br/logo-email.png][image: gptw]



*De:* Alessandro Prudencio da Cruz Silva <notifications@github.com>
*Enviada em:* quinta-feira, 21 de fevereiro de 2019 11:07
*Para:* backend-br/vagas <vagas@noreply.github.com>
*Cc:* MobiSelecao <fabiana.perrotta@mobicare.com.br>; Author <
author@noreply.github.com>
*Assunto:* Re: [backend-br/vagas] [Botafogo, Rio de Janeiro] Desenvolvedor
Fullsatck (Backend e Frontend) / Mobicare (#859)



100% remoto?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/backend-br/vagas/issues/859#issuecomment-466011325>,
or mute
the thread

**Comment by gabrielsimas** [comment]
@MobiSelecao vocês têm a opção para contratos PJ?

**Comment by MobiSelecao** [comment]
Oi Gabriel,



A Mobicare só trabalha com contrato CLT.



*Abs,*

*Fabiana Perrotta Bezerra*
DC Analyst
*fabiana.perrotta@mobicare.com.br <escarlet.suzan@mobicare.com.br>*
*+55 (21) 3032-5165*

*www.** mobicare.com.br <http://www.mobicare.com.br/>*

*https://jobs.kenoby.com/mobicarreira
<https://jobs.kenoby.com/mobicarreira>*



[image: http://www.mobicare.com.br/logo-email.png][image: gptw]



*De:* Gabriel Simas <notifications@github.com>
*Enviada em:* quinta-feira, 21 de fevereiro de 2019 11:37
*Para:* backend-br/vagas <vagas@noreply.github.com>
*Cc:* MobiSelecao <fabiana.perrotta@mobicare.com.br>; Mention <
mention@noreply.github.com>
*Assunto:* Re: [backend-br/vagas] [Botafogo, Rio de Janeiro] Desenvolvedor
Fullsatck (Backend e Frontend) / Mobicare (#859)



@MobiSelecao <https://github.com/MobiSelecao> vocês têm a opção para
contratos PJ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/backend-br/vagas/issues/859#issuecomment-466021985>,
or mute
the thread

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
