### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Python/Flask

### ISSUE THREAD

**Issue by franciswagner** [backend-br/vagas#860]
## Descrição da vaga

Estamos recrutando um desenvolvedor Python/Flask Pleno ou Sênior para atuar em nossa plataforma de investimentos. Nosso ambiente é extremamente colaborativo.

## Local

Presencial, São Paulo - Campos Elíseos

## Benefícios

- Plano de saúde
- Gympass

#### Diferenciais

- Horário Flexível
- Snacks à vontade
- Frigobar com cervejas, refrigerantes, sucos e energéticos
- Xbox One para descontração e tirar um contra no PES 2019 :P
- Dress code despojado
- Cafés Nespresso e Dolce Gusto
- Acesso a quase 2000 cursos online pela Udemy, Datacamp
- Acesso a cursos online sobre finanças e investimentos

## Requisitos

**Obrigatórios:**
- 3 anos ou mais de experiência com Python e Flask
- Experiência em criação de APIs
- Experiência com banco de dados Mongodb

**Desejáveis:**
- Conhecimentos de Git

**Diferenciais:**
- Conhecimentos de matemática financeira
- Conhecimentos com banco de dados Neo4J e Redis

## Contratação

PJ a combinar

## Nossa empresa

O App Renda Fixa é uma startup da área financeira (Fintech) e nosso propósito é revolucionar o mercado de investimentos no Brasil.

## Como se candidatar

Por favor envie um email para francis@rendafixa.rocks com seu CV anexado - enviar no assunto: Vaga Dev Python/Flask

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- PJ

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
