### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Full Stack na ONAWA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#861]
### Sobre a empresa: Onawa

**Descrição: O que você fará na Onawa?**

Além de ser um fera que vai ser inspiração técnica para um time muito bom de serviço, esperamos que você seja capaz de protagonizar evoluções e melhorias em nossos produtos e plataformas. Para isso ser verdade, você irá botar a mão na massa, desenvolver funcionalidades, adaptar recursos e evoluir nosso sistema. 

Contamos com alguém com uma bagagem bem bacana para sugerir, criticar e implementar soluções. Se você tem espírito empreendedor e quer alavancar sua carreira fazendo parte de um time que muda vidas, é para Onawa que você tem que vir!

### Requisitos que você precisa atender:

Desenvolver em PHP, Laravel;
Conhecer de React e React Native;
Saber JavaScript;
Conhecer de desenvolvimento Mobile (Android e iOS);
Ionic;
Ter maturidade em entregas e trabalho em equipe;
Ter sede por conhecimento;

### Diferenciais que vão contar pontos para você:

Conhecer de Apis de E-commerce e pagamento online;
Algum contato anterior com AWS;
Dispor de um PC pessoal para uso inicial;
Gostar muito de impactar a vidas pessoas positivamente;
Saber se posicionar e transmitir conhecimentos.

### Oferecemos um tudo para você crescer:

Salário compatível com o mercado;
Ambiente sensacional da Artplan;
Café o tempo todo, S2;
Escritório 24h, mas não queremos você trabalhando mais do que o horário;
Somos flexíveis, mas de forma organizada, rsrs;
Zero hierarquia, estamos caminhando para uma holocracia;
Cultura animal!

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Auxiliar na criação de uma equipe de alta performance.

### Labels:

Alocado
Senior

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
