### ISSUE TITLE
[São Paulo] Back-End Developer na [MIRA EDUCAÇÃO]

### ISSUE THREAD

**Issue by MiraEduc** [backend-br/vagas#863]
**Quem Somos:**

A Mira é uma Startup que busca uma questão básica em todo o mundo: educação. Desenvolvemos ferramentas com o objetivo de facilitar a vida de professores e gestores, aumentando a eficácia e garantindo uma melhoria no ensino.

Uma empresa engajada por um propósito maior, fazer uma mudança na educação pública do Brasil. Somos inconformados com o presente e sonde melhor do futuro diferente.

Se você quer que seu trabalho cause impacto na sociedade e você seja feliz, seu lugar é aqui.

Queremos inspirar outras pessoas, contribuir positivamente para o futuro de nosso país. To this contamos com colaboradores engajados, apaixonados pela nossa causa e motivados pelo impacto social.

O time de Engenheiros de Software Backend é responsável pela arquitetura, desenvolvimento e manutenção dos micros serviços que dão suporte às aplicações mobile e web da Mira Educação. Nosso time de engenheiros de software se preocupa em utilizar as melhores tecnologias e metodologias de desenvolvimento para encontrar as melhores soluções possíveis para os problemas do dia a dia, além de sempre estarem estudando coisas novas e constantemente propondo sugestões de melhorias.

Estamos crescendo e precisamos aumentar o nosso time. Procuramos engenheiros de software apaixonados por tecnologia, que se identifiquem com os valores e missão da Mira Educação. Que não se limitem apenas em resolver o problema, mas também em encontrar a melhor solução dentre as demais.

**Como Desenvolvedor (a) Backend as suas maiores responsabilidades serão:**

- Desenhar, desenvolver e manter micro serviços que solucionem da forma mais eficaz, eficiente e segura as demandas vindas de produto e marketing;
- Auxiliar tecnicamente o time com seu conhecimento e experiência;
- Ser agnóstico a linguagens e estar disposto a conhecer, estudar e aplicar novas linguagens e tecnologias;

**O que esperamos de você:**

- Experiência com desenvolvimento de software;
- Conhecimento em algumas das linguagens e tecnologias de backend, como Java/Kotlin com SpringBoot, Python com Flask ou Django;
- Preocupação constante com arquitetura e documentação;
- Implementar testes, muitos testes;
- Familiaridade com Git;
- Compartilhar conhecimentos, discutir soluções, trabalhar em equipe;
- Sempre ter um olhar crítico e propor melhorias na organização do código, estrutura e arquitetura quando achar necessário;
- Expor sua opinião, independente da opinião dos demais.

**Desejável:**

- Interesse em diferentes linguagens e frameworks.
- Conhecimentos em plataformas cloud, especialemnte com AWS.
- Docker, Kubernetes, EFK, CI & CD, Oauth2, Mensagerias.

**Benefícios:**

Assistência Médica e Odontológica - 100% custeada pela empresa; 
Vale Refeição; 
Vale Alimentação ou Combustível; 
Vale Cultura; 
Gympass; 
Auxílio Creche; 
PLR - Atrelado a metas; 
Desconto com escola de idiomas; 
Massagem Rápida; 
Flexíveis: Happy Hour toda sexta, Snacks à vontade, Sala de descanso, Vídeo game, Dresscode e ambiente informal; 
Localização, ao lado do metrô Santa Cruz;

Interessados, envio o currículo para: rh@miraeducacao.com.br no assunto colocar: Vaga Backend ou se cadastrar em nossa página de carreiras: https://jobs.kenoby.com/miraeducacao/job/software-engineer-backend-senior/5b7dbfeb6f3bb97206ef3765

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
