### ISSUE TITLE
São Paulo Back-End Developer no Looke

### ISSUE THREAD

**Issue by thaishbrasil** [backend-br/vagas#864]
**Desenvolvedor(a) BackEnd – SR 
Enviar CV para: vagas@looke.com.br
A/C Thais Fernandes

**Com o que você vai trabalhar:**** 
Atuar no desenvolvimento e manutenção do back da plataforma de streaming com gestão de banco, servidores e criação de serviços. Desenvolvimento de processos inovadores de encoding e encriptação de filmes e séries. Integração com plataforma de parceiros, meios de pagamentos etc. Desenvolver aplicativos para Smart TV e STB (set-top box). Desenvolver aplicativos para console de jogos como Xbox e PlayStation. 
 
**Atividades:**
➢ Colaborar com equipe de trabalho na criação de soluções inovadoras e de Performance 
➢ Auxiliar na arquitetura de sistemas desenvolvendo novos componentes
➢ Trazer inovações e novas Tecnologias que possam ser utilizadas para melhorar nossos sistemas.
➢ Construir APIs e serviços de back end utilizando .NET;
➢ Contribuir em decisões de arquitetura do projeto;
➢ Criar ferramentas para medir e otimizar a performance dos nossos serviços; 
➢ Integrar serviços terceiros, como gateways de pagamento e ferramentas de e-mail marketing.
➢ Priorizar e tratar bugs e exceções reportados em produção; 

**Requisitos para se candidatar:**  
Net/C#:
Experiência com Arquitetura, Desenvolvimento, Manutenção e Aplicações .NET 
Conhecimentos em MVC e WebAPI
Ser atualizado sobre as mais recentes ferramentas de framework e criação de bibliotecas;
Conhecimentos em Software Design Patterns
Conhecimentos de Windows Azure
 Inglês avançado/fluente
Conhecimentos avançados em Banco de Dados SQL Server 
Sólidos conhecimentos de Estruturas de Dados e Algoritmos
 
**Benefícios**:   
-Seguro Saúde, Odontológico e de Vida de Primeira linha
-VT/VR
-Bônus Salarial por Performance pago 1x no ano
-Escola de Inglês na empresa
-“no dress code” o que for mais confortável 
-Frutas, Snacks, Ginástica Laboral e programas de incentivo e suporte de Qualidade de vida; 
Integração: Gostamos de comemorar com festas 1x ao mês no nosso Ambiente de trabalho! 

Nossa Cultura:
Somos uma empresa jovem inspirada em tecnologias disruptivas. Oferecemos um ambiente de trabalho que Incentiva a inovação e a produtividade, garantido liberdade com responsabilidade.

http://www.looke.com.br

O Looke é uma Plataforma brasileira. 
Temos aplicativos de iOS, Android, TV conectada, Playstation, PC, Safari, Apple TV, Android TV.
Tudo isso a gente faz aqui. A gente faz a plataforma inteira.
Fazemos toda a parte de Encriptação, Decriptação, Encoding de vídeo.
Você, se vir a ser contratado, virá para trabalhar numa área específica de Backend para atender essa plataforma.
O Streaming de Vídeo é o futuro da distribuição de Vídeo pela internet. O que a gente conhece hoje de distribuição linear de TV, aqueles canais que a gente contrata, isso vai acabar. 100% está se tornando internet. Está se tornando no mundo inteiro. Como a Netflix fez isso, a Amazon Prime, o próprio Itunes, o Google Play...
É com isso que a gente quer que você venha trabalhar.
Distribuição de Vídeo por internet.

![looke para vagas](https://user-images.githubusercontent.com/47364879/53264430-533f8700-36ba-11e9-9b78-0d66cc338908.png)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
