### ISSUE TITLE
[São Paulo] Desenvolvedor Back End PHP na CELEBRYTS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#867]
### Sobre a empresa: Celebryts

A Celebryts é uma startup especializada em Marketing de Influência que usa dados para criar, planejar e gerenciar campanhas publicitárias com foco em resultados reais. Foram criados robôs que analisam grande quantidade de informações de perfis em redes sociais, procurando identificar o melhor perfil para determinada empresa. O mais legal é que o algoritmo coleta todas essas informações organicamente; trata-se de um projeto instigante e desafiador.

### Descrição: Quais são os requisitos básicos?

No mínimo 6 anos de experiência com PHP;
No mínimo 3 anos de experiência com Zend Framework versão 2 ou superior;
Experiência comprovada com APIs RESTful.

### O que brilharia nossos olhos?

Experiência com ReactJS e/ou ReduxJS;
Aptidão para liderança.

### Você gostará de trabalhar na Celebryts se:

Se identifica com um tipo de trabalho acelerado, dentro de uma startup que vem crescendo cada vez mais;
É uma pessoa dinâmica e gosta de trabalhar de forma ágil;
Tem capacidade de trabalhar em múltiplos projetos ao mesmo tempo;
Não se preocupa com horário, mas sim com resultados e entregas;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor.

### Benefícios:

Vale transporte;
Vale refeição;
Horários flexíveis;
No dress code.

### Labels:

PJ
Alocado

### Candidatar: http://bit.ly/celebrytsphp_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
