### ISSUE TITLE
[REMOTO] Arquiteto de Software na IDOX TECNOLOGIA

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#868]
### Sobre a empresa: IDox

Somos uma Startup da República de Curitiba que desenvolve tecnologias cujo objetivo é proporcionar ao advogado um ambiente de escritório virtual. Neste escritório o advogado atende seus clientes, automatiza partes repetitivas na elaboração das peças e até pode obter insights de BI sobre seus processos.

### Descrição: Ocupações do cargo

Arquitetar soluções, criar os testes automatizados e programar.

### Benefícios

-Salário competitivo;
-Participação com possibilidade de vesting;
-Vaga 100% remota;
-Oportunidade de atuar com algo bem avançado.

### Aptidões e qualidades

Arquiteto de software que sabe programar Rails. É necessária muita atenção com a arquitetura, cuidado com os detalhes e saber trabalhar em equipe.

### Candidatar: http://bit.ly/idox_github

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
