### ISSUE TITLE
[Curitiba] Python Developer na Celero

### ISSUE THREAD

**Issue by vinicoelho1074** [backend-br/vagas#870]
Estamos em busca de um(a) Python Developer para o time de desenvolvimento! 
Temos um grande caminho pela frente e você terá bastante liberdade para desenvolver 😉

Você irá planejar, desenvolver e implementar novas funcionalidades na plataforma Celero.

Trabalhará com Python e Django no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e um método de trabalho ágil.

_**Oportunidade para trabalhar no escritório em Curitiba ou remoto.**_

**O que precisamos que você tenha:**

- Sólida experiência comercial com Python + Django;
- Autonomia e pró-atividade;
- Modelagem e consumo de API's RESTful;
- Experiência com Git para versionamento de código.

**Será um diferencial:**

- Bacharel em Ciências da Computação ou equivalente;
- Experiência anterior com Testes unitários;
- Modelagem de bancos de dados relacionais (preferencialmente PostgreSQL)
- Experiência anterior com NoSQL;
- AWS (preferencialmente EC2, RDS e S3);
- Ser autodidata;
- Ter espírito empreendedor;
- Conhecer o ambiente de startups;
- Experiência na área de gestão financeira.

Se identificou? 💚 Envie o seu currículo e pretensão salarial para carreira@celero.com.br

**Comment by felipsmartins** [comment]
Olá, Kyvia Carvalho! 
Tudo bem?

Encontrei a vaga no linkedin primeiro hoje, mas no link de para candidatar-se está apontando para um URL não disponível, talvaz devesse apontar para cá. Ainda bem que enconrei esse post via Google. Vou enviar.

**Comment by gbbocchini** [comment]
@kyviacarvalho continua aberta essa vaga? Aceita remoto dentro do PR? Tks
