### ISSUE TITLE
[Curitiba, PR] Desenvolvedora(dor) Serverless na ONLi

### ISSUE THREAD

**Issue by brendonmatos** [backend-br/vagas#872]
Olá! 

A ONLi é uma Startup especializada em soluções de seguro. 

Estamos procurando alguém que possa compor nosso time na parte do Back-End. Ele está totalmente serverless, e totalmente em Node.js. Estamos precisando criar mais serviços que não necessariamente precisam ser em Node.js

Estamos procurando um desenvolvedor com apenas UM requisito:
- Dominar uma dessas linguagens: Python, Go, JavaScript, TypeScript, Java ou Kotlin

Diferenciais:
- Ter algum projeto utilizando Serverless (https://serverless.com/)
- Ter algum projeto utilizando Apex (http://apex.run/)
- Ter algum projeto utilizando Up (https://github.com/apex/up)
- Ter algum projeto utilizando Zappa (https://github.com/Miserlou/Zappa)
- Ter algum projeto utilizando Firebase
- Dominar Node.js
- Contribuições Open Source

O que utilizamos no back:
- Node.js
- AWS DynamoDB
- Aurora Serverless Database
- AWS Lambda
- API Gateway - REST API e WebSockets

Utilizamos no Front:
- WebSockets
- Vue.js
- Nuxt.js

Benefícios:
- Horário Flexível
- Escritório localizado na área do Água verde.

Salário: 3.5k

Regime: PJ

Contato: brendon@onli.com.br

**Comment by rbezerra** [comment]
aceitam remoto?

**Comment by gislainy** [comment]
@brendonferreira aceita remoto?

**Comment by brendonmatos** [comment]
@rbezerra @gislainy No momento estamos buscando pessoas apenas no modelo presencial
