### ISSUE TITLE
[Rio de Janeiro - Barra da Tijuca] DEV BACKEND na INCHURCH

### ISSUE THREAD

**Issue by LuanaMoreira** [backend-br/vagas#874]
E aí, tem interesse em trabalhar em uma startup referência na construção de aplicativos para o terceiro setor na América Latina?! Chegou ao lugar certo!

Nós da inChurch fazemos parte do inRadar Group, uma marca de soluções para grupos e organizações. Desenvolvemos Apps, Portais Web, Totens Interativos e tudo que for importante para entregar conveniência para os nossos usuários.

Fazemos tudo isso aqui na Barra da Tijuca-RJ em um ambiente informal e descontraído com área de games e um lounge pra dar aquela relaxada. (;

Vem crescer com a gente!

**Nossos Benefícios:**

✔️ Assistência médica
✔️ Auxílio academia
✔️ Auxílio combustível
✔️ Convênio com empresas parceiras
✔️ Vale-refeição
✔️ Vale-transporte

*Estamos trabalhando com Pretensão Salarial*

_**DEV BACKEND**_

**Suas Habilidades Técnicas:**

✔️ Domínio de Python com algum framework de backend (Django/Flask);

✔️ Familiaridade com APIs REST e desenvolvimento de serviços, preferencialmente com Django REST Framework ou Tastypie;

✔️ Experiência em versionamento de projetos com Git;

✔️ Experiência no desenvolvimento de testes unitários automatizados;

**Sua Missão:**

✔️ Desenvolver e refatorar serviços para APIs REST;

✔️ Criar rotinas de teste automatizadas e pipelines de integração contínua;

✔️ Documentar detalhadamente os serviços desenvolvidos.

**Requisitos a +:**

✔️ Proficiência em inglês a partir do nível intermediário;

✔️ Desenvolvimento de código utilizando metodologias ágeis.

**Etapas do Processo Seletivo:**

✔️ Inscrição

✔️ Testes Online

✔️ Entrevista RH

✔️ Entrevista Requisitante

✔️ Proposta&Admissão

**Local de Trabalho: Barra da Tijuca 
Modalidade: Presencial (Flexível)**

Para participar da nossa seleção envie seu currículo ou URL do seu Linkedin com pretensão salarial para [[rh@inchurch.com.br](mailto:rh@inchurch.com.br)] com o assunto ''DEV BACKEND GITHUB''

#vemcrescercomagente

**Comment by lucasperrotta** [comment]
Há a possibilidade de 100% remoto?
