### ISSUE TITLE
[Remoto] Sysadmin – Freela

### ISSUE THREAD

**Issue by hmaesta** [backend-br/vagas#876]
Busco freelancer para refazer estrutura de 4 servidores de aplicação em Laravel (PHP) e MongoDB. 

Os servidores são administrados no [Forge](https://forge.laravel.com) e estão na DigitalOcean. Todos rodando Ubuntu 18.04 x64.

Problemas enfrentados atualmente:
- servidores fora do ar em momentos de pouca demanda (reboot = volta ao normal)
- uso excessivo de memória ou swap (reboot = volta ao normal)
- dificuldade de leitura de uso de servidor (histórico de uso, requisições diárias, etc)
- dificuldade para ler o que pode estar causando os problemas

Precisamos de alguém que...

Primeiramente, configure um dashboard pra gente ler onde está a carga do servidor, o histórico do CPU, memória, etc. Por exemplo, instalar algo similar ao [nginx Amplify](https://amplify.nginx.com) de forma que todos os erros fiquem centralizados (de início o Amplify supriu a necessidade, mas verificou-se baixa confiabilidade nas informações – e, do nada, parou de registrar).

Após fornecer uma forma fácil de ler os dados, aplicar soluções para os problemas.

Obviamente não será algo de "um dia", pois será necessário que o freelancer monitore os servidores por alguns dias para ver o comportamento.

Específicações mais detalhadas serão enviadas por e-mail (o que é a aplicação em si, o que cada servidor faz, etc).

## Requisitos

*Obrigatórios*

- Experiência com serviços similares (se puder, explique trabalhos anteriores)
- Experiência com PHP e Laravel (o freela é pra sysadmin, mas é interessante conseguir compreender o funcionamento da aplicação)
- Experiência com Ubuntu 18.04

*Desejáveis*

- Experiência com [Forge](https://forge.laravel.com)

## Como se candidatar
Envie um email para [hmaesta+fsys@gmail.com](mailto:hmaesta+fsys@gmail.com) com **CV e experiências anteriores**
➡️ Título do e-mail: `Freela: Sysadmin`

💰 Irei enviar mais informações por e-mail e assim você poderá passar uma estimativa de preço e prazo.

⚠️ **E-mails sem experiência anterior** não serão respondidos.

## Labels

- Remoto
- Freela

**Comment by worais** [comment]
Se poder lhe dar um conselho migra logo pra AWS, lá tem o CloudWatch que centraliza todas as métricas vc pode configurar um canal no SNS e já receber os alertas por SMS e tals...  o problema do consumo de memoria não é comum pro nginx (a menos que seja alguma configuração de keep-alive ou cache) é bem mais provável que seja na aplicação...

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
