### ISSUE TITLE
[Remoto] Full Stack Developer @FeelTech

### ISSUE THREAD

**Issue by GiuButtenbender** [backend-br/vagas#8761]
## Nossa empresa

Feel Tech é uma consultoria de pesquisa e desenvolvimento de pessoas com foco em inovação, E COM MUITO AMOR pelo que faz!

Estamos com uma oportunidade para atuar em uma empresa que você consegue apoiar clientes de toda a América Latina, atuando com tecnologias de ponta, e em uma empresa que após o desenvolvimento de seus profissionais.

## Descrição da vaga

Pessoa Desenvolvedora Full Stack para atuar em projetos com inovação e inteligência de mercado.
Sobre as responsabilidades deste profissional:
Desenvolver código limpo e funcional, no back-end e front-end das aplicações;
Participar ativamente dos momentos de planejamento, revisão, diárias do tempo junto com Product Managers e Product Designers para construir aplicações aderentes à proposta de valor;
Desenvolver front-end seguindo as diretrizes de design aplicações da companhia;
Testar as aplicações para garantir desempenho, responsividade e eficiência;
Redação técnica dos produtos e processos;
Trabalhar na evolução do produto, em especial, na escalabilidade do mesmo e na exploração de novos modelos de negócio.

## Local

Remoto

## Requisitos

**Obrigatórios:**
•	Experiência em desenvolvimento Web (Javascript, HTML e CSS);
•	Experiência em desenvolvimento front-end (Vue,js, React, Angular);
•	Experiência em construção de APIs e serviços (Node.js e express.js);
•	Conhecimento em banco de dados relacional (Postgres, MySQL, Oracle, SQL Server, etc);
•	Conhecimento em banco de dados não relacional (MongoDB, Redis, Dynamo DB, etc);
•	Conhecimento consumindo dados do Data Warehouse BigQuery (diferencial);
•	Conhecimento em arquitetura de software (microsserviços, aplicações monolíticas, etc) (diferencial);
•	Conhecimento em CI/CD, Jenkins (diferencial);
•	Conhecimento em Arquitetura, padrões de projeto e código limpo (diferencial);
•	Conhecimento em Testes Automatizados (unitário, E2E, integração, entre outros) (diferencial);
•	Conhecimento em Arquitetura Cloud, AWS (Elastic Beanstalk, Lambda Functions, EC2, S3, etc) (diferencial);
•	Noções de metodologias ágeis, em especial na criação de produtos (diferencial);
•	Uso de sistemas de design em construção de produtos digitais (diferencial);
•	Conhecimento em Design de digitais, principalmente aplicações para visualização de produtos de dados (diferencial).

Soft skills que serão valorizadas:
•	Foco no resultado;
•	Boa comunicação;
•	Trabalho em equipe.

## Benefícios

•	Plano de saúde
•	Plano Odontológico
•	Seguro de vida
•	VR/VA

## Contratação

CLT a combinar

## Como se candidatar

Fale com a nossa Central da Pessoa inscreva-se junto ao nosso Gaby Direto e encontre os desafios mais alinhados ao seu momento profissional!

Chama no link e conheça a nossa GabyBot: [https ://bit.3LZlNEly/3LZlNEc](https://bit.ly/3LZlNEc)

Visite também nosso site, conheça e muitas outras oportunidades.

https://feeltechrh.com.br/sou-profissional/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by venturion** [comment]
Anuncie em https://devance.com.br 👍
