### ISSUE TITLE
[REMOTA] Back-end Developer @ Payfy

### ISSUE THREAD

**Issue by tavarescarolina** [backend-br/vagas#8766]
## Nossa empresa

Somos uma empresa inovadora localizada em Florianópolis, capital do estado de Santa Catarina, também conhecida como “Ilha do Silício”. Neste contexto, criamos uma plataforma para ajudar empresas a otimizarem seus recursos financeiros, seu tempo e principalmente o dia-a-dia dos colaboradores.

## Descrição da vaga

Vaga para desenvolvedor/a back-end júnior em Elixir

## Local

Vaga 100% remota

## Requisitos

**Vaga exclusiva para mulheres e pessoas negras.**
Não é necessário saber elixir, nem ter experiência prévia, apenas alguma linguagem de programação e ter um projeto de autoria própria para apresentar. Caso prefira, podemos enviar um desafio técnico.

## Detalhes da vaga

Salário: R$ 2.500,00 PJ
40 horas semanais
Carga horária flexível (20h semanais)
Horários flexíveis

## Como se candidatar

Envie uma mensagem no linkedin para https://www.linkedin.com/in/carolina-pinheiro-tavares/ 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by RuiJ72** [comment]
Olá viva, boa tarde.
Tentei entrar em contato via linkedin com a recrutadora mas não está sendo possível. Haverá possibilidade de outra forma, email ou outra?
Grato
