### ISSUE TITLE
[São Paulo] Desenvolvedor(a) NodeJS / .Net Core [ Fcamara ]

### ISSUE THREAD

**Issue by jakeliny** [backend-br/vagas#877]
## Vagas
Para você que gosta de desafios, estou buscando Desenvolvedor Node.js e .Net Core, Pleno ou Senior, CLT ou PJ

## Como se candidatar
Interessados ou indicações, enviar CV para [jakeliny.pereira@fcamara.com.br](mailto:jakeliny.pereira@fcamara.com.br)

## Nossa empresa
A FCamara Formação e Consultoria iniciou suas atividades em 2008 com o objetivo de servir com excelência as demandas de verificação de desempenho de aplicações e organização de times de desenvolvimento. Hoje, somos referência em transformação digital através de um método próprio, o High Performance Team, que ajuda empresas a desenvolver projetos e ideias de negócio de forma mais eficiente. Inovação, tecnologia e empreendedorismo fazem parte de quem somos. Queremos ser uma empresa útil e funcional. Útil porque possuímos serviços e produtos necessários. Funcional porque nossos serviços e produtos realmente solucionam e representam valor agregado ao Cliente.

Venha fazer parte do #SangueLaranja. Seja um de nossos clientes ou consultores. Aqui suas ideias tem valor!

## Labels
* CLT
* PJ
* Senior
* Pleno

**Comment by brunooomelo** [comment]
aceita remoto?

**Comment by jakeliny** [comment]
@brunooomelo  Infelizmente não, apenas presencial :)

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
