### ISSUE TITLE
[Barueri - Alphaville] Desenvolvedor(a) Back-End/Full Stack na Partner Group

### ISSUE THREAD

**Issue by danielsalviati** [backend-br/vagas#880]
## Descrição da vaga

Desenvolvedor Full Stack com experiencia em React.Js e .C#. 
Desenvolvedor Back-End com experiencia C#. 

Temos 4 vagas:
- Home Office - Desenvoledor Full Stack - Pleno ou Senior - Temporário (contrato de 3 meses) **[VAGA PREENCHIDA]**
- Home Office - Desenvolvedor C# - Pleno ou Senior - Temporário (contrato de 3 meses) **[VAGA PREENCHIDA]**
- Alocado  - Desenvoledor Full Stack - Junior ou Pleno - Fixo por tempo indeterminado
- Alocado  - Desenvolvedor C# - Junior ou Pleno - Fixo por tempo indeterminado

## Local

Escritório, Barueri - Alphaville

#### Diferenciais
- Horário Flexível
- Ambiente descontraído
- Equipe experiente

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com React.Js
- 2 anos de experiência com C#

## Contratação
PJ a combinar

## Nossa empresa

Somos um Grupo de empresas com 600 funcionários, atuamos no mercado financeiro com plataformas inovadoras no nicho de empréstimos, prevenção a fraudes, pontos, automação, entre outros.

## Como se candidatar

Por favor envie um email para daniel.salviati@partnergroup.com.br com seu CV anexado - enviar no assunto: [VAGA] FULL STACK ou  [VAGA] BACK END ou se preferir whatsapp (11) 9 9587 1973.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniel.salviati@partnergroup.com.br

## Labels

- Alocado
- PJ

**Comment by netoestacio** [comment]
Somente C#?

**Comment by danielsalviati** [comment]
Sim, no momento apenas C#. Obrigado.
