### ISSUE TITLE
[São José Rio Preto/SP ou Remoto] Dev Fullstack na [SMS Digital]

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#881]
# Descrição da vaga
A SMS Digital é uma franqueadora no segmento de comunicação digital.
Hoje nosso carro chefe é o envio de SMS, mas estamos incluindo em nosso portfólio a comunicação via WhatsApp e esta previsto para o segundo semestre terminações de voz sobre IP.
O programador cuidará do site/sistemas utilizados por nossos cliente e franqueados, promovendo alterações em layout e implementando novos recursos.

# Local
São Jose do Rio Preto, São Paulo ou remoto.

# Conhecimentos 
## Indispensáveis:
* C#
* ASP.net MVC/Web Forms
* JavaScript
* SQL Server

## Desejáveis
* TypeScript
* Vue.js
* Redis

# Contratação
CLT ou PJ.

# Benefícios
## CLT
* Salário Compatível
* Vale Transporte
* Vale Refeição
* Auxilio Plano de Saúde
## PJ
* A combinar.

# Como se candidatar
Enviar CV para rh@smsdigital.com.br, mencionar PROGRAMADOR WEB no assunto

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
