### ISSUE TITLE
[REMOTO] Java Back-end Developer @ CIBERNIX

### ISSUE THREAD

**Issue by alvarogomes** [backend-br/vagas#8811]
VAGA

Precisamos de 2 Desenvolvedores Backend Java para fazer manutenção de backend/microserviços em Java com Springboot.

Inicio imediato.

Com possibilidade de integrar o time para projetos nacionals.

Enviar github e Disponibilidade.

Tech stack

Springboot
Java
Gitlab

Banco de dados: MySQL
Ambiente: GCP

Contratação

PJ por mês = 4k
HORARIO FLEXIVEL

Nível
Pleno ou Senior

E-mail para se candidatar: [alvaro.brito@cibernix.com](mailto:alvaro.brito@cibernix.com)

**Comment by fabricio-cbnx** [comment]
Vaga ainda aberta
