### ISSUE TITLE
[Remoto] Rails Developer Junior/Pleno @ Catarse

### ISSUE THREAD

**Issue by stephannv** [backend-br/vagas#8827]
## Nossa empresa
O Catarse é a primeira plataforma de financiamento coletivo para projetos criativos criada no Brasil e é hoje um dos principais canais para artistas, jornalistas, quadrinistas, autores, músicos e profissionais do mercado criativo independente tirarem seus projetos do papel. [Saiba mais sobre o Catarse aqui](https://crowdfunding.catarse.me/quem-somos). 

## Descrição da vaga
Estamos buscando pessoas de nível Júnior ou Pleno para entrar no nosso time de desenvolvimento. As atividades serão:
- Desenvolver novas funcionalidades
- Corrigir bugs
- Ajudar na refatoração da aplicação
- Revisar código dos demais membros do time
- Participar nas decisões de implementação

Hoje temos uma base de código escrita principalmente com Ruby on Rails, mas temos um front-end fortemente baseado em Mithril.js, alguns SQL avançados e um ou outro microserviço em Node.js. A curto prazo, temos que dar manutenção nessa stack, mas em paralelo estamos simplificando e executando uma refatoração para voltar tudo para dentro do Ruby on Rails.

## Local
Remoto. O Catarse tem a cultura do trabalho remoto desde a fundação há mais de 10 anos, hoje temos pessoas espalhadas por todo o país e até fora dele, e nem escritório físico temos. Então já sabemos como trabalhar de forma remota e não vamos mudar isso.

## Requisitos
Os requisitos se você pretende se candidatar pra **nível Júnior** são:
- Lógica de programação já não é uma dificuldade pra você.
- Saber usar o Ruby on Rails indo um pouco além do `rails g scaffold`
- SQL básico é um plus, tipo aquele conteúdo da cadeira Banco de Dados I (select, join, left join, where, order e etc)
- Saber pelo menos o básico de HTML e CSS
- Entender o funcionamento básico de uma aplicação web (requisição, resposta)
- Se tiver noção do Git básico também é um plus, tipo um `git pull`, `git commit`, `git push`.

Os requisitos se você pretende se candidatar pra **nível Pleno** são:
- Ter experiência de trabalho no Ruby on Rails pelo menos uns 2~3 anos.
- Estar confortável em entender e manter código javascript
- Estar confortável em entender e manter SQLs que fujam do básico.
- Ter alguma experiência com as libs mais famosas do ecossistema Rails (sidekiq, rspec, devise, pundit e etc).
- Estar confortável no uso Git. 
- Já ter alguma consciência e se preocupar sobre qualidade, organização e performance de código.
- Conseguir resolver por contra própria alguns problemas mais complexos, mas também saber a hora de somar forças e pedir ajuda.

## Benefícios
- Trabalho remoto: você trabalha de casa e tem flexibilidade para construir o seu horário com o time.
- Carga horária reduzida: o full-time no Catarse é de 30 horas semanais para todos da empresa.
- Bem-estar: Você pode usar até 3 horas de suas horas semanais para atividades pessoais de bem-estar (Natação? Corrida? Bicicleta? O que mais te interessar!)
- Folgas remuneradas: Você terá 40 dias de folgas remuneradas por ano.

## Contratação
Contração via PJ
- Júnior: 4k~6k
- Pleno I: 6k~8k
- Pleno II: 8k~10k

## Como se candidatar
Se candidate através desse link: https://catarse.freshteam.com/jobs/RIqZeFgmiFSi/dev-full-stack-ruby-on-rails-jr-ou-pleno-remote

## Tempo médio de feedbacks
Nossa seleção é feita assim:
- Conversa técnica entre devs pra entender as experiências e conhecimentos
- Alguma forma de validação técnica (o candidato pode apresentar as coisas relevantes do seu github, ou então participar de dinâmica no desenvolvimento de uma feature básica num repositório de teste).
- Última conversa para entender o perfil do candidato, verificar se encaixa no nosso time e etc.

Nossos retornos podem demorar cerca de 1~3 semanas, dependendo do andamento do processo de seleção.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by Djamess** [comment]
inscrito
