### ISSUE TITLE
[São Paulo] Desenvolvedor Backend - Turbi

### ISSUE THREAD

**Issue by marciopedrozo** [backend-br/vagas#885]
**Assunto**
Buscamos desenvolvedor em GO, podendo ter experiência de outra linguagem (JAVA, C#, C++, Python)

**Local**
Rua Lisboa, 890, São Paulo - Pinheiros

**Nossa empresa**
Turbi é uma empresa de tecnologia com produto de car sharing, com experiência inovadora, tecnologias novas e ambiente de startup.
www.turbi.com.br

**Descrição da Vaga**
- Conhecer desenvolvimento robusto em uma linguagem de programação com conceitos de tipagem tipo JAVA, C#, C++, GO, etc..
- Entender bem processos síncronos e assíncronos e com boa noção dos funcionamento das linguagens nesses conceitos.
- Conhecer e já ter trabalhado com a construção de API rest. Ter boa aptidão em modelagem de contratos JSON e conhecer os mecanismos padrões de funcionamento de Restful
- Gostar de vincular tecnologia ao negócio e ser fanático por pensar em casos de uso, cenários e tratamento das informações.
- Conhecimento de nível intermediário em bancos relacionais e não relacionais.
- Conhecimento e práticos com testes unitários, integrados.

**Como se candidatar**
Envie e-mail para hiring.it@turbi.com.br colocando no assunto: [Vaga Desenvolvedor Backend] Seu nome

Detalhe no texto do e-mail

Sua experiência (projetos, atuação e tempo) em:
JAVA, C#, C++, GO

detalhe outros conhecimentos relacionados que tenha (Kubernetes, Docker....)

Valor hora
Linkedind
Seu portfólio (GIT/GITLAB/Bitbucket)

Contatos
(email, telefone/whatsapp)

Anexar CV

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 5 dias

**Labels**

- Alocado
- PJ
- Júnior
- Pleno
- Sênior

**Comment by ramonberrutti** [comment]
@marciopedrozo freelance?
