### ISSUE TITLE
[Florianópolis/SC] C# Developer @ ESSS

### ISSUE THREAD

**Issue by Esss0102** [backend-br/vagas#8881]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga
A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE (Computer-Aided Engineering) na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.

Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição e venha simular o futuro conosco!

O[ ](https://rocky.esss.co/)time de desenvolvimento de software do produto Rocky está em busca de um Desenvolvedor de Software.

Você será responsável pelo desenvolvimento de diferentes acoplamentos entre o Rocky e softwares de terceiros. Estes acoplamentos permitem que o Rocky troque informações com outros softwares, utilizando-as para contribuir com as suas simulações, de outros softwares ou ambos.

O Rocky é um projeto desafiador e inovador, um produto desenvolvido pela ESSS e utilizado mundialmente por um número cada vez maior de empresas de diferentes setores.

Mais informações: https://rocky.esss.co/ e https://www.youtube.com/user/RockyDEMSimulator.

Para essa posição seus principais desafios serão (conhecimento prévio nestes itens são valorizados):

- Desenvolver softwares de Computer-Aided Engineering (CAE).
- Desenvolver códigos para integração entre softwares multi-plataforma com testes automatizados (testes unitários e de aceitação).
- Desenvolver algoritmos e estruturas de dados para integração de softwares.
- Realizar correções e aperfeiçoamentos em softwares existentes.

## Local

Remoto ou Escritório, Florianópolis-SC

## Requisitos

- Conhecimentos em desenvolvimento de software.
- Conhecimentos em I/O de arquivos binários e texto.
- Conhecimentos em programação distribuída.
- Inglês intermediário.
- Trabalho em equipe.
- Experiência na área a partir de 4 anos. 

## Benefícios

- Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
- Cartão de benefícios flexíveis.
- Licença maternidade e paternidade estendidas.
- Oportunidade para contribuição em projetos open source.
- Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
- Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
- Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se cadastre no link: https://esss.gupy.io/jobs/1506310

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by DevCleverton** [comment]
> > Vaga Remota durante a pandemia
> 
> ## Nossa empresa
> Exemplo: Aqui na Corporação ACME somos líderes em...
> 
> ## Descrição da vaga
> A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE (Computer-Aided Engineering) na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.
> 
> Se você acredita que seus talentos, e experiências são de alta qualidade para trabalhar, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição conosco e venha simular o futuro!
> 
> O [ ](https://rocky.esss.co/)tempo de desenvolvimento de software do produto Rocky está em busca de um Desenvolvedor de Software.
> 
> Você será responsável pelo desenvolvimento de diferentes soluções entre o Rocky e softwares de terceiros. Estes outros softwares permitiram que o Rocky troque informações com outros softwares, usando-as para contribuir com suas simulações, de ambos.
> 
> O Rocky é um projeto desafiador e um produto desenvolvido pela ESSS e utilizado mundialmente por um número cada vez maior de empresas de diferentes setores.
> 
> Mais informações: https://rocky.esss.co/ e https://www.youtube.com/user/RockyDEMSimulator .
> 
> Para essa seus principais desafios serão (conhecimento prévio nestes itens são valorizados):
> 
> * Desenvolver softwares de Engenharia Assistida por Computador (CAE).
> * Desenvolver integração para softwares multiplataforma com testes automatizados (testes unitários e desenvolvidos entre softwares).
> * Desenvolvimentos e estruturas de dados para integração de softwares.
> * Realizações e perdas em softwares existentes.
> 
> ## Local
> Remoto ou Escritório, Florianópolis-SC
> 
> ## Requisitos
> * Conhecimentos em desenvolvimento de software.
> * Conhecimentos em I/O de arquivos binários e texto.
> * Conhecimentos em programação distribuída.
> * Inglês intermediário.
> * Trabalho em equipe.
> * Experiência na área a partir de 4 anos.
> 
> ## Benefícios
> * Plano de saúde nacional com integral sem coparticipação (melhor operadora da região).
> * Cartão de benefícios.
> * Licença maternidade e paternidades.
> * Oportunidade para contribuição em projetos open source.
> * Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílios idiomas.
> * Incentivo de publicações, participações em eventos relevantes para seu trabalho.
> * Mais de 20 outros benefícios.
> 
> ## Contratação
> CLT
> 
> ## Como se candidatar
> Se cadastre no link: https://esss.gupy.io/jobs/1506310
> 
> ## Rótulos
> #### Alocação
> * Alocado
> * Remoto
> 
> #### Regime
> * CLT
> 
> #### Nível
> * Pleno
> * Senior
> * Especialista
