### ISSUE TITLE
[REMOTO] Back-end Developer PHP @ Postmetria

### ISSUE THREAD

**Issue by flavialpo** [backend-br/vagas#8882]
Vaga Remota

Eu falo Dev e você diz remoto. Vamos lá?! 🗣️
- Dev?
- Remoto!!

Você quer ter liberdade para criar e trabalhar de forma flexível e remota num ambiente colaborativo?
Então você achou seu lugar ao sol! 😎
Na Postmetria, priorizamos muito a qualidade de vida dos nossos colaboradores. Por isso, damos até duas sextas-feiras livres no mês, além de um day off de presente de aniversário! 🎁

Se você tem experiência no desenvolvimento e manutenção de plataforma web e seus micro-serviços, análise de performance do sistema e uso de tecnologias e técnicas para aumentar sua
escalabilidade, revisão e aplicação de melhores práticas de segurança da informação no desenvolvimento. Assim como Code review, testes automatizados e deploy automático de código e Pesquisa e projeto de novas funcionalidades...
... continue lendo esse anúncio porque estamos prestes a dar um match! 🤩

📚 Buscamos um(a) profissional com:
- Conhecimentos sólidos em engenharia de software para aplicações web e micro-serviços;
- Experiência mínima de 3 anos em desenvolvimento backend, utilizando linguagem PHP e frameworks como Laravel ou Yii2;
- Experiência com base de dados relacionais e NoSQL e com práticas ágeis.

É desejável:
- Experiência com Google Cloud Computing, conteinerização (Docker, Kubernetes, …),
ElasticSearch, segurança da informação, código limpo e que atenda convenções e
inglês.

Diferenciais:
- Liberdade e autonomia para criar
- Horário flexível
- Até 2 6as feiras livres no mês - Dia do Relax
- Day off de aniversário

Regime
- CLT ou PJ

Nível
- Pleno

Se animou?! Vem para a Postmetria! 🚀
Aqui você vai aprender muito em um ambiente inovador e dinâmico
e, ainda por cima, trabalhar com propósito!

Se identificou com a oportunidade?
Então encaminhe o seu currículo para este e-mail:
📩 [rh@postmetria.com.br](mailto:rh@postmetria.com.br)

**Comment by flavialpo** [comment]
up

**Comment by devXela** [comment]
Mandando email com currículo

Att,

Alex Rosa Santos Barbosa
Desenvolvedor PHP

Em seg., 30 de mai. de 2022 às 16:08, Flavia Lopes ***@***.***>
escreveu:
