### ISSUE TITLE
[São Paulo/SP] Backend Developer na 18digital

### ISSUE THREAD

**Issue by samir-jorge-araujo** [backend-br/vagas#89]
## Descrição da vaga

Procuramos um(a) Programador(a) Laravel / PHP com experiência comprovada para ser efetivado em nossa equipe e coordenado por especialista em projetos para startups. 
As atividades serão no desenvolvimento de aplicações web, web services e micro serviços com Laravel 5.x.x

## Local

Escritório na Rua Itambé, 341 - Higienópolis

## Benefícios

- Férias remuneradas
- Política de cursos
- Bônus por performance/produtividade

#### Diferenciais

- Monte a sua máquina como desejar
- Cerveja liberada na sexta-feira

## Requisitos

**Obrigatórios:**
- Experiência significativa com desenvolvimento de software
- Conhecimento sólidos com javascript (sem jquery / mootools, etc.)
- Proficiência em webpack
- Conhecimento em design patterns para css
- Desenvolver códigos sustentáveis e saber testá-los
- Saber usar sistema de controle de versões (git)
- Conhecimento de pré-processadores css (sass / stylus / less)
- Integração com apis rest
- Essencial ter código limpo, organizado, reutilizável e testável

**Desejáveis:**
- Conhecer bem Javascript
- Conhecimento em linha de comando linux
- Conhecimento em photoshop e sketch (básico - corte de imagens)

## Contratação

PJ a combinar

## Nossa empresa

Conectamos a realidade dos negócios com a melhor experiência digital para todos, da maneira mais orgânica possível.
Nenhum projeto é igual e cada desenvolvimento da 18digital tem sua própria assinatura. Com a sua ideia ou desafio vamos mergulhar, planejar e executar com o espirito de quem respira e se realiza no ambiente virtual e não consegue deixar de lado uma boa história!

## Como se candidatar

Por favor envie um email para trampo@18digital.com.br com seu CV anexado - enviar no assunto: Vaga Backend Developer

## Labels

- Alocado
- PJ
- Pleno/Sênior

**Comment by reginaldojunior** [comment]
Vaga preenchida?

**Comment by samir-jorge-araujo** [comment]
@reginaldojunior acabamos de abrir mais uma para essa mesma descrição.
Devo abrir uma nova issue?

**Comment by reginaldojunior** [comment]
Abre, acho melhor que ela vai para primeira página ;)
