### ISSUE TITLE
[Remoto] Full Stack Developer @ Apus

### ISSUE THREAD

**Issue by vcromeiro** [backend-br/vagas#8903]
## Nossa empresa

A Apus – Soluções em TI nasce da junção de empresas de tecnologia da informação e consultoria, com o propósito de construir e propor soluções personalizadas, criativas e eficientes, que gerem maior qualidade e precisão no trato das informações de seus clientes.

Especializados em Gestão Educacional, porém, criando soluções para um universo cada mais plural de clientes, temos diferentes soluções perante a gestão, ensino à distância e avaliação tanto para a educação pública, quanto a privada, além de trabalhos de assessoramento e consultoria.

## Descrição da vaga

Desenvolvimento de aplicações Web utilizando a linguagem PHP (Laravel).

## Local

Home office/remoto.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento de aplicações para Web.
- PHP 7.x com experiência em orientação a objetos;
- Conhecimentos avançados em desenvolvimento utilizando o framework Laravel;
- Experiência com banco de dados relacionais (Conhecimento em PostgreSQL é um diferencial);
- Saber trabalhar com versionamento de código (Git);

**Desejáveis:**
- Estar familiarizado com os principais padrões de desenvolvimento em PHP e Javascript;
- Saber trabalhar com conteinerização utilizando Docker e Docker Compose.

**Diferenciais:**
- Conhecimento em React

## Atividades
- Trabalhar em implementações de novas aplicações REST feita em PHP, utilizando o framework Laravel e na manutenção dos sistemas da empresa;
- Ajudar nas decisões de arquitetura sobre novas partes do projeto;
- Desenvolver as telas front-end utilizando Javascript com Typescript.

## Contratação

PJ a combinar

## Como se candidatar

Enviar e-mail com pretensão salarial utilizando o assunto: Desenvolvedor(a) Full Stack
Para: desenvolvimento@apus.info

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by williambh** [comment]
Tenho interesse em contribuir com a empresa, mas não posso fulltime.
Tenho ampla experiência em postgresql e PHP, e já utilizo laravel em vários projetos da Universidade que trabalho. UFVJM
