### ISSUE TITLE
[São Paulo ]DESENVOLVEDOR BACKEND - Java - Stefanini

### ISSUE THREAD

**Issue by VagasStefanini** [backend-br/vagas#895]
Stefanini:  Líder reconhecida no setor global de tecnologia, estamos presentes em mais de 40 países, atuando em conjunto com nossos clientes, cocriando soluções para um futuro melhor. Estamos esperando você para atuar como **Desenvolvedor Backend** em um grande projeto de "Banco Digital" para atuar em São Paulo, se você tem experiencia com:

•	Linguagem de programação: Java 7 ou superior
•	Conhecimento em controle de versão (GIT)
•	GitFlow
•	Gestão de dependências (Gradle)
•	Criação e integração com API’S REST/SOAP
•	Framework Spring
•	Banco de Dados: SQL
•	Conceito de Microserviços

Desejáveis

•	Testes (Unitários, Integração e Interface)
•	Injeção de dependências
•	Bons conhecimentos de Design Patterns
•	Vivência com metodologias ágeis (SCRUM, Kanban, XP, etc)
•	Banco de Dados: NoSQL, MongoDB
•	Mensageria: JMS
•	Infraestrutura: AWS
•	Cache: MemCached, Redis

Salario: à combinar.

Não perca tempo, envie seu currículo para: aiclaudino@stefanini.com ou se inscreva pelo link: https://is.gd/SFK6B4 (é so anexar o seu currículo)

**Comment by JosephSousa** [comment]
Aberta ainda a vaga?
