### ISSUE TITLE
[Remoto] Back-end Developer @ Codeminer42

### ISSUE THREAD

**Issue by talyssonoc** [backend-br/vagas#8953]
## Nossa empresa

A Codeminer42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Começando suas operações em Setembro de 2011 com os melhores profissionais e desenvolvedores do país.

## Descrição da vaga

Na Codeminer42 você terá a oportunidade de trabalhar com os mais diversos tipos de projetos, com tecnologias variadas e um time de pessoas incríveis que estarão sempre prontas a te ajudar no que você precisar. Incentivamos o diálogo e o compartilhamento de conhecimento e apoiamos o desenvolvimento open-source.

Alguns desafios farão parte dessa trajetória:

- Trabalhar juntamente com times diversificados;
- Buscar novos conhecimentos e tecnologias;
- Não ter medo de se adaptar. Buscamos e incentivamos o aprendizado;
- Saber se comunicar é de extrema importância.

## Local

Remoto ou em algum dos nossos escritórios físicos (listados na página de vagas).

## Descrição

- Pelo menos 3 anos de experiência em desenvolvimento back-end moderno usando a linguagem Ruby, e ter finalizado um curso superior relacionado à area de desenvolvimento em uma faculdade de primeira linha. Nesta denominação não se encaixam bootcamps;

- Experiência com bancos de dados SQL;

- Experiência com CI/CD e testes automatizados;

- Conhecimentos em HTML, CSS e Javascript;

- Interesse em aprimorar suas habilidades através da prática em diferentes projetos, incluindo projetos de clientes e open source;

- Disposição para trabalhar em um ambiente de organização horizontal onde o "sim, senhor" não é aceito e as críticas proativas são sempre bem-vindas;

- Inglês avançado. Temos clientes internacionais e uma boa compreensão e conversação são fundamentais. O inglês é de extrema importância e será parte do processo seletivo.

- Para candidatos ainda sem experiência, possuímos um [programa de trainee](https://trainee.codeminer42.com/);

## Extras

- Conhecimentos de infra-estrutura. Heroku e AWS são amplamente utilizados no dia a dia;
- Conhecimentos de bancos de dados não-relacionais;
- Conhecimentos em arquitetura de software;
- Conhecimentos de frameworks de UI como React, React Native, Vue ou Angular.

## Benefícios

- Plano de saúde e dental;
- Vale-refeição;
- Vale-transporte;
- Curso de inglês para aperfeiçoamento;
- Acesso a livros e cursos de programação.
- Reembolso para atividade física;

**Diferenciais:**
- Ambiente de trabalho informal;

## Contratação

CLT ou PJ a combinar.

## Como se candidatar

Através do site: https://www.codeminer42.com/careers

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio
- PJ

#### Nível
- Pleno
- Sênior

**Comment by talyssonoc** [comment]
Up

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
