### ISSUE TITLE
[Remoto] PHP/Wordpress Developer na Orbital

### ISSUE THREAD

**Issue by wallaceerick** [backend-br/vagas#8966]
## Empresa
Somos a [Orbital](https://orbital.company), empresa de tech & inovation que atua diretamente na concepção e construção de produtos inovadores para startups e multinacionais.

## Vaga
Estamos recrutamento profissionais de Wordpress para criação, desenvolvimento e manutenção de temas e plug-ins. 
Além disso, pessoas que:
- Gostem de lidar com projetos grandes e desafiadores;
- Sejam detalhistas e analíticas em relação ao código;
- Trabalhem em equipe de forma colaborativa;
- Se preocupem com a entrega do projeto;
- Busquem aprendizado constante.

## Local
Remoto (temos um escritório na Vila Olímpia que pode ser utilizado)

####  Obrigatórios
- 3 anos de experiência com Wordpress, PHP e Javascript
- Experiência com o desenvolvimento de aplicações complexas
- Consumo de APIs Restfull
- Git Workflow

####  Desejável
- Laravel
- Integração Contínua

####  Diferencial
- Vue.js

## Benefícios
- Auxílio Home-Office

## Contratação
- PJ 

## Candidatos
Por favor, [preencha esse formulário](https://orbital.company/vagas?id=8) com suas informações pessoais.

## Feedbacks
Entraremos em contato com os candidatos selecionados em 3 ou 5 dias.

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior

**Comment by wallaceerick** [comment]
Atualizado!

**Comment by wallaceerick** [comment]
Atualizado!

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
