### ISSUE TITLE
[Teresópolis] Back-end Developer @Noclaf Tech

### ISSUE THREAD

**Issue by Toledopamella** [backend-br/vagas#8976]
OPORTUNIDADE: 

Vaga para uma grande empresa reconhecida no país pelo desenvolvimento Tecnológico.

 Vaga para:

Desenvolvedor Back End - Pleno e Sênior

Requisitos:

* Necessário residir em Teresópolis (RJ) / Rio de Janeiro ou Região Serrana do Rio

* Ter formação acadêmica

Vaga: CLT

Híbrido

Interessados enviar e-mail: pamellatoledo@noclaftech.com 

Favor anexar o currículo atualizado com pretensão salarial!

**Comment by jonathan-mothe** [comment]
Quais são os requisitos técnicos da vaga?

**Comment by Toledopamella** [comment]
Bom dia,Ser um Desenvolvedor Back, dominando as linguagens dentro da linguagem.At,Em 8 de abr. de 2022 09:43, Jonathan Mothé ***@***.***> escreveu:

Quais são os requisitos técnicos da vaga?

**Comment by rondirio** [comment]
Enviei uma mensagem no LinkedIn. Te respondendo.
