### ISSUE TITLE
[Remoto] PHP Developer @CRMThink

### ISSUE THREAD

**Issue by JaquelineCD** [backend-br/vagas#8982]
Nós da Culture Designer estamos apoiando nosso cliente: CRM Think, na busca de um (a) profissional para atuar como  **Desenvolvedor PHP Júnior ou Pleno**. A oportunidade é para atuar de forma híbrida em Joinville ou 100% remoto em qualquer lugar do Brasil.

**Conheça um pouco mais sobre a CRM Think:** 

Um dos principais parceiros Bitrix24 no Brasil, além de atuação em projetos em países como EUA, Rússia, Portugal e Andorra.
Indicado ao Prêmio Best Bitrix24 Partner Awards 2020 – Best Cloud Seller com Melhores resultados de vendas anuais de produtos Cloud.

Trata-se de uma empresa na área de tecnologia em franco crescimento.

Uma empresa com cultura organizacional forte, pautada na valorização das pessoas e incentivo contínuo ao autodesenvolvimento. Convidamos você para ingressar em um time fantástico e construir sua jornada de sucesso nesta empresa que é referência no Brasil em sua área de atuação. 
Visite o site da empresa:  https://www.crmthink.com.br/

**Principais responsabilidades do cargo:**

- Manutenção nos produtos ativos em PHP;
- Construção de novos produtos.

**Hard Skills**

- Linguagem de programação: PHP;
- Framework: Laravel;
- Banco de Dados: My SQL ou PostgreSQL;
- Conhecimento em CRM será considerado diferencial.

**Soft Skills**

- Trabalho em equipe;
- Raciocínio Lógico apurado.

**Remuneração**: estamos avaliando a remuneração conforme skills, experiência e pretensão salarial;
**Modalidade**: (MEI/PJ);
**Local**: Híbrido em Joinville ou Remoto.

Email: jaqueline@culturedesigner.com.br

**Comment by engfabiorogerio** [comment]
[CURRICULO DEV.docx](https://github.com/backend-br/vagas/files/8456903/CURRICULO.DEV.docx)

Bom dia,
Segue em anexo CV para participação no Processo.

Att,.
Fábio Rogério de Moraes e Silva

**Comment by lsena-web** [comment]
Olá, meu nome é Lucas, sou desenvolvedor PHP júnior formado em análise e desenvolvimento de sistemas.

segue em anexo o currículo ^^

[currículo.pdf](https://github.com/backend-br/vagas/files/8459875/curriculo.pdf)

**Comment by caiorabelo** [comment]
Bom dia,

Segue em anexo CV para participação do processo no nível Pleno.

[Curriculo_Caio_Rabelo.pdf](https://github.com/backend-br/vagas/files/8463487/Curriculo_Caio_Rabelo.pdf)

**Comment by marcosyamashita** [comment]
Boa noite. Segue meu currículo para vaga.
[Curriculo Linkedin Marcos Yamashita.pdf](https://github.com/backend-br/vagas/files/8468477/Curriculo.Linkedin.Marcos.Yamashita.pdf)

**Comment by hgf777-br** [comment]
Bom dia,

Segue meu currículo em anexo.

Obrigado pela atenção.

[Curriculo HGF - português.pdf](https://github.com/backend-br/vagas/files/8482037/Curriculo.HGF.-.portugues.pdf)

**Comment by marcelocastelari** [comment]
Olá, segue currículo em anexo.

[Currículo - Marcelo Castelari.pdf](https://github.com/backend-br/vagas/files/8483337/Curriculo.-.Marcelo.Castelari.pdf)

**Comment by gustavosillva0256** [comment]
Olá, segue currículo em anexo para participação da vaga
[cv_GUSTAVO PEREIRA.pdf](https://github.com/backend-br/vagas/files/8485303/cv_GUSTAVO.PEREIRA.pdf)

**Comment by ViniciusCampos12** [comment]
Boa tarde , segue currículo em anexo para vaga de Desenvolvedor Júnior

[VINICIUS-H-CAMPOS-CURRICULO-2021 (1) (1).docx](https://github.com/backend-br/vagas/files/8500189/VINICIUS-H-CAMPOS-CURRICULO-2021.1.1.docx)

**Comment by VitorParisio** [comment]
Boa noite. Segue em anexo meu currículo para uma possível análise a vaga desenvolvedor junior.
[Vitor Parísio- Currículo.pdf](https://github.com/backend-br/vagas/files/8502592/Vitor.Parisio-.Curriculo.pdf)

**Comment by murilolivorato** [comment]
nao tem um email que possa enviar cv ?  nunca vi isso . kkkk
