### ISSUE TITLE
[REMOTO] Pessoa desenvolvedora Python na Cloudia

### ISSUE THREAD

**Issue by raivitor** [backend-br/vagas#899]
**Descrição da empresa**

Quer trabalhar em uma startup em crescimento acelerado e com o objetivo de ajudar milhões de pessoas a acessarem estabelecimentos de saúde de forma ilimitada, através da tecnologia e sem complicações?

A Startup Cloudia criou um chatbot para estabelecimentos de saúde que usa inteligência artificial e NLU para atendimento aos pacientes.

Aqui você terá a oportunidade de criar produtos e processos novos, se desenvolver e crescer junto com a empresa.

Saiba mais sobre a Cloudia em https://www.cloudia.com.br/sobre-nos/

**Atividades e Responsabilidades**

Esta vaga é para trabalhar principalmente na evolução e manutenção do nosso Chatbot, desenvolvido em Python. Por isso, precisamos que você ame e domine essa linguagem e já tenha alguma experiência anterior com desenvolvimento de software em Python. 

Você também poderá ajudar na evolução e manutenção de outros softwares da nossa empresa desenvolvidos em outras linguagens e outros frameworks.

_O trabalho pode ser parcialmente ou 100% remoto._

**Requisitos**

Antes de tudo você precisa estar alinhado com os valores da empresa e ter uma atitude empreendedora e pró-ativa para entrar no time da Cloudia. Veja nossos valores em https://www.cloudia.com.br/sobre-nos/

É pré-requisito ser apaixonado por aprender e gostar muito de tecnologia, dominar a linguagem Python, além de ter muito interesse em desenvolver suas habilidades em outras tecnologias, linguagens e frameworks que utilizamos.

Experiência prévia com métodologia SCRUM e uso de GIT para versionamento de código são desejáveis.

São considerados diferenciais conhecer a metologia Lean Startup, ter o inglês avançado, ter conhecimento em Node.js, conhecer o funcionamento da AWS, além de Docker, CICD e TDD.

**O que nós oferecemos**

- Muito aprendizado. 
- Fazer parte de um time que ama tecnologia, causa impacto social e está modernizando um setor da saúde brasileira. 
- Possibilidade de evoluir e crescer junto com a empresa que se encontra em estágio inicial com altas taxas de crescimento. 
- Oportunidade de se conectar ao ecossistema de startups. 
- Local de trabalho flexível, podendo ser totalmente remoto. 
- Horário: 8 horas diárias, com horários flexíveis, mas preferencialmente distribuídas dentro do horário comercial.
- Remuneração: praticamos valores compatíveis com o mercado, dependendo do seu nível de senioridade. Buscamos desenvolvedores plenos. 

INSCRIÇÃO: [https://www.linkedin.com/jobs/view/1153171075/](https://www.linkedin.com/jobs/view/1153171075/)

**Comment by jmateusousa** [comment]
Enviado!!
