### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor PHP na Sys10

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#90]
## Descrição da vaga

Desenvolvedor PHP na Sys 10

## Local

Belo Horizonte

## Requisitos

**Obrigatórios:**
-PHP orientado a objetos
-Microsoft .NET, C#, MVC4+
-MySQL / MariaDB
-Microsoft SQL Server
-HTML / CSS básico
-Framework Javascript (Angular JS, React JS, Vue ou similar)

**Diferenciais:**
-Frameworks PHP (Symfony, Yii2, Laravel, Zend)
-Microsoft .NET Core, MVC Core
-Node JS
-NoSQL (MongoDB, Cassandra DB)
-HTML 5 / CSS 3 avançados
-Experiência com e-commerce
## Contratação

CLT 
Faixa salarial: R$2500 - R$3000

## Nossa empresa
A SYS10 é uma empresa com espírito jovem, formada por uma equipe multidisciplinar. Acreditamos que a diversidade e as diferentes perspectivas constroem soluções mais criativas e inovadoras. Criamos experiências digitais a partir de uma visão holística do projeto, sem perder o foco do usuário final. Unimos o raciocínio analítico, conhecimento tecnológico e empatia para criar produtos eficientes e que atendam as reais necessidades dos nossos clientes.
## Como se candidatar

https://app.vulpi.com.br/sys10/518

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Vaga preenchida?
