### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Backend

### ISSUE THREAD

**Issue by vinyguedess** [backend-br/vagas#907]
# Descrição da Vaga
Se você programa em iOS, sabe trabalhar em equipe, é movido por desafios e busca uma empresa onde tenha liberdade para abusar da criatividade, seu lugar é aqui! \o/

Levamos a mobilidade sustentável para cidades no brasil e na América Latina, e para isso precisamos de desenvolvedores que além de programar, topem disseminar a cultura da tembici, e engajar nosso time a ir cada vez mais longe! 😊

# Local
São Paulo, SP. Eureka Coworking - Avenida Paulista

# Principais responsabilidade
- Desenvolvimento de plataforma web;
- Elaborar junto com o time de arquitetura os novos sistemas;
- Desenvolver novos recursos e sustentar sistemas legados.

# Requisitos
- Sólidos conhecimentos em:
    - python e node.js;
    - aws;
    - visões de web como arquitetura, componentização e soluções para alta performance, com resiliência,
    - escalabilidade e segurança.
- Tenham conhecimento em:
    - Ruby on rails;
    - refactoring em códigos legados, deixando-os testáveis e mantendo seu funcionamento original;
    - conceitos de design de APIs;
    - integração e Delivery Contínuos, Jenkins ou ferramentas similares;
    - desenvolvimento de testes unitários;
- APIs Restful;
    - volumetria: ferramental e análise;
    - metodologias ágeis (Scrum e XP).
- Saibam alguma coisa sobre:
    - controle de versão distribuído (Git);
    - testes de contrato, testes de integração e testes end-to-end.
    - microserviços

# Contratação 
PJ ou CLT à combinar

# Como se candidatar
https://tembici.gupy.io/jobs/32921

# Labels
Python
Fullstack
Alocado
CLT
PJ

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by flaugabriel** [comment]
Tenho interesse
