### ISSUE TITLE
[Rio de Janeiro] [Remoto] Desenvolvedor Node.JS-15 na Upnid 

### ISSUE THREAD

**Issue by penelopevitoria** [backend-br/vagas#908]
**Esta é uma vaga de um cliente da GeekHunter, candidate-se para ter acesso as informações completas sobre a empresa.**

Nós construímos ferramentas que facilitam o processo de vendas online. Nosso principal produto é o checkout, uma página de pagamento que permite, em menos de 5 minutos, que nossos clientes consigam vender por meio da internet.

Nossa missão é simplificar a maneira como pequenos e médios empreendedores recebem pagamentos pela internet.

### **Sobre os desafios**

O nosso QG fica no Rio de Janeiro, mas você pode estar em qualquer lugar do mundo.Você será responsável por desenvolver a integração via API. Criar testes automatizados para garantir a confiabilidade dos novos recursos. Para isso, é bacana ter um conhecimento prévio em:

- Bancos de dados MySQL e MongoDB
- Conhecimento de API RestFull
- Experiência com testes automatizados
- Conhecimento em JavaScript ou Node.Js

### **Um dia típico de um DEV aqui inclui:**

- Acompanhar e estudar sobre o mercado de pagamentos e vendas online, trazendo novas ideias para o projeto; 

- Colaboração remota via Slack, Jira, Notion e videoconferência; 

- Alinhar com o time o andamento dos projetos e a preparação para lançamento de novas funcionalidades. 

### **O que buscamos em alguém**

1. Você não sabe tudo, mas aprende rápido. Você é faminto(a) pelo novo, está constantemente estudando e se qualificando. Se tem um desafio que não sabe como resolver, você estuda e coloca em prática o que aprendeu;

2. Você não faz trabalho meia boca. Se você tem um desafio, você vai até o fim. Sempre se preocupando com a qualidade, sem deixar que isso atrapalhe no cumprimento dos prazo;.

3. Você é curioso(a). Está sempre questionando e buscando maneiras de melhorar o seu trabalho;

4. Você é motivado(a) e independente. Você toma iniciativa para garantir que tenha todos os recursos necessários para desempenhar bem o seu trabalho e é proativo(a) em pedir ajuda quando necessário.

### **Local**

Rio de Janeiro - RJ

### **Benefícios**

- Liberdade.  Aqui você escolhe onde e quando trabalhar. Nosso time é remoto e você tem liberdade para escolher seus horários.

- Desenvolvimento de novas habilidades. Oferecemos uma ajuda mensal de R$ 100,00 para compra de livros, cursos e qualquer tipo de material educativo. (Também investimos em cursos mais caros - iremos analisar a viabilidade primeiro.)

- Alimentação e Transporte. Cuidamos de suas despesas de alimentação e transporte nos dias em que você optar por trabalhar do nosso escritório.

- Crescimento. Você estará fazendo parte de um time jovem e dinâmico, em um projeto em pleno crescimento. Participará ativamente em decisões estratégicas.

### **Requisitos Obrigatórios**

MongoDB, MySQL, Node.js

**### Requisitos Desejáveis**
JavaScript

### Contratação**

Regime PJ
Salário: R$ 5 000,00

Cadastre-se na GeekHunter e concorra à vaga: http://bit.ly/2Y7UVZP

**Comment by jonathangaldino** [comment]
Tenho um super interesse na vaga. Entretanto, não achei ela no GeekHunter (tenho perfil lá a uma semanas já). 

Como posso entrar em contato?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
