### ISSUE TITLE
[São Paulo - SP] Senior Backend Software Engineer na Casafy

### ISSUE THREAD

**Issue by penelopevitoria** [backend-br/vagas#909]
**This is a vacancy for a GeekHunter client, apply to have access to the complete information about the company**

We are a real-estate portal start-up located in Sao Paulo, Distrito AdTech start-up hub

We are technology lovers that are passionate about learning, development, real-estate market, science and processes.

We secured recently R$8 MM investment from Austrian and Estonian VC funds and have aggressive plans and interesting ideas how to disrupt LATAM real-estate market.

If you like challenges, thinking big and deliver kick-ass services, please take a look at our job position.

### What are we looking for?

We are searching for backend software engineers who are passionate about what they do, have a wide spread knowledge about technologies, system architecture and are proficient in at least two development languages. We have a system developed in Ruby and some microservices in Python, so proficiency in one of these languages is going to be benefit.

**### What do you need to apply to this job?**

- 5+ years of experience developing web systems;
- System architecture knowledge;
- Frontend experience is desirable;
- Experience working with TDD methodologies in DDD systems;
- Master at least two programming languages - Ruby or Python are preferred;
- Experience working with SQL and NoSQL databases;
- Need to know how to work in Linux environment;
- English is a requirement, at least in conversational level since we work with people from other countries also;
- Love for learning.

### **Where?**
Rio de Janeiro - RJ

### **Benefits**

- Health and dental plan from Bradesco;
- Meal compensation- R$35,00/day;
- Competitive salary and bonus from company results;
- Informal environment and minimal bureaucracy;
- Your ideas will have big impact on business results;
- Highend tools that match your talent.**

### **Technology and skills**

Programação Orientada a Objeto, Arquitetura de software

### **Differential**

Python, Elasticsearch, Linux, MySQL, Ruby, AWS, Flask, Google Cloud, Sinatra

### **Salary**

CLT - R$ 10400.0

**Sign up for GeekHunter and apply for a job:** http://bit.ly/2Y8s0Vt

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!
