### ISSUE TITLE
[Rio de Janeiro] Full-stack Developer temporário na TV Globo

### ISSUE THREAD

**Issue by dericeira** [backend-br/vagas#91]
## Descrição da vaga
Estamos com 3 vagas temporárias abertas para trabalhar em projetos específicos na TV Globo. A vaga é para 3 meses, porém há possibilidade de contratação. Trabalhamos em 3 frentes: Front-end (Javascript: Angular 4, Ionic, etc), Back-end (Javascript: NodeJS, infra AWS), Desktop (.NET C#).

## Local

Rio de Janeiro, RJ (Zona Oeste)
**Não há possibilidade de remoto**

## Benefícios

- VT
- VR

#### Diferenciais

- Vc escolhe: mac, windows ou linux;
- Ambiente de trabalho dinâmico;
- Trabalhar nos Estúdios Globo, o maior centro de produção de conteúdo da América Latina.

## Requisitos

**Obrigatórios:**
- Domínio em JavaScript, HTML e CSS
- Capacidade de escrever código eficiente, escalável e reutilizável
- Conhecimento em um ou mais frameworks JavaScript (React, Angular, etc.)
- Conhecimento em APIs Rest
- NodeJS
- Experiência em controle de versão, como Gitlab, Bitbucket
- Habilidades de gestão de tempo em projeto
- Habilidade para definir prazo de entrega

**Diferenciais:**
- Ionic
- C#
- .NET

## Contratação

Contrato temporário de 3 meses.

## Como se candidatar

Por favor envie um email para daniel.ericeira@tvglobo.com.br com seu CV anexado - enviar no assunto: Vaga Full-stack

**Comment by reginaldojunior** [comment]
Vaga preenchida?
