### ISSUE TITLE
[REMOTO] Back-end Developer/Magento @ McFadyen Digital/USA

### ISSUE THREAD

**Issue by VanessaAlbuquerque** [backend-br/vagas#9105]
## McFadyen Digital/BRA-US

A McFadyen Digital é uma agência global de comércio digital com 30 anos de história em inovação para mais de 250 das principais marcas do mundo. Oferecemos serviços de comércio digital, marketplace, marketing digital e experiência do usuário (UX), em nossos escritórios localizados na América do Norte, América do Sul e Índia. Em todas as práticas, ajudamos nossos clientes a atingir suas metas, garantindo que a tecnologia seja implementada estrategicamente e adotada de forma a atender aos objetivos do negócio.

## Descrição da vaga

- Escrever e manter os módulos do Magento2 EE/Cloud

- Escrever código limpo, modular e robusto para implementar os requisitos desejados com pouca ou nenhuma supervisão

- Criar componentes reutilizáveis, que podem ser configurados para diferentes projetos

- Revisar os requisitos de negócios trabalhando com outros membros da equipe

## Local

100% REMOTO

## Requisitos

**Obrigatórios:**
- 2 anos ou mais de experiência com Magento 2
- Fortes habilidades em PHP e Magento com ênfase em Programação Orientada a Objetos
- Forte experiência em banco de dados MYSQL
- Experiência com metodologias ágeis
- Forte compreensão da arquitetura do sistema Magento, design, temas, aprimoramentos de funcionalidade, configuração
- Inglês intermediário/avançado (Interações diárias em inglês)

**Diferenciais:**
- Já ter atuado em projetos internacionais
- Experiência com PWA

**Diferenciais McFadyen Digital:**
- Opção de pagamento em Dólar - USD para contrato PJ
- Aulas de inglês

## Contratação

PJ ou CLT

## Como se candidatar

- Por favor envie um email para valbuquerque@mcfadyen.com com seu CV anexado ou link to LinkedIn
- Ou pode aplicar nesse link: https://smrtr.io/8SgFM

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by cesarcardoso-mcfadyen** [comment]
Empresa TOP! Recomendo!

**Comment by iiagolima** [comment]
Recomendadíssimo!!!

**Comment by VanessaAlbuquerque** [comment]
Ainda temos uma vaga em aberto :)
Venham fazer parte desse time incrível!!!!
