### ISSUE TITLE
[Teresópolis/RJ e Nova Friburgo/RJ] Back-End Java Developer para Alterdata Software

### ISSUE THREAD

**Issue by recursoshumanosalterdata** [backend-br/vagas#912]
Back-end Java Developer

Quer ser Alterdatano e fazer parte de uma das maiores empresas de tecnologia 100% nacional?

A Alterdata é uma empresa que tem como objetivo melhorar a vida das pessoas, fornecendo soluções empresariais através de softwares e serviços.

Você integrará nosso time de especialistas, desenvolvendo produtos da área contábil, utilizando as mais diversas tecnologias disponíveis no mercado.

Temos somente uma regra! Nunca ficamos parados, pois inovação é o que nos inspira a cada dia.

Gosta de aprender e ser desafiado? Esse é o lugar!

Vagas para Matriz(Teresópolis) ou Polo de DSN de Software de Nova Friburgo/RJ (Não é home office).

Benefícios:

Plano de saúde
Plano odonto
Gym pass
VR ou VA de R$ 25,31/dia
Cargos e Salários
VT
Sala de jogos com Xbox e Sinuca, sala de relaxamento, refeitórios, intervalo para lanches e open café.
Requisitos:

Obrigatórios:
- Superior completo ou Cursando
- Experiência mínima de 2 anos como programador Java
- Java
- Projeto Orientado a Objeto
- SQL
- APIs REST e Integrações entre sistemas
- Gostar de desafios e de trabalhar em equipe

Desejáveis:

- PostgreSQL ou SQL Server
- ElasticSeach
- BDD, DDD e TDD
- MicroServiços
- Métodos Ágeis
- SaaS

Diferenciais:
- HTML, CSS e JavaScript
- AWS
- Google Cloud
- Linux

Contratação:
CLT (Full time)

Nossa empresa:

https://www.youtube.com/watch?v=fEmWlVka-H4&t=3s
https://www.alterdata.com.br

Como se candidatar?

Por favor envie um email para greyce.rh@alterdata.com.br com seu CV anexado - enviar no assunto: Vaga Back-End Java Developer

Tempo médio de feedback's?

Costumamos enviar feedbacks em até 07 dias após cada processo.

E-mail para contato em caso de não haver resposta: greyce.rh@alterdata.com.br

Labels
Alocado
CLT
Estágio
Júnior
Pleno
Sênior

**Comment by JosephSousa** [comment]
Essa vaga ainda se encontra aberta?
