### ISSUE TITLE
[Remoto] Back-end Developer PHP (Laravel) @labfour

### ISSUE THREAD

**Issue by marocama** [backend-br/vagas#9128]
## Nossa empresa

A LABFOUR busca através de uma política moderna e dinâmica desenvolver uma solução completa para laboratórios, atuando com o foco principal na comercialização de mobiliários técnicos, oferecendo aos parceiros desde a elaboração de projetos customizados, visitas técnicas, estudos do local e execução da obra, além disso, presta serviços de manutenção, reforma e readequação para os mobiliários, tal como, serviços de calibração e certificação para os equipamentos, os produtos oferecidos possuem design moderno, inovadores e totalmente customizados, os equipamentos com tecnologia de ponta e serviços especializados com equipes qualificadas e certificadas atendendo as mais rigorosas normas de segurança. O maior objetivo é atender as necessidades para os mais diversos segmentos.

## Descrição da vaga

- Desenvolvimento e manutenção de aplicações web (Sistema ERP)

## Local

- Remoto ou escritório em Bom Jesus dos Perdões / SP

## Requisitos

- Experiência com PHP (Laravel) e MySQL
- Experiência com ferramentas de versionamento de código (GIT)

## Como se candidatar

Por favor envie um email para sistemaerp@labfour.com.br com seu CV anexado - enviar no assunto: Vaga PHP (Laravel)

**Comment by dilneiss** [comment]
Boa noite, já mandei meu currículo por e-mail, mas não tenho certeza se receberam, pois não deram nenhuma confirmação.
Tenho toda experiência que precisa tranquilamente

**Comment by MarlonAelson** [comment]
A vaga já foi preenchida?
