### ISSUE TITLE
Caxias do Sul/RS Desenvolvedor C# @HunterCo

### ISSUE THREAD

**Issue by vivihunterco** [backend-br/vagas#9146]
## Nossa empresa

HunterCo
Atividades: 
Desenvolver soluções tecnológicas, usando ferramentas de suporte ao cliente Analista das tecnologias, verificando erros e inconsistências nas soluções externas.
Desenvolver sistema de uso de padrões de segurança pela empresa.
Definir padrões de usabilidade e interface.
Desenvolver sistema de uso de padrões de segurança pela empresa.
Realizar a implantação e homologação dos sistemas nos ambientes dos clientes, através de acesso remoto e ferramentas de desenvolvimento específicas.
Apoiar nas estimativas de solicitações de manutenção ou de projetos.

## Local

Modelo Presencial - Caxias do Sul/RS

## Requisitos

**Obrigatórios:**
V

Aplicações Web: Net Core 3.1 ou superior, Asp.Net Core, HTML, CSS, Javascript
Bancos de Dados: SQL Server
Repositório de Código: Git
Padrão de modelagem de software: DDD
Arquitetura em Microserviços

## Benefícios

Salário a combinar
Plano de Saúde Unimed ou Fátima (estendido aos seus dependentes);
Plano Odontológico Fátima (estendido aos seus dependentes);
Seguro de Vida em grupo;
Vale refeição ou alimentação;
Transporte Vale;
Verba para treinamentos | cursos | oficina;
Horário de trabalho tabulação;
Presente a sua escolha no mês do seu aniversário;
Equipamentos de trabalho fornecidos pela empresa;
Plataformas de estudos gratuitos.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vivianne.amora.4rh@gmail.com seu CV anexado - enviar no assunto: Vaga Desenvolvedor C# 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

Nível - Pleno

**Comment by victorjoao97** [comment]
Essa vaga tem label Remoto, mas na descrição é Presencial, qual seria?

**Comment by vivihunterco** [comment]
Vaga é presencial
