### ISSUE TITLE
[REMOTO] Desenvolvedor(a) PHP Pleno/Sênior | CRP Tecnologia

### ISSUE THREAD

**Issue by JulianaBNunes** [backend-br/vagas#9147]
**DESCRIÇÃO DA VAGA**

Olá Pessoa Desenvolvedora PHP!

Está em busca de novos desafios? Então você está no lugar certo!

Temos oportunidades para você, **Pessoa Desenvolvedora PHP PL/SR,** que está disposta a integrar o time de uma Fábrica de Software, com diversos clientes espalhados pelo Brasil e pelo mundo. Empresa 100% Brasileira, líder no Centro/Norte do país, com projetos de diversos tamanhos e complexidades.

Sua missão é criar de forma dinâmica e sustentável, recursos inovadores aos seus clientes. Para isso, conta com equipes especializadas em diferentes tecnologias e linguagens.

Venha fazer parte desse time!

**Aqui sua missão será:**

Irá exercer funções de desenvolvimento e manutenção de softwares;
A atuação pode contemplar todo o ciclo de produção de um software:
requisitos, arquitetura, análise, projeto, desenvolvimento, integração, testes,
implantação, manutenção e treinamento de usuários, além de suporte a
aplicações já desenvolvidas. 

**Para isso você precisa ter:**

Superior Completo ou Cursando Ciência da Computação, Sistemas de
Informação ou cursos similares. 
PHP: Back End
Framework: Laravel
Ter trabalhado com pelo menos 1 destes: Oracle, SQL Server, PostgreSQL,
MySQL e / ou bancos não relacionais; 
Ter trabalhado com pelo menos 1 destes: Google Cloud; Amazon AWS;
Microsoft Azure.  

**Você ganha pontos de tiver:**

✓ Certificações associadas a Desenvolvimento de Software;

✓ Azure DevOps; e / outras ferramentas ALM;

✓ Integração contínua (CI); Entrega contínua (CD);

✓ Test Driven Development (TDD);

✓ Behaviour Driven Development (BDD);

✓ Domain Driven Design (DDD);

✓ Padrões de arquitetura;

✓ Estimativa e medição de sistemas utilizando Análise de Pontos de Função;

✓ Hospedagem; Servidores Linux 

**Benefícios: Plano de Saude,Plano Odontológico,Vale Alimentação,Seguro de Vida (somente se optar pelo contrato CLT)

Carga horária semanal: 40 Horas

Regime de Contratação: CLT ou PJ**

**Comment by ramospedro21** [comment]
Como me candidato?

**Comment by JulianaBNunes** [comment]
Olá Pedro, você pode se candidatar através do link:
https://domdh.gupy.io/jobs/1728224

Em ter., 3 de mai. de 2022 09:00, Pedro Ramos ***@***.***>
escreveu:
