### ISSUE TITLE
[São Paulo] Back-End Developer na B2W Digital

### ISSUE THREAD

**Issue by vcalixto** [backend-br/vagas#917]
DESCRIÇÃO DA VAGA
A SkyHub começou como startup, e hoje faz parte do grupo B2W como porta de entrada para os maiores marketplaces da América Latina e mais de 1 milhão de produtos conectados. 

Quer desenvolver diversas soluções que fazem a diferença para milhares de e-commerces e consumidores todos os dias? Então esta oportunidade é para você. 

O que é a SkyHub? Muito mais que uma plataforma de integração, que além de possibilitar ao vendedor conectar sua loja virtual nos maiores marketplaces (Lojas Americanas, Submarino, Shoptime...), fornece facilidades como ferramentas de frete, nota fiscal eletrônica, análises financeiras e muito mais. 

Como é a SkyHub? Um ambiente estimulante, que incentiva a melhoria contínua com um time apaixonado pelo que faz. 

A difusão de conhecimento é essencial para que todos da equipe cresçam, por isso realizamos talks e cursos para obter conhecimentos sobre diversos campos: Elixir, ReactJS, Lambda AWS, ElasticSearch e permitir a escalabilidade da SkyHub com possibilidades para alcançar novos patamares e desafios. 

A contratação é em modelo CLT.

REQUISITOS E QUALIFICAÇÕES
Experiência Necessária 

- Conhecimentos de programação Orientada à Objetos 
- Metodologias de programação como: TDD ou BDD 
- Consumo de APIs Web 
- Conhecimento de algoritmos e estrutura de dados 

Diferenciais 

- Conhecimento de programação funcional 
- Conhecimento de Elixir com Phoenix Framework ou Ruby on Rails 
- Amazon Web Services 
- Conhecimento de arquitetura de Micro Serviços 
- Noção de arquitetura orientada a filas/eventos 
- Continuous Integration e Continuous Delivery 
- Trabalhar com metodologias ágeis como SCRUM e KANBAN 

QUEM SOMOS
Nosso propósito é conectar pessoas, negócios, produtos e serviços em uma mesma plataforma digital. Por isso, a B2W Digital quer, cada vez mais, estar sempre próxima dos clientes, oferecendo a melhor experiência de compra e desenvolvendo os melhores talentos. 

Líder na América Latina, a B2W Digital tem um modelo de negócio único, multicanal, multimarca e multinegócio. A Companhia atua nas seguintes frentes: e-commerce nas marcas Americanas.com, Submarino, Shoptime e Sou Barato; plataformas de serviços de crédito ao consumidor, com o Submarino Finance e o Digital Finance; plataforma de tecnologia; plataforma de logística, distribuição e atendimento ao cliente; e Marketplace.

cadastre-se:
https://b2w.gupy.io/jobs/17418

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by vcalixto** [comment]
PL/SR

**Comment by allansduarte** [comment]
Como está o status dessa oportunidade?

**Comment by vcalixto** [comment]
Bom dia
Aberta.

Abs
________________________________
De: Allan Soares Duarte <notifications@github.com>
Enviado: sexta-feira, 17 de janeiro de 2020 16:03:20
Para: backend-br/vagas <vagas@noreply.github.com>
Cc: Valdir Calixto <instvaldir@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [backend-br/vagas] [São Paulo] Back-End Developer na B2W Digital (#917)


Como está o status dessa oportunidade?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
