### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor C# na Take

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#92]
## Descrição da vaga

Buscamos alguém que irá trabalhar com programação de Chatbots e criação e manutenção de plataformas da empresa, utilizadas na construção de Chatbots. Estamos trabalhando com uma tecnologia nova e disruptiva, por isso, essa pessoa deverá ser capaz de propor e desenvolver soluções completas em diversas linguagens de programação (não se apegue a nenhuma :)). No dia-a-dia atuará com equipes de suporte, negócios e produtos a fim de auxiliar na resolução de problemas, no desenvolvimento e aprimoramento de produtos.

Uma pessoa: curiosa para sempre buscar descobrir o novo mundo à sua volta; proativa que sabe perceber oportunidades de contribuição para o time; dinâmica, aqui nossos dias são de muita agitação; com facilidade de lidar com mudança de contexto porque atuamos nas principais plataformas da empresa; que busque inovações. E que goste de fazer as coisas acontecerem!

## Local

Belo Horizonte

## Requisitos

**Obrigatórios:**
- Javascript (avançado)

- HTML5

- CSS3

**Desejáveis:**
- Backbone.js

- SASS

- LESS

- Bower

- Grunt

- Node.js (diferencial)

## Contratação

CLT
## Nossa empresa
Ajudamos as empresas a atender, engajar e vender nos aplicativos de mensagem, usando soluções de comunicação automática (chatbots) com suporte de atendentes.

## Como se candidatar
https://app.vulpi.com.br/take/524

## Labels

- Alocado
- CLT
- Pleno
- Junior
- Senior

**Comment by reginaldojunior** [comment]
Vaga preenchida?
