### ISSUE TITLE
[Remote] Back-end Developer @ 4intelligence

### ISSUE THREAD

**Issue by rm-4i** [backend-br/vagas#9207]
## Nossa empresa
Somos uma startup de Inteligência Artificial (IA). Nosso objetivo é possibilitar que organizações utilizem IA em suas tomadas de decisão a fim de otimizarem resultados. Acreditamos que, ao decodificar IA, potencializamos o mundo de negócios. Construímos, por exemplo, respostas para questões sobre: previsão de vendas, retorno de investimentos, formação de preços e otimização geográfica de operações.

## Sobre o time de Engineering & Software Development

Para nós, Data Science é um esporte de equipe - acreditamos e vivemos uma cultura horizontal, aberta, transparente e "anti-rockstar", e valorizamos a diversidade de experiências, perspectivas e background de cada um. A pessoa ideal para entrar na equipe tem que acreditar neste lema, estar preparada e aberta para encarar os mais variados tipos de desafios, pensar sempre em escalabilidade e agilidade, e ser colaborativa, criativa e investigativa - aqui quem vence são as grandes ideias.

## Descrição da vaga

A pessoa ideal para se juntar ao time deve ser colaborativa, investigativa e analítica, ter excelência técnica e querer difundir melhores práticas de desenvolvimento, e estar preparada para encarar e proativamente propor soluções para os mais variados tipos de desafios.

As suas principais responsabilidades serão: 

- Desenvolver código limpo, testável, escalável e de fácil manutenção, e participar de code review, garantindo qualidade e consistência do código; 
- Contribuir nas discussões técnicas sobre os desafios encontrados, propondo melhorias nos sistemas existentes e garantindo qualidade nas entregas;
- Participar ativamente no processo de arquitetura e planejamento de soluções de software, visando escalabilidade e melhores práticas e padrões de desenvolvimento;
- Ajudar no monitoramento e otimização do desempenho dos nossos serviços; 
- Fazer entregas constantes e contribuir para repositórios e documentos do time; 
- Trabalhar com um time multidisciplinar (em squads), seguindo frameworks como Scrum, e fomentando a cultura ágil e DevOps;
- Compartilhar a sua experiência e conhecimentos para desenvolver os membros do time;
- Colaborar com outras pessoas de tecnologia, produto e ciências de dados para identificar e resolver problemas desafiadores. 

## Local

Remoto ou nos escritórios em São Paulo (WeWork Inovabra) e Santa Rita do Sapucaí

## Requisitos

**Obrigatórios:**
- Formação em cursos de Tecnologia é um diferencial (ex: Engenharia da Computação, Ciência da Computação, Sistemas de Informação).
- Experiência no desenvolvimento de aplicações web, preferencialmente utilizando [Node.js](http://node.js/), Go e com proficiência em Python;
- Entendimento em desenvolvimento de sistemas com arquitetura de serviços REST, e microserviços;
- Conhecimento de Docker e Kubernetes, e base de dados como NoSQL;
- Histórico sólido trabalhando com serviços Cloud GCP e Azure (certificações é um diferencial);
- Experiência com serviços de mensagerias como Kafka, Pub/Sub e Event Hub;
- Proficiência de API Gateway, e experiência com versionamento de código e com Github Actions;
- Vontade de trabalhar com times multidisciplinares, usando Scrum e ferramentas como Jira, e em ambientes complexos e ritmo acelerado; 

**Desejáveis:**
- Histórico sólido trabalhando com serviços Cloud GCP e Azure;
- conhecimentos em C#

**Diferenciais:**
- projetos opensource

## Benefícios

- Remuneração variável anual (bônus) competitiva;
- Vale-alimentação e vale-refeição; 
- Plano de Saúde (sem coparticipação); 
- Telemedicina e desconto em medicamentos;
- Seguro de Vida;

## Contratação

- CLT

## Como se candidatar

Por favor, cadastre sua candidatura no site abaixo
https://4intelligence.gupy.io/job/eyJqb2JJZCI6MTczNTM5Niwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

O processo pode demorar 45 dias ou mais, desde a aplicação até à oferta, e o nosso time irá responder todas as candidaturas, mas pode ser que demore um pouco. Estas são as etapas: 
 - Aplicação 
 - Entrevista inicial - para conhecermos você um pouco mais. 
 - Avaliação técnica 
 - Entrevista com liderança 
 - Background check 
 - Oferta 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by rm-4i** [comment]
This position is still open.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
