### ISSUE TITLE
[Rio de Janeiro] Back-end Python/Django Jr/PL na Brbid

### ISSUE THREAD

**Issue by guiljardim** [backend-br/vagas#921]
**Brbid – Rio de Janeiro, RJ**

Estamos procurando alguém que esteja motivado a criar soluções junto com nosso time. Esta pessoa entrará para squad do Brpatio, um produto que gerencia pátios de veículos apreendidos em conjunto com órgãos. Não é necessário ser um expert. Procuramos alguém que queira evoluir junto com a gente, aprender e somar forças nesse momento de expansão. 

**Requisitos:**
Gostar de desenvolver em Python
Saber desenvolver em Django
Noção com desenvolvimento em ambiente Linux
Versionamento de código com Git

**Desejável:**
Celery
Metodologias ágeis (Scrum ou Kanban)
Bootstrap
AWS
PEP8
Soulth
Bons conhecimentos de padrões de projeto, refatoração e testes unitários.

**Benefícios:**
Contratação CLT
Vale refeição ou Alimentação (R$22/dia)
Vale transporte ou combustível
Plano de saúde Amil
Horários flexíveis

**Como se Candidatar:**
Currículo + Pretensão para o email guilherme.jardim@brbid.com
Assunto: Vaga Back-end Python/Django

**Local:**
Brbid – Americas Avenue Business Square
Recreio dos Bandeirantes, próximo ao Terminal Salvador Allende.

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!
