### ISSUE TITLE
[São Paulo-SP] PHP Developer na Finnet S/A Tecnologia

### ISSUE THREAD

**Issue by carolzperez** [backend-br/vagas#922]
**Sobre nós**

Com mais de 14 anos de experiência, a Finnet está interligada a mais de 40 instituições financeiras e 782 mil empresas na cadeia de valor. Por meio de nossos produtos e serviços, anualmente são trafegados mais de 5,6 milhões de arquivos e processados mais de 74,8 milhões de transações em produtos de nossos clientes.

Nosso objetivo é tornar os processos menos burocráticos e muito mais ágeis, e acreditamos que unindo nossa tecnologia com os objetivos de nossos clientes podemos criar um mundo mais acessível, facilitado e sustentável para todos.

Independente do porte e segmento de com quem estamos conectados, nasce uma solução Finnet, e é com essa responsabilidade que inovamos para simplificar todo o processo de gestão de forma inteligente e revolucionária!

**Sua atuação no dia a dia**

- Desenvolvimento backend de serviços e integrações, de soluções de alta qualidade, focadas na experiência do usuário;

- Avaliar soluções, impactos, riscos e estimar esforços;

- Acompanhar o produto em produção e resolver problemas (suporte, correções, dúvidas, configurações e melhoria contínua dos produtos existentes);

- Auxiliar o analista de qualidade no desenvolvimento da estratégia de Q&A;

- Trabalhar com o time do produto para construir soluções que traduzam a estratégia da empresa em seu produto e funcionalidade;

- Responsável por codar os nossos novos microsserviços

**Para isso, precisamos de você:**

Superior completo na área de Tecnologia;
Vivência em projetos Web, backend;
Experiência em banco de dados relacional (MySQL)
Conhecimentos em cloud (AWS, Azure ou Google Cloud)
Profundo conhecimento PHP e em outra linguagem de programação
orientada a objeto (Java, Phyton...)
Conhecimentos em desenvolvimento seguro OWASP

**Seria bacana se você tivesse:**

Conhecimento/experiência em frameworks como Angular, ReactJS,
Vuejs, Node.js, etc
Conhecimentos em bancos NoSQL (ElasticSearch, Redis, Mongo...)
Conhecimentos em DDD/TDD
Experiência com desenvolvimento de produtos digitais (e-commerce
ou mercado financeiro);

**Onde estamos**

Jardim Paulista - São Paulo (próximo ao metrô Trianon-Masp).

**O que oferecemos**

Regime de contratação CLT;
Horário flexível;
Bermuda e tênis são bem-vindos;
Viagem para o funcionário destaque do ano;
Premiação para funcionários por tempo de casa (a cada cinco anos);
Vale refeição/ Vale alimentação/ Plano de saúde/ Seguro de vida/ Auxílio Creche/ PPR semestral/ Frutas no escritório;
Convênios com universidades, escolas de idioma, farmácias, consultórios odontológicos, estacionamentos e Sesc

**Como se candidatar**

Por favor envie um email para carolina.zacharias@finnet.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by garaujodev** [comment]
É apenas alocado ou há a possibilidade de flexibilização?
