### ISSUE TITLE
[Remoto] Back-end Developer TAGNA TECNOLOGIA

### ISSUE THREAD

**Issue by 897856** [backend-br/vagas#9223]
## Nossa empresa

Somos uma empresa de tecnologia e automação industrial.

Trabalhamos para resolver os desafios das indústrias e impulsionar a inovação no negócio de nossos clientes.

Procuramos alguém que:

Gosta de trabalhar em equipe; 💛 

- Goste de desafios e seja proativo para resolvê-los.;
- Saiba se comunicar e lidar bem com pessoas;
- Tenha capacidade de tomada de decisão em situações complexas;
- Tenha atenção concentrada e consiga trabalhar sob pressão;
- Seja um profissional de alta performance com foco, organização e planejamento de atividades;
- Seja capaz de liderar e ser liderado;
- E claro, se identifique com a nossa cultura!

## Descrição da vaga

Estamos à procura de um (a) Analista de Desenvolvimento de Software Pleno  com foco em Back-End. para completar o nosso time Xperts e que seja capaz de:

- Propor soluções para problemas relacionados ao produto/projeto em desenvolvimento atuando junto à uma equipe multidisciplinar, podendo atuar em diversas áreas do desenvolvimento de software.
- Desenvolver e realizar manutenção de aplicações, com práticas de código limpo, envolvendo integração com banco de dados, desenvolvimento de soluções que atendam às necessidades do projeto, implementação de testes automatizados, criação de APIs para a disponibilização de dados entre os serviços, utilização de contêineres para rodar as aplicações, entre outras.
- Realizar deploy das aplicações para o ambiente de produção visando garantir seu correto funcionamento.

## Local
 Remoto ou Escritório, Belo Horizonte, região da Savassi.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência 
- Superior em andamento em Engenharia de Software, Ciência da Computação, Sistemas de Informação ou Similares;
- Inglês Avançado;
- Conhecimento em Programação Orientada a Objetos;
- Linguagens Java e Python;
- Conhecimento em Banco de Dados Relacionais e Temporais;
- Conhecimento em Docker e Git;
- Experiência com provedores de Cloud (Google Cloud);
- Experiência com testes automatizados;
- Disponibilidade para viagens esporádicas.

**Diferenciais:**

- Conhecimento em JavaScript, TypeScript, ReactJS, CSS3, HTML 5;
- Experiência com Frameworks/bibliotecas Springboot, React-Redux, Redux-Saga;
- Metodologias ágeis (SCRUM);
- Experiência com micros serviços;
- Experiência com TDD;
- Experiência com desenvolvimento de provas de conceito e MVP’s;

## Benefícios

Vale-transporte, vale mobilidade ou auxílio home office;
Vale-refeição e alimentação pelo  cartão Flash;
Seguro de vida;
Auxílio Creche;
Plano de Saúde e Odontológico Sul América, sem coparticipação para cuidados da saúde física e mental;
Convênio com a TotalPass, para que os nossos colaboradores cuidem da saúde física.

Carreira:

Participação em cursos, eventos e palestras para você se desenvolver cada vez mais;
Oportunidade de crescimento na empresa com plano de carreira estruturado.
 
Bem-estar:
Flexibilidade no horário de trabalho e banco de horas;
Parcerias com instituições de saúde, educação, conveniência, cultura e entretenimento;
Day off no aniversário (redução de 50% da carga horária);
Liberdade para trabalhar em home office (inclusive após a pandemia);

## Contratação

CLT

## Como se candidatar

Se inscreve na vaga pelo link: https://tagnatecnologia.gupy.io/jobs/1729628

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@tagna.com.br

#### Regime
- CLT

#### Nível
- Pleno

**Comment by ramonpaolo** [comment]
Recomendo mudas as labels, pois o foco parece ser para dev NodeJs
