### ISSUE TITLE
[Remoto] Javascript Fullstack Developer @ Quave

### ISSUE THREAD

**Issue by edimarlnx** [backend-br/vagas#9227]
## Nossa empresa
quave: PASSIONATE PEOPLE TRANSFORMING CODE INTO PRODUCTS

A Quave surgiu com o objetivo de juntar desenvolvedores que gostam de transformar código em produtos que façam a diferença na vida das pessoas. Por isso, além de procurar reunir desenvolvedores, tentamos ajudar pessoas a se desenvolverem na área de tecnologia, através de conteúdos online e dicas com o que praticamos no nosso dia a dia. Entre em nosso site [quave.dev](https://quave.dev/)  e nosso [GitHub](https://github.com/quavedev/) para acompanhar nossos conteúdos.

## Descrição da vaga
Para a maioria de nossas vagas é esperado conhecimento avançado da linguagem Javascript, tanto para backend quanto para frontend (NodeJS e Navegadores). Em nossa equipe temos vários especialistas em Meteor, que faz parte da stack de vários clientes que atendemos, desta forma conhecer Meteor é um grande diferencial. Para banco de dados é fundamental conhecimento em NoSQL, principalmente MongoDB que é utilizado por quase todos os projetos envolvidos. Para frontend, adotamos React como biblioteca padrão, sendo muito importante conhecer sobre hooks e pure component, mas também importante conhecer os padrões mais antigos para manutenção em códigos existentes. Ainda sobre frontend, é importante que o desenvolvedor tenha conhecimentos sobre responsividade, conceitos de flexbox, css e bibliotecas que facilitem o desenvolvimento de interfaces de usuário amigável.

Todas as nossas vagas são 100% remotas e a maioria é remunerada em dólar!

Dedicação full-time é esperada.

## Local
Remoto

## Requisitos
**Obrigatórios:**

* Ser Brasileiro
* Ser fiscalmente ativo no Brasil
* Saber Javascript (pelo menos o conteúdo dos 6 livros [YDKJS](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/README.md))
* Saber [MongoDB](https://www.mongodb.com/) (já ter utilizado)

**Diferenciais:**

* Saber [Meteor](https://www.meteor.com/) (já ter utilizado)
* Conhecer React
* Falar inglês (vai se comunicar com equipe internacional)
* Ter participado de competições de programação
* Saber algoritmos muito bem (inclusive Grafos e assuntos mais complexos)

## Benefícios
* Receber em Dólar
* Liberdade para trabalhar de onde quiser
* Flexibilidade de horário

## Contratação
PJ

## Como se candidatar
Por favor envie um email para hireme@quave.com.br com seu CV anexado e projetos no GitHub com o assunto: Vaga de Fullstack Developer

Você receberá então os detalhes do processo seletivo e as instruções para os próximos passos, incluindo um desafio de programação que nos ajudará a avaliar sua aptidão para a vaga.

## Remuneração média
Entre 2k - 4,5k USD (dependendo da avaliação)

#### Categoria
* Front-End
* Back-End

#### Alocação
* Remoto

#### Regime
* PJ

#### Nível
* Pleno
* Sênior

**Comment by iugmali** [comment]
Olá! Eu tenho CNPJ, posso emitir NFe e estou disposto a integrar esse time. 

+5521996796425
https://www.linkedin.com/in/iugmali
https://www.iugmali.com/download/curriculum-vitae

**Comment by degod** [comment]
I am open for any English speaking remote role. Preferably in a PHP, Laravel, VueJS, AngularJS, Ionic (Hybrid mobile apps) roles. Kindly email me on godwinseeyou@gmail.com or chat me on WhatsApp on +2347061933309
