### ISSUE TITLE
[São Paulo e Rio de Janeiro] #Vaga Fullstack Pleno na Atlas Inovações

### ISSUE THREAD

**Issue by marcosafmartins92** [backend-br/vagas#923]
Vaga Fullstack Pleno

Requisitos:
- Inglês técnico
- Conhecimento em C# (.Net, .Net Core) e Javascript (React)
- Entity Framework
- Criação e consumo API Rest (Web API)
- Gostar de desafios

Diferenciais:
- Testes automatizados
- Docker
- Aws
- SOLID
- Padrão de projetos

Benefícios: Vale refeição, plano de saúde e dental
Salário à combinar

e-mail de contato: rh@atlasinovacoes.com.br

**Comment by rmelobarbosa** [comment]
Boa oportunidade =)

**Comment by marcosafmartins92** [comment]
Já preenchido
