### ISSUE TITLE
[100% Remoto] Back-End Rails Developer no Catarse (Pleno ou Sênior)

### ISSUE THREAD

**Issue by thiagocatarse** [backend-br/vagas#925]
## Objetivo da vaga

Trabalhar no time de Produto do Catarse, formado hoje por 3 pessoas: 
* 1 Designer/Líder de Produto
* 1 Desenvolvedor Back-end Sênior
* 1 Desenvolvedor Full-stack Junior.

Entre suas responsabilidades estará a resolução de bugs e tasks operacionais rotineiras; implementação do back-end de features desenvolvidas para melhorar a experiência de nossos usuários; migração do código do Catarse para novas linguagens/tecnologias adotadas.
[Saiba mais sobre o Catarse aqui](https://crowdfunding.catarse.me/quem-somos)

## Atribuições e conhecimentos desejáveis

* Experiência com APIs REST
* Experiência com microserviços.
* Conhecimento de Javascript, Rails e PostgreSQL.
* Familiaridade com Git.
* Manter a qualidade e garantir a capacidade de resposta das nossas aplicações.
* Colaborar com o resto da equipe de desenvolvedores para projetar, fazer manutenção e lançar novas features.
* Colaborar com a equipe de Suporte (atendimento ao cliente) para entender os problemas/bugs enfrentados pelos nossos usuários e resolvê-los com presteza.
* Manter a integridade e a organização do código.
* Participar da construção de soluções através da análise do problema, de retirar dúvidas técnicas sobre a viabilidade e dificuldade de implementar tal solução.
* Saber se certificar que o problema que está sendo resolvido em qualquer situação está claro, trazer as dúvidas pertinentes, planejar adequadamente a execução antes de escrever código, e garantir a entrega da solução com precisão.
* Corrigir bugs.
* Trabalhar com o restante do time de produto para converter projetos em aplicações.
* Inglês intermediário (leitura e escrita)

## Quem é você?

* Apaixonada(o) pelo o que o Catarse faz: ser parte do processo de construção de uma cultura de colaboração no Brasil através do financiamento coletivo de projetos criativos;
* É curioso(a) e gosta de ter problemas complexos no seu colo para serem resolvidos;
* Estar confortável para trabalhar remoto. Não temos escritório físico e todo mundo da equipe trabalha de casa.
*  É organizada(o) e rígido(a) com a qualidade (e beleza!) do código escrito;
* Tem apreço por uma boa documentação do código;
* Tem paciência para, na medida do possível, traduzir problemas de programação para uma linguagem mais palatável para outros membros do time do Catarse (que não falam a língua dos devs!);
* Interessado(a) em aprender novas linguagens e se adaptar às mudanças (às vezes rápidas) no código do Catarse;

## Local de Trabalho:

Não temos escritório físico, logo você pode trabalhar de onde você quiser ;)

## Salário:

R$6.500,00 a R$8.000,00 (full-time). Trabalho remoto. Pagamento via PJ.
Início a partir de Maio/Junho 2019 

## Como se candidatar

[Acesse este link e se cadastre por lá!](https://catar.se/backend)

## Labels
* Remoto
* Pleno
* Sênior
* PJ
* Full time
* Rails
* Javascript
* PostgreSQL
* APIs REST

**Comment by maickelc** [comment]
Close please!
We are currently not accepting applications for this job.
You can apply for other jobs via our Career Portal
