### ISSUE TITLE
[Vitória] Dev - SQL @ [Code n'App]

### ISSUE THREAD

**Issue by carolinesgarcia** [backend-br/vagas#9254]
> Vaga híbrida

## Code n'App

Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada.
Além disso, estamos em um ritmo de crescimento a-ce-le-ra-do, então se você curte desafios, busca evoluir e ama tecnologia, temos aqui um time para chamar de seu! Pois adoramos reconhecer e potencializar o desenvolvimento dos nossos Codenappers.

#VemPraCode ♥

## Responsabilidades e Atribuições

A pessoa desenvolvedora SQL será responsável pela criação e evolução de APIs que utilizam procedures e functions em bancos de dados para processar requisições web, tendo a oportunidade de atuar internamente ou em clientes parceiros, contribuindo em todo o ciclo de vida, desde a concepção até a implantação, atuando com metodologias ágeis para entregar uma solução eficiente. Esperamos que essa pessoa possa:
Contribuir para o sucesso do projeto e o crescimento da equipe
Conhecer as boas práticas de programação das tecnologias utilizadas
Escrever código limpo, de qualidade e de fácil manutenção

## REQUISITOS E QUALIFICAÇÕES

Experiência no desenvolvimento de APIs com processamento em procedures, functions e views;
Sólidos conhecimentos em:
Linguagem SQL para criar quieres, functions e procedures;
Modelagem de tabelas e seus relacionamentos.

**Será um diferencial se você entender sobre:**
Otimização de queries
Utilização do Azure DevOps para a gestão de backlog e tarefas;
Utilização do Git e GitFlow;
Experiência em metodologias ágeis como Scrum.

## Benefícios
Horário flexível e possibilidade de home office ou modelo híbrido;
No dress-code;
Gympass;
Assistência médica (você + parceiro(a) + filhos até 18 anos é por nossa conta);
Somos flexíveis: Disponibilizamos um cartão de crédito bandeira Visa para livre utilização do saldo nas categorias de alimentação, restaurante, mobilidade, cultura, saúde e home office;
Vale transporte;
Celebração de datas importantes (Seu aniversário, aniversário Code n’ App, etc.)

**Temos Também:**
Programa Indica Code - Indicando um amigo você ganhará um bônus pelo talento em nosso time;
Cesta recém-nascido;
Cafézinho e biscoitinhos à vontade, além de puffs para cochilar nos intervalos;
Empréstimo consignado;
Assessoria e educação financeira;
Oportunidade de fazer parte de um time de feras e com muitas experiências para compartilhar.
## Contratação

CLT/ PJ

## Como se candidatar

Acesse o link abaixo e se inscreva: 
https://codenapp.gupy.io/jobs/1724715

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: queroser@codenapp.com

#### Alocação
- Alocado
- Híbrido

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by carolinesgarcia** [comment]
Vaga em aberto!!

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
