### ISSUE TITLE
[Remoto] Backend C# Developer na Ploomes Sistemas Empresariais

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#9258]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-backend-c-125531349?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Ploomes Sistemas Empresariais</strong> busca pessoa <strong>Backend C# Developer </strong>para compor seu time!</p>
<p>Insaciedade é um dos nossos valores e aqui você poderá aprender e se desenvolver todos os dias com um time de profissionais extremamente dedicados!</p>
<p>Se você se identifica com os pontos abaixo essa vaga é pra você. Não perca tempo e venha ser nosso novo Ploomer!</p>
<p>Buscamos uma pessoa Backend C# Developer para trabalhar com integrações do Ploomes a outros sistemas. O roadmap de integrações é definido junto à equipe de marketing, visando sempre desenvolver aquelas que trarão maiores resultados em geração de receita para a empresa.</p>
<p>A pessoa terá de pensar e executar as melhores práticas em para o desenvolvimento das integrações, com o objetivo de levar a maior eficácia e facilidade de uso para o usuário final.</p>
<p>Terá que lidar com diferentes tipos de sistemas, consumir e construir APIs e desenvolver integrações com softwares no geral, como de ERP, BI, TMS, WMS, entre outros.</p>

## Ploomes Sistemas Empresariais: 
 <p style="text-align:justify;">A Ploomes está reinventando os departamentos de vendas de empresas B2B em todo o Brasil, levando eficiência e inteligência através de um sistema de gerenciamento de relacionamento com clientes (CRM) altamente robusto, aliado a serviços consultivos baseados em processos consolidados.&nbsp;</p>
<p style="text-align:justify;">No último ano mais que dobramos de tamanho, e seguimos com planos ambiciosos de crescimento acelerado. Para isso, precisamos contar com pessoas altamente capacitadas e com muita vontade de crescer.&nbsp;</p><a href='https://coodesh.com/empresas/ploomes-sistemas-empresariais'>Veja mais no site</a>

 ## Habilidades: 
 - C# 
- REST APIs 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência em programação C# 
- Sólida experiência em JS

## Benefícios: 
 - Plano de saúde e odontológico; 
- Vale Alimentação/Refeição Flexíveis; 
- Auxílio Home Office; 
- Seguro de Vida; 
- Alura 100% gratuita; 
- Remuneração Variável; 
- Plano de Carreira.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend C# Developer na Ploomes Sistemas Empresariais](https://coodesh.com/vagas/desenvolvedor-backend-c-125531349?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by Gilcemir** [comment]
Gabriela, bom dia!
Qual o nível de senioridade exigida para esta vaga?
Obrigado.
