### ISSUE TITLE
[Pernambuco] Back-end Developer @NutcacheBrasil

### ISSUE THREAD

**Issue by Criscampello** [backend-br/vagas#9280]
[Pernambuco] Back-End Developer @NutcacheBrasil

## Nossa empresa

Na Nutcache o time de desenvolvedores trabalha com a criação e aprimoramento de
funcionalidades para o nosso software. Procuramos fazer pequenas entregas constantes e com
qualidade, seguindo os preceitos de gestão ágil e da ferramenta Scrum.

## Descrição da vaga

Análise, planejamento e desenvolvimento da funcionalidade;
● Colaborar ativamente com o SCRUM Master e o Product Owner nas entregas;
● Participar da análise e arquitetura necessária ao desenvolvimento das tarefas;
● Seguir o método Scrum, utilizada pelos times para gestão das atividades diárias;
● Manter boa comunicação com o time de desenvolvimento discutindo e opinando sobre os
direcionamentos a serem tomados, buscando ajudar na solução de problemas com os pares
quando necessário.

## Local

Remoto ou Híbrido, Recife/PE

## Requisitos

**Obrigatórios:**
● Possuir formação completa ou em andamento em curso de Ciências da Computação ou
relativos;
● 2 anos ou mais de experiência como desenvolvedor;
● Experiência de 2 anos ou mais com desenvolvimento de aplicações em .Net Framework
(C#, Entity Framework e ASP.NET MVC)
● Microsoft SQL Server;
● ASP.NET Web APIs;
● Experiência na filosofia Ágil, mais especificamente no método SCRUM;
● Inglês intermediário / avançado / fluente (conversação)

**Desejáveis:**
● Capacidade de trabalhar de forma autônoma, com pouca supervisão;
● Experiência em desenvolvimento de front-end (HTML, CSS, Javascript e React)
● Habilidades de análise e resolução de problemas;
● SignalR;
● GraphQL;
● Docker;
● Excelente capacidade de gerenciamento de tempo e prioridades.

## Benefícios

● Plano de Saúde - Bradesco Saúde Top Nacional (100% custeado pela empresa);
● Plano Odontológico - Bradesco Odonto (100% custeado pela empresa);
● Seguro de vida - Prudential;
● Benefício de bem-estar físico e mental - Gympass;
● Vale refeição/alimentação - Flash benefícios flexíveis (Bandeira Mastercard);
● Gratificação por indicação de novos colaboradores;
● Material de trabalho completo;
● Day off no mês de aniversário;
● Horário e formato flexível;
● Auxílio idiomas;
● Auxílios de capacitação técnica;
● Clima colaborativo e flexível.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para cristianeferrao2012@mail.com com seu CV anexado - enviar no assunto: Vaga Backend Nutcache

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Nível
- Pleno
- Sênior

**Comment by makenchi** [comment]
Oi Cris, bom dia, gostaria de me candidatar a vaga, mas quando mandei o email, ele voltou. O email cristianeferrao2012@mail.com está correto?

**Comment by Criscampello** [comment]
Boa tarde Lucas,

Sim o email está correto, pode tentar novamente ou enviar seu currículo por
aqui mesmo.


Atenciosamente,


Cristiane Campello
*Tech Recruiter*

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 24 de mai. de 2022 às 11:56, Lucas Santos ***@***.***>
escreveu:
