### ISSUE TITLE
[São Paulo] Back-End Developer Pleno na [ICTS]

### ISSUE THREAD

**Issue by KIQ02** [backend-br/vagas#930]
A ICTS é uma empresa de consultoria, auditoria e serviços em gestão de riscos. Possuímos a mais ampla atuação do mercado de gestão de riscos, auditoria interna, Compliance, gestão da ética, prevenção à fraude e gestão da segurança. Oferecemos uma plataforma de serviços recorrentes de gestão de riscos, como o Canal de Denúncias, para a proteção contínua dos negócios.

**Você é:** 
Ético, comprometido, valoriza o trabalho em equipe e quer ser valorizado pelo seu trabalho?
Quer trabalhar num ambiente de inovação e que entrega soluções rápidas, objetivas e de qualidade?
A ICTS pode ser o seu lugar!

**Você tem:**

- Graduação em Engenharia, Ciências da Computação ou Matemática.
- Experiência e Gestão de Projetos baseados em Sistemas Web.
- Conhecimento metodologia AGILE.
- Conhecimento em Postgres e AWS.

**Você sabe/conhece:**

- Desenvolvimento e Manutenção de sistemas em JAVA/PYTHON;
- Manter um Back End moderno, baseado em JAVA/PYTHON;
- Microserviços utilizando as melhores práticas.

**Local de trabalho:** Alphaville - Barueri
**Forma de contratação:** CLT
**Benefícios:** 

- Assistência Médica;
- Assistência Odontológica;
- Vale Refeição;
- Vale Transporte;
- PLR;
- Patrocínios para cursos, certificações, especializações, etc;

**Como se candidatar:** 
https://tinyurl.com/y39t3res ou visite nossa página de carreiras em https://jobs.kenoby.com/protiviticarreiras

**#VEMPRAICTS

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!
