### ISSUE TITLE
[Campinas / Presencial] Back-end Developer @ Timesidiomas

### ISSUE THREAD

**Issue by Fabianasander** [backend-br/vagas#9314]
### Empresa: Times Idiomas
Somos uma rede de escolas de inglês com mais de 100 professores, especializada no ensino rápido e definitivo de adultos, que interage com você a qualquer tempo e onde você estiver.
Promovemos a efetiva comunicação universal através do inglês com a proposta de uma experiência diferente no ensino, aliando diversão, tecnologia e inovação.

### Descrição do Trabalho:
Executar a projeção de soluções de tecnologia da informação (TI), identificando a necessidade do cliente e seguindo os diagramas de arquitetura. Realizar a implantação de sistemas de tecnologia da informação e estabelecer padrões para ambiente de TI, acompanhando o planejamento e execução de testes dos sistemas, prestar suporte técnico ao cliente, seguir documentação técnica.

### Requisitos:
Laravel (ou ter trabalhado com PHP)
MySQL
HTML/CSS

### Horário: 
Segunda a Sexta-feira: 09:00 - 18:00 hrs

### Trabalho: 
Presencial

### Contratação:  
PJ

### Enviar currículo para:
rh@timesidiomas.com.br

Labels
- PHP
- PJ
- SQL
- Junior
- Presencial
- Laravel

**Comment by aeusteixeira** [comment]
Presencial onde?

**Comment by Fabianasander** [comment]
Bom dia,

 Campinas/SP 

Em 02/06/2022 17:55, Matheus Teixeira escreveu:

> Presencial onde? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/backend-br/vagas/issues/9314#issuecomment-1145332464
[2]
