### ISSUE TITLE
[Ponta Grossa/PR] Back-end Developer NodeJS Júnior @HunterCo

### ISSUE THREAD

**Issue by Criscampello** [backend-br/vagas#9328]
[Ponta Grossa/PR] Back-end Developer NodeJS Júnior @Trizy
==================================================
## Nossa empresa

A Trizy conecta quem precisa transportar a quem realiza o transporte, otimizando a gestão logística através de tecnologia e inovação na plataforma ou no aplicativo.

## Descrição da vaga

Procuramos Desenvolvedor Junior Node.JS com conhecimento em modelagem de bancos relacionais e Gitflow, para trabalhar de forma remota ou presencial com mapeamento de requisitos, desenvolvimento de novas funcionalidades e melhorias, garantindo a boa qualidade das entregas e prestando suporte técnico aos clientes internos.

## Local

Remoto - Ponta Grossa/PR

## Requisitos da vaga

Ensino superior completo ou cursando em Tecnologia da Informação, Engenharia de Software, Engenharia da Computação, ou áreas correlatas;
Experiência com Node.JS;
Experiência com Modelagem de bancos relacionais;
Banco de dados relacionais (gatilhos, pacotes e procedimentos);
Experiência com Gitflow;
Scrum

**Diferenciais:**
Conhecimento em Oracle
Filas
SVN
SCRUM
Testes automatizados

## Benefícios

Cartão Flash (crédito flexível, bandeira Mastercard)
Auxílio-híbrido ou Auxílio-home office
Odontoprev
Plano de Saúde opções (Unimed e Bradesco)
Racional do Bônus: de até 1x salário-base
Day Off de aniversário
Seguro de vida
Reembolso e custeio de despesas com viagens e deslocamento para sede em Ponta Grossa, se necessário.

## Contratação
CLT

## Como se candidatar

Por favor envie um email para criscampello@parceirohunterco.com.br com seu CV anexado - enviar no assunto: Vaga Backend NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Nível
- Júnior

**Comment by felipelouzeiro** [comment]
Olá, ter ensino superior na área é um requisito obrigatório ou a experiência com projetos também conta nesse caso?

**Comment by Criscampello** [comment]
Boa tarde Felipe,

Se as suas experiências são comprovadas profissionalmente, sim, contam
também na avaliação.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua., 1 de jun. de 2022 às 11:54, Felipe Louzeiro <
***@***.***> escreveu:

**Comment by ThiagoTatico** [comment]
CV enviado. : )

**Comment by NathBabs** [comment]
Hi @Criscampello is this position Remote Anywhere ?... I'm interested
