### ISSUE TITLE
[Remoto] Desenvolvedor Mobile na BN BR

### ISSUE THREAD

**Issue by gabbianiiii** [backend-br/vagas#933]
## Descrição
Atividades do desenvolvedor:

O app deverá possuir duas telas, sendo:
- Primeira tela apresentando os dispositivos bluetooth disponíveis e no rodapé possuir um botão chamado "Parear".
- Segunda tela apresentando todos os arquivos recebidos em forma de lista.

Este app deverá estar apto à receber os arquivos sem interação humana para confirmar a gravação.

## Linguagem / Frameworks desejadas
- Python;
- Kivy;
- BeeWare.

## Necessário
- Disponibilizar código fonte
- Realizar documentação (Incluindo testes realizados)

Aos interessados, enviar e-mail para raphael.pacheco@bnbrservices.com

**Comment by Lafaiet** [comment]
A vaga seria para desenvolver esse projeto, ou a descrição trata-se de um teste para a vaga?

**Comment by gabbianiiii** [comment]
> A vaga seria para desenvolver esse projeto, ou a descrição trata-se de um teste para a vaga?

Para desenvolver.

**Comment by gabbianiiii** [comment]
Vaga encerrada.
