### ISSUE TITLE
[Londrina-PR ou Remoto] Desenvolvedor backend pleno na Lapaza

### ISSUE THREAD

**Issue by danielsanfr** [backend-br/vagas#935]
## Sobre a empresa Lapaza Empreendimentos LTDA

Empresa responsável pelo desenvolvimento e manutenção de sistemas de estacionamento rotativo em várias cidades do Paraná e com pretenção de aumentar esse número ainda mais.

## Descrição da vaga

**Fullstack Developer**: Será o responsável pelo desenvolvimento contínuo do backend do nosso sistema, incluindo novas features, adaptações e correções de bugs.

## Requisitos obrigatórios:

* Experiência com **Python/Django** ou **Ruby on Rails** (2 anos ou mais);
* PostgreSQL
* MongoDB
* Git (Git-flow)
* Bootstrap
* Javascript/Typescript
* JQuery

## Diferenciais

* Boa experiência em manutenção de servidores Linux e utilizando containers Docker em ambiente AWS;
* Experiência com a AWS - Amazon Web Services (route53, elastic beanstalk, RDS, Elastic Cache, ECR, EC2);
* Conhecimento intermediário/avançado de docker e docker-compose;
* Conhecimento intermediário/avançado de Linux (server side);
* Experiência com shell script.

## Contratação

A combinar, podendo ser CLT ou PJ com férias e décimo terceiro salário. Os possíveis benéficios serão negociados a depender do tipo de contratação que desejar.

## Como se candidatar

Envie um e-mail para danielsan@vago.online com o título **Vaga para Desenvolvedor Backend**. Coloque sua pretensão salarial, links para Github e ou LinkedIn e também anexe seu currículo.

> **Labels**: AWS, Docker, Python/Django, Ruby on Rails, API, Backend, DevOps, CLT, PJ, Remoto, Pleno

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by danielsanfr** [comment]
Estamos com uma vaga para Python/Django.

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
