### ISSUE TITLE
[São Paulo - SP - Pinheiros] Backend Developer na Digesto

### ISSUE THREAD

**Issue by ricardocabral** [backend-br/vagas#936]
# Sobre a Digesto

Somos uma lawtech focada em tornar o direito no Brasil mensurável e computável através de tecnologia. Criamos novos produtos, serviços e tecnologias de extração, tratamento e classificação que entregam dados e inteligência agregada para nossos clientes.

Na Digesto você vai encontrar pessoas que priorizam o fazer acima do parecer e que têm paixão em usar tecnologia para resolver problemas de nossos clientes. Batalhamos diariamente para nos manter inovadores e aplicar com excelência tecnologias para melhorar a prática do Direito no Brasil.

# Vaga

Buscamos devs backend CLT ou estagiários(as) que amem tecnologia e gostem de criar software para resolver problemas e facilitar a vida de nossos clientes. Precisamos de alguém dedicado, ágil, curioso e com vontade de crescer junto conosco.

Você nos ajudará a entender problemas, analisar soluções, desenvolvê-las e testá-las. Há espaço para atuar em todas as fases do ciclo de desenvolvimento de software, desde a análise, acompanhamento em produção e suporte aos usuários. Temos demandas diversas em programação web, banco de dados, sistemas distribuídos e web scraping.

# Requisitos

- Conhecimento em linguagens de programação
- Noções de bancos de dados como MySQL, PostgreSQL: modelagem e querying de dados.
- Conhecimentos em HTML e tecnologias JavaScript (AngularJS, jQuery, etc.)
- Noções de Linux/UNIX
- Boa capacidade para trabalho em equipe: comunicação, iniciativa, senso de responsabilidade.

# Diferenciais

- Bom conhecimento em Python
- Noções de Cloud Computing
- Noções de web scraping

# Benefícios

- Remuneração acima da média do mercado
- Plano de saúde
- Plano odontológico
- Vale transporte
- Vale refeição
- Ambiente descontraído e ágil

# Outros

- Forma de contratação: CLT ou estágio de 20 a 30h/semana, via convênio formalizado com faculdade.
- Previsão de formatura a partir de Fev/2020

# Como se candidatar

[Enviar CV](https://docs.google.com/forms/d/e/1FAIpQLSf0UtVEQMxif0L87AmpmLawPe4bddfLqZEYb7BDkNUEWgBJYQ/viewform?usp=sf_link)

# Labels

> GCloud, AWS, Docker, K8S, Python/Flask, Web scrapers, Sistemas distribuídos, DevOps, CLT, Pleno, Estagio

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by ricardocabral** [comment]
@meselfiap olá, tentei mas nao consigo me logar (volta pra tela de login depois de submeter) nem recuperar a senha (o email nao chega)

**Comment by ricardocabral** [comment]
ah vou tentar postar sem logar.

**Comment by ricardocabral** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

ainda aberta, obrigado!
