### ISSUE TITLE
[São Paulo, SP] Desenvolvedor[a] Node.js Pleno/Senior | Jurema

### ISSUE THREAD

**Issue by etruta** [backend-br/vagas#937]
Desde 2010, a [Jurema](http://jurema.la) busca criar soluções que tornem o dia a dia das pessoas mais simples ou divertido. Combinando design e desenvolvimento de software concebe produtos e serviços que rompem os limites entre a web e o mundo físico, ajudando junto com seus parceiros - empreendedores, empresas e agências - a criar o futuro da web.

Estamos procurando um[a] Desenvolvedor[a] Back-End com boa experiência em Node.js para juntar-se a nossa equipe e nos ajudar na criação de um novo produto digital.

### Requisitos:
- Proficiência em Javascript ES6;
- Bons conhecimentos em Node.js, Express e Sequelize;
- Bom entendimento de programação assíncrona, suas peculiaridades e alternativas;
- Conhecimento básico de tecnologias front-end (HTML5, CSS3);
- Bons conhecimentos em modelagem relacional de dados;
- Experiência com arquiteturas RESTful e SOAP;
- Controle de versão de código-fonte em Git (Gitflow);
- Testes automatizados (BDD e TDD);
- Integração contínua e entrega contínua (CI/CD);
- Conhecimento do funcionamento de containers com Docker;
- Familiaridade com ambiente Linux.

### Desejável
- Boas práticas de desenvolvimento (S.O.L.I.D);
- Capacidade de autogestão e aprendizado;
- Familiaridade com scrum;
- 5 anos de experiência prévia no desenvolvimento de software;

Tipo de contratação: PJ

Estamos próximo ao metrô Vergueiro em São Paulo.

Interessados enviar email para jobs+nodejs@jurema.la

**Comment by diego-jo** [comment]
Olá, tem possibilidade de trabalhar remotamente?

**Comment by etruta** [comment]
@diego-jo, tem possibilidade sim de trabalhar remoto.

**Comment by caiocutrim** [comment]
fiquei muito feliz em ver essa vaga, ela dá um 'match' muito bom para o meu
perfil, já submeti meu CV.

Caio Cutrim - Fullstack Developer
Cellphone: +55 (98) 99112-2765


Em seg, 1 de abr de 2019 às 10:16, Eduardo Silva <notifications@github.com>
escreveu:
