### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor GRGi9

### ISSUE THREAD

**Issue by danielangelo98** [backend-br/vagas#94]
## Descrição da vaga
Estamos em busca de Desenvolvedores Full Stack que sejam curiosos, apaixonados por tecnologia, que queiram trabalhar em projetos sensacionais, colaborar, aprender e ensinar.
## Local

Rio de Janeiro

## Detalhes
- Curso superior em Tecnologia (completo ou cursando)

- Boa lógica de programação

- JavaScript (ES6)

- Conhecimento em um ou mais frameworks JavaScript (React, React Native, AngularJS)

- Conhecimento em alguma linguagem de Back-end (Node.js, Python)

- HTML5

- CSS3 (FLEXBOX, SMACSS, BEM ou OOCSS)

- Conhecimento em controle de versão como GIT

- Foco na entrega 

## Habilidades

- Desired Skills

- Conceitos de programação funcional

- Implementações de Flux (Redux, Reflux)

- Design Patterns (Observables e outros)

- Familiaridade com métodos ágeis

- Ativo na comunidade open source

## Contratação

CLT
## Nossa empresa
Área de atuação: Inovacoes e tecnologia
## Como se candidatar
https://app.vulpi.com.br/grgi9/535
## Labels

- Alocado
- CLT
- Junior

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
