### ISSUE TITLE
[REMOTO] - Vagas Python, Django e Java

### ISSUE THREAD

**Issue by gmenegatti** [backend-br/vagas#942]
Olá, pessoal,

Estamos em busca de desenvolvedores Java ou Python/Django, **de qualquer lugar do Brasil e com qualquer nível de conhecimento técnico**, para trabalhar no SlicingDice [1]. A única exigência é ter inglês fluente ou realmente avançado, incluindo conversação.

Por favor, quem tiver interesse em saber mais, peço gentilmente que envie um email para gabriel@slicingdice.com com seu currículo e pretensão salarial.

[1] - https://www.slicingdice.com

Agradeço pela atenção.

Abs,
Gabriel.

## Requisito:
- Ter um inglês fluente ou realmente avançado.

## Forma de contratação:
CLT, PJ ou Estágio.

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by gmenegatti** [comment]
Olá,

Postamos sim. Obrigado.

**Comment by ghost** [comment]
Viu só, não doeu colocar uma vaga que não fosse arrombada, né?
Agora, se você vai vir com papinho de "potencial participação" ou "10 horas por dia" durante a própria entrevista, aí o problema é do pobre coitado que se submeteu a te enviar o currículo antes de olhar o seu histórico no site, rsrsrs ;)

**Comment by RaulLima2** [comment]
Está aberto ainda?

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
