### ISSUE TITLE
[Campinas/SP/ Desenvolvedor (a) Web [Instituto Eldorado]

### ISSUE THREAD

**Issue by CynthiaAlvarenga** [backend-br/vagas#946]
**Atividades:** 

Atuação em projeto junto a times no exterior, com foco no desenvolvimento de ferramenta de acesso e controle de telefones celulares de forma remota, através de comunicação síncrona, utilizando tecnologias e protocolos de comunicação WebSocket e WebRTC. 

**Requisitos:**

- Formação superior concluída em Engenharia/Ciência da Computação, Sistemas de Informação, ou cursos similares;
- Experiência com desenvolvimento em JAVA para web;
- Experiência com desenvolvimento utilizando SpringBoot;
- Experiência com desenvolvimento em Angular 4 (ou superior);
- Conhecimentos em Android e Python são um diferencial;
- Inglês avançado para conversação, escrita e leitura, para contato com times no exterior.

**Local**

Campinas/SP

**Contratação**

**CLT**

Nossa empresa

O Eldorado é referência no Brasil em pesquisa, desenvolvimento e inovação nas áreas de software, hardware, ensaios e testes de produtos eletrônicos, com diversos prêmios como uma das Melhores Empresas para se trabalhar e começar a carreira! Venha fazer parte desta história que já tem 20 anos!

**Como se candidatar**

Basta acessar nosso site :)

https://www.eldorado.org.br/project/DesenvolvedorWeb_216/

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!
