### ISSUE TITLE
[Blumenau/SC] Python Developer no Serasa Consumidor

### ISSUE THREAD

**Issue by SelecaoSerasaConsumidor** [backend-br/vagas#949]
Você quer trabalhar em um ambiente com tecnologia de ponta e uma equipe altamente capacitada para mudar a vida financeira do consumidor brasileiro? #vempraserasaconsumidor

Já somos uma das maiores empresas digitais do mercado financeiro e estamos desenvolvendo produtos e serviços que vão mudar a forma como o brasileiro se relaciona com o dinheiro.

Somos um time com brilhos nos olhos, multidisciplinar e com autonomia para propor ideias. Se você é apaixonado pelas transformações do mundo digital, não tem medo de assumir riscos e quer sentir-se “dono do negócio”, vem trabalhar com a gente!

Como Python Developer você desenvolverá produtos inteligentes que vão para o mercado com alta volumetria e larga escala.

### O que buscamos?

Experiência com desenvolvimento Python. Experiência avançada em versionamento de código. Experiência com arquitetura em micro serviços e testes de software. Atuação com produtos 100% digitais. Inglês técnico

### O que pode diferenciar você?

Experiência em outras linguagens (PHP, Go, Elixir, Java Node.JS). Atuação em ambiente de startup, especialmente fintechs e/ou mercado financeiro. Experiência com arquitetura e desenvolvimento Cloud (AWS, Google Cloud). Experiência profissional em ambiente ágil.

### Oferecemos:

- Produtos com a possibilidade de fazer história e deixar legado!
- Ambiente desafiador e High Performance
- Times multidisciplinares e Multiculturais
- Pacote salarial atrativo;
- Pacote de benefícios;
- PLR anual;
- Previdência privada;

Entrar em contato: https://www.linkedin.com/in/alexandre-verardo-dedinho-csm%C2%AE-01406169/

**Comment by fcschmidt** [comment]
Perfil do linkedin, está bloqueado para receber mensagem!

**Comment by SelecaoSerasaConsumidor** [comment]
@fcschmidt irei te procurar no privado.

**Comment by victtorvpb** [comment]
@SelecaoSerasaConsumidor como faço? LinkedIn continua bloqueado.

**Comment by SelecaoSerasaConsumidor** [comment]
@victtorvpb pode nos enviar um e-mail para alexandre.dedinho@br.experian.com com os seus contatos para marcarmos um bate papo.

**Comment by victtorvpb** [comment]
@SelecaoSerasaConsumidor enviado.

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no PyJobs? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by SelecaoSerasaConsumidor** [comment]
@meselfiap obrigado pela dica. Vamos postar no PyJobs também.
