### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na AKREDITO

### ISSUE THREAD

**Issue by fellipecouto96** [backend-br/vagas#95]
## Descrição da vaga

Desenvolvimento utilizando nossa aplicação estruturada sobre Python e Django.

Já temos um mvp, mas precisamos fazer uma série de melhorias e ajustes.

No momento estamos procurando alguém para fechar um projeto piloto com duração de aproximadamente 3 meses (PJ). Se durante o projeto o desenvolvedor tiver fit com a empresa, pode vir a ser contratado (Emprego). Dentro da empresa, o desenvolvedor pode chegar até o posto de CTO.

## Local

Remoto ou Escritório, Rio de Janeiro - Rio de Janeiro

## Benefícios

- Não fazemos micro-gerenciamento ("We don't micro-manage", como se diz isso em português?)
- Feedback e comunicação direta com os fundadores
- Autonomia, espaço para criar e planejar
- Flexibilidade de horário
- Espaço para crescimento e desenvolvimento pessoal

## Requisitos

**Diferenciais:**
- Ter paixão por ajudar os outros
- Ser criativo, atento a detalhes e organizado
- Ser proativo
- Ter pensamento analítico e capacidade de resolver problemas de forma criativa

## Contratação

Faixa salarial: R$4000.00 - R$5000.00

## Nossa empresa

A Akredito é uma fintech com cunho social. Vamos ajudar milhões de brasileiros inadimplentes e negativados, renegociando e refinanciando as suas dívidas. Nossa missão é limpar os seus nomes! Atualmente estamos em fase inicial do projeto, mas pretendemos crescer exponencialmente no ano de 2018. Já criamos um mvp e testamos a plataforma com alguns clientes. Somos uma empresa jovem com paixão por ajudar os outros.

## Como se candidatar

https://app.vulpi.com.br/akredito/581

## Labels

- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
