### ISSUE TITLE
[Blumenau/SC] PHP Developer no Serasa Consumidor

### ISSUE THREAD

**Issue by SelecaoSerasaConsumidor** [backend-br/vagas#951]
Você quer trabalhar em um ambiente com tecnologia de ponta e uma equipe altamente capacitada para mudar a vida financeira do consumidor brasileiro?

Já somos uma das maiores empresas digitais do mercado financeiro e estamos desenvolvendo produtos e serviços que vão mudar a forma como o brasileiro se relaciona com o dinheiro.

Somos um time com brilhos nos olhos, multidisciplinar e com autonomia para propor ideias. Se você é apaixonado pelas transformações do mundo digital, não tem medo de assumir riscos e quer sentir-se “dono do negócio”, vem trabalhar com a gente!

Como PHP Developer você desenvolverá produtos inteligentes que vão para o mercado com alta volumetria e larga escala.

### O que buscamos?

- Experiência com desenvolvimento PHP 7.0 ou superior
- Experiência com microframeworks
- Experiência com desenvolvimento de API's REST
- Experiência em versionamento de código
- Experiência com arquitetura em micro serviços e testes de software
- Atuação com produtos 100% digitais
- Inglês técnico

### Oferecemos:

- Produtos com a possibilidade de fazer história e deixar legado!
- Ambiente desafiador e High Performance
- Times multidisciplinares e Multiculturais
- Pacote salarial atrativo;
- Pacote de benefícios;
- PLR anual;
- Previdência privada;

Entrar em contato: https://www.linkedin.com/in/alexandre-verardo-dedinho-csm%C2%AE-01406169/

**Comment by rios0rios0** [comment]
Olá, tudo bem?
Poderia fornecer um e-mail?
O Linkedin recusa mensagens para quem não é conexão, e cujo remetente que não é premium.

**Comment by johnatanivini** [comment]
Também gostaria de enviar, mas não sou premium.

*Johnatan Ívini*
---------------------------------------------------------------------
Especialização em Análise, Projeto e Gerência de Sistemas - ESTÁCIO
Graduado em Gestão em Tecnologia da Informação - FATENE
Programador Web
Site: http://www.johnatanivini.eti.br
*Tel (85) 9 8754-3565*



Em qua, 3 de abr de 2019 às 10:27, Felipe Rios <notifications@github.com>
escreveu:

**Comment by SelecaoSerasaConsumidor** [comment]
@rios0rios0 já estamos em contato. De qualquer forma podem entrar em contato também através do seguinte e-mail: alexandre.dedinho@br.experian.com

**Comment by SelecaoSerasaConsumidor** [comment]
@johnatanivini entramos em contato contigo também.

**Comment by THAYLLER** [comment]
Tambem tenho interesse fiz pedido para me adcionar como contato no linkedin e irei mandar email com meu curriculo

**Comment by SelecaoSerasaConsumidor** [comment]
@THAYLLER já entramos em contato, nessa semana vamos bater um papo sobre a oportunidade.

**Comment by THAYLLER** [comment]
ok to aguardando marcarem a conversa para dar seguimento

**Comment by SelecaoSerasaConsumidor** [comment]
@THAYLLER nossa bate papo está previsto para 22/04.

**Comment by THAYLLER** [comment]
opa blz
