### ISSUE TITLE
[HÍBRIDA|PRESENCIAL| REMOTO] Back-End Developer.NET @DQRTECH

### ISSUE THREAD

**Issue by Carladella** [backend-br/vagas#9515]
> Vaga Remota durante a pandemia

## Nossa empresa

Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

A DQR TECH está em busca de um profissional para atuar em Squad ágil no maior banco de Investimentos da América Latina.

[HÍBRIDA|PRESENCIAL| REMOTO]

## Requisitos

**Obrigatórios:**
Experiência em projetos de desenvolvimento de software utilizando .NET Core
Experiência em Modelagem de dados em DDD;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, SQS, DynamoDb, S3, EC2, RDS; etc;
Execução de Testes Unitário.

**Diferenciais:**
-Microsserviços;
Mensageria (RabbitMQ/Kafka, ou semelhante);
Design Patterns GoF;
Node.js

## Benefícios

Assistência médica e Odontológica para você + dependentes*;
Auxílio flexível de R$880,00 para gastar como quiser;
Acreditamos no desenvolvimento contínuo de nossos colaboradores, dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
Auxílio-creche;
Prêmio: Indique seus amigos, aqui sua indicação vale premiação em dinheiro*;
Seu aniversário tem pizza: No dia do seu aniversário a pizza é por nossa conta, para que você comemore este dia especial com as pessoas que você gosta;
Seguro de vida;

## Contratação
8k a 10k
CLT – 40h (semanais)

## Como se candidatar

Por favor envie um email para carla.dellafiori@dqrtech.com.br com seu CV anexado - enviar no assunto: Back-End Developer.NET
Ou se candidatar pelo site https://dqrtech.com.br/portfolio-items/desenvolvedora-backend-net-remoto/?portfolioCats=9%2C14

#### Regime
- CLT

**Comment by gsabreudev** [comment]
#vem para a @dqrtech
