### ISSUE TITLE
[São Paulo] Desenvolvedor Back End na TAKE

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#954]
### Sobre a empresa: TAKE

A Take nasceu para facilitar a comunicação entre empresas e pessoas. Nossa meta é revolucionar estratégias de comunicação e relacionamento aproximando a empresa e seu cliente. Temos uma plataforma chamada BLiP e metodologia própria de construção, gestão e evolução de contatos inteligentes, além disso somos parceiros e utilizamos os principais canais de mensagem: WhatsApp, Facebook Messenger, Telegram, sites e mais. 

Além da nossa expertise de 20 anos trabalhando com mensageria, temos alguns prêmios, reconhecimentos e conquistas que nos diferenciam: • Provedor de Solução Oficial para o WhatsApp Business solution • "Cool Vendor in Brazil" da Gartner em 2017 • Fornecedora Oficial para o Messenger no Facebook Business • Case global do Facebook com o chatbot para a Casas Bahia • Parceira e case referência da IBM • Parte da WeWork, a maior rede de coworkings do mundo • Desde de 2013 estamos no ranking da GPTW, o ranking das melhores empresas para se trabalhar.

### Descrição: Quais serão as suas responsabilidades?

Aqui na Take você será responsável pelo desenvolvimento de Chatbots que gerem real valor para as empresas clientes e seus usuários. Você utilizará tecnologias e metodologias novas e atuará no modelo de células digitais com profissionais de usabilidade, produto, data analytics, gestão e negócios. Assim, sua missão será construir produtos tecnológicos que melhoraram a comunicação das empresas com seus clientes e usuários.

### Você vai gostar de trabalhar na Take se...

Aprende rápido e está sempre em busca de resolver problemas;
Possui uma formação sólida e busca sempre crescer na sua carreira;
Trabalha com grande sendo de urgência;
Possui grande senso de responsabilidade, assumindo suas tarefas e se responsabilizando por elas;
Expressa seus pontos de vista de forma proativa;
Trabalha de forma ágil e procura resolver as coisas de forma simples e prática;
Gosta de feedbacks constantes, focados em desenvolvimento pessoal e melhoria contínua;
Quer trabalhar com um time fora da curva e que está em constante crescimento;
Valoriza um bom ambiente de trabalho, onde as pessoas trabalham de forma descontraída e sem formalidades desnecessárias.

### Benefícios:

Vale Alimentação ou Vale Refeição (R$42,00/dia);
Vale-transporte alinhado com a necessidade de cada Take.Ser;
Vale-Cultura para comprar livros, instrumentos musicais, ir ao teatro, shows, cinema e mais;
Horário flexível de verdade;
Se a empresa tem lucro, você merece uma parte! Por isso, todos recebem PL;
Plano de Saúde de referência e um Auxílio Odontológico;
Convênios com restaurantes, autoescola, academias e universidades.

### Labels:

Alocado
Pleno

### Candidatar: http://bit.ly/take_github

**Comment by filipemacedo** [comment]
Há vagas para desenvolvedor NodeJS?

Obrigado.

**Comment by megandavulpi** [comment]
> Há vagas para desenvolvedor NodeJS?
> 
> Obrigado.

Da uma olhada nessa aqui: https://app.vulpi.com.br/manac-capital/1133

De qualquer forma, envie seu currículo para: christian.veiga@vulpi.com.br

Posso te ajudar a encontrar a vaga ideal!
