### ISSUE TITLE
[Remoto] Estágio Back-end Developer Python @ Compass

### ISSUE THREAD

**Issue by ccrvlh** [backend-br/vagas#9552]
## Nossa empresa

[Compass](https://compasshq.io) é uma startup que desenvolve soluções de finanças & estratégia para empresas de médio e grande porte.
Nascemos da necessidade de uma gestão voltada a dados, alinhando a finanças e operações para uma visão completa das organizações.

## Descrição da vaga

Estamos buscando alguém para auxiliar em projeto de desenvolvimento e manutenção de aplicações. Time enxuto, altamente motivado para fazer acontecer. Adaptabilidade e autonomia na resolução de problemas sao fundamentais.  Essa não é uma vaga de uma grande empresa, com time estabelecido e equipes de suporte, foco em fazer acontecer. 

Remoto, com flexibilidade - foco no resultado.

## Local

Remoto

## Requisitos

O stack é composto por Flask/FastAPI, Celery/RQ, Redis, Docker, PostgreSQL, Kubernetes e alguns serviços serverless (SQS, Lambda, API Gateway). É importante ter alguma vivência com projetos web em Python, projetos próprios e etc.
A vaga será para colocar a mão na massa, bom para quem tem vontade de aprender na prática e fazer acontecer.  Valorizamos muito a participação dos profissionais em todas as etapas: desde o codebase backend até o CI/CD, deploy e monitoramento de infra, não é necessária nenhuma experiência nessa área, apenas vontade de aprender e botar a mão na massa!

**Obrigatórios:**
- Alguma vivência com aplicações web Python (preferencialmente Flask / FastAPI)
- Noções básicas de OOP, API REST, ORM e JSON
- Muita vontade de aprender
- Autonomia na resolução de problema
- Proatividade para buscar soluções
- Flexibilidade
- Organização
- Inglês

**Desejáveis:**
- noções de SQL
- noções de ORM / SQLAlchemy

**Diferenciais:**
- Horário flexível
- 100% Remoto

## Contratação

Estágio.
Preferência para 12-18 meses para formatura.

## Como se candidatar

Cadastro feito a partir do [portal de vagas](https://crafthouse.freshteam.com/jobs).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas após cada processo.
Qualquer dúvida favor utilizar o email: estagiario_backend_python_remot_id_WfmNEbbDdIAq@crafthouse.freshteam.com

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Estágio

**Comment by ccrvlh** [comment]
Aberta

**Comment by felippesantia** [comment]
Tenho interesse

Em sáb, 27 de ago de 2022 18:15, lowercase00 ***@***.***>
escreveu:

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
