### ISSUE TITLE
[Campo Grande/MS] PHP Developer @Wise

### ISSUE THREAD

**Issue by crispgcunha** [backend-br/vagas#9554]
SOMOS WISEANOS 🖖

Somos a Wise, uma software house feita por pessoas que amam e querem ser desafiadas dentro desse mundo de tecnologia. Pessoas diferentes e distintas que se unem para criar projetos incríveis! Temos wiseanos espalhados por esse Brasilzão todo e também uma grande maioria se encontra aqui em Curitiba/PR em nosso office.

Criamos soluções específicas para necessidades específicas. Gostamos de inovar, otimizar processos, implementar e/ou reorganizar todo o sistema de informações de empresas. Com essas melhorias, os processos se tornam mais produtivos e os custos de operação também são reduzidos.

Na vida, gostamos de dividir experiências com pessoas que estejam dispostas a se desenvolver, a ajudar. Errar faz parte do processo e enxergamos o erro como uma nova oportunidade de entender a situação ou problema para acertar nas próximas tentativas. Valorizamos muito novas ideias, criatividade, autonomia, companheirismo e bom humor dentro de um ambiente de trabalho super humanizado e com muita troca entre as pessoas, seja no presencial ou também no remoto.

Nossos times se esforçam bastante para continuarmos transformando o dia a dia das empresas. E aí, você quer fazer parte da nossa jornada?

**RESPONSABILIDADES E ATRIBUIÇÕES**
Programação de software existentes/novos
Análise da demanda e construção de interfaces e programação de APIs
Responsável para sustentar aplicações dos clientes da Wise
Entender a complexidade do modelo de negócio do cliente e contribuir para melhorar as aplicações e integrações existentes, propondo soluções de mercado e/ou criadas em experiências anteriores.

**REQUISITOS E QUALIFICAÇÕES**
**O que você precisa ter para esta função:** 
Conhecimentos em HTML5, CSS3 e Javascript básico;
Modelagem e consumo de API's REST;
Modelagem de bancos de dados relacionais;
Git para versionamento de código, nível básico
Angular – versão entre 4 e 10
Framework Cake-php
Construção/manutenção de de APIs
PHP versão 5.6 a 7.x
Comandos Linux
Algum conhecimento do processo de desenvolvimento ágil
Perfil fullstack
Mínimo de 2 anos de experiência como desenvolvedor.
Disponibilidade para o trabalho presencial em Campo Grande/MS

**O que é um diferencial:** 
Framework Laravel
Conhecimento em container Docker.
Conhecimentos básico em Kubernetes;
Github
GitLab
Experiência com banco não relacionais NoSQL;
Experiência em aplicação em nuvem (AWS)
Framework – ReactJS
Conhecimentos em Rabbitmq e/ou kafka e/ou NATS;
Conhecimento em fluxos de CI/CD (integração e entrega contínua).
Conhecimento em Metodologias e/ou Práticas Ágeis (Scrum, Kanban)

**INFORMAÇÕES ADICIONAIS**
Trabalho Presencial em Campo Grande/MS
Contratação PJ por tempo indeterminado 
Possibilidade de projeção de carreira 
Incentivos a Certificações
Treinamentos - Alura
2 semanas de descanso remunerado depois de 1 ano

**Como se candidatar**
Através do link: https://wises.gupy.io/jobs/2567619

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado em Campo Grande/MS
- Trabalho Presencial

#### Regime
- PJ (Pessoa Jurídica)

#### Nível
- Júnior
- Pleno

**Comment by crispgcunha** [comment]
Vaga aberta e aceitando candidaturas

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
