### ISSUE TITLE
[Remoto] Java Developer @Wise

### ISSUE THREAD

**Issue by crispgcunha** [backend-br/vagas#9555]
SOMOS WISEANOS 🖖

Somos a Wise, uma software house feita por pessoas que amam e querem ser desafiadas dentro desse mundo de tecnologia. Pessoas diferentes e distintas que se unem para criar projetos incríveis! Temos wiseanos espalhados por esse Brasilzão todo e também uma grande maioria se encontra aqui em Curitiba/PR em nosso office.

Criamos soluções específicas para necessidades específicas. Gostamos de inovar, otimizar processos, implementar e/ou reorganizar todo o sistema de informações de empresas. Com essas melhorias, os processos se tornam mais produtivos e os custos de operação também são reduzidos.

Na vida, gostamos de dividir experiências com pessoas que estejam dispostas a se desenvolver, a ajudar. Errar faz parte do processo e enxergamos o erro como uma nova oportunidade de entender a situação ou problema para acertar nas próximas tentativas. Valorizamos muito novas ideias, criatividade, autonomia, companheirismo e bom humor dentro de um ambiente de trabalho super humanizado e com muita troca entre as pessoas, seja no presencial ou também no remoto.

Nossos times se esforçam bastante para continuarmos transformando o dia a dia das empresas. E aí, você quer fazer parte da nossa jornada?

**RESPONSABILIDADES E ATRIBUIÇÕES**
Programação de software existentes/novos;
Análise da demanda e construção de interfaces e programação de APIs;
Responsável para sustentar aplicações dos clientes da Wise;
Seguir documentação funcional escrita pelo cliente ou por áreas da empresa;
Entender a complexidade do modelo de negócio e contribuir para melhorar as aplicações e integrações existentes, propondo soluções de mercado e/ou criadas em experiências anteriores.

**REQUISITOS E QUALIFICAÇÕES
O que você precisa ter para esta função:** 
Conhecimentos em HTML5, CSS3 e Javascript Intermediário;
Modelagem e consumo de API REST;
Modelagem de bancos de dados relacionais;
Git para versionamento de código, nível intermediário;
Construção/manutenção de APIs;
PLSQL – intermediário;
SQL Avançado;
Experiência em desenvolvimento com Springboot;
Experiência/Conhecimento avançado em Metodologias e/ou Práticas Ágeis (Scrum, Kanban);
Conhecimento em API, análise de cenários de problemas e análise de impacto na implementação de requisitos;
Uso das ferramentas Postman ou SoapUI;
Deploy em servidores de aplicação (Wildfly/Tomcat);
Java 6+, JUnit, Maven, Spring, Hibernate/JPA;
Mínimo de 5 anos de experiência como desenvolvedor.

**O que é um diferencial:** 
Banco de dados Oracle
Conhecimento em container Docker.
Conhecimentos básico em Kubernetes;
GitLab
Experiência em aplicação em nuvem (AWS)
Linguagem Node.JS
Conhecimentos em Rabbitmq e/ou kafka e/ou NATS;
Conhecimento em fluxos de CI/CD (integração e entrega contínua).

#### Regime
- Contratação PJ por tempo indeterminado 

#### Nível
- Sênior
- Especialista

## Benefícios
Trabalho Remoto, mas se você estiver em Curitiba/PR pode optar também pelo híbrido ou presencial.
Contratação PJ por tempo indeterminado
Possibilidade de projeção de carreira
Incentivos financeiros a Certificações
Treinamentos - Alura
Horário flexível
No Dress Code

## Local
Remoto

## Contratação
PJ a combinar

## Como se candidatar
Através do link: https://wises.gupy.io/jobs/2567929

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

**Comment by crispgcunha** [comment]
Vaga em Aberto e aceitando candidaturas

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
