### ISSUE TITLE
[São Paulo, Remoto] Engenheiro de Software - Pleno/Senior - no [ReclameAQUI]

### ISSUE THREAD

**Issue by diegoscampos** [backend-br/vagas#957]
O ReclameAQUI é uma das maiores plataformas reputacionais do mundo, e um dos 10 sites mais acessados do Brasil. O ReclameAQUI ao longo de seus 18 anos de existência, mudou a forma como clientes e empresas se relacionam no Brasil, e nosso sonho é transportar essa revolução para outros países, através de uma plataforma global. Você pode fazer parte disso! Bora?

### **O que você vai fazer:**

- Desenvolver automação de implantação e operação com mindset Devops 
- Desenhar e implementar modelos de dados tanto para Bancos Relacionais quanto para NoSql 
- Estudar e sugerir mudanças frequentes para manter o Software vivo e alinhado com os padrões atuais de mercado 
- Implementar software adequado para Cloud, alta audiência e alta disponibilidade.

### **Backend**

**_Necessário_**

- Desenvolver modelo de dados, queries, automações para Mysql e ou PostgreSQL 
- Desenvolver modelo de dados, queries e automações para MongoDB, Elasticsearch, Cassandra ou algum outro Nosql 
- Desenvolver e operar cache distribuido e ou datagrid (Redis, Infinispan, etc) 
- Desenvolver fluência com Java, Nodejs, Python ou Golang 
- Modelar de dados (Relacional e Nosql) 
- Implementar software distribuído baseado em micro serviços 
- Implementar batchs 
- Implementar gateways de api 
- Implementar integração com apis de terceiros 
- Gestão de versão de código adequada (git) 

**_Diferencial_**

- Capacidade de estudar e implementar padrões de software recentes (event sourcing, reactive, streams, functional, service mesh, etc.) 
- Implementar automação de implantação (salt, ansible, docker, kubernetes, etc) 
- Implementar testes unitários 
- Implementar módulos de monitoria (zabbix, prometheus, etc) 
- Implementar Pocs e testes eventuais para estudo

### **Local**

- Remoto ou Escritório (São Paulo - Berrini)

### **Contratação**

- Modelo de contratação CLT ou PJ, a ser combinado
- Salários compatíveis com o mercado de São Paulo
- Benefícios: VT, VR, VA, Plano de Saúde
- Ambiente nos times de engenharia: colaborativo, inovador e desafiador
- Ambiente na empresa: descontraído e preocupado com seu bem-estar

Por favor envie um email para leticia.prieto@reclameaqui.com.br com seu CV anexado - enviar no assunto: Vaga Backend

**Comment by diegoscampos** [comment]
O ReclameAQUI é uma das maiores plataformas reputacionais do mundo, e um dos 10 sites mais acessados do Brasil. O ReclameAQUI ao longo de seus 18 anos de existência, mudou a forma como clientes e empresas se relacionam no Brasil, e nosso sonho é transportar essa revolução para outros países, através de uma plataforma global. Você pode fazer parte disso! Bora?

### **O que você vai fazer:**

- Desenvolver automação de implantação e operação com mindset Devops 
- Desenhar e implementar modelos de dados tanto para Bancos Relacionais quanto para NoSql 
- Estudar e sugerir mudanças frequentes para manter o Software vivo e alinhado com os padrões atuais de mercado 
- Implementar software adequado para Cloud, alta audiência e alta disponibilidade.


### **Backend**

**_Necessário_**

Desenvolver modelo de dados, queries, automações para Mysql e ou PostgreSQL 
Desenvolver modelo de dados, queries e automações para MongoDB, Elasticsearch, Cassandra ou algum outro Nosql 
Desenvolver e operar cache distribuido e ou datagrid (Redis, Infinispan, etc) 
Desenvolver fluência com Java, Nodejs, Python ou Golang 
Modelar de dados (Relacional e Nosql) 
Implementar software distribuído baseado em micro serviços 
Implementar batchs 
Implementar gateways de api 
Implementar integração com apis de terceiros 
Gestão de versão de código adequada (git) 

**_Diferencial_**

Capacidade de estudar e implementar padrões de software recentes (event sourcing, reactive, streams, functional, service mesh, etc.) 
Implementar automação de implantação (salt, ansible, docker, kubernetes, etc) 
Implementar testes unitários 
Implementar módulos de monitoria (zabbix, prometheus, etc) 
Implementar Pocs e testes eventuais para estudo


### **Contratação**

Modelo de contratação CLT ou PJ, a ser combinado;
Salários compatíveis com o mercado de São Paulo;
Benefícios: VT, VR, VA, Plano de Saúde
Ambiente nos times de engenharia: colaborativo, inovador e desafiador.
Ambiente na empresa: descontraído e preocupado com seu bem-estar.

Para se candidatar, envie e-mail com CV para leticia.prieto@reclameaqui.com.br

**Comment by rodrigues882013** [comment]
Permite remoto @diegoscampos ?

**Comment by diegoscampos** [comment]
Sim, permitimos remoto. Boa parte da equipe é remota.

**Comment by diegoscampos** [comment]
> Permite remoto @diegoscampos ?

Sim, permitimos remoto. Boa parte da equipe é remota. Atualizei a descrição.

**Comment by ramonberrutti** [comment]
Ainda esta aberta a vaga?

**Comment by diegoscampos** [comment]
> Ainda esta aberta a vaga?

Já estamos entrevistando candidatos, mas esta aberta ainda.

**Comment by odravison** [comment]
A vaga ainda está aberta?

**Comment by diegoscampos** [comment]
Sim, na verdade uma outra equivalente, pode enviar o currículo para o e-mail da descrição.

**Comment by JosephSousa** [comment]
A vaga ainda está aberta?
