### ISSUE TITLE
[Vitória - ES ] Analista de Sistemas @LyonEngenharia/VALE

### ISSUE THREAD

**Issue by andreoliveiratech** [backend-br/vagas#9588]
Requisitos:

Conhecimento em linguagens de programação;
Desenvolvimento de APP;
Experiência anterior em análise e manutenção de banco de dados, sistemas e correção de falhas;
Necessário conhecimento avançado em Power BI e Excel

Atividades:

Elaborar de estudos técnicos e realizar manutenção de sistemas;
Analisar indicadores e propor melhorias nos processos;
Desenvolvimento de relatórios e indicadores utilizado o Power BI;
Gerir de banco de dados na Central de Monitoramento de Transportes;

Vaga para atender e trabalhar no nosso cliente VALE no Tubarão

**Comment by heitorutz** [comment]
como faço pra me aplicar?

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
