### ISSUE TITLE
[São Paulo] Application Developer Back-End at IBM

### ISSUE THREAD

**Issue by Kelycsf** [backend-br/vagas#96]
**Descrição da vaga**
O profissional será  responsável por desenvolvimento e manutenção de Aplicações Web. É esperado que a maior parte do trabalho ocorra em aplicações Back-End com possibilidade de alguma atuação também em Front End.

**Local**
IBM Hortolândia

**Benefícios**
VR/VA
Vida Link
Assistência Medica e Odontológica 
Fretado
PLR
Previdêcia Privada
   

Requisitos
* Sólida experiência em aplicações Back End em alguma das seguintes linguagens: Java, PHP, Node.js
* Disponibilidade e interesse em aprender novas linguagens conforme a necessidade do projeto.
* Conhecimentos básicos em Front End em alguma das seguintes linguagens: Java Script, PHP ou outras.
* Conhecimentos básicos em Front End em algum dos seguintes frameworks: Angular JS, Angular 2/4, Laravel
* Conhecimento em Criação e Consumo de Web Services  (APIs RESTful, SOAP)
* Conhecimento em Application Server (WebSphere Liberty, JBOSS, Tomcat o outro)
* Noção de Banco de Dados - Queries, SQL, Estrutura de Dados
* Experiência com ferramentas de controle de código fonte (GIT é um diferencial)
* Conceitos sólidos em Orientação a Objeto

Diferenciais:
* Conhecimento / Experiência em outras linguagens de Back End não citadas como requeridas
* Conhecimento / Experiência em linguagens de Front End não citadas como requeridas
* Conhecimento / Experiência em Banco de Dados não relacional (Mongo DB, Couch DB, outros)
* Conhecimento / Experiência com Desenvolvimento Ágil (Scrum)
* Conhecimento / Experiência em Continuous Integration  Continuous Deployment e ferramentas Dev Ops como Jenkins, UrbanCode Deploy ou similares
    
Contratação

Nossa empresa
A IBM é uma multinacional americana e uma das maiores em Tecnologia no mundo.

Como se candidatar
Entrar no site da IBM [https://ibm.biz/Bdi26G] e se candidatar na vaga 127613BR

Labels
    CLT
    Pleno

**Comment by kivervinicius** [comment]
@Kelycsf Há algum auxilio para quem re-alocação de quem não mora em são paulo?

**Comment by Kelycsf** [comment]
Olá Kiver, tudo bem?
 
Não há nada definido no processo seletivo, mas é um tipo de informação que pode ser negociado com o gerente da vaga no dia da entrevita.
                                                                        Kely Ferreira                        Brazil Senior Talent Acquisition Partner                        Product Owner for Developers, Architect and Consultant Skills                                                                                                                                                                                                                Phone: (5511) 2132-5824
                        E-mail: kelycsf@br.ibm.com                        Hortolândia, Brazil 
                        https://www.linkedin.com/in/kelyferreira/                          
                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                          This e-mail may contain confidential, proprietary, copyrighted, sensitive personal and/or legally privileged information solely for the intended recipient/s.                         The contents do not represent the opinion of IBM or any of its affiliates except to the extent that it relates to its official business. If you are not the intended                         recipient, kindly delete this e-mail and any attachments hereto, and inform the sender by return e-mail of your receipt hereof in error. Any unauthorized                         access to, review, reproduction, dissemination or other use of the information contained herein is strictly prohibited. Thank you.                        
 
 
----- Original message -----From: Kiver Teixeira <notifications@github.com>To: backend-br/vagas <vagas@noreply.github.com>Cc: Kelycsf <kelycsf@br.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [backend-br/vagas] [São Paulo] Application Developer Back-End at IBM (#96)Date: Fri, Feb 23, 2018 5:55 PM 
@Kelycsf Há algum auxilio para quem re-alocação de quem não mora em são paulo?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kivervinicius** [comment]
@Kelycsf apliquei para a vaga ontem. =)

**Comment by kivervinicius** [comment]
Vaga já foi preenchida?

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
