### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Backend Pleno @DeliveryMuchBrasil 

### ISSUE THREAD

**Issue by manoellapreuss** [backend-br/vagas#9610]
## A Delivery 

A Delivery Much é o maior aplicativo de delivery de comida do interior do Brasil! Acreditamos na democratização do delivery através da tecnologia. Por isso, enquanto startup, a DM valoriza imensamente o colaborador, pensando em ações para que o mesmo sinta-se pertencente atuando a partir de qualquer local do Brasil. Saiba mais e conheça os valores que nos acompanham em nosso dia a dia: https://carreiras.deliverymuch.com.br/#about

## Descrição da vaga

Como Desenvolvedor(a) Backend da Tribo de Payments você será responsável por garantir a implementação das regras de negócio, segurança, banco de dados e integrações dos produtos do squad em que fará parte, conforme as necessidades levantadas.

## Local

100% remoto 

## Requisitos

**Obrigatórios:**

- NodeJS/Go;

**Desejáveis:**

- MongoDB;
- APIs REST/RESTful;
- RabbitMQ;
- Github;
- Testes unitários.

**Diferenciais:**

- Testes de integração;
- Conteinerização (docker);
- Cloud AWS;
- Clean Code.
- Já ter trabalhado em franqueadora/conhecer o modelo.

## Benefícios

- Plano de saúde, Plano odontológico e Seguro de Vida;
- PLR semestral;
- VA/VR Flexível;
- Gympass e Gogood;
- Dayoff no aniversário;
- Investimento em capacitação;
- Parceria com SESC, ACATE e desconto em diversos estabelecimentos; 
- Flexibilidade de horários;
- Licença paternidade e maternidade estendida.

## Contratação

CLT 

## Como se candidatar

Através do link https://boards.greenhouse.io/deliverymuch/jobs/4989338003 ou aqui mesmo comigo! 

## Tempo médio de feedbacks

Costumamos enviar feedbacks na mesma semana! 

![#Vem ser Mucher 2](https://user-images.githubusercontent.com/107579926/177146113-24bded70-c7de-44a7-9ccf-4a6672460ae0.png)

**Comment by marcusformiga** [comment]
olá @manoellapreuss você tem email para que eu possa enviar meu cv ou linkedin ? tenho interesse em atuar com voces. grato

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
