### ISSUE TITLE
[Remoto] Back-end Developer .Net @ Premiersoft

### ISSUE THREAD

**Issue by maluconzatti** [backend-br/vagas#9617]
## Nossa empresa

Somos a 2ª Melhor Empresa de Tecnologia e a 4ª Melhor Empresa para se trabalhar no Brasil pelo #GPTW, também somos a 3ª melhor empresa de Desenvolvimento Mobile no ranking Brasil da Clutch! Você pode conferir mais [aqui](https://premiersoft.net/).

## Descrição da vaga

Buscamos por duas **pessoas Desenvolvedoras .Net** para atuar com a gente na reestruturação de API existente, totalmente desenvolvida em .NET Core!

## Local

Atuação remota, hibrída **ou** presencial (Blumenau/SC).

## Requisitos

**Obrigatórios:**
- Vivência com .Net Core;
- Conhecimento em padrões de projetos 
- Conhecer banco de dados relacional;
- Conhecimento em EF ou Dapper;
- Conhecimento em versionamento de código;

**Desejáveis:**
- Conhecimento em sistemas distribuídos (Docker e K8s);
- Conhecimento em Mensageria (RabbitMQ ou Kafka);

**Diferenciais:**
- Conhecimento ou vivência com sistemas de cooperativa de crédito.

## Como se candidatar

Por favor envie um email para rh@premiersoft.net com seu CV anexado - enviar no assunto: Vaga .Net 
Ou se candidatar [aqui](https://premiersoft.solides.jobs/vacancies/159065) pela plataforma

#### Alocação
- Alocado
- Remoto

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
