### ISSUE TITLE
Desenvolvedor SENIOR Java] CLT ou PJ - Remoto

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9621]
[Desenvolvedor SENIOR Java] CLT ou PJ - Remoto - R$ 7.500,00 a R$ 15.000,00 negociável
O que precisa?
Trabalha na área de back end com Java por pelo menos 4 anos.
Experiência e requisitos
Lógica de Programação
Conhecimento de Orientação a Objetos
Conhecimento em Versionamento de Códigos (git/svn)
Familiaridade com desenvolvimento na plataforma Java 8+
Familiaridade com Maven 3
Familiaridade com desenvolvimento de aplicações RESTful (JAX-RS) usando Jersey ou outro framework
Conhecimento em ORM utilizando Hibernate 3+
Conhecimento em Banco de Dados utilizando o MySQL 5.7+
Requisitos Desejáveis
Conhecimento em recursos Cloud usando o GCP (Google Cloud Platform)
Vue.js
JQuery, CSS, HTML
Testes unitários usando o JUnit 4+
Elaborar documentos técnicos necessários para o desenvolvimento de novas funcionalidades
Empresa
Uma plataforma focada em automatizar a operação de lojistas nos marketplaces.
Benefícios
Salário compatível com mercado e nível de experiência;
Trabalho remoto ou híbrido
Cartão de benefícios flexíveis;
Plano de saúde;
Plano odontológico;
Programa de educação financeira.                                  Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
