### ISSUE TITLE
[São Paulo/SP | Remoto] Software Engineer - Full Stack @ Fanatee Games

### ISSUE THREAD

**Issue by laizeamon** [backend-br/vagas#9625]
**Sobre a vaga**

O time de desenvolvimento da Fanatee é responsável por planejar, escrever e manter o código de programação dos nossos sistemas internos. Como parte desta equipe você vai trabalhar com programadores experientes, além de interagir com times de produto, design e BI. 

**Como Software Engineer, estas serão suas principais atividades:**
- Trabalhar na programação de sistemas, seja no desenvolvimento de PoCs, em novos sistemas ou na manutenção dos existentes;
- Atuar na otimização e na solução de bugs;
- Pesquisar soluções para problemas e desafios técnicos;
- Interagir com os times de produto em reuniões de briefing e acompanhamento.

**Requisitos**
Bacharelado em Ciência da Computação (ou áreas relacionadas) ou experiência de trabalho equivalente;
4+ anos de experiência prévia em desenvolvimento de sistemas de backend;
Domínio pleno de duas ou mais linguagens de programação;
Sólidos conhecimentos em programação orientada a objetos, design patterns, programação assíncrona, multithread;
Profundo conhecimento/experiência com arquitetura de dados com preferência pela tecnologia .NET;
Sólidos conhecimentos de Javascript, HTML e tecnologias [web.](http://web.experi/)
Experiência em DDD;

**Não são requisitos, mas serão considerados diferenciais:**
Conhecimentos de banco de dados não relacionais (ex:MongoDB) e conceitos de Big Data;
Familiaridade com a infra-estrutura da AWS;
Experiência com [vue.js](http://vue.jsser/)
Ser apaixonado por jogos.

**O que oferecemos:**

Contratação CLT;
Remuneração competitiva;
Benefícios flexíveis;
Assistência Médica e Odontológica;
PLR semestral;
Ambiente descontraído;
Uma sala para necessários momentos de descanso, cheia de snacks, frutas e bebidas quando no escritório.

**Sobre a Fanatee**

Somos uma startup fundada em 2013 e, desde então, nos dedicamos para que as pessoas possam jogar games a qualquer hora e em qualquer lugar. Somos perfeccionistas, guiados por dados e nosso talento consiste em transformar ideias em business: não à toa temos títulos de sucesso em nossa história, incluindo os aplicativos Stop e CodyCross, que juntos contam com mais de 130 milhões de downloads feitos ao redor do mundo. O mundo digital nos permitiu realizar nosso sonho: passar o dia todo em volta de pessoas talentosas, criando produtos que levam diversão e conteúdo à muitas pessoas ao redor do mundo!Se identificou com a nossa cultura e objetivo? Então se candidate e venha fazer parte do time Fanatee!

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
