### ISSUE TITLE
[HOME OFFICE] Back-end Developer @ Mttechne

### ISSUE THREAD

**Issue by techagassi** [backend-br/vagas#9626]
[HOME OFFICE] Back-end Developer @ Mttechne

## Nossa empresa

Somos uma empresa de tecnologia focada na construção de soluções inovadoras e geradoras de resultados de negócios para nossos clientes, e especializada em Desenvolvimento de Projetos, Eficiência Operacional, Gestão e Governança, Infraestrutura, Customer Experience e Meios de Pagamento.

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Dominio atuando com Java;
Experiência com Banco de Dados (DML, DDL, Oracle, SQL, DB2);
Experiência com Controlador de Versão e Teste de Perfomance (JUnit);
Sólidos conhecimentos com Sistema Operacional (Linux, UNIX), Websphere Application Server, JBoss, Websphere MQ;

**Desejáveis:**
Superior completo em Ciências da Computação, Analise e Desenvolvimento de Sistemas, Engenharias e áreas correlatas;
Inglês nível intermediário;
Vivências com XML, XSD, Json;
Entendimento de HTML, JavaScript, CSS, Wicket;
Conhecimentos com Webservice, Segurança e Negociações.

## Benefícios

Plano de Saúde;
Plano Odontológico;
Seguro de Vida;
Plano de Previdência;
Ajuda de custo Home Office;
Ajuda de custo com Educação;
Auxilio Medicamento;
Vale Transporte;
Vale Refeição;
Vale Alimentação;
Auxílio Creche;
Auxílio Filho com Deficiência;
PLR;
Gympass.

## Contratação

CLT FLEX

## Como se candidatar

Por favor envie um email para leticia.agassi@mttechne.com.br com seu CV anexado - enviar no assunto: Vaga JAVA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: leticia.agassi@mttechne.com.br

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
