### ISSUE TITLE
[Remoto] Back-end Developer .Net @ Code n' App

### ISSUE THREAD

**Issue by JorgeDelmaestro** [backend-br/vagas#9628]
## Nossa empresa

Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada.

Além disso, estamos em um ritmo de crescimento a-ce-le-ra-do, então se você curte desafios, busca evoluir e ama tecnologia, temos aqui um time para chamar de seu! Pois adoramos reconhecer e potencializar o desenvolvimento dos nossos Codenappers.

#VemPraCode ♥

## Descrição da vaga

A pessoa desenvolvedora .Net será responsável pela criação e evolução de sistemas web, APIs e integrações, tendo a oportunidade de atuar internamente ou em clientes parceiros, contribuindo em todo o ciclo de vida, desde a concepção até a implantação, atuando com metodologias ágeis para entregar uma solução eficiente. Esperamos que essa pessoa possa:

- Contribuir para o sucesso do projeto e o crescimento da equipe;
- Conhecer as boas práticas de programação das tecnologias utilizadas;
- Escrever código limpo, de qualidade e de fácil manutenção.

## Local

Remoto 

## Requisitos

- Cursando ensino superior na área de tecnologia da informação;
- Experiência no desenvolvimento de sistemas web, APIs REST e integrações;

Sólidos conhecimentos em:

- Framework .NET 5.0 ou superior, SQL Server, Linguagem C# e JAVA
- Experiência com SVN e GIT;
- DDD - Domain Driven Design;
- Conhecimento e aplicabilidade do Clean Code (Código Limpo).

Será um diferencial caso você conheça sobre:

- Linguagem Delphi;
- Microsserviços;
- Padrão ISO 8583;
- Inglês intermediário.

## Contratação

PJ 

## Como se candidatar

Para se candidatar, é só se inscrever no link: https://codenapp.gupy.io/jobs/2355941

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
