### ISSUE TITLE
[Remoto] Tech Lead Back-end Developer Node @maithatech

### ISSUE THREAD

**Issue by jaqicm** [backend-br/vagas#9633]
O time da **Maitha** está crescendo!

Somos uma empresa em expansão no mercado Tech. Buscamos evoluir, incluir, crescer, sonhar e aplaudir junto com as nossas pessoas. Queremos que você se sinta muito mais que número e resultados e, se quiser fazer parte de um time que tem como objetivo transformar as relações de carreira e vida pessoal, seu lugar é aqui.

Buscamos por **Tech Lead** para atuar em um Portal Cliente Gestou ou apoiar squads de Microserviços de uma Comercializadora de Energia Elétrica que acelera a transformação do mercado energético brasileiro e está em um momento de reestruturação tecnológica e com projetos super aquecidos.

Qualificações que buscamos:

Experiência com Node.js; Express.js, Nest.js;
Experiência com Bancos de dados relacionais NoSQL;
Experiência com mensageria e contexto de filas: RabbitMQ ou Kafka (dead letter, poison message);
Experiência com testes;
Experiência com Typescript, CSS, HTML e Java Script;
Experiência com Solid ou Clean Code; 
Experiência com Type ORM ou Sequelize ORM 

Desejável: 
Experiência com Vue.js / Nuxt.js /  Vuetify;
Experiência com  micro frontend e DDD.

O que oferecemos:

- Contratação PJ (Horas fechadas) / Valor a combinar
- 100% Home office;
- Gympass;
- Disponibilizamos Equipamento de qualidade;
- Programa de pontos e premiações;
- Oportunidade de desenvolvimento de carreira;
- EDI: nossa experiência de desenvolvimento individual acompanhado por especialistas em desenvolvimento humano;
- Programa de bem-estar;
- Programa de saúde mental;
- Eventos, talks e comunidades tech;
- E muito mais

Por favor envie um e-mail para jaqueline@maitha.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS
Confira e se cadastre também pelo nosso portal de vagas: https://maitha.com.br/vagas/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
