### ISSUE TITLE
[Remoto] Back-end Developer @ RD Station

### ISSUE THREAD

**Issue by Beatrizvianabernardino** [backend-br/vagas#9634]
## Nossa empresa

- Somos uma das maiores empresas do Brasil no modelo SaaS (software como serviço). Desenvolvemos uma plataforma 100% brasileira que automatiza tarefas de [marketing digital](http://bit.ly/3pQ2KQs) e [vendas](http://bit.ly/2ZTFzdm);
- Temos desafios de expansão nacional (onde somos líderes) e de [penetração internacional](http://bit.ly/3qY0zvo) na América Latina. Atendemos + 40.000 clientes de todos os portes em +30 países;
- As +700 pessoas do nosso time (RDoers, como chamamos por aqui) nos elegeram 8 vezes uma das melhores empresas para se trabalhar no país e nos deram [4.7 estrelas no Glassdoor](https://bit.ly/2ZOdJiK).

## Descrição da vaga

O desafio de nossa área de Engenharia está ligado à escala & performance, por isso estamos focados na evolução da nossa plataforma no tripé de infraestrutura (Kubernetes), dados (100% na GCP) e APIs (internas e externas) — e não vamos medir esforços pra isso! Para 2021, [vamos investir R$ 100.000 milhões](https://bit.ly/2NYZWDy) em tecnologia e aquisição de novos negócios que complementem nossa visão de plataforma, e colocaremos ainda mais grana se tivermos boas oportunidades na mesa.

Dentro do seu squad, você contará com o apoio de pessoas na posição de Team Leader, Product Manager, Designer e Developer, além de toda a galera dos chapters, guildas e tribos pra te ajudar a tracionar suas entregas como Software Engineer!

Você poderá atuar na tribo de email marketing ou na tribo de internacional.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento backend, preferencialmente com Ruby ou Go;
- Vivência com boas práticas de desenvolvimento, como Clean Architectures ou TDD, BDD, DDD e entre outras;
- Experiência com arquitetura em nuvem (AWS, GCP ou Azure).
- 
**Desejáveis:**
- Experiência com metodologias ágeis de entrega, Scrum ou Kanban;
- Conhecimento ESLINT, i18next e bibliotecas de internacionalização;

**Diferenciais:**
- Projetos opensource

## Benefícios

Link dos benefícios [aqui](https://talent.rdstation-tm.com/beneficios-rdstation).

## Contratação

CLT

## Como se candidatar

Para se candidatar é só clicar [aqui](https://grnh.se/5b6c9d542us). 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz.viana@rdstation.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
