### ISSUE TITLE
Desenvolvedor (A) Salesforce Sr - DQR TECH

### ISSUE THREAD

**Issue by Carladella** [backend-br/vagas#9637]
>De onde você quiser ou se preferir pode escolher o formato Híbrido (Itaim Bibi-SP).

## Nossa empresa

Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

Migrar um sistema legado para a plataforma Salesforce/Vlocity.

Responsável pelo time de arquitetura.

## Local

De onde você quiser ou se preferir pode escolher o formato Híbrido (Itaim Bibi-SP).

## Requisitos

**Obrigatórios:**
Experiência em projetos de desenvolvimento e arquitetura de software utilizando Salesforce;

Experiência com a plataforma Vlocity (fornecedora de software móvel e em nuvem).

Experiência com Metodologia ágil.

**Desejáveis:**
Atuado no setor financeiro (seguros);

Conhecimento em Arquitetura de Microsserviços;

POO; Padrões de Projetos.

## Benefícios

Vale Refeição/Alimentação;

Assistência Médica e Odontológica;

Seguro de Vida;

Acreditamos no desenvolvimento contínuo de nossos colaboradores,

dessa forma oferecemos acesso full aos cursos da plataforma ALURA;

Auxílio-creche;

Aqui a sua indicação vale premiação;

No seu aniversário tem mimos;

## Contratação

Contrato CLT (40 hrs semanais).

## Como se candidatar

Só encaminhar currículo com pretensão.
Para: [carla.dellafiori@dqrtech.com.br](mailto:carla.dellafiori@dqrtech.com.br)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by carolinetech** [comment]
🚨🚨🚨 Alerta de VAGA 🚨🚨🚨

🔊 Desenvolvedor (A) Salesforce Sr no seguimento bancário (área de seguros).

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
