### ISSUE TITLE
[SÃO JOSÉ DOS CAMPOS/ REMOTO] DevOps Engineer @ DEEPESG

### ISSUE THREAD

**Issue by murilo-arruda** [backend-br/vagas#9639]
## Nossa empresa

Nosso compromisso é solucionar um dos maiores desafios da sustentabilidade: como calcular e reportar métricas de sustentabilidade de forma uniforme e em escala global. 

Somos uma empresa de tecnologia jovem, movida pela busca da inovação, que respeita e valoriza os seus colaboradores, a diversidade e a ética.

No último ano crescemos acima da nossa meta de aquisição de clientes e precisamos que nosso time acompanhe esse crescimento.
Por isso, estamos atrás de novos Deepers que também queiram mudar o mundo com a gente. Vamos?

## Descrição da vaga

Estamos com vaga aberta de Cloud Architect / DevOps Engineer para trabalhar junto ao nosso time de produto. O objetivo é identificar soluções para o uso da nossa infraestrutura em cloud e otimizar nosso processo de CI/CD.

Principais atividades:
- Esteiras de CI/CD para aprimorar processo de deploy
- Cuidar das configurações na GCP para aprimorar nossa segurança
- Otimizar nossa arquitetura de cloud
- Trazer observabilidade/monitoramento ao código/processamento

## Local

São José dos Campos/SP - Modelo híbrido

## Requisitos

**Obrigatórios:**
- Conhecimento de Cloud (GCP)
- Experiência com Docker
- Alguma linguagem de script (Python, Shell Script, etc)
- Experiência com a implantação de esteiras CI/CD (Jenkins, Github Actions, etc)
- Conhecimento prático de IaC (Terraform, Cloudformation, Deployment Manager, etc)
- Gostar de trabalhar em equipe, compartilhar e ouvir novas ideias.
- Ser proativo e buscar uma solução para os possíveis problemas futuros.
- 
**Diferenciais:**
- Conhecimento sobre DevSecOps
- Conhecimento de ferramentas de monitoramento (Zabbix, Grafana)
- Experiência no uso de Kubernetes

## Contratação

PJ a combinar

## Como se candidatar

candidate-se no nosso site - https://deepesg.com/jobs

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
