### ISSUE TITLE
[Brasil] Back-end Developer Senior (PcD) @Reponto - Estratégia em Seleção 

### ISSUE THREAD

**Issue by BiaLemes** [backend-br/vagas#9640]
>## Nossa empresa

Somos uma empresa especializada em Recrutamento e Seleção (R&S) com foco em posições gerais, estratégicas, Pessoas com Deficiência e outros grupos de diversidade.

## Descrição da vaga

Buscamos Dev. Backend, perfil Sênior, com conhecimentos em Java ou Python.
Venha fazer parte de uma grande empresa do varejo e eleita a melhor empresa para se trabalhar no Brasil segundo o Great Place to Work 🏆⭐⭐⭐⭐⭐

## **Local**

Remoto 

## Carga horária

Full Time, em Horário Comercial

## Requisitos

**Obrigatórios:**
- Desenvolvimento back-end (Python ou Java)
- Bancos relacionais e não relacionais
- Docker, Git, Rest
- Testes unitários;
- Metodologias ágeis (Kanban/Scrum);
- CI/CD.

**Diferenciais:**
- Conhecimento em arquitetura orientada a eventos (pub/sub, fila, streaming, etc) e ferramentas (kafka, rabbitmq, etc)
- Bancos Relacionais: SQL Server, PostgreSQL
- Bancos Não relacionais: NoSQL
- Plataforma GCP
- Kubernetes
- Redis

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de Vida
- Vale Alimentação
- Vale Refeição
- Estacionamento

## Contratação

CLT + Benefícios 

## Como se candidatar

Por favor envie um email para beatriz@reponto.com com seu CV anexado - enviar no assunto: Vaga DevSR ou se inscreva pelo link https://jobs.recrutei.com.br/reponto/vacancy/26413-desenvolvedora-back-end-senior-python-ou-java-exclusiva-para-pessoa-com-deficiencia

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
