### ISSUE TITLE
[SENIOR Java Software Engineer with English] - Remote

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9646]
[SENIOR Java Software Engineer with English] - Remote - USD 4k-8k
Explore. Create. Implement.
We automate buying of ads on Google, Bing and Facebook using Java, MariaDB, Linux, Vue.js, Amazon Web Services and a number of open-source software.
You will:
Use your Java programming skills to help small businesses find customers by creating, and optimizing Google, Bing and Facebook advertising.
Collaborate with product managers on creating feature specifications
Design and code the software. Refactor the platform architecture as needed
Build and run automated test cases
Manually test the software
Manage the deployment of new features
Work with technical support on addressing on-going client issues
Whatever else is needed to get your job done
Experienced engineers will also experiment with new product ideas, and architect solutions from scratch
You Need:
Strong written and verbal communication skills in English.
Several years of Java programming experience
CS Degree or Relevant experience building great software products
MariaDB, Vue.js, API development experience strongly desired
Desire to work in a highly collaborative work environment, including pair programming
Facebook API experience highly desirable.                     Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
