### ISSUE TITLE
[Systems Engineer Python or Ruby or Java or PHP or JavaScript] - Remote

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9647]
[Systems Engineer Python or Ruby or Java or PHP or JavaScript] - Remote - USD 4k-8k
About This Role:
We are looking for a passionate and creative software engineer to work in a collaborative environment on our Engineering team.
For this role, we are looking for software engineers with strong analytical skills who are passionate about Systems/DevOps and Software Development, best practices, operations, and optimizations. The ideal candidate has a strong background in systems architecture and software development, complemented by a significant amount of experience working with deployment automation, continuous integration, and packaging.
They have multiple years of systems and software development experience and have released, supported, and scaled production systems. They have experience or understanding of what it means to implement infrastructure-as-code, ideally using Terraform/Terragrunt and SaltStack. They have a continuous growth mindset, a strong desire to research and learn, as well as an ability to help define our technology roadmap.
Responsibilities
Develop code, tests, and deployment automation
Write documentation as well as functional tests and deployment tests
Perform code, architecture, and systems reviews within and outside the team
Deploy systems to cloud environments using automation tools
Handle all aspects of Linux server management
Create a philosophy around monitoring and alerting, implement it, and continuously tune the thresholds
Provide support for multiple application and database servers
Debug ambiguous failures in infrastructure and bring them to resolution with fellow engineers
Respond to and deploy security updates and develop solutions to address vulnerabilities
Provide off-hours support on a rotating schedule and as-needed
Research and integrate emerging technologies
Work collaboratively and pair program with the team
Required Skills
Experience with deploying to cloud platforms (e.g. AWS or Google Cloud)
Experience with deployment automation (Terraform, Terragrunt, SaltStack, Ansible, or similar)
Programming experience in one or more languages: Python, Ruby, Java, PHP, JavaScript
Experience with Linux (Debian/Ubuntu, CentOS/RedHat) or BSD systems
Practical hands-on SQL knowledge (PostgreSQL, MariaDB, MySQL, or similar)
Demonstrate a functional understanding of basic networking, TCP/IP Protocols, DHCP
Comfortable with the Linux (or BSD) command line and intermediate Bash scripting
DevOps skills with focus in CI/CD, testing, benchmarking, monitoring, and security
Ability to mentor developers and lead projects of medium to high complexity
Required Experience
Systems Engineering: 5-8 years designing, deploying, and maintaining complex infrastructure via automation
Software Engineering: 3 - 5 years of designing and developing complex applications
Linux: 4 - 6 years experience managing and deploying applications and databases to Linux servers (e.g. Debian/Ubuntu)
AWS Cloud: 1+ years of professional hands on experience
Opportunities for Growth and Learning
Assigned mentors help you to learn new skills
Team-run classes on variety of tech training (i.e. systems administration, programming languages)
Conferences and training.                                            Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
