### ISSUE TITLE
[SENIOR Software Engineer Golang or Node.js and React.js with English] - Remote

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9648]
[SENIOR Software Engineer Golang or Node.js and React.js with English] - Remote - USD 4k-8k
Are you looking for a new challenge? Do you dream of an opportunity to be creative and have an impact on the lives of thousands of SMBs worldwide? If so… keep reading!
We’re looking for a Senior Software Engineer to join our team. As a senior technical memberli of this team, you will be responsible for designing simplified solutions that will change how our customers do business.
What are you going to do?
Work closely with the team to rapidly iterate on features
Participate in code reviews, peer support and architecture
Stay up to date with the latest technologies to ensure we are always using the best practices
Grow as a developer through peer mentorship and collaboration
What do you need to bring?
We're looking for a Senior Software Developer who has experience with the following:
Significant experience developing user facing applications
Experience writing automated unit and functional tests
Excellent communication skills
Either experience in, or an interest in working with node.js, golang, and react.js
Have worked in an agile environment in the past
What would be great to have?
Experience working in Golang
Experience working with node.js
Experience in microservice architectures
Experience with cloud environments like GCP, AWS, as well as container technologies such as Kubernetes, Docker, etc.
Experience with real time messaging systems (Pub/Sub, Kafka)
Experience with both relational (SQL) and non-relational (NoSQL) datastores
Practical understanding of HTML, CSS (SASS or equivalent)
Strong knowledge of JavaScript (ES6+) and Typescript
Solid understanding of cross-browser/platform issues and solutions
Experience building responsive websites
Experience using JS libraries/tools such as React.js, Node.js
What’s in it for you?
Ability to do your job in a truly flexible environment;
Genuine career opportunities in a company that’s creating new jobs everyday;
Work in a team big enough for growth but lean enough to make a real impact.                                   Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
