### ISSUE TITLE
[Remoto] Dev Backend Sênior (PJ) [Python/SQL]

### ISSUE THREAD

**Issue by tomas-itrecruiter** [backend-br/vagas#9655]
VAGA INTERNACIONAL 
[Python/SQL] Desenvolvedor Backend Sênior

*Empresa contratante*: a vaga está disponível em uma plataforma de recrutamento Freelancer que não disponibiliza o nome da empresa contratante, assim sendo, é feita a indicação do candidato, e todas as informações são passadas na entrevista inicial.

O cliente é uma empresa que investe em capital privado, capital de risco e fundos de cobertura de primeiro nível

O que os candidatos precisam ter?
● 5 anos de experiência em desenvolvimento
● Forte experiência em Python ou Python3 (preferencial)
● Experiência com Flask
● SQL
● Residir na América Latina
● Inglês avançado (verbal e escrito)

O que é bom ter?
● Experiência em Flask RESTful, API Python, Celery e SQLAlchemy
● Bom comunicador, team player, comprometido e autossuficiente.

O que os candidatos NÃO podem ter?
● Não pode ser jumpers
● Não pode ser um Freelancer

Salário a combinar

Interessados chamar no Whatsapp ou Telegram; 81 988564321

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
