### ISSUE TITLE
[Remore] Developer @ ESSS

### ISSUE THREAD

**Issue by Esss0102** [backend-br/vagas#9657]
> Vaga Remota 

## Nossa empresa

A ESSS é uma multinacional brasileira de base tecnológica, dedicada à simulação em engenharia. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE (Computer-Aided Engineering) na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente em âmbito global. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, Peru, Portugal, Espanha, França, México e Estados Unidos.

Contamos com um clima de trabalho colaborativo, oferecemos mais de 30 benefícios a nossos colaboradores, incluindo plano médico e odontológico, incentivos à educação continuada e apoio a cursos de idiomas, flexibilidade de horário e excelente infraestrutura.
Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, cadastre seu currículo em nosso site para que possamos conhecê-lo! https://esss.gupy.io/jobs/2569925

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor de Software. 

**Para essa posição seus principais desafios serão:** 

- Desenvolver tooling para otimizar e aperfeiçoar pipeline de construção das aplicações dentro de um sistema de CI (Integração Contínua)
- Desenvolver e manter tooling para provisionamento de máquinas de CI 
- Gerenciar e manter plataforma de CI com Jenkins e agents em Linux e Windows
- Desenvolver aplicações multi-plataforma com testes automatizados 

## Local

Exemplo: Remoto ou Escritório, Florianópolis/SC

## Requisitos

- + 2 anos de experiência com Desenvolvimento de Software.
- Proficiência em Python.
- Conhecimento em Linux.
- Bash e Windows Batch Files.
- Inglês intermediário.

Tecnologias e Processos que Utilizamos:

- Python 3 e C++.
- Testes automatizados com Pytest (unitários, integração e end-to-end).
- Integração Contínua (Jenkins).
- Puppet, Invoke, Conda.
- CentOS e WIndows.

## Benefícios

- Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
- Cartão de benefícios flexíveis.
- Licença maternidade e paternidade estendidas.
- Oportunidade para contribuição em projetos open source.
- Incentivo à educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
- Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
- Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se cadastre em: https://esss.gupy.io/jobs/2569925

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
