### ISSUE TITLE
[Remoto/Hibrido - Colombo, PR] Desenvolvedor Back-end @ BNE- BANCO NACIONAL DE EMPREGOS

### ISSUE THREAD

**Issue by israelaandrade** [backend-br/vagas#9659]
## Nossa empresa

Nós do BNE somos uma empresa de tecnologia com enfoque em recursos humanos.

## Descrição da vaga

Atuação na criação e de aplicações web, em projetos de alta manutenção no cenário nacional.

## Local

Remoto ou Hibrido em Colombo - PR

## Requisitos

**Obrigatórios:**
- Conhecimentos sênior C# [ASP.NET](https://asp.net/) CORE
- Conhecimentos sênior de MVC 
- servidor SQL

**Desejáveis:**
- Conhecimentos em processos assíncronos
- Desenvolvimento de sistemas em nuvem (Azure)
- SCRUM
- Angular
- Identity server

**Diferenciais:**
- Equipe altamente engajada
- Oportunidades de crescimento
- Ambiente descontraído
- Quarta do CS, na qual os devs se juntam após o trabalho para jogar CS

## Contratação

PJ a combinar

## Como se candidatar

Entrar no linktree ao lado e clicar na opção "vaga de back end sênior".
https://linktr.ee/ia_vagaserecrutamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: [israelaandrade@bne-empregos.com.br](mailto:israelaandrade@bne-empregos.com.br)

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

![Flyer no formato de Instagram (4)](https://user-images.githubusercontent.com/107878719/178501873-85d772ff-28bb-431a-9594-1b2eb06bfe61.png)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
