### ISSUE TITLE
[MySQL/Python] Desenvolvedor de Suporte Técnico

### ISSUE THREAD

**Issue by izabellethaina** [backend-br/vagas#9660]
## Nossa empresa
Empresa americana, com plataforma de colaboração para ensaios clínicos. A plataforma de soluções baseadas em nuvem oferece suporte a locais de teste, patrocinadores, CROs e outros parceiros em uma variedade de fluxos de trabalho específicos para gerenciamento de testes clínicos. O nome da empresa é disponibilizado após primeira etapa do processo.

## Descrição da vaga

● Fornece suporte conforme a necessidade para assinantes existentes que chegam à linha de suporte.
● Responde prontamente aos problemas e dúvidas dos clientes que chegam por e-mail e telefone.
● Auxilia na construção de servidores baseados em Linux para implantação em sites de clientes.
● Ajuda os clientes a instalar, configurar e usar a rede e os sistemas periféricos da empresa.
● Diagnostica, soluciona problemas e resolve problemas de portal, transporte e rede com os clientes.
● Gerencia vários casos de clientes simultaneamente e fornece atualizações regulares de progresso para clientes com problemas de suporte em aberto.
● Insere informações relacionadas ao cliente, incluindo histórico de casos, no banco de dados de rastreamento de contatos.
● Trabalha proativamente com engenheiros de software para fornecer à equipe de suporte informações atuais sobre problemas e resoluções do produto.
● Identifica, replica e documenta com precisão defeitos de software e aprimoramentos de produtos solicitados pelo cliente no sistema de rastreamento apropriado.

## Local

Estados Unidos; Full remoto

## Requisitos

**Obrigatórios:**
● Inglês avançado (verbal e escrito)
● É necessário diploma em uma disciplina técnica ou experiência equivalente com 1-2 anos de experiência anterior trabalhando em um ambiente de serviço e/ou suporte técnico que suporte servidores Linux (Red Hat ou CentOS Linux é uma vantagem).
● Excelentes habilidades de atendimento ao cliente
● +2 anos de experiência com os sistemas operacionais Windows e OS X.
● +2 anos de experiência com MySQL ou PostgreSQL (preferencialmente habilidade para escrever consultas complexas).
● Ampla compreensão das tecnologias LAN e WAN.
● Experiência em shell script (BASH, Python)

**Desejáveis:**
● Desejável experiência com sistemas de ticketing mas não obrigatório Salesforce, Desk, Jira, Confluence).
● Preferência por exposição à AWS e servidores de aplicativos

**Diferenciais:**
- Trabalho full remoto em empresa internacional
- Salário em dólar a combinar

Se interessou pela vaga? Me manda um whatsapp ou telegram para: (92) 98176-7671 =)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas para cada processo.

#### Nível
- Pleno-Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
