### ISSUE TITLE
[Remoto] Back-end Developer @NexMuv

### ISSUE THREAD

**Issue by Tech-Aline** [backend-br/vagas#9664]
> Vaga Remota durante a pandemia

## Local

Remoto 

## Requisitos

+ 3 anos de experiência como backend developer ou posição similar; Experiência em uma ou mais linguagens de programação orientadas a objeto (Go, PHP, JavaScript, Java, etc); Experiência com testes automatizados (TDD); Experiência em times ágeis; Conhecimentos em Clean Code; 

**Desejáveis:**
Experiência em criação de soluções cloud native; Experiência com soluções que usam cache; Conhecimentos em SOLID; Experiência na linguagem GO;

## Contratação

PJ

## Como se candidatar

Por favor envie um email para aline.lemos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga Back-end Developer

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
