### ISSUE TITLE
[ Remoto] Desenvolvimento Node.js Pleno

### ISSUE THREAD

**Issue by TherecruiterJu** [backend-br/vagas#9665]
Quais serão suas responsabilidades?

Estamos em busca de desenvolvedor NodeJs para atuar na construção de microserviços para uma plataforma global de pagamentos, responsável por prover funcionalidades para diversos países a partir de arquitetura Cloud baseada em Microservices, Jobs, APIs e Analytics. Para esta posição, o foco será em desenvolvimento de microseviços para atender as necessidades de negócio e integração entre sistemas e squads, bem como suporte dos ambientes e no entendimento dos dados da plataforma. Também irá auxiliar no desenvolvimento de arquiteturas de referência.

O que é necessário para participar desse processo seletivo?

 

  - Experiência com desenvolvimento em NodeJs (Javascript);

  - Experiência com testes e documentação, Swagger Open API, Async API;

  - Sólidos conhecimentos em arquiteturas de software, como: monolito, microsserviços, TDD, DDD, EventDriven Architecture, Hexagonal Architecture;

  - Necessário experiência com ferramentas de versionamento de código(Git);

  - Experiência em Containers utilizando Docker, Docker Compose;

  - Experiência com bancos de dados relacionais e não relacionais e de cache (Postgres SQL, MongoDB, Redis);

  - Processamento Async com message brokers, por exemplo: Azure Service Bus, RabbitMQ, EventHub, Apache Kafka, AWS SQS;

  -  Compreensão dos diferentes tipos de protocolo HTTP, AMQP, TCP, TLS;

  - Experiência com testes unitários, funcionais e integração, TDD;

  - Experiência em métodos ágeis com SCRUM;

  - Experiência com sustentação de aplicações em produção, monitoria, troubleshooting e análise;

 

Qual pode ser o seu diferencial?

 

  - Conhecimento em Azure Cloud (Azure ServiceBus, EventHub, AKS, App Insights)

  - Kubernetes

  - Experiência em CI/CD;

  - Experiência em grandes projetos com entregas modularizadas

  - Ferramentas de monitoria: Grafana

  - Protocolo ISO 8583 (87 e 93)

  - Inglês técnico

Envio de CV para techrecruiterju@gmail.com

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
