### ISSUE TITLE
[Remoto] Back-end Java Developer 

### ISSUE THREAD

**Issue by TherecruiterJu** [backend-br/vagas#9666]
Descrição da vaga:
Esta é uma vaga de uma empresa parceira ao qual presto consultoria, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Estamos em  busca Backend Java Developer para compor o time!

Buscamos profissional para atuar no Desenvolvimento Back end Sênior para cliente de grande porte no segmento financeiro.

Habilidades:
- Experiência em Java 8;

- Experiência em SOAP;

- Experiência em REST;

- Experiência em Spring Boot;

- Experiência em JUnit;

- Experiência em Maven;

- Experiência em Gradle;

- Experiência em Banco de dados Oracle;

- Experiência em Mongo DB;

- Experiência em Kafka;

- Experiência em GitLab;

- Experiência em Microsserviços;

- Experiência em metodologia ágil.

Qual pode ser o seu diferencial?
- Conhecimento no ramo financeiro;
- Conhecimento ou Experiência em OSB.

Local:
100% Remoto

Labels
Alocação
Remoto

Regime
CLT
PJ

Categoria
Back-End

Envio de CV para techrecruiterju@gmail.com

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
