### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack Sênior [Java e React]

### ISSUE THREAD

**Issue by TherecruiterJu** [backend-br/vagas#9667]
Esta é uma vaga de uma empresa parceira ao qual presto consultoria, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Estamos em  busca de desenvolvedor Fullstack para compor o time!

Responsabilidades e atribuições
- Desenvolver softwares para atendimento das necessidades internas;
- Atuar na manutenção de soluções existentes e propor melhorias nas mesmas;
- Participar de discussões técnicas para criar softwares de alta qualidade e alto desempenho;
- Implementar as melhores práticas técnicas com qualidade e segurança;
- Realizar testes unitários, teste funcionais e automação de testes das soluções desenvolvidas;
- Seguir as orientações da arquitetura de referência;
- Promover boas práticas e aprendizado contínuo;
- Documentar os projetos de software;
- Reutilização de componentes.

Habilidades:
- Experiência com conhecimentos avançados em Java 8 ou posterior;
- Experiência no desenvolvimento de APIs Rest;
- Experiência na arquitetura de micro-serviços;
- Experiência na Stack Spring (Spring Framework 4.0+, SpringBoot, Spring Data, Security, Spring Cloud, etc);
- Experiência JSP ( Java Server Pages ) e JSTL;
- Experiência com JavaScript / AJAX;
- Familiaridade com CSS e HTML;
- Experiência com React;
- Conhecimento intermediário em JPA/Hibernate;
- Experiência com bancos de dados relacionais (PostgreSQL);
- Experiência com Maven;
- Conhecimento intermediário em JBoss/Wildfly;
- Experiência em controle de versionamento com Git;
- Experiência com testes automatizados;
- Familiaridade com containerização (Docker).

Qual pode ser o seu diferencial?
- Conhecimento/Experiência com frameworks ágeis (Scrum, Kanban);
- Desejável conhecimento com filas e tópicos;
- Desejável experiência com bancos de dados não relacionais (Redis).

Local:
100% Remoto

Labels
Alocação
Remoto

Regime
CLT
PJ
Envio de CV para techrecruiterju@gmail.com

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
