### ISSUE TITLE
[REMOTO] Back-end Developer .NET 15k PJ - @DQRTECH

### ISSUE THREAD

**Issue by gsabreudev** [backend-br/vagas#9668]
## SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DESAFIO:
A DQR TECH está em busca de um profissional para atuar em Squad ágil no setor financeiro.
## REQUISITOS:
Experiência em projetos de desenvolvimento de software utilizando .NET Core
Experiência em serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, SQS, DynamoDb, S3, EC2, RDS;
## DIFERENCIAL:
Experiência em modelagem de dados em DDD;
React;
Conhecimento em Arquitetura de Microsserviços;
Execução de testes unitários;
Metodologia ágil.
## O QUE OFERECEMOS PARA VOCÊ:
Contrato PJ + notebook para desempenhar as tarefas + DESENVOLVIMENTO DE CARREIRA.

##  15K PJ 

Enviar seu CV para: gabriela.abreu@dqrtech.com.br

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
