### ISSUE TITLE
[Ruby on Rails] Software Developer Pleno

### ISSUE THREAD

**Issue by izabellethaina** [backend-br/vagas#9670]
**## Nossa empresa**

Plataforma fintech de última geração que gerencia o fluxo de trabalho de finanças, operações e comércio para programas de educação, recreação e atividades familiares.

**## Descrição da vaga**
Você irá trabalhar em todos os aspectos da produção. Isso inclui trabalho braçal (ou seja, novas páginas e comportamentos), otimizações de banco de dados, bugs e construção de novos módulos e conjuntos de recursos. Mandatório ter experiência programando em Ruby on Rails.

## Local
****
Full remoto

## Requisitos

**Obrigatórios:**

● 4+ anos de experiência em desenvolvimento software
● Inglês avançado
● Desenvolvimento fullstack
● Fluência em ambiente CI/CD.

**Diferenciais:**
● Ter enviado produtos FinTech e SaaS comerciais em seus empregos anteriores.

## Contratação

PJ, salário em dólar

## Como se candidatar

Me manda um whatsapp ou telegram: (92)98176-7671 =)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas após cada processo.

#### Nível
- Pleno-sênior

Palavras-chave:
| Ruby on Rails | back-end | CI/CD | Microsserviços

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
