### ISSUE TITLE
[Remoto] Tech Lead Back-end (PcD) @Reponto

### ISSUE THREAD

**Issue by BiaLemes** [backend-br/vagas#9676]
>## Nossa empresa

Somos uma empresa especializada em Recrutamento e Seleção (R&S) com foco em posições gerais, estratégicas, Pessoas com Deficiência e outros grupos de diversidade.

## Descrição da vaga

Buscamos Dev. Backend, perfil Sênior/Especialista, com conhecimentos em Java.
Venha fazer parte da fintech que vem crescendo exponencialmente, vem fazer parte de um tempo e que faz acontecer😎

## **Local**

Remoto 

## Carga horária

Full Time, em Horário Comercial

## Requisitos

**Obrigatórios:**
- Conhecer o ambiente bancário em sua visão geral (Abertura de relacionamento / adesão, aprovação de conta, Análise de Crédito, Pagamentos, Conta Corrente, Cartões - Débito/Crédito, Embossing, PIX, atendimento ao cliente, investimentos, seguros e ambiente ATM);
- Ter desenvoltura com o conceito de segurança digital (tipos de criptografia, autenticações, mecanismos de segurança, integridade, assinaturas digitais, etc);
- Conhecimento avançado em SQL Language, Java 8 ou superior para Back-End (Server Side), Ambiente de nuvem, Ambiente Linux e conhecimento de arquitetura em ambientes distribuídos (Micro serviços);
- Graduação completa.

## Atividades:

- Atuar como responsável na integração do next ao core bancário existente e ser o agente de mudança para um novo core bancário a ser definido;
- Desenvolvimento de soluções JAVA (Back end) para possibilitar essa integração através de APIs REST;
- Participar na solução de arquitetura de migração e convivência desse novo core bancário;
- Negociar com as áreas de negócio envolvidas sobre desafios que surgirão com a convivência e integração ao novo core bancário;
- Apoiar as squads envolvidas na remoção de blockers / defeitos que impactem a evolução das atividades relacionadas a essa evolução.  

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de Vida
- Vale Alimentação
- Vale Refeição

## Contratação

CLT + Benefícios 

## Como se candidatar

Por favor envie um email para beatriz@reponto.com com seu CV anexado - enviar no assunto: Vaga DevSR ou se inscreva pelo link https://jobs.recrutei.com.br/reponto/vacancy/27362-tech-lead-exclusiva-para-pessoa-com-deficiencia

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
