### ISSUE TITLE
[São Paulo ou São Bernardo ou Remoto] Pleno/Senior Developer na Sistematize

### ISSUE THREAD

**Issue by danielasantosrh** [backend-br/vagas#9677]
## Resumo da vaga

Programador Java - CLT ou PJ
Se você for PJ pode atuar em outros projetos que não seja concorrente.

Salário a combinar: estamos considerando a sua pretensão salarial
8 horas por dia (10h às 19h - flexível)

Benefícios (CLT):
VR R$ 22,59 por dia. VT, Plano de saúde AMIL, empresa paga 100% da mensalidade, e o colaborador paga a coparticipação em caso de utilização.

Você vai atuar diretamente com o CTO/CEO, participando de projetos importantes e estratégicos.

Java será usado no back e front

## Sobre a empresa e projeto

A Sistematize é uma Startup com foco em desenvolvimento de softwares de gestão e atendimento para o setor de serviços. Iniciou com o desenvolvimento de um ecossistema de pagamento que vai do atendimento no POS, recebimento, emissão de NFS-e, distribuição de fundos, gestão e conciliação de recebíveis a fim de dar escalabilidade para pequenas e médias empresas do setor de serviços. Estamos com projeto de banco digital com White Label, para atender as redes de franquias.

O projeto terá foco nos sistemas do grupo DryWash, na maior parte do tempo.
Detalhes: sistema de frente de loja, não fiscal, serviços. Atendimento, recebimento, integrado com sistemas de pagamento, parte web, administrativa, nível Brasil, todas as franquias usam. Tem o app celular. Tecnologia própria. Roda nas TVs, andamento dos carros, cloud Digital Ocean AWS, web. Algumas versões antigas desktop em processo de desativar. Trazer funcionalidade do sistema antigo para o sistema novo.

## Local

Remoto ou Escritório, São Paulo - Vila Maria ou São Bernardo do Campo - SP

## Requisitos

- Sistema legado
- Java
- JDBC, Swing, JSF, JPA (não mandatório)
- Tecnologia Rest Jersey framework ou Spring
- Postgress, Query SQL. Primefaces
- Java Android (conhecimento não obrigatório)
- JSP, Servlets.
- Containers: GlassFish e Wildfly.
- Experiência com desenvolvimento de APIs

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie um email para f.selecaorh@gmail.com com seu CV anexado ou link do seu LinkedIn - enviar no assunto: Vaga Java

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
