### ISSUE TITLE
[Remoto] Back-end C# Developer @ SharePrime

### ISSUE THREAD

**Issue by alexsandervasconcelos** [backend-br/vagas#9683]
## Nossa empresa

A SharePrime há oito anos desenvolve soluções que facilitam o dia a dia das organizações, conduzindo-as para transformação digital. Criamos valor por meio de conexões e experiências com tecnologia.
Estamos em pleno crescimento e buscamos talentos como você para integrar nosso time! 💛

**Nossos valores são os princípios que nos inspiram e guiam todos os dias**
•	Somos incansáveis pelo resultado;
•	Temos foco no cliente;
•	De pessoas, para pessoas;
•	Descomplicamos a tecnologia;
•	E temos coragem para transformar!

## Descrição da vaga

Buscamos profissionais com experiência em desenvolvimento com C# e .NET, que tenham conhecimento em CSOM e SSOM. Envolvidos no projeto ficarão responsáveis pela criação de listas em Sharepoint, portanto, conhecimento na ferramenta será bem vindo.

## Local

100% remoto.

## Requisitos

**Obrigatórios:**

- Linguagem C#;
- Plataforma .Net;
- HTML5;
- CSS3;
- Javascript;
- API;
- SQL Server;
- GIT/TFS.

**Desejáveis:**
- Sharepoint Online
- Sharepoint Onepremise
- Métodos ágeis e práticas como CodeReview
- Boas práticas de clean code

**Diferenciais:**
- Sharepoint Framework (SPFx)

## Benefícios

- VA + VR - Cartão Swile (flexível) - CLT
- Auxílio home office (50,00) - CLT e PJ
- Plano de certificações Microsoft - CLT e PJ
- Descanso remunerado de 30 dias para PJ

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para rh@shareprime.com.br com seu CV anexado - enviar no assunto: DS0722G

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@shareprime.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
