### ISSUE TITLE
REMOTO (Back-end Developer) para empresa de inteligência artificial e Machine Learning

### ISSUE THREAD

**Issue by gabrielanatascha** [backend-br/vagas#9687]
Se você gostaria de entrar para um time tendo como principal objetivo contribuir com a Transformação Digital por meio de inteligência artificial e do Machine Learning, essa vaga é para você!

Estamos em busca de um Desenvolvedor Pleno ou Sênior para atuar no desenvolvimento de back-end utilizando .Net e que possua certificação técnica em Google Cloud. 

Regime de contratação: CLT ou PJ - Projeto com duração inicial de seis meses com bastante chance de efetivação.

Carga horária: 20 horas semanais. Horário flexível. Remuneração: 7k

Interessados encaminhar currículo para: gabriela@escolhacertarh.com.br.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
