### ISSUE TITLE
[Remoto] Tech Lead Back-end @ BAVA

### ISSUE THREAD

**Issue by palomagarcel** [backend-br/vagas#9694]
## CONHEÇA O BAVA!

Acreditamos no equilíbrio das relações empresariais como parte fundamental de uma sociedade mais próspera. Com inteligência, impulsionamos e geramos negócios, apoiando a indústria, fornecedores e potencializando o varejo. Processos complicados e nebulosos não fazem parte de uma relação de confiança. Sabendo disso, com transparência, simplificamos o que era complexo e a partir da nossa expertise no segmento oferecemos o que há de mais moderno em meios de pagamento. O resultado? Impulsionamos negócios.

**Conheça os nossos valores, que guiam o nosso jeito de trabalhar:**

**OUSADIA** | Sonhamos grande, questionamos o status quo e antecipamos o futuro.

**GENTE EXCELENTE** | Valorizamos pessoas inteligentes, humildes e colaborativas, que trabalham duro, com autonomia e fazem acontecer.

**EMPATIA** | Verdadeiramente nos colocamos no lugar de nossos(as) clientes.

**SIMPLICIDADE E PRAGMATISMO** | Tomamos decisões baseados em fatos, dados e experimentos bem desenhados. Evitamos complexidades desnecessárias.

**ÉTICA E TRANSPARÊNCIA** | Somos brutalmente honestos(as) e claros(as).

## Descrição da vaga

A equipe de engenharia do Bava é formada por pessoas que são apaixonadas por resolver problemas de negócio com tecnologia, mas vamos além, estamos sempre olhando para as melhores práticas da comunidade. Assim como todas as equipes do Bava, na engenharia também temos pessoas que pensam grande, e que são incríveis individualmente e em grupo.

Seu dia a dia será repleto de desafios, terão projetos grandes ou pequenos ao mesmo tempo com rails e ruby puro.

## Responsabilidades

- Contribuir com o crescimento de seus/suas liderados(as), tanto na área técnica quanto em soft skills, atuando como facilitador(a) do desenvolvimento e aprendizagem;
- Fomentar e garantir o uso de boas práticas dentro do time;
- Direcionar o time na construção de soluções de APIs robustas, visando o crescimento e expansão destas soluções;
- Atuar em pontos chaves, como utilização de novas tecnologias e áreas sensíveis do código;
- Guiar o time no uso de metodologias ágeis, atuando como um(a) scrum master.

## Local

- Remoto - temos colaboradores de todo canto do Brasil e fornecemos os equipamentos para trabalhar de casa ☺

## Requisitos

- Conhecimentos em desenvolvimento de soluções utilizando clouds públicas (Ex: AWS, GCP, etc);
- Familiaridade com metodologias ágeis;
- Uma ou mais das seguintes linguagens de programação (Golang, Python, JavaScript, C#, Java);
- Construção de APIs Restful;
- Construção de testes unitários;
- Uso de bancos de dados relacionais (Ex: Postgresql, Mysql, etc);
- Comunicação de serviços assíncrona utilizando brokers de mensageria (Ex: RabbitMQ, AWS SQS, AWS EventBridge, etc);
- Construções de aplicações baseadas em microsserviços;
- Ferramentas de versionamento de código (algum framework de desenvolvimento. Ex: Git Flow, Trunk Based, etc);
- Manutenção de pipelines de integração e deploy contínuo.

## Diferenciais

- Conhecimentos em boas práticas de desenvolvimento (Ex: Clean Code, Desenvolvimento Seguro, etc);
- Experiência com APIs de Pagamentos (Gateways);
- Experiência com produtos produtos financeiros digitais (BaaS, Contas Digitais, etc).

## Benefícios

- Plano de saúde (sem descontos);
- Horário flex;
- Plano odontológico (sem descontos);
- Cartão Benefício Flex (Alimentação, Refeição, aplicativos de transporte);
- Gympass

## Contratação

CLT 

## Como se candidatar

Pela [GUPY ](https://bava.gupy.io/job/eyJqb2JJZCI6MTQwMTMwMSwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page) [ou enviar um oiê pro nosso [CTO ](https://www.linkedin.com/in/fglinhares/)(: 

## Tempo médio de feedbacks

7 dias.
Sendo o retorno positivo para trabalhar conosco ou construtivo. 

#### Regime
- CLT
- 40h/semanais

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
