### ISSUE TITLE
[Remoto] Pessoa Facilitadora Backend @Resilia

### ISSUE THREAD

**Issue by Luiza2203** [backend-br/vagas#9695]
## Nossa empresa - Resilia

A Resilia é uma *edtech* que prepara e emprega jovens para as profissões mais quentes do mercado. Questionamos o status quo e constantemente buscamos formas mais rápidas, acessíveis e eficientes de capacitar as pessoas para as profissões mais demandadas pelas empresas. Somos apaixonados por fazer as pessoas aprenderem e por gerar uma real diferença na vida dos nossos alunos e Resilientes. 
Nossa visão é capacitar a América Latina para o século 21. Para chegar lá, precisamos resolver desafios e problemas com tecnologia e gente boa.

## Descrição da vaga
No papel de pessoa facilitadora tech, você terá o desafio de facilitar o aprendizado e desenvolvimento dos nossos estudantes para que eles cheguem preparados no mercado de trabalho. Você será responsável por facilitar o conteúdo tech (já desenvolvido internamente) do módulo, que tem duração de 5 semanas. Você também será responsável por aplicar a metodologia Resilia.

Se você não conhece a nossa metodologia, não se preocupe, todos os aprovados serão formados nela antes de entrarem em sala de aula :)

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em:
    - NodeJS
    - NPM
    - Promessas
    - Rest & CRUD
    - SQLite3
    - DAO
    - Jest
    - Supertest
- Formação ou conhecimento em uma ou mais áreas a seguir: Engenharia da Computação, Tecnologia da Informação, Ciência da Computação, Sistemas para Internet, Análise e Desenvolvimento de Sistemas e/ou áreas relacionadas.
- Experiência mínima de 6 meses no mercado de trabalho
- Paixão por educação e o impacto que ela pode gerar
- Adorar se relacionar com pessoas e apoiá-las no seu desenvolvimento

**Desejáveis:**
- Experiência em monitoria, docência de cursos livres, técnico ou superior

**Essa será um pouco da sua rotina:**
- Facilitar aulas de segunda a quinta das 19 às 22hs (sendo que a sua parte da aula é em torno de 1h30) durante 5 semanas
- Fazer correção de exercícios de meio e final de módulo
- Participar de reuniões semanais de 1hs com o restante do time para discutir o desenvolvimento dos alunos e criar plano de ações
- Apoiar os estudantes no seu desenvolvimento, implementando planos de ação discutidos internamente

**Dedicação necessária para facilitar:**
- 25 horas semanais, tendo disponibilidade sempre de segunda a quinta das 19 às 22 hs

## Contratação
PJ a combinar

## Como se candidatar
Preencha Por favor o formulário: https://docs.google.com/forms/d/e/1FAIpQLSdl1rwO7pWC0vHgzEoGNZtqthifVT6MfVWcFltPEaDkGjt1WQ/viewform

#### Alocação
- Remoto

#### Regime
- PJ

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
