### ISSUE TITLE
[Remoto] Desenvolvedor .NET Pleno @ Acelera RH

### ISSUE THREAD

**Issue by jsantosrh** [backend-br/vagas#9708]
## Nossa empresa

Nosso cliente-parceiro é uma das HR-techs líderes no mercado de benefícios flexíveis. Uma plataforma rápida e inovadora, consolidando todos os benefícios em um só cartão. Sua cultura é horizontal, colaborativa e relacional.

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga

- O desenvolvedor vai trabalhar em uma equipe agil (Scrum) como full stack, dando manutenção e adicionando novas funcionalidades ao sistema.

## Local

- Remoto

## Requisitos

- ASP.NET MVC
- Bootstrap / HTML / Javascript
- jQuery
- .NET Core
- Bancos MySQL e MongoDB

**Desejáveis:**
- React
- NodeJS (NestJS)
- Typescript
- Cloud (AWS ou outras)

**Diferenciais:**
- .net, c#, .NET ⋅⋅ Core, MySQL, mongodb, react, NodeJs, typescript, cloud, aws, jquery, bootstrap, html, javascript, Agile

## Benefícios

- Benefícios flexíveis;
- Plano de Saúde;
- Seguro de Vida;
- Gympass;
- PLR

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para dbatista1@acelerarh.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor .NET Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: jsantos@acelerarh.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
