### ISSUE TITLE
[Senior Android Developer with advanced and spoken English] - Remote - $4500-$5500

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9719]
[Senior Android Developer with advanced and spoken English] - Remote - $4500-$5500 - Latin America, Canada and Europe Residents.
Proficient in native Kotlin/Java Android development
5+ years of mobile app development experience
BA in Engineering, Computer Science
Working knowledge of C#, Ruby/Rails, #!/bin/bash, and Agile Development processes.
Experience with Dagger, Coroutines, Navigation Component, single-activity applications
Familiarity with cross-platform development environments (Xamarin in particular) for reading legacy code is a plus.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
