### ISSUE TITLE
[Senior Software Engineer with advanced and spoken English] - Remote - $4500-$10000

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9720]
[Senior Software Engineer with advanced and spoken English] - Remote - $4500-$10000 - Latin America, Canada and Europe Residents.
70% front end 30% back end
5+ years of experience as a software engineer with frontend and backend development
React, ReScript, Elixir
Conducting testing (no QAs) and CI/CD (no DevOps)
Excellent knowledge of web development tools HTML, CSS, JS + React
Proficiency in at least one backend programming language NodeJs, Java, Go, etc
Experience working in a team ensuring code quality and system security through automation, unit testing, and structured code reviews.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
