### ISSUE TITLE
[Engineering Team Lead with advanced and spoken English] - Remote - $8000-$15000

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9721]
[Engineering Team Lead with advanced and spoken English] - Remote - $8000-$15000 - Latin America, Canada and Europe Residents.
As a Fullstack Engineering Manager, you will directly manage an engineering team and work shoulder to shoulder with your PM counterpart to drive team KPIs and OKRs
5+ years of professional experience as a software engineer with frontend and backend development.
3+ years of experience managing remote engineering teams at mid-size startups
Excellent knowledge of web development tools(HTML/CSS/JS + React)
Proficiency in at least one backend programming language NodeJs/Java/Go etc.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
