### ISSUE TITLE
[São Paulo] Analista Back End Junior/Pleno na [B2W Digital]

### ISSUE THREAD

**Issue by hugohaa** [backend-br/vagas#973]
## Sobre a vaga
Como desenvolvedor back end o profissional irá atuar junto a equipe de plataforma de frete (desenvolvedores, arquitetos, cientistas de dados e analistas de negócio), com o papel de estudar novas tecnologias e implementar projetos de inovação de alta escalabilidade e disponibilidade, alta performance, resilientes e orientada a eventos, além participar da arquitetura de microsserviços que atuam na estrutura de frete da companhia.

## Formação acadêmica
* Graduação em Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou Análise de Sistemas.

## Requisitos
* Conhecimentos nas linguagens de programação Java e SQL.
* Conhecimentos na Stack Spring (Spring Framework 4.0+, SpringBoot, Spring Data, etc.)
* Conhecimentos em versionadores (GIT)
* Desenvolvimento de serviços REST

## Desejável
* Experiência com bancos NoSQL.
* Experiência com docker
* Conhecimentos no ambiente AWS
* Conhecimento em frameworks front-end (angular, react, javascript, etc.)
* Python ou Scala
* Experiência em processos de carga para ambiente distribuído – HDFS
* Conhecimento no ambiente Cloudera, AWS ou Google
* Conhecimento em programação funcional

## Como se candidatar
* Envie um email para diandra.kuchar@b2wdigital.com com CV e referenciando a vaga pro time de Frete.

## Labels
* Alocado
* CLT
* Júnior/Pleno

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no [PyJobs](https://www.pyjobs.com.br)? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by JosephSousa** [comment]
A vaga ainda está aberta?
