### ISSUE TITLE
[São Paulo] Back-End Pleno/Senior na [Petlove]

### ISSUE THREAD

**Issue by alxpborges** [backend-br/vagas#974]
## Descrição da vaga

Vagas para o time de desenvolvimento da Petlove.
Se você é uma pessoa analítica, com um forte background em Ruby on Rails, temos uma ótima oportunidade para você:
Procuramos um profissional experiente para contribuir no desenvolvimento da nossa plataforma de produtos.

## Nossa empresa

A Petlove é o e-commerce líder no mercado, investido pelos melhores fundos de Venture Capital do Brasil. Nascemos em 1999 a partir do sonho visionário de um médico veterinário que foi pioneiro em apostar na venda online de produtos pet em uma época em que a internet no país ainda era uma incerteza. Hoje, são mais de 15 mil produtos vendidos através do nosso site e aplicativo e entregues em todo o território nacional. Somos mais de 280 petlovers que acreditam no investimento em tecnologia e amor pelos pets para continuarmos oferecendo os melhores serviços, produtos e conteúdos pet para nossos clientes: os peludos e suas famílias.

![petlove](https://user-images.githubusercontent.com/463350/55993560-cbbbd080-5c85-11e9-83df-74767dad5fe3.jpg)

## Local
[São Paulo - Berrini](https://goo.gl/maps/HarDqbMRWCL2)

## Benefícios

- Assistência médica
- Odontológica
- Seguro de vida
- Bicicletário no prédio
- VR/VA

#### Diferenciais

- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim;
- Crédito em nosso refeitório autônomo com uma variedade de Snacks =)
- Pet Friendly, pets são muito bem vindos no escritório =)
- Sala de jogos
- PLR anual
- Desconto em produtos no site
- Day-off de aniversário;
- Parcerias com descontos;

## Requisitos

**Perfil técnico:**
- Capacidade de trabalhar na concepção dos produtos, envolvendo equipe, clientes e stakeholders
- Levantamento de requisitos, pesquisa, provas de conceito
- Habilidade em propor e comunicar soluções de maneira clara e objetiva para a equipe e áreas de negócio
- Conhecer processos ágeis de desenvolvimento

**Tecnologias Obrigatórias:**
- Ruby / Rails
- Webservices / REST
- GIT
- Banco de Dados
- Cloud (AWS ou Google Cloud)
- TDD / BDD
- Linux
- Javascript
- Mensageria / Batch
- OOP e Design Patterns
- Docker
- NoSQL
- Redis ou Memcached
- Serverless

**Conhecimentos Desejáveis:**
- Elixir
- Kubernetes
- Elasticsearch
- NodeJS
- VueJS, React ou Angular 2+
- Machine Learning
- Big Data
- Python

## Contratação

CLT

### Presença

Distribuição em todo território nacional
Mais de 1 milhão de clientes

### Conquistas e Premiações

- [Melhores Apps 2017 na Apple Store](https://www.petlove.com.br/dicas/aplicativo-petlove-e-eleito-como-um-dos-melhores-ano-pela-app-store)
- [Loja mais querida Ebit 2017](https://www.ebit.com.br/premio-ebit/2017)
- [Loja mais querida Ebit 2018](https://www.ebit.com.br/premio-ebit/2018)
- [RA1000 no Reclame Aqui](https://www.reclameaqui.com.br/empresa/petlove-petsupermarket/)
- [Case de site mobile - Google 2018](https://www.youtube.com/watch?v=PsgW-0M67TQ&feature=youtu.be&t=17m17s)
- Primeiro pet shop Diamante Ebit

## Como se candidatar

Para se candidatar, basta se increver nos links abaixo:
- [Web Developer Pleno](https://petlove.gupy.io/jobs/38376)
- [Web Developer Senior](https://petlove.gupy.io/jobs/38228)

### Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

Email para dúvidas sobre o processo: [vagasti@petlove.com.br](mailto:vagasti@petlove.com.br)

## Labels

- CLT
- Pleno
- Sênior
- Presencial

**Comment by meselfiap** [comment]
Olá,

Vocês já postaram essa vaga no [PyJobs](https://www.pyjobs.com.br)? Acredito que possamos te ajudar a encontrar o profissional desejado!

**Comment by alxpborges** [comment]
@meselfiap Acho que o foco de vocês é mais desenvolvedores python né? Essas vagas são para devs Ruby
