### ISSUE TITLE
[Grande Vitória/ES] Back-end Developer/ Analista de Sistemas (SQL) @Espiral Engenharia

### ISSUE THREAD

**Issue by KassianeMendesS** [backend-br/vagas#9745]
## Nossa empresa

A Espiral Engenharia é comprometida em construir desde 1998.

Atendendo às demandas de serviços de montagem de andaimes no Setor Industrial e Construção Civil do Espírito Santo para todo o Brasil.

A Espiral Engenharia é consolidada como a maior empresa de engenharia de acesso, com andaimes industriais, plataformas elevatórias, formas para concreto, e maior locadora de equipamentos para escoramento metálico do mercado capixaba, levando o crescimento sustentável através de sua prestação de serviços a todo país.

Com unidades nas principais indústrias das regiões Sudeste e Nordeste, além de fazer locações e vendas de material para todo o Brasil, o foco é investir na busca de novas tecnologias, como acesso mecanizado das plataformas elevatórias e sistema rápido e econômico de formas prontas para a Construção Civil, atendendo com sucesso aos clientes e às necessidades do mercado.

## Descrição da vaga

Oportunidade para atuar como Analista de Sistemas, com foco em melhorias e customização dos sistemas internos da empresa. Buscamos uma pessoa com ótimo senso analítico para indicar o melhor caminho para resolução de problemas. 

O modelo é preferencialmente presencial, mas temos abertura para Híbrido e/ou Home Office.

## Local

Boa Vista II, Serra - ES (lateral da Hospital Vitória Apart).

## Requisitos

**Obrigatórios:**

- Vivência de pelo menos 1 ano em Programação SQL;
- Olhar analítico (quando as demanda chegarem você dirá o que é possível ou não de realizar e o prazo);
- Habilidades interpessoais de escrita e de comunicação verbal;
- Pessoa auto gerenciável, que busca conhecimento e seja resolutivo nos problemas;
- Preferencialmente, residir na região da Grande Vitória;
- Diferencial: Conhecimento no sistema TOTVS RM.

## Benefícios

- Vale Transporte;
- Plano de Saúde;
- Plano Odontológico;
- Cesta Básica;
- Vale Refeição;
- Seguro de Vida.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para consultorakassiane@gmail.com com seu CV anexado ou link do Linkedin - enviar no assunto: Vaga Analista de Sistemas - SQL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- A combinar

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
