### ISSUE TITLE
[Remoto] Back-end Java Developer @ DB

### ISSUE THREAD

**Issue by Lucasheck21** [backend-br/vagas#9746]
## Nossa empresa

Auxiliamos nossos clientes a viver o presente da melhor forma possível e construir um futuro melhor que o presente, a partir da convergência entre as melhores práticas de design e as principais tendências tecnológicas. Acreditamos na excelência técnica como valor essencial para  maximizar o impacto nos  negócios, com tecnologia e inovação.

Desde 1993 criamos soluções digitais para empresas no Brasil e no exterior, com especialização em segmentos como finanças, varejo, serviços, indústria e tecnologia, com ênfase em relacionamentos de longa duração.

## Descrição da vaga

Nesse projeto, trabalharemos juntos na transformação digital em um projeto financeiro focado em inovação. Nosso time é preocupado em propor as melhores soluções baseado em excelência técnica, pensando em alternativas que agreguem valor, com mindset ágil e cultura de colaboração. Nós respeitamos a diversidade e acreditamos que times diversos contribuem para construir ideias mais inovadoras.

## Local

Trabalhe de onde você quiser. Vaga 100% remoto. 

## Requisitos

AWS; 

Desenvolvimento Java (Spring); 

AWS 

Docker 

Git 

Kubernets 

PL/SQL 

Testes unitários; 

Web services e APIs (JSON ou XML sobre HTTP); 

Banco de dados Oracle, MongoDB e SQLSERVER (desejável); 

Práticas ágeis; 

## Benefícios

- Vale Refeição - Bandeira iFood Benefícios 

- Auxílio Home Office 

- Seguro de vida 

- Plano Odontológico 

- Plano de saúde 

- Cartão Flash 

**Diferenciais:**

Horário de Trabalho Flexível

## Contratação

Contrato CLT.

## Como se candidatar

Candidatura pelo link: https://db.gupy.io/jobs/1445270

Qualquer dúvida pode me chamar pelo e-mail: [lucas.heck@db.tec.br](mailto:lucas.heck@db.tec.br)  

Ou pelo Linkedin: https://www.linkedin.com/in/lucas-pheck/

## Tempo médio de feedbacks

Feedback em até 1 semana após processo seletivo. 

Caso você não receba um feedback dentro desse período, por favor, mande uma mensagem por algum dos canais como Linkedin ou E-mail. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
