### ISSUE TITLE
Analista de Sistemas Pleno

### ISSUE THREAD

**Issue by recrutamento-funcamp** [backend-br/vagas#9748]
[Campinas] Analista de Sistemas Pleno @FUNCAMP 
==================================================

## Nossa empresa
A Fundação de Desenvolvimento da Unicamp - FUNCAMP, instituída em 1977, com sede em Campinas/SP, é uma fundação de direito privado sem fins lucrativos, criada por escritura pública (Estatuto da FUNCAMP, art. 1º) e mantida com recursos próprios. A principal atividade da FUNCAMP é o gerenciamento de recursos de convênios administrativos (união de esforços com objetivo comum aos partícipes) e contratos, atuando, via de regra, como interveniente administrativa em projetos de interesse da UNICAMP e de instituições públicas e privadas, nacionais e estrangeiras. Sua responsabilidade consiste na gestão de recursos financeiros, físicos e humanos, controle contábil e fiscal, segurança jurídica e prestação de contas, tendo como referência o plano de trabalho acordado entre os partícipes de cada convênio. Esta atividade inclui aquisições de bens e contratações de serviços, assim como de pessoal necessário à execução dos ajustes.

## Descrição da vaga

- Adequar soluções à necessidade do cliente;
- Avaliar qualidade dos produtos gerados;
- Comparar alternativas tecnológicas;
- Desenvolver e implantar customizações e novas ferramentas, dimensionando requisitos e funcionalidade do sistema, especificando sua arquitetura, sugerindo ferramentas de desenvolvimento, especificando programas e codificando aplicativos;
- Elaborar documentação técnica;
- Monitorar o desempenho do sistema;
- Prestar atendimento e treinamento ao cliente;
- Simular problemas em ambiente controlado;
- Realizar outras atividades correlatas a critério do seu superior imediato e/ou em relação aos procedimentos do seu processo de trabalho e/ou em relação aos procedimentos do sistema da qualidade.

## Local

Avenida Érico Veríssimo 1251 Distrito - Barão Geraldo, Campinas - SP, 13083-851

## Requisitos

- Conclusão do Ensino Superior em Análise e Desenvolvimento de Sistemas ou áreas correlatas;
- Experiência profissional mínima de 06 (seis) meses na área de Análise, desenvolvimento e customizações na plataforma Sênior Sistemas, que deverá ser comprovada através da cópia da carteira de trabalho onde consta o registro ou declaração emitida pela empresa em papel timbrado. 

## Carga Horária

200 horas mensais, podendo variar para o período diurno, noturno, misto, na forma de revezamento, ou escala de serviço ou em regime híbrido.

#### Salário
- R$ 5.874,00
- Vale Alimentação; 
- Vale Refeição; 
- Vale Transporte; 
- Seguro de Vida; 
- Assistência Médica e Odontológica. 

## Contratação

CLT.

## Como se candidatar

OS CANDIDATOS INTERESSADOS DEVERÃO SE ATENTAR AS INFORMAÇÕES PRESENTES NO EDITAL 117/2022 E SE INSCREVER DIRETAMENTE PELO SITE DA FUNCAMP www.funcamp.unicamp.br, até o dia 19/08/2022

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
