### ISSUE TITLE
[Remoto] Back-end Developer NodeJs @ VTurb (25k PJ)

### ISSUE THREAD

**Issue by Joaoesdc** [backend-br/vagas#9749]
Link da Vaga no Notion: https://www.notion.so/vturb/Desenvolvedor-Full-Stack-no-VTurb-Node-js-3a3403e284774483847487023a2217ec

## Nossa empresa

O http://www.vturb.com.br é um software de player e hospedagem de vídeo. Nós ajudamos criadores de conteúdo a venderem os seus cursos através de vídeos de vendas. Acesse o http://www.vturb.com.br e assista o vídeo da Landing Page.

Somos uma Startup extremamente nova, de pessoas jovens, com uma equipe de apenas 7 pessoas. Apesar disso, já contamos com milhares de usuários pagantes.

Nós gostamos de:

1. [Transparência radical](https://www.youtube.com/watch?v=7KqyXF9f1dc), porque acreditamos que assim as relações são mais humanas e honestas.
2. Nos divertir enquanto trabalhamos, e temos liberdade para trabalhar de onde a gente quiser.
3. E também gostamos de ganhar dinheiro. Fazemos isso gerando mais e mais valor ao nosso cliente.

🤩 Até 2027, seremos o maior serviço de hospedagem de vídeo para marketing de resposta direta do mundo. Temos os contatos, o know-how e o mercado para fazer isso. Nossos fundadores, [André](https://www.youtube.com/watch?v=hySl-i9RBfc) e [João](https://www.youtube.com/watch?v=h12W5tAloZE), são especialistas em Marketing Direto.

**Nosso Tech Stack**

- NodeJs
- Ruby On Rails
- Golang
- Git, Github Actions
- Kafka
- NestJS
- React.js

💡 Nosso sistema conta com uma arquitetura de microsserviços e atualmente está, em grande parte, em *Ruby On Rails*. Você precisa ficar confortável com esse código. Estamos pensando em refatorá-lo para Node.JS em breve, por isso a vaga. Não se preocupe: no começo, você terá auxílio do desenvolvedor que fez o sistema, até que você consiga andar por conta própria e trabalhar ativamente no sistema.

## Descrição da vaga

Você será o principal responsável pela evolução da arquitetura do VTurb e pelos resultados do Time de Tecnologia, trabalhando junto com o CEO para construir a visão de produto do VTurb.

Você ajudará a montar a equipe de tecnologia, e você também colocará a mão na massa, codando o que for necessário.

Você deve ter boas noções de Front-End para conseguir conversar com os programadores, e deve proativamente propor soluções.

Você vai: 

- Planejar a evolução da arquitetura do VTurb
- Construir novas features, e refatorar features existentes.
- Gerenciar a equipe de programação, garantindo a qualidade do código, e a entrega nos prazos.
- Documentar o que você está fazendo.
- Implementar processos no Time de Tecnologia para aumentar a produtividade
- Propor melhorias na arquitetura do VTurb, de forma proativa.
- Identificar e solucionar bugs de forma proativa.

**Atenção: essa é uma vaga de período integral. Não esperamos que você trabalhe como freelancer por fora.**

Em resumo, você será o líder do Time de Tecnologia.

## Local

No melhor lugar do mundo: a sua própria casa.

## Requisitos

Não nos importamos com anos de experiência, mas sim com o que você sabe fazer. 

Caso você não se considere um desenvolvedor sênior, por favor, não aplique. Você vai gastar o seu tempo e o nosso.

Aqui estão as qualificações desejadas:

- Experiência sólida com Node.js em trabalho profissional
- GitHub e GitHub Actions
- Experiência sólida com Arquitetura Microserviços
- Experiência com NestJS
- Experiência com Kafka
- Excelente comunicação escrita: nós usamos Slack para discutir tudo.
- Experiência em metodologias ágeis

Além disso, você:

- É uma pessoa positiva, descontraída, que gosta de se divertir no trabalho.
- Gosta que outras pessoas vejam suas ideias, para você ter feedback e evoluir.
- Não tem medo de questionar quando você vê algo que considera errado, e não tem medo de admitir que você está errado quando percebe que você está.
- Você é uma pessoa racional, que sempre aceita a melhor ideia, mesmo que não seja a sua. **O VTurb não tem tempo e não tolera briga de ego. Usamos nosso tempo para ajudar pessoas, solucionar problemas, nos divertir e crescer.**

## Benefícios

- **Salário:** R$ 25k (PJ)
- **Possibilidade de Equity**: no futuro, é possível que você vire sócio do VTurb com um Contrato de Vesting. O seu crescimento depende apenas da sua vontade.
- **Local:** no melhor lugar do mundo, o conforto da sua própria casa (home-office) 😉. Eventualmente, fazemos encontros em alguma cidade do Brasil. O próximo será em Agosto, na cidade de Florianópolis.
- **Período:** essa é uma vaga integral. Não esperamos que você pegue qualquer trabalho por fora.

## Contratação

- PJ

## Como se candidatar

Queremos ter uma ideia de como você pensa, e como você se comunica por escrito. Por favor, nos envie um email para [joao.campos@vturb.com.br](mailto:joao.campos@vturb.com.br) com o **assunto: “Vaga Full Stack - *Seu_Nome_Aqui”***

O corpo do email deve conter, no mínimo, as informações abaixo:

- A URL do seu LinkedIn
- Por que você quer trabalhar no VTurb, e por que você quer essa vaga em específico
- Mostre algo que você codou que você tem orgulho. Se possível nos mostre algum código que você fez. Explique sobre o projeto.
- Nos pergunte tudo o que você quer saber sobre o VTurb e a vaga.
- Faça [esse teste rápido aqui](https://www.interviewzen.com/apply/QyNXxQ)](https://www.interviewzen.com/apply/QyNXxQ) de lógica, e diga o email que você usou para realizar o teste.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2-4 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao.campos@vturb.com.br

#### Nível
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
