### ISSUE TITLE
[REMOTO] Back-end Developer @99hunters 

### ISSUE THREAD

**Issue by Jennifergnun** [backend-br/vagas#9755]
[REMOTO] Back - End Developer @99hunters
Esta vaga está sendo fechada em parceria com a 99 hunters 

## Sobre a vaga: trata - se de uma startup tech, atua por meio de um marketplace para diversos tipos de soluções de e-commerce;

Atendem clientes privados e públicos, com foco em Vendas de Produtos e economia rotativa;

Tem cultura forte de protagonismo, não é um ambiente engessado, isso garante mais liberdade e crescimento acelerado aos profissionais;

prezam por desenvolver pessoas e ajudar na carreira dos colaboradores.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência 
- Experiência com Java, Springboot, REST APIs;

Conhecimento em banco de dados relacionais e não relacionais (SQL, MySQL, Oracle, MongoDB...);

Conhecimento em filas de mensageria (RabbitMQ/Kafka/SQS);

Conhecimento em boas práticas de desenvolvimento (Clean Code, Solid, entre outros);

Experiência com Metodologia ágil 

Experiência com testes automatizados (unitários e integrados);

Conhecimento em AWS e seus serviços.

Requisitos diferenciais:  Microserviços e Docker

## Benefícios

Vale Refeição
Seguro Saúde
Plano Odontológico
Auxílio creche

- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para @jennifernunesrh.tech@gmail.com 
- enviar no assunto: Vaga BackendJAVA

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
