### ISSUE TITLE
HOME OFFICE - Joinville SC - Back-end Developer C# ASP.NET PLENO

### ISSUE THREAD

**Issue by debora-recruiter** [backend-br/vagas#9757]
**Nossa empresa**
A Easy busca inovar tanto em seus produtos, como em equipe e cultura empresarial, pensando no dia de amanhã e quebrando paradigmas.

Contamos com uma equipe preparada e atualizada, que adora desafios, voltada para tudo o que for atual e inovador em tecnologia. O que permite que nossos produtos e serviços sejam sempre de alta qualidade e diferenciados.

A Easy é uma empresa que tem em sua cultura o desenvolvimento de sua equipe, sempre receptiva a novas ideias e conceitos. Estimulamos as pessoas a criar, inovar, desenvolver e evoluir. Nossa cultura empresarial permite isso, a expansão de horizontes e mudanças de conceitos, com o objetivo de uma evolução constante.

#VemPraEasy ♥

**Descrição da vaga**
A pessoa desenvolvedora back end será responsável pela criação e manutenção do código fonte para processar requisições web, tendo a oportunidade de atuar internamente ou em clientes parceiros. Esperamos que essa pessoa possa:

• Contribuir para o sucesso do projeto e o crescimento da equipe

• Conhecer as boas práticas de programação das tecnologias utilizadas

• Escrever código limpo, de qualidade e de fácil manutenção

Local
100% Home Office

Requisitos

• WebForms;
• Asp.Net  .Net 6 Net Core
• JavaScript + jQuery;
• SQL (Stored Procedures, Functions, Triggers);
• Unit Tests (NUnit, NSubstitute, FluentAssertions);
• EntityFramework;
• Docker 
• Kubernetes

Diferenciais:

• Utilização do Azure DevOps para a gestão de backlog e tarefas;
• Utilização do Git e GitFlow.

Benefícios
• Bônus Academia;
• Bônus Estudo;
• Bônus Horas Trabalhadas;
• Parceria escola de Idiomas (aulas remotas);

Contratação
PJ(Pode ser MEI)

Como se candidatar
Acesse o link e inscreva-se na oportunidade: https://www.easycomtec.com/homeoffice/developer

Alocação
100% Home Office
Regime
PJ
Nível
Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
