### ISSUE TITLE
[100% Remoto] Desenvolvedores Java Junior/Pleno/Sênior | Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [backend-br/vagas#9758]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga

Buscamos Java Developers para atuar alocado em um dos maiores banco de investimento da América Latina.  Atuará em diversos projetos de modernização de sistemas e automatização de processos de sistema legado que está para ser substituido e estão realizado um novo sistema. Terá contato com produtos de conta corrente, além de  projetos para offshore conta internacional.

Temos posições para Sêniores, Plenos e Juniores.

## O que buscamos nos perfis? 

Ter uma consciência de performance, como trabalhar em banco de dados para que não haja concorrência entre as transações. Conhecer banco de dados relacional e não relacional. Computação na nuvem (AWS é o que usam, mas pode conhecer outra cloud). Profissionais com experiência em Java que tb tenham interesse em Kotlin. 

_Requisitos técnicos:_
Conhecimento geral dos serviços da AWS ou outra cloud (para junior e pleno é um requisito não obrigatório/ desejável)
Ter sólido os conceitos de programação orientada a objeto e conceitos de serviços. 
Experiência em ambiente de Arquitetura de microserviços, arquitetura em clean code, Solid (para junior e pleno é um requisito não obrigatório/ desejável)
Experiência de mercado com linguagem Java e vontade de aprender  Kotlin, se já tiver experiência nesta segunda será um plus
Conhecimento em Spring framework como um todo.

## Atividades

Entendimento do problema/desenvolvimento de solução. Atuar próximo das áreas de negócios
Desenvolvimento de código com Java e Kotlin, desenvolvendo microserviços, utilizando os serviços da AWS.
Desenvolvimento de testes para garantir a qualidade do software. 
Escrever código de teste unitário, teste de software de produto.
Além de atuar nos novos projetos, o profissional também faz a construção de ferramentas internas para o time de suporte realizar a sustentação dos produtos. 
Resolver bugs, tirar dúvidas mais críticas

## Local

100% remoto

## Benefícios

- Assistência Médica
- Vale Refeição
- Seguro de Vida

## Contratação

A contratação será pela Robert Half como CLT - modelo outsourcing

## Como se candidatar

Por favor envie um email para livia.mello@roberthalf.com.br com seu CV anexado - enviar no assunto: Vaga Java (Pleno ou Senior ou Junior)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Junior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
