### ISSUE TITLE
[REMOTO] Back-End Developer na Citar Tech

### ISSUE THREAD

**Issue by meneguite** [backend-br/vagas#976]
![Citar.tech](https://s3-sa-east-1.amazonaws.com/citar.tech/assets/developers/dev-citar-tech.png)

### O que nós buscamos

* Responsável por desenvolver, testar e documentar rotinas;
* Atuar em implementações, melhorias de performance e integrações; 
* Desenvolver códigos bem estruturados utilizando boas práticas de programação;
* Realizar revisão por pares dos artefatos de programação; 
* Interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes; 
* Construir código com testes automatizados/unitários para garantir a qualidade.

## Local
Remoto

## Requisitos:
* NodeJs
* Experiência na utilização de banco de dados não relacionais, em especial MongoDb;
* Bom domínio de testes unitários/integração usando mocha/chai;
* Experiência na construção de Rest APIs;
* Dominio do Git para versionamento de projetos;
* Conhecimento básico em modelagem de dados, relacionais e não relacionais;
* Noções básicas de scrum e metodologias ágeis;

## Diferenciais:
* Experiência na utilização do docker;
* PHP 7+;
* Bom domínio de testes unitários/integração usando o PhpUnit;
* MySQL;
* Golang;
* Microservices;
* Experiência em tecnologias de IA ou machine learning;
* Linux;
* AWS;

## Contratação

PJ

## Como se candidatar

Após a execução do teste disponível em https://github.com/citartech/job-vacancies/blob/master/backend-node.md envie um email para rh.dev@grupocitar.com.br com seu CV anexado ou link do linkedin - enviar no assunto: Vaga Backend NodeJs

## Outras vagas abertas

Além dessa vaga de backend temos mais duas vagas uma de full stack e uma de frontend, caso tenham interesse podem visualizar mais detalhes nos repositórios abaixo:

> Frontend: https://github.com/citartech/job-vacancies/blob/master/frontend-vue.md
> Fullstack: https://github.com/citartech/job-vacancies/blob/master/fullstack-js.md

## Labels

- Remoto - Total
- PJ
- Pleno
- Sênior

**Comment by Luiz-junior** [comment]
Bom dia! A vaga ai está em aberto?

**Comment by THAYLLER** [comment]
tem um erro no texto do anuncio, quando vc diz que tem uma vaga tbm de front vc coloco beck kk

**Comment by meneguite** [comment]
Ainda está aberta sim.. pode deixar que fecho a issue quando finalizarmos a vaga.

**Comment by meneguite** [comment]
Obrigado a todos que fizeram a submissão para a vaga, ainda que tenhamos algumas vagas em aberto, em respeito aos que já enviaram vou fechar a issue para que consigamos colocar as submissões já enviadas em dia.
