### ISSUE TITLE
[Mogi das Cruzes/SP] .NET Core Back-end Developer @ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#9768]
## Local

Mogi das Cruzes – Três dias presenciais (Terça, Quarta e Quinta) e dois dias remoto (Segunda e Sexta).

## Requisitos

Experiência com .NET Core, .NET Framework, MVC, Angular, ORACLE, SQLServer, RabbitMQ, Microsserviço, Azure DEVOPS.

## Atividades

Desenvolvimento de atividades de programação .NET Web.

## Contratação

10 meses, podendo prorrogar

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - .NET Mogi/SP

## Labels

- Horário comercial
- Híbrido
- Sênior
- PJ

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
