### ISSUE TITLE
[Remoto Internacional] Scala Developer | Pacifica Continental 

### ISSUE THREAD

**Issue by leticiaamf7** [backend-br/vagas#9779]
## Nossa empresa 🌎

Pacifica Continental é uma empresa de recrutamento global especializada em cargos estratégicos, tais como membros da diretoria, c-suites, gerentes superiores e intermediários. Nossas soluções personalizadas e abordagem consultiva garantem a seleção dos melhores talentos do mercado.

Nossas operações alcançaram mais de 50 países, incluindo mais de 250 cidades ao redor do mundo. Orgulhamo-nos de trabalhar com precisão e conhecimento em uma ampla gama de indústrias. Sempre comprometidos com a obtenção de uma visão industrial contínua, fazemos parcerias com um grande número de empresas multinacionais e locais.
Desenvolvendo uma forte interface entre nossas operações, entregamos soluções globais com uma abordagem local.

## Descrição da vaga 📢
Nosso cliente está contratando um desenvolvedor **Scala Sênior** para contribuir com o time de desenvolvedores na construção de micro-serviços reativos de **back end** altamente simultâneos para grandes volumes de dados através de streaming Kafka. 

## Local✈

Remoto - Empresa localizada em El Salvador.

## Requisitos ✔

**Obrigatórios:**

-  1 ano de experiência com desenvolvimento Scala;

- 3 anos de experiência como Dev Backend;

- Experiência com Akka Streams, Akka http, Akka actors model;

- End to End reactive flows.

- 3 anos de experiência com metologias ágeis;

-  Proficiência em Inglês;

- Experiência com grande volume de dados;

**Desejáveis:**

- Cat

- Doobie 

- Slick 

## Contratação ✨

PJ a combinar - Remuneração em dólar;

## Como se candidatar 💻

Se identificou com a vaga? Você pode se inscrever aqui pelo link: https://recruitcrm.io/apply/16577194019330026088DvX.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

Em caso de dúvidas, ou demora no retorno durante o processo é possível contato via linkedin no perfil: https://www.linkedin.com/in/leticia-martins-fagundes/

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by leticiaamf7** [comment]
#Akka

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
