### ISSUE TITLE
[Remoto] Arquiteto .NET @ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#9782]
## Local

100% Remoto - Horário comercial (Full time)

## Requisitos

Principais linguagens: .NET; Kotlin; Swift.
Banco de Dados; SQL Server
Mensageria; RabbitMQ, KAFKA
Design Patterns: GoF, KISS, DRY, SOLID
Ferramentas de monitoração: Dynatrace, NewRelic
GCP, Diagramas C4.

## Atividades

Será responsável pela construção de solução e junto com o time, deverá olhar para o impacto no ambiente, cliente e organização.

## Contratação

Contratação: 6 meses, podendo prorrogar
PJ ou a combinar

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - Arquiteto .NET

## Labels

- Horário comercial (Full time)
- Remoto
- Sênior
- PJ ou a combinar

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
