### ISSUE TITLE
[100% Remote + PJ + U$D ] PHP Developer🐉 @Jobsity

### ISSUE THREAD

**Issue by OrianaRodriguez** [backend-br/vagas#9783]
Hi GitHub! are you excited about House of the Dragon🐉 coming up? I would be thrilled to have your Targaryen skills with PHP and Drupal on our team! I'm Orii, an IT Sourcer, and the House of Jobsity🔥 would like to see what you got!

🤸🏽‍♀️**We offer** full-time, long-term, 100% remote contracts with USD payments

 * Local Holidays and Vacations are off and paid
 * Extra OFF/sick days per year
 * 3 weeks of paid vacations (15 working days )🌴 
 * Unlimited PTO hours 
 * Financing program for equipment
 * 60 USD budget for e-learning courses every three months, like Udemy, Platzi, Pluralsight, and any other platform that you prefer.
 * Paid commissions if you refer a friend and gets hired👨‍👩‍👦‍👦 

### Before applying always keep in mind these details 
😉must have  +3 Years of professional experience as a developer _(excluding internships for this matter)_, located in LATAM **or** being able to work during Central Time Zones, and great English speaking skills🌎

### How to apply??🐱‍🏍
Send me a message and a connection request through [LinkedIn🎯 ](https://www.linkedin.com/in/oriana-rodr%C3%ADguez-3146b7199/)
or send me an email _with the subject_ **GitHub + tech stack you want to apply for + NAME**  and your updated curriculum ( .pdf format please 🙌🏽) to this email address oriana.rodriguez@jobsity.com

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
