### ISSUE TITLE
[REMOTO] Ruby on Rails Developer @ Meta 

### ISSUE THREAD

**Issue by jenniferaqn** [backend-br/vagas#9785]
## Nossa empresa

A Meta é uma companhia de tecnologia e inovação, focada em transformação digital (DX), que atua da definição da estratégia digital à entrega de soluções tecnológicas completas, colocando o ser humano no centro de todos os projetos. Com mais de 31 anos de mercado, a companhia tem atuação global: são 300 clientes em mais de 8 países, com uma equipe de 2,5 mil colaboradores, em 350 cidades e 14 países. 

## Local

100% remoto

## Requisitos

**Obrigatórios:**
- Ruby on Rails
- Microsserviços
- APIS e REST
- Experiência com atuação em times ágeis/squads/metodologia ágil
- Cobertura de teste com Rspec
- Conhecimento com jobs (sidekiq), mensageria (rabbitmq ou outras) 

**Diferenciais:**
-  Ferramentas de monitoramento (datadog, relic, papertrail, sentry...etc)
-  Design patterns (clean code, solid...etc)
- Conhecimento em CI/CD

## Benefícios

🏥🦷 Assistência Médica, Odontológica e Seguro de Vida
💳 VA e VR
💻 Auxílio Home Office | Ajuda de Custo
💰 PLR
📚 Capacitações: parceria com Microsoft Learn, Meta Academy (plataforma interna de treinamentos), English Club, além de parceria com escolas de idiomas. 
🧘🏻‍♀️ Parceria com Vittude: 40% de desconto em sessões de psicoterapia online
🤩🤑 Programa de Indicação de Talentos

## Contratação

CLT

## Como se candidatar

Conhece alguém ou se identificou? Manda seu cv para jennifer.silva@meta.com.br

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
