### ISSUE TITLE
[Remoto] Back-end Enginnering (Pleno e Sênior) @ Itaú Unibanco

### ISSUE THREAD

**Issue by gilagareiro** [backend-br/vagas#9789]
## Nossa empresa

Somos o Maior banco da América Latina, a marca mais valiosa do Brasil e a segunda melhor empresa para trabalhar segundo o ranking da Great Place to Work US 2021, estamos presentes em 18 países impactando diariamente mais de 55 milhões de clientes através dos nossos produtos e soluções.
Queremos ser uma empresa onde pessoas de todos os gêneros, raça, idade, orientação sexual e com deficiência escolham para se desenvolver, com diversidade em clientes, tecnologias, produtos, soluções e faremos isso com você!
Não queremos você apenas por achar que tem a nossa cara. Queremos ter um pouco da sua também!

O que esperamos de você?

Estamos buscando pessoas que queiram se desenvolver e aprender constantemente, compartilhando, colaborando, inovando e entregando valor para todos os nossos clientes. Aqui nos organizamos por modelos de comunidades e você fará parte de um time robusto e inovador.

## Descrição da vaga

Atuar em times ágeis e multidisciplinares com engenharia e desenvolvimento de aplicações BackEnd (Java/Spring/Kotlin);
Desenvolvimento de aplicações Cloud (Cloud Privada/AWS)
Gerar o desenho técnico de acordo com os padrões e referências de arquitetura de solução;
Desenhar soluções sustentáveis a partir do conhecimento da estrutura dos sistemas e soluções;
Garantir elasticidade e escalabilidade na construção de software;
Garantir a atualização da documentação e gestão do conhecimento dos sistemas;
Participar de todo o ciclo das aplicações desde a concepção a sustentação do projeto/produto;

## Local

Flexível ou Remoto - Escritório em São Paulo

## Requisitos

**Obrigatórios:**
Conhecimentos consolidados com BackEnd (Java/Springboot/Kotlin)
Conhecimento em banco de dados (Ex: SQL, Cassandra, Mongo DB, REDIS);
Conhecimentos em Cloud AWS;
Conhecimentos em qualidade dos softwares (Ex: BDD, TDD, testes unitários, testes integrados);

**Desejáveis:**
Construção de esteiras de CI/CD (Jenkins);
Principais Desing Patterns ;
Vivência em ambiente Ágil e DevOps;

## Benefícios

Vale Transporte
Vale Refeição (Restaurantes) / Vale Alimentação (Supermercados)
Convênio médico e odontológico
Seguro de Vida
PLR (Mediante resultados do banco)
Previdência privada
Descontos exclusivos em nossos produtos financeiros
Licença maternidade estendida
Auxílio Creche / Babá (para papais e mamães)
Incentivo a estudos
Gym Pass (Mas se preferir temos Bio Ritmo em alguns polos)
Acesso aos Clubes Itaú (Guarapiranga / Itanhaém e São Sebastião)
+ Algumas vantagens que você pode conhecer durante o processo

## Contratação

CLT

## Como se candidatar

Vaga divulgada no Linkedin: https://www.linkedin.com/jobs/view/3191743494

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias ao término de cada processo.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois o link de candidatura não está mais disponível ou não está mais aceitando candidaturas.
