### ISSUE TITLE
[Remoto] Back-end Developer @ Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [backend-br/vagas#9790]
> Vaga Remota 

## Nossa empresa

Somos um grupo focado em tecnologia e educação. Temos a missão de criar ferramentas inovadoras, afim de contribuir com o mercado de Dropshipping e educação!

## Descrição da vaga

-Criar aplicativos em versão Web;
-Desenvolver em VanillaJs;
-Prestar suporte e manutenção aos nossos produtos;
-Participar de Interações com todo time;

## Local

-Remoto (home Office)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento back -end:

**Desejáveis:**
- conhecimentos em Javascript;
-PHP;
-CodeIgniter;
-NodeJS;
-Api's Rest;
-Mysql;
-Redis;
-AWS S3;

**Diferenciais:**

## Benefícios

- Bônus de Natal
- Bônus de Férias
- Aulas de Idiomas
- Participação de Lucros
-Biblioteca de Cursos
- ...

**Diferenciais:**
- 1 horas de almoço

- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para serena@empreender.com.br com seu CV anexado - enviar no assunto: Vaga Back-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniele@empreender.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
