### ISSUE TITLE
[Híbrido x1 - RJ, Curitiba, SP ou Uberlândia] Back-end Developer @ The Bridge 

### ISSUE THREAD

**Issue by mariasecco** [backend-br/vagas#9791]
## Nossa empresa

Nosso cliente é um Banco que nasceu para a democratização do atendimento bancário. Para isso, está ampliando o time de tecnologia e busca uma pessoa que irá compor uma das Squads como Líder Técnico e de pessoas.

Você estará integrado à um time de cultura DevOps e atuará com o apoio, o desenvolvimento, implementações de códigos e soluções em cloud.

## Descrição da vaga
Perfil Pleno: https://thebridgesocial.gupy.io/jobs/2688463
Perfil Sênior: https://thebridgesocial.gupy.io/jobs/2688378

## Local

Exemplo: Híbrido, tendo sede em tais cidades: 
- São Paulo, SP
- Rio de Janeiro, RJ
- Curitiba, PR
- Uberlândia, MG

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Nodejs ou JAVA
- Experiência com soluções em ao menos um dos principais provedores de nuvem; (AWS ou Azure)
- Ensino Superior Completo

**Desejáveis:**
- Softwares para API Management, arquitetura API-first, API mashups, modelos de monetização, segurança de APIs
- Projetos Ágeis (Scrum)

## Benefícios

- VR + VR (1700 R$)
- Plano de Saúde
- Seguro de Vida
- Previdência
- PLR
- Auxilio Creche

## Contratação

CLT, diretamente com o cliente. 

## Como se candidatar

Por favor envie um email para maria.secco@thebridge.social com seu CV anexado - enviar no assunto: Vaga Back End ou enviar para o número +55 43 93618-4617.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 21 dias após cada processo.
E-mail para contato em caso de não haver resposta: maria.secco@thebridge.social 
Ou enviar mensagem para o número +55 43 93618-4617.

#### Alocação
- Híbrido

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
