### ISSUE TITLE
[Brasil] Back-end Developer Senior e Pleno (Node.js) @BeerOrCoffee

### ISSUE THREAD

**Issue by Leticiapsi2021** [backend-br/vagas#9793]
> Vaga 100% Remota.

## BeerOrCoffee - o maior marketplace de coworking da América Latina.

Você já sonhou em trabalhar de forma 100% remota e poder viver toda a liberdade e flexibilidade que esse modelo de trabalho oferece? Imagina ter +1.000 espaços ao redor do Brasil e poder trabalhar de onde quiser?
Se você ainda não conhece, somos uma plataforma que conecta empresas a espaços de trabalho em todo Brasil proporcionando maior liberdade, eficácia e inteligência na forma de trabalhar.

## Back end Developer (Senior e Pleno)

NodeJS

## Local

100% remoto (qualquer localidade do Brasil)

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento em NodeJs (ou linguagem correlata como Go e Clojure) para aplicações críticas ao negócio;
Experiência em desenvolvimento de software voltado para qualidade (TDD ou BDD);
Conhecimento em versionamento de código utilizando Git/Github/GitLab;
Experiência com equipes ágeis (Kanban, scrum,XP);
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
Formação superior completa ou cursando;
Escrita de testes automatizados;
Habilidade em design de aplicações pensando em boas práticas de integração, performance e segurança;
Experiência com práticas de DevOps;
Experiência com mentoria de novos membros do time;
Prévia experiência em startups ou Marketplace.
Inglês intermediário para leitura.

## Benefícios
✈️ Trabalho Remoto (Be #anywhere);
🎒 Kit Anywhereoffice (Você pode adquirir mochila, mouse, teclado, headset que desejar para o seu conforto no remoto);
🔑 OfficePass (Remoto não precisa ser apenas homeoffice, você terá acesso ilimitado a mais de 1000 coworkings);
🛫 BeerOrCoffee Wings (ajudamos no custo das suas viagens);
☕ Caju (Nosso cartão contempla as categorias: 🥗 alimentação, 🍴 refeição, ⛽mobilidade, 📚 educação e 🏠 ajuda de custo homeoffice)
🏋️‍♀️Gympass
🏥 Plano de Saúde & Odontológico;
👶🏽 Auxílio Creche;
💖 Head of Love (cuidando do bem-estar dos nômades);
🏖️ Annual BeerOrCoffee Retreat (Nosso encontro presencial dos nômades);
💰 Bonificação trimestral (exceto áreas que tenham comissão);
🥪 Snack Time (quando estiver trabalhando de algum dos nossos espaços, peça um lanche por nossa conta);
📖 12 minutos (app de livros);

## Contratação
CLT ou PJ a combinar

## Como se candidatar

https://beerorcoffee.gupy.io/job/eyJqb2JJZCI6MjYzNTE1OCwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks após cada etapa do processo.
E-mail para contato em caso de não haver resposta: leticia.franca@beerorcoffee.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
