### ISSUE TITLE
[Remoto ou semipresencial em Colombo/PR] Back-end Developer Pleno @ BNE - Banco Nacional de Empregos

### ISSUE THREAD

**Issue by israelaandrade** [backend-br/vagas#9794]
## Nossa empresa

Aqui no BNE a natureza é de tecnologia e inovação, somos uma empresa de tecnologia com enfoque em RH.

## Descrição da vaga

O profissional atuará na criação e manutenção de aplicações web, em projetos de alta relevância no cenário nacional.

## Local

Remoto ou semipresencial em Colombo/PR.

## Requisitos

**Obrigatórios:**
- Conhecimentos plenos C#[ ASP.NET](https://asp.net/) CORE
- Conhecimentos plenos de MVC
- SQL Server

**Desejáveis:**
- Conhecimentos em processos assíncronos
- Desenvolvimento de sistemas em nuvem (Azure)
- SCRUM
- Angular
- Identity server

**Diferenciais:**
- Quarta do CS, onde os devs se reúnem após o serviço para jogar CS e interagirem.
- Tecnologias recentes do mercado
- Oportunidades de crescimento
- Oportunidades de conhescimentos

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para: cristianenazareth@bne.com.br com seu CV anexado - enviar no assunto: Vaga Back end (GitHub) ou através de nosso Linktree: https://linktr.ee/ia_vagaserecrutamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Contato em caso de não haver resposta: 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
![Flyer no formato de Instagram (12)](https://user-images.githubusercontent.com/107878719/182422044-1a6acb8b-ffc8-4147-b1c2-d3cc42e4655a.png)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
