### ISSUE TITLE
[Remoto] Back-end Developer Java SR @ Snowman Labs

### ISSUE THREAD

**Issue by Julianagorreses** [backend-br/vagas#9795]
Nossa empresa
A Snow é uma empresa do Paraná que possui o proposito de transformar a vida das pessoas e impactar os negócios por meio de tecnologia, soluções de negócios e design. Esse é o objetivo que nos move e norteia todas as nossas ações, desde a nossa fundação em 2012.
Somos apaixonados por inovação e estamos sempre dispostos a enfrentar um bom desafio. Adoramos desenvolver aplicativos para diferentes interfaces, desde aplicativos para dispositivos móveis até aplicativos para dispositivos IoT ou até veículos autônomos, para nós a interface é um meio onde podemos entregar nossa solução💙🚀

Descrição da vaga
Projeto com cliente internacional

Local
100% remoto

Requisitos
Obrigatórios:
Domínio em diferentes Arquiteturas de Software.
Experiência com refatoração contínua.
Experiência com AWS, Firebase, etc.
Experiência na criação e manutenção de API’s.
Stack: Spring Boot, Spring Security, Spring Data JPA, Hibernate, Tomcat, Linux.
Databases: SQL Server, Postgres, MySQL, MongoDB, etc.
Experiência com testes unitários e de integração.
Inglês Fluente

Benefícios
Nossos benefícios são 💙

VR e/ou VA no valor de R$ 1.200,00 por mês 🍔 🍟 🧁
Plano de Saúde - Odontologico (Unimed/ Sulamerica) 🏥
Titulares Free, dependentes pagam apenas 50% do valor do plano
Seguro de Vida🔑
Inglês in company - para te incentivar a voar mais longe e alcançar novos desafios🚀
Auxílio Home Office de R$ 100,00🏠
Auxílio Educação de R$ 150,00📚📝
Acompanhamento Psicológico Free, para cuidar de você em todos os sentidos🥰
Plano de desenvolvimento de Carreiras - um guia para o seu crescimento profissional aqui com a gente.
Bônus por indicação no valor de R$ 1.500 reais 😍💸
Contratação
CLT ou PJ, a combinar

Como se candidatar
Por favor envie um e-mail para juliana.correa@snowmanlabs.com com seu CV anexado - enviar no assunto: Vaga Java  ou se inscreve em nosso link da gupy https://snowvagas.gupy.io/jobs/2616167

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 03 dias após cada processo.

🏢 Remoto
👴 Sênior
⚖️ A-Combinar
💰 A-Combinar

Regime
CLT
PJ

Nível
Pleno
Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
