### ISSUE TITLE
[Belo Horizonte] Back-End Developer na ABG Consultoria Estatística

### ISSUE THREAD

**Issue by fellipecouto96** [backend-br/vagas#98]
## Descrição da vaga

O objetivo desta vaga é formar um desenvolvedor Full-Stack para compor a longo prazo a equipe de desenvolvimento da ABG Consultoria Estatística.

## Local

Escritório, Belo Horizonte - Belo Horizonte

## Benefícios

Seguro contra acidentes pessoais.

## Requisitos

A vaga é destinada a estudantes que têm, mais do que interesse, uma grande VONTADE de se tornar um desenvolvedor Full-Stack. Sendo assim, o ideal é que tenha conhecimentos básicos sobre HTML, PHP, MySQL, Javascript, CSS. Caso falte algum deles, não se preocupe pois poderá aprender na prática. A principal qualidade que buscamos nos candidatos é a capacidade de aprendizado, pois a vaga se destina a formar um profissional completo.

## Contratação

Estágio

## Nossa empresa

A ABG Consultoria Estatística atua no mercado de análise de dados há 9 anos, atendendo a pesquisadores das mais diversas áreas do conhecimento e empresas de todos os ramos e portes.

Com a missão de fornecer as melhores soluções em estatística aplicada, a fim de promover desenvolvimento científico e gerar informações com confiabilidade para a tomada de decisão, tem como um de seus valores a busca constante pelo aperfeiçoamento de suas soluções. Por esse motivo, começou a trabalhar com desenvolvimento de sistemas, otimizando e agregando valor às suas soluções.

Com ambiente de trabalho diferenciado, a empresa visa o relacionamento a longo prazo não somente com os clientes, mas também com seus colaboradores que têm a oportunidade de ir crescendo junto com a empresa.

## Como se candidatar

https://app.vulpi.com.br/abg-consultoria-estat-stica/564

## Labels

- Alocado
- Estágio

**Comment by HandersonSilva** [comment]
Candidatura enviada..

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
