### ISSUE TITLE
[100% REMOTO] Back-End Developer Java (Quarkus) Pleno/Sênior na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#9810]
## Nossa empresa

A Samba está buscando uma **pessoa Desenvolvedora Backend Java (Pleno/Sênior)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **PJ e 100% remoto.** Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

Para essa oportunidade não podemos abrir mão de experiência com:

- JAVA, J2EE;
- Quarkus;
- Typescript;
- GraphQL;
- Sistemas de banco de dados relacionais, SQL e frameworks de mapeamento;
- Objeto-relacional JPA (Hibernate);
- Desenvolvimento de APIs;
- Projetos utilizando micro serviços e computação distribuída; 
- Controle de versão (Git);
- Testes unitários, de aceitação, mocks, integração, BDD.

## Local

100% Remoto, Brasil.

## Requisitos

**Diferenciais:**

- Ambientes virtualizados (Docker);
- Vivência com Quarkus; 
- Automação de deploy,
- Familiaridade com entrega contínua (Jenkins);
- Metodologias ágeis;
- AWS.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão PJ** - enviar no assunto: **Vaga Java Quarkus**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta:  **daiana.oliveira@sambatech.com.br** 

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
