### ISSUE TITLE
[100% Remoto] Back-end Developer Delphi Pleno/Sênior na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#9811]
## Nossa empresa

A Samba está buscando uma **pessoa Desenvolvedora Delphi (Pleno/Sênior)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **CLT e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

Apoiar na definição da arquitetura de software ajudando a construir o sistema, analisando e propondo melhoria nos requisitos;
Definir boas práticas mantendo-se atualizado nas novas tecnologias e compartilhando conhecimento com outros desenvolvedores;
Apoiar e orientar na elaboração de melhores estratégias de implementação e análise de correções e evoluções;
Trabalhar em parceria com outros desenvolvedores, PO’s e analistas de qualidade e gestão em busca do objetivo de evoluir e corrigir software legado.

## Local

100% Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- Domínio na linguagem Delphi;
- Sólidos conhecimentos em OOP;
- Experiência com desenvolvimento de software 3 camadas;
- Testes unitários e integrados, TDD, BDD;
- Experiência com Git e\ou GitLab;
- Experiência com os bancos de dados relacionais (Oracle / PostgreSQL) e domínio de SQL;
- Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento;
- Bons conhecimentos em Design Patterns e conceitos S.O.L.I.D;
- Conhecimento de técnicas e práticas de Clean Code.

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office;
- Auxílio home office;
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gym Pass; 
- Day off no dia do aniversário;
- Seguro de vida;
- Ways Education - Atividades extracurriculares para os filhos;
- Previdência privada.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão (CLT)** - enviar no assunto: **Vaga Delphi** 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta:  **daiana.oliveira@sambatech.com.br**

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
