### ISSUE TITLE
[100% Remoto] Fullstack Developer C# .Net (Pleno/Sênior) na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#9813]
## Nossa empresa

A Samba está buscando uma **pessoa Desenvolvedora Fullstack Pleno/Sênior (C#)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **CLT e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Local

Remoto, Brasil. 

## Requisitos

- C#
- Asp.Net Core
- API’s REST e GraphQL.
- ReactJS
- Microservices
- microfrontends
- testes unitários back e front
- testes automatizados
- Design Patterns
- Clean Code
- Mensageria
- SRE
- Kubernets.

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office;
- Auxílio home office;
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gym Pass; 
- Day off no dia do aniversário;
- Seguro de vida;
- Ways Education - Atividades extracurriculares para os filhos;
- Previdência privada.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão CLT**- enviar no assunto: **Vaga C#**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: **daiana.oliveira@sambatech.com.br**
#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
