### ISSUE TITLE
[100% Remoto] Back-end Developer Java Pleno/Sênior na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#9814]
## Nossa empresa

A Samba está buscando uma **pessoa Desenvolvedora Backend Java (Pleno/Sênior)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **CLT e 100% remoto.** Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Responsabilidades

- Realizar correções nos sistemas após a identificação das causas dos erros;
- Realizar a compilação e instalação dos sistemas, disponibilizando para o usuário;
- Valorizar a manutenibilidade do código;
- Prezar pela sustentabilidade das soluções;
- Gerar scripts de dados necessários para o correto funcionamento dos sistemas;
- Documentar e manter a documentação técnica atualizada;
- Documentar análises para escolhas tecnológicas e técnicas das melhorias entregues em novas
- versões;
- Realizar estimativas de esforço para entregas de correção e evolução de sistemas;
- Realizar simulações em ambientes de desenvolvimento e aferir nos ambientes de produção
- resultados das correções e evoluções;
- Ser corresponsável pela qualidade do produto entregue;

## Descrição da vaga

Para essa oportunidade não podemos abrir mão de experiência com:

- Domínio linguagem Java, será um destaque se conhecer versão 6 ao 13;
- Conhecimento em Spring Mvc, Spring-boot, Spring-Webflux, Spring-data, Spring-security,
- Spring-actuator, Spring-batch, Spring-boot-test;
- Hibernate e Jdbc
- J2EE: Ejb, Jsp, Struts;
- Containers Web: tomcat e jboss;
- Repositório Gitlab com CI;
- Docker, Docker compose, Kubernates;
- WebServices em Rest e Soap;
- SQL;
- Junit, Mockito e Spock;
- Experiência no desenvolvimento de serviços: REST e SOAP;
- Conhecimento em metodologias: Clean code, TDD, DDD e BDD;
- Graduação em Ciências da Computação ou áreas afins.

## Requisitos

**Diferenciais:**

Experiência com javascript, AngularJs e React;
Configuration Management (Ansible, Puppet)
Experiência com arquiteturas em microsserviços;
Metodologias ágeis: SCRUM, XP, Lean, Kanban

## Local

100% Remoto, Brasil.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão CLT** - enviar no assunto: **Vaga Java**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta:  **daiana.oliveira@sambatech.com.br** 

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
