### ISSUE TITLE
[Remoto] Analista de Testes Automatizados (QA)

### ISSUE THREAD

**Issue by TechRecruiterJu** [backend-br/vagas#9815]
Responsabilidades:
O profissional que trabalha com Análise de Qualidade é o responsável por garantir validação de requisitos de desenvolvimento, considerando os aspectos técnicos e de negócio. Deve avaliar a qualidade das aplicações e a experiência do usuário, bem como construir e automatizar testes de software, incluindo testes funcionais, performance e integração, com foco na entrega contínua. Trabalha em par com os profissionais de desenvolvimento para construção de aplicações sem gaps técnicos, ajudando os mesmos com as melhores práticas de codificação, garantindo aplicações de alta qualidade, além de auxiliar os demais membros do time em tarefas que estejam impactando a conclusão do Sprint.

Descrição da vaga
Projeto  financeiro

Local
100% remoto

Requisitos
- Experiência com GIT;
- Experiência com testes em Java;
- Experiência com Javascript;
- Experiência com Oracle/SQL;
- Experiência com PL/SQL;
- Experiência com Selenium IDE;
- Experiência com Selenium WebDriver;
- Experiência com com Testlink;
- Experiência com automação de API;
- Experiência com automação Web.

Qual pode ser o seu diferencial?
- Experiência no segmento financeiro;
- Vivência em metodologias ágeis.

Como se candidatar
Por favor envie um e-mail para techrecruiterju@gmail.com com seu CV anexado - enviar no assunto: Vaga Analista de Testes (QA)

🏢 Remoto
👴 Sênior
⚖️ A-Combinar
💰 A-Combinar

Regime
CLT
PJ

Nível
Pleno
Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
