### ISSUE TITLE
[Remoto] NodeJS Developer na WTLL

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9817]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-nodejs-165140224?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>WTLL</strong> busca<strong> </strong><strong><ins>NodeJs Developer</ins></strong> para compor seu time!</p>
<p>Somos uma empresa focada em entregar exatamente os Softwares que nossos clientes precisam para potencializar ainda mais os seus negócios.&nbsp;</p>
<p>Atuamos 100% remoto, todos como PJ e você define seu horário de trabalho!&nbsp;</p>
<p>Vamos nessa! Participe do nosso processo seletivo e faça parte da nossa equipe!</p>

## WTLL: 
 <p>Somos uma empresa focada em entregar exatamente os Softwares que nossos clientes precisam para potencializar ainda mais os seus negócios.&nbsp;</p>
<p>Para Apps, Sistemas Web, Desktop  ou basicamente qualquer demanda tecnológica que exija os melhores profissionais do Mercado, conte conosco.</p><a href='https://coodesh.com/empresas/wtll'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- Python 
- Django
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com NodeJs;

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [NodeJS Developer na WTLL](https://coodesh.com/vagas/desenvolvedor-nodejs-165140224?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
