### ISSUE TITLE
[Remoto] Backend Developer (Delphi) na Samba Tech

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9818]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-delphi-185235847?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Samba</strong> está buscando <strong><ins>Delphi Developer (Pleno/Sênior)</ins></strong> para agregar ao nosso time! <br><br>Para essa oportunidade buscamos uma pessoa para atuar em regime CLT e 100% remoto. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Apoiar na definição da arquitetura de software ajudando a construir o sistema, analisando e propondo melhoria nos requisitos;</li>
<li>Definir boas práticas mantendo-se atualizado nas novas tecnologias e compartilhando conhecimento com outros desenvolvedores;</li>
<li>Apoiar e orientar na elaboração de melhores estratégias de implementação e análise de correções e evoluções;</li>
<li>Trabalhar em parceria com outros desenvolvedores, PO’s e analistas de qualidade e gestão em busca do objetivo de evoluir e corrigir software legado.</li>
</ul>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Delphi 
- GIT 
- SQL
## Local: 
 100% Remoto
## Requisitos: 
 - Domínio na linguagem Delphi; 
- Sólidos conhecimentos em OOP; 
- Experiência com desenvolvimento de software 3 camadas; 
- Testes unitários e integrados, TDD, BDD; 
- Experiência com Git e\ou GitLab; 
- Experiência com os bancos de dados relacionais (Oracle / PostgreSQL) e domínio de SQL; 
- Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento; 
- Bons conhecimentos em Design Patterns e conceitos S.O.L.I.D; 
- Conhecimento de técnicas e práticas de Clean Code.

## Benefícios: 
 - Ambiente criativo e inovador; 
- Clima leve e descontraído; 
- Horário flexível; 
- Home office; 
- Auxílio home office; 
- Plano de Saúde; 
- Plano Odontológico; 
- Vale refeição/alimentação; 
- Gym Pass;  
- Day off no dia do aniversário; 
- Seguro de vida; 
- Ways Education - Atividades extracurriculares para os filhos; 
- Previdência privada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Developer (Delphi) na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-delphi-185235847?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
