### ISSUE TITLE
[Remoto] Desenvolvedor C++/Python @ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#9819]
## Local

100% Remoto - Horário comercial (Full time)

## Requisitos

Experiência em desenvolvimentos C++ (principal)
Conhecimentos em Python.

## Atividades

Projeto de restruturação de arquitetura de dados do projeto.

## Contratação

Contratação: 3 meses
PJ 

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora PJ - enviar no assunto: Vaga no GITHUB - C++/Python

## Labels

- Horário comercial (Full time)
- Remoto
- Pleno e Sênior
- PJ

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
