### ISSUE TITLE
[São Paulo] Back-end Developer @ Talentify.io

### ISSUE THREAD

**Issue by Mendesgabrielaa** [backend-br/vagas#9820]
## Nossa empresa

Somos uma empresa que conecta de forma inovadora os candidatos aos seus futuros empregos dos sonhos. E, além disso, preparamos os nossos clientes nessa jornada através de nossa plataforma de microlearning.

## Descrição da vaga

Reportando-se ao CTO da Talentify o profissional desenvolvedor back-end Python é responsável por atuar com a extração de dados em alinhamento com as prioridades do negócio.
Seu foco será atuar no desenvolvimento de crawlers web e na extração e normalização de dados.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento Python
- 1 anos de experiência com Arquitetura orientada a eventos
- Python - Linguagem de programação
- Scrapy/ Extração de dados
- REST API
- Kubernetes/ Docker

**Diferenciais:**
- Flask
- Selenium
- JsRender/JsViews
- Pypeter
- Marshmallow
- Banco de Dados relacional e não relacional
- RabbitMQ

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 26/dia
- VA de R$ 250/mês...

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor, envie um e-mail para rh@talentify.io com seu CV anexado - enviar no assunto: Vaga Back End Python

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriela.mendes@talentify.io

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
