### ISSUE TITLE
[Remoto] RPA Developer @ Viaflow

### ISSUE THREAD

**Issue by Viaflow-Tech** [backend-br/vagas#9821]
## Nossa empresa

APAIXONADOS POR TECNOLOGIA E INSPIRADOS PARA TRANSFORMAR!
Na Viaflow, somos um time apaixonado por tecnologia. E somos GPTW!
Isso é resultado de um time que acredita que TODOS somos responsáveis por construir um ambiente cada vez mais incrível para se trabalhar.
Aqui, nós acreditamos que empresas de sucesso se diferenciam pelos seus talentos e uso de tecnologias inovadoras. Acreditamos que as pessoas são a chave para a transformação.
Por isso, trabalhamos com muita energia, respeitamos as diferenças e estimulamos a diversidade! A nossa palavra predileta é COLABORAÇÃO.
 A Viaflow é sem fronteiras e isso também nos torna ainda mais especiais.

## Descrição da vaga

Você gosta de inovação e curte resolver problemas complexos? Nós também! Por isso, estamos em busca de profissionais inovadores e criativos, gostem de atuar em times de alta performance e busquem grandes desafios nas suas carreiras. Aqui, na Viaflow, temos um lugar especial esperando por você!

Essa oportunidade é para atuação no nosso time de projetos.

Você será o responsável pela criação propriamente dita das features priorizadas, garantindo que elas sejam feitas conforme o especificado​.

## RESPONSABILIDADES E ATRIBUIÇÕES
Automatizar de forma eficiente e flexível os processos manuais e repetitivos utilizando RPA;
Desenvolvimento na plataforma Microsoft Power Automate, Automation Anywhere e IBM RPA;
Garantir que os serviços RPA sejam entregues em alta qualidade e em tempo hábil;
Garantir que os dados do cliente sejam mantidos no mais alto nível de integridade;
Desenvolver soluções utilizando ferramentas de RPA disponíveis;
Buscar a melhoria contínua da qualidade dos processos sob sua responsabilidade;
Conhecimentos em configuração Windows: MS Office, Configuração de Rede, Permissões, Instalação de aplicações, TeamViewer;
Aplicar o framework de RPA em todas as etapas do processo utilizando a metodologia globalmente definida.
Acionar o Analista de Requisitos sempre que tiver dúvidas no que foi especificado ou encontrar comportamentos inesperados e divergências​;
Realizar testes unitários e validar com o Analista de Negócio;
Realizar, documentar e validar testes completos para posterior homologação​;
Homologar o robô desenvolvido junto ao Analista de Negócio e a área de negócio dona do robô​.

## Local

Remoto

## Requisitos

Conhecimento e experiência com Microsoft Power Automate, Automation Anywhere, Blue Prism ou IBM RPA;
Conhecimentos em: SQL, ambiente Citrix.
Experiência com automação de processos;
Experiência com lógica de programação e interação de sistemas utilizando API ou Web services.
Cursos relacionados a tecnologia;
Vivência em conceitos de robótica, softwares e linguagens de programação;
Pacote Office avançado, em especial Excel.

## INFORMAÇÕES ADICIONAIS
Ter experiência prévia no processo de desenvolvimento de sistemas (ágil ou tradicional);
Noções de controle de versão (GIT, SVN, TFS) 
Experiência prévias em soluções na área contábil, fiscal e financeira.

## Contratação

Modelo cooperativa (3%)

## Como se candidatar

Por favor cadastre na nossa página de carreiras: https://viaflow.gupy.io/job/eyJqb2JJZCI6MjM0MTIxMCwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07dias após cada processo.
E-mail para contato em caso de não haver resposta: gestaodepessoas@viaflow.com.br

#### Alocação
- Remoto

#### Regime
- Cooperativa

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
