### ISSUE TITLE
[São Paulo] Especialista em ETL @ HealthBith

### ISSUE THREAD

**Issue by jsantosrh** [backend-br/vagas#9822]
## Nossa empresa

Nosso cliente/parceiro é uma Healthtech que atende empresas e encontra soluções inteligentes que melhorem a saúde de seus colaboradores e familiares, reduzindo custos demandados com operadoras de plano de saúde, sinistralidade, afastamentos e muito mais. Suas principais especialidades são: tecnologia, análise de dados e gestão em saúde, trabalhando com grandes números (Big Data) e tecnologias escaláveis ampliando a melhoria do sistema de saúde.

## Descrição da vaga

Principais Atribuições e Atividades:

- Realizar implementação do sistema de ETL, bem como seus fluxos.
- Atuar juntamente com a equipe no desenho da arquitetura e implantação de um sistema de DW ou DL.
- Atuar na padronização de ambiente de banco de dados (DDL, DML e configurações) para a adequação para DW.

## Requisitos

- Robusta vivência em implantação de fluxos ETL.
- Experiência com arquitetura de e desenho de soluções de sistemas.
- Experiência com desenvolvimento em banco de dados.
- Experiência mínima de 03 anos nos requisitos obrigatórios.

**Desejáveis:**

- Conhecimento em ambientes Unix;
- Experiência com versionamento (GIT, SVN e afins).
- Experiência com Airflow.
- Experiência no desenvolvimento e tunning de queries.
- Vivência com Mongo DB.

## Benefícios

- Auxílio Home Office;
- Equipamento de Trabalho;
- VA;
- Plano de Saúde;
- Auxilio Saúde Mental;
- Desconto Farmácia;
- Seguro de Vida;
- Horário Flexível.

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para ksouza@acelerarh.com.br; msantos@acelerarh.com.br com seu CV anexado - enviar no assunto: Vaga - Especialista em ETL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: msantos@acelerarh.com.br

#### Alocação

- Remoto

#### Nível

- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
