### ISSUE TITLE
[Remoto] Analista M.I.S Sênior 

### ISSUE THREAD

**Issue by TechRecruiterJu** [backend-br/vagas#9825]
Responsabilidades:
Desenvolver Dashboards para as áreas da companhia;
Consumir dados de estrutura de Data Lake, BigTables, Cubos, BI e outros com a ferramenta Power BI;
Realizar Discovery e estudos de dados para produção de indicadores;
Processar rotinas para geração de relatórios, OKR's, indicadores (KPI's) e informações gerenciais;
Interagir e atender as necessidades das áreas de negócio para geração de relatórios.

Descrição da vaga
Projeto financeiro

Local
100% remoto

Requisitos

Conhecimento em Power BI avançado;
Excel Avançado;
Imprescindível conhecimento em SQL e DAX;
Desenvolvimento de querys nos principais bancos de dados do mercado;
Conhecimento na criação de KPI's com base nos OKR's.

Conhecimentos Desejáveis:
Tableau e Qlick;
Linguagem R.

Qual pode ser o seu diferencial?

Habilidade para conduzir análises sofisticadas e criativas a partir de alto volume de dados de grande complexidade;
Ser capaz de compilar e traduzir informações geradas a partir dos dados em análises e recomendações;
Capacidade de organização e priorização de tarefas.

Como se candidatar
Por favor envie um e-mail para [techrecruiterju@gmail.com](mailto:techrecruiterju@gmail.com) com seu CV anexado - enviar no assunto: Vaga Analista M.I.S Sênior

🏢 Remoto
👴 Sênior
⚖️ A-Combinar
💰 A-Combinar

Regime
CLT
PJ

Nível
Pleno
Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
