### ISSUE TITLE
[Remoto] Liderança Técnica de Desenvolvimento Sênior 

### ISSUE THREAD

**Issue by TechRecruiterJu** [backend-br/vagas#9826]
Descrição da vaga
Projeto financeiro

Local
100% remoto

Requisitos

- Redes: conhecer protocolos de rede TCP/IP, serviços de filtragem web, VPN, IPS/IDS e filtragem de pacotes (preferência iptables).
- Configurar e administrar sistemas Linux, em especial ferramentas de redes;
- Possuir conhecimento e habilidade em C e C++ e principais bibliotecas; 
- Ferramentas de Debug (exemplo: GDB, Valgrind, Address Sanityzer); 
- Básico em PHP, GO, Perl e Shell Script;
- Conhecimento e habilidade Intermediário em Bancos PostgreSQL e SQLite
- Conhecer e aplicar conceitos de versionamento no Git, incluindo branchs, tags e edição de histórico de commits.;
- Conceitos e Teorias de desenvolvimento;
- Orientação a objeto;
- Conhecimentos SOLID (diferencial);
- Desenvolvimento para alta performance (exemplo: Multi Threading e Mutex);
- Experiência com liderança.

Qual pode ser o seu diferencial?
Experiência no segmento financeiro;
Vivência em metodologias ágeis.

Como se candidatar
Por favor envie um e-mail para [techrecruiterju@gmail.com](mailto:techrecruiterju@gmail.com) com seu CV anexado - enviar no assunto: Vaga Liderança Técnica de Desenvolvimento Sênior 

🏢 Remoto
👴 Sênior
⚖️ A-Combinar
💰 A-Combinar

Regime
CLT
PJ

Nível

Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
