### ISSUE TITLE
[Remoto] Tech Lead

### ISSUE THREAD

**Issue by TechRecruiterJu** [backend-br/vagas#9827]
Responsabilidades
Terá relacionamento com área de negócio (PO/PM) no momento da chegada da demanda;
Terá responsabilidade de identificar áreas envolvidas nas histórias e fazer alinhamentos de necessidades técnicas;
Avaliação de códigos e implementação de boas práticas de desenvolvimento;
Será ponto focal do time técnico para eliminar dúvidas e/ou buscar soluções de desenvolvimento (dentro da infraestrutura instalado na companhia).

Local
100% remoto

Requisitos
- Vivência com desenvolvimento em arquitetura distribuída;
- Experiência em front-end (Angular versão JS e Typescript / React);
- Experiência em back-end (.net);
- Experiência em arquitetura de micro-front-end;
- Conhecimento/conceito BFF;
- Conceito de BPM;
- Conhecimento de Devops (acompanhamento de pipeline);
- Conhecimento em cloud (Azure);
- Conhecimento na Metodologia Ágil (Scrum).

Como se candidatar
Por favor envie um e-mail para [techrecruiterju@gmail.com](mailto:techrecruiterju@gmail.com) com seu CV anexado - enviar no assunto: Vaga Tech lead

🏢 Remoto
👴 Sênior
⚖️ A-Combinar
💰 A-Combinar

Regime
CLT
PJ

Nível
Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
