### ISSUE TITLE
[Software Engineer Fullstack with English] - Remoto - PJ - USD 5 K - USD 6 K - Brazil Residents.

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9833]
[Software Engineer Fullstack with English] - Remoto - PJ - USD 5 K - USD 6 K - Brazil Residents.
 
RESPONSIBILITIES 
 Strategically define, design, implement, deliver and operate software applications 
 Apply best practices of synchronous and asynchronous communication to work effectively  across functional teams. Utilize documentations, video recordings of demos and bug  replications, JIRA, confluence, postmortems, retrospectives to continuously improve  asynchronous collaboration. 
 Work closely with business stakeholders and product managers to provide technical solutions,  tradeoffs and, insights to design best software system for the long term 
 Incorporate tool automation and automated testing so that future releases can be more  confidently and easily deployable 
 Collaborate with engineers and grow them by pairing, code reviewing and teaching latest and  greatest techniques 
 Facilitate domain driven design and implementation of well abstracted services that are easily  testable via tools like Pact 
 Refactor existing systems and APIs to provide best user experience to customers, developers  and stakeholders. 
 Assist product manager in breaking down epics to executable stories and further subtasking  them for incremental agile delivery. 
 Ability to distill problem definitions, models, and constraints from informal business  requirements, and to deal with ambiguity and competing objectives 
 
QUALIFICATIONS 
 You love to code and care about automation, testability, extensibility and maintainability so that  you can please other engineers in the future 
 You are very detail oriented problem solver that knows how to clearly break down into smaller  problems and able to execute in an iterative manner 
 You are skilled at planning your day and week with minimal oversight and love to get things  done 
 You are experienced with at least one modern language such as Typescript, Javascript, Python,  Go, Java, Scala, Kotlin and use functional or object-oriented design to clearly abstract  components and contracts between systems to minimize unexpected side effects 
 You have contributed 1+ years in the architecture and design (architecture, design patterns,  reliability and scaling) of new and existing systems 
 You have 2+ years of experience building successful production software systems with good  monitoring and alerting in AWS or similar cloud environments 
 You have 3+ years of experience building in full SDLC, refactoring services and supporting production software with continuous end user feedback 
 You are obsessed with customer happiness and usability and have experience working with cross functional teams (e.g. business stakeholder, product manager, marketing, sales, customer support) in agile environments and comfortable giving specific feedback to others to improve 
 You have understanding of Computer Science fundamentals, such as Algorithms, Data Structures, Design Patterns, and Databases. 
PREFERRED QUALIFICATIONS 
 You have owned design, development, operations and handing off of highly scalable software services and systems 
 You have bachelor's degree in Computer Science or similar technical field 
 You have experience refactoring and rearchitecting large-scale multi-tiered systems and serviceoriented architecture 
 You have experience with infrastructure automation using tools such as Ansible, Terraform, Cloudformation, Crossplane or equivalent 
 You have experience in creating reusable libraries and packaging modules for other engineers to reuse 
 You have experience with a range of data manipulation (image, structured, unstructured, audio, video), ETL pipelines and ML technologies in ML frameworks 
 You have experience building secure applications with threat modeling, load testing, WAF protection or cryptography 
 
ABOUT US:
"The company is a world-class destination for leading designer brands at an extraordinary value. The company combines the two great joys of shopping: the pleasure of discovering the best in luxury and the thrill of finding a bargain. Designer trends, Exceptional service and savings with the biggest names in fashion, we lead the market as the premier luxury value destination. The company's unique approach combines a focus on the digital customer experience with a strong connection to a network of extraordinary stores that span this seamless experience for the real world. We are currently in the midst 
of a dramatic expansion, driven by significant improvements to our platformsand offerings, with the goal of becoming the pre-eminent luxury destination internationally. 
We want to make the Company your favorite place to work and shop. We are looking for experienced full stack software engineers at all levels (3-20 years experience) for mobile app development, backend enterprise APIs, personalization, loyalty programs, in-store apps, infrastructure automation, service integrations third-party instrumentation, observability, and engineering operations optimizations. 
If you're excited to apply best practices in software engineering to create elegant user experiences, reusable libraries, scalable software architecture, streamlined integrations with third-party APIs, and highperformance data-driven systems in the AWS cloud, the opportunity is here. . You can help shorten software development cycle time through test-driven development, automated testing, and CI/CD pipelines. If you are comfortable and excited to increase your subject matter expertise and development experiences in different programming languages: Typescript, Javascript, Python, Go; and frameworks: 
Svelte, React, Native Script, Fast API, AWS API Gateway, Serverless; and storage systems: Elastic Search, SQL databases, Kafka, Snowflake you can come and unleash your technical superpowers. 
The successful candidate will have an established track record in developing scalable systems, a solid technical background, great communication skills and a drive to achieve results."

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
