### ISSUE TITLE
[Software Engineer with English] - Remoto - PJ - USD 5 K - USD 6 K - Brazil Residents. 

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9834]
[Software Engineer with English] - Remoto - PJ - USD 5 K - USD 6 K - Brazil Residents. 
  
RESPONSIBILITIES  
The company is looking for an experienced software developer who will be responsible for implementing the front end for our award-winning cloud and on-premises monitoring application. They will architect and design components and features of products large and small. They will write code that queries a variety of data stores and presents them in a visually appealing application. The ideal candidate is an experienced developer who also has an understanding of the building blocks of IT infrastructures. What you will do: 
 
•	Implement new features, bug fixes and required maintenance Netreo's Omnicenter network and infrastructure monitoring platform, in particular the SaaS version of our product 
•	Create new features and work on refactoring and improving existing features and appearance 
•	Help design and build the next generation of Netreo apps and UI 
•	Work with engineering and product management leadership on the roadmap 
•	Work with a team of other developers 
•	Adhere to organizational standards for security, performance, and automated testing • 	 Determine and follow best practices and standards 
 
Experience and Skills  
•	Bachelor's in Computer Science or equivalent  
•	Expert in a Linux development environment  
•	Strong experience with PHP  
•	Experience with backend technologies: .net, perl, python  
•	Experience working with UX concepts and designing user friendly UIs  
•	Experience with databases (MySQL, NoSQL, Influx DB, MongoDB, etc)  
•	Experience working with remote geographically distributed teams  • 	 Experience leading and mentoring small teams of developers  
 
Nice to have:  
•	Experience working with REST APIs  
•	Experience with PHP frameworks (Yii, Laravel, etc)  
•	Experience with both backend and front end development (full stack engineering) with mix of technologies:  
•	PHP, Python, Java, golang, .net  • Various RDBs and NoSQL technologies  • Experience with cloud technologies:  
•	AWS, Azure, GCP  
•	EC2, S3, API gateway, server-less computing  
•	Strong sense of ownership, urgency, and drive  
•	Experience with monitoring products and standards:  
•	Cloud APIs (cloudwatch, Azure graph API etc.)  
•	IT Vendor monitoring APIs and SDKs  
•	Powershell and/or WMI  
•	SNMP 
 
ABOUT US: 
Today’s IT organizations are faced with the challenge of integrating new technology into their infrastructure while continuing to support all of their legacy needs. Business technology stacks have become more complex, diverse, and difficult to control than ever before. The Company  Infrastructure Monitoring Platform, provides a platform that gives organizations a unified, single source of truth view into their entire IT infrastructure — regardless of size, footprint or complexity.  
Company is trusted worldwide by thousands of private and public entities, and manages half a billion technology resources per day. From launching rockets into space to saving lives, helping assure financial futures to feeding millions … their 1,400 customers in 60 countries are making an impact across key industries.  
On top of that company  is one of Inc. 5000’s fastest-growing companies. In addition to receiving leading reviews at Gartner Peer Insights, Capterra and G2 for sterling offerings and service, we have also received The Startup Weekly’s 2021 “Exceptional Workplace” Award."

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
