### ISSUE TITLE
[REMOTO] Back-end Developer Sênior | Pacifica Continental

### ISSUE THREAD

**Issue by leticiaamf7** [backend-br/vagas#9835]
## Nossa empresa 🌎

Pacifica Continental é uma empresa de recrutamento global especializada em cargos estratégicos, tais como membros da diretoria, c-suites, gerentes superiores e intermediários. Nossas soluções personalizadas e abordagem consultiva garantem a seleção dos melhores talentos do mercado.

Nossas operações alcançaram mais de 50 países, incluindo mais de 250 cidades ao redor do mundo. Orgulhamo-nos de trabalhar com precisão e conhecimento em uma ampla gama de indústrias. Sempre comprometidos com a obtenção de uma visão industrial contínua, fazemos parcerias com um grande número de empresas multinacionais e locais.
Desenvolvendo uma forte interface entre nossas operações, entregamos soluções globais com uma abordagem local.

## Local 📍

Remoto.

## Responsabilidades e Atribuições 💻

-  Garantir a entrega bem-sucedida de projetos e promover a saúde técnica de longo prazo de nossos serviços;

- Projetar, desenvolver, testar, implantar, manter e melhorar serviços com foco em desempenho, escalabilidade e estabilidade;

- Faça parceria com produtos e design para criar experiências altamente responsivas, intuitivas e elegantes que irão encantar os clientes e definir um padrão alto para todos os aplicativos da Web;

- Apoiar os sistemas existentes que buscam aprimorar a funcionalidade, aumentar a escala e transformar em novas maneiras de atender às demandas de nossos produtos;

- Criar novos serviços e recursos para atender às necessidades emergentes à medida que nossos negócios crescem;

- Seja mentor (a) para outras pessoas desenvolvedoras.

## Requisitos ✅

- 5 anos + de experiência como engenheira de software;

- Experiência em arquitetura de microsserviços, design orientado a domínio e APIs RESTful usando linguagens como Node, Java ou Python;

- Profunda experiência técnica com bancos de dados relacionais e não relacionais;

- Excelentes habilidades analíticas, de resolução de problemas e pensamento crítico;

- Experiência com infraestrutura (AWS) e monitoramento de aplicativos;

- Compreensão profunda das compensações de desempenho do sistema, balanceamento de carga e engenharia para alta disponibilidade ;

- Forte experiência com integrações de sistemas ;

- Experiência com arquitetura orientada a eventos (sqs, sns, kafka)

**Considerado um Plus**✨

- Familiaridade com padrões de acesso a dados CQRS;

- Experiência em nosso Tech Stack em geral (typescript, node, nest, python);

- Experiência em pagamentos.

## Contratação

PJ a combinar

## Como se candidatar✔

Se identificou com a vaga? Você pode se inscrever aqui pelo link: https://recruitcrm.io/apply/16599749409070019299xis
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

Em caso de dúvidas, ou demora no retorno durante o processo é possível contato via linkedin no perfil: 
https://www.linkedin.com/in/paloma-cavalcante-batista-gomes-46415241/

#### Regime
- CLT.
- PJ à negociar.

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
