### ISSUE TITLE
[Remoto] Backend (Golang) Developer na Mobiplus

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9838]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-golang-senior-pj-125645251?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Mobiplus</strong> busca <strong><ins>Backend (Golang) Developer</ins></strong> para compor seu time!</p>
<p></p>
<p>A Mobiplus nasce em 2017 com uma ideia bem clara: prestar serviços de alta qualidade para viabilizar a montagem de um TIME de alta performance e, em um segundo momento, gerar resultados importantes para todos os envolvidos na empreitada, com produtização de serviços e desenvolvimento de produtos (SaaS).</p>
<p>Estamos em busca constante por profissionais apaixonados pelo que fazem, que gostem de trabalhar em equipe, que buscam soluções para qualquer desafio ou problema independente da tecnologia utilizada, e, principalmente, que se encaixem na nossa cultura e que queiram grandes conquistas, mas sem sacrificar a vida pessoal para isso. O perfil técnico ideal é aquele que consegue balancear as necessidades técnicas com as necessidades de negócio em cada momento do ciclo de vida de um produto.</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Atuar no time de desenvolvimento nos serviços da Afya, com foco no backend, auxiliando na evolução do produto e sempre que possível atuando como um orientador de boas práticas de desenvolvimento de software e de produto (mesmo não sendo um líder nomeado). Ajudar o time cada vez mais a ter proximidade com a área de negócios/produto e ter mentalidade de Product Developers.</li>
</ul>

## Mobiplus: 
 <p>A Mobiplus nasce em 2017 com uma ideia bem clara: prestar serviço de alta qualidade para viabilizar a montagem de um TIME de alta performance e, em um segundo momento, gerar resultados importantes para todos os envolvidos na empreitada, com produtização de serviços e desenvolvimento de produtos (SaaS).</p><p>Nosso caminho passa por: Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p><a href='https://coodesh.com/empresas/mobiplus'>Veja mais no site</a>

 ## Habilidades: 
 - GoLang 
- AWS 
- Docker 
- Node.js 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Golang, com noções de javascript e/ou python; 
- Conhecimento em ApiRest;
## Diferenciais: 
 - Conhecimento em Docker e Kubernets; 
- Experiência com a criação de microserviços; 
- Conhecimento em Node; 
- Conhecimentos em CI/CD.
## Benefícios: 
 - Descanso remunerado de 20 dias; 
- Trabalho 100% remoto (nascemos 100% remotos já em 2017); 
- Ambiente 100% propício para aprendizado constante e inovação; 
- Horário flexível (limitações de janela de horário dependendo do contexto/cliente); 
-  Possibilidade de recesso de final de ano remunerado; 
- Todas as semanas temos nosso Just Talk, onde trazemos convidados de fora para compartilharem suas experiências conosco, batemos papo sobre assuntos diversos no clube do podcast e brincamos também no final do dia.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend (Golang) Developer na Mobiplus](https://coodesh.com/vagas/pessoa-desenvolvedora-golang-senior-pj-125645251?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
