### ISSUE TITLE
[Analista Desenvolvedor .Net Full Framework (inglês fluente escrito e falado)] - Remoto - PJ - R$ 15 K Pleno e R$ 20 K Sênior.

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9839]
[Analista Desenvolvedor .Net Full Framework (inglês fluente escrito e falado)] - Remoto - PJ - R$ 15 K Pleno e R$ 20 K Sênior.
Descrição da vaga:
Tecnologia, motivação, espírito de equipe e resultados!
Se você se identifica com essas características, venha trabalhar com a gente!
Somos Great Place to Work, um reconhecimento oferecido pelo Instituto GPTW para empresas que se destacam pelas boas práticas no ambiente de trabalho.
Buscamos pessoas com vontade e disponibilidade para trabalhar em um ambiente sem fronteiras para atuação home office no exterior!
Junte-se a nós para fazer a diferença!

Responsabilidades e atribuições:
English fluency required (verbal and written). Must be able to conduct regular meetings with the client, in English.
Work with System integrations using SOAP and API
Coding and developing applications in SQL and .Net
Providing day-to-day application support and maintenance of Internal and external Systems and integrations with IMS System
Resolve escalated application bugs and issues on Production Enviroment
Requisitos e qualificações:
+3 years of professional programming experience developing applications using C# and other .NET technologies, including VSTO, ASP.NET MVC, ASP.NET Web Services using software design patterns and DDD
SQL Server technologies, SSRS and SSIS and SQL optimization and SQL Server performance tuning
Experience of systems integration, web service and ETL development
Experience with continuous integration frameworks and processes, test-driven development (TDD) and automated testing environments
If you have our match it will be even bigger!
Experience with workflow-based applications
Adaptive to change and feedback from team members
Working knowledge of accounting and reporting principles in the Private Equity area
Demonstrated experience configuring and supporting FIS Investran solutions
Strong knowledge of the Investran data model, Accounting and reporting hierarchies, transaction types, batch templates, Active Templates, Allocation Rules, Data Import Utility, and Report Wizard
Working knowledge of the Investran SDK and API
Strong analytical and technical skills to carry out detailed technical work (development and support)
Demonstrated team player, self-starter, and independent thinker with good communication and team collaboration skills.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
