### ISSUE TITLE
[DevOps Senior with English] - Remote - Brazil Residents

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9840]
[DevOps Senior with English] - Remote - Brazil Residents - Recibos verdes or CTI. Euro 2.500,00,00 - Euro 3.200,00 net salary (líquido) negotiable. 

OBS: Ter disponibilidade para trabalhar no fuso horário de Portugal, participando das Dailys as 6:00h BR. O inglês avançado para conversação e listening muito bons é imprescindível já que vai lidar com cliente de outro país.

Company
Software Consulting founded with the mission to inspire the connection of
technology with people, fostering the best of our professionals through our
expertise in finding and attracting the best talent for the best projects.

What You’ll do:
● You will support the company services before they go live through
system design consulting, developing software platforms and
frameworks, and capacity planning.
● You will build and manage the cloud server infrastructure for
development and production environments in a state-of-the-art
technology (e.g., using Kubernetes).
● You are responsible for the planning and successful implementation of
new technology.
Experience and Skill Requirements
● You have already worked as a DevOps Engineer and/or SRE for at least 3
years, ideally in an agile dev environment.
● You are familiar with continuous integration & deployment tools and
techniques (we are working with Jenkins).
● You have worked with Docker, Kubernetes and virtual machines (VMware,
VirtualBox).
● You know your way around cloud-based deployments like AWS and
Google Cloud as well as configuration management systems (Chef,
Puppet, Terraform).
You are familiar with Linux, Scrum and Agile methodologies. Furthermore,
you possess good knowledge on Shell scripting, Python and Go.
● You stand out for your proven pro-activeness in previous projects, your
eagerness to learn and share your knowledge as well as for your
goal-driven mindset.
● Languages: EN.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
