### ISSUE TITLE
[São Paulo - Remote] Back-End Developer Sênior @ FASTER

### ISSUE THREAD

**Issue by PaivaT** [backend-br/vagas#9842]
## Nossa empresa

A Faster é uma startup de tecnologia que escala operações criativas dos melhores times de marketing do Brasil. Somos o parceiro de escolha de startups e scale-ups incríveis como Nubank, Descomplica, Hotmart, Petlove e iFood, além de empresas globais como Ambev, WarnerBros e SAP.
 
Somos investidos por uma das principais gestoras de venture capital do país, além dos fundadores de startups como Alura e Descomplica e executivos de grandes empresas como Adobe, Google, NotCo e Botmaker.
 
Nossa missão é criar o maior ecossistema de serviços criativos da América Latina e agora precisamos de você para nos ajudar a alcançar esse objetivo. Se você quer fazer parte dessa revolução, essa vaga é pra você!

## Descrição da vaga

- Conduzir o design e arquitetura das APIs e modelagem do banco de dados, considerando eventuais evoluções ao longo do tempo de vida do projeto;
- Saber interpretar os problemas dos usuários e propor/discutir soluções junto à equipe;
- Propor arquitetura future-proof e que seja de simples manutenção;
- Fomentar boas práticas de desenvolvimento (testes unitários, padrões de projetos, etc);
- Cultivar relações com os outros times e o seu próprio no intuito de buscar a melhor forma de entregar o melhor resultado para problemas específicos que a Plataforma Faster tem;
- Ser auto-gerenciável e proativo;

## Local

Full Remote ; 100% remoto ; remoto ; home office

## Requisitos

**Obrigatórios:**

- NodeJS
- APIs com AdonisJS
- Gerenciamento de DB com Lucid
- Monitoramento com Sentry
- AWS
- GitFlow com Github

**Desejáveis:**
- MongoDB ou algum outro não-relacional
- Outros frameworks de NodeJS

## Benefícios

- PJ + Descanso remunerado de 30 dias.
- Plano de Saúde Allianz (sem desconto ou coparticipação)
- Alura 
- Allya 
- Best Off
- 6 meses gratuitos na Bodytech
- 20% de desconto em cursos da Descomplica
- Dayoff de aniversário
**O plano de saúde é estendível de forma 100% gratuita para filhos(as) e enteados(as).

**Diferenciais:**
- Flexibilidade
- Autonomia
- Trabalhar em um projeto pioneiro e uma plataforma inovadora
- Equipe Sênior 
- Processos Flexíveis

## Contratação

PJ + benefícios

## Como se candidatar

E-mail: thiago.paiva@fstr.co
WhatsApp - 11964514391
LinkedIn - https://www.linkedin.com/in/thiago-oli-paiva/

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
