### ISSUE TITLE
[REMOTO] Back-end Developer @ Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [backend-br/vagas#9843]
## Nossa empresa

Somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial no Brasil da plataforma ArcGIS, da norte-americana Esri.

Há mais de 30 anos ajudamos nossos clientes a visualizar, questionar, analisar e interpretar atributos dos dados através de apps, funcionalidades, dashboards e mapas.

Certificados pelo GPTW como um “Excelente Lugar para Trabalhar”.
Conheça mais sobre nossa empresa em: https://www.img.com.br/pt-br/home

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Superior Completo nas áreas de tecnologia, desenvolvimento ou afins;
- Python;
- Javascript / Typescript;
- ASP.NET.

**Habilidades e experiências:**
- Implementação de pequenos projetos utilizando como base a plataforma ESRI;
- Desenvolver novas ferramentas e serviços para integração dos produtos ESRI com outros sistemas (ERP,CRM e ETC), utilizando metodologia ágil e clean code;
- Desenvolvimento WEB e Desktop (Back-End e Front-End);
- Utilização de RestFul API´s;
- Manipulação de banco de dados (Oracle, PostgreSQL, SQL server);
- Conhecimento das ferramentas de controle de versão de código;
- Participar de estimativas de requisitos.
- 
**Diferenciais:**
- Conhecimento GIS e da plataforma ArcGIS;
- Noções de arquitetura de aplicações para ambiente Web, Desktop e Mobile.

## Benefícios

-  Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade;
- Vale alimentação ou refeição;
- Plano de Saúde;
- Assistência Odontológica;
- Seguro de Vida;
- Auxílio Home Office;
- Salário compatível com o mercado e vários benefícios.

## Contratação

A combinar

## Como se candidatar

Envie seu currículo atualizado e sua pretensão salarial para o email: recrutamento@img.com.br com o assunto: Desenvolvedor 1188

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
