### ISSUE TITLE
[Cidade] Back-end Developer @VEGA

### ISSUE THREAD

**Issue by luanasantosog** [backend-br/vagas#9844]
## Nossa empresa

A VEGA, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.
Conheça mais sobre a empresa em: https://vegamonitoramento.com.br/

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento utilizando C# .NET Core (ou .NET Framework); ORM (preferencialmente Entity Framework); Web services (preferencialmente em REST); repositório de arquivos (preferencialmente Git).

**Desejáveis:**
- Conhecimento em banco de dados (preferencialmente PostgreSQL);
- Conhecimento em metodologias ágeis;
- Experiência em framework Javascript (preferencialmente React JS).

## Benefícios

- Nossas posições são 100% REMOTAS ou HÍBRIDAS caso sua região seja próxima a nossa Sede (São José dos Campos) ou nossos Hubs (Lavras e Piracicaba);
- Vale Alimentação ou Vale Refeição pelo cartão Alelo, você pode escolher a opção que mais combina com você;
- Plano de Saúde Sul América ou Unimed - sem custos para o colaborador e com a possibilidade de incluir dependentes;
- Seguro de Vida Individual - sem custos para o colaborador;
- Plano Odontológico Sul América com valores diferenciados do mercado;
- Day Off e Voucher Ifood no mês do seu aniversário;
- Flexibilidade de Horário de até 1 hora na sua jornada;
- 1 hora por semana para se dedicar aos seus estudos (cursos/especializações/idiomas);
- Licença Paternidade estendida de 15 dias;
- Programas e Trilhas para o seu Desenvolvimento;
- Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade.

## Contratação

A combinar

## Como se candidatar

Por favor seu currículo atualizado e sua pretensão salarial para o email recrutamento@img.com.br E - enviar no assunto: Back-end Developer VEGA

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
