### ISSUE TITLE
[São Paulo] 👩‍💻Especialista em Fluttler - Mobile📱 👨‍💻 na Youse Seguros 💜

### ISSUE THREAD

**Issue by priscilarame** [backend-br/vagas#9845]
## Nossa empresa

A Youse nasceu pra revolucionar o mercado de seguros, oferecendo proteção com tecnologia e simplicidade, dando autonomia a todos os nossos clientes e facilidade/agilidade na escolha dos nossos produtos. Eles podem montar seu seguro de acordo com sua necessidade, do seu jeito, no seu tempo e na palma da mão! 

💜 O jeito Youser de ser! 

Nossos Yousers têm todo um jeitinho de ser. Isso é superimportante pra gente conseguir cada vez mais transformar o mercado de seguros e melhorar a experiência com os nossos clientes, que são nosso ponto de partida. Por ser uma empresa tech, a galera aqui ama inovar, pensar diferente, sabe? Estamos sempre testando, aprendendo e evoluindo, com a tecnologia como nosso principal pilar.  

Pra tudo isso acontecer, a gente precisa de pessoas que tenham uma pegada de igual pra igual! Aqui, a gente preza pela igualdade de oportunidade e inclusão da diversidade. Isso se traduz em gênero e identidade de gênero, religião, PCDs, LGBTQIA+, raça/etnia e idade, pois acreditamos que é muito valioso para nossa cultura compartilhar ideias e pontos de vista diferentes. 🏳️‍🌈♿✊🏿

👀 O que esperar no ambiente de trabalho na Youse? 

Ambiente aberto a todo tipo de diversidade;
Vc tem liberdade de ser quem vc é, sem essa de dress code;
O papo é reto e de igual pra igual;
Pelo menos uma vez por mês a gente traz convidados ou encoraja os próprios Yousers a apresentarem temas como: diversidade, inovação e empreendedorismo.

## Descrição da vaga

Se vc trabalha com Flutter, tem vontade de aprimorar um aplicativo ambientado em uma cultura de inovação e, de quebra, ainda impactar milhares de pessoas no seu dia a dia? Se sim, é vc que queremos pra compor nosso time de Mobile Software Engineers!

## Local

- Modelo Híbrido;
- O escritório fica aqui: WTorre - Av. das Nações Unidas, 7815 - Pinheiros, São Paulo;
- 4 minutos andando da estação de Pinheiros.

## Requisitos

**Obrigatórios:**

- Ter atuado em projetos com Flutter;
- Sólidos conhecimentos em princípios de programação como SOLID e no paradigma OOP (programação orientada a objetos);
- Conhecimentos de arquitetura no padrão Clean Architecture;
- Conhecimentos em testes unitários e testes de integração;
- Conhecimento em CI/CD;
- Interesse em sempre aprender novas tecnologias e sair da zona de conforto.

**Diferenciais:**

- Conhecimento no desenvolvimento nativo em iOS/Swift ou Android/Kotlin;
- Conhecimento em gerenciamento de estado no padrão BLoC;
- Experiência no lançamento de releases por meio das lojas de aplicativos (Google Play/App Store);
- Experiência em plataformas e ferramentas de CI/CD (Fastlane, Bitrise);
- Experiência em soluções do Firebase.

#### Nível
- Sênior
- Especialista

## Benefícios

- Carga horária semanal de 37,5h;
- PLR;
- Assistência médica (SulAmerica);
- Assistência odontológica;
- Vale refeição;
- Vale alimentação;
- Vale transporte (caso precise);
- Auxílio creche/babá;
- Auxílio home-office;
- Auxílio farmácia;
- Seguro de vida;
- Seguro residencial;
- Desconto seguro auto (30%)
- Licença parental estendida;
- Previdência privada;
- Reembolso bem-estar (Academia)

## Contratação

CLT

## Como se candidatar

[Kenoby - Especialista em Fluttler](https://jobs.kenoby.com/vagas-youse/job/pessoa-desenvolvedora-especialista-em-flutter/62ab465c4be96769250bfeca?utm_source=website)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias úteis;
Caso de não houver resposta só mandar um e-mail para: leticia.jesus@youse.com.br ou priscila.mendes@youse.com.br

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois o link de candidatura não está mais disponível ou não está mais aceitando candidaturas.
