### ISSUE TITLE
[Híbrido - São Paulo] Development Analyst - Dev Ruby na Youse Seguros💜

### ISSUE THREAD

**Issue by priscilarame** [backend-br/vagas#9846]
## Nossa empresa

A Youse nasceu pra revolucionar o mercado de seguros, oferecendo proteção com tecnologia e simplicidade, dando autonomia a todos os nossos clientes e facilidade/agilidade na escolha dos nossos produtos. Eles podem montar seu seguro de acordo com sua necessidade, do seu jeito, no seu tempo e na palma da mão!

💜 O jeito Youser de ser!

Nossos Yousers têm todo um jeitinho de ser. Isso é superimportante pra gente conseguir cada vez mais transformar o mercado de seguros e melhorar a experiência com os nossos clientes, que são nosso ponto de partida. Por ser uma empresa tech, a galera aqui ama inovar, pensar diferente, sabe? Estamos sempre testando, aprendendo e evoluindo, com a tecnologia como nosso principal pilar.

Pra tudo isso acontecer, a gente precisa de pessoas que tenham uma pegada de igual pra igual! Aqui, a gente preza pela igualdade de oportunidade e inclusão da diversidade. Isso se traduz em gênero e identidade de gênero, religião, PCDs, LGBTQIA+, raça/etnia e idade, pois acreditamos que é muito valioso para nossa cultura compartilhar ideias e pontos de vista diferentes. 🏳️‍🌈♿✊🏿

👀 O que esperar no ambiente de trabalho na Youse?

Ambiente aberto a todo tipo de diversidade;
Vc tem liberdade de ser quem vc é, sem essa de dress code;
O papo é reto e de igual pra igual;
Pelo menos uma vez por mês a gente traz convidados ou encoraja os próprios Yousers a apresentarem temas como: diversidade, inovação e empreendedorismo.

## Descrição da vaga

Vc já atua com desenvolvimento de software, manja de Ruby e é bom em Rails, PostgreSQL, RabbitMQ? Conhece microsserviços? Tem paixão por TDD? 

Tem vontade de impactar milhares de pessoas no seu dia a dia, desenhando, construindo e mantendo o código eficiente e escalável, e ainda por cima tem preocupação com sua performance? 💻⚡

Então se liga porque estamos buscando uma pessoa desenvolvedora como vc!

## Local

- Modelo Híbrido;
- O escritório fica aqui: WTorre - Av. das Nações Unidas, 7815 - Pinheiros, São Paulo;
- 4 minutos a pé da estação de Pinheiros.

## Requisitos

- Conhecer/ter atuado com ruby on rails;
- Rspect, postgreSQL, RabbitMQ são importantes;
- Ter arquitetura voltada a eventos; 
- Ter noção de arquitetura web;
- Preocupação em performance e em código escalável;
- Noção de testes unitários e de integração;
- Conhecer github/GIT; 
- Realizar pair programming e code review são interessantes.

#### Nível

- Pleno
- Sênior

## Benefícios

- Vale-refeição;
- Vale-alimentação (temos 13º do VA!); 
- Plano de Saúde (sem desconto. Dependentes também entram no plano sem custo algum);
- Plano Odontológico (sem desconto. Dependentes também entram no plano sem custo algum);
- PLR;
- Vale-transporte ou fretado para quem reside acima de 25 km do escritório;
- Seguro de Vida; 
- Convênio farmácia;
- Auxílio academia;
- Previdência privada;
- Licença maternidade de 6 meses e paternidade de 30 dias; 
- Auxílio-creche/babá para crianças de até 05 anos e 11 meses;
- Auxílio home office;
- Jornada de trabalho de 7h30/dia;
- Modelo de trabalho: híbrido.

## Contratação

CLT

## Como se candidatar

[Kenoby - Analista de Desenvolvimento - Dev Ruby](https://jobs.kenoby.com/vagas-youse/job/analista-de-desenvolvimento-pleno-dev-ruby/62c71fd32663e1140f379099?utm_source=website)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias úteis;
Caso de não houver resposta só mandar um e-mail para: [leticia.jesus@youse.com.br](mailto:leticia.jesus@youse.com.br) ou [priscila.mendes@youse.com.br](mailto:priscila.mendes@youse.com.br)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.

**Comment by priscilarame** [comment]
Obrigada, Gustavo!

*Priscila Racolto Mendes*

Recursos Humanos

Atração & Seleção


c (11) 95033-8639

***@***.*** ***@***.***>*

youse.com.br


Em ter., 27 de set. de 2022 às 09:11, Gustavo Freze <
***@***.***> escreveu:
