### ISSUE TITLE
[Híbrido - Lorena] Engenheiro de Dados @KAAD

### ISSUE THREAD

**Issue by marianabompean** [backend-br/vagas#9847]
* Engenheiro de Dados (Pleno/Sênior)
* Experiência com: Modelagem de dados, SQL.
* conhecimentos com ERP SAP.

Contratação: CLT
Atuação hibrida - 1x ao mês em Lorena
Tempo de projeto: inicialmente 6 meses com grande possibilidade de extensão.

Segue email:
mariana.nunes@kaad.com.br
Venham nos conhecer e se tornar parte de nossa equipe.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
