### ISSUE TITLE
[Remoto] .NET FullStack Developer @ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#9849]
## Local

100% Remoto 
Full time em horário comercial

## Requisitos

Experiência em C#, Asp.Net, API Rest, GrapgQL, React.Js, Microserviços, Microfrontends, testes unitários BackEnd e FrontEnd, testes automatizados, Design Patterns, Clean Code.
Experiência em times ágeis.

## Desejável

SRE e Kubernetes.

## Contratação

Tempo indeterminado
CLT + benefícios (Não aceita PJ)

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão salarial CLT - enviar no assunto: Vaga no GITHUB - FullStack .NET CLT

## Labels

- Horário comercial (Full time)
- Remoto
- Sênior
- CLT

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
