### ISSUE TITLE
[Híbrido/Joinville] Back-end Developer Júnior @ JetBov

### ISSUE THREAD

**Issue by barbarameurer** [backend-br/vagas#9860]
## Nossa empresa

A JetBov é uma Startup que está transformando a pecuária de corte no mundo. Usamos a tecnologia de inteligência artificial e armazenamento de dados com o objetivo de digitalizar a cadeia produtiva da bovinocultura de corte. Nosso propósito é empoderar o(a) pecuarista, através de informação e oportunidades, agregando maior valor a cadeia de forma sustentável.

Quer saber como é ser um JetBover? Acesse o link:

https://jobs.quickin.io/jetbov

## Descrição da vaga

A equipe de engenharia na Jetbov tem papel importante na construção dos produtos planejados. Nossa equipe é multidisciplinar e composta por profissionais de qualidade que trabalham como um time forte o tempo todo, e você fará parte deste time fantástico trazendo seu conhecimento e crescendo junto com todos.

As suas responsabilidades serão:

- Desenvolvimento de APIs utilizando Python 3 e FastAPI;
- Manutenção de código já existente em Python 2 e 3;
- Desenvolvimento de querys de banco de dados que tenham boa performance;
- Realizar versionamento de código (Git);
- Participar ativamente de uma equipe usando processo de desenvolvimento Ágil.

## Local

- Híbrido em Joinville - SC

## Requisitos

**Obrigatórios:**
- Boa Lógica de programação;
- Python.

**Diferenciais:**

- Conhecimento em arquitetura de software;
- Django;
- FastAPI.

## Benefícios

- Plano de saúde com cobertura nacional, sem co-participação;
- Vale refeição ou alimentação;
- Benefício Flexível;
- Auxílio Equipamento.

## Contratação

CLT.

## Como se candidatar

Envie um e-mail para talentos@jetbov.com ou cadastra-se no site https://jobs.quickin.io/jetbov/jobs/62cc4f102d1b1f001becb806

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Híbrido

#### Regime
- CLT

#### Nível
- Júnior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
