### ISSUE TITLE
[São Paulo] Back-End Developer @ Cuco Health

### ISSUE THREAD

**Issue by tiagords** [backend-br/vagas#9863]
## Cuco Health

A [Cuco Health](https://cucohealth.com/), pioneira em Digital Therapeutics no Brasil, está construindo uma nova forma de pacientes conviverem com seus tratamentos, e agora faz parte do grupo RD – Gente, Saúde e Bem-estar é uma empresa líder no mercado brasileiro de farmácias. Com as nossas marcas Droga Raia e Drogasil, temos mais de 2.500 unidades espalhadas por todo o país e mais de 50 mil funcionários(as) empenhados(as) em cuidar de perto da saúde e bem-estar das pessoas em todos os momentos da vida.

Até 2030, queremos ser o grupo que mais contribui para uma sociedade mais saudável. Para isso, entendemos que o nosso compromisso vai além do cuidado com a saúde individual. É preciso cuidar das pessoas, dos negócios e do planeta. Vamos juntos nessa?

## O que estamos buscando?

Um (a) profissional para atuar com Desenvolvimento e Manutenção dos sistemas e plataformas da Cuco Health, visando à conformidade aos padrões da empresa e qualidade das entregas. Se você se identifica com esse desafio, essa vaga é para você!

## Local

Remoto ou Escritório, Av. Corifeu de Azevedo Marques, São Paulo - SP

## Quais as principais responsabilidades?
- Desenvolvimento de tarefas disponibilizadas através do Jira, alinhadas com o PO;
- Desenvolvimento de novas funcionalidades, integrações com plataformas externas e manutenção das APIs;
- Participação nos ritos de SCRUM do time de desenvolvimento;
- Atuação com ferramentas de versionamento de códigos (Git);
- Revisão de código;
- Atuação com testes automatizados.

## O que precisa ter?
- Superior cursando/completo em Ciência da Computação, Análise e Desenvolvimento de Sistemas e áreas correlatas;
- Experiência com as principais tecnologias: PHP (preferencialmente com Laravel), Banco de dados relacionais (MySQL), PHPUnit, versionamento de código - (Git), APIs (REST);
- Desejável conhecimento em desenvolvimento de microserviços, Google Cloud Platform e Kubernetes;
- Experiência em times ágeis;
- Desenvolvimento de testes e2e;
- Vivência com SCRUM;
- Boas práticas de desenvolvimento e documentação.

## O que oferecemos?
- Contrato CLT;
- Horário flexível;
- Day off no aniversário;
- Modelo de trabalho home office;
- Assistência médica;
- Assistência odontológica;
- Vale transporte ou estacionamento no local, ou fretado;
- Seguro de vida; 
- SaúdeiD (telemedicina); 
- Restaurante no local;
- Gympass;
- Programa de Participação nos Resultados;
- Benefício farmácia e Clube de Benefícios RD.

## Como se candidatar

Por favor envie um email para tiago.rodrigues@drcuco.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Back-End Developer - SEU NOME

## Diversidade & Inclusão

Na RD, assumimos o compromisso de incluir e empoderar nossos(as) funcionários(as) por meio da promoção da diversidade e da inclusão. Valorizamos as pessoas, construindo uma cultura acolhedora e de respeito a todos e todas. Seja quem você é aqui!

**#vemserRD**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: tiago.rodrigues@drcuco.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
