### ISSUE TITLE
[REMOTO] Back-end Developer .NET @DQRTECH

### ISSUE THREAD

**Issue by carolinetech** [backend-br/vagas#9865]
### SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

### REQUISITOS:
Experiência em projetos de desenvolvimento de software utilizando .NET Core
Experiência em serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, SQS, DynamoDb, S3, EC2, RDS;

### DIFERENCIAL:
Experiência em modelagem de dados em DDD;
React;
Conhecimento em Arquitetura de Microsserviços;
Execução de testes unitários;
Metodologia ágil.

## local: Home Office 

**Diferenciais:**
- projetos na área financeira. 

## Benefícios

Vale Refeição/Alimentação;
Assistência Médica e Odontológica;
Seguro de Vida;
Acreditamos no desenvolvimento contínuo de nossos colaboradores, dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
Auxílio-creche;
Aqui a sua indicação vale premiação;
No seu aniversário tem mimos;
Contrato CLT (40 hrs semanais)

## Como se candidatar

Por favor envie um e-mail para caroline.silva@dqrtech.com.br com seu CV anexado - enviar no assunto: Vaga [REMOTO] Back-end Developer .NET @DQRTECH

**Comment by isabellebecker** [comment]
Show!!

**Comment by DaianeMFirmiano** [comment]
**Ótima oportunidade, galera!!**

**Comment by kerol-barros** [comment]
**#vempraDQRTech**

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
