### ISSUE TITLE
[Home-Office] Back-end Java Developer @ Alterdata Software

### ISSUE THREAD

**Issue by yankats** [backend-br/vagas#9868]
## Empresa
A Alterdata Software desenvolve soluções para impulsionar a prosperidade da sociedade através da tecnologia nos mais variados ramos de atuação, com destaque nos segmentos contábil, empresarial, food, imobiliário, moda e varejo.

Contamos com:

+2.500 colaboradores;
+ 300k sistemas em uso;
+ 50 mil clientes;
+100 bases em TODO Brasil!

Quer ser Alterdatano e fazer parte de uma das maiores empresas de tecnologia 100% nacional? A Alterdata é uma empresa que tem como objetivo melhorar a vida das pessoas, fornecendo soluções empresariais através de softwares e serviços. Você integrará nosso time de especialistas, desenvolvendo produtos da área contábil, utilizando as mais diversas tecnologias disponíveis no mercado.

Temos somente uma regra! Nunca ficamos parados, pois inovação é o que nos inspira a cada dia. Gosta de aprender e ser desafiado? Esse é o seu lugar!   

## Regime

**Vaga 100% Home Office.**

**Requisitos**
Experiência como programador Java;
Experiência com projeto orientado a objeto;
Padrões de projetos;
SQL;
APIs REST e integração entre sistemas. 

**Desejáveis:**
PostgreSQL;
ElasticSearch;
BDD, DDD e TDD;
Micro Serviços;
Métodos Ágeis;
SaaS;

**Diferenciais:**
HTML;
CSS e JavaScript
AWS;
Linux e Docker.

## Benefícios

Vale alimentação ou refeição;
Assistência médica;
Seguro de vida;
Gympass;
Assistência odontológica;
Além da oportunidade de crescimento conforme o seu desenvolvimento e descontos em produtos e serviços em diversas empresas parceiras a nível nacional, como cursos voltados para a área de programação, day off, entre outros...

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para yanka.rh@alterdata.com.br com seu CV anexado - enviar no assunto: Vaga Back-end Java

#### Nível
Pl/Sr

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
