### ISSUE TITLE
[Rio de Janeiro] Back-end Developer Java @fattoriaweb

### ISSUE THREAD

**Issue by carol3008** [backend-br/vagas#9870]
vaga híbrida 
 `[Rio de Janeiro] vaga Back-end Developer Java
-->
> Vaga híbrida

## Nossa empresa
A Fattoria é uma empresa focada em soluções para web com mais de 15 anos de mercado. Trabalhamos em projetos de escala nacional e procuramos profissionais que queiram trabalhar e crescer conosco.

## Descrição da vaga
Você desenvolverá sistemas em Java web de autoatendimento, apps e APIs;
Executará novas funcionalidades, manutenção em aplicações existentes e integrações de sistemas;

Requisitos 
- Graduação em Análise de sistemas e afins ou em curso;
- Experiência comprovada na área;
- Java web;
- Banco SQL/Oracle;
-  JSP, Struts, VRaptor, EJB e JBoss;
-  ambiente IDE;
- versão GIT ou SVN.

## Local
Remoto ou Escritório, Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- sólida experiência em Backend Java e seus framworks;
- experiência com ambiente IDE;

**Desejáveis:**
- conhecimentos em AWS.

## Benefícios

- Plano de saúde e odontológico Nacional;
- Seguro de vida;
- VR de R$ 29,65/ dia;
- VT quando necessário.

## Contratação CLT
Salário R$5.500,00

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com seu CV anexado - enviar no assunto: Vaga Java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
