### ISSUE TITLE
[Rio de Janeiro] Estágio Back-end Developer Java @fattoriaweb

### ISSUE THREAD

**Issue by carol3008** [backend-br/vagas#9871]
> Vaga híbrida

## A Nossa empresa
A Fattoria é uma empresa focada em soluções para web com mais de 15 anos de mercado. em projetos de escala nacional e procuramos profissionais queiram trabalhar e crescer conosco.

## Descrição da vaga

 Neste projeto de autoatendimento, você auxiliará a equipe de desenvolvimento nos sistemas web, em apps e APIs, executando manutenções em aplicações existentes e integrações de sistemas.

Requisitos
Conhecimentos em:
- Java web;
- Struts, VRaptor, EJB, JBoss, JSP, EJB;
- Banco SQL/ Oracle

##Local

Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- conhecimentos em programação Java;

**Desejáveis:**
- conhecimentos em frameworks de Java.

**Diferenciais:**
- vivência em programação

## Benefícios

- Seguro de vida
- VR de R$ 29,65/Dia
- VT quando necessário.

## Contratação

Contrato de estágio com bolsa auxílio.

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com seu CV anexado - enviar no assunto: Vaga estagio Java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.

#### Alocação
- híbrido

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
