### ISSUE TITLE
[Remoto] Staff Engineer @Passei Direto

### ISSUE THREAD

**Issue by nathzamberlan** [backend-br/vagas#9875]
## Nossa empresa

Prazer, somos a PD, parte do ecossistema UOL EdTech e orgulhosamente responsáveis por transformar o futuro de milhões de estudantes e produtores de conteúdo a partir do compartilhamento do conhecimento. Legal, né?

Você também pode nos conhecer como a maior rede de estudos do Brasil, pois contamos com 11 milhões de materiais disponíveis, mais de 20 milhões de visitas por mês e somos o app https://github.com/backend-br/vagas/issues/1 de Educação.

O nosso propósito é facilitar o acesso ao conhecimento para empoderar as pessoas e transformar o futuro. Na prática, isso significa que conectamos quem quer ensinar com quem quer aprender para conquistar seus sonhos.

## Descrição da vaga

A posição de Pessoa Staff - Engenheira de Software está em nosso time de Tecnologia e faz parte do plano de carreira técnico. O nosso maior desafio é trabalhar em conjunto com nossas equipes multifuncionais para ajudá-las a projetar e construir nossos produtos. Esperamos que você seja apaixonado por programação e arquitetura. Você também deve se sentir confortável trabalhando em um ambiente dinâmico e em ritmo acelerado. 🧡

Aqui na Passei Direto o aprendizado é constante. Contamos com a sua inquietude e colaboração para apoiar o time e suas principais responsabilidades serão:

- Liderar tecnicamente um time multidisciplinar composto por Pessoas Engenheira de Software Fullstack, Pessoa Engenheira Devops, Pessoa Engenheira de Qualidade e Data Scientists;
- Trabalhar junto com o Engineering Manager, Product Manager e Designer do time para alinhar prioridades do time;
- Zelar pelo ambiente em produção, prestando cuidados especiais ao uso eficiente dos recursos e à escalabilidade e estabilidade do sistema. Bem como definindo métricas técnicas para tais sistemas;
- Garantir que o time desenvolve com excelência técnica entregando um código limpo, com baixa proporção de bugs, boa cobertura de testes, melhores práticas e padrões sem desrespeitar o tempo estimado;
- Guiar o time para a construção de soluções e arquitetura dos sistemas, além de ser responsável técnico das soluções finais;
- Conduz mentorias técnicas e feedback técnicos com os membros do time;
- Interagir com outros Líderes Técnicos para avaliar soluções e garantir que o sistema de seu time esteja adequado aos demais sistemas da empresa;
- Mapear oportunidades de soluções e roadmap técnico do time;
- Identificar riscos técnicos dos projetos;
- Ter conhecimento sobre o funcionamento de times de plataforma e conseguir atuar com olhar macro, de forma onde consiga habilitar e alavancar as iniciativas dos demais times.

## Local

- Full remote (all Brasil)
- Flex office (Rio de Janeiro e Recife)

## Requisitos

Acreditamos que o nosso time nos ajuda a fortalecer a nossa cultura, transformando para melhor a forma que trabalhamos e nos relacionamos na empresa. Para essa oportunidade, estamos buscando um profissional com:

- Familiaridade com desenvolvimento de ponta a ponta de sistemas. De preferência sistemas do âmbito de descoberta de conteúdo (exemplo: busca, grafos, recomendação e categorização);
- Ser apaixonado por tecnologias e aprender uma nova por si mesmo, sendo capaz de configurar, testar, monitorar, otimizar, escalar e automatizar;
- Entender como os bancos de dados relacionais funcionam e ser capaz de modelar e consultar um banco de dados;
- Familiaridade com CI/CD (integração e entrega contínuas);
- Monitoramento e investigação de bugs e problemas;
- Familiaridade com diferentes tipos de testes automáticos (unitário, integração, componente, ponta a ponta);
- Conhecimento de princípios e padrões de qualidade software;
- Conhecer sobre programação orientada a objetos;
- Conhecer sobre REST Apis;
- Familiaridade com arquitetura de micro serviços, micro frontends, orientada a eventos e em cluster;
- Conhecimento em desenvolvimento ágil e protótipos rápidos;
- Aprender rápido e se adaptar às mudanças.

Tecnologias que usamos aqui :) mas não esperamos que você conheça todas elas!

- AWS (S3, ECS, EC2, RDS, SNS, SQS, ElastiCache, DynamoDB, CloudFront, Neptune, CloudWatch, Kinesis, Transcribe, Textract);
- Github;
- Python;
- Vue.js;
- React e React Native;
- Node.js;
- MySQL;
- Elasticsearch;
- Redis;
- Neo4j;
- RabbitMQ.

## Benefícios

- Vale alimentação ou refeição de R$ 815,00 mensais - não descontamos em período de férias!
- Plano de saúde e odontológico Bradesco nacional - sem co-participação e extensível para cônjuges e filhos;
- Seguro de vida.
- Descontos de até 50% em pós graduação e MBA de grandes instituições, como FIA e PUCRS;
- Plano corporativo do Gympass para você praticar o exercício físico que mais curte;
- Mentorias individuais e coletivas para nossas lideranças e time;
- Apoio psicológico, financeiro e jurídico 24 horas;
- Licença maternidade e paternidade estendida;
- Kit maternidade para mamães e papais de plantão;
- Auxílio creche de até R$530,00 por mês para filhos de até 6 anos;
- Happy Day para você poder aproveitar o dia do seu aniversário focando na pessoa mais importante do dia: você!
- Participação nos resultados da empresa (PPR): se a PD e a UOL Ed Tech ganham, você ganha também!
- Ajuda de custo mensal para o home office.

**Diferenciais:**

- Horário de trabalho flexível - aqui na PD não batemos ponto;
- Temos um dia no mês dedicado ao Aprendizado, o nosso Refresh, quando os foguetes compartilham conhecimentos e dedicam tempo para estudar o que preferir!

## Contratação

CLT, com salario a ser definido a partir da senioridade e pretensão salarial.

## Como se candidatar

Para esta vaga estamos usando a candidatura simplificada no Linkedin, para acessar clique [aqui](https://www.linkedin.com/jobs/view/3217309924)

## Tempo médio de feedbacks

Costumamos enviar feedbacks semanais sobre o andamento do processo seletivo, mas em caso de não haver resposta, você pode procurar via [Linkedin](https://www.linkedin.com/in/nathaliazamberlan/)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
