### ISSUE TITLE
[Remoto] Back-end Developer Java @SignaHealht

### ISSUE THREAD

**Issue by RenataVianaCosta** [backend-br/vagas#9881]
<!--
==================================================
> Vaga Remota 

## Nossa empresa

Somos uma healthtech que utiliza tecnologia e design para desenvolver softwares que ajudam pacientes e suas equipes de cuidado. Ajudamos prestadores de serviço de saúde a promover cuidado integrado oferecendo comunicação centralizada, rápida e segura. Isso possibilita a criação de ações de saúde baseada em valor, como linhas de cuidado e programas de navegação. 

Para o paciente, criamos soluções que viabilizam contato direto, fácil e seguro com sua equipe, gerenciamento de consultas e compromissos e assistência de qualquer lugar. 

Acreditamos que um mundo melhor é feito de pessoas que se sentem cuidadas, pertencentes e importantes, mesmo em seus momentos mais difíceis. 

Somos o elo que promove conexões mais humanas entre pacientes crônicos e prestadores de serviços de saúde. É assim que mudamos o mundo.
## Descrição da vaga

Back-end Developer Java

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Java
- 2 anos de experiência com Spring

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Ter atuado em produtos digitais
- ter atuado em Projetos de Saúde

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para renata.viana@signa.health com seu CV anexado - enviar no assunto: Vaga Java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
