### ISSUE TITLE
[Remoto] Back-end Developer Java @signahealth

### ISSUE THREAD

**Issue by RenataVianaCosta** [backend-br/vagas#9882]
## Nossa empresa

Somos uma healthtech que utiliza tecnologia e design para desenvolver softwares que ajudam pacientes e suas equipes de cuidado. Ajudamos prestadores de serviço de saúde a promover cuidado integrado oferecendo comunicação centralizada, rápida e segura. Isso possibilita a criação de ações de saúde baseada em valor, como linhas de cuidado e programas de navegação. 

Para o paciente, criamos soluções que viabilizam contato direto, fácil e seguro com sua equipe, gerenciamento de consultas e compromissos e assistência de qualquer lugar. 

Acreditamos que um mundo melhor é feito de pessoas que se sentem cuidadas, pertencentes e importantes, mesmo em seus momentos mais difíceis. 

Somos o elo que promove conexões mais humanas entre pacientes crônicos e prestadores de serviços de saúde. É assim que mudamos o mundo.
## Descrição da vaga

[Remoto] Back-end Developer Java 

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Java
- 2 anos de experiência com Spring

**Desejáveis:**

**Diferenciais:**
- Ter atuado em Projetos Digitais com foco em Saúde
## Benefícios

- Horário Flexível
- 30 dias remunerados a cada 12 meses

## Contratação

PJ / Remuneração de R$ 9.000 (Pleno) a R$ 14.000 (Senior) - negociavel

## Como se candidatar

Por favor envie um email para renata.viana@signa.health com seu CV anexado - enviar no assunto: Vaga Java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
