### ISSUE TITLE
[Remoto] Analista de testes Júnior - QA @ HealthBit

### ISSUE THREAD

**Issue by jsantosrh** [backend-br/vagas#9883]
## Nossa empresa

Nosso cliente/parceiro é uma Healthtech que faz parte do grupo RD, atende empresas e encontra soluções inteligentes que melhorem a saúde de seus colaboradores e familiares, reduzindo custos demandados com operadoras de plano de saúde, sinistralidade, afastamentos e muito mais. Suas principais especialidades são: tecnologia, análise de dados e gestão em saúde, trabalhando com grandes números (Big Data) e tecnologias escaláveis ampliando a melhoria do sistema de saúde.

## Descrição da vaga

Principais atividades e responsabilidades: 

- Estudo de caso;
- Escrita e Execução de testes manuais e dinâmicos;
- Extração de testes;
- Levantamento de requisitos.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**

- Experiência prática com testes manuais;
- Levantamento e análise de requisitos;
- Ensino superior cursando ou completo em Tecnologia ou correlatas;

**Desejáveis:**

- Experiência com Testlink e Azure;
- Noções de extração de dados;

## Benefícios

-  Auxílio Home Office;
- Plano de Saúde;
- VA;
- Auxílio saúde mental;
- Desconto em Farmácias;
- Seguro de vida.

## Como se candidatar

Por favor envie um e-mail para rpaiva@acelerarh.com.br com seu CV anexado - enviar no assunto: Analista QA JR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: ksouza@acelerarh.com.br

#### Regime
- CLT

#### Nível
- Júnior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
