### ISSUE TITLE
[Remoto] Delphi Developer (Sênior) na Grupo Fácil

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9886]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/analista-de-sistema-delphi-234710833?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Grupo Fácil</strong> busca <strong><ins>Delphi Developer</ins></strong> para compor seu time!</p>
<p></p>
<p><strong>Atividades e responsabilidades:</strong></p>
<ul>
<li>Atuará com desenvolvimento e manutenção de programas, implementar melhorias, correções em sistemas, baseando nas definições fornecidas na fase de análise, valendo-se de métodos, técnicas adequadas aos equipamentos e aplicações que destinam Delphi. Programação orientada à objetos.</li>
</ul>
<p></p>

## Grupo Fácil: 
 <p>Nós somos o Grupo Fácil. Ao longo de mais de 25 anos construímos uma história de inovação, dinamismo e ousadia, com grandes clientes e projetos que são referência para o mercado.</p>
<p>Nossas cinco empresas se destacam por um atendimento dedicado, proximidade com os clientes, resultados surpreendentes e excelência técnica.</p><a href='https://coodesh.com/empresas/grupo-facil'>Veja mais no site</a>

 ## Habilidades: 
 - Delphi 
- PL/SQL 
- Oracle
## Local: 
 100% Remoto
## Requisitos: 
 - Se habituado com metodologias ágeis; 
- Trabalho em equipe; 
- Conhecimento avançado em modelagem e desenvolvimento de aplicações com alto desempenho, alta disponibilidade e sistemas de grande porte; 
- Nível superior completo ou em curso.
## Diferenciais: 
 - Conhecimento em gestão de operadora de saúde.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Delphi Developer (Sênior) na Grupo Fácil](https://coodesh.com/vagas/analista-de-sistema-delphi-234710833?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
