### ISSUE TITLE
[Remoto] Backend Developer C# na Samba Tech

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9889]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-backend-c-plenosenior-202521643?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Samba Tech</strong> está buscando<strong><ins> Backend Developer C# (Pleno/Sênior)</ins></strong> para compor seu time!&nbsp;</p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - C# 
- Asp.Net 
- API
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em C#; 
- Conhecimento em Asp.Net; 
- Conhecimento em API’s REST e GraphQL; 
- Conhecimento em ReactJS; 
- Microservices; 
- Testes unitários.

## Benefícios: 
 - Ambiente criativo e inovador; 
- Clima leve e descontraído; 
- Horário flexível; 
- Home office; 
- Auxílio home office; 
- Plano de Saúde; 
- Plano Odontológico; 
- Vale refeição/alimentação; 
- Gym Pass;  
- Day off no dia do aniversário; 
- Seguro de vida; 
- Ways Education - Atividades extracurriculares para os filhos; 
- Previdência privada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Developer C# na Samba Tech](https://coodesh.com/vagas/desenvolvedor-backend-c-plenosenior-202521643?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
