### ISSUE TITLE
[Remoto] Back-end Developer

### ISSUE THREAD

**Issue by Livia-Tech** [backend-br/vagas#9891]
## **Pessoa desenvolvedora Backend**

PJ
Remoto
Rate até R$24.000,00 conforme senioridade

## Requisitos **Obrigatórios:**

_Deve possuir experiência de no mínimo 4 anos nas ferramentas abaixo:_
- Java 
- Kotlin 
- Cloud

## Benefícios
- 15 dias de férias anuais

## Contratação
PJ

## Como se candidatar

Por favor envie um e-mail para **liviamalexandre@outlook.com** com seu CV anexado - enviar no assunto: Vaga Back-end Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: liviamalexandre@outlook.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
