### ISSUE TITLE
[Brasil] Back-end Developer Clojure SR na Hunter

### ISSUE THREAD

**Issue by ErikaStosTechRecruiter** [backend-br/vagas#9894]
[Back-end] Developer Clojure SR  [https://forms.gle/NgWbM7djS5AYNTp4A](url)

Remoto - Sênior 

Empresa especializada em design criativo, e está construindo um produto no mercado de Machine Learning/Artificial Intelligence e está buscando um Sr. Back End Developer (Clojure + AWS).

REQUISITOS:
Inglês avançado
Clojure, Aws
5 anos de experiência ou mais.
Preferencialmente que tenham experiência trabalhando em startups.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
