### ISSUE TITLE
[REMOTO] Senior Java Developer na [Builders]! 🤩🤟

### ISSUE THREAD

**Issue by RaissaBaltazar** [backend-br/vagas#9898]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Um lugar para você se desenvolver, crescer e alcançar resultados exponenciais, é essa oportunidade que te espera aqui, o momento para se tornar Builder é agora! 😎

**Tecnologias que vão gerar valor nos projetos 💻:**
- Java 8+;
- Springboot;
- Sonar;
- Unit Test;
- JPA;
- GIT;
- Linux;
- DDD.

**Conhecimentos que te aproximam de ser uma Pessoa Builder 💪:**
- Docker e Kubernets;
- Cloud;
- Plataformas de CI/CD como Jenkins, ArgoCD, Github Actions;
- Maven;
- Arquitetura de micro serviços;
- REST;
- Design Patterns.

**Como Builder, você terá acesso a 👀:**
- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios.

**Junte-se ao Movimento! 💛🖤**
[Inscrição pelo link](https://bit.ly/3Sf7C13)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
