### ISSUE TITLE
[Lisbon ou Porto - Portugal] Oportunidades Internacionais @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#9899]
# Estás à procura de projetos internacionais na área de IT? Se o teu objetivo é ser bem-sucedido na Europa, temos novidades para ti!

## .Net Developer 

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional em desenvolvimento .NET;

- Experiência com C# e .NET Core;

- Conhecimento em APIs;

- Familiaridade com metodologias Agile;

- Inglês fluente (obrigatório).

 

## Java Developer

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional em desenvolvimento Java;

- Experiência em Java 8+;

- Experiência com Micro Serviços e Spring Framework;

- Experiência com SQL Server;

- Familiaridade com metodologias Agile;

- Inglês fluente (obrigatório).

 

## Outsystems Developer

- Experiência em Outsystems 11;

- Experiência no desenvolvimento de extensões;

- Experiência em TDD/BDD e Continous Delivery;

- Experiência em SQL;

- Conhecimentos em .Net;

- Inglês fluente (valorizado).

 

## Business Process Management (BPM)

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- Experiência com desenvolvimento ADF; 

- Experiência com Oracle SOA Suite (OSB, BPEL, Weblogic);

- Experiência com bases de dados Oracle (preferencialmente 12c); 

- Conhecimentos de XML, de contratos XSD e transformações XPath, XSLT.

## ETL Developer

- Experiência em desenvolvimento de processos ETL em ambiente DataWarehouse Oracle;

- Experiência em Powercenter, Datastage ou Oracle ODI;

- Conhecimentos em base de dados Oracle (SQL e PL/SQL);

- Conhecimentos de BI;

- Capacidade de análise de requisitos e desenho técnico de modelos analíticos.

## Tester Automático

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional com testes automáticos;

- Experiência com ferramentas de automação (Selenium, Appium, Calabash);

- Conhecimentos das Frameworks BDD (Behaviour Driven Development) como o Cucumber;

- Capacidade de realizar testes funcionais, além dos automáticos;

- Inglês fluente (obrigatório).

## iOS Developer

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional em desenvolvimento iOS;

- Experiência com Swift e/ou Objective-C;

- Experiência com Rest APIs;

- Conhecimentos das Frameworks iOS, como por exemplo, Foundation e UIKIT;

- Inglês fluente (obrigatório).

## Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues.
