### ISSUE TITLE
[São Paulo] Back-End Developer na AUTOMATOS

### ISSUE THREAD

**Issue by fellipecouto96** [backend-br/vagas#99]
## Descrição da vaga

O candidato deve ter um perfil autodisciplinado, saber trabalhar em equipe e manter-se atualizado, em constante aprendizado. Deve ter postura analítica e ser capaz de propor melhorias no sistema, saber se comunicar e buscar informação com key-users e sponsors do projeto.

## Local

Escritório, São Paulo - São Paulo

## Beneficio

- Vale refeição (R$ 20,00/dia)
- Vale transporte
- Convênio Médico (Sul América)
- Convênio Odontológico (Sul América)
- Seguro de vida (Metlife)
- Plano de Previdência Privada (Sul América)

## Requisitos

**Obrigatórios:**
- C# (.net e .net core)
- JavaScript
- Node.JS
- SQL
- Testes Unitários
- Design Patterns
- Métodos Ágeis
- Docker
- Git (Bitbucket)

**Desejáveis:**
- C, C++, Python, Delivery Continuous, Continuous Integration

**Diferenciais:**
- projetos opensource

## Contratação

CLT - R$ 4.000,00 (nos 3 primeiros meses, após esse período passará para R$ 5.000,00)

## Nossa empresa

Fundada em 2001 e uma das pioneiras na oferta de software como serviço no Brasil, a Automatos é uma empresa nacional de software e serviços de TI reconhecida por sua excelência no atendimento.
 
Com mais de 200 clientes dos mais diversos segmentos de mercado e em todo território nacional, a Automatos gerencia através de sua solução de Inteligência em Gestão de Ativos, mais de 1 milhão de dispositivos de TI.
 
A Automatos conta com colaboradores e parceiros experientes, altamente capacitados e focados na oferta de soluções de gestão de ativos de TI com alto valor agregado.

## Como se candidatar

https://app.vulpi.com.br/automatos/589

## Labels

- Alocado
- CLT
- Pleno

**Comment by reginaldojunior** [comment]
Vaga preenchida? Issue fechada, se ainda estiver aberta me avisa que reabro.
