### ISSUE TITLE
[Remoto] Senior Fullstack Developer (Node.js/React.js) @ DQR Tech

### ISSUE THREAD

**Issue by kerol-barros** [backend-br/vagas#9902]
## Oportunidade
Senior Fullstack Developer (Node.js/React.js) 

## Nossa empresa

Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

Estamos buscando um profissional para atuar em um grande projeto de nosso cliente do setor financeiro.

## Local

100% Remoto 

## Requisitos

**Obrigatórios:**
- Experiência em projetos de desenvolvimento de software utilizando NODE, Javascript, React;
- BDs relacionais e não relacionais (Saber fazer Tuning);
- Experiência em serviço de mensageria (RabbitMQ/Kafka, ou semelhantes);
- Docker;
- Design Patterns GoF, POO;
- API Rest;
- WebServices – Rest;
- Desenvolvimento de aplicações em nuvem AWS (SQS, SNS, Lambda, API Gateway; Serverless).

**Diferenciais:**
- Experiência em Modelagem de dados em DDD;
- Conhecimento de arquitetura em Microserviços;
- Conhecimento em ferramentas de automação de infraestrutura as a code Jenkins;
- Execução de Testes Unitários;
- Metodologia ágil;
- Aplicação SOLID;
- Elixir/Go.

## Contratação

CLT

**Benefícios:**
- Assistência médica e Odontológica sem coparticipação para colaboradores;
- Auxílio flexível de R$880,00 para gastar como quiser;
- Acreditamos no desenvolvimento contínuo de nossos colaboradores, dessa forma
oferecemos acesso full aos cursos da plataforma ALURA;
- Auxílio-creche;
- Prêmio: Indique seus amigos, aqui sua indicação vale premiação em dinheiro*;
- Seu aniversário tem pizza: No dia do seu aniversário a pizza é por nossa conta, para que você comemore este dia especial com as pessoas que você gosta;
- Seguro de vida.

## Como se candidatar

Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: kerolayne.barros@dqrtech.com.br - enviar CV anexo e no assunto colocar: Vaga Fullstack Node.js

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- 100% Remoto

#### Regime
- CLT

#### Nível
- Pleno/Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
