### ISSUE TITLE
[Remoto] Back-end Developer PHP (Laravel) SR @ IEBT Innovation 

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#9904]
## Descrição da vaga

Atenção Galera de PHP!
Se o seu sonho é trabalhar em uma empresa que materializa transformações efetivas para grandes corporações, preza por um cuidado especial com as pessoas e constrói ambientes de trabalho colaborativos e ágeis, então se liga nessa oportunidade!

Responsabilidades
-Desenvolver códigos seguindo recomendações;
-Realizar correção de bugs;
-Prezar pela qualidade dos códigos e realizar code review.

## Local

Remoto

## Benefícios

- Plano de saúde Bradesco coparticipativo e extensivo a família;
-Auxílio home office;
-Auxilio Transporte;
-Auxilio Alimentação;
-Férias pagas e Day off no dia do aniversário;
-Auxílio PJ;
-Auxilio saúde e bem estar (Acesso gratuito a plataforma de saúde mental);
-Plano de treinamento e desenvolvimento de soft e hard skills, conforme o feedback e feedfoward- PDI. Plano de cargos e salários;
-Licença maternidade e paternidade paga;
-Ambiente inovador com acesso a informações e pesquisas e projetos de impacto social e econômico, treinamento, flexibilidade de horário;

## Requisitos

O que você precisa conhecer
-Experiência em PHP e Laravel;
-Banco de dados MySQL;
-Controle de versão Git;
-Familiaridade com as PSRs;
-Conhecimentos sólido no paradigma OO.

Pra ter aquela vantagem extra
-Experiência na criação de soluções escaláveis / serviços com grande concorrência;
-Serviços AWS;
-NodeJs;
-Ambientes virtualizados (docker);
-Mensageria / Sistemas de filas;
-Conhecimentos em design e arquitetura de software;
-Conhecimento das boas práticas da engenharia de software, ferramentas e processos.

## Contratação

PJ

## Nossa empresa

O IEBT Innovation é uma consultoria de Inovação Corporativa e Transformação Digital.

Um time com mais de 150 profissionais e 12 anos de experiência em Materialização de Resultados por meio de Inovação e Tecnologia.

O que fazemos:

Inovação Corporativa: Estratégia e Cultura de Inovação; Inovação Aberta e Gestão de Hubs Corporativos; Corporate Venture Capital e Corporate Venture Building.

Transformação Digital: Squad-as-a-Service de Desenvolvimento Ágil de Software, RPA, Ciência de Dados e Analytics.

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/62f663903ae929001ee7deec?r=nvgt&c=4740

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
