### ISSUE TITLE
[Farroupilha-RS Remoto/Presencial] Back-End Developer JR/PL @Grendene

### ISSUE THREAD

**Issue by BarbaraRodarte** [backend-br/vagas#9906]
## Nossa empresa

A nossa história é construída há mais de 50 anos por mãos que realizam e expressam seu amor em tudo o que fazem!
Nosso principal recurso é o capital humano, é através do comprometimento e da dedicação das nossas pessoas que os nossos produtos chegam aos pés dos nossos consumidores.

Somos detentores das marcas: Melissa, Rider, Grendha, Ipanema, Zaxy, Cartago, Grendene Kids e Pega Forte, além de uma linha de licenças que contemplam celebridades e personagens. Além disso, temos o licenciamento para a produção e venda dos calçados da marca Azaleia.

Somos comprometidos com o futuro, por isso, buscamos constantemente por soluções que garantam a eficiência dos nossos processos, reduzam desperdícios e contribuam para o bem-estar dos nossos colaboradores e comunidades onde estamos inseridos.

Acreditamos que a equidade e o respeito às diferenças promovem um clima organizacional colaborativo e de valorização ao outro, criando ambientes psicologicamente seguros que estimulam nossos talentos a atingirem seu potencial.

## Descrição da vaga

Analisar e desenvolver soluções técnicas através de requisitos de softwares utilizando-se das tecnologias envolvidas;
Orientar e trabalhar com o time de desenvolvimento para encontrar soluções de negócio, arquitetura através da comunicação e trocas de conhecimento;
Realizar manutenção e a otimização dos softwares existentes, visando sempre a melhor experiência para as áreas de negócio;
Criar modelagem de dados com o objetivo de implementar sistemas bem estruturados e que atendem as regras de negócio;
Realizar análises de requisitos funcionais e elaborar documentações técnicas e funcionais.

## Local

- Remoto ou Escritório, Rio Grande do Sul - Farroupilha

## Requisitos

**Obrigatórios:**

- Graduação completa em áreas correlatas;
- Desenvolvimento em Java
- Modelagem de dados,
- GIT/TFS,
- Metodologias ágeis
- Web Servers;

**Diferenciais:**
- Vivência com uma ou mais das seguintes linguagens:
- JavaScript, PrimeFaces, PL/SQL, WEB, .NET, ASP, C#, PHP, HTML5 ou CSS.

## Benefícios

- Seguro de vida;
- Plano de Saúde (Unimed);
- Refeitório na empresa (para contratos presenciais e híbrido)
- Cesta básica (para contratos presenciais e híbrido - para contratado remoto, revertido em valor no cartão alelo);
- Transporte fretado (para contratos presenciais e híbrido)
- Auxílio Creche (para filhos com idade até 5 anos, 11 meses e 29 dias) – apenas para funcionárias mulheres;
- Auxílio médico e odontológico na empresa para funcionários;
- Cesta de Páscoa
- Ave de Natal
- Festa e presente de Natal para filhos de funcionários (até 12 anos)
- Diversos convênios com óticas e farmácias
- Loja Interna Online (acesso aos nossos produtos de forma facilitada)
- Universidade Grendene – desenvolvimento para equipes com ações diferenciadas e acesso à plataforma do conhecimento Grendene.

## Contratação

CLT + Salário a combinar. Estamos trabalhando com a sua pretensão.

## Como se candidatar

Por favor candidate-se pelo link abaixo:
https://vagas.hunterco.com.br/job/62ba179c4d7b47001eee74fa?c=6297

Caso tenha dúvidas, segue meu e-mail para contato: barbararodarte.rh@gmail.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: barbararodarte.rh@gmail.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by pablo-moraes** [comment]
Esta vaga já foi preenchida?
A vaga do link não está mais disponível, segundo o site.
