### ISSUE TITLE
[VAGA Internacional] Back-end Developer Node.js | Typescript | DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [backend-br/vagas#9908]
> Atuação 100% remota

## Nossa empresa
Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga
O QUE NOS MOVE?
Tecnologia e vontade de evoluir! É por isso que estamos em busca de excelentes profissionais para atuar em uma Edtech sustentável e inovadora de Las Vegas – Nevada, que busca combinar e conectar estudantes com universidades adequadas e suas futuras carreiras.

SUAS ATIVIDADES SERÃO?
Analisar, projetar, desenvolver, configurar, implantar, manter e aprimorar aplicações altamente escaláveis para a web.

## Local
Remoto!!

## Requisitos
O QUE ESPERAMOS QUE VOCÊ TENHA?
Node.js
Typescript
DynamoDB
Serverless Framework
Automação de testes com Jest ou similares
GraphQL
Processos ágeis
Versionamento com GIT
Sistemas Linux
Inglês intermediário ou avançado

O QUE SERIA LEGAL SE VOCÊ TIVESSE?
DevOps
CI/CD

SOFT-KILLS ESPERADAS?
Comprometimento; Foco no desenvolvimento do produto;
Perfil responsável; Perfil Proativo.

## Benefícios
O QUE OFERECEMOS PARA VOCÊ?
Modalidade de trabalho PJ (pago em Dólar)!
Contrato por longa duração - tempo indeterminado.
Buscamos profissionais para permanecerem por bastante tempo em atuação conosco!!

Vem pra DQR TECH!!
Aguardamos seu contato!!

Meu contato direto
(51) 989678273
daiane.firmiano@dqrtech.com.br
Linkedin: https://www.linkedin.com/in/daiane-firmiano-74b1a622/

DQR Tech
Qualidade do inicio ao fim
🌐 https://lnkd.in/ecbmZnu

## Contratação
PJ 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
