### ISSUE TITLE
[Hibrido / Região Metropolitana de Belo Horizonte, Minas Gerais, Brazil] Python Developer (Híbrido) na VP6

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9910]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-de-sistemas-235848261?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>VP6</strong> busca<strong> </strong><strong><ins>Python Developer</ins></strong> para compor seu time!</p>
<p>A VP6 é uma software house que desenvolve ferramentas para otimização de processos empresariais.</p>
<p>Construímos soluções personalizadas para cada cliente e integráveis a outras ferramentas para fortalecer as operações do seu negócio, aliando tecnologia à performance.</p>
<p><strong>Reponsabilidades:</strong></p>
<ul>
<li>Criar e manter API´s que cumprem os requisitos de negócio;</li>
<li>Realizar a manutenção e evolução dos sistemas que construímos.</li>
</ul>
<p></p>
<p></p>
<p></p>

## VP6: 
 <p>A VP6 é uma software house que desenvolve ferramentas para otimização de processos empresariais.</p>
<p>Construímos soluções personalizadas para cada cliente e integráveis a outras ferramentas para fortalecer as operações do seu negócio, aliando tecnologia à performance.</p><a href='https://coodesh.com/empresas/vp6'>Veja mais no site</a>

 ## Habilidades: 
 - SQL 
- Python 
- Django
## Local: 
 Região Metropolitana de Belo Horizonte, Minas Gerais, Brazil
## Requisitos: 
 - Linguagem SQL Intermediário/Avançado; 
- Python para dados (pandas not e outras bibliotecas) Intermediário/avançado; 
- Noções de Django.

## Benefícios: 
 - Plano de saúde; 
- Vale alimentação; 
- Gympass; 
- Aulas de inglês.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Python Developer (Híbrido) na VP6](https://coodesh.com/vagas/desenvolvedor-de-sistemas-235848261?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Full-Stack

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
