### ISSUE TITLE
[São Paulo] Devs Fullstack Java/Angular @ Foursys

### ISSUE THREAD

**Issue by alexandrebronze** [backend-br/vagas#9913]
Devs Fullstack Java/Angular

[São Paulo] Devs Fullstack Java/Angular @ Foursys

==================================================
-->
> Vaga Híbrido

## Se o seu sonho é trabalhar com novas tecnologias ao lado de pessoas incríveis e ter novos aprendizados dentro de equipes multidisciplinares, vem com a gente! #VemSerFoursys 👊

Buscamos profissionais que sejam comprometidos com resultados, criativos nas resoluções de problemas, que vibram energia, que são movidos pela curiosidade, que sabem construir junto com outras pessoas e desfrutem do trabalho em equipe.

A Foursys nasceu em 2000 com o propósito de revolucionar o mercado de TI. Atendemos grandes clientes nacionais e internacionais através de nossos escritórios localizados no Brasil e nos Estados Unidos.

## Local

Híbrido, São Paulo - Santo Amaro

## Requisitos

**Obrigatórios:**
Java 11+.
Desenvolvimento de micro serviços.
Frameworks (Spring, Spring Boot, Hibernate).
Integração com serviços SOAP, Rest (cliente e servidor).
API Gateway.
Banco SQL AWS.
Conhecimentos em Design Patterns e padrões de arquitetura.
Monitoramento: ferramentas como Dynatrace ou Google Analytics.
Diferencial: Python, Javascript, Camel. Devops.
Git / GitFlow.
Jenkins.
Docker.

**Desejáveis:**
- conhecimentos em Ruby on Rails
- conhecimentos em C#

## Benefícios

- Plano de saúde
- VR 

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para alexandre.bronze@foursys.com.br com seu CV anexado - Assunto: Vaga Devs Fullstack Java/Angular 

#### Alocação
- Híbrido

#### Regime
- CLT

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
