### ISSUE TITLE
[REMOTO] Desenvolvedor Node.js Sênior| DEAL TECHNOLOGIES

### ISSUE THREAD

**Issue by ThauanySilva7** [backend-br/vagas#9914]
**Sobre nós**
Somos a Deal, estamos no mercado desde 2004 e somos referência em Inteligência de Dados e Transformação Digital, desde a estratégia até a execução (end-to-end).
Aqui, cada Dealmaker tem liberdade para:
• Ser quem é, numa cultura que valoriza as pessoas pela sua essência;
• Trabalhar de onde quiser, porque o Anywhere Office é uma realidade por aqui;
• Ser protagonista da sua carreira e escolher aonde quer chegar profissionalmente!

**Experiência e Conhecimentos em:**
• Desenvolvimento Node.js
• APIS em microserviços
• Arquitetura baseada em SOLID
• Arquitetura hexagonal
• Desenvolvimento guiado por teste (TDD)
• Clean architecture, DDD
• Cloud, RabbitMQ, Kafka
• Metodologias de entrega ágil e integração contínua

**Local**
Remoto, trabalhe de qualquer lugar da galáxia. 

**O que oferecemos:**
• Benefícios personalizados
• Parceria com o SESC
• Capacitação e desenvolvimento pelo nosso Núcleo de Inovação Deal
• Programa de mobilidade interna (Deal Moving)
• E muito mais!

**Como se candidatar**
Por favor, envie um e-mail para [vemser@deal.com.br](mailto:vemser@deal.com.br)
Com seu CV anexado – enviar no assunto: Desenvolvedor Node.js Sênior

**Labels**
•	Remoto 
•	Sênior
•	CLT
•	NodeJS
•	TDD
•	Cloud
•	 RabbitMQ
•	 Kafka
•	APIS
•	SOLID

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
