### ISSUE TITLE
[São Paulo (Híbrido)] Full Stack Developer (Node.js / React) @ Glocou

### ISSUE THREAD

**Issue by lucas-glocou** [backend-br/vagas#9916]
[São Paulo (Híbrido)] Full Stack Developer (Node.js / React) @ Glocou

## Nossa empresa

Junte-se aos primeiros dias de uma startup com o propósito de transformar o ecossistema agrícola no Brasil e assuma uma posição chave desde os primeiros dias.

A Glocou está transformando o ecossistema de tecnologia agrícola do Brasil, e nossa missão de empoderar pequenos agricultores é o coração e alma do que estamos construindo.
- Já alcançamos 300+ pequenos produtores de café
- Estamos lançando produtores inovadores na comercialização e financiamento agrícola
- Estamos desenvolvendo o futuro da agricultura transparente

A Glocou foi criada por dois alumni do INSEAD junto com um em-membro da Rappi. Nossa equipe fundadora se alavanca no conhecimento de tecnologia, agricultura e finanças.

## Descrição da vaga

O desenvolvedor irá trabalhar em um ou mais projetos relacionados a Marketplace, SaaS e Financiamento

O candidato ideal para esta função é tanto visionário como executor, possui experiência na construção de equipes e produtores e conhecimento sobre o que é preciso para estar em uma startup em seus primeiros dias.
Aqui você irá:
- Colocar a mão na massa e desenvolver processos
- Sair da zona de conforto para desempenhar vários papéis
- Garantir um produto estelar
- Liderar uma squad e ajudar a moldar a cultura de uma startup incrível
- Projetar e liderar novos produtos. Temos algumas ideias em mente e estamos empolgados com elas.

## Local

Nossa equipe é híbrida trabalhando remotamente e do nosso escritório nos Jardins, São Paulo

## Requisitos

**Obrigatórios:**
- Experiência nível sênior com Node.js, React, PostgreSQL e AWS
- Capacidade de criar código limpo, moderno, testável e bem documentado
- Mentalidade empreendedora para construir uma grande empresa com poucos recursos
- Autônomo e curioso

**Desejáveis:**
- Experiência em C#

**Diferenciais:**
- Gostar de agro e de café
- Ter construído algum produto do zero

## Contratação

PJ a combinar + stock options

## Como se candidatar

Por favor envie um email para lucas@glocou.com com seu CV anexado ou perfil no linkedin - enviar no assunto: Candidato Dev

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
