### ISSUE TITLE
[REMOTO] SRE Azure Devops @ Bionexo

### ISSUE THREAD

**Issue by catenawork** [backend-br/vagas#9917]
## Bionexo

Somos a Bionexo, uma healthtech brasileira com mais de 20 anos e somos
experts em desenvolver soluções SaaS que trazem mais eficiência, transparência
e inteligência para a área da saúde.

Com mais de 500 colaboradores espalhados pelo Brasil, Colômbia, Argentina e México, estamos em pleno crescimento e em busca de um SRE Devops Azure!

## Descrição da vaga

✔️ Manter a infraestrutura de tecnologia da Bionexo em funcionamento

✔️ Analisar e monitorar o desempenho da plataforma

✔️ Desenvolver e implementar soluções com estabilidade, escalabilidade, segurança

✔️ Administrar ambientes em Cloud

## Local

Work From Anywhere - 100% Remoto

## Requisitos

✔️ Experiência com Cloud Computing Azure (diferenciais AWS e Oracle Cloud)

✔️ Experiência com Docker Swarm e Kubernetes

✔️ Experiência com Softwares de monitoramento e logs (ELK, Graylog, Zabbix, Nagios)

✔️ Experiência em serviços Web (Nginx e Apache)

## Benefícios

✔️ Bônus Anual

✔️ Cartão de Benefícios + Auxílio Home-Office

✔️ Assistências Médica e Odontológica + Dependentes

✔️ Seguro de vida + Gympass + Programa de Saúde Mental

✔️ Licença maternidade/paternidade + Auxílio-creche

## Contratação

CLT

## Como se candidatar

Acesse o [LINK](https://form.jotform.com/222333608585660)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
