### ISSUE TITLE
Lucere Tecnologia > Desenvolvedor Full Stack Pleno < REMOTO

### ISSUE THREAD

**Issue by gabrielanatascha** [backend-br/vagas#9919]
Desenvolvedor Full Stack Pleno - REMOTO

Formação: curso superior completo ou em andamento em Análise e Desenvolvimento de Sistemas, Tecnologia da Informação e afins. 

Atribuições: Atuar no desenvolvimento de novas aplicações e manutenção/sustentação de aplicações existentes. 

Requisitos: Experiência com ASP.NET core, React ou Angular, SQL Server, Entity Framework, DDD (Domain Driven Design). 

Diferenciais: Noções de Azure, CQRS, RabbitMQ, IIS e experiência com aplicações de facilities.

Modelo de contrato: PJ 

Remuneração á combinar. 

Interessados encaminhar currículo para: gabriela@escolhacertarh.com.br

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
