### ISSUE TITLE
REMOTO > Desenvolvedor Back End < Intellimetri 

### ISSUE THREAD

**Issue by gabrielanatascha** [backend-br/vagas#9920]
Estamos em busca de um Desenvolvedor Back-End Pleno ou Sênior:

Se você gostaria de entrar para um time tendo como principal objetivo contribuir com a Transformação Digital por meio de inteligência artificial e do Machine Learning, essa vaga é para você!

Requisitos: curso superior completo ou cursando nas áreas de programação;  experiência mínima de três anos no desenvolvimento de Python com Django, domínio de integração de APIs e conhecimento de SQL, disponibilidade para atuar remoto e full time. 

Modelo de contrato: PJ 

Remuneração á combinar. 

Interessados encaminhar currículo para: [gabriela@escolhacertarh.com.br](mailto:gabriela@escolhacertarh.com.br). 

#escolhacertarh #vagasti #desenvolvimento #backend #python #django #ti #tech #vagassc #tabalhoremoto #oportunidade #fulltime

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
