### ISSUE TITLE
[Remoto] Back-end Developer DotNet @ Brasil Risk

### ISSUE THREAD

**Issue by vitoriagcosta** [backend-br/vagas#9921]
## Nossa empresa
Desde 2006 a [Brasil Risk](https://www.brasilrisk.com.br/pt-br) atua em Gerenciamento de Riscos de Transporte de Carga, Gestão Logística e Gerenciamento de Risco Patrimonial. Com estrutura diferenciada, conhecimento e experiência comprovada, a Brasil Risk, gerenciadora de risco, inova e aumenta consistentemente a efetividade de seus serviços e produtos, ampliando a acessibilidade, a conveniência e a simplicidade de suas ofertas.

A sua experiência é muito valiosa para a Brasil Risk!

Somos um time que valoriza as diferenças e características de cada colaborador. E, como uma equipe, cada um cumpre uma tarefa indispensável.

## Descrição da vaga
Buscamos alguém para exercer as seguintes atividades:
- Realizar as fases de elaboração de requisitos e da programação de sistemas na linguagem .NET;
- Desenvolver, testar e implementar;
- Elaborar e orientar atividades de correção e manutenção dos programas;
- Codificar e realizar os testes;
- Preparar documentação e produzir manuais de operação;
- Ajustar sistemas existentes para acompanhar as mudanças e necessidades dos usuários.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- 3 a 5 anos de experiência com .Net ((C, MVC, SQL Server e Entity Framework)
- Programação de Web Services e Windows Services;
- Programação de interfaces gráficas com HTML, Javascript e CSS;
- Conhecimentos no Framework Bootstrap;
- Conhecimentos em jQuery;
- Conhecimentos de modelagem de sistemas usando UML;
- Interpretação de diagramas UML para implementação de funcionalidades de sistema.

## Benefícios
- Contratação: PJ  (Indeterminado) + 13º (Sim, você ganha);
- Férias;
- 100% Home Office;
- Zenklub;
- Alura.

## Contratação
PJ

## Como se candidatar
Para se candidatar é só enviar seu currículo na própria vaga: https://jobs.quickin.io/plugaae/jobs/62fd1c2cd35c250014be8bb8

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
