### ISSUE TITLE
Desenvolvedor FULLSTACK 

### ISSUE THREAD

**Issue by MilenySouza** [backend-br/vagas#9926]
**VOCÊ JÁ PENSOU EM TRABALHAR EM UMA INDÚSTRIA MÉDICA?**
Se você gosta de desafios e quer fazer parte de uma empresa cujo principal valor é utilizar a tecnologia para melhorar a vida das pessoas, venha trabalhar conosco!

A **SELAZ** tem 10 anos de atividade no desenvolvimento e fabricação de produtos médicos ortopédicos, na cidade de São José dos Campos. Localizada no berço do setor aeronáutico e aeroespacial do Brasil, a SELAZ transporta tecnologias desse setor para a área médica, disponibilizando ao mercado nacional e internacional produtos de alta tecnologia para reconstrução óssea complexa. Com um forte apelo em pesquisa e parcerias com instituições e universidades, a SELAZ possui projetos em desenvolvimento envolvendo o uso de robótica, biomateriais e materiais compósitos avançados.
**_Visite nosso site https://www.selaz.com.br/_**

**Descrição da vaga:**
- Realizar atividades de desing de software.
- Programação Web (Banco de dados, Java, HTML, Java Script, PHP).
- Utilizar Frame Works de desenvolvimento.
- Modelagem UML (Enterprise Architect).
- Implementar soluções em tecnologia de informação (servidores locais e
em nuvem).
- Elaborar documentação.
- Fornecer suporte técnico.

**Requisitos:**
- 2 anos na função de Desenvolvedor Full Stack.
- Superior completo em Engenharia da Computação ou ciências da
computação.
- Curso de programação.
- Conhecimento em desenvolvimento de softwares.
- Inglês intermediário.

**Benefícios:**
- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 20,00/dia (Sodexo)
- Vale Transporte

**Regime de contratação:** CLT
**Nível:** Pleno
**Remuneração:** à combinar
**Local:** São José dos Campos

Por favor envie um email para adm@selaz.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor FullStack

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
