### ISSUE TITLE
[Híbrido/Campo Grande] Back-end Developer Java @EmpowerMind

### ISSUE THREAD

**Issue by BeatrizSantos01** [backend-br/vagas#9927]
## EmpowerMind

Somos uma empresa que oferece consultoria em recrutamento e seleção, benefícios, transformação cultural, mentoria e educação corporativa em todo o Brasil. 

## Descrição da vaga

Nessa oportunidade, você trabalhará com: 
- Desenvolvimento de aplicações web utilizando Java 8 com sringboot; 
- Banco de dados relacional SQL Server (2012 +); 
- É necessário ter noções básicas de front-end (HTML 5, CSS 3, Java Script e XML); 
- Versionamento do código utilizando JSON e GIT; 
- Aplicação mobile utilizando Java 8 (Front-end em React Native). 

## Local

Campo Grande-MS;

## Requisitos

**Obrigatórios:**
- JAVA 8;
- JAVA EE
- Sringboot;
- Microsoft SQL Server 2012 +;
- JSON e GIT;
- Apache Maven.

**Desejáveis:**
- Noções básicas em React Native;
- Conhecimentos em Angular versão 10 ou superiores.

## Benefícios

-  Vale alimentação de 700,00 reais por mês;
- Plano de saúde;
- Convênio Médico;
- Convênio Odontológico;
- Seguro de vida;

## Contratação

- Contratação CLT;
- Budget: De R$6.000,00 à R$8.000,00 (estamos abertos à negociação)

## Como se candidatar

Por favor envie um e-mail para bia@empowermind.com.br com seu CV anexado - enviar no assunto: Vaga Java
Ou, se candidate através do link: https://jobs.recrutei.com.br/empowermind-2/vacancy/29473-desenvolvedor-full-stack-java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: bia@empowermind.com.b

#### Alocação

- Alocado (A atuação é hibrida, em que as segundas-feiras são presencias na empresa, nos demais dias a atuação é remota).

#### Regime

- CLT;
- Jornada de trabalho: 07h30 às 11h30 e das 13h30 às 17h30.

#### Nível

- Pleno.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
