### ISSUE TITLE
[Barueri/São Paulo, SP] Back-End DotNet Developer @ Control 361

### ISSUE THREAD

**Issue by Hentadin** [backend-br/vagas#9933]
## Nossa empresa

A Control 361° é uma Startup especializada em desenvolvimento de software, trazendo soluções para o mercado com agilidade e praticidade. Temos mais de 30 anos de experiência, com uma equipe de especialistas prontos para trazer novas tecnologias ao mercado.

## Descrição da vaga

No seu dia a dia você vai:

- Mapear plano de ação e planejamento do projeto;
- Conduzir reuniões de projeto semanais de acompanhamento do projeto;
- Elaborar reportes semanais do time;
- Interpretar necessidades das áreas de negócio e definir implementação técnica;
- Definir, junto com as áreas de negócio e PO, indicadores chave para acompanhamento de resultados – Jira.
- Ter conhecimento das tecnologias utilizadas pela equipe;
- Ter capacidade de medir esforços e definir prazos de implementação;
- Solucionar problemas que surgem durante os projetos;
- Comunicar os objetivos do projeto para todos os membros da equipe envolvidos;
- Fornecer feedback, encorajamento e conselhos para o time;
- Habilidade de gerenciar conflitos e expectativas.

## Local

Presencial, Barueri - SP.

## Requisitos

*Obrigatórios:*

- 5 anos de experiência com C# (Framework .Net, Core ou ambos)
- 3 anos de experiência com Postgres

*Desejáveis:*

- conhecimentos em Microserviços
- conhecimentos em Postgres
- conhecimento de React

*Diferenciais:*

- conhecimento de Git
- conhecimento de PHP e Laravel

*Nossos Diferenciais:*

- Ambiente que estimula mudanças, inspiração e inovação;
- Possibilidade de crescimento profissional;
- Autonomia e liberdade para novas ideias;
- Um grupo incrível de pessoas dispostas a concluir objetivos;
- Vontade incansável de desenvolver novos projetos com foco (sempre) em facilitar a vida das pessoas;
- Um lugar onde temos consciência da importância de cada pessoa para a execução do nosso negócio (todos são cruciais);
- E, por último e não menos importante, um espaço que está esperando por você.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para cmohamed@somoslogin.com.br com seu CV anexado - enviar no assunto: Vaga DotNet

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: hdinis@somoslogin.com.br

#### Alocação

- Presencial

#### Regime

- PJ

#### Nível

- Pleno
- Sênior
- Especialista

#### Período

- Full time

**Comment by Hentadin** [comment]
Vaga ainda ativa

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
