### ISSUE TITLE
[INTERNACIONAL - BRAZIL] Back-end Python Developer SR @ Luxoft (DXC Technology)

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [backend-br/vagas#9934]
> Inglés: B2 Intermedio Superior <
Remote from Brazil

## About the company ##

LUXOFT

A design, data, and IT service development company represented in 21 countries with 17 000+ employees globally and headquarters in Switzerland.

The company provides end-to-end technology solutions for mission-critical systems, products, and services, and helps create data-fueled organizations, solving complex operational, technological, and strategic challenges. Its main aim and passion are building resilient businesses while generating new business channels and revenue streams, exceptional user experiences, and modernized operations at scale.

## Proyecto Descripción ##

El proyecto es para una de las principales firmas globales de gestión de inversiones. La firma está reuniendo un nuevo equipo especializado de ingenieros para rediseñar, construir, implementar y operar sus capacidades de informes de riesgos de próxima generación. El equipo trabaja conjuntamente con gestores de cartera, trading y operaciones. La cultura del equipo es emprendedora, donde el equilibrio entre el trabajo y la vida, la propiedad y la excelencia son muy valorados.

## Responsabilidades ## 

• Liderazgo de un equipo
• Desarrollo de nuevos microservicios basados en Python en AWS
• Ingeniería inversa de scripts
basados en MSSQL y R • Diseño y mejora de la arquitectura de soluciones • Participación en la
elicitación de requisitos, comunicación con clientes finales • Mejora de los
procesos
de desarrollo • Revisiones de código

## Habilidades ##

> Debe tener <

• Más de 3 años de experiencia en desarrollo en Python
• Sólida comprensión de algoritmos y estructuras
de datos • Sólido conocimiento de MSSQL, R
• Experiencia práctica con arquitectura
basada en microservicios • Orientado a resultados, puede entregar código de calidad con una respuesta rápida

> Agradable de tener <

• Antecedentes en ciencia de datos / análisis
• Competente en el trabajo con grandes conjuntos
de datos • Experiencia en la creación y modificación de sistemas
multilingües • Comprensión de las tecnologías de computación distribuida / en la nube y las tendencias informáticas emergentes
• Emprendedor y pensador crítico, se apropia de sus propios proyectos y hace sugerencias de mejora para toda la infraestructura
• Fuertes habilidades de comunicación escrita y oral.

## Contratação

3K EUR ~ 6K EUR

## Como se candidatar

Por favor envie um email para jose.castellani@castech.ai com seu CV anexado - enviar no assunto: Vaga Python

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
