### ISSUE TITLE
[Remoto - BRASIL] Back-end Ruby Developer SR @ CASTECH.ai

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [backend-br/vagas#9935]
## Sobre o cliente ##

https://pinpeople.com.br/

É uma plataforma de experiência do colaborador por meio de People Analytics e tecnologias inovadoras no mercado. Atua em parceria com grandes empresas como: Itaú Unibanco, Magazine Luiza, Claro, Cogna e MRV, 

## Responsabilidades do cargo ##

Dar suporte na descoberta e implementação de melhorias;
Garantir a utilização de técnicas e melhores práticas de Desenvolvimento de Software Web;
Contato direto e projetos multidisciplinares com os times de Data Science, Metodologia e Produto, participando da construção de produtos e processos;
Ajudar na melhoria contínua do processo de desenvolvimento de software;
Estudar novas tecnologias e como aplicá-las de forma a criar novas soluções ou melhorar as existentes;
Revisar código;
Comunicar-se com as partes interessadas da empresa para ajudar a refinar os requisitos.
Identificar problemas e trabalhar em conjunto com o time para resolvê-los.

## O que esperamos encontrar em você ##

Experiência em desenvolvimento de software com Ruby.
Ter experiência com tecnologia, em um ambiente de startup em pleno crescimento;
Vivência na construção de APIs e integração entre serviços.
Será considerado um diferencial experiência com produto SaaS.

## Contratação

13k ~ 16k PJ

## Como se candidatar

Por favor envie um email para jose.castellani@castech.ai com seu CV anexado - enviar no assunto: Vaga Ruby SR

Confira nosso Linkedin, vagas nacionais e internacionais: https://www.linkedin.com/company/castechbrzl/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
