### ISSUE TITLE
[Remoto] Back-end Developer C# (Júnior) na Hub Home Box

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9938]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/backend-developer-c-140025024?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A empresa <strong>Hub Home Box</strong> está procurando um <strong><ins>Back-end Developer C# Júnior</ins></strong> para compor seu time!</p>
<p>O Hub Home Box é um portal especializado em clubes de assinatura. Cada vez mais populares no Brasil, esses clubes nada mais são do que encomendas que os assinantes recebem mensalmente no conforto de suas casas. A diferença entre o clube de assinatura e uma encomenda comum é que os clubes são um serviço regular e dão aos assinantes experiências personalizadas de recebimento. Desde o detalhe da caixa até a seleção de produtos, a sensação que o cliente tem ao receber seu kit é a de ganhar um presente.</p>

## Hub Home Box: 
 <p>O <strong>Hub Home Box</strong> é um portal especializado em clubes de assinatura. Cada vez mais populares no Brasil, esses clubes nada mais são do que encomendas que os assinantes recebem mensalmente no conforto de suas casas.</p>
<p>A diferença entre o clube de assinatura e uma encomenda comum é que os clubes são um serviço regular e dão aos assinantes experiências personalizadas de recebimento. Desde o detalhe da caixa até a seleção de produtos, a sensação que o cliente tem ao receber seu kit é a de ganhar um presente.</p><a href='https://coodesh.com/empresas/hub-home-box'>Veja mais no site</a>

 ## Habilidades: 
 - C# 
- SQL 
- .NET
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos em C# e SQL; 
- Perfil dedicado e envolvido; 
- Gostar de aprender e buscar novos conhecimentos.
## Diferenciais: 
 - Conhecimentos em Photoshop; 
- Conhecimento em PHP.
## Benefícios: 
 - Vale alimentação/mês; 
- Voucher de benefícios dentro do site.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Back-end Developer C# (Júnior) na Hub Home Box](https://coodesh.com/vagas/backend-developer-c-140025024?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
