### ISSUE TITLE
[Remoto] Java Developer (Pleno) na Linked RH

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9939]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-java-pleno-112445823?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Linked RH</strong> busca <strong><ins>Java Developer (pleno)</ins></strong> para compor seu time!</p>
<p>Uma empresa de software e serviços totalmente direcionada à gestão de pessoas. Desenvolvedora do sistema de gestão de pessoas Join RH, há mais de 24 anos apoia seus clientes na constante evolução do RH.</p>
<p></p>
<p><strong>Responsabilidades e atividades:</strong></p>
<p>- Liderar o time de desenvolvimento de software.</p>
<p>- Definir a arquitetura de software.</p>
<p>- Acompanhar a evolução técnica das tecnologias.</p>
<p></p>

## Linked RH: 
 <p>Oferecemos apoio para que as pessoas se desenvolvam profissionalmente, através de plano de carreira, programa de mentoria, ambiente desafiador e oportunidades de aprendizados constantes.</p>
<p>Você utilizará metodologias ágeis, ferramentas/tecnologias de última geração, computação em nuvem e muito mais.</p><a href='https://coodesh.com/empresas/linked-rh'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Spring 
- API
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em desenvolvimento Java Web, API REST e Spring; 
- Experiência em arquitetura de software em geral; 
-  Experiência com testes automatizados.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Java Developer (Pleno) na Linked RH](https://coodesh.com/vagas/desenvolvedor-java-pleno-112445823?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by marcelolemes** [comment]
Pleno e Liderar time? Tem coisa errada aí hein...

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
