### ISSUE TITLE
[Remoto] Back-end Developer C# (Nível Pleno e Sênior) @EmpowerMind

### ISSUE THREAD

**Issue by BeatrizSantos01** [backend-br/vagas#9942]
## EmpowerMind
Somos uma empresa que oferece consultoria em recrutamento e seleção, benefícios, transformação cultural, mentoria e educação corporativa em todo o Brasil.

## Nessa oportunidade, você trabalhará com:

• .NET Framework;
• .NET Core;
• C#;
• Angular/AngularJs;
• JavaScript, HTML e CSS;
• Desenvolvimento de APIs REST;
• Driven Design (bounded contexts, aggregate roots);
• Programação orientada a testes;
• Noções de banco de dados (SQL Server).

## Local

100% Remoto;

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com C# e .Net Core;
- 2 anos de experiência com JavaScript, HTML e CSS.

**Desejáveis:**
- Conhecimentos em Angular/AngularJs;
- Conhecimento em testes automatizados.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para bia@empowermind.com.br com seu CV anexado - enviar no assunto: Vaga C# com o nível de senioridade;
Ou, entre em contato comigo via WhatsApp: https://wa.me/message/6WQB3ZQSRBRED1 (Recruiter Beatriz)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: bia@empowermind.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno e Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
