### ISSUE TITLE
[100% REMOTO] Senior Java Developer na Builders 🤟

### ISSUE THREAD

**Issue by RaissaBaltazar** [backend-br/vagas#9945]
**Conhece o Movimento Builders?**
Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios. 

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar! 

**Como será seu dia-a-dia?**
Como Java Developer você irá trabalhar em projetos de desenvolvimento de produtos digitais junto com grandes empresas, apoiado por uma equipe de tecnologia, designers e gestores. Buscamos pessoas desenvolvedoras apaixonadas pela linguagem Java, inconformadas por natureza e encantadas em gerar valor.

**Para cumprir esse desafio, você precisa dominar:** 
- Java 8+
- Springboot
- Unit Test
- JPA
- GIT
- Linux
- DDD

**Será um diferencial se você tiver também:** 
- Docker e Kubernetes
- Cloud
- Plataformas de CI/CD como Jenkins, ArgoCD, Github Actions
- Maven
- Arquitetura de Microsserviços
- Rest
- Design Patterns

**O que nós oferecemos?**
- Atuação 100% remota;
- Parceria com coworking em São Paulo;
- Webnars semanais para expandir ainda mais seu conhecimento;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Possibilidade de profit share de novos negócios.

**[Ficou com curiosidade de saber mais? #SóBora se inscrever?](https://bit.ly/3Sf7C13)**

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
