### ISSUE TITLE
[NY, USA] Python Developer @ Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [backend-br/vagas#9946]
Winter is coming GitHub community!❄ That's why at [Jobsity ](https://www.jobsity.com/) we're looking for Vue+Python Developer with +3 years of experience and a good English level to to join our pack to defend the Seven Kingdoms! We offer an indefinite time contract, payment in USD as contractor, 100% remote, FULL time and awesome benefits such as the following:

🔹15 business days of paid vacation
🔹3 extra off days per year
🔹Paid and flexible local holidays
🔹Unlimited PTOs (Paid time off)
🔹Budget for e-learning courses
🔹Financing program for equipment
🔹Bonuses for referrals and more

Would you like to find out more? ⚔

Drop me a line via [EMAIL ](angela.barboza@jobsity.com) or [LINKEDIN ](https://www.linkedin.com/in/angela-barboza/) and I'll share with you more info. so you can decide if you'd like to participate!

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
