### ISSUE TITLE
[Remoto] Back-end Developer PHP e Laravel Sênior na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [backend-br/vagas#9947]
## Nossa empresa

A Samba está buscando uma **pessoa Desenvolvedora Back-End Sênior (PHP e Laravel)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **PJ e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

- Desenvolver códigos seguindo recomendações;
- Realizar correção de bugs;
- Prezar pela qualidade dos códigos;
- Realizar code review.

## Local

Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- Experiência em PHP e Laravel;
- Banco de dados MySQL;
- Controle de versão Git;
- Familiaridade com as PSRs
- Conhecimentos sólido no paradigma OO.

**Desejáveis:**

- Experiência na criação de soluções escaláveis / serviços com grande concorrência;
- Serviços AWS;
- NodeJs;
- Ambientes virtualizados (docker);
- Mensageria / Sistemas de filas;
- Conhecimentos em design e arquitetura de software;
- Conhecimento das boas práticas da engenharia de software, ferramentas e processos.

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu CV anexado + pretensão salarial - enviar no assunto: Vaga PHP

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: **daiana.oliveira@sambatech.com.br**

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
