### ISSUE TITLE
[Remoto] Developer JAVA Pl/Sr @ DQR Tech

### ISSUE THREAD

**Issue by kerol-barros** [backend-br/vagas#9949]
## Nossa empresa
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

A DQR TECH está em busca de uma pessoa desenvolvedora Pl/Sr JAVA para atuar em Squad ágil no maior banco de Investimentos da América Latina.

## Local

De onde você quiser! Nossa vaga é para atuação 100% remota.

## Requisitos
- Java
- Spring Boot
- Oracle/PostgreSQL
- Rest
- SOAP
- Mensageria

## Benefícios

- Assistência médica e Odontológica para você + dependentes*;
- Auxílio flexível de R$880,00 para gastar como quiser;
- Auxílio-creche;
- Prêmio: Indique seus amigos, aqui sua indicação vale premiação em dinheiro*;
- Seu aniversário tem pizza: No dia do seu aniversário a pizza é por nossa conta, para que você comemore este dia especial com as pessoas que você gosta;
- Seguro de vida;
  * ver regra para dependentes com o nosso RH;

## Contratação

CLT

## Como se candidatar

Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: [kerolayne.barros@dqrtech.com.br](mailto:kerolayne.barros@dqrtech.com.br) - enviar CV anexo e no assunto colocar: Vaga - Desenvolvedor Java

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno/Sênior

**Comment by DaianeMFirmiano** [comment]
**ÓTIMA** vaga de JAVA!!!

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
