### ISSUE TITLE
[Rio de Janeiro - RJ][Remoto] Desenvolvedor Back-end / Product Manager na Bilo

### ISSUE THREAD

**Issue by penelopevitoria** [backend-br/vagas#995]
### **O que fazemos?**

Somos uma startup que traz uma solução Whitelabel para a venda de ingressos para o mercado de eventos, shows e festivais. Trabalhamos com grandes clientes na indústria da música e precisamos dos melhores em nosso time!

O nosso time está em crescimento e é formado por pessoas jovens e apaixonadas por empreendedorismo. E além de tudo, você pode operar em homeoffice!

### **Local**
Rua Gomes Carneiro, 52, Ipanema, Rio de Janeiro - RJ, 22071-110, Brazil

### **Benefícios**

- Remuneração compatível com o mercado;
- Bonificação de PLR;

###  **Requisitos Obrigatórios:**

- Gestão de produtos
- Experiência em PHP
- Ter boa comunicação
- Ser proativo(a)
- Perfil empreendedor
- Conhecimento em Metodologias Ágeis

### **Tecnologias obrigatórias**
PHP

### **Conhecimentos Desejáveis**
SCRUM

### **Contratação**
PJ e opção de trabalho remoto

### **Carga horária** 
Fulltime / HOMEOFFICE

### **Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 1 mês após uma entrevista.

### **Como se candidatar?**
Cadastre-se na GeekHunter para concorrer à vaga: http://bit.ly/2ZgKaoE

**Comment by garaujodev** [comment]
É realmente necessário o cadastro no Geek Hunter pra participar da vaga? Não há possibilidade de ser por email?

**Comment by penelopevitoria** [comment]
> É realmente necessário o cadastro no Geek Hunter pra participar da vaga? Não há possibilidade de ser por email?

Oi Gustavo. 

Como nós somos um Marketplace de match entre empresas e profissionais de TI, esse é o modelo que atendemos. Não faria sentido postar apenas a vaga. Ficou claro? Lembrando que todas as vagas que a GeekHunter divulga no GitHub são vagas de urgência alta, o que aumenta as chances de quem entrar primeiro. Qualquer dúvida estou à disposição :)

**Comment by garaujodev** [comment]
Perfeitamente. Não me entenda mal, mas são n vagas interessante pedindo para cadastrar em n "plataformas de Hunting" diferentes, o que é um processo bem lento e nada automatizado(importação por LinkedIn). De qualquer maneira vou concluir o meu cadastro na GeekHunter. Obrigado.

**Comment by penelopevitoria** [comment]
> Perfeitamente. Não me entenda mal, mas são n vagas interessante pedindo para cadastrar em n "plataformas de Hunting" diferentes, o que é um processo bem lento e nada automatizado(importação por LinkedIn). De qualquer maneira vou concluir o meu cadastro na GeekHunter. Obrigado.

Desculpe se não ficou claro o suficiente no anúncio. Entendo que a oferta possa não parecer clara em um primeiro momento, mas o nosso algoritmo favorece o match entre interesses e perfis. Logo, se você se candidatou para vagas em RJ, com skills específicas e não fechou com a empresa de interesse primário, receberá convites parelhos. 

Um abraço.
