### ISSUE TITLE
[Remoto] Backend Developer (PHP e Laravel) na Samba Tech

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9953]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-back-end-php-e-laravel-195224905?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Samba Tech</strong> busca <strong><ins>Backend Developer</ins></strong> para compor seu time!</p>
<p>A Samba está buscando uma pessoa Desenvolvedora Back End (PHP e Laravel) para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime PJ e 100% remoto. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>
<p></p>
<p><strong>Responsabilidades e atividades:</strong></p>
<ul>
<li>Desenvolver códigos seguindo recomendações;</li>
<li>Realizar correção de bugs;</li>
<li>Prezar pela qualidade dos códigos;</li>
<li>Realizar code review.</li>
</ul>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- Laravel 
- MySQL
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em PHP e Laravel; 
- Banco de dados MySQL; 
- Controle de versão Git; 
- Familiaridade com as PSRs; 
- Conhecimentos sólido no paradigma OO.
## Diferenciais: 
 - Experiência na criação de soluções escaláveis/serviços com grande concorrência; 
- Serviços AWS; 
- NodeJs; 
- Ambientes virtualizados (docker); 
- Mensageria/Sistemas de filas; 
- Conhecimentos em design e arquitetura de software; 
- Conhecimento das boas práticas da engenharia de software, ferramentas e processos.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Developer (PHP e Laravel) na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-back-end-php-e-laravel-195224905?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
