### ISSUE TITLE
[Remoto] Back-end Developer .NET na Icon It 

### ISSUE THREAD

**Issue by Thamme1** [backend-br/vagas#9954]
**Sobre a Icon IT**

A ICON Solutions é especialista em pessoas. Referência no mercado de recrutamento e seleção, profissionais altamente qualificados e no desenvolvimento de pessoas para todos os setores e níveis de mercado.

## Descrição da vaga

Responsável pelo desenvolvimento das soluções de backend, baseado nas discussões e propostas do time. Tudo isso alinhado com demais áreas, como segurança, por exemplo. Deverá respeitar as boas práticas e padrões de desenvolvimento do cliente.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
Necessário ter experiência com: 
- .net (Core/Framework)
- Conhecimentos de infra
- Práticas CI/CD
- Testes unitários e integrados
 Banco de dados (SQL Server, Docker)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para thamires.camacho@iconit.com.br com seu CV anexado - enviar no assunto: Vaga .NET

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- .NET
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
