### ISSUE TITLE
[Remote - Toronto, Canada] Fullstack Lead Engineer (Java/Kotlin/ReactJS) @ VeganHive

### ISSUE THREAD

**Issue by lemmks** [backend-br/vagas#9956]
## Who we are

We are a vegan-centric company with a mission to build a more compassionate and sustainable world. VeganHive empowers individuals and business owners through an online social platform in order to accelerate a global transition to vegan lifestyle. Join us and be part of this adventure with a creative, forward-thinking team. For the Animals, for the Planet, for all of Us.

## Job description

We're seeking a highly-motivated, flexible and talented backend focused Full Stack Engineer to expand our server-side team.

**Responsibilities:**
- Design, develop, test, refactor and scale, mostly backend, implementations of new and existing user-centric product features
- Collaborate effectively with other technology teams and architects to solve complex problems spanning their respective areas
- Diagnose, troubleshooting and bug fixes
- Stay up-to-date on relevant technologies, trends and opportunities

## Location

Remote

## Requirements

**Mandatory:**
- Deep understanding of OO, functional, event-based and reactive programming paradigms
- Strong knowledge of algorithms, standard data structures and async multi-threading
- Proficiency with back-end technologies such as Java/Kotlin, GraphQL and REST apis, Microservices, Kafka (or similar), SQL and NoSQL databases
- Experience working with third-party APIs and integrations
- Good knowledge of Git, Git Flow, Docker and DevOps
- Strong analytical, testing and debugging skills
- Experience with writing reliable and strategic automated unit and e2e tests
- Proactive and get things done spirit
- Language intermediate English speaker 
- Ability to work remotely, independently and as a team player with an offshore team

**Desired Abilities:**
- Understanding of Agile software development methodologies
- Proficiency with front-end technologies such as JS, ReactJS, NodeJS, HTML5 and CSS3
- Knowledge of infrastructure, networking and cloud such as K8S, GCP etc
- Experience with cross-browser, cross-platform, and design constraints on the web
- Understanding of security standards and software architecture
- Good communication skills and empathy

## Why you should work with us

- Start-up culture that values compassion, sustainability, innovation and personal growth
- Opportunity to solve crucial problems that matter within huge business potential
- Acquire lots of career opportunities and learnings of emerging cutting-edge techs
- Enjoy a fun remote work experience with friendly environment and flexible hours

## Contact

Please send CV to career@veganhive.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

#### Reqs
- Java
- Kotlin
- ReactJS
- Microservices
- Kafka
- GraphQL

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
