### ISSUE TITLE
[Chapecó/SC-Presencial/Campo] Consultor(a) de Implantação Desenvolvedor(a) C# @ TOTVS

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#9957]
## Nossa empresa

Nossa tecnologia dita o ritmo do mercado. Afinal, 25% do PIB brasileiro passa pelos softwares presentes em mais de 40 mil empresas clientes da TOTVS.
Para que isso aconteça precisamos ser ágeis, pois as coisas aqui acontecem em uma velocidade acima da média. No nosso dia-dia, aprendemos muito e muito rápido, em um ambiente leve, divertido e desafiador.
Nosso time de tecnologia tem a ousadia para colocar todo esse aprendizado e conhecimento em prática. Assim, transformando todos os setores da economia por meio da tecnologia.

## Descrição da vaga

Traçamos atividades, estratégias e objetivos para aumentar a produtividade de nossos clientes, melhorar a qualidade de nosso serviço e expandir nossas operações.
Tudo isso confirma quem somos como uma empresa dedicada a resultados, inovação, tecnologia e pessoas!

Responsabilidades
-Desenvolver para todos os módulos dos produtos TOTVS;
-Fazer implantação de produtos;
-Corrigir erros e bugs.

## Local

Chapecó/SC-Presencial.

## Requisitos

O que você precisa conhecer
-Conhecimento em desenvolvimento em linguagens de programação Delphi;
-ADVPL;
-Java ou Javascript;
-SQL;
-C#;
-Disponibilidade para viagens.

Pra ter aquela vantagem extra
-Experiência na área de Desenvolvimento de Software, visão sistêmica de um ERP;
-Desenvolvimento de Sistema em Delphi, PHP, JSP. Desenvolvimento de módulos de gestão empresarial;
-Parametrização de processos em sistemas ERP Totvs;
-Treinamentos de sistemas aos usuários;
-Migração de bases de dados;
-Planejamento e controle de cronogramas e atividades dos projetos;
-Interface com clientes do negócio e desenvolvedores para captura de requisitos e solicitação de mudanças no sistema existente.

## Benefícios
-Vale Refeição;
-Vale Alimentação;
-Mobilidade;
-Plano de Saúde;
-Plano Odontológico;
-Seguro de Vida;
-Reembolso de despesas.

## Contratação

CLT.

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/6244a12756a972001eaf0da4?r=srch&c=4740

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista (ou feedback negativo pelo E-mail).

#### Alocação
- Alocado
- Presencial
- Campo
- Viagens

#### Regime
- CLT

#### Nível
- Pleno

#### Período
- Full time

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
