### ISSUE TITLE
[Remoto] Back-end Developer Ruby On Rails @ Lyncas

### ISSUE THREAD

**Issue by ghost** [backend-br/vagas#9958]
## Company

Lyncas are a young company that seeks excellent service for our clients, respecting each team professional, supplier and customer.
Dissatisfied with a market that values volume, we seek standards of quality to connect people and systems and promote an incredible digital journey!

## Job Description

We’re after experienced Ruby on Rails Developer to join our customers cross-functional, agile, international NZ team.

-Ruby on Rails Sr Developers who want to engineer a SaaS platform that continues to scale.
-Someone who’s comfortable working on a large Ruby on Rails application, from building backend business logic through to a complete web experience.
-Someone who thrives in a fast-paced agile environment, can adapt to change in processes and features, and communicates effectively with both technical and non-technical people.
-Not just interested in writing code, you’ll be able to jump in to diagnose production issues and write tests to ensure the quality of your code.

## Local

100% remote.

## Qualifications

-Technically you would know the ins and outs of the following technology: Ruby, Ruby on Rails, SQL, PostgreSQL, HTML, HAML, JavaScript.
-Experience with API with a preference for OpenAPI.
-Advantageous for anyone with Microservices, MariaDB, or AWS experience.
-Advanced English.

## Benefits

-Salary/Fixed Remuneration PJ R$.
-Psychological Reception.
-15 days of vacation (PJ).
-Happy Our On Line.
-Academy of Knowledge.

## Contract

PJ.

## How to apply

https://vagas.hunterco.com.br/job/62c470634f346b001fc0d388?c=4740 

https://www.linkedin.com/jobs/view/3250118058

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
