### ISSUE TITLE
[Lisboa/Portugal] Analista/Programador Mainframe @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [backend-br/vagas#9959]
# Integer Consulting
A Integer Consulting é uma empresa portuguesa de consultoria em tecnologias de informação. Somos especialistas em serviços de IT outsourcing, software, projetos de nearshore e desenvolvimento à medida. Somos parceiros dos principais players tecnológicos a nível mundial e trabalhamos com empresas nacionais e multinacionais de diversos setores de atividade. A maioria dos projetos em que participamos são em Portugal, no Brasil e um pouco por toda a Europa. O que nos diferencia é o talento tecnológico e a experiência das pessoas que fazem parte da equipa e que integram os nossos projetos.

Estás à procura de novas oportunidades na área de IT? Temos novidades para ti!

## Este pode ser o desafio perfeito, se tiveres:
- Experiência em DB2;
- Experiência em desenvolvimento em Cobol (Batch/Online);
- Conhecimentos em JCL;
- Conhecimentos em TSO/ISPF e EOS;
- Conhecimentos em TDD\BDD;
- Conhecimentos em Continuous Delivery.

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para [bruno.carvalho@integer.pt](mailto:bruno.carvalho@integer.pt?subject=Resposta%20Oferta%20Net-Empregos:%20Analista%20Programador%20Mainframe)

Para saber mais como protegemos a tua privacidade, consulte a nossa Política em [www.integerconsulting.pt](http://www.integerconsulting.pt/)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se fora do padrão fornecido na issues. Faltam informações.
