### ISSUE TITLE
[Backend Engineer PHP com inglês para conversação] Remoto para Portugal

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9961]
[Backend Engineer PHP com inglês para conversação] Remoto para Portugal (trabalhar no fuso horário de Portugal). Salário aplicado em torno de 2K Euros a 3.5K Euros. 

Software Consulting founded with the mission to inspire the connection of technology with people, fostering the best of our professionals through our expertise in finding and attracting the best talent for the best projects.

About The Job:

What You’ll do:

●      Design, test, build, ship and maintain e cient, reusable, and reliable object-oriented PHP8 code.

●      You provide and enhance tools to automate processes and ultimately improve our development environment.

●      Ensure the best possible performance, quality, and responsiveness of the applications.

●      Help maintain code quality, organization, and automatization.

Experience and Skill Requirements

●      Strong object-oriented PHP skills, experience with MVC frameworks

(Symfony is a plus).

●      Experience in designing, building, testing and shipping web applications.

●      Automated testing, clean code and code coverage is just as important to you as production code.

●      Exceptional experience with various design and architectural patterns, algorithms, and data structures (experience with microservices is valued).

●      Great English communication skills.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
