### ISSUE TITLE
[Remoto ou semipresencial em Colombo/PR] Back-end Developer Júnior @ BNE - Banco Nacional de Empregos

### ISSUE THREAD

**Issue by israelaandrade** [backend-br/vagas#9963]
## Nossa empresa

Aqui no BNE a natureza é de tecnologia e inovação, somos uma empresa de tecnologia com enfoque em RH.

## Descrição da vaga

O profissional atuará na criação e aplicações web, em projetos de alta de manutenção no cenário nacional.

## Local

Remoto ou semipresencial em Colombo/PR.

## Requisitos

**Obrigatórios:**
- Conhecimentos júnior C# [ASP.NET](https://asp.net/) CORE
- Conhecimentos júnior de MVC
- Servidor SQL

**Desejáveis:**
- Conhecimentos em processos assíncronos
- Desenvolvimento de sistemas em nuvem (Azure)
- SCRUM
- Angular
- Servidor de identidade

**Diferenciais:**
- Quarta do CS, onde os devs se reúnem após o serviço para jogar CS e interagirem.
- Tecnologias recentes do mercado
- Oportunidades de crescimento
- Oportunidades de reconhecimentos

## Contratação

PJ a combinar.

## Como se candidatar

Por favor envie uma mensagem pelo WhatsApp, enviar no assunto: Vaga Back end (GitHub) através de nosso Linktree: https://linktr.ee/ia_vagaserecrutamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Contato em caso de não haver resposta: Por favor envie um email para: [israelaandrade@bne.com.br] com seu CV anexado - enviar no assunto: Vaga Back end (GitHub)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

![Back pleno (2)](https://user-images.githubusercontent.com/107878719/186955000-6475f2ae-b0e9-4dba-995d-745350fbdf7a.png)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
