### ISSUE TITLE
[Remoto ou semipresencial em Colombo/PR] Back-end Developer Sênior @ BNE - Banco Nacional de Empregos

### ISSUE THREAD

**Issue by israelaandrade** [backend-br/vagas#9964]
## Nossa empresa

Aqui no BNE a natureza é de tecnologia e inovação, somos uma empresa de tecnologia com enfoque em RH.

## Descrição da vaga

O profissional atuará na criação e aplicações web, em projetos de alta manutenção no cenário nacional.

## Local

Remoto ou semipresencial em Colombo/PR.

## Requisitos

**Obrigatórios:**
- Conhecimentos sênior C# [ASP.NET](https://asp.net/) CORE
- Conhecimentos sênior de MVC
- Servidor SQLs

**Desejáveis:**
- Conhecimentos em processos assíncronos
- Desenvolvimento de sistemas em nuvem (Azure)
- SCRUM
- Angular
- Servidor de identidade

**Diferenciais:**
- projetos opensource

**Diferenciais:**
- Quarta do CS, onde os devs se reúnem após o serviço para jogar CS e interagirem.
- Tecnologias recentes do mercado
- Oportunidades de crescimento
- Oportunidades de reconhecimentos

## Contratação

PJ a combinar.

## Como se candidatar

Por favor envie uma mensagem pelo WhatsApp, envie no assunto: Vaga Back end (GitHub) através de nosso Linktree: https://linktr.ee/ia_vagaserecrutamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Contato em caso de não haver resposta: Por favor envie um email para: [israelaandrade@bne.com.br] com seu CV anexado - enviar no assunto: Vaga Back end (GitHub)

Rótulos

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

![Back pleno (4)](https://user-images.githubusercontent.com/107878719/186955874-dc8836dc-30a1-4d4c-ae6d-954a066b372c.png)

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
