### ISSUE TITLE
[São Paulo-SP] Arquiteto de softwares @Icon IT 

### ISSUE THREAD

**Issue by Thamme1** [backend-br/vagas#9965]
## Descrição da vaga

Oportunidade para Arquiteto de Software, será responsável por avaliar e recomendar ferramentas, tecnologias e processos para garantir a maior plataforma de produtos de qualidade;
Colaborar com organizações parceiras, garantir qualidade e usuários finais para produzir soluções de software de ponta;
Interpretar os requisitos dos negócios para articular as necessidades do negócio a serem abordadas

## Local

Exemplo: Hibrido - São Paulo - Vila Olímpia (3x)

## Requisitos

**Obrigatórios:**
- Formação superior completa em Ciência da Computação, Engenharia ou correlatas;
- Experiência como arquiteto de software;
- Experiência no desenvolvimento de softwares e codificação (Java, C#, .NET, etc.);
- Excelente conhecimento de projeto e arquitetura de softwares e aplicativos;
- Conhecimento dos principais frameworks de EA (TOGAF, SOMF entre outros);
- Excelente conhecimento de UML e outros métodos de modelagem;
- Compreensão dos princípios de garantia de qualidade de softwares.

**Desejáveis:**
- Inglês avançado

## Benefícios

- Plano de saúde
- Seguro de vida
- VR/VA 

**Diferenciais:**
- Empresa Global - Grande oportunidade de atuar com times de grande visibilidade internacional

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para thamires.camacho@iconit.com.br com seu CV anexado e pretensão CLT
Enviar no assunto: Arquiteto de Software

#### Regime
- CLT

#### Nível
- Sênior

#arquiteto

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
