### ISSUE TITLE
[REMOTO] DEV NODE SÊNIOR | DB1 GROUP  

### ISSUE THREAD

**Issue by talentos-db1** [backend-br/vagas#9969]
## Descrição da vaga  
- Nessa vaga, você terá a missão de contribuir com o time em um projeto de banco digital e mercado financeiro, com desenvolvimento Node, atuando com práticas de desenvolvimento ágil e boas práticas de programação, com pair programming, CI/CD e TDD. Verá a sua solução impactando as grandes e pequenas transações de compra e venda no mundo digital, inclusive as suas!   

## Requisitos  

**Obrigatórios:**  
- Experiência desenvolvendo em Node JS;  
- Experiência com arquitetura baseada em microsserviços;  
- Experiência com Docker, Kubernetes; 
- Experiência com controle de versionamento Git;  
- Conhecimento em banco de dados relacionais e não relacionais. 
  

**Diferenciais:**  
- Conhecimento em React  
  

## Nossa empresa  
- Somos um grupo empresas de tecnologia, nascido no interior do Paraná, com mais de 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado, como na DB1 Global Software (DGS), que é a nossa SoftwareHouse.   
- Aqui trabalhamos com a transformação digital alinhada a uma entrega de valor aos nossos clientes. Aqui, entendemos que o profissional e pessoal andam juntos, por isso, cultura importa tanto quanto conhecimento técnico. A DB1 é uma empresa de tecnologia com padrão global de qualidade, mas a nossa principal preocupação vai além de software: queremos melhorar a vida das pessoas.   
-  Somos mais de 750 colaboradores em todo o Brasil e LatAm. Atuamos em modalidade remota desde 2017!   
- Movidos por desafios diários, sempre buscamos uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos(as) aqui tem autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de time. DB1 é pra quem não quer ser mais um!  
- Acreditamos na construção de uma empresa para durar gerações e aqui consideramos todas as pessoas candidatas. Por isso, não fazemos distinção de cor, raça, religião, identidade de gênero, orientação sexual, idade, estado civil ou pessoa com deficiência (PcD).  
  

## Benefícios  
- Cartão de benefícios flexíveis (Alimentação, Mobilidade, Qualidade de Vida, entre outros);  
- Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;  
- Auxílio home office;  
- Horários flexíveis!;  
- Gympass (opcional);  
- Plano odontológico (opcional);  
- Seguro de Vida (opcional);  
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;  
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do Mestre dos Códigos.  
- Comitês para você participar e contribuir com as melhorias dos processos do Grupo DB1 ou contribuir com a comunidade: Comitês de Boas Práticas de Gestão de Pessoas (CBPGP), Comitê técnico, Comitê de Responsabilidade e Desenvolvimento Socioambiental (CORDS)  
  

## Como se candidatar  
- [Clique aqui para se candidatar na vaga](https://jobs.kenoby.com/vagas-db1-group/job/pessoa-desenvolvedora-node-senior/62f248e9c5a660627df14618?utm_source=github)  
Ou envie seu currículo para talentos@db1.com.br

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
