### ISSUE TITLE
[Campo Bom/RS] Back-end Developer @ Iniciativa RH TI

### ISSUE THREAD

**Issue by Kerolyn-Rocha** [backend-br/vagas#9970]
## Iniciativa RH TI

Empresa com mais de 30 anos de experiência no Brasil, EUA, e América Latina atuando em mercados como mercantil, construção civil, financeiro e agro

## Local

Atuação em modelo Híbrido em Campo Bom/RS (1 a 2x na semana presencial na empresa).

## Requisitos

**Obrigatórios:**
- Experiência com PHP;
- Experiência em GIT;
- Desenvolvimento e consumo de APIs (REST);
- Experiência com Framework Laravel;

**Desejáveis:**
- Conhecimentos em VS Code;
- Conhecimento em Visual DevOps;

## Benefícios

- Plano de saúde Unimed;
- Plano Odontológico;
- Seguro de vida;
- VR de R$ 26,51/dia;
- VT;
- Day Off
- Acesso a plataforma Alura;
- Acesso a plataforma Cíngulo.

## Contratação

R$ 4.300 CLT

## Como se candidatar

Por favor envie um email para rhti@iniciativa.com.br com seu CV anexado - enviar no assunto: Vaga Dev PHP Campo Bom/RS
Ou manda uma mensagem no WhatsApp: https://bit.ly/3P5mT1K com o seu nome e vaga de interesse.

#### Nível
- Júnior
- Pleno

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
