### ISSUE TITLE
[Rio de Janeiro] Back-end Developer @ Buus

### ISSUE THREAD

**Issue by aikeda** [backend-br/vagas#9971]
![](https://buus.s3-sa-east-1.amazonaws.com/images/Facebook+Cover.png)

## Sobre a Buus
> Tenho 3.000 funcionários que precisam chegar até uma fábrica. Qual a menor frota que preciso contratar para fazer todos os deslocamentos em menos de 1h30? Qual o ônibus devo pegar e por onde ele passa?

Organizar e manter a logística do **transporte de passageiros** em áreas mal servidas pelo transporte público, sem tecnologia, é demandante e custoso para as empresas. E o que todos querem é eficiência nos processos e humanidade ao lidar com os passageiros.

Nós da **[Buus](https://www.linkedin.com/company/5020309)**, somos uma empresa de **tecnologia** e **mobilidade** focada na gestão do transporte de colaboradores. E fazemos isso através da nossa plataforma que atende empresas de óleo & gás, manufatura, TI, esportes e outros segmentos. Listadas na Fortune 500, no Brasil e no mundo (LATAM). 

**Estamos procurando talentosos e criativos desenvolvedores Python** para juntar-se à nossa equipe dinâmica aqui na Buus.
Como desenvolvedor python, você será responsável por codificar, projetar e implantar projetos que trazem funcionalidades novas e inovadoras ao mercado de mobilidade.

Especificamente, você será responsável para:

1. Escrever um código Python reutilizável, testável e eficiente;
2. Desenvolver código de aplicação back-end;
3. Desenvolver código para soluções e integração de sistemas;
4. Desenvolver código de engenharia e análise de dados;
5. Desenvolver código de visualização de dados.

## Qualificações mínimas?

- Experiência comprovada em Python por pelo menos **dois anos**;
- Nível superior em ciências da computação, engenharia, ou campo relevante com experiência em Python;
- Fortes habilidades de resolução de problemas;
- Boa capacidade analítica;
- Uma atitude proativa e batalhadora;
- Boas habilidades interpessoais e de comunicação;

## Habilidades requeridas

- **Python**

**Experiência ou familiaridade em algumas das bibliotecas abaixo (não em todos):**

- Engenharia e análise de dados (pandas, NumPy);
- Visualização de dados (por exemplo, matplotlib, seaborn, Bokeh/Plotly);
- Software para dados geoespaciais e (Geopandas, Networkx);
- Framework Django;
- pytest e pacotes de testes similares;
- Prática em versionamento de código com Git;

- Docker;
- Bancos de dados (ex. Postgres, Redis, MongoDB, etc.);
- Job queue (ex. RQ);
- AWS SDK (ex. boto3);
- OOP;
- Javascript.

## Onde ficamos?
Flamengo, Rio de Janeiro &#127958;

## Onde trabalharei?
Híbrido: a ideia é fazer algo misto entre presencial e remoto.

## O que buscamos?
Pessoas com disposição (!), curiosidade e certa bagagem (pleno). Sem apego à um tecnologia ou linguagem e que buscam um conhecimento amplo sobre a tecnologia e suas práticas (arquiteturas, patterns, testabilidade, algoritmos, DB, etc).

## Modelo de contratação
CLT

## Remuneração & Benefícios
- Remuneração competitiva - gostaríamos de ouvir sua pretensão salarial;
- Trabalho flexível, um híbrido entre remoto e presencial;
- Plano de saúde;
- Vale refeição ou vale alimentação;
- Day off para o seu aniversário.

## Contato
Mande seu e-mail com CV para: vagas@buus.com.br

**Labels**
- Híbrido
- CLT
- Backend
- Geospacial
- Dados
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
