### ISSUE TITLE
[Hibrido / Barueri/ SP] Backend Developer Java (Estágio) na Assesso

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9976]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/estagio-em-desenvolvimento-backend-java-173024227?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Assesso</strong> busca <strong><ins>Backend Developer Java (Estágio)</ins></strong> para compor seu time!</p>
<p>A ASSESSO é líder no segmento de Qualidade e Governança de Dados, possui certificação do MIT e uma ferramenta própria chamada Datacare, que faz a gestão de dados dos nossos clientes: grandes empresas de diversos segmentos.</p>
<p>Estamos em busca de uma pessoa para apoiar o time de Produtos na manutenção, evolução e desenvolvimento de novos módulos do DataCare.</p>

## Assesso: 
 <p>A Assesso é uma empresa de tecnologia com mais de 40 anos de atuação no mercado brasileiro.</p>
<p>Atualmente, a Assesso é referência no mercado brasileiro de Qualidade e Governança de Dados, aí incluídas as áreas de Big Data e MDM – Master Data Management, tendo evoluído à frente do mercado com a moderna visão da informação como um valioso ativo das empresas, merecendo estrutura especializada para a sua contínua evolução e qualidade.</p><a href='https://coodesh.com/empresas/assesso'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Lógica de Programação 
- Excel
## Local: 
 Barueri/ SP
## Requisitos: 
 - Cursando a partir do 2º Semestre do curso de Análise e Desenvolvimento de Sistemas ou cursos correlatos; 
- Habilidade em Raciocínio Lógico e Lógica de Programação; 
- Conhecimento teórico da linguagem de programação Java; 
- Interesse em se desenvolver profissionalmente como Desenvolvedor Backend; 
- Inglês técnico.
## Diferenciais: 
 - Projetos pessoais ou acadêmicos relacionados ao desenvolvimento em Java, e conhecimento da linguagem Python serão considerados como diferenciais.
## Benefícios: 
 - Seguro de Vida; 
- Auxílio transporte; 
- Gympass.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Backend Developer Java (Estágio) na Assesso](https://coodesh.com/vagas/estagio-em-desenvolvimento-backend-java-173024227?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
Estágio
#### Categoria
Back-End

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
