### ISSUE TITLE
[REMOTO] NodeJS Sênior Developer @Eureka Labs

### ISSUE THREAD

**Issue by Marianagana** [backend-br/vagas#9978]
## EUREKA LABS

Se você busca autonomia e evolução contínua, quer trabalhar em um lugar bom e que te ofereça muitas oportunidades: A Eureka é o lugar para você!

## Descrição da vaga

-Desenvolvimento de aplicações backend em NodeJS com API REST;
-Implementação de testes unitários ou funcionais;
-Apoio aos líderes no entendimento técnico de sistemas e integrações;
-Apoio aos líderes para a realização de estimativa para a construção de novos módulos em diferentes sistemas;
-Suporte e mentoria a outros membros do time.

## Local

REMOTO

## Requisitos

-Experiência com projetos com regras e requisitos complexos;
-Experiência demonstrável de atuação em uma solução de médio/grande porte;
-Experiência com desenvolvimento de APIs em Node;
-Experiência com elaboração de solução a nível arquitetural (modelagem de banco, serviços, etc);
-Experiência com controlador de versionamento (Git e afins);
-Experiência com banco de dados relacionais e não relacionais;
-Experiência com arquitetura REST;
-Experiência e aplicação dos conceitos do SOLID e Clean Code;
-Suporte e mentora o desenvolvimento das equipes;
-Experiência em liderar, formal ou informalmente, iniciativas de desenvolvimento;
-Experiência com CI/CD;
-Experiência com configuração de Docker;
-Experiência com testes unitários, funcionais e de integração;
-Boa comunicação verbal e escrita.

## Contratação

PJ.

## Como se candidatar

Envie seu currículo para rh@eurekalabs.com.br.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
