### ISSUE TITLE
[Remoto] Full Stack REACT/NODE Developer @Eureka Labs

### ISSUE THREAD

**Issue by Marianagana** [backend-br/vagas#9979]
## EUREKA LABS

Trabalhando em uma empresa antiquada? Com sistemas legados? E parece que ninguém ouve o que você fala?
A Eureka Labs está em crescimento! Tem uma cultura incrível, com muita flexibilidade e oportunidades 100% remotas.

Buscamos Desenvolvedores(as) Pleno e Sênior para trabalhar com tecnologia de ponta em projetos inovadores.

## Descrição da vaga

-Desenvolvimento de aplicações utilizando as tecnologias ReactJS; NestJS e PostgreSQL
-Criação e Manutenção de Endpoints na API para comunicação com o front;
-Ser parte de um time multidisciplinar;

## Local

REMOTO

## Requisitos

-Experiência em NodeJS e frameworks, preferência NestJS
-Experiência em ReactJSExperiência com banco de dados relacional, preferência PostgreSQL
-Paixão pelo que faz e muito interesse em participar de discussões técnicas ou de negócio.

**DIFERENCIAL 

-Conhecimentos em Docker
-Otimização de consultas em banco de dados
-Gostar de Typescript!
-Ter mente aberta, integridade e transparência

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@eurekalabs.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
