### ISSUE TITLE
[Brooklin SP] Back-End Developer (Java/Kotlin/Node.js) na Tecer

### ISSUE THREAD

**Issue by tomas-itrecruiter** [backend-br/vagas#9981]
## Tecer
Consultoria de RH recrutando para empresa de tecnologia que faz parte de um grupo de 7 empresas de tecnologia cujo objetivo é trazer negócios tradicionais para a nova economia. Fazem parte de seu ecossistema Fintech, Lawtech, Marketplace de Serviços, Logtech e Cloudtech. . Procuramos profissionais para Desenvolvimento Back End. Ambiente descontraído, criativo e oportunidade de crescimento acelerado

## Descrição da vaga
Buscamos makers, hunters e profissionais Backend preparados para resolver problemas e que gostem de desafios e tasks diversas das diferentes empresas, onde em cada projeto você obterá mais conhecimento e experiência.

## Local
Brooklin - SP

## Requisitos
**Obrigatórios:**
● Requerido conhecimento nas linguagens de Kotlin, Java, Node.js;
● Experiência de no mínimo 3 anos com APIs RESTful e Microsserviços;
● Experiência de no mínimo 3 anos com AWS;
● Experiência de no mínimo 3 anos com sistemas financeiros;
● Necessário conhecimento avançado em criptografia e comunicação criptografada (HTTPS, mTLS, TLS, JWT, JWKS, XML Assinado, OAuth, OpenID);
● Necessário conhecimento intermediário de infraestrutura e containers (VPN, VPC, Containers, Proxy Reverso, Enfileiramento, Networking, Serverless);
● Experiência de no mínimo 3 anos com bancos de dados relacionais e não relacionais;

**Desejáveis:**
● Desejável Inglês intermediário ou suficiente para leitura técnica.

**Diferenciais:**
● Pessoas curiosas, corajosas e colaborativas e que gostam de aprender, com perfil proativo e resiliente;

## Benefícios
- ...

## Contratação
PJ
## Remuneração
A combinar, considerando pretensão

## Como se candidatar
Entrar em contato por Whatsapp 81 988564321 ou enviar e-mail com CV + Pretensão Salarial para tomas.psi2020@gmail.com

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels
- Backend
- São Paulo
- Alocado
- PJ
- Sênior
- Especialista
- Java
- Kotlin
- Node

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
