### ISSUE TITLE
[REMOTO] Back-end Developer @ Bento Ltd

### ISSUE THREAD

**Issue by renannery** [backend-br/vagas#9982]
## Nossa empresa

Olar! Bento é uma empresa caribenha com sotaque brazuca, estamos em crescimento e buscamos desenvolvedor (a) back-end com experiencia comprovada em Node.

## Descrição da vaga

Manutenção de nossas APIs e do ambiente backend que é Google Cloud.

## Local

Remoto - Cayman Islands

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em Node (pelo menos 1 ano)
- Experiência com Typescript
- Experiência com Firebase (Firestore, Functions)
- Experiência em manutenção de sistemas complexos
- Experiência com Google Cloud
- Experiência com Cloud Run
- Experiência com BigQuery

**Desejáveis:**
- Capacidade de julgar se um design é feio ou bonito.
- Desenvolvimento de aplicações escaláveis
- Experiência com NestJS
- Acostumado(a) com desenvolvimento ágil através de processos como Scrum/Kanban
- Comunicação bem estruturada. Você deve ter opiniões fortes, mas saber argumentar em cima delas, e manter a cabeça aberta para mudar de opinião na construção de soluções com o time

**Diferenciais:**
- Experiência com JSON AP
- Experiência com WebSockets e SSE (Server Side Events)

## Benefícios

- Flexibilidade de Horários
- Viagem anual ao caribe

## Contratação

- A combinar

## Como se candidatar

Se você achar que possui 50% das coisas listadas acima, manda um e-mail para nery@bento.ky

## Labels
Valores aproximados em Reais (BRL)

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- 💰 3k-5k
- 💰 5k-10k

#### Alocação
- Remoto

#### Regime
- A combinar

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by ferreirase** [comment]
Entrei em contato, tenho bastante interesse e fit, espero poder ajudar.

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
