### ISSUE TITLE
[Desenvolvedor(a) Senior ou Tech Lead de Jogos - Godot e Python] - PRESENCIAL Moema - São Paulo

### ISSUE THREAD

**Issue by ErickaMB** [backend-br/vagas#9987]
[Desenvolvedor(a) Senior ou Tech Lead de Jogos - Godot e Python] - PRESENCIAL Moema - São Paulo - CLT - Salário a combinar.

Quem somos

Somos uma empresa com atuação global especializada no desenvolvimento de software para jogos. Líder em nosso setor, trabalhamos com uma série de tecnologias e plataformas: software embarcado, máquinas físicas, web e mobile. Nossa missão é levar inovação e novas experiências aos jogadores.

Atribuições do cargo

Desenvolvimento e manutenção de backends de jogos e sistemas administrativos em Django/Python, Java e frontends em Godot engine;
Criação e consumo de APIs e Rest;
Integração de ambientes multi-linguagem;
Liderara de modo técnico a equipe de desenvolvedores;
Onboarding técnico e desenvolvimento da equipe;
Evolução tecnológica das soluções;
Apoiar a equipe em desafios técnicos, atuando como facilitador na resolução de problemas e auxiliando-os na aplicação de boa práticas, arquiteturas, ferramentas e fluxos de trabalho;
Assegurar a qualidade, eficiência e cumprimento de prazos das entregas do time;
Code review.

Requisitos

Experiência prévia em liderança de pessoas em equipes de desenvolvimento e com perfil hands-on;
Foco em resultados e comprometimento com qualidade e datas de entrega;
Domínio de desenvolvimento Python/Django e Java (mínimo de 5 anos de experiência)
Experiência com Godot engine;
Experiência com banco de dados;
Formação ou experiência comprovada em ciência da computação, engenharia da computação, análise de sistemas ou desenvolvimento de jogos;
Boas habilidades de comunicação (oral e escrita);
Esforço para atingir os objetivos, atitude positiva, proatividade, resiliência, respeito, ética para trabalhar em grupo e paixão pelo que faz.

Desejáveis

Experiência prévia de desenvolvimento de jogos digitais;
Portfólio de jogos publicados em plataformas web, mobile ou embarcados;
Conhecimento ou certificações em metodologias ágeis (Scrum, XP);
Vivência em sistemas embarcados e sistema operacional Linux;
Conhecimento de Docker, Jenkins, Nexus e Gilt;
Habilidade em UX e UI;
Forte base técnica em sistemas, plataformas de jogo, game engines e arquitetura clienye-servidor (on premises e cloud);
Conhecimento em Cloud como infraestrutura (Amazon AWS e Azure)
Conhecimento em bancos de dados MySQL e Azure)
Conhecimento em C e C++

Idioma

Inglês ou espanhol avançados são diferenciais

Principais benefícios

Contratação CLT;
Vaga Presencial - Região de Moema- SP (próximo à estação Moema – Linha Lilás);
Jornada de Trabalho Flexível;
Seguro de Vida - 100% custo empresa;
Assistência Médica Bradesco - 100% custo empresa;
Assistência Odontológica Bradesco;
VR Flex: R$880,00;
Auxílio creche - Filhos até 5 anos;
Vale Transporte.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
