### ISSUE TITLE
[Fechado][Rio de Janeiro] Back-End Developer JR [Nova Aliança Imóveis]

### ISSUE THREAD

**Issue by rafaelso86** [backend-br/vagas#999]
## Descrição da vaga

Tá procurando Job?

O que acha de vir trabalhar em ambiente criativo, participar da mirabolação de novos serviços e soluções e, de quebra, fazer parte de uma equipe multidisciplinar formada por gente bonita, elegante e sincera? Aqui, você trabalhará criando soluções web, como aplicativos, intranet e websites. Pra isso, a gente precisa que você:

## Local

Ficamos no centro da cidade do Rio de Janeiro.

## Requisitos
- Tenha mais de um ano de experiência como profissional;
- Tenha experiência em desenho ou manutenção de banco de dados;
- Trabalhe com APIs e integração entre plataformas;
- Tenha interesse em se desenvolver com PostgreSQL, MySQL, PHP, Node.js e REACT;
- Saiba trabalhar em equipe;

**Diferenciais:**
- Boa leitura em inglês;
- Experiência com projetos de estruturação de dados;

## Contratação

CLT 

## Benefícios
- 13° salário;
- Férias;
- Vale transporte;
- Vale refeição;
- Após o período de experiência, plano de saúde integral;
- Possibilidade de home office planejado;
- Treinamentos na plataforma Alura;

## Nossa empresa

Somos uma corretora de imóveis jovem e dinâmica criada em 1995 com a missão de atender compradores, proprietários e incorporadores de imóveis da Zona Sul ao centro da cidade.

Aqui na Nova Aliança Imóveis, nossos clientes contam com profissionais atentos e dedicados prontos para atendê-los com os seguintes serviços de apoio aos negócios:

- Divulgação nos principais veículos de comunicação     
- Avaliação gratuita do preço de venda     
- Assessoria Jurídica     
- Serviços de Despachantes     
- Pós-vendas (registros e transferências)

## Como se candidatar

Se você se interessar, é só mandar CV para leandrobulkool@novaaliancaimoveis.com.br e colocar o cargo no assunto.

**Comment by rbezerra** [comment]
aceitam remoto?
