### ISSUE TITLE
[Remoto] Back-end Developer @ Neon

### ISSUE THREAD

**Issue by GuiDev08** [backend-br/vagas#9990]
## Nossa empresa
Neon é uma fintech brasileira, fundada em 2016, com missão de unir tecnologia e design para redesenhar e simplificar a experiência financeira das pessoas. Nascemos com um sonho grande, nosso objetivo é diminuir desigualdades, mostrando caminhos financeiros mais justos, porque todas as pessoas merecem um futuro brilhante.

## Descrição da vaga
A Neon está em busca de Pessoa Desenvolvedora Backend III para fazer um time incrível e de alta performance. 💙

Na Neon, acreditamos que ao trabalhar com um time diverso e inclusivo, somos capazes de criar produtos que atendam a todos, todas e todes e para isso buscamos contratar pessoas independente de gênero, raça, orientação sexual, idade ou deficiência.

Requisitos: 

Participar do refinamento técnico Implementação de features e melhorias;
Construção e evolução de Microserviços;
Trabalhar de maneira colaborativa com outras áreas;
Colocaboração com outros desenvolvedores da squad.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- .Net 5 e 6
- AWS
- EKS
- Docker
- Kubernetes
- Git
- Kafka
- Rabbit
- Redis
- MongoDB
- SQL Server
- Vault
- Modelagem e desenvolvimentos de API's
- Microsserviços
- Integração contínua (CI/CD)
- Modelos e cases de atuação com Observabilidade, Escalabilidade, Disponibilidade

**Diferenciais:**
- Atuação no segmento financeiro

## Benefícios

Aqui na Neon apoiamos e valorizamos nossos Neonwers, não apenas com excelentes benefícios, mas também pensando em bem-estar e desenvolvimento!

Para sua saúde, oferecemos assistência médica e odontológica - e se liga, você ainda poderá escolher o melhor plano para você e seus dependentes
Seguro de vida
Para seu bem-estar, o “Alô cafune” - nosso programa de apoio psicológico
Ama descontinhos? Oferecemos o Allya! Nele você encontra descontos em produtos e serviços variados
Tem filhos? Aqui temos auxílio creche ou babá
Pensando em carreira? Aqui você encontrará o Decola (nosso Programa de Recrutamento Interno), o nosso Ciclo de Avaliação semestral, rotinas de feedbacks e acompanhamento do seu plano de desenvolvimento, e muito mais

E mais um montão de opções de benefícios flexíveis para você distribuir da forma que mais combinar com seu estilo de vida! Entre eles estão:

Refeição/alimentação (para você se alimentar bem!)
Budget para cursos e treinamentos (para você ser cada vez mais talentoso!)
GymPass (para você se exercitar!)
Massagem (para você dar aquela relaxada!)
Mobilidade (para você ir e vir com tranquilidade!

## Contratação

CLT 14K

## Como se candidatar

Me chama no Whats +55 11 99220-6201 com o link do seu linkedin

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Sênior

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
