### ISSUE TITLE
Remote Senior Full Stack Engineer: Node, React, React Native and MongoDB

### ISSUE THREAD

**Issue by smarthoptechrecruiter** [backend-br/vagas#9991]
We are currently searching for a Senior Full Stack Engineer with experience in building large scale applications using Node.js, React, React Native and MongoDB to join our growing team.

SmartHop's powerful freight dispatching AI technology makes it easier and more profitable to run a trucking business. 

We just raised a $30 million Series B financing round, and with the fresh capital, we aim to focus more on our fintech products.

You would work hand in hand with our CTO Miguel Sucre from MIT and our VP of Engineering Aliaksei Patapau from Facebook. 

**Qualifications**: 6+ years of working experience in software development.
**Language**: English.
**Location**: 100% Remote.
**Availability**: Full-time schedule.
**Methodology**: Scrum. 

**Key Responsibilities**: 
> - Implement cloud based software components and user / system interfaces.
> - Develop software components and requirements on time.
> - Design software architecture and algorithms.
> - Consider non-functional requirements such as security, border cases and scalability.
> - Test and debug code.
> - Maintain source control process.
> - Deploy in development and production environments.

**Benefits**:
> - Unlimited paid time off.
> - Up-to-80-hrs sick leave.
> - Paid holidays.
> - Parental leave.
> - Training and development opportunities.
> - Employee referral program.
> - Computer.
> - And more...

Here’s all the info: https://jobs.lever.co/smarthop/d3ac6a1b-9793-4801-b36c-9e0502b36059. 

**Does this fit your profile?** I'd love to discuss the possibility of working together either now or in the future.
Please apply using the link above!

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
