### ISSUE TITLE
[São Paulo] Analista Programador Xharbour | Clipper @Global 

### ISSUE THREAD

**Issue by BruPsi** [backend-br/vagas#9996]
**Global Empregos em parceria com AlBriggs Empresa Ambiente S.A.**

**Tipo de contratação: CLT**
Salário: 4.000,00 + ajuda de custo (R$ 1.000,00)
Jabaquara, São Paulo - SP, Brasil
Escala: Segunda a Sexta-feira
Horários: Seg a sexta das 08 as 18h/ sexta das 08 as 17h

**Benefícios:**
Assistência médica
Assistência odontológica
Convênio farmácia
Seguro de vida
Vale-alimentação - R$ 132,00/mês
Vale-refeição - R$ 23,10/dia útil
Vale-transporte

**Formação Acadêmica:** 
Superior completo 

**Experiência Profissional Anterior:** 
Desejável experiência anterior nos pontos solicitados 
Conhecer linguagens de programação Clipper e Harbour
Desejável candidatos com conhecimento em SQL e ambiente Linux

**Responsabilidade do Cargo:**
Programar, codificar e testar o sistema
Executar a manutenção do sistema, fazendo eventuais correções necessárias, visando atender as necessidades dos clientes
Desenvolver trabalhos de montagem, depuração e testes de programas, executando serviços de manutenção nos programas já desenvolvidos

Contato através do whatsapp (11)97543-2612

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
