### ISSUE TITLE
[Remoto] Back-end Developer @ E-vo.tech

### ISSUE THREAD

**Issue by Paloma04** [backend-br/vagas#9997]
## Nossa empresa
Somos uma consultoria que trabalha com o mercado de startups, já apoiamos a construção de mais de 10 unicórnios. Vem com a gente nessa?

## Descrição da vaga
Estamos apoiando uma Fintech em fase de expansão nacional, com um produto voltado para apoiar a empresas a lidar com questões financeiras de maneira mais inteligente. É um projeto em Node, Typescript em AWS que no futuro será implementado novas tecnologias como Golang, Clojure e Datatomic.

## Local
Remoto

## Requisitos

**Obrigatórios:**
-Experiência com Python, Node ou Golang;
-Vivência com sistemas de mensageria (Kafka, RabbitMQ ou SQS/SNS);
-Monitoramento de disponibilidade e segurança de aplicações;
-Experiência com metodologias ágeis.

**Desejáveis:**
-Conhecimento sobre arquitetura (microserviços);
-Gestão de serviços em nuvem (AWS ou GCP);

## Benefícios

- Plano de saúde
- Férias Remuneradas 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para henzo@e-volve.in com seu CV anexado - enviar no assunto: Backend Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: paloma.rodrigues@e-volve.in

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior ou Especialista

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
