### ISSUE TITLE
[Remoto] Developer Mobile iOS @ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [backend-br/vagas#9998]
## Local

100% Remoto 
Full time em horário comercial

## Requisitos

Experiência em desenvolvimento mobile iOS, estando confortável em escrever aplicações em Swift;
Capaz de elaborar diversos tipos de layout, auxiliados por Auto Layout e/ou SwiftUI (sendo o UIKit bastante familiar), visando responsividade, reutilização de componentes, estilos e cores;
Pleno domínio em comunicação síncrona e assíncrona, tanto que norteia os conceitos e boas práticas, quanto na tecnologia em si (HTTP/HTTPS, RESTful, push notification, web socket etc.);
Ser capaz de desenvolver as diversas formas de testes (unitário e interface); 
Acessibilidade;
Conhecer e ter experiência nas diversas arquiteturas de solução propostas para aplicativos móveis (MVC, VIPER, MVVM etc.);
Conhecer profundamente os frameworks do ecossistema iOS, como Core Data, Core Animation, entre outros;
Já ter publicado apps na loja e ter acompanhado as estratégias de release (phasing rollout);
Familiarizado na investigação de problemas em aplicativos (guiados ou não por ferramentas de monitoramento);
Trabalhar com versionamento de código, preferencialmente Git.

Tecnologias utilizadas:
Principais linguagens utilizadas: Swift;			
Testes unitários e integrados;				
Persistência de Dados: Core Data;			
Boas práticas de código e técnicas de refatoração;				
Design patterns: GoF, KISS, DRY, SOLID;
Ferramentas de monitoração mobile;				
Arquitetura: Viper, MVVM;			
Experiência em subida de apps na loja oficial;			
Layouts Responsivos: Swift UI, XIB, Storyboards, Auto Layout;
Modularização;				
Versionamento de Código: Git			
Comunicação assíncrona: websocket, push notification			
Acessibilidade

## Atividades

Com o desafio de realizar a migração do codebase da tecnologia atual para nativo (Swift), utilizando-se das melhores práticas de código e priorizando o desenvolvimento de um produto de fácil manutenção, alta escalabilidade e com um olhar voltado à segurança, o profissional trabalhará em uma squad multidisciplinar (Negócios, UX/UI, QAs, DEVs e outras áreas afins) para atingir este desafio, mantendo, na medida do possível, a retrocompatibilidade com o ecossistema já existente.

Principais responsabilidades: Ser o guardião da qualidade de código e arquitetura proposta para o app;
Disseminar o conhecimento da plataforma e dos combinados técnicos e processuais;
Acompanhar, desenvolver e sustentar o aplicativo em todas as suas fases.

## Contratação

6 meses renováveis
Regime: PJ ou a combinar

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - iOS

## Labels

- Horário comercial (Full time)
- Remoto
- Pleno e Sênior
- PJ ou a combinar

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
