### ISSUE TITLE
[Remoto] Tech Lead (Python) na Qbem

### ISSUE THREAD

**Issue by blankapf** [backend-br/vagas#9999]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/tech-lead-python-222435040?utm_source=github&utm_medium=backend-br-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>QBem </strong>está buscando <strong><ins>Tech Lead (Python)</ins></strong><strong> </strong>para compor seu time!</p>
<p>A Qbem é uma empresa de inteligência digital em saúde corporativa, formada por uma "plataforma as a service"  que integra corretor, RH e beneficiário gerando soluções em gestão e automação de processos (RPA) para corretoras e consultorias de benefícios.&nbsp;</p>
<p>Entregando o diferencial de integração da gestão e dos dados dos benefícios para gestão da saúde corporativa em um só local. Possuimos uma Solução Multibenefícios (vida, saúde e odontológico), conexão com o beneficiário, segurança de dados LGPD e Plataforma de vendas.&nbsp;</p>
<p><strong>Responsabilidades e atividades:</strong></p>
<ul>
<li>Assuma a propriedade de todo o projeto, desde o requisito até o estágio de entrega final;</li>
<li>Responsável por fornecer experiência no ciclo de vida de desenvolvimento de software, desde o conceito, arquitetura, design, implementação e testes;</li>
<li>Liderar e orientar equipes de pequeno porte em um projeto;</li>
<li>Responsável por entender os requisitos e escrever documentos de arquitetura técnica dos clientes;</li>
<li>Forte foco na qualidade, reforçando as revisões de código e as melhores práticas/processos de desenvolvimento;</li>
<li>Responsável pelo planejamento do escopo técnico de ponta a ponta das áreas de projeto e engajamento do cliente, incluindo planejamento de sprint e entregas;</li>
<li>Liderar todas as chamadas de clientes e comunicação por e-mail;</li>
<li>Estima esforços, identifica riscos e fornece suporte técnico sempre que necessário;</li>
<li>Gerenciar uma pequena equipe de engenheiros;</li>
<li>Demonstra a capacidade de multitarefa e re-priorizar responsabilidades com base em requisitos dinâmicos.</li>
</ul>

## Qbem: 
 <p>A Qbem é uma empresa de inteligência digital em saúde corporativa, formada por uma "plataforma as a service"  que integra corretor, RH e beneficiário gerando soluções em gestão e automação de processos (RPA)  para corretoras e consultorias de benefícios.&nbsp;</p>
<p>Entregando o diferencial de integração da gestão e dos dados dos benefícios para gestão da saúde corporativa em um só local. Possuimos uma Solução Multibenefícios (vida, saúde e odontológico) , Conexão com o beneficiário , Segurança de dados LGPD, Plataforma de vendas.&nbsp;</p><a href='https://coodesh.com/empresas/qbem'>Veja mais no site</a>

 ## Habilidades: 
 - Python 
- Javascript 
- Linux
## Local: 
 100% Remoto
## Requisitos: 
 - Ampla experiência em arquitetura de software, design e desenvolvimento de sistemas; 
- Ampla experiência em desenvolvimento em programação Python; 
- Apaixonado por aprender novas tecnologias, domínios e frameworks; 
- Desejável boa experiência em tecnologias JavaScript; 
- Fortes fundamentos em Design Orientado a Objetos e Estruturas de Dados; 
- Experiência em trabalhar diretamente com clientes, o que inclui levantamento de requisitos iniciais, discussões técnicas diárias, demonstrações técnicas e entrega de projetos; 
- Experiência no desenvolvimento de Web services RESTful utilizando qualquer framework; 
- Experiência em trabalhar com metodologia ágil de desenvolvimento de software; 
- Experiência com programação Linux, ou expertise nas áreas de Big Data; 
- Experiência anterior na equipe de liderança/orientação; 
- Deve possuir excelentes habilidades orais, escritas, de resolução de problemas e analíticas; 
- Experiência no gerenciamento de vários projetos ao mesmo tempo; 
- Educação: Superior em na área de TI.
## Diferenciais: 
 - Conhecimento e prática em tecnologias web front-end como: HTML5, Javascript, CSS, AngularJS e Bootstrap; 
- Conhecimentis em Data Analytics é um diferencial.
## Benefícios: 
 - 100% Home Office; 
- Plano de Saúde.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead (Python) na Qbem](https://coodesh.com/vagas/tech-lead-python-222435040?utm_source=github&utm_medium=backend-br-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Gestão em TI

**Comment by gustavofreze** [comment]
Esta vaga foi fechada, pois encontra-se há um bom tempo sem novas interações.
